### PR TITLE
[sundials] Add klu feature

### PR DESCRIPTION
**Pull request by tlestang**
This PR adds a new `klu` feature for the sundials port. 

`KLU` is a sparse linear solver that comes with [SuiteSparse](https://people.engr.tamu.edu/davis/suitesparse.html), which is already available from vcpkg. See [the suitesparse port](https://github.com/microsoft/vcpkg/tree/master/ports/suitesparse). Additonally, the previous CONTROL file for the sundials port is updated to an equivalent `vcpkg.json` file, adding the klu feature.

To compile sundials with KLU enabled, CMake must be passed the location of the klu include and library files. Currently these paths are partially hardcoded in the portfile, for a lack of better way of doing this:
```cmake
set(KLU_INCLUDE_DIR ${CURRENT_PACKAGES_DIR}/../suitesparse_x64-windows/include/suitesparse)
set(KLU_LIBRARY_DIR ${CURRENT_PACKAGES_DIR}/../suitesparse_x64-windows/lib)
```
Ideally both variables should point to the suitesparse libs and headers (likely installed by vcpkg as a dependency) for the right triplet. What's the best way of doing this?

### CODE REVIEW

**Comment by JackBoosY** [comment]
@tlestang  Please sign CLA first.

Thanks.

**Comment by tlestang** [comment]
Thanks @JackBoosY . I have to check with my organisation first. I have a feeling this might take a while.

**Comment by JackBoosY** [comment]
Pinging @tlestang for response. Is work still being done for this PR?

**Comment by tlestang** [comment]
I'll come back to this in a month or so. Feel free to close this PR, I can open a new one whenever I have some time to finish this.
Thanks @JackBoosY

**Comment by FrankXie05** [comment]
@tlestang I found that your PR submitted upstream has been merged, is it reopened or the PR can work?

**Pull request closed without merging**
