### PR TITLE
 [wxwidgets] Fix absolute paths

### PR DESCRIPTION
**Pull request by dg0yt**
- #### What does your PR fix?
  Fixes https://github.com/microsoft/vcpkg/pull/24047#issuecomment-1102494282.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  unchanged, no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  yes

### CODE REVIEW

**Comment by dg0yt** [comment]
The downside of `file(GLOB ...)`: You don't notice wrong paths.

CC @autoantwort.

**Comment by autoantwort** [comment]
> You don't notice wrong paths.

Because of that I always use a custom build vcpkg-tool with https://github.com/microsoft/vcpkg-tool/pull/172

**Review by autoantwort — APPROVED** [review]

**Review by FrankXie05 — APPROVED** [review]

**Review by talregev — APPROVED** [review]
Run correctly on the ci

**Comment by strega-nil-ms** [comment]
Thank you @dg0yt!

**Pull request merged**
