### PR TITLE
[directxtex] update port with omp feature

### PR DESCRIPTION
**Pull request by walbourn**
The library has a build option for using OpenMP to make the software BC6H/BC7 codec use multiple cores. This feature has been on by default for some time, but there are some build contexts where I need to be able to disable it.

Therefore, this port adds an ``omp`` feature for controlling that build option, and this is a 'default' feature.

### CODE REVIEW

**Comment by JonLiu1993** [comment]
@walbourn, Thanks for your PR, According to my understanding, this PR is to change the existing feature omp from optional to default, right?

**Comment by JonLiu1993** [comment]
All features are tested successfully in the following triplet:
- x86-windows
- x64-windows
- x64-windows-static

**Review by JonLiu1993 — DISMISSED** [review]

**Comment by BillyONeal** [comment]
Hmmm it sounds like the feature being *off* enables more scenarios than the feature being on? I'm not sure if making this a feature is a great fit.

Let's say you are building port "a" that depends on "directxtex" like this:

```
"dependencies": ["directxtex"]
```

this will cause the feature to be on, because "a" depends on "directxtex[default]", so

```
vcpkg install directxtex[core] a
```

will still turn on the omp feature despite the `[core]` line trying to avoid that.

Should the feature be `no-omp` instead?

**Comment by BillyONeal** [comment]
Put another way, if you can ever have a requirement that a feature be *off*, that isn't really a feature. Everything about vcpkg's interaction with features assumes it is always safe to turn on more features.

**Comment by walbourn** [comment]
Honestly this is just for the really weird build environment of razzle where I need to be able to turn off OpenMP which I can do by disabling default features.

That said, I can also invert it to a `no-omp` feature if you feel it's a better design.

**Comment by walbourn** [comment]
Verified all supported triplets and features:

```
vcpkg install directxtex[core]:x86-windows
vcpkg install directxtex:x86-windows --recurse
vcpkg install directxtex[no-omp]:x86-windows --recurse
vcpkg install directxtex[tools]:x86-windows --recurse
vcpkg install directxtex[dx12]:x86-windows --recurse
vcpkg install directxtex[openexr,tools]:x86-windows --recurse
vcpkg install directxtex[spectre]:x86-windows --recurse
vcpkg install directxtex:x86-windows-static
vcpkg install directxtex:x86-windows-static-md

vcpkg install directxtex[core]:x64-windows
vcpkg install directxtex:x64-windows --recurse
vcpkg install directxtex[no-omp]:x64-windows --recurse
vcpkg install directxtex[tools]:x64-windows --recurse
vcpkg install directxtex[dx12]:x64-windows --recurse
vcpkg install directxtex[openexr,tools]:x64-windows --recurse
vcpkg install directxtex[spectre]:x64-windows --recurse
vcpkg install directxtex:x64-windows-static
vcpkg install directxtex:x64-windows-static-md

vcpkg install directxtex:arm-windows
vcpkg install directxtex[tools]:arm-windows --recurse
vcpkg install directxtex[spectre]:arm-windows --recurse

vcpkg install directxtex:arm64-windows
vcpkg install directxtex[tools]:arm64-windows --recurse 
vcpkg install directxtex[spectre]:arm64-windows --recurse
vcpkg install directxtex:arm64-windows-static
vcpkg install directxtex:arm64-windows-static-md

vcpkg install directxtex:x86-uwp
vcpkg install directxtex:x64-uwp
vcpkg install directxtex:arm-uwp
vcpkg install directxtex:arm64-uwp

vcpkg install directxtex:x64-xbox-scarlett
vcpkg install directxtex:x64-xbox-scarlett-static
vcpkg install directxtex:x64-xbox-xboxone
vcpkg install directxtex:x64-xbox-xboxone-static

./vcpkg install directxtex:x64-linux
./vcpkg install directxtex[dx12]:x64-linux --recurse
./vcpkg install directxtex[openexr]:x64-linux --recurse

./vcpkg install directxtex:arm64-linux
./vcpkg install directxtex[dx12]:arm64-linux --recurse
./vcpkg install directxtex[openexr]:arm64-linux --recurse

vcpkg install directxtex:x64-mingw-static
vcpkg install directxtex[dx12]:x64-mingw-static --recurse
vcpkg install directxtex[tools]:x64-mingw-static --recurse

vcpkg install directxtex:x86-mingw-static
vcpkg install directxtex[dx12]:x86-mingw-static --recurse
vcpkg install directxtex[tools]:x86-mingw-static --recurse
```

**Comment by BillyONeal** [comment]
> Honestly this is just for the really weird build environment of razzle where I need to be able to turn off OpenMP which I can do by disabling default features.

The problem is that you can't do that if anything in your entire package graph doesn't turn off default features.

Can we get information into here about the razzle environment that allows the port to respond appropriately without needing a feature? Razzle uses their own triplets right? They could set a variable and then the port could do:

```cmake
# The following setting is intended to be overridden in the triplet if necessary
if (NOT DEFINED BC_USE_OPENMP)
    set(BC_USE_OPENMP ON)
endif()

# ...

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS} -DBUILD_SAMPLE=OFF -DBUILD_TESTING=OFF "-DBC_USE_OPENMP=${BC_USE_OPENMP}"
)
```

**Comment by walbourn** [comment]
The problem is that the OS razzle build environment doesn't have support for OpenMP at all, and it's not indicated by anything. Having it be an inverted-feature is perfectly fine.

**Comment by BillyONeal** [comment]
> The problem is that the OS razzle build environment doesn't have support for OpenMP at all, and it's not indicated by anything. Having it be an inverted-feature is perfectly fine.

Sure, but doesn't that build environment need custom triplets anyway, that can tell ports that omp can't be used?

**Comment by walbourn** [comment]
There's no standard way to indicate that in a triplet. I'm using a custom build option for my CMake.

**Comment by BillyONeal** [comment]
Sure, I'm saying it doesn't need to be a standard thing. The triplet .cmake runs before portfile.cmake so any variables you set in there, portfile.cmake can listen to.

**Comment by walbourn** [comment]
The inverted feature is a perfectly valid choice for other scenarios, and achieves my goals without having to dig into the core of the OS VCPKG triplet system :)

**Comment by walbourn** [comment]
Again, in the context I'm trying to solve for I don't have control over the triplet.

The library has been using OpenMP by default for MSVC windows builds since it was first introduced, so using an inverted feature avoids changing existing behavior.

**Comment by Neumann-A** [comment]
> The library has been using OpenMP by default for MSVC windows builds since it was first introduced, so using an inverted feature avoids changing existing behavior.

that is not an argument.... vcpkg has `default-features`.

In your case an `omp` feature is better since you want to restrict it with a supports clause for whatever razzle is (and `default-features` will at some point support `supports`)

**Comment by Neumann-A** [comment]
The main reason to use `no-omp` instead of `omp` is the fact that `omp` will require `default-features=false` in all dependent downstream ports. However both cases require an explicit mentioning of the feature in the projects manifest.

**Comment by walbourn** [comment]
In 99.9% of cases, OpenMP should be used to build the BC6H/BC7 codec which is otherwise incredibly slow for all but trivial sized images. That's what I want to happy by default and even when you use: ``default-features: false``.

The *only* case where I need to be able to disable the OpenMP is in weird edge-case scenarios like a build environment that just happens to be missing the OpenMP header/lib support for MSVC which is when I'd use ``no-omp``.

**Comment by walbourn** [comment]
I need this to unblock me for now, but I'll see if I can come up with a better solution down the road that removes the need for a custom 'feature' like this.

**Pull request merged**
