### PR TITLE
[osgearth:x64-linux] Fix osg version not found in osgearth

### LINKED ISSUE #11614: [osgearth:x64-linux] Build failure in linux 64 bit: does not find osg version
**Host Environment**
- OS: Ubuntu 18.04
- Compiler: gcc 7.5.0

**To Reproduce**
`./vcpkg install osgearth`

**Failure logs** 
```
Building package osgearth[core]:x64-linux...
-- Note: osgearth only supports dynamic library linkage. Building dynamic library.
CMake Error at ports/osgearth/portfile.cmake:8 (message):
  Could not determine osg version
Call Stack (most recent call first):
  scripts/ports.cmake:90 (include)


Error: Building package osgearth:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: osgearth:x64-linux
  Vcpkg version: 2020.02.04-unknownhash

Additionally, attach any relevant sections from the log files above.
CMake Error at build/_pmm/1.9.4/vcpkg.cmake:232 (message):
  Failed to install requirements with vcpkg [1]:

Call Stack (most recent call first):
  build/_pmm/1.9.4/main.cmake:41 (_pmm_vcpkg)
  build/_pmm/1.9.4/main.cmake:57 (_pmm_project_fn)
  CMakeLists.txt:11 (PMM)


-- Configuring incomplete, errors occurred!
See also "/home/.../cpp/gpsop/build/CMakeFiles/CMakeOutput.log".
```

**Additional context**
Fixed copying `lib/osgPlugins-*` to `tools/osg` since it does not check the lib folder which I think should be better, should I make a pull request?

### PR DESCRIPTION
**Pull request by omaralvarez**
**Fix osg not found error in unix**

- What does your PR fix? Fixes #11614

### CODE REVIEW

**Comment by PhoebeHui** [comment]
@omaralvarez, thanks for the PR!

Could you pelase remove 'osgearth:x64-linux=fail' in scripts/ci.baseline.txt file? Also update Version to 2.10.2-2 in CONTROL file?

**Comment by omaralvarez** [comment]
Done! Although I think it fails due to OpenSSL. #10327

**Comment by PhoebeHui** [comment]
@omaralvarez, the x64-linux failed with following failure, could you pelase have a look?

lib/libosgEarthd.so.2.10.2: undefined reference to `X509_get_version'
lib/libosgEarthd.so.2.10.2: undefined reference to `SSL_CTX_set_keylog_callback'
lib/libosgEarthd.so.2.10.2: undefined reference to `BIO_s_file'
lib/libosgEarthd.so.2.10.2: undefined reference to `UI_get_string_type'
lib/libosgEarthd.so.2.10.2: undefined reference to `ENGINE_free'
lib/libosgEarthd.so.2.10.2: undefined reference to `ASN1_STRING_length'
lib/libosgEarthUtild.so.2.10.2: undefined reference to `FcPatternDestroy'
lib/libosgEarthd.so.2.10.2: undefined reference to `SSL_CTX_add_client_CA'
lib/libosgEarthd.so.2.10.2: undefined reference to `OPENSSL_load_builtin_modules'
lib/libosgEarthd.so.2.10.2: undefined reference to `X509_get_issuer_name'
lib/libosgEarthd.so.2.10.2: undefined reference to `ENGINE_ctrl'
...
[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/4763752/install-x64-linux-dbg-out.log)

**Comment by omaralvarez** [comment]
I think the problem is not in the osgEarth recipe, it has to do with the GDAL recipe. The only fix I can think of is using system package GDAL. Not sure on what to do...

**Comment by ASxa86** [comment]
#13101 

Will this resolve the other issues I've reported? I'm not seeing anything in here handle the fact that it only searches for *.exe files in the portfile.cmake. I wanted to verify as my issue was closed stating it was a duplicate and would be resolved by #11614 which linked me to this pull request.

**Comment by omaralvarez** [comment]
Your issue has to do with OpenSSL and is not fixed by this PR. This PR fixes an issue finding the OSG version due to missing .so files.

**Comment by ASxa86** [comment]
Okay. I guess I'll get my issue re-opened. To clarify. My issue called out the failure to find OSG Version, OpenSSL, AND the fact that osgearth will not build on linux due to the portfile.cmake looking for *.exe files. So I'd be very curious to see how this pull request passes without resolving the issues I called out in #13101.

**Comment by strega-nil** [comment]
@omaralvarez are you still interested in finishing this PR, or should we close? If you're still interested, please merge with master and let's look again at what we need to solve.

**Comment by BillyONeal** [comment]
I'm closing this PR due to inactivity; please feel free to create a new one if you're still interested in continuing here.

**Pull request closed without merging**
