### PR TITLE
[daxa]Update Daxa to 2.0.0

### PR DESCRIPTION
**Pull request by GabeRundlett**
If this PR updates an existing port, please uncomment and fill out this checklist:

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by Adela0814** [comment]
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

**Comment by GabeRundlett** [comment]
Daxa requires Vulkan >=1.3, and the Vulkan SDK version installed on that machine is `1.2.198.1`. The Vulkan package from vcpkg doesn't have a way of specifying this it seems. What can be done about that?

**Comment by Adela0814** [comment]
When I installed `daxa`, I received a message requesting to install `Vukan` first. I installed the latest version of Vukan, but the error message was that couldn't find `Vukan`(version 1.2.198.1). So I reinstalled the specified version(1.2.198.1) and encountered the above error. 
It is worth mentioning that after manually installing the `vukan-header` port, the above error will no longer appear. Since `daxa` requires `Vukan`, can you set `vukan-header` as a dependency?

**Comment by Adela0814** [comment]
Please move the following options to `MAYBE_UNUSED_VARIABLES`. Thanks.
```
The following variables are not used in CMakeLists.txt:

      CMAKE_REQUIRE_FIND_PACKAGE_WAYLAND
      CMAKE_REQUIRE_FIND_PACKAGE_X11

  Please recheck them and remove the unnecessary options from the
  `vcpkg_cmake_configure` call.

  If these options should still be passed for whatever reason, please use the
  `MAYBE_UNUSED_VARIABLES` argument.
```

**Comment by Adela0814** [comment]
All feature tested pass on the following triplets:
```
x64-windows
x64-windows-static
```
Usage tested pass on `x64-windows`.

**Comment by GabeRundlett** [comment]
Is it normal that this check has been running for 8 hours?

**Comment by GabeRundlett** [comment]
it's still going...

**Review by Adela0814 — APPROVED** [review]

**Pull request merged**
