### PR TITLE
[libcoap] add new port

### PR DESCRIPTION
**Pull request by mathisloge**
**Describe the pull request**

Currently waiting for a new release, since the installation of the tools aren't part of the current release.

- #### What does your PR fix?
adds libcoap https://github.com/obgm/libcoap

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by mathisloge** [comment]
I think I need to provide add some fixes for upstream generated configs.

**Comment by mathisloge** [comment]
`find_package(libcoap CONFIG REQUIRED)` and linkage tested ✅

**Comment by PhoebeHui** [comment]
@mathisloge, feel free to ping us if the PR ready for review.

**Comment by Adela0814** [comment]
Closing this PR since it seems that no progress is being made. Please reopen if work is still being done.

**Pull request closed without merging**
