### PR TITLE
hdf5

### LINKED ISSUE #384: Add HDF5
Website: https://support.hdfgroup.org/HDF5/

Required for #294.

### PR DESCRIPTION
**Pull request by albertziegenhagel**
Adds a port for HDF5

fixes #384

Requires #518 and #515 to be merged first

### CODE REVIEW

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by Remotion** [comment]
One question why is  HDF5_BUILD_CPP_LIB  "Build HDF5 C++ Library" set to OFF ?

**Comment by albertziegenhagel** [comment]
The reason for this is that the options "HDF5_ENABLE_PARALLEL" and "HDF5_BUILD_CPP_LIB" are mutually exclusive. And from my experience using the C interface with MPI enabled is far more common than using the C++ interface. Even in C++ projects.

**Comment by alexkaratarakis** [comment]
Thanks!
I added the `PREFER_NINJA` option to build with `ninja` for faster builds.

**Pull request merged**
