### PR TITLE
[llvm] Update the version to 9.0.0

### PR DESCRIPTION
**Pull request by NancyLi1013**
Update to 9.0.0

Related issue #8463

No feature need to test.

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by NancyLi1013** [comment]
It seems that the failures on `x64-windows` and `x64-windows-static` are due to:
```
CMake Error at lib/IRReader/cmake_install.cmake:36 (file):
  file INSTALL cannot copy file
  "C:/vsts/_work/2/s/buildtrees/llvm/x64-windows-static-rel/lib/LLVMIRReader.lib"
  to
  "C:/vsts/_work/2/s/packages/llvm_x64-windows-static/lib/LLVMIRReader.lib".
Call Stack (most recent call first):
  lib/cmake_install.cmake:39 (include)
  cmake_install.cmake:56 (include)
```
It cannot be reproduced this issue on my local. So I don't know what happened on CI.

**Comment by cloudrex** [comment]
This may be because the `LLVMIRReader` library fails to compile, and thus the file cannot be found. There's always an issue with Windows & LLVM. Any updates on this?

**Comment by NancyLi1013** [comment]
Hi @cloudrex  thanks for your comments. I have checked the code in `lib/IRReader` folder and found that there is something different in `IRReader.cpp` file between 9.0.0 and 8.0.0.
In 8.0.0
```
static std::unique_ptr<Module>
getLazyIRModule(std::unique_ptr<MemoryBuffer> Buffer, SMDiagnostic &Err,
                LLVMContext &Context, bool ShouldLazyLoadMetadata)
```
In 9.0.0

```
std::unique_ptr<Module>
llvm::getLazyIRModule(std::unique_ptr<MemoryBuffer> Buffer, SMDiagnostic &Err,
                      LLVMContext &Context, bool ShouldLazyLoadMetadata)
```

But it seems that this change is not related to this issue.

I also checked the log and found that `LLVMIRReader.lib` has been generated successfully.

`[526/2795] cmd.exe /C "cd . && C:\VS2017\Stable\VC\Tools\MSVC\14.22.27905\bin\Hostx64\x64\link.exe /lib  /machine:x64 /out:lib\LLVMIRReader.lib lib\IRReader\CMakeFiles\LLVMIRReader.dir\IRReader.cpp.obj  && cd ."`

It is also installed here 
```
C:/vsts/_work/2/s/packages/llvm_x64-windows-static/debug/tools/llvm/llvm-tblgen.exe
-- Installing: C:/vsts/_work/2/s/packages/llvm_x64-windows-static/debug/lib/LLVMCore.lib
-- Installing: C:/vsts/_work/2/s/packages/llvm_x64-windows-static/debug/lib/LLVMFuzzMutate.lib
-- Installing: C:/vsts/_work/2/s/packages/llvm_x64-windows-static/debug/lib/LLVMIRReader.lib
-- Installing: C:/vsts/_work/2/s/packages/llvm_x64-windows-static/debug/lib/LLVMCodeGen.lib
-- Installing: C:/vsts/_work/2/s/packages/llvm_x64-windows-static/debug/lib/LLVMSelectionDAG.lib
-- Installing: C:/vsts/_work/2/s/packages/llvm_x64-windows-static/debug/lib/LLVMAsmPrinter.lib
-- Installing: C:/vsts/_work/2/s/packages/llvm_x64-windows-static/debug/lib/LLVMMIRParser.lib
```
I have tested more than twice on my local and I still cannot reproduce it. So I don't know how to solve this issue now.

Thanks again for your attention.

**Comment by cloudrex** [comment]
Could anyone chime in to help solve the issue?

**Comment by JackBoosY** [comment]
Additional library and tool paths for llvm need to be reconfigured in cmakelists.txt.

**Comment by cloudrex** [comment]
I'm trying to see the build details but it says build not found...

**Comment by JackBoosY** [comment]
Please see vcpkg-windows-PR-test,  the vcpkg-windows-PR has been removed.

**Comment by tan-wei** [comment]
So is it ready to be merged? Thanks!

**Comment by NancyLi1013** [comment]
There is still something to be go further investigation.
So it can't be merged now.

**Comment by tan-wei** [comment]
> 
> 
> There is still something to be go further investigation.
> So it can't be merged now.

Thanks.

**Comment by NancyLi1013** [comment]
@tan-wei 
Thanks for your update.
Since you have updated to 10.0.0 in #10295, this PR can be closed now.

**Pull request closed without merging**
