### PR TITLE
[flashlight-cpu] Update port to v0.3

### PR DESCRIPTION
**Pull request by jacobkahn**
Updates to Flashlight v0.3 (release https://github.com/flashlight/flashlight/releases/tag/v0.3).

Tested on Ubuntu and CentOS with gcc 7 (min compiler supported)

- #### Which triplets are supported/not supported? Have you updated the [CI baseline]

Same triplet support as before - no changes.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  

Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  

Yes

### CODE REVIEW

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
Hi @jacobkahn 

Thanks for updating this port.

Have you tested these features in this PR?

**Comment by jacobkahn** [comment]
@NancyLi1013 I have tested all of the features of the port, yes 👍

**Comment by ras0219-msft** [comment]
Awesome, thanks for the great library and update!

**Pull request merged**
