### PR TITLE
[OpenCV] update to v4.5.4 and v3.4.16

### LINKED ISSUE #12621: OpenCV 4.3.0 No HighGUI/GTK support on Linux
**Host Environment**
- OS: Linux
- Compiler: g++-10/clang++-10

**To Reproduce**
`./vcpkg install opencv4`

OpenCV 4.3 will build perfectly on Linux and link as well _but_ when I try and use the `cv::imshow` function, I get a message that the library was not compiled with GUI support. Because I'm on Linux, it mentions installing libgtk-2.0 which I have installed alongside pkg-config.

I worked around this issue by manually updating the portfile to set: `WITH_GTK=ON` and now it seems like it Just Works.

### LINKED ISSUE #20991: install opencv2[cuda * * * ] fails with error:   Unsupported gpu architecture 'compute_30'
**Describe the bug:**
When installing opencv2[cuda,eigen,ffmpeg,jasper,jpeg,openexr,opengl,png,qt,tiff,world] on windows 10 home with CUDA  11.4, installed,  the install fails with this message in the log file:  
> nvcc fatal   : Unsupported gpu architecture 'compute_30'

**Environment**
- OS: 10.0.19042 N/A Build 19042
- Visual Studio 2019
- Compiler: Version 19.29.30136
- install option: x64-windows
- cpu: R9 5900X,
- gpu: RTX 3080
- cuda version: V11.4.120
- powershell

**To Reproduce**
>  .\vcpkg.exe install opencv2[cuda,eigen,ffmpeg,jasper,jpeg,openexr,opengl,png,qt,tiff,world]

**Expected behavior**
The install should be completed, with all the targeted packages installed.

**The actual outcome**
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):

**What did get installed before the failure:

- This was the first install in a just cloned vcpkg folder.  
- It looks like opencv2 did not get installed, but most other packages did get installed.

```
PS C:\vcpkg> .\vcpkg.exe list
brotli:x64-windows                                 1.0.9#2          a generic-purpose lossless compression algorithm...
bzip2:x64-windows                                  1.0.8#2          bzip2 is a freely available, patent free, high-q...
cuda:x64-windows                                   10.1#8           A parallel computing platform and programming model
double-conversion:x64-windows                      3.1.5#1          Efficient binary-decimal and decimal-binary conv...
egl-registry:x64-windows                           2020-02-20#1     the EGL API and Extension Registry
eigen3:x64-windows                                 3.3.9#1          C++ template library for linear algebra: matrice...
ffmpeg:x64-windows                                 4.4#15           a library to decode, encode, transcode, mux, dem...
ffmpeg[avcodec]:x64-windows                                         Build the avcodec library
ffmpeg[avdevice]:x64-windows                                        Build the avdevice library
ffmpeg[avfilter]:x64-windows                                        Build the avfilter library
ffmpeg[avformat]:x64-windows                                        Build the avformat library
ffmpeg[swresample]:x64-windows                                      Build the swresample library
ffmpeg[swscale]:x64-windows                                         Build the swscale library
freeglut:x64-windows                               3.2.1#6          Open source implementation of GLUT with source a...
freetype:x64-windows                               2.11.0#1         A library to render fonts.
freetype[brotli]:x64-windows                                        Support decompression of WOFF2 streams
freetype[bzip2]:x64-windows                                         Support bzip2 compressed fonts.
freetype[png]:x64-windows                                           Support PNG compressed OpenType embedded bitmaps.
freetype[zlib]:x64-windows                                          Use zlib instead of internal library for DEFLATE
harfbuzz:x64-windows                               3.0.0            HarfBuzz OpenType text shaping engine
icu:x64-windows                                    69.1#15          Mature and widely used Unicode and localization ...
jasper:x64-windows                                 2.0.33           Open source implementation of the JPEG-2000 Part...
libjpeg-turbo:x64-windows                          2.0.6#2          libjpeg-turbo is a JPEG image codec that uses SI...
liblzma:x64-windows                                5.2.5#3          Compression library with an API similar to that ...
libpng:x64-windows                                 1.6.37#15        libpng is a library implementing an interface fo...
openexr:x64-windows                                2.5.0#3          OpenEXR is a high dynamic-range (HDR) image file...
opengl:x64-windows                                 0.0#9            Open Graphics Library (OpenGL)[3][4][5] is a cro...
openssl:x64-windows                                1.1.1l#2         OpenSSL is an open source project that provides ...
pcre2:x64-windows                                  10.37            PCRE2 is a re-working of the original Perl Compa...
qt5-base:x64-windows                               5.15.2#11        Qt5 Application Framework Base Module. Includes ...
sqlite3:x64-windows                                3.36.0#1         SQLite is a software library that implements a s...
tiff:x64-windows                                   4.3.0#2          A library that supports the manipulation of TIFF...
tiff[jpeg]:x64-windows                                              Support JPEG compression in TIFF image files
tiff[lzma]:x64-windows                                              Support LZMA compression in TIFF image files
tiff[zip]:x64-windows                                               Support ZIP/deflate compression in TIFF image files
vcpkg-cmake-config:x64-windows                     2021-09-27
vcpkg-cmake:x64-windows                            2021-09-13
vcpkg-pkgconfig-get-modules:x64-windows            2021-04-02#1
zlib:x64-windows                                   1.2.11#13        A compression library
zstd:x64-windows                                   1.5.0            Zstandard - Fast real-time compression algorithm
```

**Console output**
```
Starting package 28/28: opencv2:x64-windows
Building package opencv2[core,cuda,eigen,ffmpeg,jasper,jpeg,openexr,opengl,png,qt,tiff,world]:x64-windows...
-- Downloading https://github.com/opencv/opencv/archive/2.4.13.7.tar.gz -> opencv-opencv-2.4.13.7.tar.gz...
-- Extracting source C:/vcpkg/downloads/opencv-opencv-2.4.13.7.tar.gz
-- Applying patch 0002-install-options.patch
-- Applying patch 0003-force-package-requirements.patch
-- Applying patch 0004-add-ffmpeg-missing-defines.patch
-- Applying patch 0005-fix-cuda.patch
-- Using source at C:/vcpkg/buildtrees/opencv2/src/2.4.13.7-64eb3208d2.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j25
    Working Directory: C:/vcpkg/buildtrees/opencv2/x64-windows-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\opencv2\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:102 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/opencv2/portfile.cmake:98 (vcpkg_cmake_install)
  scripts/ports.cmake:142 (include)


Error: Building package opencv2:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opencv2:x64-windows
  Vcpkg version: 2021-09-10-2059ef11aa6067e6f59b0d939c5d17e3c5c47d3e

Additionally, attach any relevant sections from the log files above.
```

**Failure logs:**
from: install-x64-windows-dbg-out.log
```
[1/546] cmd.exe /C "cd /D C:\vcpkg\buildtrees\opencv2\x64-windows-dbg\modules\core\CMakeFiles\cuda_compile_1.dir\__\dynamicuda\src\cuda && "C:\Program Files\CMake\bin\cmake.exe" -E make_directory C:/vcpkg/buildtrees/opencv2/x64-windows-dbg/modules/core/CMakeFiles/cuda_compile_1.dir/__/dynamicuda/src/cuda/. && "C:\Program Files\CMake\bin\cmake.exe" -D verbose:BOOL=OFF -D build_configuration:STRING=Debug -D generated_file:STRING=C:/vcpkg/buildtrees/opencv2/x64-windows-dbg/modules/core/CMakeFiles/cuda_compile_1.dir/__/dynamicuda/src/cuda/./cuda_compile_1_generated_matrix_operations.cu.obj -D generated_cubin_file:STRING=C:/vcpkg/buildtrees/opencv2/x64-windows-dbg/modules/core/CMakeFiles/cuda_compile_1.dir/__/dynamicuda/src/cuda/./cuda_compile_1_generated_matrix_operations.cu.obj.cubin.txt -P C:/vcpkg/buildtrees/opencv2/x64-windows-dbg/modules/core/CMakeFiles/cuda_compile_1.dir/__/dynamicuda/src/cuda/cuda_compile_1_generated_matrix_operations.cu.obj.Debug.cmake"
FAILED: modules/core/CMakeFiles/cuda_compile_1.dir/__/dynamicuda/src/cuda/cuda_compile_1_generated_matrix_operations.cu.obj C:/vcpkg/buildtrees/opencv2/x64-windows-dbg/modules/core/CMakeFiles/cuda_compile_1.dir/__/dynamicuda/src/cuda/cuda_compile_1_generated_matrix_operations.cu.obj 
cmd.exe /C "cd /D C:\vcpkg\buildtrees\opencv2\x64-windows-dbg\modules\core\CMakeFiles\cuda_compile_1.dir\__\dynamicuda\src\cuda && "C:\Program Files\CMake\bin\cmake.exe" -E make_directory C:/vcpkg/buildtrees/opencv2/x64-windows-dbg/modules/core/CMakeFiles/cuda_compile_1.dir/__/dynamicuda/src/cuda/. && "C:\Program Files\CMake\bin\cmake.exe" -D verbose:BOOL=OFF -D build_configuration:STRING=Debug -D generated_file:STRING=C:/vcpkg/buildtrees/opencv2/x64-windows-dbg/modules/core/CMakeFiles/cuda_compile_1.dir/__/dynamicuda/src/cuda/./cuda_compile_1_generated_matrix_operations.cu.obj -D generated_cubin_file:STRING=C:/vcpkg/buildtrees/opencv2/x64-windows-dbg/modules/core/CMakeFiles/cuda_compile_1.dir/__/dynamicuda/src/cuda/./cuda_compile_1_generated_matrix_operations.cu.obj.cubin.txt -P C:/vcpkg/buildtrees/opencv2/x64-windows-dbg/modules/core/CMakeFiles/cuda_compile_1.dir/__/dynamicuda/src/cuda/cuda_compile_1_generated_matrix_operations.cu.obj.Debug.cmake"
nvcc fatal   : Unsupported gpu architecture 'compute_30'
CMake Error at cuda_compile_1_generated_matrix_operations.cu.obj.Debug.cmake:220 (message):
  Error generating
  C:/vcpkg/buildtrees/opencv2/x64-windows-dbg/modules/core/CMakeFiles/cuda_compile_1.dir/__/dynamicuda/src/cuda/./cuda_compile_1_generated_matrix_operations.cu.obj


[2/546] cmd.exe /C "cd /D C:\vcpkg\buildtrees\opencv2\x64-windows-dbg\modules\highgui && "C:\Program Files\CMake\bin\cmake.exe" -E cmake_autogen C:/vcpkg/buildtrees/opencv2/x64-windows-dbg/modules/highgui/CMakeFiles/opencv_highgui_autogen.dir/AutogenInfo.json Debug && "C:\Program Files\CMake\bin\cmake.exe" -E touch C:/vcpkg/buildtrees/opencv2/x64-windows-dbg/modules/highgui/opencv_highgui_autogen/timestamp && "C:\Program Files\CMake\bin\cmake.exe" -E cmake_transform_depfile Ninja gccdepfile C:/vcpkg/buildtrees/opencv2/src/2.4.13.7-64eb3208d2.clean C:/vcpkg/buildtrees/opencv2/src/2.4.13.7-64eb3208d2.clean/modules/highgui C:/vcpkg/buildtrees/opencv2/x64-windows-dbg C:/vcpkg/buildtrees/opencv2/x64-windows-dbg/modules/highgui C:/vcpkg/buildtrees/opencv2/x64-windows-dbg/modules/highgui/opencv_highgui_autogen/deps C:/vcpkg/buildtrees/opencv2/x64-windows-dbg/CMakeFiles/d/96907176fc92cb7c6f4b88b92bd4963a777599b51031e9924eea198598cb16df.d"
ninja: build stopped: subcommand failed.
```

**What I found:**
The problem and fix seem to be described on stackoverflow  [link](https://stackoverflow.com/questions/64774548/unsupported-gpu-architecture-compute-30-on-a-cuda-5-capable-gpu).

### PR DESCRIPTION
**Pull request by cenit**
fixes: #12621
fixes: #20991

### CODE REVIEW

**Comment by cenit** [comment]
no change at all, still qt5.
Also, it was working in the first push here, got broken after a parallel non-qt related commit... might it be CI cache problems? 😢

**Comment by dg0yt** [comment]
> no change at all, still qt5.

But x64-linux says:

~~~
--   GUI:                           QT6
--     QT:                          YES (ver 6.2.0 )
--       QT OpenGL support:         YES (Qt6::OpenGL )
~~~

**Comment by Neumann-A** [comment]
Looked into the src. You nerd to patch it to unconditionally search for/use qt5. Currently it searches gor qt6 then qt5 snd then qt4.

**Review by JonLiu1993 — CHANGES_REQUESTED** [review]

**Comment by cenit** [comment]
PR is fine, CI has some problems.
will merge with master later, or if anyone wants to trigger an /azp run

**Comment by PhoebeHui** [comment]
```
Failure to remove_all_inside("D:\buildtrees") due to file "D:\buildtrees\gdal\src\4abe53c876-5b20fd3ee5.clean\autotest\gdrivers\data\sentinel2\fake_l2a_MSIL2Ap\S2A_MSIL2A_20170823T094031_N0205_R036_T34VFJ_20170823T094252.SAFE\GRANULE\L2A_T34VFJ_A011330_20170823T094252\IMG_DATA\R10m": The directory is not empty.
##[error]vcpkg clean failed
```

I will take a look.

**Review by JonLiu1993 — APPROVED** [review]

**Review by JonLiu1993 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Hi there! Your description says it depends on 20654, but 20654 is broken because it needs changes to the test VMs, but this one passes. Is it indeed a dependency our CI system isn't detecting or is something else going on?

**Comment by cenit** [comment]
it is based on an older commit of that PR, in which a gtk module is disabled (enabling it requires vm update)

**Comment by BillyONeal** [comment]
> it is based on an older commit of that PR, in which a gtk module is disabled (enabling it requires vm update)

Sorry, to clarify, I'm still not sure whether that means we should wait for that one before merging this or not.

**Comment by Neumann-A** [comment]
> Sorry, to clarify, I'm still not sure whether that means we should wait for that one before merging this or not.

This PR has to wait until linux vms are updated. Furthermore this PR should back out the changes to gtk making xdamage optional if upstream made the decision to make it mandatory as mentioned in the other PR.

**Comment by BillyONeal** [comment]
Thanks for the clarification :)

**Comment by cenit** [comment]
now that VM images have been updated, I merged with master and merged with latest commits in berry/gtk4.4

It should build again cleanly, and be ready for merging

**Comment by cenit** [comment]
don't know what happened here.
I'd also would like to offer as much help as possible to make this PR merged, since it's becoming old

**Comment by BillyONeal** [comment]
Looks like Azure Spot ate the Linux VM. I wish ADO was smarter about requeueing in such cases

**Comment by cenit** [comment]
> Looks like Azure Spot ate the Linux VM. I wish ADO was smarter about requeueing in such cases

thanks for the explanation. ADO is Azure DevOps in your case? How far is not being smart enough just a "call" and a "sprint" away from reality?

**Comment by BillyONeal** [comment]
> ADO is Azure DevOps in your case?

Yes.

> How far is not being smart enough just a "call" and a "sprint" away from reality?

Don't know what you mean by this. The scale set agents feature we use we've been using since March 2020 and they haven't added anything special for Spot in that time so I wouldn't hold our breath

**Comment by cenit** [comment]
> Don't know what you mean by this.

how much influence other teams might have in deciding sprints in azo agile development ;)
your use case is pretty much standard, if it does not work very well already it might deserve a call, maybe you get heard more than outsiders :)

**Comment by cenit** [comment]
@BillyONeal any news here? also the PR on which this is depending is waiting for a very long time now (and is ready too...)

**Comment by BillyONeal** [comment]
> how much influence other ms teams might have in deciding sprints in ado agile development ;) your use case is pretty much standard, if it does not work very well already it might deserve a call, maybe you get heard more than outsiders :)

Well they have an answer to make it reliable: don't cheap out on your VMs. We have chosen to accept some level of random failures in exchange for paying about half and this is what happens there. :)

> @BillyONeal any news here?

This PR was still marked as depending on the other one so we haven't been looking.

> also the PR on which this is depending is waiting for a very long time now (and is ready too...)

Yeah it looks like upstream has been notified there. After that lands do you have anything else you need to do before this one is ready?

**Comment by BillyONeal** [comment]
Since it looks like this PR had the contents of the other one I resolved conflicts in favor of https://github.com/microsoft/vcpkg/pull/20654 .

Please confirm that you don't want to do anything else?

**Comment by cenit** [comment]
confirmed, pr is ready since a long time ago

i moved the control to manifest just to trigger a rebuild on osx by myself (it failed for unknown reasons before)

**Review by JackBoosY — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the updates!

**Pull request merged**
