### PR TITLE
[cmocka] Add new port (fix #4728)

### LINKED ISSUE #4728: Add cmocka
Please, consider adding a port of cmocka to vcpkg.

cmocka is "an elegant unit testing framework for C with support for mock objects. It only requires the standard C library, works on a range of computing platforms (including embedded) and with different compilers."

Home: https://cmocka.org/
Git: git://git.cryptomilk.org/projects/cmocka.git
Releases: https://cmocka.org/files/

### PR DESCRIPTION
**Pull request by myd7349**
Fix #4728 

Test project: https://github.com/myd7349/Ongoing-Study/tree/master/cpp/CMake/vcpkg/cmocka_tests

Tested with:

- x86-windows
- x86-windows-static
- x64-windows
- x64-windows-static
- x64-linux

### CODE REVIEW

**Comment by Rastaban** [comment]
I see this building on all ports.  Let us know when you finish your own testing.

**Comment by myd7349** [comment]
Sure!

**Comment by myd7349** [comment]
Known issue: ${CMOCKA_LIBRARIES} only contains a optimized version of lib file.

**Comment by cryptomilk** [comment]
I've released cmocka 1.1.5.

**Comment by myd7349** [comment]
As @cryptomilk has no time to handle this PR: https://gitlab.com/cmocka/cmocka/merge_requests/9#note_158565619 yet, I am not able to remove those patches used in this port.
I think it is time to move on. So I will remove the `WIP` tag.

**Pull request merged**
