### PR TITLE
[geotrans] Modify incorrect version in CONTROL

### PR DESCRIPTION
**Pull request by LilyWangL**
**Describe the pull request**
Upgrade geotrans to version 3.8. No features need to test.
- What does your PR fix? Fixes issue #10150

### CODE REVIEW

**Comment by LilyWangL** [comment]
The windows and Linux CI test machines can’t access the address with the following failure, it works on osx test machines and I can download the source locally. Does keep the version 3.7 temporarily? Could you help have a look? @strega-nil 
```
-- Downloading ftp://ftp.nga.mil/pub2/gandg/website/wgs84/apps/geotrans/current-version/sw/dev_version/win_dev.zip...
-- Downloading ftp://ftp.nga.mil/pub2/gandg/website/wgs84/apps/geotrans/current-version/sw/dev_version/win_dev.zip... Failed. Status: 28;"Timeout was reached"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):
      
      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues
```

**Comment by LilyWangL** [comment]
@dan-shaw Can you take a look?

**Comment by LilyWangL** [comment]
> The windows and Linux CI test machines can’t access the address with the following failure, it works on osx test machines and I can download the source locally. Does keep the version 3.7 temporarily? Could you help have a look? @strega-nil
> 
> ```
> -- Downloading ftp://ftp.nga.mil/pub2/gandg/website/wgs84/apps/geotrans/current-version/sw/dev_version/win_dev.zip...
> -- Downloading ftp://ftp.nga.mil/pub2/gandg/website/wgs84/apps/geotrans/current-version/sw/dev_version/win_dev.zip... Failed. Status: 28;"Timeout was reached"
> CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):
>       
>       Failed to download file.
>       If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
>       variables to "https://user:password@your-proxy-ip-address:port/".
>       Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues
> ```

@dan-shaw Can you take a look?

**Comment by dan-shaw** [comment]
@LilyWangL I'm not sure why the CI has a timeout error. Maybe we can change the Control file to version 3.7 instead and fix the immediate issue?

**Comment by LilyWangL** [comment]
> @LilyWangL I'm not sure why the CI has a timeout error. Maybe we can change the Control file to version 3.7 instead and fix the immediate issue?

Thanks for your reply. Done.

**Review by NancyLi1013 — APPROVED** [review]

**Pull request merged**
