### PR TITLE
[opencascade] Update version to 7.7.2

### LINKED ISSUE #33155: [opencascade] update to 7.7.2
### Library name

opencascade

### New version number

7.7.2

### Other information that may be useful (release notes, etc...)

Blog announcement: https://dev.opencascade.org/content/open-cascade-technology-772-maintenance-release  
Release tag: https://git.dev.opencascade.org/gitweb/?p=occt.git;a=shortlog;h=refs/heads/OCCT-772

### PR DESCRIPTION
**Pull request by FrankXie05**
Fix https://github.com/microsoft/vcpkg/issues/33155 https://github.com/microsoft/vcpkg/issues/27896

All features are tested successfully in the following triplet:

- x86-windows
- x64-windows
- x64-windows-stataic

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by FrankXie05** [comment]
Waiting `fontconfig`. 🫤 

```
error: Failed to download from mirror set
error: https://gitlab.freedesktop.org/fontconfig/fontconfig/-/archive/2.14.2/fontconfig-2.14.2.tar.gz: curl fail      ed to download with exit code 22
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

curl: (22) The requested URL returned error: 504
```

**Comment by FrankXie05** [comment]
```
FAILED: lin64/gcc/bind/ExpToCasExe-7.7.2 
: && /usr/bin/c++ -fPIC -fexceptions -fPIC -Wall -Wextra -g -rdynamic src/ExpToCasExe/CMakeFiles/ExpToCasExe.dir/lex.exptocas.cxx.o src/ExpToCasExe/CMakeFiles/ExpToCasExe.dir/exptocas.tab.cxx.o src/ExpToCasExe/CMakeFiles/ExpToCasExe.dir/ExpToCasExe.cxx.o -o lin64/gcc/bind/ExpToCasExe-7.7.2  lin64/gcc/libd/libTKernel.a  lin64/gcc/libd/libTKExpress.a && :
/usr/bin/ld: lin64/gcc/libd/libTKExpress.a(Express.cxx.o): in function `Express::WriteFileStamp(std::ostream&)':
/mnt/vcpkg-ci/buildtrees/opencascade/src/9e8dfa85e2-cfb9860284.clean/src/Express/Express.cxx:44: undefined reference to `OSD_Process::OSD_Process()'
/usr/bin/ld: /mnt/vcpkg-ci/buildtrees/opencascade/src/9e8dfa85e2-cfb9860284.clean/src/Express/Express.cxx:45: undefined reference to `OSD_Process::SystemDate()'
/usr/bin/ld: /mnt/vcpkg-ci/buildtrees/opencascade/src/9e8dfa85e2-cfb9860284.clean/src/Express/Express.cxx:46: undefined reference to `OSD_Environment::OSD_Environment(TCollection_AsciiString const&)'
/usr/bin/ld: /mnt/vcpkg-ci/buildtrees/opencascade/src/9e8dfa85e2-cfb9860284.clean/src/Express/Express.cxx:47: undefined reference to `OSD_Environment::Value()'
/usr/bin/ld: /mnt/vcpkg-ci/buildtrees/opencascade/src/9e8dfa85e2-cfb9860284.clean/src/Express/Express.cxx:58: undefined reference to `OSD_Process::UserName()'
/usr/bin/ld: lin64/gcc/libd/libTKExpress.a(Express_Entity.cxx.o): in function `Express_Entity::GenerateClass() const':
/mnt/vcpkg-ci/buildtrees/opencascade/src/9e8dfa85e2-cfb9860284.clean/src/Express/Express_Entity.cxx:181: undefined reference to `OSD_Directory::OSD_Directory(OSD_Path const&)'
/usr/bin/ld: /mnt/vcpkg-ci/buildtrees/opencascade/src/9e8dfa85e2-cfb9860284.clean/src/Express/Express_Entity.cxx:182: undefined reference to `OSD_Directory::Build(OSD_Protection const&)'
/usr/bin/ld: /mnt/vcpkg-ci/buildtrees/opencascade/src/9e8dfa85e2-cfb9860284.clean/src/Express/Express_Entity.cxx:552: undefined reference to `OSD_Directory::OSD_Directory(OSD_Path const&)'
/usr/bin/ld: /mnt/vcpkg-ci/buildtrees/opencascade/src/9e8dfa85e2-cfb9860284.clean/src/Express/Express_Entity.cxx:553: undefined reference to `OSD_Directory::Build(OSD_Protection const&)'
/usr/bin/ld: /mnt/vcpkg-ci/buildtrees/opencascade/src/9e8dfa85e2-cfb9860284.clean/src/Express/Express_Entity.cxx:764: undefined reference to `OSD_Directory::OSD_Directory(OSD_Path const&)'
/usr/bin/ld: /mnt/vcpkg-ci/buildtrees/opencascade/src/9e8dfa85e2-cfb9860284.clean/src/Express/Express_Entity.cxx:765: undefined reference to `OSD_Directory::Build(OSD_Protection const&)'
/usr/bin/ld: lin64/gcc/libd/libTKExpress.a(Express_Entity.cxx.o): in function `Express_Entity::writeIncludes(std::ostream&) const':
```
Looks like there is some problem with linking `libTKerne`.

**Comment by JonLiu1993** [comment]
Duplicate of #33498

**Pull request closed without merging**
