### PR TITLE
[vcpkg] Add the possibility to load vcvars.bat with external toolchain. 

### PR DESCRIPTION
**Pull request by Neumann-A**
allow loading vcvars.bat with an external toolchain by setting VCPKG_LOAD_VCVARS_ENV to (true|on|1).

Useful e.g. if one wants to change vcpkg default compiler flags

### CODE REVIEW

**Comment by PhoebeHui** [comment]
@strega-nil, could you help review?

**Comment by strega-nil** [comment]
What's the benefit of this? I don't understand this feature.

**Comment by qis** [comment]
@strega-nil Open `x64-windows.cmake` and add:

```cmake
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE
  "${CMAKE_CURRENT_SOURCE_DIR}/triplets/toolchains/windows.cmake")
```

Now this `windows.cmake` **must** set `CMAKE_C_COMPILER`, `CMAKE_CXX_COMPILER`, and other SDK related directories/variables.

Problems:

1. Using the developer command prompt and setting both CMake variables to `cl.exe` (or not setting them at all) does not work because `vcpkg.exe` ignores the current environment.
2. Even if `vcpkg.exe` did not ignore the current environment, you'd still have to run the `vcvarsall.bat` script manually.
3. Both, `vcvarsall.bat` and `cl.exe` reside in directories which are constantly changing due to VS updates.

My current solution is to just completely overwrite the vcpkg directory `scripts/toolchains` with files that are actually useful to me. This is not good practice, poisons commits and makes contributing to the project more difficult. Yet, this is the only reasonable solution until now.

**Comment by strega-nil** [comment]
Ah, so this is basically "use the existing environment for vcpkg"?

**Comment by Neumann-A** [comment]
>Ah, so this is basically "use the existing environment for vcpkg"?

That is not what VCPKG does if `VCPKG_CHAINLOAD_TOOLCHAIN_FILE` was not set.

VCPKG on windows starts from a completely clean shell and has an automatic VS detection logic to call vcvarsall.bat with the right arguments unless `VCPKG_CHAINLOAD_TOOLCHAIN_FILE` is set.  
The effect can be seen by running `vcpkg install (someport) --debug` where the vcvarsall.bat call will be displayed


From the documentation:
>#### VCPKG_CHAINLOAD_TOOLCHAIN_FILE
>Specifies an alternate CMake Toolchain file to use.
>**This (if set) will override all other compiler detection logic**. By default, a toolchain file is selected >from `scripts/toolchains/` appropriate to the platform.

My documentation clearly states what happens
>#### VCPKG_LOAD_VCVARS_ENV
>If `VCPKG_CHAINLOAD_TOOLCHAIN_FILE` is used, **VCPKG will not setup the Visual Studio environment** *(detection logic is skipped as stated above)*. 
>**Setting `VCPKG_LOAD_VCVARS_ENV` to (true|1|on) changes this behavior** so that the Visual Studio environment is setup following the same rules **as if `VCPKG_CHAINLOAD_TOOLCHAIN_FILE` was not set**.

**Comment by strega-nil** [comment]
Got it! That makes sense now. (I'm kinda curious why that didn't happen that way before, honestly...) Thanks @Neumann-A :)

**Review by strega-nil — APPROVED** [review]

**Comment by Neumann-A** [comment]
>I'm kinda curious why that didn't happen that way before, honestly...

There are good reason for having a completely clean environment. For example if you are not planning to use visual studio at all and defining VCPKG_CHAINLOAD_TOOLCHAIN_FILE probably means that. Also it allows the user more freedom/control in what they plan to do with vcpkg if there is at least one way without forcing vsvars on the user.

**Comment by strega-nil** [comment]
Ah, that makes sense. Cool, thanks @Neumann-A :)

**Comment by dan-shaw** [comment]
LGTM

**Comment by dan-shaw** [comment]
@Neumann-A thanks for the PR!

**Pull request merged**
