### PR TITLE
[lerc] Fix missing algorithm header needed for std::min

### LINKED ISSUE #27962: [lerc] build failure
**Host Environment**

- OS: Windows 10
- Compiler: Visual Studio 15 2017
- The C compiler identification is MSVC 19.16.27039.0
-The CXX compiler identification is MSVC 19.16.27039.0

**To Reproduce**

`./vcpkg install lerc` 

**Failure logs**

- Cut and paste the appropriate build messages from the console output.

```
Installing 1/26 lerc:x86-windows...
Building lerc[core]:x86-windows...
-- Using cached Esri-lerc-v4.0.0.tar.gz.
-- Cleaning sources at D:/repos/vcpkg/buildtrees/lerc/src/v4.0.0-ce5de9f790.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/repos/vcpkg/downloads/Esri-lerc-v4.0.0.tar.gz
-- Applying patch create_package.patch
-- Using source at D:/repos/vcpkg/buildtrees/lerc/src/v4.0.0-ce5de9f790.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:131 (message):
    Command failed: D:/repos/vcpkg/downloads/tools/cmake-3.24.0-windows/cmake-3.24.0-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: D:/repos/vcpkg/buildtrees/lerc/x86-windows-dbg
    See logs for more information:
      D:\repos\vcpkg\buildtrees\lerc\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/lerc/portfile.cmake:14 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building lerc:x86-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+lerc
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[lerc]+Build+error
Include '[lerc] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
    vcpkg-scripts version: e81b17250 2022-11-22 (2 hours ago)
```

- Attach ***every failure log file*** mentioned in the console output.

```
[1/16] C:\PROGRA~2\MICROS~4\2017\BUILDT~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x86\cl.exe   /TP -DLERC_EXPORTS  /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++17 /showIncludes /FoCMakeFiles\Lerc.dir\src\LercLib\BitMask.cpp.obj /FdCMakeFiles\Lerc.dir\ /FS -c D:\repos\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\BitMask.cpp
[2/16] C:\PROGRA~2\MICROS~4\2017\BUILDT~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x86\cl.exe   /TP -DLERC_EXPORTS  /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++17 /showIncludes /FoCMakeFiles\Lerc.dir\src\LercLib\RLE.cpp.obj /FdCMakeFiles\Lerc.dir\ /FS -c D:\repos\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\RLE.cpp
[3/16] C:\PROGRA~2\MICROS~4\2017\BUILDT~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x86\cl.exe   /TP -DLERC_EXPORTS  /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++17 /showIncludes /FoCMakeFiles\Lerc.dir\src\LercLib\fpl_Compression.cpp.obj /FdCMakeFiles\Lerc.dir\ /FS -c D:\repos\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\fpl_Compression.cpp
[4/16] C:\PROGRA~2\MICROS~4\2017\BUILDT~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x86\cl.exe   /TP -DLERC_EXPORTS  /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++17 /showIncludes /FoCMakeFiles\Lerc.dir\src\LercLib\fpl_Predictor.cpp.obj /FdCMakeFiles\Lerc.dir\ /FS -c D:\repos\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\fpl_Predictor.cpp
[5/16] C:\PROGRA~2\MICROS~4\2017\BUILDT~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x86\cl.exe   /TP -DLERC_EXPORTS  /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++17 /showIncludes /FoCMakeFiles\Lerc.dir\src\LercLib\Lerc1Decode\BitStuffer.cpp.obj /FdCMakeFiles\Lerc.dir\ /FS -c D:\repos\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\Lerc1Decode\BitStuffer.cpp
[6/16] C:\PROGRA~2\MICROS~4\2017\BUILDT~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x86\cl.exe   /TP -DLERC_EXPORTS  /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++17 /showIncludes /FoCMakeFiles\Lerc.dir\src\LercLib\fpl_EsriHuffman.cpp.obj /FdCMakeFiles\Lerc.dir\ /FS -c D:\repos\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\fpl_EsriHuffman.cpp
FAILED: CMakeFiles/Lerc.dir/src/LercLib/fpl_EsriHuffman.cpp.obj 
C:\PROGRA~2\MICROS~4\2017\BUILDT~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x86\cl.exe   /TP -DLERC_EXPORTS  /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++17 /showIncludes /FoCMakeFiles\Lerc.dir\src\LercLib\fpl_EsriHuffman.cpp.obj /FdCMakeFiles\Lerc.dir\ /FS -c D:\repos\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\fpl_EsriHuffman.cpp
D:\repos\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\fpl_EsriHuffman.cpp(350): error C2039: 'min': is not a member of 'std'
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\vector(20): note: see declaration of 'std'
D:\repos\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\fpl_EsriHuffman.cpp(350): error C2065: 'min': undeclared identifier
[7/16] C:\PROGRA~2\MICROS~4\2017\BUILDT~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x86\cl.exe   /TP -DLERC_EXPORTS  /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++17 /showIncludes /FoCMakeFiles\Lerc.dir\src\LercLib\BitStuffer2.cpp.obj /FdCMakeFiles\Lerc.dir\ /FS -c D:\repos\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\BitStuffer2.cpp
[8/16] C:\PROGRA~2\MICROS~4\2017\BUILDT~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x86\cl.exe   /TP -DLERC_EXPORTS  /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++17 /showIncludes /FoCMakeFiles\Lerc.dir\src\LercLib\fpl_UnitTypes.cpp.obj /FdCMakeFiles\Lerc.dir\ /FS -c D:\repos\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\fpl_UnitTypes.cpp
[9/16] C:\PROGRA~2\MICROS~4\2017\BUILDT~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x86\cl.exe   /TP -DLERC_EXPORTS  /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++17 /showIncludes /FoCMakeFiles\Lerc.dir\src\LercLib\Huffman.cpp.obj /FdCMakeFiles\Lerc.dir\ /FS -c D:\repos\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\Huffman.cpp
[10/16] C:\PROGRA~2\MICROS~4\2017\BUILDT~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x86\cl.exe   /TP -DLERC_EXPORTS  /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++17 /showIncludes /FoCMakeFiles\Lerc.dir\src\LercLib\fpl_Lerc2Ext.cpp.obj /FdCMakeFiles\Lerc.dir\ /FS -c D:\repos\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\fpl_Lerc2Ext.cpp
FAILED: CMakeFiles/Lerc.dir/src/LercLib/fpl_Lerc2Ext.cpp.obj 
C:\PROGRA~2\MICROS~4\2017\BUILDT~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x86\cl.exe   /TP -DLERC_EXPORTS  /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++17 /showIncludes /FoCMakeFiles\Lerc.dir\src\LercLib\fpl_Lerc2Ext.cpp.obj /FdCMakeFiles\Lerc.dir\ /FS -c D:\repos\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\fpl_Lerc2Ext.cpp
D:\repos\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\fpl_Lerc2Ext.cpp(216): error C2039: 'min': is not a member of 'std'
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\vector(20): note: see declaration of 'std'
D:\repos\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\fpl_Lerc2Ext.cpp(216): error C2065: 'min': undeclared identifier
[11/16] C:\PROGRA~2\MICROS~4\2017\BUILDT~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x86\cl.exe   /TP -DLERC_EXPORTS  /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++17 /showIncludes /FoCMakeFiles\Lerc.dir\src\LercLib\Lerc1Decode\CntZImage.cpp.obj /FdCMakeFiles\Lerc.dir\ /FS -c D:\repos\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\Lerc1Decode\CntZImage.cpp
[12/16] C:\PROGRA~2\MICROS~4\2017\BUILDT~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x86\cl.exe   /TP -DLERC_EXPORTS  /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++17 /showIncludes /FoCMakeFiles\Lerc.dir\src\LercLib\Lerc_c_api_impl.cpp.obj /FdCMakeFiles\Lerc.dir\ /FS -c D:\repos\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\Lerc_c_api_impl.cpp
[13/16] C:\PROGRA~2\MICROS~4\2017\BUILDT~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x86\cl.exe   /TP -DLERC_EXPORTS  /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++17 /showIncludes /FoCMakeFiles\Lerc.dir\src\LercLib\Lerc.cpp.obj /FdCMakeFiles\Lerc.dir\ /FS -c D:\repos\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\Lerc.cpp
[14/16] C:\PROGRA~2\MICROS~4\2017\BUILDT~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x86\cl.exe   /TP -DLERC_EXPORTS  /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++17 /showIncludes /FoCMakeFiles\Lerc.dir\src\LercLib\Lerc2.cpp.obj /FdCMakeFiles\Lerc.dir\ /FS -c D:\repos\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\Lerc2.cpp
ninja: build stopped: subcommand failed.

```

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

I am attempting to install gdal and vcpkg installs lerc as a dependency, running as administrator results in the same issue. I'm not entirely sure why this particular build command would fail when all the previous dependencies succeeded. Would appreciate any help fixing this.

### PR DESCRIPTION
**Pull request by nrowe**
Fix missing algorithm header needed for std::min

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  Tested with x64-windows-static-md though the change is standard c++

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  No

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by nrowe** [comment]
@microsoft-github-policy-service agree

**Comment by FrankXie05** [comment]
Please bump the port version. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).
Also please run command `vcpkg x-add-version lerc` then commit the changes.

**Comment by FrankXie05** [comment]
@nrowe  Are you still working on this PR?

**Comment by Mattc2021** [comment]
Hey I was just wondering if this PR was still being worked on.

**Review by BillyONeal — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the fix!

**Pull request merged**
