### PR TITLE
[libconfuse] Add new port

### PR DESCRIPTION
**Pull request by myd7349**
https://github.com/martinh/libconfuse

### CODE REVIEW

**Comment by myd7349** [comment]
https://github.com/martinh/libconfuse/pull/126

**Comment by myd7349** [comment]
TODO: pkg-config

**Comment by Rastaban** [comment]
I'm confused by your "TODO" comment.  Does this PR need a pkg-config related change before it is ready to merge?

**Comment by myd7349** [comment]
Hi! @Rastaban I think *nix users might be interest in the pkg-config files. So I'd like to install the pkg-config files as well. Maybe I can finish it this weekend.

**Comment by myd7349** [comment]
CI failure on Linux is caused by `libexif`: https://github.com/microsoft/vcpkg/pull/7344

**Pull request merged**
