### PR TITLE
[angle] Fix UWP build

### LINKED ISSUE #7264: Angle is not built for UWP
# Steps to reproduce

* Clone latest vcpkg
* Run `bootstrap-vcpkg.bat`
* Run `vcpkg.exe install angle:x64-uwp`

# Actual behaviour

Vcpkg produces following error:

```
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: C:/Users/konsoletyper/devel/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Debug --target install -- /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /m
    Working Directory: C:/Users/konsoletyper/devel/vcpkg/buildtrees/angle/x64-uwp-dbg
    See logs for more information:
      C:\Users\konsoletyper\devel\vcpkg\buildtrees\angle\install-x64-uwp-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/angle/portfile.cmake:35 (vcpkg_install_cmake)
  scripts/ports.cmake:73 (include)


Error: Building package angle:x64-uwp failed with: BUILD_FAILED
```

# Expected behaviour

Vcpkg installs Angle successfully.

# Additional notes

Looks like it's regression introduced by 7a3818f575fadf1ded97244f803930fe2464f190#diff-f08e5b272610fce9183fc679c06667e3.

### PR DESCRIPTION
**Pull request by kirillp**
fixes #7264

### CODE REVIEW

**Comment by linuxaged** [comment]
build successfully, but the name was changed to `unofficial-angle`, so any function level diff?

**Comment by vicroms** [comment]
Hi @kirillp 

Have you made a Pull Request to upstream your changes to angle? 

These patches seem to substantial to maintain in the long run without the proper support.

**Review by JackBoosY — CHANGES_REQUESTED** [review]
Please update the version in `CONTROL` file.
Thanks.

**Comment by kirillp** [comment]
@vicroms No, I have not contributed to Google, I dont belive I can find arguments to jusstify the change.

@JackBoosY May I use "Version: 2019-11-20-1" ?

**Comment by cbezault** [comment]
@kirillp that looks fine for the version. I agree that Google would not take this change to support UWP but I think that the patch can be made smaller. @vicroms unless someone is interested in making this patch smaller I don't see why we shouldn't include it.

**Comment by cbezault** [comment]
I actually take that back. There's currently upstream work being done to fix Angle for UWP.
[4053](https://bugs.chromium.org/p/angleproject/issues/detail?id=4053)
[4054](https://bugs.chromium.org/p/angleproject/issues/detail?id=4054&q=uwp&colspec=ID%20Type%20Status%20Priority%20Component%20Owner%20Summary)
[3928](https://bugs.chromium.org/p/angleproject/issues/detail?id=3928&q=uwp&colspec=ID%20Type%20Status%20Priority%20Component%20Owner%20Summary)

**Comment by JackBoosY** [comment]
In `CONTROL`:
`Version: 2019-07-19-2`
->
`Version: 2019-07-19-3`

**Review by JackBoosY — APPROVED** [review]

**Comment by ras0219-msft** [comment]
@kirillp Given that upstream is receptive to supporting UWP[1], have you opened PRs against angle for these patches? This is a nontrivial amount of code and we would prefer upstream's blessing (via merge or otherwise approval) before taking this into vcpkg.

[1] https://github.com/microsoft/vcpkg/pull/8970#issuecomment-556549556

**Comment by kirillp** [comment]
@ras0219-msft This is not may patches, VCPKG version of angle used to support UWP, later it was broken. My patch just fixes that regression.

**Comment by kirillp** [comment]
Well, if Google claim to support UWP 
then it probably should work just fine without my patch....

> commit 67527cb4529351b719ad346cb825e47838d51f11
> Author: Josh Matthews <mrlachatte@gmail.com>
> Date: Tue Nov 05 03:04:38 2019
> Fix compilation on UWP targets.

**Comment by cbezault** [comment]
Looks like 4053 was closed a day ago 4054 is still open.

**Comment by JackBoosY** [comment]
@cbezault Does that related with this PR？

**Comment by kirillp** [comment]
> But UWP should now build for angle head without this patch.
microsoft vcpkg master **does not build** Angle for me with the fresh VS 2019 install on fresh latest windows.
**my branch builds just fine**, I will continue my project with my brancn.

**Comment by kirillp** [comment]
vcpkg.exe install angle:x64-uwp
Error: Building package angle:x64-uwp failed with: BUILD_FAILED
full log : https://gist.github.com/kirillp/a9c67d427b0d6ed09e870746bfe18d19

**Comment by twinaphex** [comment]
I am having similar issues trying to get this compiled even with this PR manually applied to current master -

https://paste.ee/p/bOyV2

Really, Microsoft has to start addressing this. I have no idea why a project like ANGLE is actively promoted by MS and yet it can't be built in any way or shape right now either manually or through vcpkg.

**Comment by kirillp** [comment]
Well its is strange indeed.
I have me many pull requests, all (including this) are rejected.
Same time our company uses my branch for our products, and you are welcome as well.

**Comment by JackBoosY** [comment]
@kirillp Log shows:
```
 5>angle_common.lib(system_utils_win.obj) : error LNK2019: unresolved external symbol __imp_SetCurrentDirectoryA referenced in function "bool __cdecl angle::SetCWD(char const *)" (?SetCWD@angle@@YA_NPEBD@Z) [G:\libretro-super\vcpkg\buildtrees\angle\x64-uwp-dbg\libGLESv2.vcxproj]
     5>angle_common.lib(system_utils_win.obj) : error LNK2019: unresolved external symbol __imp_GetCurrentDirectoryA referenced in function "struct Optional<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > __cdecl angle::GetCWD(void)" (?GetCWD@angle@@YA?AU?$Optional@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@@XZ) [G:\libretro-super\vcpkg\buildtrees\angle\x64-uwp-dbg\libGLESv2.vcxproj]
     5>G:\libretro-super\vcpkg\buildtrees\angle\x64-uwp-dbg\Debug\libGLESv2.dll : fatal error LNK1120: 2 unresolved externals [G:\libretro-super\vcpkg\buildtrees\angle\x64-uwp-dbg\libGLESv2.vcxproj]
```
I think the problem is that `kernel32.lib` is not linked to `angle_common`.

**Comment by driver1998** [comment]
It seems updating ANGLE to a more recent commit makes most patches here unnecessary: #9557

**Pull request closed without merging**
