### PR TITLE
[doxygen] Add alternative download URL

### PR DESCRIPTION
**Pull request by c72578**
Only the current and the previous version of doxygen can be downloaded
from: http://doxygen.nl
Sourceforge provides the current version and any previously released
versions for download: https://sourceforge.net/projects/doxygen/files/
Add sourceforge as alternative download URL. This avoids situations,
when the version of doxygen in vcpkg is n-2 and cannot be downloaded
any more, see e.g. commit: 526f9375800f846b113989fc3d566af7b8c79408 and the related PR:  #9574

**Describe the pull request**

- What does your PR fix? Fixes issue #
This PR fixes potential download issues of doxygen.
- Which triplets are supported/not supported? Have you updated the CI baseline?
N/A
- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

### CODE REVIEW

**Comment by JackBoosY** [comment]
These fake failures will resolve in #9726.

**Comment by PhoebeHui** [comment]
Need rerun CI on windows after PR https://github.com/microsoft/vcpkg/pull/9752 merged.

**Comment by c72578** [comment]
OK, PR #9752 has been merged in the meantime and CI has passed.

**Review by PhoebeHui — APPROVED** [review]

**Pull request merged**
