### PR TITLE
[angle] Update to 2019-12-31

### PR DESCRIPTION
**Pull request by driver1998**
Fixes issue #7264 
Add support for ARM64 Desktop/UWP
Fix a bug in EGLRenderResolutionScaleProperty where the scale based on 100% DPI, instead of the screen's DPI as expected.

### CODE REVIEW

**Comment by driver1998** [comment]
The bug is introduced when trying to replace Windows::Graphics::Display::DisplayProperties with Windows::Graphics::Display::DisplayInformation to resolve a deprecated API warning (as error). Although upstream angle just disable this warning outright...

**Review by NancyLi1013 — APPROVED** [review]

**Review by JackBoosY — APPROVED** [review]

**Comment by vicroms** [comment]
I would really prefer if these patches could make it upstream. In the meantime, I think it is OK to have them in vcpkg as they simplify the already existing ones.

**Pull request merged**
