### PR TITLE
[openimageio] Bump to 2.2.10.0.

### LINKED ISSUE #15413: [openimageio:x64-linux] build failure
**Host Environment**
- OS: Kali Linux on WSL2
- Compiler: GNU 10.2.1

**To Reproduce**
`sudo ./vcpkg install openimageio[libraw,opencolorio,ffmpeg,freetype,opencv,gif,webp,openjpeg,pybind11,tools]`

**Failure logs** 

[config-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/5759320/config-x64-linux-dbg-out.log)
[config-x64-linux-dbg-err.log](https://github.com/microsoft/vcpkg/files/5759322/config-x64-linux-dbg-err.log)


**Shell Output**
```
-- Using source at /mnt/c/kali/vcpkg/buildtrees/openimageio/src/9c73ea82cc-c334986945.clean         -- Configuring x64-linux-dbg                                                                        
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:108 (message):
                        Command failed: /mnt/c/kali/vcpkg/downloads/tools/cmake-3.19.2-linux/cmake-3.19.2-Linux-x86_64/bin/cmake /mnt/c/kali/vcpkg/buildtrees/openimageio/src/9c73ea82cc-c334986945.clean -DUSE_LIBRAW=ON -DUSE_OCIO=ON -DUSE_FFMPEG=ON -DUSE_FIELD3D=OFF -DUSE_FREETYPE=ON -DUSE_GIF=ON -DUSE_OPENCV=ON -DUSE_OPENJPEG=ON -DUSE_WEBP=ON -DUSE_PYTHON=ON -DOIIO_BUILD_TOOLS=ON -DOIIO_BUILD_TESTS=OFF -DHIDE_SYMBOLS=ON -DUSE_DCMTK=OFF -DUSE_NUKE=OFF -DUSE_QT=OFF -DUSE_PTEX=OFF -DLINKSTATIC=ON -DBUILD_MISSING_PYBIND11=OFF -DBUILD_MISSING_DEPS=OFF -DVERBOSE=ON -DCMAKE_MAKE_PROGRAM=/mnt/c/kali/vcpkg/downloads/tools/ninja-1.10.1-linux/ninja -DCMAKE_SYSTEM_NAME=Linux -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/mnt/c/kali/vcpkg/scripts/toolchains/linux.cmake -DVCPKG_TARGET_TRIPLET=x64-linux -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/mnt/c/kali/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=/mnt/c/kali/vcpkg -D_VCPKG_INSTALLED_DIR=/mnt/c/kali/vcpkg/installed -DVCPKG_MANIFEST_INSTALL=OFF -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/mnt/c/kali/vcpkg/packages/openimageio_x64-linux/debug
                       Working Directory: /mnt/c/kali/vcpkg/buildtrees/openimageio/x64-linux-dbg
                        Error code: 1
                        See logs for more information:                       
                            /mnt/c/kali/vcpkg/buildtrees/openimageio/config-x64-linux-dbg-out.log
                           /mnt/c/kali/vcpkg/buildtrees/openimageio/config-x64-linux-dbg-err.log                                                                                                                             

Call Stack (most recent call first):
    scripts/cmake/vcpkg_configure_cmake.cmake:328 (vcpkg_execute_required_process)
    ports/openimageio/portfile.cmake:50 (vcpkg_configure_cmake)
    scripts/ports.cmake:136 (include)                                                                                                                                                                                                                                                                         

Error: Building package openimageio:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including: 
    Package: openimageio:x64-linux
    Vcpkg version: 2020.11.12-unknownhash

Additionally, attach any relevant sections from the log files above.
```

**Speculation**

it seems like it's complaining about boost?

```
CMake Warning at /mnt/c/kali/vcpkg/downloads/tools/cmake-3.19.2-linux/cmake-3.19.2-Linux-x86_64/share/cmake-3.19/Modules/FindBoost.cmake:1204 (message): New Boost version may have incorrect or missing dependencies and imported targets                                                                                           
Call Stack (most recent call first):                                                                  
/mnt/c/kali/vcpkg/downloads/tools/cmake-3.19.2-linux/cmake-3.19.2-Linux-x86_64/share/cmake-3.19/Modules/FindBoost.cmake:1326 (_Boost_COMPONENT_DEPENDENCIES)                                            /mnt/c/kali/vcpkg/downloads/tools/cmake-3.19.2-linux/cmake-3.19.2-Linux-x86_64/share/cmake-3.19/Modules/FindBoost.cmake:1935 (_Boost_MISSING_DEPENDENCIES)                                              /mnt/c/kali/vcpkg/scripts/buildsystems/vcpkg.cmake:598 (_find_package)                              src/cmake/externalpackages.cmake:90 (find_package)                                                  src/cmake/externalpackages.cmake:164 (checked_find_package)                                         CMakeLists.txt:117 (include) 
```

 or the naming of certain packages?

```
The package name passed to `find_package_handle_standard_args` (JPEG) does                          not match the name of the calling package (JPEGTurbo).
```


Any help would be greatly appreciated. Happy New Year.

### PR DESCRIPTION
**Pull request by Hoikas**
This fixes #15413. The openimageio used the deprecated FindPythonInterp in the previous version, which was not playing nicely with vcpkg's python3 port. The most recent openimageio is using the new FindPython module, which behaves correctly.

All features have been tested, with some known issues:
- There is a potential build error in the libraw feature due to an error in the libraw port (See: #15506)
- The pybind11 incorrectly uses system Python on non-Windows platforms (See: #15507)

The following other issues are known but seem to have existed previously:
- The field3d feature does not work on Windows because field3d does not properly expose any symbols.
- On non-MSVC compilers, to use the ffmpeg and pybind11 features together, either dynamic library linkage needs to be used or `-fPIC` needs to be set in the C/CXX flags.

Any suggestions on those would be appreciated. 

- What does your PR fix?
Fixes #15413

- Which triplets are supported/not supported? Have you updated the CI baseline?
No change.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

### CODE REVIEW

**Comment by NancyLi1013** [comment]
Hi @Hoikas 

Thanks for your PR.

This PR should also fix #13750, #13621. Right?

**Review by NancyLi1013 — APPROVED** [review]

**Comment by Hoikas** [comment]
I think so, yes.

**Comment by NancyLi1013** [comment]
Sorry for the delay.

I think the last thing needs to be done is feature testing. 
Have you testing these features in this PR?

**Pull request merged**
