### PR TITLE
[sail] Update to 0.9.0-pre19

### PR DESCRIPTION
**Pull request by HappySeaFox**
**Describe the pull request**

COMMON: Added more BPP16 RGB[X] pixel formats
COMMON: Added sail_io_contents_to_data() and sail_io_contents_into_data()
COMMON: Make sail_now() return 0 on error, not SAIL_OK
EXAMPLES: Fixed using bytes per line (ignored previously)
ICO: Added ICO image format
LIBSAIL: Make codec priorities as enum
PCX: Added PCX image format
QOI: Added QOI image format (https://phoboslab.org/log/2021/11/qoi-fast-lossless-image-compression)

- #### What does your PR fix?  
\-

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  Same as before

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  `Yes`

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by LilyWangLL** [comment]
`vcpkg_fail_port_install` has been deprecated, VCPKG use `supports` in vcpkg.json instead of it. Could you please remove it in **portfile.cmake**?

**Comment by HappySeaFox** [comment]
@LilyWangLL Is this deprecation the latest change that is not reflected in the docs? I see no deprecation warnings in https://github.com/Microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_fail_port_install.md

**Comment by LilyWangLL** [comment]
> @LilyWangLL Is this deprecation the latest change that is not reflected in the docs? I see no deprecation warnings in https://github.com/Microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_fail_port_install.md

Yeah, our documentation has not stated that `vcpkg_fail_port_install` is deprecated, but its function is the same as `Supports`, we usually use `Supports` instead of it.

**Comment by HappySeaFox** [comment]
@LilyWangLL Updated, thanks!

**Review by LilyWangLL — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the update!

**Pull request merged**
