### PR TITLE
[simpleini] Install missing code

### PR DESCRIPTION
**Pull request by JackBoosY**
- Install missing code files `ConvertUTF.h` and `ConvertUTF.c`.
- Install sample code.

Related: #9320.

Note: no feature needs to be tested.

### CODE REVIEW

**Comment by JackBoosY** [comment]
@AMS21  Could you test it?

Thanks.

**Comment by AMS21** [comment]
Tested on my local copy of Ubuntu 18.04 and compiles without errors! 👍

**Comment by PhoebeHui** [comment]
Does the failures on linux and windows expect? Have you test the features?

**Comment by PhoebeHui** [comment]
It looks the azure-kinect-sensor-sdk:x64-windows-static, proxygen:x64-linux and freerdp:x64-linux failures blocked many PRs, could you take a look? the ci baseline files have not been updated. It might be helpful if we found why this happened.

**Comment by JackBoosY** [comment]
@PhoebeHui These failure will solve in other PRs.

**Review by PhoebeHui — APPROVED** [review]

**Pull request merged**
