### PR TITLE
[cudnn] Add library path

### LINKED ISSUE #17680: [<darknet>] build failure
Hello, I am installing darknet using vcpkg and I keep getting a build failure.
I run windows 10 and use the anaconda3 prompt for executing commands.
I used the following commands for installing vcpkg and darknet:

```
(base) C:\>git clone https://github.com/microsoft/vcpkg
(base) C:\>conda activate yolov3
(yolov3) C:\>.\vcpkg\bootstrap-vcpkg.bat
(yolov3) C:\>cd vcpkg
(yolov3) C:\vcpkg>.\vcpkg integrate install
(yolov3) C:\vcpkg>.\vcpkg install darknet[opencv-base,cuda,cudnn]:x64-windows
```
Everything up till here is fine, but the last of the  30 packages of the install darknet command gives the following response/error:

```
Starting package 30/30: darknet:x64-windows
Building package darknet[core,cuda,cudnn,opencv-base]:x64-windows...
-- Downloading https://github.com/AlexeyAB/darknet/archive/91efb7c7f6c00a4616ed58735f7c670908d0a849.tar.gz -> AlexeyAB-darknet-91efb7c7f6c00a4616ed58735f7c670908d0a849.tar.gz...
-- Extracting source C:/vcpkg/downloads/AlexeyAB-darknet-91efb7c7f6c00a4616ed58735f7c670908d0a849.tar.gz-- Using source at C:/vcpkg/buildtrees/darknet/src/0908d0a849-27adeee8f8.clean
-- Configuring x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: C:/vcpkg/downloads/tools/cmake-3.20.1-windows/cmake-3.20.1-windows-i386/bin/cmake.exe C:/vcpkg/buildtrees/darknet/src/0908d0a849-27adeee8f8.clean -DENABLE_CUDA=ON -DENABLE_CUDNN=ON -DINSTALL_BIN_DIR:STRING=bin -DINSTALL_LIB_DIR:STRING=lib -DENABLE_OPENCV:BOOL=TRUE -DENABLE_OPENCV_WITH_CUDA:BOOL=FALSE -DCMAKE_MAKE_PROGRAM=C:/vcpkg/downloads/tools/ninja/1.10.1-windows/ninja.exe -DBUILD_SHARED_LIBS=ON -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/vcpkg/scripts/toolchains/windows.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=v142 -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=C:/vcpkg -D_VCPKG_INSTALLED_DIR=C:/vcpkg/installed -DVCPKG_MANIFEST_INSTALL=OFF -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=C:/vcpkg/packages/darknet_x64-windows/debug
    Working Directory: C:/vcpkg/buildtrees/darknet/x64-windows-dbg
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\darknet\config-x64-windows-dbg-out.log
      C:\vcpkg\buildtrees\darknet\config-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:333 (vcpkg_execute_required_process)
  ports/darknet/portfile.cmake:39 (vcpkg_configure_cmake)
  scripts/ports.cmake:142 (include)


Error: Building package darknet:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: darknet:x64-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

Additionally, attach any relevant sections from the log files above.
```
I also have the error logs down here. They had a .log format, but for some reason, I couldn't upload those to GitHub, so I made them .txt, but the contents are the same.

[config-x64-windows-dbg-err.txt](https://github.com/microsoft/vcpkg/files/6426694/config-x64-windows-dbg-err.txt)
[config-x64-windows-dbg-out.txt](https://github.com/microsoft/vcpkg/files/6426695/config-x64-windows-dbg-out.txt)

I have read about #16597 and #2985 where it was suggested to install on the c-drive, which I did, and to temporarily remove CMake from the program files, so vcpkg could install its own. Both didn't help.

I hope you can help me, and thanks in advance.
Kind regards,

-Zayr0

### PR DESCRIPTION
**Pull request by NancyLi1013**
**Describe the pull request**

- #### What does your PR fix? 
Fixes #17680

Update `endif `as` endif()` in FindCUDNN.cmake.
https://github.com/microsoft/vcpkg/blob/c99dc50be99c9656502d140e1d785a267ab233a4/ports/cudnn/FindCUDNN.cmake#L39
Install `vcpkg-cmake-wrapper.cmake` to `share/${PORT}` to enable `cudnn `found.

Additional fixes:
Currently, `cuddn `needs to download from official website manually.  The libs in the latest version 8.2.0 are listed in _cuda/lib/x64_ folder. So I add `cuda/lib/x64` to the library path to enable the library found.

image

Related #17377

Note: No feature needs to test.

### CODE REVIEW

**Comment by cenit** [comment]
is it really necessary? I can find CUDNN even with current module 🤔 
in any case it's no harm

**Comment by NancyLi1013** [comment]
On my machine, it doesn't work without the additional path `cuda/lib/x64`.

```
Starting package 1/28: cudnn:x64-windows
Building package cudnn[core]:x64-windows...
-- Found CUDA V11.3.58
-- CUDNN_INCLUDE_DIR: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.3/cuda/include
-- CUDNN_LIBRARY: CUDNN_LIBRARY-NOTFOUND
CMake Error at ports/cudnn/portfile.cmake:69 (message):
  Please download CUDNN from official sources (such as
  https://developer.nvidia.com/rdp/cudnn-download ) and extract the zip into
  your CUDA_TOOLKIT_ROOT (C:/Program Files/NVIDIA GPU Computing
  Toolkit/CUDA/v11.3).  (For example: tar.exe -xvf
  cudnn-11.2-windows-x64-v8.1.1.33.zip --strip 1 --directory "C:/Program
  Files/NVIDIA GPU Computing Toolkit/CUDA/v11.3"
Call Stack (most recent call first):
  scripts/ports.cmake:141 (include)


Error: Building package cudnn:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: cudnn:x64-windows
  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9
```
As you can see, it can only find headers in `cuda/include`, but library cannot be found.

**Review by JackBoosY — APPROVED** [review]

**Comment by ras0219-msft** [comment]
This LGTM, thanks!

**Pull request merged**
