### PR TITLE
[ctp] New version v6.6.1_P1_20210406_se

### PR DESCRIPTION
**Pull request by xgao1023**
Updates:
 * new order types
 * ClientLoginRemark
 * compression during data transmission

Compatible with server version 6.5.0 or newer (new feature needs server version 6.6.1)
Data collection module is not included and not changed from 6.3.19_P1.

Original Update in Chinese:

简介：看穿式监管Linux/Windows版本。本次更新内容如下：支持中金所顶单功能、支持交易所结算风险隔离功能，登录接口中新加ClientLoginRemark，API与前置传输过程中的数据压缩。适用于6.5.0及以上柜台，新功能需要连接6.6.1以上柜台才能使用。仅tradeapi，采集模块(WinDataCollect.dll/ LinuxDataCollect.so)请从期货期权看穿式监管评测6.3.19P1版本中下载。

### CODE REVIEW

**Comment by PhoebeHui** [comment]
@xgao1023, thanks for the PR! 

Could you fix the indent issue in portfile.cmake?

**Comment by xgao1023** [comment]
> @xgao1023, thanks for the PR!
> 
> Could you fix the indent issue in portfile.cmake?

Fixed and re-pushed.

**Review by PhoebeHui — APPROVED** [review]
Thanks for your updates!

**Comment by ras0219-msft** [comment]
Thanks for the update!

**Pull request merged**
