### PR TITLE
[vcpkg] Use portable verion of Strawberry perl, so it can work properly without calling relocation.pl.bat after install

### PR DESCRIPTION
**Pull request by mturk**
The patch uses portable version of Strawberry perl which does not need to execute the relocation.pl.bat after unzipping the distribution. 

From the official doc ...
* If installing this version from a .zip file, you MUST extract it to a 
  directory that does not have spaces in it - e.g. c:\myperl\
  and then run some commands and manually set some environment variables:

  c:\myperl\relocation.pl.bat         ... this is REQUIRED!
  c:\myperl\update_env.pl.bat         ... this is OPTIONAL

### CODE REVIEW

**Comment by strega-nil** [comment]
Where is `relocation.pl.bat` run? If it's not removed in this PR, were we just never running it?

**Comment by LilyWangL** [comment]
Pinging @mturk for response. Is work still being done for this PR?

**Comment by LilyWangL** [comment]
Closing this PR since it seems that no progress is being made. Please reopen if work is still being done.

**Pull request closed without merging**
