### PR TITLE
[vcpkg baseline][rapidjson] Re-check hash value

### PR DESCRIPTION
**Pull request by JackBoosY**
```
2022-07-03T21:15:44.5630830Z Installing 115/249 rapidjson:x64-osx...
2022-07-03T21:15:44.5633200Z Building rapidjson[core]:x64-osx...
2022-07-03T21:15:44.6139470Z CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:14 (message):
2022-07-03T21:15:44.6140630Z   
2022-07-03T21:15:44.6141080Z 
2022-07-03T21:15:44.6141700Z   File does not have expected hash:
2022-07-03T21:15:44.6142530Z 
2022-07-03T21:15:44.6144010Z           File path: [ /Users/vagrant/Data/downloads/Tencent-rapidjson-232389d4f1012dddec4ef84861face2d2ba85709.tar.gz ]
2022-07-03T21:15:44.6145120Z       Expected hash: [ 0d7d751179abdaa6ebf6167d522651a2d13bc024d20c7e3f775c7397a8aab4cd866a6c91a55521ad7847e910822fcf982625c7308c74f5df663e6fd81336c9fc ]
2022-07-03T21:15:44.6146240Z         Actual hash: [ 60bfbfe4884122aa9ae8755531da18ce4a793bb217c06474dd8c5afe0f2f5df280c40be2f303c1740f5af14c7ad5cc2a57f08de5205cc7ab27d6166b0f49130d ]
2022-07-03T21:15:44.6147110Z 
2022-07-03T21:15:44.6147950Z   The cached file SHA512 doesn't match.  The file may have been corrupted.
2022-07-03T21:15:44.6148990Z   To re-download this file please delete cached file at path
2022-07-03T21:15:44.6150290Z   /Users/vagrant/Data/downloads/Tencent-rapidjson-232389d4f1012dddec4ef84861face2d2ba85709.tar.gz
2022-07-03T21:15:44.6151170Z   and retry.
2022-07-03T21:15:44.6151360Z 
2022-07-03T21:15:44.6151840Z Call Stack (most recent call first):
2022-07-03T21:15:44.6152560Z   scripts/cmake/vcpkg_download_distfile.cmake:171 (z_vcpkg_download_distfile_test_hash)
2022-07-03T21:15:44.6153380Z   scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
2022-07-03T21:15:44.6154100Z   ports/rapidjson/portfile.cmake:2 (vcpkg_from_github)
2022-07-03T21:15:44.6154720Z   scripts/ports.cmake:146 (include)
2022-07-03T21:15:44.6155250Z 
2022-07-03T21:15:44.6155550Z 
2022-07-03T21:15:44.6185620Z error: building rapidjson:x64-osx failed with: BUILD_FAILED
```
Update PR: https://github.com/microsoft/vcpkg/pull/25509

Related: https://github.com/microsoft/vcpkg/pull/24843 https://github.com/microsoft/vcpkg/pull/25239 https://dev.azure.com/vcpkg/public/_build/results?buildId=74527&view=results

### CODE REVIEW

**Comment by Osyotr** [comment]
Last time I downloaded the hash was `0d7d751179abdaa6ebf6167d522651a2d13bc024d20c7e3f775c7397a8aab4cd866a6c91a55521ad7847e910822fcf982625c7308c74f5df663e6fd81336c9fc`...

**Comment by Thomas1664** [comment]
> Last time I downloaded the hash was `0d7d751179abdaa6ebf6167d522651a2d13bc024d20c7e3f775c7397a8aab4cd866a6c91a55521ad7847e910822fcf982625c7308c74f5df663e6fd81336c9fc`...

Same for me. I think the root cause of this issue is that the binary caching feature has a bug.

**Comment by JackBoosY** [comment]
> > Last time I downloaded the hash was `0d7d751179abdaa6ebf6167d522651a2d13bc024d20c7e3f775c7397a8aab4cd866a6c91a55521ad7847e910822fcf982625c7308c74f5df663e6fd81336c9fc`...
> 
> Same for me. I think the root cause of this issue is that the binary caching feature has a bug.

But our pipeline re-downloaded the package and matched the changed hash.

**Comment by JackBoosY** [comment]
@Thomas1664 Yeah it should be binary cache issue.

**Review by LilyWangLL — DISMISSED** [review]

**Review by LilyWangLL — APPROVED** [review]

**Pull request merged**
