### PR TITLE
[botan] add arm

### PR DESCRIPTION
**Pull request by jgilje**
**Describe the pull request**

- #### What does your PR fix?  
Adds support for 32 and 64 bit builds on ARM. Botan includes a selftester which I've verified ran successfully for both arm32 and arm64 on Linux.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
No (primarily tested on Linux, whose arm-triplets are in community)

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
To the best of my knowledge

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
Yes

### CODE REVIEW

**Comment by PhoebeHui** [comment]
@jgilje, thanks for your PR!

Botan only support arm on unix, right? I just test botan with arm64-windows locally, it failed with following failure:

```
build\include\botan/mul128.h(42): warning C4163: '_umul128': not available as an intrinsic function
build\include\botan/mul128.h(88): error C3861: '_umul128': identifier not found
```

**Comment by jgilje** [comment]
Yeah, it would appear so. I haven't got windows-on-arm hardware to test, so for now - should I just add a fail condition if it's arm+windows?

**Comment by PhoebeHui** [comment]
You can add 'supports' to control file to implement this.

**Comment by jgilje** [comment]
Thanks, Supports field has been updated and arm-build has been removed from ci.baseline

**Comment by PhoebeHui** [comment]
@jgilje, could you please update the baseline version by executing './vcpkg x-add-version --overwrite-version"?

**Comment by jgilje** [comment]
Sorry, fixed! The Versions feature is new since I last contributed to vcpkg :)

**Review by PhoebeHui — APPROVED** [review]
Thanks for your updates!

**Comment by BillyONeal** [comment]
Thanks for fixing some of our CI skips :D

**Pull request merged**
