### PR TITLE
[azure-iot-sdk-c] C SDK release 2019-12-11

### PR DESCRIPTION
**Pull request by ewertons**
[azure-iot-sdk-c] C SDK release 2019-12-11

### CODE REVIEW

**Comment by ewertons** [comment]
Folks, any estimate of when these build issues will get solved and the PRs will start to get merged again? Should we expect to have this done only after the holidays?

**Comment by LilyWangL** [comment]
Hi @ewertons, thanks for your new PR. Here are some regressions from the current CI system:

x86-windows | master | test | notes
-- | -- | -- | --
azure-uhttp-c | Pass | Fail | Regression
azure-umqtt-c | Pass | Fail | Regression

x64-windows | master | test | notes
-- | -- | -- | --
azure-uhttp-c | Pass | Fail | Regression
azure-umqtt-c | Pass | Fail | Regression

x64-windows-static | master | test | notes
-- | -- | -- | --
azure-uhttp-c | Pass | Fail | Regression
azure-umqtt-c | Pass | Fail | Regression

arm64-windows | master | test | notes
-- | -- | -- | --
azure-uhttp-c | Pass | Fail | Regression
azure-umqtt-c | Pass | Fail | Regression

**Comment by ras0219-msft** [comment]
@ewertons just to clarify the current situation -- Our OSX testing is down, but please do make sure that the PR is passing for both Linux and Windows so we can merge as soon as possible once OSX is available again.

Currently, this PR fails on Windows due to:
```
CMake Error at C:/vsts/_work/3/s/installed/x86-windows/share/azure_c_shared_utility/azure_c_shared_utilityFunctions.cmake:644 (if):
  if given arguments:

    "STREQUAL" "OFF"

  Unknown arguments specified
Call Stack (most recent call first):
  CMakeLists.txt:112 (set_platform_files)
```

I'm 99% sure this is caused by accidentally double-expanding inside an `if()` directive. This happens to `FOO` in the following example:
```cmake
if(${FOO} STREQUAL "Hello")
```
It can be fixed by removing the `${}` or adding additional quotes:
```cmake
if("${FOO}" STREQUAL "Hello")
if(FOO STREQUAL "Hello")
```
See also the CMake documentation for `if()`: https://cmake.org/cmake/help/latest/command/if.html

**Comment by LilyWangL** [comment]
Pinging @ewertons for response. Is work still being done for this PR?

**Comment by LilyWangL** [comment]
Closing this PR since it seems that no progress is being made. Please reopen if work is still being done.

**Pull request closed without merging**
