### PR TITLE
FLTK Port

### PR DESCRIPTION
**Pull request by smasherprog**

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Awesome first port, I remember using FLTK in university :).

Good job renaming the .LIB files! The one catch is that you have to avoid renaming the DLLs/PDBs, because the LIB files refer to the DLLs by name:
```
PS D:\src\vcpkg> dumpbin /headers installed\x64-windows\lib\fltk.lib | findstr .dll
  DLL name     : libfltk_SHARED.dll
  DLL name     : libfltk_SHARED.dll
  ....
```
I removed those lines during the merge.

**Comment by stekyne** [comment]
What are the reasons for removing the fltk-fluid.exe and config files? I need the fluid executable for my app basically. Is it possible to remove these lines?

port file...
file(REMOVE ${CURRENT_PACKAGES_DIR}/bin/fluid.exe)
file(REMOVE ${CURRENT_PACKAGES_DIR}/bin/fltk-config)

file(REMOVE ${CURRENT_PACKAGES_DIR}/debug/bin/fluid.exe)
file(REMOVE ${CURRENT_PACKAGES_DIR}/debug/bin/fltk-config)

Thanks

**Comment by smasherprog** [comment]
ras0219     did you want me to add a a PR to include these files?
I'm not sure if exe's should be included in vcpkg packages

**Comment by stekyne** [comment]
@ras0219-msft Any update on this? Thanks

**Comment by smasherprog** [comment]
You might have to create a new issue on this to get someone to comment.
I can add the PR, but im not sure what the stance on building executables vs libraries

**Comment by ras0219-msft** [comment]
Sorry, looks like this message slipped through my inbox :).

The guideline on executables vs. libraries is "Do you need to run this executable as part of your build process?" and "Does the _specific exact version_ of this executable matter for my application?".

For example, Yacc and Lex are tied to runtimes and must be run as part of the build -- these do need to be packaged inside Vcpkg.

Alternatively, curl probably _doesn't_ qualify -- generally, you don't run curl as part of a build and even if you did it doesn't matter that the `libcurl` you're building against is the same version as the `curl.exe` you run during your build.

Another good way to look at it is: "Can I reasonably install this through chocolatey/msi/store/etc instead?" If the answer is yes, it _probably_ should be gotten through that!

**Comment by smasherprog** [comment]
Just did a PR on this.

**Comment by stekyne** [comment]
@smasherprog Thanks, that's great!

**Pull request merged**
