### PR TITLE
[boost-build] do not depend on boost-uninstall

### PR DESCRIPTION
**Pull request by huangqinjin**
boost-build and boost-modular-build-helper are host packages, while boost-uninstall is for target tiplets.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] ~~SHA512s are updated for each updated download~~
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by Neumann-A** [comment]
What use case is this PR improving? 
If you want to remove all of boost everything needs to depend on boost-uninstall.

**Comment by huangqinjin** [comment]
For example, install `boost` for both `x64-windows` and `x86-windows`, and `x64-windows` is the host triplet. If we uninstall `boost-uninstall:x64-windows`, `x86-windows` also get uninstalled. It is impossible currently to only uninstall host boost.

**Comment by Neumann-A** [comment]
> It is impossible currently to only uninstall host boost.

I would say uninstalling boost should include boost-build because otherwise you are not uninstalling all of boost. (But that is just a personal opinion.)

**Review by FrankXie05 — APPROVED** [review]

**Comment by BillyONeal** [comment]
This is exchanging one problem for another. Yes, by avoiding removing the host dependencies, you avoid removing stuff installed for other target triplets. However, by doing so, you also *break* uninstalling things for the host.

This situation is no different than what happens for every other thing with host dependencies; for example `vcpkg remove protobuf`. I don't think we should create an exception to how this works for boost.

Given that this seems to replace one problem for another I'm personally opposed to merging this.

**Comment by huangqinjin** [comment]
>  you also break uninstalling things for the host

Yes. But `boost-build` and `boost-modular-build-helper` are host tools, leaving them uninstalled is acceptable from my POV, I consider they are same things as `vcpkg-cmake` and `vcpkg-cmake-config`. Compared to uninstalling something I don't expect, I **personally** prefer it does things correctly (but not perfectly). (Just like you can install Visual Studio, but you can not uninstall it completely :upside_down_face:.)

> This situation is no different than what happens for every other thing with host dependencies

That is true for any host dependencies, but the point of this PR is that `boost-uninstall` should not be a host dependency.

If `boost-uninstall` was meant to remove `boost-*:*` completely, then only `boost-uninstall:<host>` should be installed rather than installing it per triplet.

**Comment by BillyONeal** [comment]
> Yes. But `boost-build` and `boost-modular-build-helper` are host tools, leaving them uninstalled is acceptable from my POV, [...] Compared to uninstalling something I don't expect, I **personally** prefer it does things correctly (but not perfectly). (Just like you can install Visual Studio, but you can not uninstall it completely 🙃.)

I do not think the folks who asked for `boost-uninstall` to exist in the first place would be happy with removing `boost-uninstall` not actually uninstalling parts of boost.

> [...] I consider they are same things as `vcpkg-cmake` and `vcpkg-cmake-config`. [...]

If you remove `vcpkg-cmake` et al., that removes things in other triplets too.

> That is true for any host dependencies, but the point of this PR is that `boost-uninstall` should not be a host dependency.
> 
> If `boost-uninstall` was meant to remove `boost-*:*` completely, then only `boost-uninstall:<host>` should be installed rather than installing it per triplet.

Again, the problem is that if we make it not a host dependency, then it is incapable of doing what it exists to do. You're just replacing one bug with another.

**Comment by huangqinjin** [comment]
> You're just replacing one bug with another.

@BillyONeal Then what is your suggestion? Add `boost-uninstall-this-triplet` and `boost-uninstall-all-triplets`?

**Comment by dan-shaw** [comment]
I agree with Billy, this is the expected behavior of `boost-uninstall`. You can use manifests so you don't have to manually remove dependencies. I am closing this PR for now.

**Comment by huangqinjin** [comment]
@dan-shaw respect you but it is not **expected behavior**. `boost-uninstall` is introduced before we have host dependencies.

**Pull request closed without merging**
