### PR TITLE
[itk] Revise, test, fix

### LINKED ISSUE #35939: [itk] fftw3 feature
### Is your feature request related to a problem? Please describe.

Now itk port has made linking to fftw3 a default behavior, which will cause itk to be forced to switch from the Apache license to the GPL license

https://github.com/InsightSoftwareConsortium/ITK/blob/72aa9a602bd92b665acc915d8df4bd00a27c98f0/CMake/itkExternal_FFTW.cmake#L24C9-L24C9

```
  set(msg "ATTENTION: You have enabled the use of FFTW.")
  set(msg "${msg} This library is distributed under a GPL license.")
  set(msg "${msg} By enabling this option, the ITK libraries binary")
  set(msg "${msg} that is built will be covered by a GPL license")
  set(msg "${msg} and so will any executable that is linked against these libraries.")
  message("${msg}")
```

### Proposed solution

Maybe we can consider fftw3 as an available feature

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dg0yt**
Add test port.  
Fix cuda.  
Fix pkgconfig.  
Drop unofficial debug postfix.
De-vendor vxl.
[rtk]: Update download, patch without warnings.  
[vtk]: Fix build with vtk[python].  
[fftw]: New optional feature to control GPL dependency. Resolves #35939.  
[python]: Move hidden castxml download to new tool port. Enables caching.  
Update copyright.
Cleanup.

### CODE REVIEW

**Comment by dg0yt** [comment]
x64-linux regression is unrelated. Fixed in #41893.

Please review now.

**Review by MonicaLiu0311 — APPROVED** [review]

**Comment by dg0yt** [comment]
Unrelated CI failure, fixed by #42017.

**Review by MonicaLiu0311 — APPROVED** [review]

**Comment by dg0yt** [comment]
All checks green.

**Comment by MonicaLiu0311** [comment]
Features `fftw,python,rtk` are tested successfully in the following triplet:
```
x64-windows
```

**Review by MonicaLiu0311 — APPROVED** [review]

**Pull request merged**
