### PR TITLE
[arrow] Update to 6.0.1

### PR DESCRIPTION
**Pull request by ianmcook**
Updates the arrow port to version 6.0.1

### CODE REVIEW

**Comment by ianmcook** [comment]
I tested the features locally with triplets `x64-osx`, `x64-windows`, and `x64-windows-static` and observed no regressions from version 6.0.0.

**Review by PhoebeHui — APPROVED** [review]
Thanks for your PR!

**Comment by ianmcook** [comment]
FYI @GPSnoopy @jgiannuzzi 
See https://arrow.apache.org/release/6.0.1.html for what's new in 6.0.1.
I doubt this will have any new impacts on ParquetSharp compared to 6.0.0.

**Comment by BillyONeal** [comment]
Thanks for the update!

**Comment by jgiannuzzi** [comment]
> FYI @GPSnoopy @jgiannuzzi
> See https://arrow.apache.org/release/6.0.1.html for what's new in 6.0.1.
> I doubt this will have any new impacts on ParquetSharp compared to 6.0.0.

Thanks @ianmcook, I will update our branch — I also doubt it will have any impact!

**Pull request merged**
