### PR TITLE
[blend2d] Update to beta_2020-05-04

### PR DESCRIPTION
**Pull request by ZeeWanderer**
initial impl of font manager is here

### CODE REVIEW

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
Need to test features.

**Comment by ZeeWanderer** [comment]
Would it be better to change features to `no_{feature_name}` to avoid having most or all features as default? Current set default features mirror default CMake behavior when built without any additional options.

**Comment by strega-nil** [comment]
@ZeeWanderer no, it would not be; features _should_ be purely additive.

On the other hand, thank you so much! This looks great :D

**Pull request merged**
