### PR TITLE
[libevhtp] Add new port

### PR DESCRIPTION
**Pull request by NancyLi1013**
`Libevhtp` was created as a replacement API for `Libevent's` current HTTP API. 
It currently doesn't support Windows platform.

Related issue #4793.

All features test pass with` x64-linux` triplet.

### CODE REVIEW

**Review by PhoebeHui — APPROVED** [review]

**Review by JackBoosY — APPROVED** [review]

**Review by dan-shaw — APPROVED** [review]

**Comment by ras0219-msft** [comment]
Please modify ci.baseline.txt to account for the windows failures.

**Pull request merged**
