### PR TITLE
[mathgl]Fix feature glut/hdf5/qt5.

### PR DESCRIPTION
**Pull request by JackBoosY**
This PR will fix:
- [x] mathgl[glut].
- [x] mathgl[hdf5]
- [x] mathgl[qt5]

Related: #8360 #8357 #8359.

### CODE REVIEW

**Comment by JackBoosY** [comment]
`LINK : fatal error LNK1104: cannot open file 'freeglut.lib'`
Why?
`-- Found GLUT: optimized;C:/vsts/_work/2/s/installed/x64-windows/lib/glut32.lib;debug;C:/vsts/_work/2/s/installed/x64-windows/debug/lib/freeglutd.lib`

Did not find any place to call it in error log.

**Comment by cenit** [comment]
Isn’t it better if you use freeglut and that’s it for glut? Also I don’t like at all the “vendor” mixing inside a single port, where the glut feature inside OpenGL is coming from another repository completely unrelated to Windows SDK...

**Comment by JackBoosY** [comment]
@cenit `mathgl[glut]` does depend on the port `freeglut` now.

**Comment by cenit** [comment]
it's the "hidden" work you did on OpenGL here that I was trying to point out...

**Comment by JackBoosY** [comment]
@cenit  yes, you're right.

**Review by PhoebeHui — APPROVED** [review]

**Review by vicroms — APPROVED** [review]

**Pull request merged**
