### PR TITLE
[ois] fix pkgconfig file not installed on windows

### PR DESCRIPTION
**Pull request by maz-1**
**Describe the pull request**

- #### What does your PR fix?  
  Fixes pkgconfig file not installed on windows

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  not updated, sould be same as before

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  <Yes>

### CODE REVIEW

**Comment by maz-1** [comment]
Hold on, I did not fix debug suffix in pkgbuild file
will reopen after fixed.

**Comment by JackBoosY** [comment]
We need to check the pkgconfig files.

**Comment by JonLiu1993** [comment]
@maz-1, Thanks for posting this issue,I cloned your branch to the local and then use the commands ''./vcpkg install osi --debug" and "./vcpkg install osi" after installation, it is not in the F:\test-pr\vcpkg\packages\osi_x86-windows path Found the pkgconfig file, have you tested it locally?

**Comment by maz-1** [comment]
> @maz-1, Thanks for posting this issue,I cloned your branch to the local and then use the commands ''./vcpkg install osi --debug" and "./vcpkg install osi" after installation, it is not in the F:\test-pr\vcpkg\packages\osi_x86-windows path Found the pkgconfig file, have you tested it locally?

I think you mistaken the package name, it's ois not osi

**Comment by JonLiu1993** [comment]
> > @maz-1, Thanks for posting this issue,I cloned your branch to the local and then use the commands ''./vcpkg install osi --debug" and "./vcpkg install osi" after installation, it is not in the F:\test-pr\vcpkg\packages\osi_x86-windows path Found the pkgconfig file, have you tested it locally?
> 
> I think you mistaken the package name, it's ois not osi

Sorry, I made a mistake, I re-tested with the correct package name and saw the .pc file in F:\test-pr\vcpkg\packages\ois_x86-windows\debug\lib\pkgconfig

**Review by JonLiu1993 — APPROVED** [review]

**Pull request merged**
