### PR TITLE
[libheif] update to 1.9.1

### LINKED ISSUE #14437: [libheif] update to 1.9.1
Library name: **libheif**

New version number: **v1.9.1**

Other information that may be useful (release notes, etc...)

The current version of libheif (1.0.5) just doesn't work, it can't decode any iPhone photo, just failing with `codec not supported`.

I had to update both `libde265` to `v1.0.8` and `libheif` to `v1.9.1` to get it working.

[I have committed my code in this fork](https://github.com/Ziriax/vcpkg/tree/libheif_v1_9_1), if you prefer I can make a PR.

### PR DESCRIPTION
**Pull request by JonLiu1993**
Fix #14437 

Update libheif to the latest version 1.9.1

Note : No feature need to test

### CODE REVIEW

**Comment by Ziriax** [comment]
Nice! 

I think you also need to update the libde265 package to get libheif to work correctly, the former has a couple of fixes: https://github.com/strukturag/libde265/releases

I already did this in my fork: https://github.com/Ziriax/vcpkg/commit/0640124d19e6f1472cc34fdd7a45ab847ced1f4f

**Comment by NancyLi1013** [comment]
Needs to update `libde265 ` in PR #14497 first.

**Comment by JonLiu1993** [comment]
Duplicate to #14648

**Pull request closed without merging**
