### PR TITLE
[ffmpeg] Enable dav1d feature on osx

### PR DESCRIPTION
**Pull request by horenmar**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Review by autoantwort — APPROVED** [review]

**Comment by FrankXie05** [comment]
Is there any official explanation? why support it? :)

**Comment by autoantwort** [comment]
I thing there is no official explanation that states that it is not supported. I builds => should not be marked as unsupported.

**Comment by FrankXie05** [comment]
The feature `dav1d` has been tested successfully locally.

**Review by FrankXie05 — APPROVED** [review]

**Comment by BillyONeal** [comment]
I merged with master to make sure this plays nicely with dav1d update we just merged

**Comment by BillyONeal** [comment]
Thanks!

**Pull request merged**
