### PR TITLE
[catch2] Don't install docs

### PR DESCRIPTION
**Pull request by Thomas1664**
**Describe the pull request**

- #### What does your PR fix?
  Disable installing docs

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  unchanged

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
 Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by Thomas1664** [comment]
@FrankXie05 Why requires:author-response?

**Comment by FrankXie05** [comment]
@Thomas1664 Could you please explain why want to turn off the option to download documents? :)

**Comment by Thomas1664** [comment]
> @Thomas1664 Could you please explain why want to turn off the option to download documents? :)

Our policy is to not install docs by default.
Copying docs takes time (not much here, though)

**Review by FrankXie05 — APPROVED** [review]

**Comment by strega-nil-ms** [comment]
Thanks!

**Pull request merged**
