### PR TITLE
[grpc] Upgrade to gRPC-1.26.0

### LINKED ISSUE #8453: [grpc] update to 1.24.1
Library name: gRPC

New version number:  v1.24.1

### PR DESCRIPTION
**Pull request by coryan**
This updates gRPC to 1.26.0. I removed a number of patches that are no longer needed,
and updated existing patches to match the new line numbers.

This fixes #8453 

I do not believe this patch breaks or fixes any particular triplets, but I am less certain about the UWP triplets.

### CODE REVIEW

**Comment by JackBoosY** [comment]
From UWP build log:
```
8>C:\vsts\_work\4\s\buildtrees\grpc\src\v1.26.0-152e906888\src\core\lib\security\credentials\alts\check_gcp_environment_windows.cc(48,15): error C2039:  'RegGetValueA': is not a member of '`global namespace'' [C:\vsts\_work\4\s\buildtrees\grpc\x64-uwp-dbg\grpc.vcxproj]
```

The [documentation](https://docs.microsoft.com/en-us/windows/win32/api/winreg/nf-winreg-reggetvaluea) shows:

  |  
-- | --
Minimum supported client | Windows Vista, Windows XP Professional x64 Edition [desktop apps only]
Minimum supported server | Windows Server 2008, Windows Server 2003 with SP1 [desktop apps only]

So I think the function `RegGetValue` needs to be changed to another suitable function.

**Comment by coryan** [comment]
> From UWP build log:
> 
[snip]
> So I think the function `RegGetValue` needs to be changed to another suitable function.

I disabled the GCE checks on UWP, just like they were on the previous version.  I really doubt folks will be deploying UWP applications to GCE instances, and the only downside (that I know of, at least at this time) is some more complicated authentication configuration if you are trying to access Google services via gRPC.

**Review by JackBoosY — APPROVED** [review]

**Comment by PhoebeHui** [comment]
@jozefizso, would you like to help review this PR?

**Review by PhoebeHui — APPROVED** [review]

**Comment by jozefizso** [comment]
@PhoebeHui definitely not. You threw away my contribution and I should work on someone else code? Why?

**Comment by dan-shaw** [comment]
@coryan This PR looks good to me. We're going to merge #9135 before merging this one.

**Comment by coryan** [comment]
@dan-shaw that is fine.  Once you do, I will see if a simple rebase works, but if not I might have to close this PR and start over (no biggie if that is the case).

In the future, would you like me to preserve existing patches?  What if they stop working?  Should I delete them or replace them?

**Comment by dan-shaw** [comment]
@coryan Thanks - that would be great. The only conflict should be the UWP patch.

If patches stop working (but are still relevant), update the respective patch files.
If patches stop working (and are not relevant anymore), remove the patch files.

In either case, if a patch file is unsuccessfully applied, it should fail in the CI.

**Comment by dan-shaw** [comment]
@coryan I've merged #9135

**Comment by coryan** [comment]
I just rebased this PR, in detail, this is why I changed the patches:

* The `00001-*.patch` modified 3 files:
  * The changes to `CMakeLists.txt` did not apply due to line number and context changes. I manually applied the same changes, except for the `gRPC_BUILD_CODEGEN` changes that they do not seem to be applicable anymore.
   * I updated the patch to `src/core/lib/iomgr/resource_quota.cc`.
   * The code in `src/core/lib/security/credentials/alts/check_gcp_environment_windows.cc` changed, I made an equivalent patch (remove GCE detection when compiled with UWP).

* The `0000[235]-*.patch` files needed to be updated with new line numbers and context.
* The `00007-*.patch` file is no longer needed, equivalent changes to disable the `grpc_channelz` with protobuf lite are applied upstream.

I installed `grpc` with `x64-linux`, `x64-uwp`, `x64-windows-static`, and `x86-windows`. We will see what the CI system has to say.

**Comment by coryan** [comment]
@dan-shaw PTAL

**Comment by dan-shaw** [comment]
LGTM

**Pull request merged**
