### PR TITLE
[pcl] Add gcc version check

### PR DESCRIPTION
**Pull request by NancyLi1013**
Using `std::random_device `and `std::mt19937` needs `c++17` if gcc version is below 6.0.

So I add this to CMakeLists.txt.
```
if(UNIX AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS 6.0)
    set (CMAKE_CXX_STANDARD 17)
endif()
```

Related issue #8998.

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by vicroms** [comment]
Regression on MacOS

```
FAILED: common/CMakeFiles/pcl_common.dir/src/fft/kiss_fft.c.o 
/Library/Developer/CommandLineTools/usr/bin/cc -DvtkDomainsChemistry_AUTOINIT="1(vtkDomainsChemistryOpenGL2)" -DvtkIOExport_AUTOINIT="2(vtkIOExportOpenGL2,vtkIOExportPDF)" -DvtkRenderingContext2D_AUTOINIT="1(vtkRenderingContextOpenGL2)" -DvtkRenderingCore_AUTOINIT="3(vtkInteractionStyle,vtkRenderingFreeType,vtkRenderingOpenGL2)" -DvtkRenderingOpenGL2_AUTOINIT="1(vtkRenderingGL2PSOpenGL2)" -DvtkRenderingVolume_AUTOINIT="1(vtkRenderingVolumeOpenGL2)" -I/Users/vagrant/myagent/_work/2/s/buildtrees/pcl/src/pcl-1.9.1-2b52dd20fc/recognition/include/pcl/recognition/3rdparty -I/Users/vagrant/myagent/_work/2/s/installed/x64-osx/share/vtk/../../include -I/Users/vagrant/myagent/_work/2/s/installed/x64-osx/share/vtk/../../include/eigen3 -I/Users/vagrant/myagent/_work/2/s/installed/x64-osx/share/vtk/../../include/double-conversion -Iinclude -I/Users/vagrant/myagent/_work/2/s/buildtrees/pcl/src/pcl-1.9.1-2b52dd20fc/common/include -isystem /Users/vagrant/myagent/_work/2/s/installed/x64-osx/include/eigen3 -isystem /Users/vagrant/myagent/_work/2/s/installed/x64-osx/include -fPIC  -g -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk   -std=c++17 -MD -MT common/CMakeFiles/pcl_common.dir/src/fft/kiss_fft.c.o -MF common/CMakeFiles/pcl_common.dir/src/fft/kiss_fft.c.o.d -o common/CMakeFiles/pcl_common.dir/src/fft/kiss_fft.c.o   -c /Users/vagrant/myagent/_work/2/s/buildtrees/pcl/src/pcl-1.9.1-2b52dd20fc/common/src/fft/kiss_fft.c
error: invalid argument '-std=c++17' not allowed with 'C'
```

**Comment by dan-shaw** [comment]
Closing PR due to inactivity. Please reopen if this is ongoing work.

**Pull request merged**
