### PR TITLE
[boost] update to 1.73.0

### LINKED ISSUE #3495: New ports: python2, boost-python2 and boost-python3
With Boost v1.67 is possible to build variants for multiple Python versions in a single build process. For example, a variant compiled with Python 2.7 will produce library names boost_python27 and boost_numpy27, etc.

Unfortunately, vcpkg hasn't port for python2.

### LINKED ISSUE #11035: [New Port Request] boost-nowide
Library name: boost-nowide

Library description: Boost nowide nowide module (it makes it easier to handle Unicode (UTF-8) I/O in Windows without `wchar_t`)

Source repository URL: https://github.com/boostorg/nowide

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
Windows API prefers `wchar_t` as characters type for I/O rather than `char`, but this is a Galapagosized behavier and lacks compatibility with and code portability to other OSes (macOS, Linux, and other POSIX OSes).
Other major OSes treat `char` as UTF-8 but Windows usually do not.  But you can force Windows to do so with the help of this library.

### LINKED ISSUE #11147: [boost] update to 1.73.0
Library name: Boost

New version number: 1.73.0

### PR DESCRIPTION
**Pull request by yurybura**
Updates Boost to 1.73.0.
Release Notes: https://www.boost.org/users/history/version_1_73_0.html

Fixes #11147
Fixes #11035
Fixes #3495

### CODE REVIEW

**Comment by BillyONeal** [comment]
There are still ports that list `boost-disjoint-sets` as a dependency, so vcpkg is unable to proceed.

**Comment by yurybura** [comment]
> There are still ports that list `boost-disjoint-sets` as a dependency, so vcpkg is unable to proceed.
Thank you for help. I didn't catch this from the original error message..

**Comment by PhoebeHui** [comment]
https://github.com/microsoft/vcpkg/tree/master/ports/nowide should be removed when this PR merged.

**Review by PhoebeHui — APPROVED** [review]
Thank you as always!

**Comment by PhoebeHui** [comment]
The CI test pass! thanks for the quick updates!

**Comment by yurybura** [comment]
> The CI test pass! thanks for the quick updates!

I hope the vcpkg's team could review and merge it quickly too)

**Review by dan-shaw — APPROVED** [review]

**Comment by strega-nil** [comment]
Alright, awesome, thanks @yurybura :D

**Pull request merged**
