### PR TITLE
[libsbsms] add new port with version 2.3.0

### PR DESCRIPTION
**Pull request by Be-ing**
**Describe the pull request**

I am not sure whether to call this new port `sbsms` or `libsbsms`. I initially tried `libsbms`, but then `find_package(sbsms)` and `find_package(libsbsms)` both failed to find the CMake config module installed by the library's build system.

- #### What does your PR fix?  
  Adds libsbsms port

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

### CODE REVIEW

**Comment by JonLiu1993** [comment]
@Be-ing ,Please run the command "./vcpkg x-add-version sbsms --overwrite-version" then commit the changes again.

**Comment by Be-ing** [comment]
Thoughts on naming the port "libsbsms" versus "sbsms"?

**Comment by ras0219** [comment]
Upstream's name for it appears to be `libsbms`, so we'd prefer that name:

https://github.com/claytonotey/libsbsms
>libsbsms is a library for high quality time and pitch scale modification. It uses octave subband sinusoidal modeling.

**Comment by Be-ing** [comment]
> I initially tried libsbms, but then find_package(sbsms) and find_package(libsbsms) both failed to find the CMake config module installed by the library's build system.

Any ideas what is going wrong with this?

**Comment by JonLiu1993** [comment]
The following cmake code can be used successfully:
```cmake
    find_package(sbsms CONFIG REQUIRED)
    target_link_libraries(main PRIVATE sbsms::sbsms)
```

**Comment by Be-ing** [comment]
I had to change the vcpkg_cmake_config_fixup call to:

```
vcpkg_cmake_config_fixup(CONFIG_PATH "lib/cmake/sbsms" PACKAGE_NAME sbsms)
```

Now `find_package(sbsms)` works.

**Comment by JonLiu1993** [comment]
@Be-ing ,As @ras0219  said, have you considered naming the new port for libsbms? Upstream's name for it appears to be libsbms

**Comment by Be-ing** [comment]
Yes, I switched it back to "libsbsms" now that I got the CMake config module to work. Sorry, I forgot to update the title of the PR.

**Review by JonLiu1993 — APPROVED** [review]

**Comment by ras0219-msft** [comment]
LGTM, thanks for the PR and sorry for the long merge delay!

**Pull request merged**
