### PR TITLE
[zziplib] Update to 0.13.72

### PR DESCRIPTION
**Pull request by chausner**
**Describe the pull request**

- #### What does your PR fix?  
  Updates zziplib to 0.13.72

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  As before, Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run ./vcpkg x-add-version --all and committed the result?  
  Yes

### CODE REVIEW

**Comment by Cheney-W** [comment]
@chausner 
Is this PR ready to be reviewed? If yes, please click the `Ready for review button`. Thank you!

**Comment by chausner** [comment]
> @chausner Is this PR ready to be reviewed?

I see CI is succeeding but I think there was some issue remaining which I wasn't able to fix. I can't remember the details anymore.

**Comment by Cheney-W** [comment]
OK, keep this PR as a  draft until you think the job is done. Thank you!

**Comment by Cheney-W** [comment]
Pinging @chausner  for response. Are you still working on this PR?

**Comment by chausner** [comment]
> Pinging @chausner for response. Are you still working on this PR?

I am no longer working on it. I'll close it.

**Pull request closed without merging**
