### PR TITLE
[EasyCL] New GitHub Repository

### PR DESCRIPTION
**Pull request by ghost**
Here is the [GitHub Repository](https://github.com/architector1324/EasyCL) made by [architector1324](https://github.com/architector1324).

### CODE REVIEW

**Comment by cbezault** [comment]
Thanks for the PR!

It appears that in order to use EasyCL a user must have OpenCL installed.
Could you please add OpenCL to the list of dependencies for EasyCL?

Thanks

**Comment by xorz57** [comment]
@cbezault Can you help me with it?

**Comment by xorz57** [comment]
Should I just write the following?

```
Build-Depends: opencl
```

**Comment by cbezault** [comment]
Yup, that should be sufficient since EasyCL just requires that OpenCL be installed for someone to use EasyCL, not to build it.

**Comment by xorz57** [comment]
@cbezault, thanks!

**Pull request merged**
