### PR TITLE
[ktx] Update to 4.1.0-rc3.

### PR DESCRIPTION
**Pull request by maoliver-amd**
This also fixes a compilation error with the previous port version (4.1.0-rc2) when using feature ktx[tools].

### CODE REVIEW

**Comment by maoliver-amd** [comment]
linux build error seems to be about missing libtool
Is this a known issue on the CI?

**Comment by JonLiu1993** [comment]
> linux build error seems to be about missing libtool Is this a known issue on the CI?

````
FAILED: libktx.a 
: && /mnt/vcpkg-ci/downloads/tools/cmake-3.24.0-linux/cmake-3.24.0-linux-x86_64/bin/cmake -E rm -f libktx.a && /usr/bin/ar qc libktx.a  CMakeFiles/ktx.dir/lib/basis_transcode.cpp.o CMakeFiles/ktx.dir/lib/basisu/transcoder/basisu_transcoder.cpp.o CMakeFiles/ktx.dir/lib/checkheader.c.o CMakeFiles/ktx.dir/lib/dfdutils/createdfd.c.o CMakeFiles/ktx.dir/lib/dfdutils/colourspaces.c.o CMakeFiles/ktx.dir/lib/dfdutils/interpretdfd.c.o CMakeFiles/ktx.dir/lib/dfdutils/printdfd.c.o CMakeFiles/ktx.dir/lib/dfdutils/queries.c.o CMakeFiles/ktx.dir/lib/dfdutils/vk2dfd.c.o CMakeFiles/ktx.dir/lib/etcdec.cxx.o CMakeFiles/ktx.dir/lib/etcunpack.cxx.o CMakeFiles/ktx.dir/lib/filestream.c.o CMakeFiles/ktx.dir/lib/hashlist.c.o CMakeFiles/ktx.dir/lib/info.c.o CMakeFiles/ktx.dir/lib/memstream.c.o CMakeFiles/ktx.dir/lib/strings.c.o CMakeFiles/ktx.dir/lib/swap.c.o CMakeFiles/ktx.dir/lib/texture.c.o CMakeFiles/ktx.dir/lib/texture2.c.o CMakeFiles/ktx.dir/lib/vkformat_check.c.o CMakeFiles/ktx.dir/lib/vkformat_str.c.o CMakeFiles/ktx.dir/lib/gl_funcs.c.o CMakeFiles/ktx.dir/lib/glloader.c.o CMakeFiles/ktx.dir/lib/texture1.c.o CMakeFiles/ktx.dir/lib/basis_encode.cpp.o CMakeFiles/ktx.dir/lib/astc_encode.cpp.o CMakeFiles/ktx.dir/lib/basisu/encoder/basisu_backend.cpp.o CMakeFiles/ktx.dir/lib/basisu/encoder/basisu_basis_file.cpp.o CMakeFiles/ktx.dir/lib/basisu/encoder/basisu_bc7enc.cpp.o CMakeFiles/ktx.dir/lib/basisu/encoder/basisu_comp.cpp.o CMakeFiles/ktx.dir/lib/basisu/encoder/basisu_enc.cpp.o CMakeFiles/ktx.dir/lib/basisu/encoder/basisu_etc.cpp.o CMakeFiles/ktx.dir/lib/basisu/encoder/basisu_frontend.cpp.o CMakeFiles/ktx.dir/lib/basisu/encoder/basisu_gpu_texture.cpp.o CMakeFiles/ktx.dir/lib/basisu/encoder/basisu_kernels_sse.cpp.o CMakeFiles/ktx.dir/lib/basisu/encoder/basisu_opencl.cpp.o CMakeFiles/ktx.dir/lib/basisu/encoder/basisu_pvrtc1_4.cpp.o CMakeFiles/ktx.dir/lib/basisu/encoder/basisu_resample_filters.cpp.o CMakeFiles/ktx.dir/lib/basisu/encoder/basisu_resampler.cpp.o CMakeFiles/ktx.dir/lib/basisu/encoder/basisu_ssim.cpp.o CMakeFiles/ktx.dir/lib/basisu/encoder/basisu_uastc_enc.cpp.o CMakeFiles/ktx.dir/lib/writer1.c.o CMakeFiles/ktx.dir/lib/writer2.c.o && /usr/bin/ranlib libktx.a && cd /mnt/vcpkg-ci/buildtrees/ktx/x64-linux-dbg && libtool -static -o /mnt/vcpkg-ci/buildtrees/ktx/x64-linux-dbg/libktx.a /mnt/vcpkg-ci/buildtrees/ktx/x64-linux-dbg/libktx.a /mnt/vcpkg-ci/buildtrees/ktx/x64-linux-dbg/lib/astc-encoder/Source/libastcenc-avx2-static.a
/bin/sh: 1: libtool: not found
ninja: build stopped: subcommand failed.
````
From the error log, It seems not ci issue, I will rerun the ci and look the result

**Comment by dg0yt** [comment]
> linux build error seems to be about missing libtool

It is quite unusual that CMake projects use libtool. And ktx doesn't apply the same steps for Windows.
But `libtool` is installed in CI:
https://github.com/microsoft/vcpkg/blob/86eb754bce1ac2087cbf8351a11015a9df7ca8dd/scripts/azure-pipelines/linux/provision-image.sh#L19

**Comment by dg0yt** [comment]
> But `libtool` is installed in CI:

Wait, this package brings only `libtoolize`. And autotools packages create a local tool. That's why the are not affected.

The global `/usr/bin/libtool` is in Ubuntu package `libtoolize` which is not installed in CI. CC @BillyONeal.

**Comment by BillyONeal** [comment]
VM update queued with this added. Will keep you posted.

**Comment by BillyONeal** [comment]
VM update landed. Pushed merge with `master` to pick that up.

**Comment by JonLiu1993** [comment]
All features are tested successfully in the following triplet:
- x64-windows
- x64-windows-static

**Comment by JonLiu1993** [comment]
@maoliver-amd , Please sign in the CLA.

**Comment by maoliver-amd** [comment]
> @maoliver-amd , Please sign in the CLA.

I have signed the CLA as I have contributed previously. Im not sure why the license/cla check is no longer working as my last PR was fine.

**Comment by maoliver-amd** [comment]
> 

@microsoft-github-policy-service agree [company="AMD"]

**Comment by maoliver-amd** [comment]
@microsoft-github-policy-service agree company="AMD"

**Review by JonLiu1993 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks!

**Pull request merged**
