### PR TITLE
[vcpkg] Fix name clash (e.g. "all" build for triplet x64-windows-release and "release" build for triplet x64-windows).

### PR DESCRIPTION
**Pull request by mkhon**
Describe the pull request
This fixes name clash still left after 7534d24
	•	What does your PR fix?
	•	Which triplets are supported/not supported? Have you updated the CI baseline?
all
	•	Does your PR follow the maintainer guide?
Yes
	•	If you have added/updated a port: Have you run ./vcpkg x-add-version --all and committed the result?
N/A
If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/

### CODE REVIEW

**Comment by mkhon** [comment]
This is re-open of #22501

.combined name change does not make sense to me as the filenames that conflict here are:
- ${CURRENT_BUILDTREES_DIR}/cmake-vars-${TARGET_TRIPLET}.${VCPKG_BUILD_TYPE}.cmake.log (line 43), when building for TARGET_TRIPLET=x64-windows, VCPKG_BUILD_TYPE=release
- ${CURRENT_BUILDTREES_DIR}/cmake-vars-${TARGET_TRIPLET}.cmake.log (line 46), when building for TARGET_TRIPLET=x64-windows-release

**Comment by dg0yt** [comment]
> .combined name change does not make sense to me as the filenames that conflict here are:
> 
> * ${CURRENT_BUILDTREES_DIR}/cmake-vars-${TARGET_TRIPLET}.${VCPKG_BUILD_TYPE}.cmake.log (line 43), when building for TARGET_TRIPLET=x64-windows, VCPKG_BUILD_TYPE=release
> * ${CURRENT_BUILDTREES_DIR}/cmake-vars-${TARGET_TRIPLET}.cmake.log (line 46), when building for TARGET_TRIPLET=x64-windows-release

I think the idea was to always `set(cmake_vars_file "${CURRENT_BUILDTREES_DIR}/cmake-vars-${TARGET_TRIPLET}-combined.cmake.log")`. So for each suffix in combined, rel, dbg, it is clear that triplet ends before the suffix.

**Comment by BillyONeal** [comment]
As I said back in https://github.com/microsoft/vcpkg/pull/22501/ , I don't like whether something is a "-" vs "." to be "load bearing" like this. If the names are conflicting we should pick one or the other to "own" the pattern and add actual name text to distinguish the other rather than only punctuation.

**Comment by BillyONeal** [comment]
> I think the idea was to always `set(cmake_vars_file "${CURRENT_BUILDTREES_DIR}/cmake-vars-${TARGET_TRIPLET}-combined.cmake.log")`. So for each suffix in combined, rel, dbg, it is clear that triplet ends before the suffix.

That would work!

**Comment by mkhon** [comment]
> > .combined name change does not make sense to me as the filenames that conflict here are:
> > 
> > * ${CURRENT_BUILDTREES_DIR}/cmake-vars-${TARGET_TRIPLET}.${VCPKG_BUILD_TYPE}.cmake.log (line 43), when building for TARGET_TRIPLET=x64-windows, VCPKG_BUILD_TYPE=release
> > * ${CURRENT_BUILDTREES_DIR}/cmake-vars-${TARGET_TRIPLET}.cmake.log (line 46), when building for TARGET_TRIPLET=x64-windows-release
> 
> I think the idea was to always `set(cmake_vars_file "${CURRENT_BUILDTREES_DIR}/cmake-vars-${TARGET_TRIPLET}-combined.cmake.log")`. So for each suffix in combined, rel, dbg, it is clear that triplet ends before the suffix.

I am not sure I understand. cmake-vars do not conflict with -rel or -dbg (because VCPKG_BUILD_TYPE is "release" or "debug", not "rel" or "dbg"). They conflict with each other in case TARGET_TRIPLET=windows-x64-release (no VCPKG_BUILD_TYPE) and TARGET_TRIPLET=windows-x64, VCPKG_BUILD_TYPE=release

**Comment by dg0yt** [comment]
Again, unconditionally 
~~~cmake
set(cmake_vars_file "${CURRENT_BUILDTREES_DIR}/cmake-vars-${TARGET_TRIPLET}-combined.cmake.log")
~~~
i.e. replace the `if-else-endif` from https://github.com/microsoft/vcpkg/commit/7534d241b08dc0c80d14c09f955c161e7cf5f92f. 

| triplet | file / build type | filename |
|--------|--------------------|-----------|
| x64-windows | combined | cmake-vars-x64-windows-combined.cmake |
|                       | included for release      | cmake-vars-x64-windows-rel.cmake |
|                       | included for debug       | cmake-vars-x64-windows-dbg.cmake |
| x64-windows-rel | combined | cmake-vars-x64-windows-rel-combined.cmake |
|                       | included for release      | cmake-vars-x64-windows-rel-rel.cmake |
|                       | (not) included for debug       | cmake-vars-x64-windows-rel-dbg.cmake |
| x64-windows-release | combined | cmake-vars-x64-windows-release-combined.cmake |
|                       | included for release      | cmake-vars-x64-windows-release-rel.cmake |
|                       | (not) included for debug       | cmake-vars-x64-windows-release-dbg.cmake |

**Comment by dg0yt** [comment]
Looking again at the problem which https://github.com/microsoft/vcpkg/commit/7534d241b08dc0c80d14c09f955c161e7cf5f92f: 
I assume you wanted to use a different combined file name because the content varies with `VCPKG_BUILD_TYPE` changes in the portfile. Let's remove this variation: always write both `include` lines, and do one of the following:
- use the `OPTIONAL` keyword for `include`.
- when `VCPKG_BUILDT_TYPE` is set, set the cache file variable to the actual file for that build type.

**Comment by JackBoosY** [comment]
Convert this PR to draft since there is no progress.

**Pull request closed without merging**
