### PR TITLE
[gmp] Fix usage

### PR DESCRIPTION
**Pull request by Adela0814**
For https://github.com/microsoft/vcpkg/issues/26290

Add usage file.

Tested usage on x64-windows.

### CODE REVIEW

**Review by Cheney-W — DISMISSED** [review]

**Comment by KiruyaMomochi** [comment]
I have installed the fixed GMP, and finished CMake configuration.
Unfortunately, I cannot build it successfully. Error messages are
```log
Demo.cpp.obj : error LNK2019: unresolved external symbol __imp___gmpz_init referenced in function "void __cdecl test_gmp(void)" (?test_gmp@@YAXXZ)
Demo.cpp.obj : error LNK2019: unresolved external symbol __imp___gmpz_probab_prime_p referenced in function "void __cdecl test_gmp(void)" (?test_gmp@@YAXXZ)
Demo.cpp.obj : error LNK2019: unresolved external symbol __imp___gmpz_set_str referenced in function "void __cdecl test_gmp(void)" (?test_gmp@@YAXXZ)
Demo\Demo.exe : fatal error LNK1120: 3 unresolved externals
```

My CMake commands for GMP are
```cmake
find_package (gmp CONFIG REQUIRED)
target_link_libraries (Demo gmp::gmp)
```

I'm using Visual Studio 2022.

It works on my environment after change `Config.cmake.in` to
```cmake
add_library(gmp::gmp SHARED IMPORTED)
set_target_properties(gmp::gmp PROPERTIES
    IMPORTED_IMPLIB "${_gmp_root}/lib/${CMAKE_IMPORT_LIBRARY_PREFIX}gmp${CMAKE_IMPORT_LIBRARY_SUFFIX}"
    IMPORTED_LOCATION "${_gmp_root}/bin/${CMAKE_SHARED_LIBRARY_PREFIX}gmp${CMAKE_SHARED_LIBRARY_SUFFIX}"
)
```

But I have not tested on other environments.

**Comment by JavierMatosD** [comment]
> For #26290
> 
> Add `Config.cmake.in` to export the usage.
> 
> Tested usage on x64-windows.
As @Neumann-A  indicated in https://github.com/microsoft/vcpkg/issues/26290#issuecomment-1212455612,  please add a usage file like this rather than adding the config files.

```
The package gmp provides PkgConfig files:

    #  gmp
    find_package(PkgConfig REQUIRED)
    pkg_check_modules(gmp REQUIRED IMPORTED_TARGET gmp)
    target_link_libraries(main PkgConfig::gmp)

    # gmpxx
    find_package(PkgConfig REQUIRED)
    pkg_check_modules(gmpxx REQUIRED IMPORTED_TARGET gmpxx)
    target_link_libraries(main PkgConfig::gmpxx)
```

**Comment by Adela0814** [comment]
> > For #26290
> > Add `Config.cmake.in` to export the usage.
> > Tested usage on x64-windows.
> > As @Neumann-A  indicated in [#26290 (comment)](https://github.com/microsoft/vcpkg/issues/26290#issuecomment-1212455612),  please add a usage file like this rather than adding the config files.
> 
> ```
> The package gmp provides PkgConfig files:
> 
>     #  gmp
>     find_package(PkgConfig REQUIRED)
>     pkg_check_modules(gmp REQUIRED IMPORTED_TARGET gmp)
>     target_link_libraries(main PkgConfig::gmp)
> 
>     # gmpxx
>     find_package(PkgConfig REQUIRED)
>     pkg_check_modules(gmpxx REQUIRED IMPORTED_TARGET gmpxx)
>     target_link_libraries(main PkgConfig::gmpxx)
> ```

Fixed.

**Review by JackBoosY — APPROVED** [review]
I really hope that vcpkg can automatically print these pkgconfig related usage, but the current conditions are not met.

**Comment by BillyONeal** [comment]
> I really hope that vcpkg can automatically print these pkgconfig related usage, but the current conditions are not met.

@ras0219-msft indicated that we don't do this right now because:

1. It isn't clear what CMake customers do when publishing their own configs; it isn't like 'just change `find_package` to `find_dependency` does the right thing here.
2. This won't actually do the right thing for most Windows customers because they won't have pkgconfig in their `PATH`. We would like some way where vcpkg fixes that before automating such instructions.
3. We need to have a story for this working or not in multiconfig CMake generators like msbuild and eclipse.

(He said that we shouldn't panic revert this PR but that it remains with some problems)

**Comment by Neumann-A** [comment]
> 3.	We need to have a story for this working or not in multiconfig CMake generators like msbuild and eclipse.

The story is just to fix `FindPkgConfig` and adjust its behavior for the two config dependent pkgconfig paths vcpkg offers. 

>2. This won't actually do the right thing for most Windows customers because they won't have pkgconfig in their PATH. We would like some way where vcpkg fixes that before automating such instructions.

pkgconfig doesn't need to be on path. Having port pkgconfig installed is enough for it to work. We could simply add this message to the message?

> 1. It isn't clear what CMake customers do when publishing their own configs; it isn't like 'just change find_package to find_dependency does the right thing here.

this is only important if the library is linked via the imported target PkgConfig generated. In that case find_dependency(PkgConfig) + pkg_<whatever_function_was_used_in_the_cmakelists.txt> is enough to make it work. If you link the PkgConfig target you need to import it for the consumers. (in the other case portfiles need to manually(?) adjust the interface_link_libraries entry to contain both configs of the libs they tried to link.)

I conclude the only important point here is to fix FindPkgConfig for the multi config case since this solves all the possible issues.

**Pull request merged**
