### PR TITLE
[raylib] Fix usage for raylib

### PR DESCRIPTION
**Pull request by observant2**
Hi!
The environment variable written in the usage file was wrong and it took me some time to figure out that my vcpkg installation wasn't broken. Feel free to merge. 🙂

### CODE REVIEW

**Comment by NancyLi1013** [comment]
Hi @itmuckel 

Thanks for your PR.

Could you please help describe what problem you encountered in using `raylib`?

Since I can compile it successfully with current usage.

**Comment by itmuckel** [comment]
Yes, compilation is no problem, but the usage was misleading. The variables in the usage were `RAYLIB` uppercased, while the actual variables were `raylib` lowercased. So when you copy the lines from the usage description, you need to look into the actual sources to find out how the environment variable is called.

**Comment by NancyLi1013** [comment]
Thanks for your feedback.

There is still error `fatal error: raylib.h: No such file or directory` with the usage you modified in this PR.

For original usage, it failed on Linux with link error. Please see https://github.com/microsoft/vcpkg/issues/16047

**Comment by NancyLi1013** [comment]
@itmuckel 

Are you willing to re-fix this problem?

**Comment by NancyLi1013** [comment]
Is work still being done for this PR? @itmuckel

**Comment by NancyLi1013** [comment]
Thanks for the PR; we're closing this for now since there's been no response. If you'd like to continue working on it, please reopen and ping us!

**Comment by FrankXie05** [comment]
@itmuckel Is work still being done for this PR?

**Pull request closed without merging**
