### PR TITLE
[alembic] add hdf5 dependency and fix link issue. #1545

### PR DESCRIPTION
**Pull request by ousttrue**
* Windows10(64bit)
* vs2017
* ``vcpkg.exe install alembic`` ok
* ``vcpkg.exe install alembic:x64-windows`` ok

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for the PR!

**Comment by ras0219-msft** [comment]
Since this changes the package's output, we also needed to bump the version number (6c22dbea).

**Comment by jasjuang** [comment]
@ousttrue @ras0219-msft This commit breaks the installation for me.

`vcpkg install alembic` shows the below error

``````
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:43 (message):
    Command failed: C:/Program Files/CMake/bin/cmake.exe;C:/dev/vcpkg/buildtrees/alembic/src/alembic-1.7.1;-DUSE_HDF5=ON;-DBUILD_SHARED_LIBS=ON;-DVCPKG_TARGET_TRIPLET=x64-windows-dev;-DCMAKE_CXX_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP ;-DCMAKE_C_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /MP ;-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON;-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE;-DCMAKE_VERBOSE_MAKEFILE=ON;-DVCPKG_APPLOCAL_DEPS=OFF;-DCMAKE_TOOLCHAIN_FILE=C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake;-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON;-DCMAKE_CXX_FLAGS_RELEASE=/MD /O2 /Oi /Gy /DNDEBUG /Zi ;-DCMAKE_C_FLAGS_RELEASE=/MD /O2 /Oi /Gy /DNDEBUG /Zi ;-DCMAKE_SHARED_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF ;-DCMAKE_EXE_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF ;-G;Visual Studio 14 2015 Win64;-DCMAKE_BUILD_TYPE=Release;-DCMAKE_INSTALL_PREFIX=C:/dev/vcpkg/packages/alembic_x64-windows-dev
    Working Directory: C:/dev/vcpkg/buildtrees/alembic/x64-windows-dev-rel
    See logs for more information:
      C:\dev\vcpkg\buildtrees\alembic\config-x64-windows-dev-rel-out.log
      C:\dev\vcpkg\buildtrees\alembic\config-x64-windows-dev-rel-err.log
``````

And here is `C:\dev\vcpkg\buildtrees\alembic\config-x64-windows-dev-rel-err.log`

``````
ILMBASE_ROOT is undefined
CMake Error at C:/Program Files/CMake/share/cmake-3.9/Modules/FindHDF5.cmake:450 (get_target_property):
  get_target_property called with incorrect number of arguments
Call Stack (most recent call first):
  cmake/AlembicHDF5.cmake:59 (FIND_PACKAGE)
  CMakeLists.txt:229 (INCLUDE)



   * Alembic Configuration          ===
   * USE_ARNOLD                     OFF
   * USE_BINARIES                   ON
   * USE_EXAMPLES                   OFF
   * USE_HDF5                       ON
   * USE_MAYA                       OFF
   * USE_PRMAN                      OFF
   * USE_PYALEMBIC                  OFF
   * USE_STATIC_BOOST               OFF
   * USE_STATIC_HDF5                OFF
   * USE_TESTS                      ON
   * ALEMBIC_ILMBASE_LINK_STATIC    OFF
   * ALEMBIC_SHARED_LIBS            ON
   * ALEMBIC_LIB_USES_BOOST         OFF
   * ALEMBIC_LIB_USES_TR1           OFF
``````

And here is `C:\dev\vcpkg\buildtrees\alembic\config-x64-windows-dev-rel-out.log`

``````
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE SYSTEM NAME: Windows
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Failed
-- The install dir is C:/dev/vcpkg/packages/alembic_x64-windows-dev
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE  
-- #define ILMBASE_VERSION_STRING "2.2.0"
-- ILMBASE INCLUDE PATH: C:/dev/vcpkg/installed/x64-windows-dev/include/OpenEXR
-- HALF LIB: C:/dev/vcpkg/installed/x64-windows-dev/lib/Half.lib
-- IEX LIB: C:/dev/vcpkg/installed/x64-windows-dev/lib/Iex-2_2.lib
-- IEXMATH LIB: C:/dev/vcpkg/installed/x64-windows-dev/lib/IexMath-2_2.lib
-- ILMTHREAD LIB: C:/dev/vcpkg/installed/x64-windows-dev/lib/IlmThread-2_2.lib
-- IMATH LIB: C:/dev/vcpkg/installed/x64-windows-dev/lib/Imath-2_2.lib
-- Found ZLIB: C:/dev/vcpkg/installed/x64-windows-dev/lib/zlib.lib (found version "1.2.11") 
-- Found HDF5: hdf5-shared (found version "1.10.0") found components:  C 
-- HDF5_INCLUDE_DIRS: C:/dev/vcpkg/installed/x64-windows-dev/include;C:/dev/vcpkg/installed/x64-windows-dev/include
-- HDF5_LIBRARIES: hdf5-shared
-- Configuring incomplete, errors occurred!
See also "C:/dev/vcpkg/buildtrees/alembic/x64-windows-dev-rel/CMakeFiles/CMakeOutput.log".
See also "C:/dev/vcpkg/buildtrees/alembic/x64-windows-dev-rel/CMakeFiles/CMakeError.log".
``````

**Comment by ousttrue** [comment]
@jasjuang

vcpkg my newly clone also has the same problem.
vcpkg/downloads/cmake-3.9.0-win32-x86/share/cmake-3.9/Modules/FindHDF5.cmake may break.
my cmake-3.8.0 version worked correctly.

**Comment by ousttrue** [comment]
https://gitlab.kitware.com/cmake/cmake/issues/17039

**Comment by jasjuang** [comment]
@ousttrue You are right, I just downgraded to cmake 3.8.0 and it works.... I was on cmake 3.9.0. How do we patch this?

**Comment by ras0219-msft** [comment]
We could hardcode all the relevant variables in the portfile's configure command: HDF5_FOUND, HDF5_LIBRARIES etc.

**Comment by ousttrue** [comment]
work around

ports/alembic/portfile.cmake
```cmake
SET(VCPKG_INSTALLED ${VCPKG_ROOT_DIR}/installed/${TARGET_TRIPLET})
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    OPTIONS 
    -DUSE_HDF5=ON
    -DHDF5_FOUND=1
    -DHDF5_INCLUDE_DIRS=${VCPKG_INSTALLED}/include
    -DHDF5_LIBRARIES=${VCPKG_INSTALLED}/lib/hdf5.lib
)
```

I will make PR later.

**Pull request merged**
