### PR TITLE
[freeimage, libwebp, OpenEXR, OpenVDB] Updates

### PR DESCRIPTION
**Pull request by vicroms**
This branch integrates changes from these PRs:
* `libwebp` (#5210)
* `openexr` (#5227)
* `freeimage` (#5228)
* `openvdb` (#5265) 

In order to avoid causing regressions in the `master` branch, it is necessary to merge all of these PRs together. 

@cenit please review these changes

### CODE REVIEW

**Comment by cenit** [comment]
@vicroms thanks. So in the end this time was better a unique big PR, I agree :)
I will check it today, will let you know afterwards

**Comment by cenit** [comment]
I put some comments , mainly related to `CMAKE_EXECUTABLE_SUFFIX`.
Apart from that, I tried building this branch and it LGTM.

**Comment by vicroms** [comment]
@cenit 

Thank you! 
Your PRs have been merged.

**Comment by cenit** [comment]
I think the review was not submitted?!? Anyway, thanks for the merge. Let's hope everything goes smooth in the next few days with people updating, this PR was very big. I will use it to continue working on OpenCV 4 👍

**Comment by liuzijing97** [comment]
Break IlmImf-2_3.dll and OpenEXR static build

**Pull request merged**
