### PR TITLE
[log4cplus] upgrade to v2.0.0rc2.

### PR DESCRIPTION
**Pull request by LazyWolfLin**
issues: #2230

### CODE REVIEW

**Comment by xoviat** [comment]
threadpool should be.a separate package. Copy the header from the include directory.

**Review by ghost — CHANGES_REQUESTED** [review]
Also this is wrong as the hash will change when master is updated

**Comment by LazyWolfLin** [comment]
threadpool is a small wrapper, there are not tag or other branch.

**Comment by LazyWolfLin** [comment]
[threadpool](https://github.com/log4cplus/ThreadPool) is a small wrapper. It seems to be used only by log4cplus.

**Comment by alexkaratarakis** [comment]
Thanks!

**Pull request merged**
