### PR TITLE
[gettext]Support Linux and OSX build

### LINKED ISSUE #13518: [gettext] msgfmt (and other gettext bin tools) missing on macOS & Windows
**Describe the bug**
macOS nor Windows  come with gettext by default. There is a gettext port in vcpkg,[ but it doesn't ship the \bin tools](https://github.com/microsoft/vcpkg/pull/245#issue-92014084). The `vcpkg_find_acquire_program()` does not offer it, either. Because of that reason, ports that require msgfmt binary tools (e.g. `kf5i18n`) fail to build on macOS and Windows.

~~What's even more puzzling, though, is that the vcpkg OS X Azure Pipeline [builds it just fine](https://dev.azure.com/vcpkg/public/_build/results?buildId=42873&view=logs&j=a83b7983-e539-5449-9e09-337ff5f52283&t=8636fc5b-b802-51ab-60e0-76e11f68a179&l=800), despite that gettext [is not one of the home-brew prerequisites](https://github.com/microsoft/vcpkg/blob/master/scripts/azure-pipelines/osx/configuration/VagrantFile) installed by vagrant.~~ EDIT: these pipeline builds were in fact false-positives and [were never actually executed](https://github.com/microsoft/vcpkg/pull/13467#issuecomment-692119190).

**Environment**
- OS: macOS 10.15.6, as well as Windows 10
- Compiler: Apple clang version 11.0.3 (clang-1103.0.32.62)

**To Reproduce**
1. Make sure you do not have a gettext brew package installed
2. `vcpkg install kf5i18`
3. See the error.

**Expected behavior**
1. Azure Pipeline build should fail just like the local build does
2. `vcpkg_find_acquire_program()` should include gettext tools

~~Alternatively, the way that OS X Azure Pipeline delivers a functioning set of gettext tools should be explicitly documented.~~ as explained above, this was a false-positive.

**Failure logs** 
```
CMake Error at /Volumes/External/Sourcecode/vcpkg/downloads/tools/cmake-3.17.2-osx/cmake-3.17.2-Darwin-x86_64/CMake.app/Contents/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find Gettext (missing: GETTEXT_MSGMERGE_EXECUTABLE
  GETTEXT_MSGFMT_EXECUTABLE)
Call Stack (most recent call first):
  /Volumes/External/Sourcecode/vcpkg/downloads/tools/cmake-3.17.2-osx/cmake-3.17.2-Darwin-x86_64/CMake.app/Contents/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  /Volumes/External/Sourcecode/vcpkg/downloads/tools/cmake-3.17.2-osx/cmake-3.17.2-Darwin-x86_64/CMake.app/Contents/share/cmake-3.17/Modules/FindGettext.cmake:81 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /Volumes/External/Sourcecode/vcpkg/scripts/buildsystems/vcpkg.cmake:478 (_find_package)
  /Volumes/External/Sourcecode/vcpkg/buildtrees/kf5i18n/x64-osx-dbg/cmake/KF5I18nMacros.cmake:5 (find_package)
  CMakeLists.txt:66 (include)
```

### PR DESCRIPTION
**Pull request by JackBoosY**
- [x] Support Linux Build
- [x] Support OSX Build
- [ ] Modify dependencies
- [ ] test

### CODE REVIEW

**Comment by JackBoosY** [comment]
@Neumann-A @Voskrese Could you test it?
I don't think the file generated now is complete.

**Comment by past-due** [comment]
I'm not sure this approach is necessary? There is already a `config.unix.h.in`, and code in the `CMakeLists.txt` to handle macOS / Linux builds. (Admittedly, it may need a little bit of tweaking for Linux, although a while ago I tested it on Ubuntu.)

Also, using `vcpkg_configure_make` builds for macOS (at least) is going to be problematic, as the gettext runtime's native configure / build scripts do various undesirable things, like trigger a messagebox to install a Java runtime (even if `--disable-java` is specified - this may depend on the version of macOS). I'd strongly encourage sticking with the current CMakeLists.txt setup for the port for macOS.

**Comment by JackBoosY** [comment]
@past-due Infact, if you need to use gettext in Linux and OSX, it is actually installed using apt / yum / brew instead of using gettext in vcpkg.
See code here:
https://github.com/microsoft/vcpkg/blob/5c415ff8a0aad831ee90ee4327f26992d5fe3fb3/ports/gettext/portfile.cmake#L7

**Comment by past-due** [comment]
@JackBoosY: Ah, to clarify: A little while back, I tested the gettext port with that
```cmake
if(VCPKG_TARGET_IS_LINUX)
    set(VCPKG_POLICY_EMPTY_PACKAGE enabled)
    ...
    return()
```
block removed, and it built on Ubuntu.

For reference: #4849

Also that block does not apply to macOS builds, which use the `config.unix.h.in` and logic in the CMakeLists.txt today. (I use these quite frequently, and actually fixed those macOS builds back in #4849.)

**Comment by JackBoosY** [comment]
@past-due I will have a try, thanks for the info.

**Comment by JackBoosY** [comment]
Replaced by #11776

**Pull request closed without merging**
