### PR TITLE
sdl1 x64-windows-static... ok

### PR DESCRIPTION
**Pull request by MVoz**
[sdl1.zip](https://github.com/Microsoft/vcpkg/files/3026246/sdl1.zip)

Starting package 1/33: sdl1:x64-windows-static
Building package sdl1[core]:x64-windows-static...
-- Using cached E:/tools/vcpkg/downloads/SDL-Mirror-SDL-release-1.2.15.tar.gz
-- Using source at E:/tools/vcpkg/buildtrees/sdl1/src/ase-1.2.15-2ca6426de6
-- Building VisualC/SDL1_2017.sln for Release
-- Building VisualC/SDL1_2017.sln for Debug
-- Installing: E:/tools/vcpkg/packages/sdl1_x64-windows-static/share/sdl1/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package sdl1[core]:x64-windows-static... done
Installing package sdl1[core]:x64-windows-static...

### CODE REVIEW

**Comment by cenit** [comment]
Judging from the open issues and from the fact that statically it builds, it is even possible that the initial check is wrong and must be switched to the opposite: static linkage (but only for library, not for crt)

**Comment by Voskrese** [comment]
?
```
if(VCPKG_CRT_LINKAGE STREQUAL "static")
    message(STATUS "Static CRT linkage is not supported")
    set(VCPKG_CRT_LINKAGE dynamic)
endif()
```

**Comment by cenit** [comment]
No that’s “old-style” and also opposite to the one that you need

**Comment by Voskrese** [comment]
Ok, I'll close it until I have time to deal with it. Although The static ok is collected and subsequent dependencies on it

**Comment by JuttaAnders** [comment]
IMHO the provided vcxproj files are not set correctly for a static build (ConfigurationType/RuntimeLibrary are wrong).
I've tried to make a patch about that applies on static builds only.
... on my computers it works just fine...
Pls have a loot at [https://github.com/Microsoft/vcpkg/pull/5885/commits/4d16626370d8bc4625e38a6c306447827428930e](https://github.com/Microsoft/vcpkg/pull/5885/commits/4d16626370d8bc4625e38a6c306447827428930e)

**Pull request closed without merging**
