### PR TITLE
[libmagic] Update port to build with CMake.

### PR DESCRIPTION
**Pull request by teo-tsirpanis**
- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] SHA512s are updated for each updated download
- [ ] The "supports" clause reflects platforms that may be fixed by this new version
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [X] Any patches that are no longer applied are deleted from the port's directory.
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

Contributes to #12636.

This PR rewrites the `libmagic` port to build with CMake and to export CMake targets and variables for consuming packages. It builds on top of TileDB-Inc/TileDB#4119 (which builds on top of https://github.com/TileDB-Inc/file-windows), and was adapted to handle more scenarios such as dynamic linking and cross compiling.

One other difference lies in the regex engine. Instead of using `tre` on Windows and the system's `regex.h` on Unix, we are now using PCRE2 everywhere. This was done for consistency among platforms.

### CODE REVIEW

**Comment by BillyONeal** [comment]
Restarting build to get it off macos machine #8

**Review by Osyotr — CHANGES_REQUESTED** [review]
#12636 is more of a "nice to have" than "must be done". There's no reason to vendor buildsystem inside vcpkg or at least I fail to see one. I do see two problems though: these changes effectively kill pkg-config support which is the usual way of consumption of the library and (more importantly) someone must maintain this vendored buildsystem.

**Comment by teo-tsirpanis** [comment]
Thanks @Osyotr, I tried using CMake's `FindPkgConfig` module and it worked great!

One question: I have a library that depends on libmagic. What to write in the installed config file? Is a `find_dependency(PkgConfig)` and `pkg_check_modules(libmagic IMPORTED_TARGET libmagic)` sufficient? And should the port for the library have a host dependency to `pkgconf`?

**Comment by teo-tsirpanis** [comment]
> keep the current status-quo where users should manually find an link to a package that comes from pkg-config

And have it fail with linker errors by default?

**Comment by Osyotr** [comment]
> > keep the current status-quo where users should manually find an link to a package that comes from pkg-config
> 
> And have it fail with linker errors by default?

Hmm I think you can fix it in wrapper. https://github.com/search?q=repo%3Amicrosoft%2Fvcpkg%20vcpkg-cmake-wrapper&type=code

**Comment by dg0yt** [comment]
> Hmm I think you can fix it in wrapper.

Wrap what? 
Wrapper are useful for dealing with official Find Modules from CMake. But there is no Find Module for libmagic.
Everything else is abuse. (You can provide CMake config instead.)

IMO pkg-config and cmake don't mix that bad (if not broken). The big problem for MSVC is multi-config support. This might be fixed with a wrapper.

**Comment by dg0yt** [comment]
> `find_dependency(PkgConfig)`

This is fine. Failure lets search continue.

> `pkg_check_modules(libmagic IMPORTED_TARGET libmagic)`

This is not so fine. In that form, failure will simly not create the target. You probably get an error in the generation step, when there is no definition for target `PkgConfig::libmagic`.

You might add the keyword `REQUIRED`. This won't let search continue on failure (as `find_dependency` does), but generates an immediate error. This is not so bad after all - vcpkg should have take care of providing libmagic, so we really have a problem if libmagic isn't found.

**Comment by teo-tsirpanis** [comment]
Thanks for the feedback @dg0yt, I will try hand-crafting a CMake config. Just opened #35134 that provides an unofficial config for `tre`.

**Comment by teo-tsirpanis** [comment]
Superseded by #35274.

**Pull request closed without merging**
