### PR TITLE
[vcpkg] ci.baseline.txt updates for 2021-09-13

### PR DESCRIPTION
**Pull request by BillyONeal**
Most recent CI build: https://dev.azure.com/vcpkg/public/_build/results?buildId=59428

REGRESSION: poppler:arm64-windows. If expected, add poppler:arm64-windows=fail to .\scripts\ci.baseline.txt.
PASSING, REMOVE FROM FAIL LIST: fontconfig:arm64-windows (.\scripts\ci.baseline.txt)

poppler depends on fontconfig, so this isn't actually a regression.

PASSING, REMOVE FROM FAIL LIST: libfreenect2:x64-linux

### CODE REVIEW

**Comment by autoantwort** [comment]
> PASSING, REMOVE FROM FAIL LIST: fontconfig:arm64-windows (.\scripts\ci.baseline.txt)

Is something like this also done for ports that are excluded by support expressions?

**Review by PhoebeHui — APPROVED** [review]

**Comment by BillyONeal** [comment]
>Is something like this also done for ports that are excluded by support expressions?

No. This is one of the reasons support expressions need to be related to what upstream says, and why changes due to infrastructure are done in ci.baseline.txt rather than supports.

**Comment by autoantwort** [comment]
Yeah I only asked because I have seen support expressions like `windows & !windows` but the package build without an error on windows (there are some other examples in https://github.com/microsoft/vcpkg/pull/20053). So it would have been cool if the ci reported that the support expression is to restrictive.

**Comment by cenit** [comment]
windows & !windows was for directx legacy port? it was done to avoid building in CI and to express its legacy nature

**Comment by autoantwort** [comment]
Yes. But we can't do that in the future with https://github.com/microsoft/vcpkg-tool/pull/184. If one want to express deprecation we should introduce a deprecated field.

**Pull request merged**
