### PR TITLE
[boost-interprocess] Fix build issue

### PR DESCRIPTION
**Pull request by Olli1080**
Add missing dependencies

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [x] The "supports" clause reflects platforms that may be fixed by this new version.
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by Olli1080** [comment]
Had a quick look and at least one boost test [unordered_test.cpp](https://github.com/boostorg/interprocess/blob/develop/test/unordered_test.cpp) uses unordered and integer is used by [interprocess_fwd.hpp](https://github.com/boostorg/interprocess/blob/develop/include/boost/interprocess/interprocess_fwd.hpp)

**Comment by dg0yt** [comment]
The boost ports intentionally do not build tests, and no test deps should be added to the core. 

We must also update the boost port generator script. I can pick this into my set boost changes.

**Comment by dg0yt** [comment]
https://github.com/microsoft/vcpkg/pull/38815 fixes the build issue without adding deps.

**Comment by Olli1080** [comment]
Closing in favor of #38815.

**Pull request closed without merging**
