### PR TITLE
Update boost-iostreams to the same style as the other Boost ports.

### LINKED ISSUE #4468: boost 1.68.0 dll names
All boost components are named `boost_[component]-vc141-mt-x64-1_68.dll`, except that `iostreams`  named `boost_iostreams-vc141-mt-x32-1_67.dll`

### PR DESCRIPTION
**Pull request by chrullrich**
Fixes #4468. I think.

### CODE REVIEW

**Comment by Rastaban** [comment]
I see a failure in the cartographer port on x64-windows and x86-windows.  It has a dependency on boost-iostreams.

**Comment by PhoebeHui** [comment]
@chrullrich, could you also update CONTROL revision in https://github.com/Microsoft/vcpkg/blob/master/ports/boost-iostreams/CONTROL?

See more information in https://github.com/Microsoft/vcpkg/blob/master/docs/maintainers/control-files.md

**Comment by Rastaban** [comment]
@ras0219-msft, you mentioned the other day that there was somthing about boost-iostreams that made it unique so you added the CMakeLists.txt.  Could you remind me what that was?  It was added for boost 1.67 and I am wondering if it still applies to 1.69 and also if it is related to the cartogropher port failures in this PR.

**Comment by ras0219-msft** [comment]
@chrullrich Thanks for the PR; the reason we have a separate style for this library compared to the other boost libraries is because:

1. The iostreams build is relatively simple (doesn't have complex assembly code or otherwise)
2. .. except for dependencies. We were unable to get boost build to reliably detect the dependencies, whereas it is trivial for CMake to do so. Therefore, rewriting the buildsystem in CMake is the best option available.

**Pull request closed without merging**
