### PR TITLE
[wxwidgets] Add 'WXWIDGETS_USE_STD_CONTAINERS' option

### PR DESCRIPTION
**Pull request by Karandra**
- #### What does your PR fix?  
  It adds a new option `WXWIDGETS_USE_STD_CONTAINERS` to set `wxUSE_STD_CONTAINERS` macro, which isn't controlled by `wxUSE_STL` that is set by `WXWIDGETS_USE_STL` option.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes, I think.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes.

### CODE REVIEW

**Comment by LilyWangLL** [comment]
Thanks for your PR. `vcpkg_fail_port_install` has been deprecated, VCPKG use `supports` in vcpkg.json instead of it. Could you please remove it in **portfile.cmake**?

**Review by LilyWangLL — APPROVED** [review]

**Comment by BillyONeal** [comment]
Hmm based on the documentation it appears that this causes breaking changes when turned on: https://docs.wxwidgets.org/trunk/overview_container.html

>The standard container build is mostly, but not quite, compatible with the default one
> [...]

I think that means it doesn't follow "do not use features to implement alternatives" https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-use-features-to-implement-alternatives

and as a result I think if you want this setting you really need to use an overlay port. Unless I have misunderstood the situation?

**Comment by Karandra** [comment]
That's not a feature though, just an option for a custom triplet that is off by default.

> Hmm based on the documentation it appears that this causes breaking changes when turned on:

It's the same as `wxUSE_STL` actually. I added similar option for `wxUSE_STD_CONTAINERS `. There's a discussion about it on https://github.com/microsoft/vcpkg/pull/19274, I don't really know what else I could add to this.

**Comment by BillyONeal** [comment]
> That's not a feature though, just an option for a custom triplet that is off by default.
> 
> > Hmm based on the documentation it appears that this causes breaking changes when turned on:
> 
> It's the same as `wxUSE_STL` actually. I added similar option for `wxUSE_STD_CONTAINERS `. There's a discussion about it on #19274, I don't really know what else I could add to this.

That does it as a triplet option, not a feature.

**Comment by BillyONeal** [comment]
Oh wait, I am blind. I could have swore I saw something in this PR that talked about using features to control this rather than a triplet option, let me review again.

**Review by BillyONeal — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks again!

**Pull request merged**
