### PR TITLE
[laszip] Migrate LASzip to the new manifest format.

### PR DESCRIPTION
**Pull request by CreMindES**
**Description**

- #### What does your PR fix?  
  Migrate [LASzip](https://github.com/LASzip/LASzip) to the preferred manifest format.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  `Yes`
  
- #### Note
  It also fixed an issue on Windows with MSVC where `LASZIP_ROOT` needed to be defined. With the new cmake configure and install functions this is no longer needed.

### CODE REVIEW

**Comment by JonLiu1993** [comment]
@CreMindES ,Thanks for your pr .
We recommend waiting for the new version of LASzip to be released, and port optimization should be performed when upgrading the new version.

**Comment by CreMindES** [comment]
> @CreMindES ,Thanks for your pr .
> We recommend waiting for the new version of LASzip to be released, and port optimization should be performed when upgrading the new version.

@JonLiu1993 Could you elaborate on the motivation behind that or point me to the a docs about it? I've looked but did not find much. 
Side note: the last release date of LASzip is Nov 2019 ...

**Comment by JackBoosY** [comment]
> > @CreMindES ,Thanks for your pr .
> > We recommend waiting for the new version of LASzip to be released, and port optimization should be performed when upgrading the new version.
> 
> @JonLiu1993 Could you elaborate on the motivation behind that or point me to the a docs about it? I've looked but did not find much.
> Side note: the last release date of LASzip is Nov 2019 ...

See https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#avoid-trivial-changes-in-untouched-files.

> It also fixed an issue on Windows with MSVC where LASZIP_ROOT needed to be defined. With the new cmake configure and install functions this is no longer needed.

I didn't find the related changes about this, can you confirm that?

**Review by PhoebeHui — APPROVED** [review]
LGTM

**Pull request merged**
