### PR TITLE
Disable boost-python for ARM

### PR DESCRIPTION
**Pull request by janisozaur**
`boost-python` depends on `python3`, which in turn depends on `libffi`,
which is not available for arm (see
https://github.com/microsoft/vcpkg/pull/6119, pending upstream release
3.3). Until this becomes fixed, drop `boost-python` from packages
`boost` depends on, so it can be built for arm.

https://github.com/microsoft/vcpkg/blob/75b4620da5c201d577426aafe101ecb045e7411b/ports/boost-python/CONTROL#L4
https://github.com/microsoft/vcpkg/blob/75b4620da5c201d577426aafe101ecb045e7411b/ports/python3/CONTROL#L5

### CODE REVIEW

**Comment by cenit** [comment]
> # Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

Fix also that script to not loose your patch next time boost is updated :)

(I repeat this phrase for every PR patch regarding boost...)

**Comment by janisozaur** [comment]
Sorry, but the script you refer to looks alien to me and I can't fix it. Can you please help me out? Also, the path seems to be `scripts/boost/generate-ports.ps1` rather than what you wrote.

**Review by JackBoosY — CHANGES_REQUESTED** [review]

**Comment by LilyWangL** [comment]
Pinging @janisozaur for response. Is work still being done for this PR?

**Comment by janisozaur** [comment]
Libffi has been merged to vcpkg since this PR was submitted, I think it should not be necessary anymore and effort should be out into fixing boost with libffi instead of disabling it.

**Pull request closed without merging**
