### PR TITLE
Patch Tuesday for January 2023

### PR DESCRIPTION
**Pull request by BillyONeal**
* Update pwsh to 7.4.1.
* Use a specific Docker base image to reduce the impact of accidentally cached Docker layers for Android as suggested by @ras0219-msft . (They only seem to mint a new base image every 2 months or so, so we still need the cache clear commands, but ...)

Also includes https://github.com/microsoft/vcpkg/pull/36141 to try the new tool for the full CI run.

### CODE REVIEW

**Comment by LilyWangLL** [comment]
`jasper` blocked by a VS bug https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1835847.

`portable-snippets` will be fixed by https://github.com/microsoft/vcpkg/pull/35791.

**Comment by dg0yt** [comment]
Could you perhaps pick libxcb-dri3-dev for linux from #36081?

**Comment by BillyONeal** [comment]
> `jasper` blocked by a VS bug https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1835847.

I don't think it's a VS bug, submitted https://github.com/jasper-software/jasper/pull/370

**Comment by BillyONeal** [comment]
> Could you perhaps pick libxcb-dri3-dev for linux from #36081?

Linux passed so I don't want to trigger a reset over that.

**Comment by BillyONeal** [comment]
> `portable-snippets` will be fixed by #35791.

I included a much more targeted fix here.

**Review by LilyWangLL — APPROVED** [review]

**Review by jimwang118 — APPROVED** [review]

**Pull request merged**
