### PR TITLE
[libcerf] Add new port

### LINKED ISSUE #7314: [New port request] libcerf
A self-contained numeric library that provides an efficient and accurate implementation of complex error functions, along with Dawson, Faddeeva, and Voigt functions.

Homepage: https://jugit.fz-juelich.de/mlz/libcerf

Used for example by gnuplot.

### PR DESCRIPTION
**Pull request by AlexanderTaeschner**
Resolves #7314.

### CODE REVIEW

**Comment by Voskrese** [comment]
@Rastaban 
for the sake of interest looked at the log, where there may be a bug
there are no errors

what could be the reason?

**Comment by Rastaban** [comment]
@Voskrese The error happened in the post build validation, which unfortunately is not captured in the logs that are written out under the projects buildtrees so you need to look at the console output under the `** Build vcpkg and test ports **` task in Azure DevOps.  I am interested in updating vcpkg to capture all console output into a port-specific log to avoid this hole in the CI system but haven't gotten around to it yet.

Here is the output:
```
Starting package 1/1: libcerf:x64-windows-static
Building package libcerf[core]:x64-windows-static...
Could not locate cached archive: C:\vsts\_work\1\s\archives\cb\cb32dd0a1b6524b38fab7dbf3b4f161ea7caf85d.zip
-- Downloading https://jugit.fz-juelich.de/mlz/libcerf/uploads/924b8d245ad3461107ec630734dfc781/libcerf-1.13.tgz...
-- Extracting source C:/vsts/_work/1/s/downloads/libcerf-1.13.tgz
-- Using source at C:/vsts/_work/1/s/buildtrees/libcerf/src/libcerf-1-0c1261ec09
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Installing: C:/vsts/_work/1/s/packages/libcerf_x64-windows-static/share/libcerf/copyright
-- Performing post-build validation
Expected Debug,Static crt linkage, but the following libs had invalid crt linkage:

    C:/vsts/_work/1/s/packages/libcerf_x64-windows-static/debug/lib/cerfcpp.lib: Release,Static

To inspect the lib files, use:
    dumpbin.exe /directives mylibfile.lib
Found 1 error(s). Please correct the portfile:
    C:\vsts\_work\1\s\ports\libcerf\portfile.cmake
-- Performing post-build validation done
Error: Building package libcerf:x64-windows-static failed with: POST_BUILD_CHECKS_FAILED
Elapsed time for package libcerf:x64-windows-static: 12.18 s

Triplet: x64-windows-static
Total elapsed time: 12.18 s
RESULTS
    libcerf:x64-windows-static: POST_BUILD_CHECKS_FAILED: 12.18 s

```

**Comment by Voskrese** [comment]
Alexander Taeschner

default in CMakeLists.txt

```
if(NOT DEFINED BUILD_SHARED_LIBS)
    option(BUILD_SHARED_LIBS "Build as shared library" ON)
endif()
```

static = `BUILD_SHARED_LIBS=OFF`

**Comment by Voskrese** [comment]
?
```
if(VCPKG_LIBRARY_LINKAGE STREQUAL dynamic)
  set(BUILD_SHARED_LIBS ON)
else()
  set(BUILD_SHARED_LIBS OFF)
endif()
```

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS
        -DCERF_CPP=ON
        -DLIB_MAN=OFF
        -DBUILD_SHARED_LIBS =${BUILD_SHARED_LIBS}
)

**Comment by AlexanderTaeschner** [comment]
@Voskrese: ypur proposed changes fail in post build validation. The question is, if it is a real problem stat the static build is not supported under windows (even the error message in CI reads: "##[error] NEW ADDED PORT FAILURE: libcerf:x64-windows-static (ignore if triplet is not supported by upstream port)").

**Comment by AlexanderTaeschner** [comment]
Added patch to enable libcerf:x64-windows-static build.

**Comment by cbezault** [comment]
While I think you're doing the right thing here to get it to compile statically it would also have been legitimate to use `vcpkg_check_linkage` to force the library to be built dynamically as upstream didn't have static support.

**Pull request merged**
