### PR TITLE
[pkg-config] new port

### PR DESCRIPTION
**Pull request by Neumann-A**
revived from an old PR since host tools are now a thing

### CODE REVIEW

**Comment by dg0yt** [comment]
I wonder how if this port might interact with `cmake_find_acquire_program(PKGCONFIG)` when building a port with a complex set of dependencies. Will all dependencies use the same pkg-config binary? If not, will the different pkg-config binaries give the same results? (In particular, how will pkg-config from this port handle system directories?)

**Review by JackBoosY — APPROVED** [review]

**Comment by Neumann-A** [comment]
vcpkg_find_aquire_program does not look into the installed tree by default and thus there is no interaction.  Since pkg-config is just used to discover libs/flags via standarized pc files the output should always be the same unless there is a bug. For system deps pkg-config probably uses the default behavior or relies on env variables.

**Comment by dg0yt** [comment]
Well, ports shouldn't depend on discovered pc files files anyway, so differences in discovered .pc file should not occur when dependencies are controlled properly.

TBH I'm surprised that the port is so straigtforward. Does this apply to using this port, too?
- Does it handle vcpkg's debug vs. release build types?
- Does it work for cross-compiling (Android, iOS, Mingw)?
  (This is were pkg-config really helps.)

Was this tested in some real project?
(I really miss tests in some areas of vcpkg, also as a synopsis of how things are meant to be used.)

Maybe it only needs some README how to use it correctly, unless it is really just a plain port dependency.

**Comment by Neumann-A** [comment]
@dg0yt The real challenge is to bootstrap glib without pkg-config after #13100 is merged. Meson does not make it that simple.

> Does it handle vcpkg's debug vs. release build types?

You need to setup `PKG_CONFIG_PATH` for this like `vcpkg_configure_make|meson|qmake` does it. In CMake this is done automatically via `CMAKE_PREFIX_PATH` and the vcpkg toolchain (Unless CMake paths are explicitly disabled for FindPkgConfig).

> Was this tested in some real project?

No but there is no magic here. It is just the pkg-config executable build using vcpkg. In the future vcpkg might want to fallback to this as a host-port after script stabilization. Then the real challenge lies in bootstrapping the port and its dependencies without using pkg-config. 

@ras0219-msft @strega-nil: If you intend to merge this one please run a CI test run where this is installed first. Otherwise CMake might pick up a lot of optional dependencies in ports which can suddenly be found due to `FindPkgConfig` actually working on windows.

**Comment by talregev** [comment]
vote up

**Comment by dg0yt** [comment]
> No but there is no magic here. It is just the pkg-config executable build using vcpkg. In the future vcpkg might want to fallback to this as a host-port after script stabilization.

I think pkg-config *must* be built for the host because it needs to run on the host. And then you will also have to set `PKG_CONFIG_LIBDIR` to stop pkg-config from looking up .pc files in default (host) directories. This is often done in wrapper scripts which come as \<autotools_triplet>-pkg-config.

**Comment by BillyONeal** [comment]
Should we replace uses of `vcpkg_find_acquire_program` with this?

**Comment by Neumann-A** [comment]
> Should we replace uses of vcpkg_find_acquire_program with this?

requires building of glib without pkg-config. Can be done, but is a bit more complicated.

**Comment by BillyONeal** [comment]
OK, then 99% sure this is OK but want to ask a few folks to confirm

**Comment by dg0yt** [comment]
> requires building of glib without pkg-config. Can be done, but is a bit more complicated.

Would it be easier when building `--with-internal-glib`? pkg-config being a tool not a library, the embedded copy seems more acceptable for bootstrapping purposes.

**Comment by ras0219-msft** [comment]
>Would it be easier when building --with-internal-glib? pkg-config being a tool not a library, the embedded copy seems more acceptable for bootstrapping purposes.

Agreed, I think this is the appropriate approach here.

>And then you will also have to set PKG_CONFIG_LIBDIR to stop pkg-config from looking up .pc files in default (host) directories.

Unfortunately, it's not quite as clean as that. Most users build targeting their host machines and there are some things that we _need_ to get from there (C library, drivers, core OS components). Users that want to opt-in to 100% host isolation can `set(ENV{PKG_CONFIG_LIBDIR} ...)` in the triplet file.

**Comment by Neumann-A** [comment]
I think we could bootstrap glib with `pkgconf` instead or generally use `pkgconf` instead of `pkg-config`. `pkgconf` should be a drop in replacement for `pkg-config`.
Otherwise bootstrapping glib could be done using `override_dependency` (https://github.com/mesonbuild/meson/issues/8224#issuecomment-763861461) together with [declare_dependency](https://mesonbuild.com/Reference-manual.html#declare_dependency)

**Comment by strega-nil-ms** [comment]
Since pkgconf seems like a strictly better pkg-config, is there a reason to merge both of these tools?

**Comment by Neumann-A** [comment]
> Since pkgconf seems like a strictly better pkg-config

Any real proof for that instead of people just saying it?

**Comment by strega-nil** [comment]
@Neumann-A I mean if you have opinions to the contrary, I'd love to hear them; I think we still need msys2 for autoconf on windows, so I'd like to avoid it, and I'd also like for us to standardize upon exactly one pkg-config solution.

**Comment by BillyONeal** [comment]
> I think we still need msys2 for autoconf on windows

There are lots of ports that need only pkgconfig though.

**Comment by talregev** [comment]
> There are lots of ports that need only pkgconfig though.

Why we can't have both and let the user decide what to install with vcpkg? 
Our opensource project is now using `pkg-config` to compile curl on linux and android with vcpkg.
I can imagine that there will be a user that will want to compile that on a linux base os that there isn't `pkg-config`
It really help that user to install it right away from vcpkg.

**Comment by dg0yt** [comment]
MSYS2 switch to pkgconf in November 2020, https://github.com/msys2/MINGW-packages/issues/7263

> we still need msys2 for autoconf on windows

Somewhat OT for this PR, but how many ports do really need to run autoconf when using official tarballs?

**Comment by Neumann-A** [comment]
> autoconf when using official tarballs?

@dg0yt: many, due to them shipping/using outdated versions of libtool/autotools which won't correctly work on windows. Basically configure was generated with an old version of autotools. 

@strega-nil: I don't have a strong opinion I am just saying that I don't see a strong reason to prefer one over the other. If vcpkg wishes to use `pkgconf` internally it can simply do so. Script stabilization will probably add a port for `vcpkg_fixup_pkgconfig` any way. Personally I would just use `find_program(PKGCONFIG NAMES pkgconf pkg-config)`. 
From a CMake perspective `FindPkgConfig` is not explicitly searching for `pkgconf` so it needs a symlink or an update to cmake itself. (Fun Fact: On windows it is also searching for `pkg-config.bat`)

**Comment by dg0yt** [comment]
> Fun Fact: On windows it is also searching for `pkg-config.bat`

Actually this makes sense: It would find a wrapper ~script~batch file which sets the environment variables as needed. In this way, you can configure pkg-config in a single spot.

> Personally I would just use find_program(PKGCONFIG NAMES pkgconf pkg-config).

In the first place, `FindPkgConfig` checks `ENV{PKG_CONFIG}`. This is used by cmake, by autotools and probably also by other systems. So write a single wrapper and set `ENV{PKG_CONFIG}` globally, early.

**Comment by Neumann-A** [comment]
> Actually this makes sense: It would find a wrapper scriptbatch file which sets the environment variables as needed. In this way, you can configure pkg-config in a single spot.

No it doesn't. Either the toolchain sets everything up (included env settings) or it should be at least symmetric and platform independent (like search for `pkg-config.sh` on unix)

> In the first place, FindPkgConfig checks ENV{PKG_CONFIG}

ENV{PKG_CONFIG} is always an option. But how `vcpkg.cmake` is currently setup it would automatically find `pkg-config` if it is installed into `tools/pkg-config/bin` due to:
https://github.com/microsoft/vcpkg/blob/63e7b48acfd30d52092986cd8f9e7c1c027a66b0/scripts/buildsystems/vcpkg.cmake#L654-L660

**Comment by dg0yt** [comment]
> it should be at least symmetric and platform independent (like search for `pkg-config.sh` on unix)

It is symmetric and platform independent: On Unix, the wrapper script would be literally called `pkg-config`. Or `<triplet>-pkg-condig` for cross-builds (Android, iOS, Mingw). Cf. tool calling conventions on https://autotools.io/pkgconfig/cross-compiling.html

On Windows, the limitation is in Cmake. It wouldn't consider `pkg-config.bat` for `find_program(PPP "pkg-config")`. But `find_program(PPP "pkg-config.bat")` works.

**Comment by dg0yt** [comment]
@Neumann-A 
> how `vcpkg.cmake` is currently setup it would automatically find `pkg-config` if it is installed into `tools/pkg-config/bin` due to:
> 
> https://github.com/microsoft/vcpkg/blob/63e7b48acfd30d52092986cd8f9e7c1c027a66b0/scripts/buildsystems/vcpkg.cmake#L654-L660

Please note that it would add `tools/pkg-config`, but *not* add `tools/pkg-config/bin`: This glob is not recursive.

**Comment by JackBoosY** [comment]
So... how is the progress now?

**Comment by talregev** [comment]
We doing a vote and then decide?

**Comment by talregev** [comment]
@Neumann-A @dg0yt Can you vote here?

**Comment by JackBoosY** [comment]
I think it's good, but I should wait for the consent of other members.

**Comment by BillyONeal** [comment]
> OK, then 99% sure this is OK but want to ask a few folks to confirm

I understand now: pkg-config requires a bunch of msys things anyway so that wouldn't actually fix anything.

If we want a better non-msys provider for this, it seems like it would be better to use the existing port `pkgconf`.

If we don't intend to replace the `vcpkg_find_acquire_program` uses, do we have a specific library use case here (given that vcpkg does not intend to provide standalone tools)?

**Comment by dg0yt** [comment]
AFAIU `pkgconf` should work well enough. A few days ago I was trying to create a port to leverage `pkgconf` instead of msys pkgconfig, in order to test its usability and fix the lack of generalized pkgconfig setup which also includes `vcpkg_cmake_configure`. (That's how I found the meson mingw issue BTW.) It could work well for classic mode. However, I miss a way to safely detect the host triplet / host tool path in manifest mode. Any ideas?  The point is that `ENV{PKG_CONFIG}` needs to point to the host tool path. But`vcpkg-cmake-config.cmake` is not loaded in manifest mode...

**Comment by Neumann-A** [comment]
all `vcpkg(_*)_configure(_*)` functions should have an option `NO_PKG_CONFIG` which disables `PKG_CONFIG` lookup via `vcpkg_find_acquire_program` and the setup of `PKG_CONFIG_PATH`. This way pkgconf could easily be bootstrapped. Doing that with `pkg-config` is a bit more complex but also possible (requires manual setting of the appropriate lib variables). After that vcpkg could add `CURRENT_HOST_INSTALLED_DIR` to `find_program` in `vcpkg_find_acquire_program` and use the internally build version of pkgconf.

**Comment by dg0yt** [comment]
The major issues at the moment are:
 - no pkgconfig support in cmake maintainer scripts
 - no pkgconfig support for user projects. (Actually no substitute at all for vcpkg_find_acquire_program.)

And the second point (or generally finding tools) is hard to fix without knowing host installation path.

**Comment by JackBoosY** [comment]
I have tried to add pkgconfig to the vcpkg toolchain but failed: the path to find the pc file is not recognized.

**Comment by dg0yt** [comment]
> I have tried to add pkgconfig to the vcpkg toolchain but failed: the path to find the pc file is not recognized.

Did you also set the search path variables, as done e.g. in `vcpkg_configure_make`? That's my point: It is solved in some build helpers, but not for cmake.

**Comment by JackBoosY** [comment]
> > I have tried to add pkgconfig to the vcpkg toolchain but failed: the path to find the pc file is not recognized.
> 
> Did you also set the search path variables, as done e.g. in `vcpkg_configure_make`? That's my point: It is solved in some build helpers, but not for cmake.

I wish to automatically use the pkgconfig installed by vcpkg and add _lib/pkgconfig_ / _debug/lib/pkgconfig_ to the search path.
There are two ways to add pc file path in cmake:
1. Set environment variables
2. Set a variable of cmake

Both them are failed.

**Comment by dg0yt** [comment]
> I wish to automatically use the pkgconfig installed by vcpkg and add _lib/pkgconfig_ / _debug/lib/pkgconfig_ to the search path.
> There are two ways to add pc file path in cmake:
> 
>     1. Set environment variables
> 
>     2. Set a variable of cmake
> 
> 
> Both them are failed.

Okay. I will try again. We will find a way to share the WIP and review.

In any case, we need to provide the host install path to cmake user projects, for the benefit of all types of host tool dependencies. I would like to hear opinions before jumping into implementations.

**Comment by JackBoosY** [comment]
@dg0yt  After that, I can make a new feature to vcpkg to automaticly print the pkgconfig usage like cmake.

**Comment by Neumann-A** [comment]
the following ports alreday use FindPkgConfig:
```
Suche "PKG_CONFIG_EXECUTABLE" (8 Treffer in 8 Dateien von 6408 gesucht)
  E:\vcpkg_folders\master\ports\cpprestsdk\portfile.cmake (1 Treffer)
	Zeile 36:         -DPKG_CONFIG_EXECUTABLE=FALSE
  E:\vcpkg_folders\master\ports\fluidsynth\portfile.cmake (1 Treffer)
	Zeile 22:         -DPKG_CONFIG_EXECUTABLE=${PKGCONFIG}
  E:\vcpkg_folders\master\ports\gmime\portfile.cmake (1 Treffer)
	Zeile 29:         -DPKG_CONFIG_EXECUTABLE=${PKGCONFIG}
  E:\vcpkg_folders\master\ports\gts\portfile.cmake (1 Treffer)
	Zeile 19:         -DPKG_CONFIG_EXECUTABLE=${PKGCONFIG}
  E:\vcpkg_folders\master\ports\libcroco\portfile.cmake (1 Treffer)
	Zeile 22:         -DPKG_CONFIG_EXECUTABLE=${PKGCONFIG}
  E:\vcpkg_folders\master\ports\libheif\gdk-pixbuf.patch (1 Treffer)
	Zeile 13: -    execute_process(COMMAND ${PKG_CONFIG_EXECUTABLE} gdk-pixbuf-2.0 --variable gdk_pixbuf_moduledir --define-variable=prefix=${CMAKE_INSTALL_PREFIX} OUTPUT_VARIABLE GDKPIXBUF2_MODULE_DIR OUTPUT_STRIP_TRAILING_WHITESPACE)
  E:\vcpkg_folders\master\ports\libnice\portfile.cmake (1 Treffer)
	Zeile 19:         -DPKG_CONFIG_EXECUTABLE=${PKGCONFIG}
  E:\vcpkg_folders\master\ports\librsvg\portfile.cmake (1 Treffer)
	Zeile 22:         -DPKG_CONFIG_EXECUTABLE=${PKGCONFIG}
```

**Comment by dg0yt** [comment]
Fun fact: The Perl installation added by vcpkg on Windows comes with a perl-only implementation of `pkg-config` and `pkg-config.bat`. So when the path of `perl.exe` is added to `ENV{PATH}`, even cmake on Windows will find pkg-config...

**Comment by JackBoosY** [comment]
Will continue review this PR untill cmake update to 3.22 or later.

**Comment by BillyONeal** [comment]
> Will continue review this PR untill cmake update to 3.22 or later.

Note that there are some good reasons to avoid updating the cmake version; going forward, that breaks Alpine: https://github.com/microsoft/vcpkg/issues/21218

**Comment by JackBoosY** [comment]
Depends on #21456.

**Comment by SamuelMarks** [comment]
[offtopic]
If we go crazy on the pkg-config side we can contribute `FindPackageName.cmake` files for most all that vcpkg proffers; back to CMake itself, which could enable successful configuration of C/C++ projects from dependencies installed on the system or via a package manager like vcpkg. E.g., use vcpkg for dev and OS for prod; or vcpkg for Windows and OS for macOS & Linux.
[/offtopic]

**Comment by JackBoosY** [comment]
pkgconfig is gradually becoming a way to use packages provided by cmake, so we should provide these methods like cmake.

**Comment by dg0yt** [comment]
> we can contribute `FindPackageName.cmake` files for most all that vcpkg proffers

Please don't. There is no benefit over using `FindPkgConfig.cmake`, but there are all downsides of Find modules.

**Comment by Neumann-A** [comment]
@JackBoosY This PR really never dependent on the cmake update to 3.22. the pkgconf PR did which is why the CMake update was an issues.

**Pull request closed without merging**
