### PR TITLE
Fixed android toolchain with newest NDK

### PR DESCRIPTION
**Pull request by christophe-calmejane**
**Describe the pull request**
ANDROID_NATIVE_API_LEVEL has been removed from NDK cmake toolchain so we now have to use ANDROID_PLATFORM

- #### What does your PR fix?  
Using latest android NDK

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
Only affects android triplets

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
Yes

### CODE REVIEW

**Comment by cenit** [comment]
why not setting both, to preserve compatibility with older ndk?

**Comment by christophe-calmejane** [comment]
I noticed some weird stuff when setting both. Some versions of the NDK do not execute the same code when both are set (checks are made in the toolchain if both variables are set or not set).
ANDROID_PLATFORM is actually here since a long time but it was not clear which variable was "the new one" when I first added it to this script.

**Comment by JackBoosY** [comment]
cc @talregev @tronical @jherico @huangqinjin @jamiebk for review this PR.

**Comment by talregev** [comment]
@AenBleidd

**Comment by dg0yt** [comment]
CC @holmescn @m-kuhn

**Comment by huangqinjin** [comment]
If I recall correctly, since NDK 19, `ANDROID_NATIVE_API_LEVEL` is same as `ANDROID_PLATFORM`, as stated in https://developer.android.com/ndk/guides/cmake#android_platform. But before that, `ANDROID_PLATFORM` only supports `android-NN` format.

Seems the latest NDK dropped `ANDROID_NATIVE_API_LEVEL` for new toolchain, but still support for legacy toolchain. Sorry to bother @DanAlbert, is that intentional?

**Comment by DanAlbert** [comment]
> If I recall correctly, since NDK 19, `ANDROID_NATIVE_API_LEVEL` is same as `ANDROID_PLATFORM`, as stated in https://developer.android.com/ndk/guides/cmake#android_platform. But before that, `ANDROID_PLATFORM` only supports `android-NN` format.
> 
> Seems the latest NDK dropped `ANDROID_NATIVE_API_LEVEL` for new toolchain, but still support for legacy toolchain. Sorry to bother @DanAlbert, is that intentional?

File an NDK bug please.

**Comment by AenBleidd** [comment]
Building with this change failed on compiler-detect at least on armv6:
```
CMake Error at /home/runner/work/boinc/boinc/3rdParty/android/android-ndk-r15c/build/cmake/android.toolchain.cmake:408 (message):
  Invalid Android platform: 16.
Call Stack (most recent call first):
  /home/runner/work/boinc/boinc/3rdParty/android/vcpkg/scripts/toolchains/android.cmake:46 (include)
  /home/runner/work/boinc/boinc/3rdParty/android/vcpkg/scripts/buildsystems/vcpkg.cmake:215 (include)
  /usr/local/share/cmake-3.21/Modules/CMakeDetermineSystem.cmake:124 (include)
  CMakeLists.txt:2 (project)
```
So in order to fix the usage of the newest NDK, a little bit more work is required here.

**Comment by huangqinjin** [comment]
Filed bug https://github.com/android/ndk/issues/1610.

**Comment by talregev** [comment]
I think `CMAKE_SYSTEM_VERSION` should change both:
`ANDROID_NATIVE_API_LEVEL` and `ANDROID_PLATFORM`
Then it will support old and new android sdk.
Can you try?

**Comment by christophe-calmejane** [comment]
> I think `CMAKE_SYSTEM_VERSION` should change both: `ANDROID_NATIVE_API_LEVEL` and `ANDROID_PLATFORM` Then it will support old and new android sdk. Can you try?

The issue with setting both is that the 2 variables are not fully compatible (in syntax), depending on the NDK version used by the caller.
I noticed some weird issues/errors when trying to set both at first.

Not sure what is the best solution here, just that for people updating to the latest NDK, vcpkg is not working anymore.

**Comment by talregev** [comment]
If both not working, then we need to separate the update according to NDK version.
old version (let say 21 and less) will update the old var: `ANDROID_NATIVE_API_LEVEL`
The new version will update the new var: `ANDROID_PLATFORM`
You can take the version of the ndk from the cmake (or the path) that user will providing you. 
Can you try?

**Comment by christophe-calmejane** [comment]
> You can take the version of the ndk from the cmake (or the path) that user will providing you.
> Can you try?

I unfortunately won't have the time to test this at the moment.
I'm not sure it will be that easy as you have to define the variables before including the NDK cmake toolchain, so it might be difficult to get a value from it before including it, to define said variable based on what has been retrieved.

Maybe someone has a better idea, but currently vcpkg is broken if you get latest NDK. Setting both variables will break vcpkg for people with an older NDK depending on what is set in their `CMAKE_SYSTEM_VERSION`

**Comment by talregev** [comment]
You don't have to include the cmake to find version number. maybe simple parse from one of the txt/cmake file for ndk version.

**Comment by talregev** [comment]
I look on the `android.toolchain.cmake` inside the ndk 15. we actually can use `ANDROID_PLATFORM`
we need to set it to 'android-16` and not just 16.
@AenBleidd Can you try and let us know?

**Comment by AenBleidd** [comment]
@talregev, not sure I got your idea.

**Comment by talregev** [comment]
@AenBleidd I am writing you in discord.

**Comment by talregev** [comment]
ok. I understand the confusion. 
the `ANDROID_PLATFORM` also work in old ndks but in needed to add the prefix `android-` before the platform number that it will work.
For backward compatibility and not confuse others, I am suggesting another change:   
to check if `CMAKE_SYSTEM_VERSION` it just a number, and if yes, add it `android-` prefix to the number.
```cmake
if(CMAKE_SYSTEM_VERSION MATCHES "[0-9]+$")
    set(ANDROID_PLATFORM android-${CMAKE_SYSTEM_VERSION} CACHE STRING "")
else()
    set(ANDROID_PLATFORM ${CMAKE_SYSTEM_VERSION} CACHE STRING "")
endif()
```

**Comment by talregev** [comment]
We change our triplets to 
set(VCPKG_CMAKE_SYSTEM_VERSION android-x) and it working. (also working before and after your change).

**Comment by JackBoosY** [comment]
So everyone approved this changes?

**Comment by holmescn** [comment]
I think before we can refactor the entire build process, any patches would temporarily work. Although Android NDK is not evolved so fast, version fragmentation is serious. Issue #21345 tried to discuss and resolve this problem from scratch. But any effort is welcome.

**Comment by AenBleidd** [comment]
@JackBoosY, I'm ok with these changes.

**Review by JackBoosY — APPROVED** [review]

**Comment by talregev** [comment]
@JackBoosY Please consider my suggestion before merge.

**Comment by talregev** [comment]
> ok. I understand the confusion. the `ANDROID_PLATFORM` also work in old ndks but in needed to add the prefix `android-` before the platform number that it will work. For backward compatibility and not confuse others, I am suggesting another change: to check if `CMAKE_SYSTEM_VERSION` it just a number, and if yes, add it `android-` prefix to the number.
> 
> ```cmake
> if(CMAKE_SYSTEM_VERSION MATCHES "[0-9]+$")
>     set(ANDROID_PLATFORM android-${CMAKE_SYSTEM_VERSION} CACHE STRING "")
> else()
>     set(ANDROID_PLATFORM ${CMAKE_SYSTEM_VERSION} CACHE STRING "")
> endif()
> ```

@christophe-calmejane Can you try my suggestion? 
https://github.com/microsoft/vcpkg/pull/21465#issuecomment-975966155

**Comment by christophe-calmejane** [comment]
I quickly checked and it fails if you set CMAKE_SYSTEM_VERSION to android-15 for exemple

**Comment by talregev** [comment]
There is no android-15. the number is no ndk. we  using android-16.

**Comment by talregev** [comment]
https://developer.android.com/ndk/downloads/revision_history

from ndk 18 google drop the support for android 15

> Android NDK r18b
> Support for ICS (android-14 and android-15) has been removed. Apps using executables no longer need to provide both a PIE and non-PIE executable.

**Comment by christophe-calmejane** [comment]
Sorry I just used any random number when replying, use any number you want, it fails with your change if you set android-NN

**Comment by talregev** [comment]
> use any number you want, it fails with your change if you set android

Can you tell me what ndk are you using, and past here the error?

**Comment by JackBoosY** [comment]
Since I have less knowledge with Android, I will follow the opinions of most people.

**Comment by christophe-calmejane** [comment]
> > use any number you want, it fails with your change if you set android
> 
> Can you tell me the ndk version are you using, and past here the error?

Your code causes `android-19` to be transformed to `android-android-19` which is bad.
It might just be as simple as to add strict matching `"^[0-9]+$"` but I don't have time this week to test more

**Comment by talregev** [comment]
> 

Thank you that you find error in my regular expression. I meant if the var contain only digits. can you fix  it?

**Comment by talregev** [comment]
> ```cmake
> if(CMAKE_SYSTEM_VERSION MATCHES "[0-9]+$")
>     set(ANDROID_PLATFORM android-${CMAKE_SYSTEM_VERSION} CACHE STRING "")
> else()
>     set(ANDROID_PLATFORM ${CMAKE_SYSTEM_VERSION} CACHE STRING "")
> endif()
> ```

@christophe-calmejane

I understand the my error
Also read here:
https://cmake.org/cmake/help/latest/command/string.html#regex-specification

Can you test it with the fix?

```cmake
if(CMAKE_SYSTEM_VERSION MATCHES "^[0-9]+$")
    set(ANDROID_PLATFORM android-${CMAKE_SYSTEM_VERSION} CACHE STRING "")
else()
    set(ANDROID_PLATFORM ${CMAKE_SYSTEM_VERSION} CACHE STRING "")
endif()
```

**Comment by christophe-calmejane** [comment]
Sorry for the long delay, I'm gonna test some changes as soon as I find a bit of time, hopefully before the end of the week.

**Comment by christophe-calmejane** [comment]
I pushed a new commit, including your proposal. Seems fine on my side.

**Comment by JackBoosY** [comment]
@talregev What's your opinion now?

**Comment by talregev** [comment]
I am happy with the changes. It also support back compatibility. 
@christophe-calmejane Thank you for your changes and fix.
@JackBoosY Can you merge it please?

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
Maybe we should also update our docs.

**Comment by BillyONeal** [comment]
> Maybe we should also update our docs.

I don't see anywhere any of these variables are mentioned in our docs for Android.

**Comment by BillyONeal** [comment]
Thanks for the bugfix!

**Pull request merged**
