### PR TITLE
[hdf5] Update to 1.8.23 (add old version possible ?)

### PR DESCRIPTION
**Pull request by bansan85**
- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [X] SHA512s are updated for each updated download.
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version.~~
- [X] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [X] Any patches that are no longer applied are deleted from the port's directory.
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

This PR is for an old (but still maintained) version : 1.8.23.

The problem is now, the default version will be 1.8.23 instead of the latest version 1.14.2.

How can I fix that ? All tutorial I found explain how to add a new version but not an old version.

### CODE REVIEW

**Comment by Neumann-A** [comment]
vcpkg does not backfill old versions. If you want to use that version consider using an overlay

**Comment by bansan85** [comment]
Thanks, I didn't know about overlay port.

I spend about one hour to do this port version. I just didn't wanted to be selfish.

I let the team close this PR if it really can't be merge.

**Comment by bansan85** [comment]
hdf5 looks good.

The CI fails because other packages that depend on hdf5 doesn't support this old version of hdf5.

**Comment by jimwang118** [comment]
You can refer to this [website](https://learn.microsoft.com/en-us/vcpkg/concepts/overlay-ports) to learn how to implement Overlay ports.
If you want to update the port version to the latest version, you need to modify the version to the latest released version.

**Pull request closed without merging**
