### PR TITLE
[mongo-cxx-driver] update to 3.10.1

### LINKED ISSUE #36972: [mongo-cxx-driver] update to 3.10.0
### Library name

mongo-cxx-driver

### New version number

3.10.0

### Other information that may be useful (release notes, etc...)

Release notes are available here: https://github.com/mongodb/mongo-cxx-driver/releases/tag/r3.10.0

### PR DESCRIPTION
**Pull request by Cheney-W**
Fixes https://github.com/microsoft/vcpkg/issues/36972

All features passed with following triplets:
```
x86-windows 
x64-windows 
x64-windows-static 
```
Usage passed with `x64-windows` triplet.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version.~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Review by LilyWangLL — DISMISSED** [review]

**Comment by eramongodb** [comment]
> Package libbsoncxx-v_noabi-rhs- was not found in the pkg-config search path.

The trailing `-` concerns me. What is the value of `MSVC_RUNTIME_LIBRARY` following [this line in BsoncxxUtil.cmake](https://github.com/mongodb/mongo-cxx-driver/blob/2c8eb429508c19ebc2b76b1e5989ee4e3c5d94b7/cmake/BsoncxxUtil.cmake#L94)?

```cmake
get_target_property(runtime ${TARGET} MSVC_RUNTIME_LIBRARY)

message(WARNING "Unexpected MSVC_RUNTIME_LIBRARY value: ${MSVC_RUNTIME_LIBRARY}") # <--
```

Per [CMake documentation](https://cmake.org/cmake/help/latest/prop_tgt/MSVC_RUNTIME_LIBRARY.html), it should only be one of the four supported values, which are all handled accordingly. This trailing `-` seems to imply there is an unexpected value that falls through the `if()/elseif()` conditions, leading to an empty `${runtime_str}` being appended to the suffix.

**Comment by Cheney-W** [comment]
> What is the value of `MSVC_RUNTIME_LIBRARY` following [this line in BsoncxxUtil.cmake](https://github.com/mongodb/mongo-cxx-driver/blob/2c8eb429508c19ebc2b76b1e5989ee4e3c5d94b7/cmake/BsoncxxUtil.cmake#L94)?

During debugging, I found that after executing the statement `get_target_property(runtime ${TARGET} MSVC_RUNTIME_LIBRARY)`, the corresponding variable values are as follows:
```
runtime: MultiThreaded$<$<CONFIG:Debug>:Debug>$<$<STREQUAL:dynamic,dynamic>:DLL>
TARGET: bsoncxx_shared
MSVC_RUNTIME_LIBRARY: 
```
This causes the `if(runtime)` condition to be entered, but its subsequent subconditions are not entered, ultimately resulting in the `runtime_str` value being empty.

**Comment by eramongodb** [comment]
The trailing `-` issue should be resolved by https://github.com/mongodb/mongo-cxx-driver/pull/1106.

**Comment by Cheney-W** [comment]
@eramongodb Do you have any plans to release a new tag for `mongo-cxx-driver` recently?

**Comment by eramongodb** [comment]
@Cheney-W We are planning a 3.10.1 release this Tuesday (tomorrow) which will contain the fixes mentioned above. Tracked by [CXX-2972](https://jira.mongodb.org/browse/CXX-2972).

**Review by LilyWangLL — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks!

**Pull request merged**
