### PR TITLE
[freetype] Update to 2.13.1

### PR DESCRIPTION
**Pull request by sakiodre**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [ ] <s>The "supports" clause reflects platforms that may be fixed by this new version</s>
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by Osyotr** [comment]
You probably also need to apply suggestions from this comment: https://github.com/microsoft/vcpkg/pull/31382#discussion_r1193414743

**Comment by JonLiu1993** [comment]
@sakiodre, Thanks for your PR, this is ci error, please take a look:
````
CMake Error at D:/installed/x86-windows/share/freetype/freetype-targets.cmake:42 (message):
  Some (but not all) targets in this export set were already defined.

  Targets Defined: Freetype::Freetype

  Targets not yet defined: freetype

````

**Comment by JonLiu1993** [comment]
Ping @sakiodre for response.

**Comment by sakiodre** [comment]
Sorry, I don't have enough technical knowledge to solve the issue, closing.

**Pull request closed without merging**
