### PR TITLE
[icu] remove setting triplet

### LINKED ISSUE #18086: [icu:x64-windows-static] build failure
**Host Environment**
- OS: Windows 10 21H1
- Compiler: VS 16.9.6

**To Reproduce**
`./vcpkg install icu:x64-windows-static`

**Failure logs** 

```
Computing installation plan...
The following packages will be built and installed:
    icu[core]:x64-windows-static -> 69.1#9
Detecting compiler hash for triplet x64-windows-static...
Could not locate cached archive: C:\Users\Johnathan\AppData\Local\vcpkg\archives\d2\d2df960a9062beb50351d4f0c146928050f82dfe.zip
Starting package 1/1: icu:x64-windows-static
Building package icu[core]:x64-windows-static...
-- Using cached C:/dev/vcpkg/downloads/icu4c-69_1-src.tgz
-- Cleaning sources at C:/dev/vcpkg/buildtrees/icu/src/c-69_1-src-78c1b28057.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/dev/vcpkg/downloads/icu4c-69_1-src.tgz
-- Applying patch C:/dev/vcpkg/ports/icu/disable-escapestr-tool.patch
-- Applying patch C:/dev/vcpkg/ports/icu/remove-MD-from-configure.patch
-- Applying patch C:/dev/vcpkg/ports/icu/fix_parallel_build_on_windows.patch
-- Applying patch C:/dev/vcpkg/ports/icu/fix-extra.patch
-- Using source at C:/dev/vcpkg/buildtrees/icu/src/c-69_1-src-78c1b28057.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows-static
-- Using msys root at C:/dev/vcpkg/downloads/tools/msys2/d589ebc2087b2b2c
-- Using msys root at C:/dev/vcpkg/downloads/tools/msys2/50864d9fae363d6e
-- Configuring x64-windows-static-dbg
-- Configuring x64-windows-static-rel
-- Using msys root at C:/dev/vcpkg/downloads/tools/msys2/969c0913b9df89e1
-- Building x64-windows-static-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: C:/dev/vcpkg/downloads/tools/msys2/d589ebc2087b2b2c/usr/bin/make.exe -j 9 --trace -f Makefile all
    Working Directory: C:/dev/vcpkg/buildtrees/icu/x64-windows-static-dbg
    See logs for more information:
      C:\dev\vcpkg\buildtrees\icu\build-x64-windows-static-dbg-out.log
      C:\dev\vcpkg\buildtrees\icu\build-x64-windows-static-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:194 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:26 (vcpkg_build_make)
  ports/icu/portfile.cmake:136 (vcpkg_install_make)
  scripts/ports.cmake:141 (include)


Error: Building package icu:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: icu:x64-windows-static
  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9
```

### PR DESCRIPTION
**Pull request by autoantwort**
Remove unnecessary settings (maybe fix #18086 ?)

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
The paraview regression will be fixed by another PR.

**Comment by JackBoosY** [comment]
Depends on https://github.com/microsoft/vcpkg/pull/19629.

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
