### PR TITLE
[git add] recurse-submodules

### PR DESCRIPTION
**Pull request by MVoz**

### CODE REVIEW

**Comment by linquize** [comment]
You should add one argument like `RECURSE_SUBMODULES` to enable `--recurse-submodules` so that the port author can choose to / not to checkout submodules.

**Comment by Voskrese** [comment]
@linquize 

example port or doc?

**Comment by linquize** [comment]
Usage:
```cmake
vcpkg_from_git(
     OUT_SOURCE_PATH src
     URL https://example.com/repo.git
     REF 59f7335e4d
     RECURSE_SUBMODULES
     PATCHES patch1.patch patch2.patch
)
```

**Comment by Voskrese** [comment]
I do not understand fluent English, from the word completely )))
I apologize, you propose to implement it or it is realized, i don 't see anywhere in the code

https://github.com/microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_from_github.cmake

in general, your idea is certainly better when there is a choice, and not strictly prescribed
I think those who are better versed in the script code will help us )))

**Comment by Neumann-A** [comment]
Maybe make the following change to the original code:

```
  set(multipleValuesArgs PATCHES OPTIONS)
```

```
    vcpkg_execute_required_process(
      ALLOW_IN_DOWNLOAD_MODE
      COMMAND ${GIT} fetch ${_vdud_URL} ${_vdud_REF} ${_vdud_OPTIONS} --depth 1 -n
      WORKING_DIRECTORY ${DOWNLOADS}/git-tmp
      LOGNAME git-fetch-${TARGET_TRIPLET}
    )
```

**Comment by linquize** [comment]
Could you squash into a single commit?

**Comment by heydojo** [comment]
Crazy that this wasn't merged.
This feature is still completely missing from vcpkg, making some projects (such as Audacity's custom fork of wxwidgets) impossible to build as they rely heavily on sub modules.
But the comments in vcpkg_from_git.cmake have been reformatted, so that's nice. 🤷

**Pull request closed without merging**
