### PR TITLE
[Documentation] Added documentation page for vcpkg_fixup_cmake_targets.cmake

### PR DESCRIPTION
**Pull request by vpaladino778**
Added example usage comment to .cmake file. I found it somewhat confusing with the way the comment was formatted, so i changed it for clarity. Also added a basic documentation page for `vcpkg_fixup_cmake_targets.cmake`

### CODE REVIEW

**Review by vicroms — APPROVED** [review]
LGTM

**Comment by vpaladino778** [comment]
I'm trying to figure out why @cbezault's commits caused the build to fail, because my original commit passed the tests. The weird thing is that all he changes was some comments.

**Comment by vpaladino778** [comment]
Here was the errors from the failed checks:

```bash
##[error] REGRESSION: librabbitmq:x64-linux
##[error] REGRESSION: geographiclib:x64-linux
##[error] REGRESSION: otl:x64-linux
```

After checking out the master branch, and attempting to compile `geographiclib` and `otl`, I recieved errors. So this problem may not be with these commits, but a problem with the master branch.

**Comment by cbezault** [comment]
I'm pretty sure otl's hash changed on us, which is why it's failing :/

**Pull request merged**
