### PR TITLE
[boost] Add version constraints

### PR DESCRIPTION
**Pull request by Osyotr**
Fix https://github.com/microsoft/vcpkg/discussions/26582 (aka https://github.com/microsoft/vcpkg/issues/26548) by adding version constraints to boost ports.

Cc @horenmar

### CODE REVIEW

**Comment by Osyotr** [comment]
Huh? With this manifest:
```
{
  "name": "super-duper-boost-test",
  "builtin-baseline":"96ec7fb25da25e0463446e552d59715a47c95e73",
  "dependencies": [
    {
      "name": "boost-modular-build-helper",
      "version>=": "1.80.0#2"
    }
  ]
}
```

```
vcpkg install --dry-run
Error: Cannot resolve a minimum constraint for dependency vcpkg-cmake-get-vars from boost-modular-build-helper:x86-windows.
The dependency was not found in the baseline, indicating that the package did not exist at that time. This may be fixed by providing an explicit override version via the "overrides" field or by updating the baseline.
See `vcpkg help versioning` for more information.
```

**Comment by Osyotr** [comment]
Oh, `vcpkg-cmake-get-vars` has been introduced after baseline `96ec7fb25da25e0463446e552d59715a47c95e73` so it's not found. Should a port look for its baseline if its dependency was not found? @BillyONeal

**Comment by BillyONeal** [comment]
> Oh, `vcpkg-cmake-get-vars` has been introduced after baseline `96ec7fb25da25e0463446e552d59715a47c95e73` so it's not found. Should a port look for its baseline if its dependency was not found? @BillyONeal

In the current design, the user asked us to use the port as it is in `96ec7fb25da25e0463446e552d59715a47c95e73`. If it does not exist there then they asked to use something that doesn't exist. However, I agree this can be somewhat unfortunate in this cease. I don't have great answers though; there's not an obviously correct version to use here. (We don't have a way to go from a port version to a baseline, only the other way around)

**Comment by horenmar** [comment]
If I understand the behaviour correctly, if the `boost-modular-build-helper` port asked for a specific version of `vcpkg-cmake-get-vars`, then it would be able to resolve it, but currently it asks for whatever version is in the baseline, and, well, there is none.

This is basically why I said in the original issue that basically all ports with dependencies are affected. vcpkg relies on baseline to resolve versions of transitive dependencies, and at the same time the behaviour of baseline constraints is such that e.g. my place wants to keep old baselines for as long as we can.

**Comment by Osyotr** [comment]
Maybe add `requires:vcpkg-team-review`?

**Comment by Danielmelody** [comment]
This PR is a rescue for our team, we need a easy and clean way to use partial of newer boost library while keeping the baseline pinned to a old version. Other wise we have to manually write constraints for hundreds of boost libraries.

**Comment by JackBoosY** [comment]
Please resolve the file conflicts.

Thanks.

**Comment by Osyotr** [comment]
I've also added a note to generated files:
`"$comment": "When changing this file also update and run scripts/boost/generate-ports.ps1",`
https://github.com/microsoft/vcpkg/pull/26918#discussion_r977308883

**Pull request merged**
