### PR TITLE
[Qt6] Update to 6.4.1

### PR DESCRIPTION
**Pull request by Neumann-A**
depends on #26693
(CI Testrun to work out problems tomorrow)
(will fix version db if Qt 6.4 is merged; otherwise it makes little sense to add new versions)

### CODE REVIEW

**Comment by Sharpe49** [comment]
Why is AVFoundation disabled in the qtmultimedia port file ? It is an Apple Framework, so it will never be on VCPKG, I think.
https://developer.apple.com/documentation/avfoundation

**Comment by Neumann-A** [comment]
> Why is AVFoundation disabled in the qtmultimedia port file ?

Because it is controlling a bunch of features:
https://github.com/qt/qtmultimedia/blob/21a75150e38167fcadc8ad679cd75174356da8e5/src/multimedia/configure.cmake#L83
Feel free to activate it if it is safe.

**Comment by Sharpe49** [comment]
> > Why is AVFoundation disabled in the qtmultimedia port file ?
> 
> Because it is controlling a bunch of features: https://github.com/qt/qtmultimedia/blob/21a75150e38167fcadc8ad679cd75174356da8e5/src/multimedia/configure.cmake#L83 Feel free to activate it if it is safe.

Well, I am currently getting build issues on macOS (on the gstreamer update branch) because it is disabled.
`CMake Error at /Users/vagrant/Data/installed/x64-osx/share/Qt6/QtTargetHelpers.cmake:80 (target_link_libraries):
  Target "QDarwinMediaPlugin" links to:

    AVFoundation::AVFoundation

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  /Users/vagrant/Data/installed/x64-osx/share/Qt6/QtPluginHelpers.cmake:312 (qt_internal_extend_target)
  src/plugins/multimedia/darwin/CMakeLists.txt:8 (qt_internal_add_plugin)`

**Review by Adela0814 — APPROVED** [review]

**Comment by JavierMatosD** [comment]
Thank you!

**Pull request merged**
