### PR TITLE
[c-dbg-macro] Add new port

### PR DESCRIPTION
**Pull request by eerimoq**
**Describe the pull request**

- #### What does your PR fix?  
  Add new port

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all, Yes (I think)

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Probably not. A lot to read.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

### CODE REVIEW

**Review by JonLiu1993 — APPROVED** [review]

**Comment by autoantwort** [comment]
This breaks the ci:
```
Starting package 408/935: dbg-macro:x64-uwp
Building package dbg-macro[core]:x64-uwp...
-- Downloading https://github.com/sharkdp/dbg-macro/archive/4db61805d90cb66d91bcc56c2703591a0127ed11.tar.gz -> sharkdp-dbg-macro-4db61805d90cb66d91bcc56c2703591a0127ed11.tar.gz...
-- Extracting source D:/downloads/sharkdp-dbg-macro-4db61805d90cb66d91bcc56c2703591a0127ed11.tar.gz
-- Using source at D:/buildtrees/dbg-macro/src/1a0127ed11-833f10929f.clean
-- Performing post-build validation
-- Performing post-build validation done
Uploaded binaries to 1 HTTP remotes.
Installing package dbg-macro[core]:x64-uwp...
The following files are already installed in D:/installed/x64-uwp and are in conflict with dbg-macro:x64-uwp

Installed by c-dbg-macro:x64-uwp
    include/dbg.h

Elapsed time for package dbg-macro:x64-uwp: 447.8 ms

```

**Comment by JonLiu1993** [comment]
@autoantwort , I install c-dbg-macro:x64-uwp by command "./vcpkg install c-dbg-macro:x64-uwp" and install successfully:
````
PS F:\test\vcpkg> ./vcpkg install c-dbg-macro:x64-uwp
Computing installation plan...
The following packages will be built and installed:
    c-dbg-macro[core]:x64-uwp -> 2020-02-29
Detecting compiler hash for triplet x64-uwp...
Restored 0 packages from C:\Users\vzhli17\AppData\Local\vcpkg\archives in 261.3 us. Use --debug to see more details.
Starting package 1/1: c-dbg-macro:x64-uwp
Building package c-dbg-macro[core]:x64-uwp...
-- Downloading https://github.com/eerimoq/dbg-macro/archive/78b7655bd0cfc2389fe96a3b6584d2930eb7ebd7.tar.gz -> eerimoq-dbg-macro-78b7655bd0cfc2389fe96a3b6584d2930eb7ebd7.tar.gz...
-- Extracting source F:/test/vcpkg/downloads/eerimoq-dbg-macro-78b7655bd0cfc2389fe96a3b6584d2930eb7ebd7.tar.gz
-- Using source at F:/test/vcpkg/buildtrees/c-dbg-macro/src/930eb7ebd7-10be9aa7b4.clean
-- Performing post-build validation
-- Performing post-build validation done
A suitable version of 7zip was not found (required v21.7.0). Downloading portable 7zip v21.7.0...
Downloading 7zip...
  https://www.7-zip.org/a/7z2107-extra.7z -> F:\test\vcpkg\downloads\7z2107-extra.7z
Extracting 7zip...
Stored binary cache: C:\Users\vzhli17\AppData\Local\vcpkg\archives\c1\c150d8becedd4f05662e5437657008ba0cee6eb9ce2a129f9745619e91c6e6b9.zip
Installing package c-dbg-macro[core]:x64-uwp...
Elapsed time for package c-dbg-macro:x64-uwp: 2.621 s

Total elapsed time: 21.41 s

The package c-dbg-macro is header only and can be used from CMake via:

    find_path(C_DBG_MACRO_INCLUDE_DIRS "dbg.h")
    target_include_directories(main PRIVATE ${C_DBG_MACRO_INCLUDE_DIRS})

PS F:\test\vcpkg>
````

**Comment by dg0yt** [comment]
@JonLiu1993 The conflict is when installing the second port from the set `< dbg-macro, c-dbg-macro >`.

**Comment by eerimoq** [comment]
Not sure what to do about it. Renaming the header file when installing using vcpkg is possible, but could be confusing. However, the package in vcpkg is called c-dbg-macro, so a c as prefix might be ok?

**Comment by dg0yt** [comment]
A file name as general as `include/dbg.h` is not well suited for a general library manager as vcpkg. 
There is a simple solution: Use a subdirectory, e.g. `include/eerimoq/dbg-macro.h`.
And replace this port with a new one named `eerimoq/dbg-macro`.

I need to repeat that there should be more care before adding ports. It can't be merge 2 days after the PR, even if trivial.

**Comment by autoantwort** [comment]
Or use `include/<port-name>/..`, thus `include/c-dbg-macro/dbg.h`

**Pull request merged**
