### PR TITLE
[z3] Update to 4.8.15

### PR DESCRIPTION
**Pull request by ekilmer**
**Describe the pull request**

- #### What does your PR fix?
  N/A

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

### CODE REVIEW

**Comment by FrankXie05** [comment]
@ekilmer The port `z3`  has bugs for `vcpkg_cmake_configure`, you can restore this function back to solve the CI error.
Reference: https://github.com/microsoft/vcpkg/pull/22687#issuecomment-1020033216

**Comment by dg0yt** [comment]
> @ekilmer The port `z3` has bugs for `vcpkg_cmake_configure`, you can restore this function back to solve the CI error. Reference: [#22687 (comment)](https://github.com/microsoft/vcpkg/pull/22687#issuecomment-1020033216)

~~~
CMake Error at D:/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/share/cmake-3.22/Modules/ExternalProject.cmake:1754 (file):
  file attempted to create a directory:
  D:/buildtrees/z3/src/z3-4.8.15-a1f0ec7b90.clean/examples/c into a source
  directory.
Call Stack (most recent call first):
  D:/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/share/cmake-3.22/Modules/ExternalProject.cmake:3668 (_ep_set_directories)
  examples/CMakeLists.txt:37 (ExternalProject_Add)
~~~
IMO the build is doing this which it shouldn't do, and `vcpkg_cmake_configure` is pointing this out correctly.

**Comment by ekilmer** [comment]
@FrankXie05 Ready for review!

**Review by FrankXie05 — APPROVED** [review]

**Comment by strega-nil-ms** [comment]
Thanks!

**Pull request merged**
