### PR TITLE
fix issue #9228 : Add support to subgroups in gitlab

### LINKED ISSUE #9228: Bug in vcpkg_from_gitlab
****

**Is your feature request related to a problem? Please describe.**
vcpkg_from_gitlab doesn't take into account subgroups after organizations name 
for example: organization/cpp/project
**Proposed solution**
I didn't dig into vcpkg_from_gitlab but I think it could be added easily

### PR DESCRIPTION
**Pull request by RamadanAhmed**
Fixes #9228.

### CODE REVIEW

**Comment by RamadanAhmed** [comment]
@dan-shaw @PhoebeHui  does reviewing need the CI to work ?

**Comment by dan-shaw** [comment]
Thanks for the PR! We aren't quite sure what this PR does. Can you clarify what usecases this change could have?

**Comment by RamadanAhmed** [comment]
old vcpkg_from_gitlab didn't support subgroups within organization, so if your organization/group have different subgroups inside it vcpkg can't download any code from subgroup(organization/subgroup/repo) so I split the name given in the repo name *seperator= '/'* and according to size we use fixed link for subgroup or the normal way vcpkg done before

**Comment by RamadanAhmed** [comment]
Any Updates on the issue

**Comment by PhoebeHui** [comment]
The CI test pass, @dan-shaw, could you help futher review?

**Review by ras0219-msft — APPROVED** [review]

**Pull request merged**
