### PR TITLE
#9306 Feature/add port version variable

### PR DESCRIPTION
**Pull request by CJCombrink**
**Describe the pull request**

- What does your PR fix? Fixes issue #9306

- Which triplets are supported/not supported? Have you updated the CI baseline?
This does not affect triplets but vcpkg

- Does your PR follow the [maintainer guide]
I think so yes

### CODE REVIEW

**Comment by CJCombrink** [comment]
Maybe I should remove the Documentation commit from this PR, it adds a lot of noise.

**Comment by JackBoosY** [comment]
It's very useful,  but we prefer to use commit id as the REF instead of version number. 
So I think this function is limited.

**Comment by JackBoosY** [comment]
Please resolve conflicts.

Thanks,

**Comment by JackBoosY** [comment]
Closing this PR since it seems that no progress is being made. Please reopen if work is still being done.

**Pull request closed without merging**
