### PR TITLE
WIP: [x64-windows-intel] new Triplet:

### PR DESCRIPTION
**Pull request by Neumann-A**
Requirements:
Intel C/C++/Fortran compiler via oneAPI
~~manuall copy of llvm-ar and subsequent rename to llvm-ranlib.~~
~~cmake platform seems to be `Windows-Clang`~~

~~opened:~~
~~https://gitlab.kitware.com/cmake/cmake/-/issues/21588~~

- [x] waiting for cmake to actually support those compilers.

### CODE REVIEW

**Comment by JackBoosY** [comment]
Any progress?

**Comment by JackBoosY** [comment]
Please temporary close this PR if you don't have spare time to finish it.

**Comment by Neumann-A** [comment]
> Please temporary close this PR if you don't have spare time to finish it.

Mainly waiting for other PRs to be merge first and if I should hijack one of the normal triplets for testing ;)

**Comment by LilyWangLL** [comment]
Ping @Neumann-A for response. Is work still being done for this PR?

**Comment by Neumann-A** [comment]
> Ping @Neumann-A for response. Is work still being done for this PR?

waiting for other complicated stuff to getting merged.

**Comment by LilyWangLL** [comment]
> > Ping @Neumann-A for response. Is work still being done for this PR?
> 
> waiting for other complicated stuff to getting merged.

Please link other PR to here, this will make it easier for us to track this PR.

**Comment by Neumann-A** [comment]
#26617
#26370 
#26337
#24327

**Comment by BillyONeal** [comment]
Closing this PR as there has not been activity in over 4 months. Please feel free to reopen it, or another PR, should you wish to continue this.

Note that we were recently forced to no longer install icc in the test lab, though that doesn't necessarily matter for this given that we wouldn't have made icc an official triplet anytime soon.

**Pull request closed without merging**
