### PR TITLE
[expat] fix build on x64-windows

### PR DESCRIPTION
**Pull request by AlessandroScrem**
"Fixes [[expat] Build error on x64-windows #35878]
Fix also [icu] Build error #22976 depend on this port

### CODE REVIEW

**Comment by AlessandroScrem** [comment]
@microsoft-github-policy-service agree [company="default"]
@microsoft-github-policy-service agree
@microsoft-github-policy-service agree company="Microsoft"

**Comment by AlessandroScrem** [comment]
@microsoft-github-policy-service agree
@microsoft-github-policy-service agree company="your company"

**Comment by AlessandroScrem** [comment]
> "Fixes Also [icu] Build error #22976 depend on expat

**Comment by dg0yt** [comment]
> "Fixes [[expat] Build error on x64-windows #35878] 

I don't think so. The issue reports an error at determining the compiler. This is far away from see this macro.

> Fix also [icu] Build error #22976 depend on this port

I don't think so. Port icu doesn't depend on port pcre. And that issue doesn't point to expat.

**Comment by BillyONeal** [comment]
I agree with @dg0yt , this doesn't seem like it'll fix anything about that. Has this change been submitted upstream?

Feel free to mark 'ready for review' if upstream has had 30 days to consider the change with an explanation as to how it actually achieves fixing the indicated issues.

**Comment by BillyONeal** [comment]
Closing this in favor of https://github.com/microsoft/vcpkg/pull/39505 ; if upstream accepts your changes please feel to reopen with a pointer to where they accepted it.

**Pull request closed without merging**
