### PR TITLE
[vcpkg] Fix compile on gcc 6

### PR DESCRIPTION
**Pull request by strega-nil**
~~Depends on #13038~~

Tested with g++ 6.5.0 on Ubuntu 18.04.

### CODE REVIEW

**Comment by BillyONeal** [comment]
Stupid question: Can you name these constants outside of the files you declared them in here?

And should these constants even be in headers at all?

**Comment by strega-nil** [comment]
@BillyONeal yes, and yes.

**Review by BillyONeal — APPROVED** [review]

**Comment by BillyONeal** [comment]
:sigh: I still hate named-constants-with-content-identical-to-the-named-constant but this doesn't change that.

**Pull request merged**
