### PR TITLE
[harfbuzz] Add feature gdi

### LINKED ISSUE #38880: [harfbuzz] <Add GDI & Uniscribe build option>
### Is your feature request related to a problem? Please describe.

The port for HarfBuzz has the feature option for `directwrite`, but not for Uniscribe & GDI font support.

### Proposed solution

- Add a 'gdi' option for Windows to the vcpkg.json file.
- Add to portfile.cmake to detect feature 'gdi' and apply the FEATURE_OPTIONS `-Dgdi=enabled`

e.g. vcpkg.json (line 55 before the glib option):
```
    "gdi": {
      "description": "Enable GDI/Uniscribe support on Windows",
      "supports": "windows"
    },
```

e.g. portfile.cmake (line 11)
```
if("gdi" IN_LIST FEATURES)
    list(APPEND FEATURE_OPTIONS -Dgdi=enabled) # Enable GDI/Uniscribe support on Windows
endif()
```

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jimwang118**
Fixes https://github.com/microsoft/vcpkg/issues/38880

- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [ ] ~~SHA512s are updated for each updated download.~~
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version.~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

The feature gdi passed with following triplet:

```
x64-windows
```

### CODE REVIEW

**Comment by MattMatic** [comment]
Thanks for addressing this port…
Has progress stalled? Can I try and help?
Thanks.
Matt

**Comment by jimwang118** [comment]
> Thanks for addressing this port… Has progress stalled? Can I try and help? Thanks. Matt
> 
> cc: @jimwang118

Thank you very much, after installing gdi feature, I tried to install kf5kio and got an error. I don't know how to fix it, please help me fix this error.
You can check the CI Linux platform and download the detailed error log.

**Comment by dg0yt** [comment]
The new feature is windows-only. It cannot break linux. So the error must have been a baseline regression.
And I fixed it in https://github.com/microsoft/vcpkg/pull/38965.

**Comment by MattMatic** [comment]
Agreed - the GDI feature of HarfBuzz is Windows only and cannot affect Linux.

I presume that bringing this commit up to date with master should correct the regression error (as mentioned by dg0yt) and pass the tests.

**Comment by jimwang118** [comment]
> Agreed - the GDI feature of HarfBuzz is Windows only and cannot affect Linux.
> 
> I presume that bringing this commit up to date with master should correct the regression error (as mentioned by dg0yt) and pass the tests.

OK, I will merge the master code, and then merge this PR after waiting for CI to pass.

**Comment by MattMatic** [comment]
Glad the tests passed :-) All good to merge this PR?

**Review by LilyWangLL — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks!

**Pull request merged**
