### PR TITLE
windows: set CMAKE_MSVC_RUNTIME_LIBRARY for cmake policy CMP0091

### PR DESCRIPTION
**Pull request by marcrambo**
Starting with Cmake 3.15 policy CMP0091 was introduced: https://cmake.org/cmake/help/v3.16/policy/CMP0091.html. Currently vcpkg windows toolchain does not properly set the CMAKE_MSVC_RUNTIME_LIBRARY variable leading to linker errors.

- What does your PR fix? 
Projects using this new policy currently fail to build with vcpkg for non default VCPKG_LIBRARY_LINKAGE/ VCPKG_CRT_LINKAGE combinations. Specifically the following project uses the new policy and currently fails: https://github.com/NativeInstruments/ni-media with the following error:
```
error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug'
```

- Which triplets are supported/not supported? Have you updated the CI baseline?
All combinations of VCPKG_LIBRARY_LINKAGE / VCPKG_CRT_LINKAGE on windows are supported. Other platforms are not affected.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

### CODE REVIEW

**Comment by Neumann-A** [comment]
The problem with this PR is that it requires cmake_minimum_required of 3.15 or setting the policy manually. A lot of ports use a version much lower than that and will simply ignore the additional variable....
Furthermore current CMake version in vcpkg is 3.14 if I am not incorrect. So you probably want to detect if the policy exists and then set the variable.

**Comment by marcrambo** [comment]
> The problem with this PR is that it requires cmake_minimum_required of 3.15 or setting the policy manually. A lot of ports use a version much lower than that and will simply ignore the additional variable....

This is actually not a problem but the intended behavior. CMake will only make use of this variable when CMP0091 is set (default for cmake>= 3.15), and ignore it otherwise. New ports using this policy or existing ports bumping their cmake_minimum_required_version are currently facing the linker errors this PR fixes.

> Furthermore current CMake version in vcpkg is 3.14 if I am not incorrect.

I think it is even lower 3.12.4, however vpkg will use whatever cmake > 3.12.4 the user has installed. In my case it was version 3.15.1, and I ran into the linker errors described, and probably many other users have cmake >= 3.15 installed. 

> So you probably want to detect if the policy exists and then set the variable.

The variable is ignored by CMake if the policy is not set so IMHO there is no harm in setting it. I am actually not sure this would even be possible, since we'd have to do this check in the toolchain file, but AFAIK the policies are set later in the user's ports, and these will be different for each port.

**Comment by MikeGitb** [comment]
Isn't the only triplet that is affected by the new policy the windows-static one? For the regular one, cmake's default should be fine no? 

Off Topic, but I still think it is a bad idea to statically link against the CRT - even (or especially) when using static libraries.

**Comment by marcrambo** [comment]
I think that is correct yes. According to the CMake documentation "... If that property is not set then CMake uses the default value MultiThreaded$<$<CONFIG:Debug>:Debug>DLL to select a MSVC runtime library."
So currently all 32/64bit, Dynamic/Static linkage, static CRT linkage triplet combinations are failing. 

I agree that static CRT linkage usually doesn't make much sense. I could imagine that this option is interesting for smaller projects who don't necessarily want to ship an installer to deploy the runtime library.

**Comment by mbeutel** [comment]
> Off Topic, but I still think it is a bad idea to statically link against the CRT - even (or especially) when using static libraries.

I also agree, and I wish the combination of dynamic CRT and static libraries was supported by an official triplet in Vcpkg.

**Comment by marcrambo** [comment]
Any feedback on this?

**Comment by JackBoosY** [comment]
@strega-nil Could you review this PR?

Thanks.

**Comment by strega-nil** [comment]
This looks good! Lemme rerun the azure pipelines.

**Comment by marcrambo** [comment]
Not sure why the MacOS CI step wasn't passing as my changes only affect Windows. Anyways, this PR was already pretty old so I rebased onto master and now the CI passes.

**Comment by strega-nil** [comment]
Cool, thanks @marcrambo :)

**Pull request merged**
