### PR TITLE
[simdjson]Update to version 3.6.2

### LINKED ISSUE #34823: [libsimdjson] update to 14 (with support for .a/.lib in debug and release)
### Library name

libsimdjson

### New version number

14

### Other information that may be useful (release notes, etc...)

Hello,

The library should now offer static capable linkage files `.a` / `.lib` --- it already support .dll or .so files

`arm64` and `x86_64` should also be supported.

Thanks

### PR DESCRIPTION
**Pull request by JonLiu1993**
Fixes #34823

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

All features are tested successfully in the following triplet:
- x86-windows
- x64-windows
- x64-windows-static

### CODE REVIEW

**Comment by myd7349** [comment]
Hi! @JonLiu1993 Simdjson has just released version 3.6.2. Could you please update the PR to this latest version?

**Review by Adela0814 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the update!

**Comment by hongxinGuo** [comment]
Hi! @JonLiu1993 Simdjson has just released version 3.8.0. Could you please update the PR to this latest version?

**Pull request merged**
