### PR TITLE
[highfive] Update to v2.3

### PR DESCRIPTION
**Pull request by myd7349**
**Describe the pull request**

- #### What does your PR fix?  
  Fixes #...

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  <all / linux, windows, ...>, <Yes/No>

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes.

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Review by JonLiu1993 — COMMENTED** [review]
Please change "file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/highfive RENAME copyright)" to "file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)" in the portifile.cmake

**Comment by PhoebeHui** [comment]
@myd7349, thanks for your contribution! ping us if the PR ready for review.

**Comment by myd7349** [comment]
Hi! @JonLiu1993 @PhoebeHui Sorry for the long delay. I think I have finished this PR. Please review. Thanks.

**Review by JonLiu1993 — APPROVED** [review]

**Comment by JonLiu1993** [comment]
All features are tested successfully in the following triplets:
- x86-windows
- x64-windows
- x64-windows-static

**Comment by strega-nil-ms** [comment]
Thanks @myd7349 :)

**Pull request merged**
