### PR TITLE
[flatbuffers] support iOS triplets

### PR DESCRIPTION
**Pull request by luncliff**
### What does your PR fix?

Exclude `flatc` build target which requires `BUNDLE DESTINATION`. (config error when iOS triplets)

I encountered this issue while trying `arm` triplets for #15717, and found an old issue #7380.  

### Which triplets are supported/not supported? Have you updated the CI baseline?

4 iOS triplets should become available with this PR.

* arm64-ios
* arm-ios
* x64-ios
* x86-ios

### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

Sure. I think this is the minimum change.

### CODE REVIEW

**Comment by luncliff** [comment]
#15717 changes `Port-Version` of `flatbuffers`. To prevent a collision, changed to a draft.

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
Is this PR ready for review now @luncliff?

**Comment by luncliff** [comment]
I think so.  
I don't have a test project which uses `flatbuffers` in iOS in my hand... but the change is small(just disables `flatc`), so it won't be a matter I think.

**Comment by NancyLi1013** [comment]
Thanks for your feedback. 

Since these triplets are all community triplets, CI machine will not test these. Have you tested them locally?

**Comment by luncliff** [comment]
> Thanks for your feedback.
> 
> Since these triplets are all community triplets, CI machine will not test these. Have you tested them locally?

Yes. Without the executable build target, the port only builds several source files.

[flatbuffers-ios.zip](https://github.com/microsoft/vcpkg/files/6195248/flatbuffers-ios.zip)

**Comment by ras0219-msft** [comment]
LGTM, thanks for the PR!

**Pull request merged**
