### PR TITLE
[parallel-hashmap] Update to version 1.36

### PR DESCRIPTION
**Pull request by greg7mdp**
- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  all

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by FrankXie05** [comment]
@greg7mdp For any modification of the port files, even an empty commit needs to comply with the `port-version` policy.
See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports) :)

**Comment by greg7mdp** [comment]
@FrankXie05 sorry about this, I believe I addressed the empty change.

**Comment by FrankXie05** [comment]
@greg7mdp 
`vcpkg` does not build port `test` and `example` projects by default, which can reduce unnecessary build time. :)
````
# Use greg7mdp/parallel-hashmap's own build process, skipping examples and tests
vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        -DPHMAP_BUILD_TESTS=OFF
        -DPHMAP_BUILD_EXAMPLES=OFF
)
````

**Comment by greg7mdp** [comment]
Thanks a lot @FrankXie05 , I added the change!

**Review by FrankXie05 — APPROVED** [review]

**Comment by vicroms** [comment]
Thanks for the PR!

**Comment by greg7mdp** [comment]
Thank you for merging it :-)

**Pull request merged**
