### PR TITLE
[vcpkg baseline] [Qt6] add FETCH_REF for qt modules without tag

### LINKED ISSUE #21918: [<qtinterfaceframework>] build failure
**Host Environment**
- OS: Windows

**To Reproduce**
`./vcpkg install qtinterfaceframework`

**Failure logs** 
```
Building package qtinterfaceframework[core]:x64-windows...
-- Fetching https://code.qt.io/qt/qtinterfaceframework.git 118fa138186144cf2d802405255f08662ed76d43...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: "C:/Program Files/Git/mingw64/bin/git.exe" fetch https://code.qt.io/qt/qtinterfaceframework.git 118fa138186144cf2d802405255f08662ed76d43 --depth 1 -n
    Working Directory: D:/dev/vcpkg/downloads/git-tmp
    Error code: 128
    See logs for more information:
      D:\dev\vcpkg\buildtrees\qtinterfaceframework\git-fetch-x64-windows-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_git.cmake:123 (vcpkg_execute_required_process)
  installed/x64-windows/share/qtbase/qt_install_submodule.cmake:32 (vcpkg_from_git)
  ports/qtinterfaceframework/portfile.cmake:62 (qt_download_submodule)
  scripts/ports.cmake:142 (include)


Error: Building package qtinterfaceframework:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+qtinterfaceframework
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[qtinterfaceframework]+Build+error
including:
  package: qtinterfaceframework[core]:x64-windows -> 6.2.2
    vcpkg-tool version: 2021-11-24-48b94a6946b8a70abd21529218927fd478d02b6c
    vcpkg-scripts version: 7bb175eaf 2021-12-07 (14 hours ago)
```

**Additional context**
```
cat .\vcpkg\buildtrees\qtinterfaceframework\git-fetch-x64-windows-err.log
error: Server does not allow request for unadvertised object 118fa138186144cf2d802405255f08662ed76d43
```
```
curl https://code.qt.io/qt/qtinterfaceframework.git
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /qt/qtinterfaceframework.git was not found on this server.</p>
</body></html>
```

### PR DESCRIPTION
**Pull request by Neumann-A**
Trying to fix CI errors

closes #21918

### CODE REVIEW

**Comment by BillyONeal** [comment]
Thank you so much :D :D :D <3

**Comment by PhoebeHui** [comment]
@Neumann-A, I still could repro qtinterfaceframework failrues locally with these changes, it seems use the binary cache in CI testing, so it passed in CI testing. 

https://dev.azure.com/vcpkg/public/_build/results?buildId=64325&view=logs&j=7922e5c4-0103-5f8f-ad17-45ce9bb98e80&t=491b9f02-7edc-5990-cda1-511e95a3768e

```
Starting package 77/98: qtinterfaceframework:x64-windows
Installing package qtinterfaceframework[core]:x64-windows...
Elapsed time for package qtinterfaceframework:x64-windows: 267 ms
```

**Comment by Neumann-A** [comment]
@PhoebeHui you need to look at the very first ci run of this pr. It rebuild qt completly and succesful.

**Comment by PhoebeHui** [comment]
I only find one run for this PR https://dev.azure.com/vcpkg/public/_build?definitionId=27&_a=summary&keywordFilter=21925.

**Pull request merged**
