### PR TITLE
[libhv] add support ARM

### LINKED ISSUE #27518: [libhv] support for arm
in windows 10 with ndk 25 ,please remove arm in supports
image

image

image

### PR DESCRIPTION
**Pull request by FrankXie05**
Fix #27518

Add support `arm`.

All features have been tested successfully in the following triplet:

- x86-windows
- x64-windows
- x64-windows-static
- arm64-windows

### CODE REVIEW

**Comment by ithewei** [comment]
@FrankXie05 Fixed it by https://github.com/ithewei/libhv/commit/df6e44dfa15a9a92a08962739193bcf7126ad096

**Comment by FrankXie05** [comment]
@ithewei Thank you very much. Are there any plans to release a new version in the near future? The best way we directly update to the new version. :)

**Comment by ithewei** [comment]
> 

OK, I will release a new version in this week.

**Comment by FrankXie05** [comment]
@ithewei Thanks! :)

**Comment by FrankXie05** [comment]
@ithewei Is there any news about the new version? If the time is long, we can temporarily use the patch.  :)

**Comment by ithewei** [comment]
> @ithewei Is there any news about the new version? If the time is long, we can temporarily use the patch. :)

https://github.com/ithewei/libhv/releases/tag/v1.3.0

**Comment by FrankXie05** [comment]
The patch has been merged upstream.

**Comment by FrankXie05** [comment]
@ithewei The error shows that the conditions are not completely added to support `arm64`.

````
D:\buildtrees\libhv\src\fcb6a6b1ef-a914874f53.clean\base\hplatform.h(248): fatal error C1021: invalid preprocessor command 'warning'
````
[install-arm64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/10000484/install-arm64-windows-dbg-out.log)

https://github.com/ithewei/libhv/blob/3a67fe506a291ee94ed80bbdd73553fcb6a6b1ef/base/hplatform.h#L239

**Comment by ithewei** [comment]
> @ithewei The error shows that the conditions are not completely added to support `arm64`.
> 
> ```
> D:\buildtrees\libhv\src\fcb6a6b1ef-a914874f53.clean\base\hplatform.h(248): fatal error C1021: invalid preprocessor command 'warning'
> ```
> 
> [install-arm64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/10000484/install-arm64-windows-dbg-out.log)
> 
> https://github.com/ithewei/libhv/blob/3a67fe506a291ee94ed80bbdd73553fcb6a6b1ef/base/hplatform.h#L239

Do you known any macros to recognize byte order on arm64_windows?

**Comment by FrankXie05** [comment]
@ithewei I mean the judgment on byte order. It seems that there are fewer errors caused by the judgment on `arm64`

**Comment by MonicaLiu0311** [comment]
@FrankXie05 Is there any new progress?

**Comment by FrankXie05** [comment]
Upstream didn't fully add the judgment flag about supporting triplet arm. 
If it doesn't get fixed, I'll add it manually via a patch.
https://github.com/microsoft/vcpkg/pull/27524#issuecomment-1313203798

**Comment by FrankXie05** [comment]
Convert to draft and add conditions to solve CI error.

**Comment by FrankXie05** [comment]
Convert to active to re-run CI check.

**Review by MonicaLiu0311 — DISMISSED** [review]

**Review by BillyONeal — APPROVED** [review]

**Pull request merged**
