### PR TITLE
Update spirv headers

### PR DESCRIPTION
**Pull request by wrosecrans**
Update version of spirv-headers port

- #### What does your PR fix?  

Oldness.  And updated versions of other packages like spirv-tools will depend on stuff that has been added in recent versions of spirv-headers when they get updated.  AFAIK, the new version just adds stuff but I don't think it'll hurt any existing stuff.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
 
Should be supported anywhere, since it's just headers and .json files.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
I think so.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by FrankXie05** [comment]
@wrosecrans Thank for posting this PR, but you must sign this CLA([Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=23282)) before you start. :)

**Comment by wrosecrans** [comment]
Yeah, I'll look into how ${Employer} currently handles approvals for this.  I haven't needed to wrangle a CLA since our last major reshuffle.  It may take me a minute, if somebody else wants to do an equivalent update to spirv-headers before I get there.

**Comment by wrosecrans** [comment]
FYI, the CLA is now signed.  It's in MS's hands if there are any further approvals/reviews for it on your side of the fence.

**Comment by FrankXie05** [comment]
@wrosecrans Is still work for this PR? According to the logs it looks like the `spirv-tools` also needs to be updated. Could you please check again? :)
`install-x64-windows-dbg-out.log:`
```
D:\buildtrees\spirv-tools\x64-windows-dbg\operand.kinds-unified1.inc(1327): error C2065: 'SPV_OPERAND_TYPE_QUANTIZATION_MODES': undeclared identifier
D:\buildtrees\spirv-tools\x64-windows-dbg\operand.kinds-unified1.inc(1329): error C2065: 'SPV_OPERAND_TYPE_OVERFLOW_MODES': undeclared identifier
D:\buildtrees\spirv-tools\x64-windows-dbg\operand.kinds-unified1.inc(1342): error C2065: 'SPV_OPERAND_TYPE_PACKED_VECTOR_FORMAT': undeclared identifier
```
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8212883/install-x64-windows-dbg-out.log)

**Comment by FrankXie05** [comment]
@wrosecrans Is work still being done for this PR?

**Comment by FrankXie05** [comment]
This PR has been inactive for a long time, please reopen it if there is any progress.

**Pull request closed without merging**
