### PR TITLE
[ffmpeg] Enable fdk on arm or uwp.

### PR DESCRIPTION
**Pull request by Sibras**
Enables the use of fdk-aac when using arm or uwp as this is no longer required since fdk was updated to 2.0.2.

### CODE REVIEW

**Comment by cenit** [comment]
can you please add the feature as a default one in vcpkg-ci-ffmpeg also for these new valid configs, so that we test it automatically?

**Comment by NancyLi1013** [comment]
Hi @Sibras 

Thanks for your PR.

Have you tested these features `fdk-aac` and `all-nonfree` on arm and uwp?

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
> can you please add the feature as a default one in vcpkg-ci-ffmpeg also for these new valid configs, so that we test it automatically?

we can test the feature in this way, but should not add it as a default one in master branch, except it's reasonable.

**Comment by Sibras** [comment]
> 
> 
> can you please add the feature as a default one in vcpkg-ci-ffmpeg also for these new valid configs, so that we test it automatically?

The vcpkg-ci-ffmpeg already runs all-nonfree (which includes fdk) so it should be auto running the tests already.

> 
> Thanks for your PR.
> 
> Have you tested these features `fdk-aac` and `all-nonfree` on arm and uwp

As above the ci is already running tests with all dependencies enabled as part of all-nonfree (which includes fdk-aac)

**Comment by cenit** [comment]
> we can test the feature in this way, but should not add it as a default one in master branch, except it's reasonable.

those are for CI only and are used for some specific ports to test as many features as possible, in order to ease review process and guarantee that dependencies are not going to break their non-default features

**Comment by NancyLi1013** [comment]
Have found the build result on ci. Thanks @Sibras 
```
Building package ffmpeg[all,all-gpl,all-nonfree,avcodec,avdevice,avfilter,avformat,avresample,bzip2,core,fdk-aac,freetype,gpl,iconv,lzma,mp3lame,nonfree,openjpeg,openssl,opus,postproc,sdl2,snappy,soxr,speex,swresample,swscale,theora,vorbis,vpx,webp,xml2,zlib]:arm-uwp... done
Installing package ffmpeg[all,all-gpl,all-nonfree,avcodec,avdevice,avfilter,avformat,avresample,bzip2,core,fdk-aac,freetype,gpl,iconv,lzma,mp3lame,nonfree,openjpeg,openssl,opus,postproc,sdl2,snappy,soxr,speex,swresample,swscale,theora,vorbis,vpx,webp,xml2,zlib]:arm-uwp...
Installing package ffmpeg[all,all-gpl,all-nonfree,avcodec,avdevice,avfilter,avformat,avresample,bzip2,core,fdk-aac,freetype,gpl,iconv,lzma,mp3lame,nonfree,openjpeg,openssl,opus,postproc,sdl2,snappy,soxr,speex,swresample,swscale,theora,vorbis,vpx,webp,xml2,zlib]:arm-uwp... done
```

**Comment by NancyLi1013** [comment]
I have made sense why it will run `all-nonfree` in CI test and also cleared about `vcpkg-ci-ffmpeg`. Sorry for my ignorance. Thanks @Sibras @cenit 

https://github.com/microsoft/vcpkg/blob/bb002cdd1a2c9eacbe60d8383fb5d437752b1e4e/scripts/test_ports/vcpkg-ci-ffmpeg/CONTROL#L5

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
