### PR TITLE
[libofx] new port

### PR DESCRIPTION
**Pull request by wrobelda**
**Describe the pull request**
  Adds a new port for LibOFX. Still a WIP. 
  
  Pending:
  - [x] a LibOFX 0.10.8 release. 

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  All official, except UWP on Windows (for now, see https://github.com/libofx/libofx/issues/84) + macOS arm64

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by wrobelda** [comment]
@JonLiu1993 ready now for a review.

**Comment by JonLiu1993** [comment]
All features are tested successfully in the following triplet:
- x86-windows
- x64-windows
- x64-windows-static
- x64-linux

**Comment by JonLiu1993** [comment]
`libofx:x64-windows` triplet usage tested successfully in my local machine.

**Review by JonLiu1993 — DISMISSED** [review]

**Comment by wrobelda** [comment]
@JonLiu1993 just noticed that `portfile.cmake` is missing newline at the end.

**Comment by JonLiu1993** [comment]
> @JonLiu1993 just noticed that `portfile.cmake` is missing newline at the end.



> @JonLiu1993 just noticed that `portfile.cmake` is missing newline at the end.

Could you add it?

**Comment by wrobelda** [comment]
> > @JonLiu1993 just noticed that `portfile.cmake` is missing newline at the end.
> 
> Could you please add it?

Done.

**Review by JonLiu1993 — APPROVED** [review]

**Pull request merged**
