### PR TITLE
[szip] fix hash mismatch

### PR DESCRIPTION
**Pull request by moeinfinityx**

### CODE REVIEW

**Comment by alexkaratarakis** [comment]
I am still getting the old hash when downloading the file. Are you certain your downloaded file is intact?
You can try downloading the file in your browser and checking with `vcpkg hash <file>`.

**Comment by moeinfinityx** [comment]
I cloned a new vcpkg and run `vcpkg install szip` on my home desktop (windows), it downloads the `af7333` file. Manually download the file using firefox also result in the new `af7333` file. However, using msys2 wget on same machine I get the original `ada640` file. Also tried with my laptop, got same result. No proxy is set on both machine. I also tested using vcpkg to install szip on a VPS (archlinux), which successfully downloaded the original `ada640` file.
Comparing those two file, the `af733` one have a extra tar package. It seems like the `ada640` one should be correct. I think there maybe a issue on their server. Don't know if anyone else has encountered this problem.
szip
I've included the af7333 file if you are interested.
[szip-2.1.1.tar.gz](https://github.com/Microsoft/vcpkg/files/2063377/szip-2.1.1.tar.gz)

**Comment by sojdemoghadam** [comment]
Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Infinity_XSent: Friday, 1 June 2018 8:52 PMTo: Microsoft/vcpkgReply To: Microsoft/vcpkgCc: SubscribedSubject: Re: [Microsoft/vcpkg] [szip] fix hash mismatch (#3629)I cloned a new vcpkg and run vcpkg install szip on my home desktop (windows), it downloads the af7333 file. Manually download the file using firefox also result in the new af7333 file. However, using msys2 wget on same machine I get the original ada640 file. Also tried with my laptop, got same result. No proxy is set on both machine. I also tested using vcpkg to install szip on a VPS (archlinux), which successfully downloaded the original ada640 file.
Comparing those two file, the af733 one have a extra tar package. It seems like the ada640 one should be correct. I think there maybe a issue on their server. Don't know if anyone else has encountered this problem.

I've included the af7333 file if you are interested.
szip-2.1.1.tar.gz

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/Microsoft/vcpkg/pull/3629#issuecomment-393932743","url":"https://github.com/Microsoft/vcpkg/pull/3629#issuecomment-393932743","name":"View Pull Request"},"description":"View this Pull Request on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Microsoft/vcpkg","title":"Microsoft/vcpkg","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Microsoft/vcpkg"}},"updates":{"snippets":[{"icon":"PERSON","message":"@moeinfinityx in #3629: I cloned a new vcpkg and run `vcpkg install szip` on my home desktop (windows), it downloads the `af7333` file. Manually download the file using firefox also result in the new `af7333` file. However, using msys2 wget on same machine I get the original `ada640` file. Also tried with my laptop, got same result. No proxy is set on both machine. I also tested using vcpkg to install szip on a VPS (archlinux), which successfully downloaded the original `ada640` file.\r\nComparing those two file, the `af733` one have a extra tar package. It seems like the `ada640` one should be correct. I think there maybe a issue on their server. Don't know if anyone else has encountered this problem.\r\n![szip](https://user-images.githubusercontent.com/6095297/40850804-28311d50-65f8-11e8-8739-5ddd4312c2fc.png)\r\nI've included the af7333 file if you are interested.\r\n[szip-2.1.1.tar.gz](https://github.com/Microsoft/vcpkg/files/2063377/szip-2.1.1.tar.gz)\r\n"}],"action":{"name":"View Pull Request","url":"https://github.com/Microsoft/vcpkg/pull/3629#issuecomment-393932743"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Re: [Microsoft/vcpkg] [szip] fix hash mismatch (#3629)",
"sections": [
{
"text": "",
"activityTitle": "**Infinity_X**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@moeinfinityx",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Microsoft/vcpkg\",\n\"issueId\": 3629,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close pull request",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"PullRequestClose\",\n\"repositoryFullName\": \"Microsoft/vcpkg\",\n\"pullRequestId\": 3629\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Microsoft/vcpkg/pull/3629#issuecomment-393932743"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 340998723\n}"
}
],
"themeColor": "26292E"
}

**Comment by ras0219-msft** [comment]
Closing for inactivity; if the problem persists, please open a new issue!

**Pull request closed without merging**
