### PR TITLE
Change z_vcpkg_fixup_rpath_in_dir to behave like other vcpkg helpers

### PR DESCRIPTION
**Pull request by BillyONeal**
This updates the list of helper port scripts in ports.cmake to ensure it has every file in scripts/cmake, and changes the caller to conditionally call the function rather than conditionally include.

This was extracted from https://github.com/microsoft/vcpkg/pull/31748/ but I'm not sure we want to do it.

### CODE REVIEW

**Comment by BillyONeal** [comment]
I intentionally cancelled the build because this will trigger a world rebuild and I'm first really trying to find out of we want to do this or not.

**Review by Osyotr — APPROVED** [review]

**Comment by dg0yt** [comment]
But it can be combined with other changes, e.g. https://github.com/microsoft/vcpkg/pull/34546 - mark it for a roll-up.

**Comment by dg0yt** [comment]
In particular, it is close to #32200.

**Comment by BillyONeal** [comment]
> But it can be combined with other changes, e.g. #34546 - mark it for a roll-up.

Yeah I don't dislike the change but the pros and cons seemed to be a net zero (parsing more code for 'no reason' vs. being consistent in how this works) meaning it wasn't worth the cost. But if someone wants to do something similar in one of those other PRs I wouldn't object

**Comment by dg0yt** [comment]
FTR the price of this change touches a weak point of current script hashing: It is impossible to filter out platform-specific code.

**Pull request closed without merging**
