### PR TITLE
[OpenCV][ffmpeg] Use ffmpeg built by vcpkg in OpenCV - WIP

### PR DESCRIPTION
**Pull request by themikem**
This is based on the OpenCV 3.4.1 update  ( https://github.com/Microsoft/vcpkg/pull/2906 ) by @cenit .  Adds the ability to build a new opencv_ffmpeg.dll wrapper library from a build of ffmpeg.  Current default opencv build settings of the ffmpeg wrapper disable most hardware acceleration of the ffmpeg library.  This allows restoring that functionality as well as (eventually) updating the version of the ffmpeg library used with opencv.

This brings windows opencv into close parity with other platforms.  I did not remove the dll altogether, although that is likely where this should go next.  There is no reason to treat windows differently than Linux / MacOS if we can have a reliable build of ffmpeg.

Has a few fixes (handles debug mode correctly, etc.) and extensions.  I need to put version detection into the FindFFMPEG.cmake script, but I wanted to put a "beta" version out there while we're waiting on the OCV 3.4.1 update to be merged.

Appreciate any comments / suggestions.

### CODE REVIEW

**Comment by paul-michalik** [comment]
Are you going to fix the conflicts? This would be a great addition!

**Comment by themikem** [comment]
I actually already have, and I now have a complete working version, but I've had to re-arrange the way I went about it.  I'll post it in the next day or two.

On Apr 9, 2018, at 2:56 AM, Paul Michalik <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you going to fix the conflicts? This would be a great addition!

-

**Comment by cbezault** [comment]
@themikem We're interested in getting this change into vcpkg, if you have some additional changes you're sitting on we'd love to have them!

**Comment by cenit** [comment]
@cbezault I am preparing a revival of it in my opencv4 port. Last time @ras0219-msft killed it after i made it ready, it was proposed again by @themikem but this PR got lost nowhere. I hope next time it will work. Also because now opencv is broken with ffmpeg feature on linux/mac (no feature is tested in CI...)

**Comment by cbezault** [comment]
Thanks @cenit, I'll let @vicroms handle it then,

**Pull request closed without merging**
