### PR TITLE
[vcpkg baseline][spatialite-tools] fix linux osx build falied

### PR DESCRIPTION
**Pull request by longhuan2018**

### CODE REVIEW

**Comment by longhuan2018** [comment]
@JackBoosY  I added port version: 1 to the control file, but portfile.cmake The content of is not updated, only fix is updated- makefiles.patch File, do I need to revise it portfile.cmake Write something in it?
```
Found the following errors:
Error: While reading versions for port spatialite-tools from file: C:\a\1\s\port_versions\s-\spatialite-tools.json
       Version `5.0.0#1` was not found in versions file.
       Run:

           vcpkg x-add-version spatialite-tools

       to add the new port version.
```

**Comment by JackBoosY** [comment]
Don't worry, I will handle that now.

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
ping @dan-shaw for merge this PR quickly.

**Comment by ras0219-msft** [comment]
Thanks for the fixes!

**Pull request merged**
