### PR TITLE
Add Dbow3 Library

### PR DESCRIPTION
**Pull request by RamadanAhmed**

### CODE REVIEW

**Comment by Voskrese** [comment]
delete str
`         -DBUILD_SHARED_LIBS=ON`

**Comment by vicroms** [comment]
Thanks for your contribution!

**Comment by cenit** [comment]
This is the original repository of this library... shall we change to that maybe??.......

https://github.com/rmsalinas/DBow3

**Comment by cenit** [comment]
Also I am not sure it really requires opencv3 and is not working with the generic opencv[contrib]

**Comment by RamadanAhmed** [comment]
> This is the original repository of this library... shall we change to that maybe??.......
> 
> https://github.com/rmsalinas/DBow3

I tried to build it on windows but it didn't go smoothly
 
> Also I am not sure it really requires opencv3 and is not working with the generic opencv[contrib]

You are correct, but I was working with opencv3 so it asked me to rebuild the whole opencv package at the time

**Comment by cenit** [comment]
While I appreciate your efforts, usually it's best to link to the original repository and attach a patch to the portfile here to make it work. Personal repositories are not very well received by the downstream users (people that might want to use DBow3 but don't know you and so might assume it's a different library)

**Comment by RamadanAhmed** [comment]
Thank you for the information
I will try to make a patch from diff in CMakelists.txt and make another PR soon

**Comment by Voskrese** [comment]
https://github.com/rmsalinas/DBow3/pull/38.patch

**Comment by RamadanAhmed** [comment]
@Voskrese Thanks alot

**Pull request merged**
