### PR TITLE
[capstone] update to 5.0.0-rc2

### PR DESCRIPTION
**Pull request by theblackunknown**
**Describe the pull request**

This PR upgrades the `capstone` port to 5.0.0-rc2 version.
This update allows us to simplify the `portfile.cmake` thanks to recent improvements.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
They are all supported, no update was made to ci.baseline.txt

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
Yes

### CODE REVIEW

**Comment by JonLiu1993** [comment]
@theblackunknown ,Thanks for your pr, looks the ci tested failed on many triplets,
This is error log, Please take a look
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8424223/install-x86-windows-dbg-out.log)

**Comment by theblackunknown** [comment]
@JonLiu1993 Indeed, the `triton` port has been impacted.
I have just pushed a series of changes which should solves this, I'll check later the CI results.

**Comment by theblackunknown** [comment]
Commit 978e854 is irrelevant to this PR but I have noticed an error in the way the library linkage was done for `triton`.

**Comment by JonLiu1993** [comment]
@theblackunknown ,Fixed a lot of triplets, now only UWP is left,
[install-x64-uwp-dbg-out.log](https://github.com/microsoft/vcpkg/files/8439183/install-x64-uwp-dbg-out.log)

**Comment by theblackunknown** [comment]
Looks @JonLiu1993 ! It is all green !

**Review by JonLiu1993 — APPROVED** [review]

**Comment by strega-nil-ms** [comment]
Thanks!

**Pull request merged**
