### PR TITLE
[boost-context] fix linux -> windows cross compile

### LINKED ISSUE #16352: [boost-context] build failure (linux -> windows cross compile)
**Host Environment**
- OS: Linux (Docker Container with [mxe](https://github.com/mxe/mxe))
- Compiler: x86_64-w64-mingw32.shared.posix-gcc (GCC) 8.4.0

**To Reproduce**
1. Use the mxe environment + vcpkg with master of vcpkg-tool (for "host": true / #15424 ) + boost-build patches
1. ./vcpkg install boost-context --triplet=x64-linux-windows-static
2. Get error

**Failure logs** 
Not important, but: [install-x64-linux-windows-static-rel-out.log](https://github.com/microsoft/vcpkg/files/6018923/install-x64-linux-windows-static-rel-out.log)

**Solution**
You have to pass `abi=ms binary-format=pe` to b2 when compiling `boost-context`, but not when compiling other boost packages.  
So maybe we need an additional parameter for the function `boost_modular_build`.

### PR DESCRIPTION
**Pull request by autoantwort**
**Describe the pull request**

- What does your PR fix? Fixes #16352

### CODE REVIEW

**Comment by cenit** [comment]
usually boost port files are auto generated. it might be better to fix the generating script in order to not loose your mods the next update

**Comment by autoantwort** [comment]
Yeah the script https://github.com/microsoft/vcpkg/blob/master/scripts/boost/generate-ports.ps1#L185 uses the `b2-options.cmake.in` file and creates the same code as I

**Review by PhoebeHui — APPROVED** [review]
LGTM, thanks for the PR!

**Comment by ras0219-msft** [comment]
This PR LGTM, however should this fragment always be applied to all boost builds? Or is boost-context the only library that cares about `abi=ms`?

**Review by ras0219-msft — APPROVED** [review]

**Comment by autoantwort** [comment]
> This PR LGTM, however should this fragment always be applied to all boost builds? Or is boost-context the only library that cares about `abi=ms`?

No this is a boost-context only option. See [here](https://github.com/boostorg/context/blob/develop/build/Jamfile.v2#L87).

**Comment by ras0219-msft** [comment]
LGTM, thanks again!

**Pull request merged**
