### PR TITLE
[libconfig] shlwapi is not available on linux

### PR DESCRIPTION
**Pull request by vmiheer**
** This fixes error while building for `x64-linux-dynamic` **

- Which triplets are supported/not supported? Have you updated the CI baseline?
This will add support for non-standard `x64-linux-dynamic`

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes.

### CODE REVIEW

**Comment by BillyONeal** [comment]
Does this remove the need for the `libconfig:x64-osx=fail` in ci.baseline.txt?

**Comment by vmiheer** [comment]
> Does this remove the need for the `libconfig:x64-osx=fail` in ci.baseline.txt?

I am not sure. 😊

**Review by BillyONeal — APPROVED** [review]

**Review by NancyLi1013 — COMMENTED** [review]
Could you please also update version in CONTROL file?

Update
`Version: 1.7.2-2`
as
```
Version: 1.7.2
Port-Version: 3
```

**Comment by vmiheer** [comment]
@NancyLi1013, done.

**Review by NancyLi1013 — APPROVED** [review]

**Pull request merged**
