### PR TITLE
[vcpkg] Fix nuget/aria2/ninja version/filename inconsistent

### PR DESCRIPTION
**Pull request by LilyWangL**
**Describe the pull request**
Fix nuget/aria2/ninja in vcpkgTools.xml, vcpkg_find_acquire_program.cmake version/filename inconsistent
- What does your PR fix? Fixes issue #10625

- Which triplets are supported/not supported? Have you updated the CI baseline?

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

### CODE REVIEW

**Review by PhoebeHui — APPROVED** [review]
LGTM

**Comment by Voskrese** [comment]
https://github.com/ninja-build/ninja/releases
> ninja v1.10.0 released this on 28 Jan
?

**Review by JackBoosY — APPROVED** [review]

**Comment by LilyWangL** [comment]
> https://github.com/ninja-build/ninja/releases
> 
> > ninja v1.10.0 released this on 28 Jan
> 
> ?

This PR fix issue #10655. Ninja will update to new version by other PRs.

**Comment by Voskrese** [comment]
why can't you update the version right away as it contradicts

**Comment by dan-shaw** [comment]
Going to merge this to fix the immediate issue. For updating Ninja, we can open another PR

**Pull request merged**
