### PR TITLE
[qwtw] Add new port

### PR DESCRIPTION
**Pull request by ig-or**
add another library port (qwtw)

only Windows x64bit non-static is currently supported. Will try to eventually add Linux.
CI baseline updated.

### CODE REVIEW

**Comment by ig-or** [comment]
it tells "Error code: 1
2020-08-04T21:03:20.3877860Z     See logs for more information:
2020-08-04T21:03:20.3883198Z       D:\buildtrees\qwtw\config-x64-windows-out.log"

how to get to the actual log file with more information?

**Comment by LilyWangL** [comment]
@ig-or Thanks for your PR. `qwtw:x64-windows` build failed with the following error:
```
CMake Error at D:/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find Boost (missing: thread) (found version "1.73.0")
Call Stack (most recent call first):
  D:/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  D:/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/share/cmake-3.17/Modules/FindBoost.cmake:2162 (find_package_handle_standard_args)
  C:/agent/_work/1/s/scripts/buildsystems/vcpkg.cmake:419 (_find_package)
  buildsys/ccmake.cmake:157 (find_package)
  buildsys/ccmake.cmake:924 (addBoost)
  buildsys/ccmake.cmake:1033 (commonEnd)
  qwtw/c_lib/CMakeLists.txt:112 (libraryEnd)
```
You can download the error log from this URL: https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/41073/artifacts?artifactName=x64-windows%20port%20build%20failure%20logs&api-version=5.1&%24format=zip

**Comment by ig-or** [comment]
LilyWangL, thank you very much. Will try to fix it.

**Comment by ig-or** [comment]
@LilyWangL , would you please review?

**Review by LilyWangL — APPROVED** [review]

**Comment by strega-nil** [comment]
Cool, thanks @ig-or :)

**Pull request merged**
