### PR TITLE
[zziplib]Fix build error in linux.

### PR DESCRIPTION
**Pull request by JackBoosY**
Missing **configure** parameter, **ZILB_INCLUDE_DIRS** and **config.h**, I added and modified them.

Relate: #4751.

### CODE REVIEW

**Comment by cenit** [comment]
mmm __config.h should be generated by configure, not hardcoded by us...
I was using this lib recently, updated with #6188, and I didn't find anymore problems with linux after the PR was merged...

**Comment by JackBoosY** [comment]
@cenit Sorry, I didn't notice that **config.h.in** exists in the source code. I will continue to fix this issue.
And if it doesn't fix it, it really can't be built.

**Comment by cenit** [comment]
which error do you see using latest master?

**Comment by JackBoosY** [comment]
> which error do you see using latest master?
```
**:~/master/vcpkg$ cat /home/***/master/vcpkg/buildtrees/zziplib/autotools-config-x64-linux-err.log
sed: -e expression #1, char 0: no previous regular expression
configure: error: zlib.h not found: "zlib" is required to build "zziplib"
```

**Comment by vicroms** [comment]
I'm not sure whether the changes to CMakeLists.txt are needed. the configure step in the portfile should be enough. 

Although, the configure line in master is missing `--with-zlib` which seems to be important.

**Comment by JackBoosY** [comment]
Well... let me tell you the steps I have to solve this problem:
1. Run `./vcpkg install zzip` in linux without any fixes.
2. Error `configure: error: zlib.h not found: "zlib" is required to build "zziplib"`.
3. Dive into the _source/configure_ file and look for errors because **$prefix** defaults to **NONE**(line 845).
4. Find the comment that shows `--prefix = PREFIX`(line 1393), so we need to set the zlib header path here.
5. Rerun `./vcpkg install zzip` by set `--prefix = ${CURRENT_INSTALLED_DIR}`.
6. The same error as step 2.
7. Continue looking for the macro **prefix**.
8. On line 1481, `--with-zlib zlib prefix (eg '$HOME / software')`.
9.  Add `--with-zlib` to the **configure** option.
10. Rerun `./vcpkg install zzip` with set `--prefix = $ {CURRENT_INSTALLED_DIR}` and `--with-zlib`.
11. Built was successful.

**Pull request merged**
