### PR TITLE
[libqglviewer] add new port

### PR DESCRIPTION
**Pull request by renshi-code**
Adding a new portfile for the QGLViewer library http://libqglviewer.com/

### CODE REVIEW

**Comment by Rastaban** [comment]
@TheScarfix I see failures in the static windows builds, are these expected?

**Comment by TheScarfix** [comment]
http://libqglviewer.com/installWindows.html I think it is dll only
 on windows, also haven't tested the other platforms yet

**Comment by Rastaban** [comment]
Our CI system avoids building ports that are unchanged by caching the installed files.  qt5-base is doing something that causes it to not be cached correctly in our system which can cause failures in dependent ports that should build correctly.  I am looking into addressing that issue but it should not hold up this port.  To work the issue I made a whitespace change in qt5-base which should get the system to do a clean build.  I should be able to merge this change after that completes.

**Comment by TheScarfix** [comment]
@Rastaban thank you :) will work on a linux compatible version as soon as I get the qmake system working there.

**Comment by Rastaban** [comment]
NP, thanks for the work!  The tests looks better with the qt5-base rebuild so I am going to accept this port as is, when you get the Linux compatible version it can be added in a separate PR.

**Pull request merged**
