### PR TITLE
[sentry-native] Add features 'backend' and 'transport'

### LINKED ISSUE #27696: [sentry-native] support different backends via feature flags
****

**Is your feature request related to a problem? Please describe.**

I only use sentry for generic event reporting, and don't need the crashpad machinery.

**Proposed solution**
Add feature flags for different backends, including "none" backend.

**Describe alternatives you've considered**
Compile myself, but its a headache as its using cmake where as my projects use msbuild.

### PR DESCRIPTION
**Pull request by dg0yt**
- Moves choice between alternative specific backends from the portfile to upstream's buildsystem.
- Enables opt-out from the default backend/transport, explicitly selecting the 'none' backend/transport in this case.
- Resolves #27696 wrt to choosing the 'none' backend. Alternative to #27770, implementing proper additive, default features. CC @FrankXie05.

### CODE REVIEW

**Comment by Osyotr** [comment]
This is why we need https://github.com/microsoft/vcpkg/pull/22216 ASAP

**Comment by MonicaLiu0311** [comment]
Because some edits overlap with https://github.com/microsoft/vcpkg/pull/27770, waiting for @FrankXie05  response.

**Comment by dg0yt** [comment]
This PR is what #27770 should have done...

**Comment by MonicaLiu0311** [comment]
> This PR is what #27770 should have done...

Closed #27770.

**Comment by MonicaLiu0311** [comment]
All features are tested successfully in the following triplet:
x86-windows
x64-windows
x64-windows-static

**Review by MonicaLiu0311 — APPROVED** [review]

**Comment by BillyONeal** [comment]
I have not totally internalized what this PR is doing; the added feature looks suspiciously like 'do not use features to control alternatives'. However, @vicroms looked at this and said that this 'feature plus triplet variable' thing we have accepted before under some precedent established when I was on vacation. So I'm going to take his word for it :)

Thanks for the submission!

**Pull request merged**
