### PR TITLE
[abseil] update to 20240116.0

### PR DESCRIPTION
**Pull request by miyanyan**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [ ] The "supports" clause reflects platforms that may be fixed by this new version.
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [ ] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by miyanyan** [comment]
image

grpc failed, but i don't know how to see the detail logs

**Comment by JonLiu1993** [comment]
This is detail error log:
````
FAILED: CMakeFiles/grpc.dir/src/core/lib/iomgr/tcp_posix.cc.o 
/usr/bin/c++  -I/mnt/vcpkg-ci/b/grpc/src/v1.51.1-1066d25324.clean/include -I/mnt/vcpkg-ci/b/grpc/src/v1.51.1-1066d25324.clean -I/mnt/vcpkg-ci/b/grpc/src/v1.51.1-1066d25324.clean/third_party/address_sorting/include -I/mnt/vcpkg-ci/b/grpc/src/v1.51.1-1066d25324.clean/src/core/ext/upb-generated -I/mnt/vcpkg-ci/b/grpc/src/v1.51.1-1066d25324.clean/src/core/ext/upbdefs-generated -I/mnt/vcpkg-ci/b/grpc/src/v1.51.1-1066d25324.clean/third_party/xxhash -isystem /mnt/vcpkg-ci/installed/x64-linux/include -fPIC  -g -std=c++17 -fPIC -MD -MT CMakeFiles/grpc.dir/src/core/lib/iomgr/tcp_posix.cc.o -MF CMakeFiles/grpc.dir/src/core/lib/iomgr/tcp_posix.cc.o.d -o CMakeFiles/grpc.dir/src/core/lib/iomgr/tcp_posix.cc.o -c /mnt/vcpkg-ci/b/grpc/src/v1.51.1-1066d25324.clean/src/core/lib/iomgr/tcp_posix.cc
/mnt/vcpkg-ci/b/grpc/src/v1.51.1-1066d25324.clean/src/core/lib/iomgr/tcp_posix.cc: In function ‘void update_rcvlowat({anonymous}::grpc_tcp*)’:
/mnt/vcpkg-ci/b/grpc/src/v1.51.1-1066d25324.clean/src/core/lib/iomgr/tcp_posix.cc:861:19: error: ‘StrCat’ is not a member of ‘absl’
  861 |             absl::StrCat("Cannot set SO_RCVLOWAT on fd=", tcp->fd,
      |                   ^~~~~~
/mnt/vcpkg-ci/b/grpc/src/v1.51.1-1066d25324.clean/src/core/lib/iomgr/tcp_posix.cc: In function ‘bool tcp_do_read({anonymous}::grpc_tcp*, grpc_error_handle*)’:
/mnt/vcpkg-ci/b/grpc/src/v1.51.1-1066d25324.clean/src/core/lib/iomgr/tcp_posix.cc:951:58: error: ‘StrCat’ is not a member of ‘absl’
  951 |             tcp_annotate_error(absl::InternalError(absl::StrCat(
      |                                                          
````

**Comment by JonLiu1993** [comment]
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

**Comment by miyanyan** [comment]
found this pr, https://github.com/grpc/grpc/pull/35589, seems need to include "absl/strings/str_cat.h"

maybe i can wait until this pr finished

**Comment by miyanyan** [comment]
there's a new release of grpc, https://github.com/grpc/grpc/releases/tag/v1.61.0, and already support abseil 202240116.

should we update grpc here or create a new grpc-port-update pr

**Comment by JonLiu1993** [comment]
> there's a new release of grpc, https://github.com/grpc/grpc/releases/tag/v1.61.0, and already support abseil 202240116.
> 
> should we update grpc here or create a new grpc-port-update pr

You can update grpc separately in other PR.

**Comment by dg0yt** [comment]
> > there's a new release of grpc, https://github.com/grpc/grpc/releases/tag/v1.61.0, and already support abseil 202240116.
> > should we update grpc here or create a new grpc-port-update pr
> 
> You can update grpc separately in other PR.

There is #35781.

**Pull request closed without merging**
