### PR TITLE
[implot] Update to v0.7

### PR DESCRIPTION
**Pull request by RT2Code**
https://github.com/epezent/implot/releases/tag/v0.5
https://github.com/epezent/implot/releases/tag/v0.6
https://github.com/epezent/implot/releases/tag/v0.7

### CODE REVIEW

**Comment by LilyWangL** [comment]
Thanks for your PR. Now `implot` build failed on MACOS with the following error:
```
/Users/vagrant/Data/buildtrees/implot/src/v0.6-f150881564.clean/implot_demo.cpp:1344:41: error: a space is required between consecutive right angle brackets (use '> >')
    static ImVector<ImVector<ImPlotPoint>> records;
                                        ^~
                                        > >
1 warning and 1 error generated.
```

**Comment by RT222** [comment]
I added a patch to fix this, it should build fine now.

**Review by LilyWangL — APPROVED** [review]

**Comment by RT222** [comment]
To be honest I'm kinda scared that this PR is going into oblivion. I don't want to sound impatient, but I'd like to check that it has not been forgotten. :)

**Review by ras0219 — APPROVED** [review]

**Pull request merged**
