### PR TITLE
[ffmpeg] Update to 4.1.

### PR DESCRIPTION
**Pull request by peters**

### CODE REVIEW

**Comment by alexkaratarakis** [comment]
Related: https://github.com/Microsoft/vcpkg/pull/3578

**Comment by Rastaban** [comment]
It looks like there is the same aubio and pangolin breaks.  I am testing the aubio fix from @alexkaratarakis and will look into the pangolin issue.

**Comment by Rastaban** [comment]
building pangolin with --head still has the LNK2001 issue reported earlier.  It also has a C2719 error.  I don't plan on digging into this further at this time.

**Comment by Rastaban** [comment]
Pulled fixes for pangolin into a patch to address some of the build failures.  I am retesting the PR now.

**Comment by Rastaban** [comment]
There was still a build break in static aubio on windows that I addressed.  Running tests to verify that is the last issue.  If they are good I will be able to complete this merge.

**Pull request merged**
