### PR TITLE
[vcpkg/configure_cmake] add LOGNAME option

### PR DESCRIPTION
**Pull request by Neumann-A**
preparation for #12936

### CODE REVIEW

**Review by PhoebeHui — APPROVED** [review]
Thanks for the improvements!

**Comment by PhoebeHui** [comment]
The openxr_loader failed with the following failures:

CMake Error: install(EXPORT "openxr_loader_export" ...) includes target "openxr_loader" which requires target "jsoncpp_interface" that is not in any export set.
CMake Error in src/loader/CMakeLists.txt:
  export called with target "openxr_loader" which requires target
  "jsoncpp_interface" that is not in any export set.

**Comment by strega-nil** [comment]
I'll merge this after all the non-osx stuff passes, since we just deleted the osx archives

**Comment by PhoebeHui** [comment]
@strega-nil , all the non-osx triplet passed. ready to merge.

**Pull request merged**
