### PR TITLE
[ace] Upgrade to 7.0.1

### PR DESCRIPTION
**Pull request by jwillemsen**
[ace] Upgrade to 7.0.1

### CODE REVIEW

**Comment by NancyLi1013** [comment]
Hi @jwillemsen 

Thanks for your update.

For the failures on x86-windwos:

```
Found the following errors:
Error: While reading baseline version for port ace.
       While validating latest version from file: C:\a\1\s\versions\a-\ace.json
       Baseline file declares version: 7.0.0.
       But the latest version in version files is: 7.0.1.
       Run:

           vcpkg x-add-version ace
```
Please run `vcpkg x-add-version ace` and then submit the changes.

Besides this, have you tested the features included in this PR? Can they work fine?

**Comment by jwillemsen** [comment]
Updated vcpkg versions. ACE has been fully tested as part of our regular ACE testing

**Comment by NancyLi1013** [comment]
Thanks for your reply. @jwillemsen

Could you please help take a look at https://github.com/microsoft/vcpkg/issues/16551?

**Comment by jwillemsen** [comment]
> Could you please help take a look at #16551?

That is a different issue, that needs more time to analyze and is unrelated to this ACE upgrade PR

**Comment by ras0219-msft** [comment]
LGTM, thanks for the update!

**Pull request merged**
