### PR TITLE
[pfring] Update to 8.4.0 and fix build error

### LINKED ISSUE #22601: [pfring] Build error on x64-osx
Package: pfring[core]:x64-osx -> 2019-10-17#3
**Host Environment**
- Host: arm64-osx
- Compiler: AppleClang 13.0.0.13000029
-    vcpkg-tool version: 2999-12-31-unknownhash-debug
    vcpkg-scripts version: 4fff1e9cf 2022-01-17 (18 hours ago)

**To Reproduce**
`vcpkg install `

**Failure logs**
```
-- Using cached ntop-PF_RING-582fa09bc58411cfe6f27facd7e6438924f779d2.tar.gz.
-- Extracting source /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/downloads/ntop-PF_RING-582fa09bc58411cfe6f27facd7e6438924f779d2.tar.gz
-- Applying patch use-vcpkg-libpcap.patch
-- Applying patch makefile.patch
-- Using source at /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/pfring/src/8924f779d2-d140e6c4f4.clean
-- Found external ninja('1.10.2').
-- Getting CMake variables for x64-osx-dbg
-- Getting CMake variables for x64-osx-rel
-- Building x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:157 (message):
    Command failed: /usr/bin/make V=1 -j 11 -f Makefile all
    Working Directory: /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/pfring/x64-osx-dbg/
    See logs for more information:
      /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/pfring/build-x64-osx-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:187 (vcpkg_execute_build_process)
  ports/pfring/portfile.cmake:22 (vcpkg_build_make)
  scripts/ports.cmake:145 (include)



```
<details><summary>/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/pfring/build-x64-osx-dbg-err.log</summary>

```
make: Makefile: No such file or directory
make: *** No rule to make target `Makefile'.  Stop.
```
</details>

**Additional context**
<details><summary>vcpkg.json</summary>

```
{
  "name": "lichtsteuerung",
  "version-string": "2.0.0",
  "dependencies": [
    "pfring"
  ]
}

```
</details>

### PR DESCRIPTION
**Pull request by LilyWangLL**
Fixes #22601, update `pfring` to 8.4.0 and fix build error.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by dg0yt** [comment]
Can't this port use `vcpkg_configure_make` etc.?

**Comment by LilyWangLL** [comment]
> Can't this port use `vcpkg_configure_make` etc.?

The source of `pfring` only contains the `configure` file. When using `vcpkg_configure_make` for compilation, the following error occurs. However, installing directly using commands `./configure & make` in the source directory is successful.

Error message:
```
./configure: not found
```
The contents of `configure` file:
```
#! /bin/sh
cd ..
./configure $@
```

**Comment by dg0yt** [comment]
If someone wants to repair or update this port: IMO it needs more work, if it makes sense at all.
- Look into [`README.FIRST`](https://github.com/ntop/PF_RING/blob/dev/README.FIRST) for an overview.
- Look into the top-level [`Makefile`](https://github.com/ntop/PF_RING/blob/dev/Makefile) for how configuration and build would proceed normally, outside vcpkg.
- Transform this for vcpkg.

I wonder if the key promise of the package - "High-speed packet processing" -  can be achieved when  
only building the user space library (`userland/lib/`) as the vcpkg port does,  
but omitting the kernel module (`kernel/`), the PF_RING ZC accelerated drivers (`drivers/`) and the Libpcap enhanced with PF_RING support (`userland/libpcap/`).

**Comment by LilyWangLL** [comment]
Closed as duplicate of https://github.com/microsoft/vcpkg/pull/32280.

**Pull request closed without merging**
