### PR TITLE
[openssl] Support static builds on UWP

### PR DESCRIPTION
**Pull request by pabusse**
This PR adds support for static builds of OpenSSL on UWP. Previously, only Windows and Unix flavors allowed setting `VCPKG_LIBRARY_LINKAGE` to `static`.

- #### What does your PR fix?  
  Enables static builds of OpenSSL on UWP.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  Adds support for custom uwp triplets with `VCPKG_LIBRARY_LINKAGE=static`. Does not affect any CI triplets.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

### CODE REVIEW

**Comment by NancyLi1013** [comment]
Hi @pabusse 

Thanks for your PR. I wonder if this is necessary to support.

Since in vcpkg, both `x64-uwp` and `arm-uwp` triplets are built as dynamic. Enable static builds on uwp seems invalid.

**Comment by pabusse** [comment]
The built-in and community triplets use dynamic linking on UWP. This is not a technical limitation, and plenty of software uses static linking instead. In our case, we want to bundle OSS dependencies into an SDK that we distribute as a single .so or .dll file.

I know of several other projects which define their own `x86-uwp-static` and `arm64-uwp-static` triplets. Since the upstream software supports this configuration, it would be limiting for vcpkg to prevent such usage.

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
Thanks for your clarification @pabusse.

**Comment by NancyLi1013** [comment]
Depends on #19633.

**Review by BillyONeal — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for your help!

**Pull request merged**
