### PR TITLE
 [libfabric] initial port of libfabric #4739

### LINKED ISSUE #4739: Port Request : libfabric
https://github.com/ofiwg/libfabric
https://ofiwg.github.io/libfabric/

The Open Fabrics Interfaces (OFI) is a framework focused on exporting fabric communication services to applications. OpenFabrics Interfaces (OFI) is a framework focused on exporting fabric communication services to applications. OFI is best described as a collection of libraries and applications used to export fabric services. The key components of OFI are: application interfaces, provider libraries, kernel services, daemons, and test applications.

### PR DESCRIPTION
**Pull request by ct-clmsn**
initial import of libfabric. 

The Open Fabrics Interfaces (OFI) is a framework focused on exporting fabric communication services to applications. OFI is best described as a collection of libraries and applications used to export fabric services. The key components of OFI are: application interfaces, provider libraries, kernel services, daemons, and test applications.

https://github.com/ofiwg/libfabric
https://ofiwg.github.io/libfabric/

closes #4739

### CODE REVIEW

**Comment by ct-clmsn** [comment]
There is an external dependency for this library on the Network Direct SDK/DDK. Right now, you have to modify the port file, by adding the directory to the unzipped version of the Network Direct SDK/DDK to a variable, for it to build correctly. Is there a mechanism to define command line variables and arguments for vcpkg to propagate into a portfile?

**Comment by Rastaban** [comment]
We normally try to avoid external dependences, but It looks like the Network Direct SDK/DDK is available in a NuGet package at https://www.nuget.org/packages/NetworkDirect, so it could probably be added as a separate library in vcpkg.

**Comment by ct-clmsn** [comment]
@Rastaban is there an example application in vcpkg that integrates with nuget? I can probably get that implemented in a short order.

**Comment by Rastaban** [comment]
Sorry for the huge delay I dropped the ball on this one.  If you are still available to finish this PR then I would love to help you out, but if you have moved on to other things let me know and I will take it over and get it merged.

A nuget package is a zip with a few additional files added to the root directory so you should be able to download with `vcpkg_download_distfile` and extract it with  `vcpkg_extract_source_archive_ex` just like any other zip.

**Comment by Rastaban** [comment]
Passes for x64-windows, which is what is expected for now.  libfabric does support other systems, but those can be done as a separate PR.

**Pull request merged**
