### PR TITLE
Fix for #7903

### LINKED ISSUE #7903: bootstrap-vcpkg.bat is not able to find the VS install
**Describe the bug**
On my newly installed clean Windows 10 Enterprice LTSC machine with visual studio 2019 Enterprise installed the bootstrap-vcpkg.bat script is not able to find the visual studio 2019 install directory.

**Environment**
- OS: Windows 10 Enterprise LTSC
- Compiler: Visual Studio 2019 Enterprise

**To Reproduce**
1. clone the latest git repo
2. navigate to the vcpkg folder
3. run bootstrap-vcpkg.bat

**Expected behavior**
It should find the VS2019 installation directory.

**Failure logs** 
```
c:\Tools\vcpkg>bootstrap-vcpkg.bat
The property 'instance' cannot be found on this object. Verify that the property exists.
At C:\Tools\vcpkg\scripts\bootstrap.ps1:78 char:31
+         foreach ($instance in $asXml.instances.instance)
+                               ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict

Could not find Visual Studio. VS2015 or VS2017 (with C++) needs to be installed.
At C:\Tools\vcpkg\scripts\bootstrap.ps1:143 char:9
+         throw "Could not find Visual Studio. VS2015 or VS2017 (with C ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find ...o be installed.:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find Visual Studio. VS2015 or VS2017 (with C++) needs to be installed.
```

**Additional context**
I did some debugging of the /scripts/bootstrap.ps1 script and the issue seems to be with the following line `$output = & $vswhereExe -prerelease -legacy -products * -format xml` (75). The vswhere.exe utility does not return any results if the command line arguments are specified as followed `vswhere.exe -prerelease -legacy -products *`.

Since it seems to me that the desired result of vswhere execution is to return all results. Hence my suggested fix is to replace the arguments with the single -all parameter. I have already tested this solution on my machine and raised a PR for this ( #7904 ).

### PR DESCRIPTION
**Pull request by mmjr-x**
Fixes #7903

### CODE REVIEW

**Comment by sumagnadas** [comment]
it fixed my bug at least
thanks mmjr-x

**Comment by KineticTheory** [comment]
I just tested this PR on a machine that only has VS-2019 Community installed.  It seems to allow the bootstrap process to run and I no longer see the error reported in #7903.

**Comment by strega-nil** [comment]
I don't think this is still an issue; if you still have this issue, please reopen :)

**Pull request closed without merging**
