### PR TITLE
Fix building AWS SDK for C++  with CMake 3.22.0

### PR DESCRIPTION
**Pull request by ahmedyarub**
**Describe the pull request**

- #### What does your PR fix?  
  Fixes https://github.com/aws/aws-sdk-cpp/pull/1810

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all, Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]
Reasonable.

**Comment by JackBoosY** [comment]
Can you please also report this bug to the upstream?

Thanks.

**Comment by ahmedyarub** [comment]
> ~Can you please also report this bug to the upstream?~ Ah already have a upstream PR.
> 
> Thanks.

I even created a ticket https://github.com/aws/aws-sdk-cpp/issues/1820

**Comment by dg0yt** [comment]
Please remember that port aws-sdk-cpp needs an update (1.9.96 -> 1.9.152).

**Comment by JackBoosY** [comment]
@dg0yt We can accept this then remove the fix patch in the next release.

**Comment by BillyONeal** [comment]
Thanks for the patch!

**Comment by BillyONeal** [comment]
(And for following up with upstream!

**Comment by ahmedyarub** [comment]
> Please remember that port aws-sdk-cpp needs an update (1.9.96 -> 1.9.152).

Amazon rarely, if ever, merges user contributions. I have a couple of PR's hanging there for more than a year already!

**Comment by BillyONeal** [comment]
> Amazon rarely, if ever, merges user contributions. I have a couple of PR's hanging there for more than a year already!

That's a good reason to apply patches. We still usually want upstream to have a first say on any changes since anything we patch *looks* like it comes from upstream; this is the source of most of our guidelines regarding patches (e.g. the ban on implementing features).

If they've had an opportunity to look at a build fix for a while and haven't responded as long as the thing has actually been filed with them and they've had the opportunity, that's fine.

**Pull request merged**
