### PR TITLE
Update vcpkg-tool to 2021-07-16.

### PR DESCRIPTION
**Pull request by BillyONeal**

### CODE REVIEW

**Review by ras0219-msft — APPROVED** [review]

**Review by strega-nil-ms — APPROVED** [review]

**Comment by dg0yt** [comment]
You updated bootstrapping. Will you update the requirements in `ports.cmake` to make people upgrade vcpkg-tool before updating cmake?

https://github.com/microsoft/vcpkg/blob/111220b3cf3311744369425d5c323a0f17941076/scripts/ports.cmake#L28-L29

**Comment by BillyONeal** [comment]
> You updated bootstrapping. Will you update the requirements in `ports.cmake` to make people upgrade vcpkg-tool before updating cmake?
> 
> https://github.com/microsoft/vcpkg/blob/111220b3cf3311744369425d5c323a0f17941076/scripts/ports.cmake#L28-L29

We intentionally don’t update that unless we have a specific reason to force a rebootstrap; the cmake version update seems a good reason to me so maybe it should go in that review? I can prepare a stand-alone update PR if you wish

**Comment by dg0yt** [comment]
I made a comment in #18955 now.

> We intentionally don’t update that unless we have a specific reason to force a rebootstrap

It might be forced for `CMAKE_VERSION VERSION_GREATER 3.21` to limit scope, but OTOH this might not be desired from a maintenance point of view.

**Comment by BillyONeal** [comment]
> It might be forced for `CMAKE_VERSION VERSION_GREATER 3.21` to limit scope, but OTOH this might not be desired from a maintenance point of view.

That's already always true because the vcpkg binary will already download 3.21 if the one on the system is older than the one it has configured.

**Pull request merged**
