### PR TITLE
[vcpkg] improve s390x support

### PR DESCRIPTION
**Pull request by lebdron**
Improve s390x support based on https://github.com/microsoft/vcpkg/pull/11880
- Set `vcpkgUseSystem` in bootstrap.sh
- Check `VCPKG_FORCE_SYSTEM_BINARIES` 
- Define default triplet

### CODE REVIEW

**Comment by PhoebeHui** [comment]
@lebdron, could you format the C++ file?
 
The formatting of the C++ files didn't match our expectation.
See github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#vcpkg-internal-code for solution.
File list:
    toolsrc/src/vcpkg.cpp
clang-format should produce the following diff:
diff --git a/toolsrc/src/vcpkg.cpp b/toolsrc/src/vcpkg.cpp

**Comment by lebdron** [comment]
@PhoebeHui Done, thanks! I would also suggest to specify in documentation which version of clang-format is used for CI, because clang-format-7 and clang-format-10 may have different outputs, for example. I see that "Install llvm clang-format" link points to version 10.0, but that is not that obvious in my opinion.

**Comment by PhoebeHui** [comment]
@lebdron, clang-format-7 and clang-format-10 should be okay, we defined the format in https://github.com/microsoft/vcpkg/blob/master/toolsrc/.clang-format.

**Review by PhoebeHui — APPROVED** [review]
LGTM, thanks for the PR!

@dan-shaw, could you help furhter review?

**Comment by ras0219-msft** [comment]
LGTM, really cool to see further improvements here :)

**Pull request merged**
