### PR TITLE
[openimageio] fix utf-8 build error

### LINKED ISSUE #42327: [openimageio] "/utf-8 is required on Windows" error returns with version v3.0.0.3
### Is your feature request related to a problem? Please describe.

When using Visual Studio 2022, if you include headers from OpenImageIO (such as `OpenImageIO/imagebuf.h`) you get the following compilation error:

```
C:<foo>\out\build\x64-Release\vcpkg_installed\x64-windows\include\OpenImageIO\detail\fmt\base.h(458): error C2338: static_assert failed: 'Unicode support requires compiling with /utf-8'
```

This appears to be related to https://github.com/microsoft/vcpkg/issues/41405, which was resolved by https://github.com/microsoft/vcpkg/pull/41429.  However looking at the portfile, the change (adding `-DINTERNALIZE_FMT=OFF ` to the portfile.cmake) is still present in the most recent port for version v3.0.0.3, so I am unsure how related it is.

I do not get the issue when compiling with g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, which I do using the following commands:

```
mkdir build;
cd build;
cmake ../ -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=<path/to/my/vcpkg>/scripts/buildsystems/vcpkg.cmake
cmake --build .
```

### Proposed solution
Unsure? 

### Describe alternatives you've considered
Unsure of alternatives (for time being, I am continuing to use a previous version of OpenImageIO, which works without issue)

### Additional context
[This public repo](https://github.com/crgnam/oiio-utf8-error) contains a minimal working example to reproduce the error.

### PR DESCRIPTION
**Pull request by JonLiu1993**
Fixes #42327

When using Visual Studio 2022, if you include headers from OpenImageIO (such as `OpenImageIO/imagebuf.h`) you get the following compilation error:

```
C:<foo>\out\build\x64-Release\vcpkg_installed\x64-windows\include\OpenImageIO\detail\fmt\base.h(458): error C2338: static_assert failed: 'Unicode support requires compiling with /utf-8'
```
Add the necessary compile option on Windows

Tested usage successfully by `openimageio:x64-windows`.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [ ] ~~SHA512s are updated for each updated download.~~
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version.~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by dg0yt** [comment]
> include\OpenImageIO\detail\fmt\base.h

Is this a vendored `fmt`? Should this file exist at all?

**Comment by JonLiu1993** [comment]
> > include\OpenImageIO\detail\fmt\base.h
> 
> Is this a vendored `fmt`? Should this file exist at all?

I will replace openimageio's internal fmt with the fmt header file that lets openimageio call vcpkg.

**Review by WangWeiLin-MV — APPROVED** [review]

**Comment by dg0yt** [comment]
Okay, port `fmt` export the same flag. But:
Vendored copy with public headers is worrying. (Possible mismatch with vcpkg port.)
Reading `git` is worrying. (Possible bypass of asset caching.)
The port builds with:
~~~
        -DBUILD_MISSING_FMT=OFF
        -DINTERNALIZE_FMT=OFF  # carry fmt's msvc utf8 usage requirements
~~~
Is something going wrong about using the external fmt?

**Comment by BillyONeal** [comment]
I agree that this seems like fmt needs to be devendored and upstream should be involved before adding exported content like this.

Moreover, it won't even fix many of our customers, such as MSBuild customers.

Moreover, even if we could fix it this way, it isn't clear that we should, since people need to know that this switch is being set underneath them; silently changing the interpretation of every literal in your program because you added a dependency is surprising, and I think it might be appropriate to intentionally tell customers they need to add this flag themselves.

**Comment by BillyONeal** [comment]
@ras0219-msft points out that our toolset should already be doing this:

https://github.com/microsoft/vcpkg/blob/13c226fc46306fa6090db14317a7786099274a3a/scripts/toolchains/windows.cmake#L67-L71

so in addition to my concerns above, I believe this won't fix the situation.

**Comment by BillyONeal** [comment]
> @ras0219-msft points out that our toolset should already be doing this:

But @BillyONeal misunderstood that that toolset only applies building in vcpkg but not customers.

**Comment by BillyONeal** [comment]
(Also, speaking personally: if the real fmt port is doing this, I disagree with that, but at least then we aren't patching in something with which I disagree, we're just delivering someone else doing that. :) )

**Comment by JonLiu1993** [comment]
@BillyONeal, thanks for your review suggesstion, I will try other fixes locally, temporarily close this PR.

**Comment by crgnam** [comment]
Has there been any progress on this issue, or is there a work around for the time being?

**Pull request closed without merging**
