### PR TITLE
[VCPKG baseline] Fix many ports

### PR DESCRIPTION
**Pull request by JackBoosY**
Related: #11502.

### CODE REVIEW

**Comment by JackBoosY** [comment]
@BillyONeal Could you please take a look?
It seems that `geographiclib` source cannot be downloaded.

**Comment by BillyONeal** [comment]
@JackBoosY `geographiclib` and `libaiff` are on SourceForge; that service may have chosen a bad mirror when the build tried to download the bits since SourceForge has a large number of mirrors.

I pushed a change which should fix the /home problem.

**Review by BillyONeal — APPROVED** [review]

**Comment by JackBoosY** [comment]
@dan-shaw @strega-nil Please review and merge this PR first.

Thanks.

**Review by PhoebeHui — APPROVED** [review]
LGTM

**Pull request merged**
