### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by gladhorn**

### CODE REVIEW

**Comment by ShinNoNoir** [comment]
Is it really a typo? In the original text, "simply" is an adverb that modifies an adjective. In your proposed change, "simply" has become an adverb that modifies the sentence.

**Comment by gladhorn** [comment]
"This file is a simply formatted set of fields describing the package's metadata." is grammatically questionable. If it is supposed to be and adjective, it should be simple. So either it is "just" a formatted set of fields or it is a simple formatted set of fields. Probably "a set of formatted fields" would be even more sensible. I don't think it's worth spending time on this though, feel free to just close this or do whatever you please :)

**Comment by ShinNoNoir** [comment]
If we have
> a simple formatted set of fields

then "simple" is an adjective modifying "set of fields". If, on the other hand, we have
> a simply formatted set of fields

then "simply" is an adverb modifying "formatted". Since "formatted" here is an adjective, this means "a set of fields" is described by the adjective phrase "simply formatted". In other words, the formatting is simple.

---

> feel free to just close this

I'm not a collaborator on this project, so I can't do that. Besides, it's up to the vcpkg team to decide what the intended meaning of the original sentence is and whether the current wording is clearly conveying that meaning.

**Comment by ras0219-msft** [comment]
Thanks for pointing out that this could be difficult to read for some! I felt like the most important word was actually "simple", not "formatted", so I revised it further to completely remove any confusion :)

**Pull request merged**
