### PR TITLE
[ignition-*] Update hashes

### PR DESCRIPTION
**Pull request by LilyWangLL**
Update the hash of `ignition-cmake0` and `ignition-cmake2`.

### CODE REVIEW

**Comment by BillyONeal** [comment]
This is a good change, but I want to see discussion from the actual Ignition folks about these ports' future. I think the right answer may be to = skip them since they haven't seemed to care about the vcpkg entries for a long time.

**Comment by BillyONeal** [comment]
OK following discussion in https://github.com/microsoft/vcpkg/issues/24630 I'm checking that the rest of the ignition hashes are OK and will go with this PR

**Review by BillyONeal — APPROVED** [review]

**Comment by BillyONeal** [comment]
@LilyWangLL Please double check that you're happy with this since I fixed the other hashes too :)

**Comment by LilyWangLL** [comment]
> @LilyWangLL Please double check that you're happy with this since I fixed the other hashes too :)

Just add the license for them. Thanks Billy~😀

**Comment by ras0219-msft** [comment]
Please confirm that this change also names the downloaded files differently -- otherwise previous users will have conflicts in the downloads directory (existing files will have the old SHA).

**Comment by BillyONeal** [comment]
I knew I was forgetting something 😅

**Comment by BillyONeal** [comment]
> Do you mind removing docs as well?

@Thomas1664 This is a high priority "can anything be installed at all" fix, and given that these are cmake utilities, it isn't clear to me that these are actually docs (as opposed to generated files which are for this port's *consumers* to use in their own CMake scripts to generate docs).

To that end I'm merging this as is, but welcome @Ace314159 to do that if it makes sense.

@LilyWangLL Thanks for the fix!

**Pull request merged**
