### PR TITLE
[libwebp] update to v1.0.2

### PR DESCRIPTION
**Pull request by cenit**
Besides the upgrade, I also did some **deep** maintenance to the port, which will requires some extensive testing I had no time to do:

- [x] port vastly simplified
- [x] remove unnecessary custom find_package script in favour of original Config files for cmake (this one in particular should fix many problem, also one I am stuck with #5169, but of course can expose problems in ports relying to old "broken" custom script)
- [x] expose all possible build configs, to enable future features easily

### CODE REVIEW

**Comment by cenit** [comment]
I also expanded the port a little bit, enable building of all exe tools.

**Comment by cenit** [comment]
And now I added a compatibility layer inside the official cmake config file, in order to expose the symbol checked by some projects. 
I am not expecting more commits now, please let me know if you see any regression. I will start using the library myself now, so I will also report if I find any problem

**Comment by vicroms** [comment]
This PR causes regressions for `freeimage` on `x64-windows`, however it builds successfuly on `x86-windows`. 

I pulled this PR and #5228 to a local branch for testing. The log shows a lot of unresolved external symbol errors:

```
CMakeFiles\FreeImage.dir\Source\Metadata\XTIFF.cpp.obj 
  <vcpkg_root>installed\x64-windows\debug\lib\zlibd.lib 
  <vcpkg_root>installed\x64-windows\debug\lib\jpegd.lib 
  <vcpkg_root>installed\x64-windows\debug\lib\tiffd.lib 
  <vcpkg_root>installed\x64-windows\debug\lib\libpng16d.lib 
  <vcpkg_root>installed\x64-windows\debug\lib\zlibd.lib 
  <vcpkg_root>installed\x64-windows\debug\lib\openjp2.lib 
  <vcpkg_root>installed\x64-windows\debug\lib\webpd.lib 
  <vcpkg_root>installed\x64-windows\debug\lib\webpdecoderd.lib 
  <vcpkg_root>installed\x64-windows\debug\lib\webpdemuxd.lib 
  <vcpkg_root>installed\x64-windows\debug\lib\libwebpmuxd.lib 
  <vcpkg_root>installed\x64-windows\debug\lib\jpegxrd.lib 
  <vcpkg_root>installed\x64-windows\debug\lib\jxrglued.lib 
  <vcpkg_root>installed\x64-windows\debug\lib\rawd.lib 
  <vcpkg_root>installed\x64-windows\debug\lib\jpegd.lib 
  <vcpkg_root>installed\x64-windows\debug\lib\tiffd.lib 
  <vcpkg_root>installed\x64-windows\debug\lib\libpng16d.lib 
  <vcpkg_root>installed\x64-windows\debug\lib\webpd.lib 
  <vcpkg_root>installed\x64-windows\debug\lib\webpdecoderd.lib 
  <vcpkg_root>installed\x64-windows\debug\lib\webpdemuxd.lib 
  <vcpkg_root>installed\x64-windows\debug\lib\libwebpmuxd.lib 
  <vcpkg_root>installed\x64-windows\debug\lib\jpegxrd.lib 
  <vcpkg_root>installed\x64-windows\debug\lib\jxrglued.lib 
  <vcpkg_root>installed\x64-windows\debug\lib\rawd.lib 
  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib 

PluginEXR.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl Imf_2_2::IStream::~IStream(void)" (__imp_??1IStream@Imf_2_2@@UEAA@XZ) referenced in function "public: virtual __cdecl C_IStream::~C_IStream(void)" (??1C_IStream@@UEAA@XZ)
PluginEXR.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) protected: __cdecl Imf_2_2::IStream::IStream(char const * const)" (__imp_??0IStream@Imf_2_2@@IEAA@QEBD@Z) referenced in function "public: __cdecl C_IStream::C_IStream(struct FreeImageIO *,void *)" (??0C_IStream@@QEAA@PEAUFreeImageIO@@PEAX@Z)
PluginEXR.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl Imf_2_2::OStream::~OStream(void)" (__imp_??1OStream@Imf_2_2@@UEAA@XZ) referenced in function "public: virtual __cdecl C_OStream::~C_OStream(void)" (??1C_OStream@@UEAA@XZ)
.
.
.
FreeImaged.dll : fatal error LNK1120: 67 unresolved externals
ninja: build stopped: subcommand failed.

```

**Comment by cenit** [comment]
@vicroms All my PR are extremely intertwined. I disentagled all of them in single PR because of some previous experience here, when I did a "huge" PR for OpenCV3 but Robert preferred to close my PR, push changes individually and loose track of my work #2764. In view of it I tried my best to separate them but unfortunately I think that without the PR #5227 I fear you cannot solve those problems. Could you please check with also that PR in your local branch?

**Comment by cenit** [comment]
@vicroms any news on this? Did you have time to check with #5227 too? Please let me know if I can do anything to help you with this or any other of my open PRs...

**Comment by vicroms** [comment]
I haven't had the time to keep working on it.

The last thing I did was merge #5227, #5228, #5210, and #5265 into the same branch, but the issue persisted.

Does `.\vcpkg install freeimage:x64-windows` work for you?

I pushed my branch to https://github.com/Microsoft/vcpkg/tree/dev/viromer/cenit-prs 
If you have time can you please compare that with your own source code?

**Comment by cenit** [comment]
x64-windows is my default triplet, so I am confident especially on that triplet... I will test everything again

**Comment by cenit** [comment]
closed in favor of #5417

**Pull request closed without merging**
