### PR TITLE
[CMake] VCPKG_APPLOCAL_DEPS sometimes causes conflicts when processing multiple files in the same directory

### PR DESCRIPTION
**Pull request by sandercox**
In our CMake setup we often have multiple targets output to the same directory keeping lists of plugins together for instance. When these targets run the custom target on windows to gather their depedencies (`VCPKG_APPLOCAL_DEPS` is `on`) the custom target script sometimes complains that files are already in use.

Adding a `USES_TERMINAL` makes sure these commands do on run in parallel. Maybe there is another (better) way to only do when running within the same directory so in 'normal' situation these can still happen in parallel

### CODE REVIEW

**Comment by sandercox** [comment]
> > I'm a bit concerned about USES_TERMINAL potentially making the user's link steps serialized; I haven't checked recently, but I recall this essentially adding an `&& powershell` at the end of the link command, which means that the whole line would be marked as USES_TERMINAL.

I did some tests to see if USES_TERMINAL affects the amount of targets that are linked in parallel, but just removing the linked output on some simple test targets and this seems to work just fine. But, atleast for Ninja generator, USES_TERMINAL will cause all post build steps to be run single threaded. So if a user adds other steps they might conflict.

I've also been looking at the other suggestion of combining and making sure it only runs once. Would you have any pointers as in how to make that happen. Right now we can only know when a target needs this on the `add_executable` call. And the actual dependencies are not soley determined by the CMake script. Eg. if the binary doesn't use a particular DLLs code that was specified using `target_link_library` it will just not list in the `dumpbin`.
So we would then need some dummy target that executes always even when you just compile a single target. I have no idea how to accomplish this in CMake - so I'd need some pointers.

Then again, I do not thing that the USES_TERMINAL is as bad as we were afraid of. I did change the code slightly to make this optional.

**Comment by ras0219-msft** [comment]
Thanks for making it optional -- I think the north start obviously needs to be thread safe all the time (possibly via merging them together), so I named the option accordingly to indicate to users that they shouldn't depend on this behavior.

That said, this seems like a good intermediate solution until we're able to do the perfect one.

**Comment by JackBoosY** [comment]
Blocked by #13722.

**Comment by sandercox** [comment]
#13722 seems to be merged so can this get merged too?

**Comment by JackBoosY** [comment]
Looks good, all test passed.

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
