### PR TITLE
[libvpx, mpg123]Yasm fix msbuild

### PR DESCRIPTION
**Pull request by MVoz**
test

### CODE REVIEW

**Comment by Voskrese** [comment]
`x64-windows port build failure logs\x64-windows\libvpx\build-x64-windows-rel-out.log 
`
?

> Build started 4/20/2020 4:19:28 PM.
>      1>Project "C:\vsts\_work\4\s\buildtrees\libvpx\x64-windows\vpx.vcxproj" on node 1 (Rebuild target(s)).
>      1>CoreClean:
>          Creating directory "x64\Release\vpx\".
>      1>C:\VS2017\Stable\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(379,5): error MSB8020: The build tools for Visual Studio 2017 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install Visual Studio 2017 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\vsts\_work\4\s\buildtrees\libvpx\x64-windows\vpx.vcxproj]
>      1>Done Building Project "C:\vsts\_work\4\s\buildtrees\libvpx\x64-windows\vpx.vcxproj" (Rebuild target(s)) -- FAILED.
> 
> Build FAILED.

**Comment by mcmtroffaes** [comment]
Thanks for this. I can confirm that these two changes:

https://github.com/microsoft/vcpkg/pull/10929/files#diff-7731bcb41a474eab87d622212d61fc16
https://github.com/microsoft/vcpkg/pull/10929/files#diff-98903bbc8e154c3feada9997d871a5dc

fix the libvpx build. This change:

https://github.com/microsoft/vcpkg/pull/10929/files#diff-69af7c0122dce2c87618cc966d665c3c

was not needed for me.

**Comment by Voskrese** [comment]
error `BasePlatformToolset`

**Pull request closed without merging**
