### PR TITLE
Add DevIL port

### PR DESCRIPTION
**Pull request by Lyrex**

### CODE REVIEW

**Comment by xoviat** [comment]
@Lyrex can you sign the CLA? It's just a few minutes.

**Comment by Lyrex** [comment]
Sorry that I did not check back until now. The site was down when I submitted the PR but I signed it now.

**Comment by Agadoul** [comment]
@Lyrex I mad another PR myself.

**Comment by ras0219-msft** [comment]
Thanks for the port! I fixed the static builds while merging :)

**Pull request merged**
