### PR TITLE
[fmilib] Fix linking issues with fmilib by using vendored minizip.

### LINKED ISSUE #30886: [fmilib] the current port builds but is unusable
### Is your feature request related to a problem? Please describe.

The current port for fmilib replaces the vendored version of minizip that comes with [fmi-library](https://github.com/modelon-community/fmi-library/tree/master) with the vcpkg version of minizip. While this all builds fine, the resulting library is actually unusable (at least I don't see how).

The thing is that fmi-library slightly modified minizip (cf. [README.txt here](https://github.com/modelon-community/fmi-library/blob/master/ThirdParty/Minizip/minizip/README.txt)). Among these modifications, they renamed the main function of miniunz to just that -- `miniunz(...)`. Since that functions doesn't exist in the usual minizip library, you get linking errors saying that function `miniunz` is not defined.

### Proposed solution

Don't use minizip as a dependency [in vcpkg.json](https://github.com/microsoft/vcpkg/blob/master/ports/fmilib/vcpkg.json#L11), and do use the vendored version of minizip [this patch](https://github.com/microsoft/vcpkg/blob/master/ports/fmilib/devendor-sublibs.diff#L37).

I gave that a try, and the resulting library is usable then.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by hheld**
Fixes #30886.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by hheld** [comment]
@microsoft-github-policy-service agree

**Comment by dg0yt** [comment]
I do believe your report in #30889 about downstream linking issues. But I'm afraid re-activating the 11 years old fork in fmilib will cause different types of problems.
IIUC the key gap to fill is not the minizip *library* but fmilib's use of modified `minizip.c` and `miniunz.c` which are normally part of the *executables*.

**Comment by dg0yt** [comment]
Let me see... Building with tests enabled reproduces the link error, so I should be able to verify my ideas of approaching this bug. And I already found issues with port minizip.

**Comment by dg0yt** [comment]
My proposal is #30930. It leaves de-vendored what comes with the up to-date minizip lib, but builds the vendored sources of minizip and miniunz which come with fmilib (with minimal fixes backported). @hheld Can you test my PR?

**Comment by hheld** [comment]
> My proposal is #30930. It leaves de-vendored what comes with the up to-date minizip lib, but builds the vendored sources of minizip and miniunz which come with fmilib (with minimal fixes backported). @hheld Can you test my PR?

Awesome, that sounds promising! I did give it a try but got an error that `unofficial-minizip` cannot be found:

```
CMake Error at /home/hheld/.clion-vcpkg/vcpkg (fmilib)/scripts/buildsystems/vcpkg.cmake:852 (_find_package):
  Could not find a package configuration file provided by
  "unofficial-minizip" with any of the following names:

    unofficial-minizipConfig.cmake
    unofficial-minizip-config.cmake

  Add the installation prefix of "unofficial-minizip" to CMAKE_PREFIX_PATH or
  set "unofficial-minizip_DIR" to a directory containing one of the above
  files.  If "unofficial-minizip" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  Config.cmake/fmizip.cmake:27 (find_package)
  CMakeLists.txt:208 (include)
```

**Comment by dg0yt** [comment]
You have to remove minizip first. It needs the version from that PR.

**Comment by hheld** [comment]
Actually, I just completely deleted everything I had and only pulled your version from the PR ... shouldn't that do the trick? I'm not that familiar with `vcpkg` yet, so maybe I'm also doing something wrong here.

When I look at the CMake output of the project I'm trying to build that uses `fmilib`, I see this:

```
The following packages will be built and installed:
    catch2[core]:x64-linux -> 3.3.2 -- /home/hheld/.clion-vcpkg/vcpkg (fmilib)/buildtrees/versioning_/versions/catch2/e776d4cb313c846f6de82c05fa2ab9b7748edb6b
  * expat[core]:x64-linux -> 2.5.0#3 -- /home/hheld/.clion-vcpkg/vcpkg (fmilib)/buildtrees/versioning_/versions/expat/9a1bc114edd74892d292c799e7b45b407f2a0b8b
    fmilib[core]:x64-linux -> 2.4.1#2 -- /home/hheld/.clion-vcpkg/vcpkg (fmilib)/buildtrees/versioning_/versions/fmilib/e875efe56416de71aa671c57a77817c67290f0a9
  * fmt[core]:x64-linux -> 9.1.0#1 -- /home/hheld/.clion-vcpkg/vcpkg (fmilib)/buildtrees/versioning_/versions/fmt/3f452404270b508daf355b72031ad3ee7d0d5751
  * minizip[core]:x64-linux -> 1.2.13 -- /home/hheld/.clion-vcpkg/vcpkg (fmilib)/buildtrees/versioning_/versions/minizip/c0843dcfad42a538a772797a3f50627b5c8d411a
    spdlog[core]:x64-linux -> 1.11.0 -- /home/hheld/.clion-vcpkg/vcpkg (fmilib)/buildtrees/versioning_/versions/spdlog/296d78e54c14ce64474b66f60847026ddb1f576e
    stduuid[core]:x64-linux -> 1.2.2 -- /home/hheld/.clion-vcpkg/vcpkg (fmilib)/buildtrees/versioning_/versions/stduuid/bd235773c953e5636a7b9f6356437daef6e5010c
  * vcpkg-cmake[core]:x64-linux -> 2022-12-22 -- /home/hheld/.clion-vcpkg/vcpkg (fmilib)/buildtrees/versioning_/versions/vcpkg-cmake/1913f86defd2140d0a6751be2d51952e4090efa4
  * vcpkg-cmake-config[core]:x64-linux -> 2022-02-06#1 -- /home/hheld/.clion-vcpkg/vcpkg (fmilib)/buildtrees/versioning_/versions/vcpkg-cmake-config/8d54cc4f487d51b655abec5f9c9c3f86ca83311f
  * zlib[core]:x64-linux -> 1.2.13 -- /home/hheld/.clion-vcpkg/vcpkg (fmilib)/buildtrees/versioning_/versions/zlib/ad5a49006f73b45b715299515f31164131b51982
```

So it uses [your version](https://github.com/dg0yt/vcpkg/blob/fmilib/versions/f-/fmilib.json#L4) of `fmilib`, but port version 0 of `minizip` (see [here](https://github.com/dg0yt/vcpkg/blob/fmilib/versions/m-/minizip.json#L9)) instead of the newer port version 1 [here](https://github.com/dg0yt/vcpkg/blob/fmilib/versions/m-/minizip.json#L4). Shouldn't it build the most recent port version of a dependency if not specified otherwise?

**Comment by dg0yt** [comment]
Are you sure you are building my PR/branch, not your PR/branch? Or are you using manifest mode and need to adjust the manifest?

**Comment by hheld** [comment]
I'm pretty sure, yes. Here is the output of `git remote -v`:

```
origin  https://github.com/dg0yt/vcpkg (fetch)
origin  https://github.com/dg0yt/vcpkg (push)
```

... and the branch (`git branch`):

```
* fmilib
  issue-template
```

And yes, I am using manifest mode with these dependencies:

```json
  "dependencies" : [ {
    "name" : "catch2",
    "version>=" : "3.3.2"
  }, {
    "name" : "spdlog",
    "version>=" : "1.11.0"
  }, {
    "name" : "stduuid",
    "version>=" : "1.2.2"
  }, {
    "name" : "fmilib",
    "version>=" : "2.4.1#2"
  } ]
```

That all sounds right, doesn´t it?

**Comment by dg0yt** [comment]
IIRC the manifest also has a baseline field somewhere. If there is no other information, the baseline determines the minizip  version. If you don't want to raise the baseline, you must add an explicit minizip dependency with the new version.

**Comment by hheld** [comment]
Ah, now I got it :smile: Yes, after raising the baseline, I can confirm that it works with your package.

Thanks, and sorry for the confusion!

**Comment by FrankXie05** [comment]
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". 
          That way, I can be aware that you've responded since you can't modify the tags.

**Comment by hheld** [comment]
This was actually resolved with #30930 such that this merge request is no longer needed. I'll close it.

**Pull request closed without merging**
