### PR TITLE
[liblzma] Patch headers to fix https://github.com/OpenTTD/OpenTTD/pull/7614

### PR DESCRIPTION
**Pull request by ras0219-msft**

### CODE REVIEW

**Comment by PhoebeHui** [comment]
@vicroms, the CI on OSX failed on git 'checkout' steps, could you help take a look?

**Review by PhoebeHui — APPROVED** [review]

**Comment by BillyONeal** [comment]
@ras0219 @ras0219-msft This PR is a year old and now passes tests, should we merge it?

**Review by ras0219 — APPROVED** [review]

**Pull request merged**
