### PR TITLE
[mygui] Update to 3.4.2

### PR DESCRIPTION
**Pull request by Pospelove**
- updated to 3.4.2 
- removed [ports/mygui/Use-vcpkg-sdl2.patch](https://github.com/microsoft/vcpkg/pull/34006/files#diff-56ba36abdc1bc03793a94dbb235801f7ec5467f6882febe6d306ea59b1121775) because upstream now performs similar step to link SDL2
- removed  fix-osx.patch since it was accepted to the upstream repo
- fixed wasm32-emscripten build

while 3.4.3 is already out, it's quite different in some parts. I'm working on a project that doesn't compile with 3.4.3. I guess we should accept 3.4.2 first.

### CODE REVIEW

**Comment by MonicaLiu0311** [comment]
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review".

**Comment by Pospelove** [comment]
note for myself: I should try linking opengl here: https://github.com/MyGUI/mygui/blob/a81a88693fa25710a85a5cd64b2481071bf87f30/Common/CMakeLists.txt

find_package(OpenGL REQUIRED)
    target_link_libraries(main PRIVATE OpenGL::GL)

**Comment by Pospelove** [comment]
@MonicaLiu0311 go

**Comment by MonicaLiu0311** [comment]
An error occurred while testing `features` on `x64-windows-static`: 
```
./vcpkg install mygui[*]:x64-windows-static

...

-- Configuring x64-windows-static
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: G:/mygui/buildtrees/mygui/x64-windows-static-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      G:\mygui\buildtrees\mygui\config-x64-windows-static-dbg-CMakeCache.txt.log
      G:\mygui\buildtrees\mygui\config-x64-windows-static-rel-CMakeCache.txt.log
      G:\mygui\buildtrees\mygui\config-x64-windows-static-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:252 (vcpkg_execute_required_process)
  ports/mygui/portfile.cmake:31 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)
```

G:\mygui\buildtrees\mygui\install-x64-windows-dbg-out.log: 
```
-- Configuring MYGUI 3.4.2
-- Found Freetype: optimized;G:/mygui/installed/x64-windows-static/lib/freetype.lib;debug;G:/mygui/installed/x64-windows-static/debug/lib/freetyped.lib (found version "2.12.1") 
-- Found ZLIB: optimized;G:/mygui/installed/x64-windows-static/lib/zlib.lib;debug;G:/mygui/installed/x64-windows-static/debug/lib/zlibd.lib (found version "1.3.0")  
-- Found BZip2: optimized;G:/mygui/installed/x64-windows-static/lib/bz2.lib;debug;G:/mygui/installed/x64-windows-static/debug/lib/bz2d.lib (found version "1.0.8") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Found PNG: optimized;G:/mygui/installed/x64-windows-static/lib/libpng16.lib;debug;G:/mygui/installed/x64-windows-static/debug/lib/libpng16d.lib (found version "1.6.39") 
-- Could NOT find SDL2 (missing: SDL2_LIBRARY) (found version "2.28.3")
-- Could NOT find SDL2_image (missing: SDL2_IMAGE_LIBRARIES) (found version "2.6.3")
CMake Deprecation Warning at CMake/Dependencies.cmake:56 (cmake_policy):
  The OLD behavior for policy CMP0072 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
Call Stack (most recent call first):
  CMakeLists.txt:189 (include)


-- Found OpenGL: opengl32  found components: OpenGL 
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- 
-----------------------------------------------------------------------------
-- The following external packages were located on your system.
-- This installation will have the extra features provided by these packages.
+ freetype
+ opengl
-----------------------------------------------------------------------------
-- The following OPTIONAL packages could NOT be located on your system.
-- Consider installing them to enable more features from this software.
+ Doxygen: Tool for building API documentation <http://doxygen.org>
-----------------------------------------------------------------------------

-- Found OpenGL: opengl32   
-- Configuring done (5.2s)
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
SDL2_IMAGE_LIBRARY (ADVANCED)
    linked by target "EditorFramework" in directory G:/mygui/buildtrees/mygui/src/MyGUI3.4.2-2a0c5de7a4.clean/Tools/EditorFramework
    linked by target "LayoutEditor" in directory G:/mygui/buildtrees/mygui/src/MyGUI3.4.2-2a0c5de7a4.clean/Tools/LayoutEditor
    linked by target "SkinEditor" in directory G:/mygui/buildtrees/mygui/src/MyGUI3.4.2-2a0c5de7a4.clean/Tools/SkinEditor
    linked by target "ImageEditor" in directory G:/mygui/buildtrees/mygui/src/MyGUI3.4.2-2a0c5de7a4.clean/Tools/ImageEditor
    linked by target "FontEditor" in directory G:/mygui/buildtrees/mygui/src/MyGUI3.4.2-2a0c5de7a4.clean/Tools/FontEditor
SDL2_LIBRARY (ADVANCED)
    linked by target "EditorFramework" in directory G:/mygui/buildtrees/mygui/src/MyGUI3.4.2-2a0c5de7a4.clean/Tools/EditorFramework
    linked by target "LayoutEditor" in directory G:/mygui/buildtrees/mygui/src/MyGUI3.4.2-2a0c5de7a4.clean/Tools/LayoutEditor
    linked by target "SkinEditor" in directory G:/mygui/buildtrees/mygui/src/MyGUI3.4.2-2a0c5de7a4.clean/Tools/SkinEditor
    linked by target "ImageEditor" in directory G:/mygui/buildtrees/mygui/src/MyGUI3.4.2-2a0c5de7a4.clean/Tools/ImageEditor
    linked by target "FontEditor" in directory G:/mygui/buildtrees/mygui/src/MyGUI3.4.2-2a0c5de7a4.clean/Tools/FontEditor

-- Generating done (0.2s)
CMake Warning:
  Manually-specified variables were not used by the project:

    FETCHCONTENT_FULLY_DISCONNECTED
    _VCPKG_ROOT_DIR


CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by Pospelove** [comment]
@MonicaLiu0311 fixed

**Comment by MonicaLiu0311** [comment]
All features are tested successfully in the following triplet:
```
x86-windows
x64-windows
x64-windows-static
```

**Review by MonicaLiu0311 — APPROVED** [review]

**Pull request merged**
