### PR TITLE
[rocksdb] update to v6.11.4

### PR DESCRIPTION
**Pull request by kobykahane**
Update the rocksdb port to v6.11.4
- Update patches to apply to the latest CMakeLists.txt.
- Use `ROCKSDB_BUILD_SHARED` which is now available in rocksdb's CMakeLists.txt, instead of a custom variable.
- Disable `WITH_BENCHMARK_TOOLS` so only the library is built, similarly to how `WITH_TESTS` is disabled.
- Remove `debug/share` as required by the post checks.

### CODE REVIEW

**Comment by LilyWangL** [comment]
Thanks for your PR. Now `rocksdb` build failed with the following error:
```
D:\buildtrees\rocksdb\src\v6.11.4-b24dbdbd17.clean\util\math.h(22): error C3861: '__popcnt64': identifier not found
D:\buildtrees\rocksdb\src\v6.11.4-b24dbdbd17.clean\table\multiget_context.h(241): note: see reference to function template instantiation 'int rocksdb::BitsSetToOne<uint64_t>(T)' being compiled
        with
        [
            T=uint64_t
        ]
```

**Comment by kobykahane** [comment]
> Thanks for your PR. Now `rocksdb` build failed with the following error:
> 
> ```
> D:\buildtrees\rocksdb\src\v6.11.4-b24dbdbd17.clean\util\math.h(22): error C3861: '__popcnt64': identifier not found
> D:\buildtrees\rocksdb\src\v6.11.4-b24dbdbd17.clean\table\multiget_context.h(241): note: see reference to function template instantiation 'int rocksdb::BitsSetToOne<uint64_t>(T)' being compiled
>         with
>         [
>             T=uint64_t
>         ]
> ```

Yes, this is an upstream regression with building with MSVC on non-x64 targets. I am working on an upstream PR to address this.

**Comment by kobykahane** [comment]
Upstream PR, that among other things, fixes the x86 build is at https://github.com/facebook/rocksdb/pull/7439.
After it is reviewed I'll extract the relevant parts and add them as patches against the current release tag to the port file and update this PR.

**Comment by kobykahane** [comment]
PR updated with a patch containing the portions of https://github.com/facebook/rocksdb/pull/7439 necessary for successful x86 and arm64 triplet builds.

**Comment by kobykahane** [comment]
@LilyWangL Any additional review comments?

**Review by LilyWangL — APPROVED** [review]

**Comment by dan-shaw** [comment]
Thanks!

**Pull request merged**
