### PR TITLE
[volk] Remove the volk port

### PR DESCRIPTION
**Pull request by jeweg**
After [discussing with the volk author](https://github.com/zeux/volk/pull/30) we decided that building volk separately can currently not be supported due to the implementation file depending on various preprocessor defines that the user project must set. Making those CMake options in volk and features in vcpkg doesn't seem a good fit for this library because it's mostly auto-generated code and that part would have to be maintained manually. The CMake-package-config support in volk was therefore removed.
For the same reason the vcpkg port I added recently should be removed as well -- if actually used, the aforementioned defines likely have the wrong values (...and the vulkan platform-specific extensions will be unavailable in volk).

### CODE REVIEW

**Comment by cenit** [comment]
Curious to see how this will be managed. Currently vcpkg is not ready for the fully removal of a package, but eventually it would have happened such a situation

**Comment by jweg** [comment]
Well, it makes sense that that would be a tricky situation. But hang on, we may still be able to avoid this mess altogether. It might make a lot of sense to put the lib into vcpkg (and CMake package config) in header-only style, but that's a bit of a change in philosophy upstream, I'm still discussing that with the library author.

**Comment by Rastaban** [comment]
typically we don't remove ports from vcpkg because we don't want to break users.  If we can show that no one is using this port then we would probably make an exception.  If someone is using it then we would probably keep the port but deprecate it so it will warn users that it may not be supported in the future and discourage new users.  For now I will wait to hear the result of your discussion with the author.

**Comment by jweg** [comment]
It took a while, but good news! I gave the library config-file package support and an optional header-only usage mode upstream. This means the volk port now makes total sense, after a small update. I will shortly submit that update as its own PR and close this one.

**Pull request closed without merging**
