### PR TITLE
[bootstrap-vcpkg.sh] Fixes a build error due to missing log linkage

### PR DESCRIPTION
**Pull request by davemackintosh**
**Describe the pull request**

- #### What does your PR fix?  
  Fixes building in termux failing due to missing log library.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
 `N/A`

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  `N/A`

### CODE REVIEW

**Comment by davemackintosh** [comment]
CLA signed

**Comment by BillyONeal** [comment]
What function are we calling here that's creating the issue?

**Comment by davemackintosh** [comment]
This is a specific issue when building in an Android Termux environment. The error occurs when calling `./bootstrap-vcpkg.sh`

**Comment by dg0yt** [comment]
Maybe it is enough to set `LDFLAGS`? I

**Comment by davemackintosh** [comment]
I'd be happy to switch to LDFLAGS but I just used the code style that was there.

**Comment by JackBoosY** [comment]
Can you please provide the error output without this changes?

**Comment by davemackintosh** [comment]
```
2  1  [tmux] *                   2022-01-04  12:34  localhost p.o CMakeFiles/vcpkglib.dir/src/vcpkg/statusparagraphs.cpp.o CM[0/128]s/vcpkglib.dir/src/vcpkg/tools.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/triplet.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/update.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/userconfig.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/vcpkgcmdarguments.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/vcpkglib.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/vcpkgpaths.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/versiondeserializers.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/versions.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/versiont.cpp.o CMakeFiles/vcpkglib.dir/src/vcpkg/visualstudio.cpp.o CMakeFiles/vcpkg-test.dir/src/vcpkg-test/arguments.cpp.o CMakeFiles/vcpkg-test.dir/src/vcpkg-test/binarycaching.cpp.o CMakeFiles/vcpkg-test.dir/src
/vcpkg-test/catch.cpp.o CMakeFiles/vcpkg-test.dir/src/vcpkg-test/chron
o.cpp.o CMakeFiles/vcpkg-test.dir/src/vcpkg-test/commands.cpp.o CMakeF
iles/vcpkg-test.dir/src/vcpkg-test/configmetadata.cpp.o CMakeFiles/vcp
kg-test.dir/src/vcpkg-test/configparser.cpp.o CMakeFiles/vcpkg-test.dir/src/vcpkg-test/dependencies.cpp.o CMakeFiles/vcpkg-test.dir/src/vcpkg-test/downloads.cpp.o CMakeFiles/vcpkg-test.dir/src/vcpkg-test/files.cpp.o CMakeFiles/vcpkg-test.dir/src/vcpkg-test/hash.cpp.o CMakeFiles/vcpkg-test.dir/src/vcpkg-test/json.cpp.o CMakeFiles/vcpkg-test.dir/src/vcpkg-test/manifests.cpp.o CMakeFiles/vcpkg-test.dir/src/vcpkg-test/mockcmakevarsprovider.cpp.o CMakeFiles/vcpkg-test.dir/src/vcpkg-test/optional.cpp.o CMakeFiles/vcpkg-test.dir/src/vcpkg-test/paragraph.cpp.o CMakeFiles/vcpkg-test.dir/src/vcpkg-test/plan.cpp.o CMakeFiles/vcpkg-test.dir/src/vcpkg-test/platform-expression.cpp.o CMakeFiles/vcpkg-test.dir/src/vcpkg-test/registries.cpp.o CMakeFiles/vcpkg-test.dir/src/vcpkg-test/specifier.cpp.o CMakeFiles/vcpkg-test.dir/src/vcpkg-test/statusparagraphs.cpp.o CMakeFiles/vcpkg-test.dir/src/vcpkg-test/strings.cpp.o CMakeFiles/vcpkg-test.dir/src/vcpkg-test/stringview.cpp.o CMakeFiles/vcpkg-test.dir/src/vcpkg-test/system.cpp.o CMakeFiles/vcpkg-test.dir/src/vcpkg-test/uint128.cpp.o CMakeFiles/vcpkg-test.dir/src/vcpkg-test/
update.cpp.o CMakeFiles/vcpkg-test.dir/src/vcpkg-test/util.cpp.o CMake
Files/vcpkg-test.dir/src/vcpkg-test/versionplan.cpp.o -o vcpkg-test  _
deps/fmt-build/libfmt.a  -pthread && :
ld.lld: error: undefined symbol: __android_log_write
>>> referenced by catch.cpp
>>>               CMakeFiles/vcpkg-test.dir/src/vcpkg-test/catch.cpp.o
:(Catch::writeToDebugConsole(std::__ndk1::basic_string<char, std::__nd
k1::char_traits<char>, std::__ndk1::allocator<char> > const&))
>>> referenced by catch.cpp
>>>               CMakeFiles/vcpkg-test.dir/src/vcpkg-test/catch.cpp.o
:(Catch::Detail::(anonymous namespace)::StreamBufImpl<Catch::Detail::(
anonymous namespace)::OutputDebugWriter, 256ul>::sync())
>>> referenced by catch.cpp
>>>               CMakeFiles/vcpkg-test.dir/src/vcpkg-test/catch.cpp.o
:(Catch::Detail::(anonymous namespace)::StreamBufImpl<Catch::Detail::(
anonymous namespace)::OutputDebugWriter, 256ul>::overflow(int))
clang-13: error: linker command failed with exit code 1 (use -v to see
 invocation)
ninja: build stopped: subcommand failed.
```

**Review by JackBoosY — APPROVED** [review]

**Review by dg0yt — CHANGES_REQUESTED** [review]
This isn't a bootstrap issue, but a vcpkg-tool build issue. If you really want to fix the build for Android or Termux, you must do in the CMake build system of https://github.com/microsoft/vcpkg-tool, not here.

**Comment by BillyONeal** [comment]
Why are you trying to build vcpkg to run *on* android? Building packages for android makes sense...

**Comment by davemackintosh** [comment]
I build my apps both on my computer and on my phone and recently moved from downloading assets to vcpkg. Termux fully supports a modern c++ workflow end to end so I like to build apks on my device. Does that change the validness of the PR though? 

I'm happy to move this check to the right context/repo though.

**Comment by strega-nil-ms** [comment]
Okay, this is specifically an issue with our tests; the correct way to do this (and to make the build faster for everyone) is to just disable tests.

```diff
diff --git a/scripts/bootstrap.sh b/scripts/bootstrap.sh
index 846f297b6..f607e8ba8 100644
--- a/scripts/bootstrap.sh
+++ b/scripts/bootstrap.sh
@@ -230,10 +230,10 @@ else
     rm -rf "$baseBuildDir"
     mkdir -p "$buildDir"
     vcpkgExtractTar "$tarballPath" "$srcBaseDir"
-    cmakeConfigOptions="-DCMAKE_BUILD_TYPE=Release -G 'Ninja' -DVCPKG_DEVELOPMENT_WARNINGS=OFF"
+    cmakeConfigOptions="-DCMAKE_BUILD_TYPE=Release -G 'Ninja' -DVCPKG_DEVELOPMENT_WARNINGS=OFF -DBUILD_TESTING:BOOL=OFF"
 
     if [ "${VCPKG_MAX_CONCURRENCY}" != "" ] ; then
-        cmakeConfigOptions=" $cmakeConfigOptions '-DCMAKE_JOB_POOL_COMPILE:STRING=compile' '-DCMAKE_JOB_POOL_LINK:STRING=link' '-DCMAKE_JOB_POOLS:STRING=compile=$VCPKG_MAX_CONCURRENCY;link=$VCPKG_MAX_CONCURRENCY' "
+        cmakeConfigOptions="$cmakeConfigOptions '-DCMAKE_JOB_POOL_COMPILE:STRING=compile' '-DCMAKE_JOB_POOL_LINK:STRING=link' '-DCMAKE_JOB_POOLS:STRING=compile=$VCPKG_MAX_CONCURRENCY;link=$VCPKG_MAX_CONCURRENCY'"
     fi
 
     (cd "$buildDir" && CXX="$CXX" eval cmake "$srcDir" $cmakeConfigOptions) || exit 1

```

**Comment by BillyONeal** [comment]
>Does that change the validness of the PR though?

It looked like a misunderstanding of what vcpkg does so I wanted confirmation. The bigger issue is that moving forward now that we have binary releases we're likely to add dependencies to vcpkg that will make bootstrapping like this progressively more painful so that we get out of the business of implementing the world over again but badly, if that makes sense.

I agree with Nicole's feedback though

**Comment by strega-nil-ms** [comment]
@davemackintosh could you tell me if the changes fix your problem?

**Comment by Cheney-W** [comment]
Pinging @davemackintosh  for response. Is work still being done for this PR?

**Comment by davemackintosh** [comment]
Sorry, I totally forgot about this but I have also since moved away from Android and this Termux. Feel free to either merge or close this PR.

**Pull request closed without merging**
