### PR TITLE
[dbow3] Switch from unofficial repo to large patchset

### PR DESCRIPTION
**Pull request by RamadanAhmed**
Fix #8547 portfile by using original repo and add .patch file with needed changes

### CODE REVIEW

**Comment by dan-shaw** [comment]
Thanks for the PR! Usually, we want to make the patch file as minimal as possible and additional feature work should be submitted to the original repository.

See https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#minimize-patches

**Comment by cenit** [comment]
The portfile has already been accepted using his own personal repository which is even worse imho. At least having the patchset external, while very big, is better than the current situation.

**Comment by vicroms** [comment]
The last merged PR to `dbow3` is from March, and the author seems to have moved all of their effort to maintain `fbow`. But I'm OK with taking the patch file in the hope that the PR gets merged some day.

**Pull request merged**
