### PR TITLE
[vcpkg baseline][vcpkg_configure_make] Fix arm64-windows, arm-uwp

### LINKED ISSUE #15737: [gettext:arm64-windows] build failure (and possibly other ports), culprit: af3c99b
**Host Environment**
- OS: Windows 10, x64
- Compiler: MSVC 2019 (latest)

**To Reproduce**
`./vcpkg install gettext:arm64-windows`

**Failure logs** 
```
-- Building arm64-windows-dbg
CMake Error at scripts/cmake/vcpkg_build_make.cmake:205 (message):
  libtool could not find a file being linked against!
Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_make.cmake:26 (vcpkg_build_make)
  ports/gettext/portfile.cmake:59 (vcpkg_install_make)
  scripts/ports.cmake:137 (include)
```
```
[...]
libtool: compile:  compile cl.exe -DHAVE_CONFIG_H -I. -I.././../src/0.21-73e9069d8f.clean/gettext-runtime/intl -I.. -DLOCALEDIR=\"/C/Users/pastdue/src/vcpkg/installed/arm64-windows/debug/share/gettext/locale\" -DLOCALE_ALIAS_PATH=\"\" -DLIBDIR=\"/C/Users/pastdue/src/vcpkg/installed/arm64-windows/debug/lib\" -DBUILDING_LIBINTL -DBUILDING_DLL -DIN_LIBINTL -D__USE_MINGW_ANSI_STDIO=0 -DENABLE_RELOCATABLE=1 -DIN_LIBRARY -DINSTALLDIR=\"/C/Users/pastdue/src/vcpkg/installed/arm64-windows/debug/lib\" -DNO_XMALLOC -Dset_relocation_prefix=libintl_set_relocation_prefix -Drelocate=libintl_relocate -Drelocate2=libintl_relocate2 -DDEPENDS_ON_LIBICONV=1 -DWIN32 -D_WINDOWS -D_DEBUG -nologo -W3 -utf-8 -MP -MDd -Z7 -Ob0 -RTC1 -Od -c .././../src/0.21-73e9069d8f.clean/gettext-runtime/intl/localename-table.c  -DDLL_EXPORT -DPIC -o .libs/localename-table.obj
localename-table.c
Makefile:1643: update target 'libintl.la' due to: bindtextdom.lo dcgettext.lo dgettext.lo gettext.lo finddomain.lo hash-string.lo loadmsgcat.lo localealias.lo textdomain.lo l10nflist.lo explodename.lo dcigettext.lo dcngettext.lo dngettext.lo ngettext.lo plural.lo plural-exp.lo localcharset.lo threadlib.lo lock.lo relocatable.lo langprefs.lo localename.lo localename-table.lo log.lo printf.lo setlocale.lo setlocale-lock.lo setlocale_null.lo version.lo xsize.lo osdep.lo intl-compat.lo windows-mutex.lo windows-rwlock.lo windows-recmutex.lo windows-once.lo libintl.res.lo
/bin/sh ../libtool  --tag=CC   --mode=link compile cl.exe  -nologo -W3 -utf-8 -MP -MDd -Z7 -Ob0 -Od -Xcompiler -RTC1 -Wl,--export-all-symbols -liconv  -ladvapi32 -no-undefined -export-symbols-regex '^([^g]|g[^l]|gl[^w]|glw[^t]|glwt[^h]|glwth[^r]|glwthr[^e]|glwthre[^a]|glwthrea[^d]).*' -version-info 10:0:2 -rpath /C/Users/pastdue/src/vcpkg/installed/arm64-windows/debug/lib -LC:/Users/pastdue/src/vcpkg/installed/arm64-windows/debug/lib -LC:/Users/pastdue/src/vcpkg/installed/arm64-windows/debug/lib/manual-link -Wl,--disable-auto-import -o libintl.la  bindtextdom.lo dcgettext.lo dgettext.lo gettext.lo finddomain.lo hash-string.lo loadmsgcat.lo localealias.lo textdomain.lo l10nflist.lo explodename.lo dcigettext.lo dcngettext.lo dngettext.lo ngettext.lo plural.lo plural-exp.lo localcharset.lo threadlib.lo lock.lo relocatable.lo langprefs.lo localename.lo localename-table.lo log.lo printf.lo setlocale.lo setlocale-lock.lo setlocale_null.lo version.lo xsize.lo osdep.lo intl-compat.lo windows-mutex.lo windows-rwlock.lo windows-recmutex.lo windows-once.lo libintl.res.lo -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -lcomdlg32 -ladvapi32

*** Warning: linker path does not have real file for library -liconv.
*** I have the capability to make that library automatically link in when
*** you link to this library.  But I can only do this if you have a
*** shared version of the library, which you do not appear to have
*** because I did check the linker path looking for a file starting
*** with iconv and none of the candidates passed a file format test
*** using a file magic. Last file checked: /usr/bin/iconv.exe
*** The inter-library dependencies that have been dropped here will be
*** automatically added whenever a program is linked with this library
*** or is declared to -dlopen it.

*** Since this library must not contain undefined symbols,
*** because either the platform does not support them or
*** it was explicitly requested with -no-undefined,
*** libtool will only create a static version of it.
libtool: link: ar-lib lib.exe cru .libs/intl.lib .libs/bindtextdom.obj .libs/dcgettext.obj .libs/dgettext.obj .libs/gettext.obj .libs/finddomain.obj .libs/hash-string.obj .libs/loadmsgcat.obj .libs/localealias.obj .libs/textdomain.obj .libs/l10nflist.obj .libs/explodename.obj .libs/dcigettext.obj .libs/dcngettext.obj .libs/dngettext.obj .libs/ngettext.obj .libs/plural.obj .libs/plural-exp.obj .libs/localcharset.obj .libs/threadlib.obj .libs/lock.obj .libs/relocatable.obj .libs/langprefs.obj .libs/localename.obj .libs/localename-table.obj .libs/log.obj .libs/printf.obj .libs/setlocale.obj .libs/setlocale-lock.obj .libs/setlocale_null.obj .libs/version.obj .libs/xsize.obj .libs/osdep.obj .libs/intl-compat.obj .libs/windows-mutex.obj .libs/windows-rwlock.obj .libs/windows-recmutex.obj .libs/windows-once.obj .libs/libintl.res.obj
libtool: link: : .libs/intl.lib
libtool: link: ( cd ".libs" && rm -f "libintl.la" && cp -pR "../libintl.la" "libintl.la" )
make[1]: Leaving directory '/cygdrive/c/Users/pastdue/src/vcpkg/buildtrees/gettext/arm64-windows-dbg/intl'
```

**Additional context**
A git bisect reveals that:
3ddaeb41800d263b5cffeef1c87b23bdc1f3b98f - works
af3c99bc65d46e77900ae4e826866f134dc903ae - breaks `gettext:arm64-windows` (and possibly other ports as well)

@Neumann-A

### PR DESCRIPTION
**Pull request by past-due**
**Describe the pull request**
Since https://github.com/microsoft/vcpkg/commit/af3c99bc65d46e77900ae4e826866f134dc903ae various ports have been failing on `arm64-windows`.

Investigation yielded the cause: `objdump` is failing to deal with arm64 arch libraries:
```
usr/bin/objdump: installed\arm64-windows\lib\iconv.lib(iconv-2.dll): unrecognised machine type (0xaa64) in Import Library Format archive
```

@Neumann-A Suggested that the best option, for now, is to add a workaround with a comment (reverting af3c99bc65d46e77900ae4e826866f134dc903ae would have its own issues) - so that's what this PR does.

- What does your PR fix? Fixes #15737

- Which triplets are supported/not supported? Have you updated the CI baseline?

`arm64` Windows triplet(s) are impacted.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

### CODE REVIEW

**Comment by JackBoosY** [comment]
cc @Neumann-A

**Comment by JackBoosY** [comment]
Seems this PR doesn't fix the arm regression:
```
/cygdrive/c/a/1/s/scripts/buildsystems/make_wrapper/windres-rc: line 62: RCFLAGS: command not found
```

**Comment by past-due** [comment]
> Seems this PR doesn't fix the arm regression

Correct - it just fixes the `arm64-windows` regression. (I have not had a chance to investigate the `arm-uwp` triplet.)

**Comment by JackBoosY** [comment]
@Neumann-A What do you think about the arm regression?

**Comment by past-due** [comment]
The arm regression appears to be the same, but there is information that isn't contained in the logs (the exact output of running `objdump` on arm libraries) that I'd like to verify before implementing the same change for `arm` as well. I may have a chance to test this tomorrow.

**Comment by Neumann-A** [comment]
@JackBoosY Everything fine. This was discussed in the vcpkg discord.

**Comment by JackBoosY** [comment]
`spatialite-tools` regression will be resolved in #15746 or other PR, I hope this PR can solve arm and arm64 regression issues.

**Comment by past-due** [comment]
I can confirm on `arm-uwp` that `objdump` yields a similar issue:
```
vcpkg\installed\arm-uwp\lib\iconv.lib(iconv-2.dll): unrecognised machine type (0x1c4) in Import Library Format archive
```
(same error message with a different machine type)

@JackBoosY: I've implemented the same fix for arm on Windows.

**Comment by Neumann-A** [comment]
@past-due Do you have by any chance llvm-objdump installed? Would like to know if it has the same problems.

**Comment by past-due** [comment]
> @past-due Do you have by any chance llvm-objdump installed? Would like to know if it has the same problems.

Just installed it (through Visual Studio's LLVM / Clang package).

<details><summary>Results for arm .lib</summary>
<p>

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community>llvm-objdump -f C:\Users\pastdue\src\vcpkg\installed\arm-uwp\lib\iconv.lib

C:\Users\pastdue\src\vcpkg\installed\arm-uwp\lib\iconv.lib(iconv-2.dll):        file format COFF-ARM

architecture: thumb
start address: 0x00000000


C:\Users\pastdue\src\vcpkg\installed\arm-uwp\lib\iconv.lib(iconv-2.dll):        file format COFF-ARM

architecture: thumb
start address: 0x00000000


C:\Users\pastdue\src\vcpkg\installed\arm-uwp\lib\iconv.lib(iconv-2.dll):        file format COFF-ARM

architecture: thumb
start address: 0x00000000


C:\Users\pastdue\src\vcpkg\installed\arm-uwp\lib\iconv.lib(iconv-2.dll):        file format COFF-import-file


C:\Users\pastdue\src\vcpkg\installed\arm-uwp\lib\iconv.lib(iconv-2.dll):        file format COFF-import-file


C:\Users\pastdue\src\vcpkg\installed\arm-uwp\lib\iconv.lib(iconv-2.dll):        file format COFF-import-file


C:\Users\pastdue\src\vcpkg\installed\arm-uwp\lib\iconv.lib(iconv-2.dll):        file format COFF-import-file


C:\Users\pastdue\src\vcpkg\installed\arm-uwp\lib\iconv.lib(iconv-2.dll):        file format COFF-import-file


C:\Users\pastdue\src\vcpkg\installed\arm-uwp\lib\iconv.lib(iconv-2.dll):        file format COFF-import-file


C:\Users\pastdue\src\vcpkg\installed\arm-uwp\lib\iconv.lib(iconv-2.dll):        file format COFF-import-file


C:\Users\pastdue\src\vcpkg\installed\arm-uwp\lib\iconv.lib(iconv-2.dll):        file format COFF-import-file


C:\Users\pastdue\src\vcpkg\installed\arm-uwp\lib\iconv.lib(iconv-2.dll):        file format COFF-import-file


C:\Users\pastdue\src\vcpkg\installed\arm-uwp\lib\iconv.lib(iconv-2.dll):        file format COFF-import-file


C:\Users\pastdue\src\vcpkg\installed\arm-uwp\lib\iconv.lib(iconv-2.dll):        file format COFF-import-file


C:\Users\pastdue\src\vcpkg\installed\arm-uwp\lib\iconv.lib(iconv-2.dll):        file format COFF-import-file


C:\Users\pastdue\src\vcpkg\installed\arm-uwp\lib\iconv.lib(iconv-2.dll):        file format COFF-import-file


C:\Users\pastdue\src\vcpkg\installed\arm-uwp\lib\iconv.lib(iconv-2.dll):        file format COFF-import-file


C:\Users\pastdue\src\vcpkg\installed\arm-uwp\lib\iconv.lib(iconv-2.dll):        file format COFF-import-file
```
</p>
</details>

<details><summary>Results for arm64 .lib:</summary>
<p>

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community>llvm-objdump -f C:\Users\pastdue\src\vcpkg\installed\arm64-windows\lib\iconv.lib

C:\Users\pastdue\src\vcpkg\installed\arm64-windows\lib\iconv.lib(iconv-2.dll):  file format COFF-ARM64

architecture: aarch64
start address: 0x0000000000000000


C:\Users\pastdue\src\vcpkg\installed\arm64-windows\lib\iconv.lib(iconv-2.dll):  file format COFF-ARM64

architecture: aarch64
start address: 0x0000000000000000


C:\Users\pastdue\src\vcpkg\installed\arm64-windows\lib\iconv.lib(iconv-2.dll):  file format COFF-ARM64

architecture: aarch64
start address: 0x0000000000000000


C:\Users\pastdue\src\vcpkg\installed\arm64-windows\lib\iconv.lib(iconv-2.dll):  file format COFF-import-file


C:\Users\pastdue\src\vcpkg\installed\arm64-windows\lib\iconv.lib(iconv-2.dll):  file format COFF-import-file


C:\Users\pastdue\src\vcpkg\installed\arm64-windows\lib\iconv.lib(iconv-2.dll):  file format COFF-import-file


C:\Users\pastdue\src\vcpkg\installed\arm64-windows\lib\iconv.lib(iconv-2.dll):  file format COFF-import-file


C:\Users\pastdue\src\vcpkg\installed\arm64-windows\lib\iconv.lib(iconv-2.dll):  file format COFF-import-file


C:\Users\pastdue\src\vcpkg\installed\arm64-windows\lib\iconv.lib(iconv-2.dll):  file format COFF-import-file


C:\Users\pastdue\src\vcpkg\installed\arm64-windows\lib\iconv.lib(iconv-2.dll):  file format COFF-import-file


C:\Users\pastdue\src\vcpkg\installed\arm64-windows\lib\iconv.lib(iconv-2.dll):  file format COFF-import-file


C:\Users\pastdue\src\vcpkg\installed\arm64-windows\lib\iconv.lib(iconv-2.dll):  file format COFF-import-file


C:\Users\pastdue\src\vcpkg\installed\arm64-windows\lib\iconv.lib(iconv-2.dll):  file format COFF-import-file


C:\Users\pastdue\src\vcpkg\installed\arm64-windows\lib\iconv.lib(iconv-2.dll):  file format COFF-import-file


C:\Users\pastdue\src\vcpkg\installed\arm64-windows\lib\iconv.lib(iconv-2.dll):  file format COFF-import-file


C:\Users\pastdue\src\vcpkg\installed\arm64-windows\lib\iconv.lib(iconv-2.dll):  file format COFF-import-file


C:\Users\pastdue\src\vcpkg\installed\arm64-windows\lib\iconv.lib(iconv-2.dll):  file format COFF-import-file


C:\Users\pastdue\src\vcpkg\installed\arm64-windows\lib\iconv.lib(iconv-2.dll):  file format COFF-import-file
```
</p>
</details>

Also tested `DUMPBIN.EXE`:

<details><summary>Results for arm .lib:</summary>
<p>

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community>dumpbin.exe /NOLOGO /HEADERS C:\Users\pastdue\src\vcpkg\installed\arm-uwp\lib\iconv.lib

Dump of file C:\Users\pastdue\src\vcpkg\installed\arm-uwp\lib\iconv.lib

File Type: LIBRARY

FILE HEADER VALUES
             1C4 machine (ARM)
               3 number of sections
        CAC54605 time date stamp
             10B file pointer to symbol table
               8 number of symbols
               0 size of optional header
             100 characteristics
                   32 bit word machine

SECTION HEADER #1
[... removed many, many lines ...]
```
</p></details>

<details><summary>Results for arm64 .lib:</summary>
<p>

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community>dumpbin.exe /NOLOGO /HEADERS C:\Users\pastdue\src\vcpkg\installed\arm64-windows\lib\iconv.lib

Dump of file C:\Users\pastdue\src\vcpkg\installed\arm64-windows\lib\iconv.lib

File Type: LIBRARY

FILE HEADER VALUES
            AA64 machine (ARM64)
               3 number of sections
        C5E1F4A1 time date stamp
             10B file pointer to symbol table
               8 number of symbols
               0 size of optional header
               0 characteristics

SECTION HEADER #1
[... removed many, many lines ...]
```
</p></details>

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
LGTM.

**Review by BillyONeal — APPROVED** [review]

**Comment by ras0219-msft** [comment]
Thanks for the discussions and fix!

**Pull request merged**
