### PR TITLE
[vcpkg] Create triplet to build with the static runtime a shared library

### PR DESCRIPTION
**Pull request by illera88**
Use MT flag to use build a shared library.

- What does your PR fix?
Right now there is no triplet to use the static runtime and at the same time building a shared library

### CODE REVIEW

**Comment by PhoebeHui** [comment]
@illera88, thanks for the PR. however, building a DLL that static links the CRT will have a separate copy of the CRT for every DLL library built this way – this causes serious size, correctness, and general surprise problems. That's why we don't have a triplet for this case.

You can reference from https://docs.microsoft.com/en-us/cpp/c-runtime-library/crt-library-features?view=vs-2019

**Comment by illera88** [comment]
It will only have one copy of the CRT if you build all the dependents DLLs with the same CRT version. And since vcpkg is a tool to ease the building process all of them will be built with whatever CRT version you have.

**Comment by BillyONeal** [comment]
>It will only have one copy of the CRT if you build all the dependents DLLs with the same CRT version.

That is incorrect. Statically linking the CRT gives each DLL independent copies of the CRT, so you can't, for example, concurrently modify a std::vector shared by pointer between the DLLs.

**Comment by PhoebeHui** [comment]
I will close this PR now, feel free reopen it if you still have a question about this PR.

**Pull request closed without merging**
