### PR TITLE
[wxWidgets] Fix issue introduced in 9b654a1f2174edaf63ef6af2c2d7e1ccd3cba83a

### LINKED ISSUE #22521: [wxwidgets] wxwidgets[core]:x64-windows -> 3.1.5#6 broken after latest changes
**Describe the bug**
Install is broken after upgrade to wxwidgets[core]:x64-windows -> 3.1.5#6

**Environment**
- OS: Win10
- Compiler: Visual Studio 2019

**To Reproduce**

```
C:\src\vcpkg>vcpkg install wxwidgets:x64-windows
Computing installation plan...
The following packages will be built and installed:
    wxwidgets[core]:x64-windows -> 3.1.5#6
Detecting compiler hash for triplet x64-windows...
-- Using HTTP(S)_PROXY in environment variables.
Restored 0 packages from C:\Users\jpo\AppData\Local\vcpkg\archives in 223.7 us. Use --debug to see more details.
Starting package 1/1: wxwidgets:x64-windows
Building package wxwidgets[core]:x64-windows...
-- Using cached wxWidgets-wxWidgets-9c0a8be1dc32063d91ed1901fd5fcd54f4f955a1.tar.gz.
-- Extracting source C:/src/vcpkg/downloads/wxWidgets-wxWidgets-9c0a8be1dc32063d91ed1901fd5fcd54f4f955a1.tar.gz
-- Applying patch disable-platform-lib-dir.patch
-- Applying patch fix-build.patch
-- Using source at C:/src/vcpkg/buildtrees/wxwidgets/src/54f4f955a1-0d7c66a59e.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: C:/src/vcpkg/packages/wxwidgets_x64-windows/share/wxwidgets/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\jpo\AppData\Local\vcpkg\archives\9a\9a8c3a297ad07d9e7d03b00cbbe2fa0541d0d9faf23340281c868c26168237a4.zip
Installing package wxwidgets[core]:x64-windows...
Elapsed time for package wxwidgets:x64-windows: 7.241 min

Total elapsed time: 7.304 min

The package wxwidgets provides CMake integration:

    find_package(wxWidgets REQUIRED)
    target_include_directories(main PRIVATE ${wxWidgets_INCLUDE_DIRS})
    target_link_libraries(main PRIVATE ${wxWidgets_LIBRARIES})
```

**Expected behavior**
wxWidgets can be used

**Failure logs** 
`2>C:\src\vcpkg\installed\x64-windows\include\wx\setup.h(2,10): fatal error C1083: Cannot open include file: '../../debug/lib//setup.h': No such file or directory
`
**Additional context**
Used to work with previous version

### PR DESCRIPTION
**Pull request by AenBleidd**
Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

### CODE REVIEW

**Comment by jpo234** [comment]
Fix doesn't work. See https://github.com/microsoft/vcpkg/issues/22521#issuecomment-1012141023

**Comment by jpo234** [comment]
@AenBleidd Looks good now.

**Comment by AenBleidd** [comment]
@jpo234, thank you for testing 👍

**Review by LilyWangLL — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for your fix!

**Pull request merged**
