### PR TITLE
[binarycaching.md] Add experimental binarycaching source strings missing from docs

### PR DESCRIPTION
**Pull request by samwarring**
In my own research into the binary caching feature, I found the existing documentation was incomplete. The source strings `x-gcs`, `x-aws`, `x-aws-config`, and `x-cos` were not listed in the table of valid source strings, even though they are supported by the `vcpkg` tool. This completes the table with the same descriptions given by `vcpkg help binarycaching` (EDIT: The `http` source string was missing too)

**Describe the pull request**

- #### What does your PR fix?
  N/A - I did not find a relevant issue for this.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  N/A - This change does not affect any ports, only documentation.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes, to the best of my knowledge.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  I did not update a port.

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Review by LilyWangLL — APPROVED** [review]

**Comment by samwarring** [comment]
Thanks for the review!

**Comment by BillyONeal** [comment]
/cc @AugP @ras0219-msft

@samwarring it may take a bit longer than normal to get this landed because our docs 'v-team' is half missing for a while :). Don't take it as disliking the change, it's just holidays.

Thanks for your contribution :)

**Comment by cnSchwarzer** [comment]
Hey, searching around and find this. How about close this PR?

**Comment by samwarring** [comment]
Thanks for the [shout-out](https://devblogs.microsoft.com/cppblog/vcpkg-2023-01-09-release-registry-pattern-matching-documentation-changes-and-more/)! I do have a couple follow-up questions.
1. I noticed the docs [linked](https://learn.microsoft.com/en-us/vcpkg/users/binarycaching) from the blog post don't yet include the changes, even though [vcpkg-docs #22](https://github.com/microsoft/vcpkg-docs/pull/22) was merged a month ago. When exactly do those changes take effect?
2. In the future, should documentation issues/PRs be created under the vcpkg-docs repo?
3. Should I close this PR, since it's already merged elsewhere?

Thanks again!

**Comment by cnSchwarzer** [comment]
Yes, I have the same question about vcpkg documentation. It seems totally messed up. #29019

**Comment by BillyONeal** [comment]
As @autoantwort points out, it looks like these changes are live. Thanks for your contribution to vcpkg!

**Pull request closed without merging**
