### PR TITLE
[cppmicroservices] Fix deps, configuration, fixup

### PR DESCRIPTION
**Pull request by dg0yt**
For https://github.com/microsoft/vcpkg/pull/33825#issuecomment-1767671046.

### CODE REVIEW

**Comment by dg0yt** [comment]
@Hardold Please test these changes.

Notet that the port has vendored dependencies. They should be removed in additional commits.

**Comment by GitJQ** [comment]
any update ?

**Comment by dg0yt** [comment]
@GitJQ Did you test it?

**Comment by dg0yt** [comment]
... and from my comments, there are still the vendored dependencies. This takes time.

**Comment by dg0yt** [comment]
Resolved by #42720.

**Pull request closed without merging**
