### PR TITLE
[gdal] Update port to latest GDAL 2.2.2

### PR DESCRIPTION
**Pull request by mloskot**
* Bump GDAL version wherever necessary
* Update download package and checksum.
* Remove `0001-Add-support-for-MSVC1900-backported-from-GDAL2.patch`
  no longer necessary.
* Recalculate `000N` prefix in patch filenames after the removal.
* Update `0002-Ensures-inclusion-of-PDB-in-release-dll-if-so-reques.patch`
  * Patch pushed upstream https://trac.osgeo.org/gdal/ticket/7055
    and should no longer be necessary in GDAL 2.2.3 or later
* Update `0003-Fix-openjpeg-include.patch`

---

Updated port successfully tested locally:
```
vcpkg install gdal:x86-windows
vcpkg install gdal:x64-windows
```

### CODE REVIEW

**Comment by alex85k** [comment]
Now freexl and spatialite drivers can also be added.

**Comment by ShinNoNoir** [comment]
GDAL 2.x does introduce some breaking changes, if I recall correctly, and thus projects relying on GDAL 1.x would most likely break.

Any idea how we should deal with these changes? Perhaps have two different ports, one for GDAL 1.x and one for GDAL 2.x?

**Comment by ShinNoNoir** [comment]
In my search to find some details on the differences between 1.x and 2.x, I stumbled upon this website: 

[Binary compatibility report for the libgdal.so object between 1.11.5 and 2.0.0 versions on x86_64](https://abi-laboratory.pro/tracker/compat_report/gdal/1.11.5/2.0.0/17f8d/abi_compat_report.html) 

Apparently 206 symbols have been removed in the transition from 1.x to 2.x.

**Comment by mloskot** [comment]
GDAL 1.11.5 is 1.5 years old and I don't think any releases have been planned.
It is highly recommended to switch GDAL 2.x

If vcpkg does maintain single version of a port, then it should be GDAL 2.x

Those who rely on GDAL 1.x should fix their environments at snapshot with the desired version, as per:

* [pin older library versions](https://github.com/Microsoft/vcpkg/issues/25#issuecomment-248753718)
* [We take the stance that it is (in the general case) completely unreasonable for one library to request another to be held back](https://github.com/Microsoft/vcpkg/issues/1036)
* FAQ: [How do I use different versions of a library on one machine?](https://github.com/Microsoft/vcpkg/blob/master/docs/about/faq.md)

**Comment by ras0219-msft** [comment]
Thanks for the PR and supplying excellent policy guidance :)!

**Comment by lukern** [comment]
https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-config:x64-windows
  Vcpkg version: 2018.11.23-nohash

**Comment by Darker** [comment]
Is it possible to also have debug version built using this package? We're trying to find an error while using this library (heap corruption), but the error happens inside GDAL DLL. It may be either incorrect configuration or a bug in GDAL.

**Comment by mloskot** [comment]
@Darker yes, it should be possible, as for any vcpkg package. From the vcpkg FAQ:

> Vcpkg will only produce the standard "Release" and "Debug" configurations when building a library

**Pull request merged**
