### PR TITLE
[libigl] Remove broken features

### PR DESCRIPTION
**Pull request by dg0yt**
This PR was triggered by the pkgconf dependency missing the host property, but became more radical:
- Some recently added features build and need binary artifacts, but they don't install extra files in the end. How was this meant to work? If these features are desired, they must be added properly, maybe using separate ports for the dependencies. Comiso seems non-trivial.
  CC @iAnyKey This reverts the feature additions from #27963.
- The CMake config didn't actually load the exported targets or dependencies... I fixed the most obvious problems.
- For now, it is really enough to build only release (header-only port).
- I added a png feature.

--

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Review by JonLiu1993 — DISMISSED** [review]

**Comment by FabienPean** [comment]
Could you also add a usage file `find_path(LIBIGL_INCLUDE_DIR igl/AABB.h)` or add the missing `include("${CMAKE_CURRENT_LIST_DIR}/LibiglConfigTargets.cmake")` in `cmake/igl/libigl-config.cmake.in` to have the core target visible

This would completely fix #30621

**Comment by dg0yt** [comment]
> `include("${CMAKE_CURRENT_LIST_DIR}/LibiglConfigTargets.cmake")`

Good catch, this was meant to be part of the patch.

**Review by JonLiu1993 — APPROVED** [review]

**Comment by JonLiu1993** [comment]
All features are tested successfully in the following triplet:
- x86-windows
- x64-windows
- x64-windows-static

**Comment by BillyONeal** [comment]
Thank you for the fix @dg0yt!

**Pull request merged**
