### PR TITLE
[licensepp] Update to 2020-11-24

### PR DESCRIPTION
**Pull request by michaelmigliore**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by michaelmigliore** [comment]
Looks like the compilation fails on OSX.  
I took a look at the Azure logs but couldn't find any details regarding the failure.  
Let me know if I should add the exception in `ci.baseline.txt` or if I can find the compilation error somewhere.

**Comment by JonLiu1993** [comment]
@michaelmigliore, Thanks for your PR, this is detail error log:
````
FAILED: CMakeFiles/licensepp-lib.dir/src/json-object.cc.o 
/Library/Developer/CommandLineTools/usr/bin/c++ -DLICENSEPP_SOVERSION=\"1.0.6\" -DRIPE_VERSION=\"4.0.1-custom-static\" -I/Users/vagrant/Data/installed/x64-osx/include -I/Users/vagrant/Data/buildtrees/licensepp/x64-osx-dbg -I/Users/vagrant/Data/buildtrees/licensepp/src/612a3d3e3c-fee8106458.clean -fPIC -std=c++11 -O3 -Wall -Werror -g -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk -MD -MT CMakeFiles/licensepp-lib.dir/src/json-object.cc.o -MF CMakeFiles/licensepp-lib.dir/src/json-object.cc.o.d -o CMakeFiles/licensepp-lib.dir/src/json-object.cc.o -c /Users/vagrant/Data/buildtrees/licensepp/src/612a3d3e3c-fee8106458.clean/src/json-object.cc
In file included from /Users/vagrant/Data/buildtrees/licensepp/src/612a3d3e3c-fee8106458.clean/src/json-object.cc:11:
/Users/vagrant/Data/buildtrees/licensepp/src/612a3d3e3c-fee8106458.clean/src/json-object.h:86:16: error: returning address of local temporary object [-Werror,-Wreturn-stack-address]
        return getString(key, defaultValue).c_str();
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
````

**Comment by michaelmigliore** [comment]
Thank you @JonLiu1993  
I've patched it and opened a PR upstream: https://github.com/amrayn/licensepp/pull/40

**Comment by BillyONeal** [comment]
Thanks for the update and submitting the fix for the dead code upstream!

**Pull request merged**
