### PR TITLE
[cgal][openmvs] CGAL: Upgrade to 5.0

### PR DESCRIPTION
**Pull request by maxGimeno**
Upgrade the CGAL port to version 5.0-beta1

### CODE REVIEW

**Comment by lrineau** [comment]
This pull-request is for the moment a draft. Do not merge it until it is updated to 5.0 final version.

**Comment by lrineau** [comment]
@maxGimeno 

Could you add a `usage` file, like in the data port:
https://github.com/microsoft/vcpkg/blob/2aaf7fd8b3d7dce245c5ce2d41aa3fdb6f0f7438/ports/date/usage#L1-L4
https://github.com/microsoft/vcpkg/blob/2aaf7fd8b3d7dce245c5ce2d41aa3fdb6f0f7438/ports/date/portfile.cmake#L44-L45

That would avoid the false message displayed automatically by vcpkg:
```
The package cgal:x64-linux provides CMake targets:

    find_package(CGAL CONFIG REQUIRED)

    # Note: 1 target(s) were omitted.

    target_link_libraries(main PRIVATE ${cgal_lib} CGAL::${cgal_lib} CGAL_Qt5_moc_and_resources CGAL::Qt5_moc_and_resources)
```

**Review by JackBoosY — APPROVED** [review]

**Comment by lrineau** [comment]
I have pushed an upgrade to CGAL-5.0-beta2. That is still a `wip` PR.

**Comment by maxGimeno** [comment]
I have upgraded to 5.0. This PR should now be ready for integration.

**Comment by acgetchell** [comment]
This is a really important library for my project. I have tests for MacOS, Linux, and Windows if you want real-world examples to check: https://github.com/acgetchell/CDT-plusplus

**Comment by maxGimeno** [comment]
I don't understand the CI failures. It says it is probably caused by the missing log files for comparison baseline, but I don't know how to fix this :/

**Comment by JackBoosY** [comment]
@maxGimeno See #8949.

**Review by ras0219-msft — CHANGES_REQUESTED** [review]
This PR LGTM except that `openmvs` needs to have its control version incremented to include the new patch file.

**Comment by JackBoosY** [comment]
@maxGimeno Please modify _VCPKG_PATH/ports/openmvs/CONTROL_:
`Version: 1.0-2`
->
`Version: 1.0-3`

**Comment by JackBoosY** [comment]
@ras0219-msft I thinks this PR is ready to merge now.

**Review by ras0219-msft — APPROVED** [review]

**Comment by ras0219-msft** [comment]
Thanks for the PR!

**Comment by acgetchell** [comment]
Thank you, that was a smooth upgrade and the first simultaneous one for me on Windows, Linux, and macOS.

https://ci.appveyor.com/project/acgetchell/cdt-plusplus#L518

https://travis-ci.org/acgetchell/CDT-plusplus/jobs/615752586#L540

**Pull request merged**
