### PR TITLE
[dbus] Cleanup, fix pkgconfig for osx

### PR DESCRIPTION
**Pull request by dg0yt**
- #### What does your PR fix?
  Fixes -lLIBRT-NOTFOUND in pc files on osx. Discovered by #23898.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  no changes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  yes

@Neumann-A Should we add an x11 feature, or disable x11 for osx?

### CODE REVIEW

**Comment by dg0yt** [comment]
This port needs three dirs in `share`:
- `dbus` aka `${PORT}`
- `dbus1` for `session.conf`
- `DBus-1` for CMake config

**Comment by Neumann-A** [comment]
> @Neumann-A Should we add an x11 feature, or disable x11 for osx?

I don't have any feelings if it should be a feature for osx. If people could want it, make it a feature, otherwise disable it for osx.

**Comment by autoantwort** [comment]
I think you can disable x11 on osx. It is not really a thing on macos and only works if you install third party software that runs a x11 server.

**Comment by Neumann-A** [comment]
> only works if you install third party software that runs a x11 server

logically that means it is a feature.

**Comment by dg0yt** [comment]
The new question is if someone objects to `"supports": "!staticcrt"`, due to only building dynamic libs, effectively excluding `x64-windows-static`.

**Comment by dg0yt** [comment]
> > only works if you install third party software that runs a x11 server
> 
> logically that means it is a feature.

Would it be okay to make it opt-in for Linux, too?

**Comment by Neumann-A** [comment]
> Would it be okay to make it opt-in for Linux, too?

Probably:

```
if get_option('x11_autolaunch').disabled()
    use_x11_autolaunch = false
    x11 = not_found
else
    if get_option('x11_autolaunch').enabled() and platform_windows
        error('X11 autolaunch is not supported on Windows')
    endif

    x11 = dependency('x11', required: false)
    use_x11_autolaunch = x11.found()

    if get_option('x11_autolaunch').enabled() and not use_x11_autolaunch
        error('X11 autolaunch support requested but not found')
    endif
endif
config.set('DBUS_BUILD_X11', use_x11_autolaunch)
config.set('DBUS_ENABLE_X11_AUTOLAUNCH', use_x11_autolaunch)

```

but this looks like you could get away in ripping out the libx11 dep completely.

**Comment by Neumann-A** [comment]
Ok for the CMake part:
```
if(X11_FOUND)
    option(DBUS_BUILD_X11 "Build with X11 autolaunch support " ON)
endif()
```
maybe ask upstream if it is supported on windows. Seems like it diverged

**Comment by dg0yt** [comment]
Extra comments:
- AFAICS port `dbus` is currently not used by any other vcpkg port. However, there are ports with `dbus` features. There may be installation order problems in those ports.
- On Linux, the port may use (if present) system `libsystemd.so` which pulls in `liblzma.so.5`, `liblz4.so.1`, `libgcrypt.so.20` and `libgpg-error.so.0` (Ubuntu 18.04). I'm not sure how symbols are resolved when an app uses those libs from vcpkg and `dbus`.

**Review by FrankXie05 — APPROVED** [review]

**Comment by BillyONeal** [comment]
> * On Linux, the port may use (if present) system `libsystemd.so` which pulls in `liblzma.so.5`, `liblz4.so.1`, `libgcrypt.so.20` and `libgpg-error.so.0` (Ubuntu 18.04). I'm not sure how symbols are resolved when an app uses those libs from vcpkg and `dbus`.

I don't know if anyone knows :). That said, this PR is clearly an improvement on the status quo, thanks!

**Pull request merged**
