### PR TITLE
[z3] Update to v4.10.2

### PR DESCRIPTION
**Pull request by ekilmer**
**Describe the pull request**

Update to latest Z3 version.

- #### What does your PR fix?
  N/A

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

### CODE REVIEW

**Comment by ekilmer** [comment]
I'm not sure why Triton is failing only on Windows

**Comment by dg0yt** [comment]
> I'm not sure why Triton is failing only on Windows

Is there an `inline` keyword missing in this z3 header?

https://github.com/Z3Prover/z3/blob/87dd837b551fa8650ef1be10f0ee3c1f56e106b9/src/api/c%2B%2B/z3%2B%2B.h#L3417-L3422

**Comment by FrankXie05** [comment]
Log from `install-x86-windows-dbg-out.log` :
````
/MANIFESTFILE:src\libtriton\CMakeFiles\triton.dir/intermediate.manifest src\libtriton\CMakeFiles\triton.dir/manifest.res" failed (exit code 1169) with the following output:
callbacks.cpp.obj : error LNK2005: "public: __thiscall z3::constructor_list::constructor_list(class z3::constructors const &)" (??0constructor_list@z3@@QAE@ABVconstructors@1@@Z) already defined in api.cpp.obj
solverEngine.cpp.obj : error LNK2005: "public: __thiscall z3::constructor_list::constructor_list(class z3::constructors const &)" (??0constructor_list@z3@@QAE@ABVconstructors@1@@Z) already defined in api.cpp.obj
synthesizer.cpp.obj : error LNK2005: "public: __thiscall z3::constructor_list::constructor_list(class z3::constructors const &)" (??0constructor_list@z3@@QAE@ABVconstructors@1@@Z) already defined in api.cpp.obj
tritonToZ3.cpp.obj : error LNK2005: "public: __thiscall z3::constructor_list::constructor_list(class z3::constructors const &)" (??0constructor_list@z3@@QAE@ABVconstructors@1@@Z) already defined in api.cpp.obj
z3ToTriton.cpp.obj : error LNK2005: "public: __thiscall z3::constructor_list::constructor_list(class z3::constructors const &)" (??0constructor_list@z3@@QAE@ABVconstructors@1@@Z) already defined in api.cpp.obj
z3Solver.cpp.obj : error LNK2005: "public: __thiscall z3::constructor_list::constructor_list(class z3::constructors const &)" (??0constructor_list@z3@@QAE@ABVconstructors@1@@Z) already defined in api.cpp.obj
   Creating library src\libtriton\triton.lib and object src\libtriton\triton.exp
src\libtriton\triton.dll : fatal error LNK1169: one or more multiply defined symbols found
ninja: build stopped: subcommand failed.
````
And regarding the `error LNK2005`, this error can occur when a header file defines a variable. Using the keyword `inline` can circumvent this problem but cannot solve it completely.
See https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk2005?view=msvc-170

**Comment by ekilmer** [comment]
@FrankXie05 This is ready for review now. I've skipped 4.10.1 in favor of using 4.10.2, which fixes the issue we were seeing with Triton. All of CI now passes.

**Review by FrankXie05 — APPROVED** [review]

**Comment by JavierMatosD** [comment]
Thanks!

**Pull request merged**
