### PR TITLE
[proj] Update to proj 9.4.0

### PR DESCRIPTION
**Pull request by rhuijben**
- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [X] SHA512s are updated for each updated download.
- [X] The "supports" clause reflects platforms that may be fixed by this new version.
- [X] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [X] Any patches that are no longer applied are deleted from the port's directory.
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by MonicaLiu0311** [comment]
Please get [failure logs here](https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/100085/artifacts?artifactName=failure%20logs%20for%20x64-windows&api-version=7.1&%24format=zip).
```
CMake Warning (dev) at C:/a/1/s/scripts/buildsystems/vcpkg.cmake:859 (_find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

Call Stack (most recent call first):
  D:/installed/x64-windows/share/opencv/OpenCVConfig.cmake:86 (find_package)
  D:/installed/x64-windows/share/opencv/OpenCVConfig.cmake:108 (find_host_package)
  C:/a/1/s/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  CMakeLists.txt:232 (FIND_PACKAGE)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at C:/a/1/s/scripts/buildsystems/vcpkg.cmake:859 (_find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

Call Stack (most recent call first):
  D:/downloads/tools/cmake-3.27.1-windows/cmake-3.27.1-windows-i386/share/cmake-3.27/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)
  D:/installed/x64-windows/share/opencv/OpenCVModules.cmake:36 (find_dependency)
  D:/installed/x64-windows/share/opencv/OpenCVConfig.cmake:174 (include)
  C:/a/1/s/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  CMakeLists.txt:232 (FIND_PACKAGE)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at C:/a/1/s/scripts/buildsystems/vcpkg.cmake:859 (_find_package):
  Found package configuration file:

    D:/installed/x64-windows/share/proj/proj-config.cmake

  but it set PROJ_FOUND to FALSE so package "PROJ" is considered to be NOT
  FOUND.  Reason given by package:

  PROJ could not be found because dependency SQLite3 could not be found.

Call Stack (most recent call first):
  D:/installed/x64-windows/share/vtk/VTK-vtk-module-find-packages.cmake:820 (find_package)
  D:/installed/x64-windows/share/vtk/vtk-config.cmake:150 (include)
  C:/a/1/s/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  D:/downloads/tools/cmake-3.27.1-windows/cmake-3.27.1-windows-i386/share/cmake-3.27/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)
  D:/installed/x64-windows/share/opencv/OpenCVModules.cmake:43 (find_dependency)
  D:/installed/x64-windows/share/opencv/OpenCVConfig.cmake:174 (include)
  C:/a/1/s/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  CMakeLists.txt:232 (FIND_PACKAGE)
```

**Comment by rhuijben** [comment]
This likely not an easy fix as proj completely removed its custom finder of sqlite and now uses the system finder, yet this other package somehow relied on it finding this way.

**Comment by rhuijben** [comment]
@dg0yt do you know any quick fixes here?

**Comment by dg0yt** [comment]
I don't see why the `find_dependency` fails but I guess it is caused by custom FindSQLite3 modules in downstream projects, previously hidden by PROJ's module, and now hiding the official module. (Even GDAL maintains an own module.)

The question is if such modules set the right result variables (here: `SQLite3_FOUND`, not `SQLITE3_FOUND`). Such modules could be patched in downstream ports.

If we only need to isolate PROJ config from downstream's find modules, the PROJ config might be modified to do
~~~cmake
set(CMAKE_MODULE_PATH_BAK "${CMAKE_MODULE_PATH}")
set(CMAKE_MODULE_PATH "${CMAKE_ROOT}/Modules")
find_dependency(SQLite3)
set(CMAKE_MODULE_PATH "${CMAKE_MODULE_PATH}_BAK")
~~~

If we need to isolate downstreams from the side effects of the official module, we could patch PROJ to use vcpkg's `unofficial-sqlite3` config instead.

**Pull request closed without merging**
