### PR TITLE
[vcpkg scripts] Update Bazel to 6.1.1

### PR DESCRIPTION
**Pull request by sbrajchuk**
Was not able to install the ryu port using Visual Studio Community 2022 (64-bit) Version 17.5.1 on Windows 10 Pro (64-bit )
Version 22H2 (OS build 19045.2728).

After update the ryu port was installed successfully.

### CODE REVIEW

**Review by JonLiu1993 — DISMISSED** [review]

**Comment by sbrajchuk** [comment]
The latest version of Bazel is 6.1.1. I think we should update Bazel to it. @JonLiu1993 what do you think?

**Comment by JonLiu1993** [comment]
> The latest version of Bazel is 6.1.1. I think we should update Bazel to it. @JonLiu1993 what do you think?

It would be great if you could upgrade to the latest version.

**Comment by JonLiu1993** [comment]
Please get [failure logs here](https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/87043/artifacts?artifactName=failure%20logs%20for%20x64-linux&api-version=7.0&%24format=zip). Please ping me if you need any help.

**Comment by sbrajchuk** [comment]
All errors related to the MKL library. 
colmap:
`ninja: error: '/mnt/vcpkg-ci/installed/x64-linux/debug/lib/intel64/libmkl_intel_lp64.a', needed by 'src/exe/colmap', missing and no known rule to make it`

dbow2:
`ninja: error: '/mnt/vcpkg-ci/installed/x64-linux/debug/lib/intel64/libmkl_intel_lp64.a', needed by 'libDBoW2.so', missing and no known rule to make it`

openimageio:
`ninja: error: '/mnt/vcpkg-ci/installed/x64-linux/debug/lib/intel64/libmkl_intel_lp64.a', needed by 'bin/strutil_test', missing and no known rule to make it`

openturns:
`ninja: error: '/mnt/vcpkg-ci/installed/x64-linux/debug/lib/intel64/libmkl_intel_lp64.a', needed by 'lib/src/linktest', missing and no known rule to make it`

From what I understand, these errors are not related to the current PR.

**Comment by dg0yt** [comment]
The x64-linux baseline regressions should be fixed in master.

**Comment by dg0yt** [comment]
Did you mean to close this PR?

**Comment by sbrajchuk** [comment]
No, I just wanted to observe how the checks are conducted without my modifications:smile:

**Pull request closed without merging**
