### PR TITLE
[sdl2] Bump to 2.26.0

### PR DESCRIPTION
**Pull request by FtZPetruska**
**Describe the pull request**

- #### What does your PR fix?
  N/A

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  Unchanged

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  `Yes`

---

The first patch (`ports/sdl2/0001-sdl2-Enable-creation-of-pkg-cfg-file-on-windows.patch`) was replaced with `ports/sdl2/0001-sdl2-uwp-skip-list-clean.patch` since the rest of the patch was added upstream.

The second patch (`ports/sdl2/0002-sdl2-skip-ibus-on-linux.patch`) can be replaced by setting `SDL_IBUS` to `OFF`.

`SDL_INSTALL_CMAKEDIR` can be used to set CMake's install directory and remove the logic around `vcpkg_cmake_config_fixup`.

### CODE REVIEW

**Comment by FtZPetruska** [comment]
- ffmpeg issues (affects Windows and Linux):
```
=== CONFIGURING ===
ERROR: sdl2 requested but not found

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
```
Does not seem to happen when I try install `vcpkg[sdl2]` in a Linux container. Cannot test on Windows as `pkgconf` fails to install

- gamedev-framework issue on x64-Linux:
```
[28/29] : && /usr/bin/c++ -Wall -Wextra -pedantic -O1 -g  tools/gf_info/CMakeFiles/gf_info.dir/gf_info.cc.o -o tools/gf_info/gf_info  library/libgf0.a  library/libgfcore0.a  -lpthread  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libSDL2d.a  -ldl  -lwayland-egl  -lwayland-client  -lwayland-cursor  -lEGL  -lxkbcommon  -lrt  -pthread  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libfreetyped.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libbz2d.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libpng16d.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libz.a  -lm  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libbrotlidec-static.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libbrotlicommon-static.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libpugixml.a && :
FAILED: tools/gf_info/gf_info 
: && /usr/bin/c++ -Wall -Wextra -pedantic -O1 -g  tools/gf_info/CMakeFiles/gf_info.dir/gf_info.cc.o -o tools/gf_info/gf_info  library/libgf0.a  library/libgfcore0.a  -lpthread  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libSDL2d.a  -ldl  -lwayland-egl  -lwayland-client  -lwayland-cursor  -lEGL  -lxkbcommon  -lrt  -pthread  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libfreetyped.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libbz2d.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libpng16d.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libz.a  -lm  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libbrotlidec-static.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libbrotlicommon-static.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libpugixml.a && :
/usr/bin/ld: /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libSDL2d.a(SDL_waylandtouch.c.o): in function `Wayland_touch_create':
/mnt/vcpkg-ci/buildtrees/sdl2/src/ase-2.26.0-c07c770d55.clean/src/video/wayland/SDL_waylandtouch.c:256: undefined reference to `wl_registry_bind'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```
Similarly, does not happen when building from a Linux container (where SDL is built with Wayland support).

Any help would be greatly appreciated!

**Comment by quyykk** [comment]
> ffmpeg issues (affects Windows and Linux):

"sdl2 requested but not found" is a generic error message. Somewhere in the logs (I forgot where), there is the actual reason why it failed (for example, the Windows failure is almost certainly because of an ill-named debug library - we rename the Windows debug build names inside the pkgconfig file; If I were to guess upstream now correctly uses `-lSDL-static` for static Windows builds, so you'll have to update the find+replace in the portfile).

> gamedev-framework issue on x64-Linux:

It seems like CI has some pretty old wayland protocol library? You can try disabling wayland when the wayland feature isn't specified as a workaround for now I think. The correct solution would probably be to add [wayland] as a dependency

**Comment by FtZPetruska** [comment]
> > ffmpeg issues (affects Windows and Linux):
> 
> "sdl2 requested but not found" is a generic error message. Somewhere in the logs (I forgot where), there is the actual reason why it failed (for example, the Windows failure is almost certainly because of an ill-named debug library - we rename the Windows debug build names inside the pkgconfig file; If I were to guess upstream now correctly uses `-lSDL-static` for static Windows builds, so you'll have to update the find+replace in the portfile).

I skimmed through the logs again. It seems that ffmpeg is built with a `configure` script, and it doesn't seem like any log about it is captured other than the "sdl2 requested but not found" error. Although .pc file is correctly generated, named, and installed with `sdl2`.

I am still unable to build `pkgconf` which is necessary for ffmpeg to try it out on my personal machine.

**Comment by quyykk** [comment]
> it doesn't seem like any log about it is captured other

Oh you're right, I just checked and the log file is located under ffbuild/config.log inside the directory with the other log files (but Azure doesn't upload this).

The issues seems to be that Libs.private inside the sdl2.pc file includes -lSDL2-static. Simply deleting that entry makes ffmpeg build successfully on my machine.

For the windows static triplet: The sdl2.pc mentions SDL2-static instead of SDL2-staticd (this is what I referred to, you'll need to update the find+replace in the portfile). (It also mentions SDL2-static twice; same problem as above, but in this case it's fine).

**Comment by FtZPetruska** [comment]
Last failure remaining (Hopefully) when building `ogre` on `arm64-windows`.

```
CMake Error at Components/Bites/CMakeLists.txt:186 (qt6_wrap_cpp):
  Unknown CMake command "qt6_wrap_cpp".
```

Oddly enough I wasn't able to reproduce it locally. Any idea ?

**Comment by FrankXie05** [comment]
@FtZPetruska This is `CI pipline`. We are currently repairing it. Don't worry. :)

**Comment by FrankXie05** [comment]
@FtZPetruska Is this PR ready for review？

**Comment by FtZPetruska** [comment]
> @FtZPetruska Is this PR ready for review？

Yes, I was keeping it as draft while we were figuring out CI.

**Review by FrankXie05 — APPROVED** [review]

**Comment by JavierMatosD** [comment]
Thank you

**Pull request merged**
