### PR TITLE
[magic-enum] Update to the latest version

### PR DESCRIPTION
**Pull request by ljishen**
Update the [magic_enum](https://github.com/Neargye/magic_enum) port to support its latest features.

### CODE REVIEW

**Review by BillyONeal — CHANGES_REQUESTED** [review]
It seems like upstream actually does releases here: it would be wrong to tell people this is 0.7.3 when it is in fact something completely different. 

@Neargye are you expecting to do a release any time soon?

**Comment by Neargye** [comment]
@BillyONeal Yes, I prepare new release, and send the PR to vcpkg.

**Comment by ljishen** [comment]
That will be great. @Neargye I'll discard this change and hopefully see your update soon.

**Comment by Neargye** [comment]
@ljishen https://github.com/microsoft/vcpkg/pull/24646

**Comment by ljishen** [comment]
Thanks @[Neargye](https://github.com/Neargye). I have been waiting for this update!

**Pull request closed without merging**
