### PR TITLE
[vcpkg] Use IncludePath and LibraryPath properties

### PR DESCRIPTION
**Pull request by FrankHeimes**
These tool agnostic properties allow to configure ClCompile and ResourceCompile without repeating the code. This change includes my changes from #4454.

### CODE REVIEW

**Comment by FrankHeimes** [comment]
Signing the CLA apparently faces some technical difficulties: _400 - Request Header Or Cookie Too Large_

**Comment by Neumann-A** [comment]
Does the change from `AdditionalIncludeDirectories` to `IncludePath` and `AdditionalLibraryDirectories` to `LibraryPath` change the search order? 
I like the code reduction.

**Comment by FrankHeimes** [comment]
> Does the change from `AdditionalIncludeDirectories` to `IncludePath` and `AdditionalLibraryDirectories` to `LibraryPath` change the search order?

The search precedence is
1. C/C++ / Additional Include Directories
2. VC++ Directories / Include Directories

Since the `vcpkg` paths are appended to the variables, as before, my changes do not change the search order.

**Review by yuehuang010 — APPROVED** [review]
Please make sure that $(VcpkgRoot) is defined before this point.  You are moving the evaluation of VcpkgRoot earlier in MSBuild evalution order.

**Comment by NancyLi1013** [comment]
Could you please solve the conflicts in this PR?

**Comment by FrankHeimes** [comment]
> Please make sure that $(VcpkgRoot) is defined before this point. You are moving the evaluation of VcpkgRoot earlier in MSBuild evalution order.

I'm not sure if I get your point right. $(VcpkgRoot) is defined before being used (line 57). It is only used if $(VcpkgEnabled) is true.

**Comment by NancyLi1013** [comment]
@strega-nil 
Could you please help review this PR?

**Comment by strega-nil** [comment]
@ras0219-msft @dan-shaw I don't know anything about MSBuild; could you look into this?

**Comment by yuehuang010** [comment]
MSBuild evaluation order:
1) Under \<Project\>, \<PropertyGroup\>
2) Under \<Project\>, then \<ItemDefinitionGroup\>
3) Under \<Project\>, then \<ItemGroup\>
4) Under \<Target\>, in order.

Your change moved $(VcpkgRoot) from #2 to #1.  There is a chance where $(VcpkgRoot) could have changed by another property group.

**Comment by FrankHeimes** [comment]
> MSBuild evaluation order:
> 
> 1. Under <Project>, <PropertyGroup>
> 2. Under <Project>, then <ItemDefinitionGroup>
> 3. Under <Project>, then <ItemGroup>
> 4. Under <Target>, in order.
> 
> Your change moved $(VcpkgRoot) from #2 to #1. There is a chance where $(VcpkgRoot) could have changed by another property group.

You're right. After importing vcpkg.targets, another <PropertyGroup> might be evaluated that changes $(VcpkgRoot) again. So vcpkg isn't supposed to modify $(IncludePath) and $(LibraryPath) at all, or is it?

**Comment by NancyLi1013** [comment]
@FrankHeimes 
Could you please remove the conflicts?

**Comment by FrankHeimes** [comment]
@NancyLi1013 I removed the conflict and addressed @yuehuang010's objection against modifying IncludePath and LibraryPath using the contents of $(VcpkgRoot); i.e. I reverted some of my changes.

**Comment by strega-nil** [comment]
@FrankHeimes could you merge in PR FrankHeimes/master#2?

**Pull request merged**
