### PR TITLE
[ffmpeg] fix link order

### LINKED ISSUE #9714: ffmpeg link error
**Describe the bug**
ffmpeg can not link to executable file

**Environment**
- OS: [e.g. Windows/Linux etc...] Linux x64 
- Compiler: gcc8.3

**To Reproduce**
cmake file
```
cmake_minimum_required(VERSION 3.15)

project(usb_cam)

set(CMAKE_CXX_STANDARD 11)

if (CMAKE_SYSTEM_NAME MATCHES "Linux")
    message(STATUS "current platform: Linux ")
    set( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O2" )
    find_package(FFMPEG REQUIRED)
    include_directories(${FFMPEG_INCLUDE_DIRS})
    link_directories(${FFMPEG_LIBRARY_DIRS})
elseif (CMAKE_SYSTEM_NAME MATCHES "Windows")
    message(STATUS "current platform: Windows")
else ()
    message(STATUS "other platform: ${CMAKE_SYSTEM_NAME}")
endif (CMAKE_SYSTEM_NAME MATCHES "Linux")

include_directories(src)

file(GLOB_RECURSE SRC_FILES src/*.cpp *.h)

add_executable(usb_cam ${SRC_FILES})
target_link_libraries(usb_cam ${FFMPEG_LIBRARYS})

cpp file
#include <iostream>
using namespace std;
extern "C"
{
#include <math.h>
#include <libavutil/opt.h>
#include <libavcodec/avcodec.h>
#include <libavutil/channel_layout.h>
#include <libavutil/common.h>
#include <libavutil/imgutils.h>
#include <libavutil/mathematics.h>
#include <libavutil/samplefmt.h>
#include <libavformat/avformat.h>
#include <libavdevice/avdevice.h>
#include <libavutil/dict.h>
};
int main(int argc, char **argv)
{
    int ret;
    AVFormatContext *fmtCtx = NULL;
    AVPacket pkt1, *pcaket = &pkt1;
    avcodec_register_all();
    avdevice_register_all();
    AVInputFormat *inputFmt = av_find_input_format("video4linux2");
    if (NULL != inputFmt)
    {
        std::cout << "input device name:" << inputFmt->name << std::endl;
    }
    else
    {
        std::cout << "Null point!" << std::endl;
    }
    ret = avformat_open_input(&fmtCtx, "/dev/video0", inputFmt, NULL);
    if (0 == ret)
    {
        std::cout << "Open input device seccess!" << std::endl;
    }
    av_read_frame(fmtCtx, pcaket);
    std::cout << "packet size:" << (pcaket->size) << std::endl;
    FILE *fp = NULL;
    fp = fopen("out.yuv", "wb");
    if (NULL != fp)
    {
        fwrite(pcaket->data, 1, pcaket->size, fp);
    }
    fclose(fp);
    av_free_packet(pcaket);
    avformat_close_input(&fmtCtx);
    return 0;
}
```
**Expected behavior**

**Failure logs** 
```
main.cpp:(.text.startup+0x12): undefined reference to `avcodec_register_all'
/usr/bin/ld: main.cpp:(.text.startup+0x17): undefined reference to `avdevice_register_all'
/usr/bin/ld: main.cpp:(.text.startup+0x23): undefined reference to `av_find_input_format'
/usr/bin/ld: main.cpp:(.text.startup+0x77): undefined reference to `avformat_open_input'
/usr/bin/ld: main.cpp:(.text.startup+0x91): undefined reference to `av_read_frame'
/usr/bin/ld: main.cpp:(.text.startup+0x103): undefined reference to `av_free_packet'
/usr/bin/ld: main.cpp:(.text.startup+0x10b): undefined reference to `avformat_close_input'
collect2: error: ld returned 1 exit status
```

**Additional context**

### PR DESCRIPTION
**Pull request by Neumann-A**
closes #9714

### CODE REVIEW

**Comment by cenit** [comment]
before merging please check original issue and eventual updates

**Comment by cenit** [comment]
@Neumann-A sorry for asking, did you try with the example supplied by the issue owner if it is fixed now? Since we are updating ffmpeg many times in these days, it would be nice to have an update that lasts some time...

**Comment by Neumann-A** [comment]
@how0723 Could you try this PR out and check if it really fixes your problem. 

@cenit The problem with the example is that it is only partially testing the link order. I have to trust, that the dependency list in https://github.com/microsoft/vcpkg/issues/9714#issuecomment-575591795 is somehow correct.

**Comment by how0723** [comment]
I have checked and it really fixed. @Neumann-A

**Review by JackBoosY — APPROVED** [review]

**Comment by vicroms** [comment]
Thanks for the PR!

**Pull request merged**
