### PR TITLE
[open62541] fix dynamic build

### PR DESCRIPTION
**Pull request by PhoebeHui**
Fix issue https://github.com/microsoft/vcpkg/issues/8242

1. It only replace ${CMAKE_INSTALL_PREFIX}"  to ${BIN_INSTALL_DIR} in CMakeList.txt file, it doesn't define BIN_INSTALL_DIR before, so the dll doesn't install correctly. Fix and move that in patch.
2. Remove EXECUTABLE_SUFFIX since it doesn't use here.

### CODE REVIEW

**Comment by cenit** [comment]
the regex was there because in this way the port file works also with --head revision.
Please rearrange it to keep --head version working, otherwise it would be a bad regression for me (and I heard also other users here that preferred the head version @traversaro if I remember correctly)

**Comment by cenit** [comment]
about the executable suffix, it should have been used for the python tools just below this removed definition. Instead of the explicit .exe that now is present, the symbols should be used ;)

**Comment by PhoebeHui** [comment]
@cenit, thanks for your review, I added the regex back for unblocking you and other user when build the port with --head. I also changed the .exe to EXECUTABLE_SUFFIX.

**Comment by cenit** [comment]
thank you very much

**Review by JackBoosY — APPROVED** [review]

**Pull request merged**
