### PR TITLE
[ffmpeg] fix link debug bzip2

### PR DESCRIPTION
**Pull request by cbezault**
Closes #4250

### CODE REVIEW

**Comment by emptyVoid** [comment]
@cbezault, this doesn't seem to work.

I'm trying to build ```ffmpeg``` with:
```
.\vcpkg.exe install ffmpeg[bzip2]
```
Your patch does not get applied:
```
-- Applying patch fixed-debug-bzip2-link.patch
-- Applying patch failed. This is expected if this patch was previously applied.
```
Here's the contents of ```patch-x64-windows-6-err.log```:
```
Checking patch configure...
error: while searching for:
enable $subarch
enabled spic && enable_weak pic

# OS specific
case $target_os in
    aix)

error: patch failed: configure:4753
error: configure: patch does not apply
```
Debug configuration fails to build:
```
-- Building ffmpeg for Debug
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: D:/Temp/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe;--noprofile;--norc;D:/Temp/vcpkg/ports/ffmpeg\build.sh;D:/Temp/vcpkg/buildtrees/ffmpeg/x64-windows-dbg;D:/Temp/vcpkg/buildtrees/ffmpeg/src/ffmpeg-4-7abad339c8;D:/Temp/vcpkg/packages/ffmpeg_x64-windows/debug;--enable-asm --enable-yasm --disable-doc --enable-debug --enable-runtime-cpudetect --disable-openssl --disable-ffmpeg --disable-ffplay --disable-ffprobe --disable-libx264 --disable-opencl --disable-lzma --enable-bzlib --extra-cflags=-DHAVE_UNISTD_H=0 --disable-static --enable-shared  --extra-cflags=-MDd --extra-cxxflags=-MDd
```
Here's the contents of ```build-x64-windows-dbg-out.log```:
```
=== CONFIGURING ===
ERROR: bzlib requested but not found

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
```

**Comment by cbezault** [comment]
Hmmm, I managed to get it to build on my system I'll fix this issue asap

**Comment by cenit** [comment]
@cbezault yes that’s the goal of #6578. It’s necessary to finish it before transforming the status message into a fatal_error one, otherwise many ports would fail. It was not designed as a fatal error since the beginning only because vcpkg was missing some source-recycling mechanisms. Now that they are available, I think it’s better to move to fail. Many mistakes and problems would be avoided, with no counter problem afaik

**Comment by cbezault** [comment]
@emptyvoid we're going to be making a change to bzip so that we don't add the "d" suffix, once that is done I'll submit a PR that should add bzip2 support on windows and all other platforms.

**Pull request merged**
