### PR TITLE
[hpx] Adapting for HPX V1.5

### PR DESCRIPTION
**Pull request by hkaiser**
This PR updates HPX to V1.5

### CODE REVIEW

**Comment by aurianer** [comment]
Thanks @hkaiser!

**Review by PhoebeHui — APPROVED** [review]
Thanks for the PR!

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Comment by hkaiser** [comment]
> Thanks for your contribution!

Thanks for your work on vcpkg!

**Pull request merged**
