### PR TITLE
[libpng] remove broken patch

### PR DESCRIPTION
**Pull request by cenit**

### CODE REVIEW

**Comment by NancyLi1013** [comment]
Hi @cenit, I see that qt5-3d failed on x86-windows from the current CI system.
The error likes this:
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: C:/vsts/_work/2/s/downloads/tools/jom/jom-1.1.3/jom.exe
    Working Directory: C:/vsts/_work/2/s/buildtrees/qt5-3d/x86-windows-rel
    Error code: 2
    See logs for more information:
      C:\vsts\_work\2\s\buildtrees\qt5-3d\package-build-x86-windows-rel-out.log
      C:\vsts\_work\2\s\buildtrees\qt5-3d\package-build-x86-windows-rel-err.log
[failureLogs.zip](https://github.com/Microsoft/vcpkg/files/3145237/failureLogs.zip)

**Comment by cenit** [comment]
This one is really curious, I will investigate it soon (I didn’t open the zip as of now): this PR technically should not change anything, since it adds “unused” targets (make the port more future-proof) and removes a patch that was impossible to apply because it was broken with recent sources... I was expecting an “easy” green mark!

**Comment by vicroms** [comment]
@cenit were you able to get a repro?
I was unable to get one locally.

**Comment by cenit** [comment]
@vicroms No sorry. Too much busy

**Pull request merged**
