### PR TITLE
[libflac] Fix build error

### LINKED ISSUE #14044: [libflac] build failure
**Host Environment**
- OS: Windows 10
- Compiler: VS2019

**To Reproduce**
`./vcpkg install libflac`

**Failure logs** 
.\vcpkg.exe install libflac
Computing installation plan...
The following packages will be built and installed:
    libflac[core]:x86-windows
Detecting compiler hash for triplet x86-windows...
Starting package 1/1: libflac:x86-windows
Building package libflac[core]:x86-windows...
Could not locate cached archive: C:\Users\cbe\AppData\Local\vcpkg\archives\09\090658f2a269f3d0a3bd02a5bff0f0b3f2e3437e.zip
-- Using cached C:/Devel/vcpkg/vcpkg/downloads/xiph-flac-ce6dd6b5732e319ef60716d9cc9af6a836a4011a.tar.gz
-- Cleaning sources at C:/Devel/vcpkg/vcpkg/buildtrees/libflac/src/a836a4011a-c7a3381410.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Devel/vcpkg/vcpkg/downloads/xiph-flac-ce6dd6b5732e319ef60716d9cc9af6a836a4011a.tar.gz
-- Applying patch C:/Devel/vcpkg/vcpkg/ports/libflac/uwp-library-console.patch
-- Applying patch C:/Devel/vcpkg/vcpkg/ports/libflac/uwp-createfile2.patch
-- Using source at C:/Devel/vcpkg/vcpkg/buildtrees/libflac/src/a836a4011a-c7a3381410.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:141 (message):
    Command failed: C:/Devel/vcpkg/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v -j21
    Working Directory: C:/Devel/vcpkg/vcpkg/buildtrees/libflac/x86-windows-dbg
    See logs for more information:
      C:\Devel\vcpkg\vcpkg\buildtrees\libflac\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:92 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/libflac/portfile.cmake:37 (vcpkg_install_cmake)
  scripts/ports.cmake:79 (include)

Error: Building package libflac:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libflac:x86-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Additional context**
Latest portfiles have been used.

### PR DESCRIPTION
**Pull request by NancyLi1013**
**Describe the pull request**

- What does your PR fix? Fixes #14044

Add MSVC condition for these two compile options `/wd4267 /wd4996`. 

Add `asm `as feature for libflac.

Add `vcpkg_fixup_pkgconfig()` to check pkgconfig files.

Note: Feature has passed with the following triplets:

- x86-windows
- x86-windows-static

Feature `asm `only supports x86 architecture.

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by cbergemann** [comment]
This pull request does not fix the issue for me. The error remains the same (see attached log). The problem is that for some reason nasm is detected as MSVC, and hence the /wd* options are set. They are incompatible with nasm.

To reproduce:

`vcpkg install libflac:x86-windows`
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5442007/install-x86-windows-dbg-out.log)

**Comment by NancyLi1013** [comment]
Thanks for your testing and feedback.
I think we can consider to try to remove these two options directly. Seems that it can build fine on x86-windows and x64-windows without these two options.

@cbergemann What do you think? Or do you have another good idea about this issue?

Thanks.

**Comment by NancyLi1013** [comment]
@cbergemann 

You can try to rebuild this port based on the latest commit.

**Comment by cbergemann** [comment]
I am happy to report that with the current version, libflac builds successfully on x86. Thank you @NancyLi1013 for your work and support!

**Review by JackBoosY — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for your help!

**Pull request merged**
