### PR TITLE
[casclib] Add new port

### PR DESCRIPTION
**Pull request by stijnherfst**
Add support for the CascLib library. This library does not target UWP as a platform.

### CODE REVIEW

**Comment by Rastaban** [comment]
I also see a failure on Mac, is that expected?

**Comment by stijnherfst** [comment]
> I also see a failure on Mac, is that expected?

No, it should work on Mac OS. Could you send me the failure logs? I can only access the failure logs for Windows and Linux it seems.

**Comment by Rastaban** [comment]
We are in the process of bringing up a new osx test pipeline that is accessible by the community.  You can find the logs in that new pipeline here: https://dev.azure.com/vcpkg/public/_build/results?buildId=1566&view=results.  If you run into issues getting these logs let me know so I can fix the pipeline.

**Comment by Rastaban** [comment]
It looks like the build is not finding `isxdigit` from `<cctype>`.

```
src/CascFiles.cpp:161:39: error: use of undeclared identifier 'isxdigit'
        if (szDataPtr >= szDataEnd || isxdigit(szDataPtr[0]) == 0)
                                      ^
```

I don't have access to a Mac right now, but my guess is that <cctype> is indirectly included, and the version of the tools used on our Mac test machine is a different version than what you have so the file is not getting pulled in.  I bet if you add a patch that puts `#include <cctype>` into `src/CascCommon.h` then it will fix the build issue.

**Comment by Rastaban** [comment]
It looks like <ctype.h> is included in CascPort.h for Windows/Linux but not for Mac.  I have it open so I will just add the patch to see if that makes the CI system happy.

**Comment by Rastaban** [comment]
OSX is happy now :)

**Comment by stijnherfst** [comment]
Thanks for solving the issues with Mac compilation! I was very busy lately so didn't get to it.

**Pull request merged**
