### PR TITLE
[openexr] Fix openexr using unrequested intrinsics

### PR DESCRIPTION
**Pull request by Neumann-A**
this is way to much typing for small patches

### CODE REVIEW

**Comment by Neumann-A** [comment]
Ok now osx is happy.

**Review by MonicaLiu0311 — APPROVED** [review]

**Comment by dan-shaw** [comment]
Has this change been submitted to upstream?

**Comment by Neumann-A** [comment]
I informed upstream about it.

**Comment by Neumann-A** [comment]
upstream has created https://github.com/AcademySoftwareFoundation/openexr/pull/1354 which is the patch added here

**Review by MonicaLiu0311 — APPROVED** [review]

**Comment by Neumann-A** [comment]
@dan-shaw why does this depend on a different pr?

**Comment by dan-shaw** [comment]
I would prefer if upstream merged first

**Comment by Neumann-A** [comment]
@MonicaLiu0311 Why should upstream make a new release for such a small and more or less unimportant change? (referring to https://github.com/AcademySoftwareFoundation/openexr/pull/1354#issuecomment-1469287729). Especially since the last release was just last week. I mean if it is CVE fixed here than I would understand that request but this here is just a minor correction for a preprocessor definition correctly allowing AVX which MSVC normally silently ignores/allows (i.e. allowing instructions although the correct arch flag is missing.). 

@dan-shaw: I understand that but taking https://github.com/microsoft/vcpkg-docs/pull/35/ into account I have to assume you have no confidence in this patch although upstream itself created a PR including the patch and upstream CI being green. I find that kind of funny but its ok ;), just make sure i don't need to remember you to merge this PR if upstream is merged.

**Pull request merged**
