### PR TITLE
[protobuf] Update to 3.8.0

### PR DESCRIPTION
**Pull request by myd7349**

### CODE REVIEW

**Comment by NancyLi1013** [comment]
Hi @myd7349, thanks for your PR. I see that orc also failed on OSX. Please let us know if you need any help.

**Comment by dan-shaw** [comment]
Right now, we are waiting for #6872 to go through. This should set CMAKE_SYSTEM_PROCESSOR correctly on Linux.

**Comment by dan-shaw** [comment]
Thanks for the PR!

**Pull request merged**
