### PR TITLE
[boost-process] Patch for header bug in boost 1.72

### PR DESCRIPTION
**Pull request by d-winsor**
Applies a patch to fix boost-process which is currently broken in 1.72. This is likely to be fixed in 1.73 at which point this patch can be removed.

- What does your PR fix? Fixes issue #

This fixed issue https://github.com/boostorg/process/issues/116

- Which triplets are supported/not supported? Have you updated the CI baseline?

All triplets should be supported. Have no updated the CI baseline.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

Yes

### CODE REVIEW

**Review by NancyLi1013 — COMMENTED** [review]
`include(vcpkg_common_functions)` is no longer needed. 
Could you please remove this line?

Could you  please also update the version in `ports/boost-process/CONTROL` file as `1.72.0-1`?

**Comment by d-winsor** [comment]
> `include(vcpkg_common_functions)` is no longer needed.
> Could you please remove this line?
> 
> Could you please also update the version in `ports/boost-process/CONTROL` file as `1.72.0-1`?

Removing `include(vcpkg_common_functions)` would update every boost port file as they are auto-generated. That means updating every boost port version number. Is that OK or should it be a separate PR?

**Review by dan-shaw — APPROVED** [review]

**Comment by dan-shaw** [comment]
LGTM, we will probably need to remove the patch from the script for 1.73, but that is fine. There are some unrelated failures in the CI that we are trying to fix which may depend on boost, so we should wait before merging this.

**Review by NancyLi1013 — APPROVED** [review]

**Pull request merged**
