### PR TITLE
[vcpkg] Add new community triplet x86-windows-static-release

### PR DESCRIPTION
**Pull request by xiaozhuai**
**Describe the pull request**

Since there are `x64-windows-static-release`, `arm-windows-static-release`, `arm64-windows-static-release` and missing `x86-windows-static-release`. We should also add this.

1. Add new community triplet `x86-windows-static-release`

### CODE REVIEW

**Review by JonLiu1993 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Tagging requires: vcpkg-team-review because I want to confirm the team is OK with this.

The triplet on its face as a thing to do is reasonable, but I think we want to make sure we're principled about not necessarily creating the cross product of possible settings.

**Comment by BillyONeal** [comment]
@ras0219-msft @markle11m @JavierMatosD @dan-shaw and I discussed this today.

We think there needs to be some set of guidelines for what community triplets we add.

To be a triplet it needs to be tested in our CI.
To be a community triplet we need to not know that it does not work. (This is what excluded linux-dynamic before the patchelf workaround was found)
To be a community triplet we need to know that a user actually wants to use that combination: the entire combinatoric state space of these options is impractical to generate. Someone adding x86-windows-dynamic-md just because we have x64-windows-dynamic-md and they see that it could go there is not sufficient.
We are not looking to fill every hole in the sparse matrix, due to the costs of potentially thousands of files to model that space. (That is, we would be happy to model the whole space if it were not impractically expensive to do so)

We think it might make sense to make tool changes that change the triplet system so that the obvious scheme ones are 'generated' automatically. In the medium term we are also looking to generate much of the triplet interaction by inspection of the consuming build system in manifest mode.

Because this PR looks like it's just trying to fill an entry in the sparse matrix rather than a demonstrated end user requirement, we are going to close this PR. That does not mean that we wouldn't add this community triplet if a meaningful number of users who would benefit is demonstrated. (If you are a user who is supplying this triplet regularly with an overlay, please respond here!)

Thanks for your contribution to vcpkg, and sorry we didn't land this!

**Comment by xiaozhuai** [comment]
> @ras0219-msft @markle11m @JavierMatosD @dan-shaw and I discussed this today.
> 
> We think there needs to be some set of guidelines for what community triplets we add.
> 
> To be a triplet it needs to be tested in our CI. To be a community triplet we need to not know that it does not work. (This is what excluded linux-dynamic before the patchelf workaround was found) To be a community triplet we need to know that a user actually wants to use that combination: the entire combinatoric state space of these options is impractical to generate. Someone adding x86-windows-dynamic-md just because we have x64-windows-dynamic-md and they see that it could go there is not sufficient. We are not looking to fill every hole in the sparse matrix, due to the costs of potentially thousands of files to model that space. (That is, we would be happy to model the whole space if it were not impractically expensive to do so)
> 
> We think it might make sense to make tool changes that change the triplet system so that the obvious scheme ones are 'generated' automatically. In the medium term we are also looking to generate much of the triplet interaction by inspection of the consuming build system in manifest mode.
> 
> Because this PR looks like it's just trying to fill an entry in the sparse matrix rather than a demonstrated end user requirement, we are going to close this PR. That does not mean that we wouldn't add this community triplet if a meaningful number of users who would benefit is demonstrated. (If you are a user who is supplying this triplet regularly with an overlay, please respond here!)
> 
> Thanks for your contribution to vcpkg, and sorry we didn't land this!

In fact, I do use this triplet. I use it on making a windows virtual camera (with dshow lib). And it need provide both x64 and x86 dll to make both x86 and x64 client work. And I want this dll independs with vc runtime. So I would like to link to static runtime and other libs. That why I add such a triplet. And I believe there should be other similar situation.

**Comment by Neumann-A** [comment]
Just have an extra folder with triplets and define that folder as an overlay? I mean I do that for https://github.com/Neumann-A/my-vcpkg-triplets

**Comment by xiaozhuai** [comment]
> Just have an extra folder with triplets and define that folder as an overlay? I mean I do that for https://github.com/Neumann-A/my-vcpkg-triplets

That is inneed what I need, thank you!

**Pull request closed without merging**
