### PR TITLE
[TinyEXIF] Update to version 1.0.2

### PR DESCRIPTION
**Pull request by cdcseacave**

### CODE REVIEW

**Comment by cdcseacave** [comment]
@vicroms Is there anything missing to commit this PR?

**Comment by vicroms** [comment]
Hi @cdcseacave 

I'm currently looking into an issue on x64-osx with this library.

```
Processing x64-osx                        526 vs 527
    tinyexif                      **regression**                Fail vs Pass
```

**Comment by vicroms** [comment]
@cdcseacave 

The following line is giving a compilation error on OS X.
```
TinyEXIF.cpp:71:47: error: unknown type name 'TCHAR'
    static void strSplit(const std::string& str, TCHAR delim, std::vector<std::string>& values) {
```

It is related to the following check:
```
#ifdef _MSC_VER
#include <tchar.h>
#else
```
As OS X libraries do not define TCHAR.
Seeing as you're the library author, is there a reason to use TCHAR instead of a more portable type?

**Comment by cdcseacave** [comment]
Thx, you are right, there is absolutely no reason for using that, it was a copy paste error (I use this lib inside a bigger app). I fixed it, now should be fine.
Can you pls have a look at this [PS ](https://github.com/Microsoft/vcpkg/pull/5137) as well? I need it too for my work.
Thank you!

**Comment by vicroms** [comment]
And finally it is merged!

**Comment by cdcseacave** [comment]
@vicroms can u pls explain all the changes you made so that I do not repeat the mistakes again?
the first looks like changing to a random SSH hash, and in the second you revert to the one I used, while in the third you use a new one again; I do not understand any of these

**Comment by vicroms** [comment]
Thanks for asking! (please ignore everything but the last commit, those were me screwing it up...) 

**vcpkg** caches the downloaded source code in a zip file `/downloads/<package>-<version>`; where `<version>` matches a Github release tag or a commit's SHA (specified by REF in the CONTROL file). 

__In this case, the release tag's commit changed but the version number did not.__
In the download step, **vcpkg** detects that it already has downloaded the source code for version 1.0.2 and uses it. However, the SHA512 of the (old) downloaded source code and the expected SHA512 specified in CONTROL are different.

To fix this, I changed REF to be the SHA of the commit, and the SHA512 in CONTROL to be the SHA512 of the source code downloaded from that commit.

To avoid this issue in the future, I suggest creating a new release for the newest commit instead of moving the release tag.
Examples: 1.0.2.1 or 1.0.3.

Does this makes sense?

**Comment by cdcseacave** [comment]
it makes sense, except for the SHA512 which the correct value for https://github.com/cdcseacave/TinyEXIF/archive/1.0.2.tar.gz is 95a88c45c9f4812266cc6b7cf57e93be1229513274b446f5da6b9c4d5dc07c07985bf6ad6ffc31de673e88ef6e428cb29b1b58ad78dee17cb36fc2b859a55f98

Why did u use a different value and from where did you take it?

**Pull request merged**
