### PR TITLE
[ffmpeg] reenable osx platform support for ffmpeg[sdl2]

### PR DESCRIPTION
**Pull request by foobra**
- [ √] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [√ ] The "supports" clause reflects platforms that may be fixed by this new version.
- [ √] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [√ ] Only one version is added to each modified port's versions file.

@microsoft-github-policy-service agree

### CODE REVIEW

**Comment by foobra** [comment]
I've tested on my x64-osx . fix #40232

**Comment by MonicaLiu0311** [comment]
Please resolve the conflict.

**Comment by MonicaLiu0311** [comment]
I will be converting your PR to draft status. When you're ready, please revert to "ready for review".

**Review by MonicaLiu0311 — APPROVED** [review]

**Comment by MonicaLiu0311** [comment]
Feature `ffmpeg[sdl2]` is tested successfully in the following triplet:
```
arm64-osx
```

**Pull request merged**
