### PR TITLE
[tomlplusplus] Update to 3.3.0

### LINKED ISSUE #33810: [tomlplusplus] update to 3.3.0
### Library name

tomlplusplus

### New version number

3.3.0

### Other information that may be useful (release notes, etc...)

https://github.com/marzer/tomlplusplus/releases/tag/v3.3.0

### PR DESCRIPTION
**Pull request by LilyWangLL**
Fixes #33810, update `tomlplusplus` to 3.3.0, add `usage` for it.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

Usage test passed on `x64-windows`.

### CODE REVIEW

**Comment by LilyWangLL** [comment]
The following [CI pipeline](https://dev.azure.com/vcpkg/public/_build/results?buildId=94205&view=logs&jobId=c1ef8ca6-ab04-50c1-d72d-1af418e8be99&j=c1ef8ca6-ab04-50c1-d72d-1af418e8be99&t=dafb61b0-0690-5aa4-f152-5e6b2a96efb2) error looks a compiler error, need I add `tomlplusplus:arm-neon-android=fail` to `ci.baseline.txt`? cc @dan-shaw @vicroms 
```
/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -Isrc/libtomlplusplus.a.p -Isrc -I../src/v3.3.0-055894c820.clean/src -Iinclude -I../src/v3.3.0-055894c820.clean/include -I/mnt/vcpkg-ci/installed/arm-neon-android/include -fvisibility=hidden -fcolor-diagnostics -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++17 -O0 -g --target=armv7-none-linux-androideabi21 -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security -frtti -fexceptions -fPIC --sysroot=/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/sysroot -fno-limit-debug-info -fPIC -ferror-limit=5 -Wno-unused-command-line-argument -Wno-reserved-macro-identifier -fchar8_t -D_HAS_EXCEPTIONS=1 -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-documentation -Wno-documentation-unknown-command -Wno-switch-enum -Wno-covered-switch-default -Wno-padded -Wno-float-equal -DTOML_HEADER_ONLY=0 -MD -MQ src/libtomlplusplus.a.p/toml.cpp.o -MF src/libtomlplusplus.a.p/toml.cpp.o.d -o src/libtomlplusplus.a.p/toml.cpp.o -c ../src/v3.3.0-055894c820.clean/src/toml.cpp
In file included from ../src/v3.3.0-055894c820.clean/src/toml.cpp:13:
In file included from ../src/v3.3.0-055894c820.clean/include/toml++/toml.h:69:
In file included from ../src/v3.3.0-055894c820.clean/include/toml++/impl/parser.inl:26:
/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/fstream:952:20: error: use of undeclared identifier 'ftello'; did you mean 'ftell'?
    pos_type __r = ftello(__file_);
                   ^
/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/cstdio:141:9: note: 'ftell' declared here
using ::ftell;
        ^
In file included from ../src/v3.3.0-055894c820.clean/src/toml.cpp:13:
In file included from ../src/v3.3.0-055894c820.clean/include/toml++/toml.h:69:
In file included from ../src/v3.3.0-055894c820.clean/include/toml++/impl/parser.inl:26:
/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/fstream:950:9: error: use of undeclared identifier 'fseeko'
    if (fseeko(__file_, __width > 0 ? __width * __off : 0, __whence))
        ^
```

**Comment by LilyWangLL** [comment]
The baseline error `rsm-bsa:arm-neon-android` will fixed by PR https://github.com/microsoft/vcpkg/pull/33900.

**Comment by LilyWangLL** [comment]
The baseline error `tomlplusplus:arm-neon-android`, I have submitted an upstream issue: https://github.com/marzer/tomlplusplus/issues/204

**Comment by dg0yt** [comment]
> /android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/fstream:952:20: error: use of undeclared identifier 'ftello'; did you mean 'ftell'?

`ftello` needs API level >= 24.
https://android.googlesource.com/platform/bionic/+/master/docs/32-bit-abi.md#32_bit-and

**Review by Cheney-W — APPROVED** [review]

**Pull request merged**
