### PR TITLE
libwebsockets: added support to build uwp versions

### PR DESCRIPTION
**Pull request by stammen**
This PR adds support for building uwp versions of libwebsockets.  This PR depends on PR #524 to pass WACK testing. (openssl dlls were failing WACK)

### CODE REVIEW

**Comment by ras0219-msft** [comment]
By default (and in the case of this port) we share the source tree across all triplets. Therefore, to get reproducible results, could you modify the patch to always be applied? My brief skim says it shouldn't significantly change the non-uwp build, but I'd like a second opinion.

**Comment by stammen** [comment]
I authored the patch to work across all triplets so I will modify the pull request to patch the source for all builds.

**Comment by stammen** [comment]
@ras0219-msft The patch is now applied to all builds triplets.

**Comment by ras0219-msft** [comment]
Thanks!

I bumped the version since this modifies the produced package.

**Pull request merged**
