### PR TITLE
[Vcpkg] clean PR clutters commit

### LINKED ISSUE #37352: PR template clutters commit messages
The current style of merging PRs makes all parts of the GH PR template enter the git log, including parts hidden in GH UI (`<!-- ... -->`).
In general, commit messages are not given much attention (except from those who dig history for cruft blocking good port quality).

### PR DESCRIPTION
**Pull request by FrankXie05**
Fix https://github.com/microsoft/vcpkg/issues/37352

### CODE REVIEW

**Comment by dg0yt** [comment]
The problem is not in the contributor's commit message, and this cannot be caught with regular PR checks because that commit message doesn't exist at that time.
The problem is in the commit message of the Squash Merge Commit which is synthetized from the initial post.

The initial post is based on the PR draft message  which is unfortunately designed to have commented sections. PR checks would have to fetch the PR's comment via GH API. But you can't really suggest to remove the commented sections which were just suggested by the template.

**Comment by FrankXie05** [comment]
@dg0yt 
This mechanism is mainly to prompt maintainers to check whether the body contains undeleted notes section, helping to clean up the messy information in the commit.

**Comment by Osyotr** [comment]
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests

> The default message uses the commit title and message if the pull request contains only 1 commit, or the pull request title and list of commits if the pull request contains 2 or more commits. You can also choose to use just the pull request title, the pull request title and commit details, >**or the pull request title and description.**<

I guess someone changed repository settings to this. Please change back to
> pull request title and list of commits

**Comment by BillyONeal** [comment]
> The problem is in the commit message of the Squash Merge Commit which is synthetized from the initial post.

image

I think when you first complained about this I changed it to PR title instead.

**Comment by BillyONeal** [comment]
I think this is 'the person clicking the merge button needs to do a better job' than something to complain about contributors about.

**Comment by BillyONeal** [comment]
@FrankXie05 Thanks for looking in to this. I think the problem @dg0yt was talking about should be resolved now without needing to add more bots. Thanks!

**Pull request closed without merging**
