### PR TITLE
[kangaru ] Update to version 4.3.1

### PR DESCRIPTION
**Pull request by gracicot**
**Describe the pull request**

This pull request updates kangaru to version 4.3.1

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  
All

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?

Yes

### CODE REVIEW

**Comment by dg0yt** [comment]
> Unknown CMake command "vcpkg_cmake_configure".

Maybe the installed `vcpkg-cmake` (for the host triplet) needs an upgrade. Check with `./vcpkg upgrade`.

**Comment by JonLiu1993** [comment]
> @JonLiu1993 Hi I noticed you added the `requires:author-response` label, but I'm unsure what response you need.

@gracicot, The above are all my review comments, please take a look.

**Comment by gracicot** [comment]
> @gracicot, The above are all my review comments, please take a look.

@JonLiu1993 Sorry for pinging again, but have you published the review? I'm not seeing any review comments, not here, not in the files changes tab

**Review by JonLiu1993 — CHANGES_REQUESTED** [review]

**Comment by gracicot** [comment]
It should be all good now!

**Review by JonLiu1993 — APPROVED** [review]

**Comment by JonLiu1993** [comment]
All features are tested successfully in the following triplet:
- x86-windows
- x64-windows
- x64-windows-static
- x64-linux

**Pull request merged**
