### PR TITLE
[qt5-websockets] Option to disable qt5-decalarative dependency

### PR DESCRIPTION
**Pull request by kafeg**
[qt5-websockets] Option to disable qt5-decalarative dependency

### CODE REVIEW

**Comment by Neumann-A** [comment]
The way it is currently implemented breaks binary caching. You need to pass an option to qmake to toogle/enforce the correct behavior. (but don't ask me which one it is)

**Comment by kafeg** [comment]
Everything what i found is condition in `buildtrees\qt5-websockets\src\5.15.2-d3bc637515.clean\src\src.pro` file :
```
TEMPLATE = subdirs
CONFIG += ordered

qtConfig(textcodec) {
    SUBDIRS += websockets
    qtHaveModule(quick): SUBDIRS += imports
}
```
It builds just a plugin for QML if Qt:Quick module available. And if not then it will not build a plugin.

But not in all cases `Qt:Quick` and all it deps needed to build app project.

So i just propose to make that dependency optional but enabled by default for all and if developer has a special case he can disable it for his risk.

**Comment by Osyotr** [comment]
I think `qt5-websockets/src/src.pro` should be patched (replace qtHaveModule with some other condition and set this condition from vcpkg).

**Comment by JackBoosY** [comment]
cc @Neumann-A for review this PR.

**Comment by Neumann-A** [comment]
> is not so good in my opinion

not patching it is breaking binary caching and thus introduces inconsistencies. Meaning building a/b is not the same as building b/a. This is something vcpkg can not have. Patching is required in this case. (there is a reason i introduced such features in Qt6 and not Qt5.)

**Comment by kafeg** [comment]
Ok, then i will just decline this. Will think about patch later. Thank you.

**Pull request closed without merging**
