### PR TITLE
[ffmpeg] enable windres

### LINKED ISSUE #18775: FFmpeg build doesn't show version info in the DLL files
**Environment**
- OS: Windows 10 64 bit

**Reproduction Path**
`vcpkg.exe install ffmpeg[core,ffmpeg,swresample,swscale,avdevice]:x86-windows`

Installation was successful. And the following dll files are created -
```
vcpkg/installed/x86-windows/bin/avcodec-58.dll
vcpkg/installed/x86-windows/bin/avdevice-58.dll
vcpkg/installed/x86-windows/bin/avfilter-7.dll
vcpkg/installed/x86-windows/bin/avformat-58.dll
vcpkg/installed/x86-windows/bin/avutil-56.dll
vcpkg/installed/x86-windows/bin/swresample-3.dll
vcpkg/installed/x86-windows/bin/swscale-5.dll
```

But there is no version info in the dll files.

avcodec-58

Regardless of version info, FFmpeg works well. No issue with that.

### PR DESCRIPTION
**Pull request by mcmtroffaes**
**Describe the pull request**

- #### What does your PR fix?  
  Fixes #18775. The ffmpeg configure patch was also posted upstream here: http://ffmpeg.org/pipermail/ffmpeg-devel/2021-July/282131.html I also fixed some status messages (not related to the problem but I noticed it, so I snuck it in... hope that's ok).

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  No changes.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes.

### CODE REVIEW

**Comment by mcmtroffaes** [comment]
@iqHpi Can you confirm that this PR fixes the problem for you?

**Comment by mcmtroffaes** [comment]
Although it works on libavutil, on some other libraries it appears to be failing. This might be more complicated than I thought...

**Comment by mcmtroffaes** [comment]
It's been suggested that it would be better to implement support for rc. Since it's broken on postproc, I'll close this for now until a better solution is in place.

**Comment by Neumann-A** [comment]
try using the windres-rc wrapper located at https://github.com/microsoft/vcpkg/blob/master/scripts/buildsystems/make_wrapper/windres-rc

**Comment by mcmtroffaes** [comment]
Ah, I was thinking to see if upstream ffmpeg could support rc natively, but using the wrapper is an interesting alternative. Worth a shot.

**Pull request closed without merging**
