### PR TITLE
More KF5 ports added

### PR DESCRIPTION
**Pull request by NebuHiiEjamu**
Will eventually be adding all dependencies needed to build the Kate text editor that aren't currently ports.

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Looking forward to this PR; Kate is <3

**Comment by NebuHiiEjamu** [comment]
I'm not sure how essential, if at all, the file in bin/data are. I went ahead and removed the *.desktop and *.service files since those are Linux specific, however.

**Comment by ras0219-msft** [comment]
Let me know when you're ready for review & merge here (you seem to still be adding commits :) )

**Comment by NebuHiiEjamu** [comment]
Actually, I think I pretty much did all I can do at the moment. KF5Sonnet is still giving me problems with 'parsetrigrams.exe' failing to generate 'trigrams.map'. I did it manually with the failed build's parsetrigrams.exe and it succeeds, so I'm puzzled at what's going on. KF5Sonnet is needed to get the rest of the ports in to build Kate with.

**Comment by tronical** [comment]
Super awesome to see kde packages in vcpkg :)

**Comment by NebuHiiEjamu** [comment]
Just an update: I may have this done today. I was able to fix the kink with KF5Sonnet and that should pave the way to have the rest of the ports done.

**Comment by NebuHiiEjamu** [comment]
Alright, well, I hit a brick wall. There's a tool KF5CoreAddons installs called desktoptojson.exe. KF5TextEditor, while building, uses desktoptojson to generate a file from kpart.desktop, provided by KF5Parts, and located in the data/kservicetypes5 directory. The problem is that on Windows, QStandardPaths::QGenericDataLocation points to %AppData%\Local or C:\ProgramData, two directories vcpkg can't install files to.

I could patch CMakeLists.txt in KF5TextEditor's source to have the absolute path to it, but I'm not sure if vcpkg CMake vars apply to it, otherwise I could do something like ${VCPKG_ROOT_DIR}/installed/${TARGET_TRIPLET}/data/kservicetypes5/kpart.desktop

**Comment by ras0219-msft** [comment]
@tronical could this be solved by dropping a qt.conf file in the right place?

**Comment by NebuHiiEjamu** [comment]
vcpkg_copy_dependencies DOES put an empty qt.conf file in that has [Paths] header in the contents

**Comment by NebuHiiEjamu** [comment]
Well, for the time being, there's this, but it's separate from vcpkg: https://community.kde.org/Craft

**Comment by NebuHiiEjamu** [comment]
I'm just going to commit what works. I didn't achieve my goal, but I still got a lot of new ports in, so... I'm going to submit this for review.

I think the problem here is VCPkg disallows EXEs in the bin/ path and additional files in the tools/<existing installed port> paths.

**Comment by mattiascibien** [comment]
@NebuHiiEjamu Nice work. Was going to do this myself but did not have much time.

**Comment by NebuHiiEjamu** [comment]
Thanks. It's pretty much ready for review @ras0219-msft. I didn't get it ALL done because the way vcpkg maintains the bin/ directory makes it impossible.

**Comment by patrickelectric** [comment]
can this be merged ?

**Comment by NebuHiiEjamu** [comment]
I've said it's ready for review but none of the repo managers seem to notice and there's no contact info for them.

**Comment by patrickelectric** [comment]
@ras0219 	@ras0219-msft 	Any review ?

**Comment by patrickelectric** [comment]
image

**Comment by patrickelectric** [comment]
@ras0219 @ras0219-msft Any review ?

**Comment by vicroms** [comment]
The original PR branch has been deleted so it is not possible to run a CI build for it.

**Comment by cenit** [comment]
@vicroms there was a small treasure here. I recovered it, but a lot of work must be done in #7075 to put it back on track. Will need help for sure. In the meantime we can close this one if you want

**Comment by NebuHiiEjamu** [comment]
Wait, if I delete my fork after submitting the PR, the PR is lost too?

**Comment by grdowns** [comment]
@NebuHiiEjamu kind of. We are unable to push to the PR branch, so therefore it cannot progress. We would absolutely love to have these changes, so feel free to create another PR! You and @cenit can take useful commits from each other's PR, and that way you will both have your own CI results whenever a change is made. Thanks!

**Comment by cenit** [comment]
I will close my Pr the moment you restore yours. No way I want to hide your work!! I was fearing you were loosing interest in vcpkg due to waiting

**Comment by NebuHiiEjamu** [comment]
Ahh bummer, okay

**Comment by Voskrese** [comment]
@NebuHiiEjamu  keep working on the ports!

**Review by NancyLi1013 — CHANGES_REQUESTED** [review]

**Comment by NancyLi1013** [comment]
Hi @NebuHiiEjamu 
Could you update the requested changes and also update other ports to do the same operations as `editorconfig-core-c` I requested?

**Comment by NancyLi1013** [comment]
Hi @NebuHiiEjamu 
Could you please resolve the conflicts against master and also address the review suggestions? Thanks.

**Comment by NancyLi1013** [comment]
Pinging @NebuHiiEjamu 
Is work still being done for this PR?

**Comment by cenit** [comment]
@NancyLi1013 The original branch is lost, so this PR is unrecoverable. That's why I created #7075...

**Comment by NancyLi1013** [comment]
@cenit  Thanks for your friendly reminder.

@NebuHiiEjamu Closing this PR due to above causes. Please feel free to reopen this if you can continue to do the work for this PR.

Thanks again for your contribuation to vcpkg.

**Pull request closed without merging**
