### PR TITLE
[nanosvg] Update and use upstream CMake

### PR DESCRIPTION
**Pull request by Neumann-A**
+ added patch from fltk to allow for non-square svgs. (you can fight me for this patch but i am not going to add a `fltk-nanosvg` port to vcpkg if it is basically just this addition.)

### CODE REVIEW

**Review by JonLiu1993 — APPROVED** [review]

**Comment by JonLiu1993** [comment]
usage tested successfully by `nanosvg:x64-windows`
````
nanosvg provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(NanoSVG CONFIG REQUIRED)
    target_link_libraries(main PRIVATE NanoSVG::nanosvg NanoSVG::nanosvgrast)
````

**Comment by dan-shaw** [comment]
Has this patch been submitted to upstream?

**Comment by Neumann-A** [comment]
There is https://github.com/memononen/nanosvg/pull/68 which achieves something similar. Since it was created in 2019 I doubt that it will be merged anytime soon so I used the FLTK patch to nanosvg.

**Comment by Neumann-A** [comment]
@JonLiu1993: author-response should be removed

**Pull request merged**
