### PR TITLE
[meson] fix windows linker detection

### PR DESCRIPTION
**Pull request by Neumann-A**
solves:
https://github.com/mesonbuild/meson/issues/9727
https://github.com/mesonbuild/meson/issues/9730

### CODE REVIEW

**Comment by Neumann-A** [comment]
Question: should the meson scripts be moved into `vcpkg-meson` or vcpkg-tool-meson? The former would allow separate versioning of the scripts vs meson but i would assume both a tightly coupled deepening on the features future meson versions support.

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
> Question: should the meson scripts be moved into `vcpkg-meson` or `vcpkg-tool-meson`? The former would allow separate versioning of the scripts vs meson but i would assume both are tightly coupled depending on the features future meson versions support.

Should be moved to `vcpkg-meson`.

**Comment by Neumann-A** [comment]
> Should be moved to vcpkg-meson.

ok for the future. I still don't know how to deal with the possible `pkgconf` dependency. I feel like there needs to be a `vcpkg-meson-script` dependency (without a dep on `pkgconf`) and a `vcpkg-meson` dependency with a dep to `pkgconf` so `pkgconf` itself can use `vcpkg-meson-script`. Cannot add it as a feature since that won't work ;)

**Comment by BillyONeal** [comment]
Thanks for the fix! (I'm kinda taking your word that this is correct since I know very little about meson but I don't see any obvious kittens killed here :) )

**Comment by Neumann-A** [comment]
> I'm kinda taking your word that this is correct since

you can look at the build logs of static builds before and after this change. 
Before it was just calling `lib <args>`
Now with  `ar` being able to be passed to meson it should be calling `<fullpathtolib> <args>` 
I tested this stuff with my custom llvm triplet and it finally works together with meson..... 

> I know very little about meson

i wouldn't call me an expert either. I just know it is riddled with annoying bugs and hasn't learned from other buildsystems.

**Pull request merged**
