### PR TITLE
[mgnlibs][mgnlibs-*] Add new ports

### PR DESCRIPTION
**Pull request by g-e-n-o-s**
Single-file public domain libraries for C/C++

https://github.com/mattiasgustavsson/libs

### CODE REVIEW

**Comment by g-e-n-o-s** [comment]
Should I make separate ports for `libs-app`, `libs-assetsys`, etc?

**Comment by cenit** [comment]
I would avoid the `libs` name. It’s too much generic

**Comment by g-e-n-o-s** [comment]
How about... `mgnlibs`? `mgn` being short for `Mattias Gustavsson`

**Comment by g-e-n-o-s** [comment]
All right should be ready to merge now

**Comment by Rastaban** [comment]
some of the filenames are generic enough that they will probably cause conflicts with other ports.  The most common fix for this is to move them into their own sub-directory under `include`, otherwise the port ends up getting disabled in the CI tests.

Running a full rebuild test to search for conflicts: https://dev.azure.com/vcpkg/public/_build/results?buildId=8913

**Comment by g-e-n-o-s** [comment]
Okay. Which ports do this? (to use as examples to work from :sweat_smile:)

**Comment by Rastaban** [comment]
There are lots of ports that do do this, off the top of my head I think sdl1 would be a good one to look at because it is avoiding a conflict with sdl2.

**Comment by Rastaban** [comment]
Looking at the test results there is a conflict with `inih`.

**Pull request closed without merging**
