### PR TITLE
Use Opus CMake #4875

### LINKED ISSUE #4875: vcpkg install opus arm-uwp
Error: Cannot find definition for package `arm-uwp`

### PR DESCRIPTION
**Pull request by xnorpx**
Use Opus CMake, this will also fix #4875

### CODE REVIEW

**Comment by xnorpx** [comment]
@evpobr @ras0219

**Comment by Rastaban** [comment]
It looks like this fixes build issues on Linux/OSX too!  Do you know when Opus is planning their next official release?

**Comment by evpobr** [comment]
@xnorpx, :+1:

**Comment by xnorpx** [comment]
@Rastaban according to JM it could take a while for 1.4 https://github.com/xiph/opus/issues/110#issuecomment-455311112

"OK, I think I get the problem. Now, the issue I see with your solution is how you handle older versions. You won't ever be able to see query version numbers 1.0 through 1.3 that way. The first you'd be able to query is 1.4 and it's likely more than a year away (could be multiple years). Maybe there's another way -- ideally one that would work for existing versions."

**Pull request merged**
