### PR TITLE
[glib] Add static build support

### LINKED ISSUE #3409: glib:x64-windows-static failing
actually trying to install cairo x64 static, which previously worked

-- CURRENT_PORT_DIR=C:/Users/oli/Dev/vcpkg/ports/glib/.
Glib relies on DllMain and therefore cannot be built statically
CMake Error at C:/Users/oli/Dev/vcpkg/ports/glib/portfile.cmake:13 (message):
  Glib only supports dynamic library and crt linkage

Error: Building package glib:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glib:x64-windows-static
  Vcpkg version: 0.0.110-2018-05-02-1e41c4377f38512d1d6c0d65a2e7b9c7c8b03bea

### PR DESCRIPTION
**Pull request by JackBoosY**
Fixes #3409.

### CODE REVIEW

**Comment by Neumann-A** [comment]
has this been accept upstream?

**Comment by JackBoosY** [comment]
@Neumann-A The changes just suitable for vcpkg.

**Comment by Neumann-A** [comment]
Upstream has some open PRs about that: 
https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1399
https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1454
https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1655

**Comment by proTerm** [comment]
Hello, any progress on this work?

I'm still getting an error?

```
Starting package 6/15: glib:x64-windows-static
Building package glib[core]:x64-windows-static...
-- Note: glib only supports dynamic library linkage. Building dynamic library.
CMake Error at scripts/cmake/vcpkg_check_linkage.cmake:47 (message):
  Refusing to build unexpected dynamic library against the static CRT.  If
  this is desired, please configure your triplet to directly request this
  configuration.
Call Stack (most recent call first):
  ports/glib/portfile.cmake:6 (vcpkg_check_linkage)
  scripts/ports.cmake:142 (include)


Error: Building package glib:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glib:x64-windows-static
  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9
```

**Comment by JackBoosY** [comment]
@proTerm  Yeah... we need to wait for upstream approval.
Close this PR temporary.

**Pull request closed without merging**
