### PR TITLE
Add python2 port

### PR DESCRIPTION
**Pull request by TheAifam5**
This port is based on python3 port.

### CODE REVIEW

**Comment by TheAifam5** [comment]
Is there any blocker which prevents this package to be merged?

**Comment by ras0219-msft** [comment]
No known blockers yet; however we run all PRs through a validation system that still requires a bit of manual verification work (so it can take some time to get to new PRs). Thanks for the PR and thank you for your patience :)!

**Comment by bitsrules** [comment]
Am I supposed to be able to install it like this?
```
vcpkg install python2
vcpkg install boost-python2
vcpkg install boost-python3
```

Thanks!

**Comment by TheAifam5** [comment]
Boost-python should have build dependencies on python packages. Just install boost-python2 and 3 :)

**Comment by damian123** [comment]
So that means I do not need to edit \ports\boost-python\CONTROL to build boost-python2 and 3?
Also I guess I need to install all versions of Python for this to work, i.e. x64 and x86 versions, but I can easily use powershell and choco do that.

**Comment by nato4r** [comment]
Is it possible to link boost-python2 statically but python2.7 dynamically? If so how? Thanks.

**Pull request merged**
