### PR TITLE
[angle] Update to chromium/4758

### PR DESCRIPTION
**Pull request by past-due**
- Update commit to latest on stable chromium/4758 branch
- Generate `angle_commit.h`

**Describe the pull request**

Update the `angle` port (libANGLE) to `chromium/4758` (corresponding to the current Chromium Stable release).

(This follows the recommendations in the libANGLE "[Choosing an ANGLE branch](https://github.com/google/angle/blob/master/doc/ChoosingANGLEBranch.md#matching-a-chromium-release-to-an-angle-branch)" guide, matching the current Chromium Stable 98.0.4758.102.)

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  Same triplets as existing

### CODE REVIEW

**Comment by FrankXie05** [comment]
@past-due Is still work for this PR? I found that the latest branch has been updated to [chromium/4933](https://github.com/google/angle/tree/chromium/4933),  Could you please confirm it?

**Comment by past-due** [comment]
> @past-due Is still work for this PR? I found that the latest branch has been updated to [chromium/4933](https://github.com/google/angle/tree/chromium/4933), Could you please confirm it?

To keep pace with the branch used by the current _stable_ Chromium channel (which is what is recommended in the "[Choosing an ANGLE branch](https://github.com/google/angle/blob/master/doc/ChoosingANGLEBranch.md#matching-a-chromium-release-to-an-angle-branch)" guide), the current would be chromium/4844

I am indeed still working on this PR - just haven't had a chance to take a look at the failing triplets yet.

**Comment by FrankXie05** [comment]
`install-arm-uwp-dbg-out.log`:
```
5>D:\buildtrees\angle\src\378e635a16-98552e68e8.clean\include\CL/cl_dx9_media_sharing.h(38,23): error C2143: syntax error: missing ';' before '*' (compiling source file D:\buildtrees\angle\src\378e635a16-98552e68e8.clean\src\common\PackedCLEnums_autogen.cpp) [D:\buildtrees\angle\arm-uwp-dbg\angle_common.vcxproj]
     5>D:\buildtrees\angle\src\378e635a16-98552e68e8.clean\include\CL/cl_dx9_media_sharing.h(38,23): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file D:\buildtrees\angle\src\378e635a16-98552e68e8.clean\src\common\PackedCLEnums_autogen.cpp) [D:\buildtrees\angle\arm-uwp-dbg\angle_common.vcxproj]
     5>D:\buildtrees\angle\src\378e635a16-98552e68e8.clean\include\CL/cl_dx9_media_sharing.h(38,32): error C2238: unexpected token(s) preceding ';' (compiling source file D:\buildtrees\angle\src\378e635a16-98552e68e8.clean\src\common\PackedCLEnums_autogen.cpp) [D:\buildtrees\angle\arm-uwp-dbg\angle_common.vcxproj]
     5>D:\buildtrees\angle\src\378e635a16-98552e68e8.clean\include\CL/cl_dx9_media_sharing.h(177,5): error C2061: syntax error: identifier 'IDirect3DSurface9' (compiling source file D:\buildtrees\angle\src\378e635a16-98552e68e8.clean\src\common\PackedCLEnums_autogen.cpp) [D:\buildtrees\angle\arm-uwp-dbg\angle_common.vcxproj]
     5>D:\buildtrees\angle\src\378e635a16-98552e68e8.clean\include\CL/cl_dx9_media_sharing.h(185,5): error C2061: syntax error: identifier 'IDirect3DSurface9' (compiling source file D:\buildtrees\angle\src\378e635a16-98552e68e8.clean\src\common\PackedCLEnums_autogen.cpp) [D:\buildtrees\angle\arm-uwp-dbg\angle_common.vcxproj]
     5>C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets(486,5): error MSB4181: The "CompileXaml" task returned false but did not log an error. [D:\buildtrees\angle\arm-uwp-dbg\angle_common.vcxproj]
```
failure log: 
[failure logs for arm-uwp.zip](https://github.com/microsoft/vcpkg/files/8299893/failure.logs.for.arm-uwp.zip)
[failure logs for x64-linux.zip](https://github.com/microsoft/vcpkg/files/8299894/failure.logs.for.x64-linux.zip)
[failure logs for x64-uwp.zip](https://github.com/microsoft/vcpkg/files/8299895/failure.logs.for.x64-uwp.zip)

**Comment by FrankXie05** [comment]
This PR has been inactive for a long time, please reopen it if there is any progress.

**Pull request closed without merging**
