### PR TITLE
[libunibreak] Fixed missing definition of variable in config.cmake

### PR DESCRIPTION
**Pull request by bold84**
**Describe the pull request**

- #### What does your PR fix?
  Sorry about that. I assumed that ${_INSTALL_DIR} was defined by vcpkg. But it actually was defined by another file I included before this one in a project. Now, after testing it isolated, it appeared that ${_INSTALL_DIR} was not defined.
This PR changes that. 

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  all

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by dg0yt** [comment]
You need only one of `_INSTALLED_DIR` and `VCPKG_INSTALLED_DIR` - they should be the same in the end. The first is how config files generally derive the installation prefix, the second is provided by the vcpkg toolchain.
(I prefer the first form, for decoupling the config from vcpkg.)

**Comment by bold84** [comment]
> You need only one of `_INSTALLED_DIR` and `VCPKG_INSTALLED_DIR` - they should be the same in the end. The first is how config files generally derive the installation prefix, the second is provided by the vcpkg toolchain.
> (I prefer the first form, for decoupling the config from vcpkg.)

Thank you for clarification 😊

**Comment by bold84** [comment]
How to solve the "license/cla Expected — Waiting for status to be reported" thing?

**Review by JackBoosY — APPROVED** [review]

**Comment by BillyONeal** [comment]
> How to solve the "license/cla Expected — Waiting for status to be reported" thing?

Sorry, the bot got confused. Close and reopen should kick the bot and fix it

**Comment by BillyONeal** [comment]
Thanks!

**Pull request merged**
