### PR TITLE
[sdl2-gfx] Fixed build error ARM64 Windows 10

### PR DESCRIPTION
**Pull request by shibayan**
Fixed ARM64 build error:

- Add `lrint` function for ARM64 (tested on Surface Pro X)
- Update `ci.baseline.txt`

### CODE REVIEW

**Comment by JackBoosY** [comment]
We want upstream to merge these changes in order to reduce the amount of maintenance code. Can you submit a PR to upstream?

Thanks.

**Comment by JackBoosY** [comment]
Can you open a new issue in vcpkg to describe this error?

Thanks.

**Comment by shibayan** [comment]
Thanks. From now on, I will open an issue before creating a PR.

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
Can you resolve these conflicts?

Thanks.

**Comment by shibayan** [comment]
I resolved conflicts. thanks!

**Comment by JackBoosY** [comment]
@shibayan Can you revert changes to the baseline and make changes again?

Thanks.

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
LGTM, thanks for this PR!

**Pull request merged**
