### PR TITLE
[vcpkg] Add universal builds for macOS

### PR DESCRIPTION
**Pull request by omartijn**
**Describe the pull request**

This yields binaries which work on either platform, making it easier for
end-users, since they don't have to be aware on which architecture they
are running.

- #### What does your PR fix?  
It adds a triplet allowing universal builds on macOS

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
Added `universal-osx` and universal-osx-dynamic`, both as community triplets.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
N/A

### CODE REVIEW

**Comment by autoantwort** [comment]
I think this only works for cmake ports. For example `openssl` is only `arm64` with this triplet

**Comment by omartijn** [comment]
Yes, there are many ports where this won't work. Another example of this was `ffmpeg`, for which a custom build-script was written to enable this functionality. Maybe we can find a way to make this more generic.

Given the number of ports, it's unfeasible to find and fix all of them without adding this triplet as an official triplet, having it run through the CI and then fixing all the ones that fail.

**Review by JackBoosY — APPROVED** [review]

**Review by JonLiu1993 — APPROVED** [review]

**Review by PhoebeHui — APPROVED** [review]

**Review by JonLiu1993 — APPROVED** [review]

**Comment by ras0219-msft** [comment]
This requires a long term strategy for how we intend to handle MacOS universal binaries. This problem is not simple, because we need to consider cases like assembly code, chip-specific optimizations, and fortran.

**Comment by JonLiu1993** [comment]
Draft this PR since it seems that no progress is being made.

**Comment by BillyONeal** [comment]
> This requires a long term strategy for how we intend to handle MacOS universal binaries. This problem is not simple, because we need to consider cases like assembly code, chip-specific optimizations, and fortran.

@JavierMatosD @valeriaconde @ras0219-msft @vicroms and I discussed this today and decided to close this because there is necessary feature work necessary, like what Robert described above. (For example, at a minimum post-build checks need to be fixed to enforce that the output actually contains both architectures so that we aren't 'lying') If you want to continue working in this direction adding things like that will bring this closer to reality.

**Pull request closed without merging**
