### PR TITLE
[vcpkg baseline][physx, omniverse-physx-sdk] Fix conflict

### PR DESCRIPTION
**Pull request by FrankXie05**
PR https://github.com/microsoft/vcpkg/pull/32420 added the new port `omniverse-physx-sdk` cause `physx` build failed on CI pipline, due to `omniverse-physx-sdk` is conflict with `physx`. 

It has been verified locally that these libs are just the same name, but the size and content are different.

The error message:
```
error: The following files are already installed in D:/installed/x64-windows-static and are in conflict with physx:x64-windows-static
Installed by omniverse-physx-sdk:x64-windows-static    
debug/lib/PhysXCharacterKinematic_static_64.lib
    debug/lib/PhysXCommon_static_64.lib
    debug/lib/PhysXCooking_static_64.lib
    debug/lib/PhysXExtensions_static_64.lib
    debug/lib/PhysXFoundation_static_64.lib
    debug/lib/PhysXPvdSDK_static_64.lib
    debug/lib/PhysXVehicle_static_64.lib
    debug/lib/PhysX_static_64.lib
    lib/PhysXCharacterKinematic_static_64.lib
    lib/PhysXCommon_static_64.lib
    lib/PhysXCooking_static_64.lib
    lib/PhysXExtensions_static_64.lib
    lib/PhysXFoundation_static_64.lib
    lib/PhysXPvdSDK_static_64.lib
    lib/PhysXVehicle_static_64.lib
    lib/PhysX_static_64.lib

```

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] ~~SHA512s are updated for each updated download~~
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by dg0yt** [comment]
It is #31506 which added omniverse-physx-sdk.
IIRC there was also a post which explained changed from version 4 (physx) to version 5 (omniverse-physx-sdk).

**Review by LilyWangLL — DISMISSED** [review]

**Comment by marcodiiga** [comment]
Sorry about this, didn't occur me that the generated artifacts could conflict with the previous port (a new one was created because Omniverse PhysX 5 dropped official support for many architectures and the old physx port continued to support them instead).

**Comment by BillyONeal** [comment]
@marcodiiga Can we rename the artifacts so they don't conflict?

**Comment by BillyONeal** [comment]
@FrankXie05 I think we don't want to add any more conflicting libraries now that separate registries exist; we need to pick which one of these is canonical and delist the other, or somehow fix them to coexist. The right fix might be to replace the PhysX port with the new one and tell people 'if you need older architectures use versioning' if we can't make them play nice together.

**Comment by FrankXie05** [comment]
@BillyONeal This makes sense. I would prefer to use the new port instead.

**Comment by FrankXie05** [comment]
Convert to draft for @marcodiiga response.

**Comment by marcodiiga** [comment]
Sorry for the delay. I gave it a try at renaming the various artifacts https://github.com/marcodiiga/vcpkg/commit/42dd67b2784aab6d1d900ae51357bf7029b5ad36
this also included the 3rd party acceleration libraries, it seems that unfortunately this is not enough and the executables crash at startup after using the new libraries (there could be something that silently fails in the upstream repo if a binary is not found).

At this point I don't think we can fix this in the port itself so I would vote for versioning since it seems the right solution to go.

**Comment by Hoikas** [comment]
Please retain PhysX 4. PhysX 5 drops support for multiple platforms, and upstream is not interested in accepting fixes or support for these platforms.

**Comment by BillyONeal** [comment]
@Hoikas

> Please retain PhysX 4. PhysX 5 drops support for multiple platforms, and upstream is not interested in accepting fixes or support for these platforms.

We believe that the nominal owners of a given name in the curated registry should be the upstream maintainers of the component denoted by that name. We aren't able to maintain a clearinghouse where we maintain backports for old platforms. If the maintainers of PhysX don't care to support older platforms, we don't have the resources to provide that support for them.

For a similar example, we updated to OpenSSL 3.x and Threading Building Blocks 2021 despite those releases dropping support for some things, which resulted in removing testing for some downstream ports like usd.

We provide registries, overlays, and versioning support to allow users to override particular selected components if they need to get older versions of things.

**Comment by BillyONeal** [comment]
Replaced by https://github.com/microsoft/vcpkg/pull/32568 . Thanks for the help!

**Pull request closed without merging**
