### PR TITLE
[azure-kinect-sensor-sdk] Remove feature test and fix static build in Windows

### PR DESCRIPTION
**Pull request by JackBoosY**
- Remove feature test due to we don't need it.
- Fix windows-static build failure: cannot find PYTHON3

Related: #9457.

Note: feature tool will fix after #8788 merge, other feature tested successfully in the following triplets:
- x86-windows
- x86-windows-static
- x64-windows
- x64-linux

### CODE REVIEW

**Comment by JackBoosY** [comment]
@vicroms In x86-windows:
```
CMake Error: Could not open file for write in copy operation C:/vsts/_work/3/s/buildtrees/azure-kinect-sensor-sdk/src/11aa54ede6-301103fcfa/src/csharp/VersionInfo.cs.tmp
CMake Error: : System Error: Permission denied
CMake Error at CMakeLists.txt:303 (configure_file):
  configure_file Problem configuring file
```
Could you have a look?

Thanks.

**Review by PhoebeHui — APPROVED** [review]

**Pull request merged**
