### PR TITLE
[openfbx] Update port openfbx to latest version

### PR DESCRIPTION
**Pull request by flarive**
Update vcpkg openfbx to latest

### CODE REVIEW

**Comment by flarive** [comment]
@microsoft-github-policy-service agree [company=""]

**Comment by flarive** [comment]
@microsoft-github-policy-service agree

**Comment by flarive** [comment]
What should i do to fix that, really don't know how to fix failure :(

**Comment by JonLiu1993** [comment]
@flarive, Please run command `./vcpkg x-add-version openfbx` and commit again.

**Comment by JonLiu1993** [comment]
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

**Comment by flarive** [comment]
vcpkg x-add-version openfbx done !

**Comment by flarive** [comment]
Hello @JonLiu1993, i think everything is ok for the review and the merge in master :)

**Review by JonLiu1993 — APPROVED** [review]

**Comment by flarive** [comment]
Thanks for the review @JonLiu1993, i still have the message "Merging is blocked"
(Merge is not an allowed merge method in this repository. This branch must not contain merge commits.)

How can i merge in master ?

**Comment by JonLiu1993** [comment]
> Thanks for the review @JonLiu1993, i still have the message "Merging is blocked" (Merge is not an allowed merge method in this repository. This branch must not contain merge commits.)
> 
> How can i merge in master ?


1. git remote add Upstream https://github.com/Microsoft/vcpkg 
2. git pull Upstream master
3. git push

**Comment by dg0yt** [comment]
@flarive Just wait for the repo owners to merge your PR.

**Comment by JonLiu1993** [comment]
Yes, Just wait for the repo owners to merge your PR.

**Comment by flarive** [comment]
@JavierMatosD , I still see openfbx 2022-07-18 on vcpkg website instead of latest just merged, why ?
 https://vcpkg.io/en/package/openfbx

**Comment by JonLiu1993** [comment]
> @JavierMatosD , I still see openfbx 2022-07-18 on vcpkg website instead of latest just merged, why ? https://vcpkg.io/en/package/openfbx

@flarive, https://vcpkg.io/en/package/openfbx this website is manually updated, not in real time.

**Comment by flarive** [comment]
Ok, but when i add "openfbx" to my vcpkg.json and i recompile my solution, i still have the old openfbx being downloaded to vcpkg_installed, what's the problem, i really don't understand why it takes so much time to have the latest version available and ready to use :(

**Comment by flarive** [comment]
Ah sorry i was not clear may be, i want to use openfbx in a raytracer project i'm working on.


Don't understand why it's so long and so complicated to have up to date packages (ports) on vcpkg :(
One week to have an updated port available is a quite poor user experience to be honest.
Asking developers to contribute to updating ports to latest version is ok (i understand even if Microsoft teams could do the job i suppose), but it would be great to have a much faster and smoother experience to avoid developers worldwide being blocked during one week by the MR/review/deploy painfull process.

So, my question is still quite the same again :
When latest openfbx vcpkg package will be available for download in my raytracer project ?

**Comment by dg0yt** [comment]
When the PR is merged, that version is available. Of course you need to `git pull` and to  update the baseline in your project's manifest.

**Comment by flarive** [comment]
Ok, seems to work now with vcpkg update (not sure) and vcpkg x-update-baseline.
I didn't know i had to do that.
Thanks a lot

**Pull request merged**
