### PR TITLE
[vcpkg baseline][ebml] Remove ebml in ci.baseline.txt

### PR DESCRIPTION
**Pull request by Adela0814**
Fixes vcpkg pipeline issue: 
```
PASSING, REMOVE FROM FAIL LIST: ebml:x64-uwp
PASSING, REMOVE FROM FAIL LIST: ebml:arm-uwp
```
The latest `embl` supports uwp, `!uwp` has been removed from support filed: see https://github.com/microsoft/vcpkg/pull/30750 https://github.com/Matroska-Org/libebml/commit/8bf6c83d759e25b4116f8657f1732f6b63d801ec.

- [ ] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] ~~SHA512s are updated for each updated download~~
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [ ] ~~The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.~~
- [ ] ~~Only one version is added to each modified port's versions file.~~

### CODE REVIEW

**Comment by dg0yt** [comment]
I would recommend to deal with #30756 first, so that CI testing of this PR is hardened against new baseline regressions.

**Comment by robUx4** [comment]
Once #30751 is merged you can do the same with Matroska (if it's in there)

**Comment by dg0yt** [comment]
> Once #30751 is merged you can do the same with Matroska (if it's in there)

@robUx4 Matroska isn't in CI baseline file... You should immediately add the change from this PR to #30786. This is needed to ensure matroska CI runs for uwp.
(There won't be a merge conflict when the changes are identical.)

**Comment by BillyONeal** [comment]
Thanks!

**Pull request merged**
