### PR TITLE
[glib] Update to 2.78.4 (microsoft/vcpkg#36330)

### LINKED ISSUE #36330: [glib] update to 2.78.4
### Library name

glib

### New version number

2.78.4 

### Other information that may be useful (release notes, etc...)

_No response_

### PR DESCRIPTION
**Pull request by SchaichAlonso**
Fixes #36330.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [x] The "supports" clause reflects platforms that may be fixed by this new version.
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by JonLiu1993** [comment]
@SchaichAlonso, the ci bug has been fixed, please merge this PR. Thanks.

**Comment by nlogozzo** [comment]
Hi, any update on this merging?

**Comment by JonLiu1993** [comment]
> @SchaichAlonso, the ci bug has been fixed, please merge this PR. Thanks.

Ping @SchaichAlonso for response, I don’t have permission to merge PR for you.

**Comment by SchaichAlonso** [comment]
> Ping @SchaichAlonso for response, I don’t have permission to merge PR for you.

I don't have merge permissions, either ;)

**Comment by dg0yt** [comment]
@SchaichAlonso I think the current request is to merge vcpkg master into your branch, to update the PR and to trigger a CI run.

**Comment by SchaichAlonso** [comment]
[Another CI issue](https://dev.azure.com/vcpkg/public/_build/results?buildId=99179&view=logs&jobId=c2a18d2e-37ac-57b0-b2a5-926ff10fbe32)

**Comment by JonLiu1993** [comment]
All features are tested successfully in the `x64-linux` triplet.

**Pull request merged**
