### PR TITLE
[vcpkg] Added linux-static target for arm64

### PR DESCRIPTION
**Pull request by samip5**
I'm not exactly sure how these targets should be added and this is at least partly preventing arm64 support on porla.

- https://github.com/porla/porla/issues/103

### CODE REVIEW

**Review by LilyWangLL — DISMISSED** [review]

**Comment by dan-shaw** [comment]
Maybe `arm64-linux-static-release` would be a better name?

**Comment by dg0yt** [comment]
Hm, if the primary use case is building with musl, it might still take a more customized triplet file, e.g. setting `VCPKG_MAKE_BUILD_TRIPLET` to `aarch64-linux-musl` or similar.
https://wiki.musl-libc.org/getting-started.html
https://github.com/richfelker/musl-cross-make/blob/master/README.md

And if there is no general usage except for porla, it could be left to porla to make use of overlay triplets.

> I'm not exactly sure how these targets should be added

https://learn.microsoft.com/en-us/vcpkg/users/triplets#adding-or-replacing-triplets

**Comment by LilyWangLL** [comment]
> Hm, if the primary use case is building with musl, it might still take a more customized triplet file, e.g. setting `VCPKG_MAKE_BUILD_TRIPLET` to `aarch64-linux-musl` or similar. https://wiki.musl-libc.org/getting-started.html https://github.com/richfelker/musl-cross-make/blob/master/README.md
> 
> And if there is no general usage except for porla, it could be left to porla to make use of overlay triplets.
> 
> > I'm not exactly sure how these targets should be added
> 
> https://learn.microsoft.com/en-us/vcpkg/users/triplets#adding-or-replacing-triplets

Pinging author @samip5 for response.

**Comment by samip5** [comment]
Currently it seems porla just uses custom overlays to achieve this so I'm closing this.

**Pull request closed without merging**
