### PR TITLE
[libmt32emu] update to 2.5.0

### LINKED ISSUE #17069: [libmt32emu] update to 2.5.0
**Library name:** libmt32emu

**New version number:** 2.5.0 (tag)

**Other information:**
 - [release notes](https://github.com/munt/munt/blob/1f42d80d9a4f1b0d5a499b783b9c5808c24c1a3e/mt32emu/NEWS.txt)
 - 2.5.0 has been regression tested and confirmed good in DOSBox Staging
 - 2.5.0 supports a new bitwise ROM feature, which has been tested and is planned-for-use in DOSBox Staging.

Thank you, vcpkg team!

### PR DESCRIPTION
**Pull request by autoantwort**
**Describe the pull request**

- What does your PR fix? Fixes  #17069

- Which triplets are supported/not supported? Have you updated the CI baseline? All

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)? Yes

### CODE REVIEW

**Comment by autoantwort** [comment]
This time I got new kinds of pipeline errors :D I request a pipeline rerun :)

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
LGTM, thanks for your PR @autoantwort.

**Comment by ytbigvinny27** [comment]
> This time I got new kinds of pipeline errors :D I request a pipeline rerun :)

And tunnel creator

**Pull request merged**
