### PR TITLE
[aws-sdk-cpp] update to 1.9.331

### LINKED ISSUE #24727: [aws-sdk-cpp] update to 1.9.257
Library name: aws-sdk-cpp

New version number: 1.9.257

The latest changes bring interesting improvements

### PR DESCRIPTION
**Pull request by JonLiu1993**
Fix #24727

Update aws-sdk-cpp to the latest version 1.9.331

All features are tested successfully in the following triplet:
- x86-windows
- x64-windows
- x64-windows-static

### CODE REVIEW

**Comment by JonLiu1993** [comment]
Closing this PR for now I'll reopen it while it's being processed.

**Comment by autoantwort** [comment]
> while it's being processed.

What do you mean by this?

**Comment by JonLiu1993** [comment]
> > while it's being processed.
> 
> What do you mean by this?

I'm temporarily closing this PR but will keep the local branch, when I re-fix this PR I will open it.

**Comment by JonLiu1993** [comment]
Duplicate of https://github.com/microsoft/vcpkg/pull/29236

**Pull request closed without merging**
