### PR TITLE
[vcpkg] create pkg-config files

### LINKED ISSUE #7162: Allow portfile.cmake to get information defined in CONTROL file
It would be great to get the version or other things defined in the CONTROL file to use as a reference to vcpkg_from_github.

Best would be something to get the major, minor and patch version number using vcpkg functions or variables.

### PR DESCRIPTION
**Pull request by isanych**
When I was building non vcpkg Qt using vcpkg dependencies, I was struggling until I created pkg-config files for vcpkg libs, so I decided to automate this process. Change should not affect cmake usage of vcpkg, but help to use vcpkg created libs as non cmake dependencies. As a side effect port version could be used in cmake files, one place less to change during version change process.

`vcpkg_pkgconfig` cmake function generates pkgconfig file, next cmake variables added:
`PORT_FULL_VERSION` - Version from CONTROL file
`PORT_VERSION` - `PORT_FULL_VERSION` without vcpkg version suffix
`PORT_CMAKE_VERSION` - cmake compatible version, 4 version components max, numbers only
`PORT_DESCRIPTION` - Description from CONTROL file
`PORT_HOMEPAGE` - Homepage from CONTROL file
`PORT_DEPENDENCIES` - list of port dependencies

Closes #7162

### CODE REVIEW

**Comment by Voskrese** [comment]
)) windows?

**Comment by isanych** [comment]
> )) windows?

I'm not sure if pkgconfig files are needed on windows, removing 3 lines here - https://github.com/microsoft/vcpkg/blob/8a79337389ff32ad079a1a4895cf11dd386ffbd8/scripts/cmake/vcpkg_pkgconfig.cmake#L49 will create them on windows too

**Comment by Voskrese** [comment]
> I'm not sure if pkgconfig files are needed on windows

meson works tight with pkgconfig

**Comment by isanych** [comment]
> > I'm not sure if pkgconfig files are needed on windows
> 
> meson works tight with pkgconfig

ok, removed windows check - should work on windows too now

**Comment by Voskrese** [comment]
@isanych Игорь, верните, пока vcpkg для виндовс не работает с pkgconfig. я спросил про запас, так сказать на будущее
но вот для примера проект по сборке GTK
https://github.com/wingtk/gvsbuild

там плотно meson + pkgconfig связаны

**Comment by cbezault** [comment]
Closes #7162

**Comment by PhoebeHui** [comment]
@isanych,  Is work still being done for this PR? Could you please resolve the conflicts?

**Comment by isanych** [comment]
@PhoebeHui, ok I'll give it another go - last time build server was failing without obvious reason for me - so I'm just using own branch, but it would be nice to have less differences with upstream

**Comment by isanych** [comment]
@PhoebeHui, could you restart full ci build please, I expecting it to pass now.

**Comment by PhoebeHui** [comment]
@isanych, the CI test failed with following triplets, could you please have a look?

https://dev.azure.com/vcpkg/public/_build/results?buildId=36753&view=results:

|x86-windows      |result|features|notes
|-----------------|----|--------|-----
|idevicerestore   |Fail|core|Test passes in baseline but fails in current run. If expected update ci.baseline.txt with 'idevicerestore:x86-windows=fail'
|jaeger-client-cpp|Fail|core|Test passes in baseline but fails in current run. If expected update ci.baseline.txt with 'jaeger-client-cpp:x86-windows=fail'
|libmediainfo     |Fail|core|Test passes in baseline but fails in current run. If expected update ci.baseline.txt with 'libmediainfo:x86-windows=fail'

|x64-windows      |result|features|notes
|-----------------|----|--------|-----
|idevicerestore   |Fail|core|Test passes in baseline but fails in current run. If expected update ci.baseline.txt with 'idevicerestore:x64-windows=fail'
|jaeger-client-cpp|Fail|core|Test passes in baseline but fails in current run. If expected update ci.baseline.txt with 'jaeger-client-cpp:x64-windows=fail'
|libmediainfo     |Fail|core|Test passes in baseline but fails in current run. If expected update ci.baseline.txt with 'libmediainfo:x64-windows=fail'


|x64-windows-static|result|features|notes
|------------------|----|--------|-----
|jaeger-client-cpp |Fail|core|Test passes in baseline but fails in current run. If expected update ci.baseline.txt with 'jaeger-client-cpp:x64-windows-static=fail'
|libmediainfo      |Fail|core|Test passes in baseline but fails in current run. If expected update ci.baseline.txt with 'libmediainfo:x64-windows-static=fail'

|x64-uwp     |result|features|notes
|------------|----|--------|-----
|libmediainfo|Fail|core|Test passes in baseline but fails in current run. If expected update ci.baseline.txt with 'libmediainfo:x64-uwp=fail'

|arm64-windows|result|features|notes
|-------------|----|--------|-----
|libmediainfo |Fail|core|Test passes in baseline but fails in current run. If expected update ci.baseline.txt with 'libmediainfo:arm64-windows=fail'

|x64-linux|result|features|notes
|---------|----|--------|-----
|blosc    |Fail|core|Test passes in baseline but fails in current run. If expected update ci.baseline.txt with 'blosc:x64-linux=fail'

**Comment by isanych** [comment]
@PhoebeHui, build server complains about packages which it does not attempt to build, and all my attempts to trigger full build have failed. My understanding that CI tries to rebuilt only affected packages and system does not work well when there are changes in vcpkg sources and not in ports.

**Comment by PhoebeHui** [comment]
@isanych, I test the changes locally, and it failed with following failure, it looks a vcpkg bug in this change:

PS F:\vcpkg\7129\vcpkg> ./vcpkg install libmediainfo
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
Computing installation plan...
The following packages will be built and installed:
  * curl[core,non-http,ssl,sspi,winssl]:x86-windows
    libmediainfo[core]:x86-windows
  * libzen[core]:x86-windows
  * zlib[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/4: zlib:x86-windows
Building package zlib[core]:x86-windows...
CMake Error at scripts/ports.cmake:47 (message):
  Unsupported target triplet.  Triplet file does not exist:
  F:vcpkg7129vcpkgtripletsx86-windows.cmake

**Comment by isanych** [comment]
@PhoebeHui, thank you - I see the issue, I'm passing description (beside other variables) to cmake - `blosc` has backticks there which was causing shell attempt to execute sting between them - so I've removed dangerous characters, but went too far there as I've done that for all cmake variables - will do it for description field only

**Comment by cbezault** [comment]
If you truly want a full-rebuild modifying the `vcpkg_fixup_cmake_targets.cmake` file will do it. See https://github.com/microsoft/vcpkg/pull/10420/commits/4dd67c2536084ef940fa40420df8d4c5c9bbde8d.

**Comment by isanych** [comment]
@cbezault full rebuild helped thank you
@PhoebeHui issues which supposed to be gone are gone now, from latest failures I could only reproduce llvm on windows and parallelstl , but they are failing on master too, not sure what are my next steps should be

**Comment by PhoebeHui** [comment]
The failures on x86-windows doesn't related to this change, @isanych, could you also update the Version in CONTROL file in related ports?

I will ask team member help to do feature review.

**Comment by PhoebeHui** [comment]
@isanych, could you please resolve the conflicts?

@strega-nil, could you help review this feature?

**Pull request closed without merging**
