### PR TITLE
[qt5] Fix mac build

### PR DESCRIPTION
**Pull request by seanwarren**
This PR allows qt5 to be build on mac

### CODE REVIEW

**Comment by seanwarren** [comment]
Hi, could you let me know what is failing please? 
Is there somewhere I can check this myself?

**Comment by vicroms** [comment]
Sorry, it failed due to an unrelated problem with our CI infrastructure.
I'll trigger a new build.

At the moment, build logs are not public.
We're working on a solution to make relevant build logs available.

**Comment by Rastaban** [comment]
With this change we are seeing regressions on windows with most ports that depend on qt5-base.  On Linux the build is doing something that causes the test VM to become unresponsive and the Azure DevOps agent connection times out so I don't have any results.  The qt5-base build on OSX was skipped, usually this is because one of its dependencies failed.  I will see if I can figure out which one it is.

**Comment by seanwarren** [comment]
I believe the regressions on windows are now resolved. For me, PR #5359 is required for building on linux

**Comment by TheScarfix** [comment]
@seanwarren is qt5 building for you on Linux? because if it is my PR #5364 might become obsolete

**Comment by seanwarren** [comment]
@TheScarfix yes qt5 builds on linux using this PR (although per #4560 qt-declarative fails with a static build)

**Comment by seanwarren** [comment]
Hello, please could I have an update on whats failing in the CI system

**Comment by vicroms** [comment]
I've got good news 👼 

```
Processing x64-linux                      630 vs 617
     qt5-charts                                                  Pass vs Fail
     qt5-connectivity                                            Pass vs Fail
     qt5-datavis3d                                               Pass vs Fail
     qt5-gamepad                                                 Pass vs Fail
     qt5-imageformats                                            Pass vs Fail
     qt5-networkauth                                             Pass vs Fail
     qt5-script                                                  Pass vs Fail
     qt5-serialport                                              Pass vs Fail
     qt5-speech                                                  Pass vs Fail
     qt5-svg                                                     Pass vs Fail
     qt5-virtualkeyboard                                         Pass vs Fail
     qt5-webchannel                                              Pass vs Fail
     qt5-websockets                                              Pass vs Fail
```

And bad news 👿 
```
 Processing x64-osx                        611 vs 611
 Processing x64-uwp                        441 vs 441
```

**There are no regressions on Mac, but also no improvements** (still failing)

```
 Processing x64-windows                    854 vs 887
     libqglviewer                  **regression**                Fail vs Pass
     qscintilla                    **regression**                Fail vs Pass
     qt5                                                         Skip vs Pass
     qt5-3d                                                      Skip vs Pass
     qt5-activeqt                  **regression**                Fail vs Pass
     qt5-charts                    **regression**                Fail vs Pass
     qt5-connectivity              **regression**                Fail vs Pass
     qt5-datavis3d                 **regression**                Fail vs Pass
     qt5-declarative               **regression**                Fail vs Pass
     qt5-gamepad                   **regression**                Fail vs Pass
     qt5-graphicaleffects                                        Skip vs Pass
     qt5-imageformats              **regression**                Fail vs Pass
     qt5-location                                                Skip vs Pass
     qt5-multimedia                                              Skip vs Pass
     qt5-networkauth               **regression**                Fail vs Pass
     qt5-purchasing                **regression**                Fail vs Pass
     qt5-quickcontrols                                           Skip vs Pass
     qt5-quickcontrols2                                          Skip vs Pass
     qt5-remoteobjects             **regression**                Fail vs Pass
     qt5-script                    **regression**                Fail vs Pass
     qt5-scxml                                                   Skip vs Pass
     qt5-sensors                   **regression**                Fail vs Pass
     qt5-serialport                **regression**                Fail vs Pass
     qt5-speech                    **regression**                Fail vs Pass
     qt5-svg                       **regression**                Fail vs Pass
     qt5-tools                                                   Skip vs Pass
     qt5-virtualkeyboard           **regression**                Fail vs Pass
     qt5-webchannel                **regression**                Fail vs Pass
     qt5-websockets                **regression**                Fail vs Pass
     qt5-webview                                                 Skip vs Pass
     qt5-winextras                 **regression**                Fail vs Pass
     qt5-xmlpatterns               **regression**                Fail vs Pass
     qwt                                                         Skip vs Pass
 Processing x64-windows-static             765 vs 781
     qscintilla                    **regression**                Fail vs Pass
     qt5-charts                    **regression**                Fail vs Pass
     qt5-connectivity              **regression**                Fail vs Pass
     qt5-datavis3d                 **regression**                Fail vs Pass
     qt5-gamepad                   **regression**                Fail vs Pass
     qt5-imageformats              **regression**                Fail vs Pass
     qt5-networkauth               **regression**                Fail vs Pass
     qt5-script                    **regression**                Fail vs Pass
     qt5-sensors                   **regression**                Fail vs Pass
     qt5-serialport                **regression**                Fail vs Pass
     qt5-speech                    **regression**                Fail vs Pass
     qt5-svg                       **regression**                Fail vs Pass
     qt5-virtualkeyboard           **regression**                Fail vs Pass
     qt5-webchannel                **regression**                Fail vs Pass
     qt5-websockets                **regression**                Fail vs Pass
     qt5-winextras                 **regression**                Fail vs Pass
Processing x86-windows                    834 vs 867
     libqglviewer                  **regression**                Fail vs Pass
     qscintilla                    **regression**                Fail vs Pass
     qt5                                                         Skip vs Pass
     qt5-3d                                                      Skip vs Pass
     qt5-activeqt                  **regression**                Fail vs Pass
     qt5-charts                    **regression**                Fail vs Pass
     qt5-connectivity              **regression**                Fail vs Pass
     qt5-datavis3d                 **regression**                Fail vs Pass
     qt5-declarative               **regression**                Fail vs Pass
     qt5-gamepad                   **regression**                Fail vs Pass
     qt5-graphicaleffects                                        Skip vs Pass
     qt5-imageformats              **regression**                Fail vs Pass
     qt5-location                                                Skip vs Pass
     qt5-multimedia                                              Skip vs Pass
     qt5-networkauth               **regression**                Fail vs Pass
     qt5-purchasing                **regression**                Fail vs Pass
     qt5-quickcontrols                                           Skip vs Pass
     qt5-quickcontrols2                                          Skip vs Pass
     qt5-remoteobjects             **regression**                Fail vs Pass
     qt5-script                    **regression**                Fail vs Pass
     qt5-scxml                                                   Skip vs Pass
     qt5-sensors                   **regression**                Fail vs Pass
     qt5-serialport                **regression**                Fail vs Pass
     qt5-speech                    **regression**                Fail vs Pass
     qt5-svg                       **regression**                Fail vs Pass
     qt5-tools                                                   Skip vs Pass
     qt5-virtualkeyboard           **regression**                Fail vs Pass
     qt5-webchannel                **regression**                Fail vs Pass
     qt5-websockets                **regression**                Fail vs Pass
     qt5-webview                                                 Skip vs Pass
     qt5-winextras                 **regression**                Fail vs Pass
     qt5-xmlpatterns               **regression**                Fail vs Pass
     qwt                                                         Skip vs Pass
```     

Give me a moment to pull the relevant failure logs.

**Comment by seanwarren** [comment]
@vicroms, thanks for the update. Are these logs build including commit 992b2beaaa03f94cb50498559ae506965777bd38 , which should have resolved that error?

**Comment by vicroms** [comment]
The commit is included, but the ports didn't get rebuilt after that change so they're reported as still failing.

Our CI only rebuilds packages that have been changed, as that commit didn't modify any port, then nothing got rebuilt and reports the previous failure.

I've added a whitespace to `qt5-base` that should trigger a rebuild of all Qt related packages.

**Comment by seanwarren** [comment]
Ah yes of course. OK will bear in find for future reference

**Comment by vicroms** [comment]
Here are the build results:

```
Processing x64-linux                      631 vs 618
    qt5-charts                                                  Pass vs Fail
    qt5-connectivity                                            Pass vs Fail
    qt5-datavis3d                                               Pass vs Fail
    qt5-gamepad                                                 Pass vs Fail
    qt5-imageformats                                            Pass vs Fail
    qt5-networkauth                                             Pass vs Fail
    qt5-script                                                  Pass vs Fail
    qt5-serialport                                              Pass vs Fail
    qt5-speech                                                  Pass vs Fail
    qt5-svg                                                     Pass vs Fail
    qt5-virtualkeyboard                                         Pass vs Fail
    qt5-webchannel                                              Pass vs Fail
    qt5-websockets                                              Pass vs Fail
```

I still don't see any new builds passing on Mac. 
I noticed that `qt5-base` was skipped, and the only dependency I found to have problems was `harfbuzz` (which was also skipped). I'm investigating why `harfbuzz` was skipped for Mac.

**Comment by seanwarren** [comment]
OK it looks like the `harfbuzz` update to 2.3.1 broke the mac build due to an unused variable warning and the use of `-Werror`. I've pushed a patch which removes the offending lines (which were `if(false) {}`'d out anyway)

Sorry about the CONTROL versions - I've bumped `qt5-base` now

**Comment by seanwarren** [comment]
The build of `harfbuzz` is now fixed on mac, however Qt seems to have a problem linking to this new version and falls over on some tests during the configure stage. 

Since `harfbuzz` is an optional component I have disabled this on the mac build in the interest of getting something working

**Comment by Rastaban** [comment]
This is what I now see in the CI system:

```
Processing x64-osx                        628 vs 612
    cutelyst2                                                   Fail vs Skip
    libqglviewer                                                Fail vs Skip
    qca                                                         Fail vs Skip
    qscintilla                                                  Fail vs Skip
    qt5-activeqt                                                Fail vs Skip
    qt5-base                                                    Pass vs Skip
    qt5-charts                                                  Pass vs Skip
    qt5-connectivity                                            Pass vs Skip
    qt5-datavis3d                                               Pass vs Skip
    qt5-declarative                                             Fail vs Skip
    qt5-gamepad                                                 Pass vs Skip
    qt5-imageformats                                            Pass vs Skip
    qt5-networkauth                                             Pass vs Skip
    qt5-purchasing                                              Fail vs Skip
    qt5-remoteobjects                                           Fail vs Skip
    qt5-script                                                  Pass vs Skip
    qt5-sensors                                                 Pass vs Skip
    qt5-serialport                                              Pass vs Skip
    qt5-speech                                                  Pass vs Skip
    qt5-svg                                                     Pass vs Skip
    qt5-virtualkeyboard                                         Pass vs Skip
    qt5-webchannel                                              Pass vs Skip
    qt5-websockets                                              Pass vs Skip
    qt5-xmlpatterns                                             Pass vs Skip
```

The build failures in the list are not considered regressions because they were previously being skipped so we could accept this PR even with those failures.  However you are on a roll, are you interested in investigating these failures as part of this PR?

**Comment by seanwarren** [comment]
I think `qt-declarative` might be a bit more complex than I have time for (see #4560), I'll have a quick look at the others

**Comment by seanwarren** [comment]
I think I can resolve most of these failures, however some of the fixes might need discussion.
Is it ok if we merge this PR as-is and I'll open another one for the other failures?
Cheers

**Pull request merged**
