### PR TITLE
[openblas] make openblas build on MinGW

### LINKED ISSUE #21146: [openblas:arm64-uwp\openblas:arm-uwp] build failure
**Host Environment**
- OS: Windows 10
- Compiler: MSVC 2019

**To Reproduce**
` .\vcpkg\vcpkg.exe install openblas:arm64-uwp`

**Failure logs** 

Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  package: openblas[core]:arm64-uwp -> 0.3.15
  vcpkg version: 2021-10-25-b4bff9afacafb0a234a8f20fd6451b2362c0f9a0
  vcpkg-tool version: 85b31152d 2021-11-02 (6 hours ago)

**Additional context**

CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: ninja -v
    Working Directory: D:/vcpkg/buildtrees/openblas/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\vcpkg\buildtrees\openblas\config-x64-windows-out.log

[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/7464752/config-x64-windows-out.log)

### PR DESCRIPTION
**Pull request by ChristopherSchwartzXRITE**
- #### What does your PR fix?  
  Fixes building openblas on MinGW on Windows.  
  The MinGW build using GCC seems to require the same explicit build flags as the non-windows systems, but it the `VCPKG_TARGET_IS_WINDOWS` will be set to true. Adding the extra check for `NOT VCPKG_TARGET_IS_MINGW` will make the portfile use the working set of build flags.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all + mingw, no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  yes

Tested with x64-mingw-static and x64-mingw-dynamic on Windows.

### CODE REVIEW

**Review by NancyLi1013 — COMMENTED** [review]
```
vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    FEATURES
        threads         USE_THREAD
        simplethread    USE_SIMPLE_THREADED_LEVEL3
)
vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    FEATURES
    	"dynamic-arch"      DYNAMIC_ARCH
)

```
Could you please add the features in one `vcpkg_check_features`?

**Comment by JackBoosY** [comment]
> `vcpkg_check_features` doesn't care for the original value of the output variable, so the second call overwrites `FEATURE_OPTIONS`.
> 
> #18265, merged 11 Jun, added the first call, and it added the passing of `FEATURE_OPTIONS` to `vcpkg_configure_cmake` _for `VCPKG_TARGET_IS_UWP` only_.
> 
> #15238, merged 26 Jul, added the second call, and it added the passing of `FEATURE_OPTIONS` to `vcpkg_configure_cmake` _for `VCPKG_TARGET_IS_WINDOWS` only_.
> 
> With two calls, the threading options are lost, and the DYNAMIC_ARCH option is passed to UWP and Windows. With the merged call, threading options and DYNAMIC_ARCH are passed to both UWP and Windows.
> 
> Now what was the intention? What about non-windows targets?

`vcpkg_check_features` should only be called once, #18265 is my mistake.

**Comment by ChristopherSchwartzXRITE** [comment]
Thanks for sorting this out and fixing the broken uwp build @JackBoosY!

**Comment by JackBoosY** [comment]
```
[10/660] /usr/bin/c++ -DH5_BUILT_AS_STATIC_LIB -I/mnt/vcpkg-ci/buildtrees/shogun/src/b686d6e1cc-534b82672e.clean/src -I/mnt/vcpkg-ci/buildtrees/shogun/x64-linux-dbg/src -I/mnt/vcpkg-ci/installed/x64-linux/include/libxml2 -isystem /mnt/vcpkg-ci/installed/x64-linux/include/eigen3 -isystem /mnt/vcpkg-ci/installed/x64-linux/include -Wall -Wno-unused-parameter -Wformat -Wformat-security -Wparentheses -Wshadow -Wno-unknown-pragmas -Wno-deprecated -fPIC -g -fPIC -gsplit-dwarf -std=c++11 -MD -MT src/shogun/CMakeFiles/libshogun.dir/classifier/svm/NewtonSVM.cpp.o -MF src/shogun/CMakeFiles/libshogun.dir/classifier/svm/NewtonSVM.cpp.o.d -o src/shogun/CMakeFiles/libshogun.dir/classifier/svm/NewtonSVM.cpp.o -c /mnt/vcpkg-ci/buildtrees/shogun/src/b686d6e1cc-534b82672e.clean/src/shogun/classifier/svm/NewtonSVM.cpp
FAILED: src/shogun/CMakeFiles/libshogun.dir/classifier/svm/NewtonSVM.cpp.o 
/usr/bin/c++ -DH5_BUILT_AS_STATIC_LIB -I/mnt/vcpkg-ci/buildtrees/shogun/src/b686d6e1cc-534b82672e.clean/src -I/mnt/vcpkg-ci/buildtrees/shogun/x64-linux-dbg/src -I/mnt/vcpkg-ci/installed/x64-linux/include/libxml2 -isystem /mnt/vcpkg-ci/installed/x64-linux/include/eigen3 -isystem /mnt/vcpkg-ci/installed/x64-linux/include -Wall -Wno-unused-parameter -Wformat -Wformat-security -Wparentheses -Wshadow -Wno-unknown-pragmas -Wno-deprecated -fPIC -g -fPIC -gsplit-dwarf -std=c++11 -MD -MT src/shogun/CMakeFiles/libshogun.dir/classifier/svm/NewtonSVM.cpp.o -MF src/shogun/CMakeFiles/libshogun.dir/classifier/svm/NewtonSVM.cpp.o.d -o src/shogun/CMakeFiles/libshogun.dir/classifier/svm/NewtonSVM.cpp.o -c /mnt/vcpkg-ci/buildtrees/shogun/src/b686d6e1cc-534b82672e.clean/src/shogun/classifier/svm/NewtonSVM.cpp
In file included from /mnt/vcpkg-ci/buildtrees/shogun/src/b686d6e1cc-534b82672e.clean/src/shogun/classifier/svm/NewtonSVM.cpp:20:
/mnt/vcpkg-ci/buildtrees/shogun/src/b686d6e1cc-534b82672e.clean/src/shogun/mathematics/lapack.h:41:10: fatal error: cblas.h: No such file or directory
   41 | #include <cblas.h>
      |          ^~~~~~~~~
compilation terminated.
```

Seems shogun select cblas instead of openblas.

**Comment by ChristopherSchwartzXRITE** [comment]
> Seems shogun select cblas instead of openblas.

This issue seems to persist.

I noticed that shogun is skipped for ci builds for all other plaforms except for linux in the ci.baseline.txt.
@NancyLi1013 Should I just add another line, `shogun:x64-linux = skip` to the file within the scope of this PR so that we can move on?

**Comment by JackBoosY** [comment]
> > Seems shogun select cblas instead of openblas.
> 
> This issue seems to persist.
> 
> I noticed that shogun is skipped for ci builds for all other plaforms except for linux in the ci.baseline.txt. @NancyLi1013 Should I just add another line `shogun:x64-linux = skip` to the file within the scope of this PR so that we can move on?

Nope, we should completly solve it in this PR.
I will take a look in next week.

**Comment by JackBoosY** [comment]
I can't repro this issue because shogun found cblas.h in _/usr/include/x86_64-linux-gnu/_.
Now it should be okay.

**Comment by ChristopherSchwartzXRITE** [comment]
> I can't repro this issue because shogun found cblas.h in _/usr/include/x86_64-linux-gnu/_. The reason why it happend is the header `cblas.h` is removed into _include/openblas_. @ChristopherSchwartzXRITE Can you confirm whether this change was made by upstream? Now it should be okay.

To me it looks as if the behavior to install `cblas.h` into _include/openblas/_ instead of _include_ was a change in the OpenBLAS repo in October 2018.
See lines 295 and 296 in the diff https://github.com/xianyi/OpenBLAS/commit/474f7e9583a85630345458abb71b7246def3f10f#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR295.

I'm wondering why it wasn't noticed sooner 🤔 .

**Review by JackBoosY — APPROVED** [review]

**Pull request merged**
