### PR TITLE
Switch ci from arm-uwp to arm64-uwp

### PR DESCRIPTION
**Pull request by autoantwort**
Fixes https://github.com/microsoft/vcpkg/discussions/33481

### CODE REVIEW

**Comment by autoantwort** [comment]
> Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(457,5): error MSB8020: The build tools for 'v143' application Type UWP (Platform Toolset = 'v143') cannot be found. Please install the workflow for this application type and include the build tools for the  [D:\buildtrees\libvpx\arm64-uwp-rel\vpx.vcxproj]

Seems that the VS Installation is "incomplete".

**Comment by walbourn** [comment]
All the UWP C++ toolsets are 'optional installs' for Visual Studio. The CI machine needs to have `Microsoft.VisualStudio.Component.VC.Tools.ARM64` and `Microsoft.VisualStudio.Component.UWP.VC.ARM64` installed.

**Comment by autoantwort** [comment]
https://github.com/microsoft/vcpkg/blob/4a600e9fea71bd7872080cbb716797e04d30e6d3/scripts/azure-pipelines/windows/deploy-visual-studio.ps1#L9-L31
It seems that `Microsoft.VisualStudio.Component.UWP.VC.ARM64` is missing

**Comment by BillyONeal** [comment]
@ras0219-msft @AugP @dan-shaw @vicroms and I discussed this today and we are happy with the replacing `arm-uwp` with `arm64-uwp`.

**Comment by BillyONeal** [comment]
Closing because this was merged into https://github.com/microsoft/vcpkg/pull/33759 , thanks!

**Pull request closed without merging**
