### PR TITLE
 _

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by JuttaAnders** [comment]
@Rastaban my first fix [https://github.com/Microsoft/vcpkg/pull/5885/commits/4d16626370d8bc4625e38a6c306447827428930e](https://github.com/Microsoft/vcpkg/pull/5885/commits/4d16626370d8bc4625e38a6c306447827428930e) seems not to work: Vcpkg-PR-Eager — #2545859 failed (but I cannot see the log)
Can I do something about that?

**Comment by Rastaban** [comment]
@JuttaAnders, it looks like the Azure Devops build for the first commit was canceled so it may not have actually failed.  When it canceled it deleted the logs though, so I am unable to confirm that.  This usually happens when another commit is added to a PR before the first test has completed.

**Comment by JuttaAnders** [comment]
@Rastaban thanks for the explanantion.
I was trying to fix static builds for SD1 and LIBWEBP.
If this pull request contains both commit, then it should fix both ports at onece.
Could you try to merge these changes?

**Comment by cenit** [comment]
I’d add a message if you disable feature because of static linking... also libwebp[all] works in static...?

**Comment by JuttaAnders** [comment]
@cenit Which features am I disabling?
Concerning SDL1 the idea is to patch the vcxproj files because they are not correctly set for static building.
Concerning LIBWEBP I added an extra check that prevent the build of the example/tools/whatever exe because - if I remember correctly - the build system complained that there should be no exe files in a static build

**Comment by cenit** [comment]
libwebp[all] is not just tools. It is also an extended more functional lib if I remember exactly.
Of course in static no exe must survive in the bin folder, but also in dynamic this is true and the port is ready to do that (on win, not on Linux/Mac because the issue survived the PR in which we discussed it).

**Comment by cenit** [comment]
(It would be just a matter of converting `.exe` in a dynamic symbol)

**Comment by JuttaAnders** [comment]
@cenit feel free to modify the port.cmake to match your needs ... this pull request is anyway not (yet) merged, so libwebp is untouched

**Pull request closed without merging**
