### PR TITLE
[vcpkg] Update cmake 3.20.4 hash

### PR DESCRIPTION
**Pull request by ghost**
**Describe the pull request**

- #### What does your PR fix?  
  Fixes freebsd cmake hash mismatch issue (?, looks like it was updated for some reason)

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
yes

### CODE REVIEW

**Review by autoantwort — APPROVED** [review]

**Comment by Hoikas** [comment]
Doesn't vcpkg require 3.21 for ports.cmake?

**Comment by InfRandomness** [comment]
> Doesn't vcpkg require 3.21 for ports.cmake?

yes, it does, but that version isn't available as of right now on freebsd, unfortunately

**Review by PhoebeHui — APPROVED** [review]
@InfRandomness, thanks for your fix!

**Comment by ras0219-msft** [comment]
LGTM, though if this URL is not bit-stable over time we will need to find another source for the package.

**Pull request merged**
