### PR TITLE
[vcpkg_backup_env_variables] use CACHE INTERNAL instead of PARENT_SCOPE

### PR DESCRIPTION
**Pull request by csabasipos89**
…PE variables to be able to restore them

**Describe the pull request**

[z_vcpkg_setup_pkgconfig_path](https://github.com/microsoft/vcpkg/blob/83eb3d3d136f751b0562e1219d391575fdf9fe73/scripts/cmake/z_vcpkg_setup_pkgconfig_path.cmake#L1) does not backup PKG_CONFIG and PKG_CONFIG_PATH variables, because [vcpkg_backup_env_variables](https://github.com/microsoft/vcpkg/blob/83eb3d3d136f751b0562e1219d391575fdf9fe73/scripts/cmake/vcpkg_backup_restore_env_vars.cmake#L1) works only if the restore part is called from where the backup was called, which is not the case here. These functions are used in lots of configure scripts but they are not doing what they are intended to do. 
To reproduce the problem, I made a simple port which uses these functions: [git@github.com:csabasipos89/vcpkg_test_ports.git.](https://github.com/csabasipos89/vcpkg_test_ports/tree/main/test-env-variable-save-restore)

- #### What does your PR fix?
In  [vcpkg_backup_env_variables](https://github.com/microsoft/vcpkg/blob/83eb3d3d136f751b0562e1219d391575fdf9fe73/scripts/cmake/vcpkg_backup_restore_env_vars.cmake#L1) instead of using parent scope variables, now it uses a stack like implementation, implemented with lists, to backup and restore environment variables

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  all 

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  `Yes`

### CODE REVIEW

**Comment by csabasipos89** [comment]
I see now, I just solved one problem and created others, didn't think about nested calls, but with PARENT_SCOPE set, https://github.com/microsoft/vcpkg/blob/e2794913924ef606cc7bbc59c173f2714e9853c5/scripts/cmake/z_vcpkg_setup_pkgconfig_path.cmake#L1 and https://github.com/microsoft/vcpkg/blob/e2794913924ef606cc7bbc59c173f2714e9853c5/scripts/cmake/z_vcpkg_setup_pkgconfig_path.cmake#L28  duo is not working properly, it will always remove the content of PKG_CONFIG PKG_CONFIG_PATH environment variables, because the backups will be available in z_vcpkg_setup_pkgconfig_path scope, not in the calling function, I think.

z_vcpkg_setup_pkgconfig_path/z_vcpkg_restore_pkgconfig_path used in multiple location. 

Could be the solution to make one of z_vcpkg_setup_pkgconfig_path/z_vcpkg_restore_pkgconfig_path or vcpkg_backup_env_variables/vcpkg_restore_env_variables to be macros instead of functions?

**Comment by dg0yt** [comment]
> Could be the solution to make one of z_vcpkg_setup_pkgconfig_path/z_vcpkg_restore_pkgconfig_path or vcpkg_backup_env_variables/vcpkg_restore_env_variables to be macros instead of functions?

I don't think macros are the solution. This would bring *all* local variables into what is now the parent scope.

But these functions are probably hard to use correctly. I think you should go one step back and start with reporting the original problem so that it can be reproduced und understood.

**Comment by csabasipos89** [comment]
> I don't think macros are the solution. This would bring _all_ local variables into what is now the parent scope.
> 

Yes, you are right, I am trying to find a good solution but none came to my mind :(

> But these functions are probably hard to use correctly. I think you should go one step back and start with reporting the original problem so that it can be reproduced und understood.

I agree.

**Comment by csabasipos89** [comment]
> The cache is global, so this will break nested (i.e. scoped) backup and restore.

I just made some changes, fixed the nested problem implementing a stack like behavior. 
Also created a test example port which is using z_vcpkg_setup_pkgconfig_path  and z_vcpkg_restore_pkgconfig_path to backup and restore PKG_CONFIG and PKG_CONFIG_PATH environment variables, you can find it here: git@github.com:csabasipos89/vcpkg_test_ports.git. The test can also be used to reproduce the issue.

Tested on windows and Ubuntu 18.04

**Comment by Neumann-A** [comment]
Is there a reason you didn't update this PR then?

**Comment by csabasipos89** [comment]
> Is there a reason you didn't update this PR then?

Pushed the new version yesterday and updated the PR description just now

**Comment by dg0yt** [comment]
Your change assumes balanced backup/restore. But AFAICT the original code is meant to do the "right" thing with unbalanced usage, i.e. one single backup and even multiple restores per scope. This is used in 
https://github.com/microsoft/vcpkg/blob/bde216bf73eaf88c62acef2c46e301908d2900f0/scripts/cmake/vcpkg_build_make.cmake#L69
https://github.com/microsoft/vcpkg/blob/bde216bf73eaf88c62acef2c46e301908d2900f0/scripts/cmake/vcpkg_build_make.cmake#L180
(And I did ask for balanced usage in reviewing that change, but I couldn't get my message through.)

**Comment by csabasipos89** [comment]
> Your change assumes balanced backup/restore. But AFAICT the original code is meant to do the "right" thing with unbalanced usage, i.e. one single backup and even multiple restores per scope. 

@dg0yt  I am sorry, I didn't know about the unbalanced usage. Anyway, I think something needs to be done to fix [z_vcpkg_setup_pkgconfig_path](https://github.com/microsoft/vcpkg/blob/83eb3d3d136f751b0562e1219d391575fdf9fe73/scripts/cmake/z_vcpkg_setup_pkgconfig_path.cmake#L1)/restore functions, because in the current state they are not working. Do you think I should drop this pull request and leave the fix to someone who has better understanding of these functions and their design or do you have any suggestion?

**Comment by dg0yt** [comment]
I don't want really to defend the curent code, but the vcpkg maintainers integrated it just like that.

> in the current state they are not working.

These are internal functions, and AFAICT they work were they are used internally now. This doesn't mean they work as you need it externally, in your portfile.

> Do you think I should drop this pull request and leave the fix to someone who has better understanding of these functions and their design or do you have any suggestion?

I don't care much who implements changes. My experience is that if you want a change soon, you have to provide the change.
But I do care about the side effects of such changes, and that's why such function should be complemented by test cases IMO. These functions don't have them yet, and that's why is difficult to realize what is expected, what is broken now, and what is broken with the changes you introduce.
I do understand that this raises the barrier for contributions, but OTOH most tests that were added paid off quite quickly.

**Comment by csabasipos89** [comment]
> These are internal functions, and AFAICT they work were they are used internally now. This doesn't mean they work as you need it externally, in your portfile.

I understand, but if you take a look at [z_vcpkg_setup_pkgconfig_path](https://github.com/microsoft/vcpkg/blob/83eb3d3d136f751b0562e1219d391575fdf9fe73/scripts/cmake/z_vcpkg_setup_pkgconfig_path.cmake#L1) function there is a call to vcpkg_backup_env_variables(VARS PKG_CONFIG PKG_CONFIG_PATH), but there is no restore after that on the same level, which means, when the function exits, the backups  are gone, with the current behavior. When [z_vcpkg_restore_pkgconfig_path](https://github.com/microsoft/vcpkg/blob/83eb3d3d136f751b0562e1219d391575fdf9fe73/scripts/cmake/z_vcpkg_setup_pkgconfig_path.cmake#L28) is called, there is nothing to restore and the variables will be unset. Maybe that is not causing any problem now internally, because PKG_CONFIG and PKG_CONFIG_PATH environment variables are not set when these functions are called, but when they will be expected to be backed up and restored, it won't work. 

these functions are used at least in 3 places: 

* [vcpkg_configure_make](https://github.com/microsoft/vcpkg/blob/72fa4d4630c0971eadea7d0a70045351ab13be9d/scripts/cmake/vcpkg_configure_make.cmake#L663)
* [vcpkg_configure_meson](https://github.com/microsoft/vcpkg/blob/72fa4d4630c0971eadea7d0a70045351ab13be9d/scripts/cmake/vcpkg_configure_meson.cmake#L422)
* [vcpkg_configure_qmake](https://github.com/microsoft/vcpkg/blob/72fa4d4630c0971eadea7d0a70045351ab13be9d/scripts/cmake/vcpkg_configure_qmake.cmake#L32)

**Comment by dg0yt** [comment]
> I understand, but if you take a look at [z_vcpkg_setup_pkgconfig_path](https://github.com/microsoft/vcpkg/blob/83eb3d3d136f751b0562e1219d391575fdf9fe73/scripts/cmake/z_vcpkg_setup_pkgconfig_path.cmake#L1) function there is a call to vcpkg_backup_env_variables(VARS PKG_CONFIG PKG_CONFIG_PATH), but there is no restore after that on the same level, which means, when the function exits, the backups are gone, with the current behavior.

Indeed. Now we have a description of the issue. My attempt at it: #25361

**Comment by dg0yt** [comment]
#25361 was merged.
This PR should be withdrawn, or it should be updated: There are basic unit tests for `vcpkg_backup/restore_env_vars` now.

**Comment by csabasipos89** [comment]
@dg0yt Thank you very much for the fix, I will close this now.

**Pull request closed without merging**
