### PR TITLE
[opencv] update portfiles to use vcpkg-get-python-packages

### PR DESCRIPTION
**Pull request by cenit**
- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  all, yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  yes

### CODE REVIEW

**Comment by Neumann-A** [comment]
Probably needs a small change to `vcpkg-get-python-packages` to get rid of the annoying warnings about `LOGNAME` needing to be set.

**Comment by Neumann-A** [comment]
osx and linux will require changes to the vm setup scripts. Seems like the ports are currently installing stuff on the users systems which shouldn't be done.

**Comment by cenit** [comment]
> osx and linux will require changes to the vm setup scripts. Seems like the ports are currently installing stuff on the users systems which shouldn't be done.  

that's why I wanted to move to common tool scripts, to be sure that python was doing something approved. I will fix the pr asap. Is there no way to have a local python installation on *nix like we have on win? It should be the best option to have automatic package installation also there without modifying user land

**Comment by Neumann-A** [comment]
> Is there no way to have a local python installation on *nix like we have on win? 

There is no portable binary for *nix. We could use virtual env somehow but don't ask me about how that works.

**Comment by cenit** [comment]
@BillyONeal should i remove python from vcpkg-ci-python or should i modify the minting script so that *nix images contain numpy?

**Comment by Neumann-A** [comment]
Maybe: https://github.com/microsoft/vcpkg/issues/24058#issuecomment-1094129428. Seem like `tensorflow-common` is already using venv. So may we could simply copy over its behavior?

**Comment by Neumann-A** [comment]
merged this into #24041 to see if the a venv python setup works.

**Comment by BillyONeal** [comment]
> @BillyONeal should i remove python from vcpkg-ci-opencv or should i modify the minting script so that *nix images contain numpy?

Unfortunately I know absolutely nothing about Python :(

**Comment by Neumann-A** [comment]
@BillyONeal approach in #24041 setting up a virtual env seems to be working.

**Comment by cenit** [comment]
without touching user land?

**Comment by cenit** [comment]
and messages are clear about what to install if missing? sorry for being so pedantic

**Comment by Neumann-A** [comment]
> and messages are clear about what to install if missing? sorry for being so pedantic

I hope so since *unix defaults are already good. https://github.com/microsoft/vcpkg/pull/24041 has been merged so this can probably be closed.

**Pull request closed without merging**
