### PR TITLE
[vcpkg_build_nmake] Fix /MP -> /FS transformation

### PR DESCRIPTION
**Pull request by dg0yt**
https://github.com/microsoft/vcpkg/issues/41796#issuecomment-2440178727

### CODE REVIEW

**Review by jimwang118 — APPROVED** [review]

**Comment by jimwang118** [comment]
Add reviewed tag for further review by the vcpkg team.

**Comment by dg0yt** [comment]
> @[jimwang118](https://github.com/jimwang118) removed the[ info:reviewed ](https://github.com/microsoft/vcpkg/labels/info%3Areviewed)label [Oct 30, 2024](https://github.com/microsoft/vcpkg/pull/41815#event-14994222712)

Why?

**Comment by jimwang118** [comment]
Wait for CI to turn green.

**Comment by dg0yt** [comment]
> Wait for CI to turn green.

Well, this is recorded in the PR anyways, as "required" check.

**Comment by aboelens** [comment]
I am seeing:
````
2024-10-30T11:08:31.4656223Z Building gperftools:x64-linux@2.10#1...
2024-10-30T11:08:31.4837933Z -- Downloading https://github.com/gperftools/gperftools/archive/gperftools-2.10.tar.gz -> gperftools-gperftools-gperftools-2.10.tar.gz...
2024-10-30T11:08:31.9152252Z -- Extracting source /mnt/vcpkg-ci/downloads/gperftools-gperftools-gperftools-2.10.tar.gz
2024-10-30T11:08:31.9462859Z -- Using source at /mnt/vcpkg-ci/b/gperftools/src/tools-2.10-f6f5d5bdde.clean
2024-10-30T11:08:31.9525727Z -- Getting CMake variables for x64-linux-dbg
2024-10-30T11:08:32.3421316Z -- Getting CMake variables for x64-linux-rel
2024-10-30T11:08:32.7216015Z -- Generating configure for x64-linux
2024-10-30T11:08:41.7021079Z -- Finished generating configure for x64-linux
2024-10-30T11:08:41.7109412Z -- Configuring x64-linux-dbg
2024-10-30T11:08:48.9316964Z -- Configuring x64-linux-rel
2024-10-30T11:08:56.4059418Z -- Building x64-linux-dbg
2024-10-30T11:08:59.7480656Z CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
2024-10-30T11:08:59.7481844Z     Command failed: /usr/bin/make V=1 -j 33 -f Makefile all
2024-10-30T11:08:59.7482241Z     Working Directory: /mnt/vcpkg-ci/b/gperftools/x64-linux-dbg/
2024-10-30T11:08:59.7485010Z     See logs for more information:
2024-10-30T11:08:59.7485719Z       /mnt/vcpkg-ci/b/gperftools/build-x64-linux-dbg-out.log
2024-10-30T11:08:59.7486169Z       /mnt/vcpkg-ci/b/gperftools/build-x64-linux-dbg-err.log
2024-10-30T11:08:59.7486389Z 
2024-10-30T11:08:59.7488481Z Call Stack (most recent call first):
2024-10-30T11:08:59.7489003Z   scripts/cmake/vcpkg_build_make.cmake:136 (vcpkg_execute_build_process)
2024-10-30T11:08:59.7489367Z   scripts/cmake/vcpkg_install_make.cmake:2 (vcpkg_build_make)
2024-10-30T11:08:59.7490210Z   ports/gperftools/portfile.cmake:64 (vcpkg_install_make)
2024-10-30T11:08:59.7490538Z   scripts/ports.cmake:192 (include)
2024-10-30T11:08:59.7492259Z 
2024-10-30T11:08:59.7492603Z 
2024-10-30T11:08:59.8054201Z error: building gperftools:x64-linux failed with: BUILD_FAILED
2024-10-30T11:08:59.8055271Z See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
2024-10-30T11:08:59.8055791Z Elapsed time to handle gperftools:x64-linux: 28 s
```
Is it possible to access the files "/mnt/vcpkg-ci/b/gperftools/build-x64-linux-dbg-out.log" and "/mnt/vcpkg-ci/b/gperftools/build-x64-linux-dbg-err.log" to see what went wrong?

**Comment by dg0yt** [comment]
> Is it possible to access the files "/mnt/vcpkg-ci/b/gperftools/build-x64-linux-dbg-out.log" and "/mnt/vcpkg-ci/b/gperftools/build-x64-linux-dbg-err.log" to see what went wrong?

Sure, the logs are in the CI run's assets. I use that every day...

... but the x64-linux error is entirely unrelated to MSVC and nmake. An installation order bug.

Reviewers, don't wait for x64-linux fixes before proceeding with this PR.

**Comment by dg0yt** [comment]
Unrelated CI failure, fixed by #42017.

**Comment by dg0yt** [comment]
All checks green, as before the unreated regressions, as expected.

**Pull request merged**
