### PR TITLE
Added spanish readme

### PR DESCRIPTION
**Pull request by UnixY2K**
This Pull Request is the same as #13068, 
however, it includes the corrections made in the previous PR and slight corrections in the readme.

- What does your PR fix?
It does not fix anything, just add a new translation of the main readme

- Which triplets are supported/not supported? Have you updated the CI baseline?
N/A, as it is just a new readme

### CODE REVIEW

**Comment by JackBoosY** [comment]
I am completely powerless for this PR...

**Review by vicroms — APPROVED** [review]
¡Gracias por la traducción!

**Pull request merged**
