### PR TITLE
[3fd] Initial port of 3FD project

### PR DESCRIPTION
**Pull request by faburaya**
Initial port of 3FD to vcpkg. Currently, the project does not support building with static linkage to CRT. The user is expected to create its own tripplet specifying dynamic linkage to CRT and static linkage to the library itself. The only supported platform so far is Windows, because it depends on POCO that currently does not build successfully by vcpkg in Linux.

### CODE REVIEW

**Comment by faburaya** [comment]
Project being merged:
https://github.com/faburaya/3fd

**Comment by ras0219-msft** [comment]
Thanks for the PR!

While merging, I made a few tweaks and fixes:
- I fixed `vcpkg_build_msbuild()` to actually give you the current triplet instead of some other triplet (oops!)
- I hit a compile error when using the latest VS2017, but it's a really simple fix (see patch)
- We conventionally _do_ allow ports that can only build statically to be built that way in dynamic triplets -- the "non-negotiable" setting is the CRT linkage for obvious reasons :)
- Generally, use `STREQUAL` over `MATCHES`; for example, I don't believe you intended to map `arm64` to `ARM` :)
- Added build-from-clean every time to ensure we don't accidentally leak bits between builds
- Windows desktop maps to `VCPKG_CMAKE_SYSTEM_NAME` _not_ being set, so I took advantage of that to explicitly add errors for all other settings

Thanks again for the PR and for exercising some lesser-used pieces! If you're interested, I'd love to chat a bit at vcpkg@microsoft.com about your experience packaging your own library :)

**Comment by faburaya** [comment]
Great, Robert. Thanks for you service in open source!
Yes, I can write about my experience to vcpkg@microsoft.com
Should I use some reference number in the message subject for identification?

**Comment by ras0219-msft** [comment]
Sure, if you could just throw `PR #3811` in there that would be great!

**Pull request merged**
