### PR TITLE
[ffmpeg] Fixed build error ARM64 Windows 10

### PR DESCRIPTION
**Pull request by shibayan**
- Update to latest `gas-preprocessor.pl`
- Fixed cmake permission argument (#8660)

### CODE REVIEW

**Review by cbezault — APPROVED** [review]

**Comment by cbezault** [comment]
This looks good to me but I'm going to re-trigger an ffmpeg build to make sure.

**Comment by cbezault** [comment]
Looks like ffmpeg still failed to build.

**Comment by shibayan** [comment]
It seems that osx build was canceled, but what log should I look at for ffmpeg CI build errors?

**Comment by shibayan** [comment]
Sorry. I checked the build log.

I updated gas-preprocessor.pl, but it seems that an error occurred trying to always use the cache on CI.
It seems to be caused by always saving with the same name.

**Comment by cbezault** [comment]
Yeah the OSX CI is in the process of getting moved over to better/more hardware which is why it was canceled. Yes you are right, the cached file is getting used instead of your new one :/

**Comment by vicroms** [comment]
Hi @shibayan 

The `ARCHIVE` should have the version as part of the name to avoid caching issue (e.g.: `gas-preprocessor-b5ea3a5.pl`).

You can use a `POST_INSTALL_COMMAND` to rename it back to `gas-preprocessor.pl` after the download.  
Example:

https://github.com/microsoft/vcpkg/blob/b66d9ab380d0451ae9955f83f7d62d87a67130bc/scripts/cmake/vcpkg_find_acquire_program.cmake#L91-L100

**Comment by shibayan** [comment]
@vicroms Thanks! Added a fix to avoid cache effects.
In my environment, the cache was not affected and the gas-preprocessor was updated.

**Comment by cbezault** [comment]
@vicroms, the tombstone needs to get removed again to test his changes.

**Comment by vicroms** [comment]
Looks good to me

**Pull request merged**
