### PR TITLE
[upb] Disable pointer alignment assertion in upb.h

### PR DESCRIPTION
**Pull request by heinrichWeichert**
**Describe the pull request**

- #### What does your PR fix?
 Already fixed in third-party/upb in the port `grpc`, a "misaligned" pointer in Windows will crash in upb.h. This is commented out.
The crash occurred arbitrarily during RCP calls.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
Unknown/no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
 Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  n/a

### CODE REVIEW

**Comment by Cheney-W** [comment]
Please modify the `ports/upb/vcpkg.json` as below:
```
{
  "name": "upb",
  "version-date": "2022-04-04",
  "port-version": 1,
  "description": "μpb (often written 'upb') is a small protobuf implementation written in C.",
```
`git add .`
`git commit -m "xxx"`
then run `./vcpkg x-add-version upb`
`git add .`
`git commit -m "xxx"`

**Comment by heinrichWeichert** [comment]
> Please modify the `ports/upb/vcpkg.json` as below:
> 
> ```
> {
>   "name": "upb",
>   "version-date": "2022-04-04",
>   "port-version": 1,
>   "description": "μpb (often written 'upb') is a small protobuf implementation written in C.",
> ```
> 
> `git add .` `git commit -m "xxx"` then run `./vcpkg x-add-version upb` `git add .` `git commit -m "xxx"`

Thanks for the hint, I hope it's OK now

**Comment by Cheney-W** [comment]
If there is nothing to modify, please click `Ready for review`.

**Comment by dan-shaw** [comment]
Can this fix be submitted upstream?

**Comment by Cheney-W** [comment]
Upstream has deleted the commented out statement above in commit https://github.com/protocolbuffers/upb/commit/e4635f223e7d36dfbea3b722a4ca4807a7e882e2#diff-badc965f22bfefa2a15596baaaf222a7c50c89319f64b463ae0e71a8a01a1cad

**Comment by heinrichWeichert** [comment]
> Can this fix be submitted upstream?

The patch is based on an older version and the newer versions don't have the same code.

**Comment by heinrichWeichert** [comment]
> Upstream has deleted the commented out statement above in commit [protocolbuffers/upb@e4635f2#diff-badc965f22bfefa2a15596baaaf222a7c50c89319f64b463ae0e71a8a01a1cad](https://github.com/protocolbuffers/upb/commit/e4635f223e7d36dfbea3b722a4ca4807a7e882e2#diff-badc965f22bfefa2a15596baaaf222a7c50c89319f64b463ae0e71a8a01a1cad)

But the release in vcpkg is older, so the code does not match. Do you mean I should rather just delete the line instead of commenting it out?

**Comment by Cheney-W** [comment]
No, I just wanted to show that it's OK for this statement to be commented.

**Comment by dan-shaw** [comment]
Since this library is around 5 months out of date, I would prefer if we updated the library instead. I would like to minimize the number of patches we have to maintain if possible.

**Comment by heinrichWeichert** [comment]
Fine with me, but I don't know when I'll come around to it

**Comment by Cheney-W** [comment]
Pinging @heinrichWeichert  for response. Is work still being done for this PR?

**Comment by heinrichWeichert** [comment]
> Pinging @heinrichWeichert for response. Is work still being done for this PR?

Currently, closing due to lack of time, sorry

**Pull request closed without merging**
