### PR TITLE
[pthreads]Add usage.

### PR DESCRIPTION
**Pull request by JackBoosY**
Related: #6169.

### CODE REVIEW

**Comment by cenit** [comment]
why not the "modern" target?

**Comment by JackBoosY** [comment]
llvm build failure is fake.

**Comment by cenit** [comment]
instead of suggesting the old library & include symbols, which *I* wrote for backwards compatibility, why not using PThreads4W::PThreads4W, PThreads4W::PThreads4W_CXXEXC and PThreads4W::PThreads4W_STRUCTEXC modern cmake targets, that's what I meant

**Comment by JackBoosY** [comment]
@cenit I hope that pthreads can completely replace pthread in windows, just like using `FindThreads.cmake` to use ` vcpkg_cmake_wrapper.cmake`.
And confirmed, we don't need to add `CONFIG` in `find_package`.

If we use namespace, we may need to set the namespace to export it, but it is now built using makefile.

**Comment by cenit** [comment]
note that you should not use all of the three targets together. They are mutually exclusive, depending on what you need as a threading platform/capabilities :)

not sure on what you mean with
> I hope that pthreads can completely replace pthread in windows,

**Comment by JackBoosY** [comment]
> not sure on what you mean with
I hope that pthreads can completely replace pthread in windows,

Never mind this.

**Review by PhoebeHui — APPROVED** [review]

**Comment by cenit** [comment]
Last note: of course when using modern targets there is no need to do an explicit target_include_directories ;)

**Comment by JackBoosY** [comment]
@vicroms ready to merge now. Just add usage.

**Pull request merged**
