### PR TITLE
Add libxslt

### PR DESCRIPTION
**Pull request by muemart**
Added a port for libxslt. I had to fix libxml2 in the process because of the new CRT checks.

### CODE REVIEW

**Comment by alexkaratarakis** [comment]
This looks good. 
I noticed all builds are being done in the same folder. For example, both debug and release are in the same folder. Can you change the builds to be in different folders?

In general, portfiles use:
`${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel` for release
`${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-dbg` for debug

This also makes builds from different triplets be placed in different folders. To see how this would look like, you can do:
`vcpkg install zlib zlib:x86-windows-static`
and then check the `buildtrees\zlib` folder. You will see:
`src\`, `x86-windows-dbg\`, `x86-windows-rel\`, `x86-windows-static-dbg\`, `x86-windows-static-rel\`

If out-of-source builds are not supported, then it is fine to copy paste the sources in each folder as necessary. 


This will also fix the pdb warning that the build emits. Since the builds are stomping on top of each other, only the pdbs of the last build are available and `vcpkg` warns that it cannot find the pdbs for all the dlls.

**Comment by alexkaratarakis** [comment]
Alternatively, a quick and easy solution would be to just copy the pdbs after each build, before they get overwritten by the next build.

**Comment by muemart** [comment]
I patched the makefile to support different output directories. The release builds didn't generate debug symbols, so I fixed that too while I was at it.

**Comment by alexkaratarakis** [comment]
I see the directories being created, but it doesn't look like the build is actually done in them.
Did a commit not get pushed perhaps?
(also pdbs are missing, but this is probably because the above step didn't work)

Also, I have merged the `libxml2` fixes.

**Comment by muemart** [comment]
Hm, it works for me and I have no local changes. Sounds like the patch wasn't applied, maybe it works if you delete the buildtree and try again?

**Comment by alexkaratarakis** [comment]
You are right, cleaning up `buildtrees` and it worked. My bad.
Merging this, thanks for the solid work!

On a side note, we have some work in progress about applying patches that will (among other things) prevent things like not-having-patches-applied from being an issue.

**Pull request merged**
