### PR TITLE
[wolfssl] Build wolfssl with HAVE_EX_DATA and NO_WOLFSSL_STUB to enable async use and coexistence with openssl without link error

### PR DESCRIPTION
**Pull request by ycdev1**
Async applications using wolfssl need to associate extra data (application context) with the ssl session and context. This is used in verification callback.
NO_WOLFSSL_STUB is needed to prevent a link time error resulting from duplicate symbols when linking to both wolfssl and openssl at the same time

### CODE REVIEW

**Comment by ycdev1** [comment]
@microsoft-github-policy-service agree

**Comment by MonicaLiu0311** [comment]
* Missing edit of `vcpkg.json` file:
When there is an upstream version update, please edit the `"version" : "x.x.x"`, such as: [38664/files](https://github.com/microsoft/vcpkg/pull/38664/files); when there is no upstream version update, please edit the `"port-version": x`, which is a field used internally by vcpkg for recording, such as: [31055/files](https://github.com/microsoft/vcpkg/pull/31055/files).

* Submit changes.
* Run `./vcpkg x-add-version portName [--overwrite-version]` to generate version information.
* Push.

**Comment by MonicaLiu0311** [comment]
Note: I will be converting your PR to draft status. When you're ready, please revert to "ready for review".

**Comment by MonicaLiu0311** [comment]
Ping @ycdev1

**Pull request closed without merging**
