### PR TITLE
[New port] Add Triton port

### PR DESCRIPTION
**Pull request by illera88**
**Describe the pull request**
This PR adds support for [Triton](https://github.com/JonathanSalwan/Triton)

- #### What does your PR fix?  
Lack of  Triton port
- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
All

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
Yes
- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
 Yes

### CODE REVIEW

**Comment by illera88** [comment]
Hi @NancyLi1013 
I've tried again to port Triton to vcpkg. I made all the changes you suggested at https://github.com/microsoft/vcpkg/pull/17224

Can you give me a hand here. How can I see the output error in the CI to know what went wrong?

Thank you

**Comment by JonLiu1993** [comment]
@illera88 ,Thanks for your pr, 
This is _D:\buildtrees\triton\install-x64-windows-static-dbg-out.log_
[install-x64-windows-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/8076358/install-x64-windows-static-dbg-out.log)

For other log files, you can click on the button I circled in yellow step by step to get the log you want

1. https://dev.azure.com/vcpkg/public/_build/results?buildId=67464&view=logs&j=878666d5-db33-5b27-9e7d-b0c7ee352005

image

2. https://dev.azure.com/vcpkg/public/_build/results?buildId=67464&view=artifacts&pathAsName=false&type=publishedArtifacts

image

**Comment by illera88** [comment]
> @illera88 ,Thanks for your pr, This is _D:\buildtrees\triton\install-x64-windows-static-dbg-out.log_ [install-x64-windows-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/8076358/install-x64-windows-static-dbg-out.log)
> 
> For other log files, you can click on the button I circled in yellow step by step to get the log you want
> 
> 1. https://dev.azure.com/vcpkg/public/_build/results?buildId=67464&view=logs&j=878666d5-db33-5b27-9e7d-b0c7ee352005
> 
> image
> 
> 2. https://dev.azure.com/vcpkg/public/_build/results?buildId=67464&view=artifacts&pathAsName=false&type=publishedArtifacts
> 
> image

thanks! I'll get into it

**Comment by illera88** [comment]
The error is weird:
it's complaining about not finding `capston`:
```
externalLibs.hpp(38): fatal error C1083: Cannot open include file: 'capstone.h': No such file or directory
```
but `capstone` is being added to the include path:
```
 -IC:\a\1\s\installed\x64-windows-static\include\capstone 
```

@JonLiu1993 do you have any idea why this can be happening?

**Comment by illera88** [comment]
Hi @JackBoosY,

Maybe you know what could be failing.

thank you so much

**Comment by JackBoosY** [comment]
The Config.cmake.in also needs to be fixed.

**Comment by JackBoosY** [comment]
```
[51/59] : && /Library/Developer/CommandLineTools/usr/bin/c++ -pthread -g -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names -static src/examples/cpp/CMakeFiles/ir.dir/ir.cpp.o -o src/examples/cpp/ir  src/libtriton/libtriton.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libz3.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libcapstone.a && :
FAILED: src/examples/cpp/ir 
: && /Library/Developer/CommandLineTools/usr/bin/c++ -pthread -g -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names -static src/examples/cpp/CMakeFiles/ir.dir/ir.cpp.o -o src/examples/cpp/ir  src/libtriton/libtriton.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libz3.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libcapstone.a && :
ld: library not found for -lcrt0.o
```
No idea where `crt0.o` comes from.

**Comment by JackBoosY** [comment]
This port still have some cmake bugs, we should wait for the upstream to fix them completely.

**Comment by illera88** [comment]
Hi @JackBoosY 👋 

I hope you had a good weekend.

I think the upstream problems have been solved at this point.

**Comment by JackBoosY** [comment]
I will update this PR later.

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
When building `triton[*]:x86-windows`:
```
[1/81] "C:\PROGRA~2\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x86\cl.exe"   /TP -DBUILDING_DLL -DG:/23111/vcpkg/installed/x86-windows/debug/lib/python310_d.lib" -DG:/23111/vcpkg/installed/x86-windows/lib/python310.lib -DPYTHON_LIBRARIES=\"optimized -Ddebug -Dtriton_EXPORTS -IG:\23111\vcpkg\installed\x86-windows\include\python3.10 -IG:\23111\vcpkg\installed\x86-windows\include\capstone -IG:\23111\vcpkg\buildtrees\triton\src\14e2382e7a-dbfc11990e.clean\src\libtriton\includes -IG:\23111\vcpkg\buildtrees\triton\x86-windows-dbg\src\libtriton\includes -IG:\23111\vcpkg\installed\x86-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -MDd /showIncludes /Fosrc\libtriton\CMakeFiles\triton.dir\api\api.cpp.obj /Fdsrc\libtriton\CMakeFiles\triton.dir\ /FS -c G:\23111\vcpkg\buildtrees\triton\src\14e2382e7a-dbfc11990e.clean\src\libtriton\api\api.cpp
FAILED: src/libtriton/CMakeFiles/triton.dir/api/api.cpp.obj 
"C:\PROGRA~2\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x86\cl.exe"   /TP -DBUILDING_DLL -DG:/23111/vcpkg/installed/x86-windows/debug/lib/python310_d.lib" -DG:/23111/vcpkg/installed/x86-windows/lib/python310.lib -DPYTHON_LIBRARIES=\"optimized -Ddebug -Dtriton_EXPORTS -IG:\23111\vcpkg\installed\x86-windows\include\python3.10 -IG:\23111\vcpkg\installed\x86-windows\include\capstone -IG:\23111\vcpkg\buildtrees\triton\src\14e2382e7a-dbfc11990e.clean\src\libtriton\includes -IG:\23111\vcpkg\buildtrees\triton\x86-windows-dbg\src\libtriton\includes -IG:\23111\vcpkg\installed\x86-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -MDd /showIncludes /Fosrc\libtriton\CMakeFiles\triton.dir\api\api.cpp.obj /Fdsrc\libtriton\CMakeFiles\triton.dir\ /FS -c G:\23111\vcpkg\buildtrees\triton\src\14e2382e7a-dbfc11990e.clean\src\libtriton\api\api.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27045 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.
```

Any ideas?

**Comment by JackBoosY** [comment]
Already test all features in x86-windows and x64-windows-static.

**Comment by illera88** [comment]
Hi @JackBoosY 

I made a change to the code so capstone is required to be installed with:

```json
{
      "name": "capstone",
      "default-features": false,
      "features": [
        "arm",
        "arm64",
        "static-crt",
        "x86"
      ]
    },
```
`static-crt` capstone feature has not yet been merged into main but it is on its way. So please don't merge until that's done so we can test it properly.

[Here ](https://github.com/microsoft/vcpkg/pull/23122) is the PR to add `static-crt` to Capstone for reference.

**Comment by illera88** [comment]
Hi @JackBoosY 

I think now it is ready

**Comment by JonLiu1993** [comment]
All features are tested successfully in the following triplet:
- x86-windows
- x64-windows
- x64-windows-static

**Comment by illera88** [comment]
Hi @JackBoosY and @JonLiu1993 

I think this port is not working. When adding to CMakelists.txt:
```
 find_package(triton CONFIG REQUIRED)
```

It ends up with:
```
CMake Error at C:/Users/user/Documents/code/vcpkg/installed/x64-windows-static/share/triton/tritonConfig.cmake:53 (include_directories):
  include_directories given empty-string as include directory.
Call Stack (most recent call first):
  C:/Users/user/Documents/code/vcpkg/scripts/buildsystems/vcpkg.cmake:782 (_find_package)
  CMakeLists.txt:17 (find_package)
```

If I check `C:/Users/user/Documents/code/vcpkg/installed/x64-windows-static/share/triton/tritonConfig.cmake:53 `
I can see:

```
# Z3 include directories
if (TRITON_Z3_INTERFACE)
    include_directories("")
endif()
```

Who creates `tritonConfig.cmake`? Why are the Z3 include directories empty?

Thanks

**Pull request merged**
