### PR TITLE
[pcre] fix build pcre undeclared identifier strtoq on arm-android

### PR DESCRIPTION
**Pull request by tqcq**
* replace CHECK_FUNCTION_EXISTS by CHECK_SYMBOL_EXISTS

**Describe the pull request**

- #### What does your PR fix?
  - fix build pcre on arm-android error. (replace  CheckFunctionExists by CheckSymbolExists.)
  - [#17600](https://github.com/microsoft/vcpkg/issues/17600)

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  `unchanged`, `No`

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  `Yes`

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by tqcq** [comment]
Hello @BillyONeal , I am trying to fix a pcre build problem, can you help me review these codes.

**Comment by BillyONeal** [comment]
Has this patch been submitted upstream? (Can you point to the submission?)

Otherwise this looks good to me.

**Comment by tqcq** [comment]
> Has this patch been submitted upstream? (Can you point to the submission?)
> 
> Otherwise this looks good to me.

This is just a patch for version 8.45. It was not submitted upstream.

The older, but still widely deployed PCRE library, originally released in 1997, is at version 8.45. (Reference [https://www.pcre.org/](https://www.pcre.org/))
so

**Comment by tqcq** [comment]
> Can you point to the submission?)

```cmake
CHECK_FUNCTION_EXISTS: symbol links (defined)
CHECK_SYMBOL_EXISTS: symbol available (declared and defined)
```
Therefore, CHECK_SYMBOL_EXISTS should be used here to ensure that the symbol exists

**Review by Adela0814 — APPROVED** [review]

**Comment by BillyONeal** [comment]
> Therefore, CHECK_SYMBOL_EXISTS should be used here to ensure that the symbol exists

I'm not saying it's a bad patch, but when it's a patch that isn't specific to something vcpkg does we generally try to make sure upstream knows about it.

(1) This means that when they issue a new version they may have this fixed which allows us to remove the patch.
(2) This ensures that we don't apply patches upstream doesn't *disagree* with.

I'm less worried about (2) given that this is a minor build system detection change which generally isn't going to change the outcome.

**Comment by BillyONeal** [comment]
Ah, I see, upstream says there will never be another release in this series so notifying them about a build system fix is largely irrelevant, OK.

Maybe we should consider updating the port to 10.x but that's of course unrelated to this change.

**Comment by BillyONeal** [comment]
Thanks for the fix!

**Comment by Neumann-A** [comment]
> Maybe we should consider updating the port to 10.x but that's of course unrelated to this change.

there is already port pcre2 which is 10.x

**Pull request merged**
