### PR TITLE
[boost-modular-build-helper] Support Clang '--target=<value>' syntax to enable Android builds

### PR DESCRIPTION
**Pull request by mschofie**
**Describe the pull request**
`boost-modular-build-helper` builds a `CXXFLAGS` variable (containing `user-config.jam` compiler command-line options) to pass to `b2`. When `CMAKE_CXX_COMPILER_TARGET` is specified (which it is for Android builds) then the `CXXFLAGS` value is appended with `<compileflags>${CMAKE_CXX_COMPILE_OPTIONS_TARGET} <compileflags>${CMAKE_CXX_COMPILER_TARGET}`, which is correct for gcc's command-line options. But Clang expects no space between `${CMAKE_CXX_COMPILE_OPTIONS_TARGET}` and `${CMAKE_CXX_COMPILER_TARGET}`. In order to build for Clang this PR adds a [`CMAKE_CXX_COMPILER_ID`](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_COMPILER_ID.html) check for `Clang` and composes the variables in the Clang-specific manner.

- What does your PR fix? Fixes issue #10091 

- Which triplets are supported/not supported? Have you updated the CI baseline? There aren't any 'android' triplets at the minute. I've buddy built this change locally successfully using Android NDK 20.1.5948994 and 21.0.6113669 on Windows.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)? Yes.

### CODE REVIEW

**Comment by JackBoosY** [comment]
Regression is not related to the modification of the current PR, and I will be retested after the merger of #10265.

**Review by JackBoosY — CHANGES_REQUESTED** [review]
Could you update port `boost-modular-build-helper` version info?
See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
Will rerun linux PR test after `osg-qt` issue resolve.

**Comment by JackBoosY** [comment]
Some `x64-windows-static` regressions are same with #10486. 
I suspect it is a problem with the ci test.

**Review by JackBoosY — APPROVED** [review]

**Comment by ras0219-msft** [comment]
This LGTM, thanks for the PR!

**Pull request merged**
