### PR TITLE
[z4kn4fein-semver] Add new port

### PR DESCRIPTION
**Pull request by kp-cat**
**Describe the pull request**

- #### What does your PR fix?
Added support for semver header only library https://github.com/z4kn4fein/cpp-semver

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  All. No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Review by JonLiu1993 — DISMISSED** [review]

**Comment by JonLiu1993** [comment]
Tested the semver:x64-windows usage successfully

**Comment by JavierMatosD** [comment]
We appreciate your contributions to the catalog. However, we have an issue with the port's name. "semver" is way too generic. We recommend prefixing with your username. Note that "cpp-semver" will not work because there are other repositories with the same name, and this repository is still new.

**Comment by kp-cat** [comment]
Hi @JavierMatosD,
I can't see "cpp-semver" in the ports just "neargye-semver". I tried "neargye-semver" lib but unfortunately, it seems it's not working correctly. Opened an issue about the error but we still don't have any response :( 
That's why we created a new lib.

if you think "semver" is way too generic I think "cpp-semver" can work.

**Comment by kp-cat** [comment]
Hi @JavierMatosD,

I can see just "neargye-semver" in the ports. Would "semver-cpp" work for you?

**Comment by Neumann-A** [comment]
I think this library should be kept in a private port overlay until there are more users.

**Comment by kp-cat** [comment]
What does "private port overlay" mean? 

Or just should I use the repo owner? "z4kn4fein-semver"?

**Comment by kp-cat** [comment]
Hi @JavierMatosD,
I've just renamed "semver" to "z4kn4fein-semver". I'd like to use vcpkg for dependency handling in another library and I'd like to use this semver lib there. That's why I created this port here. I hope it can be merged into the master.

**Pull request merged**
