### PR TITLE
[bootstrap.ps1] Add option for building 64-bit vcpkg.exe

### PR DESCRIPTION
**Pull request by alexkaratarakis**

### CODE REVIEW

**Review by fcharlie — COMMENTED** [review]
Does this code work on ARM64?

**Comment by alexkaratarakis** [comment]
We are testing `vcpkg` for targeting arm64, but currently not for doing the builds on arm64.
If I can get my hands on an arm64 machine, I will test :).

**Comment by fcharlie** [comment]
@alexkaratarakis Good.

**Comment by alexkaratarakis** [comment]
@fcharlie Merging this. Thanks for the PR!

**Comment by fcharlie** [comment]
@alexkaratarakis Will fail in other locales

```bat
powershell "Get-WmiObject win32_operatingsystem | Select-Object osarchitecture"
```
My OS output:

```

osarchitecture
--------------
64 位
```

**Pull request merged**
