### PR TITLE
fix vcpkg_configure_cmake for case when having semicolons in OPTIONS

### LINKED ISSUE #4320: Semi-colon separated lists in portfile becomes multi-quote guarded, space delimited strings on the command line
I'm trying to enhance the LLVM package to suit my needs, but there is a big problem which I spent over a day now trying to come over. _(This is the kind of aggravation which makes me start to think that Vcpkg does not scale.)_

LLVM requires a `LLVM_TARGETS_TO_BUILD` variable which [by the docs](http://llvm.org/docs/CMake.html#llvm-specific-variables) should be a semi-colon delimited string, so the native CMake encoding for lists. Currently the LLVM port only builds the X86 target, but I want it to also build GPU-related targets. (Currently it's hardcoded, but before I submit, I'll make non-x86 targets _features_ of the package.) Problem is, that if I write this in the portfile:

```CMake
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS
        -DLLVM_TARGETS_TO_BUILD="X86;AMDGPU;NVPTX"
        -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD="X86;AMDGPU;NVPTX"
        -DLLVM_INCLUDE_TOOLS=ON
        -DLLVM_INCLUDE_UTILS=OFF
        -DLLVM_INCLUDE_EXAMPLES=OFF
        -DLLVM_INCLUDE_TESTS=OFF
        -DLLVM_ABI_BREAKING_CHECKS=FORCE_OFF
        -DLLVM_TOOLS_INSTALL_DIR=tools/llvm
        -DLLVM_PARALLEL_LINK_JOBS=8
)
```

It does not matter if I use quotes or not, the command-line invocation contains:

```
"-DLLVM_TARGETS_TO_BUILD="X86" "AMDGPU" "NVPTX""
```

Things from here on start to fall apart spectacularly. (`LLVM_EXPERIMENTAL_TARGETS_TO_BUILD` is undocumented, which targets should be placed there, it just argues seemingly randomly if something's not there. So I just duplicate everything. The two get merged anyway in the main `CMakeLists.txt` file via)

```CMake
set(LLVM_TARGETS_TO_BUILD
   ${LLVM_TARGETS_TO_BUILD}
   ${LLVM_EXPERIMENTAL_TARGETS_TO_BUILD})
list(REMOVE_DUPLICATES LLVM_TARGETS_TO_BUILD)
```

This is the code snippet that calls the LLVM-build Python scripts:

```CMake
message(STATUS "Constructing LLVMBuild project information")
execute_process(
  COMMAND ${PYTHON_EXECUTABLE} -B ${LLVMBUILDTOOL}
            ...
            --enable-targets "${LLVM_TARGETS_TO_BUILD}"
            ...
  RESULT_VARIABLE LLVMBUILDRESULT)
```

The error becomes:

```
-- LLVMHello ignored -- Loadable modules not supported on this platform.
-- Targeting X86 AMDGPU NVPTX
CMake Error at lib/Target/CMakeLists.txt:18 (add_subdirectory):
  add_subdirectory given source "X86 AMDGPU NVPTX" which is not an existing
  directory.


CMake Error at cmake/modules/LLVM-Config.cmake:175 (message):
  Target X86 AMDGPU NVPTX is not in the set of libraries.
Call Stack (most recent call first):
```

of course, because the scripts got derailed a few lines back in LLVM-Config.cmake before invoking the Python scripts when it tried

```CMake
list(FIND LLVM_TARGETS_TO_BUILD "${LLVM_NATIVE_ARCH}" have_native_backend)
```

The variable with the semi-colons stripped is no longer a list.

The fix is to add:

```CMake
message(STATUS "Constructing LLVMBuild project information")
message(STATUS "LLVM_TARGETS_TO_BUILD: ${LLVM_TARGETS_TO_BUILD}")
string(REPLACE " " ";" LLVM_TARGETS_TO_BUILD ${LLVM_TARGETS_TO_BUILD})
message(STATUS "LLVM_TARGETS_TO_BUILD: ${LLVM_TARGETS_TO_BUILD}")
```

which results in configuration succeeding.

```
-- Constructing LLVMBuild project information
-- LLVM_TARGETS_TO_BUILD: X86 AMDGPU NVPTX
-- LLVM_TARGETS_TO_BUILD: X86;AMDGPU;NVPTX
-- LLVMHello ignored -- Loadable modules not supported on this platform.
-- Targeting X86
-- Targeting AMDGPU
-- Targeting NVPTX
```

## Summa summarum

Having to patch the build scripts solely because Vcpkg messes up command-line invocations containing native CMake lists is not okay.

### PR DESCRIPTION
**Pull request by jgehw**
fixes #4320
after having fixed #12926 this was an easy one (special case of root cause in #12926)

### CODE REVIEW

**Comment by Neumann-A** [comment]
Does it depend on #12926?

**Comment by jgehw** [comment]
> Does it depend on #12926?

No, it's independent. It's only the same type of bug, resulting from the undocumented difference between the two cmake API variants
`cmake_parse_arguments(<prefix> <options> <one_value_keywords> <multi_value_keywords> <args>...)`
`cmake_parse_arguments(PARSE_ARGV <N> <prefix> <options> <one_value_keywords> <multi_value_keywords>)`
w.r.t. to handling semicolons. The fix was rather easy in this case because only non-semicolon-destructive `list(APPEND ...)` operations (no `list(INSERT ...)` etc.) are applied after arguments parsing.

**Comment by Neumann-A** [comment]
>resulting from the undocumented difference between the two cmake API

It is not undocumented:

> The PARSE_ARGV signature is only for use in a function() body. In this case the arguments that are parsed come from the ARGV# variables of the calling function. The parsing starts with the <N>-th argument, where <N> is an unsigned integer. This allows for the values to have special characters like ; in them.

otherwise cmake will treat ; as a list separator since ARGN is parsed as a list.

**Comment by jgehw** [comment]
> It is not undocumented

You're right, my fault, I didn't read carefully enough.

**Comment by jgehw** [comment]
merged master because PR #13000 contains CI baseline fixes for soil, which just broke on invalid repository URL while this PR was work in progress

**Comment by jgehw** [comment]
@Neumann-A can you as the author of lapack-reference see why this is failing, e.g., on x64_uwp? I looked through the sources of your portfiles, found one usage of vcpkg_configure_cmake, but as far as I understand it, none of its options has a semicolon it, so I can't see how this PR could break things with lapack-reference. Also, in the log output I didn't find a reason. I'm just wondering if the log output ends abruptly? The last lines are:
-- Configuring x64-uwp
-- Building x64-uwp-dbg
-- Building x64-uwp-rel
-- Fixing pkgconfig file: D:/packages/lapack-reference_x64-uwp/lib/pkgconfig/blas.pc
-- Fixing pkgconfig file: D:/packages/lapack-reference_x64-uwp/lib/pkgconfig/lapack.pc
-- Fixing pkgconfig file: D:/packages/lapack-reference_x64-uwp/debug/lib/pkgconfig/blas.pc
-- Fixing pkgconfig file: D:/packages/lapack-reference_x64-uwp/debug/lib/pkgconfig/lapack.pc
-- Warning: Could not find a matching pdb file for:
    D:/packages/lapack-reference_x64-uwp/bin/liblapack.dll
    D:/packages/lapack-reference_x64-uwp/debug/bin/liblapack.dll

-- Installing: D:/packages/lapack-reference_x64-uwp/share/lapack-reference/copyright

**Comment by Neumann-A** [comment]
```
- Performing post-build validation
Import libs were not present in D:\packages\lapack-reference_x64-uwp\debug\lib
If this is intended, add the following line in the portfile:
    SET(VCPKG_POLICY_DLLS_WITHOUT_LIBS enabled)
Import libs were not present in D:\packages\lapack-reference_x64-uwp\lib
If this is intended, add the following line in the portfile:
    SET(VCPKG_POLICY_DLLS_WITHOUT_LIBS enabled)
Found 2 error(s). Please correct the portfile:
    C:\agent\_work\1\s\ports\lapack-reference\portfile.cmake
-- Performing post-build validation done
```

You are probably not passing `FORTRAN_CMAKE` correctly forward

**Comment by BillyONeal** [comment]
@jgehw It seems like `"${FORTRAN_CMAKE}"` should not have quotes around it in `ports\lapack-reference\portfile.cmake`; you're fixing a bug that some other ports are depending on. (Load bearing bugs are fun eh?)

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
