### PR TITLE
Delete use of vcpkg_test_cmake and vcpkg_common_functions.

### PR DESCRIPTION
**Pull request by BillyONeal**
CONTROL files are intentionally not updated because this change should not affect callers of `vcpkg upgrade`.

* `vcpkg_test_cmake` is a no-op that was usually commented out and has been slowly getting deleted.
* `vcpkg_common_functions` was a no-op because we already provide those ambiently in `portfile.cmake`.

### CODE REVIEW

**Review by vicroms — APPROVED** [review]

**Review by ras0219 — CHANGES_REQUESTED** [review]

**Comment by JackBoosY** [comment]
In fact, I am thinking of rewriting vcpkg_test_cmake and adding a common method for test generated libraries.

**Comment by cenit** [comment]
@JackBoosY maybe your test can be applied automatically to every port without any command from portfile? That would be awesome

**Comment by BillyONeal** [comment]
Reviewing the second commit by itself is suggested since all the tool changes are in there.

**Comment by BillyONeal** [comment]
Merged because all failures were in the baseline.

**Pull request merged**
