### PR TITLE
[civetweb] increase stack size

### LINKED ISSUE #22054: [civetweb] add option for larger thread stacks
****

**Is your feature request related to a problem? Please describe.**

Worker threads in my application run out of stack space easily, in particular when generating a stacktrace with libdw from elfutils. This is because civetweb creates its threads with only 100 KB stacks by default, compared to the default stack size of 2 MB. In the past, I've dealt with this by building civetweb outside of vcpkg and setting 8 MB stacks with `-DCIVETWEB_THREAD_STACK_SIZE=8388608`, but the vcpkg port doesn't expose this option.

**Proposed solution**

Add a feature to the port called `large_stacks` (or whatever) to pass `-DCIVETWEB_THREAD_STACK_SIZE=8388608` in the `vcpkg_configure_cmake()` call.

**Describe alternatives you've considered**

8 MB may be overkill; using the Linux default of 2 MB stacks could suffice. (Edit: we could make the port do this by default instead of adding a feature, too, although it'd deviate from the upstream behavior.) Ideally this would be parameterized, but I don't know of a way to do that within vcpkg. Larger stacks are necessary for my application, so the other alternative would be to have a separate civetweb port; at the moment I have a modified one in my own repository.

**Additional context**

I've run into this with Linux on x86-64. I'll be happy to put a PR together to add this feature, if it seems like the right approach.

### PR DESCRIPTION
**Pull request by csw**
This increases the stack size of worker threads created by civetweb to match the Linux default of 2 MB. By default, it uses 100 KB stacks, which are quite restrictive; they're not sufficient for my application, especially when using libdw for stack traces. (Up until now, I've been building civetweb myself outside of vcpkg, and setting the stack size directly.) This is obviously a divergence from the upstream default behavior, but it's a compile-time option so there's no way to set it when using civetweb via vcpkg. 2 MB stacks are less surprising, and running out of stack space can be a pain to diagnose, so I think this will be better default behavior.

The Windows default stack size is apparently 1 MB, so stacks will be larger than normal on there. We could make this platform-specific and use 1 MB stacks on Windows.

I considered adding a feature to enable this, and I could, but it seemed like it'd create a better experience overall to increase the default.

I think this is ready to go, but I'm happy to make the above changes if need be.

- #### What does your PR fix?  
  Fixes #22054.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  Should be unchanged.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes.

### CODE REVIEW

**Comment by JackBoosY** [comment]
Hmm that's reasonable, but can you please report this to the upstream first?

Thanks.

**Comment by JackBoosY** [comment]
Ping for response.

**Comment by BillyONeal** [comment]
This seems like a change that needs to be made upstream rather than here.

**Comment by JackBoosY** [comment]
Convert to draft until the author response.

**Comment by JackBoosY** [comment]
Closing this PR since it seems that no progress is being made. Please reopen if work is still being done.

**Pull request closed without merging**
