### PR TITLE
[CI Rebuild] Searching for the mythic libmath.a

### PR DESCRIPTION
**Pull request by Neumann-A**
To find hidden dependency in paraview see: #12144

### CODE REVIEW

**Comment by Neumann-A** [comment]
I regret making the message not `[VCPKG-DEBUG]: ${PORT}`

**Comment by PhoebeHui** [comment]
@Neumann-A,t thanks for helping diagnose this issue! can we close this PR now? since we have got the results that the libmath.a from embree3.

**Comment by JackBoosY** [comment]
Since my PR merged, I think we can close this now.

**Comment by Neumann-A** [comment]
Thinks which need vcpkg_fixup_pkgconfig: (I also have a list for vcpkg_fixup_cmake but the detection logic seems flawed)
```
        Line 54: 	Line 4230: 2020-06-29T16:17:39.4659643Z   [VCPKG-DEBUG]: hdf5 has pkgconfig files and has not called
	Line 58: 	Line 4345: 2020-06-29T16:21:19.4610289Z   [VCPKG-DEBUG]: curl has pkgconfig files and has not called
	Line 62: 	Line 4454: 2020-06-29T16:21:57.5165652Z   [VCPKG-DEBUG]: libflac has pkgconfig files and has not called
	Line 64: 	Line 4498: 2020-06-29T16:22:06.4071957Z   [VCPKG-DEBUG]: libvorbis has pkgconfig files and has not called
	Line 65: 	Line 4521: 2020-06-29T16:22:48.3651875Z   [VCPKG-DEBUG]: openal-soft has pkgconfig files and has not called
	Line 67: 	Line 4557: 2020-06-29T16:22:59.2983044Z   [VCPKG-DEBUG]: opus has pkgconfig files and has not called
	Line 70: 	Line 4624: 2020-06-29T16:23:31.9214012Z   [VCPKG-DEBUG]: allegro5 has pkgconfig files and has not called
	Line 72: 	Line 4673: 2020-06-29T16:23:58.8583626Z   [VCPKG-DEBUG]: amqpcpp has pkgconfig files and has not called
	Line 80: 	Line 4989: 2020-06-29T16:32:49.4094363Z   [VCPKG-DEBUG]: openblas has pkgconfig files and has not called
	Line 81: 	Line 5040: 2020-06-29T16:33:35.2046550Z   [VCPKG-DEBUG]: armadillo has pkgconfig files and has not called
	Line 96: 	Line 5404: 2020-06-29T16:34:02.1847597Z   [VCPKG-DEBUG]: brotli has pkgconfig files and has not called
	Line 107: 	Line 5817: 2020-06-29T16:37:00.6201351Z   [VCPKG-DEBUG]: libevent has pkgconfig files and has not called
	Line 108: 	Line 5841: 2020-06-29T16:37:51.5463973Z   [VCPKG-DEBUG]: thrift has pkgconfig files and has not called
	Line 109: 	Line 5898: 2020-06-29T16:40:37.3226630Z   [VCPKG-DEBUG]: arrow has pkgconfig files and has not called
	Line 112: 	Line 6049: 2020-06-29T16:42:23.3200818Z   [VCPKG-DEBUG]: assimp has pkgconfig files and has not called
	Line 119: 	Line 6437: 2020-06-29T16:53:47.0129646Z   [VCPKG-DEBUG]: ffmpeg has pkgconfig files and has not called
	Line 129: 	Line 6736: 2020-06-29T16:55:44.8924720Z   [VCPKG-DEBUG]: avisynthplus has pkgconfig files and has not called
	Line 131: 	Line 6763: 2020-06-29T16:55:59.5614579Z   [VCPKG-DEBUG]: jansson has pkgconfig files and has not called
	Line 132: 	Line 6787: 2020-06-29T16:56:07.0179906Z   [VCPKG-DEBUG]: avro-c has pkgconfig files and has not called
	Line 138: 	Line 6995: 2020-06-29T16:58:01.2996514Z   [VCPKG-DEBUG]: zeromq has pkgconfig files and has not called
	Line 140: 	Line 7175: 2020-06-29T16:58:52.2088937Z   [VCPKG-DEBUG]: cjson has pkgconfig files and has not called
	Line 141: 	Line 7214: 2020-06-29T16:59:01.8475273Z   [VCPKG-DEBUG]: glfw3 has pkgconfig files and has not called
	Line 142: 	Line 7249: 2020-06-29T16:59:12.8414830Z   [VCPKG-DEBUG]: gtest has pkgconfig files and has not called
	Line 143: 	Line 7290: 2020-06-29T16:59:28.1022824Z   [VCPKG-DEBUG]: libjpeg-turbo has pkgconfig files and has not called
	Line 146: 	Line 7418: 2020-06-29T17:00:08.3946727Z   [VCPKG-DEBUG]: spdlog has pkgconfig files and has not called
	Line 153: 	Line 7654: 2020-06-29T17:03:14.1273511Z   [VCPKG-DEBUG]: benchmark has pkgconfig files and has not called
	Line 160: 	Line 7843: 2020-06-29T17:04:03.9307729Z   [VCPKG-DEBUG]: pugixml has pkgconfig files and has not called
	Line 166: 	Line 8050: 2020-06-29T17:06:06.8412660Z   [VCPKG-DEBUG]: blitz has pkgconfig files and has not called
	Line 167: 	Line 8074: 2020-06-29T17:06:12.0456948Z   [VCPKG-DEBUG]: blosc has pkgconfig files and has not called
	Line 249: 	Line 12670: 2020-06-29T17:15:52.4807357Z   [VCPKG-DEBUG]: c-ares has pkgconfig files and has not called
	Line 252: 	Line 12763: 2020-06-29T17:18:38.0995697Z   [VCPKG-DEBUG]: protobuf has pkgconfig files and has not called
	Line 261: 	Line 13119: 2020-06-29T17:32:22.4067462Z   [VCPKG-DEBUG]: ccd has pkgconfig files and has not called
	Line 270: 	Line 13524: 2020-06-29T17:38:10.3401016Z   [VCPKG-DEBUG]: check has pkgconfig files and has not called
	Line 279: 	Line 13921: 2020-06-29T17:41:24.7142689Z   [VCPKG-DEBUG]: cmark has pkgconfig files and has not called
	Line 280: 	Line 13945: 2020-06-29T17:41:40.1279035Z   [VCPKG-DEBUG]: cmocka has pkgconfig files and has not called
	Line 292: 	Line 14360: 2020-06-29T17:48:26.0789526Z   [VCPKG-DEBUG]: cpp-redis has pkgconfig files and has not called
	Line 298: 	Line 14588: 2020-06-29T17:55:04.6037475Z   [VCPKG-DEBUG]: librdkafka has pkgconfig files and has not called
	Line 315: 	Line 15211: 2020-06-29T18:01:33.0592558Z   [VCPKG-DEBUG]: curlpp has pkgconfig files and has not called
	Line 320: 	Line 15362: 2020-06-29T18:11:48.1578945Z   [VCPKG-DEBUG]: cutelyst2 has pkgconfig files and has not called
	Line 321: 	Line 15403: 2020-06-29T18:12:04.7035065Z   [VCPKG-DEBUG]: czmq has pkgconfig files and has not called
	Line 326: 	Line 15566: 2020-06-29T18:13:06.5875101Z   [VCPKG-DEBUG]: libwebp has pkgconfig files and has not called
	Line 327: 	Line 15590: 2020-06-29T18:13:23.7146240Z   [VCPKG-DEBUG]: tiff has pkgconfig files and has not called
	Line 333: 	Line 15764: 2020-06-29T18:21:59.2263075Z   [VCPKG-DEBUG]: freeglut has pkgconfig files and has not called
	Line 335: 	Line 15831: 2020-06-29T18:22:33.4714443Z   [VCPKG-DEBUG]: devil has pkgconfig files and has not called
	Line 346: 	Line 16167: 2020-06-29T18:25:53.4804356Z   [VCPKG-DEBUG]: fftw3 has pkgconfig files and has not called
	Line 347: 	Line 16193: 2020-06-29T18:26:33.2757358Z   [VCPKG-DEBUG]: dlib has pkgconfig files and has not called
	Line 361: 	Line 16853: 2020-06-29T18:45:07.2309214Z   [VCPKG-DEBUG]: entityx has pkgconfig files and has not called
	Line 367: 	Line 16989: 2020-06-29T18:46:14.0083925Z   [VCPKG-DEBUG]: exiv2 has pkgconfig files and has not called
	Line 375: 	Line 17265: 2020-06-29T18:48:37.7213250Z   [VCPKG-DEBUG]: octomap has pkgconfig files and has not called
	Line 376: 	Line 17288: 2020-06-29T18:50:03.7012883Z   [VCPKG-DEBUG]: fcl has pkgconfig files and has not called
	Line 379: 	Line 17359: 2020-06-29T18:51:02.7149504Z   [VCPKG-DEBUG]: ffnvcodec has pkgconfig files and has not called
	Line 382: 	Line 17425: 2020-06-29T18:52:31.2702587Z   [VCPKG-DEBUG]: folly has pkgconfig files and has not called
	Line 383: 	Line 17485: 2020-06-29T18:55:00.0019026Z   [VCPKG-DEBUG]: flann has pkgconfig files and has not called
	Line 384: 	Line 17527: 2020-06-29T18:56:27.1248024Z   [VCPKG-DEBUG]: fluidsynth has pkgconfig files and has not called
	Line 387: 	Line 17575: 2020-06-29T18:56:57.1336650Z   [VCPKG-DEBUG]: libzip has pkgconfig files and has not called
	Line 394: 	Line 17886: 2020-06-29T19:03:15.9000639Z   [VCPKG-DEBUG]: freerdp has pkgconfig files and has not called
	Line 396: 	Line 17933: 2020-06-29T19:04:31.3057761Z   [VCPKG-DEBUG]: glew has pkgconfig files and has not called
	Line 400: 	Line 18042: 2020-06-29T19:04:52.7910245Z   [VCPKG-DEBUG]: fribidi has pkgconfig files and has not called
	Line 407: 	Line 18329: 2020-06-29T19:11:54.7219981Z   [VCPKG-DEBUG]: netcdf-c has pkgconfig files and has not called
	Line 412: 	Line 18477: 2020-06-29T19:24:53.8618423Z   [VCPKG-DEBUG]: geogram has pkgconfig files and has not called
	Line 423: 	Line 18873: 2020-06-29T19:30:39.6805285Z   [VCPKG-DEBUG]: grpc has pkgconfig files and has not called
	Line 424: 	Line 18897: 2020-06-29T19:33:26.2671590Z   [VCPKG-DEBUG]: google-cloud-cpp has pkgconfig files and has not called
	Line 431: 	Line 19072: 2020-06-29T19:37:09.6076865Z   [VCPKG-DEBUG]: graphite2 has pkgconfig files and has not called
	Line 437: 	Line 19233: 2020-06-29T19:39:05.6212757Z   [VCPKG-DEBUG]: libepoxy has pkgconfig files and has not called
	Line 450: 	Line 19660: 2020-06-29T20:45:01.7482839Z   [VCPKG-DEBUG]: hiredis has pkgconfig files and has not called
	Line 456: 	Line 19834: 2020-06-29T20:55:35.4890112Z   [VCPKG-DEBUG]: libplist has pkgconfig files and has not called
	Line 458: 	Line 19862: 2020-06-29T20:55:39.0677720Z   [VCPKG-DEBUG]: libusbmuxd has pkgconfig files and has not called
	Line 471: 	Line 20468: 2020-06-29T21:00:46.6853399Z   [VCPKG-DEBUG]: iniparser has pkgconfig files and has not called
	Line 483: 	Line 21011: 2020-06-29T21:07:20.3802799Z   [VCPKG-DEBUG]: json11 has pkgconfig files and has not called
	Line 490: 	Line 21213: 2020-06-29T21:09:55.6837752Z   [VCPKG-DEBUG]: keystone has pkgconfig files and has not called
	Line 498: 	Line 21429: 2020-06-29T21:11:49.7562515Z   [VCPKG-DEBUG]: liblemon has pkgconfig files and has not called
	Line 500: 	Line 21474: 2020-06-29T21:12:09.1284204Z   [VCPKG-DEBUG]: leptonica has pkgconfig files and has not called
	Line 505: 	Line 21630: 2020-06-29T21:14:39.3438090Z   [VCPKG-DEBUG]: libass has pkgconfig files and has not called
	Line 507: 	Line 21695: 2020-06-29T21:14:50.8020357Z   [VCPKG-DEBUG]: libbson has pkgconfig files and has not called
	Line 508: 	Line 21737: 2020-06-29T21:15:05.3057655Z   [VCPKG-DEBUG]: libcerf has pkgconfig files and has not called
	Line 511: 	Line 21784: 2020-06-29T21:15:19.2892463Z   [VCPKG-DEBUG]: libconfuse has pkgconfig files and has not called
	Line 518: 	Line 22060: 2020-06-29T21:18:06.8683818Z   [VCPKG-DEBUG]: libfreenect2 has pkgconfig files and has not called
	Line 520: 	Line 22122: 2020-06-29T21:18:20.8948320Z   [VCPKG-DEBUG]: libftdi1 has pkgconfig files and has not called
	Line 522: 	Line 22192: 2020-06-29T21:19:11.6379775Z   [VCPKG-DEBUG]: libgit2 has pkgconfig files and has not called
	Line 525: 	Line 22270: 2020-06-29T21:19:26.6463989Z   [VCPKG-DEBUG]: libgta has pkgconfig files and has not called
	Line 529: 	Line 22373: 2020-06-29T21:19:49.4016745Z   [VCPKG-DEBUG]: libideviceactivation has pkgconfig files and has not called
	Line 531: 	Line 22419: 2020-06-29T21:20:19.2097540Z   [VCPKG-DEBUG]: libkml has pkgconfig files and has not called
	Line 533: 	Line 22485: 2020-06-29T21:21:07.0000442Z   [VCPKG-DEBUG]: liblo has pkgconfig files and has not called
	Line 538: 	Line 22660: 2020-06-29T21:23:18.8395526Z   [VCPKG-DEBUG]: libmikmod has pkgconfig files and has not called
	Line 559: 	Line 23189: 2020-06-29T21:27:59.8604995Z   [VCPKG-DEBUG]: libpmemobj-cpp has pkgconfig files and has not called
	Line 561: 	Line 23239: 2020-06-29T21:28:18.0887522Z   [VCPKG-DEBUG]: libproxy has pkgconfig files and has not called
	Line 563: 	Line 23335: 2020-06-29T21:28:53.0661845Z   [VCPKG-DEBUG]: libqrencode has pkgconfig files and has not called
	Line 572: 	Line 23566: 2020-06-29T21:31:29.0263190Z   [VCPKG-DEBUG]: libsrt has pkgconfig files and has not called
	Line 619: 	Line 25165: 2020-06-29T21:50:09.4719336Z   [VCPKG-DEBUG]: mongo-c-driver has pkgconfig files and has not called
	Line 620: 	Line 25193: 2020-06-29T21:51:10.4196919Z   [VCPKG-DEBUG]: mongo-cxx-driver has pkgconfig files and has not called
	Line 623: 	Line 25340: 2020-06-29T21:52:09.7588406Z   [VCPKG-DEBUG]: mosquitto has pkgconfig files and has not called
	Line 629: 	Line 25462: 2020-06-29T21:52:53.5657540Z   [VCPKG-DEBUG]: msgpack11 has pkgconfig files and has not called
	Line 632: 	Line 25512: 2020-06-29T21:53:55.6569874Z   [VCPKG-DEBUG]: xerces-c has pkgconfig files and has not called
	Line 635: 	Line 25605: 2020-06-29T21:54:47.1503039Z   [VCPKG-DEBUG]: munit has pkgconfig files and has not called
	Line 637: 	Line 25631: 2020-06-29T21:54:55.8617954Z   [VCPKG-DEBUG]: muparser has pkgconfig files and has not called
	Line 641: 	Line 25753: 2020-06-29T21:55:44.5816247Z   [VCPKG-DEBUG]: nanoflann has pkgconfig files and has not called
	Line 644: 	Line 25817: 2020-06-29T21:56:44.7656710Z   [VCPKG-DEBUG]: nanomsg has pkgconfig files and has not called
	Line 648: 	Line 25971: 2020-06-29T21:57:45.0818108Z   [VCPKG-DEBUG]: nghttp2 has pkgconfig files and has not called
	Line 655: 	Line 26383: 2020-06-29T22:02:32.3117983Z   [VCPKG-DEBUG]: ode has pkgconfig files and has not called
	Line 659: 	Line 26488: 2020-06-29T22:11:47.2467554Z   [VCPKG-DEBUG]: ompl has pkgconfig files and has not called
	Line 660: 	Line 26511: 2020-06-29T22:12:53.1334663Z   [VCPKG-DEBUG]: oniguruma has pkgconfig files and has not called
	Line 661: 	Line 26550: 2020-06-29T22:13:37.7429192Z   [VCPKG-DEBUG]: opencc has pkgconfig files and has not called
	Line 663: 	Line 26602: 2020-06-29T22:13:59.9047291Z   [VCPKG-DEBUG]: opencolorio has pkgconfig files and has not called
	Line 674: 	Line 27044: 2020-06-29T22:23:40.9068597Z   [VCPKG-DEBUG]: orocos-kdl has pkgconfig files and has not called
	Line 678: 	Line 27128: 2020-06-29T22:23:59.4997586Z   [VCPKG-DEBUG]: p-ranav-csv2 has pkgconfig files and has not called
	Line 689: 	Line 27587: 2020-06-29T23:02:21.4851133Z   [VCPKG-DEBUG]: qhull has pkgconfig files and has not called
	Line 690: 	Line 27617: 2020-06-29T23:12:06.0105204Z   [VCPKG-DEBUG]: pcl has pkgconfig files and has not called
	Line 691: 	Line 27645: 2020-06-29T23:14:58.5936197Z   [VCPKG-DEBUG]: pdal has pkgconfig files and has not called
	Line 711: 	Line 28600: 2020-06-29T23:24:15.4520673Z   [VCPKG-DEBUG]: ponder has pkgconfig files and has not called
	Line 760: 	Line 30217: 2020-06-30T00:00:35.1897723Z   [VCPKG-DEBUG]: raylib has pkgconfig files and has not called
	Line 763: 	Line 30302: 2020-06-30T00:02:46.3943525Z   [VCPKG-DEBUG]: realsense2 has pkgconfig files and has not called
	Line 771: 	Line 30714: 2020-06-30T00:07:47.4763938Z   [VCPKG-DEBUG]: rtlsdr has pkgconfig files and has not called
	Line 776: 	Line 30879: 2020-06-30T00:08:56.1977584Z   [VCPKG-DEBUG]: sais has pkgconfig files and has not called
	Line 781: 	Line 31101: 2020-06-30T00:11:07.1662563Z   [VCPKG-DEBUG]: sdformat6 has pkgconfig files and has not called
	Line 784: 	Line 31285: 2020-06-30T00:12:36.4143679Z   [VCPKG-DEBUG]: sdl2pp has pkgconfig files and has not called
	Line 790: 	Line 32277: 2020-06-30T00:15:45.7892330Z   [VCPKG-DEBUG]: spirv-tools has pkgconfig files and has not called
	Line 791: 	Line 32300: 2020-06-30T00:17:29.5713785Z   [VCPKG-DEBUG]: shaderc has pkgconfig files and has not called
	Line 825: 	Line 33478: 2020-06-30T00:30:42.9800535Z   [VCPKG-DEBUG]: stxxl has pkgconfig files and has not called
	Line 826: 	Line 33576: 2020-06-30T00:32:52.3379563Z   [VCPKG-DEBUG]: taglib has pkgconfig files and has not called
	Line 833: 	Line 33936: 2020-06-30T00:36:32.5866031Z   [VCPKG-DEBUG]: tidy-html5 has pkgconfig files and has not called
	Line 840: 	Line 34193: 2020-06-30T00:37:28.2687841Z   [VCPKG-DEBUG]: tinyobjloader has pkgconfig files and has not called
	Line 854: 	Line 34757: 2020-06-30T00:39:18.8946751Z   [VCPKG-DEBUG]: uchardet has pkgconfig files and has not called
	Line 859: 	Line 34864: 2020-06-30T00:40:37.9438086Z   [VCPKG-DEBUG]: unittest-cpp has pkgconfig files and has not called
	Line 873: 	Line 35364: 2020-06-30T00:51:19.3564160Z   [VCPKG-DEBUG]: wampcc has pkgconfig files and has not called
	Line 875: 	Line 35410: 2020-06-30T00:52:13.4998057Z   [VCPKG-DEBUG]: wavpack has pkgconfig files and has not called
	Line 884: 	Line 35605: 2020-06-30T00:52:48.3645178Z   [VCPKG-DEBUG]: woff2 has pkgconfig files and has not called
	Line 890: 	Line 35815: 2020-06-30T01:00:38.5129369Z   [VCPKG-DEBUG]: x265 has pkgconfig files and has not called
	Line 892: 	Line 35844: 2020-06-30T01:01:41.8816640Z   [VCPKG-DEBUG]: xalan-c has pkgconfig files and has not called
	Line 894: 	Line 35884: 2020-06-30T01:01:51.5571213Z   [VCPKG-DEBUG]: xtl has pkgconfig files and has not called
	Line 896: 	Line 36045: 2020-06-30T01:02:59.8204828Z   [VCPKG-DEBUG]: xtensor-fftw has pkgconfig files and has not called
	Line 906: 	Line 36583: 2020-06-30T01:08:41.1234834Z   [VCPKG-DEBUG]: zyre has pkgconfig files and has not called
```

**Pull request closed without merging**
