### PR TITLE
Update to cmake 3.14 (allow compilation with VS2019RC v142)

### LINKED ISSUE #5344: glfw3
vcpkg install glfw3
```
The following packages will be built and installed:
    glfw3[core]:x86-windows
Starting package 1/1: glfw3:x86-windows
Building package glfw3[core]:x86-windows...
-- Using cached C:/vcpkg/vcpkg/downloads/glfw-glfw-3.2.1.tar.gz
-- Using source at C:/vcpkg/vcpkg/buildtrees/glfw3/src/3.2.1-28ab61727b
CMake Error at scripts/cmake/vcpkg_configure_cmake.cmake:113 (message):
  Unable to determine appropriate generator for: -x86-v142
Call Stack (most recent call first):
  ports/glfw3/portfile.cmake:21 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)


Error: Building package glfw3:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glfw3:x86-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.
```

### LINKED ISSUE #5527: Add CMake support for Visual Studio 2019
Package: sfml:x64-windows
Vcpkg version: 2018.11.23-nohash

Currently SFML fails to build after installing Visual Studio 2019 Community RC with the following console output:

~~~
CMake Error at scripts/cmake/vcpkg_configure_cmake.cmake:113 (message):
  Unable to determine appropriate generator for: -x64-v142
Call Stack (most recent call first):
  ports/sfml/portfile.cmake:22 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)


Error: Building package sfml:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: sfml:x64-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.
~~~

I understand if the maintainers want to wait until VS 2019 is fully released, but I thought I'd at least make the problem apparent. Also, don't know if we're waiting for an updated CMake.

### PR DESCRIPTION
**Pull request by kiwixz**
Currently, if VS2019 RC is installed on the machine, it is detected as the latest stable VS (it's a RC and not a Preview).  CMake <3.14 does not support VS2019, so vcpkg would not let us configure any CMake project without explicitly adding `set(VCPKG_PLATFORM_TOOLSET v141)` to triplet.

Fixes #5344.
Fixes #5527.

### CODE REVIEW

**Comment by kiwixz** [comment]
It's a duplicate of #5683 and #5700, sorry I should have checked before.

**Comment by Rastaban** [comment]
I am running some tests on this PR.

**Comment by Rastaban** [comment]
Because this change triggered a full rebuild of all ports it exposed some unrelated regressions that have slowed down the processing of this PR.  We are working on addressing those issues at the same time as we are working on testing this PR.

**Comment by bitsrules** [comment]
Also seems to work with the final version of VS 2019 released today.

**Comment by grdowns** [comment]
We're greenlit! Thanks for the contributions everyone, including those in #5683 and #5700

**Pull request merged**
