### PR TITLE
[co] Rename port co to cocoyaxi

### PR DESCRIPTION
**Pull request by idealvin**
**Describe the pull request**

- #### What does your PR fix?  
Rename co to [cocoyaxi](https://github.com/idealvin/cocoyaxi).

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  <all / linux, windows, ...>, <Yes>

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  <Yes / I am still working on this PR>

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. VCPKG use `supports` in vcpkg.json instead of `vcpkg_fail_port_install`. Could you please remove there codes in **portfile.cmake**?
```
if(VCPKG_TARGET_IS_WINDOWS OR VCPKG_TARGET_IS_UWP)
    vcpkg_fail_port_install(ON_ARCH "arm" ON_TAREGT "uwp")
endif()
```
And if you rename co to cocoyaxi, you need also rename the directory name _VCPKG_ROOT/ports/co_ to _VCPKG_ROOT/ports/cocoyaxi_.

**Comment by idealvin** [comment]
> Thanks for posting this issue. VCPKG use `supports` in vcpkg.json instead of `vcpkg_fail_port_install`. Could you please remove there codes in **portfile.cmake**?
> 
> ```
> if(VCPKG_TARGET_IS_WINDOWS OR VCPKG_TARGET_IS_UWP)
>     vcpkg_fail_port_install(ON_ARCH "arm" ON_TAREGT "uwp")
> endif()
> ```
> 
> And if you rename co to cocoyaxi, you need also rename the directory name _VCPKG_ROOT/ports/co_ to _VCPKG_ROOT/ports/cocoyaxi_.

@LilyWangLL 
Hi, I think I have already renamed it to cocoyaxi. But I don't know how to use `supports` instead of `vcpkg_fail_port_install`. Could you help? Thanks!

**Comment by LilyWangLL** [comment]
@idealvin You just need remove these codes in **portfile.cmake**.
```
if(VCPKG_TARGET_IS_WINDOWS OR VCPKG_TARGET_IS_UWP)
    vcpkg_fail_port_install(ON_ARCH "arm" ON_TAREGT "uwp")
endif()
```

**Comment by idealvin** [comment]
> @idealvin You just need remove these codes in **portfile.cmake**.
> 
> ```
> if(VCPKG_TARGET_IS_WINDOWS OR VCPKG_TARGET_IS_UWP)
>     vcpkg_fail_port_install(ON_ARCH "arm" ON_TAREGT "uwp")
> endif()
> ```

ok, I removed it..

**Review by strega-nil-ms — CHANGES_REQUESTED** [review]
This PR is incorrect since it removes history; it should've been caught by CI.

The correct way to rename a port is to have an empty port under the old name, which depends only on the new port. The new port's version.json should only contain the latest version.

What you need to do here is:

* restore `co` as an empty port which depends only on `cocoyaxi`
* restore `versions/c-/co.json`
* have _only_ the latest version of cocoyaxi in `versions/c-/cocoyaxi.json`

**Comment by idealvin** [comment]
> @idealvin You could download and unzip the attached file **co.zip**, then put directory **co** into _VCPKG_ROOT/ports_, and put **co.json** into _VCPKG_ROOT/versions/c-_. [co.zip](https://github.com/microsoft/vcpkg/files/7868984/co.zip)

@LilyWangLL ok，thanks! I'll try later. A little busy these days.

**Review by LilyWangLL — APPROVED** [review]

**Comment by idealvin** [comment]
> This PR is incorrect since it removes history; it should've been caught by CI.
> 
> The correct way to rename a port is to have an empty port under the old name, which depends only on the new port. The new port's version.json should only contain the latest version.
> 
> What you need to do here is:
> 
> * restore `co` as an empty port which depends only on `cocoyaxi`
> * restore `versions/c-/co.json`
> * have _only_ the latest version of cocoyaxi in `versions/c-/cocoyaxi.json`



> This PR is incorrect since it removes history; it should've been caught by CI.
> 
> The correct way to rename a port is to have an empty port under the old name, which depends only on the new port. The new port's version.json should only contain the latest version.
> 
> What you need to do here is:
> 
> * restore `co` as an empty port which depends only on `cocoyaxi`
> * restore `versions/c-/co.json`
> * have _only_ the latest version of cocoyaxi in `versions/c-/cocoyaxi.json`

@strega-nil-ms  Done. Thanks.

**Pull request merged**
