### PR TITLE
[metrohash] installation fix

### PR DESCRIPTION
**Pull request by kreuzerkrieg**
Fixing paths and configuration

### CODE REVIEW

**Comment by LilyWangL** [comment]
Thanks for your PR! Can you please correct the Version field in the CONTROL file? You can get more information from [maintainer-guide.md](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md).

**Comment by kreuzerkrieg** [comment]
> Thanks for your PR! Can you please correct the Version field in the CONTROL file? You can get more information from [maintainer-guide.md](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md).

Done

**Comment by kreuzerkrieg** [comment]
Please do not merge, more changes to come

**Comment by kreuzerkrieg** [comment]
Ok, looks good now
Please review

**Review by LilyWangL — APPROVED** [review]

**Comment by strega-nil** [comment]
LGTM! Thanks @kreuzerkrieg :)

**Pull request merged**
