### PR TITLE
[libpcap] update to 1.10.4

### PR DESCRIPTION
**Pull request by jiayuehua**
- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [X] SHA512s are updated for each updated download
- [ ] ~The "supports" clause reflects platforms that may be fixed by this new version~
- [ ] ~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~
- [ ] ~Any patches that are no longer applied are deleted from the port's directory.~
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by Cheney-W** [comment]
The patch here does not need to be modified.

**Comment by jiayuehua** [comment]
If not modified, when install new version libpcap, vcpkg report error:    
-- Applying patch install-pc-on-msvc.patch
CMake Error at scripts/cmake/z_vcpkg_apply_patches.cmake:34 (message):
  Applying patch failed: Checking patch CMakeLists.txt...

  Hunk #1 succeeded at 3238 (offset 560 lines).

  error: while searching for:

   install(FILES ${CMAKE_CURRENT_BINARY_DIR}/libpcap.pc DESTINATION lib/pkgconfig)?

  ?

      #?
      # Man pages.?

  

  error: patch failed: CMakeLists.txt:2715

  error: CMakeLists.txt: patch does not apply

**Comment by Cheney-W** [comment]
Yes, you are right. I could reproduce this error in a new vcpkg folder. (I previously tested on an old vcpkg folder and did not encounter this error.)
However, please do not modify the line break at the end of the line. This patch was previously used in CRLF, please keep it as is to reduce the amount of modification.

**Review by Cheney-W — APPROVED** [review]

**Comment by Cheney-W** [comment]
Thanks for your PR!

**Comment by jiayuehua** [comment]
you are welcome.

**Pull request merged**
