### PR TITLE
[grpc] Update grpc to 1.24.3

### PR DESCRIPTION
**Pull request by jozefizso**
Update grpc port to release [1.24.3](https://github.com/grpc/grpc/releases/tag/v1.24.3) ([full release notes](https://github.com/grpc/grpc/releases/tag/v1.24.0))

As grpc 1.24.3 tar.gz package includes the **upb** source code, it can be compiled easily compared to 1.24.0 release.

This pull request supersede #8791 and #8881

### CODE REVIEW

**Comment by jozefizso** [comment]
grpc build on `uwp-arm` fails on error **error C4146:  unary minus operator applied to unsigned type, result still unsigned** in **ubp** library:

```
       "C:\vsts\_work\2\s\buildtrees\grpc\arm-uwp-dbg\install.vcxproj" (default target) (1) ->
       "C:\vsts\_work\2\s\buildtrees\grpc\arm-uwp-dbg\ALL_BUILD.vcxproj" (default target) (3) ->
       "C:\vsts\_work\2\s\buildtrees\grpc\arm-uwp-dbg\grpc_unsecure.vcxproj" (default target) (19) ->
       (ClCompile target) -> 
         C:\vsts\_work\2\s\buildtrees\grpc\src\v1.24.3-43a141fa24\third_party\upb\upb\msg.c(36,10): error C4146:  unary minus operator applied to unsigned type, result still unsigned [C:\vsts\_work\2\s\buildtrees\grpc\arm-uwp-dbg\grpc_unsecure.vcxproj]
         C:\vsts\_work\2\s\buildtrees\grpc\src\v1.24.3-43a141fa24\third_party\upb\upb\msg.c(40,10): error C4146:  unary minus operator applied to unsigned type, result still unsigned [C:\vsts\_work\2\s\buildtrees\grpc\arm-uwp-dbg\grpc_unsecure.vcxproj]
         C:\vsts\_work\2\s\buildtrees\grpc\src\v1.24.3-43a141fa24\third_party\upb\upb\msg.c(46,10): error C4146:  unary minus operator applied to unsigned type, result still unsigned [C:\vsts\_work\2\s\buildtrees\grpc\arm-uwp-dbg\grpc_unsecure.vcxproj]


       "C:\vsts\_work\2\s\buildtrees\grpc\arm-uwp-dbg\install.vcxproj" (default target) (1) ->
       "C:\vsts\_work\2\s\buildtrees\grpc\arm-uwp-dbg\ALL_BUILD.vcxproj" (default target) (3) ->
       "C:\vsts\_work\2\s\buildtrees\grpc\arm-uwp-dbg\grpc_cronet.vcxproj" (default target) (15) ->
         C:\vsts\_work\2\s\buildtrees\grpc\src\v1.24.3-43a141fa24\third_party\upb\upb\msg.c(36,10): error C4146:  unary minus operator applied to unsigned type, result still unsigned [C:\vsts\_work\2\s\buildtrees\grpc\arm-uwp-dbg\grpc_cronet.vcxproj]
         C:\vsts\_work\2\s\buildtrees\grpc\src\v1.24.3-43a141fa24\third_party\upb\upb\msg.c(40,10): error C4146:  unary minus operator applied to unsigned type, result still unsigned [C:\vsts\_work\2\s\buildtrees\grpc\arm-uwp-dbg\grpc_cronet.vcxproj]
         C:\vsts\_work\2\s\buildtrees\grpc\src\v1.24.3-43a141fa24\third_party\upb\upb\msg.c(46,10): error C4146:  unary minus operator applied to unsigned type, result still unsigned [C:\vsts\_work\2\s\buildtrees\grpc\arm-uwp-dbg\grpc_cronet.vcxproj]


       "C:\vsts\_work\2\s\buildtrees\grpc\arm-uwp-dbg\install.vcxproj" (default target) (1) ->
       "C:\vsts\_work\2\s\buildtrees\grpc\arm-uwp-dbg\ALL_BUILD.vcxproj" (default target) (3) ->
       "C:\vsts\_work\2\s\buildtrees\grpc\arm-uwp-dbg\grpc.vcxproj" (default target) (11) ->
         C:\vsts\_work\2\s\buildtrees\grpc\src\v1.24.3-43a141fa24\third_party\upb\upb\msg.c(36,10): error C4146:  unary minus operator applied to unsigned type, result still unsigned [C:\vsts\_work\2\s\buildtrees\grpc\arm-uwp-dbg\grpc.vcxproj]
         C:\vsts\_work\2\s\buildtrees\grpc\src\v1.24.3-43a141fa24\third_party\upb\upb\msg.c(40,10): error C4146:  unary minus operator applied to unsigned type, result still unsigned [C:\vsts\_work\2\s\buildtrees\grpc\arm-uwp-dbg\grpc.vcxproj]
         C:\vsts\_work\2\s\buildtrees\grpc\src\v1.24.3-43a141fa24\third_party\upb\upb\msg.c(46,10): error C4146:  unary minus operator applied to unsigned type, result still unsigned [C:\vsts\_work\2\s\buildtrees\grpc\arm-uwp-dbg\grpc.vcxproj]

    619 Warning(s)
    9 Error(s)
```

**Comment by jozefizso** [comment]
I'm not sure why grpc is being built against **arm-uwp** because **zlib** or **c-ares** libraries does not support arm.

**Comment by jozefizso** [comment]
I fixed the issue in **upb** so the compiler ignores the C4146 error in **msg.c**

Latest build is failing in the **llvm** package on Linux. The grpc itself can be built:

```

Triplet: x64-linux
Total elapsed time: 14.41 min
RESULTS
    protobuf:x64-linux: SUCCEEDED: 2.585 s
    c-ares:x64-linux: SUCCEEDED: 288.1 ms
    zlib:x64-linux: SUCCEEDED: 178.1 ms
    openssl-unix:x64-linux: SUCCEEDED: 390.5 ms
    openssl:x64-linux: SUCCEEDED: 103 ms
    grpc:x64-linux: SUCCEEDED: 5.021 min
    googleapis:x64-linux: SUCCEEDED: 1.894 min
    google-cloud-cpp-common:x64-linux: SUCCEEDED: 15.22 s
    crc32c:x64-linux: SUCCEEDED: 98.53 ms
    curl:x64-linux: SUCCEEDED: 213.3 ms
    google-cloud-cpp-spanner:x64-linux: SUCCEEDED: 1.384 min
    google-cloud-cpp:x64-linux: SUCCEEDED: 4.687 min
    pthreads:x64-linux: SUCCEEDED: 191.6 ms
    pthread:x64-linux: SUCCEEDED: 206.8 ms
    openblas:x64-linux: SUCCEEDED: 638.3 ms
    llvm:x64-linux: BUILD_FAILED: 511.9 ms
    halide:x64-linux: CASCADED_DUE_TO_MISSING_DEPENDENCIES: 77.9 us
    offscale-libetcd-cpp:x64-linux: SUCCEEDED: 1.082 min

SUMMARY
    SUCCEEDED: 16
    BUILD_FAILED: 1
    POST_BUILD_CHECKS_FAILED: 0
    FILE_CONFLICTS: 0
    CASCADED_DUE_TO_MISSING_DEPENDENCIES: 1
    EXCLUDED: 0
Test complete
```

**Comment by jozefizso** [comment]
@grdowns I hope I fixed the compilation on all platforms.

**Comment by jozefizso** [comment]
@grdowns @LilyWangL is there any more work required on this to be merged?

**Comment by PhoebeHui** [comment]
@jozefizso, thanks for the PR!

Duplicated this PR to https://github.com/microsoft/vcpkg/pull/9363 since it update grpc to latest release revision 1.26.0

**Comment by jozefizso** [comment]
@PhoebeHui why this wasn't accepted?

**Comment by PhoebeHui** [comment]
@jozefizso, the PR looks good for me. The macOS CI test machine offline for maintenance,  so it haven't been merged in time, sorry for delay!

We are appreciated for your contribution!  Even though we duplicated this PR to PR#9363, you solved some issues ahead, It's still valuable for us!

**Comment by jozefizso** [comment]
This wasn’t merged at all!

I don’t understand how is this valuable when it’s not merged?

And I don’t get this concept of “duplicating PR” as #9363 does not contain commits from this pull request.

**Comment by PhoebeHui** [comment]
@jozefizso, sorry for the confusing.

I duplicated to PR#9363 since it upgraded grpc to latest revision that we prefer to reviewing and merging. For this PR, even it's not merged, but it doesn't block other user to use it, they can get these changes if they like.

**Comment by jozefizso** [comment]
To my best knowledge, this PR is done according to you rules for making port updates.

It was ignored for two weeks without being merged (based on what rule?)

Also my changes were moved elsewhere without attribution.

When I delete the branch from my fork, this is gone and to no use to others. PR does not work in a way that I have to maintain a fork indefinitely to have access to code and information from PR.

**Comment by PhoebeHui** [comment]
It's our fault, I feel really sorry for that.

We are trying to give quick response for new PRs, and try to get the macOS test machine online as soon as possible, we sincerely apologize for that!

**Comment by jozefizso** [comment]
How does this make it non-mergable PR?

**Comment by PhoebeHui** [comment]
@dan-shaw, what do you think?

**Comment by dan-shaw** [comment]
@jozefizso After looking at both PRs, I think it makes sense to merge this PR first. It has a better approach for patching the UWP error than #9363. I saw that you have been pinging us for a while, and we really should have gotten back to you sooner. Sorry about that! In the future, it might be better to ping us on Slack for review - we usually will get back to you much faster that way.

**Comment by dan-shaw** [comment]
@jozefizso Thanks for the wait - its now merged!

**Comment by jozefizso** [comment]
@dan-shaw thanks a lot for merging this.

**Pull request merged**
