### PR TITLE
[vcpkg|scripts] fix version check in vcpkg_find_acquire_program

### PR DESCRIPTION
**Pull request by Neumann-A**
and force exact version match for meson (because it is meson and stuff breaks with other versions......)

### CODE REVIEW

**Comment by BillyONeal** [comment]
Thank you so much... you have no idea how many hours you just saved this poor not-yet-cmake-native 😅

**Review by vicroms — APPROVED** [review]

**Comment by BillyONeal** [comment]
I confirmed that fontconfig is broken before and fixed now on an Ubuntu 20.04 box.

**Review by BillyONeal — APPROVED** [review]

**Review by JackBoosY — APPROVED** [review]

**Comment by Be-ing** [comment]
Thanks for fixing this!

**Comment by JackBoosY** [comment]
@wrobelda  There is a kf5kio regression:
```
CMake Error at /agent/_work/1/s/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
  Target "kioexec" links to target "LibMount::LibMount" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  src/kioexec/CMakeLists.txt:28 (add_executable)


CMake Error at /agent/_work/1/s/scripts/buildsystems/vcpkg.cmake:578 (_add_library):
  Target "kio_trash" links to target "LibMount::LibMount" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  src/ioslaves/trash/CMakeLists.txt:30 (add_library)
...
```
I didn't find any find libmount code in kf5kio source, can you please take a look?

**Comment by Neumann-A** [comment]
@BillyONeal I assume you will merge this although CI is not completely green due to regression discovered by the world rebuild

**Comment by BillyONeal** [comment]
> @BillyONeal I assume you will merge this although CI is not completely green due to regression discovered by the world rebuild

*picks up admin hammer*

**ping**

*puts down admin hammer*

Thanks for the fix!

**Pull request merged**
