### PR TITLE
[nameof] Update to 0.9.3

### PR DESCRIPTION
**Pull request by Neargye**
https://github.com/Neargye/nameof/releases/tag/v0.9.3

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by c72578** [comment]
@Neargye could you please edit the first comment and update the link in the PR above to:
https://github.com/Neargye/nameof/releases/tag/v0.9.3

The current link points to magic_enum.

**Comment by Neargye** [comment]
@c72578 Oh, thanks for notices, update link in the PR.

**Comment by dan-shaw** [comment]
Thanks for the PR!

**Pull request merged**
