### PR TITLE
[imgui] Update to 1.87 [implot] Update to 0.13

### PR DESCRIPTION
**Pull request by RT2Code**
Update the imgui port from 1.86 to 1.87 and the implot port from 0.12 to 0.13.

Changelogs :
https://github.com/ocornut/imgui/releases/tag/v1.87
https://github.com/epezent/implot/releases/tag/v0.13

### CODE REVIEW

**Comment by JonLiu1993** [comment]
@RT222 ,Thanks for your pr, looks ci failed on x64_osx triplet,
This is error log:
[install-x64-osx-dbg-out.log](https://github.com/microsoft/vcpkg/files/8021205/install-x64-osx-dbg-out.log)

**Comment by RT222** [comment]
I added a patch to fix this and also submitted a PR upstream : https://github.com/epezent/implot/pull/322

**Comment by RT222** [comment]
I have a question about how I should update this port in the future. It's not in implot goals to support pre C++11 compiler (https://github.com/epezent/implot/pull/322#issuecomment-1033291059), but from my understanding, it's what is used to build for osx. I am completely clueless about this platform, but patching implot continually to support it doesn't seem very realistic in the long term as the library will growth and the patch will get bigger and uglier.

What is the best way to handle this? Am I mistaken and it there a way to build C++11 libraries on osx, or should we remove the support of this platform for implot?

**Comment by RT222** [comment]
Nevermind, I suddenly remembered cmake default to c++03

**Comment by RT222** [comment]
Nevermind, I suddenly realized the c++ standard could simply be configured through the cmake file. (sorry about the close, I missclicked).

**Review by JonLiu1993 — APPROVED** [review]

**Comment by ras0219-msft** [comment]
LGTM, thanks for the update!

**Pull request merged**
