### PR TITLE
[mpir] Fix download REF and HASH

### LINKED ISSUE #23328: [mpir] Build error
**Host Environment**
- OS: Windows
- Compiler:     
    vcpkg-tool version: 2022-02-24-7efe7f2b04912a7d674f86a406f9f2711c0221c6
    vcpkg-scripts version: 1b1ae50e1 2022-02-25 (3 days ago)

**To Reproduce**
`.\vcpkg\vcpkg install mpir:x86-windows-static`

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    mpir[core]:x86-windows-static -> 3.0.0#11
Detecting compiler hash for triplet x86-windows-static...
Restored 0 packages from C:\Users\Administrator\AppData\Local\vcpkg\archives in 123.2 us. Use --debug to see more details.
Starting package 1/1: mpir:x86-windows-static
Building package mpir[core]:x86-windows-static...
-- Using community triplet x86-windows-static. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: C:\Users\Administrator\vcpkg\triplets\community\x86-windows-static.cmake
-- Downloading https://github.com/wbhart/mpir/archive/mpir-3.0.0.tar.gz -> wbhart-mpir-mpir-3.0.0.tar.gz...
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Downloading https://github.com/wbhart/mpir/archive/mpir-3.0.0.tar.gz
Error: Failed to download from mirror set:
https://github.com/wbhart/mpir/archive/mpir-3.0.0.tar.gz: failed: **status code 300**

[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(705)
[DEBUG] Time in subprocesses: 0 us
[DEBUG] Time in parsing JSON: 2 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 3809 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 847.6 ms (630145 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:84 (message):

      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.

      3. Your proxy's remote server is out of service.

      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:309 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:175 (vcpkg_download_distfile)
  ports/mpir/portfile.cmake:59 (vcpkg_from_github)
  scripts/ports.cmake:145 (include)

Error: Building package mpir:x86-windows-static failed with: BUILD_FAILED

**Additional context**
I opened this url https://github.com/wbhart/mpir/archive/mpir-3.0.0.tar.gz in Google Chrome, it turns out `the given path has multiple possibilities: #<Git::Ref:0x00007ff572232868>, #<Git::Ref:0x00007ff5722316e8>`, so I guess this url lacks of some params?

### PR DESCRIPTION
**Pull request by JackBoosY**
The origin one is invalid.

Fixes #23328.

### CODE REVIEW

**Comment by dg0yt** [comment]
I would suggest to use the same download for Windows as for non-Windows.

**Comment by JackBoosY** [comment]
@dg0yt Yeah but it has risk.

**Comment by dg0yt** [comment]
> @dg0yt Yeah but it has risk.

Using two different downloads is the most risky option at all, with regard to consistency and to fragility.

Downloading tarballs for refs has a specific risk: GH reserves the right to change the tar implementation for this case. But it promises to keep release tarballs unchanged IIRC.

**Comment by JackBoosY** [comment]
@dg0yt Done, please review again.

**Review by LilyWangLL — APPROVED** [review]

**Comment by ras0219-msft** [comment]
From the website http://mpir.org/:

> MPIR is community maintained with a continuous development model. There are no official releases. For the latest code, please refer to the development repositories.
>
> For Linux/OSX:
>
>     git clone git://github.com/wbhart/mpir.git mpir
> 
> For Windows MSVC
>
>     git clone git://github.com/BrianGladman/mpir.git mpir

I think it's fine to use the wbhart fork as our single source. Because upstream has declared that there will be no more official releases, we need to move to date-based versioning.

**Comment by JackBoosY** [comment]
@ras0219-msft Done.

**Pull request merged**
