### PR TITLE
[openCV] add vulkan support for openCV dnn

### PR DESCRIPTION
**Pull request by sethome2**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] SHA512s are updated for each updated download
- [ ] The "supports" clause reflects platforms that may be fixed by this new version
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [ ] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

I found the openCV missing Vulkan support, which is a new backend of openCV::dnn module. Now openCV supports openvion, cuda and Vulkan, so I think vulkan should be added to vcpkg package list.

I was check the function of Vulkan work normally in X64-windows.
image

Thanks for your time to check the pr.

### CODE REVIEW

**Comment by LilyWangLL** [comment]
Feature `opencv4[vulkan]` passed with following triplets:
```
x86-windows
x64-windows
x64-windows-static
```

**Comment by LilyWangLL** [comment]
Please modify `port-version` in `vcpkg.json`, see https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md#update-the-port-version-field-in-the-manifest-file-of-any-modified-ports.

**Comment by sethome2** [comment]
> Please modify `port-version` in `vcpkg.json`, see https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md#update-the-port-version-field-in-the-manifest-file-of-any-modified-ports.

I am so sorry that I missed checking this file. Now I modified the port-version of opencv and opencv4, and then run this command 
```
vcpkg x-add-version opencv4
vcpkg x-add-version opencv
```
to update the baseline.

**Review by LilyWangLL — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks!

**Pull request merged**
