### PR TITLE
[libiconv] Fix usage

### LINKED ISSUE #22539: [iconv] How to use with vcpkg? `vcpkg install iconv` then "Could not find a package configuration file"
Library name: iconv
CMake: https://cmake.org/cmake/help/latest/module/FindIconv.html

```cmake
include(FindIconv) # Attempted without this line also
find_package(iconv CONFIG REQUIRED)
```

After running this on 371be89c1e3bc42c71ee325193daa083e3d75d8f:
```
$ ./vcpkg install libiconv
Computing installation plan...
The following packages will be built and installed:
    libiconv[core]:x64-osx -> 1.16#11
Detecting compiler hash for triplet x64-osx...
Restored 1 packages from .cache/vcpkg/archives in 14.66 ms. Use --debug to see more details.
Starting package 1/1: libiconv:x64-osx
Installing package libiconv[core]:x64-osx...
Elapsed time for package libiconv:x64-osx: 2.29 ms

Total elapsed time: 2.654 s

The package libiconv provides CMake targets:

    find_package(iconv CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Iconv::Charset)
```

NOTE: I am debugging this issue from Intl in vcpkg:
```
Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      __nl_find_msg in libintl.a(dcigettext.o)
  "_iconv_open", referenced from:
      __nl_find_msg in libintl.a(dcigettext.o)
  "_libiconv_set_relocation_prefix", referenced from:
      _libintl_set_relocation_prefix in libintl.a(relocatable.o)
```

Which made me think the wrong libiconv was being found, so I'm trying to explicitly specify the vcpkg one.

### PR DESCRIPTION
**Pull request by Thomas1664**
**Describe the pull request**

- #### What does your PR fix?
  Fixes #22539

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  unchanged

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

### CODE REVIEW

**Comment by JonLiu1993** [comment]
@Thomas1664 ,Thanks for your pr, have you tested  the usage?

**Comment by dg0yt** [comment]
@JonLiu1993 This is canonical usage: https://cmake.org/cmake/help/v3.21/module/FindIconv.html?highlight=findiconv

**Comment by JonLiu1993** [comment]
> @JonLiu1993 This is canonical usage: https://cmake.org/cmake/help/v3.21/module/FindIconv.html?highlight=findiconv

Thanks for your clarify

**Review by JonLiu1993 — APPROVED** [review]

**Comment by strega-nil-ms** [comment]
Thanks!

**Pull request merged**
