### PR TITLE
[vcpkg-tool] Add -DPIC to pic flags on Linux

### LINKED ISSUE #13827: [MPIR:x64-linux] build failure (static linking)
**Host Environment**
- OS: Linux (Ubuntu 20)
- Compiler: g++ 9.3

**To Reproduce**
```sh
./vcpkg install cgal eigen3
git clone https://github.com/amakhno/vcpkg-gmp-bug-example.git
cd vcpkg-gmp-bug-example
cmake . && make
```

**Failure logs** 
vcpkg install works perfectly but I have an error during the project build (linking)
```log
-- Using header-only CGAL
-- Targetting Unix Makefiles
-- Using /usr/bin/c++ compiler.
-- Boost include dirs: /home/noir/projects/vcpkg/installed/x64-linux/include
-- Boost libraries:    
-- Using gcc version 4 or later. Adding -frounding-math
CMake Warning at /home/noir/projects/vcpkg/installed/x64-linux/share/cgal/CGAL_enable_end_of_configuration_hook.cmake:99 (message):
  =======================================================================

  CGAL performance notice:

  The variable CMAKE_BUILD_TYPE is set to "".  For performance reasons, you
  should set CMAKE_BUILD_TYPE to "Release".

  Set CGAL_DO_NOT_WARN_ABOUT_CMAKE_BUILD_TYPE to TRUE if you want to disable
  this warning.

  =======================================================================
Call Stack (most recent call first):
  CMakeLists.txt:9999 (CGAL_run_at_the_end_of_configuration)


-- Configuring done
-- Generating done
-- Build files have been written to: /home/noir/projects/vcpkg-bug-example
[ 50%] Linking CXX shared library libexample.so
/usr/bin/ld: /home/noir/projects/vcpkg/installed/x64-linux/debug/lib/libgmp.a(modexact_1c_odd.o): relocation R_X86_64_PC32 against symbol `__gmp_modlimb_invert_table' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/example.dir/build.make:86: libexample.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/example.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

**Additional context**
There is no such a problem when you try to buld it with a dynamic library or a console application. 
I've tried to reinstall vcpkg completely but it didn't help. 
The same project works like a charm with :windows-x64-static on my Windows machine.

As I googled, it's likely that linux default triplet is x64-linux which is static, but I couln't find any reasons why it doesn't work

The problem is probably in MPIR but I'm not sure

### PR DESCRIPTION
**Pull request by lrineau**
**Describe the pull request**

Because `/usr/bin/libtool` has that line of code:
```shell
pic_flag=" -fPIC -DPIC"
```
That macro definition `PIC` can trigger different assembler code, as for example in GMP assembler code.

**Note:* I think the same bug applies to the other toolchains using `-fPIC`:
```
scripts/toolchains/android.cmake
scripts/toolchains/freebsd.cmake
scripts/toolchains/ios.cmake
scripts/toolchains/openbsd.cmake
scripts/toolchains/linux.cmake
scripts/toolchains/osx.cmake
```
but I can test only on Linux. Should I commit a similar change in all those files, and let the CI scripts and others test locally? In my opinion, I hardly see how adding `-DPIC` can harm.

- #### What does your PR fix?
  Fixes #13827.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  all

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  yes I think so

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  not applicable

### CODE REVIEW

**Comment by Neumann-A** [comment]
Rebuild gmp with #25009 merged in. An retry the issue in #13827. Currently the linker flags are not correctly passed if i remember correctly.

According to docs. `-fPIC` defines `__PIC__ ` so upstream should check against that and not a arbitrary define added by libtool.

**Comment by lrineau** [comment]
> Rebuild gmp with #25009 merged in. An retry the issue in #13827. Currently the linker flags are not correctly passed if i remember correctly.

I have tried to merge #25009 in `master` but I still had the issue #13827. Only the define of `-fPIC` fixes it.

> According to docs. `-fPIC` defines `__PIC__ ` so upstream should check against that and not a arbitrary define added by libtool.

Do you mean that this PR will not be accepted? The upstream GMP project documents that `--with-pic` should be added to `./configure`. But @BillyONeal said in https://github.com/microsoft/vcpkg/issues/13827#issuecomment-1150203335 that the enabling of PIC should be from the toolchain, and not from the GMP port file. That is why I have created this PR (#25158).

**Comment by JonLiu1993** [comment]
@lrineau, Thanks for your pr, looks ci test failed on x64-linux triplet
This is error log, please take a look:
llvm:
[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/8888345/install-x64-linux-dbg-out.log)
libmikmod:
[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/8888365/install-x64-linux-dbg-out.log)

**Comment by lrineau** [comment]
> @lrineau, Thanks for your pr, looks ci test failed on x64-linux triplet
> This is error log, please take a look:
> llvm:
> [install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/8888345/install-x64-linux-dbg-out.log)
> libmikmod:
> [install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/8888365/install-x64-linux-dbg-out.log)


For `libmikmod`, I do not understand the error, and how it might be related to `PIC` being a macro.

As for `llvm`, there is an understandable issue: `PIC` is used as a symbol name in the code:
```
llvm/include/llvm/MC/MCObjectFileInfo.h:237:52: note: in expansion of macro ‘PIC’
  237 |   void initMCObjectFileInfo(MCContext &MCCtx, bool PIC,
      |                                                    ^~~
```

That means `PIC` cannot be defined by the toolchain. I close this PR, and will try again to act on the `gmp` port itself.

**Pull request closed without merging**
