### PR TITLE
Librsvg port

### PR DESCRIPTION
**Pull request by Kwizatz**
These are the initial commits for a new librsvg port.

Fulfills PR for issue #3865

### CODE REVIEW

**Comment by Kwizatz** [comment]
So, what I see is that the tests passed but some policy failed? not sure what the problem is, I can build the library on my Linux box as is.

**Comment by Rastaban** [comment]
It looks like the cmake config had errors.  If it works on your computer it is possible there is a missing dependency on the CI machines.  You can get the logs here: https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/2062/artifacts?artifactName=port%20build%20failure%20logs&api-version=5.1-preview.5&%24format=zip

```
Starting package 22/22: librsvg:x64-linux
Building package librsvg[core]:x64-linux...
Could not locate cached archive: /home/vcpkg/myagent/_work/4/s/archives/eb/eb1e596be119400b2413a5d250897a1c452924cc.zip
-- Downloading https://download.gnome.org/sources/librsvg/2.40/librsvg-2.40.20.tar.xz...
-- Extracting source /home/vcpkg/myagent/_work/4/s/downloads/librsvg-2.40.20.tar.xz
-- Using source at /home/vcpkg/myagent/_work/4/s/buildtrees/librsvg/src/librsvg-2-a2e28f96fe
-- Configuring x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: /home/vcpkg/myagent/_work/4/s/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/bin/cmake;/home/vcpkg/myagent/_work/4/s/buildtrees/librsvg/src/librsvg-2-a2e28f96fe;-DCMAKE_MAKE_PROGRAM=/home/vcpkg/myagent/_work/4/s/downloads/tools/ninja-1.8.2-linux/ninja;-DCMAKE_SYSTEM_NAME=Linux;-DBUILD_SHARED_LIBS=OFF;-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/vcpkg/myagent/_work/4/s/scripts/toolchains/linux.cmake;-DVCPKG_TARGET_TRIPLET=x64-linux;-DVCPKG_PLATFORM_TOOLSET=external;-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON;-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE;-DCMAKE_VERBOSE_MAKEFILE=ON;-DVCPKG_APPLOCAL_DEPS=OFF;-DCMAKE_TOOLCHAIN_FILE=/home/vcpkg/myagent/_work/4/s/scripts/buildsystems/vcpkg.cmake;-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON;-DVCPKG_CXX_FLAGS=;-DVCPKG_CXX_FLAGS_RELEASE=;-DVCPKG_CXX_FLAGS_DEBUG=;-DVCPKG_C_FLAGS=;-DVCPKG_C_FLAGS_RELEASE=;-DVCPKG_C_FLAGS_DEBUG=;-DVCPKG_CRT_LINKAGE=dynamic;-DVCPKG_LINKER_FLAGS=;-DCMAKE_INSTALL_LIBDIR:STRING=lib;-DCMAKE_INSTALL_BINDIR:STRING=bin;-G;Ninja;-DCMAKE_BUILD_TYPE=Debug;-DCMAKE_INSTALL_PREFIX=/home/vcpkg/myagent/_work/4/s/packages/librsvg_x64-linux/debug
    Working Directory: /home/vcpkg/myagent/_work/4/s/buildtrees/librsvg/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /home/vcpkg/myagent/_work/4/s/buildtrees/librsvg/config-x64-linux-dbg-out.log
      /home/vcpkg/myagent/_work/4/s/buildtrees/librsvg/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:282 (vcpkg_execute_required_process)
  ports/librsvg/portfile.cmake:17 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)


Error: Building package librsvg:x64-linux failed with: BUILD_FAILED
```

**Comment by Kwizatz** [comment]
This is odd, it is complaining that gdk-pixbuf is not installed, but it is listed in the CONTROL file:

Build-Depends: cairo, pango, gdk-pixbuf, libcroco

**Comment by NNemec** [comment]
I've just been successful in building this branch and loading pixbufloader-svg into my application. Everything appears to be working fine for me now!

**Comment by Kwizatz** [comment]
Are the tests somehow being run with a commit hash from the day the first commit was created? this should be fine if rebased on top of #6663, which should be the case if the tests either run from a fresh checkout of my branch or if the commits are cherry picked on top of the tip of master. The first commit (and the others might as well) likely does have a creation date from before #6663 merged.

**Comment by Rastaban** [comment]
When the tests run it does merge with the latest master on the CI system before building.  we can rerun the tests.

**Comment by Kwizatz** [comment]
@Rastaban Thank you for the follow up! 😁

**Pull request merged**
