### PR TITLE
[vcpkg] GENERATOR with Makefiles can build parallel

### LINKED ISSUE #26779: [vcpkg] GENERATOR with Makefiles can build parallel
****

**Is your feature request related to a problem? Please describe.**
GENERATOR with Makefiles the port build very slow

**Proposed solution**
GENERATOR with Makefiles can build parallel

**Describe alternatives you've considered**
#26780

**Additional context**
None

### PR DESCRIPTION
**Pull request by day253**
**Describe the pull request**

- #### What does your PR fix?
  Fixes #26779 

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  `all`, `Yes`

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  `Yes`

outdated PR #26596

I think the break change was related to #23259

### CODE REVIEW

**Review by JackBoosY — DISMISSED** [review]
Thanks for the fix!

**Comment by JackBoosY** [comment]
I will tracking the regressions.
Some regressions will be fixed in https://github.com/microsoft/vcpkg/pull/26771 and https://github.com/microsoft/vcpkg/pull/26646

**Comment by day253** [comment]
> Thanks for the fix!

I will check all the ci case when the pipeline end.

> #26646

Thanks!

**Comment by day253** [comment]
> I will track the regressions. Some regressions will be fixed in #26771 and #26646

Thanks!

**Comment by JackBoosY** [comment]
It looks that we only have saucer regression, so please wait for #26783 merge first.

**Comment by day253** [comment]
> #26783

No problem.

**Review by vicroms — DISMISSED** [review]

**Comment by vicroms** [comment]
Approved but not merged. I tried fixing the merge conflicts but don't have permission to push to your repo.

**Comment by day253** [comment]
> Approved but not merged. I tried fixing the merge conflicts but don't have permission to push to your repo. 

I will fix the conflicts today.

**Comment by day253** [comment]
> > Approved but not merged. I tried fixing the merge conflicts but don't have permission to push to your repo.
> 
> I will fix the conflicts today.

@vicroms @JackBoosY I add you two as members of my repo. I merged the master branch into my branch. All tests have passed.

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
Thanks for this PR!

**Pull request merged**
