### PR TITLE
[polyhook2] Update polyhook to latest

### PR DESCRIPTION
**Pull request by stevemk14ebr**
**Describe the pull request**
Updates to latest polyhook this is nearly identical to what the repo was for https://github.com/microsoft/vcpkg/pull/11561#event-3395518836 except i moved some header implementations to their own source files.

- What does your PR fix? Fixes #
Updates to latest polyhook which fixes a bug with the logging level not being setable.

- Which triplets are supported/not supported? Have you updated the CI baseline?
x86-windows-static
x86-windows
x64-windows
x64-windows-static

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yup

### CODE REVIEW

**Review by PhoebeHui — COMMENTED** [review]
Thanks for the PR!

Could you also sign CLA?

**Comment by stevemk14ebr** [comment]
Where do I sign

**Comment by stevemk14ebr** [comment]
@PhoebeHui The CLA doesn't work: https://github.com/microsoft/vcpkg/issues/3414. I give whatever permissions are necessary

**Comment by stevemk14ebr** [comment]
Bumped the version again to reflect polyhook2 upstream changes. Note: Looks like the CLA bot has a bug, it didn't showup before, perhaps add a command to invoke it via comment?

**Review by PhoebeHui — APPROVED** [review]

**Comment by PhoebeHui** [comment]
I'm not sure why it didn't showup before. 

The changes looks good for me. thanks for the PR!

**Review by dan-shaw — APPROVED** [review]

**Comment by stevemk14ebr** [comment]
I'm doing continuous work on polyhook i'm going to keep bumping this version until a merge occurs. Please don't let this delay the merge at all im just sneaking fixes in until it's done

**Comment by dan-shaw** [comment]
It looks good to me. Just want to make sure we get a green checkmark before merging this.

**Comment by stevemk14ebr** [comment]
Looks like something else is breaking the pipeline

**Comment by dan-shaw** [comment]
Thanks for the PR!

**Pull request merged**
