### PR TITLE
Update qt5 to 5.12.1 and add some missing modules

### PR DESCRIPTION
**Pull request by renshi-code**
still missing are androidextras, macextras, x11extras, webengine, webglplugin, webview, serialbus.
Also still fixing the Linux error, got to SQLite working. PSQL is still broken (but qt is not failing because of it now) and OpenGL libraries are needed on Linux (thinking about making it a dependency but I don't know how to check for installed packages)

### CODE REVIEW

**Comment by TheScarfix** [comment]
thinking about using features for the qt5 port instead of putting everything in as default. What do you think?

**Comment by Zingam** [comment]
> thinking about using features for the qt5 port instead of putting everything in as default. What do you think?

Could you, please, explain?

**Comment by TheScarfix** [comment]
@Zingam sure :) I would split the qt5 port into features like quick, web, GUI, plugins so that when you install qt5 only the base is installed and not the whole framework. The other modules are installed via features or by specifying them like it is now. So the qt[quick] for example would include qt5-base, qt5-declarative, qt5-quickcontrols and qt5-quickcontrols2.

**Comment by Zingam** [comment]
Sounds great! What about Web related stuff?

**Comment by TheScarfix** [comment]
@Zingam some modules are still not working and I currently don't know how to get them to work if that's what you mean. So the web feature would be a thing for the future with webengine and other related modules.

**Comment by TheScarfix** [comment]
fixes #3859 #5038 #4804

**Comment by vicroms** [comment]
Excellent job @TheScarfix!

Looks like there are no regressions, so I'll merge this PR.
Here's the current status of Qt 5 on each platform.

package|arm-uwp|arm64-windows|x64-linux|x64-osx|x64-uwp|x64-windows|x64-windows-static|x86-windows
--|--|--|--|--|--|--|--|--
qt5|skip|skip|skip|skip|skip|pass|skip|pass
qt5-3d|skip|skip|skip|skip|skip|pass|skip|pass
qt5-activeqt|skip|skip|fail|skip|skip|pass|fail|pass
qt5-base|skip|skip|pass|skip|skip|pass|pass|pass
qt5-charts|skip|skip|fail|skip|skip|pass|pass|pass
qt5-connectivity|skip|skip|fail|skip|skip|pass|pass|pass
qt5-datavis3d|skip|skip|fail|skip|skip|pass|pass|pass
qt5-declarative  |skip|skip|fail|skip|skip|pass|fail|pass
qt5-gamepad |skip|skip|fail|skip|skip|pass|pass|pass
qt5-graphicaleffects|skip|skip|skip|skip|skip|pass|skip|pass
qt5-imageformats|skip|skip|fail|skip|skip|pass|pass|pass
qt5-location|skip|skip|skip|skip|skip|pass|skip|pass
qt5-modularscripts|pass|pass|pass|pass|pass|pass|pass|pass
qt5-multimedia|skip|skip|skip|skip|skip|pass|skip|pass
qt5-networkauth|skip|skip|fail|skip|skip|pass|pass|pass
qt5-purchasing|skip|skip|fail|skip|skip|pass|fail|pass
qt5-quickcontrols|skip|skip|skip|skip|skip|pass|skip|pass
qt5-quickcontrols2|skip|skip|skip|skip|skip|pass|skip|pass
qt5-remoteobjects|skip|skip|fail|skip|skip|pass|fail|pass
qt5-script|skip|skip|fail|skip|skip|pass|pass|pass
qt5-scxml|skip|skip|skip|skip|skip|pass|skip|pass
qt5-sensors|skip|skip|fail|skip|skip|pass|pass|pass
qt5-serialport|skip|skip|fail|skip|skip|pass|pass|pass
qt5-speech|skip|skip|fail|skip|skip|pass|pass|pass
qt5-svg|skip|skip|fail|skip|skip|pass|pass|pass
qt5-tools|skip|skip|skip|skip|skip|pass|skip|pass
qt5-virtualkeyboard|skip|skip|fail|skip|skip|pass|pass|pass
qt5-webchannel|skip|skip|fail|skip|skip|pass|pass|pass
qt5-websockets|skip|skip|fail|skip|skip|pass|pass|pass
qt5-winextras|skip|skip|skip|skip|skip|pass|pass|pass
qt5-xmlpatterns|skip|skip|fail|skip|skip|pass|fail|pass

**Comment by heydojo** [comment]
Missing QtWebEngine. If you can successfully get Qt to 5.12.4 then I might consider sharing my port if there is any interest.

**Pull request merged**
