### PR TITLE
[guile] update to 3.0.9

### PR DESCRIPTION
**Pull request by jiayuehua**
- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [X] SHA512s are updated for each updated download
- [ ] ~The "supports" clause reflects platforms that may be fixed by this new version~
- [ ] ~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~
- [ ] ~Any patches that are no longer applied are deleted from the port's directory.~
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Review by WangWeiLin-MV — APPROVED** [review]

**Review by WangWeiLin-MV — CHANGES_REQUESTED** [review]
According to the upstream documentation update https://git.savannah.gnu.org/gitweb/?p=guile.git;a=commit;h=98dff7a75e672f98154c52a2ceb00e2c9015a06b, the build requires the tool `gperf`. The port needs to be adapted or more info added. Could you help to fix it?

**Comment by jiayuehua** [comment]
I don't know how to add gperf requirement.

**Comment by WangWeiLin-MV** [comment]
> I don't know how to add gperf requirement.

This patch should work.
```diff
diff --git a/ports/guile/portfile.cmake b/ports/guile/portfile.cmake
index e8bbbb410..12da6e0b0 100644
--- a/ports/guile/portfile.cmake
+++ b/ports/guile/portfile.cmake
@@ -6,6 +6,8 @@ vcpkg_download_distfile(GUILE_ARCHIVE
 
 vcpkg_extract_source_archive(GUILE_SOURCES ARCHIVE ${GUILE_ARCHIVE})
 
+vcpkg_add_to_path("${CURRENT_HOST_INSTALLED_DIR}/tools/gperf")
+
 vcpkg_configure_make(
     SOURCE_PATH "${GUILE_SOURCES}"
     ADD_BIN_TO_PATH
diff --git a/ports/guile/vcpkg.json b/ports/guile/vcpkg.json
index 01ccab5c5..192fd57ec 100644
--- a/ports/guile/vcpkg.json
+++ b/ports/guile/vcpkg.json
@@ -17,6 +17,10 @@
       ]
     },
     "gmp",
+    {
+      "name": "gperf",
+      "host": true
+    },
     "libffi",
     "libunistring"
   ]

```

**Review by WangWeiLin-MV — APPROVED** [review]
Port usage tests pass with following triplets:
* x64-linux

**Comment by BillyONeal** [comment]
Thanks for the update!

**Pull request merged**
