### PR TITLE
[lz4] Update to version 1.10.0 and use the official CMake build system.

### PR DESCRIPTION
**Pull request by teo-tsirpanis**
- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [X] SHA512s are updated for each updated download.
- [ ] The "supports" clause reflects platforms that may be fixed by this new version.
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [X] Any patches that are no longer applied are deleted from the port's directory.
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by dg0yt** [comment]
libarchive stumbles over `-llz4::lz4`. Either it imports from a now-invalid pc file, or from now-invalid CMake package variables.

**Comment by dg0yt** [comment]
The cmake namespace change (`lz4::lz4` to LZ4::lz4`, very unfortunate given the case-sensitive `lz4` package name) will also affect vcpkg user projects. Does it make sense to keep `lz4::lz4` for a while to facilitate migrations?

Before starting and finishing this comment, I did https://github.com/lz4/lz4/issues/1179#issuecomment-2245364741.

**Comment by teo-tsirpanis** [comment]
Superseded by #40052. Thanks @dg0yt!

**Pull request closed without merging**
