### PR TITLE
[openssl] do not try to install openssl as tool if cross-compiling

### LINKED ISSUE #29948: [openssl] now requires pwsh on mingw/linux for no good reason
**Host Environment**

- OS: Ubuntu 20.04
- Compiler: x86_64-w64-mingw32-g++ (GCC) 9.3-win32 20200320

**To Reproduce**

`./vcpkg install openssl --triplet=x64-mingw-dynamic`

**Failure logs**

``` 
CMake Error at scripts/cmake/vcpkg_copy_tool_dependencies.cmake:31 (message):
  Could not find PowerShell Core; please open an issue to report this.
Call Stack (most recent call first):
  scripts/cmake/vcpkg_copy_tools.cmake:48 (vcpkg_copy_tool_dependencies)
  ports/openssl/unix/portfile.cmake:118 (vcpkg_copy_tools)
  ports/openssl/portfile.cmake:60 (include)
  scripts/ports.cmake:147 (include)
```
This worked fine until 9ccc64ca98b320404d059df4349220bd2c1b4a46

**Additional context**

Probably we shouldn't actually install the tool when cross-compiling? It is unusable anyway, right?

### PR DESCRIPTION
**Pull request by flichtenheld**
It is not usable anyway. This also avoids an unnecessary pwsh dependency.

Fixes #29948

- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] ~SHA512s are updated for each updated download~
- [ ] ~The "supports" clause reflects platforms that may be fixed by this new version~
- [ ] ~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~
- [ ] ~Any patches that are no longer applied are deleted from the port's directory.~
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by flichtenheld** [comment]
@microsoft-github-policy-service agree company="OpenVPN"

**Comment by dg0yt** [comment]
Maybe it is time to make the tools an optional feature?

> It is not usable anyway. 

Why do you think it is not usable?

**Comment by dg0yt** [comment]
> It is not usable anyway.

It is usable, https://github.com/microsoft/vcpkg/issues/29948#issuecomment-1451414459.

**Comment by flichtenheld** [comment]
Superseded by #29966

**Pull request closed without merging**
