### PR TITLE
[vcpkg|scripts] pass caller and port info to get_cmake_vars

### PR DESCRIPTION
**Pull request by Neumann-A**
Why is this necessary?

Customization of toolchain independent of triplet but dependent on the caller of get_cmake_vars.

E.g. (Windows)
Autotool ports typically link by invoking the compiler instead of the linker which requires a different set of link flags than CMake. On the other hand CMake rules could be changed to use compiler instead of the linker which then requires other link flags for buildsystems which invoke the linker directly. (which is a requirement to get sanitizers working on all buildsystems [meson currently being broken for static library linkage since I cannot pass different flags for exe/dll linkage])

So TL;DR I need a customization/filter point which is less fine grained than per port customization and can filter by buildsystem and act accordingly.  

@Osyotr: To give you mere context: I need to pass the following to the linker:
```
      set(sanitizer_libs "clang_rt.ubsan_standalone-x86_64.lib clang_rt.ubsan_standalone_cxx-x86_64.lib")
      if(VCPKG_CRT_LINKAGE STREQUAL "dynamic")
        set(sanitizer_libs_exe "clang_rt.asan_dynamic-x86_64.lib clang_rt.asan_dynamic_runtime_thunk-x86_64.lib")
        set(sanitizer_libs_dll "${sanitizer_libs_exe}")
      else()
        set(sanitizer_libs_exe "/wholearchive:clang_rt.asan-x86_64.lib /wholearchive:clang_rt.asan_cxx-x86_64.lib")
        set(sanitizer_libs_dll "clang_rt.asan_dll_thunk-x86_64.lib")
      endif()
```
or invoke the link through the compiler with:
```
    set(sanitizers "undefined,alignment,null")
    if(VCPKG_USE_LTO)
      string(APPEND sanitizers ",cfi")
    else()
      string(APPEND sanitizers ",address") # lld-link: error: /alternatename: conflicts: __sanitizer_on_print=__sanitizer_on_print__def
    endif()
    string(APPEND CLANG_FLAGS_RELEASE "-fsanitize=${sanitizers} -fsanitize-stats")
```

Neither autotools nor meson allow the former for static CRT builds.  While the second possibility is currently not possible for meson.

### CODE REVIEW

**Review by FrankXie05 — APPROVED** [review]

**Comment by BillyONeal** [comment]
>So TL;DR I need a customization/filter point which is less fine grained than per port customization and can filter by buildsystem and act accordingly.

I don't see how this change achieves that: it seems like it would require some other corresponding change in vcpkg_cmake_get_vars that knows about every port and what their build system is, which seems inappropriate.

Moreover, what the function is documented to do is tell you what CMake does, the right place to fix up what autotools wants is not in the "tell me what CMake does" function.

Can you describe the behavior change you're looking to get in concrete terms rather than a callee assuming implementation details about the caller?

**Comment by Neumann-A** [comment]
@BillyONeal 
https://github.com/Neumann-A/my-vcpkg-triplets/blob/5675339a4534bcf69a762dc6a4e61dc98b41aeba/x64-win-llvm/extra_setup.cmake#L37-L44
https://github.com/Neumann-A/my-vcpkg-triplets/blob/5675339a4534bcf69a762dc6a4e61dc98b41aeba/x64-win-llvm/x64-win-llvm.toolchain.cmake#L3-L7
https://github.com/Neumann-A/my-vcpkg-triplets/blob/5675339a4534bcf69a762dc6a4e61dc98b41aeba/x64-win-llvm/x64-win-llvm.toolchain.cmake#L124-136

But it could very well be that everything has to be put into wrapper scripts including the flags which then decides if the compiler or the linker gets called depending on how the scripts gets called

**Comment by BillyONeal** [comment]
> But it could very well be that everything has to be put into wrapper scripts including the flags which then decides if the compiler or the linker gets called depending on how the scripts gets called

It might make sense to have a flag like `USE_COMPILER_AS_LINKER` or similar that can get passed around. It needs to be expressed in terms of the change in effect you're trying to achieve, not who the caller happens to be. If tomorrow we added `vcpkg_build_super_meson` or something that wanted the same behavior, it would be inappropriate to require everyone writing their own triplet to need to special case everything.

**Comment by Neumann-A** [comment]
> It might make sense to have a flag like USE_COMPILER_AS_LINKER or similar that can get passed around. It needs to be expressed in terms of the change in effect you're trying to achieve, not who the caller happens to be. If tomorrow we added vcpkg_build_super_meson or something that wanted the same behavior, it would be inappropriate to require everyone writing their own triplet to need to special case everything.

That is why I say that the 100% correct solution would be to overrule any buildsystem except cmake with a generated compiler/linker wrapper which calls the compiler/linker as cmake would do it using the platform information supplied by cmake, e.g. for windows-msvc:
https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/Platform/Windows-MSVC.cmake#L356
https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/Platform/Windows-MSVC.cmake#L362
https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/Platform/Windows-MSVC.cmake#L370-L371

but this is probably very time intensive to implement correctly so just give people an easy way to deal with it themselves until a better solution is developed.

**Comment by FrankXie05** [comment]
Turn this PR into a draft before finishing it.

**Pull request closed without merging**
