### PR TITLE
[proxywrapper] Remove proxywrapper package

### PR DESCRIPTION
**Pull request by shishirb-MSFT**
[proxywrapper] Remove package.

- #### What does your PR fix?  
  This PR deletes the proxywrapper vcpkg port. The proxywrapper repo is unused and is scheduled to be deleted. 
  See: https://github.com/microsoft/proxy-wrapper/issues/3

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  n/a

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  n/a

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by shishirb-MSFT** [comment]
CI checks passed. Moving PR out of draft stage.

**Comment by PhoebeHui** [comment]
@ras0219-msft, do we need remove proxywrapper from baseline.json, also remove the version/p-/proxywrapper.json file?

**Comment by ras0219-msft** [comment]
The `version/p-/proxywrapper.json` file must remain, however we should remove it from `baseline.json`.

**Review by ras0219-msft — APPROVED** [review]

**Comment by PhoebeHui** [comment]
The cnl issue would be fixed by PR https://github.com/microsoft/vcpkg/pull/18767, please ignore it.

**Comment by shishirb-MSFT** [comment]
@PhoebeHui thanks for reviewing and getting the necessary updates done. Is there anything else needed from my side? Or we just waiting for the cnl issue to be fixed before merging this PR?

**Comment by PhoebeHui** [comment]
@shishirb-MSFT, we only need to wait for the CI issue to be fixed. No more actions required from your side.

**Comment by ras0219-msft** [comment]
Thanks for the PR!

**Pull request merged**
