### PR TITLE
[toolchain] Toolchain update to remove /MP when using clang-cl custom triplets

### PR DESCRIPTION
**Pull request by walbourn**
When creating custom triplets that use clang/LLVM for Windows, the default windows, uwp, and xbox toolchains work for everything *except* they include ``/MP`` which generates a ton of warnings.

This PR updates these three platform toolchains to not use the ``/MP`` switch for this scenario.

> For all other cases, there is no change to parameters or order.

### CODE REVIEW

**Comment by walbourn** [comment]
> Please make `.exe` in `clang-cl.exe` optional.

Can you clarify when ``CMAKE_CXX_COMPILER`` is set to ``clang-cl``? Is it just that cmake works with our without it?

**Comment by unageek** [comment]
> Is it just that cmake works with our without it?

Yes, unless it is normalized somewhere (IDK).

**Comment by walbourn** [comment]
I just tried setting it to "clang-cl" and to "clang-cl.exe" and they both work. CMake normalized it to "<fullpath>\clang-cl.exe"

**Comment by unageek** [comment]
Thank you for the verification! I'm sorry that I didn't do that myself.

**Pull request merged**
