### PR TITLE
[azure] Update azure-iot-sdk-c for release of 2019-10-07

### PR DESCRIPTION
**Pull request by ewertons**
[azure] Update azure-iot-sdk-c for release of 2019-10-07

### CODE REVIEW

**Comment by ewertons** [comment]
Hey folks, could you help us get this in, please? 
We haven't changed anything in these port files other than the REFs and SHAs, the rest is all the same.

What is the regression these jobs are complaining about?
```
|x64-windows    |test|notes
|---------------|----|-----
|azure-iot-sdk-c|Skip|Missing port dependency
|azure-uhttp-c  |Fail|**Regression**
|azure-umqtt-c  |Fail|**Regression**


Uncompressing w:\fail\9d\9d8b2d8302c7043315c45e93f09741b2dd85cd76.zip to C:\vsts\_work\2\a\failureLogs\x64-windows\
Uncompressing w:\fail\e9\e9c97a647c0169d95a64532433d32a03d060394e.zip to C:\vsts\_work\2\a\failureLogs\x64-windows\
##[error] REGRESSION: azure-uhttp-c:x64-windows
##[error] REGRESSION: azure-umqtt-c:x64-windows
##[section]Finishing: Analyze results and prepare test logs
```

**Comment by ras0219-msft** [comment]
When cracking open the log, I see the following issue during configure:
```
CMake Error at C:/vsts/_work/2/s/installed/x64-windows/share/azure_c_shared_utility/azure_c_shared_utilityFunctions.cmake:643 (if):
  if given arguments:

    "OR" "(" "STREQUAL" "ON_WITH_CONSOLE" ")"

  Unknown arguments specified
Call Stack (most recent call first):
  CMakeLists.txt:112 (set_platform_files)


-- Configuring incomplete, errors occurred!
```

**Comment by ewertons** [comment]
All fixed! Could you please merge it? thanks

**Comment by vicroms** [comment]
Thanks for the PR!

**Pull request merged**
