### PR TITLE
[PEGTL] Upgrade to 2.8.0

### PR DESCRIPTION
**Pull request by zhihaoy**
Migration guide:
https://github.com/taocpp/PEGTL/blob/master/doc/Migration-Guide.md#version-280

### CODE REVIEW

**Comment by Rastaban** [comment]
It looks like this PR is causing a build failure in cppgraphqlgen on x64-windows and x64-windows-static.  I haven't looked at the logs, but it looks like there were some changes in the migration guide that may be the cause.

**Comment by zhihaoy** [comment]
> It looks like this PR is causing a build failure in cppgraphqlgen on x64-windows and x64-windows-static. I haven't looked at the logs, but it looks like there were some changes in the migration guide that may be the cause.

Guess what, it works on my machine™️ 
```
cppgraphqlgen:x86-windows                          2.1.0            C++ GraphQL schema service generator
pegtl:x86-windows                                  2.8.0            The Parsing Expression Grammar Template Library ...
```

Please take a look a the log, I suspect it's caused by compiler differences
```
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27027.1 for x64
```

**Comment by NancyLi1013** [comment]
Hi @zhihaoy, I see the logs and find some errors like these:
C:\vsts\_work\2\s\buildtrees\cppgraphqlgen\src\v2.1.0-e7b93728ae\GraphQLTree.cpp : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj
The compiler on CI is:
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27026.1 for x64

**Comment by zhihaoy** [comment]
Reproduced, my bad, I removed my environment variable recently and did not noticed that this repo is building x86 rather than x64.
Fixed.

**Comment by grdowns** [comment]
Thanks for the PR, @zhihaoy!

**Pull request merged**
