### PR TITLE
[msys2] Automatically detect SSL

### LINKED ISSUE #13286: [msys2] download components failure: SSL connect error
**Host Environment**
- Windows 8.1 Home x64
- MSVC++ 14.27 _MSC_VER == 1927 (Visual Studio 2019 Version 16.7)

**To Reproduce**
vcpkg install [ffmpeg] (no triplet does work, and no additional feature does matter)

**Failure logs** 
```
D:\Code\Repos\vcpkg>vcpkg install ffmpeg:x86-windows
Computing installation plan...
The following packages will be built and installed:
    ffmpeg[avcodec,avdevice,avfilter,avformat,avresample,core,postproc,swresample,swscale]:x86-windows
Detecting compiler hash for triplet x86-windows...
Starting package 1/1: ffmpeg:x86-windows
Building package ffmpeg[avcodec,avdevice,avfilter,avformat,avresample,core,postproc,swresample,swscale]:x86-windows...
Could not locate cached archive: C:\Users\Daniel\AppData\Local\vcpkg/archives\3f\3f551c8ffdfb689003869e2d0981ea9fa7bc696e.zip
-- Using cached D:/Code/Repos/vcpkg/downloads/ffmpeg-ffmpeg-n4.2.tar.gz
-- Extracting source D:/Code/Repos/vcpkg/downloads/ffmpeg-ffmpeg-n4.2.tar.gz
-- Applying patch 0001-create-lib-libraries.patch
-- Applying patch 0003-fix-windowsinclude.patch
-- Applying patch 0004-fix-debug-build.patch
-- Applying patch 0005-fix-libvpx-linking.patch
-- Applying patch 0006-fix-StaticFeatures.patch
-- Applying patch 0007-fix-lib-naming.patch
-- Applying patch 0008-Fix-wavpack-detection.patch
-- Applying patch 0009-Fix-fdk-detection.patch
-- Applying patch 0010-Fix-x264-detection.patch
-- Applying patch 0011-Fix-x265-detection.patch
-- Applying patch 0012-Fix-ssl-110-detection.patch
-- Using source at D:/Code/Repos/vcpkg/buildtrees/ffmpeg/src/n4.2-2f6d2343f6.clean
-- Downloading https://repo.msys2.org/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz... Failed. Status: 35;"SSL connect error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:178 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:97 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_acquire_msys.cmake:148 (msys_package)
  ports/ffmpeg/portfile.cmake:59 (vcpkg_acquire_msys)
  scripts/ports.cmake:79 (include)


Error: Building package ffmpeg:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: ffmpeg:x86-windows
  Vcpkg version: 2020.06.15-nohash
```

**Additional context**
Hello,

the issue here doesn't really seem to be a "port bug", because it affects all ports which need MSYS2 for building. The problem basically is that https://repo.msys2.org since a few days stricly disallows all other security protocols but TLS 1.3 - which users of other Windows OS but latest Windows 10 (like me) are unable to use for global WinHttp connections as it's simply not implemented in the resp. OS (and obviously never will be).

Since vcpkg apparently tries to acquire the package using PowerShell we are bound to WinHttp limits and the download has to fail, while 3rd-party-programs like e.g. wget, which support TLS 1.3 natively, are able to download from https://repo.msys2.org perfectly fine. So I actually have the package vcpkg tries to download for more than one hour on my HDD already, but fail to figure out where to place it so that vcpkg would pick it up (as quick bypass). Could you please tell me? Thank you.

The problem I mention here is a pretty huge one given that it effectively excludes all non-Win 10 users from the possibility to build MSYS2-dependent ports (which are not just a few as you surely know). I strongly recommend to add alternate download urls in addition to https://repo.msys2.org as soon as possible, thank you very much.

[ffmpeg.zip](https://github.com/microsoft/vcpkg/files/5158747/ffmpeg.zip)

### PR DESCRIPTION
**Pull request by JackBoosY**
When using https to download msys components in Windows 7, the download failed because the system does not support TLS> 1.2.
Add automatic detection and switch to http code.

Fixes #13286.

### CODE REVIEW

**Comment by BillyONeal** [comment]
I'm not sure how I feel about this. On the one hand, it is going to reenable this for Win7, on the other hand falling back to http when https fails largely defeats the purpose of https in the first place: an attacker who wants to see what you're visiting can MITM you and just block TLS entirely.

**Comment by ras0219** [comment]
Does this still repro when you pass `--x-use-aria2`? If not, I think the much better option would be to detect if the system is Windows7 and turn that on by default.

**Comment by JackBoosY** [comment]
@ras0219 Didn't work using parameter `--x-use-aria2`.

**Comment by BillyONeal** [comment]
We do not believe that regressing TLS support is an appropriate fix for this problem. We are left with the following options:

1. Fix `vcpkg` to expose a download file command, which we recursively invoke from our cmake scripts, which uses WinHTTP correctly or similar to keep TLS support turned on. (This is ultimately the correct fix)
2. Try to find some other downloader tool or similar that would work; that aria2 does not work suggests that this might be difficult.
3. Choose that TLS support is more important than Win7 support, which means not merging this change.
4. Optionally disable TLS only on Win7.
5. Choose that Win7 is more important than TLS, thus merging this change.

We believe TLS is more important than Win7 which excludes (5). I would personally also argue against (4) but it's technically workable.

**Comment by BillyONeal** [comment]
> @ras0219 Doesn't work using parameter `--x-use-aria2`.

What about if you set aria2's minimum TLS version to 1.2? As far as I understood TLS 1.3 servers are supposed to refuse attempts to handshake that offer TLS1.0 and TLS1.1 due to downgrade vulnerabilities.

@ras0219 suggests that we might be able to try updating aria2 since they have changed this default in a more recent verison.

**Comment by JackBoosY** [comment]
```
PS C:\vcpkg> .\vcpkg.exe install vcpkg-gfortran --x-use-aria2
...
-- Downloading msys-mingw-w64-i686-gcc-fortran-10.2.0-1-any.pkg.tar.zst...
-- Downloading msys-mingw-w64-i686-gcc-fortran-10.2.0-1-any.pkg.tar.zst... Faile
d.
    Exit Code: 1
    See logs for more information:
        C:/vcpkg/downloads/download-msys-mingw-w64-i686-gcc-fortran-10.2.0-
1-any.pkg.tar.zst-out.log
        C:/vcpkg/downloads/download-msys-mingw-w64-i686-gcc-fortran-10.2.0-
1-any.pkg.tar.zst-err.log
        C:/vcpkg/downloads/download-msys-mingw-w64-i686-gcc-fortran-10.2.0-
1-any.pkg.tar.zst-detailed.log

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:178 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/is
sues
...
```

```
2020-09-04 02:06:27.830898 [DEBUG] [SocketCore.cc:926] Creating TLS session
2020-09-04 02:06:27.830898 [DEBUG] [SocketCore.cc:946] TLS Handshaking
2020-09-04 02:06:27.830898 [DEBUG] [WinTLSSession.cc:585] WinTLS: Starting/Resuming TLS Connect
2020-09-04 02:06:27.830898 [DEBUG] [WinTLSSession.cc:604] WinTLS: Initializing handshake
2020-09-04 02:06:27.830898 [DEBUG] [WinTLSSession.cc:630] WinTLS: Writing handshake
2020-09-04 02:06:27.830898 [DEBUG] [WinTLSSession.cc:662] WinTLS: Reading handshake...
2020-09-04 02:06:27.940282 [DEBUG] [AbstractCommand.cc:184] CUID#7 - socket: read:1, write:0, hup:0, err:0
2020-09-04 02:06:27.940282 [DEBUG] [WinTLSSession.cc:585] WinTLS: Starting/Resuming TLS Connect
2020-09-04 02:06:27.940282 [DEBUG] [WinTLSSession.cc:662] WinTLS: Reading handshake...
2020-09-04 02:06:27.971535 [ERROR] [AbstractCommand.cc:351] CUID#7 - Download aborted. URI=https://repo.msys2.org/mingw/i686/mingw-w64-i686-gcc-fortran-10.2.0-1-any.pkg.tar.zst
Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://repo.msys2.org/mingw/i686/mingw-w64-i686-gcc-fortran-10.2.0-1-any.pkg.tar.zst
  -> [SocketCore.cc:1021] errorCode=1 SSL/TLS handshake failure: Error: The message received was unexpected or badly formatted.
(80090326)
2020-09-04 02:06:27.971535 [DEBUG] [AbstractCommand.cc:479] CUID#7 - Aborting download
2020-09-04 02:06:27.971535 [DEBUG] [AbstractCommand.cc:426] CUID#7 - Not trying next request. No reserved/pooled request is remaining and total length is still unknown.
2020-09-04 02:06:27.971535 [DEBUG] [RequestGroup.cc:982] GID#7bf17c94bca73c04 - Request queue check
2020-09-04 02:06:27.971535 [DEBUG] [WinTLSSession.cc:176] WinTLS: Cannot close connection
2020-09-04 02:06:27.971535 [NOTICE] [RequestGroupMan.cc:427] Download GID#7bf17c94bca73c04 not complete: C:/jack/vcpkg/downloads/temp/msys-mingw-w64-i686-gcc-fortran-10.2.0-1-any.pkg.tar.zst
2020-09-04 02:06:27.971535 [DEBUG] [RequestGroup.cc:1172] GID#7bf17c94bca73c04 - Creating DownloadResult.
2020-09-04 02:06:27.971535 [DEBUG] [RequestGroupMan.cc:482] 1 RequestGroup(s) deleted.
```

**Comment by BillyONeal** [comment]
Unfortunate :(

**Comment by Krzmbrzl** [comment]
Imo it would make sense to disable this functionality by default and only enable it, if the user specifies some sort of command line flag. Snd if (s)he does vcpkg could print a warning first that the user has to accept before continuing.

That way only user who are explicitly willing to take this risk will be affected.

If however you can fix this by using a download tool that can handle the TLS properly, that'd be the best solution.

**Comment by JackBoosY** [comment]
Close this PR, this issue will be solved in another way.

**Comment by JackBoosY** [comment]
This issue was fixed by the upstream, so we don't need this PR anymore.

**Pull request closed without merging**
