### PR TITLE
[ffmpeg] soxr dependency fix

### LINKED ISSUE #17270: [ffmpeg] fails to detect soxr
**Describe the bug**

There is a soxr feature for ffmpeg, but this one fails to detect soxr and don't use it.

**Environment**
- OS: Macos and Windows

**To Reproduce**
1. `./vcpkg install ffmpeg[core,ffmpeg,ffprobe,mp3lame,vorbis,opus,soxr]`
2. You can see that in tools/ there will be no `soxr.dll` and that ffmpeg.exe will not be compiled with soxr even through it was compiled with --enable-soxr

I suspect that the build script fails to find soxr.

### PR DESCRIPTION
**Pull request by mcmtroffaes**
**Describe the pull request**

- #### What does your PR fix? Fixes #17270 

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  Triplets unchanged, baseline updated.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes to the best of my knowledge.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes.

### CODE REVIEW

**Comment by mcmtroffaes** [comment]
Wrong base branch. 😄 Rebasing...

**Comment by mcmtroffaes** [comment]
Ok, should be good now.

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
LGTM, let's wait for the CI checks.

**Comment by abique** [comment]
@mcmtroffaes You are a rock star ;-)

**Comment by abique** [comment]
Why is the CI so slow?

**Comment by NancyLi1013** [comment]
Seems to solve the conflicts @mcmtroffaes.

**Comment by mcmtroffaes** [comment]
I'll wait for #17204 to get merged before solving the conflicts, if that's ok?

**Comment by NancyLi1013** [comment]
> I'll wait for #17204 to get merged before solving the conflicts, if that's ok?

Sure, No problem.

**Comment by mcmtroffaes** [comment]
Rebased.

**Comment by mcmtroffaes** [comment]
Rebased & conflicts resolved.

**Comment by mcmtroffaes** [comment]
Rebased & resolved conflicts.

**Pull request merged**
