### PR TITLE
[sdl2-mixer]Re-fix dynamic call.

### PR DESCRIPTION
**Pull request by JackBoosY**
Define `-D${PORT}="${PORT_LIBRARY}"` to use dynamic call in sdl2-mixer.

Related: #8208.

### CODE REVIEW

**Comment by JackBoosY** [comment]
@Vermeille @lethal-guitar @timautry @Vultraz
Sorry for late. Can you test it?

Thanks.

**Comment by Vultraz** [comment]
It works for vorbis 👍

**Comment by Vermeille** [comment]
Can't look into it rn, gimme a few days. Sorry for the latency

**Comment by cbezault** [comment]
It works for my couple of tests too. I'm going to merge this since the problem was pretty disruptive.

**Comment by timautry** [comment]
Works as advertised!!!!
Thanks for the quick turnaround, I appreciate it greatly. Have a wonderful week!!!.

**Pull request merged**
