### PR TITLE
[brunocodutra-metal] Add new port

### PR DESCRIPTION
**Pull request by myd7349**

### CODE REVIEW

**Comment by Rastaban** [comment]
I see a failure on linux but passing on everything else:

```
Starting package 1/1: metal:x64-linux
Building package metal[core]:x64-linux... 
Could not locate cached archive: /home/vcpkg/myagent/_work/1/s/archives/de/dee7384292912a171e3831e4e3df322fd88ba558.zip
-- Downloading https://github.com/brunocodutra/metal/archive/v2.0.1.tar.gz...
-- Extracting source /home/vcpkg/myagent/_work/1/s/downloads/brunocodutra-metal-v2.0.1.tar.gz
-- Using source at /home/vcpkg/myagent/_work/1/s/buildtrees/metal/src/v2.0.1-cee2e39175
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
CMake Error at scripts/cmake/vcpkg_fixup_cmake_targets.cmake:45 (message):
  
  '/home/vcpkg/myagent/_work/1/s/packages/metal_x64-linux/debug/lib/cmake/metal'
  does not exist.
Call Stack (most recent call first):
  ports/metal/portfile.cmake:20 (vcpkg_fixup_cmake_targets)
  scripts/ports.cmake:71 (include)


Error: Building package metal:x64-linux failed with: BUILD_FAILED
Elapsed time for package metal:x64-linux: 4.604 s
```
[install-x64-linux-dbg-out.log](https://github.com/Microsoft/vcpkg/files/3009577/install-x64-linux-dbg-out.log)

Maybe case sensitivity (metal/Metal) from `vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake/${PORT})`

**Comment by ras0219-msft** [comment]
To avoid confusion with the Apple software product Metal[1], I think this should probably be renamed to something like `brunocodutra-metal`.

[1] https://developer.apple.com/metal/

**Comment by myd7349** [comment]
@Rastaban Thanks! I did not test it on Linux yet.
@ras0219-msft Good idea!

**Comment by myd7349** [comment]
Test project: https://github.com/myd7349/Ongoing-Study/tree/master/cpp/CMake/vcpkg/metal_example

Test with:

- x86-windows
- x86-windows-static
- x64-windows
- x64-windows-static
- x64-linux

**Comment by Rastaban** [comment]
Passes on all triplets

**Pull request merged**
