### PR TITLE
[c-ares] Update to 1.28.0

### PR DESCRIPTION
**Pull request by waywardmonkeys**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [x] The "supports" clause reflects platforms that may be fixed by this new version.
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
Filed a bug upstream for the `trantor` issue and added a commit here to try working around it: https://github.com/an-tao/trantor/issues/329

**Review by JonLiu1993 — DISMISSED** [review]

**Comment by BillyONeal** [comment]
I pushed what I believe is a more correct fix for the deprecation issue. Specifically, disabling -Werror allows customers to continue to build Trantor while not erasing audit logs of the particular deprecations that are occurring.

I also removed the attempt to install find modules. Notably, FindBotan could never have been used because we pick openssl, and FindCAres could never have been used because we were already patching that `find_package` to say `CONFIG`. This made explicitly deleting the debug/share directory unnecessary.

Can you confirm that you are OK with these changes or describe ways in which you do not agree?

Thanks for the update!

**Comment by waywardmonkeys** [comment]
@BillyONeal  These seem fine to me!

**Comment by BillyONeal** [comment]
Awesome, thanks!

**Pull request merged**
