### PR TITLE
[curl] update to 7.62.0

### PR DESCRIPTION
**Pull request by pravic**

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for the PR!

I'm seeing regressions with this change for `cpr` on most self-hosted platforms (e.g. x64-windows) and for `curl` itself on cross-compilation platforms (e.g. x64-uwp).

Could you take a look at that?

**Comment by pravic** [comment]
Ok, I'll check.

**Comment by luzpaz** [comment]
FYI, 7.63.0 was released  
https://curl.haxx.se/changes.html#7_63_0

**Comment by luzpaz** [comment]
FYI, when merged this should close https://github.com/Microsoft/vcpkg/issues/4691

**Comment by Rastaban** [comment]
@pravic have you had a chance to look at the build failures?  If not, would you like some help with investigations?
Also 7.64.0 is our https://curl.haxx.se/changes.html#7_64_0

**Comment by pravic** [comment]
@Rastaban Nope, haven't checked that. It works for me (at least, compiles `curl`, even the recent version). Other than that, I don't use vcpkg anymore.

So I guess, this PR is better be closed then as non actual.

**Pull request closed without merging**
