### PR TITLE
[libdatachannel] chore(version): updated to 0.17.8

### PR DESCRIPTION
**Pull request by crisboarna**
**Describe the pull request**
Updating libdatachannel version.

- #### What does your PR fix?
It updates libdatachannel to latest version 0.17.7.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
No.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
Yes

### CODE REVIEW

**Comment by FrankXie05** [comment]
Please run command `./vcpkg x-add-version libdatachannel --overwrite-version`

**Comment by crisboarna** [comment]
Hi @FrankXie05 ,

I have tried running the requested command but I am getting the following output with no changes performed:

```
./vcpkg x-add-version libdatachannel --overwrite-version
version 0.17.1 is already in .../vcpkg/versions/l-/libdatachannel.json
version 0.17.1 is already in .../vcpkg/versions/baseline.json
No files were updated for libdatachannel
```

I am running this on the repo as it is in this branch.

**Comment by FrankXie05** [comment]
Do you mind if I change it?

**Comment by crisboarna** [comment]
Of course ! Please do.

**Comment by FrankXie05** [comment]
@crisboarna  I saw that the latest version 0.17.8 was released upstream, so I updated directly to version 0.17.8. :) 
https://github.com/paullouisageneau/libdatachannel/releases/tag/v0.17.8

**Comment by FrankXie05** [comment]
@crisboarna Regarding the update to port `libjuice` in the upstream issue I will submit a new PR to resolve
https://github.com/paullouisageneau/libdatachannel/issues/663#issuecomment-1173169039

**Review by FrankXie05 — APPROVED** [review]

**Comment by crisboarna** [comment]
Thank you very much for the assistance !

**Comment by crisboarna** [comment]
Hi @FrankXie05 , I tried adding `libjuice` update in #25552 but seems like I ran into the same issue with version command not doing anything ? What is the missing step ?

**Comment by BillyONeal** [comment]
> Hi @FrankXie05 , I tried adding `libjuice` update in #25552 but seems like I ran into the same issue with version command not doing anything ? What is the missing step ?

Most likely your changes weren't committed yet

**Comment by FrankXie05** [comment]
From the results it looks like applying the changes I requested, I'll keep an eye on it.

**Pull request merged**
