### PR TITLE
[opencv4] Fix build failure with some features

### PR DESCRIPTION
**Pull request by Matioupi**
fix for compile errors when building opencv with command line : .\vcpkg.exe install opencv[nonfree,ade,contrib,cuda,dnn,eigen,ffmpeg,gdcm,ipp,jasper,jpeg,openexr,opengl,openmp,ovis,png,qt,sfm,tbb,tiff,vtk,webp,halide]:x64-windows
error was located in modules/imgcodecs/src/grfmt_jpeg2000.cpp file and is fixed by a new patch
(official patch https://github.com/opencv/opencv/pull/17983/files)

**Describe the pull request**

- What does your PR fix? Fixes #

- Which triplets are supported/not supported? Have you updated the CI baseline?

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

### CODE REVIEW

**Comment by JackBoosY** [comment]
cc @cenit for review this PR.

**Review by JackBoosY — CHANGES_REQUESTED** [review]
Please bump the port version. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).

**Comment by Matioupi** [comment]
Source: opencv4
Version: 4.3.0
Port-Version: 1

**Comment by JackBoosY** [comment]
@Matioupi  Modify _VCPKG_ROOT/ports/opencv4/CONTROL_ line 3:
`Port-Version: 1` to `Port-Version: 2`.

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
I’m not sure if the changes are correct, I need more people to confirm.
The discussion about the changes is https://github.com/jasper-software/jasper/issues/223#issuecomment-666545623.

**Comment by Matioupi** [comment]
After reading the discussion your are pointing (and that I missed while fixing) the patch I proposed is basically the same as this commit :
https://github.com/opencv/opencv/pull/17983/commits
The committhat has been merged in opencv, but as far as I understand, it has only been applied to opencv 3.4 while I believe it should be applied also to newer versions.

**Pull request merged**
