### PR TITLE
[vcpkg] Use more forward declarations rather than definitions

### PR DESCRIPTION
**Pull request by cngzhnp**
I had done before in #12836 and these are new fixes for other files as well. I try to use forward declaration files as much as possible. Please give feedback about if new files need to be created.

### CODE REVIEW

**Review by strega-nil — APPROVED** [review]
Thanks for doing this @cngzhnp :)

**Comment by BillyONeal** [comment]
The CI failures look legitimate

**Comment by cngzhnp** [comment]
Yes, I did not realize that compilation of tests are failed. Is there any batch file to run it or just run cmake on vcpkg-test?

**Comment by BillyONeal** [comment]
> Yes, I did not realize that compilation of tests is failed. Is there any batch file to run it or just run cmake on vcpkg-test?

Right, you can see the exact commands we run in the ymls in `$/scripts/azure-pipelines`.

**Comment by BillyONeal** [comment]
It does indeed look like configuring CMake with tests on:

https://github.com/microsoft/vcpkg/blob/2a6442cb934de2f99c8ac5bbd8a9dcf5538aee98/toolsrc/CMakeLists.txt#L12

rather than trying to use the msbuild based bootstrap would show you these failures:

```
"C:\PROGRA~2\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.27.29110\bin\Hostx86\x86\cl.exe"  /nologo /TP -DVCPKG_USE_STD_FILESYSTEM=1 -IC:\a\1\s\toolsrc\include /DWIN32 /D_WINDOWS  /GR /EHsc /MDd /Zi /Ob0 /Od /RTC1   -FC -permissive- -utf-8 -W4 -analyze -WX -std:c++17 /showIncludes /FoCMakeFiles\vcpkg-test.dir\src\vcpkg-test\update.cpp.obj /FdCMakeFiles\vcpkg-test.dir\ /FS -c C:\a\1\s\toolsrc\src\vcpkg-test\update.cpp
C:\a\1\s\toolsrc\src\vcpkg-test\update.cpp(21): error C2079: 'status_db' uses undefined struct 'vcpkg::StatusParagraphs'
C:\a\1\s\toolsrc\src\vcpkg-test\update.cpp(21): error C2440: 'initializing': cannot convert from 'std::vector<std::unique_ptr<vcpkg::StatusParagraph,std::default_delete<vcpkg::StatusParagraph>>,std::allocator<std::unique_ptr<vcpkg::StatusParagraph,std::default_delete<vcpkg::StatusParagraph>>>>' to 'int'
C:\a\1\s\toolsrc\src\vcpkg-test\update.cpp(21): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
C:\a\1\s\toolsrc\src\vcpkg-test\update.cpp(26): error C2039: 'MapPortFileProvider': is not a member of 'vcpkg::PortFileProvider'
C:\a\1\s\toolsrc\include\vcpkg\update.h(15): note: see declaration of 'vcpkg::PortFileProvider'
C:\a\1\s\toolsrc\src\vcpkg-test\update.cpp(26): error C2065: 'MapPortFileProvider': undeclared identifier
C:\a\1\s\toolsrc\src\vcpkg-test\update.cpp(26): error C2146: syntax error: missing ';' before identifier 'provider'
C:\a\1\s\toolsrc\src\vcpkg-test\update.cpp(26): error C3861: 'provider': identifier not found
C:\a\1\s\toolsrc\src\vcpkg-test\update.cpp(28): error C2065: 'provider': undeclared identifier
C:\a\1\s\toolsrc\src\vcpkg-test\update.cpp(28): error C2440: '<function-style-cast>': cannot convert from 'bool (__cdecl *)(const vcpkg::Update::OutdatedPackage &,const vcpkg::Update::OutdatedPackage &)' to 'vcpkg::SortedVector<vcpkg::Update::OutdatedPackage>'
C:\a\1\s\toolsrc\src\vcpkg-test\update.cpp(29): note: No constructor could take the source type, or constructor overload resolution was ambiguous
C:\a\1\s\toolsrc\src\vcpkg-test\update.cpp(31): error C3536: 'pkgs': cannot be used before it is initialized
C:\a\1\s\toolsrc\src\vcpkg-test\update.cpp(32): error C2109: subscript requires array or pointer type
C:\a\1\s\toolsrc\src\vcpkg-test\update.cpp(33): error C2109: subscript requires array or pointer type
C:\a\1\s\toolsrc\src\vcpkg-test\update.cpp(45): error C2079: 'status_db' uses undefined struct 'vcpkg::StatusParagraphs'
C:\a\1\s\toolsrc\src\vcpkg-test\update.cpp(45): error C2440: 'initializing': cannot convert from 'std::vector<std::unique_ptr<vcpkg::StatusParagraph,std::default_delete<vcpkg::StatusParagraph>>,std::allocator<std::unique_ptr<vcpkg::StatusParagraph,std::default_delete<vcpkg::StatusParagraph>>>>' to 'int'
C:\a\1\s\toolsrc\src\vcpkg-test\update.cpp(45): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
C:\a\1\s\toolsrc\src\vcpkg-test\update.cpp(50): error C2039: 'MapPortFileProvider': is not a member of 'vcpkg::PortFileProvider'
C:\a\1\s\toolsrc\include\vcpkg\update.h(15): note: see declaration of 'vcpkg::PortFileProvider'
C:\a\1\s\toolsrc\src\vcpkg-test\update.cpp(50): error C2065: 'MapPortFileProvider': undeclared identifier
C:\a\1\s\toolsrc\src\vcpkg-test\update.cpp(50): error C2146: syntax error: missing ';' before identifier 'provider'
C:\a\1\s\toolsrc\src\vcpkg-test\update.cpp(50): error C3861: 'provider': identifier not found
C:\a\1\s\toolsrc\src\vcpkg-test\update.cpp(52): error C2065: 'provider': undeclared identifier
C:\a\1\s\toolsrc\src\vcpkg-test\update.cpp(52): error C2440: '<function-style-cast>': cannot convert from 'bool (__cdecl *)(const vcpkg::Update::OutdatedPackage &,const vcpkg::Update::OutdatedPackage &)' to 'vcpkg::SortedVector<vcpkg::Update::OutdatedPackage>'
C:\a\1\s\toolsrc\src\vcpkg-test\update.cpp(53): note: No constructor could take the source type, or constructor overload resolution was ambiguous
C:\a\1\s\toolsrc\src\vcpkg-test\update.cpp(55): error C3536: 'pkgs': cannot be used before it is initialized
C:\a\1\s\toolsrc\src\vcpkg-test\update.cpp(56): error C2109: subscript requires array or pointer type
C:\a\1\s\toolsrc\src\vcpkg-test\update.cpp(57): error C2109: subscript requires array or pointer type
C:\a\1\s\toolsrc\src\vcpkg-test\update.cpp(71): error C2079: 'status_db' uses undefined struct 'vcpkg::StatusParagraphs'
C:\a\1\s\toolsrc\src\vcpkg-test\update.cpp(71): error C2440: 'initializing': cannot convert from 'std::vector<std::unique_ptr<vcpkg::StatusParagraph,std::default_delete<vcpkg::StatusParagraph>>,std::allocator<std::unique_ptr<vcpkg::StatusParagraph,std::default_delete<vcpkg::StatusParagraph>>>>' to 'int'

```

Billy3

**Comment by cngzhnp** [comment]
@BillyONeal Thanks, at least I could generate VS19 solution from CMakeLists.txt and saw that _update.cpp_ was failed during compilation. It seems that it is fixed right now but let's see what CI brings to me :)

**Comment by BillyONeal** [comment]
It seems like for most of these we should extract `_fwd` headers rather than redeclaration?

**Comment by BillyONeal** [comment]
> It seems like for most of these we should extract `_fwd` headers rather than redeclaration?

To clarify, I'm saying we should apply Nicole's feedback in the previous PR ( https://github.com/microsoft/vcpkg/pull/12836#issuecomment-674980108 ) here too

**Comment by cngzhnp** [comment]
@BillyONeal It is OK from my perspective. I've mentioned in PR description if new files need to be created, I can do it in this PR. Otherwise, we can close this, create new one to refer this and make changes in there. What do you think?

**Comment by BillyONeal** [comment]
I would feel better if `_fwd`s are used rather than duplicating declarations.

**Comment by cngzhnp** [comment]
Could you please review my changes again @BillyONeal @strega-nil?

**Review by strega-nil — APPROVED** [review]

**Review by BillyONeal — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
