### PR TITLE
[v8] Update v8 to current stable version: 8.6.395.17

### LINKED ISSUE #13500: [v8] Could not find package configuration file
I have successfully installed `v8:x64-windows` and am trying to use the package in a CMake project in VS 2019. Running `vcpkg list` shows the package fine and there were no errors during the install:

```
icu:x64-windows                                    67.1-3           Mature and widely used Unicode and localization ...
v8:x64-windows                                     8.3.110.13       Google Chrome's JavaScript engine
zlib:x64-windows                                   1.2.11#9         A compression library
```

vcpkg is used as a Git submodule. `CMakeLists.txt` has the following:

```cmake
cmake_minimum_required (VERSION 3.8)

set(CMAKE_TOOLCHAIN_FILE ${CMAKE_CURRENT_SOURCE_DIR}/vcpkg/scripts/buildsystems/vcpkg.cmake CACHE STRING "Vcpkg toolchain file")

project ("HelloWorldV8_vcpkg")

find_package(v8 CONFIG REQUIRED)
```

CMake reports this error:

```
1> [CMake] CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:478 (_find_package):
1> [CMake]   Could not find a package configuration file provided by "v8" with any of
1> [CMake]   the following names:
1> [CMake] 
1> [CMake]     v8Config.cmake
1> [CMake]     v8-config.cmake
1> [CMake] 
1> [CMake]   Add the installation prefix of "v8" to CMAKE_PREFIX_PATH or set "v8_DIR" to
1> [CMake]   a directory containing one of the above files.  If "v8" provides a separate
1> [CMake]   development package or SDK, be sure it has been installed.
```

The vcpkg directory tree does not contain either `v8Config.cmake` or `v8-config.cmake`.

When installing the package, output ends with the "Total elapsed time" line, there is no "The package provides CMake targets..." like in other packages.

Contrary to what's mentioned in https://github.com/microsoft/vcpkg/pull/12687#issue-461463078 the package's `tools` folder does not exist.

/cc @Kwizatz

### PR DESCRIPTION
**Pull request by Kwizatz**
Updates v8 to current stable version: 8.6.395.17

- What does your PR fix?

Just a version upgrade

- Which triplets are supported/not supported? Have you updated the CI baseline?

Same as before.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

### CODE REVIEW

**Review by NancyLi1013 — APPROVED** [review]

**Comment by ras0219-msft** [comment]
Thank you very much for this PR!

This includes a huge patch to make mingw work -- has this work been submitted upstream? I am concerned about the future maintainability of this patchset over time if upstream isn't willing to support it.

**Comment by Kwizatz** [comment]
> This includes a huge patch to make mingw work -- has this work been submitted upstream? I am concerned about the future maintainability of this patchset over time if upstream isn't willing to support it.

Hi @ras0219-msft, as you did notice, the changes for mingw are not exactly trivial, most of the changes are on the "build" subdirectory/repo/module which is really part of the overall chromium project, so I am not sure what the sentiment towards that would be. I did uploaded a couple of changes for GN to be compiled with mingw and did not feel any resistance, so I say there's a good chance the changes will be welcome.

On the other hand, this effort has taken a lot of time on my side, and I would rather take a rest at least until the next stable release, as I am sure that uploading the changes will likely require more revisions and more changes.

In the meantime, I created a sandbox to make rebasing these patches easier for me on each new version [here](https://github.com/AeonGames/v8-builder)

**Comment by Kwizatz** [comment]
Reverted to Draft to address #13500

**Comment by Kwizatz** [comment]
Hi @ras0219-msft , this PR is ready for review again, I gave a response above, can you take a look?

Thanks!

**Review by mganss — APPROVED** [review]
I've verified this works on x64-windows and x64-linux. Please merge.

**Comment by Kwizatz** [comment]
@NancyLi1013 , @JackBoosY , @ras0219-msft , Just a quick poke to see if we can move this forward.

Thanks guys.

**Comment by JackBoosY** [comment]
I think it's okay.

**Comment by JackBoosY** [comment]
@BillyONeal What do you think about?

**Comment by BillyONeal** [comment]
I agree with @ras0219 that this patch is huge and really seems counter to our "do not implement features in patches" guidelines. Has upstream been willing to accept the patch?

**Comment by Kwizatz** [comment]
> I agree with @ras0219 that this patch is huge and really seems counter to our "do not implement features in patches" guidelines. Has upstream been willing to accept the patch?

Hi Bill, the patches seem huge because they include changes to build v8 on a MSYS2 MingW environment, those changes can be removed, I rather not remove them because that would involve a manual step further in my version upgrade process just for vcpkg, but it can be done.

No "features" are being implemented here, at all.

Please refer to my previous post from Sep 9, the situation has not changed, except that now latest stable is version 8.6.

**Comment by BillyONeal** [comment]
>the patches do seem huge because they include changes to build v8 on a MSYS2 MingW environment, those changes can be removed, I rather not remove them because that would involve a manual step further in my version upgrade process just for vcpkg, but it can be done.

Have you tried to submit those changes upstream? If v8 folks are unwilling to support MinGW and we are patching that in after the fact, that makes the vcpkg team responsible for the "supports MinGW" feature, and we are in the deployment business, not the add-features-we-like business.

For example, if we go to update the v8 version ourselves, it's likely that the patch would no longer apply cleanly and we'd be forced to drop this MinGW support you need.

>No "features" are being implemented here, at all.

I would argue "MinGW support" is a feature.

>Please refer to my previous post from Sep 9, the situation has not changed, except that now latest stable is version 8.6.

Right, our concern with being on the hook for the MinGW patch is unchanged; I don't think we want to merge that. Of course, if upstream takes such a change and thus it becomes a temporary patch that goes away next time we update v8, that would be fine.

Thanks for your contribution and sorry it hasn't been as smooth as it should be!

**Comment by Kwizatz** [comment]
> Have you tried to submit those changes upstream? If v8 folks are unwilling to support MinGW and we are patching that in after the fact, that makes the vcpkg team responsible for the "supports MinGW" feature, and we are in the deployment business, not the add-features-we-like business.

I have queried the dev mailing list in this regard, they seem welcoming the changes though no support (IE CI tests, not breaking the changes with future changes) on their part is being offered, pretty much what I expected and accept.

> For example, if we go to update the v8 version ourselves, it's likely that the patch would no longer apply cleanly and we'd be forced to drop this MinGW support you need.

That would be 100% fine with me, I really don't need that support here, I **though**  maybe the mingw vcpkg triplets could use it, but I don't use them myself. It all came down to what's easier for me, and keeping a single branch up to date is easier for me.

> I would argue "MinGW support" is a feature.

So, it is a feature even though the binary result is exactly the same with or without the changes and no single line of a mingw conditional in gn ever runs. ok.  

> Right, our concern with being on the hook for the MinGW patch is unchanged; I don't think we want to merge that. Of course, if upstream takes such a change and thus it becomes a temporary patch that goes away next time we update v8, that would be fine.

Don't worry, you won't have to, it would have been nice **not** to have left me hanging for two months and to have talked this much earlier than this, but at least we managed to iron out a bug.

> Thanks for your contribution and sorry it hasn't been as smooth as it should be!

Sure, no problem, I am not bitter, but I do hope future interactions go smoother/faster.

**Comment by JackBoosY** [comment]
@BillyONeal @strega-nil Is there anything else to discuss here?

**Comment by strega-nil** [comment]
@JackBoosY not really. We don't want to support the mingw feature; if @Kwizatz wants to upstream these changes, we'd be happy to take those changes at that point.

**Comment by Kwizatz** [comment]
@strega-nil, @JackBoosY Check the last commit, the mingw "feature" was removed.

**Comment by strega-nil** [comment]
@Kwizatz thank you very much; I'm so sorry for the experience you've had here. We're currently working on our process around this, because we know that it sucks for too many people.

We appreciate your contribution, and if you need anything else, don't hesitate to open an issue or a PR.

**Pull request merged**
