### PR TITLE
[mathgl] Update to v2.5

### PR DESCRIPTION
**Pull request by wtywtykk**
- #### What does your PR fix?  
This pull request updates mathgl to v2.5

1. new patches:
    fix_arma_sprintf.patch: fix sprintf name conflict with armadillo
    fix_attribute.patch: MGL_FUNC_INIT and MGL_FUNC_FINI not defined issue.
    fix_default_graph_init.patch: mglDefaultGr is initialized in DllMain, so it causes the similar problem as https://github.com/microsoft/vcpkg/pull/21411 (this one is fixed in v2.5, but v2.5 have new problems) . Fixed by disabling  mglDefaultGr initialize in DllMain, it will be initialized  on first use. 
    fix_mglDataList.patch: mglDataList is imported in a wrong way, msvc can't find it in widgets dlls.
2. deleted:
    type_fix.patch: upstream has fixed that.
    fix_cmakelists_and_cpp.patch: upstream fixed the min/max redefinition issue and mgl_ask_func/mgl_progress_func definition issue. Removed those from the patch. cmake related patches are kept.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all , Yes
(linux x64 failed but it seems to be a environment issue. On rockylinux8.5, it says opengl is missing. After manually installed opengl, it works. The repo without my commits also can't pass. Did the CI environment changed?)

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
 Yes

### CODE REVIEW

**Comment by LilyWangLL** [comment]
Thanks for your PR. This error need change portfile.cmake Line 46 `vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/mathgl)` to `vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/mathgl2)`, this will fix build failed on Linux.

**Comment by wtywtykk** [comment]
> Thanks for your PR. This error need change portfile.cmake Line 46 `vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/mathgl)` to `vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/mathgl2)`, this will fix build failed on Linux. This is error message on Linux of pipelines:
> 
> ```
> CMake Error at /mnt/vcpkg-ci/installed/x64-linux/share/vcpkg-cmake-config/vcpkg_cmake_config_fixup.cmake:84 (message):
>   '/mnt/vcpkg-ci/packages/mathgl_x64-linux/debug/lib/cmake/mathgl' does not
>   exist.
> Call Stack (most recent call first):
>   ports/mathgl/portfile.cmake:46 (vcpkg_cmake_config_fixup)
>   scripts/ports.cmake:142 (include)
> ```

Thanks for pointing this out! I've pushed a new version.

**Review by LilyWangLL — APPROVED** [review]

**Comment by BillyONeal** [comment]
These are fairly substantial and tricky patches that probably should be looked at by upstream first given that they seem somewhat responsive (because they have fixed bugs from the previous patches). Can you show that they have been contacted for each of these patches and have had an opportunity to comment?

**Comment by LilyWangLL** [comment]
Ping @wtywtykk for response.

**Comment by wtywtykk** [comment]
> Ping @wtywtykk for response.

The author agreed to merge my code, but didn't say if I should commit here. 
(He didn't issue a release, so we can't use his updated version)

Dialog on google groups: https://groups.google.com/g/mathgl/c/ixs2QegDqA8

**Comment by BillyONeal** [comment]
> > Ping @wtywtykk for response.
> 
> The author agreed to merge my code, but didn't say if I should commit here. (He didn't issue a release, so we can't use his updated version)
> 
> Dialog on google groups: https://groups.google.com/g/mathgl/c/ixs2QegDqA8

Thanks for the Google Groups link; the upstream authors don't say that the patches are crazy and are just asking clarifying questions on how to ingest them themselves, so I think we can take that. Thanks for following up!

**Pull request merged**
