### PR TITLE
[spdlog] Update to 1.11.0

### LINKED ISSUE #27799: [spdlog] update to 1.11.0
Library name: spdlog

New version number: 1.11.0

[spdlog have been updated to 1.11.0](https://github.com/gabime/spdlog/releases/tag/v1.11.0)

### PR DESCRIPTION
**Pull request by KiruyaMomochi**
- [spdlog] Update to 1.11.0
- [spdlog] Add 1.11.0 to versions file

**Describe the pull request**

- #### What does your PR fix?
  None

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  all, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by FrankXie05** [comment]
@KiruyaMomochi We can wait for PR https://github.com/microsoft/vcpkg/pull/27740.

**Comment by kromain** [comment]
for consideration: backporting https://github.com/gabime/spdlog/commit/c5a09ebc49c05687c0f46c1c4b2a3ae57e5bbfad to fix the build with the `benchmark` option

**Comment by FrankXie05** [comment]
@KiruyaMomochi Now we can continue this PR, please resolve the conflict. And consider adding options `SPDLOG_BUILD_BENCH` to solve the construction problems. https://github.com/gabime/spdlog/pull/2545

**Review by FrankXie05 — DISMISSED** [review]

**Review by BillyONeal — APPROVED** [review]
Thank you!

**Pull request merged**
