### PR TITLE
[vcpkg baseline] Add discordcoreapi omplapp to ci.baseline.txt

### PR DESCRIPTION
**Pull request by WangWeiLin-MV**
Relieve [Pipelines - Run 20240725.1 (azure.com)](https://dev.azure.com/vcpkg/public/_build/results?buildId=105330&view=logs&j=f79cfdd7-47a8-597f-8f57-dc3e21a8f2ad&t=4f03addf-ef5a-50a2-71be-19894d9df4e3) "Nothing to show. Final logs are missing. This can happen when the job is cancelled or times out.", that CI test hanging on `x64-linux`.

So mark port `discordcoreapi` as `skip` for `x64-linux`.

---

Port `discordcoreapi` failed with dependency https://github.com/microsoft/vcpkg/pull/39693#issuecomment-2262575056

```plain
discordcoreapi:x64-uwp=fail
discordcoreapi:x64-windows=fail
discordcoreapi:x64-windows-static=fail
discordcoreapi:x64-windows-static-md=fail
```

---

Port `omplapp` failed with FILE_CONFLICTS https://github.com/microsoft/vcpkg/pull/40151

```plain
omplapp:arm64-osx=skip
omplapp:x64-osx=skip
omplapp:x64-linux=skip
```

### CODE REVIEW

**Comment by WangWeiLin-MV** [comment]
### More Information

Based on local testing for building `discordcoreapi` on linux, memory seems to be exhausted very quickly. Afterwards the build goes single-threaded and hangs for a long time.

Based on the running CI log, the build-time log stay `-- Building x64-linux-dbg` same as local.

Other triplets build normally. (the build fails in about 3 minutes)

So, mark it from 'fail' to `skip` for `x64-linux`.

### Regression

Before it marks as 'fail' on #35358, but it built normally. (the build fails in about 3 minutes)

Regression from #39693, the updating of its dependency `jsonifier` did not trigger the build of `discordcoreapi` [Pipelines - Run 20240723.12 (azure.com)](https://dev.azure.com/vcpkg/public/_build/results?buildId=105231&view=logs&j=f79cfdd7-47a8-597f-8f57-dc3e21a8f2ad&t=4f03addf-ef5a-50a2-71be-19894d9df4e3&l=7415). Further investigation is required.

**Comment by WangWeiLin-MV** [comment]
Depends on #40231 or #40249

**Comment by talregev** [comment]
@WangWeiLin-MV 
https://github.com/microsoft/vcpkg/pull/40249 Already merged.

**Comment by dg0yt** [comment]
Please speed this up and mark this ready-for-review.

**Comment by WangWeiLin-MV** [comment]
> Please speed this up and mark this ready-for-review.

According to the CI log, its progress has reached 4/5

**Comment by dg0yt** [comment]
> > Please speed this up and mark this ready-for-review.
> 
> ~According to the CI log, its progress has reached 4/5~
> 
> Updates: Depends on #40327

This PR can be reviewed and merged despite the build errors. It might even be necessary.

**Review by JonLiu1993 — DISMISSED** [review]

**Comment by WangWeiLin-MV** [comment]
Add item
```plain
omplapp:x64-linux=skip
```

**Comment by WangWeiLin-MV** [comment]
https://github.com/microsoft/vcpkg/pull/40229#issuecomment-2264887786
> ### Regression
> Before it marks as 'fail' on #35358, but it built normally. (the build fails in about 3 minutes)
> 
> Regression from #39693, the updating of its dependency `jsonifier` did not trigger the build of `discordcoreapi` [Pipelines - Run 20240723.12 (azure.com)](https://dev.azure.com/vcpkg/public/_build/results?buildId=105231&view=logs&j=f79cfdd7-47a8-597f-8f57-dc3e21a8f2ad&t=4f03addf-ef5a-50a2-71be-19894d9df4e3&l=7415). Further investigation is required.


Updates:

PR checks miss the hang-error due to various reasons:

* Test script skipping failures when `$BuildReason -eq 'PullRequest'`, see [scripts/azure-pipelines/test-modified-ports.ps1#L94-L96](https://github.com/microsoft/vcpkg/blob/2024.07.12/scripts/azure-pipelines/test-modified-ports.ps1#L94-L96)
* `discordcoreapi` marked as `fail` for `x64-linux` and `x64-osx` [scripts/ci.baseline.txt#L303-L304](https://github.com/microsoft/vcpkg/blob/2024.07.12/scripts/ci.baseline.txt#L303-L304)
* Other `Linux` triplets (like `x64-android`) are skipped because its dependencies are not supported on these platforms
* The hang-error only occurs under `Linux`

**Review by data-queue — APPROVED** [review]

**Pull request merged**
