### PR TITLE
[libiconv] Fix android

### LINKED ISSUE #27304: libiconv:arm64-android failed
**Host Environment**

- OS: macOS 12.6
- Compiler:~/Library/Android/sdk/ndk/23.2.8568313/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++

**To Reproduce**

vcpkg install libiconv:arm64-android --debug --binarysource=clear

**Failure logs**

CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:131 (message):
    Command failed: /usr/bin/make V=1 -j 13 -f Makefile all
    Working Directory: /Users/dusmit/Developer/vcpkg/buildtrees/libiconv/arm64-android-dbg/
    See logs for more information:
      /Users/dusmit/Developer/vcpkg/buildtrees/libiconv/build-arm64-android-dbg-out.log
      /Users/dusmit/Developer/vcpkg/buildtrees/libiconv/build-arm64-android-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:149 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:2 (vcpkg_build_make)
  ports/libiconv/portfile.cmake:39 (vcpkg_install_make)
  scripts/ports.cmake:147 (include)

[DEBUG] 34388: cmd_execute_and_stream_data() returned 1 after 53709918 us
error: building libiconv:arm64-android failed with: BUILD_FAILED

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

### LINKED ISSUE #29719: [libiconv] build failure
**Host Environment**

- OS: Linux Debian Sid WSL
- Compiler: android Ndk 25.2.9519653 clang

**To Reproduce**

`./vcpkg install libiconv --triplet=x64-android`

**Failure logs**

[build-x64-android-dbg-err.log](https://github.com/microsoft/vcpkg/files/10768683/build-x64-android-dbg-err.log)
[build-x64-android-dbg-out.log](https://github.com/microsoft/vcpkg/files/10768684/build-x64-android-dbg-out.log)

### PR DESCRIPTION
**Pull request by dg0yt**
Fixes #29719. Fixes #27304.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Review by JonLiu1993 — APPROVED** [review]

**Comment by dg0yt** [comment]
@JonLiu1993 The problems were reproducible, the PR does fix it, and the same fix is now already for libtasn1. No need to hold this back.

**Comment by hushanjushi** [comment]
> @hushanjushi, could you please test it on your environment and see if it solves your problem?

I tested and found a puzzling error:
```shell
configure: error: in `/home/test/tools/test/vcpkg/buildtrees/libiconv/x64-android-dbg':
configure: error: C compiler cannot create executables
```
I clone [dg0yt:libiconv](https://github.com/dg0yt/vcpkg/tree/libiconv) and input:
```
./vcpkg install libiconv --triplet=x64-android
```
I have set `Android-ndk` and can compile other packages.. Confused...

**Comment by hushanjushi** [comment]
> @JonLiu1993 The problems were reproducible, the PR does fix it, and the same fix is now already merged for libtasn1. No need to hold this back.

I met some problems when tests this pr...

**Comment by dg0yt** [comment]
@hushanjushi Share your config.log from buildtrees/libiconv/x64-android-dbg.

**Comment by hushanjushi** [comment]
> @hushanjushi Share your config.log from buildtrees/libiconv/x64-android-dbg.

[config.log](https://github.com/microsoft/vcpkg/files/10938952/config.log)

**Comment by dg0yt** [comment]
~~~
configure:4218: checking whether the C compiler works
configure:4240: gcc -g -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wformat -Werror=format-security -fPIC -fno-limit-debug-info -DANDROID -D_FORTIFY_SOURCE=2 -avoid-version   conftest.c -latomic -lm >&5
gcc: error: unrecognized command-line option '-fno-limit-debug-info'
gcc: error: unrecognized command-line option '-avoid-version'; did you mean '-fno-version'?
~~~
Not a NDK compiler.

~~~
ac_cv_env_CC_set=
ac_cv_env_CC_value=
~~~
vcpkg scripts set environment variable `CC` to the compiler which is detected by CMake, but here it is empty. Did you modify your environment?

This PR changes source files, but not the build system. Your current problem is unrelated to this PR.

**Comment by hushanjushi** [comment]
> ```
> configure:4218: checking whether the C compiler works
> configure:4240: gcc -g -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wformat -Werror=format-security -fPIC -fno-limit-debug-info -DANDROID -D_FORTIFY_SOURCE=2 -avoid-version   conftest.c -latomic -lm >&5
> gcc: error: unrecognized command-line option '-fno-limit-debug-info'
> gcc: error: unrecognized command-line option '-avoid-version'; did you mean '-fno-version'?
> ```
> 
> Not a NDK compiler.
> 
> ```
> ac_cv_env_CC_set=
> ac_cv_env_CC_value=
> ```
> 
> vcpkg scripts set environment variable `CC` to the compiler which is detected by CMake, but here it is empty. Did you modify your environment?
> 
> This PR changes source files, but not the build system. Your current problem is unrelated to this PR.

I don't change the environment. `./vcpkg install gsl --triplet=x64-android` can work in pr version vcpkg...

**Comment by dg0yt** [comment]
All my recent testing is with setting `ANDROID_NDK_HOME` only. 
`gsl` uses CMake only.
`libiconv` and `libtasn1` use autotools build system. vcpkg needs to pass in certain setting via environment variables. I determines the actual values by configuring a small CMake project first. This is where the cmake log files come from. Here, we should get the same variables as with `gsl`. Files of interest:
cmake-vars-arm-android-dbg.cmake.log : selected preprocessed variables
get-cmake-vars-arm-android-dbg-CMakeCache.txt.log : cached variables from CMake configuration

**Comment by hushanjushi** [comment]
> ```
> configure:4218: checking whether the C compiler works
> configure:4240: gcc -g -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wformat -Werror=format-security -fPIC -fno-limit-debug-info -DANDROID -D_FORTIFY_SOURCE=2 -avoid-version   conftest.c -latomic -lm >&5
> gcc: error: unrecognized command-line option '-fno-limit-debug-info'
> gcc: error: unrecognized command-line option '-avoid-version'; did you mean '-fno-version'?
> ```
> 
> Not a NDK compiler.
> 
> ```
> ac_cv_env_CC_set=
> ac_cv_env_CC_value=
> ```
> 
> vcpkg scripts set environment variable `CC` to the compiler which is detected by CMake, but here it is empty. Did you modify your environment?
> 
> This PR changes source files, but not the build system. Your current problem is unrelated to this PR.

Sorry, I found I have not updated...

**Comment by hushanjushi** [comment]
> All my recent testing is with setting `ANDROID_NDK_HOME` only. `gsl` uses CMake only. `libiconv` and `libtasn1` use autotools build system. vcpkg needs to pass in certain setting via environment variables. It determines the actual values by configuring a small CMake project first. This is where the cmake log files come from. Here, we should get the same variables as with `gsl`. Files of interest: `cmake-vars-arm-android-dbg.cmake.log` : selected preprocessed variables `get-cmake-vars-arm-android-dbg-CMakeCache.txt.log` : cached variables from CMake configuration

I try again, but very confusing, fail, too.

**Comment by hushanjushi** [comment]
> cmake-vars-arm-android-dbg.cmake.log



> All my recent testing is with setting `ANDROID_NDK_HOME` only. `gsl` uses CMake only. `libiconv` and `libtasn1` use autotools build system. vcpkg needs to pass in certain setting via environment variables. It determines the actual values by configuring a small CMake project first. This is where the cmake log files come from. Here, we should get the same variables as with `gsl`. Files of interest: `cmake-vars-arm-android-dbg.cmake.log` : selected preprocessed variables `get-cmake-vars-arm-android-dbg-CMakeCache.txt.log` : cached variables from CMake configuration

[cmake-vars-x64-android-dbg.cmake.log](https://github.com/microsoft/vcpkg/files/10939305/cmake-vars-x64-android-dbg.cmake.log)

no get-cmake-vars-x64-android-dbg-CMakeCache.txt.log

**Comment by dg0yt** [comment]
> It seems like found ndk but no use?

Yes, but this problem is not related to this PR.

As expected, CMake detects the right compiler:
~~~
set(VCPKG_DETECTED_CMAKE_C_COMPILER "/home/test/tools/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin/clang")
~~~

Check the output of `env`. I guess you set `CC` to an empty value (maybe in an attempt to unset it). It might be ignored by CMake, but unfortunately it isn't by vcpkg scripts.

**Comment by hushanjushi** [comment]
> 



> > It seems like found ndk but no use?
> 
> Yes, but this problem is not related to this PR.
> 
> As expected, CMake detects the right compiler:
> 
> ```
> set(VCPKG_DETECTED_CMAKE_C_COMPILER "/home/test/tools/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin/clang")
> ```
> 
> Check the output of `env`. I guess you set `CC` to an empty value (maybe in an attempt to unset it). It might be ignored by CMake, but unfortunately it isn't by vcpkg scripts.

I understand. I try again...

**Comment by hushanjushi** [comment]
> > It seems like found ndk but no use?
> 
> Yes, but this problem is not related to this PR.
> 
> As expected, CMake detects the right compiler:
> 
> ```
> set(VCPKG_DETECTED_CMAKE_C_COMPILER "/home/test/tools/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin/clang")
> ```
> 
> Check the output of `env`. I guess you set `CC` to an empty value (maybe in an attempt to unset it). It might be ignored by CMake, but unfortunately it isn't by vcpkg scripts.

I have set:
```
export CC=/usr/local/bin/gcc
export CXX=/usr/local/bin/g++
```
and link `/usr/bin/cc` and `/usr/bin/c++`

**Comment by hushanjushi** [comment]
> > It seems like found ndk but no use?
> 
> Yes, but this problem is not related to this PR.
> 
> As expected, CMake detects the right compiler:
> 
> ```
> set(VCPKG_DETECTED_CMAKE_C_COMPILER "/home/test/tools/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin/clang")
> ```
> 
> Check the output of `env`. I guess you set `CC` to an empty value (maybe in an attempt to unset it). It might be ignored by CMake, but unfortunately it isn't by vcpkg scripts.

Can vcpkg auto set it? Or we should set CC manually for autotools in recent days?

**Comment by dg0yt** [comment]
For now, you shall not set `CC` unless you want to override vcpkg autotools stuff (and deal with the effects).
Either unset it, or try what vcpkg would use, `home/test/tools/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin/clang`.

(Whether vcpkg should ignore the user's `CC` is off-topic in this PR.)

**Comment by hushanjushi** [comment]
> For now, you shall not set `CC` unless you want to override vcpkg autotools stuff (and deal with the effects). Either unset it, or try what vcpkg would use, `home/test/tools/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin/clang`.
> 
> (Whether vcpkg should ignore the user's `CC` is off-topic in this PR.)



> For now, you shall not set `CC` unless you want to override vcpkg autotools stuff (and deal with the effects). Either unset it, or try what vcpkg would use, `home/test/tools/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin/clang`.
> 
> (Whether vcpkg should ignore the user's `CC` is off-topic in this PR.)

But I found CC unset will give me the not-found error... (Not ignore but i think if empty will use default cc in vcpkg? Not CC can't find is really strange)

**Comment by dg0yt** [comment]
You must sanitize your environment. I would prefer to no longer deal with these unrelated problems here.

**Comment by hushanjushi** [comment]
> 



> You must sanitize your environment. I would prefer to no longer deal with these unrelated problems here.

Ok. I fully understand it...

**Comment by hushanjushi** [comment]
> You must sanitize your environment. I would prefer to no longer deal with these unrelated problems here.

In a new VM, it works.

**Comment by hushanjushi** [comment]
> > You must sanitize your environment. I would prefer to no longer deal with these unrelated problems here.
> 

In a new VM, it works. Thank you.

**Pull request merged**
