### PR TITLE
Add nvidia-texture-tools.

### PR DESCRIPTION
**Pull request by vlj**

### CODE REVIEW

**Comment by ras0219-msft** [comment]
I'm taking a look at this, and I currently fail due to not having the desired .NETframework installed.

We probably need to either
- If it's small, we can download it on-demand during the build
- If it's large or requires system-wide install, we should check up-front for it and give a nice error message AND clear instructions on how to install it (ideally a direct link to an MSI).

```
       "D:\src\vcpkg\buildtrees\nvidia-texture-tools\src\nvidia-texture-tools-2.1.0\project\vc12\nvtt.sln" (default target) (1) ->
       "D:\src\vcpkg\buildtrees\nvidia-texture-tools\src\nvidia-texture-tools-2.1.0\project\vc12\Nvidia.TextureTools\Nvidia.TextureTools.csproj" (default target) (26) ->
       (GetReferenceAssemblyPaths target) -> 
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(1111,5): error MSB3645: .NET Framework v3.5 Service Pack 1 was not found. In order to target ".NETFramework,Version=v2.0", .NET Framework v3.5 Service Pack 1 or later must be installed. [D:\src\vcpkg\buildtrees\nvidia-texture-tools\src\nvidia-texture-tools-2.1.0\project\vc12\Nvidia.TextureTools\Nvidia.TextureTools.csproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(1111,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v2.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [D:\src\vcpkg\buildtrees\nvidia-texture-tools\src\nvidia-texture-tools-2.1.0\project\vc12\Nvidia.TextureTools\Nvidia.TextureTools.csproj]
```

**Comment by vlj** [comment]
What is your software env ? I though .Net Framework were present by default on Windows and/or part of minimal visual studio install.
Unfortunatly I think that it requires a system wide install (.net needs to fill the global assembly cache)

**Comment by ras0219-msft** [comment]
Ok, finally managed to build this.

It looks like the .NET framework is only needed to build the C# bindings -- since we currently have no story around C# exposure I think we should disable building the `Nvidia.TextureTools` project. This should remove all dependencies on .NET.

Now, after building, I noticed that the package is essentially empty:
```
PS D:\src\vcpkg> tree /f .\packages\nvidia-texture-tools_x86-windows
Folder PATH listing for volume DATADRIVE1
Volume serial number is 5C4F-33A2
D:\SRC\VCPKG\PACKAGES\NVIDIA-TEXTURE-TOOLS_X86-WINDOWS
│   BUILD_INFO
│   CONTROL
│
├───include
│   └───nvtt
│           nvtt.h
│           nvtt_wrapper.h
│
└───share
    └───nvidia-texture-tools
            copyright

PS D:\src\vcpkg>
```
Did you intend to install the contents of `${SOURCE_PATH}/project/vc12/Release.${MSBUILD_PLATFORM}/bin`? That folder contains several executables and the `nvtt.dll` (which I presume is the purpose of this port).

I think it would be best to have a whitelist of the installed executables, because we probably don't want to install `nvtt-testsuite.exe`.

**Comment by ras0219-msft** [comment]
Closing this due to inactivity. If you or someone else would like to pick it back up, please feel free to open a new one!

**Pull request closed without merging**
