### PR TITLE
Fix libpng build with Emscripten

### PR DESCRIPTION
**Pull request by tronical**
Add a patch to avoid libm linkage, which is not needed.

The same fix was submitted upstream at https://github.com/glennrp/libpng/pull/320 . Meanwhile I think it makes sense to include it here.

### CODE REVIEW

**Comment by tronical** [comment]
I think after commit 8887f6c09c27dd5f6dfeecc4c766ec9f67d95f7a in master this change is not needed anymore. The "else branch" takes care of what this issue tried to fix :)

**Comment by ras0219-msft** [comment]
Thanks for the PR; I'll close this given your comment.

Please do open a new PR if this isn't fixed!

**Pull request closed without merging**
