### PR TITLE
Add support custom triplets in OpenNI2 port

### PR DESCRIPTION
**Pull request by UnaNancyOwen**
Add support custom triplets in OpenNI2 port. (issues https://github.com/Microsoft/vcpkg/issues/1927)

### CODE REVIEW

**Comment by jasjuang** [comment]
Please merge this so I can build PCL without having to manually apply this PR for all the computers!

**Comment by ras0219-msft** [comment]
Thanks for working on this, both of you!

I noticed some issues with the original approach; namely that once you've patched the sources for a given triplet, you'd never be able to patch them again to another one.

Additionally, pulling from the `packages\` directory is _strongly_ discouraged (we'd like to compress those files one day!). Instead, we can simply reference the installed directory.

In my tests this change worked correctly up until it needed `NuiApi.h` (I don't have the Kinect SDK installed). I'm pretty confident that this should work fine for you guys so I'll merge it now. Let me know if I should revert it or if we need a follow-up PR with a few touch-ups!

**Comment by jasjuang** [comment]
@ras0219-msft With your new commit I am not able to compile openni2. The compilation error is `NuiApi.h` missing. Maybe you missed something?

**Comment by ras0219-msft** [comment]
I accidentally made a mistake and missed a file; could you pull, **delete the buildtrees\openni2\ folder** and try again?

**Comment by jasjuang** [comment]
@ras0219-msft It works now, thanks!

**Pull request merged**
