### PR TITLE
[cpp-taskflow] Update to 2.5.0

### PR DESCRIPTION
**Pull request by mfornace**
Updates:

- Update to 2.5.0 tag
- Change associated hash

Note: the 2.2.0->2.5.0 update includes fixed behavior inside cpp-taskflow to allow for AppleClang

### CODE REVIEW

**Comment by JackBoosY** [comment]
```
D:\buildtrees\cpp-taskflow\src\v2.5.0-c89047d1ae.clean\unittests\basics.cpp : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj
ninja: build stopped: subcommand failed.
```

**Comment by JackBoosY** [comment]
Seems doesn't work. Same error.

**Comment by mfornace** [comment]
Thanks. Can you tell me how to specify that vcpkg should only build some targets? This library is a header-only library; building is failing on some of the example files (which do not have a CMake -D option to exclude).

If you think the example files must compile for the library to be considered successfully built, then I would think the baseline should be changed. I suspect these files would never have compiled successfully with the default options.

**Comment by JackBoosY** [comment]
@mfornace It is indeed a header-only library, and we are not building it as a library now. `vcpkg_*_cmake` only installed its headers to _installed/TRIPLET_ now.
The question is, does the updated cmakelists.txt modify this behavior?

**Comment by mfornace** [comment]
@JackBoosY yes the new version has a different option specification pattern, so that example targets like the following are included during configure time (not dependent on any conditions that I can see). 

```
message(STATUS "Building examples ...")
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${TF_EXAMPLE_DIR})

add_executable(simple ${TF_EXAMPLE_DIR}/simple.cpp)
```

Is there a way to only build the main `Taskflow::Taskflow` target, or is it better to just add a new target myself for the include path? (Or, should I raise an issue with the library repo?)

**Comment by JackBoosY** [comment]
Most targets are configuration options or test items, and itself is not involved in the build process.

**Comment by JackBoosY** [comment]
Nonono, don't just remove them, you need to include them in `if (BUILD_TEST)` and `endif()`, and seems you removed my patch to add compile option  `/bigobj`.

**Comment by mfornace** [comment]
OK thanks, I added the content back in as you said. I put the compile option in the interface library since there are 28 executables that I think should encounter the same issue, not just the "basics" one.

How do you actually see the created error from the CI pipeline? I haven't been able to find the correct artifact to download.

**Review by JackBoosY — APPROVED** [review]

**Comment by mfornace** [comment]
@JackBoosY thanks for your help!

**Comment by BillyONeal** [comment]
Thanks!

**Pull request merged**
