### PR TITLE
[boost-modular-builder] let fallback to default tool path

### PR DESCRIPTION
**Pull request by xandox**
Let fallback to default boost build path.

This fix works for me now but I am not sure it is correct way to fix a problem.
I use vcpkg in manifest mode and try cross compile my project for android. I redefine `VCPKG_TARGET_ARCHITECTURE` and `VCPKG_CMAKE_SYSTEM_NAME` for `boost-build` port in overplayed triplet file, but any checks in this script assumes that you use vcpkg not in manifest mode. Maybe it's better to check here if we in manifest mode but there are not any cmake variable which can helps to detect this mode (VCPKG_MANIFEST_MODE not defined, VCPKG_MANIFEST_INSTALL is OFF).

- What does your PR fix? Fixes #

- Which triplets are supported/not supported? Have you updated the CI baseline?

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

### CODE REVIEW

**Comment by PhoebeHui** [comment]
@xandox, could you open an issue for this?

**Comment by xandox** [comment]
@PhoebeHui sure but for what concrete?

**Comment by PhoebeHui** [comment]
@xandox, I'm also not sure if it's a correct fix, since it affects a community triplet, this is not usual scenario we're working on, but we accept the PRs for fixing the issue, I suggest to open an issue with details so others may replicate this problem.

BTW, what does the issue have to do with manifest? this is not be a problem if not in manifest mode?

**Comment by xandox** [comment]
Tried to explain everything in #15291

**Comment by PhoebeHui** [comment]
@xandox, could you please resolve the conflicts?

@BillyONeal, could you help further review?

**Review by vicroms — APPROVED** [review]
This looks OK to me.

**Pull request merged**
