### PR TITLE
[krabsetw] Update to 4.3.1

### PR DESCRIPTION
**Pull request by dahapls**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by dahapls** [comment]
https://github.com/microsoft/vcpkg/pull/33640

**Comment by dahapls** [comment]
@microsoft-github-policy-service agree

**Comment by MonicaLiu0311** [comment]
An error occurred while testing usage, but was not caused by your PR, would you like to fix it?

usage:
```
krabsetw is header-only and can be used from CMake via:

    find_path(KRABSETW_INCLUDE_DIRS "krabs.hpp")
    target_include_directories(main PRIVATE ${KRABSETW_INCLUDE_DIRS})
```

When testing usage, the following error occurs:
```
>------ Build All started: Project: CMakeUsage, Configuration: x64-Debug ------
  MSBuild version 17.6.3+07e294721 for .NET Framework
  
    Checking Build System
    Building Custom Rule C:/Users/monica/source/repos/CMakeUsage/CMakeUsage/CMakeLists.txt
    CMakeUsage.cpp
G:\vcpkg\installed\x64-windows\include\krabs\kt.hpp(108,9): error C2440: 'return': cannot convert from 'const char [17]' to 'std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>>' [C:\Users\monica\source\repos\CMakeUsage\out\build\x64-debug\CMakeUsage\main.vcxproj]
  G:\vcpkg\installed\x64-windows\include\krabs\kt.hpp(108,9): message : No constructor could take the source type, or constructor overload resolution was ambiguous [C:\Users\monica\source\repos\CMakeUsage\out\build\x64-debug\CMakeUsage\main.vcxproj]

Build All failed.
```

<details>
<summary><b>CMakeFindUsage.cpp</b></summary>
<pre>
#include &#60;iostream&#62;
#include "krabs.hpp"

using namespace std;

int main()
{
        cout << "Hello CMake." << endl;
        return 0;
}
</pre></details>


<details>
<summary><b>CMakeLists.txt</b></summary>
<pre>
cmake_minimum_required (VERSION 3.8)

set(CMAKE_TOOLCHAIN_FILE "E:/krabsetw/scripts/buildsystems/vcpkg.cmake")

project ("CMakeFindUsage")

add_library (main "CMakeFindUsage.cpp")

find_path(KRABSETW_INCLUDE_DIRS "krabs.hpp")
target_include_directories(main PRIVATE ${KRABSETW_INCLUDE_DIRS})
</pre></details>

**Comment by MonicaLiu0311** [comment]
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review".

**Comment by dahapls** [comment]
> Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review".

I apologize for late reply, I was out of town last week, I'll take a look and see if I can figure out the testing stage error this week

**Comment by dahapls** [comment]
Hi Monica, I've found the issue with the testing usage. It was missing the preprocessor definition for UNICODE that prevents it from building successfully (https://github.com/microsoft/krabsetw/blob/550f5edfdb6464567d7a618702316183d31746e5/krabs/README.md?plain=1#L5C15-L5C15).  Adding `add_compile_definitions(UNICODE)` to CMakeLists.txt lets it build without errors.

**Comment by BillyONeal** [comment]
Can you add a usage file which says that UNICODE needs to be on? See https://learn.microsoft.com/en-us/vcpkg/maintainers/handling-usage-files

**Comment by BillyONeal** [comment]
Actually nevermind this is just an update.

**Pull request merged**
