### PR TITLE
[Proposal] Add a new triplet for static libraries with dynamic CRT linkage

### PR DESCRIPTION
**Pull request by frabert**
Static libraries with dynamic CRT linkage are useful if one wants to build a dynamic library further down the line that links its dependencies as static libraries instead of dynamic ones. For example, consider `libfoo` that depends on `libbar` and `libquux`: if one was to distribute `libfoo.dll`, right now they would have to distribute `libbar.dll` and `libquux.dll` as well. With this triplet, it would be possible to build `libbar.lib` and `libquux.lib` and link them into `libfoo.dll`, which would then be self-sufficient.

### CODE REVIEW

**Comment by degski** [comment]
What's wrong with linking those static libs to the static crt and the dynamic ones to the dynamic crt?

**Comment by frabert** [comment]
> 
> 
> What's wrong with linking those static libs to the static crt and the dynamic ones to the dynamic crt?
>

You'd get linker errors about mismatched CRT linkage when merging the two sets together.

>
>
> Apart from the above, nothing stops you from creating your own triple.
>

This seems like a common enough problem with an easy enough fix that it seem sensible to me to include it out-of-the-box.

**Comment by contre** [comment]
Based on the fact that dynamic everything is the default for windows, I’d recommend the name for this triplet be something along the lines of x64-windows-static-dyncrt.

Maybe a bit verbose but it follows the already established naming convention of the dynamic and static triplets.

**Comment by frabert** [comment]
I'm not opposed to changing the name of the triplet -- the name in the PR is just the first thing I've come up with.

**Comment by contre** [comment]
And I am not tied to my suggested name either. I just wanted to contribute My opinion so please feel free to ignore it if you have any strong feelings against it.

**Comment by dan-shaw** [comment]
Closing because #10028 is merged. Please reopen if I'm missing anything.

**Pull request closed without merging**
