### PR TITLE
add UVAtlas

### PR DESCRIPTION
**Pull request by sdcb**

### CODE REVIEW

**Comment by codicodi** [comment]
How is the VS project going to find dependencies?

**Comment by ras0219-msft** [comment]
Here's the build failure I get (basically, can't find the dependencies):
```
"D:\src\vcpkg\buildtrees\uvatlas\src\UVAtlas-sept2016\UVAtlasTool\UVAtlasTool_2015.sln" (default target) (1) ->
       "D:\src\vcpkg\buildtrees\uvatlas\src\UVAtlas-sept2016\UVAtlasTool\UVAtlasTool_2015.vcxproj" (default target) (3) ->
       (ResolveProjectReferences target) -> 
         C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1611,5): warning : The referenced project '..\..\DirectXMesh\DirectXMesh\DirectXMesh_Desktop_2015.vcxproj' does not exist. [D:\src\vcpkg\buildtrees\uvatlas\src\UVAtlas-sept2016\UVAtlasTool\UVAtlasTool_2015.vcxproj]
         C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1611,5): warning : The referenced project '..\..\DirectXTex\DirectXTex\DirectXTex_Desktop_2015.vcxproj' does not exist. [D:\src\vcpkg\buildtrees\uvatlas\src\UVAtlas-sept2016\UVAtlasTool\UVAtlasTool_2015.vcxproj]


       "D:\src\vcpkg\buildtrees\uvatlas\src\UVAtlas-sept2016\UVAtlasTool\UVAtlasTool_2015.sln" (default target) (1) ->
       (Build target) -> 
         D:\src\vcpkg\buildtrees\uvatlas\src\UVAtlas-sept2016\UVAtlasTool\UVAtlasTool_2015.sln.metaproj : error MSB3202: The project file "D:\src\vcpkg\buildtrees\uvatlas\src\UVAtlas-sept2016\UVAtlasTool\..\..\DirectXTex\DirectXTex\DirectXTex_Desktop_2015.vcxproj" was not found. [D:\src\vcpkg\buildtrees\uvatlas\src\UVAtlas-sept2016\UVAtlasTool\UVAtlasTool_2015.sln]
         D:\src\vcpkg\buildtrees\uvatlas\src\UVAtlas-sept2016\UVAtlasTool\UVAtlasTool_2015.sln.metaproj : error MSB3202: The project file "D:\src\vcpkg\buildtrees\uvatlas\src\UVAtlas-sept2016\UVAtlasTool\..\..\DirectXMesh\DirectXMesh\DirectXMesh_Desktop_2015.vcxproj" was not found. [D:\src\vcpkg\buildtrees\uvatlas\src\UVAtlas-sept2016\UVAtlasTool\UVAtlasTool_2015.sln]


       "D:\src\vcpkg\buildtrees\uvatlas\src\UVAtlas-sept2016\UVAtlasTool\UVAtlasTool_2015.sln" (default target) (1) ->
       "D:\src\vcpkg\buildtrees\uvatlas\src\UVAtlas-sept2016\UVAtlasTool\UVAtlasTool_2015.vcxproj" (default target) (3) ->
       (ClCompile target) -> 
         UVAtlas.cpp(34): fatal error C1083: Cannot open include file: 'directxtex.h': No such file or directory [D:\src\vcpkg\buildtrees\uvatlas\src\UVAtlas-sept2016\UVAtlasTool\UVAtlasTool_2015.vcxproj]
         d:\src\vcpkg\buildtrees\uvatlas\src\uvatlas-sept2016\uvatlastool\mesh.h(33): fatal error C1083: Cannot open include file: 'directxmesh.h': No such file or directory [D:\src\vcpkg\buildtrees\uvatlas\src\UVAtlas-sept2016\UVAtlasTool\UVAtlasTool_2015.vcxproj]

    2 Warning(s)
    4 Error(s)

Time Elapsed 00:00:01.94
```

**Comment by sdcb** [comment]
@Robert Schumacher, @codicodi  sorry for inconvenience, I'll fix that.

**Comment by sdcb** [comment]
@codicodi @ras0219-msft I fixed the build by dropped the uvatlastool.exe, please review again, thanks.

**Comment by codicodi** [comment]
Well if it builds now then I guess it's OK... but there is probably no need to install the debug lib twice :)

In the long them I think this library as well as DirectX* ones should be switched to (possibly pushed upstream) cmake builds. It shouldn't be hard as all of them are rather simple. This could allow us to:
- Easily support more than one VS version. 
- Possibly enable dynamic build with cmake's autoexport (as long as there are no data symbols in public interface)
- Support static builds with either static or dynamic CRT. Currently dynamic one is always used and `*-windows-static` triplets fail (post-build checks complain about mismatch).

**Comment by sdcb** [comment]
Hey guys, what's more can I need to do for helping you merge this PR?

**Comment by alexkaratarakis** [comment]
This looks solid to me. Merging, thanks!

**Pull request merged**
