### PR TITLE
Update 0002-Fix-z7-override.patch

### PR DESCRIPTION
**Pull request by DrPizza**
The current patch doesn't apply any more. This makes the same change to the right location.

### CODE REVIEW

**Comment by vicroms** [comment]
All tests passed, thanks for your PR!

**Comment by DrPizza** [comment]
Oh, is it necessary to bump the version of gtest now, so that it rebuilds with the correct debug info?

**Comment by vicroms** [comment]
@DrPizza 

My bad, sorry! 😞 
I forgot to check for the CONTROL version bump.

Yes, it is really important!  Otherwise, we will have two different ports using the same version number (people with the old patch vs people with the new patch). And that could make issue reporting/debugging very difficult.

**Comment by DrPizza** [comment]
Do you want to revert so I can fix it, or can you just update the version separately?

**Comment by vicroms** [comment]
I reverted the PR.
Please create a new one with the updated patch and CONTROL version.

**Pull request merged**
