### PR TITLE
[vcpkg] New policy: SKIP_ARCHITECTURE_CHECK.

### LINKED ISSUE #919: How to solve "Could not find proper second linker member"?
Hi,

I am trying to port [openblas](http://www.openblas.net/), the strategy is to directly download the binary distribution and copy the include , lib and dlls to the desired place.

Here is my temporary code,

```

include(vcpkg_common_functions)
if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")
    message(WARNING "openblas only support dynamic link for msvc")
    set(VCPKG_LIBRARY_LINKAGE "dynamic")
endif()
if(TARGET_TRIPLET STREQUAL "x86-windows")
    message(WARNING "current only port openblas for x64-windows")
    set(TARGET_TRIPLET "x64-windows")
endif()

set(SOURCE_PATH ${CURRENT_BUILDTREES_DIR}/src)
set(SOURCE_OPENBLAS ${SOURCE_PATH}/OpenBLAS-v0.2.19-Win64-int32)
set(SOURCE_MINGW64 ${SOURCE_PATH}/mingw64_dll)

vcpkg_download_distfile(ARCHIVE
    URLS "https://nchc.dl.sourceforge.net/project/openblas/v0.2.19/OpenBLAS-v0.2.19-Win64-int32.zip"
    FILENAME "OpenBLAS-v0.2.19-Win64-int32.zip"
    SHA512 2bb13bf5e322d35e0bef7ef1ca986653117ef74e1071108520273ee9703e6b9cbec3cd615bfac6b52965fb7d661b76628a5526a8e658628b172fb7585cde2219
)
vcpkg_download_distfile(MINGW64_DLL
    URLS "https://nchc.dl.sourceforge.net/project/openblas/v0.2.14/mingw64_dll.zip"
    FILENAME "mingw64_dll.zip"
    SHA512 8fabb10c6556686d1b04816f6ba62702f607d90cdae9c3c20e598d0330acfcbb361a3fd811402f34f896c88a232e29541ec2e98cfa9ae698b2f7c6216e2b8420
)
vcpkg_extract_source_archive(${ARCHIVE})
vcpkg_extract_source_archive(${MINGW64_DLL})

# apply patches
vcpkg_apply_patches(
    SOURCE_PATH ${SOURCE_OPENBLAS}
    PATCHES "${CMAKE_CURRENT_LIST_DIR}/config-file-use-relative-path.patch"
)

# copy include headers
file(COPY ${SOURCE_OPENBLAS}/include 
    DESTINATION ${CURRENT_PACKAGES_DIR})

# copy lib
file(COPY ${SOURCE_OPENBLAS}/lib/libopenblas.dll.a 
    DESTINATION ${CURRENT_PACKAGES_DIR}/lib)
file(COPY ${SOURCE_OPENBLAS}/lib/libopenblas.dll.a 
    DESTINATION ${CURRENT_PACKAGES_DIR}/debug/lib)
file(RENAME ${CURRENT_PACKAGES_DIR}/lib/libopenblas.dll.a ${CURRENT_PACKAGES_DIR}/lib/libopenblas.lib)
file(RENAME ${CURRENT_PACKAGES_DIR}/debug/lib/libopenblas.dll.a ${CURRENT_PACKAGES_DIR}/debug/lib/libopenblas.lib)

#copy dlls
file(COPY ${SOURCE_OPENBLAS}/bin 
    DESTINATION ${CURRENT_PACKAGES_DIR})
file(COPY ${SOURCE_OPENBLAS}/bin 
    DESTINATION ${CURRENT_PACKAGES_DIR}/debug)
file(GLOB MINGW64_DLL_FILES ${SOURCE_MINGW64}/*.dll)

file(COPY ${MINGW64_DLL_FILES}
    DESTINATION ${CURRENT_PACKAGES_DIR}/bin)
file(COPY ${MINGW64_DLL_FILES}
    DESTINATION ${CURRENT_PACKAGES_DIR}/debug/bin)

# copy cmake
file(COPY ${SOURCE_OPENBLAS}/lib/cmake
    DESTINATION ${CURRENT_PACKAGES_DIR}/share/openblas)

# copy license
file(COPY ${CMAKE_CURRENT_LIST_DIR}/LICENSE
    DESTINATION ${CURRENT_PACKAGES_DIR}/share/openblas)
file(RENAME ${CURRENT_PACKAGES_DIR}/share/openblas/LICENSE ${CURRENT_PACKAGES_DIR}/share/openblas/copyright)
```

And I have successfully get the packages in the `./vcpkg/packages/openblas_x64-windows` as below,

snipaste_20170408_121153

But at last, I have encountered the error, and I have no idea what is this.
```
-- Performing post-build validation
Could not find proper second linker member
```

So, is this strategy OK to only copy the files but no compilation? Because openblas is C, and I think it is ABI compatible if only dynamic link is used.

If it's OK, how could I solve the `Could not find proper second linker member` problem?

Thanks,

Han

### LINKED ISSUE #3902: Build new package. Could not find proper second linker member.
#### General
I try to build a **vcpkg** package for **mit-optim** library (https://github.com/libmir/mir-optim). It has only one header file and one static library.
I have checked its work in MSVS 2017 Community.

#### The machine setup: 
1. Windows 10 Education.
2. en-en locale.
3. OS build: 17134.165

#### The steps to reproduce:
1. `vcpkg create mir-optim`
2. add attached [portfile.cmake](https://github.com/Microsoft/vcpkg/files/2194656/portfile.txt) in ports/mir-optim
3. `vcpkg build mir-optim:x64-windows-static`

#### The outcome you expected
1. Download Dlang compiler for mir-optim
2. Compile source code to mir-optim.lib
3. Pass post-validation tests

#### The actual outcome
I have got a crash dialog the same as here https://github.com/Microsoft/vcpkg/issues/919.
```
-- Performing post-build validation
Could not find proper second linker member
```

I compared openblas.lib and mir-optim.lib using: `DUMPBIN /ARCHIVEMEMBERS libname.lib`
For **mir-optim.lib** I got:
`Archive member name at 240E: /0              .dub\build\library-better-c-release-windows-x86_64-ldc_2080-A774BCC55B177EA464176B4C2CBCB970\least_squares_0ef42f2f.obj`

For **openblas.lib**:
`Archive member name at B02A: openblas.dll/`

If I right understand this line of code:
`Checks::check_exit(VCPKG_LINE_INFO, second_linker_member_header.name().substr(0, 2) == "/ ", "Could not find proper second linker member"); `
The archive member name must be in the right format. 

So how can I deal with this problem as Dlang compiler does not have features for changing these names?

### PR DESCRIPTION
**Pull request by Neumann-A**
The check only works if MS link.exe is used
otherwise the second linker member is missing
(according to the observed errors)

(Might only be useful for community triplets targeting windows e.g. using clang-cl and lld via llvm toolset)

closes #919
closes #3902

### CODE REVIEW

**Review by dan-shaw — APPROVED** [review]

**Comment by dan-shaw** [comment]
@Neumann-A Could you elaborate what do you mean when you say the second linker member is missing or point to some instances where this occurs.

**Comment by Neumann-A** [comment]
@dan-shaw:
Triplet:
```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
if(DEFINED VCPKG_PLATFORM_TOOLSET) 
# Silly trick to switch platform toolset to llvm while making sure vcpkg does what it normally does 
    set(VCPKG_PLATFORM_TOOLSET llvm)
endif()
set(ENV{CXX} "C:\\Program Files\\LLVM\\bin\\clang-cl.exe") # for ninja
set(ENV{CC} "C:\\Program Files\\LLVM\\bin\\clang-cl.exe")
```

```
$ ./vcpkg.exe install zlib:x64-windows-llvm
Computing installation plan...
The following packages will be built and installed:
    zlib[core]:x64-windows-llvm
Starting package 1/1: zlib:x64-windows-llvm
Building package zlib[core]:x64-windows-llvm...
-- Using cached D:/vcpkg_common/downloads/zlib1211.tar.gz
-- Using source at F:/vcpkg/buildtrees/zlib/src/1.2.11-deec42f53b
-- Configuring x64-windows-llvm
-- Building x64-windows-llvm-dbg
-- Building x64-windows-llvm-rel
-- Installing: F:/vcpkg/packages/zlib_x64-windows-llvm/share/zlib/copyright
-- Performing post-build validation
Could not find proper second linker member
```

zlib:x64-windows-llvm dumpbin /ALL:
[zlib.llvm.symbols.txt](https://github.com/microsoft/vcpkg/files/4399658/zlib.llvm.symbols.txt)

Probably also the reason why the mingw community triplet uses static library linkage.

This always happens if another linker then the VS one is used on windows hosts.

**Comment by Neumann-A** [comment]
Or should it be named `SKIP_LIB_ARCHITECTURE_CHECK` ? 
Note:
This PR was taken out of #4609. After testing @qis found out that I accidentally remove the wrong architecture check because I copied the wrong part out of #4609. That is why I renamed the title of the PR although I cannot rename the branch without closing and opening up a new PR.

**Comment by qis** [comment]
Works like a charm now!

I'd like to add that this is absolutely necessary to enable LTO since `link.exe` doesn't know what to do with the generated bytecode.

```
/clang:-flto=full /clang:-fwhole-program-vtables /clang:-fvirtual-function-elimination
```

**Comment by Neumann-A** [comment]
closes #919

**Comment by Neumann-A** [comment]
related #4997

**Pull request merged**
