### PR TITLE
[libxml2] Pass version to rc via configured file

### PR DESCRIPTION
**Pull request by dg0yt**
- #### What does your PR fix?  
  This change fixes a build failure on mingw/Windows from issues with quoting/escaping the dotted version string when passing it to the resource compiler.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all, no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  yes

### CODE REVIEW

**Review by JonLiu1993 — APPROVED** [review]

**Comment by ras0219-msft** [comment]
LGTM, thanks for the fix!

**Comment by JackBoosY** [comment]
Does the upstream know this bug or fixed it?

**Comment by dg0yt** [comment]
There is no upstream bug. The `CMakeLists.txt` comes from vcpkg. That's why the include was missing.

**Comment by dg0yt** [comment]
FTR, upstream creates `rcVersion.h` here: 
https://gitlab.gnome.org/GNOME/libxml2/-/blob/master/win32/configure.js#L283-294

**Pull request merged**
