### PR TITLE
Suggest support expressions

### PR DESCRIPTION
**Pull request by autoantwort**
As an alternative to #21489

### CODE REVIEW

**Comment by autoantwort** [comment]
Any news?

**Comment by JackBoosY** [comment]
Ping @strega-nil-ms for review this PR.

**Comment by BillyONeal** [comment]
This one is "easy" enough I think we should consider just bulk fixing them and truly deprecating...

**Comment by autoantwort** [comment]
There are "easy" cases, but there are also ports where there is an existing `supports` expression and a `vcpkg_fail_port_install` call, but they differ in semantics. So you have to fix all this ports manually. Currently `vcpkg_fail_port_install` is used in 293 ports.

**Comment by BillyONeal** [comment]
> There are "easy" cases, but there are also ports where there is an existing `supports` expression and a `vcpkg_fail_port_install` call, but they differ in semantics. So you have to fix all this ports manually. Currently `vcpkg_fail_port_install` is used in 293 ports.

I'm down to 161 remaining and they've been relatively straightforward...

**Comment by BillyONeal** [comment]
OK I have submitted PRs to eliminate all the calls; I would prefer to merge those then adopt https://github.com/microsoft/vcpkg/pull/21489 (outright deprecation) instead.

**Comment by BillyONeal** [comment]
There are officially no more `vcpkg_fail_port_install` calls in master so I think we should do https://github.com/microsoft/vcpkg/pull/21489 instead.

**Comment by ras0219-msft** [comment]
Agreed with @BillyONeal, closing this in favor of #21489.

**Pull request closed without merging**
