### PR TITLE
[angelscript] Add new port

### PR DESCRIPTION
**Pull request by NoFr1ends**
https://www.angelcode.com/angelscript/

### CODE REVIEW

**Comment by NancyLi1013** [comment]
Hi @NoFr1ends, thanks for the new port. I see the failures on arm64-windows and arm-uwp. Are those expected?
[failureLogs.zip](https://github.com/microsoft/vcpkg/files/3170929/failureLogs.zip)

**Comment by NoFr1ends** [comment]
It looks like the arm64-windows and arm-uwp are missing MASM for compiling assembler.
I have no knowledge in arm windows, is it possible to test the build locally?

**Comment by NoFr1ends** [comment]
It looks like cmake currently does not support armasm and try to use masm instead which fails.
So currently this is expected.

**Comment by vicroms** [comment]
Thanks for the PR!

**Pull request merged**
