### PR TITLE
[armadillo] Add dependent port superlu on osx

### PR DESCRIPTION
**Pull request by JackBoosY**
[Official document](https://gitlab.com/conradsnicta/armadillo-code#4-compilers-and-external-dependencies):
```
### 4: Compilers and External Dependencies

Armadillo makes extensive use of template meta-programming and many other advanced C++ features. As such, C++ compilers which do not fully implement the C++ standard may not work correctly.

The functionality of Armadillo is partly dependent on other libraries: LAPACK, BLAS (preferably OpenBLAS), ARPACK and SuperLU. LAPACK and BLAS are used for dense matrices, while ARPACK and SuperLU are used for sparse matrices.

Armadillo can work without the above libraries, but its functionality will be reduced. Basic functionality will be available (eg. matrix addition and multiplication), but operations like eigen decomposition or matrix inversion will not be. Matrix multiplication (mainly for big matrices) may not be as fast.

As Armadillo is a template library, we recommended that optimisation is enabled during compilation of programs that use Armadillo. For example, for GCC and Clang compilers use -O2 or -O3
```

Related: #10767 #11037 #11018 #10476 #11016 #11036 #11020 #10295 #8871 #11058 #11017 #11057 #9550 #11010 #11055 #11057 #11058 #10943.

### CODE REVIEW

**Review by LilyWangL — APPROVED** [review]

**Comment by JackBoosY** [comment]
@strega-nil Please merge this PR first.

Thanks.

**Comment by cenit** [comment]
Why superlu is a dependency (as a feature!) for armadillo only for osx?

Also, I'm not sure superlu port is ok.
On macOS it's best to avoid installing openblas, since the Accelerate framework (native in osx) includes a better version and is already available. So superlu in its control file shall depend (like any other port) on openblas(!osx) maybe?

**Comment by cbezault** [comment]
Like @cenit pointed out superlu definitely needs to not install OpenBLAS on macOS and use the Accelerate framework instead. 

Looking at the doc @JackBoosY is quoting from I'm also surprised we don't need superlu on other platforms. Perhaps OpenBLAS provides some of the same functions as superlu (OpenBLAS is known to do that kind of stuff).

**Comment by cenit** [comment]
@cbezault Exactly. Please do not merge *confused* pr only to apparently fix things.

**Comment by BillyONeal** [comment]
> @cbezault Exactly. Please do not merge _confused_ pr only to apparently fix things.

It doesn't seem like a confused PR, it seems like a PR correctly documenting the status quo, since the only way this passed before was accidentally getting superlu on the box first?

**Comment by cenit** [comment]
1. Superlu is not mandatory for armadillo
2. If it were mandatory, why is it only for osx?

**Comment by BillyONeal** [comment]
1. And yet, the build for it is failing due to a missing superlu header.
2. No idea.
3. Maybe, but the PR seems to be documenting the status quo rather than changing something here.

**Comment by BillyONeal** [comment]
> 3\. Armadillo was working on OS X well before the very recent superlu port...

Other ports vendored superlu. For example `hypre`.

**Comment by strega-nil** [comment]
I think this is not correct; it works fine without updating armadillo right now on my macbook, this seems like an issue with a different port that's getting installed. Can we just skip it in CI for now and try and figure it out later?

**Comment by BillyONeal** [comment]
@strega-nil You are the mac wizard :)

**Comment by cbezault** [comment]
A vendored superlu is a plausible explanation for what's going on but I have to agree with @cenit, it's just an unknown right now. I'd rather see this port get skipped and we actually fix it right.

**Comment by Neumann-A** [comment]
```
  message(STATUS "     MKL_FOUND = ${MKL_FOUND}"     )
  message(STATUS "  ACMLMP_FOUND = ${ACMLMP_FOUND}"  )
  message(STATUS "    ACML_FOUND = ${ACML_FOUND}"    )
  message(STATUS "OpenBLAS_FOUND = ${OpenBLAS_FOUND}")
  message(STATUS "   ATLAS_FOUND = ${ATLAS_FOUND}"   )
  message(STATUS "    BLAS_FOUND = ${BLAS_FOUND}"    )
  message(STATUS "  LAPACK_FOUND = ${LAPACK_FOUND}"  )

include(ARMA_FindARPACK)
message(STATUS "ARPACK_FOUND = ${ARPACK_FOUND}")

include(ARMA_FindSuperLU5)
message(STATUS "SuperLU_FOUND = ${SuperLU_FOUND}")
```

Armadillo's CMakeLists.txt probably needs to be patched to put all those dependencies behind an option

BLAS and LAPACK are already patched

**Comment by BillyONeal** [comment]
https://github.com/microsoft/vcpkg/pull/11091 just adds to the baseline.

**Comment by ras0219-msft** [comment]
Since this is the underlying issue causing the mlpack:x64-osx regression, I've added a patch that disables all the dynamic dependency enablement. Through future PRs, these individual dependencies can be reenabled via features :)

**Comment by ras0219-msft** [comment]
Note: the OSX CI check appears offline, so this should not be merged until that is resolved.

**Comment by Neumann-A** [comment]
>Since this is the underlying issue causing the mlpack:x64-osx regression

It is one reason. The other reason is that some port is vendoring SuperLU. So somebody needs to find the port doing it

**Comment by BillyONeal** [comment]
> Note: the OSX CI check appears offline, so this should not be merged until that is resolved.

It's part of the 'microsoft.vcpkg' check now :)

**Pull request merged**
