### PR TITLE
Added fluid.exe to output tools

### PR DESCRIPTION
**Pull request by smasherprog**
This is added as per the conversion here https://github.com/Microsoft/vcpkg/pull/551#issuecomment-303247813
If this should not be in the vcpkg output, please close the PR.

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for the PR!

In the future, it would be helpful to attach a link to the documentation -- until this PR, I had no idea fluid even existed, so it makes it hard to decide whether to accept the PR 😄!

http://www.fltk.org/doc-1.1/fluid.html

**Comment by ras0219-msft** [comment]
Thanks!

**Comment by stekyne** [comment]
Finally got around to testing this. It seems that the CMake file can't find the fluid executable. Even though it does appear to be in "tools/fltk/fluid.exe".

If I remove the extra "fltk" directory and put the files in "tools". It does work as expected. However, I assume the reason this was done was to not pollute the tools dir with FLTK dependencies. 

Any ideas?

**Comment by ras0219-msft** [comment]
Sorry for dropping this on the floor a bit :)

The fix (which we need to do for other reasons) is to add all first-level-subdirectories of `tools\` to `CMAKE_PROGRAM_PATH`. I'm planning to do this as part of another PR merge: be68dcc.

**Comment by stekyne** [comment]
Excellant, thanks for doing that!

**Pull request merged**
