### PR TITLE
add seqan library for vcpkg

### PR DESCRIPTION
**Pull request by alienzj**

### CODE REVIEW

**Comment by Codiferous** [comment]
@alienzj Thanks for this PR! Is this effectively a duplicate of #5239? I spent some time with both pull requests, and I believe that this is the PR that we should base off of. The reason is that the Seqan library itself recommends that users install the library by copying the package from http://packages.seqan.de (as this PR does). The other PR copies the sources from git, but the include structure appears to differ from the expected structure. This PR seems to place the files in the right structure -- my thought is that the packaging process that the Seqan distributors use restructures the include directory.

I also believe that this PR uses the correct name (`seqan` instead of `seqan3`). The library seems to refer to itself as `Seqan`, and the library is not packaged with a consistent name across different repositories (there are a lot of `seqan`, `seqan2`, `seqan3`). I'd prefer to use `seqan`.

If this PR is a duplicate of #5239, let's close the other PR and get this one completed. 😄

**Comment by Codiferous** [comment]
@alienzj After a little more thorough looking, it seems that these are actually intended to be treated as two separate libraries, so the two PRs you submit are not actually duplicates. I'll take a look at both!

**Comment by alienzj** [comment]
Thanks very much~

**Comment by Codiferous** [comment]
This PR looks good! I'm going to merge it -- thanks! 😄

**Pull request merged**
