### PR TITLE
Add Microsofts openssl fork which supports the UWP platform

### PR DESCRIPTION
**Pull request by pdehne**

### CODE REVIEW

**Comment by ras0219-msft** [comment]
This should be merged with the existing `openssl` portfile so that libraries depending on `openssl` can potentially be compiled for UWP.

**Comment by pdehne** [comment]
I would love to do that, but the original openssl distribution does not support UWP. The changes in Microsofts fork of openssl have not been integrated into the upstream repository.

**Comment by ras0219-msft** [comment]
I merged them together by switching at the top of the `ports\openssl\portfile.cmake` and diverting the build to your portfile if UWP is requested.

It would be ideal in the future to merge the codepaths slightly, but this is still an excellent start. Thanks again!

**Comment by pdehne** [comment]
Thats great! I did not know that was possible. Once caveat to keep in mind: the downloaded versions for regular and UWP may be different which could confuse users.

**Pull request merged**
