### PR TITLE
[qt5] Fix qt5 dll missing

### LINKED ISSUE #14712: [qt5] module "QtQuick.Dialogs" is not installed
**Describe the bug**
While #14594 fixed a few bugs related to QML deployment I still get the error
```
QQmlApplicationEngine failed to load component
qrc:/main.qml:4:1: module "QtQuick.Dialogs" is not installed
```
when I do `import QtQuick.Dialogs 1.2` inside a QML file.

**To Reproduce**
1. `./vcpkg install qt5`
(`./vcpkg install qt5-declarative` should be enough in this case, but I tested with both to be sure)
2. `import QtQuick.Dialogs 1.2` inside a QML file.
3. Build & run project.

**Expected behavior**
All imports inside a qml file should be deployed to the output folder.

**Additional context**
Inside `{output path to binary}/qml/QtQuick` the Dialogs folder is indeed missing.

### LINKED ISSUE #16983: [qt5] QML `qtquick2plugind.dll` cannot be loaded
It seems QML is not working now. See this repo for reporduce: https://github.com/upupming/vcpkg-qt5-qml-bug

> Did we forget to copy some libraries to the tools folder?

@JackBoosY I got this bug, too when I build a QML project (an empty QML project from Qt creator).

image

It says `C:\Users\ming\projects\tooth-studio\build\Debug\qml\QtQuick.2\qtquick2plugind.dll` couldn't be found, but it exists there:

image

_Originally posted by @upupming in https://github.com/microsoft/vcpkg/issues/14156#issuecomment-810992704_

### PR DESCRIPTION
**Pull request by xiaozhuai**
- #### What does your PR fix?
1. Fix #16983
2. Fix #14712
3. Add translations and websockets to default features

### CODE REVIEW

**Comment by xiaozhuai** [comment]
Hello @MonicaLiu0311 
I've already change port-version and exec `vcpkg x-add-version --all`
Why the error says
```
    Error: While reading versions for port qt5 from file: C:\a\1\s\versions\q-\qt5.json
       File declares version `5.15.7#1` with SHA: 643ca0349ac0a0c9d8bb74d92e9bfca3f2bb395f
       But local port with the same version has a different SHA: ae86831b5413a334195f8751e78e2ad9fcbd4349
       Please update the port's version fields and then run:

           vcpkg x-add-version qt5
           git add versions
           git commit -m "Update version database"

       to add a new version.
    Error: While reading versions for port qt5-base from file: C:\a\1\s\versions\q-\qt5-base.json
       File declares version `5.15.7#2` with SHA: e3ec04e7fab9aa5caef957d5c7ae5265804d7217
       But local port with the same version has a different SHA: 5464e5c86a4d0f0e55e9962a0a4476669411fdaf
       Please update the port's version fields and then run:

           vcpkg x-add-version qt5-base
           git add versions
           git commit -m "Update version database"

       to add a new version.
To attempt to resolve all errors at once, run:
vcpkg x-add-version --all
```

**Comment by xiaozhuai** [comment]
@MonicaLiu0311 Ok, I figure out this. I should first commit all changes and then exec `vcpkg x-add-version --all`

**Comment by MonicaLiu0311** [comment]
> @MonicaLiu0311 Ok, I figure out this. I should first commit all changes and then exec `vcpkg x-add-version --all`

After making any changes, please commit it, then run `./vcpkg x-add-version xxx` to generate the corresponding json; If it is a repeated modification for the same version, please use `./vcpkg x-add-version xxx --overwrite-version` to update git-tree.

**Comment by xiaozhuai** [comment]
Hello @MonicaLiu0311, if there is no problem, please consedering merge this pr.

**Review by MonicaLiu0311 — APPROVED** [review]

**Comment by JavierMatosD** [comment]
Thanks!

**Pull request merged**
