### PR TITLE
[libigl] Fix dynamic build and enable header-only mode

### LINKED ISSUE #14371: [libigl] Enable header-only mode
The libigl port is now only available as a (huge) static library (>1GB). The library is heavily template based thus it would be preferable to keep the header-only mode.

**Is your feature request related to a problem? Please describe.**
I was attempting to use the port but encountered linker error problems because the types passed as arguments, despite being valid, were not explicitly instantiated by the library during vcpkg build.

**Proposed solution**
Removing the build only static constraint and fix what breaks 😄 

**Describe alternatives you've considered**
The explicit instantiations could be added on the libigl side, but this is not a long-term solution due to the combinatorial nature of templates. One may always reach a point where the needed template was not instantiated, and also it raises the problem of binary size (which is already quite extreme here)

### PR DESCRIPTION
**Pull request by FabienPean**
This is an attempt at getting rid of libigl huge static .lib file and getting the header-library mode. I could make it work on my machine (Windows VS2019 Clang 10) with the current set of modifications. Not necessarily optimal nor "clean", but hopefully a good start to resolve the issue. 

Let me know if anything is missing or feel free to take over from here.

- What does your PR fix? Fixes #14371 

- Which triplets are supported/not supported? Have you updated the CI baseline?
Dynamic library version works on windows but not the static, and other platform untested. I don't know what is the CI baseline.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
I think so.

### CODE REVIEW

**Comment by FabienPean** [comment]
Alright so, despite compiling successfully, the baseline x64-windows-static is not actually usable. It leads to `/failifmismatch: mismatch detected for '_ITERATOR_DEBUG_LEVEL'`. Current changes also successfully pass the CI and leads to same problem.

However my question is, should `vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)` be imposed and `ci.baseline.txt` updated to `libigl:x64-windows-static=fail` or stick to "if it compiles it is fine"

Otherwise, I am out of idea to make the static build actually be usable. Since it does not alter the original behavior (on x64-windows) the PR should be ok, but could be simplified if dynamic only is decided (I most probably added too many `if(LIBIGL_USE_STATIC_LIBRARY)` initially hoping to solve the static build issue).

Let me know your opinion on the subject

**Comment by FabienPean** [comment]
The CI x86_windows instance is hogging.

For convenience, I made the gist with the test files here (requires building igl from head for fixes on writeDAE): https://gist.github.com/FabienPean/9c1a6c5eea6b304d0e1241024e0387b1

**Review by LilyWangL — APPROVED** [review]

**Comment by strega-nil** [comment]
Thanks @FabienPean :)

**Pull request merged**
