### PR TITLE
[curl] update to 7.87.0

### LINKED ISSUE #28977: [curl] update to 7.87.0
Library name: curl

New version number: 7.87.0

Other information that may be useful (release notes, etc...)
https://curl.se/changes.html#7_87_0
https://github.com/curl/curl/releases/tag/curl-7_87_0

### PR DESCRIPTION
**Pull request by marekr**
- #### What does your PR fix?
Update to curl 7.87.0 released on Dec 14th

### CODE REVIEW

**Review by JonLiu1993 — DISMISSED** [review]

**Comment by autoantwort** [comment]
Can you add `"supports": "windows & !uwp",` to the `winssl` feature? :)

**Comment by marekr** [comment]
> Can you add `"supports": "windows & !uwp",` to the `winssl` feature? :)

Sure done

**Comment by JonLiu1993** [comment]
@marekr, Thanks for your pr, when I tested the features by the command "./vcpkg install curl[brotli,c-ares,http2,idn,idn2,mbedtls,non-http,openssl,schannel,ssh,ssl,sspi,tool,websockets,winidn,winldap,winssl,wolfssl]:x86-windows" I got this error, could you please take a look:
````
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:131 (message):
    Command failed: F:/Feature-test/curl/vcpkg/downloads/tools/cmake-3.25.0-windows/cmake-3.25.0-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: F:/Feature-test/curl/vcpkg/buildtrees/curl/x86-windows-dbg
    See logs for more information:
      F:\Feature-test\curl\vcpkg\buildtrees\curl\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/curl/portfile.cmake:76 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)
````
F:\Feature-test\curl\vcpkg\buildtrees\curl\install-x86-windows-dbg-out.log:
````
FAILED: lib/CMakeFiles/libcurl.dir/curl_ntlm_core.c.obj 
C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x86\cl.exe   -DBUILDING_LIBCURL -DCURLDEBUG -DCURL_HIDDEN_SYMBOLS -DDEBUGBUILD -DHAVE_CONFIG_H -DLIBSSH2_WIN32 -DOPENSSL_SUPPRESS_DEPRECATED -DUNICODE -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE -D_UNICODE -D_WINDLL -Dlibcurl_EXPORTS -IF:\Feature-test\curl\vcpkg\buildtrees\curl\src\url-7_87_0-fe2580e2b4.clean\include -IF:\Feature-test\curl\vcpkg\buildtrees\curl\x86-windows-dbg\lib\..\include -IF:\Feature-test\curl\vcpkg\buildtrees\curl\src\url-7_87_0-fe2580e2b4.clean\lib\.. -IF:\Feature-test\curl\vcpkg\buildtrees\curl\src\url-7_87_0-fe2580e2b4.clean\lib\..\include -IF:\Feature-test\curl\vcpkg\buildtrees\curl\x86-windows-dbg\lib\.. -IF:\Feature-test\curl\vcpkg\buildtrees\curl\src\url-7_87_0-fe2580e2b4.clean\lib -IF:\Feature-test\curl\vcpkg\buildtrees\curl\x86-windows-dbg\lib -external:IF:\Feature-test\curl\vcpkg\installed\x86-windows\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W4 /utf-8 /MP  /MP /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -MDd /showIncludes /Folib\CMakeFiles\libcurl.dir\curl_ntlm_core.c.obj /Fdlib\CMakeFiles\libcurl.dir\ /FS -c F:\Feature-test\curl\vcpkg\buildtrees\curl\src\url-7_87_0-fe2580e2b4.clean\lib\curl_ntlm_core.c
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\wolfssl/openssl/compat_types.h(54): error C2371: 'EVP_MD': redefinition; different basic types
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\openssl/types.h(103): note: see declaration of 'EVP_MD'
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\wolfssl/openssl/compat_types.h(55): error C2371: 'EVP_MD_CTX': redefinition; different basic types
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\openssl/types.h(104): note: see declaration of 'EVP_MD_CTX'
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\wolfssl/openssl/compat_types.h(56): error C2371: 'EVP_CIPHER': redefinition; different basic types
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\openssl/types.h(101): note: see declaration of 'EVP_CIPHER'
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\wolfssl/openssl/compat_types.h(57): error C2371: 'EVP_CIPHER_CTX': redefinition; different basic types
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\openssl/types.h(102): note: see declaration of 'EVP_CIPHER_CTX'
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\wolfssl/openssl/compat_types.h(58): error C2371: 'ASN1_PCTX': redefinition; different basic types
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\openssl/types.h(70): note: see declaration of 'ASN1_PCTX'
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\wolfssl/openssl/compat_types.h(59): error C2371: 'EVP_PKEY': redefinition; different basic types
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\openssl/types.h(107): note: see declaration of 'EVP_PKEY'
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\wolfssl/openssl/compat_types.h(60): error C2371: 'PKCS8_PRIV_KEY_INFO': redefinition; different basic types
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\openssl/types.h(174): note: see declaration of 'PKCS8_PRIV_KEY_INFO'
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\wolfssl/openssl/compat_types.h(62): error C2371: 'ENGINE': redefinition; different basic types
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\openssl/types.h(183): note: see declaration of 'ENGINE'
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\wolfssl/openssl/compat_types.h(63): error C2371: 'EVP_PKEY_CTX': redefinition; different basic types
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\openssl/types.h(112): note: see declaration of 'EVP_PKEY_CTX'
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\wolfssl/wolfcrypt/rsa.h(163): error C2059: syntax error: 'constant'
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\wolfssl/wolfcrypt/rsa.h(223): error C2065: 'RSA_MAX_ID_LEN': undeclared identifier
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\wolfssl/wolfcrypt/rsa.h(223): error C2057: expected constant expression
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\wolfssl/wolfcrypt/rsa.h(224): error C2229: struct 'RsaKey' has an illegal zero-sized array
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\wolfssl/wolfcrypt/rsa.h(225): error C2065: 'RSA_MAX_LABEL_LEN': undeclared identifier
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\wolfssl/wolfcrypt/rsa.h(225): error C2057: expected constant expression
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\wolfssl/wolfcrypt/rsa.h(226): error C2229: struct 'RsaKey' has an illegal zero-sized array
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\wolfssl/openssl/bn.h(164): error C2371: 'BIGNUM': redefinition; different basic types
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\openssl/types.h(87): note: see declaration of 'BIGNUM'
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\wolfssl/openssl/bn.h(165): error C2371: 'BN_CTX': redefinition; different basic types
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\openssl/types.h(88): note: see declaration of 'BN_CTX'
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\wolfssl/openssl/bn.h(166): error C2371: 'BN_GENCB': redefinition; different basic types
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\openssl/types.h(92): note: see declaration of 'BN_GENCB'
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\wolfssl/openssl/rsa.h(102): error C2371: 'RSA': redefinition; different basic types
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\openssl/types.h(143): note: see declaration of 'RSA'
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\wolfssl/openssl/rsa.h(103): error C2371: 'RSA_METHOD': redefinition; different basic types
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\openssl/types.h(144): note: see declaration of 'RSA_METHOD'
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\wolfssl/openssl/hmac.h(70): error C2371: 'HMAC_CTX': redefinition; different basic types
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\openssl/types.h(132): note: see declaration of 'HMAC_CTX'
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\wolfssl/wolfcrypt/asn.h(760): error C2059: syntax error: 'constant'
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\wolfssl/ssl.h(2324): error C2365: 'OCSP_RESPONSE': redefinition; previous definition was 'typedef'
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\openssl/types.h(203): note: see declaration of 'OCSP_RESPONSE'
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\wolfssl/ssl.h(2324): error C2086: '<unnamed-enum-OCSP_NOCERTS> OCSP_RESPONSE': redefinition
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\wolfssl/ssl.h(2324): note: see declaration of 'OCSP_RESPONSE'
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\wolfssl/ssl.h(2328): error C2365: 'ASN1_GENERALIZEDTIME': redefinition; previous definition was 'typedef'
F:\Feature-test\curl\vcpkg\installed\x86-windows\include\openssl/types.h(57): note: see declaration of 'ASN1_GENERALIZEDTIME'

````

**Comment by JonLiu1993** [comment]
Ping @marekr to response.

**Comment by marekr** [comment]
> Ping @marekr to response.

I am unable to troubleshoot.

wolfssl in vcpkg refuses to download, it seems the url in vcpkg is invalid and doesn't even work in a browser

```
-- Downloading https://github.com/wolfssl/wolfssl/archive/v5.5.0-stable.tar.gz -> wolfssl-wolfssl-v5.5.0-stable.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
Downloading https://github.com/wolfssl/wolfssl/archive/v5.5.0-stable.tar.gz
warning: Download failed -- retrying after 1000ms
error: Failed to download from mirror set
error: https://github.com/wolfssl/wolfssl/archive/v5.5.0-stable.tar.gz: WinHttpReadData failed with exit code 12152
error: https://github.com/wolfssl/wolfssl/archive/v5.5.0-stable.tar.gz: failed: status code 503
```

I have no idea where this `/archive` path url comes from because that's not from the GitHub releases page.

**Comment by autoantwort** [comment]
Strange I can download https://github.com/wolfssl/wolfssl/archive/v5.5.0-stable.tar.gz in my browser and via vcpkg.

**Comment by marekr** [comment]
I ended up downloading it through alternate means and tossing it in the vcpkg cache.

The build issue is openssl + wolfssl combo was broken upstream 
https://github.com/curl/curl/issues/10321

**Comment by marekr** [comment]
FYI, I have also tested and the wolfssl+openssl feature combination is currently broken on the current vcpkg port with curl 7.86.0 which makes sense since the curl breakage happened a few versions earlier for curl

**Review by BillyONeal — APPROVED** [review]
Getting CVE fixes is more important than fixing the non regression. Thanks for the help, and hope Curl fixes their stuff soon!

**Comment by marekr** [comment]
> Getting CVE fixes is more important than fixing the non regression. Thanks for the help, and hope Curl fixes their stuff soon!

It's better than that :D 

curl 7.87 contains a fix for curl 7.84 to 7.86 being broken on windows for tls 1.3. I have dozens of users filing complaints they can't load assets that are hosted on github as a result 

Officially the fix called:
[sendf: change Curl_read_plain to wrap Curl_recv_plain](https://curl.se/bug/?i=9431) / https://github.com/curl/curl/pull/9904

**Pull request merged**
