### PR TITLE
[openvino] 2023.2.0 release

### PR DESCRIPTION
**Pull request by ilya-lavrenov**

### CODE REVIEW

**Comment by MonicaLiu0311** [comment]
@BillyONeal @data-queue 

Currently this PR is affected by [the cache](https://dev.azure.com/vcpkg/public/_build/results?buildId=96698&view=logs&j=7922e5c4-0103-5f8f-ad17-45ce9bb98e80&t=66eef212-08d6-5e6c-a560-7d01149d0188&l=3887) of the old version(2023.1.0#4), and the [CI Pipeline](https://dev.azure.com/vcpkg/public/_build/results?buildId=96698&view=logs&j=7922e5c4-0103-5f8f-ad17-45ce9bb98e80&t=66eef212-08d6-5e6c-a560-7d01149d0188&l=6425) does not run the new version(2023.2.0).



When running `./vcpkg install openvino:x64-windows` locally, the following error occurs:
```
[2/3221] C:/PROGRA~1/CMake/bin/cmcldeps.exe RC G:\openvino\buildtrees\openvino\x64-windows-dbg\src\vs_version.rc src\CMakeFiles\openvino.dir\vs_version.rc.res.d src\CMakeFiles\openvino.dir\vs_version.rc.res "Note: including file: " "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe" C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\rc.exe -DIE_BUILD_POSTFIX=\"d\" -DIE_THREAD=IE_THREAD_TBB -DIN_OV_COMPONENT -DOV_BUILD_POSTFIX=\"d\" -DOV_NATIVE_PARENT_PROJECT_ROOT_DIR=\"2023.2.0-11fa024909.clean\" -DOV_THREAD=OV_THREAD_TBB -DTBB_PREVIEW_WAITING_FOR_WORKERS=1 -DTBB_USE_DEBUG -Dopenvino_EXPORTS -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\core\include -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\frontends\common\include -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\inference\include -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\inference\include\ie -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\core\reference\include -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\core\dev_api -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\core\builder\include -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\core\shape_inference\include -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\common\transformations\include -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\common\itt\include -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\common\util\include -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\common\conditional_compilation\include -I G:\openvino\installed\x64-windows\include -c65001 /DWIN32 -D_DEBUG /fo src\CMakeFiles\openvino.dir\vs_version.rc.res G:\openvino\buildtrees\openvino\x64-windows-dbg\src\vs_version.rc
FAILED: src/CMakeFiles/openvino.dir/vs_version.rc.res 
C:/PROGRA~1/CMake/bin/cmcldeps.exe RC G:\openvino\buildtrees\openvino\x64-windows-dbg\src\vs_version.rc src\CMakeFiles\openvino.dir\vs_version.rc.res.d src\CMakeFiles\openvino.dir\vs_version.rc.res "Note: including file: " "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe" C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\rc.exe -DIE_BUILD_POSTFIX=\"d\" -DIE_THREAD=IE_THREAD_TBB -DIN_OV_COMPONENT -DOV_BUILD_POSTFIX=\"d\" -DOV_NATIVE_PARENT_PROJECT_ROOT_DIR=\"2023.2.0-11fa024909.clean\" -DOV_THREAD=OV_THREAD_TBB -DTBB_PREVIEW_WAITING_FOR_WORKERS=1 -DTBB_USE_DEBUG -Dopenvino_EXPORTS -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\core\include -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\frontends\common\include -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\inference\include -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\inference\include\ie -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\core\reference\include -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\core\dev_api -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\core\builder\include -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\core\shape_inference\include -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\common\transformations\include -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\common\itt\include -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\common\util\include -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\common\conditional_compilation\include -I G:\openvino\installed\x64-windows\include -c65001 /DWIN32 -D_DEBUG /fo src\CMakeFiles\openvino.dir\vs_version.rc.res G:\openvino\buildtrees\openvino\x64-windows-dbg\src\vs_version.rc
Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384

Copyright (C) Microsoft Corporation.  All rights reserved.

G:\openvino\buildtrees\openvino\x64-windows-dbg\src\vs_version.rc(5) : error RC2127 : version WORDs separated by commas expected

G:\openvino\buildtrees\openvino\x64-windows-dbg\src\vs_version.rc(5) : error RC2167 : unrecognized VERSIONINFO field;  BEGIN or comma expected
```

**Comment by ilya-lavrenov** [comment]
> @BillyONeal @data-queue
> 
> Currently this PR is affected by [the cache](https://dev.azure.com/vcpkg/public/_build/results?buildId=96698&view=logs&j=7922e5c4-0103-5f8f-ad17-45ce9bb98e80&t=66eef212-08d6-5e6c-a560-7d01149d0188&l=3887) of the old version(2023.1.0#4), and the [CI Pipeline](https://dev.azure.com/vcpkg/public/_build/results?buildId=96698&view=logs&j=7922e5c4-0103-5f8f-ad17-45ce9bb98e80&t=66eef212-08d6-5e6c-a560-7d01149d0188&l=6425) does not run the new version(2023.2.0).
> 
> When running `./vcpkg install openvino:x64-windows` locally, the following error occurs:
> 
> ```
> [2/3221] C:/PROGRA~1/CMake/bin/cmcldeps.exe RC G:\openvino\buildtrees\openvino\x64-windows-dbg\src\vs_version.rc src\CMakeFiles\openvino.dir\vs_version.rc.res.d src\CMakeFiles\openvino.dir\vs_version.rc.res "Note: including file: " "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe" C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\rc.exe -DIE_BUILD_POSTFIX=\"d\" -DIE_THREAD=IE_THREAD_TBB -DIN_OV_COMPONENT -DOV_BUILD_POSTFIX=\"d\" -DOV_NATIVE_PARENT_PROJECT_ROOT_DIR=\"2023.2.0-11fa024909.clean\" -DOV_THREAD=OV_THREAD_TBB -DTBB_PREVIEW_WAITING_FOR_WORKERS=1 -DTBB_USE_DEBUG -Dopenvino_EXPORTS -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\core\include -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\frontends\common\include -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\inference\include -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\inference\include\ie -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\core\reference\include -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\core\dev_api -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\core\builder\include -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\core\shape_inference\include -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\common\transformations\include -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\common\itt\include -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\common\util\include -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\common\conditional_compilation\include -I G:\openvino\installed\x64-windows\include -c65001 /DWIN32 -D_DEBUG /fo src\CMakeFiles\openvino.dir\vs_version.rc.res G:\openvino\buildtrees\openvino\x64-windows-dbg\src\vs_version.rc
> FAILED: src/CMakeFiles/openvino.dir/vs_version.rc.res 
> C:/PROGRA~1/CMake/bin/cmcldeps.exe RC G:\openvino\buildtrees\openvino\x64-windows-dbg\src\vs_version.rc src\CMakeFiles\openvino.dir\vs_version.rc.res.d src\CMakeFiles\openvino.dir\vs_version.rc.res "Note: including file: " "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe" C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\rc.exe -DIE_BUILD_POSTFIX=\"d\" -DIE_THREAD=IE_THREAD_TBB -DIN_OV_COMPONENT -DOV_BUILD_POSTFIX=\"d\" -DOV_NATIVE_PARENT_PROJECT_ROOT_DIR=\"2023.2.0-11fa024909.clean\" -DOV_THREAD=OV_THREAD_TBB -DTBB_PREVIEW_WAITING_FOR_WORKERS=1 -DTBB_USE_DEBUG -Dopenvino_EXPORTS -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\core\include -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\frontends\common\include -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\inference\include -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\inference\include\ie -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\core\reference\include -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\core\dev_api -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\core\builder\include -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\core\shape_inference\include -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\common\transformations\include -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\common\itt\include -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\common\util\include -I G:\openvino\buildtrees\openvino\src\2023.2.0-11fa024909.clean\src\common\conditional_compilation\include -I G:\openvino\installed\x64-windows\include -c65001 /DWIN32 -D_DEBUG /fo src\CMakeFiles\openvino.dir\vs_version.rc.res G:\openvino\buildtrees\openvino\x64-windows-dbg\src\vs_version.rc
> Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384
> 
> Copyright (C) Microsoft Corporation.  All rights reserved.
> 
> G:\openvino\buildtrees\openvino\x64-windows-dbg\src\vs_version.rc(5) : error RC2127 : version WORDs separated by commas expected
> 
> G:\openvino\buildtrees\openvino\x64-windows-dbg\src\vs_version.rc(5) : error RC2167 : unrecognized VERSIONINFO field;  BEGIN or comma expected
> ```

Added the patch to address the issue.

**Review by MonicaLiu0311 — DISMISSED** [review]

**Comment by MonicaLiu0311** [comment]
> @BillyONeal @data-queue
> 
> Currently this PR is affected by [the cache](https://dev.azure.com/vcpkg/public/_build/results?buildId=96698&view=logs&j=7922e5c4-0103-5f8f-ad17-45ce9bb98e80&t=66eef212-08d6-5e6c-a560-7d01149d0188&l=3887) of the old version(2023.1.0#4), and the [CI Pipeline](https://dev.azure.com/vcpkg/public/_build/results?buildId=96698&view=logs&j=7922e5c4-0103-5f8f-ad17-45ce9bb98e80&t=66eef212-08d6-5e6c-a560-7d01149d0188&l=6425) does not run the new version(2023.2.0).

Marked `info:reviewed` for further review.

**Comment by BillyONeal** [comment]
> > @BillyONeal @data-queue
> > Currently this PR is affected by [the cache](https://dev.azure.com/vcpkg/public/_build/results?buildId=96698&view=logs&j=7922e5c4-0103-5f8f-ad17-45ce9bb98e80&t=66eef212-08d6-5e6c-a560-7d01149d0188&l=3887) of the old version(2023.1.0#4), and the [CI Pipeline](https://dev.azure.com/vcpkg/public/_build/results?buildId=96698&view=logs&j=7922e5c4-0103-5f8f-ad17-45ce9bb98e80&t=66eef212-08d6-5e6c-a560-7d01149d0188&l=6425) does not run the new version(2023.2.0).
> 
> Marked `info:reviewed` for further review.

That's talking about the version in `master`; it's printed as part of the first run that's getting the parent hashes from there.

**Comment by MonicaLiu0311** [comment]
> > > @BillyONeal @data-queue
> > > Currently this PR is affected by [the cache](https://dev.azure.com/vcpkg/public/_build/results?buildId=96698&view=logs&j=7922e5c4-0103-5f8f-ad17-45ce9bb98e80&t=66eef212-08d6-5e6c-a560-7d01149d0188&l=3887) of the old version(2023.1.0#4), and the [CI Pipeline](https://dev.azure.com/vcpkg/public/_build/results?buildId=96698&view=logs&j=7922e5c4-0103-5f8f-ad17-45ce9bb98e80&t=66eef212-08d6-5e6c-a560-7d01149d0188&l=6425) does not run the new version(2023.2.0).
> > 
> > 
> > Marked `info:reviewed` for further review.
> 
> That's talking about the version in `master`; it's printed as part of the first run that's getting the parent hashes from there.

How do we handle this situation so that the CI Pipeline can run the new version properly?

**Comment by dg0yt** [comment]
> How do we handle this situation so that the CI Pipeline can run the new version properly?

There is no problem here, thanks to vcpkg's ABI hashing.

The CI run you linked determined the ABI hash `fae21d8780f63b5581ee2d973421d99e5b65074334458dc97468abf02c4b5946` for the binary artifact, and vcpkg found this artifact in the cache. So it correctly decided that it was not necessary to do another build for this change, and not build output is generated for the new commit.

Note that the port directory had the same state two commits earlier. If nothing else changed in the meantime, the cached artifact was probably generated at this state.

The ABI hashes for the `HEAD` of master (reached via `HEAD~1` from the commit tested by CI) are determined using a "dry run". The output of this invocation used to be hidden, but this made it hard to track vcpkg tool bugs. Maintainers decided to show it again, and that's why there is (dry-run!) install output for the old version. Key output:
~~~
2023-11-17T03:02:18.9438173Z Comparing with HEAD~1
2023-11-17T03:02:28.4110113Z CI baseline unchanged, determining parent hashes
2023-11-17T03:02:28.4400655Z warning: vcpkg ci is an internal command which will change incompatibly or be removed at any time.
2023-11-17T03:02:37.2838325Z Loading dependency information for 973 packages...
2023-11-17T03:02:39.1410970Z Detecting compiler hash for triplet x64-windows...
...
2023-11-17T03:03:05.5975550Z     openvino[auto,auto-batch,core,cpu,gpu,hetero,ir,onnx,paddle,pytorch,tensorflow,tensorflow-lite]:x64-windows -> 2023.1.0#4
...
2023-11-17T03:03:06.0494260Z Running CI for HEAD...
2023-11-17T03:03:06.1530477Z HEAD is now at 60d1df2ec Merge 26e7747e7c46f1889ccad6fd2e9a253e6c7c5513 into 939eaca4969825d5ccd06ec64f7541864c96a606
2023-11-17T03:03:06.1741225Z warning: vcpkg ci is an internal command which will change incompatibly or be removed at any time.
2023-11-17T03:03:06.1749258Z Creating failure logs output directory C:\a\1\a\failure-logs.
2023-11-17T03:03:06.7088488Z Loading dependency information for 973 packages...
2023-11-17T03:03:08.4365244Z Detecting compiler hash for triplet x64-windows...
...
2023-11-17T03:03:21.7054005Z                     openvino:x64-windows:     pass: fae21d8780f63b5581ee2d973421d99e5b65074334458dc97468abf02c4b5946
...
2023-11-17T03:03:22.0595866Z Total install time: 300 ns
2023-11-17T03:03:22.0598857Z 
2023-11-17T03:03:22.0605048Z Triplet: x64-windows
2023-11-17T03:03:22.0611177Z RESULTS
2023-11-17T03:03:22.0614312Z 
2023-11-17T03:03:22.0635834Z 
2023-11-17T03:03:22.0877317Z ##[section]Finishing: *** Test Modified Ports
~~~

**Comment by ilya-lavrenov** [comment]
Can we proceed with merging?

**Comment by ilya-lavrenov** [comment]
Can we proceed with merging?
Customers are waiting for more than 2 weeks

**Comment by dg0yt** [comment]
@BillyONeal You removed info-reviewed - why?

**Comment by MonicaLiu0311** [comment]
All features are tested successfully in the following triplet:
```
x64-windows
x64-windows-static
x64-linux
```

The usage test passed on `x64-windows` (header files found):
```
The package OpenVINO can be used in cmake scripts as:

    find_package(OpenVINO REQUIRED)
    target_link_libraries(main PRIVATE openvino::runtime)

```

**Review by MonicaLiu0311 — APPROVED** [review]

**Pull request merged**
