### PR TITLE
update to QT5.12

### PR DESCRIPTION
**Pull request by renshi-code**
Updates QT to 5.12 LTS

### CODE REVIEW

**Comment by Neumann-A** [comment]
Obviously the difference is in:

`LIBS          = /LIBPATH:C:\dev\vcpkg\installed\x64-windows\debug\lib /LIBPATH:C:\dev\vcpkg\buildtrees\qt5-declarative\x64-windows-dbg\lib C:\dev\vcpkg\buildtrees\qt5-declarative\x64-windows-dbg\lib\Qt5Quickd.lib C:\dev\vcpkg\buildtrees\qt5-declarative\x64-windows-dbg\lib\Qt5Qmld.lib C:\dev\vcpkg\installed\x64-windows\debug\lib\Qt5Guid.lib C:\dev\vcpkg\installed\x64-windows\debug\lib\Qt5Networkd.lib C:\dev\vcpkg\installed\x64-windows\debug\lib\Qt5Cored.lib  glu32.lib opengl32.lib gdi32.lib user32.lib qtmaind.lib `

`LIBS          = glu32.lib opengl32.lib gdi32.lib user32.lib shell32.lib /LIBPATH:C:\dev\test\vcpkg\installed\x64-windows\debug\lib\manual-link qtmaind.lib /LIBPATH:C:\dev\test\vcpkg\installed\x64-windows\debug\lib /LIBPATH:C:\dev\test\vcpkg\buildtrees\qt5-declarative\x64-windows-dbg\lib C:\dev\test\vcpkg\buildtrees\qt5-declarative\x64-windows-dbg\lib\Qt5Quickd.lib C:\dev\test\vcpkg\buildtrees\qt5-declarative\x64-windows-dbg\lib\Qt5Qmld.lib C:\dev\test\vcpkg\installed\x64-windows\debug\lib\Qt5Guid.lib C:\dev\test\vcpkg\installed\x64-windows\debug\lib\Qt5Networkd.lib C:\dev\test\vcpkg\installed\x64-windows\debug\lib\Qt5Cored.lib `

the follwing is missing:
` /LIBPATH:C:\dev\test\vcpkg\installed\x64-windows\debug\lib\manual-link`

**Comment by Neumann-A** [comment]
the error is probably in fixcmake.py in qt5-base

**Comment by Neumann-A** [comment]
ok found the real culprit it is `vcpkg_build_qmake.cmake`

It should do a replace the following string in the makefiles:
`string(REPLACE "/LIBPATH:${NATIVE_INSTALLED_DIR}\\debug\\lib qtmaind.lib" "shell32.lib /LIBPATH:${NATIVE_INSTALLED_DIR}\\debug\\lib\\manual-link qtmaind.lib /LIBPATH:${NATIVE_INSTALLED_DIR}\\debug\\lib" _contents "${_contents}")`

but apparently that is not working. Ending the bugsearch for today

**Comment by Neumann-A** [comment]
probable solution. Just replace:

`string(REPLACE "/LIBPATH:${NATIVE_INSTALLED_DIR}\\debug\\lib qtmaind.lib" "shell32.lib /LIBPATH:${NATIVE_INSTALLED_DIR}\\debug\\lib\\manual-link qtmaind.lib /LIBPATH:${NATIVE_INSTALLED_DIR}\\debug\\lib" _contents "${_contents}")`

with 

`string(REPLACE "/LIBPATH:${NATIVE_INSTALLED_DIR}\\debug\\lib" "/LIBPATH:${NATIVE_INSTALLED_DIR}\\debug\\lib\\manual-link /LIBPATH:${NATIVE_INSTALLED_DIR}\\debug\\lib" _contents "${_contents}")`

**Comment by TheScarfix** [comment]
Will try this tomorrow, thank you

**Comment by Neumann-A** [comment]
@TheScarfix sent a pull request your way with all required fixes

**Pull request merged**
