### PR TITLE
Azure-IoT-Sdk for C release for 2021-08-18

### PR DESCRIPTION
**Pull request by momuno**
**Describe the pull request**

- #### What does your PR fix?  
  It updates references of our ports to reflect our new release done on 08-18-2021

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  All. Update unneeded.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by momuno** [comment]
Tests are failing with respsect to 'azure-kinect-sensor-sdk:x64-linux' and 'paraview:x64-osx'.
What are these and why do they relate to the C SDK?

**Comment by JonLiu1993** [comment]
> Tests are failing with respsect to 'azure-kinect-sensor-sdk:x64-linux' and 'paraview:x64-osx'.
> What are these and why do they relate to the C SDK?
> 
> Our last release update (#15109) did not appear to have this issue.

Due to the CI baseline error, the'paraview' is interrupted, just wait for the CI error to be fixed. Another error I cannot confirm whether it is related to CI for the time being, just wait for ci to be fixed and run again

**Comment by momuno** [comment]
> > Tests are failing with respsect to 'azure-kinect-sensor-sdk:x64-linux' and 'paraview:x64-osx'.
> > What are these and why do they relate to the C SDK?
> > Our last release update (#15109) did not appear to have this issue.
> 
> Due to the CI baseline error, the'paraview' is interrupted, just wait for the CI error to be fixed. Another error I cannot confirm whether it is related to CI for the time being, just wait for ci to be fixed and run again

Thank you @JonLiu1993 .  When do you expect the CI baseline error to be fixed?  I will wait until then before running again.

**Comment by ras0219-msft** [comment]
https://github.com/microsoft/vcpkg/pull/19633 which was just merged should have fixed this.

**Comment by JonLiu1993** [comment]
@momuno ,There is the 'azure-kinect-sensor-sdk:x64-linux' log,Could you please take a look?
https://dev.azure.com/vcpkg/public/_build/results?buildId=58045&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by momuno** [comment]
@Jon Liu1993. It appears that azure-kinect-sensor-sdk:x64-linux build is failing.  Accoridng to "x64-liux: Test Modify Ports and Prepare Test Logs".   But azure-kinect-sensor-sdk:x64-linux ***should not*** be getting built in the first place -- I did not change this port, nor does the C SDK have a dependency on it.

**Comment by momuno** [comment]
@dg0yt thanks for that info.  This section of C-shared-utility CMakeLists.txt has existed for 4 years -- trying pkgconfig before cmake for curl.  So this approach is not new and it has never been an issue before.  Do you know why it would be an issue now?  It looks like the tests have changed (?) -- or at least what they are named -- since our last PR was merged December 9, 2020 (https://github.com/microsoft/vcpkg/pull/19644#issuecomment-906944509)

**Comment by dg0yt** [comment]
> @dg0yt thanks for that info.  This section of C-shared-utility CMakeLists.txt has existed for 4 years -- trying pkgconfig before cmake for curl.  So this approach is not new and it has never been an issue before.

I think that it always had the hidden issue of using system libcurl.pc files when this dev package was installed. If they don't contain absolute paths, linking could use a dangerous mix of vcpkg and system libraries. It may somehow work, at least on similar systems. But now this card house collapsed.

> Do you know why it would be an issue now?  It looks like the tests have changed (?) -- or at least what they are named -- since our last PR was merged December 9, 2020 (https://github.com/microsoft/vcpkg/pull/15109)

There have been many updates: CI images, maintainer functions, port curl, curl's dependencies.

**Comment by momuno** [comment]
Closed for #19809

**Pull request closed without merging**
