### PR TITLE
[vcpkg] Add new community triplet arm64ec

### PR DESCRIPTION
**Pull request by dan-shaw**
Additional flags need to be set so that arm64ec can work

### CODE REVIEW

**Review by kobykahane — APPROVED** [review]

**Comment by vicroms** [comment]
`zeroc-ice:x64-windows-static-md` has been added to baseline failures, please merge with master and rerun CI.

**Review by dg0yt — COMMENTED** [review]
Did this PR forget to add setting `CMAKE_SYSTEM_PROCESSOR`? 
Lines 7-15 don't handle `VCPKG_TARGET_ARCHITECTURE` arm64ec.

**Comment by BillyONeal** [comment]
> Did this PR forget to add setting `CMAKE_SYSTEM_PROCESSOR`? Lines 7-15 don't handle `VCPKG_TARGET_ARCHITECTURE` arm64ec.

arm64ec isn't supposed to change that, to my understanding. It's ... weird.

**Comment by edgchen1** [comment]
> > Did this PR forget to add setting `CMAKE_SYSTEM_PROCESSOR`? Lines 7-15 don't handle `VCPKG_TARGET_ARCHITECTURE` arm64ec.
> 
> arm64ec isn't supposed to change that, to my understanding. It's ... weird.

Apologies for restarting this old thread, but I'm also wondering about this.

Is it correct for `CMAKE_SYSTEM_PROCESSOR` to not be set at all?

Some libraries expect it to be set. For example, cpuinfo.

https://github.com/pytorch/cpuinfo/blob/8a9210069b5a37dd89ed118a783945502a30a4ae/CMakeLists.txt#L91-L96

**Pull request merged**
