### PR TITLE
[vcpkg_build_qmake]Switch qmake build system to nmake in Windows.

### PR DESCRIPTION
**Pull request by JackBoosY**
Building system jom is very inefficient, try to switch to nmake.

Related: #4692.

### CODE REVIEW

**Comment by TheScarfix** [comment]
install_qt.cmake in qt5-base still uses jom

**Comment by Neumann-A** [comment]
also we should pass some parallel build argumenet because else building qt takes forever.

**Comment by heydojo** [comment]
> Building system jom is very inefficient, try to switch to nmake.

Could you elaborate please?

https://wiki.qt.io/Jom

> jom is a clone of nmake to support the execution of multiple independent commands in parallel.

As far as others are aware jom _is_ the tool you use to build Qt.

**Comment by JackBoosY** [comment]
@heydojo  Take it easy, it's just a draft. If using nmake takes longer than jom, I will turn off this PR.

**Comment by Voskrese** [comment]
@Neumann-A  flag `/mp` parallel build
nmake can't parallelize, but the compiler itself is doing a good job

**Comment by ras0219-msft** [comment]
From the issue:

>I have one PC (out of 3) where Jom consistently deadlocks (4 Jom process running without any progress for hours) within bigger builds of qt (e.g. qt5-base)

So the issue is not inefficiency (nmake will definitely be less efficient), but it appears there is a correctness issue in Jom on certain machines.

**Comment by Voskrese** [comment]
why closed?
code that works with the /MP flag

```
    if(CMAKE_HOST_WIN32)
        #vcpkg_find_acquire_program(JOM)
		find_program(NMAKE nmake)
        set(ENV{CL} /MP)
        set(INVOKE "nmake")
    else()
        find_program(MAKE make)
        set(INVOKE "${MAKE}")
    endif()
```

**Comment by JackBoosY** [comment]
@Voskrese 
1. After testing, the time to use nmake is greater than the time to use jom.
2. According to @ras0219-msft said, we need to solve the jam problem of jom instead of replacing it with nmake.

**Comment by Neumann-A** [comment]
@Jackboosy.
maybe a solution like the `PREFER_NINJA` solution in the CMake generator selection?
Let the user set e.g. `VCPKG_AVOID_JOM` in a triplet to force nmake instead of JOM

**Comment by Voskrese** [comment]
@JackBoosY 
from JOM the known problem for a long time, at multithreading, it begins to compile the new file, without having compiled dependence, and as a result there is a conflict, dependence is not present, and compilation went, an error

**Pull request closed without merging**
