### PR TITLE
Add a modernized cross-platform fork of MiniSat 2.2

### PR DESCRIPTION
**Pull request by horenmar**
This passed `vcpkg build minisat` locally, so hopefully there are no dumb mistakes.

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thank you very much for the PR!

I'm concerned about using the `minisat` name, due to how many other systems use that to refer to MiniSat 2.2[1]. Given how everyone else refers to the old source, it is reasonable for a migrating user to expect the same under the same name.

Therefore, I'd be much more comfortable with accepting this package under another name. A totally non-exhaustive list of suggestions:
- `master-keyring-minisat`
- `minisat-master-keyring`
- `minisat-keyring`
- `microsat`/`nanosat`/`tinysat`/`femptosat`/ etc :)
- `minisat-horenmar`
- `horenmar-minisat`

I _might_ be persuaded by `minisat3`, but I'd prefer not.

[1] https://repology.org/metapackage/minisat/versions

**Comment by horenmar** [comment]
> I might be persuaded by `minisat3`, but I'd prefer not.

God no. I already don't like the BSD ports providing version 2.2.1 (it never existed), so let's not go inventing new major version whole cloth.

**Comment by horenmar** [comment]
I changed the port name, but I think the port's folder should remain called `minisat`.

**Comment by ras0219-msft** [comment]
Thanks for the rename!

**Pull request merged**
