### PR TITLE
[sqlite3] Update to 3.34.1

### PR DESCRIPTION
**Pull request by past-due**
Update `sqlite3` port to 3.34.1: https://sqlite.org/releaselog/3_34_1.html

### CODE REVIEW

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
Hi @past-due 

Thanks for your PR.

LGTM. Have you tested these features in this PR?

**Comment by NancyLi1013** [comment]
All features have passed with the following triplets:

- x86-windows
- x64-windows-static

**Review by ras0219-msft — APPROVED** [review]

**Comment by ras0219-msft** [comment]
LGTM, thanks for the PR!

**Comment by NancyLi1013** [comment]
```
1>D:\buildtrees\3fd\x64-windows-rel\c67c0b275c-accfc8aba3.clean\3FD\broker.h(11,10): fatal error C1083: Cannot open include file: 'Poco/Data/Session.h': No such file or directory (compiling source file broker_impl_writer.cpp) [D:\buildtrees\3fd\x64-windows-rel\c67c0b275c-accfc8aba3.clean\3FD\3FD.vcxproj]
     1>D:\buildtrees\3fd\x64-windows-rel\c67c0b275c-accfc8aba3.clean\3FD\broker.h(11,10): fatal error C1083: Cannot open include file: 'Poco/Data/Session.h': No such file or directory (compiling source file broker_impl_reader.cpp) [D:\buildtrees\3fd\x64-windows-rel\c67c0b275c-accfc8aba3.clean\3FD\3FD.vcxproj]
     1>D:\buildtrees\3fd\x64-windows-rel\c67c0b275c-accfc8aba3.clean\3FD\broker.h(11,10): fatal error C1083: Cannot open include file: 'Poco/Data/Session.h': No such file or directory (compiling source file broker_impl.cpp) [D:\buildtrees\3fd\x64-windows-rel\c67c0b275c-accfc8aba3.clean\3FD\3FD.vcxproj]
         isam_impl_database.cpp
         isam_impl_databaseconn.cpp
         isam_impl_errorhelper.cpp
     1>D:\buildtrees\3fd\x64-windows-rel\c67c0b275c-accfc8aba3.clean\3FD\logger.h(10,14): fatal error C1083: Cannot open include file: 'Poco/Logger.h': No such file or directory (compiling source file callstacktracer.cpp) [D:\buildtrees\3fd\x64-windows-rel\c67c0b275c-accfc8aba3.clean\3FD\3FD.vcxproj]
     1>D:\buildtrees\3fd\x64-windows-rel\c67c0b275c-accfc8aba3.clean\3FD\cmdline.h(6,10): fatal error C1083: Cannot open include file: 'boost/regex.hpp': No such file or directory (compiling source file cmdline.cpp) [D:\buildtrees\3fd\x64-windows-rel\c67c0b275c-accfc8aba3.clean\3FD\3FD.vcxproj]
         isam_impl_instance.cpp
         isam_impl_recordreader.cpp
     1>D:\buildtrees\3fd\x64-windows-rel\c67c0b275c-accfc8aba3.clean\3FD\xml.h(6,10): fatal error C1083: Cannot open include file: 'rapidxml/rapidxml.hpp': No such file or directory (compiling source file configuration.cpp) [D:\buildtrees\3fd\x64-windows-rel\c67c0b275c-accfc8aba3.clean\3FD\3FD.vcxproj]
         isam_impl_session.cpp
```

**Comment by NancyLi1013** [comment]
After rerun, all CI checks have passed now.

**Pull request merged**
