### PR TITLE
[directx-dxc, directx-headers] Update for March 2024 release

### PR DESCRIPTION
**Pull request by walbourn**
Updates the DXC complier and DirectX 12 Headers for the *DirectX 12 Agility SDK* release for GDC 2024.

### CODE REVIEW

**Comment by walbourn** [comment]
Verified locally all supported triplets

```
.\vcpkg install directx-dxc:x64-windows
.\vcpkg install directx-dxc:x64-windows-static-md

.\vcpkg install directx-dxc:arm64-windows
.\vcpkg install directx-dxc:arm64-windows-static-md

.\vcpkg install directx-dxc:x64-mingw-static

./vcpkg install directx-dxc:x64-linux
```

```
.\vcpkg install directx-headers:x86-windows
.\vcpkg install directx-headers:x86-windows-static
.\vcpkg install directx-headers:x86-windows-static-md

.\vcpkg install directx-headers:x64-windows
.\vcpkg install directx-headers:x64-windows-static
.\vcpkg install directx-headers:x64-windows-static-md

.\vcpkg install directx-headers:arm64-windows
.\vcpkg install directx-headers:arm64-windows-static
.\vcpkg install directx-headers:arm64-windows-static-md

.\vcpkg install directx-headers:x86-uwp
.\vcpkg install directx-headers:x64-uwp
.\vcpkg install directx-headers:arm64-uwp

.\vcpkg install directx-headers:x64-mingw-static
.\vcpkg install directx-headers:x86-mingw-static

./vcpkg install directx-headers:x64-linux
```

ARM (32b-bit) is deprecated, but still builds:

```
.\vcpkg install directx-headers:arm-windows
.\vcpkg install directx-headers:arm-uwp
```

And built dependent projects **directxtex**, **directxtk12**, **directxmesh**, **uvatlas**.

**Review by jenatali — APPROVED** [review]

**Comment by MonicaLiu0311** [comment]
The usage test passed on `x64-windows` (header files found):
```
The DirectX Shader Compiler package provides CMake targets:

    find_package(directx-dxc CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Microsoft::DirectXShaderCompiler)

The CMake variable DIRECTX_DXC_TOOL is also set to point to the appropriate DXC command-line tool.
```

**Review by MonicaLiu0311 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks!

**Comment by AraHaan** [comment]
Does the directxheaders vcpkg also ship headers to D3D9, D3D10, and D3D11 by chance as well?

**Comment by jenatali** [comment]
You don't need the legacy DirectX SDK for those headers, they are part of the Windows SDK. They are not part of DirectX-Headers, that only contains D3D12/DXCore/DML headers at this time.

**Comment by walbourn** [comment]
> Does the directx-headers vcpkg also ship headers to D3D9, D3D10, and D3D11 by chance as well so that way one does not need to install the legacy DirectX SDK in order to get them? I also wish that the Windows SDK could be migrated to VCPKG as well so then projects that depends on a specific version could use that as well (also so then Visual Studio would start forcing it's install though VCPKG and not directly so then projects if they desire can upgrade it project wide at a per project basis)

For Direct3D 9, Direct3D 10, and Direct3D 11 you can count on them being present in all versions of the Windows SDK for as far back as you care to look.  They are at this point absolutely 'platform headers' just like all the other Win32 headers, and they aren't changing really at all. As such, you can generally assume ``d3d11_1.h`` or earlier exists in all Windows build environments already even the wierdo one that ships with MinGW. For Visual Studio and Windows SDK scenarios, you can count on ``FXC.EXE`` being present, but it's not there in MinGW--you have to have to install the standalone Windows SDK in that case. See [this blog post](https://walbourn.github.io/directx-sdks-of-a-certain-age/) for details of exactly when these headers started showing up.

For legacy D3DX9, D3DX10, D3DX11 you should ideally not use them at all. If you do need them, the **dxsdk-d3dx** port pulls in the *Microsoft.DXSDK.D3DX* NuGet package. The DLLs here are identical functionally to June 2010, but have been SHA256 signed and have a 'side-by-side' redist license so you do NOT need to use legacy DirectSetup at all. See [this blog post](https://walbourn.github.io/legacy-d3dx-on-nuget/).

The reason there is a **directx-headers** port in the first place is because:

* DirectX 12 is getting regular functionality updates through Windows releases and the [DirectX 12 Agility SDK](https://aka.ms/directx12agility).
* DirectX 12 is also supported on Windows Subsystem for Linux (WSL) where you can't use the Windows SDK to build.
* DirectX12 headers are available on [GitHub](https://github.com/microsoft/DirectX-Headers) under the MIT license.

None of those are true for DirectX 11 or earlier.

**Pull request merged**
