### PR TITLE
[icu] fix mac os x64 build on apple arm

### LINKED ISSUE #16424: [qt-base] build failure (icu is build for arm with x64-osx triplet)
**Host Environment**
- OS: macOS 11
- Compiler: Apple clang version 12.0.0 (clang-1200.0.32.29) Target: arm64-apple-darwin20.3.0

**To Reproduce**
`./vcpkg install qt-base`

**Failure logs** 
```
Starting package 26/26: qt5-base:x64-osx
Building package qt5-base[core]:x64-osx...
-- Figuring out qt target mkspec. Target arch x64
-- Target mkspec set to: macx-clang
-- Host mkspec not set. Qt's own buildsystem will try to figure out the host system
-- Downloading http://download.qt.io/official_releases/qt/5.15/5.15.2/submodules/qtbase-everywhere-src-5.15.2.tar.xz -> qtbase-everywhere-src-5.15.2.tar.xz...
-- Extracting source /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/downloads/qtbase-everywhere-src-5.15.2.tar.xz
-- Applying patch patches/winmain_pro.patch
-- Applying patch patches/windows_prf.patch
-- Applying patch patches/qt_app.patch
-- Applying patch patches/gui_configure.patch
-- Applying patch patches/icu.patch
-- Applying patch patches/xlib.patch
-- Applying patch patches/egl.patch
-- Applying patch patches/zstdd.patch
-- Applying patch patches/mysql_plugin_include.patch
-- Applying patch patches/mysql-configure.patch
-- Applying patch patches/Qt5BasicConfig.patch
-- Applying patch patches/Qt5PluginTarget.patch
-- Applying patch patches/create_cmake.patch
-- Applying patch patches/Qt5GuiConfigExtras.patch
-- Using source at /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/qt5-base/src/5.15.2-70178539f6.clean
objc[21913]: Class AMSupportURLConnectionDelegate is implemented in both ?? (0x1f2474188) and ?? (0x1161ac2b8). One of the two will be used. Which one is undefined.
objc[21913]: Class AMSupportURLSession is implemented in both ?? (0x1f24741d8) and ?? (0x1161ac308). One of the two will be used. Which one is undefined.
2021-02-26 00:28:35.855 xcodebuild[21913:10168219] [MT] PluginLoading: Required plug-in compatibility UUID 2F1A5FFF-BFEB-4498-B2AC-1296A7454F81 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/VVDocumenter-Xcode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2021-02-26 00:28:35.855 xcodebuild[21913:10168219] [MT] PluginLoading: Required plug-in compatibility UUID 2F1A5FFF-BFEB-4498-B2AC-1296A7454F81 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ClangFormat.xcplugin' not present in DVTPlugInCompatibilityUUIDs
-- Detected OSX SDK Version: 11.1
-- Major.Minor OSX SDK Version: 11.1
-- Qt 5.15.2 only support OSX_DEPLOYMENT_TARGET up to 10.15
-- Enviromnent OSX SDK Version: 10.15
-- Configuring x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/qt5-base/src/5.15.2-70178539f6.clean/configure -confirm-license -opensource -verbose -system-zlib -system-libjpeg -system-libpng -system-freetype -system-pcre -system-doubleconversion -system-sqlite -system-harfbuzz -sql-psql -icu -no-angle -openssl-linked -fontconfig -nomake examples -nomake tests -static LIBJPEG_LIBS=/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libjpeg.a ZLIB_LIBS=/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libz.a "LIBPNG_LIBS=/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libpng16d.a /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libz.a" PCRE2_LIBS=/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libpcre2-16.a "FREETYPE_LIBS=/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libfreetyped.a /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libbz2d.a /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libpng16d.a /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libz.a /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libbrotlidec-static.a /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libbrotlicommon-static.a" "ICU_LIBS=/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libicui18n.a /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libicutu.a  /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libicuuc.a /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libicuio.a /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libicudata.a" QMAKE_LIBS_PRIVATE+=/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libbz2d.a QMAKE_LIBS_PRIVATE+=/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libpng16d.a "QMAKE_LIBS_PRIVATE+=/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libicui18n.a /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libicutu.a  /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libicuuc.a /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libicuio.a /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libicudata.a" QMAKE_LIBS_PRIVATE+=/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libzstdd.a "PSQL_LIBS=/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libpq.a /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libpgport.a  /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libpgcommon.a /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libssl.a /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libcrypto.a -ldl -lpthread" "SQLITE_LIBS=/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libsqlite3.a -ldl -lpthread" "HARFBUZZ_LIBS=/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libharfbuzz.a /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libfreetyped.a /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libbz2d.a /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libpng16d.a /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libz.a /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libbrotlidec-static.a /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libbrotlicommon-static.a -framework ApplicationServices" "OPENSSL_LIBS=/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libssl.a /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libcrypto.a -ldl -lpthread" "FONTCONFIG_LIBS=/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libfontconfig.a /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libfreetyped.a /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libexpat.a -liconv" -debug -prefix /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx -hostprefix /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/tools/qt5/debug -hostlibdir /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/tools/qt5/debug/lib -hostbindir /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/tools/qt5/debug/bin -archdatadir /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/tools/qt5/debug -datadir /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/share/qt5/debug -plugindir /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/plugins -qmldir /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/qml -headerdir /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/include -libexecdir /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/tools/qt5/debug -bindir /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/bin -libdir /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib -I /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/include -L /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib -L /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/manual-link -platform macx-clang
    Working Directory: /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/qt5-base/x64-osx-dbg
    Error code: 3
    See logs for more information:
      /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/qt5-base/config-x64-osx-dbg-out.log
      /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/qt5-base/config-x64-osx-dbg-err.log

Call Stack (most recent call first):
  ports/qt5-base/cmake/configure_qt.cmake:126 (vcpkg_execute_required_process)
  ports/qt5-base/portfile.cmake:341 (configure_qt)
  scripts/ports.cmake:133 (include)


Error: Building package qt5-base:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: qt5-base:x64-osx
  Vcpkg version: 2021-01-13-unknownhash

Additionally, attach any relevant sections from the log files above.
```
[config-x64-osx-dbg-err.log](https://github.com/microsoft/vcpkg/files/6046347/config-x64-osx-dbg-err.log)

relevant pieces:
```
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -stdlib=libc++ -headerpad_max_install_names  -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -mmacosx-version-min=10.15 -Wl,-rpath,@executable_path/../Frameworks -o verifyspec verifyspec.o   -L/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib -L/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/manual-link   /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libbz2d.a /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libpng16d.a /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libicui18n.a /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libicutu.a /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libicuuc.a /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libicuio.a /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libicudata.a /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libzstdd.a
> ld: warning: directory not found for option '-L/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/manual-link'
> ld: warning: ignoring file /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libicui18n.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
> ld: warning: ignoring file /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libicuio.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
> ld: warning: ignoring file /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libicudata.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
> ld: warning: ignoring file /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libicutu.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
> ld: warning: ignoring file /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libicuuc.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
```
```
ERROR: Feature 'icu' was enabled, but the pre-condition 'libs.icu' failed.
```

So the real error seems to be that icu is build for arm64 while I am using the `x64-osx` triplet

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

### PR DESCRIPTION
**Pull request by autoantwort**
**Describe the pull request**

- What does your PR fix? Fixes  #16424

That was the only successful way to generate x64 binaries on an arm mac. I tried many different approaches but that one was the only successful one. See [here](https://unicode-org.atlassian.net/browse/ICU-21354).

### CODE REVIEW

**Comment by autoantwort** [comment]
I could image that another solution is to cross build from arm to x64 on mac, but than you need icu installed for the host triplet, so that solution is only possible when #15424 gets merged.

**Comment by autoantwort** [comment]
Can you rerun the pipeline? The mac machine was offline.

**Review by JackBoosY — APPROVED** [review]

**Review by ras0219-msft — COMMENTED** [review]
Let me know what path you'd like to take with this PR.

**Comment by autoantwort** [comment]
> Let me know what path you'd like to take with this PR.

I think the host triplet way is a better one. It will also make cross compiling from linux -> windows possible and other cross compiling scenarios. The only downside to my understanding is that you build the port twice if you are using for example the triplet `x86-windows` (`x86-windows` + `x64-windows`)

**Comment by autoantwort** [comment]
Ok currently #16504 prevents a solution with host triplets on macs.

**Comment by JackBoosY** [comment]
@autoantwort It looks like we have to fix issue #16504 first.

**Comment by ras0219-msft** [comment]
From https://github.com/microsoft/vcpkg/issues/16504#issuecomment-796029985:

>As a workaround, you can set VCPKG_HOST_TRIPLET as an environment variable or pass --host-triplet= on the command line to change which triplet to use as the host.

**Comment by autoantwort** [comment]
> We can avoid building the "tools" part in the cross-compiled port

Some of the tools are needed to cross compile and I don't know if you can only build the tools needed for cross compiling. 

I think this can be closed in favour of #16577

**Pull request closed without merging**
