### PR TITLE
Update vcpkg-tool to 2022-11-10.

### PR DESCRIPTION
**Pull request by BillyONeal**

### CODE REVIEW

**Comment by BillyONeal** [comment]
Fixes https://github.com/microsoft/vcpkg/issues/26651 .

**Comment by BillyONeal** [comment]
Merge with: https://github.com/microsoft/vcpkg/pull/27172

**Comment by walbourn** [comment]
https://github.com/microsoft/vcpkg-tool/releases/tag/2022-11-10

**Comment by BillyONeal** [comment]
@walbourn  that one failed release smoke testing so we've been working on a replacement

**Pull request merged**
