### PR TITLE
Disable libhdfs3 and osg-qt in linux temporarily

### PR DESCRIPTION
**Pull request by JackBoosY**
In recent PRs, I found the following regressions in linux:
- libhdfs3:
```
CMake Error at /home/work/vcpkg/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find KERBEROS (missing: KERBEROS_LIBRARIES KERBEROS_INCLUDE_DIR)
```

- osg-qt: Since `ms-angle` conflicts with `angle` and `qt-5base`, `libegl` build fails, which leads to this regression.

I will fix them in another PR later.

Related: #10285 #10167 #10253 #10287.

### CODE REVIEW

**Review by PhoebeHui — APPROVED** [review]

**Comment by strega-nil** [comment]
Thanks Jack!

**Comment by kreuzerkrieg** [comment]
@JackBoosY , any ETA when `libhdfs3` is going to make it back?

**Comment by JackBoosY** [comment]
@kreuzerkrieg Less than one week.

**Comment by JackBoosY** [comment]
Since vcpkg does not currently join port `Kerberos`, we need to remind users to install it with other package managers and fix the issue of finding it.

**Comment by kreuzerkrieg** [comment]
so, what is the current status of `libhdfs3`?

**Comment by strega-nil** [comment]
@kreuzerkrieg I'm not sure; it looks like an unsupported library?

**Comment by strega-nil** [comment]
@JackBoosY I don't think kerberos is generally available in package managers; I think we have to add `krb5` as a port to vcpkg (http://web.mit.edu/kerberos/)

**Comment by PhoebeHui** [comment]
@kreuzerkrieg, it looks you are the author of the libhdfs3 port in vcpkg, do you know if kerberos required to build libhdfs3, if there is a way to disable it? it built failed on linux when configure the project. Could you give us some suggestion?

BTW, I'm curious about PR https://github.com/microsoft/vcpkg/pull/10021, why the ci test pass on linux? the port haven't been changed after it added, so it should detact the failure before, however the CI test pass, and we merged the changes, it cause failrues in CI baseline .

Failures:
CMake Error at /home/phoebe/vcpkg/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find KERBEROS (missing: KERBEROS_LIBRARIES KERBEROS_INCLUDE_DIR)
Call Stack (most recent call first):
  /home/phoebe/vcpkg/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  CMake/FindKERBEROS.cmake:21 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /home/phoebe/vcpkg/scripts/buildsystems/vcpkg.cmake:288 (_find_package)
  CMakeLists.txt:20 (FIND_PACKAGE)

**Comment by kreuzerkrieg** [comment]
@PhoebeHui First, I have no idea. Second I can try and ask folks from libhdfs. And third, I guess the answer is no, it makes perfect sense - want authentication? go for gsasl, using sasl? you need kerberos.

As of making ports, gsasl and kerberos last releases were issued a century before I've born, not sure anyone needs this port, honestly I dont see any reason for making port for a package that may be provided by native package management.

**Comment by strega-nil** [comment]
@kreuzerkrieg unfortunately, afaict, Ubuntu doesn't have kerberos :/

**Comment by kreuzerkrieg** [comment]
krb5 AFAIR

**Comment by PhoebeHui** [comment]
Thank you all for taking look at this issue!

**Pull request merged**
