### PR TITLE
Build Boost with ICU and Python

### PR DESCRIPTION
**Pull request by muemart**
With this PR, Boost uses ICU for regex and locale, and also builds the Python library (all on desktop only). I had to rip out the ICU library detection from the build scripts because they always forced dynamic linking. The ICU libraries are now defined in the user-config, which is configured by the portfile to set the correct CRT linkage.

### CODE REVIEW

**Comment by codicodi** [comment]
Not sure what went wrong, but looks like debug Boost.Python links to release python library.
```
> dumpbin /dependents .\packages\boost_x64-windows\debug\bin\boost_python3-vc141-mt-gd-1_64.dll
Microsoft (R) COFF/PE Dumper Version 14.10.25019.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file .\packages\boost_x64-windows\debug\bin\boost_python3-vc141-mt-gd-1_64.dll

File Type: DLL

  Image has the following dependencies:

    python36.dll
    MSVCP140D.dll
    KERNEL32.dll
    VCRUNTIME140D.dll
    ucrtbased.dll

  Summary

        3000 .data
        D000 .pdata
       30000 .rdata
        1000 .reloc
        1000 .rsrc
       5E000 .text
        1000 .tls
```

**Comment by muemart** [comment]
Oops, should have checked that. Should be OK now.

**Comment by jasjuang** [comment]
Is this ready to merge? I like the boost python addition

**Comment by muemart** [comment]
Yes, this should be ready to merge. Maybe they're waiting for feature packages to be a thing first? It *does* add ICU and Python as dependencies, which might be a little big.

**Comment by jasjuang** [comment]
@muemart There is a merge conflict because of the boost 1.65 update. Could you resolve it? Hope this will get merged soon. @ras0219-msft @alexkaratarakis

**Comment by muemart** [comment]
Conflicts fixed.

**Comment by ras0219-msft** [comment]
Thank you very much for the PR and sorry for how long it's taken to merge!

I've moved the two dependency additions into feature packages:
```
>vcpkg search boost --featurepackages
beast                v84-1            HTTP/1 and WebSocket, header-only using Boost.Asio and C++11
boost                1.65.1-1         Peer-reviewed portable C++ source libraries
boost[locale-icu]                     ICU backend for Boost.Locale
boost[regex-icu]                      ICU support for Boost.Regex
boost[python]                         a C++ library which enables seamless interoperability between C++ and the Pyth...
boost-di             1.0.1            C++14 Dependency Injection Library.
spirit-po            1.1.2            A header-only C++ library for localization using GNU gettext po files, based o...
```
These can be installed with
```
>vcpkg install boost[locale-icu,regex-icu,python] --featurepackages
```

**Comment by jasjuang** [comment]
This is awesome!

**Pull request merged**
