### PR TITLE
[arrow]Fix build error on Visual Studio 2019.

### PR DESCRIPTION
**Pull request by JackBoosY**
Related: #6497.

Thanks @treigilbert.

### CODE REVIEW

**Comment by grdowns** [comment]
Thanks for the fix, @JackBoosY!

**Comment by wesm** [comment]
Does this need to be fixed upstream in Apache Arrow?

**Comment by JackBoosY** [comment]
@wesm Yes, but I don't have an account.

**Comment by wesm** [comment]
Anyone can contribute to this project, see

https://github.com/apache/arrow/blob/master/.github/CONTRIBUTING.md

**Comment by wesm** [comment]
@kszucs are we testing VS2019 in GitHub Actions now? Do you know whether the problem here has been fixed?

**Comment by kszucs** [comment]
@wesm We do test VS2019, see [build log](https://github.com/apache/arrow/runs/375950915#step:4:404) and the build machine's [spec](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners#visual-studio-2019-enterprise).

But, both patches look valid because:
- ARROW_PARQUET is not enabled in the C++ VS2019 build (created https://issues.apache.org/jira/browse/ARROW-7524)
- we don't have a VS2019 build for pyarrow (created https://issues.apache.org/jira/browse/ARROW-7525)

**Pull request merged**
