### PR TITLE
[imgui] update to 1.84.2

### PR DESCRIPTION
**Pull request by mathisloge**
**Describe the pull request**

- #### What does your PR fix?  
update imgui to 1.84.2

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
 y
- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
y

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
y

### CODE REVIEW

**Comment by RT222** [comment]
The docking-experimental feature will build but projects depending on it won't, because you used a commit from the master branch where the docking feature doesn't exist. They did not merge the master to the docking branch for the 1.84.2, so the only way to get it would be from [this merge commit](https://github.com/ocornut/imgui/commit/dedb381c510cc0b87164e16b9e7ef6bf50ffccec), which would also bring some wip changes from the 1.85, which is not desirable.

**Comment by mathisloge** [comment]
Thanks for the hint. Thought I used the correct one. Will fix later today

**Comment by mathisloge** [comment]
>(https://github.com/ocornut/imgui/commit/dedb381c510cc0b87164e16b9e7ef6bf50ffccec) happened after the 1.84.2

I would use this commit. 

> and using it would also bring some changes from the 1.85 wip which is not desirable. 

In my opinion it is not desirable to not update a port because a _experimental_ feature is some steps ahead. Have build a example application with docking and it works and build. 

So IMHO the focus should be the stable release version and not the docking branch. I know that a lot of people using it, but if you experience some malfunctioning inside the experimental-docking feature, you could also pinpoint the version to 1.84.1. 
The regression fix in 1.84.2 is important.

**Comment by RT222** [comment]
I actually agree that it is better to update it in this case, but I would like to clarify that the docking branch is not experimental, it is in beta, which I think is very different. I don't know with the port feature it was named like this and it is an error in my opinion.

From the Imgui changelog :
> The docking (#2109) and multi-viewports (#1542) features are available in the docking branch, they are in beta but actively maintained and being used by many teams already. Your continuous feedback is always appreciated.

**Comment by mathisloge** [comment]
@RT222 yeah. agree with thats beta. I think the wording _experimental_ is indeed a bit ambiguous and open to interpretation. But in the end we have to agree to some policy that the docking is not the offical release. Therefore it should be the version guidance. However there are then two possible ways to handle docking if the commit is newer or older than the release version. 
1. Use the latest minor version since merge 
2. Use the last merge after release

In my opinion the second point is the way to go. (If there aren't to many differences between release and latest merge)

**Comment by JonLiu1993** [comment]
@mathisloge , This pr is ready for review?

**Comment by mathisloge** [comment]
From my point of view - yes

**Comment by JonLiu1993** [comment]
Have you tested the feature locally?

**Review by JonLiu1993 — APPROVED** [review]

**Comment by mathisloge** [comment]
> Have you tested the feature locally?

docking-experimental with sdl2 and opengl

**Pull request merged**
