### PR TITLE
[kealib] Update, revise features

### PR DESCRIPTION
**Pull request by dg0yt**
- #### What does your PR fix?  
  - [x] Update kealib to latest release (1.4.14)
  - [x] Revise and modernize
  - ~Add gdal (driver) feature.~
    (Dropped from this PR. See https://github.com/microsoft/vcpkg/pull/19118#issuecomment-914053385.)

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all, no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  yes

### CODE REVIEW

**Review by ras0219-msft — APPROVED** [review]

**Comment by JonLiu1993** [comment]
@dg0yt ,I failed to test the feature "gdal" locally. Is it related to the pr #19120 you linked?

**Comment by dg0yt** [comment]
@JonLiu1993 #19120 and #19119.

**Comment by dg0yt** [comment]
@JonLiu1993 #19120 and #19119 were merged to master, and I merged master back here. You can now test feature "gdal". Builds for me on x64-linux.

**Comment by JonLiu1993** [comment]
@dg0yt, I tested the feature "gdal" on x86-windows and x64-windows, and they all failed. There is error log:
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/7113623/install-x86-windows-dbg-out.log)

**Comment by dg0yt** [comment]
~~~
keadataset.cpp.obj : error LNK2019: unresolved external symbol "public: __thiscall CPLMutexHolder::CPLMutexHolder(void * *,double,char const *,int,int)" (??0CPLMutexHolder@@QAE@PAPAXNPBDHH@Z) referenced in function __catch$??0KEADataset@@QAE@PAVH5File@H5@@W4GDALAccess@@@Z$0
keaband.cpp.obj : error LNK2001: unresolved external symbol "public: __thiscall CPLMutexHolder::CPLMutexHolder(void * *,double,char const *,int,int)" (??0CPLMutexHolder@@QAE@PAPAXNPBDHH@Z)
keamaskband.cpp.obj : error LNK2001: unresolved external symbol "public: __thiscall CPLMutexHolder::CPLMutexHolder(void * *,double,char const *,int,int)" (??0CPLMutexHolder@@QAE@PAPAXNPBDHH@Z)
kearat.cpp.obj : error LNK2001: unresolved external symbol "public: __thiscall CPLMutexHolder::CPLMutexHolder(void * *,double,char const *,int,int)" (??0CPLMutexHolder@@QAE@PAPAXNPBDHH@Z)
gdal\gdal_KEA.dll : fatal error LNK1120: 1 unresolved externals
~~~
[CPLMutexHolder](https://gdal.org/doxygen/classCPLMutexHolder.html) is from gdal. I will investigate later. Perhaps I will make gdal a default feature temporarily for CI testing purposes.

**Comment by dg0yt** [comment]
I decided to drop the gdal plugin feature from this PR.
- I cannot verify that it actually works in any configuration.
- Windows seems to be unsupported by upstream (no exported symbols, insufficient install commands).

**Review by JonLiu1993 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for your help!

**Pull request merged**
