### PR TITLE
[cgal] Fix incorrect warning message

### LINKED ISSUE #23098: [cgal] Fix CGAL_DATA_DIR CMake warning
****

**Is your feature request related to a problem? Please describe.**
Using CGAL produces the CMake warning:

```
CMake Warning at vcpkg_installed/arm64-osx/share/cgal/CGALConfig.cmake:92 (message):
  CGAL_DATA_DIR cannot be deduced, set the variable CGAL_DATA_DIR to set the
  default value of CGAL::data_file_path()
Call Stack (most recent call first):
  /Users/adam/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:793 (_find_package)
  CMakeLists.txt:72 (find_package)
```

**Proposed solution**
Fix the port so that this works:

https://github.com/CGAL/cgal/blob/master/Installation/lib/cmake/CGAL/CGALConfig.cmake#L75

**Describe alternatives you've considered**
Setting this manually, however, that doesn't fit well within the vcpkg port philosophy heretofore, which is that installing a package should not usually require environment variables to be set.

**Additional context**
In CLion, this causes error messages in CMake builds
Screen Shot 2022-02-14 at 9 52 03 PM
.

### PR DESCRIPTION
**Pull request by JackBoosY**
The upstream uses a special cmake scripts to install _Data/data_:
https://github.com/CGAL/cgal/blob/master/Scripts/developer_scripts/cgal_create_release_with_cmake.cmake
https://github.com/CGAL/cgal/blob/master/Scripts/developer_scripts/create_new_release#L258

However, that isn't suitable for vcpkg.
After discussed with the upstream, use official patch https://github.com/CGAL/cgal/pull/6649 to fix this.

Fixes #23098.

### CODE REVIEW

**Comment by dg0yt** [comment]
This would still burn an absolute installation path into user binaries.

I think it needs to take a different direction.
- Don't install data for demos/examples/tests/benchmarks (unless required for a feature). This is vcpkg policy.
- Change the usage instruction to reflect the limited relevance, app.
  ~~~
  vcpkg doesn't define CGAL_DATA_DIR. If you need to use CGAL::data_file_path(),
  read the function's documentation for how to set the data path for
  your build or deployment environment.
  ~~~

**Comment by JackBoosY** [comment]
Since cgal's cmake buildsystem is too complex, @maxGimeno can you please help me to disable all the tests and examples in this PR?

**Comment by dg0yt** [comment]
> Since cgal's cmake buildsystem is too complex, @maxGimeno can you please help me to disable all the tests and examples in this PR?

@JackBoosY It is your new patch which installs the data.

**Comment by JackBoosY** [comment]
> @JackBoosY It is your new patch which installs the data.

Yep, I know that. However, cgal provides other options like `BUILD_TESTING`, `BUILD_DOC` and `CGAL_BUILD_THREE_DOC`.
And I found that the feature dependency `qt5` is for the test project, which we should disabled.

**Comment by JackBoosY** [comment]
@lrineau Also please help me in this PR. 

Thanks.

**Comment by lrineau** [comment]
> This PR cannot be the solution. You do not want to install CGAL examples files in the default installation of CGAL. I will find another way.
> 
> Upstream bug: [CGAL/cgal#6647](https://github.com/CGAL/cgal/issues/6647)

The solution, in my opinion, is the pull-request I have submitted upstream: CGAL/cgal#6649. Its patch is: https://patch-diff.githubusercontent.com/raw/CGAL/cgal/pull/6649.patch.

**Comment by JackBoosY** [comment]
@lrineau Thank you very much! I will make your changes as a patch and apply it in this PR after your PR merged.

**Comment by JackBoosY** [comment]
@lrineau So I just need to add a condition `CGAL_TEST_SUITE` ?

**Review by LilyWangLL — APPROVED** [review]

**Comment by citystrawman** [comment]
> > @lrineau So I just need to add a condition `CGAL_TEST_SUITE` ?
> 
> Right: that warning was supposed to be a warning for developers, and not for users. Users can still define `CGAL_DATA_DIR` manually if they have a .cpp file that uses the function [`CGAL::data_file_path`](https://doc.cgal.org/latest/Manual/namespaceCGAL.html#acdae9a147ad2a3998cc21f88bc292dac).

Hello, from this [link](https://doc.cgal.org/latest/Manual/namespaceCGAL.html#acdae9a147ad2a3998cc21f88bc292dac) it seems to me that, to use data_file_path(), just add `set(CGAL_DATA_DIR "D:/Programs/CGAL-5.6.1-examples/CGAL-5.6.1/data")` and `target_link_libraries(target PUBLIC CGAL::Data)` in CMakeLists.txt ? But I tried this and it doesn't work.

**Comment by lrineau** [comment]
@citystrawman If you set `CGAL_DIR` to `D:/Programs/CGAL-5.6.1-examples/CGAL-5.6.1` then `CGAL_DATA_DIR` will be set automatically to `D:/Programs/CGAL-5.6.1-examples/CGAL-5.6.1/data`.

Is `D:/Programs/CGAL-5.6.1-examples/CGAL-5.6.1` a full and virgin installation of CGAL-5.6.1?

**Comment by citystrawman** [comment]
> @citystrawman If you set `CGAL_DIR` to `D:/Programs/CGAL-5.6.1-examples/CGAL-5.6.1` then `CGAL_DATA_DIR` will be set automatically to `D:/Programs/CGAL-5.6.1-examples/CGAL-5.6.1/data`.
> 
> Is `D:/Programs/CGAL-5.6.1-examples/CGAL-5.6.1` a full and virgin installation of CGAL-5.6.1?

Thank you. I just managed to figure it out:  First you need to set` CGAL_DATA_DIR `at very beginning, right after the project declaration; then you need to write `target_link_libraries(target PRIVATE CGAL::CGAL CGAL::Data)`, it is case sensitive!!! after all these done, data_file_path() works fine.

**Pull request merged**
