### PR TITLE
[boost] Update to 1.71.0

### PR DESCRIPTION
**Pull request by ras0219-msft**

### CODE REVIEW

**Comment by ras0219-msft** [comment]
@qis I did need to patch openmvs to accommodate the new boost, but I included a few other improvements as well (assuming that's what you're referring to).

**Comment by qis** [comment]
Just didn't see the connection. P. S. Asio and Beast soon to work fine.

**Comment by qis** [comment]
@ras0219-msft Yay! Thank you very much!

Shouldn't https://github.com/microsoft/vcpkg/issues/7857 be closed?

**Pull request merged**
