### PR TITLE
[vcpkg] add out/ folder to .gitignore

### PR DESCRIPTION
**Pull request by sean0921**
**Describe the pull request**

After I use `vcpkg` to install some c++ depencdies, I want to check if `vcpkg` content is clean(sometimes I will modify package content for tweaking build), so I will use `git status` to check it.  But I've seen:
圖片

Is it appropriate to add `out/` auto-generated content to `.gitignore` list?  Thanks!

### CODE REVIEW

**Comment by cenit** [comment]
What is this out/ folder inside many port folder? Is there anything inside? I don’t see it on my machine

**Comment by sean0921** [comment]
They appeared after I use `.\vcpkg install cpprestsdk[default-features,websockets]` (In this case), I guess those packages are dependencies of it.

**Comment by cenit** [comment]
In case it’s possible to reproduce it on another machine, it’s a bug of the portfile of cpprestsdk

**Comment by BillyONeal** [comment]
Does not repro for me:

```
PS D:\vcpkg> git status
HEAD detached at origin/master
nothing to commit, working tree clean
PS D:\vcpkg> .\bootstrap-vcpkg.bat | Out-Null
PS D:\vcpkg> .\vcpkg.exe install cpprestsdk
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
Computing installation plan...
A suitable version of cmake was not found (required v3.17.2). Downloading portable cmake v3.17.2...
Downloading cmake...
  https://github.com/Kitware/CMake/releases/download/v3.17.2/cmake-3.17.2-win32-x86.zip -> D:\vcpkg\downloads\cmake-3.17.2-win32-x86.zip
Extracting cmake...
A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Downloading 7zip...
  https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> D:\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg
Extracting 7zip...
A suitable version of nuget was not found (required v4.8.1). Downloading portable nuget v4.8.1...
Downloading nuget...
  https://dist.nuget.org/win-x86-commandline/v4.8.1/nuget.exe -> D:\vcpkg\downloads\nuget.exe
The following packages will be built and installed:
  * brotli[core]:x86-windows
    cpprestsdk[brotli,compression,core,default-features]:x86-windows
  * zlib[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
A suitable version of powershell-core was not found (required v6.2.1). Downloading portable powershell-core v6.2.1...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v6.2.1/PowerShell-6.2.1-win-x86.zip -> D:\vcpkg\downloads\PowerShell-6.2.1-win-x86.zip
Extracting powershell-core...
Starting package 1/3: brotli:x86-windows
Building package brotli[core]:x86-windows...
-- Downloading https://github.com/google/brotli/archive/v1.0.7.tar.gz...
-- Extracting source D:/vcpkg/downloads/google-brotli-v1.0.7.tar.gz
-- Applying patch install.patch
-- Applying patch fix-arm-uwp.patch
-- Using source at D:/vcpkg/buildtrees/brotli/src/v1.0.7-bf01b84227
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: D:/vcpkg/packages/brotli_x86-windows/share/brotli/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package brotli[core]:x86-windows... done
Installing package brotli[core]:x86-windows...
Installing package brotli[core]:x86-windows... done
Elapsed time for package brotli:x86-windows: 9.325 s
Starting package 2/3: zlib:x86-windows
Building package zlib[core]:x86-windows...
-- Downloading http://www.zlib.net/zlib-1.2.11.tar.gz...
-- Extracting source D:/vcpkg/downloads/zlib1211.tar.gz
-- Applying patch cmake_dont_build_more_than_needed.patch
-- Using source at D:/vcpkg/buildtrees/zlib/src/1.2.11-deec42f53b
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: D:/vcpkg/packages/zlib_x86-windows/share/zlib/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package zlib[core]:x86-windows... done
Installing package zlib[core]:x86-windows...
Installing package zlib[core]:x86-windows... done
Elapsed time for package zlib:x86-windows: 3.186 s
Starting package 3/3: cpprestsdk:x86-windows
Building package cpprestsdk[brotli,compression,core,default-features]:x86-windows...
-- Downloading https://github.com/Microsoft/cpprestsdk/archive/v2.10.16.tar.gz...
-- Extracting source D:/vcpkg/downloads/Microsoft-cpprestsdk-v2.10.16.tar.gz
-- Using source at D:/vcpkg/buildtrees/cpprestsdk/src/v2.10.16-35b281201d
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: D:/vcpkg/packages/cpprestsdk_x86-windows/share/cpprestsdk/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package cpprestsdk[brotli,compression,core,default-features]:x86-windows... done
Installing package cpprestsdk[brotli,compression,core,default-features]:x86-windows...
Installing package cpprestsdk[brotli,compression,core,default-features]:x86-windows... done
Elapsed time for package cpprestsdk:x86-windows: 9.36 s

Total elapsed time: 31.95 s

The package cpprestsdk:x86-windows provides CMake targets:

    find_package(cpprestsdk CONFIG REQUIRED)
    target_link_libraries(main PRIVATE cpprestsdk::cpprest cpprestsdk::cpprestsdk_zlib_internal cpprestsdk::cpprestsdk_brotli_internal)

PS D:\vcpkg> git status
HEAD detached at origin/master
nothing to commit, working tree clean
PS D:\vcpkg> dir -Recurse ports\out
PS D:\vcpkg>
```

**Review by BillyONeal — CHANGES_REQUESTED** [review]
We need to figure out why you're getting out/ folders, not ignore that.

**Comment by dan-shaw** [comment]
Closing this PR, I think we need to open an issue and find the library that has the problem first before adding this check.

**Pull request closed without merging**
