### PR TITLE
[freeimage] add compatibility with latest OpenEXR

### PR DESCRIPTION
**Pull request by cenit**
Due to #5227, some modifications are required in this port.
I also simplified it a lot in the meantime, recycling as much code as possible instead of having to maintain many doubles

### CODE REVIEW

**Comment by cenit** [comment]
@vicroms I confirm no problem on my side pulling this PR, merging it with #5210, #5227 and also #5226 (or rebasing this PR on the latest master, since #5226 has already been accepted). If it is done, then `freeimage[core]:x64-windows` is built correctly

[log.txt](https://github.com/Microsoft/vcpkg/files/2865349/log.txt)

**Comment by vicroms** [comment]
@cenit
I had better luck pulling the PRs for `libwebp` and `openexr` into this branch (at least it builds locally).
On my previous attempt I started from the `libwebp` branch as base.

I'll trigger a CI build and let you know the results.

**Comment by cenit** [comment]
thanks! hoping for the best, please let me know in case you find anything that requires a modification

**Comment by vicroms** [comment]
@cenit 
Shouldn't OpenEXR be disabled for UWP? The now removed port for `ilmbase` didn't support UWP, and now that it is embedded into OpenEXR doesn't the same restriction apply?

**Comment by cenit** [comment]
closed in favor of #5417

**Pull request closed without merging**
