### PR TITLE
[libltdl] New port

### PR DESCRIPTION
**Pull request by dg0yt**
- #### What does your PR fix?
  Adds an explicit libltdl port. This mirrors the packaging in other repositories:
  https://repology.org/project/libltdl/information
  Some ports already use individual copies.
  https://github.com/microsoft/vcpkg/pull/21731#issuecomment-1276658920, CC @vividos

  Known issues:
  When using libltdl with static linkage for linux, libdl (`-ldl`) is a usage requirement. Some downstream ports don't handle this sufficiently. (Static linkage is less common in linux.) `CMAKE_DL_LIBS` seems to be a good source of polyfill for CMake projects.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  !uwp, no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  yes

### CODE REVIEW

**Comment by dg0yt** [comment]
To be continued after #27314.

**Comment by dg0yt** [comment]
> You have modified or added at least one portfile where deprecated functions are used.
> ...
> In the ports that use the new function, you have to add the corresponding dependencies:

@autoantwort Now it catches `vcpkg_extract_source_archive_ex` but the suggested dependencies do no match. Maybe we should just point to a doc page with detailed instructions?

**Comment by dg0yt** [comment]
https://github.com/microsoft/vcpkg/pull/27314.was merged. PR updated.

**Comment by autoantwort** [comment]
> Now it catches `vcpkg_extract_source_archive_ex` but the suggested dependencies do no match.

What do you mean?

**Comment by dg0yt** [comment]
Modernizing `vcpkg_extract_source_archive_ex` doesn't need the proposed `vcpkg-cmake`, `vcpkg-cmake-config`.

**Comment by autoantwort** [comment]
Yeah it does not check which function is used, it checks if any function is used. In general the goal should be https://github.com/microsoft/vcpkg/pull/26981

**Comment by dg0yt** [comment]
To be continued after #27471.

**Comment by BillyONeal** [comment]
Closing this as it's been in draft without changes for more than a year, please feel to recreate or reopen!

**Pull request closed without merging**
