### PR TITLE
[wxWidgets] Use libpng CMake target

### LINKED ISSUE #16543: [wxWidgets] Using static triplet fails because of missing png.lib
**Describe the bug**
The cmake wrapper for wxWidgets expects libpng to always be called `png.lib` but it is not on static triplets so it fails to find the library to link when you try to use wxWidgets.

**Environment**
- OS: Windows
- Compiler: cl.exe 19.28.29910

**To Reproduce**
1. ./vcpkg install wxwidgets:x64-windows-static
2. Try to use wxWidgets from your own statically linked project via CMake

**Expected behavior**
Successful linking

**Failure logs** 
    fatal error LNK1104: cannot open file 'png.lib'

**Additional context**
libpng's library for static triplets is called `png_static` so using `png` won't work.

I have a pull request ready that I will add after filing this issue.

### PR DESCRIPTION
**Pull request by brad-anderson**
libpng uses png_static library name on static triplets. Using the CMake target fixes wxWidget's cmake wrapper so it works on static triplets.

**Describe the pull request**
Updates wxWidget's cmake wrapper to use the libpng CMake target instead of referring to the libpng library by name.

- What does your PR fix?
  Fixes #16543

- Which triplets are supported/not supported? Have you updated the CI baseline?
  Adds partial support for static triplets (unrelated issues remain related to release/debug library mixup #16545)
 
- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes, I hope.

### CODE REVIEW

**Comment by JackBoosY** [comment]
We should modify the cmake wrapper instead of this.

**Comment by brad-anderson** [comment]
> 
> 
> We should modify the cmake wrapper instead of this.

Perhaps I'm missing something but is that not what this PR does?

**Comment by Hoikas** [comment]
vcpkg's libpng port exports a config named `libpng`. This PR seems to revert to using CMake's built-in FindPNG and its `PNG::PNG` target.

**Comment by JackBoosY** [comment]
Since my PR https://github.com/microsoft/vcpkg/pull/16546 was merged. can I close this PR now?

**Pull request closed without merging**
