### PR TITLE
[many-ports] Don't use deprecated functions (autogenerated)

### PR DESCRIPTION
**Pull request by autoantwort**
Generated by https://github.com/microsoft/vcpkg-tool/pull/720

### CODE REVIEW

**Comment by vicroms** [comment]
@autoantwort would it be possible for you to submit the script that generated these changes in a different PR? 
It would be easier for us to review and validate the script itself than the 1.3K changed files in here.

**Comment by autoantwort** [comment]
> @autoantwort would it be possible for you to submit the script that generated these changes in a different PR? It would be easier for us to review and validate the script itself than the 1.3K changed files in here.

Sure, it was generated by https://github.com/microsoft/vcpkg-tool/pull/720

**Comment by autoantwort** [comment]
New license expressions core from [here](https://github.com/microsoft/vcpkg/pull/24060#issuecomment-1261172637) if the [spdx online tool](https://tools.spdx.org/app/check_license/) and the github api agreed on the license expression.

**Comment by FrankXie05** [comment]
@autoantwort Can you resolve the conflict?
Although there are a lot of modified files, the content is just to apply the new function. I think we can merge it when the CI is passed. :)  (It is best to divide it into multiple PRs to modify, which is more convenient for review. 🙌)

**Comment by autoantwort** [comment]
@FrankXie05 I will do it if @vicroms says they are willing to merge it.

**Comment by vicroms** [comment]
I'll make some time to review https://github.com/microsoft/vcpkg-tool/pull/720

**Comment by Pospelove** [comment]
It's awesome. I love that

**Review by BillyONeal — APPROVED** [review]

**Comment by BillyONeal** [comment]
Basically all of the license changes should have been -or-later rather than -only.
The qtbase change was incorrect because only a commented out line changed, so I reverted that.

Will merge as soon as build finishes...

**Pull request merged**
