### PR TITLE
[ignition-msgs*] Fix flaky CI tests for ignition-msgs* ports

### LINKED ISSUE #14565: [ignition-msgs1] cmake dev warning in portfile
From one of my CI runs:

```
Building package ignition-msgs1[core]:x64-windows-static...
Could not locate cached archive: W:\08\087749218c4e972449965998fdab076641a6aa50.zip
-- Downloading https://github.com/ignitionrobotics/ign-msgs/archive/ignition-msgs_1.0.0.tar.gz...
-- Extracting source D:/downloads/ignitionrobotics-ign-msgs-ignition-msgs_1.0.0.tar.gz
-- Applying patch fix-protobuf-static-link-order.patch
-- Using source at D:/buildtrees/ignition-msgs1/src/msgs_1.0.0-83c03d2b65.clean
-- Configuring x64-windows-static-dbg
-- Configuring x64-windows-static-rel
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Using msys root at D:/downloads/tools/msys2/c809757c94447846
-- Fixing pkgconfig file: D:/packages/ignition-msgs1_x64-windows-static/lib/pkgconfig/ignition-msgs1.pc
-- Fixing pkgconfig file: D:/packages/ignition-msgs1_x64-windows-static/debug/lib/pkgconfig/ignition-msgs1.pc
-- Installing: D:/packages/ignition-msgs1_x64-windows-static/share/ignition-msgs1/copyright
CMake Warning (dev) at ports/ignition-msgs1/portfile.cmake:33 (set):
  Only the first value argument is used when setting an environment variable.
  Argument 'C:\Program Files (x86)\Microsoft Visual
  Studio\2019\Enterprise\VC\Tools\MSVC\14.27.29110\bin\HostX64\x64' and later
  are unused.
Call Stack (most recent call first):
  scripts/ports.cmake:136 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Performing post-build validation
-- Performing post-build validation done
```

@traversaro: Please fix

https://github.com/microsoft/vcpkg/blob/783763162901f32e6d6270aede22519844b8e9ce/ports/ignition-msgs1/portfile.cmake#L33

should be `set(ENV{PATH} "${path_backup}")`

### PR DESCRIPTION
**Pull request by traversaro**
We fix the flaky CI tests by not adding anymore the bin and debug/bin directories to the `PATH`, but rather by making sure that `VCPKG_APPLOCAL_DEPS` option is correctly propagated.

**Describe the pull request**

- What does your PR fix? Fixes the problem mentioned in https://github.com/microsoft/vcpkg/pull/14324#discussion_r517128792, not sure if there is a corresponding issue.

- Which triplets are supported/not supported? Have you updated the CI baseline? The PR should not change the supported triplets. 

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)? Yes

cc @BillyONeal

### CODE REVIEW

**Comment by traversaro** [comment]
As I needed to modify the `vcpkg_configure_cmake` script that is used by basically every CMake port, I imagine we will have the usual endless CI and spurious CI failures of those cases. :D

**Comment by JackBoosY** [comment]
Nicole's PR #14399 also tried to fix this issue.

**Comment by traversaro** [comment]
> 
> 
> Nicole's PR #14399 also tried to fix this issue.

To clarify, this is a cleanup that should avoid problems of this kind also in the future.

**Comment by traversaro** [comment]
The osgearth failure is due to this error: 
~~~
D:\buildtrees\osgearth\src\18c0ed88a1-76bf0cae95.clean\src\osgEarthDrivers\cache_leveldb\Tracker(23): fatal error C1083: Cannot open include file: 'osgEarth/ThreadingUtils': No such file or directory
[377/606] "C:\PROGRA~2\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.27.29110\bin\Hostx64\x64\cl.exe"   /TP -DCURL_STATICLIB -DOSGEARTH_HAVE_GEOS -DOSGEARTH_HAVE_MBTILES -DOSGEARTH_HAVE_MVT -DOSGEARTH_HAVE_SQLITE3 -DOSGEARTH_LIBRARY -DTIXML_USE_STL -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -D__STDC_FORMAT_MACROS -DosgEarth_EXPORTS -Ibuild_include -ID:\installed\x64-windows\include -ID:\buildtrees\osgearth\src\18c0ed88a1-76bf0cae95.clean\src -Isrc\osgEarth /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /Fosrc\osgEarth\CMakeFiles\osgEarth.dir\PlaceNode.cpp.obj /Fdsrc\osgEarth\CMakeFiles\osgEarth.dir\ /FS -c D:\buildtrees\osgearth\src\18c0ed88a1-76bf0cae95.clean\src\osgEarth\PlaceNode.cpp
[378/606] "C:\PROGRA~2\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.27.29110\bin\Hostx64\x64\cl.exe"   /TP -DCURL_STATICLIB -DOSGEARTH_HAVE_GEOS -DOSGEARTH_HAVE_MBTILES -DOSGEARTH_HAVE_MVT -DOSGEARTH_HAVE_SQLITE3 -DOSGEARTH_LIBRARY -DTIXML_USE_STL -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -D__STDC_FORMAT_MACROS -DosgEarth_EXPORTS -Ibuild_include -ID:\installed\x64-windows\include -ID:\buildtrees\osgearth\src\18c0ed88a1-76bf0cae95.clean\src -Isrc\osgEarth /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /Fosrc\osgEarth\CMakeFiles\osgEarth.dir\LocalGeometryNode.cpp.obj /Fdsrc\osgEarth\CMakeFiles\osgEarth.dir\ /FS -c D:\buildtrees\osgearth\src\18c0ed88a1-76bf0cae95.clean\src\osgEarth\LocalGeometryNode.cpp
[379/606] "C:\PROGRA~2\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.27.29110\bin\Hostx64\x64\cl.exe"   /TP -DOSGEARTH_HAVE_MBTILES -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -Dosgdb_osgearth_cache_leveldb_EXPORTS -Ibuild_include -ID:\installed\x64-windows\include -ID:\buildtrees\osgearth\src\18c0ed88a1-76bf0cae95.clean\src /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /Fosrc\osgEarthDrivers\cache_leveldb\CMakeFiles\osgdb_osgearth_cache_leveldb.dir\LevelDBCacheBin.cpp.obj /Fdsrc\osgEarthDrivers\cache_leveldb\CMakeFiles\osgdb_osgearth_cache_leveldb.dir\ /FS -c D:\buildtrees\osgearth\src\18c0ed88a1-76bf0cae95.clean\src\osgEarthDrivers\cache_leveldb\LevelDBCacheBin.cpp
FAILED: src/osgEarthDrivers/cache_leveldb/CMakeFiles/osgdb_osgearth_cache_leveldb.dir/LevelDBCacheBin.cpp.obj 
"C:\PROGRA~2\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.27.29110\bin\Hostx64\x64\cl.exe"   /TP -DOSGEARTH_HAVE_MBTILES -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -Dosgdb_osgearth_cache_leveldb_EXPORTS -Ibuild_include -ID:\installed\x64-windows\include -ID:\buildtrees\osgearth\src\18c0ed88a1-76bf0cae95.clean\src /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /Fosrc\osgEarthDrivers\cache_leveldb\CMakeFiles\osgdb_osgearth_cache_leveldb.dir\LevelDBCacheBin.cpp.obj /Fdsrc\osgEarthDrivers\cache_leveldb\CMakeFiles\osgdb_osgearth_cache_leveldb.dir\ /FS -c D:\buildtrees\osgearth\src\18c0ed88a1-76bf0cae95.clean\src\osgEarthDrivers\cache_leveldb\LevelDBCacheBin.cpp
D:\buildtrees\osgearth\src\18c0ed88a1-76bf0cae95.clean\src\osgEarthDrivers\cache_leveldb\Tracker(23): fatal error C1083: Cannot open include file: 'osgEarth/ThreadingUtils': No such file or directory
[380/606] "C:\PROGRA~2\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.27.29110\bin\Hostx64\x64\cl.exe"   /TP -DCURL_STATICLIB -DOSGEARTH_HAVE_GEOS -DOSGEARTH_HAVE_MBTILES -DOSGEARTH_HAVE_MVT -DOSGEARTH_HAVE_SQLITE3 -DOSGEARTH_LIBRARY -DTIXML_USE_STL -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -D__STDC_FORMAT_MACROS -DosgEarth_EXPORTS -Ibuild_include -ID:\installed\x64-windows\include -ID:\buildtrees\osgearth\src\18c0ed88a1-76bf0cae95.clean\src -Isrc\osgEarth /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /Fosrc\osgEarth\CMakeFiles\osgEarth.dir\ModelNode.cpp.obj /Fdsrc\osgEarth\CMakeFiles\osgEarth.dir\ /FS -c D:\buildtrees\osgearth\src\18c0ed88a1-76bf0cae95.clean\src\osgEarth\ModelNode.cpp
[381/606] "C:\PROGRA~2\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.27.29110\bin\Hostx64\x64\cl.exe"   /TP -DCURL_STATICLIB -DOSGEARTH_HAVE_GEOS -DOSGEARTH_HAVE_MBTILES -DOSGEARTH_HAVE_MVT -DOSGEARTH_HAVE_SQLITE3 -DOSGEARTH_LIBRARY -DTIXML_USE_STL -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -D__STDC_FORMAT_MACROS -DosgEarth_EXPORTS -Ibuild_include -ID:\installed\x64-windows\include -ID:\buildtrees\osgearth\src\18c0ed88a1-76bf0cae95.clean\src -Isrc\osgEarth /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /Fosrc\osgEarth\CMakeFiles\osgEarth.dir\FeatureNode.cpp.obj /Fdsrc\osgEarth\CMakeFiles\osgEarth.dir\ /FS -c D:\buildtrees\osgearth\src\18c0ed88a1-76bf0cae95.clean\src\osgEarth\FeatureNode.cpp
[382/606] "C:\PROGRA~2\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.27.29110\bin\Hostx64\x64\cl.exe"   /TP -DOSGEARTH_HAVE_MBTILES -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -Dosgdb_osgearth_cache_leveldb_EXPORTS -Ibuild_include -ID:\installed\x64-windows\include -ID:\buildtrees\osgearth\src\18c0ed88a1-76bf0cae95.clean\src /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /Fosrc\osgEarthDrivers\cache_leveldb\CMakeFiles\osgdb_osgearth_cache_leveldb.dir\LevelDBCacheDriver.cpp.obj /Fdsrc\osgEarthDrivers\cache_leveldb\CMakeFiles\osgdb_osgearth_cache_leveldb.dir\ /FS -c D:\buildtrees\osgearth\src\18c0ed88a1-76bf0cae95.clean\src\osgEarthDrivers\cache_leveldb\LevelDBCacheDriver.cpp
FAILED: src/osgEarthDrivers/cache_leveldb/CMakeFiles/osgdb_osgearth_cache_leveldb.dir/LevelDBCacheDriver.cpp.obj 
"C:\PROGRA~2\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.27.29110\bin\Hostx64\x64\cl.exe"   /TP -DOSGEARTH_HAVE_MBTILES -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -Dosgdb_osgearth_cache_leveldb_EXPORTS -Ibuild_include -ID:\installed\x64-windows\include -ID:\buildtrees\osgearth\src\18c0ed88a1-76bf0cae95.clean\src /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /Fosrc\osgEarthDrivers\cache_leveldb\CMakeFiles\osgdb_osgearth_cache_leveldb.dir\LevelDBCacheDriver.cpp.obj /Fdsrc\osgEarthDrivers\cache_leveldb\CMakeFiles\osgdb_osgearth_cache_leveldb.dir\ /FS -c D:\buildtrees\osgearth\src\18c0ed88a1-76bf0cae95.clean\src\osgEarthDrivers\cache_leveldb\LevelDBCacheDriver.cpp
D:\buildtrees\osgearth\src\18c0ed88a1-76bf0cae95.clean\src\osgEarthDrivers\cache_leveldb\Tracker(23): fatal error C1083: Cannot open include file: 'osgEarth/ThreadingUtils': No such file or directory
~~~
It does not seem to be directly related to this modification

**Review by JackBoosY — APPROVED** [review]

**Comment by traversaro** [comment]
>  I started #14474 to check if the ports fails also in the current master.

Unfortunately https://github.com/microsoft/vcpkg/pull/14474 worked fine, so either the osqearth failure is non-deterministic, or it is actually related to the change of the PR. Another possibility is that the failure is due to the rebuild of one of osgeart dependencies.

**Comment by BillyONeal** [comment]
osgearth has also been sporadically failing; I suspect they have some form of races in their build. As such I don't think we should block merging over that.

However, I have a concern with forcing `VCPKG_APPLOCAL_DEPS` on for the tree -- that's a huge waste of copying time for most ports since it triggers a copy into the buildtrees directory which is then immediately deleted.

**Comment by JackBoosY** [comment]
```
D:\buildtrees\osgearth\src\18c0ed88a1-76bf0cae95.clean\src\osgEarthDrivers\cache_leveldb\Tracker(23): fatal error C1083: Cannot open include file: 'osgEarth/ThreadingUtils': No such file or directory
```

**Comment by traversaro** [comment]
> osgearth has also been sporadically failing; I suspect they have some form of races in their build. As such I don't think we should block merging over that.
> 
> However, I have a concern with forcing `VCPKG_APPLOCAL_DEPS` on for the tree -- that's a huge waste of copying time for most ports since it triggers a copy into the buildtrees directory which is then immediately deleted.

That is the reason why it is enabled only for ignition-msgs* ports and not for all the ports.

**Review by BillyONeal — APPROVED** [review]
>That is the reason why it is enabled only for ignition-msgs* ports and not for all the ports.

Ah, derp, I somehow read the default you set as backwards to what you actually set 🤣

**Comment by traversaro** [comment]
> 
> 
> > That is the reason why it is enabled only for ignition-msgs* ports and not for all the ports.
> 
> Ah, derp, I somehow read the default you set as backwards to what you actually set 🤣

No problem. I think that in general having an opt-in `VCPKG_APPLOCAL_DEPS` set to ON is a good idea for all the projects that need to run a code generator as part of their build.

**Comment by strega-nil** [comment]
I'll merge after CI runs through.

**Comment by Neumann-A** [comment]
>No problem. I think that in general having an opt-in VCPKG_APPLOCAL_DEPS set to ON is a good idea for all the projects that need to run a code generator as part of their build.

isn't that why ADD_BIN_TO_PATH exists?

**Comment by traversaro** [comment]
> 
> 
> > No problem. I think that in general having an opt-in VCPKG_APPLOCAL_DEPS set to ON is a good idea for all the projects that need to run a code generator as part of their build.
> 
> isn't that why ADD_BIN_TO_PATH exists?

Good catch! Yes, I think that would also be sufficient, and will not require the crazy luck of being able to do a full re-build of all the cmake-based ports without any spurious failures, that is apparently really unlikely. I think I can use that one.

**Comment by strega-nil** [comment]
Waiting for the `ADD_BIN_TO_PATH` change.

**Comment by traversaro** [comment]
> 
> 
> Waiting for the `ADD_BIN_TO_PATH` change.

Done in https://github.com/microsoft/vcpkg/pull/14730 .

**Pull request closed without merging**
