### PR TITLE
[septag-sx] Add new port

### PR DESCRIPTION
**Pull request by myd7349**
https://github.com/septag/sx
BTW, is the package name too short?
https://github.com/septag/sx/pull/11

### CODE REVIEW

**Comment by Rastaban** [comment]
I see failures on uwp triplets and arm64-windows.  Are those expected?

@vicroms do we have a policy regarding the length of names?

**Comment by vicroms** [comment]
There's no policy regarding specifically to name length, but searching in [repology.org](https://repology.org/projects/s/?search=sx) returns a bunch of similarly named `sx` packages.

In Fedora, `sx` refers to a [reporting tool](https://src.fedoraproject.org/rpms/sx), but on Arch-Linux it refers to the [`septag/sx` repo](https://aur.archlinux.org/packages/sx-git) (same as this PR).

I don't see any other obvious name for this library, unless we make the package name `septag-sx`.

**Comment by vicroms** [comment]
More packages already named `sx`

https://pkgs.org/download/sx
https://packages.debian.org/search?searchon=names&keywords=sx

**Comment by Rastaban** [comment]
Okay, so go ahead and change the name (maybe `septag-sx`?)

**Comment by myd7349** [comment]
@Rastaban @vicroms Thanks for your helpful reply. Maybe we can document it somewhere(Also this: https://github.com/microsoft/vcpkg/pull/5817#issuecomment-476909628).
I think `septag-sx` is better.
I didn't test it with a real project yet, I will test it later. Then I may figure out what happens to `UWP` and `ARM`.

**Comment by myd7349** [comment]
Hi! @NancyLi1013 Thanks!
I will test it as soon as possible.

**Comment by Rastaban** [comment]
A step toward improving the docs: #6397

**Comment by myd7349** [comment]
Test with https://github.com/myd7349/Ongoing-Study/tree/master/cpp/CMake/vcpkg/sx_example. These triplets are tested:
* x86-windows
* x86-windows-static
* x64-windows
* x64-windows-static
* x64-linux

**Comment by NancyLi1013** [comment]
@myd7349 ,thanks for your contribution. All test results are normal now except for uwp/arm/arm64 that are not supported.

**Comment by grdowns** [comment]
Thanks for the new port, @myd7349!

**Pull request merged**
