### PR TITLE
Added SFML 2.4.0 and Sery 1.0.0 support

### PR DESCRIPTION
**Pull request by Telokis**

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Sery looks great, I'd be happy to pull that in via a separate request.

Looking at `sfml`'s build output, I notice it has a bunch of extra lib files:
```
│   │
│   └───lib
│       │   flac.lib
│       │   freetype.lib
│       │   jpeg.lib
│       │   ogg.lib
│       │   openal32.lib
│       │   sfml-audio-d.lib
│       │   sfml-graphics-d.lib
│       │   sfml-main-d.lib
│       │   sfml-network-d.lib
│       │   sfml-system-d.lib
│       │   sfml-window-d.lib
│       │   vorbis.lib
│       │   vorbisenc.lib
│       │   vorbisfile.lib
```

I suspect it's building its own copies of `flac`, `freetype`, etc and statically linking them in. We don't want libraries to build private copies of libs -- they need to use the other packages so updates correctly apply system-wide.

**Comment by Ninetainedo** [comment]
I made #46 for Sery.
Regarding SFML, what would be the best solution ?
A dependency system inside the portfile ? Something similar to what is done with [Cocos2d](https://github.com/Microsoft/vcpkg/blob/master/ports/cocos2d/portfile.cmake) ?

**Comment by ras0219-msft** [comment]
Yes, the `CONTROL` file needs to list out all the dependencies and the `portfile.cmake` needs to supply whatever CMake arguments are needed to coax SFML to build against the already-existing libraries.

This will probably require patching. See:
https://github.com/SFML/SFML/blob/master/CMakeLists.txt#L301
https://github.com/SFML/SFML/blob/master/src/SFML/CMakeLists.txt#L17
https://github.com/SFML/SFML/blob/master/src/SFML/Graphics/CMakeLists.txt#L93
etc.

I think the best way to figure out what needs to be fixed may be to completely delete the `extlibs\` folder after extracting the source but before running `vcpkg_cmake_configure`. Then, CMake and cl.exe should guide us directly to all the issues.

**Comment by Ninetainedo** [comment]
From the CMakeLists, it seems that SFML doesn't have a possible workaround to allow users to compile with the libraries they already have.
That could be an issue for others libraries as well. (Thinking of Ogre #14 and its ton of dependencies right now)

Deleting extlibs before configuring would probably make `vcpkg_cmake_configure` error.

**Comment by Ninetainedo** [comment]
Alright, my last comment is outdated now that I've seen how opencv ports is made.
I will try to dig through it and let everyone know about my progress here.

**Comment by Ninetainedo** [comment]
I'm closing this pull request for now. I'll open an issue to keep track of my progress.

**Pull request closed without merging**
