### PR TITLE
VM update January 2023

### PR DESCRIPTION
**Pull request by BillyONeal**

### CODE REVIEW

**Comment by Osyotr** [comment]
Maybe also add `libcups2-dev`? Required by qt printsupport (which is currently not controlled by feature)

**Comment by Neumann-A** [comment]
Cups still looks like a normal port to me. https://github.com/OpenPrinting/cups

**Comment by BillyONeal** [comment]
REGRESSION: marisa-trie:x86-windows failed with FILE_CONFLICTS. If expected, add marisa-trie:x86-windows=fail to C:\a\2\s\scripts\azure-pipelines/../ci.baseline.txt.
REGRESSION: marisa-trie:x64-windows failed with FILE_CONFLICTS. If expected, add marisa-trie:x64-windows=fail to C:\a\2\s\scripts\azure-pipelines/../ci.baseline.txt.

```
error: The following files are already installed in D:/installed/x86-windows and are in conflict with marisa-trie:x86-windows
Installed by hunspell:x86-windows
include/Makefile.am

Elapsed time to handle marisa-trie:x86-windows: 18.54 s
```

https://github.com/microsoft/vcpkg/pull/28607/ + https://github.com/microsoft/vcpkg/pull/28352/

REGRESSION: ideviceinstaller:x64-windows-static failed with BUILD_FAILED. If expected, add ideviceinstaller:x64-windows-static=fail to C:\a\2\s\scripts\azure-pipelines/../ci.baseline.txt.

Failed due to multiply defined symbols:

       "D:\buildtrees\ideviceinstaller\x64-windows-static-rel\1.1.2.23-68bdac5247.clean\ideviceinstaller.vcxproj" (Rebuild target) (1) ->
       (Link target) ->
         getopt.lib(getopt.c.obj) : error LNK2005: optind already defined in darknet.lib(getopt.c.obj) [D:\buildtrees\ideviceinstaller\x64-windows-static-rel\1.1.2.23-68bdac5247.clean\ideviceinstaller.vcxproj]
         getopt.lib(getopt.c.obj) : error LNK2005: opterr already defined in darknet.lib(getopt.c.obj) [D:\buildtrees\ideviceinstaller\x64-windows-static-rel\1.1.2.23-68bdac5247.clean\ideviceinstaller.vcxproj]
         getopt.lib(getopt.c.obj) : error LNK2005: optopt already defined in darknet.lib(getopt.c.obj) [D:\buildtrees\ideviceinstaller\x64-windows-static-rel\1.1.2.23-68bdac5247.clean\ideviceinstaller.vcxproj]
         D:\buildtrees\ideviceinstaller\x64-windows-static-rel\1.1.2.23-68bdac5247.clean\x64\Release\ideviceinstaller.exe : fatal error LNK1169: one or more multiply defined symbols found [D:\buildtrees\ideviceinstaller\x64-windows-static-rel\1.1.2.23-68bdac5247.clean\ideviceinstaller.vcxproj]

https://github.com/microsoft/vcpkg/pull/28718

**Pull request merged**
