### PR TITLE
[vcpkg_configure_meson] CMake binary is now supplied to Meson in cross-compile configurations.

### PR DESCRIPTION
**Pull request by PandarinDev**
After one of our dependencies (Pistache) switched to Meson we noticed that we can still compile our project for the host architecture (x86_64), but cross-compilation broke. Turns out this is because `vcpkg_configure_meson` only supplies the CMake binary to the Meson configuration when building for the native platform.

- #### What does your PR fix?  
CMake binary is now supplied to Meson even when cross-compiling by `vcpkg_configure_meson`.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
Yes

### CODE REVIEW

**Comment by PandarinDev** [comment]
I don't see a reason for build failure other than the connection timeout to the node. Could this be an infrastructure problem, not a code problem? Is there anything I can do to help moving this PR forward?

**Comment by PhoebeHui** [comment]
@PandarinDev, sorry for my late response, I have rerun the PR.

**Comment by PhoebeHui** [comment]
cc @Neumann-A

**Comment by PhoebeHui** [comment]
I want to get other maintainers' feedback.

cc @Neumann-A, do you know more about this?

**Comment by Neumann-A** [comment]
This is just passing the `cmake` binary to meson? Normally meson should be able to find it but for cross builds it might not do a lookup. So i am totally fine with this change.

**Comment by PandarinDev** [comment]
Yes, that's the only change basically. Passing the `cmake` binary to meson is already done in native builds as I pointed out, this part was simply missing in the cross compilation version of `vcpkg_configure_meson`.

**Review by PhoebeHui — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the fix :)

**Pull request merged**
