### PR TITLE
[boost] bugfix and new features after update to 1.77.0

### LINKED ISSUE #20417: [boost] build failure due to missing msmpi
**Host Environment**
- OS: Windows
- Compiler: MSVC VS2019 16.11.3

**To Reproduce**
`./vcpkg install boost:x64-windows-static-md`

**Failure logs** 
```
CMake Error at ports/msmpi/portfile.cmake:59 (message):
    Could not find:
      C:\Program Files/Microsoft MPI/Bin/mpiexec.exe
    Please install the MSMPI redistributable package before trying to install this port.
    The appropriate installer has been downloaded to:
      E:/vcpkg/downloads/msmpisetup-10.1.12498.exe
```

**Additional context**

Looks like now boost by default has a dependency on the boost-mpi boost-

### LINKED ISSUE #20508: [Boost-1.77.0::MSMPI] build failure (x86, x64)
**Host Environment**
- OS: Windows
- Compiler: Visual Studio 2019 16.11.3

**To Reproduce**
`./vcpkg install boost:x86-windows`
`./vcpkg install boost:x64-windows`

**Failure logs** 
For x86:
```
Building package msmpi[core]:x86-windows...
-- Downloading https://download.microsoft.com/download/a/5/2/a5207ca5-1203-491a-8fb8-906fd68ae623/msmpisdk.msi -> msmpisdk-10.1.12498-b0087dfd.msi...
-- Downloading https://download.microsoft.com/download/a/5/2/a5207ca5-1203-491a-8fb8-906fd68ae623/msmpisetup.exe -> msmpisetup-10.1.12498.exe...
CMake Error at ports/msmpi/portfile.cmake:59 (message):
    Could not find:
      C:\Program Files/Microsoft MPI/Bin/mpiexec.exe
    Please install the MSMPI redistributable package before trying to install this port.
    The appropriate installer has been downloaded to:
      D:/toolkit/vcpkg/downloads/msmpisetup-10.1.12498.exe

Call Stack (most recent call first):
  scripts/ports.cmake:141 (include)


Error: Building package msmpi:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: msmpi:x86-windows
  Vcpkg version: 2021-09-10-2059ef11aa6067e6f59b0d939c5d17e3c5c47d3e

Additionally, attach any relevant sections from the log files above.
```

For x64:
```
Building package msmpi[core]:x64-windows...
-- Downloading https://download.microsoft.com/download/a/5/2/a5207ca5-1203-491a-8fb8-906fd68ae623/msmpisdk.msi -> msmpisdk-10.1.12498-b0087dfd.msi...
-- Downloading https://download.microsoft.com/download/a/5/2/a5207ca5-1203-491a-8fb8-906fd68ae623/msmpisetup.exe -> msmpisetup-10.1.12498.exe...
CMake Error at ports/msmpi/portfile.cmake:59 (message):
    Could not find:
      C:\Program Files/Microsoft MPI/Bin/mpiexec.exe
    Please install the MSMPI redistributable package before trying to install this port.
    The appropriate installer has been downloaded to:
      D:/toolkit/vcpkg/downloads/msmpisetup-10.1.12498.exe

Call Stack (most recent call first):
  scripts/ports.cmake:141 (include)


Error: Building package msmpi:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: msmpi:x64-windows
  Vcpkg version: 2021-09-10-2059ef11aa6067e6f59b0d939c5d17e3c5c47d3e

Additionally, attach any relevant sections from the log files above.
```
**Additional context**
Not install anything, just run the command above.
Please fix this issue, thx.

### PR DESCRIPTION
**Pull request by yurybura**
Allow to disable compression filters for iostreams. Examples:
```
vcpkg install boost-iostreams[core]
vcpkg install boost-iostreams[core,zlib]
vcpkg install boost-iostreams[core,zstd]
vcpkg install boost-iostreams[core,lzma,zstd]
etc.
```

Fixes #20417
Fixes #20508

### CODE REVIEW

**Review by PhoebeHui — COMMENTED** [review]
boost-odeint also depends on boost-mpi. Could you please remove it from boost dependency list?

**Comment by yurybura** [comment]
> boost-odeint also depends on boost-mpi. Could you please remove it from boost dependency list?

Done.

**Comment by dg0yt** [comment]
Maintainers please re-run CI on this.

**Comment by BillyONeal** [comment]
> Maintainers please re-run CI on this.

Done.

**Review by PhoebeHui — APPROVED** [review]
Thanks for your updates!

**Review by BillyONeal — APPROVED** [review]

**Pull request merged**
