### PR TITLE
[woff2] no absolute paths

### PR DESCRIPTION
**Pull request by autoantwort**
For #20469

### CODE REVIEW

**Comment by JonLiu1993** [comment]
@autoantwort ,Thanks for posting this issue, this is error log:
````
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:78 (message):
  /bin/pkg-config --exists libwoff2dec failed with error code: 1

      ENV{PKG_CONFIG_PATH}: "/mnt/vcpkg-ci/packages/woff2_x64-linux/lib/pkgconfig:/mnt/vcpkg-ci/packages/woff2_x64-linux/share/pkgconfig:/mnt/vcpkg-ci/installed/x64-linux/lib/pkgconfig:/mnt/vcpkg-ci/installed/x64-linux/share/pkgconfig"
      output: Package unofficial::brotli::brotlidec-static was not found in the pkg-config search path.

  Perhaps you should add the directory containing
  `unofficial::brotli::brotlidec-static.pc'

  to the PKG_CONFIG_PATH environment variable

  Package 'unofficial::brotli::brotlidec-static', required by 'libwoff2dec',
  not found
````

**Comment by autoantwort** [comment]
@JonLiu1993 Hm I don't get this error locally on my mac

**Review by JonLiu1993 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the fix!

**Pull request merged**
