### PR TITLE
[libirecovery] Add tools feature

### PR DESCRIPTION
**Pull request by xiaozhuai**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by xiaozhuai** [comment]
@Adela0814 @dg0yt
 I need `pkgconf`
```cmake
find_package(PkgConfig REQUIRED)
pkg_check_modules(readline REQUIRED IMPORTED_TARGET readline)
```
And I already provide these lines in json.
```json
{
      "name": "pkgconf",
      "host": true
}
```
But it fails with `Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)`
Please help.

**Comment by dg0yt** [comment]
> ```json
> {
>       "name": "pkgconf",
>       "host": true
> }
> ```

No. You need to do it in the portfile:
~~~
vcpkg_find_acquire_program(PKGCONFIG)
...
vcpkg_cmake_configure(
    ...
    "-DPKG_CONFIG_EXECUTABLE=${PKGCONFIG}"
)
~~~

**Comment by xiaozhuai** [comment]
@dg0yt 
So should I remove these in json?
```json
{
      "name": "pkgconf",
      "host": true
}
```

**Comment by dg0yt** [comment]
> ```json
> {
>       "name": "pkgconf",
>       "host": true
> }
> ```

Yes, please remove it.

**Comment by xiaozhuai** [comment]
@dg0yt It works now, thanks!

**Comment by xiaozhuai** [comment]
@dg0yt
The CI fails on `x64-windows-static`, which is odd.
Any suggestions?
```
irecovery.c.obj : error LNK2019: unresolved external symbol __imp_readline referenced in function init_shell
irecovery.c.obj : error LNK2019: unresolved external symbol __imp_add_history referenced in function append_command_to_history
irecovery.c.obj : error LNK2019: unresolved external symbol __imp_read_history referenced in function load_command_history
irecovery.c.obj : error LNK2019: unresolved external symbol __imp_write_history referenced in function append_command_to_history
irecovery.exe : fatal error LNK1120: 4 unresolved externals
```

**Comment by xiaozhuai** [comment]
@dg0yt 
After I add `USE_READLINE_STATIC `, this time the error log is
```
readline.lib(misc.c.obj) : error LNK2005: readline_top_level already defined in readline.lib(readline.c.obj)
readline.lib(text.c.obj) : error LNK2005: readline_top_level already defined in readline.lib(readline.c.obj)
readline.lib(undo.c.obj) : error LNK2005: readline_top_level already defined in readline.lib(readline.c.obj)
readline.lib(vi_mode.c.obj) : error LNK2005: readline_top_level already defined in readline.lib(readline.c.obj)
readline.lib(display.c.obj) : error LNK2005: readline_top_level already defined in readline.lib(readline.c.obj)
readline.lib(bind.c.obj) : error LNK2005: readline_top_level already defined in readline.lib(readline.c.obj)
readline.lib(rltty.c.obj) : error LNK2005: readline_top_level already defined in readline.lib(readline.c.obj)
readline.lib(input.c.obj) : error LNK2005: readline_top_level already defined in readline.lib(readline.c.obj)
readline.lib(terminal.c.obj) : error LNK2005: readline_top_level already defined in readline.lib(readline.c.obj)
readline.lib(signals.c.obj) : error LNK2005: readline_top_level already defined in readline.lib(readline.c.obj)
readline.lib(macro.c.obj) : error LNK2005: readline_top_level already defined in readline.lib(readline.c.obj)
readline.lib(nls.c.obj) : error LNK2005: readline_top_level already defined in readline.lib(readline.c.obj)
readline.lib(util.c.obj) : error LNK2005: readline_top_level already defined in readline.lib(readline.c.obj)
readline.lib(complete.c.obj) : error LNK2005: readline_top_level already defined in readline.lib(readline.c.obj)
readline.lib(kill.c.obj) : error LNK2005: readline_top_level already defined in readline.lib(readline.c.obj)
readline.lib(isearch.c.obj) : error LNK2005: readline_top_level already defined in readline.lib(readline.c.obj)
readline.lib(search.c.obj) : error LNK2005: readline_top_level already defined in readline.lib(readline.c.obj)
readline.lib(mbutil.c.obj) : error LNK2005: readline_top_level already defined in readline.lib(readline.c.obj)

readline.lib(parens.c.obj) : error LNK2005: readline_top_level already defined in readline.lib(readline.c.obj)

```

**Comment by dg0yt** [comment]
> readline.lib(parens.c.obj) : error LNK2005: readline_top_level already defined in readline.lib(readline.c.obj)

I guess you have now two providers of readline functions in the windows build: "readline.lib" from readline-win32, and local objects from your port. You must remove one of them. 
(Readline is normally only used by tools, so de-vendoring is less important. Try making the readline dependency `!windows`.)

**Comment by dg0yt** [comment]
... maybe I spoke to soon.

**Comment by xiaozhuai** [comment]
@dg0yt 
After I patch `readline-win32` port, it works on my local machine.
It looks like I am right.
But the patch it's so big, I'm not sure if there is a better solution.

**Pull request closed without merging**
