### PR TITLE
[vcpkg baseline][graphqlparser] Deindexed

### PR DESCRIPTION
**Pull request by WangWeiLin-MV**
Failed on https://dev.azure.com/vcpkg/public/_build/results?buildId=105330&view=logs&j=7b75bd19-17d3-53d4-00fd-23f1a49a8ba4

Test that `FIND_PACKAGE(PythonInterp 2 REQUIRED)`, and based on it's [result](https://dev.azure.com/vcpkg/public/_build/results?buildId=105487&view=results) :

* Failed for CI `x64-osx` and `arm64-osx` machine
* Found `python3` for CI `x64-linux` machine

The port `graphqlparser` requires `python2`, so mark `x64-osx` and `x64-linux` as `failed` in `ci.baseline.txt` (`arm64-osx` has bee added before #27414).

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [ ] ~SHA512s are updated for each updated download.~
- [ ] ~The "supports" clause reflects platforms that may be fixed by this new version.~
- [ ] ~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~
- [ ] ~Any patches that are no longer applied are deleted from the port's directory.~
- [ ] ~The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.~
- [ ] ~Only one version is added to each modified port's versions file.~

### CODE REVIEW

**Comment by BillyONeal** [comment]
Given that this won't build on any modern systems (depends on out of support Python 2), upstream appears missing, the last release was 7 years ago, and that this is a leaf, I think we should deindex this outright.

**Comment by BillyONeal** [comment]
@ras0219-msft @AugP @JavierMatosD @vicroms and I agree that it should be deindexed entirely. Thanks!

**Comment by WangWeiLin-MV** [comment]
@BillyONeal Please let me confirm that should this port be set to empty with `set(VCPKG_POLICY_EMPTY_PACKAGE enabled)`? Or deleted in `ports` and `versions/baseline.json`

**Comment by dg0yt** [comment]
> deleted in `ports` and `versions/baseline.json`

This.

**Comment by BillyONeal** [comment]
All the failures are existing other baseline regressions likely resulting from the build lab being broken before so I'm merging around it.

**Pull request merged**
