### PR TITLE
[rtmidi] Fix configure CMakeLists.txt

### PR DESCRIPTION
**Pull request by LilyWangL**
Use CMakeLists.txt which is in source code to configure. It has different configurations for Windows, Linux or MacOS. Due to `HMIDIIN` `HMIDIOUT` only support desktop apps, rtmidi doesn't support target UWP. Please refer to the following docs: 
`HMIDIIN`: https://docs.microsoft.com/en-us/previous-versions/dd798460(v%3Dvs.85)
`HMIDIOUT`: https://docs.microsoft.com/en-us/windows/win32/api/mmeapi/nf-mmeapi-midioutshortmsg
There are code in source file RtMidi.cpp L2394.
```
struct WinMidiData {
  HMIDIIN inHandle;    // Handle to Midi Input Device
  HMIDIOUT outHandle;  // Handle to Midi Output Device
  DWORD lastTime;
  MidiInApi::MidiMessage message;
  LPMIDIHDR sysexBuffer[RT_SYSEX_BUFFER_COUNT];
  CRITICAL_SECTION _mutex; // [Patrice] see https://groups.google.com/forum/#!topic/mididev/6OUjHutMpEo
};
```
Related issue: #6993
There are no features of this port need to test.

### CODE REVIEW

**Comment by strega-nil** [comment]
@LilyWangL do you still want to merge this PR? If so, could you resolve the conflicts and rerun the CI?

**Comment by LilyWangL** [comment]
> @LilyWangL do you still want to merge this PR? If so, could you resolve the conflicts and rerun the CI?

Done, this PR is ready to merge.

**Review by NancyLi1013 — APPROVED** [review]

**Review by ras0219-msft — APPROVED** [review]

**Pull request merged**
