### PR TITLE
[aws-sdk-cpp] disable custom memory management

### PR DESCRIPTION
**Pull request by cedral**
**Describe the pull request**
Allow building aws-sdk-cpp with custom memory management disabled. I added a feature setting to it called stdallocators that sets -DCUSTOM_MEMORY_MANAGEMENT=OFF

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  all

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  I think so.  

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by strega-nil-ms** [comment]
I think this should be a regular feature, since `CUSTOM_MEMORY_MANAGEMENT` seems to add features? Are dependencies which expect `AWS_CUSTOM_MEMORY_MANAGEMENT` compatible with those that don't?

**Comment by JonLiu1993** [comment]
@cedral ,Please also fix the Conflicting files.

**Comment by JonLiu1993** [comment]
@cedral , This is error log, please take a look:
[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/8493411/install-x64-linux-dbg-out.log)

**Comment by cedral** [comment]
I am pulling this plan. I discovered that the default for this setting is different based on static or dynamic libraries and since linux defaults to static and windows defaults to dynamic there is just no easy way to get consistent behavior that doesn't break existing things.

**Pull request closed without merging**
