### PR TITLE
[tensorflow] fix macOS build errors caused by numpy and bazel upgrades

### LINKED ISSUE #18597: [tensorflow-cc] build failure on x64-osx
**Host Environment**
- OS: osx (in vcpkg-ci)

**To Reproduce**
`./vcpkg install tensorflow-cc`

**Failure logs** 
[prerequesits-numpy-x64-osx-err (1).log](https://github.com/microsoft/vcpkg/files/6697954/prerequesits-numpy-x64-osx-err.1.log)
[stdout-x64-osx (2).log](https://github.com/microsoft/vcpkg/files/6697955/stdout-x64-osx.2.log)

**Additional context**
Tensorflow-cc was added to ci.baseline.txt in https://github.com/microsoft/vcpkg/pull/18233

It looks likely that updates to Python we use on our test hardware broke tensorflow-cc

### PR DESCRIPTION
**Pull request by jgehw**
Build failures on macOS originate from BLAS/LAPACK/ATLAS accelerator incompatibilities with numpy:
https://numpy.org/doc/stable/user/building.html#accelerated-blas-lapack-libraries

Fixes #18597 and #18809.

Moreover, fix scripts for static linkage that were broken by Bazel upgrade #19165.

### CODE REVIEW

**Comment by JackBoosY** [comment]
Please get failure logs [here](https://dev.azure.com/vcpkg/public/_build/results?buildId=57227&view=artifacts&pathAsName=false&type=publishedArtifacts).

**Comment by JackBoosY** [comment]
Convert this PR to draft until it's ready for review.

**Comment by JackBoosY** [comment]
Depends on https://github.com/microsoft/vcpkg/pull/19629.

**Comment by jgehw** [comment]
> Depends on #19629.

As far as I can see, only paraview (which caused the CI failure on x64_osx) depends on #19629. I don't see any relation between tensorflow and paraview build, so it should be ok to merge this PR even without paraview being fixed before.

**Comment by JackBoosY** [comment]
@jgehw We'd better to wait for all tests success.

**Review by JackBoosY — APPROVED** [review]

**Review by BillyONeal — APPROVED** [review]

**Comment by jgehw** [comment]
> 2021-08-31T06:41:59.6029260Z Starting package 2/3: tensorflow:x64-osx
> 2021-08-31T06:41:59.6030070Z Building package tensorflow[core]:x64-osx...
> 2021-08-31T09:16:23.3089720Z ##[error]The operation was canceled.
> 2021-08-31T09:16:28.6588930Z ##[section]Finishing: *** Test Modified Ports and Prepare Test Logs ***
> 2021-08-31T09:16:31.2688560Z ##[section]Starting: Report on Disk Space After Build

need to re-run failed job

**Comment by BillyONeal** [comment]
Finally got a passing build 😅.

Thanks for your contribution!

**Pull request merged**
