### PR TITLE
[gdal] Remove the dependency atlmfc

### PR DESCRIPTION
**Pull request by whuaegeanse**
**Describe the pull request**

- #### What does your PR fix?
  Fix##4257  
  Remove the dependency atlmfc of gdal because atlmfc is about 1G, the installation process is time-consuming. 
  GDAL works fine without relying on atlmfc.

### CODE REVIEW

**Comment by dg0yt** [comment]
@BillyONeal You added this dependency before the merge, without discussion, so please review.
FTR, atlbase.h/lib is used only to get the Windows product UUID in order to cheaply detect AWS EC2 instances. Without it, there is a more expensive network-based check. Cf. https://github.com/OSGeo/gdal/pull/5440.
(This may still mean that we need to add explicit feature control.)

**Comment by BillyONeal** [comment]
> @BillyONeal You added this dependency before the merge, without discussion, so please review. FTR, atlbase.h/lib is used only to get the Windows product UUID in order to cheaply detect AWS EC2 instances. Without it, there is a more expensive network-based check. Cf. [OSGeo/gdal#5440](https://github.com/OSGeo/gdal/pull/5440). (This may still mean that we need to add explicit feature control.)

I added the dependency because your patch hardcoded the "atl found" answer to "yes", so we need to ensure that it's actually true. Adding a feature for that setting seems like it might be reasonable?

**Comment by dg0yt** [comment]
> I added the dependency because your patch hardcoded the "atl found" answer to "yes", so we need to ensure that it's actually true. Adding a feature for that setting seems like it might be reasonable?

Hard-coded "yes"? I don't think so. The problem was that arm64-windows has `atlbase.h` but not the arm64 lib, and similar with another lib for uwp. So there is a hard-coded "no" for arm64 and for uwp, and everything else was left to gdal's configuration.

(And I'm also confused about the usefulness of the atlmfc port here: My problem are platforms which have the headers but still lack the matching libraries.)

**Comment by BillyONeal** [comment]
> Hard-coded "yes"? I don't think so. The problem was that arm64-windows has `atlbase.h` but not the arm64 lib, and similar with another lib for uwp. So there is a hard-coded "no" for arm64 and for uwp, and everything else was left to gdal's configuration.

https://github.com/microsoft/vcpkg/blob/d72783cb3aeddfd667861caef1060e54ca6fa7a9/ports/gdal/0009-atlbase.patch#L9-L13

Maybe hardcoding no was the intent but that code certainly looks like yes? The comment seems to not match what the code does...

> (And I'm also confused about the usefulness of the atlmfc port here: My problem are platforms which have the headers but still lack the matching libraries.)

I mean, I'm not saying the `atlmfc` port is perfect. Only that ports that intend to use `atlmfc` are supposed to declare a dependency on that so that users get some diagnostic as to what they need to install. Maybe we should indeed be checking for presence of the libs etc.

**Comment by dg0yt** [comment]
> Maybe hardcoding no was the intent but that code certainly looks like yes? The comment seems to not match what the code does...

I see... Thanks for the pointer.

@whuaegeanse Did you actually test your PR on a machine without atlmfc? After this discussion, the proposed change wouldn't be enough to resolve the hard dependency.
Do you want to continue this PR? I could create a new PR with a new opt-in port feature this weekend.

**Comment by whuaegeanse** [comment]
> @whuaegeanse Did you actually test your PR on a machine without atlmfc? After this discussion, the proposed change wouldn't be enough to resolve the hard dependency. Do you want to continue this PR? I could create a new PR with a new opt-in port feature this weekend.

1. GDAL has been used in several projects without relying on atlmfc. 
2. I can't test GDAL installed via vcpkg because I have another problem #24035
3. I did't access AWS EC2 via GDAL.

**Comment by JackBoosY** [comment]
At least we can add a feature and don't  set it as a default feature.

**Review by JackBoosY — CHANGES_REQUESTED** [review]
Please bump the port version. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).
Also please run command `vcpkg x-add-version --all` then commit the changes.

**Comment by whuaegeanse** [comment]
> @whuaegeanse Did you actually test your PR on a machine without atlmfc? After this discussion, the proposed change wouldn't be enough to resolve the hard dependency. Do you want to continue this PR? I could create a new PR with a new opt-in port feature this weekend.
@dg0yt 
I don't know how to fix this PR. So please create a new one.

**Comment by dg0yt** [comment]
Oh, I still need to implement this feature...

**Comment by JackBoosY** [comment]
I'm checking whether there is an option to enable/disable this feature.

**Comment by dg0yt** [comment]
> I'm checking whether there is an option to enable/disable this feature.

No, there isn't.

**Comment by dg0yt** [comment]
> > I'm checking whether there is an option to enable/disable this feature.
> 
> No, there isn't.

... in the coming CMake build. Now in nmake, it could work.

**Comment by JackBoosY** [comment]
ATL judgment exists in _gdal/nmake.opt_ line 242:
```
# Set HAVE_ATLBASE_H=NO if atlbase.h header is not available
!IFNDEF HAVE_ATLBASE_H
HAVE_ATLBASE_H=YES
!ENDIF
```
It only controls the declarations and definitions of some functions in the code.

However, `atl*.h` exists in other source files and is not controlled using this macro.
Example:
_gdal/ogr/ogrsf_frmts/arcobjects/ogr_ao.h_:
```cpp

#ifndef OGR_AO_H_INCLUDED
#define OGR_AO_H_INCLUDED

#include "ogrsf_frmts.h"

#include <vector>
#include "cpl_string.h"

//COM ATL Includes
#include <atlbase.h>
#include <atlcom.h>
#include <atlctl.h>
#include <atlstr.h> //CString
...
```

_gdal/port/cpl_aws_win32.cpp_:
```cpp
#include "cpl_port.h"

#if defined(HAVE_ATLBASE_H)

#define _WIN32_DCOM
#include <iostream>
#include <mutex>

#include <comdef.h>
#include <Wbemidl.h>
#include <windows.h>
#include <comutil.h>
#include <atlbase.h>
...
```

They are always built.

Does this mean that atlmfc is a required dependency?

**Comment by dg0yt** [comment]
> Does this mean that atlmfc is a required dependency?

If that were the case, it wouldn't build for uwp in vcpkg CI (and it wouldn't have built for arm64-windows in the past).

> `gdal/ogr/ogrsf_frmts/arcobjects/ogr_ao.h:`

I guess this driver needs a an SDK which isn't available in vcpkg, so it is already disabled.
`gdal/port/cpl_aws_win32.cpp` is all we need to take care of at the moment, and IMO it should be enabled with an opt-in `aws-ec2` feature controlling `HAVE_ATLBASE_H` when calling `nmake`.

**Comment by dg0yt** [comment]
An "aws-ec2-windows" feature is now part of the gdal 3.4.3 update draft: #24353
The atlmfc dependency also broke mingw builds.

**Pull request closed without merging**
