### PR TITLE
[zlmediakit] Fix zlmediakit android

### PR DESCRIPTION
**Pull request by foobra**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] The "supports" clause reflects platforms that may be fixed by this new version.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.~~
- [x] Only one version is added to each modified port's versions file.

@microsoft-github-policy-service agree

### CODE REVIEW

**Comment by BillyONeal** [comment]
This change seems reasonable but I'm not sure how to verify that it is correct. Is `log` supposed to come from the NDK or something else?

Has this fix been submitted upstream?

**Comment by foobra** [comment]
> This change seems reasonable but I'm not sure how to verify that it is correct. Is `log` supposed to come from the NDK or something else?
> 
> Has this fix been submitted upstream?

@BillyONeal When compile Android triplet, one logger file use __android_log_print function which belongs to Android NDK log library , but the origin repo forget to link it.

**Comment by BillyONeal** [comment]
> @BillyONeal When compile Android triplet, one logger file use __android_log_print function which belongs to Android NDK log library , but the origin repo forget to link it.

Thanks! Seems consistent with https://stackoverflow.com/questions/4455941/

**Review by BillyONeal — APPROVED** [review]
Can you submit this upstream?

**Review by JonLiu1993 — APPROVED** [review]

**Comment by foobra** [comment]
> Can you submit this upstream?

Already submit to upstream

**Review by BillyONeal — APPROVED** [review]
Submitted upstream as https://github.com/ZLMediaKit/ZLMediaKit/pull/3670/

**Comment by BillyONeal** [comment]
Thanks for the fix!

**Pull request merged**
