### PR TITLE
[azure-sdk-for-cpp] Upgrade vcpkg manifest files

### PR DESCRIPTION
**Pull request by antkmsft**
Update functions that are now deprecated, update manifest for better feature organization.

### CODE REVIEW

**Comment by antkmsft** [comment]
VcPkg team, please help me - how should I format the file, what is the command line to format it? I can't see what is wrong with the file - is it line endings, or some JSON formatting?

**Review by JackBoosY — CHANGES_REQUESTED** [review]
Please add `"port-version": 1,` to `vcpkg.json`.

**Comment by antkmsft** [comment]
@JackBoosY, after adding `"port-version": 1`, do I need to run `vcpkg x-add-version` with `--overwrite-version`, or without? (currently I ran with it)

**Comment by JackBoosY** [comment]
@antkmsft You need to revert changes in _versions_ and rerun command `x-add-version` : (

**Comment by antkmsft** [comment]
@JackBoosY, got it. It actually makes sense. Thank you! I undone the changes and reran, it was not hard: `git checkout origin/master versions`, and then the usual `vcpkg x-add-version` without `--overwrite-version`.

**Review by JackBoosY — APPROVED** [review]

**Comment by ras0219-msft** [comment]
LGTM, thanks for all the cleanup!

**Pull request merged**
