### PR TITLE
[libnice] Update to 0.1.18

### PR DESCRIPTION
**Pull request by Neumann-A**
- remove from baseline.
- switch to meson. 
depends on #20555 to solve the qtmultimedia regression

### CODE REVIEW

**Comment by Neumann-A** [comment]
Hmm CI logs tell me:
a) Linux pc file for openssl seems to be broken
b) Some linkage issue on osx which requires an extra log CI is not giving me.

**Comment by dg0yt** [comment]
@Neumann-A I can't say for sure. Every project hacks it is own way around issues on some build environment, instead of just using pkg-config. I can check linux later, but my native mingw buildtree is discouraging:
~~~
 $ grep PKG_CHECK buildtrees/*/src/*/configure.ac  | grep "ssl\|crypto"
~~~
(No results)

**Comment by dg0yt** [comment]
On linux, I had one hit: nghttp2.
However, it looks for module "openssl". This module exists in my Ubuntu system, but vcpkg port openssl only creates `libssl.pc` and `libcrypto.pc`.

(The Ubuntu module basically just `Requires: libssl libcrypt`.)

**Comment by JonLiu1993** [comment]
@Neumann-A ,Is this PR being worked on?

**Review by LilyWangLL — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the update!

**Comment by ras0219-msft** [comment]
The openssl pkgconfig dependency should have been fixed by https://github.com/microsoft/vcpkg/pull/20831

**Pull request merged**
