### PR TITLE
[mpg123] Upgrade to 1.26.3-1

### PR DESCRIPTION
**Pull request by evpobr**
Fix invalid `MPG123_API_VERSION` value in `mpg123.h.in` for Windows platform. It was equal to `@API_VERSION@`, now it is read from `configure.ac` and set to correct value.

See also libsndfile/libsndfile#499.

### CODE REVIEW

**Comment by evpobr** [comment]
@PhoebeHui , can you restart checks?

**Comment by evpobr** [comment]
@PhoebeHui , is this my bug?

**Comment by PhoebeHui** [comment]
@evpobr, this is not a bug, since you have a new commit, the baseline hash changed, could you update the baseline version by executing command './vcpkg x-add-version --overwrite-version mpg123', and  then submit the changes again?

**Comment by evpobr** [comment]
@PhoebeHui , ready.

**Review by PhoebeHui — APPROVED** [review]

**Comment by ras0219-msft** [comment]
LGTM, thanks for the fix, looking forward to the libsndfile improvements :)

**Comment by evpobr** [comment]
@PhoebeHui , @ras0219-msft , current stable version is 1.26.5. Should i add 1.26.4 too?

**Comment by PhoebeHui** [comment]
@evpobr, we prefer to update it with lastest stable revision, thanks again for your contribution!

**Pull request merged**
