### PR TITLE
Add toolfile and triplet to build with system provided clang and libc++

### PR DESCRIPTION
**Pull request by kreuzerkrieg**
Add toolfile and triplet to build with system provided `clang` and `libc++`

Related: https://github.com/microsoft/vcpkg/issues/24086

### CODE REVIEW

**Comment by Neumann-A** [comment]
I think there was currently a policy to not accept new community triplets. But people can correct me if I am wrong about that.

**Comment by kreuzerkrieg** [comment]
additional note, not sure there should be any changes to azure ci, maybe additional run for x64-linux-clang? your opinion is important

**Comment by dg0yt** [comment]
> additional note, not sure there should be any changes to azure ci, maybe additional run for x64-linux-clang?

No.

**Comment by BillyONeal** [comment]
I think this is ... dubious given that the resulting software isn't going to work in the vast vast majority of cases given that libc++ isn't link compatible with any system libs. Morever, it's not clear that someone asking for "clang" is going to also be expecting "libc++".

**Pull request closed without merging**
