### PR TITLE
[PCL] Fix pcl

### PR DESCRIPTION
**Pull request by larshg**
**Describe the pull request**

- What does your PR fix? Fixes linking with flann due to #16724

- Which triplets are supported/not supported? Have you updated the CI baseline? 
All triplets.
updated versions/baseline.json .

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)? yes.

### CODE REVIEW

**Comment by JackBoosY** [comment]
Does this PR depends on https://github.com/microsoft/vcpkg/pull/16791 ?

**Comment by larshg** [comment]
Yes, for both to complete successfully - should I include #16791 in this one, to get all build?

**Comment by JackBoosY** [comment]
@larshg  Yes if the changes of these two PRs depend on each other.

**Comment by larshg** [comment]
@JackBoosY #16724 makes PCL and OpenMVC not being build. I have created two PRs to fix those, as you wrote in #16724. Or should I include all changes in the original PR about FLANN, so all is green?

**Comment by JackBoosY** [comment]
@larshg  Yes please. We should make all the pipeline test pass.

**Comment by larshg** [comment]
Closing as it is included in #16724

**Pull request closed without merging**
