### PR TITLE
[libflac] Update to 1.3.3-1

### PR DESCRIPTION
**Pull request by evpobr**
**Describe the pull request**

- What does your PR fix? Fixes issue #

- Which triplets are supported/not supported? Have you updated the CI baseline?

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

### CODE REVIEW

**Review by PhoebeHui — CHANGES_REQUESTED** [review]
Thanks for the PR!

The following regressions caused by the changes, could you have a look?
libflac:arm-uwp
libflac:arm64-windows
aubio:x64-windows-static

**Comment by evpobr** [comment]
Hmm, erros logs are not very informative. Can i have more info?

**Comment by PhoebeHui** [comment]
@evpobr, see the failure, you can also full logs in attachments.
libflac:arm64-windows:
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.25.28610\include\tmmintrin.h(14): fatal error C1189: #error:  This header is specific to X86 and X64 targets

libflac:x64-uwp and libflac:arm-uwp:
  C:\agent\_work\1\s\buildtrees\libflac\src\34fa315125-b626d87b3a\src\utils\flactimer\main.cpp(120,2): error C3861: 'GetStartupInfoA': identifier not found [C:\agent\_work\1\s\buildtrees\libflac\x64-uwp-dbg\src\utils\flactimer\flactimer.vcxproj]

aubio:x64-windows-static:
libsndfile.lib(flac.c.obj) : error LNK2019: unresolved external symbol __imp_FLAC__stream_decoder_new referenced in function flac_open
libsndfile.lib(flac.c.obj) : error LNK2019: unresolved external symbol __imp_FLAC__stream_decoder_delete referenced in function flac_close
libsndfile.lib(flac.c.obj) : error LNK2019: unresolved external symbol __imp_FLAC__stream_decoder_set_metadata_respond_all referenced in function flac_open
libsndfile.lib(flac.c.obj) : error LNK2019: unresolved external symbol 
...
[install-x64-uwp-dbg-out.log](https://github.com/microsoft/vcpkg/files/4597188/install-x64-uwp-dbg-out.log)
[install-x64-windows-static-rel-out.log](https://github.com/microsoft/vcpkg/files/4597194/install-x64-windows-static-rel-out.log)
[install-arm64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4597197/install-arm64-windows-dbg-out.log)

**Comment by evpobr** [comment]
Bugs are fixed, waiting for xiph/flac#210.

**Comment by evpobr** [comment]
It is ready. Tests fail, don't know why.

**Comment by PhoebeHui** [comment]
@evpobr, the previous failures in CI doesn't related to your change, it's infrastructure issue that fixed currently, I have rerun the PR, let's wait for the results.

**Review by PhoebeHui — APPROVED** [review]
The CI test pass!

**Comment by strega-nil** [comment]
Thanks @evpobr !

I just want to write this down for posterity: you may see that 1.3.3 and this commit are about 6 months apart, but the only changes made in between here are cleanups:

* `std::`-ify a bunch of C library stuff
* C-cast -> `static_cast` or `reinterpret_cast`
* build system changes
* `unsigned` -> `uint32_t`
* removing UB in a shift
* better support for powerPC and Windows
* Change out `cos(double)` for `cosf(float)` in C
* Correct `%d` to `%u` in `printf`

These are all completely benign, imo, so I'm okay with still calling this 1.3.3 with bugfixes.

**Comment by evpobr** [comment]
@strega-nil 

> These are all completely benign, imo, so I'm okay with still calling this 1.3.3 with bugfixes.

The main goal was [ce6dd6b](https://github.com/xiph/flac/commit/ce6dd6b5732e319ef60716d9cc9af6a836a4011a) - upstream `CMakeLists.txt`.

**Comment by strega-nil** [comment]
@evpobr yeah, absolutely; just wanted to document the changes that made it in between 1.3.3 and ce6dd6b :)

**Pull request merged**
