### PR TITLE
[libjbig] add version 2.1

### PR DESCRIPTION
**Pull request by Mixaill**

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks!

Should this be named jbigkit?

**Comment by Mixaill** [comment]
Looks like both variants are acceptable.

Debian-based -- **libjbig**: https://packages.debian.org/sid/libjbig-dev
Fedora -- **jbigkit**: https://admin.fedoraproject.org/pkgdb/package/rpms/jbigkit/

**Comment by ras0219-msft** [comment]
It looks like the debian source package is also called jbigkit: https://packages.debian.org/source/sid/jbigkit

I think we should name the package that since that is the upstream project name. Otherwise, this looks good to me.

**Comment by Mixaill** [comment]
>It looks like the debian source package is also called jbigkit
It is package with source code.

Package with library called **libjbig0** and package with development files called **libjbig-dev**

Anyway, no big difference to me, I'll rename it.

**Comment by ras0219-msft** [comment]
Thanks for making the rename (and the PR as well, of course)!

**Pull request merged**
