### PR TITLE
[sqlite3] Fix typo for the Windows build

### PR DESCRIPTION
**Pull request by plq**
**Describe the pull request**

- #### What does your PR fix?
  Fixes a small (but critical?) typo in sqlite build script

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  no change to support status, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  sure

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

### CODE REVIEW

**Comment by Cheney-W** [comment]
Please modify the value of `port-version` in vcpkg.json as 2.

**Comment by plq** [comment]
> Please modify the value of `port-version` in vcpkg.json as 2.

Done

**Review by Cheney-W — APPROVED** [review]

**Comment by dg0yt** [comment]
How is the macro used? Would it make sense to burn it into the installed header?

**Comment by plq** [comment]
> How is the macro used? Would it make sense to burn it into the installed header?

I don't know, just here to fix the typo

**Pull request merged**
