### PR TITLE
[libvpx] Copy debug symbols

### PR DESCRIPTION
**Pull request by chrisaverage**

### CODE REVIEW

**Comment by NancyLi1013** [comment]
Hi @chrisaverage, thanks for your PR. I see this port failed on x64-uwp. Please refer to the following attachment to take a look.
[libvpx.zip](https://github.com/microsoft/vcpkg/files/3245562/libvpx.zip)

**Comment by chrisaverage** [comment]
Thanks for the logs. I wasn't sure what's going on.
```
error: failed to update mingw32 (unable to lock database)
error: failed to update mingw64 (unable to lock database)
error: failed to update msys (unable to lock database)
error: failed to synchronize all databases
```

It seems to error out on getting dependencies, so it has nothing to do with my change, which adds a post build install step. It also builds fine locally on my machine, so I don't think there's anything  I can do on my end to fix that.

**Comment by grdowns** [comment]
Thanks for the  PR, @chrisaverage! The msys problem is part of a known issue (#6688). Once the fix for it goes through in #6729 we can get meaningful results from the CI system for this PR. Thanks for your patience :smile:

**Comment by grdowns** [comment]
#6729 has gone through and I've retriggered the build to test this port, which has passed. Thanks for the fix, @chrisaverage!

**Pull request merged**
