### PR TITLE
[prometheus-cpp] Update to version 0.12.1

### PR DESCRIPTION
**Pull request by gjasny**
Update prometheus-cpp to 0.12.0. Locally tested on macOS.

### CODE REVIEW

**Comment by gjasny** [comment]
Version 0.12.0 did not compile with C++17 on latest VS2019.

**Review by JonLiu1993 — CHANGES_REQUESTED** [review]
configure_file(${SOURCE_PATH}/LICENSE ${CURRENT_PACKAGES_DIR}/share/prometheus-cpp/copyright COPYONLY) should be configure_file(${SOURCE_PATH}/LICENSE ${CURRENT_PACKAGES_DIR}/share/${PORT}/copyright COPYONLY)

**Comment by JonLiu1993** [comment]
@gjasny ,Have you tested all these features?

**Comment by gjasny** [comment]
Thanks for the review. I updated the portfile and also tested the feature flags permutations.

**Comment by ras0219-msft** [comment]
Awesome, thanks for the update!

**Pull request merged**
