### PR TITLE
[arrow] Fix port-version for new version

### PR DESCRIPTION
**Pull request by FrankXie05**
Modify the `port-version` to the correct value for the new version.

Due to https://github.com/microsoft/vcpkg/pull/35026
Realted PR https://github.com/microsoft/vcpkg/pull/35492
https://github.com/microsoft/vcpkg/blob/b051745c68faa6f65c493371d564c4eb8af34dad/versions/a-/arrow.json#L6

### CODE REVIEW

**Comment by FrankXie05** [comment]
cc @aleradamantis99 @jimwang118

**Comment by dg0yt** [comment]
Just leave as is. We are at port-version 1 now, and we can only move forward. #35492 needs to bump the port-version to 2.

**Comment by FrankXie05** [comment]
It shuold be `0` for update.

**Comment by dg0yt** [comment]
> It shuold be `0` for update.

But it is too late now, 1 was merged. There is no benefit from inserting 0, but there is damage from creating ambiguity about 1.

**Pull request closed without merging**
