### PR TITLE
[vcpkg baseline] Retrigger failed ports in baseline

### PR DESCRIPTION
**Pull request by PhoebeHui**
Related to https://github.com/microsoft/vcpkg/pull/7733  https://github.com/microsoft/vcpkg/pull/11277 https://github.com/microsoft/vcpkg/pull/11637

Retrigger failed ports, verified these ports locally, all passed.

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by PhoebeHui** [comment]
@BillyONeal, geographiclib:x64-windows-static failed to downlaod source, I checked the sourceforge, we could download the source successfully, but it's very slow, could you help take a look? these ports block CI testing with relate PRs.

-- Downloading https://sourceforge.net/projects/graphicsmagick/files/graphicsmagick/1.3.35/GraphicsMagick-1.3.35-windows-source.7z... Failed. Status: 7;"Couldn't connect to server"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):
      
      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

**Comment by BillyONeal** [comment]
I don't understand this change: the baseline (the CI build I mean) is currently green/passing.

We should not be forcing end users to rebuild stuff in `vcpkg upgrade` to fix transient issues in our own CI system.

**Comment by PhoebeHui** [comment]
@BillyONeal, these ports failed in PR https://github.com/microsoft/vcpkg/pull/7733 https://github.com/microsoft/vcpkg/pull/11277 https://github.com/microsoft/vcpkg/pull/11637 are our baseline issue, they are not related to the auther's changes, rerun the PR doesn't fix the issue, so I retriggered these ports.

**Comment by BillyONeal** [comment]
@PhoebeHui If the problem is that a tombsone was created in those users' PR that invalidates results, the user can push an update to their PR that changes `clean-tombstones-first` and then change it back or rebase that change out: https://github.com/microsoft/vcpkg/blob/7960648b4d922888e7a5c2a4c3ae9e153eab0374/scripts/azure-pipelines/azure-pipelines.yml#L7

For you folks who have access to the web interface I thought you were able to change that setting when queueing a build there, but I just tested and that doesn't seem to work :(

**Comment by BillyONeal** [comment]
https://github.com/microsoft/vcpkg/pull/12000 <-- I'm trying to fix the web interface thing over here

**Comment by PhoebeHui** [comment]
Yes, remove tomestone doesn't work now, that why I summited this PR☺.

Currently, it doesn't work for geographiclib:x64-windows-static, it failed to download source even I retriggered it, that means it also fail when the author remove the tomestone, It might need to archive the source manually, since the server is very slow yesterday, hopes it's better today☺.

**Comment by BillyONeal** [comment]
Right, if the problem is that the server giving us the sources is bad there's no guarantee that a rerun will help

**Comment by BillyONeal** [comment]
Given the clean-every-CI change on tombstones I would prefer to limit this to geographiclib and polyclipping since those have meaningful changes.

**Review by JackBoosY — APPROVED** [review]

**Comment by PhoebeHui** [comment]
@BillyONeal, thanks for your help!

**Pull request merged**
