### PR TITLE
[fontconfig] Update to 2.13.94

### PR DESCRIPTION
**Pull request by ghost**
**Describe the pull request**

- #### What does your PR fix?  
  Updates fontconfig to 2.13.84

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by Lucius-Q-User** [comment]
Will conflict with #18625 but one can be rebased on top of the other depending on the orders they will get merged in.

**Comment by Neumann-A** [comment]
2.13.94 is not a stable release.

**Comment by JackBoosY** [comment]
2.13.94 was published one week ago.

**Comment by Neumann-A** [comment]
> 2.13.94 was published one week ago.

 2.13.9x releases are prereleases for 2.14 
e.g.
> Version 2.13.91 (2.14 RC1)

from the readme in the repo

From https://www.freedesktop.org/wiki/Software/fontconfig/
> The current stable series is 2.13.1. All releases are available in the release directory.

**Pull request closed without merging**
