### PR TITLE
[log4cpp] Change to official upstream source

### LINKED ISSUE #31273: [log4cpp] incorrect upstream & version
https://stackoverflow.com/questions/76091004/does-vcpkg-incorrectly-delivers-an-old-version-of-log4cpp

From that post it seems the current port should be `orcos-log4cpp` while the correct upstream for `log4cpp` is https://sourceforge.net/projects/log4cpp/

https://repology.org/project/log4cpp/versions
https://repology.org/project/log4cpp-orocos/versions

Fixing this probably requires purging the whole version database for `log4cpp`

### PR DESCRIPTION
**Pull request by jimwang118**
Fixes https://github.com/microsoft/vcpkg/issues/31273

Change the source of log4cpp from https://github.com/orocos-toolchain/log4cpp to https://sourceforge.net/projects/log4cpp/.
- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [X] SHA512s are updated for each updated download
- [X] The "supports" clause reflects platforms that may be fixed by this new version
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [X] Any patches that are no longer applied are deleted from the port's directory.
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by JonLiu1993** [comment]
Pinging @jimwang118 for response. Is work still being done for this PR?

**Review by JonLiu1993 — DISMISSED** [review]

**Comment by BillyONeal** [comment]
Not sure how we should address the versioning situation, given that this makes the version number go backwards. Will ask around... we might be forced to leave this as the taken name, delist it, and add log4cpp-sourceforge or something like that instead.

**Comment by BillyONeal** [comment]
Looks like we've been using a funny source since all the way in the beginning in https://github.com/microsoft/vcpkg/pull/7433/

**Review by BillyONeal — APPROVED** [review]

**Review by JonLiu1993 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks!

**Pull request merged**
