### PR TITLE
[WIP][vtk] add the option -DModule_vtkGUISupportMFC=ON

### PR DESCRIPTION
**Pull request by MouhammadEV**

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for the PR!

When I build vtk in this PR for x64-windows or x64-windows-static, I get the following error:

>C:\vsts\_work\1\s\buildtrees\vtk\src\v8.1.0-3e8db5da7b\GUISupport\MFC\vtkMFCWindow.cpp(195): error C2661: 'vtkOpenGLRenderWindow::GetPixelData': no overloaded function takes 5 arguments

This is with the latest VS2017.

Could you take a look at this or confirm that it doesn't repro for you? You may also want to purge the `buildtrees\vtk\` directory just to make sure you're working from clean sources.

**Comment by MouhammadEV** [comment]
Yes .. I got also this error while trying to compile the vtk library.
However this problem was solved in the new version (v8.1.2). So I think the portfile of the vtk library should  be edited to be able to download the new version.

**Comment by ras0219-msft** [comment]
I definitely can't merge this without `vcpkg install vtk` building cleanly; I think this means we need to wait on this PR until 8.2.0 is fully released.

**Comment by luzpaz** [comment]
Any progress on this ? Thanks!

**Comment by Rastaban** [comment]
vtk had been updated in vcpkg to 8.2.0, Resolved merge conflict.

**Pull request merged**
