### PR TITLE
[sdl2] Update to 2.0.14

### PR DESCRIPTION
**Pull request by RT2Code**
https://discourse.libsdl.org/t/sdl-2-0-14-released/28470/2

I updated patches as needed and removed those who were merged upstream. I also had to remove the sensor api from UWP builds because from what I understood it isn't available on this platform.

I was able to build the vulkan feature with success on the following platforms :
- arm-uwp
- arm64-windows
- x64-uwp
- x64-windows
- x64-windows-static
- x86-windows

### CODE REVIEW

**Comment by JonLiu1993** [comment]
@RT222 ,Can you take a look?
````
2020-12-31T01:05:32.1320130Z ##[section]Starting: Create Diff
2020-12-31T01:05:32.1407254Z ==============================================================================
2020-12-31T01:05:32.1407696Z Task         : PowerShell
2020-12-31T01:05:32.1408013Z Description  : Run a PowerShell script on Linux, macOS, or Windows
2020-12-31T01:05:32.1408311Z Version      : 2.179.1
2020-12-31T01:05:32.1408569Z Author       : Microsoft Corporation
2020-12-31T01:05:32.1408937Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
2020-12-31T01:05:32.1409340Z ==============================================================================
2020-12-31T01:05:32.7269050Z Generating script.
2020-12-31T01:05:32.7308365Z Formatted command: . 'C:\a\1\s\scripts\azure-pipelines\Create-FormatDiff.ps1' -DiffFile C:\a\1\a\format.diff
2020-12-31T01:05:32.7563265Z ========================== Starting Command Output ===========================
2020-12-31T01:05:32.7738968Z ##[command]"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'C:\a\_temp\5334a638-5914-49f0-a9bf-9ff9cfb10858.ps1'"
2020-12-31T01:05:34.5700213Z C:\a\1\s\scripts\azure-pipelines\Create-FormatDiff.ps1 : The formatting of the files in the repo were not what we expected,
2020-12-31T01:05:34.5701198Z or the documentation was not regenerated.
2020-12-31T01:05:34.5701684Z Please access the diff from format.diff in the build artifacts,
2020-12-31T01:05:34.5702159Z and apply the patch with `git apply`
2020-12-31T01:05:34.5702734Z At C:\a\_temp\5334a638-5914-49f0-a9bf-9ff9cfb10858.ps1:3 char:1
2020-12-31T01:05:34.5703452Z + . 'C:\a\1\s\scripts\azure-pipelines\Create-FormatDiff.ps1' -DiffFile  鈥�
2020-12-31T01:05:34.5704035Z + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-12-31T01:05:34.5704643Z + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
2020-12-31T01:05:34.5705281Z + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Create-FormatDiff.ps1
2020-12-31T01:05:34.6423360Z ##[error]PowerShell exited with code '1'.
2020-12-31T01:05:34.6670481Z ##[section]Finishing: Create Diff
````

**Comment by RT222** [comment]
Now the following ports fail to build :

- sdl2-image
- sdl2-mixer:x64-windows
- sdl2-ttf:x64-windows
- sdl2-net:x64-windows
- smpeg2:x64-windows

It only happens when trying to build with dynamic linkage. I'll try to fix it but any help would very much appreciated. :)

**Comment by crackedmind** [comment]
according to this patch https://github.com/spurious/SDL-mirror/commit/c7d1a55ce471ab8692a9217be59bf395eab77186#diff-bd5d6f5d531b85b28099385f15e99168b6e1a42f7519b35111d89fcd3bdda13e and removing ports/sdl2/no-propagate-shared-link-options.patch 

sdl2-image sdl2-mixer sdl2-ttf sdl2-net smpeg2 CMakeLists.txt need replace this
`set_target_properties(smpeg2 PROPERTIES DEFINE_SYMBOL SDL2_EXPORTS)`
with
`set_target_properties(smpeg2 PROPERTIES DEFINE_SYMBOL DLL_EXPORT)`

**Comment by RT222** [comment]
Thank a lot, I had pinpointed the problem to this line, but I couldn't find the new symbol name. It's working fine now. :)

**Review by JonLiu1993 — APPROVED** [review]

**Comment by JonLiu1993** [comment]
> Thank a lot, I had pinpointed the problem to this line, but I couldn't find the new symbol name. It's working fine now. :)

Thanks for your contribution

**Pull request merged**
