### PR TITLE
[cmake] update to 3.19.2

### PR DESCRIPTION
**Pull request by JackBoosY**
Update to 3.19.1

### CODE REVIEW

**Comment by traversaro** [comment]
In CMake 3.19.0 there is a regression that may prevent to build LLVM, and will be fixed in CMake 3.19.1 : https://gitlab.kitware.com/cmake/cmake/-/issues/21469 .

**Comment by JackBoosY** [comment]
@traversaro 3.19.1 is not published.

**Comment by traversaro** [comment]
> 
> 
> @traversaro 3.19.1 is not published on github.

Yes, sorry for not being clear, but I meant that it **will** be fixed in 3.19.1 once it is released (in the future). Homebrew backported the fix for the time being, see https://github.com/Homebrew/homebrew-core/pull/65416 .

**Comment by JackBoosY** [comment]
@traversaro So this PR will wait for 3.19.1 published.

**Comment by traversaro** [comment]
> 
> 
> @traversaro So this PR will wait for 3.19.1 published.

CMake 3.19.1 was released today: https://discourse.cmake.org/t/cmake-3-19-1-available-for-download/2228 .

**Comment by JackBoosY** [comment]
Since there are many same regressions about cmake, I will continue this PR after https://discourse.cmake.org/t/error-when-installing-targets-and-exports-in-3-19-1/2245/6 discussion finished.

**Comment by JackBoosY** [comment]
The official fixed this issue, waiting for the new version publish.

**Comment by BillyONeal** [comment]
@JackBoosY Why does this require a VM update?

**Comment by JackBoosY** [comment]
@BillyONeal  I updated the cmake path in pipeline script on Windows.

**Comment by BillyONeal** [comment]
@JackBoosY You don't need to wait for a VM update for that, since vcpkg itself acquires cmake and it doesn't come from the VM images.

**Review by BillyONeal — APPROVED** [review]

**Comment by JackBoosY** [comment]
```
LINK : fatal error LNK1201: error writing to program database 'D:\buildtrees\itk\x86-windows-dbg\bin\ITKQuadEdgeMesh-5.1.pdb'; check for insufficient disk space, invalid path, or insufficient privilege
```
Should be a disk space issue.

**Comment by BillyONeal** [comment]
> ```
> LINK : fatal error LNK1201: error writing to program database 'D:\buildtrees\itk\x86-windows-dbg\bin\ITKQuadEdgeMesh-5.1.pdb'; check for insufficient disk space, invalid path, or insufficient privilege
> ```
> 
> Should be a disk space issue.

I'm not sure where you saw this output but if there were disk space issues we would see them in the reports. For example x64-windows-static in the current build says:

```
Disk Label             Size    Free Space
---- -----             ----    ----------
C:   Windows           127 GiB 86 GiB
D:   Temporary Storage 400 GiB 390 GiB
E:                     0 B     0 B
```

before the build and

```
Disk Label             Size    Free Space
---- -----             ----    ----------
C:   Windows           127 GiB 86 GiB
D:   Temporary Storage 400 GiB 313 GiB
E:                     0 B     0 B
```

at the end of the build.

**Comment by JackBoosY** [comment]
@BillyONeal Maybe because I reran the test.

**Comment by JackBoosY** [comment]
`libsigcpp:x86-windows`: download issue. ITK regression did not appear.
Rerun the pipeline test now.

**Comment by BillyONeal** [comment]
Robert looked at this and was OK with it but doesn't like the hdf5 related changes. I replied that these are similar to hdf5 related changes we have all over the rest of the tree and he was OK with that. I filed https://github.com/microsoft/vcpkg/issues/15357 to track that work.

Will merge this once PR build passes.

**Pull request merged**
