### PR TITLE
[h5py-lzf] Add new port

### PR DESCRIPTION
**Pull request by zi-m**
Home: http://www.h5py.org/lzf/
Repo: https://github.com/h5py/h5py/tree/master/lzf

From https://support.hdfgroup.org/services/filters.html:
> LZF can be used to compress any data type, and requires no compile-time or run-time configuration. HDF5 versions 1.6.5 through 1.8.3 are supported. The filter is written in C and **_can be included directly in C or C++ applications_**; it has no external dependencies. The license is 3-clause BSD (virtually unrestricted, including commercial applications).

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for the PR!

Could you please add a comment explaining why `0001-disable-H5PLget_plugin-api.patch` is needed?

**Comment by LilyWangL** [comment]
Pinging @zi-m

**Comment by zi-m** [comment]
> Could you please add a comment explaining why 0001-disable-H5PLget_plugin-api.patch is needed?


From [doc](https://support.hdfgroup.org/HDF5/doc/Advanced/DynamicallyLoadedFilters/HDF5DynamicallyLoadedFilters.pdf):
> 4. The two functions necessary for the HDF5 Library to find the correct type of the plugin library
> while loading it at runtime and to get information about the filter function:
> H5PL_type_t H5PLget_plugin_type(void);
> const void* H5PLget_plugin_info(void);

There are a lot of [filters](https://support.hdfgroup.org/services/filters.html): [lz4](https://github.com/nexusformat/HDF5-External-Filter-Plugins/blob/cabe5fd0aa3402bb742016a68acfc1def63210bd/LZ4/src/H5Zlz4.c#L49), [zstd](https://github.com/aparamon/HDF5Plugin-Zstandard/blob/d5afdb5f04116d5c2d1a869dc9c7c0c72832b143/zstd_h5plugin.h#L17), [blosc](https://github.com/Blosc/hdf5-blosc/blob/bd8ee59708f366ac561153858735165d3a543b18/src/blosc_plugin.h#L28), etc.

So **H5PLget_plugin*** couses problems in case of static linkage.

**Comment by strega-nil** [comment]
Awesome, thanks @zi-m :)

**Pull request merged**
