### PR TITLE
Fixed filesystem for uwp builds of Boost

### PR DESCRIPTION
**Pull request by stammen**
This PR adds UWP support for building Boost filesystem which is currently omitted from UWP builds.

### CODE REVIEW

**Comment by ras0219-msft** [comment]
@stammen Sorry for the long delay here; I pushed a fixup and rebase to dev/roschuma/3633, however it appears to be failing for all the non-uwp windows systems.

Could you take a look?

**Comment by stammen** [comment]
I will take a look. Thanks.

**Comment by dan-shaw** [comment]
I’m going to close this PR because it’s been a long time since any update has been made. If this is something you’d like to see merged and work is being done, please reopen.

**Pull request closed without merging**
