### PR TITLE
[vcpkg] Prefer STREQUAL over MATCHES

### PR DESCRIPTION
**Pull request by SunBlack**
Avoid using CMake's well-known slow regex engine if it is not necessary

Used the regex `if.*MATCHES "\^[\w\s]*\$"` to find all occurrences.

### CODE REVIEW

**Comment by JackBoosY** [comment]
I don't think we're using regex because it's too slow.
cc @strega-nil-ms

**Review by JackBoosY — APPROVED** [review]
Since it's full keyword regex. I think that's correct.

**Review by ras0219-msft — APPROVED** [review]

**Comment by BillyONeal** [comment]
These changes are all improvements, but not worth forcing everyone to rebuild the world over, as an edit to `ports.cmake` will do. As a result, we have tagged this with "world-rebuild" to potentially roll up into other changes that would affect that file.

However, the changes to `buildsystems/vcpkg.cmake` will not cause a world rebuild, so if you want to create a second PR with only those changes because you want those effects early, that would be OK. (Of course, given that this is just a code cleanup I doubt it's worth it to you)

**Comment by BillyONeal** [comment]
Sorry, I've just been informed the correct tag is "next-rollup" rather than "world-rebuild"; the latter is about PRs in progress while this PR is otherwise ready-to-merge/

**Comment by ras0219-msft** [comment]
LGTM, thanks for the improvement!

**Pull request merged**
