### PR TITLE
[vcpkg build] fix build command

### LINKED ISSUE #12055: Create Package Example fails with 'Value was Null"
## Description
Run the basic vcpkg git clone, bootstrap
Follow the create package example: https://vcpkg.readthedocs.io/en/latest/examples/packaging-zipfiles/
at the step of `vcpkg build zlib2` you recieve error 'Value was null` with nothing else useful for diagnostics.

**Environment**
- OS: Windows v2004 19041.329
- Compiler: Vcpkg package management program version 2020.02.04-nohash

**To Reproduce**
1. .\vcpkg create zlib2 http://zlib.net/zlib-1.2.11.tar.gz zlib-1.2.11.zip
2. .\vcpkg.exe edit zlib2
3. .\vcpkg build zlib2

emits error "Value was null"

**Expected behavior**
Should work, as it's the example -- this happens with every project I start now.

**Failure logs** 
-(please attached failure logs)

**Additional context**
see below - note that i've done this on a fresh machine too and same result. 

image

The same exact failure happens in wsl2 👍 

```
Resolving deltas: 100% (50382/50382), done.
Updating files: 100% (4975/4975), done.
cicorias@DESKTOP-BE6CJBJ:/e/temp$ cd vcpkg/
cicorias@DESKTOP-BE6CJBJ:/e/temp/vcpkg$ ./bootstrap-vcpkg.sh
Downloading cmake...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   639  100   639    0     0   7261      0 --:--:-- --:--:-- --:--:--  7344
100 38.7M  100 38.7M    0     0  22.1M      0  0:00:01  0:00:01 --:--:-- 25.7M
Downloading cmake... done.
Extracting cmake...
Extracting cmake... done.
Downloading ninja...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   624  100   624    0     0   2971      0 --:--:-- --:--:-- --:--:--  2957
100 99857  100 99857    0     0   218k      0 --:--:-- --:--:-- --:--:--  218k
Downloading ninja... done.
Extracting ninja...
Extracting ninja... done.
-- The CXX compiler identification is GNU 9.3.0
-- Check for working CXX compiler: /usr/bin/g++-9
-- Check for working CXX compiler: /usr/bin/g++-9 - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting the C++ standard library
-- Detecting the C++ standard library - libstdc++
-- Detecting how to use the C++ filesystem library
-- Detecting how to use the C++ filesystem library - <filesystem>
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: /e/temp/vcpkg/toolsrc/build.rel
[0/2] Re-checking globbed directories...
[77/77] Linking CXX executable vcpkg
Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md
cicorias@DESKTOP-BE6CJBJ:/e/temp/vcpkg$ ./vcpkg create dotenv https://github.com/cicorias/cpp-dotenv/archive/v0.1.0.tar.gz dotenv-0.1.0.zip
-- Downloading https://github.com/cicorias/cpp-dotenv/archive/v0.1.0.tar.gz...
-- Generated portfile: /e/temp/vcpkg\ports\dotenv\portfile.cmake
-- Generated CONTROL: /e/temp/vcpkg\ports\dotenv\CONTROL
-- To launch an editor for these new files, run
--     .\vcpkg edit dotenv
cicorias@DESKTOP-BE6CJBJ:/e/temp/vcpkg$ vc
vcamp120.dll              vcamp140.dll              vccorlib140d.dll          vcomp100.dll              vcomp140d.dll             vcruntime140_1d.dll       vcruntime140_clr0400.dll  vcruntime140d.dll
vcamp140d.dll             vccorlib120.dll           vccorlib140.dll           vcomp120.dll              vcomp140.dll              vcruntime140_1.dll        vcruntime140_cor3.dll     vcruntime140.dll
cicorias@DESKTOP-BE6CJBJ:/e/temp/vcpkg$ ./vcpkg build dotenv
Value was null
cicorias@DESKTOP-BE6CJBJ:/e/temp/vcpkg$ ./vcpkg create zlib2 http://zlib.net/zlib-1.2.11.tar.gz zlib-1.2.11.zip
-- Downloading http://zlib.net/zlib-1.2.11.tar.gz...
-- Generated portfile: /e/temp/vcpkg\ports\zlib2\portfile.cmake
-- Generated CONTROL: /e/temp/vcpkg\ports\zlib2\CONTROL
-- To launch an editor for these new files, run
--     .\vcpkg edit zlib2
cicorias@DESKTOP-BE6CJBJ:/e/temp/vcpkg$ ./vcpkg build zlib2
Value was null
cicorias@DESKTOP-BE6CJBJ:/e/temp/vcpkg$

```

### PR DESCRIPTION
**Pull request by strega-nil**
Fixes #12055

### CODE REVIEW

**Review by vicroms — APPROVED** [review]

**Review by BillyONeal — APPROVED** [review]
Can you add a smoke test to prevent future regressions? (Example https://github.com/microsoft/vcpkg/pull/11842/files#diff-0ea0efced14b52175edfd555a0d338c5R10 )

**Comment by PhoebeHui** [comment]
Test this changes, it works, the CI failed due to baseline failures that we already have PR to fix it.

**Review by BillyONeal — APPROVED** [review]
Approve HARDER

**Comment by cicorias** [comment]
thanks so much for the rapid response!

**Pull request merged**
