### PR TITLE
[libde265] Add new port

### PR DESCRIPTION
**Pull request by NancyLi1013**
`libde265` is an open source implementation of the h.265 video codec.
This port currently doesn't support `arm, arm64, uwp`.

Related issue #5973

No feature need to test.

### CODE REVIEW

**Comment by NancyLi1013** [comment]
The failure on `osx` is due to:
```
/Users/vagrant/azure_agent/_work/2/s/buildtrees/libde265/src/v1.0.3-fbbd68a8ca/libde265/image.cc:75:27: error: use of undeclared identifier 'memalign'
  uint8_t* p = (uint8_t *)ALLOC_ALIGNED_16(stride * height + MEMORY_PADDING);
```

**Review by JackBoosY — APPROVED** [review]

**Comment by NancyLi1013** [comment]
Since this port is failing in CI system on osx. I added unsupported message for the port.

**Review by dan-shaw — APPROVED** [review]

**Comment by ras0219-msft** [comment]
Please modify ci.baseline.txt to account for the windows failures

**Comment by NancyLi1013** [comment]
Please feel free to reopen this PR if you need it.

**Pull request closed without merging**
