### PR TITLE
[qtwebengine] fix debug builds

### PR DESCRIPTION
**Pull request by Neumann-A**
simply fix debug builds by applying the same change to `LogStreamer<V,T,Ts...>`

### CODE REVIEW

**Comment by carsten-grimm-at-ipolog** [comment]
@Neumann-A While you are working on this, could you check if the binaries for the debug build are copied into the right directories? I seem to remember that I was missing a debug version of the QtWebEngineProcess executable. I was unable to pursue the matter, due to the other build error. 

If this is out of scope for this pull request, I can check if the issue still exists once I can build the port and create a separate issue, if need be. Thank you.

**Comment by Neumann-A** [comment]
Vcpkg generally tries to only keep release versions of executables around. Is the debug version really needed?

**Comment by carsten-grimm-at-ipolog** [comment]
> Vcpkg generally tries to only keep release versions of executables around. Is the debug version really needed?

For our use case, yes. We have tried to debug our application with the release build of the qt web engine process, but we could not get that to work. 

If it is too much of a hassle, we can manually copy the debug binaries from the build tree to the respective folders, but it would be nice if we could skip that step.

**Comment by dg0yt** [comment]
Debug executables are ultra-heavy for static triplets.

> is the debug version really needed?

**Comment by Neumann-A** [comment]
Qtwebengine only allows dynamic builds. Otherwise you'll get into symbol hell due to all the vendored third party libs in chromium.

**Comment by Neumann-A** [comment]
@carsten-grimm-at-ipolog: Yeah the debug exe gets installed however it gets removed by `vcpkg_copy_tools`. So it is definitely out of scope for this PR.

**Comment by carsten-grimm-at-ipolog** [comment]
> @carsten-grimm-at-ipolog: Yeah the debug exe gets installed however it gets removed by `vcpkg_copy_tools`. So it is definitely out of scope for this PR.

Thank you for taking the time to look into this and thank you for the insight. This might help us build a better workaround on our end.

**Comment by BillyONeal** [comment]
https://github.com/microsoft/vcpkg/pull/35640 is testing with the updated compiler

**Pull request closed without merging**
