### PR TITLE
[google-cloud-cpp] update to v2.17.0#2

### PR DESCRIPTION
**Pull request by dbolduc**
Removes `debugger`, `gameservices`, `iot`. These features were deprecated and removed upstream.

Fixes
- `iam`, `policytroubleshooter` by adding `iam_v2`
- `appengine`, `logging`, `servicecontrol` by adding `logging_type`
- `compute` by adding `compute_protos`

Tested with:
```
./vcpkg install 'google-cloud-cpp[*]'

GOOGLE_CLOUD_CPP=... # e.g. ${HOME}/code/git/google-cloud-cpp

cmake -S ${GOOGLE_CLOUD_CPP}/google/cloud/compute/quickstart -B .test-compute --toolchain $PWD/scripts/buildsystems/vcpkg.cmake && cmake --build .test-compute

cmake -S ${GOOGLE_CLOUD_CPP}/google/cloud/iam/quickstart -B .test-iam --toolchain $PWD/scripts/buildsystems/vcpkg.cmake && cmake --build .test-iam

cmake -S ${GOOGLE_CLOUD_CPP}/google/cloud/policytroubleshooter/quickstart -B .test-policytroubleshooter --toolchain $PWD/scripts/buildsystems/vcpkg.cmake && cmake --build .test-policytroubleshooter
```

---

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by jimwang118** [comment]
The following error occurred during local testing.

`F:\google-cloud-cpp\buildtrees\google-cloud-cpp\src\v2.17.0-42b8e1a9bc.clea
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/13067363/install-x64-windows-dbg-out.log)
n\google\cloud\compute\global_public_delegated_prefixes\v1\global_public_delegated_prefixes_connection_idempotency_policy.cc : fatal error C1083: Cannot open compiler generated file: '': Invalid argument`
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/13067385/install-x64-windows-dbg-out.log)

**Comment by dbolduc** [comment]
> The following error occurred during local testing.

Hey @jimwang118, thanks for testing.

This error seems to come from the filepath being too long for the MSVC compiler. Is there a best practice to workaround this issue? Do we have to just make the names shorter?

**Comment by dbolduc** [comment]
@jimwang118 I disabled the library that was breaking the build on Windows. Please take another look.

**Comment by jimwang118** [comment]
I tested it under local Linux and got the following error.
`/usr/include/c++/9/type_traits:883:12: error: default member initializer for ‘grpc_core::XdsListenerResource::DownstreamTlsContext::require_client_certificate’ required before the end of its enclosing class`
[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/13212674/install-x64-linux-dbg-out.log)

**Comment by dbolduc** [comment]
> `grpc_core`

This error was in building `grpc`. It doesn't seem related to `google-cloud-cpp`, or any changes in this PR.

Maybe it is a compiler bug? Some googling revealed: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=88165

Can we go ahead with this PR?

**Comment by jimwang118** [comment]
Usage test pass with following triplets:

```
x86-windows
x64-windows
```

**Pull request merged**
