### PR TITLE
[sdl2-image] Bump to 2.6.3

### PR DESCRIPTION
**Pull request by FtZPetruska**
- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)
- [X] SHA512s are updated for each updated download
- [X] The "supports" clause reflects platforms that may be fixed by this new version
- [X] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [X] Any patches that are no longer applied are deleted from the port's directory.
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by FtZPetruska** [comment]
> Thanks for your update. Now feature `sdl2-image[libwebp]` build failed with the following error:
> 
> ```
> -- SDL2_image: Using system libwebp
> CMake Error at E:/Lily/sdl2/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
>   Could NOT find webp (missing: webp_LIBRARY)
> Call Stack (most recent call first):
>   E:/Lily/sdl2/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
>   cmake/Findwebp.cmake:17 (find_package_handle_standard_args)
>   E:/Lily/sdl2/scripts/buildsystems/vcpkg.cmake:843 (_find_package)
>   CMakeLists.txt:610 (find_package)
> 
> -- Configuring incomplete, errors occurred!
> ```
> 
> Could you please also fix it? `libwebp` updated by PR #29165.

I was able to make it build on Windows by introducing a new patch that removes SDL_image's custom findwebp and instead rely on the config files shipped with libwebp. Is this acceptable ?

<details>
<summary>The patch</summary>

```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 438a0aa..4e10733 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -607,7 +607,7 @@ if(SDL2IMAGE_WEBP)
         list(APPEND INSTALL_EXTRA_TARGETS webp)
     else()
         message(STATUS "${PROJECT_NAME}: Using system libwebp")
-        find_package(webp REQUIRED)
+        find_package(WebP CONFIG REQUIRED)
         list(APPEND PC_REQUIRES libwebp)
     endif()
     if(SDL2IMAGE_WEBP_SHARED)
@@ -683,7 +683,6 @@ if(SDL2IMAGE_INSTALL)
             "${CMAKE_CURRENT_BINARY_DIR}/SDL2_imageConfig.cmake"
             "${CMAKE_CURRENT_BINARY_DIR}/SDL2_imageConfigVersion.cmake"
             cmake/Findlibjxl.cmake
-            cmake/Findwebp.cmake
         DESTINATION "${PKG_PREFIX}"
         COMPONENT devel
     )
diff --git a/SDL2_imageConfig.cmake.in b/SDL2_imageConfig.cmake.in
index ae38719..fd5b93e 100644
--- a/SDL2_imageConfig.cmake.in
+++ b/SDL2_imageConfig.cmake.in
@@ -66,8 +66,7 @@ if(SDL2IMAGE_TIF AND NOT SDL2IMAGE_VENDORED AND NOT TARGET TIFF::TIFF)
 endif()
 
 if(SDL2IMAGE_WEBP AND NOT SDL2IMAGE_VENDORED AND NOT TARGET WebP::webp)
-    list(APPEND webp_ROOT "${CMAKE_CURRENT_LIST_DIR}")
-    find_dependency(webp)
+    find_dependency(WebP)
 endif()
 
 #FIXME: can't add SDL2IMAGE_SDL2_REQUIRED_VERSION since not all SDL2 installs ship SDL2ConfigVersion.cmake
diff --git a/cmake/Findwebp.cmake b/cmake/Findwebp.cmake
deleted file mode 100644
index 23982dd..0000000
--- a/cmake/Findwebp.cmake
+++ /dev/null
@@ -1,32 +0,0 @@
-include(FindPackageHandleStandardArgs)
-
-find_library(webp_LIBRARY
-    NAMES webp
-)
-
-find_path(webp_INCLUDE_PATH
-    NAMES webp/decode.h
-)
-
-set(webp_COMPILE_OPTIONS "" CACHE STRING "Extra compile options of webp")
-
-set(webp_LINK_LIBRARIES "" CACHE STRING "Extra link libraries of webp")
-
-set(webp_LINK_FLAGS "" CACHE STRING "Extra link flags of webp")
-
-find_package_handle_standard_args(webp
-    REQUIRED_VARS webp_LIBRARY webp_INCLUDE_PATH
-)
-
-if (webp_FOUND)
-    if (NOT TARGET WebP::webp)
-        add_library(WebP::webp UNKNOWN IMPORTED)
-        set_target_properties(WebP::webp PROPERTIES
-            IMPORTED_LOCATION "${webp_LIBRARY}"
-            INTERFACE_INCLUDE_DIRECTORIES "${webp_INCLUDE_PATH}"
-            INTERFACE_COMPILE_OPTIONS "${webp_COMPILE_FLAGS}"
-            INTERFACE_LINK_LIBRARIES "${webp_LINK_LIBRARIES}"
-            INTERFACE_LINK_FLAGS "${webp_LINK_FLAGS}"
-        )
-    endif()
-endif()

```

</details>

**Comment by LilyWangLL** [comment]
> I was able to make it build on Windows by introducing a new patch that removes SDL_image's custom findwebp and instead rely on the config files shipped with libwebp. Is this acceptable ?

Thanks for your work. I think here should use `find_package(WebP CONFIG REQUIRED)` to link `libwebp`, and is there other way without calling `cmake/Findwebp.cmake` instead of deleting its contents, deleting contents will make the patch bigger.

**Comment by FtZPetruska** [comment]
> > I was able to make it build on Windows by introducing a new patch that removes SDL_image's custom findwebp and instead rely on the config files shipped with libwebp. Is this acceptable ?
> 
> Thanks for your work. I think here should use `find_package(WebP CONFIG REQUIRED)` to link `libwebp`, and is there other way without calling `cmake/Findwebp.cmake` instead of deleting its contents, deleting contents will make the patch bigger.

In the end the following patch (added in [c68c75d](https://github.com/microsoft/vcpkg/pull/29485/commits/c68c75dfc06ded4c9105e8f2a78273979409df74)) is enough to restore the expected behaviour:

```diff

diff --git a/cmake/Findwebp.cmake b/cmake/Findwebp.cmake
index 23982dd..c81c4b9 100644
--- a/cmake/Findwebp.cmake
+++ b/cmake/Findwebp.cmake
@@ -1,7 +1,7 @@
 include(FindPackageHandleStandardArgs)

 find_library(webp_LIBRARY
-    NAMES webp
+    NAMES webp libwebp
 )

 find_path(webp_INCLUDE_PATH
```

**Comment by LilyWangLL** [comment]
> ```
>  find_library(webp_LIBRARY
> -    NAMES webp
> +    NAMES webp libwebp
>  )
> ```
You could use `find_package(webp NAMES WebP CONFIG REQUIRED)`.

**Comment by FtZPetruska** [comment]
> > ```
> >  find_library(webp_LIBRARY
> > -    NAMES webp
> > +    NAMES webp libwebp
> >  )
> > ```
> 
> You could use `find_package(webp NAMES WebP CONFIG REQUIRED)`.

Just to make sure I understand, you would prefer patching the call to `find_package` in the main CMakeLists (and the call to `find_dependency` in the generated Config file) as such:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 438a0aa..5f019fa 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -607,7 +607,7 @@ if(SDL2IMAGE_WEBP)
         list(APPEND INSTALL_EXTRA_TARGETS webp)
     else()
         message(STATUS "${PROJECT_NAME}: Using system libwebp")
-        find_package(webp REQUIRED)
+        find_package(webp NAMES WebP CONFIG REQUIRED)
         list(APPEND PC_REQUIRES libwebp)
     endif()
     if(SDL2IMAGE_WEBP_SHARED)
diff --git a/SDL2_imageConfig.cmake.in b/SDL2_imageConfig.cmake.in
index ae38719..f1cc020 100644
--- a/SDL2_imageConfig.cmake.in
+++ b/SDL2_imageConfig.cmake.in
@@ -67,7 +67,7 @@ endif()
 
 if(SDL2IMAGE_WEBP AND NOT SDL2IMAGE_VENDORED AND NOT TARGET WebP::webp)
     list(APPEND webp_ROOT "${CMAKE_CURRENT_LIST_DIR}")
-    find_dependency(webp)
+    find_dependency(webp NAMES WebP CONFIG)
 endif()
 
 #FIXME: can't add SDL2IMAGE_SDL2_REQUIRED_VERSION since not all SDL2 installs ship SDL2ConfigVersion.cmake

```

**Comment by LilyWangLL** [comment]
Yes, use `find_package CONFIG` module can use the library provided by vcpkg and it provide the include link.

**Comment by FtZPetruska** [comment]
> Yes, use `find_package CONFIG` module can use the library provided by vcpkg and it provide the include link.

Thank you for the clarification! I have updated the patch in [b3a1ac1](https://github.com/microsoft/vcpkg/pull/29485/commits/b3a1ac1ef4a53393135f9fc614d101477cc2aece).

**Review by LilyWangLL — APPROVED** [review]

**Pull request merged**
