### PR TITLE
[lz4] Fix for building Linux shared libraries

### PR DESCRIPTION
**Pull request by here-mikelley**
**Describe the pull request**

- What does your PR fix? 

Fixes issue #7223. This pull request allows lz4 to be compiled as a shared object under Linux.

- Which triplets are supported/not supported? Have you updated the CI baseline?

Supports all current triplets

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

Yes

### CODE REVIEW

**Comment by Cheney-W** [comment]
@here-mikelley 
Thanks for your PR! 
1. Could you please update the version in ports/lz4/CONTROL as 1.9.2-1? 
2. `include(vcpkg_common_functions)` is no longer needed, could you please remove this line?
3. Could you please modify the line 37 and 38 of ports/lz4/portfile.cmake as below:
`file(INSTALL ${SOURCE_PATH}/lib/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)`

You can get more information from [maintainer-guide.md](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md).

**Comment by here-mikelley** [comment]
Thanks @Cheney-W . I've added a commit that should have all of your requested changes.

**Comment by dan-shaw** [comment]
@here-mikelley I'm not sure what this PR fixes. Can you open an issue/provide an example on what it does?

**Comment by here-mikelley** [comment]
> @here-mikelley I'm not sure what this PR fixes. Can you open an issue/provide an example on what it does?

I've updated my original pull-request description by referencing a previously submitted issue. This pull request allows users to build lz4 as a dynamic library under Linux.

**Comment by ras0219-msft** [comment]
LGTM, thanks for the PR!

**Pull request merged**
