### PR TITLE
[opentelemetry-proto] New port

### PR DESCRIPTION
**Pull request by Pravila00**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [ ] <del> The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context. </del>
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by BillyONeal** [comment]
https://github.com/microsoft/vcpkg/blob/8007fc4dff04f35383d85434c161d68454d0988f/ports/opentelemetry-cpp/portfile.cmake#L37

This is already part of `opentelemetry-cpp`

**Comment by dg0yt** [comment]
> v.0.14.0 is the last version that supports OS such as Ubuntu18, RedHat8 and CentOS8. You can read more information about this issue here [open-telemetry/opentelemetry-proto#394](https://github.com/open-telemetry/opentelemetry-proto/issues/394).

AFAIU the limitation is the system package of protobuf. But the new vcpkg port would use the vcpkg package of protobuf, so it shouldn't be affected.

**Comment by Pravila00** [comment]
> This is already part of `opentelemetry-cpp`

@BillyONeal what if I simply want to install only opentelemetry-proto and not the complete OpenTelemetrySDK (opentelemetry-cpp)? I believe opentelemetry-proto should be an independent package to install, simply because you may need OTLP but not OpenTelemetrySDK. This is exactly the case I am facing right now.

**Comment by BillyONeal** [comment]
> @BillyONeal what if I simply want to install only opentelemetry-proto and not the complete OpenTelemetrySDK (opentelemetry-cpp)?

@juandemanjon @JonLiu1993 pinging you because you were involved with https://github.com/microsoft/vcpkg/pull/21149 . Is it true that this part is independent? If so, why is it a feature of the `opentelemetry-cpp` port?

**Comment by JonLiu1993** [comment]
> > @BillyONeal what if I simply want to install only opentelemetry-proto and not the complete OpenTelemetrySDK (opentelemetry-cpp)?
> 
> @juandemanjon @JonLiu1993 pinging you because you were involved with #21149 . Is it true that this part is independent? If so, why is it a feature of the `opentelemetry-cpp` port?

@BillyONeal:

- quoting the official upstream document of opentelemetry-cpp: opentelemetry-proto is an `external dependency` of opentelemetry-cpp: https://github.com/open-telemetry/opentelemetry-cpp/blob/e918960e06b45e899cd6e1f361acdb578d968334/docs/dependencies.md#external-dependencies
- I think opentelemetry-proto provides dependencies for the implementation of feature "otlp-http" and "otlp-grpc" as well as "otlp": 
 ````
 protoc compiler is used to generate C++ stubs for proto files provided by opentelemetry-proto.
 
 ````

**Comment by juandemanjon** [comment]
I think opentelemetry-proto is a separated project under otel umbrella and
I dont see any issue having a separate port for it

**Comment by Pravila00** [comment]
I've decided to just use opentelemetry-cpp port and the OTLP feature

**Pull request closed without merging**
