### PR TITLE
[qt5] latest From 5.13.1 to 5.13.2

### PR DESCRIPTION
**Pull request by longhuan2018**
Upgrade qt5 latest from 5.13.1 to 5.13.2

### CODE REVIEW

**Comment by Neumann-A** [comment]
For CI to test this correctly you must make `latest` the default feature in the control file and remove it after CI has finished

**Comment by longhuan2018** [comment]
@Neumann-A Can you help me, I don't know why CL failed, I just deleted [latest]

**Comment by Neumann-A** [comment]
@longhuan2018:
You need to add `Default-Features: latest` to the qt5-base CONTROL file. The way you tried to do it did not trigger a CI rebuild of qt5-base

**Comment by longhuan2018** [comment]
@Neumann-A  I don't know where the problem is, even if I added Default-Features: latest to qt5-base, the problem is still not solved. I decided to turn off this PR first.

**Pull request closed without merging**
