### PR TITLE
[protobuf] update version to 3.21.12

### LINKED ISSUE #28691: [protobuf] update to 3.21.12
Library name: protobuf

New version number: 3.21.12

### PR DESCRIPTION
**Pull request by FrankXie05**
**Describe the pull request**

- #### What does your PR fix?
  Fixes https://github.com/microsoft/vcpkg/issues/28691
  Note: Update [protobuf] version to 3.21.12 https://github.com/protocolbuffers/protobuf/releases/tag/v21.12
            and use `${VERSION}`
All features have been tested successfully on the follow triplets:

-   x86-windows
-   x64-windows
-   x64-windows-static

### CODE REVIEW

**Comment by dg0yt** [comment]
Can you please validate the installed pc files for windows? I suspect that they always contain `-lprotobuf*`. But even for `windows & !mingw`, the binaries are named `libprotobuf*`, so this must be fixed in the portfile.

**Comment by FrankXie05** [comment]
@dg0yt Yes, I'll do it and report back. :)

**Comment by olejniczak** [comment]
Can it be merged into master?

**Comment by FrankXie05** [comment]
@olejniczak Sure. @dg0yt Let's merge this update. Submit another PR to completely fix the pc issue.

**Comment by dg0yt** [comment]
I do not have a MSVC toolchain. I will burn CI time while you can check the installed file. Assuming a minimal familarity with pkg-config on windows.

**Review by Adela0814 — APPROVED** [review]

**Pull request merged**
