### PR TITLE
[open62541] Update to 1.3.12, add missing features, remove openssl from default features

### PR DESCRIPTION
**Pull request by lukasberbuer**
- Update open62541 to v1.3.12
- Add missing options with default values as defined here: https://github.com/open62541/open62541/blob/v1.3.10/CMakeLists.txt#L149-L160

<hr>

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [x] The "supports" clause reflects platforms that may be fixed by this new version.
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by lukasberbuer** [comment]
@jimwang118, I wonder why "openssl" or encryption in general is a default option. In open62541's `CMakeLists.txt` encryption is disabled by default. I would prefer to stick to open62541's defaults and provide openssl just as a non-default feature.

**Comment by jimwang118** [comment]
> @jimwang118, I wonder why "openssl" or encryption in general is a default option. In open62541's `CMakeLists.txt` encryption is disabled by default. I would prefer to stick to open62541's defaults and provide openssl just as a non-default feature.

Yes, the upstream encryption module is disabled by default. I found that this module was added in PR [16969](https://github.com/microsoft/vcpkg/pull/16969), and it is intended for use with QT6. You can try setting it as a non-default feature.

**Comment by lukasberbuer** [comment]
👍 done!

**Comment by jimwang118** [comment]
Usage test pass with following triplet:

```
x64-windows
```

**Comment by Samega7Cattac** [comment]
Last open62541 stable version is 1.4.4: https://github.com/open62541/open62541/releases/tag/v1.4.4

**Comment by lukasberbuer** [comment]
> Last open62541 stable version is 1.4.4: https://github.com/open62541/open62541/releases/tag/v1.4.4

True. We can have another PR for the 1.4.* update. For me it's important to have the features selection updates also for 1.3.x.

**Pull request merged**
