### PR TITLE
[lapack-reference] fix cblas feature

### LINKED ISSUE #12911: [lapack] build failure - pkgconfig undefined prefix variable
**Host Environment**
- OS: Windows 10
- vcpkg: 2020.06.15-nohash

**To Reproduce**
vcpkg.exe install lapack-reference[cblas] --triplet x64-windows

CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:84 (message):
  pkg-config error output:Variable 'prefix' not defined in
  '/D/git/vcpkg/packages/lapack-reference_x64-windows/lib/pkgconfig/cblas.pc'
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:316 (vcpkg_fixup_pkgconfig_check_files)
  ports/lapack-reference/portfile.cmake:94 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

Error: Building package lapack-reference:x64-windows failed with: BUILD_FAILED

Looks like prefix is not defined at the top of the pkgconfig file for lapack, however it is for cblas.  Is there a way to pass it through, or a bug in the pkgconfig file?

### PR DESCRIPTION
**Pull request by Neumann-A**
closes #12911

depends #12895  for CI success

### CODE REVIEW

**Comment by LilyWangL** [comment]
@Neumann-A Thanks for your PR. I installed `lapack-reference[cblas]` and got the following error:
```
Building package lapack-reference[blas-select,cblas,core,noblas]:x64-windows... done
Installing package lapack-reference[blas-select,cblas,core,noblas]:x64-windows...
The following files are already installed in E:/Lily/pr/vcpkg/installed/x64-windows and are in conflict with lapack-reference:x64-windows

Installed by openblas:x64-windows
    include/cblas.h
```

**Comment by Neumann-A** [comment]
@LilyWangL: noblas and cblas are by design incompatible. Still if openblas is installed there will be a file conflict between those two ports if lapack-reference is built with feature cblas.

**Comment by LilyWangL** [comment]
Yes, if noblas and cblas are by design incompatible, blas-select should not be default feature. If blas-select is default feature, when I install `lapack-reference[cblas]`, it will install `lapack-reference[blas-select,cblas,core,noblas]`. `lapack-reference[cblas]` will build failed on Windows.

**Comment by Neumann-A** [comment]
blas-select needs to be the default feature otherwise ci and users don't get what they expect. People who explicitly want cblas must deactivate the defaults by explicitly declaring [core,cblas]. Feature cblas only exists for corner cases and should be treated as such.

**Comment by Neumann-A** [comment]
The feature is also up for removal as soon as a native windows fortran compiler is available

**Comment by LilyWangL** [comment]
Could add message for feature cblas to declare that this feature does not support windows temporarily?

**Comment by Neumann-A** [comment]
>Could add message for feature cblas to declare that this feature does not support windows temporarily?

It should support windows if you install it **without** the feature `noblas`

**Comment by LilyWangL** [comment]
I test `lapack-reference[cblas]:x64-windows-static` and it can install successfully.
```
Building package lapack-reference[blas-select,cblas,core]:x64-windows-static... done
Installing package lapack-reference[blas-select,cblas,core]:x64-windows-static...
Installing package lapack-reference[blas-select,cblas,core]:x64-windows-static... done
Elapsed time for package lapack-reference:x64-windows-static: 6.92 min

Total elapsed time: 10.11 min
```

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
