### PR TITLE
[librtmp] Update to 2.4

### PR DESCRIPTION
**Pull request by TheStormN**

### CODE REVIEW

**Comment by alexkaratarakis** [comment]
Thanks!

**Comment by TheStormN** [comment]
@alexkaratarakis No problem. I'm glad to see that compared to other projects that I contributed here the response and the acceptance are pretty fast. Keep up the good work. :)

**Comment by lazyhamster** [comment]
Nice. Thanks for the update.
One question though. Why did you choose to install all library headers? Some of them are internal and not needed for library users.

**Comment by TheStormN** [comment]
@lazyhamster Because I stumbled across several projects that are using the internal headers. On Linux and Mac this is not an issue, because the default Makefile and also the package managers do install all the headers, so I think it is only logical to make the same behavior for Windows. :)

**Comment by lazyhamster** [comment]
@TheStormN I see. Make sense then to have them all installed. It is better to have maximum compatibility across all platforms.

**Pull request merged**
