### PR TITLE
[qtbase] Add feature for gtk3 platform theme

### LINKED ISSUE #35594: [qtbase] Add feature for gtk3 support on Linux
### Is your feature request related to a problem? Please describe.

Since QT 6.5, when running on gtk based Linux desktops (eg GNOME) QT apps will match the color scheme of the active gtk3 theme. This requires building QT with FEATURE_gtk3.

### Proposed solution

Add "gtk3" feature (available on Linux platforms) which builds with FEATURE_gtk3 cmake variable set. This would likely be good to include by default for Linux builds (as this matches official QT packages).

### Describe alternatives you've considered

Apps don't match color scheme. This is particularly noticeable if using a dark theme. QT apps built using QT from vcpkg will be light. Doesn't break functionality, but is not what is expected by end users or developers expecting behavior matching official packages.

### Additional context

If this is something that would be accepted, I can implement and make a PR.

### PR DESCRIPTION
**Pull request by MB3hel**
Fixes #35594

- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] ~~SHA512s are updated for each updated download~~
- [X] The "supports" clause reflects platforms that may be fixed by this new version
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by MB3hel** [comment]
@microsoft-github-policy-service agree

**Comment by jimwang118** [comment]
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.
Please resolve the code conflict.

**Comment by MB3hel** [comment]
Previously failed on `x86-windows` due to incorrect commit hash in versions file. Not sure why, because it was updated. Maybe related to force push / commit amend? 

Regardless, fixed now and I double checked manually this time.

**Comment by jimwang118** [comment]
The following error occurred during local testing:
```
CMake Error at cmake/QtBuildInformation.cmake:508 (message):
   Feature "xcb": Forcing to "ON" breaks its condition:

       QT_FEATURE_thread AND TARGET XCB::XCB AND TEST_xcb_syslibs AND QT_FEATURE_xkbcommon_x11

   Condition values dump:

       QT_FEATURE_thread = "ON"
       TARGET XCB::XCB found
       TEST_xcb_syslibs = "FALSE"
       QT_FEATURE_xkbcommon_x11 not evaluated
```
[config-x64-linux-out.log](https://github.com/microsoft/vcpkg/files/13682540/config-x64-linux-out.log)

**Comment by jimwang118** [comment]
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

**Comment by MB3hel** [comment]
@jimwang118 This doesn't seem to be caused by any changes in this PR. This seems to be due to missing system libraries necessary to build QT (`TEST_xcb_syslibs = "FALSE"` indicates such, see lines 483 and 918 of `qtbase/src/gui/configure.cmake`)

On an Ubuntu system, this is solved for me by running `sudo apt-get install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev` as indicated by the port as required.

Without these system dependencies, this error occurs even without the changes made in this PR.

If I'm missing something here please let me know, but I don't believe this is related to my changes.

**Comment by jimwang118** [comment]
> @jimwang118 This doesn't seem to be caused by any changes in this PR. This seems to be due to missing system libraries necessary to build QT (`TEST_xcb_syslibs = "FALSE"` indicates such, see lines 483 and 918 of `qtbase/src/gui/configure.cmake`)
> 
> On an Ubuntu system, this is solved for me by running `sudo apt-get install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev` as indicated by the port as required.
> 
> Without these system dependencies, this error occurs even without the changes made in this PR.
> 
> If I'm missing something here please let me know, but I don't believe this is related to my changes.

OK, thank you very much, I will retest this PR.

**Comment by jimwang118** [comment]
Feature gtk3 passed with following triplets:

```
x64-linux
```

**Comment by BillyONeal** [comment]
@jimwang118 You can run https://github.com/microsoft/vcpkg/blob/master/scripts/azure-pipelines/linux/provision-image.sh on a Linux box to install the same stuff that our build lab installs.

@MB3hel Thanks for the feature!

**Pull request merged**
