### PR TITLE
[poco] pre 2.0.0

### PR DESCRIPTION
**Pull request by gennesseaux**
- Updated to the latest compiling commit
- Added SQLite support
- Added PDF support
- Added MariaDB support
- Added PostgreSQL support

### CODE REVIEW

**Comment by Rastaban** [comment]
I am seeing a new build failure in the 3fd port (which has a dependancy on poco) in x64-windows and x86-windows.  Can you take a look at it?

**Comment by gennesseaux** [comment]
Ok, I'll take a look.

**Comment by PhoebeHui** [comment]
@gennesseaux, could you also update CONTROL version in https://github.com/Microsoft/vcpkg/blob/master/ports/3fd/CONTROL?

More information in https://github.com/Microsoft/vcpkg/blob/master/docs/maintainers/control-files.md

**Comment by vicroms** [comment]
I've updated the CONTROL file for 3fd and can confirm that this update causes no regressions now.

Thanks for the PR!

**Pull request merged**
