### PR TITLE
[Qt] update to 5.12.5

### LINKED ISSUE #8157: [qt] update to 5.12.5
since qt 5.12.4 has been merged today we can move on to qt 5.12.5 which was released yesterday. Why did nobody say anything? .... probably a good time to test the update routine I added. I wish there would be a way to automatically update the hashes also.

### PR DESCRIPTION
**Pull request by Neumann-A**
closes #8157
~~I let CI tell me the two remaining hashes.~~
Previous run looked good on windows. Lets see if Linux and OSX agree.  
OSX had a regression in libqglviewer due to:
 `Project ERROR: Could not resolve SDK SDKVersion for 'macosx10.12' using --show-sdk-version`. 
Maybe libqglviewer should use the same logic as qt5-base to set/discover the SDK version? (Relevant [SO](https://stackoverflow.com/questions/26320677/error-could-not-resolve-sdk-path-for-macosx10-8))

### CODE REVIEW

**Comment by Neumann-A** [comment]
@Rastaban:

Did something change with the SDK installation on the OSX CI? The libqglviewer regression seems strange to me and should not have happend.

**Comment by cbezault** [comment]
@Neumann-A, generally I handle the mac CI stuff and no nothing has changed in the last 5 months. I'm not in the office today so I can't get on those CI machines ( 😢 ) but I'll see if @Rastaban can take a look if he has time.

**Comment by Neumann-A** [comment]
Other PR told me OSX takes around 12h. argh another 3h until osx is green. Wish the logoutput would be fully scrollable while the job is running

**Comment by Rastaban** [comment]
Our Mac machines are a little old and slow.  We put in an order for new faster ones but I don't know when we will get them.

**Review by cbezault — APPROVED** [review]

**Comment by JackBoosY** [comment]
The results look good, thank you for your work!

**Pull request merged**
