### PR TITLE
[openexr] Update to 3.1.4

### LINKED ISSUE #21652: OpenEXR update to 3.1.3
Library name: OpenEXR

New version number:

3.1.3

https://github.com/AcademySoftwareFoundation/openexr/releases/tag/v3.1.3

Other information that may be useful (release notes, etc...)

Many projects, such as OpenVdb and OpenImageIO have migrated to OpenEXR 3 already, and vcpkg only supply OpenEXR version 2 is starting to impact users.

https://github.com/AcademySoftwareFoundation/openexr/issues/1207

### PR DESCRIPTION
**Pull request by chausner**
**Describe the pull request**

- #### What does your PR fix?  
  Updates openexr to 3.1.4. Also updates ports that directly or indirectly depend on openexr: devil, freeimage, ogre, osg

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  As before, Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run ./vcpkg x-add-version --all and committed the result?  
  Yes

### CODE REVIEW

**Comment by chausner** [comment]
This MR is blocked by https://github.com/microsoft/vcpkg/pull/21079.

**Comment by fabiencastan** [comment]
Any news to move to openexr-3.x?

**Comment by fabiencastan** [comment]
It's quite critical as a new package has been created for [imath](https://github.com/microsoft/vcpkg/blob/master/ports/imath) and is used by packages such as [alembic](https://github.com/microsoft/vcpkg/blob/master/ports/alembic).
But openexr-2 still embeds a version of imath which is not aligned with the imath package.
So when you install some packages, you got multiple imath.dll installed with different versions and multiple imath include files.
And obviously build/link errors when using them.

**Comment by fabiencastan** [comment]
Now depends on https://github.com/microsoft/vcpkg/pull/22463

**Comment by EvanAW** [comment]
> Now depends on #22463

Which has now been merged! Yay!

@PhoebeHui I believe that means the depends on another PR tag can be removed.

**Comment by fabiencastan** [comment]
Any news on the openexr upgrade to 3.x?

**Comment by meshula** [comment]
@chausner I'm sorry to ask a very naive question, but how can the failing triplets be viewed? I attempted to visit the failures reported in the CI just above, and can only find messages like this:

```
HEAD is now at 6aafc264d Merge e66d454a28acc3a45df9c8877f1a2f8a7baa188a into daa7215f3d68c2a2f2e18c398cb73dab63cda829
Running CI using parent hashes
'vcpkg ci' is an internal command which will change incompatibly or be removed at any time.
Creating failure logs output directory C:\a\1\a\failure-logs
Loading dependency information for 187 packages...
Loading dependency information for 512 packages...
Detecting compiler hash for triplet x64-uwp...
Detecting compiler hash for triplet x64-windows...
Error: vcpkg has crashed; no additional details are available.
The source line is D:\a\_work\1\s\src\vcpkg\binarycaching.cpp(587)

##[error]vcpkg ci failed
At C:\a\1\s\scripts\azure-pipelines\test-modified-ports.ps1:178 char:5
+     throw "vcpkg ci failed"
+     ~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (vcpkg ci failed:String) [], RuntimeException
+ FullyQualifiedErrorId : vcpkg ci failed
##[error]PowerShell exited with code '1'.
Finishing: *** Test Modified Ports and Prepare Test Logs ***
```

**Comment by dg0yt** [comment]
> how can the failing triplets be viewed?

It is pointless for the generic "vcpkg has crashed" error. 
For failing ports, you can navigate to the builds's "artifacts" on Azure pipelines, and you can download failure logs from the vertical three-dots icon on the right side.

**Comment by dg0yt** [comment]
> got this far: https://github.com/microsoft/vcpkg/pull/20957/checks?check_run_id=5311194250

Click on "[5 errors / 0 warnings](https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_build/results?buildId=67902)", then you are on Azure pipelines. 
From here, one way to get to the artifacts list is to click "[11 published](https://dev.azure.com/vcpkg/public/_build/results?buildId=67902&view=artifacts&pathAsName=false)".

**Comment by meshula** [comment]
That was helpful, I think. OpenScengraph is the next consumer of OpenEXR 2. There's an open issue here:

https://github.com/openscenegraph/OpenSceneGraph/issues/1075

```
CMake Error at src/osgWrappers/serializers/osg/cmake_install.cmake:47 (file):
  file INSTALL cannot find
  "D:/buildtrees/osg/x64-windows-dbg/bin/osgPlugins-3.6.5/osgdb_serializers_osgd.pdb":
  File exists.
Call Stack (most recent call first):
  src/osgWrappers/serializers/cmake_install.cmake:37 (include)
  src/cmake_install.cmake:55 (include)
  cmake_install.cmake:101 (include)
```

**Comment by dg0yt** [comment]
@chausner Any chance that you can continue this PR?

**Comment by chausner** [comment]
> @chausner Any chance that you can continue this PR?

I am looking into it again right now. It turns out that there are actually many more ports that depend on OpenEXR and most of them are not compatible with OpenEXR 3.x, so they all need patches:

* devil
* directxtex
* freeimage
* magnum-plugins
* ogre
* opencv
* opencv2
* opencv3
* opencv4
* openimageio
* opendb
* osg
* pangolin

So far, I got devil, freeimage, ogre and osg working but haven't looked into any of the others.

**Comment by dg0yt** [comment]
Thanks for the update.

> * openimageio

This is the port where I got stuck recently when I tried to use it (i.e. test it) together with opencolorio, due to half/imath library issues, cf. #23918. That's why I was looking for related PRs and came to this one.

**Comment by simogasp** [comment]
@PhoebeHui @chausner @fabiencastan 
Since OpenEXR 3.0 introduced so many changes in terms of building (modern cmake) and the split into different libraries, wouldn't it make sense to have a port openexr3 like we already have for opencv (opencv3, opencv4). It will make things much easier because the ports that want to upgrade to > 3.0 can do it properly in their source  code instead of creating patches here, and people who really need to have openexr 3 in vcpkg to link with their own project won't be stuck.

I know it's not ideal in terms of maintenance, but since it has been done for opencv it think it's the best solution. It's a very particular case because the changes introduced in openexr 3 are so radical that it's almost impossible to manage the compatibility between the two versions (I mean in terms of building rules/cmake) without writing a lot of cmake code that will have to take into account so many corner cases.

And in the medium term we can declare the original openxr deprecated to "force" maintainers of the ports to transition to the new way of importing.

**Comment by JackBoosY** [comment]
Any update on this PR?

**Comment by chausner** [comment]
> Any update on this PR?

I am going to close this MR but I'll keep the branch in case somebody else wants to continue where I left off or try the approach suggested by @simogasp.

**Comment by simogasp** [comment]
@JackBoosY What do you think about that proposal of mine? Does it seem reasonable?
If I have time I might give it a try

**Comment by JackBoosY** [comment]
@simogasp Agreed.

**Pull request closed without merging**
