### PR TITLE
[openssl] bump to 1.0.2r / [openssl] bump to 1.0.2s

### PR DESCRIPTION
**Pull request by the-j0k3r**
Here we are again =)

### CODE REVIEW

**Comment by NancyLi1013** [comment]
Hi @the-j0k3r, thanks for your PR. Here are the test results from current CI system:

|x64-windows              |master| test |notes
|-------------------------|------|------|-----
|openssl-windows          |Pass  |Fail  |**Regression**

|x64-windows-static       |master| test |notes
|-------------------------|------|------|-----
|openssl-windows          |Pass  |Fail  |**Regression**

|x64-osx                  |master| test |notes
|-------------------------|------|------|-----
|openssl-unix             |Pass  |Fail  |**Regression**

|arm64-windows  |master| test |notes
|---------------|------|------|-----
|openssl-windows|Pass  |Fail  |**Regression**

|x86-windows              |master| test |notes
|-------------------------|------|------|-----
|openssl-windows          |Pass  |Fail  |**Regression**

|x64-linux                |master| test |notes
|-------------------------|------|------|-----
|openssl-unix             |Pass  |Fail  |**Regression**

x64-uwp had no regressions

arm-uwp had no regressions

It seems that it failed on all triplets except for uwp.

**Comment by the-j0k3r** [comment]
@NancyLi1013 thank you for that information. I wont be able to fix the tests though =)

**Comment by Bo98** [comment]
You haven't changed these lines: https://github.com/Microsoft/vcpkg/blob/aa886d0498a8700157d9029fdc77ae0c9f855a81/ports/openssl-unix/portfile.cmake#L6

and

https://github.com/Microsoft/vcpkg/blob/aa886d0498a8700157d9029fdc77ae0c9f855a81/ports/openssl-windows/portfile.cmake#L6

**Comment by the-j0k3r** [comment]
Thanks @Bo98, updated and pushed.

**Comment by heydojo** [comment]
Current stable version of the 1.0.2 series is openssl-1.0.2s released 2019-May-28 according to the [openssl website](https://www.openssl.org/source/). So this pull request should be updated.

However, it is strongly recommended that because the 1.0.2 series has less than six months left on it's long term support status, that 1.1.1 is adopted instead due to it's long term support status ending 2023-09-11. Please see the [openssl release policies](https://www.openssl.org/policies/releasestrat.html) for more information.

The change to openssl will also affect a large number of ports. libpq for instance (which is well overdue for a bump anyway,) is one example.

**Comment by Bo98** [comment]
I suggest updating to 1.0.2s as soon as possible, considering 1.0.2r _is_ a security update and that version bump really shouldn't be causing issues (I don't know what's up with the CI since we're not allowed to check its logs). After that, we should focus on migrating to 1.1.1 which may need a little more time to make sure nothing breaks. API wise, I'm not sure what vcpkg's policy is on updating libraries with API changes, but it would need to be done regardless before the year's out.

**Comment by the-j0k3r** [comment]
>Current stable version of the 1.0.2 series is openssl-1.0.2s released 2019-May-28 according to the openssl website. So this pull request should be updated.

I can update this PR to reflect that instead, though getting this up to snuff to get merged is another matter.

**Comment by the-j0k3r** [comment]
da heck? OK closing and re-opening seems rebase got nuked by the sheer ammount of commits that came after this.

**Pull request closed without merging**
