### PR TITLE
[boost] pulling has_synchro bits from https://github.com/microsoft/vcpkg/pull…

### PR DESCRIPTION
**Pull request by JavierMatosD**
@Neumann-A I want to pull out the `has_synchro` bits from https://github.com/microsoft/vcpkg/pull/27694/

### CODE REVIEW

**Comment by JonLiu1993** [comment]
@BillyONeal, Could you please take a review?

**Review by BillyONeal — DISMISSED** [review]
The changes in here look good. However, clearly `scripts/boost/generate-ports.ps1` has not been run, which will erase a bunch of these changes. I believe you and @ras0219-msft were going to propose changes to `generate-ports.ps1`, but in that case I think you're on the hook to have those changes in hand before we proceed. (That is, in an otherwise unchanged repo `generate-ports.ps1` needs to result in no changes)

**Comment by JonLiu1993** [comment]
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

**Comment by JonLiu1993** [comment]
Depends on https://github.com/microsoft/vcpkg/pull/31572.

**Review by JonLiu1993 — APPROVED** [review]

**Review by BillyONeal — APPROVED** [review]
This approval is assuming `generate-ports.ps1` makes no changes.

**Pull request merged**
