### PR TITLE
[directxtk, directxtk12, directxmesh, directxtex, uvatlas] ports updated for June 2021 releases

### PR DESCRIPTION
**Pull request by walbourn**
Updated the **directxtk**, **directxtk12**, **directxmesh**, **directxtex**, and **uvatlas** ports to the latest GitHub releases.

* **directxtk** now supports a new feature ``xaudio2redist`` which supports *DirectX Tool Kit for Audio* on Windows 7 SP1 via the *xaudio2redist* port.

* **directxtk12** now makes use the *directx-headers* port to build with the latest DirectX 12 headers.

* all ports converted from ``CONTROL`` files to ``vcpkg.json``

### CODE REVIEW

**Comment by walbourn** [comment]
https://github.com/microsoft/DirectXTK/releases/tag/jun2021

https://github.com/microsoft/DirectXTK12/releases/tag/jun2021

https://github.com/microsoft/DirectXTex/releases/tag/jun2021

https://github.com/microsoft/DirectXMesh/releases/tag/jun2021

https://github.com/microsoft/UVAtlas/releases/tag/jun2021

**Review by NancyLi1013 — APPROVED** [review]

**Comment by walbourn** [comment]
Verified the ports build with all supported triplets locally (using GCC 9 for linux)

```
vcpkg install directxtk:x86-windows
vcpkg install directxtk[xaudio2redist]:x86-windows --recurse
vcpkg install directxtk:x86-windows-static
vcpkg install directxtk:x64-windows
vcpkg install directxtk[xaudio2redist]:x64-windows --recurse
vcpkg install directxtk:x64-windows-static
vcpkg install directxtk:arm64-windows
vcpkg install directxtk:arm64-windows-static
vcpkg install directxtk:x86-uwp
vcpkg install directxtk:x64-uwp
vcpkg install directxtk:arm-uwp
vcpkg install directxtk:arm64-uwp

vcpkg install directxtk12:x86-windows
vcpkg install directxtk12:x86-windows-static
vcpkg install directxtk12:x64-windows
vcpkg install directxtk12:x64-windows-static
vcpkg install directxtk12:arm64-windows
vcpkg install directxtk12:arm64-windows-static
vcpkg install directxtk12:x86-uwp
vcpkg install directxtk12:x64-uwp
vcpkg install directxtk12:arm-uwp
vcpkg install directxtk12:arm64-uwp

vcpkg install directxtex:x86-windows
vcpkg install directxtex[openexr]:x86-windows --recurse
vcpkg install directxtex:x86-windows-static
vcpkg install directxtex:x64-windows
vcpkg install directxtex[openexr]:x64-windows --recurse
vcpkg install directxtex:x64-windows-static
vcpkg install directxtex:arm64-windows
vcpkg install directxtex:arm64-windows-static
vcpkg install directxtex:x86-uwp
vcpkg install directxtex:x64-uwp
vcpkg install directxtex:arm-uwp
vcpkg install directxtex:arm64-uwp
vcpkg install directxtex:x64-linux
vcpkg install directxtex[openexr]:x64-linux --recurse
vcpkg install directxtex:arm64-linux
vcpkg install directxtex[openexr]:arm64-linux --recurse

vcpkg install directxmesh:x86-windows
vcpkg install directxmesh:x86-windows-static
vcpkg install directxmesh:x64-windows
vcpkg install directxmesh:x64-windows-static
vcpkg install directxmesh:arm64-windows
vcpkg install directxmesh:arm64-windows-static
vcpkg install directxmesh:x86-uwp
vcpkg install directxmesh:x64-uwp
vcpkg install directxmesh:arm-uwp
vcpkg install directxmesh:arm64-uwp
vcpkg install directxmesh:x64-linux
vcpkg install directxmesh:arm64-linux

vcpkg install uvatlas:x86-windows
vcpkg install uvatlas:x86-windows-static
vcpkg install uvatlas:x64-windows
vcpkg install uvatlas:x64-windows-static
vcpkg install uvatlas:arm64-windows
vcpkg install uvatlas:arm64-windows-static
vcpkg install uvatlas:x86-uwp
vcpkg install uvatlas:x64-uwp
vcpkg install uvatlas:arm-uwp
vcpkg install uvatlas:arm64-uwp
vcpkg install uvatlas:x64-linux
vcpkg install uvatlas:arm64-linux
```

**Comment by walbourn** [comment]
@NancyLi1013 - Yes, features have been tested.

**Comment by NancyLi1013** [comment]
LGTM, thanks again for your efforts @walbourn.

**Comment by strega-nil-ms** [comment]
Cool, thanks @walbourn !

**Pull request merged**
