### PR TITLE
[mpfr] Support Linux and OSX

### LINKED ISSUE #22671: [mpfr] Build error
**Host Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
`./vcpkg install xxxx`

**Failure logs** 
-Cut and paste the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

### PR DESCRIPTION
**Pull request by JackBoosY**
This port needs texinfo on Linux and OSX.

Fixes #22671.

### CODE REVIEW

**Comment by dg0yt** [comment]
Texinfo is probably needed for documentation, and vpckg doesn't care for documentation. Can it turned off?

**Comment by Neumann-A** [comment]
Maybe like `GTKDOCIZE=false` ? Just for texinfo

**Comment by JackBoosY** [comment]
> Maybe like `GTKDOCIZE=false` ? Just for texinfo

No mpfr doesn't have such option / value.

**Comment by dg0yt** [comment]
> No mpfr doesn't have such option / value.

It is not a regular option but an environment variable affection `autoreconf`.
~~~
$ git grep GTKDOCIZE
ports/libcanberra/portfile.cmake:set(ENV{GTKDOCIZE} true)
ports/libidn2/portfile.cmake:    set(ENV{GTKDOCIZE} true)
ports/libtasn1/portfile.cmake:set(ENV{GTKDOCIZE} true)
~~~

**Comment by JackBoosY** [comment]
> > No mpfr doesn't have such option / value.
> 
> It is not a regular option but an environment variable affecting `autoreconf`.
> 
> ```
> $ git grep GTKDOCIZE
> ports/libcanberra/portfile.cmake:set(ENV{GTKDOCIZE} true)
> ports/libidn2/portfile.cmake:    set(ENV{GTKDOCIZE} true)
> ports/libtasn1/portfile.cmake:set(ENV{GTKDOCIZE} true)
> ```

No that doesn't work when I set it to `true` or `false`.

**Comment by Neumann-A** [comment]
> No that doesn't work when I set it to true or false.

The point is that there must be a program on the path called true/false. (/usr/bin/true | /usr/bin/false)
GTKDOCIZE is the variable for the program gtkdocize and autoconf will use it instead of searching for gtkdocize if it is set. The question is if texinfo has some similar variable. The question comes done if it uses one of https://www.gnu.org/software/autoconf/manual/autoconf-2.68/html_node/Generic-Programs.html

**Comment by JackBoosY** [comment]
In favor of #22859

**Pull request closed without merging**
