### PR TITLE
[tiff,zstd,gdal] Fix find_package interactions

### PR DESCRIPTION
**Pull request by dg0yt**
- #### What does your PR fix?
  Fixes regression in using gdal with tiff[zstd], appearing #27928.
  Upstream: https://github.com/OSGeo/gdal/pull/7048, https://github.com/OSGeo/gdal/issues/7040
  Closes #28803.

CC @Neumann-A

### CODE REVIEW

**Comment by Neumann-A** [comment]
This does not fix that: https://github.com/microsoft/vcpkg/blob/5bb5f3923a33d862b25c18fd4514e08c74c698e1/ports/tiff/vcpkg-cmake-wrapper.cmake.in#L40 is wrong and leads to calling the wrong module which is the underlying fix https://github.com/microsoft/vcpkg/pull/28803 provides. 

Furthermore, this has nothing to do with `find_package2` since it is simply not defined for the offending targets/packages.
https://github.com/OSGeo/gdal/blob/6bdeb5623b5e7febde1fcfb932ee9214db9594dc/cmake/modules/DefineFindPackage2.cmake#L85-L87
acts as the implicit stop gate for `find_package2` and does the same as your explicit variable here. Just study the CI trace logs from https://github.com/microsoft/vcpkg/runs/10517848810

Since you didn't add the tiff changes from #28803 you probably won't see the regression in gdal in this PR which makes the test itself invalid.

**Comment by dg0yt** [comment]
I'm still looking into completing the test coverage because I'm aware of the relevant ports not being built. 

> Furthermore, this has nothing to do with `find_package2` since it is simply not defined for the offending targets/packages.
> https://github.com/OSGeo/gdal/blob/6bdeb5623b5e7febde1fcfb932ee9214db9594dc/cmake/modules/DefineFindPackage2.cmake#L85-L87
> acts as the implicit stop gate for `find_package2` and does the same as your explicit variable here. Just study the CI trace logs from https://github.com/microsoft/vcpkg/runs/10517848810

IMO still missing the point I made in https://github.com/OSGeo/gdal/issues/7040#issuecomment-1376169052.

**Comment by Neumann-A** [comment]
> IMO still missing the point I made in https://github.com/OSGeo/gdal/issues/7040#issuecomment-1376169052.

Yeah but that is not to be discussed in vcpkg since vcpkg just needs a working solution for itself. Having a general upstream solution is a nice to have but not a hard requirement for vcpkg. 
But let me tell you: target generation itself is always guarded by `if(TARGET)` and as such will not lead to any interactions when the `if` is removed. However, target name collisions are a problem with gdals current design and that might cause issues. I would rather like to see them use `GDAL::ZSTD` (VTK Style) and stuff for external deps instead of `ZSTD::zstd` which might create a collision as already observed in the tribits parts of https://github.com/microsoft/vcpkg/pull/27928 where i went ahead an prefixed all meaningful targets with `TPL::` to avoid at least a collision with `fmt::fmt`.

**Comment by dg0yt** [comment]
The gdal patch was accepted upstream.

**Review by LilyWangLL — APPROVED** [review]

**Comment by LilyWangLL** [comment]
Close this PR? @dg0yt https://github.com/microsoft/vcpkg/pull/28929#issuecomment-1382672584

**Comment by dg0yt** [comment]
@LilyWangLL  Now that #28929 is green and approved, too, I can reset this PR to draft and close it as soon as the other is merged.

**Comment by Neumann-A** [comment]
@dg0yt close?

**Comment by dg0yt** [comment]
> > Now that #28929 is green and approved, too, I can reset this PR to draft and close it as soon as the other is merged.
>
> close?

@Neumann-A As announced, now.

**Pull request closed without merging**
