### PR TITLE
[cli11] Update to 2.2.0

### PR DESCRIPTION
**Pull request by chausner**
**Describe the pull request**

- #### What does your PR fix?  
  Updates cli11 to 2.2.0

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  As before, Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run ./vcpkg x-add-version --all and committed the result?  
  Yes

### CODE REVIEW

**Comment by Thomas1664** [comment]
I'm afraid you have to take a second look at the ports `CMakeLists.txt` because it seems like they changed their options to disable tests/ docs:

```
CMake Warning at scripts/cmake/vcpkg_configure_cmake.cmake:435 (message):
  The following variables are not used in CMakeLists.txt:

      DISABLE_EXAMPLES
      DISABLE_TESTS
```

**Comment by chausner** [comment]
> I'm afraid you have to take a second look at the ports `CMakeLists.txt` because it seems like they changed their options to disable tests/ docs:

Hmm, I can't reproduce these warnings. Also, I can't find these options being set anywhere. Are you maybe referring to a different port?

**Comment by Thomas1664** [comment]
> Hmm, I can't reproduce these warnings. Also, I can't find these options being set anywhere. Are you maybe referring to a different port?

You're right. Sorry for that.

**Review by JonLiu1993 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the update!

**Pull request merged**
