### PR TITLE
[mimalloc,vcpkg-ci-mimalloc] Fix exported usage, add test port

### LINKED ISSUE #37489: mimalloc is not publishing the libraries
### Operating system

Windows

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
1. run vcpkg install mimalloc

2. look on your machine in the vcpkg...installed folder for the two libraries mimalloc.lib and mimalloc-redirect.lib

The files are not there. The mimalloc.lib file has been put into a packages folder, but the mimalloc-redirect lib file didn't even make it that far.
```

### Failure logs

not relevant. Please see description above. The port does not publish the two files that it needs to publish.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dg0yt**
Resolves #37489.

The new test port builds and runs official tests from mimalloc. In addition to the original executables, it builds one more C++ executable configured with data from pkg-config.

- The targets provided by the cmake config provided the right locations.
- The variables were wrong, but normally wouldn't be needed.
  The PR fixes this (in the wrapper) as far as reasonable. There is no point in providing the "object dir". The "library dir" cannot handle multi-config generators.
- The pkg-config files were completely broken for debug, \[secure], and windows-static. The library name varies widely. This PR fixes the name issue.

The pkg-config files still don't carry C++ linkage. Related: https://github.com/microsoft/vcpkg/pull/37339#issuecomment-2001932741

It seems there is still a problem with app-local deployment:
- For dynamic builds with MSVC, no DLLs are copied next to the executable
  (expected: `mimalloc.dll`, `mimalloc-redirect.dll`). This can be seen in the CI file lists for  
  `vcpkg-ci-mimalloc:x64-windows:/tools/vcpkg-ci-mimalloc/pkgconfig-override-cxx.exe`
- But for dynamic builds with mingw, the DLLs are copied.

### CODE REVIEW

**Comment by dg0yt** [comment]
> It seems there is still a problem with app-local deployment:
> 
>  * For dynamic builds with MSVC, no DLLs are copied next to the executable
>    (expected: `mimalloc.dll`, `mimalloc-redirect.dll`). This can be seen in the CI file lists for
>    `vcpkg-ci-mimalloc:x64-windows:/tools/vcpkg-ci-mimalloc/pkgconfig-override-cxx.exe`

From https://dev.azure.com/vcpkg/public/_build/results?buildId=100747 x64-windows:
Linking with `mimalloc-secure.lib`:
~~~
[9/12] cmd.exe /C "cd . && D:\downloads\tools\cmake-3.27.1-windows\cmake-3.27.1-windows-i386\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\pkgconfig-override-cxx.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MICROS~1\2022\ENTERP~1\VC\Tools\MSVC\1438~1.331\bin\Hostx64\x86\link.exe  CMakeFiles\pkgconfig-override-cxx.dir\main-override.cpp.obj  /out:pkgconfig-override-cxx.exe /implib:pkgconfig-override-cxx.lib /pdb:pkgconfig-override-cxx.pdb /version:0.0 /machine:X86 /nologo /DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF   /subsystem:console  D:\installed\x86-windows\lib\mimalloc-secure.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
~~~
Copying tool dependencies for `pkgconfig-override-cxx.exe` finds no reference to mimalloc:
~~~
Name                           Value
----                           -----
api-ms-win-crt-runtime-l1-1-0… True
KERNEL32.dll                   True
api-ms-win-crt-math-l1-1-0.dll True
api-ms-win-crt-heap-l1-1-0.dll True
api-ms-win-crt-locale-l1-1-0.… True
VCRUNTIME140.dll               True
api-ms-win-crt-stdio-l1-1-0.d… True
~~~

>  * But for dynamic builds with mingw, the DLLs are copied.

Linking with `mimalloc-secure.lib`:
~~~
[8/9] : && /usr/lib/ccache/x86_64-w64-mingw32-g++ -O3 -DNDEBUG  CMakeFiles/dynamic-override-cxx.dir/main-override.cpp.obj -o dynamic-override-cxx.exe -Wl,--out-implib,libdynamic-override-cxx.dll.a -Wl,--major-image-version,0,--minor-image-version,0  /vcpkg/installed/x64-mingw-dynamic/lib/libmimalloc-secure.dll.a  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && :
~~~

Copying tool dependencies for `pkgconfig-override-cxx.exe`, x64-mingw-dynamic:
~~~
Name                           Value
----                           -----
ADVAPI32.dll                   True
libmimalloc-secure.dll         True
KERNEL32.dll                   True
ntdll.dll                      True
libwinpthread-1.dll            True
msvcrt.dll                     True
libstdc++-6.dll                True
mimalloc-redirect.dll          True
libgcc_s_seh-1.dll             True
~~~

**Comment by JonLiu1993** [comment]
@dg0yt, When I test usage I can configure successfully, but when I include <mimalloc.h>build I can't find
````
#include <stdio.h>
#include <mimalloc.h>

int main()
{
    printf("%s\n", "HELLO WORLD");
    return 0;
}
````
````
>------ Build All started: Project: CMakeProject1, Configuration: x64-Debug ------
  MSBuild version 17.9.5+33de0b227 for .NET Framework
  
    CMakeProject1.cpp
C:\Users\test\source\repos\CMakeProject1\CMakeProject1\CMakeProject1.cpp(2,10): error C1083: Cannot open include file: 'mimalloc.h': No such file or directory 

Build All failed.
````

**Comment by dg0yt** [comment]
Use CMake, or set your include dirs manually.

**Comment by dg0yt** [comment]
Note that the test port already verifies that the header is installed.

**Comment by JonLiu1993** [comment]
> Note that the test port already verifies that the header is installed.

Yes I can see the header file is installed, I mean when I reference it in a test .cpp it can't be found.

**Comment by JonLiu1993** [comment]
CMakeLists.txt：
````
cmake_minimum_required(VERSION 3.0)

project(test)

find_package(mimalloc CONFIG REQUIRED)

add_executable(test CMakeProject1.cpp)

target_link_libraries(test PRIVATE $<IF:$<TARGET_EXISTS:mimalloc-static>,mimalloc-static,mimalloc)
````
CMakeProject1.cpp:
````
#include <stdio.h>
#include <mimalloc.h>

int main()
{
    printf("%s\n", "HELLO WORLD");
    return 0;
}
````
config:
````
1> CMake generation started for configuration: 'x64-Debug'.
1> Command line: "C:\WINDOWS\system32\cmd.exe" /c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Visual Studio 17 2022" -A x64  -DCMAKE_CONFIGURATION_TYPES:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\test\source\repos\CMakeProject1\out\install\x64-Debug"  -DCMAKE_TOOLCHAIN_FILE=F:/Feature-test/mimalloc/scripts/buildsystems/vcpkg.cmake "C:\Users\test\source\repos\CMakeProject1" 2>&1"
1> Working directory: C:\Users\test\source\repos\CMakeProject1\out\build\x64-Debug
1> [CMake] -- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
1> [CMake] -- The C compiler identification is MSVC 19.39.33522.0
1> [CMake] -- The CXX compiler identification is MSVC 19.39.33522.0
1> [CMake] -- Detecting C compiler ABI info
1> [CMake] -- Detecting C compiler ABI info - done
1> [CMake] -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe - skipped
1> [CMake] -- Detecting C compile features
1> [CMake] -- Detecting C compile features - done
1> [CMake] -- Detecting CXX compiler ABI info
1> [CMake] -- Detecting CXX compiler ABI info - done
1> [CMake] -- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe - skipped
1> [CMake] -- Detecting CXX compile features
1> [CMake] -- Detecting CXX compile features - done
1> [CMake] CMake Deprecation Warning at CMakeProject1/CMakeLists.txt:1 (cmake_minimum_required):
1> [CMake]   Compatibility with CMake < 3.5 will be removed from a future version of
1> [CMake]   CMake.
1> [CMake] 
1> [CMake]   Update the VERSION argument <min> value or use a ...<max> suffix to tell
1> [CMake]   CMake that the project does not need compatibility with older versions.
1> [CMake] 
1> [CMake] 
1> [CMake] -- Configuring done (7.6s)
1> [CMake] -- Generating done (0.0s)
1> [CMake] -- Build files have been written to: C:/Users/test/source/repos/CMakeProject1/out/build/x64-debug
1> Extracted CMake variables.
1> Extracted source files and headers.
1> Extracted code model.
1> Extracted toolchain configurations.
1> Extracted includes paths.
1> CMake generation finished.
````
build:
````
>------ Build All started: Project: CMakeProject1, Configuration: x64-Debug ------
  MSBuild version 17.9.5+33de0b227 for .NET Framework
  
    1>Checking Build System
    Building Custom Rule C:/Users/test/source/repos/CMakeProject1/CMakeProject1/CMakeLists.txt
    CMakeProject1.cpp
C:\Users\test\source\repos\CMakeProject1\CMakeProject1\CMakeProject1.cpp(2,10): error C1083: Cannot open include file: 'mimalloc.h': No such file or directory 

Build All failed.
````

**Comment by JonLiu1993** [comment]
I tested successfully using PC files, but still cannot find the header file using the usage provided by the port.
CMakeList.txt:
````
cmake_minimum_required(VERSION 3.5)

set(PKG_CONFIG_EXECUTABLE "${VCPKG_INSTALLED_DIR}/x64-windows/tools/pkgconf/pkgconf.exe")
project(test)

add_executable(test CMakeProject1.cpp)

find_package(PkgConfig REQUIRED)

pkg_check_modules(MIMALLOC mimalloc REQUIRED IMPORTED_TARGET)

target_link_libraries(test PRIVATE PkgConfig::MIMALLOC)
````
CMakeProject1.cpp:
````
#include <stdio.h>
#include <mimalloc.h>

int main()
{
    printf("%s\n", "HELLO WORLD");
    return 0;
}
````
config:
````
1> CMake generation started for configuration: 'x64-Debug'.
1> Command line: "C:\WINDOWS\system32\cmd.exe" /c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Visual Studio 17 2022" -A x64  -DCMAKE_CONFIGURATION_TYPES:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\test\source\repos\CMakeProject1\out\install\x64-Debug"  -DCMAKE_TOOLCHAIN_FILE=F:/Feature-test/mimalloc/scripts/buildsystems/vcpkg.cmake "C:\Users\test\source\repos\CMakeProject1" 2>&1"
1> Working directory: C:\Users\test\source\repos\CMakeProject1\out\build\x64-Debug
1> [CMake] -- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
1> [CMake] -- The C compiler identification is MSVC 19.39.33522.0
1> [CMake] -- The CXX compiler identification is MSVC 19.39.33522.0
1> [CMake] -- Detecting C compiler ABI info
1> [CMake] -- Detecting C compiler ABI info - done
1> [CMake] -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe - skipped
1> [CMake] -- Detecting C compile features
1> [CMake] -- Detecting C compile features - done
1> [CMake] -- Detecting CXX compiler ABI info
1> [CMake] -- Detecting CXX compiler ABI info - done
1> [CMake] -- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe - skipped
1> [CMake] -- Detecting CXX compile features
1> [CMake] -- Detecting CXX compile features - done
1> [CMake] -- Found PkgConfig: F:/Feature-test/mimalloc/installed/x64-windows/tools/pkgconf/pkgconf.exe (found version "2.1.0") 
1> [CMake] -- Checking for module 'mimalloc'
1> [CMake] --   Found mimalloc, version 2.1
1> [CMake] -- Configuring done (6.6s)
1> [CMake] -- Generating done (0.0s)
1> [CMake] -- Build files have been written to: C:/Users/test/source/repos/CMakeProject1/out/build/x64-debug
1> Extracted CMake variables.
1> Extracted source files and headers.
1> Extracted code model.
1> Extracted toolchain configurations.
1> Extracted includes paths.
1> CMake generation finished.
````
build:
````
>------ Build All started: Project: CMakeProject1, Configuration: x64-Debug ------
  MSBuild version 17.9.5+33de0b227 for .NET Framework
  
    1>Checking Build System
    Building Custom Rule C:/Users/test/source/repos/CMakeProject1/CMakeProject1/CMakeLists.txt
    CMakeProject1.cpp
    test.vcxproj -> C:\Users\test\source\repos\CMakeProject1\out\build\x64-debug\CMakeProject1\Debug\test.exe
    Building Custom Rule C:/Users/test/source/repos/CMakeProject1/CMakeLists.txt

Build All succeeded.
````

**Comment by dg0yt** [comment]
And I cannot check your `share/mimalloc/mimalloc.cmake`.

**Comment by dg0yt** [comment]
@JonLiu1993 Will you trace your local issue? Or ask another reviewer?

**Review by JonLiu1993 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks @dg0yt!

**Pull request merged**
