### PR TITLE
[opencv4,opencv3] Control exported protobuf dependency

### LINKED ISSUE #20366: [zxing-cpp] build failure
**Host Environment**
- OS: macOS 11
- Compiler: clang

**Failure logs** 

```
Detecting compiler hash for triplet x64-osx...
The following packages will be built and installed:
    zxing-cpp[core,opencv]:x64-osx -> 2020-12#3
Restored 0 packages from /Users/leanderSchulten/.cache/vcpkg/archives in 687.3 us. Use --debug to see more details.
Starting package 1/1: zxing-cpp:x64-osx
Building package zxing-cpp[core,opencv]:x64-osx...
-- Downloading https://github.com/glassechidna/zxing-cpp/archive/e0e40ddec63f38405aca5c8c1ff60b85ec8b1f10.tar.gz -> glassechidna-zxing-cpp-e0e40ddec63f38405aca5c8c1ff60b85ec8b1f10.tar.gz...
-- Cleaning sources at /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/zxing-cpp/src/85ec8b1f10-637534e8b9.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/downloads/glassechidna-zxing-cpp-e0e40ddec63f38405aca5c8c1ff60b85ec8b1f10.tar.gz
-- Applying patch 0001-opencv4-compat.patch
-- Applying patch 0002-improve-features.patch
-- Applying patch 0003-fix-dependency-bigint.patch
-- Using source at /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/zxing-cpp/src/85ec8b1f10-637534e8b9.clean
-- Configuring x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/downloads/tools/cmake-3.21.1-osx/cmake-3.21.1-macos-universal/CMake.app/Contents/bin/cmake /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/zxing-cpp/src/85ec8b1f10-637534e8b9.clean -DWITH_OPENCV=ON -DWITH_ICONV=OFF -DCMAKE_MAKE_PROGRAM=/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/downloads/tools/ninja-1.10.2-osx/ninja -DCMAKE_SYSTEM_NAME=Darwin -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/scripts/toolchains/osx.cmake -DVCPKG_TARGET_TRIPLET=x64-osx -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/ -D_VCPKG_INSTALLED_DIR=/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/vcpkg_installed -DVCPKG_MANIFEST_INSTALL=OFF -DCMAKE_OSX_ARCHITECTURES=x86_64 -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/packages/zxing-cpp_x64-osx/debug
    Working Directory: /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/zxing-cpp/x64-osx-dbg
    Error code: 1
    See logs for more information:
      /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/zxing-cpp/config-x64-osx-dbg-out.log
      /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/zxing-cpp/config-x64-osx-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:381 (vcpkg_execute_required_process)
  ports/zxing-cpp/portfile.cmake:25 (vcpkg_configure_cmake)
  scripts/ports.cmake:140 (include)


Error: Building package zxing-cpp:x64-osx failed with: BUILD_FAILED
```

<details><summary>zxing-cpp/config-x64-osx-dbg-out.log</summary>

```
-- The C compiler identification is AppleClang 13.0.0.13000029
-- The CXX compiler identification is AppleClang 13.0.0.13000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring incomplete, errors occurred!
See also "/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/zxing-cpp/x64-osx-dbg/CMakeFiles/CMakeOutput.log".
See also "/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/zxing-cpp/x64-osx-dbg/CMakeFiles/CMakeError.log".

```
</details>

<details><summary>zxing-cpp/config-x64-osx-dbg-err.log</summary>

```
CMake Error at /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/scripts/buildsystems/vcpkg.cmake:786 (_find_package):
  Could not find a package configuration file provided by "Protobuf" with any
  of the following names:

    ProtobufConfig.cmake
    protobuf-config.cmake

  Add the installation prefix of "Protobuf" to CMAKE_PREFIX_PATH or set
  "Protobuf_DIR" to a directory containing one of the above files.  If
  "Protobuf" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/downloads/tools/cmake-3.21.1-osx/cmake-3.21.1-macos-universal/CMake.app/Contents/share/cmake-3.21/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/vcpkg_installed/x64-osx/share/opencv/OpenCVModules.cmake:15 (find_dependency)
  /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/vcpkg_installed/x64-osx/share/opencv/OpenCVConfig.cmake:126 (include)
  /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/scripts/buildsystems/vcpkg.cmake:786 (_find_package)
  CMakeLists.txt:54 (find_package)



```
</details>

### PR DESCRIPTION
**Pull request by dg0yt**
- #### What does your PR fix?  
  Protobuf is only needed for feature dnn(opencv4)/flann(opencv3), but without an explicit gate, it became required when using `find_package(OpenCV REQUIRED)`.
  Fixes #20366, #20529.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  unchanged, no.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  yes

Disclaimer.
No local tests were made.

### CODE REVIEW

**Comment by dg0yt** [comment]
CC @autoantwort @horenmar for review/test.

**Comment by autoantwort** [comment]
Yeah fixes #20366 👍

**Review by autoantwort — APPROVED** [review]

**Comment by horenmar** [comment]
lgtm

**Review by strega-nil-ms — APPROVED** [review]

**Comment by strega-nil-ms** [comment]
LGTM, thanks @dg0yt :)

**Pull request merged**
