### PR TITLE
[test] gettext

### PR DESCRIPTION
**Pull request by PhoebeHui**
Test

### CODE REVIEW

**Comment by PhoebeHui** [comment]
Updating [msys2-runtime-3.2.0-8](https://repo.msys2.org/msys/x86_64/msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst%22) to [msys2-runtime-3.3.4-1](https://repo.msys2.org/msys/x86_64/msys2-runtime-3.3.4-1-x86_64.pkg.tar.zst) cause gettext hang in configure steps.

**Comment by Neumann-A** [comment]
vcpkg needs to get off of msys somehow

**Comment by dg0yt** [comment]
Vcpkg is ignoring msys installation procedures and dependencies. This invites problems with incompatible runtimes.

**Comment by Neumann-A** [comment]
> Vcpkg is ignoring msys installation procedures and dependencies. This invites problems with incompatible runtimes.

vcpkg was using pacman in the past but it was just as unreliable. vcpkg needs to build the required tools itself and provide a common prefix so we can get away from msys.

**Pull request closed without merging**
