### PR TITLE
[openal-soft] Revert #12047

### LINKED ISSUE #7790: [openal-soft:x86-windows][x86 system] [openal-soft:x64-windows][x64 system] build failure
**Host Environment**
- OS: Windows 10 x86
- Compiler: MSBuild

**To Reproduce**
`./vcpkg install openal-soft:x86-windows`

**Failure logs** 
[install-x86-windows-dbg-out.log.zip](https://github.com/microsoft/vcpkg/files/3522655/install-x86-windows-dbg-out.log.zip)

**Additional context**
This issue only occurs on AppVeyor builds and only on 32 bits. 

Here's the complete openal-soft subdirectory in the buildtrees directory:
[openal-soft-buildtree.zip](https://github.com/microsoft/vcpkg/files/3522661/openal-soft-buildtree.zip)

### PR DESCRIPTION
**Pull request by Hoikas**
The reverted commit claims to address #7790, however, attempting to build openal-soft with that commit merged on AppVeyor [continues to fail](https://ci.appveyor.com/project/Hoikas/plasmaprefix/builds/33965996) under Visual Studio 2015. Therefore, #7790 should be reopened. #12047 introduces a regression in that attempting to build openal-soft on AppVeyor with Visual Studio 2017 [fails](https://ci.appveyor.com/project/Hoikas/plasmaprefix/builds/33966096). Reverting #12047 causes the Visual Studio 2017 [build to succeed](https://ci.appveyor.com/project/Hoikas/plasmaprefix/builds/33966245) on AppVeyor.

Additionally, #12047 changes the openal-soft cmake to download an arbitrary ref that does not correspond with any particular tag or release from the openal-soft repository. The ref introduced does not match the CONTROL file version of 1.20.1. I assume this ref was the HEAD at the time of the pull request submission. If so, this was improper; instead, the user should use the command `vcpkg install --head openal-soft` to fetch and build the latest commit from the openal-soft repository.

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for the PR and additional diagnostics!

I believe I've identified the root cause of #10825, #7790, and #12047: `openal-soft` internally would search for and add an additional Windows SDK to its build, which would conflict with the one we provide via the environment.

I've added a CMake option that should prevent it and fix all these issues. I'd appreciate any confirmation on whether it handles the various scenarios you've tested.

Regardless of that, this PR LGTM to merge as long as there are no regressions.

**Review by ras0219-msft — APPROVED** [review]

**Comment by Hoikas** [comment]
Unfortunately, that does not seem to fix #7790 -- building on AppVeyor with VS 2015 still [fails](https://ci.appveyor.com/project/Hoikas/plasmaprefix/builds/33989261). However, I can confirm that there is [no regression](https://ci.appveyor.com/project/Hoikas/plasmaprefix/builds/33989021) when building with AppVeyor and VS 2017.

**Comment by PhoebeHui** [comment]
Related to issue https://github.com/microsoft/vcpkg/issues/12325

**Comment by PhoebeHui** [comment]
cc @Pospelove

**Comment by Pospelove** [comment]
Great. I have nothing against it

**Pull request merged**
