### PR TITLE
[ffmpeg] Use nproc - 1 build jobs for ffmpeg instead of 6.

### PR DESCRIPTION
**Pull request by rkitover**
nproc is part of both coreutils and busybox and should be available on
all linux distributions and msys2.

This should speed up the (very long and tedious) ffmpeg build time for
people with more hardware threads.

Signed-off-by: Rafael Kitover <rkitover@gmail.com>

### CODE REVIEW

**Comment by Neumann-A** [comment]
You probably want to use VCPKG_CONCURRENCY  there. So the trick here is to configure the patch in the portfile and apply it afterwards.

**Comment by rkitover** [comment]
@Neumann-A I did a more extensive rework using `configure_file()`, with `VCPKG_CONCURRENCY`, what do you think?

**Comment by Neumann-A** [comment]
hmm after looking at the build.sh script i think this should be refactored to use `vcpkg_configure_make` and `vcpkg_install_make` if possible. Probably requires #11836

**Comment by rkitover** [comment]
Great, I'll wait for that to be merged first then.

**Comment by rkitover** [comment]
@Neumann-A I tried this, unfortunately this will require making some tweaks to that script, which I will do in a separate PR.

This is because the ffmpeg configure is not autoconf, and it does not understand options like `--sbindir`, and dies with an error if it sees an option it doesn't understand.

Maybe I'll add a `REMOVE_OPTIONS` option or some such.

Also there's a bug on line 349, `DISABLE_VERBOSE_FLAGS` should be `_csc_DISABLE_VERBOSE_FLAGS`.

**Comment by rkitover** [comment]
@Neumann-A perhaps we should merge this (if it's ok otherwise) until the proper rework is ready, since it has turned out to be more complicated, to give people the benefit of faster build times. I will leave that decision up to you guys.

**Review by PhoebeHui — APPROVED** [review]
LGTM, thanks for the PR!

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Comment by rkitover** [comment]
Thanks guys, I will do a more proper rework using `vcpkg_configure_make` and friends later, those scripts will need some modifications to support non-autoconf configure systems.

**Comment by cenit** [comment]
broken on Ubuntu On WSL now with error:

./build.sh: 5: export: Files/Microsoft: bad variable name

**Comment by rkitover** [comment]
Sorry, can you try changing that line in `ports/ffmpeg/build.sh.in` from:

```bash
export PATH=/usr/bin:$PATH
```

to:

```bash
export PATH="/usr/bin:$PATH"
```

**Comment by cenit** [comment]
Yes that's what I did. For now it seems to work. At least it didn't stop at the same position as before.
I will let you know if it reaches the end

**Comment by cenit** [comment]
@rkitover confirmed, it's ok now.
Would you like to do a urgent PR to fix master or do you prefer me to do it?

**Comment by rkitover** [comment]
If you have commit access just make the change yeah, sorry.

**Comment by cenit** [comment]
I can do a PR like you :)

**Comment by rkitover** [comment]
@cenit opened https://github.com/microsoft/vcpkg/pull/13275.

**Pull request merged**
