### PR TITLE
[mongoose] update to v7.5

### PR DESCRIPTION
**Pull request by ryuukk**
**Describe the pull request**

- #### What does your PR fix?  
  It updates mongoose to the latest v7.5 version

### CODE REVIEW

**Comment by JonLiu1993** [comment]
@ryuukk ,Thanks for your pr, Could you please modernize the cmake function in port file.cmake?

**Comment by JonLiu1993** [comment]
After finish your pr, please run command "./vcpkg x-add-version mongoose --overwrite-version" and commit again

**Review by JonLiu1993 — APPROVED** [review]

**Comment by JonLiu1993** [comment]
All features are tested successfully in the following triplet:
- x86-windows
- x64-windows
- x64-windows-static

**Comment by strega-nil-ms** [comment]
Thanks!

**Comment by ryuukk** [comment]
@JonLiu1993 thanks a lot for helping me with this PR, it is my first time contributing to it, sorry about the little mistake!

**Pull request merged**
