### PR TITLE
[meson] Update meson to 0.58.1 

### PR DESCRIPTION
**Pull request by Neumann-A**

### CODE REVIEW

**Comment by JackBoosY** [comment]
Does the simage regression related to meson changes?

**Comment by Neumann-A** [comment]
@JackBoosY: looks more like a problem with the JPEG wrapper 

```
CMake Error at /Users/vagrant/Data/installed/x64-osx/share/jpeg/vcpkg-cmake-wrapper.cmake:1 (_find_package):
  _find_package for module JPEG called with REQUIRED, but
  CMAKE_DISABLE_FIND_PACKAGE_JPEG is enabled.  A REQUIRED package cannot be
  disabled.
Call Stack (most recent call first):
  /Users/vagrant/Data/work/1/s/scripts/buildsystems/vcpkg.cmake:745 (include)
  /Users/vagrant/Data/installed/x64-osx/share/tiff/vcpkg-cmake-wrapper.cmake:17 (find_package)
  /Users/vagrant/Data/work/1/s/scripts/buildsystems/vcpkg.cmake:745 (include)
  CMakeLists.txt:222 (find_package)


CMake Error at /Users/vagrant/Data/work/1/s/scripts/buildsystems/vcpkg.cmake:791 (_find_package):
  _find_package for module ZLIB called with REQUIRED, but
  CMAKE_DISABLE_FIND_PACKAGE_ZLIB is enabled.  A REQUIRED package cannot be
  disabled.
```

**Comment by JackBoosY** [comment]
When building `simage:x64-uwp` when install tiff first:
```
     4>D:\buildtrees\simage\src\mage-1.8.0-17f988a113.clean\src\simage_tiff.c(88,18): error C4996: 'uint16': libtiff type deprecated; please use corresponding C99 stdint.h type 
```

**Comment by dg0yt** [comment]
> looks more like a problem with the `TIFF` wrapper

- JPEG is required iff port tiff is used with feature "jpeg".
- ZLIB is required iff port tiff is used with feature "zip". 
- jpeg, lzma and zip are opt-out features of port tiff because tiff was built with them before I updated that port.

Port simage is configured with `CMAKE_DISABLE_FIND_PACKAGE_JPEG` and `CMAKE_DISABLE_FIND_PACKAGE_ZLIB` for `OSX_OR_WINDOWS`. I don't know why this is done, but this conflicts with tiff's transitive dependencies.

So how about opting out from tiff's features "jpeg" and "zip" in port simage?

**Comment by Neumann-A** [comment]
@dg0yt 
> don't know why this is done, but this conflicts with tiff's transitive dependencies.

They are only required **if and only if** `find_package(TIFF REQUIRED)`. If `find_package(TIFF)` is called the transitive dependencies should not be marked as `REQUIRED`. instead if the dependency is not satisfied TIFF_Found should be set to false.

**Comment by dg0yt** [comment]
> When building `simage:x64-uwp` that install tiff first:
> 
> ```
>      4>D:\buildtrees\simage\src\mage-1.8.0-17f988a113.clean\src\simage_tiff.c(88,18): error C4996: 'uint16': libtiff type deprecated; please use corresponding C99 stdint.h type 
> ```

tiff 4.3.0 changed its type system. This was explicitly mentioned in https://github.com/microsoft/vcpkg/pull/18187. With that PR, [I patched a similar issue in port selene](https://github.com/microsoft/vcpkg/pull/18187/files#diff-9693267cc3a0c0a25b5e19b706db8f4eee2ad2758d8645e5f3e3438ca98105bd).

**Comment by dg0yt** [comment]
>  If `find_package(TIFF)` is called the transitive dependencies should not be marked as `REQUIRED`. instead if the dependency is not satisfied TIFF_Found should be set to false.

I see, it becomes clear with the simage example. Unfortunately it didn't come up during CI and review. I'm not sure if I can act quickly for tiff at the moment. 

 `git grep REQUIRED ports/*/vcpkg-cmake-wrapper.cmake` shows a few more hits which might need to be reviewed then.

**Comment by JackBoosY** [comment]
Depends on #18473. Since this is a tool update PR, I need to make sure all tests pass.

**Comment by dg0yt** [comment]
> Does the simage regression related to meson changes?

Same as for [gn update problem](https://github.com/microsoft/vcpkg/pull/17519#issuecomment-864227032):
simage for windows triplets does not depend on tiff (and some other ports) so it is no must not use it. That's why it was not covered in CI for port tiff.

**Comment by BillyONeal** [comment]
I poked @ras0219 @ras0219-msft about the "vcpkg-find-acquire-program" server intermittent failure that got triggered by tool update

**Comment by dg0yt** [comment]
> looks more like a problem with the TIFF wrapper
> ...
> cc @dg0yt because of git blame ;)

For osx, I came to the conclusion that the error is one level above the TIFF wrapper: #18631

**Comment by JackBoosY** [comment]
> > looks more like a problem with the TIFF wrapper
> > ...
> > cc @dg0yt because of git blame ;)
> 
> For osx, I came to the conclusion that the error is one level above the TIFF wrapper: #18631

Related: #18602.

**Comment by JackBoosY** [comment]
The gl3w:x86-windows regression will be fixed by another PR.

**Review by JackBoosY — APPROVED** [review]

**Comment by PhoebeHui** [comment]
The 'set(MESON_VERSION 0.58.0)' need to change the version to '0.58.1', since PR https://github.com/microsoft/vcpkg/pull/18817 already covered all changes in this PR, @Neumann-A, do you mind to close this PR? or I can revert the changes in PR #18817.

**Pull request closed without merging**
