### PR TITLE
[mpir] only install debug files if VCPKG_BUILD_TYPE is empty or 'debug'

### LINKED ISSUE #11962: [mpir] build failure (regression)
**Host Environment**
- OS: Windows 10
- Compiler: VS 2017 & 2019

after this update:

    mpir:x64-windows-v141            3.0.0-7 -> 3.0.0-8

I get the following error when building mpir:

```
Starting package 75/96: mpir:x64-windows-v141
Building package mpir[core]:x64-windows-v141...
-- Downloading https://github.com/wbhart/mpir/archive/mpir-3.0.0.tar.gz...
-- Extracting source C:/Tools/vcpkg/downloads/wbhart-mpir-mpir-3.0.0.tar.gz
-- Applying patch enable-runtimelibrary-toggle.patch
-- Using source at C:/Tools/vcpkg/buildtrees/mpir/src/mpir-3.0.0-c9f63a8302
-- Building C:/Tools/vcpkg/buildtrees/mpir/x64-windows-v141/build.vc15/dll_mpir_gc/dll_mpir_gc.vcxproj for Release
-- Installing: C:/Tools/vcpkg/packages/mpir_x64-windows-v141/include/gmp.h
-- Installing: C:/Tools/vcpkg/packages/mpir_x64-windows-v141/include/gmpxx.h
-- Installing: C:/Tools/vcpkg/packages/mpir_x64-windows-v141/include/mpir.h
-- Installing: C:/Tools/vcpkg/packages/mpir_x64-windows-v141/include/mpirxx.h
-- Installing: C:/Tools/vcpkg/packages/mpir_x64-windows-v141/bin/mpir.dll
-- Installing: C:/Tools/vcpkg/packages/mpir_x64-windows-v141/lib/mpir.lib
-- Installing: C:/Tools/vcpkg/packages/mpir_x64-windows-v141/share/mpir/copyright
-- Performing post-build validation
There should be no empty directories in C:\Tools\vcpkg\packages\mpir_x64-windows-v141
The following empty directories were found:
    C:/Tools/vcpkg/packages/mpir_x64-windows-v141/debug/bin
    C:/Tools/vcpkg/packages/mpir_x64-windows-v141/debug/lib
If a directory should be populated but is not, this might indicate an error in the portfile.
If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:
    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/a/dir" "${CURRENT_PACKAGES_DIR}/some/other/dir")
Found 1 error(s). Please correct the portfile:
    C:\Tools\vcpkg\ports\mpir\portfile.cmake
-- Performing post-build validation done
Error: Building package mpir:x64-windows-v141 failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: mpir:x64-windows-v141
  Vcpkg version: 2020.02.04-nohash
```

full log:

https://ci.appveyor.com/project/josch/3dtk/builds/33540793/job/9y0wa55s08qv68a2?fullLog=true

### PR DESCRIPTION
**Pull request by josch**
closes #11962

Fix regression where mpir fails to build with VCPKG_BUILD_TYPE set to release.

### CODE REVIEW

**Comment by NancyLi1013** [comment]
Hi @josch 
Thanks for this PR.
I noticed that you only added debug type for windows. 
Actually, we also need to add both debug and release type on all platforms.
So could you please help update others?

**Comment by josch** [comment]
I'm afraid my vcpkg-foo is not good enough to also add linux and osx support. After wrapping the respective chunks where release and debug builds are done with a check for `VCPKG_BUILD_TYPE` the release builds work fine but the debug build will not install include files and I don't know how to fix that.

**Comment by NancyLi1013** [comment]
We can always install the headers to `include `directory whatever the build type is debug or release.
[portfile.txt](https://github.com/microsoft/vcpkg/files/4802824/portfile.txt)
 You can refer to this attachment to update.

Note:  Please also update the version in CONTROL file.

**Comment by NancyLi1013** [comment]
@josch 
Could you please sign the CLA first? You can click the above link to finish this.

**Comment by josch** [comment]
This is not my code. As you can see, I just took yours and made a commit out of it. This is also why you are listed as the author in the git commit.

Since I have no copyright on this contribution, there is also no need for me to sign the CLA.

**Comment by NancyLi1013** [comment]
@vicroms 
Could you please help take a look if this PR is blocked by the signing of CLA? Is it necessary for @josch  to sign CLA?

**Comment by NancyLi1013** [comment]
@ras0219-msft 
Could you please help take a look if this PR is blocked by the signing of CLA? Is it necessary for @josch to sign CLA?

**Comment by josch** [comment]
@NancyLi1013 This seems like a technical problem to me and not a legal one. My name is not the commit author, so I'm surprised the CI thinks I have any kind of copyright on this contribution. You could probably also fix this problem just by making a new pull request with the same commit. Thanks!

**Comment by NancyLi1013** [comment]
@josch 
Thanks for your above info.  Since this PR was submitted by you, it is normal that you are the author. But for now, I will open a new PR to fix this issue.
Thanks for your efforts.

**Comment by NancyLi1013** [comment]
Closing this PR  due to another new PR #12514 opened to fix the issue.

**Pull request closed without merging**
