### PR TITLE
[CMake] update to 3.9

### PR DESCRIPTION
**Pull request by Mixaill**
fixes some bugs ( #1280 for example)

### CODE REVIEW

**Comment by Voskrese** [comment]
многое не собирается под 3.9, я бы пока не рекомендовал

> a lot not going under 3.9, I'd not yet recommended

**Comment by Mixaill** [comment]
>многое не собирается под 3.9, я бы пока не рекомендовал

any example?
например?

**Comment by Voskrese** [comment]
@Mixaill допустим библиотеки от гугол и фейсбук, на память экспериментировал на glog или gflags, когда мучался с folly

> Suppose the library of googl and Facebook, experimented on memory glog or gflags tool when live with folly

**Comment by zabulus** [comment]
Issue with not detectable compiler is about not installed studio component. Here is solution for this:
https://stackoverflow.com/a/45300253.

**Comment by zabulus** [comment]
FWIW, I'm using CMake 3.9 without issues except compiler-related, that was fixed by installing additional studio component.

**Comment by Voskrese** [comment]
@zabulus точно не в этом проблема, у меня стоит все на максимуме. в общем то cmake не привязан к версии, можете использовать любую версию, просто создать линк либо подменить. вариантов множество. но лучше использовать проверенную версию, чем потом возвращаться.
хотя я сам использую уже давно 3.8.2 релиз

> not exactly this problem I have everything on high. in general the cmake does not bind to version, you can use any version, simply create a link or replace. There are many solutions. but it is better to use the checked version than then coming back.
> Although I use myself for a long time already 3.8.2 release

**Comment by zabulus** [comment]
Error with not detectable compiler is based on CMake unavailability to compile simple C++ program. Reason for this is about environment where it functions.
I'm good with any version as soon it has arm support.

**Comment by ras0219-msft** [comment]
CMake 3.9 also improved the parallelism of the Ninja generator, which results in faster compiles for the vast majority of our packages.

I agree that it's a solid upgrade now that it has come out -- if there are any issues we will address them when they arise.

Thanks for the PR!

**Pull request merged**
