### PR TITLE
Add package lame and add features to ffmpeg

### PR DESCRIPTION
**Pull request by cmpute**
Modifications:
- Add port `lame`
- Add some features to ffmpeg, all tested under x86-windwos

### CODE REVIEW

**Comment by cmpute** [comment]
I met following problem building ffmpeg so I turned off relevant switch.
```
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um\winsock2.h(180): error C2011: 'timeval': 'struct' type redefinition
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um\winsock.h(108): note: see declaration of 'timeval'
...
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um\winsock2.h(1624): error C2375: 'accept': redefinition; different linkage
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um\winsock.h(739): note: see declaration of 'accept'
```

**Comment by LilyWangL** [comment]
@cmpute, could you resolve the conflicts?

**Comment by cmpute** [comment]
It's long since I add this package, I don't have spare time to fix it right now

**Comment by dan-shaw** [comment]
I'm going to close this PR because it’s been a long time since any update has been made. If this is something you’d like to see merged and work is being done, please reopen.

**Pull request closed without merging**
