### PR TITLE
[ms-angle] Set ms-angle to empty package

### LINKED ISSUE #11386: [ms-angle] now an invalid port - needs to be removed
**Host Environment**
- OS: 
- Compiler:

**To Reproduce**

**Failure logs** 

**Additional context**
According to the port home page: https://github.com/microsoft/angle
MS is no longer maintaining the ms-angle port and refers you to use google's version:  https://opensource.google.com/projects/angle.

Note: vcpkg already has a port angle which appears to be pulling from the google/angle github repository.

### PR DESCRIPTION
**Pull request by LilyWangL**
**Describe the pull request**

- What does your PR fix? Fixes #11386
This repository has been deprecated, all of its change have been submitted upstream to the master ANGLE repository. So remove ms-angle repository.
- Which triplets are supported/not supported? Have you updated the CI baseline?
Yes.
- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes.

### CODE REVIEW

**Comment by Neumann-A** [comment]
If I remember correctly removing a port means `vcpkg upgrade` does not work any more. That is why qt5-modularscripts still exists. 
Instead empty the portfile and print a warning?

**Review by PhoebeHui — APPROVED** [review]
LGTM, I think we should remove it. 

@Neumann-A, there is an issue https://github.com/microsoft/vcpkg/issues/11482 for track the bug when use 'vcpkg upgrade', I think we need a fix for this.

**Comment by cenit** [comment]
@PhoebeHui it's still true that as of now many deprecated ports have remained as empty, and with a dependency to the new one. It would not be so bad also for backwards compatibility in principle, do you agree?

**Comment by timautry** [comment]
> @PhoebeHui it's still true that as of now many deprecated ports have remained as empty, and with a dependency to the new one. It would not be so bad also for backwards compatibility in principle, do you agree?

@cenit I did not think of that.  Good idea!

**Comment by cenit** [comment]
@liliwangl it’s missing a crucial Build-Depends: angle

**Pull request merged**
