### PR TITLE
[sqlite3] Ability to enable the DBSTAT virtual table feature

### PR DESCRIPTION
**Pull request by trueqbit**
This PR adds a configuration for the virtual table DBSTAT to the list of configuration options.

Apart from simply rounding out the sqlite3 port, this is useful for two immediate reasons:
1. sqlite_orm has built-in support for the "dbstat" table, but programmers who want to use it cannot take vcpkg's sqlite3.
2. sqlite_orm's codebase tests built-in support for the "dbstat" table and relies on the vcpkg ecosystem. Tests for "dbstat" remain unexecuted.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Review by FrankXie05 — APPROVED** [review]

**Comment by FrankXie05** [comment]
The feature has been test successfully locally.

**Comment by trueqbit** [comment]
Are the failing tests expected?

**Review by fnc12 — APPROVED** [review]

**Comment by FrankXie05** [comment]
@trueqbit The ci baseline has been fixed and please merger this PR to master. :)

**Comment by trueqbit** [comment]
@FrankXie05 Just letting you know that all checks have passed.

**Review by FrankXie05 — APPROVED** [review]

**Comment by trueqbit** [comment]
Thanks everyone!

**Pull request merged**
