### PR TITLE
[liblsl] Update to 1.16.0

### PR DESCRIPTION
**Pull request by chausner**
**Describe the pull request**

- #### What does your PR fix?  
  This updates the liblsl port to version 1.16.0

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  All, Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

### CODE REVIEW

**Comment by JonLiu1993** [comment]
@chausner ,Thanks for your pr, is this pr ready for review?

**Comment by chausner** [comment]
It's basically ready, I'm just waiting for the upstream maintainers to create a new stable release because this PR currently depends on a development build.

**Comment by JonLiu1993** [comment]
@chausner ,If this pr is ready for review, please let me know

**Comment by chausner** [comment]
> @chausner ,If this pr is ready for review, please let me know

This ready for review now. 👍

**Review by JonLiu1993 — APPROVED** [review]

**Comment by strega-nil-ms** [comment]
cool, thanks!

**Pull request merged**
