### PR TITLE
Add harfbuzz.

### PR DESCRIPTION
**Pull request by vlj**
This adds harfbuzz, a text shaping engine.

### CODE REVIEW

**Comment by ebraminio** [comment]
Hi @vlj, thanks for the great work. I think if you use official release [tarball](https://www.freedesktop.org/software/harfbuzz/release/) your workflow will become much easier as it contains ragel generated sources (so you don't need to compile ragel first) and doesn't need to include your Makefile/config.h/hb-version.h which maybe get break soon and should modified with every update.

**Comment by ebraminio** [comment]
Also please consider disabling [directwrite support](https://github.com/behdad/harfbuzz/pull/340) of harfbuzz support. As the author of hb-directwrite I can safely say that it is less useful for regular harfbuzz users. I am going to disable default [Uniscribe](https://github.com/behdad/harfbuzz/pull/340) backend support also as I am pretty sure no one really is using that also on real world scenarios.

**Comment by vlj** [comment]
Thanks ! I initially assumed that github .zip were the official releases. Will update the portfile asap.

**Comment by vlj** [comment]
I removed directwrite support and make vcpkg use the freedesktop source tarball with the last push.

**Comment by ebraminio** [comment]
It looks great now. Thank you very much :)

**Comment by ras0219-msft** [comment]
Thanks for the great work, both of you!

**Pull request merged**
