### PR TITLE
[ffmpeg] fix feature dependencies

### PR DESCRIPTION
**Pull request by mcmtroffaes**
Currently, ffmpeg[core,ffmpeg], ffmpeg[core,ffplay], and ffmpeg[core,ffprobe] are failing to build the required tools due to missing dependencies. Furthermore, ffmpeg[core,x264], ffmpeg[core,x265], ffmpeg[core,avisynthplus], ffmpeg[core,fdk-aac], and ffmpeg[core,openssl] pull in all default features. This patch fixes all of that, with a few more minor improvements. Full list of changes:

* do not pull in default depedencies when specifying nonfree/gpl
* explicitly mark postproc as gpl
* add required dependencies for ffmpeg, ffplay, and ffprobe
* remove defunct ffserver feature (this feature was removed in ffmpeg a while ago)
* minor spelling fixes

---

- What does your PR fix? See above.

- Which triplets are supported/not supported? Have you updated the CI baseline? No changes.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)? Yes.

### CODE REVIEW

**Comment by mcmtroffaes** [comment]
I've just fixed a few more that I missed in my previous round. For reference, all these dependencies can be extracted from the configure script:

https://github.com/FFmpeg/FFmpeg/blob/47be5a505657f478636ff08cef45f5c4c201ad23/configure#L3684

**Comment by NancyLi1013** [comment]
Hi @mcmtroffaes 
Thanks for this PR. Have you tested these features?

**Comment by mcmtroffaes** [comment]
Yes, I've tested each of these individually. A lesson learnt here is that, for ffmpeg, we need to take care to mimick the dependencies listed in the configure file. If you request a feature but disable one of its dependencies, the ffmpeg configure script will disable the feature, without failing.

**Review by NancyLi1013 — APPROVED** [review]

**Review by ras0219-msft — APPROVED** [review]
Thanks for the PR!

**Comment by mcmtroffaes** [comment]
Thanks for merging!

**Pull request merged**
