### PR TITLE
Add autotools ports and fix libb2, libmagic for Mac

### PR DESCRIPTION
**Pull request by SeekingMeaning**
**Describe the pull request**

- What does your PR fix?
  - Might fix parts of issue #9600 (`libb2: does not support osx` and `libmagic missing dependency LIBTOOL`)
- Which triplets are supported/not supported? Have you updated the CI baseline?
  - Mac support only for autotools (autoconf, automake, libtool); yes
- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  - Yes (libb2 and libmagic require autotools on Mac, so I put them in this PR)

### CODE REVIEW

**Comment by JackBoosY** [comment]
Thanks,  we really need this PR.

**Comment by SeekingMeaning** [comment]
I just got libmagic working; should I push now?

**Comment by JackBoosY** [comment]
@SeekingMeaning Yes please.

**Comment by cenit** [comment]
May I ask why is linux not included in your autotools compatibility baseline? It would be great also for other ports if it was available

**Comment by SeekingMeaning** [comment]
@cenit Partly because I don't have a Linux machine 😛 but mostly because this PR is aimed towards getting CI fixed

**Comment by SeekingMeaning** [comment]
Closing this for now since CI works and the dependencies for this are kind of a mess.

**Comment by JackBoosY** [comment]
Can I use your changes to create new ports autotools?

**Comment by SeekingMeaning** [comment]
Yes, please do 😄

**Pull request closed without merging**
