### PR TITLE
[orc] update to 1.5.5

### PR DESCRIPTION
**Pull request by edmBernard**
update version to 1.5.4, adding support for zstd
rebase with vcpkg master

### CODE REVIEW

**Comment by edmBernard** [comment]
WIP: Somethings is broken with 1.5.4 and protobuf

**Comment by Rastaban** [comment]
In its current state I see failures on all windows triplets.

**Comment by edmBernard** [comment]
@Rastaban yes there is some change in Orc that break compatility with protobuf version. I have to work on it. I put the Tag Work in Progress but if you prefer I can delete it and recreate it when it will be done.

**Comment by Rastaban** [comment]
I'm okay with you leaving the PR open as you work on it.  Let us know if you would like us to post any failure logs from the test system.

**Comment by edmBernard** [comment]
@Rastaban I test on x64-linux and on x86-windows. It works on this two triplets. Can you send me log for triplet that fail ?

**Comment by Rastaban** [comment]
x64-windows-static is the only one currently failing

```
Building package orc[core]:x64-windows-static... 
Could not locate cached archive: C:\vsts\_work\2\s\archives\b0\b0f37022ceb51eb397e9a41d12ad6187fadfa733.zip
-- Downloading https://github.com/apache/orc/archive/bf5b7800930bfa030db83aba925d9d3b75852839.tar.gz...
-- Extracting source C:/vsts/_work/2/s/downloads/apache-orc-bf5b7800930bfa030db83aba925d9d3b75852839.tar.gz
-- Applying patch 0003-dependencies-from-vcpkg.patch
-- Using source at C:/vsts/_work/2/s/buildtrees/orc/src/3b75852839-af6004fd43
-- Configuring x64-windows-static
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: C:/vsts/_work/2/s/buildtrees/orc/x64-windows-static-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\vsts\_work\2\s\buildtrees\orc\config-x64-windows-static-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:269 (vcpkg_execute_required_process)
  ports/orc/portfile.cmake:32 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)


Error: Building package orc:x64-windows-static failed with: BUILD_FAILED
```
[config-x64-windows-static-out.log](https://github.com/Microsoft/vcpkg/files/2968810/config-x64-windows-static-out.log)

**Comment by edmBernard** [comment]
@Rastaban I think the PR is good now

**Pull request merged**
