### PR TITLE
[OpenVDB] update to v6.0

### PR DESCRIPTION
**Pull request by cenit**
as per title, this PR updates OpenVDB to v6.0 and adds compatibility with latest OpenEXR release. During the update, I took the chance to remove hardcoded paths in the portfile, using cmake modules included inside the port itself. I think that a future update recycling vcpkg cmake modules will be even better.

### CODE REVIEW

**Comment by cenit** [comment]
due to #5227 this update is also required

**Comment by cgolchert** [comment]
will this make it before 7.0 is released?

**Comment by cenit** [comment]
I have many opened PR now here on vcpkg. I gave my full availability to fix problems if necessary. It is becoming a little bit frustrating to not see any progress...

**Comment by cgolchert** [comment]
I REALLY appreciate your update.  Hopefully "someone with write access" will merge it.  That was the target of my previous comment.  I wonder who we can light on fire to get any attention like the stuff that seems to get updates every other day.

**Comment by cenit** [comment]
closed in favor of #5417

**Pull request closed without merging**
