### PR TITLE
[libdatachannel] Fix dependency not found

### LINKED ISSUE #35584: [libdatachannel] build failure
### Operating system

Linux

### Compiler

arm-linux-gnueabihf-gcc

### Steps to reproduce the behavior

```Shell
mkdir test-libdatachannel
cd test-libdatachannel
vcpkg new --application
vcpkg add port libdatachannel[srtp]
cat >main.cpp <<EOF
int main(int argc, char** argv) {
    return 0;
}
EOF
cat >CMakeLists.txt <<EOF
cmake_minimum_required(VERSION 3.14)
project(test-libdatachannel)
add_executable(test-libdatachannel main.cpp)
find_package(LibDataChannel CONFIG REQUIRED)
find_package(plog CONFIG REQUIRED)
find_package(libSRTP CONFIG REQUIRED)
target_link_libraries(test-libdatachannel PUBLIC LibDataChannel::LibDataChannelStatic)
EOF
cat >CMakePresets.json <<EOF
{
  "version": 3,
  "configurePresets": [
    {
      "name": "arm-linux-release",
      "binaryDir": "\${sourceDir}/build/arm-linux-release",
      "cacheVariables": {
        "CMAKE_BUILD_TYPE": "Release",
        "VCPKG_TARGET_TRIPLET": "arm-linux-release",
        "CMAKE_SYSTEM_NAME": "Linux",
        "CMAKE_SYSTEM_PROCESSOR": "arm",
        "CMAKE_C_COMPILER": "arm-linux-gnueabihf-gcc",
        "CMAKE_CXX_COMPILER": "arm-linux-gnueabihf-g++",
        "CMAKE_TOOLCHAIN_FILE": "\$env{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"
      }
    }
  ]
}
EOF
cmake --preset=arm-linux-release
```

### Failure logs

```bash
root@H610ITX /tmp/test-libdatachannel
# cmake --preset=arm-linux-release
Preset CMake variables:

  CMAKE_BUILD_TYPE="Release"
  CMAKE_CXX_COMPILER="arm-linux-gnueabihf-g++"
  CMAKE_C_COMPILER="arm-linux-gnueabihf-gcc"
  CMAKE_SYSTEM_NAME="Linux"
  CMAKE_SYSTEM_PROCESSOR="arm"
  CMAKE_TOOLCHAIN_FILE="/usr/local/vcpkg/scripts/buildsystems/vcpkg.cmake"
  VCPKG_TARGET_TRIPLET="arm-linux-release"

-- Running vcpkg install
Detecting compiler hash for triplet x64-linux...
Detecting compiler hash for triplet arm-linux-release...
All requested packages are currently installed.
Total install time: 271 ns
libdatachannel provides CMake targets:

  # this is heuristically generated, and may not be correct
  find_package(LibDataChannel CONFIG REQUIRED)
  target_link_libraries(main PRIVATE LibDataChannel::LibDataChannelStatic)

-- Running vcpkg install - done
-- Configuring done
CMake Error at /usr/local/vcpkg/scripts/buildsystems/vcpkg.cmake:598 (_add_executable):
  Target "test-libdatachannel" links to target "Usrsctp::Usrsctp" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:3 (add_executable)


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jimwang118**
Fixes  https://github.com/microsoft/vcpkg/issues/35584 https://github.com/microsoft/vcpkg/issues/35863

Add export config to usrsctp.
Add find_dependency(plog) and find_dependency(libSRTP CONFIG) in the LibDataChannelConfig.cmake file.

- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] ~~SHA512s are updated for each updated download~~
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

Usage test pass with following triplets:

```
x64-windows
x64-windows-static
```

### CODE REVIEW

**Comment by dg0yt** [comment]
Remember that the package name and targets need to be prefixed as *unofficial*.

**Review by Adela0814 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the fix!

**Comment by vipcxj** [comment]
I think this cause issue [#1093](https://github.com/paullouisageneau/libdatachannel/issues/1093),

**Comment by dg0yt** [comment]
The CMake config changes don't match the CMakeLists.txt changes.

**Pull request merged**
