### PR TITLE
[tinyxml] Use proper CMake targets

### LINKED ISSUE #11382: [tinyxml] Use proper CMake Targets
****

**Is your feature request related to a problem? Please describe.**
The current version of the tinyxml port doesn't actually differentiate between the debug and release library that it builds in it's tinyxml-config.cmake file.  It _always_ put the release version into the tinyxml_LIBRARIES variable:
[configfileisbugged](https://github.com/microsoft/vcpkg/blob/5504dfa7da38a65981868fc7885744ac5d8f234e/ports/tinyxml/tinyxml-config.cmake#L11)

For now, most dependencies of TinyXML have been "getting away with it", as people typically just write their own FindTinyXML.cmake script that sidesteps the problem.  But if you genuinely use the tinyxml_LIBRARIES variable set by this port as a link library for a Debug build configuration, you will (at least on Windows) get a linker error when the linker does what you ask and tries to link a pre-built Release library into a Debug library.

**Proposed solution**
Use proper exported targets as the CMake gods intended.  Export a target (perhaps named tinyxml::tinyxml to follow the convention used in tinyxml2) that includes the appropriate libraries and include directories for the current build type.

**Describe alternatives you've considered**
One could always just ignore the tinyxml-config.cmake file and just write your own FindTinyXML script, but this is hacky.

**Additional context**
None presently identified.

### PR DESCRIPTION
**Pull request by TrentWeiss**
**Describe the pull request**

- What does your PR fix? Fixes #11382
Uses CMake's concept of exported/imported targets to make a significantly better tinyxml-config.cmake file. 

- Which triplets are supported/not supported? Have you updated the CI baseline?
AFAIK, the standard triplets still work with these changes.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
On my honor as a Boy Scout, I have diligently read this document and did not see any issues.

### CODE REVIEW

**Comment by Electric-Turtle** [comment]
The failure logs of the CI don't contain anything related to the build of tinyxml or vcpkg in general.  They appear to be some sort of Azure error. I don't really know how to interpret them.

**Comment by PhoebeHui** [comment]
@Electric-Turtle, thanks for the PR! the CI failures doesn't relate to this change, It passed after rerun.

For suggestion from @traversaro in https://github.com/microsoft/vcpkg/issues/11382#issuecomment-629385945, I agree to rename it to 'unofficial-tinyxml', @ras0219-msft, what do you think?

**Comment by Electric-Turtle** [comment]
> @Electric-Turtle, thanks for the PR! the CI failures doesn't relate to this change, It passed after rerun.
> 
> For suggestion from @traversaro in [#11382 (comment)](https://github.com/microsoft/vcpkg/issues/11382#issuecomment-629385945), I agree to rename it to 'unofficial-tinyxml', @ras0219-msft, what do you think?

I'm fine with that. I will make the update.

**Comment by Electric-Turtle** [comment]
I made the change to name the target "unofficial-tinyxml".  However, the build for protobuf seems to fail on the x64-uwp and both arm triplets.  I don't know why this would happen, protobuf doesn't depend on tinyxml at all. I also checked out the current master branch and got the exact same build errors when attempting to build protobuf on x64-uwp (I don't have an ARM machine available for testing myself). I think a more recent commit to master has broken the protobuf build for those triplets

**Comment by PhoebeHui** [comment]
@Electric-Turtle, thanks for the updates!

Protobuf failures doesn't relate to your changes, it has been fixed now.

@strega-nil, could you help do further review?

**Comment by strega-nil** [comment]
Yeah, this looks better to me. Thanks @Electric-Turtle :)

**Pull request merged**
