### PR TITLE
[USD] update to 22.08

### LINKED ISSUE #26920: [USD] update to 22.08
Library name: usd

New version number: 22.08

Other information that may be useful (release notes, etc...)
https://github.com/PixarAnimationStudios/USD/releases/tag/v22.08

This request is from https://github.com/PixarAnimationStudios/USD/pull/2041.

### PR DESCRIPTION
**Pull request by Cheney-W**
- #### What does your PR fix?
  Fixes https://github.com/microsoft/vcpkg/issues/26920
  
  No feature need to be tested.

### CODE REVIEW

**Comment by meshula** [comment]
USD version 22.11 has landed. It should be ready to update into vcpkg. Please let me know if there's any questions.

**Comment by LilyWangLL** [comment]
Closing this PR since it seems that no progress is being made. Please ping us to reopen if work is still being done.

**Comment by meshula** [comment]
The work at our end (Pixar) is finished. USD version 23.02 has been released since my last update.

**Comment by Cheney-W** [comment]
What is the current state of this issue: https://github.com/PixarAnimationStudios/USD/issues/1600 ?

**Comment by meshula** [comment]
The migration is planned for Vfxplatform CY2024 (https://vfxplatform.com). Vfxplatform cy2024 will begin formalization in August, so I would look for motion on https://github.com/PixarAnimationStudios/USD/issues/1600 in support of that time frame.

I'm not a vcpkg maintainer, so I am unfamiliar with vcpkg's support for tbb vs Onetbb. It is possible to build tbb with a custom namespace for USD, and link it to a program that uses OneTBB, but I do not know if that is a viable path for vcpkg in the mean time.

I am fine with closing this request and perhaps revisiting it when the OneTbb migration is finished. My main motivation for pursuing this topic is to help move this issue forward: https://github.com/PixarAnimationStudios/USD/pull/2041 ~ it will be great to be able to promote vcpkg as a way for end users to obtain usd, when they are able to obtain the current release version.

**Pull request closed without merging**
