### PR TITLE
[openssl] install pkgconfig file

### PR DESCRIPTION
**Pull request by Perlmint**
- What does your PR fix?

Install generated pkg-config file of OpenSSL

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

yes

### CODE REVIEW

**Comment by Perlmint** [comment]
@JackBoosY Could you review this, please?

**Comment by JackBoosY** [comment]
Ops, sorry. I forgot this PR completely.

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
cppcms regression will be fixed in #15473.

**Pull request merged**
