### PR TITLE
uwp fixes for libxml2

### PR DESCRIPTION
**Pull request by stammen**
This PR adds the fixes to build and install libxml2 for x86-uwp and x64-uwp targets. The arm-uwp build is broken as the cmake find_program() is broken for arm builds when searching for nmake. 

For example, in vcpkg\ports\libxml2\portfile.cmake at line 18:

find_program(NMAKE nmake) returns NMAKE-NOTFOUND for arm builds.

This pull request depends on PR: https://github.com/Microsoft/vcpkg/pull/365 for uwp libiconv support.

### CODE REVIEW

**Comment by stammen** [comment]
Need to fix WACK errors

**Comment by HppZ** [comment]
API WSACleanup in wsock32.dll is not supported for this application type. libxml2.dll calls this API.
API WSAGetLastError in wsock32.dll is not supported for this application type. libxml2.dll calls this API.
API WSAStartup in wsock32.dll is not supported for this application type. libxml2.dll calls this API.
API __WSAFDIsSet in wsock32.dll is not supported for this application type. libxml2.dll calls this API.
API bind in wsock32.dll is not supported for this application type. libxml2.dll calls this API.
API closesocket in wsock32.dll is not supported for this application type. libxml2.dll calls this API.
API connect in wsock32.dll is not supported for this application type. libxml2.dll calls this API.
API gethostbyname in wsock32.dll is not supported for this application type. libxml2.dll calls this API.
API getsockname in wsock32.dll is not supported for this application type. libxml2.dll calls this API.
API getsockopt in wsock32.dll is not supported for this application type. libxml2.dll calls this API.
API htons in wsock32.dll is not supported for this application type. libxml2.dll calls this API.
API ioctlsocket in wsock32.dll is not supported for this application type. libxml2.dll calls this API.
API listen in wsock32.dll is not supported for this application type. libxml2.dll calls this API.
API recv in wsock32.dll is not supported for this application type. libxml2.dll calls this API.
API select in wsock32.dll is not supported for this application type. libxml2.dll calls this API.
API send in wsock32.dll is not supported for this application type. libxml2.dll calls this API.
API socket in wsock32.dll is not supported for this application type. libxml2.dll calls this API.
API __CxxFrameHandler4 in vcruntime140_1_app.dll is not supported for this application type. App5.exe calls this API.

**Comment by HppZ** [comment]
Hi, @stammen I think WACK errors are still not fixed yet, right?

**Comment by HppZ** [comment]
@JackBoosY WACK issue with libxml2

**Pull request closed without merging**
