### PR TITLE
Update applocal.ps1

### LINKED ISSUE #2801: Can not copy dll files after build
The path contains non-ascii characters `代码库`, Is a character encoding conversion problem?

``` text
1>已完成代码的生成
1>LCUI.vcxproj -> E:\代码库\GitHub\LCUI\build\windows\..\..\bin\Debug\LCUI.dll
1>LCUI.vcxproj -> E:\代码库\GitHub\LCUI\build\windows\..\..\bin\Debug\LCUI.pdb (Partial PDB)
1>D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4222,5): error MSB3030: 无法复制文件“E:\�����\GitHub\LCUI\bin\Debug\libxml2.dll”，原因是找不到该文件。
1>D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4222,5): error MSB3030: 无法复制文件“E:\�����\GitHub\LCUI\bin\Debug\zlibd1.dll”，原因是找不到该文件。
1>D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4222,5): error MSB3030: 无法复制文件“E:\�����\GitHub\LCUI\bin\Debug\lzma.dll”，原因是找不到该文件。
1>D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4222,5): error MSB3030: 无法复制文件“E:\�����\GitHub\LCUI\bin\Debug\libiconv.dll”，原因是找不到该文件。
1>D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4222,5): error MSB3030: 无法复制文件“E:\�����\GitHub\LCUI\bin\Debug\libcharset.dll”，原因是找不到该文件。
1>已完成生成项目“LCUI.vcxproj”的操作 - 失败。
========== 生成: 成功 0 个，失败 1 个，最新 0 个，跳过 0 个 ==========
```

### PR DESCRIPTION
**Pull request by shadowxiali**
Fix #2801 , chinese char path fail

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for the PR!

I don't totally understand the problem this fixes, and this doesn't currently work on my machine:

```powershell
D:\src\vcpkg> set-content -path foo.txt -value "" -encoding UTF
Set-Content : Cannot bind parameter 'Encoding'. Cannot convert value "UTF" to type "Microsoft.PowerShell.Commands.FileSystemCmdletProviderEncoding". Error: "The identifier name UTF cannot be processed because it is either too similar or identical to the following enumerator names: UTF8, UTF7, UTF32. Use a more specific identifier name."
At line:1 char:47
+ set-content -path foo.txt -value "" -encoding UTF
+                                               ~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-Content], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.SetContentCommand
```

The created file in this case is blank regardless of the `-encoding` setting, so I don't see how this could possibly fix any issue. Is the issue that `$copiedFilesLog` has chinese characters in the path?

**Comment by shadowxiali** [comment]
sorry, the correct value is **UTF8**
PS C:\Users\xiali.000> set-content -path foo.txt -value "" -encoding **UTF8**
PS C:\Users\xiali.000>

**Comment by vicroms** [comment]
Hi @shadowxiali 

There are some concerns regarding this change, see comments on #5301.
Explicitly, do you know if these changes introduce Byte Order Marks?

**Comment by ras0219-msft** [comment]
Thanks for this PR!

**Pull request merged**
