### PR TITLE
[zlmediakit] update zlmediakit to 20240330.0

### PR DESCRIPTION
**Pull request by xia-chu**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html).
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [x] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by BillyONeal** [comment]
Can you explain why you're adding a default feature like this? Other than that everything seems reasonble to me...

**Comment by xia-chu** [comment]
> Can you explain why you're adding a default feature like this? Other than that everything seems reasonable to me...

Many newcomers who are just getting started don't know how to use vcpkg and zlmediakit. Enabling all features by default can reduce their mental burden, and there is no cost to doing so.

**Review by FrankXie05 — DISMISSED** [review]

**Comment by BillyONeal** [comment]
The problem is that getting default features to be *off* can be difficult for customers to do, for example: https://github.com/microsoft/vcpkg/issues/35694

In general, we try to avoid making a feature default unless the resulting library is ~broken without one. For example, a libarchive with no archive backends is worthless.

> Enabling all features by default can reduce their mental burden, and there is no cost to doing so.

There are costs to doing so because this adds a dependency on that feature for callers who might not be expecting this. Is there a particular thing about `zlmediakit` which makes it not worthwhile for the vast majority of users with this feature off?

**Comment by BillyONeal** [comment]
Tagging vcpkg-team-review because we need to discuss how we describe how default features are to be used

**Comment by xia-chu** [comment]
> The problem is that getting default features to be off can be difficult for customers to do, for example: https://github.com/microsoft/vcpkg/issues/35694

OK, i had disable sctp default, and pushed new commits, thanks!

**Comment by BillyONeal** [comment]
Thanks for the update!

**Pull request merged**
