### PR TITLE
Package lzo

### PR DESCRIPTION
**Pull request by OlafvdSpek**

### CODE REVIEW

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Review by ras0219-msft — COMMENTED** [review]
We will need to bump rapidjson's version number as well as make sure Bond builds using the new rapidjson. @chwarr has bond been updated to use the released version of rapidjson?

**Comment by chwarr** [comment]
Bond as of https://github.com/Microsoft/bond/commit/52989c8545a78e058ce6c448f3b945d9b87d955b works with RapidJSON v1.0.0 and v1.1.0. We haven't yet bumped the submodule in Bond repository yet, but, IIRC, in vcpkg we use whatever RapidJSON can be found.

Do you need me to update Bond in vcpkg?

**Comment by ras0219-msft** [comment]
If you'd like to make the PR, I'd be happy to accept it :). Otherwise, we can pretty easily update it ourselves. What commit ID would you consider the new latest stable?

**Comment by chwarr** [comment]
Just bumping the versions for Bond isn't working. Seems that something changed in wrt. `BOOST_ALL_NO_LIB`. Haven't dug into it myself. If you know a fix for this off the top of your head, that would be nice.

As for a good commit from Bond to use, the tip of master (https://github.com/Microsoft/bond/commit/a3ff1018973ade0c9abde435d42d3dee6fcf326c) is fine. Though, you may run into some problems with non-ASCII characters that crept into the Bond code base. I'm scrubbing them out now.

**Comment by ras0219-msft** [comment]
Ok, the change is that we need a way to disable "Boost_USE_STATIC_LIBS". In order to enable the user to choose between the boost static libs or the dynamic libs, we rename the import libraries for boost to always look like the dynamic libraries.

In `cmake\Config.cmake`, I was able to achieve this by changing the appropriate line to
```cmake
set (Boost_USE_STATIC_LIBS ON CACHE)
```
which will set the option only if it was not previously set. Then, we can override it in the portfile.

Would you like me to use the commit above + a patch, or would you like to find a solution we can commit upstream first?

**Comment by ras0219-msft** [comment]
@OlafvdSpek When I tried to build this locally (for the x86-windows triplet), the link fails because lzo expects `__setargv(void);` to exist. AFAICT, this was an implementation detail of `msvcrt.lib` which was never supported and was removed in the newer CRTs.

```
       "D:\src\vcpkg\buildtrees\lzo\x86-windows-rel\install.vcxproj" (default target) (1) ->
       "D:\src\vcpkg\buildtrees\lzo\x86-windows-rel\ALL_BUILD.vcxproj" (default target) (3) ->
       "D:\src\vcpkg\buildtrees\lzo\x86-windows-rel\dict.vcxproj" (default target) (5) ->
       (Link target) -> 
         dict.obj : error LNK2019: unresolved external symbol ___setargv referenced in function __setargv [D:\src\vcpkg\buildtrees\lzo\x86-windows-rel\dict.vcxproj]
         D:\src\vcpkg\buildtrees\lzo\x86-windows-rel\Release\dict.exe : fatal error LNK1120: 1 unresolved externals [D:\src\vcpkg\buildtrees\lzo\x86-windows-rel\dict.vcxproj]
```

It doesn't look like this function is ever called elsewhere in the sources, so I think the right answer is to patch the declaration out. Does that sound fine to you?

**Comment by chwarr** [comment]
Bond doesn't build against the Boost dynamic libraries, so a patch makes more sense for this.

**Comment by OlafvdSpek** [comment]
@ras0219-msft Sounds good, I did that locally but forgot and don't know how to include it in the pkg.

**Comment by ras0219-msft** [comment]
Ok, I merged the first commit of this PR. I'll make a second PR about updating bond and rapidjson.

Thanks for submitting this, @OlafvdSpek :)!

**Pull request closed without merging**
