### PR TITLE
[vcpkg_find_acquire_program(CLANG).cmake] update window clang version to 17.0.6

### PR DESCRIPTION
**Pull request by c8ef**
As title.

### CODE REVIEW

**Comment by Neumann-A** [comment]
clang 17 and 18 are broken on windows

**Comment by c8ef** [comment]
Got it.

**Comment by c8ef** [comment]
Does clang-16 work on windows? @Neumann-A

**Comment by Neumann-A** [comment]
Yes but why do you want to update?

**Pull request closed without merging**
