### PR TITLE
[upb] Fix uwp build

### PR DESCRIPTION
**Pull request by JackBoosY**
Fix uwp build, add some compile options.

Related: #9980.

### CODE REVIEW

**Comment by Noemata** [comment]
I took a look at: JackBoosY:dev/jack/9980

It fails to build with this error:


CMake Error at scripts/cmake/vcpkg_fail_port_install.cmake:89 (message):
  openssl-windows is only for Windows Desktop

  Target 'UWP' not supported by openssl-windows!

Besides, this is not the current 1.27 release of grpc.

**Comment by JackBoosY** [comment]
@Noemata Did you build `grpc:x64-uwp`?

**Comment by Noemata** [comment]
I did try to build grpc:x64-uwp from your repo.  Build failed at openssl part.

**Comment by JackBoosY** [comment]
@Noemata Sorry for late.
Can you provide all the information output from the command line / powershell?

**Review by PhoebeHui — APPROVED** [review]

**Comment by JackBoosY** [comment]
@Noemata The openssl part will fix in #10366.

**Comment by Noemata** [comment]
Thanks for the notification @JackBoosY.  What I'm curious about is the fact that someone is already building gRPC for uwp in order to produce this (https://www.nuget.org/packages/Grpc/) nuget package.  Can some of this activity not be coordinated?  I'm guessing Google is doing this work on behalf of Microsoft?  It's great to be able to leverage VCPKG instead of having to rely on other parties to build such libs.  Also, if Google is able to produce lib builds for Microsoft platforms, I should think Microsoft can do so even better.

**Comment by JackBoosY** [comment]
@Noemata The official nuget package provided by grpc does not use the vcpkg dependencies, so we still need to fix this issue.

**Comment by Noemata** [comment]
Thank you for the clarification @JackBoosY.

**Comment by ras0219-msft** [comment]
LGTM, thanks!

**Comment by Noemata** [comment]
Tried building gRPC, same issue as before with abseil.  VCPKG gets tripped up by whatever is wrong with the ninja build setup.  I did describe this in detail in another posting.

Very disappointing.

Extracting git...
-- Note: abseil only supports static library linkage. Building static library.
-- Downloading https://github.com/abseil/abseil-cpp/archive/06f0e767d13d4d68071c4fc51e25724e0fc8bc74.tar.gz...
-- Extracting source D:/vcpkg/downloads/abseil-abseil-cpp-06f0e767d13d4d68071c4fc51e25724e0fc8bc74.tar.gz
-- Applying patch fix-lnk2019-error.patch
-- Applying patch fix-uwp-build.patch
-- Using source at D:/vcpkg/buildtrees/abseil/src/4e0fc8bc74-c40446395f
-- Configuring x64-uwp
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: D:/vcpkg/buildtrees/abseil/x64-uwp-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\vcpkg\buildtrees\abseil\config-x64-uwp-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:295 (vcpkg_execute_required_process)
  ports/abseil/portfile.cmake:14 (vcpkg_configure_cmake)
  scripts/ports.cmake:90 (include)


Error: Building package abseil:x64-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: abseil:x64-uwp
  Vcpkg version: 2020.02.04-nohash-external

**Comment by Noemata** [comment]
This is using the 10005 commit.

**Comment by JackBoosY** [comment]
@Noemata Here is my console output:
```
PS F:\vcpkg> .\vcpkg.exe install grpc:x64-uwp
Computing installation plan...
The following packages will be built and installed:
  * abseil[core]:x64-uwp
    grpc[core]:x64-uwp
  * upb[core]:x64-uwp
Additional packages (*) will be modified to complete this operation.
Starting package 1/3: upb:x64-uwp
Building package upb[core]:x64-uwp...
-- Note: upb only supports static library linkage. Building static library.
-- Using cached F:/vcpkg/downloads/protocolbuffers-upb-9effcbcb27f0a665f9f345030188c0b291e32482.tar.gz
-- Using source at F:/vcpkg/buildtrees/upb/src/b291e32482-5b4f85036a
-- Configuring x64-uwp
-- Building x64-uwp-dbg
-- Building x64-uwp-rel
-- Installing: F:/vcpkg/packages/upb_x64-uwp/share/upb/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package upb[core]:x64-uwp... done
Installing package upb[core]:x64-uwp...
Installing package upb[core]:x64-uwp... done
Elapsed time for package upb:x64-uwp: 1.094 min
Starting package 2/3: abseil:x64-uwp
Building package abseil[core]:x64-uwp...
-- Note: abseil only supports static library linkage. Building static library.
-- Using cached F:/vcpkg/downloads/abseil-abseil-cpp-06f0e767d13d4d68071c4fc51e25724e0fc8bc74.tar.gz
-- Using source at F:/vcpkg/buildtrees/abseil/src/4e0fc8bc74-c40446395f
-- Configuring x64-uwp
-- Building x64-uwp-dbg
-- Building x64-uwp-rel
-- Installing: F:/vcpkg/packages/abseil_x64-uwp/share/abseil/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package abseil[core]:x64-uwp... done
Installing package abseil[core]:x64-uwp...
Installing package abseil[core]:x64-uwp... done
Elapsed time for package abseil:x64-uwp: 2.505 min
Starting package 3/3: grpc:x64-uwp
Building package grpc[core]:x64-uwp...
-- Note: grpc only supports static library linkage. Building static library.
-- Using cached F:/vcpkg/downloads/grpc-grpc-v1.27.3.tar.gz
-- Using source at F:/vcpkg/buildtrees/grpc/src/v1.27.3-191df9b830
-- Configuring x64-uwp
-- Building x64-uwp-dbg
-- Building x64-uwp-rel
-- Installing: F:/vcpkg/packages/grpc_x64-uwp/share/grpc/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package grpc[core]:x64-uwp... done
Installing package grpc[core]:x64-uwp...
Installing package grpc[core]:x64-uwp... done
Elapsed time for package grpc:x64-uwp: 9.167 min

Total elapsed time: 12.77 min

The package grpc:x64-uwp provides CMake targets:

    find_package(gRPC CONFIG REQUIRED)
    # Note: 5 target(s) were omitted.
    target_link_libraries(main PRIVATE gRPC::gpr gRPC::grpc gRPC::grpc++ gRPC::grpc++_alts)

    find_package(modules CONFIG REQUIRED)
    target_link_libraries(main PRIVATE c-ares::cares)

PS F:\vcpkg>
```
So, please provide failure logs such as _D:\vcpkg\buildtrees\abseil\config-x64-uwp-out.log_.

**Comment by Noemata** [comment]
My apologies, I must have gotten the repo too soon.  I did a fresh clone of the vcpkg master repo this morning and the results were much better.  However, Now I get this:

```
Building package openssl-uwp[core]:x64-uwp... done
Installing package openssl-uwp[core]:x64-uwp...
Installing package openssl-uwp[core]:x64-uwp... done
Elapsed time for package openssl-uwp:x64-uwp: 3.113 min
Starting package 3/8: openssl-windows:x64-uwp
Building package openssl-windows[core]:x64-uwp...
CMake Error at scripts/cmake/vcpkg_fail_port_install.cmake:93 (message):
  openssl-windows is only for Windows Desktop

  Target 'UWP' not supported by openssl-windows!

Call Stack (most recent call first):
  ports/openssl-windows/portfile.cmake:1 (vcpkg_fail_port_install)
  scripts/ports.cmake:90 (include)


Error: Building package openssl-windows:x64-uwp failed with: BUILD_FAILED
```

Not sure if someone pushed in something new the break the openssl build for UWP, since this was an older problem.  Suggest @JackBoosY have another look.  Looks like someone added a condition to prevent building openssl for UWP.

**Comment by Noemata** [comment]
I did notice in the build log @JackBoosY provides above, openssl is never listed as part of the build process?

**Comment by Noemata** [comment]
In case this helps, I was able to build the following individually:

.\vcpkg.exe install upb[core]:x64-uwp --recurse
.\vcpkg.exe install protobuf[core]:x64-uwp --recurse
.\vcpkg.exe install abseil[core]:x64-uwp --recurse
.\vcpkg.exe install zlib[core]:x86-uwp --recurse

It was nice to see upb and abseil in there.

**Comment by JackBoosY** [comment]
@Noemata Openssl does have dependency issue, and it will fix in #10366:

You can check changes [here](https://github.com/microsoft/vcpkg/pull/10366/files#diff-e124ec5c4b13f3337be9a2c76d0e996dR5).

**Pull request merged**
