### PR TITLE
[cpuinfo] Fix cpuid-dump is not generated with x86-windows

### LINKED ISSUE #24713: [cpuinfo] Build error
# Host Environment

* **OS:** Windows 10 Pro Version 21H2 build 19044.1706 with Windows Feature Experience Pack 120.2212.4170.0
* **Compiler:** Microsoft Visual Studio Community 2022 Version 17.2.0
* **vcpkg-tool version:** 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
* **vcpkg-scripts version:** b9298e472 2022-05-13 (19 hours ago)

# To Reproduce

`./vcpkg.exe install cpuinfo[core,tools] --triplet x86-windows`

# Failure logs

```
Building cpuinfo[core,tools]:x86-windows...
-- Note: cpuinfo only supports static library linkage. Building static library.
-- Using cached pytorch-cpuinfo-b40bae27785787b6dd70788986fd96434cf90ae2.tar.gz.
-- Cleaning sources at D:/vcpkg/buildtrees/cpuinfo/src/434cf90ae2-25e833541a.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/pytorch-cpuinfo-b40bae27785787b6dd70788986fd96434cf90ae2.tar.gz
-- Using source at D:/vcpkg/buildtrees/cpuinfo/src/434cf90ae2-25e833541a.clean
-- Found external ninja('1.10.2').
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Fixing pkgconfig file: D:/vcpkg/packages/cpuinfo_x86-windows/lib/pkgconfig/libcpuinfo.pc
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at D:/vcpkg/downloads/tools/msys2/9a1ec3f33446b195
-- Fixing pkgconfig file: D:/vcpkg/packages/cpuinfo_x86-windows/debug/lib/pkgconfig/libcpuinfo.pc
CMake Error at scripts/cmake/vcpkg_copy_tools.cmake:70 (message):
  Couldn't find tool "cpuid-dump":

      "D:/vcpkg/packages/cpuinfo_x86-windows/bin/cpuid-dump.exe" does not exist
Call Stack (most recent call first):
  ports/cpuinfo/portfile.cmake:70 (vcpkg_copy_tools)
  scripts/ports.cmake:146 (include)

error: building cpuinfo:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+cpuinfo
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[cpuinfo]+Build+error
Include '[cpuinfo] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: b9298e472 2022-05-13 (19 hours ago)

```
# Log Files

* [install-x86-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/8693674/install-x86-windows-rel-out.log)

# Additional Context

cpuinfo builds for x64-windows without issue.

### PR DESCRIPTION
**Pull request by Cheney-W**
**Describe the pull request**

- #### What does your PR fix?
  Fixes https://github.com/microsoft/vcpkg/issues/24713

  1. Modify portfile.cmake to pass the correct values.
  2. Add a condition to make the option to use the value passed by portfile.cmake under windows.

### CODE REVIEW

**Review by LilyWangLL — APPROVED** [review]

**Comment by BillyONeal** [comment]
Can you explain what this patch does? Has upstream been notified?

(Normally I wouldn't have questions like that about what look like relatively simple build system changes, but this port is literally `cpuinfo` so it likely cares a *lot* about the specific CPU it wants to target)

**Comment by Cheney-W** [comment]
I added this patch to make following part set in portfile.cmake take effect in cmakelist.txt of source:
```
set(CPUINFO_TARGET_PROCESSOR_param "")
if(VCPKG_TARGET_IS_WINDOWS)
    # NOTE: arm64-windows is unsupported for now;
    # see https://github.com/pytorch/cpuinfo/pull/82 for updates
    # NOTE: arm-windows is unsupported
    if(VCPKG_TARGET_ARCHITECTURE STREQUAL "x86")
        set(CPUINFO_TARGET_PROCESSOR_param "-DCPUINFO_TARGET_PROCESSOR=i386")
    elseif(VCPKG_TARGET_ARCHITECTURE STREQUAL "x64")
        set(CPUINFO_TARGET_PROCESSOR_param "-DCPUINFO_TARGET_PROCESSOR=AMD64")
    elseif(VCPKG_TARGET_ARCHITECTURE STREQUAL "arm")
        set(CPUINFO_TARGET_PROCESSOR_param "-DCPUINFO_TARGET_PROCESSOR=ARM")
    elseif(VCPKG_TARGET_ARCHITECTURE STREQUAL "arm64")
        set(CPUINFO_TARGET_PROCESSOR_param "-DCPUINFO_TARGET_PROCESSOR=ARM64")
    endif()
endif()
```
If the target is windows, `CPUINFO_TARGET_PROCESSOR_param` will be passed as an option to CMakeLists.txt of source by vcpkg_cmake_configure(), this option sets different values for CPUINFO_TARGET_PROCESSOR under different architectures.

But CMakeLists.txt of source have following content:
`SET(CPUINFO_TARGET_PROCESSOR "${CMAKE_SYSTEM_PROCESSOR}")`
This causes the value of `CPUINFO_TARGET_PROCESSOR` always be `${CMAKE_SYSTEM_PROCESSOR}` even if the target is window.

If cpuinfo install with x86-windows, the value of `${CMAKE_SYSTEM_PROCESSOR}` will be x86, this leads to a false result in the following judgment in CMakeLists.txt of source:
```
  IF(CPUINFO_TARGET_PROCESSOR MATCHES "^(i[3-6]86|AMD64|x86_64)$")
    ADD_EXECUTABLE(cpuid-dump tools/cpuid-dump.c)
    CPUINFO_TARGET_ENABLE_C99(cpuid-dump)
    CPUINFO_TARGET_RUNTIME_LIBRARY(cpuid-dump)
    TARGET_INCLUDE_DIRECTORIES(cpuid-dump BEFORE PRIVATE src)
    TARGET_INCLUDE_DIRECTORIES(cpuid-dump BEFORE PRIVATE include)
    INSTALL(TARGETS cpuid-dump RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
  ENDIF()
```
This is also the reason why `cpuid-dump` is not generated under x86-windows.
To solve this problem, I originally planned two scenarios:
1. Modify the part of the copy tool in the portfile.cmake so that it does not copy cpuid-dump under x86.
2. Modify the value of `CPUINFO_TARGET_PROCESSOR` to i386 when triplet is x86-windows, and add judgment to make `CPUINFO_TARGET_PROCESSOR` use the value passed by vcpkg_cmake_configure instead of `${CMAKE_SYSTEM_PROCESSOR}`.

Because there is no documentation that `cpuid-dump` is not available under x86, I used scheme 2.

**Comment by BillyONeal** [comment]
@LilyWangLL My point about upstream needing to be involved stands. However, I did my own digging here and am proposing a competing resolution here, which upstream has already OK'd: https://github.com/microsoft/vcpkg/pull/25258

**Comment by Cheney-W** [comment]
Dup to https://github.com/microsoft/vcpkg/pull/25258

**Pull request closed without merging**
