### PR TITLE
[entt] Update to 3.10.0

### PR DESCRIPTION
**Pull request by ghost**
**Describe the pull request**

- #### What does your PR fix?
Updates EnTT to 3.10.0

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
No change to triplet support, tested on x64-osx

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Review by Adela0814 — APPROVED** [review]

**Comment by sbhutch** [comment]
Added license field to `ports/entt/vcpkg.json` as requested through github-actions.

**Comment by Adela0814** [comment]
@sbhutch  please run `./vcpkg x-add-version entt` to add a new version.

**Comment by sbhutch** [comment]
@Adela0814 done

**Comment by strega-nil-ms** [comment]
Thanks!

**Pull request merged**
