### PR TITLE
[vcpkg] Add static triplet for arm64-windows

### PR DESCRIPTION
**Pull request by orudge**
This pull requests adds a new community triplet, **arm64-windows-static** (ARM64, Windows Desktop, build static libraries, use static CRT).

I have tested a handful of libraries I require for a project (including libpng, lzma, lzo2, SDL2, zlib) using VC++ 2019 16.5.5 and have not noticed any issues.

### CODE REVIEW

**Review by JackBoosY — CHANGES_REQUESTED** [review]
Please add `!triplets/community/arm64-windows-static.cmake` to file `.gitignore`.

See [example](https://github.com/microsoft/vcpkg/commit/ecff0166637f958b0272d10f5f308c83e25d4acb).

**Comment by orudge** [comment]
> Please add `!triplets/community/arm64-windows-static.cmake` to file `.gitignore`.

I've pushed an update with these changes, thanks.

**Comment by JackBoosY** [comment]
Waiting for #11459 merge.

**Review by JackBoosY — APPROVED** [review]

**Comment by strega-nil** [comment]
Alright cool, thanks @orudge :)

**Pull request merged**
