### PR TITLE
[angle] new port

### PR DESCRIPTION
**Pull request by atkawa7**

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for the PR!

Could you use `vcpkg_from_github()` and grab from https://github.com/google/angle instead? This way we can have a stable ref.

**Comment by atkawa7** [comment]
@ras0219-msft Thanks. I have used `vcpkg_from_github()`.
>>> We might want to also consider pulling from https://github.com/Microsoft/angle to get (better?) UWP support.

Definitely would need some help as I am not sure about that one.

**Comment by ras0219-msft** [comment]
Thanks!

When trying to build this on our CI machine, I get:

```
2017-06-20T10:48:05.4215889Z ________ running 'C:\Python27\python.exe gyp/gyp_angle' in 'D:\vcpkg-live-ci\_work\1\s\buildtrees\angle\angle.git'
2017-06-20T10:48:05.4215889Z Updating projects from gyp files...
2017-06-20T10:48:05.4215889Z 
2017-06-20T10:48:05.4215889Z Traceback (most recent call last):
2017-06-20T10:48:05.4215889Z 
2017-06-20T10:48:05.4215889Z   File "gyp/gyp_angle", line 73, in <module>
2017-06-20T10:48:05.4215889Z 
2017-06-20T10:48:05.4215889Z     generateProjects(args)
2017-06-20T10:48:05.4215889Z 
2017-06-20T10:48:05.4215889Z   File "gyp/gyp_angle", line 38, in generateProjects
2017-06-20T10:48:05.4215889Z 
2017-06-20T10:48:05.4215889Z     gyp.main(args)
2017-06-20T10:48:05.4215889Z 
2017-06-20T10:48:05.4215889Z   File ".\third_party\gyp\pylib\gyp\__init__.py", line 538, in main
2017-06-20T10:48:05.4215889Z 
2017-06-20T10:48:05.4215889Z     return gyp_main(args)
2017-06-20T10:48:05.4215889Z 
2017-06-20T10:48:05.4215889Z   File ".\third_party\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
2017-06-20T10:48:05.4215889Z 
2017-06-20T10:48:05.4215889Z     options.duplicate_basename_check)
2017-06-20T10:48:05.4215889Z 
2017-06-20T10:48:05.4215889Z   File ".\third_party\gyp\pylib\gyp\__init__.py", line 98, in Load
2017-06-20T10:48:05.4215889Z 
2017-06-20T10:48:05.4215889Z     generator.CalculateVariables(default_variables, params)
2017-06-20T10:48:05.4215889Z 
2017-06-20T10:48:05.4215889Z   File ".\third_party\gyp\pylib\gyp\generator\ninja.py", line 1692, in CalculateVariables
2017-06-20T10:48:05.4215889Z 
2017-06-20T10:48:05.4215889Z     gyp.msvs_emulation.CalculateCommonVariables(default_variables, params)
2017-06-20T10:48:05.4215889Z 
2017-06-20T10:48:05.4215889Z   File ".\third_party\gyp\pylib\gyp\msvs_emulation.py", line 1083, in CalculateCommonVariables
2017-06-20T10:48:05.4215889Z 
2017-06-20T10:48:05.4215889Z     msvs_version = gyp.msvs_emulation.GetVSVersion(generator_flags)
2017-06-20T10:48:05.4215889Z 
2017-06-20T10:48:05.4215889Z   File ".\third_party\gyp\pylib\gyp\msvs_emulation.py", line 934, in GetVSVersion
2017-06-20T10:48:05.4215889Z 
2017-06-20T10:48:05.4215889Z     allow_fallback=False)
2017-06-20T10:48:05.4215889Z 
2017-06-20T10:48:05.4215889Z   File ".\third_party\gyp\pylib\gyp\MSVSVersion.py", line 447, in SelectVisualStudioVersion
2017-06-20T10:48:05.4215889Z 
2017-06-20T10:48:05.4215889Z     raise ValueError('Could not locate Visual Studio installation.')
2017-06-20T10:48:05.4215889Z 
2017-06-20T10:48:05.4215889Z ValueError: Could not locate Visual Studio installation.
```

I would guess that gyp hasn't been updated to work with VS2017 yet, which is the only version of VS installed on the CI machine. Any ideas?

**Comment by atkawa7** [comment]
@ras0219-msft.  Thanks Robert. Yes most if not all chromium projects do not support vs 2017 yet. But they are in the process of transition. My assumption was this [line](https://github.com/atkawa7/vcpkg/blob/426748127371ee7a5aa79415fdb74bd9ba0f5992/ports/angle/portfile.cmake#L20) would stop it from  building

**Comment by ras0219-msft** [comment]
Ok, I used the project files pre-generated in https://github.com/Microsoft/angle [1] as an example to write a CMake replacement buildsystem[2] which supports VS2015 and VS2017.

Overall, it's actually quite simple and has no dependencies on python, gclient, gyp, etc.

I've pushed it to the branch `angle-cmake` -- would you mind trying to build it and confirming it works for you?

[1] https://github.com/Microsoft/angle/blob/ms-master/src/libANGLE.vcxproj
[2] https://github.com/Microsoft/vcpkg/blob/angle-cmake/ports/angle/CMakeLists.txt

**Comment by atkawa7** [comment]
@ras0219-msft  Thanks. Tried it but here is is what I am getting.

`Cannot open include file: 'anglebase/numerics/safe_math.h': No such file or directory`

Full Trace 


[package-x86-windows-rel-out.txt](https://github.com/Microsoft/vcpkg/files/1095505/package-x86-windows-rel-out.txt)

**Comment by ras0219-msft** [comment]
Huh, seems I forgot to push some of my fixes last night. Thanks for trying it out -- I re-added my changes and double-checked that it works locally.

Could you try it once more from branch `angle-cmake`?

**Comment by atkawa7** [comment]
@ras0219-msft Looks okay at my end

**Comment by zabulus** [comment]
UWP support is absent, but doable as I can judge.

**Comment by ras0219-msft** [comment]
Merged in 305d6493. @zabulus, I'd be happy to merge a PR to add UWP support. Let's track it in issue #1365.

**Pull request closed without merging**
