### PR TITLE
[glm] Remove all unnecessary build steps

### PR DESCRIPTION
**Pull request by cwfitzgerald**
GLM is a header only library. For some reason it builds static and shared libraries within its cmakelists but never actually installs them. In addition, the 160 test executables are unconditionally built with no option to disable them. I have replaced their complicated CMakeLists.txt with a barebones one that properly creates the exported target and copies the headers. Installation time for this header only library went from 3 minutes to 3 seconds.

### CODE REVIEW

**Comment by NancyLi1013** [comment]
Hi @cwfitzgerald, thanks for your new PR. I see that the port globjects that depends on glm failed on all triplets. The port forge failed on x64-windows. Please check the changes again.

|x64-windows|master| test |notes
|-----------|------|------|-----
|globjects  |Pass  |Fail  |**Regression**
|forge      |Pass  |Fail  |**Regression**

|x64-windows-static|master| test |notes
|------------------|------|------|-----
|globjects         |Pass  |Fail  |**Regression**

|x64-osx  |master| test |notes
|---------|------|------|-----
|globjects|Pass  |Fail  |**Regression**

|arm64-windows|master| test |notes
|-------------|------|------|-----
|globjects    |Pass  |Fail  |**Regression**

|x86-windows|master| test |notes
|-----------|------|------|-----
|globjects  |Pass  |Fail  |**Regression**

|x64-linux|master| test |notes
|---------|------|------|-----
|globjects|Pass  |Fail  |**Regression**

|x64-uwp  |master| test |notes
|---------|------|------|-----
|globjects|Pass  |Fail  |**Regression**

|arm-uwp  |master| test |notes
|---------|------|------|-----
|globjects|Pass  |Fail  |**Regression**

[failureLogs.zip](https://github.com/microsoft/vcpkg/files/3171007/failureLogs.zip)

**Comment by cwfitzgerald** [comment]
Thanks for the logs, I'll investigate the issue tomorrow.

**Comment by cwfitzgerald** [comment]
globjects failed because of a really stupid header export issue that exported everything inside the glm folder not the folder itself. Not sure if forge is still failing on this build.

**Comment by ras0219-msft** [comment]
I confirmed that this shouldn't break CMake users -- the existing glm port provides:
```
The package glm:x86-windows provides CMake targets:

    find_package(glm CONFIG REQUIRED)
    target_link_libraries(main PRIVATE glm)
```

**Comment by cwfitzgerald** [comment]
👍 I don't know what is causing the CI to fail currently, but the outward effects of the port should be currently identical.

**Comment by ras0219-msft** [comment]
This LGTM, thanks for the PR!

**Comment by cenit** [comment]
> I confirmed that this shouldn't break CMake users -- the existing glm port provides:
> 
> ```
> The package glm:x86-windows provides CMake targets:
> 
>     find_package(glm CONFIG REQUIRED)
>     target_link_libraries(main PRIVATE glm)
> ```

#6461 the new port file does not export interface include directories...

**Comment by cwfitzgerald** [comment]
Line 6 of the CMakeLists exports the include directory into the exported
glm target. From the logs I was given, the headers not being found is
because I was exporting the headers not the containing folder, i.e.
`glm/fwd.hpp` was erroneously exported to `fwd.hpp`.

**Comment by ras0219-msft** [comment]
The issue was that `include(GNUInstallDirs)` was placed _after_ the use of `CMAKE_INSTALL_INCLUDEDIR`, so it wasn't defined yet.

I've opened #6466 to fix this.

**Comment by cwfitzgerald** [comment]
Oh snap! Sorry about that!

**Pull request merged**
