### PR TITLE
Set VcpkgEnabled flag to true in the CMake toolchain file

### PR DESCRIPTION
**Pull request by fwcd**
In order to use installed packages (such as `SFML`) with CMake, the `VcpkgEnabled` flag has to be set to true.

Otherwise the VC++ Build would fail (this is the output of an example project using the `SFML` package):

```
VcpkgTripletSelection:
  Not using Vcpkg because VcpkgEnabled is "false"
[...]
d:\git\marblemarcher\src\overlays.h(18): fatal error C1083: Cannot open include file: 'SFML/Graphics.hpp': No such file or directory [D:\git\MarbleMarch
er\build\src\MarbleMarcherSources.vcxproj]
```

However, after enabling the proposed flag, the build works fine:

```
VcpkgTripletSelection:
  Using triplet "x86-windows" from "D:\git\vcpkg\installed\x86-windows\"
```

### CODE REVIEW

**Comment by Rastaban** [comment]
@ras0219-msft is there a reason why this was false by default?

**Comment by cenit** [comment]
if true, msbuild enables linking to all vcpkg installed libs and includes vcpkg's own header folder in order to solve linked symbols and included sources. In CMake-mode I think it's better to properly use the find_package commands and related symbols to properly link targets and include folders...

**Comment by Neumann-A** [comment]
I am strongly against setting the variable to true in CMakeMode. Just fix your CMakeLists.txt and use find_package with target_link_libraries... one of the ideas of cmake is to enable easy crosscompilation and your are making it only work with Visual Studio by relying on VcpkgAutoLink.....
see also #5485 for problems with VcpkgAutoLink

I would also close #5021due to it being the intended behavior.

**Comment by Rastaban** [comment]
Thank you for all of you input.  I am closing this PR based on the conversation above.

**Pull request closed without merging**
