### PR TITLE
[vcpkg baseline] Adding lunarg-vulkantools and qt5-serialbus as fail in ci.baseline.txt

### PR DESCRIPTION
**Pull request by JonLiu1993**
Fixes  regression: https://dev.azure.com/vcpkg/public/_build/results?buildId=102737&view=results
````
REGRESSION: lunarg-vulkantools:x64-linux failed with BUILD_FAILED
REGRESSION: qt5-serialbus:x64-linux failed with BUILD_FAILED
````
Error:
````
/usr/bin/ld: /mnt/vcpkg-ci/b/krb5/x64-linux-dbg/lib/gssapi/krb5/../../.././../src/krb5-1-8a38cd677f.clean/src/lib/gssapi/krb5/export_name.c:61: undefined reference to `krb5_free_context'
````

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [ ] ~~SHA512s are updated for each updated download.~~
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version.~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [ ] ~~The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.~~
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by JonLiu1993** [comment]
The correct repair method should be to disable gssapi feature in qt5-base.

**Comment by Neumann-A** [comment]
Please fix the regressions instead of masking them .....

**Comment by JonLiu1993** [comment]
> Please fix the regressions instead of masking them .....

Because the local machine cannot reproduce this error, we are currently testing PR and trying to fix it.

**Comment by Neumann-A** [comment]
> Because the local machine cannot reproduce this error

As most of the times if there are uncontrolled dependencies..... look at what ports where added the last month. #38402 added krb5 as such install that which the features CI would install first before everything else.

**Comment by Neumann-A** [comment]
(and make sure you don't use your current binary cache when rebuilding. Otherwise you just pull the working version from there)

**Comment by JonLiu1993** [comment]
Yes, we have reproduced all errors in the test PR https://github.com/microsoft/vcpkg/pull/38670 and are currently analyzing and solving them.

**Comment by data-queue** [comment]
`ci.baseline.txt` should reflect current state, and these failures are being fixed in #38670

**Pull request merged**
