### PR TITLE
[OpenCV3] fix protobuf patch, again

### PR DESCRIPTION
**Pull request by cenit**
Again, sorry for the trouble.
I have still to test it but this was the final patch I was using when I opened the incomplete PR, I hope it works as it did for me.

### CODE REVIEW

**Comment by twMr7** [comment]
Please revert PR #4861 instead, I don't see any reason to skip the working cmake file from the original opencv code.

**Comment by cenit** [comment]
because it is *not* working! In case of multiple configurations generators, the libraries that are generated are linked towards wrong msvcrt version, always toward the release one, also in debug!
Also, tbh, I wrote also the previous 0005 patch which added a phantom target to keep the building happy. The new way of dealing with protobuf is much cleaner and more robust for the future. Do you still experience any problem?

**Comment by twMr7** [comment]
I built opencv:x64-windows port with all features and without "0005-remove-custom-protobuf-find-package.patch", the opencv[dnn] and libprotobuf looks fine to me. Can you point out which part has the linking problem for libprotobuf? or can you provide the log to show the problem?

Please see the complete log files posted in issue #4956

**Comment by cenit** [comment]
Inside the OpenCV-config.cmake the dependencies were not correctly set for debug and release configs. And many more are still in this way, for example also the JPEG lib (which is another dependency for OpenCV) suffers a similar problem (but this one can be solved in the libjpeg-turbo port, and in fact a PR is open for that).
Again, the problem is not when building OpenCV, the annoyance was when *using* it, in a downstream project. What I am really missing is a way to define test cases here on vcpkg, specific for each port and mandatory for each new PR, 
I think it would be great to check ALL PR and verify them. It would help in so many cases!

**Pull request merged**
