### PR TITLE
[Libassuan] Add cflags to tool build command

### PR DESCRIPTION
**Pull request by xandox**
Libassuan add cflags to tool build command

- What does your PR fix? Fixes for PR #15605 

- Which triplets are supported/not supported? same
-  Have you updated the CI baseline? no

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)? yes

### CODE REVIEW

**Comment by PhoebeHui** [comment]
@xandox, could you also submit an issue or PR to Upstream as well?

**Comment by xandox** [comment]
ok

**Comment by xandox** [comment]
https://dev.gnupg.org/T5380

**Comment by xandox** [comment]
@PhoebeHui up?

**Review by PhoebeHui — APPROVED** [review]
LGTM, thanks for reporting the issue to Upsteam.

**Comment by strega-nil-ms** [comment]
@xandox thanks!

**Pull request merged**
