### PR TITLE
[cmake] update to 3.9.1

### PR DESCRIPTION
**Pull request by atkawa7**

### CODE REVIEW

**Comment by alexkaratarakis** [comment]
You also needs to change the version here:
https://github.com/Microsoft/vcpkg/blob/master/toolsrc/src/VcpkgPaths.cpp#L99

**Comment by Mixaill** [comment]
Also in README.md https://github.com/Microsoft/vcpkg/blob/master/README.md

**Comment by atkawa7** [comment]
@alexkaratarakis @Mixaill updated

**Comment by alexkaratarakis** [comment]
So fast! :) Thanks!

**Pull request merged**
