### PR TITLE
[qt5] Modify qtdeploy to include qtquickshapes

### PR DESCRIPTION
**Pull request by tcsavage**
Qt 5.10 introduced the QtQuick.Shapes module. The qtdeploy tool copies the QML plugin (`qmlshapesplugin.dll`) into the build directory, but a second required dll (`Qt5QuickShapes.dll`) is not copied over.

This change adds this missing dll to  the list of QtQuick-associated dlls to deploy.

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Great PR! Can you also please increment the qt5-base CONTROL version number?

**Comment by tcsavage** [comment]
@ras0219-msft, I incremented the version number as you asked but now the validation fails presumably for other reasons. What can I do to keep this moving forward?

**Comment by ras0219-msft** [comment]
This LGTM, thanks for the PR!

**Pull request merged**
