### PR TITLE
[sdl2] allow sdl2 vulkan support

### PR DESCRIPTION
**Pull request by jhs67**
The sdl2 build will automatically enable vulkan support if the requisite library and headers are available, but the vcpkg build will force vulkan support off. This pull request allows vulkan support if available.

I couldn't find anything in the history that suggested a problem with vulkan support in particular. The flag was added with e6c65b93b125cf0be13254cf2f5a9d27cb009707 for reasons that aren't immediately apparent to me.

### CODE REVIEW

**Comment by Rastaban** [comment]
This should probably be enabled as an optional feature in the CONTROL file, that way if someone wants it vcpkg will take care of the vulkan dependency.

**Comment by jhs67** [comment]
I turned it into feature as requested. Seems to work.
Included is a change that fixes the vulkan test on linux. I only have access to linux, so I needed this for testing. This would need to be carefully tested on windows.

**Comment by Rastaban** [comment]
Thank you @jhs67, this looks great!  I have ran it through the other architectures and see no new build failures.

**Comment by Zingam** [comment]
Why is this not enabled by default?

**Pull request merged**
