### PR TITLE
[glib/gtk/atk] Add pkgconfig file

### LINKED ISSUE #12282: gtk missing and broken pkgconfig files
**Describe the bug**
The directory lib/pkgconfig is supposed to contain pkgconfig files for gtk, however some of them are missing.
I was instructed they were required here https://github.com/gtk-rs/gtk/issues/1032

**Environment**
- OS: Windows

**To Reproduce**
```
git clone https://github.com/Microsoft/vcpkg
cd vcpkg
.\bootstrap-vcpkg.bat
vcpkg install gtk:x64-windows
```

**Expected behavior**
The command `pkg-config --libs gtk+-3.0` should succeed
```
PS C:\Users\rukai\Projects\vcpkg\installed\x64-windows\lib\pkgconfig> ls


    Directory: C:\Users\rukai\Projects\vcpkg\installed\x64-windows\lib\pkgconfig


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         5/07/2020   3:52 PM            323 epoxy.pc
-a----         5/07/2020   3:47 PM            425 gio-2.0.pc
-a----         5/07/2020   3:47 PM            330 gio-windows-2.0.pc
-a----         5/07/2020   3:47 PM            387 glib-2.0.pc
-a----         5/07/2020   3:47 PM            278 gmodule-2.0.pc
-a----         5/07/2020   3:47 PM            278 gmodule-export-2.0.pc
-a----         5/07/2020   3:47 PM            277 gmodule-no-export-2.0.pc
-a----         5/07/2020   3:47 PM            270 gobject-2.0.pc
-a----         5/07/2020   3:47 PM            232 gthread-2.0.pc
-a----         5/07/2020   3:46 PM            330 libpcre.pc
-a----         5/07/2020   3:46 PM            335 libpcre16.pc
-a----         5/07/2020   3:46 PM            335 libpcre32.pc
-a----         5/07/2020   3:46 PM            275 libpcrecpp.pc
-a----         5/07/2020   3:46 PM            318 libpcreposix.pc


PS C:\Users\rukai\Projects\vcpkg\installed\x64-windows\lib\pkgconfig> pkg-config --libs gtk+-3.0
Package gtk+-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtk+-3.0' found
PS C:\Users\rukai\Projects\vcpkg\installed\x64-windows\lib\pkgconfig> pkg-config --libs glib-2.0
-LC:/Users/rukai/Projects/vcpkg/installed/x64-windows/lib -lglib-2.0
PS C:\Users\rukai\Projects\vcpkg\installed\x64-windows\lib\pkgconfig>
```

**problem 2**
We also just noticed that the .pc files that do exist are actually broken due to having an empty version.
e.g. glib-2.0.pc:
```
prefix=${pcfiledir}/../..
exec_prefix=${prefix}
libdir=${prefix}/lib
includedir=${prefix}/include

glib_genmarshal=glib-genmarshal
gobject_query=gobject-query
glib_mkenums=glib-mkenums

Name: GLib
Description: C Utility Library
Version: 
Requires.private: 
Libs: -L${libdir} -lglib-2.0 
Libs.private:       
Cflags: -I${includedir}/glib-2.0 -I${libdir}/glib-2.0/include 
```

### PR DESCRIPTION
**Pull request by PhoebeHui**
Fixes #12282 #7641

1. Add package version for glib
2. Add atk and gtk pkgconfig file
3. Gtk: remove '.0' for ARCHIVE_OUTPUT_NAME 
    Before: gdk-3.0.lib
    Now: gdk-3.lib
    Since the library name doesn't have '.0' which used in gtk+-3.0.pc.in file. Not sure why it added before.

### CODE REVIEW

**Comment by sdroege** [comment]
The GTK pkg-config file should depend on the ones from gdk, pango, pangocairo, harfbuzz, cairo, cairo-gobject, gdk-pixbuf (directly or indirectly). Unless those are all there already this would be incomplete.

**Comment by rukai** [comment]
I checked out your branch, then did:
```
./bootstrap-vcpkg.bat
./vcpkg remove gtk:x64-windows
./vcpkg install gtk:x64-windows
```

But it failed with:
```
PS C:\Users\rukai\Projects\vcpkg> ./vcpkg install gtk:x64-windows
Computing installation plan...
The following packages will be built and installed:
    gtk[core]:x64-windows
Starting package 1/1: gtk:x64-windows
Building package gtk[core]:x64-windows...
-- Using cached C:/Users/rukai/Projects/vcpkg/downloads/gtk+-3.22.19.tar.xz
-- Cleaning sources at C:/Users/rukai/Projects/vcpkg/buildtrees/gtk/src/gtk+-3-b723a7b846.clean. Pass --editable to vcpkg to reuse sources.
-- Extracting source C:/Users/rukai/Projects/vcpkg/downloads/gtk+-3.22.19.tar.xz
-- Using source at C:/Users/rukai/Projects/vcpkg/buildtrees/gtk/src/gtk+-3-b723a7b846.clean
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Fixing pkgconfig
-- Fixing pkgconfig - release
-- Checking file: C:/Users/rukai/Projects/vcpkg/packages/gtk_x64-windows/lib/pkgconfig/gail-3.0.pc
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:184 (message):
  Package atk not found! If it is a system package add it to the
  SYSTEM_PACKAGES parameter for the vcpkg_fixup_pkgconfig call! Otherwise,
  corret the *.pc file
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:234 (vcpkg_fixup_pkgconfig_check_libraries)
  ports/gtk/portfile.cmake:40 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:76 (include)


Error: Building package gtk:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: gtk:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.
PS C:\Users\rukai\Projects\vcpkg>
```

**Comment by PhoebeHui** [comment]
@sdroege, thanks for your review, I will try to add pkgconfig file to others depedency ports.

@rukai, the atk port need rebuild in your local machine.

**Comment by PhoebeHui** [comment]
Some pkgconfig file for dependency ports added in https://github.com/microsoft/vcpkg/pull/11776

**Comment by PhoebeHui** [comment]
I will continue this PR after PR https://github.com/microsoft/vcpkg/pull/11550 and https://github.com/microsoft/vcpkg/pull/11776 merged.

**Comment by PhoebeHui** [comment]
List dependency ports which are lacking of the .pc file currently.

- [ ] cairo
- [ ] gdk-pixbuf
- [ ] harfbuzz
- [ ] pango
- [ ] pixman
- [ ] ragel
- [X] zlib
- [X] brotli
- [X] fontconfig
- [X] freetype
- [X] json-c
- [X] libffi
- [X] libpng
- [X] pcre
- [X] atk
- [X] glib

**Comment by PhoebeHui** [comment]
Closing this PR now. I will reopen it once I have time.

**Pull request closed without merging**
