### PR TITLE
add chromium/base script

### LINKED ISSUE #8850: Add chromium base port
Please add port for `Chromium Base`, thank goodness. 
URL at:
```
https://chromium.googlesource.com/chromium/src/base/
```
It doesn't supported for cmake, i try to write a CMakeLists.txt for it, but always failed, SOS!

各位大大请支持一下Chrome Base库，我试过自己写cmake文件，可总是失败，那个gyp文件不好读，总是翻译失败，想把chromium base作为基础库，用cmake链接

### PR DESCRIPTION
**Pull request by iHuahua**
Closes #8850.

### CODE REVIEW

**Comment by JackBoosY** [comment]
@iHuahua Could you sign CLA first?

**Comment by iHuahua** [comment]
@JackBoosY sorry，以前没提交过GitHub的MR，现在登录了，然后还需要哪些？

**Comment by JackBoosY** [comment]
@iHuahua 不需要了，最近我看看怎么添加。建议改名为chromium。

**Comment by iHuahua** [comment]
> @iHuahua 不需要了，最近我看看怎么添加。建议改名为chromium。

OK，Cr是我看内部的命名，你看怎么符合vcpkg的规范就怎么改

**Comment by JackBoosY** [comment]
@iHuahua 
```
ERROR at //build_overrides/build.gni:5:1: Unable to load "F:/12280/vcpkg/buildtrees/chromium/src/a269b59caf-4c7f7fdc4c/build/config/gclient_args.gni".
import("//build/config/gclient_args.gni")
^---------------------------------------
See //build/toolchain/toolchain.gni:9:1: whence it was imported.
import("//build_overrides/build.gni")
^-----------------------------------
See //build/config/coverage/coverage.gni:5:1: whence it was imported.
import("//build/toolchain/toolchain.gni")
^---------------------------------------
See //build/config/sanitizers/sanitizers.gni:7:1: whence it was imported.
import("//build/config/coverage/coverage.gni")
^--------------------------------------------
See //build/config/compiler/compiler.gni:8:1: whence it was imported.
import("//build/config/sanitizers/sanitizers.gni")
^------------------------------------------------
See //BUILD.gn:11:1: whence it was imported.
import("//build/config/compiler/compiler.gni")
^--------------------------------------------
```

**Comment by iHuahua** [comment]
@JackBoosY 亲，有啥联系方式吗？我上传的脚本目录根本本地的有点不一样，我没有仔细核对上传的脚本

**Comment by JackBoosY** [comment]
@iHuahua 知乎找我 余朔钰

**Comment by JackBoosY** [comment]
@vejmartin can you help us to add this port?

Thanks.

**Comment by vejmartin** [comment]
@JackBoosY, yes, I’ll take a look :)

**Comment by vejmartin** [comment]
@iHuahua thank you for the PR! I've looked into the first commit and the [`bootstap.py`](http://bootstap.py) script builds the `base` library on macOS with minimal changes 🎉. Most of the functionality in the script, however, already exists in `vcpkg` (shallow git checkout, patching) as CMake functions, so it would be best to reuse them.

As this port only covers the `base` library, wouldn't it be more accurate to name it `chromium-base` instead?

The current implementation relies on `gclient` for fetching the dependencies, which might be unnecessary overhead (total size of the checkout was about 5.4GB). I was able to build `base` by only checking out `icu` and `boringssl` in their corresponding locations, which might not even be necessary, as `vcpkg` already provides them.

By default, the build relies on a custom version of Clang, which gets pulled down by `gclient` . Building with Xcode's Clang is possible with some changes, and it might be desirable to add support for it.

I used the following `gn` args: `use_custom_libcxx=false clang_base_path=\"/usr\" clang_use_chrome_plugins=false` and added "-Wno-unknown-warning-option" to `//build/config/clang:extra_warnings` (`$clang_base_path/bin/clang` must be valid). Please note that the "//" at the beginning stands for the directory that contains the `.gn` file.

I haven't tried MSVC on Windows, but it looks like it only needs an extra "is_clang=false" `gn` arg.

To make the build work without `gclient`, the following files also need to be created:  
`//build/config/gclient_args.gni`

```cpp
build_with_chromium = true
checkout_android = false
checkout_android_native_support = false
checkout_ios_webkit = false
checkout_nacl = false
checkout_oculus_sdk = false
checkout_openxr = false
```

`//build/util/LASTCHANGE.committime` (looks like the number of second since epoch for the Chromium commit)

```cpp
1575594590
```

The `.gn` file could also be replaced with just the `buildconfig` setting:

```cpp
buildconfig = "//build/config/BUILDCONFIG.gn"
```

Looking at the build commands from `ninja`, it appears that the only files required for `base` to build are in `base` and `boringssl` . So it might be possible to avoid checking out the entire Chromium repo, and only pull the [base](https://chromium.googlesource.com/chromium/src/base/) and [build](https://chromium.googlesource.com/chromium/src/build/) sub-repos, provided there won't be too many issues to patch in the `gn` config.

**Comment by JackBoosY** [comment]
@vejmartin Could you make changes in this PR? You should have the permission to modifiy it.

Thanks.

**Comment by iHuahua** [comment]
@vejmartin 是的，`bootstrap.py` 是我为本地项目写的，我觉得写得不漂亮，所以想大家一起把它加到`vcpkg`里，`bootstrap.py` 没有依赖`vcpkg`，我对`vcpkg`内部流程不熟，所以 @JackBoosY 建议我先传一个空的port，再把我本地的脚本一起带上。这个`port`只包含了base一个`top-level`(chromium called it top-level project)项目，`chromium-base`确实是一个更好的名字，而`base`在`chromium`实际上有两个产物，一个叫`base`，另一个叫`base_i18n`，`base`对`boringssl`不是必须的，我在补丁里`0004-base_build_gn-78.patch`/`0005-base_hash_md5-78.patch`把依赖去掉了，`icu`/`i18n`是`base_i18n`依赖的。5.41G的文件里实际上有很多是不需要的，里面包含了`llvm-clang`/`libcxx`/`libcxxabi`等，但是我没有找到修改的入口，理论上下载`https://chromium.googlesource.com/chromium/src/+refs`里的一个tag加上一些补丁去移除依赖就够了。
sorry, my english is poor, i have to replay by Chinese, the `Chromium Docs` i couldn't understand too much, so, some build args i don't known how to replace. than, Chinese's firewall was ***, i'm sorry...

**Comment by iHuahua** [comment]
by the way, pls keep android native support in android's port if it's possible

**Comment by vejmartin** [comment]
@JackBoosY, I've added support for macOS and Windows [here](https://github.com/vejmartin/vcpkg/commit/1f920859a2a337a7f769771a5aed30db1d80fc12). I don't, however, have write permissions to this PR or the head branch. What would be the best way to add the change list?

@iHuahua, thank you for pointing out `boringssl` could be safely disabled. I don't have access to a Linux instance, which is required for Android to build, so I haven't added support for it. More information can be found [here](https://chromium.googlesource.com/chromium/src/+/master/docs/android_build_instructions.md).

**Comment by JackBoosY** [comment]
@vejmartin Could you please open a PR to add this port?

Thanks.

**Pull request closed without merging**
