### PR TITLE
Upgrade google-cloud-cpp to v0.11.0.

### PR DESCRIPTION
**Pull request by coryan**

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for the PR, @coryan!

From the OSX log:

> FAILED: google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark 
> : && /Library/Developer/CommandLineTools/usr/bin/c++  -fPIC -g -Wl,-search_paths_first -Wl,-headerpad_max_install_names  google/cloud/storage/benchmarks/CMakeFiles/storage_throughput_vs_cpu_benchmark.dir/storage_throughput_vs_cpu_benchmark.cc.o  -o google/cloud/storage/benchmarks/storage_throughput_vs_cpu_benchmark  google/cloud/storage/benchmarks/libstorage_benchmarks.a google/cloud/storage/libstorage_client.a google/cloud/libgoogle_cloud_cpp_common.a /Users/vagrant/azure_agent/_work/3/s/installed/x64-osx/debug/lib/libcurl-d.a -lidn2 -framework CoreFoundation -framework Security /Users/vagrant/azure_agent/_work/3/s/installed/x64-osx/debug/lib/libcrc32c.a /Users/vagrant/azure_agent/_work/3/s/installed/x64-osx/debug/lib/libssl.a /Users/vagrant/azure_agent/_work/3/s/installed/x64-osx/debug/lib/libcrypto.a -ldl /Users/vagrant/azure_agent/_work/3/s/installed/x64-osx/debug/lib/libz.a && :
> ld: library not found for -lidn2

It looks like we're somehow pulling in an unexpected `idn2` library dependency somewhere in the dependency chain and that's causing problems. Based on position, it's probably `curl`'s config files at fault.

**Comment by coryan** [comment]
I was not able to reproduce this locally with macOS 10.14.5 and:

```
$ ./bootstrap-vcpkg.sh 
-- The C compiler identification is AppleClang 10.0.1.10010046
-- The CXX compiler identification is GNU 9.1.0
....
$ ./vcpkg install google-cloud-cpp
```

Do you see an obvious difference between this and the CI build?  Or can you point me to the CI build configuration so I can try to reproduce it here?

**Comment by coryan** [comment]
Seems like rebasing fixed the problem. PTAL.

**Comment by vicroms** [comment]
All tests are passing, thanks for the PR!

**Pull request merged**
