### PR TITLE
[vcpkg] Extend the timeout period for vcpkg test msvc run

### PR DESCRIPTION
**Pull request by Cheney-W**
In the past two weeks, most of our `vcpkg test msvc run` processes were automatically canceled due to timeouts, with only one indeed halted due to blocking during installation. The other runs were terminated because they ran slowly and exceeded the specified time limit. 

Especially when there is a run that is not blocking and only 40 ports are left to be installed, but it gets automatically canceled because it has been running for 2 days.

Therefore, I am submitting this pull request to extend the timeout period for `vcpkg test msvc run`.

https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8960686&view=results
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8990821&view=results

### CODE REVIEW

**Comment by Cheney-W** [comment]
@dan-shaw @BillyONeal 
If you have no objections to this modification, could you please merge it as soon as possible? I hope to initiate a new vcpkg test msvc run after it has been merged.

**Comment by Cheney-W** [comment]
Because the modifications do not affect any ports, I cancel the CI check.

**Comment by dg0yt** [comment]
> Because the modifications do not affect any ports, I cancel the CI check.

Not necessary. The PR CI only tests ports which are changed or which are not in artifact cache.

**Review by FrankXie05 — DISMISSED** [review]

**Comment by Neumann-A** [comment]
So full CI runs every 3 days instead of 2days in the future?

**Comment by FrankXie05** [comment]
Just change the timeout of checking ports from 2 days to 2.5 days.

**Comment by BillyONeal** [comment]
> So full CI runs every 3 days instead of 2days in the future?

This is a service we are providing to the MSVC compiler team where they test the prerelease compiler with our curated registry and ensure they are able to build it. It has no effect on our public CI policy.

**Comment by BillyONeal** [comment]
I merged this after approval from EricBr.

**Pull request merged**
