### PR TITLE
[vcpkg baseline][tiff] Remove REQUIRED vcpkg-cmake-wrapper.in

### PR DESCRIPTION
**Pull request by NancyLi1013**
**Describe the pull request**

- #### What does your PR fix?  
  
Currently `simage `failed with the following errors on x64-osx: 

Even though we have disabled `tiff `via `CMAKE_DISABLE_FIND_PACKAGE_TIFF` on Windows and osx in `simage`, it will fail to build if installing `tiff`. Not sure why it still check `tiff`.
```
CMake Error at /Users/vagrant/Data/installed/x64-osx/share/jpeg/vcpkg-cmake-wrapper.cmake:1 (_find_package):
  _find_package for module JPEG called with REQUIRED, but
  CMAKE_DISABLE_FIND_PACKAGE_JPEG is enabled.  A REQUIRED package cannot be
  disabled.
Call Stack (most recent call first):
  /Users/vagrant/Data/work/1/s/scripts/buildsystems/vcpkg.cmake:718 (include)
  /Users/vagrant/Data/installed/x64-osx/share/tiff/vcpkg-cmake-wrapper.cmake:17 (find_package)
  /Users/vagrant/Data/work/1/s/scripts/buildsystems/vcpkg.cmake:718 (include)
  CMakeLists.txt:222 (find_package)

 

CMake Error at /Users/vagrant/Data/work/1/s/scripts/buildsystems/vcpkg.cmake:764 (_find_package):
  _find_package for module ZLIB called with REQUIRED, but
  CMAKE_DISABLE_FIND_PACKAGE_ZLIB is enabled.  A REQUIRED package cannot be
  disabled.
Call Stack (most recent call first):
  /Users/vagrant/Data/installed/x64-osx/share/tiff/vcpkg-cmake-wrapper.cmake:32 (find_package)
  /Users/vagrant/Data/work/1/s/scripts/buildsystems/vcpkg.cmake:718 (include)
  CMakeLists.txt:222 (find_package)
```

Related PR https://github.com/microsoft/vcpkg/pull/18570

### CODE REVIEW

**Comment by dg0yt** [comment]
**Tiff is the wrong port to patch. You must patch port simage**. Either enable image format dependencies for uwp in `vcpkg.json`, or handle vcpkg target UWP like Windows and OSX in `portfile.cmake`. I don't know the desired behaviour.
Cf. https://github.com/microsoft/vcpkg/pull/15683#discussion_r654807832
CC @ras0219-msft

**Comment by dg0yt** [comment]
Alternatively, there is #18473 for changing tiff's wrapper.

**Comment by NancyLi1013** [comment]
@ras0219 @ras0219-msft 
 
Do you have any ideas about this problem?

**Comment by NancyLi1013** [comment]
Closing this PR in flavor of #18645.

**Pull request closed without merging**
