### PR TITLE
[concurrencpp] Update to 0.1.7

### PR DESCRIPTION
**Pull request by chausner**
Updates concurrencpp to 0.1.7

* [x]  Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)
* [x]  SHA512s are updated for each updated download
* [x]  The "supports" clause reflects platforms that may be fixed by this new version
* [x]  Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
* [x]  Any patches that are no longer applied are deleted from the port's directory.
* [x]  The version database is fixed by rerunning ./vcpkg x-add-version --all and committing the result.
* [x]  Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by BillyONeal** [comment]
```
concurrencpp:arm-neon-android=fail
concurrencpp:arm64-android=fail
concurrencpp:x64-android=fail
concurrencpp:x64-linux=fail
concurrencpp:x64-osx=fail
```

Should any of these fails be removed with the new version?

**Comment by chausner** [comment]
No, I don't think so. All the Android triplets and OS X use Clang, right? Clang is not supported by the library.

**Comment by chausner** [comment]
The only compiler/platform dependency change introduced with this version is added support for gcc. But gcc version 13 is required and the gcc version in CI older. So no, I don't think any changes are needed.

**Comment by BillyONeal** [comment]
Thanks for the update!

**Pull request merged**
