### PR TITLE
[gRPC] Update to 1.27.1

### PR DESCRIPTION
**Pull request by ymshenyu**
update gRPC version

### CODE REVIEW

**Comment by Qv2ray-dev** [comment]
This could fix: #9940

**Comment by Qv2ray-dev** [comment]
Any updates?

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
LGTM, thanks for this PR!

**Comment by DuckSoft** [comment]
Any updates on this?

**Comment by JackBoosY** [comment]
@ras0219-msft Ready to merge.

**Comment by ras0219-msft** [comment]
LGTM, thanks everyone for pitching in on this!

**Pull request merged**
