### PR TITLE
OpenVDB: Add `/bigobj` as compiler flag only for MSVC

### LINKED ISSUE #4940: Error: Building package openvdb:x64-linux failed with: BUILD_FAILED
## Machine Setup

OS: Ubuntu 18.04

## Steps to Reproduce

I ran `./vcpkg install openvdb` and got the following error message.

```
Starting package 82/82: openvdb:x64-linux
Building package openvdb[core]:x64-linux... 
-- Downloading https://github.com/dreamworksanimation/openvdb/archive/v5.0.0.tar.gz...
-- Extracting source /home/aang/Code/vcpkg/downloads/dreamworksanimation-openvdb-v5.0.0.tar.gz
-- Using source at /home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828
-- Applying patch /home/aang/Code/vcpkg/ports/openvdb/UseGLEWOnWindowsForViewer.patch
-- Applying patch /home/aang/Code/vcpkg/ports/openvdb/AddLinkageAndToolsChoice.patch
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: /home/aang/Code/vcpkg/downloads/tools/cmake-3.12.4-linux/cmake-3.12.4-Linux-x86_64/bin/cmake;--build;.;--config;Debug;--target;install;--;-v;-j1
    Working Directory: /home/aang/Code/vcpkg/buildtrees/openvdb/x64-linux-dbg
    See logs for more information:
    /home/aang/Code/vcpkg/buildtrees/openvdb/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
ports/openvdb/portfile.cmake:97 (vcpkg_install_cmake)
scripts/ports.cmake:71 (include)


Error: Building package openvdb:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
Package: openvdb:x64-linux
Vcpkg version: 2018.11.23-unknownhash

Additionally, attach any relevant sections from the log files above.
```

The log that was produced: `vcpkg/buildtrees/openvdb/install-x64-linux-dbg-out.log`:

```
[1/26] /usr/bin/c++   -I/home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828 -I/home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828/openvdb/. -Idwa -isystem /home/aang/Code/vcpkg/installed/x64-linux/include -isystem /home/aang/Code/vcpkg/installed/x64-linux/include/OpenEXR -fPIC -g   -pthread -fPIC -DOPENVDB_PRIVATE -DOPENVDB_USE_BLOSC  /bigobj -MD -MT openvdb/CMakeFiles/openvdb_static.dir/MetaMap.cc.o -MF openvdb/CMakeFiles/openvdb_static.dir/MetaMap.cc.o.d -o openvdb/CMakeFiles/openvdb_static.dir/MetaMap.cc.o -c /home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828/openvdb/MetaMap.cc
FAILED: openvdb/CMakeFiles/openvdb_static.dir/MetaMap.cc.o 
/usr/bin/c++   -I/home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828 -I/home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828/openvdb/. -Idwa -isystem /home/aang/Code/vcpkg/installed/x64-linux/include -isystem /home/aang/Code/vcpkg/installed/x64-linux/include/OpenEXR -fPIC -g   -pthread -fPIC -DOPENVDB_PRIVATE -DOPENVDB_USE_BLOSC  /bigobj -MD -MT openvdb/CMakeFiles/openvdb_static.dir/MetaMap.cc.o -MF openvdb/CMakeFiles/openvdb_static.dir/MetaMap.cc.o.d -o openvdb/CMakeFiles/openvdb_static.dir/MetaMap.cc.o -c /home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828/openvdb/MetaMap.cc
c++: error: /bigobj: No such file or directory
[2/26] /usr/bin/c++   -I/home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828 -I/home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828/openvdb/. -Idwa -isystem /home/aang/Code/vcpkg/installed/x64-linux/include -isystem /home/aang/Code/vcpkg/installed/x64-linux/include/OpenEXR -fPIC -g   -pthread -fPIC -DOPENVDB_PRIVATE -DOPENVDB_USE_BLOSC  /bigobj -MD -MT openvdb/CMakeFiles/openvdb_static.dir/Grid.cc.o -MF openvdb/CMakeFiles/openvdb_static.dir/Grid.cc.o.d -o openvdb/CMakeFiles/openvdb_static.dir/Grid.cc.o -c /home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828/openvdb/Grid.cc
FAILED: openvdb/CMakeFiles/openvdb_static.dir/Grid.cc.o 
/usr/bin/c++   -I/home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828 -I/home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828/openvdb/. -Idwa -isystem /home/aang/Code/vcpkg/installed/x64-linux/include -isystem /home/aang/Code/vcpkg/installed/x64-linux/include/OpenEXR -fPIC -g   -pthread -fPIC -DOPENVDB_PRIVATE -DOPENVDB_USE_BLOSC  /bigobj -MD -MT openvdb/CMakeFiles/openvdb_static.dir/Grid.cc.o -MF openvdb/CMakeFiles/openvdb_static.dir/Grid.cc.o.d -o openvdb/CMakeFiles/openvdb_static.dir/Grid.cc.o -c /home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828/openvdb/Grid.cc
c++: error: /bigobj: No such file or directory
[3/26] /usr/bin/c++   -I/home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828 -I/home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828/openvdb/. -Idwa -isystem /home/aang/Code/vcpkg/installed/x64-linux/include -isystem /home/aang/Code/vcpkg/installed/x64-linux/include/OpenEXR -fPIC -g   -pthread -fPIC -DOPENVDB_PRIVATE -DOPENVDB_USE_BLOSC  /bigobj -MD -MT openvdb/CMakeFiles/openvdb_static.dir/Metadata.cc.o -MF openvdb/CMakeFiles/openvdb_static.dir/Metadata.cc.o.d -o openvdb/CMakeFiles/openvdb_static.dir/Metadata.cc.o -c /home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828/openvdb/Metadata.cc
FAILED: openvdb/CMakeFiles/openvdb_static.dir/Metadata.cc.o 
/usr/bin/c++   -I/home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828 -I/home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828/openvdb/. -Idwa -isystem /home/aang/Code/vcpkg/installed/x64-linux/include -isystem /home/aang/Code/vcpkg/installed/x64-linux/include/OpenEXR -fPIC -g   -pthread -fPIC -DOPENVDB_PRIVATE -DOPENVDB_USE_BLOSC  /bigobj -MD -MT openvdb/CMakeFiles/openvdb_static.dir/Metadata.cc.o -MF openvdb/CMakeFiles/openvdb_static.dir/Metadata.cc.o.d -o openvdb/CMakeFiles/openvdb_static.dir/Metadata.cc.o -c /home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828/openvdb/Metadata.cc
c++: error: /bigobj: No such file or directory
[4/26] /usr/bin/c++   -I/home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828 -I/home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828/openvdb/. -Idwa -isystem /home/aang/Code/vcpkg/installed/x64-linux/include -isystem /home/aang/Code/vcpkg/installed/x64-linux/include/OpenEXR -fPIC -g   -pthread -fPIC -DOPENVDB_PRIVATE -DOPENVDB_USE_BLOSC  /bigobj -MD -MT openvdb/CMakeFiles/openvdb_static.dir/Platform.cc.o -MF openvdb/CMakeFiles/openvdb_static.dir/Platform.cc.o.d -o openvdb/CMakeFiles/openvdb_static.dir/Platform.cc.o -c /home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828/openvdb/Platform.cc
FAILED: openvdb/CMakeFiles/openvdb_static.dir/Platform.cc.o 
/usr/bin/c++   -I/home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828 -I/home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828/openvdb/. -Idwa -isystem /home/aang/Code/vcpkg/installed/x64-linux/include -isystem /home/aang/Code/vcpkg/installed/x64-linux/include/OpenEXR -fPIC -g   -pthread -fPIC -DOPENVDB_PRIVATE -DOPENVDB_USE_BLOSC  /bigobj -MD -MT openvdb/CMakeFiles/openvdb_static.dir/Platform.cc.o -MF openvdb/CMakeFiles/openvdb_static.dir/Platform.cc.o.d -o openvdb/CMakeFiles/openvdb_static.dir/Platform.cc.o -c /home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828/openvdb/Platform.cc
c++: error: /bigobj: No such file or directory
[5/26] /usr/bin/c++   -I/home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828 -I/home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828/openvdb/. -Idwa -isystem /home/aang/Code/vcpkg/installed/x64-linux/include -isystem /home/aang/Code/vcpkg/installed/x64-linux/include/OpenEXR -fPIC -g   -pthread -fPIC -DOPENVDB_PRIVATE -DOPENVDB_USE_BLOSC  /bigobj -MD -MT openvdb/CMakeFiles/openvdb_static.dir/io/Archive.cc.o -MF openvdb/CMakeFiles/openvdb_static.dir/io/Archive.cc.o.d -o openvdb/CMakeFiles/openvdb_static.dir/io/Archive.cc.o -c /home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828/openvdb/io/Archive.cc
FAILED: openvdb/CMakeFiles/openvdb_static.dir/io/Archive.cc.o 
/usr/bin/c++   -I/home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828 -I/home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828/openvdb/. -Idwa -isystem /home/aang/Code/vcpkg/installed/x64-linux/include -isystem /home/aang/Code/vcpkg/installed/x64-linux/include/OpenEXR -fPIC -g   -pthread -fPIC -DOPENVDB_PRIVATE -DOPENVDB_USE_BLOSC  /bigobj -MD -MT openvdb/CMakeFiles/openvdb_static.dir/io/Archive.cc.o -MF openvdb/CMakeFiles/openvdb_static.dir/io/Archive.cc.o.d -o openvdb/CMakeFiles/openvdb_static.dir/io/Archive.cc.o -c /home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828/openvdb/io/Archive.cc
c++: error: /bigobj: No such file or directory
[6/26] /usr/bin/c++   -I/home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828 -I/home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828/openvdb/. -Idwa -isystem /home/aang/Code/vcpkg/installed/x64-linux/include -isystem /home/aang/Code/vcpkg/installed/x64-linux/include/OpenEXR -fPIC -g   -pthread -fPIC -DOPENVDB_PRIVATE -DOPENVDB_USE_BLOSC  /bigobj -MD -MT openvdb/CMakeFiles/openvdb_static.dir/io/Compression.cc.o -MF openvdb/CMakeFiles/openvdb_static.dir/io/Compression.cc.o.d -o openvdb/CMakeFiles/openvdb_static.dir/io/Compression.cc.o -c /home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828/openvdb/io/Compression.cc
FAILED: openvdb/CMakeFiles/openvdb_static.dir/io/Compression.cc.o 
/usr/bin/c++   -I/home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828 -I/home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828/openvdb/. -Idwa -isystem /home/aang/Code/vcpkg/installed/x64-linux/include -isystem /home/aang/Code/vcpkg/installed/x64-linux/include/OpenEXR -fPIC -g   -pthread -fPIC -DOPENVDB_PRIVATE -DOPENVDB_USE_BLOSC  /bigobj -MD -MT openvdb/CMakeFiles/openvdb_static.dir/io/Compression.cc.o -MF openvdb/CMakeFiles/openvdb_static.dir/io/Compression.cc.o.d -o openvdb/CMakeFiles/openvdb_static.dir/io/Compression.cc.o -c /home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828/openvdb/io/Compression.cc
c++: error: /bigobj: No such file or directory
[7/26] /usr/bin/c++   -I/home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828 -I/home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828/openvdb/. -Idwa -isystem /home/aang/Code/vcpkg/installed/x64-linux/include -isystem /home/aang/Code/vcpkg/installed/x64-linux/include/OpenEXR -fPIC -g   -pthread -fPIC -DOPENVDB_PRIVATE -DOPENVDB_USE_BLOSC  /bigobj -MD -MT openvdb/CMakeFiles/openvdb_static.dir/io/File.cc.o -MF openvdb/CMakeFiles/openvdb_static.dir/io/File.cc.o.d -o openvdb/CMakeFiles/openvdb_static.dir/io/File.cc.o -c /home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828/openvdb/io/File.cc
FAILED: openvdb/CMakeFiles/openvdb_static.dir/io/File.cc.o 
/usr/bin/c++   -I/home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828 -I/home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828/openvdb/. -Idwa -isystem /home/aang/Code/vcpkg/installed/x64-linux/include -isystem /home/aang/Code/vcpkg/installed/x64-linux/include/OpenEXR -fPIC -g   -pthread -fPIC -DOPENVDB_PRIVATE -DOPENVDB_USE_BLOSC  /bigobj -MD -MT openvdb/CMakeFiles/openvdb_static.dir/io/File.cc.o -MF openvdb/CMakeFiles/openvdb_static.dir/io/File.cc.o.d -o openvdb/CMakeFiles/openvdb_static.dir/io/File.cc.o -c /home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828/openvdb/io/File.cc
c++: error: /bigobj: No such file or directory
[8/26] /usr/bin/c++   -I/home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828 -I/home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828/openvdb/. -Idwa -isystem /home/aang/Code/vcpkg/installed/x64-linux/include -isystem /home/aang/Code/vcpkg/installed/x64-linux/include/OpenEXR -fPIC -g   -pthread -fPIC -DOPENVDB_PRIVATE -DOPENVDB_USE_BLOSC  /bigobj -MD -MT openvdb/CMakeFiles/openvdb_static.dir/io/GridDescriptor.cc.o -MF openvdb/CMakeFiles/openvdb_static.dir/io/GridDescriptor.cc.o.d -o openvdb/CMakeFiles/openvdb_static.dir/io/GridDescriptor.cc.o -c /home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828/openvdb/io/GridDescriptor.cc
FAILED: openvdb/CMakeFiles/openvdb_static.dir/io/GridDescriptor.cc.o 
/usr/bin/c++   -I/home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828 -I/home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828/openvdb/. -Idwa -isystem /home/aang/Code/vcpkg/installed/x64-linux/include -isystem /home/aang/Code/vcpkg/installed/x64-linux/include/OpenEXR -fPIC -g   -pthread -fPIC -DOPENVDB_PRIVATE -DOPENVDB_USE_BLOSC  /bigobj -MD -MT openvdb/CMakeFiles/openvdb_static.dir/io/GridDescriptor.cc.o -MF openvdb/CMakeFiles/openvdb_static.dir/io/GridDescriptor.cc.o.d -o openvdb/CMakeFiles/openvdb_static.dir/io/GridDescriptor.cc.o -c /home/aang/Code/vcpkg/buildtrees/openvdb/src/v5.0.0-7f1d479828/openvdb/io/GridDescriptor.cc
c++: error: /bigobj: No such file or directory
ninja: build stopped: subcommand failed.
```

I would love to help out fixing this bug if anyone could guide me through the process 😄 

Thank you for this amazing project!

EDIT:

Seems like `/bigobj` is added in [AddLinkageAndToolsChoice.patch](https://github.com/Microsoft/vcpkg/blob/master/ports/openvdb/AddLinkageAndToolsChoice.patch#L154). Could we just delete that part?

### PR DESCRIPTION
**Pull request by aaronang**
This patch should fix #4940.

### CODE REVIEW

**Comment by sanxiyn** [comment]
Does it continue to build on MSVC? If it doesn't, you should make the removal conditional on the compiler; see #3442 for an example.

**Comment by aaronang** [comment]
I see. I wasn't aware of /bigobj being used on MSVC. I currently don't have a Windows machine but will use the fix you proposed 🙂

**Comment by aaronang** [comment]
@sanxiyn Thank you for the feedback! I incorporated your feedback.

**Comment by ras0219-msft** [comment]
Thanks for the PR and happy holidays!

**Pull request merged**
