### PR TITLE
[portable-snippets] Add new port

### PR DESCRIPTION
**Pull request by myd7349**
https://github.com/nemequ/portable-snippets
BTW, any advice about the package name?

### CODE REVIEW

**Comment by ehsan-mohammadi** [comment]
@myd7349 Is this library doesn't support `arm-uwp`?

**Comment by myd7349** [comment]
Hi! @ehsan-mohammadi The failure on `arm-uwp` is caused by:
https://github.com/nemequ/portable-snippets/blob/master/cpu/cpu.c#L65-L66

Most of the shiny code snippets included in `portable-snippets` are header only.

**Comment by myd7349** [comment]
I am not able to fix the `arm-uwp` right now. Except that, I am also a little worry about the package name.

**Comment by grdowns** [comment]
Hey @myd7349, I think this port is fine as is. We can take an arm-uwp fix in the future. As for the port name, Google gives me the correct repo as the first hit so we should be fine. Whether the name is descriptive enough is up to the owner in this case :smile:. Thanks for the new port!

**Pull request merged**
