### PR TITLE
[vcpkg] Fix warning (as error) when building vcpgk/toolsrc with clang++ 10 or g++ 9.3 (see #15148)

### LINKED ISSUE #15148: [vcpkg] Warning (as error) when building vcpgk/toolsrc with clang++ 10 or g++ 9.3
**Describe the bug**
There are 3 warnings that prevent the compilation since `-Werror` is enabled. I'll paste the log below.

**Environment**
- OS: Ubuntu 20.04
- Compiler: I tried both `clang version 10.0.0-4ubuntu1` and `g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0`

**To Reproduce**
1. `cd toolsrc`
2. `mkdir debug`
3. `cd debug`
4. `cmake -DCMAKE_BUILD_TYPE=Debug -G Ninja ..`
5. `cmake --build .`

**Expected behavior**
I expected the compilation to succeed.

**Failure logs** 

First warning:

```shell
[13/114] Building CXX object CMakeFiles/vcpkg-test.dir/src/vcpkg-test/dependencies.cpp.o
FAILED: CMakeFiles/vcpkg-test.dir/src/vcpkg-test/dependencies.cpp.o 
/usr/bin/g++  -DVCPKG_USE_STD_FILESYSTEM=1 -I../include -g   -Wall -Wextra -Wpedantic -Wno-unknown-pragmas -Wno-missing-field-initializers -Wno-redundant-move -Wmissing-declarations -Werror -std=c++17 -MD -MT CMakeFiles/vcpkg-test.dir/src/vcpkg-test/dependencies.cpp.o -MF CMakeFiles/vcpkg-test.dir/src/vcpkg-test/dependencies.cpp.o.d -o CMakeFiles/vcpkg-test.dir/src/vcpkg-test/dependencies.cpp.o -c ../src/vcpkg-test/dependencies.cpp
../src/vcpkg-test/dependencies.cpp:606:96: error: integer constant is so large that it is unsigned [-Werror]
  606 |     check_relaxed_version(version_long, {1, 20, 300, 4000, 50000, 6000000, 70000000, 80000000, 18446744073709551610});
      |                                                                                                ^~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

Second warning:

```shell
[80/102] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/portfileprovider.cpp.o
FAILED: CMakeFiles/vcpkglib.dir/src/vcpkg/portfileprovider.cpp.o 
/usr/bin/clang++  -DVCPKG_USE_STD_FILESYSTEM=1 -I../include -g   -Wall -Wextra -Wpedantic -Wno-unknown-pragmas -Wno-missing-field-initializers -Wno-redundant-move -Wmissing-prototypes -Werror -include /home/klalumiere/Projects/vcpkg-klalumiere/toolsrc/include/pch.h -pthread -std=c++17 -MD -MT CMakeFiles/vcpkglib.dir/src/vcpkg/portfileprovider.cpp.o -MF CMakeFiles/vcpkglib.dir/src/vcpkg/portfileprovider.cpp.o.d -o CMakeFiles/vcpkglib.dir/src/vcpkg/portfileprovider.cpp.o -c ../src/vcpkg/portfileprovider.cpp
In file included from <built-in>:1:
In file included from /home/klalumiere/Projects/vcpkg-klalumiere/toolsrc/include/pch.h:5:
In file included from ../include/vcpkg/base/files.h:14:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/filesystem:37:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/fs_path.h:37:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/locale:43:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/locale_conv.h:41:
/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/unique_ptr.h:81:2: error: delete called on non-final 'vcpkg::PortFileProvider::PathsPortFileProvider' that has virtual functions but non-virtual destructor [-Werror,-Wdelete-non-abstract-non-virtual-dtor]
        delete __ptr;
        ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/unique_ptr.h:292:4: note: in instantiation of member function 'std::default_delete<vcpkg::PortFileProvider::PathsPortFileProvider>::operator()' requested here
          get_deleter()(std::move(__ptr));
          ^
../src/vcpkg/portfileprovider.cpp:299:13: note: in instantiation of member function 'std::unique_ptr<vcpkg::PortFileProvider::PathsPortFileProvider, std::default_delete<vcpkg::PortFileProvider::PathsPortFileProvider> >::~unique_ptr' requested here
            BaselineProviderImpl(const VcpkgPaths& paths) : paths(paths) { }
            ^
1 error generated.
```

Third warning :

```shell
[3/9] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/versiondeserializers.cpp.o
FAILED: CMakeFiles/vcpkglib.dir/src/vcpkg/versiondeserializers.cpp.o 
/usr/bin/clang++  -DVCPKG_USE_STD_FILESYSTEM=1 -I../include -g   -Wall -Wextra -Wpedantic -Wno-unknown-pragmas -Wno-missing-field-initializers -Wno-redundant-move -Wmissing-prototypes -Werror -include /home/klalumiere/Projects/vcpkg-klalumiere/toolsrc/include/pch.h -pthread -std=c++17 -MD -MT CMakeFiles/vcpkglib.dir/src/vcpkg/versiondeserializers.cpp.o -MF CMakeFiles/vcpkglib.dir/src/vcpkg/versiondeserializers.cpp.o.d -o CMakeFiles/vcpkglib.dir/src/vcpkg/versiondeserializers.cpp.o -c ../src/vcpkg/versiondeserializers.cpp
../src/vcpkg/versiondeserializers.cpp:15:29: error: unused variable 'GIT_TREE' [-Werror,-Wunused-const-variable]
    constexpr StringLiteral GIT_TREE = "git-tree";
                            ^
1 error generated.
```

**Additional context**
I fixed the issues and I'll make a PR in a few seconds.

### PR DESCRIPTION
**Pull request by klalumiere**
**Describe the pull request**

- What does your PR fix? Fixes #15148

It now compiles (and then the tests succeed) with both clang++ 10 and g++ 9.3.

- Which triplets are supported/not supported? Have you updated the CI baseline? Does not apply.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)? Yes

### CODE REVIEW

**Comment by BillyONeal** [comment]
Can you fix what the thing is warning about rather than silencing the warning?

**Comment by klalumiere** [comment]
> Can you fix what the thing is warning about rather than silencing the warning?

Yes I can. The reason I didn't do it to begin with is that the warning [1] is a little bit more subtle than the other two. In particular, there's (at least) two ways to fix the issue highlighted by it:

1. Declare `PathsPortFileProvider` as `final`.
2. Add a virtual destructor to `PortFileProvider`.

In principle, the way we choose to fix it should ultimately depends on the intent of the author of the code. In practice, it probably won't matter a lot. I thought the warning was pedantic (which is what we asked the compiler), so I choose the third option to silence it locally.

I'll add a virtual destructor for now since this fix is "local" (if I choose the alternative, i.e. to make `PathsPortFileProvider` final, I should probably also make `MapPortFileProvider` final). I'm happy to discuss it or to go the other way if you think it's better :slightly_smiling_face: .


[1]
```
[80/102] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/portfileprovider.cpp.o
FAILED: CMakeFiles/vcpkglib.dir/src/vcpkg/portfileprovider.cpp.o 
/usr/bin/clang++  -DVCPKG_USE_STD_FILESYSTEM=1 -I../include -g   -Wall -Wextra -Wpedantic -Wno-unknown-pragmas -Wno-missing-field-initializers -Wno-redundant-move -Wmissing-prototypes -Werror -include /home/klalumiere/Projects/vcpkg-klalumiere/toolsrc/include/pch.h -pthread -std=c++17 -MD -MT CMakeFiles/vcpkglib.dir/src/vcpkg/portfileprovider.cpp.o -MF CMakeFiles/vcpkglib.dir/src/vcpkg/portfileprovider.cpp.o.d -o CMakeFiles/vcpkglib.dir/src/vcpkg/portfileprovider.cpp.o -c ../src/vcpkg/portfileprovider.cpp
In file included from <built-in>:1:
In file included from /home/klalumiere/Projects/vcpkg-klalumiere/toolsrc/include/pch.h:5:
In file included from ../include/vcpkg/base/files.h:14:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/filesystem:37:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/fs_path.h:37:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/locale:43:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/locale_conv.h:41:
/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/unique_ptr.h:81:2: error: delete called on non-final 'vcpkg::PortFileProvider::PathsPortFileProvider' that has virtual functions but non-virtual destructor [-Werror,-Wdelete-non-abstract-non-virtual-dtor]
        delete __ptr;
        ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/unique_ptr.h:292:4: note: in instantiation of member function 'std::default_delete<vcpkg::PortFileProvider::PathsPortFileProvider>::operator()' requested here
          get_deleter()(std::move(__ptr));
          ^
../src/vcpkg/portfileprovider.cpp:299:13: note: in instantiation of member function 'std::unique_ptr<vcpkg::PortFileProvider::PathsPortFileProvider, std::default_delete<vcpkg::PortFileProvider::PathsPortFileProvider> >::~unique_ptr' requested here
            BaselineProviderImpl(const VcpkgPaths& paths) : paths(paths) { }
            ^
1 error generated.
```

**Comment by klalumiere** [comment]
I recompiled and re-ran the test with both clang++ 10 and g++ 9.3. Everything is green :heavy_check_mark:.

**Comment by BillyONeal** [comment]
Thanks for squashing those warnings!

**Pull request merged**
