### PR TITLE
[freetype-gl] Fix POST_BUILD_CHECKS_FAILED failure on Unix

### PR DESCRIPTION
**Pull request by NancyLi1013**
Since on Linux and Mac platforms, the suffix of generated library is different from that on Windows platform. 
 I  handle `*.lib `and `*.a` separately by adding `VCPKG_TARGET_IS_WINDOWS` to judge platform.

Related issue #8981.

Note: No features need to test.

### CODE REVIEW

**Comment by cenit** [comment]
What about simply using VCPKG_TARGET_STATIC_LIBRARY_SUFFIX, which is a symbol that resolves correctly to the proper suffix on each platform?

**Comment by JackBoosY** [comment]
@cenit Yes, we should use `VCPKG_TARGET_STATIC_LIBRARY_SUFFIX`.

**Comment by NancyLi1013** [comment]
@cenit and @JackBoosY  thanks for your suggestion.

**Comment by ras0219-msft** [comment]
This appears to fix x64-osx, however `freetype-gl` is not built for x64-linux because `freetype` is not currently being built.

**Comment by JackBoosY** [comment]
@ras0219-msft At least we avoided post check failures on non-Windows triplets.

**Review by JackBoosY — APPROVED** [review]

**Pull request merged**
