### PR TITLE
[gtk]Fix missing resource files issue.

### PR DESCRIPTION
**Pull request by JackBoosY**
Complete the manifest generation step by viewing gtk's msvc project file and add the manifest to the build using CMakelists.txt.

Related: #6554.

### CODE REVIEW

**Comment by JackBoosY** [comment]
@NNemec Can you help me to test it?

Thanks.

**Comment by NNemec** [comment]
@JackBoosY thanks for the work, but sorry, I will not be able to help on this. The project where I stumbled over this has been on ice for a few months and I have no idea when I will pick it up again.

**Comment by JackBoosY** [comment]
@NNemec Can you give me some test code first?

Thanks.

**Comment by JackBoosY** [comment]
Close this PR because we need to change the compiler mode to msbuild.

**Pull request closed without merging**
