### PR TITLE
[libmysql] update to 8.0.3

### LINKED ISSUE #26006: [libmysql] update to 8.0.3
Library name: libmysql

New version number: 8.0.3

Other information that may be useful (release notes, etc...):
Fixes compilation with c++20

### PR DESCRIPTION
**Pull request by FrankXie05**
Fix #26006

Update [libmysql] version to 8.0.3 

No feature need to test.

### CODE REVIEW

**Comment by dg0yt** [comment]
Please coordinate with #26121.

**Comment by JonLiu1993** [comment]
@FrankXie05,  Can you please resolve the conflicts against master?

**Comment by JonLiu1993** [comment]
Pinging @FrankXie05   for response. Is work still being done for this PR?

**Comment by JonLiu1993** [comment]
Closing this PR since it seems that no progress is being made. Please ping us to reopen if work is still being done.

**Pull request closed without merging**
