### PR TITLE
[re2] update to 2023-07-01

### PR DESCRIPTION
**Pull request by kobykahane**
Update the re2 port to new upstream release 2023-07-01.
Add upstream's newly introduced dependency on abseil.

- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [X] SHA512s are updated for each updated download
- [X] The "supports" clause reflects platforms that may be fixed by this new version
- [X] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [X] Any patches that are no longer applied are deleted from the port's directory.
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by Cheney-W** [comment]
`D:\buildtrees\libphonenumber\src\v8.13.13-101fa5850b.clean\cpp\src\phonenumbers\regexp_adapter_re2.cc(44): error C2039: 'ToString': is not a member of 'absl::lts_20230125::string_view'`

Error logs: https://dev.azure.com/vcpkg/public/_build/results?buildId=91869&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by Cheney-W** [comment]
About the `portfile.cmake`, please just modify the value of `SHA512` instead of the whole contents of this file.

**Comment by BillyONeal** [comment]
> About the `portfile.cmake`, please just modify the value of `SHA512` instead of the whole contents of this file.

It's fixing the file to be LF line endings rather than CRLF. Seems OK to me.

**Comment by BillyONeal** [comment]
I submitted https://github.com/google/libphonenumber/pull/3134 to libphonenumber to fix the compatibility issue.

**Comment by BillyONeal** [comment]
@kobykahane Are you OK with the changes I added? Thanks!

**Review by Cheney-W — APPROVED** [review]

**Comment by kobykahane** [comment]
> @kobykahane Are you OK with the changes I added? Thanks!

LGTM. Thanks.

**Pull request merged**
