### PR TITLE
[mysql-connector-cpp] add JDBC feature

### LINKED ISSUE #28220: How do I can build JDBC?
Hello, i added Mysql Connector but it hasn't jdbc binaries. How do i can include it to build?
I didn't find out how i can provide command option to CMake where use "vcpkg install".
Here's says make this to build with jdbc: https://dev.mysql.com/doc/connector-cpp/8.0/en/connector-cpp-source-configuration-options.html#option_cmake_with_jdbc

### PR DESCRIPTION
**Pull request by FrankXie05**
**Describe the pull request**

- #### What does your PR fix?
  Fixes https://github.com/microsoft/vcpkg/issues/28220
  Note: add feature `JDBC` with option `WITH_JDBC`

### CODE REVIEW

**Review by MonicaLiu0311 — DISMISSED** [review]

**Review by BillyONeal — CHANGES_REQUESTED** [review]
Attempting to build this feature did not succeed:

```
Wrote configuration header: D:/vcpkg/buildtrees/mysql-connector-cpp/x64-windows-dbg/cdk/include/mysql/cdk/config.h
CMake Error at CMakeLists.txt:338 (add_subdirectory):
  The source directory

    D:/vcpkg/buildtrees/mysql-connector-cpp/src/8.0.30-3e5f000053.clean/jdbc

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:344 (target_include_directories):
  Cannot specify include directories for target "connector-jdbc" which is not
  built by this project.


Preparing to merge SHARED library: connector (xapi;devapi)
Connector library name: mysqlcppconn8-2-vs14
Building version 8.0.30
Generating INFO_SRC
Generating INFO_BIN
Install location: D:/vcpkg/packages/mysql-connector-cpp_x64-windows/debug
Connector libraries will be installed at: lib

Project configuration options:

: BUILD_STATIC: 0
Build static version of connector library

: WITH_SSL: D:/vcpkg/installed/x64-windows
Either 'system' to use system-wide OpenSSL library, or custom OpenSSL location. (default : system)

: WITH_JDBC: ON
Whether to build a variant of connector library which implements legacy JDBC API

-- Configuring incomplete, errors occurred!
See also "D:/vcpkg/buildtrees/mysql-connector-cpp/x64-windows-dbg/CMakeFiles/CMakeOutput.log".
See also "D:/vcpkg/buildtrees/mysql-connector-cpp/x64-windows-dbg/CMakeFiles/CMakeError.log".
ninja: build stopped: subcommand failed.
```

It looks like upstream puts that in a git submodule. Is that a third party dependency being vendored or morally part of the same thing that deserves another `vcpkg_from_Xxx` call?

**Comment by MonicaLiu0311** [comment]
Convert this PR to draft since there is no progress. Please ping us if this PR is ready for review again.

**Comment by FrankXie05** [comment]
Upstream has been integrated `jdbc` since version 8.0.32. 
https://github.com/mysql/mysql-connector-cpp/commit/bca53b733468820ee7ebd34ee8088c0a0f22b34b

**Comment by BillyONeal** [comment]
Are you waiting for me to review this again? (I'm not trying because it is still draft rather than being marked ready for review)

**Comment by FrankXie05** [comment]
@BillyONeal The interval is too long, I need to retest this feature.

**Comment by FrankXie05** [comment]
Fixed by PR https://github.com/microsoft/vcpkg/pull/30869

**Pull request closed without merging**
