### PR TITLE
Revert baseline changes from #20449

### PR DESCRIPTION
**Pull request by dg0yt**
- #### What does your PR fix?  
  Fixes CI file conflict between lodepng and lodepng-c, introduced by #20449, discovered in 
  https://dev.azure.com/vcpkg/public/_build/results?buildId=64084&view=logs&j=c2a18d2e-37ac-57b0-b2a5-926ff10fbe32&t=b0e2c199-eacf-5d50-0d96-a04f9ea0e46a.

  #20449 didn't modify neither lodepng[-c] nor pdcurses. The lodepng ports show their conflict in the portfiles.
  I don't know the reason for the pdcurses fail, but it does say `ONLY_DYNAMIC_CRT`

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  --, yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  --

CC @BillyONeal

### CODE REVIEW

**Comment by dg0yt** [comment]
Alternative: merge lodepng-c into lodepng, #21846.

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
I think I can accept this.

**Comment by dg0yt** [comment]
In vcpkg.ci pipeline:
https://dev.azure.com/vcpkg/public/_build/results?buildId=64134&view=logs&j=c2a18d2e-37ac-57b0-b2a5-926ff10fbe32&t=b0e2c199-eacf-5d50-0d96-a04f9ea0e46a

**Comment by BillyONeal** [comment]
Thanks for the notice about the file conflicts!

**Pull request merged**
