### PR TITLE
[TinyNPY] Add new port

### PR DESCRIPTION
**Pull request by cdcseacave**

### CODE REVIEW

**Comment by cdcseacave** [comment]
I do not understand the failure reason on linux and osx, pls help!

**Comment by cdcseacave** [comment]
@gnu-lorien can u pls help merging this?

**Comment by gnu-lorien** [comment]
It looks like the problem is that somewhere you said "TinyNPY" when you meant "tinynpy" or vice versa. When I build, the error message is this:

 '$DEV/cdcseacave/packages/tinynpy_x64-linux/debug/lib/cmake/tinynpy'
  does not exist.
Call Stack (most recent call first):
  ports/tinynpy/portfile.cmake:23 (vcpkg_fixup_cmake_targets)
  scripts/ports.cmake:74 (include)

When I ls cdcseacave/packages/tinynpy_x64-linux/debug/lib/cmake/ there's a TinyNPY directory.

So something sets the case to be the pretty version rather than the package name version which will only work case insensitive file systems.

**Comment by cdcseacave** [comment]
That was it, thx for your help.
Good to merge now!

**Pull request merged**
