### PR TITLE
[prometheus-cpp] Update to version 0.7.0

### PR DESCRIPTION
**Pull request by gjasny**

### CODE REVIEW

**Comment by grdowns** [comment]
Hey @gjasny, thanks for the port update. Is there a particular reason for enabling testing? As a general rule we do not build tests as it brings on additional dependencies and build times for a feature that users most likely will not be using. If there isn't, I can go ahead and re-disable the tests the tests for you. Let me know!

**Comment by gjasny** [comment]
Hi @grdowns,

There's no particular reason to enable the tests. By enabling but not running them you gain a check for missing symbols.

Feel free to disable them, again.

Thanks,
Gregor

**Comment by grdowns** [comment]
@dan-shaw, could you please add a `test` feature for this port? This way users who are interested in the additional level of symbol checking or want to run the tests themselves will be able to do so easily. Thanks!

**Comment by dan-shaw** [comment]
Thanks for the PR!

**Pull request merged**
