### PR TITLE
[gz-sensors7] New port

### PR DESCRIPTION
**Pull request by talregev**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [x] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by talregev** [comment]
This port is depends on gz-rendering7 that depends on ogre-next. That way it skip in the CI.
I tested it on windows and linux.

**Review by JonLiu1993 — APPROVED** [review]

**Comment by JonLiu1993** [comment]
Tested usage successfully by `gz-sensors7:x64-windows`:
````
Total install time: 2.9 h
gz-sensors7 provides CMake targets:

  # this is heuristically generated, and may not be correct
  find_package(gz-sensors7 CONFIG REQUIRED)
  target_link_libraries(main PRIVATE gz-sensors7::core gz-sensors7::requested gz-sensors7::gz-sensors7)
````

**Comment by talregev** [comment]
wow, why is it 2.9h?
On my pc on windows it takes several minutes.
I will post time soon.

**Comment by talregev** [comment]
On windows 11:
Elapsed time to handle gz-sensors7:x64-windows: 1.9 min
Total install time: 1.9 min
gz-sensors7 provides CMake targets:

  # this is heuristically generated, and may not be correct

**Pull request merged**
