### PR TITLE
[vcpkg] Reset to known-good build scripts

### LINKED ISSUE #10847: ./bootstrap-vcpkg.sh fails to link vcpkg and create executable binary with latest update
**Describe the bug**
./bootstrap-vcpkg.sh fails to link vcpkg and create executable binary with latest update

**Environment**
- OS: [Linux OpenSuse Leap 15.1 - latest updates]
- Compiler: GNU 8.2.1 - latest updates

**To Reproduce**
1. git clone --verbose https://github.com/Microsoft/vcpkg.git ./vcpkg
2. cd ./vcpkg
3. ./bootstrap-vcpkg.sh
4. **[72/72] Linking CXX executable vcpkg**
**FAILED: vcpkg**
 ... see attached _**bootstrap-vcpkg.log**_ for complete error listing produced when running ./bootstrap-vcpkg.sh

**Expected behavior**
bootstrap-vcpkg.sh should be compile, link and create vcpkg

**Failure logs** 
[bootstrap-vcpkg.log](https://github.com/microsoft/vcpkg/files/4483143/bootstrap-vcpkg.log)

**Additional context**
- Initially since vcpkg sources were updated maybe the changes were incompatible with the an existing vcpkg instance, so I then created a new instance and it also produces the same failed results.
- Also tried run ./bootstrap-vcpkg.sh logged in as _root_ with same results.
- I did a _**git reset --hard 1e19af09e53e5f306ed89c2033817a21e5ee0bcf**_ on the linux instance to back out the latest two changes and ./bootstrap-vcpkg.sh compiled, linked and created the vcpkg binary properly.
- On Windows 10 x64 the latest vcpkg with all updates  .\bootstrap-vcpkg.bat compiles, links and creates vcpkg.exe as expected.

### PR DESCRIPTION
**Pull request by strega-nil**
Should fix #10847.

### CODE REVIEW

**Comment by strega-nil** [comment]
@timautry @Farwaykorse could you build these and see if these actually do fix your issue?

**Comment by timautry** [comment]
I replaced the 
- toolsrc/CMakeLists.txt, 
- scripts/bootstrap.sh with the ones here
- and renamed toolsrc/cmake/utilities.cmake to utilities.cmake.txt 
- reran the ./bootstrap-vcpkg.sh with the following errors about VCPKG_DISABLE_METRICS in the attached:
[bootstrap-vcpkg.log](https://github.com/microsoft/vcpkg/files/4489175/bootstrap-vcpkg.log)
[CMakeError.log](https://github.com/microsoft/vcpkg/files/4489176/CMakeError.log)
[CMakeOutput.log](https://github.com/microsoft/vcpkg/files/4489178/CMakeOutput.log)

- I can help as I am able off and on as I may need to rest due to my disability or do other household chores, etc.

**Comment by strega-nil** [comment]
@timautry this should actually work -.- I'm sorry

**Comment by timautry** [comment]
The latest change works... Yeah :)
[bootstrap-vcpkg.log](https://github.com/microsoft/vcpkg/files/4489290/bootstrap-vcpkg.log)

**Comment by Farwaykorse** [comment]
Cloned in a new directory; checked-out `fix-bootstrap`; ran `./bootstrap-vcpkg.sh`

54ec9b26cb74aa656b07742e7f28a01be580fb42 builds and links.

**Comment by strega-nil** [comment]
@Farwaykorse, @timautry can you also try the following?

```sh
git clone https://github.com/strega-nil/vcpkg
cd vcpkg
git checkout new-buildsystem
./boostrap-vcpkg.sh
```
?

**Comment by Farwaykorse** [comment]
I noticed the current HEAD of vcpkg CMake output [Line 12](https://gist.github.com/Farwaykorse/30c05f1125314f0e24ef5d2234efd9b5#file-gistfile1-txt-L12)
```
-- Detecting how to use the C++ filesystem library - <experimental/filesystem>
```
But when I run the functions in an other CMake project it shows:
````
-- Detecting how to use the C++ filesystem library - <filesystem>
````
So I tried changing the CMake version in the `vcpkgTools.xml`, to CMake v3.17.1.
This worked!

Changing it back to v3.14.0, again resulted in it trying to use `<experimental/filesystem>` and a failed build.

**Comment by Farwaykorse** [comment]
> @Farwaykorse, @timautry can you also try the following?
> 
> ```shell
> git clone https://github.com/strega-nil/vcpkg
> cd vcpkg
> git checkout new-buildsystem
> ./boostrap-vcpkg.sh
> ```
> 
> ?

This one builds. ffac3774dbdd16e8421924d45d7009d5ce572ec9

**Comment by timautry** [comment]
I created new instance vcpkg.devl from above instructions and it compiled and linked fine.
[bootstrap-vcpkg-new-buildsystem.log](https://github.com/microsoft/vcpkg/files/4489383/bootstrap-vcpkg-new-buildsystem.log)

**Comment by Farwaykorse** [comment]
The detection to use `<filesystem>` works properly for CMake 3.15.0 and newer.
Since there is already a PR to update CMake to 3.17.1 #10767 this should be fixed soon.

@timautry can you try if it works for your issue too?
````
git clone https://github.com/Farwaykorse/vcpkg
cd vcpkg
git checkout update_cmake_linux
./boostrap-vcpkg.sh
````

**Comment by strega-nil** [comment]
@Farwaykorse I think the issue with openSUSE is unrelated -- it looks like the issue was attempting to link with a G++ that was different from the compiler.

**Comment by timautry** [comment]
@Farwaykorse - I still get a failed to link using the version you have provided using 
[bootstrap-vcpkg.cmake.test.log](https://github.com/microsoft/vcpkg/files/4489511/bootstrap-vcpkg.cmake.test.log)
cmake 3.17.1
attached

**Comment by strega-nil** [comment]
Superseded by #10867

**Pull request closed without merging**
