### PR TITLE
[ilmbase][openexr] Update IlmBase and OpenEXR to v2.3.0

### PR DESCRIPTION
**Pull request by UnaNancyOwen**
This pull request will update these port.

* Update IlmBase port  to IlmBase v2.3.0
* Update OpenEXR port to OpenEXR v2.3.0

TODO: check all ports that dependent on these libraries.

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for the PR!

What's the purpose for adding all those .nuspec and .bat files in the patches?

**Comment by UnaNancyOwen** [comment]
> What's the purpose for adding all those .nuspec and .bat files in the patches?

These patches (001-005) is difference between the current master and v2.3.0. 
I reproduced current master by patch, because OpenEXR could not configure and build in v2.3.0.
It will include changes that are directly irrelevant to making possible to configure and build.
Should I extract minimal necessary changes?

openexr_

**Comment by Voskrese** [comment]
```
-- Performing post-build validation
DLLs should not be present in a static build, but the following DLLs were found:

    E:/tools/vcpkg/packages/ilmbase_x64-windows-static/bin/Half-2_3.dll
    E:/tools/vcpkg/packages/ilmbase_x64-windows-static/bin/Iex-2_3.dll
    E:/tools/vcpkg/packages/ilmbase_x64-windows-static/bin/IexMath-2_3.dll
    E:/tools/vcpkg/packages/ilmbase_x64-windows-static/bin/IlmThread-2_3.dll
    E:/tools/vcpkg/packages/ilmbase_x64-windows-static/bin/Imath-2_3.dll
    E:/tools/vcpkg/packages/ilmbase_x64-windows-static/debug/bin/Half-2_3_d.dll
    E:/tools/vcpkg/packages/ilmbase_x64-windows-static/debug/bin/Iex-2_3_d.dll
    E:/tools/vcpkg/packages/ilmbase_x64-windows-static/debug/bin/IexMath-2_3_d.dll
    E:/tools/vcpkg/packages/ilmbase_x64-windows-static/debug/bin/IlmThread-2_3_d.dll
    E:/tools/vcpkg/packages/ilmbase_x64-windows-static/debug/bin/Imath-2_3_d.dll

There should be no bin\ directory in a static build, but E:\tools\vcpkg\packages\ilmbase_x64-windows-static\bin is present.
There should be no debug\bin\ directory in a static build, but E:\tools\vcpkg\packages\ilmbase_x64-windows-static\debug\bin is present.
If the creation of bin\ and/or debug\bin\ cannot be disabled, use this in the portfile to remove them

    if(VCPKG_LIBRARY_LINKAGE STREQUAL static)
        file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/bin ${CURRENT_PACKAGES_DIR}/debug/bin)
    endif()

Found 2 error(s). Please correct the portfile:
    E:\tools\vcpkg\ports\ilmbase\portfile.cmake
```

add

```
    if(VCPKG_LIBRARY_LINKAGE STREQUAL static)
        file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/bin ${CURRENT_PACKAGES_DIR}/debug/bin)
    endif()
```

**Comment by UnaNancyOwen** [comment]
@Voskrese Please try again! Thanks,

**Comment by Voskrese** [comment]
@UnaNancyOwen 
I have corrected, there was another mistake

`e:\tools\vcpkg\buildtrees\openexr\src\v2.3.0-a634df73e5\ilmbase\imath\ImathNamespace.h(78): fatal error C1083: Cannot open include file: 'IlmBaseConfig.h': No such file or directory`

**Comment by UnaNancyOwen** [comment]
@Voskrese Sorry, It was a little mistake. I fixed. Please confirm again.

**Comment by Rastaban** [comment]
Closing pull request because it looks like both ilmbase and openexr have been updated to the newer versions in other PRs.

**Pull request closed without merging**
