### PR TITLE
[gpgme] add Qt feature, update to 1.18, add Windows support

### PR DESCRIPTION
**Pull request by wrobelda**
**Describe the pull request**
 Depends on:
 - [x] #26467 
 - [ ] #26433 
 - [ ] #26340 (not merging to this branch as it triggers world rebuild)
 - [ ]  #26454

- #### What does your PR fix?
  Fixes #...

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  <all / linux, windows, ...>, <Yes/No>

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  `Your answer`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  <Yes / I am still working on this PR>

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by wrobelda** [comment]
Windows progress currently stuck at:

```
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(525): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(616): warning C4098: 'release_onetime_context': 'void' function returning a value
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(702): error C2059: syntax error: '{'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(702): error C2065: '_r': undeclared identifier
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(702): error C2059: syntax error: ')'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(704): error C2059: syntax error: 'for'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(704): error C2143: syntax error: missing '{' before '++'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(704): error C2059: syntax error: '++'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(704): error C2059: syntax error: ')'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(713): error C2065: 'i': undeclared identifier
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(713): error C2057: expected constant expression
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(713): error C2466: cannot allocate an array of constant size 0
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(713): error C2065: 'tmp': undeclared identifier
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(713): error C2100: illegal indirection
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(713): error C2059: syntax error: '{'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(713): error C2059: syntax error: ')'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(713): error C2059: syntax error: ':'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(715): error C2143: syntax error: missing ')' before '('
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(715): error C2059: syntax error: ')'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(715): error C2143: syntax error: missing ')' before ';'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(715): error C2091: function returns function
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(715): error C2373: 'gpgrt_free': redefinition; different type modifiers
C:\vcpkg\installed\x64-windows\include\gpg-error.h(1160): note: see declaration of 'gpgrt_free'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(716): error C2059: syntax error: 'return'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(717): error C2059: syntax error: '}'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(2708): warning C4013: 'add_secret_fprs' undefined; assuming extern returning int
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3187): error C2059: syntax error: '{'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3187): error C2065: '_r': undeclared identifier
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3187): error C2059: syntax error: ')'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3188): error C2059: syntax error: 'else'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3191): error C2059: syntax error: 'string'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3191): error C2371: 'xjson_AddStringToObject': redefinition; different basic types
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(194): note: see declaration of 'xjson_AddStringToObject'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3192): error C2059: syntax error: 'string'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3192): error C2371: 'xjson_AddStringToObject': redefinition; different basic types
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(194): note: see declaration of 'xjson_AddStringToObject'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3194): error C2143: syntax error: missing ')' before '('
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3194): error C2059: syntax error: ')'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3194): error C2143: syntax error: missing ')' before ';'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3194): error C2091: function returns function
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3194): error C2373: 'gpgrt_free': redefinition; different type modifiers
C:\vcpkg\installed\x64-windows\include\gpg-error.h(1160): note: see declaration of 'gpgrt_free'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3195): error C2059: syntax error: 'return'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3196): error C2059: syntax error: '}'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3379): error C2059: syntax error: '{'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3379): error C2065: '_r': undeclared identifier
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3379): error C2059: syntax error: ')'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3380): error C2059: syntax error: 'if'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3388): error C2065: 'buflen': undeclared identifier
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3388): error C2057: expected constant expression
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3388): error C2466: cannot allocate an array of constant size 0
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3388): error C2075: 'buf': initialization requires a brace-enclosed initializer list
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3391): error C2059: syntax error: 'return'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3392): error C2059: syntax error: '}'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3462): error C2059: syntax error: '{'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3462): error C2065: '_r': undeclared identifier
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3462): error C2143: syntax error: missing ';' before ')'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3463): warning C4133: 'function': incompatible types - from 'int [1]' to 'const char *'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3475): error C2059: syntax error: 'else'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3477): error C2059: syntax error: 'else'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3491): error C2059: syntax error: 'else'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3494): error C2059: syntax error: 'return'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3495): error C2059: syntax error: '}'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3558): warning C4013: 'get_line' undefined; assuming extern returning int
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3558): warning C4047: '=': 'char *' differs in levels of indirection from 'int'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3566): error C2059: syntax error: '{'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3566): error C2065: '_r': undeclared identifier
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3566): error C2143: syntax error: missing ';' before ')'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3567): error C2181: illegal else without matching if
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3569): error C2059: syntax error: '{'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3569): error C2065: '_r': undeclared identifier
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3569): error C2143: syntax error: missing ';' before ')'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3571): error C2065: 'tmp': undeclared identifier
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3571): warning C4047: '=': 'char *' differs in levels of indirection from 'int'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3573): error C2059: syntax error: '}'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3598): warning C4013: 'get_help_msg' undefined; assuming extern returning int
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3624): error C2059: syntax error: 'while'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3626): error C2143: syntax error: missing ')' before '('
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3626): error C2059: syntax error: ')'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3626): error C2143: syntax error: missing ')' before ';'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3626): error C2091: function returns function
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3626): error C2373: 'gpgrt_free': redefinition; different type modifiers
C:\vcpkg\installed\x64-windows\include\gpg-error.h(1160): note: see declaration of 'gpgrt_free'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3627): error C2143: syntax error: missing ')' before '('
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3627): error C2059: syntax error: ')'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3627): error C2143: syntax error: missing ')' before ';'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3627): error C2091: function returns function
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3627): error C2373: 'gpgrt_free': redefinition; different type modifiers
C:\vcpkg\installed\x64-windows\include\gpg-error.h(1160): note: see declaration of 'gpgrt_free'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3628): error C2143: syntax error: missing ')' before '('
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3628): error C2059: syntax error: ')'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3628): error C2143: syntax error: missing ')' before ';'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3628): error C2091: function returns function
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3628): error C2373: 'gpgrt_free': redefinition; different type modifiers
C:\vcpkg\installed\x64-windows\include\gpg-error.h(1160): note: see declaration of 'gpgrt_free'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3629): error C2059: syntax error: '}'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3750): warning C4267: '=': conversion from 'size_t' to 'uint32_t', possible loss of data
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3902): error C2059: syntax error: '{'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3902): error C2065: '_r': undeclared identifier
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3902): error C2143: syntax error: missing ';' before ')'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3903): error C2065: 'file': undeclared identifier
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3903): warning C4047: 'function': 'const char *' differs in levels of indirection from 'int'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3903): warning C4024: 'gpgrt_log_set_sink': different types for formal and actual parameter 1
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3904): error C2065: 'file': undeclared identifier
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3904): warning C4022: 'gpgrt_free': pointer mismatch for actual parameter 1
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3881): warning C4996: 'getenv': This function or variable may be unsafe. Consider using _dupenv_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3899): warning C4996: 'getenv': This function or variable may be unsafe. Consider using _dupenv_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3907): error C2059: syntax error: 'if'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3913): error C2059: syntax error: 'switch'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3935): error C2059: syntax error: 'if'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3938): error C2059: syntax error: 'return'
C:\vcpkg\buildtrees\gpgme\src\gpgme-1-77ff3d7240.clean\src\gpgme-json.c(3939): error C2059: syntax error: '}'
```

**Comment by Adela0814** [comment]
Pinging @wrobelda  for response. Is work still being done for this PR?

**Comment by Adela0814** [comment]
Closing this PR since it seems that no progress is being made. Please ping us to reopen if work is still being done.

**Comment by wrobelda** [comment]
@Adela0814 please do reopen this, I was temporarily drawn to other work, but will return to it this week.

**Comment by Adela0814** [comment]
Pinging @wrobelda for response. Is work still being done for this PR?

**Comment by wrobelda** [comment]
@Adela0814 yes, I very much intend to finish this sometime soon.

**Comment by Adela0814** [comment]
Closing this PR since it seems that no progress is being made. Please ping us to reopen if work is still being done.

**Pull request closed without merging**
