### PR TITLE
[fakeit] update to 2.3.0

### PR DESCRIPTION
**Pull request by Stannieman**
**Describe the pull request**

- #### What does your PR fix?
Update FakeIt to 2.3.0

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  all, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by Cheney-W** [comment]
Please sign the CLA first.

**Comment by Cheney-W** [comment]
Please run `.\vcpkg x-add-version fakeit` when you submit a new commit.

**Comment by Stannieman** [comment]
CLA signed and vcpkg x-add-version done. Did not realize that this command needs to be ran after commit.

**Comment by BillyONeal** [comment]
Thanks!

**Pull request merged**
