### PR TITLE
[fastgltf] New port

### PR DESCRIPTION
**Pull request by spnda**
**Describe the pull request**

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  all, Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

### CODE REVIEW

**Comment by Cheney-W** [comment]
By default, vcpkg does not build `test` and `example`, so could you use macros to control the enabling of these two parts, and then pass the macro value of off in `vcpkg_cmake_configure()`. Thank you!

**Comment by Cheney-W** [comment]
Considering that building tests and examples for each port will impose a great burden on the ci system, we do not build them by default, but they can be used as features of ports. We could add the `test` and the `example` as a feature of `fastgltf`.

About disable parallel configure, you could add `DISABLE_PARALLEL_CONFIGURE` option into the vcpkg_cmake_configure(), such as:
```
vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    DISABLE_PARALLEL_CONFIGURE
    OPTIONS -DFASTGLTF_DOWNLOAD_SIMDJSON=OFF
)
```

**Comment by Cheney-W** [comment]
Please add the `test` and the `example` as a feature of `fastgltf`, and use macros to control whether they are enabled or not. 
Thank you!

**Comment by spnda** [comment]
No, I don't see any gain in adding the tests and examples as port features, especially when the tests require a 3GB download of sample files. I don't know of any other port that does that and I seriously don't see why one would want these tests or examples. If anybody wants to, and I doubt anyone will want to if they're not already working on contributing to it, they can clone the repo and compile them. Perhaps you could add this afterwards *if anyone* opens an issue and asks for it. As no doubt you are aware vcpkg is used for installing library dependencies, not for running tests.

**Comment by dg0yt** [comment]
I think the PR is okay as is. 
IIUC examples and tests have the `EXCLUDE_FROM_ALL` property, so no patching for feature control is required. But I didn't verify in the build log.

**Comment by spnda** [comment]
Yes, the dependencies required for tests and examples are only downloaded through a Python script. As that script is never invoked the tests and examples would result in build failures because of missing headers and libraries.

**Comment by Cheney-W** [comment]
Test and example were not built.
```
[1/4] C:\PROGRA~1\MICROS~2\2022\ENTERP~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x64\cl.exe   /TP -DSIMDJSON_THREADS_ENABLED=1 -IF:\fastgltf\buildtrees\fastgltf\src\d1f0969b11-2105bfd15b\src -external:IF:\fastgltf\installed\x64-windows-static\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MTd /Z7 /Ob0 /Od /RTC1  /EHsc -std:c++17 /showIncludes /Fosrc\CMakeFiles\fastgltf.dir\base64_decode.cpp.obj /Fdsrc\CMakeFiles\fastgltf.dir\fastgltf.pdb /FS -c F:\fastgltf\buildtrees\fastgltf\src\d1f0969b11-2105bfd15b\src\base64_decode.cpp
[2/4] C:\PROGRA~1\MICROS~2\2022\ENTERP~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x64\cl.exe   /TP -DSIMDJSON_THREADS_ENABLED=1 -IF:\fastgltf\buildtrees\fastgltf\src\d1f0969b11-2105bfd15b\src -external:IF:\fastgltf\installed\x64-windows-static\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MTd /Z7 /Ob0 /Od /RTC1  /EHsc -std:c++17 /showIncludes /Fosrc\CMakeFiles\fastgltf.dir\fastgltf.cpp.obj /Fdsrc\CMakeFiles\fastgltf.dir\fastgltf.pdb /FS -c F:\fastgltf\buildtrees\fastgltf\src\d1f0969b11-2105bfd15b\src\fastgltf.cpp
[3/4] cmd.exe /C "cd . && C:\PROGRA~1\MICROS~2\2022\ENTERP~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x64\lib.exe  /machine:x64 /nologo /out:src\fastgltf.lib src\CMakeFiles\fastgltf.dir\base64_decode.cpp.obj src\CMakeFiles\fastgltf.dir\fastgltf.cpp.obj  && cd ."
[3/4] cmd.exe /C "cd /D F:\fastgltf\buildtrees\fastgltf\x64-windows-static-dbg && F:\fastgltf\downloads\tools\cmake-3.24.0-windows\cmake-3.24.0-windows-i386\bin\cmake.exe -P cmake_install.cmake"
-- Install configuration: "Debug"
-- Installing: F:/fastgltf/packages/fastgltf_x64-windows-static/debug/include/base64_decode.hpp
-- Installing: F:/fastgltf/packages/fastgltf_x64-windows-static/debug/include/fastgltf_parser.hpp
-- Installing: F:/fastgltf/packages/fastgltf_x64-windows-static/debug/include/fastgltf_types.hpp
-- Installing: F:/fastgltf/packages/fastgltf_x64-windows-static/debug/include/fastgltf_util.hpp
-- Installing: F:/fastgltf/packages/fastgltf_x64-windows-static/debug/lib/fastgltf.lib
-- Installing: F:/fastgltf/packages/fastgltf_x64-windows-static/debug/lib/cmake/fastgltf/fastgltfConfig.cmake
-- Installing: F:/fastgltf/packages/fastgltf_x64-windows-static/debug/lib/cmake/fastgltf/fastgltfConfig-debug.cmake
```

**Pull request merged**
