### PR TITLE
[libgit2] fixup regex backend dependency

### PR DESCRIPTION
**Pull request by kindrowboat**
**Describe the pull request**

- #### What does your PR fix?

libgit2 allows for at least three regex regex backends: builtin, pcre,
and pcre2. While builtin uses a statically linked pcre, if "pcre" is
specified as the regex backend, and pcre is never linked to or used in
the production code, vcpkg won't copy the required pcre DLL into the
build output directory (at least in msbuild). Therefore, unless a
dynamically linked pcre or pcre2 is preferred, the vcpkg libgit2 port
ought to use the builtin regex backend.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  

all, no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  

Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?

Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by Neumann-A** [comment]
1) https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-use-vendored-dependencies

2)
```
E:\vcpkg_folders\master\installed\x64-windows\bin>dumpbin git2.dll /DEPENDENTS
Microsoft (R) COFF/PE Dumper Version 14.29.30037.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file git2.dll

File Type: DLL

  Image has the following dependencies:

    WS2_32.dll
    WINHTTP.dll
    RPCRT4.dll
    CRYPT32.dll
    ole32.dll
    pcre.dll
    zlib1.dll
    KERNEL32.dll
    ADVAPI32.dll
    VCRUNTIME140.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-filesystem-l1-1-0.dll
    api-ms-win-crt-environment-l1-1-0.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-time-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-convert-l1-1-0.dll
    api-ms-win-crt-utility-l1-1-0.dll

  Summary

        5000 .data
        C000 .pdata
       2C000 .rdata
        1000 .reloc
        1000 .rsrc
       E6000 .text
```
should be copied. Looks more like a bug in the deployment code.

as such this PR looks invalid to me.

**Comment by motevets** [comment]
@Neumann-A, thank you so much for the fast response! I'm fairly new vcpkg and Windows C/C++ development in general, so I realize I have much to learn. Some questions/follow-up:

To your first point (don't vendor dependencies): I took this to mean as the port maintainer shouldn't vendor dependencies. If the upstream project has exposed a ["builtin" option for the regex engine](https://github.com/libgit2/libgit2/blob/508361401fbb5d87118045eaeae3356a729131aa/CMakeLists.txt#L56), meant to be a opaque to the end user (i.e. maybe it vendors pcre today, maybe they roll their own tomorrow, but if I opt for "builtin" I'm saying  "I don't care, I just want it to work,") shouldn't we expose that as an option for the vcpkg port as well?

To your second point, I would like to help report and/or fix this bug in the deployment code. Could you point me in the right direction (e.g. repo, documentation, code files, or contact) to get started? As it is right now, I can't use vcpkg to include libgit2 in my project (x86-windows using vs2019/msbuild), and it [looks like I'm not the only one](https://stackoverflow.com/questions/67487957/libgit2-dependency-pcre-not-present-in-build).

Thanks again for your help. 😃

**Comment by Neumann-A** [comment]
> To your first point (don't vendor dependencies): I took this to mean as the port maintainer shouldn't vendor dependencies. If the upstream project has exposed a "builtin" option for the regex engine, meant to be a opaque to the end user (i.e. maybe it vendors pcre today, maybe they roll their own tomorrow, but if I opt for "builtin" I'm saying "I don't care, I just want it to work,") shouldn't we expose that as an option for the vcpkg port as well?

No, since it vendors pcre. 

> To your second point, I would like to help report and/or fix this bug in the deployment code. Could you point me in the right direction (e.g. repo, documentation, code files, or contact) to get started? As it is right now, I can't use vcpkg to include libgit2 in my project (x86-windows using vs2019/msbuild), and it looks like I'm not the only one.

https://github.com/microsoft/vcpkg/blob/master/scripts/buildsystems/msbuild/applocal.ps1. The problem is it is not recursively searching for dependencies as far as I can tell. Also the MSBuild integration is limited and buggy the same applies to the deployment script. It works in some cases but not in all. Better setup the environment that those DLLs get found if you run it in the Debugger/VS IDE.

**Review by JackBoosY — CHANGES_REQUESTED** [review]
Please bump the port version. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).
Also please run command `vcpkg x-add-version --all` then commit the changes.

**Comment by JackBoosY** [comment]
Ping @motevets  for response.

**Comment by JackBoosY** [comment]
This PR has been inactive for a long time, please reopen it if there is any progress.

**Pull request closed without merging**
