### PR TITLE
[lionkor-commandline] Update library to 2.0.0

### PR DESCRIPTION
**Pull request by Pospelove**

### CODE REVIEW

**Comment by JonLiu1993** [comment]
@Pospelove ,Thanks for your pr, Looks the CI tested failed on x64-uwp and arm_uwp, 
This is error log, please take a look:
[install-arm-uwp-dbg-out.log](https://github.com/microsoft/vcpkg/files/8361087/install-arm-uwp-dbg-out.log)

**Comment by Pospelove** [comment]
@JonLiu1993 Thanks! I've marked UWP as unsupported.

**Comment by JonLiu1993** [comment]
> @JonLiu1993 Thanks! I've marked UWP as unsupported.

@Pospelove ,Could you please clarify why UWP as unsupported?

**Comment by Pospelove** [comment]
@JonLiu1993 this lib in 2.0.0 uses GetKeyState function which is AFAIK unavailable under uwp.

**Comment by lionkor** [comment]
That's accurate, yes. We may reintroduce UWP as a working target, but for now we rely on GetKeyState heavily.

**Review by JonLiu1993 — APPROVED** [review]

**Comment by strega-nil-ms** [comment]
Thanks!

**Pull request merged**
