### PR TITLE
[azure-storage-cpp]Upgrade to 7.1.0

### PR DESCRIPTION
**Pull request by Jinming-Hu**
**Describe the pull request**

- What does your PR fix? Fixes issue #

Version upgrade
Remove the patch since it's already backported to release 7.1.0

- Which triplets are supported/not supported? Have you updated the CI baseline?

x64-linux, x64-windows, x64-windows-static, x86-windows, x86-windows-static

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

Yes

### CODE REVIEW

**Review by PhoebeHui — APPROVED** [review]
Thanks for the PR!

**Comment by ras0219-msft** [comment]
LGTM, thanks for the PR!

**Pull request merged**
