### PR TITLE
Add google-cloud-cpp package

### LINKED ISSUE #3093: Add package for Google Cloud C++ Libraries
If it is interesting, I can submit a PR to support the Google Cloud Platform C++ Libraries (currently one library really), hosted on [GitHub](https://github.com/GoogleCloudPlatform/google-cloud-cpp/).

Thanks for the great package manager, btw.

### PR DESCRIPTION
**Pull request by coryan**
This adds support for the Google Cloud C++ libraries (currently one really).  It fixes #3093.
Feedback is welcome, as this is my first PR into this repository.

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for the PR!

Once the CLA is signed, I'll make any needed adjustments while merging and let you know for the future :)

**Comment by coryan** [comment]
Unfortunately I cannot sign the automated CLA.  I have signed the CLA negotiated between Google and Microsoft and sent it to both Microsoft's CLA automation team and to Google's licensing teams.

**Comment by ras0219-msft** [comment]
Thanks, I'll check in with them and get this sorted.

**Comment by coryan** [comment]
@ras0219-msft any news on the CLA front?  Would it help if I created a new PR?

**Comment by ras0219-msft** [comment]
I'm continuing to ping our CLA team -- I want to see this merged too :)

Sorry I don't have anything more concrete than that!

**Comment by coryan** [comment]
Magic happened, the PR is clear to commit, thank you!

**Comment by ras0219-msft** [comment]
Thanks again for making this PR!

While merging, I made a few changes to improve the port:
1. I used `vcpkg_from_github` which enables users to `install google-cloud-cpp --head` to get your latest master branch.
1. I simplified the source unpacking a little bit
1. I added a call to `vcpkg_fixup_cmake_targets()` which enables `find_package(bigtable_client REQUIRED)` to pick up the library.
1. I ran an automatic upgrade to v0.1.0 :)

Additionally, I found two upstream improvements you might want to make.

First, in the generated cmake config files, your targets have references to `gRPC::grpc++` and `protobuf::libprotobuf`, however they won't be available if a user just runs `find_package(bigtable_client REQUIRED)`.

To make this work, you simply need to add the following to the top of your `bigtable_client-config.cmake`:
```cmake
include(CMakeFindDependencyMacro)
find_dependency(grpc)
find_dependency(protobuf)
```

Second, would it make sense for `googleapis` to be a separate port? I see that it's a bunch of `.proto` definitions -- it might make sense to have a `googleapis` port that does one of:
1. Just package the `.proto` files directly
2. Generate the C++ sources and package them
3. Generate and compile the C++ sources into static libs / DLLs

Having it as a separate port will allow us to automatically upgrade it as a rolling release (rebuilding everything downstream to ensure no breakages).

Finally, I can add this to our list of automatically upgraded libraries, either as a rolling release or tag-based. Does taking the latest tag on your github repo seem appropriate or would it be better to filter it down to non-pre-release? Alternatively, we can do live-at-HEAD and use timestamps (see our abseil port), eagerly updating as long as there are no build breaks.

**Comment by coryan** [comment]
Thanks for finishing the merge and the thoughtful suggestions.  Let me answer them from easy to harder:

> To make this work, you simply need to add the following to the top of your
> bigtable_client-config.cmake:
> include(CMakeFindDependencyMacro)
> find_dependency(grpc)
> find_dependency(protobuf)

I have created a PR (GoogleCloudPlatform/google-cloud-cpp#400) to incorporate this idea, thank you again.

> Finally, I can add this to our list of automatically upgraded libraries, either as a rolling release or
> tag-based. Does taking the latest tag on your github repo seem appropriate or would it be better to
> filter it down to non-pre-release?

I think non-pre-release is better.

> Second, would it make sense for `googleapis` to be a separate port?

Yes, but that is a longer conversation.  We need to figure out if `googleapis` will get its own CMake files, and then how we would support that in multiple platforms. I created GoogleCloudPlatform/google-cloud-cpp#401 to remind us of doing that.

**Pull request merged**
