### PR TITLE
[openssl-unix] Update header path for shared library compilation

### PR DESCRIPTION
**Pull request by here-mikelley**
**Describe the pull request**

- What does your PR fix? Fixes issue #

Doesn't currently fix an issue 

- Which triplets are supported/not supported? Have you updated the CI baseline?

All triplets, including custom triplet for compiling Linux shared libraries

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

Yes

### CODE REVIEW

**Comment by LilyWangL** [comment]
Thanks for your PR! Can you please correct the Version field in the CONTROL file? You can get more information from [maintainer-guide.md](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md).

**Comment by here-mikelley** [comment]
> Thanks for your PR! Can you please correct the Version field in the CONTROL file? You can get more information from [maintainer-guide.md](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md).

Thanks, I've updated the version. Sorry about that.

**Comment by fabiencastan** [comment]
This PR fixes the issue for me. Thanks.

**Comment by ras0219-msft** [comment]
@here-mikelley Thanks for the PR and thanks @fabiencastan for confirming the fix!

**Pull request merged**
