### PR TITLE
[vcpkg|msys] Update some components

### LINKED ISSUE #19653: [vcpkg|msys] Update autconf to 2.71
currently 2.69

https://packages.msys2.org/base/autoconf

### PR DESCRIPTION
**Pull request by Neumann-A**
- closes #19653

### CODE REVIEW

**Comment by JonLiu1993** [comment]
@Neumann-A ,Could you please take a look?
````
CMake Error in Remoting/Views/CMakeLists.txt:
  Imported target "VTK::opengl" includes non-existent path

    "-framework OpenGL"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in Plugins/StreamLinesRepresentation/Representations/CMakeLists.txt:
  Imported target "VTK::opengl" includes non-existent path

    "-framework OpenGL"

````

**Comment by Neumann-A** [comment]
> @Neumann-A ,Could you please take a look?
> 
> ```
> CMake Error in Remoting/Views/CMakeLists.txt:
>   Imported target "VTK::opengl" includes non-existent path
> 
>     "-framework OpenGL"
> 
>   in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
> 
>   * The path was deleted, renamed, or moved to another location.
> 
>   * An install or uninstall procedure did not complete successfully.
> 
>   * The installation package was faulty and references files it does not
>   provide.
> 
> 
> 
> CMake Error in Plugins/StreamLinesRepresentation/Representations/CMakeLists.txt:
>   Imported target "VTK::opengl" includes non-existent path
> 
>     "-framework OpenGL"
> ```

This is an old ci regression. Just merge with master or rerun ci

**Comment by xavier2k6** [comment]
There's a few more that can be updated too bash, tar for example.

**Review by JonLiu1993 — APPROVED** [review]

**Comment by BillyONeal** [comment]
> There's a good few more that can be updated too (some you've already done) for example

This one is already passing so I'm going to merge it, but feel free to make a different PR @xavier2k6

@Neumann-A  Thanks for the updates!

**Pull request merged**
