### PR TITLE
[libpng] Strong cleanup of the port

### PR DESCRIPTION
**Pull request by cenit**
it might trigger some failures in other ports where we adopted patches to make the previous very convoluted port work

### CODE REVIEW

**Comment by cenit** [comment]
is CI still *broken*? so sorry, looks like fixing it is really much more difficult than expected

**Comment by cbezault** [comment]
OSX is migrating to new (much much much faster) hardware so the pipeline is paused right now. The mathGL failure on Linux looks like it couldn't reach the sourceforge server (which happens sometimes I guess) so nothing out of the ordinary there.

**Comment by cenit** [comment]
and what about the windows one? on x64-windows, just out of curiosity, I saw that neither opencv nor opencv4 or opencv3 have been rebuilt. All of them are stale and considered broken. You might imagine I don't like this situation 🤣

**Comment by PhoebeHui** [comment]
@cenit, thanks for the PR!

gdal:x64-windows-static failed with 'LINK : fatal error LNK1181: cannot open input file 'C:\vsts\_work\3\s\installed\x64-windows-static\lib\libpng16.lib', 

I checked that the lib name update to 'png16.lib', could you take a look?

**Comment by cenit** [comment]
@phoebeHui thanks for your review, I properly restored the library name for the windows static triplets

**Review by PhoebeHui — APPROVED** [review]

**Review by JackBoosY — APPROVED** [review]

**Review by ras0219-msft — APPROVED** [review]

**Pull request merged**
