### PR TITLE
[flatbuffers] Update to 2.0.8

### PR DESCRIPTION
**Pull request by JulZimmermann**
**Describe the pull request**

- updates version to 2.0.8.
- removes patch `no-werror`: -Werror isn't set by default anymore
- removes patch  `ignore_use_of_cmake_toolchain_file`: Seems not needed anymore

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
Yes

### CODE REVIEW

**Review by MonicaLiu0311 — DISMISSED** [review]

**Comment by JonLiu1993** [comment]
@JulZimmermann , Thanks for your pr, please get [failure logs here](https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/78342/artifacts?artifactName=failure%20logs%20for%20x64-linux&api-version=7.0&%24format=zip). Please ping me if you need any help.

**Comment by JulZimmermann** [comment]
Looks like this is caused by https://github.com/google/flatbuffers/issues/7499 and fixed with https://github.com/google/flatbuffers/pull/7502.

The fix isn't included in the 2.0.8 release. I created a patch with the changes from https://github.com/google/flatbuffers/pull/7502.

**Comment by MonicaLiu0311** [comment]
@JulZimmermann
Please get [failure logs here](https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/78379/artifacts?artifactName=failure%20logs%20for%20x86-windows&api-version=7.0&%24format=zip). Please ping me if you need any help.

**Comment by MonicaLiu0311** [comment]
@JulZimmermann , ping for response.

**Comment by MonicaLiu0311** [comment]
@JulZimmermann 
Convert this PR to draft since there is no progress. Please ping us if this PR is ready for review again.

**Comment by MonicaLiu0311** [comment]
Closing this PR since it seems that no progress is being made. Please ping us to reopen if work is still being done.

**Pull request closed without merging**
