### PR TITLE
 [libjuice] chore(version): updated to 1.0.2

### PR DESCRIPTION
**Pull request by crisboarna**
**Describe the pull request**
 Updating libjuice version.

- #### What does your PR fix?
It updates libjuice to latest version 1.0.2.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
Yes
Output:
```
./vcpkg x-add-version libjuice --overwrite-version                                                 ✔  4s   01:10:32 PM  
version 1.0.0 is already in .../vcpkg/versions/l-/libjuice.json
version 1.0.0 is already in .../vcpkg/versions/baseline.json
No files were updated for libjuice

```

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by FrankXie05** [comment]
The first time to change the version field just run the command `./vcpkg x-add-version libjuice`.
The parameter `--overwrite-version` just ensures that our `version` field remains unchanged and only modifies the hash value
You can get more information from [maintainer-guide.md](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md).

**Comment by crisboarna** [comment]
Hi, I have run the command, with the output received being:

```
./vcpkg x-add-version libjuice --overwrite-version                                 
version 1.0.0 is already in .../vcpkg/versions/l-/libjuice.json
version 1.0.0 is already in .../vcpkg/versions/baseline.json
No files were updated for libjuice
```

I have tried this with system vcpkg and with local repo built vcpkg with modifications done before, both yield same result.

**Comment by FrankXie05** [comment]
Just `./vcpkg x-add-version libjuice` no  `--overwrite-version`

**Comment by crisboarna** [comment]
Hi @FrankXie05 
Same result:

```
./vcpkg x-add-version libjuice                                                                     
version 1.0.0 is already in /Users/cris/vcpkg/versions/l-/libjuice.json
version 1.0.0 is already in /Users/cris/vcpkg/versions/baseline.json
No files were updated for libjuice
```

**Comment by crisboarna** [comment]
I am exactly on this branch, no changes. baseline.json has version `1.0.2` as on branch in Github.

```
git status                                                                            
On branch feat/libjuice-bump
Your branch is up to date with 'origin/feat/libjuice-bump'.

nothing to commit, working tree clean

```

**Comment by FrankXie05** [comment]
You need to update the hash. https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/74589/logs/62
````
2022-07-04T10:16:24.0806810Z              url : [ https://github.com/paullouisageneau/libjuice/archive/e7218e30fef3cd4437355aca817fa0980863973a.tar.gz ]
2022-07-04T10:16:24.0811314Z        File path : [ D:\downloads\paullouisageneau-libjuice-e7218e30fef3cd4437355aca817fa0980863973a.tar.gz.6756.part ]
2022-07-04T10:16:24.0815744Z    Expected hash : [ 958f99d926119ab666a2866fc4c66dc115077d0895aba55030ecb70486b47e8aa569e5f92fad5e6afc844c69eab8426d80c8fd09cf528935b2481b576e368364 ]
2022-07-04T10:16:24.0820134Z      Actual hash : [ b54c827774509915e98faec9891b5121ff50c01c33081480b805ca2f0910f26446cb75d7f721a0b8dfcc87ea7988c7020793befd2788ed132c0f608d434c7eca ]
````

**Comment by FrankXie05** [comment]
I can attach my full process and commands to you，
I have omitted some unnecessary content for ease of reading
````
PS E:\other\test> git clone https://github.com/crisboarna/vcpkg.git                                                  
   Cloning into 'vcpkg'...                                                                                           
   remote: Enumerating objects: 156045, done.                                                                        
   remote: Counting objects: 100% (293/293), done.                                                                   
   remote: Compressing objects: 100% (163/163), done.                                                                
   remote: Total 156045 (delta 187), reused 167 (delta 130), pack-reused 155752                                      
   Receiving objects: 100% (156045/156045), 60.67 MiB | 23.10 MiB/s, done.                                           
   Resolving deltas: 100% (98535/98535), done.                                                                       
   Updating files: 100% (8953/8953), done.                                                                           
   PS E:\other\test> cd .\vcpkg\                                                                                     
   PS E:\other\test\vcpkg> cat .\ports\libjuice\vcpkg.json                                                           
···                                                                                                  
   "version": "1.0.0",                                                                                                                                                                                                                                                                                          
···
PS E:\other\test\vcpkg> git chekcout feat/libjuice-bump                                                
   git: 'chekcout' is not a git command. See 'git --help'.                                                                                                                                                                                  
   The most similar command is                                                                                                  
   checkout                                                                                                   
   PS E:\other\test\vcpkg> git checkout feat/libjuice-bump                                                   
   Switched to a new branch 'feat/libjuice-bump'                                                             
   Branch 'feat/libjuice-bump' set up to track remote branch 'feat/libjuice-bump' from 'origin'.             
PS E:\other\test\vcpkg> cat .\ports\libjuice\vcpkg.json                                                     
 ```                                                                                                           
   "name": "libjuice",                                                                                            
   "version": "1.0.2",   
```   
   PS E:\other\test\vcpkg> git diff                                                                          
   diff --git a/ports/libjuice/portfile.cmake b/ports/libjuice/portfile.cmake                                
   REF e7218e30fef3cd4437355aca817fa0980863973a #v1.0.2                                                
   -    SHA512 958f99d926119ab666a2866fc4c66dc115077d0895aba55030ecb70486b47e8aa569e5f92fad5e6afc844c69eab8426d80c8fd09cf528935b2481b576e368364                   
   +    SHA512 b54c827774509915e98faec9891b5121ff50c01c33081480b805ca2f0910f26446cb75d7f721a0b8dfcc87ea7988c7020793befd2788ed132c0f608d434c7eca ^M               
                                                                                        
PS E:\other\test\vcpkg> git add .\ports\libjuice\portfile.cmake                                                       
PS E:\other\test\vcpkg> git commit -m "update hash"                                                                   
   [feat/libjuice-bump 6e6ceff9e] update hash                                                                            
   1 file changed, 1 insertion(+), 1 deletion(-)                                                                                                                                                                                         
                                                             
PS E:\other\test\vcpkg> .\bootstrap-vcpkg.bat                 
   Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2022-06-17/vcpkg.exe -> E:\other\test\vcpkg\vcpkg.exe... done.      
   Validating signature... done.                                                                                                           
   Telemetry                                                                                                           
   ---------                                                                                                             
   vcpkg collects usage data in order to help us improve your experience.                                           
   The data collected by Microsoft is anonymous.                                                                    
   You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,                      
   passing --disable-metrics to vcpkg on the command line,                                                         
   or by setting the VCPKG_DISABLE_METRICS environment variable.                                       
   Read more about vcpkg telemetry at docs/about/privacy.md       
   
PS E:\other\test\vcpkg> ./vcpkg x-add-version libjuice --overwrite-version           
   added version 1.0.2 to E:\other\test\vcpkg\versions\l-\libjuice.json                                                    
   version 1.0.2 is already in E:\other\test\vcpkg\versions\baseline.json 
````

**Comment by crisboarna** [comment]
Hi,

I have followed exactly your commands ... 

```
>git commit -m "update hash"                                                            
[feat/libjuice-bump d7bba619b] update hash
 1 file changed, 1 insertion(+), 1 deletion(-)
 >./bootstrap-vcpkg.sh
Downloading vcpkg-macos...
Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md
 >./vcpkg x-add-version libjuice --overwrite-version     
version 1.0.0 is already in .../vcpkg/versions/l-/libjuice.json
version 1.0.0 is already in .../vcpkg/versions/baseline.json
No files were updated for libjuice

```

vcpkg still does not seem to work for update version ...

**Comment by FrankXie05** [comment]
run `git pull` and try again

**Comment by crisboarna** [comment]
Ran once more: 
```
>git status                                                                                  
On branch feat/libjuice-bump
Your branch is up to date with 'origin/feat/libjuice-bump'.

nothing to commit, working tree clean
>git pull                                                                         
Already up to date.
>./vcpkg x-add-version libjuice --overwrite-version                             
version 1.0.0 is already in /Users/cris/vcpkg/versions/l-/libjuice.json
version 1.0.0 is already in /Users/cris/vcpkg/versions/baseline.json
No files were updated for libjuice
```

Still no change, i went into one of the failing action logs and got the expected hash from there ...

**Comment by crisboarna** [comment]
On a different note, can this and #25522 be merged for new versions to be reachable via vcpkg ? :)

And thank you very much for your rapid responses and assistance nonetheless !

**Comment by FrankXie05** [comment]
@crisboarna 

> Ran once more:
> 
> ```
> >git status                                                                                  
> On branch feat/libjuice-bump
> Your branch is up to date with 'origin/feat/libjuice-bump'.
> 
> nothing to commit, working tree clean
> >git pull                                                                         
> Already up to date.
> >./vcpkg x-add-version libjuice --overwrite-version                             
> version 1.0.0 is already in .../vcpkg/versions/l-/libjuice.json
> version 1.0.0 is already in .../vcpkg/versions/baseline.json
> No files were updated for libjuice
> ```
> 
> Still no change, i went into one of the failing action logs and got the expected hash from there ...

Could you please run command `cat .\ports\libjuice\vcpkg.json` and tell me the result?

**Comment by crisboarna** [comment]
```shell
> cat ports/libjuice/vcpkg.json                                                                           
{
  "name": "libjuice",
  "version": "1.0.2",
  "description": "The library is a simplified implementation of the Interactive Connectivity Establishment (ICE) protocol in C for POSIX platforms (including Linux and Apple macOS) and Microsoft Windows.",
  "homepage": "https://github.com/paullouisageneau/libjuice",
  "license": "LGPL-2.1-only",
  "dependencies": [
    {
      "name": "vcpkg-cmake",
      "host": true
    },
    {
      "name": "vcpkg-cmake-config",
      "host": true
    }
  ],
  "features": {
    "nettle": {
      "description": "Use nettle for HMAC computation instead of the Builtin",
      "dependencies": [
        "nettle"
      ]
    }
  }
}

 > ./vcpkg x-add-version libjuice --overwrite-version                                                    
version 1.0.0 is already in /Users/cris/vcpkg/versions/l-/libjuice.json
version 1.0.0 is already in /Users/cris/vcpkg/versions/baseline.json
No files were updated for libjuice

```

**Comment by FrankXie05** [comment]
sorry, can you run the command `cat  /Users/cris/vcpkg/versions/l-/libjuice.json`?

**Comment by crisboarna** [comment]
```shell
cat /Users/cris/vcpkg/versions/l-/libjuice.json                                                                                                   ✔  04:48:47 PM 
{
  "versions": [
    {
      "git-tree": "02ea9a1ae4e054d9474f801747e5edd17a3d8ad1",
      "version": "1.0.0",
      "port-version": 0
    },
    {
      "git-tree": "62c215b49c59158589a9bc98d02b20243ef1bf0b",
      "version": "0.9.8",
      "port-version": 0
    },
    {
      "git-tree": "f544d762be0d7f9016b47f865843d0e575535166",
      "version": "0.9.6",
      "port-version": 0
    },
    {
      "git-tree": "564ac624cbbabb45356d592264c090a0e6f64669",
      "version": "0.9.1",
      "port-version": 0
    },
    {
      "git-tree": "077151e85bf11cabc11d0f1c46b778b5a21829dd",
      "version": "0.8.4",
      "port-version": 0
    },
    {
      "git-tree": "42cecee2b8da92c2c8c120c09bd663b20f2c947a",
      "version": "0.7.1",
      "port-version": 0
    },
    {
      "git-tree": "e7ef5f1f7d883e5f8a7dcb52ea5821730281e375",
      "version-string": "0.6.0",
      "port-version": 0
    },
    {
      "git-tree": "44d596ff7bfe74a699564ed6dcca46001f4ff95b",
      "version-string": "0.5.2",
      "port-version": 0
    }
  ]
}
```

**Comment by FrankXie05** [comment]
From the result, your `version` field is not written into `libjuice.json`, re-run the script(.\bootstrap-vcpkg.bat or \bootstrap-vcpkg.sh) and run the command `./vcpkg x-add-version`
Make sure you format vcpkg.json before doing everything. Run command `./vcpkg format-manifest .\ports\libjuice\vcpkg.json`

**Pull request merged**
