### PR TITLE
[cyclonedds-cxx] Update to 0.10.3

### PR DESCRIPTION
**Pull request by ex-purple**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by ex-purple** [comment]
Depends on https://github.com/microsoft/vcpkg/pull/30413

**Comment by LilyWangLL** [comment]
Feature `cyclonedds-cxx[idllib]` passed on `x64-linux`.

**Comment by LilyWangLL** [comment]
Please add the following codes in `portfile.cmake`:
```
if ("idllib" IN_LIST FEATURES)
    if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")
    	file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/bin" "${CURRENT_PACKAGES_DIR}/debug/bin")
    endif()
endif()
```

**Comment by ex-purple** [comment]
@LilyWangLL 
Why is it needed? These folders do not exist

**Comment by LilyWangLL** [comment]
```
PS E:\Lily\30414> .\vcpkg.exe install cyclonedds-cxx[idllib]:x64-windows-static
Computing installation plan...
The following packages will be built and installed:
    cyclonedds-cxx[core,idllib]:x64-windows-static -> 0.10.3
Detecting compiler hash for triplet x64-windows-static...
Installing 1/1 cyclonedds-cxx:x64-windows-static...
Building cyclonedds-cxx[core,idllib]:x64-windows-static...
-- Downloading https://github.com/eclipse-cyclonedds/cyclonedds-cxx/archive/0.10.3.tar.gz -> eclipse-cyclonedds-cyclonedds-cxx-0.10.3.tar.gz...
-- Extracting source E:/Lily/30414/downloads/eclipse-cyclonedds-cyclonedds-cxx-0.10.3.tar.gz
-- Using source at E:/Lily/30414/buildtrees/cyclonedds-cxx/src/0.10.3-36c9dfb596.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Installing: E:/Lily/30414/packages/cyclonedds-cxx_x64-windows-static/share/cyclonedds-cxx/copyright
-- Performing post-build validation
warning: DLLs should not be present in a static build, but the following DLLs were found:

    E:\Lily\30414\packages\cyclonedds-cxx_x64-windows-static\debug\bin\cycloneddsidlcxx.dll
    E:\Lily\30414\packages\cyclonedds-cxx_x64-windows-static\bin\cycloneddsidlcxx.dll

warning: There should be no bin\ directory in a static build, but E:\Lily\30414\packages\cyclonedds-cxx_x64-windows-static\bin is present.
warning: There should be no debug\bin\ directory in a static build, but E:\Lily\30414\packages\cyclonedds-cxx_x64-windows-static\debug\bin is present.
warning: If the creation of bin\ and/or debug\bin\ cannot be disabled, use this in the portfile to remove them
    if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")
        file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/bin" "${CURRENT_PACKAGES_DIR}/debug/bin")
    endif()

error: Found 2 post-build check problem(s). To submit these ports to curated catalogs, please first correct the portfile: 
```
@ex-purple This is the output log.

**Comment by ex-purple** [comment]
@LilyWangLL I understand this only happens on Windows.

But if I remove these libraries, then the [idllib] feature will lose its meaning. 
The cycloneddsidlcxx library always must be dynamic, because it is a dynamic plugin for idlc tool from cyclonedds port.

We should suppress this warning or I can disable this feature for the "windows & static" case. The first option is preferred because it makes the code generation feature available in Windows.

**Comment by ex-purple** [comment]
@LilyWangLL 
>  it is unreasonable to generate *.dll files under static build

But this is exactly what the design of the CycloneDDS project implies.
You can build the cyclondds library statically or dynamically, but the IDL library must always be a dynamic plugin

This restriction deprives port users of a convenient code generation tool

**Comment by ex-purple** [comment]
Example of the usage:
```cmake
find_package(CycloneDDS-CXX CONFIG REQUIRED)

file(GLOB IDL_SOURCE ${CMAKE_CURRENT_SOURCE_DIR}/idl/*.idl)

# this command run idlc tool that use dynamic **idlccxx** as plugin
idlcxx_generate(TARGET dds_data_structures_cxx 
    FILES "${IDL_SOURCE}"
    DEFAULT_EXTENSIBILITY final
)

# this command links main target with **ddscxx** library that may by static or dynamic
target_link_libraries(main PRIVATE CycloneDDS-CXX::ddscxx
```

**Comment by LilyWangLL** [comment]
> The dll plugin library it is a part of building system application based on DDS. It's not runtime library, it's part of the code generation.
> 
> I use static linkage for the CycloneDDS, but I need dynamic IDL plugin library for the code generation. CycloneDDS may builds as static library but for the code generation you need IDL dynamic library as plugin for the idlc tool.
> 
> Maybe I should install the IDL plugin library to the tools folder?

cc @vicroms About installation of this feature, could you please give some suggestions? Thanks in advance.

**Comment by LilyWangLL** [comment]
> > The dll plugin library it is a part of building system application based on DDS. It's not runtime library, it's part of the code generation.
> > I use static linkage for the CycloneDDS, but I need dynamic IDL plugin library for the code generation. CycloneDDS may builds as static library but for the code generation you need IDL dynamic library as plugin for the idlc tool.
> > Maybe I should install the IDL plugin library to the tools folder?
> 
> cc @vicroms About installation of this feature, could you please give some suggestions? Thanks in advance.

cc @BillyONeal  Please give some suggestions about this PR. Thanks~

**Comment by LilyWangLL** [comment]
> Maybe I should install the IDL plugin library to the tools folder?

@ex-purple Sorry for the late reply, this point is correct, please install the IDL plugin library to the tools folder. Thanks.

**Comment by LilyWangLL** [comment]
> > Maybe I should install the IDL plugin library to the tools folder?
> 
> @ex-purple Sorry for the late reply, this point is correct, please install the IDL plugin library to the tools folder. Thanks.

Please also fix port `cyclonedds`.

**Comment by BillyONeal** [comment]
> Please also fix port `cyclonedds`.

It looks like https://github.com/microsoft/vcpkg/pull/30413/ already did?

**Comment by BillyONeal** [comment]
vcpkg-team-review: Do we allow DLLs in static? I always get this mixed up (as to me without single binary deployment static loses all meaning).

**Comment by dg0yt** [comment]
... in "static" as in x64-windows-static (static CRT) or as in x64-windows-static-md (dynamic CRT) or as in x64-mingw-static (dynamic CRT)?

**Comment by BillyONeal** [comment]
> ... in "static" as in x64-windows-static (static CRT) or as in x64-windows-static-md (dynamic CRT) or as in x64-mingw-static (dynamic CRT)?

As in `x64-windows-static`. I don't remember if that's what we require right now or not.

**Comment by LilyWangLL** [comment]
> > Please also fix port `cyclonedds`.
> 
> It looks like #30413 already did?

`cyclonedds` generated *.dll files under the static build too.

**Comment by dg0yt** [comment]
> As in `x64-windows-static`.

The last file list from vcpkg.ci shows 128 files matching *.dll in x64-windows-static, 19 of them being in `bin/` (6 llvm, 4 gfortran, 2 directx-dxc, 2 geotrans, 2 lapack-reference, 1 winsparkle, 1 xaudio2redist, 1 arpack-ng). The others are in `debug`, `lib`, `tools`, `plugins`.

**Comment by BillyONeal** [comment]
@JavierMatosD @dan-shaw @vicroms @ras0219-msft and I discussed this today but ran out of time to fully cover the topic. There is some nuance with how many CRTs are implicated in the process and similar; my understanding of 'static means single binary deployment is the point' is not how this was interpreted before (as @dg0yt points out).

We'll be discussing it again soon I guess.

**Comment by ex-purple** [comment]
I just want to point out that this port would be pretty much useless without the idl plugin library. And it doesn't matter if it is builds statically or dynamically. In any of these cases, we need idlcxx plugin library.

**Comment by BillyONeal** [comment]
@JavierMatosD @dan-shaw @vicroms @ras0219-msft @markle11m and I discussed this last Thursday. (Sorry, I dropped the ball on writing up the results until now :( )

Static is a request to build everything that is possible to build statically statically. The idea is adhere to the user's request to the maximum extent possible. Our choice is "fail their build" or "give them something that might be acceptable" we chose the latter. This is why we disallow static linking the CRT in that condition in vcpkg_check_linkage, beause most of the world isn't prepared for multiple CRTs flying around. This means x64-windows-static-md is allowed but x64-windows-static is not.

>But if I remove these libraries, then the [idllib] feature will lose its meaning.
The cycloneddsidlcxx library always must be dynamic, because it is a dynamic plugin for idlc tool from the cyclonedds port.

Does this mean that those DLLs should be in the tools directory and not in the bin directory at all? That would totally resolve all concerns here.

**Comment by ex-purple** [comment]
@BillyONeal 
> That would totally resolve all concerns here.

Not really.
If we save the plugin to the tools folder, then it is not quite obvious how exactly idlc tool will look for it.

idlc is installed in the `tools/cyclonedds` and look plugins in the library folder. If we will install idlcxx plugin to the `tools/cyclonedds-cxx` folder idlc just will not find it

**Comment by BillyONeal** [comment]
The situation is "in bin means end user must deploy with their app", so if this is some kind of plugin for a tool it should not be in bin. Perhaps there needs to be some patching of the tools in question to do the right thing?

The DLLs in question do appear to break the 'several copies of CRT' rule / exception carved out above; `packages\cyclonedds_x64-windows-static\debug\bin\cycloneddsidl.dll` for example was built with `/MTd` which embeds a copy of the CRT into that DLL.

That "ddsperf" depends on "idlc" as a host dependency suggests that the "idlc" feature not supporting static-windows is not too big a problem? After all, if you want the tool to be runnable it needs to be a host dependency, and all the default native triplets on Windows are dynamic.

**Pull request closed without merging**
