### PR TITLE
[boost-modular-build-helper] Allow setting B2_OPTIONS_[DBG|REL] in BOOST_CMAKE_FRAGMENT (fixes #15273)

### LINKED ISSUE #15273: [boost-modular-build-helper] Allow setting B2_OPTIONS_[DBG|REL] in BOOST_CMAKE_FRAGMENT
**Is your feature request related to a problem? Please describe.**
Based on the comment [ports/boost-modular-build-helper/boost-modular-build.cmake:8](https://github.com/microsoft/vcpkg/blob/master/ports/boost-modular-build-helper/boost-modular-build.cmake#L8), that is

> Next CMake variables may be overridden in the file specified in ${_bm_BOOST_CMAKE_FRAGMENT},

one should be able to set the variables `B2_OPTIONS_DBG` and `B2_OPTIONS_REL` inside a `BOOST_CMAKE_FRAGMENT`, i.e. inside the files which are typically named `b2-options.cmake`.
However, these two variables are `set` at line [216](https://github.com/microsoft/vcpkg/blob/master/ports/boost-modular-build-helper/boost-modular-build.cmake#L216) and line [227](https://github.com/microsoft/vcpkg/blob/master/ports/boost-modular-build-helper/boost-modular-build.cmake#L227) respectively, meaning that they cannot be used as an input to the `boost_modular_build`. This is problematic since it removes the possibility to pass `B2_OPTIONS` only for `Debug` or only for `Release` builds.

**Proposed solution**
Use `list(APPEND` instead of `set`. I'll submit a pull request right after this issue is submitted.

**Describe alternatives you've considered**
I need to be able to pass `B2_OPTIONS_DBG` to fix another issue with `boost-python` (not opened formally yet). Another solution would be to include the fix to the issue with `boost-python` directly in `boost-modular-build.cmake`. However, this would break separation of concern and this would couple the implementation of `boost-python` and `boost-modular-build-helper`, making maintenance and improvements harder.

### PR DESCRIPTION
**Pull request by klalumiere**
**Describe the pull request**

- What does your PR fix? Fixes #15273

- Which triplets are supported/not supported? Have you updated the CI baseline? The same. No.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)? Yes

### CODE REVIEW

**Comment by PhoebeHui** [comment]
@klalumiere, thanks for your contribution!

Could resolve the conflicts?

**Comment by klalumiere** [comment]
Done! :heavy_check_mark:

**Review by PhoebeHui — APPROVED** [review]
LGTM, thanks for your updates!

**Comment by BillyONeal** [comment]
Thanks for the help!

**Pull request merged**
