### PR TITLE
[aubio] patches for UWP builds

### PR DESCRIPTION
**Pull request by aybe**
And my last patch for aubio on UWP (first intent) !

**Requirements:**
[libsndfile] patches for UWP builds #2216
[libflac] patches for UWP builds #2214

### CODE REVIEW

**Comment by bagong** [comment]
How about updating to 0.46 release version at the same time? It might be enough to change the download link to https://github.com/aubio/aubio/archive/0.4.6.tar.gz ?

**Comment by ras0219-msft** [comment]
@aybe Thanks for these three PRs!

Overall, the patches look pretty reasonable. However, there's just one snag: we use the same sources to build for every platform (which reduces build times, sometimes significantly). This means that conditional patching based on the platform doesn't work, since if you run `vcpkg install aubio:x64-uwp` and then `vcpkg install aubio:x64-windows`, you'll get the "most patched" version of the sources.

Instead, the patches should insert `#ifdef`'s that keep the code buildable for all platforms. This makes it much easier to upstream them later on as well :)

Here's an example of what to use for the macros: https://github.com/Microsoft/vcpkg/blob/1a6d0f5611882618f9179898448ca56770ff2ab0/ports/mongo-c-driver/fix-uwp.patch. Specifically:
```cpp
#if defined (WINAPI_FAMILY_PARTITION) && !WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM)
// This is UWP, new code goes here
#else
// this is desktop, original code stays in here
#endif
```

**Comment by aybe** [comment]
@bagong updated and now uses vcpkg_from_github instead

@ras0219-msft I have changed all the 3 packages to use `#ifdef` instead and confirm they all build

**Comment by aybe** [comment]
@ras0219-msft talked a bit too fast, forgot a `return` in fact, fixed now !

**Comment by alexkaratarakis** [comment]
Thanks!

**Pull request merged**
