### PR TITLE
[xaudio2redist] Update for XAudio2Redist 1.2.10 release

### PR DESCRIPTION
**Pull request by walbourn**
# Version 1.2.10
* Fixed Clang and GCC compiler warnings.

### CODE REVIEW

**Comment by walbourn** [comment]
Verified all supported triplets

```
vcpkg install xaudio2redist:x86-windows
vcpkg install xaudio2redist:x86-windows-static-md
vcpkg install xaudio2redist:x64-windows
vcpkg install xaudio2redist:x64-windows-static-md
vcpkg install xaudio2redist:x64-mingw-static
vcpkg install xaudio2redist:x86-mingw-static
```

Also built some library triplets that use it:

```
vcpkg install directxtk[xaudio2redist]:x64-windows
vcpkg install directxtk[xaudio2redist]:x64-windows-static-md
vcpkg install directxtk[xaudio2redist]:x86-windows
vcpkg install directxtk[xaudio2redist]:x86-windows-static-md

vcpkg install directxtk[xaudio2redist]:x64-mingw-static
vcpkg install directxtk[xaudio2redist]:x86-mingw-static

vcpkg install directxtk12[xaudio2redist]:x64-windows
vcpkg install directxtk12[xaudio2redist]:x64-windows-static-md
vcpkg install directxtk12[xaudio2redist]:x86-windows
vcpkg install directxtk12[xaudio2redist]:x86-windows-static-md

vcpkg install directxtk12[xaudio2redist]:x64-mingw-static
vcpkg install directxtk12[xaudio2redist]:x86-mingw-static
```

**Review by FrankXie05 — DISMISSED** [review]

**Review by BillyONeal — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks!

**Comment by Neumann-A** [comment]
Why does this port have `!staticcrt`? There are 3 libs one suffixed with `_md` linking MSVCRT the other one with the same name but without the suffix linking libcmt. The third one does not have any directives.  

There is also this comment in the targets file:
```
    <!-- By default, the project links with xapobaseredist.lib which depends on the static runtime library.
         An alternate version of the library, xapobaseredist_md.lib is provided if the dynamic runtime library is preferred.
         To make the project link with it, set the environment variable XAPODynamicCRT to 1. Or you can do it by adding the
         following to your .vcxproj file:
           <PropertyGroup>
             <XAPODynamicCRT>1</XAPODynamicCRT>
           </PropertyGroup>
    -->
```

So from my point of view the support statement is false and also the `vcpkg_check_linkage` statement in the portfile. It should  simply be `set(VCPKG_LIBRARY_LINKAGE dynamic)` without further checks.

**Comment by walbourn** [comment]
The XAudio2Redist is a bit of an odd duck.

The primary library ``xaudio2.lib`` is just an import library for the DLL.

There's then optionally a rarely used static C++ library for implementing custom xAPOs: ``xapobaseredist.lib``. This one comes in two flavors: DEBUG and RELEASE. They both assume the DLL versions of the CRT is being used, and won't link with the static MSVC CRT.

**Comment by walbourn** [comment]
I see from the MSBuild that it's supposed to be ``/MD`` vs. ``/MT``. The XAudio2 DLL itself always use the DLL version of the CRT, but it uses the one built into the OS rather than the retail VC DLL.

**Comment by walbourn** [comment]
So the port has logic for handling ``/MD`` .vs ``/MT`` selection of the static C++ library per this code:

```
if(VCPKG_CRT_LINKAGE STREQUAL dynamic)
   file(INSTALL "${PACKAGE_PATH}/build/native/debug/lib/${VCPKG_TARGET_ARCHITECTURE}/xapobaseredist_md.lib" DESTINATION "${CURRENT_PACKAGES_DIR}/debug/lib")
   file(INSTALL "${PACKAGE_PATH}/build/native/release/lib/${VCPKG_TARGET_ARCHITECTURE}/xapobaseredist_md.lib" DESTINATION "${CURRENT_PACKAGES_DIR}/lib")
else()
   file(INSTALL "${PACKAGE_PATH}/build/native/release/lib/${VCPKG_TARGET_ARCHITECTURE}/xapobaseredist.lib" DESTINATION "${CURRENT_PACKAGES_DIR}/lib")
   file(INSTALL "${PACKAGE_PATH}/build/native/debug/lib/${VCPKG_TARGET_ARCHITECTURE}/xapobaseredist.lib" DESTINATION "${CURRENT_PACKAGES_DIR}/debug/lib")
endif()
```

I maintain a number of ports, so my memory is a little fuzzy, but I think the error was introduced with https://github.com/microsoft/vcpkg/pull/24104

**Comment by walbourn** [comment]
OK, now the memory has paged back in :)

Technically, the port should be:

```
"supports": "windows & !arm & !uwp & !static"
```

In other words, it *can* support ``VCPKG_CRT_LINKAGE`` of dynamic and static, but the core library can only support ``VCPKG_LIBRARY_LINKAGE`` of dynamic.

The thing is, there isn't any triplet that defines:

```
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE dynamic)
```

**Comment by Neumann-A** [comment]
Library linkage for this library is irrelevant  since it is a prebuild

**Comment by walbourn** [comment]
> Library linkage for this library is irrelevant since it is a prebuild

Logically, if you are using a ``static`` triplet, you expect all dependencies to be bound into your executable binary. The ``static-md`` triplet means all dependencies are in your library except the CRT DLLs which have to be deployed.

In the case of **xaudio2redist**, **dxsdk-d3dx**, **dstorage**, etc. you always have a DLL you must redist and none of them provide a statically linked library.

Your comparison to OpenGL is not the same. OpenGL has a well-known deployment redistributable model which will add all required DLLs to the system. The same is true of the MSVC CRT redist package. For these ports, they all expect the *application* to deploy the DLL.

**Comment by walbourn** [comment]
Note this conversion has moved to https://github.com/microsoft/vcpkg/pull/28699

**Comment by dg0yt** [comment]
> Logically, if you are using a static triplet, you expect all dependencies to be bound into your executable binary.

... if possible.
Not having to distribute DLLs is just one possible reason for choosing a static triplet.
If vcpkg was so strict on static linkage, it couldn't offer `vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)`.

**Pull request merged**
