### PR TITLE
[blaze] Fix the SHA512 in the 'portfile.cmake'

### PR DESCRIPTION
**Pull request by igl42**
Dear vcpkg-Team!

The SHA512 of the download file for Blaze-3.4 has changed. This pull request adapts the vcpkg port for the Blaze library. Thanks for your help,

Best regards,

   Klaus!

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks Klaus!

In the future, could you consider minting a simple 3.4.1 when you find issues with a release? I think there's an expectation (beyond vcpkg) that tags are never to be moved, even if it's just a quick <24h hotfix :)

**Comment by igl42** [comment]
Thanks Robert for handling this issue so well. You are correct, I didn't even consider this option since it never happened in the past. Next time I will follow your suggestion.

Allow me a question about the `avoid-src-dir-generation.patch` file that was added. Is this intended as a patch for the Blaze `CMakeLists.txt` or only required for vcpkg?

Thanks again!

**Comment by igl42** [comment]
And if I may I have a second question: How did you compute the SHA512 for the `portfile.cmake` in your commit 7771899? Unfortunately I failed to reproduce it, but I will likely need to do the same in the next releases. Thanks a lot!

**Comment by ras0219-msft** [comment]
>Is this intended as a patch for the Blaze …

Imo, it would improve the blaze buildsystem if you made these changes upstream; it's considered poor CMake practice to modify the source directory during the build. However, we have unfortunately not gotten the time to properly propose it as a PR.

In the concrete case of Vcpkg, we actually configure Release and Debug _simultaneously_ on Windows so having both of them write into the source directory actually causes intermittent build failures :).

>How did you compute the SHA512

We run `vcpkg install blaze` with a `0` for the SHA512 (after updating the REF) and let it tell us what the right hash is :). The error message prints both the expected hash and the actual hash in a form that's easy to copy-paste into the file.

**Comment by igl42** [comment]
Thanks a lot, this definitely helps. I will make sure to add you to the list of Blaze contributors.

**Pull request merged**
