### PR TITLE
[vcpkg] GENERATOR with Makefiles can build parallel

### LINKED ISSUE #26779: [vcpkg] GENERATOR with Makefiles can build parallel
****

**Is your feature request related to a problem? Please describe.**
GENERATOR with Makefiles the port build very slow

**Proposed solution**
GENERATOR with Makefiles can build parallel

**Describe alternatives you've considered**
#26780

**Additional context**
None

### PR DESCRIPTION
**Pull request by day253**
**Describe the pull request**

- #### What does your PR fix?
  Fixes #26779 

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  `all`, `Yes`

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  `Yes`

### CODE REVIEW

**Comment by JonLiu1993** [comment]
Ping @day253 for response, Is work still being done for this PR?

**Comment by dg0yt** [comment]
@day253 Are there any reasons for premature closure which we might help overcome?

**Comment by day253** [comment]
> Ping @day253 for response, Is work still being done for this PR?

Yes, I am still working on it. I test this while I am building libtorch. It works fine, but I don't know it's the right way to fix it.

**Comment by day253** [comment]
> @day253 Are there any reasons for premature closure which we might help overcome?

Can I reopen this PR? I test this PR on some ports. It works fine, but I don't know it's the right way to fix it.

**Pull request closed without merging**
