### PR TITLE
[libmariadb] Fix plugin installation, fix pkgconfig

### LINKED ISSUE #18749: [libmariadb] Missing caching_sha2_password.so for Linux/MacOs build
****

There are missing dynamic files for libMariaDB in the case of build on Linux and MacOS.

MariaDB connector needs for example caching_sha2_password when connecting to MySQL 8.0. Without this file, MariaDB library returns error `"Plugin caching_sha2_password could not be loaded: dlopen(PATH/caching_sha2_password.so.2) image not found`

- Windows: This file (together with others) is correctly built and installed for windows to "plugin" directory.
- Linux: some of these files are built but not installed. Files can be found at `vcpkg/buildtrees/libmariadb/x64-linux-dbg/caching_sha2_password.so 
- MacOS: these files are completely missing and not build

I'm installing it via `vcpkg install libmariadb`

### PR DESCRIPTION
**Pull request by JackBoosY**
Fix plugin installation code in:
- `install_plugins.cmake`.
- `portfile.cmake`.
- `mariadb_version.h.in` and `mariadb_config.c.in`.

Fix pkgconfig file.

Fixes #18749.

### CODE REVIEW

**Comment by JackBoosY** [comment]
@ludekvodicka  Can you please test my changes?

Thanks.

**Comment by ludekvodicka** [comment]
Sure.

On Windows, everything seems ok. Only `plugin` directory was moved from `x86-windows\bin\plugin` to `x86-windows-plugin`, but this is ok.

I will also test it on Linux/OSX and let you know.

**Comment by ludekvodicka** [comment]
Unfortunately, Linux and OSX don't work. 

chrome_2021-07-02_12-19-14

**Comment by JackBoosY** [comment]
@ludekvodicka  Please test again.

Thanks.

**Comment by ludekvodicka** [comment]
> @ludekvodicka Please test again.
> 
> Thanks.

Looks good. OSX and Linux are working great now. Thanks

chrome_2021-07-05_08-41-16

**Review by NancyLi1013 — APPROVED** [review]

**Pull request merged**
