### PR TITLE
Add port nsync

### PR DESCRIPTION
**Pull request by ehsan-mohammadi**
Add new port `nsync`.

### CODE REVIEW

**Comment by Voskrese** [comment]
empty folder.  enabled politic empty folder

**Comment by Voskrese** [comment]
@ehsan-mohammadi 

`set(VCPKG_POLICY_EMPTY_PACKAGE enabled)`

**Comment by ehsan-mohammadi** [comment]
> @ehsan-mohammadi
> 
> `set(VCPKG_POLICY_EMPTY_PACKAGE enabled)`

@Voskrese Should I add `TARGET_TRIPLET STREQUAL` to the `portfile.cmake`? Because some checks were not successful

**Comment by Voskrese** [comment]
this is enough, there is only a header

...

```
vcpkg_install_cmake()

set(VCPKG_POLICY_EMPTY_PACKAGE enabled) # automatic templates
configure_file(${SOURCE_PATH}/LICENSE ${CURRENT_PACKAGES_DIR}/share/${PORT}/copyright COPYONLY)
```

it is possible simply through COPY

example
https://github.com/microsoft/vcpkg/pull/7542/files

**Comment by ehsan-mohammadi** [comment]
> this is enough, there is only a header
> 
> ...
> 
> ```
> vcpkg_install_cmake()
> 
> set(VCPKG_POLICY_EMPTY_PACKAGE enabled) # automatic templates
> configure_file(${SOURCE_PATH}/LICENSE ${CURRENT_PACKAGES_DIR}/share/${PORT}/copyright COPYONLY)
> ```
> 
> it is possible simply through COPY
> 
> example
> https://github.com/microsoft/vcpkg/pull/7542/files

Thanks, I try to add a new pull request.

**Pull request closed without merging**
