### PR TITLE
[crashpad]Upgrade crashpad to latest version

### PR DESCRIPTION
**Pull request by omartijn**
**Describe the pull request**

- #### What does your PR fix?  
Updates crashpad. This fixes some bugs and also implements attachments for crash reports

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
No changes. Windows/mac. I've tested it on linux by also applying #14211 which sadly isn't getting merged.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
Yes

### CODE REVIEW

**Comment by JonLiu1993** [comment]
@omartijn ,Please take a look :
````
ERROR at //third_party/mini_chromium/mini_chromium/build/config/BUILD.gn:435:15: Unknown substitution pattern
    command = "$cc -MMD -MF $depfile {{defines}} {{include_dirs}} {{framework_dirs}} {{cflags}} {{cflags_c}}${extra_cflags}${extra_cflags_c} -c {{source}} -o {{output}}"
              ^----------------------------------------------------------------------------------------------------------------------------------------------------------
Found a {{ at offset 57 and did not find a known substitution following it.
See //build/test.gni:43:7: which caused the file to be included.
      executable(target_name) {
      ^------------------------
````

**Comment by omartijn** [comment]
Hmm, it looks like latest crashpad uses some newer ninja functions and the ninja coming with vcpkg is outdated.

**Comment by omartijn** [comment]
@JonLiu1993 Turns out it was GN in need of updating, but only on Windows. I've added this change as a separate commit (so it can easily be cherry-picked if desired).

Please let me know if you would like me to split up the PR so that one PR updates GN only. I'm a bit conflicted on this since it's only a dependency, not an actual port.

**Comment by JonLiu1993** [comment]
@omartijn ，As you said, I suggest a separate PR to update GN, because in this regard, we will solve this update step by step.

**Comment by JonLiu1993** [comment]
@omartijn ，Are you still working on this pr?

**Comment by omartijn** [comment]
Well, I am a bit stuck on upgrading gn in a different PR. That rebuilds almost the entire catalogue and that results in some errors I believe are unrelated.

**Comment by JonLiu1993** [comment]
> Well, I am a bit stuck on upgrading gn in a different PR. That rebuilds almost the entire catalogue and that results in some errors I believe are unrelated.

@omartijn ，If it is not feasible to upgrade gn with a different pr, we still upgrade in the original way, as you said, it is not a port

**Comment by omartijn** [comment]
@JonLiu1993 Shall I mark this PR as ready for review, then?

**Comment by JonLiu1993** [comment]
> @JonLiu1993 Shall I mark this PR as ready for review, then?

It seems that CI was not successful. After I rerun, we will look at the specific errors.

**Comment by JonLiu1993** [comment]
@omartijn ,Thanks for your pr,I will close this pr for now, if you need to repair this pr, you can reopen it

**Pull request closed without merging**
