### PR TITLE
[openssl] Update to 3.0.3

### LINKED ISSUE #24534: [OpenSSL] update to 3.0.3
Library name: OpenSSL

New version number: 3.0.3

Other information that may be useful (release notes, etc...)
https://www.openssl.org/source/
https://github.com/openssl/openssl/tags
https://www.openssl.org/news/secadv/20220503.txt
https://www.openssl.org/news/newslog.html

### PR DESCRIPTION
**Pull request by Thomas1664**
**Describe the pull request**

- #### What does your PR fix?
  Fixes #24534

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  Unchanged

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

### CODE REVIEW

**Comment by Thomas1664** [comment]
@Neumann-A qtwebengine:x64-uwp looks like a baseline regression

**Review by JonLiu1993 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the update!

**Pull request merged**
