### PR TITLE
[lua] update to 5.4.0

### LINKED ISSUE #12344: [Lua] update to 5.4.0
Library name: Lua

New version number: 5.4.0

Website: [lua.org](https://www.lua.org/) 

Source: [5.4.0](https://www.lua.org/ftp/lua-5.4.0.tar.gz) 

Breaking changes: [manual](https://www.lua.org/manual/5.4/manual.html#8)

### PR DESCRIPTION
**Pull request by JonLiu1993**
Fix #12344 

Update lua to the latest version 5.4.0

All features have passed with the following triplets:

- x64-windows
- x86-windows
- x64-windows-static

### CODE REVIEW

**Comment by kevinlul** [comment]
Because even Lua minor version bumps [break compatibility](https://www.lua.org/manual/5.4/manual.html#8) and some downstream libraries thus lock to specific versions of Lua, is it vcpkg policy to still keep one port up-to-date over some side-by-side approach?

**Review by NancyLi1013 — APPROVED** [review]

**Review by NancyLi1013 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks :D !

**Pull request merged**
