### PR TITLE
[reproc] Enabled C++ target for version 6.0.0.

### PR DESCRIPTION
**Pull request by qis**
After the upgrade to version 6.0.0 the C++ target is neither built nor installed.

This PR fixes the build and install part, but leaves the usasge message alone since the cmake scripts are generated using a broken library (cddm) and don't work.

The library (both, `reproc` and `reproc++`) can still be used when linking manually.

### CODE REVIEW

**Comment by qis** [comment]
Eh... I don't follow. Did I do something wrong? Forgot a check?

**Comment by ras0219-msft** [comment]
Nope, we just had a hiccup in the pipeline :)

Thanks for the PR!

**Comment by DaanDeMeyer** [comment]
@qis Any suggestions on how I can improve the reproc CMake scripts? cddm just installs each configured library to the standard cmake install directories. This works perfectly with the Unix directory structure but unfortunately vcpkg does not like a package installing multiple targets. I made an issue (https://github.com/microsoft/vcpkg/issues/4888) to improve the situation but unfortunately there hasn't been any response yet.

**Pull request merged**
