### PR TITLE
Detours respects build type

### LINKED ISSUE #20775: [detours] build failure under "set(VCPKG_BUILD_TYPE release)"
**Host Environment**
- OS: Windows
- Compiler: any

**To Reproduce**
`./vcpkg install --triplet=x64-windows-release --overlay-triplets=.`
with the current working directory containing this "vcpkg.json":
```
{
    "name": "test",
    "version-string": "1",
    "dependencies": [
        "detours"
    ]
}
```
and this "x64-windows-release" triplet file:
```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_BUILD_TYPE release)
```

**Failure logs** 
```
-- Installing: D:/GitHub/vcpkg/packages/detours_x64-windows-release/lib/detours.pdb
CMake Error at ports/detours/portfile.cmake:23 (file):
  file INSTALL cannot find
  "D:/GitHub/vcpkg/buildtrees/detours/x64-windows-release-dbg/lib.x64Debug":
  File exists.
Call Stack (most recent call first):
  scripts/ports.cmake:141 (include)


Error: Building package detours:x64-windows-release failed with: BUILD_FAILED
```

**Additional context**
The "detours" port unconditionally assumes that "VCPKG_BUILD_TYPE" has not been set and that, therefore, there will always be "-rel" and "-dbg" target directories.

### PR DESCRIPTION
**Pull request by PavelCurtis**
If the target triplet sets VCPKG_BUILD_TYPE, we can't assume that both '-rel' and '-dbg' build trees exist.

**Describe the pull request**

- #### What does your PR fix?  
  Fixes #20775

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  All triplets, including custom ones that set VCPKG_BUILD_TYPE.  I haven't changed the CI baseline.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

### CODE REVIEW

**Review by JackBoosY — CHANGES_REQUESTED** [review]

**Review by JackBoosY — APPROVED** [review]

**Comment by helmesjo** [comment]
Was this ever tested for `debug`? For me, `set(VCPKG_BUILD_TYPE release)` works, `set(VCPKG_BUILD_TYPE debug)` doesn't. Using vcpkg `2022.01.01` and dependency `cpprestsdk>=2.10.18`.

**Comment by dg0yt** [comment]
Debug-only is generally not supported.

**Comment by helmesjo** [comment]
Ok. I should clarify one thing though: Leaving `VCPKG_BUILD_TYPE ` unset (so that it builds both debug & release) _works_. It's just debug alone that doesn't work.

**Comment by PavelCurtis** [comment]
Interesting.  I did, indeed, test debug-only.  What error do you get?

Thanks,
        Pavel

**Pull request merged**
