### PR TITLE
[mathgl] missing internal dep

### PR DESCRIPTION
**Pull request by autoantwort**
Fixes
```
CMake Error at CMakeLists.txt:605 (message):
  You have to enable ZLib if you plan to use PNG export.

```

### CODE REVIEW

**Comment by jimwang118** [comment]
There is a problem with the usage of this port. Follow the usage prompt to test the compiled library and the following problems occur:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E1696	cannot open source file "mgl2/dllexport.h"	testmathgl.exe (testmathgl\Debug\testmathgl.exe) - x64-
Error	C1083	Cannot open include file: 'mgl2/dllexport.h': No such file or directory 	
```

**Comment by autoantwort** [comment]
> Follow the usage prompt to test the compiled library and the following problems occur:

Was this caused by this PR or is this an existing problem?

**Comment by jimwang118** [comment]
> > Follow the usage prompt to test the compiled library and the following problems occur:
> 
> Was this caused by this PR or is this an existing problem?

This should be a problem that has always existed. I tested the version before the upgrade and this problem also exists.

**Comment by BillyONeal** [comment]
> This should be a problem that has always existed. I tested the version before the upgrade and this problem also exists.

Then I don't think we should be requiring that @autoantwort fix it in order to fix this unrelated bug.

**Review by BillyONeal — DISMISSED** [review]

**Comment by jimwang118** [comment]
You can make a patch that modifies the `src/CMakeLists.txt` file. Add the following two lines to use it normally.
```
target_include_directories(mgl PUBLIC $<INSTALL_INTERFACE:include>)
target_include_directories(mgl-static PUBLIC $<INSTALL_INTERFACE:include>)
```

**Comment by BillyONeal** [comment]
> You can make a patch that modifies the `src/CMakeLists.txt` file. Add the following two lines to use it normally.
> 
> ```
> target_include_directories(mgl PUBLIC $<INSTALL_INTERFACE:include>)
> target_include_directories(mgl-static PUBLIC $<INSTALL_INTERFACE:include>)
> ```

I'm not sure I understand. Are you saying this fixes the preexisting usage problem? Do you already have that change in a branch somewhere?

I'm happy to smash a spot fix like that into the same PR if @autoantwort is willing but I don't want to block them over it.

**Comment by jimwang118** [comment]
> > You can make a patch that modifies the `src/CMakeLists.txt` file. Add the following two lines to use it normally.
> > ```
> > target_include_directories(mgl PUBLIC $<INSTALL_INTERFACE:include>)
> > target_include_directories(mgl-static PUBLIC $<INSTALL_INTERFACE:include>)
> > ```
> 
> I'm not sure I understand. Are you saying this fixes the preexisting usage problem? Do you already have that change in a branch somewhere?
> 
> I'm happy to smash a spot fix like that into the same PR if @autoantwort is willing but I don't want to block them over it.

I cloned the branch of this PR locally, and then used the above method to fix the usage issue and the local test can be used normally. If @autoantwort does not want to incorporate this usage issue in this PR, then I will submit a separate PR to fix the usage issue.

**Comment by dg0yt** [comment]
@jimwang118 I can tell you that this is broken for many of the unofficial configs added in vcpkg. You can find suspects with git grep.

**Pull request merged**
