### PR TITLE
Added globjects

### PR DESCRIPTION
**Pull request by mattiascibien**
This pull request adds support for the globjects library by cginternals. https://github.com/cginternals/globjects

Both dynamic and static libraries are built correctly

### CODE REVIEW

**Comment by barcharcraz** [comment]
Gliding required some screwing around to get everything working. Awesome port btw

**Comment by mattiascibien** [comment]
I got almost everything working now but I still do not get why it copied the wrong del. In the cmake file there are no references to glbinding at all

**Comment by mattiascibien** [comment]
Forget what I said about not copying the right DLL. Seems fine now that I have actually used a class from globjects. Sorry but I am a bit new to the whole autolinking thing.

**Comment by mattiascibien** [comment]
@Madras signed the CLA.

**Comment by mattiascibien** [comment]
Closing in favour #362

**Pull request closed without merging**
