### PR TITLE
New port: g2o

### PR DESCRIPTION
**Pull request by jasjuang**
Good graph optimization library

### CODE REVIEW

**Comment by atkawa7** [comment]
@jasjuang Could you take care of 
https://github.com/RainerKuemmerle/g2o/blob/master/g2o/types/data/g2o_types_data_api.h#L17-L25
https://github.com/RainerKuemmerle/g2o/blob/master/g2o/apps/g2o_simulator/g2o_simulator_api.h#L17-L25
Found them through
https://github.com/RainerKuemmerle/g2o/search?utf8=%E2%9C%93&q=dllexport&type=

**Comment by jasjuang** [comment]
@atkawa7 Could you guide me a bit on how to do it. I usually specify macro definitions for my own project with `target_compile_definitions`, but obviously I can't use it in the portfile. 

Another side note is I tested the compilation and it compiles. Wouldn't this supposed to cause compilation error? Maybe the export macros are handled internally already.

**Comment by atkawa7** [comment]
@jasjuang Something along these lines 
```
if(VCPKG_LIBRARY_LINKAGE STREQUAL dynamic)
    foreach(HEADER  list of headers )
        file(READ ${CURRENT_PACKAGES_DIR}/include/${HEADER} HEADER_CONTENTS)
        string(REPLACE "#ifdef G2O_SHARED_LIBS" "#if 1" HEADER_CONTENTS "${HEADER_CONTENTS}")
        file(WRITE ${CURRENT_PACKAGES_DIR}/include/${HEADER} "${HEADER_CONTENTS}")
    endforeach()
endif()
```
see
https://github.com/Microsoft/vcpkg/blob/master/ports/protobuf/portfile.cmake#L98-L106
https://github.com/Microsoft/vcpkg/blob/master/ports/zstd/portfile.cmake#L32-L38
https://github.com/Microsoft/vcpkg/blob/master/ports/libarchive/portfile.cmake#L42-L46
https://github.com/Microsoft/vcpkg/blob/master/ports/openal-soft/portfile.cmake#L54-L62
https://github.com/Microsoft/vcpkg/blob/master/ports/icu/portfile.cmake#L130-L134

**Comment by jasjuang** [comment]
@atkawa7 make the corrections as you suggested, please let me know if anything else has to be done

**Comment by atkawa7** [comment]
@jasjuang This seems okay to me.

**Comment by ras0219-msft** [comment]
Looks good to me as well!

I made a few changes while merging:
1. Qt5 is only used for the executables, which we were removing anyway. I disabled their builds and removed the Qt5 dependency.
2. Prefer ninja for faster builds
3. Use `file(GLOB_RECURSE)` to avoid listing out every header file (which is bound to become out of date in the future).

**Pull request merged**
