### PR TITLE
[boost] Support non-Windows build.

### LINKED ISSUE #4166: Problem with boost-regex[icu]
Hello,

I'm new with vcpkg. When I try to install boost-regex[icu], I get these errors : 

```
$ ~/vcpkg/vcpkg install boost-regex[icu]
...
Starting package 59/119: boost-regex:x64-linux
Removing package boost-regex:x64-linux...
Removing package boost-regex:x64-linux... done
Purging package boost-regex:x64-linux...
Purging package boost-regex:x64-linux... done
Elapsed time for package boost-regex:x64-linux: 4.416 ms
Starting package 60/119: icu:x64-linux
Building package icu[core]:x64-linux...
-- Using cached /home/jm/vcpkg/downloads/icu4c-61_1-src.tgz
-- Applying patch /home/jm/vcpkg/ports/icu/disable-escapestr-tool.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Configuring x64-linux-rel
-- Configuring x64-linux-rel done
-- Configuring x64-linux-dbg
-- Configuring x64-linux-dbg done
-- Package x64-linux-rel
-- Package x64-linux-rel done
-- Package x64-linux-dbg
-- Package x64-linux-dbg done
[1/2] cd /home/jm/vcpkg/buildtrees/boost-regex/src/ost-1.68.0-e671fb14f8/build && /home/jm/vcpkg/installed/x64-linux/tools/boost-build/b2 --user-config=/home/jm/vcpkg/buildtrees/boost-regex/x64-linux-dbg/user-
config.jam --stagedir=/home/jm/vcpkg/buildtrees/boost-regex/x64-linux-dbg/stage --build-dir=/home/jm/vcpkg/buildtrees/boost-regex/x64-linux-dbg runtime-link=static link=static address-model=64 target-os=linux
toolset=gcc -sZLIB_BINARY=z -sZLIB_LIBPATH="/home/jm/vcpkg/installed/x64-linux/debug/lib/libz.a" -sBZIP2_BINARY=bz2d -sBZIP2_LIBPATH="/home/jm/vcpkg/installed/x64-linux/debug/lib/libbz2d.a" variant=debug --
layout=system --with-atomic --with-random --with-date_time --with-filesystem --with-system --with-thread --with-chrono -sZLIB_INCLUDE="/home/jm/vcpkg/installed/x64-linux/include" -sBZIP2_INCLUDE="/home/jm/vcpkg/
installed/x64-linux/include" -sICU_PATH="/home/jm/vcpkg/installed/x64-linux" -j1 -sBOOST_ROOT=/home/jm/vcpkg/installed/x64-linux/tools/boost-build -sBOOST_BUILD_PATH=/home/jm/vcpkg/installed/x64-linux/tools/boost-
build --debug-configuration --ignore-site-config --hash -q architecture=x86 threading=multi threadapi=pthread debug-symbols=on
FAILED: CMakeFiles/boost
cd /home/jm/vcpkg/buildtrees/boost-regex/src/ost-1.68.0-e671fb14f8/build && /home/jm/vcpkg/installed/x64-linux/tools/boost-build/b2 --user-config=/home/jm/vcpkg/buildtrees/boost-regex/x64-linux-dbg/user-config.
jam --stagedir=/home/jm/vcpkg/buildtrees/boost-regex/x64-linux-dbg/stage --build-dir=/home/jm/vcpkg/buildtrees/boost-regex/x64-linux-dbg runtime-link=static link=static address-model=64 target-os=linux
toolset=gcc -sZLIB_BINARY=z -sZLIB_LIBPATH="/home/jm/vcpkg/installed/x64-linux/debug/lib/libz.a" -sBZIP2_BINARY=bz2d -sBZIP2_LIBPATH="/home/jm/vcpkg/installed/x64-linux/debug/lib/libbz2d.a" variant=debug --
layout=system --with-atomic --with-random --with-date_time --with-filesystem --with-system --with-thread --with-chrono -sZLIB_INCLUDE="/home/jm/vcpkg/installed/x64-linux/include" -sBZIP2_INCLUDE="/home/jm/vcpkg/
installed/x64-linux/include" -sICU_PATH="/home/jm/vcpkg/installed/x64-linux" -j1 -sBOOST_ROOT=/home/jm/vcpkg/installed/x64-linux/tools/boost-build -sBOOST_BUILD_PATH=/home/jm/vcpkg/installed/x64-linux/tools/boost-
build --debug-configuration --ignore-site-config --hash -q architecture=x86 threading=multi threadapi=pthread debug-symbols=on
notice: found boost-build.jam at /home/jm/vcpkg/installed/x64-linux/tools/boost-build/boost-build.jam
notice: loading Boost.Build from /home/jm/vcpkg/installed/x64-linux/tools/boost-build/src/kernel
notice: Site configuration files will be ignored due to the
notice: --ignore-site-config command-line option.
notice: Loading explicitly specified user configuration file:
    /home/jm/vcpkg/buildtrees/boost-regex/x64-linux-dbg/user-config.jam
notice: Searching '/home/jm/vcpkg/buildtrees/boost-regex/x64-linux-dbg' for user-config configuration file 'user-config.jam'.
notice: Loading user-config configuration file 'user-config.jam' from '/home/jm/vcpkg/buildtrees/boost-regex/x64-linux-dbg'.
notice: will use '/usr/bin/c++' for gcc, condition <toolset>gcc-5.4.1
notice: using gcc libraries :: <toolset>gcc-5.4.1 :: /usr/bin /usr/lib /usr/lib32 /usr/lib64
notice: using gcc archiver :: <toolset>gcc-5.4.1 :: /usr/bin/ar
notice: using gcc ranlib :: <toolset>gcc-5.4.1 :: /usr/bin/ranlib
warning: toolset gcc initialization: can not find tool windres
warning: initialized from /home/jm/vcpkg/buildtrees/boost-regex/x64-linux-dbg/user-config.jam:19
notice: using rc compiler :: <toolset>gcc-5.4.1 :: /usr/bin/as
error: Unable to find file or target named
error:     '/debug/lib/icudtd.lib'
error: referred to from project at
error:     ''

ninja: build stopped: subcommand failed.
```
I'm build on Ubuntu 16.04.

Do you why ?

Thanks,

Jean-Marc

### PR DESCRIPTION
**Pull request by icedream2linxi**
Fixed #4166.

### CODE REVIEW

**Comment by icedream2linxi** [comment]
I tested build boost with following triplet:

- x86-windows
- x86-windows-static
- x64-windows
- x64-windows-static
- x64-linux
- x64-osx

Looks good.

**Comment by OlafvdSpek** [comment]
Don't recent gcc versions default to -std=c++14?

**Comment by icedream2linxi** [comment]
@OlafvdSpek 
Thanks for your advice, I have modified.

**Comment by MikeGitb** [comment]
Imho individual port files shouldn't set a custom c++ standard at all. Either provide an option to set the standard in the triplet file so that all libraries are compiled with the same setting (which requires some cooperation from libraries that are not build with cmake) or just use the compiler default. One Idea might be to read `CMAKE_CXX_STANDARD` and if set translate it into a corresponding b2 flag.

Anything else can lead to annoying errors when the same header file ends up included in different  TUs that are compiled with different settings. (Related: https://github.com/Microsoft/vcpkg/issues/4004)

This might not be a big problem in this case, as most boost libraries are header only anyway, so the b2 setting here will not have any influence on them, but if it has an effect at all, it is imho more likely to cause trouble than help.

**Comment by LarryIII** [comment]
I am seeing new build failures on the following ports with this PR. Let me know if you need build log.
```
Processing arm-uwp                        357 vs 403
boost-contract                **regression**                Fail vs Pass
boost-math                    **regression**                Fail vs Pass

Processing x64-osx                        485 vs 577
boost-atomic                  **regression**                Fail vs Pass
boost-container               **regression**                Fail vs Pass
boost-exception               **regression**                Fail vs Pass
boost-regex                   **regression**                Fail vs Pass
boost-signals                 **regression**                Fail vs Pass
boost-stacktrace              **regression**                Fail vs Pass
boost-system                  **regression**                Fail vs Pass
Processing x64-uwp                        382 vs 431
boost-math                    **regression**                Fail vs Pass
Processing x64-windows                    771 vs 856
boost-math                    **regression**                Fail vs Pass
Processing x86-windows                    764 vs 841
boost-math                    **regression**                Fail vs Pass
```

**Comment by ras0219-msft** [comment]
This should have been fixed by c2e4fa7. If this is still unresolved, please open a new issue!

**Pull request closed without merging**
