### PR TITLE
[vcpkg] add support for FreeBSD

### PR DESCRIPTION
**Pull request by ivysnow**
Add files for use vcpkg in FreeBSD.

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thank you very much for the PR! You've done an awesome job plumbing everything through 👍!

However, from the non-technical side, we want to be very thoughtful about adding new "first-class" supported platforms (rejecting PRs if they don't build, etc); at the moment, we aren't ready to add FreeBSD to that list.

That "list" is communicated through docs and through the triplets in-box. Therefore, the only change needed is to not actually add the `triplets/x64-freebsd.cmake` file. Everything else we definitely want -- enabling the tool to build, fetching ninja/cmake, etc.

I've pushed that change to your branch and if that sounds good to you this looks good to merge once the CI completes.

**Comment by ras0219-msft** [comment]
Thanks for the PR!

**Comment by vladp** [comment]
The support for FreeBSD 12.0  (12.0-RELEASE-p3 FreeBSD 12.0-RELEASE-p3 GENERIC  amd64) seems to be broken.

CMake that's bundle is built with previous version of FreeBSD, so shared libs do not match.
Which is why I tried with -useSystemBinaries (cmake and ninja are installed),   but got errors:

> [v@fbsd11_a_hv1 ~/devel/other/vcpkg]$ ./bootstrap-vcpkg.sh -useSystemBinaries
> [: FreeBSD clang version 6: bad number
> -- The C compiler identification is Clang 6.0.1
> -- The CXX compiler identification is Clang 6.0.1
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Looking for pthread_create
> -- Looking for pthread_create - not found
> -- Check if compiler accepts -pthread
> -- Check if compiler accepts -pthread - yes
> -- Found Threads: TRUE  
> -- Performing Test USES_LIBSTDCXX
> -- Performing Test USES_LIBSTDCXX - Failed
> -- Performing Test USES_LIBCXX
> -- Performing Test USES_LIBCXX - Success
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /usr/home/v/devel/other/vcpkg/toolsrc/build.rel
> [0/2] Re-checking globbed directories...
> [0/65] Building CXX object CMakeFiles/vc....dir/src/vcpkg/base/cofffilereader.cp[0/65] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/base/downloads.cpp.[1/65] Building CXX object CMakeFiles/vc....dir/src/vcpkg/base/cofffilereader.cp[2/65] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/base/downloads.cpp.[4/65] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/base/machinetype.cp[6/65] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/base/stringview.cpp[8/65] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/base/files.cpp.o
> FAILED: CMakeFiles/vcpkglib.dir/src/vcpkg/base/files.cpp.o 
> /usr/bin/c++  -DDISABLE_METRICS=0 -I../include -O3 -DNDEBUG   -std=c++1z -pthread -MD -MT CMakeFiles/vcpkglib.dir/src/vcpkg/base/files.cpp.o -MF CMakeFiles/vcpkglib.dir/src/vcpkg/base/files.cpp.o.d -o CMakeFiles/vcpkglib.dir/src/vcpkg/base/files.cpp.o -c ../src/vcpkg/base/files.cpp
> ../src/vcpkg/base/files.cpp:124:25: error: variable has incomplete type 'struct stat'
>             struct stat s;
>                         ^
> ../src/vcpkg/base/files.cpp:124:20: note: forward declaration of 'stat'
>             struct stat s;
>                    ^
> ../src/vcpkg/base/files.cpp:133:26: error: use of undeclared identifier 'S_IFLNK'
>             if (!(mode & S_IFLNK))
>                          ^
> ../src/vcpkg/base/files.cpp:135:25: error: use of undeclared identifier 'S_IWUSR'
>                 mode |= S_IWUSR;
>                         ^
> 3 errors generated.
> [9/65] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/base/machinetype.cp[10/65] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/base/stringview.cp[13/65] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/base/hash.cpp.o
> ninja: build stopped: subcommand failed.
> [v@fbsd11_a_hv1 ~/devel/other/vcpkg]$ exit
> exit
>

**Comment by ubsan** [comment]
@vladp this is what we meant by "not first class support". I think I know how to fix it, though, and I'll ping you in a PR by tomorrow.

**Comment by vladp** [comment]
@ubsan  Totally understand the 2nd class status for fbsd at the moment.
Any help is greatly appreciated.

**Pull request merged**
