### PR TITLE
[xlsxio] new port

### PR DESCRIPTION
**Pull request by playgithub**
**Describe the pull request**

- #### What does your PR fix?  
port xlsxio

- #### Which triplets are supported/not supported? Have you updated the [CI baseline]
All
No

- #### Does your PR follow the [maintainer guide]
Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
Yes

### CODE REVIEW

**Comment by playgithub** [comment]
not clean, redo

**Comment by dg0yt** [comment]
You don't need to close PRs if you want to clean up. You can force-push a clean history. However I would recommend this only for PRs in draft state. 
Note that in the vcpkg repo, PRs are squashed when merged, and only the commit messages remain from intermediate steps.

**Comment by playgithub** [comment]
> You don't need to close PRs if you want to clean up. You can force-push a clean history. However I would recommend this only for PRs in draft state.
> Note that in the vcpkg repo, PRs are squashed when merged, and only the commit messages remain from intermediate steps.

The branch for PR is base on a wrong commit.
I think force-push should work as the branch name doesn't change, anyway I'll try later.

Thanks

**Comment by cenit** [comment]
force push let you do almost everything. You could even push a totally different repository branch.

but if you force push while PR is closed, you cannot reopen it anymore if I remember correctly github policies

**Pull request closed without merging**
