### PR TITLE
[libarchive] update to 3.5.1

### LINKED ISSUE #14985: [libarchive] update to 3.5.0
Library name: libarchive

New version number: 3.5.0

https://github.com/libarchive/libarchive/releases/tag/v3.5.0

### PR DESCRIPTION
**Pull request by JonLiu1993**
Fix #14985

Update libarchive to the latest version 3.5.1

All features are tested successfully in the following triplets:
- x86-windows
- x64-windows
- x64-windows-static

### CODE REVIEW

**Comment by Thieum** [comment]
@JonLiu1993 @NancyLi1013 I would be interested in this new version of libArchive. If I can do anything to help, I'm available =)

**Comment by JonLiu1993** [comment]
> @JonLiu1993 @NancyLi1013 I would be interested in this new version of libArchive. If I can do anything to help, I'm available =)

Hi @Thieum ,thanks for your contribution, you can submit pr to update libarchive, if the CI test is blocked, we will help you

**Comment by Thieum** [comment]
PR sent in #16845 . As it supersedes this one, it may be closed.

**Comment by JonLiu1993** [comment]
Duplicate of #16845

**Pull request closed without merging**
