### PR TITLE
[vcpkg-cmake-get-vars] Handle CMAKE_SYSROOT_COMPILE/CMAKE_SYSROOT_LINK

### PR DESCRIPTION
**Pull request by Osyotr**
https://cmake.org/cmake/help/latest/variable/CMAKE_SYSROOT_COMPILE.html
https://cmake.org/cmake/help/latest/variable/CMAKE_SYSROOT_LINK.html

CMake does the same:
https://gitlab.kitware.com/cmake/cmake/-/blob/e25f95c4cce29e20120928097e7a70e289611d1c/Source/cmLocalGenerator.cxx#L125-137

### CODE REVIEW

**Comment by jimwang118** [comment]
Add reviewed tag for further review by the vcpkg team.

**Comment by JavierMatosD** [comment]
Hi @Osyotr, thank you for the contribution. Can you explain what this change enables/fixes for you?

**Comment by Osyotr** [comment]
> Hi @Osyotr, thank you for the contribution. Can you explain what this change enables/fixes for you?

While cross-compiling python3 for QNX I've noticed that it didn't pickup system copy of ncurses even though I have an empty overlay for it.
The layout of the NDK for QNX looks roughly like this:
```
target/usr/include
target/arm/usr/lib
target/x86/usr/lib
```
Then I realized that I've only set `CMAKE_SYSROOT` in my toolchain and CMake can't see my libs.
Then I found out that it's possible to use separate sysroots for compiling and linking in CMake.
Then I've noticed that after replacing `CMAKE_SYSROOT` with `CMAKE_SYSROOT_COMPILE`/`LINK` the `--sysroot` flag disappeared from the command line.
At this point the problem was obvious for me.

Note that these variables originally were added for Android so theoretically it may fix some make-based ports there too, though I can't verify that.

**Comment by JavierMatosD** [comment]
Ok this LGTM but I have to wait until I can bring it up to the team since it touches the scripts directory.

**Review by JavierMatosD — APPROVED** [review]

**Pull request merged**
