### PR TITLE
[tinkerforge] add new port

### PR DESCRIPTION
**Pull request by Neumann-A**

### CODE REVIEW

**Comment by vicroms** [comment]
UWP errors are caused by calls to functions from `libloaderapi.h` which is not supported in that platform, e.g.: 

```
error LNK2019: unresolved external symbol GetModuleHandleA referenced in function gettimeofday 
```

So it makes sense to explicitly fail for UWP.

**Comment by Neumann-A** [comment]
@vicroms: What is the standarized way to early abort in the portfile or message those errors to the user? I couldn't find any detail in the docs about this (maybe that is also worth another issue?).

Maybe something like:
```
if(VCPKG_TARGET_IS_UWP)
      vcpkg_abort_unsupported()
endif()
```

with default error message like:
`"${PORT} currently does not support building on ${TARGET}"`

**Comment by vicroms** [comment]
Thanks for the PR!

**Comment by Neumann-A** [comment]
hmm wasn't this still PR still in Draft mode? I was just busy with fixing Qt. 
please add `advapi32.lib` and `Threads::Threads` to the target_link_libraries call as an interface library 
see: https://www.tinkerforge.com/en/doc/Software/API_Bindings_C.html#api-bindings-c

**Pull request merged**
