### PR TITLE
[vcpkg] Fix broken vcpkg_check_features

### LINKED ISSUE #9023: vcpkg does not really build VTK Qt
command: vcpkg install vtk[qt]:x64-windows 
env: Visual Studion 2017, build x64, Windows 10 x64, the latest vcpkg installed from scratch (13 Nov 2017 )

vcpkg installs vtk without errors, however, include, lib, bin folders do not have VTK Qt files
Really vcpkg has required sources in the port folder but does not build them (does not build VTK Qt folder)

### PR DESCRIPTION
**Pull request by Neumann-A**
closes #9023 (maybe more)

### CODE REVIEW

**Comment by cenit** [comment]
-D<var>=<value> was already exported to the parent scope, which would have been enough... in this way you are exporting them also not as cache variables... is it really a good practice? It might just be that vtk has a non-standard cmake snippet in its build script that breaks our usual check_features?

**Comment by Neumann-A** [comment]
The problem is that for easy ports `-D<var>=<value>` is enough but for more complex ports one want to check if `<var>` has been set in the portfile. One example: `tools` feature generally requires moving of binaries into the tools dir but requires knowing if `tools` is in the build feature. 
A similar usage is assumed in VTK:
```
vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    qt     VTK_WITH_QT
    mpi    VTK_Group_MPI
    python VTK_WITH_PYTHON
    openvr Module_vtkRenderingOpenVR
    atlmfc Module_vtkGUISupportMFC 
)
```
```
if(VTK_WITH_QT)
    list(APPEND ADDITIONAL_OPTIONS
        -DVTK_Group_Qt=ON
        -DVTK_QT_VERSION=5
        -DVTK_BUILD_QT_DESIGNER_PLUGIN=OFF
    )
endif()
```
Of course `VTK_WITH_QT` could be replaced by a `if(${FEATURES} MATCHES "qt")` but this seems undesirable.

> It might just be that vtk has a non-standard cmake snippet in its build script that breaks our usual check_features?

VTKs build script is simply more complex and requires setting more than one variable. We could change it to     `qt     VTK_Group_Qt` but it would still require and extra check vs. the `FEATURES` variable

**Review by cbezault — APPROVED** [review]

**Comment by vicroms** [comment]
Not exporting the macros was a design decision, there was discussion about this in the PR that added this function. 

Multiple variables can be set by the same feature, and you can use the `INVERTED_FEATURES` section to set something to `OFF`.

```
vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    qt     VTK_WITH_QT
    qt     VTK_Group_Qt
    mpi    VTK_Group_MPI
    python VTK_WITH_PYTHON
    openvr Module_vtkRenderingOpenVR
    atlmfc Module_vtkGUISupportMFC 
INVERTED_FEATURES
    qt     VTK_BUILD_QT_DESIGNER_PLUGIN
)

if("qt" IN_LIST FEATURES)
    list(APPEND ADDITIONAL_OPTIONS
        -DVTK_QT_VERSION=5
    )
endif()
```

**Review by JackBoosY — APPROVED** [review]

**Comment by Neumann-A** [comment]
> Not exporting the macros was a design decision, there was discussion about this in the PR that added this function.

I thought so much after reading the documentation for it. 

But why should I prefer:
```
vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    qt     VTK_Group_Qt (<-- maybe allowing a list here would make it better?)
    (...... some more Qt options ..... )
    mpi    VTK_Group_MPI
    python VTK_WITH_PYTHON   (<--- Note this is also wrong and would need more variables)
    openvr Module_vtkRenderingOpenVR
    atlmfc Module_vtkGUISupportMFC 
INVERTED_FEATURES
    qt     VTK_BUILD_QT_DESIGNER_PLUGIN (<-- this is also logically wrong. There should be a feature qtdesigner which sets this option)
)
if("qt" IN_LIST FEATURES)
    list(APPEND ADDITIONAL_OPTIONS
        -DVTK_QT_VERSION=5
    )
endif()
```
which logically separates the options and still needs the check
over
```
if("qt" IN_LIST FEATURES)
    list(APPEND ADDITIONAL_OPTIONS
        -DVTK_QT_VERSION=5
        -DVTK_BUILD_QT_DESIGNER_PLUGIN=OFF
        -DVTK_Group_Qt=ON
        (... some more modules with would make sense to activate with qt ...)
    )
endif()
(... same with python .... it also sets more values....)
```
which bundles the features better

In its current version `vcpkg_check_features` only makes sense for simple CMake based ports.

**Comment by Neumann-A** [comment]
And since I am updating VTK at the moment. Check features completely breaks with that due to:
```
CMake Error at CMake/vtkModule.cmake:331 (message):
  The `VTK_GROUP_ENABLE_Qt` variable must be one of `YES`, `WANT`,
  `DONT_WANT`, `NO`, or `DEFAULT`.  Found `ON`.
```

**Pull request closed without merging**
