### PR TITLE
 [fluidsynth] enable sound drivers on Mac/Linux build

### LINKED ISSUE #24638: [fluidsynth] enable sound drivers on Mac/Linux build
****
**Is your feature request related to a problem? Please describe.**
On Mac and Linux, no sound drivers are compiled in. ALSA and CoreAudio are explicitly disabled in `fluidsynth/portfile.cmake`. The Windows drivers are not disabled though.

**Proposed solution**
Sound drivers should be available. On Mac this means enabling CoreAudio which does not require any additional dependencies. 

On Linux this would mean enabling pulseaudio (which would be provided by the system package manager) and/or alsa (in vcpkg), so this could be an optional feature. But for feature parity with Windows I'd expect alsa to be enabled by default.

### PR DESCRIPTION
**Pull request by hmoffatt**
**Describe the pull request**

- #### What does your PR fix?
  Enables sound drivers on Mac and Linux, to match the behaviour on Windows. Fixes #24638.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  All supported, changes tested on Windows, Mac (x64-osx and arm64-osx) and Linux (x64-linux), No change to CI baseline.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

### CODE REVIEW

**Review by BillyONeal — DISMISSED** [review]
You removed the block on the feature but didn't actually hook the feature up. You need to add something in portfile.cmake that consumes the feature.

**Comment by hmoffatt** [comment]
@BillyONeal fluidsynth's own cmake project enables these features if it can find the relevant libraries. The port already depends on this behaviour to enable the Windows drivers (there are several features for that which are not explicitly set in portfile.cmake).

I can make it explicit if that would be better?

**Comment by BillyONeal** [comment]
If there is a feature in vcpkg.json, then that needs to actually control something; it can't rely on auto-detection. (Autodetection in general is bad because (1) it breaks binary caching, and (2) it causes the same install on different machines, or with different ports installed, to produce different output)

**Comment by BillyONeal** [comment]
See https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#when-defining-features-explicitly-control-dependencies

**Comment by hmoffatt** [comment]
There's no new feature in vcpkg.json though?

**Comment by BillyONeal** [comment]
> There's no new feature in vcpkg.json though?

Sorry, I am apparently blind and read that addition as a feature.

**Comment by hmoffatt** [comment]
Thanks for reviewing this.

**Comment by BillyONeal** [comment]
I looked at the sources and yeah... unfortunately the way it tries to be optional about everything is problematic. It breaks binary caching and will give different results depending on which other ports are installed first, which is not OK. For at least the backends you want to be on here, we need to patch upstream so that they are forced to be required.

I would really appreciate if you would do the same for the Windows selections, but since that is unrelated to the feature you're trying to enable here I don't think we should block your PR over that.

**Comment by BillyONeal** [comment]
You might not need patches for everything, I think you can get away with adding `-DALSA_SUPPORT=ON` for alsa, `-COREMIDI_FOUND=ON` for coremidi, etc. (as CMake options)

**Review by BillyONeal — CHANGES_REQUESTED** [review]
Waiting for force-on for the relevant features.

**Comment by hmoffatt** [comment]
@BillyONeal I have made changes as discussed

**Comment by BillyONeal** [comment]
Thanks for the feature and the plumbing!

**Pull request merged**
