### PR TITLE
[python3] upgrade to 3.9.2

### LINKED ISSUE #15369: [openimageio:x86-windows] build failure
**Host Environment**
- Windows 10 Pro. My machine is using the en-us locale.
- Visual Studio 2019 16.8.3
- Windows SDK 10.0.19041

**To Reproduce**
- Steps to reproduce the behavior:
`.\vcpkg install openimageio[pybind11]`

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:145 (message):
    Command failed: C:/Users/Kamil/Downloads/vcpkg-master/downloads/tools/cmake-3.19.2-windows/cmake-3.19.2-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v -j13
    Working Directory: C:/Users/Kamil/Downloads/vcpkg-master/buildtrees/openimageio/x86-windows-dbg
      C:\Users\Kamil\Downloads\vcpkg-master\buildtrees\openimageio\install-x86-windows-dbg-out.log
Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:27 (vcpkg_build_cmake)
  ports/openimageio/portfile.cmake:66 (vcpkg_install_cmake)
  scripts/ports.cmake:136 (include)
Error: Building package openimageio:x86-windows failed with: BUILD_FAILED

**Additional context**
- I ensured that I'm using the latest profiles with `.\vcpkg update`.

**Log file**
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5750890/install-x86-windows-dbg-out.log)

### PR DESCRIPTION
**Pull request by Hoikas**
Upgrades the Python 3 port to 3.9,2, including important security fixes and improved compatibility with macOS Big Sur's "Silicon".

- What does your PR fix?
Fixes #15369

- Which triplets are supported/not supported? Have you updated the CI baseline?
No change

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

### CODE REVIEW

**Comment by MVoz** [comment]
> this is not enough, see other ports and system in the cloud

**Comment by Hoikas** [comment]
CI failures appear to be unrelated to these changes -- eg download failures (librtmp) and disk space running out (g2o:x86-windows).

**Comment by MVoz** [comment]
> maybe it is worth deleting from this file, since it does not affect anything

https://github.com/microsoft/vcpkg/blob/a037d826492039db9d58af47a1e1248037d15f40/scripts/vcpkgTools.xml#L6

**Review by NancyLi1013 — APPROVED** [review]

**Comment by ras0219-msft** [comment]
Thanks for the update!

**Comment by ras0219-msft** [comment]
@MVoz That is used by the community-contributed export generator for `ifw`

**Pull request merged**
