### PR TITLE
[sdl2-mixer] Fix link mpg123 error

### LINKED ISSUE #22023: CMake can't link to libmpg123 when building with sdl2-mixer
I have 2 projects which are based on sdl2 which use sdl2-mixer and produce automatic builds for Windows. Since this issue #21776 this hasn't worked. A fix has been applied which makes sdl2-mixer build again with libmpg123 support, but my builds, which were working before, are still not working. I changed nothing.

Here is a link to the build: https://github.com/JoseTomasTocino/freegemas/runs/4520681620?check_suite_focus=true

I'm building on windows-latest in github actions. I'm getting the following error:

```
main.cpp
Generating Code...
LINK : fatal error LNK1104: cannot open file 'MPG123::libmpg123.lib' [D:\a\freegemas\freegemas\freegemas.vcxproj]
Error: Process completed with exit code 1.
```
This is my workflow:

```
  Windows:
    runs-on: windows-latest

    steps:
      - name: Install dependencies
        run: |
          vcpkg install --triplet x64-windows sdl2 sdl2-image[libjpeg-turbo] sdl2-ttf sdl2-mixer[libvorbis,mpg123] jsoncpp
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -D-DVCPKG_TARGET_TRIPLET=x64-windows -A x64 .
          cmake --build . --config Release
```

The relevant part of my ``CMakeLists.txt`` can be found here: https://github.com/JoseTomasTocino/freegemas/blob/ea416c4594b3e0a97e594e4968d000f70ff198c6/CMakeLists.txt#L121-L152

There is probably an error in one of the cmake files shipped with sdl2-mixer, but I did not extensively troubleshoot this.

### PR DESCRIPTION
**Pull request by LilyWangLL**
Fix link error: `LINK : fatal error LNK1104: cannot open file 'MPG123::libmpg123.lib'`
Fixes #22023

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Review by sharkwouter — APPROVED** [review]
I just tested this and it solves the problem on my machine. Thanks!

**Comment by BillyONeal** [comment]
Can you explain why we need to reinvent what goes on in mpg123 cmake configs here? (Depending on the situation this can be fine but the solution is very fragile since changes in upstream mpg123 can break it)

**Comment by JackBoosY** [comment]
@BillyONeal  
See https://github.com/microsoft/vcpkg/blob/9dea7a60d6158c2f4b6c5af55c7770e3952b03e3/ports/sdl2-mixer/CMakeLists.txt#L21
The `sdl2-mixer` contains the code for dynamically calling (`load_library`) the dynamic library, which leads to the need to pass the dynamic library name (not including the path) into the build command using a c++ macro.
However, in the previous version #21812, the dynamic library name was split and spliced by the static library name.

**Comment by BillyONeal** [comment]
> @BillyONeal See
> 
> https://github.com/microsoft/vcpkg/blob/9dea7a60d6158c2f4b6c5af55c7770e3952b03e3/ports/sdl2-mixer/CMakeLists.txt#L21
> 
> 
> The `sdl2-mixer` contains the code for dynamically calling (`load_library`) the dynamic library, which leads to the need to pass the dynamic library name (not including the path) into the build command using a c++ macro.
> However, in the previous version #21812, the dynamic library name was split and spliced by the static library name.

That's strange though because the error message mentioned above is a linker error, not a `LoadLibrary` failure.

**Comment by BillyONeal** [comment]
I see now that this is just a revert of the previous PR, OK.

**Pull request merged**
