### PR TITLE
[fmt] Update to 10.1.0

### LINKED ISSUE #33189: [fmt] update to 10.1.0
### Library name

fmt

### New version number

10.1.0

### Other information that may be useful (release notes, etc...)

https://github.com/fmtlib/fmt/releases/tag/10.1.0

### PR DESCRIPTION
**Pull request by chausner**
Updates fmt to 10.1.0
Fixes #33189

* [x]  Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)
* [x]  SHA512s are updated for each updated download
* [x]  The "supports" clause reflects platforms that may be fixed by this new version
* [x]  Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
* [x]  Any patches that are no longer applied are deleted from the port's directory.
* [x]  The version database is fixed by rerunning ./vcpkg x-add-version --all and committing the result.
* [x]  Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by chausner** [comment]
The CI failures in opencv4 and related ports seem unrelated to me:
> D:\buildtrees\opencv4\src\4.8.0-50001c828e.clean\modules\dnn\misc\tflite\schema_generated.h(12): error C2338: static_assert failed: 'Non-compatible flatbuffers version included'

**Comment by LilyWangLL** [comment]
> The CI failures in opencv4 and related ports seem unrelated to me:
> 
> > D:\buildtrees\opencv4\src\4.8.0-50001c828e.clean\modules\dnn\misc\tflite\schema_generated.h(12): error C2338: static_assert failed: 'Non-compatible flatbuffers version included'

Yeah, this is CI pipeline issue, it is not related with this PR.

**Comment by LilyWangLL** [comment]
Depends on #33141.

**Comment by xiaozhuai** [comment]
Close #33189

**Review by LilyWangLL — APPROVED** [review]

**Review by ras0219-msft — APPROVED** [review]

**Pull request merged**
