### PR TITLE
[python3] Some patches up for discussion 

### PR DESCRIPTION
**Pull request by Neumann-A**
- [?] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] ~~SHA512s are updated for each updated download~~
- [x] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [x] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [x] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [ ] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by BillyONeal** [comment]
The vcpkg team (@dan-shaw @vicroms @JavierMatosD @ras0219-msft and I) discussed this today.

@ras0219-msft points out that in a vcpkg context we can add the bin directory of the host triplet to the `%PATH%`, so the add_search_path is only relevant to external-to-vcpkg callers. That makes the goal here somewhat suspicious. "We are not yet opening the can of worms that means becoming an application deployment platform, and that includes Python."

But we acknowledge that we as a team have a big blind spot in our understanding of the python / plugins ... situation. We probably need a better understanding of what you're trying to do here before pceeding.

Robert also points out that we could solve the package ownership problem by creating ports that own just the copy from bin to the right plugins place. (That isn't to say that we **want** to do that, just pointing it out for the sake of discussion)

**Comment by Neumann-A** [comment]
> @ras0219-msft points out that in a vcpkg context we can add the bin directory of the host triplet to the %PATH%, 

the problem is that python doesn't care about PATH anymore.

**Comment by MonicaLiu0311** [comment]
@Neumann-A 
Do you want to continue this discussion? If not, I'll remove the `requires:discussion` tag and convert to `draft`.

**Comment by Neumann-A** [comment]
Yes this is still up for discussion

**Pull request closed without merging**
