### PR TITLE
[boost-python] Fix build failure: cannot find python includes

### PR DESCRIPTION
**Pull request by JackBoosY**
Although the python include path has been set, the python header file is still not found during the build process. I don't know if this change is reasonable.

### CODE REVIEW

**Comment by yurybura** [comment]
I think this issue can be fixed with #6639 without patching of Boost.Python source code.

**Comment by JackBoosY** [comment]
@yurybura If your PR can fix this issue, I will close this PR.

**Comment by JackBoosY** [comment]
``
../include/boost/python/detail/wrap_python.hpp:57:11: fatal error: 'python3.7/pyconfig.h' file not found
# include <python3.7/pyconfig.h>
          ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.

    "clang++" -x c++ -m64 -O0 -fno-inline -Wall -g  -DBOOST_ALL_NO_LIB=1 -DBOOST_PYTHON_SOURCE -DBOOST_PYTHON_STATIC_LIB -I"../include" -I"/Users/vagrant/azure_agent/_work/1/s/installed/x64-osx/include" -I"/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/include/python2.7" -c -o "/Volumes/Data/buildtrees/boost-python/x64-osx-dbg/boost/build/5d8ed05da44ad584e4b38ce8e777e812/list.o" "../src/list.cpp"
```

File `pyconfig.h` should exist in _/Users/vagrant/azure_agent/_work/1/s/installed/x64-osx/include/python3.7_, but it's not found.
@vicroms  Could you help me to check it?
Thanks.

**Comment by JackBoosY** [comment]
@vicroms The osx failure log of boost-python is empty, can you have a look?

Thanks.

**Comment by PhoebeHui** [comment]
@JackBoosY, the failure log for OSX have been uploaded, could you please resolve the OSX failures and conflicts?

**Comment by yurybura** [comment]
It should be fixed with #9317 without patching of Boost.Python source.

**Comment by JackBoosY** [comment]
Close this PR via #9317 fixed it.

**Pull request closed without merging**
