### PR TITLE
[zimpl] New port

### PR DESCRIPTION
**Pull request by dg0yt**

### CODE REVIEW

**Comment by Cheney-W** [comment]
Usage passed with following triplets:
x64-windows 
x64-windows-static

**Review by Cheney-W — DISMISSED** [review]

**Comment by Cheney-W** [comment]
Sorry, during the first test, it may have been due to caching issues, and I did not encounter this error. So I marked the reviewed tag.

**Comment by dg0yt** [comment]
Sorry, I realized the outstanding issues while away from keyboard.

**Comment by Cheney-W** [comment]
Usage passed with following triplets:
x64-windows 
x64-windows-static

**Review by Cheney-W — APPROVED** [review]

**Pull request merged**
