### PR TITLE
[curl] Update to 7.68.0

### PR DESCRIPTION
**Pull request by kevinlul**
**Describe the pull request**

- What does your PR fix?
Updates curl to the [latest release](https://github.com/curl/curl/releases/tag/curl-7_68_0)

- Which triplets are supported/not supported? Have you updated the CI baseline?
N/A

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

### CODE REVIEW

**Comment by PhoebeHui** [comment]
@kevinlul, thanks for the PR!

Have you test all features with x86-windows, x64-windows and linux?

**Comment by PhoebeHui** [comment]
Double checked features on local machine, all features tool, non-http, http2, ssl and ssh test pass on x86-windows, x64-windows and Linux.

**Review by PhoebeHui — APPROVED** [review]

**Comment by kevinlul** [comment]
Do I need to look into the macOS issues? It seems like every PR has been choking on those recently.

**Comment by c72578** [comment]
@kevinlul concerning osx see #9600

**Comment by dan-shaw** [comment]
@kevinlul The macOS failures are not relevant to your PR, so we are merging this.

**Pull request merged**
