### PR TITLE
[llvm] fix clang rescource dir

### LINKED ISSUE #34748: [llvm] clang has wrong internal paths
`"-internal-isystem" "E:\\all\\vcpkg\\vcpkg_installed\\x64-windows-release\\tools\\llvm\\../tools/llvm/lib/clang/17\\include"`
`"-resource-dir" "E:\\all\\vcpkg\\vcpkg_installed\\x64-windows-release\\tools\\llvm\\../tools/llvm/lib/clang/17"`
cc @yurybura 

output generated with `clang -### dummy.c`

### PR DESCRIPTION
**Pull request by Neumann-A**
closes #34748

### CODE REVIEW

**Comment by autoantwort** [comment]
`llvm[core]` now fails on macOS with 
```
...
-- Installing: /Users/leanderSchulten/git_projekte/vcpkg2/packages/llvm_arm64-osx/share/llvm/usage
CMake Error at ports/llvm/portfile.cmake:370 (file):
  file RENAME failed to rename

    /Users/leanderSchulten/git_projekte/vcpkg2/packages/llvm_arm64-osx/bin/lib

  to

    /Users/leanderSchulten/git_projekte/vcpkg2/packages/llvm_arm64-osx/tools/llvm/lib

  because: No such file or directory

Call Stack (most recent call first):
  scripts/ports.cmake:168 (include)

```

**Review by MonicaLiu0311 — DISMISSED** [review]

**Comment by JonLiu1993** [comment]
Tested in the local machine, Installation successful on osx:
````
./vcpkg install llvm:x64-osx
./vcpkg install ogre:x64-osx
````

**Comment by autoantwort** [comment]
@JonLiu1993 You have to install `llvm[core]`

**Comment by JonLiu1993** [comment]
> @JonLiu1993 You have to install `llvm[core]`

running

**Comment by JonLiu1993** [comment]
I get same error by `./vcpkg install  llvm[core]`
````
CMake Error at ports/llvm/portfile.cmake:370 (file):
  file RENAME failed to rename

    /Users/vcpkg/Jon/llvm/vcpkg/packages/llvm_x64-osx/bin/lib

  to

    /Users/vcpkg/Jon/llvm/vcpkg/packages/llvm_x64-osx/tools/llvm/lib

  because: No such file or directory

Call Stack (most recent call first):
  scripts/ports.cmake:168 (include)


````

**Review by JonLiu1993 — APPROVED** [review]

**Pull request merged**
