### PR TITLE
[angle] Fix uwp build

### PR DESCRIPTION
**Pull request by zabulus**
I've copy-pasted CMakeLists.txt, and fixed it for UWP.
I need help to merge it to a single file

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for the PR!

I'm a bit concerned about the patch file -- it looks like a functionality change and not a compatibility change. Could you speak a bit about why it's needed?

**Comment by zabulus** [comment]
> I'm a bit concerned about the patch file -- it looks like a functionality change and not a compatibility change. Could you speak a bit about why it's needed?

Sure. Looks like that WinRT implementation part of angle is quite outdated.
```samples``` that I've added fixes ```abstract class instantiation``` error because base class ```NativeWindow11``` added new parameter ```samples```. 

Second change https://github.com/Microsoft/vcpkg/pull/1370/files#diff-25a1ee3ddf9d692de9d5f6824f8a00b1R98 is implemented like in other implementation for win32 ```NativeWindow11Win32::createSwapChain```.

Though, second change could be reverted. First change is MUST for compilation.

**Comment by zabulus** [comment]
I can't get work angle samples with installed package, so I close PR till I fix the package.

**Comment by ras0219-msft** [comment]
Thanks, I'll look forward to it!

I'm going to temporarily reopen this PR so I can push my attempt at merging the two CMake files.

**Comment by ras0219-msft** [comment]
I merged the two CMake files and used the PR to pull them into master, however there's still a guard around UWP builds.

In your next PR once you've figured out the issue, could you remove the guard?

**Pull request merged**
