### PR TITLE
[libtorrent] minor portfile simplification and version bump

### PR DESCRIPTION
**Pull request by FranciscoPombal**
Simplify portfile according to https://github.com/arvidn/libtorrent/pull/4627 and https://github.com/arvidn/libtorrent/pull/4641.

Bump version to one that includes those changes.

### CODE REVIEW

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
Hi @FranciscoPombal 
Thanks for this PR.
Needs to test features now. Once finished, I will update the results.

**Comment by NancyLi1013** [comment]
All features (except for `python3`) have passed with the following triplets:
- x86-windows
- x64-windows-static

Note: feature `python3 `is broken now.

**Comment by FranciscoPombal** [comment]
@NancyLi1013 

> All features (except for `python`) have passed with the following triplets:
> 
>     * x86-windows
> 
>     * x64-windows-static
> 
> 
> Note: feature `python `is broken now.

If you mean that the python feature is broken on Windows, this has always been the case since its introduction. This PR does not change anything about that.

This PR only removes a variable definition that is now redundant thanks to fixes upstream. I did forget to actually remove the corresponding `OPTION` from the `vcpkg_configure_cmake` call. That is fixed now.

**Comment by NancyLi1013** [comment]
Thanks for your update.
Feature `python `is broken on Windows in current master, which is not introduced by this PR. I forgot to mention this info, just updated the test results for these features. I'm sorry for this.

**Comment by strega-nil** [comment]
Cools, LGTM! Thanks @FranciscoPombal

**Pull request merged**
