### PR TITLE
[vcpkg_find_acquire_program(NINJA).cmake] Update to 1.11.1

### PR DESCRIPTION
**Pull request by gerard-ryan-immersaview**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

I was getting some build discrepancies between my CI builds, which use this ninja, and my dev builds, which use the ninja that comes with Visual Studio which uses version `1.11.1`.

I might not have the time to progress this from the draft stage if many ports need fixes, but we'll see.

### CODE REVIEW

**Comment by dg0yt** [comment]
Implements https://github.com/microsoft/vcpkg/pull/34433#issuecomment-1762032317.

**Comment by gerard-ryan-immersaview** [comment]
It looks like the CI succeeded so I imagine this should be fine.

Note: I came across additional discrepancies between my CI and Dev so this change may not be necessary to fix errors, but here all the same.

**Comment by Adela0814** [comment]
Please fix the conflict and CI error.

**Comment by Adela0814** [comment]
Please get [failure logs here](https://dev.azure.com/vcpkg/public/_build/results?buildId=98370&view=artifacts&pathAsName=false&type=publishedArtifacts). Please ping me if you need any help.

**Comment by Adela0814** [comment]
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

**Comment by gerard-ryan-immersaview** [comment]
> Please get [failure logs here](https://dev.azure.com/vcpkg/public/_build/results?buildId=98370&view=artifacts&pathAsName=false&type=publishedArtifacts). Please ping me if you need any help.

<details>
<summary>

[x64_android](https://dev.azure.com/vcpkg/public/_build/results?buildId=98370&view=logs&j=f1a99d27-903c-5ce5-ab6b-a2a85be7b723&t=aaa276db-f8e2-58d4-78b7-1840ad464665&l=29161)
</summary>

```
Building tinyfiledialogs:x64-android@3.8.8#4...
-- Fetching https://git.code.sf.net/p/tinyfiledialogs/code master...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /usr/bin/git fetch https://git.code.sf.net/p/tinyfiledialogs/code master -n
    Working Directory: /vcpkg/downloads/git-tmp
    Error code: 128
    See logs for more information:
      /mnt/vcpkg-ci/b/tinyfiledialogs/git-fetch-x64-android-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_git.cmake:86 (vcpkg_execute_required_process)
  ports/tinyfiledialogs/portfile.cmake:3 (vcpkg_from_git)
  scripts/ports.cmake:170 (include)


error: building tinyfiledialogs:x64-android failed with: BUILD_FAILED
Elapsed time to handle tinyfiledialogs:x64-android: 174 ms
```
</details> 

<details>
<summary>

[arm64_android](https://dev.azure.com/vcpkg/public/_build/results?buildId=98370&view=logs&j=185c373b-2f55-539e-a6cb-ef2677cc0d97&t=bd42ae40-c428-56e6-fb3d-bb973ea0084d&l=28613)
</summary>

```
Building tinyfiledialogs:arm64-android@3.8.8#4...
-- Fetching https://git.code.sf.net/p/tinyfiledialogs/code master...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /usr/bin/git fetch https://git.code.sf.net/p/tinyfiledialogs/code master -n
    Working Directory: /vcpkg/downloads/git-tmp
    Error code: 128
    See logs for more information:
      /mnt/vcpkg-ci/b/tinyfiledialogs/git-fetch-arm64-android-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_git.cmake:86 (vcpkg_execute_required_process)
  ports/tinyfiledialogs/portfile.cmake:3 (vcpkg_from_git)
  scripts/ports.cmake:170 (include)


error: building tinyfiledialogs:arm64-android failed with: BUILD_FAILED
Elapsed time to handle tinyfiledialogs:arm64-android: 196 ms

```
</details> 

@Adela0814 These look like intermittent network failures to me, is there a way to re-run just those jobs?

**Comment by gerard-ryan-immersaview** [comment]
It looks like the failures are due to Windows build machine timeouts.

**Comment by dg0yt** [comment]
1.12.0 seems to be more attractive:
https://github.com/ninja-build/ninja/releases/v1.12.0
https://github.com/microsoft/vcpkg/issues/38494

**Comment by dg0yt** [comment]
> 1.12.0 seems to be more attractive: https://github.com/ninja-build/ninja/releases/v1.12.0 #38494

#38538

**Comment by BillyONeal** [comment]
Hi there, thanks for the update. I'm closing this in favor of the other PR which updates to 1.12. (Which I also have to resurrect :) )

**Pull request closed without merging**
