### PR TITLE
[libbacktrace] The port does not support windows builds

### PR DESCRIPTION
**Pull request by mkhon**
**Describe the pull request**

The port does not support windows builds

- #### What does your PR fix?  

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
all

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Review by JackBoosY — CHANGES_REQUESTED** [review]
Please also check _scripts/ci.baseline.txt_ and remove all windows triplet about this port.

**Comment by mkhon** [comment]
@JackBoosY done

**Review by JackBoosY — APPROVED** [review]

**Comment by ras0219-msft** [comment]
Thanks, this LGTM!

**Comment by Osyotr** [comment]
@ras0219-msft could you please explain what exactly does `"supports": "!windows"` mean here? Does it mean the build will fail if I use MinGW or Clang on Windows? 

UPD: wtf?
```
As of October 2020, libbacktrace supports ELF, PE/COFF, Mach-O, and XCOFF executables with DWARF debugging information. In other words, it supports GNU/Linux, *BSD, macOS, Windows, and AIX. 
```

**Comment by JackBoosY** [comment]
> @ras0219-msft could you please explain what exactly does `"supports": "!windows"` mean here? Does it mean the build will fail if I use MinGW or Clang on Windows?
> 
> UPD: wtf?
> 
> ```
> As of October 2020, libbacktrace supports ELF, PE/COFF, Mach-O, and XCOFF executables with DWARF debugging information.
> In other words, it supports GNU/Linux, *BSD, macOS, Windows, and AIX. 
> ```

Yes, see the title: doesn't support Windows builds.
We didn't try the mingW / clang build on Windows yet.

**Comment by ras0219-msft** [comment]
In our CI, all of the windows builds were failing:
```
libbacktrace:arm64-windows=fail
libbacktrace:arm-uwp=fail
libbacktrace:x64-uwp=fail
libbacktrace:x64-windows=fail
libbacktrace:x64-windows-static=fail
libbacktrace:x64-windows-static-md=fail
libbacktrace:x86-windows=fail
```

I'd love to reenable this if we receive a PR that fixes them!

**Comment by Osyotr** [comment]
So, in order to at least try to build with mingw I would have to create an overlay port with just this field removed? That sounds not very convenient.

**Comment by dg0yt** [comment]
> So, in order to at least try to build with mingw I would have to create an overlay port with just this field removed? That sounds not very convenient.

You can try `vcpkg install --allow-unsupported ...`. From the tool's help for the `install` command:

~~~
  --allow-unsupported             Instead of erroring on an unsupported port, continue with a
                                  warning.
~~~

**Pull request merged**
