### PR TITLE
[immer] Add new port

### LINKED ISSUE #6764: [New port request] immer
https://github.com/arximboldi/immer

### PR DESCRIPTION
**Pull request by myd7349**
Fix #6764 .

### CODE REVIEW

**Comment by myd7349** [comment]
https://github.com/arximboldi/immer/pull/85

**Comment by myd7349** [comment]
TODO: Remove the patch.

**Comment by cbezault** [comment]
@myd7349 does that TODO mean this PR isn't ready yet?

**Comment by myd7349** [comment]
Hi! @cbezault I have just removed the patch file which has already been merged in the upstream repo.

**Comment by ras0219-msft** [comment]
Thanks for the PR!

**Pull request merged**
