### PR TITLE
[ogre] Update port to Ogre version 1.10.8.

### PR DESCRIPTION
**Pull request by lazyhamster**
Updated Ogre port to support current version 1.10.
I've removed exiting patches because I think they are not relevant any more. But I could be wrong.

One think I'm not sure about:
CMake script from Ogre installs all .cmake files to {package_dir}/CMake directory. In port file I'm moving them to {package_dir}/share/ogre/CMake. Is it ok or does vcpkg expects flat structure and all .cmake files should be moved to {package_dir}/share/ogre?

### CODE REVIEW

**Comment by traversaro** [comment]
Hi @lazyhamster , thanks for the work on this. 
Some comments: 
>  I've removed exiting patches because I think they are not relevant any more. But I could be wrong.

The patch `0001-use-vcpkg-freeimage` seems to be still necessary, as the `-DFREEIMAGE_LIB` is still there: https://github.com/OGRECave/ogre/blob/v1.10.8/OgreMain/CMakeLists.txt#L278 . 
Patch `0003-use-flat-installation` seems indeed not necessary anymore, see https://github.com/OGRECave/ogre/blob/v1.10.8/CMake/Utils/OgreConfigTargets.cmake#L43 . 

> CMake script from Ogre installs all .cmake files to {package_dir}/CMake directory. In port file I'm moving them to {package_dir}/share/ogre/CMake. Is it ok or does vcpkg expects flat structure and all .cmake files should be moved to {package_dir}/share/ogre?

Patch `0002-ogre-cmake-dir-as-option` was used exactly to address this problem. 

In general, at a first glance I am afraid that the OGREConfig.cmake resulting from this PR will not be relocatable ( https://cmake.org/cmake/help/v3.3/manual/cmake-packages.7.html#creating-relocatable-packages ). This is a problem for vcpkg, see https://github.com/Microsoft/vcpkg/issues/1027 .

**Comment by lazyhamster** [comment]
> Patch 0002-ogre-cmake-dir-as-option was used exactly to address this problem.
IMO move code in port file is much simpler to maintain then a patch.

> The patch 0001-use-vcpkg-freeimage seems to be still necessary, as the -DFREEIMAGE_LIB is still there: 
I don't fully understand the purpose of this patch. Both static and dynamic OGRE versions build without any problem. I only see a potential issue if we try to build OGRE executables (tools, samples, etc) and they may link with invalid FreeImage lib file.

**Comment by traversaro** [comment]
>  IMO move code in port file is much simpler to maintain then a patch. 

If I remember correctly, the problem was that some files were generated containing relative path computed according to the installation directory, so changing those at CMake level had a different effect then just moving the file after installation, but I don't know if that is still the case (see https://github.com/Microsoft/vcpkg/issues/77 and https://github.com/Microsoft/vcpkg/blob/e4cab1750a110fcebf5d21c99d9db888f34c0656/scripts/cmake/vcpkg_fixup_cmake_targets.cmake#L2 for a similar problem). However, I don't know if this still applies. 

> I don't fully understand the purpose of this patch. Both static and dynamic OGRE versions build without any problem. I only see a potential issue if we try to build OGRE executables (tools, samples, etc) and they may link with invalid FreeImage lib file.

IIndeed, if this is the case the patch is not necessary. I think everything is working fine even when linking a dynamic freeimage due to this `#undef FREEIMAGE_LIB` added in https://github.com/Microsoft/vcpkg/blob/2da08053d615e1ffc6b7dc16f5ee1876229e0bee/ports/freeimage/FreeImageConfig-dynamic.h#L4 , so removing the patch seems ok.

**Comment by lazyhamster** [comment]
> If I remember correctly, the problem was that some files were generated containing relative path computed according to the installation directory, so changing those at CMake level had a different effect then just moving the file after installation
Ah. I thought those files just copied from source without any changes. Never actually checked what inside. May be patch is still needed after all. I have to make some tests.

**Comment by lazyhamster** [comment]
It appears that CMake install dir patch is still needed after all. But now 2 files need to be patched (2 sets of installed cmake files).
I've updated pull request with patch and also Ogre version is now 1.10.9.

**Comment by ras0219-msft** [comment]
Looks good, thanks for the PR!

**Comment by traversaro** [comment]
@ras0219-msft did you check if this is not resulting in non-relocatable CMake config file being installed?  

See https://github.com/Microsoft/vcpkg/pull/2092#issuecomment-341935163 for more details : 
> In general, at a first glance I am afraid that the OGREConfig.cmake resulting from this PR will not be relocatable ( https://cmake.org/cmake/help/v3.3/manual/cmake-packages.7.html#creating-relocatable-packages ). This is a problem for vcpkg, see #1027 .

**Comment by ras0219-msft** [comment]
No, you're right, I missed that. I'll look into it now.

**Comment by traversaro** [comment]
Thanks a lot.

**Comment by ras0219-msft** [comment]
Ok, I've attempted to fix the unrelocatable files, however it also looked completely unworkable for debug mode.

I tried to fix it with generator expressions, but I can't properly test it since I'm not an ogre user. I've pushed what I have to master; can someone try it out and let me know if it works for a more complete scenario?

**Pull request merged**
