### PR TITLE
[itk] Upgrade to 5.0.0

### PR DESCRIPTION
**Pull request by LilyWangL**
Related to #6618
1. Update to version 5.0.0
2. Fix old patches and build error

### CODE REVIEW

**Comment by cenit** [comment]
I also had to deal with itk in my megaPR :D
I also updated to 5.0 and ended up requiring another patch. I am wondering how you could do without...?

**Comment by wangli28** [comment]
Hi @cenit, can you provide your PR link? I didn't find it.

**Comment by cenit** [comment]
hi @wangli28 it's this one #6730 
Today I will fix a couple of regression on osx due to flacky builds and then it will be ready for discussions/merging/whatever

**Comment by wangli28** [comment]
@cenit Since this PR has been merged into master, can you merge my changes into your branch?
Thanks!

**Comment by cenit** [comment]
yes sure, I will merge master asap. Busy with other work atm

**Pull request merged**
