### PR TITLE
 [magnum-plugins] Fix basisimporter/basisimageconverter features

### PR DESCRIPTION
**Pull request by Squareys**
Hi all!

This PR fixes two features of the magnum-plugins port. The maintainer, @mosra, will give this a review quickly.

Thanks!

Jonathan.

### CODE REVIEW

**Review by mosra — APPROVED** [review]

**Comment by Squareys** [comment]
@PhoebeHui @JackBoosY @grdowns What the status? Looks like the rerun of the CI succeeded 🎉 

Thanks in advance.

**Comment by ras0219-msft** [comment]
Since the patch was very large (and exactly a commit from the repo), I've switched the portfile to download the diff from github instead of checking the full text in.

Assuming the CI passes, LGTM & thanks for the PR!

**Comment by mosra** [comment]
@ras0219-msft ping ... can we have this in? :)

**Comment by grdowns** [comment]
Merged! Thanks for the contributions, everyone

**Pull request merged**
