### PR TITLE
[Test] 2023.2.0 release of openvino

### PR DESCRIPTION
**Pull request by MonicaLiu0311**
This is a copy of #35125, which was affected by the old version's cache, so it wasn't running CI Pipelines, so I tried again with this new PR.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by MonicaLiu0311** [comment]
Testing is over and this PR is closed.

**Comment by dg0yt** [comment]
Why does this need to be reopened?

**Comment by MonicaLiu0311** [comment]
> Why does this need to be reopened?

I want to test if openvino still runs the old cache on this PR.

**Comment by dg0yt** [comment]
> > Why does this need to be reopened?
> 
> I want to test if openvino still runs the old cache on this PR.

Hm, is there anything I need to add to https://github.com/microsoft/vcpkg/pull/35125#issuecomment-1823237414? 
It did never "run the old cache" - if what you meant is that it would build an old revision.

You should simply ignore the output before the `Running CI for HEAD...` line because it is from a dry-run for collecting meta-data, not for the actual build.

And there will be no build of a port if an artifact already exists in the cache, for the new ABI hash.

**Pull request closed without merging**
