### PR TITLE
[at-spi2-atk, at-spi2-core] Add new port

### PR DESCRIPTION
**Pull request by talregev**
at-spi2-atk 2.38.0 port
at-spi2-core 2.44.1 port

@dg0yt  @JackBoosY 
Feel free to fix, edit, push and PR this PR. Thank you!. 

This PR needed dbus. Should we install on ci or add it to here?

### CODE REVIEW

**Comment by dg0yt** [comment]
Duplicates #24934?

**Comment by talregev** [comment]
> Duplicates #24934?

Yes. In case the PR will go too slow.

**Comment by dg0yt** [comment]
> > Duplicates #24934?
> 
> Yes. In case the PR will go too slow.

Oh no. If you double the work on the review side, you will be on my ignore list.

**Comment by talregev** [comment]
> > > Duplicates #24934?
> > 
> > Yes. In case the PR will go too slow.
> 
> Oh no. If you double the work on the review side, you will be on my ignore list.

Don't need to ignore me.
I will close this PR.

**Pull request closed without merging**
