### PR TITLE
[quill] Update to 1.4.1

### LINKED ISSUE #14181: [quill] update to 1.4.1
Library name: [quill](https://github.com/odygrd/quill)

New version number: 1.4.1

Other information that may be useful (release notes, etc...)
https://github.com/odygrd/quill/releases/tag/v1.4.1

### PR DESCRIPTION
**Pull request by cngzhnp**
Update quill to the latest release (1.4.1).

- Fixes #14181 
- Which triplets are supported/not supported? No
- Have you updated the CI baseline? No

### CODE REVIEW

**Comment by LilyWangL** [comment]
@cngzhnp Thanks for your PR. Now `quill` build failed on Windows with the following error:
```
-- Building x64-windows-rel
-- Installing: D:/packages/quill_x64-windows/share/quill/copyright
-- Performing post-build validation
Import libs were not present in D:\packages\quill_x64-windows\debug\lib
If this is intended, add the following line in the portfile:
    SET(VCPKG_POLICY_DLLS_WITHOUT_LIBS enabled)
Import libs were not present in D:\packages\quill_x64-windows\lib
If this is intended, add the following line in the portfile:
    SET(VCPKG_POLICY_DLLS_WITHOUT_LIBS enabled)
The following DLLs have no exports:
    D:/packages/quill_x64-windows/debug/bin/quill.dll
    D:/packages/quill_x64-windows/bin/quill.dll
DLLs without any exports are likely a bug in the build script.
If this is intended, add the following line in the portfile:
    SET(VCPKG_POLICY_DLLS_WITHOUT_EXPORTS enabled)
There should be no empty directories in D:\packages\quill_x64-windows
The following empty directories were found:
    D:/packages/quill_x64-windows/debug/lib
    D:/packages/quill_x64-windows/lib
If a directory should be populated but is not, this might indicate an error in the portfile.
If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:
    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/a/dir" "${CURRENT_PACKAGES_DIR}/some/other/dir")
```
Could you continue to fix this?

**Comment by cngzhnp** [comment]
@LilyWangL I will try to fix it, I checked just in my Linux machine, so I was not aware of that problem occurs in the Windows environment. If I cannot get any action until Wednesday, could you please continue to fix it?

**Comment by LilyWangL** [comment]
> @LilyWangL I will try to fix it, I checked just in my Linux machine, so I was not aware of that problem occurs in the Windows environment. If I cannot get any action until Wednesday, could you please continue to fix it?

Yes, I will do.

**Comment by LilyWangL** [comment]
Port `quill` has no `dllexport`, it only support static build.

**Review by LilyWangL — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks again 👍

**Pull request merged**
