### PR TITLE
[libtorch] Add new port

### PR DESCRIPTION
**Pull request by luncliff**
This PR adds a new port for [PyTorch](https://pytorch.org/).  
**Instead of performing local build, the new port extracts prebuilt binaries**.

* Sources:
    * https://pytorch.org/
    * https://github.com/pytorch/pytorch

### Changes
* **New**:  `libtorch 1.2.0` (C++ part for PyTorch)

### Related Issues
* Port Request: #5209 #6345

### Triplets

* x64-windows (CPU, GPU)
* x64-osx (CPU)
* x64-linux (CPU, GPU)

#### Unavailables

* `*-windows-static`
* `*-uwp`

#### CPU Only

For windows, there are only 1 available triplet. 
```
vcpkg install --triplet x64-windows libtorch
```
For Linux and OSX, simply install with …
```
vcpkg install libtorch
```

#### GPU (with CUDA)
Notice that CUDA support is only available for Windows/Linux
```
vcpkg install --triplet x64-windows libtorch[cuda]
vcpkg install --triplet x64-linux   libtorch[cuda]
```

### Usage

Targets of the `protobuf` and `cpuinfo` sould be specified.

```
This is custom installation of the LibTorch for vcpkg:

    find_package(Protobuf   CONFIG REQUIRED)
    find_package(cpuinfo    CONFIG REQUIRED)
    find_package(Torch      CONFIG REQUIRED)

    target_link_libraries(main
    PRIVATE
        # from vcpkg
        protobuf::libprotobuf cpuinfo::clog cpuinfo::cpuinfo

        # from pytorch prebuilt package
        c10 torch caffe2::mkl
    )

```

### CODE REVIEW

**Comment by cbezault** [comment]
In general we don't delete ports. If caffe users should really really really be using this port we should turn caffe into a stub port which prints a deprecation message and redirects the user to this port by having a dependency on this one.

**Comment by luncliff** [comment]
@cbezault Oh, I never thought about the point. Will recover the port soon.

**Comment by luncliff** [comment]
Just fixed removal of `caffe2`.

**Comment by cenit** [comment]
@luncliff I also propose to leave caffe as an empty port redirecting to this one. Otherwise we would have to check for the reciprocal installation since the two might be incompatible

**Comment by luncliff** [comment]
@cenit Sorry, but I can't get the word, 'empty'.  
Is that mean we have to keep `ports/caffe2/`? or the installation should modify something under `installed/{triplet}/{caffe2, libtorch}`?

**Comment by cenit** [comment]
something similar to what happened to ilmbase when it got merged to openexr. Now ilmbase is empty and depends on openexr, so when you install it you are "redirected".
https://github.com/microsoft/vcpkg/tree/master/ports/ilmbase

**Comment by luncliff** [comment]
@cbezault @cenit Understood. Doing so is indeed easy.
However, the new port(libtorch) is 1.2 and the current caffe2 port is 0.8. I can't sure about their compatibility issue. 

When I open the PR I thought they have to be replaced. But on second thought, **I have no confidence that this is the "really really really" case**. If possible, I would like to leave them as is.  
If I have to make the `caffe2` empty, then I will do within days. Just like the `ilmbase` did.

**Comment by cenit** [comment]
Since caffe2 just became libtorch from the c++ point of view (and also the python one...), I can't see the point in keeping both. Am I missing something?

**Comment by cenit** [comment]
for the "history" of caffe2 we also have the `x-history` command, so don't be afraid in removing the old portfile. There is no real reason to keep it "visible" in the master tree.

**Comment by luncliff** [comment]
@cenit Oh, wow. Learn a new feature!

**Comment by cenit** [comment]
Also, i’d create also an “empty” `caffè` port. That would be useful for newcomers and to close many issues that otherwise get opened from time to time

**Comment by luncliff** [comment]
I asked about the difference between `caffe2` and `caffe` to my coworker. And his answer was they have much difference unlike their name. So I think adding `caffe` port in this PR is not appropriate.

Related Issues: `caffe` 
 * #2848
 * #2570

**Comment by cenit** [comment]
Ok, fair enough

**Comment by cenit** [comment]
what are the errors on the windows platform? I tried to see also CI:14505 build but it looks empty. Might be that the force-push removed the references to the previous trials, but CI remembered them and declared port already failed. Can you please retrigger the build, just bumping the version inside CONTROL file for example, if you don't know what was wrong?
I am asking this because I'd like to see this PR merged soon and declaring failures as expected with a reason might be necessary

**Comment by Voskrese** [comment]
> install pre-built ? 

error

```
Installing package libtorch[core,cuda]:x64-windows...
The following files are already installed in E:/tools/vcpkg/installed/x64-windows and are in conflict with libtorch:x64-windows
Installed by cpuinfo:x64-windows
    debug/lib/clog.lib
    debug/lib/cpuinfo.lib
    include/clog.h
    include/cpuinfo.h
    lib/clog.lib
    lib/cpuinfo.lib
```

**Comment by luncliff** [comment]
With the message I recognized that the cpuinfo is merged. 
I will adjust the part in this weekend, **as soon as possible**.

My windows laptop is broken (not working) now so I have to borrow one.

**Comment by luncliff** [comment]
Just updated the files. Now it seems like 'x64-windows' is working well.

**Comment by cenit** [comment]
Just read the portfile and the initial message better now:

> Instead of performing local build, the new port extracts prebuilt binaries.

I am a little bit uncomfortable with it. Is it really necessary? Whenever possible, vcpkg builds library from sources...

**Comment by luncliff** [comment]
Sorry for late comment, @cenit. I couldn't focus on the issue well.   
For the downloading behavior, I agree that the install step should build whenever possible.

However, me and my teammates wanted to ship **the package** (libtorch 1.2.0) and some other **build results** in the vcpkg. For the purpose my decision was to place those prebuilt into the installed dir. 

If such portfile can't be adopted, I think this PR should be closed.  
In my opinion, someone can be motivated to enhance the file if there are an existing one. I wish this `libtorch` port to be the case.

**Comment by cenit** [comment]
I can understand your position. Which is reasonable. I am not sure the mods might agree with it or not. The only ore-built ports that you can find on vcpkg are ones that are not providing the source code, and so the built artifacts are the only things available... let’s see here their stance

**Comment by jasjuang** [comment]
Do we have any decision on this PR? It would be amazing to have libtorch working in vcpkg.

**Comment by luncliff** [comment]
we are waiting for the feedback. :)

**Comment by cbezault** [comment]
@luncliff if you can expand on why you think shipping a pre-built binary is a superior choice in this case I would be interested in hearing it.

**Comment by luncliff** [comment]
@cbezault I don't think using a prebuilt is a kind of superior choice. 
In my opinion, the pros and cons of doing so are like the following.

### Pros

* **Reduced build time**:  
   pytorch's build time [takes too much time (more than 50min)](https://ci.pytorch.org/jenkins/job/caffe2-master-debug/lastCompletedBuild/).
* **Bypassing dependencies**: 
   In vcpkg, [Intel MKL requires some manual installation](https://github.com/microsoft/vcpkg/blob/master/ports/intel-mkl/portfile.cmake). Which broked my team's CI builds. As a user, I wanted to avoid such ports if possible.

### Cons

* **Possible linking issues in the future**:  
  Especially `protobuf` is the module that made my team suffer from version matching. Port of `protobuf` and `cpuinfo` will make progress as time flows, but prebuilt can't handle those issues.

**Comment by cbezault** [comment]
It is unfortunate that building will take so long. It seems like the right thing for us to do is to provide a tarball of MKL like Conda does. (We could literally take from conda...)

**Comment by luncliff** [comment]
I can try but it's out of my cost... I will close this for now
so another person can try in the future.

**Comment by traversaro** [comment]
> You could also try to use the beta binary caching feature in your CI.

That is great, I was not aware there was a plan to use those binaries outside your CI system. I thought about using those binary by lurking the CI system logs, but then I desisted as I thought it was only for internal use. Do you have some entry point on how to do that? Thanks in advance.

**Comment by cbezault** [comment]
It's been a minute since I've had to turn it on but I think there's a --binary-caching flag and there's definitely some sort of environment variable you can set. Note there's still some details that are not added to the hash of the packages. Notably the type of compiler used is not hashed, ports which just just check for system dependencies such as cuda are not hashed correctly, and ports which have dependencies on ports in other triplets like proj4[database] are not hashed correctly.

**Comment by cbezault** [comment]
Note you will also need to point vcpkg/archives to somewhere all your ci machines can reach (like a network drive)

**Pull request closed without merging**
