### PR TITLE
[sqlite3] Fix tool installation with zlib

### PR DESCRIPTION
**Pull request by dg0yt**
Fixes missing zlib DLL. (Cf. #31040.)

This PR intentionally doesn't change the location of the tool at this point, to not break consumers.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by rcoup** [comment]
@dg0yt to fix #31040, presumably Proj still needs to change along these lines?

```patch
diff --git a/ports/proj/portfile.cmake b/ports/proj/portfile.cmake
index 2e280823b..a28bd0851 100644
--- a/ports/proj/portfile.cmake
+++ b/ports/proj/portfile.cmake
@@ -24,7 +24,7 @@ if("tools" IN_LIST FEATURES AND NOT "net" IN_LIST FEATURES)
     vcpkg_list(REMOVE_ITEM TOOL_NAMES projsync)
 endif()

-find_program(EXE_SQLITE3 NAMES "sqlite3" PATHS "${CURRENT_HOST_INSTALLED_DIR}/tools" NO_DEFAULT_PATH REQUIRED)
+find_program(EXE_SQLITE3 NAMES "sqlite3" PATHS "${CURRENT_HOST_INSTALLED_DIR}/bin" NO_DEFAULT_PATH REQUIRED)

 vcpkg_cmake_configure(
     SOURCE_PATH "${SOURCE_PATH}"
```

**Comment by dg0yt** [comment]
> @dg0yt to fix #31040, presumably Proj still needs to change along these lines?
> 
> ```diff
> diff --git a/ports/proj/portfile.cmake b/ports/proj/portfile.cmake
> index 2e280823b..a28bd0851 100644
> --- a/ports/proj/portfile.cmake
> +++ b/ports/proj/portfile.cmake
> @@ -24,7 +24,7 @@ if("tools" IN_LIST FEATURES AND NOT "net" IN_LIST FEATURES)
>      vcpkg_list(REMOVE_ITEM TOOL_NAMES projsync)
>  endif()
> 
> -find_program(EXE_SQLITE3 NAMES "sqlite3" PATHS "${CURRENT_HOST_INSTALLED_DIR}/tools" NO_DEFAULT_PATH REQUIRED)
> +find_program(EXE_SQLITE3 NAMES "sqlite3" PATHS "${CURRENT_HOST_INSTALLED_DIR}/bin" NO_DEFAULT_PATH REQUIRED)
> 
>  vcpkg_cmake_configure(
>      SOURCE_PATH "${SOURCE_PATH}"
> ```

No. `vcpkg_copy_tools` moves the program.

**Comment by dg0yt** [comment]
Hooray, this the first regular PR build getting CI builds for android! :heart: even if it would add regressions.

**Comment by BillyONeal** [comment]
Thanks for the fix!

**Pull request merged**
