### PR TITLE
[speex] Build every triplets with CMake and added CMake config files

### PR DESCRIPTION
**Pull request by Sharpe49**
Builds the package with CMake for every triplets
Added CMake config files

- #### What does your PR fix?
  None

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  all, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  I am still working on this PR

### CODE REVIEW

**Comment by dg0yt** [comment]
Did you consider using the original build system for all triplets instead? I know it is slower on Windows, but having the buildsystem maintenance in vcpkg (and no tests!) is a problem in some other ports already. `vcpkg_configure_make` has improved a lot since this port was added, and pkg-config support, too.

**Comment by Sharpe49** [comment]
I just tried it : it's completely broken with MSVC. I get build errors coming from everywhere.
And I am really not used to autoconf and automake, so I can't try and fix those files.

**Comment by dg0yt** [comment]
Looks like there was just a tiny showstopper: https://github.com/xiph/speex/pull/20

Full alternative PR: https://github.com/microsoft/vcpkg/pull/26502

**Comment by Sharpe49** [comment]
Ok, closing this pull request.
I would have prefered to use unofficial config files instead of pkg-config, but anyway...

**Pull request closed without merging**
