### PR TITLE
[gdal] fixed compilation issue with std::fabs

### PR DESCRIPTION
**Pull request by jepessen**
I had a compilation issue in ogr/ogrlinestring.cpp because std::fabs was not defined. I've added <cmath> include file.

I'm using Windows 10 Professional, and build with Visual Studio 2017 and 2019

### CODE REVIEW

**Comment by jumpinjackie** [comment]
You should probably upstream this fix to https://github.com/OSGeo/gdal as well

**Comment by jepessen** [comment]
I've created a pull request also in gdal repository.

**Comment by NancyLi1013** [comment]
Hi @jepessen, thanks for your PR. Could you also bump the CONTROL version?

**Comment by jepessen** [comment]
It should be ok. Where can I find some guideline about bumping version numbers? I didn't find anything about it...

**Comment by jumpinjackie** [comment]
@jepessen You bump the number after the `-` to signal changes to the port. Pretty much any PR for ports that does not update to a new release version would require bumping the port version number.

Source: My observations from submitted PRs :)

**Comment by jepessen** [comment]
Ok thanks for the info. I'll take care of it in future merges.

**Comment by Rastaban** [comment]
@jepessen incrementing the control verson helps with the `vcpkg upgrade` command.  The policy is buried with the documentation for the CONTROL file in [control-files.md](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/control-files.md) and is admitadly very easy to miss.

**Pull request merged**
