### PR TITLE
[sdl2-mixer] Fix dynamic loading when building static library

### PR DESCRIPTION
**Pull request by JackBoosY**
1. Since sdl2 uses `LoadLibrary` /` dlopen` to open the feature library, we should always use dynamic suffixes to build.
2. Add dynamic load as a feature.

Related: 
https://github.com/microsoft/vcpkg/commit/df484b0e5a504aa341b767223b530325995fbffd#commitcomment-36414770 
#9333.

Note: all features test pass with following triplets:
- x86-windows
- x64-windows
- x64-linux

### CODE REVIEW

**Comment by JackBoosY** [comment]
@edo9300 @tannergooding @Vultraz @timautry @Vermeille Are these changes correct? Could you test it?

Thanks.

**Comment by timautry** [comment]
@JackBoosY @Vultraz @vermeille
I can only vouch for x64-windows, compiles/links and seems to run correctly with a few debug/release programs I've written. I don't use x86 nor the x64 static triplets, so I have not tested them, maybe some of the others have these triplets installed.
Thank you very much for all the hard work.

**Comment by kevinlul** [comment]
Would it be possible to add a feature to static link the sound backends instead of loading them dynamically?

**Comment by JackBoosY** [comment]
@kevinlul @timautry I've set dynamic loading as a feature, could you test it?

Thanks.

**Review by PhoebeHui — APPROVED** [review]

**Comment by kevinlul** [comment]
Both static loading and dynamic loading now work on Windows. Tested on x86-windows-static. I assume the `dll` files aren't automatically copied as part of MSBuild because they are compiled on x86-windows when using dynamic loading?

**Comment by JackBoosY** [comment]
@kevinlul I disabled dynamic loading when building static library. Could you re-test it?

Thanks.

**Comment by kevinlul** [comment]
Is that necessary? There might be a use case for mixer itself to be static linked but not the backends. If it's possible then there's no need to remove it.

**Comment by JackBoosY** [comment]
@kevinlul Sadly, vcpkg cannot determine the type of a certain port has been built. So here according to the inheritance relationship, by default all plugins are the same build type as sdl2-mixer (both dynamic or both static).

**Comment by Vultraz** [comment]
For some reason I'm having trouble building a dynamic `sdl2-mixer[libvorbis]` lib, either 32 or 64 bit. A static build works fine :(

```
[23/24] cmd.exe /C "cd . && C:\Users\exodi\Documents\vcpkg\downloads\tools\cmake-3.14.0-windows\cmake-3.14.0-win32-x86\bin\cmake.exe -E vs_link_dll --intdir=CMakeFiles\SDL2_mixer.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~3\2019\COMMUN~1\VC\Tools\MSVC\1424~1.283\bin\Hostx64\x64\link.exe  CMakeFiles\SDL2_mixer.dir\effect_position.c.obj CMakeFiles\SDL2_mixer.dir\effect_stereoreverse.c.obj CMakeFiles\SDL2_mixer.dir\effects_internal.c.obj CMakeFiles\SDL2_mixer.dir\load_aiff.c.obj CMakeFiles\SDL2_mixer.dir\load_voc.c.obj CMakeFiles\SDL2_mixer.dir\mixer.c.obj CMakeFiles\SDL2_mixer.dir\music.c.obj CMakeFiles\SDL2_mixer.dir\music_cmd.c.obj CMakeFiles\SDL2_mixer.dir\music_flac.c.obj CMakeFiles\SDL2_mixer.dir\music_fluidsynth.c.obj CMakeFiles\SDL2_mixer.dir\music_mad.c.obj CMakeFiles\SDL2_mixer.dir\music_mikmod.c.obj CMakeFiles\SDL2_mixer.dir\music_modplug.c.obj CMakeFiles\SDL2_mixer.dir\music_mpg123.c.obj CMakeFiles\SDL2_mixer.dir\music_ogg.c.obj CMakeFiles\SDL2_mixer.dir\music_opus.c.obj CMakeFiles\SDL2_mixer.dir\music_timidity.c.obj CMakeFiles\SDL2_mixer.dir\music_wav.c.obj CMakeFiles\SDL2_mixer.dir\version.rc.res CMakeFiles\SDL2_mixer.dir\music_nativemidi.c.obj CMakeFiles\SDL2_mixer.dir\native_midi\native_midi_common.c.obj CMakeFiles\SDL2_mixer.dir\native_midi\native_midi_win32.c.obj  /out:SDL2_mixer.dll /implib:SDL2_mixer.lib /pdb:SDL2_mixer.pdb /dll /version:0.0 /machine:x64 /debug /INCREMENTAL  C:\Users\exodi\Documents\vcpkg\installed\x64-windows\debug\lib\SDL2d.lib Winmm.lib user32.lib gdi32.lib winmm.lib imm32.lib ole32.lib oleaut32.lib version.lib uuid.lib advapi32.lib setupapi.lib shell32.lib dinput8.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib  && cd ."
FAILED: SDL2_mixer.dll SDL2_mixer.lib 
cmd.exe /C "cd . && C:\Users\exodi\Documents\vcpkg\downloads\tools\cmake-3.14.0-windows\cmake-3.14.0-win32-x86\bin\cmake.exe -E vs_link_dll --intdir=CMakeFiles\SDL2_mixer.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~3\2019\COMMUN~1\VC\Tools\MSVC\1424~1.283\bin\Hostx64\x64\link.exe  CMakeFiles\SDL2_mixer.dir\effect_position.c.obj CMakeFiles\SDL2_mixer.dir\effect_stereoreverse.c.obj CMakeFiles\SDL2_mixer.dir\effects_internal.c.obj CMakeFiles\SDL2_mixer.dir\load_aiff.c.obj CMakeFiles\SDL2_mixer.dir\load_voc.c.obj CMakeFiles\SDL2_mixer.dir\mixer.c.obj CMakeFiles\SDL2_mixer.dir\music.c.obj CMakeFiles\SDL2_mixer.dir\music_cmd.c.obj CMakeFiles\SDL2_mixer.dir\music_flac.c.obj CMakeFiles\SDL2_mixer.dir\music_fluidsynth.c.obj CMakeFiles\SDL2_mixer.dir\music_mad.c.obj CMakeFiles\SDL2_mixer.dir\music_mikmod.c.obj CMakeFiles\SDL2_mixer.dir\music_modplug.c.obj CMakeFiles\SDL2_mixer.dir\music_mpg123.c.obj CMakeFiles\SDL2_mixer.dir\music_ogg.c.obj CMakeFiles\SDL2_mixer.dir\music_opus.c.obj CMakeFiles\SDL2_mixer.dir\music_timidity.c.obj CMakeFiles\SDL2_mixer.dir\music_wav.c.obj CMakeFiles\SDL2_mixer.dir\version.rc.res CMakeFiles\SDL2_mixer.dir\music_nativemidi.c.obj CMakeFiles\SDL2_mixer.dir\native_midi\native_midi_common.c.obj CMakeFiles\SDL2_mixer.dir\native_midi\native_midi_win32.c.obj  /out:SDL2_mixer.dll /implib:SDL2_mixer.lib /pdb:SDL2_mixer.pdb /dll /version:0.0 /machine:x64 /debug /INCREMENTAL  C:\Users\exodi\Documents\vcpkg\installed\x64-windows\debug\lib\SDL2d.lib Winmm.lib user32.lib gdi32.lib winmm.lib imm32.lib ole32.lib oleaut32.lib version.lib uuid.lib advapi32.lib setupapi.lib shell32.lib dinput8.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib  && cd ."
LINK Pass 1: command "C:\PROGRA~2\MICROS~3\2019\COMMUN~1\VC\Tools\MSVC\1424~1.283\bin\Hostx64\x64\link.exe CMakeFiles\SDL2_mixer.dir\effect_position.c.obj CMakeFiles\SDL2_mixer.dir\effect_stereoreverse.c.obj CMakeFiles\SDL2_mixer.dir\effects_internal.c.obj CMakeFiles\SDL2_mixer.dir\load_aiff.c.obj CMakeFiles\SDL2_mixer.dir\load_voc.c.obj CMakeFiles\SDL2_mixer.dir\mixer.c.obj CMakeFiles\SDL2_mixer.dir\music.c.obj CMakeFiles\SDL2_mixer.dir\music_cmd.c.obj CMakeFiles\SDL2_mixer.dir\music_flac.c.obj CMakeFiles\SDL2_mixer.dir\music_fluidsynth.c.obj CMakeFiles\SDL2_mixer.dir\music_mad.c.obj CMakeFiles\SDL2_mixer.dir\music_mikmod.c.obj CMakeFiles\SDL2_mixer.dir\music_modplug.c.obj CMakeFiles\SDL2_mixer.dir\music_mpg123.c.obj CMakeFiles\SDL2_mixer.dir\music_ogg.c.obj CMakeFiles\SDL2_mixer.dir\music_opus.c.obj CMakeFiles\SDL2_mixer.dir\music_timidity.c.obj CMakeFiles\SDL2_mixer.dir\music_wav.c.obj CMakeFiles\SDL2_mixer.dir\version.rc.res CMakeFiles\SDL2_mixer.dir\music_nativemidi.c.obj CMakeFiles\SDL2_mixer.dir\native_midi\native_midi_common.c.obj CMakeFiles\SDL2_mixer.dir\native_midi\native_midi_win32.c.obj /out:SDL2_mixer.dll /implib:SDL2_mixer.lib /pdb:SDL2_mixer.pdb /dll /version:0.0 /machine:x64 /debug /INCREMENTAL C:\Users\exodi\Documents\vcpkg\installed\x64-windows\debug\lib\SDL2d.lib Winmm.lib user32.lib gdi32.lib winmm.lib imm32.lib ole32.lib oleaut32.lib version.lib uuid.lib advapi32.lib setupapi.lib shell32.lib dinput8.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\SDL2_mixer.dir/intermediate.manifest CMakeFiles\SDL2_mixer.dir/manifest.res" failed (exit code 1120) with the following output:
Microsoft (R) Incremental Linker Version 14.24.28315.0
Copyright (C) Microsoft Corporation.  All rights reserved.

   Creating library SDL2_mixer.lib and object SDL2_mixer.exp
music_ogg.c.obj : error LNK2019: unresolved external symbol ov_clear referenced in function OGG_Load
music_ogg.c.obj : error LNK2019: unresolved external symbol ov_open_callbacks referenced in function OGG_Load
music_ogg.c.obj : error LNK2019: unresolved external symbol ov_pcm_total referenced in function OGG_Load
music_ogg.c.obj : error LNK2019: unresolved external symbol ov_pcm_seek referenced in function OGG_Load
music_ogg.c.obj : error LNK2019: unresolved external symbol ov_time_seek referenced in function OGG_Load
music_ogg.c.obj : error LNK2019: unresolved external symbol ov_pcm_tell referenced in function OGG_Load
music_ogg.c.obj : error LNK2019: unresolved external symbol ov_info referenced in function OGG_Load
music_ogg.c.obj : error LNK2019: unresolved external symbol ov_comment referenced in function OGG_Load
music_ogg.c.obj : error LNK2019: unresolved external symbol ov_read referenced in function OGG_Load
SDL2_mixer.dll : fatal error LNK1120: 9 unresolved externals
ninja: build stopped: subcommand failed.
```

**Comment by JackBoosY** [comment]
@Vultraz Can you open a new issue?

Thanks.

**Comment by timautry** [comment]
@Vultraz  - did you try:
.\vcpkg.exe install sdl2-mixer[dynamic-load,libvorbis]:x64-windows ?
I had a similar issue #9828 during an upgrade run and was able to install all the package when adding the dynamic-load feature.

**Comment by Vultraz** [comment]
@timautry that worked! Thanks 😃

**Comment by timautry** [comment]
You are most welcome!

**Comment by timautry** [comment]
Yes. Thank you!!!

**Pull request merged**
