### PR TITLE
[drogon] Update to 1.8.4

### PR DESCRIPTION
**Pull request by an-tao**

### CODE REVIEW

**Comment by MonicaLiu0311** [comment]
```
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: D:/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j33
    Working Directory: D:/buildtrees/drogon/x64-windows-dbg
    See logs for more information:
      D:\buildtrees\drogon\install-x64-windows-dbg-out.log
```
Thanks for your PR. CI test failed, please get [failure logs here](https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/86951/artifacts?artifactName=failure%20logs%20for%20x64-windows&api-version=7.0&%24format=zip).

**Comment by an-tao** [comment]
> ```
> -- Building x64-windows-dbg
> CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
>     Command failed: D:/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j33
>     Working Directory: D:/buildtrees/drogon/x64-windows-dbg
>     See logs for more information:
>       D:\buildtrees\drogon\install-x64-windows-dbg-out.log
> ```
> 
> Thanks for your PR. CI test failed, please get [failure logs here](https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/86951/artifacts?artifactName=failure%20logs%20for%20x64-windows&api-version=7.0&%24format=zip).

Thanks so much for your feedback, I think this is caused by the version of trantor, we can try again after merging the trantor's PR.

**Comment by MonicaLiu0311** [comment]
All features are tested successfully in the following triplet:
x86-windows
x64-windows
x64-windows-static

**Review by MonicaLiu0311 — APPROVED** [review]

**Pull request merged**
