### PR TITLE
[poco] Fix the release libraries are linked to debug pcred.dll

### PR DESCRIPTION
**Pull request by tetsuh**
This merge fixies #6349 but adhoc way.

This is a modified version of PR #5994 to support non-windows platforms.

Note:  this find_pcre.patch will be breaked by POCO's upstream modification  https://github.com/pocoproject/poco/commit/bd98f5cedf298148a053bf2f7142847351f64fb9
So we will need to remake find_pcre.patch when bump up ports/poco/portfile.cmake.

Usually, this problem should be solved by POCO or PCRE itself by providing FindPCRE.cmake.
In the meantime, I would like to apply this patch to keep the correct POCO build on vcpkg.

Initially, #5543 considered to include #5994 but finally excluded. because it looks a special kind of butterfly between #304 and #5994.  I hope this fixes these butterfly issue too.

### CODE REVIEW

**Comment by cbezault** [comment]
I think this can be implemented in a vcpkg-wrapper. Take a look at `[scripts/buildsystems/vcpkg.cmake](https://github.com/microsoft/vcpkg/blob/277393703d9ec1af7e20d2f75483930833778b45/scripts/buildsystems/vcpkg.cmake#L217)`. We intercept all calls to find_package and replace it with a macro.

**Comment by tetsuh** [comment]
Thnx. I try vcpkg-wrapper.

**Comment by JackBoosY** [comment]
@tetsuh I think #7698 would be better.

**Comment by tetsuh** [comment]
@JackBoosY  Yes, #7698 is better way that use select_library_configurations ().

**Comment by tetsuh** [comment]
@cbezault I've tried putting ports/pcre/vcpkg-cmake-wrapper.cmake  and  I saw how it working to override find_package(pcre).  then, I thought that it would be better to put pcre-config.cmake because that would allow find_package(pcre) other than vcpkg.
Anyway, at the moment I couldn't reach a good solution.

**Pull request closed without merging**
