### PR TITLE
Fix breakpad HEADER_EXCLUDE_REGEX matching

### LINKED ISSUE #26117: [breakpad] header not installed
**Host Environment**
- OS: macOS
- Compiler: Apple clang version 13.1.6 (clang-1316.0.21.2.5)

**To Reproduce**
`./vcpkg install breakpad`

**Failure logs**
-Cut and paste the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

```
Installing 1/1 breakpad:arm64-osx...
Building breakpad[core]:arm64-osx...
warning: -- Using community triplet arm64-osx. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /Users/user/Projects/A/vcpkg/triplets/community/arm64-osx.cmake
-- Downloading https://github.com/google/breakpad/archive/9c4671f2e3a63c0f155d9b2511192d0b5fa7f760.tar.gz -> google-breakpad-9c4671f2e3a63c0f155d9b2511192d0b5fa7f760.tar.gz...
-- Extracting source /Users/user/Projects/A/vcpkg/downloads/google-breakpad-9c4671f2e3a63c0f155d9b2511192d0b5fa7f760.tar.gz
-- Applying patch fix-unique_ptr.patch
-- Applying patch fix-unordered_map.patch
-- Using source at /Users/user/Projects/A/vcpkg/buildtrees/breakpad/src/0b5fa7f760-4cf530ff2b.clean
-- Found external ninja('1.10.2').
-- Configuring arm64-osx-dbg
-- Configuring arm64-osx-rel
-- Building arm64-osx-dbg
-- Building arm64-osx-rel
-- Installing: /Users/user/Projects/A/vcpkg/packages/breakpad_arm64-osx/share/breakpad/copyright
-- Performing post-build validation
The folder /include is empty or not present. This indicates the library was not correctly installed.
Found 1 post-build check problem(s). To submit these ports to curated catalogs, please first correct the portfile:
    /Users/user/Projects/A/vcpkg/ports/breakpad/portfile.cmake
-- Performing post-build validation done
Stored binary cache: '/Users/user/.cache/vcpkg/archives/42/42a95bdfc8ea656374cc7e1fb267bbb93ac255c677f8a1ef8edc189e1f6baf3e.zip'
Elapsed time to handle breakpad:arm64-osx: 11.11 s

Total elapsed time: 13.02 s

breakpad provides CMake targets:
    # this is heuristically generated, and may not be correct
    find_package(unofficial-breakpad CONFIG REQUIRED)
    target_link_libraries(main PRIVATE unofficial::breakpad::libbreakpad unofficial::breakpad::libbreakpad_client)
```

The installation is successful but see the header errors:
```
The folder /include is empty or not present. This indicates the library was not correctly installed.
```

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.
`Projects` in the path is suspicious.

### PR DESCRIPTION
**Pull request by youknowone**
**Describe the pull request**

- #### What does your PR fix?
Fixes #26117 

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  <all / linux, windows, ...>, <Yes/No>

Not changed.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by youknowone** [comment]
This is fixing breakpad problem for the issue, but it doesn't look like the correct fix for the cause.
I think EXCLUDE_HEADER_REGEX should match only subpath under the buildtree, not the full path.

**Comment by JackBoosY** [comment]
> This is fixing breakpad problem for the issue, but it doesn't look like the correct fix for the cause. I think EXCLUDE_HEADER_REGEX should match only subpath under the buildtree, not the full path.

We have various solutions for this issue, for example, set an absolute path to a benchmark and calculate its relative path, and use the relative path to make a comparison.

**Comment by youknowone** [comment]
If this is invalid, I hope one of the proper fixes coming soon. This is a disaster for people who cannot change their working directory. (and `proj` can matches too widely)

**Comment by Adela0814** [comment]
Clean up invalid PR.

**Pull request closed without merging**
