### PR TITLE
[lief/mbedtls] Update to 0.12.1 and 3.1.0

### LINKED ISSUE #25703: [mbedtls] update to 3.2.1
Library name: mbedtls

New version number: 3.2.1

Other information that may be useful (release notes, etc...)
https://github.com/Mbed-TLS/mbedtls/releases
https://github.com/Mbed-TLS/mbedtls-docs/blob/main/security-advisories/advisories/mbedtls-security-advisory-2022-07.md

### PR DESCRIPTION
**Pull request by ekilmer**
## **DRAFT PR. DO NOT MERGE** This is mainly for testing to figure out what needs fixing for v0.12.0.

One big issue I see with vcpkg is the dependency on new MbedTLS v3 when there are other vcpkg ports that rely on v2 and are incompatible with v3, which was attempted in this now-closed PR #20860. It is my understanding that vcpkg _requires_ only a _single version_ of any project, so either we need to update all of the incompatible ports to use MbedTLS or LIEF needs to support mbedtls v2.

Relevant issues on other repos for updated MbedTLSv3:
* https://github.com/oatpp/oatpp-mbedtls/issues/10
* https://github.com/OpenVPN/openvpn3/issues/200
* [`libssh`](https://gitlab.com/libssh/libssh-mirror) - None

**Describe the pull request**

This PR uses external dependencies to build [LIEF](https://github.com/lief-project/LIEF) that is only possible in the latest release of LIEF.

Builds upon #21213.

- #### What does your PR fix?  
#12511 is the original issue requesting LIEF.

#21213 adds LIEF, but the version of LIEF in that PR does not allow selection of external dependencies.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  

Windows ARM has a compilation error:
```
Class.cpp.obj : error LNK2019: unresolved external symbol __popcnt referenced in function "public: unsigned int __cdecl LIEF::OAT::Class::method_offsets_index(unsigned int)const "
```

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  

I'm not sure how to deal with the `disable-frozen` feature and removal of the dependency.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
I am still working on this PR, but also yes.

### CODE REVIEW

**Comment by ekilmer** [comment]
Getting some link errors on Windows with mbedTLS. Will investigate later:

```
[more similar errors...]
LINK : warning LNK4217: symbol '_fwrite' defined in 'libucrt.lib(fwrite.obj)' is imported by 'mbedcrypto.lib(bignum.c.obj)' in function '_mbedtls_mpi_write_file'
LINK : warning LNK4217: symbol '_fwrite' defined in 'libucrt.lib(fwrite.obj)' is imported by 'mbedcrypto.lib(hmac_drbg.c.obj)' in function '_mbedtls_hmac_drbg_free'
LINK : warning LNK4217: symbol '___stdio_common_vsprintf' defined in 'libucrt.lib(output.obj)' is imported by 'mbedcrypto.lib(platform.c.obj)' in function '_vsnprintf'
LINK : warning LNK4217: symbol '__time64' defined in 'libucrt.lib(time.obj)' is imported by 'mbedx509.lib(x509.c.obj)' in function '_time'
LINK : warning LNK4217: symbol '_fseek' defined in 'libucrt.lib(fseek.obj)' is imported by 'mbedcrypto.lib(pkparse.c.obj)' in function '_mbedtls_pk_load_file'
LINK : warning LNK4217: symbol '_ftell' defined in 'libucrt.lib(ftell.obj)' is imported by 'mbedcrypto.lib(pkparse.c.obj)' in function '_mbedtls_pk_load_file'
mbedcrypto.lib(md.c.obj) : error LNK2019: unresolved external symbol __imp__ferror referenced in function _mbedtls_md_file
mbedcrypto.lib(hmac_drbg.c.obj) : error LNK2001: unresolved external symbol __imp__ferror
mbedcrypto.lib(platform_util.c.obj) : error LNK2019: unresolved external symbol __imp___gmtime64_s referenced in function _gmtime_s
mbedcrypto.lib(rsa.c.obj) : error LNK2019: unresolved external symbol __imp__rand referenced in function _myrand
mbedcrypto.lib(bignum.c.obj) : error LNK2019: unresolved external symbol __imp__fgets referenced in function _mbedtls_mpi_read_file
MSVCRTD.lib(chandler4gs.obj) : error LNK2019: unresolved external symbol __except_handler4_common referenced in function __except_handler4
LIEF.dll : fatal error LNK1120: 5 unresolved externals
ninja: build stopped: subcommand failed.
```

**Comment by ekilmer** [comment]
The CMake patches allow for the test project located at [`examples/cmake/find_package/CMakeLists.txt`](https://github.com/lief-project/LIEF/blob/b65e7cca03ec4cd91f1d7125e717d01635ea81ba/examples/cmake/find_package/CMakeLists.txt) to turn into something more idiomatic like the following

```cmake
cmake_minimum_required(VERSION 3.1)

project(CMakeLIEF)

# Find LIEF
find_package(LIEF REQUIRED)

# Add our executable
# ==================
add_executable(HelloLIEF main.cpp)

# C++11 minimum
set_property(TARGET HelloLIEF
             PROPERTY CXX_STANDARD           11
             PROPERTY CXX_STANDARD_REQUIRED  ON)

# Link the executable with LIEF
target_link_libraries(HelloLIEF PRIVATE LIEF::LIEF)
```

**Comment by ekilmer** [comment]
Failure on Windows arm has following error

```
Class.cpp.obj : error LNK2019: unresolved external symbol __popcnt referenced in function "public: unsigned int __cdecl LIEF::OAT::Class::method_offsets_index(unsigned int)const "
```

**Comment by LilyWangLL** [comment]
Thanks for your PR. Now `ixwebsocket` `openvpn3` `oatpp-mbedtls` `libssh` build failed on CI pipeline, they all depend on mbestls. Could you please continue to fix them? You can click **Details** to check their fail log.

**Comment by ekilmer** [comment]
> Thanks for your PR. Now `ixwebsocket` `openvpn3` `oatpp-mbedtls` `libssh` build failed on CI pipeline, they all depend on mbestls. Could you please continue to fix them? You can click **Details** to check their fail log.

Hi @LilyWangLL , I've been attempting to look at these with some fairly limited success.

The biggest issue is that the failing projects depend on mbedtls v2, but LIEF needs mbedtls v3---a major version bump. There are some easy fixes, like patching the `FindMbedtls.cmake` files in the projects to correctly find the new version's files, but there are much bigger fixes for actually supporting the changed API in v3. I will try to open issues on the respective project's pages.

Another big concern is: what happens if the project doesn't want to support Mbedtls v3? I see that ["Mbed TLS 2.28.0 is a long-time support branch. It will be supported with bug-fixes and security fixes until end of 2024."](https://github.com/ARMmbed/mbedtls/releases/tag/v2.28.0) So, I can very easily see a project that might be understaffed, or might not even see a reason to update, be unwilling to make the switch to the new major version. It's a bit of a conundrum with respect to vcpkg's policy on having only a single version of a package, especially when I have zero experience with MbedTLS, and I can't offer support for PRs to those projects.

What are your thoughts?

---------------------

Furthermore

> You can click **Details** to check their fail log.

I found the Azure Pipelines page, can read the stdout logs, but I can't seem to access the specific package/platform build error logs (like compiler or CMake configuration errors). This page does not let me click to download

Screen Shot 2022-02-14 at 11 39 10 AM


am I doing something wrong?

**Comment by LilyWangLL** [comment]
@ekilmer VCPKG doesn't support choose dependency's version now. If want make port depend on different version of dependency, The best way is report issue to upstream and suggest them support new version of dependency. You could download the log file as follwoing picture.
image

**Comment by ekilmer** [comment]
> VCPKG doesn't support choose dependency's version now. If want make port depend on different version of dependency, The best way is report issue to upstream and suggest them support new version of dependency.

Understood. I will try my best.

> You could download the log file as follwoing picture.

Ahhh! Thank you for pointing that out! I must be blind 🤦

**Comment by LilyWangLL** [comment]
Ping @ekilmer for response. Is work still being done for this PR?

**Comment by ekilmer** [comment]
@LilyWangLL 

> Is work still being done for this PR?

It would be ready to merge if the mbedtls issue(s) were resolved

> Could you resolve the conflicts?

Done

**Comment by LilyWangLL** [comment]
Closing this PR since it seems that no progress is being made. Please ping me to reopen if work is still being done.

**Pull request closed without merging**
