### PR TITLE
[boost-build] Fix wrong hash

### LINKED ISSUE #40033: [boost-build] Build error on x64-windows
Package: boost-build:x64-windows@1.85.0#1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.40.33812.0
-    vcpkg-tool version: 2024-07-10-d2dfc73769081bdd9b782d08d27794780b7a99b9
    vcpkg-scripts version: 821100d96 2024-07-20 (2 days ago)

**To Reproduce**

`vcpkg install boost-build`

**Failure logs**

```
-- Downloading https://github.com/boostorg/build/archive/boost-1.85.0.tar.gz -> boostorg-build-boost-1-61540a3b.85.0.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from P:\dev\vcpkg\vcpkg-bundle.json
[DEBUG] Failed to open: P:\dev\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
[DEBUG] Trying to hash P:\dev\vcpkg\downloads\boostorg-build-boost-1-61540a3b.85.0.tar.gz.135144.part
[DEBUG] P:\dev\vcpkg\downloads\boostorg-build-boost-1-61540a3b.85.0.tar.gz.135144.part has hash 332a00c39c1510ce8526e68fffe73afe9079c3e7cfb2d84471cfb9da484244cdb287b4a8d7b677ea716174aa4af5e53cfd3b6a5ebf161088b7f1296ea100a6ba
error: Missing boostorg-build-boost-1-61540a3b.85.0.tar.gz and downloads are blocked by x-block-origin.
error: File does not have the expected hash:
url: https://github.com/boostorg/build/archive/boost-1.85.0.tar.gz
File: P:\dev\vcpkg\downloads\boostorg-build-boost-1-61540a3b.85.0.tar.gz.135144.part
Expected hash: 61540a3b2b7b6167ed8286daed4b4fde515ae9e0de81d17ef688d7972a0a6325b15afbe4e9a73ec883a81d5b86998d612cadbdc79abaf1b087a74e4e6b7cc2b5
Actual hash: 332a00c39c1510ce8526e68fffe73afe9079c3e7cfb2d84471cfb9da484244cdb287b4a8d7b677ea716174aa4af5e53cfd3b6a5ebf161088b7f1296ea100a6ba
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(1030): 
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 7us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 1719us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 1.9 s (1878981us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.
      
      3. Your proxy's remote server is out of service.
      
      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.
      

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/boost-build/portfile.cmake:9 (vcpkg_from_github)
  scripts/ports.cmake:192 (include)



```

### PR DESCRIPTION
**Pull request by LilyWangLL**
Fixes #40033

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version.~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by dg0yt** [comment]
There is no wrong hash in the port. Please check #40033 for the real error message.

**Comment by dg0yt** [comment]
I see, the hash changed (again) :facepalm:

**Comment by Neumann-A** [comment]
Seems like we need to use commit refs for boost in the future if the tags are not stable

**Review by data-queue — APPROVED** [review]

**Pull request merged**
