### PR TITLE
[libbf] Add new port 

### PR DESCRIPTION
**Pull request by amiremohamadi**
Initial port for [Libbf](https://github.com/mavam/libbf) library.
This solves #5428

### CODE REVIEW

**Comment by vicroms** [comment]
Hi @amiremohamadi 

I've got the following error in OS X and Linux, it looks like the license file is not being copied to the installed destination (maybe check for upper- lower-case inconsistencies).

```
The software license must be available at ${CURRENT_PACKAGES_DIR}/share/libbf/copyright

    file(COPY ${CURRENT_BUILDTREES_DIR}/src/v1.0.0-5bf953e697/COPYING DESTINATION ${CURRENT_PACKAGES_DIR}/share/libbf)
    file(RENAME ${CURRENT_PACKAGES_DIR}/share/libbf/COPYING ${CURRENT_PACKAGES_DIR}/share/libbf/copyright)
Found 1 error(s). Please correct the portfile:
    /home/vcpkg/myagent/_work/2/s/ports/libbf/portfile.cmake
-- Performing post-build validation done
Error: Building package libbf:x64-linux failed with: POST_BUILD_CHECKS_FAILED
```

As for Windows builds, I see a different error:

```
CMake Error at CMakeLists.txt:66 (message):
  Your C++ compiler does not support C++11.
-- Configuring incomplete, errors occurred!
```

Which is very strange... I haven't checked the CMakeLists.txt shipped with the library but a patch may be required for it to work on Windows.

**Comment by amiremohamadi** [comment]
Thank you vicroms
I did a fool mistake (Misspelling) that lead to POST_BUILD_CHECKS_FAILED :)

**Comment by vicroms** [comment]
Nice, that fixes the OS X and Linux builds.

I checked the source of the C++11 not supported error.

It is in the `CMakeLists.txt` file, the message is **actually misleading, is not checking for C++11 conformance, is checking that the compiler is either GCC or Clang**. And that's the reason it doesn't build on Windows. 

Given that MSVC does support C++ 11, it would be good to [patch it and add MSVC to the list of supported compilers.](https://github.com/Microsoft/vcpkg/blob/master/docs/examples/patching.md)


```
if ("${CMAKE_CXX_COMPILER_ID}" MATCHES "GNU")
  execute_process(
    COMMAND ${CMAKE_CXX_COMPILER} -dumpversion OUTPUT_VARIABLE GCC_VERSION)
  if (NOT (GCC_VERSION VERSION_GREATER 4.7 OR GCC_VERSION VERSION_EQUAL 4.7))
    message(FATAL_ERROR "${PROJECT_NAME} requires g++ 4.7 or greater.")
  endif ()
elseif ("${CMAKE_CXX_COMPILER_ID}" MATCHES "Clang")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -stdlib=libc++")
else ()
  message(FATAL_ERROR "Your C++ compiler does not support C++11.")
endif ()
```

**Comment by amiremohamadi** [comment]
Again thank you for your help
After trying hard I found out that this library doesn't support msvc yet. (only GCC >= 4.7 or Clang >= 3.2)
So I added a check at the beginning of the portfile.

**Comment by vicroms** [comment]
Thanks for the PR!

**Pull request merged**
