### PR TITLE
[Regression][tbb,openblas] Add dynamic build fallback back

### PR DESCRIPTION
**Pull request by zhihaoy**
Revert parts of 050e71d0 which breaks end-users' builds.

### CODE REVIEW

**Comment by zhihaoy** [comment]
Regression, please resolve ASAP.

**Comment by cenit** [comment]
https://github.com/Microsoft/vcpkg/pull/5937#issuecomment-488960198

This was an intended effect.

**Comment by Neumann-A** [comment]
@zhihaoy. I can tell you with 99% certainty that this will not be reverted. The error msg also tells you what you should do with your triplet file to overwrite the behavior.

**Comment by zhihaoy** [comment]
> [#5937 (comment)](https://github.com/microsoft/vcpkg/pull/5937#issuecomment-488960198)
> 
> This was an intended effect.
> Also the libraries can _only_ be built with dynamic linking, the new snippet is there just to avoid problematic configuration. If you really want a static crt with dynamic linking (I suppose that’s your problem) you have to explicitly request it in your own triplet

I think you two did not get the use case.  There are some ports that must use dynamic linking even your project is static linking.  The change was approved in https://github.com/microsoft/vcpkg/pull/5430 , and I've explained the use case in that issue.  Requesting a different triplet doesn't help, because when your build is static, vcpkg doesn't look up ports installed as dll -- unless this ports is built as if it is static.

**Comment by Neumann-A** [comment]
@zhihaoy You should costumize your triplet and add the following to it:

if(PORT MATCHES "openblas")
    set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()
if(PORT MATCHES "tbb")
    set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()

(you can add those lines to your own x64-windows-static triplet if you want. )

but it seems like your are unable to read the docs ;)
https://vcpkg.readthedocs.io/en/latest/users/triplets/

**Comment by zhihaoy** [comment]
> @zhihaoy You should costumize your triplet and add the following to it:
> 
> ```
> if(PORT MATCHES "openblas")
>     set(VCPKG_LIBRARY_LINKAGE dynamic)
> endif()
> if(PORT MATCHES "tbb")
>     set(VCPKG_LIBRARY_LINKAGE dynamic)
> endif()
> ```
> 
> (you can add those lines to your own x64-windows-static triplet if you want. )
> 
> but it seems like your are unable to read the docs ;)
> https://vcpkg.readthedocs.io/en/latest/users/triplets/

I found this, so thanks, but the error message does not point to this docs.

**Pull request closed without merging**
