### PR TITLE
[vcpkg] Update tls12-download.exe to 2021-05-05 version

### LINKED ISSUE #17688: tls2-downlload.exe get error 0x00000057 behind http proxy
**Describe the bug**
scripts/bootstrap.ps1 failed, because tls2-downlload.exe get error 0x00000057 behind http proxy

**Environment**
- OS: windows 10 v10.0.19042.0
- shell: powershell 5.1.19041.906

**To Reproduce**
1. $Env:HTTP_PROXY=http://192.168.32.1:8080; $Env:HTTPS_PROXY=http://192.168.32.1:8080 # Setup http proxy
2. .\bootstrap-vcpkg.bat
2. See error

**Expected behavior**
Download vcpkg.exe successifully.

**Failure logs** 
image

**Additional context**
There is nothing wrong with my proxy. At my local branch, I modified the 'scripts/bootstrap.ps1' to replace tls2-download.exe with aria2c, which installed by scoop. Then, downloading successed.
image

### PR DESCRIPTION
**Pull request by PhoebeHui**
Fixes https://github.com/microsoft/vcpkg/issues/17688

Update tls12-download.exe to 2021-05-05 version.

Related https://github.com/microsoft/vcpkg/pull/17734

### CODE REVIEW

**Comment by PhoebeHui** [comment]
We would fix the baseline issue in PR https://github.com/microsoft/vcpkg/pull/17983

**Review by JackBoosY — APPROVED** [review]

**Comment by PhoebeHui** [comment]
@dan-shaw, could you help merge this change?

**Comment by ChanthMiao** [comment]
What is the status of this PR @PhoebeHui ?

**Comment by strega-nil-ms** [comment]
Thanks @PhoebeHui ! sorry for taking so long

**Pull request merged**
