### PR TITLE
[qt5] Update to 5.15.4

### PR DESCRIPTION
**Pull request by Osyotr**
Testing build on CI...

### CODE REVIEW

**Comment by Osyotr** [comment]
A little step-by-step tutorial on how to update qt5:

Modify `qt_port_hashes.cmake` and `qt_port_hashes_latest.cmake`:
Bump version
switch `QT_UPDATE_VERSION` to `ON`

Get most hashes:
`vcpkg install qt5[all] --triplet=x64-windows`

Temporary remove platform restrictions in `vcpkg.json` and get remaining hashes:
`vcpkg install qt5-doc qt5-androidextras qt5-x11extras qt5-macextras qt5-wayland --triplet=x64-windows`

`qt_new_hashes.cmake`:
Sort lines ascending (In Notepad++: Edit -> Line Operations -> Sort lines lexicographically ascending)
Adjust spacing
Replace hashes in `vcpkg_port_hashes.cmake` and `vcpkg_port_hashes_latest.cmake`

Modify `qt_port_hashes.cmake` and `qt_port_hashes_latest.cmake`:
switch `QT_UPDATE_VERSION` to `OFF`

Remove installed Qt5 libraries (either `vcpkg remove qt5 --triplet=x64-windows --recurse` or remove installed directory)
Verify that qt5-base builds:
`vcpkg install qt5-base[core] --triplet=x64-windows`

Revert changes in platform-dependent ports
Update version in `qt5` metaport
Commit results

`vcpkg x-add-version --all`
Amend last commit
Check number of modified files (should be 85 + number of additionally modified files)

Push and create PR.

**Comment by Neumann-A** [comment]
> Temporary remove platform restrictions in vcpkg.json and get remaining hashes:

use `--allow-unsupported`

> Bump version

might be misunderstood. Don't bump version in vcpkg.json

> vcpkg remove qt5

you mean `vcpkg remove qt5-base --recurse`

**Comment by Neumann-A** [comment]
You probably want to remove `qt_port_hashes_latest.cmake` and deprecate the latest feature. 
You can also add qt5 to the port list so that you don't have to manually update the version in that file.

**Review by JonLiu1993 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the update!

**Pull request merged**
