### PR TITLE
[termcolor] update to v2.1.0

### LINKED ISSUE #23287: [termcolor] update to NULL
Library name: termcolor

New version number: The author of the repository did not create a release and therefore there is no new version, but there is a very important thing in the commits

Other information that may be useful (release notes, etc...)
https://github.com/ikalnytskyi/termcolor

### PR DESCRIPTION
**Pull request by FrankXie05**
Fix #23287 
Update to the master commit
No features need to test.

### CODE REVIEW

**Comment by playday3008** [comment]
> Thanks for the PR! I've opened https://github.com/ikalnytskyi/termcolor/issues/69 on upstream to request a new version release. Let's give them a few days to respond, since we'd like to avoid publishing a commit other than the official `2.0.0` one masquerading as `2.0.0`.

Well, we give him two months, issue still untouched

**Comment by playday3008** [comment]
> Thanks for the PR! I've opened https://github.com/ikalnytskyi/termcolor/issues/69 on upstream to request a new version release. Let's give them a few days to respond, since we'd like to avoid publishing a commit other than the official `2.0.0` one masquerading as `2.0.0`.

Updated

**Comment by FrankXie05** [comment]
@playday3008 Thanks for the survey, I will update it soon. :)

**Review by Cheney-W — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the update, quotes, and modernization!

**Pull request merged**
