### PR TITLE
[fastgltf] Update to 0.5.0

### PR DESCRIPTION
**Pull request by spnda**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

Not sure what the "supports clause" is?

### CODE REVIEW

**Comment by spnda** [comment]
Can somebody please paste the output logs of the arm_neon_android runner? (`/mnt/vcpkg-ci/buildtrees/fastgltf/install-arm-neon-android-dbg-out.log`, ...)

**Comment by dg0yt** [comment]
> Can somebody please paste the output logs of the arm_neon_android runner? (`/mnt/vcpkg-ci/buildtrees/fastgltf/install-arm-neon-android-dbg-out.log`, ...). Not sure how or if I am even allowed to access those files.

You can access them, cf. https://github.com/microsoft/vcpkg/discussions/31357

**Comment by MonicaLiu0311** [comment]
The x64-linux test fails, please get [failure logs here](https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/89690/artifacts?artifactName=failure%20logs%20for%20x64-linux&api-version=7.0&%24format=zip).

**Comment by AppleJ01** [comment]
```
/mnt/vcpkg-ci/buildtrees/fastgltf/src/v0.5.0-d6e3eea75f.clean/src/base64.cpp: In function ‘void fastgltf::base64::avx2_decode_inplace(std::string_view, uint8_t*, std::size_t)’:
/mnt/vcpkg-ci/buildtrees/fastgltf/src/v0.5.0-d6e3eea75f.clean/src/base64.cpp:108:62: error: inlining failed in call to always_inline ‘auto avx2_lookup_pshufb_bitmask(__m256i)’: function body can be overwritten at link time
/mnt/vcpkg-ci/buildtrees/fastgltf/src/v0.5.0-d6e3eea75f.clean/src/base64.cpp:167:49: note: called from here
  167 |         auto values = avx2_lookup_pshufb_bitmask(in);
      |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
```

Make sure that the `AVX2` instruction set is supported and the optimization option for `AVX2` is enabled on `Linux`. 😕

**Comment by spnda** [comment]
> ```
> /mnt/vcpkg-ci/buildtrees/fastgltf/src/v0.5.0-d6e3eea75f.clean/src/base64.cpp: In function ‘void fastgltf::base64::avx2_decode_inplace(std::string_view, uint8_t*, std::size_t)’:
> /mnt/vcpkg-ci/buildtrees/fastgltf/src/v0.5.0-d6e3eea75f.clean/src/base64.cpp:108:62: error: inlining failed in call to always_inline ‘auto avx2_lookup_pshufb_bitmask(__m256i)’: function body can be overwritten at link time
> /mnt/vcpkg-ci/buildtrees/fastgltf/src/v0.5.0-d6e3eea75f.clean/src/base64.cpp:167:49: note: called from here
>   167 |         auto values = avx2_lookup_pshufb_bitmask(in);
>       |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
> ```
> 
> Make sure that the `AVX2` instruction set is supported and the optimization option for `AVX2` is enabled on `Linux`. 😕

Nothing you mentioned is relevant. I am merely missing some `inline` specifies. Also, that's the old debug output, which I've already fixed. The new one has the same issue, but I want to get the same version of GCC or Clang running locally so I can be sure I catch 100% of the bugs. I've got some other things to do today, so I'll do all of this tomorrow, but if anyone knows; what version of GCC or Clang is the Azure CI running?

**Comment by MonicaLiu0311** [comment]
> what version of GCC or Clang is the Azure CI running?

As follows:
```
C compiler for the host machine: /usr/bin/cc (gcc 9.4.0 "cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0")
C linker for the host machine: /usr/bin/cc ld.bfd 2.34
C++ compiler for the host machine: /usr/bin/c++ (gcc 9.4.0 "c++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0")
C++ linker for the host machine: /usr/bin/c++ ld.bfd 2.34
```

**Comment by spnda** [comment]
I think this run of CI should complete now. I'll reopen now.

**Comment by MonicaLiu0311** [comment]
> Not sure what the "supports clause" is?

See: [vcpkg-json.md#-supports](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/reference/vcpkg-json.md#-supports)

**Comment by spnda** [comment]
Ah right, thanks. This is good to go then from my side.

**Comment by MonicaLiu0311** [comment]
The usage test passed (header files found):
```
find_package(fastgltf CONFIG REQUIRED)
target_link_libraries(main PRIVATE fastgltf::fastgltf)
```

**Review by MonicaLiu0311 — APPROVED** [review]

**Pull request merged**
