### PR TITLE
Add option for WCHAR32 support in ImGUI

### PR DESCRIPTION
**Pull request by geiseri**
According to https://github.com/ocornut/imgui/issues/3247 32bit wchars are needed to support Google's newer icon fonts.  This enables that as an option.  Since it will change the exported API it is disabled by default

- Which triplets are supported/not supported? Have you updated the CI baseline?
I had only tested linux, but I do not think it is an issue on windows or mac.  

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
I am not sure I like modifying the configuration file inline.  I am wondering if supplying a custom one might be better.  By default the supplied one is all commented out, so maybe it makes sense to have a `imconfig.h.in`, and have cmake expand it replace the default once with these options.  The `.in` file approach might be better since there are some other interesting flags in there.

### CODE REVIEW

**Comment by JackBoosY** [comment]
Please wait for #13289 to fix the regressions.

**Review by JackBoosY — CHANGES_REQUESTED** [review]
Please bump the port version. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).

**Comment by geiseri** [comment]
Updated (correctly) ;)

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
