### PR TITLE
[libusb] Set host triplet for wasm32

### PR DESCRIPTION
**Pull request by dg0yt**
Fixes wasm32-emscripten build, https://github.com/microsoft/vcpkg/discussions/35289. 
But I cannot verify if it is usable.

### CODE REVIEW

**Review by LilyWangLL — DISMISSED** [review]

**Review by BillyONeal — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks!

**Comment by RReverser** [comment]
Ouch, just a bit late to the party. This will need a follow-up fix because for the libusb RC we changed the required triplet to be explicit `--host=wasm32-emscripten` not `--host=wasm32`.

**Comment by dg0yt** [comment]
Good to know. This can be handled with the port update.

**Comment by RReverser** [comment]
> This can be handled with the port update.

Yeah fair enough.

More generally, I'm actually not sure why this project needs a port when there is an official & tested https://github.com/libusb/libusb-cmake.

I assume vcpkg could import it instead?

**Comment by RReverser** [comment]
> More generally, I'm actually not sure why this project needs a port when there is an official & tested [libusb/libusb-cmake](https://github.com/libusb/libusb-cmake).

OTOH looks like that one needs a bit more work.

**Pull request merged**
