### PR TITLE
[opencv4] update to 4.8.0

### LINKED ISSUE #32463: [opencv4] update to 4.8.0
### Library name

OpenCV

### New version number

4.8.0

### Other information that may be useful (release notes, etc...)

Released on 2023-06-29. [Release note](https://github.com/opencv/opencv/wiki/ChangeLog#version480)

### PR DESCRIPTION
**Pull request by Cheney-W**
Fixes https://github.com/microsoft/vcpkg/issues/32463

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by Cheney-W** [comment]
arm64-windows failure:
```
D:\buildtrees\opencv4\src\4.8.0-ead832a67f.clean\modules\dnn\src\layers\cpu_kernels\conv_block.simd.hpp(455): error C2678: binary '+=': no operator found which takes a left-hand operand of type 'float32x4_t' (or there is no acceptable conversion)
```
@cenit Could you please provide some suggestions to fix this issue? Thank you!

**Comment by cenit** [comment]
i was working on the same update but got stuck in other urgent matters. I will finish the work before mid august, if ok for you

**Comment by Cheney-W** [comment]
OK, I will duplicate this PR when your PR is submitted. Thank you!

**Comment by BillyONeal** [comment]
> arm64-windows failure:
> 
> ```
> D:\buildtrees\opencv4\src\4.8.0-ead832a67f.clean\modules\dnn\src\layers\cpu_kernels\conv_block.simd.hpp(455): error C2678: binary '+=': no operator found which takes a left-hand operand of type 'float32x4_t' (or there is no acceptable conversion)
> ```
> 
> @cenit Could you please provide some suggestions to fix this issue? Thank you!

This was fixed by https://github.com/opencv/opencv/commit/e5e1a3bfdea96bebda2ad963bc8f6cf17930aef7 which I apply in my PR

**Comment by Cheney-W** [comment]
I haven't been keeping up with the upstream developments lately, so I'm glad to hear that the issue with arm64_windows has been resolved. 

Duplicate of https://github.com/microsoft/vcpkg/pull/33048.

**Pull request closed without merging**
