### PR TITLE
[vcpkg | vcpkg_copy_pdbs]: Support copying .pdb when using llvm/clang-mingw

### PR DESCRIPTION
**Pull request by past-due**
**Describe the pull request**

Clang-based mingw toolchains can support generating `.PDB` files (example: https://github.com/mstorsjo/llvm-mingw/blob/master/README.md#pdb-support )

However, the existing `vcpkg_copy_pdbs` function does *not* support this.

This PR makes two core changes / additions to `vcpkg_copy_pdbs`:
1. Always support trying `dumpbin /PDBPATH` when the host is Windows (even if using a mingw toolchain)
2. Support a backup path to find the `.pdb` files when cross-compiling with mingw (or if `dumpbin` fails or cannot be found, which may happen - even *on* Windows - depending on how PATHS are set up for use with the mingw toolchain).

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  windows / mingw, No updates needed

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

### CODE REVIEW

**Comment by Neumann-A** [comment]
Consider taking a look at:
https://github.com/microsoft/vcpkg/pull/25692/files#diff-8b5de3c96a4458bb5c63401b7278e36fb78f0f7aad949780353bec0b1f6e4c77

**Review by JonLiu1993 — APPROVED** [review]

**Comment by vicroms** [comment]
Hi @past-due 

We've been actively trying to remove our dependency on dumpbin by implementing the features we need directly in the vcpkg executable (see [this PR to remove dumpbin calls](https://github.com/microsoft/vcpkg-tool/pull/834) and the [changes to replace applocal.ps1](https://github.com/microsoft/vcpkg-tool/pull/814)). 

Would you be willing to investigate whether we can get the PDB path information using a method that would not require dumpbin? 

These seem like good starting points:
* [PE Format - Debug Directory](https://learn.microsoft.com/en-us/windows/win32/debug/pe-format#debug-directory-image-only)
* [.NET implementation](https://github.com/dotnet/dotnet/blob/7dd10c9edfdbd4c29672a5b4423e05d0fa48acc4/src/runtime/src/libraries/System.Reflection.Metadata/src/System/Reflection/PortableExecutable/PEReader.cs#L759) of [PEReader](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.portableexecutable.pereader.tryopenassociatedportablepdb?view=net-8.0)

**Comment by past-due** [comment]
@vicroms If you are already parsing the PE header, I believe:
- If you get the `IMAGE_OPTIONAL_HEADER`,
- use that to get the pointer to the `IMAGE_DEBUG_DIRECTORY ` (`DataDirectory[IMAGE_DIRECTORY_ENTRY_DEBUG]`?)
- then if `IMAGE_DEBUG_DIRECTORY.Type == IMAGE_DEBUG_TYPE_CODEVIEW`, cast `<base image address> + IMAGE_DEBUG_DIRECTORY.AddressOfRawData` to a CodeView debugging information struct*

Which I believe takes a form like (from various snippets around the web):
```
struct CodeViewDebuggingInfo
{
  DWORD Signature;
  BYTE Guid[16];
  DWORD Age;
  char PdbFileName[0]; // presumably this is null-terminated? Probably a good idea to check `IMAGE_DEBUG_DIRECTORY.SizeOfData`
};
```

(Completely untested and unverified, but hopefully that helps point in a useful direction.)

I still think there's probably merit to keeping the fallback that this PR adds (which is to just search for a matching .pdb file in the same directory) as well.

**Comment by JonLiu1993** [comment]
Closing this PR since it seems that no progress is being made. Please ping us to reopen if work is still being done.

**Pull request closed without merging**
