### PR TITLE
[leveldb] Fix build on linux

### PR DESCRIPTION
**Pull request by HungMingWu**
Fix build on linux

### CODE REVIEW

**Comment by edmBernard** [comment]
you need to add C++11 option in compiler flag. Currently, there is an error with std::atomic.
you can add these two line at the beginning of the file : 

```
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
```

**Comment by edmBernard** [comment]
For me it works perfect now

**Comment by HungMingWu** [comment]
Is it need to merge iinto master?

**Comment by alexkaratarakis** [comment]
Thanks! Sorry for the delay.

**Pull request merged**
