### PR TITLE
[ffmpeg] add openh264 support

### PR DESCRIPTION
**Pull request by mcmtroffaes**
- #### What does your PR fix?  
  Implements one of the features for ffmpeg requested at #9272.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  Locally tested x64-windows and x64-windows-static (including linking against the resulting ffmpeg library to ensure the FindFFMPEG script works as intended). No changes to CI baseline.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes.

### CODE REVIEW

**Comment by JackBoosY** [comment]
Depends on https://github.com/microsoft/vcpkg/pull/17528

cc @cenit for review this PR.

**Comment by talregev** [comment]
vote up

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
LGTM, just need to wait for #17528 merged. Thanks for your help @mcmtroffaes.

**Comment by cenit** [comment]
> Depends on https://github.com/microsoft/vcpkg/pull/17528
> 
> 
> 
> cc @cenit for review this PR.

ok also for me

**Review by cenit — APPROVED** [review]

**Comment by NancyLi1013** [comment]
Need to merge master to solve the conflicts @mcmtroffaes.

**Comment by mcmtroffaes** [comment]
Rebased on latest master.

**Comment by strega-nil-ms** [comment]
Thanks @mcmtroffaes :)

**Comment by mcmtroffaes** [comment]
Oh, great, many thanks for the quick merge!

**Pull request merged**
