### PR TITLE
[openssl-unix] use xcrun for iOS triplet build

### PR DESCRIPTION
**Pull request by luncliff**
### What does your PR fix?

* config for iOS simulator architecture
* use .dylib suffix for iOS shared is used

### Which triplets are supported/not supported? Have you updated the CI baseline?

Enhance support for: `arm64-ios`, `arm-ios`, `x86-ios`, `x64-ios`

#### [Build status of the fork](https://dev.azure.com/luncliff/personal/_build?definitionId=41)

Since current mainstream CI pipeline doesn't check `ios` triplets, I created some build jobs to test the changes.

```bash
vcpkg install --triplet arm64-ios openssl
```

### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

Yes

### CODE REVIEW

**Comment by LilyWangL** [comment]
Thanks for your PR! Can you please correct the Version field in the CONTROL file? You can get more information from [maintainer-guide.md](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md).

**Comment by luncliff** [comment]
@LilyWangL I thought the part was only for `CONTROL` and `portfile.cmake`, but It wasn't. Thanks for the point :)

**Comment by luncliff** [comment]
Updated `Port-Version` in `CONTROL`. 

4 triplets still worked well in my local machine. [The status (Azure Pipelines)](https://dev.azure.com/luncliff/personal/_build/results?buildId=1349&view=results)

**Comment by LilyWangL** [comment]
@luncliff Many ports depend on openssl-unix and they build failed on Linux. You can download the CI error log from: https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/41091/artifacts?artifactName=x64-linux%20port%20build%20failure%20logs&api-version=5.1&%24format=zip

**Comment by luncliff** [comment]
I had to find the reason much earlier. So what I found was that `no-stdio` change was the source of all build failures. 
I was looking for the wrong place since last week... :(

**Review by LilyWangL — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
