### PR TITLE
[nowide] Upgrade to 11.1.1

### LINKED ISSUE #16912: [nowide] update to 11.1.1
Library name: `nowide` (standalone version)

New version number: 11.1.1

Other information that may be useful (release notes, etc...)
https://github.com/boostorg/nowide/releases/tag/v11.1.1

### PR DESCRIPTION
**Pull request by tats-u**
**Describe the pull request**

- What does your PR fix? Fixes #16912

- Which triplets are supported/not supported? Have you updated the CI baseline?
Same as the current version

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Probably yes

### CODE REVIEW

**Review by PhoebeHui — CHANGES_REQUESTED** [review]
Thanks for the PR! Could you update the baseline revision by executing "./vcpkg x-add-version nowide"? And submit the changes.

Please ignore the CI failures, I will rerun this PR after the baseline issue fixed.

**Comment by tats-u** [comment]
@PhoebeHui

```
 tatsu@TATSU-DPC-2ND   base  ~\..\..\vcpkg   master ≣  ./vcpkg x-add-version nowide
 tatsu@TATSU-DPC-2ND   base  ~\..\..\vcpkg   master ≣  git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

**Comment by tats-u** [comment]
@PhoebeHui Done.

**Review by PhoebeHui — APPROVED** [review]
LGTM, thanks for the updates!

**Comment by autoantwort** [comment]
nowide 11.1.1 is not available any more. That causes pipeline failures, I have created #17209

**Pull request merged**
