### PR TITLE
[caf] Update to 0.17.3

### LINKED ISSUE #9438: [caf] update to 0.17.3
Library name: caf

New version number: 0.17.3

Other information that may be useful (release notes, etc...)
https://github.com/actor-framework/actor-framework/releases/tag/0.17.3

### PR DESCRIPTION
**Pull request by JonLiu1993**
Fix #9438

Update caf to the latest version 0.17.3

Note: No feature need to test

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Review by JackBoosY — APPROVED** [review]

**Comment by ras0219-msft** [comment]
LGTM, thanks for the update!

**Pull request merged**
