### PR TITLE
[glib] Enable static build

### LINKED ISSUE #3409: glib:x64-windows-static failing
actually trying to install cairo x64 static, which previously worked

-- CURRENT_PORT_DIR=C:/Users/oli/Dev/vcpkg/ports/glib/.
Glib relies on DllMain and therefore cannot be built statically
CMake Error at C:/Users/oli/Dev/vcpkg/ports/glib/portfile.cmake:13 (message):
  Glib only supports dynamic library and crt linkage

Error: Building package glib:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glib:x64-windows-static
  Vcpkg version: 0.0.110-2018-05-02-1e41c4377f38512d1d6c0d65a2e7b9c7c8b03bea

### PR DESCRIPTION
**Pull request by JackBoosY**
- Enable static build on Windows.
- Disable export  function `dllmain` in `glib` and `gobject`.
- Add missing definition `GLIB_STATIC_COMPILATION ` and `GOBJECT_STATIC_COMPILAT` when building static.
- Fix the static build of ports partially that depend on glib.

Fixes #3409.

### CODE REVIEW

**Review by PhoebeHui — APPROVED** [review]

**Comment by JackBoosY** [comment]
For qt5-base:
https://github.com/microsoft/vcpkg/blob/49972a664f0c7c145972ac46fd86158aed37dd7b/ports/qt5-base/portfile.cmake#L184-L189
Here we must add glib dependencies during static build, or directly use find_package to find zlib and use its targets.

**Comment by BillyONeal** [comment]
Sorry about the qt issue @JackBoosY, I'm hoping to look at it soon

**Comment by JackBoosY** [comment]
Close this PR temporary.

**Pull request closed without merging**
