### PR TITLE
Add freeglut

### LINKED ISSUE #105: Add freeglut
http://freeglut.sourceforge.net/

### PR DESCRIPTION
**Pull request by ebraminio**
Fixes #105

### CODE REVIEW

**Comment by ebraminio** [comment]
I successfully was able to build my project with it.

**Comment by ras0219-msft** [comment]
Thanks!

**Comment by ebraminio** [comment]
Yes, this was specially due to your niceness @ras0219-msft :)

**Comment by leok7v** [comment]
Did:
git pull
powershell -exec bypass scripts\bootstrap.ps1
(successful):

C:\github\microsoft\vcpkg>vcpkg install freeglut
-- CURRENT_INSTALLED_DIR=C:/github/microsoft/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/github/microsoft/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/github/microsoft/vcpkg/packages/freeglut_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/github/microsoft/vcpkg/buildtrees/freeglut
-- CURRENT_PORT_DIR=C:/github/microsoft/vcpkg/ports/freeglut/.
-- Downloading http://downloads.sourceforge.net/project/freeglut/freeglut/3.0.0/freeglut-3.0.0.tar.gz...
-- Downloading http://downloads.sourceforge.net/project/freeglut/freeglut/3.0.0/freeglut-3.0.0.tar.gz... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Extracting source C:/github/microsoft/vcpkg/downloads/freeglut-3.0.0.tar.gz
-- Extracting done
-- Configuring x86-windows-rel
-- Configuring x86-windows-rel done
-- Configuring x86-windows-dbg
-- Configuring x86-windows-dbg done
-- Package x86-windows-rel
-- Package x86-windows-rel done
-- Package x86-windows-dbg
-- Package x86-windows-dbg done
-- Performing post-build validation
Incorrect string found. Expected: `
but found

**Comment by ebraminio** [comment]
I am not sure why it is failing there, perhaps a vcpkg bug itself, but it was used to work on [glyphy ci](https://ci.appveyor.com/project/ebraminio/glyphy)

**Pull request merged**
