### PR TITLE
[boost-regex] Enable arm64-windows (Fix #5511)

### LINKED ISSUE #5511: boost-regex:arm64-uwp fails to build
Installing package boost-iterator[core]:arm64-uwp... done
Elapsed time for package boost-iterator:arm64-uwp: 2.788 s
Starting package 12/43: boost-regex:arm64-uwp
Building package boost-regex[core]:arm64-uwp...
-- Downloading https://github.com/boostorg/regex/archive/boost-1.69.0.tar.gz...
-- Extracting source C:/vcpkg/downloads/boostorg-regex-boost-1.69.0.tar.gz
-- Using source at C:/vcpkg/buildtrees/boost-regex/src/ost-1.69.0-80bf9a4997
-- Building arm64-uwp-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: C:/vcpkg/installed/x86-windows/tools/boost-build/b2.exe;--stagedir=C:/vcpkg/buildtrees/boost-regex/arm64-uwp-rel/stage;--build-dir=C:/vcpkg/buildtrees/boost-regex/arm64-uwp-rel;--user-config=C:/vcpkg/buildtrees/boost-regex/arm64-uwp-rel/user-config.jam;windows-api=store;-j12;--debug-configuration;--debug-building;--debug-generators;--disable-icu;--ignore-site-config;--hash;-q;-sZLIB_INCLUDE="C:/vcpkg/installed/arm64-uwp/include";-sBZIP2_INCLUDE="C:/vcpkg/installed/arm64-uwp/include";threading=multi;threadapi=win32;runtime-link=shared;link=shared;address-model=32;architecture=x86;toolset=msvc-14.1;-sZLIB_BINARY=zlib;-sZLIB_LIBPATH="C:/vcpkg/installed/arm64-uwp/lib";-sBZIP2_BINARY=bz2;-sBZIP2_LIBPATH="C:/vcpkg/installed/arm64-uwp/lib";variant=release;debug-symbols=on
    Working Directory: C:/vcpkg/buildtrees/boost-regex/src/ost-1.69.0-80bf9a4997/build
    See logs for more information:
      C:\vcpkg\buildtrees\boost-regex\build-arm64-uwp-rel-out.log

Call Stack (most recent call first):
  installed/arm64-uwp/share/boost-build/boost-modular-build.cmake:270 (vcpkg_execute_required_process)
  ports/boost-regex/portfile.cmake:20 (boost_modular_build)
  scripts/ports.cmake:71 (include)

Error: Building package boost-regex:arm64-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-regex:arm64-uwp
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

Attached Files:
[build-arm64-uwp-rel-out.log](https://github.com/Microsoft/vcpkg/files/2923571/build-arm64-uwp-rel-out.log)

### PR DESCRIPTION
**Pull request by tony979**
Update boost-build and boost-modular-build-helper to enable boost-regex:arm64-windows and boost-regex:arm64-uwp. Fix #5511

### CODE REVIEW

**Comment by Rastaban** [comment]
With this change I am seeing a new failure in arrow on x64-windows.
[install-x64-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/3118613/install-x64-windows-dbg-out.log)

I also see a great improvement on 30+ boost related ports on arm64-windows.

**Comment by grdowns** [comment]
Hey @tony979, thanks for enabling this! I couldn't repro the issue so I forced a rebuild of the failing port (`arrow`) and found that it passed just fine. This PR is good to be merged in.

**Comment by tony979** [comment]
@Rastaban, there's no change for x64-windows in this commit. In addition, I got arrow:x64-windows installed with the changes. Could you check again?

**Comment by tony979** [comment]
thank you @grdowns, I also got arrow:x64-windows installed with the changes in this commit.

**Pull request merged**
