### PR TITLE
[benchmark] Fix build failure under QNX

### LINKED ISSUE #35510: [benchmark] build for QNX failure. Patch suggestion
### Operating system

host: Ubuntu20.04 cross-compiling target: QNX710

### Compiler

ntoaarch64-g++ from QNX SDP 710

### Steps to reproduce the behavior

```Shell
Crosscompile to QNX and observe build failure due to unaddressed old-style C-casts
```

### Failure logs

```
FAILED: src/CMakeFiles/benchmark.dir/sysinfo.cc.o
qnx-sdp/qnx710/host/linux/x86_64/usr/bin/ntoaarch64-g++ --sysroot=qnx-sdp/qnx710/target/qnx7 -DBENCHMARK_STATIC_DEFINE -DHAVE_STD_REGEX -DHAVE_STEADY_CLOCK -D_QNX_SOURCE -I/home/user/vcpkg/buildtrees/benchmark/src/v1.8.3-eb6e61b079.clean/include -I/home/user/vcpkg/buildtrees/benchmark/src/v1.8.3-eb6e61b079.clean/src -fexceptions -D_XOPEN_SOURCE=600 -D_POSIX_C_SOURCE=200112L -D_QNX_SOURCE -fexceptions -D_XOPEN_SOURCE=600 -D_POSIX_C_SOURCE=200112L -D_QNX_SOURCE  -Wall  -Wextra  -Wshadow  -Wfloat-equal  -Wold-style-cast  -Werror  -Wsuggest-override  -pedantic  -pedantic-errors  -fstrict-aliasing  -Wno-deprecated-declarations  -Wno-deprecated  -Wstrict-aliasing -g -std=c++11 -fvisibility=hidden -fvisibility-inlines-hidden -MD -MT src/CMakeFiles/benchmark.dir/sysinfo.cc.o -MF src/CMakeFiles/benchmark.dir/sysinfo.cc.o.d -o src/CMakeFiles/benchmark.dir/sysinfo.cc.o -c /home/user/vcpkg/buildtrees/benchmark/src/v1.8.3-eb6e61b079.clean/src/sysinfo.cc
/home/user/vcpkg/buildtrees/benchmark/src/v1.8.3-eb6e61b079.clean/src/sysinfo.cc: In function 'double benchmark::{anonymous}::GetCPUCyclesPerSecond(benchmark::CPUInfo::Scaling)':
/home/user/vcpkg/buildtrees/benchmark/src/v1.8.3-eb6e61b079.clean/src/sysinfo.cc:774:69: error: use of old-style cast to 'int64_t' {aka 'long int'} [-Werror=old-style-cast]
   return static_cast<double>((int64_t)(SYSPAGE_ENTRY(cpuinfo)->speed) *
                                                                     ^
                              ---------
                              static_cast<int64_t> (                  )
/home/user/vcpkg/buildtrees/benchmark/src/v1.8.3-eb6e61b079.clean/src/sysinfo.cc:775:51: error: use of old-style cast to 'int64_t' {aka 'long int'} [-Werror=old-style-cast]
                              (int64_t)(1000 * 1000));
                                                   ^
                              ---------
                              static_cast<int64_t> ()
cc1plus: all warnings being treated as errors
```

### Additional context

Upstream bug report at https://github.com/google/benchmark/issues/1707

Patch suggestion:
```diff
diff --git a/src/sysinfo.cc b/src/sysinfo.cc
index 922e83a..ec9fd35 100644
--- a/src/sysinfo.cc
+++ b/src/sysinfo.cc
@@ -771,8 +771,8 @@ double GetCPUCyclesPerSecond(CPUInfo::Scaling scaling) {
   kstat_close(kc);
   return clock_hz;
 #elif defined(BENCHMARK_OS_QNX)
-  return static_cast<double>((int64_t)(SYSPAGE_ENTRY(cpuinfo)->speed) *
-                             (int64_t)(1000 * 1000));
+  return static_cast<double>(static_cast<int64_t>(SYSPAGE_ENTRY(cpuinfo)->speed) *
+                             static_cast<int64_t>(1000 * 1000));
 #elif defined(BENCHMARK_OS_QURT)
   // QuRT doesn't provide any API to query Hexagon frequency.
   return 1000000000;

```

This patch fixes the issue and `benchmark` builds and operates as expected.

### PR DESCRIPTION
**Pull request by jimwang118**
Fixes https://github.com/microsoft/vcpkg/issues/35510

Use C++ casts.

- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] ~~SHA512s are updated for each updated download~~
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

Usage test pass with following triplets:

```
x86-windows
x64-windows
```

### CODE REVIEW

**Review by LilyWangLL — APPROVED** [review]

**Comment by BillyONeal** [comment]
I think this needs to be submitted upstream, and I would like to see confirmation from @Arech that it actually fixes something because the problem will not repro on anything we currently have the capacity to test.

**Comment by Arech** [comment]
Well, with the exception of adding `-Werror=old-style-cast` it's the same patch, that I have suggested, so it should work...
But I'll test it tomorrow anyway and will get back to you with the results. It's 23:35 here, good night everyone...

**Comment by jimwang118** [comment]
Track the upstream issue [1707](https://github.com/google/benchmark/issues/1707).

**Comment by Arech** [comment]
I can confirm that the PR indeed compiles and works on QNX as expected

In the manifest:

```json
"default-registry": {
  "kind": "git",
  "repository": "https://github.com/jimwang118/vcpkg",
  "reference": "fixbenchmark",
  "baseline": "0d6278ea26eecd1ebd3cbb2d183d3eb0cee6cf5c"
},
```

```
benchmarks$ . $QNXSDP/qnx710/qnxsdp-env.sh
...
benchmarks$ rm -rf ./build_qnx; cmake -B ./build_qnx -G Ninja -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=aarch64-qnx.cmake -DCMAKE_BUILD_TYPE=Release && cmake --build ./build_qnx -j 8
...
-- Running vcpkg install
warning: Embedding `vcpkg-configuration` in a manifest file is an EXPERIMENTAL feature.
Fetching registry information from https://github.com/jimwang118/vcpkg (fixbenchmark)...
...
The following packages will be built:
    benchmark:arm64-qnx@1.8.3#1 -- ...
...
Installing 85/165 benchmark:arm64-qnx@1.8.3#1...
Building benchmark:arm64-qnx@1.8.3#1...
-- [OVERLAY] Loading triplet configuration from: .../arm64-qnx.cmake
...
-- Applying patch fix_qnx.patch
...
-- Configuring arm64-qnx
-- Building arm64-qnx-dbg
-- Building arm64-qnx-rel
...
```

I run the binary on a device with QNX and it worked as expected.

**Comment by jimwang118** [comment]
The upstream fix PR [1739](https://github.com/google/benchmark/pull/1739) has been merged.

**Pull request merged**
