### PR TITLE
[chartdir] use versioned download link

### LINKED ISSUE #23721: [chartdir] update download link
We are the developer of the ChartDirector software. Recently, we find out ChartDirector is available through vckpg as the package "chartdir". The package downloads the ChartDirector from our web site at https://www.advsofteng.com/chartdir_cpp_win.zip. This link is a generic link that always points to the latest update of ChartDirector. The file content can change over time and this will break the hash checksum in the chartdir port. 

To make the port more stable, we have created a new link https://www.advsofteng.com/vckpg/chartdir_cpp_win_7.0.0.zip that we promise will never change. This will keep the port stable. Would you mind to update the download link in the port to use this is new URL?

Also, can we manage the chartdir port ourselves in vcpkg (we are already managing nuget packages for our .NET release), or must be always go through you?  

Regards
Peter Kwan

### PR DESCRIPTION
**Pull request by cd-pkwan**
The original download link is a generic link that points to the latest version of the software. The download content can change from time to time, and this will break the SHA512 hash in the port. This update change the download link to a link that points to the real file with version number, which will not change. This makes the port more stable.

### CODE REVIEW

**Comment by strega-nil-ms** [comment]
@cd-pkwan I assume you're the author, since the website has been changed to mention vcpkg; would it be possible for you to do the same for the macOS and Linux versions?

**Comment by JonLiu1993** [comment]
@cd-pkwan ,Thanks for your pr, could you please sign in CLA first?

**Comment by BillyONeal** [comment]
I removed the skips from https://github.com/microsoft/vcpkg/commit/671db8ae9d4b62d1c4303332144dd493da7d4057 from ci.baseline.txt , so if we get versioned links for MacOS and Linux we can finally start testing chardir regularly :)

**Review by cd-pkwan — COMMENTED** [review]
Updated to use versioned download link for macOS, Linux x86 and Linux x64.

**Comment by BillyONeal** [comment]
```
Building package chartdir[core]:x64-windows-static...
-- Note: chartdir only supports dynamic library linkage. Building dynamic library.
CMake Error at scripts/cmake/vcpkg_check_linkage.cmake:61 (message):
  Refusing to build unexpected dynamic library against the static CRT.

      If this is desired, please configure your triplet to directly request this configuration.
Call Stack (most recent call first):
  ports/chartdir/portfile.cmake:1 (vcpkg_check_linkage)
  scripts/ports.cmake:145 (include)
```

Should we add `"supports": "!staticcrt"` to `vcpkg.json`?

The other platforms are broken because:

```
if(TRIPLET_SYSTEM_ARCH MATCHES "arm" OR VCPKG_CMAKE_SYSTEM_NAME STREQUAL "WindowsStore" OR VCPKG_LIBRARY_LINKAGE STREQUAL static)

    set(VCPKG_POLICY_EMPTY_PACKAGE enabled)

```

is entered, so SOURCE_PATH does not get set, so

```
file(COPY "${SOURCE_PATH}/LICENSE.TXT" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}/copyright")
```

fails.

Proposal:

```
From 7d16e8044a677537c24564cce898ebdedeed3772 Mon Sep 17 00:00:00 2001
From: Billy Robert O'Neal III <bion@microsoft.com>
Date: Tue, 29 Mar 2022 10:52:41 -0700
Subject: [PATCH] Guard with supports rather than making the package empty.

---
 ports/chartdir/portfile.cmake | 6 +-----
 ports/chartdir/vcpkg.json     | 3 ++-
 versions/c-/chartdir.json     | 2 +-
 3 files changed, 4 insertions(+), 7 deletions(-)

diff --git a/ports/chartdir/portfile.cmake b/ports/chartdir/portfile.cmake
index bfeb10699..b263588f3 100644
--- a/ports/chartdir/portfile.cmake
+++ b/ports/chartdir/portfile.cmake
@@ -1,10 +1,6 @@
 vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)
 
-if(TRIPLET_SYSTEM_ARCH MATCHES "arm" OR VCPKG_CMAKE_SYSTEM_NAME STREQUAL "WindowsStore" OR VCPKG_LIBRARY_LINKAGE STREQUAL static)
-
-    set(VCPKG_POLICY_EMPTY_PACKAGE enabled)
-
-elseif(VCPKG_TARGET_IS_WINDOWS)
+if(VCPKG_TARGET_IS_WINDOWS)
 
     vcpkg_download_distfile(ARCHIVE_FILE
         URLS "https://www.advsofteng.com/vcpkg/chartdir_cpp_win_7.0.0.zip"
diff --git a/ports/chartdir/vcpkg.json b/ports/chartdir/vcpkg.json
index 425a2ca91..b6a1cfa0a 100644
--- a/ports/chartdir/vcpkg.json
+++ b/ports/chartdir/vcpkg.json
@@ -3,5 +3,6 @@
   "version": "7.0.0",
   "port-version": 4,
   "description": "ChartDirector is a powerful chart component for creating professional looking charts for web and windows applications.",
-  "homepage": "https://www.advsofteng.com/"
+  "homepage": "https://www.advsofteng.com/",
+  "supports": "!staticcrt & !arm & !uwp"
 }
diff --git a/versions/c-/chartdir.json b/versions/c-/chartdir.json
index a8aeb8aab..d7186fafa 100644
--- a/versions/c-/chartdir.json
+++ b/versions/c-/chartdir.json
@@ -1,7 +1,7 @@
 {
   "versions": [
     {
-      "git-tree": "470db0162f8e6a30ded91a22d8611e1a2fee2aac",
+      "git-tree": "6b1b1029aa38c2a698a4cd6e3cfa7104a3580baf",
       "version": "7.0.0",
       "port-version": 4
     },
-- 
2.35.1.windows.2


```

**Comment by cd-pkwan** [comment]
My understanding of x64-windows-static is that the package should work with the static C runtime. In this case, the chartdir, though being a DLL,  should work with the CRT static library. I often create projects in Visual Studio that use the /MT option to link with the static C runtime and it works normally. Does the x64-windows-static actually test if the package itself is a static library?

**Comment by BillyONeal** [comment]
>My understanding of x64-windows-static is that the package should work with the static C runtime. 

We have blocks around attempting to use DLLs with the static CRT because it gives each DLL their own copy of the CRT. So the DLL interface can't contain std::string* or FILE* or otherwise interact with any CRT entity, which substantially all libraries we have seen are unprepared to deal with.

>Does the x64-windows-static actually test if the package itself is a static library?

I don't know if we have an explicit post-build check for it but if a port does otherwise that port is extremely badly behaved. People who pick static want single-exe deployment.

**Comment by BillyONeal** [comment]
> We have blocks around attempting to use DLLs with the static CRT because it gives each DLL their own copy of the CRT. So the DLL interface can't contain std::string* or FILE* or otherwise interact with any CRT entity, which substantially all libraries we have seen are unprepared to deal with.

That said it looks like bchartdir.h indicates that this is intentionally done at the moment.

I think you can just do:

    # ChartDirector's DLL interface only contains primitive types, so it is CRT agnostic.
    if("${VCPKG_LIBRARY_LINKAGE}" STREQUAL "static")
        message(STATUS "Note: ${PORT} only supports dynamic library linkage. Building dynamic library.")
        set(VCPKG_LIBRARY_LINKAGE dynamic)
    endif()

or similar in portfile.cmake rather than using `vcpkg_check_linkage`. `vcpkg_check_linkage` is the 99% case but you're kinda juggling razor blades :)

**Comment by JonLiu1993** [comment]
@cd-pkwan, Could you consider @BillyONEal's suggestion?

**Comment by cd-pkwan** [comment]
Yes, I will try to include @BillyONeal's suggestion.

Actually I have never used vcpkg. One day my client told me our software ChartDirector is available in vcpkg but the checksum is incorrect due to we updated our release file. That's why I am here. I will download vcpkg and try it myself to make sure any I  would not break something by modifying the package script.

**Comment by BillyONeal** [comment]
@cd-pkwan Thanks so much for helping fix the situation :D

vcpkg requires exact SHA matches to deliver on the "no changes means no changes" policy.

**Comment by JonLiu1993** [comment]
@cd-pkwan ,Can you please resolve the conflicts against master?

**Comment by cd-pkwan** [comment]
I am embarassed to say that I am not familiar with vcpkg or github. I think the conflict is resolved, but there is still a checksum problem with versions/c-/chartdir.json. Can someone help to fix this problem as well?

**Comment by BillyONeal** [comment]
The SHA listed there is the git-tree of the portfile directory. You can fix it with (assuming `https://github.com/microsoft/vcpkg/` is your `origin` and your stuff is the current branch):

```
git merge origin/master
git checkout origin/master -- versions
.\vcpkg x-add-version chartdir
git commit -am "Update version database."
```

I just ran this for you.

**Comment by BillyONeal** [comment]
> I am embarassed to say that

No need to be embarrassed! In a perfect world we would give you one button to just fix this...

**Review by BillyONeal — APPROVED** [review]

**Review by JonLiu1993 — APPROVED** [review]

**Pull request merged**
