### PR TITLE
[node-api-headers] add usage

### PR DESCRIPTION
**Pull request by Pospelove**

### CODE REVIEW

**Comment by BurningEnlightenment** [comment]
How do you select the correct target triplet and CMake generator+toolchain? Or more specifically: How do you write the npm/yarn install script for a package with a native addon?

**Comment by Pospelove** [comment]
@BurningEnlightenment I've updated usage, does this address your questions?

P.S. I may take a look at publishing later. For now, this port only helps to build something that will be loaded by NodeJS _without npm/node-gyp/cmake-js_ so it doesn't have a clear way to do npm publish. I believe we can still work around that by creating a package.json file, etc

**Comment by BurningEnlightenment** [comment]
> For now, this port only helps to build something that will be loaded by NodeJS without npm/node-gyp/cmake-js 

Yes, I understood that and I like it a lot. I consider the usage information appropriate for the scope of the package.
I just wanted to know, whether or not someone thought the end-user distribution story through. Obviously this is out of scope of this port as it requires some sort of integration with npm and the like. My primary desire is to reduce the required amount of (transitive) dependencies to ship native node addons.

**Comment by Pospelove** [comment]
@BurningEnlightenment 
I think this port is a good choice in terms of reducing the required amount of dependencies.

However, as I have said, we'll need a custom script to publish node addons built with that port.

I'll likely need something like that for my own project. So, I think I'll do that at some point. Please let me know if you'll have something to share earlier than me because I struggle to say what my solution would be and when I'll work on it.

**Comment by jimwang118** [comment]
The usage has been tested successfully locally.
```
find_package(unofficial-node-api-headers CONFIG REQUIRED)
target_link_libraries(main PRIVATE unofficial::node-api-headers::node-api-headers)
```

**Pull request merged**
