### PR TITLE
[nss] Version bump to 3.77

### PR DESCRIPTION
**Pull request by plq**
NSS 3.77 was released:

https://groups.google.com/a/mozilla.org/g/dev-tech-crypto/c/zOd5WWPcPkc/m/2rVl77IkBQAJ

### CODE REVIEW

**Review by Adela0814 — APPROVED** [review]

**Comment by strega-nil-ms** [comment]
Thanks!

**Comment by abuyanov** [comment]
Is it possible to update to 3.78? (https://groups.google.com/a/mozilla.org/g/dev-tech-crypto/c/hQUjX_jwbEk)

**Comment by plq** [comment]
Sure, just imitate this pull request by following the below steps:

1. Switch to (or download) a fresh vcpkg checkout
2. Edit the NSS version in portfile.cmake. 
3. Try to install NSS. it will fail because you didn't update the hash. Get the new hash from the error log on the console, or compute it yourself using the following poweshell command ```Get-FileHash <path to input file> -Algorithm SHA512``` and add it to the portfile
4. if installation works, commit the new portfile
5. Run ```vcpkg x-add-version nss``` and commit the result. (two commits in total)
6. Send a pull request.

**Comment by abuyanov** [comment]
Thx

**Comment by abuyanov** [comment]
I've noticed that some builded dlls in the installed\<triplet>\bin folder (freebl3, nss3, nssckbi, nssutil, smime3, softokn3, ssl3) do not have a version info. While nspr related files has version info.
image
What needs to be changed so that the files have a version?

**Pull request merged**
