### PR TITLE
[libvpx] allow arm64 as target architecture

### PR DESCRIPTION
**Pull request by hanseuljun**
According to libvpx (refer https://github.com/webmproject/libvpx), not only x64 and x86, but arm64 is supported. So, loosening the guarding condition.

### CODE REVIEW

**Review by PhoebeHui — CHANGES_REQUESTED** [review]
Thanks for the PR!

Could you update the Port-Version to 'Port-Version: 2' in CONTROL file?

**Comment by hanseuljun** [comment]
Done!

**Review by PhoebeHui — APPROVED** [review]
Thanks for your updates!

**Comment by ras0219-msft** [comment]
LGTM, thanks for the PR!

**Pull request merged**
