### PR TITLE
[nmap]Fix build error.

### PR DESCRIPTION
**Pull request by JackBoosY**
Fix build error on Windows/Linux.

Related: #6581.

### CODE REVIEW

**Comment by JackBoosY** [comment]
Now the problem is these error:
```makefile.dep:1: *** missing separator.  Stop.```

@Neumann-A Can you have a look?

**Comment by Neumann-A** [comment]
@JackBoosY Cannot help here. I have no experience with Makefile magic.

**Comment by Neumann-A** [comment]
But here are my errors:
```
=== BUILDING ===
lc.exe -MM -I/e/openni2/buildtrees/nmap/src/nmap-7-8208ce9e35/liblinear -I/e/openni2/buildtrees/nmap/src/nmap-7-8208ce9e35/liblua -I/e/openni2/buildtrees/nmap/src/nmap-7-8208ce9e35/libdnet-stripped/include -IE:/openni2/installed/x64-windows/include  -IE:/openni2/installed/x64-windows/include -I/e/openni2/buildtrees/nmap/src/nmap-7-8208ce9e35/libpcap -I/e/openni2/buildtrees/nmap/src/nmap-7-8208ce9e35/nbase -I/e/openni2/buildtrees/nmap/src/nmap-7-8208ce9e35/nsock/include -DHAVE_CONFIG_H -DNMAP_NAME=\"Nmap\" -DNMAP_URL=\"https://nmap.org\" -DNMAP_PLATFORM=\"x86_64-pc-msys\" -DNMAPDATADIR=\"/e/openni2/packages/nmap_x64-windows/share/nmap\" -D_FORTIFY_SOURCE=2 charpool.cc FingerPrintResults.cc FPEngine.cc FPModel.cc idle_scan.cc MACLookup.cc main.cc nmap.cc nmap_dns.cc nmap_error.cc nmap_ftp.cc NmapOps.cc NmapOutputTable.cc nmap_tty.cc osscan2.cc osscan.cc output.cc payload.cc portlist.cc portreasons.cc protocols.cc scan_engine.cc scan_engine_connect.cc scan_engine_raw.cc scan_lists.cc service_scan.cc services.cc Target.cc NewTargets.cc TargetGroup.cc targets.cc tcpip.cc timing.cc traceroute.cc utils.cc xml.cc nse_main.cc nse_utility.cc nse_nsock.cc nse_dnet.cc nse_fs.cc nse_nmaplib.cc nse_debug.cc nse_pcrelib.cc nse_lpeg.cc nse_openssl.cc nse_ssl_cert.cc nse_libssh2.cc nse_zlib.cc > makefile.dep
/bin/sh: lc.exe: command not found
make: *** No rule to make target 'liblinear/Makefile', needed by 'build-liblinear'.  Stop.
make: *** Waiting for unfinished jobs....
Compiling libnetutil
cd libnetutil && make
make[1]: Entering directory '/e/openni2/buildtrees/nmap/x64-windows-rel/libnetutil'
lc.exe -MM -I/e/openni2/buildtrees/nmap/src/nmap-7-8208ce9e35/liblinear -I/e/openni2/buildtrees/nmap/src/nmap-7-8208ce9e35/liblua -I/e/openni2/buildtrees/nmap/src/nmap-7-8208ce9e35/libdnet-stripped/include -IE:/openni2/installed/x64-windows/include  -IE:/openni2/installed/x64-windows/include -I/e/openni2/buildtrees/nmap/src/nmap-7-8208ce9e35/libpcap -I/e/openni2/buildtrees/nmap/src/nmap-7-8208ce9e35/nbase -I/e/openni2/buildtrees/nmap/src/nmap-7-8208ce9e35/nsock/include -DHAVE_CONFIG_H -D_FORTIFY_SOURCE=2 /e/openni2/buildtrees/nmap/src/nmap-7-8208ce9e35/libnetutil/netutil.cc /e/openni2/buildtrees/nmap/src/nmap-7-8208ce9e35/libnetutil/PacketElement.cc /e/openni2/buildtrees/nmap/src/nmap-7-8208ce9e35/libnetutil/NetworkLayerElement.cc /e/openni2/buildtrees/nmap/src/nmap-7-8208ce9e35/libnetutil/ARPHeader.cc /e/openni2/buildtrees/nmap/src/nmap-7-8208ce9e35/libnetutil/PacketElement.cc /e/openni2/buildtrees/nmap/src/nmap-7-8208ce9e35/libnetutil/NetworkLayerElement.cc /e/openni2/buildtrees/nmap/src/nmap-7-8208ce9e35/libnetutil/TransportLayerElement.cc /e/openni2/buildtrees/nmap/src/nmap-7-8208ce9e35/libnetutil/ARPHeader.cc /e/openni2/buildtrees/nmap/src/nmap-7-8208ce9e35/libnetutil/EthernetHeader.cc /e/openni2/buildtrees/nmap/src/nmap-7-8208ce9e35/libnetutil/ICMPv4Header.cc /e/openni2/buildtrees/nmap/src/nmap-7-8208ce9e35/libnetutil/ICMPv6Header.cc /e/openni2/buildtrees/nmap/src/nmap-7-8208ce9e35/libnetutil/IPv4Header.cc /e/openni2/buildtrees/nmap/src/nmap-7-8208ce9e35/libnetutil/IPv6Header.cc /e/openni2/buildtrees/nmap/src/nmap-7-8208ce9e35/libnetutil/TCPHeader.cc /e/openni2/buildtrees/nmap/src/nmap-7-8208ce9e35/libnetutil/UDPHeader.cc /e/openni2/buildtrees/nmap/src/nmap-7-8208ce9e35/libnetutil/RawData.cc /e/openni2/buildtrees/nmap/src/nmap-7-8208ce9e35/libnetutil/HopByHopHeader.cc /e/openni2/buildtrees/nmap/src/nmap-7-8208ce9e35/libnetutil/DestOptsHeader.cc /e/openni2/buildtrees/nmap/src/nmap-7-8208ce9e35/libnetutil/FragmentHeader.cc /e/openni2/buildtrees/nmap/src/nmap-7-8208ce9e35/libnetutil/RoutingHeader.cc /e/openni2/buildtrees/nmap/src/nmap-7-8208ce9e35/libnetutil/PacketParser.cc > makefile.dep
make[1]: *** No rule to make target 'Makefile.in', needed by 'Makefile'.  Stop.
make[1]: *** Waiting for unfinished jobs....
/bin/sh: lc.exe: command not found
make[1]: Leaving directory '/e/openni2/buildtrees/nmap/x64-windows-rel/libnetutil'
make: *** [Makefile:164: build-netutil] Error 2

```

**Comment by JackBoosY** [comment]
@Neumann-A 
I found that configure/makefile has a strong relationship with source code directory, which means we can't simply separate the generated folder from the source.

**Comment by Neumann-A** [comment]
@JackBoosY really stupid question. I just browsed the source dir and found an nmap.sln in the mswin32 folder. According to https://nmap.org/book/inst-windows.html this is the prefered way to build nmap on windows. So we should use and patch that instead of doing makefile magic. I was able to build that solution after a few changes but it will require some patching to get the external vcpkg dependencies in. 
Since I am not using nmap I will not work on that port further.

**Pull request merged**
