### PR TITLE
[vcpkg-cmake] Fix vcpkg_copy_pdbs false alarm

### PR DESCRIPTION
**Pull request by myd7349**
**Describe the pull request**

- #### What does your PR fix?  
  Fixes #...

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  <all / linux, windows, ...>, <Yes/No>

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  `Your answer`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  <Yes / I am still working on this PR>

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by PhoebeHui** [comment]
The baseline issue would be fixed by https://github.com/microsoft/vcpkg/pull/19361.

**Review by PhoebeHui — APPROVED** [review]
Thanks for your PR!

**Comment by JackBoosY** [comment]
I think something breaks the pipeline test.

**Comment by dg0yt** [comment]
> I think something breaks the pipeline test.

The CI errors seem unrelated.
- ptex:x86-windows had issues before, cf. https://github.com/microsoft/vcpkg/pull/18961. Maybe it isn't triggered often enough in CI.
- The rbdl-orb problems are not original build errors (no failure logs!), but duplicate installations with port rbdl. Interesting: They happened only x86-compatible windows builds other native x64-windows.

**Comment by PhoebeHui** [comment]
@dg0yt, thanks for your comments! the baseline issue would be fixed by https://github.com/microsoft/vcpkg/pull/19453

**Review by silverqx — APPROVED** [review]
This looks exactly like PR I have proposed at #19462, I have tested it and it should really be `dlls_without_matching_pdbs`, so I can approve this.

**Comment by PhoebeHui** [comment]
@dan-shaw, could you help merge this PR?

**Pull request merged**
