### PR TITLE
[vlfeat] Add initial port

### PR DESCRIPTION
**Pull request by cdcseacave**
Implement the port for the open library of computer vision algorithms http://vlfeat.org/
Using frocked version primarily because the original version does not support CMake.

### CODE REVIEW

**Comment by cenit** [comment]
I opened a PR on vlfeat for adding CMakeLists.txt: https://github.com/vlfeat/vlfeat/pull/171
It is still there, unaccepted, but working!

But the problem is that building all of vlfeat requires Matlab...

**Comment by cdcseacave** [comment]
I didn't know, so I implemented again myself.

**Comment by cdcseacave** [comment]
I'm not good at CMake/Ninja, can anybody have a look why enabling `ENABLE_AVX` it breaks the build with Ninja? So it build fine both on windows and Linux with the default building system, but it does not work if trying with Ninja.
```
-DENABLE_AVX=ON
```

**Comment by cenit** [comment]
to be honest what I don't like about your fork is that it is so full of CMake code, that it is very difficult to debug. Is it all yours? Is it all necessary? I was able to build vlfeat (and use it in production environment!) with my much smaller single-file CMakeLists.txt, which also provided Matlab wrappers!

**Comment by cdcseacave** [comment]
No, much of it is not necessary, I took it from an other project of mine where it is necessary (I imagine you speak about Utils.cmake), but it has some important features, like controlling SSE flags, machine flags, build as lib+app or lib only. If your script does all of this, feel free to propose a PR.

**Comment by cenit** [comment]
what do you mean with "build as app"?
my CMakeLists.txt was more of a porting of the official makefile than else. Only supported flags (nothing added that was not explicitly set by the original author in the makefile...), checking the consistency of results and reliability of the compilation. And of course only libs were coming out from vlfeat...

**Comment by ras0219-msft** [comment]
We've closed this for inactivity. If this is in error, please open a new PR!

**Pull request closed without merging**
