### PR TITLE
Add kealib ports and modify hdf5 recipe

### PR DESCRIPTION
**Pull request by miurahr**
KEALib is a library to provide a driver to process HDF5 based raster file format.

- Patch library cmake scripts.
- Provide MIT license file.
- Update hdf5 script to provide cpp library

Signed-off-by: Hiroshi Miura <miurahr@linux.com>

### CODE REVIEW

**Comment by miurahr** [comment]
There are still errors, CASCADED_DUE_TO_MISSING_DEPENDENCIES, and unused variable ENABLE_SHARED_LIBS.
Now working in progress.

**Comment by miurahr** [comment]
Warning `unused variable ENABLE_SHARED_LIBS` is fixed. 
Current CONTROL has 
```
Build-Depends: hdf5[cpp]
````
and it causes `CASCADED_DUE_TO_MISSING_DEPENDENCIES` error.
and not print missing dependency in console. Instead, it shows trouble shooting message like as follows:
```
Error: Building package kealib failed with: CASCADED_DUE_TO_MISSING_DEPENDENCIES
Please ensure you're using the latest portfiles with `.\\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
 Package: kealib
 Vcpkg version: brabrabra

Additionally, attach any relevant sections from the log files above.
```

Following manual compilation is successful.

Changing CONTROL to
```
Build-Depends: hdf5
````

and run
```
.\vcpkg install hdf5[cpp]
.\vcpkg install kealib
```
What is happened?

I try an investigation . in vcpkg source,  `toolsrc/src/vcpkg/build.cpp:73`
```
        const auto result = Build::build_package(paths, build_config, status_db);
        System::println("Elapsed time for package %s: %s", spec.to_string(), build_timer.to_string());

        if (result.code == BuildResult::CASCADED_DUE_TO_MISSING_DEPENDENCIES)
        {
            System::println(System::Color::error,
                            "The build command requires all dependencies to be already installed.");
            System::println("The following dependencies are missing:");
            System::println();
            for (const auto& p : result.unmet_dependencies)
            {
                System::println("    %s", p);
            }
            System::println();
            Checks::exit_fail(VCPKG_LINE_INFO);
        }

        Checks::check_exit(VCPKG_LINE_INFO, result.code != BuildResult::EXCLUDED);

        if (result.code != BuildResult::SUCCEEDED)
        {
            System::println(System::Color::error, Build::create_error_message(result.code, spec));
            System::println(Build::create_user_troubleshooting_message(spec));
            Checks::exit_fail(VCPKG_LINE_INFO);
        }
```
According from the code, when failing CASCADED_DUE_TO_MISSING_DEPENDENCIES, we should see   `The build command requires all dependencies to be already installed.` message, but don't.
I seems to see a error message from here
```
        if (result.code != BuildResult::SUCCEEDED)
        {
            System::println(System::Color::error, Build::create_error_message(result.code, spec));
            System::println(Build::create_user_troubleshooting_message(spec));
```
This is very very strange behavior.

**Comment by miurahr** [comment]
There is a  problem in static build that kealib build cannot found szip-static library.

**Comment by miurahr** [comment]
in vcpkg/installed/lib/libhdf5.settings
```
	    SUMMARY OF THE HDF5 CONFIGURATION
	    =================================

General Information:
-------------------
                   HDF5 Version: 1.10.1
                  Configured on: 2018-02-03
                  Configured by: Ninja
                    Host system: Windows-10.0.14393
              Uname information: Windows
                       Byte sex: little-endian
             Installation point: C:/src/vcpkg/packages/hdf5_x86-windows-static

Linking Options:
----------------
                      Libraries: 
  Statically Linked Executables: OFF
                        LDFLAGS: /machine:X86
                     H5_LDFLAGS: 
                     AM_LDFLAGS: 
                Extra libraries: C:/src/vcpkg/installed/x86-windows-static/lib/zlib.lib;szip-static;szip-static
                       Archiver: 
                         Ranlib: 
```
Especially
```
Extra libraries: C:/src/vcpkg/installed/x86-windows-static/lib/zlib.lib;szip-static;szip-static
```
zlib are described in full path, but not for szip. `szip-static` would be an IMPORT name that is not resolved. This seems to be a bug in HDF5 static library.

**Comment by miurahr** [comment]
I've tried to resolve CASCADED_DUE_TO_MISSING_DEPENDENCIES error by reverting problematic commit for HDF5 port and by always building cpp feature of HDF5.
This solves the problem, and pass unit test for kealib in dynamic library builds.

**Comment by miurahr** [comment]
I believe I made it working.
This PR add `kealib` port and fix some bug or ugly behavior in hdf5 for handling cpp build and szip link in -windows-static.

**Comment by ras0219-msft** [comment]
Thanks for the PR, sorry for taking so long to get it merged!

We found and fixed the issue with depending on `hdf5[cpp]`, so I've restored that (it was the right way to go!)

Additionally, I minimized the changes in the patch file -- lots of the changes weren't used by us, so they would just cause merge conflicts in the future when we upgrade to the next kealib version :)

**Pull request merged**
