### PR TITLE
[ace] 6.5.12

### PR DESCRIPTION
**Pull request by jwillemsen**
**Describe the pull request**

- What does your PR fix? 

Upgrade to ACE 6.5.12

### CODE REVIEW

**Comment by NancyLi1013** [comment]
Hi @jwillemsen 
Thanks for this PR.

Have you tested all features in this PR? Can these features work fine?

**Comment by jwillemsen** [comment]
Yes, the features work

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
LGTM now, thanks for your PR @jwillemsen.

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
