### PR TITLE
[libtiff] Switch to vcpkg_from_gitlab function 

### LINKED ISSUE #3483: tiff:x64-windows download link broken
I am trying to build Theia:64, and I get the following error when running:

` .\vcpkg.exe install theia:x64-windows`

..some packages install successfully, then on libtiff.. 

```
Starting package 1/18: tiff:x64-windows
Building package tiff[core]:x64-windows...
-- CURRENT_INSTALLED_DIR=D:/vcpkg-master/installed/x64-windows
-- DOWNLOADS=D:/vcpkg-master/downloads
-- CURRENT_PACKAGES_DIR=D:/vcpkg-master/packages/tiff_x64-windows
-- CURRENT_BUILDTREES_DIR=D:/vcpkg-master/buildtrees/tiff
-- CURRENT_PORT_DIR=D:/vcpkg-master/ports/tiff/.
-- Downloading http://download.osgeo.org/libtiff/tiff-4.0.9.tar.gz...
-- Downloading http://download.osgeo.org/libtiff/tiff-4.0.9.tar.gz... Failed. Status: 56;"Failure when receiving data from the peer"

Error: Building package tiff:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: tiff:x64-windows
  Vcpkg version: 0.0.105-unknownhash
```

The link seems to be down.

### PR DESCRIPTION
**Pull request by thomaswillecomme**
Fixes #3483
Just replace the download url to a buggy server by the official gitlab source repository using from_gitlab routine

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
yes just did and added changed files

### CODE REVIEW

**Review by PhoebeHui — CHANGES_REQUESTED** [review]
@thomaswillecomme, could you update the version database?

**Review by BillyONeal — APPROVED** [review]

**Comment by BillyONeal** [comment]
> @thomaswillecomme, could you update the version database?

@PhoebeHui we can fix these for folks by doing:

```
(checkout their branch)
git merge origin/master
git checkout origin/master -- versions
vcpkg x-add-version tiff
(commit and push the changes)
```

If you're super busy don't worry about it.

**Comment by PhoebeHui** [comment]
@BillyONeal, thanks for helping follow up this PR, I'm pretty busy in the past week, I could be going through these PRs this week.

**Comment by dg0yt** [comment]
Please don't merge this with a "buggy URL" commit message. The URL is valid and working. It is not reliable for some users for unknown reasons (user side connectivity, rate limiting etc.)

**Review by PhoebeHui — APPROVED** [review]

**Comment by thomaswillecomme** [comment]
Thanks for merging, i was not available these days but your remarks will be helpful for the next PR.

**Pull request merged**
