### PR TITLE
[libspatialite]  Use pkgconfig for nmake and autotools

### PR DESCRIPTION
**Pull request by dg0yt**
- #### What does your PR fix?  
  - [x] Use pkg-config for determining libraries to pass even to nmake, instead of hardcoding.
         Needed to allow features in dependencies.
  - [x] Fix building with mingw
  - [x] Install pc file for windows
  - [x] Add feature interface

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all, yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  yes

### CODE REVIEW

**Comment by Neumann-A** [comment]
I have the feeling you want to pass '--msvc-syntax' to pkg-config and avoid the transformation?

**Comment by dg0yt** [comment]
> I have the feeling you want to pass '--msvc-syntax' to pkg-config and avoid the transformation?

Possibly, yes. TBH I know the option but I don't know enough about nmake to know for sure. I only see explicit `FOO_LIBS=D:/some_path/z.lib`, while the output from pkg-config is:
~~~
$ pkg-config.exe --libs --msvc-syntax zlib
/libpath:D:/msys64/mingw64/lib z.lib
~~~

If it is so easy, why all these explicit paths e.g. in https://github.com/microsoft/vcpkg/blob/master/ports/gdal/dependency_win.cmake? I'm really curious, because this nmake dependency stuff is a blocker for improvements.

**Comment by Neumann-A** [comment]
It simply predates the pkg-config stuff and nobody tried to change it yet because it could be  a headache to get it to work again. I only introduced the pkg-config stuff in qt5-base because it fixed a CI build order/dependency regression.

**Comment by dg0yt** [comment]
Okay, I will give it a try as long as CI is idle.

In the geographic ports, there is a lot of nmake+autotools meeting a lot of features, with significant effect on dependencies and license options. This really needs to be improved.

For `x_vcpkg_pkgconfig_get_modules` I have a draft change to catch and report errors (via `RESULT_VARIABLE`). I would suggest to add a `REQUIRED` keyword to enable this behaviour.

**Comment by dg0yt** [comment]
> Okay, I will give it a try as long as CI is idle.

Works for `libspatialite`. This makes it much easier. :+1:

IIUC `vcpkg_build_nmake` doesn't do anyhing to pass `/LIBPATH` or adjust `ENV{LIB}` for vcpkg's installed dir.

**Comment by dg0yt** [comment]
@PhoebeHui Ping for review. Needed for proceeding with #20443.

**Comment by dg0yt** [comment]
Also needed for #21261.

**Comment by dg0yt** [comment]
Ping again @PhoebeHui. This and #20443 was meant to be finished before #16494.

**Comment by PhoebeHui** [comment]
@dg0yt, I'm sorry for my late response, I will test these features in my local machine firstly. And invite other members help review at the same time.

**Comment by PhoebeHui** [comment]
All features test passed with x64-windows and x64-linux.

**Review by PhoebeHui — APPROVED** [review]
LGTM.

**Comment by vicroms** [comment]
Thanks for the PR!

**Comment by dg0yt** [comment]
Thank you @PhoebeHui @vicroms.

**Pull request merged**
