### PR TITLE
[Baseline] Fix boost-*:arm-uwp failure and resolve conflicts in CI

### PR DESCRIPTION
**Pull request by PhoebeHui**
Related to https://github.com/microsoft/vcpkg/pull/11427

Fix the The following issues in CI baseline
1. Building boost-* with arm-uwp requires the x86-windows boost-* which breaks CI testing, Ignore them
boost-atomic:arm-uwp=ignore
boost-signals:arm-uwp=ignore
boost-exception:arm-uwp=ignore
boost-regex:arm-uwp=ignore
boost-nowide:arm-uwp=ignore
boost-system:arm-uwp=ignore
boost-container:arm-uwp=ignore

2. Resolve conflicts bettwen microsoft-signalr and signalrclient, they are different repo, and they don't depend on each other.

Failures:
Installing package microsoft-signalr[core,cpprestsdk,default-features]:x86-windows...
The following files are already installed in F:/vcpkg/boost_173/vcpkg/installed/x86-windows and are in conflict with microsoft-signalr:x86-windows

Installed by signalrclient:x86-windows
    bin/signalrclient.dll
    debug/bin/signalrclient.dll
    debug/lib/signalrclient.lib
    include/signalrclient/_exports.h
    include/signalrclient/connection.h
    include/signalrclient/connection_state.h
    include/signalrclient/hub_connection.h
    include/signalrclient/hub_exception.h
    include/signalrclient/log_writer.h
    include/signalrclient/trace_level.h
    include/signalrclient/transport_type.h
    include/signalrclient/web_exception.h
    lib/signalrclient.lib

3. Remove itk:x64-osx=fail in CI baseline file.
PASSING, REMOVE FROM FAIL LIST: itk:x64-osx (/Users/vagrant/Data/work/1/s/scripts/ci.baseline.txt)

### CODE REVIEW

**Comment by PhoebeHui** [comment]
@strega-nil, could you help merge this PR?

**Review by JackBoosY — APPROVED** [review]

**Comment by BillyONeal** [comment]
Sorry, I broke this with https://github.com/microsoft/vcpkg/issues/11511

**Comment by strega-nil** [comment]
Thanks @PhoebeHui :)

Hopefully @BillyONeal can refix this next week :3

**Comment by BillyONeal** [comment]
@strega-nil https://github.com/microsoft/vcpkg/pull/11545/ should fix :)

**Pull request merged**
