### PR TITLE
[gstreamer, gst-rtsp-server] update and add port

### PR DESCRIPTION
**Pull request by mathisloge**
**Describe the pull request**

Updates gstreamer to latest 1.19.2 and adds gst-rtsp-server

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by luncliff** [comment]
Can we run the build for this PR again?
I want to check the build log for `x64-osx`. 
This port should fail because it requires Gstreamer's `bad` plugin which is not supported yet(#17394).

**Comment by dg0yt** [comment]
> Can we run the build for this PR again?
~~~
git commit --allow-empty -m "[skip actions] CI"
git push
~~~

**Comment by dg0yt** [comment]
(Or merge master, and push.)

**Comment by mathisloge** [comment]
> (Or merge master, and push.)

I've done this. But dindnt work for merged PRs

**Comment by dg0yt** [comment]
> But didnt work for merged PRs

Sorry, I didn't  pay attention... 

> This port should fail because it requires Gstreamer's bad plugin

vcpkg daily CI builds `gstreamer[core,plugins-good,plugins-ugly]:x64-osx`. Where does it require the bad plugin?
https://dev.azure.com/vcpkg/public/_build/results?buildId=66830&view=logs&j=7b75bd19-17d3-53d4-00fd-23f1a49a8ba4&t=a23dba4e-3a62-59dc-a73c-a7222676d7a4

**Comment by luncliff** [comment]
#22910 gst rtsp server was trying to find the plugin with pkg-config. It's not installed by port gstreamer. Eventually, gst rtsp server's configuration should fail.

**Pull request merged**
