### PR TITLE
[directxmesh, directxtex, directxtk, uvatlas] update ports for Dec 2022 releases

### PR DESCRIPTION
**Pull request by walbourn**
**directxmesh**, **directxtex**, **directxtk**, **directxtk12**, and **uvatlas** ports have new December 2022 releases on GitHub.

This includes updating the upstream CMake files to require CMake 3.20, support for CTest, and a Spectre-mitigated library build option.

### CODE REVIEW

**Comment by JonLiu1993** [comment]
@walbourn, Thanks for your pr, please run command "./vcpkg x-add-version --all --overwrite-version" and commit again.

**Comment by walbourn** [comment]
> @walbourn, Thanks for your pr, please run command "./vcpkg x-add-version --all --overwrite-version" and commit again.

Fixed.

**Comment by JonLiu1993** [comment]
@walbourn, this is ci error log, please take a look:
https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/82723/artifacts?artifactName=failure%20logs%20for%20x64-linux&api-version=7.0&%24format=zip

**Comment by walbourn** [comment]
Requires some upstream fixes

https://github.com/microsoft/DirectXTex/pull/299

**Comment by walbourn** [comment]
Took a number of days to get approvals with folks out for the holidays, but the two fixes are approved. Working on an update after some testing.

**Review by JonLiu1993 — APPROVED** [review]

**Comment by JonLiu1993** [comment]
Feature `spectre` tested successfully in the following triplet:
- x86-windows
- x64-windows

**Comment by Neumann-A** [comment]
Why is spectre a feature? Shouldnt that be a toolchain setting?
Does it make sense to build a single lib with mitigations and the rest not?
 Doesn't this fall into the polyfill rule?

**Comment by walbourn** [comment]
There does not seem to be a VCPKG support for building ``/Qspectre`` or not globally. The one case I found a reference to it in the vcpkg issues, the recommendation was to make it a feature and support it upstream.

**Pull request merged**
