### PR TITLE
[vcpkg-msbuild-integration] Utilize `UseDebugLibraries` for sensible normalized configuration

### PR DESCRIPTION
**Pull request by trueqbit**
Continuation of closed #9496

### CODE REVIEW

**Comment by JackBoosY** [comment]
I'd like @BillyONeal @ras0219-msft to review this PR.

**Comment by JackBoosY** [comment]
Ping @ras0219-msft again for review this.

**Comment by JackBoosY** [comment]
Tagged `reviewed` so other members will review this changes (doesn't means approved).

**Comment by ras0219-msft** [comment]
From https://github.com/microsoft/vcpkg/pull/9496#discussion_r370553770:

> A 'personal' must-have: Historically, I have a configuration named "DebugRelease", which turns off all optimizations but links to the release runtime. There's no way to override vcpkg's existing logic.

Have you tried setting the `VcpkgConfiguration` Property to `Release` or `Debug`? That is our mechanism to override vcpkg's existing logic.

**Comment by trueqbit** [comment]
> From [#9496 (comment)](https://github.com/microsoft/vcpkg/pull/9496#discussion_r370553770):
> 
> > A 'personal' must-have: Historically, I have a configuration named "DebugRelease", which turns off all optimizations but links to the release runtime. There's no way to override vcpkg's existing logic.
> 
> Have you tried setting the `VcpkgConfiguration` Property to `Release` or `Debug`? That is our mechanism to override vcpkg's existing logic.

Sorry, I don't see how your question is related to my request. Did you read what my request is all about?

**Comment by BillyONeal** [comment]
Unfortunately, I strongly agree that this is a 'righteous' change, but I don't think we can make it as proposed given that it's likely to be a breaking one.

I think we must maintain the following invariants:

* We guess Debug or Release according to Configuration. (That is maintained here because the default Debug and Release configurations set `UseDebugLibraries` appropriately)
* Users must be able to override VcpkgConfiguration, and existing overrides must be maintained. (That is broken by this change)
* The editor / property pages in the IDE need to show something reasonable, and edits there need to actually do what they say. (Also broken by this change by virtue of ignoring VcpkgConfiguration)

I have prepared a competing change https://github.com/microsoft/vcpkg/pull/26177 , can you let me know if that does what you want?

**Comment by BillyONeal** [comment]
Closed in favor of https://github.com/microsoft/vcpkg/pull/26177

**Pull request closed without merging**
