### PR TITLE
[rdkit] New port

### LINKED ISSUE #30007: [New Port Request] rdkit
Library name: rdkit

Library description: RDKit is a collection of cheminformatics and machine-learning software written in C++ and Python.

Source repository URL: https://github.com/rdkit/rdkit

Project homepage (if different from the source repository):  https://www.rdkit.org/docs/index.html

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
 - requires Boost 1.58 and is not obviously overridable

### PR DESCRIPTION
**Pull request by LuigiPagani**
Resolves https://github.com/microsoft/vcpkg/issues/30007

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [ ] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [ ] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [ ] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [ ] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by LuigiPagani** [comment]
@microsoft-github-policy-service agree [company="{your company}"]




________________________________
Da: microsoft-github-policy-service[bot] ***@***.***>
Inviato: lunedì 10 aprile 2023 00:59
A: microsoft/vcpkg ***@***.***>
Cc: Luigi Pagani ***@***.***>; Mention ***@***.***>
Oggetto: Re: [microsoft/vcpkg] Issue#3007 Create ports rdkit (PR #30742)


@LuigiPagani<https://github.com/LuigiPagani> please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.

@microsoft-github-policy-service agree [company="{your company}"]


Options:

  *   (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.

@microsoft-github-policy-service agree


  *   (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.

@microsoft-github-policy-service agree company="Microsoft"


Contributor License Agreement
Contribution License Agreement

This Contribution License Agreement (“Agreement”) is agreed to by the party signing below (“You”),
and conveys certain license rights to Microsoft Corporation and its affiliates (“Microsoft”) for Your
contributions to Microsoft open source projects. This Agreement is effective as of the latest signature
date below.

  1.  Definitions.
“Code” means the computer software code, whether in human-readable or machine-executable form,
that is delivered by You to Microsoft under this Agreement.
“Project” means any of the projects owned or managed by Microsoft and offered under a license
approved by the Open Source Initiative (www.opensource.org<http://www.opensource.org>).
“Submit” is the act of uploading, submitting, transmitting, or distributing code or other content to any
Project, including but not limited to communication on electronic mailing lists, source code control
systems, and issue tracking systems that are managed by, or on behalf of, the Project for the purpose of
discussing and improving that Project, but excluding communication that is conspicuously marked or
otherwise designated in writing by You as “Not a Submission.”
“Submission” means the Code and any other copyrightable material Submitted by You, including any
associated comments and documentation.
  2.  Your Submission. You must agree to the terms of this Agreement before making a Submission to any
Project. This Agreement covers any and all Submissions that You, now or in the future (except as
described in Section 4 below), Submit to any Project.
  3.  Originality of Work. You represent that each of Your Submissions is entirely Your original work.
Should You wish to Submit materials that are not Your original work, You may Submit them separately
to the Project if You (a) retain all copyright and license information that was in the materials as You
received them, (b) in the description accompanying Your Submission, include the phrase “Submission
containing materials of a third party:” followed by the names of the third party and any licenses or other
restrictions of which You are aware, and (c) follow any other instructions in the Project’s written
guidelines concerning Submissions.
  4.  Your Employer. References to “employer” in this Agreement include Your employer or anyone else
for whom You are acting in making Your Submission, e.g. as a contractor, vendor, or agent. If Your
Submission is made in the course of Your work for an employer or Your employer has intellectual
property rights in Your Submission by contract or applicable law, You must secure permission from Your
employer to make the Submission before signing this Agreement. In that case, the term “You” in this
Agreement will refer to You and the employer collectively. If You change employers in the future and
desire to Submit additional Submissions for the new employer, then You agree to sign a new Agreement
and secure permission from the new employer before Submitting those Submissions.
  5.  Licenses.

  *   Copyright License. You grant Microsoft, and those who receive the Submission directly or
indirectly from Microsoft, a perpetual, worldwide, non-exclusive, royalty-free, irrevocable license in the
Submission to reproduce, prepare derivative works of, publicly display, publicly perform, and distribute
the Submission and such derivative works, and to sublicense any or all of the foregoing rights to third
parties.
  *   Patent License. You grant Microsoft, and those who receive the Submission directly or
indirectly from Microsoft, a perpetual, worldwide, non-exclusive, royalty-free, irrevocable license under
Your patent claims that are necessarily infringed by the Submission or the combination of the
Submission with the Project to which it was Submitted to make, have made, use, offer to sell, sell and
import or otherwise dispose of the Submission alone or with the Project.
  *   Other Rights Reserved. Each party reserves all rights not expressly granted in this Agreement.
No additional licenses or rights whatsoever (including, without limitation, any implied licenses) are
granted by implication, exhaustion, estoppel or otherwise.

  1.  Representations and Warranties. You represent that You are legally entitled to grant the above
licenses. You represent that each of Your Submissions is entirely Your original work (except as You may
have disclosed under Section 3). You represent that You have secured permission from Your employer to
make the Submission in cases where Your Submission is made in the course of Your work for Your
employer or Your employer has intellectual property rights in Your Submission by contract or applicable
law. If You are signing this Agreement on behalf of Your employer, You represent and warrant that You
have the necessary authority to bind the listed employer to the obligations contained in this Agreement.
You are not expected to provide support for Your Submission, unless You choose to do so. UNLESS
REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING, AND EXCEPT FOR THE WARRANTIES
EXPRESSLY STATED IN SECTIONS 3, 4, AND 6, THE SUBMISSION PROVIDED UNDER THIS AGREEMENT IS
PROVIDED WITHOUT WARRANTY OF ANY KIND, INCLUDING, BUT NOT LIMITED TO, ANY WARRANTY OF
NONINFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
  2.  Notice to Microsoft. You agree to notify Microsoft in writing of any facts or circumstances of which
You later become aware that would make Your representations in this Agreement inaccurate in any
respect.
  3.  Information about Submissions. You agree that contributions to Projects and information about
contributions may be maintained indefinitely and disclosed publicly, including Your name and other
information that You submit with Your Submission.
  4.  Governing Law/Jurisdiction. This Agreement is governed by the laws of the State of Washington, and
the parties consent to exclusive jurisdiction and venue in the federal courts sitting in King County,
Washington, unless no federal subject matter jurisdiction exists, in which case the parties consent to
exclusive jurisdiction and venue in the Superior Court of King County, Washington. The parties waive all
defenses of lack of personal jurisdiction and forum non-conveniens.
  5.  Entire Agreement/Assignment. This Agreement is the entire agreement between the parties, and
supersedes any and all prior agreements, understandings or communications, written or oral, between
the parties relating to the subject matter hereof. This Agreement may be assigned by Microsoft.

**Comment by LuigiPagani** [comment]
@microsoft-github-policy-service agree



________________________________
Da: microsoft-github-policy-service[bot] ***@***.***>
Inviato: lunedì 10 aprile 2023 01:12
A: microsoft/vcpkg ***@***.***>
Cc: Luigi Pagani ***@***.***>; Mention ***@***.***>
Oggetto: Re: [microsoft/vcpkg] Issue#3007 Create ports rdkit (PR #30742)


@LuigiPagani<https://github.com/LuigiPagani> the command you issued was incorrect. Please try again.

Examples are:

@microsoft-github-policy-service agree


and

@microsoft-github-policy-service agree company="your company"

**Comment by LuigiPagani** [comment]
The checksum is set to 0, because I could not find the correct value

**Comment by jimwang118** [comment]
Please run the command: `vcpkg x-add-version portname`, and then submit the running result.

**Comment by jimwang118** [comment]
@LuigiPagani You can follow this [example](https://learn.microsoft.com/en-us/vcpkg/examples/packaging-github-repos) to complete your port. Or you can read the readme.md on the `vcpkg `home page to learn how to add a new port.

**Comment by LuigiPagani** [comment]
> Please run the command: `vcpkg x-add-version portname`, and then submit the running result.

@jimwang118 I am sorry, i tried cloning the repo and running the command in the directory where i cloned, but  i get this errror:"vcpkg : The term 'vcpkg' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path 
was included, verify that the path is correct and try again.". I am newbie, if cou can please help me

**Comment by jimwang118** [comment]
> > Please run the command: `vcpkg x-add-version portname`, and then submit the running result.
> 
> @jimwang118 I am sorry, I tried cloning the repo and running the command in the directory where I cloned, but I get this errror:"vcpkg : The term 'vcpkg' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.". I am newbie, if you can give me more detailed instructions I would be happy to contribute. Thanks a lot anyway!

Thanks for submitting your new port. You can refer to this [example](https://github.com/microsoft/vcpkg#examples) to learn how to submit a new port.

**Comment by BillyONeal** [comment]
@LuigiPagani Can you fill out the new port checklist please? I uncommented it in the description.

**Comment by LuigiPagani** [comment]
@BillyONeal I did my best to complete the port checklist. There is no copyright or usage section in the port, so I left the boxes unchecked. There is a dependency on boost, specified in the .json, but honestly I don't know what the second element of the checklist mean. Same with this:"The version database is fixed by rerunning ./vcpkg x-add-version --all and committing the result.".  I don't understand what does it mean. If it refers to the checksum I wasn't able to obtain it, and put it to 0. Thanks a lot for your help.

**Comment by BillyONeal** [comment]
Oh, I see the problem, no validation actually took place because we didn't actually try to build the new port, because it isn't named `vcpkg.json`.

build can't find vcpkg.json

>I did my best to complete the port checklist. There is no copyright or usage section in the port, so I left the boxes unchecked.

Because the port does not currently install a copyright file, it fails validation. If I rename the json to `vcpkg.json`, that says the JSON is malformed:

bad JSON

If I fix that by adding the missing comma it will then complain about there not being a SHA for the download, and I'm sure it will eventually complain about the SHA for the download not being filled in and no copyright being installed by the port.

You should try building the port yourself and get that to succeed on at least one platform before continuing.

>There is a dependency on boost, specified in the .json, but honestly I don't know what the second element of the checklist mean.

We want users who do something like `vcpkg install curl` to get the curl project, what they were probably expecting, not someone else's unrelated curl fork or similar.

In this case, https://repology.org/project/rdkit/versions seems to contain packages pointing to rdkit.org, which points to https://github.com/rdkit/rdkit, so the name appears appropriate.

>Same with this:"The version database is fixed by rerunning ./vcpkg x-add-version --all and committing the result.". I don't understand what does it mean. If it refers to the checksum I wasn't able to obtain it, and put it to 0. Thanks a lot for your help.

Once you have a port that actually builds and commit it you literally run that command:

x-add-version

**Review by jimwang118 — COMMENTED** [review]
You should rename the file `ports_rdkit_vcpkg.json` to `vcpkg.json`.

**Comment by jimwang118** [comment]
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

**Pull request closed without merging**
