### PR TITLE
[vcpkg baseline][dcmtk] Remove the leading spaces of pc file

### PR DESCRIPTION
**Pull request by Cheney-W**
Fixed [CI pipeline](https://dev.azure.com/vcpkg/public/_build/results?buildId=90705&view=results) issue:
```
dcmtk:x86-windows
dcmtk:x64-windows
dcmtk:x64-windows-static
dcmtk:x64-windows-static-md
```
```
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:141 (message):
  D:/downloads/tools/msys2/6f3fa1a12ef85a6f/mingw32/bin/pkg-config.exe
  --exists dcmtk failed with error code: 1
      ENV{PKG_CONFIG_PATH}: "D:/packages/dcmtk_x64-windows-static/lib/pkgconfig;D:/packages/dcmtk_x64-windows-static/share/pkgconfig;D:/installed/x64-windows-static/lib/pkgconfig;D:/installed/x64-windows-static/share/pkgconfig"
      output: Package dcmtk was not found in the pkg-config search path.
  Perhaps you should add the directory containing `dcmtk.pc' to the PKG_CONFIG_PATH environment variable
  Package 'dcmtk', required by 'virtual:world', not found
```
This issue occurred after the merge of PR https://github.com/microsoft/vcpkg/pull/31924. When I tried using the older version of `pkg-config`, the problem disappeared. I checked the relevant files of `dcmtk`, and there have been no recent changes to them.

Remove the leading spaces of pc file could fix this issue.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] ~~SHA512s are updated for each updated download~~
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by Neumann-A** [comment]
This is simply ignoring the problem instead of fixing it. You need to figure out why `pkgconf` fails. You need to manually run the command an enable verbose output.

**Comment by autoantwort** [comment]
Any progress?

**Comment by Cheney-W** [comment]
I have tried the options provided by `pkg-config.exe`, but they didn't give me more detailed error information.
However, I noticed that there is a space at the beginning of each line in the dcmtk.pc file. If I remove the leading space from the lines mentioned below, it fixes the error.
```
 Name: DCMTK
 Description: DICOM Toolkit (DCMTK)
 URL: https://dcmtk.org
 Version: 3.6.7
```
These spaces are from the [pc.in](https://github.com/DCMTK/dcmtk/blob/master/CMake/dcmtk.pc.in) file provided by the upstream. In order to maintain consistent formatting, I have removed the leading spaces from each line.

**Review by LilyWangLL — APPROVED** [review]

**Comment by autoantwort** [comment]
@Cheney-W Have you upstreamed the patch? :)

**Comment by Cheney-W** [comment]
> Have you upstreamed the patch? :)

Working...

**Comment by Cheney-W** [comment]
https://github.com/DCMTK/dcmtk/pull/82

**Pull request merged**
