### PR TITLE
[bdwgc] Update to v8.2.0

### PR DESCRIPTION
**Pull request by ivmai**
* Remove 001-install-libraries.patch (all changes are in upstream)
* Change REF from 0c8905e84 (old master) to v8.2.0
* Remove -Dbuild_tests=OFF which is default one
* Kill spaces at EOLn in portfile.cmake
* Update version-string, reset port-version

**Describe the pull request**

- #### What does your PR fix?  
  Fixes #...

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  <all / linux, windows, ...>, <Yes/No>

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  `Your answer`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  <Yes / I am still working on this PR>

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by ivmai** [comment]
Hello @vicroms,
Could you please help with this PR? I don't understand why it fails.

**Review by NancyLi1013 — CHANGES_REQUESTED** [review]

**Review by NancyLi1013 — CHANGES_REQUESTED** [review]

**Review by NancyLi1013 — CHANGES_REQUESTED** [review]

**Comment by ivmai** [comment]
Builds are still failing

**Comment by ivmai** [comment]
Is git-tree value correct?

**Comment by ivmai** [comment]
Still failing, help is appreciated:
```
-- Performing post-build validation
/debug/share should not exist. Please reorganize any important files, then use
    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")
The /lib/cmake folder should be merged with /debug/lib/cmake and moved to /share/bdwgc/cmake.
Please use the helper function `vcpkg_fixup_cmake_targets()`
The following cmake files were found outside /share/bdwgc. Please place cmake files in /share/bdwgc.

    /Users/vagrant/Data/packages/bdwgc_x64-osx/lib/cmake/bdwgc/BDWgcTargets.cmake
    /Users/vagrant/Data/packages/bdwgc_x64-osx/lib/cmake/bdwgc/BDWgcConfig.cmake
    /Users/vagrant/Data/packages/bdwgc_x64-osx/lib/cmake/bdwgc/BDWgcTargets-release.cmake
    /Users/vagrant/Data/packages/bdwgc_x64-osx/lib/cmake/bdwgc/BDWgcConfigVersion.cmake
    /Users/vagrant/Data/packages/bdwgc_x64-osx/debug/lib/cmake/bdwgc/BDWgcTargets.cmake
    /Users/vagrant/Data/packages/bdwgc_x64-osx/debug/lib/cmake/bdwgc/BDWgcConfig.cmake
    /Users/vagrant/Data/packages/bdwgc_x64-osx/debug/lib/cmake/bdwgc/BDWgcTargets-debug.cmake
    /Users/vagrant/Data/packages/bdwgc_x64-osx/debug/lib/cmake/bdwgc/BDWgcConfigVersion.cmake
```

**Comment by ivmai** [comment]
Still failing, help is appreciated:
```
-- Performing post-build validation
/debug/share should not exist. Please reorganize any important files, then use
    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")
The /lib/cmake folder should be merged with /debug/lib/cmake and moved to /share/bdwgc/cmake.
Please use the helper function `vcpkg_fixup_cmake_targets()`
The following cmake files were found outside /share/bdwgc. Please place cmake files in /share/bdwgc.

    /Users/vagrant/Data/packages/bdwgc_x64-osx/lib/cmake/bdwgc/BDWgcTargets.cmake
    /Users/vagrant/Data/packages/bdwgc_x64-osx/lib/cmake/bdwgc/BDWgcConfig.cmake
    /Users/vagrant/Data/packages/bdwgc_x64-osx/lib/cmake/bdwgc/BDWgcTargets-release.cmake
    /Users/vagrant/Data/packages/bdwgc_x64-osx/lib/cmake/bdwgc/BDWgcConfigVersion.cmake
    /Users/vagrant/Data/packages/bdwgc_x64-osx/debug/lib/cmake/bdwgc/BDWgcTargets.cmake
    /Users/vagrant/Data/packages/bdwgc_x64-osx/debug/lib/cmake/bdwgc/BDWgcConfig.cmake
    /Users/vagrant/Data/packages/bdwgc_x64-osx/debug/lib/cmake/bdwgc/BDWgcTargets-debug.cmake
    /Users/vagrant/Data/packages/bdwgc_x64-osx/debug/lib/cmake/bdwgc/BDWgcConfigVersion.cmake
```

**Comment by ivmai** [comment]
> The failures on arm are like this

Got it, I'll fix it.

> D:\buildtrees\bdwgc\src\v8.2.0-a140da6a73.clean\extra\msvc_dbg.c(139,14): error C2065: 'STACKFRAME': undeclared identifier [D:\buildtrees\bdwgc\arm-uwp-dbg\gc.vcxproj]

How to see this in the build logs? Probably I've overlooked it.

**Comment by ivmai** [comment]
All checks passed, waiting for the review.

**Review by NancyLi1013 — CHANGES_REQUESTED** [review]

**Review by NancyLi1013 — APPROVED** [review]

**Pull request merged**
