### PR TITLE
Added globjects

### PR DESCRIPTION
**Pull request by mattiascibien**
This pull request adds support for the globjects library by cginternals. https://github.com/cginternals/globjects

Both dynamic and static libraries are built correctly

### CODE REVIEW

**Comment by alexkaratarakis** [comment]
@mattiascibien CLA marked as ok, sorry for the confusion, CLA bot was acting weird the last few days!

**Comment by mattiascibien** [comment]
@alexkaratarakis thanks for your help. Let me know if this requires more work. Works fine for me.

**Comment by alexkaratarakis** [comment]
Looks solid!

One minor issue: there are two copies of AUTHORS, VERSION, LICENSE, README.md, on in `${CURRENT_PACKAGES_DIR}` and one in `${CURRENT_PACKAGES_DIR}\debug`. 

Can you move them (one copy) to `${CURRENT_PACKAGES_DIR}\share\globjects\` ? Also, LICENSE is the same as the copyright file which is already there, so no need to have it.

Reason: Upon installation, the files of each package are copied from the `packages\` directory over to the  `installed\x86-windows\` directory. 
Thus, files in the root of a package cannot work, because if two packages have a file like VERSION in the root directory, they will overwrite each other. The files BUILD_INFO and CONTROL are exceptions and we explicitly handle those names in the code. `${CURRENT_PACKAGES_DIR}\share\globjects\` does not have this issue, because the name `globjects` is "reserved" for this port. 

I am guessing the files are automatically placed by the build. If this cannot be suppressed, you can just rename them (or delete them if they are not needed) at the end of the portfile.

**Comment by mattiascibien** [comment]
I will have a look shortyle... Thanks for the explaination

**Comment by mattiascibien** [comment]
@alexkaratarakis can you check also the glbinding port as it seem to have the same issue?

**Comment by alexkaratarakis** [comment]
You are right, glbinding has the same issue. I will add a check for this.

**Comment by alexkaratarakis** [comment]
Thanks for the solid PR!

I have added a check for files present in the package dir and debug dir. 
I also went ahead and added code to the glbinding's and globject's portfile that removes the misplaced files so they pass the new `vcpkg` checks.

**Pull request merged**
