### PR TITLE
[tiff] support zstd compression in TIFF image files (take 2)

### PR DESCRIPTION
**Pull request by ghesketh**
https://github.com/microsoft/vcpkg/issues/16585

### CODE REVIEW

**Comment by StarGate-One** [comment]
@ghesketh /cc: @JonLiu1993 @JackBoosY 
I do not think this will work, as making these changes creates a cycle between ports:
PS D:\2017\test\> `./vcpkg install libwebp[img2webp] tiff[webp]`
>Computing installation plan...
>Cycle detected within graph at libwebp:x64-windows:
>    libwebp:x64-windows
>   tiff:x64-windows

PS D:\vcpkgMgr\2019\test> `./vcpkg depend-info libwebp[img2webp]`
>libjpeg-turbo:
>liblzma:
>zlib:
>libpng: zlib
>tiff: libjpeg-turbo, liblzma, zlib
>libwebp[img2webp, nearlossless, unicode, simd]: libjpeg-turbo, libpng, **_tiff_**

PS D:\vcpkgMgr\2019\test> `./vcpkg depend-info tiff[webp]`
>libjpeg-turbo:
>liblzma:
>libwebp[nearlossless, unicode, simd]:
>zlib:
>tiff[webp]: libjpeg-turbo, liblzma, **_libwebp_**, zlib

The ports end up depending on each other.

**Comment by JackBoosY** [comment]
@autoantwort Please consider @StarGate-One question.

**Comment by ghesketh** [comment]
> 
> 
> @autoantwort Please consider @StarGate-One question.

I reverted to remove the webp feature for tiff, although this issue seems like a design flaw; they should be able to exist as peers, rather than have one subordinate to the other.

**Comment by ghesketh** [comment]
@JackBoosY 
All checks passed on Mar 12.  Is your review still pending?

**Review by JackBoosY — APPROVED** [review]

**Pull request merged**
