### PR TITLE
[zstd] Removing de-duplication of cmake flags

### PR DESCRIPTION
**Pull request by Nemirtingas**
**Describe the pull request**

- What does your PR fix? 
Fixes cross-compilation of zstd linux to windows.

### CODE REVIEW

**Review by NancyLi1013 — COMMENTED** [review]
Could you please also update CONTROL file?

**Comment by Nemirtingas** [comment]
If I understand correctly the documentation, I just need to increase the port-version right ?
I just did it, can you check please ?

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
LGTM now, thanks for your PR.

**Comment by NancyLi1013** [comment]
Hi @Nemirtingas 
Why do you close this PR? It looks good on my side.

**Comment by Nemirtingas** [comment]
Hi, sorry, I deleted the branch locally and it deleted the remote branch. It was a mistake.

**Comment by NancyLi1013** [comment]
Is it possible to merge master to this PR to retrigger CI?

**Comment by Nemirtingas** [comment]
Is this ok to merge ?

**Comment by NancyLi1013** [comment]
LGTM now. 
I think it can be merged once CI checks have passed.

**Comment by dan-shaw** [comment]
Can we submit this patch to upstream instead?

**Comment by NancyLi1013** [comment]
I checked the source code in upstream.
This change has been merged to upstream, but not in current version.
https://github.com/facebook/zstd/commit/0fa9406ae210ed3f38b89bbff6b8f825f3365457#diff-c2115e00ec0f36ee352263ce07b253b1ffb80fc32cf0be0cf04145bdabea6221

We might consider to remove this patch in next release. What do you think? @dan-shaw

**Comment by BillyONeal** [comment]
Thanks for your contribution

**Pull request merged**
