### PR TITLE
[xsimd] Add new port

### PR DESCRIPTION
**Pull request by myd7349**
See #5140 

`xcomplex` feature depends on #5145 .

### CODE REVIEW

**Comment by zhihaoy** [comment]
If at the time this PR is merged before https://github.com/QuantStack/xsimd/pull/255/files , please make a local patch, otherwise the port can drive me crazy, thank you so much.

**Comment by Codiferous** [comment]
I've updated this PR to include the patch that @zhihaoy asked about. @zhihaoy, could you verify that this PR now includes the changes you need?

Otherwise, this PR looks good to me. All I'm waiting on now is final CI results before completing the PR! 😄

**Comment by zhihaoy** [comment]
> I've updated this PR to include the patch that @zhihaoy asked about. @zhihaoy, could you verify that this PR now includes the changes you need?

It works, thanks 👍

**Comment by Codiferous** [comment]
Okay, this change looks good to go! I'm going to merge this. Thanks for this PR!

**Pull request merged**
