### PR TITLE
Update arm64-osx baseline for 2023-12-18

### PR DESCRIPTION
**Pull request by autoantwort**
From
```
REGRESSIONS:
PASSING, REMOVE FROM FAIL LIST: bitserializer:arm64-osx (./scripts/ci.baseline.txt).
REGRESSION: coroutine:arm64-osx failed with BUILD_FAILED. If expected, add coroutine:arm64-osx=fail to ./scripts/ci.baseline.txt.
REGRESSION: cppslippi:arm64-osx failed with BUILD_FAILED. If expected, add cppslippi:arm64-osx=fail to ./scripts/ci.baseline.txt.
REGRESSION: ctbench:arm64-osx failed with BUILD_FAILED. If expected, add ctbench:arm64-osx=fail to ./scripts/ci.baseline.txt.
REGRESSION: freeglut:arm64-osx failed with BUILD_FAILED. If expected, add freeglut:arm64-osx=fail to ./scripts/ci.baseline.txt.
REGRESSION: libcoro:arm64-osx failed with BUILD_FAILED. If expected, add libcoro:arm64-osx=fail to ./scripts/ci.baseline.txt.
REGRESSION: libgwenhywfar:arm64-osx failed with BUILD_FAILED. If expected, add libgwenhywfar:arm64-osx=fail to ./scripts/ci.baseline.txt.
PASSING, REMOVE FROM FAIL LIST: ogre:arm64-osx (./scripts/ci.baseline.txt).
REGRESSION: openscap:arm64-osx failed with BUILD_FAILED. If expected, add openscap:arm64-osx=fail to ./scripts/ci.baseline.txt.
PASSING, REMOVE FROM FAIL LIST: qwt:arm64-osx (./scripts/ci.baseline.txt).
REGRESSION: xbitmaps:arm64-osx failed with BUILD_FAILED. If expected, add xbitmaps:arm64-osx=fail to ./scripts/ci.baseline.txt.
```

### CODE REVIEW

**Comment by FrankXie05** [comment]
Could you please provide the CI Pipelines link?

**Comment by autoantwort** [comment]
I run the pipeline locally on my mac since there is no official arm64-osx pipeline

**Comment by autoantwort** [comment]
Also all new entries already have corresponding entries for x64-osx

**Comment by BillyONeal** [comment]
I'm happy that these changes are mostly consistent with https://dev.azure.com/vcpkg/public/_build/results?buildId=97707&view=logs&j=ac0731cb-f2f9-5764-2e0a-a6fa8ebb4a08&t=a736d46b-7c00-5a22-ac7a-3e397096d32e ( from https://github.com/microsoft/vcpkg/pull/35665/ )

diff of results between that PR and here

**Pull request merged**
