### PR TITLE
Update VMs for April Patch Tuesday

### LINKED ISSUE #23756: vcpkg build fleet should have CMake, Ninja, and Python installed so they need not be `vcpkg fetch`'d every time

### PR DESCRIPTION
**Pull request by BillyONeal**
Should also fix https://github.com/microsoft/vcpkg/issues/23756

### CODE REVIEW

**Comment by Neumann-A** [comment]
does the oneapi installation now set the required env vars ?

**Comment by BillyONeal** [comment]
I hope so? I have no idea.

**Comment by BillyONeal** [comment]
> does the oneapi installation now set the required env vars ?

What ones do you want me to check for?

**Comment by Neumann-A** [comment]
https://github.com/microsoft/vcpkg-tool/blob/7b2fc58f4ae3f03bf04fa83241db51ed285975c7/src/vcpkg/base/system.process.cpp#L356-L359

maybe also `IFORT_COMPILER22` (don't know if the number actually stands for a year). One of the `IFORT_COMPILER` need to be set

**Comment by BillyONeal** [comment]
> https://github.com/microsoft/vcpkg-tool/blob/7b2fc58f4ae3f03bf04fa83241db51ed285975c7/src/vcpkg/base/system.process.cpp#L356-L359
> 
> maybe also `IFORT_COMPILER22` (don't know if the number actually stands for a year). One of the `IFORT_COMPILER` need to be set

image

Maybe that works?

**Comment by BillyONeal** [comment]
PASSING, REMOVE FROM FAIL LIST: azure-storage-cpp:arm64-windows

Fixed by atlmfc being completely installed for those platforms. /cc @dg0yt

REGRESSION: dxsdk-d3dx:x64-windows-static-md failed with BUILD_FAILED

Should be fixed by https://github.com/microsoft/vcpkg/commit/2437383eb0ce6e72383a30303392c385b27440f3

REGRESSION: zeroc-ice:x64-linux failed with BUILD_FAILED
REGRESSION: zeroc-ice:x64-windows-static failed with BUILD_FAILED

Probably broken by https://github.com/microsoft/vcpkg/pull/23764 ?

**Comment by BillyONeal** [comment]
Nicole confirmed with me over the shoulder that she was OK with this.

**Comment by strega-nil-ms** [comment]
REGRESSION: zeroc-ice:x64-linux failed with BUILD_FAILED
REGRESSION: zeroc-ice:x64-windows-static failed with BUILD_FAILED

should be fixed by #24169

**Pull request merged**
