### PR TITLE
[opencc] allow to build on arm

### PR DESCRIPTION
**Pull request by shenlebantongying**
Replace https://github.com/microsoft/vcpkg/pull/39366

### CODE REVIEW

**Comment by shenlebantongying** [comment]
Why the hell `x64_android` not `android`?

**Comment by data-queue** [comment]
I think you need to remove the `opencc` entry from `ci.baseline.txt`

**Comment by dg0yt** [comment]
Note https://github.com/microsoft/vcpkg/pull/39366#pullrequestreview-2126949720

**Comment by shenlebantongying** [comment]
Sorry guys, not really have energy to work on this now. Probably will try this again much later time.

**Pull request closed without merging**
