### PR TITLE
Add package for lpeg

### PR DESCRIPTION
**Pull request by TheCycoONE**
LPeg (http://www.inf.puc-rio.br/~roberto/lpeg/lpeg.html) is an expression
parsing library for lua created by the developer of lua.

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for the PR!

I think you missed a `Build-Depends: lua` :).

Is there a license available in the download itself? It's much better to get the license directly from the downloaded sources so that we won't accidentally miss a license change during an upgrade.

**Comment by TheCycoONE** [comment]
Ah yes, I'll fix that.

The copy of the license in the download is at the end of the included lpeg.html; formatted as html. They didn't include a separate copy. Seems to be Roberto's style, as  you can see https://github.com/Microsoft/vcpkg/tree/master/ports/lua had to include their own license as well.

**Comment by TheCycoONE** [comment]
Build-Depends: lua added.

**Comment by ras0219-msft** [comment]
Thanks for the PR!

The html-formatted version is still preferable to checking in a copy. Thanks for pointing out the lua port -- it probably just slipped through.

**Pull request merged**
