### PR TITLE
[ffmpeg] fix optional X11 platform dependencies

### PR DESCRIPTION
**Pull request by mcmtroffaes**
- #### What does your PR fix?  
  If X11 is not installed on the system, ffmpeg gets compiled without X11 support, however the FindFFMPEG script will still add X11 to the list of platform dependent libraries, leading to linking errors (see for instance [here](https://app.circleci.com/pipelines/github/mcmtroffaes/ffmpeg-msvc-build/67/workflows/96bdc11b-52b4-4be9-900e-fbfaf341f2be/jobs/39)). This PR fixes that issue.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  No changes, baseline not updated.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes.

### CODE REVIEW

**Comment by mcmtroffaes** [comment]
I forgot to mention this above, but whilst at it, I've also added Xext and Xv as dependent libraries, since these were listed in the [ffmpeg configure script](https://github.com/FFmpeg/FFmpeg/tree/036bb53ccc7050aad3f8f309e5650da5840da7ea#L6179).

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
Ping @cenit @Neumann-A for review this PR.

**Comment by cenit** [comment]
@mcmtroffaes is doing a wonderful job with ffmpeg port!
ok for me!

**Comment by cenit** [comment]
unrelated to this PR directly but still relevant for CI tests: opencv on uwp architectures (arm and x64) is now (again) a cascade failure. 

Again, undetected, it has fallen to this status which means that PR can break it without noticing.... when did it happen??

luckily there is no x11 on uwp platform, but in principle the problem is again there and any pr can break it without any red mark (i keep opencv under strict control also because it's an ffmpeg consuming port, so it's useful to see regressions in FindFFMPEG.cmake)...

@BillyONeal

**Comment by BillyONeal** [comment]
@cenit I still want to address that someday but having been load balanced elsewhere it's going to be a while before I have a chance to look. Starting to move things out of our wrapper powershell scripts (like analyze-test-results.ps1) and into `vcpkg ci` itself over in https://github.com/microsoft/vcpkg-tool would be helpful if anyone wants to help.

**Comment by cenit** [comment]
I will try my best if/when possible to help you on this front. Cannot promise anything

**Comment by mcmtroffaes** [comment]
Conflicts resolved.

**Review by JackBoosY — APPROVED** [review]

**Comment by strega-nil-ms** [comment]
@mcmtroffaes you'll need to merge with latest please :)

**Comment by mcmtroffaes** [comment]
Sure, merged again.

**Comment by strega-nil-ms** [comment]
Awesome, thanks @mcmtroffaes :D

**Pull request merged**
