### PR TITLE
[gdal] Update to 3.4.0, minor adjustments

### PR DESCRIPTION
**Pull request by dg0yt**
- #### What does your PR fix?  
  Updates gdal to 3.4.0 (pre-tested with 3.4.0 in #21231).
  Enables arm support except for windows (replaces #21194).
  Removes an obsolete option from the windows build.
  Fixes the wrapper for mingw.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all, no.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  yes

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
When building `gdal[*]:x64-windows-static`:
```
	cl   /nologo /MP%NUMBER_OF_PROCESSORS% /MT /EHsc /Ox /D_CRT_SECURE_NO_DEPRECATE /D_CRT_NONSTDC_NO_DEPRECATE /DNDEBUG /W3 /wd4127 /wd4251 /wd4275 /wd4786 /wd4100 /wd4245 /wd4206 /wd4351 /wd4611  /DHAVE_SSE_AT_COMPILE_TIME /DHAVE_SSSE3_AT_COMPILE_TIME -I..\port -I..\ogr -I..\gcore  -I..\alg -I..\ogr\ogrsf_frmts  -I..\gnm -I..\gnm\gnm_frmts -I..\apps /DHAVE_AVX_AT_COMPILE_TIME -I..\frmts\vrt -I..\ogr\ogrsf_frmts\geojson\libjson -I..\ogr\ogrsf_frmts\geojson -I..\ogr\ogrsf_frmts\generic -IG:/21261/vcpkg/installed/x64-windows-static/include -DHAVE_GEOS -IG:/21261/vcpkg/installed/x64-windows-static/include  -DGNM_ENABLED  -DGDAL_COMPILATION gdal_translate_bin.cpp  ..\gdal.lib  /Fegdal_translate.exe /link   
gdal_translate_bin.cpp
   Creating library gdal_translate.lib and object gdal_translate.exp
gdal.lib(ogrmysqldriver.obj) : error LNK2019: unresolved external symbol mysql_server_init referenced in function "class GDALDataset * __cdecl OGRMySQLDriverOpen(class GDALOpenInfo *)" (?OGRMySQLDriverOpen@@YAPEAVGDALDataset@@PEAVGDALOpenInfo@@@Z)
gdal.lib(ogrmysqldriver.obj) : error LNK2019: unresolved external symbol mysql_server_end referenced in function "void __cdecl OGRMySQLDriverUnload(class GDALDriver *)" (?OGRMySQLDriverUnload@@YAXPEAVGDALDriver@@@Z)
gdal.lib(ogrsqlitedatasource.obj) : error LNK2001: unresolved external symbol spatialite_version
gdal.lib(ogrsqlitedatasource.obj) : error LNK2019: unresolved external symbol spatialite_init referenced in function "int __cdecl OGRSQLiteInitOldSpatialite(void)" (?OGRSQLiteInitOldSpatialite@@YAHXZ)
gdal.lib(ogrmysqldatasource.obj) : error LNK2019: unresolved external symbol mysql_num_rows referenced in function "public: int __cdecl OGRMySQLDataSource::FetchSRSId(class OGRSpatialReference *)" (?FetchSRSId@OGRMySQLDataSource@@QEAAHPEAVOGRSpatialReference@@@Z)
gdal.lib(ogrmysqldatasource.obj) : error LNK2019: unresolved external symbol mysql_field_count referenced in function "public: virtual class OGRLayer * __cdecl OGRMySQLDataSource::ExecuteSQL(char const *,class OGRGeometry *,char const *)" (?ExecuteSQL@OGRMySQLDataSource@@UEAAPEAVOGRLayer@@PEBDPEAVOGRGeometry@@0@Z)
gdal.lib(ogrmysqldatasource.obj) : error LNK2019: unresolved external symbol mysql_affected_rows referenced in function "public: virtual class OGRLayer * __cdecl OGRMySQLDataSource::ExecuteSQL(char const *,class OGRGeometry *,char const *)" (?ExecuteSQL@OGRMySQLDataSource@@UEAAPEAVOGRLayer@@PEBDPEAVOGRGeometry@@0@Z)
gdal.lib(ogrmysqltablelayer.obj) : error LNK2001: unresolved external symbol mysql_affected_rows
gdal.lib(ogrmysqldatasource.obj) : error LNK2019: unresolved external symbol mysql_error referenced in function "public: virtual class OGRLayer * __cdecl OGRMySQLDataSource::ExecuteSQL(char const *,class OGRGeometry *,char const *)" (?ExecuteSQL@OGRMySQLDataSource@@UEAAPEAVOGRLayer@@PEBDPEAVOGRGeometry@@0@Z)
gdal.lib(ogrmysqldatasource.obj) : error LNK2019: unresolved external symbol mysql_init referenced in function "public: int __cdecl OGRMySQLDataSource::Open(char const *,char * *,int)" (?Open@OGRMySQLDataSource@@QEAAHPEBDPEAPEADH@Z)
gdal.lib(ogrmysqldatasource.obj) : error LNK2019: unresolved external symbol mysql_real_connect referenced in function "public: int __cdecl OGRMySQLDataSource::Open(char const *,char * *,int)" (?Open@OGRMySQLDataSource@@QEAAHPEBDPEAPEADH@Z)
gdal.lib(ogrmysqldatasource.obj) : error LNK2019: unresolved external symbol mysql_close referenced in function "public: virtual __cdecl OGRMySQLDataSource::~OGRMySQLDataSource(void)" (??1OGRMySQLDataSource@@UEAA@XZ)
gdal.lib(ogrmysqldatasource.obj) : error LNK2019: unresolved external symbol mysql_query referenced in function "private: virtual int __cdecl OGRMySQLDataSource::DeleteLayer(int)" (?DeleteLayer@OGRMySQLDataSource@@EEAAHH@Z)
gdal.lib(ogrmysqltablelayer.obj) : error LNK2001: unresolved external symbol mysql_query
gdal.lib(ogrmysqlresultlayer.obj) : error LNK2001: unresolved external symbol mysql_query
gdal.lib(ogrmysqllayer.obj) : error LNK2001: unresolved external symbol mysql_query
gdal.lib(ogrmysqldatasource.obj) : error LNK2019: unresolved external symbol mysql_store_result referenced in function "public: class OGRSpatialReference * __cdecl OGRMySQLDataSource::FetchSRS(int)" (?FetchSRS@OGRMySQLDataSource@@QEAAPEAVOGRSpatialReference@@H@Z)
gdal.lib(ogrmysqltablelayer.obj) : error LNK2001: unresolved external symbol mysql_store_result
gdal.lib(ogrmysqlresultlayer.obj) : error LNK2001: unresolved external symbol mysql_store_result
gdal.lib(ogrmysqllayer.obj) : error LNK2001: unresolved external symbol mysql_store_result
gdal.lib(ogrmysqldatasource.obj) : error LNK2019: unresolved external symbol mysql_use_result referenced in function "public: virtual class OGRLayer * __cdecl OGRMySQLDataSource::ExecuteSQL(char const *,class OGRGeometry *,char const *)" (?ExecuteSQL@OGRMySQLDataSource@@UEAAPEAVOGRLayer@@PEBDPEAVOGRGeometry@@0@Z)
gdal.lib(ogrmysqltablelayer.obj) : error LNK2001: unresolved external symbol mysql_use_result
gdal.lib(ogrmysqllayer.obj) : error LNK2001: unresolved external symbol mysql_use_result
gdal.lib(ogrmysqldatasource.obj) : error LNK2019: unresolved external symbol mysql_options referenced in function "public: int __cdecl OGRMySQLDataSource::Open(char const *,char * *,int)" (?Open@OGRMySQLDataSource@@QEAAHPEBDPEAPEADH@Z)
gdal.lib(ogrmysqldatasource.obj) : error LNK2019: unresolved external symbol mysql_free_result referenced in function "public: class OGRSpatialReference * __cdecl OGRMySQLDataSource::FetchSRS(int)" (?FetchSRS@OGRMySQLDataSource@@QEAAPEAVOGRSpatialReference@@H@Z)
gdal.lib(ogrmysqltablelayer.obj) : error LNK2001: unresolved external symbol mysql_free_result
gdal.lib(ogrmysqlresultlayer.obj) : error LNK2001: unresolved external symbol mysql_free_result
gdal.lib(ogrmysqllayer.obj) : error LNK2001: unresolved external symbol mysql_free_result
gdal.lib(ogrmysqldatasource.obj) : error LNK2019: unresolved external symbol mysql_fetch_row referenced in function "public: class OGRSpatialReference * __cdecl OGRMySQLDataSource::FetchSRS(int)" (?FetchSRS@OGRMySQLDataSource@@QEAAPEAVOGRSpatialReference@@H@Z)
gdal.lib(ogrmysqltablelayer.obj) : error LNK2001: unresolved external symbol mysql_fetch_row
gdal.lib(ogrmysqlresultlayer.obj) : error LNK2001: unresolved external symbol mysql_fetch_row
gdal.lib(ogrmysqllayer.obj) : error LNK2001: unresolved external symbol mysql_fetch_row
gdal.lib(ogrmysqltablelayer.obj) : error LNK2019: unresolved external symbol mysql_insert_id referenced in function "public: virtual int __cdecl OGRMySQLTableLayer::ICreateFeature(class OGRFeature *)" (?ICreateFeature@OGRMySQLTableLayer@@UEAAHPEAVOGRFeature@@@Z)
gdal.lib(ogrmysqltablelayer.obj) : error LNK2019: unresolved external symbol mysql_errno referenced in function "public: virtual int __cdecl OGRMySQLTableLayer::ICreateFeature(class OGRFeature *)" (?ICreateFeature@OGRMySQLTableLayer@@UEAAHPEAVOGRFeature@@@Z)
gdal.lib(ogrmysqltablelayer.obj) : error LNK2019: unresolved external symbol mysql_fetch_lengths referenced in function "public: virtual int __cdecl OGRMySQLTableLayer::GetExtent(class OGREnvelope *,int)" (?GetExtent@OGRMySQLTableLayer@@UEAAHPEAVOGREnvelope@@H@Z)
gdal.lib(ogrmysqllayer.obj) : error LNK2001: unresolved external symbol mysql_fetch_lengths
gdal.lib(ogrmysqlresultlayer.obj) : error LNK2019: unresolved external symbol mysql_num_fields referenced in function "public: class OGRFeatureDefn * __cdecl OGRMySQLResultLayer::ReadResultDefinition(void)" (?ReadResultDefinition@OGRMySQLResultLayer@@QEAAPEAVOGRFeatureDefn@@XZ)
gdal.lib(ogrmysqllayer.obj) : error LNK2001: unresolved external symbol mysql_num_fields
gdal.lib(ogrmysqlresultlayer.obj) : error LNK2019: unresolved external symbol mysql_field_seek referenced in function "public: class OGRFeatureDefn * __cdecl OGRMySQLResultLayer::ReadResultDefinition(void)" (?ReadResultDefinition@OGRMySQLResultLayer@@QEAAPEAVOGRFeatureDefn@@XZ)
gdal.lib(ogrmysqllayer.obj) : error LNK2001: unresolved external symbol mysql_field_seek
gdal.lib(ogrmysqlresultlayer.obj) : error LNK2019: unresolved external symbol mysql_fetch_field referenced in function "public: class OGRFeatureDefn * __cdecl OGRMySQLResultLayer::ReadResultDefinition(void)" (?ReadResultDefinition@OGRMySQLResultLayer@@QEAAPEAVOGRFeatureDefn@@XZ)
gdal.lib(ogrmysqllayer.obj) : error LNK2001: unresolved external symbol mysql_fetch_field
gdal_translate.exe : fatal error LNK1120: 23 unresolved externals
```

**Comment by dg0yt** [comment]
> gdal[*]:x64-windows-static

I think the static linkage issues existed before and are not regressions. It is just hidden from CI due to opt-in features. But I can look at it as long as I have other PRs waiting for merge. There will be merge conflicts anyway.

**Comment by dg0yt** [comment]
> > gdal[*]:x64-windows-static
> 
> I think the static linkage issues existed before and are not regressions. It is just hidden from CI due to opt-in features. But I can look at it as long as I have other PRs waiting for merge. There will be merge conflicts anyway.

Really no regressions, so please don't hold back this PR. The merge conflicts from the libgeotiff update are resolved now.

I am already working on the non-default features in separate PRs. If it helps with tracking, I can open an issue listing all gdal port sub-issues and related PRs.

**Comment by ras0219-msft** [comment]
This LGTM, thanks for the great work as always!

**Pull request merged**
