### PR TITLE
[xsimd] Update to version 9.0.1

### PR DESCRIPTION
**Pull request by bernhardmgruber**
This PR updates [xsimd](https://github.com/xtensor-stack/xsimd) to the newly released version 9.0.0.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline]
  Same triplets as before (I guess all), No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

### CODE REVIEW

**Comment by bernhardmgruber** [comment]
Hi! Do you happen to know whether the build failure is caused by my changes or a current problem with the `arrow` package? Thx!

**Comment by bernhardmgruber** [comment]
> Hi! Do you happen to know whether the build failure is caused by my changes or a current problem with the `arrow` package? Thx!

I think this is indeed an incompatibility of the `arrow` package with the new version of `xsimd`. I will have to wait with this PR until the issue is resolved in arrow. See: https://issues.apache.org/jira/browse/ARROW-17569 and https://github.com/apache/arrow/pull/14005.

**Comment by serge-sans-paille** [comment]
Hey, thanks for the packaging effort. Could your try 9.0.1 instead?

**Comment by bernhardmgruber** [comment]
> Hey, thanks for the packaging effort. Could your try 9.0.1 instead?

I changed the PR accordingly, but `arrow` is still not building successfully with this version of xsimd. Surprisingly enough, I can install arrow and xsimd successfully with this PR locally.

**Comment by bernhardmgruber** [comment]
So from the error logs in the CI when building `arrow` I see:
```
CMake Error at /agent/_work/1/s/scripts/buildsystems/vcpkg.cmake:829 (_find_package):
  Could not find a configuration file for package "xsimd" that is compatible
  with requested version "8.1.0".

  The following configuration files were considered but not accepted:

    /mnt/vcpkg-ci/installed/x64-linux/share/xsimd/xsimdConfig.cmake, version: 9.0.1
```
So it seems `arrow 9.0.0` is incompatible with `xsimd 9.0.x`. @serge-sans-paille: is this expected? If yes, then I need to wait until the next version of `arrow` is released.

**Comment by bernhardmgruber** [comment]
It seems Apache Arrow 10.0 (just released) will be compatible with xsimd 9.0.1, since it contains the relevant PR: https://github.com/apache/arrow/pull/14005. This PR can be resumed once Arrow 10.0 lands in vcpkg.

**Comment by spectre-ns** [comment]
I'm waiting for this on a separate project. With https://github.com/apache/arrow/pull/14005 merged is this one ready to go?

**Comment by bernhardmgruber** [comment]
> I'm waiting for this on a separate project. With [apache/arrow#14005](https://github.com/apache/arrow/pull/14005) merged is this one ready to go?

First, someone from the Arrow team needs to update their port. I had a quick look and there are several patches involved and the portfile is also not trivial. Therefore, I opened an issue in Arrow's issue tracker: https://issues.apache.org/jira/browse/ARROW-18249

**Comment by bernhardmgruber** [comment]
Ok, PR for Arrow is up: #27687

**Comment by bernhardmgruber** [comment]
I rebased on top of PR #27687 to see whether this PR will work after the former has been merged.

**Comment by bernhardmgruber** [comment]
> I rebased on top of PR #27687 to see whether this PR will work after the former has been merged.

Seems it will work! I marked the PR ready for review. Please only review the last commit. I will rebase the PR on top of master, once #27687 is merged.

**Comment by bernhardmgruber** [comment]
> I will rebase the PR on top of master, once https://github.com/microsoft/vcpkg/pull/27687 is merged.

Which I did now.

**Review by LilyWangLL — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the update!

**Pull request merged**
