### PR TITLE
[azure-core-cpp] Fix gcc13 compilation error

### LINKED ISSUE #34272: [azure-core] build failure with gcc 13
### Operating system

Linux (gentoo)

### Compiler

gcc 13.2.1

### Steps to reproduce the behavior

```Shell
git clone https://github.com/microsoft/vcpkg
./vcpkg/bootstrap-vcpkg.sh
/vcpkg/vcpkg install azure-core-cpp
```

### Failure logs

`Building azure-core-cpp[core,curl,http]:x64-linux...
-- Downloading https://github.com/Azure/azure-sdk-for-cpp/archive/azure-core_1.10.2.tar.gz -> Azure-azure-sdk-for-cpp-azure-core_1.10.2.tar.gz...
-- Extracting source /hey1/users/normg/vcpkg/downloads/Azure-azure-sdk-for-cpp-azure-core_1.10.2.tar.gz
-- Using source at /hey1/users/normg/vcpkg/buildtrees/azure-core-cpp/src/ore_1.10.2-d563a045e8.clean
-- Found external ninja('1.11.1').
-- Configuring x64-linux
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: /hey1/users/normg/vcpkg/downloads/tools/cmake-3.27.1-linux/cmake-3.27.1-linux-x86_64/bin/cmake --build . --config Debug --target install -- -v -j9
    Working Directory: /hey1/users/normg/vcpkg/buildtrees/azure-core-cpp/x64-linux-dbg
    See logs for more information:
      /hey1/users/normg/vcpkg/buildtrees/azure-core-cpp/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/azure-core-cpp/portfile.cmake:33 (vcpkg_cmake_install)
  scripts/ports.cmake:168 (include)

error: building azure-core-cpp:x64-linux failed with: BUILD_FAILED
Elapsed time to handle azure-core-cpp:x64-linux: 2.8 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+azure-core-cpp
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[azure-core-cpp]+Build+error&body=Copy+issue+bo
[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/12810977/install-x64-linux-dbg-out.log)
dy+from+%2Fhey1%2Fusers%2Fnorm`

### Additional context

azure-core fails to build on gentoo linux with gcc 13. Builds on the same host with gcc 12 succeed. Adding this line:

`#include <stdint.h>`

to these two files

`sdk/core/azure-core/inc/azure/core/base64.hpp`
`sdk/core/azure-core/inc/azure/core/uuid.hpp`

fixes the problem.

### PR DESCRIPTION
**Pull request by jimwang118**
Fixes https://github.com/microsoft/vcpkg/issues/34272
`/vcpkg/buildtrees/azure-core-cpp/src/ore_1.10.2-d563a045e8.clean/_/_/_/inc/azure/core/base64.hpp:42:55: error: ‘uint8_t’ was not declared in this scope`
Add `stdint.h` header file, fixed via PR [5031](https://github.com/Azure/azure-sdk-for-cpp/pull/5031) upstream.

- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] ~~SHA512s are updated for each updated download~~
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

Usage test pass with following triplets:

```
x64-linux
```

### CODE REVIEW

**Comment by BillyONeal** [comment]
@LarryOsterman FYI

**Comment by LarryOsterman** [comment]
Due to the way that the Azure SDK for C++ publishes its packages, all changes made to the vcpkg repository will be discarded when the Azure SDK for C++ is next released. As such, making changes to fix issues in the vcpkg repository are always ephemeral and should probably be avoided.

The Azure SDK is located at https://github.com/Azure/azure-sdk-for-cpp and we welcome community contributions like this one. 

FWIW, we currently have an outstanding issue regarding this specific change: https://github.com/Azure/azure-sdk-for-cpp/issues/5007.

**Comment by jimwang118** [comment]
> Due to the way that the Azure SDK for C++ publishes its packages, all changes made to the vcpkg repository will be discarded when the Azure SDK for C++ is next released. As such, making changes to fix issues in the vcpkg repository are always ephemeral and should probably be avoided.
> 
> The Azure SDK is located at https://github.com/Azure/azure-sdk-for-cpp and we welcome community contributions like this one.
> 
> FWIW, we currently have an outstanding issue regarding this specific change: [Azure/azure-sdk-for-cpp#5007](https://github.com/Azure/azure-sdk-for-cpp/issues/5007).

Okay, then I will mark this PR as draft, wait for you to fix it, and then update it.

**Comment by LarryOsterman** [comment]
> > Due to the way that the Azure SDK for C++ publishes its packages, all changes made to the vcpkg repository will be discarded when the Azure SDK for C++ is next released. As such, making changes to fix issues in the vcpkg repository are always ephemeral and should probably be avoided.
> > The Azure SDK is located at https://github.com/Azure/azure-sdk-for-cpp and we welcome community contributions like this one.
> > FWIW, we currently have an outstanding issue regarding this specific change: [Azure/azure-sdk-for-cpp#5007](https://github.com/Azure/azure-sdk-for-cpp/issues/5007).
> 
> Okay, then I will mark this PR as draft, wait for you to fix it, and then update it.

So I took a look at the issue. The base64.hpp file already includes `cstdint` which is supposed to include stdint.h. 

The version of cstdint on my machine (in /usr/include/x86_64-linux-gnu/c++/11) does include stdint.h. Are you using a different C++ runtime library?

**Comment by BillyONeal** [comment]
> EDIT: I think I figured it out. cstdint only defines the `std::uint8_t` type (and friends), stdint.h defines the `uint8_t` types in the global namespace.

Right, `<cfoo>` means "use `std::foo`", `<foo.h>` means "use `::foo`".

**Comment by LarryOsterman** [comment]
> > EDIT: I think I figured it out. cstdint only defines the `std::uint8_t` type (and friends), stdint.h defines the `uint8_t` types in the global namespace.
> 
> Right, `<cfoo>` means "use `std::foo`", `<foo.h>` means "use `::foo`".

What complicates this is that many (most?) implementations of cstdint include stdint.h (including the version of the CRT used in our CI pipelines). The version of cstdint that the reporters are using do not. That is why even after selecting clang-13 (and clang-15) we didn't see a problem.

**Review by LilyWangLL — DISMISSED** [review]

**Comment by data-queue** [comment]
Can you fix merge conflicts? And I think we can use the upstream patch since it merged

**Comment by jimwang118** [comment]
> Can you fix merge conflicts? And I think we can use the upstream patch since it merged

OK, I'll resolve the merge conflict and fix it with the upstream patch.

**Review by LilyWangLL — APPROVED** [review]

**Pull request merged**
