### PR TITLE
Enable to overwrite utf-8 character set in triplet

### PR DESCRIPTION
**Pull request by martin-s**
For Visual Studio 2013 the utf8 character encoding isn't available and causes compiler warnings. This fix enables to set a character encoding in a triplet file in order to avoid these warnings.
`set(VCPKG_CHARACTER_SET /D_MBCS)`

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for the PR!

Since this is a property of the toolset, it doesn't seem like a per-triplet option is the right fit. I've pushed an implementation that _always_ removes /utf-8 for v120 to `dev/roschuma/v120-utf8` -- could you take a look at let me know if that solves the issue?

**Comment by KindDragon** [comment]
But it would be nice if we could remove the flag `/utf-8` for some libraries, such as DevIL

**Comment by martin-s** [comment]
I have no objection against the new PR as for both solutions only cmake files are changed. I'm not fully sure whether not setting any charset for VS2013 is ok. What's the default in that case? Otherwise make `/D_MBCS `the default.

**Comment by ras0219-msft** [comment]
`/utf-8` should have no effect on `/D_UNICODE` or `/D_MBCS` -- it simply says to interpret the _input source files_ as utf8 instead of as the local codepage. Whether you get `W` or `A` versions of the Windows APIs is orthogonal.

@KindDragon In those circumstances, we would need to replace the switch with a different source charset. Something like `/utf-8` -> `/source-charset:latin1 /execution-charset:utf8`. If this is a pervasive problem, then I agree having a flag in `vcpkg_configure_cmake()` makes sense, however if it is extremely limited (just DevIL, for example), then I think patching is probably still the best approach.

**Comment by ras0219-msft** [comment]
I've merged `dev/roschuma/v120-utf8` to master, which should resolve this issue. Thanks!

**Pull request closed without merging**
