### PR TITLE
[ngtcp2,wolfssl] Add features

### PR DESCRIPTION
**Pull request by talregev**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [x] The "supports" clause reflects platforms that may be fixed by this new version.
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

wolfssl:
- quic feature

ngtcp2:
- wolfssl feature
- gnutls feature

### CODE REVIEW

**Comment by jimwang118** [comment]
All features passed with following triplet:

```
x64-linux
```

**Comment by dg0yt** [comment]
> ngtcp2:
> 
> * wolfssl feature
> * gnutls feature

AFAIU these are alternative TLS backends for the optional "ngtcp2 crypto helper library".
(And just two of them. OpenSSL would be available via "Picotls with OpenSSL as crypto backend".)

What happens with both features enabled?

**Comment by talregev** [comment]
> > ngtcp2:
> > 
> > * wolfssl feature
> > * gnutls feature
> 
> AFAIU these are alternative TLS backends for the optional "ngtcp2 crypto helper library". (And just two of them. OpenSSL would be available via "Picotls with OpenSSL as crypto backend".)
> 
> What happens with both features enabled?

from ngtcp2 readme file in github:

> In order to make TLS stack integration less painful, we provide a crypto helper library which offers the basic crypto operations.

ngtcp2 bring basic operation for tls but curl for http3 use other tls like wolfssl,gnutls and more with ngtcp2.
You can install both feature alongside, also when you compile it with curl http3, and choose only one backend, it working. I test it on wsl2, linux with wolfssl http3 backend, and ngtcp2 both feature enable.

**Review by data-queue — APPROVED** [review]

**Comment by dg0yt** [comment]
> You can install both feature alongside.

And both will be linked? Or one is selected? And curl will add another one?

**Pull request merged**
