### PR TITLE
Update cmake to 3.15.2

### PR DESCRIPTION
**Pull request by NancyLi1013**
Update CMake tools to latest release.

### CODE REVIEW

**Comment by Neumann-A** [comment]
vtk regression related to #7519

**Comment by vicroms** [comment]
Pushed changes to fix flaky ports that are holding back this update.

**Comment by cbezault** [comment]
Looks like more flaky ports...

**Comment by PhoebeHui** [comment]
CMake 3.16.2 is avaliable for download, we might consider to update to that revision.
https://blog.kitware.com/cmake-3-16-2-available-for-download/

**Comment by NancyLi1013** [comment]
Since someone has submitted a PR #9531 to update cmake to 3.16.2.
So I close this PR now.

**Pull request closed without merging**
