### PR TITLE
[vcpkg/scripts] Update meson to 0.57.2

### PR DESCRIPTION
**Pull request by Neumann-A**
lets see what updating meson breaks ....

### CODE REVIEW

**Comment by Neumann-A** [comment]
@JackBoosY : Another marble issue? (x64-windows). The libheif regression is also funny (Missing Install destination for a target).

**Comment by JackBoosY** [comment]
It was fixed.

**Comment by JackBoosY** [comment]
```
[20/1446] cmd.exe /C "cd /D D:\buildtrees\marble\x64-windows-dbg\src\lib\marble && D:\downloads\tools\cmake-3.20.1-windows\cmake-3.20.1-windows-i386\bin\cmake.exe -E cmake_autogen D:/buildtrees/marble/x64-windows-dbg/src/lib/marble/CMakeFiles/marblewidget_autogen.dir/AutogenInfo.json Debug && D:\downloads\tools\cmake-3.20.1-windows\cmake-3.20.1-windows-i386\bin\cmake.exe -E touch D:/buildtrees/marble/x64-windows-dbg/src/lib/marble/marblewidget_autogen/timestamp && D:\downloads\tools\cmake-3.20.1-windows\cmake-3.20.1-windows-i386\bin\cmake.exe -E cmake_transform_depfile Ninja gccdepfile D:/buildtrees/marble/src/d820856286-99e796b78b.clean D:/buildtrees/marble/src/d820856286-99e796b78b.clean/src/lib/marble D:/buildtrees/marble/x64-windows-dbg D:/buildtrees/marble/x64-windows-dbg/src/lib/marble D:/buildtrees/marble/x64-windows-dbg/src/lib/marble/marblewidget_autogen/deps D:/buildtrees/marble/x64-windows-dbg/CMakeFiles/d/7e69118ea51bedc9ac29ab8cd6afbfcb51edf10f7570534052e17d7c683c5aed.d"
FAILED: src/lib/marble/marblewidget_autogen/timestamp 
cmd.exe /C "cd /D D:\buildtrees\marble\x64-windows-dbg\src\lib\marble && D:\downloads\tools\cmake-3.20.1-windows\cmake-3.20.1-windows-i386\bin\cmake.exe -E cmake_autogen D:/buildtrees/marble/x64-windows-dbg/src/lib/marble/CMakeFiles/marblewidget_autogen.dir/AutogenInfo.json Debug && D:\downloads\tools\cmake-3.20.1-windows\cmake-3.20.1-windows-i386\bin\cmake.exe -E touch D:/buildtrees/marble/x64-windows-dbg/src/lib/marble/marblewidget_autogen/timestamp && D:\downloads\tools\cmake-3.20.1-windows\cmake-3.20.1-windows-i386\bin\cmake.exe -E cmake_transform_depfile Ninja gccdepfile D:/buildtrees/marble/src/d820856286-99e796b78b.clean D:/buildtrees/marble/src/d820856286-99e796b78b.clean/src/lib/marble D:/buildtrees/marble/x64-windows-dbg D:/buildtrees/marble/x64-windows-dbg/src/lib/marble D:/buildtrees/marble/x64-windows-dbg/src/lib/marble/marblewidget_autogen/deps D:/buildtrees/marble/x64-windows-dbg/CMakeFiles/d/7e69118ea51bedc9ac29ab8cd6afbfcb51edf10f7570534052e17d7c683c5aed.d"
ninja: build stopped: subcommand failed.
```

**Comment by Neumann-A** [comment]
I'll close this until 0.58 is out since it does not seem to break anything mayor.

**Pull request closed without merging**
