### PR TITLE
[suitesparse] Copy shared library to build directory.

### PR DESCRIPTION
**Pull request by vtraag**
This PR fixes issue #14203 by copying the shared suitesparse library to the build directory.

### CODE REVIEW

**Comment by PhoebeHui** [comment]
@vtraag, thanks for the PR! I have updated the version, could you sign the CLA?

**Comment by PhoebeHui** [comment]
Ping @vtraag...

**Comment by vtraag** [comment]
Closed, see https://github.com/microsoft/vcpkg/issues/14203#issuecomment-786630284 for more information.

**Pull request closed without merging**
