### PR TITLE
[giflib]fix compile error in x64-uwp

### PR DESCRIPTION
**Pull request by JackBoosY**
Installing giflib will prompt some functions to be unsafe, so I added macro **-D_CRT_SECURE_NO_WARNINGS** and replaced some safe functions to avoid compilation failure.

See #3043.

### CODE REVIEW

**Comment by JackBoosY** [comment]
All failed triplet cannot perform the patch correctly, this should be a bug with vcpkg.

**Comment by JackBoosY** [comment]
@Rastaban I have modified code, please check it out. Thank you.

**Comment by Rastaban** [comment]
Resolved merge conflict

**Comment by qis** [comment]
@JackBoosY @Rastaban Could you please revert this change? It breaks compilation on Linux. Tested on Ubuntu 18.04.2 LTS.

**Comment by gerwalk** [comment]
I'm also getting this error in the x86-uwp version.

**Pull request merged**
