### PR TITLE
[DPP] Adding a new port

### PR DESCRIPTION
**Pull request by braindigitalis**
**Describe the pull request**

#### What does your PR fix?
Adds support for DPP, a lightweight high performance C++ discord library used in multiple large popular Discord bots

#### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
 linux, windows, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  `Yes, lib has vendored depencies which are fetched from vcpkg during a vcpkg build`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

### CODE REVIEW

**Comment by braindigitalis** [comment]
still draft while i fix some upstream vendor dep issues

**Comment by JonLiu1993** [comment]
@braindigitalis, Thanks for your pr, looks the ci tested on x64-linux triplet and x64-uwp triplet, 
could you please take a look:
[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/8460757/install-x64-linux-dbg-out.log)
[install-x64-uwp-dbg-out.log](https://github.com/microsoft/vcpkg/files/8460759/install-x64-uwp-dbg-out.log)

**Comment by braindigitalis** [comment]
thanks  it isn't supposed to build on uwp, there's some things id like to address before I mark this pr as ready for review.

**Comment by braindigitalis** [comment]
going to resubmit a newer fixed verison of this and will close this pr

**Comment by JonLiu1993** [comment]
Duplicate of #25949

**Pull request closed without merging**
