### PR TITLE
[lilv] Add new port

### LINKED ISSUE #13211: [New Port Request] lilv
Library name:
lilv

Library description:
From the project homepage:
> Lilv is a C library (with Python bindings) for simple use of LV2 plugins in applications, which includes utilities for investigating installed LV2 plugins.

On LV2:
> LV2 is an extensible open standard for audio plugins. LV2 has a simple core interface, which is accompanied by extensions that add more advanced functionality.

Source repository URL:
https://gitlab.com/lv2/lilv

Project homepage (if different from the source repository):
https://drobilla.net/software/lilv

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
This library has four dependencies, lv2, serd, sord, and sratom, none of which are currently in vcpkg. I am ready to open pull requests to add these, and can open individual port request issues if desired, but thought it best to ensure the end goal was acceptable first.
The build system (and that of the dependencies) is waf-based (actually a slightly modified version, [autowaf](https://gitlab.com/drobilla/autowaf)). I have rewritten enough of it in CMake to build what I need, but this may be worth revisiting if something like #1312 is merged.

### PR DESCRIPTION
**Pull request by DomClark**
**Describe the pull request**

- What does your PR fix?
  Fixes #13211.

- Which triplets are supported/not supported? Have you updated the CI baseline?
  UWP is not supported. I have tested `x86-windows`, `x64-windows`, and `x64-windows-static`; I would expect others to work too. The CI baseline has not been updated.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes.

### CODE REVIEW

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
Is this PR ready for review now?

**Comment by NancyLi1013** [comment]
LGTM now. Thanks for your PR @DomClark.

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Comment by Be-ing** [comment]
@DomClark have you contacted upstream about merging the CMakeLists.txt?

**Comment by DomClark** [comment]
@Be-ing I haven't, no. It relies on CMake versions of other libraries in the LV2 family, some of which are rather incomplete (I only implemented what I required), and don't follow upstream's packaging guidelines exactly (due to vcpkg's different requirements and aims). If you think doing so could be beneficial, though, by all means feel free to contact them.

**Comment by Be-ing** [comment]
I did [contact upstream](https://gitlab.com/lv2/lilv/-/issues/6). He is working on a new Meson build system for the LV2 libraries, so when that is released, the custom CMakeLists.txts in vcpkg can be dropped.

**Comment by DomClark** [comment]
Thanks - that's good to hear.

**Pull request merged**
