### PR TITLE
[akali] Remove port

### PR DESCRIPTION
**Pull request by JonLiu1993**
Deprecated port.
The author of `winsoft666/akali` decides to delete this repository because it involves sensitive data. 
There is no replacement repository or link, so we remove this port from vcpkg.

### CODE REVIEW

**Comment by dg0yt** [comment]
There is no point in leaving an empty port: Downstream usage will fail. Just remove from `ports` and `versions/baseline.json`, as was done with port xalan-c.

**Comment by dg0yt** [comment]
I didn't mention `versions/a-/akali.json` because I think it should be left for those who do have source assets and pin the version.

**Comment by BillyONeal** [comment]
Thanks!

**Comment by BillyONeal** [comment]
> I didn't mention `versions/a-/akali.json` because I think it should be left for those who do have source assets and pin the version.

That's right. Baseline removals, version DB stays.

**Pull request merged**
