### PR TITLE
[libpng]Fix copy libpngConfig.cmake.

### PR DESCRIPTION
**Pull request by JackBoosY**
Related: #8241 #1627.

### CODE REVIEW

**Comment by cenit** [comment]
Just out of curiosity, is there any issue related? The two variables should point to the same folder...

**Comment by JackBoosY** [comment]
@cenit Well, any port linked to libpng will cause this problem.
In fact, I tried to fix the issue of linking debug dependencies in vtk, but it is complicated.

**Comment by JackBoosY** [comment]
`C:\VS2017\Stable\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(425,5): error MSB8040: Spectre-mitigated libraries are required for this project. Install them from the Visual Studio installer (Individual components tab) for any toolsets and architectures being used. Learn more: https://aka.ms/Ofhn4c [C:\vsts\_work\2\s\buildtrees\3fd\x86-windows-all\v2.6.2-c8e9e110eb\3FD\3FD.vcxproj]`
@dan-shaw  Could you have a look?

**Comment by JackBoosY** [comment]
@dan-shaw 
```
The following files are already installed in /Users/vagrant/azure_agent/_work/3/s/installed/x64-osx and are in conflict with vxl:x64-osx

Installed by qt5-location:x64-osx
    lib/libclipper.a
```

It seems that `vxl` conflicts with `qt5-location`.

**Comment by dan-shaw** [comment]
@JackBoosY This seems to be a problem with the CI system. This issue should be fixed when those changes get merged in.

**Comment by JackBoosY** [comment]
Duplicate fix with #8716.

**Pull request closed without merging**
