### PR TITLE
[opencv4] Fix build failure when dnn feature is not enabled

### PR DESCRIPTION
**Pull request by WentsingNee**
Given the following manifest (when `dnn` feature is not included):

```json
"dependencies": [
  {
    "name": "opencv4",
    "version>=": "4.8.0#18",
    "default-features": false,
    "features": [
      "png"
    ]
  }
]
```

it failed and here is what `vcpkg/buildtrees/opencv4/config-x64-linux-out.log` said:

```
...
CMake Error at /home/peter/open-source/git/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package):
  Could not find a package configuration file provided by "flatbuffers" with
  any of the following names:

    flatbuffersConfig.cmake
    flatbuffers-config.cmake

  Add the installation prefix of "flatbuffers" to CMAKE_PREFIX_PATH or set
  "flatbuffers_DIR" to a directory containing one of the above files.  If
  "flatbuffers" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:759 (find_package)
...
```

This problem is introduced by [commit 6d2c9714](https://github.com/microsoft/vcpkg/commit/6d2c97145828d01040d654c136831b16cc43e4a3) contributed by @jimwang118

In the patch `vcpkg/ports/opencv4/0023-fix-no-flatbuffers.patch`, Jim disabled the procedure of `Flatbuffers` detection introduced by the previous patch `0017-fix-flatbuffers.patch`, which has correctly fixed the `flatbuffers`-related issues.

```patch
...
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -756,7 +756,7 @@ include(cmake/OpenCVFindLibsVideo.cmake)
 include(cmake/OpenCVFindLibsPerf.cmake)
 include(cmake/OpenCVFindLAPACK.cmake)
 include(cmake/OpenCVFindProtobuf.cmake)
-include(cmake/OpenCVDetectFlatbuffers.cmake)
+find_package(flatbuffers CONFIG REQUIRED)
...
```

In `vcpkg/ports/opencv4/vcpkg.json` we can see, `flatbuffers` is only the dependency of feature `dnn`:

```json
  "dependencies": [
...
    "dnn": {
      "description": "Enable dnn module",
      "dependencies": [
        "flatbuffers",
        {
          "name": "flatbuffers",
          "host": true,
          "default-features": false
        },
        "protobuf"
      ]
    },
...
```

and when `dnn` is not enabled, it broke down at the line `find_package(flatbuffers CONFIG REQUIRED)`

And this change is unnecessary either:

```patch
-  list(APPEND libs ocv.3rdparty.flatbuffers)
+  list(APPEND libs flatbuffers::flatbuffers)
```

Thus, we'd better to revert those changes.

### CODE REVIEW

**Comment by jimwang118** [comment]
I tested it locally without installing the dnn feature, and the error you mentioned did not occur.
Installation command:
vcpkg install opencv4[core,png]
result:
image

**Comment by WentsingNee** [comment]
> I tested it locally without installing the dnn feature, and the error you mentioned did not occur. Installation command: vcpkg install opencv4[core,png] result: image


port version 15 is no problem. Bug is introduced since port version 16 you committed
image

image

**Comment by jimwang118** [comment]
I suggest adding constraints to the patch that determine when using dnn to find flatbuffers through the patch. Removing the patch may trigger the original CI error.
...
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -756,7 +756,7 @@ include(cmake/OpenCVFindLibsVideo.cmake)
 include(cmake/OpenCVFindLibsPerf.cmake)
 include(cmake/OpenCVFindLAPACK.cmake)
 include(cmake/OpenCVFindProtobuf.cmake)
-include(cmake/OpenCVDetectFlatbuffers.cmake)
if(BUILD_opencv_dnn)
+find_package(flatbuffers CONFIG REQUIRED)
endif()
...

**Comment by WentsingNee** [comment]
But I don't think that it's a good way to use `find_package(flatbuffers)` instead of `include(cmake/OpenCVDetectFlatbuffers.cmake)` because their script is better to handle with some corner cases.

Eg.

```cmake
if(BUILD_opencv_dnn)
```

We shouldn't assume that `dnn` feature depends on `flatbuffers` or there is **ONLY** `dnn` feature depends on `flatbuffers` (i.e. if in the future, `dnn` is not depend on `flatbuffers` anymore or there is an another feature depends on `flatbuffers`), it will trigger errors again.

**Comment by WentsingNee** [comment]
May I have ask why CI failed if we remove the patch? Does it related to something like caches?

**Comment by WentsingNee** [comment]
image

I' ve seen that there are some commits removed the patches. It doesn't seem that vcpkg project disallow to remove port's patches

**Comment by WentsingNee** [comment]
And your patches is the last one applied, remove it will not cause other patches applied failed

**Comment by jimwang118** [comment]
> And your patches is the last one applied, remove it will not cause other patches applied failed

Ok, I will test it locally and if there are no problems, I will mark it as reviewed.

**Comment by jimwang118** [comment]
Compile test pass with following triplets:
```
x64-windows
x64-windows-static
```

**Pull request merged**
