### PR TITLE
[libwebp] update to 1.2.3

### PR DESCRIPTION
**Pull request by Neumann-A**

### CODE REVIEW

**Review by JonLiu1993 — DISMISSED** [review]

**Comment by JonLiu1993** [comment]
All features are tested successfull in the following triplet:
- x86-windows
- x64-windows
- x64-windows-static

**Comment by JonLiu1993** [comment]
@Neumann-A, looks the ci test failed in x64-osx, this is error log, please take a look:

/Users/vagrant/Data/buildtrees/x264/install-x64-osx-dbg-err.log
````
install: mkdir /Users/vagrant/Data/packages/x264_x64-osx/Users/vagrant/Data: File exists
make: *** [install-lib-dev] Error 71
make: *** Waiting for unfinished jobs....
```` 

/Users/vagrant/Data/buildtrees/qtbase/install-x64-osx-dbg-out.log
````
clang: error: unable to execute command: Abort trap: 6
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: x86_64-apple-darwin21.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
clang: note: diagnostic msg: 
````

**Comment by Neumann-A** [comment]
@JonLiu1993 https://github.com/microsoft/vcpkg/pull/25959/commits/cf2199bc4648ab69740b0511fe02519fce9407a3 was green. and the only thing you did was to add a license. As such sich is probably a spurious CI issue after a lot of PR were merged into master. The first problem is probably because CI didn't clean correctly (or parallelism), the second issue is a compiler crash I can do little about. 
What is the right action here? -> simply retry the CI run and hope for the best.

**Review by JavierMatosD — APPROVED** [review]

**Review by JavierMatosD — APPROVED** [review]

**Comment by JavierMatosD** [comment]
Thanks!

**Pull request merged**
