### PR TITLE
Added port brynet - A C++ cross platform high performance TCP network library.

### PR DESCRIPTION
**Pull request by IronsDu**
Brynet is a cross platform high performance TCP network library.

Support SSL(depend openssl), HTTP, WebSocket.

It can be used in Visual C++ 2013+(2015,2017...) on Windows (32/64-bit).

### CODE REVIEW

**Comment by sdcb** [comment]
Looks cool

**Comment by ras0219-msft** [comment]
Thanks for the PR! Looks like a great library :)

I switched the portfile while merging to use `vcpkg_from_github()`, which also enables users to get the latest version from your master branch by installing like:
```
>vcpkg install brynet --head
```

**Comment by IronsDu** [comment]
Thanks for your update and merge.

**Comment by IronsDu** [comment]
@ras0219-msft , Can't  get the latest version from master by `>vcpkg install brynet --head `.
Can you help me to fix it ? Thanks.

**Comment by IronsDu** [comment]
It's ok of  `vcpkg install brynet --head`

**Pull request merged**
