### PR TITLE
[brotli] add iOS support

### PR DESCRIPTION
**Pull request by jwtowner**
This adds support for building brotli on iOS triplets.

For iOS the `BUNDLE DESTINATION` parameter must be specified when calling `install` in `CMakeLists.txt`, and so this PR sets it to the same path as the `RUNTIME DESTINATION`.

Triplets that now compile with this change:

arm64-ios
x64-ios

### CODE REVIEW

**Comment by jwtowner** [comment]
I take it the failure in x86_windows due to `freeopcua` is unrelated?

**Comment by NancyLi1013** [comment]
Yes, `freeopcua ` failed with insufficient disk space:
```
CMakeFiles\opcuaprotocol.dir/manifest.res" failed (exit code 1201) with the following output:
LINK : fatal error LNK1201: error writing to program database 'D:\buildtrees\freeopcua\x86-windows-dbg\opcuaprotocold.pdb'; check for insufficient disk space, invalid path, or insufficient privilege
ninja: build stopped: subcommand failed.
```

**Comment by NancyLi1013** [comment]
@strega-nil 
Could you please help take a look? Thanks.

**Comment by NancyLi1013** [comment]
The failure disappeared after rerun.

LGTM now, thanks for your PR @jwtowner.

**Review by NancyLi1013 — APPROVED** [review]

**Comment by ras0219-msft** [comment]
Thanks for the PR!

**Pull request merged**
