### PR TITLE
[nlohmann-json] Update to 3.5.0

### PR DESCRIPTION
**Pull request by evpobr**
* Update to 3.5.0
* Use upstream CMake script to configure and provide targets

### CODE REVIEW

**Comment by evpobr** [comment]
@ras0219-msft , don't merge, bugs found. Package config module is installed in wrong place (`installed\x64-windows\share\nlohmann-json\nlohmann_json\nlohmann_jsonConfig.cmake `).

Not the only dublicated nested `directory is problem. Port name is `nlohmann-json`, but project name is `nlohmann_json.` So package config module will not be found. Is there a way to override directory, where package config modules are installed with `Vcpkg`?

**Comment by myd7349** [comment]
It seems that there is another PR: #5033 which has already done the first part.

**Comment by evpobr** [comment]
Ok, i think it's better to close this for now.

**Comment by myd7349** [comment]
@evpobr The CMake support is really nice, however. Looking forward to seeing this PR being opened again. :)

**Comment by myd7349** [comment]
Hi, @evpobr . PR #5033 has been merged. Could you rebase and reopen your PR?

**Comment by evpobr** [comment]
Still don't know how to fix:

> Port name is `nlohmann-json`, but project name is `nlohmann_json.`

`find_package(nlohmann_json)` ([official way](https://github.com/nlohmann/json#external)) fails, because package config module is installed under `nlohmann_json` directory (port name).

**Comment by ras0219-msft** [comment]
I think this upgrade was taken care of as part of #5258. Let me know if there's anything left here and thanks for the PR!

**Pull request closed without merging**
