### PR TITLE
[curl] Update to 7.86.0

### PR DESCRIPTION
**Pull request by Znurre**
**Update curl to version 7.86.0**

- #### What does your PR fix?
Bumps the version of curl to 7.86.0 and adds WebSockets as a feature

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
No, unchanged.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
I think so. I have done my best to conform, but this is my first contribution, so please be kind :)

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by Znurre** [comment]
@microsoft-github-policy-service agree

**Comment by Znurre** [comment]
I notice that multiple workflows failed. Looking at the logs, I can see that curl (which I updated) is seemingly passing. Are the failures unrelated to my changes? Or are they caused by other packages which are dependent on curl, which for some reason fail due to my changes?

Any advice would be appreciated! :slightly_smiling_face:

**Comment by dg0yt** [comment]
Your PR looks good. However, upstream changes (in CURL) may have changed usage requirements. This often shows up only when a downstream port builds executables (resolving all static libs). 
You can download the failure logs from CI, the download is a little bit hidden behind a three-dots menu on the right side of a failure log asset, visible only when hovering the line of interest:
https://dev.azure.com/vcpkg/public/_build/results?buildId=80791&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by Osyotr** [comment]
You can download failure logs to see what exactly has failed.

image

**Comment by Znurre** [comment]
Thanks a lot for the advice! I will investigate.

**Comment by FrankXie05** [comment]
Thank you very much for submitting this PR :). It seems to be an error of `LNK2019`. 
You can view the corresponding error causes and solutions through https://learn.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk2019?view=msvc-160.
````
FAILED: azure-core.dll azure-core.lib 
cmd.exe /C "cmd.exe /C "D:\downloads\tools\cmake-3.24.0-windows\cmake-3.24.0-windows-i386\bin\cmake.exe -E __create_def D:\buildtrees\azure-core-cpp\x86-windows-dbg\CMakeFiles\azure-core.dir\.\exports.def D:\buildtrees\azure-core-cpp\x86-windows-dbg\CMakeFiles\azure-core.dir\.\exports.def.objs && cd D:\buildtrees\azure-core-cpp\x86-windows-dbg" && D:\downloads\tools\cmake-3.24.0-windows\cmake-3.24.0-windows-i386\bin\cmake.exe -E vs_link_dll --intdir=CMakeFiles\azure-core.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MICROS~1\2022\ENTERP~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x86\link.exe  CMakeFiles\azure-core.dir\src\http\curl\curl.cpp.obj CMakeFiles\azure-core.dir\src\http\winhttp\win_http_transport.cpp.obj CMakeFiles\azure-core.dir\src\azure_assert.cpp.obj CMakeFiles\azure-core.dir\src\base64.cpp.obj CMakeFiles\azure-core.dir\src\context.cpp.obj CMakeFiles\azure-core.dir\src\cryptography\md5.cpp.obj CMakeFiles\azure-core.dir\src\cryptography\sha_hash.cpp.obj CMakeFiles\azure-core.dir\src\datetime.cpp.obj CMakeFiles\azure-core.dir\src\environment.cpp.obj CMakeFiles\azure-core.dir\src\environment_log_level_listener.cpp.obj CMakeFiles\azure-core.dir\src\etag.cpp.obj CMakeFiles\azure-core.dir\src\exception.cpp.obj CMakeFiles\azure-core.dir\src\http\bearer_token_authentication_policy.cpp.obj CMakeFiles\azure-core.dir\src\http\http.cpp.obj CMakeFiles\azure-core.dir\src\http\http_sanitizer.cpp.obj CMakeFiles\azure-core.dir\src\http\log_policy.cpp.obj CMakeFiles\azure-core.dir\src\http\policy.cpp.obj CMakeFiles\azure-core.dir\src\http\raw_response.cpp.obj CMakeFiles\azure-core.dir\src\http\request.cpp.obj CMakeFiles\azure-core.dir\src\http\request_activity_policy.cpp.obj CMakeFiles\azure-core.dir\src\http\retry_policy.cpp.obj CMakeFiles\azure-core.dir\src\http\telemetry_policy.cpp.obj CMakeFiles\azure-core.dir\src\http\transport_policy.cpp.obj CMakeFiles\azure-core.dir\src\http\url.cpp.obj CMakeFiles\azure-core.dir\src\http\user_agent.cpp.obj CMakeFiles\azure-core.dir\src\io\body_stream.cpp.obj CMakeFiles\azure-core.dir\src\io\random_access_file_body_stream.cpp.obj CMakeFiles\azure-core.dir\src\logger.cpp.obj CMakeFiles\azure-core.dir\src\operation_status.cpp.obj CMakeFiles\azure-core.dir\src\strings.cpp.obj CMakeFiles\azure-core.dir\src\tracing\tracing.cpp.obj CMakeFiles\azure-core.dir\src\uuid.cpp.obj  /out:azure-core.dll /implib:azure-core.lib /pdb:azure-core.pdb /dll /version:0.0 /machine:X86 /nologo    /debug /INCREMENTAL  /DEF:CMakeFiles\azure-core.dir\.\exports.def  bcrypt.lib  crypt32.lib  D:\installed\x86-windows\debug\lib\libcurl-d.lib  winhttp.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib  && cd ."
LINK Pass 1: command "C:\PROGRA~1\MICROS~1\2022\ENTERP~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x86\link.exe CMakeFiles\azure-core.dir\src\http\curl\curl.cpp.obj CMakeFiles\azure-core.dir\src\http\winhttp\win_http_transport.cpp.obj CMakeFiles\azure-core.dir\src\azure_assert.cpp.obj CMakeFiles\azure-core.dir\src\base64.cpp.obj CMakeFiles\azure-core.dir\src\context.cpp.obj CMakeFiles\azure-core.dir\src\cryptography\md5.cpp.obj CMakeFiles\azure-core.dir\src\cryptography\sha_hash.cpp.obj CMakeFiles\azure-core.dir\src\datetime.cpp.obj CMakeFiles\azure-core.dir\src\environment.cpp.obj CMakeFiles\azure-core.dir\src\environment_log_level_listener.cpp.obj CMakeFiles\azure-core.dir\src\etag.cpp.obj CMakeFiles\azure-core.dir\src\exception.cpp.obj CMakeFiles\azure-core.dir\src\http\bearer_token_authentication_policy.cpp.obj CMakeFiles\azure-core.dir\src\http\http.cpp.obj CMakeFiles\azure-core.dir\src\http\http_sanitizer.cpp.obj CMakeFiles\azure-core.dir\src\http\log_policy.cpp.obj CMakeFiles\azure-core.dir\src\http\policy.cpp.obj CMakeFiles\azure-core.dir\src\http\raw_response.cpp.obj CMakeFiles\azure-core.dir\src\http\request.cpp.obj CMakeFiles\azure-core.dir\src\http\request_activity_policy.cpp.obj CMakeFiles\azure-core.dir\src\http\retry_policy.cpp.obj CMakeFiles\azure-core.dir\src\http\telemetry_policy.cpp.obj CMakeFiles\azure-core.dir\src\http\transport_policy.cpp.obj CMakeFiles\azure-core.dir\src\http\url.cpp.obj CMakeFiles\azure-core.dir\src\http\user_agent.cpp.obj CMakeFiles\azure-core.dir\src\io\body_stream.cpp.obj CMakeFiles\azure-core.dir\src\io\random_access_file_body_stream.cpp.obj CMakeFiles\azure-core.dir\src\logger.cpp.obj CMakeFiles\azure-core.dir\src\operation_status.cpp.obj CMakeFiles\azure-core.dir\src\strings.cpp.obj CMakeFiles\azure-core.dir\src\tracing\tracing.cpp.obj CMakeFiles\azure-core.dir\src\uuid.cpp.obj /out:azure-core.dll /implib:azure-core.lib /pdb:azure-core.pdb /dll /version:0.0 /machine:X86 /nologo /debug /INCREMENTAL /DEF:CMakeFiles\azure-core.dir\.\exports.def bcrypt.lib crypt32.lib D:\installed\x86-windows\debug\lib\libcurl-d.lib winhttp.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\azure-core.dir/intermediate.manifest CMakeFiles\azure-core.dir/manifest.res" failed (exit code 1120) with the following output:
   Creating library azure-core.lib and object azure-core.exp
curl.cpp.obj : error LNK2019: unresolved external symbol __imp__setsockopt@20 referenced in function __catch$?ParseChunkSize@CurlSession@Http@Core@Azure@@AAEXABVContext@34@@Z$0
curl.cpp.obj : error LNK2019: unresolved external symbol __imp__shutdown@8 referenced in function "public: virtual void __thiscall Azure::Core::Http::CurlConnection::Shutdown(void)" (?Shutdown@CurlConnection@Http@Core@Azure@@UAEXXZ)
curl.cpp.obj : error LNK2019: unresolved external symbol __imp__WSAIoctl@36 referenced in function __catch$?ParseChunkSize@CurlSession@Http@Core@Azure@@AAEXABVContext@34@@Z$0
curl.cpp.obj : error LNK2019: unresolved external symbol __imp__WSAPoll@12 referenced in function __catch$?ParseChunkSize@CurlSession@Http@Core@Azure@@AAEXABVContext@34@@Z$0
azure-core.dll : fatal error LNK1120: 4 unresolved externals
ninja: build stopped: subcommand failed
````
Log from: https://dev.azure.com/vcpkg/public/_build/results?buildId=80791&view=artifacts&pathAsName=false&type=publishedArtifacts

[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/10000290/install-x86-windows-dbg-out.log)

**Comment by Znurre** [comment]
Thank you @FrankXie05 !

After spending a couple of hours on this though, I can't say that I am any wiser.

The OpenSSL problem I can reproduce on my Linux machine, but I have no idea what is causing it.
I can see that `ssl` is a default feature of `curl`, and for Linux (and macOS) it makes sense that curl would link against OpenSSL.
However, I do not understand why `aws-sdk-cpp` specifically would have a problem with that, and I don't see any obvious upstream curl change that might have caused the issue.
The linking problem on Windows, I cannot even reproduce locally on my Windows machine.

I don't know how to proceed with this, and I think I need to admit defeat on this one. My cmake and vcpkg skills are simply not enough to proceed with this.

Should I close the PR, or do you want to keep it open for the case that someone else wants to take over?

**Comment by FrankXie05** [comment]
@Znurre Never mind, I will take over this PR. :)

**Comment by BillyONeal** [comment]
I am not sure why check_cxx_source_runs seems to hate private dependencies; aws sdk's CMake is ... strange. I think the break was caused by https://github.com/curl/curl/pull/9125 . I pushed a change that works around the problem by locking the selected curl features, thus eliminating the need for check_cxx_source_runs in the first place.

**Comment by BillyONeal** [comment]
Also, I am super *not* confident that https://github.com/microsoft/vcpkg/pull/27778/commits/98e3bbb306c4c1a2b816d6811c576980e5916c49 is correct; I would appreciate other reviwers.

**Review by BillyONeal — APPROVED** [review]

**Review by FrankXie05 — APPROVED** [review]

**Comment by JavierMatosD** [comment]
Thank you!

**Pull request merged**
