### PR TITLE
[libgeotiff] support linux build

### PR DESCRIPTION
**Pull request by miurahr**

### CODE REVIEW

**Comment by alexkaratarakis** [comment]
This fixes Linux, but breaks Windows.
I think patch 003 needs to be amended to discern between Windows and Linux.

**Comment by miurahr** [comment]
@alexkaratarakis Thanks for good point.
We may need a generator expression such as
`$<$<PLATFORM_ID:linux>:m>`  that generate 'm' when linux oherwise nothing. 

Does this work for you?
```
SET(CMAKE_REQUIRED_LIBRARIES ${TIFF_LIBRARIES} ${ZLIB_LIBRARIES} ${JPEG_LIBRARIES} ${LIBLZMA_LIBRARIES} $<$<NOT:$<PLATFORM_ID:Windows>>:m> )
```

**Comment by alexkaratarakis** [comment]
This doesn't seem to work. According to the [documentation](https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html):
`
Generator expressions are allowed in the context of many target properties, such as LINK_LIBRARIES, INCLUDE_DIRECTORIES, COMPILE_DEFINITIONS and others. They may also be used when using commands to populate those properties, such as target_link_libraries(), target_include_directories(), target_compile_definitions() and others.
`

It probably doesn't work for SET. I think branching with:
```
if(NOT VCPKG_CMAKE_SYSTEM_NAME OR VCPKG_CMAKE_SYSTEM_NAME STREQUAL "WindowsStore")
```

would work though.

**Comment by ras0219-msft** [comment]
I have a branch[1] attempting to address the root cause of this issue -- `find_package(TIFF)` does not properly bring in dependencies in static mode.

We can fix this by adding a wrapper for TIFF that will get pulled in around the underlying `FindTIFF` provided by CMake which adds in all the needed static dependencies.

Sorry this has taken so long to process!

[1] https://github.com/Microsoft/vcpkg/tree/dev/roschuma/3843

**Pull request merged**
