### PR TITLE
[vcpkg] fix --x-feature flag

### PR DESCRIPTION
**Pull request by strega-nil**
~~still to do: add e2e tests~~

### CODE REVIEW

**Review by ras0219-msft — APPROVED** [review]
LGTM pending testing

**Review by past-due — APPROVED** [review]
Tested - fixes the issue 👍

(for reference: this was broken in d9351c9c3f1e17593c5fe078218c5d07cf746922)

**Comment by strega-nil** [comment]
@ras0219 I've added e2e tests; can you take a look?

**Comment by strega-nil** [comment]
@ras0219 this looks like a problem with `create_versioned_install_plan`; can you look?

**Comment by strega-nil** [comment]
Closed in lieu of microsoft/vcpkg-tool#1

**Pull request closed without merging**
