### PR TITLE
[vcpkg] Fix more cases of semicolon mishandling in "scripts" - follow-up to PR #12926

### PR DESCRIPTION
**Pull request by jgehw**
- also fix semicolons in `vcpgk_execute_required_process` (follow-up of #12926)
- add optional output and error variable to `vcpgk_execute_required_process`
- apply fix to gdal port (currently quotes lists to prevent expansion)
- this PR is a spin-off of PR #13028 to separate changes in `vcpgk_execute_required_process`

### CODE REVIEW

**Review by JackBoosY — CHANGES_REQUESTED** [review]
Please bump the port version. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).

**Comment by JackBoosY** [comment]
@BillyONeal @Neumann-A Could you please review this PR?

Thanks.

**Comment by jgehw** [comment]
I don't see any relation between remaining CI failures and code changes of this PR. Over the last 3 CI runs, errors appeared and disappeared without any code changes in this PR, just by re-running and/or merging master. In particular:

last but 2nd run:
x86-windows: ois osgearth
x64-windows: plib osgearth
x64-windows-static: openxr-loader qt5-tools
x64-uwp: vcpkg-gfortran protobuf
arm-windows: protobuf boost*
x64-linux: openxr-loader qt5-tools

last but 1st run:
x86-windows: ogre sqlcipher
x64-windows: ogre parmetis qt5-scxml qt5-sensors qt5-serialport sqlcipher
x64-windows-static: ogre openxr-loader
x64-linux: openxr-loader

last run:
x86-windows: sqlcipher
x64-windows: apr sqlcipher
x64-windows-static: ogre
x64-linux: apr

sqlcipher is currently broken also in master (Error: There are invalid field types in the CONTROL or manifest file of C:\work\tools\vcpkg\ports\sqlcipher\vcpkg.json). apr has transient error (SSL connection while downloading).

**Comment by JackBoosY** [comment]
sqlcipher:
```
couldn't read file ";TCLVERSION=90;ORIGINAL_SRC=D:\buildtrees\sqlcipher\src\v4.4.0-36c69edad7.clean;EXT_FEATURE_FLAGS=-DSQLITE_TEMP_STORE=2": no such file or directory
```
I think that's related to your changes.

**Comment by jgehw** [comment]
> sqlcipher:
> 
> ```
> couldn't read file ";TCLVERSION=90;ORIGINAL_SRC=D:\buildtrees\sqlcipher\src\v4.4.0-36c69edad7.clean;EXT_FEATURE_FLAGS=-DSQLITE_TEMP_STORE=2": no such file or directory
> ```
> 
> I think that's related to your changes.

Sorry, you're right. It turned out that the error I was seeing on my machine (Error: There are invalid field types in the CONTROL or manifest file) was hiding the error you quoted. After I rebuilt vcpkg.exe, I was able to reproduce the issue. I'll push a fix.

**Comment by jgehw** [comment]
just re-running CI lead to these changes in CI failures:

previous run:
x86-windows: sqlcipher
x64-windows: apr sqlcipher
x64-windows-static: ogre
x64-linux: apr

after re-running:
x86-windows: sqlcipher osgearth
x64-windows: sqlcipher osgearth
x64-windows-static: plib ogre
arm-uwp: anyrpc

I then fixed sqlcipher to work wit my changes of this PR. Now all tests succeed. Thus, apr, ogre, osgearth, anyrpc were unrelated and transient issue.

Anyway, the main thing is: is working now :-) So, this PR is ready for final review and merge.

**Review by JackBoosY — APPROVED** [review]

**Comment by jgehw** [comment]
@JackBoosY BTW: The code you reviewed included the port version bump you requested. I don't find an option to acknowledge that your requested changes are done. How to get rid of the status "changes requested"?

**Comment by jgehw** [comment]
Merging master caused these new CI failures:
x86-windows: akali, libpqxx, moos-core, osgearth
x64-windows-static: ogre, qt5-tools
arm64-windows: libpqxx

Looking through the logs, it's mostly some file or lib not found. I observed similar transient issues on my local machine, where the culprit was the anti-virus scanner locking a file while scanning and thus making it unavailable to the build process. As
- ogre, osgearth, qt5-tools already had transient issues appearing and disappearing without code changes during the history of this PR (see above),
- libpqxx was updated in master but I don't see any changes in the diff being affected by this PR,
- akali, moos-core had no relevant code changes since previous merge of master,

can you please re-run all failed CI to see which of them are not transient errors?

**Comment by ianier** [comment]
> Looking through the logs, it's mostly some file or lib not found. I observed similar transient issues on my local machine, where the culprit was the anti-virus scanner locking a file while scanning and thus making it unavailable to the build process. 

As someone interested in getting this PR through to ultimately get tensorflow-cc back to life, I can see that this is much more painful than it should be. Please don’t give up, @jgehw, the world is counting on you :-)

**Comment by BillyONeal** [comment]
Unfortunately the nature of this PR causes the entire binary cache to be invalidated, so that PR build tries to build everything, so you're subject to the union of build flakiness of all ~1350 ports and their associated servers. We are always working to make things more reliable and things are better now than they were a few months ago, but still not "rock solid". @ras0219 / @ras0219-msft is working on caching package sources rather than just outputs which will help a lot since it will mean we don't break because some server is down.

**Comment by jgehw** [comment]
Today's CI failures:
- libpqxx (x86-windows, x64-windows, arm64-windows) "dl.lib" not found - seems to be an issue with the build environment, it's compiling fine on my machine
- qt5-multimedia (x86-windows, x64-windows, x64-windows-static) network issues while download -> transient error
- freetds (x64-windows) permission denied on temp file -> transient error
- ogre (x64-windows-static) compile error "definition of dllimport static data member not allowed" - not reproducable on my machine - either transient or specific to build environment

@BillyONeal @JackBoosY can you please re-run failed CIs? (I can't, insufficient permissions)

**Comment by BillyONeal** [comment]
We talked about this today and resolved that for "rebuild the world from contributors" changes like this we will merge them upon manual review that all the failures match a previous CI nightly build (currently https://dev.azure.com/vcpkg/public/_build?definitionId=29 )

**Comment by BillyONeal** [comment]
Well I was going to merge this anyway with potential failures but it passed now, yay! :D :D :D :D

**Comment by BillyONeal** [comment]
Thanks so much for your contribution and dealing with our PR / CI system issues :D

**Pull request merged**
