### PR TITLE
[vcpkg toolchain] Fix paths with special characters

### LINKED ISSUE #24447: Mac: applocal.py post-build step fails if executable name contains parenthesis
**Describe the bug**
Call to applocal.py causes an error after building an executable with a file name containing parenthesis. Might also be relevant if the executable contains spaces, but have not tested.

I think that the problem might be solved by adding qoutes in the call, "\\"$<TARGET_FILE:${target_name}>\\"", to the target file name (possibly also to the installed):
```
add_custom_command(TARGET "${target_name}" POST_BUILD
                    COMMAND python "${Z_VCPKG_TOOLCHAIN_DIR}/osx/applocal.py"
                        "$<TARGET_FILE:${target_name}>"
                        "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}$<$<CONFIG:Debug>:/debug>"
                    )
```
https://github.com/microsoft/vcpkg/blob/16ebf7b9b83ea79020ed6caa39ea3301e7890de1/scripts/buildsystems/vcpkg.cmake#L591

So, suggested fix:
```
add_custom_command(TARGET "${target_name}" POST_BUILD
                    COMMAND python "${Z_VCPKG_TOOLCHAIN_DIR}/osx/applocal.py"
                        "\"$<TARGET_FILE:${target_name}>\""
                        "\"${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}$<$<CONFIG:Debug>:/debug>\""
                    )
```

A possible workaround to this problem is to turn of VCPKG_APPLOCAL_DEPS:
VCPKG_APPLOCAL_DEPS=OFF

**Environment**
- OS: OSX

**To Reproduce**
Use example CMake code in a project using vcpkg:
```
project(ParenthesisTestProject)
add_executable("Executable (T)" MACOSX_BUNDLE ...)
```
2. Configure and build
3. See error

**Failure logs**
https://github.com/SciVis/VisualNeuro/runs/6180628365?check_suite_focus=true
Relevant extract from the logs:
```
FAILED: bin/VisualNeuro Helper (GPU).app/Contents/MacOS/VisualNeuro Helper (GPU) 
: && /Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -O3 -DNDEBUG -arch x86_64 -isysroot /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk -mmacosx-version-min=10.11 -Wl,-search_paths_first -Wl,-headerpad_max_install_names  modules/webbrowser/webhelper/CMakeFiles/cef_inviwo_helper_gpu.dir/app_switches.cpp.o modules/webbrowser/webhelper/CMakeFiles/cef_inviwo_helper_gpu.dir/webotherapp.cpp.o modules/webbrowser/webhelper/CMakeFiles/cef_inviwo_helper_gpu.dir/webrendererapp.cpp.o modules/webbrowser/webhelper/CMakeFiles/cef_inviwo_helper_gpu.dir/cefprocesshelper.cpp.o -o "bin/VisualNeuro Helper (GPU).app/Contents/MacOS/VisualNeuro Helper (GPU)"  lib/libcef_dll_wrapper.a  -lpthread  -framework Cocoa  -framework AppKit  ext/cef/cef_binary_93.1.14+gf38ce34+chromium-93.0.4577.82_macosx64/Release/cef_sandbox.a && cd /Users/runner/work/VisualNeuro/VisualNeuro/build/modules/webbrowser/webhelper && python **/Users/runner/work/VisualNeuro/VisualNeuro/vcpkg/scripts/buildsystems/osx/applocal.py /Users/runner/work/VisualNeuro/VisualNeuro/build/bin/VisualNeuro\ Helper\ (GPU).app/Contents/MacOS/VisualNeuro\ Helper\ (GPU) /Users/runner/work/VisualNeuro/VisualNeuro/build/vcpkg_installed/x64-osx** && cd /Users/runner/work/VisualNeuro/VisualNeuro/build/modules/webbrowser/webhelper && /usr/local/Cellar/cmake/3.23.1/bin/cmake -E copy_directory "/Users/runner/work/VisualNeuro/VisualNeuro/build/bin/VisualNeuro Helper (GPU).app" "/Users/runner/work/VisualNeuro/VisualNeuro/build/bin/VisualNeuro Helper (GPU).app/../VisualNeuro.app/Contents/Frameworks/VisualNeuro Helper (GPU).app"
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `: && /Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -O3 -DNDEBUG -arch x86_64 -isysroot /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk -mmacosx-version-min=10.11 -Wl,-search_paths_first -Wl,-headerpad_max_install_names  modules/webbrowser/webhelper/CMakeFiles/cef_inviwo_helper_gpu.dir/app_switches.cpp.o modules/webbrowser/webhelper/CMakeFiles/cef_inviwo_helper_gpu.dir/webotherapp.cpp.o modules/webbrowser/webhelper/CMakeFiles/cef_inviwo_helper_gpu.dir/webrendererapp.cpp.o modules/webbrowser/webhelper/CMakeFiles/cef_inviwo_helper_gpu.dir/cefprocesshelper.cpp.o -o "bin/VisualNeuro Helper (GPU).app/Contents/MacOS/VisualNeuro Helper (GPU)"  lib/libcef_dll_wrapper.a  -lpthread  -framework Cocoa  -framework AppKit  ext/cef/cef_binary_93.1.14+gf38ce34+chromium-93.0.4577.82_macosx64/Release/cef_sandbox.a && cd /Users/runner/work/VisualNeuro/VisualNeuro/build/modules/webbrowser/webhelper && python /Users/runner/work/VisualNeuro/VisualNeuro/vcpkg/scripts/buildsystems/osx/applocal.py /Users/runner/work/VisualNeuro/VisualNeuro/build/bin/VisualNeuro\ Helper\ (GPU).app/Contents/MacOS/VisualNeuro\ Helper\ (GPU) /Users/runner/work/VisualNeuro/VisualNeuro/build/vcpkg_installed/x64-osx && cd /Users/runner/work/VisualNeuro/VisualNeuro/build/modules/webbrowser/webhelper && /usr/local/Cellar/cmake/3.23.1/bin/cmake -E copy_directory "/Users/runner/work/VisualNeuro/VisualNeuro/build/bin/VisualNeuro Helper (GPU).app" "/Users/runner/work/VisualNeuro/VisualNeuro/build/bin/VisualNeuro Helper (GPU).app/../VisualNeuro.app/Contents/Frameworks/VisualNeuro Helper (GPU).app"'
```
**Additional context**
On Mac, the chromium embedded framework (CEF) uses 3 different applications according to following structure:
```
"\<app name\> + Helper<type>", e.g. Inviwo Helper (GPU)
```
So, I think that any project using CEF and vcpkg will have this issue on Mac.

### PR DESCRIPTION
**Pull request by JackBoosY**
When using `execute_process` and `add_custom_command`, the path included in the command line with special characters will break the execution process.

Fixes #24447.

### CODE REVIEW

**Comment by JackBoosY** [comment]
@ResearchDaniel Can you please test this PR?

Thanks.

**Comment by dg0yt** [comment]
This change doesn't make sense. Fortunately, it failed early.

**Comment by ResearchDaniel** [comment]
I think that the quotes need to be escaped inside of the other quotes? For example:
`"\”${Z_VCPKG_BOOTSTRAP_SCRIPT}\"”`

**Comment by JackBoosY** [comment]
@ResearchDaniel I think now it's okay?

**Review by LilyWangLL — APPROVED** [review]

**Comment by ResearchDaniel** [comment]
> @ResearchDaniel I think now it's okay?

tested your branch and it seems to work.

**Comment by BillyONeal** [comment]
> This change doesn't make sense. Fortunately, it failed early.

Do you think the current one makes sense?

**Comment by dg0yt** [comment]
> > This change doesn't make sense. Fortunately, it failed early.
> 
> Do you think the current one makes sense?

Well, now it is what I proposed, and what CMake doc recommends.
(What didn't make sense was removing quotes which were needed for CMake syntax.)

**Comment by BillyONeal** [comment]
> Well, now it is what I proposed, and what CMake doc recommends.

Sorry, I didn't see such a proposal.

**Comment by BillyONeal** [comment]
@JackBoosY Thanks for the fix :)

**Pull request merged**
