### PR TITLE
[libressl,vcpkg-ci-libressl] Test and fix exported config and wrapper

### LINKED ISSUE #40915: [libressl] port bug: find_package(openssl) is detect openssl libs outside vcpkg, in github ci action, instead libressl port
### Operating system

windows latest github ci

### Compiler

msvc

### Steps to reproduce the behavior

On github action ci with windows latest runner. run this command:
```
  vcpkg install vcpkg-ci-libressl '--triplet=x64-windows' --overlay-ports=$VCPKG_INSTALLATION_ROOT\\scripts\\test_ports
```

### Failure logs
https://github.com/talregev/curl/actions/runs/10859242578/job/30138314640?pr=22

### Additional context

I run libressl test port on github action windows ci.
https://github.com/talregev/curl/actions/runs/10859242578/job/30138314640?pr=22
and I download the logs.

[windows_logs_7696dc6fb70eff5b0a5079d78b9818f4dc486861.zip](https://github.com/user-attachments/files/17000835/windows_logs_7696dc6fb70eff5b0a5079d78b9818f4dc486861.zip)

I reproduce the problem: 
[config-x64-windows-out.log](https://github.com/user-attachments/files/17000833/config-x64-windows-out.log)

```
-- Found OpenSSL: optimized;C:/vcpkg/installed/x64-windows/lib/crypto.lib;debug;C:/Program Files/OpenSSL/lib/VC/libcrypto64MDd.lib (found version "2.0.0")
-- OpenSSL::SSL IMPORTED_LOCATION_DEBUG: C:/Program Files/OpenSSL/lib/VC/libssl64MDd.lib
CMake Error at CMakeLists.txt:19 (message):
  OpenSSL::SSL IMPORTED_LOCATION_DEBUG is not from vcpkg.
```

find_package(openssl) is detect openssl libs outside vcpkg, in github ci action.

As discuss here, is a libressl port bug.
https://github.com/microsoft/vcpkg/pull/40922#issuecomment-2362310018

> suggests a bug in the LibreSSL port and should not be worked around in every downstream port that wants to consume LibreSSL in this way.

### PR DESCRIPTION
**Pull request by dg0yt**
"LibreSSL provides much of the OpenSSL 1.1 API. Incompatibilities between the projects exist and are unavoidable since both evolve with different goals and priorities."

This PR:
- fixes the installed **LibreSSL** CMake config.
- installs pkg-config files for MSVC.
- installs a wrapper for `FindOpenSSL.cmake`. 
  Fixes https://github.com/microsoft/vcpkg/issues/40915.
- adds OpenSSL and LibreSSL API compile and link tests to the test port.

### CODE REVIEW

**Comment by dg0yt** [comment]
I :heart: test ports.

**Comment by talregev** [comment]
@dg0yt Thank you for your hard work! I also test this branch on github action ci with windows latest, and it working.
This PR is solve this issue:
fix https://github.com/microsoft/vcpkg/issues/40915.

You can add this.

**Comment by talregev** [comment]
@dg0yt Thank you for adding the issue.
@Mengna-Li Can you review this PR?

**Comment by talregev** [comment]
@JavierMatosD Can you review the PR?

**Comment by Mengna-Li** [comment]
All feature tested on the following triplets:

- x64-windows
- x64-windows-static
- x86-windows

**Review by Mengna-Li — APPROVED** [review]

**Pull request merged**
