### PR TITLE
[ffmpeg] Fix static linking on Windows, FindFFMPEG

### PR DESCRIPTION
**Pull request by mkroening**
This adds zlib as dependency to make it possible to find in FindFFMPEG.cmake.
Also FFmpeg likes to autodetect zlib for additional features on compilation.
This removes the check for stdint.h, as it is included since MSVC 2010 and does not always find it.
To enable static linking on windows, bcript had to be added:
```cmd
avutil.lib(random_seed.o) : error LNK2019: unresolved external symbol _BCryptOpenAlgorithmProvider@16 referenced in function _av_get_random_seed
avutil.lib(random_seed.o) : error LNK2019: unresolved external symbol _BCryptCloseAlgorithmProvider@8 referenced in function _av_get_random_seed
avutil.lib(random_seed.o) : error LNK2019: unresolved external symbol _BCryptGenRandom@16 referenced in function _av_get_random_seed
```

### CODE REVIEW

**Comment by mwkroening** [comment]
First I tried to upgrade to 4.2 as well but that failed on Windows on ARM: [old vcpkg-Linux-PR](https://dev.azure.com/vcpkg/public/_build/results?buildId=9594)

This should now succeed and then be ready for review.

**Review by cbezault — COMMENTED** [review]
It's fine since the ffmpeg port already provides a cmake module but just as a note ports should be providing cmake config files not modules.

**Comment by mwkroening** [comment]
Thanks for the quick reply!

So you mean a `FFMPEGConfig.cmake.in` (like in [CMake docs - Package Configuration File](https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html#package-configuration-file) using [CMakePackageConfigHelpers](https://cmake.org/cmake/help/latest/module/CMakePackageConfigHelpers.html)) would be better than the `FindFFMPEG.cmake`?

Is there any documentation about this regarding vcpkg? What are the benefits? Would it be worth to switch? Is there a particular port worth looking at regarding best practices?

**Comment by cenit** [comment]
> ports should be providing cmake config files not modules.

? But ffmpeg is not built with CMake... like many other ports! In this case providing a config file would be just hard coding values with no real benefits, while in this case we can just enhance the module step by step and maybe push for it upstream... (to ffmpeg or to cmake)

**Pull request merged**
