### PR TITLE
Fixes building libevent with linkages other than static

### LINKED ISSUE #11680: [libevent] build failure dynamic linkage
**Host Environment**
- OS: Ubuntu 20.04
- Compiler: gcc v9.3.0

**To Reproduce**
First, define a triplet for dynamic linkage.
`./vcpkg install libevent:x64-linux-shared`

**Failure logs** 
There should be no empty directories in /home/aaron/dev/vcpkg/packages/libevent_x64-linux-shared
The following empty directories were found:

    /home/aaron/dev/vcpkg/packages/libevent_x64-linux-shared/bin

If a directory should be populated but is not, this might indicate an error in the portfile.
If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:

    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/a/dir" "${CURRENT_PACKAGES_DIR}/some/other/dir")

Found 1 error(s). Please correct the portfile:
    /home/aaron/dev/vcpkg/ports/libevent/portfile.cmake
-- Performing post-build validation done
Error: Building package libevent:x64-linux-shared failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libevent:x64-linux-shared
  Vcpkg version: 2020.02.04-unknownhash

Additionally, attach any relevant sections from the log files above.

**Additional context**
This can be resolved in the portfile.cmake by removing the linkage check prior to removing bin directories.

### PR DESCRIPTION
**Pull request by andreabedini**
Remove linkage check prior to removing bin directories.

**Describe the pull request**

- What does your PR fix? Fixes #

Fixes #11680

- Which triplets are supported/not supported? Have you updated the CI baseline?

Supports building libevent with linkages other than static

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

it looks like it, yes.

### CODE REVIEW

**Comment by JackBoosY** [comment]
I think this changes can also delete dynamic libraries when building dynamic.

**Comment by andreabedini** [comment]
> I think this changes can also delete dynamic libraries when building dynamic.

Are libraries going to be in `${CURRENT_PACKAGES_DIR}/bin`?

**Comment by andreabedini** [comment]
the following (or a variation thereof) is done many times in `ports/`
```
if(VCPKG_LIBRARY_LINKAGE STREQUAL static)
    file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/bin ${CURRENT_PACKAGES_DIR}/debug/bin)
endif()
```
basically preventing me form building an "all-dynamic" triplet. I am wondering what the rationale behind this choice is, or perhaps, whether I am missing something fundamental here.

**Comment by JackBoosY** [comment]
_VCPKG_ROOT/installed/${TRIPLET}/bin_ <---- dynamic libraries and pdbs
_VCPKG_ROOT/installed/${TRIPLET}/lib_ <---- static libraries
_VCPKG_ROOT/installed/${TRIPLET}/include_ <---- header files
_VCPKG_ROOT/installed/${TRIPLET}/share_ <---- docs, other configure files and examples
_VCPKG_ROOT/installed/${TRIPLET}/tools_ <---- tools

**Comment by andreabedini** [comment]
I see! "bin" in the unix world has a different meaning. Thanks for clarifying @JackBoosY

**Pull request closed without merging**
