### PR TITLE
[tiff] Make BUILD_TOOLS option a feature

### PR DESCRIPTION
**Pull request by ShinNoNoir**
This PR adds a new feature to the libtiff package for optionally building libtiff tools.

### CODE REVIEW

**Comment by ShinNoNoir** [comment]
Hmm, I'm having a hard time figuring out what exactly failed in the automatic checks, but looking at most other recent PRs, is it possible that there's currently an issue in the automatic checks themselves?

**Review by dan-shaw — APPROVED** [review]

**Comment by ras0219-msft** [comment]
LGTM, thanks for the PR!

**Pull request merged**
