### PR TITLE
[WIP][pcl] Support boost 1.75 with cuda

### LINKED ISSUE #15447: [PCL:x64-windows] build failure with [cuda] feature since BOOST 1.75.0
**Host Environment**
- OS: Windows 10
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29335 for x64

**To Reproduce**
`./vcpkg install pcl[cuda]`

**Failure logs** 
- [install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5766095/install-x64-windows-dbg-out.log)

**Additional context**
It was building fine using boost 1.74, and the build error is directly linked with boost while compiling cuda files:

```
[463/477] cmd.exe /C "cd /D E:\vcpkg\buildtrees\pcl\x64-windows-dbg\cuda\segmentation\CMakeFiles\pcl_cuda_segmentation.dir\src && "C:\Program Files\CMake\bin\cmake.exe" -E make_directory E:/vcpkg/buildtrees/pcl/x64-windows-dbg/cuda/segmentation/CMakeFiles/pcl_cuda_segmentation.dir/src/. && "C:\Program Files\CMake\bin\cmake.exe" -D verbose:BOOL=OFF -D build_configuration:STRING=Debug -D generated_file:STRING=E:/vcpkg/buildtrees/pcl/x64-windows-dbg/cuda/segmentation/CMakeFiles/pcl_cuda_segmentation.dir/src/./pcl_cuda_segmentation_generated_connected_components.cu.obj -D generated_cubin_file:STRING=E:/vcpkg/buildtrees/pcl/x64-windows-dbg/cuda/segmentation/CMakeFiles/pcl_cuda_segmentation.dir/src/./pcl_cuda_segmentation_generated_connected_components.cu.obj.cubin.txt -P E:/vcpkg/buildtrees/pcl/x64-windows-dbg/cuda/segmentation/CMakeFiles/pcl_cuda_segmentation.dir/src/pcl_cuda_segmentation_generated_connected_components.cu.obj.Debug.cmake"
FAILED: cuda/segmentation/CMakeFiles/pcl_cuda_segmentation.dir/src/pcl_cuda_segmentation_generated_connected_components.cu.obj
...
E:\vcpkg\installed\x64-windows\include\boost/mpl/not.hpp(47): error: identifier "T1" is undefined
E:\vcpkg\installed\x64-windows\include\boost/mpl/not.hpp(47): error: expected a type specifier
E:\vcpkg\installed\x64-windows\include\boost/mpl/not.hpp(47): error: expected a type specifier
...
```

Maybe we can switch back to 1.74 if a easy fix could not be found. Anyway, since many package have cuda support, a CI step targeting cuda option would be great to catch this kind of error early.

### PR DESCRIPTION
**Pull request by dweckmann**
**Describe the pull request**

- What does your PR fix? 

Fixes #15447

BTW, it is a patch from upstream that I've borrowed:

https://github.com/PointCloudLibrary/pcl/commit/8f667b508d7afb4e23ea5d43207cc319d69598b2?branch=8f667b508d7afb4e23ea5d43207cc319d69598b2&diff=unified

- Which triplets are supported/not supported? Have you updated the CI baseline?

Nothing should have changed in this regards.

### CODE REVIEW

**Comment by dweckmann** [comment]
Sorry, this patch is not enough. Some additional work are required.

**Comment by JackBoosY** [comment]
Any progress?
I wish this PR can also fix issue https://github.com/microsoft/vcpkg/issues/15130.

**Comment by NancyLi1013** [comment]
Seems upstream has new changes for `boost`. https://github.com/PointCloudLibrary/pcl/pull/4660

@dweckmann 

Could you please update to the latest changes to rebuild this?

**Comment by dweckmann** [comment]
I'm sorry, I have not time to work on this right now. However, I will try to take some time in the next few day to test again that.

**Comment by BillyONeal** [comment]
I've closed this PR due to lack of response (and us trying to update to boost 1.67 now :) ). Please feel free to reopen or create a new PR should you want to look again :)

**Pull request closed without merging**
