### PR TITLE
[octomap] fix linux build

### PR DESCRIPTION
**Pull request by markdegreef**
Copy entire bin folder for linux, as it only contains the executables

### CODE REVIEW

**Comment by grdowns** [comment]
Hey @markdegreef, thanks for the PR. Is it intended to leave the `debug/bin` directory for the Linux build? I noticed that the executables located in the `debug/bin` for Windows triplets are removed with only the `.dll`'s remaining.

**Comment by markdegreef** [comment]
I removed the bin directory instead of the debug/bin directory. Latest commit fixes removes the correct files.

**Comment by PhoebeHui** [comment]
@markdegreef, thanks for contributing to vcpkg!

Here is failed triplet and failed ports with your PR.
```
Processing arm-uwp                        412 vs 412
 Processing arm64-windows                  471 vs 471
 Processing x64-linux                      613 vs 612
     fcl                                                         Fail vs Skip
     octomap                                                     Pass vs Fail
 Processing x64-osx                        606 vs 605
     fcl                                                         Fail vs Skip
     octomap                                                     Pass vs Fail
 Processing x64-uwp                        440 vs 440
 Processing x64-windows                    881 vs 883
     fcl                                                         Skip vs Pass
     octomap                       **regression**                Fail vs Pass
 Processing x64-windows-static             777 vs 777
 Processing x86-windows                    863 vs 863
```
[install-x64-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2960103/install-x64-windows-dbg-out.log)

**Comment by markdegreef** [comment]
Seems to build fine on my machine. Also I tried to make sure nothing changed on the windows side. Any idea what the problem is?

**Comment by grdowns** [comment]
Hey @markdegreef. Yeah, after some investigation it looks like a problem purely on our CI builds. We're failing to acquire `msys` due to a leftover lock file (ie the PR is perfectly fine). After talking with the team it's now a high priority of mine to get this problem fixed so that this PR as well as #5582 can be unblocked. Thanks for bearing with us!

**Comment by markdegreef** [comment]
@grdowns no problem. Thanks for looking into it.

**Pull request merged**
