### PR TITLE
[vtk][itk][proj4] Update proj4, ITK, and VTK portfiles.

### PR DESCRIPTION
**Pull request by fbudin69500**
* proj4 was not compiling on Linux due to interactions in the portfile with files generated only with MSVC.
* VTK portfile has been simplified to use a CMake configuration option to select where to install RUNTIME files instead of manually moving them. This should simplify the process and remove possible bugs.
* ITK now depends on vcpkg hdf5[cpp] instead of building its own hdf5 version, and thanks to that can also build the VTK bridge (feature).

### CODE REVIEW

**Comment by Rastaban** [comment]
I am seeing build failures failures on libgeotiff on windows, which has a dependency on proj4.

**Comment by fbudin69500** [comment]
@Rastaban Thanks for looking into it. I haven't tested this in a long time. Maybe the proj4 patch is not necessary anymore. I will try to find some time to test this but I don't have much time for this right now.

**Comment by Rastaban** [comment]
The proj4 changes look to be independent of the itk/vtk changes, so I am going to revert that port.  Please correct me if I am wrong.  If they are still needed for the proj4 port then we can do them in a separate PR.

**Comment by Rastaban** [comment]
We are interested in having the x11 libraries in vcpkg sometime in the future, but it is better to not let that block this PR.  Added message similar to what we have in nana about getting the library if needed.

**Pull request merged**
