### PR TITLE
[pdal, pdal-c] Update to v2.5.3, v2.2.0 and fix GCC 13 build

### PR DESCRIPTION
**Pull request by cbrl**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

This updates PDAL to version 2.5.3, and includes a [PR](https://github.com/PDAL/PDAL/pull/4039) that fixes a build error with GCC 13. The GCC 8 compatibility patch was removed as it has been accepted into the upstream repo.

PDAL 2.5.3 depends on Draco 1.5.6. An existing PR to upgrade Draco exists at #31220

### CODE REVIEW

**Comment by MonicaLiu0311** [comment]
The following error occurs during CI testing:
```
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: D:/buildtrees/pdal/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\buildtrees\pdal\config-x64-windows-dbg-CMakeCache.txt.log
      D:\buildtrees\pdal\config-x64-windows-rel-CMakeCache.txt.log
      D:\buildtrees\pdal\config-x64-windows-out.log

Call Stack (most recent call first):
  D:/installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:248 (vcpkg_execute_required_process)
  ports/pdal/portfile.cmake:49 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)
```
**D:\buildtrees\pdal\config-x64-windows-out.log:**
```
CMake Error at C:/a/1/s/scripts/buildsystems/vcpkg.cmake:852 (_find_package):
  Could not find a configuration file for package "Draco" that is compatible
  with requested version "1.5.6".

  The following configuration files were considered but not accepted:

    D:/installed/x64-windows/share/draco/draco-config.cmake, version: 1.5.3

Call Stack (most recent call first):
  plugins/draco/CMakeLists.txt:6 (find_package)
```


Note: I will be converting your PR to draft status. When you resolve, revert to "ready for review". That way, I know you've fixed it, since you can't modify the tags.

**Comment by cbrl** [comment]
That error is expected until the mentioned PR for Draco is merged, which does unfortunately prevent the pipeline from running successfully. I will mark this for review once the Draco PR has been merged.

**Comment by cbrl** [comment]
PDAL's C API must also be updated to version 2.2.0 to account for an API change in PDAL. I have added the required update to pdal-c to this PR.

**Comment by MonicaLiu0311** [comment]
Usage:
```
The package pdal provides CMake variables:

    find_package(PDAL CONFIG REQUIRED)
    target_include_directories(${PDAL_INCLUDE_DIRS})
    target_link_libraries(main PRIVATE ${PDAL_LIBRARIES})

If necessary, override the default plugin search path by setting the
environment variable PDAL_DRIVER_PATH to a list of directories that
pdal should search for plugins.
```

When testing usage, the following error occurs:
```
1> [CMake] CMake Error at CMakeFindUsage/CMakeLists.txt:16 (target_include_directories):
1> [CMake]   target_include_directories called with incorrect number of arguments
1> [CMake] 
1> [CMake] 
1> [CMake] -- Configuring incomplete, errors occurred!
```


Added Usage from #21275, now submit 77fc184f788f7a0ed88aaa681af175f04d53c1f0 to fix it.

**Comment by MonicaLiu0311** [comment]
All features are tested successfully in the following triplet:
```
x86-windows
x64-windows
```

The usage test passed (header files found):
```
The package pdal provides CMake variables:

    find_package(PDAL CONFIG REQUIRED)
    target_include_directories(main PRIVATE ${PDAL_INCLUDE_DIRS})
    target_link_libraries(main PRIVATE ${PDAL_LIBRARIES})

If necessary, override the default plugin search path by setting the
environment variable PDAL_DRIVER_PATH to a list of directories that
pdal should search for plugins.
```

**Review by MonicaLiu0311 — APPROVED** [review]

**Pull request merged**
