### PR TITLE
[volk] Update dependencies to only depend on vulkan-headers rather than vulkan

### PR DESCRIPTION
**Pull request by Honeybunch**
**Describe the pull request**
  The volk library doesn't need the entire `vulkan` package as a dependency. It can build with just `vulkan-headers`. This would be ideal as `vulkan-headers` is a more minimal dependency than `vulkan` which currently relies on the user to have an already installed Vulkan SDK.

- #### What does your PR fix?
  Minimizes the dependencies on the `volk` library

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  All

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes
- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

### CODE REVIEW

**Comment by Cheney-W** [comment]
Does upstream approve of this modification?

**Comment by Honeybunch** [comment]
The upstream CMakeLists.txt does have support for simply being given the path to the vulkan headers. Also it doesn't really make sense for `volk` to depend on the `vulkan` package. The Vulkan SDK actually contains a volk library out of the box now, so the current setup is a bit redundant.

I can certainly open an issue upstream to get input from @zeux if you think that's required but the change here feels pretty natural / minimal to me as someone who has worked with the `volk` library for a while now

**Comment by Honeybunch** [comment]
Also of note is that upstream's CMakeLists.txt explicitly checks for this variable that I'm setting in the port: https://github.com/zeux/volk/blob/master/CMakeLists.txt#L71

**Comment by JavierMatosD** [comment]
Thank you!

**Pull request merged**
