### PR TITLE
[boost] MinGW build fixes

### PR DESCRIPTION
**Pull request by koprok**
Fixes boost libraries build errors using MinGW toolchain.

### CODE REVIEW

**Comment by PhoebeHui** [comment]
I summited PR https://github.com/microsoft/vcpkg/pull/11496 for fixing the baseline failures which blocks this PR.

**Comment by PhoebeHui** [comment]
PR https://github.com/microsoft/vcpkg/pull/11545 would fix boost failures with arm64_windows.

**Comment by koprok** [comment]
@PhoebeHui, I have accumulated several more MinGW build fixes for other ports. What do you prefer, i.e. how it would be easier for you:
- add all my MinGW port fixes to this branch for review and merge them all at once;
- or make a separate merge request for any additional MinGW port fixes?

**Comment by PhoebeHui** [comment]
@koprok, I suggest to make a separate merge request for any additional MinGW port fixes, it's more easier to review or to fix the failures in CI testing.

**Review by PhoebeHui — APPROVED** [review]
LGTM

**Pull request merged**
