### PR TITLE
[pango] Update to 1.50.14

### LINKED ISSUE #30890: [pango] update to 1.50.14
### Library name

pango

### New version number

1.50.14

### Other information that may be useful (release notes, etc...)

https://gitlab.gnome.org/GNOME/pango/-/blob/25c27f452294f84044d5cc9f23b637193c7b4421/NEWS

### PR DESCRIPTION
**Pull request by SchaichAlonso**
Fixes #30890.

- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Review by JonLiu1993 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks!

**Comment by JonLiu1993** [comment]
Feature `introspection` tested successfully in the following triplrt:
- x86-windows
- x64-windows

**Comment by BillyONeal** [comment]
> Feature `introspection` tested successfully in the following triplrt:

I assumed it was good because it was approved :)

**Comment by JonLiu1993** [comment]
> > Feature `introspection` tested successfully in the following triplrt:
> 
> I assumed it was good because it was approved :)

Yes, but just to be on the safe side, I also tested the feature locally.

**Pull request merged**
