### PR TITLE
[minitrace] Update minitrace to the latest version

### PR DESCRIPTION
**Pull request by JuliusBrueggemann**
This version includes two important changes:
1. It can be built and installed with CMake, which removes the need for a custom CMakeLists.txt
2. It can be built as a shared library as well as a static library

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by JuliusBrueggemann** [comment]
@microsoft-github-policy-service agree

**Review by BillyONeal — APPROVED** [review]
I love getting rid of custom build systems! Thanks! ❤️

**Comment by FrankXie05** [comment]
The usage has been tested successfully loacally.
```
minitrace provides CMake targets: 

    # this is heuristically generated, and may not be correct 
    find_package(minitrace CONFIG REQUIRED) 
    target_link_libraries(main PRIVATE minitrace::minitrace)
```

**Review by FrankXie05 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the update!

**Pull request merged**
