### PR TITLE
[field3d] Remove port

### PR DESCRIPTION
**Pull request by chausner**
**Describe the pull request**

- #### What does your PR fix?  
  This removes port `field3d` since it is no longer maintained upstream, cannot be updated and prevents the update of other ports. See the discussion at https://github.com/microsoft/vcpkg/pull/21079 for more details. In addition to removing the port, this PR removes the `field3d` feature from openimageio which depends on the removed port.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

### CODE REVIEW

**Comment by Hoikas** [comment]
If the port is simply unmaintained but not broken, deleting the port entirely seems inappropriate, IMO.

**Comment by JackBoosY** [comment]
But we can keep the current version and add a message to notify the user that field3d will no longer update, right?

**Comment by JackBoosY** [comment]
@chausner I think we don't need to remove this port, just remove this dependency relationship when the next openexr update would be okay.

**Comment by JackBoosY** [comment]
Here's what I understand:
1. The issue with openexr for field3d could not be handled for some time.
2. oiio has removed the necessary dependencies openexr.

So, I think field3d is fine so far as long as we don't update it. For updating openexr, we should do it after the upstream has dealt with the field3d issue.
For oiio, we can move openexr from a required dependency as a feature, or simply remove this dependency in the next update of oiio.

**Comment by fabiencastan** [comment]
The main problem is that openexr is a **highly used** packages in the VFX industry (http://vfxplatform.com is documenting the recommended versions for the VFX industry). OpenEXR needs to be updated to 3.x as soon as possible. OpenEXR-2 has conflicts with some boost versions and with cuda (due to "half" type redefinition). These are fixed in OpenEXR-3.

Also, currently vcpkg is broken as there is both an imath packages and an old openexr package which includes imath. So during installation there are headers and libraries at different versions installed at the same time.

So, IMO we should drop the "field3d" package and upgrade "openexr".

**Comment by JackBoosY** [comment]
> Also, currently vcpkg is broken as there is both an imath package and an old openexr package which includes an old version of imath. So during installation there are 2 versions of imath headers and libraries mixed together.

After some exploration, I found that ilmbase in vcpkg actually points to ilmbase in openexr, so I think this is not an issue.

> The main problem is that openexr is a highly used packages in the VFX industry (http://vfxplatform.com is documenting the recommended versions for the VFX industry). OpenEXR needs to be updated to 3.x as soon as possible. OpenEXR-2 has conflicts with some boost versions and with cuda (due to "half" type redefinition). These are fixed in OpenEXR-3.

Now, openexr doesn't depends on field3d and there is no code related to field3d. Therefore, field3d is no longer in the dependency chain of openexr or oiio.
So I don't think we need to remove field3d.

**Comment by dg0yt** [comment]
> Now, openexr doesn't depends on field3d and there is no code related to field3d. Therefore, field3d is no longer in the dependency chain of openexr or oiio.

@JackBoosY It is the other way: field3d *depends on openexr*. Updating openexr breaks the unmaintained field3d so it can't pass CI.

**Comment by JackBoosY** [comment]
> > Now, openexr doesn't depends on field3d and there is no code related to field3d. Therefore, field3d is no longer in the dependency chain of openexr or oiio.
> 
> @JackBoosY It is the other way: field3d _depends on openexr_. Updating openexr breaks the unmaintained field3d so it can't pass CI.

OMG, that's unfortunate. Fine, I personaly agreed that, but please empty this port since we shouldn't `remove` any port, see example: https://github.com/microsoft/vcpkg/tree/030cfaa24de9ea1bbf0a4d9c615ce7312ba77af1/ports/parquet

@strega-nil-ms @BillyONeal what do you think about?

**Comment by BillyONeal** [comment]
I think the right thing is to add field3d to ci.baseline.txt. Let me ask around.

**Comment by BillyONeal** [comment]
Example precedent: https://github.com/microsoft/vcpkg/pull/19909/files#diff-9fcdd4a058d859ef3176f49bff8b5cb026f9fdfb2a35aaae36beaf6a9a0b1807L1585

**Comment by JackBoosY** [comment]
> I think the right thing is to add field3d to ci.baseline.txt. Let me ask around.

Once openexr update, field3d will no longer be built succesful, does it make sense?

**Comment by theblackunknown** [comment]
Out of curiosity, can [vcpkg versionning feature](https://vcpkg.io/en/docs/users/versioning.html) help to keep a valid field3d port here ?

Either using [overrides](https://vcpkg.io/en/docs/users/versioning.html#overrides) to pin openexr version to a 2.X
```diff
--- C:\devel\vcpkg\ports\field3d\vcpkg.json	Sun Sep 12 15:19:46 2021
+++ C:\devel\vcpkg\ports\field3d\vcpkg.json	Fri Jan 14 09:21:41 2022
@@ -16,6 +16,9 @@
     "boost-timer",
     "hdf5",
     "openexr"
+  ],
+  "overrides": [
+    { "name": "openexr", "version": "2.5.0" }
   ]
 }
```

Or a [builtin-baseline](https://vcpkg.io/en/docs/users/versioning.html#builtin-baseline) so that the right version is picked 
```diff
--- C:\devel\vcpkg\ports\field3d\vcpkg.json	Sun Sep 12 15:19:46 2021
+++ C:\devel\vcpkg\ports\field3d\vcpkg.json	Fri Jan 14 09:23:52 2022
@@ -16,6 +16,7 @@
     "boost-timer",
     "hdf5",
     "openexr"
-  ]
+  ],
+  "builtin-baseline":"9f04533f307a8560cc1cc5c1fdee0d88d6d7d818"
 } 
```

or both ?

If yes that would allow to keep a functional `field3d` port, possibly useful for backwards compatibility instead of an empty port

**Comment by chausner** [comment]
> I think the right thing is to add field3d to ci.baseline.txt. Let me ask around.

Thanks, please let me know once there is a decision how to best handle this case.

**Comment by JackBoosY** [comment]
@theblackunknown No, vcpkg will no pick the required dependency version, only use the current latest version in vcpkg.

**Comment by theblackunknown** [comment]
@JackBoosY  Understood, so versioning is only useful when describing dependencies for projects correct ?
In any case, thanks for the explanation !

**Comment by JackBoosY** [comment]
> @JackBoosY Understood, so versioning is only useful when describing dependencies for projects correct ? In any case, thanks for the explanation !

- In traditional mode(command mode), version control only follows the description in vcpkg.json. If it is not explicitly stated in vcpkg.json, the current latest version is used in vcpkg.
- In manifest mode, the user can enable versioning by declaring this rule in the private vcpkg.json.

**Comment by fabiencastan** [comment]
Hi all,
What's the current status? Are we close to getting this PR merged?

**Comment by JackBoosY** [comment]
@BillyONeal Any results?

**Comment by fabiencastan** [comment]
It is a critical blocking point for us for weeks.
Is there any chance that this package could be removed soon to finally update openexr?
Thanks for your help.

**Review by BillyONeal — APPROVED** [review]

**Review by JackBoosY — APPROVED** [review]

**Comment by BillyONeal** [comment]
Turns out there was a bit of a "wires crossing" here; our old rules were "no removals ever"; the new rules are "if a port is completely broken, its contents and baseline can be deleted because people can access old versions using the versions database. The versions DB must be kept though".

I resolved the merge conflicts and now think this is OK but want confirmation from another maintainer before merging because removals are impactful.

**Comment by fabiencastan** [comment]
Thank you!!

**Pull request merged**
