### PR TITLE
Resolves "project is never up-to-date" problem (issue 6179)

### LINKED ISSUE #6179: Project that depends on vcpkg library is never considered up-to-date
Win7, MSVC 2017, latest vcpkg. Here is how output looks like:

```
1>------ Build started: Project: o2ftool, Configuration: Debug x64 ------
1>Build started 4/19/2019 5:31:55 PM.
1>Target ResolveProjectReferences:
1>Target InitializeBuildStatus:
1>  Touching "x64\Debug\o2ftool.tlog\unsuccessfulbuild".
1>Target VcpkgTripletSelection:
1>  Using triplet "x64-windows" from "c:\vcpkg\installed\x64-windows\"
1>Target ClCompile:
1>  All outputs are up-to-date.
1>Target ResolvedLinkLib:
1>  Target SetBuildDefaultEnvironmentVariables:
1>Target Link:
1>  All outputs are up-to-date.
1>  o2ftool.vcxproj -> C:\<blah-blah>\Debug\o2ftool.exe
1>Target AppLocalFromInstalled:
1>  C:\<blah-blah>\Debug\aws-cpp-sdk-core.dll
1> ...
1>  C:\<blah-blah>\Debug\zlibd1.dll
1>Target _CopyFilesMarkedCopyLocal:
1>  Touching "C:\<blah-blah>\o2ftool\x64\Debug\o2ftool.vcxproj.CopyComplete".
1>Target GetCopyToOutputDirectoryItems:
1>Target FinalizeBuildStatus:
1>  Deleting file "x64\Debug\o2ftool.tlog\unsuccessfulbuild".
1>  Touching "x64\Debug\o2ftool.tlog\o2ftool.lastbuildstate".
1>
1>Build succeeded.
1>    0 Warning(s)
1>    0 Error(s)
1>
1>Time Elapsed 00:00:00.67
========== Build: 1 succeeded, 0 failed, 2 up-to-date, 0 skipped ==========
```

Regardless how many time I build it, it finds smth to do every time... Looks like some sort of a bug, here is what output looks like on 'Diagnostic' lvl:
```
3>------ Up-To-Date check: Project: o2ftool, Configuration: Debug x64 ------
3>Project is not up-to-date: build output '㩃呜卆卜潴慲敧屘畃牲湥屴楂屮敄畢屧睡⵳灣⵰摳⵫潣敲搮汬਍㩃呜卆卜潴慲敧屘畃牲湥屴楂屮敄畢屧睡⵳ⵣ癥湥⵴瑳敲浡搮汬਍㩃呜卆卜潴慲敧屘畃牲湥屴楂屮敄畢屧睡⵳ⵣ潣浭湯搮汬਍㩃呜卆卜潴慲敧屘畃牲湥屴楂屮敄畢屧睡⵳档捥獫浵⹳汤൬䌊尺䙔屓瑓牯条塥䍜牵敲瑮䉜湩䑜扥杵慜獷挭灰猭此猭⸳汤൬䌊尺䙔屓瑓牯条塥䍜牵敲瑮䉜湩䑜扥杵捜灰敲瑳㉟ㅟ搰搮汬਍㩃呜卆卜潴慲敧屘畃牲湥屴楂屮敄畢屧楬换牵⵬⹤汤൬䌊尺䙔屓瑓牯条塥䍜牵敲瑮䉜湩䑜扥杵穜楬摢⸱汤൬䌊尺䙔屓瑓牯条塥䍜牵敲瑮䉜湩䑜扥杵睜獡潴慲敧搮汬਍' is missing
3>------ Build started: Project: o2ftool, Configuration: Debug x64 ------
3>Build started 4/22/2019 5:32:51 PM.
3>Environment at start of build:
<blah-blah-blah>
```

I have no idea where this long line of garbage came from and why my project depends on it, but I can't find anything in vcxproj files and this happens **only** if I try to use vcpkg library in my code.

### PR DESCRIPTION
**Pull request by crusader-mike**
This issue resolves #6179 (that happens in certain configurations).

### CODE REVIEW

**Comment by Rastaban** [comment]
Because this touches the scripts directory I am running a full rebuild test at https://dev.azure.com/vcpkg/public/_build/results?buildId=5956

**Comment by crusader-mike** [comment]
@Rastaban Looks like all tests are fine -- what is the typical wait for a PR to be merged?

**Comment by Rastaban** [comment]
I will just merge it now.  Thanks!

**Comment by crusader-mike** [comment]
@Rastaban Thank you

**Pull request merged**
