### PR TITLE
[curl] update to 7.61.0

### PR DESCRIPTION
**Pull request by pravic**

### CODE REVIEW

**Comment by alexkaratarakis** [comment]
Is the hash correct? I am getting a hash mismatch error.

**Comment by fcharlie** [comment]
@pravic Please remove Patch [0005_winssl_http2.patch](https://github.com/Microsoft/vcpkg/blob/master/ports/curl/0005_winssl_http2.patch) , cURL fixed see https://github.com/curl/curl/issues/2591
[Pull 3616](https://github.com/Microsoft/vcpkg/pull/3616)

**Comment by pravic** [comment]
@alexkaratarakis It was invalid.

@fcharlie Thanks, I've made the requested changes.

**Comment by ras0219-msft** [comment]
Thanks for the PR!

**Pull request merged**
