### PR TITLE
[libimobiledevice] Use its orignal upstream

### PR DESCRIPTION
**Pull request by xiaozhuai**
1. [libplist] update to 2.2.0 latest ref and use its orignal upstream
2. [libimobiledevice-glue] add new port
3. [libusbmuxd] update to 2.0.2 latest ref and use its orignal upstream
4. [libimobiledevice] using original upstream
5. [libideviceactivation] use original upstream and use its orignal upstream

Suggested by https://github.com/microsoft/vcpkg/pull/28022#issuecomment-1332034406 and https://github.com/microsoft/vcpkg/pull/28022#pullrequestreview-1195032811

### CODE REVIEW

**Comment by xiaozhuai** [comment]
Contains a lot of things that are not compatible with msvc.
It doesn't look like there's an easy way to do this

**Comment by dg0yt** [comment]
It is a known example of bad upstreaming (from the msvc fork) and bad porting (by not being based on the proper upstream).
In the end we may need to split into `<port>-win32` and `<port>-unix` to properly dead with possibly diverging versions. (This patterns already exists, but in puts mingw in the unix family.)

**Comment by xiaozhuai** [comment]
> It is a known example of bad upstreaming (from the msvc fork) and bad porting (by not being based on the proper upstream).
> In the end we may need to split into `<port>-win32` and `<port>-unix` to properly dead with possibly diverging versions. (This patterns already exists, but in puts mingw in the unix family.)

@dg0yt Thank you for your reply.

As you said, although the upstream of these ports claims to support windows, they only support mingw and not msvc. 
The fork supports msvc, but it part ways with the upstream.
This is a depressing fact.

I don't like `<port>-win32` and `<port>-unix` pattern, nobody would, but there seems to be no other good way.
So I'll leave these ports as they are.
Maybe someone would like to do this.
For my usage, the fork works good by far.

**Comment by xiaozhuai** [comment]
Maybe the best way is to create a new fork based on the upstream which can merge any changes from the upstream at any time : )
I don't know.

**Pull request closed without merging**
