### PR TITLE
[Vulkan] Ensure minimum Vulkan SDK of 1.2

### PR DESCRIPTION
**Pull request by juan-lunarg**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

Currently the latest version of the vulkan sdk is `1.3`. So `1.2` as a minimum isn't too restricting. When `1.4` comes out, I'll update the version to `1.3` accordingly.

The Vulkan SDK follows semantic versioning so there shouldn't be any issues with this approach.

Also it makes the version number more useful and less confusing than `1.1.82.1` to developers.

### CODE REVIEW

**Comment by juan-lunarg** [comment]
Converted to draft since this is more of a suggestion/idea.

**Comment by BillyONeal** [comment]
I think the issue is less "do we think something breaks" vs. "what is the benefit". Do we have some other port in the catalog that really wants a later version?

**Comment by juan-lunarg** [comment]
> Do we have some other port in the catalog that really wants a later version?

I just checked the most popular ports that depend on Vulkan. GLFW, VMA, and Volk. It looks like none of them depend on a newer SDK (I think), they all seem to work with older SDKs. I'll close this PR.

**Comment by BillyONeal** [comment]
> I just checked the most popular ports that depend on Vulkan. GLFW, VMA, and Volk. It looks like none of them depend on a newer SDK (I think), they all seem to work with older SDKs. I'll close this PR.

To be clear, even if it's just an end user who wants to pick a later version that's a reason to do it. Just don't want to bump minimums and thus potentially break people without any carrot to go with that stick whatsoever, if you know what I mean :).

Thanks for your submission to vcpkg!

**Pull request closed without merging**
