### PR TITLE
[fastdds] update to 3.0.1(rename fastrtps)

### PR DESCRIPTION
**Pull request by miyanyan**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [ ] The "supports" clause reflects platforms that may be fixed by this new version.
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [ ] Any patches that are no longer applied are deleted from the port's directory.
- [ ] When updating the upstream version, the `"port-version"` is reset (removed from `vcpkg.json`).
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

The FastRTPS project has been renamed to the FastDDS, and there's a new version 3.0, so it's time to rename it like https://github.com/microsoft/vcpkg/pull/38346, I also found this had been tried in https://github.com/microsoft/vcpkg/pull/28181

### CODE REVIEW

**Comment by BillyONeal** [comment]
We are happy to take the rename. This PR needs to be fixed to deindex the old one:

* delete ports/fastrtps
* delete the entry from versions/baseline.json
* DO NOT touch anything in versions/f-/fastrtps.json

Hope that helps!

**Comment by miyanyan** [comment]
fastdds requires `android-ifaddrs` when platform is android, but vcpkg doesn't have this port
requires here
```
if(ANDROID)
    if((ANDROID_PLATFORM LESS_EQUAL 23) OR (ANDROID_NATIVE_API_LEVEL LESS_EQUAL 23))
        eprosima_find_thirdparty(android-ifaddrs android-ifaddrs)
    endif()
endif()
```
fastdds used `android-ifaddrs` as a submodule, https://github.com/michalsrb/android-ifaddrs

how to fix this, need some help😭

**Comment by dg0yt** [comment]
CI is instructed to skip many ports which required API level 24 for android. Maybe this is also an option for fastdds?

**Comment by miyanyan** [comment]
> CI is instructed to skip many ports which required API level 24 for android. Maybe this is also an option for fastdds?

Does this refer to `scripts/test_ports/vcpkg-ci-xxx`? I found there are some prs related to this folder.

**Comment by BillyONeal** [comment]
> > CI is instructed to skip many ports which required API level 24 for android. Maybe this is also an option for fastdds?
> 
> Does this refer to `scripts/ci.baseline.txt`? I found there are some prs related to this file.

I believe so.

When Android was first added to testing we added anything that failed to `ci.baseline.txt` so that new PRs could still be written without someone needing to fix a world of unrelated stuff.

**Comment by jimwang118** [comment]
The following problems occurred during local testing.
```
[DEBUG] E:\fastdds\downloads\eProsima-Fast-DDS-v3.0.1.tar.gz.6236.part has hash 84333bef4b5264b72129e515c2208048c25794d7d653073298cbf5f43ba95c85f2aa64f30e6911a69daf9affc4dc1e10cea4064da43fdd709bbe04ef1cf1f4d7
error: Missing eProsima-Fast-DDS-v3.0.1.tar.gz and downloads are blocked by x-block-origin.
error: File does not have the expected hash:
url: https://github.com/eProsima/Fast-DDS/archive/v3.0.1.tar.gz
File: E:\fastdds\downloads\eProsima-Fast-DDS-v3.0.1.tar.gz.6236.part
Expected hash: 8ccf3c976220719db59515ec680bb68dbd3bd726f6b6f29b3e9d19acd9b40545e8315109d5ab0c60bc55af7288b890e22f40a513ab56443c4b1c1a40c4d02bb0
Actual hash: 84333bef4b5264b72129e515c2208048c25794d7d653073298cbf5f43ba95c85f2aa64f30e6911a69daf9affc4dc1e10cea4064da43fdd709bbe04ef1cf1f4d7
```

**Pull request merged**
