### PR TITLE
[libbson][mongo-c-driver] Update to version 1.13.0.

### PR DESCRIPTION
**Pull request by ivysnow**
Update libbson and mongo-c-driver to latest version 1.13.0.

### CODE REVIEW

**Comment by lsparey** [comment]
Good work. I could do with this update.

I would suggest -DENABLE_BSON=SYSTEM when building mongo-c-driver and including libbson as a separate dependency

**Comment by Cheney-W** [comment]
Here are the test results. The left results column is the latest commit to this PR, the right results column is test results from master: Skip typically means something it has a dependency on failed so it was not built.
```
Processing x64-windows                    844 vs 846

     mongo-c-driver                **regression**                Fail vs Pass

     mongo-cxx-driver                                            Skip vs Pass

 Processing x86-windows                    824 vs 826

     mongo-c-driver                **regression**                Fail vs Pass

     mongo-cxx-driver                                            Skip vs Pass
```

**Comment by Rastaban** [comment]
Resolved merge conflicts

**Comment by grdowns** [comment]
Thanks for the updates, @ivysnow!

**Pull request merged**
