### PR TITLE
[utfcpp] Update to 3.2.1 version

### PR DESCRIPTION
**Pull request by RT2Code**
https://github.com/nemtrif/utfcpp/releases/tag/v3.2.1

### CODE REVIEW

**Review by JonLiu1993 — COMMENTED** [review]
@RT222 ,Thanks for your PR.could you explain why the patch was deleted?

**Comment by RT222** [comment]
Utfcpp was providing GTest as a submodule, and the patch used the vcpkg port instead to build the library. Since the 3.2 version, the author switched from GTest to his own unit test framework, rendering this patch obsolete : https://github.com/nemtrif/utfcpp/commit/fe79d14ae764e0da411078927b1c60ea9271e408

**Comment by JonLiu1993** [comment]
> Utfcpp was providing GTest as a submodule, and the patch used the vcpkg port instead to build the library. Since the 3.2 version, the author switched from GTest to his own unit test framework, rendering this patch obsolete : [nemtrif/utfcpp@fe79d14](https://github.com/nemtrif/utfcpp/commit/fe79d14ae764e0da411078927b1c60ea9271e408)

Thanks for your clarification

**Review by JonLiu1993 — APPROVED** [review]

**Comment by strega-nil-ms** [comment]
Cool, thanks @RT222 :)

**Pull request merged**
