### PR TITLE
Add new port AMF and add AMF support to FFmpeg

### LINKED ISSUE #9272: [ffmpeg] add amd/amf, qsv hard encoding and openh264 encoding support

### PR DESCRIPTION
**Pull request by perroboc**
**Describe the pull request**

- #### What does your PR fix?
  Fixes https://github.com/microsoft/vcpkg/issues/9272

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  windows yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  `Your answer`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  I am still working on this PR

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by Cheney-W** [comment]
versions/a-/amf.json#L2
versions/a-/amf.json(2,): error : While reading versions for port amf from file: version/a-/amf.json
File declares version `1.4.21` with SHA: bc721bba64c094dc7cfbadb8a33b77d96500b28b
But local port with the same version has a different SHA: 0acef831b58c397493e9255586c5c5329be28430
Please update the port's version fields and then run:

    vcpkg x-add-version amf
    git add versions
    git commit -m "Update version database"

to add a new version.

**Comment by Cheney-W** [comment]
versions/f-/ffmpeg.json#L2
versions/f-/ffmpeg.json(2,): error : While reading versions for port ffmpeg from file: version/f-/ffmpeg.json
File declares version `4.4.1#15` with SHA: 48c64ca10cbcf4e3760bbff64128939e9541897f
But local port with the same version has a different SHA: 6ac13c7c770d629d4f943afd7dda85e68668abb1
Please update the port's version fields and then run:

    vcpkg x-add-version ffmpeg
    git add versions
    git commit -m "Update version database"

to add a new version.

**Comment by Cheney-W** [comment]
Pinging @alvaromunoz for response. Is work still being done for this PR?

**Comment by alvaromunoz** [comment]
Sorry, just got back from vacation and right now I'm unable to keep keep working on this. Should I close this PR?

**Comment by Cheney-W** [comment]
If you are willing to continue to work on this PR later, we can keep it in draft form for a month, if not, then close it.

**Pull request closed without merging**
