### PR TITLE
[scripts audit] vcpkg_copy_pdbs

### PR DESCRIPTION
**Pull request by strega-nil**
See [scripts-audit], issue #16188 

[scripts-audit]: https://github.com/microsoft/vcpkg/blob/master/docs/specifications/scripts-extraction.md

Part of the "merge 2021-02-26 EOD" group.

### CODE REVIEW

**Comment by strega-nil** [comment]
Hey @PhoebeHui, do you know what's going on with itpp:*-uwp? did that just break or something?

**Comment by PhoebeHui** [comment]
@strega-nil. I will take a look the failures.

**Comment by PhoebeHui** [comment]
@strega-nil, I could repro this issue locally, it can't find the fft package, FFT_INCLUDES was set to NOTFOUND, so it configured fail when use the FFT_INCLUDES, I have submmited PR#16385 to fix it.

**Comment by strega-nil** [comment]
Closing in favor of a single PR that contains all of these PRs. (to avoid destroying the CI system)

**Pull request closed without merging**
