### PR TITLE
[spdlog] Add feature stdformat

### LINKED ISSUE #25164: [spdlog] Add feature for SPDLOG_USE_STD_FORMAT
Because our project makes heavy use of C++20 `std::format` and `std::formatter`, we would like to enable `spdlog`'s option to use the  same `std::format` instead of  bringing `fmt` in as an external dependency.

**Proposed solution**
Add a feature for `stdformat` that:

1.  Changes the configure options to:
    a.  SPDLOG_FMT_EXTERNAL=OFF
    b.  SPDLOG_USE_STD_FORMAT=ON
2. Uncomments the appropriate line in `include/spdlog/tweakme.h`

### PR DESCRIPTION
**Pull request by LilyWangLL**
- #### What does your PR fix?
  Fixes #25164, add feature stdformat

### CODE REVIEW

**Comment by meldavis** [comment]
A couple of points.   At the bottom of the page you adjust "tweakme.h" for external `fmt` even when using std::format.  And std::format will require setting CMAKE_CXX_STANDARD to at least 20.   

I've attached the files I'm using in an overlay.   Maybe some of it will work for you.

[spdlog-overlay.zip](https://github.com/microsoft/vcpkg/files/8877711/spdlog-overlay.zip)

**Comment by LilyWangLL** [comment]
> A couple of points. At the bottom of the page you adjust "tweakme.h" for external `fmt` even when using std::format. And std::format will require setting CMAKE_CXX_STANDARD to at least 20.
> 
> I've attached the files I'm using in an overlay. Maybe some of it will work for you.
> 
> [spdlog-overlay.zip](https://github.com/microsoft/vcpkg/files/8877711/spdlog-overlay.zip)

Thanks for your suggestion, I am handling set CMAKE_CXX_STANDARD to at least 20. I will check your provided file locally. Thanks again~ 😀

**Comment by meldavis** [comment]
Just wanted to mention that in my overlay, the default feature is "fmt".  To enable std::format, use: "
```json
{ name": "spdlog",
  "default-features": false
}
```

I made "fmt" a feature, because it brings in an external dependency and std::format does not.    Thanks for updating spdlog to accommodate std::format!

**Comment by meldavis** [comment]
Just an FYI.  The latest commit on spdlog addresses the CMAKE_CXX_STANDARD when using STD_FORMAT.

**Comment by meldavis** [comment]
Oh, and just one comment.  Your draft version makes `spdlog` needlessly dependent on the external library `fmt`,  when the user specifies the "std::format" feature.    I wouldn't think that you wouldn't want to pull in a library the user specifically states they do not want/need.

Thanks for updating the port.

**Comment by LilyWangLL** [comment]
> Oh, and just one comment. Your draft version makes `spdlog` needlessly dependent on the external library `fmt`, when the user specifies the "std::format" feature. I wouldn't think that you wouldn't want to pull in a library the user specifically states they do not want/need.
> 
> Thanks for updating the port.

Thanks for your reply. `fmt` and `stdformat` cannot be added to `spdlog` as features at the same time, due to `fmt` is a default feature. The function `"default-features": false` of vcpkg is to reduce the dependencies of feature installation. This function cannot be implemented in the current port features. This is by design. So we can't install `stdformat` without installing `fmt`.

And in my latest commit, I just add `stdformat` to a feature of `spdlog`, I don't modify the dependency `fmt`.

**Comment by JackBoosY** [comment]
Closing this PR since it seems that no progress is being made. Please ping me to reopen if work is still being done.

**Comment by jameskr97** [comment]
@JackBoosY I would be interested in adding this feature to the spdlog library, though I'd like to ask what the preferred implementation would be.

I see two options:
1. Installing `fmt` is the default (as it currently is), and a `std` feature is added to tell vcpkg and spdlog that we'll be using `std::format` instead of `fmt`. I'm still learning about creating vcpkg packages, but it seems that we can only add dependencies, and not remove them. (Does that sound right?)
2. Using `std` is the default, and users who want to use the `fmt` library would need to install that as a feature.

Please let me know what would be preferred, and I can make an appropriate PR.

**Comment by JackBoosY** [comment]
> @JackBoosY I would be interested in adding this feature to the spdlog library, though I'd like to ask what the preferred implementation would be.
> 
> I see two options:
> 
> 1. Installing `fmt` is the default (as it currently is), and a `std` feature is added to tell vcpkg and spdlog that we'll be using `std::format` instead of `fmt`. I'm still learning about creating vcpkg packages, but it seems that we can only add dependencies, and not remove them. (Does that sound right?)
> 2. Using `std` is the default, and users who want to use the `fmt` library would need to install that as a feature.
> 
> Please let me know what would be preferred, and I can make an appropriate PR.

cc @LilyWangLL

**Pull request closed without merging**
