### PR TITLE
[ffmpeg] add usage

### PR DESCRIPTION
**Pull request by autoantwort**
**Describe the pull request**

- #### What does your PR fix?  
  How to use ffmpeg (see discussion on discord)

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  All

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
   I am still working on this PR

After #17153, #17204 and #17236 are merged, I will run `./vcpkg x-add-version --all`.

### CODE REVIEW

**Comment by longnguyen2004** [comment]
Probably no need for `x-add-version` since we're just merely adding a USAGE file.

**Comment by autoantwort** [comment]
> Probably no need for `x-add-version` since we're just merely adding a USAGE file.

Yeah that is right, but I don't know if that is allowed

**Comment by JonLiu1993** [comment]
@autoantwort ,please run the _vcpkg x-add-version ffmpeg --overwrite-version_ command then commit angin.

**Review by JonLiu1993 — COMMENTED** [review]
@autoantwort ,please set Port-Version: 3 to Port-Version: 4

**Comment by longnguyen2004** [comment]
@autoantwort I think you should go with this first, since it already LGTM.

**Comment by autoantwort** [comment]
> @autoantwort I think you should go with this first, since it already LGTM.

Ok, done

**Comment by strega-nil-ms** [comment]
Note to self: merge at same time as #17299

**Review by longnguyen2004 — APPROVED** [review]

**Comment by autoantwort** [comment]
> Note to self: merge at same time as #17299

#17299 has already been merged

**Review by JonLiu1993 — APPROVED** [review]

**Review by BillyONeal — APPROVED** [review]

**Comment by dan-shaw** [comment]
@autoantwort Can you resolve the conflicts?

**Review by PhoebeHui — APPROVED** [review]
Thanks for your PR!

**Pull request merged**
