### PR TITLE
[vcpkg] 32-bit linux triplet

### PR DESCRIPTION
**Pull request by smadurange**
32-bit linux triplet

- What does your PR fix? Fixes issue #10376

- Which triplets are supported/not supported? Have you updated the CI baseline?
NA.

- Does your PR follow the [maintainer guide]
Yes, I think so.

### CODE REVIEW

**Comment by linquize** [comment]
You have to modify vcpkg (roughly 3 places) to support linux x86 as well.

**Comment by smadurange** [comment]
@linquize  no wonder it seemed to work on my x64 host. What are the 3 places that require modification?

**Comment by linquize** [comment]
For example , in a x86 32-bit docker image, you have to use 32-bit gcc to compile vcpkg. 
And the default triplet should be x86. But vcpkg emit a compile error because the arch is not supported.

**Comment by smadurange** [comment]
Seems like a non-trivial change that requires work on vcpkg itself. Abandoning this PR.

**Comment by linquize** [comment]
Don't close pull request yet.
Typically, you cross compile x86 on x64 host. You have to add `-m32` flag.

check if `CMAKE_SYSTEM_PROCESSOR` is `x86_64`,
`VCPKG_C_FLAGS` and `VCPKG_CXX_FLAGS` should add `-m32`

**Comment by JackBoosY** [comment]
Pinging @smadurange  for response. Is work still being done for this PR?

**Comment by smadurange** [comment]
@JackBoosY Hi, no I am not working on this PR. I've pretty much switched to pacman now, I don't think I will work on this anymore.

**Comment by JackBoosY** [comment]
Closing this PR since it seems that no progress is being made. Please reopen if work is still being done.

**Pull request closed without merging**
