### PR TITLE
[opencv4] Update opencv4 to version 4.10.0

### PR DESCRIPTION
**Pull request by jfulem**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [ ] The "supports" clause reflects platforms that may be fixed by this new version.
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by jfulem** [comment]
@microsoft-github-policy-service agree

**Comment by jfulem** [comment]
@microsoft-github-policy-service agree


pá 16. 8. 2024 v 16:42 odesílatel microsoft-github-policy-service[bot] <
***@***.***> napsal:

**Comment by dg0yt** [comment]
This needs coordination with https://github.com/microsoft/vcpkg/pull/38928.

**Comment by dg0yt** [comment]
> This needs coordination with #38928.

Seriously.
Also for coordination with `opencv`, `opencv2`, `opencv3`.

**Comment by cenit** [comment]
for sure it would be bad to have ocv 4.10 without 4.9 first. Please in case you want to spend time on it helm me finishing the 4.9, then we can move to 4.10 asap.
i don't have time fixing regressions there

**Comment by cenit** [comment]
also most of the patches are still necessary, so the removal is just plain wrong

**Comment by jfulem** [comment]
When the patches are there it just does not progress anywhere so why are they needed?

**Comment by dg0yt** [comment]
The patches are needed because opencv's vendored find modules poorly cover transitive usage requirements for static linkage, and possibly also multi-config builds. Basically, that the key shortcoming of find modules.
Upstreaming the patches also isn't an option when depedencies don't provide official CMake config upstream.

**Pull request closed without merging**
