### PR TITLE
[cairo] Windows: Fix cairo dll definition

### LINKED ISSUE #17595: [cairo] CMake does not copy necessary dlls after glib/gtk port update.
**Describe the bug**
After PR https://github.com/microsoft/vcpkg/pull/13100, I'm not able to run my application becaue, CMake does not copy dlls next to the executeble. I'm using my own CMake module file (Findcairo.cmake) in order to setup cairo, but this does not work anymore. After configuring, the library is called cairo.lib (earlier this was cairod.lib for debug) and the dll is cairo-2.dll. If I start my application, the windows tells me, that there is no libcairo-2.dll. 

My module file is probably not the best, but can anyone help me how to set this up?

**Environment**
- OS: Windows 10 20H2
- Compiler: MSVC v16.9.3

Here's my Findcairo.cmake file:
```cmake
if (NOT WIN32)
    find_package(PkgConfig)
    if (PKG_CONFIG_FOUND)
        pkg_check_modules(_CAIRO cairo)

        SET(CAIRO_VERSION ${_CAIRO_VERSION})
        STRING (REGEX REPLACE "([0-9]+).([0-9]+).([0-9]+)" "\\1" num "${CAIRO_VERSION}")
        MATH (EXPR CAIRO_VERSION_MAJOR "${num}")
        STRING (REGEX REPLACE "([0-9]+).([0-9]+).([0-9]+)" "\\2" num "${CAIRO_VERSION}")
        MATH (EXPR CAIRO_VERSION_MINOR "${num}")
        STRING (REGEX REPLACE "([0-9]+).([0-9]+).([0-9]+)" "\\3" num "${CAIRO_VERSION}")
        MATH (EXPR CAIRO_VERSION_MICRO "${num}")
    endif (PKG_CONFIG_FOUND)
endif (NOT WIN32)

set(_CAIRO_ROOT_HINTS_AND_PATHS
  HINTS 
     $ENV{CAIRO}
     $ENV{CAIRO_DIR}
     ${CMAKE_FIND_ROOT_PATH}
     ${CAIRO_ROOT_DIR}
  PATHS
    ${CMAKE_FIND_ROOT_PATH}
    $ENV{CAIRO}/src
    /usr
    /usr/local
)

find_path(CAIRO_INCLUDE_DIR
    NAMES
        cairo.h
    HINTS
        ${_CAIRO_INCLUDEDIR}
        ${_CAIRO_ROOT_HINTS_AND_PATHS}
    PATH_SUFFIXES
        include
        "include/cairo"
)

if(NOT CAIRO_LIBRARY)
    FIND_LIBRARY(CAIRO_LIBRARY_RELEASE
        NAMES
            cairo
            cairo-static
        HINTS
            ${_CAIRO_LIBDIR}
            ${_CAIRO_ROOT_HINTS_AND_PATHS}
        PATH_SUFFIXES
            "lib"
            "local/lib"
    ) 

    FIND_LIBRARY(CAIRO_LIBRARY_DEBUG
        NAMES
            cairod
            cairo-staticd
        HINTS
            ${_CAIRO_LIBDIR}
            ${_CAIRO_ROOT_HINTS_AND_PATHS}
        PATH_SUFFIXES
            "lib"
            "local/lib"
    ) 

    include(SelectLibraryConfigurations)
    select_library_configurations(CAIRO)
endif()
set(CAIRO_LIBRARIES ${CAIRO_LIBRARY})

if (NOT CAIRO_VERSION)
    if (EXISTS "${CAIRO_INCLUDE_DIR}/cairo-version.h")
        file(READ "${CAIRO_INCLUDE_DIR}/cairo-version.h" CAIRO_VERSION_CONTENT)

        string(REGEX MATCH "#define +CAIRO_VERSION_MAJOR +([0-9]+)" _dummy "${CAIRO_VERSION_CONTENT}")
        set(CAIRO_VERSION_MAJOR "${CMAKE_MATCH_1}")

        string(REGEX MATCH "#define +CAIRO_VERSION_MINOR +([0-9]+)" _dummy "${CAIRO_VERSION_CONTENT}")
        set(CAIRO_VERSION_MINOR "${CMAKE_MATCH_1}")

        string(REGEX MATCH "#define +CAIRO_VERSION_MICRO +([0-9]+)" _dummy "${CAIRO_VERSION_CONTENT}")
        set(CAIRO_VERSION_MICRO "${CMAKE_MATCH_1}")

        set(CAIRO_VERSION "${CAIRO_VERSION_MAJOR}.${CAIRO_VERSION_MINOR}.${CAIRO_VERSION_MICRO}")
        set(CAIRO_VERSION_STRING CAIRO_VERSION)
    endif ()
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(
    cairo 
    REQUIRED_VARS 
        CAIRO_LIBRARIES 
        CAIRO_INCLUDE_DIR
    VERSION_VAR
        CAIRO_VERSION_STRING
)

MARK_AS_ADVANCED(
    CAIRO_INCLUDE_DIR 
    CAIRO_LIBRARY
    CAIRO_LIBRARIES)

```

### PR DESCRIPTION
**Pull request by Neumann-A**
closes #17595 (confirmed to work https://github.com/microsoft/vcpkg/issues/17595#issuecomment-830409807)

(similar fix as #14946 for fontconfig)

### CODE REVIEW

**Comment by JackBoosY** [comment]
Waiting for https://github.com/microsoft/vcpkg/pull/17586.

**Comment by Neumann-A** [comment]
@JackBoosY: Wrong PR? you probably ment #17610

**Comment by JackBoosY** [comment]
@Neumann-A Yeah...

**Comment by ras0219-msft** [comment]
LGTM, thanks for the continued fixes :)

**Pull request merged**
