### PR TITLE
Skip rarely needed maintainer tools when not available

### LINKED ISSUE #17057: [libidn2] build failure on osx pipeline
**Host Environment**
- OS: macOS CI
- Compiler: unknown

**To Reproduce**
Run pipeline of #17049

**Failure logs** 
https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/51476/artifacts?artifactName=failure%20logs%20for%20x64-osx&api-version=6.0&%24format=zip

autoconf-x64-osx-err.log:
```
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: running: autopoint --force
autoreconf: running: aclocal --force -I m4 -I unistring/m4
autoreconf: configure.ac: tracing
autoreconf: running: glibtoolize --copy --force
autoreconf: configure.ac: not using Intltool
autoreconf: running: gtkdocize --copy
Can't exec "gtkdocize": No such file or directory at /usr/local/Cellar/autoconf/2.71/share/autoconf/Autom4te/FileUtils.pm line 293.
autoreconf: error: gtkdocize failed with exit status: 2
```

**Additional context**
It seems to be similar to #16990

### PR DESCRIPTION
**Pull request by dg0yt**
This is a third alternative (after #17227/#17278 (CI provisioning) and #17317 (lightweight feature)) to solve the problem of missing maintainer tools `autopoint`, `gtkdocize`.
This is the fastest solution for vcpkg ports which don't really need to update to these parts of the build systems. It solves the issue both for CI and for vcpkg users. 
The tools are still used when provided by environment variables (set by the portfile or toolchain file), found in the host system, or of found in matching vcpkg tools directories.

---

- #### What does your PR fix?  
  Fixes #17057, #17098.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all, -/-

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  -/-

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  -/-

### CODE REVIEW

**Comment by JackBoosY** [comment]
cc @Neumann-A for review this PR.

**Comment by dg0yt** [comment]
- atk:x64-windows: Download error, unrelated
 - libmicrohttpd:x64-osx: Linker error, unrelated, except that both this PR and the error are related to the gettext port.
   ~~~
   Undefined symbols for architecture x86_64:
    "_CFArrayGetCount", referenced from:
        _add_system_trust in libgnutls.a(certs.o)
        __nl_language_preferences_default in libintl.a(langprefs.o)
    ~~~
    I assume that the missing symbol is in some `CoreF...` library, and a dependency is not properly carried. From config.log, the dependency exists in `/Users/vagrant/Data/installed/x64-osx/lib/libintl.a`, i.e. in the library created from vcpkg's gettext port.

 - fontconfig: Hard dependency on `autopoint`. This indicates an issue in this PR, because it worked before, so the new code should have found an existing `autopoint` program.

Maybe this PR is too invasive or too naive because it effectively pretends that these tools are available. It might be safer to touch those environment variables only in the ports which actually do not need to run these tools. OTOH, it seems to uncover hard dependencies.

**Comment by dg0yt** [comment]
> * fontconfig: Hard dependency on `autopoint`. This indicates an issue in this PR, because it worked before, so the new code should have found an existing `autopoint` program.

Actually, this was broken before. However, it is clear now that autopoint is a hard requirement for building fontconfig.

**Comment by dg0yt** [comment]
>  It might be safer to touch those environment variables only in the ports which actually do not need to run these tools.

This was picked up in #17419 (libidn2, waiting for merge) and #17420 (libtasn1, merged).
I'm closing this draft PR now. (But it gave useful insight.)

**Pull request closed without merging**
