### PR TITLE
[icu] Fix pc files

### LINKED ISSUE #22311: [icu] ICU port adds -lm in pkgconfig files for debug MSVC builds
**Describe the bug**
When ICU is built for Windows (MSVC) target with debug variant, its configure script adds -lm library to Libs.private property of pkgconfig files. As as I know, this library does not exist in MSVC toolchain. It is not used with dynamic linking, but static linking with pkgconfig results in linking error.

**Environment**
- OS: Windows
- Compiler: MSVC 19.29.30138

**To Reproduce**
1. ./vcpkg install icu:x64-windows-static pkgconf:x64-windows-static
2. Try to link to static ICU library by using pkgconfig
3. Try to build CMake project with following CMakeLists.txt: https://gist.github.com/equeim/851df8e69165e509d9a511d1071e5631,
dummy main.cpp and following CMake configuration command:
```
cmake -S \path\to\source -B \path\to\build -GNinja -DCMAKE_TOOLCHAIN_FILE=\path\to\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static -DPKG_CONFIG_EXECUTABLE=\path\to\vcpkg\installed\x64-windows-static\tools\pkgconf\pkgconf.exe -DCMAKE_BUILD_TYPE=Debug
```
2. Observe linking error `LINK : fatal error LNK1104: cannot open file 'm.lib'`

**Expected behavior**
Statically linking ICU using pkgconfig should work.

**Failure logs** 
[build.log](https://github.com/microsoft/vcpkg/files/7804370/build.log)

**Additional context**
I believe that passing `ac_cv_lib_m_floor=no` to configure script in icu/portfile.cmake for MSVC toolchain fixes the issue but I don't know whether it is the correct solution.

### PR DESCRIPTION
**Pull request by PhoebeHui**
Fixes https://github.com/microsoft/vcpkg/issues/22311

Remove '-lm' in icu pc files on windows.

Failures:
LINK : fatal error LNK1104: cannot open file 'm.lib'

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by strega-nil-ms** [comment]
I feel like the correct fix here is to use the Windows build system, as opposed to using autoconf? This is what `source/allinone/allinone.sln` is for...

**Comment by JackBoosY** [comment]
@strega-nil-ms We can build with mingW in Windows or optionally build its sln with msbuild.

**Comment by PhoebeHui** [comment]
@strega-nil-ms, the author of the icu port change msbuild to autoconf via https://github.com/microsoft/vcpkg/pull/965.

cc @codicodi

**Comment by strega-nil-ms** [comment]
Can we modify the faulty autoconf instead of modifying the resulting pkgconfig?

**Review by JackBoosY — APPROVED** [review]

**Pull request merged**
