### PR TITLE
[opencv] sfm module should depend on ceres

### PR DESCRIPTION
**Pull request by jasjuang**

### CODE REVIEW

**Comment by cenit** [comment]
why not explain your problem in the big PR I was trying to setup?

**Comment by jasjuang** [comment]
@cenit looks like you still need time to complete it and this is an independent increment improvement, why do you think this PR has to be bundled with yours?

**Comment by cenit** [comment]
to be honest, because this package (OpenCV) really needs some work before being useful, apart from simple dependencies in the control file. In that PR it is already way more functional than the normal distribution, and just some tests on that version would be good, with simple things like this perfect along the path. Since you try to be very active on OpenCV, a coordinated effort maybe would have been very beneficial.

**Comment by ras0219-msft** [comment]
Definitely we're all interested in working together here!

However, I can say that, at least from my side, it's a lot harder to review lots of changes at once (new OpenCV version, new patches, new features, etc). Having things split into nice, bite sized chunks like this makes it a _ton_ easier to pull in. Plus, we can pull in the parts that work without waiting for the parts that aren't quite there yet!

I'm sure that @jasjuang didn't mean to replace your PR in any way, it's just nice to get the easy wins in early while we're working on the harder ones (ffmpeg)!

**Comment by cenit** [comment]
ffmpeg is already done there. I am working toward completely remove all internal libraries rebuilt. Then a lot of tests should be done, to avoid what happened with the OpenCV 3.4.0 uncontrolled upgrade

**Comment by jasjuang** [comment]
@cenit To be honest with you, current OpenCV without #2764 works fine for me. I am not using OpenCV statically nor ffmpeg so I don't have the problems you are running into. The upgrade I did to 3.4.0 is not uncontrolled. I checked a few common feature package combinations and make sure it compiles and submit a PR. As I mentioned at #2798, it is impossible for me to test compilation all static, dynamic, uwp combining with all different possible feature packages, not to mention checking whether it works with downstream and then make a PR. I don't even think it's possible to do it on a CI because of how long it takes to compile. 

We are not going to stick to the old version just because it still works. We are going to update to the latest version. If I ran into a problem for my configuration with the update, I fix it just like this PR. Similarity, if you are ran into a problem with your configuration, you are more than welcome to update it just like what you are doing at #2764.

**Comment by cenit** [comment]
@jasjuang  and to be honest with you, the fact that the patches became just broken, anyway, testify that something went wrong with your PR. Independently from the fact that it was working or not in your specific case, those patches had to be fixed or removed. Not there and broken.
The "works for me" only attitude is a bad sign for the usefulness for others IMHO and, to be honest, I really hope it is not supported by the project itself. Otherwise I think I will just have to rethink our usage of the tool itself (vcpkg). Otherwise, we would be continuously at the mercy of anyone if we do not keep it under tight control.

**Comment by ras0219-msft** [comment]
I think all the relevant points have been said for now. Please feel free to email us at vcpkg@microsoft.com if you'd like to continue this thread further.

It is currently a US holiday, so i will review this PR tomorrow.

**Pull request merged**
