### PR TITLE
[many ports] Upgrades to 2019.10.29

### PR DESCRIPTION
**Pull request by ras0219-msft**

### CODE REVIEW

**Comment by JackBoosY** [comment]
`spdlog` and `folly` was upgrading by PR #8779 #8765.

**Comment by JackBoosY** [comment]
The `asio` upgrade caused some port builds to fail. It is being processed in #8800.

**Comment by JackBoosY** [comment]
The remaining questions are:
1. VTK:
```
Using cached binary package: /Users/vagrant/azure_agent/_work/2/s/archives/a9/a9ba954790c08d6948ba208e3ee9c96352d490b5.zip
file #6:  bad zipfile offset (local header sig):  994599
file #7:  bad zipfile offset (local header sig):  1590886
file #8:  bad zipfile offset (local header sig):  2962014
file #9:  bad zipfile offset (local header sig):  4181092
file #10:  bad zipfile offset (local header sig):  7305310
file #11:  bad zipfile offset (local header sig):  25915411
file #12:  bad zipfile offset (local header sig):  26778819
file #13:  bad zipfile offset (local header sig):  29903331
file #14:  bad zipfile offset (local header sig):  35869370
file #15:  bad zipfile offset (local header sig):  36206416
file #16:  bad zipfile offset (local header sig):  50290662
file #17:  bad zipfile offset (local header sig):  50408265
file #18:  bad zipfile offset (local header sig):  50914905
Failed to decompress archive package
Error: Building package vtk:x64-osx failed with: BUILD_FAILED
```
I think it's a CI system error.

2. sfgui:
```
CMake Error in CMakeLists.txt:
  Imported target "CoreFoundation" includes non-existent path

    "/System/Library/Frameworks/CoreFoundation.framework/Headers"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```
Also a CI system error. Missing framework in the OSX system?

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
Vxl needs to wait for official support for the latest openjpeg2 before updating, see [#627](https://github.com/vxl/vxl/issues/627).

**Comment by JackBoosY** [comment]
It looks like there is a problem with the llvm package archive on the CI system, causing the regression of linux.

**Comment by ras0219-msft** [comment]
Going to regenerate and reopen this.

**Pull request closed without merging**
