### PR TITLE
Prevent python3 build failure

### PR DESCRIPTION
**Pull request by heydojo**
If VCPKG_BUILD_TYPE release is set inside a
triplet, then the build will fail because
the port file attempts to deal with debug
files which will never exist. The changes
in this patch allow the build to succeed
if VCPKG_BUILD_TYPE release is stipulated
using a triplet before a build of the
python3 port is initiated.

### CODE REVIEW

**Comment by heydojo** [comment]
The CI/CD integration appears to be misconfigured or malfunctioning.
The vcpkg-windows-PR job failed with:

```
Building package boost-logic[core]:x86-windows...
Using cached binary package: C:\vsts\_work\2\s\archives\75\75a5a57560253dffeae555313d5ca9ebc9059997.zip
Error: while parsing the Binary Paragraph for boost-logic:x86-windows
Error: There are invalid fields in the control file of boost-logic:x86-windows
The following fields were not expected:

    Type
…
Different source may be available for vcpkg. Use .\bootstrap-vcpkg.bat to update.

CI test is complete
##[error]PowerShell exited with code '1'.
##[section]Finishing: ** Build vcpkg and test ports **
```
So not doing shallow clones for each build?

And the vcpkg-Linux-PR failed with:
```

Downloading artifacts for build: 18440
##[error]Artifact raw xml results not found for build 18440. Please ensure you have published artifacts in any previous phases of the current build.
##[section]Finishing: Download Build Artifacts
```

Because the error:

`##[warning]Directory '/ci/myagent/_work/1/a/xml-results' is empty. Nothing will be added to build artifact 'raw xml results'.`

was displayed in the PR test, which then caused the analysis stage to fail.
And yet the OSX build and test and analysis went through just fine.

Hopefully the issues are an easy fix.

**Comment by cbezault** [comment]
The team is trying to fix this issue now. Mine and Rastaban's PR messed up a lot of the binary caches that the CI relies on.

**Comment by cbezault** [comment]
Could you also bump the version in the CONTROL file?

**Review by cbezault — CHANGES_REQUESTED** [review]
Looks good minus the CONTROL file.

**Comment by heydojo** [comment]
> The team is trying to fix this issue now. Mine and Rastaban's PR messed up a lot of the binary caches that the CI relies on.

Oh noes... 😫

> Could you also bump the version in the CONTROL file?

Yeah, I'll try a refresh from origin/master and push back to this PR. Hopefully it will go through OK.

Thanks for the heads up @cbezault and good luck getting it fixed!

**Review by cbezault — APPROVED** [review]

**Comment by grdowns** [comment]
Thanks for the PR, @heydojo!

**Comment by heydojo** [comment]
No problem, glad it made it in! Thanks guys!

**Pull request merged**
