### PR TITLE
[WIP] Add a Homepage URL entry for vcpkg ports

### LINKED ISSUE #1642: Links to project source repository in CONTROL?
Currently port description (ports\name\CONTROL) contains only project name, version and its short description. 

So it is hard to find out where this repository lives (especially if its name is not unique), and we have to dig into portfile.cmake to find the exact link to the port.

Wouldn't it be better to add an URL of the repository in CONTROL file? For example, Rust crates [contain](http://doc.crates.io/manifest.html#package-metadata) "documentation", "homepage" and "repository" URLs, but for us it would be enough to have at least "homepage" or "repository" link in the port description.

### PR DESCRIPTION
**Pull request by pravic**
Fixes #1642.

When browsing new ports, it is often hard to understand their purpose. Or where they come from (without looking into `portfile.cmake`). Some examples: [http-parser](https://github.com/Microsoft/vcpkg/blob/25b8f25dadcb2af28ae5be2e6d31884ca67f1b26/ports/http-parser/CONTROL), [ode](https://github.com/Microsoft/vcpkg/blob/25b8f25dadcb2af28ae5be2e6d31884ca67f1b26/ports/ode/CONTROL), and lots of others.

The idea was to add a human readable URL in port's description, thus `vcpkg` could print it in `vcpkg list` and `vcpkg search` results. However I am not sure about the best place for URL at the moment, so it is an open question.

This PR does not implement corresponding changes in vcpkg source (to support the new field), it just adds a `Homepage` entry to almost all ports (except empty ones like winsock2 or atlmfc and except modularized subports like `qt5-` or `boost-`). URLs are extracted from `vcpkg_from_github`, `vcpkg_from_bitbucket`, `vcpkg_download_distfile` so they can be not perfect, but it is the best I can do :)

### Unresolved questions:

0. The name of the homepage entry in CONTROL files. `Homepage`? `URL`? `Repository`? Actually, most of repositories use multiple entries (`homepage` and `repository` in Rust crates, homepage, download and issue tracker URLs in pypi and so on).
1. Do we need to print URLs or we can leave them in CONTROL files just for manual reading? Personally, I would go without print.
2. If we are going to print, when and where? Descriptions often quite big and do not fit in one line in console.
3. May be introduce an additional command similar to [`cargo-show`](https://github.com/g-k/cargo-show) (`pip show`, `npm view`, etc.) which will print all information about particular port?

### CODE REVIEW

**Comment by jasjuang** [comment]
This is a great idea

**Comment by soul4soul** [comment]
0.  I vote for `Homepage`. It should be a URL to the webpage which is the primary entry point into learning about the port. For software which has a dedicated website it would be a URL to that website. Other software with no dedicated website would be a URL to the github repo.
0. See 3.
0. See 3.
0. I vote for having a show command which would print all of the information about a particular port.

Why would not include `HomePage` for each subport too?

**Comment by luzpaz** [comment]
This would be very useful. Is there an ETA on when this will be merged ?

**Comment by Rastaban** [comment]
The only failure is shogun:x64-linux and looks like it is unrelated to this PR.  It should probably not hold up this PR.

**Comment by Voskrese** [comment]
@Rastaban add in templates ?
vcpkg\scripts\templates\CONTROL.in

```
Source: @PORT@
Version: 
#Homepage: 
Description: 
#Build-Depends: 
```

**Pull request merged**
