### PR TITLE
[glew] fix pkgconfig

### PR DESCRIPTION
**Pull request by Neumann-A**
depends #11550

### CODE REVIEW

**Review by NancyLi1013 — CHANGES_REQUESTED** [review]
Could you please update this

```
file(INSTALL ${CMAKE_CURRENT_LIST_DIR}/vcpkg-cmake-wrapper.cmake DESTINATION ${CURRENT_PACKAGES_DIR}/share/glew )
file(INSTALL ${SOURCE_PATH}/LICENSE.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/glew RENAME copyright)
```
as

```
file(INSTALL ${CMAKE_CURRENT_LIST_DIR}/vcpkg-cmake-wrapper.cmake DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} )
file(INSTALL ${SOURCE_PATH}/LICENSE.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
```
?

**Comment by Neumann-A** [comment]
Ok this requires a *.pc files for `glu` and `gl` on windows.

**Comment by NancyLi1013** [comment]
Closing this PR for now since this is inactive for a long time. If you'd like to continue working on it, please reopen and ping us! @Neumann-A

**Pull request closed without merging**
