### PR TITLE
[fmt] Update to 10.0.0

### PR DESCRIPTION
**Pull request by FtZPetruska**
- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [X] SHA512s are updated for each updated download
- [X] The "supports" clause reflects platforms that may be fixed by this new version
- [X] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [X] Any patches that are no longer applied are deleted from the port's directory.
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by FtZPetruska** [comment]
coolprop and seacas failures come from a breaking change with 10.0 where enums require a custom formatter.

spdlog 1.11 has known issues with the latest fmt version. It has already been fixed upstream but no release contain this fix. (https://github.com/gabime/spdlog/commit/0ca574ae168820da0268b3ec7607ca7b33024d05)

**Comment by Cheney-W** [comment]
Are the upstream projects of `coolprop` and `seacas` aware of this issue? If they are not aware, could you report this issue to the upstream projects to seek a solution?
As for `spdlog`, could you use a patch to apply the upstream fix?

**Comment by Cheney-W** [comment]
If updating a port causes issues with downstream ports, it is necessary to fix those downstream ports as well.

**Review by Cheney-W — DISMISSED** [review]

**Review by JavierMatosD — COMMENTED** [review]
Has upstream been notified of this issue/ are they planning on fixing it? We would prefer to avoid patching whenever possible and some of these patches are very large. If upstream is aware of the issue and working on the solution, it might be best to wait for their update. 

Additionally, I see this patch being added to the `coolprop` port, but I don't see it being applied in the portfile.

**Comment by FtZPetruska** [comment]
> Has upstream been notified of this issue/ are they planning on fixing it? We would prefer to avoid patching whenever possible and some of these patches are very large. If upstream is aware of the issue and working on the solution, it might be best to wait for their update.
> 
> Additionally, I see this patch being added to the `coolprop` port, but I don't see it being applied in the portfile.

I hear your concerns, regarding upstream:
- CacheLib has been notified and provided a patch https://github.com/facebook/CacheLib/issues/235
- WasmEdge has been notified and provided a patch https://github.com/WasmEdge/WasmEdge/issues/2501
- spdlog had the issue already fixed https://github.com/gabime/spdlog/commit/0ca574ae168820da0268b3ec7607ca7b33024d05
- seacas has been notified and the upstream patch is used
  - https://github.com/sandialabs/seacas/issues/382
  - https://github.com/sandialabs/seacas/commit/5a576de57ee1664d845c83f552f2100cc9303a26
- CoolProp has been notified and the upstream patch is used
  - https://github.com/CoolProp/CoolProp/issues/2251
  - https://github.com/CoolProp/CoolProp/commit/d248c75a43aabdcdf01c672963291ab05d5e5e97
- OpenImageIO has been notified and the upstream patch is used
  - https://github.com/CoolProp/CoolProp/issues/2251
  - https://github.com/OpenImageIO/oiio/commit/f27a974c34d068050e8ee097174652c565cefff3
  - A [new release was made today](https://github.com/OpenImageIO/oiio/releases/tag/v2.4.11.1) including the patch, I will go ahead and update the port version instead os using the patch when I rebase to fix the merge conflicts.

Regarding Coolprop's patch not being added to the portfile, there already was a `fmt-fix.patch` that was updated to include fmt 10 support.

Hopefully this addresses your concerns, let me know if there is any change you wish to be made.

**Comment by FtZPetruska** [comment]
It seems that updating `openimageio` to the latest release fixes fmt 10 issues, but has other build issues specifically on MSVC unrelated to fmt.

I went ahead and opened a standalone PR to update the port since it's no longer related to this PR. (https://github.com/microsoft/vcpkg/pull/31489)

**Pull request merged**
