### PR TITLE
Use msys64 on 64bit systems

### LINKED ISSUE #954: ffmpeg does not build due to msys problems
This is with vcpkg git master on Windows 10 Creators Update x64:

latte C:\src\vcpkg > .\vcpkg.exe install ffmpeg --triplet x64-windows
The following packages will be built and installed:
    ffmpeg:x64-windows
Building package ffmpeg:x64-windows...
-- CURRENT_INSTALLED_DIR=C:/src/vcpkg/installed/x64-windows
-- DOWNLOADS=C:/src/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/src/vcpkg/packages/ffmpeg_x64-windows
-- CURRENT_BUILDTREES_DIR=C:/src/vcpkg/buildtrees/ffmpeg
-- CURRENT_PORT_DIR=C:/src/vcpkg/ports/ffmpeg/.
-- Downloading http://ffmpeg.org/releases/ffmpeg-3.2.4.tar.bz2...
-- Downloading http://ffmpeg.org/releases/ffmpeg-3.2.4.tar.bz2... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Extracting source C:/src/vcpkg/downloads/ffmpeg-3.2.4.tar.bz2
-- Extracting done
-- Building ffmpeg for Release
     13 [main] bash (13536) C:\src\vcpkg\downloads\tools\msys2\msys32\usr\bin\bash.exe: *** fatal error - cygheap base mismatch detected - 0x1365408/0x12F5408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
[...]

The first thing I noticed is msys i686 is downloaded even on x64. 32bit builds are more suspect to heap mismatches due to limited adress space. Also the version of msys2 downloaded is really old.

### PR DESCRIPTION
**Pull request by ismail**
Might fix #954

### CODE REVIEW

**Comment by ismail** [comment]
This indeed fixes #954 you just need to delete C:/src/vcpkg/downloads/tools/msys2 first.

**Comment by ras0219-msft** [comment]
Thanks for making this PR! It definitely does fix #954.

I switched the script to use `ENV{PROCESSOR_ARCHITECTURE}` instead of `TRIPLET_SYSTEM_ARCH`, because it's fine to use 64-bit msys2 if you're a 64-bit OS targeting x86.

I also separated the stamp file for each, so both can live side-by-side and existing users will seamlessly upgrade.

**Comment by ismail** [comment]
Sounds good but PROCESSOR_ARCHITEW6432 doesn't seem to be defined on my Windows 10 x64 system (creators update).

**Comment by ras0219-msft** [comment]
It's the "WoW" version of `PROCESSOR_ARCHITECTURE`. If you happen to have a 32-bit version of CMake, then you'll get `PROCESSOR_ARCHITECTURE=x86` and `PROCCESSOR_ARCHITEW6432=x64`, but if you have 64-bit then you'll get `PROCESSOR_ARCHITECTURE=x64`.

**Comment by ismail** [comment]
It doesn't work for me though, it still downloads 32bit msys. Is it might be because vcpkg.exe is 32bit?

**Comment by ras0219-msft** [comment]
Hmm. Could you first make sure you re-bootstrap, then run `vcpkg env` (which will drop you into a `cmd.exe` with the same environment we build in), then run `set` to print the environment variables?

**Comment by ismail** [comment]
PROCCESSOR_ARCHITEW6432 is actually AMD64 instead of x64, so the relevant line in vcpkg_acquire_msys.cmake should be updated.

**Comment by ras0219-msft** [comment]
Ouch, that was a pretty bad bug on my part. Thank you for noticing and calling it out!

**Comment by ismail** [comment]
Great! Thanks.

**Pull request merged**
