### PR TITLE
[gtk] Incorporate fixes from https://gtk-rs.org/docs-src/requirements.html

### PR DESCRIPTION
**Pull request by ras0219-msft**
This PR attempts to address the package deficiencies listed in https://gtk-rs.org/docs-src/requirements.html without the massive overhaul required to switch to meson. From the docs at time of submission (2019-07-10):

> MSVC toolchain
> 1. Install GTK using the instructions on the GTK website. This will take some time. Once it’s finished, make a note of the folder installed\x86-windows (32-bit)/installed\x64-windows (64-bit); these instructions will refer to it as %VCPKGDIR%.
> 2. Add %VCPKGDIR%\bin to the beginning of your PATH environment variable.
> 3. Set the GTK_LIB_DIR environment variable to %VCPKGDIR%\lib.
> 4. Create the following symlinks. (NTFS has supported symlinks since Windows Vista, but prior to the Windows 10 Creators Update it required elevated privileges. Copying the files also works, but you’ll need to do it again when GTK is updated.)
> %VCPKGDIR%\lib\gtk-3.0.lib points to %VCPKGDIR%\lib\gtk-3.lib.
> %VCPKGDIR%\lib\gdk-3.0.lib points to %VCPKGDIR%\lib\gdk-3.lib.
> %VCPKGDIR%\bin\gtk-3.0.dll points to %VCPKGDIR%\bin\gtk-3.dll.
> %VCPKGDIR%\bin\gdk-3.0.dll points to %VCPKGDIR%\bin\gdk-3.dll.
> 5. Create the folder %VCPKGDIR%\etc\gtk-3.0. Inside it, create the file settings.ini:
> [Settings]
> gtk-theme-name=win32
>
> Possible problems
> unresolved external symbol gtk_font_chooser_level_get_type
> This is a bug in version 0.6 of gtk-rs with versions of GTK prior to 3.22.30; either use gtk-rs from Git directly or backport the fix into the copy of gtk-rs in your Cargo registry.
> 
> process didn't exit successfully (exit code: 0xc0000139, STATUS_ENTRYPOINT_NOT_FOUND)
> %VCPKGDIR%\bin is too late in the PATH environment variable, and DLLs for other programs are being found before the ones installed alongside GTK. Move %VCPKGDIR%\bin earlier in your PATH and try again.

This PR will rename the import lib files to be `gtk-3.0.lib` by default, removing step 4. It will also create the `settings.ini` required in step 5. AFAIK, creating the DLL symlinks should not be needed; the .lib files will still be referencing the "old" names (gtk-3.dll).

We can't directly solve step 2 and step 3 because those involve modifying global system state, however step 2 may be solvable by the gtk-rs crate or vcpkg-rs crate if they copy the DLLs app-local to the produced output. Via the vcpkg-rs crate, step 3 may also not be needed.

@sdroege I saw you had a lot of good feedback and knowledge on various threads -- could you comment on whether the above is an accurate assessment?

### CODE REVIEW

**Comment by sdroege** [comment]
The main problem with the gtk from vcpkg is that it does not install any of the resources (icons, etc) to be able to actually run GTK applications. I think that's not addressed in this PR yet? I'd really recommend to not reinvent the GTK build system here. Especially not if there's nobody to actually maintain it and bring it in a good shape. Rather use the meson-based build system that GTK has since the last release. That only requires ninja or msbuild, and Python 3.

For the actual changes
2. I'd say that this is just normal environment setup stuff anybody using vcpkg or generally doing development on Windows has to do. You need to make sure your stuff is in `PATH`, and ideally in an order to not run into DLL hell. One big problem with GTK that I'm aware of is that there are often incompatible DLLs of GTK dependencies in the `PATH` before GTK, and that's why there's 2) here. But that's really just environment setup and nothing vcpkg should take care off IMHO.
3. I don't know the details of `GTK_LIB_DIR` but at least other GNOME-related libraries don't need such a thing and instead work relatively via the module path of their main library. I don't know why the `GTK_LIB_DIR` is needed exactly with GTK.
4. it would make sense to use the naming of DLLs used by the GTK project. Which AFAIK is gtk-3.0.dll and not gtk-3.dll. Just renaming the .lib file is not sufficient for e.g. the C#/.NET bindings that are loading the DLL at runtime.

**Comment by JackBoosY** [comment]
@sdroege I tried to rebuild the code about gtk but found some errors.

**Comment by sdroege** [comment]
> @sdroege I tried to rebuild the code about gtk but found some errors.

@JackBoosY I'm not responsible for the cmake build system in vcpkg, it's broken by design.

**Comment by JackBoosY** [comment]
@sdroege Yes, It's broken. We need to do a lot of work to patch `CMakeLists.txt`, so I tend to use nmake to build vtk.

**Comment by sdroege** [comment]
> @sdroege Yes, It's broken. We need to do a lot of work to patch `CMakeLists.txt`, so I tend to use nmake to build vtk.

Use meson to build GTK. Anything else will be broken again sooner or later.

**Comment by sdroege** [comment]
Was this solved somehow now?

**Pull request closed without merging**
