### PR TITLE
[harfbuzz] update to 2.8.2

### LINKED ISSUE #19563: [harfbuzz] update to 2.8.2
Library name: **harfbuzz**

New version number: **2.8.2**

Other information that may be useful (release notes, etc...)

https://github.com/harfbuzz/harfbuzz/releases/latest

### PR DESCRIPTION
**Pull request by JonLiu1993**
Fix #19563 
Update harfbuzz to the latest version 2.8.2

All featurse are tested successfully in the following triplet:
- x64-windows

- Feature 'glib' only supports dynamic library linkage.
- Feature 'coretext' os only available on OSX

### CODE REVIEW

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
Depends on #19633.

**Comment by xavier2k6** [comment]
@NancyLi1013 ref.: https://github.com/microsoft/vcpkg/issues/19563#issuecomment-901828446

**Comment by BillyONeal** [comment]
Thanks for the update!

**Pull request merged**
