### PR TITLE
[implot] Update to 0.9

### PR DESCRIPTION
**Pull request by RT2Code**
https://github.com/epezent/implot/releases/tag/v0.9

I also removed the unused and deprecated patch file.

### CODE REVIEW

**Comment by autoantwort** [comment]
You forgot to commit the `vcpkg.json` file

**Comment by RT222** [comment]
Whoops, fixed. Thanks!

**Comment by autoantwort** [comment]
And don't change the version files by hand. Use `./vcpkg x-add-version --overwrite-version implot`

**Comment by RT222** [comment]
That's what I do. ;)

**Comment by autoantwort** [comment]
Oh sorry, I didn't read correctly when I looked at the changes :)

**Comment by autoantwort** [comment]
But you have to run `./vcpkg x-add-version --overwrite-version implot` again because the vcpkg.json file was changed (committed later) after the first `./vcpkg x-add-version --overwrite-version implot`

**Comment by RT222** [comment]
Ah yes you're right, sorry about that. It's fixed.

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
LGTM, thanks for your PR @RT222.

**Comment by ras0219-msft** [comment]
LGTM, thanks for the PR!

**Pull request merged**
