### PR TITLE
[libwebsockets] Extend LWS build params with gencrypto & tls options

### PR DESCRIPTION
**Pull request by zbroyar**
I propose to extend LWS build options list with LWS_WITH_GENCRYPTO=ON and LWS_WITH_TLS=ON

This extension does not require any additional libraries or fixes but extends LWS functionality with useful stuff.

Thanks in advance.

### CODE REVIEW

**Review by PhoebeHui — CHANGES_REQUESTED** [review]
Could you also update the Port-Version in CONTROL file?

From
Version: 4.1.3

to 
Version: 4.1.3
Port-Version: 1

**Comment by zbroyar** [comment]
Added. Please, have a look :-)

**Review by PhoebeHui — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
