### PR TITLE
[fixed-string] Update to 0.1.1

### PR DESCRIPTION
**Pull request by chausner**
**Describe the pull request**

- #### What does your PR fix?  
  Updates fixed-string to 0.1.1

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  As before, Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run ./vcpkg x-add-version --all and committed the result?  
  Yes

### CODE REVIEW

**Comment by Thomas1664** [comment]
Please stop doing this. You are clearly using a bot. Although I like your approach I don't think you should opening that many PRs. Enaugh for today!

**Comment by Thomas1664** [comment]
I would like to see an issue with a list of all outdated ports first. Then you can agree with the maintainers on how many PRs you can open per day/ week

**Comment by chausner** [comment]
> Please stop doing this. You are clearly using a bot. Although I like your approach I don't think you should opening that many PRs. Enaugh for today!

@Thomas1664 Thanks for your message.

I am not using a bot but manually updating and testing every port locally. I do have some scripts to make the updates more efficient and submit the PR automatically. I am not choosing random ports to update but have focused on those that had their last release farthest in the past, and can be easily updated without requiring changes to patches. For every update, I add `license` if missing, change `version-string` to the appropriate one version type, change `vcpkg_configure_cmake` to `vcpkg_cmake_configure` and surround string-interpolated values with quotes (as is suggested for newer ports).

I'll stop creating more of these PRs until a maintainer confirms if it is fine or not, or if there is a better way to submit batch updates.

**Comment by Thomas1664** [comment]
> I'll stop creating more of these PRs until a maintainer confirms if it is fine or not, or if there is a better way to submit batch updates.

You won't hear anything from the maintainers until Monday (I think it's not a holiday in the US). Until then you have the chance to open many PRs and I don't think maintainers are happy if you overdo those updates. Furthermore, I think it's better to ask for approval _before_ doing this and not for forgiveness after you already opened dozens of PRs.

Don't get me wrong: I really like your approach and I already worked on creating a script to auto update ports.

**Comment by dg0yt** [comment]
FTR the maintainers didn't complain about these contributions last year. 
https://github.com/microsoft/vcpkg/graphs/contributors?from=2021-09-01&to=2021-12-31&type=c

**Comment by mathisloge** [comment]
> Please stop doing this. You are clearly using a bot. Although I like your approach I don't think you should opening that many PRs. Enaugh for today! 

> Until then you have the chance to open many PRs and I don't think maintainers are happy if you overdo those updates.

IMHO those statements shouldn't come from community members without maintainers having complained so far. IMO it is a bit rude since those PRs all are updating ports acordings to the maintainer guide. Such statements can quickly be misunderstood and discourage other contributors from helping the project in the future. You never know how a sentence will be taken.

**Comment by chausner** [comment]
Thanks for all your comments. While I have done these batch updates in the past without maintainers complaining, I do see @Thomas1664's point that they could overwhelm the review process if done in large batches. So I do think it's a good point in time to hear the maintainers' opinion.

**Comment by Thomas1664** [comment]
> IMHO those statements shouldn't come from community members without maintainers having complained so far. IMO it is a bit rude since those PRs all are updating ports acordings to the maintainer guide. Such statements can quickly be misunderstood and discourage other contributors from helping the project in the future. You never know how a sentence will be taken.

Sorry if my comment was root/ misunderstood.
I agree with you that maintainers are in charge of deciding how many PRs are enough:
>Then you can agree with the maintainers on how many PRs you can open per day/ week.

All I wanted to say was: "Don't open like 50+ at once". It is obvious that maintainers can't review like 50+ PRs at once and in this case I think it's ok for community members to point that out. In the situation I made the comment there was like every few minutes a new PR and I really thought it would go up to like 50 or even more. I couldn't know that this was ending at ~20 PRs. If I saw this number of new PRs by @chausner after he made his last one, I wouldn't have written this comment.

To be clear:
- I really love that you, @chausner, take the effort to keep those ports up to date
- I never wanted to say "Don't update ports"
- I don't claim any kind of authority

**Comment by Thomas1664** [comment]
Furthermore, I want to suggest that we keep track of outdated ports somehow - either with an issue or even with some GH Actions/ bot

**Comment by Thomas1664** [comment]
@chausner I'm currently trying to remove docs/tests/examples from as many ports as possible. It would be nice if we could team up somehow to get both done at once.

**Comment by dg0yt** [comment]
> Furthermore, I want to suggest that we keep track of outdated ports somehow - either with an issue or even with some GH Actions/ bot

Start here: https://repology.org/repository/vcpkg

**Comment by Thomas1664** [comment]
> Start here: https://repology.org/repository/vcpkg

If those figures are correct, at least 450 ports or 25% are outdated. If 10 ports were updated per day (weekends excluded), it wold take 9 weeks to update every port.
The process of keeping ports up to date should really be automated, although this isn't possible right now giving deprecated cmake, patches, missing license, generally low quality portfiles, etc.

**Comment by dg0yt** [comment]
@Thomas1664 Let's keep off-topic discussions out of this PR.

**Review by LilyWangLL — APPROVED** [review]

**Comment by strega-nil-ms** [comment]
Thanks!

**Pull request merged**
