### PR TITLE
[expat] Delete docs

### PR DESCRIPTION
**Pull request by Thomas1664**
**Describe the pull request**

- #### What does your PR fix?
  Port installs by default readme and changelog

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  unchanged

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

### CODE REVIEW

**Comment by JonLiu1993** [comment]
@Thomas1664 , This is error log:
````
"D:/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/bin/cmake.exe" -E chdir "D:/buildtrees/discordcoreapi/x64-windows-dbg" "D:/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/bin/cmake.exe" -S "D:/buildtrees/discordcoreapi/src/ccf17b10f0-e6ad1b3682.clean" "-DCMAKE_MAKE_PROGRAM=D:/downloads/tools/ninja/1.10.2-windows/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/a/1/s/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v143" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/a/1/s/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/a/1/s" "-D_VCPKG_INSTALLED_DIR=D:/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-DCMAKE_DISABLE_SOURCE_CHANGES=ON" -G "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=D:/packages/discordcoreapi_x64-windows/debug"
-- The CXX compiler identification is MSVC 19.31.31104.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.31.31103/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Curl!
-- Found FFMPEG!
-- Found Glib!
-- Found OpenSSL!
-- Found Opus!
-- Found Sodium!
-- Copying a file...
CMake Error at Library/CMakeLists.txt:38 (configure_file):
  Permission denied


-- Copying a file...
-- Copying a file...
-- Configuring incomplete, errors occurred!
See also "D:/buildtrees/discordcoreapi/x64-windows-dbg/CMakeFiles/CMakeOutput.log".
````

**Comment by Thomas1664** [comment]
This is strange. I tested it locally on the same triplet without errors. May retriggering CI solve the issue?

**Comment by JonLiu1993** [comment]
> This is strange. I tested it locally on the same triplet without errors. May retriggering CI solve the issue?

I have rerun ci before replying to you, but it has not been solved

**Comment by dg0yt** [comment]
> See also "D:/buildtrees/discordcoreapi/x64-windows-dbg/CMakeFiles/CMakeOutput.log".

Not expat.

**Comment by Thomas1664** [comment]
This is very strange. I found out that the issue actually comes from `ffmpeg` and likely has nothing to do with my PR because ffmpeg doesn't depend on expat (verified by removing expat: ffmpeg doesn't want to install expat). 
@JonLiu1993 Can you try to install `ffmpeg:x64-windows` on a clean environment from master to verify this?

**Comment by Thomas1664** [comment]
Furthermore, notice that x64-windows now succeeds and x64-osx now fails because of a vcpkg crash

**Comment by JackBoosY** [comment]
The regression is `discordcoreapi:x64-windows`.

**Comment by dg0yt** [comment]
> x64-osx now fails because of a vcpkg crash

This happens sometimes. https://github.com/microsoft/vcpkg/issues/21905 item 2.

**Comment by Thomas1664** [comment]
@JonLiu1993 CI succeeds now

**Review by JonLiu1993 — APPROVED** [review]

**Comment by strega-nil-ms** [comment]
Thanks!

**Pull request merged**
