### PR TITLE
Add NDK r26 to CI image

### PR DESCRIPTION
**Pull request by dg0yt**

### CODE REVIEW

**Comment by dg0yt** [comment]
@BillyONeal For https://github.com/microsoft/vcpkg/pull/35851#issuecomment-2095368686.

**Review by Cheney-W — DISMISSED** [review]

**Comment by BillyONeal** [comment]
Should we add r26 or just outright replace r25?

**Comment by dg0yt** [comment]
> Should we add r26 or just outright replace r25?

No. Outright replacement will break CI. You also need #35851 minus its NDK download.

But once the NDK is available (this PR), #35851 can simply include a change to override ANDROID_NDK_HOME in the pipeline. Then that PR could be ready to review and to merge to make the actual switch. And the old NDK could be removed after that.

And in the meantime you may think about raising the Android API level to 24 (which means devices running Android 7.0, available sice 2016) together wth the NDK switch. It will reduce CI validity for users targeting older devices. But it will significantly increase overall CI coverage. See ci.baseline.txt changes in the other PR.  
https://apilevels.com/

**Review by BillyONeal — APPROVED** [review]

**Comment by BillyONeal** [comment]
Done, thanks!

**Pull request merged**
