### PR TITLE
[crc32c] add license

### PR DESCRIPTION
**Pull request by Lex-2008**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] SHA512s are updated for each updated download
- [ ] The "supports" clause reflects platforms that may be fixed by this new version
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [ ] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by Cheney-W** [comment]
@Lex-2008 
Could you sign our Contributor License Agreement based on the robot's prompts?

**Comment by Lex-2008** [comment]
Thanks for the reminder, @Cheney-W! Sorry for the delay, need to sync with my employer first.

**Comment by Lex-2008** [comment]
@microsoft-github-policy-service agree company="reMarkable"

**Comment by Lex-2008** [comment]
Sorry for the delay, signed now!

@Cheney-W: do you want me to rebase these changes to latest master, or is this PR fine as is?

**Comment by Cheney-W** [comment]
Yes, this PR is fine.

**Review by Cheney-W — APPROVED** [review]

**Pull request merged**
