### PR TITLE
Now able to build the Microsoft/Angle that can be leveraged for UWP

### PR DESCRIPTION
**Pull request by johanlindfors**
This is a first attempt at creating a new package, this is for github.com/Microsoft/angle which is the Microsoft version of Angle, which can be used to UWP development.

### CODE REVIEW

**Comment by LarryIII** [comment]
I am seeing new build failures on the following ports with this PR. Let me know if you need build log.
```
Processing arm64-windows                  452 vs 452
    ms-angle                                                    Fail
Processing x64-linux                      585 vs 585
    ms-angle                                                    Fail
Processing x64-osx                        577 vs 577
    ms-angle                                                    Fail
Processing x64-uwp                        431 vs 431
    ms-angle                                                    Fail
Processing x64-windows                    856 vs 856
    ms-angle                                                    Fail
Processing x64-windows-static             759 vs 759
    ms-angle                                                    Fail
```

**Comment by johanlindfors** [comment]
Thanks for reporting this issue @LarryIII. I have updated the PR with the latest from master and also included the fix for this issue. Please try again. Please be aware that I don't expect this to work on OSX and/or Linux since its primary target is Windows and/or UWP.

**Comment by LarryIII** [comment]
@johanlindfors Thanks for creating the new commit again. Here is the latest result.
```
Processing arm64-windows                  466 vs 466
    ms-angle                                                    Fail
Processing x64-linux                      608 vs 608
    ms-angle                                                    Fail
Processing x64-osx                        599 vs 599
    ms-angle                                                    Fail
```
We can ignore OSX anf Linux failure, but I suggest we need to add some judgement, like:
**if (VCPKG_CMAKE_SYSTEM_NAME STREQUAL "linux" OR VCPKG_CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    message(FATAL_ERROR "This portfile not supports linux and osx")
endif()**

For arm64-windows, it failed with below error 
[install-arm64-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2939428/install-arm64-windows-dbg-out.log)
src\common/mathutil.h(156): error C3861: '__cpuid': identifier not found

I think this should be by-design since https://docs.microsoft.com/en-us/cpp/intrinsics/cpuid-cpuidex?view=vs-2017, only support X86 and X64. Right? Besides, I am interested arm-uwp pass, any idea? If arm64 is also not support.  I think we also need to add a judgement for this:
**if (VCPKG_TARGET_ARCHITECTURE STREQUAL "arm64")
    message(FATAL_ERROR "GLEW_BUILDING_LIBRARY OFF")
endif()**

Thanks again for all your working for this PR.

**Comment by johanlindfors** [comment]
I'm sorry for this @LarryIII. I though that my PR for ARM64 support for angle had been merged, but apparently not: https://github.com/Microsoft/angle/pull/144

Both ARM and ARM64 should be fine with some minor modifications, I will try and fix this by changing the patch for now. FYI we have used ms-angle for UWP and UWP-ARM for several years but have recently migrated to the official google angle release with some minor tweaks, I might check into that as well for vcpkg.

**Comment by johanlindfors** [comment]
Port is now updated and builds fine on my machine. Please try again!

**Comment by LarryIII** [comment]
@johanlindfors ARM64-windows failed with link errors, attached.
[install-arm64-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2944189/install-arm64-windows-dbg-out.log)

**Comment by johanlindfors** [comment]
Sorry for spamming you with requests @LarryIII, but please try again. There was a library missing. I have also begun looking into getting the Google Angle version able to build for UWP with vcpkg.

**Pull request merged**
