### PR TITLE
[openssl] Fix build for Android x86.

### LINKED ISSUE #24021: [openssl] build failure on Android x86
**Target Environment**
- OS: Android x86
- Compiler: clang

**Failure logs**
```
configure:17890: checking whether libcurl is usable
configure:17923: i686-linux-android16-clang -o conftest --sysroot=/home/runner/work/boinc/boinc/3rdParty/android/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DANDROID -DDECLARE_TIMEZONE -Wall -I/home/runner/work/boinc/boinc/3rdParty/buildCache/android/android-tc/x86/i686-linux-android/include -O3 -fomit-frame-pointer -fPIE -D__ANDROID_API__=16 -Wall  -I/home/runner/work/boinc/boinc/3rdParty/android/vcpkg/installed/x86-android/include -I/home/runner/work/boinc/boinc/3rdParty/android/vcpkg/installed/x86-android/lib/pkgconfig/../../include -L/home/runner/work/boinc/boinc/3rdParty/android/vcpkg/installed/x86-android/lib -llog -fPIE -pie -latomic -static-libstdc++ -L/home/runner/work/boinc/boinc/3rdParty/android/vcpkg/installed/x86-android/lib conftest.c  -L/home/runner/work/boinc/boinc/3rdParty/android/vcpkg/installed/x86-android/lib/pkgconfig/../../lib -lcurl -lssl -lcrypto -ldl -pthread -lz >&5
clang: warning: argument unused during compilation: '-static-libstdc++' [-Wunused-command-line-argument]
crypto/threads_pthread.c:219: error: undefined reference to '__atomic_is_lock_free'
crypto/threads_pthread.c:220: error: undefined reference to '__atomic_fetch_or_8'
crypto/threads_pthread.c:244: error: undefined reference to '__atomic_is_lock_free'
crypto/threads_pthread.c:245: error: undefined reference to '__atomic_load'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Additional context**
This is looks like and issue of clang for Android x86, and could be fixed on openssl upstream only.
Reference: https://github.com/openssl/openssl/issues/18059
As a workaround, if https://github.com/openssl/openssl/pull/18056 merged, it will be possible to disable usage of these functions by defining `BROKEN_CLANG_ATOMICS` somewhere in port's cmake file.

Keeping this just for reference if anyone else faces the same issue.

I will provide a fix if I find some workaround or a quicker solution than waiting for upstream fix.

### PR DESCRIPTION
**Pull request by AenBleidd**
OpenSSL3 uses atomics that are broken on clang for Android x86.
This commit fixes the build by disabling usage of these atomics on Android x86 only.

This fixes #24021.

Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

### CODE REVIEW

**Comment by AenBleidd** [comment]
This PR is tested using overlay ports here: https://github.com/BOINC/boinc/pull/4749

**Review by Adela0814 — APPROVED** [review]

**Review by BillyONeal — APPROVED** [review]

**Comment by talregev** [comment]
Please hold for this fix. I want to investigate another solution. 
@AenBleidd Can you put this PR on draft? Thank you.

**Review by talregev — CHANGES_REQUESTED** [review]
There is another solution for update the ndk version (the clang version) and it solve the bug.
@AenBleidd please put this PR on draft.

**Comment by AenBleidd** [comment]
@BillyONeal, sorry for 'not nice' words. Didn't know you have such a policy. Next time I'll try to be more polite.
@talregev, I remember I tried with NDK update, and failed, but of course you can try again. Previous build took 11 hours, so you have enough time to test your fix

**Comment by talregev** [comment]
> @BillyONeal, sorry for 'not nice' words. Didn't know you have such a policy. Next time I'll try to be more polite. @talregev, I remember I tried with NDK update, and failed, but of course you can try again. Previous build took 11 hours, so you have enough time to test your fix

Please review my PR:
https://github.com/BOINC/boinc/pull/4751

**Comment by talregev** [comment]
> @BillyONeal, sorry for 'not nice' words. Didn't know you have such a policy. Next time I'll try to be more polite. @talregev, I remember I tried with NDK update, and failed, but of course you can try again. Previous build took 11 hours, so you have enough time to test your fix

Because of your comment I understand the problem.

**Comment by BillyONeal** [comment]
> @BillyONeal, sorry for 'not nice' words.

No problem!

**Comment by talregev** [comment]
> @BillyONeal, sorry for 'not nice' words. Didn't know you have such a policy. Next time I'll try to be more polite. @talregev, I remember I tried with NDK update, and failed, but of course you can try again. Previous build took 11 hours, so you have enough time to test your fix

I fix 24021 issue in this PR https://github.com/BOINC/boinc/pull/4751 without this PR fix.

**Comment by AenBleidd** [comment]
@talregev, congratulations with the fix.
@BillyONeal, I'm closing this PR because looks like my previous assumption was not correct and tests were not correct either. I was just using an NDK with an incomplete implementation of atomics for x86.

**Pull request closed without merging**
