### PR TITLE
[drogon] Update to 1.8.0

### PR DESCRIPTION
**Pull request by an-tao**

### CODE REVIEW

**Review by JonLiu1993 — DISMISSED** [review]

**Comment by JonLiu1993** [comment]
@an-tao ,Thanks for your pr, when I tested the features by commnad `./vcpkg install drogon[*]:x86-windows` ,
I got this error:
````
F:\Feature-test\drogon\vcpkg\installed\x86-windows\include\hiredis\hiredis.h(42): error C2371: 'ssize_t': redefinition; different basic types
F:\Feature-test\drogon\vcpkg\installed\x86-windows\include\trantor/utils/MsgBuffer.h(25): note: see declaration of 'ssize_t'
F:\Feature-test\drogon\vcpkg\installed\x86-windows\include\hiredis\sds.h(39): error C2371: 'ssize_t': redefinition; different basic types
F:\Feature-test\drogon\vcpkg\installed\x86-windows\include\trantor/utils/MsgBuffer.h(25): note: see declaration of 'ssize_t'
[46/123] C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x86\cl.exe   /TP -DHAS_MYSQL_OPTIONSV -DUSE_BROTLI -DUSE_REDIS -Ddrogon_EXPORTS -IF:\Feature-test\drogon\vcpkg\buildtrees\drogon\src\v1.8.0-f24d158237.clean\lib\inc -IF:\Feature-test\drogon\vcpkg\buildtrees\drogon\src\v1.8.0-f24d158237.clean\orm_lib\inc -IF:\Feature-test\drogon\vcpkg\buildtrees\drogon\src\v1.8.0-f24d158237.clean\nosql_lib\redis\inc 
````

could you please take a look?

**Comment by an-tao** [comment]
> @an-tao ,Thanks for your pr, when I tested the features by commnad `./vcpkg install drogon[*]:x86-windows` , I got this error:
> 
> ```
> F:\Feature-test\drogon\vcpkg\installed\x86-windows\include\hiredis\hiredis.h(42): error C2371: 'ssize_t': redefinition; different basic types
> F:\Feature-test\drogon\vcpkg\installed\x86-windows\include\trantor/utils/MsgBuffer.h(25): note: see declaration of 'ssize_t'
> F:\Feature-test\drogon\vcpkg\installed\x86-windows\include\hiredis\sds.h(39): error C2371: 'ssize_t': redefinition; different basic types
> F:\Feature-test\drogon\vcpkg\installed\x86-windows\include\trantor/utils/MsgBuffer.h(25): note: see declaration of 'ssize_t'
> [46/123] C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x86\cl.exe   /TP -DHAS_MYSQL_OPTIONSV -DUSE_BROTLI -DUSE_REDIS -Ddrogon_EXPORTS -IF:\Feature-test\drogon\vcpkg\buildtrees\drogon\src\v1.8.0-f24d158237.clean\lib\inc -IF:\Feature-test\drogon\vcpkg\buildtrees\drogon\src\v1.8.0-f24d158237.clean\orm_lib\inc -IF:\Feature-test\drogon\vcpkg\buildtrees\drogon\src\v1.8.0-f24d158237.clean\nosql_lib\redis\inc 
> ```
> 
> could you please take a look?

https://github.com/microsoft/vcpkg/pull/17986?w=1#issuecomment-844645514
Last year I modified drogon's code to fit the hiredis library, but it has changed since then. I have to change again, can I use a specific version of hiredis lib in vcpkg ? I think this is a general requirement to reduce the impact of upstream library modifications on downstream software.

**Comment by an-tao** [comment]
@JonLiu1993 I made a patch to fix the redis problem, please check it out. thanks.

**Comment by JonLiu1993** [comment]
All features are tested successfully in the following triplet:
- x86-windows
- x64-windows
- x64-windows-static

**Comment by JonLiu1993** [comment]
@an-tao, We should not make drogon depend on a specific hiredis version unless hiredis is no longer updated

**Review by JonLiu1993 — APPROVED** [review]

**Pull request merged**
