### PR TITLE
[speexdsp] Only use SSE on x86/amd64

### PR DESCRIPTION
**Pull request by janisozaur**
This fixes UWP builds.

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for the PR!

This is actually always disabling SSE, because the variable `VCPKG_TARGET_ARCHITECTURE` isn't actually available inside the project's `CMakeLists.txt`. You should probably use `CMAKE_SYSTEM_PROCESSOR` instead: https://cmake.org/cmake/help/v3.9/variable/CMAKE_SYSTEM_PROCESSOR.html

**Comment by janisozaur** [comment]
Thanks, updated.

**Comment by janisozaur** [comment]
@ras0219-msft does it need any more changes?

**Comment by ras0219-msft** [comment]
Nope, this looks good. Thanks for the PR!

**Pull request merged**
