### PR TITLE
[vcpkg] Revise the file lists script

### PR DESCRIPTION
**Pull request by dg0yt**
- #### What does your PR fix?  
  - Modifies the output to print `:<triplet>` after each filename.
    This is relevant for cross builds. Before this change, DLL might be listed even for x64-windows-static due to the x64-windows host triplet. This problem includes vcpkg CI. Not to mention mingw on linux...
  - Modifies the output to not blur the location of headers.
    - `VCPKGHeadersDatabase.txt` now only list contents in the top-level `/include` subtree.
      This is the only path directly available with build system integration. Other subtrees are still in `VCPKGDatabase.txt`.
    - But the actual problem was that files in `include` dirs in other subtrees of a port were listed in `VCPKGDatabase.txt` as if they were in the top-level include dir. This is a source of confusion, example: 
      `lib/glib-2.0/include/glibconfig.h` appearing as `glib:/include/glibconfig.h` in `VCPKGDatabase.txt`, cf. https://github.com/microsoft/vcpkg/issues/20483#issuecomment-947503700 :boom: 

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all / not needed

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  not needed

- #### Example output

~~~
$ python3 scripts/file_script.py ./installed/vcpkg/info/

$ grep zlib: scripts/list_files/VCPKGDatabase.txt 
zlib:x64-mingw-dynamic:/bin/libzlib1.dll
zlib:x64-mingw-dynamic:/debug/bin/libzlibd1.dll
zlib:x64-mingw-dynamic:/debug/lib/libzlibd.dll.a
zlib:x64-mingw-dynamic:/debug/lib/pkgconfig/zlib.pc
zlib:x64-mingw-dynamic:/include/zconf.h
zlib:x64-mingw-dynamic:/include/zlib.h
zlib:x64-mingw-dynamic:/lib/libzlib.dll.a
zlib:x64-mingw-dynamic:/lib/pkgconfig/zlib.pc
zlib:x64-mingw-dynamic:/share/zlib/copyright
zlib:x64-mingw-dynamic:/share/zlib/usage
zlib:x64-mingw-dynamic:/share/zlib/vcpkg-cmake-wrapper.cmake
zlib:x64-mingw-dynamic:/share/zlib/vcpkg_abi_info.txt
zlib:x64-linux:/debug/lib/libz.a
zlib:x64-linux:/debug/lib/pkgconfig/zlib.pc
zlib:x64-linux:/include/zconf.h
zlib:x64-linux:/include/zlib.h
zlib:x64-linux:/lib/libz.a
zlib:x64-linux:/lib/pkgconfig/zlib.pc
zlib:x64-linux:/share/zlib/copyright
zlib:x64-linux:/share/zlib/usage
zlib:x64-linux:/share/zlib/vcpkg-cmake-wrapper.cmake
zlib:x64-linux:/share/zlib/vcpkg_abi_info.txt

$ grep zlib: scripts/list_files/VCPKGHeadersDatabase.txt 
zlib:x64-mingw-dynamic:zconf.h
zlib:x64-mingw-dynamic:zlib.h
zlib:x64-linux:zconf.h
zlib:x64-linux:zlib.h

### CODE REVIEW

**Comment by JackBoosY** [comment]
I hope my colleague will review this further.

**Comment by dg0yt** [comment]
Ping @BillyONeal

**Comment by BillyONeal** [comment]
@ras0219 @ras0219-msft @vicroms @dan-shaw Does this have impact on the website?

**Comment by BillyONeal** [comment]
Thanks for the updates!

**Comment by ras0219-msft** [comment]
We will likely need to change the website to account for this, but it's still a needed change.

**Comment by BillyONeal** [comment]
@ras0219-msft Daniel said there would be no effect in Teams chat.

**Pull request merged**
