### PR TITLE
[netcdf-cxx4] Export cmake targets

### LINKED ISSUE #8396: netcdf-cxx4 doesn't provide information on how to use it in cmake
**Describe the bug**
Installing the package gets you this output:
```
➜ ./vcpkg install netcdf-cxx4
The following packages are already installed:
    netcdf-cxx4[core]:x64-linux
Starting package 1/1: netcdf-cxx4:x64-linux
Package netcdf-cxx4:x64-linux is already installed
Elapsed time for package netcdf-cxx4:x64-linux: 7.493 us

Total elapsed time: 13.32 us
```
But there are no instructions on how to integrate it with your build.

```
find_library(NetCDFCxx4 netcdf-cxx4)
target_link_libraries(main PRIVATE ${NetCDFCxx4})
```
worked for me, but I'm not sure if that is the recommended way to do it or not.

**Environment**
- OS: Linux (arch linux)
- Compiler: clang 8.0.1 / g++ 9.1.0

**To Reproduce**
1. ./vcpkg install netcdf-cxx4
2. See above error.

**Expected behavior**
I feel all of the vcpkg libraries should print out the appropriate cmake commands for including them in your build.

### PR DESCRIPTION
**Pull request by NancyLi1013**
**Describe the pull request**

- What does your PR fix? Fixes #8396
 
Export CMake targets

Note: No feature needs to test.

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by BillyONeal** [comment]
Hmmm I'm on board with the cmake targets bits but not necessarily on board with the version change. Upstream seems like they want folks to use their explicitly versioned releases, and this is going to conflict with that. Is there a specific change this contains that we need from upstream that prevents us from using a released copy?

**Comment by NancyLi1013** [comment]
@BillyONeal 
Thanks for your review and attention. 

I'll close this PR now. We might consider to update this port until the next version is released.

Thanks again for your help.

**Comment by BillyONeal** [comment]
The other part of this fix though, the cmake targets bits, seem just fine; can we apply those to the current version?

**Comment by NancyLi1013** [comment]
Thanks for your suggestion @BillyONeal. I will try to make a patch to apply to the current version and confirm if it can work fine.

**Comment by NancyLi1013** [comment]
@BillyONeal 

Applying the patch makes `netcdf-cxx4` work fine on current version. I also test `find_package()` without any problems.

Here is the usage:

```
    find_package(netCDFCxx CONFIG REQUIRED)
    target_link_libraries(main PRIVATE netCDF::netcdf netCDF::netcdf-cxx4)
```

**Comment by BillyONeal** [comment]
@NancyLi1013 Thanks so much :D!

**Pull request merged**
