### PR TITLE
[vcpkg.cmake] add VCPKG_INSTALLED_DIR as a settable option

### PR DESCRIPTION
**Pull request by strega-nil**
This is something that #16061 tried to do, but screwed up; see #16293 . This one fixes that.

### CODE REVIEW

**Comment by Neumann-A** [comment]
You need to also fix the 68 matches for `_VCPKG_INSTALLED_DIR` in `/ports/*`. Otherwise you break the wrappers and so on.

**Comment by strega-nil** [comment]
@Neumann-A how about the new version, which includes back-compat considerations?

**Review by ras0219-msft — APPROVED** [review]

**Comment by ras0219-msft** [comment]
ping @strega-nil that this LGTM

**Comment by strega-nil-ms** [comment]
Thanks robert!

**Pull request merged**
