### PR TITLE
[CURL] fix an error on find_package(CURL CONFIG) for debug library

### LINKED ISSUE #3053: [CURL] error on find_package(CURL CONFIG)
When testing with simple project, it fails building with error on find_package(CURL CONFIG)

test project: https://github.com/miurahr/vcpkg_curl_testcase
test result: https://ci.appveyor.com/project/miurahr/vcpkg-curl-testcase

```
CMake Error at C:/Tools/vcpkg/installed/x86-windows/share/curl/libcurl-target.cmake:78 (message):
  The imported target "CURL::libcurl" references the file
     "C:/Tools/vcpkg/installed/x86-windows/debug/lib/libcurl-d_imp.lib"
  but this file does not exist.  Possible reasons include:
  * The file was deleted, renamed, or moved to another location.
  * An install or uninstall procedure did not complete successfully.
  * The installation package was faulty and contained
     "C:/Tools/vcpkg/installed/x86-windows/share/curl/libcurl-target.cmake"
  but not all the files it references.
Call Stack (most recent call first):
  C:/Tools/vcpkg/installed/x86-windows/share/curl/curl-config.cmake:15 (include)
  C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake:263 (_find_package)
  CMakeLists.txt:3 (find_package)
-- Configuring incomplete, errors occurred!
See also "C:/Tools/vcpkg/build/CMakeFiles/CMakeOutput.log".
Command exited with code 1
```

### PR DESCRIPTION
**Pull request by miurahr**
Fixed #3053

### CODE REVIEW

**Comment by past-due** [comment]
A quick note:
@miurahr's fix for this in CMake itself [was merged into CMake's master branch about 1 month ago](https://gitlab.kitware.com/cmake/cmake/commit/59b3e78451a1b19b95f7cb40fbd19454ace7f483).
It did **_not_** make it into CMake 3.12.x, but it looks like [it'll be in CMake 3.13.0](https://gitlab.kitware.com/cmake/cmake/milestones/26#tab-merge-requests).

**Comment by miurahr** [comment]
@past-due  Thanks for note.
https://github.com/Microsoft/vcpkg/pull/3220/commits/bcedb02a7c3d144205092a94689150abbceb9a11 is as same FindCURL.cmake as CMake 3.13.0, which is my fix. For interim solution, I'd like to propose to bundle it.

**Comment by Neumann-A** [comment]
this pr should be closed.
a) fixed in newer CMake and with #6386

**Comment by miurahr** [comment]
@Neumann-A thanks.

**Pull request closed without merging**
