### PR TITLE
[CGAL] switch dep to gmp instead of mpir

### LINKED ISSUE #15881: [cgal] build failure with latest version
**Host Environment**
- OS: macOS 11.1
- Compiler: Apple clang version 12.0.0 (clang-1200.0.32.28)

**To Reproduce**
`./vcpkg update`
`./vcpkg upgrade --no-dry-run`

**Failure logs** 
```
Starting package 66/69: gmp:x64-osx
Building package gmp[core]:x64-osx...
CMake Error at ports/gmp/portfile.cmake:2 (message):
  Can't build gmp if mpir is installed.  Please remove mpir, and try install
  gmp again if you need it.
Call Stack (most recent call first):
  scripts/ports.cmake:128 (include)


Error: Building package gmp:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: gmp:x64-osx
  Vcpkg version: 2021-01-13-unknownhash

Additionally, attach any relevant sections from the log files above.
```
**Additional context**
The upgrade reinstalls boost which reinstalls cgal, which fails due to the above. Explictly attempting to install CGAL yields:
```
adam@hapkido ~/vcpkg (master) $ ./vcpkg install cgal
Computing installation plan...
The following packages will be built and installed:
    cgal[core]:x64-osx -> 5.2
  * gmp[core]:x64-osx -> 6.2.1#3
  * mpfr[core]:x64-osx -> 4.1.0
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-osx...
Could not locate cached archive: /Users/adam/.cache/vcpkg/archives/0e/0e4b12f212b200f36191a8ccd16474ade56aceaa.zip
Could not locate cached archive: /Users/adam/.cache/vcpkg/archives/2e/2e21dd1d6bfb1cd9bf00bd6bd2895992a18ec243.zip
Could not locate cached archive: /Users/adam/.cache/vcpkg/archives/4e/4ee8b1f3a9c6fc5040f92e822a68c6fd1cefaa70.zip
Starting package 1/3: gmp:x64-osx
Building package gmp[core]:x64-osx...
CMake Error at ports/gmp/portfile.cmake:2 (message):
  Can't build gmp if mpir is installed.  Please remove mpir, and try install
  gmp again if you need it.
Call Stack (most recent call first):
  scripts/ports.cmake:128 (include)


Error: Building package gmp:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: gmp:x64-osx
  Vcpkg version: 2021-01-13-unknownhash

Additionally, attach any relevant sections from the log files above.
```

### PR DESCRIPTION
**Pull request by Neumann-A**
enable builds in CI again

closes #15881

### CODE REVIEW

**Comment by cenit** [comment]
just a question: why not using gmp on linux/osx and mpir on windows? 
They should be compatible and also give you the best result on respective platform. Or is it uniformity valued more?

**Comment by Neumann-A** [comment]
@cenit `gmp` is more actively maintained (last release end of 2020) while the `mpir` MSVC branch is not (last release end of 2017). As such using `gmp` everywhere seems to be the better alternative.

**Comment by Neumann-A** [comment]
The colmap regression in x64-windows-static seems to be due to optional dependencies (e.g. openjpeg) and also wrong linkage of FreeImage (release vs debug) and should also fail in the baseline if those dependencies are found.

**Comment by cenit** [comment]
This PR is very urgent for me to unblock a series of nightly pipelines which got broken otherwise. I hope it can be merged soon

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
@Neumann-A  I will check later.

**Comment by JackBoosY** [comment]
```

**Comment by JackBoosY** [comment]
```
-- Found FreeImage
--   Includes : D:/installed/x64-windows-static/include
--   Libraries : D:/installed/x64-windows-static/lib/FreeImage.lib
```

Only provides the release library.

**Comment by JackBoosY** [comment]
Will be fixed in #15886.

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
LGTM.

**Pull request merged**
