### PR TITLE
Update the repo for jom 1.1.3

### PR DESCRIPTION
**Pull request by zigguratvertigo**
The http://download.qt.io/ repo is unreliable. At the time of this message, it's been down for 6 days (https://www.isitdownrightnow.com/download.qt.io.html). It seems to be a recurring theme, from a simple google search.

Updating the link to grab from the Berkeley mirror instead.

### CODE REVIEW

**Review by PhoebeHui — APPROVED** [review]
Thanks for the PR!

**Comment by dan-shaw** [comment]
This change looks OK to me. However, I believe we can download from more than one URL, you can see some examples in `vcpkg_find_acquire_program.cmake`. Can you update the PR?

**Comment by zigguratvertigo** [comment]
Do you have a specific example in mind? 

At a quick glance all examples in `vcpkg_find_acquire_program.cmake` only provide a single URL, via SET(URL ...)

**Comment by dan-shaw** [comment]
`NASM` has two URLs.

**Review by PhoebeHui — APPROVED** [review]
LGTM, thanks for the PR!

**Comment by vicroms** [comment]
Thanks for the PR!

**Pull request merged**
