### PR TITLE
[ctbench] Add portfile

### PR DESCRIPTION
**Pull request by JPenuchot**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [ ] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by JPenuchot** [comment]
@microsoft-github-policy-service agree

**Comment by JPenuchot** [comment]
Two questions regarding my PR:

- I'm using range algorithms that aren't available on the CI used to build this package, is that blocking for merging this package? 
- I would like to remove LLVM from the dependencies and let users install it to avoid 1hour+ build times, is that reasonable?

**Comment by Cheney-W** [comment]
> * I'm using range algorithms that aren't available on the CI used to build this package, is that blocking for merging this package?

I think you could add below contents in https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt:
```
ctbench:x64-linux=fail
ctbench:x64-osx=fail
```
and add a warning in `portfile.cmake` to inform users that `compiling this library requires a compiler with C++20 support`.

**Comment by Cheney-W** [comment]
Converted your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded. Thank you!

**Comment by JPenuchot** [comment]
Hi, I did not add a usage file yet because ctbench is mostly meant to be used through its [CMake API](https://jpenuchot.github.io/ctbench-docs/md_generated-docs_2ctbench-api.html) to declare compile-time benchmark targets, not really as a library. Should I just leave it as is?

**Comment by JPenuchot** [comment]
And btw thanks for your instructions, they've been very clear so far :)

**Comment by Cheney-W** [comment]
We are fixing those ci issues.

**Review by Cheney-W — DISMISSED** [review]

**Comment by Cheney-W** [comment]
Our CI system is currently unable to test this port in its environment. However, I believe this does not hinder users from installing this port through vcpkg in the appropriate local environment. Therefore, I have added the `info:reviewed` label. 
And this PR requires further review from vcpkg team.

**Comment by vicroms** [comment]
We'll be able to test this port in the next VM update. Let's wait a little bit more before merging.

**Comment by BillyONeal** [comment]
depends:vm-update Ubuntu 22.04

**Comment by JPenuchot** [comment]
Should I remove `ctbench:x64-linux=fail` from the CI baseline file?

**Comment by vicroms** [comment]
Please do, so that this port can be tested in CI

**Comment by BillyONeal** [comment]
Thanks for the new port!

**Comment by JPenuchot** [comment]
Thanks for the merge :)

**Pull request merged**
