### PR TITLE
fix #1497

### LINKED ISSUE #1497: Unable to include opencv header with default build setting
With the latest port file (3.2.0-2, no problem with 3.2.0-1), I am unable to include opencv with the default build setting.

Here is a minimal code for test
``` cpp
#include <opencv/cv.hpp>

int main()
{
	cv::Mat im = cv::Mat::zeros(cv::Size(640, 480), CV_8UC3);
	cv::imshow("test", im);
}
```

and it leads to following error.
```
c:\tools\vcpkg\installed\x86-windows\include\opencv\cv.hpp(56): fatal error C1083: Cannot open include file: 'opencv2/features2d.hpp': No such file or directory
```

Where the submodule `features2d` depends on `flann` which is disabled explicitly.

### PR DESCRIPTION
**Pull request by cloudhan**

### CODE REVIEW

**Comment by KindDragon** [comment]
Add flann to https://github.com/cloudhan/vcpkg/blob/5d435bf6cbebe28f6879bcfa5a31edbc2d0163e6/ports/opencv/CONTROL than

**Comment by cloudhan** [comment]
@KindDragon flann is an internal dependency not external.

**Comment by cloudhan** [comment]
It is not a good idea to add flann as an external dep, this will add a lot unnecessary ad-hoc patches to correct include path and an build-in module, opencv devs might diverge from the upstream flann (they might have done this already).

FYI, the apt maintainers also use the builtin flann to build opencv and provide an separate flann package. Check this with `apt search flann`.

**Comment by ras0219-msft** [comment]
Keeping both appears to cause problems in apt (https://github.com/PointCloudLibrary/pcl/issues/483). If we must keep both, we will need to patch opencv's copy to ensure it does not conflict with the main flann library's symbols (even private ones, due to static linking) and headers.

**Comment by cloudhan** [comment]
All opencv library have `opencv_` prefix. The mentioned issue should be pcl's problem. And you don't have PCL in vcpkg ports ;) 

If you do not want to maintaining ad-hoc patches here and there, now and then, it would be better to use the builtin source.

**Comment by ras0219-msft** [comment]
Thanks @cloudhan. I built opencv with flann and confirmed that the produced DLL doesn't have any flann exports, which means it's suitable to be treated as a totally independent library from flann.

**Pull request merged**
