### PR TITLE
[nana] Revert 1 darkcacok patch nana

### PR DESCRIPTION
**Pull request by Darkcacok**
**Describe the pull request**

What does your PR fix? Fixes issue #
Build in Windows 10.

Which triplets are supported/not supported? Have you updated the CI baseline?
Supported x64-windows, in x64-linux I don't know how to fix issue with fontconfig yet.
vcpkg/installed/x64-linux/lib/libfontconfig.a(fcfreetype.c.o): undefined reference to symbol 'FT_Get_Postscript_Name'

Does your PR follow the maintainer guide?

### CODE REVIEW

**Comment by LilyWangL** [comment]
What does this PR fix?

**Comment by Darkcacok** [comment]
> What does this PR fix?

If we have several subfolders, then the project cannot be build because cmake ignores "if (ON)".

**Comment by Darkcacok** [comment]
I am not good at cmake. Perhaps this can be done more elegantly.

**Comment by cenit** [comment]
> I am not good at cmake. Perhaps this can be done more elegantly.

The problem is that your PR is empty as of now. Maybe one of the commit was unwanted?

**Comment by Darkcacok** [comment]
> > I am not good at cmake. Perhaps this can be done more elegantly.
> 
> The problem is that your PR is empty as of now. Maybe one of the commit was unwanted?

I'm sorry. I did not notice that I canceled the changes.

**Comment by LilyWangL** [comment]
Thanks for your PR! Can you please correct the Version field in the CONTROL file? You can get more information from [maintainer-guide.md](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md).

**Comment by Darkcacok** [comment]
done

**Comment by strega-nil** [comment]
Alright, LGTM! Thanks @Darkcacok :)

**Pull request merged**
