### PR TITLE
[azure-iot] vcpkg update for master/public-preview release 2019-04-11

### PR DESCRIPTION
**Pull request by ewertons**
[azure-iot] vcpkg update for master/public-preview release 2019-04-11

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for the PR!

Could you also update the CONTROL file version strings to match the new version?

**Comment by ewertons** [comment]
Thank you @ras0219-msft 
I made the changes request, please let me know if it they are good.

**Comment by NancyLi1013** [comment]
Hi @ewertons, here are some regressions from the current CI system and it seems that azure-c-shared-utility failed on all triplets and other ports built successfully.

|x64-windows           |master| test |notes
|----------------------|------|------|-----
|azure-c-shared-utility|Pass  |Fail  |**Regression**

|x64-windows-static    |master| test |notes
|----------------------|------|------|-----
|azure-c-shared-utility|Pass  |Fail  |**Regression**

|x64-osx               |master| test |notes
|----------------------|------|------|-----
|azure-c-shared-utility|Pass  |Fail  |**Regression**

|arm64-windows         |master| test |notes
|----------------------|------|------|-----
|azure-c-shared-utility|Pass  |Fail  |**Regression**

|x86-windows           |master| test |notes
|----------------------|------|------|-----
|azure-c-shared-utility|Pass  |Fail  |**Regression**

|x64-linux             |master| test |notes
|----------------------|------|------|-----
|azure-c-shared-utility|Pass  |Fail  |**Regression**

[failureLogs.zip](https://github.com/Microsoft/vcpkg/files/3130113/failureLogs.zip)

**Comment by ewertons** [comment]
Thanks @ras0219-msft ,
we apologize for the breaks. Let me recall this PR, and submit again after some fixes and more testing.

**Pull request closed without merging**
