### PR TITLE
[OpenEXR] Update to v2.3.0

### PR DESCRIPTION
**Pull request by cenit**
Upgrade the whole package:

- [x] move to github
- [x] update to v2.3.0
- [x] improve the FindOpenEXR.cmake, maintaining backwards compatibility (there's an official one distributed with the package but it is completely different, for now it is avoided)
- [x] remove the `ilmbase` port because now it is part of `OpenEXR`
- [x] enable installation of OpenEXR tools

### CODE REVIEW

**Comment by UnaNancyOwen** [comment]
> [x] remove the ilmbase port because now it is part of OpenEXR

I agree. I think it is a good proposal than my pull request #4820. 👍 
@ras0219-msft What do you think?

**Comment by cenit** [comment]
I just updated `freeimage` to comply with the new OpenEXR.
I noticed that also updates to `alembic` and to `OpenVDB` are necessary, due to this upgrade...

**Comment by cenit** [comment]
this PR is necessary to build #5169 with all features

**Comment by vicroms** [comment]
@cenit 
Shouldn't OpenEXR be disabled for UWP? The now removed port for `ilmbase` didn't support UWP, and now that it is embedded into OpenEXR doesn't the same restriction apply?

**Comment by cenit** [comment]
if you see any failure yes sure. Maybe I didn't check all the ports with all the triplets, CI would be great to be exposed ;)
Shall I remove UWP build from OpenEXR itself alone or also in all dependent ports? (I never really appreciated the fact that sometimes it happens to build all the dependencies just to tell you "ok no way to build this port with this triplet"...)

**Comment by vicroms** [comment]
Great. I made [a few changes](https://github.com/Microsoft/vcpkg/compare/dev/viromer/5228) so that OpenEXR can be built on Linux and MacOS, for now those changes are only on my branch.

I also pulled your changes to `openvdb` (PR #5265) as the removal of `ilmbase` would cause regressions otherwise, the CI build takes a while to finish, but hopefully this time it is successful.

**Comment by cenit** [comment]
closed in favor of #5417

**Pull request closed without merging**
