### PR TITLE
[vcpkg] Update CMake to 3.25.1

### PR DESCRIPTION
**Pull request by mrowrpurr**
The recent PR #28012 broke my application builds due to https://gitlab.kitware.com/cmake/cmake/-/issues/24209

> https://gitlab.kitware.com/cmake/cmake/-/issues/24209  
> PCH compilations fails on VC++/Ninja if CMAKE_EXPERIMENTAL_CXX_MODULE_DYNDEP=1

^ The issue shows how easy it is to reproduce this issue on CMake 3.25.0 using `target_precompile_headers`

---

> _Uncertain of the process for bumping CMake, simply based this PR on #28012 from a few days ago._
>
> _**Feel free to close if there's an internal process for doing this and y'all will do it. But please get to 3.25.1 soon!**_

### CODE REVIEW

**Comment by mrowrpurr** [comment]
@microsoft-github-policy-service agree

**Review by JonLiu1993 — DISMISSED** [review]

**Comment by mrowrpurr** [comment]
@JonLiu1993 The `x86` build has been running and stuck for over a day 😅 Can it be restarted?

**Comment by Neumann-A** [comment]
@mrowrpurr Just sync the branch with master via github. It will automatically restart then

**Comment by mrowrpurr** [comment]
@JonLiu1993 ping to un-stuck-ify. Triggered fresh build with a pull from `master` but, as a first time contributor, looks like it needs another manual approval to run the builds

**Comment by JonLiu1993** [comment]
> @JonLiu1993 ping to un-stuck-ify. Triggered fresh build with a pull from `master` but, as a first time contributor, looks like it needs another manual approval to run the builds

@mrowrpurr, Thanks for your pr, I always keep an eye on this PR.

**Comment by JonLiu1993** [comment]
The ci error will be fixed by https://github.com/microsoft/vcpkg/pull/28089

**Comment by dg0yt** [comment]
> The ci error will be fixed by #28089

No, the actual fix is #28160.

**Comment by dg0yt** [comment]
Given that the CMake update nearly rebuilds the world, can we integrate another change with the next push?

> Please update
> 
> https://github.com/microsoft/vcpkg/blob/30a20e8f15ff26eec665205dea52f4ffc6f0814b/scripts/ports.cmake#L87

This should be bumped to `2022-10-12` to generally enable the use of `${VERSION}` in portfiles.
Cf. https://github.com/microsoft/vcpkg/pull/28240#discussion_r1043313224, cc @Neumann-A

**Comment by mrowrpurr** [comment]
@dg0yt Bumped

https://github.com/microsoft/vcpkg/pull/28126/commits/fda3307afa4d2e49cf359b6f86c3865b8622e357

```diff
- vcpkg_minimum_required(VERSION 2021-11-02)
+ vcpkg_minimum_required(VERSION 2022-10-12)
```

**Comment by mrowrpurr** [comment]
@dg0yt My bad if I should've waited for #28160 before "_rebuilding the world_" 🌍

**Comment by Neumann-A** [comment]
Consider syncing with master again. Maybe the CI run gets lucky and skips the problem ;)

**Comment by dg0yt** [comment]
CI won't get happy if the baseline fixes are not merged.
IMO this PR could be merged despite the well-known baseline regressions.

**Comment by Neumann-A** [comment]
> CI won't get happy if the baseline fixes are not merged.

That is only true for full rebuilds not partial rebuilds ;)

> IMO this PR could be merged despite the well-known baseline regressions.

Yeah I agree with that.

**Comment by Neumann-A** [comment]
> A CMake update is not so much different from a full rebuild.

A CMake update is always a full rebuild in the first run. After that it should just be partial rebuilds.

**Comment by mrowrpurr** [comment]
@JonLiu1993 I can sync to HEAD anytime again as needed (_although I think you can do it too_)

Any way to get movement here?

This is breaking my projects for everyone who doesn't manually install CMake 3.25.1 into their PATH because of the 3.25.0 PCH bug. Could we please find a way to merge this?

**Comment by JonLiu1993** [comment]
> @JonLiu1993 I can sync to HEAD anytime again as needed (_although I think you can do it too_)
> 
> Any way to get movement here?
> 
> This is breaking my projects for everyone who doesn't manually install CMake 3.25.1 into their PATH because of the 3.25.0 PCH bug. Could we please find a way to merge this?

The strange thing is that I can't reproduce the error on ci locally. I'm thinking whether we can temporarily fail the triplet that reported the error in ci in cibaseline to bypass these errors. But this operation may obviously be dangerous or incorrect, I need to discuss it with my colleagues.

**Comment by dg0yt** [comment]
Port protobuf installs `libprotobuf.lib`, but libphonenumer looks for `protobuf`, https://github.com/microsoft/vcpkg/pull/28522#issuecomment-1365712964.

`libphonenumber` builds with CMake 3.25.0 due to a temporary behaviour which was reverted in CMake 3.25.1: 
Trying the `lib` name prefix when searching for libs on Windows,
https://github.com/Kitware/CMake/commit/4c2952c5cb95e06e3f9c096d71bc342bfa2d4443

Possible fix: patch  https://github.com/google/libphonenumber/blob/9741ae82fdf85e12d40e9d1f78632378c4e0f885/cpp/CMakeLists.txt#L59 
~~~diff
+  set(CMAKE_FIND_LIBRARY_PREFIXES "" "lib")
  find_library (${NAME}_LIB NAMES ${LIBRARY})
~~~

**Comment by dg0yt** [comment]
> ```diff
> +  set(CMAKE_FIND_LIBRARY_PREFIXES "" "lib")
>   find_library (${NAME}_LIB NAMES ${LIBRARY})
> ```
To not interfere, with default order, guard with `if(MSVC)` or use 
`set(CMAKE_FIND_LIBRARY_PREFIXES "${CMAKE_FIND_LIBRARY_PREFIXES};lib")`

**Comment by mrowrpurr** [comment]
@dg0yt @JonLiu1993 

Could I get some guidance? I see `requires: author-response` added.

Is that a response of the libphonenumber port author or from myself?

@dg0yt's patch helps `google/libphonenumber` which had a PR merged a couple days ago:
https://github.com/google/libphonenumber/pull/2818 "_CPP: Fix cmake build failure + export libphonenumber-config.cmake_"

I don't think y'all need me for anything, in which case, "_as you were_." Just poking.

**Comment by dg0yt** [comment]
I don't think you need to continue this PR: There is #28522.
Unfortunately, new regressions are merged faster than fixes.

**Comment by mrowrpurr** [comment]
#28522 was merged (_which was a duplicate of this one_)

**Pull request closed without merging**
