### PR TITLE
[libsquish] Add new port

### PR DESCRIPTION
**Pull request by frabert**

### CODE REVIEW

**Comment by grdowns** [comment]
Thanks for the port contribution, @frabert! This looks good, however we do not use `WINDOWS_EXPORT_ALL_SYMBOLS` as per [this discussion](https://github.com/Microsoft/vcpkg/pull/5784#issuecomment-476908733). We don't have any documentation around our stance on it yet, but I did create an issue regarding it (#6043). To amend this in the PR, could you please remove the references to `WINDOWS_EXPORT_ALL_SYMBOLS` and disable dynamic builds via the portfile?

**Comment by frabert** [comment]
I'm going to try and see if I can have a patch accepted in upstream in a reasonable timeframe, otherwise I will disable the shared linking as requested

**Comment by frabert** [comment]
@grdowns I'm going to try and see if I can make this pass :)

Would this solution be acceptable? The end users would not feel any difference, the generated header is "transparent" and does not need to be used.

**Comment by grdowns** [comment]
Hey @frabert! Thanks for waiting for me to get the chance to review these changes. Looks good!

**Pull request merged**
