### PR TITLE
[g3log] Add new port

### PR DESCRIPTION
**Pull request by myd7349**
Test project: https://github.com/myd7349/Ongoing-Study/tree/master/cpp/CMake/vcpkg/g3log_example

Test on:
- x86-windows
- x86-windows-static
- x64-windows
- x64-windows-static
- x64-linux
- x64-osx

Known issues:
- Failed to install on UWP: [build-x86-uwp-dbg-out.log](https://github.com/Microsoft/vcpkg/files/3047212/build-x86-uwp-dbg-out.log) (even I specify `-DENABLE_VECTORED_EXCEPTIONHANDLING=OFF`)
- `target_link_libraries(${example_name} PRIVATE g3logger)` doesn't work for me

### CODE REVIEW

**Comment by NancyLi1013** [comment]
Hi @myd7349, thanks for your contribution to vcpkg. Here are the test results from the current CI system:

|x64-windows|master| test |notes
|-----------|------|------|-----
|g3log      |      |Pass  |New Port

|x64-windows-static|master| test |notes
|------------------|------|------|-----
|g3log             |      |Pass  |New Port

|x64-osx|master| test |notes
|-------|------|------|-----
|g3log  |      |Pass  |New Port

|arm64-windows|master| test |notes
|-------------|------|------|-----
|g3log        |      |Fail  |New Port

|x86-windows|master| test |notes
|-----------|------|------|-----
|g3log      |      |Pass  |New Port

|x64-linux|master| test |notes
|---------|------|------|-----
|g3log    |      |Pass  |New Port

|x64-uwp|master| test |notes
|-------|------|------|-----
|g3log  |      |Fail  |New Port

|arm-uwp|master| test |notes
|-------|------|------|-----
|g3log  |      |Fail  |New Port

**Comment by NancyLi1013** [comment]
The port failed on arm and uwp. Are those expected?

**Comment by myd7349** [comment]
Hi! @NancyLi1013 Yeah! These failures are as expected.
The reason I marked this port as `WIP` is that I have created a PR in the upstream repo to fix some issues.

**Comment by myd7349** [comment]
Hi! @NancyLi1013 I have created a PR for it. And I have created a PR in the upstream and I am just waiting on it.

**Comment by myd7349** [comment]
OK. The `WIP` tag is removed.

**Pull request merged**
