### PR TITLE
[vcpkg_find_acquire_program(NINJA).cmake] Update to 1.12.0

### LINKED ISSUE #38494: [vcpkg-tool-<ninja>] update to <1.12.0>
### Build tool name

ninja

### New version number

1.12.0

### Other information that may be useful (release notes, etc...)

Operation System: Windows 10

1、The Vcpkg build tool **Ninja** currently version is _1.10.2_. But the official latest version of **Ninja** is _1.12.0_ . Please update it to the latest version _1.12.0_ ;

2、The Vcpkg always download **Ninja** binaries to the `%VCPKG_ROOT%/downloads/tools/ninja/<ninja-version>/` directory. 
How to make Vcpkg prioritize the use of Ninja binaries already downloaded&installed on the computer by myself. (And I have added **Ninja.exe** to the system environment variable:  `PATH`)

Homepage: https://ninja-build.org/
Repository:  https://github.com/ninja-build/ninja

### PR DESCRIPTION
**Pull request by bowenxuuu**
Fixes #38494

### CODE REVIEW

**Comment by dg0yt** [comment]
IMO it would be good to chose the arm variant on arm64 hosts now. 1.12.0 has arm64 binaries for linux and windows.

Possible patterns (windows, linux):
https://github.com/microsoft/vcpkg/blob/815d93b520779e4354bb4b954fc2179b3e520c26/scripts/cmake/vcpkg_configure_meson.cmake#L124-L137
https://github.com/microsoft/vcpkg/blob/815d93b520779e4354bb4b954fc2179b3e520c26/scripts/cmake/vcpkg_configure_meson.cmake#L147-L160

**Comment by xb284524239** [comment]
> @xb284524239 please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by xb284524239** [comment]
> IMO it would be good to chose the arm variant on arm64 hosts now. 1.12.0 has arm64 binaries for linux and windows.
> 
> Possible patterns (windows, linux):
> 
> https://github.com/microsoft/vcpkg/blob/815d93b520779e4354bb4b954fc2179b3e520c26/scripts/cmake/vcpkg_configure_meson.cmake#L124-L137
> 
> 
> https://github.com/microsoft/vcpkg/blob/815d93b520779e4354bb4b954fc2179b3e520c26/scripts/cmake/vcpkg_configure_meson.cmake#L147-L160

Hey bro, I have added arm64 binaries for linux and windows.

**Comment by JonLiu1993** [comment]
@xb284524239, Thanks for your PR, this is test error log, please take a look.
[package-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/15399042/package-x86-windows-dbg-out.log)

**Comment by JonLiu1993** [comment]
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

**Comment by xb284524239** [comment]
> @xb284524239, Thanks for your PR, this is test error log, please take a look. [package-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/15399042/package-x86-windows-dbg-out.log)

@JonLiu1993 The log file above is empty.

**Comment by JonLiu1993** [comment]
@xb284524239, Sorry for my negligence, I have uploaded the latest log:
[package-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/15399985/package-x86-windows-dbg-out.log)

**Comment by BillyONeal** [comment]
I'm sorry there was some confusion here. I'll make sure you're credited as a co-author when https://github.com/microsoft/vcpkg/pull/39260 merges. Thanks for the submission!

**Comment by xb284524239** [comment]
> I'm sorry there was some confusion here. I'll make sure you're credited as a co-author when #39260 merges. Thanks for the submission!

@BillyONeal Thanks and I wish you will success.

**Pull request closed without merging**
