### PR TITLE
Add -allowAppleClang option to bootstrap.sh. (fixes #4698)

### LINKED ISSUE #4698: no way to set VCPKG_ALLOW_APPLE_CLANG
When building on Mac with xcode installed, I am given the following message:

```
Building the vcpkg tool requires support for the C++ Filesystem TS.
Apple clang versions 9 and below do not have support for it.
Please install gcc6 or newer from homebrew (brew install gcc6).
If you would like to try anyway, set VCPKG_ALLOW_APPLE_CLANG.
```

However, setting this environmental variable does nothing and results in the same error.

It looks like this line in the CMakeLists should be reading from the environment `$ENV(VCPKG_ALLOW_APPLE_CLANG).`

https://github.com/Microsoft/vcpkg/blob/a6986fdbea87c5af4ab9c1eb4d8c3d52563aee65/toolsrc/CMakeLists.txt#L9

### PR DESCRIPTION
**Pull request by soroshsabz**
ITNOA

Add -allowAppleClang option to bootstrap.sh to create an easy way for switch VCPKG_ALLOW_APPLE_CLANG.

This PR resolved #4698

### CODE REVIEW

**Comment by soroshsabz** [comment]
related to #4475 #4476

**Comment by soroshsabz** [comment]
@Rastaban can you have little time to check this PR?

thanks very much

**Comment by soroshsabz** [comment]
@ras0219-msft Thanks for editing, but the if statement is needed, because as you can see in toolsrc/CMakeLists.txt I want to use ENV variable if does not any option from user provided. so if statement is needed.

thanks

**Comment by soroshsabz** [comment]
@ras0219-msft did you agree with me?

**Comment by ras0219-msft** [comment]
Hi @soroshsabz, sorry for the long delay and missing the environment variable the first time!

At this time, I don't see a purpose for adding an environment variable here. Once AppleClang officially supports the Filesystem TS, we'll be removing this section entirely and always using AppleClang by default.

If you have some compelling use case for an environment variable, I'd be happy to discuss it here and then potentially open a new PR!

**Comment by soroshsabz** [comment]
@ras0219-msft Thanks for merge it, but I think environment variable is good approach still, for large scale company and reducing IT staff cost.

So I welcome to add all important condition and configuration in environment variables :)

**Comment by harrysummer** [comment]
Sorry for the interrupt. I was trying to find a cross-platform solution for my project. And when I tried to run vcpkg on Azure Pipeline with hosted Mac OS 10.14, I was shocked that Clang is not supported! (It's not vcpkg team's fault though). And I found the added argument of this PR quite confusing to me.

IMHO, I agree with @ras0219-msft that the variable `VCPKG_ALLOW_APPLE_CLANG` is not needed. I could understand why @soroshsabz has the argument of the reducing cost stuff. But it's a false claim of this variable -- If user is running Xcode version < 11, then allowing Clang has no use because C++17 filesystem is not supported and vcpkg cannot be compiled. Otherwise, if running the upcoming Xcode 11 (the [beta version](https://developer.apple.com/documentation/xcode_release_notes/xcode_11_beta_2_release_notes) already includes filesystem), then Clang can natively build vcpkg. So we can see the whole process is only determined by the version of Clang and it's no benefit, even confusing, in introducing a redundant variable.

My suggestion in the Clang support logic would be, adding a condition to test the version of Clang, and throwing an error when using the version lower than the one in Xcode 11 beta. It is not good enough to remove the whole section because we should still consider back-compatibility.

**Pull request merged**
