### PR TITLE
[openssl] Two build fixes

### PR DESCRIPTION
**Pull request by yirkha**
Hi,

I had to do these two changes in order to make OpenSSL build on my machine cleanly.

Thanks for your consideration.

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Hi yirkha, thanks for the PR!

This changes the OpenSSL build to be in-source instead of out-of-source, which can cause an enormous amount of issues when building for multiple targets.

Could you provide more details about what particular problems you were hitting that this solves? What error messages were you getting when it did not build cleanly?

**Comment by yirkha** [comment]
Hi Robert, thanks for the quick reply and my apologies for not providing more explanation right away.

I am using VS 2017, x86-windows target and the latest vcpkg from master (cabf99d).

----

When I do `vcpkg install openssl`, it fails with this output (long paths redacted for clarity):

```
...
-- Configuring x86-windows-rel
-- Configuring x86-windows-rel done
-- Configuring x86-windows-dbg
-- Configuring x86-windows-dbg done
-- Build x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
    Command failed: C:/.../cmake/bin/cmake.exe;--build;.
    Working Directory: C:/.../vcpkg/buildtrees/openssl/x86-windows-rel
    See logs for more information:
      ...\vcpkg\buildtrees\openssl\build-x86-windows-rel-out.log
      ...\vcpkg\buildtrees\openssl\build-x86-windows-rel-err.log

Call Stack (most recent call first):
  ports/openssl/portfile.cmake:43 (vcpkg_execute_required_process)
  scripts/ports.cmake:73 (include)

Error: Building package openssl:x86-windows failed with: BUILD_FAILED
```

----

Looking at the build tree under `%VCPKG_ROOT%\buildtrees\openssl`, `src` contains just `CMakeLists.txt` and some patch files, but the whole OpenSSL source code is extracted twice under `x86-windows-dbg` and `x86-windows-rel`.

This is in contrast to what other vcpkg ports seem to be doing, yes, I noticed that too. But I thought somebody had a reason to make it so.

I did not change this behavior nor deemed necessary to do so (to make it _out-of-source_ or whatever).

----

`%VCPKG_ROOT%\buildtrees\openssl\config-x86-windows-rel-out.log` contains this:

```
-- Extracting source C:/.../vcpkg/downloads/openssl-1.0.2k.tar.gz
-- Applying patch C:/.../vcpkg/buildtrees/openssl/src/openssl-1.0.2k/PerlScriptSpaceInPathFixes.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/.../vcpkg/buildtrees/openssl/src/openssl-1.0.2k/PerlScriptSpaceInPathFixes.patch done
-- Applying patch C:/.../vcpkg/buildtrees/openssl/src/openssl-1.0.2k/ConfigureIncludeQuotesFix.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/.../vcpkg/buildtrees/openssl/src/openssl-1.0.2k/ConfigureIncludeQuotesFix.patch done
-- Applying patch C:/.../vcpkg/buildtrees/openssl/src/openssl-1.0.2k/STRINGIFYPatch.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/.../vcpkg/buildtrees/openssl/src/openssl-1.0.2k/STRINGIFYPatch.patch done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/.../vcpkg/buildtrees/openssl/x86-windows-rel
```

So configuring has succeeded, but there were some patching issues.

The underlying errors look like this - an example from `patch-x86-windows-0-err.log`:

```
Checking patch util/copy.pl...
error: util/copy.pl: No such file or directory
Checking patch util/mk1mf.pl...
error: util/mk1mf.pl: No such file or directory
```

Investigating further, I found the patches are being applied in `%VCPKG_ROOT%\buildtrees\openssl\src\openssl-1.0.2k`, but the source code is actually under `%VCPKG_ROOT%\buildtrees\openssl\x86-windows-rel` (or `x86-windows-dbg`).

It turned out the patching is done through `vcpkg_apply_patches()` with
        `... SOURCE_PATH ${SOURCE_PATH} ...`
which is defined earlier as
        `set(SOURCE_PATH ${CMAKE_CURRENT_BINARY_DIR}/openssl-${OPENSSL_VERSION})`
but all other commands are using
        `... WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/openssl-${VERSION} ...`
and the parent `portfile.cmake` is setting just the latter, `-DVERSION=...`.  

That's what my first commit is about - ad30f9d  
It makes the patches to be actually applied.  
I tried to explain this in the commit message, although I understand now that the diff might be confusing. Suggestions welcome.

----

But running `vcpkg install openssl` again still failed for me, with the same command line output.  

This time `build-x86-windows-rel-err.log` had the reason:

```
NMAKE : fatal error U1052: file 'ms\ntdll.mak' not found
Stop.
```

`ms\ntdll.mak` is not present in OpenSSL source code at all!  

Some more investigation reveals it's supposed to be generated by running `openssl-1.0.2k\ms\do_ms.bat`, which begins like this:  

```
perl util\mkfiles.pl >MINFO
perl util\mk1mf.pl no-asm VC-WIN32 >ms\nt.mak
perl util\mk1mf.pl dll no-asm VC-WIN32 >ms\ntdll.mak
...
```

But my output in `configure-do-x86-windows-Release-out.log` is just this one line:

```
C:\...\vcpkg\buildtrees\openssl\x86-windows-rel\openssl-1.0.2k>perl util\mkfiles.pl  1>MINFO
```

So only the first perl command is actually executed.

The reason for this is that I happen to have an existing Perl installation elsewhere and `perl.bat` in my `%PATH%` pointing to it. The interpreter itself is working fine and I reckon it would be good enough for OpenSSL to build, but because it is a batch file, invoking it from another batch file without using the `call` command stops the rest of the parent script from executing and therefore the build is not correctly set up.  

That's what my second commit tries to improve - 109a8b9

----

With both of these changes applied, I am able to build openssl through vcpkg without any problems.

**Comment by ras0219-msft** [comment]
Thank you very much for the detailed reply! I made a mistake in my initial assessment -- you're totally right that this preserves the current separate-source builds (an unfortunate requirement of openssl 😦).

W.r.t. the perl ordering: we had a previous unfortunate bug where users who had chosen the "add all unix utilities to my path" option when installing Git for Windows would have a copy of `perl.exe` in their path. Unfortunately, this perl shared a directory with other fun utilities like `link.exe`, so adding it to the path first broke lots of builds.

However, I believe both your problem and the problem above have been solved with 6860b461a1 and Vcpkg release 76; we have transitioned to a whitelisted environment for builds which does _not_ inherit the user's path. This has the downside that we will always download perl, but the upside that we will always use the perl that works 😄.

Thank you for the fixes!

**Comment by yirkha** [comment]
OK, thanks - for the merge and for maintaining this useful project.
A separate, fully controlled build environment will be even better in the long term (y)

**Pull request merged**
