### PR TITLE
[ffmpeg] add if guard, fix library ordering on linux, minor clean up

### PR DESCRIPTION
**Pull request by mcmtroffaes**
- What does your PR fix? Currently, repeated calls to find_package(FFMPEG) across a single cmake project results in the FFmpeg libraries being included more than once (see for instance the cmake log here: https://travis-ci.org/github/mcmtroffaes/ffmpeg-msvc-build/jobs/740501464#L361). This patch adds a guard to fix that problem. It also fixes the link ordering of the x64-linux static builds, because gcc expects dependencies to be specified last (see for instance build failure here: https://travis-ci.org/github/mcmtroffaes/ffmpeg-msvc-build/jobs/740832347#L430 - unresolved symbols even though the library is specified on the command line, but the symbol is not resolved due to wrong library ordering). Finally, there's some minor clean ups too (cmake includes, version field). Tested on x64-linux and x64-windows-static-md triplets.

- Which triplets are supported/not supported? Have you updated the CI baseline? No changes.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)? To the best of my knowledge, yes.

### CODE REVIEW

**Comment by mcmtroffaes** [comment]
Just rebased onto latest master to correct port version bump.

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
Thanks again for your efforts. @mcmtroffaes

**Comment by mcmtroffaes** [comment]
You're welcome. Thank you for the quick review!

**Comment by BillyONeal** [comment]
Encode all the things! Thanks!

**Pull request merged**
