### PR TITLE
[minio-cpp] chore(version): updated to v0.1.1

### PR DESCRIPTION
**Pull request by harshavardhana**
**Describe the pull request**

- #### What does your PR fix?
Updating minio-cpp version

- #### Which triplets are supported/not supported? Have you updated the [CI baseline]
osx

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?

Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by harshavardhana** [comment]
I am having a hard time finding the relevant logs for the failure https://dev.azure.com/vcpkg/public/_build/results?buildId=76332&view=artifacts&pathAsName=false&type=publishedArtifacts - I am not able to click or download any of the artifacts uploaded here.

**Comment by JonLiu1993** [comment]
> I am having a hard time finding the relevant logs for the failure https://dev.azure.com/vcpkg/public/_build/results?buildId=76332&view=artifacts&pathAsName=false&type=publishedArtifacts - I am not able to click or download any of the artifacts uploaded here.

@harshavardhana, this is the error log, plesase take a look:
[config-x64-osx-out.log](https://github.com/microsoft/vcpkg/files/9297503/config-x64-osx-out.log)
[config-x64-osx-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/9297504/config-x64-osx-CMakeCache.txt.log)

**Comment by harshavardhana** [comment]
```
CMake Error at include/CMakeLists.txt:28 (configure_file):
  No such file or directory


-- Configuring incomplete, errors occurred!
See also "/Users/vagrant/Data/buildtrees/minio-cpp/x64-osx-dbg/CMakeFiles/CMakeOutput.log".
See also "/Users/vagrant/Data/buildtrees/minio-cpp/x64-osx-dbg/CMakeFiles/CMakeError.log".
```

strange! not sure what is missing. Let me go figure.

**Comment by harshavardhana** [comment]
So I tested this on OSX looks like something is wrong with the build system on Azure pipelines here

```
Stored binary cache: "/Users/minio/.cache/vcpkg/archives/e7/e77dde94d59e5713549188c8518f9375735b814ddb09d77d51343fd701de0157.zip"
Elapsed time to handle openssl:x64-osx: 1.966 min
Installing 9/10 pugixml:x64-osx...
Building pugixml[core]:x64-osx...
-- Downloading https://github.com/zeux/pugixml/archive/v1.12.1.tar.gz -> zeux-pugixml-v1.12.1.tar.gz...
-- Extracting source /Users/minio/vcpkg/downloads/zeux-pugixml-v1.12.1.tar.gz
-- Applying patch dllexport.patch
-- Using source at /Users/minio/vcpkg/buildtrees/pugixml/src/v1.12.1-65f02a4d38.clean
-- Found external ninja('1.11.0').
-- Configuring x64-osx
-- Building x64-osx-dbg
-- Building x64-osx-rel
-- Fixing pkgconfig file: /Users/minio/vcpkg/packages/pugixml_x64-osx/lib/pkgconfig/pugixml.pc
-- Fixing pkgconfig file: /Users/minio/vcpkg/packages/pugixml_x64-osx/debug/lib/pkgconfig/pugixml.pc
-- Installing: /Users/minio/vcpkg/packages/pugixml_x64-osx/share/pugixml/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: "/Users/minio/.cache/vcpkg/archives/15/1524c6abe1299b73923ff22d59b2cb45b63cae92fdf3a903654349330b93096b.zip"
Elapsed time to handle pugixml:x64-osx: 10.17 s
Installing 10/10 minio-cpp:x64-osx...
Building minio-cpp[core]:x64-osx...
-- Downloading https://github.com/minio/minio-cpp/archive/v0.1.1.tar.gz -> minio-minio-cpp-v0.1.1.tar.gz...
-- Extracting source /Users/minio/vcpkg/downloads/minio-minio-cpp-v0.1.1.tar.gz
-- Using source at /Users/minio/vcpkg/buildtrees/minio-cpp/src/v0.1.1-c280f46adc.clean
-- Found external ninja('1.11.0').
-- Configuring x64-osx
-- Building x64-osx-dbg
-- Building x64-osx-rel
-- Fixing pkgconfig file: /Users/minio/vcpkg/packages/minio-cpp_x64-osx/lib/pkgconfig/miniocpp.pc
-- Fixing pkgconfig file: /Users/minio/vcpkg/packages/minio-cpp_x64-osx/debug/lib/pkgconfig/miniocpp.pc
-- Installing: /Users/minio/vcpkg/packages/minio-cpp_x64-osx/share/minio-cpp/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: "/Users/minio/.cache/vcpkg/archives/29/295d02b91c8429d8b5421db1443c4ee9086ba28370dc2c4a639300ae51362f8b.zip"
Elapsed time to handle minio-cpp:x64-osx: 26.8 s

Total elapsed time: 4.333 min

```

Locally I am able to build and install this package fine from this PR.  I suspect this is something to do with `pkg-config` but I have no idea how to debug azure pipelines here. 

Is there a reason pkg-config won't be available on OSX?

**Comment by harshavardhana** [comment]
Looks like this

```
configure_file(${CMAKE_CURRENT_SOURCE_DIR}/config.h.in ${CMAKE_CURRENT_SOURCE_DIR}/config.h @ONLY)
```

mostly `CMAKE_CURRENT_SOURCE_DIR` is wrong on OSX

**Comment by JonLiu1993** [comment]
@harshavardhana, I reproduced the ci problem locally, and I add `DISABLE_PARALLEL_CONFIGURE `to function `vcpkg_cmake_configure `in [VCPKG_PATH]/ports/minio-cpp/portfile.cmake as below:
````
vcpkg_cmake_configure(
     SOURCE_PATH "${SOURCE_PATH}"
     DISABLE_PARALLEL_CONFIGURE
     OPTIONS ${FEATURE_OPTIONS}
)
````
Can be installed successfully

**Comment by harshavardhana** [comment]
> @harshavardhana, I reproduced the ci problem locally, and I add `DISABLE_PARALLEL_CONFIGURE `to function `vcpkg_cmake_configure `in [VCPKG_PATH]/ports/minio-cpp/portfile.cmake as below:
> 
> ```
> vcpkg_cmake_configure(
>      SOURCE_PATH "${SOURCE_PATH}"
>      DISABLE_PARALLEL_CONFIGURE
>      OPTIONS ${FEATURE_OPTIONS}
> )
> ```
> 
> Can be installed successfully

Let me check thank you @JonLiu1993

**Comment by harshavardhana** [comment]
That worked thanks a lot @JonLiu1993

**Comment by harshavardhana** [comment]
Next release we will get windows in.

**Review by JonLiu1993 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks!

**Comment by harshavardhana** [comment]
when does the new vcpkgs info gets published to https://vcpkg.io/en/packages.html

**Pull request merged**
