### PR TITLE
[igraph] add support for external BLAS/LAPACK

### PR DESCRIPTION
**Pull request by szhorvat**
**Describe the pull request**

- #### What does your PR fix?
  Adds support for using external BLAS/LAPACK libraries.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  `all`

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  <Yes>

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by szhorvat** [comment]
When I originally contributed igraph to vcpkg, some of the tests would not pass on Windows when using OpenBLAS. Therefore, I did not add support for using external BLAS (igraph vendors its own copy). Now vcpkg contains a newer version of OpenBLAS, and the tests pass, so we can start linking to OpenBLAS by default.

**Comment by Thomas1664** [comment]
Please revert your change to `versions/i-/igraph.json`. Then add `"port-version": 1,` bellow `version` in `ports/igraph/vcpkg.json` and commit your changes. Finally, run `vcpkg x-add-version igraph` and commit the result.

**Comment by szhorvat** [comment]
@Thomas1664 Sorry about that, this is fixed now.

**Review by LilyWangLL — APPROVED** [review]

**Comment by strega-nil-ms** [comment]
I am concerned with this change; it looks like a "vendor if you don't pass a feature" situation, which is imo not a great use of features. Is there any reason we can't remove this feature entirely?

**Comment by szhorvat** [comment]
There are two reasons why I wanted to make it possible to optionally vendor:

 - In the past we had a lot of trouble with OpenBLAS on Windows, with a number of unusual test failures. With the current version of OpenBLAS included in vcpkg, the igraph test suite does pass, hence this PR to use it. However, I do not yet have full confidence in OpenBLAS, so I wanted to make the transition gradual, retaining an option to use the vendored BLAS, in case some users experience problems.
 - Linking to vcpkg's LAPACK brings a dependency on gfortran and its runtime libraries, which AFAICT makes it impossible to use fully static linking. I wanted to retain the possibility for users to use static linking, without the need to ship any MinGW/gfortran components.

    Note: I know that SuiteSparse, another dependency of igraph, also appears to bring in gfortran, but the part of SuiteSparse that igraph uses (CXSparse) does not actually have any dependencies. Suggestion: You could consider breaking up the `suitesparse` port its several independent parts as many other package managers do.

**Comment by strega-nil-ms** [comment]
@szhorvat got it; my second question is, is there any possibility of the vendored copy and the non-vendored copy stepping over each other? In other words:

* if you install both this without the `extern-linalg` feature, and blas and lapack, is there any conflict between the libraries?
* if you link both this without the `extern-linalg` feature, and blas and lapack, is there any linker conflict where they step over each others' symbols?

**Comment by szhorvat** [comment]
There is no possibility for conflict. The symbol names of the vendored BLAS/LAPACK are prefixed with `igraph` to prevent any conflict.

**Comment by szhorvat** [comment]
I would prefer to leave this feature at least temporarily. I think it's a reasonable safety net in case something goes wrong with OpenBLAS, and avoiding the reliance on gfortran is also useful. For example, I maintain the Mathematica interface of igraph, and I was hoping that in the future I can simply use vcpkg's igraph for it, to make it easier for others to contribute. But I can only do this if I avoid the gfortran dependency.

That said, if you decide that this feature won't be allowed, I'll remove it.

**Comment by strega-nil-ms** [comment]
@szhorvat Our opinion at this point:

We would like the feature to be removed, so you always use external blas and lapack; if we get actual reports of user pain from this suggestion, we can add the feature back in. You can just comment out the support code, instead of removing it entirely, so it's easy to add the feature back if we need to.

**Comment by szhorvat** [comment]
@strega-nil-ms A question before we finalize this: Does vcpkg have some way to ensure that CMake's FindBLAS picks up a BLAS provided by vcpkg itself? There could be other BLAS present on the system. For example, a BLAS implementation is present on all macOS.

Is it possible to have multiple BLAS implementations installed at the same time with vcpkg? If yes, how do I make it predictable which one gets picked? [Normally one sets `BLA_VENDOR`](https://cmake.org/cmake/help/latest/module/FindBLAS.html), but this affects finding both BLAS and LAPACK, and vcpkg (unusually) uses OpenBLAS for BLAS and the reference LAPACK for LAPACK, so `BLA_VENDOR=OpenBLAS` won't work.

**Comment by Neumann-A** [comment]
> [Normally one sets BLA_VENDOR](https://cmake.org/cmake/help/latest/module/FindBLAS.html), but this affects finding both BLAS and LAPACK, and vcpkg (unusually) uses OpenBLAS for BLAS and the reference LAPACK for LAPACK, so BLA_VENDOR=OpenBLAS won't work.

The `blas` and `lapack` need to learn a way to force this via setting `BLA_VENDOR=<vendor>` in a `vcpkg-cmake-wrapper.cmake`

**Comment by strega-nil-ms** [comment]
@szhorvat I don't know; this would be a question for @Neumann-A. I don't think it's likely.

**Comment by szhorvat** [comment]
@strega-nil-ms It now always uses external BLAS/LAPACK.

@Neumann-A Let me know if we should make any more changes here before merging this.

**Comment by Neumann-A** [comment]
>  Should I add any BLA_VENDOR specification to this port, and if yes, what?

No. This has to be dealt with elsewhere.

> Note that igraph relies on CMake's default FindBLAS and FindLAPACK 

That is totally fine.

**Comment by strega-nil-ms** [comment]
Thanks so much! I really appreciate it :)

**Pull request merged**
