### PR TITLE
[xerces-c] Remove unnecessary duplication of import prefix

### LINKED ISSUE #5819: Xerces-C can't be found by CMake anymore
I have used Xerces-C 3.2.2-6 which worked without hassle.

I did a git pull today (using 3.2.2-7) and rebuilt all my libraries.

However, CMake doesn't find Xerces-C anymore:

    CMake Error at D:/vcpkg/installed/x86-windows/share/xercesc/XercesCConfigInternal.cmake:80 (message):
    The imported target "xerces_xerces-c" references the file

     "D:/vcpkg/debug/lib/xerces-c_3D.lib"

      but this file does not exist.  Possible reasons include:

      * The file was deleted, renamed, or moved to another location.

      * An install or uninstall procedure did not complete successfully.

      * The installation package was faulty and contained

     "D:/vcpkg/installed/x86-windows/share/xercesc/XercesCConfigInternal.cmake"

     but not all the files it references.

     Call Stack (most recent call first):
     D:/vcpkg/installed/x86-windows/share/xercesc/XercesCConfig.cmake:27 (include)
     D:/vcpkg/scripts/buildsystems/vcpkg.cmake:233 (_find_package)
     CMakeLists.txt:26 (find_package)

    Configuring incomplete, errors occurred!

The given path `D:/vcpkg/debug/lib/xerces-c_3D.lib` doesn't exist anyway.

### PR DESCRIPTION
**Pull request by ruggin**
This fixes #5819 by simply removing the rewrite of the XercesCConfigInternal.cmake that appears to duplicate the _IMPORT_PREFIX. It is not immediately clear why this is being done in the first place but appears unnecessary and causes the package to not be found. Users are currently working around this by removing or manually editing the generated file.

### CODE REVIEW

**Comment by vicroms** [comment]
Please also bump the version in the CONTROL file

**Comment by NancyLi1013** [comment]
Hi @ruggin, here are some regressions from the current CI system:

|x64-windows|test|notes
|-----------|----|-----
|msix       |Fail|**Regression**

|x86-windows|test|notes
|-----------|----|-----
|msix       |Fail|**Regression**

[failureLogs.zip](https://github.com/microsoft/vcpkg/files/3221638/failureLogs.zip)

**Comment by ruggin** [comment]
Looks like a fix for this has already been applied. 

https://github.com/microsoft/vcpkg/commit/33af90d42af68ef343edb00a69b1e11548a9e2e1#diff-fd850636e03dbb0fae1475d658759dc0

**Pull request closed without merging**
