### PR TITLE
[Arrow] Update to 1.0.0

### PR DESCRIPTION
**Pull request by GPSnoopy**
Update Arrow from 0.17.1 to the recently released 1.0.0.

Built and successfully tested on x64-windows-static, x64-linux and x64-osx as part of https://github.com/G-Research/ParquetSharp/pull/146.

Changes:
* Added dependency on utf8proc (new dependency added in 1.0.0, enabled by default).
* Added explicit Shared/Static config flags for some of the dependencies; these are now needed for correct linkage (and for CMake to find the correct libraries).
* Simplified part of the patches.

(The dependencies handling by Arrow upstream CMake files is a bit of a hit and miss, there is little consistency. Nothing new here, but it does mean that most of the existing patches are still necessary.)

(I've also reported the lack of UTF8PROC_STATIC definition upstream: https://issues.apache.org/jira/browse/ARROW-9541)

### CODE REVIEW

**Comment by xhochy** [comment]
Note that Arrow 1.0 is not released yet, you should not use Github as a source as the 1.0 is moved until a release is done.

**Comment by GPSnoopy** [comment]
Thanks for the clarification @xhochy. I didn't realise this was only a Release Candidate (I checked the chatter on arrow-dev mailing list). I'll update the PR when the Final release is done (I wouldn't expect many changes, so we'll be ready).

**Review by LilyWangL — APPROVED** [review]

**Comment by GPSnoopy** [comment]
According to https://arrow.apache.org/install/, the release candidate has now been promoted to final release. I'm happy for this PR to be merged to master.

**Comment by strega-nil** [comment]
Something is wrong with itk on x64-osx; unsure what.

Thanks @GPSnoopy!

**Pull request merged**
