### PR TITLE
upgrade cmake to 3.14.0 in order to support VS2019

### PR DESCRIPTION
**Pull request by cyyever**

### CODE REVIEW

**Comment by Rastaban** [comment]
It looks like the hash may not be correct:

```
Downloading cmake...
  https://github.com/Kitware/CMake/releases/download/v3.14.0/cmake-3.14.0-win32-x86.zip -> C:\vsts\_work\2\s\downloads\cmake-3.14.0-win32-x86.zip
File does not have the expected hash:
             url : [ https://github.com/Kitware/CMake/releases/download/v3.14.0/cmake-3.14.0-win32-x86.zip ]
       File path : [ C:\vsts\_work\2\s\downloads\cmake-3.14.0-win32-x86.zip.part ]
   Expected hash : [ 9eb42917f9c5dc30ff86d8197497e4f8e2f4455b4c07841aa3dfb3283902d1ee ]
     Actual hash : [ 60eb6a0790883da4152a957bd1133405f620f4b7a073af3bea97695b3ef8c22c41d9b90e45815f2a896df5be0cd6dedb73a6df5f17a42761ca8f457c9f3b708c ]

```

**Comment by cyyever** [comment]
> 
> 
> It looks like the hash may not be correct:
> 
> ```
> Downloading cmake...
>   https://github.com/Kitware/CMake/releases/download/v3.14.0/cmake-3.14.0-win32-x86.zip -> C:\vsts\_work\2\s\downloads\cmake-3.14.0-win32-x86.zip
> File does not have the expected hash:
>              url : [ https://github.com/Kitware/CMake/releases/download/v3.14.0/cmake-3.14.0-win32-x86.zip ]
>        File path : [ C:\vsts\_work\2\s\downloads\cmake-3.14.0-win32-x86.zip.part ]
>    Expected hash : [ 9eb42917f9c5dc30ff86d8197497e4f8e2f4455b4c07841aa3dfb3283902d1ee ]
>      Actual hash : [ 60eb6a0790883da4152a957bd1133405f620f4b7a073af3bea97695b3ef8c22c41d9b90e45815f2a896df5be0cd6dedb73a6df5f17a42761ca8f457c9f3b708c ]
> ```

The hash values is given by CMake.You used a particialy  

> 
> 
> It looks like the hash may not be correct:
> 
> ```
> Downloading cmake...
>   https://github.com/Kitware/CMake/releases/download/v3.14.0/cmake-3.14.0-win32-x86.zip -> C:\vsts\_work\2\s\downloads\cmake-3.14.0-win32-x86.zip
> File does not have the expected hash:
>              url : [ https://github.com/Kitware/CMake/releases/download/v3.14.0/cmake-3.14.0-win32-x86.zip ]
>        File path : [ C:\vsts\_work\2\s\downloads\cmake-3.14.0-win32-x86.zip.part ]
>    Expected hash : [ 9eb42917f9c5dc30ff86d8197497e4f8e2f4455b4c07841aa3dfb3283902d1ee ]
>      Actual hash : [ 60eb6a0790883da4152a957bd1133405f620f4b7a073af3bea97695b3ef8c22c41d9b90e45815f2a896df5be0cd6dedb73a6df5f17a42761ca8f457c9f3b708c ]
> ```

fixed

**Comment by Rastaban** [comment]
Sorry for the delay, I am currently running some tests on this change.

**Comment by Rastaban** [comment]
These changes were combined with #5702 and merged.  Thank you for the PR!

**Pull request closed without merging**
