### PR TITLE
[vcpkg scripts] Update msys2

### PR DESCRIPTION
**Pull request by dg0yt**
msys2-runtime no longer supports Windows 7 since version 3.5. msys2-runtime-3.4 is the replacement for user who cannot upgrade. YMMV.

autoconf-wrapper is not updated, cf. #36774.

pkgconf is not updated, waiting for 2.2.

### CODE REVIEW

**Comment by Osyotr** [comment]
Are Windows 7 *dev* machines still a thing?

**Comment by dg0yt** [comment]
> Are Windows 7 _dev_ machines still a thing?

I don't know but some industries might be very conservative. IIUC vcpkg tool is kept running on Windows 7, and it is still the minimum requirement at https://github.com/Microsoft/vcpkg?tab=readme-ov-file#quick-start-windows.

**Review by Cheney-W — DISMISSED** [review]

**Comment by vicroms** [comment]
We discussed this PR during our weekly meeting:

We are due to update our documented minimum requirements. The new minimum supported versions for Windows are 8.1 onwards.

**Comment by dg0yt** [comment]
Fine, I will update the PR soon.

**Comment by Neumann-A** [comment]
Is there an automatic script for updating the msys stuff?

**Comment by dg0yt** [comment]
> Is there an automatic script for updating the msys stuff?

There is (limited) automation via `vcpkg-ci-msys2[update-all]`.
It still needs human brain to review what to merge and which dependencies to override.

And I run it on `linux` with `--allow-unsupported`.

**Comment by dg0yt** [comment]
Maybe related: https://github.com/microsoft/vcpkg/issues/39171#issuecomment-2154637815

**Comment by BillyONeal** [comment]
> We are due to update our documented minimum requirements. The new minimum supported versions for Windows are 8.1 onwards.

This is applied in https://github.com/microsoft/vcpkg-docs/pull/339

@dg0yt Thank you for the update.

**Pull request merged**
