### PR TITLE
[fmt] Fix an easily avoidable compilation warning

### PR DESCRIPTION
**Pull request by PazerOP**
In the fmt package, there is a patch that adds `#pragma warning(disable:4189)` near the top of the main include file. This does not account for non-MSVC compilers, so I added a check for that.

- #### What does your PR fix?  
  Fixes fmt not being able to compile on non-MSVC compilers that treat unknown pragmas as errors (whether due to warnings-as-errors, or otherwise).

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  Only a compile issue fix.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes, only a compile issue fix.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes.

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Review by NancyLi1013 — COMMENTED** [review]
Could you please also update` port-version` as 5 in vcpkg.json?

**Comment by Hoikas** [comment]
IMO this is inappropriate for inclusion into vcpkg because it will change the warning state of consumer code.

**Comment by PazerOP** [comment]
> Could you please also update` port-version` as 5 in vcpkg.json?

Done.

> Despite what OP says, this patch seems to add a new warning pragma where there was not one previously. IMO this is inappropriate for inclusion into vcpkg because it will change the warning state of consumer code.

It does not add a new warning pragma. See https://github.com/microsoft/vcpkg/blob/master/ports/fmt/fix-warning4189.patch. Although I agree with you it's not the best idea in the first place.

**Comment by Hoikas** [comment]
Ah, I see. GitHub's diff views of diffs is playing with my eyes... IMO that whole patch should be deleted.

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
LGTM now, thanks for your fixing @PazerOP.

**Comment by ras0219-msft** [comment]
This PR is a strict upgrade, so I'm going to merge it as-is -- however I do agree that this should eventually be changed to a push+pop and upstreamed :)

Thanks for the PR!

**Pull request merged**
