### PR TITLE
[eastl] Fix error C2338

### PR DESCRIPTION
**Pull request by Cheney-W**
- #### What does your PR fix?  
  In an internal version of Visual Studio, eastl install failed with following error:
  `internal\atomic\atomic_integral.h(330): error C2338: eastl::atomic<T> atomic macro not implemented!`
  
  This issue could be fixed by adding the compile option: /Zc:static_assert- or modifying the source, I added this patch only as a temporary workaround, the specific fix still needs to be discussed with upstream.

No feature need to be tested.

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by BillyONeal** [comment]
What is the behavior of adding `/Zc:static_assert-` with older compilers?

**Comment by BillyONeal** [comment]
I observe that `/Zc:static_assert-` is not documented: https://docs.microsoft.com/en-us/cpp/build/reference/zc-conformance?view=msvc-170

**Comment by Cheney-W** [comment]
1. I have compared one by one the output of this port between the older compiler and the latest compiler with /Zc:static_assert- option, I didn't notice any difference.
2. This option is added by Jonathan Caves, please check the related [commit](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/msvc/commit/95d95e7f1b1ec76e3edfcac07500d01207fdbdde?refName=refs/heads/prod/fe&tab=details) for more info.

**Comment by BillyONeal** [comment]
I asked Jonathan Caves to comment.

**Comment by BillyONeal** [comment]
(I'm not sure whether 'author response' or 'upstream changes' convey the right tone here but...)

**Comment by Cheney-W** [comment]
Avoid affecting the PR age, converted this PR to draft.

**Comment by BillyONeal** [comment]
I know we talked a lot about this change out-of-band; to summarize what I think needs to happen:

* Given that there is no documented behavior for what the compiler does on unrecognized `/Zc` flags and the existence of `clang-cl` and friends, I think this needs to be guarded for versions of the compiler new enough to support it.
* Documentation for the new `/Zc` switch needs to be added to MSDN/docs.microsoft.com/etc.

**Comment by JackBoosY** [comment]
Ping @Cheney-W

**Comment by Cheney-W** [comment]
The /Zc:static_assert- option is now recognized in the latest VS2022 17.1.0 Preview 5, but this version should not be able to be used as a judgment node for implementing version protection.
We may have to wait for VS2022 17.1 to be released.

@BillyONeal What do you think about this?

**Comment by BillyONeal** [comment]
@Cheney-W As long as the version check can be done in CMake world I think it's fine without waiting for 17.1. Perhaps `CMAKE_C_COMPILER_VERSION`/`CMAKE_CXX_COMPILER_VERSION` could work?

**Review by BillyONeal — APPROVED** [review]

**Review by JackBoosY — APPROVED** [review]

**Comment by ras0219-msft** [comment]
Thanks!

**Pull request merged**
