### PR TITLE
[boost-vcpkg-helpers] Pass boost port creation output folder as a parameter

### PR DESCRIPTION
**Pull request by sagmor**
This is to reuse this script to easily generate port overlays targeting different boost versions.

Like:
```powershell
.\Vcpkg\ports\boost-vcpkg-helpers\generate-ports.ps1 -version 1.67.0 -portsFolder .\My\Port\Overlay\Folder
```

### CODE REVIEW

**Comment by PhoebeHui** [comment]
@sagmor, could you please resolve the conflicts?

**Comment by sagmor** [comment]
done

**Comment by PhoebeHui** [comment]
@vicroms, the CI on OSX failed on git 'checkout' steps, could you help take a look?

**Comment by ras0219-msft** [comment]
LGTM, thanks for the PR!

**Pull request merged**
