### PR TITLE
[imgui] update docking branch to 1.81

### PR DESCRIPTION
**Pull request by strega-nil**
Last time imgui was updated, the docking branch was not also updated.

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
Waiting for test features.

**Comment by JackBoosY** [comment]
Tested feature `docking-experimental` successfully on `x86-windows` and `x64-windows-static`.

**Comment by RT222** [comment]
Thanks but I made a similar pull request some times ago which also update the freetype feature : https://github.com/microsoft/vcpkg/pull/16268

**Comment by strega-nil** [comment]
Fixed by #16268 instead.

**Pull request closed without merging**
