### PR TITLE
[freetds] Add new port

### PR DESCRIPTION
**Pull request by maharmstone**
Adds port for FreeTDS (https://www.freetds.org/), the free implementation of the Tabular Data Stream protocol that Microsoft SQL Server uses to communicate.

### CODE REVIEW

**Comment by NancyLi1013** [comment]
Hi @maharmstone, thanks for the new port. Here are the test results from the current CI system:

|x64-osx|test|notes
|-------|----|-----
|freetds|Fail|New Port

|arm64-windows|test|notes
|-------------|----|-----
|freetds      |Fail|New Port

|x86-windows|test|notes
|-----------|----|-----
|freetds    |Pass|New Port

|x64-linux|test|notes
|---------|----|-----
|freetds  |Fail|New Port

|x64-uwp|test|notes
|-------|----|-----
|freetds|Fail|New Port

|arm-uwp|test|notes
|-------|----|-----
|freetds|Fail|New Port

[failureLogs.zip](https://github.com/microsoft/vcpkg/files/3209892/failureLogs.zip)

**Comment by crazy2013** [comment]
Ur fucking crazy or a married man

**Comment by Rastaban** [comment]
@maharmstone this port is looking good to me so far and is passing the windows and windows-static builds.  Are you interested in investigating the failures on other triplets?  If you don't have time then I will merge this as is and the other triplets can be addressed in a separate PR.

**Comment by maharmstone** [comment]
Thanks - if you can merge it as it is for now, that'd be great.

I can't do anything about OS X or ARM, but the Linux version compiles alright on my Gentoo box, so it must be something minor - I'll send through a separate PR once I sort it.

**Comment by Rastaban** [comment]
If the Linux build failure comes down to a missing dependency that needs to be added to the build machine let me know via an issue.

**Pull request merged**
