### PR TITLE
[OpenMPI] add a new port

### PR DESCRIPTION
**Pull request by cenit**

### CODE REVIEW

**Comment by cenit** [comment]
i also provided a generic `mpi` port, which is the one that should be used. It redirects to `msmpi` on windows, `openmpi` otherwise.
Still untested, but it should be ready

**Comment by cenit** [comment]
there are failures on Windows but I think they are perfectly acceptable, since openmpi is ported only for linux/mac

**Comment by vicroms** [comment]
Sorry for the barrage of `/azp run`, this PR exposed some flaky ports that weren't fixed yet.

**Comment by vicroms** [comment]
Is there a reason why UWP support has been disabled? 

There's a regression on `msmpi:x64-uwp`, and I'm also able to build it locally.

**Comment by cenit** [comment]
msmpi is not built from source (unfortunately - https://github.com/microsoft/Microsoft-MPI/issues/2), so I just assumed the library was not uwp-ready (the same .lib is used for x64-windows...)
Unfortunately I don't have any program to test msmpi:x64-uwp, if you have any please let me know if I overlooked it. My principle was "better safe than sorry", and so I removed the compatibility if it was not really there.

**Comment by vicroms** [comment]
Thanks for the PR!

**Pull request merged**
