### PR TITLE
[glm] Bump to 2023-08-18

### PR DESCRIPTION
**Pull request by xiaozhuai**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

Fix `GLM_FORCE_QUAT_DATA_XYZW ` not working.
See also https://github.com/microsoft/vcpkg/pull/32685#issuecomment-1764289386

### CODE REVIEW

**Comment by dg0yt** [comment]
You suggest to use `GLM_FORCE_QUAT_DATA_XYZW` to enable old behaviour. However, it means that different downstreams could disagree on the actual data layout. 
This problem seems to have existed before, but with the changed data layout, it becomes more relevant because downstream are forced to react. 

It might have been easier if vcpkg wouldn't have diverged from the official release's default layout already.

I wonder if an extra paragraph in `usage` would help with this situation.

**Comment by Osyotr** [comment]
It might have been easier if vcpkg didn't update glm at all. As a user, I would expect `vcpkg install glm` to install latest release, as any package manager would do.

**Comment by xiaozhuai** [comment]
Convert to draft. I would like to hear more views on this issue.

**Comment by dg0yt** [comment]
@MonicaLiu0311 This might need a vcpkg team review.

**Comment by marekr** [comment]
> It might have been easier if vcpkg wouldn't have diverged from the official release's default layout already.

Yes, vcpkg diverging is what has made this port difficult to use now.

vcpkg is now creating non-maintainer supported releases and there is zero documentation for these releases. Meaning, the API breaking changes are not documented. Such as the changing of the quanterion data structure.

> You suggest to use `GLM_FORCE_QUAT_DATA_XYZW` to enable old behaviour. However, it means that different downstreams could disagree on the actual data layout.

Heh, we had to pin vcpkg glm to 0.9.9.8#2 :3

**Comment by MonicaLiu0311** [comment]
@JavierMatosD Please help take a look at this PR.

There are different opinions on the impact of changes in GLM data layout and how vcpkg handles GLM version updates:
https://github.com/microsoft/vcpkg/pull/34523#issuecomment-1765697528
https://github.com/microsoft/vcpkg/discussions/34511#discussion-5742237

**Comment by JavierMatosD** [comment]
> @JavierMatosD Please help take a look at this PR.

Can you explain how this update fixes the problem? From the conversation, it seems like vcpkg updated `glm` prematurely, diverging from upstream release schedule, which resulted in breaking changes to downstream users, i.e., the change to the data layout.

**Comment by MonicaLiu0311** [comment]
> Can you explain how this update fixes the problem? From the conversation, it seems like vcpkg updated glm prematurely, diverging from upstream release schedule, which resulted in breaking changes to downstream users, i.e., the change to the data layout. This seems to be updating to a newer commit?

The latest upstream release version is [0.9.9.8](https://github.com/g-truc/glm/releases/tag/0.9.9.8), released on 2020-04-14.

Macro `GLM_FORCE_QUAT_DATA_WXYZ` has been added upstream since `0.9.9.7`: [master/readme.md#improvements-2](https://github.com/g-truc/glm/blob/master/readme.md#improvements-2)
Version `0.9.9.8` also retains this macro: [0.9.9.8/manual.md#section2_21](https://github.com/g-truc/glm/blob/0.9.9.8/manual.md#section2_21)


However, since 2021-06-01, the upstream has successively changed it to `GLM_FORCE_QUAT_DATA_XYZW`. But regarding these modifications, the upstream has not given corresponding instructions because they have not released a new version so far.
https://github.com/g-truc/glm/commit/59ddeb7d1c5455cedbe29be31a086bb38449a6bb
https://github.com/g-truc/glm/commit/f32eea13455215369380df82e212c287e5da4f56
https://github.com/g-truc/glm/commit/9398c5843f70fddec3d7d344b224cd85ea1f04ea
https://github.com/g-truc/glm/commit/de7c83f1b6f3f252c13dc32a7e33e0688bcf1498


Prior to PR https://github.com/microsoft/vcpkg/pull/32685, the version in VCPKG was consistent with upstream, but @xiaozhuai  updated GLM to the latest commit(5c46b9c) at the time, which included these modifications from upstream and broke the data layout for [some users](https://github.com/microsoft/vcpkg/pull/32685#issuecomment-1764242765).

Upstream made some fixes in https://github.com/g-truc/glm/pull/1148, so @xiaozhuai  started this update to make `GLM_FORCE_QUAT_DATA_XYZW` work. But whether the user's problem is really fixed may require @dsa-t's follow-up help to verify.


@xiaozhuai  If you have any other clarifications, please add them, thanks.

**Comment by xiaozhuai** [comment]
Thanks @MonicaLiu0311 
I think what you said is detailed enough.

In the meantime, I'll also explain why I submitted #32685

First of all, my projects did benifit from the update.
It's been more than 2 years since the last release of version 0.9.9.8.
Before latest update of this port, I tried to get in touch with upstream to get the new version released, but upstream didn't reply.

This leads us to believe that GLM is entering a rolling update phase, then I switch it to version-date and update to the latest commit at the time.

But unfortunately GLM introduced significant changes during this period, and that's something I haven't found.
Just as @marekr said, there is zero documentation.


My conclusion is:
If this broke the downstream user, I'd prefer to revert this port to 0.9.9.8. (It does happen at the moment). 
Perhaps upstream will propose a good solution in a subsequent release, or improve the relevant documentation.

So I will close this PR.
Thanks @Osyotr for submiting #34591

**Comment by xiaozhuai** [comment]
@dg0yt @marekr @MonicaLiu0311 @Osyotr @JavierMatosD 
Waiting for glm 1.0.0
See
https://github.com/g-truc/glm/pull/1186
https://github.com/g-truc/glm/pull/1183
https://github.com/g-truc/glm/pull/1180

**Comment by shrinktofit** [comment]
> @dg0yt @marekr @MonicaLiu0311 @Osyotr @JavierMatosD Waiting for glm 1.0.0 See [g-truc/glm#1186](https://github.com/g-truc/glm/pull/1186) [g-truc/glm#1183](https://github.com/g-truc/glm/pull/1183) [g-truc/glm#1180](https://github.com/g-truc/glm/pull/1180)

Will glm 1.0.0 solve the problem? I'm just waiting for the fix for `-glm::quat{1, 0, 0, 0} != glm::quat{-1, 0, 0, 0}` under macro `GLM_FORCE_QUAT_XYZW_ORDER`.

**Comment by xiaozhuai** [comment]
> > @dg0yt @marekr @MonicaLiu0311 @Osyotr @JavierMatosD Waiting for glm 1.0.0 See [g-truc/glm#1186](https://github.com/g-truc/glm/pull/1186) [g-truc/glm#1183](https://github.com/g-truc/glm/pull/1183) [g-truc/glm#1180](https://github.com/g-truc/glm/pull/1180)
> 
> Will glm 1.0.0 solve the problem? I'm just waiting for the fix for `-glm::quat{1, 0, 0, 0} != glm::quat{-1, 0, 0, 0}` under macro `GLM_FORCE_QUAT_XYZW_ORDER`.

`GLM_FORCE_QUAT_XYZW_ORDER` is already removed in https://github.com/g-truc/glm/pull/1183.
Now the data layout is `xyzw` by default.
You can clone the master branch to test if the latest commits fix your problem.

**Pull request closed without merging**
