### PR TITLE
[air-ctl] Update to v1.1.2

### PR DESCRIPTION
**Pull request by inie0722**
**Describe the pull request**

- #### What does your PR fix?
 air-ctl update to v1.1.2

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  `all Yes`

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  `Yes`

### CODE REVIEW

**Comment by JonLiu1993** [comment]
CI test error but not caused by this port: 
````
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:14 (message):
  

  File does not have expected hash:

          File path: [ D:/downloads/inie0722-CTL-v1.1.2.tar.gz ]
      Expected hash: [ 5669db0448359023cc55b0f9134084cda3aea716996d58ef7e8e63d3721c074af27f59a52c1976c72decea93630f64c463718344f34fdae3e5a832c9d876913a ]
        Actual hash: [ e44d978875e030ded9a40687063f5fc9624307942ff2f2c40aad334c280c04464198f7a784c28206a8b328fc9f9ea26cf3e095bac44bede2522513b0d16e56b1 ]

  The cached file SHA512 doesn't match.  The file may have been corrupted.
  To re-download this file please delete cached file at path
  D:/downloads/inie0722-CTL-v1.1.2.tar.gz and retry.

````

**Comment by inie0722** [comment]
CI may read the previous cache.

**Review by JonLiu1993 — APPROVED** [review]

**Comment by vicroms** [comment]
There was probably another PR at some point for this version(?).

Seems weird to me that we had a cache conflict while using `vcpkg_from_github`. This means we should probably take a look at how temporary file names under the hood to prevent this from happening again.

**Pull request merged**
