### PR TITLE
[ogre] initial commit

### PR DESCRIPTION
**Pull request by codicodi**
This features the latest (2.1) development branch. Some plugins and components doesn't seem to compile, but core stuff and rendering systems are [said](http://www.ogre3d.org/tikiwiki/tiki-index.php?page_ref_id=2191#Is_Ogre_2.1_stable_) to be stable.

### CODE REVIEW

**Comment by traversaro** [comment]
Great! 
I was also working on packaging `ogre` (see https://github.com/traversaro/vcpkg_playground/tree/master/ogre), but I was focusing on v1.9 because as I far as I understand, ogre v1.* and v2.* are not source code compatible. 
My main interested in getting ogre in vcpkg is to simplify Windows compilation of applications depending on Ogre (in particular the [Gazebo robotics simulator](http://gazebosim.org/) ). Most of this applications still depend on Ogre v1.x, as Ogre v2.x is not *stable* in the sense of the fact that the interfaces does not change, in fact OGRE developers state: 
> However being still in development there is the occasional build-breaking change that usually takes 10 to 20 minutes of your dev time to adapt your code. There aren't huge/major changes anymore. 

I wonder how we could satisfy both the needs for ogre v1.* and ogre v2.* . If we could enforce mutual exclusion between two ports, we could have the two ports `ogre` (v1.x) and `ogre2` (v2.x), but this is not possible at the moment as far as I know.

From the port point of view, I think we can:
* avoid to modifying the installation paths in the port file by patching directly the `CMakeLists.txt` files in an upstream-friendly way, see https://github.com/traversaro/vcpkg_playground/blob/master/ogre/0003-use-flat-installation.patch 
* easily support `find_package(OGRE)` out of the box, instead of deleting all the CMake files : https://github.com/traversaro/vcpkg_playground/blob/master/ogre/0002-ogre-cmake-dir-as-option.patch and https://github.com/traversaro/vcpkg_playground/blob/master/ogre/OGREConfig.cmake 
* avoid to install anything in `media` (that is not necessary to use ogre as a library, if I understand correctly) by setting `OGRE_INSTALL_SAMPLES` to OFF https://github.com/traversaro/vcpkg_playground/blob/master/ogre/portfile.cmake#L32
* disable compilation of the tools instead of deleting them afterwords, https://github.com/traversaro/vcpkg_playground/blob/master/ogre/portfile.cmake#L29 .

How does this works without disabling installation of dependencies (whose location is assumed to be in an hardcoded position by ogre, see https://github.com/traversaro/vcpkg_playground/blob/master/ogre/portfile.cmake#L27 and https://bitbucket.org/sinbad/ogre/src/06631aef218d73fdc2ca323da626a53650d941be/CMake/InstallDependencies.cmake?at=v2-1&fileviewer=file-view-default#InstallDependencies.cmake-21 .

**Comment by ras0219-msft** [comment]
W.r.t. the previous version of ogre, you're exactly right that to handle the older non-compatible version we need to make the two ports mutually exclusive. Today, however, we don't have a good way to do that.

I think the best thing to do (for now) would be to put a comment at the top of this portfile that links to that specific commit+folder in your github repo[1] and indicates that users who need 1.x _today_ can grab that port folder to replace the default one in their repo.

In the future, we can make this process better via a resolution to #164.

[1] https://github.com/traversaro/vcpkg_playground/tree/adf246855d31c1e13c81078c00229fe08e3a4c3e/ogre

**Comment by traversaro** [comment]
@ras0219-msft Good idea, but are we sure that for the default port (the one available in `Microsoft/vcpkg`) we want to go with an unstable and unreleased version of Ogre? Note that Ogre v2.1 has not even released as a tag on bitbucket [1], and even the version 2.0 has been tagged just as an Release Candidate. 
Furthermore all the Linux distributions I am aware of, such as [Ubuntu](http://packages.ubuntu.com/search?suite=yakkety&section=all&arch=any&keywords=libogre&searchon=names), [Debian Sid](https://packages.debian.org/sid/libogre-1.9-dev), [Fedora](https://apps.fedoraproject.org/packages/ogre), [Gentoo](https://packages.gentoo.org/packages/dev-games/ogre) and even [Arch](https://www.archlinux.org/packages/community/i686/ogre/) all package Ogre 1.9 . 

[1] https://bitbucket.org/sinbad/ogre/#tags

**Comment by codicodi** [comment]
@traversaro,  good points, I'll work on it.
As for the default ogre version I don't see why should we stick to 1.9.
Over a year ago, main ogre developer [wrote](http://www.ogre3d.org/forums/viewtopic.php?f=25&t=83171):

> If "stable" means, bug-free / few bugs; then I dare to say Ogre 2.1 is already stable and even surpasses the 1.x branch.
> If "stable" means stable codebase, then there are still changes to be made. While the codebase has become much more stable in the last few months, we have yet to add support for GLES2 (no ETA), polish the v2 mesh file format, add tag points, add Hlms customization interface, perform a few shadow map enhancements.
> 
> Several persons have notified they're starting to use 2.1 for their commercial projects. Even myself, I am using it in production too.

And most of the issues mentioned here are already fixed.
Some interesting points are also made [here](http://www.ogre3d.org/about/what-version-to-choose).

The problem is that if we provide 1.9 now as default version, we may have problems with upgrading it later when both vcpkg and ogre 2,1 will be "fully stable".

**Comment by ras0219-msft** [comment]
Ah, I didn't see that 2.1 isn't a released version; we should provide 2.0 at the latest by default then.

Now, between 2.0 and 1.9, I think the fact that all major Linux distributions (even the famously bleeding Arch!) are packaging 1.9 is a hugely strong indicator that the OSS ecosystem is still thriving around 1.9. For example: if I want to publish a plugin or similar for ogre and I want it available in everyone's favorite package managers, it's a pretty clear choice which version I will target -- 1.9.

As an application developer, it sounds like there are some really good reasons to use the latest version of 2.1: way better perf, DX11 support, usability improvements, etc. We do need to _enable_ you to do that! But, it looks like the _ecosystem_ simply isn't there and hasn't even started moving in earnest. 

I believe the most prudent course is to package 1.9 by default. I'd be happy to have some instructions in the portfile on how to locally switch to 2.0 or 2.1; in the worst case this could be a comment pointing at another GitHub. In the best case, it could be a single line you need to uncomment/change.

_Re: problems upgrading later_
I'm sure Ogre has a bright and evolving future :); when 2.1 is stable, there will certainly be a 2.2 unstable branch with breaking changes that puts us in a similar position. I believe that at that time, 2.1 will be preferable to 2.2.

_Additional comments around unstable APIs:_
The fundamental reason why we don't want unreleased versions of software with unstable APIs as the default is because software in that state is incredibly hard to build upon for other projects. While 2.1 is unstable, every _user_ of 2.1 in the wild will almost certainly be using _API incompatible versions_. This means unending pain for anyone who would like to build an OSS library or plugin on top of Ogre; either I'm limited to an audience of 2-3 people or I spend all my time trying to make compatibility shims to support dozens of 2.1 subversions.

**Comment by codicodi** [comment]
> Additional comments around unstable APIs...

I guess you're right. I'll keep v.2.1 port around then. :)

**Comment by codicodi** [comment]
@traversaro I looked at your port and it seems pretty nice, however this
`URLS "https://bitbucket.org/sinbad/ogre/get/v1-9-0.zip"`
will download the latest version of 1.9 branch, so any fixes merged to it will break the hash. I guess this `https://bitbucket.org/sinbad/ogre/get/dd30349ea667.zip` shoud be tied to specific commit.

**Comment by traversaro** [comment]
@codicodi I may be getting something wrong, but I think that [`v1-9`](`https://bitbucket.org/sinbad/ogre/src/108ab0bcc69603dba32c0ffd4bbbc39051f421c9/?at=v1-9`) is indeed the branch, while that URL will download the tarball for the tag [`v1-9-0`](https://bitbucket.org/sinbad/ogre/src/dd30349ea6670e3cd962d9d41a8039de3a3482d3/?at=v1-9-0) that as a tag will always point to the same commit.

**Comment by codicodi** [comment]
@traversaro ah, it's a tag, not a branch. My bad, sorry!

**Pull request closed without merging**
