### PR TITLE
[range-v3] set license

### PR DESCRIPTION
**Pull request by JulZimmermann**
**Describe the pull request**

sets license in port `range-v3`

### CODE REVIEW

**Comment by Cheney-W** [comment]
I saw this port also have below licenses:
```
libc++ License
Stepanov and McJones, "Elements of Programming" license
SGI C++ Standard Template Library license
```

**Comment by JulZimmermann** [comment]
Yes, you are right.

I looked at the licenses of the referenced packages (all listed [here](https://github.com/ericniebler/range-v3/blob/master/LICENSE.txt)):
- range-v3 itself: `BSL-1.0`
- Alex Stepanov's Elements of Programming: `MIT`
- libc++: `NCSA OR MIT`
- SGI STL: `MIT`

In this case, the correct license entry would probably be: `BSL-1.0 AND MIT AND (NCSA OR MIT)`

Should I change it to this string?

**Comment by Cheney-W** [comment]
I think the license could be `BSL-1.0 AND MIT AND NCSA`.

**Comment by JulZimmermann** [comment]
I think `BSL-1.0 AND MIT AND NCSA` would indicate that the port has components licensed under `NCSA` in any case.

However, the libc++ license states:
```
The libc++ library is dual licensed under both the University of Illinois
"BSD-Like" license and the MIT license.  As a user of this code you may choose
to use it under either license.  As a contributor, you agree to allow your code
to be used under both.
```

Because of the sentence `As a user of this code you may choose
to use it under either license`, the user can choose not to use `NCSA` license at all, but instead use `MIT`.

Because of this, I don't think the `OR` should be left out.

**Comment by Cheney-W** [comment]
I agree with your decision.

**Comment by JulZimmermann** [comment]
Great. I updated the license field

**Pull request merged**
