### PR TITLE
[darknet] update to latest version

### PR DESCRIPTION
**Pull request by cenit**
as per title

### CODE REVIEW

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
@cenit 
Thanks for your PR.
Have you tested these features in this PR?

**Comment by cenit** [comment]
locally is fully tested and working, please confirm if possible

**Comment by NancyLi1013** [comment]
Seems good now, let's see the CI test results.

**Comment by cenit** [comment]
merged with master to keep monitored. Sorry for the noise

**Comment by cenit** [comment]
@strega-nil something went wrong in your rebase. 
vcpkg end2end tests are failing.

**Comment by strega-nil** [comment]
@cenit shoot, I screwed up; should be fixed Extremely Soon.

**Comment by NancyLi1013** [comment]
x64-linux failed like this:

```
CMake Error at scripts/cmake/vcpkg_minimum_required.cmake:43 (message): 
 Your vcpkg executable is from 2021-01-13 which is older than required by 
 the caller of vcpkg_minimum_required (2999-12-31). Please re-acquire vcpkg 
 by running bootstrap-vcpkg. 
Call Stack (most recent call first): 
 scripts/e2e_ports/overlays/vcpkg-requires-future-date/portfile.cmake:1 (vcpkg_minimum_required) 
 scripts/ports.cmake:128 (include) 
Error: Building package vcpkg-requires-future-date:x64-linux failed with: BUILD_FAILED 
Please ensure you're using the latest portfiles with `./vcpkg update`, then 
submit an issue at https://github.com/Microsoft/vcpkg/issues including: 
 Package: vcpkg-requires-future-date:x64-linux 
 Vcpkg version: 2021-01-13-unknownhash
```

**Comment by cenit** [comment]
@strega-nil another e2e test failed? @NancyLi1013 this is not a Darknet problem, build was fine before the double rebase/merge from master

**Comment by NancyLi1013** [comment]
The above failure seems expected. I have rerun this failed job.

**Comment by NancyLi1013** [comment]
LGTM now. Just rerun, the failure disappeared.

**Pull request merged**
