### PR TITLE
[basisu] Remove basis universal port

### PR DESCRIPTION
**Pull request by jherico**
The basis universal port relies on a fork of the upstream library that no longer exists.

- What does your PR fix? 

Build failure of basisu port

### CODE REVIEW

**Comment by Neumann-A** [comment]
switch to https://github.com/BinomialLLC/basis_universal instead of deleting?

**Comment by jherico** [comment]
@Neumann-A the port as is depends heavily on a CMake refactor of the original repository.  Simply switching over would require additional work.  I have been maintaining the fork and the vcpkg port for about a year now but the cmake refactor PR against the upstream repo is no closer to being merged.  If @richgel999 wants to maintain this he is free to do so.

**Comment by cenit** [comment]
as a historical note, here it is the original PR @jherico used in his fork, in case anyone wants to adopt the port.
Let me be clear: this is another reason we should not accept ports coming from forks done only to reduce patchset. We should use original repositories as much as possible, otherwise repositories can go away without any notice and *only for vcpkg*...

**Comment by PhoebeHui** [comment]
It affects 2 features for port magnum-plugins, @jherico, could you also remove the 2 features from magnum-plugins? 

They are added by PR https://github.com/microsoft/vcpkg/pull/8742, @Squareys, let us know if you have any concern about removing the 2 featues.

Feature: basisimageconverter
Description: BasisImageConverter plugin
Build-Depends: magnum[trade], basisu

Feature: basisimporter
Description: BasisImporter plugin
Build-Depends: magnum[trade], basisu

**Comment by jherico** [comment]
In order to avoid inconveniencing the Magnum developers, I've restored the repository and archived it instead of deleting it.

**Comment by cenit** [comment]
@jherico thanks

@PhoebeHui in parallel, do you think it would be better to rebase the port onto the original repository + patch-set?

**Comment by mosra** [comment]
@jherico oh, thanks for backtracking on this.

I'm planning to bundle Basis sources for Homebrew packages anyway, so I might do that for vcpkg as well then. It's sad to see upstream completely ignoring the proposed CMake improvements, but what can we do.

**Comment by PhoebeHui** [comment]
@cenit, it would be better to rebase the port onto the original repository + patch-set, however, if the patches contains huge changes, it will be hard to upgarde the port, since we need regenarte the patches each time, so I think it depends on how many files and changes it has.

@jherico, thanks for restoring the repository!

@mosra, we are looking forward to your PRs for basisu port!

**Comment by mosra** [comment]
@jherico @PhoebeHui once https://github.com/microsoft/vcpkg/pull/12211 gets merged, the `basisu` port can be removed.

**Pull request closed without merging**
