### PR TITLE
[proxygen, wangle, fizz, folly] Update and repair of facebook libraries.

### LINKED ISSUE #20805: [wangle, folly, fizz, proxygen] Update and repair of facebook libraries.
****

**Is your feature request related to a problem?**
Problems with the facebook repositories.

**Proposed solution**
Update facebook repositories (wangle, fizz, folly, proxygen) and repair windows compatibility (wangle, fizz, folly).

**Additional context**
Wangle cannot compile on windows. The solution is in a fork of mine.

### PR DESCRIPTION
**Pull request by cmachaca**
**Describe the pull request**

- #### What does your PR fix?  
  Update facebook repositories (wangle, fizz, folly, proxygen) and repair windows compatibility (wangle, fizz, folly). Issue #20805

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
   x64-linux, yes
   x64-windows, yes
   x64-windows-static, yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

### CODE REVIEW

**Review by NancyLi1013 — CHANGES_REQUESTED** [review]
Could you please also add double quotes for the paths in this PR? Please see https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/cmake-guidelines.md

**Comment by NancyLi1013** [comment]
Hi @cmachaca Thanks for your PR.

The failures on osx are like this:

For `fbthrift`
```
/Users/vagrant/Data/buildtrees/fbthrift/src/1.06.14.00-9a72f27f39.clean/thrift/lib/cpp/concurrency/ThreadManager.h:30:10: fatal error: 'folly/concurrency/QueueObserver.h' file not found
#include <folly/concurrency/QueueObserver.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
For `rsocket`

```
yarpl source dir: /Users/vagrant/Data/buildtrees/rsocket/src/3daa230e14-e3a6381b1c.clean/yarpl
CMake Error at /Users/vagrant/Data/work/1/s/scripts/buildsystems/vcpkg.cmake:578 (_add_library):
  Target "ReactiveSocket" links to target "unofficial-sodium::sodium" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:210 (add_library)


CMake Error at /Users/vagrant/Data/work/1/s/scripts/buildsystems/vcpkg.cmake:578 (_add_library):
  Target "yarpl" links to target "unofficial-sodium::sodium" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  yarpl/CMakeLists.txt:73 (add_library)
```
These problems also existed on Linux.

Please see the details here https://dev.azure.com/vcpkg/public/_build/results?buildId=61452&view=artifacts&pathAsName=false&type=publishedArtifacts

**Review by NancyLi1013 — COMMENTED** [review]
Would you like to make other paths in this PR quoted?

**Comment by NancyLi1013** [comment]
Hi @cmachaca 

Could you please resolve the conflicts?

**Comment by PhilippGrulich** [comment]
Hi, this is quite crucial for us? Can I somehow help?

**Comment by LilyWangLL** [comment]
Ping @cmachaca for response.

**Comment by JonLiu1993** [comment]
@cmachaca ,Is this PR being worked on? Can you please resolve the conflicts against master?

**Comment by LilyWangLL** [comment]
Closing this PR since it seems that no progress is being made. Please reopen if work is still being done.

**Pull request closed without merging**
