### PR TITLE
[ffmpeg] fix cross compilation on mac arm64 to x86_64

### PR DESCRIPTION
**Pull request by abique**
Fix cross compilation on mac arm64 to x86_64

### CODE REVIEW

**Comment by NancyLi1013** [comment]
Hi @abique 

Thanks for your PR.

Could you please post what problems you encountered here on mac?

**Comment by abique** [comment]
So when cross compiling on Mac Arm to Mac Intel, ffmpeg could not find libmp3lame because it was searching for the arm library instead of the intel one.

**Comment by NancyLi1013** [comment]
Thanks for your information. LGTM now.

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
Hi @abique 

Could you please rebase this PR to resolve the conflicts?

**Comment by abique** [comment]
> Hi @abique
> 
> Could you please rebase this PR to resolve the conflicts?

Done.

**Comment by abique** [comment]
@NancyLi1013 Hi, I'm not sure I understand what the error is on x86_windows?
Could it be a buildbot bug? Because the same check passed on other targets.

**Comment by NancyLi1013** [comment]
Since vcpkg adds a detection for versions only on x86-windows triplet. It will fail only on x86-windows if the versions are incorrect.

Could you please run `.\vcpkg x-add-version --overwrite-version ffmpeg` to solve the failures on x86-windows?
```
Error: While reading versions for port ffmpeg from file: C:\a\1\s\versions\f-\ffmpeg.json
       File declares version `4.4#8` with SHA: ffaeffcc2be0ca6109dd5186a4aa94e4e1de469a
       But local port with the same verion has a different SHA: 06fbaa1d12fc98ec42d278b2e1684a005f7042a2
       Please update the port's version fields and then run:

           vcpkg x-add-version ffmpeg

       to add a new version.
```

**Comment by abique** [comment]
Thank you :)

**Comment by NancyLi1013** [comment]
```
CMake Error at scripts/cmake/vcpkg_fixup_cmake_targets.cmake:95 (message):
  '/mnt/vcpkg-ci/packages/pistache_x64-linux/debug/lib/cmake/RapidJSON' does
  not exist.
Call Stack (most recent call first):
  ports/pistache/portfile.cmake:22 (vcpkg_fixup_cmake_targets)
  scripts/ports.cmake:140 (include)

```
The regressions caused by `pistache `will be fixed by https://github.com/microsoft/vcpkg/pull/18994.

**Comment by vicroms** [comment]
Please solve merge conflicts

**Comment by BillyONeal** [comment]
> Please solve merge conflicts

When the only conflict is the versions DB perhaps we should fix those?

**Pull request merged**
