### PR TITLE
Update VTK to version 8.0.

### LINKED ISSUE #1488: VTK build fails because it creates an unexpected bin directory.
VTK has always created a bin directory to store some additional tools that might be needed in particular cases (i.e. H5detect.exe, H5make_libsettings.exe, lproj.exe, vtkEncodeString*.exe, vtkHashSource*.exe, vtkParseOGLExt*.exe).
It seems that the bin folders to store these tools are created even though the tools themselves are not built.
The vcpkg build complains about these orphan bin folders and aborts the build:
```
vcpkg install vtk:x86-windows-static
The following packages will be built and installed:
    vtk:x86-windows-static
Building package vtk:x86-windows-static... 
-- Package x86-windows-static-dbg done
-- Performing post-build validation
There should be no bin\ directory in a static build, but D:\GitHub\vcpkg\packages\vtk_x86-windows-static\bin is present.
There should be no debug\bin\ directory in a static build, but D:\GitHub\vcpkg\packages\vtk_x86-windows-static\debug\bin is present.
If the creation of bin\ and/or debug\bin\ cannot be disabled, use this in the portfile to remove them

    if(VCPKG_LIBRARY_LINKAGE STREQUAL static)
        file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/bin ${CURRENT_PACKAGES_DIR}/debug/bin)
    endif()

There should be no empty directories in D:/GitHub/vcpkg/packages/vtk_x86-windows-static
The following empty directories were found: 

    D:/GitHub/vcpkg/packages/vtk_x86-windows-static/bin
    D:/GitHub/vcpkg/packages/vtk_x86-windows-static/debug/bin

If a directory should be populated but is not, this might indicate an error in the portfile.
If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:

    file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/a/dir ${CURRENT_PACKAGES_DIR}/some/other/dir)
```
So apparently, the portfile needs to be adjusted.

### PR DESCRIPTION
**Pull request by albertziegenhagel**
Version 8.0 introduces a CMake variable `VTK_EXTERNAL_HDF5_IS_SHARED` that should resolve the problems with respect to the shared HDF5 libraries without all the hacks we had implemented.

This port works for me with a x64-windows triplet.

Additionally I've applied some changes to fix #1488 but I was not able to test the static build since it is blocked by #1478.

I was not able to reproduce #1326 or #1129.

### CODE REVIEW

**Comment by albertziegenhagel** [comment]
@KindDragon, @UnaNancyOwen, @Fleischner could you test this port and report back whether this works for you or not?

**Comment by UnaNancyOwen** [comment]
It is necessary to disable the old workaround (disable-workaround-findhdf5.patch).
Please refer to this pull request (https://github.com/Microsoft/vcpkg/pull/1568) for the reason.

**Comment by UnaNancyOwen** [comment]
The some errors related to HDF5 occur in vtkNetCDF.
```
Error	C2632	'int' followed by 'int' is illegal (compiling source file C:\vcpkg\buildtrees\vtk\src\VTK-8.0.0\ThirdParty\netcdf\vtknetcdf\libsrc4\error4.c)		vtkNetCDF	c:\vcpkg\installed\x86-windows\include\H5public.h	165	
Error	C2632	'int' followed by 'int' is illegal (compiling source file C:\vcpkg\buildtrees\vtk\src\VTK-8.0.0\ThirdParty\netcdf\vtknetcdf\libsrc4\nc4dim.c)		vtkNetCDF	c:\vcpkg\installed\x86-windows\include\H5public.h	165	
Error	C2632	'int' followed by 'int' is illegal (compiling source file C:\vcpkg\buildtrees\vtk\src\VTK-8.0.0\ThirdParty\netcdf\vtknetcdf\libsrc4\nc4file.c)		vtkNetCDF	c:\vcpkg\installed\x86-windows\include\H5public.h	165	
Error	C2632	'int' followed by 'int' is illegal (compiling source file C:\vcpkg\buildtrees\vtk\src\VTK-8.0.0\ThirdParty\netcdf\vtknetcdf\libsrc4\nc4grp.c)		vtkNetCDF	c:\vcpkg\installed\x86-windows\include\H5public.h	165	
Error	C2632	'int' followed by 'int' is illegal (compiling source file C:\vcpkg\buildtrees\vtk\src\VTK-8.0.0\ThirdParty\netcdf\vtknetcdf\libsrc4\nc4attr.c)		vtkNetCDF	c:\vcpkg\installed\x86-windows\include\H5public.h	165	
Error	C2632	'int' followed by 'int' is illegal (compiling source file C:\vcpkg\buildtrees\vtk\src\VTK-8.0.0\ThirdParty\netcdf\vtknetcdf\libsrc4\nc4type.c)		vtkNetCDF	c:\vcpkg\installed\x86-windows\include\H5public.h	165	
Error	C2632	'int' followed by 'int' is illegal (compiling source file C:\vcpkg\buildtrees\vtk\src\VTK-8.0.0\ThirdParty\netcdf\vtknetcdf\libsrc4\nc4var.c)		vtkNetCDF	c:\vcpkg\installed\x86-windows\include\H5public.h	165	
Error	C2632	'int' followed by 'int' is illegal (compiling source file C:\vcpkg\buildtrees\vtk\src\VTK-8.0.0\ThirdParty\netcdf\vtknetcdf\libsrc4\ncfunc.c)		vtkNetCDF	c:\vcpkg\installed\x86-windows\include\H5public.h	165	
Error	C2632	'int' followed by 'int' is illegal (compiling source file C:\vcpkg\buildtrees\vtk\src\VTK-8.0.0\ThirdParty\netcdf\vtknetcdf\libsrc4\nc4internal.c)	vtkNetCDF	c:\vcpkg\installed\x86-windows\include\H5public.h	165	
Error	C2632	'int' followed by 'int' is illegal (compiling source file C:\vcpkg\buildtrees\vtk\src\VTK-8.0.0\ThirdParty\netcdf\vtknetcdf\libsrc4\nc4hdf.c)		vtkNetCDF	c:\vcpkg\installed\x86-windows\include\H5public.h	165	
```

**Comment by albertziegenhagel** [comment]
Strange that I do not get the same compiler errors on my machine.

Anyways I re-enabled the old patch. Could you try whether this fixes the issues for you?

**Comment by UnaNancyOwen** [comment]
Hmmm, The same error occurs.
I tried this pull request on the latest vcpkg.

**Comment by albertziegenhagel** [comment]
Okay, I think the problem that hit you here, was that `ssize_t` got redefined, which was handled by `dont-define-ssize_t.patch`. I still do not understand why it compiles on my machine without that fix (maybe you are using VS2015 and I use VS2017?!), but I just re-enabled that fix, so it should work for you.

Additionally I dug deeper into the problem with VTK mixing debug and release libraries. The cause for this is quite complicated and a mixture of how VTK writes it's exported targets and how vcpkg installs release and debug libraries into separate folders. Details can be taken from the comments in the portfile.

I think I finally added workarounds for all those issues. The only one left is glew32.lib which is linked in the debug build instead of glew32d.lib. But here it is always glew32.lib, and never glew32d.lib, so there shouldn't be any problems. I will open a separate issue for this, since I think other ports are affected by the same problem.

I would be glad, if you could try again, whether everything works for you now :)

**Comment by UnaNancyOwen** [comment]
You tried, It can build normally in my environment.
Thanks,

I found another problem when using <code>vcpkg integrate install</code>.
The <code>vcpkg integrate install</code> command makes it can use libraries that installed by vcpkg in all Visual C++ projects. It sets the include directories setting to <code>vcpkg\installed\x86-windows\include</code>.
Usually, Users write such as  <code>#include <vtk_headers.h></code>. But, In this case, Users need write such as <code>#include <vtk-8.0/vtk_headers.h></code> when include header files. It is not good.
I think that the VTK header files should be installed in the following directory structure.
```cmake
# vcpkg\installed\x86-windows\include\vtk-8.0\<vtk_headers.h>
vcpkg\installed\x86-windows\include\<vtk_headers.h>
```
Also, the VTK configuration files for CMake should be adjusted. (<code>VTK_INCLUDE_DIRS</code> should be shows <code>..\vcpkg\installed\x86-windows\include</code>.)

PCL port also had same problem. For details, Please read this comment https://github.com/Microsoft/vcpkg/pull/1283#issuecomment-321610342.
 Can you solve this problem in VTK port?

**Comment by albertziegenhagel** [comment]
Thanks for trying it out and the hint on `vcpkg integrate install`.

The headers should now be installed into the correct directory.

**Comment by albertziegenhagel** [comment]
@ras0219-msft , @alexkaratarakis I think this is ready to merged now.

**Comment by alexkaratarakis** [comment]
Thanks for the solid work! Hopefully this also fixes various bugs reported about the vtk port.

**Comment by albertziegenhagel** [comment]
@alexkaratarakis I think this should fix #1129, #1326, #1419 and #1488.

**Pull request merged**
