### PR TITLE
Improve Android doc (triplets, usage with cmake and prefab)

### LINKED ISSUE #5717: android support
Hi,
I don't understand if vcpkg is able to manage android and/or ios toolchain.
The issues have android references, but the documentation doesn't.
Thanks

### LINKED ISSUE #11052: Eliminate bad error reporting "Value was null"
****

**Is your feature request related to a problem? Please describe.**

vcpkg became valuable to me now that it started to support Android prefab (https://github.com/microsoft/vcpkg/pull/10271), so I started evaluating current ports. So far I cannot "export" AAR for **unknown** reason. And this seems to happen to **everywhere** in vcpkg tool itself has some bogus code that only avoids runtime crash.

It is not appropriate. We need at least information on why and/or where it crashed.

**Proposed solution**

- Give error details on each caller to `check_exit()`.
- Give error codes (either in MSBuild style or not).

**Additional context**

Here is an **example** reproducible steps I had (Ubuntu 19.10, Android SDK at standard location `~/Android/Sdk` with NDK):

- `./bootstrap-vcpkg.sh -disableMetrics`
- `export ANDROID_NDK_HOME=~/Android/Sdk/ndk/21.0.6113669`
- create `triplets/arm64-android.cmake` (below)
- `./vcpkg install jsoncpp:arm64-android`
- `./vcpkg export --triplet arm64-android jsoncpp  --prefab --prefab-maven` (as [docs/specifications/prefab.md](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/prefab.md) describes.)

File content for `triplets/arm64-android.cmake`:

```
set(VCPKG_TARGET_ARCHITECTURE arm64-v8a)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME Android)
```

The output from the last command:

```
The following packages are already built and will be exported:
    jsoncpp:arm64-android
Value was null
```

revision: 28ab0b1

### PR DESCRIPTION
**Pull request by pthom**
#### Describe your PR
Improve Android prefab and triplet doc

* Add a *very minimal* [example showcasing the use of vcpkg + cmake + android](https://github.com/pthom/vcpkg/tree/fix_prefab_doc/docs/examples/vcpkg_android_example_cmake) 
* Add [docs/users/android.md](https://github.com/pthom/vcpkg/blob/fix_prefab_doc/docs/users/android.md). This file provides:
    * A script to populate (and adjust) the android triplets
    * details about the matching "android abi" / "vcpkg triplet"
    * An example showcasing how to consume libraries using vpckg, cmake and the android toolchain

* Improve the [android prefab doc](https://github.com/pthom/vcpkg/blob/fix_prefab_doc/docs/specifications/prefab.md) 

* provides links to android.md inside docs/triplet.md

* provides link to android.md inside docs/index.md

#### What does your PR fix? 
This PR can may be considered as a fix for two issues that arise because of incomplete doc
  * Fix https://github.com/microsoft/vcpkg/issues/11052
  * Fix https://github.com/microsoft/vcpkg/issues/5717

#### Which triplets are supported/not supported? Have you updated the CI baseline?
Not applicable, this is doc only

#### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

### CODE REVIEW

**Comment by atkawa7** [comment]
@pthom @strega-nil looks good to me

**Comment by pthom** [comment]
@atkawa7 : if you have a few minutes, would you mind giving me some help on this pr: https://github.com/microsoft/vcpkg/pull/11269

My issue is that I now can built a prefab package, but I do not know how to consume it (and thus test it). As a newbie to android development, the [prefab doc](https://google.github.io/prefab/) was not that helpful for this.

**Comment by atkawa7** [comment]
@pthom I forgot another option which shows examples on how to consume it. Add this option `--prefab-debug` 

```cpp
./vcpkg export --triplet arm64-android jsoncpp --prefab --prefab-maven --prefab-debug
```

Output 

```
[DEBUG] Configuration properties in Android Studio
In app/build.gradle

	com.vcpkg.ndk.support:jsoncpp:1.9.2

And cmake flags

    externalNativeBuild {
                cmake {
                    arguments '-DANDROID_STL=c++_shared'
                    cppFlags "-std=c++17"
                }
            }

In gradle.properties

    android.enablePrefab=true
    android.enableParallelJsonGen=false
    android.prefabVersion=${prefab.version}
```

Note:  prefab packages are supported on Android Studio 4+ 

If you have Android 3.6 you might need to install android 4.1 Preview

**Comment by atkawa7** [comment]
@pthom checkout the following project that I created to consume the packages created 

https://github.com/atkawa7/prefab-vpkg-integration-sample

**Comment by pthom** [comment]
I made some changes, and added an example + android.md file.

@atkawa7  could you please have a look at
 https://github.com/pthom/vcpkg/blob/fix_prefab_doc/docs/users/android.md 
and 
https://github.com/pthom/vcpkg/blob/fix_prefab_doc/docs/specifications/prefab.md

**Comment by atkawa7** [comment]
@pthom looks good to me

**Comment by strega-nil** [comment]
Please poke me when you think the documentation is ready to merge; I don't know anything about android, and so I'm just going to trust your judgement :)

**Comment by atkawa7** [comment]
@strega-nil I think the documentation in its current form is good. I think @pthom addressed issues that new users might come across when consuming android archive packages.  I don't know if there is still anything to be added @pthom. I am sure as more issues related to android come up we will continue to improve the docs and address concerns users might have

**Comment by pthom** [comment]
I added a [second example](https://github.com/pthom/vcpkg/tree/fix_prefab_doc/docs/examples/vcpkg_android_example_cmake_script)

It provides a script [vcpkg_android.cmake](https://github.com/pthom/vcpkg/blob/fix_prefab_doc/docs/examples/vcpkg_android_example_cmake_script/cmake/vcpkg_android.cmake)

The usage is even simpler:

1. [Main CMakeList](https://github.com/pthom/vcpkg/blob/fix_prefab_doc/docs/examples/vcpkg_android_example_cmake_script/CMakeLists.txt), before calling `project()`
````cmake
if (VCPKG_TARGET_ANDROID)
    include("cmake/vcpkg_android.cmake")
endif()
````

2. cmake invocation:
````bash
cmake .. -DVCPKG_TARGET_ANDROID=ON -DANDROID_ABI=armeabi-v7a
````

I have successfuly tested on two vanillla installations of vcpkg under linux and MacOS.

@atkawa7 @strega-nil  : if this looks good to you, I think the PR is ok on my side too

**Comment by pthom** [comment]
The pipelines fails under osx.

The [azure log file](https://dev.azure.com/vcpkg/public/_build/results?buildId=36716&view=logs&jobId=7b75bd19-17d3-53d4-00fd-23f1a49a8ba4&j=7b75bd19-17d3-53d4-00fd-23f1a49a8ba4&t=6c1a7a3b-b385-5a17-556f-78ddf167924d) says
````
fatal: update_ref failed for ref 'HEAD': cannot lock ref 'HEAD': 
Unable to create '/Volumes/data/work/1/s/.git/HEAD.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
````

@strega-nil : I tried to retrigger the build but the issue persists. Could you look into it?

**Comment by strega-nil** [comment]
Alright, awesome! Thanks everyone, and @pthom especially. Y'all make this project so good!

**Pull request merged**
