### PR TITLE
[xaudio2redist] Code cleanup for port

### PR DESCRIPTION
**Pull request by walbourn**
* Updated portfile for modern best practices
* Fixed behavior with VCPKG_BUILD_TYPE set to "release"
* Added specific usage help
* Minor CMake cleanup

### CODE REVIEW

**Comment by walbourn** [comment]
Verified locally all supported triplets:

```
.\vcpkg install xaudio2redist:x86-windows
.\vcpkg install xaudio2redist:x86-windows-static-md

.\vcpkg install xaudio2redist:x64-windows
.\vcpkg install xaudio2redist:x64-windows-static-md

.\vcpkg install xaudio2redist:x64-mingw-static
.\vcpkg install xaudio2redist:x86-mingw-static
```

**Review by LilyWangLL — APPROVED** [review]

**Comment by LilyWangLL** [comment]
Usage test passed on `x64-windows`.

**Comment by walbourn** [comment]
@LilyWangLL  - @dg0yt noted in another review that I should not use per-config imports for things with the same DLL in all cases.

```
   add_library(Microsoft::XAudio2Redist SHARED IMPORTED)
   set_target_properties(Microsoft::XAudio2Redist PROPERTIES
      IMPORTED_LOCATION                    "${_xaudio2_root}/bin/xaudio2_9redist.dll"
      IMPORTED_IMPLIB                     "${_xaudio2_root_lib}"
      INTERFACE_INCLUDE_DIRECTORIES        "${_xaudio2_root}/include/xaudio2redist"
      IMPORTED_LINK_INTERFACE_LANGUAGES    "C")
```

**Comment by walbourn** [comment]
> @LilyWangLL - @dg0yt noted in another review that I should not use per-config imports for things with the same DLL in all cases.
> 
> ```
>    add_library(Microsoft::XAudio2Redist SHARED IMPORTED)
>    set_target_properties(Microsoft::XAudio2Redist PROPERTIES
>       IMPORTED_LOCATION                    "${_xaudio2_root}/bin/xaudio2_9redist.dll"
>       IMPORTED_IMPLIB                      "${_xaudio2_root_lib}"
>       INTERFACE_INCLUDE_DIRECTORIES        "${_xaudio2_root}/include/xaudio2redist"
>       IMPORTED_LINK_INTERFACE_LANGUAGES    "C")
> ```

Nevermind. The XAudio2Redist actually contains both a release and debug flavor of the DLL.

**Comment by BillyONeal** [comment]
Thanks :)

**Pull request merged**
