### PR TITLE
[nettle] Cleanup, fix cross-builds

### LINKED ISSUE #29893: Build failue
Package: nettle[core]:x64-osx -> 3.7.3

**Host Environment**

- Host: arm64-osx
- Compiler: AppleClang 14.0.0.14000029
-    vcpkg-tool version: 2999-12-31-unknownhash
    vcpkg-scripts version: 223d33be7 2023-02-24 (2 days ago)

**To Reproduce**

`vcpkg install `

**Failure logs**

```
-- Using cached nettle-nettle-52bacacaf4339fd78289f58919732f1f35bea1c1.tar.gz.
-- Cleaning sources at /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/nettle/src/1f35bea1c1-b3c5d0ac7b.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/downloads/nettle-nettle-52bacacaf4339fd78289f58919732f1f35bea1c1.tar.gz
-- Applying patch fix-InstallLibPath.patch
-- Applying patch flags.patch
-- Using source at /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/nettle/src/1f35bea1c1-b3c5d0ac7b.clean
-- Getting CMake variables for x64-osx-dbg
-- Getting CMake variables for x64-osx-rel
-- Generating configure for x64-osx
-- Finished generating configure for x64-osx
-- Configuring x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /bin/bash -c "V=1 ./../src/1f35bea1c1-b3c5d0ac7b.clean/configure --host=x86_64-apple-darwin \"--disable-documentation\" \"--disable-openssl\" \"--disable-shared\" \"--disable-silent-rules\" \"--verbose\" \"--disable-shared\" \"--enable-static\" \"--prefix=/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug\" \"--bindir=\\${prefix}/../tools/nettle/debug/bin\" \"--sbindir=\\${prefix}/../tools/nettle/debug/sbin\" \"--libdir=\\${prefix}/lib\" \"--includedir=\\${prefix}/../include\" \"--datarootdir=\\${prefix}/share/nettle\""
    Working Directory: /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/nettle/x64-osx-dbg
    Error code: 1
    See logs for more information:
      /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/nettle/config-x64-osx-dbg-config.log
      /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/nettle/config-x64-osx-dbg-out.log
      /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/nettle/config-x64-osx-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:812 (vcpkg_execute_required_process)
  ports/nettle/portfile.cmake:49 (vcpkg_configure_make)
  scripts/ports.cmake:147 (include)



```
<details><summary>/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/nettle/config-x64-osx-dbg-config.log</summary>

```
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by nettle configure 3.7.3, which was
generated by GNU Autoconf 2.71.  Invocation command line was

  $ ./../src/1f35bea1c1-b3c5d0ac7b.clean/configure --host=x86_64-apple-darwin --disable-documentation --disable-openssl --disable-shared --disable-silent-rules --verbose --disable-shared --enable-static --prefix=/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug '--bindir=${prefix}/../tools/nettle/debug/bin' '--sbindir=${prefix}/../tools/nettle/debug/sbin' '--libdir=${prefix}/lib' '--includedir=${prefix}/../include' '--datarootdir=${prefix}/share/nettle'

## --------- ##
## Platform. ##
## --------- ##

hostname = MacBook-Pro.local
uname -m = arm64
uname -r = 22.3.0
uname -s = Darwin
uname -v = Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000

/usr/bin/uname -p = arm
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = Mach kernel version:
	 Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
Kernel configured for up to 10 processors.
10 processors are physically available.
10 processors are logically available.
Processor type: arm64e (ARM64E)
Processors active: 0 1 2 3 4 5 6 7 8 9
Primary memory available: 32.00 gigabytes
Default processor set: 500 tasks, 3670 threads, 10 processors
Load average: 5.80, Mach factor: 4.39
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /Users/leanderSchulten/Library/pnpm/
PATH: /opt/homebrew/opt/bison/bin/
PATH: /Users/leanderSchulten/git_projekte/build-vcpkg-tool-No_QT-RelWithDebInfo/
PATH: /usr/local/opt/node@14/bin/
PATH: /Users/leanderSchulten/anaconda3/bin/
PATH: /opt/homebrew/bin/
PATH: /opt/homebrew/sbin/
PATH: /usr/local/bin/
PATH: /System/Cryptexes/App/usr/bin/
PATH: /usr/bin/
PATH: /bin/
PATH: /usr/sbin/
PATH: /sbin/
PATH: /Library/TeX/texbin/
PATH: /usr/local/share/dotnet/
PATH: /opt/X11/bin/
PATH: /Library/Apple/usr/bin/
PATH: /Library/Frameworks/Mono.framework/Versions/Current/Commands/
PATH: /Applications/Wireshark.app/Contents/MacOS/
PATH: /Users/leanderSchulten/Library/pnpm/
PATH: /opt/homebrew/opt/bison/bin/
PATH: /Users/leanderSchulten/git_projekte/build-vcpkg-tool-No_QT-RelWithDebInfo/
PATH: /usr/local/opt/node@14/bin/
PATH: /Users/leanderSchulten/anaconda3/bin/
PATH: /opt/homebrew/bin/
PATH: /opt/homebrew/sbin/
PATH: /Users/leanderSchulten/.cargo/bin/
PATH: /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/downloads/tools/ninja/1.10.2-osx/
PATH: /opt/homebrew/bin/


## ----------- ##
## Core tests. ##
## ----------- ##

configure:2963: looking for aux files: install-sh config.guess config.sub
configure:2976:  trying ./../src/1f35bea1c1-b3c5d0ac7b.clean/./
configure:2987:   ./../src/1f35bea1c1-b3c5d0ac7b.clean/./install-sh found
...
Skipped 436 lines
...

| {
|   // Test initializer lists
|   cxx11test::testinit il = { 4323, 435234.23544 };
| }
| {
|   // Test range-based for
|   int array[] = {9, 7, 13, 15, 4, 18, 12, 10, 5, 3,
|                  14, 19, 17, 8, 6, 20, 16, 2, 11, 1};
|   for (auto &x : array) { x += 23; }
| }
| {
|   // Test lambda expressions
|   using cxx11test::eval;
|   assert (eval ([](int x) { return x*2; }, 21) == 42);
|   double d = 2.0;
|   assert (eval ([&](double x) { return d += x; }, 3.0) == 5.0);
|   assert (d == 5.0);
|   assert (eval ([=](double x) mutable { return d += x; }, 4.0) == 9.0);
|   assert (d == 5.0);
| }
| {
|   // Test use of variadic templates
|   using cxx11test::sum;
|   auto a = sum(1);
|   auto b = sum(1, 2);
|   auto c = sum(1.0, 2.0, 3.0);
| }
| {
|   // Test constructor delegation
|   cxx11test::delegate d1;
|   cxx11test::delegate d2();
|   cxx11test::delegate d3(45);
| }
| {
|   // Test override and final
|   cxx11test::overridden o1(55464);
| }
| {
|   // Test nullptr
|   char *c = nullptr;
| }
| {
|   // Test template brackets
|   test_template<::test_template<int>> v(test_template<int>(12));
| }
| {
|   // Unicode literals
|   char const *utf8 = u8"UTF-8 string \u2500";
|   char16_t const *utf16 = u"UTF-8 string \u2500";
|   char32_t const *utf32 = U"UTF-32 string \u2500";
| }
| 
|   return ok;
| }
| 
configure:4837: result: none needed
configure:4920: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -c -fPIC -g -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk conftest.cpp >&5
configure:4920: $? = 0
configure:4943: checking if LD -Wl,--version-script works
configure:4961: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -fPIC -g -o conftest -fPIC -g -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -L/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -Wl,--version-script=conftest.map conftest.c  >&5
ld: unknown option: --version-script=conftest.map
clang: error: linker command failed with exit code 1 (use -v to see invocation)
configure:4961: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "nettle"
| #define PACKAGE_TARNAME "nettle"
| #define PACKAGE_VERSION "3.7.3"
| #define PACKAGE_STRING "nettle 3.7.3"
| #define PACKAGE_BUGREPORT "nettle-bugs@lists.lysator.liu.se"
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
| 
| int
| main (void)
| {
| 
|   ;
|   return 0;
| }
configure:4990: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -fPIC -g -o conftest -fPIC -g -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -L/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -Wl,--version-script=conftest.map conftest.c  >&5
ld: unknown option: --version-script=conftest.map
clang: error: linker command failed with exit code 1 (use -v to see invocation)
configure:4990: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "nettle"
| #define PACKAGE_TARNAME "nettle"
| #define PACKAGE_VERSION "3.7.3"
| #define PACKAGE_STRING "nettle 3.7.3"
| #define PACKAGE_BUGREPORT "nettle-bugs@lists.lysator.liu.se"
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
| 
| int
| main (void)
| {
| 
|   ;
|   return 0;
| }
configure:5003: result: no
configure:5014: checking whether make sets $(MAKE)
configure:5037: result: yes
configure:5049: checking for x86_64-apple-darwin-ranlib
configure:5081: result: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib
configure:5151: checking for x86_64-apple-darwin-nm
configure:5183: result: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/nm
configure:5254: checking for x86_64-apple-darwin-objdump
configure:5286: result: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump
configure:5356: checking for x86_64-apple-darwin-ar
configure:5388: result: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar
configure:5475: checking for a BSD-compatible install
configure:5548: result: /opt/homebrew/bin/ginstall -c
configure:5563: checking for a race-free mkdir -p
configure:5607: result: /opt/homebrew/bin/gmkdir -p
configure:5611: checking whether ln -s works
configure:5615: result: yes
configure:5626: checking build system compiler touch a.out | touch conftest | true -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -fPIC -g
configure:5639: touch a.out | touch conftest | true -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -fPIC -g conftest.c
configure:5642: $? = 0
./../src/1f35bea1c1-b3c5d0ac7b.clean/configure: line 5644: ./a.out: Permission denied
./../src/1f35bea1c1-b3c5d0ac7b.clean/configure: line 5644: ./b.out: No such file or directory
./../src/1f35bea1c1-b3c5d0ac7b.clean/configure: line 5644: ./a.exe: No such file or directory
./../src/1f35bea1c1-b3c5d0ac7b.clean/configure: line 5644: ./a_out.exe: No such file or directory
./../src/1f35bea1c1-b3c5d0ac7b.clean/configure: line 5644: ./conftest: Permission denied
configure:5649: result: no
configure:5654: error: Specified CC_FOR_BUILD doesn't seem to work

## ---------------- ##
## Cache variables. ##
## ---------------- ##

ac_cv_build=aarch64-apple-darwin22.3.0
ac_cv_c_compiler_gnu=yes
ac_cv_cxx_compiler_gnu=yes
ac_cv_env_CCC_set=
ac_cv_env_CCC_value=
ac_cv_env_CC_FOR_BUILD_set=set
ac_cv_env_CC_FOR_BUILD_value='touch a.out | touch conftest | true -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -fPIC -g'
ac_cv_env_CC_set=set
ac_cv_env_CC_value='/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -fPIC -g'
ac_cv_env_CFLAGS_set=set
ac_cv_env_CFLAGS_value='-fPIC -g'
ac_cv_env_CPPFLAGS_set=set
ac_cv_env_CPPFLAGS_value='-arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk'
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_CXXFLAGS_set=set
ac_cv_env_CXXFLAGS_value='-fPIC -g'
ac_cv_env_CXX_set=set
ac_cv_env_CXX_value=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
ac_cv_env_LDFLAGS_set=set
ac_cv_env_LDFLAGS_value='-L/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk'
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=set
ac_cv_env_host_alias_value=x86_64-apple-darwin
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_host=x86_64-apple-darwin
ac_cv_objext=o
ac_cv_path_install='/opt/homebrew/bin/ginstall -c'
ac_cv_path_mkdir=/opt/homebrew/bin/gmkdir
ac_cv_prog_AR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar
ac_cv_prog_CC='/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -fPIC -g'
ac_cv_prog_NM=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/nm
ac_cv_prog_OBJDUMP=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump
ac_cv_prog_RANLIB=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib
ac_cv_prog_cc_c11=
ac_cv_prog_cc_g=yes
ac_cv_prog_cc_stdc=
ac_cv_prog_cxx_11=no
ac_cv_prog_cxx_g=yes
ac_cv_prog_cxx_stdcxx=
ac_cv_prog_make_make_set=yes
nettle_cv_link_ifunc=no

## ----------------- ##
## Output variables. ##
## ----------------- ##

ALLOCA=''
AR='/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar'
ASM_ALIGN_LOG=''
ASM_COFF_STYLE=''
ASM_ELF_STYLE=''
ASM_MARK_NOEXEC_STACK=''
ASM_PPC_WANT_R_REGISTERS=''
ASM_RODATA=''
ASM_SYMBOL_PREFIX=''
ASM_TYPE_FUNCTION=''
ASM_TYPE_PROGBITS=''
ASM_WORDS_BIGENDIAN=''
ASM_X86_ENDBR=''
ASM_X86_MARK_CET=''
ASM_X86_MARK_CET_ALIGN=''
BENCH_LIBS=''
CC='/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -fPIC -g'
CCPIC=''
CC_FOR_BUILD='touch a.out | touch conftest | true -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -fPIC -g'
CFLAGS='-fPIC -g'
CPP=''
CPPFLAGS='-arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk'
CXX='/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++'
CXXFLAGS='-fPIC -g'
DEFS=''
DEP_FLAGS=''
DEP_PROCESS=''
ECHO_C='\c'
ECHO_N=''
ECHO_T=''
EGREP=''
EMULATOR=''
EXEEXT=''
EXEEXT_FOR_BUILD=''
EXTRA_HOGWEED_LINKER_FLAGS=''
EXTRA_LINKER_FLAGS=''
FAT_TEST_LIST=''
GMP_NUMB_BITS=''
GREP=''
HOGWEED_EXTRA_SYMBOLS=''
IF_ASM=''
IF_CXX=''
IF_DLL=''
IF_DLOPEN_TEST=''
IF_DOCUMENTATION=''
IF_HOGWEED=''
IF_MINI_GMP=''
IF_NOT_SHARED=''
IF_SHARED=''
IF_STATIC=''
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
LDFLAGS='-L/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk'
LIBHOGWEED_FILE=''
LIBHOGWEED_FILE_SRC=''
LIBHOGWEED_FORLINK=''
LIBHOGWEED_LIBS=''
LIBHOGWEED_LINK=''
LIBHOGWEED_MAJOR='6'
LIBHOGWEED_MINOR='4'
LIBHOGWEED_SONAME=''
LIBNETTLE_FILE=''
LIBNETTLE_FILE_SRC=''
LIBNETTLE_FORLINK=''
LIBNETTLE_LIBS=''
LIBNETTLE_LINK=''
LIBNETTLE_MAJOR='8'
LIBNETTLE_MINOR='4'
LIBNETTLE_SONAME=''
LIBOBJS=''
LIBS=''
LN_S='ln -s'
LTLIBOBJS=''
M4=''
MAJOR_VERSION='3'
MAKEINFO=''
MINOR_VERSION='7'
MKDIR_P='/opt/homebrew/bin/gmkdir -p'
NETTLE_USE_MINI_GMP='0'
NM='/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/nm'
NUMB_BITS=''
OBJDUMP='/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump'
OBJEXT='o'
OPENSSL_LIBFLAGS=''
OPT_HOGWEED_OBJS=''
OPT_NETTLE_OBJS=''
OPT_NETTLE_SOURCES=''
PACKAGE_BUGREPORT='nettle-bugs@lists.lysator.liu.se'
PACKAGE_NAME='nettle'
PACKAGE_STRING='nettle 3.7.3'
PACKAGE_TARNAME='nettle'
PACKAGE_URL=''
PACKAGE_VERSION='3.7.3'
PATH_SEPARATOR=':'
RANLIB='/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib'
SET_MAKE=''
SHELL='/bin/sh'
W64_ABI=''
ac_ct_CC=''
ac_ct_CXX=''
bindir='${prefix}/../tools/nettle/debug/bin'
build='aarch64-apple-darwin22.3.0'
build_alias=''
build_cpu='aarch64'
build_os='darwin22.3.0'
build_vendor='apple'
datadir='${datarootdir}'
datarootdir='${prefix}/share/nettle'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='NONE'
host='x86_64-apple-darwin'
host_alias='x86_64-apple-darwin'
host_cpu='x86_64'
host_os='darwin'
host_vendor='apple'
htmldir='${docdir}'
includedir='${prefix}/../include'
infodir='${datarootdir}/info'
libdir='${prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug'
program_transform_name='s,x,x,'
psdir='${docdir}'
runstatedir='${localstatedir}/run'
sbindir='${prefix}/../tools/nettle/debug/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target_alias=''

## ----------- ##
## confdefs.h. ##
## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "nettle"
#define PACKAGE_TARNAME "nettle"
#define PACKAGE_VERSION "3.7.3"
#define PACKAGE_STRING "nettle 3.7.3"
#define PACKAGE_BUGREPORT "nettle-bugs@lists.lysator.liu.se"
#define PACKAGE_URL ""

configure: exit 1
```
</details>
<details><summary>/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/nettle/config-x64-osx-dbg-out.log</summary>

```
checking build system type... aarch64-apple-darwin22.3.0
checking host system type... x86_64-apple-darwin
checking for -R flag... none
Searching for libraries
checking /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib... added
checking /usr/local/lib... added
checking /sw/local/lib... not found
checking /sw/lib... not found
checking /usr/gnu/lib... not found
checking /opt/gnu/lib... not found
checking /sw/gnu/lib... not found
checking /usr/freeware/lib... not found
checking /usr/pkg/lib... not found
checking for x86_64-apple-darwin-gcc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -fPIC -g
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -fPIC -g accepts -g... yes
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -fPIC -g option to enable C11 features... none needed
checking for ifunc support... no
checking whether the compiler supports GNU C++... yes
checking whether /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ accepts -g... yes
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ option to enable C++11 features... none needed
checking if LD -Wl,--version-script works... no
checking whether make sets $(MAKE)... yes
checking for x86_64-apple-darwin-ranlib... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib
checking for x86_64-apple-darwin-nm... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/nm
checking for x86_64-apple-darwin-objdump... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump
checking for x86_64-apple-darwin-ar... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar
checking for a BSD-compatible install... /opt/homebrew/bin/ginstall -c
checking for a race-free mkdir -p... /opt/homebrew/bin/gmkdir -p
checking whether ln -s works... yes
checking build system compiler touch a.out | touch conftest | true -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -fPIC -g... no
```
</details>
<details><summary>/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/nettle/config-x64-osx-dbg-err.log</summary>

```
configure: WARNING: unrecognized options: --disable-silent-rules
configure: error: Specified CC_FOR_BUILD doesn't seem to work
```
</details>

**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg-tool/main/docs/vcpkg.schema.json",
  "name": "lichtsteuerung",
  "version-string": "2.0.0",
  "dependencies": [
    {
      "name": "zeromq",
      "default-features": false,
      "features": [
        "websockets-sha1"
      ]
    }
  ],
  "vcpkg-configuration": {
    "overlay-ports": [
      "overlay-ports"
    ]
  }
}

```
</details>

### PR DESCRIPTION
**Pull request by dg0yt**
Fixes cross builds. Fixes https://github.com/microsoft/vcpkg/issues/29893.
Backported from unfinished port update. Generalizes parts of the former windows patches.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by dg0yt** [comment]
CC @autoantwort: This may fix #29893. (Tested arm64-osx build on x64-osx.)

**Comment by Neumann-A** [comment]
Hmm could you copy the code from `gmp` and make `nettle` also use `clang` instead of `yasm` ? (So that we can get rid of yasm)

**Comment by autoantwort** [comment]
> CC @autoantwort: This may fix #29893. (Tested arm64-osx build on x64-osx.)

Yeah it fixed https://github.com/microsoft/vcpkg/issues/29893 🚀

**Comment by dg0yt** [comment]
> Hmm could you copy the code from `gmp` and make `nettle` also use `clang` instead of `yasm` ? (So that we can get rid of yasm)

I do have preliminary work for this. But I will probably put in another PR. The full set of topics for nettle:
- cleanup and cross builds (this PR)
- switching away from yasm
- windows dll patching
- update to 3.8.x

**Review by FrankXie05 — APPROVED** [review]

**Pull request merged**
