### PR TITLE
[openmvg] update to 2.0

### LINKED ISSUE #21364: [openmvg] update to 2.0
Library name: openMVG

New version number: 2.0

See: https://github.com/openMVG/openMVG/releases/tag/v2.0

Also fixes the issue with Eigen3.4.0: https://github.com/microsoft/vcpkg/pull/20056

### PR DESCRIPTION
**Pull request by FrankXie05**
Fix #21364
[openmvg] update to the latest version 2.0
All features have been tested successfullly in the following triplet:

- x86-windows
- x64-windwos

It has been resolved in the latest version, so delete the message in portfile.cmake. Related PR #12229

### CODE REVIEW

**Comment by cenit** [comment]
what's the difference with #21509 ?

**Review by JonLiu1993 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the update!

**Comment by BillyONeal** [comment]
> what's the difference with #21509 ?

It looks like the problem you mentioned with the patches was fixed?

**Comment by FrankXie05** [comment]
@BillyONeal Yes, fix it. :)

**Comment by cenit** [comment]
even if the dependency on "vcpkg-provided" graphviz was not made explicit for tool feature, still leaving the message to install it from system...

**Pull request merged**
