### PR TITLE
[tinygltf] Enable usage variants

### PR DESCRIPTION
**Pull request by dg0yt**
- #### What does your PR fix?
  - Enable use with RapidJSON, with Draco or without stb.
    (osgearth wants to use it with RapidJSON. This shouldn't  enforce a dependency on nlohmann-json. OTOH osgearth uses a modified version which cannot be replaced easily.)
  - Update license information.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  unchanged, no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  yes

### CODE REVIEW

**Comment by Thomas1664** [comment]
Can all features be used together?

**Comment by Thomas1664** [comment]
Can all features be used together?

**Comment by dg0yt** [comment]
> Can all features be used together?

Used in the same unit: no. There is one definition which toggles the JSON library.

Installed at the same time: yes. It is just a header file. I only added checks to ensure that you can't use a transitive dependency without requesting the dependency (i.e. you cannot break an installed depending port, only remove it via the transitive port dependencies.)

**Comment by dg0yt** [comment]
@Adela0814 @Cheney-W This is waiting for two weeks now.

**Review by Adela0814 — APPROVED** [review]

**Review by ras0219-msft — CHANGES_REQUESTED** [review]
This (nlohmann-json vs rapidjson vs default json) violates our policy [Do not use features to implement alternatives](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-use-features-to-implement-alternatives); I see the following options to handle it:
1. Change the port to pin a specific json implementation (nlohmann-json). Embed the choice into the headers. `osgearth` will not be able to use the shared copy; its vendored copy will need to be patched to introduce namespaces that avoid abi conflicts while static linking.
2. Don't build an implementation library, don't depend on any of the json libraries, but keep `json-includes.patch`. Consumers will need to follow the full complex implementation details from https://github.com/syoyo/tinygltf, introducing their own dependency onto the json implementation library they want to use. I don't like this option because it pushes all the complexity onto consumers, but it doesn't violate the maintainer guidelines. It also almost certainly causes infinite pain once two consumers appear that want different choices.

Another option might be to work with upstream to introduce inline namespaces that separate the ABI-incompatible implementations so at least a program could link both of them. We could then look at something like installing the different versions into different subfolders.

Thanks for the PR and sorry for the troubles!

**Comment by dg0yt** [comment]
> 2\. Don't build an implementation library

This port doesn't build an implementation library.

~~~~
tinygltf:x64-windows:/include/tiny_gltf.h
tinygltf:x64-windows:/share/tinygltf/copyright
tinygltf:x64-windows:/share/tinygltf/vcpkg.spdx.json
tinygltf:x64-windows:/share/tinygltf/vcpkg_abi_info.txt
~~~~

**Comment by dg0yt** [comment]
@ras0219-msft Waiting for your response.

**Comment by dg0yt** [comment]
... not requires:author-response.

**Comment by dg0yt** [comment]
> don't depend on any of the json libraries, but keep json-includes.patch. Consumers will need to follow the full complex implementation details from https://github.com/syoyo/tinygltf, introducing their own dependency onto the json implementation library they want to use. 

Taking this as todo. This may need extra comments in the manifest.

**Comment by BillyONeal** [comment]
@ras0219 / @ras0219-msft

Based on these responses it looks like this thing is header only, and the injected `#cmakedefine`s are only checking that if you try to consume one of the backends that that matching backend is installed.

> > Can all features be used together?
> 
> Used in the same unit: no. There is one definition which toggles the JSON library.
> 
> Installed at the same time: yes. It is just a header file. I only added checks to ensure that you can't use a transitive dependency without requesting the dependency (i.e. you cannot break an installed depending port, only remove it via the transitive port dependencies.)

> > 2. Don't build an implementation library
> 
> This port doesn't build an implementation library.
> 
> ```
> tinygltf:x64-windows:/include/tiny_gltf.h
> tinygltf:x64-windows:/share/tinygltf/copyright
> tinygltf:x64-windows:/share/tinygltf/vcpkg.spdx.json
> tinygltf:x64-windows:/share/tinygltf/vcpkg_abi_info.txt
> ```

It's indeed a problem that 2 consumers of this in our tree that choose different values are going to be link-incompatible but I think this meets the letter, if not the spirt, of our guidelines.

**Comment by dg0yt** [comment]
Ping for directions.

**Comment by dg0yt** [comment]
Another ping.

**Comment by vicroms** [comment]
Bringing this to discussion on Thursday. This still has potential to cause a diamond conflict in the main catalog which suggests to me that we should go with Robert's first option of picking a "blessed" configuration and sticking with it.

**Comment by dg0yt** [comment]
IIUC:
| Before this PR | After this PR | 
|---------------------|-------------------|
| vcpkg nlohmann-json | vcpkg nlohmann-json (unchanged) |
| vendored RapidJSON | vcpkg rapidjson |
| draco by coincidence | draco feature/dep |
| stb by coincidence | stb feature/dep |

**Comment by BillyONeal** [comment]
OK @dg0yt you've convinced me at least that the problem we're concerned about is already present. (I'm pretty sure @vicroms was convinced too but don't want to put words in his mouth)

The only other thing I'd ask to consider is: is there any reason to not just pick one of the backends and say "it's that one too bad"?

**Comment by dg0yt** [comment]
> The only other thing I'd ask to consider is: is there any reason to not just pick one of the backends and say "it's that one too bad"?

User's choice of the backend might actually depend on what else is required in the user's project. I don't really see why it should be appropriate to implement restrictions via port tinygltf. 
IIRC this PR was triggered by an unsuccessfull attempt to devendor an embedded copy in another port. Any restriction will just mean more unsuccsessful attempts.

**Comment by BillyONeal** [comment]
> IIRC this PR was triggered by an unsuccessfull attempt to devendor an embedded copy in another port. Any restriction will just mean more unsuccsessful attempts.

The reason vendoring is bad is the same reason we are concerned about creating alternatives: that it results in `installed` trees that are impossible to safely link (and likely result in silent-bad-codegen at runtime).

**Comment by dg0yt** [comment]
If I didn't miss a symbol, all functions which depend on the JSON selection macros are either in anonymous namespace, or declared `static`. AFAIU this implies "internal linkage", i.e. these symbols should not escape out of single translation unit.
(There is a template function specialization which doesn't repeat the template function's `extern`, but it only exists for one JSON variant).

**Comment by dg0yt** [comment]
Ping

**Comment by dg0yt** [comment]
One more month.

**Comment by ras0219-msft** [comment]
> If I didn't miss a symbol, all functions which depend on the JSON selection macros are either in anonymous namespace, or declared static.

Looking at the header https://raw.githubusercontent.com/syoyo/tinygltf/6e8a858c4567340919238c21277481f88e14044c/tiny_gltf.h, I see the following chain of symbols:

```
::tinygltf::TinyGLTF::WriteGltfSceneToFile(); // inline, but with external linkage (class member)
calls
::tinygltf::SerializeGltfModel(); // inline with internal linkage (static inline)
calls
::tinygltf::{anonymous}::JsonReserveArray(); // not inline, internal linkage (anonymous namespace), depends on macro settings
```

This presents ODR violations if any two projects use the library with different macro settings.

**Comment by Adela0814** [comment]
Pinging @dg0yt  for response. Is work still being done for this PR?

**Comment by dg0yt** [comment]
@ras0219-msft pointed to a real blocker, and I cannot remove it at the moment.

OTOH I'm afraid that the ODR problem may exist independent of this PR, due to vendored copies which cannot be removed in other ports. Preventing the combination of features while building tinygltf might be a better indication of problems than finding out at runtime.

**Pull request closed without merging**
