### PR TITLE
[gdk-pixbuf] Add pkgconfig file 

### PR DESCRIPTION
**Pull request by kwiechen**
Add pkgconfig file

- What does your PR fix? Fixes missing .pc file of gdk-pixbuf

x86-windows, x64-windows, x64-linux-dynamic

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

### CODE REVIEW

**Comment by Neumann-A** [comment]
also included in #13100 and switched to meson

**Comment by JackBoosY** [comment]
Hmm... should we use this PR or #13100?

**Review by ytbigvinny27 — APPROVED** [review]

**Review by JackBoosY — APPROVED** [review]

**Comment by Neumann-A** [comment]
can be closed #13100 is merged

**Comment by JackBoosY** [comment]
@kwiechen Can I close this PR now?

**Comment by JackBoosY** [comment]
Close this issue since it was fixed.

**Pull request closed without merging**
