### PR TITLE
Fix crosscompiling for x86_64 on ARM64 macOS

### PR DESCRIPTION
**Pull request by orudge**
The x64-osx triplet does not explicitly specify the x86_64 architecture in the OSX_ARCHITECTURES variable. This means that CMake-based projects can in some cases incorrectly produce arm64 binaries instead of x86_64, if building on an arm64 platform.

I found an update of CMake was also necessary to incorporate some Apple Silicon-related fixes in order to build the ports I was having trouble with (libpng primarily, though there are additional issues with libpng that I will submit in a separate pull request).

### CODE REVIEW

**Comment by orudge** [comment]
It looks like there's a separate PR (https://github.com/microsoft/vcpkg/pull/14716) for updating CMake (which looks to be the cause of some of the build failures/regressions), so I'll remove that commit from my branch and just include the triplet change here.

**Comment by JackBoosY** [comment]
I think for arm64, we need a new triplet instead of modifying it. @strega-nil Am I right?

**Comment by orudge** [comment]
> I think for arm64, we need a new triplet instead of modifying it. @strega-nil Am I right?

Apologies if I’m misunderstanding - there’s already an arm64-osx community triplet which in most cases works fine. This PR is for fixing compilation of x86_64 on an arm64 host, which in some cases may incorrectly produce arm64 binaries due to the macOS arch not being specified in the triplet.

**Comment by strega-nil** [comment]
This is a good change.

**Review by strega-nil — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
