### PR TITLE
fix Glew:x64-windows install failure #11.

### PR DESCRIPTION
**Pull request by sdcb**
related to my PR: https://github.com/Microsoft/vcpkg/pull/63 (closed by me)
/ports/glew/portfile.cmake is hard code to "Win32", I defined the BUILD_ARCH to fix this.

### CODE REVIEW

**Comment by Ninetainedo** [comment]
Will that work with ARM as well ?

**Comment by sdcb** [comment]
Yes, and no.
ARM BUILD_ARCH is same as TRIPLET_SYSTEM_ARCH, so it won't block arm-uwp.
But glew_shared14.vcxproj does not have a ARM configuration, so it cannot compile, should we create another issue for ARM (for different cause)?

**Comment by Ninetainedo** [comment]
I think there should at least be an explicit error message displayed.
Actually, it fails but there is no information saying why it failed. Even the log files are empty.

**Comment by sdcb** [comment]
Added a cmake FATAL_ERROR message "ARM is currently not supported.", is that acceptable?

**Comment by ras0219-msft** [comment]
Looks great to me, nice job!

**Pull request merged**
