### PR TITLE
[pybind11] Remove the debug link patch since the exported target `pybind11::pybind11` already supports this

### PR DESCRIPTION
**Pull request by yurybura**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [x] The "supports" clause reflects platforms that may be fixed by this new version.
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by Osyotr** [comment]
> ... since the exported target pybind11::pybibd11 already supports this

How so?
Note that justification for keeping `Py_DEBUG` is explained here #35169

**Comment by yurybura** [comment]
> > ... since the exported target pybind11::pybibd11 already supports this
> 
> How so? Note that justification for keeping `Py_DEBUG` is explained here #35169

There is no need to force `Py_DEBUG` since this definition is added [here](https://github.com/pybind/pybind11/blob/768cebe17e65c2a0a64ed067510729efc3c7ff6c/tools/pybind11NewTools.cmake#L172-L177).

**Comment by Neumann-A** [comment]
and where does `PYTHON_IS_DEBUG` get set (especially in the context of vcpkg)?

**Comment by yurybura** [comment]
> and where does `PYTHON_IS_DEBUG` get set (especially in the context of vcpkg)?

This variable will be defined if a debug version of Python is detected [here](https://github.com/pybind/pybind11/blob/768cebe17e65c2a0a64ed067510729efc3c7ff6c/tools/pybind11NewTools.cmake#L124-L133).

More information:
https://docs.python.org/3.6/c-api/intro.html#debugging-builds
https://stackoverflow.com/questions/39161202/how-to-work-around-missing-pymodule-create2-in-amd64-win-python35-d-lib

**Comment by Neumann-A** [comment]
> This variable will be defined if a debug version of Python is detected [here](https://github.com/pybind/pybind11/blob/768cebe17e65c2a0a64ed067510729efc3c7ff6c/tools/pybind11NewTools.cmake#L124-L133).

That detection is invalid for vcpkg.... pybind really needs to depend on the python3 port again..... The meaning of debug is bound to vcpkg not to some external program.

**Comment by yurybura** [comment]
> > This variable will be defined if a debug version of Python is detected [here](https://github.com/pybind/pybind11/blob/768cebe17e65c2a0a64ed067510729efc3c7ff6c/tools/pybind11NewTools.cmake#L124-L133).
> 
> That detection is invalid for vcpkg.... pybind really needs to depend on the python3 port again..... The meaning of debug is bound to vcpkg not to some external program.

What is invalid? I think, the Py_DEBUG should be defined as part of the python3 exported target, not in pybind11.

**Comment by Neumann-A** [comment]
> What is invalid? I think, the Py_DEBUG should be defined as part of the python3 exported target, not in pybind11.

The point that the python executables decides this and not the python library. As such you are currently mixing debug/release probably for debugging reasons. Using system python build as release with whatever you use pybind for build as debug. Maybe vcpkg needs to allow for a debug version of the python3 binary to make this more clear for users.
Furthermore there is no python3 exported target since python3 does not use cmake for building.

**Comment by Osyotr** [comment]
> This variable will be defined if a debug version of Python is detected [here](https://github.com/pybind/pybind11/blob/768cebe17e65c2a0a64ed067510729efc3c7ff6c/tools/pybind11NewTools.cmake#L124-L133).

The check will always find release library because it uses python interpreter and vcpkg currently does not build debug interpreter.

**Comment by yurybura** [comment]
> > What is invalid? I think, the Py_DEBUG should be defined as part of the python3 exported target, not in pybind11.
> 
> The point that the python executables decides this and not the python library. As such you are currently mixing debug/release probably for debugging reasons. Using system python build as release with whatever you use pybind for build as debug. Maybe vcpkg needs to allow for a debug version of the python3 binary to make this more clear for users. Furthermore there is no python3 exported target since python3 does not use cmake for building.

CMake's built-in finder exports targets for Python, and vcpkg modifies them inside the file ports/python3/vcpkg-cmake-wrapper.cmake.

I belive that this is the correct place to force Py_DEBUG definition.

**Comment by yurybura** [comment]
> > This variable will be defined if a debug version of Python is detected [here](https://github.com/pybind/pybind11/blob/768cebe17e65c2a0a64ed067510729efc3c7ff6c/tools/pybind11NewTools.cmake#L124-L133).
> 
> The check will always find release library because it uses python interpreter and vcpkg currently does not build debug interpreter.

This means that vcpkg has two instances of the Python3 library. This is the root cause of the problem. Pybind11 cannot solve this.

**Comment by Neumann-A** [comment]
> This means that vcpkg has two instances of the Python3 library. 

Of course it has two. One in `lib` and one in `debug/lib`. It just doesn't have a debug interpreter. 
I don't mind if the patch is made conditional on `VCPKG_BUILD_TYPE` but the patch has to stay for combined release/debug builds.

**Comment by yurybura** [comment]
> > This means that vcpkg has two instances of the Python3 library.
> 
> Of course it has two. One in `lib` and one in `debug/lib`. It just doesn't have a debug interpreter. I don't mind if the patch is made conditional on `VCPKG_BUILD_TYPE` but the patch has to stay for combined release/debug builds.

In these case, vcpkg has 3 instances. Third instance is located in the same folder with the python.exe on Windows.

**Review by FrankXie05 — DISMISSED** [review]

**Comment by FrankXie05** [comment]
Add `reviewed` tag for further review.

**Comment by BillyONeal** [comment]
> In this case, vcpkg has 3 instances. The third instance is located in the same folder with the python.exe on Windows.

It is true that in a vcpkg context, there are at least 2 pythons. We do not want to require building python from source to run a .py script when `/usr/bin/python3` is available and works perfectly fine for that.

@yurybura How can it be validated that the right thing *actually* happens here rather than guessing? Customers getting pybind11 from vcpkg with `CMAKE_BUILD_TYPE` == `Debug` should be getting `Py_Debug`.

**Comment by yurybura** [comment]
> It is true that in a vcpkg context, there are at least 2 pythons. We do not want to require building python from source to run a .py script when `/usr/bin/python3` is available and works perfectly fine for that.

@BillyONeal  VCPKG should not require Python to be built from source to create custom Python bindings. It is better to allow linking with the default system Python or a custom version of Python. For example, my library requires Python 3.10, which is not included in VCPKG right now, I would like to use Python downloaded from the official web site. On the other hand, building Python from source is a big challenge due to many dependencies like openssl. Making an overlay for custom Python version in VCPKG also is a big challenge..

> @yurybura How can it be validated that the right thing _actually_ happens here rather than guessing? Customers getting pybind11 from vcpkg with `CMAKE_BUILD_TYPE` == `Debug` should be getting `Py_Debug`.

I think the correct place to add Py_Debug is the following file: https://github.com/microsoft/vcpkg/blob/master/ports/python3/vcpkg-cmake-wrapper.cmake.
Pybind11 should not explicitly define this build flag.

**Comment by Neumann-A** [comment]
Making an empty overlay fo system python is not really a challenge. Thee is also a blog post about this somewhere.

So the TL;DR of the discussion here is that pybind should depend on python3 and every other view on this matter requires an overlay.

**Comment by yurybura** [comment]
> Making an empty overlay fo system python is not really a challenge. Thee is also a blog post about this somewhere.
Creating empty ports is a workaround due to VCPKG limitations.

> So the TL;DR of the discussion here is that pybind should depend on python3 and every other view on this matter requires an overlay.
I absolutely disagree that Pybing11 should depend on the Python3 built from the source. Only the user library should depend on the CMake target `Python3::Module`. There should be an easy way for the user to provide their own Python from the official site without creating empty overlays or other dubious workarounds.

**Comment by Neumann-A** [comment]
> Creating empty ports is a workaround due to VCPKG limitations.

Then come up with a way to tell vcpkg-tool that something is system provided.... Probably something like`"system": true` field in the manifest (loading a `portfile.system.cmake` or having a variable like `SYSTEM_PORT` being set?) which can be overriden via a cli flag (`--no-system-ports`) ? Then wait and get it reviewed and merged.

> without creating empty overlays or other dubious workarounds.

It is not a dubious workaround it is currently the blessed vcpkg approach to the problem. If you require headers or link against python your are obligated to get it from vcpkg unless you specifically said no via an empty overlay. You are just angry that your workflow requires an extra step and cannot be the default in the main registry (currently). 

Case closed from my point of view. 

Who makes the PR to re-add python3 as a pybind dependency (already ran into problems due to that missing dep)?

**Comment by yurybura** [comment]
> It is not a dubious workaround it is currently the blessed vcpkg approach to the problem. If you require headers or link against python your are obligated to get it from vcpkg unless you specifically said no via an empty overlay. You are just angry that your workflow requires an extra step and cannot be the default in the main registry (currently).
> 
> Case closed from my point of view.

I disagree. For instance, I want to use system Python with my library right now. I can simply avoid to use the VCPKG port for Python3 which built from source code. Why are you prohibiting this? Instead of flexibility your suggest to just force building Python from sources... Or.. Alternative is making overlays: empty Python3 overlay (?) and/or Pybind11 overlay with avoiding dependency to Python3 and removing explicitly defined `Py_Debug`, because system Python usually don't have debug library...

If VCPKG port `python3` requires define `Py_Debug` then please modify exported target for `python3` port (VCPKG has this possibility in file python3/vcpkg-cmake-wrapper.cmake). Let's allow to use `pybind11` independently. Why `pybind11` is responsible for the build options used during the `python3` port build?

> Who makes the PR to re-add python3 as a pybind dependency (already ran into problems due to that missing dep)?

Did you see `usage` file for the Pybind11 library? I think this file contains all instructions. Why following these instructions is a problem?

**Comment by Neumann-A** [comment]
> Did you see usage file for the Pybind11 library?

Yes. And I also see this in pybind11:

```
if(TARGET ${_Python}::Python)
  set_property(
    TARGET pybind11::embed
    APPEND
    PROPERTY INTERFACE_LINK_LIBRARIES ${_Python}::Python)
endif()

# CMake 3.15+ has this
if(TARGET ${_Python}::Module)
  set_property(
    TARGET pybind11::module
    APPEND
    PROPERTY INTERFACE_LINK_LIBRARIES ${_Python}::Module)
else()
  set_property(
    TARGET pybind11::module
    APPEND
    PROPERTY INTERFACE_LINK_LIBRARIES pybind11::python_link_helper)
endif()
```

So if `pybind11` would actually have a correct `find_package(pybind11)` it would internally call `find_dependency(Python)` (instead of externally requiring it) since it wants to link targets from it. As such `python3` is a direct dependency of `pybind11`.

**Comment by yurybura** [comment]
> So if `pybind11` would actually have a correct `find_package(pybind11)` it would internally call `find_dependency(Python)` (instead of externally requiring it) since it wants to link targets from it. As such `python3` is a direct dependency of `pybind11`.

I don't see any contradictions. Python is not needed during the Pybind11 build and installation. Only the target user library depends on both Python and Pybind11 even if the `find_package(Python)` is called explicitly from the Pybind11 helper functions.

**Comment by Osyotr** [comment]
> I disagree. For instance, I want to use system Python with my library right now. I can simply avoid to use the VCPKG port for Python3 which built from source code. Why are you prohibiting this?

Vcpkg can't guarantee that if you install `pybind11@2.11.1#0` it will use system python. Another package that has dependency on python will break your assumptions. `pybind11` must depend on `python3` and you must use empty overlay for `python3`.

**Comment by yurybura** [comment]
> Another package that has dependency on python will break your assumptions. 

Which package do you mean? I've suggest solution which will not break any package. 
If your package want to use VCPKG Python built from source the `vcpkg.json` may be like this:
```json
{
  "name": "mylib",
  "version": "1.0.0",
  "dependencies": [
    "python3",
    "pybind11"
  ]
}
```

If your package DON'T want to use VCPKG Python built from source define `vcpkg.json`:
```json
{
  "name": "mylib",
  "version": "1.0.0",
  "dependencies": [
    "pybind11"
  ]
}
```
Your `CMakeLists.txt` file will be unchanged in both cases:

```cmake
cmake_minimum_required(VERSION 3.18)
project(mylib LANGUAGES CXX)

find_package(Python3 COMPONENTS Interpreter Development REQUIRED)
find_package(pybind11 CONFIG REQUIRED)

pybind11_add_module(mylib example.cpp)
```

> `pybind11` must depend on `python3` and you must use empty overlay for `python3`.

See [documentation](https://pybind11.readthedocs.io/en/stable/compiling.html#findpython-mode). `pybind11` allows users to override Python. You are simply prohibiting this possibility.

**Comment by BillyONeal** [comment]
>I disagree. For instance, I want to use system Python with my library right now. I can simply avoid to use the VCPKG port for Python3 which built from source code. Why are you prohibiting this?

Because it breaks the ordering rule.

```
vcpkg install python3
vcpkg install pybind11
```

needs to produce the same result as

```
vcpkg install pybind11
vcpkg install python3
```

; package installation order is not a configuration mechanism. Among other things, order is not contractually enforced anywhere in vcpkg.

**Comment by Neumann-A** [comment]
To make the example more explicit:  

```
python3
pybind11
port using pybind11 <---will use vcpkg python
(project invoking vcpkg) <---- will use vcpkg python
```

```
pybind11
port using pybind11 <---will use system python
python3
(project invoking vcpkg) <---- will use vcpkg python
```

That is an inconsistency which should not happen. So the `python3` dependency is needed.

**Comment by miyanyan** [comment]
> So if `pybind11` would actually have a correct `find_package(pybind11)` it would internally call `find_dependency(Python)` (instead of externally requiring it) since it wants to link targets from it. As such `python3` is a direct dependency of `pybind11`.

In my project I will explicit set the exact python version:
```
find_package(Python3 EXACT 3.8 COMPONENTS Interpreter Development REQUIRED)
find_package(pybind11 REQUIRED)
target_link_libraries(xxx PRIVATE pybind11::embed)
```

so I can just use the system python38 to build a pyd or just call python in cpp with the py38 embed. For me, pybind11 is just a lightweight header-only library and ```xxx install pybind11``` only need to download it.

**Comment by miyanyan** [comment]
> How so? Note that justification for keeping `Py_DEBUG` is explained here #35169

btw, after https://github.com/microsoft/vcpkg/pull/31318, ```vcpkg install pybind11``` is not worked in my project, I had to download and copy pybind11 to my 3rdparty forder manually, because I don't have python debug version in my system and I dont' want to link ```python**_d.lib```...

**Comment by yurybura** [comment]
> Because it breaks the ordering rule.

@BillyONeal Thanks for pointing this out. My example breaks the ordering rules (not a port of pybind11). I can fix this:

```cmake
cmake_minimum_required(VERSION 3.18)
project(mylib LANGUAGES CXX)

set(Python3_ROOT_DIR "usr/python")
find_package(Python3 COMPONENTS Interpreter Development REQUIRED)
find_package(pybind11 CONFIG REQUIRED)

pybind11_add_module(mylib example.cpp)
```

In mylib I don't want to build Python3 from source. Building Python3 from source requires a lot of additional dependencies. But as @miyanyan said, the pybind11 port also needs to be patched. The mylib project requires a Python interpreter in addition. I have to make a lot of tricks to provide Python interpreter from one path and use Python lib from VCPKG...

@BillyONeal, could you please answer the following question:

> If VCPKG port `python3` requires define `Py_Debug` then please modify exported target for `python3` port (VCPKG has this possibility in file python3/vcpkg-cmake-wrapper.cmake). Let's allow to use `pybind11` independently. Why `pybind11` is responsible for the build options used during the `python3` port build?

The Nanobind port has the same problem. I need to wait for Python3 to be built from source.

**Comment by Neumann-A** [comment]
> The mylib project requires a Python interpreter in addition. 

For cross-compiling purposes you need to separate the interpreter usage from `find_package(Python)` any way.

**Comment by BillyONeal** [comment]
> Is there any way to explicitly choose system or vcpkg python?

In general, anything vcpkg builds that loads into python is expected to be only used with the python made by the port named python.

If you want to do things to the system python, the expected outcome is to overlay the port named python with an empty one.

The only use of the system's python (`vcpkg_find_acquire_program(PYTHON3)`) should be for 'I'm running this python build script which does not need any other plugins or similar that come from vcpkg'.

See Daniel's blog post https://devblogs.microsoft.com/cppblog/using-system-package-manager-dependencies-with-vcpkg/

**Comment by BillyONeal** [comment]
> But if I want to use vcpkg for a project that builds a Python native module (like bindings), which is the use case for pybind11, shouldn't I be using the system Python, to make sure I have the correct ABI? I don't want to ship my own Python interpreter built for the module.

You need an overlay.

> Does this work in manifest mode?

Yes

**Comment by Osyotr** [comment]
@BillyONeal hmm without these changes people wouldn't be able to use system python even with empty overlay.
So we need both this PR and #37758 and also add `Py_DEBUG` to `INTERFACE_COMPILE_DEFINITIONS` in python3.

**Comment by BillyONeal** [comment]
@JavierMatosD @ras0219-msft @data-queue and I discussed this in person today.

> @BillyONeal, could you please answer the following question:
> 
> > If VCPKG port `python3` requires define `Py_Debug` then please modify exported target for `python3` port (VCPKG has this possibility in file python3/vcpkg-cmake-wrapper.cmake). Let's allow to use `pybind11` independently. Why `pybind11` is responsible for the build options used during the `python3` port build?

It seems to make sense to us that both https://github.com/microsoft/vcpkg/pull/37758 *and* this PR are correct, and that Py_DEBUG should come from the python3 port.

@ras0219-msft points out that if the empty-port-overlay mechanism creates *problems* that we are on the hook to fix those problems.

> The Nanobind port has the same problem. I need to wait for Python3 to be built from source.

Yes, many ports have this problem.

@data-queue points out that vcpkg's default behavior is likely to not be what many Python customers want, as wanting to build extensions to load into the system python, or into a venv, are common scenarios. 

@BillyONeal points out that the point is not to say 'the python is this one', the point is that the installed tree needs to agree on what the Python selected is, and today the mechanism to do that overlays, even if that sucks. Alternatives getting over the cut line would be very nice :/

@ras0219-msft points out that we would be very happy to work with @yurybura to write a document on learn.microsoft.com/vcpkg describing these particular python edge cases and scenarios to make the scenario he wants as easy as possible for other folks.

A point we as a team want to stress is that we care about @yurybura 's scenario, and we *want* to make that good. However, we are forced to maintain integrity of the mechanisms by which ports link with each other, and competing versions of python in the same link are problematic. Features which will enable vcpkg to make selections like this easier (e.g. 'alternatives') are on our backlog and we will make sure this scenario is made better when we get to those.


(I underscore this because alternatives have sometimes become the thing that will fix X for all X, but replacing dependencies from our registry with system ones is a very common reason people look for alternative selections so it's absolutely going to be a priority to make good)

**Comment by BillyONeal** [comment]
To clarify: I think we are happy with this if it moves the definition to the Python3 port but not to just remove it like this.

**Comment by BillyONeal** [comment]
Actually I realize now that it looks like @Osyotr did that in https://github.com/microsoft/vcpkg/pull/37758 . @yurybura can you confirm that resolves your concern?

**Pull request closed without merging**
