### PR TITLE
[qt5] use configure_file to install qt_debug.conf and qt_release.conf

### PR DESCRIPTION
**Pull request by huangqinjin**
see previous discussion #2857 .

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for the PR and sorry for taking so long to get to it!

For my understanding: the objective here is to get the current installed path hardcoded into the `qt_debug.conf` and `qt_release.conf` files so that you can use them directly in your own project?

(Assuming the above) have you considered doing what we do internally: running our _own_ `configure_file()` call on those files to generate a `qt.conf` on the fly. You would need to do something like:
```
set(CURRENT_INSTALLED_DIR /path/to/vcpkg/installed/x64-windows)
configure_file(${CURRENT_INSTALLED_DIR}/tools/qt5/qt_release.conf /wherever/you/want/qt.conf)
```

The problem with hardcoding the local machine path is that it obviously makes the package unrelocatable; even renaming the vcpkg folder on your own machine would break things.

**Comment by huangqinjin** [comment]
I don't think that anyone want to change the vcpkg location, so hardcoding isn't really a problem. Without hardcoding, I need to construct the `CURRENT_INSTALLED_DIR` variable in *every my own* projects, but the value never changed in my local machine. Would you mind give me an example that I need to relocate the qt package?

**Comment by ras0219-msft** [comment]
https://github.com/Microsoft/vcpkg/blob/master/docs/specifications/export-command.md is a command supported by vcpkg that enables users to reuse binaries across multiple machines; we've seen a lot of users who are quite happy with this mechanism, so we do need each package to be relocatable :)

Yes, you will need to construct the `CURRENT_INSTALLED_DIR` in your project, but don't you have to construct that anyway to find the `qt_release.conf`? Alternatively, if you know the location of `qt_release.conf`, you can use
```cmake
get_filename_component(CURRENT_INSTALLED_DIR "${QT_RELEASE}" DIRECTORY)
get_filename_component(CURRENT_INSTALLED_DIR "${CURRENT_INSTALLED_DIR}" DIRECTORY)
get_filename_component(CURRENT_INSTALLED_DIR "${CURRENT_INSTALLED_DIR}" DIRECTORY)
```
to compute the current installed location based on the path to `qt_release.conf`.

[1] https://cmake.org/cmake/help/latest/command/get_filename_component.html

**Comment by glachancecmaisonneuve** [comment]
@ras0219-msft I agree with everything you have written but the use-case where you use an exported tree but where a user is still using cmake (to create a qt.conf) seems to me unrealistic.

Lets say I want to build qBittorrent with an exported build tree.  I will 
```
vcpkg install qt5-base libtorrent boost-system
vcpkg export qt5-base libtorrent boost-system --raw
```

And then that's it, **i'm done with cmake**.  If a had more cmake work to do, I'd do it in a personal vcpkg tree.  Now it's time for qmake to do it's thing .... and I would like it to be able to find it's libraries.  I can't find a qt distribution out there that does not add a qt.conf file in it's bin folder, wherever it is.  Qt's own redist package has one, so does conda, so does arch, so does whoever builds the ubuntu package.

Thankfully there is an easy solution to this problem.  It 
- [x] Works with exported trees
- [x] Works for linux
- [x] Works for OSX
- [x] Works for windows

The solution is to create a qt.conf file everywhere we put a qt executable in.  It should use relative paths to point to where to find it's different bits.

something along those lines (*Needs further testing*):
```ini
[Paths]
Prefix = ../..
Documentation = share/qt5/doc
Headers = include
Libraries = lib
Binaries = tools/qt5
LibraryExecutables = tools/qt5
Plugins = plugins
Qml2Imports = qml
Data = share/qt5
ArchData = share/qt5
HostData = share/qt5
HostBinaries = tools/qt5-tools
HostLibraries = lib
Translations = share/qt5/translations
```

Seperatly, we should also offer a qt_debug.conf that, when used with qmake -conf <filename.conf> option, has it finding/binding to it's debug libs.

**Comment by mingwandroid** [comment]
You seem unaware that qt.conf doesn't work. It has 0 bearing on the result of QLibraryInfo::HeadersPath for example.

**Comment by mingwandroid** [comment]
Here's a pyqt5 sample to demonstrate:

Wrong value:

```
import PyQt5.QtCore
PyQt5.QtCore.QLibraryInfo.location(PyQt5.QtCore.QLibraryInfo.HeadersPath)
'C:/qt5/_h_env/Library/include/qt'
```

Right value:

```
import PyQt5.QtCore
PyQt5.QtCore.QLibraryInfo.location(PyQt5.QtCore.QLibraryInfo.HeadersPath)
qapp = QApplication(["blah"])
PyQt5.QtCore.QLibraryInfo.location(PyQt5.QtCore.QLibraryInfo.HeadersPath)
'C:/Users/builder/m64/envs/pyqt/Library/include/qt'
```

**Comment by ras0219-msft** [comment]
If the relative path works sufficiently, that sounds like a good solution to me and I'd be happy to merge a PR for that!

**Comment by glachancecmaisonneuve** [comment]
@mingwandroid let's try to stay on topic please.  I have tried to make this fix happen for more than a year now (see https://github.com/Microsoft/vcpkg/pull/2892) and the comment about qt.conf doesn't work reliably is not relevant to this thread.  **This thread is about having qmake, qdesigner, qml and other tools working, in the vcpkg buildtree, or in an exported vcpkg buildtree**.

As you stated, *qt.conf works for QApplications*, and it so happens that qmake, qdesigner, qml and others are QApplications (technically qmake isnt one, not by inheritance like QDesigner is, but behaves like one by instanciating QLibrary during it startup).  

If you found bugs in pyqt, you should file them with [Riverbank](https://www.riverbankcomputing.com/software/pyqt/intro).

**Comment by glachancecmaisonneuve** [comment]
> that sounds like a good solution to me and I'd be happy to merge a PR for that

Working on it.

**Comment by huangqinjin** [comment]
#3280 has fixed some paths except for `qmldir`. `mklink /D qml ..\qml` in`${CURRENT_INSTALLED_DIR}/debug` fixes it.

**Pull request closed without merging**
