### PR TITLE
Qt 5.11 and static build fixes

### PR DESCRIPTION
**Pull request by RobertBColton**
This updates the `qt5-base` port to build successfully under the new Qt 5.11. It also fixes the issues with respect to static building allowing the static triplet to be used.

### Noteworthy changes
* `fix-C3615.patch` deleted as it has already been sent upstream and is in Qt 5.11
* `fix-msvc2017.patch` added to enable MSVC 2017 builds
* `fix-system-pcre2.patch` recreated to match newer source
* `fix-system-pcre2-linux.patch` recreated to match newer source
* `portfile.cmake` changed from Qt 5.9 to Qt 5.11

### CODE REVIEW

**Comment by tumugin** [comment]
I tested this PR but static build seems to fail on my environment.
```
WARNING: Failure to find: C:\Users\kazuki\Documents\SourceCode\vcpkg\buildtrees\qt5-base\src\5.11.1-35431efc74\src\3rdparty\sqlite\sqlite3.c
WARNING: Failure to find: C:\Users\kazuki\Documents\SourceCode\vcpkg\buildtrees\qt5-base\src\5.11.1-35431efc74\src\3rdparty\sqlite\sqlite3.c
Error: dependent 'C:\Users\kazuki\Documents\SourceCode\vcpkg\buildtrees\qt5-base\src\5.11.1-35431efc74\src\3rdparty\sqlite\sqlite3.c' does not exist.
jom: C:\Users\kazuki\Documents\SourceCode\vcpkg\buildtrees\qt5-base\x86-windows-static-dbg\src\plugins\sqldrivers\sqlite\Makefile [debug] Error 2
jom: C:\Users\kazuki\Documents\SourceCode\vcpkg\buildtrees\qt5-base\x86-windows-static-dbg\src\plugins\sqldrivers\Makefile [sub-sqlite-make_first] Error 2
jom: C:\Users\kazuki\Documents\SourceCode\vcpkg\buildtrees\qt5-base\x86-windows-static-dbg\src\plugins\Makefile [sub-sqldrivers-make_first] Error 2
jom: C:\Users\kazuki\Documents\SourceCode\vcpkg\buildtrees\qt5-base\x86-windows-static-dbg\src\Makefile [sub-plugins-make_first] Error 2
jom: C:\Users\kazuki\Documents\SourceCode\vcpkg\buildtrees\qt5-base\x86-windows-static-dbg\Makefile [sub-src-make_first] Error 2
```
Added this patch to `portfile.cmake` and static build succeeded.
```patch
diff --git a/ports/qt5-base/portfile.cmake b/ports/qt5-base/portfile.cmake
index 5a29e47c..b007757d 100644
--- a/ports/qt5-base/portfile.cmake
+++ b/ports/qt5-base/portfile.cmake
@@ -61,7 +61,7 @@ set(CORE_OPTIONS
 if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")
     list(APPEND CORE_OPTIONS
         -static
-        -no-sqlite
+        -system-sqlite
     )
 else()
     list(APPEND CORE_OPTIONS
```

**Comment by RobertBColton** [comment]
Please tell Robert to update the Chilla.

**Comment by ras0219-msft** [comment]
>update the Chilla.

@RobertBColton What do you mean?

**Comment by ras0219-msft** [comment]
Thanks for the PR and sorry for the long delay handling this!

The current status for x64-windows-static after this PR is:

- qt5-declarative fails
- qt5-activeqt fails
- qt5-xmlpatterns fails

However the other qt components succeed! 🎉

**Comment by RobertBColton** [comment]
Please see #4332 about the chilla.

**Comment by ras0219-msft** [comment]
Thanks!

**Pull request merged**
