### PR TITLE
[lensfun] Add new port

### PR DESCRIPTION
**Pull request by NancyLi1013**
The goal of the `Lensfun `library is to provide a open source database of photographic lenses and their characteristics.
Dependency: `glib`

Note: It currently only supports dynamic build. (`arm`, `arm64`, `uwp `are all not supported)
No features need to test.

Related issue #8801.

### CODE REVIEW

**Comment by NancyLi1013** [comment]
Failed on x64-linux, due to this:
```
[9/18] cd /ci/myagent/_work/3/s/buildtrees/lensfun/x64-linux-dbg/apps && /usr/bin/python3 /ci/myagent/_work/3/s/buildtrees/lensfun/x64-linux-dbg/apps/setup.py build && /ci/myagent/_work/3/s/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/bin/cmake -E touch /ci/myagent/_work/3/s/buildtrees/lensfun/x64-linux-dbg/apps/build/timestamp
FAILED: apps/build/timestamp 
cd /ci/myagent/_work/3/s/buildtrees/lensfun/x64-linux-dbg/apps && /usr/bin/python3 /ci/myagent/_work/3/s/buildtrees/lensfun/x64-linux-dbg/apps/setup.py build && /ci/myagent/_work/3/s/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/bin/cmake -E touch /ci/myagent/_work/3/s/buildtrees/lensfun/x64-linux-dbg/apps/build/timestamp
Traceback (most recent call last):
  File "/ci/myagent/_work/3/s/buildtrees/lensfun/x64-linux-dbg/apps/setup.py", line 6, in <module>
    from distutils.core import setup
ModuleNotFoundError: No module named 'distutils.core'
```
It seems that there is lack of `distutils` in CI system.
But I cannot reproduce this on my local and I didn't find `distutils` on my local either.

So I don't know how to solve it currently.

**Comment by NancyLi1013** [comment]
Please feel free to ask us to reopen this PR if need it.

**Comment by cgilles** [comment]
Hi, 

I compile Lenfun for a big project under Linux, MacOS, and Windows (MinGW). I always dropped python3 support as i only use the C library. Python3 support is to manage the lens database for the calibration. See the CMake options to configure Lensfun:

https://github.com/lensfun/lensfun/blob/master/CMakeLists.txt#L52C1-L53C80

This is how i configure Lensfun in my project:

https://invent.kde.org/graphics/digikam/-/blob/master/project/bundles/3rdparty/ext_lensfun/CMakeLists.txt?ref_type=heads#L11

Please re-open this PR at least to provide the core library + the database.

Note that Lenfun team do not provide stable releases and recommend to use code in rolling-release from git/master repository.

Best regards

Gilles Caulier

**Comment by JackBoosY** [comment]
@cgilles See https://github.com/microsoft/vcpkg/pull/34783

**Pull request closed without merging**
