### PR TITLE
vcpkg_extract_archive: Use vcpkg.exe z-extract

### PR DESCRIPTION
**Pull request by JavierMatosD**
Uses vcpkg.exe to unpack 7z.exe archives. 

This causes a bug with `vcpgk_find_acquire(CLANG)` since we are currently downloading its archive as a `7z.exe` even though it is not a `7z` archive. The tool cannot unpack it.

### CODE REVIEW

**Comment by JavierMatosD** [comment]
vcpkg_find_acquire(7z) should give use the full 7zip as a.7z.exe, the tool should unpack that. ✅

`vcpkg fetch 7zip` should return full 7zip so we should be able to use 7zip for literally any unpacking. ✅ (We don't need 7zr for anything)

Problem:
vcpkg_find_acquire(CLANG) downloads as a .7z.exe -> triggers tool extraction  -> 💣 (not a real 7z archive)

**Comment by JavierMatosD** [comment]
Changed `vcpkg_find_acquire(CLANG)` to download as a `.exe` since it is not a 7z archive. I've opened another [PR against the tool](https://github.com/microsoft/vcpkg-tool/pull/1548) that specifically looks for `.7z.exe` extensions, assuming it is a 7zip archive, and uses the self extractor for those instances. Else, `.exe` will be extracted using 7zip.

**Comment by BillyONeal** [comment]
I merged with master due to https://github.com/microsoft/vcpkg/pull/42491 merging for a CVE fix

**Review by BillyONeal — APPROVED** [review]
Please do not merge this into master.

Instead, assuming https://github.com/microsoft/vcpkg/ is origin, please:

```
git fetch origin
git merge origin/master
git reset origin/master
git commit -am "The commit text you're happy to put into vcpkg's history."
git push origin 7z_extraction
```

and close this PR.

We'll can use that resulting commit SHA in a tool release.

(I would follow the instructions myself but I want you to be listed as the author of the commit and I'm unwilling to `git blame-someone-else` to do that)

**Comment by BillyONeal** [comment]
Hmmm.... Azure seems unhappy for some reason. No reason to think those failures are related to changes here yet.

**Pull request closed without merging**
