### PR TITLE
[aws-lambda-cpp] add new port

### PR DESCRIPTION
**Pull request by marcomagdy**

### CODE REVIEW

**Comment by marcomagdy** [comment]
I just released v0.1.0 so I'll update this PR shortly

**Comment by marcomagdy** [comment]
@Rastaban any chance getting this merged soon?

**Comment by marcomagdy** [comment]
bump

**Comment by Rastaban** [comment]
Sorry for the delay, I am running tests with it now and will report back the results.

**Comment by Rastaban** [comment]
It fails to build on windows using MSVC because the compiler does not recognize the -Wextra switch, but it looks like aws-lambda-cpp does not officially support MSVC so this is probably expected.

**Pull request merged**
