### PR TITLE
[google-cloud-cpp] update to latest (v1.28.0) version

### PR DESCRIPTION
**Pull request by coryan**
- #### What does your PR fix?  

N/A. It updates `google-cloud-cpp` to the latest release (v1.28.0). One of the new things in this release is the `-DGOOGLE_CLOUD_CPP_ENABLE_EXAMPLES=OFF` option, which eliminates the need for `disable-benchmarks.patch`.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  

No change.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  

Yes.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  

Yes.

### CODE REVIEW

**Review by JonLiu1993 — CHANGES_REQUESTED** [review]
@coryan ,Thanks for your pr,please add 'vcpkg_fixup_pkgconfig()' below '
````
vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake TARGET_PATH share)
````
 in portfile.cmake

**Comment by coryan** [comment]
Done, please take another look.

**Comment by ras0219-msft** [comment]
It looks like the grpc pkgconfig files are not fixed up; we'll need to add similar commands to that and abseil before google-cloud-cpp will be able to properly support pkgconfig.

**Comment by coryan** [comment]
Ugh. I have reverted the `pkgconfig` change for now.  I can send PRs for Abseil and gRPC if you want me to and then send a PR for `google-cloud-cpp`.  I could create a PR will all the changes, but that sounds complicated and more risky.

**Comment by ras0219-msft** [comment]
Thanks a bunch; I think doing all three at the same time would be small enough to be put into a single PR, but separate is definitely the "proper" solution :)

**Pull request merged**
