### PR TITLE
[vulkan-sdk-components] Use separate port for the SDK

### PR DESCRIPTION
**Pull request by dg0yt**
Cf. https://github.com/microsoft/vcpkg/pull/35479#issuecomment-1858765149:
- Do not pull in additional SDK dependencies into ports which just need "Vulkan".
- Do not require android-26 to just use Vulkan.

Remarks:
- ~`vulkan-loader` provides a `vulkan.pc`. Now this file is missing for Android. The `vulkan` port could add a polyfill.~ Rejected.
- ~If the gap to the official Vulkan SDK is seen as too large, an alternative name might make this clear, e.g. vulkan-sdk-components.~ Adopted.

### CODE REVIEW

**Comment by dg0yt** [comment]
Who or what would have benefitted from this PR:
-  #35822: By depending on `vulkan`, `vulkan-memory-allocator-hpp` currently pulls in more dependencies than needed.
- https://github.com/microsoft/vcpkg/pull/35344#issuecomment-1865968884: If port vulkan has printed the Android notice, I would not have need to explain. And API level 24 would suffice.

**Comment by Osyotr** [comment]
Ping @juan-lunarg @charles-lunarg

**Comment by juan-lunarg** [comment]
> Do not pull in additional SDK dependencies into ports which just need "Vulkan".

👍🏾 

> Do not require android-26 to just use Vulkan.

👍🏾 

> vulkan-loader provides a vulkan.pc. Now this file is missing for Android. The vulkan port could add a polyfill.

vulkan.pc was added by open source contributors and doesn't represent how the loader maintainer actually wants people to use the library:
https://github.com/KhronosGroup/Vulkan-Loader/blob/f914f5e4a50b71894fc6c57c3ddffef0b5e5820b/loader/CMakeLists.txt#L503

I'd rather not mimic vulkan.pc for Android.

> If the gap to the official Vulkan SDK is seen as too large, an alternative name might make this clear, e.g. vulkan-sdk-components.

👍🏾

**Comment by Neumann-A** [comment]
hmm i wonder if `vulkan` should stay the sdk and `vulkan-cmake/findvulkan` should be the parts which cmake requires to fullfill `FindVulkan.cmake` or if the ports depending on vulkan should be changed to depend on the parts which they actually require. The reason I say that is because `vulkan` was previously the system installed full sdk according to the port messages. 
But in the end I don't really care about how the apparent problem is solved.

**Pull request merged**
