### PR TITLE
Add WinPCAP Developer's Pack

### PR DESCRIPTION
**Pull request by UnaNancyOwen**
Add WinPCAP Developer's Pack

### CODE REVIEW

**Comment by codicodi** [comment]
What compiler was used to produce these binaries? According to [website](https://www.winpcap.org)  version 4.1.3 was released in 2013, so they certainly weren't built with vc14x ABI

**Comment by UnaNancyOwen** [comment]
@codicodi It can be used with vc14x. Currently, I'm being use pre-built library with vc14x.
Should It building from source code?

**Comment by codicodi** [comment]
Sure, building from source is always the best approach

**Comment by UnaNancyOwen** [comment]
@codicodi OK, I will try it. Thanks,

**Comment by UnaNancyOwen** [comment]
@codicodi I fixed that as it was pointed out to me. Please review it. Thanks,

**Comment by codicodi** [comment]
Cool!
I can see the resulting dlls are statically linked to the CRT. Is it possible to select CRT type based on the value of `VCPKG_CRT_LINKAGE`?

**Comment by UnaNancyOwen** [comment]
@codicodi I made some fixes about it. Please review it.

**Comment by codicodi** [comment]
Hmm, they still seem to be linked statically
```
> dumpbin /dependents .\packages\winpcap_x64-windows\bin\wpcap.dll
  ...
  Image has the following dependencies:

    WS2_32.dll
    packet.dll
    KERNEL32.dll

  ...
```

**Comment by UnaNancyOwen** [comment]
@codicodi Hmm... Sorry, I have no more ideas. Do you have any ideas?

**Comment by ras0219-msft** [comment]
Thanks for the PR and sorry for the delay!

By a brief survey of the WinPCAP examples, it looks like they take care to provide `pcap_x_free()` functions for all their allocated memory. It also looks like a C-abi, so I think it can probably be used safely even though it's static linking the CRT.

While it would be great to see this improved in the future (I suspect a CMake buildsystem replacement will be needed), I think merging it in the current state is acceptable.

**Comment by Voskrese** [comment]
It may be worth using a newer version, from another group of [npcap-sdk-0.1]

https://nmap.org/npcap/#download
https://nmap.org/npcap/dist/npcap-sdk-0.1.zip

https://github.com/nmap/npcap

**Pull request merged**
