### PR TITLE
[FFMpeg] better iOS support

### PR DESCRIPTION
**Pull request by XITRIX**
If this PR updates an existing port, please uncomment and fill out this checklist:

- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [X] SHA512s are updated for each updated download.
- [X] The "supports" clause reflects platforms that may be fixed by this new version.
- [X] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [X] Any patches that are no longer applied are deleted from the port's directory.
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by XITRIX** [comment]
@microsoft-github-policy-service agree

**Comment by MonicaLiu0311** [comment]
At present, the version information of your commit is inconsistent with your local one:
```
##[error]Found the following errors:
##[error]versions/f-/ffmpeg.json(2,): error : while parsing versions for ffmpeg from version/f-/ffmpeg.json
6.1.1#1 is declared with cde9944f0f87e8bf96b08bdfd42215b1ef77e26d, but the local port has a different SHA 830c58775efe5c5e501bad472af97b064b3446bc.
```

`--overwrite-version`
After the first modification, please run `./vcpkg x-add-version portName` to generate the corresponding json; for subsequent modifications of the same version, please use `./vcpkg x-add-version portName --overwrite-version` to update git-tree.

[maintainer guide#versioning](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md#versioning).

**Comment by XITRIX** [comment]
@MonicaLiu0311, thanks for details, changed hash to proper one

**Comment by nirvn** [comment]
@XITRIX , nice contribution, thanks.

**Review by MonicaLiu0311 — APPROVED** [review]

**Pull request merged**
