### PR TITLE
[restclient-cpp]: correct the way to remove debug/include

### PR DESCRIPTION
**Pull request by curoky**
Just need removing `${CURRENT_PACKAGES_DIR}/debug/include`, not `${CURRENT_PACKAGES_DIR}/lib` and `${CURRENT_PACKAGES_DIR}/bin`.

### CODE REVIEW

**Comment by JackBoosY** [comment]
The CI test reports:
```
2019-12-28T12:24:48.1340353Z -- Performing post-build validation
2019-12-28T12:24:48.1341935Z Import libs were not present in C:\vsts\_work\3\s\packages\restclient-cpp_x86-windows\debug\lib
2019-12-28T12:24:48.1343629Z If this is intended, add the following line in the portfile:
2019-12-28T12:24:48.1345668Z     SET(VCPKG_POLICY_DLLS_WITHOUT_LIBS enabled)
2019-12-28T12:24:48.1347511Z Import libs were not present in C:\vsts\_work\3\s\packages\restclient-cpp_x86-windows\lib
2019-12-28T12:24:48.1349063Z If this is intended, add the following line in the portfile:
2019-12-28T12:24:48.1351279Z     SET(VCPKG_POLICY_DLLS_WITHOUT_LIBS enabled)
2019-12-28T12:24:48.4992565Z The following DLLs have no exports:
2019-12-28T12:24:48.4994289Z 
2019-12-28T12:24:48.4997696Z     C:/vsts/_work/3/s/packages/restclient-cpp_x86-windows/debug/bin/restclient-cppd.dll
2019-12-28T12:24:48.4999850Z     C:/vsts/_work/3/s/packages/restclient-cpp_x86-windows/bin/restclient-cpp.dll
2019-12-28T12:24:48.5001783Z 
2019-12-28T12:24:48.5004075Z DLLs without any exports are likely a bug in the build script.
2019-12-28T12:24:48.9199924Z There should be no empty directories in C:\vsts\_work\3\s\packages\restclient-cpp_x86-windows
2019-12-28T12:24:48.9227415Z The following empty directories were found:
2019-12-28T12:24:48.9227698Z 
2019-12-28T12:24:48.9230345Z     C:/vsts/_work/3/s/packages/restclient-cpp_x86-windows/debug/lib
2019-12-28T12:24:48.9232676Z     C:/vsts/_work/3/s/packages/restclient-cpp_x86-windows/lib
2019-12-28T12:24:48.9234393Z 
2019-12-28T12:24:48.9236674Z If a directory should be populated but is not, this might indicate an error in the portfile.
2019-12-28T12:24:48.9238957Z If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:
2019-12-28T12:24:48.9240698Z 
2019-12-28T12:24:48.9243840Z     file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/a/dir ${CURRENT_PACKAGES_DIR}/some/other/dir)
2019-12-28T12:24:48.9245849Z 
2019-12-28T12:24:48.9247821Z 
2019-12-28T12:24:48.9250064Z Found 4 error(s). Please correct the portfile:
2019-12-28T12:24:48.9253404Z     C:\vsts\_work\3\s\ports\restclient-cpp\portfile.cmake
2019-12-28T12:24:48.9255258Z -- Performing post-build validation done
2019-12-28T12:24:49.0651015Z Error: Building package restclient-cpp:x86-windows failed with: POST_BUILD_CHECKS_FAILED
2019-12-28T12:24:49.0652679Z Elapsed time for package restclient-cpp:x86-windows: 11.76 s
```

**Comment by SeekingMeaning** [comment]
Hmm, perhaps update the cmake linking patch like https://github.com/mrtazz/restclient-cpp/pull/135 (The ppconsul regression should be fixed by #9752)

**Comment by JackBoosY** [comment]
@curoky Yes, but we do have restclient-cpp:windows regreession. Please see [test results](https://dev.azure.com/vcpkg/public/_build/results?buildId=26408&view=results).

**Comment by curoky** [comment]
Maybe i need to update the cmake-link patch. 
I can't test it in window, i just have linux environment.

**Comment by JackBoosY** [comment]
@curoky I've fixed it.

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
Please sign CLA. Thanks.

**Comment by vicroms** [comment]
Thanks for the PR

**Pull request merged**
