### PR TITLE
[x265] Update to version 3.5

### PR DESCRIPTION
**Pull request by 0xC0000054**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by LilyWangLL** [comment]
Pinging @0xC0000054 for response. Is work still being done for this PR?

**Comment by 0xC0000054** [comment]
> Is work still being done for this PR?

No, it is done.
I am not sure why the automated builds are failing, the `x64-windows` target was working when I tested it locally.

**Comment by LilyWangLL** [comment]
> I am not sure why the automated builds are failing, the `x64-windows` target was working when I tested it locally.

I also test passed locally. I installed `x265:x64-windows`.

**Comment by dg0yt** [comment]
Proposed fix for the windows issue in https://github.com/0xC0000054/vcpkg/pull/1: 
Do not rely on `hg` or `git` being available to determine the version.

**Comment by 0xC0000054** [comment]
I would create another PR with your changes.

**Comment by dg0yt** [comment]
#35531

**Pull request closed without merging**
