### PR TITLE
[tinyexif] update to master

### LINKED ISSUE #23072: [TinyEXIF] update to master
Library name: tinyexif

New version number: master

Other information that may be useful (release notes, etc...)

Unless @cdcseacave creates a tag for a new version, this port should pull from master as the current version 1.0.2, is 3 years old, and there has been many updates since then, including ifstream support, that can not be utilizied in the current port version

### PR DESCRIPTION
**Pull request by JonLiu1993**
Fix #23072 

Update port tinyexif to the latest commit 

Note: no feature need to test

### CODE REVIEW

**Review by FrankXie05 — APPROVED** [review]

**Comment by BillyONeal** [comment]
@cdcseacave Are there plans for TinyEXIF to add a new version tag anytime soon or are you expecting customers to just grab what's in master now?

Thanks!

**Comment by reunanen** [comment]
@BillyONeal sorry, I have no idea – I'm not a maintainer of this project (think you may have wanted to ping somebody else instead?)

**Comment by reunanen** [comment]
@cdcseacave perhaps?

**Comment by BillyONeal** [comment]
> @BillyONeal sorry, I have no idea – I'm not a maintainer of this project (think you may have wanted to ping somebody else instead?)

I pinged you in addition because you authored https://github.com/cdcseacave/TinyEXIF/commit/d75f772ffa330b28539a0c6493803c9205b281a6

**Comment by cdcseacave** [comment]
> @cdcseacave Are there plans for TinyEXIF to add a new version tag anytime soon or are you expecting customers to just grab what's in master now?
> 
> Thanks!

Using the latest master is fine for now. No new tags foreseen in the near future. Thx

**Comment by BillyONeal** [comment]
> Using the latest master is fine for now. No new tags foreseen in the near future. Thx

Thank you!

**Comment by BillyONeal** [comment]
Thanks for the version update!

**Pull request merged**
