### PR TITLE
[directxtk, directxtk12, directxtex, directxmesh, uvatlas] ports updated for September 2021 release

### PR DESCRIPTION
**Pull request by walbourn**
# DirectX Tool Kit
* Added ModelBone support for transformation hierarchies
  * Rigid-body & skinned animation Draw support added to Model
* Added type aliases ``ModelMeshPart::InputLayoutCollection``, ``GeometricPrimitive::VertexCollection`` and ``IndexCollection``.
* EnvironmentMapEffect and NormalMapEffect will now use default diffuse/normal textures if none are set
* VS 2017 projects updated to require the Windows 10 SDK (19401)
* Code review updates

# DirectX Tool Kit for DX12
* Added ModelBone support for transformation hierarchies
  * Rigid-body & skinned animation Draw support added to Model
* Support for loading Visual Studio ``CMO`` models added using BasicEffect or SkinnedEffect materials
* Added type aliases ``Model::EffectCollection``, ``ModelMeshPart::InputLayoutCollection``, ``GeometricPrimitive::VertexCollection`` and ``IndexCollection``
* Fixed handle leak in ResourceUploadBatch
* Updated ScopeBarrier to conform with C++14 ``std::initializer_list``
* VS 2017 projects updated to require the Windows 10 SDK (19401) and make use of Shader Model 6.0
* Code review updates

# DirectXMesh
* Fixed overflow case in meshlet generation with degenerate triangles
* Minor code review and project cleanup

# DirectXTex
* Minor code and project cleanup

# UVatlas
* Minor code and project cleanup

> directxtk12 port now opts into Shader Model 6 which is what all the other projects are doing with Sept 2021.

### CODE REVIEW

**Comment by walbourn** [comment]
A GitHub action told me to try out using the new ``vcpkg-cmake`` port commands.

I did, and for directxtk and directxtk12 they fail because my CMakeLists generates C headers via a custom_command that needs to be used for building:

```
CMake Error at CMakeLists.txt:152 (add_custom_command):
  OUTPUT path

    D:/vcpkg/buildtrees/directxtk/src/sept2021-e237a84202.clean/Src/Shaders/Compiled/SpriteEffect_SpriteVertexShader.inc

  in a source directory as an output of custom command.
```

**Comment by dg0yt** [comment]
> my CMakeLists generates C headers via a custom_command that needs to be used for building:

If you need to generate files, better do that in the binary directory, not in the source directory.

The new cmake maintainer functions use Ninja by default. And they build debug and release in parallel by default. This isn't  compatible with modifying files in the source directory.

**Comment by walbourn** [comment]
> If you need to generate files, better do that in the binary directory, not in the source directory.

This would break compatibility with all my vcxprojs in the current design. I'll take a look at options for resolving this in a future update of my libraries.

**Comment by BillyONeal** [comment]
Thanks for the updates! Please do consider avoiding edits to the source tree during build soon.

**Pull request merged**
