### PR TITLE
[mysql-connector-cpp] Add correct target namespace

### PR DESCRIPTION
**Pull request by FrankXie05**
The namespace in usage of port [mysql-connector-cpp] should be `unofficial`.
Fix PR #26536  incorrect namespace
````
mysql-connector-cpp provides CMake targets: 
    # this is heuristically generated, and may not be correct
    find_package(unofficial-mysql-connector-cpp CONFIG REQUIRED)
    target_link_libraries(main PRIVATE unofficial::mysql-connector-cpp::connector)
````

### CODE REVIEW

**Comment by FrankXie05** [comment]
The usage after repai: 
````
mysql-connector-cpp provides CMake targets:

    # this is heuristically generated, and may not be correct 
    find_package(unofficial-mysql-connector-cpp CONFIG REQUIRED)
    target_link_libraries(main PRIVATE unofficial::connector)
````

**Comment by JackBoosY** [comment]
This change will break usage for users and I don't think it's necessary now.

**Comment by dg0yt** [comment]
> This change will break usage for users and I don't think it's necessary now.

The usage was changed two days ago. So there is a window of opportunity to permanently fix it now.

> ~~~
> target_link_libraries(main PRIVATE unofficial::connector)

This is still not correct because it lacks a package component. You need `unofficial::<pkg>::connector`.

**Comment by FrankXie05** [comment]
Related PR #26536

**Comment by FrankXie05** [comment]
This usage has been tested in local `cmake` and `MSVC` projects.

**Review by JackBoosY — APPROVED** [review]

**Pull request merged**
