### PR TITLE
[boost] Fix `boost-modular-build.cmake` with VS 2022 17.0 Preview 2

### PR DESCRIPTION
**Pull request by StephanTLavavej**
- #### What does your PR fix?

After installing only VS 2022 17.0 Preview 2, and using `vcpkg.exe` containing the just-merged https://github.com/microsoft/vcpkg-tool/pull/124 (fixing https://github.com/microsoft/vcpkg/issues/18987 ), attempting to `vcpkg.exe install boost-math:x86-windows boost-math:x64-windows` fails with:

```
CMake Error at installed/x64-windows/share/boost-build/boost-modular-build.cmake:317 (message):
  Unsupported value for VCPKG_PLATFORM_TOOLSET: 'v143'
```

<details>
  <summary>Click to expand full diagnostic!</summary>

```
Starting package 25/92: boost-exception:x64-windows
Building package boost-exception[core]:x64-windows...
-- Downloading https://github.com/boostorg/exception/archive/boost-1.76.0.tar.gz -> boostorg-exception-boost-1.76.0.tar.gz...
-- Extracting source D:/GitHub/STL/vcpkg/downloads/boostorg-exception-boost-1.76.0.tar.gz
-- Using source at D:/GitHub/STL/vcpkg/buildtrees/boost-exception/src/ost-1.76.0-5e68eb1a52.clean
CMake Error at installed/x64-windows/share/boost-build/boost-modular-build.cmake:317 (message):
  Unsupported value for VCPKG_PLATFORM_TOOLSET: 'v143'
Call Stack (most recent call first):
  ports/boost-exception/portfile.cmake:15 (boost_modular_build)
  scripts/ports.cmake:141 (include)


Error: Building package boost-exception:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-exception:x64-windows
  Vcpkg version: 2021-07-21-unknownhash-debug

Additionally, attach any relevant sections from the log files above.
```
</details>

Applying this patch allows the build to succeed.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?

This is specific to Windows. I have updated the CI baseline.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

I believe so.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?

Yes, please double-check this as I barely know what I'm doing.

### CODE REVIEW

**Comment by BillyONeal** [comment]
> I have not updated the CI baseline

It looks like you did :)

**Comment by StephanTLavavej** [comment]
Ha! I've updated my PR description, thanks.

**Review by ras0219-msft — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
