### PR TITLE
[ogre] Update to 13.4.4

### LINKED ISSUE #22597: [ogre] Build error on x64-osx
Package: ogre[assimp,core,freeimage,overlay,zziplib]:x64-osx -> 1.12.9#5
**Host Environment**
- Host: arm64-osx
- Compiler: AppleClang 13.0.0.13000029
-    vcpkg-tool version: 2999-12-31-unknownhash-debug
    vcpkg-scripts version: 4fff1e9cf 2022-01-17 (17 hours ago)

**To Reproduce**
`vcpkg install `

**Failure logs**
```
ogre currently requires the following library from the system package manager:
    Xaw

It can be installed on Ubuntu systems via apt-get install libxaw7-dev
-- Using cached OGRECave-ogre-7d0c8181ac43ad20bdba326abbd3deeddf310f0b.tar.gz.
-- Extracting source /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/downloads/OGRECave-ogre-7d0c8181ac43ad20bdba326abbd3deeddf310f0b.tar.gz
-- Applying patch toolchain_fixes.patch
-- Applying patch fix-dependency.patch
-- Applying patch fix-findimgui.patch
-- Applying patch disable-dependency-qt.patch
-- Using source at /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/ogre/src/eddf310f0b-6ab1152694.clean
CMake Deprecation Warning at scripts/cmake/vcpkg_check_features.cmake:182 (message):
  calling `vcpkg_check_features` without the `FEATURES` keyword has been
  deprecated.

      Please add the `FEATURES` keyword to the call.
Call Stack (most recent call first):
  ports/ogre/portfile.cmake:32 (vcpkg_check_features)
  scripts/ports.cmake:145 (include)


-- Found external ninja('1.10.2').
-- Configuring x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/downloads/tools/cmake-3.21.1-osx/cmake-3.21.1-macos-universal/CMake.app/Contents/bin/cmake /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/ogre/src/eddf310f0b-6ab1152694.clean -DOGRE_BUILD_DEPENDENCIES=OFF -DOGRE_BUILD_SAMPLES=OFF -DOGRE_BUILD_TESTS=OFF -DOGRE_BUILD_TOOLS=OFF -DOGRE_BUILD_MSVC_MP=ON -DOGRE_BUILD_MSVC_ZM=ON -DOGRE_INSTALL_DEPENDENCIES=OFF -DOGRE_INSTALL_DOCS=OFF -DOGRE_INSTALL_PDB=OFF -DOGRE_INSTALL_SAMPLES=OFF -DOGRE_INSTALL_TOOLS=OFF -DOGRE_INSTALL_CMAKE=ON -DOGRE_INSTALL_VSPROPS=OFF -DOGRE_STATIC=ON -DOGRE_CONFIG_THREAD_PROVIDER=std -DOGRE_BUILD_RENDERSYSTEM_D3D11=ON -DOGRE_BUILD_RENDERSYSTEM_GL=ON -DOGRE_BUILD_RENDERSYSTEM_GL3PLUS=ON -DOGRE_BUILD_RENDERSYSTEM_GLES=OFF -DOGRE_BUILD_RENDERSYSTEM_GLES2=OFF -DFREETYPE_FOUND=ON -DOGRE_BUILD_RENDERSYSTEM_D3D9=OFF -DOGRE_BUILD_COMPONENT_JAVA=OFF -DOGRE_BUILD_COMPONENT_PYTHON=OFF -DOGRE_BUILD_COMPONENT_CSHARP=OFF -DOGRE_BUILD_COMPONENT_OVERLAY=ON -DOGRE_CONFIG_ENABLE_ZIP=ON -DOGRE_RESOURCEMANAGER_STRICT=0 -DOGRE_CMAKE_DIR=share/ogre -DCMAKE_MAKE_PROGRAM=/opt/homebrew/bin/ninja -DCMAKE_SYSTEM_NAME=Darwin -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/scripts/toolchains/osx.cmake -DVCPKG_TARGET_TRIPLET=x64-osx -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg -DZ_VCPKG_ROOT_DIR=/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg -D_VCPKG_INSTALLED_DIR=/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed -DVCPKG_MANIFEST_INSTALL=OFF -DCMAKE_OSX_ARCHITECTURES=x86_64 -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/packages/ogre_x64-osx/debug
    Working Directory: /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/ogre/x64-osx-dbg
    Error code: 1
    See logs for more information:
      /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/ogre/config-x64-osx-dbg-out.log
      /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/ogre/config-x64-osx-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:358 (vcpkg_execute_required_process)
  ports/ogre/portfile.cmake:46 (vcpkg_configure_cmake)
  scripts/ports.cmake:145 (include)



```
<details><summary>/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/ogre/config-x64-osx-dbg-out.log</summary>

```
-- The C compiler identification is AppleClang 13.0.0.13000029
-- The CXX compiler identification is AppleClang 13.0.0.13000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring OGRE 1.12.9
-- Check size of void*
-- Check size of void* - done
-- Performing Test OGRE_GCC_HAS_SSE
-- Performing Test OGRE_GCC_HAS_SSE - Success
-- Search path: /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/ogre/x64-osx-dbg/Dependencies;/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/ogre/src/eddf310f0b-6ab1152694.clean/Dependencies;/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/ogre/x64-osx-dbg/../Dependencies;/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/ogre/src/eddf310f0b-6ab1152694.clean/../Dependencies
-- Found ZLIB: optimized;/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/lib/libz.a;debug;/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libz.a (found version "1.2.11") 
-- Looking for ZZip...
-- Found PkgConfig: /opt/homebrew/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'zziplib'
--   Found zziplib, version 0.13.71
-- Could not locate ZZip
-- Looking for FreeImage...
-- Checking for module 'freeimage'
--   No package 'freeimage' found
-- Found BZip2: optimized;/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/lib/libbz2.a;debug;/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libbz2d.a (found version "1.0.8") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Found PNG: optimized;/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libpng.a;debug;/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libpng16d.a (found version "1.6.37") 
-- Found OpenGL: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/OpenGL.framework   
-- Looking for Cg...
-- Cg_PREFIX_PATH changed.
-- Checking for module 'Cg'
--   No package 'Cg' found
-- Could not locate Cg
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found PythonInterp: /usr/bin/python (found version "2.7.18") 
-- Found PythonLibs: /usr/lib/libpython2.7.dylib (found version "2.7.18") 
-- Found JPEG: optimized;/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/lib/libjpeg.a;debug;/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg_installed/x64-osx/debug/lib/libjpeg.a (found version "62") 
-- Looking for Softimage...
-- Softimage_PREFIX_PATH changed.
-- Could not locate Softimage
-- Looking for strtol_l
-- Looking for strtol_l - found
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- 
-----------------------------------------------------------------------------
-- The following external packages were located on your system.
-- This installation will have the extra features provided by these packages.
+ zlib
+ freeimage
+ freetype
+ OpenGL
+ OpenGL ES 2.x
+ OpenEXR
+ Python
+ pugixml
+ SDL2
+ Doxygen
-----------------------------------------------------------------------------
-- The following OPTIONAL packages could NOT be located on your system.
-- Consider installing them to enable more features from this software.
+ zziplib: Extract data from zip archives <http://zziplib.sourceforge.net>
+ cg: C for graphics shader language <http://developer.nvidia.com/object/cg_toolkit.html>
+ SWIG: Language bindings (Python, Java, C#) for OGRE <http://www.swig.org/>
+ Assimp: Needed for the AssimpLoader Plugin <https://www.assimp.org/>
+ Qt: optional integration with the Qt Library for window creation and input <http://www.qt.io/>
+ Softimage: Softimage SDK needed for building XSIExporter <FALSE>
-----------------------------------------------------------------------------

-- 
----------------------------------------------------------------------------
  FEATURE SUMMARY
----------------------------------------------------------------------------

Building components:
  + Bites
  + MeshLodGenerator
  + Overlay
  + Overlay Dear Imgui
  + Paging
  + Property
  + RTShader System
  + RTShader System Shaders
  + Terrain
  + Volume
Building plugins:
  + BSP scene manager
  + Octree scene manager
  + OpenEXR image codec
  + STBI codec (generic)
  + FreeImage codec (generic)
  + Portal connected zone scene manager
  + Particle FX
  + DotScene loader
Building rendersystems:
  + OpenGL
  + OpenGL 3+
Building core features:
  + Mesh Lod
  + DDS image codec (.dds)
  + ETC image codec (.pkm, .ktx) 
  + ASTC image codec (.astc)
  + Nodeless positioning of Lights and Cameras [DEPRECATED]

Build type:                      static
Thread safety:                   none
ResourceManager behaviour:       legacy [DEPRECATED]
Use double precision:            disabled
Nodes inherit transform:         disabled
Assert mode:                     release exceptions

----------------------------------------------------------------------------

-- Configuring done
-- Generating done
```
</details>
<details><summary>/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/ogre/config-x64-osx-dbg-err.log</summary>

```
CMake Deprecation Warning at CMakeLists.txt:37 (cmake_policy):
  The OLD behavior for policy CMP0078 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


objc[15162]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x1dfeeeb90) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1040082c8). One of the two will be used. Which one is undefined.
objc[15162]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x1dfeeebe0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x104008318). One of the two will be used. Which one is undefined.
2022-01-17 20:27:38.900 xcodebuild[15162:12454426] [MT] PluginLoading: Required plug-in compatibility UUID 7A3A18B7-4C08-46F0-A96A-AB686D315DF0 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/VVDocumenter-Xcode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2022-01-17 20:27:38.900 xcodebuild[15162:12454426] [MT] PluginLoading: Required plug-in compatibility UUID 7A3A18B7-4C08-46F0-A96A-AB686D315DF0 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ClangFormat.xcplugin' not present in DVTPlugInCompatibilityUUIDs
CMake Warning (dev) at /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/downloads/tools/cmake-3.21.1-osx/cmake-3.21.1-macos-universal/CMake.app/Contents/share/cmake-3.21/Modules/CMakeDependentOption.cmake:52 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'OGRE_BUILD_RENDERSYSTEM_GLES2'.
Call Stack (most recent call first):
  CMakeLists.txt:313 (cmake_dependent_option)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error:
  Running

   '/opt/homebrew/bin/ninja' '-C' '/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/ogre/x64-osx-dbg' '-t' 'recompact'

  failed with:

   ninja: error: build.ninja:2533: bad $-escape (literal $ must be written as $$)

  



CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_INSTALL_BINDIR
    CMAKE_INSTALL_LIBDIR
    OGRE_BUILD_MSVC_MP
    OGRE_BUILD_MSVC_ZM
    OGRE_BUILD_RENDERSYSTEM_GLES
    OGRE_INSTALL_VSPROPS
    VCPKG_CRT_LINKAGE
    VCPKG_PLATFORM_TOOLSET
    VCPKG_SET_CHARSET_FLAG
    _VCPKG_ROOT_DIR


CMake Generate step failed.  Build files cannot be regenerated correctly.
```
</details>

**Additional context**
<details><summary>vcpkg.json</summary>

```
{
  "name": "lichtsteuerung",
  "version-string": "2.0.0",
  "dependencies": [
    "ogre"
  ]
}

```
</details>

### LINKED ISSUE #24984: [ogre] update to 13.3.4
Library name: ogre

New version number: 13.3.4

Other information that may be useful (release notes, etc...)
This port was last updated in 2020. Don't be confused with the new versioning number, ogre developers just dropped 1 from 1.13 so it's just v13 now.
https://github.com/OGRECave/ogre

### PR DESCRIPTION
**Pull request by dg0yt**
(Including squashed commits from https://github.com/microsoft/vcpkg/pull/26938)

- #### What does your PR fix?
  Resolves #24984.
  Fixes #22597.
  Changes installation layout to use per build-type `etc/ogre` (for config) and `plugins/ogre`, and to use `share/ogre` for common stuff.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  fixes osx, no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  yes

- #### Known issues
  - Upstream limitation (won't fix): There is vendored copy of miniz. It cannot be unvendored easily because ogre usage relies on private functions.
  - Upstream limitation (won't fix): The pkg-config files probably lack some transitive usage requirements.
  - Port limitation: For linux etc., the port requires the Xaw system library. However, apart from upstream's pc file template, it isn't strictly necessary.

### CODE REVIEW

**Comment by autoantwort** [comment]
https://github.com/microsoft/vcpkg/issues/22597#issuecomment-1014845137 Did an update fixed this issue?

**Comment by dg0yt** [comment]
> [#22597 (comment)](https://github.com/microsoft/vcpkg/issues/22597#issuecomment-1014845137) Did an update fixed this issue?

The bug was fixed upstream in https://github.com/OGRECave/ogre/commit/84ae9396322a39f766b7acaeb9a1b15f4c51d261.
But the immediate solution for vcpkg was setting `-DOGRE_BUILD_LIBS_AS_FRAMEWORKS=OFF` which disabled the broken section.

**Review by JonLiu1993 — DISMISSED** [review]

**Comment by JonLiu1993** [comment]
@dg0yt, Thanks for your pr, when I tested the features by command "./vcpkg install ogre[*]:x86-windows",
I got this error, please take a look:
````
CMake Error at F:/Feature-test/orge/vcpkg/downloads/tools/cmake-3.24.0-windows/cmake-3.24.0-windows-i386/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR) (Required is at
  least version "3.0.8")
Call Stack (most recent call first):
````

**Comment by dg0yt** [comment]
> @dg0yt, Thanks for your pr, when I tested the features by command "./vcpkg install ogre[*]:x86-windows", I got this error, please take a look:
> 
> ```
> CMake Error at F:/Feature-test/orge/vcpkg/downloads/tools/cmake-3.24.0-windows/cmake-3.24.0-windows-i386/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
>   Could NOT find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR) (Required is at
>   least version "3.0.8")
> Call Stack (most recent call first):
> ```

Because you don't have `swig` installed. It is not a regression. 
(I could add `vcpkg_find_acquire_program(SWIG)` but I cannot test it for windows triplets.)

**Comment by JonLiu1993** [comment]
> > @dg0yt, Thanks for your pr, when I tested the features by command "./vcpkg install ogre[*]:x86-windows", I got this error, please take a look:
> > ```
> > CMake Error at F:/Feature-test/orge/vcpkg/downloads/tools/cmake-3.24.0-windows/cmake-3.24.0-windows-i386/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
> >   Could NOT find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR) (Required is at
> >   least version "3.0.8")
> > Call Stack (most recent call first):
> > ```
> 
> Because you don't have `swig` installed. It is not a regression. (I could add `vcpkg_find_acquire_program(SWIG)` but I cannot test it for windows triplets.)

@dg0yt, I added `vcpkg_find_acquire_program(SWIG)` to portfile.cmake file, but got this error,
I can help you test it.
````
CMake Error at CMakeLists.txt:19 (vcpkg_find_acquire_program):
  Unknown CMake command "vcpkg_find_acquire_program".
````

**Comment by dg0yt** [comment]
> I added `vcpkg_find_acquire_program(SWIG)` to portfile.cmake file, but got this error, I can help you test it.
> 
> ```
> CMake Error at CMakeLists.txt:19 (vcpkg_find_acquire_program):
>   Unknown CMake command "vcpkg_find_acquire_program".
> ```

Please think twice.

**Comment by JonLiu1993** [comment]
> > I added `vcpkg_find_acquire_program(SWIG)` to portfile.cmake file, but got this error, I can help you test it.
> > ```
> > CMake Error at CMakeLists.txt:19 (vcpkg_find_acquire_program):
> >   Unknown CMake command "vcpkg_find_acquire_program".
> > ```
> 
> Please think twice.

Sorry, I forget I have added this to CMakeLists.txt file, I remove `vcpkg_find_acquire_program(SWIG)`  code in CMakeLists.txt file, and tested again, but also can't find `SWIG`
````
CMake Error at F:/Feature-test/orge/vcpkg/downloads/tools/cmake-3.24.0-windows/cmake-3.24.0-windows-i386/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR) (Required is at
  least version "3.0.8")
Call Stack (most recent call first):
````

**Comment by dg0yt** [comment]
> `missing: SWIG_EXECUTABLE`

This tells us what to do with `SWIG`.

**Comment by JonLiu1993** [comment]
@dg0yt, The above error is solved, but a new error is encountered,
````
CMake Error at F:/Feature-test/orge/vcpkg/downloads/tools/cmake-3.24.0-windows/cmake-3.24.0-windows-i386/share/cmake-3.24/Modules/CMakeDetermineCSharpCompiler.cmake:5 (message):
  C# is currently only supported for Microsoft Visual Studio 2010 and later.
Call Stack (most recent call first):
  Components/Csharp/CMakeLists.txt:8 (enable_language)


CMake Error: CMAKE_CSharp_COMPILER not set, after EnableLanguage
````

**Comment by dg0yt** [comment]
Certainly not a regression. I'm not going to fix it.

**Review by JonLiu1993 — APPROVED** [review]

**Comment by JonLiu1993** [comment]
> Certainly not a regression. I'm not going to fix it.

It is difficult for these features to be successfully tested locally

**Pull request merged**
