### PR TITLE
[wavpack] Update to 5.7.0

### PR DESCRIPTION
**Pull request by CrSjimo**
Update wavpack to 5.7.0

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [x] The "supports" clause reflects platforms that may be fixed by this new version.
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] When updating the upstream version, the `"port-version"` is reset (removed from `vcpkg.json`).
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by CrSjimo** [comment]
@microsoft-github-policy-service agree

**Comment by CrSjimo** [comment]
sdl2-mixer that depends on wavpack comes with errors on some platforms. What's wrong with that?

**Comment by dg0yt** [comment]
wavpack-config.cmake lacks `find_dependency(Threads)` etc.
~~~
CMake Error at /mnt/vcpkg-ci/installed/x64-linux/share/wavpack/wavpack-config.cmake:60 (set_target_properties):
  The link interface of target "WavPack::WavPack" contains:

    Threads::Threads

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
~~~

**Comment by CrSjimo** [comment]
It appears that there are some issues with Wavpack's CMakeLists. I have submitted a pull request to its repo, and later I'll make a patch to fix it.

**Pull request closed without merging**
