### PR TITLE
[mongoose] Add new port

### PR DESCRIPTION
**Pull request by myd7349**
https://github.com/cesanta/mongoose

There is also a Javascript project named `mongoose`: https://github.com/Automattic/mongoose
From https://repology.org/projects/?search=mongoose, we see that some use `mongoose` as the lib name, and some use `libmongoose`.

`Cesanta` also provides a web server application named `mongoose` which can be downloaded from the homepage.

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for the PR and the name research 👍 !

Since we always have 3.14 available, we can start taking advantage of new awesome defaults in cmake such as the default install directories[1].

[1] https://cmake.org/cmake/help/v3.14/command/install.html#targets

**Comment by gjasny** [comment]
Just a heads-up: there's also civetweb in vcpkg which is a mongoose fork but uses the same symbol names.

**Comment by dan-shaw** [comment]
Thanks for the PR!

**Pull request merged**
