### PR TITLE
[curl] Fix/android curl debug bin

### LINKED ISSUE #15940: [curl] Port fails on Android due to leftovers in debug/bin
**Host Environment**
- OS: Android
- Compiler: LLVM, NDK21e

**To Reproduce**
`./vcpkg install curl:arm-android`

**Failure logs** 
```
-- Performing post-build validation
There should be no empty directories in /data/vcpkg/packages/curl_arm-android
The following empty directories were found:

    /data/vcpkg/packages/curl_arm-android/bin
    /data/vcpkg/packages/curl_arm-android/debug/bin

If a directory should be populated but is not, this might indicate an error in the portfile.
If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:

    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/a/dir" "${CURRENT_PACKAGES_DIR}/some/other/dir")


Found 1 error(s). Please correct the portfile:
    /data/vcpkg/ports/curl/portfile.cmake
```

I have a PR ready

### PR DESCRIPTION
**Pull request by venabled**
**Describe the pull request**

- What does your PR fix? Fixes #15940

- Which triplets are supported/not supported? Have you updated the CI baseline?

Tested on `arm-android` which is what I'm trying to fix.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

I think so, I think I'm up to speed on the port version bumps now thanks to @NancyLi1013

### CODE REVIEW

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
The failure on x64-linux:

```
-Wl,-rpath-link,/mnt/vcpkg-ci/installed/x64-linux/debug/lib && :
c++: error: /mnt/vcpkg-ci/installed/x64-linux/debug/lib//libglib-2.0.a: No such file or directory
c++: error: /mnt/vcpkg-ci/installed/x64-linux/debug/lib//libglib-2.0.a: No such file or directory
c++: error: /mnt/vcpkg-ci/installed/x64-linux/debug/lib//libglib-2.0.a: No such file or directory
```

**Review by ras0219 — APPROVED** [review]
This LGTM; it just needs a CI rerun. No action required from @venabled.

Thanks for the PR!

**Comment by ras0219-msft** [comment]
Thanks for the PR!

**Pull request merged**
