### PR TITLE
[msys2] Update msys components pkgconfig url

### LINKED ISSUE #15726: Package: zlib:x64-windows-static
**Host Environment**
- OS: Win10

**To Reproduce**
.\vcpkg install zlib:x64-windows-static

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
 Downloading https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz... Failed
-Please attach any additional failure logs mentioned in the console output.
I visit the https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz via IE browser,  the file is not existed.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

### PR DESCRIPTION
**Pull request by JackBoosY**
Fixes #15726.

### CODE REVIEW

**Comment by JackBoosY** [comment]
@wangweiwei1188  Can you please test this PR?

Thanks.

**Comment by wangweiwei1188** [comment]
> @wangweiwei1188 Can you please test this PR?
> 
> Thanks.

OK, I will do it.

**Review by wangweiwei1188 — APPROVED** [review]
it's well done.

**Comment by JackBoosY** [comment]
Waiting for #15740.

**Review by PhoebeHui — APPROVED** [review]

**Review by ras0219 — APPROVED** [review]
I have reviewed the changes[1] to the package and determined that this is an acceptable upgrade -- in the future, this is likely to need to move to a port for better version management.

However, I'm unable to repro the issue linked -- we have many different mirrors listed for a reason, and (for example) https://www2.futureware.at/~nickoe/msys2-mirror/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz succeeds for me.

[1] https://github.com/msys2/MSYS2-packages/commits/master/pkg-config

**Comment by JackBoosY** [comment]
@ras0219 You can remove _downloads/tools/msys2_ and rerpo this issue by installing `x264:x64-uwp`.

**Pull request merged**
