### PR TITLE
[Arrow] Update Arrow to 0.11.1

### PR DESCRIPTION
**Pull request by philjdf**
This updates Arrow from 0.9 to 0.11.1, and also builds Parquet.

[Parquet](https://github.com/apache/parquet-cpp) has recently been merged into the [Arrow](https://github.com/apache/arrow) Github repo, and is now built by passing a flag to the Arrow CMake script so that you additionally get Parquet as part of your Arrow build. I thought it simplest for this PR to mirror that and also build Parquet. I'm not sure if there's a better solution. It leaves the question of what to do with the deprecated Parquet port?

I've checked that this builds on Windows (x64-windows, x64-windows-static) and Linux (x64-linux).

### CODE REVIEW

**Comment by GPSnoopy** [comment]
Testing on Ubuntu 18.04 (via Windows 10 WSL), I get the following error. My gut feeling is that arrow build script is looking for the system zlib dev libraries (which I don't have installed) rather than looking correctly into vcpkg existing libraries (I can confirm libz.a is there).

INFOCompiler id: GNU
Selected compiler gcc 7.3.0
Using optional gold linker (version 1.15)
Configured for DEBUG build (set with cmake -DCMAKE_BUILD_TYPE={release,debug,...})
Added shared library dependency boost_system: /home/gpsnoopy/development/vcpkg/installed/x64-linux/debug/lib/libboost_system.a
Added shared library dependency boost_filesystem: /home/gpsnoopy/development/vcpkg/installed/x64-linux/debug/lib/libboost_filesystem.a
Added shared library dependency boost_regex: /home/gpsnoopy/development/vcpkg/installed/x64-linux/debug/lib/libboost_regex.a
Added static library dependency double-conversion: /home/gpsnoopy/development/vcpkg/buildtrees/arrow/x64-linux-dbg/double-conversion_ep/src/double-conversion_ep/lib/libdouble-conversion.a
**CMake Error at cmake_modules/FindZLIB.cmake:75 (message):
  Could not find the ZLIB library.  Looked in system search paths.**
Call Stack (most recent call first):
  /home/gpsnoopy/development/vcpkg/scripts/buildsystems/vcpkg.cmake:247 (_find_package)
  cmake_modules/ThirdpartyToolchain.cmake:787 (find_package)
  CMakeLists.txt:386 (include)

**Comment by philjdf** [comment]
@GPSnoopy The FindZLIB.cmake in the base Arrow 0.11.1 was looking for a .so. The latest commit fixes that, and it finds the vcpkg static version of zlib.

**Comment by philjdf** [comment]
Just tested again x64-linux, x64-windows, x64-windows-static, and they're all building.

**Comment by GPSnoopy** [comment]
@philjdf Build is still failing for me, but I think it's now just a missing boost dependency. Going to try to add it manually and see what happens.

Although it's not very clear to me if it's using Thrift to generate and compile some Arrow code or whether part of Arrow cmake file is still trying to build Thrift. I've highlighted below a couple of worrying lines.

CMake Error at /home/gpsnoopy/development/vcpkg/buildtrees/arrow/x64-linux-dbg/thrift_ep-prefix/src/thrift_ep-stamp/thrift_ep-build-DEBUG.cmake:16 (message):
  Command failed: 1

[68/119] Building CXX object lib/cpp/CMakeFiles/thrift.dir/src/thrift/concurrency/Mutex.cpp.o
FAILED: lib/cpp/CMakeFiles/thrift.dir/src/thrift/concurrency/Mutex.cpp.o
/usr/bin/c++  **-DBOOST_ALL_DYN_LINK** -DBOOST_TEST_DYN_LINK -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Dthrift_EXPORTS -Ilib/cpp -I/home/gpsnoopy/development/vcpkg/buildtrees/arrow/x64-linux-dbg/thrift_ep-prefix/src/thrift_ep/lib/cpp -I. -I/home/gpsnoopy/development/vcpkg/buildtrees/arrow/x64-linux-dbg/thrift_ep-prefix/src/thrift_ep/lib/cpp/src -isystem /home/gpsnoopy/development/vcpkg/installed/x64-linux/include -fPIC -fuse-ld=gold -ggdb -O0   -fPIC -Wno-variadic-macros -Wno-long-long -g -fPIC   -std=c++11 -MD -MT lib/cpp/CMakeFiles/thrift.dir/src/thrift/concurrency/Mutex.cpp.o -MF lib/cpp/CMakeFiles/thrift.dir/src/thrift/concurrency/Mutex.cpp.o.d -o lib/cpp/CMakeFiles/thrift.dir/src/thrift/concurrency/Mutex.cpp.o -c /home/gpsnoopy/development/vcpkg/buildtrees/arrow/x64-linux-dbg/thrift_ep-prefix/src/thrift_ep/lib/cpp/src/thrift/concurrency/Mutex.cpp
/home/gpsnoopy/development/vcpkg/buildtrees/arrow/x64-linux-dbg/thrift_ep-prefix/src/thrift_ep/lib/cpp/src/thrift/concurrency/Mutex.cpp:36:10: fatal error: boost/format.hpp: No such file or directory
 **#include <boost/format.hpp>**
          ^~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by GPSnoopy** [comment]
I can confirm that typing {{./vcpkg install boost-format:x64-linux}} fixes the build issue.

**Comment by Rastaban** [comment]
This change looks good so far, I'm just trying to decide what to do about the parquet port before completing the merge.

**Comment by GPSnoopy** [comment]
@Rastaban I think @philf has still a couple of bugs to fix before this can be merged in. For example, the build is pulling Thrift from the net instead of using the one from vcpkg (hence the mysterious boost format that had to be temporarily added). He's on holiday until new year. 

For the old parquet port, I think it's probably best to delete it once this PR is finished and merged in. It will not build correctly anymore and will only confuse people.

**Comment by philjdf** [comment]
@Rastaban I've pushed some changes which:

- Make sure we pick up the correct dependencies for Linux builds. For quite a few it was either picking up release libs for a debug build, or not finding them at all and then downloading and building them using ExternalProject_Add. These issues were because there wasn't a 'd' appended to the lib name, or the find_library call used the no default paths option.
- Remove Arrow CMake's ExternalProject_Add calls, so we'll get an error when a dependency is not found, rather than an attempt to download and build. This highlighted that glog and double-conversion were missing dependencies, now added in the portfile.

I'd be happy if you'd like to merge this now.

It's taken a bit of effort, which has made me think it would be great if the vcpkg documentation was more thorough, with some more complex examples of making a port and some best practices.

**Comment by GPSnoopy** [comment]
Looks good to me.

**Pull request merged**
