### PR TITLE
[portaudio] Added ASIO support to build

### PR DESCRIPTION
**Pull request by stekyne**
Adding ASIO support for portaudio. Requires downloading the ASIO SDK from the steinberg site and extracting it alongside the portaudio source before running cmake.

Not sure if there is a licensing issue with that? Maybe someone else knows..

### CODE REVIEW

**Comment by bagong** [comment]
I hope this can be added. The ASIO backend is the most important one for pro audio requirements. In fact though licensing is a grey area, Steinberg nominally makes redistribution dependent on a written agreement. Here each user will be downloading the SDK individually, so that should be fine, and yet - what can we do with the resulting libraries? ;) Steinberg did simplify access in the past by removing the requirement to obtain a developer account in order to download the SDK, and quite recently made a move towards open source by dual licensing the VST SDK, with one license being GPL now. Would be interesting to see how MS looks at this. Maybe Steinberg can be convinced to add a more permissive license to the ASIO SDK too? ;)
Ideally, ASIO support would be made optional in the portfile. Some users might want to chose not to redistribute with the backend. In the original cmake file of portaudio the ASIO backend is only built *if* the ASIO SDK is found.

**Comment by stekyne** [comment]
Yeah I'm not sure if it's allowed to be included like this. I was hoping someone else could give a definite answer.

I don't see how optional build features are possible but would be better of course, sure.

**Comment by ras0219-msft** [comment]
We don't have proper optional build feature support yet, but we are working on it.

For now, the best approach is to put comments in the CONTROL and portfile that explain how someone could manually alter the file to add support. For example, opencv[1].

As for the license,
> Steinberg nominally makes redistribution dependent on a written agreement.

According to the current (May 18, 2017) website,
>Please note that there are licensing agreements coupled with the use of development tools which you have to agree. These agreements contain conditions and/or requirements which are mostly concerned with liability issues. 
Please send the filled license agreement to the address that is given on the form, by mail or email it to info[SB]steinberg.de

It does look like they intend for the acquisition experience to not be made automatic. While that's quite unfortunately, we must follow the intentions of the author -- which in this case means we can't acquire the SDK for the user automatically.

It would be possible for us to fail the build the first time with a message that the user must download the SDK (and fill out the license) separately, then place it into our downloads\ folder. Then, they re-run the install and we can pick it up from there. However, due to the user-hostility of this approach, we _would_ need to make this an optional feature that requires editing the portfile to enable (until we get better in-tool support for optional features).

[1] https://github.com/Microsoft/vcpkg/blob/c5daa93506b616d253e257488ecc385271238e2a/ports/opencv/CONTROL

**Comment by bagong** [comment]
How about creating a prompt that asks the user (replace by some legally correct wording): "I am aware of Steinberg's requirements concerning the use of the ASIO-SDK (yes/no).

**Comment by bagong** [comment]
Note that in the current state you need to use tricks to build the ASIO backend *at all*. The ASIO-SDK find module relies on the SDK being available as a sibling-folder of the PA source. Yet that folder is only created during the vcpkg build process. That's a pretty serious limitation.

**Comment by bagong** [comment]
Last comment (it's a plan ;) ): at the very least I think the user should get feedback of the sort: "NOTE: in order to build with ASIO support, remove the portaudio build, copy the ASIOSDK into buildtrees/portaudio/src and build again" ;)

**Comment by ras0219-msft** [comment]
We avoid prompting in our user experience (except during the very first use) because prompting is quite hostile to automation/scripting. Even the limited prompting we have in our "first use" situations has caused a lot of user issues in systems like AppVeyor.

Instead, we generally prefer to print a descriptive message and ask the user to re-run the command with some additional argument.

In this case I don't think an additional argument is appropriate, but we could tell the user to uncomment something inside the portfile, drop some file in some location, or maybe set a variable in their triplet file. Then, on re-run, the portfile can detect that file/setting and do the right thing (nuke the src directory, etc).

I think it would make the most sense to actually have a completely separate src folder for the portaudio version (which would also make it very clean to switch back and forth).

**Comment by bagong** [comment]
@ras0219-msft , it is your decision if a) we need to force the user to manually download and extract the ASIO-SDK, or b) if - after the descriptive message was printed - (s)he only needs to do some editing in the build, and *then* the sdk will be downloaded automatically.

if a) : then I would suggest to print a descriptive message at the end of a default build that says something like: "If you would like to build with ASIO support, please download the SDK from Steinberg, place it next to the portaudio-folder in buildtrees/portaudio/src/, and rebuild". Note that it is a pecularity of the portaudio build system that it will build the ASIO backend *if* the ASIO-SDK is auto-detected (compare cmake_modules/FindASIOSDK.cmake). Setting PA_USE_ASIO=1 is not really required.

if b) then I think creating an option that can be edited is good. But atm this still has two disadvantages: the edit will turn up in `git status`, and it is quite possible that it gets accidentally committed at some point with `git add .`. Also the edit will cause a conflict on update of the pa port. It would actually be nice if there were a options file that was in .gitignore somewhere. But that isn't a show-stopper in my view, the main thing is that you decide which degree of convenience can be offered to the user in view of the peculiar licensing situation.

**Comment by ras0219-msft** [comment]
I think we should do a), but this should definitely be expressed as a non-default feature.

**Comment by bagong** [comment]
Are these additions accidental?

**Comment by stekyne** [comment]
Oops, yeah they were.

**Comment by TheStormN** [comment]
@ras0219-msft I think that the prompt option is the best with a command line argument to auto accept it. I've saw this in various Linux package managers especially when installing Oracle Java. It prompts you for the license agreement but you have **-y** option to auto accept it on your responsibility.

**Comment by stekyne** [comment]
Now that there is feature packages, can anything be done to resolve this? Otherwise, I'll probably just close it off.

**Pull request closed without merging**
