### PR TITLE
[libkml] new port

### PR DESCRIPTION
**Pull request by atkawa7**
New Port for #1369 . @ras0219-msft Requires applying to missing header minizip #1539

### CODE REVIEW

**Comment by Voskrese** [comment]
CMake Error - C2137
https://msdn.microsoft.com/ru-ru/library/fhxwbt0t.aspx?f=255&MSPPError=-2147217396

`edit vcpkg\buildtrees\libkml\src\libkml-1.3.0\src\kml\base\file_win32.cc`
45 str - no `''`, yes `' '` ;))
  `std::wstring wstr(str.length(), L'');` ->   `std::wstring wstr(str.length(), L' ');`

**Comment by atkawa7** [comment]
@Voskrese Forgot to add the fix for that. Thanks

**Comment by atkawa7** [comment]
@ras0219-msft Ready to merge

**Comment by ras0219-msft** [comment]
Thanks for the PR!

Could we instead copy their latest master implementation [1]? I'd feel a bit safer about it since I'm not sure what `L''` was _intended_ to do, so it's difficult to say whether `L' '` is the right fix.

[1] https://github.com/libkml/libkml/blob/916a801ed3143ab82c07ec108bad271aa441da16/src/kml/base/file_win32.cc#L46-L51

**Comment by ras0219-msft** [comment]
(Also, does it fail to build with Ninja? Otherwise, it'd be best to leave in the `PREFER_NINJA`!)

**Comment by atkawa7** [comment]
@ras0219-msft The master is fails to build because of tzname not found.
https://github.com/libkml/libkml/blob/master/src/kml/base/contrib/strptime.c#L392-L401

**Comment by ras0219-msft** [comment]
Thanks for the PR!

**Pull request merged**
