### PR TITLE
Set symbol visibility to hidden by default on macOS and Linux

### PR DESCRIPTION
**Pull request by kduske**
**Describe the pull request**

- #### What does your PR fix?

Fixes linker warnings when linking against libraries with inconsistent visibility settings (main project has symbols hidden, linked library has symbols visible).

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  osx, linux, no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Maybe -- I'll double check.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  I am still working on this PR

### CODE REVIEW

**Comment by kduske** [comment]
@Neumann-A There are a few failures that are due to libraries not exporting symbols. I'm not sure that the list is exhaustive because I don't know what the CI tests entail. Is there a test for each library where a program links against it?

Assuming that the list is complete, we could fix these libraries by changing their ports to set symbol visibility to default explicitly -- essentially the opposite of what I did for `poly2tri` [here](https://github.com/microsoft/vcpkg/pull/27263).

I did see some warnings about `CMP0063` not being set even though I set it in the toolchain files. I'd have to investigate why this happens.

There is one particularly nasty caveat however, and it has to do with different compilers merge `typeinfo` objects for multiple instances of identical types. I don't fully understand this and I'm probably using the wrong terms, but this stackoverflow question and the answers explain it quite well: https://stackoverflow.com/questions/19496643/using-clang-fvisibility-hidden-and-typeinfo-and-type-erasure

I have seen this problem in action and it can be very subtle and hard to diagnose. I worry that a lot of `vcpkg` users might run into this and will have to spend a lot of time diagnosing it if we just turn it on for every library. What do you think?

**Comment by Cheney-W** [comment]
Is work still being done for this PR?

**Comment by kduske** [comment]
@Cheney-W Not from my side. I'm not sure if @Neumann-A wants to follow up on this, though.

**Comment by Neumann-A** [comment]
Just close. Was worth a try ;)

**Pull request closed without merging**
