### PR TITLE
New package: Pixar USD

### PR DESCRIPTION
**Pull request by VictorYudin**
# Overview

This is a pull request to add a new package.
Name: usd
Version: 0.8.4
Description: Universal Scene Description (USD) is an efficient, scalable system for authoring, reading, and streaming time-sampled scene description for interchange between graphics applications.

# Patches

## bzip2
The bzip2 port produced a library with the name liblibbz2 in Linux and CMake wasn't able to find it. Fixed.

## boost
There was no support for shared libraries in Linux because the port copied only static libraries from the build directory. Fixed with specifying the stage build target and copying everything from the stage folder.

## TBB
There was no Linux support, and there were no static libs. Although it's not recommended to use static TBB, sometimes it's handy. TBB doesn't provide tools to build static lib, and a custom CMakeLists was added to the port. Unlike Windows TBB that is built with MSBuild, the Linux version uses GNU make.

## USD
It's a very minimal configuration.

# Testing

Built the port on the following triplets: `x64-windows`, `x64-windows-static`, `x64-osx`, `x64-linux`

### CODE REVIEW

**Comment by timlehr** [comment]
USD would be a fantastic addition, especially for Windows users. Any updates on this PR?

**Comment by cbezault** [comment]
I'm working on this PR next on my queue USD is awesome and would be a great addition to vcpkg.

**Comment by cbezault** [comment]
@VictorYudin, you might not still care but I'm going to go ahead and cherry-pick your commits to other ports so that this PR will be a clean USD PR.

**Comment by VictorYudin** [comment]
Hi @cbezault 

Nice to see you are interested in this PR. I did it a year ago and since then USD was updated multiple times. Now the version 0.8.4 is very old. I'm sorry Microsoft didn't merge this PR a year ago because I could support it and keep the USD version updated as I do it in my project [saturn](https://github.com/VictorYudin/saturn). If you are from Microsoft and you are able to merge it, I can work on it and update this MR to the latest version.

Best regards,
Victor

**Comment by cbezault** [comment]
@VictorYurin, I can just go ahead and bring USD to the newest version and finish out this PR. It looks like the changes you made to tbb, boost and bzip2 might no longer be necessary. We would really appreciate it if you "adopted" this port and kept it up to date with upstream.

**Pull request closed without merging**
