### PR TITLE
[WIP][Help Needed] Create x86-linux.cmake

### LINKED ISSUE #8917: How do I get x86-linux libraries?
When asking a question please also include where you looked for an answer (so we can update the documentation if needed).

### PR DESCRIPTION
**Pull request by talregev**
Create x86-linux.cmake
Fix #8917, #14812

### CODE REVIEW

**Comment by talregev** [comment]
Not sure how really add a x86-linux.
image

**Comment by talregev** [comment]
[config-x86-linux-rel-err.log](https://github.com/microsoft/vcpkg/files/6135474/config-x86-linux-rel-err.log)
[config-x86-linux-rel-out.log](https://github.com/microsoft/vcpkg/files/6135475/config-x86-linux-rel-out.log)

**Comment by talregev** [comment]
If someone can help and suggest what to do next, that will be great.

**Comment by talregev** [comment]
I install:
`sudo apt install gcc-multilib`
It solve half of the problem, because now it looking for `libstdc++` of 64 bit:
```c++
    /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/9/libstdc++.so when searching for -lstdc++
    /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/9/libstdc++.a when searching for -lstdc++
```

[config-x86-linux-rel-err.log](https://github.com/microsoft/vcpkg/files/6135524/config-x86-linux-rel-err.log)
[config-x86-linux-rel-out.log](https://github.com/microsoft/vcpkg/files/6135525/config-x86-linux-rel-out.log)


I try also to install:
`sudo apt install lib32stdc++-9-dev-x32-cross`
`sudo apt install libstdc++-9-dev-i386-cross`

It install other stdc++, but the compiler still choose the 64bit one (instead the 32)
image

**Comment by autoantwort** [comment]
May I ask why you want to build for 32 Bit Linux?

**Comment by autoantwort** [comment]
Maybe you can create a toolchain file like [here](https://stackoverflow.com/a/28047073/10162645) and add the line `
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE /path/to/toolchain/file.cmake)` to `triplets/community/x86-linux.cmake`

**Comment by talregev** [comment]
> May I ask why you want to build for 32 Bit Linux?

To compile with android x86.


> Maybe you can create a toolchain file like [here](https://stackoverflow.com/a/28047073/10162645) and add the line ` set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE /path/to/toolchain/file.cmake)` to `triplets/community/x86-linux.cmake`

Thank you for the suggestion! 
Where I need to put the toolchain file?

**Comment by autoantwort** [comment]
You can put the toolchain file wherever you want. Instead of `set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE /path/to/toolchain/file.cmake)` you can also set the environment variable `VCPKG_CHAINLOAD_TOOLCHAIN_FILE` to the path. For example
```sh
$ export VCPKG_CHAINLOAD_TOOLCHAIN_FILE=/path/to/toolchain/file.cmake
$ ./vcpkg install rappture:x86-linux
```

**Comment by JackBoosY** [comment]
```
    : && /usr/bin/cc -fPIC  -m32  CMakeFiles/cmTC_30b6a.dir/testCCompiler.c.o -o cmTC_30b6a   && :
    /usr/bin/ld: cannot find Scrt1.o: No such file or directory
    /usr/bin/ld: cannot find crti.o: No such file or directory
    /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/9/libgcc.a when searching for -lgcc
    /usr/bin/ld: cannot find -lgcc
    /usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libgcc_s.so.1 when searching for libgcc_s.so.1
    /usr/bin/ld: cannot find libgcc_s.so.1
    /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/9/libgcc.a when searching for -lgcc
    /usr/bin/ld: cannot find -lgcc
    collect2: error: ld returned 1 exit status
```

**Comment by talregev** [comment]
@JackBoosY 
> ```
>     : && /usr/bin/cc -fPIC  -m32  CMakeFiles/cmTC_30b6a.dir/testCCompiler.c.o -o cmTC_30b6a   && :
>     /usr/bin/ld: cannot find Scrt1.o: No such file or directory
>     /usr/bin/ld: cannot find crti.o: No such file or directory
>     /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/9/libgcc.a when searching for -lgcc
>     /usr/bin/ld: cannot find -lgcc
>     /usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libgcc_s.so.1 when searching for libgcc_s.so.1
>     /usr/bin/ld: cannot find libgcc_s.so.1
>     /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/9/libgcc.a when searching for -lgcc
>     /usr/bin/ld: cannot find -lgcc
>     collect2: error: ld returned 1 exit status
> ```

You need to install:
sudo apt install gcc-multilib

Then it will search for stdlib.

**Comment by JackBoosY** [comment]
After some attempts but failed in the end, I need the help of my colleague.

**Comment by talregev** [comment]
I am closing this PR.
I wanted to compile for android, and here the solution. 
I will make another PR to support armv6. 
https://vcpkg.readthedocs.io/en/latest/users/android/

**Pull request closed without merging**
