### PR TITLE
[libcanberra] new port

### PR DESCRIPTION
**Pull request by wrobelda**
**Describe the pull request**

   Adds new libcanberra port.
   Depends on:
   - [x] #19852 

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  Linux and macOS only.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

### CODE REVIEW

**Comment by wrobelda** [comment]
@PhoebeHui this currently rebuilds the world due to #19852, which this PR depends on.

**Comment by wrobelda** [comment]
@PhoebeHui this no longer has any dependencies, ready to be merged.

**Review by PhoebeHui — APPROVED** [review]
LGTM, thanks for your contribution!

**Comment by BillyONeal** [comment]
Thanks for the new port!

**Pull request merged**
