### PR TITLE
[rubberband] Update to 3.1.1

### PR DESCRIPTION
**Pull request by daschuer**
**Describe the pull request**

- #### What does your PR fix?
  Updates to the latest upstream release

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
 
No change 

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?

Yes 

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by FrankXie05** [comment]
@daschuer 
Error log from config-x64-osx-dbg-out.log.
https://dev.azure.com/vcpkg/public/_build/results?buildId=78973&view=artifacts&pathAsName=false&type=publishedArtifacts
````
../src/v3.1.0-883b0dd07c.clean/meson.build:139:2: ERROR: Unknown compiler "javac"
````
[config-x64-osx-dbg-out.log](https://github.com/microsoft/vcpkg/files/9750368/config-x64-osx-dbg-out.log)

**Comment by daschuer** [comment]
Homebrew has fixed it by installing openjdk:
https://github.com/Homebrew/homebrew-core/pull/112467

This is the Meson bug: 
https://github.com/mesonbuild/meson/issues/10900

**Comment by JoergAtGithub** [comment]
This issue is fixed upstream now! A new bugfix release 3.1.1 of Rubberband containing the fix for this issue is out:
https://github.com/breakfastquay/rubberband/releases/tag/v3.1.1

**Comment by FrankXie05** [comment]
@daschuer Now we can proceed with this PR. :)

**Review by FrankXie05 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks!

**Pull request merged**
