### PR TITLE
[proj,rtabmap] Update proj to 9.4.0

### PR DESCRIPTION
**Pull request by dg0yt**
Continued from #37121, CC @rhuijben 
Make rtabmap use stock CMake 3.14 (!) FindSQLite.cmake, fixing case sensitivity issues.

### CODE REVIEW

**Comment by LilyWangLL** [comment]
Thanks for your PR. There are the following warnings in installation of `proj[tools]`:
```
CMake Warning at scripts/cmake/vcpkg_copy_pdbs.cmake:44 (message):
  Could not find a matching pdb file for:

      F:/PRreview/vcpkg/packages/proj_x64-windows/bin/proj.dll

Call Stack (most recent call first):
  ports/proj/portfile.cmake:64 (vcpkg_copy_pdbs)
  scripts/ports.cmake:172 (include)
```
But I found there are the pdb files in `${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/dbg`, if just install `proj[core]`, pdb files will install normally.
image
image

**Comment by dg0yt** [comment]
Perhaps not a regression?
Note that the .exe and the .dll share the same base name.

**Comment by LilyWangLL** [comment]
Usage of `rtabmap` test passed on `x64-windows`.

**Comment by LilyWangLL** [comment]
> Perhaps not a regression? Note that the .exe and the .dll share the same base name.

Yes, the original `proj.pdb` was overwritten by the one generated by the tools. Is it possible to preserve the original `proj.pdb` by modifying the installation path of the following tool?
https://github.com/OSGeo/PROJ/blob/e99882b596cf073dfd0ef82b91ceb26913ff7397/src/apps/bin_proj.cmake#L9-L16
```
add_executable(binproj ${PROJ_SRC})
set_target_properties(binproj
  PROPERTIES
  RUNTIME_OUTPUT_NAME proj)
target_link_libraries(binproj PRIVATE ${PROJ_LIBRARIES})

install(TARGETS binproj
  DESTINATION ${CMAKE_INSTALL_BINDIR})
```

**Comment by dg0yt** [comment]
I don't want to add another change to this PR.
But I can suggest a change to upstream. Solved a similar situation in `freerdp`.

**Comment by Neumann-A** [comment]
Just use: https://cmake.org/cmake/help/latest/prop_tgt/PDB_NAME.html

**Comment by dg0yt** [comment]
> Just use: https://cmake.org/cmake/help/latest/prop_tgt/PDB_NAME.html

That is what I did in freerdp (`... PDB_NAME <TARGET_NAME>.exe`).
I still don't want to add a patch now.

**Comment by BillyONeal** [comment]
Confirming that unmodified builds result in:

```
Installing 5/8 proj[core,net,tiff,tools]:x64-windows@9.3.1...
Building proj[core,net,tiff,tools]:x64-windows@9.3.1...
-- Using cached OSGeo-PROJ-9.3.1.tar.gz.
-- Cleaning sources at D:/vcpkg/buildtrees/proj/src/9.3.1-d1be81ccd7.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/OSGeo-PROJ-9.3.1.tar.gz
-- Applying patch fix-win-output-name.patch
-- Applying patch fix-proj4-targets-cmake.patch
-- Applying patch remove_toolset_restriction.patch
-- Using source at D:/vcpkg/buildtrees/proj/src/9.3.1-d1be81ccd7.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Warning at scripts/cmake/vcpkg_copy_pdbs.cmake:44 (message):
  Could not find a matching pdb file for:

      D:/vcpkg/packages/proj_x64-windows/bin/proj.dll

Call Stack (most recent call first):
  ports/proj/portfile.cmake:64 (vcpkg_copy_pdbs)
  scripts/ports.cmake:175 (include)


-- Fixing pkgconfig file: D:/vcpkg/packages/proj_x64-windows/lib/pkgconfig/proj.pc
-- Using cached msys2-mingw-w64-x86_64-pkgconf-1~2.1.0-1-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.10-4-x86_64.pkg.tar.zst.
-- Using msys root at D:/vcpkg/downloads/tools/msys2/fdbea3694fb5c0d4
-- Fixing pkgconfig file: D:/vcpkg/packages/proj_x64-windows/debug/lib/pkgconfig/proj.pc
-- Installing: D:/vcpkg/packages/proj_x64-windows/share/proj/usage
-- Installing: D:/vcpkg/packages/proj_x64-windows/share/proj/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 2.6 s.
```

so I think this is OK to accept as is for now.

**Review by BillyONeal — APPROVED** [review]
This approval is subject to @LilyWangLL saying that she's convinced

**Review by LilyWangLL — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the updates!

**Pull request merged**
