### PR TITLE
[netcdf-c] Fix builds with hdf5[parallel]

### LINKED ISSUE #9696: [netcdf-c:x64-windows] build failure
**Host Environment**
Windows 10
- Compiler: VS2017

**To Reproduce**
netcdf-c:x64-windows --recurse

**Failure logs** 
.\vcpkg install netcdf-c:x64-windows --recurse
The following packages will be built and installed:
    netcdf-c[core]:x64-windows
Starting package 1/1: netcdf-c:x64-windows
Building package netcdf-c[core]:x64-windows...
-- Using cached C:/vcpkg_NEW/downloads/Unidata-netcdf-c-b7cd387bee8c661141fabb490f4969587c008c55.tar.gz
-- Using source at C:/vcpkg_NEW/buildtrees/netcdf-c/src/587c008c55-c804eaf515
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v
    Working Directory: C:/vcpkg_NEW/buildtrees/netcdf-c/x64-windows-dbg
    See logs for more information:
      C:\vcpkg_NEW\buildtrees\netcdf-c\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/netcdf-c/portfile.cmake:41 (vcpkg_install_cmake)
  scripts/ports.cmake:94 (include)

Error: Building package netcdf-c:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: netcdf-c:x64-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4064731/install-x64-windows-dbg-out.log)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

### PR DESCRIPTION
**Pull request by Neumann-A**
closes #9696 

CI will not test the correctness of these changes since hdf5[parallel] is not a tested feature.

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by davidbun** [comment]
The installation failed as follows:
==================
Building package netcdf-c[core]:x64-windows...
-- Using cached C:/vcpkg/downloads/Unidata-netcdf-c-b7cd387bee8c661141fabb490f4969587c008c55.tar.gz
-- Extracting source C:/vcpkg/downloads/Unidata-netcdf-c-b7cd387bee8c661141fabb490f4969587c008c55.tar.gz
-- Applying patch no-install-deps.patch
-- Applying patch config-pkg-location.patch
-- Applying patch use_targets.patch
-- Applying patch mpi.patch
CMake Error at scripts/cmake/vcpkg_apply_patches.cmake:52 (message):
  Applying patch failed.  Patch needs to be updated to work with source being
  used by vcpkg!
Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:134 (vcpkg_apply_patches)
  scripts/cmake/vcpkg_from_github.cmake:139 (vcpkg_extract_source_archive_ex)
  ports/netcdf-c/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:94 (include)


Error: Building package netcdf-c:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: netcdf-c:x64-windows
  Vcpkg version: 2020.01.17-nohash

**Comment by Neumann-A** [comment]
```
Starting package 98/263: netcdf-c:x64-windows
Building package netcdf-c[core]:x64-windows...
Could not locate cached archive: C:\vsts\_work\4\s\archives\53\53e853e0a855c9dbffc1e9599899d3dcf627cff0.zip
-- Using cached C:/vsts/_work/4/s/downloads/Unidata-netcdf-c-b7cd387bee8c661141fabb490f4969587c008c55.tar.gz
-- Extracting source C:/vsts/_work/4/s/downloads/Unidata-netcdf-c-b7cd387bee8c661141fabb490f4969587c008c55.tar.gz
-- Applying patch no-install-deps.patch
-- Applying patch config-pkg-location.patch
-- Applying patch use_targets.patch
-- Applying patch mpi.patch
-- Using source at C:/vsts/_work/4/s/buildtrees/netcdf-c/src/587c008c55-421483ada6
-- Configuring x64-windows-dbg
```
CI tells us that it works in every triplet so you need to attach the patch.logs from the buildtrees folder to get some kind help

**Comment by jasjuang** [comment]
I got the same exact error as reported by @davidbun, but I found the problem. You need an extra empty line at the end of the `mpi.patch` in order for it to work. If you are using editors that don't automatically append an empty line at the end when you save a file you will run into this problem. I know Sublime doesn't do it but vim does it. I am puzzled about why the CI will pass though, without the empty line it should fail. In any case, after applying this patch, I can confirm that `netcdf-c` finally builds successfully.

**Comment by Neumann-A** [comment]
Seems like git ate the last linebreak. The editor showed 14 lines file the changed files only showed 13 lines. There was also a warning about mixed line endings in the github editor

**Comment by davidbun** [comment]
Thx a lot @Neumann-A 
Now it works fine

**Pull request merged**
