### PR TITLE
Host deps for android image

### PR DESCRIPTION
**Pull request by dg0yt**
Background: #37196

### CODE REVIEW

**Comment by BillyONeal** [comment]
I'm tagging this with vm-update because we tend to update the docker containers at the same time as the VMs and I want to make sure when we do that for April we handle this at the latest.

However, we should be able to handle docker container changes more frequently.

**Comment by BillyONeal** [comment]
What are your thoughts on using docker for more things as a means of making our build environment(s) easier for folks to replicate?

My only hesitation is the recent backlash docker got over licensing mess...

**Comment by dg0yt** [comment]
I can't say much about docker.  
But I think that the same scripting should be used to host linux builds and android builds, so that even linux ABI hashes match for host dependencies.  
And since my last provisioning PR, I wonder if it is really time to move all those portfile messages about "system packages" to a script function, to display vendor specific install instructions, to select msys packages and to verify/generate CI image package lists.

**Review by BillyONeal — APPROVED** [review]

**Review by MonicaLiu0311 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Already merged, thank you!

**Comment by dg0yt** [comment]
Already using it, #37196 :heavy_check_mark:

**Pull request closed without merging**
