### PR TITLE
[aws-*]Update version

### PR DESCRIPTION
**Pull request by JackBoosY**
- aws-c-common upgrade to 0.4.15.
- aws-c-event-stream upgrade to 0.1.4.
- aws-checksums upgrade to 0.1.5
- aws-lambda-cpp upgrade to 0.2.4
- aws-sdk-cpp upgrade to 1.7.214

Since the official abandonment of OSX support, builds on OSX are disabled. See [#52](https://github.com/awslabs/aws-lambda-cpp/issues/52#issuecomment-516506872)

Related: #8792.

Note: all features test pass with following triplets:
- x86-windows
- x64-linux

### CODE REVIEW

**Comment by JackBoosY** [comment]
```
/Users/vagrant/azure_agent/_work/3/s/buildtrees/aws-lambda-cpp/src/62a5f7b606-c4ebf2d218/include/backward.h:188:22: fatal error: 'link.h' file not found
#            include <link.h>
                     ^~~~~~~~
```

Which went wrong with OSX?

**Review by PhoebeHui — APPROVED** [review]

**Review by dan-shaw — APPROVED** [review]

**Comment by PhoebeHui** [comment]
CI test failed: ##[error] REGRESSION: aws-lambda-cpp:x64-osx.

**Pull request merged**
