### PR TITLE
[cli11] Update to 1.9.1

### PR DESCRIPTION
**Pull request by BullyWiiPlaza**
**Describe the pull request**

- What does your PR fix? Fixes #
This fixes for instance compatibility with C++20 on Windows.

- Which triplets are supported/not supported? Have you updated the CI baseline?
Same as before.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes.

### CODE REVIEW

**Comment by LilyWangL** [comment]
Thanks for your PR! Can you please correct the Version field in the CONTROL file? You can get more information from [maintainer-guide.md](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md).

**Comment by BullyWiiPlaza** [comment]
@LilyWangL Sorry for that, I updated the version number in the `CONTROL` file as well now.

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
