### PR TITLE
[imgui] Add feature bindings and remove feature example

### PR DESCRIPTION
**Pull request by JackBoosY**
Since the binary generated by examples is rarely used, remove feature `examples` and add feature `bindings`.

Related: #10252 #8788.

Note: because the current feature tools still have generation problems, this PR only performs a simple separation feature.

All features passed in the following triplets test:
- x86-windows
- x64-windows
- x64-windows-static

### CODE REVIEW

**Comment by idcrook** [comment]
I found this issue while trying to resolve imgui install issue.

The header files and source files from imgui examples are used for bindings to call into imgui.  And they sometimes change with imgui versions. Alongside `examples` and `tools`, there should be "bindings" included with result artifacts so that they can be found within the package.

```shell
$ ls -1 examples/imgui_impl_opengl3.* examples/imgui_impl_glfw.*
examples/imgui_impl_glfw.cpp
examples/imgui_impl_glfw.h
examples/imgui_impl_opengl3.cpp
examples/imgui_impl_opengl3.h
```

There is no build or binary required from these, so it should be safe to always include in result.
so something resembling

```
    # Install bindings
    file(GLOB IMGUI_BINDINGS ${SOURCE_PATH}/examples/*.h ${SOURCE_PATH}/examples/*.cpp)
    file(INSTALL ${IMGUI_BINDINGS} DESTINATION ${CURRENT_PACKAGES_DIR}/resources)
```

I used `resources` there as a placeholder for `resources` or `bindings` or what have you.

**Comment by idcrook** [comment]
Note: for thesebindings to work, it also relies on `imgui_internal.h` being available
 - https://github.com/microsoft/vcpkg/issues/6665
 - https://github.com/microsoft/vcpkg/pull/9125

**Comment by idcrook** [comment]
I have an example branch off master that works for demonstrating a "bindings" feature

Under a new feature `[bindings]`:
 - copies `imgui_impl_*` to `bindings`
   - installing under `share` or `share/imgui`, etc. did not seem to "feel right"
 - installs "internal" headers needed for compilation usings these bindings to `include`

https://github.com/idcrook/vcpkg/tree/imgui-trials

i was able to test in a build where these bindings from a vcpkg install are used.

**Comment by JackBoosY** [comment]
@idcrook Already follow your suggestion, but I prefer to install it's code files to _include/bindings_.

**Comment by idcrook** [comment]
> @idcrook Already follow your suggestion, but I prefer to install it's code files to _include/bindings_.

looks good to me

**Comment by idcrook** [comment]
After looking over again, the build dependencies should be empty for “bindings” feature in the control file, as those are wrappers *into* imgui, and those files are part of imgui distribution.

If there is an “examples” feature still included, that would be where those build dependencies would probably go…

**Review by PhoebeHui — APPROVED** [review]
LGTM

**Comment by lerppana** [comment]
This feature is useless in a way that it forces dependencies of all possible bindings to project of the user. No one uses both gltf and sdl1, or if one just wants to get the binding files for dx bindings this feature forces depend on opengl too. Can you reconsider having a feature per binding.

**Comment by lerppana** [comment]
Just dropping in a suggestion here:
If user wants the official bindings for sdl for example, he gets all of these other frameworks in the same package. There is really no point in having glfw3, sdl and allegro linked in same project.

My suggestion, to make this feature usable, is to provide CMake variable for source root of the bindings folder so that user could choose a bindings to build with and add it to include directories. Or something similar.

**Comment by JackBoosY** [comment]
@lerppana All files in _buildtrees_ are temporary, we can only install the bindings source files in _installed_ and then use them.

**Comment by lerppana** [comment]
Yeah sorry for my messed up explanation. What I mean is as a port user to use binding source files from vcpkg installed folder in my projects build (better explained what I mean? 😄). So whatever this feature is, without build-depends (see what idcrooks comment)

**Comment by strega-nil** [comment]
This looks good to me :)

**Pull request merged**
