### PR TITLE
[xqilla] Add c++ runtime support for substring-before and substring-after

### PR DESCRIPTION
**Pull request by pierrebizz**
- [X ] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [X ] SHA512s are updated for each updated download.
- [ ] The "supports" clause reflects platforms that may be fixed by this new version.
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [ ] Any patches that are no longer applied are deleted from the port's directory.
- [X ] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [ X] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by Osyotr** [comment]
Upstream PR link?

**Comment by pierrebizz** [comment]
"Upstream PR link?" 
I don't understand what you mean...

**Comment by Osyotr** [comment]
Since it doesn't look like a build fix, these changes should be approved by library authors before being added as a patch to vcpkg.

**Comment by pierrebizz** [comment]
OK - xqilla is an abandonned or almost abandonned project that I myself added into vcpkg for convenience - my patch improves the performance of the xpath methods substring-before and substring-after

**Comment by dg0yt** [comment]
I'm not sure if the vcpkg repo is the right place to host this kind of improvement.

**Comment by pierrebizz** [comment]
The package is appropriately marked as vcpkg_cmake_config_fixup(PACKAGE_NAME unofficial-xqilla)

**Comment by dg0yt** [comment]
This is just labelling the cmake config package. IMO this is part of the porting effort (vcpkg), not of the develpoment effort (extermal).

**Comment by jimwang118** [comment]
Add reviewed tag for further review by the vcpkg team.

**Comment by JavierMatosD** [comment]
This kind of change needs to be made by upstream. Please open a PR against upstream.

**Comment by pierrebizz** [comment]
The problem is that there is no active upstream of this project - I was the one who packaged it for vcpkg - so others might use it - and I try to improve it by submitting patches

**Pull request closed without merging**
