### PR TITLE
[vcpkg_download_distfile] add FILE_DISAMBIGUATOR

### PR DESCRIPTION
**Pull request by strega-nil**
also, add HEADERS to the docs

As part of #22668, I noticed that this was necessary.

### CODE REVIEW

**Review by BillyONeal — CHANGES_REQUESTED** [review]
I don't *hate* doing this but I am weakly against given that `FILENAME` is something the user already owns here; other places that say `FILE_DISAMBIGUATOR` do so in cases that the infrastructure is choosing the name rather than the user. That means the user set `FILENAME` but don't actually get a file of that name, which seems.... strange.

If we keep this anyway at least the doc comment for the FILENAME parameter needs to be fixed to call out that actually depending on that name is now out of contract.

**Comment by Neumann-A** [comment]
Maybe `FILENAME` should really by a `FILENAME_PREFIX`

**Review by JackBoosY — APPROVED** [review]

**Comment by ras0219-msft** [comment]
I'm also against adding this -- the user can instead simply change the FILENAME. This is actually why we _have_ a filename argument instead of inferring it from the URL -- so that the user can use FILENAME to disambiguate with other possible downloads.

However, there's a more straightforward way to disambiguate this ~forever: subfolders based on SHA. We can use the first 2 or 4 characters of the SHA as a folder name under downloads.

**Comment by dg0yt** [comment]
> However, there's a more straightforward way to disambiguate this ~forever: subfolders based on SHA. We can use the first 2 or 4 characters of the SHA as a folder name under downloads.

Subfolders would make it harder harder to distribute the pristine sources as a separate collection of files, e.g. to satisfy GPL requirements. Today such a collection can be simply dropped into the downloads folder.

**Pull request closed without merging**
