### PR TITLE
[readline] add usage

### LINKED ISSUE #31425: [readline-(unix|win32)] Unify targets
### Is your feature request related to a problem? Please describe.

On Linux, there is no `readline` target installed by the vcpkg port, which is quite unusual. The way to get `readline` is to depend on `PkgConfig`, then call that to get a `PkgConfig::readline` target. This sucks.

On Windows, there is no `readline` target either. PkgConfig doesn't exist, obviously, so I'm not sure how to get the target at all.

### Proposed solution

On Linux and Windows, a `readline` target should exist, like for almost all other simple libraries like this.

### Describe alternatives you've considered

The alternative is to document what one is supposed to do on each platform, during the configuration step, like most other libraries do, too.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jimwang118**
Fixes https://github.com/microsoft/vcpkg/issues/31425
Add usage to port `readline`.
- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] ~~SHA512s are updated for each updated download~~
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

Usage test pass with following triplets:

```
x64-osx
x64-windows
x64-linux
```

### CODE REVIEW

**Comment by dg0yt** [comment]
Do you need to rebase the readline changes on `master`?

**Review by dg0yt — CHANGES_REQUESTED** [review]
You might advertize the unofficial config for windows, but your really should enable for windows, and promote, the official, uniform usage via `pkg-config`.

**Comment by jimwang118** [comment]
> You might advertize the unofficial config for windows, but your really should enable for windows, and promote, the official, uniform usage via `pkg-config`.

I did not find readline.pc in vcpkg and upstream readline, do I need to add a pc file for this port?

**Comment by dg0yt** [comment]
You many need to add or generate it for port `readline-win32`, the unmaintained fork of an outdated official readline version.
Port `readline-unix` is GNU readline and has `readline.pc.in`.

**Review by MonicaLiu0311 — APPROVED** [review]

**Pull request merged**
