### PR TITLE
[vcpkg baseline][monkeys-audio] Update to 565d.

### PR DESCRIPTION
**Pull request by Hoikas**
This fixes the monkeys-audio port, which was failing due to MAC_SDK_559c.zip being deleted from the remote server.

- What does your PR fix? See above

- Which triplets are supported/not supported? Have you updated the CI baseline?
No change.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

### CODE REVIEW

**Comment by JackBoosY** [comment]
vtk-m regression will be fixed in #14884.

**Comment by JackBoosY** [comment]
ping @BillyONeal for merge this PR quickly.

**Review by JackBoosY — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks!

**Pull request merged**
