### PR TITLE
[ffmpeg] avdevice CoreAudio dependency fix for osx

### PR DESCRIPTION
**Pull request by mcmtroffaes**
**Describe the pull request**

- What does your PR fix? The FindFFmpeg cmake script is missing a dependency for ffmpeg on osx when compiled with the avdevice feature, resulting in link errors (see for instance https://travis-ci.com/github/mcmtroffaes/ffmpeg-msvc-build/jobs/497488666#L282). I've confirmed the required dependency from the ffmpeg configure script: https://github.com/FFmpeg/FFmpeg/blob/36a5ae619a7d255c27f66a343a7861108d789159/configure#L3405

- Which triplets are supported/not supported? Have you updated the CI baseline? No changes.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)? To the best of my knowledge, yes.

### CODE REVIEW

**Comment by NancyLi1013** [comment]
Please run `vcpkg x-add-version ffmpeg `to solve the failures on x86-windows.

**Comment by mcmtroffaes** [comment]
Thanks. I've reran x-add-version for ffmpeg (not sure what went wrong on the previous iteration...), hopefully should be good now.

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
LGTM now, thanks for your fix @mcmtroffaes.

**Comment by mcmtroffaes** [comment]
Tried to bump the port version but something might have gone wrong with the git-tree version... Will do clean rebase, hang on.

**Comment by autoantwort** [comment]
@mcmtroffaes there was another ffmpeg PR that was merged before this PR, you have to rebase again :)

**Comment by NancyLi1013** [comment]
@mcmtroffaes Could you please rebase to solve the conflicts?

**Comment by mcmtroffaes** [comment]
I've rebased it just now. Should be good to go again.

**Comment by mcmtroffaes** [comment]
Rebased to resolve conflicts.

**Comment by mcmtroffaes** [comment]
Rebased & conflicts resolved.

**Comment by mcmtroffaes** [comment]
Rebased and resolved conflicts.

**Comment by dan-shaw** [comment]
@mcmtroffaes Could you rebase again? I merged your other PR first since it was passing CI.

**Comment by mcmtroffaes** [comment]
Sure, rebased again. CI should pass... 🤞

**Comment by strega-nil-ms** [comment]
@mcmtroffaes you'll need to remerge with latest I'm so sorry haha

**Comment by mcmtroffaes** [comment]
That's alright, merged once again.

**Comment by strega-nil-ms** [comment]
@mcmtroffaes thanks so much!

**Pull request merged**
