### PR TITLE
[libogg] Update to 1.3.3-3

### PR DESCRIPTION
**Pull request by evpobr**
* No patches required (merged in upstream)

Notes:

Target name changed: Ogg::Ogg -> Ogg::ogg (official).

```
PS D:\vcpkg> vcpkg install libogg
The following packages will be built and installed:
    libogg[core]:x64-windows
Starting package 1/1: libogg:x64-windows
Building package libogg[core]:x64-windows...
-- Using cached D:/vcpkg/downloads/xiph-ogg-6ccfcc2dce48c0d430b45064d0e13c962a64c42f.tar.gz
-- Using source at D:/vcpkg/buildtrees/libogg/src/962a64c42f-3bdf14dc8f
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: D:/vcpkg/packages/libogg_x64-windows/share/libogg/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package libogg[core]:x64-windows... done
Installing package libogg[core]:x64-windows...
Installing package libogg[core]:x64-windows... done
Elapsed time for package libogg:x64-windows: 22.23 s

Total elapsed time: 22.23 s

The package libogg:x64-windows provides CMake targets:

    find_package(ogg CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Ogg::ogg)
```

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for the PR!

@Rastaban We should consider adding a wrapper that aliases the old name to the new name

**Comment by Rastaban** [comment]
Failing on Mac/Linux due to case sensitive file system.  The call to `vcpkg_fixup_cmake_targets` needs updated

```
CMake Error at scripts/cmake/vcpkg_fixup_cmake_targets.cmake:45 (message):
  
  '/Users/vagrant/azure_agent/_work/3/s/packages/libogg_x64-osx/debug/lib/cmake/Ogg'
  does not exist.
Call Stack (most recent call first):
  ports/libogg/portfile.cmake:19 (vcpkg_fixup_cmake_targets)
  scripts/ports.cmake:71 (include)
```

**Comment by Rastaban** [comment]
This looks good, the only failure is a known 'flaky' port (which has already been addressed in the latest master) and is unrelated to this PR.

**Pull request merged**
