### PR TITLE
[wxwidgets] Fix include path in UNIX

### LINKED ISSUE #16338: [wxWidgets] failure to compile application on MacOS - it seems to be using Windows include file on MacOS.
**Describe the bug**
When trying to compile and link my application with wxWidgets on MacOS Big Sur I get a compiler error indicating that it can't find '../../lib/mswu/wx/setup.h' file.

**Environment**
- OS: MacOS Big Sur
- Compiler: Apple clang version 12.0.0 (clang-1200.0.32.29)

**To Reproduce**
Compile and link application with wxWidgets on MacOS using CMAKE 3.19.5.

*** Notice in the below error log that it seems to be trying to use the WINDOWS include files!
(../../lib/mswu/wx/setup.h)

**Expected behavior**
It should not be trying to use the WINDOWS include files on MACOS.

I believe this may have broken when issue #16154 was implemented a few days ago as it looks like that commit added the include for the WINDOWS version of the include file setup.h.

**Failure logs** 
In file included from /Users/david/projects/favor/src/favor/favor_app.cpp:13:
In file included from /Users/david/.local/share/pmm/1.5.1/vcpkg-master/packages/wxwidgets_x64-osx/include/wx-3.1/wx/wxprec.h:12:
In file included from /Users/david/.local/share/pmm/1.5.1/vcpkg-master/packages/wxwidgets_x64-osx/include/wx-3.1/wx/defs.h:45:
In file included from /Users/david/.local/share/pmm/1.5.1/vcpkg-master/packages/wxwidgets_x64-osx/include/wx-3.1/wx/platform.h:160:
/Users/david/.local/share/pmm/1.5.1/vcpkg-master/installed/x64-osx/include/wx/setup.h:4:10: fatal error: '../../lib/mswu/wx/setup.h' file not found
#include "../../lib/mswu/wx/setup.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

### PR DESCRIPTION
**Pull request by JackBoosY**
The `setup.h` content in UNIX is incorrect:
```
#ifdef _DEBUG
#include "../../debug/lib/mswud/wx/setup.h"
#else
#include "../../lib/mswu/wx/setup.h"
#endif
```
it should be _VCPKG_ROOT/installed/TRIPLET/lib/wx/include/osx_cocoa-unicode-static-3.1/wx/setup.h_ and _VCPKG_ROOT/installed/TRIPLET/debug/lib/wx/include/osx_cocoa-unicode-static-3.1/wx/setup.h_.

Fixes #16338.

### CODE REVIEW

**Comment by JackBoosY** [comment]
@davidsummers  Can you please test this PR?
@AenBleidd Can you please review this PR?

Thanks.

**Comment by AenBleidd** [comment]
@JackBoosY, sure, I'll do this within next 24 hours

**Comment by AenBleidd** [comment]
@JackBoosY, LGTM. Thanks for the fix.

**Review by PhoebeHui — APPROVED** [review]
LGTM

**Comment by davidsummers** [comment]
> @davidsummers Can you please test this PR?
> @AenBleidd Can you please review this PR?
> 
> Thanks.

Sure, I would be glad to!

Thanks!

I'll report back here in a while.

**Comment by JackBoosY** [comment]
@davidsummers Any progress?

**Pull request merged**
