### PR TITLE
[winsock2,usocket] Fix mingw build

### LINKED ISSUE #25076: `x64-mingw-dynamic` triplet cannot find WindowsSDKVersion/WindowsSdkDir in environment
**Problem**
I was trying to build `uwebsockets` for `x64-mingw-dynamic` triplet, since MSYS2 doesn't have `uwebsockets` library. I couldn't build it because `usockets` (which `uwebsockets` uses) needs to link with `ws2_32`. So I need to install `usockets` with `network` feature which will link `usockets` to `ws2_32`. This `network` feature requires `winsock2` library, which calls `vcpkg_get_windows_sdk` that needs `$ENV{WindowsSDKVersion}`, and `winsock2` ifself also needs `$ENV{WindowsSdkDir}` but vcpkg can't find any of `WindowsSDKVersion` or `WindowsSdkDir`. I did call `vcvars64.bat` to populate environment variables and check that my env has `WindowsSDKVersion` and `WindowsSdkDir`, but vcpkg cannot find them.

**Proposed solution**
Add `WindowsSDKVersion` and `WindowsSdkDir` to `VCPKG_ENV_PASSTHROUGH` in `x64-mingw-dynamic` triplet, and maybe to all of mingw triplets.
```cmake
set(VCPKG_ENV_PASSTHROUGH PATH WindowsSDKVersion WindowsSdkDir)
```

**Additional questions**
Can mingw triplets passthrough all environment variables? My proposed  solution looks like a quick fix than a permanent solution. ~~Also I have to call `vcvars...` beforehand to populate all those env vars, while `x64-windows` triplet gets them without calling `vcvars...`. Can mingw triplets do that?~~ Edit: I don't have to call vcvars.

### PR DESCRIPTION
**Pull request by dg0yt**
- #### What does your PR fix?
  Fixes https://github.com/microsoft/vcpkg/issues/25076.
  (`usockets` deserves more changes w.r.t. features and dependencies, but this is out of scope for this minimal PR. And I really don't understand the purpose of `winsock`.)

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  all, no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  yes

### CODE REVIEW

**Comment by ras0219-msft** [comment]
The purpose of `winsock` and `opengl` is:
1. To document the dependency
2. To copy non-default libraries from the selected Windows SDK into the vcpkg installed folder where they will be automatically linked by `lib/*.lib`.

Unless there's another reason why it shouldn't work, I think it would be better to fix the casing in the `winsock` port instead of making it empty for MinGW.

**Comment by dg0yt** [comment]
> I think we actually need to fix `vcpkg_get_windows_sdk()` for MinGW. How do MinGW programs link with kernel32, ws2_32, etc? Do they rely on CFLAGS containing the include paths for a Windows SDK?

The point of mingw is to not need a Windows SDK. MinGW provides own link libraries to satisfy these linking requirements, in the (gcc, clang) compiler's implicit link library directories.

Example:
https://packages.ubuntu.com/jammy/all/mingw-w64-x86-64-dev/filelist

**Comment by dg0yt** [comment]
Is ws2_32 a "non-default" library? It is used by many ports without depending on `winsock2`. In fact, `usockets` is the only port which  depends on `winsock2`.

**Comment by dg0yt** [comment]
Ping. Three weeks since last comment. You shouldn't just toggle labels, but actually post comments to keep your contributors informed and motivated.

**Comment by dg0yt** [comment]
Merged master. Now waiting for answers since more than one month :angry:

**Review by vicroms — APPROVED** [review]
I find these changes OK in view of these comments:

> The point of mingw is to not need a Windows SDK. MinGW provides own link libraries to satisfy these linking requirements, in the (gcc, clang) compiler's implicit link library directories.

What about marking the winsock2 dependency with `"platform": "windows & !mingw"`?

**Comment by dg0yt** [comment]
> What about marking the winsock2 dependency with `"platform": "windows & !mingw"`?

It won't stop people from adding an unguarded winsock2 dependency to other ports, breaking mingw.
(Again, many ports use ws2_32, but only one port depends on port winsock2.)

**Comment by longnguyen2004** [comment]
I also don't understand the purpose of the `winsock2` port. It's not an external dependency in the same way as something like `zlib`. Everyone working with sockets already knows how to link to it. Why the extra port?

**Comment by BillyONeal** [comment]
> I also don't understand the purpose of the `winsock2` port.

I agree.

> The purpose of `winsock` and `opengl` is:
> 
> 1. To document the dependency

OK, but we don't do this for any other libraries that come out of the Windows SDK. There's no kernel32 port.

> 2. To copy non-default libraries from the selected Windows SDK into the vcpkg installed folder where they will be automatically linked by `lib/*.lib`.

What is non-default about this? It comes in the Windows SDK. You get this and kernel32 or you get neither.

> Unless there's another reason why it shouldn't work, I think it would be better to fix the casing in the `winsock` port instead of making it empty for MinGW.

It also breaks binary caching.

**Comment by dg0yt** [comment]
Ping. Waiting for merge or feedback.

**Pull request merged**
