### PR TITLE
Move arm64-osx triplet from community to main triplets

### PR DESCRIPTION
**Pull request by omartijn**
**Describe the pull request**

The idea is to make arm64-osx a fully-supported and tested triplet. Since this architecture is so common, there's really no reason for this to be a community triplet

- #### What does your PR fix?  
Make arm64-osx a regular trtiplet.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
arm64-osx was already sort-of supported. But it still produced a warning and none of the ports were tested in the CI. This should be fixed.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
No changes yet, but if the CI works I'll expect changes to be required.

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by omartijn** [comment]
@JackBoosY Can you tell me what I have to do to get this new triplet part of the Azure Pipeline? It looks like it's not controlled from `.github/workflows` but elsewhere.

**Comment by BillyONeal** [comment]
This is more a "have the hardware and funding to do it" thing rather than a "process to ask for approval" thing, since taking it out of community status means we need to be testing it.

**Comment by omartijn** [comment]
@BillyONeal Can you be a bit more specific what you mean? Do you mean that there's active testing being done on the binaries _besides the build test done in the CI pipeline_?

I'm asking because it's perfectly possible to do an arm64 build on an Intel machine. You just can't execute the resulting binary on that platform. When you talk about funding are you talking about the extra CPU-time it takes to do these extra builds or do you mean something else entirely?

**Comment by BillyONeal** [comment]
> @BillyONeal Can you be a bit more specific what you mean? Do you mean that there's active testing being done on the binaries _besides the build test done in the CI pipeline_?

I mean, turning it on in the CI pipeline requires budget for the hardware to run that part of the CI pipeline (that we don't currently have), so this isn't something that can come from a contributor.

**Comment by JackBoosY** [comment]
We need to convert `arm64-osx` to the official triplet as soon as possible because the new generation of mac machines starts to use the arm architecture.

**Comment by omartijn** [comment]
I think we also should add a triplet for a universal build. Something called `universal-osx` or some such, which should probably also be a supported. This is the chosen way of releasing macOS builds supporting arm64 for most, since it doesn't require users to think and choose which architecture they're running on.

From what I understand, somebody has to agree to up the number of machines dedicated to the Azure Pipelines so we can run these builds without the CI becoming too slow (and then having builds pile up). Is there any way I can help speed up this decision? Somebody I can email or something? Or is this something you'll have to do purely internally?

**Comment by cenit** [comment]
what about converting the supported triplet from x64-osx to universal-osx, since as @omartijn says this is the most common "architecture" now on osx?

**Comment by cenit** [comment]
this should come "for free", because we are not adding any triplet, just changing the CI target

**Comment by BillyONeal** [comment]
> We need to convert `arm64-osx` to the official triplet as soon as possible because the new generation of mac machines starts to use the arm architecture.

I agree, but I don't set our budgets.

> From what I understand, somebody has to agree to up the number of machines dedicated to the Azure Pipelines so we can run these builds without the CI becoming too slow (and then having builds pile up). Is there any way I can help speed up this decision? Somebody I can email or something? Or is this something you'll have to do purely internally?

As far as I am aware it's entirely an internal thing, and unlikely to happen soon. Budget decisions like this are *typically* reevaluated in June of each year and applied a few months after that. We are presently already over budget.

> what about converting the supported triplet from x64-osx to universal-osx, since as @omartijn says this is the most common "architecture" now on osx?

That sounds like something that should be easier to do although that still results in double the compute to build multiple ways right?

**Comment by cenit** [comment]
> Maybe `universal-osx` should become a release-only triplet in CI at the same time ;-)

good idea

**Comment by BillyONeal** [comment]
We got some m1 macs to do this testing; unfortunately the virtualization solution we use to make recycling the build fleet itself can't currently handle these :(

**Comment by cenit** [comment]
isn't vagrant+parallels fully m1 compatible?

**Comment by omartijn** [comment]
> We got some m1 macs to do this testing; unfortunately the virtualization solution we use to make recycling the build fleet itself can't currently handle these :(

Good to hear that you've got some new machines to do testing! I'm not quite sure what you mean with the "recycling the build fleet" and what exactly you use that isn't compatible. Is the issue that whatever agent Azure runs on machines isn't compatible? Why couldn't it run through Rosetta2?

**Comment by BillyONeal** [comment]
> isn't vagrant+parallels fully m1 compatible?

No.

> Good to hear that you've got some new machines to do testing! I'm not quite sure what you mean with the "recycling the build fleet"

I mean the instance of macos. If someone submits us a malicious PR (like a MacOS equivalent of https://github.com/BillyONeal/temp-vmss-demo/pull/1/) we need to be able to nuke/pave all the machines in the fleet quickly. For non-MacOS, we get this by virtue of our fleet being Azure stuff for "free". For MacOS, today we get this via Vagrant and Parallels. But that combo doesn't work on the M1 yet.

**Comment by LilyWangLL** [comment]
Ping @omartijn for response. Is work still being done for this PR? Could you please resolve the conflicts?

**Comment by BillyONeal** [comment]
> Ping @omartijn for response. Is work still being done for this PR? Could you please resolve the conflicts?

I don't think there's anything @omartijn can do about this; this is blocked by lack of available hardware to run such tests.

**Comment by dan-shaw** [comment]
Closing PR for now, see above comment

**Pull request closed without merging**
