### PR TITLE
[simdjson] Update to 0.5.x

### PR DESCRIPTION
**Pull request by myd7349**
**Describe the pull request**

- What does your PR fix?
N/A.

- Which triplets are supported/not supported? Have you updated the CI baseline?
N/A. No.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes.

### CODE REVIEW

**Comment by JackBoosY** [comment]
Ready for review?

**Review by BillyONeal — APPROVED** [review]

**Comment by myd7349** [comment]
> 
> 
> Ready for review?

Yes. Please.

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
LGTM, waiting for test complete.

**Comment by JackBoosY** [comment]
```
ninja: error: 'D:/installed/x64-windows-static/debug/lib/openblas.lib', needed by 'test/ceres/test_ceres_se3.exe', missing and no known rule to make it
```

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
