### PR TITLE
[llvm] test baseline

### PR DESCRIPTION
**Pull request by autoantwort**
Test if #28415 is a baseline regression

### CODE REVIEW

**Comment by Neumann-A** [comment]
What is the error? There is one issue which is caused by CMake 3.25.0 and will be fixed by 3.25.1

**Comment by Neumann-A** [comment]
> D:\downloads\tools\perl\5.32.1.1\c\lib\libxml2.a : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64'

That error is due to CMake 3.25.0

**Comment by autoantwort** [comment]
Yeah and 
```
FAILED: bin/liblldb.dll lib/liblldb.lib 
cmd.exe /C "cd . && D:\downloads\tools\cmake-3.25.0-windows\cmake-3.25.0-windows-i386\bin\cmake.exe -E vs_link_dll --intdir=tools\lldb\source\API\CMakeFiles\liblldb.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MICROS~1\2022\ENTERP~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\link.exe  @CMakeFiles\liblldb.rsp  /out:bin\liblldb.dll /implib:lib\liblldb.lib /pdb:bin\liblldb.pdb /dll /version:14.0 /machine:x64 /nologo    /debug /INCREMENTAL  && cd ."
LINK Pass 1: command "C:\PROGRA~1\MICROS~1\2022\ENTERP~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\link.exe @CMakeFiles\liblldb.rsp /out:bin\liblldb.dll /implib:lib\liblldb.lib /pdb:bin\liblldb.pdb /dll /version:14.0 /machine:x64 /nologo /debug /INCREMENTAL /MANIFEST /MANIFESTFILE:tools\lldb\source\API\CMakeFiles\liblldb.dir/intermediate.manifest tools\lldb\source\API\CMakeFiles\liblldb.dir/manifest.res" failed (exit code 1120) with the following output:
   Creating library lib\liblldb.lib and object lib\liblldb.exp
lldbHost.lib(XML.cpp.obj) : error LNK2019: unresolved external symbol xmlFreeDoc referenced in function "public: void __cdecl lldb_private::XMLDocument::Clear(void)" (?Clear@XMLDocument@lldb_private@@QEAAXXZ)
lldbHost.lib(XML.cpp.obj) : error LNK2019: unresolved external symbol xmlDocGetRootElement referenced in function "public: class lldb_private::XMLNode __cdecl lldb_private::XMLDocument::GetRootElement(char const *)" (?GetRootElement@XMLDocument@lldb_private@@QEAA?AVXMLNode@2@PEBD@Z)
lldbHost.lib(XML.cpp.obj) : error LNK2019: unresolved external symbol xmlGetProp referenced in function "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl lldb_private::XMLNode::GetAttributeValue(char const *,char const *)const " (?GetAttributeValue@XMLNode@lldb_private@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEBD0@Z)
lldbHost.lib(XML.cpp.obj) : error LNK2019: unresolved external symbol xmlSetGenericErrorFunc referenced in function "public: bool __cdecl lldb_private::XMLDocument::ParseFile(char const *)" (?ParseFile@XMLDocument@lldb_private@@QEAA_NPEBD@Z)
lldbHost.lib(XML.cpp.obj) : error LNK2019: unresolved external symbol xmlParseFile referenced in function "public: bool __cdecl lldb_private::XMLDocument::ParseFile(char const *)" (?ParseFile@XMLDocument@lldb_private@@QEAA_NPEBD@Z)
lldbHost.lib(XML.cpp.obj) : error LNK2019: unresolved external symbol xmlReadMemory referenced in function "public: bool __cdecl lldb_private::XMLDocument::ParseMemory(char const *,unsigned __int64,char const *)" (?ParseMemory@XMLDocument@lldb_private@@QEAA_NPEBD_K0@Z)
lldbHost.lib(XML.cpp.obj) : error LNK2019: unresolved external symbol __imp_xmlFree referenced in function "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl lldb_private::XMLNode::GetAttributeValue(char const *,char const *)const " (?GetAttributeValue@XMLNode@lldb_private@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEBD0@Z)
```

**Comment by Neumann-A** [comment]
If it is trying to link the wrong `libxml` I would assume those errors are related to that. Especially since x86 symbols are prefixed with `_`

**Comment by autoantwort** [comment]
Thank you for the hint :)

**Comment by autoantwort** [comment]
The failures in #28415 are a baseline regression :)

**Pull request closed without merging**
