### PR TITLE
[lz4, flann] port patches from #5169

### PR DESCRIPTION
**Pull request by cenit**

### CODE REVIEW

**Comment by NancyLi1013** [comment]
Hi @cenit, here are some regressions from the current system:

|x64-windows|master| test |notes
|-----------|------|------|-----
|flann      |Pass  |Fail  |**Regression**

|x64-windows-static|master| test |notes
|------------------|------|------|-----
|pcl               |Pass  |Fail  |**Regression**

|arm64-windows|master| test |notes
|-------------|------|------|-----
|flann        |Pass  |Fail  |**Regression**

|x86-windows|master| test |notes
|-----------|------|------|-----
|flann      |Pass  |Fail  |**Regression**

|x64-uwp|master| test |notes
|-------|------|------|-----
|flann  |Pass  |Fail  |**Regression**

|arm-uwp|master| test |notes
|-------|------|------|-----
|flann  |Pass  |Fail  |**Regression**

[failureLogs.zip](https://github.com/Microsoft/vcpkg/files/3145196/failureLogs.zip)

**Comment by vicroms** [comment]
Hi @cenit 

These are the latest [failure logs](https://github.com/microsoft/vcpkg/files/3164430/failureLogs.zip)

|x64-windows|master| test |notes
|-----------|------|------|-----
|openmvg    |Pass  |Fail  |**Regression**

|x64-windows-static|master| test |notes
|------------------|------|------|-----
|pcl               |Pass  |Fail  |**Regression**

|x86-windows|master| test |notes
|-----------|------|------|-----
|pcl        |Pass  |Fail  |**Regression**
|openmvg    |Pass  |Fail  |**Regression**

On the bright side, `flann` now works for 64-bit Linux

|x64-linux|master| test |notes
|---------|------|------|-----
|flann    |Fail  |Pass  |

**Comment by cenit** [comment]
@vicroms any update here? Is only pcl broken now? (Already saw some necessary fix for it)

**Comment by vicroms** [comment]
Good guess, `pcl` is the only regression left.

[Failure Logs](https://github.com/microsoft/vcpkg/files/3179660/pcl-failure-logs.zip)


|x86-windows|master| test |notes
|-----------|------|------|-----
|pcl        |Pass  |Fail  |**Regression**

**Comment by cenit** [comment]
It should fail everywhere... not just x86-windows. By thanks!

(Maybe it is regressing only on x86-windows, which was building ok somehow...)

**Comment by cenit** [comment]
@vicroms I need the logs whenever you have time. I am able to build pcl locally, so I need an update on regressions.

**Comment by vicroms** [comment]
Hi @cenit

Sorry for the delay, I thought I had replied to this PR :S 

[Failure logs](https://github.com/microsoft/vcpkg/files/3193106/pcl-failureLogs.zip)


Current status: 

- `flann` works on Linux now, and 
- `pcl` is getting skipped on all platforms except `x86-windows` and `x64-windows-static`.

I'll take a look at `pcl`'s dependencies to find which are causing the build to be skipped.

**Comment by cenit** [comment]
green check 😃

**Comment by ras0219-msft** [comment]
@vicroms It looks like qhull is preventing pcl from being built for x64-windows:
```
qhull:x64-windows:       fail: 405172dc5986a116b31314fefd7ed4ffcac63810
```

**Comment by vicroms** [comment]
Thanks @cenit

Looks like everything has been sorted out in this PR.

**Pull request merged**
