### PR TITLE
[openal-soft] Update to 1.24.0

### PR DESCRIPTION
**Pull request by dpogue**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [x] The "supports" clause reflects platforms that may be fixed by this new version.
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by Cheney-W** [comment]
The downstream `libmikmod` is now failing to install due to the following issue:
libmikmod:x64-windows-static
libmikmod:x64-windows-static-md
```
OpenAL32.lib(wasapi.cpp.obj) : error LNK2019: unresolved external symbol __imp_AvSetMmThreadCharacteristicsW referenced in function "public: int __cdecl `anonymous namespace'::WasapiPlayback::mixerProc(void)" (?mixerProc@WasapiPlayback@?A0x0844112c@@QEAAHXZ)
OpenAL32.lib(wasapi.cpp.obj) : error LNK2019: unresolved external symbol __imp_AvRevertMmThreadCharacteristics referenced in function "public: void __cdecl `anonymous namespace'::AvrtHandleCloser::operator()(void *)" (??RAvrtHandleCloser@?A0x0844112c@@QEAAXPEAX@Z)
mikmod.dll : fatal error LNK1120: 2 unresolved externals
```
The downstream `sfml` is now failing to install due to the following issue:
sfml:x64-osx
sfml:arm64-osx
```
/Users/vcpkg/Data/installed/x64-osx/include/AL/al.h:478:53: error: expected function body after function declarator
AL_API void AL_APIENTRY alEnable(ALenum capability) AL_API_NOEXCEPT;
```
More logs you could get from https://dev.azure.com/vcpkg/public/_build/results?buildId=109407&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by dpogue** [comment]
Thanks Cheney.

The windows-static ones seem to be due to openal-soft's WASAPI backend now requiring linking against avrt, and that dependency doesn't get communicated properly in static builds. Patching libmikmod would probably fix it, but that doesn't seem like the ideal approach.

I'm not sure what's causing the issues on macOS, since sfml also has code that uses `noexcept` and that's not causing issues 😕

**Comment by dg0yt** [comment]
> The windows-static ones seem to be due to openal-soft's WASAPI backend now requiring linking against avrt, and that dependency doesn't get communicated properly in static builds. Patching libmikmod would probably fix it, but that doesn't seem like the ideal approach.

Add the missing link libs to the installed pc files (`openal.pc`). Ask if you need more information.

**Comment by dpogue** [comment]
The `noexcept` C++11 issue has been fixed (and merged upstream), but I'm a bit stuck on the Windows static build issue with avrt.lib.

The openal.pc pkg-config file seems to be correct and includes `-lavrt`.
The OpenAL-Target.cmake file also seems to be correct and includes `\$<LINK_ONLY:avrt>`.

However, I'm not convinced that the CMake build for libmikmod is actually reading those CMake target files in the `share/openal-soft` directory. I tried making changes there (including introducing invalid names for testing) and there was never any change in behaviour to libmikmod.

It feels to me like CMake's built-in `FindOpenAL` is being used and it's finding the lib path but not picking up any of the additional target configuration that the OpenAL-Soft CMake target files are providing.

**Comment by dg0yt** [comment]
> It feels to me like CMake's built-in `FindOpenAL` is being used and it's finding the lib path but not picking up any of the additional target configuration that the OpenAL-Soft CMake target files are providing.

libmikmod does use CMake's built-in `FindOpenAL`, and in a bad way: It uses include(FindOpenAL)`.
  - The Find module doesn't get the full set of input variables which CMake's `find_package` would provide.
  - The call isn't routed through vcpkg's overload of `find_package` which would enable loading of a wrapper to hide find module quirks.

This module is a bad example. It only uses `${OPENAL_LIBRARY}`, i.e. the singular word which is usually meant to be used as an input variable, but not to handle transitive usage requirements.

So IMO there are two task:
- Patch libmikmod to use CMake config, or at least to use Find mode correctly.
- Add a wrapper for openal to make `find_package(OpenAL)` produce a complete list in `OPENAL_LIBRARY`. (libmikmod could be the test case.)

**Review by Cheney-W — APPROVED** [review]

**Comment by Cheney-W** [comment]
Usage test passed with x64-windows-static triplet.

**Comment by BillyONeal** [comment]
Thanks for the update!

**Pull request merged**
