### PR TITLE
[vcpkg] Fortran support again. (Just testing)

### PR DESCRIPTION
**Pull request by Neumann-A**
Probably requires CMake and Ninja update in CI? Lets see...
Another approach to #6939 using gfortran from msys.

Fortran executables require to be linked with ld since libgfortran.lib requires symbols from libmingw32.lib which requires symbol `__image_base__`

### CODE REVIEW

**Comment by Neumann-A** [comment]
hmmm openblas fails with:
```
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: C:/agent/_work/1/s/buildtrees/openblas/x64-windows-rel/vcpkg-parallel-configure
    Error code: The system cannot find the file specified
    See logs for more information:
```
and I don't yet understand why. I have the feeling it is related to the ninja changes made in `vcpkg_find_acquire_program`.

**Comment by cbezault** [comment]
@Neumann-A let me know if/when you need help. I'd still like to see this happen.

**Comment by cbezault** [comment]
Also how do you plan on dealing with the circular dependency of netlib's LAPACK needing a BLAS library and OpenBLAS needing a LAPACK library?

**Comment by Neumann-A** [comment]
>Also how do you plan on dealing with the circular dependency of netlib's LAPACK needing a BLAS library and OpenBLAS needing a LAPACK library?

@cbezault: I thought we solved this issue and found that there is no circular dependency. It is LAPACK depends on BLAS and not the other way around. The OpenBLAS src directories has some extras which can be build if LAPACK is available but that would be a different port if I remember correctly. The same as lapack has some additional features like LAPACKE which should be its own little port. 

The main thing I need currently is the latest CMake merged into vcpkg ;)

**Comment by Neumann-A** [comment]
Related: http://www.netlib.org/lapack/lawnspdf/lawn270.pdf 

>When creating a shared library (.dll) the MinGW toolchain produces a GNU-format import
library (.dll.a) needed to link to the shared library. Microsoft (MS) tools do not recognize this
format. In order to use MS tools and link to a shared library created by MinGW tools one must
generate a MS-format import library (.lib) using the MS lib.exe tool installed with Visual Studio.
When building with MinGW tools on a machine that also has Visual Studio installed CMake
2.8.7 and higher offers a “CMAKE_GNUtoMS” option. When enabled CMake automatically
generates additional build rules to run the MS lib.exe tool and create a MS-format import library
(.lib) for each shared library (.dll) created by a project in addition to its normal GNU-format
import library (.dll.a). One may enable the option by setting CMAKE_GNUtoMS inside the
project CMake code or by passing it on the CMake command line when generating the build
tree: <snip>
Note that the feature currently works only for SHARED libraries because they reference their
dependence on the GNU Fortran runtime libraries internally. STATIC libraries are more
challenging because they requires explicit linking to the runtime libraries whose format would
also need conversion. A project may specify that a library be shared by using the SHARED
option of the add_library command:

probably have to switch lapack-reference to DYNAMIC only

**Comment by cbezault** [comment]
My memory is that OpenBLAS requires a LAPACK library (unnecessarily) in order to build.

**Comment by Neumann-A** [comment]
>My memory is that OpenBLAS requires a LAPACK library (unnecessarily) in order to build.

That is already solved in vcpkg and openblas should only build the blas part on all platforms.

**Comment by Neumann-A** [comment]
Closing this until #10767 is merged. Don't want to CI to be run on this without a reason. lapack-reference build fine on windows which was all I wanted to see for now.

**Pull request closed without merging**
