### PR TITLE
[vcpkg baseline][blas] Passing remove form fail list

### PR DESCRIPTION
**Pull request by Cheney-W**
Passing on https://dev.azure.com/vcpkg/public/_build/results?buildId=101640&view=results
```
PASSING, REMOVE FROM FAIL LIST: blas:arm-neon-android (/vcpkg/scripts/azure-pipelines/../ci.baseline.txt).
```

`blas:arm-neon-android=fail` was added to ci.baseline.txt by https://github.com/microsoft/vcpkg/pull/37056, which has been fixed by https://github.com/microsoft/vcpkg/pull/24327.

Since `blas-test:arm-neon-android` install failed, modify the `fail` as `skip`.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [ ] ~SHA512s are updated for each updated download.~
- [ ] ~The "supports" clause reflects platforms that may be fixed by this new version.~
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [ ] ~Any patches that are no longer applied are deleted from the port's directory.~
- [ ] ~The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.~
- [ ] ~Only one version is added to each modified port's versions file.~

### CODE REVIEW

**Comment by Neumann-A** [comment]
I don't think you should remove it as long as blas-test is failing

**Review by LilyWangLL — APPROVED** [review]

**Comment by JavierMatosD** [comment]
We need to determine what's actually broken. Is `blas-test` broken or `blas`? I think further investigation is required here. Closing this for now. Feel free to reopen if you feel strongly about this.

**Comment by BillyONeal** [comment]
> I don't think you should remove it as long as blas-test is failing

I don't think it can be like this: we can't keep having tri-weekly CI runs broken. Clearly, touching something that causes blas to fail to build on Android should now be treated as a regression, even if the change is done to fix blas-test.

As a result I think @Cheney-W 's original change (to just delete the line) is correct. It isn't necessarily making a statement that blas is in a perfect working state on Android, only that it shouldn't be failing our CI testing over it.

**Comment by Neumann-A** [comment]
> We need to determine what's actually broken. Is blas-test broken or blas?  

previously blas-test was incorporated into `blas`
To answer what is broken would require to get the actual configure log (CMakeFiles/CMakeConfigureLog.yaml) which #38409 would give. 

> As a result I think @Cheney-W 's original change (to just delete the line) is correct.

I disagree. The correct way would be to add a `supports:` field to blas unless `blas-test` is green

**Pull request closed without merging**
