### PR TITLE
[igraph] update to 0.9.9

### PR DESCRIPTION
**Pull request by szhorvat**
**Describe the pull request**

- #### What does your PR fix?
  Updated igraph to 0.9.9.
  Fixed UWP compatibility.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  `all`, `No`

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  `Yes`

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by szhorvat** [comment]
@Neumann-A I noticed you added `supports: "!uwp"` to this port since last time I was here. Can you clarify what would be required from igraph to add support? Are there any forbidden function calls?

**Comment by Neumann-A** [comment]
> @Neumann-A I noticed you added `supports: "!uwp"` to this port since last time I was here. Can you clarify what would be required from igraph to add support? Are there any forbidden function calls?

Probably. It was cascade before the uwp uses ninja change.

**Comment by szhorvat** [comment]
Could you give me a hint on how to identify the issues? I only have limited access to Windows (in a VM), thus debugging this is costly in time. I assume there's more to it than compiling with `/ZW` as CMake alone fails when using that option.

**Comment by Neumann-A** [comment]
> Could you give me a hint on how to identify the issues?

Remove the `supports` line and you get the error from vcpkg CI. Just need to download the logs then.

**Comment by JonLiu1993** [comment]
All features are tested successfully in the following triplet:
- x86-windows
- x64-windows
- x64-windows-static

**Comment by ras0219-msft** [comment]
LGTM, thanks for the update!

**Pull request merged**
