### PR TITLE
[jemalloc] Initial commit for jemalloc library

### PR DESCRIPTION
**Pull request by KindDragon**

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Oo! I'm really glad to see `jemalloc`!

However, I have a few questions about how it works and how to package it.

I understand that `jemalloc` is designed/configured, by default, to _silently replace_ your CRT's malloc implementation. I understand that this is the desired behavior in many cases, but for reproducibility reasons this means that `jemalloc` should really be implicitly available and linked from the very beginning -- it really doesn't act like just another library! It also will play havoc with our auto-linking; suddenly every VS project you build will silently have their CRT replaced!

For this reason, I think there are three reasonable ways to proceed:
1. _jemalloc as a normal port_ built with a prefix so it doesn't automatically replace malloc[1]. This could be autolinked like every other library, and you can easily access it from C/C++ by calling "vcpkg_jemalloc" (however we decide to do the prefix).
2. _jemalloc as a manual-link port_ with the lib files installed into the `manual-link\` subdirectory. This would enable (what I assume is) the primary jemalloc scenario: replacing the CRT's allocator. However, this will only replace your application's allocator -- and probably cause a **lot** of pain if you use DLLs. I don't think this is a good idea from what I can see so far.
3. _jemalloc as a triplet_ which implicitly uses jemalloc from the very beginning and links it into every library. This actually does what I suspect is probably desired by the jemalloc "default" scenario: modify your core CRT to have jemalloc as the allocator. This is certainly what triplets are designed to encapsulate, however as we've not done this before, there will be a lot of foundation work to support it.

Given this, I think the best way to proceed is to first add `jemalloc` as a port via 1, and investigate 3 in the future.

[1] https://github.com/jemalloc/jemalloc/blob/dev/INSTALL#L70-L84, though I don't know if the cmake fork supports this yet!

**Comment by KindDragon** [comment]
Jemalloc currently export all symbols with `je_` prefix, so it can be normal port
image

I want jemalloc for folly, it contains many improvements for jemalloc

**Comment by KindDragon** [comment]
Jemalloc redefine `malloc` and others only when you include `jemalloc\jemalloc.h`

**Comment by KindDragon** [comment]
Hmm. folly doesn't support jemalloc with prefix 😞  So we have only option 3 for folly

**Comment by ras0219-msft** [comment]
What do you think we should do with this PR?

**Comment by KindDragon** [comment]
I think we should close it, because
* No ports supported option 1 (jemalloc as a normal port)
* I don't have time to implement option 3 and debug all issues with jemalloc library

**Comment by KindDragon** [comment]
Or, since this PR already implements option 1, we can merge it and return to it when some port supports jemalloc

**Comment by Voskrese** [comment]
no
~jemallocso.lib~
ok
jemalloc.lib

nghttp2 - https://github.com/nghttp2/nghttp2
https://github.com/nghttp2/nghttp2/blob/master/cmake/FindJemalloc.cmake

```
cmake . -G "Visual Studio 14" -DCMAKE_PREFIX_PATH="E:/tools/vcpkg/installed/x86-window
s"
```
```
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: E:/Anaconda3/python.exe (found version "3.5.2")
-- Found OpenSSL: optimized;E:/tools/vcpkg/installed/x86-windows/lib/libcryptoMD.lib;debug;E:/tools/vcpkg/installed/x86-windows/lib/libcryptoMDd.lib (found suitable version "1.1.0f", minimum required is "1.0.1")
-- Found Libev: E:/tools/vcpkg/installed/x86-windows/lib/ev.lib (found suitable version "4.22", minimum required is "4.11")
-- Found Libcares: E:/tools/vcpkg/installed/x86-windows/lib/cares.lib (found suitable version "1.12.1-DEV", minimum required is "1.7.5")
-- Found ZLIB: E:/tools/vcpkg/installed/x86-windows/lib/zlib.lib (found suitable version "1.2.11", minimum required is "1.2.3")
-- Found Jansson: E:/tools/vcpkg/installed/x86-windows/lib/jansson.lib (found suitable version "2.10", minimum required is "2.5")
-- Could NOT find Libevent: Found unsuitable version "", but required is at least "2.0.8" (found E:/tools/vcpkg/installed/x86-windows/lib/event.lib)
-- Could NOT find Cython (missing:  CYTHON_EXECUTABLE)
-- Found PythonLibs: E:/Anaconda3/libs/python35.lib (found version "3.5.2")
-- Found LibXml2: E:/tools/gstreamer/1.0/x86/lib/xml2.lib (found suitable version "2.9.4", minimum required is "2.7.7") 
-- Found Jemalloc: E:/tools/vcpkg/installed/x86-windows/lib/jemalloc.lib (found version "jemalloc-cmake.4.3.1-0-g88c2dc8be23f85694bc3a3f015e0f9fb8f8ab942")
-- Could NOT find Spdylay (missing:  SPDYLAY_LIBRARY SPDYLAY_INCLUDE_DIR) (Required is at least version "1.3.2")
-- Performing Test CXX_FLAG__std_c_11
-- Performing Test CXX_FLAG__std_c_11 - Success
-- Performing Test HAVE_STD_FUTURE
-- Performing Test HAVE_STD_FUTURE - Success
-- Performing Test HAVE_STD_MAP_EMPLACE
....
```

**Comment by ras0219-msft** [comment]
After checking to ensure it won't conflict with normal malloc, I think it's best to merge. I've updated it to follow the guidelines changes in the last few months.

**Pull request merged**
