### PR TITLE
[rollup:2021-08-09] Rollup PR

### PR DESCRIPTION
**Pull request by strega-nil-ms**
* [rollup:2021-08-09] PR #19348 (@strega-nil)
* [rollup:2021-08-09] PR #19338 (@strega-nil)
* [rollup:2021-08-09] PR #19239 (@strega-nil)
* [rollup:2021-08-09] PR #19238 (@strega-nil)
* [rollup:2021-08-09] PR #16706 (@JackBoosY)

### CODE REVIEW

**Comment by PhoebeHui** [comment]
```
CMake Error at scripts/cmake/vcpkg_fixup_cmake_targets.cmake:244 (vcpkg_internal_get_cmake_vars):
  Unknown CMake command "vcpkg_internal_get_cmake_vars".
Call Stack (most recent call first):
  ports/curl/portfile.cmake:91 (vcpkg_fixup_cmake_targets)
  scripts/ports.cmake:140 (include)
```

**Comment by BillyONeal** [comment]
Sorry for the reset of a world rebuild :(. Pushed merge with master to shut down the older VMs and to get the fix for embree which we know would fail here anyway after there was an existing Linux failure.

**Comment by strega-nil-ms** [comment]
Merging since gdal was failing with this already, and the paraview failure isn't caused by this either.

**Comment by dg0yt** [comment]
gdal fails due to a pc file issue with libcurl.  This is new. Curl was updated recently without failures in gdal. So I assume the pkgconfig fixup is broken now.
~~~
configure:20016: $PKG_CONFIG --exists --print-errors "libcurl"
Package " was not found in the pkg-config search path.
Perhaps you should add the directory containing `".pc'
to the PKG_CONFIG_PATH environment variable
Package '"', required by 'libcurl', not found
configure:20019: $? = 1
configure:20074: result:         found libcurl version 
configure:20079: checking for library containing curl_global_init
configure:20110: gcc -o conftest -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -fPIC -fPIC  -g -DDEBUG -ftrapv -fvisibility=hidden  -L/mnt/vcpkg-ci/installed/x64-linux/debug/lib  conftest.c  >&5
/usr/bin/ld: /tmp/ccTbLeVO.o: in function `main':
/mnt/vcpkg-ci/buildtrees/gdal/x64-linux-dbg/conftest.c:99: undefined reference to `curl_global_init'
~~~

Empty elements?

**Comment by ras0219-msft** [comment]
Thanks @dg0yt ; I've fixed the libcurl issue with #19607 (with independent confirmation). Let me know if it still doesn't work for you!

**Pull request merged**
