### PR TITLE
[jsoncons] Update to version 0.162.0

### PR DESCRIPTION
**Pull request by danielaparker**
**Describe the pull request**

Update jsoncons to version 0.162.0

- What does your PR fix? Fixes #

danielaparker/jsoncons#279
danielaparker/jsoncons#280
danielaparker/jsoncons#284
danielaparker/jsoncons#285
danielaparker/jsoncons#306

Includes change to CMakeFiles.txt that hopefully addresses vcpkg build issue.

- Which triplets are supported/not supported? Have you updated the CI baseline?

All are supported. CI baseline has been updated.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

Yes

### CODE REVIEW

**Comment by cenit** [comment]
you need to run

```
./vcpkg x-add-version jsoncons
```

and commit the modifications to the baseline to fix also x86-windows regression

**Comment by danielaparker** [comment]
> you need to run
> 
> ```
> ./vcpkg x-add-version jsoncons
> ```
> 
> and commit the modifications to the baseline to fix also x86-windows regression

Thanks! now done.

**Comment by cenit** [comment]
can you also prefix PR linked in the opening message with your own repo? Otherwise, it's linking to vcpkg issues which are completely unrelated...

**Comment by danielaparker** [comment]
> can you also prefix PR linked in the opening message with your own repo? 

Fixed

**Review by ras0219 — APPROVED** [review]

**Comment by ras0219-msft** [comment]
Thanks for the update!

**Comment by cenit** [comment]
@danielaparker 

the new update fails on me because of:
```
[3/106] /usr/bin/c++  -I/mnt/vcpkg/buildtrees/jsoncons/src/a2ab3dead7-a018935420.clean/include -I/mnt/vcpkg/buildtrees/jsoncons/src/a2ab3dead7-a018935420.clean/tests -I/mnt/vcpkg/buildtrees/jsoncons/src/a2ab3dead7-a018935420.clean/third_party -I/mnt/vcpkg/buildtrees/jsoncons/src/a2ab3dead7-a018935420.clean/third_party/catch -fPIC -g -Werror -Wall -Wextra -Wcast-align -Wcast-qual -Wimplicit-fallthrough -pedantic -MD -MT tests/CMakeFiles/unit_tests.dir/bson/src/bson_cursor_tests.cpp.o -MF tests/CMakeFiles/unit_tests.dir/bson/src/bson_cursor_tests.cpp.o.d -o tests/CMakeFiles/unit_tests.dir/bson/src/bson_cursor_tests.cpp.o -c /mnt/vcpkg/buildtrees/jsoncons/src/a2ab3dead7-a018935420.clean/tests/bson/src/bson_cursor_tests.cpp
FAILED: tests/CMakeFiles/unit_tests.dir/bson/src/bson_cursor_tests.cpp.o 
/usr/bin/c++  -I/mnt/vcpkg/buildtrees/jsoncons/src/a2ab3dead7-a018935420.clean/include -I/mnt/vcpkg/buildtrees/jsoncons/src/a2ab3dead7-a018935420.clean/tests -I/mnt/vcpkg/buildtrees/jsoncons/src/a2ab3dead7-a018935420.clean/third_party -I/mnt/vcpkg/buildtrees/jsoncons/src/a2ab3dead7-a018935420.clean/third_party/catch -fPIC -g -Werror -Wall -Wextra -Wcast-align -Wcast-qual -Wimplicit-fallthrough -pedantic -MD -MT tests/CMakeFiles/unit_tests.dir/bson/src/bson_cursor_tests.cpp.o -MF tests/CMakeFiles/unit_tests.dir/bson/src/bson_cursor_tests.cpp.o.d -o tests/CMakeFiles/unit_tests.dir/bson/src/bson_cursor_tests.cpp.o -c /mnt/vcpkg/buildtrees/jsoncons/src/a2ab3dead7-a018935420.clean/tests/bson/src/bson_cursor_tests.cpp
In file included from /mnt/vcpkg/buildtrees/jsoncons/src/a2ab3dead7-a018935420.clean/include/jsoncons_ext/bson/bson.hpp:17,
                 from /mnt/vcpkg/buildtrees/jsoncons/src/a2ab3dead7-a018935420.clean/tests/bson/src/bson_cursor_tests.cpp:10:
/mnt/vcpkg/buildtrees/jsoncons/src/a2ab3dead7-a018935420.clean/include/jsoncons_ext/bson/bson_encoder.hpp: In instantiation of ‘bool jsoncons::bson::basic_bson_encoder<Sink, Allocator>::visit_uint64(uint64_t, jsoncons::semantic_tag, const jsoncons::ser_context&, std::error_code&) [with Sink = jsoncons::bytes_sink<std::vector<unsigned char> >; Allocator = std::allocator<char>; uint64_t = long unsigned int]’:
/mnt/vcpkg/buildtrees/jsoncons/src/a2ab3dead7-a018935420.clean/include/jsoncons_ext/bson/bson_encoder.hpp:396:10:   required from here
/mnt/vcpkg/buildtrees/jsoncons/src/a2ab3dead7-a018935420.clean/include/jsoncons_ext/bson/bson_encoder.hpp:434:25: error: comparison of integer expressions of different signedness: ‘uint64_t’ {aka ‘long unsigned int’} and ‘int’ [-Werror=sign-compare]
  434 |                 if (val <= (std::numeric_limits<int32_t>::max)())
      |                     ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

```
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by danielaparker** [comment]
[@cenit](https://github.com/cenit)

Can you post an issue at https://github.com/danielaparker/jsoncons/issues? Thanks!

**Pull request merged**
