### PR TITLE
Update commands_update.cpp

### PR DESCRIPTION
**Pull request by OlafvdSpek**

### CODE REVIEW

**Comment by alexkaratarakis** [comment]
I think this should be with a backslash "\" instead of "/" or am I missing something?

**Comment by OlafvdSpek** [comment]
I like / better.. works everywhere whereas \ works only on Windows.
\ doesn't even work in Git Bash for Windows.

**Comment by ras0219-msft** [comment]
Unfortunately, cmd.exe does not work with forward slashes. Since the vast majority of our users are using cmd or powershell, we need to use backslashes to ensure it works for the widest audience. Since bash users can be assumed to be more advanced, it's safer to trust that they'll figure out to replace `\` with `/`.

I've added the `.\` in 05ebbfb.

See https://github.com/Microsoft/vcpkg/issues/719#issuecomment-283051439 as well.

**Comment by OlafvdSpek** [comment]
But cmd doesn't need the `.\` ;)
Too bad it doesn't accept `./`, it does accept `/` as directory separators.

**Pull request closed without merging**
