### PR TITLE
[reflectcpp] Updated to reflectcpp 0.16.0; added support for various formats in the form of features

### PR DESCRIPTION
**Pull request by liuzicheng1987**
If this PR updates an existing port, please uncomment and fill out this checklist:

- [x ] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [ x] SHA512s are updated for each updated download.
- [ x] The "supports" clause reflects platforms that may be fixed by this new version.
- [ x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [ x] Any patches that are no longer applied are deleted from the port's directory.
- [ x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [ x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by liuzicheng1987** [comment]
> @liuzicheng1987 please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree [company="{Code 17 GmbH}"]

**Comment by liuzicheng1987** [comment]
@microsoft-github-policy-service agree [company="{Code 17 GmbH}"]

**Comment by liuzicheng1987** [comment]
@microsoft-github-policy-service agree

**Comment by LilyWangLL** [comment]
All features passed with following triplets:
```
x86-windows
x64-windows
x64-windows-static
```
Usage test passed on `x64-windows`.

**Review by LilyWangLL — DISMISSED** [review]

**Comment by dg0yt** [comment]
The toml feature has fragile dependency management.
Can this be tested with a user project?

- When building reflectcpp, it doesn't use pkg-config but file-oriented find_... commands.
  (It would be easy to use pkg-config when building the port.)
- The exported CMake config make pkg-config required for toml.
  But it is not generally installed in particular on Windows computers.
  It is probably not necessary after the file-oriented find_... commands.
  (And it may create a different imported target than the unknown "tomlplusplus" package.)

Additional notes for upstream:
- `find_dependency` calls should be done before including the target file. That's how find_package search mode might continue search when desired by the user.
- Ideally, there should be hardly any no vcpkg-specific code. vpckg is meant to be enabled by using the toolchain. That's all.

**Comment by liuzicheng1987** [comment]
@dg0yt , the problem with tomlplusplus is that the vcpkg does not provide a config.cmake file, so find_packages does not work. For that reason I have no choice but to use vcpkg-specific code. If you have a better idea, I am very open to suggestions. I would love not to have to do this.

I have extensive automated tests for the CMake file on different operating systems, including Windows, and I am very confident that it works. I would refer you to the testing pipelines in my own repository:

https://github.com/getml/reflect-cpp/tree/main/.github/workflows

**Comment by BillyONeal** [comment]
>the problem with tomlplusplus is that the vcpkg port does not provide a config.cmake file, so find_packages does not work

It provides .pc though.

**Comment by dg0yt** [comment]
The testing probably doesn't cover consuming the CMake config files on Windows, with toml enabled?

At the moment the package avoids pkg-config at build time, but requires pkg-config to be able to use the exported CMake config. This simply doesn't make sense.
 - You can use pkg-config in CMake in Windows. It is easy for authoring vcpkg ports. But outside ports, it is unusual to have it available in MSVC contexts.
 - When you don't use pkg-config for configuring the package, you don't need it in the exported config.
 - Even when you use pkg-config, you don't need it in the exported config if you just the interace variables (`<PKG>_LINK_LIBRARIES` etc.) instead of imported targets.

**Comment by liuzicheng1987** [comment]
@dg0yt, I could modify the CMakeLists.txt as follows:

```
if (REFLECTCPP_TOML)
    list(APPEND REFLECT_CPP_SOURCES
        src/reflectcpp_toml.cpp
    )
    if(REFLECTCPP_USE_VCPKG)
        find_package(PkgConfig REQUIRED)
        pkg_check_modules(tomlplusplus REQUIRED IMPORTED_TARGET tomlplusplus)
        target_link_libraries(reflectcpp PkgConfig::tomlplusplus)
    else()
        find_package(tomlplusplus)
        target_link_libraries(reflectcpp PUBLIC tomlplusplus::tomlplusplus)
    endif()
endif()
```

This is taken from the "usage" file of the tomlplusplus port. 

It seems to work fine. Is that what you have mind? If so, I would simply do a patch release.

Once we're at it, do you have any suggestions for the TinyCBOR port? The TinyCBOR port provides neither a config.cmake nor a .pc file.

**Comment by liuzicheng1987** [comment]
@LilyWangLL , @dg0yt , @BillyONeal , here's my suggestion: Let's not let the perfect be the enemy of the good.

I think the best way forward is to remove the CBOR and TOML features for now. All other features (BSON, flexbuffers, msgpack, XML, YAML)  seem completely uncontroversial and I know that people are relying on them. It would be nice to have them available in vcpkg as well.

I would kindly ask for guidance on two things:

1. Is the solution I have outlined for tomlplusplus in my last comment what @dg0yt or @BillyONeal have in mind?
2. What should we do about the TinyCBOR that provides neither a config.cmake nor a .pc file? Should I maybe switch over to libcbor, which at least offers a portfile or just use JSONcons? 

Once we have these issues clarified, I will make the necessary upstream changes and then include support for these two formats in my next regular release.

**Review by LilyWangLL — APPROVED** [review]

**Comment by BillyONeal** [comment]
> This is taken from the "usage" file of the tomlplusplus port.
> 
> It seems to work fine. Is that what you have mind? If so, I would simply do a patch release.

I'm not familiar with that specific port but that code block seems reasonable to me. The thing that matters is that someone who tries to do their own find_package for reflectcpp gets something that works when the toml feature is turned on.

**Comment by BillyONeal** [comment]
Thanks!

**Comment by liuzicheng1987** [comment]
@BillyONeal , thanks for your reply and thanks for merging! 

I will make these changes upstream and also think about a solution for CBOR.

**Pull request merged**
