### PR TITLE
Add support of external downloader aria2

### PR DESCRIPTION
**Pull request by cmpute**
I meet connection problem again.. And I consequently implement this. Other downloaders can be added as well

### CODE REVIEW

**Comment by cmpute** [comment]
Fix some problems for exporting as well

**Comment by ras0219-msft** [comment]
Thanks for the PR!

It looks like aria should respect the `https_proxy` environment variables, so it seems like it could be a drop-in replacement for everyone. Do you see any reasons why this couldn't be the _only_ downloader?

**Comment by cmpute** [comment]
Rebased~ (Actually not sure how to rebase in this situation 😅 )

> Do you see any reasons why this couldn't be the only downloader?

In my experience, aria2 might be stuck in poor connection if it downloads with multiple connections from a source which doesn't support block downloading. Of course in this situation builtin downloading will failed too. However, `wget` seems to performs better if connection is not stable. So maybe `wget` can be an alternative. Anyway, aria2 is quite sufficient. It can be the only downloader without any problem imo.

**Comment by cmpute** [comment]
I checked the documentation and [aria2 support `HTTP_PROXY` and `HTTPS_PROXY`](https://aria2.github.io/manual/en/html/aria2c.html#environment)

**Comment by cmpute** [comment]
BTW, I'm not able to download lame source files with link either `https://sourceforge.net/projects/lame/files/lame/3.100/lame-3.100.tar.gz` or `https://jaist.dl.sourceforge.net/project/lame/lame/3.100/lame-3.100.tar.gz` using internal download tool. It always told me `Failed. Status: 6;"Couldn't resolve host name"`. However, using aria2 the download can be successful. Any suggestions?

**Comment by cmpute** [comment]
I have rebased the code to master, could you pls merge this request soon? Seems there's much work going on in the toolsrc.

**Comment by alexkaratarakis** [comment]
@cmpute 
Thanks for this great PR!
I renamed the flag to `--x-use-aria2`; we are evaluating using aria2 by default and thus trying to avoid creating legacy flags.

**Pull request merged**
