### PR TITLE
[VTK-m/VTK/ParaView] Add new port (might work now)

### PR DESCRIPTION
**Pull request by Neumann-A**
Just to let people know that I am working on it and maybe help to fix the issues in getting this to work. 
for [VTK-m/VTK/ParaView] Add new port (might work now) see #9960
This PR now adds all the xorg libraries and I am trying to get xserver to compile on linux/windows.

### CODE REVIEW

**Comment by Neumann-A** [comment]
TODO: Figure out why ParaView installs directly into the installed dir and not the package dir
image

**Comment by Neumann-A** [comment]
@cenit what was your reasoning behind renaming the flann static target? This renaming is the reason why I see a regression in pcl:x64-windows-static https://dev.azure.com/vcpkg/public/_build/results?buildId=27030&view=logs&j=4c4e0d3e-e499-5796-93bc-a44aeda33b38
The correct way to solve issue like this is to provide an alias target e.g. `add_library(flann::flann_cpp ALIAS flann::flann_cpp_s)`

**Comment by Neumann-A** [comment]
So to fix the remaining cutelyst2 regression i actually have to take care of #9442 and remove most of the vcpkg_cmake_wrapper

**Comment by cenit** [comment]
> @cenit what was your reasoning behind renaming the flann static target?

You mean why `flann_s` is removed and only `flann` exists, and the same is true for `flann_cpp_s` and `flann_cpp`? Because it's almost mandatory here on vcpkg to remove differences in handling a static vs a dynamic library, we shoud hide this thing from the downstream developer.
Can you elaborate more on your error? Sorry, it's easier to read from you than investigating errors from CI

**Comment by Neumann-A** [comment]
@cenit the error simply reads that the target `flann_cpp_s` cannot be found:
```
CMake Error at C:/vsts/_work/4/s/scripts/buildsystems/vcpkg.cmake:217 (_add_library):
  Target "pcl_kdtree" links to target "flann::flann_cpp_s" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```
Personally I don't think it is required to remove the target difference since downstream consumers can always check if a certain target exists and link their libraries accordingly. In this case PCL actually got it right. I however understand why we would like to have agnostics targets in regards to the library type but I also believe this needs to be supplied upstream by defining such an extra target. In the case of e.g. hdf5 this could be a simple alias like `hdf5::hdf5` which is either `hdf5:hdf5-static` or `hdf5::hdf5-shared` depending on `BUILD_SHARED_LIBS` of the hdf5 library. In the case of flann_cpp naming is a bit more difficult since the general name `flann_cpp` is already taken by the dynamic target. Maybe something along the line of `flann_cpp_alias`, `flann_cpp_general` or `flann_cpp_vcpkg`

**Comment by Neumann-A** [comment]
@JackBoosY 
What do you think of the changes made to:
`scripts/cmake/vcpkg_configure_make.cmake`
and the new:
`scripts/cmake/vcpkg_fixup_pkgconfig.cmake`
Or are there other ways to get the same behavior?

**Comment by Neumann-A** [comment]
extracted the following PRs from this to reduce the changeset:
#9864 HDF5 tools
#9863 PKG_CONFIG_PATHS in configure make
#9862 _INIT flags in windows toolchain
#9861 new function vcpkg_fixup_pkgconfig

TODO:
with #9863 and #9861 merged the xorg libraries can be split from this PR
with #9864 merged the cgns port can be split from this PR
with #9862 merged the configure_meson changes can be split from this PR

**Comment by Neumann-A** [comment]
hmm cannot figure out why xcb is failing on linux here....

**Comment by JackBoosY** [comment]
Seems have merge conflicts?

**Comment by Neumann-A** [comment]
@JackBoosY: Dont mind this PR to much I will probably extract the required ParaView/VTK/VTK-m changes in another PR. I went a bit overboard trying to get qt5-x11extras to work on Linux and get a ParaView Linux build ;)

**Comment by Voskrese** [comment]
`vcpkg install CGNS[*]:x64-windows
`
> Package hdf5 does not have a mpi feature

there is no mpi support word in hdf5, there is a parallel

`vcpkg install hdf5[core,parallel,szip,tools,zlib]:x64-windows
`

Build-Depends: hdf5[mpi] -->> hdf5[parallel]


```
vcpkg install cgns[core,hdf5,legacy,lfs,lfsselector,tools]:x64-windows --recurse
Computing installation plan...
The following packages will be built and installed:
    cgns[core,hdf5,legacy,lfs,lfsselector,tools]:x64-windows
Starting package 1/1: cgns:x64-windows
Building package cgns[core,hdf5,legacy,lfs,lfsselector,tools]:x64-windows...
-- Using cached E:/tools/vcpkg/downloads/CGNS-CGNS-3420e23febf0eb38c1b05af3c157d614d8476557.tar.gz
-- Using source at E:/tools/vcpkg/buildtrees/cgns/src/14d8476557-c37af86822
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: E:/tools/vcpkg/packages/cgns_x64-windows/share/cgns/cgnsBuild.defs
-- Installing: E:/tools/vcpkg/packages/cgns_x64-windows/include/cgnsconfig.h
-- Installing: E:/tools/vcpkg/packages/cgns_x64-windows/tools/cgns/cgnscheck.exe
-- Installing: E:/tools/vcpkg/packages/cgns_x64-windows/tools/cgns/cgnscompress.exe
-- Installing: E:/tools/vcpkg/packages/cgns_x64-windows/tools/cgns/cgnsconvert.exe
-- Installing: E:/tools/vcpkg/packages/cgns_x64-windows/tools/cgns/cgnsdiff.exe
-- Installing: E:/tools/vcpkg/packages/cgns_x64-windows/tools/cgns/cgnslist.exe
-- Installing: E:/tools/vcpkg/packages/cgns_x64-windows/tools/cgns/cgnsnames.exe
-- Installing: E:/tools/vcpkg/packages/cgns_x64-windows/share/cgns/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package cgns[core,hdf5,legacy,lfs,lfsselector,tools]:x64-windows... done
Installing package cgns[core,hdf5,legacy,lfs,lfsselector,tools]:x64-windows...
Installing package cgns[core,hdf5,legacy,lfs,lfsselector,tools]:x64-windows... done
```

**Comment by Voskrese** [comment]
@Neumann-A 

how do I use the script `vcpkg_fixup_pkgconfig.cmake` ? do I need any special parameters?

**Comment by Neumann-A** [comment]
@Voskrese Wrong PR. #9861 is the right one. But unless the *.pc files contain only references within vcpkg you should be fine calling just vcpkg_fixup_pkgconfig(). If there are references to outside vcpkg you might need to add SYSTEM_LIBRARIES (list of libs) and SYSTEM_PACKAGES (list of packages) to the call

**Pull request closed without merging**
