### PR TITLE
[vtk] Fix building with MPI and Python enabled

### LINKED ISSUE #12883: [vtk] build failure
**Host Environment**
- OS: [Windows]
- Compiler: cl

**To Reproduce**
`./vcpkg install vcpkg install vtk[all]:x64-windows`

**Failure logs** 
Console output:

```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: C:/vcpkg/buildtrees/vtk/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\vtk\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:300 (vcpkg_execute_required_process)
  ports/vtk/portfile.cmake:135 (vcpkg_configure_cmake)
  scripts/ports.cmake:79 (include)

Error: Building package vtk:x64-windows failed with: BUILD_FAILED
```

In "C:\vcpkg\buildtrees\vtk\config-x64-windows-out.log":
```
[1/2] cmd /c "cd .. && "C:/Program Files/CMake/bin/cmake.exe" "C:/vcpkg/buildtrees/vtk/src/ad8774e85e-173cb3e94f.clean" "-DVTK_USE_CUDA=OFF" "-DVTK_BUILD_ALL_MODULES=OFF" "-DBUILD_TESTING=OFF" "-DVTK_BUILD_TESTING=OFF" "-DVTK_BUILD_EXAMPLES=OFF" "-DVTK_INSTALL_INCLUDE_DIR=include" "-DVTK_INSTALL_DATA_DIR=share/vtk/data" "-DVTK_INSTALL_DOC_DIR=share/vtk/doc" "-DVTK_INSTALL_PACKAGE_DIR=share/vtk" "-DVTK_INSTALL_RUNTIME_DIR=bin" "-DVTK_FORBID_DOWNLOADS=ON" "-DVTK_ENABLE_REMOTE_MODULES=OFF" "-DVTK_GROUP_ENABLE_StandAlone=YES" "-DVTK_GROUP_ENABLE_Rendering=YES" "-DVTK_GROUP_ENABLE_Views=YES" "-DVTK_USE_TK=OFF" "-DVTK_USE_EXTERNAL:BOOL=ON" "-DVTK_MODULE_USE_EXTERNAL_VTK_gl2ps:BOOL=OFF" "-DVTK_GROUP_ENABLE_MPI=YES" "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/vcpkg/packages/vtk_x64-windows""
FAILED: ../CMakeCache.txt 
cmd /c "cd .. && "C:/Program Files/CMake/bin/cmake.exe" "C:/vcpkg/buildtrees/vtk/src/ad8774e85e-173cb3e94f.clean" "-DVTK_USE_CUDA=OFF" "-DVTK_BUILD_ALL_MODULES=OFF" "-DBUILD_TESTING=OFF" "-DVTK_BUILD_TESTING=OFF" "-DVTK_BUILD_EXAMPLES=OFF" "-DVTK_INSTALL_INCLUDE_DIR=include" "-DVTK_INSTALL_DATA_DIR=share/vtk/data" "-DVTK_INSTALL_DOC_DIR=share/vtk/doc" "-DVTK_INSTALL_PACKAGE_DIR=share/vtk" "-DVTK_INSTALL_RUNTIME_DIR=bin" "-DVTK_FORBID_DOWNLOADS=ON" "-DVTK_ENABLE_REMOTE_MODULES=OFF" "-DVTK_GROUP_ENABLE_StandAlone=YES" "-DVTK_GROUP_ENABLE_Rendering=YES" "-DVTK_GROUP_ENABLE_Views=YES" "-DVTK_USE_TK=OFF" "-DVTK_USE_EXTERNAL:BOOL=ON" "-DVTK_MODULE_USE_EXTERNAL_VTK_gl2ps:BOOL=OFF" "-DVTK_GROUP_ENABLE_MPI=YES" "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/vcpkg/packages/vtk_x64-windows""
-- The C compiler identification is MSVC 19.27.29110.0
-- The CXX compiler identification is MSVC 19.27.29110.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test Support for 64 bit file systems
-- Performing Test Support for 64 bit file systems - Failed
-- Module testing disabled due to `VTK_FORBID_DOWNLOADS` being set.
CMake Error at CMake/vtkModule.cmake:959 (message):
  The VTK::IOParallelNetCDF module requires the disabled module VTK::mpi.
Call Stack (most recent call first):
  CMakeLists.txt:270 (vtk_module_scan)


-- Configuring incomplete, errors occurred!
See also "C:/vcpkg/buildtrees/vtk/x64-windows-rel/CMakeFiles/CMakeOutput.log".
See also "C:/vcpkg/buildtrees/vtk/x64-windows-rel/CMakeFiles/CMakeError.log".
[2/2] cmd /c "cd ../../x64-windows-dbg && "C:/Program Files/CMake/bin/cmake.exe" "C:/vcpkg/buildtrees/vtk/src/ad8774e85e-173cb3e94f.clean" "-DVTK_USE_CUDA=OFF" "-DVTK_BUILD_ALL_MODULES=OFF" "-DBUILD_TESTING=OFF" "-DVTK_BUILD_TESTING=OFF" "-DVTK_BUILD_EXAMPLES=OFF" "-DVTK_INSTALL_INCLUDE_DIR=include" "-DVTK_INSTALL_DATA_DIR=share/vtk/data" "-DVTK_INSTALL_DOC_DIR=share/vtk/doc" "-DVTK_INSTALL_PACKAGE_DIR=share/vtk" "-DVTK_INSTALL_RUNTIME_DIR=bin" "-DVTK_FORBID_DOWNLOADS=ON" "-DVTK_ENABLE_REMOTE_MODULES=OFF" "-DVTK_GROUP_ENABLE_StandAlone=YES" "-DVTK_GROUP_ENABLE_Rendering=YES" "-DVTK_GROUP_ENABLE_Views=YES" "-DVTK_USE_TK=OFF" "-DVTK_USE_EXTERNAL:BOOL=ON" "-DVTK_MODULE_USE_EXTERNAL_VTK_gl2ps:BOOL=OFF" "-DVTK_GROUP_ENABLE_MPI=YES" "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=C:/vcpkg/packages/vtk_x64-windows/debug""
FAILED: ../../x64-windows-dbg/CMakeCache.txt 
cmd /c "cd ../../x64-windows-dbg && "C:/Program Files/CMake/bin/cmake.exe" "C:/vcpkg/buildtrees/vtk/src/ad8774e85e-173cb3e94f.clean" "-DVTK_USE_CUDA=OFF" "-DVTK_BUILD_ALL_MODULES=OFF" "-DBUILD_TESTING=OFF" "-DVTK_BUILD_TESTING=OFF" "-DVTK_BUILD_EXAMPLES=OFF" "-DVTK_INSTALL_INCLUDE_DIR=include" "-DVTK_INSTALL_DATA_DIR=share/vtk/data" "-DVTK_INSTALL_DOC_DIR=share/vtk/doc" "-DVTK_INSTALL_PACKAGE_DIR=share/vtk" "-DVTK_INSTALL_RUNTIME_DIR=bin" "-DVTK_FORBID_DOWNLOADS=ON" "-DVTK_ENABLE_REMOTE_MODULES=OFF" "-DVTK_GROUP_ENABLE_StandAlone=YES" "-DVTK_GROUP_ENABLE_Rendering=YES" "-DVTK_GROUP_ENABLE_Views=YES" "-DVTK_USE_TK=OFF" "-DVTK_USE_EXTERNAL:BOOL=ON" "-DVTK_MODULE_USE_EXTERNAL_VTK_gl2ps:BOOL=OFF" "-DVTK_GROUP_ENABLE_MPI=YES" "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=C:/vcpkg/packages/vtk_x64-windows/debug""
-- The C compiler identification is MSVC 19.27.29110.0
-- The CXX compiler identification is MSVC 19.27.29110.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test Support for 64 bit file systems
-- Performing Test Support for 64 bit file systems - Failed
-- Module testing disabled due to `VTK_FORBID_DOWNLOADS` being set.
CMake Error at CMake/vtkModule.cmake:959 (message):
  The VTK::IOParallelNetCDF module requires the disabled module VTK::mpi.
Call Stack (most recent call first):
  CMakeLists.txt:270 (vtk_module_scan)


-- Configuring incomplete, errors occurred!
See also "C:/vcpkg/buildtrees/vtk/x64-windows-dbg/CMakeFiles/CMakeOutput.log".
See also "C:/vcpkg/buildtrees/vtk/x64-windows-dbg/CMakeFiles/CMakeError.log".
ninja: build stopped: subcommand failed.

```

### PR DESCRIPTION
**Pull request by albertziegenhagel**
This fixes the configure step of VTK when both MPI and Python are enabled.

To build with MPI, we need to pass `-DVTK_USE_MPI=ON`.

When both MPI and Python are enabled, VTK needs `mpi4py`. This PR enabled VTK to build its own version of mpi4py instead of looking for an external version of it.
I am not 100% sure whether this is the best approach. Maybe having mpi4py as separate port is the better solution. Please note: even though mpi4py is a Python package, usually it is required that mpi4py and VTK are linking to the same MPI implementation to function correctly. Additionally installing mpi4py comes with a header `mpi4py.h` that is required by VTK, so in some sense it is both, a Python package and a C library, just like VTK itself. Let me know what you think.

### CODE REVIEW

**Comment by Neumann-A** [comment]
mpi4py should probably be a freestandig port on its own.

**Review by JackBoosY — CHANGES_REQUESTED** [review]
Please update the version info. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).

**Comment by albertziegenhagel** [comment]
> Please update the version info. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).

Sorry, forgot to update it. I've pushed a change to increase to port version.

**Comment by JackBoosY** [comment]
@albertziegenhagel Sorry, I've no idea, I don't use that so I have no authority.

**Comment by Neumann-A** [comment]
@JackBoosY: I am also not using it and also don't have any authority but I have an opinion and you should have one too ;)
Just consider the fact that https://github.com/mpi4py/mpi4py is a completly separate from VTK and the VTK option is named `VTK_MODULE_USE_EXTERNAL_VTK_mpi4py`

**Comment by JackBoosY** [comment]
mpi4py should indeed be a separate port, but we have not added it yet. So i think it's ok.

**Comment by JackBoosY** [comment]
When building `vtk-m[core,mpi]:x86-windows`:
```
G:\12971\vcpkg\buildtrees\vtk-m\src\76c3434ac0-e3aceb77b8.clean\vtkm/Math.h(2665): error C3861: '_BitScanForward64': identifier not found
G:\12971\vcpkg\buildtrees\vtk-m\src\76c3434ac0-e3aceb77b8.clean\vtkm/Math.h(2748): error C3861: '__popcnt64': identifier not found
```

**Comment by Neumann-A** [comment]
@JackBoosY: That means the feature does not support `x86` since that are `x64` intrinsics. See https://docs.microsoft.com/de-de/cpp/intrinsics/bitscanforward-bitscanforward64?view=vs-2019

**Comment by albertziegenhagel** [comment]
Is this a regression?

This PR is only about VTK, not VTK-m. I have not tried building VTK-m with MPI yet, but I can't see how changes to the VTK port should affect VTK-m. Could you elaborate on where those errors come from?

**Comment by JackBoosY** [comment]
Well, ignore feature `mpi` when building x86-windows, I still got some errors:
Building `vtk[python]:x86-windows`:
```
CMake Error at ThirdParty/hdf5/CMakeLists.txt:26 (message):
  An external MPI-aware HDF5 requires that VTK be built with MPI support as
  well.
```

**Comment by Neumann-A** [comment]
@JackBoosY: That happens if you have `hdf5[parallel]` installed

**Comment by JackBoosY** [comment]
@Neumann-A We may need to find a way to warn users in portfile.cmake.

**Comment by Neumann-A** [comment]
@JackBoosY: Shouldn't block this PR since this error is also currently in master. Currently vcpkg does not provide a way to inspect/retrieve the installed feature set & build dependencies (both are required) of a installed port. You can try to invent `vcpkg_get_installed_port_info` which returns that information.

**Comment by JackBoosY** [comment]
Test results:
- x64-windows pass
- x64-windows-static pass
- x86-windows because of the existing regression, ignore

**Review by JackBoosY — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
