### PR TITLE
[paho-mqtt] fix ODR to libuuid and update to 1.3.12

### LINKED ISSUE #29931: [paho-mqttpp3] Linux ODR violation
**Host Environment**

- OS: Ubuntu 22.04
- Compiler: GCC 12.2.1

**To Reproduce**

`./vcpkg install paho-mqtt paho-mqttpp3 libuuid`

**Failure logs**

```
/vcpkg/buildtrees/paho-mqtt/src/adf3e3a08f-6410ea1ad2.clean/src/WebSocket.c:107: multiple definition of `uuid_generate'; ../../vcpkg_installed/x64-linux/debug/lib/libuuid.a(gen_uuid.c.o):/vcpkg/buildtrees/libuuid/src/77488caccc-f5e8f5589c.clean/gen_uuid.c:590: first defined here
```

**More info:**

It appears that Paho MQTT redefines uuid_generate from libuuid when it doesn't detect that libuuid was used when building paho. The problem is that paho now violates ODR when libuuid is required by another library in the program.

Possible fix: Add portfile option to let paho know about libuuid or add patch to fix libuuid detection

### PR DESCRIPTION
**Pull request by jimwang118**
Fixes https://github.com/microsoft/vcpkg/issues/29931
When installing `paho-mqtt`, if `libuuid` is already installed, the following error occurs.
`/vcpkg/buildtrees/paho-mqtt/src/adf3e3a08f-6410ea1ad2.clean/src/WebSocket.c:107: multiple definition of 'uuid_generate'; ../../vcpkg_installed/x64-linux/debug/lib/libuuid.a(gen_uuid.c.o):/vcpkg/buildtrees/libuuid/src/77488caccc-f5e8f5589c.clean/gen_uuid.c:590: first defined here`

To solve the problem of repeated definition of `uuid_generate `and `uuid_unparse `functions in `paho-mqtt` and `uuid` ports, by adding `LIBUUID` macro to judge whether to call the function in the installed `uuid` or call the custom function in `paho-mqtt`.
Add the macro definition `LIBUUID` in the `CMakeLists.txt` file through `target_compile_definitions (common_ssl_obj_static PUBLIC LIBUUID)`, so that the statement in the `paho-mqtt` code for judging the `LIBUUID `macro takes effect. You can use the function in `uuid` to judge through the macro `LIBUUID`, and the function uses Functions in `paho-mqtt`.

Add `target_compile_definitions (common_ssl_obj_static PUBLIC LIBUUID)` in `CMakeLists.txt` to make the following code of `paho-mqttd` work.
```
#if defined(LIBUUID)
#include <uuid/uuid.h>
#else /* if defined(USE_LIBUUID) */
#include <limits.h>
#include <stdlib.h>
#include <time.h>

/** @brief raw uuid type */
typedef unsigned char uuid_t[16];

/**
 * @brief generates a uuid, compatible with RFC 4122, version 4 (random)
 * @note Uses a very insecure algorithm but no external dependencies
 */
void uuid_generate( uuid_t out )
{
#if defined(OPENSSL)
	int rc = RAND_bytes( out, sizeof(uuid_t));
	if ( !rc )
#endif /* defined (OPENSSL) */
	{
		/* very insecure, but generates a random uuid */
		int i;
		srand(time(NULL));
		for ( i = 0; i < 16; ++i )
			out[i] = (unsigned char)(rand() % UCHAR_MAX);
		out[6] = (out[6] & 0x0f) | 0x40;
		out[8] = (out[8] & 0x3F) | 0x80;
	}
}

/** @brief converts a uuid to a string */
void uuid_unparse( uuid_t uu, char *out )
{
	int i;
	for ( i = 0; i < 16; ++i )
	{
		if ( i == 4 || i == 6 || i == 8 || i == 10 )
		{
			*out = '-';
			++out;
		}
		out += sprintf( out, "%02x", uu[i] );
	}
	*out = '\0';
}
#endif /* else if defined(LIBUUID) */
#endif /* if !(defined(_WIN32) || defined(_WIN64)) */

#include "Heap.h"

/** raw websocket frame data */
struct ws_frame
{
	size_t len; /**< length of frame */
	size_t pos; /**< current position within the buffer */
};
```

- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [X] SHA512s are updated for each updated download
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

Tested `paho-mqtt's` usage successfully on `x64-linux`.

### CODE REVIEW

**Review by LilyWangLL — DISMISSED** [review]

**Review by dg0yt — CHANGES_REQUESTED** [review]
**Objections:**
Port libuuid supports `!windows & !osx`.
IMO this implies that installation order problem isn't limited to linux, but can appear for every triplet supported by libuuid. And it should be fixed this way.

**Review by LilyWangLL — APPROVED** [review]

**Comment by BillyONeal** [comment]
> IMO this implies that installation order problem isn't limited to linux, but can appear for every triplet supported by libuuid. And it should be fixed this way.

It isn't clear to me what 'that way' means here; this change does make whether libuuid is used match the supports expression(s). Does that mean that the current PR is in keeping with what you asked for?

**Comment by tripleslash** [comment]
> > IMO this implies that installation order problem isn't limited to linux, but can appear for every triplet supported by libuuid. And it should be fixed this way.
> 
> It isn't clear to me what 'that way' means here; this change does make whether libuuid is used match the supports expression(s). Does that mean that the current PR is in keeping with what you asked for?

What is your expectation here?

**Review by dg0yt — APPROVED** [review]
This was already changed as I meant by "that way": The dependency `platform` expression matches the libuuid `supports` expression.

**Pull request merged**
