### PR TITLE
[curl] Build openssl and schannel backends by default

### PR DESCRIPTION
**Pull request by raphaelgz**
The https://github.com/curl/curl/pull/2665 makes possible to build multiple SSL backends simultaneously in Windows+CMake builds.

This PR enables the schannel backend along with the openssl backend and (probably, see below) will not change the current behavior.

The backend will be selected as follows:
  1. The backend set using [curl_global_sslset()](https://curl.haxx.se/libcurl/c/curl_global_sslset.html) is used (if any)
  1. else, the value of [CURL_SSL_BACKEND](https://curl.haxx.se/libcurl/c/libcurl-env.html) environment variable is used (if the value is invalid the variable will be ignored)
  1. else, the first available backend is used (currently: openssl)

The current behavior will change only if the variable CURL_SSL_BACKEND is set to "schannel" (or if someone enable the mbedtls backend)

### CODE REVIEW

**Comment by past-due** [comment]
Instead of defaulting the SChannel ("WinSSL") backend to on for Windows desktop builds, I think it would be better to split up the SSL backends into separate features, much like the curl configuration itself supports.

This would enable much more flexibility (ex. to compile without the OpenSSL backend), better OS support, and a much better match between vcpkg features and curl's build configuration options.

Example:

```
# Deprecated, still respects the CURL_USE_WINSSL define
# Replacement: Use the [openssl, winssl, darwinssl, mbedtls] features to specify 1+ SSL backends
Feature: ssl
Build-Depends: openssl
Description: SSL support (deprecated)

# SSL backends
Feature: openssl
Build-Depends: openssl
Description: SSL support (OpenSSL)

Feature: winssl
Description: SSL support (Secure Channel / "WinSSL")

Feature: darwinssl
Description: SSL support (Secure Transport / "DarwinSSL")

Feature: mbedtls
Build-Depends: mbedtls
Description: SSL support (mbedTLS)
```

**Comment by raphaelgz** [comment]
Done. :)

Is there some way to group features in order to satisfy the dependencies?

Something like this:
```
Source: curl
Version: 7.61.0
Build-Depends: zlib
Description: A library for transferring data with URLs
Default-Features: openssl | winssl | mbedTLS

Feature: http2
Build-Depends: nghttp2, curl[openssl | winssl]
Description: HTTP2 support

# SSL backends
Feature: openssl
Build-Depends: openssl
Description: SSL support (OpenSSL)

Feature: winssl
Description: SSL support (Secure Channel / "WinSSL")

Feature: mbedtls
Build-Depends: mbedtls
Description: SSL support (mbedTLS)
```

or this:
```
Source: curl
Version: 7.61.0
Build-Depends: zlib
Description: A library for transferring data with URLs
Default-Features: sslbackends

Feature: http2
Build-Depends: nghttp2, curl[sslbackends]
Description: HTTP2 support

Feature-Group: sslbackends
Features: openssl, winssl, mbedtls

Feature: openssl
Build-Depends: openssl
Description: SSL support (OpenSSL)

Feature: winssl
Description: SSL support (Secure Channel / "WinSSL")

Feature: mbedtls
Build-Depends: mbedtls
Description: SSL support (mbedTLS)
```

**Comment by KindDragon** [comment]
Check this thread https://github.com/Microsoft/vcpkg/pull/2631#issuecomment-359840726

**Comment by past-due** [comment]
> Check this thread #2631 (comment)

As noted above, the latest **curl** now permits easy configuration of multiple SSL backends. So these are no longer "replacement choices" (as described in that comment), but now _additive_ - you can, in fact, have both OpenSSL and WinSSL backends (or whatever other combination you want).

**Comment by pravic** [comment]
Yes, I tried to achieve that too, but without luck: https://github.com/Microsoft/vcpkg/pull/2862#issuecomment-368509443

**Comment by past-due** [comment]
@pravic: I believe things have changed in `curl` since your PR. Specifically, `curl` now permits easy configuration of multiple SSL backends (and choosing between / configuring them at run-time).

Therefore, looking at @ras0219-msft 's [comments from that earlier PR](https://github.com/Microsoft/vcpkg/pull/2862#issuecomment-368509443):

> Unfortunately, the winssl/openssl split is not expressed well with features. As mentioned above, Features are designed to map 1:1 with blocks of code/APIs/behavior. Turning on the feature turns on the APIs, turning off the feature removes those APIs. Turning on two features, should enable two sets of APIs. **Put another way, it should always make sense to "turn on all the features!".** 

It now **_can_** make sense to "turn on all the features!" in this context (with `curl`'s support for multiple SSL backends).

> In cases like this where it's two different backends for the same set of APIs, we'd ideally like to have one feature (say ssl) which represents the APIs that downstream code will consume with some other mechanism to choose the implementation. At the moment, the best mechanism is a setting in the triplet file, however that (unfortunately) isn't able to change the dependencies list. This is an area we need to improve upon, but it should work well enough for now.

This part, however, still doesn't have a perfect solution.

- It's possible that a dependent / downstream port could require `curl` with a specific SSL backend (or one of several), [as there are some differences in behavior / feature support](https://curl.haxx.se/docs/ssl-compared.html).
- It's also possible that a dependent / downstream port may simply require `curl` SSL support (i.e. _any_ SSL backend).

I'm wondering if @ras0219-msft may have some new thoughts, given the above changes.

**Comment by pravic** [comment]
@past-due 

> curl now permits easy configuration of multiple SSL backends (and choosing between / configuring them at run-time)

My main aim with Schannel was to eliminate linking of OpenSSL (among native certificates support). You are offering to link all backends, which will bloat curl and other libraries/applications that use it.

**Comment by past-due** [comment]
@pravic:

To clarify, this PR (as it currently stands) offers the option to link 0, 1, _or_ multiple SSL backends.

I'm with you on wanting the ability to link to just "WinSSL" (Schannel) on Windows, or (for example) just "DarwinSSL" (Secure Transport) on macOS. Someone else may want to link only OpenSSL on Windows. Etc.

My comments were an attempt to articulate that:
- It now _may_ be desirable to link more than one SSL backend (in some circumstances), and so the option should be available
- Linking more than one SSL backend is explicitly supported by the latest `curl` (with the option to select at run-time)
- It may be desirable to specify a dependency on curl linked to a specific SSL backend (or one from a set), [as their behavior / feature support differs](https://curl.haxx.se/docs/ssl-compared.html)
- It would be really nice if we could somehow support all of this in vcpkg without resorting to modifying the triplet (and adding more and more flags that need to go in the triplet)

**Comment by ras0219-msft** [comment]
Sorry for the long delay on this PR!

Here's the current situation as I see it:

1. We want to enable WinSSL as one of the default built backends on Windows
2. Existing users of curl are unlikely to expect multiple backends, since this feature was only recently added
3. Curl, given WinSSL and OpenSSL, will choose WinSSL by default as the current backend

Therefore, no matter what we do, existing users _will_ experience the change of moving from the current Openssl default to WinSSL in their existing programs. The only way that they will be unaffected is if they had code to explicitly set the backend back to openssl, which we expect isn't in widespread use since it was very recently added.

Therefore, it doesn't make sense to emphasize back-compat here because the segment of users who will be able to take advantage of that is diminishingly small -- instead, we should fully convert to the desired target of WinSSL by default on Windows, and OpenSSL by default on other platforms.

This has the side benefit of removing the openssl dependency on windows by default :)

I've made the changes mentioned above while merging. Thanks again to everyone who contributed to this awesome PR!

**Pull request merged**
