### PR TITLE
Ceres and SuiteSparse features

### PR DESCRIPTION
**Pull request by KindDragon**

### CODE REVIEW

**Comment by jasjuang** [comment]
I tested this and everything compiles like usual for me

**Comment by KindDragon** [comment]
@jasjuang You mean everything ok or everything compiles even if you trying to install ceres[core]? :)

**Comment by jasjuang** [comment]
I tested `vcpkg install ceres` and `vcpkg install ceres[lapack,suitesparse, cxsparse, eigen]` and both works

**Comment by ras0219-msft** [comment]
Thanks! While testing, I noticed that eigen was actually called at the top level like:

```cmake
find_package(Eigen3 REQUIRED)
```

so I've lifted that requirement up to the top of the package.

**Pull request merged**
