### PR TITLE
[highfive] Update to 2.2.2

### PR DESCRIPTION
**Pull request by ZeeWanderer**
Updates highfive to 2.2.2.

Note: Generally highfive should be updated together with hdf5 because otherwise it would result in the current situation of highfive successfully installing(it is header-only after all) but not actually working with the current vcpkg distributed hdf5 version.

### CODE REVIEW

**Review by PhoebeHui — APPROVED** [review]
Thanks for the PR!

**Comment by BillyONeal** [comment]
>Note: Generally highfive should be updated together with hdf5 because otherwise it would result in the current situation of highfive successfully installing(it is header-only after all) but not actually working with the current vcpkg distributed hdf5 version.

@ZeeWanderer Can you add a test (or at least a comment) about this? Because we're not going to remember :)

**Comment by ZeeWanderer** [comment]
Where do I add the commentary and how do I go about adding tests? I added unit tests feature so if it compiles and tests pass then all is ok. Do I need to add tests to the CI or something?

**Comment by BillyONeal** [comment]
>Where do I add the commentary

In the hdf5 `portfile.cmake`.

> how do I go about adding tests?

Any means in `portfile.cmake` to check that the resulting headers and HDF5 work together.

If there's not a good way to check that these are compatible a comment is fine.

**Comment by BillyONeal** [comment]
Sorry for the CI hiccup; assuming that comes back OK I'll merge this. Thanks for your contribution!

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
