### PR TITLE
Change Nuget binary cache pre-release info to always start with letters

### LINKED ISSUE #14542: When uploading to Nuget, the SemVer version might be invalid
**Describe the bug**
The current format is `<version>-<hash>`, but the hash might start with a leading 0, which is illegal syntax under SemVer 2.0.0.
For example, if the package is named `1.73.0-0eee625fae7ef2f8964954575ab351ff5916ae83`, it would be parsed as Version "1.73.0" and pre-release info "0eee625fae7ef2f8964954575ab351ff5916ae83", but the leading 0 is invalid here since this is not a numeric identifier. See the [full spec here](https://semver.org/#backusnaur-form-grammar-for-valid-semver-versions).

**Environment**
- OS: Windows 10
- Compiler: msvc 19.28.29333

**To Reproduce**
1. Configure binary caching on Nuget server
2. vcpkg install (any package)
3. after compilation, package is pushed to Nuget server
4. Open up a browser and navigate to your Nuget server's package search page. Look for the package just uploaded.
Notice that the UI (I'm using Baget server) is all weird, because of Node's semver library unable to parse the versions correctly.

**Expected behavior**
The version of the nuget package should be a valid SemVer string. One way to achieve that would be to simply prepend a non-digit in front of the hash, like "1.73.0-**h**0eee625fae7ef2f8964954575ab351ff5916ae83"

**Failure logs** 
I had to create a sandboxed Node.js project to verify all this, so I don't have a failure log to provide.

**Additional context**
Why does vcpkg chose to use "pre-release information" to store the hash? It would be more semantically correct to use "build metadata", since this is exactly what this hash represents: the complete information about the build environment. But one has to consider the implication about version precedence: the pre-release info is part of the precedence, while build metadata is not. However I would argue that since it is a hash, and thus randomly distributed, the ordering is already broken, and it would be better to just remove that hash from the ordering.

### PR DESCRIPTION
**Pull request by frivard-coveo**
**Describe the pull request**

- What does your PR fix? Fixes #14542

- Which triplets are supported/not supported? Have you updated the CI baseline? Not applicable, this PR affects the "tool" vcpkg.exe

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)? Yes. I ran the full test suite and everything passes.

### CODE REVIEW

**Comment by frivard-coveo** [comment]
After some testing, dropping the pre-release information alters the filename, which causes more problems since the filename, which is used directly for a search on the nuget source, no longer contains any abi info.
I switched to the other proposed solution, which is to always start the pre-release info with some letters.

**Comment by JackBoosY** [comment]
cc @ras0219

**Review by ras0219 — APPROVED** [review]

**Comment by frivard-coveo** [comment]
The failing check is for port `sophus`, and the error is :
```
ninja: error: 'D:/installed/x64-windows-static/debug/lib/openblas.lib', needed by 'test/ceres/test_ceres_se3.exe', missing and no known rule to make it
```
which is not related to my PR. Is it possible that it was already broken?

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
