### PR TITLE
[aws-sdk-cpp] update port to v1.11.65

### LINKED ISSUE #31090: [aws-sdk-cpp] update to 1.11.63
### Library name

aws-sdk-cpp

### New version number

1.11.63

### Other information that may be useful (release notes, etc...)

There is a deadlock confirmed from version `1.10.23` up to `1.11.43`, see aws/aws-sdk-cpp#2251. Hence, we should use a version >= `1.11.43`.

### PR DESCRIPTION
**Pull request by anders-wind**
This PR updates the aws-sdk-cpp from v1.11.4 to v1.11.65.
Fixes https://github.com/microsoft/vcpkg/issues/31090

- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

Updating because they fixed a [memory leak](https://github.com/aws/aws-sdk-cpp/issues/2331) which is blocking us from updating to the newest vcpkg release.

### CODE REVIEW

**Comment by anders-wind** [comment]
I still need to update the sha512 for the library.

**Comment by anders-wind** [comment]
Should I still tick the 3 missing checkboxes if I dont think this PR affects those points?

**Comment by anders-wind** [comment]
I see that the patches don't work anymore. I'll try to see if I can fix that.

**Comment by anders-wind** [comment]
The windows build error seem to be related to a warning being treated as an error (install-x64-windows-dbg-out.log):
```
[70/77] C:\PROGRA~1\MICROS~1\2022\ENTERP~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\cl.exe   /TP -DAWS_AUTH_USE_IMPORT_EXPORT -DAWS_CAL_USE_IMPORT_EXPORT -DAWS_CHECKSUMS_USE_IMPORT_EXPORT -DAWS_COMMON_USE_IMPORT_EXPORT -DAWS_COMPRESSION_USE_IMPORT_EXPORT -DAWS_CORE_EXPORTS=1 -DAWS_CRT_CPP_USE_IMPORT_EXPORT -DAWS_EVENT_STREAM_USE_IMPORT_EXPORT -DAWS_HTTP_USE_IMPORT_EXPORT -DAWS_IO_USE_IMPORT_EXPORT -DAWS_MQTT_USE_IMPORT_EXPORT -DAWS_MQTT_WITH_WEBSOCKETS -DAWS_S3_USE_IMPORT_EXPORT -DAWS_SDKUTILS_USE_IMPORT_EXPORT -DAWS_SDK_VERSION_MAJOR=1 -DAWS_SDK_VERSION_MINOR=11 -DAWS_SDK_VERSION_PATCH=37 -DAWS_TEST_REGION=US_EAST_1 -DAWS_USE_IO_COMPLETION_PORTS -DENABLED_REQUEST_COMPRESSION -DENABLED_ZLIB_REQUEST_COMPRESSION -DENABLE_BCRYPT_ENCRYPTION -DENABLE_CURL_LOGGING -DENABLE_WINDOWS_CLIENT -DPLATFORM_WINDOWS -DUSE_IMPORT_EXPORT=1 -DUSE_WINDOWS_DLL_SEMANTICS -DWINHTTP_HAS_H2 -DWININET_HAS_H2 -Daws_cpp_sdk_core_EXPORTS -ID:\buildtrees\aws-sdk-cpp\src\1.11.37-4e3e990eb0.clean\src\aws-cpp-sdk-core\include\aws\core\platform\refs -ID:\buildtrees\aws-sdk-cpp\src\1.11.37-4e3e990eb0.clean\src\aws-cpp-sdk-core\include -external:ID:\installed\x64-windows\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W4 /utf-8 /GR /EHsc /MP  /MP /bigobj /utf-8 /WX /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /Fosrc\aws-cpp-sdk-core\CMakeFiles\aws-cpp-sdk-core.dir\ub_core.cpp.obj /Fdsrc\aws-cpp-sdk-core\CMakeFiles\aws-cpp-sdk-core.dir\ /FS -c D:\buildtrees\aws-sdk-cpp\x64-windows-dbg\src\aws-cpp-sdk-core\ub_core.cpp
FAILED: src/aws-cpp-sdk-core/CMakeFiles/aws-cpp-sdk-core.dir/ub_core.cpp.obj 
C:\PROGRA~1\MICROS~1\2022\ENTERP~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\cl.exe   /TP -DAWS_AUTH_USE_IMPORT_EXPORT -DAWS_CAL_USE_IMPORT_EXPORT -DAWS_CHECKSUMS_USE_IMPORT_EXPORT -DAWS_COMMON_USE_IMPORT_EXPORT -DAWS_COMPRESSION_USE_IMPORT_EXPORT -DAWS_CORE_EXPORTS=1 -DAWS_CRT_CPP_USE_IMPORT_EXPORT -DAWS_EVENT_STREAM_USE_IMPORT_EXPORT -DAWS_HTTP_USE_IMPORT_EXPORT -DAWS_IO_USE_IMPORT_EXPORT -DAWS_MQTT_USE_IMPORT_EXPORT -DAWS_MQTT_WITH_WEBSOCKETS -DAWS_S3_USE_IMPORT_EXPORT -DAWS_SDKUTILS_USE_IMPORT_EXPORT -DAWS_SDK_VERSION_MAJOR=1 -DAWS_SDK_VERSION_MINOR=11 -DAWS_SDK_VERSION_PATCH=37 -DAWS_TEST_REGION=US_EAST_1 -DAWS_USE_IO_COMPLETION_PORTS -DENABLED_REQUEST_COMPRESSION -DENABLED_ZLIB_REQUEST_COMPRESSION -DENABLE_BCRYPT_ENCRYPTION -DENABLE_CURL_LOGGING -DENABLE_WINDOWS_CLIENT -DPLATFORM_WINDOWS -DUSE_IMPORT_EXPORT=1 -DUSE_WINDOWS_DLL_SEMANTICS -DWINHTTP_HAS_H2 -DWININET_HAS_H2 -Daws_cpp_sdk_core_EXPORTS -ID:\buildtrees\aws-sdk-cpp\src\1.11.37-4e3e990eb0.clean\src\aws-cpp-sdk-core\include\aws\core\platform\refs -ID:\buildtrees\aws-sdk-cpp\src\1.11.37-4e3e990eb0.clean\src\aws-cpp-sdk-core\include -external:ID:\installed\x64-windows\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W4 /utf-8 /GR /EHsc /MP  /MP /bigobj /utf-8 /WX /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /Fosrc\aws-cpp-sdk-core\CMakeFiles\aws-cpp-sdk-core.dir\ub_core.cpp.obj /Fdsrc\aws-cpp-sdk-core\CMakeFiles\aws-cpp-sdk-core.dir\ /FS -c D:\buildtrees\aws-sdk-cpp\x64-windows-dbg\src\aws-cpp-sdk-core\ub_core.cpp
D:/buildtrees/aws-sdk-cpp/src/1.11.37-4e3e990eb0.clean/src/aws-cpp-sdk-core/source/client/RequestCompression.cpp(159): error C2220: the following warning is treated as an error
D:/buildtrees/aws-sdk-cpp/src/1.11.37-4e3e990eb0.clean/src/aws-cpp-sdk-core/source/client/RequestCompression.cpp(159): warning C4267: '=': conversion from 'size_t' to 'uInt', possible loss of data
D:/buildtrees/aws-sdk-cpp/src/1.11.37-4e3e990eb0.clean/src/aws-cpp-sdk-core/source/client/RequestCompression.cpp(280): warning C4267: '=': conversion from 'size_t' to 'uInt', possible loss of data
[71/77] C:\PROGRA~1\MICROS~1\2022\ENTERP~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\cl.exe   /TP -DAWS_AUTH_USE_IMPORT_EXPORT -DAWS_CAL_USE_IMPORT_EXPORT -DAWS_CHECKSUMS_USE_IMPORT_EXPORT -DAWS_COMMON_USE_IMPORT_EXPORT -DAWS_COMPRESSION_USE_IMPORT_EXPORT -DAWS_CRT_CPP_USE_IMPORT_EXPORT -DAWS_DYNAMODB_EXPORTS -DAWS_EVENT_STREAM_USE_IMPORT_EXPORT -DAWS_HTTP_USE_IMPORT_EXPORT -DAWS_IO_USE_IMPORT_EXPORT -DAWS_MQTT_USE_IMPORT_EXPORT -DAWS_MQTT_WITH_WEBSOCKETS -DAWS_S3_USE_IMPORT_EXPORT -DAWS_SDKUTILS_USE_IMPORT_EXPORT -DAWS_SDK_VERSION_MAJOR=1 -DAWS_SDK_VERSION_MINOR=11 -DAWS_SDK_VERSION_PATCH=37 -DAWS_TEST_REGION=US_EAST_1 -DAWS_USE_IO_COMPLETION_PORTS -DENABLED_REQUEST_COMPRESSION -DENABLED_ZLIB_REQUEST_COMPRESSION -DENABLE_BCRYPT_ENCRYPTION -DENABLE_WINDOWS_CLIENT -DPLATFORM_WINDOWS -DUSE_IMPORT_EXPORT=1 -DUSE_WINDOWS_DLL_SEMANTICS -Daws_cpp_sdk_dynamodb_EXPORTS -ID:\buildtrees\aws-sdk-cpp\src\1.11.37-4e3e990eb0.clean\generated\src\aws-cpp-sdk-dynamodb\include -ID:\buildtrees\aws-sdk-cpp\src\1.11.37-4e3e990eb0.clean\src\aws-cpp-sdk-core\include -external:ID:\installed\x64-windows\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W4 /utf-8 /GR /EHsc /MP  /MP /bigobj /utf-8 /WX /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /Fogenerated\src\aws-cpp-sdk-dynamodb\CMakeFiles\aws-cpp-sdk-dynamodb.dir\ub_DYNAMODB.cpp.obj /Fdgenerated\src\aws-cpp-sdk-dynamodb\CMakeFiles\aws-cpp-sdk-dynamodb.dir\ /FS -c D:\buildtrees\aws-sdk-cpp\x64-windows-dbg\generated\src\aws-cpp-sdk-dynamodb\ub_DYNAMODB.cpp
[72/77] C:\PROGRA~1\MICROS~1\2022\ENTERP~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\cl.exe   /TP -DAWS_AUTH_USE_IMPORT_EXPORT -DAWS_CAL_USE_IMPORT_EXPORT -DAWS_CHECKSUMS_USE_IMPORT_EXPORT -DAWS_COMMON_USE_IMPORT_EXPORT -DAWS_COMPRESSION_USE_IMPORT_EXPORT -DAWS_CRT_CPP_USE_IMPORT_EXPORT -DAWS_EVENT_STREAM_USE_IMPORT_EXPORT -DAWS_HTTP_USE_IMPORT_EXPORT -DAWS_IO_USE_IMPORT_EXPORT -DAWS_MQTT_USE_IMPORT_EXPORT -DAWS_MQTT_WITH_WEBSOCKETS -DAWS_S3_EXPORTS -DAWS_S3_USE_IMPORT_EXPORT -DAWS_SDKUTILS_USE_IMPORT_EXPORT -DAWS_SDK_VERSION_MAJOR=1 -DAWS_SDK_VERSION_MINOR=11 -DAWS_SDK_VERSION_PATCH=37 -DAWS_TEST_REGION=US_EAST_1 -DAWS_USE_IO_COMPLETION_PORTS -DENABLED_REQUEST_COMPRESSION -DENABLED_ZLIB_REQUEST_COMPRESSION -DENABLE_BCRYPT_ENCRYPTION -DENABLE_WINDOWS_CLIENT -DPLATFORM_WINDOWS -DUSE_IMPORT_EXPORT=1 -DUSE_WINDOWS_DLL_SEMANTICS -Daws_cpp_sdk_s3_EXPORTS -ID:\buildtrees\aws-sdk-cpp\src\1.11.37-4e3e990eb0.clean\generated\src\aws-cpp-sdk-s3\include -ID:\buildtrees\aws-sdk-cpp\src\1.11.37-4e3e990eb0.clean\src\aws-cpp-sdk-core\include -external:ID:\installed\x64-windows\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W4 /utf-8 /GR /EHsc /MP  /MP /bigobj /utf-8 /WX /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /Fogenerated\src\aws-cpp-sdk-s3\CMakeFiles\aws-cpp-sdk-s3.dir\ub_S3.cpp.obj /Fdgenerated\src\aws-cpp-sdk-s3\CMakeFiles\aws-cpp-sdk-s3.dir\ /FS -c D:\buildtrees\aws-sdk-cpp\x64-windows-dbg\generated\src\aws-cpp-sdk-s3\ub_S3.cpp
ninja: build stopped: subcommand failed.
```

**Comment by autoantwort** [comment]
> I'm a bit in doubt on how to solve this, so any feedback would be appreciated.

Patch the `/Wx` out :)

**Comment by anders-wind** [comment]
> Patch the /Wx out :)
Ah yea okay that was simple.

**Comment by jimwang118** [comment]
I got an error when I installed the verification locally, please fix this problem, thank you.
step：
`.\vcpkg.exe install aws-sdk-cpp[*]:x64-windows`
log:
```
E:/aws-sdk-cpp/vcpkg/installed -DVCPKG_MANIFEST_INSTALL=OFF
    Working Directory: E:/aws-sdk-cpp/vcpkg/buildtrees/aws-sdk-cpp/x64-windows-dbg
    Error code: 1
    See logs for more information:
      E:\aws-sdk-cpp\vcpkg\buildtrees\aws-sdk-cpp\config-x64-windows-dbg-CMakeCache.txt.log
      E:\aws-sdk-cpp\vcpkg\buildtrees\aws-sdk-cpp\config-x64-windows-dbg-out.log
      E:\aws-sdk-cpp\vcpkg\buildtrees\aws-sdk-cpp\config-x64-windows-dbg-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:263 (vcpkg_execute_required_process)
  ports/aws-sdk-cpp/portfile.cmake:36 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)


error: building aws-sdk-cpp:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+aws-sdk-cpp
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[aws-sdk-cpp]+Build+error
Include '[aws-sdk-cpp] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-03-14-105f7f7e8a5ea10dfac9874ff9d1a6bacba5f454
    vcpkg-scripts version: 02af59c23 2023-03-15 (2 days ago)
```

**Comment by anders-wind** [comment]
"Unfortunately" I'm on vacation for the next 5 weeks. I'll ping one from my team, but I doubt they will have time to fix it.

**Comment by jimwang118** [comment]
> "Unfortunately" I'm on vacation for the next 5 weeks. I'll ping one from my team, but I doubt they will have time to fix it.

Ok, I'll try to fix it as well as I can.

**Comment by jimwang118** [comment]
@anders-wind Do you have time now to fix its installation issues?

**Comment by LilyWangLL** [comment]
@anders-wind Upstream has removed deprecated feature `mobileanalytics`, please remove it from `vcpkg.json`. The related upstream link: https://github.com/aws/aws-sdk-cpp/pull/2163

**Comment by anders-wind** [comment]
> @anders-wind Upstream has removed deprecated feature `mobileanalytics`, please remove it from `vcpkg.json`. The related upstream link: [aws/aws-sdk-cpp#2163](https://github.com/aws/aws-sdk-cpp/pull/2163)

Done 👍

**Review by LilyWangLL — APPROVED** [review]

**Review by jimwang118 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the update!

**Pull request merged**
