### PR TITLE
[pipelines] system.debug true

### PR DESCRIPTION
**Pull request by MVoz**

### CODE REVIEW

**Comment by BillyONeal** [comment]
The change looks correct in that it does what it says, but I'm not sure what for?

Shouldn't we do this for all platforms rather than just Windows?

**Review by BillyONeal — CHANGES_REQUESTED** [review]
I think you need to explain why you want this changed before we change it as it produces significant amounts of irrelevant log spew

**Comment by Voskrese** [comment]
I think it's mostly developers and integrators here, additional information and log files are very useful for analysis

**Comment by BillyONeal** [comment]
I'm less worried about speed and more worried about worried about needing to wade through more log spew.

**Comment by BillyONeal** [comment]
To clarify: I'm not say 'we won't do this'. I'm saying 'it would be nice if there were some concrete justification to do this', for example a specific problem that you are looking to diagnose with the extra output.

**Comment by Voskrese** [comment]
these logs are only visible at the beginning, when loading and initializing the system, and are not visible anywhere else )))

don't like a lot of questions, I'll close PR ))

**Pull request closed without merging**
