### PR TITLE
[geographiclib] Add boost dependencies

### PR DESCRIPTION
**Pull request by mheyman**
**Describe the pull request**

- #### What does your PR fix?
  the geographiclib port depends on some boost:
  - [boost-serialization](https://github.com/sotex/geographiclib/blob/32c76c99ab39810d2055baa20e519bf5048ff322/include/GeographicLib/NearestNeighbor.hpp#L27)
  - [boost-multiprecision](https://github.com/sotex/geographiclib/blob/32c76c99ab39810d2055baa20e519bf5048ff322/include/GeographicLib/Math.hpp#L69)
  - [boost-math](https://github.com/sotex/geographiclib/blob/32c76c99ab39810d2055baa20e519bf5048ff322/include/GeographicLib/Math.hpp#L70)

   This PR places those dependencies in the vcpkg.json file. 

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  all

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  yes

### CODE REVIEW

**Comment by dg0yt** [comment]
IIUC the boost packages are only need for `USE_BOOST_FOR_EXAMPLES` (off by default) and for `GEOGRAPHICLIB_PRECISION EQUAL 4` (but the default, explicitly recommended value is `2`). Cf. the main `CMakeLists.txt`. So this PR is invalid. Do you have particular build problem which you try to fix?

**Comment by mheyman** [comment]
I'm actually using an external library that uses the boost/serialization aspect of `geographiclib`. I believe the external library's authors installed boost and GeograhicLib onto their build machines (as opposed to using vcpkg).

Should I attempt some vcpkg.json-foo to make the boost dependencies only show up with a feature instead of all the time?

**Comment by Adela0814** [comment]
Is there any update? @mheyman

**Comment by Adela0814** [comment]
Close this PR because it is invalid.

**Pull request closed without merging**
