### PR TITLE
[cppgraphqlgen] Update to v3.2.0 and fix #10407

### LINKED ISSUE #10407: [cppgraphqlgen] build failure
**Host Environment**
- OS: Linux
- Compiler: 
gernot@Io:~/Development/vcpkg$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 8.3.0-26ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.3.0 (Ubuntu 8.3.0-26ubuntu1~18.04) 

**To Reproduce**
`./vcpkg install cppgraphqlgen`

**Failure logs** 
gernot@Io:~/Development/vcpkg$ ./vcpkg install cppgraphqlgen
Computing installation plan...
The following packages will be built and installed:
    cppgraphqlgen[core]:x64-linux
Starting package 1/1: cppgraphqlgen:x64-linux
Building package cppgraphqlgen[core]:x64-linux...
-- Using cached /home/gernot/Development/vcpkg/downloads/microsoft-cppgraphqlgen-v3.1.1.tar.gz
-- Using source at /home/gernot/Development/vcpkg/buildtrees/cppgraphqlgen/src/v3.1.1-f2eca4fdc5
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: /home/gernot/Development/vcpkg/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/bin/cmake --build . --config Debug --target install -- -v
    Working Directory: /home/gernot/Development/vcpkg/buildtrees/cppgraphqlgen/x64-linux-dbg
    See logs for more information:
      /home/gernot/Development/vcpkg/buildtrees/cppgraphqlgen/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/cppgraphqlgen/portfile.cmake:17 (vcpkg_install_cmake)
  scripts/ports.cmake:90 (include)

Error: Building package cppgraphqlgen:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: cppgraphqlgen:x64-linux
  Vcpkg version: 2020.02.04-unknownhash

Additionally, attach any relevant sections from the log files above.
gernot@Io:~/Development/vcpkg$ ./vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.
gernot@Io:~/Development/vcpkg$

### PR DESCRIPTION
**Pull request by wravery**
**Describe the pull request**

- What does your PR fix? Fixes issue #

I had a pending change to update to version 3.2.0, and I rolled in the fix for #10407 by upping the commit ID to add the source package fix.

- Which triplets are supported/not supported? Have you updated the CI baseline?

I've tested x64-windows with MSVC and x64-linux with gcc 7.5.0 and 8.3.0.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

Yes.

### CODE REVIEW

**Comment by wravery** [comment]
Looks like the failure for `vcpkg-windows-PR-test` was in an unrelated port/project (`libpq`).

**Comment by Cheney-W** [comment]
@wravery 
The CI system has some issues recently and we are fixing it.
Could you please modify the line 25 of `ports/cppgraphqlgen/portfile.cmake` as below:
`file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)`

**Comment by wravery** [comment]
Ok

**Comment by dan-shaw** [comment]
@wravery thanks for the PR!

**Pull request merged**
