### PR TITLE
[vcpkg/ci] Add Intel compilers to provisioning script on windows.

### PR DESCRIPTION
**Pull request by Neumann-A**
left some unnecessary comments for discussion.
add some additional build system av exclusions. 
script errors if component is already installed.  

cc @BillyONeal 

in my local test PS always asked me for permission to execute/run the process. Don't know how to change that

### CODE REVIEW

**Comment by BillyONeal** [comment]
>in my local test PS always asked me for permission to execute/run the process

Unfortunately that blocks this change because the script is run completely headlessly (it would cause the script to time out and fail).

Tagging "requires: discussion" because I'm not sure how we feel about creating a situation where ports can accidentally depend on icc things in our CI.

**Comment by Neumann-A** [comment]
>Tagging "requires: discussion" because I'm not sure how we feel about creating a situation where ports can accidentally depend on icc things in our CI.

in general that requires running a env setup script beforehand. 

>Unfortunately that blocks this change because the script is run completely headlessly (it would cause the script to time out and fail).

I only tested the part i added. I assumed that the complete script execution somewhere deals with these permission things. It is just Windows asking for allowance to execute.

**Comment by BillyONeal** [comment]
>in general that requires running a env setup script beforehand.

I see, OK then, dropping the tag.

>It is just Windows asking for allowance to execute.

If you mean "user account control" then this runs as local admin so that's already approved.

**Comment by Neumann-A** [comment]
Yes it is UAC. Just tested it again to look at the title of the popup window.

**Comment by BillyONeal** [comment]
@Neumann-A  I'm about to try to roll VMs. Are the URIs etc. herein still what you want?

**Comment by Neumann-A** [comment]
@BillyONeal there is probably an update out by now but i won't be able to check this currently.

**Comment by BillyONeal** [comment]
> @BillyONeal there is probably an update out by now but i won't be able to check this currently.

Would you rather I try to apply this as is or wait?

**Comment by Neumann-A** [comment]
@BillyONeal You can apply it as if. I'll probably be out for a few weeks.

**Comment by BillyONeal** [comment]
```
Downloading Intel oneAPI...to:  C:\Users\Administrator\AppData\Local\Temp\2\a4l2npxk.y4q.exe
Extracting Intel oneAPI...to folder:  C:\Users\Administrator\AppData\Local\Temp\2\f45mdq2i.sl1
Install Intel oneAPI...from folder:  C:\Users\Administrator\AppData\Local\Temp\2\f45mdq2i.sl1

Command line arguments validation error: Invalid value for parameter 'components'.InstallInteloneAPI : Failed to install Intel oneAPI! Installation failed! Exited with 3.
At C:\Users\Administrator\Desktop\provision-image.ps1:513 char:1
+ InstallInteloneAPI -Url $oneAPIHPCUrl -Features $oneAPIHPCComponents
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,InstallInteloneAPI
```

**Comment by BillyONeal** [comment]
:(

**Comment by Neumann-A** [comment]
@BillyONeal Fixed and updated the Installers URLs

**Comment by JackBoosY** [comment]
Seems all check passed, ready for review now?

**Comment by BillyONeal** [comment]
> Seems all check passed, ready for review now?

This one didn't make the train, next attempt will be after Patch Tuesday for May.

**Comment by Neumann-A** [comment]
merged with #18233

**Pull request closed without merging**
