### PR TITLE
Fix a import bug of nuget package, give priority to nuget package to set $(VcpkgRoot). 

### PR DESCRIPTION
**Pull request by shihaonan369**
#6213

### CODE REVIEW

**Comment by dan-shaw** [comment]
I’m going to close this PR because it’s been a long time since any update has been made. If this is something you’d like to see merged and work is being done, please reopen.

**Comment by elviiix** [comment]
If you have vcpkg directory (from where you generated nuget package) on the same computer, when compiling project containing that package VcpkgRoot is set not inside packages directory in your project, but to the vcpkg directory. So it you several versions of package and updated package version in vcpkg - you have wrong headers/libs included. 

Renaming the original version of vcpkg directory solves the problem. Reopen please.

**Comment by shihaonan369** [comment]
During the using process which followed, i got another problem that cause can not use two different packages from nuget package exported and vcpkg installed directory. In fact, that's because of a feature of vcpkg which is cannot import headers form both of them at same time. So import from both of them in following order, that's would be better:
1. Nuget packages
2. Vcpkg installed directory

**Comment by ras0219-msft** [comment]
LGTM, thanks for the PR!

**Pull request merged**
