### PR TITLE
[vcpkg_fixup_pkgconfig] Fix quoting

### LINKED ISSUE #29776: [icu] Link error when linking against ICU on Windows using pkgconfig
**Describe the bug**
Linking against ICU on Windows using pkgconfig results in link error:
```
LINK : fatal error LNK1181: cannot open input file 'kernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -lcomdlg32 -ladvapi32.lib'
```

The reason for error is these lines in icu's pkgconfig files:
```
baselibs = -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -lcomdlg32 -ladvapi32
Libs: "-L${libdir}" -licuuc -licudt "${baselibs}"
```

Notice the quotes around ${baselibs}. This causes them to be passed to linker as a single argument which causes the error.
I suspect that issue lies somewhere in vcpkg_fixup_pkgconfig() since original pkgconfig file in buildtrees doesn't have quotes:
```
Libs.private: ${baselibs}
```

**Environment**
- OS: Windows
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.34.31942 for x64

**To Reproduce**
1. ./vcpkg install icu:x64-windows-static
2. Use pkg-config/pkgconf to get linkflags for icu-uc

icu-uc.pc in buildtrees:
```
# Copyright (C) 2016 and later: Unicode, Inc. and others.
# License & terms of use: http://www.unicode.org/copyright.html
# Copyright (C) 2010-2013, International Business Machines Corporation. All Rights Reserved.

# CFLAGS contains only anything end users should set
CFLAGS = 
# CXXFLAGS contains only anything end users should set
CXXFLAGS = 
# DEFS only contains those UCONFIG_CPPFLAGS which are not auto-set by platform.h
DEFS = 
prefix = /E/projects/libtremotesf/vcpkg_installed/x64-windows-static/debug
exec_prefix = ${prefix}
#bindir = ${prefix}/../tools/icu/debug/bin
libdir = ${prefix}/lib
includedir = ${prefix}/../include
baselibs = -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -lcomdlg32 -ladvapi32
#datarootdir = ${prefix}/share/icu
#datadir = ${datarootdir}
#sbindir = ${prefix}/../tools/icu/debug/sbin
#mandir = ${datarootdir}/man
#sysconfdir = ${prefix}/etc
UNICODE_VERSION=15.0
ICUPREFIX=icu
ICULIBSUFFIX=
LIBICU=lib${ICUPREFIX}
#SHAREDLIBCFLAGS=-fPIC
pkglibdir=${libdir}/icu${ICULIBSUFFIX}/72.1
#pkgdatadir=${datadir}/icu${ICULIBSUFFIX}/72.1
ICUDATA_NAME = icudt72l
#ICUPKGDATA_DIR=${prefix}/lib
#ICUDATA_DIR=${pkgdatadir}
ICUDESC=International Components for Unicode

Version: 72.1
Cflags: -I${includedir}
# end of icu.pc.in
Description: International Components for Unicode: Common and Data libraries
Name: icu-uc
Libs: -L${libdir} -licuucd -licudtd
Libs.private: ${baselibs}
```

Installed icu-uc.pc:
```
prefix=${pcfiledir}/../..
# Copyright (C) 2016 and later: Unicode, Inc. and others.
# License & terms of use: http://www.unicode.org/copyright.html
# Copyright (C) 2010-2013, International Business Machines Corporation. All Rights Reserved.

# CFLAGS contains only anything end users should set
CFLAGS = 
# CXXFLAGS contains only anything end users should set
CXXFLAGS = 
# DEFS only contains those UCONFIG_CPPFLAGS which are not auto-set by platform.h
DEFS = 
exec_prefix = ${prefix}
#bindir = ${prefix}/../tools/icu/debug/bin
libdir = ${prefix}/lib
includedir = ${prefix}/../include
baselibs = -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -lcomdlg32 -ladvapi32
#datarootdir = ${prefix}/../share/icu
#datadir = ${datarootdir}
#sbindir = ${prefix}/../tools/icu/debug/sbin
#mandir = ${datarootdir}/man
#sysconfdir = ${prefix}/etc
UNICODE_VERSION=15.0
ICUPREFIX=icu
ICULIBSUFFIX=
LIBICU=lib${ICUPREFIX}
#SHAREDLIBCFLAGS=-fPIC
pkglibdir=${libdir}/icu${ICULIBSUFFIX}/72.1
#pkgdatadir=${datadir}/icu${ICULIBSUFFIX}/72.1
ICUDATA_NAME = icudt72l
#ICUPKGDATA_DIR=${prefix}/lib
#ICUDATA_DIR=${pkgdatadir}
ICUDESC=International Components for Unicode

Version: 72.1
# end of icu.pc.in
Description: International Components for Unicode: Common and Data libraries
Name: icu-uc

Libs: "-L${libdir}" -licuucd -licudtd "${baselibs}"
Cflags: "-I${includedir}"
```

### PR DESCRIPTION
**Pull request by dg0yt**
Fixes #29776 (regression).

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by dg0yt** [comment]
`icu-uc.pc` now (x64-mingw-static):
~~~
...
Libs: "-L${libdir}" -licuuc -licudt ${baselibs}
Cflags: "-I${includedir}"
~~~

**Comment by equeim** [comment]
BTW Original icu-uc.pc also doesn't have quotes around `-I${includedir}` and `-L${libdir}`. I'm not sure whether this can be an issue but maybe vcpkg_fixup_pkgconfig just shouldn't add quotes when there weren't any in original file?

**Comment by Neumann-A** [comment]
> BTW Original icu-uc.pc also doesn't have quotes around -I${includedir} and -L${libdir}. I'm not sure whether this can be an issue but maybe vcpkg_fixup_pkgconfig just shouldn't add quotes when there weren't any in original file?

No that is requirement to support paths with spaces. An no it is generally not an issue.

**Comment by dg0yt** [comment]
> BTW Original icu-uc.pc also doesn't have quotes around `-I${includedir}` and `-L${libdir}`. I'm not sure whether this can be an issue but maybe `vcpkg_fixup_pkgconfig` just shouldn't add quotes when there weren't any in original file?

For these flags, this has been a feature of `vcpkg_fixup_pkgconfig` for a while. AFAICT the quoting is meant to deal with space characters in paths. Most upstreams don't handle this case at all.

**Comment by dg0yt** [comment]
> litehtml:arm64-windows failed with FILE_CONFLICTS.

We need a PR check against file lists from full CI.

**Comment by dg0yt** [comment]
And now the next baseline regression:
~~~
FAILED: CMakeFiles/MNNMath.dir/source/math/Matrix.cpp.o 
/usr/bin/c++ -DDEBUG -DMNN_DEBUG -DMNN_DEBUG_MEMORY -DMNN_DEBUG_TENSOR_SIZE -DMNN_SUPPORT_TFLITE_QUAN -DMNN_USE_SSE -DMNN_USE_THREAD_POOL -DMNN_VERSION=\"1.1.0.0-d6795ad\" -DMNN_VERSION_MAJOR=1 -DMNN_VERSION_MINOR=1 -DMNN_VERSION_PATCH=0 -I/mnt/vcpkg-ci/buildtrees/mnn/src/1.1.0-9f04ab166e.clean/include -I/mnt/vcpkg-ci/buildtrees/mnn/src/1.1.0-9f04ab166e.clean/source -I/mnt/vcpkg-ci/buildtrees/mnn/src/1.1.0-9f04ab166e.clean/express -I/mnt/vcpkg-ci/buildtrees/mnn/src/1.1.0-9f04ab166e.clean/tools -I/mnt/vcpkg-ci/buildtrees/mnn/src/1.1.0-9f04ab166e.clean/schema/current -I/mnt/vcpkg-ci/buildtrees/mnn/src/1.1.0-9f04ab166e.clean/3rd_party/half -I/mnt/vcpkg-ci/installed/x64-linux/share/rapidjson/../../include -isystem /mnt/vcpkg-ci/installed/x64-linux/include -fPIC -std=c++11 -D__STRICT_ANSI__ -g -fstrict-aliasing -ffunction-sections -fdata-sections -ffast-math -fno-rtti -fno-exceptions  -g   -fPIC -std=gnu++11 -MD -MT CMakeFiles/MNNMath.dir/source/math/Matrix.cpp.o -MF CMakeFiles/MNNMath.dir/source/math/Matrix.cpp.o.d -o CMakeFiles/MNNMath.dir/source/math/Matrix.cpp.o -c /mnt/vcpkg-ci/buildtrees/mnn/src/1.1.0-9f04ab166e.clean/source/math/Matrix.cpp
In file included from /mnt/vcpkg-ci/installed/x64-linux/include/absl/base/config.h:86,
                 from /mnt/vcpkg-ci/installed/x64-linux/include/absl/base/attributes.h:37,
                 from /mnt/vcpkg-ci/installed/x64-linux/include/absl/strings/string_view.h:39,
                 from /mnt/vcpkg-ci/installed/x64-linux/include/flatbuffers/base.h:237,
                 from /mnt/vcpkg-ci/installed/x64-linux/include/flatbuffers/array.h:22,
                 from /mnt/vcpkg-ci/installed/x64-linux/include/flatbuffers/flatbuffers.h:24,
                 from /mnt/vcpkg-ci/buildtrees/mnn/src/1.1.0-9f04ab166e.clean/schema/current/Tensor_generated.h:7,
                 from /mnt/vcpkg-ci/buildtrees/mnn/src/1.1.0-9f04ab166e.clean/source/core/TensorUtils.hpp:13,
                 from /mnt/vcpkg-ci/buildtrees/mnn/src/1.1.0-9f04ab166e.clean/source/math/Matrix.cpp:12:
/mnt/vcpkg-ci/installed/x64-linux/include/absl/base/policy_checks.h:79:2: error: #error "C++ versions less than C++14 are not supported."
   79 | #error "C++ versions less than C++14 are not supported."
      |  ^~~~~
~~~
I was afraid that something like this would happen with #29692. CC @coryan

**Comment by coryan** [comment]
Sorry about this.  It seems that flatbuffers fixed this upstream:

https://github.com/google/flatbuffers/pull/7824

Could we apply the same patch here?

Mostly so I can explain to myself what happened here: it is a bit of a mess, the flatbuffers port in vcpkg does not depend on Abseil (flatbuffers compiles fine without it).  So it was not recompiled / tested when I updated Abseil.  However, flatbuffers will try to use Abseil if it is present, for example, if it has been installed by another port that depends on Abseil and on flatbuffers.

BTW, this suggests the flatbuffers port does not have a stable ABI, even after installed.  If I install the flatbuffers port I get one definition of this class:

https://github.com/google/flatbuffers/blob/f7a75173f171b5edae59a1ff28e5b408057e60ac/include/flatbuffers/string.h#L30-L34

But if I later I install Abseil then I get a different definition, because now the header may be able to find `absl/strings/string_view.h`.


/FYI: @devjgm

**Comment by coryan** [comment]
As you may have noticed I just sent #29974.  Hopefully that will merged soon and unblock your work here.

**Comment by dg0yt** [comment]
Ping @Cheney-W @jimwang118  for review.

**Review by Cheney-W — APPROVED** [review]

**Pull request merged**
