### PR TITLE
[ci] Attempt to make CI more reliable by using robocopy to delete

### PR DESCRIPTION
**Pull request by BillyONeal**
...  buildtrees, packages, and installed, before doing the normal ciclean.

### CODE REVIEW

**Comment by dg0yt** [comment]
I was wondering if "rename, then remove in background" might improve decoupling and performance.

**Comment by BillyONeal** [comment]
> I was wondering if "rename, then remove in background" might improve decoupling and performance.

The problems we've had in the past have all been running programs, and my understanding is that rename is no help there. Maybe nice perf someday...

**Comment by cenit** [comment]
just by letting the CI go without being able to complete the delete phase ;)
for sure not a final fix, but something that might be interesting

**Comment by cenit** [comment]
understood, a broken approach to say a final word on it. Thanks for explaining

**Comment by dg0yt** [comment]
Can't the CI just start with a new "active" path each time, and still cleanup the "inactive" paths in the background?

**Pull request merged**
