### PR TITLE
[catch2] Fix wrong lib Catch2WithMain dir

### LINKED ISSUE #31774: [Catch2] Wrong libdir in Catch2Main.pc
### Is your feature request related to a problem? Please describe.

Catch2Main.pc libdir ist set to prefix/lib but the catch2main.lib was moved to manual-link

### Proposed solution

change the libdir var to prefix/lib/manual-link

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by FrankXie05**
Fix https://github.com/microsoft/vcpkg/issues/31774

Note: The function of [`manual-link`](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md#place-conflicting-libs-in-a-manual-link-directory)  is to solve the conflict problem of the library, and the `Catch2WithMain `does not conflict with other libraries, so it does not need to be put into the `manual-link`.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] ~~SHA512s are updated for each updated download~~
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by Neumann-A** [comment]
> Note: The function of [manual-link](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md#place-conflicting-libs-in-a-manual-link-directory) is to solve the conflict problem of the library, and the Catch2WithMain does not conflict with other libraries, so it does not need to be put into the manual-link.

Wrong. The included `main()` part is the conflicting one which is why you cannot/shouldn't auto-link it in msbuild.

**Comment by FrankXie05** [comment]
@Neumann-A So, you mean that we should install the lib `Catch2WithMain` to `${CMAKE_INSTALL_PREFIX}/lib/manual-link`?

**Comment by Neumann-A** [comment]
> So, you mean that we should install the lib Catch2WithMain to ${CMAKE_INSTALL_PREFIX}/lib/manual-link?

Yes. https://github.com/microsoft/vcpkg/issues/31774 only speaks about correcting the generated *.pc file.

**Comment by FrankXie05** [comment]
Ok, I will fix this patch.

**Comment by dg0yt** [comment]
I don't understand the changes. Isn't it enough to do `vcpkg_replace_string` on the installed pc files in the portfile?

**Comment by FrankXie05** [comment]
> I don't understand the changes. Isn't it enough to do `vcpkg_replace_string` on the installed pc files in the portfile?

Can you explain in detail `vcpkg_replace_string`?

**Comment by dg0yt** [comment]
#32047

It is concerning if the community needs to explain `manual-link` and `vcpkg_replace_string`.

**Comment by FrankXie05** [comment]
Duplicate of https://github.com/microsoft/vcpkg/pull/32047

**Pull request closed without merging**
