### PR TITLE
[libarchive] Update to 3.4.3

### LINKED ISSUE #13170: [libarchive] update to 3.4.3
Library name: libarchive

New version number: 3.4.3

https://github.com/libarchive/libarchive/commit/fc6563f5130d8a7ee1fc27c0e55baef35119f26c

### PR DESCRIPTION
**Pull request by JonLiu1993**
Fix #13170 

Update libarchive to the latest version 3.4.3

All features are tested successfully in the following triplets:

- x86-windows
- x64-windows
- x64-windows-static
- arm64-windows

### CODE REVIEW

**Review by NancyLi1013 — APPROVED** [review]

**Review by BillyONeal — APPROVED** [review]

**Comment by NancyLi1013** [comment]
The regressions on x64-linux are due to this, which is not related with this PR.

```
CMake Error at /agent/_work/1/s/scripts/buildsystems/vcpkg.cmake:461 (_find_package):
  Found package configuration file:

    /mnt/vcpkg-ci/installed/x64-linux/share/suitesparse/suitesparse-config.cmake

  but it set suitesparse_FOUND to FALSE so package "suitesparse" is
  considered to be NOT FOUND.  Reason given by package:

  suitesparse could not be found because dependency LAPACK could not be
  found.
```

**Comment by JackBoosY** [comment]
The regressions will be solved in another PR.

**Comment by BillyONeal** [comment]
https://github.com/microsoft/vcpkg/pull/13229 @NancyLi1013 This one?

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
