### PR TITLE
[wip] Fix CMAKE_SYSTEM_PROCESSOR (Resubmission of #4688)

### PR DESCRIPTION
**Pull request by vicroms**
Related PRs:
#4970
#4688
#5218 

#4688 was reverted due to regressions

Quoting @UnaNancyOwen:
> In case of UWP and Linux triplets, `CMAKE_SYSTEM_PROCESSOR` is not specified. It is empty.
For details this problems, Please refer to this comment #4635 (comment).
This pull request will set `CMAKE_SYSTEM_PROCESSOR` under UWP and Linux triplets.
If you want to explicitly specified CPU arcitecture, You can use `VCPKG_CMAKE_SYSTEM_PROCESSOR` in triplet files.

### CODE REVIEW

**Comment by vicroms** [comment]
# Current Regressions Status

x64-windows|x64-windows-static|arm64-windows|x86-windows|x64-linux|x64-uwp|arm-uwp
--|--|--|--|--|--|--
darknet|darknet|liblemon|anax|azure-storage-cpp|ffmpeg|ms-angle
ffmpeg|glew|ms-angle|darknet|caffe2|libvpx|openssl-uwp
icu|liblemon|rxqt|ismrmrd|collada-dom|ms-angle|
ismrmrd|ms-angle||liblemon|rxqt|openssl-uwp|
liblemon|netcdf-c||magnum|z3|rxqt|
libvpx|ogdf||ms-angle||x264|
magnum|openssl-windows||octomap|||
ms-angle|tbb||ogdf|||
octomap|vxl||ogre|||
ogdf|||openssl-windows|||
ogre|||tbb|||
openssl-windows|||vxl|||
rxqt||||||
tbb||||||
vxl||||||
x264||||||

**Comment by cenit** [comment]
For darknet static I can open a PR. It is just a matter of a bug in the findpthreads_windows.cmake which is fixed in a PR upstream ( we are still testing it) and which I can submit also here. It should not have passed CI tests for static from the beginning...

**Comment by cenit** [comment]
also many of those ports are fixed in my #5169 PR, if you don't want to duplicate efforts

**Comment by vicroms** [comment]
@cenit 
Ok! Let's work on getting #5169 merged!

**Pull request closed without merging**
