### PR TITLE
Tesseract-OCR library

### PR DESCRIPTION
**Pull request by KindDragon**

### CODE REVIEW

**Comment by codicodi** [comment]
Config files for both libraries use hardcoded paths to `packages/` directory so `vcpkg export` wouldn't work with them :(

Additionally, looks like leptonica's dependency on openjpeg is not consumed:
```
Dump of file .\installed\x64-windows\bin\leptonica-1.74.4.dll

File Type: DLL

  Image has the following dependencies:

    jpeg62.dll
    libpng16.dll
    tiff.dll
    zlib1.dll
    KERNEL32.dll
    USER32.dll
    GDI32.dll
    VCRUNTIME140.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-math-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-utility-l1-1-0.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-convert-l1-1-0.dll
    api-ms-win-crt-environment-l1-1-0.dll
    api-ms-win-crt-time-l1-1-0.dll
    api-ms-win-crt-filesystem-l1-1-0.dll
```

**Comment by KindDragon** [comment]
> Additionally, looks like leptonica's dependency on openjpeg is not consumed:

Maybe it using only headers
```
-- Looking for include file openjpeg-2.0/openjpeg.h
-- Looking for include file openjpeg-2.0/openjpeg.h - not found
-- Looking for include file openjpeg-2.1/openjpeg.h
-- Looking for include file openjpeg-2.1/openjpeg.h - found
-- Looking for include file openjpeg-2.2/openjpeg.h
-- Looking for include file openjpeg-2.2/openjpeg.h - not found
```

**Comment by codicodi** [comment]
I don't think so, openjpeg isn't really usable that way. My guess would be that leptonica doesn't look correctly for the binaries:
https://github.com/DanBloomberg/leptonica/blob/master/CMakeLists.txt#L57-L62

BTW giflib is not listed in `Build-Depends`, but is picked up if present

**Comment by codicodi** [comment]
Wait, `openjpeg-2.1/openjpeg.h` should be there. I guess you didn't update openjpeg to 2.2.0?

**Comment by KindDragon** [comment]
Ok, I'll remove openjpeg from dependencies

> Config files for both libraries use hard coded paths to packages/ directory so vcpkg export wouldn't work with them :(

We had a lot of libraries with full-path to vcpkg `packages` or `installed` subdirectory. This problem can be addressed in separate PR

**Comment by ras0219-msft** [comment]
Thanks for the PR!

**Pull request merged**
