### PR TITLE
[freeimage] Enable version information in FreeImage.dll

### LINKED ISSUE #19605: [freeimage] FreeImage.dll missing version information
While integrating with FreeImage as built from `vcpkg install freeimage`, I noticed that the DLL is not built with version information. This information does exist in the binaries available from the FreeImage homepage, and the .rc file that supplies this information exists in the source zip that the port downloads to build, so I suspect its omission here was a mistake.

**Proposed solution**
I believe the fix is as simple as adding the .rc file to the DLL's sources in the port's CMakeLists.txt as such:
```cmake
# change this line: 
add_library(FreeImage ${SRCS} ${PRIVATE_HEADERS} ${PUBLIC_HEADERS})

# to this:
add_library(FreeImage ${SRCS} ${PRIVATE_HEADERS} ${PUBLIC_HEADERS}
                      ${CMAKE_CURRENT_SOURCE_DIR}/FreeImage.rc)
```

This mirrors what is currently done for FreeImagePlus.dll ([link](https://github.com/microsoft/vcpkg/blob/99e06a64eca28a9af2b9e5544459e60fa40d19fd/ports/freeimage/CMakeLists.txt#L117-L120)).

**Additional context**
The use-case that led me to find this is that I am trying to include this DLL in an MSI-based installer. In upgrade scenarios, the unversioned DLL fails to install correctly due to the [file versioning rules](https://docs.microsoft.com/en-us/windows/win32/msi/file-versioning-rules).

If this is not an intended use case, or if the omission of this information was intentional, then I can almost certainly find a different solution for my needs.

### PR DESCRIPTION
**Pull request by NancyLi1013**
**Describe the pull request**

- #### What does your PR fix?  
  Fixes #19605 

Add `FreeImage.rc` to build `FreeImage ` to enable the version information showed in `Freeimage.dll`.

Note: No feature needs to test.

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
Depends on https://github.com/microsoft/vcpkg/pull/19633.

**Comment by JackBoosY** [comment]
Depends on https://github.com/microsoft/vcpkg/pull/19628.

**Review by BillyONeal — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the bugfix!

**Pull request merged**
