### PR TITLE
[OpenMVS] fix OpenMP feature on linux for downstream projects

### PR DESCRIPTION
**Pull request by cenit**
If OpenMP feature is enabled in OpenMVS, downstream projects have problems linking to OpenMVS in linux.
With this PR the problem is fixed

### CODE REVIEW

**Comment by cenit** [comment]
why CI is not testing `openmvs:x64-linux`? It should build without errors, but here it's flagged as "cascade" failure

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
Since `openmvs `depends on `cgal`, `cgal `also shows `cascade` in CI. `cgal `depends on `mpir`. `mpir ` is set as skip in ci.baseline.txt due to conflicts with `gmp`.

If the dependency is set as fail or skip in ci.baseline.txt, the test result for this port will show `cascade` in CI.

**Comment by NancyLi1013** [comment]
All features have passed with the following triplets:

- x86-windows
- x64-windows-static

Note: Feature `cuda` is blocked on x64-linux, since there is no `cuda `installed on my local machine.
Feature `openmp` is blocked on x64-linux due to no space left on device.

**Comment by cenit** [comment]
Works here for me

**Comment by NancyLi1013** [comment]
LGTM now. Thanks for your updates.

**Comment by ras0219-msft** [comment]
LGTM, thanks for the fix!

**Pull request merged**
