### PR TITLE
[cpr] Updated to 1.5.2

### PR DESCRIPTION
**Pull request by COM8**
**Describe the pull request**
Updates [`cpr`](https://github.com/whoshuu/cpr) to version [`1.5.2`](https://github.com/whoshuu/cpr/releases/tag/1.5.2).

### CODE REVIEW

**Comment by hung1024** [comment]
I remove cpr and install again using, 
vcpkg.exe install cpr
still see 1.5.1 version:
D:\cpr-master>D:\AVMAN2\vcpkg\vcpkg.exe list
cpr:x86-windows                                    1.5.1            C++ Requests is a simple wrapper around libcurl ...
curl:x64-windows                                   7.73.0           A library for transferring data with URLs
.................................
Any suggestion?

**Comment by BillyONeal** [comment]
@hung1024 We had not yet merged this PR so you wouldn't see an updated version.

@COM8 Thanks for your contribution!

**Comment by hung1024** [comment]
I check again after see this 
"BillyONeal merged commit 878d5a5 into microsoft:master 12 hours ago
12 checks passed"

Now it is still 1.5.1 , not 1.5.2
D:\cpr-master>D:\AVMAN2\vcpkg\vcpkg.exe search cpr
cpr                  1.5.1            C++ Requests is a simple wrapper around libcurl inspired by the excellent Pyth...

If your library is not listed, please open an issue at and/or consider making a pull request:
    https://github.com/Microsoft/vcpkg/issues

**Comment by BillyONeal** [comment]
@hung1024  Did you `git pull` to get this change?

**Comment by hung1024** [comment]
Which full command with git? I only know using vcpkg.exe to download and install package.
At this moment, it still says 1.5.1 version, (with critical error)

**Comment by BillyONeal** [comment]
@hung1024 `vcpkg` only reads port definitions from a directory named "ports" next to the executable. When you `git clone`'d it followed by `.\bootstrap-vcpkg.bat`, you build a vcpkg matching that exact commit, and there will never be any changes to the ports tree unless you run `git pull` in the same place you ran `git clone`.

**Pull request merged**
