### PR TITLE
[vcpkg-ci-llvm] Find cacheable feature sets

### PR DESCRIPTION
**Pull request by dg0yt**
All PRs which touch `scripts/ci.baseline.txt` are affected by the CI's inability to cache `llvm` artifacts, also blocking resources for other PRs. E.g. (before this PR):
~~~
Building llvm[bolt,clang,core,default-options,default-targets,disable-assertions,disable-clang-static-analyzer,enable-abi-breaking-checks,enable-bindings,enable-eh,enable-rtti,enable-terminfo,enable-threads,enable-zlib,enable-zstd,flang,libclc,lld,lldb,mlir,openmp,polly,target-aarch64,target-all,target-amdgpu,target-arm,target-avr,target-bpf,target-hexagon,target-lanai,target-mips,target-msp430,target-nvptx,target-powerpc,target-riscv,target-sparc,target-spirv,target-systemz,target-ve,target-webassembly,target-x86,target-xcore,tools,utils]:x64-osx...
...
Stored binaries in 0 destinations in 13 min.
Elapsed time to handle llvm:x64-osx: 3.8 h
~~~

This PR is an attempt to trim the llvm artifact size so that caching can work normally. With this PR:

~~~
Building llvm[clang,core,default-options,default-targets,disable-assertions,disable-clang-static-analyzer,enable-abi-breaking-checks,enable-bindings,enable-eh,enable-rtti,enable-terminfo,enable-threads,enable-zlib,enable-zstd,libclc,lld,lldb,target-spirv,target-x86,tools]:x64-osx...
...
Stored binaries in 1 destinations in 7.6 min.
Elapsed time to handle llvm:x64-osx: 1.8 h
~~~

x64-linux: Even the default features from `llvm` don't give a cacheable artifact, so I moved `flang` to it. (However, this adds significant build time.)
All other triplets are cached (or not tested), https://dev.azure.com/vcpkg/public/_build/results?buildId=91452&view=results.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by dg0yt** [comment]
x64-windows: "Stored binaries in 1 destinations in 15 min. Elapsed time to handle llvm:x64-windows: 60 min"  
Do I understand correctly that 25 percent of build time go into the upload (which is failing before this PR)? 
Ultra fast...  
And all this time it displays "-- Performing post-build validation".

**Comment by autoantwort** [comment]
> x64-windows: "Stored binaries in 1 destinations in 15 min. Elapsed time to handle llvm:x64-windows: 60 min"
> Do I understand correctly that 25 percent of build time go into the upload (which is failing before this PR)?
> Ultra fast...
> And all this time it displays "-- Performing post-build validation".

Yes ...

There is a reason why I have implemented https://github.com/microsoft/vcpkg-tool/pull/908

**Review by LilyWangLL — DISMISSED** [review]

**Comment by autoantwort** [comment]
Why have you closed it?

**Comment by dg0yt** [comment]
> Why have you closed it?

Oh, I didn't even notice... GH decided to close it after some misguided push.

**Pull request merged**
