### PR TITLE
[openssl] install cmake config wrapper only at the end

### LINKED ISSUE #37987: [libarchive] Build failure on x64-linux (static only)
### Operating system

Ubuntu 20.04

### Compiler

GCC

### Steps to reproduce the behavior

I have set up a test repo for reproducing this issue with GitHub actions: https://github.com/chrismile/ActionsTestRepo2

Compilation of libarchive only fails for the static build due to undefined references to, e.g., `dlopen'. This is a regression, as this issue did not appear in commit 2a6371b01420d8820d158b4707e79931feba27aa.

Disclaimer: Due to the ongoing issues with liblzma (https://github.com/microsoft/vcpkg/issues/37839), I needed to set a different mirror.

### Failure logs

[out.log](https://github.com/microsoft/vcpkg/files/14881417/out.log)

### Additional context

None.

### PR DESCRIPTION
**Pull request by cenit**
Fixes #37987

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [x] The "supports" clause reflects platforms that may be fixed by this new version.
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

i don't know why adding the config wrapper at the beginning results in a missing file in the end, but at least in this way it works.

Could it be that including a portfile in a portfile triggers any cleanup in the packages folder?

### CODE REVIEW

**Comment by WangWeiLin-MV** [comment]
Note: I will be converting your PR to draft status. Please click "Ready for review" after making the fix and modifications.

**Comment by Neumann-A** [comment]
@WangWeiLin-MV: converting this to draft makes no sense.

**Comment by cenit** [comment]
which reviews?

**Comment by cenit** [comment]
i don't think any regression is due to this pr
nor i have time to make those fixes!

**Comment by cenit** [comment]
@BillyONeal it's more than one month that many ports (anything that depends on openssl) cannot be built on linux on many machines (e.g. any github action runner)

this pr fixes the symptom (but does not understand the real problem)

what shall we do to better expedite the merge of a fix?

**Comment by dg0yt** [comment]
@cenit Please do a `git commit --allow-empty -m CI; git push` to trigger CI.

**Comment by cenit** [comment]
kddockwidgets regression described here https://github.com/microsoft/vcpkg/issues/38509 and independent from this PR

**Comment by cenit** [comment]
sorry can i ask what is blocking the merge of this PR? there are no regressions anymore after the last retrigger

**Review by WangWeiLin-MV — APPROVED** [review]
The port usage tests pass with the following triplets:
* x64-windows

**Review by data-queue — APPROVED** [review]

**Pull request merged**
