### PR TITLE
Fix Python3 tool on Windows

### LINKED ISSUE #6988: Ports fail on Windows since Python update
Since Python was updated from 3.5.4 to 3.7.3  (#6383) importing external modules does not work in scripts, e.g.:
```
-- Found PythonInterp: F:/vcpkg/downloads/tools/python/python3/python.exe (found version "3.7.3") 
-- Constructing LLVMBuild project information
CMake Error at CMakeLists.txt:683 (message):
  Unexpected failure executing llvm-build: Traceback (most recent call last):

    File "F:/vcpkg/buildtrees/llvm/src/llvm-7.0.0.src/utils/llvm-build/llvm-build", line 3, in <module>
      import llvmbuild

  ModuleNotFoundError: No module named 'llvmbuild'
```

This behavior is unique to the [Python embeddable package](https://docs.python.org/3/using/windows.html#windows-embeddable) and it seems to work that way since Python version 3.6.0.

The build works fine when

- Using the host's Python installation or
- Adding the module path to `vcpkg\downloads\tools\python\python3\python37._pth`

Packages that use Python 3 and might be affected: `botan, clblas, ctemplate, folly, gl3w, glad, gtk, hyperscan, hyperscan, llvm, open62541, opencl, physx, pybind11, qscintilla, qt5-base, shaderc, shogun, spirv-tools, xmsh`

Related issues: #6979, #6984, #7066

Machine setup: Windows 10 1903 x64, VS2019

### PR DESCRIPTION
**Pull request by cskrisz**
Remove the file `python37._pth` from the python3 tool folder to allow scripts to import any modules. 

Closes: #6988, #6979, #6984, #7066

### CODE REVIEW

**Comment by ZeroAurora** [comment]
If python is already installed by vcpkg before, after this PR is merged, should users remove `python37._pth` manually?

**Comment by cskrisz** [comment]
I didn't realize vcpkg is already trying to stay backward compatible with old installations. For example, some portable tools won't even get updated if they have already been installed.

**Comment by ZeroAurora** [comment]
So should a warning be set? Or a function to delete `python37._pth`?

**Comment by cskrisz** [comment]
No, the underlying problem regarding the update process of tools should be addressed. That's not necessarily complicated, every tool `${SUBDIR}` should contain a version number and for cases like this, we could append a revision number.

**Comment by cskrisz** [comment]
I made the changes for `python3` and added the version to `SUBDIR` as I see some other tools have already done this.

**Comment by vicroms** [comment]
@cskrisz 

Thanks for the PR! 

I tested all ports using PYTHON3 in PR #7133. 
Only `open62541` needed some fixes.

**Pull request merged**
