### PR TITLE
[libtorch] Fix core dependencies

### PR DESCRIPTION
**Pull request by patrikhuber**
`vcpkg install libtorch[core]` fails to configure/build on windows-x64 (potentially on other platforms too - I haven't tested) because it seems to depend on fp16, fxdiv and pthreadpool - see below errors.

This problem has probably not come up yet because `vcpkg install libtorch` works - it has xnnpack as default feature, and xnnpack depends on the above libraries - so for people that do `vcpkg install libtorch`, it will transitively fetch these needed libtorch dependencies. However, if you do `vcpkg install libtorch[core]`, the configure/build fails because these dependencies are missing.

```
CMake Error at cmake/vcpkg-dependencies.cmake:26 (find_path):
  Could not find FP16_INCLUDE_DIRS using the following files: fp16.h
  
CMake Error at cmake/vcpkg-dependencies.cmake:28 (find_path):
  Could not find FXDIV_INCLUDE_DIRS using the following files: fxdiv.h
  
CMake Error at C:/Users/PatrikHuber/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package):
  Could not find a package configuration file provided by
  "unofficial-pthreadpool" with any of the following names:

    unofficial-pthreadpoolConfig.cmake
    unofficial-pthreadpool-config.cmake

  Add the installation prefix of "unofficial-pthreadpool" to
  CMAKE_PREFIX_PATH or set "unofficial-pthreadpool_DIR" to a directory
  containing one of the above files.  If "unofficial-pthreadpool" provides a
  separate development package or SDK, be sure it has been installed.
```

CC @jimwang118 @luncliff

### CODE REVIEW

**Comment by patrikhuber** [comment]
@microsoft-github-policy-service agree company="Mimetrik"

**Comment by MonicaLiu0311** [comment]
But I haven't reproduced your problem locally.
```
PS G:\vcpkg> ./vcpkg install libtorch[core]
warning: In the September 2023 release, the default triplet for vcpkg libraries changed from x86-windows to the detected host triplet (x64-windows). For the old behavior, add --triplet x86-windows . To suppress this message, add --triplet x64-windows .
Computing installation plan...
The following packages will be built and installed:
    libtorch:x64-windows -> 1.12.1#3
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\monica\AppData\Local\vcpkg\archives in 750 us. Use --debug to see more details.
Installing 1/1 libtorch:x64-windows...
Building libtorch:x64-windows...
-- Using cached pytorch-pytorch-v1.12.1.tar.gz.
-- Cleaning sources at G:/vcpkg/buildtrees/libtorch/src/v1.12.1-e1cb316ec6.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source G:/vcpkg/downloads/pytorch-pytorch-v1.12.1.tar.gz
-- Applying patch pytorch-pr-85958.patch
-- Applying patch fix-cmake.patch
-- Applying patch fix-fbgemm-include.patch
-- Applying patch fix-c10-glog.patch
-- Applying patch use-flatbuffers2.patch
-- Applying patch fix-windows.patch
-- Applying patch fix_werror.patch
-- Using source at G:/vcpkg/buildtrees/libtorch/src/v1.12.1-e1cb316ec6.clean
-- Using flatc: G:/vcpkg/installed/x64-windows/tools/flatbuffers/flatc.exe
-- Using protoc: G:/vcpkg/installed/x64-windows/tools/protobuf/protoc.exe
-- Setting up python virtual environmnent...
-- Installing python packages: typing-extensions;pyyaml;numpy
-- Setting up python virtual environmnent...finished.
-- Using Python3: G:/vcpkg/buildtrees/libtorch/x64-windows-venv/Scripts/python.exe
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/c10/benchmark
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/c10/cuda/test/impl
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/c10/hip
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/c10/test/core/impl
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/contrib/aten/docs
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/contrib/docker-ubuntu-14.04
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/contrib/fakelowp/test
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/contrib/ideep
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/contrib/nnpack
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/contrib/opencl/OpenCL
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/contrib/playground/resnetdemo
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/contrib/pytorch
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/contrib/script/examples
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/contrib/tensorboard
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/core/nomnigraph/Representations
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/experiments/python
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/ideep/operators/quantization
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/mobile/contrib/libopencl-stub/src
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/mobile/contrib/libvulkan-stub/src
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/opt/nql/tests
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/python/benchmarks
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/python/docs
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/python/examples
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/python/fakelowp
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/python/helpers
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/python/ideep
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/python/layers
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/python/mint/static/css
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/python/mint/templates
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/python/mkl
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/python/modeling
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/python/models/seq2seq
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/python/onnx/bin
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/python/onnx/tests
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/python/operator_test
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/python/predictor
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/python/rnn
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/python/serialized_test/data/operator_test
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/python/test
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/python/trt/data
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/share/contrib/depthwise
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/share/contrib/nnpack
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/test/assets
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/utils/hip
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/torch/csrc/api/src/data/datasets
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/torch/csrc/api/src/data/samplers
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/torch/csrc/api/src/nn/modules/container
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/torch/csrc/api/src/nn/options
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/torch/csrc/api/src/optim/schedulers
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/torch/csrc/api/src/python
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/torch/csrc/api/src/serialize
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/torch/csrc/cuda/shared
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/torch/csrc/deploy/example/fx
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/torch/csrc/deploy/interpreter/third_party
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/torch/csrc/jit/backends/nnapi
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/torch/csrc/jit/codegen/cuda/docs/images
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/torch/csrc/jit/codegen/cuda/python_frontend/examples
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/torch/csrc/jit/codegen/cuda/runtime
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/torch/csrc/jit/codegen/cuda/tools
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/torch/csrc/jit/docs
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/torch/csrc/jit/tensorexpr/scripts
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/c10/cuda/test
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/c10/test/core
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/contrib/playground
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/contrib/script
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/python/mint/static
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/python/models
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/python/onnx
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/python/serialized_test/data
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/python/trt
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/test
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/torch/csrc/api/src/data
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/torch/csrc/api/src/nn/modules
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/torch/csrc/api/src/optim
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/torch/csrc/deploy/example
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/python/mint
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/caffe2/python/serialized_test
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/torch/csrc/api/src/nn
-- Removed G:/vcpkg/packages/libtorch_x64-windows/include/torch/csrc/api/src
-- Installing: G:/vcpkg/packages/libtorch_x64-windows/share/libtorch/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 4.7 min.
Elapsed time to handle libtorch:x64-windows: 2.5 h
Total install time: 2.5 h
```

**Comment by patrikhuber** [comment]
Hi @MonicaLiu0311, thanks for looking at it, and I'm glad that you were able to reproduce the issue in a clean environment.

If I understood you correctly, you are saying that according to upstream, fp16, fxdiv and pthreadpool are **not** dependencies of libtorch[core] (without xnnpack), is that right? So you think there is an error in upstream's build scripts, or in vcpkg's?

**Comment by MonicaLiu0311** [comment]
> Hi @MonicaLiu0311, thanks for looking at it, and I'm glad that you were able to reproduce the issue in a clean environment.
> 
> If I understood you correctly, you are saying that according to upstream, fp16, fxdiv and pthreadpool are **not** dependencies of libtorch[core] (without xnnpack), is that right? So you think there is an error in upstream's build scripts, or in vcpkg's?

Yes, I fixed the script in #35682 and the validation passes. Please also verify my changes, thank you.

**Comment by MonicaLiu0311** [comment]
`pthreadpool` and `fxdiv` cannot be used as `libtorch[core]` dependencies because we want to be consistent with upstream, so this PR will be closed and eventually fixed by #35682.

**Comment by patrikhuber** [comment]
@MonicaLiu0311 Sounds great, thank you for #35682.

**Pull request closed without merging**
