### PR TITLE
[libxslt] Remove unneeded helper

### PR DESCRIPTION
**Pull request by ras0219-msft**
Fixup of https://github.com/microsoft/vcpkg/pull/21441#pullrequestreview-806878550

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
Sorry I thought this is used in the pkgconfig part.

**Comment by Osyotr** [comment]
Could you also apply the following comment to this port? Thanks!
https://github.com/microsoft/vcpkg/pull/21451#discussion_r750176232

**Comment by ras0219-msft** [comment]
Done.

**Comment by ras0219-msft** [comment]
Thanks for the help!

**Pull request merged**
