### PR TITLE
[vcpkg-ci] Add AZP logging markup for versioning errors

### PR DESCRIPTION
**Pull request by dg0yt**
- #### What does your PR fix?  
  This PR fixes the poor visibility of version files errors in Github.
  In its initial form, it contains an experimental commit to test the expected behaviour. This commit will be reverted or removed when the main change is accepted.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  unrelated

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  unrelated

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  not needed

### CODE REVIEW

**Comment by dg0yt** [comment]
Works as expected. Ready for comments.

**Comment by ras0219-msft** [comment]
This is really great!

Do you think we could fuse the lines together so it would display in a single error?

It looks like perhaps replacing with the newline with `%0D%0A` might fuse it together [1].

[1] https://stackoverflow.com/questions/58502351/do-azure-dev-ops-pipelines-logging-commands-support-multiline-messages

**Comment by dg0yt** [comment]
> Do you think we could fuse the lines together so it would display in a single error?

I can try to do this. I just needed to know if there was interest for this PR.

**Comment by PhoebeHui** [comment]
I like this PR, it make the message more readable to users!

**Comment by dg0yt** [comment]
Looks good now. 
- Multiline messages.
- Absolute paths turned into relative paths.
- Version files annotated at line 2, for more context in the files view at GH.

**Comment by dg0yt** [comment]
Side note: Issues with the message from tool:
~~~
While validating port STRANGEFILE.
Missing Git SHA.
Run:

    git add ports/STRANGEFILE.
~~~
Trailing dot. ^^^ 
~~~
    git commit -m "[STRANGEFILE] Add new port"
    vcpkg x-add-version STRANGEFILE
~~~
No git commit instruction vcpkg x-add-version. ^^^ 
~~~
to commit the new port and create its version file.
~~~
And yes, this is a file, not a port directory ;-)

**Comment by dg0yt** [comment]
~~~
But local port with the same verion has a different SHA: d4b18a16a1f6f529571aa35a1d5d70748b1a1eea
~~~
"version" ^^^

**Comment by ras0219-msft** [comment]
I think https://github.com/microsoft/vcpkg-tool/pull/134 covers all the typos/message suggestions

**Review by ras0219-msft — COMMENTED** [review]
This LGTM once the "Do Not Merge" changes are reverted :)

**Comment by dg0yt** [comment]
"Do Not Merge" changes are reverted now.

**Review by ras0219-msft — APPROVED** [review]

**Review by PhoebeHui — APPROVED** [review]

**Pull request merged**
