### PR TITLE
[nasm] Update to 2.16.01.

### PR DESCRIPTION
**Pull request by Sibras**
Updates 'vcpkg_find_acquire_program' to use latest nasm release.

### CODE REVIEW

**Comment by cnSchwarzer** [comment]
Will this fix x64-windows MSVC link hang issue of ffmpeg?

**Comment by Sibras** [comment]
> Will this fix x64-windows MSVC link hang issue of ffmpeg? #28390

No, not by itself but I do have a working solution for ffmpeg using this and other changes.
I put it up separately to help get things merged faster

**Comment by Sibras** [comment]
> > Will this fix x64-windows MSVC link hang issue of ffmpeg? #28390
> 
> No, not by itself but I do have a working solution for ffmpeg using this and other changes. I put it up separately to help get things merged faster

Managed to fix the last remaining link issues with x86-windows and ffmpeg. It uses this PR and a new one for ffmpeg.
FFmpeg 5.1.2 [28955](https://github.com/microsoft/vcpkg/pull/28955)

**Comment by cnSchwarzer** [comment]
x86-windows？

**Comment by Sibras** [comment]
> x86-windows？
> 
> Oh you mean x86 yasm problem， 👍🏻

Yep, just it only really effects msvc hence breaking the x86-windows triplet

**Comment by Sibras** [comment]
OK the CI failure is for 'zeroc-ice:x64-windows-static-md' which doesnt seem related at all to this PR. As the error logs suggest the process was just terminated (as opposed to an actual error) which is potentially just the CI timing out after ~1000mins??

testing locally it works fine so seems to just be the CI

**Comment by vicroms** [comment]
Please merge with master to get rid of the CI failure.

**Comment by Sibras** [comment]
Now theres a x64-linux CI failure, but that appears to have been the result of an issue connecting to the website to download source and is unrelated to this PR (x64-linux CI passed when previously run)

**Comment by BillyONeal** [comment]
Thanks for the update!

**Pull request merged**
