### PR TITLE
Fixes pugixml debug library name

### PR DESCRIPTION
**Pull request by fundies**
Fixes pugixml debug library name

### CODE REVIEW

**Comment by Neumann-A** [comment]
https://vcpkg.readthedocs.io/en/latest/maintainers/maintainer-guide/
> Do not rename binaries outside the names given by upstream
> This means that if the upstream library has different names in release and debug (libx versus libxd), then the debug library should not be renamed to libx. Vice versa, if the upstream library has the same name in release and debug, we should not introduce a new name.

**Comment by fundies** [comment]
@Neumann-A They have an option for it in their CMakeLists. I'm not changing any names your generator is just called incorrectly

**Comment by Neumann-A** [comment]
>I can use that option instead if you prefer.

That would be ok. (since your debug suffix is also different from the internal one)

**Review by JackBoosY — CHANGES_REQUESTED** [review]
Please update version info. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).

**Review by JackBoosY — APPROVED** [review]

**Comment by strega-nil** [comment]
LGTM! Thanks @fundies !

**Pull request merged**
