### PR TITLE
[`wayland`,`wayland-protocols`] Add `force-build` feature 💪

### PR DESCRIPTION
**Pull request by vicroms**
This PR removes `wayland`'s dependencies on the empty-package path. 

In order to force the wayland libraries to be built the `force-build` feature must be enabled in addition to the `X_VCPKG_FORCE_VCPKG_WAYLAND_LIBRARIES` triplet variable.

### CODE REVIEW

**Comment by Neumann-A** [comment]
@vicroms was that the agreed solution in the team? I thought a `"system" : "<platformexpression>"` field would be added to the manifest with some triplet variables controlling weather or not to actually respect that field. (maybe just triplet variables would be enough but that conflicts defining a good default.). This approach here leads to a feature dependency cascade where each "system" port (however that should be defined) would require a feature and if it depends on other "system" stuff needs to pull in the `force-build` feature (e.g. `libx11` with `force-build` requires all its deps to also be `force-build`). 

I feel like this needs a more general solution that adding a feature.

**Comment by vicroms** [comment]
This is the agreed workaround available right now, I agree that the feature you describe would be a way better solution. 

I did come across the cascade effect while preparing the other system deps ports so I will take this back for another round of discussion.

**Comment by Cheney-W** [comment]
@vicroms Convert to draft?

**Comment by Osyotr** [comment]
Making it a feature makes more sense to me.
@Neumann-A would you mind telling more about how `"system" : "<platformexpression>"` stuff is supposed to work?

**Comment by Neumann-A** [comment]
> @Neumann-A would you mind telling more about how "system" : "<platformexpression>" stuff is supposed to work?

If `<platformexpression>` evaluates to true in the ports manifest it will be treated as a system dependency and the dependency graph will end there. No manifest declared dependencies will be added. There should be one (maybe two) triplet variables `VCPKG_FORCE_SYSTEM_PORT` (`VCPKG_FORCE_VCPKG_PORT` ?) which are able to override that setting via the triplet. 
If the the port is treated as a system port vcpkg will invoke the normal build procedure with a variable `-DVCPKG_IS_SYSTEM_PORT=TRUE` so that `ports.cmake` can either load an empty dummy as the portfile or a `portfile.system.cmake`. The later allows checking if the system dependency is actually installed. (at least that would be my idea how it could work.)

**Comment by Neumann-A** [comment]
From what I see: [PackageGraph::install](https://github.com/microsoft/vcpkg-tool/blob/e73fa97801963e2e1aba31c79c18ef3d42468fa8/src/vcpkg/dependencies.cpp#L748)
will need a rewrite. Either one decides to do an unquallified cmake lookup with all deps independent of supports expressions first and rebuild the dep tree after that correctly (1 big cmake call) or one decides to do a quallified lookup for every port in the chain (One CMake call for every dep level). The current design is somewhat in between but considering that `"supports:"` is basically everywhere i probably would do the former for performance reason even if that means performance of small ports without a lot of deps and without supports regresses a bit. I would also say that making 1 big cmake call would extremly simplify the code since a lot of the guarding code if the var provider is already ready/did already run could be removed.

**Pull request merged**
