### PR TITLE
Adapting for HPX V1.5.1

### PR DESCRIPTION
**Pull request by hkaiser**
This PR adapts the configuration files to the latest version of HPX.

### CODE REVIEW

**Comment by BillyONeal** [comment]
@hkaiser Can you please merge with master?

**Comment by BillyONeal** [comment]
Despite GitHub checks and the pipelines bot comment, a successful build is here: https://dev.azure.com/vcpkg/public/_build/results?buildId=43686&view=results

Thanks for your contribution!

**Comment by hkaiser** [comment]
@BillyONeal thanks for your support!

**Pull request merged**
