### PR TITLE
[flashlight-cuda] New Port

### PR DESCRIPTION
**Pull request by jacobkahn**
Adds a new port for [flashlight](https://github.com/facebookresearch/flashlight), an ML library written in C++. I'm one of the project authors.

A few things to note:
- This port only contains support for the CUDA backend in flashlight. OpenCL/CPU backend support will be added in a separate port later when they are complete.
- The library depends on NCCL for which there doesn't currently exist a port ([I've just created a PR, ideally, we *commit that port first*](https://github.com/microsoft/vcpkg/pull/14683)) - it uses `find_package` natively with a `FindNCCL.cmake` module. `NCCL` and `cuDNN` are very similar in their installations next to CUDA, so the NCCL port works exactly like [the vcpkg cuDNN port](https://github.com/microsoft/vcpkg/tree/master/ports/cudnn).
  - CI will probably fail until the NCCL port is committed
- The features in the port depend on other features of the port:
```
lib
 ^
 |
 fl <— imgclass
 ^
 |
asr
```

- Which triplets are supported/not supported? Have you updated the CI baseline?

Supports `linux` for now. I've tested `x64-linux`. The port has `!(windows|osx)`, but I will test the port on macOS shortly. I don't expect Windows integration to be complete for some time, but I will update the port if/when it is.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

Yes.

cc @tlikhomanenko @vineelpratap @xuqiantong @avidov @andresy @syhw @padentomasello

### CODE REVIEW

**Review by JackBoosY — CHANGES_REQUESTED** [review]
Can you revert changes about nccl and depends on #14683?

**Comment by jacobkahn** [comment]
@JackBoosY done — I'll rebase on top of the NCCL port once it's done though.

**Comment by jacobkahn** [comment]
@JackBoosY how can I get detailed logs of this failure in CI?

**Comment by JackBoosY** [comment]
https://dev.azure.com/vcpkg/public/_build/results?buildId=45830&view=artifacts&pathAsName=false&type=publishedArtifacts
Do you have permission?

**Comment by jacobkahn** [comment]
@JackBoosY I have permission. How do I get to this page for future CI runs?

**Comment by JackBoosY** [comment]
@jacobkahn 
`Details`-> `View more details on Azure Pipelines` -> `* artifacts produced`

@strega-nil Maybe we need to write documentation to the contributors.

**Comment by jacobkahn** [comment]
@JackBoosY is there some way I can know what command CI ran when this error happened? I'm unable to reproduce it.

**Comment by JackBoosY** [comment]
@jacobkahn Maybe the environment of our CI machine is different from yours. You can only use the log content to solve the regression.

**Comment by jacobkahn** [comment]
@JackBoosY fixed the issue. Needed a default feature.

**Comment by strega-nil** [comment]
Thanks @jacobkahn

**Pull request merged**
