### PR TITLE
[minizip,xlsxio,fmilib,collada-dom] Minizip fixes, xlsxio update

### LINKED ISSUE #30886: [fmilib] the current port builds but is unusable
### Is your feature request related to a problem? Please describe.

The current port for fmilib replaces the vendored version of minizip that comes with [fmi-library](https://github.com/modelon-community/fmi-library/tree/master) with the vcpkg version of minizip. While this all builds fine, the resulting library is actually unusable (at least I don't see how).

The thing is that fmi-library slightly modified minizip (cf. [README.txt here](https://github.com/modelon-community/fmi-library/blob/master/ThirdParty/Minizip/minizip/README.txt)). Among these modifications, they renamed the main function of miniunz to just that -- `miniunz(...)`. Since that functions doesn't exist in the usual minizip library, you get linking errors saying that function `miniunz` is not defined.

### Proposed solution

Don't use minizip as a dependency [in vcpkg.json](https://github.com/microsoft/vcpkg/blob/master/ports/fmilib/vcpkg.json#L11), and do use the vendored version of minizip [this patch](https://github.com/microsoft/vcpkg/blob/master/ports/fmilib/devendor-sublibs.diff#L37).

I gave that a try, and the resulting library is usable then.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dg0yt**
# minizip

- Adds include dir property to exported config.
- Moves exported config to `unofficial` namespace (but adds polyfill for users of the old config).
- Install official pkg-config files.
- Cleanup scripts
- Add feature "tools"

# xlsxio

- Update to official 0.2.34
- Refresh minizip and expat patching

# fmilib

- Fix minizip devendoring/patching - fixes https://github.com/microsoft/vcpkg/issues/30886.

# collada-dom

- Refresh minizip patching

# ...

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by MonicaLiu0311** [comment]
# minizip
Feature `tools` is tested successfully in the following triplet:
```
x86-windows
x64-windows
x64-windows-static
```

The usage test passed (header files found):
```
minizip provides CMake targets:

    find_package(unofficial-minizip CONFIG REQUIRED)
    target_link_libraries(main PRIVATE unofficial::minizip::minizip)
```

# fmilib 
The usage test passed (header files found):
```
fmilib provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(unofficial-fmilib CONFIG REQUIRED)
    target_link_libraries(main PRIVATE unofficial::fmilib::fmilib)
```

# xlsxio
usage:
```
xlsxio provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(xlsxio CONFIG REQUIRED)
    target_link_libraries(main PRIVATE xlsxio::xlsxio_read_SHARED xlsxio::xlsxio_write_SHARED)
```

🔴 When testing usage, the following error occurs:
```
  CMake Error at E:/minzip/scripts/buildsystems/vcpkg.cmake:852 (_find_package):
  Found package configuration file:

    E:/minzip/installed/x64-windows/share/xlsxio/xlsxio-config.cmake

  but it set xlsxio_FOUND to FALSE so package "xlsxio" is considered to be
  NOT FOUND.  Reason given by package:

  xlsxio could not be found because dependency expat could not be found.		E:/minzip/scripts/buildsystems/vcpkg.cmake	852	
```

<details>
<summary><b>CMakeFindUsage.cpp</b></summary>
<pre>
#include &#60;iostream&#62;
#include "xlsxio_version.h"

using namespace std;

int main()
{
        cout << "Hello CMake." << endl;
        return 0;
}
</pre></details>


<details>
<summary><b>CMakeLists.txt</b></summary>
<pre>
cmake_minimum_required (VERSION 3.8)

set(CMAKE_TOOLCHAIN_FILE "E:/minzip/scripts/buildsystems/vcpkg.cmake")

project ("CMakeFindUsage")

add_executable (main "CMakeFindUsage.cpp")

find_package(xlsxio CONFIG REQUIRED)

target_link_libraries(main PRIVATE xlsxio::xlsxio_read_SHARED xlsxio::xlsxio_write_SHARED)
</pre></details>

**Comment by dg0yt** [comment]
> xlsxio could not be found because dependency expat could not be found.

Hm, probably vcpkg cmake wrapper breaking valid cmake due to unexpected case insensitivity 😠

**Comment by dg0yt** [comment]
@MonicaLiu0311 Please retest xlsxio.

**Comment by MonicaLiu0311** [comment]
> @MonicaLiu0311 Please retest xlsxio.

# xlsxio
The usage test passed (header files found):
```
xlsxio provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(xlsxio CONFIG REQUIRED)
    target_link_libraries(main PRIVATE xlsxio::xlsxio_read_SHARED xlsxio::xlsxio_write_SHARED)
```

**Review by MonicaLiu0311 — APPROVED** [review]

**Review by MonicaLiu0311 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thank you!

**Pull request merged**
