### PR TITLE
Use GNU Make to build autotools ports on FreeBSD

### LINKED ISSUE #32282: Use GNU Make to build autotools ports on FreeBSD
**Describe the bug**
For autotools ports, vcpkg runs [vcpkg_configure_make](../blob/master/scripts/cmake/vcpkg_configure_make.cmake) to generate a GNU Makefile project and then uses [vcpkg_build_make](../blob/master/scripts/cmake/vcpkg_build_make.cmake) in order to compile these Makefiles, using the `make` program, which, on linux systems, is a hardlink on the `gmake` program.

The BSD operating systems, however, ship with BSD make is the default make, and GNU make, if desired, has to be installed as a third-party application. Even if it is installed, using pkgsrc, ports, pkgng or other sources, GNU make will be `gmake`, while `make` remains BSD make (cmake, among others, uses BSD Makefiles on BSD systems, so flipping the hardlink or pushing a new make into $PATH is not a feasible soluting).

`vcpkg_configure_make` contains a branch for OpenBSD hosts to use `gmake` instead of `make` (which is `bmake` on both OpenBSD and FreeBSD), so the most straightforward approach to solve this issue would be to do the same on FreeBSD systems

**Environment**
- OS: FreeBSD 13.2-RELEASE releng/13.2-n254617-525ecfdad597 GENERIC amd64
- Compiler: FreeBSD clang version 14.0.5 (https://github.com/llvm/llvm-project.git llvmorg-14.0.5-0-gc12386ae247c)

**To Reproduce**
1. ./vcpkg install icu
2. vcpkg invokes BSD make which will fail to interpret the GNU make script

        Installing 1/1 icu:x64-freebsd...
        Building icu[core,tools]:x64-freebsd...
        warning: -- Using community triplet x64-freebsd. This triplet configuration is not guaranteed to succeed.
        -- [COMMUNITY] Loading triplet configuration from: /tmp/vcpkg/triplets/community/x64-freebsd.cmake
        [DEBUG] 1005: popen(GIT_CEILING_DIRECTORIES=/tmp/vcpkg/buildtrees  /usr/local/bin/cmake "-DALL_FEATURES=tools;" -DCURRENT_PORT_DIR=/tmp/vcpkg/ports/icu -D_HOST_TRIPLET=x64-freebsd "-DFEATURES=core;tools" -DPORT=icu -DVERSION=73.1 -DVCPKG_USE_HEAD_VERSION=0 -D_VCPKG_DOWNLOAD_TOOL=BUILT_IN -D_VCPKG_EDITABLE=0 -D_VCPKG_NO_DOWNLOADS=0 -DZ_VCPKG_CHAINLOAD_TOOLCHAIN_FILE=/tmp/vcpkg/scripts/toolchains/freebsd.cmake -DCMD=BUILD -DDOWNLOADS=/tmp/vcpkg/downloads -DTARGET_TRIPLET=x64-freebsd -DTARGET_TRIPLET_FILE=/tmp/vcpkg/triplets/community/x64-freebsd.cmake -DVCPKG_BASE_VERSION=2999-12-31 -DVCPKG_CONCURRENCY=33 -DVCPKG_PLATFORM_TOOLSET=external -DGIT=/usr/local/bin/git -DVCPKG_ROOT_DIR=/tmp/vcpkg -DPACKAGES_DIR=/tmp/vcpkg/packages -DBUILDTREES_DIR=/tmp/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=/tmp/vcpkg/installed -DDOWNLOADS=/tmp/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P /tmp/vcpkg/scripts/ports.cmake 2>&1)
        -- Using cached icu4c-73_1-src.tgz.
        -- Cleaning sources at /tmp/vcpkg/buildtrees/icu/src/c-73_1-src-3575e21c7c.clean. Use --editable to skip cleaning for the packages you specify.
        -- Extracting source /tmp/vcpkg/downloads/icu4c-73_1-src.tgz
        -- Applying patch disable-escapestr-tool.patch
        -- Applying patch remove-MD-from-configure.patch
        -- Applying patch fix_parallel_build_on_windows.patch
        -- Applying patch fix-extra.patch
        -- Applying patch mingw-dll-install.patch
        -- Applying patch disable-static-prefix.patch
        -- Applying patch fix-win-build.patch
        -- Using source at /tmp/vcpkg/buildtrees/icu/src/c-73_1-src-3575e21c7c.clean
        -- Found external ninja('1.11.1').
        -- Getting CMake variables for x64-freebsd-dbg
        -- Getting CMake variables for x64-freebsd-rel
        -- Generating configure for x64-freebsd
        -- Finished generating configure for x64-freebsd
        -- Configuring x64-freebsd-dbg
        -- Configuring x64-freebsd-rel
        -- Building x64-freebsd-dbg
        CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
            Command failed: /usr/bin/make V=1 -j 33 -f Makefile all
            Working Directory: /tmp/vcpkg/buildtrees/icu/x64-freebsd-dbg/
            See logs for more information:
            /tmp/vcpkg/buildtrees/icu/build-x64-freebsd-dbg-out.log
            /tmp/vcpkg/buildtrees/icu/build-x64-freebsd-dbg-err.log

        Call Stack (most recent call first):
        scripts/cmake/vcpkg_build_make.cmake:151 (vcpkg_execute_build_process)
        scripts/cmake/vcpkg_install_make.cmake:2 (vcpkg_build_make)
        ports/icu/portfile.cmake:144 (vcpkg_install_make)
        scripts/ports.cmake:147 (include)
**Expected behavior**
As GNU autotools always generate GNU Makefiles, vcpkg should invoke the GNU Makefile interpreter, rather then the operating system's default Makefile interpreter.

**Failure logs**
[build-x64-freebsd-dbg-err.log](https://github.com/microsoft/vcpkg/files/11898680/build-x64-freebsd-dbg-err.log)
[build-x64-freebsd-dbg-out.log](https://github.com/microsoft/vcpkg/files/11898681/build-x64-freebsd-dbg-out.log)

**Additional context**
I tried to build the other autotools packages with gmake locally, and ended up being able to install

- [x] botan (needed additional patching to build)
- [ ] healpix (everything other then linux is blacklisted)
- [x] hunspell
- [x] icu
- [x] libudns
- [x] openldap
- [ ] pfring (same error as #22601)
- [x] tracy

on FreeBSD.

### PR DESCRIPTION
**Pull request by SchaichAlonso**
For autotools ports, vcpkg runs vcpkg_configure_make to generate a GNU Makefile project and then uses vcpkg_build_make in order to compile these Makefiles, using the make program, which, on linux systems, is a hardlink on the gmake program.

The BSD operating systems, however, ship with BSD make is the default make, and GNU make, if desired, has to be installed as a third-party application. Even if it is installed, however, GNU make will be `gmake`, while `make` remains BSD make (cmake, among others, uses BSD Makefiles on BSD systems, so flipping the hardlink or pushing a new make into $PATH is not a feasible solution).

vcpkg_configure_make contains a branch for OpenBSD hosts to use gmake instead of make (which is bmake on both OpenBSD and FreeBSD), so the most straightforward approach to solve this issue would be to do the same on FreeBSD systems

Fixes #32282

### CODE REVIEW

**Comment by dg0yt** [comment]
I tried to collect all required `vcpkg_configure_make` fixes in #31228, and I would add this one, too, unless that PR needs to be refactored.

**Comment by SchaichAlonso** [comment]
go ahead

**Comment by dg0yt** [comment]
Cherry-picked into #31228. Fixed trailing whitespace.
Disclaimer: It is unclear if my PR will be merged soon.

**Review by LilyWangLL — CHANGES_REQUESTED** [review]

**Comment by LilyWangLL** [comment]
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

**Review by LilyWangLL — APPROVED** [review]

**Comment by vicroms** [comment]
Converted to draft as these changes have been rolled into #31228.

We have created an internal task to track #31228, we are deciding on what is the best approach to merge these changes.

**Comment by SchaichAlonso** [comment]
Merged into #31228 which was merged into master

**Pull request closed without merging**
