### PR TITLE
[libmesh] fix post build checks

### PR DESCRIPTION
**Pull request by autoantwort**
Currently failed with:
```
warning: pkgconfig directories should be one of share/pkgconfig (for header only libraries only), lib/pkgconfig, or lib/debug/pkgconfig. The following misplaced pkgconfig files were found:
    /home/leander/vcpkg/packages/libmesh_x64-linux/etc/libmesh/libmesh-opt.pc
    /home/leander/vcpkg/packages/libmesh_x64-linux/etc/libmesh/libmesh.pc
    /home/leander/vcpkg/packages/libmesh_x64-linux/etc/libmesh/libmesh-prof.pc
    /home/leander/vcpkg/packages/libmesh_x64-linux/etc/libmesh/libmesh-dbg.pc
    /home/leander/vcpkg/packages/libmesh_x64-linux/etc/libmesh/libmesh-oprof.pc
    /home/leander/vcpkg/packages/libmesh_x64-linux/etc/libmesh/libmesh-devel.pc
You can move the pkgconfig files with commands similar to:
    file(MAKE_DIRECTORY "${CURRENT_PACKAGES_DIR}/lib/pkgconfig")
    file(RENAME "${CURRENT_PACKAGES_DIR}/etc/libmesh/libmesh-opt.pc" "${CURRENT_PACKAGES_DIR}/lib/pkgconfig/libmesh-opt.pc")
    file(RENAME "${CURRENT_PACKAGES_DIR}/etc/libmesh/libmesh.pc" "${CURRENT_PACKAGES_DIR}/lib/pkgconfig/libmesh.pc")
    file(RENAME "${CURRENT_PACKAGES_DIR}/etc/libmesh/libmesh-prof.pc" "${CURRENT_PACKAGES_DIR}/lib/pkgconfig/libmesh-prof.pc")
    file(RENAME "${CURRENT_PACKAGES_DIR}/etc/libmesh/libmesh-dbg.pc" "${CURRENT_PACKAGES_DIR}/lib/pkgconfig/libmesh-dbg.pc")
    file(RENAME "${CURRENT_PACKAGES_DIR}/etc/libmesh/libmesh-oprof.pc" "${CURRENT_PACKAGES_DIR}/lib/pkgconfig/libmesh-oprof.pc")
    file(RENAME "${CURRENT_PACKAGES_DIR}/etc/libmesh/libmesh-devel.pc" "${CURRENT_PACKAGES_DIR}/lib/pkgconfig/libmesh-devel.pc")
    vcpkg_fixup_pkgconfig()
    file(REMOVE_RECURSE empty directories left by the above renames)
warning: There should be no absolute paths, such as the following, in an installed package:
    /home/leander/vcpkg/packages/libmesh_x64-linux
    /home/leander/vcpkg/vcpkg_installed
    /home/leander/vcpkg/buildtrees/libmesh
    /home/leander/vcpkg/downloads
Absolute paths were found in the following files:
    /home/leander/vcpkg/packages/libmesh_x64-linux/tools/libmesh/bin/nc-config
    /home/leander/vcpkg/packages/libmesh_x64-linux/include/libmesh/libmesh_config.h
```

### CODE REVIEW

**Review by JonLiu1993 — DISMISSED** [review]

**Comment by BillyONeal** [comment]
Can you explain why you're disabling Windows and MacOS with this port?

See also:

```
# libmesh installs tons of problematic files that conflict with other ports (boost, eigen, etc)
libmesh:arm-neon-android=skip
libmesh:arm64-android=skip
libmesh:arm64-windows=skip
libmesh:arm-uwp=skip
libmesh:x64-android=skip
libmesh:x64-uwp=skip
libmesh:x64-windows=skip
libmesh:x64-windows-static=skip
libmesh:x64-windows-static-md=skip
libmesh:x86-windows=skip
libmesh:x64-osx=skip
libmesh:arm64-osx=skip
libmesh:x64-linux=skip
```

**Review by BillyONeal — APPROVED** [review]

**Comment by BillyONeal** [comment]
> Because the port does not build on these platforms

Ah right, and it's not a regression because it was =skip before, OK

**Comment by BillyONeal** [comment]
Baseline issue fix: https://github.com/microsoft/vcpkg/pull/33625

**Comment by BillyONeal** [comment]
Thanks!

**Pull request merged**
