### PR TITLE
[globjects] Fix incorrect filepath in globjects

### PR DESCRIPTION
**Pull request by acdemiralp**
**Describe the pull request**

- What does your PR fix? The globjects port can not work without this fix.

- Which triplets are supported/not supported? Have you updated the CI baseline? All are effected.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)? I believe so.

### CODE REVIEW

**Review by PhoebeHui — CHANGES_REQUESTED** [review]
@acdemiralp, thanks for the PR!

Could you also update the version to '1.1.0-3' in CONTROL file?

**Comment by acdemiralp** [comment]
Done.

**Review by PhoebeHui — APPROVED** [review]
Thanks for your update!

**Comment by strega-nil** [comment]
Alright, thanks @acdemiralp :)

**Pull request merged**
