### PR TITLE
[wxwidgets] Remove debug asserts from Release build.

### PR DESCRIPTION
**Pull request by AenBleidd**
Currently when building wxWidgets in Release mode, the debug asserts are enabled.
This fixes this issue by providing a necessary define to disable them.

Ref: https://docs.wxwidgets.org/3.1.6/group__group__funcmacro__debug.html

Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

### CODE REVIEW

**Comment by AenBleidd** [comment]
Patch to wxCharts also pushed to mainstream: https://github.com/wxIshiko/wxCharts/pull/201

**Review by LilyWangLL — APPROVED** [review]

**Comment by AenBleidd** [comment]
https://github.com/wxIshiko/wxCharts/pull/201 PR is merged on upstream. Looks like there is no 'releases' on that repo and current vcpkg port also refers to just some particular commit.
Should I create a new port release of wxCharts and then fix current PR by removing the patch or we're good to go?

**Comment by vicroms** [comment]
> [wxIshiko/wxCharts#201](https://github.com/wxIshiko/wxCharts/pull/201) PR is merged on upstream. Looks like there is no 'releases' on that repo and current vcpkg port also refers to just some particular commit. Should I create a new port release of wxCharts and then fix current PR by removing the patch or we're good to go?

Yes, that would be great :)

**Comment by AenBleidd** [comment]
@vicroms, done. Please review

**Pull request merged**
