### PR TITLE
[speexdsp] Add port for speexdsp 1.2rc3

### PR DESCRIPTION
**Pull request by IntelOrca**
**speexdsp** does not have a cmake configuration, so I have provided one.

**Source:** https://www.speex.org/downloads/

### CODE REVIEW

**Comment by atkawa7** [comment]
@IntelOrca Just wondering. What's the difference between this new port and speex port currently in vcpkg

**Comment by IntelOrca** [comment]
@atkawa7 `speex` is an encoder / decoder. `speexdsp` is separate library for digital sound processing such as resampling.

Originally the DSP part was in speex but was eventually separated.

**Comment by atkawa7** [comment]
@IntelOrca I see

**Comment by alexkaratarakis** [comment]
LGTM, thanks!

**Pull request merged**
