### PR TITLE
[libxml2] Embed resources in Windows-based shared library (#9474)

### PR DESCRIPTION
**Pull request by trueqbit**
- Fixes issue #9474
- Supports triplets x86-windows+x64-windows
- PR follows the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md).

Supersedes #9476 because of having renamed the branch.

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by vicroms** [comment]
Thanks for the PR!

**Pull request merged**
