### PR TITLE
[intel-ipsec] Update to 1.5 & use upstream CMake build system

### PR DESCRIPTION
**Pull request by Thomas1664**
Don't install dll to `System32`
Reduce build time from 21 min to 1.4 min (on x64-windows-static)

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by MonicaLiu0311** [comment]
usage:
```
The package intel-ipsec is compatible with built-in CMake targets:

    FIND_PACKAGE(intel-ipsec CONFIG REQUIRED)
    TARGET_LINK_LIBRARIES(main PRIVATE IPSEC::ipsec)
```

When testing usage, the following error occurs:
```
1> [CMake] -- Detecting CXX compiler ABI info
1> [CMake] -- Detecting CXX compiler ABI info - done
1> [CMake] -- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe - skipped
1> [CMake] -- Detecting CXX compile features
1> [CMake] -- Detecting CXX compile features - done
1> [CMake] CMake Error at G:/intel-ipsec/scripts/buildsystems/vcpkg.cmake:639 (_add_library):
1> [CMake]   _add_library called with IMPORTED argument but no library type.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   G:/intel-ipsec/installed/x64-windows/share/intel-ipsec/intel-ipsecConfig.cmake:8 (add_library)
1> [CMake]   G:/intel-ipsec/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
1> [CMake]   CMakeUsage/CMakeLists.txt:15 (FIND_PACKAGE)
1> [CMake] CMake Error at G:/intel-ipsec/installed/x64-windows/share/intel-ipsec/intel-ipsecConfig.cmake:9 (set_target_properties):
1> [CMake]   set_target_properties Can not find target to add properties to:
1> [CMake]   IPSEC::ipsec
1> [CMake] Call Stack (most recent call first):
1> [CMake]   G:/intel-ipsec/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
1> [CMake]   CMakeUsage/CMakeLists.txt:15 (FIND_PACKAGE)
1> [CMake] CMake Error at G:/intel-ipsec/installed/x64-windows/share/intel-ipsec/intel-ipsec-targets-debug.cmake:1 (set_property):
1> [CMake]   set_property could not find TARGET IPSEC::ipsec.  Perhaps it has not yet
1> [CMake]   been created.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   G:/intel-ipsec/installed/x64-windows/share/intel-ipsec/intel-ipsecConfig.cmake:15 (include)
1> [CMake]   G:/intel-ipsec/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
1> [CMake]   CMakeUsage/CMakeLists.txt:15 (FIND_PACKAGE)
1> [CMake] CMake Error at G:/intel-ipsec/installed/x64-windows/share/intel-ipsec/intel-ipsec-targets-debug.cmake:2 (set_target_properties):
1> [CMake]   set_target_properties Can not find target to add properties to:
1> [CMake]   IPSEC::ipsec
1> [CMake] Call Stack (most recent call first):
1> [CMake]   G:/intel-ipsec/installed/x64-windows/share/intel-ipsec/intel-ipsecConfig.cmake:15 (include)
1> [CMake]   G:/intel-ipsec/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
1> [CMake]   CMakeUsage/CMakeLists.txt:15 (FIND_PACKAGE)
1> [CMake] CMake Error at G:/intel-ipsec/installed/x64-windows/share/intel-ipsec/intel-ipsec-targets-release.cmake:1 (set_property):
1> [CMake]   set_property could not find TARGET IPSEC::ipsec.  Perhaps it has not yet
1> [CMake]   been created.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   G:/intel-ipsec/installed/x64-windows/share/intel-ipsec/intel-ipsecConfig.cmake:15 (include)
1> [CMake]   G:/intel-ipsec/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
1> [CMake]   CMakeUsage/CMakeLists.txt:15 (FIND_PACKAGE)
1> [CMake] CMake Error at G:/intel-ipsec/installed/x64-windows/share/intel-ipsec/intel-ipsec-targets-release.cmake:2 (set_target_properties):
1> [CMake]   set_target_properties Can not find target to add properties to:
1> [CMake]   IPSEC::ipsec
1> [CMake] Call Stack (most recent call first):
1> [CMake]   G:/intel-ipsec/installed/x64-windows/share/intel-ipsec/intel-ipsecConfig.cmake:15 (include)
1> [CMake]   G:/intel-ipsec/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
1> [CMake]   CMakeUsage/CMakeLists.txt:15 (FIND_PACKAGE)
1> [CMake] -- Configuring incomplete, errors occurred!
1> 'C:\Windows\system32\cmd.exe' '/c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Visual Studio 17 2022" -A x64  -DCMAKE_CONFIGURATION_TYPES:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\monica\source\repos\CMakeUsage\out\install\x64-Debug"  -DCMAKE_TOOLCHAIN_FILE=G:/intel-ipsec/scripts/buildsystems/vcpkg.cmake "C:\Users\monica\source\repos\CMakeUsage" 2>&1"' execution failed with error: ''C:\Windows\system32\cmd.exe' '/c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Visual Studio 17 2022" -A x64  -DCMAKE_CONFIGURATION_TYPES:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\monica\source\repos\CMakeUsage\out\install\x64-Debug"  -DCMAKE_TOOLCHAIN_FILE=G:/intel-ipsec/scripts/buildsystems/vcpkg.cmake "C:\Users\monica\source\repos\CMakeUsage" 2>&1"' returned with exit code: 1'.

```

<details>
<summary><b>test.cpp</b></summary>
<pre>
#include &#60;iostream&#62;
#include "intel-ipsec-mb.h"

using namespace std;

int main()
{
        cout << "Hello CMake." << endl;
        return 0;
}
</pre></details>


<details>
<summary><b>CMakeLists.txt</b></summary>
<pre>
cmake_minimum_required (VERSION 3.8)

set(CMAKE_TOOLCHAIN_FILE "G:/intel-ipsec/scripts/buildsystems/vcpkg.cmake")

project ("test")

add_library (main "test.cpp")

FIND_PACKAGE(intel-ipsec CONFIG REQUIRED)
TARGET_LINK_LIBRARIES(main PRIVATE IPSEC::ipsec)
</pre></details>

**Comment by MonicaLiu0311** [comment]
Ping @Thomas1664

**Comment by Thomas1664** [comment]
> Ping @Thomas1664

I think we better wait for upstream to export cmake targets

**Comment by MonicaLiu0311** [comment]
Closing this PR as no progress seems to be being made. If the upstream has been exported, please ping us to reopen it.

**Pull request closed without merging**
