### PR TITLE
[breakpad] Add linux tools

### PR DESCRIPTION
**Pull request by fran6co**
Add some of the core tools so the dumps can be actually read

### CODE REVIEW

**Comment by Cheney-W** [comment]
Please make the `tools` as a feature and create an option to control whether it is enabled.

**Comment by fran6co** [comment]
@Cheney-W done

**Comment by Cheney-W** [comment]
Pinging @fran6co  Could you please address the review suggestions? Thanks!

**Comment by fran6co** [comment]
What is left to do Cheney-W? I added the tools feature flag and added the license field as well

**Comment by Cheney-W** [comment]
Two things:
1. Remove the unnecessary blank lines: line 29 or line 30.
2. Add "supports": "linux" to the feature: tools in vcpkg.json. (If this feature only used in linux, please add support field for it.)

**Comment by fran6co** [comment]
@Cheney-W done

**Review by Cheney-W — DISMISSED** [review]

**Review by BillyONeal — APPROVED** [review]

**Pull request merged**
