### PR TITLE
[boost-modular-build-helper] Fix issue that link incorrect dependent libraries

### PR DESCRIPTION
**Pull request by PhoebeHui**
Related issue https://github.com/microsoft/vcpkg/issues/7559 and https://github.com/microsoft/vcpkg/issues/8613

In current Jamroot.jam, it configured both release and debug libraries, but doesn’t distinguish them, when build release libraries, it try to find dependency port debug libraries, that cause build failures.

To fix this issue, configured the Jamroot.jam before build release libraries, and configured it with debug build info again when build debug libraries.

boost-modular-build-helper has no features that need to test locally.

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by yurybura** [comment]
Related to #9780

**Comment by JackBoosY** [comment]
Please resolve conflicts.

Thanks.

**Comment by jgiannuzzi** [comment]
Hi there, I rebased @PhoebeHui's branch on the latest master and tested successfully on Linux and macOS: https://github.com/jgiannuzzi/vcpkg/tree/boost-modular-build-helper.

@PhoebeHui could you please update this PR? Otherwise I can create a separate PR, whichever is easier for you!

**Comment by JackBoosY** [comment]
@jgiannuzzi Feel free to open a new PR, thanks.

**Comment by PhoebeHui** [comment]
@ras0219-msft, could you help review this PR?

**Review by ras0219 — APPROVED** [review]

**Pull request merged**
