### PR TITLE
[opencv3] Upgrade to version 3.4.8

### PR DESCRIPTION
**Pull request by LilyWangL**
Upgrade opencv3 to version 3.4.8 and fix old patches.
Related opencv4 PR: #8557

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by cdcseacave** [comment]
pls can anybody explain why this is not merged yet?

**Comment by JackBoosY** [comment]
@vicroms Ready to merge now.

**Comment by cenit** [comment]
I lost track of this PR
May  I say one thing: why?
This PR was not ready and is bugged:

opencv3[contrib] is broken, downloading is not disabled anymore, ocv_update is used in a patch and not through commands passed by the portfile... also I suspect that the dlls/lib are treated in the new way and so some new parameters should be passed to the configure step, something similar to what has already been requested since **a long time ago** in the opencv4 port and never done.

It looks like I should give up keeping opencv in a proper shape here on vcpkg, because the moment a PR about it is accepted, the moment it is almost surely damaged.

@vicroms sorry for ranting, but to be honest my thoughts now are that I might not contribute anymore to vcpkg, at least not without a proper CI in place to check features better, to preserve port quality and to at least guarantee not to regress going on (something that is continuously happening here)
Of course, this requires a major improvement in revision quality and procedures.

**Comment by vicroms** [comment]
Hi @cenit,

Thanks for your feedback and contributions to vcpkg – you’re one of our most active community members. I'm sorry about the issues with the OpenCV port and moving forward we’re committed to improve the experience and collaboration with our contributors.

For now, I've reverted the changes, as in it's current state, this PR regresses OpenCV features.

I would like to unblock this update, and as I understand from your comments on this and the related PR (#8557) there are changes that need to be done in the PR and in our CI testing to make sure that no features are regressed.

Moving forward, the vcpkg team would like to start a conversation with you and other OpenCV contributors to better understand how we can expand our CI coverage to ensure a higher quality control for further OpenCV upgrades/changes.

Also, if you have any feedback for other areas of improvement in vcpkg please feel free to reach me (viromer@microsoft.com) or the team at vcpkg@microsoft.com. We would be glad to receive your insights and opinions.

**Comment by cdcseacave** [comment]
Hi there, can you pls solve this and merge?

**Comment by cenit** [comment]
i'm very very busy at the moment, sorry, so I cannot guarantee any timing. I can try to push it a little bit up in my stack, but i'd be happier to help reviewing a PR if it happens

**Comment by JackBoosY** [comment]
@cenit I will do this job.

**Comment by cenit** [comment]
@jackboosy thanks

**Pull request merged**
