### PR TITLE
[brotli] Remove debug tools

### PR DESCRIPTION
**Pull request by Thomas1664**
**Describe the pull request**

- #### What does your PR fix?
  Remove tools that are created during debug builds.

### CODE REVIEW

**Review by LilyWangLL — APPROVED** [review]

**Comment by dg0yt** [comment]
> * Remove tools that are created during debug builds.

Is this to become a general policy? Given the number of PRs I make, it would be good to know for sure.

**Comment by JackBoosY** [comment]
> > * Remove tools that are created during debug builds.
> 
> Is this to become a general policy? Given the number of PRs I make, it would be good to know for sure.

Yeah, the debug tools are useless. That's why `vcpkg_copy_tools` only copy the release tools.

**Comment by BillyONeal** [comment]
This looks like you modernized the port file but I don't see any actual debug tools removal here? All the changes look like merely changing `vcpkg_Xxx_cmake` into `vcpkg_cmake_Xxx`.

**Comment by BillyONeal** [comment]
(To be clear, I'm happy to merge this as-is but want to make sure the changes you want are actually here)

**Comment by BillyONeal** [comment]
Nevermind I'm blind

**Pull request merged**
