### PR TITLE
Juandent patch 1 - portfile for latest version of cppwinrt

### PR DESCRIPTION
**Pull request by juandent**

### CODE REVIEW

**Comment by juandent** [comment]
Although the x86-windows builds ok, when trying to install another triplet I get :

> Package cppwinrt:x64-windows is already installed

yet I have already executed 

> vcpkg remove cppwinrt

So, how do I tell vcpkg that the other triplets are not installed?

Regards,
Juan Dent

**Comment by juandent** [comment]
On executing vcpkg install cppwinrt I am getting this error:

```The following packages will be built and installed:
    cppwinrt:x86-windows
Building package cppwinrt:x86-windows...
-- CURRENT_INSTALLED_DIR=C:/Users/Juan Dent/C++ Development/Source Components/vcpkg-master/installed/x86-windows
-- DOWNLOADS=C:/Users/Juan Dent/C++ Development/Source Components/vcpkg-master/downloads
-- CURRENT_PACKAGES_DIR=C:/Users/Juan Dent/C++ Development/Source Components/vcpkg-master/packages/cppwinrt_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/Users/Juan Dent/C++ Development/Source Components/vcpkg-master/buildtrees/cppwinrt
-- CURRENT_PORT_DIR=C:/Users/Juan Dent/C++ Development/Source Components/vcpkg-master/ports/cppwinrt/.
-- Using cached C:/Users/Juan Dent/C++ Development/Source Components/vcpkg-master/downloads/cppwinrt-spring_2017_creators_update_for_vs_15.3.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Performing post-build validation
-- Performing post-build validation done
Building package cppwinrt:x86-windows... done
Installing package cppwinrt:x86-windows...
value was error
```
Have no idea what is going on. It worked the first time.
then I uninstalled it and removed old references...

Regards,
Juan Dent

**Comment by alexkaratarakis** [comment]
@juandent 
1) Similarly to `vcpkg install`, you need to specify the triplet for `vcpkg remove` as well. Therefore, you would need to do: 

`vcpkg remove cppwinrt:x64-windows`

2) It looks like the package is being built correctly, but when "installing" it (i.e. placing the output in the right place), something goes wrong. However, the error message `vcpkg` gives is not helpful. Please run: 

`vcpkg install cppwinrt:x86-windows --debug` 

and paste the output here. This will tell us the exit point so we can improve the error handling/message there.

**Comment by juandent** [comment]
Upon executing 

> vcpkg.exe install cppwinrt:x86-windows --debug

I get this:

> The following packages will be installed:
    cppwinrt:x86-windows
Installing package cppwinrt:x86-windows...
value was error
[DEBUG] ..\src\vcpkglib.cpp(201)

**Comment by juandent** [comment]
I also had deleted manually directories with cppwinrt as part of their name... I don't know if this corrupted the vcpkg database...

**Comment by juandent** [comment]
Cleaning everything up, upon executing 

> vcpkg.exe install cppwinrt:x86-windows --debug

I get this:

> The following packages will be built and installed:
    cppwinrt:x86-windows
Building package cppwinrt:x86-windows...
[DEBUG] _wpopen("where.exe cmake 2>&1")
[DEBUG] _wpopen() returned 0
[DEBUG] _wpopen(""C:\Users\Juan Dent\C++ Development\Source Components\vcpkg-master\downloads\cmake-3.8.0-win32-x86\bin\cmake.exe" --version 2>&1")
[DEBUG] _wpopen() returned 1
[DEBUG] _wpopen(""C:\Program Files\CMake\bin\cmake.exe" --version 2>&1")
[DEBUG] _wpopen() returned 0
[DEBUG] _wpopen("where.exe git 2>&1")
[DEBUG] _wpopen() returned 0
[DEBUG] _wpopen(""C:\Users\Juan Dent\C++ Development\Source Components\vcpkg-master\downloads\MinGit-2.11.1-32-bit\cmd\git.exe" --version 2>&1")
[DEBUG] _wpopen() returned 1
[DEBUG] _wpopen(""C:\Program Files\Git\bin\git.exe" --version 2>&1")
[DEBUG] _wpopen() returned 0
[DEBUG] _wpopen(""C:\Program Files\CMake\bin\cmake.exe" "-DCMAKE_TRIPLET_FILE=C:/Users/Juan Dent/C++ Development/Source Components/vcpkg-master/triplets/x86-windows.cmake" -P "C:/Users/Juan Dent/C++ Development/Source Components/vcpkg-master/scripts/get_triplet_environment.cmake" 2>&1")
[DEBUG] _wpopen() returned 0
[DEBUG] _wpopen("powershell -NoProfile -ExecutionPolicy Bypass -Command "& {& 'C:\Users\Juan Dent\C++ Development\Source Components\vcpkg-master\scripts\findVisualStudioInstallationInstances.ps1' }" 2>&1")
[DEBUG] _wpopen() returned 0
[DEBUG] _wspawnlpe(cmd.exe /c ""C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64_x86   2>&1 && "C:\Program Files\CMake\bin\cmake.exe" "-DCMD=BUILD" "-DPORT=cppwinrt" "-DCURRENT_PORT_DIR=C:/Users/Juan Dent/C++ Development/Source Components/vcpkg-master/ports/cppwinrt/." "-DTARGET_TRIPLET=x86-windows" "-DVCPKG_PLATFORM_TOOLSET=v141" "-DVCPKG_USE_HEAD_VERSION=0" "-D_VCPKG_NO_DOWNLOADS=0" "-DGIT=C:/Program Files/Git/bin/git.exe" -P "C:/Users/Juan Dent/C++ Development/Source Components/vcpkg-master/scripts/ports.cmake"")
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0.26730.12
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64_x86'
-- CURRENT_INSTALLED_DIR=C:/Users/Juan Dent/C++ Development/Source Components/vcpkg-master/installed/x86-windows
-- DOWNLOADS=C:/Users/Juan Dent/C++ Development/Source Components/vcpkg-master/downloads
-- CURRENT_PACKAGES_DIR=C:/Users/Juan Dent/C++ Development/Source Components/vcpkg-master/packages/cppwinrt_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/Users/Juan Dent/C++ Development/Source Components/vcpkg-master/buildtrees/cppwinrt
-- CURRENT_PORT_DIR=C:/Users/Juan Dent/C++ Development/Source Components/vcpkg-master/ports/cppwinrt/.
-- Downloading https://github.com/Microsoft/cppwinrt/archive/spring_2017_creators_update_for_vs_15.3.tar.gz...
-- Downloading https://github.com/Microsoft/cppwinrt/archive/spring_2017_creators_update_for_vs_15.3.tar.gz... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Extracting source C:/Users/Juan Dent/C++ Development/Source Components/vcpkg-master/downloads/cppwinrt-spring_2017_creators_update_for_vs_15.3.tar.gz
-- Extracting done
[DEBUG] _wspawnlpe() returned 0
-- Performing post-build validation
-- Performing post-build validation done
Building package cppwinrt:x86-windows... done
Installing package cppwinrt:x86-windows...
value was error
[DEBUG] ..\src\vcpkglib.cpp(201)

**Comment by ras0219-msft** [comment]
Sorry for the delay and thanks for working on this!

This failure indicates a corruption in the internal database; the easiest way to fix this is to simply delete the entire `installed\` folder and reinstall any packages you'd like to have.

That said, the portfile works great! I've removed the spare one you accidentally checked into the root as well 😄.

**Pull request merged**
