### PR TITLE
[libgit2] update to 0.27.4

### PR DESCRIPTION
**Pull request by fcharlie**
Update libgit2 and support static build.

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for the PR!

`vcpkg_from_github()` already passes `BUILD_SHARED_LIBS` based on the `VCPKG_LIBRARY_LINKAGE` setting, so explicitly testing and adding it is not needed. Note that the valid settings are `dynamic` and `static`.

LGTM pending CI validation!

**Comment by fcharlie** [comment]
@ras0219-msft  Thanks.

**Comment by fcharlie** [comment]
@ras0219-msft Update to 0.27.4 see: https://github.com/libgit2/libgit2/releases/tag/v0.27.4 fix smart protocol.

**Comment by ras0219-msft** [comment]
Thanks again!

**Pull request merged**
