### PR TITLE
[jwt-cpp] Fixes SHA512

### LINKED ISSUE #19837: [Thalhammer-jwt-cpp] checksum failure
**Host Environment**
- OS: Linux (all). probably Windows too. 
- Compiler: gcc

**To Reproduce**
`./vcpkg install jwt-cpp`

**Failure logs** 
`
[DEBUG] popen(curl --fail -L https://github.com/Thalhammer/jwt-cpp/archive/60122bbd8e6b9009c4633c1a33ea94c5b682034a.tar.gz --create-dirs --output /tmp/codon/tmp/cache/vcpkg/downloads/Thalhammer-jwt-cpp-60122bbd8e6b9009c4633c1a33ea94c5b682034a.tar.gz.3615.part 2>&1)
[DEBUG] cmd_execute_and_stream_data() returned 0 after   273358 us
Error: Failed to download from mirror set:
File does not have the expected hash:
             url : [ https://github.com/Thalhammer/jwt-cpp/archive/60122bbd8e6b9009c4633c1a33ea94c5b682034a.tar.gz ]
       File path : [ /tmp/codon/tmp/cache/vcpkg/downloads/Thalhammer-jwt-cpp-60122bbd8e6b9009c4633c1a33ea94c5b682034a.tar.gz.3615.part ]
   Expected hash : [ d2c6e2174cd86c27b8866f6ea50a379a321788e91f97a0548e694d11469c05d93b0713e0c38b37a8f14a0aded4fc4635599dcfb50142e4496fb3c8b9f7e5f8cd ]
     Actual hash : [ ae905e217824d21ec9f098f562d993fbae71b2223e65f3bbcc29d352af61f2aa09b5c6b12c7d94742901a1374f9683335d3b4934c25b11500b710398331f6cb4 ]`

**Additional context**
Changing the hash on the portfile fixes the issue, but I'm not sure if the problem is with vcpkg's hash, or the upstream repo.

### PR DESCRIPTION
**Pull request by pyrotechnics-io**
This is a fix for #19837

Not sure why the hash worked a few days ago but appears to have broken now though (that needs some investigation). But the build is indeed broken

**Describe the pull request**

- #### What does your PR fix?  
Error on builds when pulling jwt-cpp

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
all

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  `Your answer`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  <Yes / I am still working on this PR>

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
@pyrotechnics-io Can you please sign CLA first?

**Comment by pyrotechnics-io** [comment]
> @pyrotechnics-io Can you please sign CLA first?

Signed

**Comment by pyrotechnics-io** [comment]
This can be merged soon?

**Comment by BillyONeal** [comment]
Sorry about that, and thanks :)

**Comment by pyrotechnics-io** [comment]
Thank you so much for all the work you guys do in general. Just happy I could help :-)

**Pull request merged**
