### PR TITLE
[lz4] update to 1.9.3

### PR DESCRIPTION
**Pull request by Thieum**
- Update lz4 to 1.9.3 https://github.com/lz4/lz4/releases/tag/v1.9.3
- no changes in triplet support. tested as an install dependency for libarchive on x86-windows and x64-windows.

### CODE REVIEW

**Comment by Thieum** [comment]
Error at least with cmake could be related the same issue we have in #16845

**Comment by NancyLi1013** [comment]
The failures on x64-linux are like this:

```
c++: error: /mnt/vcpkg-ci/installed/x64-linux/debug/lib//libglib-2.0.a: No such file or directory
c++: error: /mnt/vcpkg-ci/installed/x64-linux/debug/lib//libglib-2.0.a: No such file or directory
c++: error: /mnt/vcpkg-ci/installed/x64-linux/debug/lib//libglib-2.0.a: No such file or directory
```
This error is not related with this PR, which needs to depend on the changes in PR #15808.

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
LGTM now, thanks for your update @Thieum.

**Review by ytbigvinny27 — COMMENTED** [review]
~~~~~🤌🏾

**Pull request merged**
