### PR TITLE
[gdal] Workaround for `vcpkg clean` issue

### PR DESCRIPTION
**Pull request by dg0yt**
- #### What does your PR fix?  
  Early removes the Autotest directory which causes issues with the vcpkg clean command in CI.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  unchanged, no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by BillyONeal** [comment]
Thanks!

**Comment by BillyONeal** [comment]
A thing I don't understand though is that I've tried to repro this myself and never end up with an autotest directory...

**Comment by dg0yt** [comment]
> A thing I don't understand though is that I've tried to repro this myself and never end up with an autotest directory...

Then you missed a git pull? Before the last change, it used release tarballs which contained just the gdal subtree. (Now gdal committed to switch to cmake 🎉, and the directory tree will change over the next 18 months.)

**Comment by BillyONeal** [comment]
> > A thing I don't understand though is that I've tried to repro this myself and never end up with an autotest directory...
> 
> Then you missed a git pull? Before the last change, it used release tarballs which contained just the gdal subtree. (Now gdal committed to switch to cmake 🎉, and the directory tree will change over the next 18 months.)

Ah yes, that must be what I missed. Thanks!

**Pull request merged**
