### PR TITLE
[scripts] Remove implicitly defined MSVC runtime library flags

### PR DESCRIPTION
**Pull request by yurybura**
Starting with CMake 3.15, the [CMAKE_MSVC_RUNTIME_LIBRARY](https://cmake.org/cmake/help/latest/variable/CMAKE_MSVC_RUNTIME_LIBRARY.html) variable selects the MSVC runtime library. Compiler flags such as `/MT /MTd /MD /MDd /D_DEBUG` do not need to be added implicitly.

### CODE REVIEW

**Comment by BillyONeal** [comment]
@data-queue @JavierMatosD @ras0219-msft @vicroms and I discussed this today.

> Starting with CMake 3.15, the [CMAKE_MSVC_RUNTIME_LIBRARY](https://cmake.org/cmake/help/latest/variable/CMAKE_MSVC_RUNTIME_LIBRARY.html) variable selects the MSVC runtime library. Compiler flags such as `/MT /MTd /MD /MDd /D_DEBUG` do not need to be added implicitly.

Removing adding them seems like a breaking change, however, as we don't know that a customer isn't using a copy of cmake older than that.

Is there any harm in just specifying `/MT /MTd /MD /MDd` more than once? We could add the new variables you're adding without removing the existing ones.

Is there a specific build that is broken without this change and fixed with it we could use as an example for discussion? (And does that example need `/MT /MTd /MD /MDd` *removed* or would just making the new variable available work?)

> @yurybura You can directly close this PR. since cmake_minimum_required(VERSION 3.14) 

I think we should understand the problem @yurybura is reporting before asking them to close PRs out of hand.

**Comment by yurybura** [comment]
@BillyONeal I have postponed this this OR until I can suggest working solution. I will answer in detail your questions soon.

**Comment by yurybura** [comment]
Duplicating comment https://github.com/microsoft/vcpkg/pull/34123#issuecomment-1761351007
According to the CMake documentation, `CMAKE_MSVC_RUNTIME_LIBRARY` does not overwrite the `/MT[d]`, `/MD[d]` flags manually specified in `CMAKE_<LANG>_FLAGS_<CONFIG>`. I think VCPKG should detect running CMake version and define `CMAKE_MSVC_RUNTIME_LIBRARY` (CMake 3.15 or later) **or** runtime flags with `CMAKE_<LANG>_FLAGS_<CONFIG>` (before CMake 3.15). This is what I going to do in this PR. Define `_DEBUG` is redundant anyway.

**Comment by yurybura** [comment]
There are no plans to continue for now.

**Pull request closed without merging**
