### PR TITLE
Update vcpkg-tool to 2024-12-09.

### PR DESCRIPTION
**Pull request by JavierMatosD**
https://github.com/microsoft/vcpkg-tool/releases/tag/2024-12-09

Also uses vcpkg.exe to unpack 7z.exe archives.

This fixes a bug with `vcpkg_find_acquire(CLANG)` since we are currently downloading its archive as a 7z.exe even though it is not a 7z archive.

The following are additional meaningful tool changes:

* [spdx] Fix several bugs by @Thomas1664 in https://github.com/microsoft/vcpkg-tool/pull/1377
* Use `GITHUB_SERVER_URL` to change GitHub API host for dependency graph submission by @luncliff in https://github.com/microsoft/vcpkg-tool/pull/1547

Thank you contributors!

### CODE REVIEW

**Comment by JavierMatosD** [comment]
vcpkg_find_acquire(7z) should give use the full 7zip as a.7z.exe, the tool should unpack that. ✅

`vcpkg fetch 7zip` should return full 7zip so we should be able to use 7zip for literally any unpacking. ✅ (We don't need 7zr for anything)

Problem:
vcpkg_find_acquire(CLANG) downloads as a .7z.exe -> triggers tool extraction  -> 💣 (not a real 7z archive)

**Comment by BillyONeal** [comment]
Note that this PR needs to be landed using administrative permissions as a *MERGE*, not a squash, as we need https://github.com/microsoft/vcpkg/pull/42608/commits/0c4cf19224a049cf82f4521e29e39f7bd680440c to be accessible 'forever' as it is burned into that matching tool release.

**Comment by BillyONeal** [comment]
Full rebuild triggered here: https://dev.azure.com/vcpkg/public/_build/results?buildId=110261&view=results

**Review by BillyONeal — CHANGES_REQUESTED** [review]
Marking 'request changes' so that we don't forget to merge rather than squash.

**Comment by BillyONeal** [comment]
VS smoke test passed.

**Review by WangWeiLin-MV — APPROVED** [review]
Test with example ports `intel-mkl` and `gmp`, download files checked:

+ vcpkgTools.xml
  - `{VCPKG_DOWNLOADS}/downloads/tools/7zr-24.09-windows/7zr.exe`
  - `{VCPKG_DOWNLOADS}/downloads/7z2409.7z.exe`
  - `{VCPKG_DOWNLOADS}/downloads/LLVM-15.0.6-win64.exe`
+ win32_extract_self_extracting_7z
  - `{VCPKG_DOWNLOADS}/downloads/7z2409.7z`
+ extract_archive
  - `{VCPKG_DOWNLOADS}/downloads/tools/7zip-24.09-windows/7z.exe`
+ vcpkg_extract_archive.cmake
  - `{VCPKG_DOWNLOADS}/downloads/tools/clang/clang-15.0.6/bin/clang.exe`
  - `{VCPKG_DOWNLOADS}/downloads/tools/7z/24.09/7z.exe`

**Review by BillyONeal — APPROVED** [review]

**Pull request merged**
