### PR TITLE
[tensorflow-common] fix regex pattern of static link script

### PR DESCRIPTION
**Pull request by JackyYin**
Fix regular expression for static link pattern script.

Pattern `r"\.\d\.\d\.\d"` cannot match string `2.10.0`, changed it to `r"\.\d+\.\d+\.\d+"`.

Without this modification, we can't generate static-linked library (.a) correctly in osx.

reference issue: https://github.com/microsoft/vcpkg/issues/27411

### CODE REVIEW

**Comment by autoantwort** [comment]
Could you also remove 
```
tensorflow:x64-osx=fail
tensorflow-cc:x64-osx=fail
```
from ci.baseline.txt

**Comment by LilyWangLL** [comment]
Thanks for your PR. Please add `"port-version": 1,` in `vcpkg.json` of `tensorflow-common`.

**Comment by JackyYin** [comment]
Hi @LilyWangLL @autoantwort,
I fixed `ci.baseline.txt` and `port-version`,
could you help review again?

**Review by LilyWangLL — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for fixing OSX!

**Pull request merged**
