### PR TITLE
[glslang,pthreads,shaderc,spirv-tools,nlohmann-json] Various fixes/improvements

### PR DESCRIPTION
**Pull request by ChaoJia**
glslang: added include dir to target config file;
pthreads: added path to debug version of dll;
shaderc: export target config file, make shaderc::combined optional as a feature;
spirv-tools: vcpkg_fixup_cmake_targets, added INTERFACE_INCLUDE_DIRECTORIES for target spirv-tools::SPIRV-Tools;
nlohmann-json: added fifo_map.hpp (fifo_map.hpp helps preserve the insertion order of object elements);

### CODE REVIEW

**Comment by grdowns** [comment]
Thanks for all these additions, @ChaoJia! If you run into any problems getting parts of this PR to work, consider splitting unrelated changes into separate PRs to keep the review process easy and make diagnosing problems easier.

**Comment by grdowns** [comment]
Also, don't forget to update the CONTROL file versions! :smile:

**Comment by ChaoJia** [comment]
Now it is a bit confusing. [raw xml results](https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/14999/artifacts?artifactName=raw%20xml%20results&api-version=5.2-preview.5&%24format=zip) suggests all of the packages modified by this commit have passed on Linux. Failed ones don't seem to be affected by these packages. Same situation with https://github.com/microsoft/vcpkg/pull/8432 (pthreads split from this PR).

**Comment by ChaoJia** [comment]
@grdowns Thanks for the advice. Fixes for glslang, shaderc and spirv-tools passed all the tests (pull request #8436). 

Seems pthreads (#8432) is the cause of the failure above. Maybe add a dependency filter to package __pthread__ could do the trick (`Build-Depends: pthreads  (windows)`, this does make sense because pthreads is only for windows 😄). Will try it out some time later.

As for nlohmann-json, I'll first ask the author whether he is willing to put the stand-alone fifo-map.hpp into the library or not. If so, I don't have to bother with the version.

Close this PR now.

**Pull request closed without merging**
