### PR TITLE
[stxxl] Add new port

### PR DESCRIPTION
**Pull request by myd7349**

### CODE REVIEW

**Comment by vicroms** [comment]
@myd7349 is this still a work in progress?

**Comment by myd7349** [comment]
@vicroms Sorry for the long delay. These is something wrong with the CMake integration. I will process it this weekend.

**Comment by myd7349** [comment]
I added a patch to fix the missing include directory in the cmake target. I also created a PR for this in upstream repo: https://github.com/stxxl/stxxl/pull/95.

**Comment by myd7349** [comment]
I also tried to add shared library building support by applying an additional patch:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 3f4e5308..fd92f7f2 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -120,6 +120,10 @@ option(USE_TPIE "Try to compile extra benchmarks from the 2007 S&PE paper with a
 option(BUILD_STATIC_LIBS "Build static library version of libstxxl" ON)
 option(BUILD_SHARED_LIBS "Build shared library version of libstxxl" OFF)
 
+if (BUILD_SHARED_LIBS)
+    set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)
+endif ()
+
 ### allow user to specify other installation paths
 
 set(INSTALL_BIN_DIR "bin" CACHE PATH "Installation directory for executables")

```

**Comment by myd7349** [comment]
Test project: https://github.com/myd7349/Ongoing-Study/tree/master/cpp/CMake/vcpkg/stxxl_copy_file_example

**Comment by Rastaban** [comment]
The only failures I see in this new port are in the UWP ports, which I am okay with.  @myd7349 this is currently tagged as wip, as soon as you are comfortable with removing that tag then we will probably merge the PR.

[install-x64-uwp-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2907153/install-x64-uwp-dbg-out.log)

**Comment by myd7349** [comment]
@Rastaban I am fine with removing the `WIP` tag. :-)

**Pull request merged**
