### PR TITLE
[drogon] Update to 1.7.5

### PR DESCRIPTION
**Pull request by an-tao**

### CODE REVIEW

**Review by JonLiu1993 — APPROVED** [review]

**Comment by JonLiu1993** [comment]
All features are tested successfully in the following triplet:
- x86-windows
- x64-windows
- x64-windows-static

**Comment by kotori2** [comment]
This PR breaks `Drogon` linking on Linux. 
```
cmake -DCMAKE_TOOLCHAIN_FILE=/home/kotori/vcpkg/scripts/buildsystems/vcpkg.cmake ..
-- Running vcpkg install
-- Running vcpkg install - done
-- Found Jsoncpp: /home/kotori/untitled2/build/vcpkg_installed/x64-linux/include  
-- jsoncpp verson:1.9.5
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found OpenSSL: /home/kotori/untitled2/build/vcpkg_installed/x64-linux/lib/libcrypto.a (found version "1.1.1n")  
-- Found c-ares: /home/kotori/untitled2/build/vcpkg_installed/x64-linux/include  
-- Found UUID: /home/kotori/untitled2/build/vcpkg_installed/x64-linux/lib/libuuid.a
-- Found ZLIB: /home/kotori/untitled2/build/vcpkg_installed/x64-linux/lib/libz.a (found version "1.2.11") 
-- Found SQLite3: /home/kotori/untitled2/build/vcpkg_installed/x64-linux/lib/libsqlite3.a  
-- Found Brotli: /home/kotori/untitled2/build/vcpkg_installed/x64-linux/lib/libbrotlidec-static.a  
-- Looking for C++ include filesystem
-- Looking for C++ include filesystem - found
-- Performing Test CXX_FILESYSTEM_NO_LINK_NEEDED
-- Performing Test CXX_FILESYSTEM_NO_LINK_NEEDED - Success
-- Configuring done
CMake Error at /home/kotori/vcpkg/scripts/buildsystems/vcpkg.cmake:557 (_add_executable):
  Target "untitled2" links to target "unofficial::libmariadb" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:6 (add_executable)


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

CMakeLists.txt
```
cmake_minimum_required(VERSION 3.16.3)
project(untitled2)

set(CMAKE_CXX_STANDARD 20)
find_package(Drogon CONFIG REQUIRED)
add_executable(untitled2 main.cpp)
target_link_libraries(untitled2 Drogon::Drogon)
```

**Comment by an-tao** [comment]
did you upgrade the dependencies of drogon in vcpkg?

**Comment by kotori2** [comment]
> did you upgrade the dependencies of drogon in vcpkg?

Yes. 
```
$ cat ../vcpkg.json 
{
  "name": "test",
  "version-string": "0.1",
  "port-version": 1,
  "homepage": "",
  "description": "",
  "dependencies": [
    {
      "name": "drogon",
      "features": [ "ctl", "mysql", "sqlite3" ]
    }
  ],
  "builtin-baseline": "f3a68220a5b48132e53708ed76411f04976a911a"
}
```
982cf2bf181686481908a368239b4368801d09b5 (previous commit) works without any issue.

**Comment by dg0yt** [comment]
IIUC we lack the initialization of `MySQL_FOUND` now. That's why the `find_dependency(unofficial-libmariadb)` isn't  called in the exported config.

In the context of GDAL, I learned to appreciate the extended signature of `find_package`. If a project needs a `MySQL_FOUND`, a patch could use `find_package(MySQL NAMES unofficial-mariadb)`. This would allow smaller patches with less side effects.

**Pull request merged**
