### PR TITLE
[ffmpeg] update to 4.0

### PR DESCRIPTION
**Pull request by jasjuang**
Tested and everything compiles as usual on windows. 

The openssl and opencv patch needs to be updated. Also switched the compilation order to debug first instead of release first.

### CODE REVIEW

**Comment by jasjuang** [comment]
@alexkaratarakis @ras0219-msft Can you please look into this? Thanks!

**Comment by alexkaratarakis** [comment]
@jasjuang 
Sorry, I was working on this.
Our tests showed that it breaks aubio and pangolin. I had fixed aubio and I just pushed the fix in your branch.
I haven't been able to fix Pangolin yet.
Related: https://github.com/stevenlovegrove/Pangolin/pull/318

**Comment by crackedmind** [comment]
Any progress ?

**Comment by jasjuang** [comment]
close due to #4831

**Pull request closed without merging**
