### PR TITLE
[libjpeg-turbo] Upgrade to 2.1.3

### PR DESCRIPTION
**Pull request by reynoldsbd**
**Describe the pull request**

- #### What does your PR fix?  

  None

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  

  All triplets supported

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  

  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  

  Yes

### CODE REVIEW

**Comment by reynoldsbd** [comment]
Looks like a few of the PR jobs are failing early while trying to extract 7zip. Seems unrelated to my PR. Could this be a transient issue?

**Comment by Thomas1664** [comment]
> Looks like a few of the PR jobs are failing early while trying to extract 7zip. Seems unrelated to my PR. Could this be a transient issue?

@reynoldsbd I experienced the same issue with my recent PRs. Merging master into this PR should fix CI for all triplets except `arm64_windows` and `x64_windows_static_md`. See #23284

**Review by JonLiu1993 — APPROVED** [review]

**Comment by reynoldsbd** [comment]
@JonLiu1993 it sounds like these CI issues might be tapering down. Is there an easy way for me to restart the checks?

**Comment by JonLiu1993** [comment]
@reynoldsbd, I have rerun the CI, let's wait for the result

**Review by JonLiu1993 — APPROVED** [review]

**Pull request merged**
