### PR TITLE
Updates for Highfive (fix for MacOS) and eigen 3

### PR DESCRIPTION
**Pull request by fradav**
- Highfive fix for MacOS (same as Win32) bump to 2.0
- Eigen3 bump to 3.3.90

### CODE REVIEW

**Comment by Neumann-A** [comment]
> Eigen3 bump to 3.3.90

that is something you just invented..... Eigen is still at 3.3.7.

**Comment by fradav** [comment]
Not eigen-dev.
http://eigen.tuxfamily.org/dox-devel/
Eigen  3.3.90 (mercurial changeset 54b70baafc92)

**Comment by Neumann-A** [comment]
that is equivalent to `vcpkg install eigen3 --head`
portfiles in vcpkg should use/stay with official releases. 
(Note: I also use head, but that is not the point here)

**Comment by fradav** [comment]
Ok I didn't know --head option, thanks.
Then just ignore eigen3 patch. Should I make a new PR for highfive ?

**Comment by Rastaban** [comment]
You could create a new PR with only the highfive change or you can back out the eigen3 change in this PR, whichever is more convenient for you.  Don't forget to update the highfive/CONTROL file though.

**Comment by fradav** [comment]
Ok, new PR, discard this one, please.

**Pull request closed without merging**
