### PR TITLE
[opentelemtery-cpp] update to 1.11.0

### LINKED ISSUE #33772: [opentelemetry-cpp] update to 1.11.0
### Library name

opentelemetry-cpp

### New version number

1.11.0

### Other information that may be useful (release notes, etc...)

vcpkg has 1.9.1, which is 2 releases behind.

https://github.com/open-telemetry/opentelemetry-cpp/releases/tag/v1.11.0

### PR DESCRIPTION
**Pull request by jimwang118**
Fixes https://github.com/microsoft/vcpkg/issues/33772

1. Update to 1.11.0.
2. Delete feature `otlp` based on upstream PR [2161](https://github.com/open-telemetry/opentelemetry-cpp/pull/2161).

- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [X] SHA512s are updated for each updated download
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

Usage test pass with following triplets:

```
x86-windows
x64-windows
x64-windows-static
```

### CODE REVIEW

**Comment by kirby-mimic** [comment]
I see that there was also a PR for v1.10.0 https://github.com/microsoft/vcpkg/pull/33190 that was also never merged and left in a similar state.  Do the failing checks keep the merge from happening?

**Comment by jimwang118** [comment]
> I see that there was also a PR for v1.10.0 #33190 that was also never merged and left in a similar state. Do the failing checks keep the merge from happening?

Yes, CI failure will prevent the merge.

**Comment by willie** [comment]
What does this mean? The other PR is the one to track?

**Comment by dg0yt** [comment]
@jimwang118 Did you accidentally delete your repo? This deletion closed all your PRs here.

**Comment by jimwang118** [comment]
> @jimwang118 Did you accidentally delete your repo? This deletion closed all your PRs here.

Yes, I accidentally deleted the forked library, so the PR was closed, I re-forked a library and submitted a new PR.

**Pull request closed without merging**
