### PR TITLE
[libslirp] fix dependence on osx and add usage

### LINKED ISSUE #35137: [libslirp] Building a project that links libslirp more than once fails on macOS
**Describe the bug**
When building a project that uses libslirp, the build will succeed the first time after configuring the build directory, but after manually running the configure step again, or having changed something that causes it to re-run on build, linking will fail as the parameters for linking the system frameworks will be malformed.

**Environment**
- OS: macOS 14.1 arm64
- Compiler: Apple clang version 15.0.0 (clang-1500.0.40.1)

**To Reproduce**
[slirp-test.tar.gz](https://github.com/microsoft/vcpkg/files/13370767/slirp-test.tar.gz)
Above is a minimum project that reproduces the issue. To reproduce:
1. `cmake -B build -DVCPKG_ROOT=/path/to/your/vcpkg`
2. `cmake --build build` -- the build will succeed this time
3. `cmake -B build` to reconfigure the build directory
4. `cmake --build build` again, this time it will fail, see output below

**Expected behavior**
The build will succeed even when the build directory is reconfigured.

**Failure logs**
[slirperr.txt](https://github.com/microsoft/vcpkg/files/13370786/slirperr.txt)

**Additional context**
This also seems to happen when building for macOS x64. I have not tested Windows or Linux builds, but I suspect this is macOS-specific due to how frameworks are linked there.

### PR DESCRIPTION
**Pull request by FrankXie05**
Fix https://github.com/microsoft/vcpkg/issues/35137

The usage has been tested successfully locally on `x64-osx`.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] ~~SHA512s are updated for each updated download~~
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Review by Cheney-W — DISMISSED** [review]

**Comment by data-queue** [comment]
Is there an upstream PR?

**Comment by FrankXie05** [comment]
> Is there an upstream PR?

https://gitlab.freedesktop.org/slirp/libslirp/-/issues/73
Done.

**Comment by FrankXie05** [comment]
Closed PR by https://gitlab.freedesktop.org/slirp/libslirp/-/issues/73#note_2180513.
And fix by commit https://github.com/microsoft/vcpkg/issues/35137#issuecomment-1829235472

**Pull request closed without merging**
