### PR TITLE
[mpir] detect Windows SDK version (was: retarget MSVS2017 to Windows 10 SDK)

### LINKED ISSUE #720: mpir fails to build with VS2017 on Windows 10
In log it complains that:

`error MSB8036: The Windows SDK version 7 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [F:\vcpkg\buildtrees\mpir\src\mpir-2.7.2\build.vc14\dll_mpir_gc\dll_mpir_gc.vcxproj]`

If I open the solution in VS and retarget it to whatever toolset and Windows SDK platform I have, then installation works.

### PR DESCRIPTION
**Pull request by Mixaill**
Should fix #720

### CODE REVIEW

**Comment by stoperro** [comment]
Thanks Mixaill. I think you may have forgotten to `git add` the patches/0001-msvs2017-winsdk.patch file as still same error (no SDK for Windows 8.1), also I noticed this:
F:\vcpkg_mixaill>vcpkg install mpir:x64-windows
INFO: Could not find files for the given pattern(s).

Likely above (very non-informative) info is about that file.

Btw. will this patch hardcode to some version of Win10 SDK? I wonder if this will be best solution as I think people may have different SDK with different revisions and may be unlucky not to have exact revision. Or maybe there is already some kind of vcpkg configuration option that automatically selects some default Win SDK from disk, and this can be reused by patches for every library that vcpkg provides?

**Comment by ras0219-msft** [comment]
We really do need to solve the toolset and winsdk problem across all msbuild portfiles.

I believe this should be possible by adding /p:... overrides to the core `vcpkg_build_msbuild` that set the toolset and winsdk version.

As for selecting the right winsdk version, we have a PowerShell script we use as part of bootstrap.ps1 to solve this exact problem. I'm on mobile at the moment, but I can look it up later.

**Comment by Mixaill** [comment]
Hopefully fixed in the right way

**Comment by stoperro** [comment]
Great! I'm now on Mixaill:msvs2017-mpir-winsdk and 'vcpkg install mpir:x64-windows' works there after last fixes.

I see in commits that this platform selection logic is used, so hopefully it will work for other users too :)

**Comment by Mixaill** [comment]
What about override SDK version by default?

So,
* `vcpkg_build_msbuild()` - override to `vcpkg_get_windows_sdk()` version
* `vcpkg_build_msbuild(TARGET_PLATFORM_VERSION ${SOMETHING})` - override to `${SOMETHING}`
* `vcpkg_build_msbuild(TARGET_PLATFORM_VERSION FROM_PROJECT)` - use version from project

@ras0219-msft what do you think about?

**Comment by ras0219-msft** [comment]
@Mixaill Definitely agree we should always override it by default.

I'm actually quite skeptical about whether there is a valid use case for allowing the portfile or project to specify it. They can't _upgrade_ it, because we find the latest. They could _downgrade_ it, but why? The most reasonable case to downgrade the SDK version is if you want to target an older Windows version -- in which case you need to downgrade *all* libraries! This says it should be a triplet setting, not a portfile setting.

That said, thanks for the hard work here! I did some cleanup during the merge which I've pushed to your branch.

**Pull request merged**
