### PR TITLE
[vcpkg baseline][libqcow] Update to new version

### PR DESCRIPTION
**Pull request by LilyWangL**
**Describe the pull request**

- What does your PR fix? 
Update libqcow to new version and fix download source failed.

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
ping @dan-shaw for review and merge this PR, this blocked the pipeline test.

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
