### PR TITLE
Update baseline to fix osx failure

### PR DESCRIPTION
**Pull request by JackBoosY**
This PR changes depends on the #9599 result.

Current failure:

- [ ] open62541: build failure:No module named six
- [ ] ibb2: does not support osx
- [ ] tfhe: does not support osx
- [ ] freeglut: missing opengl
- [ ] wpilib:  does not support osx
- [ ] glib: configure error: cannot run C compiled programs.
- [X] libguarded: hash not correct
- [ ] akal:i build failure: undeclared identifier 'htobe16'
- [ ] qhull: build failure: can't open output file for writing: qhull, errno=21 for architecture x86_64
- [x] cppmicroservices: cannot open wchar.h
- [ ] libaaplus: build failure: unrecognized symbol noexcept
- [ ] libmagic missing dependency LIBTOOL
- [ ] bullet3 build failure: argument value 10880 is outside the valid range [0, 255] [-Wargument-outside-range]
- [ ] pbc: build failure:  libtoolize and glibtoolize not found
- [ ] sfgui path _/System/Library/Frameworks/CoreFoundation.framework/Headers_ not found

### CODE REVIEW

**Comment by JackBoosY** [comment]
@vicroms Could you install opengl, Libtool, libtoolize and glibtoolize to OSX pipeline machines?

Thanks.

**Comment by vicroms** [comment]
@ubsan please take a look at the regression on the `vcpkg-osx-pr` pipeline

**Comment by ubsan** [comment]
Akali will (I am fairly certain) be fixed by #9603, sfgui is fixed by #9625, and bullet3 needs an update.

**Comment by JackBoosY** [comment]
Related: #9617.

**Comment by SeekingMeaning** [comment]
See #9513 regarding wpilib:

> Only supports linux and windows. macOS is not supported, and never will be.

**Comment by PhoebeHui** [comment]
pbc should be solved by https://github.com/microsoft/vcpkg/pull/9281

**Pull request merged**
