### PR TITLE
[VTK] fix cmake patches not recycling targets already defined

### LINKED ISSUE #20038: Unable to use find_package(OpenCV REQUIRED) and find_package(VTK REQUIRED) at the same time
**Environment**
- OS: x64-linux
- Compiler: gcc 9.3.0

**To Reproduce**
CMakeLists.txt
```
set(CMAKE_TOOLCHAIN_FILE $ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake)

cmake_minimum_required(VERSION 3.20)

project(example)

find_package(OpenCV REQUIRED)
find_package(VTK REQUIRED)
```

Simply run `mkdir build & cd build & cmake ..` shows

```
-- Found TIFF: /home/jasjuang/vcpkg/installed/x64-linux/lib/libtiff.a (found version "4.3.0")  
-- Found TIFF: /home/jasjuang/vcpkg/installed/x64-linux/lib/libtiff.a;/home/jasjuang/vcpkg/installed/x64-linux/lib/liblzma.a;/home/jasjuang/vcpkg/installed/x64-linux/lib/libjpeg.a;/home/jasjuang/vcpkg/installed/x64-linux/lib/libz.a;m (found version "4.3.0")  
-- Found LibXml2: /home/jasjuang/vcpkg/installed/x64-linux/lib/libxml2.a (found version "2.9.12") 
CMake Error at /home/jasjuang/vcpkg/scripts/buildsystems/vcpkg.cmake:574 (_add_library):
  _add_library cannot create ALIAS target "hdf5::hdf5" because another target
  with the same name already exists.
Call Stack (most recent call first):
  /home/jasjuang/vcpkg/installed/x64-linux/share/vtk/patches/99/FindHDF5.cmake:8 (add_library)
  /home/jasjuang/vcpkg/installed/x64-linux/share/hdf5/vcpkg-cmake-wrapper.cmake:17 (_find_package)
  /home/jasjuang/vcpkg/scripts/buildsystems/vcpkg.cmake:738 (include)
  /home/jasjuang/vcpkg/installed/x64-linux/share/vtk/VTK-vtk-module-find-packages.cmake:303 (find_package)
  /home/jasjuang/vcpkg/installed/x64-linux/share/vtk/vtk-config.cmake:136 (include)
  /home/jasjuang/vcpkg/scripts/buildsystems/vcpkg.cmake:784 (_find_package)
  CMakeLists.txt:8 (find_package)
```

**Expected behavior**
OpenCV and VTK should be able to co-exist.

### PR DESCRIPTION
**Pull request by cenit**
- #### What does your PR fix?  
  Fixes #20038 

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all, Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

### CODE REVIEW

**Comment by cenit** [comment]
vtk is a cascade failure and so not tested in CI WTF!

but apart from it, again and again and again and again opencv is not tested anymore in CI (has a dependency on vtk and that's why i noticed it) due to a PR merging from master breaking something somewhere and NOBODY really even noticed it??????
SINCE WHEN???
Again, sorry for the rant, but this is happening TOO OFTEN for me to not be disappointed.

tagging everyone, something has to happen for CI to be considered **useful** again by me. Something very easy, again please just check if the cascade number of ports is increased by a PR and make it fail if so.

@ras0219 @ras0219-msft @strega-nil @strega-nil-ms @BillyONeal @vicroms @PhoebeHui @JackBoosY @NancyLi1013

**Comment by cenit** [comment]
#19945 and here it is

this pr just skipped some ports in CI, without any consideration of the "cascade" consequences!

**Comment by dg0yt** [comment]
> Again, sorry for the rant, but this is happening TOO OFTEN for me to not be disappointed.

#19259 was meant to help, in particular with these cases in mind. But hey, it already has :+1: from @cenit...

**Review by strega-nil-ms — APPROVED** [review]

**Comment by BillyONeal** [comment]
This is really a case of the maintainers being stuck with a bunch of bad options. qt5-activeqt and qt5-declarative breaking each other has been a long standing issue, and eventually we got a PR build situation uncovering the real problem: that the qt ports are trying to guess when they will stomp on each other, which makes the results path-dependent. This is #19922 , and it caused all PRs not directly touching any qt parts to fail. The solutions enumerated in #19922 do not look like "can be done quickly" solutions. So our options were:

* disable qt5-activeqt (and by extension, its cone of destruction)
* allow no other port to be updated in vcpkg until qt5 is fixed

and given that we already had let many contributors wait for weeks, we chose the former. I don't believe we will ever truly end up in a situation where we wouldn't have made a similar decision; there are actions we want to take resulting from this feedback but none would really change the outcome in this particular case, although it would in other cases.

Actions that we are going to take from this:

* We have fast tracked review of @dg0yt's PR #19259 which would have printed the cone of destruction in this example. Thank you @dg0yt for your contribution! That would have let you know quickly here that this PR edits a port that is currently a cascaded failure.
* @ras0219 / @ras0219-msft has signed up to fix qt in a less correct way than described in #19922 (it will waste disk space) but which will restore the unique port attribution rule.
* We are going to add logging of the count of "cascades at the top" -- those that result from `ci.baseline.txt` and `"supports"` -- and keep track of this as an important metric in CI.
* We are going to add validation for the preceeding number and fail PRs if the number of cascades change. Then at least `git blame` will find PRs that had to make significant edits here.

Actions we want to do in the future:

* We would like all cascades to be in `ci.baseline.txt` rather than locking to a number, but this would require better understanding of `ci.baseline.txt` inside `vcpkg.exe` than we have right now, and we want to roll something out which improves the situation ASAP.

We apologize that the situation has left you with a bad experience and hope you can bear with us trying to make the situation better.

**Review by JackBoosY — APPROVED** [review]

**Comment by jasjuang** [comment]
I also further discovered that similar fixes will also need to be applied to LZ4 and PEGTL. See below CMakeLists.txt with two `find_package(VTK REQUIRED)` that will trigger it.

```
set(CMAKE_TOOLCHAIN_FILE $ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake)

cmake_minimum_required(VERSION 3.20)

project(example)

find_package(VTK REQUIRED)
find_package(VTK REQUIRED)
```

Below error will show up:

```
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19043.
-- Searching for PEGTL
-- Searching for PEGTL - found target taocpp::pegtl
-- Found LibXml2: C:/dev/vcpkg/installed/x64-windows/debug/lib/libxml2.lib (found version "2.9.12")
-- Found Eigen3: C:/dev/vcpkg/installed/x64-windows/include/eigen3 (found version "3.3.9")
-- Found TIFF: optimized;C:/dev/vcpkg/installed/x64-windows/lib/tiff.lib;debug;C:/dev/vcpkg/installed/x64-windows/debug/lib/tiffd.lib (found version "4.3.0")
CMake Error at C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:574 (_add_library):
  _add_library cannot create ALIAS target "hdf5::hdf5" because another target
  with the same name already exists.
Call Stack (most recent call first):
  C:/dev/vcpkg/installed/x64-windows/share/vtk/patches/99/FindHDF5.cmake:5 (add_library)
  C:/dev/vcpkg/installed/x64-windows/share/hdf5/vcpkg-cmake-wrapper.cmake:17 (_find_package)
  C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:738 (include)
  C:/dev/vcpkg/installed/x64-windows/share/vtk/VTK-vtk-module-find-packages.cmake:256 (find_package)
  C:/dev/vcpkg/installed/x64-windows/share/vtk/vtk-config.cmake:136 (include)
  C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:784 (_find_package)
  CMakeLists.txt:37 (find_package)


CMake Error at C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:574 (_add_library):
  _add_library cannot create ALIAS target "hdf5::hdf5_hl" because another
  target with the same name already exists.
Call Stack (most recent call first):
  C:/dev/vcpkg/installed/x64-windows/share/vtk/patches/99/FindHDF5.cmake:14 (add_library)
  C:/dev/vcpkg/installed/x64-windows/share/hdf5/vcpkg-cmake-wrapper.cmake:17 (_find_package)
  C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:738 (include)
  C:/dev/vcpkg/installed/x64-windows/share/vtk/VTK-vtk-module-find-packages.cmake:256 (find_package)
  C:/dev/vcpkg/installed/x64-windows/share/vtk/vtk-config.cmake:136 (include)
  C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:784 (_find_package)
  CMakeLists.txt:37 (find_package)


-- Searching for PEGTL
-- Searching for PEGTL - found target taocpp::pegtl
CMake Error at C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:574 (_add_library):
  _add_library cannot create ALIAS target "PEGTL::PEGTL" because another
  target with the same name already exists.
Call Stack (most recent call first):
  C:/dev/vcpkg/installed/x64-windows/share/vtk/FindPEGTL.cmake:27 (add_library)
  C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:784 (_find_package)
  C:/dev/vcpkg/installed/x64-windows/share/vtk/VTK-vtk-module-find-packages.cmake:491 (find_package)
  C:/dev/vcpkg/installed/x64-windows/share/vtk/vtk-config.cmake:136 (include)
  C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:784 (_find_package)
  CMakeLists.txt:37 (find_package)


-- Found LibXml2: C:/dev/vcpkg/installed/x64-windows/debug/lib/libxml2.lib (found version "2.9.12")
CMake Error at C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:574 (_add_library):
  _add_library cannot create ALIAS target "LZ4::LZ4" because another target
  with the same name already exists.
Call Stack (most recent call first):
  C:/dev/vcpkg/installed/x64-windows/share/vtk/FindLZ4.cmake:3 (add_library)
  C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:784 (_find_package)
  C:/dev/vcpkg/installed/x64-windows/share/vtk/VTK-vtk-module-find-packages.cmake:1055 (find_package)
  C:/dev/vcpkg/installed/x64-windows/share/vtk/vtk-config.cmake:136 (include)
  C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:784 (_find_package)
  CMakeLists.txt:37 (find_package)


-- Found TIFF: optimized;C:/dev/vcpkg/installed/x64-windows/lib/tiff.lib;debug;C:/dev/vcpkg/installed/x64-windows/debug/lib/tiffd.lib;optimized;C:/dev/vcpkg/installed/x64-windows/lib/lzma.lib;debug;C:/dev/vcpkg/installed/x64-windows/debug/lib/lzmad.lib;optimized;C:/dev/vcpkg/installed/x64-windows/lib/jpeg.lib;debug;C:/dev/vcpkg/installed/x64-windows/debug/lib/jpegd.lib;optimized;C:/dev/vcpkg/installed/x64-windows/lib/zlib.lib;debug;C:/dev/vcpkg/installed/x64-windows/debug/lib/zlibd.lib (found version "4.3.0")
-- Configuring incomplete, errors occurred!
See also "C:/Users/jasju/Desktop/test/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/jasju/Desktop/test/build/CMakeFiles/CMakeError.log".
```

**Review by BillyONeal — APPROVED** [review]

**Comment by BillyONeal** [comment]
@cenit There are plenty of signoffs now, do you want to land this now or do you want to wait until the qt5-activeqt situation is resolved?

**Comment by cenit** [comment]
i did the fix in this PR because tagged by @JackBoosY in the issue but i am not the author of the original broken patches nor because i was hit by the problem. 
@jasjuang just uncovered another similarly broken patch also in vtk, let me just fix that too because it really belongs to this PR (i'll do that asap).
Not a problem for me to wait for a proper fix. Maybe @jasjuang can use vcpkg from this PR in the meantime and verify that the issue is properly solved?

**Comment by jasjuang** [comment]
@cenit I can confirm the current PR solves the 

```
find_package(OpenCV REQUIRED) 
find_package(VTK REQUIRED) 
```

scenario.

**Comment by cenit** [comment]
@jasjuang if you have time, please check again, it should contains fixes for all your reported problems

**Comment by jasjuang** [comment]
@cenit I can confirm that your latest push solves the

```
find_package(VTK REQUIRED) 
find_package(VTK REQUIRED) 
```

scenario. Thanks.

**Comment by BillyONeal** [comment]
FYI, the "cascades" enforcement enumerated above is in progress at: https://github.com/microsoft/vcpkg/pull/20140

**Comment by BillyONeal** [comment]
Thanks for your fix!

**Comment by BillyONeal** [comment]
Count enforcement of "cascade" is landed.

**Comment by BillyONeal** [comment]
Unfortunately we were forced to back out enforcement of "cascade" due to "stealth merge conflicts". See further discussion in https://github.com/microsoft/vcpkg/discussions/20180

**Pull request merged**
