### PR TITLE
[crashpad] Fix build on linux

### PR DESCRIPTION
**Pull request by MarekMaslanka**
Fetch required lss package on linux

**Describe the pull request**

- What does your PR fix?
Fix building on linux

- Which triplets are supported/not supported? Have you updated the CI baseline?
linux

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

### CODE REVIEW

**Comment by LilyWangL** [comment]
@MarekMaslanka Could you sign the cla?

**Comment by LilyWangL** [comment]
@MarekMaslanka `crashpad` build failed on Linux, could you continue to fix it? You can download the error log from: https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/44538/artifacts?artifactName=failure%20logs%20for%20x64-linux&api-version=6.0&%24format=zip

**Comment by LilyWangL** [comment]
Pinging @MarekMaslanka for response.

**Comment by MarekMaslanka** [comment]
Sorry, I'm very busy last time and forgot about this issue. I'll look at this on weekend. Meanwhile, can you tell me what is the proper way to fetch clang++ in vcpkg-fasion way?

**Comment by LilyWangL** [comment]
You could install `llvm` on VCPKG.

**Comment by MarekMaslanka** [comment]
Is any other way than adding llvm to "Build-Depends" in CONTROL file?

**Comment by NancyLi1013** [comment]
`/bin/sh: 1: clang++: not found`

Need to install `clang `on Linux machine. `sudo apt-get install clang`

**Review by NancyLi1013 — APPROVED** [review]

**Comment by BillyONeal** [comment]
The compiler used is defined by the triplet; a port should not be overriding trying to use another compiler. Dropping `vm-update`.

**Comment by BillyONeal** [comment]
If you want to do this in a way in keeping with the triplet system, you would need to edit the default Linux triplets to add something like:

```
if (PORT STREQUAL "crashpad")
set(VCPKG_C_COMPILER "clang")
set(VCPKG_CXX_COMPILER "clang++")
endif()
```

It's likely that folks who want to use crashpad themselves might be broken though since the existing contract is that the installed tree can be used with whatever the end user wants.

It would be nice too if it could be easily detected that clang is not installed and emit a help message here but I'm not sure how involved proving that the user has a working clang++ is. Perhaps the warning could be emitted unconditionally?

**Comment by NancyLi1013** [comment]
@MarekMaslanka 
Could you please address the above suggestion?

**Comment by omartijn** [comment]
Wouldn't a decent solution be to create a triplet, that sets the compiler to clang on linux and then have the crashpad port set so that it only accepts that specific triplet?

The downside is that people need to manually specify that triplet, while right now with this PR it "just works" if your default compiler is set to clang - which it is on my system.

**Comment by NancyLi1013** [comment]
@MarekMaslanka 
Is work still being done for this PR?

**Comment by NancyLi1013** [comment]
Thanks for the PR; we're closing this for now since there's been no response. If you'd like to continue working on it, please reopen and ping us!

**Pull request closed without merging**
