### PR TITLE
[libpng] Fix libpng for android

### PR DESCRIPTION
**Pull request by m-kuhn**
**Describe the problem**

`check` is only a valid value for arm architectures.

On `arm64` this errors with

```
CMake Error at CMakeLists.txt:108 (message):
  PNG_ARM_NEON must be one of [on;off]
```

**Describe the pull request**

Only use `check` on `arm`

### CODE REVIEW

**Comment by Cheney-W** [comment]
The failures on CI are known and they are being fixed.

> The default is on (with neon) which is the only configuration accepted by the latest ndk r25 which has dropped support for non neon devices.

Is this only implemented on top of the latest? So if it's not the latest, will your changes cause other errors?

**Comment by m-kuhn** [comment]
Digging deeper... The upstream logic actually has a dependency on the target architecture:

https://github.com/glennrp/libpng/blob/libpng16/CMakeLists.txt#L95-L104

This should be updated to switch to `check` if `VCPKG_TARGET_ARCHITECTURE STREQUAL "arm"`.

**Comment by dg0yt** [comment]
FTR a similar PR was reviewed in #27936.

**Comment by m-kuhn** [comment]
Should be fine now

**Comment by JavierMatosD** [comment]
Thank you!

**Pull request merged**
