### PR TITLE
[qt-advanced-docking-system] Upgrade to Qt6

### PR DESCRIPTION
**Pull request by Neumann-A**

### CODE REVIEW

**Review by JonLiu1993 — APPROVED** [review]

**Comment by dg0yt** [comment]
Please fix the PR title before merge.

**Comment by BillyONeal** [comment]
Thank you!

**Comment by FelixBer** [comment]
This hardcodes the Qt dependency to Qt6, wouldnt it be better to leave this up to the user? As it's really more of an extension to Qt and supports both Qt5 and Qt6.

**Comment by BillyONeal** [comment]
@FelixBer There is not presently a way to "leave that up to the user". `vcpkg install qt-advanced-docking-system` has to pick which one will get used.

We are aware that there are needs to better express "alternatives" but don't currently have a good way of modeling that.

**Pull request merged**
