### PR TITLE
[vcpkg ci pipeline] suggest vcpkg_*_cmake -> vcpkg_cmake_* migration

### PR DESCRIPTION
**Pull request by autoantwort**

### CODE REVIEW

**Review by BillyONeal — APPROVED** [review]

**Comment by autoantwort** [comment]
I have now moved the text into the _Details_ so that the message is not so long. The PR is now ready.

**Review by PhoebeHui — APPROVED** [review]
LGTM, thanks for the PR!

**Comment by BillyONeal** [comment]
>funktions

It's getting funky in here! :D

**Comment by Neumann-A** [comment]
> It's getting funky in here! :D

That is just a german language party ;) (https://dict.leo.org/german-english/function)

**Comment by BillyONeal** [comment]
> > It's getting funky in here! :D
> 
> That is just a german language party ;) (https://dict.leo.org/german-english/function)

🎉🎉🎉🎉🎉🎉🎉🎈🎈🎈🎈🎈🎈🥳🥳🥳🥳🥳🥳🎈🎈🎈🎈🎈🎉🎉🎉🎉🎉

**Review by ras0219-msft — APPROVED** [review]

**Comment by BillyONeal** [comment]
Dropping reviewed: This is good to go but I'm going to make sure other maintainers are OK with it (~11AM pacific tomorrow time)

**Comment by dg0yt** [comment]
This should perhaps be backed by adding the deprecated functions to https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#avoid-deprecated-helper-functions.

**Comment by BillyONeal** [comment]
Thanks for your help!

**Comment by BillyONeal** [comment]
> This should perhaps be backed by adding the deprecated functions to https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#avoid-deprecated-helper-functions.

I agree. @autoantwort I added this to my pile for today but if you get to it before me that would be great.

**Comment by wrobelda** [comment]
I just saw this in action [here](#19756) and it seems to look at some older commits in the PR, because its recommendation is off?

**Comment by BillyONeal** [comment]
@autoantwort Can you take a look at @wrobelda 's report?

**Comment by BillyONeal** [comment]
Another example where it did the wrong thing: https://github.com/microsoft/vcpkg/pull/20207

**Comment by autoantwort** [comment]
I will look at it now

**Comment by autoantwort** [comment]
Fix in #20218

**Pull request merged**
