### PR TITLE
[curl] Update to 8.7.1

### LINKED ISSUE #37770: [curl] update to 8.7.1
### Library name

curl

### New version number

8.7.1

### Other information that may be useful (release notes, etc...)

Please update the curl port from 8.6.0 to 8.7.1.  This latest version was released today.  It resolves 4 CVEs that are present in curl 8.6.0: see the first four CVEs in the [CURL CVEs](https://curl.se/docs/security.html) list.

This new version also has some new features and dozens of bugfixes; see the [changelog](https://curl.se/changes.html).

### PR DESCRIPTION
**Pull request by dg0yt**
Resolves https://github.com/microsoft/vcpkg/issues/37770.

### CODE REVIEW

**Review by BillyONeal — DISMISSED** [review]

**Comment by talregev** [comment]
from the ci:
```
Installing 566/583 qtwebengine[core,default-features,geolocation,spellchecker,webchannel]:x64-windows@6.6.1#5...
Building qtwebengine[core,default-features,geolocation,spellchecker,webchannel]:x64-windows@6.6.1#5...
-- Setting up python virtual environment...
-- Installing python packages: html5lib
-- Setting up python virtual environment... finished.
-- Downloading https://download.qt.io/archive/qt/6.6/6.6.1/submodules/qtwebengine-everywhere-src-6.6.1.tar.xz;https://mirrors.ocf.berkeley.edu/qt/archive/qt/6.6/6.6.1/submodules/qtwebengine-everywhere-src-6.6.1.tar.xz -> qtwebengine-everywhere-src-6.6.1.tar.xz...
-- Extracting source D:/downloads/qtwebengine-everywhere-src-6.6.1.tar.xz
-- Applying patch clang-cl.patch
-- Applying patch msvc-template.patch
-- Using source at D:/b/qtwebengine/src/here-src-6-4f617c9365.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
-- Building x64-windows-rel
##[warning]Free memory is lower than 5%; Currently used: 95.28%
##[warning]Free memory is lower than 5%; Currently used: 95.30%
##[warning]Free memory is lower than 5%; Currently used: 95.88%
```

**Comment by dg0yt** [comment]
@talregev That's related to the qtwebengine monster, not to the curl beauty.

**Comment by talregev** [comment]
I know, I just want to point out this in case the ci will fail again, and we don't have a log to see what happens.
So It is a general note for the ci that is now found on its limit.

**Comment by BillyONeal** [comment]
https://github.com/curl/curl/pull/13219#issuecomment-2024872779

**Review by BillyONeal — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the update!

**Comment by MonicaLiu0311** [comment]
Features `brotli,c-ares,core,http2,idn,idn2,ldap,mbedtls,non-http,openssl,schannel,ssh,ssl,sspi,tool,websockets,winidn,winldap,winssl,zstd` are tested successfully in the following triplets:
```
x86-windows
x64-windows
x64-windows-static
```

**Pull request merged**
