### PR TITLE
[fcl] Update to 0.6.0

### PR DESCRIPTION
**Pull request by NancyLi1013**
Update to 0.6.0 and remove patches.

Related issue #10013 

Note: No feature needs to test.

### CODE REVIEW

**Comment by PhoebeHui** [comment]
fcl failed on CI, could you take a look?

**Comment by NancyLi1013** [comment]
The failures on `fcl `are like this:
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
C:/vsts/_work/4/s/buildtrees/fcl/src/11f588cb82-a00892d54e/src/EIGEN3_INCLUDE_DIR
   used as include directory in directory C:/vsts/_work/4/s/buildtrees/fcl/src/11f588cb82-a00892d54e/src
```
I checked `fcl `source code and didn't find `EIGEN3_INCLUDE_DIR`. I also cannot reproduce this issue on my local. So I am not sure what's happening on CI.

**Review by PhoebeHui — APPROVED** [review]

**Comment by strega-nil** [comment]
This is awesome, thanks @NancyLi1013 :)

**Pull request merged**
