### PR TITLE
[DPP] Adding new port

### PR DESCRIPTION
**Pull request by ghost**
**Describe the pull request**

- #### What does your PR fix?  
Adds the DPP library into the vcpkg ports

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
- Yes, afaik

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
I am still working on this PR

### CODE REVIEW

**Comment by InfRandomness** [comment]
Fixes #21084

**Comment by JonLiu1993** [comment]
@InfRandomness ,Thanks for your pr, could you please take a look:
https://dev.azure.com/vcpkg/public/_build/results?buildId=62227&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by InfRandomness** [comment]
I do not know how to fix the issue. See https://github.com/microsoft/vcpkg/issues/21084.

**Comment by InfRandomness** [comment]
Stopped using vcpkg for conan.

**Pull request closed without merging**
