### PR TITLE
[detect_compiler] Improve error messages

### PR DESCRIPTION
**Pull request by JackBoosY**
For a long period of time, users have long wondered which Visual Studio components vcpkg needs in Windows:
```
CMake Error at C:/Users/James/code/ext/vcpkg/downloads/tools/cmake-3.21.1-windows/cmake-3.21.1-windows-i386/share/cmake-3.21/Modules/CMakeTestCCompiler.cmake:69 (message):
  The C compiler

    "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.30.30705/bin/Hostx64/x64/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/James/code/ext/vcpkg/buildtrees/bzip2/x64-windows-rel/CMakeFiles/CMakeTmp
    
    Run Build Command(s):C:/Users/James/code/ext/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe cmTC_3abad && [1/2] Building C object CMakeFiles\cmTC_3abad.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_3abad.exe
    FAILED: cmTC_3abad.exe 
    cmd.exe /C "cd . && C:\Users\James\code\ext\vcpkg\downloads\tools\cmake-3.21.1-windows\cmake-3.21.1-windows-i386\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_3abad.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests  -- C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1430~1.307\bin\Hostx64\x64\link.exe /nologo CMakeFiles\cmTC_3abad.dir\testCCompiler.c.obj  /out:cmTC_3abad.exe /implib:cmTC_3abad.lib /pdb:cmTC_3abad.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /fo CMakeFiles\cmTC_3abad.dir/manifest.res CMakeFiles\cmTC_3abad.dir/manifest.rc" failed (exit code 0) with the following output:
    The system cannot find the file specified
    ninja: build stopped: subcommand failed.
    

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

```
This PR aims to improve these error messages so that users can self-check the Visual Studio components that need to be installed:
```
  Failed to detect the MSVC C compiler.

  Please ensure you've installed the following Visual Studio Components using
  Visual Studio Installer:

    - Windows Universal C Runtime
    - C++ Build Tools core features
    - Visual Studio Build tools:
      * VC++ 2017 version ... latest v141 tools (for Visual Studio 2017)
      * MSVC v142 - VS 2019 C++ x64/x86 build tools (for Visual Studio 2019)
      * MSVC v143 - VS 2022 C++ x64/x86 build tools (for Visual Studio 2022)
    - MSBuild
    - Windows SDK
    - English language Pack


  For ARM / ARM64 or UWP triplet, please also installed:

    - Visual Studio Build tools for ARM:
      * VC++ 2017 version ... Libs for Spectre (ARM) (for Visual Studio 2017)
      * MSVC v142 - VS 2019 C++ ARM build tools (for Visual Studio 2019)
      * MSVC v143 - VS 2022 C++ ARM build tools (for Visual Studio 2022)
    - Visual Studio Build tools for ARM64:
      * VC++ 2017 version ... Libs for Spectre (ARM64) (for Visual Studio 2017)
      * MSVC v142 - VS 2019 C++ ARM64 build tools (for Visual Studio 2019)
      * MSVC v143 - VS 2022 C++ ARM64 build tools (for Visual Studio 2022)
    - Visual Studio Build tools for UWP:
      * Visual C++ runtime for UWP (for Visual Studio 2017)
      * C++ Universal Windows Platform support for v142 build tools (for Visual Studio 2019)
      * C++ Universal Windows Platform support for v143 build tools (for Visual Studio 2022)

```

Related: https://github.com/microsoft/vcpkg/issues/21580 https://github.com/microsoft/vcpkg/issues/22193 etc.

### CODE REVIEW

**Comment by JackBoosY** [comment]
I found that `detect_compiler` is not built first for every build. Maybe we should add the same process to `vcpkg_execute_build_process`?

**Comment by strega-nil-ms** [comment]
Is it possible to put this check into vcpkg itself? It seems like we could check for all of these components when we call vswhere and warn the user.

**Comment by JackBoosY** [comment]
@strega-nil-ms It seems that wswhere couldn't get whether the English language pack installed.

**Comment by JackBoosY** [comment]
The required product id:
```
C++:
Microsoft.VisualStudio.Workload.MSBuildTools
Microsoft.VisualStudio.Workload.VCTools
    *Microsoft.VisualStudio.Component.VC.Tools.x86.x64 (for 2017 or later)
    *Microsoft.VisualStudio.Component.VC.140 (for 2015)
Microsoft.VisualStudio.Component.Windows10SDK

ARM/ARM64:
Microsoft.VisualStudio.Component.VC.Tools.arm
Microsoft.VisualStudio.Component.VC.Tools.arm64
UWP:
Microsoft.VisualStudio.ComponentGroup.UWP.VC
Microsoft.VisualStudio.Workload.Universal
```

**Comment by strega-nil-ms** [comment]
@JackBoosY we must be able to, since otherwise we wouldn't print an error if we couldn't find the english language pack.

**Comment by PhoebeHui** [comment]
@JackBoosY, see https://github.com/microsoft/vcpkg-tool/blob/main/src/vcpkg/visualstudio.cpp#L26

**Comment by JackBoosY** [comment]
> @JackBoosY, see https://github.com/microsoft/vcpkg-tool/blob/main/src/vcpkg/visualstudio.cpp#L26

```cpp
        if (!excluded_toolsets.empty())
        {
            ret.append(msg::format(msgVSExcludedByLanguagePack));
            ret.appendnl();
            for (const Toolset& toolset : excluded_toolsets)
            {
                ret.append(msg::LocalizedString::from_string_unchecked(
                    Strings::concat("    ", toolset.visual_studio_root_path, '\n')));
            }
        }
```
I don't believe that the VS toolset is related to the English language pack.

**Comment by JackBoosY** [comment]
Will continue this in https://github.com/microsoft/vcpkg/pull/22214

**Pull request closed without merging**
