### PR TITLE
[vcpkg] Use /Zi when building dynamic libraries

### PR DESCRIPTION
**Pull request by Osyotr**
Consider scenario when you are building huge dynamic library which itself consist of multiple huge static libraries. With /Z7 you may end up with LNK1248. I've came across this error when building QtWebKit. Quick search revealed that /Z7 is used for static libraries so that they contain debug info, but with dynamic libraries it is useless and even wasteful.

### CODE REVIEW

**Comment by Osyotr** [comment]
Well, I think this is not going to work :(
Any suggestions on how to override /Z7 for a specific port?

**Comment by BillyONeal** [comment]
The usual issue with `/Zi` for static libs is that you have to establish a process for provenance etc. of the DLL which usually gets a nondescriptive name like `vc141.pdb` or similar, which in practice many ports would stomp on. There are also problems caused by contention on `mspdbsrv` in conjunction with attempting to isolate ports from each other.

Any change to use `/Zi` will need at least:

* Some form of design description of how the DLL name is set in such a way that ports won't stomp on each other; note that this is not the default.
* Some form of write-up on how downstream build systems (e.g. cmake using `scripts/buildsystems/vcpkg.cmake` or the msbuild integration or what have you) are supposed to get the right PDBs and make them available for their customers
* (probably) Some writeup / mechanism to avoid having ports affected by an already running `mspdbsrv`.

**Comment by Osyotr** [comment]
@BillyONeal thank you very much for explanation. Closing this PR with hope to reopen it in future.

**Comment by BillyONeal** [comment]
Sorry I wrote "DLL" in several places where I meant "PDB" above, I fixed it.

**Pull request closed without merging**
