### PR TITLE
[graphviz] Update to 10.0.1

### PR DESCRIPTION
**Pull request by dg0yt**
Some libs follow vcpkg library linkage now also on windows.

### CODE REVIEW

**Comment by jimwang118** [comment]
Usage test pass with following triplets:

```
x86-windows
x64-windows
```

**Comment by BillyONeal** [comment]
Thanks for the update!

**Comment by dg0yt** [comment]
Possible, but not seen in PR CI. And I built `graphviz[tools]:x64-linux` locally.

**Comment by dg0yt** [comment]
`gvRenderJobs` is defined in `common/emit.c`
which is in object library `common_obj`
which is integrated as
~~~cmake
target_link_libraries(gvc PRIVATE
  $<TARGET_OBJECTS:common_obj>
  $<TARGET_OBJECTS:pack_obj>
)
~~~
but maybe it is not so private with 
~~~
GVC_API int gvRenderJobs(GVC_t *gvc, graph_t *g);
~~~
in `lib/gvc/gvc.h`.

**Comment by dg0yt** [comment]
Should I care?
~~~
$ ./vcpkg depend-info paraview[*]:x64-windows 2>&1 | grep graphviz
$

**Pull request merged**
