### PR TITLE
[libmariadb] upgrade to 2.3.2

### PR DESCRIPTION
**Pull request by sdcb**
1. upgrade package to 2.3.2
2. enable static build support
~~3. do not block with libmysql~~

### CODE REVIEW

**Comment by alexkaratarakis** [comment]
Since `libmariadb` and `libmysql` are interchangable, shouldn't we move the headers to: mysql/mysql.h as well?

**Comment by sdcb** [comment]
@alexkaratarakis It's make sense but I originally expected installing libmariadb and libmysql at same time without blocking each other. 

If move libmariadb header to mysql/mysql.h as well, we need also rename libmariadb.lib to libmysql.lib since many other source would expect libmysql.lib instead of libmariadb, and we need to bring the blocking libmysql/libmariadb code back since they really blocks each other.

If it's everyone expects, I'll create a another PR to fix it.

**Comment by ras0219-msft** [comment]
Considering how `libmariadb` is used in other distributions (as a drop-in system wide replacement for `libmysql`), it seems _intended_ that the headers collide. You should be able to pick one of them and have all the ports use the one you picked.

If you could update the PR to move the header (and restore the conflict detection code), that would be great.

**Comment by sdcb** [comment]
@ras0219-msft that's make sense, I'll update the PR.

**Comment by sdcb** [comment]
@ras0219-msft updated.

**Comment by ras0219-msft** [comment]
Thanks for the quick turnaround 💯

**Pull request merged**
