### PR TITLE
[crashpad] Use native path for zlib

### LINKED ISSUE #28358: [crashpad/vcpkg-tool-gn] build failure
Package: crashpad[core]:x64-windows -> 2022-09-05#1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.33.31630.0
- vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
  vcpkg-scripts version: 06071749b 2022-12-14 (32 hours ago)

**To Reproduce**

`vcpkg install `

**Failure logs**

```
-- Note: crashpad only supports static library linkage. Building static library.
-- Using cached C:/vcpkg/downloads/crashpad-261679b3d2f3336d8531ed38e110254c3e2d1c10.tar.gz
-- Cleaning sources at C:/vcpkg/buildtrees/crashpad/src/4c3e2d1c10-1c4f0a1e28.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/crashpad-261679b3d2f3336d8531ed38e110254c3e2d1c10.tar.gz
-- Using source at C:/vcpkg/buildtrees/crashpad/src/4c3e2d1c10-1c4f0a1e28.clean
-- Using cached C:/vcpkg/downloads/crashpad-5654edb4225bcad13901155c819febb5748e502b.tar.gz
-- Extracting source C:/vcpkg/downloads/crashpad-5654edb4225bcad13901155c819febb5748e502b.tar.gz
-- Using source at C:/vcpkg/buildtrees/crashpad/src/b5748e502b-44507d16bb.clean
-- Found external ninja('1.10.2').
-- Getting CMake variables for x64-windows
-- Generating build (x64-windows-dbg)...
-- Generating build (x64-windows-rel)...
-- Building (x64-windows-dbg)...
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:131 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -C C:/vcpkg/buildtrees/crashpad/x64-windows-dbg client client:common util third_party/mini_chromium/mini_chromium/base handler:crashpad_handler
    Working Directory: C:/vcpkg/buildtrees/crashpad/src/4c3e2d1c10-1c4f0a1e28.clean
    See logs for more information:
      C:\vcpkg\buildtrees\crashpad\build-x64-windows-dbg-out.log
      C:\vcpkg\buildtrees\crashpad\build-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_ninja.cmake:3 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_build_ninja.cmake:24 (z_vcpkg_build_ninja_build)
  scripts/cmake/vcpkg_install_gn.cmake:95 (vcpkg_build_ninja)
  buildtrees/versioning_/versions/crashpad/f7ead3d493577856543add942c07776fe60ded9e/portfile.cmake:99 (vcpkg_install_gn)
  scripts/ports.cmake:147 (include)



```

<details><summary>C:\vcpkg\buildtrees\crashpad\build-x64-windows-dbg-out.log</summary>

```
ninja: Entering directory `C:/vcpkg/buildtrees/crashpad/x64-windows-dbg'
```

</details>

<details><summary>C:\vcpkg\buildtrees\crashpad\build-x64-windows-dbg-err.log</summary>

```
ninja: error: FindFirstFileExA(../../../../../e:/vtslink/client/build-debug/vcpkg_installed/x64-windows/debug/lib): 文件名、目录名或卷标语法不正确。


```

</details>

**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "name": "vts-link-client",
  "version-string": "0.0.1",
  "dependencies": [
    "kcp",
    "libdatachannel",
    "brotli",
    "libyuv",
    "protobuf",
    "concurrentqueue",
    "crashpad",
    {
      "name": "ffmpeg",
      "default-features": true,
      "features": [
        "nvcodec",
        "qsv",
        "x264"
      ]
    }
  ],
  "overrides": [
    {
      "name": "openssl",
      "version-string": "1.1.1m#2"
    }
  ],
  "builtin-baseline": "06071749ba78c76f425765106a94b1832a2ae06e"
}

```

</details>

### PR DESCRIPTION
**Pull request by dg0yt**
- #### What does your PR fix?
  Fixes #28358.

### CODE REVIEW

**Comment by MonicaLiu0311** [comment]
Although the CI test passed, I still reported an error when I installed `x86-windows` locally:
(`x64-windows` and `x64-windows-static` installed successfully)

```
-- Building (x86-windows-dbg)...
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:131 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -C E:/crashpad/buildtrees/crashpad/x86-windows-dbg client client:common util third_party/mini_chromium/mini_chromium/base handler:crashpad_handler
    Working Directory: E:/crashpad/buildtrees/crashpad/src/4c3e2d1c10-076c03c4e9.clean
    See logs for more information:
      E:\crashpad\buildtrees\crashpad\build-x86-windows-dbg-out.log
```

[build-x86-windows-dbg-out.log.txt](https://github.com/microsoft/vcpkg/files/10294085/build-x86-windows-dbg-out.log.txt)

**Comment by cnSchwarzer** [comment]
FYI, This PR does not yet fix https://github.com/microsoft/vcpkg/issues/28358#issuecomment-1363672791

**Comment by dg0yt** [comment]
@MonicaLiu0311 Please double-check if the error is a regression at all. Obviously it links to the x86 zlib as it should, but the crashpad build itself is x64. There is an `environment.amd64` in the gn linker wrapper arguments which should be different IMO - and it is not related to my changes.

@cnSchwarzer Please double-check that you used this PR (fork/branch). In particular, the generated `${SOURCE_PATH}/third_party/zlib/BUILD.gn` must carry native separators (`\`) for zlib.

**Comment by cnSchwarzer** [comment]
I checked, and why it is a zlib related issue in the first place? I think it should be related to a find library path and a relative path conversion issue

**Comment by dg0yt** [comment]
> why it is a zlib related issue in the first place? I think it should be related to a find library path and a relative path conversion issue

I tried to explain it before: The absolute path of the zlib library is the only specific thing which vcpkg injects into the gn build. And it is a path on another drive in your use case `vcpkg install`.
I'm unsure why gn creates an invalid ninja rule from this input.

**Comment by cnSchwarzer** [comment]
I think it is still gn's regression about creating cross disk path on Windows platform

**Comment by dg0yt** [comment]
> I think it is still gn's regression about creating cross disk path on Windows platform

Possible. Still waiting for their response.

**Comment by dg0yt** [comment]
Obsolete

**Pull request closed without merging**
