### PR TITLE
[python3] Update to 3.10.5.

### PR DESCRIPTION
**Pull request by Hoikas**
Update python3 to current.

- #### What does your PR fix?
  See above.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  No change

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by Hoikas** [comment]
The osx CI failure seems to be a port with an incorrect hash.

**Comment by Hoikas** [comment]
CI passed :tada:

**Review by FrankXie05 — CHANGES_REQUESTED** [review]

**Comment by Hoikas** [comment]
CI failure is unrelated to these changes:
```
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:14 (message):
  

  File does not have expected hash:

          File path: [ /Users/vagrant/Data/downloads/inie0722-CTL-v1.0.0.tar.gz ]
      Expected hash: [ facd0afdb20437c0ffa5b097a68e2028faa314be6052e0db1e2c727ce5a0305bca8e575c946b0e10a6343dfaddc38770c1e5a56ae201e1aa906883df6d662398 ]
        Actual hash: [ 059f22460e147dcba9d92bd8afabca3c362541b70f49f8f2a19008dfbad66c59d1235720776f24cb84c95b3534e5ab0d093c76d352e7992fa44126c252c480f8 ]

  The cached file SHA512 doesn't match.  The file may have been corrupted.
  To re-download this file please delete cached file at path
  /Users/vagrant/Data/downloads/inie0722-CTL-v1.0.0.tar.gz and retry.
  ```

**Comment by Hoikas** [comment]
Updated to fix soft conflict introduced by #25215.

**Comment by Hoikas** [comment]
`air-ctl:x64-osx` failed again - unrelated to this port.

**Comment by FrankXie05** [comment]
Looks like a ci baseline.

**Comment by Hoikas** [comment]
CI passed 🎉

**Review by FrankXie05 — APPROVED** [review]

**Pull request merged**
