### PR TITLE
[vcpkg baseline] Fix uvatlas download file hash

### PR DESCRIPTION
**Pull request by JackBoosY**
uvatlas's binary tool `uvatlastool.exe`'s hash changed.
So add option `FILE_DISAMBIGUATOR` to `vcpkg_download_dstfile`.

Related #15210 #15018.

### CODE REVIEW

**Comment by JackBoosY** [comment]
Ping @BillyONeal for merge this PR first.

**Review by PhoebeHui — APPROVED** [review]

**Review by PhoebeHui — APPROVED** [review]

**Review by BillyONeal — CHANGES_REQUESTED** [review]
This is only touching the aria2 path but breaks the default non-aria2 path.

**Comment by BillyONeal** [comment]
I think rather than adding FILE_DISAMBIGUATOR to `vcpkg_download_distfile.cmake` the port should just change `FILENAME`. `vcpkg_from_github` needed an extra option only because in that command the filename is not otherwise exposed to the port.

Also, it looks like whatever was changing the SHA is gone? Because it works without this PR now....

**Comment by JackBoosY** [comment]
Fine, I'll close it now.

**Pull request closed without merging**
