### PR TITLE
[nlohmann-json] update to 3.10.4

### PR DESCRIPTION
**Pull request by nightlark**
Updates nlohmann-json to v3.10.4

- #### What does your PR fix?  
  Updates nlohmann-json to 3.10.4

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  No change, yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

### CODE REVIEW

**Comment by nightlark** [comment]
@azp rerun

**Comment by nightlark** [comment]
I'm not seeing why `microsoft.vcpkg.pr (x86_windows)` failed - the log mentions something about `vcpkg clean` failing, which kinda makes me think maybe this is an intermittent failure and a rerun of the pipeline is needed?

**Comment by dg0yt** [comment]
I had similar issues today. Try
~~~
git commit --allow-empty -m "CI"
git push
~~~

**Review by JonLiu1993 — APPROVED** [review]

**Pull request merged**
