### PR TITLE
[libsword] Add version 1.9.0 to vcpkg

### PR DESCRIPTION
**Pull request by svollbehr**
- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [X] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [X] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html).
- [X] The versioning scheme in `vcpkg.json` matches what upstream says.
- [X] The license declaration in `vcpkg.json` matches what upstream says.
- [X] The installed as the "copyright" file matches what upstream says.
- [X] The source code of the component installed comes from an authoritative source.
- [X] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is in the new port's versions file.
- [X] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by svollbehr** [comment]
@microsoft-github-policy-service agree

**Comment by jimwang118** [comment]
I got the following error when testing usage locally.
```
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error		CMake Error at F:/libsword/scripts/buildsystems/vcpkg.cmake:859 (_find_package):
  Could not find a package configuration file provided by "libsword" with any
  of the following names:

    libswordConfig.cmake
    libsword-config.cmake

  Add the installation prefix of "libsword" to CMAKE_PREFIX_PATH or set
  "libsword_DIR" to a directory containing one of the above files.  If
  "libsword" provides a separate development package or SDK, be sure it has
  been installed.		F:/libsword/scripts/buildsystems/vcpkg.cmake	859		

```

**Comment by jimwang118** [comment]
Note: I will be converting your PR to draft status. The above suggested changes are only recommendations. If you are willing to adopt them, please click "ready for review" after making the modifications. If you do not wish to make any changes, please click "ready for review" directly. That way, I can be aware that you've responded since you can't modify the tags.

**Comment by svollbehr** [comment]
Thanks for the feedback, @jimwang118!

Currently the library is set to build using 'msbuild' and not 'cmake', so the pull request do not contain any instructions related to 'cmake' build of the library. 

> Error		CMake Error at F:/libsword/scripts/buildsystems/vcpkg.cmake:859 (_find_package):

Is this caused by manually executing 'cmake'? Is it mandatory to build with 'cmake'? I have chosen to use the vcpkg_install_msbuild function. Can you help me understand how to re-create the error? I can not reproduce the errors locally with:

$ vcpkg install libsword:x86-windows

**Comment by dg0yt** [comment]
The errors occurs when using the exported CMake config ("usage"), not when building the port.

**Comment by jimwang118** [comment]
@svollbehr Thanks for your PR, Is work still being done for this PR?

**Comment by jimwang118** [comment]
Closing this PR since it seems that no progress is being made. Please ping us to reopen if work is still being done.

**Pull request closed without merging**
