### PR TITLE
Update to asio 1.13.0

### PR DESCRIPTION
**Pull request by HungMingWu**

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for the PR!

It looks like this upgrade regresses openvpn3 and restbed in a few cases. We'll need to fix them (via upgrades or patches) before we can accept this change.

|x64-windows|master| test |notes
|-----------|------|------|-----
|openvpn3   |Pass  |Fail  |**Regression**
|restbed    |Pass  |Fail  |**Regression**

|x64-windows-static|master| test |notes
|------------------|------|------|-----
|openvpn3          |Pass  |Fail  |**Regression**
|restbed           |Pass  |Fail  |**Regression**

|x64-osx|master| test |notes
|-------|------|------|-----
|restbed|Pass  |Fail  |**Regression**

|arm64-windows|master| test |notes
|-------------|------|------|-----
|openvpn3     |Pass  |Fail  |**Regression**
|restbed      |Pass  |Fail  |**Regression**

|x86-windows|master| test |notes
|-----------|------|------|-----
|restbed    |Pass  |Fail  |**Regression**

|x64-linux|master| test |notes
|---------|------|------|-----
|restbed  |Pass  |Fail  |**Regression**

**Comment by Rastaban** [comment]
It looks like they removed some previously deprecated functions in 1.13.0 (http://think-async.com/Asio/asio-1.13.0/doc/asio/history.html#asio.history.asio_1_13_0) this is probably the cause of the failures.  We could patch their uses and/or report the failures to the upstream ports for a real fix.

**Comment by PhoebeHui** [comment]
Related to https://github.com/microsoft/vcpkg/pull/6099

**Comment by grdowns** [comment]
Closing due to repo and branch deletion. Main PR #6099

**Pull request closed without merging**
