### PR TITLE
[libevent] remove dependency of default feature

### PR DESCRIPTION
**Pull request by DailyShana**
as building with openssl becomes a feature, the default feature do not depend on openssl.

### CODE REVIEW

**Review by NancyLi1013 — APPROVED** [review]

**Comment by dan-shaw** [comment]
What does this PR fix?

**Comment by DailyShana** [comment]
remove unnecessary dependency

**Comment by NancyLi1013** [comment]
@DailyShana thanks for this PR.
As we hope that every PR has a separate issue to follow up.
So if there is no issue open for the PR, we suggest open an issue so others may replicate this problem.

**Comment by kevinlul** [comment]
This is useful because OpenSSL will not be built unnecessarily when it is not required by libevent. OpenSSL already takes quite some time to compile.

**Comment by NancyLi1013** [comment]
All features have passed with the following triplets:
- x86-windows
- x64-windows
- x64-linux

BTW, only non-feature PRs must solve an issue. So it is not necessary to open an issue for this PR.

**Comment by dan-shaw** [comment]
Can you resolve the conflict and rerun the CI? We've recently fixed the Linux CI, so it should be all passing now.

**Pull request merged**
