### PR TITLE
[tracelogging] Add new port

### PR DESCRIPTION
**Pull request by diegovelaz**
**Describe the pull request**
Add microsoft/tracelogging port.

- #### What does your PR fix?
 `N/A`

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  `linux, Yes`

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  `Yes`

### CODE REVIEW

**Comment by diegovelaz** [comment]
@bhardwajs

**Comment by bhardwajs** [comment]
Any way we can get the logs for build failure here? Thanks!

**Comment by diegovelaz** [comment]
Hi there!
Is there a way we get the build failure logs to debug this port? @Adela0814 @Cheney-W

**Comment by Adela0814** [comment]
```
CMake Error at /mnt/vcpkg-ci/downloads/tools/cmake-3.24.0-linux/cmake-3.24.0-linux-x86_64/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find LTTngUST (missing: LTTNGUST_LIBRARIES LTTNGUST_INCLUDE_DIRS)
Call Stack (most recent call first):
  /mnt/vcpkg-ci/downloads/tools/cmake-3.24.0-linux/cmake-3.24.0-linux-x86_64/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindLTTngUST.cmake:108 (find_package_handle_standard_args)
  /agent/_work/1/s/scripts/buildsystems/vcpkg.cmake:824 (_find_package)
  CMakeLists.txt:11 (find_package)
```

Please see the details from: https://dev.azure.com/vcpkg/public/_build/results?buildId=76394&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by diegovelaz** [comment]
Hi @Adela0814 

This port depends on lttng-ust. We have another [PR](https://github.com/microsoft/vcpkg/pull/26277) in the works for a port for lttng-ust. We will not be able to move forward with this one until that one is checked in so this might go without any updates for a couple of days because of that.

**Comment by Adela0814** [comment]
Convert this PR to draft since there is no progress. Please ping us if this PR is ready for review again.

**Comment by Adela0814** [comment]
Closing this PR since it seems that no progress is being made. Please ping us to reopen if work is still being done.

**Pull request closed without merging**
