### PR TITLE
[tool-meson] Update to 0.56.0

### PR DESCRIPTION
**Pull request by c72578**
**Describe the pull request**

- What does your PR fix? Fixes #
Update meson to 0.56.0
Release notes:
https://mesonbuild.com/Release-notes-for-0-56-0.html
- Which triplets are supported/not supported? Have you updated the CI baseline?
  - All official triplets are supported.
  - CI baseline: No updated required.
    A patch for `libepoxy` was added as part of this PR.
- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

### CODE REVIEW

**Comment by NancyLi1013** [comment]
The failures on `x64-windows` and `x86-windows` like this:

`..\src\1.5.4-337c486045.clean\meson.build:1:0: ERROR: Value "gnu99" (of type "string") for combo option "C language standard to use" is not one of the choices. Possible choices are (as string): "none", "c89", "c99", "c11".`

Could you please try to look into and fix it?

**Comment by c72578** [comment]
I will prepare a patch for **`libepoxy`** tonight.
`gnu99` is used here in **`meson.build`**:
https://github.com/anholt/libepoxy/blob/09edbe01d901c0f01e866aa08455c6d9ee6fd0ac/meson.build#L4

**Review by NancyLi1013 — APPROVED** [review]

**Review by JackBoosY — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks!

**Pull request merged**
