### PR TITLE
[vcpkg.cmake] Add some helpers for wrappers

### PR DESCRIPTION
**Pull request by Neumann-A**
- [ ] z_vcpkg_find_library
- [ ] z_vcpkg_setup_target
- [ ] other stuff not yet defined?

### CODE REVIEW

**Comment by dg0yt** [comment]
`z_vcpkg_find_library` as a twin to `find_library` is an excellent start. 

However, for the wrappers I would prefer a high level function which either fully succeeds or fails (the wrapper *must* find a valid configuation):
- Set `<PKG>_INCLUDE_DIRECTORY` (needs file name and optional path suffix)
- Set `<PKG>_LIBRARY_RELEASE` (needs names and optional path suffix)
- Set `<PKG>_LIBRARY_DEBUG` (needs names and option path suffix)
- Set `<PKG>_LIBRARY`
- Set `<PKG>_LIBRARIES`
- Setup a *target* (needs name, can be "unofficial")

There are [standard variable names](https://cmake.org/cmake/help/v3.21/manual/cmake-developer.7.html#standard-variable-names). However, many find modules have different behaviour.

Setting the `<PKG>_FOUND` variable should be left to the original find module which would also consider components and versions.

Repeating a previous post, I would imaging something like:
~~~
vcpkg_find_libraries(ZLIB
    INCLUDE_NAME zlib.h
    LIBRARY_NAMES_RELEASE zlib z
    LIBRARY_NAMES_DEBUG zlibd z
)
~~~

With such a high level function, there probably needs to be a way to pass dependencies (target names) which are added to the `<PKG>_LIBRARIES` and target.

(Looking at targets, I even thought about adding a property which records the pkgconfig module name, for in-project pkgconfig patching in consuming ports.)

Wouldn't port tiff with its dependencies provide a good test case?
~~~
$ ./vcpkg depend-info tiff[*]
libjpeg-turbo: 
liblzma: 
libwebp[simd, nearlossless]: 
vcpkg-cmake: 
zlib: 
zstd: 
tiff[zstd, zip, lzma, jpeg, webp, tools, cxx]: libjpeg-turbo, liblzma, libwebp, vcpkg-cmake, zlib, zstd
~~~

Last not least, the implementation doesn't have to be in `vcpkg.cmake`. It might go to a separate cmake module, into a dedicated port (which needs an explicit dependency).

**Comment by JackBoosY** [comment]
Any update on this PR?

**Comment by JackBoosY** [comment]
Please temporary close this PR if you don't have spare time to finish it.

**Comment by Neumann-A** [comment]
@JackBoosY Why? It is in draft mode any way?

**Comment by JackBoosY** [comment]
We should keep open PRs as active as possible to reduce the time consumption of maintainers (even it is draft).

**Comment by LilyWangLL** [comment]
Ping @Neumann-A for response. Is work still being done for this PR?

**Comment by LilyWangLL** [comment]
Ping @Neumann-A for response. Is work still being done for this PR?

**Comment by BillyONeal** [comment]
Closing this PR as there has not been activity in over 4 months. Please feel free to reopen it, or another PR, should you wish to continue this.

**Pull request closed without merging**
