### PR TITLE
Fixing static builds for HPX

### PR DESCRIPTION
**Pull request by hkaiser**
- flyby: prefixing downloaded patch files with 'hpx-'

### CODE REVIEW

**Comment by codicodi** [comment]
> making sure HWLOC is always 'built' as dynamic

Any comment on this? I didn't try it in the context of hpx, but standalone hwloc seems to work fine as a static library

**Comment by hkaiser** [comment]
> Any comment on this? I didn't try it in the context of hpx, but standalone hwloc seems to work fine as a static library.

The current HWLOC portfile simply installs the downloaded HWLOC binaries which currently does not work properly for static builds as the downloaded binaries are built as dynamic.

**Comment by codicodi** [comment]
See https://github.com/Microsoft/vcpkg/pull/1169

**Comment by hkaiser** [comment]
@codicodi Ok, I have removed the patch related to HWLOC from this PR

**Comment by ras0219-msft** [comment]
Thanks!

**Pull request merged**
