### PR TITLE
[apr] add usage

### PR DESCRIPTION
**Pull request by rinrab**
This is a follow-up to #40742

### CODE REVIEW

**Comment by jimwang118** [comment]
You should add the following content to vcpkg.json: "port-version": 1.

**Comment by jimwang118** [comment]
Note: I will be converting your PR to draft status. The above suggested changes are only recommendations. If you are willing to adopt them, please click "ready for review" after making the modifications. If you do not wish to make any changes, please click "ready for review" directly. That way, I can be aware that you've responded since you can't modify the tags.

**Comment by rinrab** [comment]
Done.

**Comment by jimwang118** [comment]
When I use the following code to test, I get a compilation error.
```
find_package(apr CONFIG REQUIRED)
  target_link_libraries(main PRIVATE
    $<$<TARGET_EXISTS:apr::apr-1>:apr::apr-1>
    $<$<TARGET_EXISTS:apr::aprapp-1>:apr::aprapp-1>
    $<$<TARGET_EXISTS:apr::libapr-1>:apr::libapr-1>
    $<$<TARGET_EXISTS:apr::libaprapp-1>:apr::libaprapp-1>
  )
```
error:
```
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C1083	Cannot open include file: 'arp.h': No such file or directory	tapr	F:\testspace\tapr\tapr.cpp	5		

```

**Comment by chemodax** [comment]
> When I use the following code to test, I get a compilation error.
> 
> ```
> find_package(apr CONFIG REQUIRED)
>   target_link_libraries(main PRIVATE
>     $<$<TARGET_EXISTS:apr::apr-1>:apr::apr-1>
>     $<$<TARGET_EXISTS:apr::aprapp-1>:apr::aprapp-1>
>     $<$<TARGET_EXISTS:apr::libapr-1>:apr::libapr-1>
>     $<$<TARGET_EXISTS:apr::libaprapp-1>:apr::libaprapp-1>
>   )
> ```
> 
> error:
> 
> ```
> Severity	Code	Description	Project	File	Line	Suppression State	Details
> Error	C1083	Cannot open include file: 'arp.h': No such file or directory	tapr	F:\testspace\tapr\tapr.cpp	5		
> ```

It should be `apr.h` not `arp.h`

**Comment by jimwang118** [comment]
Usage test pass with following triplet:

```
x64-windows
```

**Comment by BillyONeal** [comment]
Thanks!

**Pull request merged**
