### PR TITLE
Allow redirection of the scripts folder.

### PR DESCRIPTION
**Pull request by martin-s**
Like in #4883, make scripts folder more flexible.

### CODE REVIEW

**Comment by cbezault** [comment]
It's not clear to me why this feature is necessary. The scripts folder is a core part of vcpkg while the downloads folder is more of a tmp directory. What is the value added for you to be able to redirect the scripts folder?

**Comment by martin-s** [comment]
It's a missing part for my build scenarios, a single instance of vcpkg managing distributed port directories.
See also discussion in #114.

**Comment by cbezault** [comment]
In #114 you mention that you want a single instance of vcpkg managing many different port directories. From my perspective the scripts folder is a core part of vcpkg. Is the idea just that the vcpkg binary wouldn't have to live in the same directory as the scripts folder?

**Comment by martin-s** [comment]
Yes, although the dependencies of vcpkg are very low in terms of data sizes, they exist. As you named, the script folder is such a dependency. My workaround is that the script folder is available (through a link or a copy) in a changed vcpkg environment (-vcpkg-root). And this PR would integrate it into vcpkg with no downsides to the average vcpkg user.
The long-term vision/goal would be more towards a solution like npm in nodejs or pip in python environments.

**Comment by vicroms** [comment]
@martin-s 

I'm not convinced about using an environment variable for this. 
I propose changing the implementation to use a command line argument.

See #7053 and #6981 for how to process global command line arguments.

**Comment by martin-s** [comment]
> I'm not convinced about using an environment variable for this.

Either am I. Unfortunately, there hasn't been any alignment on this topic, see #4883.

**Comment by martin-s** [comment]
To make it more generic, we could also the .vcpkg-root file to overwrite the folder paths. If nothing is written to the file, it should take the standard paths, otherwise use the overwritten paths from the file.

**Comment by vicroms** [comment]
Hi @martin-s 

I made a change to use the `--scripts-root=<PATH>` format, which is the preferred way to provide argument values in **vcpkg** going forward (there's an open PR that will change this for `--triplet` and `--vcpkg-root`).

**Comment by vicroms** [comment]
@martin-s 
Thanks for the PR!

**Pull request merged**
