### PR TITLE
[vcpkg] Added command line switch --all-installed to allow exporting of all packages without needing to specify individual packages

### PR DESCRIPTION
**Pull request by miseri**
**Describe the pull request**

A command line switch has been added to the export command that allows all installed packages to be exported without requiring them to be specified individually.

- What does your PR fix? Fixes issue #
N/A

- Which triplets are supported/not supported? Have you updated the CI baseline?

The PR does not consider triplets. It simply allows the export command to export all installed packages which I found to be useful in our own project that uses vcpkg.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

Yes. In particular the PR is concerned with the export function of the vcpkg tool itself (not any ports).

### CODE REVIEW

**Comment by JackBoosY** [comment]
I have also considered adding this feature, but because some ports will fail in the build queue, subsequent ports will abort the build. I think we should consider this situation.

**Comment by strega-nil** [comment]
Hm... I think it's an interesting idea, but I'd rather put it behind an experimental flag if anything. I'll see if we can discuss this in our meeting.

**Comment by strega-nil** [comment]
Okay, our feeling in the meeting was that this was a good feature, but it should be experimental; can you rename the flag `--x-all-installed`?

**Comment by miseri** [comment]
Ok, great, thanks for the quick feedback.

I will rename the flag to --x-all-installed.

**Comment by strega-nil** [comment]
Alright, this looks good to me, but I'm not personally comfortable merging it since I'm pretty new to the team; I'll approve it and request someone else review. Thanks so much @miseri 😄

**Review by strega-nil — APPROVED** [review]

**Comment by ras0219-msft** [comment]
clang-format'd, LGTM!

**Review by ras0219-msft — APPROVED** [review]

**Review by JackBoosY — APPROVED** [review]

**Comment by miseri** [comment]
> Alright, this looks good to me, but I'm not personally comfortable merging it since I'm pretty new to the team; I'll approve it and request someone else review. Thanks so much @miseri smile

Thank you for the great tool, glad I could contribute a little something back. :-)

**Pull request merged**
