### PR TITLE
[freerdp] Update, cleanup + [libusb] Fix pc file

### LINKED ISSUE #32644: [freerdp] update to 2.10.0
### Library name

FreeRDP

### New version number

2.10.0

### Other information that may be useful (release notes, etc...)

Latest release available here: https://github.com/FreeRDP/FreeRDP/releases/tag/2.10.0

### PR DESCRIPTION
**Pull request by dg0yt**
Fixes freerdp[core,server,urbdrc]:x64-linux, sub-issue of #32398.
Fixes #32644.
Fix libusb-1.0.pc for windows.
Test features in CI.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by Adela0814** [comment]
I encountered the following error while testing the feature `urbdrc`:

Repro step:
`.\vcpkg.exe install freerdp[urbdrc]:x64-windows`

Error:
```
/MANIFESTFILE:client\common\CMakeFiles\freerdp-client.dir/intermediate.manifest client\common\CMakeFiles\freerdp-client.dir/manifest.res" failed (exit code 1104) with the following output:
LINK : fatal error LNK1104: cannot open file 'usb-1.0.lib'
```

**Comment by Adela0814** [comment]
All feature test pass now.

I encountered a new error while testing usage:
Usage provided by vcpkg:
```
    find_package(FreeRDP CONFIG REQUIRED)
    target_link_libraries(main PRIVATE freerdp)

    find_package(FreeRDP-Client CONFIG REQUIRED)
    target_link_libraries(main PRIVATE freerdp-client)

    find_package(WinPR CONFIG REQUIRED)
    target_link_libraries(main PRIVATE winpr)
```

Error:
image

**Comment by dg0yt** [comment]
@Adela0814  The error message is incomplete. (Why not paste text?)

**Comment by Adela0814** [comment]
> @Adela0814 The error message is incomplete. (Why not paste text?)

That's all.

```
1> CMake generation started for default configuration: 'x64-Debug'.
1> Found and using vcpkg toolchain file (E:/4/vcpkg/scripts/buildsystems/vcpkg.cmake).
1> Command line: "C:\WINDOWS\system32\cmd.exe" /c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="E:\CMakeTest\out\install\x64-Debug" -DCMAKE_C_COMPILER:FILEPATH="C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe"  -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" -DCMAKE_TOOLCHAIN_FILE="E:/4/vcpkg/scripts/buildsystems/vcpkg.cmake" "E:\CMakeTest" 2>&1"
1> Working directory: E:\CMakeTest\out\build\x64-Debug
1> [CMake] CMake Error at E:/4/vcpkg/scripts/buildsystems/vcpkg.cmake:855 (_find_package):
1> [CMake]   Found package configuration file:
1> [CMake] 
1> [CMake]     E:/4/vcpkg/installed/x64-windows/share/freerdp-client2/FreeRDP-ClientConfig.cmake
1> [CMake] 
1> [CMake]   but it set FreeRDP-Client_FOUND to FALSE so package "FreeRDP-Client" is
1> [CMake]   considered to be NOT FOUND.  Reason given by package:
1> [CMake] 
1> [CMake]   The following imported targets are referenced, but are missing: winpr
1> [CMake] 
1> [CMake] Call Stack (most recent call first):
1> [CMake]   CMakeTest/CMakeLists.txt:15 (find_package)
1> [CMake] -- Configuring incomplete, errors occurred!
1> [CMake] See also "E:/CMakeTest/out/build/x64-debug/CMakeFiles/CMakeOutput.log".
1> 'C:\WINDOWS\system32\cmd.exe' '/c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="E:\CMakeTest\out\install\x64-Debug" -DCMAKE_C_COMPILER:FILEPATH="C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe"  -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" -DCMAKE_TOOLCHAIN_FILE="E:/4/vcpkg/scripts/buildsystems/vcpkg.cmake" "E:\CMakeTest" 2>&1"' execution failed with error: ''C:\WINDOWS\system32\cmd.exe' '/c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="E:\CMakeTest\out\install\x64-Debug" -DCMAKE_C_COMPILER:FILEPATH="C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe"  -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" -DCMAKE_TOOLCHAIN_FILE="E:/4/vcpkg/scripts/buildsystems/vcpkg.cmake" "E:\CMakeTest" 2>&1"' returned with exit code: 1'.

```

**Comment by dg0yt** [comment]
> The following imported targets are referenced, but are missing: winpr

Added missing `find_dependency(...)` calls between the installed configs, guided by the output of
~~~
grep 'foreach._target "' packages/freerdp_x64-linux/share/*/*.cmake
~~~

**Comment by Adela0814** [comment]
I'm not able to find any `freerdp` related header in my test project,the include directories may need to be fixed:
image

**Comment by dg0yt** [comment]
Maybe upstream wants you to use `FreeRDP_INCLUDE_DIR`? 
I can add this to the targets' properties. But like `find_dependency`, this convenience will initially only exist in vcpkg, until I upstream the changes.

**Comment by Adela0814** [comment]
Usage tested pass on `x64-windows`.

**Review by Adela0814 — APPROVED** [review]

**Pull request merged**
