### PR TITLE
[rtmidi] update to 3.0.0

### PR DESCRIPTION
**Pull request by jiayuehua**
also add android fail to ci

### CODE REVIEW

**Comment by jiayuehua** [comment]
```
/mnt/vcpkg-ci/b/rtmidi/src/6.0.0-ef3f47c55b.clean/RtMidi.cpp:4957:5: error: 'AMidiOutputPort_open' is unavailable: introduced in Android 29
    AMidiOutputPort_open(midiIn->receiveDevice, 0, &midiIn->midiOutputPort);
    ^
/android-ndk-r26d/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/amidi/AMidi.h:249:26: note: 'AMidiOutputPort_open' has been explicitly marked unavailable here
media_status_t AMIDI_API AMidiOutputPort_open(const AMidiDevice *device, int32_t portNumber,
                         ^
/mnt/vcpkg-ci/b/rtmidi/src/6.0.0-ef3f47c55b.clean/RtMidi.cpp:5083:3: error: 'AMidiDevice_release' is unavailable: introduced in Android 29
  AMidiDevice_release(receiveDevice);
  ^
/android-ndk-r26d/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/amidi/AMidi.h:168:26: note: 'AMidiDevice_release' has been explicitly marked unavailable here
media_status_t AMIDI_API AMidiDevice_release(const AMidiDevice *midiDevice) __INTRODUCED_IN(29);
                         ^
/mnt/vcpkg-ci/b/rtmidi/src/6.0.0-ef3f47c55b.clean/RtMidi.cpp:5113:35: error: 'AMidiOutputPort_receive' is unavailable: introduced in Android 29
    ssize_t numMessagesReceived = AMidiOutputPort_receive(
                                  ^
/android-ndk-r26d/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/amidi/AMidi.h:277:19: note: 'AMidiOutputPort_receive' has been explicitly marked unavailable here
ssize_t AMIDI_API AMidiOutputPort_receive(const AMidiOutputPort *outputPort, int32_t *opcodePtr,
                  ^
/mnt/vcpkg-ci/b/rtmidi/src/6.0.0-ef3f47c55b.clean/RtMidi.cpp:5246:3: error: 'AMidiDevice_release' is unavailable: introduced in Android 29
  AMidiDevice_release(sendDevice);
  ^
/android-ndk-r26d/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/amidi/AMidi.h:168:26: note: 'AMidiDevice_release' has been explicitly marked unavailable here
media_status_t AMIDI_API AMidiDevice_release(const AMidiDevice *midiDevice) __INTRODUCED_IN(29);
                         ^
/mnt/vcpkg-ci/b/rtmidi/src/6.0.0-ef3f47c55b.clean/RtMidi.cpp:5261:3: error: 'AMidiInputPort_send' is unavailable: introduced in Android 29
  AMidiInputPort_send(midiInputPort, (uint8_t*)message, size);
  ^
/android-ndk-r26d/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/amidi/AMidi.h:309:19: note: 'AMidiInputPort_send' has been explicitly marked unavailable here
ssize_t AMIDI_API AMidiInputPort_send(const AMidiInputPort *inputPort, const uint8_t *buffer,
                  ^
```

**Comment by jiayuehua** [comment]
@MonicaLiu0311 could you please help run ci again?

**Comment by MonicaLiu0311** [comment]
> @MonicaLiu0311 could you please help run ci again?

Done

**Comment by MonicaLiu0311** [comment]
All features are tested successfully in the following triplet:
```
x64-linux
```

**Review by MonicaLiu0311 — APPROVED** [review]

**Review by data-queue — APPROVED** [review]

**Pull request merged**
