### PR TITLE
Fix building boost.mpi

### PR DESCRIPTION
**Pull request by albertziegenhagel**
Currently the boost-mpi port says that it has build boost.mpi successful but it actually did not build anything.

This is because boost.mpi is skipped by default and has to be enabled via `using mpi ;` in the `user-config.jam` manually.

This PR enables building boost.mpi and adds `msmpi` as a dependency to it. Additionally I had to add boost.serialization to the `Jamroot.jam` file, since boost.mpi depends on it.

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for the PR!

I want to make sure that the connection between `vcpkg install boost` and installing `msmpi` has at least one "optional" link, because otherwise a ton of users' first experience with vcpkg will be it failing and telling them they need to go do something with an `msi` :(

I see a few ways to do that:
1. Make building the `boost-mpi` runtime libraries optional, but always provide the headers
2. Make the link from `boost` to `boost-mpi` optional, and remove `boost-mpi` from the dependencies of `boost-odeint`, `boost-coroutine`, and `boost-graph-parallel`.
3. Keep the above links and make them all optional

I do not know enough about the boost mpi library to judge which of these approaches is the best. Do you have any insights?

**Comment by albertziegenhagel** [comment]
Keeping it optional is actually a very good idea. I totally missed that other boost libraries do actually have a dependency on `boost.mpi`.

I think option 3. would make the most sense. Only installing the headers, as it is currently done, does not make a lot of sense, since as soon as you include them and actually use any of the functionality you would get a linker error anyway. From a quick look on `boost.odeint` and `boost.graph-parallel` (I couldn't find any dependency on `boost.mpi` in `boost.coroutine`) it seems that you have to include special headers to enable mpi support in those libraries. If you do not use any of the mpi functionality they just work without `boost.mpi` (though I have not tested this myself!). So an optional dependency seems to be the way to go.

As far as I can see the `generate-ports.ps1` machinery does not yet support generating optional dependencies through feature packages, am I right?

**Comment by ras0219-msft** [comment]
We already tried internally and didn't get too far ;)

If the connection between the libraries is including special headers, then I think it's actually best to just remove the dependency links from `boost-odeint` and `boost-graph-parallel`. Features are needed to ensure a particular library gets rebuilt when a dependency changes and to sequence builds -- since these don't need that afaict, I think it will be better to just not specify anything. If the user happens to install `boost-mpi`, everything will Just Work regardless of the installation order.

In the case of `boost`, it is probably reasonable to add an `mpi` feature. Rebuilding is near-instant since it is just a stub package anyway.

We do generate optional dependencies for a few sublibraries [1][2].

[1] https://github.com/Microsoft/vcpkg/blob/a0648c23afd9f081bf8d88a41a6842e969f05805/ports/boost-vcpkg-helpers/generate-ports.ps1#L43-L51
[2] https://github.com/Microsoft/vcpkg/blob/a0648c23afd9f081bf8d88a41a6842e969f05805/ports/boost-vcpkg-helpers/generate-ports.ps1#L91-L110

**Comment by ras0219-msft** [comment]
I've applied the changes we discussed.

Thanks for the PR!

**Comment by cenit** [comment]
Thank you for having left optional boost-mpi now that it is working. Due to the fact that MSMPI does not work in all triplets (#2059), it was a little troublesome but I was able to update to latest boost removing first some components and then re-installing them (upgrading was continuously triggering the new MSMPI dependency)

**Pull request merged**
