### PR TITLE
[imgui-sfml] initial port

### PR DESCRIPTION
**Pull request by kiwixz**

### CODE REVIEW

**Comment by cenit** [comment]
Duplicate of #7429?

**Comment by kiwixz** [comment]
Yes it is.  I'm sorry, I came from eliasdaler/imgui-sfml#96 and thought nobody did it yet...
I guess it's just an updated version then 😅

**Comment by dan-shaw** [comment]
@kiwixz I've merged #7429 first because it supports all the platforms. Could you merge your changes?

**Comment by kiwixz** [comment]
@dan-shaw it should be good to go

**Pull request merged**
