### PR TITLE
[vcglib] inital port

### PR DESCRIPTION
**Pull request by MarkIanHolland**
[VCGlib](https://github.com/cnr-isti-vclab/vcglib) #2952 #2382
I added a patch to try and consume Eigen3 from vcpkg, but there does seem to be some [issues](https://github.com/cnr-isti-vclab/vcglib/issues/45) with some of those features.

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for the PR!

Is vcglib usable without Eigen? Because it seems it doesn't support the version of eigen currently in vcpkg, perhaps we should package it without eigen support (if that's an option).

**Comment by MarkIanHolland** [comment]
@ras0219-msft Vcglib doesn't provide a version without eigen, it's just dropped into the repo and it's quite widely used. I don't really know how valid the flag 'VCG_USE_EIGEN' is, I can't see it in the docs for instance. I felt I should mention that issue so we know it wasn't a vcpkg bug.

**Comment by MarkIanHolland** [comment]
@Codiferous That's right. I just thought it would be better to use the vcpkg copy of eigen so we didn't have random bits and pieces lying around. Thank you 😄

**Comment by Codiferous** [comment]
@MarkIanHolland I think you've got the right idea 😄

One last question --

I tried out your PR by grabbing some of the code in the "apps" folder on the Github repo (in particular, I grabbed the `metro` app). I get linker error because `vcg::ply::PlyFile::AddToRead` isn't built. 

It appears that the library has a bunch of wrappers, one of which is ply. I believe it's intentional that these aren't built, but I just wanted to confirm for a sanity check.

**Comment by MarkIanHolland** [comment]
You would have needed to compile [plylib](https://github.com/cnr-isti-vclab/vcglib/blob/a8e87662b63ee9f4ded5d4699b28d74183040803/apps/metro/metro.pro#L7) to have the wrapper build correctly.

**Comment by Codiferous** [comment]
@MarkIanHolland Ah, that seems reasonable. Okay, let's get this PR merged!

**Pull request merged**
