### PR TITLE
[opus] Update port to 1.3.1-2

### PR DESCRIPTION
**Pull request by evpobr**
Adds `include/opus` to interface directories. Common include pattern is:

```c
#include <opus/opus.h>
```

But Opus developers use in all projects:

```c
#include <opus.h>
```

With this patch both are supported.

### CODE REVIEW

**Comment by evpobr** [comment]
Git checkout failed?

**Comment by PhoebeHui** [comment]
It's not relate to this change, @strega-nil, could you help have a look?

Failures:
From https://github.com/microsoft/vcpkg
 + 2edc6cd3d...281f57f30 refs/pull/11279/merge -> pull/11279/merge  (forced update)
git checkout --progress --force refs/remotes/pull/11279/merge
Previous HEAD position was 01cb869fd Merge 2043550376e0d6ae0b6eac2119fb82e84a0f8b35 into 6920b49047f2de6880df8ef9724cc508c5f491ca
fatal: update_ref failed for ref 'HEAD': cannot lock ref 'HEAD': Unable to create '/Volumes/data/work/1/s/.git/HEAD.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
##[error]Git checkout failed with exit code: 128

**Review by PhoebeHui — APPROVED** [review]

**Comment by evpobr** [comment]
> Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. 

This project tries to retrieve project version from git tag. May be this is the reason?

**Comment by strega-nil** [comment]
No, there was an error somewhere leaving vcpkg in an invalid state; I've reset the machine.

**Comment by strega-nil** [comment]
Cool, thanks @evpobr!

**Pull request merged**
