### PR TITLE
[libunifex]: disable build tests and examples

### PR DESCRIPTION
**Pull request by jiayuehua**
- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [X] SHA512s are updated for each updated download
- [ ] ~The "supports" clause reflects platforms that may be fixed by this new version~
- [ ] ~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~
- [ ] ~Any patches that are no longer applied are deleted from the port's directory.~
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Review by FrankXie05 — CHANGES_REQUESTED** [review]

**Comment by FrankXie05** [comment]
Sorry for the wrong label. :)

**Comment by FrankXie05** [comment]
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". 
          That way, I can be aware that you've responded since you can't modify the tags.

**Comment by jiayuehua** [comment]
I mainly want to fix gtest dependency. Now BUILD_TESTS is no longer feature any more.

**Review by dg0yt — CHANGES_REQUESTED** [review]

**Comment by FrankXie05** [comment]
If just disable `TEST`, I think it is acceptable.

**Review by FrankXie05 — APPROVED** [review]

**Comment by dan-shaw** [comment]
Can you elaborate on what you are trying to fix? I believe upstream still has testing support.

**Comment by jiayuehua** [comment]
before change, if enable test feature, https://github.com/facebookexperimental/libunifex/blob/e3e8fc0f3b310b2abe4ea8eda59d0ff0ecf197c0/cmake/gtest.cmake#L6 # Download and unpack googletest at configure time , this port will download google test itself other than use vcpkg's test.

**Pull request merged**
