### PR TITLE
[opencv4] Fix linking halide

### PR DESCRIPTION
**Pull request by huangqinjin**
Workaround for issue #11428 .

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
Same issue with #11331 :
```
CMake Error at G:/vcpkg/scripts/buildsystems/vcpkg.cmake:250 (_add_library):
  _add_library cannot create imported target "LibHaru::LibHaru" because
  another target with the same name already exists.
```

**Comment by huangqinjin** [comment]
@JackBoosY I looked into #11331 . It's not related to PR. The problem is in `vtk/FindLibHaru.cmake`. Should check if already exists before adding target `LibHaru::LibHaru` since `FindLibHaru.cmake` can be called multiple times.

**Comment by JackBoosY** [comment]
@huangqinjin I think that's correct, so let's wait my PR to fix it first.

**Comment by JackBoosY** [comment]
@Neumann-A Could you please take a look?

**Comment by Neumann-A** [comment]
@JackBoosY: Try building VTK with the changes made in #9960. (I.E. replace the FindLibHaru.patch with 6890.diff from #9960). Maybe that fixes it. There is a c&p error in the previous patch.

**Comment by JackBoosY** [comment]
I think this PR can currently run independently without relying on other PRs.

**Comment by autoantwort** [comment]
It seems that it is now the other way around. If you don't use the package the c++17 requirement from halide is not forwarded. See https://github.com/microsoft/vcpkg/issues/31057

**Pull request merged**
