### PR TITLE
[sqlite-orm] Update to 1.6

### LINKED ISSUE #15503: [sqlite-orm] Update to 1.6
Library name: sqlite-orm
https://github.com/fnc12/sqlite_orm

New version number: 1.6
https://github.com/fnc12/sqlite_orm/releases/tag/1.6

### PR DESCRIPTION
**Pull request by NancyLi1013**
**Describe the pull request**

- What does your PR fix? Fixes #15503

 Update to latest version 1.6

 Update patches

Note: All features have passed with the following triplets:

- x86-windows
- x64-windows-static

### CODE REVIEW

**Comment by mikedld** [comment]
CMake config package seems to no longer be exported with this change.

**Comment by NancyLi1013** [comment]
There is no cmake config file in this new version. The usage has been updated as the follows:

```
    find_path(SQLITE_ORM_INCLUDE_DIRS "sqlite_orm/sqlite_orm.h")
    target_include_directories(main PRIVATE ${SQLITE_ORM_INCLUDE_DIRS})
```

**Comment by mikedld** [comment]
It's certainly there (https://github.com/fnc12/sqlite_orm/blob/1.6/cmake/SqliteOrmConfig.cmake.in) and there's some export code there as well (https://github.com/fnc12/sqlite_orm/blob/1.6/packaging/CMakeLists.txt)...

**Comment by NancyLi1013** [comment]
Thanks for your help. I have noticed this. Will update later.

**Comment by mikedld** [comment]
Tested on x64-osx, works like a charm ;) Thanks! Didn't test with x64-linux yet, but it's probably a safe bet this fixes #15555 as the exported config file is much cleaner now.

**Comment by NancyLi1013** [comment]
Thanks for your test and attention. @mikedld 
I have tested this on x64-linux and it can build fine now.

**Review by JackBoosY — APPROVED** [review]

**Pull request merged**
