### PR TITLE
[cpu-features] Add new port

### PR DESCRIPTION
**Pull request by myd7349**
**Describe the pull request**

- What does your PR fix?
Add new port: https://github.com/google/cpu_features

- Which triplets are supported/not supported? Have you updated the CI baseline?
N/A. No.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes.

### CODE REVIEW

**Comment by PhoebeHui** [comment]
@myd7349, thanks for the PR!

Could you take a look at the failures on arm64-windows, arm-uwp and x64-uwp? if the triplets doesn't support, could you add them to 'Supports'?

**Comment by myd7349** [comment]
> 
> 
> @myd7349, thanks for the PR!
> 
> Could you take a look at the failures on arm64-windows, arm-uwp and x64-uwp? if the triplets doesn't support, could you add them to 'Supports'?

Thanks. I will look into it this weekend.

**Comment by PhoebeHui** [comment]
@myd7349, you only need to add arm and uwp to 'Supports', could you please remove them from ci.baseline file?

**Comment by myd7349** [comment]
> 
> 
> @myd7349, you only need to add arm and uwp to 'Supports', could you please remove them from ci.baseline file?
> 
> For the json file check failed in CI pipeline, you can use ./vcpkg x-format-manifest --all to format the json file.

Hi @PhoebeHui Thanks. Done!

**Comment by PhoebeHui** [comment]
All features test passed on x64-windows and x64-linux.

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
