### PR TITLE
[openssl] fix mingw arm64 build

### LINKED ISSUE #35731: [openssl] Build error on arm64-mingw-static-release
Package: openssl:arm64-mingw-static-release@3.1.4#1

**Host Environment**

- Host: x64-linux
- Compiler: Clang 17.0.6
-    vcpkg-tool version: 2023-12-12-1c9ec1978a6b0c2b39c9e9554a96e3e275f7556e
    vcpkg-scripts version: 0e47c1985 2023-12-15 (15 hours ago)

**To Reproduce**

`vcpkg install openssl:arm64-mingw-static-release`
**Failure logs**

```
-- Using cached openssl-openssl-openssl-3.1.4.tar.gz.
-- Cleaning sources at /home/cat/git/vcpkg/buildtrees/openssl/src/nssl-3.1.4-c5488d00d9.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/cat/git/vcpkg/downloads/openssl-openssl-openssl-3.1.4.tar.gz
-- Applying patch disable-apps.patch
-- Applying patch disable-install-docs.patch
-- Applying patch script-prefix.patch
-- Applying patch windows/install-layout.patch
-- Applying patch windows/install-pdbs.patch
-- Applying patch unix/android-cc.patch
-- Applying patch unix/move-openssldir.patch
-- Applying patch unix/no-empty-dirs.patch
-- Applying patch unix/no-static-libs-for-shared.patch
-- Using source at /home/cat/git/vcpkg/buildtrees/openssl/src/nssl-3.1.4-c5488d00d9.clean
-- Found external ninja('1.11.1').
-- Getting CMake variables for arm64-mingw-static-release
-- Getting CMake variables for arm64-mingw-static-release-rel
-- Configuring arm64-mingw-static-release-rel
-- Building arm64-mingw-static-release-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: /usr/bin/make V=1 -j 2 -f Makefile build_sw
    Working Directory: /home/cat/git/vcpkg/buildtrees/openssl/arm64-mingw-static-release-rel/
    See logs for more information:
      /home/cat/git/vcpkg/buildtrees/openssl/build-arm64-mingw-static-release-rel-out.log
      /home/cat/git/vcpkg/buildtrees/openssl/build-arm64-mingw-static-release-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:151 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:2 (vcpkg_build_make)
  ports/openssl/unix/portfile.cmake:119 (vcpkg_install_make)
  ports/openssl/portfile.cmake:71 (include)
  scripts/ports.cmake:170 (include)



```

### PR DESCRIPTION
**Pull request by minnyres**
Fixes https://github.com/microsoft/vcpkg/issues/35731. Patch file copied from MSYS2 project: https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-openssl/001-support-aarch64.patch

### CODE REVIEW

**Comment by minnyres** [comment]
@microsoft-github-policy-service agree

**Comment by MonicaLiu0311** [comment]
```
##[error]Found the following errors:
##[error]versions/o-/openssl.json(2,): error : while parsing versions for openssl from version/o-/openssl.json
3.1.4#1 is declared with 5ee74387a1dd212dc9754c614809ff86bd0638fa, but the local port has a different SHA 6f02f56eef2f066c7c1066b27f3092b477517544.
Please update the port's version fields and then run:
vcpkg x-add-version openssl
```

Please run command `./vcpkg x-add-version openssl unix` to generate version json data and push it.

**Comment by dg0yt** [comment]
> Please run command `./vcpkg x-add-version openssl unix` to generate version json data and push it.

Please extend and correct.

**Comment by MonicaLiu0311** [comment]
> > Please run command `./vcpkg x-add-version openssl unix` to generate version json data and push it.
> 
> Please extend and correct.

Done

**Comment by minnyres** [comment]
> Please run `./vcpkg x-add-version portName ` before each push:

I have changed `port-version` to 2 and run `./vcpkg x-add-version  openssl`.

**Comment by minnyres** [comment]
I will close this and resubmit a pull request to resolve conflicts.

**Pull request closed without merging**
