### PR TITLE
Update vcpkg-tool to 2022-01-19

### PR DESCRIPTION
**Pull request by BillyONeal**

### CODE REVIEW

**Comment by autoantwort** [comment]
The ci command segfaults

**Comment by autoantwort** [comment]
Would be fixed by https://github.com/microsoft/vcpkg-tool/pull/327

**Comment by autoantwort** [comment]
Ok not completely, it then fails at 
```
Starting package 4/1734: absent:x64-osx
Building package absent:x64-osx...
-- Using cached rvarago-absent-0.3.1.tar.gz.
-- Extracting source /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/downloads/rvarago-absent-0.3.1.tar.gz
-- Using source at /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/absent/src/0.3.1-40487c5ce5.clean
-- Configuring x64-osx-dbg
-- Configuring x64-osx-rel
-- Building x64-osx-dbg
-- Building x64-osx-rel
-- Installing: /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/packages/absent_x64-osx/share/absent/README.md
-- Installing: /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/packages/absent_x64-osx/share/absent/copyright
-- Performing post-build validation
-- Performing post-build validation done
Error: vcpkg has crashed; no additional details are available.
The source line is /Users/leanderSchulten/git_projekte/vcpkg-tool/src/vcpkg/build.cpp(958)
```

**Comment by BillyONeal** [comment]
> Ok not completely, it then fails at

Right, that change sees when nulls happen and skips over them, but it doesn't fix that nulls got in there in the first place which is the actual bug. It regressed in https://github.com/microsoft/vcpkg-tool/pull/298 and I'm investigating.

**Comment by BillyONeal** [comment]
https://github.com/microsoft/vcpkg-tool/pull/329/ is my current WIP after spending all day trying to diagnose the issue

**Comment by BillyONeal** [comment]
> Maybe change `ports.cmake` to trigger a full rebuild

That would trigger a rebuild for customers too which is undesirable.

**Comment by autoantwort** [comment]
I mean you only change it to trigger a full rebuild to test if everything still works. If everything still works you revert the change again.

**Comment by BillyONeal** [comment]
> I mean you only change it to trigger a full rebuild to test if everything still works. If everything still works you revert the change again.

Oh, I see. I suppose getting a full run is a good idea. For that I can just trigger a CI run: https://dev.azure.com/vcpkg/public/_build/results?buildId=66773&view=results

**Pull request merged**
