### PR TITLE
[fontconfig/freetype/fribidi] Update versions

### LINKED ISSUE #40560: [freetype] Download from github instead of sourceforge
### Is your feature request related to a problem? Please describe.

Microsoft has blocked sourceforge.net. Building freetype is impossible because vcpkg is downloading freetype from sourceforge.net.

### Proposed solution

The package should be updated to download from https://github.com/freetype/freetype

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Osyotr**
https://gitlab.freedesktop.org/fontconfig/fontconfig/-/compare/2.14.2...2.15.0
https://gitlab.freedesktop.org/freetype/freetype/-/compare/VER-2-13-2...VER-2-13-3
https://github.com/fribidi/fribidi/compare/v1.0.13...v1.0.15

Fixes #40560 (includes changes from #40563)

### CODE REVIEW

**Comment by Osyotr** [comment]
Not sure what to do with `ftgl`. The version in vcpkg is ancient, many linux distributions switched to a fork but it's also unmaintained => the patch is not upstreamable.

**Comment by FrankXie05** [comment]
@Osyotr Thanks for this PR, this issue  https://github.com/microsoft/vcpkg/issues/40560 is just an internal policy issue, sourceforge installation will not affect users. We have tried to contact him to resolve this issue.

**Comment by FrankXie05** [comment]
We don't need to change it to `gitlab`.

**Comment by Osyotr** [comment]
> We don't need to change it to `gitlab`.

Both are official sources for this package. I don't see why I should spend any more time on this PR.

**Review by FrankXie05 — APPROVED** [review]

**Comment by FrankXie05** [comment]
> > We don't need to change it to `gitlab`.
> 
> Both are official sources for this package. I don't see why I should spend any more time on this PR.

This is just an internal policy issue and does not affect user usage and installation. The change to gitlab is just because this is an individual case that they have multiple upstreams. We cannot change the port of each upstream sourceforge.

**Comment by FrankXie05** [comment]
Aprove for further review.

**Pull request merged**
