### PR TITLE
[stlab] update to v1.4.1

### PR DESCRIPTION
**Pull request by kypp**
- update [stlab](http://stlab.cc/) from `1.3.3` to `1.4.1`
- update head reference to `develop` - the active development branch

### CODE REVIEW

**Comment by Rastaban** [comment]
I am seeing failures on x64-OSX with this update.  Are you able to investigate those?

**Comment by Rastaban** [comment]
It looks like it might be failing due to a missing dependency to the boost unit test framework
[config-x64-osx-dbg-err.log](https://github.com/Microsoft/vcpkg/files/3118537/config-x64-osx-dbg-err.log)

**Comment by grdowns** [comment]
It's due to Mac having a depency on `boost-optional` and `boost-variant` with this update -- not the tests. See the code block at `CMakeLists.txt:128`

**Comment by grdowns** [comment]
Adding these dependencies to the `CONTROL` file as `Build-Depends: boost-optional (osx), boost-variant (osx)` should fix this update for Mac

**Comment by kypp** [comment]
Thanks for the input - it appears only `boost-variant` is obligatory on Mac, but an additional patch was needed to exclude tests as using anything from boost implied them.

I've updated the PR with those changes

**Comment by grdowns** [comment]
Thanks for getting to the bottom of this, @kypp! Everything looks good

**Pull request merged**
