### PR TITLE
[doxygen] Updated to 1.8.17

### PR DESCRIPTION
**Pull request by tagsemb**
Doxygen 1.8.15 was no longer available from doxygen.nl, updated to current version 1.8.17.

### CODE REVIEW

**Comment by c72578** [comment]
Remark: doxygen files can also be downloaded from sourceforge in subfolders of
https://sourceforge.net/projects/doxygen/files/
e.g.:
https://sourceforge.net/projects/doxygen/files/rel-1.8.17/doxygen-1.8.17.windows.bin.zip

**Review by PhoebeHui — APPROVED** [review]
Thanks for the PR!

**Comment by c72578** [comment]
@tagsemb maybe you want to work on a separate branch concerning fmt.
Otherwise the commits will appear here in this PR. In general, it is recommended to use a separate branch for each PR and not master.

**Comment by tagsemb** [comment]
@c72578 Oh I see, thank you, I was not aware.

**Comment by tagsemb** [comment]
@c72578 Any way I can/should clean up this mess, or is it enough that I don't make the same mistake in the future? I'm new to this, and I cannot find any option to remove commits from the PR now.

**Comment by dan-shaw** [comment]
@tagsemb We squash the commits in the end so it should be okay if you add a commit to remove those changes. The `fmt` changes should be separate from the `doxygen` changes.

**Comment by tagsemb** [comment]
@dan-shaw Cheers, I've made a reverting commit to my master now that hopefully sets things right, and created a separate pull request on a separate branch for the fmt changes.

**Comment by vicroms** [comment]
Thanks for the PR!

**Pull request merged**
