### PR TITLE
[qt5-base] Fix install when `VCPKG_INSTALLED_DIR` is not absolute

### PR DESCRIPTION
**Pull request by Osyotr**
Build fails when this variable is set in `CMakePresets.json` like this:
`"VCPKG_INSTALLED_DIR": "${sourceDir}/../out/vcpkg_installed"`
The reason is that paths in makefiles are absolute, but `CURRENT_*_DIR`
is not and subsequent call to `string(REPLACE ...)` does nothing.

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
LGTM, @Neumann-A are you against this changes?

**Comment by Neumann-A** [comment]
>  @Neumann-A are you against this changes?

why should I? it just needs proper checking if it resolves the issue and if it still works as expected. E.g. also try to pass `--x-packackes-dir(?)=somepath` and see if it does what is expected.

**Comment by Neumann-A** [comment]
yeah and also try if it works with a subst correctly. Especially for qt5-webengine.

**Comment by JackBoosY** [comment]
@Osyotr  Please resolve the file conflict.

Thanks.

**Review by JackBoosY — APPROVED** [review]

**Comment by BillyONeal** [comment]
Hmmm.... should vcpkg be fixing this up before invoking portfile.cmake, or is this happening inside the port somehow?

**Comment by Osyotr** [comment]
I don't know all details about Qt's buildsystem and why do makefiles need to be patched, but it's theoretically possible that some ports generate makefiles with relative paths. In this case, correcting `VCPKG_INSTALLED_DIR` would break them.
PS: the issue is not really relevant for me anymore. First, we have `${sourceParentDir}` in CMakePresets.json. Second, using a directory outside the project folder hides it from VS CMake Targets View. I ended up setting the directory in `${sourceDir}/out/vcpkg_installed` so that rsync don't delete it from target machine (it skips everything inside `out/`).

**Comment by BillyONeal** [comment]
What I mean is, I don't think vcpkg should be giving you a non-absolute VCPKG_INSTALLED_DIR; and indeed that's what I see:

```
PS C:\Dev\vcpkg> type .\ports\billy-test\portfile.cmake
message(FATAL_ERROR "CURRENT_INSTALLED_DIR is ${CURRENT_INSTALLED_DIR}")
PS C:\Dev\vcpkg> type .\ports\billy-test\vcpkg.json                                 
{
  "name": "billy-test",
  "version": "1.0.0",
  "description": "Hello"
}
PS C:\Dev\vcpkg> .\vcpkg.exe install billy-test --x-install-root=..\relative
Computing installation plan...
The following packages will be built and installed:
    billy-test[core]:x86-windows -> 1.0.0
Detecting compiler hash for triplet x86-windows...
Restored 0 packages from C:\Users\bion\AppData\Local\vcpkg\archives in 193.2 us. Use --debug to see more details.
Starting package 1/1: billy-test:x86-windows
Building package billy-test[core]:x86-windows...
CMake Error at ports/billy-test/portfile.cmake:1 (message):
  CURRENT_INSTALLED_DIR is C:/Dev/relative/x86-windows
Call Stack (most recent call first):  scripts/ports.cmake:142 (include)
Error: Building package billy-test:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  package: billy-test[core]:x86-windows -> 1.0.0
  vcpkg version: 86027045b 2021-11-18 (11 days ago)
  vcpkg-tool version: 2021-11-15-ec76affcc987efbf172b7da0b05df711b48fa535

Additionally, attach any relevant sections from the log files above.
PS C:\Dev\vcpkg> 
```

something funny is going on?

**Comment by dg0yt** [comment]
CURRENT_INSTALLED_DIR or VCPKG_INSTALLED_DIR?

**Comment by BillyONeal** [comment]
> CURRENT_INSTALLED_DIR or VCPKG_INSTALLED_DIR?

VCPKG_INSTALLED_DIR is the input (the equivalent to `--x-install-root=` in my example except that's the manifest mode version) and should be being made absolute by the vcpkg binary before invoking `portfile.cmake`. If it's relative when we invoke `portfile.cmake` our binary has a bug.

**Comment by dg0yt** [comment]
~~~
ports/qt5-base/cmake/qt_build_submodule.cmake:        set(CURRENT_INSTALLED_DIR "./../../.." ) # Making the qt.conf relative and not absolute
~~~

**Comment by BillyONeal** [comment]
> ```
> ports/qt5-base/cmake/qt_build_submodule.cmake:        set(CURRENT_INSTALLED_DIR "./../../.." ) # Making the qt.conf relative and not absolute
> ```

😭

**Comment by BillyONeal** [comment]
> > ```
> > ports/qt5-base/cmake/qt_build_submodule.cmake:        set(CURRENT_INSTALLED_DIR "./../../.." ) # Making the qt.conf relative and not absolute
> > ```
> 
> 😭

Wait no it tries to set that back:

```
        set(CURRENT_INSTALLED_DIR_BACKUP "${CURRENT_INSTALLED_DIR}")
        set(CURRENT_INSTALLED_DIR "./../../.." ) # Making the qt.conf relative and not absolute
        configure_file(${CURRENT_INSTALLED_DIR_BACKUP}/tools/qt5/qt_release.conf ${CURRENT_PACKAGES_DIR}/tools/${PORT}/bin/qt.conf) # This makes the tools at least useable for release
        set(CURRENT_INSTALLED_DIR "${CURRENT_INSTALLED_DIR_BACKUP}") 
```

**Comment by Neumann-A** [comment]
Questions?
Also for debugging run 
`.\vcpkg.exe install billy-test --x-install-root=..\relative --x-cmake-args=--trace-expand`
and pipe into a log.

**Comment by BillyONeal** [comment]
@Osyotr Just in case it wasn't clear, I think the right change here is to fix qt ports' forgetting to set this back to the original path in the first place rather than trying to fix it up after the fact.

**Comment by BillyONeal** [comment]
> @BillyONeal It seems that every call to `set(CURRENT_INSTALLED_DIR ...)` is properly guarded. I no idea where it might break.

I think that needs to be run down / investigated rather than this fix given the concerns about undoing folks' subst and other MAX_PATH workarounds.

**Comment by JackBoosY** [comment]
Convert this PR to draft since there is no progress.

**Comment by JackBoosY** [comment]
Please temporary close this PR if you don't have spare time to finish it.

**Pull request closed without merging**
