### PR TITLE
[vtk] enables openvr module when openvr is listed

### PR DESCRIPTION
**Pull request by veggiesaurus**
This PR sets the `VTK_MODULE_ENABLE_VTK_RenderingOpenVR` flag when `openvr` is in the feature list. Previously, adding this feature did nothing other than changing the dependencies.

### CODE REVIEW

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
Hi @veggiesaurus 

Thanks for your PR.
Have you tested this feature `openvr `?

**Comment by veggiesaurus** [comment]
> Hi @veggiesaurus 
> 
> Thanks for your PR.
> Have you tested this feature `openvr `?
> 

Yes, I'm using it now. When compiling with this feature, the correct headers and libs now get copied to the install directory

**Comment by NancyLi1013** [comment]
LGTM now.

**Comment by ras0219-msft** [comment]
Thanks for the improvement!

**Pull request merged**
