### PR TITLE
[libbson] fix cmake find

### PR DESCRIPTION
**Pull request by fran6co**
Fixes this error when calling `find_package(libbson-1.0 CONFIG REQUIRED)` in linux
```
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:622 (_find_package):
  Could not find a package configuration file provided by "libbson-1.0" with
  any of the following names:

    libbson-1.0Config.cmake
    libbson-1.0-config.cmake

  Add the installation prefix of "libbson-1.0" to CMAKE_PREFIX_PATH or set
  "libbson-1.0_DIR" to a directory containing one of the above files.  If
  "libbson-1.0" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:17 (find_package)
```

### CODE REVIEW

**Comment by JackBoosY** [comment]
According to cmake provides [FindBISON.cmake](https://cmake.org/cmake/help/latest/module/FindBISON.html), we may not need to rename it's cmake configuration files.

**Comment by fran6co** [comment]
@JackBoosY this is not BISON it's BSON, CMake doesn't have a default Find script for it

**Comment by JackBoosY** [comment]
@fran6co Sorry, I got wrong.

**Review by JackBoosY — CHANGES_REQUESTED** [review]
Please bump the libbson version. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).

**Comment by fran6co** [comment]
> Please bump the libbson version. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).

@JackBoosY done

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
There are 2 libraries in _lib_ folder, both dynamic build and static build.
Are they the same?

**Comment by fran6co** [comment]
@JackBoosY  I only see 1 lib file on linux, I haven't tested on windows. Not sure why it would generate 2 of them

**Comment by fran6co** [comment]
shouldn't it generate a dll file for the dynamic build?

**Comment by JackBoosY** [comment]
@fran6co Yes.
For dynamic build:
```
libbson:/bin/bson-1.0.dll
libbson:/bin/bson-1.0.pdb
libbson:/debug/bin/bson-1.0.dll
libbson:/debug/bin/bson-1.0.pdb
libbson:/debug/lib/bson-1.0.lib
libbson:/debug/lib/libbson-1.0.lib
libbson:/debug/lib/pkgconfig/libbson-1.0.pc
libbson:/include/bson.h
libbson:/include/bson/bcon.h
libbson:/include/bson/bson-atomic.h
libbson:/include/bson/bson-clock.h
libbson:/include/bson/bson-compat.h
libbson:/include/bson/bson-config.h
libbson:/include/bson/bson-context.h
libbson:/include/bson/bson-decimal128.h
libbson:/include/bson/bson-endian.h
libbson:/include/bson/bson-error.h
libbson:/include/bson/bson-iter.h
libbson:/include/bson/bson-json.h
libbson:/include/bson/bson-keys.h
libbson:/include/bson/bson-macros.h
libbson:/include/bson/bson-md5.h
libbson:/include/bson/bson-memory.h
libbson:/include/bson/bson-oid.h
libbson:/include/bson/bson-prelude.h
libbson:/include/bson/bson-reader.h
libbson:/include/bson/bson-string.h
libbson:/include/bson/bson-types.h
libbson:/include/bson/bson-utf8.h
libbson:/include/bson/bson-value.h
libbson:/include/bson/bson-version-functions.h
libbson:/include/bson/bson-version.h
libbson:/include/bson/bson-writer.h
libbson:/include/bson/bson.h
libbson:/lib/bson-1.0.lib
libbson:/lib/libbson-1.0.lib
libbson:/lib/pkgconfig/libbson-1.0.pc
libbson:/share/libbson-1.0/libbson-1.0-config-version.cmake
libbson:/share/libbson-1.0/libbson-1.0-config.cmake
libbson:/share/libbson/THIRD_PARTY_NOTICES
libbson:/share/libbson/copyright
libbson:/share/libbson/usage
libbson:/share/libbson/vcpkg_abi_info.txt
```

For static build:
```
libbson:/debug/lib/bson-static-1.0.lib
libbson:/debug/lib/libbson-static-1.0.lib
libbson:/debug/lib/pkgconfig/libbson-1.0.pc
libbson:/debug/lib/pkgconfig/libbson-static-1.0.pc
libbson:/include/bson.h
libbson:/include/bson/bcon.h
libbson:/include/bson/bson-atomic.h
libbson:/include/bson/bson-clock.h
libbson:/include/bson/bson-compat.h
libbson:/include/bson/bson-config.h
libbson:/include/bson/bson-context.h
libbson:/include/bson/bson-decimal128.h
libbson:/include/bson/bson-endian.h
libbson:/include/bson/bson-error.h
libbson:/include/bson/bson-iter.h
libbson:/include/bson/bson-json.h
libbson:/include/bson/bson-keys.h
libbson:/include/bson/bson-macros.h
libbson:/include/bson/bson-md5.h
libbson:/include/bson/bson-memory.h
libbson:/include/bson/bson-oid.h
libbson:/include/bson/bson-prelude.h
libbson:/include/bson/bson-reader.h
libbson:/include/bson/bson-string.h
libbson:/include/bson/bson-types.h
libbson:/include/bson/bson-utf8.h
libbson:/include/bson/bson-value.h
libbson:/include/bson/bson-version-functions.h
libbson:/include/bson/bson-version.h
libbson:/include/bson/bson-writer.h
libbson:/include/bson/bson.h
libbson:/lib/bson-static-1.0.lib
libbson:/lib/libbson-static-1.0.lib
libbson:/lib/pkgconfig/libbson-1.0.pc
libbson:/lib/pkgconfig/libbson-static-1.0.pc
libbson:/share/libbson-1.0/libbson-1.0-config-version.cmake
libbson:/share/libbson-1.0/libbson-1.0-config.cmake
libbson:/share/libbson/THIRD_PARTY_NOTICES
libbson:/share/libbson/copyright
libbson:/share/libbson/usage
libbson:/share/libbson/vcpkg_abi_info.txt
```

**Comment by JackBoosY** [comment]
Pinging @fran6co  for response. Is work still being done for this PR?

**Comment by fran6co** [comment]
@JackBoosY  need to rebase and test on windows, haven't got around to check the dynamic libraries generated

**Comment by fran6co** [comment]
@JackBoosY I just tested the master version of this package on Windows and it has the same issue you described (bson-static and libbson-static being present), so this PR is not causing that behaviour. I don't have time to figure out why is doing it, but at least it's not a regression

**Comment by ras0219-msft** [comment]
This seems... a bit crazy that mongo-c-driver is looking for `bson-1.0` in one place but `libbson-1.0` in another. I think the best way to proceed might be to just provide _all the names_ and have them pull in the right one:

```cmake
# /share/bson-1.0/bson-1.0-config.cmake
include(CMakeFindDependencyMacro)
find_dependency(libbson-1.0 CONFIG)
```

**Comment by fran6co** [comment]
@ras0219-msft not sure that would work because the config files would need to be changed as well

**Review by ytbigvinny27 — APPROVED** [review]

**Comment by strega-nil-ms** [comment]
Given that libbson seems to want `libbson` to be how it's found, I'm up for just changing it; thanks @fran6co :)

**Pull request merged**
