### PR TITLE
[functions-framework-cpp] update to latest release (v0.6.0)

### PR DESCRIPTION
**Pull request by coryan**
Updates `functions-framework-cpp` to the latest release (v0.6.0)

- #### What does your PR fix?  

N/A

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  

No change.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  

Yes.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  

I think so.

### CODE REVIEW

**Comment by coryan** [comment]
I think the `gdal` and `paraview` breaks are unrelated to these changes. Should I be wrong, I am happy to make changes as needed.

**Comment by JonLiu1993** [comment]
> I think the `gdal` and `paraview` breaks are unrelated to these changes. Should I be wrong, I am happy to make changes as needed.

The `gdal` and `paraview` breaks due CI basline error,just wait CI error fixed.

**Review by JonLiu1993 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the version update!

**Pull request merged**
