### PR TITLE
[glib] update to 2.70.1

### LINKED ISSUE #19925: [glib] update to 2.69.3
Library name: glib

New version number: 2.69.3

Other information that may be useful (release notes, etc...)
https://download.gnome.org/sources/glib/
https://download.gnome.org/sources/glib/2.69/

### PR DESCRIPTION
**Pull request by Neumann-A**

### CODE REVIEW

**Comment by Neumann-A** [comment]
@BillyONeal  what happend to x64-osx? Never saw that error. 
```
Attempting to fetch 134 packages from HTTP servers.
Exception: /Users/vagrant/Data/work/1/s/scripts/azure-pipelines/test-modified-ports.ps1:199
Line |
 199 |          throw "vcpkg ci failed"
     |          ~~~~~~~~~~~~~~~~~~~~~~~
     | vcpkg ci failed

##[error]PowerShell exited with code '1'.
##[error]PowerShell wrote one or more lines to the standard error stream.
##[error]Exception: /Users/vagrant/Data/work/1/s/scripts/azure-pipelines/test-modified-ports.ps1:199
Line |
 199 |          throw "vcpkg ci failed"
     |          ~~~~~~~~~~~~~~~~~~~~~~~
     | vcpkg ci failed

```

**Comment by dg0yt** [comment]
This osx error already appeared randomly in the last weeks.

**Review by JonLiu1993 — APPROVED** [review]

**Comment by JonLiu1993** [comment]
@Neumann-A ,Thanks for your pr, I tested features locally on x64-linux triplet but failed :
````
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: /usr/bin/python3 /home/test1/vcpkg/downloads/tools/meson/meson-aeda7f249c4a5dbbecc52e44f382246a2377b5b0/meson.py -Dinstalled_tests=false -Dselinux=enabled -Dlibmount=enabled -Dtests=false -Dxattr=false -Dlibelf=disabled --buildtype plain --backend ninja --wrap-mode nodownload --native /home/test1/vcpkg/buildtrees/glib/meson-native-x64-linux.log --default-library static --libdir lib --native /home/test1/vcpkg/buildtrees/glib/meson-native-x64-linux-debug.log -Ddebug=true --prefix /home/test1/vcpkg/packages/glib_x64-linux/debug --includedir ../include -Dcmake_prefix_path=['/home/test1/vcpkg/installed/x64-linux/debug','/home/test1/vcpkg/installed/x64-linux'] /home/test1/vcpkg/buildtrees/glib/src/glib-2-3e22263b95.clean
    Working Directory: /home/vzhli17/test1/vcpkg/buildtrees/glib/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /home/test1/vcpkg/buildtrees/glib/config-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:512 (vcpkg_execute_required_process)
  ports/glib/portfile.cmake:46 (vcpkg_configure_meson)
  scripts/ports.cmake:142 (include)
````
/home/test1/vcpkg/buildtrees/glib/x64-linux-dbg:
````
../src/glib-2-3e22263b95.clean/meson.build:2077:2: ERROR: Dependency "libselinux" not found, tried pkgconfig and cmake

A full log can be found at /home/test1/vcpkg/buildtrees/glib/x64-linux-dbg/meson-logs/meson-log.txt

````
/home/test1/vcpkg/buildtrees/glib/x64-linux-dbg/meson-logs/meson-log.txt:
````
Compiler stderr:
 /home/test1/vcpkg/buildtrees/glib/x64-linux-dbg/meson-private/tmprk8e3u5r/testfile.c:4:12: error: #error "Header 'mach/mach_time.h' could not be found"
           #error "Header 'mach/mach_time.h' could not be found"
            ^~~~~

Has header "mach/mach_time.h" : NO
Running compile:
Working directory:  /home/test1/vcpkg/buildtrees/glib/x64-linux-dbg/meson-private/tmppavpsk6g
Command line:  /usr/bin/cc -I/home/test1/vcpkg/installed/x64-linux/include /home/test1/vcpkg/buildtrees/glib/x64-linux-dbg/meson-private/tmppavpsk6g/testfile.c -E -P -fPIC -g -D_FILE_OFFSET_BITS=64 -P -O0 -std=gnu99

````

**Comment by Neumann-A** [comment]
@JonLiu1993: I assume you are missing a system dependency if you want to enable feature selinux (`ERROR: Dependency "libselinux" not found, tried pkgconfig`)

`mach/mach_time.h` is a osx header according to a quick google search so it is no wonder that it is missing on linux.

**Comment by JonLiu1993** [comment]
> @JonLiu1993: I assume you are missing a system dependency if you want to enable feature selinux (`ERROR: Dependency "libselinux" not found, tried pkgconfig`)
> 
> `mach/mach_time.h` is a osx header according to a quick google search so it is no wonder that it is missing on linux.

Have you tested all features locally?

**Comment by Neumann-A** [comment]
> Have you tested all features locally?

Have you tested the current baseline with the same features?
No I cannot test everything locally, especially not osx. 
I can tell you that feature `selinux` works if the required system packages are installed

**Comment by BillyONeal** [comment]
> 

These mean that the vcpkg binary returned a nonzero exit code for some reason:

```
    & "./vcpkg$executableExtension" ci $Triplet --x-xunit=$xmlFile --exclude=$skipList --failure-logs=$failureLogs @hostArgs @commonArgs @cachingArgs @parentHashes

    $failureLogsEmpty = (-Not (Test-Path $failureLogs) -Or ((Get-ChildItem $failureLogs).count -eq 0))
    Write-Host "##vso[task.setvariable variable=FAILURE_LOGS_EMPTY]$failureLogsEmpty"

    if ($LASTEXITCODE -ne 0)
    {
        throw "vcpkg ci failed"
    }
```

> This osx error already appeared randomly in the last weeks.

Hmmm I have not seen yet. Is it always the same build node or something else?

**Comment by BillyONeal** [comment]
Thanks for the update!

**Comment by dg0yt** [comment]
> Hmmm I have not seen yet. Is it always the same build node or something else?

@BillyONeal  Where do I see the node? Yesterday:
https://dev.azure.com/vcpkg/public/_build/results?buildId=63849&view=logs&j=7b75bd19-17d3-53d4-00fd-23f1a49a8ba4&t=a23dba4e-3a62-59dc-a73c-a7222676d7a4
https://dev.azure.com/vcpkg/public/_build/results?buildId=63847&view=logs&j=7b75bd19-17d3-53d4-00fd-23f1a49a8ba4&t=a23dba4e-3a62-59dc-a73c-a7222676d7a4

**Comment by BillyONeal** [comment]
> @BillyONeal Where do I see the node?

If you click on 'x64-osx' on those links it shows the node in the output window:

image

Both those examples ran on vcpkg-eg-mac-06 which suggests that that one is unhealthy. I disabled it for now

**Comment by BillyONeal** [comment]
I `vagrant destroy && vagrant up`'d -06 so it should be back.

**Pull request merged**
