### PR TITLE
[halide]Upgrade to release_2019_08_27.

### PR DESCRIPTION
**Pull request by JackBoosY**
Upgrade to release_2019_08_27 using [#4173](https://github.com/halide/Halide/issues/4173) recommendations.

Related: #7838.

### CODE REVIEW

**Comment by JackBoosY** [comment]
Seems failure with:
```
CMake Error at tools/llvm-dwp/cmake_install.cmake:41 (file):
  file INSTALL cannot copy file
  "/mnt/buildtrees/llvm/x64-linux-dbg/bin/llvm-dwp" to
  "/home/vcpkg/myagent/_work/4/s/packages/llvm_x64-linux/debug/tools/llvm/llvm-dwp".
Call Stack (most recent call first):
  tools/cmake_install.cmake:68 (include)
  cmake_install.cmake:63 (include)
```

What's wrong with this file? It may be a fake error.

**Comment by JackBoosY** [comment]
@grdowns  ping.

**Comment by JackBoosY** [comment]
llvm report errors:
```
Creating llvm-ranlib.exe
Creating llvm-lib.exe
Creating llvm-dlltool.exe
Creating clang++.exe
Error copying file "clang.exe" to "clang++.exe".
Creating clang-cl.exe
Error copying file "clang.exe" to "clang-cl.exe".
Creating clang-cpp.exe
Error copying file "clang.exe" to "clang-cpp.exe".
Creating llvm-strip.exe
Creating llvm-readelf.exe
```
Llvm has no dependencies on halide.

**Comment by JackBoosY** [comment]
Ready to merge.

**Comment by grdowns** [comment]
Hey! Sorry I haven't been able to provide feedback on this PR up until this point. This looks good. Thanks for the update, @JackBoosY!

**Pull request merged**
