### PR TITLE
[vcpkg] [cuda] minor fixes for cuda and vcpkg

### PR DESCRIPTION
**Pull request by simogasp**
**Describe the pull request**

- What does your PR fix?

* ~~it fixes the initialization order of some class attributes for vcpkg, clang raise an error (and ISO C++ requires field designators to be specified in declaration order)~~ done in #11239

* ~~minor improvement in cuda port, extract the version directly from the nvcc pattern VX.Y.Z and compare to declared variable `CUDA_REQUIRED_VERSION` instead of performing a check with hardcoded values. This improves maintainability, next time the required version is changed, it has to be changed in only one place.~~ see  #11322 

- Which triplets are supported/not supported? Have you updated the CI baseline?
No changes in terms of supported triplets

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

### CODE REVIEW

**Comment by LilyWangL** [comment]
Thanks for your PR! Can you please correct the Version field in the `cuda` CONTROL file? You can get more information from [maintainer-guide.md](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md).

**Comment by simogasp** [comment]
@LilyWangL oops my bad, done in 021cf61
(and sorry if I mixed 2 different topics in a single PR, but they are very minor fixes so I figured that it was not worth it)

**Review by LilyWangL — APPROVED** [review]

**Comment by cenit** [comment]
Similar to #11322 for the CUDA part?

**Comment by simogasp** [comment]
yes, but IMHO it's better to have a single variable CUDA_REQUIRED_VERSION rather than CUDA_MAJOR etc.
If you agree you can apply the small changes of this PR to yours and I'll drop mines here.

**Comment by simogasp** [comment]
(and thanks for pointing it out, I should have checked open PRs before)

**Comment by cenit** [comment]
You can apply a review in the changes tab of my pr, and I will gladly accept it. Otherwise I can do it later

**Comment by simogasp** [comment]
I'm closing this pr because one contribution is already merged in #11239 and the other has been moved into #11322

**Pull request closed without merging**
