### PR TITLE
[libmesh] Fix Windows build

### PR DESCRIPTION
**Pull request by mkhon**
**Describe the pull request**
- update to the master w/ Windows build patches

- #### What does your PR fix?  
libmesh build on Windows

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
Yes. I haven't changed ci.baseline.txt as there are still issues with conflicting files installed by libmesh port which should be handled in a separate PR

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by mkhon** [comment]
Most of the changes in the new patches are submitted upstream:
- libMesh/libmesh#3144
- libMesh/libmesh#3135

**Review by JackBoosY — CHANGES_REQUESTED** [review]
Please remove all the content related to libmesh:WIN_TRIPLET in _VCPKG_ROOT/scripts/ci.baseline.txt_.

**Comment by JackBoosY** [comment]
Waiting for the upstream approval.

**Comment by mkhon** [comment]
> Please remove all the content related to libmesh:WIN_TRIPLET in _VCPKG_ROOT/scripts/ci.baseline.txt_.

@JackBoosY this requires more work as the port installs conflicting files:

```
The following files are already installed in C:/vcpkg/installed/x64-windows-release and are in conflict with libmesh:x64-windows-release

Installed by netcdf-c:x64-windows-release
    include/netcdf.h
    include/netcdf_aux.h
    include/netcdf_mem.h
    include/netcdf_meta.h
    lib/libnetcdf.settings
    lib/netcdf.lib
    lib/pkgconfig/netcdf.pc
```

And there are more (see scripts/ci.baseline.txt entries for this port)

**Comment by JackBoosY** [comment]
> > Please remove all the content related to libmesh:WIN_TRIPLET in _VCPKG_ROOT/scripts/ci.baseline.txt_.
> 
> @JackBoosY this requires more work as the port installs conflicting files:
> 
> ```
> The following files are already installed in C:/vcpkg/installed/x64-windows-release and are in conflict with libmesh:x64-windows-release
> 
> Installed by netcdf-c:x64-windows-release
>     include/netcdf.h
>     include/netcdf_aux.h
>     include/netcdf_mem.h
>     include/netcdf_meta.h
>     lib/libnetcdf.settings
>     lib/netcdf.lib
>     lib/pkgconfig/netcdf.pc
> ```
> 
> And there are more (see scripts/ci.baseline.txt entries for this port)

So you should change `fail` to `skip` in _ci.baseline.txt_ and add comment.

**Comment by mkhon** [comment]
> So you should change `fail` to `skip` in _ci.baseline.txt_ and add comment.

@JackBoosY have you checked the source code before giving the advices and marking the port as requires:author-response?

The port is already marked as 'skip' in ci.baseline.txt with the appropriate comments

**Comment by JackBoosY** [comment]
> > So you should change `fail` to `skip` in _ci.baseline.txt_ and add comment.
> 
> @JackBoosY have you checked the source code before giving the advices and marking the port as requires:author-response?
> 
> The port is already marked as 'skip' in ci.baseline.txt with the appropriate comments

Ah sorry, they were marked skip. This must be my memory messed up.

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
The upstream approved this changes.

**Review by ras0219-msft — CHANGES_REQUESTED** [review]
Thanks for the PR!

I see that upstream has approved and merged https://github.com/libMesh/libmesh/pull/3135, and tacitly has approved https://github.com/libMesh/libmesh/pull/3144, however there is still a significant amount of patching in this PR that hasn't been submitted upstream (as far as I can tell).

I'd really like to see the patches in this PR reduced to pulling diffs from the libmesh GitHub, for example:
```
vcpkg_download_distfile(
    PATCH1
    URLS "https://patch-diff.githubusercontent.com/raw/libMesh/libmesh/pull/3135.diff"
    SHA512 ...
    FILENAME libmesh-3135.diff
)
# ${PATCH1} is the location of the downloaded patch and can be passed to PATCHES in vcpkg_from_github()
```
(You can also get an individual commit: https://github.com/libMesh/libmesh/commit/ac5ebe88de3c15a51b9cf79ad5e8c5244beb6337.diff)

That helps us by ensuring (by construction) that upstream has everything for evaluation and that we aren't checking large amounts of code into the vcpkg registry.

**Comment by mkhon** [comment]
@ras0219-msft libMesh/libmesh#3144 has been merged
Additionally, libMesh/libmesh#3147 and libMesh/libmesh#3148 have been merged to libmesh master as well (so the only remaining patches are contrib/ patches which will unlikely to be accepted (see libMesh/libmesh#3149), but they are minor and trivial.

Unfortunately, patches for merged PRs can not be taken from libmesh github as they are done against master (so we will need to update libmesh version first).

I would suggest to merge this PR as is, then when we will update libmesh version we can remove merged patches.

**Comment by BillyONeal** [comment]
>Unfortunately, patches for merged PRs can not be taken from libmesh github as they are done against master (so we will need to update libmesh version first).

Personally I would prefer to do that update first. I tried to do so but ran into

> configure: error: You must run "git submodule update --init --recursive" before configuring libmesh

I'm assuming @ras0219-msft tagged this because normally we would not accept patches of this magnitude, but the reason we normally won't accept them is because we are worried about updates and "owning" the consequences of those patches. Seeing that they are already merged upstream mitigates that concern. Even so the patches are huge and may even be scary for licensing reasons.

Hopefully we should have an answer for you on Thursday.

**Comment by BillyONeal** [comment]
We discussed this "in person" today and agreed that we would like to see an update to the current shipping copy of libMesh before attempting to apply these patches, with the hope that that means the patches actually applied upstream will apply cleanly.

Because 1.6.2 has submodules that need to be fixed up, if you're interested in tackling that you'll need to call `vcpkg_from_github` multiple times and rename the resulting bits into place; for an example, check out what gstreamer is doing:

https://github.com/microsoft/vcpkg/blob/805811e16a84a845e1f1c19b8a64b1612d4a7706/ports/gstreamer/portfile.cmake#L19-L63

**Comment by BillyONeal** [comment]
@ras0219-msft also indicates that the release tarball (which you'd get with `vcpkg_download_distfile`) may already have the right submoduled content included.

**Comment by JackBoosY** [comment]
Ping for response.

**Comment by mkhon** [comment]
There is an issue with linking libmesh after I updated to the latest libmesh (with Windows build fixes)

**Comment by JackBoosY** [comment]
@mkhon Can you please provide the failure logs?

**Comment by JackBoosY** [comment]
Ping for response again.

**Comment by JackBoosY** [comment]
Closing this PR since it seems that no progress is being made. Please reopen if work is still being done.

**Pull request closed without merging**
