### PR TITLE
[3DSTKNativeServer] Initial Port

### PR DESCRIPTION
**Pull request by KanishkT123**
Hello,

This is a port of the 3D Streaming Toolkit V2.0.

### CODE REVIEW

**Comment by KanishkT123** [comment]
I changed the distfile downloading so it goes through the vcpkg distfile download command and has SHA512 checks.

**Comment by anderm** [comment]
Hi all, we are in the process of finishing a couple of blog posts for the toolkit and having a vcpkg would be a massive help for our partners! Can we please get some guidance if this is GTG or if it's missing anything? Many thanks for your help

**Comment by Cheney-W** [comment]
@KanishkT123 , This port failed with following error:
File does not have expected hash:

      Expected hash: [ b5fe6d1cf5bae83e50ee2c46f0b2e44433a418ec344390819d8b3d1b6a8f32100efb6984d31ea1c88e66f0247d99963d9744e359e93ff0b91e26d8d826285c4c ]
        Actual hash: [ f37a18e4164a6a1f6ceea50f56052a63b361fcb3fc2f6b8345c85b2acb63ceaa3cf65952b5672be746ae8ce140dd743517eceaf2b13d67a7933d456d6159bf1b ]

**Comment by cbezault** [comment]
I'm working to get this PR into vcpkg and was wondering if the .zip files downloaded are going to change regularly? They don't appear versioned and so I assume will be updated to latest on a regular basis. Any changes to those files will break this port for everyone as their hash will change. Is there any possibility of pointing to a more static file?

**Comment by ras0219-msft** [comment]
Closing for inactivity. Thanks for the PR and please let us know if we should reopen it!

**Pull request closed without merging**
