### PR TITLE
parmetis

### LINKED ISSUE #430: Add Parmetis
Hi!

It would be great if you add Parmetis.

Link:
http://glaros.dtc.umn.edu/gkhome/metis/parmetis/download

Thanks in advance!

### PR DESCRIPTION
**Pull request by albertziegenhagel**
Adds a port for parmetis (http://glaros.dtc.umn.edu/gkhome/metis/parmetis/overview)

fixes #430 

Requires #516 to merged first.

### CODE REVIEW

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by alexkaratarakis** [comment]
I was unable to test this because http://glaros.dtc.umn.edu is inaccessible at the moment.

**Comment by albertziegenhagel** [comment]
From my experience it happens quite often that their website is down. I found a mirror for the package at a location that seems to be the source archive for ubuntu packages:

https://launchpad.net/ubuntu/+archive/primary/+files/parmetis_4.0.3.orig.tar.gz

Should I add this to the port file as a mirror or should we prefer to have "original" sources in the port files only?

(for metis there is a package available from fedora located at
http://pkgs.fedoraproject.org/repo/pkgs/metis/metis-5.1.0.tar.gz/5465e67079419a69e0116de24fce58fe/metis-5.1.0.tar.gz)

**Comment by alexkaratarakis** [comment]
The SHA-512 hash can verify that the package is exactly the same as the original, so the launchpad mirror could definitely work.
However, the current link is working now and the port works so I am merging this. We can consider a mirror if the issue arises again. 

Thanks for the solid port!

**Pull request merged**
