### PR TITLE
[vtk] Added opengl feature.

### PR DESCRIPTION
**Pull request by larshg**
**Describe the pull request**
Adds opengl feature.

Change description of feature: all.

- Which triplets are supported/not supported? Have you updated the CI baseline?
all, no.
- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
yes.

### CODE REVIEW

**Review by NancyLi1013 — COMMENTED** [review]
Could you please update this 
```
file(COPY ${SOURCE_PATH}/Copyright.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/vtk)
file(RENAME ${CURRENT_PACKAGES_DIR}/share/vtk/Copyright.txt ${CURRENT_PACKAGES_DIR}/share/vtk/copyright)
```
as
`file(INSTALL ${SOURCE_PATH}/Copyright.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)`?

**Comment by larshg** [comment]
Updated.

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
Thanks for your update.
Needs to test the features now. I will update the test results once finished.

**Comment by NancyLi1013** [comment]
The feature tests are blocked by `icu`
```
warning: make-4.3-1 is up to date -- skipping
error: could not open file /var/cache/pacman/pkg/libgdbm-1.18.1-3-x86_64.pkg.tar.zst: Child process exited with status 127
error: could not open file /var/cache/pacman/pkg/gdbm-1.18.1-3-x86_64.pkg.tar.zst: Child process exited with status 127
error: failed to commit transaction (cannot open package file)
```
So we need to fix this issue first.

**Comment by NancyLi1013** [comment]
@larshg 
The problem caused by `icu `has been resolved. 
Could you please merge the latest commit to this PR?

**Comment by larshg** [comment]
Isn't a rebase the preferred way?

**Comment by NancyLi1013** [comment]
I will update this on my local to test features.
You won't merge it any more.

**Comment by NancyLi1013** [comment]
Hi @larshg 
Sorry for the long delay.  
Could you please look into the following problems?

The features build failed on x64-windows triplet:

The feature `all` is broken due to this:
```
CMake Error at CMake/vtkDownload.cmake:8 (message):
  Attempted to download Module_MomentInvariants when VTK_FORBID_DOWNLOADS is
  ON
Call Stack (most recent call first):
  CMake/vtkModuleRemote.cmake:142 (vtk_download_attempt_check)
  Remote/MomentInvariants.remote.cmake:5 (vtk_fetch_module)
  Remote/CMakeLists.txt:9 (include)
```
The feature `qt, atlmfc, openvr ,paraview` is broken due to this:
```
CMake Error at ThirdParty/hdf5/CMakeLists.txt:26 (message):
  An external MPI-aware HDF5 requires that VTK be built with MPI support as
  well.
```
The feature `python` is broken due to this:
```
CMake Error at CMake/vtkModule.cmake:4140 (message):
  Could not find the Python3 external dependency.
Call Stack (most recent call first):
  Utilities/Python/CMakeLists.txt:49 (vtk_module_find_package)
```

The feature `mpi` is broken due to this:
```
CMake Error at CMake/vtkModule.cmake:959 (message):
  The VTK::IOParallelNetCDF module requires the disabled module VTK::mpi.
Call Stack (most recent call first):
  CMakeLists.txt:251 (vtk_module_scan)
```

**Comment by larshg** [comment]
All of those features seems to be unrelated to the opengl features? So those features has stopped working since VTK 9 was first added by @Neumann-A ?
I don't really have the time nor knowledge to look into these errors :(

**Comment by NancyLi1013** [comment]
@larshg 

Thanks for your instant reply. 

`opengl `is also broken due to this

```
-- Found OpenGL: opengl32  found components: OpenGL 
-- vtkDICOM: Building vtkDICOM as a Remote VTK Module
CMake Error at ThirdParty/hdf5/CMakeLists.txt:26 (message):
  An external MPI-aware HDF5 requires that VTK be built with MPI support as
  well.
```
I will check this on the master later.

**Comment by Neumann-A** [comment]
>-- vtkDICOM: Building vtkDICOM as a Remote VTK Module
CMake Error at ThirdParty/hdf5/CMakeLists.txt:26 (message):
  An external MPI-aware HDF5 requires that VTK be built with MPI support as
  well.

VTK needs to pass `-DVTK_GROUP_ENABLE_MPI=YES` which it does:
```
if("mpi" IN_LIST FEATURES)
    list(APPEND ADDITIONAL_OPTIONS
        -DVTK_GROUP_ENABLE_MPI=YES
    )
endif()
```

Maybe we need to also pass `-DVTK_USE_MPI=ON`

**Comment by larshg** [comment]
I have just rebased on master an rebuild vtk[opengl] but didn't encounter any errors?

**Comment by NancyLi1013** [comment]
@larshg 
Feature `opengl` is broken on x64-windows:
```
-- vtkDICOM: Building vtkDICOM as a Remote VTK Module
CMake Error at ThirdParty/hdf5/CMakeLists.txt:26 (message):
  An external MPI-aware HDF5 requires that VTK be built with MPI support as
  well.
```
After add `-DVTK_USE_MPI=ON`, the error is like this:
```
CMake Error at F:/11399/vcpkg/scripts/buildsystems/vcpkg.cmake:252 (_add_library):
  Target "IONetCDF" links to target "MPI::MPI_C" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  CMake/vtkModule.cmake:3328 (add_library)
  IO/NetCDF/CMakeLists.txt:10 (vtk_module_add_module)


CMake Error at F:/11399/vcpkg/scripts/buildsystems/vcpkg.cmake:252 (_add_library):
  Target "IOParallelNetCDF" links to target "MPI::MPI_C" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMake/vtkModule.cmake:3328 (add_library)
  IO/ParallelNetCDF/CMakeLists.txt:14 (vtk_module_add_module)


CMake Error at F:/11399/vcpkg/scripts/buildsystems/vcpkg.cmake:252 (_add_library):
  Target "IOMINC" links to target "MPI::MPI_C" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
Call Stack (most recent call first):
  CMake/vtkModule.cmake:3328 (add_library)
  IO/MINC/CMakeLists.txt:15 (vtk_module_add_module)


CMake Error at F:/11399/vcpkg/scripts/buildsystems/vcpkg.cmake:252 (_add_library):
  Target "exodusII" links to target "MPI::MPI_C" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  CMake/vtkModule.cmake:3328 (add_library)
  ThirdParty/exodusII/vtkexodusII/CMakeLists.txt:300 (vtk_module_add_module)


CMake Error at F:/11399/vcpkg/scripts/buildsystems/vcpkg.cmake:252 (_add_library):
  Target "IOExodus" links to target "MPI::MPI_C" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  CMake/vtkModule.cmake:3328 (add_library)
  IO/Exodus/CMakeLists.txt:18 (vtk_module_add_module)
```

**Comment by larshg** [comment]
Do you install it with other features enabled as well? I'm on x64-windows and I don't encounter those errors?

**Comment by larshg** [comment]
image

**Comment by larshg** [comment]
Ah, maybe I haven't got an `MPI-aware HDF5` installed...

**Comment by larshg** [comment]
This is my hdf5:
image

So this error is probably also present if you just try to install vtk without opengl feature?

**Comment by NancyLi1013** [comment]
I just try to install `vck[opengl]:x64-windows`, and it will fail due to the errors.

**Comment by larshg** [comment]
On a clean machine or do you have multiple features installed from hdf5 (specially the parallel feature which adds MPI).

**Comment by NancyLi1013** [comment]
I try to build it on a clean machine and there are no any errors on x64-windows.
Have you tested it on other triplets?

**Comment by larshg** [comment]
No, I work only on x64-windows with dynamic libraries.
I thought this is why we have CI's running various systems/configs :-)

**Comment by NancyLi1013** [comment]
Thanks for your update. I will continue to test other triplets.

**Comment by NancyLi1013** [comment]
Feature `opengl` has passed with the following triplets:
- x86-windows
- x64-windows
- x64-windows-static

Note: Other features are not changed.

**Comment by vicroms** [comment]
Thanks for the hard work!

**Pull request merged**
