### PR TITLE
[vcpkg] Update CMake to 3.25.0

### PR DESCRIPTION
**Pull request by Neumann-A**
required for updating VTK

### CODE REVIEW

**Comment by Neumann-A** [comment]
ogre:arm64-windows:
```
CMake Error at Components/Bites/CMakeLists.txt:186 (qt6_wrap_cpp):
  Unknown CMake command "qt6_wrap_cpp".
```
looks like a baseline issue since `depend-info ogre[*]` doesn't show a qt dependency at all.

**Comment by dg0yt** [comment]
> (probably #27979)

That's the plan.

**Comment by Neumann-A** [comment]
x64-linux: Failing libssh. Probably solved by #27973

**Comment by Neumann-A** [comment]
x64-windows-static-md:
```
FAILED: bin/solid-hardware5.exe 
cmd.exe /C "cd . && D:\downloads\tools\cmake-3.25.0-windows\cmake-3.25.0-windows-i386\bin\cmake.exe -E vs_link_exe --intdir=src\tools\solid-hardware\CMakeFiles\solid-hardware5.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MICROS~1\2022\ENTERP~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\link.exe  @CMakeFiles\solid-hardware5.rsp  /out:bin\solid-hardware5.exe /implib:lib\solid-hardware5.lib /pdb:bin\solid-hardware5.pdb /version:0.0 /machine:x64 /nologo    /debug /INCREMENTAL /subsystem:console  && cd ."
LINK Pass 1: command "C:\PROGRA~1\MICROS~1\2022\ENTERP~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\link.exe @CMakeFiles\solid-hardware5.rsp /out:bin\solid-hardware5.exe /implib:lib\solid-hardware5.lib /pdb:bin\solid-hardware5.pdb /version:0.0 /machine:x64 /nologo /debug /INCREMENTAL /subsystem:console /MANIFEST /MANIFESTFILE:src\tools\solid-hardware\CMakeFiles\solid-hardware5.dir/intermediate.manifest src\tools\solid-hardware\CMakeFiles\solid-hardware5.dir/manifest.res" failed (exit code 1120) with the following output:
   Creating library lib\solid-hardware5.lib and object lib\solid-hardware5.exp
libimobiledevice-1.0.lib(idevice.c.obj) : error LNK2019: unresolved external symbol usbmuxd_subscribe referenced in function idevice_event_subscribe
```
looks also like a hidden dep to me cc @wrobelda

```
[8/1670] C:\PROGRA~1\MICROS~1\2022\ENTERP~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\cl.exe   /TP -DH5_BUILT_AS_STATIC_LIB -DOSG_LIBRARY_STATIC -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -ID:\buildtrees\osg\x64-windows-static-md-dbg\include -ID:\buildtrees\osg\src\raph-3.6.5-41fa3cfd98.clean\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /W4 /wd4589 /wd4706 /wd4127 /wd4100 /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /Fosrc\osg\CMakeFiles\osg.dir\AlphaFunc.cpp.obj /Fdsrc\osg\CMakeFiles\osg.dir\osg.pdb /FS -c D:\buildtrees\osg\src\raph-3.6.5-41fa3cfd98.clean\src\osg\AlphaFunc.cpp
FAILED: src/osg/CMakeFiles/osg.dir/AlphaFunc.cpp.obj 
C:\PROGRA~1\MICROS~1\2022\ENTERP~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\cl.exe   /TP -DH5_BUILT_AS_STATIC_LIB -DOSG_LIBRARY_STATIC -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -ID:\buildtrees\osg\x64-windows-static-md-dbg\include -ID:\buildtrees\osg\src\raph-3.6.5-41fa3cfd98.clean\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /W4 /wd4589 /wd4706 /wd4127 /wd4100 /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /Fosrc\osg\CMakeFiles\osg.dir\AlphaFunc.cpp.obj /Fdsrc\osg\CMakeFiles\osg.dir\osg.pdb /FS -c D:\buildtrees\osg\src\raph-3.6.5-41fa3cfd98.clean\src\osg\AlphaFunc.cpp
cl : Command line warning D9025 : overriding '/W3' with '/W4'
D:\buildtrees\osg\src\raph-3.6.5-41fa3cfd98.clean\include\osg/GLExtensions(323): error C2061: syntax error: identifier 'GLint64'
D:\buildtrees\osg\src\raph-3.6.5-41fa3cfd98.clean\include\osg/GLExtensions(324): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\buildtrees\osg\src\raph-3.6.5-41fa3cfd98.clean\include\osg/GLExtensions(324): error C2143: syntax error: missing ',' before '*'
``` 
looks like a opengl header define conflict. 

None of the observed failures seems to be related to this PR and are all baseline issues.

**Comment by JonLiu1993** [comment]
Depends on PR https://github.com/microsoft/vcpkg/pull/27973

**Review by JonLiu1993 — APPROVED** [review]

**Pull request merged**
