### PR TITLE
[soci] update to 4.0.2

### LINKED ISSUE #17692: [soci] update to 4.0.2
Library name: soci

New version number: 4.0.2

https://github.com/SOCI/soci/releases/tag/v4.0.2

### PR DESCRIPTION
**Pull request by JonLiu1993**
Fix #17692

Update soci to the latest version 4.0.2

Feature mysql test successfully in :
- x64-windows
- x64-windows-static

other features are tested successfully in the following triplet:
- x86-windows
- x64-windows
- x64-windows-static

### CODE REVIEW

**Comment by JonLiu1993** [comment]
The tensorflow failures would be fixed by PR #19165
```
You have bazel 4.1.0 installed.
Please downgrade your bazel installation to version 3.99.0 or lower to build TensorFlow!
```

**Review by NancyLi1013 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the version update!

**Pull request merged**
