### PR TITLE
[glslang] Bump version to 11.11.0

### LINKED ISSUE #26670: [glslang] update to 11.11.0
Library name: glslang

New version number: 11.11.0

Other information that may be useful (release notes, etc...)
A new version of glslang came out 22 days ago, and I'd love to use it! I specifically wanted the TShader::setOverrideVersion method

### PR DESCRIPTION
**Pull request by GabeRundlett**
Quick bump of glslang to 11.11.0

- #### What does your PR fix?
  glslang no longer out-of-date

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  All the ones it supported before (I think this is all)

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  No, I didn't know this existed. I did it the old fashioned way where I manually updated the version json

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**
I guess I will open as a draft, since I am not sure it's right

### CODE REVIEW

**Comment by GabeRundlett** [comment]
It appears the build error is due to some patch that I have no clue about. I tried going through the process of getting it to build locally so that I don't have to go through the build server, but I wasn't able to figure out how to do that. It just appears to want to build the 11.8.0 version instead.

Also I should probably mention issue #26670, which I opened earlier about doing this exact thing.

**Comment by GabeRundlett** [comment]
The issue now appears to be related to another port which depends on `glslang`. `shaderc` links to it, I guess, but I don't really understand how. The thing is, glslang was just recently updated to provide its own -config file, so now the targets that it provides are different.

In that same vein, installing glslang on the command line still says that it provides the following targets, but this isn't true anymore.
All the targets that glslang provides are now prefixed with glslang::*, so that may have something to do with shaderc not being able to link against glslang anymore.
```
[build]     # this is heuristically generated, and may not be correct
[build]     find_package(glslang CONFIG REQUIRED)
[build]     # note: 16 additional targets are not displayed.
[build]     target_link_libraries(main PRIVATE HLSL SPIRV glslang OGLCompiler)
```

Within a test repo, when attempting to consume and properly utilize glslang, I was able to successfully link my project using the following:
```
target_link_libraries(main PRIVATE
    glslang::HLSL
    glslang::SPIRV
    glslang::glslang
    glslang::OGLCompiler
)
```

**Comment by GabeRundlett** [comment]
LETS GOOO

**Comment by GabeRundlett** [comment]
I read on some other PR that a PR must change just 1 port, but the problem here is that shaderc appears to just use latest glslang. I noticed my changes *probably* should add a new shaderc version, so I modified the version json and baseline, but I don't get why I should open a new PR and ask for this one to be merged despite it breaking shaderc.

So ATM, this PR both updates glslang, and updates the shaderc port to be compatible with the new glslang version.
In reality, what I assume should be done is fix shaderc to somehow reference a specific version of glslang, but it seems like that's not what you guys like to do - I didn't see any overrides

Any assistance would be appreciated

**Comment by Cheney-W** [comment]
Local testing is in progress.

**Comment by GabeRundlett** [comment]
I was wondering if there was anything I need to do in order to get this through.
What does "local testing" mean?
Are there any resources (besides the maintainer guide) that I could read up on in order to have a more succinct testing process and making better PRs in the future?

**Comment by Cheney-W** [comment]
The local test I mentioned is to verify that the usage information given after the `glslang` installation you mentioned does not match the actual usage. I am trying to fix this issue.

**Comment by Cheney-W** [comment]
Please add these two files in your `ports\glslang` folder:
[usage.zip](https://github.com/microsoft/vcpkg/files/9524187/usage.zip)

**Comment by GabeRundlett** [comment]
Alright, I added those files to the port folder!

**Comment by GabeRundlett** [comment]
Do I need to do something to merge this? Or will it be merged by one of you?

**Comment by Cheney-W** [comment]
No, just wait for it to be merged.

**Pull request merged**
