### PR TITLE
Update proxygen to 2021.05.31.00

### LINKED ISSUE #18093: [proxygen] update to v2021.05.24.00
Library name: proxygen

New version number: v2021.05.24.00

The proxygen library has not been updated in a while. It would be nice to get the latest version.

### PR DESCRIPTION
**Pull request by electron271**
**Describe the pull request**

- #### What does your PR fix?  
  Fixes #18093

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
 all but windows

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Still working on this PR

### CODE REVIEW

**Comment by electron271** [comment]
Please ignore the branch name..

**Comment by autoantwort** [comment]
Also done as part of #17335

**Comment by electron271** [comment]
Tried building on x64_linux triplet, got this error:
```
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: /home/electron271/development/vcpkg/downloads/tools/cmake-3.20.2-linux/cmake-3.20.2-linux-x86_64/bin/cmake --build . --config Debug --target install -- -v -j13
    Working Directory: /home/electron271/development/vcpkg/buildtrees/proxygen/x64-linux-dbg
    See logs for more information:
      /home/electron271/development/vcpkg/buildtrees/proxygen/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:104 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/proxygen/portfile.cmake:31 (vcpkg_install_cmake)
  scripts/ports.cmake:139 (include)


Error: Building package proxygen:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: proxygen:x64-linux
  Vcpkg version: 2021-05-05-unknownhash
```

**Comment by autoantwort** [comment]
I think you can close this PR, I have fixed the error in #17335

**Pull request closed without merging**
