### PR TITLE
Add shaderc.

### PR DESCRIPTION
**Pull request by vlj**
Shaderc is a wrapper around glslang. It doesn't provide any lib afaik.

### CODE REVIEW

**Comment by ras0219-msft** [comment]
I'm a bit concerned that this is cloning and building a (potentially) different version of glslang than the `glslang` package.

Looking at [1], we may be able to drop a `CMakeLists.txt` into the third-party directory that simply "imports" the prebuilt binaries for glslang. I think this would look something like
```
find_library(GLSLANG glslang)
add_library(glslang IMPORTED)
set_target_properties(glslang PROPERTIES IMPORTED_IMPLIB ${GLSLANG})
```

[1] https://github.com/google/shaderc/blob/master/third_party/CMakeLists.txt#L26

**Comment by vlj** [comment]
I'm trying to import glslang shaderc but I'm running into various issues. Some glslang private includes and glslang seem not to be properly linked.
I'm wondering if it would not be better to merge glslang and shaderc since glslang can be built as part of shaderc.

**Comment by ras0219-msft** [comment]
The problem with merging them into a single package is that they ship at different rates from different organizations (thus also have different version numbers). I'll take a stab at adding some import code and come back with my results.

**Comment by vlj** [comment]
For what it worths I added the following copy code in glslang's port file to handle the includes requested by shaderc :
`file(COPY "${CURRENT_BUILDTREES_DIR}/src/glslang/Public" DESTINATION ${CURRENT_PACKAGES_DIR}/include/glslang)
file(COPY "${CURRENT_BUILDTREES_DIR}/src/glslang/Include" DESTINATION ${CURRENT_PACKAGES_DIR}/include/glslang)
file(COPY "${CURRENT_BUILDTREES_DIR}/src/glslang/MachineIndependent/Versions.h" DESTINATION ${CURRENT_PACKAGES_DIR}/include/glslang/MachineIndependent)
file(COPY "${CURRENT_BUILDTREES_DIR}/src/SPIRV/Logger.h" DESTINATION ${CURRENT_PACKAGES_DIR}/include/SPIRV)
file(COPY "${CURRENT_BUILDTREES_DIR}/src/SPIRV/spirv.hpp" DESTINATION ${CURRENT_PACKAGES_DIR}/include/SPIRV)
file(COPY "${CURRENT_BUILDTREES_DIR}/src/SPIRV/GlslangToSpv.h" DESTINATION ${CURRENT_PACKAGES_DIR}/include/SPIRV)`

Unfortunatly I'm getting some strange issue as cmake script fails to run a python script (despite python_exe being properly defined) and to link against glslang (it tries to link against glslang_NOT_FOUND.lib but again glslang path seems to be correctly determined.)

**Comment by vlj** [comment]
Actually the python script is fetching the spirv and glslang source code for a version number and fill build-version.inc. I think manually providing the build-version.inc may fix the issue.

**Comment by vlj** [comment]
I tried to fix as many things as possible in this branch : https://github.com/vlj/vcpkg/tree/shaderc-fix
Unfortunatly I'm hitting a lot of linking errors (LNK2038, LNK2005) about duplicate symbols and different linkeage.

**Comment by vlj** [comment]
I finally fixed it. This ports use the currently installed glslang lib to build shaderc.

**Comment by ras0219-msft** [comment]
Thanks for fixing that issue!

Tweaks I applied while merging:
- I bumped the version of glslang to indicate that the installed files are different.
- Enabled dynamic CRT support for shaderc. It still doesn't build as a DLL, but at least now when building `x86-windows` you can link it into your application successfully without hitting CRT conflicts.
- Added an explicit search for `python3`. The internal `shaderc` build assumes python3 is available, so I call out to `vcpkg_find_acquire_program(PYTHON3)` which will "do the right thing". Users who have python3 installed will get it added to the local build's PATH, users who don't have python3 will automatically get a portable version in `downloads\`.

**Pull request merged**
