### PR TITLE
[doc] Fix spelling errors

### PR DESCRIPTION
**Pull request by dg0yt**
This PR fixes spelling errors in the documentation. The errors were found by `codespell`.

I have a second commit locally, updating the documentation headers of
- scripts/cmake/vcpkg_build_cmake.cmake
- scripts/cmake/vcpkg_build_make.cmake
- scripts/cmake/vcpkg_build_nmake.cmake
- scripts/cmake/vcpkg_copy_tools.cmake

This needs to be merged, too, but I guess it will give a very long CI run. So I'm holding this back until explicitly invited, and this PR in draft state.

### CODE REVIEW

**Comment by dg0yt** [comment]
The CI errors reflects the missing changes to `scripts/cmake/`. As I said, I can push these changes when it is okay for CI load.

**Comment by dg0yt** [comment]
> The CI errors reflects the missing changes to `scripts/cmake/`

Plus one missing change to `ports/vcpkg-cmake/vcpkg_cmake_configure.md`. Now included in the pending commit.

**Comment by dg0yt** [comment]
Pending commit: https://github.com/dg0yt/vcpkg/pull/2/files

**Comment by JackBoosY** [comment]
Please apply [this patch](https://dev.azure.com/vcpkg/public/_build/results?buildId=52843&view=artifacts&pathAsName=false&type=publishedArtifacts) to your branch.

**Comment by dg0yt** [comment]
> Please apply [this patch](https://dev.azure.com/vcpkg/public/_build/results?buildId=52843&view=artifacts&pathAsName=false&type=publishedArtifacts) to your branch.

Negative. The diff restores the spelling errors. 

As I already wrote in my comments: what is needed is https://github.com/dg0yt/vcpkg/pull/2/files. I need to know if it is okay to let the pending commit hit CI because it will trigger a rebuild of many packages (without changes to the binary result).
(Before that, a native speaker might verify that the changes are valid, to avoid another expensive CI run.)

**Comment by JackBoosY** [comment]
@dg0yt Some changes need you to modify the cmake file in _scripts/cmake_.

**Comment by dg0yt** [comment]
> @dg0yt Some changes need you to modify the cmake file in _scripts/cmake_.

Yes, and I named them.
Well, I will just push that commit. Let's see how it rebuilds 1500 ports.

**Comment by dg0yt** [comment]
Oh no. Missing port version update.

**Comment by JackBoosY** [comment]
Waiting for https://github.com/microsoft/vcpkg/pull/17628.

**Comment by dg0yt** [comment]
Please re-run the failed jobs. CI was stuck at some point.

**Comment by JackBoosY** [comment]
@dg0yt Because the modification involves several key functions or ports, and they have led to the rebuild of almost all ports.

**Comment by BillyONeal** [comment]
> "Only" documentation changes, but rebuilding the world and hitting the CI wall...
> Isn't it possible to just re-run the failed jobs? Or shall I split the PR?

All the files in $/scripts/cmake are part of the base hash in the binary cache, so any change in those files is world-invalidating.

**Comment by dg0yt** [comment]
> All the files in $/scripts/cmake are part of the base hash in the binary cache, so any change in those files is world-invalidating.

This is why I was asking for coordination already when opening the PR ;-)
And that's why I keep asking to re-run the *failed* jobs only. At least in standard GH/AZP integration, this is a just a push of a button.

**Comment by strega-nil-ms** [comment]
Thanks @dg0yt !

**Pull request merged**
