### PR TITLE
[flatbuffers] support iOS build

### LINKED ISSUE #27290: [flatbuffers] Build failure for arm-ios and arm64-ios triplets
**Host Environment**

- OS: MacOS 12.6
- Compiler: XCode 14.01 and iPhone 16 SDK

**To Reproduce**

`./vcpkg install flatbuffers:arm-ios`

Note: same error when I use arm64-ios triplet

**Failure logs**
Other ports have installed fine on this machine, however, flatbuffers is failing and seems to be complaining about some architecture issue. 

```
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.0.sdk/usr/include/sys/cdefs.h:901:2: error: Unsupported architecture
#error Unsupported architecture
```

```
-- Applying patch no-werror.patch
-- Applying patch fix-uwp-build.patch
-- Using source at /Users/john/dev/vcpkg/buildtrees/flatbuffers/src/v2.0.6-b1de17998d.clean
-- Configuring arm-ios
-- Building arm-ios-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:131 (message):
    Command failed: /Users/john/dev/vcpkg/downloads/tools/cmake-3.24.0-osx/cmake-3.24.0-macos-universal/CMake.app/Contents/bin/cmake --build . --config Debug --target install -- -v -j7
    Working Directory: /Users/john/dev/vcpkg/buildtrees/flatbuffers/arm-ios-dbg
    See logs for more information:
      /Users/john/dev/vcpkg/buildtrees/flatbuffers/install-arm-ios-dbg-out.log

Call Stack (most recent call first):
  installed/x64-osx/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-osx/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/flatbuffers/portfile.cmake:28 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)


error: building flatbuffers:arm-ios failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+flatbuffers
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[flatbuffers]+Build+error
Include '[flatbuffers] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-10-12-b586c2752f75bcc3f6a243749e9a0d94d0d93ccd
    vcpkg-scripts version: 79fa9d85c 2022-10-17 (8 hours ago)
```

- Attach ***every failure log file*** mentioned in the console output.
[install-arm64-ios-dbg-out.log](https://github.com/microsoft/vcpkg/files/9805049/install-arm64-ios-dbg-out.log)

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

### PR DESCRIPTION
**Pull request by luncliff**
### What does your PR fix?

* Fix #27290

Disable universal build option for the Apple platform.

### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?

* arm64-ios
* arm-ios

And some possible iOS targeting triplets like [arm64-ios-simulator.cmake](https://github.com/luncliff/vcpkg-registry/blob/main/triplets/arm64-ios-simulator.cmake)

### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  `Your answer`

Yes.

### CODE REVIEW

**Comment by JonLiu1993** [comment]
@luncliff, Thanks for your pr, I have submitted a pr before to upgrade flatbuffers to the latest version, the review has been completed, and it is waiting to be merged. Can you wait a moment for me to help you resolve conflicts and review after the PR merge is completed?

**Comment by luncliff** [comment]
Sure. Let’s bump the version first.

**Review by JonLiu1993 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Oh, heh, sorry, I pushed a merge with master to ensure https://github.com/microsoft/vcpkg/pull/27298 didn't break this and I see that was already here. Sorry!

**Comment by luncliff** [comment]
Never mind. I know that's a necessary habit for the team 👍

**Comment by BillyONeal** [comment]
Thanks!

**Pull request merged**
