### PR TITLE
[fmt] Updated to 6.1.2

### PR DESCRIPTION
**Pull request by tagsemb**
{fmt} lib updated to latest release, 6.1.2.

### CODE REVIEW

**Comment by JackBoosY** [comment]
Please sigin CLA first.

Thanks.

**Comment by crackedmind** [comment]
Is this patch necessary? fmt 6.1.2 produces only C4275 and it was fixed in https://github.com/fmtlib/fmt/commit/8ab1c5c6e83df8f067a9121bb7c7e3a17b43e9a2 (fourth commit after 6.1.2 release) and it's fixing latest spdlog compilation (spdlog compiling with /WX)

**Comment by tagsemb** [comment]
@crackedmind This patch updates all the way from 6.0.0 to 6.1.2, and that includes a fair number of changes. 6.1.0 was at least a significant release.

**Comment by crackedmind** [comment]
I'm talking about file fix-warning4189.patch

**Comment by tagsemb** [comment]
@crackedmind Oh sorry, I have no idea. I just left it there out of fear of messing up someone else's day.

**Comment by NancyLi1013** [comment]
Have existed PR #9289.

**Comment by JackBoosY** [comment]
Please resolve these regressions.  You can download these logs in:
https://dev.azure.com/vcpkg/public/_build/results?buildId=25419&view=artifacts&type=publishedArtifacts
https://dev.azure.com/vcpkg/public/_build/results?buildId=25418&view=artifacts&type=publishedArtifacts

Thanks.

**Comment by tagsemb** [comment]
Sorry, I'm a little confused by the regressions, and I may need some guidance. The only thing resembling failures I could find in any of error logs are these ones in the "port build failure logs", config-x64-linux-[dbg/rel]-err.log:

```
CMake Warning:
  Manually-specified variables were not used by the project:

    VCPKG_PLATFORM_TOOLSET
    VCPKG_SET_CHARSET_FLAG
```

However, these are flags that are not mentioned anywhere in the diff for the PR, nor are they indeed set in the actual port files for fmt. Is this really a regression caused by this PR? If so, I'm afraid I don't understand how or how to fix it.

All the other error logs I could find that were non-zero simply contained lines that were obviously not errors, like:

```
Checking patch bench/CMakeLists.txt...
Applied patch bench/CMakeLists.txt cleanly.
```

It should also be mentioned that the OSX PR test seems to have more problems:
> Missing log files for comparison baseline (c89f944b1d874d7d2224f36dd31a499277949cea).  This may cause unrelated failures to show up in the test results. This is most likely the result of an infrastructure failure in the post checkin pipeline which creates the baseline logs. If this is the case, the fix is to manually queue a post checkin CI job (use default settings) and rerun this job when it completes.

Apologies if I'm being thick here, but I'm not sure how to proceed.

**Comment by JackBoosY** [comment]
In _install-x64-linux-dbg-out.log_:
```
[1/8] /usr/bin/c++  -DFMT_LOCALE -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -I/ci/myagent/_work/3/s/buildtrees/spdlog/src/34724392a0-c671dd4aa9/include -isystem /ci/myagent/_work/3/s/installed/x64-linux/include -fPIC -g   -Wall -Wextra -Wconversion -pedantic -Wfatal-errors -std=c++11 -MD -MT CMakeFiles/spdlog.dir/src/fmt.cpp.o -MF CMakeFiles/spdlog.dir/src/fmt.cpp.o.d -o CMakeFiles/spdlog.dir/src/fmt.cpp.o -c /ci/myagent/_work/3/s/buildtrees/spdlog/src/34724392a0-c671dd4aa9/src/fmt.cpp
[2/8] /usr/bin/c++  -DFMT_LOCALE -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -I/ci/myagent/_work/3/s/buildtrees/spdlog/src/34724392a0-c671dd4aa9/include -isystem /ci/myagent/_work/3/s/installed/x64-linux/include -fPIC -g   -Wall -Wextra -Wconversion -pedantic -Wfatal-errors -std=c++11 -MD -MT CMakeFiles/spdlog.dir/src/async.cpp.o -MF CMakeFiles/spdlog.dir/src/async.cpp.o.d -o CMakeFiles/spdlog.dir/src/async.cpp.o -c /ci/myagent/_work/3/s/buildtrees/spdlog/src/34724392a0-c671dd4aa9/src/async.cpp
FAILED: CMakeFiles/spdlog.dir/src/async.cpp.o 
/usr/bin/c++  -DFMT_LOCALE -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -I/ci/myagent/_work/3/s/buildtrees/spdlog/src/34724392a0-c671dd4aa9/include -isystem /ci/myagent/_work/3/s/installed/x64-linux/include -fPIC -g   -Wall -Wextra -Wconversion -pedantic -Wfatal-errors -std=c++11 -MD -MT CMakeFiles/spdlog.dir/src/async.cpp.o -MF CMakeFiles/spdlog.dir/src/async.cpp.o.d -o CMakeFiles/spdlog.dir/src/async.cpp.o -c /ci/myagent/_work/3/s/buildtrees/spdlog/src/34724392a0-c671dd4aa9/src/async.cpp
In file included from /ci/myagent/_work/3/s/buildtrees/spdlog/src/34724392a0-c671dd4aa9/src/async.cpp:11:0:
/ci/myagent/_work/3/s/buildtrees/spdlog/src/34724392a0-c671dd4aa9/include/spdlog/details/thread_pool-inl.h: In member function ‘bool spdlog::details::thread_pool::process_next_msg_()’:
/ci/myagent/_work/3/s/buildtrees/spdlog/src/34724392a0-c671dd4aa9/include/spdlog/details/thread_pool-inl.h:119:9: error: ‘assert’ was not declared in this scope
         assert(false && "Unexpected async_msg_type");
         ^~~~~~
compilation terminated due to -Wfatal-errors.
[3/8] /usr/bin/c++  -DFMT_LOCALE -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -I/ci/myagent/_work/3/s/buildtrees/spdlog/src/34724392a0-c671dd4aa9/include -isystem /ci/myagent/_work/3/s/installed/x64-linux/include -fPIC -g   -Wall -Wextra -Wconversion -pedantic -Wfatal-errors -std=c++11 -MD -MT CMakeFiles/spdlog.dir/src/spdlog.cpp.o -MF CMakeFiles/spdlog.dir/src/spdlog.cpp.o.d -o CMakeFiles/spdlog.dir/src/spdlog.cpp.o -c /ci/myagent/_work/3/s/buildtrees/spdlog/src/34724392a0-c671dd4aa9/src/spdlog.cpp
FAILED: CMakeFiles/spdlog.dir/src/spdlog.cpp.o 
/usr/bin/c++  -DFMT_LOCALE -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -I/ci/myagent/_work/3/s/buildtrees/spdlog/src/34724392a0-c671dd4aa9/include -isystem /ci/myagent/_work/3/s/installed/x64-linux/include -fPIC -g   -Wall -Wextra -Wconversion -pedantic -Wfatal-errors -std=c++11 -MD -MT CMakeFiles/spdlog.dir/src/spdlog.cpp.o -MF CMakeFiles/spdlog.dir/src/spdlog.cpp.o.d -o CMakeFiles/spdlog.dir/src/spdlog.cpp.o -c /ci/myagent/_work/3/s/buildtrees/spdlog/src/34724392a0-c671dd4aa9/src/spdlog.cpp
In file included from /ci/myagent/_work/3/s/buildtrees/spdlog/src/34724392a0-c671dd4aa9/src/spdlog.cpp:13:0:
/ci/myagent/_work/3/s/buildtrees/spdlog/src/34724392a0-c671dd4aa9/include/spdlog/details/pattern_formatter-inl.h: In member function ‘void spdlog::details::scoped_padder::pad_it(size_t)’:
/ci/myagent/_work/3/s/buildtrees/spdlog/src/34724392a0-c671dd4aa9/include/spdlog/details/pattern_formatter-inl.h:76:9: error: ‘assert’ was not declared in this scope
         assert(count <= spaces_.size());
         ^~~~~~
compilation terminated due to -Wfatal-errors.
[4/8] /usr/bin/c++  -DFMT_LOCALE -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -I/ci/myagent/_work/3/s/buildtrees/spdlog/src/34724392a0-c671dd4aa9/include -isystem /ci/myagent/_work/3/s/installed/x64-linux/include -fPIC -g   -Wall -Wextra -Wconversion -pedantic -Wfatal-errors -std=c++11 -MD -MT CMakeFiles/spdlog.dir/src/stdout_sinks.cpp.o -MF CMakeFiles/spdlog.dir/src/stdout_sinks.cpp.o.d -o CMakeFiles/spdlog.dir/src/stdout_sinks.cpp.o -c /ci/myagent/_work/3/s/buildtrees/spdlog/src/34724392a0-c671dd4aa9/src/stdout_sinks.cpp
[5/8] /usr/bin/c++  -DFMT_LOCALE -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -I/ci/myagent/_work/3/s/buildtrees/spdlog/src/34724392a0-c671dd4aa9/include -isystem /ci/myagent/_work/3/s/installed/x64-linux/include -fPIC -g   -Wall -Wextra -Wconversion -pedantic -Wfatal-errors -std=c++11 -MD -MT CMakeFiles/spdlog.dir/src/file_sinks.cpp.o -MF CMakeFiles/spdlog.dir/src/file_sinks.cpp.o.d -o CMakeFiles/spdlog.dir/src/file_sinks.cpp.o -c /ci/myagent/_work/3/s/buildtrees/spdlog/src/34724392a0-c671dd4aa9/src/file_sinks.cpp
[6/8] /usr/bin/c++  -DFMT_LOCALE -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -I/ci/myagent/_work/3/s/buildtrees/spdlog/src/34724392a0-c671dd4aa9/include -isystem /ci/myagent/_work/3/s/installed/x64-linux/include -fPIC -g   -Wall -Wextra -Wconversion -pedantic -Wfatal-errors -std=c++11 -MD -MT CMakeFiles/spdlog.dir/src/color_sinks.cpp.o -MF CMakeFiles/spdlog.dir/src/color_sinks.cpp.o.d -o CMakeFiles/spdlog.dir/src/color_sinks.cpp.o -c /ci/myagent/_work/3/s/buildtrees/spdlog/src/34724392a0-c671dd4aa9/src/color_sinks.cpp
ninja: build stopped: subcommand failed.
```

**Comment by tagsemb** [comment]
So spdlog, which relies on fmt, had issues with fmt 6.1.2 in the current version. I added a commit that updates spdlog from 1.4.2 to 1.5.0 as well, addressing the issues. I'm not sure if I should've made a new PR for this?

**Comment by JackBoosY** [comment]
@tagsemb Yes, you can open a new PR to update spdlog.
And I found #9289 is doing the same job.

**Comment by xeropresence** [comment]
What work needs to be done to update fmt and spdlog still?

**Comment by JackBoosY** [comment]
@xeropresence Needs to wait for #10051 merge.

**Comment by JackBoosY** [comment]
Please resolve windows build failures.

Thanks.

**Comment by kevinlul** [comment]
Unneeded since #10080 got merged?

**Comment by tagsemb** [comment]
Unneeded, duplicate of  #10080.

**Pull request closed without merging**
