### PR TITLE
[lest] Add lest v1.34.1 (was: v1.34.0)

### PR DESCRIPTION
**Pull request by martinmoene**
First version of lest C++ tiny test framework.

See also issue #1489.

### CODE REVIEW

**Comment by Codiferous** [comment]
@martinmoene Thanks for this PR! It looks pretty good to me, but I have one question.

I took the "Example Usage" code from [the lest github repo](https://github.com/martinmoene/lest) and attempted to build. The example doesn't build because this port installs the headers into the `lest` folder, so the include needs to be modified to `#include <lest/lest.hpp>`. I just want to confirm that this is intentional/how the library is intended to be used before merging this PR. 😄

**Comment by martinmoene** [comment]
@Codiferous Ah, good catch,  I'll look into it and update/report back.

**Comment by martinmoene** [comment]
@Codiferous I changed the occurrences of `#include "lest.hpp"` and the like to `#include "lest/lest.hpp"` and tried it successfully with Visual Studio 2017. Release tag now is v1.34.1.

**Comment by martinmoene** [comment]
Argh! lest version needs updating... back in a minute...

**Comment by martinmoene** [comment]
@Codiferous I, ok, done.

**Comment by Codiferous** [comment]
@martinmoene I updated the hash for lest because it wasn't matching. With that change, everything looks beautiful. I'm really happy to have lest in vcpkg! 😄

**Comment by martinmoene** [comment]
Thanks!

**Pull request merged**
