### PR TITLE
[icu] enable rpath for x64-linux-dynamic triplet

### LINKED ISSUE #37080: [qtbase] build failure when building on linux as dynamic library
### Operating system

WSL Linux Ubuntu 22.04

### Compiler

gcc

### Steps to reproduce the behavior

```Shell
./vcpkg install qtbase:x64-linux-dynamic --clean-after-build
```

### Failure logs

[557/1523] : && /usr/bin/c++ -fPIC -g -Wl,--enable-new-dtags -fPIE -pie src/tools/qlalr/CMakeFiles/qlalr.dir/qlalr_autogen/mocs_compilation.cpp.o src/tools/qlalr/CMakeFiles/qlalr.dir/compress.cpp.o src/tools/qlalr/CMakeFiles/qlalr.dir/cppgenerator.cpp.o src/tools/qlalr/CMakeFiles/qlalr.dir/dotgraph.cpp.o src/tools/qlalr/CMakeFiles/qlalr.dir/grammar.cpp.o src/tools/qlalr/CMakeFiles/qlalr.dir/lalr.cpp.o src/tools/qlalr/CMakeFiles/qlalr.dir/main.cpp.o src/tools/qlalr/CMakeFiles/qlalr.dir/parsetable.cpp.o src/tools/qlalr/CMakeFiles/qlalr.dir/recognizer.cpp.o -o bin/qlalr  -Wl,-rpath,/home/dakasianov/vcpkg/buildtrees/qtbase/x64-linux-dynamic-dbg/lib:  lib/libQt6Core.so.6.6.1 && :
FAILED: bin/qlalr 
: && /usr/bin/c++ -fPIC -g -Wl,--enable-new-dtags -fPIE -pie src/tools/qlalr/CMakeFiles/qlalr.dir/qlalr_autogen/mocs_compilation.cpp.o src/tools/qlalr/CMakeFiles/qlalr.dir/compress.cpp.o src/tools/qlalr/CMakeFiles/qlalr.dir/cppgenerator.cpp.o src/tools/qlalr/CMakeFiles/qlalr.dir/dotgraph.cpp.o src/tools/qlalr/CMakeFiles/qlalr.dir/grammar.cpp.o src/tools/qlalr/CMakeFiles/qlalr.dir/lalr.cpp.o src/tools/qlalr/CMakeFiles/qlalr.dir/main.cpp.o src/tools/qlalr/CMakeFiles/qlalr.dir/parsetable.cpp.o src/tools/qlalr/CMakeFiles/qlalr.dir/recognizer.cpp.o -o bin/qlalr  -Wl,-rpath,/home/dakasianov/vcpkg/buildtrees/qtbase/x64-linux-dynamic-dbg/lib:  lib/libQt6Core.so.6.6.1 && :
/usr/bin/ld: warning: libicudata.so.74, needed by /home/dakasianov/vcpkg/installed/x64-linux-dynamic/debug/lib/libicuuc.so.74, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /home/dakasianov/vcpkg/installed/x64-linux-dynamic/debug/lib/libicuuc.so.74: undefined reference to `icudt74_dat'
collect2: error: ld returned 1 exit status

### Additional context

./vcpkg install qtbase:x64-linux --clean-after-build

Builds ok but it produce static library, when do dynamic library it fails.

### PR DESCRIPTION
**Pull request by krjakbrjak**
Fixes #37080.

### CODE REVIEW

**Comment by Neumann-A** [comment]
Probably not needed if #37190 is merged

**Comment by krjakbrjak** [comment]
> Probably not needed if #37190 is merged

Thank you for your input. I believe the portfiles can be interpreted as "instructions" on how to build libraries. If the library already provides the means to solve the building issue, then it should be utilized.

**Comment by BillyONeal** [comment]
Is this needed any longer now that https://github.com/microsoft/vcpkg/pull/37129 is merged?

**Comment by krjakbrjak** [comment]
> Is this needed any longer now that #37129 is merged?

I have just verified that this fix is not needed on the latest master. Therefore, it can be closed.

**Pull request closed without merging**
