### PR TITLE
[cudnn] Don't copy debug versions of the lib since they aren't provided

### PR DESCRIPTION
**Pull request by jacobkahn**
Don't copy debug versions of `libcudnn` to the `debug` output directory since NVIDIA doesn't provide any cuDNN libraries built in debug mode.

See https://github.com/microsoft/vcpkg/pull/14683 for first discussion, cc @JackBoosY 

- Which triplets are supported/not supported? Have you updated the CI baseline?

Same triplets as before are supported. Tested on `x64-linux`.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

Yes

### CODE REVIEW

**Review by JackBoosY — CHANGES_REQUESTED** [review]
Please bump the port version. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).

**Review by JackBoosY — APPROVED** [review]

**Comment by jacobkahn** [comment]
@JackBoosY Are we good to merge this?

**Comment by JackBoosY** [comment]
Waiting for the pipeline test results.

**Comment by jacobkahn** [comment]
@JackBoosY It looks like the pipeline machine ran out is memory and is stuck... can we restart it? cc @strega-nil

**Comment by jacobkahn** [comment]
@JackBoosY looks like those binaries are still needed for debug. From CI on Windows:
```
2020-11-25T10:52:00.0544262Z -- Performing post-build validation
2020-11-25T10:52:00.0548441Z Mismatching number of debug and release binaries. Found 0 for debug but 1 for release.
2020-11-25T10:52:00.0552009Z Debug binaries
2020-11-25T10:52:00.0554393Z 
2020-11-25T10:52:00.0556663Z 
2020-11-25T10:52:00.0561019Z Release binaries
2020-11-25T10:52:00.0563214Z 
2020-11-25T10:52:00.0567026Z     D:/packages/cudnn_x64-windows/lib/cudnn.lib
2020-11-25T10:52:00.0569117Z 
2020-11-25T10:52:00.0573023Z Debug binaries were not found
2020-11-25T10:52:00.0575184Z 
2020-11-25T10:52:00.0579172Z Mismatching number of debug and release binaries. Found 0 for debug but 1 for release.
2020-11-25T10:52:00.0582897Z Debug binaries
2020-11-25T10:52:00.0585156Z 
2020-11-25T10:52:00.0587482Z 
2020-11-25T10:52:00.0592708Z Release binaries
2020-11-25T10:52:00.0594915Z 
2020-11-25T10:52:00.0598899Z     D:/packages/cudnn_x64-windows/bin/cudnn64_7.dll
2020-11-25T10:52:00.0600789Z 
2020-11-25T10:52:00.0605340Z Debug binaries were not found
```
is this PR still viable? Thoughts on a workaround here? Should this be abandoned?

**Comment by strega-nil** [comment]
@jacobkahn We have a policy coming to allow this: `VCPKG_POLICY_ALLOW_MISMATCHED_NUMBERS_OF_LIBS` (or something along those lines). We don't have it implemented yet tho, it's tied to LLVM 11.

I'm gonna put this on depends:different-pr, and merge it once that PR is merged.

**Comment by jacobkahn** [comment]
Sounds good — thanks, @strega-nil!

**Comment by strega-nil** [comment]
@jacobkahn could you merge with master and add the `VCPKG_POLICY_ALLOW_MISMATCHED_NUMBERS_OF_LIBS`?

**Comment by jacobkahn** [comment]
@strega-nil sure — doing now

**Comment by strega-nil** [comment]
@jacobkahn the actual policy is `VCPKG_POLICY_MISMATCHED_NUMBER_OF_BINARIES`

**Comment by strega-nil** [comment]
Awesome, thanks @jacobkahn !

**Pull request merged**
