### PR TITLE
[vcpkg] preprocess _ignore_flags with vcpkg_escape_regex_control_characters

### PR DESCRIPTION
**Pull request by jgilje**
**Describe the pull request**

- What does your PR fix?

Following the work in 299f581dc3cb6803f21e93f4c2a23c45c38cc653, the `vcpkg_escape_regex_control_characters` should also be called for the `_ignore_flags`. I have vcpkg in a subdirectory of a directory named c++, and the string-regex-replace at line 172 fails without this.

- Which triplets are supported/not supported? Have you updated the CI baseline?

NA

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

Yes

### CODE REVIEW

**Comment by JackBoosY** [comment]
cc @Neumann-A for review this PR.

**Comment by jgilje** [comment]
Hi, just a friendly nod, any progress here? I think the one pending check has been stuck since a few hours after i opened this PR :smiley: 

Also, wanted to add that the sdl2 port at least triggers the bug described here.

**Comment by JackBoosY** [comment]
Hmm... I'm not sure. @strega-nil what do you think about?

**Review by strega-nil — APPROVED** [review]

**Pull request merged**
