### PR TITLE
[openssl] Fix arm-neon-android asm

### PR DESCRIPTION
**Pull request by dg0yt**
Follow-up from #33890, tentative arm-neon-android asm patch.

Patch submitted upstream: https://github.com/openssl/openssl/pull/22181, tagged "severity: fips change".

### CODE REVIEW

**Comment by dg0yt** [comment]
CC @ankurvdev

**Comment by BillyONeal** [comment]
Tagging reviewed because the change seems OK to me, upstream seems responsive, so I want to remember to check every day...

**Comment by BillyONeal** [comment]
I poked upstream again today

**Comment by BillyONeal** [comment]
@tom-cosgrove-arm of upstream says:

> @BillyONeal I don't think the final fix will look like this, but not sure exactly what it should be at the moment. This is now top of my OpenSSL list, though
> 
> (The reason I don't think the final fix will look like this is at a minimum the duplication, and I think the fix will need something in `arm-xlate.pl` too)

so I dropped reviewed for now.

**Comment by dg0yt** [comment]
It can't go into OpenSSL without some Perl so that even arm64-vms is happy :smile:

**Comment by talregev** [comment]
@dg0yt Can you solve the conflicts?

**Comment by BillyONeal** [comment]
Based on upstream's comment in https://github.com/openssl/openssl/pull/22181#issuecomment-2185322378 I'm going to take this.

**Review by BillyONeal — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the fix and sorry for the runaround with upstream!

**Pull request merged**
