### PR TITLE
[vcpkg] Add changelog generator

### PR DESCRIPTION
**Pull request by grdowns**
Here's the changelog generator used for the release notes, now ported to PowerShell. I've tested this on arbitrary date ranges, and it seems to work well.

You can use this yourself by running the script `.\Get-Changelog.ps1`, where it will prompt you for a date range and credentials. There's no logging on it at the moment, so expect to be twiddling your thumbs for a minute or so while it works.

### CODE REVIEW

**Review by vicroms — APPROVED** [review]
LGTM but my PowerShell knowledge is lacking 😅

**Comment by vicroms** [comment]
Is it possible to put the credentials in an environment variable to avoid being prompted every time?

**Comment by grdowns** [comment]
> Is it possible to put the credentials in an environment variable to avoid being prompted every time?

I thought about this a bit and explored getting cached credentials out of the git credential manager, or by possibly reading a git-credential file or environment variable.

It seems that the git credentials cache doesn't expose the cached passwords. Understandably it's kept in memory and not exposed.

Reading a git credential file is definitely possible, but I don't see any existing utilities for that. I can try to parse a credential file, but that means adding a parameter set to the options, validating the file, and then manually parsing for the correct credentials. The other point is that keeping your credentials stored in a plain text file (via `git config credential.helper store`) is generally not recommended as it's a security vulnerability.

Reading an environment variable is just about as bad as reading a plaintext file (depending who you ask), so I think the final conclusion is to make the facility password-storage agnostic.

My recommendation is to create a `PSCredential` object in your PowerShell session and supply it as an argument when you run the command. The `PSCredential` object will be reusable for the entire PowerShell session, too. Here's an example:

```PowerShell
PS C:\source\vcpkg> $cred = Get-Credential

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential
PS C:\source\vcpkg> .\scripts\Get-Changelog.ps1 -Credentials $cred

```

**Comment by grdowns** [comment]
Added:
- Credentials validation
- Progress bar
- Prevent changelog file overwriting by creating a new one if it already exists

That'll be about it for this PR. @vicroms feel free to merge when ready 🙂

**Review by strega-nil — CHANGES_REQUESTED** [review]
You should also change the rest of the file in a similar way; @grdowns are you willing to continue this PR? or should I take it over?

**Comment by grdowns** [comment]
Thanks for the feedback! I'll get to this soon; let's wait to merge until then.

**Comment by grdowns** [comment]
@strega-nil I committed your changes and fixed a couple things as fallout from the changes (see latest commit). This should be ready to merge upon your review. 🙂

**Comment by JackBoosY** [comment]
Ping @strega-nil @strega-nil-ms for review this PR.

**Comment by vicroms** [comment]
I have some changes to clean and push to this PR, I'll try to find some time this week to finally get this merged!

**Comment by PhoebeHui** [comment]
@vicroms, any updates?

**Comment by BillyONeal** [comment]
I'm closing this for now. @vicroms Please reopen if you want to continue.

**Comment by BillyONeal** [comment]
What was in this PR needed sufficient additional work that I now believe it fair to start another PR.

**Pull request closed without merging**
