### PR TITLE
[mimalloc] Fix build error on x64-android

### PR DESCRIPTION
**Pull request by jimwang118**
```
/home/vzhli17/jim/vcpkg/buildtrees/mimalloc/src/v2.1.7-d58a1dd7b9/src/arena.c:798:3: error: no matching function for call to 'atomic_store_explicit'
  mi_atomic_store_release(&segment->thread_id, 0);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Refer to upstream PR [694](https://github.com/microsoft/mimalloc/pull/694) for modification.

- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [ ] ~SHA512s are updated for each updated download.~
- [ ] ~The "supports" clause reflects platforms that may be fixed by this new version.~
- [ ] ~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~
- [ ] Any patches that are no longer applied are deleted from the port's directory.
- [ ] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [ ] Only one version is added to each modified port's versions file.

Compile test pass with following triplets:
```

x64-windows
x64-android
```

### CODE REVIEW

**Comment by jimwang118** [comment]
An issue [950](https://github.com/microsoft/mimalloc/issues/950) was raised upstream for tracking.

**Review by MonicaLiu0311 — APPROVED** [review]

**Comment by data-queue** [comment]
Can you submit an upstream PR?

**Comment by jimwang118** [comment]
> Can you submit an upstream PR?

Submitted PR [954](https://github.com/microsoft/mimalloc/pull/954) upstream.

**Comment by jimwang118** [comment]
> > Can you submit an upstream PR?
> 
> Submitted PR [954](https://github.com/microsoft/mimalloc/pull/954) upstream.

The fix PR has been merged upstream.

**Pull request merged**
