### PR TITLE
Bulk convert CONTROL files

### PR DESCRIPTION
**Pull request by BillyONeal**
This P/R intentionally makes no manual edits to CONTROLs and thus should not require extensive review.

```
function Convert-Control {
    Param($full)
    .\vcpkg.exe format-manifest $full
    $root = $full.Substring(0, $full.Length - 7) # CONTROL
    $new = $root + 'vcpkg.json'
    $content = Get-Content -Raw $new
    $asJson = ConvertFrom-Json $content -AsHashtable -Depth 100
    $oldVersion = $asJson['port-version']
    if ($null -eq $oldVersion) {
        $oldVersionFull = $asJson['version-string']
        Write-Host "Got version $oldVersionFull"
        $match = [System.Text.RegularExpressions.Regex]::Match($oldVersionFull, '^(.+)-(\d+)$')
        if ($match.Success -and -not [System.Text.RegularExpressions.Regex]::IsMatch($oldVersionFull, '^\d\d\d\d-\d\d-\d\d$')) {
            $newFullVersion = [string]$match.Groups[1].Value
            $oldVersion = [int]$match.Groups[2].Value
            Write-Host "newFullVersion $newFullVersion oldVersion $oldVersion"
            $newVersion = $oldVersion + 1
            $asJson['version-string'] = $newFullVersion
            Write-Host "Previous version for $full extracted from version field -- setting version-string $newFullVersion and port-version $newVersion"
        } else {
            Write-Host "No previous version for $full -- setting 1"
            $newVersion = 1
        }
    } else {
        $newVersion = [int]$oldVersion + 1
        Write-Host "New version for $full : $newVersion"
    }

    $asJson['port-version'] = $newVersion

    $content = ConvertTo-Json $asJson -Depth 100
    Set-Content -Path $new -Value $content
    .\vcpkg.exe format-manifest $new
}

Get-ChildItem ports\CONTROL -Recurse | Foreach-Object {
    Convert-Control $_.FullName
}

git commit -am "this message"
.\vcpkg.exe x-add-version -all
git commit -a --amend
```

### CODE REVIEW

**Comment by BillyONeal** [comment]
Example spot-check PRs for each of the 3 kinds of edits the script made:

* `7zip` used a separate port version field
* `absent` had no previous port version
* `activemq-cpp` used the old dash port version
* `akali` is a date that also had a dash port version
* `aliyun-oss-c-sdk` is a date with no port version

I intentionally made no conversions from "version-string" to "version" or similar as that would have required manual analysis of each `CONTROL`

**Review by strega-nil-ms — APPROVED** [review]

**Comment by BillyONeal** [comment]
Depends on https://github.com/microsoft/vcpkg/pull/20039

**Comment by JackBoosY** [comment]
Should we check some of them to check their correctness?

**Comment by BillyONeal** [comment]
> Should we check some of them to check their correctness?

You can check some, although we've already had a fair amount of machine checking by virtual of the `x-add-version --all`. The point here is to do the part that can be done mechanically so that we don't have to manually review 2000 of them, while still avoiding needing to nag people (as proposed by #19698 )

**Review by JackBoosY — APPROVED** [review]

**Comment by dg0yt** [comment]
Note that leaving all those `version-string` will still create a lot of contributor/reviewer loops. (https://github.com/microsoft/vcpkg/pull/20108#pullrequestreview-752264668)

**Comment by BillyONeal** [comment]
> Note that leaving all those `version-string` will still create a lot of contributor/reviewer loops. ([#20108 (review)](https://github.com/microsoft/vcpkg/pull/20108#pullrequestreview-752264668))

That is true. I do wish we could eliminate that problem too but getting off version-string really needs to be a conversation with upstream for each of the ports since it's a statement of intent with the upstream. (i.e. is 1.2.3 semver? need humans to get an idea)

The point was to be better than the status quo, not done.

**Pull request merged**
