### PR TITLE
[spirv-tools] Updating to v2022.4

### PR DESCRIPTION
**Pull request by Honeybunch**
**Describe the pull request**

- #### What does your PR fix?
  Updates the spirv-tools port

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  All

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

### CODE REVIEW

**Comment by Honeybunch** [comment]
Huh, I can't reproduce these build failures locally. Is there some way that I can see the log file generated during the build?

**Comment by Honeybunch** [comment]
Oh I see I guess this PR depends on https://github.com/microsoft/vcpkg/pull/27761 being merged first

**Comment by JonLiu1993** [comment]
@Honeybunch, Thanks for your pr, please get [failure logs here](https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/80761/artifacts?artifactName=failure%20logs%20for%20x86-windows&api-version=7.0&%24format=zip)

**Review by JonLiu1993 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the update!

**Pull request merged**
