### PR TITLE
xalan-c: Install headers correctly

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
To address the comments in https://github.com/Microsoft/vcpkg/pull/4246#issuecomment-433036876

- Add `vcpkg_clean_msbuild` function
- Add `SKIP_CLEAN` option to `vcpkg_install_msbuild`
- xalan-c portfile uses `SKIP_CLEAN` so the headers aren't deleted prematurely, and corrects the glob to install the two missing but required headers, then cleans the build tree using `vcpkg_clean_msbuild`.

Hope that's all OK.  The function and option names can be changed if they don't match existing conventions

### CODE REVIEW

**Comment by rleigh-codelibre** [comment]
This [build log](https://gitlab.com/rleigh/ome-common-cpp/-/jobs/112754200) demonstrates a successful test of the library both as configuration time and with unit tests.

**Comment by ras0219-msft** [comment]
Ouch, sorry we missed this!

I completely agree with the approach here, awesome work!

**Comment by rleigh-codelibre** [comment]
I noticed a documentation error and indentation issue.  Fixes pushed for these.

**Comment by ras0219-msft** [comment]
Thanks again!

**Comment by rleigh-codelibre** [comment]
@rleigh-codelibre Awesome, thanks.  With this done, I can now drop my own custom [superbuild project](https://github.com/ome/ome-cmake-superbuild/tree/master/packages) in favour of vcpkg.  If I find any other defects, I'll open additional PRs.

One small thing I did notice is that patch application can be a little fragile; it won't error out if patch application fails.  One thing the superbuild would have done is fail the build at this point, and would not try to re-apply applied patches.

**Comment by ras0219-msft** [comment]
Yeah, we used to apply patches as a separate statement from the initial extraction, so if you built multiple times the patches would fail to apply the second+ times. To prevent this from killing the build, we made patch application "optional".

However, now that we have the `PATCHES` argument to pretty much all of the extraction functions (and `vcpkg_extract_source_archive_ex()`), we can start looking at making patch failure a build failure.

**Pull request merged**
