### PR TITLE
[ffmpeg] Enable D3D12VA on Windows

### PR DESCRIPTION
**Pull request by julianxhokaxhiu**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [ ] SHA512s are updated for each updated download.
- [ ] The "supports" clause reflects platforms that may be fixed by this new version.
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [ ] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

---

FFMpeg seems to support it just fine for a while, but was never enabled for this port.
See https://www.gyan.dev/ffmpeg/builds/#about-these-builds

### CODE REVIEW

**Comment by MonicaLiu0311** [comment]
Please get [failure logs here](https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/103958/artifacts?artifactName=failure%20logs%20for%20x64-windows&api-version=7.1&%24format=zip):
```
BUILD_ARCH=x86_64
OPTION_VARIABLE=OPTIONS_x86_64
=== CONFIGURING ===
Unknown option "--enable-d3d12va".
See /d/b/ffmpeg/src/n6.1.1-92c5eda8dc.clean/configure --help for available options.
```

**Comment by kadirlua** [comment]
> Please get [failure logs here](https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/103958/artifacts?artifactName=failure%20logs%20for%20x64-windows&api-version=7.1&%24format=zip):
> 
> ```
> BUILD_ARCH=x86_64
> OPTION_VARIABLE=OPTIONS_x86_64
> === CONFIGURING ===
> Unknown option "--enable-d3d12va".
> See /d/b/ffmpeg/src/n6.1.1-92c5eda8dc.clean/configure --help for available options.
> ```

As I know, this config option has been added in ffmpeg 7.0.

**Comment by julianxhokaxhiu** [comment]
> As I know, this config option has been added in ffmpeg 7.0.

You're right, sorry not sure how I missed that. I'll add a comment on #38011 to ask if possible to be added there. Closing this PR as it will never work on 6.1.1. Sorry and thanks again

**Comment by kadirlua** [comment]
> > As I know, this config option has been added in ffmpeg 7.0.
> 
> You're right, sorry not sure how I missed that. I'll add a comment on #38011 to ask if possible to be added there. Closing this PR as it will never work on 6.1.1. Sorry and thanks again

No problem, after #38011 completed you can create new one or open this again.

**Pull request closed without merging**
