### PR TITLE
[zeromq] Add sodium support and fix static build

### PR DESCRIPTION
**Pull request by myd7349**

### CODE REVIEW

**Comment by vicroms** [comment]
Hi @myd7349 

Can you tell me what is the status of this PR?
As it currently stands, it causes no regressions ...but our CI doesn't test for non-default features 😅

**Comment by myd7349** [comment]
Hi! @vicroms 

Since `libsodium` uses `MSBuild` instead of `CMake`, the `sodium` feature only works on Windows currently.

Another problem is about a static build of `zeromq[sodium]`. The users have to link to `libsodium` by themselves if they want to use this feature:

```cmake
find_package(ZeroMQ CONFIG REQUIRED)
find_library(libsodium ...)

target_link_libraries(...)
```

**Comment by vicroms** [comment]
Given our incremental philosopjy, I'm OK with merging it as it is, and creating a new PR to fix those two issues in the future.

Although, it would be good to first create a new issue to document them and not loose track of them.

**Comment by myd7349** [comment]
@vicroms Thanks!

I have just created a PR for `libsodium`: #5600 .

**Pull request merged**
