### PR TITLE
find_acquire_program (python2)

### PR DESCRIPTION
**Pull request by glachancecmaisonneuve**
pull request:
- python2 version bump
- python2 and python3 tool location changes

rationale for the change:
- python2 and python3 are versioned tools, just like jom and ninja, 
- versioned tools are placed in a versioned folder ${VCPKGROOT}/download/tools/<program_name>/subdir where subdir is a version
- as such, python2 belongs in ${VCPKGROOT}/download/tools/python/python2 and python3 belongs in ${VCPKGROOT}/download/tools/python/python3
- the current bit in about _"There is no portable redistributable for Python 2.7"_ is laughable, MSI files are imminently redistributable and portable.

(possibly) affected ports:
- botan,cppcms,ctemplate,folly,gtk,pybind11,qscintilla,shaderc,spirv-tools and qt5 all use python3 or python2 is some way.  Thankfully, they also all use the exit variable from find_acquire_program for whatever need they have.
- I revised them all, albeit cursorily, and the proposed changes does not break those ports

What's left to decide:
- **To remove the python3 files** that are currently sitting in ${VCPKGROOT}/download/tools/python **or not**
- argument for leaving them there: They don't harm anything sitting there
- argument for removing them: 
    - I think the initial intention of the project was to have only 2 python installs (unless python 4 introduces a breaking change, which history tells us is a possibility).   
    - Removing them does not break any currently published porfiles.
- Please note that I did not include the code to remove the python3 files from the old folder location in this pull request, I will wait for code reviews to make the changes (or the comitter could just add the following by him or herself.
```cmake
file(GLOB OLD_PYTHON3_FILES ${DOWNLOADS}/tools/python/*.pyd ${DOWNLOADS}/tools/python/*.exe ${DOWNLOADS}/tools/python/*.dll ${DOWNLOADS}/tools/python/pyvenv.cfg ${DOWNLOADS}/tools/python/python35.zip)
file(REMOVE OLD_PYTHON3_FILES)
```
- from my review of the 10 ports that use python3, they all use python to run some form of configure or other, there wont be any other files in the folder besides the one find_aquire_program unzipped.

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for the PR!

While we can download the python 2.7 msi, this doesn't enable any ports that rely on 2.7 being installed to function without further action from the user: installing python 2.7. The note about "no _portable_ distribution" is specifically talking about something like a zip file that we can directly extract without any installation (which python3 does provide).

Therefore, this will change all ports that currently fail with the message "You need to install python 2.7 from /*url*/" into a build crash, so we can't accept this PR as-is.

Otherwise, moving python into a subfolder seems fine, though since we can't handle python 2 in this way it doesn't seem to have much use (except for a hypothetical python 4, as you indicated).

**Comment by glachancecmaisonneuve** [comment]
Are you sure you checked out my branch when you tested this?  If you have a minute to spare could you check out my branch and then "vcpkg create" a test package with the following?
```cmake
include(vcpkg_common_functions)
vcpkg_find_acquire_program(PYTHON2)
vcpkg_find_acquire_program(PYTHON3)
message("PYTHON2 PATH: ${PYTHON2}")
message("PYTHON3 PATH: ${PYTHON3}")
```
and tell me what you get for PYTHON2 and PYTHON3 please?  For my part, executing that test package gives me:
```cmd
PYTHON2 PATH: E:/vcpkg/downloads/tools/python/python2/python.exe
PYTHON3 PATH: E:/vcpkg/downloads/tools/python/python3/python.exe
```

**Comment by ras0219-msft** [comment]
Yep, you're totally right. I forgot we had MSI-extraction capabilities in that script so I assumed the download was doing nothing and the `find_program` was actually picking up a system wide copy that you overlooked.

We might need to revert this if there are unforseen regressions, but otherwise thank you very much for the PR and discussion!

**Comment by ras0219-msft** [comment]
Re: removing the old copy of python3

I think we should leave it there; one valid usage of vcpkg is to `git checkout <sha>` some older revision to get at whatever ports were available at the time. Newer users will, of course, not have it so there shouldn't be any long-term problems.

**Comment by glachancecmaisonneuve** [comment]
Thank you for taking a second look at this.  

On a more personal note, I would like to commend you for staying so professional with your first comment for what you believed to be a pull request that was essentially a big pile of doodoo.  I am not sure I would have been able to do the same in the same circumstance.

**Pull request merged**
