### PR TITLE
[tracy] Updating port to v0.9

### PR DESCRIPTION
**Pull request by Honeybunch**
**Describe the pull request**
Updating tracy to the latest version

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  All

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

### CODE REVIEW

**Comment by JonLiu1993** [comment]
@Honeybunch, Thanks for your pr, we have deprecated the functions `vcpkg_copy_tool_dependencies` on lines 160 and 163, and now use the new function [vcpkg_copy_tools](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_copy_tools.md) instead, can you replace it?

**Comment by dg0yt** [comment]
> we have deprecated the functions `vcpkg_copy_tool_dependencies` on lines 160 and 163, and now use the new function [vcpkg_copy_tools](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_copy_tools.md) instead, can you replace it?

AFAICS this port doesn't follow the comon pattern to install the tools to `bin`, so `vcpkg_copy_tools` doesn't apply. (But it would be nice if the port be modified to just rely on `vcpkg_cmake_install` + `vcpkg_copy_tools`.)

**Comment by Honeybunch** [comment]
I can definitely give it a shot

**Comment by JonLiu1993** [comment]
All features are tested successfully in the following triplet:
- x64-windows
- x64-windows-static

**Review by JonLiu1993 — APPROVED** [review]

**Pull request merged**
