### PR TITLE
LLVM with features and fixes.

### PR DESCRIPTION
**Pull request by TheAifam5**
**If you need some other features, please comment**

**WARNING**
To build AIO you need to have minimum 32GB RAM available (because libclang uses >7 <12GB) and other libraries about 5-8GB at the linkage stage.

**QUESTIONS**
 - The installation does not work, because there is not Debug build. How can I disable verification for packages which are only release?
```cmake
set(VCPKG_BUILD_TYPE release)
set(VCPKG_POLICY_ONLY_RELEASE_CRT enabled)
```

**Warnings while configuring**
```
-- Warning: The clang-protobuf-fuzzer is not supported by MSVC compiler.
-- Warning: The libomp library doesn't support static linkage on Windows platform.
```

✅ - OK (x86 & x64)
❗️ - Fails or action required (x86 & x64)
❌ - Not tested (x86 & x64)
➖ - Not supported (maybe state2 will work)

| Feature Name  | Visual Studio 2017 | Visual Studio 2015 | Ubuntu |
| ------------- | ------------------ | ------------------ | ------ |
| AIO (All-In-One) | ✅ | ❌ | ❌ |
| llvm | ✅ | ❌ | ❌ |
| clang | ✅ | ❌ | ❌ |
| clang-tools-extra | ✅ | ❌ | ❌ |
| clang-protobuf-fuzzer | ➖ | ❌ | ❌ |
| lld | ✅ | ❌ | ❌ |
| lldb | ✅ | ❌ | ❌ |
| lldb-python2 | ❗️ | ❌ | ❌ | ❌ |
| lldb-python3 | ❗️ | ❌ | ❌ | ❌ |
| polly | ✅ | ❌ | ❌ |
| polly-gpu (requires CUDA/OpenCL) | ➖ | ❌ | ❌ |
| compiler-rt | ✅ | ❌ | ❌ |
| libcxx | ➖ | ❌ | ❌ | ❌ |
| libcxxabi | ➖ | ❌ | ❌ | ❌ |
| libunwind | ➖ | ❌ | ❌ |
| libomp | ✅ | ❌ | ❌ |
| libomp-debugger | ✅ | ❌ | ❌ |
| libomp-stats | ➖ | ❌ | ❌ |
| libomp-ompt-off | ✅ | ❌ | ❌ |
| documentation | ❌ | ❌ | ❌ |
| enable-cxx1z | ✅ | ❌ | ❌ |
| enable-cxx1y | ✅ | ❌ | ❌ |
| enable-eh | ✅ | ❌ | ❌ |
| enable-rtti | ✅ | ❌ | ❌ |
| enable-ffi | ✅ | ❌ | ❌ |
| enable-expensive-checks | ✅ | ❌ | ❌ |
| clang-enable-z3-analyzer | ❗️ | ❌ | ❌ |
| abi-breaking-checks-on | ✅ | ❌ | ❌ |
| abi-breaking-checks-off | ✅ | ❌ | ❌ |
| target-all | ✅ | ❌ | ❌ |
| target-exp-all | ✅ | ❌ | ❌ |
| target-aarch64 | ✅ | ❌ | ❌ |
| target-amdgpu | ✅ | ❌ | ❌ |
| target-arm | ✅ | ❌ | ❌ |
| target-bpf | ✅ | ❌ | ❌ |
| target-hexagon | ✅ | ❌ | ❌ |
| target-lanai | ✅ | ❌ | ❌ |
| target-mips | ✅ | ❌ | ❌ |
| target-msp430 | ✅ | ❌ | ❌ |
| target-nvptx | ✅ | ❌ | ❌ |
| target-powerpc | ✅ | ❌ | ❌ |
| target-sparc | ✅ | ❌ | ❌ |
| target-systemz | ✅ | ❌ | ❌ |
| target-x86 | ✅ | ❌ | ❌ |
| target-xcore | ✅ | ❌ | ❌ |
| target-exp-avr | ✅ | ❌ | ❌ |
| target-exp-arc | ✅ | ❌ | ❌ |
| target-exp-nios2 | ✅ | ❌ | ❌ |
| target-exp-wasm | ✅ | ❌ | ❌ |

Fixes for:
  - #3979 
  - #3981 

Requirements: 
 - [ ] Nice modifications for py and swig: https://github.com/Microsoft/vcpkg/pull/3105
 - [x] polly-gpu-cuda does not work on x86 because NVIDIA deprecated/removed x86 support (https://gitlab.kitware.com/cmake/cmake/issues/18237)
  - [x] polly-gpu does not work on Windows

TODO:
 - [x] Fix problems with libomp-debugger where VS can not link because of missing two definitions (which is weird because all is defined)
 - [x] Fix DLL/Lib copy
 - [x] Fix libomp to use dynamic-crt (uses static every triplet - no known reason why they decieded so)
 - [x] Fix libunwind which uses invalid compiler (c++, should use c) and invalid flag (-std=c99)
 - [x] Fix llvm-lto /static
 - [x] Add LZMA and ZLIB to clang-fuzzer
 - [x] Fix clang-fuzzer protobuf can not be found, but is compilable by other projects like `clang-proto-to-cxx`

Checking:
 - AIO using stage-2

On hold (need PR for SWIG):
 - [ ] lldb-python2
 - [ ] lldb-python3

On hold (need PR for Z3):
 - [ ] clang-enable-z3-analyzer

On hold (just):
 - [ ] clang-stage2

On hold (needs patches):
 - [ ] Fix libxml2 dependency (zlib)

Optional:
 - [ ] Add CLING package

Not possible on Windows yet:
 - [ ] single 
LLVM's Mailing: (http://lists.llvm.org/pipermail/llvm-dev/2017-June/113925.html)
Maybe use this?: https://github.com/valtron/llvm-stuff/wiki/Problems-building-with-LLVM_BUILD_LLVM_DYLIB

### CODE REVIEW

**Comment by MathiasMagnus** [comment]
Hi!

I am working on something very similar, though your solution is far more fleshed out than mine. I'll might just be using your working tree until this work gets merged.

One thing to note that I would like to be incorporated: many projects depending on LLVM use `llvm-config.exe` to query what components are installed, what is the install layout, etc. I am particularly interested in Portable OpenCL (pocl) which also does this. However, because the install layout required by Vcpkg differs from the canonical layout, I had to patch the source of llvm-config.cpp to make it actually report to correct layout. If you invoke `llvm-config.exe --includedir` you'll see it report bad paths. You might want to pull in this patch of mine.

[fixup-llvm-config-to-vcpkg-layout.zip](https://github.com/Microsoft/vcpkg/files/2418444/fixup-llvm-config-to-vcpkg-layout.zip)

Also, would you mind bumping the version number as well to LLVM 7.0.0?

**Comment by TheAifam5** [comment]
@MatthewPowley I'm working now on Cache file generator in CMake for Clang-stage2 compilation process. Thank you for your patch :)

**Comment by MathiasMagnus** [comment]
@TheAifam5 could you get around to finish up the PR?

**Comment by TheAifam5** [comment]
@MathiasMagnus Hey man, that could be a little but harder since there is a new release out and there can be a new things to patch or remove so I dont have time right now for it because I’m at last year of the school.

Its also really time consuming. You can try make a fork and try to upgrade the version, as far I know there are some patches which are migrated into new version so they can be safety deleted.

**Pull request closed without merging**
