### PR TITLE
[curl] Fix usage of curl library on Android.

### PR DESCRIPTION
**Pull request by AenBleidd**
Remove hard dependency on dynamically built OpenSSL.

Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

### CODE REVIEW

**Comment by ahmedyarub** [comment]
These hard-coded dependencies were copied from AWS SDK for C++. Removing them would break building on Windows.

**Comment by AenBleidd** [comment]
@ahmedyarub, these lines are specific to Android.
#17418 might be more proper fix for this

**Comment by ahmedyarub** [comment]
> 
> 
> @ahmedyarub, these lines are specific to Android.
> #17418 might be more proper fix for this

Exactly! I've just tested that PR on Windows and it worked for compiling Android apps.

**Comment by AenBleidd** [comment]
Closing this in favor of #17418

**Pull request closed without merging**
