### PR TITLE
[cgicc]Fix usage error:lnk2019.

### PR DESCRIPTION
**Pull request by JackBoosY**
Add macros `CGICC_EXPORTS`/`CGICC_STATIC` to `CMakeLists.txt` to enable export function and variable symbols.

Related: #3213.

Note: this port doesn't contain any feature.

### CODE REVIEW

**Comment by JackBoosY** [comment]
@vicroms Still have problem with using cgicc in static mode, could you help me? Thanks.

**Comment by ras0219-msft** [comment]
To use this library in static mode, we'll need to patch out some lines in `cgicc/CgiDefs.h.in`:

https://github.com/cmakified/cgicc/blob/eb76326809e96ad110d0d74c4d8908a92477cb75/cgicc/CgiDefs.h.in#L53.

Specifically, when building or consuming statically, `CGICC_API` should be defined to be empty.

**Comment by JackBoosY** [comment]
@ras0219-msft Thank you for pointing this out! I didn't notice this.

**Review by PhoebeHui — APPROVED** [review]

**Review by PhoebeHui — APPROVED** [review]

**Review by dan-shaw — APPROVED** [review]

**Pull request merged**
