### PR TITLE
[vcpkg_find_fortran] Update libiconv and zlib hash

### PR DESCRIPTION
**Pull request by JackBoosY**
Fixes https://github.com/microsoft/vcpkg/pull/18876. 

Tested my changes with `lapack-reference` with resuilt: success.

### CODE REVIEW

**Comment by cenit** [comment]
@JackBoosY i tagged only one line but there was more

also mingw-w64-i686-zlib-1.2.11-8-any.pkg.tar.zst was changed without fixing its hash!!

**Comment by JackBoosY** [comment]
@cenit I forgot this, thanks for notice.

**Comment by cenit** [comment]
my only concern is that ci was not noticing the problem. why? no port being tested? is it difficult to make one working to check problems like this in the future?

**Comment by JackBoosY** [comment]
```
Starting package 107/271: lapack-reference:x86-windows
Building package lapack-reference[blas-select,core,noblas]:x86-windows...
-- Using D:/downloads/Reference-LAPACK-lapack-v3.8.0.tar.gz
-- Extracting source D:/downloads/Reference-LAPACK-lapack-v3.8.0.tar.gz
-- Using source at D:/buildtrees/lapack-reference/src/v3.8.0-954f10683f.clean
-- The Fortran compiler identification is unknown
-- No Fortran compiler found on the PATH. Using MinGW gfortran!
-- Using msys root at D:/downloads/tools/msys2/51cfb821b1485bc1
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Using msys root at D:/downloads/tools/msys2/aa5af7b2aa7e90e8
-- Fixing pkgconfig file: D:/packages/lapack-reference_x86-windows/lib/pkgconfig/blas.pc
-- Fixing pkgconfig file: D:/packages/lapack-reference_x86-windows/lib/pkgconfig/lapack.pc
-- Fixing pkgconfig file: D:/packages/lapack-reference_x86-windows/debug/lib/pkgconfig/blas.pc
-- Fixing pkgconfig file: D:/packages/lapack-reference_x86-windows/debug/lib/pkgconfig/lapack.pc
-- Installing: D:/packages/lapack-reference_x86-windows/share/lapack-reference/copyright
-- Performing post-build validation
-- Performing post-build validation done
Uploaded binaries to 1 HTTP remotes.
Building package lapack-reference[blas-select,core,noblas]:x86-windows... done
Installing package lapack-reference[blas-select,core,noblas]:x86-windows...
Installing package lapack-reference[blas-select,core,noblas]:x86-windows... done
Elapsed time for package lapack-reference:x86-windows: 53.15 s
```
It seems that our ci system didn't catch this error.

**Comment by JackBoosY** [comment]
cc @BillyONeal do you know why our ci didn't trigger this changes?

**Comment by BillyONeal** [comment]
> cc @BillyONeal do you know why our ci didn't trigger this changes?

I don't understand; it says that the builds are running?

**Comment by JackBoosY** [comment]
@BillyONeal In #18876, the update of msys components should trigger our pipeline test to download these new components and detect their hash, but this is not the case.

**Review by NancyLi1013 — APPROVED** [review]

**Comment by cenit** [comment]
@JackBoosY @NancyLi1013 shall we not merge this PR until we have found out why ci was not detecting the issue?

**Comment by JackBoosY** [comment]
```
Starting package 107/271: lapack-reference:x86-windows
Building package lapack-reference[blas-select,core,noblas]:x86-windows...
-- Downloading https://github.com/Reference-LAPACK/lapack/archive/v3.8.0.tar.gz -> Reference-LAPACK-lapack-v3.8.0.tar.gz...
-- Extracting source D:/downloads/Reference-LAPACK-lapack-v3.8.0.tar.gz
-- Using source at D:/buildtrees/lapack-reference/src/v3.8.0-954f10683f.clean
-- The Fortran compiler identification is unknown
-- No Fortran compiler found on the PATH. Using MinGW gfortran!
-- Using msys root at D:/downloads/tools/msys2/6d8be427ceb450c6
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Using msys root at D:/downloads/tools/msys2/aa5af7b2aa7e90e8
-- Fixing pkgconfig file: D:/packages/lapack-reference_x86-windows/lib/pkgconfig/blas.pc
-- Fixing pkgconfig file: D:/packages/lapack-reference_x86-windows/lib/pkgconfig/lapack.pc
-- Fixing pkgconfig file: D:/packages/lapack-reference_x86-windows/debug/lib/pkgconfig/blas.pc
-- Fixing pkgconfig file: D:/packages/lapack-reference_x86-windows/debug/lib/pkgconfig/lapack.pc
-- Installing: D:/packages/lapack-reference_x86-windows/share/lapack-reference/copyright
-- Performing post-build validation
-- Performing post-build validation done
Uploaded binaries to 1 HTTP remotes.
Building package lapack-reference[blas-select,core,noblas]:x86-windows... done
Installing package lapack-reference[blas-select,core,noblas]:x86-windows...
Installing package lapack-reference[blas-select,core,noblas]:x86-windows... done
Elapsed time for package lapack-reference:x86-windows: 53.34 s
```
The path _D:/downloads/tools/msys2/aa5af7b2aa7e90e8_ is correct now, whether to merge this PR depends on @BillyONeal 's decision.

**Comment by ras0219** [comment]
The reason the CI didn't detect this issue is that we've added an asset cache (https://github.com/microsoft/vcpkg/blob/master/docs/users/assetcaching.md). This has _greatly_ improved stability of the CI, however it means that it will only check the URL for a given hash once -- after the asset with that hash has been downloaded a single time, we forever more fetch it from the asset cache instead (by hash).

**Pull request merged**
