### PR TITLE
[michaelmiller-sec21] Add new library

### PR DESCRIPTION
**Pull request by MichaelMiller-**
If this PR adds a new port, please uncomment and fill out this checklist:

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [ ] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html).
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [ ] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by MichaelMiller-** [comment]
@microsoft-github-policy-service agree

**Comment by JonLiu1993** [comment]
Tested usage successfully by `sec21:x64-windows`:
````
sec21 provides CMake targets:

find_package(sec21 CONFIG REQUIRED)
target_link_libraries(main PRIVATE sec21::sec21)
````

**Comment by BillyONeal** [comment]
I'm a bit nervous to add this given that the name has no search hits anywhere. As you are upstream, do you have customers who are specifically looking to include this in vcpkg's registry?

Would you accept naming the port `michaelmiller-sec21`?

**Comment by BillyONeal** [comment]
@JavierMatosD @ras0219-msft @data-queue and I agree we want this prefixed. If you have issues with this also consider making a private registry: https://learn.microsoft.com/vcpkg/produce/publish-to-a-git-registry

**Comment by MichaelMiller-** [comment]
> I'm a bit nervous to add this given that the name has no search hits anywhere. As you are upstream, do you have customers who are specifically looking to include this in vcpkg's registry?
I'm aware that the library is not widely used. However, there are already a few users. One of them is an small startup that has realized its dependency management with vcpkg. In case of simplification it would be nice if all dependencies worked via one mechanism. 

> Would you accept naming the port `michaelmiller-sec21`?
Of course I would.

**Comment by MichaelMiller-** [comment]
> Yes it does :)

That would also be fine.

> 
> Note: we (vcpkg) place your PR in draft to give you an opportunity to reply and mark "ready for review". The rationale is that you don't have the ability to add or remove tags in the PR. When you mark "ready for review" we become aware and are able to continue reviewing your PR. If you don't mark "ready for review" we may take a bit longer to notice you've responded. All that to say, please mark this PR "ready for review" once you've applied the recommended changes or responded in one way or another.

Thanks for the clarification.


What still needs to be done so that we can successfully complete the pull request?

**Comment by JonLiu1993** [comment]
We need to change the name of the new port `michaelmiller-sec21`.

**Review by BillyONeal — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the new port!

**Comment by MichaelMiller-** [comment]
Thanks to everyone for the cooperation!

**Pull request merged**
