### PR TITLE
[vcpkg message] Overload cmake function message, add color support

### PR DESCRIPTION
**Pull request by JackBoosY**
This PR will add color support to the message to better remind users.

Windows powershell:
image
Linux bash:
image

- [ ] Docuemnt.
- [ ] Implement
- [ ] Test.

### CODE REVIEW

**Comment by JackBoosY** [comment]
It seems the cmake upstream has some bugs: https://gitlab.kitware.com/cmake/cmake/-/issues/22444

**Comment by BillyONeal** [comment]
Unfortunately this solution relies on VT220 escape codes, meaning it will only work in a Windows 10 terminal and not the Win7/8/8.1 terminals.

I think to merge this we need at least the following:

* Figure out which Windows 10 release added support for VT220 transcoding and only do this on that release and later.
* Ensure that the resulting log files and output on Azure DevOps do not have VT220 escape codes embedded into them. This may require changes to the vcpkg tool to strip them?
* Confirmation by Nicole and/or Robert as our CMake experts that overriding `message` is unlikely to break things. I think this looks fine but I am not confident enough here to say for sure.

I'm not sure that that last bit can happen in 2021 given that Nicole is out with COVID :(

**Comment by BillyONeal** [comment]
It may also be a good idea to match CMake's handling of `CLICOLOR` and `CLICOLOR_FORCE`.

**Comment by strega-nil** [comment]
I think given that CMake's handling is broken here right now, we should at least avoid doing it on Windows; I wouldn't mind doing this on non-Windows, but I'd be much happier if we could figure out how to set console things from CMake. Additionally, this _needs_ to check if `stdout` is a console and only write color codes if so. (as opposed to a log)

**Comment by PhoebeHui** [comment]
Closing this PR since it seems that no progress is being made. Please reopen if work is still being done.

**Pull request closed without merging**
