### PR TITLE
Add arblib

### LINKED ISSUE #1942: Port Request: arblib
Arb is an arbitrary-precision library available at arblib.org. It's currently a pain to build and configure on windows.

### PR DESCRIPTION
**Pull request by ghost**
This is on top of #1988 and #1990.

Closes #1942.

### CODE REVIEW

**Comment by xoviat** [comment]
Unfortunately, this is not pulling in the external symbols like it should. I'll need to investigate why before this can be merged.

**Comment by ras0219-msft** [comment]
Thanks for the PR!

A few things:
* I'm concerned about the copyright for the gettimeofday header and implementation. There's no license attached, so we have no permissions to use it. Ideally, we could find a nice GitHub repo that has the file and a permissive license to the code.
* If someone else uses this same strategy to resolve the gettimeofday issue, you won't be able to static link both libs together because of multiple definitions. I think splitting gettimeofday into a separate library is the right answer here.

**Comment by xoviat** [comment]
@ras0219-msft Please merge the flint2 PR first. It will reduce the diff.

**Comment by xoviat** [comment]
The diff is nice and clean now.

**Comment by alexkaratarakis** [comment]
Thanks for the PR!

**Comment by xoviat** [comment]
You're welcome!

**Pull request merged**
