### PR TITLE
[WIP] Add libstrophe 0.9.2

### PR DESCRIPTION
**Pull request by jubalh**
Add libstrophe XMPP library.

### CODE REVIEW

**Comment by jubalh** [comment]
Inspired by the [Hacktoberfest post](https://open.microsoft.com/2018/09/30/join-hacktoberfest-2018-celebration-microsoft) I intend to add the libstrophe XMPP library.
I read all the vcpkg documentation I could find and looked at the examples of [packaging zlib](https://github.com/Microsoft/vcpkg/blob/master/docs/examples/packaging-zlib.md). libstrophe is using make and configure, so no CMake.

These ports are mentioned as example of non CMake build systems in the zlib example:
* openssl
* ffmpeg

I looked at them and tried to figure out how to use simple configure and make but unfortunately didn't succeed.

My error message in `buildtrees/libstrophe/config-x64-linux-dbg-err.log` reads:

```
CMake Error: The source directory "/home/michael/src/vcpkg/buildtrees/libstrophe/src/libstrophe-0.9.2" does not appear to contain CMakeLists.txt.
```

Which is understandable. I hope that I can get some guidance here on how to proceed with adding a port which uses non CMake build scripts.

**Comment by jubalh** [comment]
@ras0219-msft sorry for the ping. Could you help me with this PR?

**Comment by ras0219-msft** [comment]
Hi @jubalh, sorry for not opening this PR (I was skipping it due to the WIP in the title :))

Looking at libstrophe's Makefile.am[1], it seems the actual build to be performed is _extremely_ simple, so it will honestly be easiest to just replace the build with a simple CMake file.

It looks like it just needs the sources from [2],[3],[4], install the header [5], and link with openssl and expat.

[1] https://github.com/strophe/libstrophe/blob/master/Makefile.am
[2] https://github.com/strophe/libstrophe/blob/master/Makefile.am#L26-L44
[3] https://github.com/strophe/libstrophe/blob/master/Makefile.am#L64
[4] https://github.com/strophe/libstrophe/blob/master/Makefile.am#L68
[5] https://github.com/strophe/libstrophe/blob/master/Makefile.am#L73

**Comment by PhoebeHui** [comment]
@jubalh, thanks for contributing to vcpkg! I checked the test results, all triplets build failed, please let me know if you need logs

**Comment by jubalh** [comment]
Hi @PhoebeHui yeah I was testing on how to add libstrophe to vcpkg, but actually was not very successful in figuring out. If you have any pointers on how to write the cmake it would be appreciated.

**Pull request closed without merging**
