### PR TITLE
Always strip whitespace when calling `uname -m` (fixes #28936)

### LINKED ISSUE #28936: Host architecture detection fails in some cases
**Describe the bug**
The command `uname -m` is used to detect the host architecture, but the output of this command appears to sometimes contain a trailing newline that causes string comparison to fail.

I found this problem when diagnosing why the RPATH was not being patched on an `arm64-linux-dynamic` triplet. It turned out that vcpkg was downloading the x86_64 version of patchelf, which was silently failing to execute.

The failure occurs here:
https://github.com/microsoft/vcpkg/blob/92225e6ce480662b29319d8e917d253976407247/scripts/cmake/vcpkg_find_acquire_program.cmake#L559-L569

The `HOST_ARCH` variable contains a trailing newline character on my ARM64 Ubuntu 20.04 system, which causes the string comparisons to fail. Adding `OUTPUT_STRIP_TRAILING_WHITESPACE` to the `execute_process` call fixes this.

There may also be similar problems in other parts of the code, but I haven't observed any other issues yet. A brief search indicates that there are a few other calls to `uname -m` that also don't trim whitespace on the output.

**Environment**
- OS: Linux (Ubuntu 20.04)
- Architecture: ARM64
- Compiler: GCC 11
- CMake Version: 3.25.0

**To Reproduce**
1. On an ARM64 platform, add some debug print statements in the section of vcpkg_find_acquire_program.cmake mentioned above.
2. Compare the string to "aarch64\n", which evaluates to true.
3. Observe that the x86_64 condition is selected.
 
**Expected behavior**
The aarch64 platform should be detected instead of x86_64

### PR DESCRIPTION
**Pull request by rcoup**
- #### What does your PR fix?

Always strip trailing whitespace when calling `uname -m`. Fixes #28936

The bug report is in `vcpkg_find_acquire_program()`, but this change fixes it everywhere in vcpkg since presumably the same unobvious bug will come back to bite people in other situations.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?

all

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?

Yes

### CODE REVIEW

**Review by BillyONeal — APPROVED** [review]

**Comment by cnSchwarzer** [comment]
Can we make CI rebuild less ports when something changed in vcpkg scripts?

**Comment by rcoup** [comment]
@BillyONeal anything else I need to do here?

**Comment by JackBoosY** [comment]
Depends on https://github.com/microsoft/vcpkg/pull/28922 first.

**Review by JackBoosY — APPROVED** [review]

**Comment by BillyONeal** [comment]
> Can we make CI rebuild less ports when something changed in vcpkg scripts?

If touching a thing that all the ports use, we need to rebuild the ones that use the thing to be sure you didn't break anything.

**Comment by cnSchwarzer** [comment]
> If touching a thing that all the ports use, we need to rebuild the ones that use the thing to be sure you didn't break anything.

Does the CI detects which specific program changed in `vcpkg_find_acquire_program` and filter the ports? 
For example, if only CLANG changed, then only rebuild all portfiles contains `vcpkg_find_acquire_program(CLANG)`

**Comment by BillyONeal** [comment]
Thanks!

**Pull request merged**
