### PR TITLE
Adds PDBs and 64bit builds to PDCurses

### PR DESCRIPTION
**Pull request by jjcamp**
By default, PDCurses builds with debugging information built into the .lib file, but vcpkg seems to prefer PDBs, so this edits the makefile to allow those PDBs to be generated separately.

Also I was able to build and test 64-bit builds by removing the cvtres option that was forcing x86 compiles.

### CODE REVIEW

**Comment by Orvid** [comment]
pdbs should only be required if you're building a dynamic library, shouldn't they?

**Comment by jjcamp** [comment]
> pdbs should only be required if you're building a dynamic library, shouldn't they?
Depends on how the debugging information is added.  The current portfile (and the shipped makefile) use the /pdb:none linker option, which adds debugging information into the .lib itself ([ref](https://msdn.microsoft.com/en-us/library/aa278542(v=vs.60).aspx)).
Regardless, the shipped makefile does not export PDBs for DLLs, so the options are to either use PDBs for both static and dynamic libraries or to use different linker options.

**Comment by jjcamp** [comment]
I may have misunderstood.  I see now that it is possible to use C7 for the lib and the PDB for the dll.

**Comment by ras0219-msft** [comment]
Let me know when you're ready for this to be merged.

**Comment by jjcamp** [comment]
It is ready as of now (previous commit returned C7 debug info).

The package is afflicted by issue #292, but the current version is as well.  And (for me at least) that issue is only with the `:x86-windows` triplet.

**Comment by alexkaratarakis** [comment]
Thanks for the solid work!

**Pull request merged**
