### PR TITLE
[libmysql] Fix issue #5046

### PR DESCRIPTION
**Pull request by PhoebeHui**
libmysql installed failed on Linux, ${CMAKE_SYSTEM_PROCESSOR} didn’t get the value here, apply the patch for fix this issue.

The error message likes:
  CMAKE_REQUIRED_LIBRARIES is set to:
    m;crypt;dl;-lpthread;rt;atomic
  For compatibility with CMake 3.11 and below this check is ignoring it.
Call Stack (most recent call first):
  configure.cmake:188 (CHECK_INCLUDE_FILES)
  CMakeLists.txt:653 (INCLUDE)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at configure.cmake:459 (STRING):
  STRING no output variable specified
Call Stack (most recent call first):
  CMakeLists.txt:653 (INCLUDE)

### CODE REVIEW

**Comment by vicroms** [comment]
Hi Phoebe,  
The real issue we need to solve is why ${CMAKE_SYSTEM_PROCESSOR} is not set to the right value. 
Changes must be made in the Linux toolchain so that the right value is detected and set; l will take a look at this PR during the week.

**Comment by PhoebeHui** [comment]
Thank you Victor for pointing out this!

**Comment by JackBoosY** [comment]
@vicroms , the related PR is #4970.

**Comment by vicroms** [comment]
Superseded by #6442

**Pull request closed without merging**
