### PR TITLE
[gdal] add hdf5 support on windows

### PR DESCRIPTION
**Pull request by xueke114**
**Describe the pull request**

- #### What does your PR fix?  
  - add hdf5 support on windows
  - fix jpeg debug lib file name

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  windows , Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

### CODE REVIEW

**Comment by dg0yt** [comment]
LGTM. I'm surprised that CI didn't complain about the jpeg debug lib name issue.

I will eventually try to use pkgconfig to get the libaries to pass to nmake, instead of hardcoding. But gdal is at the end of the chain, so this is not a blocker for adding HDF5 now. 

There is also a request to add netcdf-c support (#20231). @longhuan2018 showed interest to work on that.

**Comment by dg0yt** [comment]
> would it possible to wrap related code with `if ("hdf5" IN_LIST FEATURES)`?

@Osyotr Is there a particular concern about hdf5? It is already used for non-windows builds. 
The feature doesn't exist yet. I want to elaborate gdal's feature interface, but it needs more work. The activated features must also be in exported configuration information (pkg-config, cmake). To simplify that, I'm working on pc files for gdal's dependencies on windows.
What I do see as a potential problem with hdf5 is the restrictive licensing of the szip dependency of hdf5. At least port netcdf-c doesn't offer to opt out.

**Comment by Osyotr** [comment]
@dg0yt I was interested if this could be trivially switched off without messing with gdal portfile. Thanks for the elaboration.
Less dependencies == less problems ¯\_(ツ)_/¯

**Review by JonLiu1993 — CHANGES_REQUESTED** [review]

**Review by JonLiu1993 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the fix!

**Pull request merged**
