### PR TITLE
[SDL2_xxx]: Add CMake targets for SDL2 addons

### PR DESCRIPTION
**Pull request by Helco**
At the current state one has many difficulties trying to add the SDL2 addons as dependencies (from my own experience on Windows as well as on Linux). I have added CMake targets to link against to have a consistent way to add SDL_image, SDL_Mixer, SDL_ttf and SDL_net to a minimal project in the form:

```
find_package(SDL2 CONFIG REQUIRED)
find_package(SDL2-ttf CONFIG REQUIRED)
find_package(SDL2-image CONFIG REQUIRED)
find_package(SDL2-mixer CONFIG REQUIRED)
find_package(SDL2-net CONFIG REQUIRED)

target_link_libraries(test PRIVATE
    SDL2::SDL2
    SDL2::SDL2_ttf
    SDL2::SDL2_image
    SDL2::SDL2_mixer
    SDL2::SDL2_net
)
```

Most of them only required an CMake export target in their CMakeLists.txt and the removal of some Windows-specific line. For SDL2_ttf the wrong variable to link against freetype was used, causing the freetype dependencies (libpng, zlib, bzip2) to not be linked against.

I have compiled a minimal project to test these changes: https://github.com/Helco/vcpkg-test-sdl2-addons.

Testing was done on:

- [x] Linux
- [x] Windows -  ~(will do shortly)~ tested
- [x] MacOS - ~(help would be appreciated)~ tested

### CODE REVIEW

**Comment by Rastaban** [comment]
Added help wanted tag to hopefully get on OSX insight.

Do you just need someone to clone your test repository and build it on OSX to verify the change?

**Comment by Helco** [comment]
yes I think that would suffice for testing.

a colleague suggested using the TravisCI Mac environment, which I will also try out in a few hours

**Comment by Helco** [comment]
So short summary for the OSX problems:

- SDL2_image uses OSX-specific functionality to load certain images with an objective-c file. I added this file to the build.
- The support of harfbuzz in freetype was disabled but the build was still looking for it and the compiled freetype was expecting it. I disabled it properly

**Comment by lerppana** [comment]
Hi @Helco I saw that we have duplicate pull requests here (#5791). My problem is that even with ${FREETYPE_LIBRARIES} cmake cannot for some reason find the proper header (could be also something wrong with my setup).

**Comment by Helco** [comment]
Hi, sure we can do that, also thanks for the additional testing.

Right now using `Freetype::Freetype` to link against breaks my current setups on Linux and Windows alike, additionally I cannot find where this target is actually defined. Can you point me to it, or make sure you don't have another freetype installation?

**Comment by lerppana** [comment]
I made sure to not have any other installations of freetype and deleted the cmake cache in between builds.

SDL2-ttf depends on freetype. When you install Freetype with vcpkg it reports:

```
The package freetype is compatible with built-in CMake targets:

    find_package(Freetype REQUIRED)
    target_link_libraries(main PRIVATE Freetype::Freetype)
```

so after find_package Freetype::Freetype should be usable? Is this what you mean by asking where it is defined?

**Comment by Helco** [comment]
No unlike some other libraries (like SDL2), freetype provides its own `usage` file with the text you pasted in it. I currently doubt that freetype works like this file says at the moment.

**Comment by lerppana** [comment]
That is true, I opened the Freetype files and have no idea why it works. I´m no cmake expert, does it have some default functionality? I tried other ways of linking, it seems to be case sensitive. It does not find targets 'freetype' or 'freetype::freetype', only with capital 'F' when I use find package with 'Freetype'.

this is from config-x64-windows-out.log:
```
-- Found Freetype: optimized;C:/Users/lassi/Documents/GitHub/vcpkg/installed/x64-windows/lib/freetype.lib;debug;C:/Users/lassi/Documents/GitHub/vcpkg/installed/x64-windows/debug/lib/freetyped.lib (found version "2.9.1") 
```

so it does use freetype from vcpkg?

**Comment by Helco** [comment]
AFAIK there is no such default functionality, it is very weird that the right library files are being printed. I guess an external project using SDL2-tff via vcpkg works on your setup?

**Comment by lerppana** [comment]
Ok so I tested again with my project (on windows) and there seems to be something wrong with linking Freetype::Freetype.

If I SDL2-ttf with Freetype::Freetype setup, external project build  requires to use find_package(Freetype REQUIRED) (but not in target_link_libraries) when linking sdl2-ttf.

If I revert to ${FREETYPE_LIBRARIES} and ${FREETYPE_INCLUDE_DIR_ft2build} on SDL2-ttf build, I can just find_package sdl2-ttf and target_link_libraries SDL2::SDL2_ttf, with no mention to freetype anymore.

I will later today test again with macOS and make sure to clear chaches and hunt down any old installations of freetype.

**Comment by vicroms** [comment]
> I quess this is the official FindFreetype.cmake module?

CMake does ship its own `FindFreetype` module:

> The modules listed here are part of the CMake distribution. Projects may provide further modules; their location(s) can be specified in the CMAKE_MODULE_PATH variable.

https://cmake.org/cmake/help/latest/manual/cmake-modules.7.html#find-module

https://cmake.org/cmake/help/latest/module/FindFreetype.html

**Comment by Helco** [comment]
No I don't see a problem with it as `FREETYPE_INCLUDE_DIRS` also includes `FREETYPE_INCLUDE_DIR_ft2build` and a short test of mine does work. 
With this I guess this PR has come to a successful conclusion.

Thanks again for the help @lerppana and @vicroms.

**Comment by vicroms** [comment]
Thanks for the PR!

**Pull request merged**
