### PR TITLE
[grpc] Update to 1.48.0

### PR DESCRIPTION
**Pull request by Tradias**
Updates gRPC to 1.48.0. This release moved the _grpc_csharp_ext_ into its own repository.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  all, Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  yes

### CODE REVIEW

**Comment by Adela0814** [comment]
Your patch seems to have changed the `crlf`, please revert them. Thanks.

**Comment by Tradias** [comment]
@Adela0814 in which files? Didn't I fix that with this commit https://github.com/microsoft/vcpkg/pull/25914/commits/6bc7c92896f4b3611207acea34c38560c888b4d9 ?

**Comment by Adela0814** [comment]
> @Adela0814 in which files? Didn't I fix that with this commit [6bc7c92](https://github.com/microsoft/vcpkg/commit/6bc7c92896f4b3611207acea34c38560c888b4d9) ?

You can check the following changes in `Files changed`:

- ports/grpc/00005-fix-uwp-error.patch
- ports/grpc/00009-use-system-upb.patch
- ports/grpc/00012-fix-use-cxx17.patch

**Comment by Tradias** [comment]
@Adela0814 Those files actually had CRLF line-endings to begin with, introduced by this pr https://github.com/microsoft/vcpkg/pull/25071, sorry for that.

Now all patches have LF endings thanks to https://github.com/microsoft/vcpkg/commit/6bc7c92896f4b3611207acea34c38560c888b4d9.

**Comment by Adela0814** [comment]
It doesn't matter what it was before, just follow it now, you don't need to convert it to LF. Because it will not be easy to check the changes in this commit.

**Review by Adela0814 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the update!

**Pull request merged**
