### PR TITLE
[vcpkg baseline] Fix baseline regression

### PR DESCRIPTION
**Pull request by JackBoosY**
#15015 update seal to 3.6.1, but forgot to update the version record.

### CODE REVIEW

**Comment by JackBoosY** [comment]
@dan-shaw @BillyONeal Can you please merge this PR quickly?

Thanks.

**Review by NancyLi1013 — APPROVED** [review]

**Comment by BillyONeal** [comment]
This explains why PRbuild didn't catch it:

image

It's a shame we don't have the ability to require a retest after some timeout (like a week)

**Comment by JackBoosY** [comment]
@BillyONeal We may have a robot to handle this automatically.

**Comment by BillyONeal** [comment]
@dan-shaw Since everything is on the floor I'm merging this; please note the above about merging things from almost 2 months ago without retesting

**Pull request merged**
