### PR TITLE
[x264] check exists before rename

### LINKED ISSUE #19792: [x264] build failure
**Host Environment**
- OS: Windows
- Compiler: Visual Studio 2019

**To Reproduce**
`./vcpkg install ffmpeg[avcodec,avformat,swresample,swscale,x264]:default`

**Failure logs** 
```
CMake Error at ports/x264/portfile.cmake:74 (file):
  file RENAME failed to rename

    C:/vcpkg/packages/x264_default/debug/lib/libx264.dll.lib

  to

    C:/vcpkg/packages/x264_default/debug/lib/libx264.lib

  because: The system cannot find the path specified.



Call Stack (most recent call first):
  scripts/ports.cmake:140 (include)


Error: Building package x264:default failed with: BUILD_FAILED
```

**Additional context**
This problem occurs when using non default triplet without building debug libraries, that directory just doesn't exist.

### PR DESCRIPTION
**Pull request by itsmattkc**
**Describe the pull request**

- #### What does your PR fix?  
  Fixes #19792 where the `portfile.cmake` assumes both a debug and release build are present and tries to rename both. If the user is only building a release OR debug version, this will throw an error since one of the files will be missing. This PR adds conditionals to check the `VCPKG_BUILD_TYPE` to see what files should have been built. This was presumed to be better than simply checking if the file exists before renaming, so that an error could still be thrown if the files were erroneously missing for whatever reason.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  All (this patches a Windows issue without affecting other platforms), no I have no updated the CI baseline.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  I believe so. It is short, should be fairly readable, and makes no extraneous changes.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes, a port has been updated and the version database has been updated too as a result.

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Review by JonLiu1993 — APPROVED** [review]

**Comment by cenit** [comment]
new rules suggest that only debug config should be wrapped inside the exists check, and the check should be just "if (NOT VCPKG_BUILD_TYPE)"

**Comment by dg0yt** [comment]
> new rules suggest that only debug config should be wrapped inside the exists check, and the check should be just "if (NOT VCPKG_BUILD_TYPE)"

Do we already actively request this? Can we already point at the guidelines?

**Comment by itsmattkc** [comment]
> new rules suggest that only debug config should be wrapped inside the exists check, and the check should be just "if (NOT VCPKG_BUILD_TYPE)"

What does this mean? Only the debug build should be checked? Do the new rules assume that a release build will always be compiled?

**Comment by cenit** [comment]
yes, because a debug only triplet is totally broken in the vcpkg layout

**Review by JonLiu1993 — APPROVED** [review]

**Comment by BillyONeal** [comment]
> new rules suggest that only debug config should be wrapped inside the exists check, and the check should be just "if (NOT VCPKG_BUILD_TYPE)"

Hmmm sorry I didn't get this memo (but it makes some vague sense). Let me ask around / confirm before proceeding; given that it is a holiday here in the US it will likely be 2021-11-29 before I get a reply, sorry :(

**Comment by BillyONeal** [comment]
Hmmm we can always change it later if we don't like the convention, so I just merged this. Thanks for the fix!

**Pull request merged**
