### PR TITLE
Add ports for libmikmod and allegro5

### PR DESCRIPTION
**Pull request by JesseTG**
I've got ports for two libraries here.  Both libraries are configured to provide as many features as possible.

The libmikmod works as intended.

The allegro5 port, however, stumps me in two ways that keep this PR from being ready to merge:

<s># Error when building in Debug mode (for dynamic builds)
When I try to build allegro5:x86-windows-dbg (i.e. as a DLL in debug mode), I get this error in the installation process after the build is complete:
```
CMake Error at cmake_install.cmake:40 (file):
  file INSTALL cannot find
  "C:/Users/Administrator/Code/vcpkg/buildtrees/allegro5/x86-windows-dbg/lib/Debug/allegro-debug.pdb".
```
There *are* PDB's, but they're in `C:/Users/Administrator/Code/vcpkg/buildtrees/allegro5/x86-windows-dbg/lib` (note the lack of a `Debug` directory).  Any ideas why I'm getting this?
</s>

Resolved with a patch

# D3D9EX support
I assume that CMake will find this if it's actually available, but it doesn't seem to be installed on my system.  Is this available with the vcbuildtools installer?

Also:

# Unrelated: Disabled Features
The following allegro5 features I've disabled because their dependencies are not available in vcpkg (if that changes, possibly by my own hand, I will update the port):
- ModAudio support (needs libdumb which doesn't have a port right now)
- Opus support (libopus is available but libopusfile is not)
- Tremor support (not available on vcpkg)

### CODE REVIEW

**Comment by JesseTG** [comment]
Anyone?

**Comment by Voskrese** [comment]
x86-windows-dbg/lib/Debug/  <- *.pdb
x86-windows-dbg/lib/ <- *.lib
ok install

**Comment by JesseTG** [comment]
@Voskrese I don't understand, can you elaborate?

**Comment by Voskrese** [comment]
@JesseTG если файлы Debug с расширение pdb лежат в папке x86-windows-dbg/lib/Debug, а так же   *.lib в папке x86-windows-dbg/lib/ тогда инсталяция проходит без ошибок

проблема в скрипте порта

> If the Debug files with the extension .PDB lie in the x 86 folder-windows-dbg Debug/lib/, as well as the x 86 folder *.lib-windows-dbg/lib/then installation runs without errors
> 
> the problem in the script of the port

для проверки можете перейти в каталог где лежит файл инсталяции cmake `cmake_install.cmake`
посмотреть его содержимое
для проверки выполнить `cmake.exe -P cmake_install.cmake`

> to verify directory can go to the installation file where lies the cmake cmake cmake_install '. '
> view its contents
> to test run ' cmake.exe-P cmake_install. cmake '

**Comment by JesseTG** [comment]
I'll try later today, thank you.

**Comment by JesseTG** [comment]
@Voskrese I double-checked the paths in my `portfile.cmake`.  I still don't see what could be causing the error.  I think it might be occurring within `vcpkg_install_cmake`.  Or do you mean that allegro5 itself is doing something wrong or unusual in its `CMakeFile.txt`?

**Comment by JesseTG** [comment]
You know what, I'm just going to make a patch.  Fingers crossed.

**Comment by JesseTG** [comment]
Okay, I'm good.  Fixed, merge at will!

**Comment by ras0219-msft** [comment]
Great, thanks for the PR!

**Comment by Voskrese** [comment]
https://github.com/liballeg/allegro5/blob/master/cmake/FindOpus.cmake
`if(OPUS_INCLUDE_DIR)`
opusfile.h
` find_path(OPUS_INCLUDE_DIR opusfile.h PATH_SUFFIXES opus)`
` MSVC built opus may be named opus_static`
opus.h
```
opus_x86-windows\include\opus
    opus.h
    opus_custom.h
    opus_defines.h
    opus_multistream.h
    opus_types.h
```
find_library(OPUS_LIBRARY

как патч opusfile.h -> opus.h
но я не проверял

**Comment by Voskrese** [comment]
D3D9EX
https://github.com/liballeg/allegro5/blob/master/cmake/FindDirectX.cmake

```
check_winsdk_root_dir("[HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Microsoft SDKs\\\\Windows\\\\v7.0;InstallationFolder]")
check_winsdk_root_dir("[HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Microsoft SDKs\\\\Windows\\\\v7.0A;InstallationFolder]")
check_winsdk_root_dir("[HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Microsoft SDKs\\\\Windows\\\\v7.1;InstallationFolder]")
check_winsdk_root_dir("[HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Microsoft SDKs\\\\Windows\\\\v7.1A;InstallationFolder]")
check_winsdk_root_dir("[HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows Kits\\\\Installed Roots;KitsRoot]")
check_winsdk_root_dir("[HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows Kits\\\\Installed Roots;KitsRoot81]")
```
WINSDK_ROOT_DIR= - SDK v7.0 - 8.1 либо DXSDK_DIR=
```
find_component(DINPUT dinput.h dinput8)
find_component(D3D9 d3d9.h dinput8)
find_component(D3DX9 d3dx9.h d3dx9)
find_component(DSOUND dsound.h dsound)
find_component(XINPUT xinput.h xinput)
```
как вариант
check_winsdk_root_dir("[HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows Kits\\\\Installed Roots;KitsRoot10]")

**Pull request merged**
