### PR TITLE
[VCPKG] WinHTTPOption for company Proxy not correctly taken into account

### PR DESCRIPTION
**Pull request by xabbudm**
**Describe the pull request**

Creates a pull request as @PhoebeHui asked for

- What does your PR fix? Fixes issue #
 Fixes issue #9064

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Hi @xabbudm, thanks for the PR!

I made some simplifications to the code:
1. We always use https, so we only need to check HTTPS_PROXY
2. Use `System::get_environment_variable()`
3. Always use the environment var if set, for all systems (including Win10+)

Could you double check that this modified code still meets all your needs?

**Review by xabbudm — COMMENTED** [review]
Hello @ras0219-msft,

thanks for your support! Your changes were the functions I was looking for,  when implementing the fix in the first place.

I pulled your changes and the functionality is as requested! 

With kind regards and have a Happy New Year!

**Pull request merged**
