### PR TITLE
[vcpkg baseline] Fix CI test

### PR DESCRIPTION
**Pull request by JackBoosY**

### CODE REVIEW

**Comment by JackBoosY** [comment]
Now, in most cases, the linux and osx pipelines exit by error:
`[error]PowerShell exited with code '1'.`
Can you see the specific cause in detail on the ci machine?

**Comment by dan-shaw** [comment]
For `kealib`, the repository has been deleted and moved.

**Comment by JackBoosY** [comment]
@dan-shaw Already fixed on my machine, wait for other ports test results.

**Comment by dan-shaw** [comment]
`intel-ipsec` requires NASM, I've just added it to the Linux CI, so we may need to rerun the pipeline

**Comment by dan-shaw** [comment]
For `mongo-cxx-driver` failure (on master), it looks like the ICU library is being auto-detected on `mongo-c-driver` sometimes, which may lead to issues as described here: #7338

**Comment by JackBoosY** [comment]
@dan-shaw After checking `mongo-c-driver`'s `CMakeLists.txt`, I found that `ICU` is an option, so I will set `icu` to `mongo-c-driver` feature.

**Comment by JackBoosY** [comment]
`Monkeys-audio` failed because the source could not be downloaded.

**Comment by JackBoosY** [comment]
Now the last failing item is `llvm`.

**Comment by dan-shaw** [comment]
I'm OK with failing llvm on the baseline. We are going to update `llvm` soon #10295

**Comment by JackBoosY** [comment]
@dan-shaw The llvm failure is:
```
Creating llvm-ranlib.exe
Creating llvm-lib.exe
Creating llvm-dlltool.exe
CMake Error at tools/llvm-lto/cmake_install.cmake:36 (file):
  file INSTALL cannot copy file
  "C:/vsts/_work/4/s/buildtrees/llvm/x64-windows-rel/bin/llvm-lto.exe" to
  "C:/vsts/_work/4/s/packages/llvm_x64-windows/tools/llvm/llvm-lto.exe".
Call Stack (most recent call first):
  tools/cmake_install.cmake:41 (include)
  cmake_install.cmake:63 (include)
```

I've seen this many times and don't know what went wrong. Maybe a permission issue? Or is it a disk space issue?

**Comment by dan-shaw** [comment]
@JackBoosY I'm not sure. I would need to investigate.

**Comment by PhoebeHui** [comment]
Similar  issue offen hanppen to llvm, see https://github.com/microsoft/vcpkg/pull/10051#issuecomment-587984005, rerun the PR on windows.

**Comment by JackBoosY** [comment]
Trying to remove default feature `tools` to resolve this issue completely.

**Comment by JackBoosY** [comment]
```
LINK : fatal error LNK1201: error writing to program database 'C:\vsts\_work\4\s\buildtrees\llvm\x64-windows-static-rel\bin\c-index-test.pdb'; check for insufficient disk space, invalid path, or insufficient privilege
```

**Comment by PhoebeHui** [comment]
@dan-shaw, could you help have a look?

**Comment by PhoebeHui** [comment]
@JackBoosY, could you disable llvm in baseline temporarily for unblocking other PRs?

**Pull request merged**
