### PR TITLE
[mathgl] draft port

### PR DESCRIPTION
**Pull request by cenit**
#6462 this is just a quick draft of a port. It builds on linux with default features, didn't check anything apart from it

### CODE REVIEW

**Review by Neumann-A — CHANGES_REQUESTED** [review]
Before you use file rename, remove pls make sure that the file exist.

**Comment by cenit** [comment]
@cbezault please let me know regressions. I hope @AntonioMiguel can try this PR, for me it's ready if there are no regressions

**Comment by AntonioMiguel** [comment]
**vcpkg install mathgl:x64-windows**

     works without any problem in windows 10 

Thanks cenit for your work

**Comment by cenit** [comment]
@cbezault any update? Looks like @AntonioMiguel is using the port successfully. Shall we merge?

**Comment by ras0219-msft** [comment]
LGTM, thanks for the PR!

**Pull request merged**
