### PR TITLE
[vulkan-sdk-*] Update to 1.3.296

### PR DESCRIPTION
**Pull request by siukosev**
- [ ] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [ ] SHA512s are updated for each updated download.
- [ ] The "supports" clause reflects platforms that may be fixed by this new version.
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [ ] Any patches that are no longer applied are deleted from the port's directory.
- [ ] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [ ] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by siukosev** [comment]
@microsoft-github-policy-service agree

**Comment by siukosev** [comment]
vulkan-loader arm64 build still failing for some reason. Worked on my PC. I will investigate it tomorrow

**Comment by LilyWangLL** [comment]
All features passed with following triplets:
```
x86-windows
x64-windows
x64-windows-static
```

**Review by LilyWangLL — DISMISSED** [review]

**Review by BillyONeal — APPROVED** [review]

**Comment by BillyONeal** [comment]
I replaced the checked in patch with upstream's actual commits in vulkan-loader so that it's clear we're applying something upstream agrees with. Thanks for the update!

**Pull request merged**
