### PR TITLE
[pixman] fix build failure on ARM32 due to sse2

### LINKED ISSUE #14178: [pixman] build failure on ARM32 due to -msse2
**Host Environment**
- OS: Linux Raspbian Buster 10.6 arm7l (32-bit)
- Compiler: gcc 8.3.0

**To Reproduce**
`./vcpkg install pixman`

**Failure logs** 

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.
```
cc: error: unrecognized command line option '-msse2'
```

* The CMakeFile adds -msse2 if you're on UNIX and you have 32-bit pointers.
* This fails on ARM32.
* The solution is probably to add a check for X86 to the if-statement or perhaps better: just check the USE_SSE2 variable.
* Looking for AMD64 is probably unnecessary since SSE2 is always enabled on x64_64 with gcc.

### PR DESCRIPTION
**Pull request by lindkvis**
* CMakeFile.txt fix: Use the USE_SSE2 flag in the if-statement to apply '-msse2'.
* This fixes #14178 since USE_SSE2 is not enabled on ARM.

### CODE REVIEW

**Review by NancyLi1013 — COMMENTED** [review]
Please also bump the version in CONFIL file.
Update

`Version: 0.38.4-1`

as

```
Version: 0.38.4
Port-Version: 5
```

**Comment by lindkvis** [comment]
> 
> 
> Please also bump the version in CONFIL file.
> Update
> 
> `Version: 0.38.4-1`
> 
> as
> 
> ```
> Version: 0.38.4
> Port-Version: 5
> ```

I assume you mean CONTROL file ... but Port-Version: 5? I don't get that one. The current upstream version appears to be 

> 
> 
> Please also bump the version in CONFIL file.
> Update
> 
> `Version: 0.38.4-1`
> 
> as
> 
> ```
> Version: 0.38.4
> Port-Version: 5
> ```

Hi @NancyLi1013  . I assume you mean the CONTROL file. I'm new to contributing to vcpkg and CONFIL isn't something that appears anywhere.

And when you say Port-Version: 5, that makes little sense to me. I see you use Port-Version for build changes to the port that doesn't change anything upstream. The current upstream version appears to be 0.38.4 so a Port-Version: 5 isn't obviously correct to me as 0.38.4 is actually the upstream version.

But previously the version was 0.38.4-1 which appears to break the VCPKG guidelines as the -1 is just added in VCPKG and not upstream. So the previous version should probably just have been 0.38.4 (omitting the -1).

The intuitively correct way of handling this (keeping in mind the past version was probably wrong?) is the following:
Version: 0.38.4
Port-Version: 2

This way we treat the previous commit as Port-Version 1 and increment it by one now. This is what I've altered in the pull request now. If this isn't correct please advise as to why.

**Comment by NancyLi1013** [comment]
Sorry, It's my fault.

You're right, it's in CONTROL file.

**Comment by lindkvis** [comment]
Thank you @NancyLi1013 . In which case, the pull request is already updated.

**Review by NancyLi1013 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
