### PR TITLE
[opencv] Update to OpenCV 3.4.4

### PR DESCRIPTION
**Pull request by UnaNancyOwen**
Update opencv port to [OpenCV 3.4.4](https://github.com/opencv/opencv/releases/tag/3.4.4).
It is able to builds with enabled dnn module.

Install Test: <code>./vcpkg install opencv[ffmpeg,ipp,dnn,contrib]</code>
* [x] x64-windows
* [x] x86-windows
* [x] x64-windows-static
* [x] x86-windows-static

@cenit Please check this port. Thanks,

Future Works: If this OpenCV 3.4.x port is stable, Let's start move this port to opencv3 and implement update to OpenCV 4.x. Discussion https://github.com/Microsoft/vcpkg/issues/4758

### CODE REVIEW

**Comment by cenit** [comment]
I just realized that `opencv[gdcm]` is broken (the same in the accepted port). Shall we fix it before merging this one?
I think that the problem relies on the `gdcm2` port itself, that correctly removes the `debug/include` folder but leaves the installation with broken paths...

**Comment by cenit** [comment]
Of course that would mean another PR for that problem, but I'd like to see a properly and thoroughly checked port for OpenCV once in a while... I think it deserves this treatment!

**Comment by cenit** [comment]
also `opencv[sfm]` is broken because the dependency walker (for static build at least) goes to `gflags-static.lib` also for debug builds, instead of `gflags-staticd.lib`

**Comment by twMr7** [comment]
> also `opencv[ovis]` is broken in the accepted port, I will analyse your PR just after I finished with that one... Just leaving comments here as notes to what to check ;)

Ogre::PixelFormat::PF_DEPTH16 required new 1.11.3 version of Ogre, please see PR #4845.

**Comment by cenit** [comment]
I have some problems also with `opencv[dnn]` due to `libprotobuf` linking mismatch... (again, not specifically to your PR, it is the same in the published port). It seems that `opencv` is used a lot here, am I the only one seeing all these problems?
It was a _long_ time i was not updating my vcpkg installation, it seems that it was a mistake starting updating... to be honest, `vcpkg` concept is great, but the realization seems still very far...

**Comment by UnaNancyOwen** [comment]
Is that a problem in this port? or dependency ports?
First of all, I think that it is necessary to find out whether the cause of problem is either port.

**Comment by cenit** [comment]
it can be both and should be analysed thoroughly.
I did some other tests and also `opencv[openexr]` is broken, because the ilmimf lib which is linked against is always the debug one, also in release mode.
When I did that huge work on this port I devoted a lot of time fixing many dependencies, which meant have them properly installed, expose a working `config` or `module` for cmake, then removing the custom files that OpenCV devs like to use (instead of the official ones). I think that many regressions happened in this year and I'd prefer a 3.4.3 *really* working port instead of a rushed 4.0 (or even 3.4.4)

**Comment by UnaNancyOwen** [comment]
I sent pull request #4820 to update openexr. Please test this port.

**Comment by cenit** [comment]
#4861 fixes the `opencv[dnn]` feature, fixing the `libprotobuf` linking

**Comment by twMr7** [comment]
> I just realized that `opencv[gdcm]` is broken (the same in the accepted port). Shall we fix it before merging this one?
> I think that the problem relies on the `gdcm2` port itself, that correctly removes the `debug/include` folder but leaves the installation with broken paths...

gdcm2 problem shall be fixed by PR #4880

**Pull request closed without merging**
