### PR TITLE
[catch2] build static lib on WIN32

### LINKED ISSUE #26880: [catch2] windows build of catch2 should be using static build
Catch2 recently enabled being built as a dynamic library, but it does not provide export macros. (And likely never fully will)

On Linux this is fine-ish due to symbols being visible by default, and variables being merged across dynamic libraries. On Windows this is an issue, because CMake's option for exporting all symbols on Windows cannot handle variables. Variables still need to be `dllimport`ed, and if they aren't, linking Catch2 does not work the way it should.

Combined with the default Windows triplet using dynamic linking for everything, this is kind of a big issue for people using Catch2 v3 through vcpkg.

### PR DESCRIPTION
**Pull request by FrankXie05**
Fix #26880 

[catch2] enables dynamic builds after version 3.10, but on windows it fails to provide exported symbols.

Error:
````
1>------ Build started: Project: tests, Configuration: Debug x64 ------
1>tests.cpp
1>tests.obj : error LNK2001: unresolved external symbol "public: static int Catch::StringMaker<double,void>::precision" (?precision@?$StringMaker@NX@Catch@@2HA)
1>C:\ubuntu\temp\msvc-sln\Debug\tests.exe : fatal error LNK1120: 1 unresolved externals
1>Done building project "tests.vcxproj" -- FAILED.
````

### CODE REVIEW

**Comment by Osyotr** [comment]
Why patch instead of `vcpkg_check_linkage`?

**Comment by FrankXie05** [comment]
@Osyotr I don't want to break the other triplets.

**Comment by Osyotr** [comment]
You won't break other triplets.

**Comment by FrankXie05** [comment]
@Osyotr 

> Why patch instead of `vcpkg_check_linkage`?

Best way, thanks for the reminder. :)

**Review by Adela0814 — APPROVED** [review]

**Pull request merged**
