### PR TITLE
[openssl] Fix armv8 asm [fastrtps] Fix configure race

### LINKED ISSUE #33394: [<openssl:arm64-android>] <Unable to compile>
### Is your feature request related to a problem? Please describe.

I need to use the curl API which depends on openssl for MAUI project with VC++ Android/Windows

I started having trouble with ANDROID_NDK_HOME which by default looks for the NDK under the SDK installed by Xamarin "C:\Program Files (x86)/Android/android-sdk/ndk-bundle" which contains spaces and especially a '(' which produces an erroneous makefile.

### Proposed solution

I ended up solving the problem by forcing an environment variable ANDROID_NDK_HOME = "C:\Microsoft\AndroidNDK64\android-ndk-r13b\" which corresponds to the installed NDK
by Visual Studio with the Workload "Mobile development with C++"

I didn't understand the C:\dev\vcpkg\scripts\toolchains\android.cmake code:

```
if(DEFINED ENV{ANDROID_NDK_HOME})
    set(ANDROID_NDK_HOME $ENV{ANDROID_NDK_HOME})
else()
    set(ANDROID_NDK_HOME "$ENV{ProgramData}/Microsoft/AndroidNDK64/android-ndk-r13b/")
    if(NOT EXISTS "${ANDROID_NDK_HOME}")
        # Use Xamarin default installation folder
        set(ANDROID_NDK_HOME "$ENV{ProgramFiles\(x86\)}/Android/android-sdk/ndk-bundle")
    endif()
endif()
```

where `$ENV{ProgramData} = "C:\ProgramData"` ?

But I still couldn't compile openssl with aarch64-linux-android ABI arm64-v8a triplet
=> crypto/aes/aesv8-armx.S:4:1: error: unknown directive .arch armv8-a+crypto

this seems to stumble on the crypto assembler compilation which does not recognize the armv8-a architecture with Clang

It seems that one of the solutions is to define no-asm to force the compilation of crypto in C language : https://stackoverflow.com/a/70848996

I ended up finding the error in C:\dev\vcpkg\ports\openssl\unix\portfile.cmake lines 48-50 :

```
if(VCPKG_DETECTED_CMAKE_ANDROID_ARCH STREQUAL "arm" AND NOT VCPKG_DETECTED_CMAKE_ANDROID_ARM_NEON)
    vcpkg_list(APPEND CONFIGURE_OPTIONS no-asm)
endif()

```
and I propose to add arm64:

```
if((VCPKG_DETECTED_CMAKE_ANDROID_ARCH STREQUAL "arm" OR VCPKG_DETECTED_CMAKE_ANDROID_ARCH STREQUAL "arm64") AND NOT VCPKG_DETECTED_CMAKE_ANDROID_ARM_NEON)
    vcpkg_list(APPEND CONFIGURE_OPTIONS no-asm)
endif()
```

which allowed me to compile successfully.

### Describe alternatives you've considered

It remains a pity not to be able to compile the crypto module in assembler and to have to sacrifice performance but we have to wait for clang and openssl to solve the problem.

### Additional context

Environment :
Visual Studio 2022 Community 17.7 Windows 10
vcpkg 2023-08-09-9990a4c9026811a312cb2af78bf77f3d9d288416

### PR DESCRIPTION
**Pull request by dg0yt**
Reverts #33421 which blindly disabled asm for arm64-android.
Fixes #33394. Tested with Android NDK r23c and r15c.

- [x] Upstream the patch.

### CODE REVIEW

**Comment by dg0yt** [comment]
https://github.com/openssl/openssl/pull/21938, https://github.com/openssl/openssl/pull/21939

**Comment by dg0yt** [comment]
CC @Lau69 @JonLiu1993

**Comment by dg0yt** [comment]
OpenSSL merged my fixes today.

**Comment by BillyONeal** [comment]
Thanks for the fix!

**Pull request merged**
