### PR TITLE
[gettext] fix ios compile, add ios support to vcpkg_configure_make

### PR DESCRIPTION
**Pull request by russelltg**
* Fix gettext port by specifying that gid_t is in sys/types.h
* Make sure to gather CMAKE_OSX_SYSROOT in get_cmake_vars
* Make sure to set --host when compiling for ios

I do have a few questions:
* Does my implementation of `z_vcpkg_determine_autotools_target_arch_ios` make any sense? I honestly felt confused that `z_vcpkg_determine_autotools_target_arch_mac` defaults to `VCPKG_DETECTED_CMAKE_HOST_SYSTEM_PROCESSOR` instead of `VCPKG_TARGET_ARCHITECTURE`. arm64 is an acceptable target architecture on iOS, it seems, no need to translate to aarch64
* Should I make the same changes to `ports/vcpkg-cmake-get-vars/cmake_get_vars/CMakeLists.txt`?

- #### What does your PR fix?
  Fixes gettext port on iOS, and maybe some others too. Supersedes #26519

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  arm64-ios, arm-ios

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

### CODE REVIEW

**Comment by russelltg** [comment]
So it seems like the libraries are LGPL and binaries are GPL: https://www.gnu.org/software/gettext/manual/html_node/Licenses.html

How should that be reflected in the `"license"` field?

**Comment by dg0yt** [comment]
> How should that be reflected in the `"license"` field?

Conditions can't be expressed, so you have to use `null` (without quotes) which means "Read the `copyright` file".
In some ports, I added conditional output to the `copyright` file, but gettext probably needs work.

**Comment by m-kuhn** [comment]
See also https://github.com/microsoft/vcpkg/pull/25670

**Review by JackBoosY — APPROVED** [review]

**Comment by m-kuhn** [comment]
@russelltg in order to mutualize the efforts as much as possible and avoid duplicate work and merge conflicts, could you check if https://github.com/microsoft/vcpkg/pull/25670 also solves your `gettext` issues, so we can abandon one or the other? On the script front, #25670 tries to harmonize things between meson and autoconf as well as between macos and ios (see triplets).

If there is something that still needs to be done for `gettext`, that can also be ported there.

If there is good reasons to stick to this work instead, I can also dismiss mine.

**Comment by russelltg** [comment]
Your PR's do everything needed for gettext, I'm pretty sure. I'll close this one for now and will reopen a new PR with the gettext change when #25670 lands.

**Pull request closed without merging**
