### PR TITLE
[kf5configwidgets] new port

### PR DESCRIPTION
**Pull request by wrobelda**
**Describe the pull request**

Adds kf5configwidgets. Depends on:
- #16561 
- #16559
- ~~#13518~~ #18159. Will rebase once it gets merged. 
- #19168 . Will rebase once it gets merged. 
- #19203. Will rebase once it gets merged.

- Which triplets are supported/not supported? Have you updated the CI baseline?
All official should be supported.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

### CODE REVIEW

**Comment by JackBoosY** [comment]
Pinging @wrobelda for response. Is work still being done for this PR?

**Comment by wrobelda** [comment]
> Pinging @wrobelda for response. Is work still being done for this PR?

@JackBoosY as noted in the pull request description, this port depends on a number of other ports, some of which are still pending inclusion in the master. Once that's done, I'll rebase and mark this as "ready for review"

**Comment by JackBoosY** [comment]
Ready for review now?

**Comment by wrobelda** [comment]
> Ready for review now?

No, as says in the description, this depends on another PR that's pending acceptance.

**Comment by wrobelda** [comment]
@JackBoosY this port no longer depends on another PR, all the dependencies were merged to master.

**Review by JackBoosY — APPROVED** [review]
Did you test features?

**Comment by wrobelda** [comment]
> Did you test features?

Yes, the designer plugin is generated correctly when feature is enabled.

**Comment by BillyONeal** [comment]
Thanks folks!

**Pull request merged**
