### PR TITLE
[BitSerializer] Update to v0.70

### PR DESCRIPTION
**Pull request by PavelKisliak**
I'd like to update port file for [BitSerializer](https://github.com/PavelKisliak/BitSerializer) to latest version 0.70 ([Release notes](https://github.com/PavelKisliak/BitSerializer/releases/tag/v0.70)).

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version.~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file~~.
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by LilyWangLL** [comment]
Thanks for your update, please add [`DISABLE_PARALLEL_CONFIGURE`](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/maintainers/functions/vcpkg_cmake_configure.md#disable_parallel_configure) to fix the following error:
```
CMake Error at CMakeLists.txt:94 (configure_file):
  No such file or directory
```

**Comment by LilyWangLL** [comment]
All features passed with following triplets:
```
x86-windows
x64-windows
x64-windows-static
```
Usage test passed on `x64-windows`.

**Comment by PavelKisliak** [comment]
> Thanks for your update, please add [`DISABLE_PARALLEL_CONFIGURE`](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/maintainers/functions/vcpkg_cmake_configure.md#disable_parallel_configure) to function `vcpkg_cmake_configure` for fixing the following error:
> 
> ```
> CMake Error at CMakeLists.txt:94 (configure_file):
>   No such file or directory
> ```

Fixed, thank you!

**Review by LilyWangLL — APPROVED** [review]

**Pull request merged**
