### PR TITLE
[protobuf] upgrade to latest release (v3.18.0)

### LINKED ISSUE #18382: [protobuf] update to v3.17.3
Library name: protobuf [repo](https://github.com/protocolbuffers/protobuf)

New version number: v3.17.3

Other information that may be useful (release notes, etc...)

See https://github.com/protocolbuffers/protobuf/releases/tag/v3.17.3

The version on vcpkg is a few versions behind at the 3.15.x series.

### PR DESCRIPTION
**Pull request by coryan**
Updates `protobuf` to the latest release (v3.18.0)

- #### What does your PR fix?  

  Fixes #18382 

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  

No change.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)? 

Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  

Yes

### CODE REVIEW

**Comment by coryan** [comment]
I am not sure, but the failures seem unrelated. If I am wrong just let me know.

**Comment by coryan** [comment]
The break is related to my change, protobuf deprecated a function, that OpenCV still uses:

https://github.com/protocolbuffers/protobuf/commit/cda795437d00a15f375d3d5e2659adac715459c6

I do not have time until 2021-09-21, but I think we should patch OpenCV.

**Comment by JonLiu1993** [comment]
> The break is related to my change, protobuf deprecated a function, that OpenCV still uses:
> 
> [protocolbuffers/protobuf@cda7954](https://github.com/protocolbuffers/protobuf/commit/cda795437d00a15f375d3d5e2659adac715459c6)
> 
> I do not have time until 2021-09-21, but I think we should patch OpenCV.

OK, I will provide you with the error log first and wait for you to fix it as soon as possible. Thank you
https://dev.azure.com/vcpkg/public/_build/results?buildId=59846&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by coryan** [comment]
Woo hoo!  All the tests pass now. Please take another look.

**Review by JonLiu1993 — APPROVED** [review]

**Comment by JonLiu1993** [comment]
Feature zlib tested successfully in the following triplet:
- x86-windows
- x64-windows
- x64-windows-static

**Comment by strega-nil-ms** [comment]
Thanks @coryan!

**Comment by cenit** [comment]
same patch should have been applied to opencv3 too. I will open a PR asap for it ;)

**Pull request merged**
