### PR TITLE
[darknet] update to latest version

### PR DESCRIPTION
**Pull request by cenit**
- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  All, Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

### CODE REVIEW

**Comment by dg0yt** [comment]
Can you check if darknet's opencv\* dependencies really need the default features of opencv\*?
ATM darknet[opencv\*] prevents opting out from default features of opencv. Cf. https://github.com/microsoft/vcpkg/issues/20471#issuecomment-1086560192.

**Comment by JonLiu1993** [comment]
@cenit ,Thanks for your pr, When I run the comand "./vcpkg install darknet[*]:x64-windows" tested the features locally, It failed :
````
CMake Error at ports/opencv2/portfile.cmake:6 (message):
  OpenCV 4 is installed, please uninstall and try again:

      vcpkg remove opencv4
Call Stack (most recent call first):
  scripts/ports.cmake:145 (include)


error: building opencv2:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
````
Then I ran the command "./vcpkg remove opencv4:x64-windows" to remove the opencv4 port and tried the command "./vcpkg install darknet[*]:x64-windows" again, but still got this error

**Comment by cenit** [comment]
yes, darknet is one of the very few ports that do not obey to new rules, meaning that there are features mutually exclusive and not additive.
In fact, if you use opencv-base, you cannot ask for opencv2-base or opencv3-base, because the opencv version on which they depend are incompatible between themselves

**Comment by JonLiu1993** [comment]
Tested fearture [cuda,cudnn,full,opencv-base,opencv-cuda] successfully in the  x64-windows triplet

**Review by JonLiu1993 — APPROVED** [review]

**Comment by strega-nil-ms** [comment]
Thanks!

**Pull request merged**
