### PR TITLE
[libarchive] update to 3.7.0

### PR DESCRIPTION
**Pull request by mostynb**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by Cheney-W** [comment]
About the changes of [disable-warnings.patch](https://github.com/microsoft/vcpkg/pull/32703/files#diff-d028128f11db99dcf5453ae5fd65feaa2c064aa07efdb096a0dac7c6b7521401), [fix-buildsystem.patch](https://github.com/microsoft/vcpkg/pull/32703/files#diff-2d07e9f7632fae8681ce25b87ca19a39dcbc5709674703ae1f7c8593781b7e5c) and [fix-cpu-set.patch](https://github.com/microsoft/vcpkg/pull/32703/files#diff-44d37f6c8dcb83e90c281ed5e2ee0e737687dc60343b955f26b1e8478487c7c4)
Please do not modify the line break, as this will cause the entire file to appear in different file comparisons.

**Comment by Cheney-W** [comment]
Could you please solve the tesseract:x64-osx failed?
Error log: https://dev.azure.com/vcpkg/public/_build/results?buildId=91991&view=artifacts&pathAsName=false&type=publishedArtifacts
```
Undefined symbols for architecture x86_64:
  "_mbedtls_ripemd160_finish_ret", referenced from:
      ___archive_ripemd160final in libarchive.a(archive_digest.c.o)
  "_mbedtls_ripemd160_free", referenced from:
      ___archive_ripemd160final in libarchive.a(archive_digest.c.o)
  "_mbedtls_ripemd160_init", referenced from:
      ___archive_ripemd160init in libarchive.a(archive_digest.c.o)
  "_mbedtls_ripemd160_starts_ret", referenced from:
      ___archive_ripemd160init in libarchive.a(archive_digest.c.o)
  "_mbedtls_ripemd160_update_ret", referenced from:
      ___archive_ripemd160update in libarchive.a(archive_digest.c.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by mostynb** [comment]
> About the changes of [disable-warnings.patch](https://github.com/microsoft/vcpkg/pull/32703/files#diff-d028128f11db99dcf5453ae5fd65feaa2c064aa07efdb096a0dac7c6b7521401), [fix-buildsystem.patch](https://github.com/microsoft/vcpkg/pull/32703/files#diff-2d07e9f7632fae8681ce25b87ca19a39dcbc5709674703ae1f7c8593781b7e5c) and [fix-cpu-set.patch](https://github.com/microsoft/vcpkg/pull/32703/files#diff-44d37f6c8dcb83e90c281ed5e2ee0e737687dc60343b955f26b1e8478487c7c4) Please do not modify the line break, as this will cause the entire file to appear in different file comparisons.

I will fix this (I had to rebase the patches for them to apply, and I happened to do that on linux).

> Could you please solve the failure of tesseract:x64-osx? Error log: https://dev.azure.com/vcpkg/public/_build/results?buildId=91991&view=artifacts&pathAsName=false&type=publishedArtifacts
> 
> ```
> Undefined symbols for architecture x86_64:
>   "_mbedtls_ripemd160_finish_ret", referenced from:
>       ___archive_ripemd160final in libarchive.a(archive_digest.c.o)
>   "_mbedtls_ripemd160_free", referenced from:
>       ___archive_ripemd160final in libarchive.a(archive_digest.c.o)
>   "_mbedtls_ripemd160_init", referenced from:
>       ___archive_ripemd160init in libarchive.a(archive_digest.c.o)
>   "_mbedtls_ripemd160_starts_ret", referenced from:
>       ___archive_ripemd160init in libarchive.a(archive_digest.c.o)
>   "_mbedtls_ripemd160_update_ret", referenced from:
>       ___archive_ripemd160update in libarchive.a(archive_digest.c.o)
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```

I am working on it, but I am at the limits of my understanding of cmake.

On mac, libarchive links against libmbedcrypto (from mbedtls), so consumers of libarchive like tesseract also need to link with that. But I haven't been able to figure out how to pass that information on from the libarchive build.

**Comment by data-queue** [comment]
Closing this PR, see #36677

**Pull request closed without merging**
