### PR TITLE
[opencv4] Update OpenCV4 to 4.5.0

### LINKED ISSUE #13098: [OpenCV] update to 4.4
Library name: OpenCV

New version number: 4.4.0

### PR DESCRIPTION
**Pull request by sgreenlay**
Updates the OpenCV4 port to 4.5.0

### CODE REVIEW

**Comment by NancyLi1013** [comment]
Hi @sgreenlay 
Thanks for this PR.
The changes seem good now.

Have you tested these features in this PR?

**Comment by sgreenlay** [comment]
I built opencv4[core] for x86-uwp, x64-uwp and arm64-uwp and successfully ran some CV test programs with each. Is there an opencv4 test suite that you'd like me to run?

**Comment by NancyLi1013** [comment]
> I built opencv4[core] for x86-uwp, x64-uwp and arm64-uwp and successfully ran some CV test programs with each. Is there an opencv4 test suite that you'd like me to run?

There are no any test suits to run. Currently, we need to test all features manually.

Note: Please resolve the conflicts first.

**Comment by NancyLi1013** [comment]
@sgreenlay 

Would you like to test these features on Windows platform (`x86-windows, x64-windows-static`) if possible?

**Comment by NancyLi1013** [comment]
@sgreenlay Could you please resolve the conflicts first?

**Comment by NancyLi1013** [comment]
Related issue #14368

**Pull request closed without merging**
