### PR TITLE
[libjuice] Libjuice/update v0.9.6

### PR DESCRIPTION
**Pull request by Nemirtingas**
**Describe the pull request**

- #### What does your PR fix?  
Updates libjuice.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
Same as before.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
Yes.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
Yes.

Will need to update libdatachannel at the same time: #22531.

### CODE REVIEW

**Comment by JonLiu1993** [comment]
@Nemirtingas, thanks for the PR, it looks like the ci test fails on all triples:

This is the error log, please take a look:
````
-- Found Threads: TRUE  
-- Found OpenSSL: D:/installed/x86-windows/debug/lib/libcrypto.lib (found version "1.1.1m")  
-- Configuring done
CMake Error at C:/a/1/s/scripts/buildsystems/vcpkg.cmake:578 (_add_library):
  Target "datachannel" links to target "LibJuice::juice" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:219 (add_library)
````

**Comment by Nemirtingas** [comment]
> @Nemirtingas, thanks for the PR, it looks like the ci test fails on all triples:
> 
> This is the error log, please take a look:
> 
> ```
> -- Found Threads: TRUE  
> -- Found OpenSSL: D:/installed/x86-windows/debug/lib/libcrypto.lib (found version "1.1.1m")  
> -- Configuring done
> CMake Error at C:/a/1/s/scripts/buildsystems/vcpkg.cmake:578 (_add_library):
>   Target "datachannel" links to target "LibJuice::juice" but the target was
>   not found.  Perhaps a find_package() call is missing for an IMPORTED
>   target, or an ALIAS target is missing?
> Call Stack (most recent call first):
>   CMakeLists.txt:219 (add_library)
> ```

Hi, yes but it works after updating libdatachannel: #22531. The target LibJuice::juice has been deprecated and removed in favor of LibJuice::LibJuice.

**Comment by JonLiu1993** [comment]
Depends on pr  #22531.

**Review by JonLiu1993 — APPROVED** [review]

**Comment by Nemirtingas** [comment]
> Depends on pr #22531.

Be careful, #22531 already packs the libjuice update. I don't know which should be merge first or if both should be merged at the same time.

**Comment by JonLiu1993** [comment]
> > Depends on pr #22531.
> 
> Be careful, #22531 already packs the libjuice update. I don't know which should be merge first or if both should be merged at the same time. 

 @Nemirtingas , pr #22531 already packs the libjuice update, we don't need to submit a pr to update it here,

**Comment by Nemirtingas** [comment]
> 

I'm fine with this, but I though it was 1 port/merge request, thats why I created 2.

**Comment by Nemirtingas** [comment]
I've updated #22531 title.

**Comment by JonLiu1993** [comment]
> I've updated #22531 title.

Now I suggest that we close this pr and wait for #22531 merge

**Comment by Nemirtingas** [comment]
Closed on demand. See #22531

**Pull request closed without merging**
