### PR TITLE
libiconv - Fix ICONV_CONST

### PR DESCRIPTION
**Pull request by Mizzrym1**
set value ICONV_CONST because it is used to configure files iconv.h.in and iconv.h.build.in.

### CODE REVIEW

**Comment by LilyWangL** [comment]
@Mizzrym1, thanks for your PR! Can you please correct the Version field in the CONTROL file?

**Comment by LilyWangL** [comment]
@Mizzrym1 Currently, this PR fails on Windows due to exiv2:arm64-windows build failed:
```
vcpkg\buildtrees\exiv2\src\v0.27.2-88a943a608\src\convert.cpp(1548): error C2664: 'size_t libiconv(libiconv_t,const char **,size_t *,char **,size_t *)': cannot convert argument 2 from 'char **' to 'const char **'
```

**Comment by Mizzrym1** [comment]
You had a different function declaration than the function definition
I don't know why you used "#define ICONV_CONST const" probably a better solution would be empty "#define ICONV_CONST"
exiv2 only for __NetBSD__ have const for iconv:
`/* Define to `const' or to empty, depending on the second argument of `iconv'. */
#cmakedefine ICONV_ACCEPTS_CONST_INPUT
#if defined(ICONV_ACCEPTS_CONST_INPUT) || defined(__NetBSD__)
#define EXV_ICONV_CONST const
#else
#define EXV_ICONV_CONST
#endif`
I deleted the const
if 'const' is needed, add in configure exiv2 -DICONV_ACCEPTS_CONST_INPUT=1

**Comment by LilyWangL** [comment]
@Mizzrym1 Could you please aign the Contributor License Agreement?

**Comment by Mizzrym1** [comment]
Ok ;)

**Comment by strega-nil** [comment]
What issue does this solve?

**Comment by LilyWangL** [comment]
Ping @Mizzrym1

**Comment by Mizzrym1** [comment]
I don't understand what to write.
Everything has already been written.
You had a different function declaration than the function definition.
This is only warning on MSVC but error on MINGW.

**Comment by strega-nil** [comment]
Ah, I understand now.

**Pull request merged**
