### PR TITLE
[vcpkg scripts] Remove deprecate functions vcpkg_*_cmake and vcpkg_fixup_cmake_targets

### PR DESCRIPTION
**Pull request by JackBoosY**
Remove these deprecated functions completely since no port uses them.

### CODE REVIEW

**Comment by JackBoosY** [comment]
Depends on https://github.com/microsoft/vcpkg/pull/29882 and https://github.com/microsoft/vcpkg/pull/29883.

**Comment by dg0yt** [comment]
You cannot remove the function names. User ports may depend on them, and in manifest mode, even vcpkg ports will need them forever.

**Comment by JackBoosY** [comment]
> You cannot remove the function names. User ports may depend on them, and in manifest mode, even vcpkg ports will need them forever.

Good point.
However, there is no way to call `vcpkg_cmake_*` / `vcpkg_cmake_config_fixup` in those functions.

**Comment by dg0yt** [comment]
Yes, it is technical debt which cannot be removed (except for a *major* release of vcpkg).
Fortunately, the new GH checks should ensure that these functions are not used in new ports.

**Comment by JackBoosY** [comment]
At least we need a point in time to notify the user that they are about to be removed, like normal 3rd party libraries do.
Let's see what the maintainer team thinks.

**Comment by Neumann-A** [comment]
You cannot remove the scripts due to versioning?

**Comment by JackBoosY** [comment]
> You cannot remove the scripts due to versioning?

Wouldn't versioning affect these scripts?

**Comment by dg0yt** [comment]
> You cannot remove the scripts due to versioning?

These are the unversioned global scripts. Manifest mode allows to install old port versions which rely on these scripts.
There is more such legacy stuff, like some `find_package` particularities in `vcpkg.cmake` which cannot be remove despite better wrappers in current port versions.

**Comment by Neumann-A** [comment]
I mean we could remove them if vcpkg-tool adds an implicit dep to a vcpkg-script port but that comes with its own set of advantages and disadvantages

**Review by BillyONeal — CHANGES_REQUESTED** [review]
I agree with @dg0yt .

**Comment by JackBoosY** [comment]
Okay, so we need to modify our GitHub actions to report error when PR changes contains those deprecated functions right?

**Comment by dg0yt** [comment]
Maybe upgrade selected keywords from warning to error.
https://github.com/microsoft/vcpkg/blob/02ad673d3bf004f17ec780cb6363ba1c7f928851/.github/workflows/untrustedPR.yml#L30

**Comment by JackBoosY** [comment]
Close this PR since it's not appropriate.

**Comment by dg0yt** [comment]
You could also issue a warning at the top of each deprecated function.

**Comment by JackBoosY** [comment]
> You could also issue a warning at the top of each deprecated function.

Will do.

**Pull request closed without merging**
