### PR TITLE
[cgal] fix dependency

### PR DESCRIPTION
**Pull request by moritz-h**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [x] The "supports" clause reflects platforms that may be fixed by this new version.
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

CGAL requires boost-format. Historically this was provided implicitly with `boost-property-tree`, but that was removed in #35693. #36567 tried to fix the same, but only for the `qt` feature.

### CODE REVIEW

**Comment by MonicaLiu0311** [comment]
Please get [failure logs here](https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/102692/artifacts?artifactName=failure%20logs%20for%20x64-linux&api-version=7.1&%24format=zip):
```
Building colmap:x64-linux@2023-10-01...
-- Downloading https://github.com/colmap/colmap/archive/9c704e89ff0a80e797725e112011f9f69e5aa28f.tar.gz -> colmap-colmap-9c704e89ff0a80e797725e112011f9f69e5aa28f.tar.gz...
-- Extracting source /mnt/vcpkg-ci/downloads/colmap-colmap-9c704e89ff0a80e797725e112011f9f69e5aa28f.tar.gz
-- Using source at /mnt/vcpkg-ci/b/colmap/src/f69e5aa28f-361efbb7b2.clean
-- Configuring x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /mnt/vcpkg-ci/downloads/tools/cmake-3.29.2-linux/cmake-3.29.2-linux-x86_64/bin/cmake /mnt/vcpkg-ci/b/colmap/src/f69e5aa28f-361efbb7b2.clean -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/mnt/vcpkg-ci/p/colmap_x64-linux/debug -DFETCHCONTENT_FULLY_DISCONNECTED=ON -DCUDA_ENABLED=OFF -DCMAKE_CUDA_ARCHITECTURES= -DTESTS_ENABLED=OFF -DGIT_COMMIT_ID=9c704e89ff0a80e797725e112011f9f69e5aa28f -DGIT_COMMIT_DATE=2024-05-07 -DOPENMP_ENABLED=ON -DCMAKE_MAKE_PROGRAM=/mnt/vcpkg-ci/downloads/tools/ninja/1.10.2-linux/ninja -DCMAKE_SYSTEM_NAME=Linux -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/mnt/vss/_work/1/s/scripts/toolchains/linux.cmake -DVCPKG_TARGET_TRIPLET=x64-linux -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/mnt/vss/_work/1/s/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=/mnt/vss/_work/1/s -D_VCPKG_INSTALLED_DIR=/mnt/vcpkg-ci/installed -DVCPKG_MANIFEST_INSTALL=OFF
    Working Directory: /mnt/vcpkg-ci/b/colmap/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /mnt/vcpkg-ci/b/colmap/config-x64-linux-dbg-CMakeCache.txt.log
      /mnt/vcpkg-ci/b/colmap/config-x64-linux-dbg-out.log
      /mnt/vcpkg-ci/b/colmap/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  /mnt/vcpkg-ci/installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:276 (vcpkg_execute_required_process)
  ports/colmap/portfile.cmake:46 (vcpkg_cmake_configure)
  scripts/ports.cmake:175 (include)
```
**/mnt/vcpkg-ci/b/colmap/config-x64-linux-dbg-err.log:**
```
CMake Error at /mnt/vcpkg-ci/installed/x64-linux/share/cmake/Qt5DBus/Qt5DBusConfig.cmake:95 (message):
  Library not found: dbus-1
Call Stack (most recent call first):
  /mnt/vcpkg-ci/installed/x64-linux/share/cmake/Qt5DBus/Qt5DBusConfig.cmake:277 (_qt5_DBus_process_prl_file)
  /mnt/vss/_work/1/s/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  /mnt/vcpkg-ci/installed/x64-linux/share/cmake/Qt5ServiceSupport/Qt5ServiceSupportConfig.cmake:231 (find_package)
  /mnt/vss/_work/1/s/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  /mnt/vcpkg-ci/installed/x64-linux/share/cmake/Qt5EglFSDeviceIntegration/Qt5EglFSDeviceIntegrationConfig.cmake:231 (find_package)
  /mnt/vss/_work/1/s/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  /mnt/vcpkg-ci/installed/x64-linux/share/cmake/Qt5Gui/Qt5Gui_QEglFSEmulatorIntegrationPlugin.cmake:8 (find_package)
  /mnt/vcpkg-ci/installed/x64-linux/share/cmake/Qt5Gui/Qt5GuiConfig.cmake:425 (include)
  /mnt/vss/_work/1/s/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  /mnt/vcpkg-ci/installed/x64-linux/share/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake:231 (find_package)
  /mnt/vss/_work/1/s/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  /mnt/vcpkg-ci/installed/x64-linux/share/cmake/Qt5OpenGL/Qt5OpenGLConfig.cmake:231 (find_package)
  /mnt/vss/_work/1/s/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  /mnt/vcpkg-ci/installed/x64-linux/share/cmake/Qt5/Qt5Config.cmake:28 (find_package)
  /mnt/vss/_work/1/s/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
  cmake/FindDependencies.cmake:149 (find_package)
  CMakeLists.txt:86 (include)
```

**Comment by dg0yt** [comment]
> Library not found: dbus-1

Not related to this PR. Retry after #38058.

**Comment by MonicaLiu0311** [comment]
qt5-tools
-
Feature `qdoc` is tested successfully in the following triplet:
```
x86-windows
x64-windows
x64-windows-static
```

**Review by MonicaLiu0311 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the fix!

**Pull request merged**
