### PR TITLE
[zlib-ng] Add compat feature

### PR DESCRIPTION
**Pull request by netcorefan1**
@Neumann-A  [suggested](https://github.com/microsoft/vcpkg/pull/30918#issuecomment-1511219443) the possibility to create a feature rather than a separate port:
> This can either be solved by adding a new port or providing a feature to `zlib-ng` which just builds the source twice with different configure options.

This seems to me a better option because (I believe) it requires no additional maintenance. So, this is going to replace my original pull [request](https://github.com/microsoft/vcpkg/pull/30918).

### Description
With `zlib-ng[compat]` and an overlay port, user can automatically replace `zlib` dependency with `zlib-ng` and take advantage of the speed provided by next gen instructions with no change to the source code. Running `zlib-ng` natively is still the preferred way, but requires changes to the source code and this is not something that all developers are willing to do and here is where `zlib-ng[compat]` comes in handy.

### Please note
I'm new to vcpkg and even to pull requests in general. So, this is to be intended as a prototype that needs to be checked and corrected by experts.

### Issues and concerns
1 - This is the only way I have been able to get both the builds:
```
if ("compat" IN_LIST FEATURES)
   vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        "-DZLIB_FULL_VERSION=${ZLIB_FULL_VERSION}"
        -DZLIB_ENABLE_TESTS=OFF
        -DWITH_NEW_STRATEGIES=ON
        -DZLIB_COMPAT=ON
    OPTIONS_RELEASE
        -DWITH_OPTIM=ON
)
vcpkg_cmake_install()
vcpkg_copy_pdbs()
vcpkg_fixup_pkgconfig()
endif()
```
...and with the following warning:
```
CMake Warning at installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:19 (message):
  vcpkg_cmake_configure already called; this function should only be called
  once.
```
Any attempt to replace the function with `set(VCPKG_CMAKE_CONFIGURE_OPTIONS ...` or `set(ZLIB_COMPAT ON)` result in no output. This is probably something that vcpkg staff can easily fix in no time while I cannot even after hours of trials.

2 - With an empty overlay port (`"dependencies": [ { "name": "zlib-ng", "features": [ "compat" ] } ]`) a package that depends on `zlib` successfully compiles even with the above. However I feel this happens just because "compat' has been the last compiled build. It's unclear how a package determine the correct linkage. I expect that, in the same process, a package can reference `zlib-ng` and another one `zlib-ng[compat]` with no issues as happens with my original pull request.
Unfortunately I cannot test a port that depends on the default `zlib-ng` because there is none in the repo.

Thanks

### CODE REVIEW

**Review by BillyONeal — CHANGES_REQUESTED** [review]
```
Building zlib-ng[compat,core]:x64-windows...
-- Downloading https://github.com/zlib-ng/zlib-ng/archive/2.0.6.tar.gz -> zlib-ng-zlib-ng-2.0.6.tar.gz...
-- Extracting source C:/Dev/vcpkg-downloads/zlib-ng-zlib-ng-2.0.6.tar.gz
-- Using source at C:/Dev/vcpkg/buildtrees/zlib-ng/src/2.0.6-f38bf28750.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Fixing pkgconfig file: C:/Dev/vcpkg/packages/zlib-ng_x64-windows/lib/pkgconfig/zlib-ng.pc
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at C:/Dev/vcpkg-downloads/tools/msys2/9a1ec3f33446b195
-- Fixing pkgconfig file: C:/Dev/vcpkg/packages/zlib-ng_x64-windows/debug/lib/pkgconfig/zlib-ng.pc
CMake Warning at installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:19 (message):
  vcpkg_cmake_configure already called; this function should only be called
  once.
Call Stack (most recent call first):
  ports/zlib-ng/portfile.cmake:23 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)


-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Fixing pkgconfig file: C:/Dev/vcpkg/packages/zlib-ng_x64-windows/lib/pkgconfig/zlib-ng.pc
-- Fixing pkgconfig file: C:/Dev/vcpkg/packages/zlib-ng_x64-windows/lib/pkgconfig/zlib.pc
-- Fixing pkgconfig file: C:/Dev/vcpkg/packages/zlib-ng_x64-windows/debug/lib/pkgconfig/zlib-ng.pc
-- Fixing pkgconfig file: C:/Dev/vcpkg/packages/zlib-ng_x64-windows/debug/lib/pkgconfig/zlib.pc
-- Installing: C:/Dev/vcpkg/packages/zlib-ng_x64-windows/share/zlib-ng/copyright
-- Performing post-build validation
error: The following files are already installed in C:/Dev/vcpkg/installed/x64-windows and are in conflict with zlib-ng:x64-windows
Installed by zlib:x64-windows
bin/zlib.pdb
    bin/zlib1.dll
    debug/bin/zlibd.pdb
    debug/bin/zlibd1.dll
    debug/lib/pkgconfig/zlib.pc
    debug/lib/zlibd.lib
    include/zconf.h
    include/zlib.h
    lib/pkgconfig/zlib.pc
    lib/zlib.lib

Stored binaries in 1 destinations.
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+zlib-ng
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[zlib-ng]+Build+error
Include '[zlib-ng] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-04-07-bedcba5172f5e4b91caac660ab7afe92c27a9895
    vcpkg-scripts version: afbfbbc4b 2023-04-17 (54 seconds ago)
```

I don't think this feature is supportable; to do that someone needs to overlay the zlib port.

**Comment by netcorefan1** [comment]
> I don't think this feature is supportable; to do that someone needs to overlay the zlib port.

Yes, as I stated in the description, it needs an overlay port, but perhaps it could be made part of the vcpkg install process. One rude way I can think of is something like that:
```
if ("compat" IN_LIST FEATURES)
...
    if (WIN32)
        EXECUTE_PROCESS(COMMAND setx VCPKG_OVERLAY_PORTS .//zlib)
    elseif (UNIX)
        EXECUTE_PROCESS(COMMAND  ..)
    endif ()
...
endif()
```
It works fine on my machine and all packages are automatically compiled with zlib-ng compat feature.

I get the same error when there is already a `zlib1.dll` (whether it comes from `zlib-ng[compat]` or `zlib` packages). `zlib-ng[compat]` is not intended to be used without a zlib overlay port. It make no sense trying to load the old `zlib` when the main purpose of the compat feature is to replace it. However, if we also want a package excluded from replacement, than we can rename files.
Also, I'm not sure if I should place a copy of `REMOVE_RECURSE` inside `if ("compat" IN_LIST FEATURES)`.

**Comment by dg0yt** [comment]
This feature was intentionally omitted when port zlib-ng was added. It is an "alternative", and there is little room for alternatives in the vcpkg repo. A little bit simplified, vcpkg users should be able to install any combination of ports and features at the same time.
- This feature is not additive (as required). It removes the zlib-ng native API. Even a single port requesting the feature would break consumers of regular zlib-ng API.
- The installed artifacts would conflict with port zlib.

**Review by BillyONeal — CHANGES_REQUESTED** [review]
I think we could accept big comments added in various files to show how to use overlay ports to get the effect you want, but as proposed this creates conflicts between zlib-ng and zlib, so I don't see a future where this can ever be on.

**Comment by netcorefan1** [comment]
@BillyONeal What you think about something like that:
```
if ("compat" IN_LIST FEATURES) && VCPKG_OVERLAY_PORTS.Contains(zlib_overlay_path)
   ... install ...
else
   Warning(compat feature requires a port overlay. Feature install aborted!)
```
In this way no conflicts should occurs and implementation will be left to the user in the way he likes more. Do you think could be feasible?

**Comment by BillyONeal** [comment]
>In this way no conflicts should occurs and implementation will be left to the user in the way he likes more. Do you think could be feasible?

I don't think that changes anything; the curated registry is trying to say "all this stuff works together", and this creates a situation that clearly does not.

**Comment by netcorefan1** [comment]
@BillyONeal Unless you didn't found a way on how to solve the issues, I think I should close this pull request. I have published a [tutorial](https://github.com/microsoft/vcpkg/discussions/31116) (that needs approval and fixes from experts like you) for people that still want to implement this locally.
Thanks

**Please note**: I saw your [bump version](https://github.com/microsoft/vcpkg/pull/30937/commits/afbfbbc4bc6f41db9dc84f6786137cf42b9a3a9b) commit. If it was a fix for the original port and not just for my specific pull request, then it needs to be merged.

**Comment by BillyONeal** [comment]
> @BillyONeal Unless you didn't found a way on how to solve the issues, I think I should close this pull request. I have published a [tutorial](https://github.com/microsoft/vcpkg/discussion,s/31116) (that needs approval and fixes from experts like you) for people that still want to implement this locally. Thanks

Okie dokie, sorry that we don't have a great way of expressing what you want right now :/

> **Please note**: I saw your [bump version](https://github.com/microsoft/vcpkg/pull/30937/commits/afbfbbc4bc6f41db9dc84f6786137cf42b9a3a9b) commit. If it was a fix for the original port and not just for my specific pull request, then it needs to be merged.

Yeah that was just to make the version database consistent with your other edits, not an independent change.

Here's hoping we can revisit this when we can better model alternatives someday. Sorry!

**Pull request closed without merging**
