### PR TITLE
[raylib] Disable Default Sanitizers on Debug Builds

### LINKED ISSUE #39996: [glfw] Undifined Reference to asan / ubsan
**Describe the bug**
Hello, I am trying to install and use raylib port, which depends on glfw. I have a simple CMake project. It seems like the GLFW port requires the adress sanitizer runtime. When adding `asan` and `ubsan` to my `target_link_library`,  my program compiles and runs but reports false (?) memory leaks from glfw3. My intention is to completely disable the address sanitizer runtime.

I tried manually building glfw3 from source and it doesn't happen.

**Environment**
- OS: EndevourOS KDE Plasma 
- Compiler: GCC 14.1.1

**To Reproduce**
1. Download the example project
2. Run vcpkg install
3. Build with CMake

**Expected behavior**

**Failure logs**
[cmake_error.txt](https://github.com/user-attachments/files/16321753/cmake_error.txt)

**Additional context**
[Sample.zip](https://github.com/user-attachments/files/16321754/Sample.zip)

### PR DESCRIPTION
**Pull request by AregevDev**
Fixes #39996
Follow up to #40100

Sanitizers should be defined in a toolchain file instead.
Tested on a custom toolchain file that enables `asan` and `ubsan` on Linux.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [ ] ~~SHA512s are updated for each updated download.~~
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version.~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by dg0yt** [comment]
Note #40209

**Comment by AregevDev** [comment]
OH, that's neat, do you need help with that PR?

**Review by dg0yt — APPROVED** [review]
You can mark this as ready for review. It is okay if it would be merged first.

**Review by FrankXie05 — APPROVED** [review]

**Review by data-queue — APPROVED** [review]

**Comment by AregevDev** [comment]
There's also #40209, it also disables the sanitizers and makes other adjustments to the port like devendoring the external header files. 

Maybe it should be merged instead...

**Comment by data-queue** [comment]
Good point, I'm going to merge the other PR instead to avoid merge conflicts since I've approved both PRs.

**Comment by AregevDev** [comment]
Closed in favor of the other PR.

**Pull request closed without merging**
