### PR TITLE
[vcpkg_build_qmake] Disable multi-threaded build when file fails to open

### PR DESCRIPTION
**Pull request by JackBoosY**
Continue PR #12529.

### CODE REVIEW

**Comment by JackBoosY** [comment]
@Neumann-A

**Comment by Neumann-A** [comment]
@JackBoosY: According to the logs this did not rerun the qt5 build in CI

**Comment by Neumann-A** [comment]
Probably just update the port-version of qt5-base. That will rebuilt everything qt5 related

**Comment by JackBoosY** [comment]
@Neumann-A That's unexpected.
@strega-nil The pipeline should detect the relevant ports and retest these ports.

**Comment by Neumann-A** [comment]
@JackBoosY: I think it is because the call is in a cmake file within qt5-base which gets installed and used. It is thus not transparent for vcpkg that the function gets called since qt5-base does not use it. Just increase the port-version of qt5-base for now.

**Comment by Neumann-A** [comment]
to be more precise `vcpkg_build_qmake.cmake` is not used by qt5-base do to the configure script calling directly qmake. `qt_build_submodule` uses `vcpkg_build_qmake.cmake` but since qt5-base is not dependent on neither `vcpkg_build_qmake.cmake` nor `qt_build_submodule` vcpkg does not have a chance detecting that dependency for the other qt5 ports

**Comment by ras0219** [comment]
Hrm, so we need to extend our dep heuristics to scan all files in the port directory instead of just the portfile.cmake.

**Pull request merged**
