### PR TITLE
[assimp] update to 5.2.1

### LINKED ISSUE #21361: [assimp] update to 5.1
Library name: assimp
https://github.com/assimp/assimp/releases/tag/v5.1.0

New version number: 5.1

Other information that may be useful (release notes, etc...)
fix qtquick3d assimp feature.

### LINKED ISSUE #22952: [assimp] update to 5.2.0
Library name: assimp

New version number: 5.2.0

It provides more comprehensive PBR material support now.

release note:
https://github.com/assimp/assimp/releases/tag/5.2.0
all commits:
https://github.com/assimp/assimp/compare/v5.0.1...5.2.0

### PR DESCRIPTION
**Pull request by JonLiu1993**
Fix #22952 

Update assimp to the latest version 5.2.1

Note: no feature need to test

### CODE REVIEW

**Comment by Neumann-A** [comment]
Please check if 

 `qtquick3d[assimp]` can be build with that version of assimp.

**Comment by Osyotr** [comment]
Please remove `irrlicht` dependency #21605

**Comment by Neumann-A** [comment]
closes #21361

**Comment by itimirichard** [comment]
Hello, great job on doing this - My team is very interested in this update and as we use assimp in some of our projects and would like to use some of the updates from 5.2. Can you share when this is likely to be completed or if there are blockers that might delay this further? Would greatly appreciate your feedback. Thanks

**Comment by Osyotr** [comment]
@itimirichard the main issues with updating assimp is that it uses patched vendored version of rapidjson and also requires many patches to it's buildsystem. If you want this port ASAP you might want to create overlay port and use vendored dependencies, until main port is updated.

**Comment by JonLiu1993** [comment]
Temporarily close this pr, I will reopen it later after I resolve the error locally

**Comment by JonLiu1993** [comment]
Duplicate of #24843

**Pull request closed without merging**
