### PR TITLE
[vcpkg] Add mingw dynamic libs triplet

### PR DESCRIPTION
**Pull request by longnguyen2004**
**Describe the pull request**

- What does your PR fix? Fixes #
This PR adds 4 triplets for building dynamic libs with `mingw` toolchain, and rename the old static libs triplets to `*-static`, following the `*-windows` triplets convention
~Currently, building with this triplet will fail, due to the post-build validation only checking for `.lib` files, not `.dll.a` files, but the building process seems to be ok, at least for CMake-based libs. So we only have that left to fix.~ Added `VCPKG_POLICY_DLLS_WITHOUT_LIBS` as a workaround.

- Which triplets are supported/not supported? Have you updated the CI baseline?
Should be all `*-mingw` triplets, but I've only tested `x64-mingw`

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

### CODE REVIEW

**Review by LilyWangL — APPROVED** [review]

**Comment by vicroms** [comment]
The only concern I have is that this PR changes the behavior of already existing triplets for MinGW, and will break users that have already adopted those triplets.

**Comment by vicroms** [comment]
I think a good compromise is to rename both triplets: `<arch>-mingw-static` and `<arch>-mingw-dynamic`.

**Comment by longnguyen2004** [comment]
So `*-mingw` would be the same as `*-mingw-static`, got it

**Comment by vicroms** [comment]
I say we remove `<arch>-mingw`, and force users to use the explicit `<arch>mingw-static` and `<arch>mingw-dynamic` triplets. That way existing users will get an error for deprecated behavior instead of changing the library linkage without them noticing.

**Comment by ras0219-msft** [comment]
Thanks for the PR!

**Pull request merged**
