### PR TITLE
[VTK/GLEW] Fix Regression of VTK with newer CMake Versions

### PR DESCRIPTION
**Pull request by Neumann-A**
Newer CMake Versions have a new Version of FindGLEW which loads just the config and forgets to define the common GLEW variables. The wrapper now takes care to add those variables back in. Should probably be fixed in either the GLEW configs or in CMakes FindGLEW since it promises to define those variables.

### CODE REVIEW

**Comment by Neumann-A** [comment]
closes #7519
related regression see #7801

**Comment by jasjuang** [comment]
It should be a good idea to submit this patch to upstream cmake FindGLEW as well.

**Comment by Neumann-A** [comment]
Reported to CMake as https://gitlab.kitware.com/cmake/cmake/issues/19662

**Comment by PhoebeHui** [comment]
It failed with 'Download Build Artifacts' steps in linux testing, it's a temp issue, requene it.

**Comment by PhoebeHui** [comment]
@grdowns, could you priority this PR to review and merge this PR? it blocked many people.

**Comment by grdowns** [comment]
Apologies for the wait! LGTM -- thanks everyone for the patience

**Pull request merged**
