### PR TITLE
[embree] Update embree to 3.2.0

### PR DESCRIPTION
**Pull request by doomtr666**
Update embree to 3.2.0

### CODE REVIEW

**Comment by doomtr666** [comment]
Nice.

**Comment by doomtr666** [comment]
Please note that version 3 is not compatible with version 2. Ideally we could enable ISPC support as well, bu no idea how to do that with vcpkg.

**Comment by past-due** [comment]
@doomtr666, @ras0219-msft: Since embree3 breaks API compatibility with embree2 (and [requires dependent source changes](https://embree.github.io/api.html#upgrading-from-embree-2-to-embree-3)), wouldn't it be better to make this a new port (`embree3`)? Or at least keep embree v2 around as `embree2`?

**Comment by doomtr666** [comment]
Embree API is not very complicated, in addition a migration script is
provided. No other vcpkg seems to depend on Embree. V3 is cleaner, faster
and enables lots of SIMDization opportunities, so my PR.
Anyway is you wish to keep v2 too, not an issue for me !

**Comment by ras0219-msft** [comment]
Thanks for the PR!

Because it seems that embree2 is still in support (upstream is continuing to release patches), it makes sense to keep it around.

**Comment by doomtr666** [comment]
Great !

**Comment by doomtr666** [comment]
Oh, I got  this error installing the new embree3 port:
-- Performing post-build validation
The software license must be available at ${CURRENT_PACKAGES_DIR}/share/embree3/copyright

    file(COPY ${CURRENT_BUILDTREES_DIR}/src/v3.2.0-0cfe213eda/LICENSE.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/embree3)
    file(RENAME ${CURRENT_PACKAGES_DIR}/share/embree3/LICENSE.txt ${CURRENT_PACKAGES_DIR}/share/embree3/copyright)
Found 1 error(s). Please correct the portfile:
    I:\Sources\insanity2\Externals\vcpkg\ports\embree3\portfile.cmake
-- Performing post-build validation done
Error: Building package embree3:x64-windows failed with: POST_BUILD_CHECKS_FAILED

**Pull request merged**
