### PR TITLE
[test] Test fields in CONTROL file(Do not merge)

### PR DESCRIPTION
**Pull request by NancyLi1013**
Just test if CI can recognize the fields key work in CONTROL file.

### CODE REVIEW

**Comment by NancyLi1013** [comment]
@BillyONeal and @strega-nil 
Could you please help confirm if this is vcpkg bug that CI detects incorrectly?

If the key word of fields in `CONTROL `file are not spelling correctly, such as we use `Support ` or `support `instead of `Supports`, our CI build will post the error like this:

```
Warning: an error occurred while parsing 'libgo'
Use '--debug' to get more information about the parse failures.
```
In this case, the port will not built again. But this seems to be not detected by our CI results.
Although all triplets are not built, CI still shows "`All checks have passed`".

**Comment by strega-nil** [comment]
Oh, shoot, thanks @NancyLi1013. I'll check it out.

**Comment by BillyONeal** [comment]
Do I understand correctly that this is a bug report that we aren't correctly hashing the actual CONTROL file or something like that into the package hash?

**Comment by BillyONeal** [comment]
This report appears related to how binary caching works, so reassigning to Robert.

**Comment by BillyONeal** [comment]
This was a test and it's old, closing.

**Pull request closed without merging**
