### PR TITLE
[osg] Add GL3 feature to OSG

### PR DESCRIPTION
**Pull request by jasonbeverage**
This PR allows you to build OSG in either gl3 mode instead of the default gl2 mode using feature flags.  So you can install osg[gl3] and it will set the OPENGL_PROFILE cmake setting correctly during the build.

- #### What does your PR fix?
Some applications that use OSG require the use of modern OpenGL and need OSG to be built in gl3 modes to function properly.  The main purpose of this to allow osg to create an OpenGL core context which lets it be used in tools like NVIDIA Nsight or in VMWare.  We are preparing a new osgEarth 3.3 release and it needs to be built against an OSG with GL3 support.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
Same as previously supported.  I tested locally on x64-windows.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by Osyotr** [comment]
I think this should be a triplet variable, like here:
https://github.com/microsoft/vcpkg/pull/22409

**Comment by JonLiu1993** [comment]
All features are tested successfully in the following triplt:
- x86-windows
- x64-windows
- x64-windows-static

**Review by JonLiu1993 — APPROVED** [review]

**Comment by Osyotr** [comment]
@JonLiu1993 you're about to violate "don't add options as features" rule...

**Comment by jasonbeverage** [comment]
If you need me to try to work on this as an option or look at another way to do this I'm happy to.   I was only familiar with features so that's why I went down that route

**Comment by jasonbeverage** [comment]
Actually after thinking about this a bit more, I think the feature route is probably a sensible way to go.  All this really does is change whether osg thinks it supports opengl3 and provides the ability to create an opengl core context, which should be supported everywhere now since it's 2022 and fixed function rendering hasn't really been supported since OpenGL 3.0.  It doesn't add any additional dependencies or anything like that.  This is also fairly low risk I'd say since only osgQT and osgEarth (which we are the maintainers of) actually depend on osg in vcpkg, so it shouldn't effect anyone unless they opt in to gl3 and won't effect anyone currently using the fixed function pipeline.

I'd love to get this merged as is, having to build osg from source to get proper gl3 support is actually a huge hassle for lots of our customers when we'd prefer them to just use vcpkg instead as we recommend it for all of their other dependencies.

**Comment by jasonbeverage** [comment]
OpenGL ES is really only used on mobile, so in theory shouldn't effect the windows or linux builds.

I do like the idea of just defaulting osg to building with the GL3 profile, that would be ideal at least for us.

I'm not sure how custom triplet variables work, but with your suggested change could someone just add:
set(osg_OPENGL_PROFILE GL2)
to their custom triplet and then it would get passed through to the port files cmake?
If so I think that is a cool solution.

I also had a previous PR that added support for building OSG against the GLCORE headers, which is really no different than building with GL3 mode except for it uses the glcorearb.h header instead of the old windows <GL/gl.h> header.  I don't know really any reason to do this, but I do know some people do build osg this way.  With the custom triplet option maybe we could just make "opengl-registry" a full time dependency of osg in case someone wants to build in GLCORE mode, it's just going to pull down some extra headers that might not be needed if they don't build with glcore in their triplet but it would be there ready to go if they did change it.

**Comment by Osyotr** [comment]
> OpenGL ES is really only used on mobile, so in theory shouldn't effect the windows or linux builds.

There are also triplets for Android and iOS (so a check is probably needed to determine appropriate default value, e.g. GL3 for x64/x86-windows/linux/osx, GL2/GLES3 for everything else)

> but with your suggested change could someone just add ... to their custom triplet and then it would get passed through to the port files cmake?

Yes

**Comment by jasonbeverage** [comment]
I'm testing a triplet based port file now and I think it's going to work out great.  Let me finish testing it and I'll try to prepare another PR.

**Comment by jasonbeverage** [comment]
I've opened a new PR at https://github.com/microsoft/vcpkg/pull/24108 that implements this as a triplet variable, thanks for the suggestion!

**Pull request closed without merging**
