### PR TITLE
[cjson] update version to 1.7.18

### PR DESCRIPTION
**Pull request by KangLin**

### CODE REVIEW

**Comment by Cheney-W** [comment]
Please run below commands after you submitted the change commit:
```
.\vcpkg x-add-version cjson
git add .
git commit --amend --no-edit
```

**Comment by Cheney-W** [comment]
Please delete the commnet in the patch to minimize the patch content.
The test function of this port is disabled in vcpkg, so there is no need to patch the test related code. You can report this issue to the upstream.

**Comment by Cheney-W** [comment]
Could you please remove the line 1-36 from 0001-Fix-compile-fail-with-android-ndk-27.patch file?

**Review by Cheney-W — DISMISSED** [review]

**Comment by dg0yt** [comment]
Please remove the patch. It is enough to add `-DCMAKE_POLICY_DEFAULT_CMP0057=NEW` to `OPTIONS`.

**Comment by Cheney-W** [comment]
@KangLin Could you please apply dg0yt's suggestion?

**Review by Cheney-W — APPROVED** [review]

**Pull request merged**
