### PR TITLE
[dstorage] Update port for 1.1.0 release

### PR DESCRIPTION
**Pull request by walbourn**
Updates port for the latest 1.1.0 release of DirectStorage

https://devblogs.microsoft.com/directx/directstorage-1-1-now-available/

### CODE REVIEW

**Comment by walbourn** [comment]
Verified the supported triplets locally:

```
vcpkg install dstorage:x86-windows
vcpkg install dstorage:x86-windows-static-md
vcpkg install dstorage:x64-windows
vcpkg install dstorage:x64-windows-static-md
vcpkg install dstorage:arm-windows
vcpkg install dstorage:arm64-windows
vcpkg install dstorage:arm64-windows-static-md
```

**Comment by MonicaLiu0311** [comment]
The `license` in `vcpkg.json` should be `MIT`.

**Comment by walbourn** [comment]
> Thanks for your PR. The `license` in `vcpkg.json` should be `MIT`.

No. The repository reference is for the samples which are under MIT. The contents of the NuGet itself installed by this port are subject to a custom license.

**Review by MonicaLiu0311 — APPROVED** [review]

**Comment by JavierMatosD** [comment]
Thank you!

**Pull request merged**
