### PR TITLE
[simdjson] Add new port (fix #5418)

### LINKED ISSUE #5418: [New port request] simdjson
https://github.com/lemire/simdjson

### PR DESCRIPTION
**Pull request by myd7349**
Tested with:

* x64-windows
* x64-windows-static
* x64-linux

Test project: https://github.com/myd7349/Ongoing-Study/tree/master/cpp/CMake/vcpkg/simdjson/print_json

### CODE REVIEW

**Comment by PhoebeHui** [comment]
@myd7349, thanks for contributing to vcpkg!

Here is failed test results:
```
x64-uwp                 fail
arm-uwp                 fail
x86-windows             fail
arm64-windows           fail
x64-windows             pass
x64-windows-static      pass
x64-linux               pass
x64-osx                 pass
```

**Comment by myd7349** [comment]
@PhoebeHui Thanks for the reply!

It seems that `simdjson` only supports `x64` architecture currently. I will comfirm this with the author.

**Comment by myd7349** [comment]
@PhoebeHui Hi! @lemire has replied me: https://github.com/Microsoft/vcpkg/issues/5418#issuecomment-470519894

I will try to find out what happens to `UWP`.

**Comment by myd7349** [comment]
I have figured out why `x64-uwp` failed. And I have created a PR for fix this problem in the upstream: https://github.com/lemire/simdjson/pull/113

**Comment by myd7349** [comment]
I think `x64-uwp` should work now.

**Comment by grdowns** [comment]
Looks good. Thanks for the PR, @myd7349!

**Pull request merged**
