### PR TITLE
[bullet3] Initial addition

### PR DESCRIPTION
**Pull request by adam4813**
This port adds bullet3 in single precision build mode.

I was uncertain if it would be prefered to build in shared library or static library form, so I went with the default of static library.

### CODE REVIEW

**Comment by ras0219-msft** [comment]
We currently only support DLLs, but we're working on static library support! See #97.

**Comment by adam4813** [comment]
I will make the change to have it build shared libraries.

Though of note it works as it is right now when adding it to a project.

**Comment by adam4813** [comment]
@ras0219-msft Should we prefer linking against static or dynamic Visual C++ Runtime libraries?

**Comment by adam4813** [comment]
Also generating shared libraries on windows is apparently a no-go without a lot of work due to it not exporting any symbols (see [here](http://stackoverflow.com/questions/28840628/building-bullet-physics-as-shared-libraries))

**Comment by alexkaratarakis** [comment]
This CMake option might help:
https://cmake.org/cmake/help/v3.6/variable/CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS.html

And example:
https://bitbucket.org/vlasovmaksim/cmake_windows_export_all_symbols/overview#branches

**Comment by adam4813** [comment]
Ok that worked for the most part, but there is now 2 linker errors for which I've submitted a PR to bulletphysics [here](https://github.com/bulletphysics/bullet3/pull/820) . When that is resolved we should be good to go on this.

**Comment by adam4813** [comment]
@ras0219-msft This should be good now, unless using a specific commit like I did is a no go.

**Comment by ras0219-msft** [comment]
Using an exact commit is the perfect thing to do, good job 👍. I'm going to switch the repo back to bulletphysics to make it more easily trusted at a glance.

**Comment by adam4813** [comment]
Ah good catch thanks.

**Pull request merged**
