### PR TITLE
Revert "[irrlicht] use unicode path on windows (#7354)"

### PR DESCRIPTION
**Pull request by adrido**
This reverts commit 22be764ecc302d93371b8f7a05faf0fc4e39fa31.

Patches that change the sourcecode that way should be done properly directly in Irrlicht.

There is probably a reason why the unicode filesystem is disabled by default. That patch causes trouble. See: https://github.com/microsoft/vcpkg/issues/7640

### CODE REVIEW

**Comment by cbezault** [comment]
I'm inclined to agree with the sentiment of this PR.
@DailyShana can you explain the intent of #7354? Otherwise I'm going to merge this change.

**Comment by cbezault** [comment]
Or @adrido could you specifically point out what is wrong with enabling unicode by default (besides, the fact that we're modifying library behavior).

**Comment by cbezault** [comment]
You know what, I agree, we're not in the business of modifying the behavior of libraries. Patches should only be used to get unruly libraries to build/link.

**Comment by adrido** [comment]
Thanks for merging. 
The problem is, that a program using this library could not longer open files. Even if its path only contains ANSI characters. A workaround would be to define UNICODE for the program as well, but this would make it incompatible to the non-vcpkg version of the library.

@DailyShana IMO you could implement it as a [feature](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/control-files.md#feature-paragraphs), to make it possible to install it e.g. irrlicht[unicode]. If im reading it correct, it is sufficient to define UNICODE and _IRR_WCHAR_FILESYSTEM inside cmake. Patching the library is not necessary.

**Pull request merged**
