### PR TITLE
[geotrans] add new port

### PR DESCRIPTION
**Pull request by tzneal**

### CODE REVIEW

**Comment by tzneal** [comment]
I can't see the details on the failed check, not authorized.  I only tested on Linux x64 on my end.

**Comment by grdowns** [comment]
> I can't see the details on the failed check, not authorized. I only tested on Linux x64 on my end.

The CI build is failing because the the CI build only passes for x64-linux. I can see that `geotrans` is also available for Windows -- would you be able to get this port to work for the Windows triplets?

**Comment by tzneal** [comment]
> The CI build is failing because the the CI build only passes for x64-linux. I can see that `geotrans` is also available for Windows -- would you be able to get this port to work for the Windows triplets?

I'll have a look. I thought that the code in the downloads was identical, only the Linux package is src+shared objects, while the Windows package is src+DLL's.

**Comment by Voskrese** [comment]
two port ?
it is necessary to isolate the Assembly on the platform


Windows Developer | 149 MB | win_dev.zip
http://earth-info.nga.mil/GandG/geotrans/geotrans3.7/win_dev.zip
Linux Developer | 144 MB | linux_dev.tgz

> and personally I have problems with access to site
> without a proxy from another country could not go
>

**Comment by tzneal** [comment]
@grdowns Can you let give me access to the failure screen, or let me know why it failed?  I tested on Windows x86, x64 and Linux x64.

**Comment by tzneal** [comment]
> two port ?
> it is necessary to isolate the Assembly on the platform
> 
> Windows Developer | 149 MB | win_dev.zip
> http://earth-info.nga.mil/GandG/geotrans/geotrans3.7/win_dev.zip
> Linux Developer | 144 MB | linux_dev.tgz

The code is the same in both, one has Linux binaries, the other has Windows.

**Comment by Rastaban** [comment]
Thank you for adding this library, it is looking good so far.  Could you add a comment near the URL just pointing out that despite having Linux in the file name the source code is the same for all architectures?  Tests are passing on all architectures except for the uwp triplets on windows.

**Comment by Rastaban** [comment]
[install-x64-uwp-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2922830/install-x64-uwp-dbg-out.log)

Here is the log file for x64-uwp.  Doing a quick scan it looks like the failures can probably all be fixed with _CRT_SECURE_NO_WARNINGS.

**Comment by vicroms** [comment]
Thanks for contributing, `geotrans` builds for all triplets in our CI system 👍

**Pull request merged**
