### PR TITLE
[ffmpeg] Link libvpx automatically with cmake if vpx feature is enabled

### PR DESCRIPTION
**Pull request by mcmtroffaes**
- What does your PR fix?

Currently, to use ffmpeg[vpx], cmake needs:

```cmake
find_package(ffmpeg REQUIRED)
find_library(VPX_LIBRARY NAMES vpxmd)  # or vpxmt. vpxmdd, ... depending on the configuration
find_path(VPX_INCLUDE_DIR NAMES vpx/vpx_codec.h)
add_executable(main main.cpp)
target_link_libraries(main PRIVATE ${FFMPEG_LIBRARIES})
target_include_directories(main PRIVATE ${FFMPEG_INCLUDE_DIRS})
target_link_libraries(main PRIVATE ${VPX_LIBRARY})
target_include_directories(main PRIVATE ${VPX_INCLUDE_DIR})
```

With this patch, the extra step of linking to libvpx is done automatically (similar to lzma and bzip2):

```cmake
find_package(ffmpeg REQUIRED)
add_executable(main main.cpp)
target_link_libraries(main PRIVATE ${FFMPEG_LIBRARIES})
target_include_directories(main PRIVATE ${FFMPEG_INCLUDE_DIRS})
```

- Which triplets are supported/not supported? Have you updated the CI baseline? No change in supported triplets.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)? To the best of my knowledge, yes.

### CODE REVIEW

**Review by NancyLi1013 — APPROVED** [review]

**Comment by Sibras** [comment]
This has already been fixed in #11277

**Comment by mcmtroffaes** [comment]
Oh, that's rather nice! This patch directly uses the cmake "unofficial-libvpx" config (I think that may have been added after you wrote your patch), which is a bit simpler.

**Comment by Sibras** [comment]
> 
> 
> Oh, that's rather nice! This patch directly uses the cmake "unofficial-libvpx" config (I think that may have been added after you wrote your patch), which is a bit simpler.

Ive updated #11277 to use your approach.

**Comment by mcmtroffaes** [comment]
Great! Closing this in favour of #11277.

**Pull request closed without merging**
