### PR TITLE
[z3] update port to 4.8.8

### PR DESCRIPTION
**Pull request by illera88**
Update port to new z3 version 4.8.8

### CODE REVIEW

**Comment by illera88** [comment]
Hi @JackBoosY,

Can you give me a hand with the CI errors?

Thanks

**Comment by JackBoosY** [comment]
```
DLLs should not be present in a static build, but the following DLLs were found:

    C:/agent/_work/1/s/packages/z3_x64-windows-static/bin/libz3.dll
    C:/agent/_work/1/s/packages/z3_x64-windows-static/debug/bin/libz3.dll

There should be no bin\ directory in a static build, but C:\agent\_work\1\s\packages\z3_x64-windows-static\bin is present.
There should be no debug\bin\ directory in a static build, but C:\agent\_work\1\s\packages\z3_x64-windows-static\debug\bin is present.
If the creation of bin\ and/or debug\bin\ cannot be disabled, use this in the portfile to remove them

    if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")
        file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/bin" "${CURRENT_PACKAGES_DIR}/debug/bin")
    endif()
```

**Comment by illera88** [comment]
That's weird. I basically just took the previous port and updated with the new code as you can see.

I see that the portfile has this code:

```
if (VCPKG_LIBRARY_LINKAGE STREQUAL "static")
  set(BUILD_STATIC "-DBUILD_LIBZ3_SHARED=OFF")
endif()
```

which should prevent the shared libraries from being build AFAIK

**Comment by illera88** [comment]
Nevermind, it seems they change the name of that flag from `BUILD_LIBZ3_SHARED` to `Z3_BUILD_LIBZ3_SHARED`.

New commit should fix this

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
LGTM, thanks for this PR!

**Comment by strega-nil** [comment]
Cool, thanks @illera88 :)

**Pull request merged**
