### PR TITLE
Angle updated to master, UWP fix for Angle

### PR DESCRIPTION
**Pull request by rollebolle**
- Updated to Angle master as of 2018-11-27
- Fixed so it builds with Windows Store

### CODE REVIEW

**Comment by past-due** [comment]
@rollebolle: Was there a particular reason why you closed this PR? Would love to see something like this integrated.

**Comment by rollebolle** [comment]
@past-due I realized I had to wait for legal at my company to approve the contribution, then I forgot about it. I can re-open it now

**Comment by Rastaban** [comment]
Thank you for reopening, this will be good to have.  I noticed in the CI system that the patch failed to apply so UWP still failed.  This is probably because the Angle version has changed since your original PR.  Could you take a look at that?

**Comment by rollebolle** [comment]
Thanks, I have a fix for that ready, will upload today

**Comment by rollebolle** [comment]
@Rastaban how can I see the status in the CI system? It compiles locally now

**Comment by Rastaban** [comment]
I see it built in the CI system.  Currently the logs from the CI system is behind a wall although we are making steps to get them publicly accessible.

**Pull request merged**
