### PR TITLE
CI with android NDK r27c

### PR DESCRIPTION
**Pull request by dg0yt**
New LTS Version

- offering support for new arm64 page size
  https://android.googlesource.com/platform/ndk/+/master/docs/BuildSystemMaintainers.md#Page-sizes
  https://github.com/microsoft/vcpkg/pull/40339#issuecomment-2274068367

**Problems:**

See also https://github.com/orgs/android/projects/19

- [x] Fixed in r27b: breaking compatibility with CMake projects which don't ask for CMake 3.3 or set CMP0057 to NEW  
  https://github.com/android/ndk/issues/2032
- [x] Fixed in r27c: gdal:arm-neon-android: clang++ crash
  - Even worse with https://github.com/android/ndk/issues/2070, planned for r27c/r28.
- [x] Fixed in r27b: ncnn:x64-android: clang++ crash, https://github.com/android/ndk/issues/2054
- [x] Added fail to baseline: several ports: `'ALooper_pollAll' is unavailable: obsoleted in Android 1 - ALooper_pollAll may ignore wakes. Use ALooper_pollOnce instead.`
- [x] Added fail to baseline: some ports with compiler flags issues (minor probably)
- [x] #41142

### CODE REVIEW

**Comment by Neumann-A** [comment]
> breaking compatibility with CMake projects which don't ask for CMake 3.5.

Why? Just set the required policy in the toolchain?

**Comment by dg0yt** [comment]
> Just set the required policy in the toolchain?

My plan is to do that, in scripts/toolchain

**Comment by bwrsandman** [comment]
> CMake projects which don't ask for CMake 3.5.

Looked into the versions. It looks like 3.3 (not 3.5) is the minimum necessary

**Comment by dg0yt** [comment]
https://github.com/android/ndk/wiki/Changelog-r27:

> Android V will allow OEMs to ship arm64-v8a devices with 16KiB page sizes. Devices that use this configuration will not be able to run existing apps that use native code. To be compatible with these devices, applications will need to rebuild all their native code to be 16KiB aligned, and rewrite any code which assumes a specific page size. 

Q: Shall 16KiB be the default for NDK r27 arm64-android?

**Comment by Neumann-A** [comment]
> > Why?

> Sounds aggressive. Ask Google.

Reads like: Words, has no sound.... ¯\\_(ツ)_/¯ Don't mind me asking stupid questions. 
But you already expressed my opinion upstream before I even had one :) .  

Q: Shall there be a special arm64-v8a triplet?

**Comment by dg0yt** [comment]
Initial success:

|        | Success | Fail | Cascade |
|--------|--------|--------|--------|
| arm-neon-android | 1120 | 252 | 230 |
| arm64-android    | 1139 | 255 | 257 |
| x64-android      | 1135 | 263 | 278 |

**Comment by dg0yt** [comment]
I have difficulties to get CMP0057 from the toolchain scope (`android.cmake`, called via `CMakeDetermineSystem.cmake`) to the failing scope (`flags.cmake`, called via `CMakeSystem.cmake`). Even when I put it directly into `vcpkg.cmake`.

Testing the proposed fix to the NDK instead.

**Comment by dg0yt** [comment]
This works:
~~~diff
diff --git a/scripts/toolchains/android.cmake b/scripts/toolchains/android.cmake
index d675d06a73..4564f29e7e 100644
--- a/scripts/toolchains/android.cmake
+++ b/scripts/toolchains/android.cmake
@@ -31,6 +31,11 @@ endif()
 
 include("${ANDROID_NDK_HOME}/build/cmake/android.toolchain.cmake")
 
+if(ANDROID_NDK_MAJOR STREQUAL "27")
+    # https://github.com/android/ndk/issues/2032#issuecomment-2274923977
+    string(APPEND CMAKE_SYSTEM_CUSTOM_CODE "cmake_policy(SET CMP0057 NEW)\n")
+endif()
+
 if(NOT _VCPKG_ANDROID_TOOLCHAIN)
     set(_VCPKG_ANDROID_TOOLCHAIN 1)
 
~~~
But it might be a somewhat tight binding to both CMake and NDK script code.

**Comment by dg0yt** [comment]
Success with patch to NDK's `flags.cmake`:

|        | Success | Fail | Cascade |
|--------|--------|--------|--------|
| arm-neon-android | n/a* |   6 |  20 |
| arm64-android    | n/a* | x (due to `IN_LIST`: y | z |
| x64-android      | n/a* |   9 |  77 |

*) successfuild builds from the first run were cached and not tested again

**Comment by dg0yt** [comment]
Initial success with r27b:

|        | Success | Fail | Cascade |
|--------|--------|--------|--------|
| arm-neon-android | 1615 |  7 |  3 |
| arm64-android    | 1658 |  9 |  7 |
| x64-android      | 1633 |  9 | 59 |

*) successfuild builds from the first run were cached and not tested again

**Comment by dg0yt** [comment]
Initial success with r27c:

|        | Success | Fail | Cascade |
|--------|--------|--------|--------|
| arm-neon-android | 1629 |  5 |  2 |
| arm64-android    | 1673 |  7 |  6 |
| x64-android      | 1646 |  7 | 61 |

x64-android errors:  
 - cppcoro: `clang++: error: unknown argument: '-fcoroutines-ts'`
 - fbbgemmerror: `variable length arrays in C++ are a Clang extension [-Werror,-Wvla-cxx-extension]`
 - freeglut: `error: 'ALooper_pollAll' is unavailable: obsoleted in Android 1`
 - libgnutls: `error: call to undeclared function 'mktime_z'` etc.
 - raylib: `error: 'ALooper_pollAll' is unavailable: obsoleted in Android 1`
 - vulkan-tools: `error: 'ALooper_pollAll' is unavailable: obsoleted in Android 1`
 - yajl: ` at reformatter/CMakeLists.txt:38 (GET_TARGET_PROPERTY):
  The LOCATION property may not be read from target "json_reformat".`

**Comment by dg0yt** [comment]
Okay, waiting for https://github.com/microsoft/vcpkg/pull/41647 arriving as an image.

**Review by BillyONeal — DISMISSED** [review]

**Review by MonicaLiu0311 — DISMISSED** [review]

**Comment by MonicaLiu0311** [comment]
There is one more conflicting item.

**Comment by dg0yt** [comment]
Resolved.

**Review by MonicaLiu0311 — APPROVED** [review]

**Review by data-queue — APPROVED** [review]

**Pull request merged**
