### PR TITLE
[tesseract] port update to 4.1.0 release

### PR DESCRIPTION
**Pull request by zhbanito**
Add Tesseract 4.1.0 release.

Removed patches, that already implemented in tesseract souce.
Added Features in CONTROL:
**training_tools** for build with training executables
**cpu_independed** for build library that working on any cpu (disable processor command extensions at the cost of reduced performance)
Handle Features in port script and added some options for building tesseract out-of-box (tiff link problem in tesseract executable, PkgConfig leptonica link problem on linux).

Succefully builded on x64-windows(+-static), x86-windows(+-static), x64-linux(+-static), x86-linux(+-static), all debug and release configurations.
Linux builds doing by WSL with Ubuntu 18.04.2 LTS

### CODE REVIEW

**Comment by JackBoosY** [comment]
Please use this patch to fix tiff link issues:
[fix-tiff-linkage.zip](https://github.com/microsoft/vcpkg/files/3391731/fix-tiff-linkage.zip)

Thanks.

**Comment by zhbanito** [comment]
> Please use this patch to fix tiff link issues:
> [fix-tiff-linkage.zip](https://github.com/microsoft/vcpkg/files/3391731/fix-tiff-linkage.zip)
> 
> Thanks.
Done

**Comment by PhoebeHui** [comment]
Related to PR https://github.com/microsoft/vcpkg/pull/7217.

**Comment by niksedk** [comment]
@zhbanito: Could you possibly make an update for 4.1.1 too?

**Comment by zhbanito** [comment]
@niksedk https://github.com/microsoft/vcpkg/pull/9629

**Pull request merged**
