### PR TITLE
[fizz/wangle] Fix cmake build failure with wangle:x64-linux

### LINKED ISSUE #20586: [wangle:x64-linux] build failure
**CMake build failed with wangle, vcpkg.**
```
-- Found Boost: /root/projects/vcpkg/installed/x64-linux/include (found suitable version "1.77.0", minimum required is "1.51.0") found components: context filesystem program_options regex system thread chrono date_time atomic 
-- Found folly: /root/projects/vcpkg/installed/x64-linux
CMake Error at /root/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:786 (_find_package):
  By not providing "FindSodium.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Sodium", but
  CMake did not find one.

  Could not find a package configuration file provided by "Sodium" with any
  of the following names:

    SodiumConfig.cmake
    sodium-config.cmake

  Add the installation prefix of "Sodium" to CMAKE_PREFIX_PATH or set
  "Sodium_DIR" to a directory containing one of the above files.  If "Sodium"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /root/projects/vcpkg/installed/x64-linux/share/fizz/fizz-config.cmake:53 (find_dependency)
  /root/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:786 (_find_package)
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /root/projects/vcpkg/installed/x64-linux/share/wangle/wangle-config.cmake:43 (find_dependency)
  /root/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:786 (_find_package)
  src/wangle_server/CMakeLists.txt:1 (find_package)


-- Configuring incomplete, errors occurred!
```

**Environment**
- OS: Linux
- Compiler: The C compiler identification is GNU 7.5.0, The CXX compiler identification is GNU 7.5.0

**To Reproduce**
1. ./vcpkg install wangle:x64-linux
2. Use wangle in my CMakeLists.txt

**Failure logs** 
```
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Warning (dev) at /root/projects/vcpkg/installed/x64-linux/share/zlib/vcpkg-cmake-wrapper.cmake:13 (_find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  CMake variable ZLIB_ROOT is set to:

    /root/projects/vcpkg/installed/x64-linux

  For compatibility, CMake is ignoring the variable.
Call Stack (most recent call first):
  /root/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:740 (include)
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /root/projects/vcpkg/installed/x64-linux/share/folly/folly-config.cmake:5 (find_dependency)
  /root/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:786 (_find_package)
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /root/projects/vcpkg/installed/x64-linux/share/wangle/wangle-config.cmake:42 (find_dependency)
  /root/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:786 (_find_package)
  src/wangle_server/CMakeLists.txt:1 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found ZLIB: optimized;/root/projects/vcpkg/installed/x64-linux/lib/libz.a;debug;/root/projects/vcpkg/installed/x64-linux/debug/lib/libz.a (found version "1.2.11") 
CMake Warning at /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/FindBoost.cmake:1354 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/FindBoost.cmake:1477 (_Boost_COMPONENT_DEPENDENCIES)
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/FindBoost.cmake:2087 (_Boost_MISSING_DEPENDENCIES)
  /root/projects/vcpkg/installed/x64-linux/share/boost/vcpkg-cmake-wrapper.cmake:11 (_find_package)
  /root/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:740 (include)
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /root/projects/vcpkg/installed/x64-linux/share/folly/folly-config.cmake:63 (find_dependency)
  /root/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:786 (_find_package)
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /root/projects/vcpkg/installed/x64-linux/share/wangle/wangle-config.cmake:42 (find_dependency)
  /root/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:786 (_find_package)
  src/wangle_server/CMakeLists.txt:1 (find_package)


CMake Warning at /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/FindBoost.cmake:1354 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/FindBoost.cmake:1477 (_Boost_COMPONENT_DEPENDENCIES)
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/FindBoost.cmake:2087 (_Boost_MISSING_DEPENDENCIES)
  /root/projects/vcpkg/installed/x64-linux/share/boost/vcpkg-cmake-wrapper.cmake:11 (_find_package)
  /root/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:740 (include)
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /root/projects/vcpkg/installed/x64-linux/share/folly/folly-config.cmake:63 (find_dependency)
  /root/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:786 (_find_package)
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /root/projects/vcpkg/installed/x64-linux/share/wangle/wangle-config.cmake:42 (find_dependency)
  /root/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:786 (_find_package)
  src/wangle_server/CMakeLists.txt:1 (find_package)


CMake Warning at /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/FindBoost.cmake:1354 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/FindBoost.cmake:1477 (_Boost_COMPONENT_DEPENDENCIES)
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/FindBoost.cmake:2087 (_Boost_MISSING_DEPENDENCIES)
  /root/projects/vcpkg/installed/x64-linux/share/boost/vcpkg-cmake-wrapper.cmake:11 (_find_package)
  /root/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:740 (include)
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /root/projects/vcpkg/installed/x64-linux/share/folly/folly-config.cmake:63 (find_dependency)
  /root/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:786 (_find_package)
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /root/projects/vcpkg/installed/x64-linux/share/wangle/wangle-config.cmake:42 (find_dependency)
  /root/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:786 (_find_package)
  src/wangle_server/CMakeLists.txt:1 (find_package)


CMake Warning at /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/FindBoost.cmake:1354 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/FindBoost.cmake:1477 (_Boost_COMPONENT_DEPENDENCIES)
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/FindBoost.cmake:2087 (_Boost_MISSING_DEPENDENCIES)
  /root/projects/vcpkg/installed/x64-linux/share/boost/vcpkg-cmake-wrapper.cmake:11 (_find_package)
  /root/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:740 (include)
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /root/projects/vcpkg/installed/x64-linux/share/folly/folly-config.cmake:63 (find_dependency)
  /root/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:786 (_find_package)
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /root/projects/vcpkg/installed/x64-linux/share/wangle/wangle-config.cmake:42 (find_dependency)
  /root/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:786 (_find_package)
  src/wangle_server/CMakeLists.txt:1 (find_package)


CMake Warning at /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/FindBoost.cmake:1354 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/FindBoost.cmake:1477 (_Boost_COMPONENT_DEPENDENCIES)
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/FindBoost.cmake:2087 (_Boost_MISSING_DEPENDENCIES)
  /root/projects/vcpkg/installed/x64-linux/share/boost/vcpkg-cmake-wrapper.cmake:11 (_find_package)
  /root/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:740 (include)
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /root/projects/vcpkg/installed/x64-linux/share/folly/folly-config.cmake:63 (find_dependency)
  /root/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:786 (_find_package)
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /root/projects/vcpkg/installed/x64-linux/share/wangle/wangle-config.cmake:42 (find_dependency)
  /root/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:786 (_find_package)
  src/wangle_server/CMakeLists.txt:1 (find_package)


CMake Warning at /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/FindBoost.cmake:1354 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/FindBoost.cmake:1477 (_Boost_COMPONENT_DEPENDENCIES)
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/FindBoost.cmake:2087 (_Boost_MISSING_DEPENDENCIES)
  /root/projects/vcpkg/installed/x64-linux/share/boost/vcpkg-cmake-wrapper.cmake:11 (_find_package)
  /root/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:740 (include)
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /root/projects/vcpkg/installed/x64-linux/share/folly/folly-config.cmake:63 (find_dependency)
  /root/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:786 (_find_package)
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /root/projects/vcpkg/installed/x64-linux/share/wangle/wangle-config.cmake:42 (find_dependency)
  /root/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:786 (_find_package)
  src/wangle_server/CMakeLists.txt:1 (find_package)


CMake Warning at /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/FindBoost.cmake:1354 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/FindBoost.cmake:1477 (_Boost_COMPONENT_DEPENDENCIES)
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/FindBoost.cmake:2087 (_Boost_MISSING_DEPENDENCIES)
  /root/projects/vcpkg/installed/x64-linux/share/boost/vcpkg-cmake-wrapper.cmake:11 (_find_package)
  /root/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:740 (include)
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /root/projects/vcpkg/installed/x64-linux/share/folly/folly-config.cmake:63 (find_dependency)
  /root/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:786 (_find_package)
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /root/projects/vcpkg/installed/x64-linux/share/wangle/wangle-config.cmake:42 (find_dependency)
  /root/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:786 (_find_package)
  src/wangle_server/CMakeLists.txt:1 (find_package)


CMake Warning at /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/FindBoost.cmake:1354 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/FindBoost.cmake:1477 (_Boost_COMPONENT_DEPENDENCIES)
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/FindBoost.cmake:2087 (_Boost_MISSING_DEPENDENCIES)
  /root/projects/vcpkg/installed/x64-linux/share/boost/vcpkg-cmake-wrapper.cmake:11 (_find_package)
  /root/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:740 (include)
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /root/projects/vcpkg/installed/x64-linux/share/folly/folly-config.cmake:63 (find_dependency)
  /root/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:786 (_find_package)
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /root/projects/vcpkg/installed/x64-linux/share/wangle/wangle-config.cmake:42 (find_dependency)
  /root/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:786 (_find_package)
  src/wangle_server/CMakeLists.txt:1 (find_package)


CMake Warning at /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/FindBoost.cmake:1354 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/FindBoost.cmake:1477 (_Boost_COMPONENT_DEPENDENCIES)
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/FindBoost.cmake:2087 (_Boost_MISSING_DEPENDENCIES)
  /root/projects/vcpkg/installed/x64-linux/share/boost/vcpkg-cmake-wrapper.cmake:11 (_find_package)
  /root/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:740 (include)
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /root/projects/vcpkg/installed/x64-linux/share/folly/folly-config.cmake:63 (find_dependency)
  /root/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:786 (_find_package)
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /root/projects/vcpkg/installed/x64-linux/share/wangle/wangle-config.cmake:42 (find_dependency)
  /root/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:786 (_find_package)
  src/wangle_server/CMakeLists.txt:1 (find_package)


-- Found Boost: /root/projects/vcpkg/installed/x64-linux/include (found suitable version "1.77.0", minimum required is "1.51.0") found components: context filesystem program_options regex system thread chrono date_time atomic 
-- Found folly: /root/projects/vcpkg/installed/x64-linux
CMake Error at /root/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:786 (_find_package):
  By not providing "FindSodium.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Sodium", but
  CMake did not find one.

  Could not find a package configuration file provided by "Sodium" with any
  of the following names:

    SodiumConfig.cmake
    sodium-config.cmake

  Add the installation prefix of "Sodium" to CMAKE_PREFIX_PATH or set
  "Sodium_DIR" to a directory containing one of the above files.  If "Sodium"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /root/projects/vcpkg/installed/x64-linux/share/fizz/fizz-config.cmake:53 (find_dependency)
  /root/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:786 (_find_package)
  /root/projects/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /root/projects/vcpkg/installed/x64-linux/share/wangle/wangle-config.cmake:43 (find_dependency)
  /root/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:786 (_find_package)
  src/wangle_server/CMakeLists.txt:1 (find_package)

-- Configuring incomplete, errors occurred!
See also "/root/projects/experiment-projects/WanglePractice/build/CMakeFiles/CMakeOutput.log".
See also "/root/projects/experiment-projects/WanglePractice/build/CMakeFiles/CMakeError.log".
```

### PR DESCRIPTION
**Pull request by nusus**
**Fix cmake build failure with wangle:x64-linux**

- #### What does your PR fix?  
  Fixes #20586

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  I encountered this issue on x64-linux，so I just fix it on x64-linux.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  `Sure`

### CODE REVIEW

**Comment by JonLiu1993** [comment]
@nusus , please sign our Contributor License Agreement before we can accept your contribution

**Comment by JonLiu1993** [comment]
@nusus ,Could you please fix this error and sign CLA:
https://dev.azure.com/vcpkg/public/_build/results?buildId=64022&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by JonLiu1993** [comment]
@nusus ,It seems that the ci test failed, please take a look:
https://dev.azure.com/vcpkg/public/_build/results?buildId=64426&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by JonLiu1993** [comment]
@nusus ,Ping for response

**Comment by JonLiu1993** [comment]
Draft this PR until it has any progress.

**Comment by BillyONeal** [comment]
wangle is currently building successfully, is there anything left to do here or should we close this?

**Comment by JonLiu1993** [comment]
I’m going to close this PR because it’s been a long time since any update has been made. If this is something you’d like to see merged and work is being done, please reopen.

**Pull request closed without merging**
