### PR TITLE
[openssl] Revise jom/nmake support

### PR DESCRIPTION
**Pull request by dg0yt**
- #### What does your PR fix?
  Uniformly use plain `vcpkg_build_nmake` for windows incl. nmake, leveraging the recently integrated `PREFER_JOM` with `nmake` fallback. This fallback should mitigate issues with running `jom` on some computers.
  It also cherry picks a post-3.0.7 fixup from #27618.

  PR history:
  Based on various issues reported for building port openssl on windows, this PR started as an attempt to build openssl without `jom` using plain `vcpkg_build_nmake` but turned into a revision of this script to integrate parallel build capabilities using `jom`. These script changes were merged as https://github.com/microsoft/vcpkg/pull/27255.
  Some past pushes also tested de-duplicating steps shared by the unix and windows branches.
  But now this PR is trimmed.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  unchanged, no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  yes

### CODE REVIEW

**Comment by dg0yt** [comment]
We probably won't remove `jom` due to build time with `nmake`, but there is still enough to take from this PR:
- General port cleanup
- Merge uwp rules into windows rules

There is still room for improvement, in particular where I don't know enough about the MSVC toolchain:
- More clear resolve the PDF/-Zi/-Z7 handling?
- Filter the -MP from concurrent builds (' jom')?

**Comment by dg0yt** [comment]
Hm, I think I pass the same options to jom and nmake, but CC (full path) arrives only in nmake log files, not jom makefiles.
OTOH, I wasn't able to create a minimal reproducer with jom and `echo $(CC)` :angry:

**Comment by dg0yt** [comment]
The current opencv4 regression is expected to be fixed by #27239.

**Comment by dg0yt** [comment]
Depends on #27255.

**Review by BillyONeal — APPROVED** [review]
I am far from an expert in this area but everything here seems reasonable. I've also closed my PR that this cherry picks.

**Comment by JavierMatosD** [comment]
Thanks you!

**Pull request merged**
