### PR TITLE
[msbuild]fix use UseEnv-True

### PR DESCRIPTION
**Pull request by MVoz**
Fixes issue # https://github.com/microsoft/vcpkg/issues/11050

was a mistake to use global settings

### CODE REVIEW

**Comment by Voskrese** [comment]
error x64-osx `mlpack` ?

`supermatrix.h' file not found`

```
In file included from /Volumes/data/work/1/s/installed/x64-osx/include/armadillo:88:
/Volumes/data/work/1/s/installed/x64-osx/include/armadillo_bits/include_superlu.hpp:95:12: fatal error: '/Volumes/data/work/1/s/installed/x64-osx/include/supermatrix.h' file not found
  #include ARMA_INCFILE_WRAP(ARMA_SLU_SUPERMATRIX_H)
```

error `vcpkg-utils` ?

**Comment by LilyWangL** [comment]
> error x64-osx `mlpack` ?
> 
> `supermatrix.h' file not found`
> 
> ```
> In file included from /Volumes/data/work/1/s/installed/x64-osx/include/armadillo:88:
> /Volumes/data/work/1/s/installed/x64-osx/include/armadillo_bits/include_superlu.hpp:95:12: fatal error: '/Volumes/data/work/1/s/installed/x64-osx/include/supermatrix.h' file not found
>   #include ARMA_INCFILE_WRAP(ARMA_SLU_SUPERMATRIX_H)
> ```
> 
> error `vcpkg-utils` ?

This error will be fixed in PR #11063.

**Comment by cbezault** [comment]
I'd suggest a full rebuild here.

**Comment by LilyWangL** [comment]
Thanks for your PR. Can you please resolve the conflicts against master?

**Comment by ras0219-msft** [comment]
Thanks for the quick hotfix!

**Pull request merged**
