### PR TITLE
[VMSS] Fix the printed error message

### LINKED ISSUE #12501: [vcpkg|manifest] Improve error messages
The following error did not tell me anything:
```
1> [CMake] Error: There are invalid field types in the CONTROL or manifest file of E:\Repos\StoPhys\vcpkg_manifest\vcpkg.json
1> [CMake] The following fields had the wrong types:
1> [CMake] 
1> [CMake]     dependencies was expected to be an array of dependencies
1> [CMake]     name was expected to be an identifier
1> [CMake] 
```

Solution:
every `"name": "<value>"` field must have a <value> with only lowercase characters. The error message did not really help here.

### PR DESCRIPTION
**Pull request by JackBoosY**
Fixes #12501
```
See ***/blob/master/docs/maintainers/maintainer-guide.md#manifest for solution.
```

### CODE REVIEW

**Comment by JackBoosY** [comment]
```
See github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#manifest for solution.
```
At least users can see this link now.

**Comment by BillyONeal** [comment]
Dropping depends:vm-update since there are no VM changes here.

I asked around for some Azure Pipelines folks to see if there's a way we can fix this without de-linkifying the results.

**Comment by BillyONeal** [comment]
Filed: https://developercommunity.visualstudio.com/content/problem/1160967/azure-devops-is-stripping-uris-from-build-log-outp.html

I'd like to give the ADO team a few days to try to resolve this before landing this workaround, but the workaround looks correct to me.

**Review by BillyONeal — APPROVED** [review]

**Comment by BillyONeal** [comment]
They didn't have an immediate solution, so merging this for now. Thanks for your help!

**Pull request merged**
