### PR TITLE
[VTK] Check if VTKTarget files exist

### PR DESCRIPTION
**Pull request by larshg**
**Describe the pull request**

- What does your PR fix? Fixes issue #10924

- Which triplets are supported/not supported? Have you updated the CI baseline?
Should support more variations.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes.

### CODE REVIEW

**Review by JackBoosY — CHANGES_REQUESTED** [review]
Please update the verion info. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).

**Comment by larshg** [comment]
Hmm, wonder where that commit went. Will do it right away.

**Comment by larshg** [comment]
Done.

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
LGTM, thanks for this PR!

**Comment by larshg** [comment]
There are more places, wait a bit with merge :)

**Comment by ras0219-msft** [comment]
LGTM, thanks for the PR!

**Pull request merged**
