### PR TITLE
[llvm] update to 16.0.6

### LINKED ISSUE #32466: [llvm] update to 17.0.1
### Library name

llvm

### New version number

17.0.1

### Other information that may be useful (release notes, etc...)

https://github.com/llvm/llvm-project/releases/tag/llvmorg-17.0.1

### PR DESCRIPTION
**Pull request by jimwang118**
Fixes https://github.com/microsoft/vcpkg/issues/32466
1.Update to 16.0.6.
2.Delete 0002-Fix-DR-1734.patch and 0008-llvm_assert.patch because the upstream has merged the patch.

Usage test pass with following triplets:

```
x86-windows
x64-windows
x64-windows-static
```
- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [X] SHA512s are updated for each updated download
- [ ] ~The "supports" clause reflects platforms that may be fixed by this new version~
- [ ] ~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~
- [X] Any patches that are no longer applied are deleted from the port's directory.
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by jimwang118** [comment]
duplicate of https://github.com/microsoft/vcpkg/pull/33600

**Comment by dg0yt** [comment]
> duplicate of https://github.com/microsoft/vcpkg/pull/33600

That PR is for LLVM 17.

**Comment by jimwang118** [comment]
> > duplicate of #33600
> 
> That PR is for LLVM 17.

Yes, there is a newer version upgrade. Do I still need to keep the older version?

**Comment by dg0yt** [comment]
> Yes, there is a newer version upgrade. Do I still need to keep the older version?

AFAIU "LLVM 17.0.0 has not been released yet" and https://github.com/microsoft/vcpkg/pull/33600 won't be ready for merge before that release.

**Comment by yurybura** [comment]
> > Yes, there is a newer version upgrade. Do I still need to keep the older version?
> 
> AFAIU "LLVM 17.0.0 has not been released yet" and #33600 won't be ready for merge before that release.

LLVM 17 is expected within two weeks.
If upgrading the port to v16.x is still interesting, let me know. I may try to make a new PR before the update to v17.x is complete.

**Comment by Neumann-A** [comment]
@yurybura: I don't think the 17 PR is mergeable unless mesa/halide move up their llvm version

**Comment by yurybura** [comment]
> @yurybura: I don't think the 17 PR is mergeable unless mesa/halide move up their llvm version

Both libraries have been updated to be compatible with LLVM v17, but no official releases are available yet.

**Pull request closed without merging**
