### PR TITLE
[nativefiledialog] update version to 2019-10-01

### PR DESCRIPTION
**Pull request by SamuelMarks**
Almost got this working!

### `CMakeLists.txt`
```cmake
cmake_minimum_required(VERSION 3.4)
cmake_policy(SET CMP0048 NEW)
project(pp VERSION 0.0.0 LANGUAGES C)

set(src "src/main.c")

find_package(unofficial-nativefiledialog CONFIG REQUIRED)

add_executable("${PROJECT_NAME}" "${src}")
target_link_libraries("${PROJECT_NAME}" PRIVATE unofficial::nativefiledialog::nfd)
```

#### `src/main.c`
```c
#include <nfd.h>
#include <stdio.h>
#include <stdlib.h>

int main( void )
{
    nfdchar_t *outPath = NULL;
    nfdresult_t result = NFD_OpenDialog( NULL, NULL, &outPath );
        
    if ( result == NFD_OKAY ) {
        puts("Success!");
        puts(outPath);
        free(outPath);
    }
    else if ( result == NFD_CANCEL ) {
        puts("User pressed cancel.");
    }
    else {
        printf("Error: %s\n", NFD_GetError() );
    }

    return 0;
}
```

### `sh`
```sh
$ [path]/vcpkg install nativefiledialog
Building package nativefiledialog[core]:x64-osx... done
Installing package nativefiledialog[core]:x64-osx...
Installing package nativefiledialog[core]:x64-osx... done
Elapsed time for package nativefiledialog:x64-osx: 4.761 s

Total elapsed time: 6.91 s

The package nativefiledialog:x64-osx provides CMake targets:

    find_package(unofficial-nativefiledialog CONFIG REQUIRED)
    target_link_libraries(main PRIVATE unofficial::nativefiledialog::nfd)
$ rm -rf cmake-build-debug && mkdir $_ && cd $_
$ cmake .. -DCMAKE_TOOLCHAIN_FILE=[path]'/vcpkg/scripts/buildsystems/vcpkg.cmake' -DCMAKE_BUILD_TYPE='Debug'
$ cmake . --build
[ 50%] Building C object CMakeFiles/pp.dir/src/main.c.o
[100%] Linking C executable pp
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_NSApplication", referenced from:
      objc-class-ref in libnfd_d.a(nfd_cocoa.m.o)
  "_OBJC_CLASS_$_NSArray", referenced from:
      objc-class-ref in libnfd_d.a(nfd_cocoa.m.o)
  "_OBJC_CLASS_$_NSAutoreleasePool", referenced from:
      objc-class-ref in libnfd_d.a(nfd_cocoa.m.o)
  "_OBJC_CLASS_$_NSMutableArray", referenced from:
      objc-class-ref in libnfd_d.a(nfd_cocoa.m.o)
  "_OBJC_CLASS_$_NSOpenPanel", referenced from:
      objc-class-ref in libnfd_d.a(nfd_cocoa.m.o)
  "_OBJC_CLASS_$_NSSavePanel", referenced from:
      objc-class-ref in libnfd_d.a(nfd_cocoa.m.o)
  "_OBJC_CLASS_$_NSString", referenced from:
      objc-class-ref in libnfd_d.a(nfd_cocoa.m.o)
  "_OBJC_CLASS_$_NSURL", referenced from:
      objc-class-ref in libnfd_d.a(nfd_cocoa.m.o)
  "_objc_alloc_init", referenced from:
      _NFD_OpenDialog in libnfd_d.a(nfd_cocoa.m.o)
      _NFD_OpenDialogMultiple in libnfd_d.a(nfd_cocoa.m.o)
      _NFD_SaveDialog in libnfd_d.a(nfd_cocoa.m.o)
      _NFD_PickFolder in libnfd_d.a(nfd_cocoa.m.o)
      _BuildAllowedFileTypes in libnfd_d.a(nfd_cocoa.m.o)
  "_objc_enumerationMutation", referenced from:
      _AllocPathSet in libnfd_d.a(nfd_cocoa.m.o)
  "_objc_msgSend", referenced from:
      _NFD_OpenDialog in libnfd_d.a(nfd_cocoa.m.o)
      _AddFilterListToDialog in libnfd_d.a(nfd_cocoa.m.o)
      _SetDefaultPath in libnfd_d.a(nfd_cocoa.m.o)
      _NFD_OpenDialogMultiple in libnfd_d.a(nfd_cocoa.m.o)
      _AllocPathSet in libnfd_d.a(nfd_cocoa.m.o)
      _NFD_SaveDialog in libnfd_d.a(nfd_cocoa.m.o)
      _NFD_PickFolder in libnfd_d.a(nfd_cocoa.m.o)
      ...
  "_objc_release", referenced from:
      _NFD_OpenDialog in libnfd_d.a(nfd_cocoa.m.o)
      _NFD_OpenDialogMultiple in libnfd_d.a(nfd_cocoa.m.o)
      _NFD_SaveDialog in libnfd_d.a(nfd_cocoa.m.o)
      _NFD_PickFolder in libnfd_d.a(nfd_cocoa.m.o)
      _BuildAllowedFileTypes in libnfd_d.a(nfd_cocoa.m.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [pp] Error 1
make[1]: *** [CMakeFiles/pp.dir/all] Error 2
make: *** [all] Error 2
```

### CODE REVIEW

**Review by JonLiu1993 — COMMENTED** [review]
@SamuelMarks, please add features under vcpkg_check_features in the port file.After change the pr ,please run the command "vcpkg x-add-version nativefiledialog --overwrite-version"

**Comment by JonLiu1993** [comment]
@SamuelMarks, please add features under vcpkg_check_features in the port file.After change the pr ,please run the command "vcpkg x-add-version nativefiledialog --overwrite-version".
I want help you do this but looks I don't have permission.

**Comment by JonLiu1993** [comment]
please add "FEATURES" under vcpkg_check_features in the port file

**Comment by JonLiu1993** [comment]
Ready for review now?

**Comment by SamuelMarks** [comment]
@JonLiu1993 It's not quite ready:
```
$ git clone https://github.com/microsoft/vcpkg /tmp/vcpkg
$ pushd /tmp/vcpkg && ./bootstrap-vcpkg.sh && gh pr checkout 17381
$ ./vcpkg install nativefiledialog && popd
# See initial post for this directory's contents
$ rm -rf cmake-build-debug ; mkdir "$_" && cd "$_"
$ cmake -DCMAKE_BUILD_TYPE='Debug' -DCMAKE_TOOLCHAIN_FILE='/tmp/vcpkg/scripts/buildsystems/vcpkg.cmake' ..
$ cmake --build .
-- The C compiler identification is AppleClang 12.0.5.12050022
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done
CMake Error in CMakeLists.txt:
  Imported target "unofficial::nativefiledialog::nfd" includes non-existent
  path

    "/tmp/vcpkg/buildtrees/nativefiledialog/src/3bcc5f7888-21c4d4e490.clean/"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in CMakeLists.txt:
  Imported target "unofficial::nativefiledialog::nfd" includes non-existent
  path

    "/tmp/vcpkg/buildtrees/nativefiledialog/src/3bcc5f7888-21c4d4e490.clean/"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

Also I was getting that `Undefined symbols for architecture x86_64:` error…

**Comment by JonLiu1993** [comment]
Pinging @SamuelMarks  for response. Is work still being done for this PR?

**Comment by SamuelMarks** [comment]
@JonLiu1993 Just merged master and brought in the changes again (force)

**Comment by JonLiu1993** [comment]
Thanks for your contribution, If this pr is ready for review, please let me know.

**Comment by JonLiu1993** [comment]
Is this PR being worked on?

**Comment by SamuelMarks** [comment]
Still getting that error, I think it's missing the cocoa link libraries:
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_NSApplication", referenced from:
      objc-class-ref in libnfd_d.a(nfd_cocoa.m.o)
  "_OBJC_CLASS_$_NSArray", referenced from:
      objc-class-ref in libnfd_d.a(nfd_cocoa.m.o)
  "_OBJC_CLASS_$_NSAutoreleasePool", referenced from:
      objc-class-ref in libnfd_d.a(nfd_cocoa.m.o)
  "_OBJC_CLASS_$_NSMutableArray", referenced from:
      objc-class-ref in libnfd_d.a(nfd_cocoa.m.o)
  "_OBJC_CLASS_$_NSOpenPanel", referenced from:
      objc-class-ref in libnfd_d.a(nfd_cocoa.m.o)
  "_OBJC_CLASS_$_NSSavePanel", referenced from:
      objc-class-ref in libnfd_d.a(nfd_cocoa.m.o)
  "_OBJC_CLASS_$_NSString", referenced from:
      objc-class-ref in libnfd_d.a(nfd_cocoa.m.o)
  "_OBJC_CLASS_$_NSURL", referenced from:
      objc-class-ref in libnfd_d.a(nfd_cocoa.m.o)
  "_objc_alloc_init", referenced from:
      _NFD_OpenDialog in libnfd_d.a(nfd_cocoa.m.o)
      _NFD_OpenDialogMultiple in libnfd_d.a(nfd_cocoa.m.o)
      _NFD_SaveDialog in libnfd_d.a(nfd_cocoa.m.o)
      _NFD_PickFolder in libnfd_d.a(nfd_cocoa.m.o)
      _BuildAllowedFileTypes in libnfd_d.a(nfd_cocoa.m.o)
  "_objc_enumerationMutation", referenced from:
      _AllocPathSet in libnfd_d.a(nfd_cocoa.m.o)
  "_objc_msgSend", referenced from:
      _NFD_OpenDialog in libnfd_d.a(nfd_cocoa.m.o)
      _AddFilterListToDialog in libnfd_d.a(nfd_cocoa.m.o)
      _SetDefaultPath in libnfd_d.a(nfd_cocoa.m.o)
      _NFD_OpenDialogMultiple in libnfd_d.a(nfd_cocoa.m.o)
      _AllocPathSet in libnfd_d.a(nfd_cocoa.m.o)
      _NFD_SaveDialog in libnfd_d.a(nfd_cocoa.m.o)
      _NFD_PickFolder in libnfd_d.a(nfd_cocoa.m.o)
      ...
  "_objc_release", referenced from:
      _NFD_OpenDialog in libnfd_d.a(nfd_cocoa.m.o)
      _NFD_OpenDialogMultiple in libnfd_d.a(nfd_cocoa.m.o)
      _NFD_SaveDialog in libnfd_d.a(nfd_cocoa.m.o)
      _NFD_PickFolder in libnfd_d.a(nfd_cocoa.m.o)
      _BuildAllowedFileTypes in libnfd_d.a(nfd_cocoa.m.o)
ld: symbol(s) not found for architecture x86_6
```

**Comment by JonLiu1993** [comment]
@SamuelMarks ,Thanks for your continuous contribution, please let me know when you modify this pr

**Comment by JonLiu1993** [comment]
@SamuelMarks ,Can I close this pr first? Then wait until you can fix it, and then you can reopen it again.

**Comment by SamuelMarks** [comment]
@JonLiu1993 Is there a "closed by" type trigger so that once that fix is merged this PR would reopen?

**Comment by JonLiu1993** [comment]
@SamuelMarks ,Yes, users can easily open closed pr or issue, just click "reopen"

**Pull request closed without merging**
