### PR TITLE
[skia] Remove use of vcpkg_apply_patches.

### PR DESCRIPTION
**Pull request by BillyONeal**
As requested by @ras0219 in the infrastructure update.

### CODE REVIEW

**Comment by cenit** [comment]
His new "editable" system is mitigating the eventual problem anyway ;)

**Comment by BillyONeal** [comment]
@cenit I'm not sure I follow. This thing needs to be patched, this is just changing where it is

**Comment by Neumann-A** [comment]
@BillyONeal The previous problem with `vcpkg_apply_patches` was that it could not be rerun on and already existing source tree. As vcpkg has `.clean` know the patches can always be applied unless you use `--editable`.

**Comment by cenit** [comment]
@BillyONeal I just remember this PR from the past https://github.com/microsoft/vcpkg/pull/8087 🤣

**Comment by BillyONeal** [comment]
I see. In this case I think this is better just for uniformity reasons.

**Review by LilyWangL — APPROVED** [review]

**Comment by LilyWangL** [comment]
@BillyONeal Please correct the Version field in the CONTROL file.

**Review by ras0219 — APPROVED** [review]

**Comment by BillyONeal** [comment]
@LilyWangL I didn't update that on purpose because there are no observable differences from this change so there was no reason to force `vcpkg upgrade` to trigger a reinstall. But not really a big deal either...

**Pull request merged**
