### PR TITLE
[ffmpeg] Fix ffmpeg[opencl, openssl, lzma] static build failed

### PR DESCRIPTION
**Pull request by LilyWangL**
Due to some functions in the lib file are missing link libraries that required, ffmpeg[opencl, openssl] static build failed. Build error in build-x64-windows-static-rel-out.log:
```
> type buildtrees\ffmpeg\build-x64-windows-static-rel-out.log
=== CONFIGURING ===
ERROR: opencl not found
```
Build error in config.log:
```
libeay32.lib(cryptlib.obj) : error LNK2019: unresolved external symbol __imp_DeregisterEventSource referenced in function OPENSSL_showfatal
libeay32.lib(cryptlib.obj) : error LNK2019: unresolved external symbol __imp_RegisterEventSourceW referenced in function OPENSSL_showfatal
libeay32.lib(cryptlib.obj) : error LNK2019: unresolved external symbol __imp_ReportEventW referenced in function OPENSSL_showfatal
libeay32.lib(cryptlib.obj) : error LNK2019: unresolved external symbol __imp_GetProcessWindowStation referenced in function OPENSSL_isservice
libeay32.lib(cryptlib.obj) : error LNK2019: unresolved external symbol __imp_GetUserObjectInformationW referenced in function OPENSSL_isservice
libeay32.lib(cryptlib.obj) : error LNK2019: unresolved external symbol __imp_MessageBoxW referenced in function OPENSSL_showfatal
libeay32.lib(bss_sock.obj) : error LNK2019: unresolved external symbol __imp_closesocket referenced in function sock_ctrl
libeay32.lib(bss_sock.obj) : error LNK2019: unresolved external symbol __imp_recv referenced in function sock_read
libeay32.lib(bss_sock.obj) : error LNK2019: unresolved external symbol __imp_send referenced in function sock_write
libeay32.lib(bss_sock.obj) : error LNK2019: unresolved external symbol __imp_shutdown referenced in function sock_ctrl
libeay32.lib(bss_sock.obj) : error LNK2019: unresolved external symbol __imp_WSASetLastError referenced in function sock_write
libeay32.lib(bss_sock.obj) : error LNK2019: unresolved external symbol __imp_WSAGetLastError referenced in function BIO_sock_should_retry
libeay32.lib(rand_win.obj) : error LNK2019: unresolved external symbol __imp_CreateCompatibleBitmap referenced in function RAND_screen
libeay32.lib(rand_win.obj) : error LNK2019: unresolved external symbol __imp_DeleteObject referenced in function RAND_screen
libeay32.lib(rand_win.obj) : error LNK2019: unresolved external symbol __imp_GetDeviceCaps referenced in function RAND_screen
libeay32.lib(rand_win.obj) : error LNK2019: unresolved external symbol __imp_GetDIBits referenced in function RAND_screen
libeay32.lib(rand_win.obj) : error LNK2019: unresolved external symbol __imp_GetObjectW referenced in function RAND_screen
libeay32.lib(rand_win.obj) : error LNK2019: unresolved external symbol __imp_GetDC referenced in function RAND_screen
libeay32.lib(rand_win.obj) : error LNK2019: unresolved external symbol __imp_ReleaseDC referenced in function RAND_screen
```
Related issue: #8631
All features test pass.

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by strega-nil** [comment]
Thanks @LilyWangL :)

**Pull request merged**
