### PR TITLE
Trivial print out change

### PR DESCRIPTION
**Pull request by o-mdr**
- An error message now contains a command that we can copy-paste directly to powershell
  vcpkg update   =>      .\\vcpkg update
  Adding two slashes to escape the output

### CODE REVIEW

**Comment by o-mdr** [comment]
Before
image


After
image

**Comment by sdcb** [comment]
@o-mdr  If vcpkg is in PATH environment(like me), I think the ".\vcpkg" would fail.

**Comment by o-mdr** [comment]
At least it would be consistent with all the examples on the [readme](https://github.com/Microsoft/vcpkg/blob/master/README.md) and [/doc/EXAMPLES.md](https://github.com/Microsoft/vcpkg/blob/master/docs/EXAMPLES.md)

Otherwise, some commands are prefixed with `\.` and others not.

**Comment by ras0219-msft** [comment]
Thanks for this.

@sdcb While we definitely think adding `vcpkg` to your path is the best experience, our official new user documentation instructs users to run `vcpkg` directly from the repository. For those users, I've personally seen how common it is to forget to add `.\`. Once you've added us to your path, I think it's safe to assume you know to drop the `.\` as appropriate ;).

**Pull request merged**
