### PR TITLE
[gsl] FTP link was not working

### PR DESCRIPTION
**Pull request by ajayrawat**
FTP link was not functional. Update it with "https://ftp.gnu.org/gnu/gsl/gsl-${GSL_VERSION}.tar.gz"

### CODE REVIEW

**Comment by NancyLi1013** [comment]
Related PR #9123.

**Comment by c72578** [comment]
PR #9123 has been merged into master:
2c7ff757a10a1d63e5fd6e295430f00bd67b902c

This PR can be closed now.

**Comment by dan-shaw** [comment]
See #9123

**Pull request closed without merging**
