### PR TITLE
[libflac] update to 1.4.2

### LINKED ISSUE #27318: [libflac] update to 1.4.1
Library name: libflac

New version number: 1.4.1

https://xiph.org/flac/changelog.html

https://github.com/xiph/flac/releases/tag/1.4.1

### PR DESCRIPTION
**Pull request by JonLiu1993**
Fix #27318 

Update libflac to the latest version 1.4.2

feature asm tested successfully in the x86-windows triplet.

### CODE REVIEW

**Review by PriitUring — CHANGES_REQUESTED** [review]
If pull request and commit is about v1.4.2 then commit title should not contain v1.4.1.

**Comment by JonLiu1993** [comment]
> If pull request and commit is about v1.4.2 then commit title should not contain v1.4.1.

@PriitUring, thanks for the heads up, I wrote a wrong commit title, but the commit is about v1.4.2

**Comment by Adela0814** [comment]
Closing this PR since it seems that no progress is being made. Please ping us to reopen if work is still being done.

**Comment by JonLiu1993** [comment]
Duplicate of #29584.

**Pull request closed without merging**
