### PR TITLE
[grpc] yet another library missing in pkg-config files

### LINKED ISSUE #7217: Cannot link Pub/Sub library with vcpkg and pkg-config
**Does this issue affect the google-cloud-cpp project?**

Maybe. It may be that we are not creating proper `pkg-config` files.  Or it could be that the problem is with the gRPC packages.

**What component of `google-cloud-cpp` is this related to?**

Cloud Pub/Sub

**Describe the bug**

Using `pkg-config` to compile an application against the Cloud Pub/Sub library, where `google-cloud-cpp` and its dependencies are compiled with `vcpkg`.

**To Reproduce**

Presumably something like

```sh
vcpkg install google-cloud-cpp
cd $HOME/google-cloud-cpp/google/cloud/pubsub/quickstart
PKG_CONFIG_PATH=$VCPKG_ROOT/installed/x64-linux/lib/pkgconfig make
```

**Expected behavior**

The application should compile and link.

**What version of `google-cloud-cpp` are you using?**

v1.30.1 from `vcpkg`.

**Additional context**

The customer reporting this problem was using `qmake`.

### PR DESCRIPTION
**Pull request by coryan**
Fixes the pkg-config files generated by gRPC

- #### What does your PR fix?  

  Fixes googleapis/google-cloud-cpp#7217 

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  

No change

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  

Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  

Yes

### CODE REVIEW

**Comment by coryan** [comment]
I cannot reproduce the errors locally, and the logs seem either unrelated or I do not understand them.  If somebody could take a look and tell me what to fix I would be happy to fix them.

**Comment by NancyLi1013** [comment]
Hi @coryan 

Thanks for your fixes. The error log is not related with your PR. I have rerun to retrigger CI.

**Comment by NancyLi1013** [comment]
Seems this is also a upstream bug for `grpc`. https://github.com/grpc/grpc/issues/25562

**Review by NancyLi1013 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the bugfix and sorry for our CI instability this week :)

**Pull request merged**
