### PR TITLE
[tinyxml2] Update tinyxml2 to fix static linkage

### PR DESCRIPTION
**Pull request by brad-anderson**
Also specify BUILD_STATIC_LIBS when building static

### CODE REVIEW

**Comment by eco** [comment]
Err, hold on. Didn't test this with non-static builds...

**Comment by eco** [comment]
Ok, this is good to go.

**Comment by ras0219-msft** [comment]
Thanks for the PR!

We automatically set `BUILD_SHARED_LIBS`[1] since it's a core recognized CMake variable, so you can omit those lines.

[1] https://github.com/Microsoft/vcpkg/blob/6925b45c27ff255ad507caf7b58d3585fe5989f5/scripts/cmake/vcpkg_configure_cmake.cmake#L106-L110

**Comment by eco** [comment]
Alright, took `BUILD_SHARED_LIBS` out.

**Comment by ras0219-msft** [comment]
Great, thanks!

**Pull request merged**
