### PR TITLE
[curl] Add openldap support on curl

### PR DESCRIPTION
**Pull request by LouisClt**
Hello, I wanted to compute curl with ldap support on linux, but it was not activable given the current options.
This patch aims to resolve this issue and works well in my testing.
But the behaviour of the curl library is to disable ldap support automatically if no ldap.h file is found. So there might be problems where ldap is not included whereas put on the command options.
The other issue is that the guidelines say that options can't be alternatives, but here winldap and openldap are alternatives on windows (if both options are included, winldap will supersedes openldap).

There was this old issue that explains the winldap option : #14030
Also, openldap does not compile for the moment on windows, so this is only useful on linux.

I would appreciate to have some reviews for this proposal. 

- [ ] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [ ] SHA512s are updated for each updated download.
- [ ] The "supports" clause reflects platforms that may be fixed by this new version.
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [ ] Any patches that are no longer applied are deleted from the port's directory.
- [ ] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [ ] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by dg0yt** [comment]
There is an openldap port. It doesn't support MSVC, but it is the obvious dependency unless the LDAP backend is winldap.
So a possible implementation is:
- Create a generic feature `ldap`.
- Let it depend on `openldap` for `!windows`.
- Either remove `winldap`, or make it do nothing but depend on `ldap`.

For MinGW, the situation is ambiguous, and one alternative must be chosen. (But again, the openldap backend needs the openldap dependency.)

**Comment by MonicaLiu0311** [comment]
At present, the version information of your commit is inconsistent with your local one:
```
##[error]Found the following errors:
##[error]versions/c-/curl.json(2,): error : while parsing versions for curl from version/c-/curl.json
8.5.0#1 is declared with 7b2bf8e8f4e0c7d000cb3b3311f4b9f185cb2d52, but the local port has a different SHA b54d9e1e94eff7f99eaafcd03fe23284d7eccaaf.
Please update the port's version fields and then run:
vcpkg x-add-version curl
git add versions
git commit -m "Update version database"
to add the new version.
To attempt to resolve all errors at once, run:
vcpkg x-add-version --all
##[error]PowerShell exited with code '1'.
```
Please run `./vcpkg x-add-version portName ` before each push:
1. For any file modification under the `ports/liblemon/` folder, please commit after modification
2. Run `./vcpkg x-add-version portName` to generate a series of version according to your commit info
3. Commit verison information again
4. Push together

`--overwrite-version`
After the first modification, please run `./vcpkg x-add-version portName` to generate the corresponding json; for subsequent modifications of the same version, please use `./vcpkg x-add-version portName --overwrite-version` to update git-tree.

[maintainer guide#versioning](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md#versioning).

**Comment by LouisClt** [comment]
@microsoft-github-policy-service agree

**Comment by MonicaLiu0311** [comment]
Ping @LouisClt

**Comment by LouisClt** [comment]
Sorry @MonicaLiu0311  , I have been busy doing other things...
I will update the code this week.

**Comment by LouisClt** [comment]
I did the update to the version, I hope this will be correct.

I also tried to make the suggestion of @dg0yt , but found out that we need to pass the USE_WIN32_LDAP in case of winldap.
So I can't just make winldap do nothing. And if I create a generic "ldap" feature, this one has to depend on "winldap" on windows in order to set the USE_WIN32_LDAP .

So I felt that was better to stick to one "openldap" and one "winldap" feature.

But feel free to correct me.

**Comment by dg0yt** [comment]
Hm, difficult to make the proposal in review comments. I can try to prepare a PR to your fork.

**Comment by LouisClt** [comment]
Yeah sorry, didn't see that there were conflicts before pushing ... I will fix that

**Comment by dg0yt** [comment]
Can I CC you for testing another PR?

**Comment by LouisClt** [comment]
Yeah no problem
(or maybe if I find a solution I will reopen this one)

**Pull request closed without merging**
