### PR TITLE
Fixed some possible incorrect comparison with null warnings.

### PR DESCRIPTION
**Pull request by soroshsabz**
ITNOA

Hi,

I think it is good to make consistent way to write PowerShell script, therefor I think [PSScriptAnalyzer rules](https://github.com/PowerShell/PSScriptAnalyzer/tree/development/RuleDocumentation) is good choice to consider.

One of the rule is [
PossibleIncorrectComparisonWithNull](https://github.com/PowerShell/PSScriptAnalyzer/blob/development/RuleDocumentation/PossibleIncorrectComparisonWithNull.md), so I fixed some violation of this rule in `bootstrap.ps1` file.

### CODE REVIEW

**Comment by soroshsabz** [comment]
Sorry for butterfingers commits.

**Comment by soroshsabz** [comment]
@vicroms is any problem to merge it?

thx

**Comment by vicroms** [comment]
I don't see any problems with it, I'l run it trough the CI system.

**Comment by soroshsabz** [comment]
@vicroms thanks :)

**Pull request merged**
