### PR TITLE
[DPP] Bump to version 10.0.18

### PR DESCRIPTION
**Pull request by braindigitalis**
**This PR updates DPP package to 10.0.18**

Our vcpkg update is built from our CI actions.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  `Triplets are unchanged, baseline not updated.`

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  `Yes`

### CODE REVIEW

**Review by Adela0814 — DISMISSED** [review]

**Comment by dan-shaw** [comment]
Can you fix the merge conflicts?

**Comment by braindigitalis** [comment]
> 

uh how do i fix this??? you asked me to resolve the merge conflicts (there werent any when i submitted this pr) and now i get this from the bot?

**Comment by Adela0814** [comment]
Please `git pull` the latest master branch and fix the conflicts.
```
    Error: While reading versions for port dpp from file: C:\a\1\s\versions\d-\dpp.json
       File declares version `10.0.18` with SHA: d3b9a27035fbf133d20d21f41e1db5bb1442ed8f
       But local port with the same version has a different SHA: 7e80b88acd9bc75ce2b9bcaeae729f758ca2fcde
```

**Comment by braindigitalis** [comment]
thanks, pr is updated

**Review by Adela0814 — APPROVED** [review]

**Pull request merged**
