### PR TITLE
Add install googletest/src and Fix find_package Gtest

### PR DESCRIPTION
**Pull request by UnaNancyOwen**
Google Test provide <code>gtest-all.cc</code> for project that desirable to build Google Test by compiling a single file.
This pull request will be install <code>googletest/src</code> directory for these projects.
Who is using? For example, It is used in PCL.

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for the PR!

How will these be used by consuming projects? I assume we probably will need to add this subdirectory to some cmake variable so the files are findable?

**Comment by UnaNancyOwen** [comment]
the original FindGtest.cmake that include in CMake/Modules doesn't provide feature of find these file/directory. It seems like it is implemented in each project.
In case of PCL, It seems to be able to find it correctly without fixing CMake files.

**Comment by UnaNancyOwen** [comment]
In addition, I have noticed that FindGtest.cmake that include in CMake finds the debug libraries that file name with postfix "d". ([CMake/Modules/FindGtest.cmake#L181-L193](https://github.com/Kitware/CMake/blob/v3.10.0/Modules/FindGTest.cmake#L181-L193))
Therefore, Additional commit add postfix "d" to the debug libraries name.
Users will be able to find googletest libraries correctly with <code>find_package(GTest)</code>.

**Comment by UnaNancyOwen** [comment]
@ras0219-msft Please review again. If there is no problem, I think ready to be merged this pull request.

**Comment by UnaNancyOwen** [comment]
@ras0219-msft @alexkaratarakis ping

**Comment by ras0219-msft** [comment]
Thanks for the ping. I confirmed that support for the `d` prefix has been in FindGTest for a long while :)

I also reverted the renaming of the _DLLs_ because those are referred to by name inside the lib files. The lib files are what are searched for, so renaming them is sufficient.

**Comment by gnaggnoyil** [comment]
Where should those sources be installed though? Should they be put into `${CURRENT_PACKAGES_DIR}/src` directly, or on a location wrapped like `${CURRENT_PACKAGES_DIR}/src/gtest/src`?

**Pull request merged**
