### PR TITLE
[wxwidgets] CMake re-run must not change libs

### PR DESCRIPTION
**Pull request by dg0yt**
- #### What does your PR fix?
  https://github.com/microsoft/vcpkg/issues/24489.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  unchanged, no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  yes

### CODE REVIEW

**Comment by dg0yt** [comment]
@marekr This change seems to fix https://github.com/microsoft/vcpkg/issues/24489. I would appreciate if you could test it locally. I use MSVC only in CI, and so I can only read logs from build failures.

**Comment by marekr** [comment]
> @marekr This change seems to fix #24489. I would appreciate if you could test it locally. I use MSVC only in CI, and so I can only read logs from build failures.

Ran it against my project and it's working fine.

**Comment by dg0yt** [comment]
Windows CI test output (without the fix) is now:
~~~
CMake Error at scripts/test_ports/vcpkg-ci-wxwidgets/portfile.cmake:29 (message):
  wxWidgets libraries changed after CMake re-run

  actual:

  --
  wxWidgets_LIBRARIES:=D:/installed/x64-windows-static/lib/wxmsw31u_core.lib\;D:/installed/x64-windows-static/lib/wxbase31u.lib\;D:/installed/x64-windows-static/lib/wxregexu.lib\;winmm\;comctl32\;uuid\;oleacc\;uxtheme\;rpcrt4\;shlwapi\;version\;wsock32\;optimized\;D:/installed/x64-windows-static/lib/libexpatMD.lib\;debug\;D:/installed/x64-windows-static/debug/lib/libexpatdMD.lib\;optimized\;D:/installed/x64-windows-static/lib/jpeg.lib\;debug\;D:/installed/x64-windows-static/debug/lib/jpeg.lib\;optimized\;D:/installed/x64-windows-static/lib/libpng16.lib\;debug\;D:/installed/x64-windows-static/debug/lib/libpng16d.lib\;optimized\;D:/installed/x64-windows-static/lib/zlib.lib\;debug\;D:/installed/x64-windows-static/debug/lib/zlibd.lib\;optimized\;D:/installed/x64-windows-static/lib/tiff.lib\;debug\;D:/installed/x64-windows-static/debug/lib/tiffd.lib\;optimized\;D:/installed/x64-windows-static/lib/lzma.lib\;debug\;D:/installed/x64-windows-static/debug/lib/lzma.lib\;optimized\;D:/installed/x64-windows-static/lib/jpeg.lib\;debug\;D:/installed/x64-windows-static/debug/lib/jpeg.lib\;optimized\;D:/installed/x64-windows-static/lib/zlib.lib\;debug\;D:/installed/x64-windows-static/debug/lib/zlibd.lib\;optimized\;D:/installed/x64-windows-static/lib/zlib.lib\;debug\;D:/installed/x64-windows-static/debug/lib/zlibd.lib


  expected:

   -- wxWidgets_LIBRARIES:=debug\;D:/installed/x64-windows-static/debug/lib/wxmsw31ud_core.lib\;optimized\;D:/installed/x64-windows-static/lib/wxmsw31u_core.lib\;debug\;D:/installed/x64-windows-static/debug/lib/wxbase31ud.lib\;optimized\;D:/installed/x64-windows-static/lib/wxbase31u.lib\;debug\;D:/installed/x64-windows-static/debug/lib/wxregexud.lib\;optimized\;D:/installed/x64-windows-static/lib/wxregexu.lib\;winmm\;comctl32\;uuid\;oleacc\;uxtheme\;rpcrt4\;shlwapi\;version\;wsock32\;optimized\;D:/installed/x64-windows-static/lib/libexpatMD.lib\;debug\;D:/installed/x64-windows-static/debug/lib/libexpatdMD.lib\;optimized\;D:/installed/x64-windows-static/lib/jpeg.lib\;debug\;D:/installed/x64-windows-static/debug/lib/jpeg.lib\;optimized\;D:/installed/x64-windows-static/lib/libpng16.lib\;debug\;D:/installed/x64-windows-static/debug/lib/libpng16d.lib\;optimized\;D:/installed/x64-windows-static/lib/zlib.lib\;debug\;D:/installed/x64-windows-static/debug/lib/zlibd.lib\;optimized\;D:/installed/x64-windows-static/lib/tiff.lib\;debug\;D:/installed/x64-windows-static/debug/lib/tiffd.lib\;optimized\;D:/installed/x64-windows-static/lib/lzma.lib\;debug\;D:/installed/x64-windows-static/debug/lib/lzma.lib\;optimized\;D:/installed/x64-windows-static/lib/jpeg.lib\;debug\;D:/installed/x64-windows-static/debug/lib/jpeg.lib\;optimized\;D:/installed/x64-windows-static/lib/zlib.lib\;debug\;D:/installed/x64-windows-static/debug/lib/zlibd.lib\;optimized\;D:/installed/x64-windows-static/lib/zlib.lib\;debug\;D:/installed/x64-windows-static/debug/lib/zlibd.lib
~~~

**Comment by BillyONeal** [comment]
Thanks for the CI improvement!

**Pull request merged**
