### PR TITLE
[libtorrent] Update to 1.2.8

### PR DESCRIPTION
**Pull request by FranciscoPombal**
Here we go again...

No-change version bump.

Previously: https://github.com/microsoft/vcpkg/pull/11709

### CODE REVIEW

**Review by NancyLi1013 — COMMENTED** [review]
Since we have added `Supports: !uwp` in CONTROL file, there is no need to set the triplets as fail in ci.baseline.txt.

Could you please remove the following codes from ci.baseline.txt?
```
libtorrent:arm-uwp=fail
libtorrent:x64-uwp=fail
```

**Comment by NancyLi1013** [comment]
Hi @FranciscoPombal 
Thanks for this PR.

Have you tested these features? Do they work fine?

**Comment by FranciscoPombal** [comment]
@NancyLi1013 

> Could you please remove the following codes from ci.baseline.txt?

Done.

> Have you tested these features? Do they work fine?

Yes, looks good on my end.

**Review by NancyLi1013 — APPROVED** [review]

**Pull request merged**
