### PR TITLE
[curl] Update version to 7.88.1 to fix incomplete read/writes.

### LINKED ISSUE #29499: [openssl+curl] OpenSSL doesn't work with curl on MacOS after updating to latest vcpkg
**Describe the bug**
After ~1.5 year we're updating all our libraries to the latest available in vcpkg. Unfortunately, it seems that there was some OpenSSL update in vcpkg and now Curl library doesn't work with OpenSSL on OSX (it works ok on Ubuntu and Windows 32/64).

When trying to connect to HTTPS target via Curl, we're receiving the following error: `Internal SSL engine error encountered during the SSL handshake`

This is the complete log of Curl when enabling verbose mode:

```
* STATE: INIT => CONNECT handle 0x7f8201879e08; line 1909 (connection #-5000)
* Added connection 1. The cache now contains 2 members
* STATE: CONNECT => RESOLVING handle 0x7f8201879e08; line 1955 (connection #1)
* [CONN-1-0] setup, init filter chain
* [CONN-1-0] cf_add(filter=SOCKET)
* [CONN-1-0] cf_add(filter=SSL)
* [CONN-1-0][CF-SOCKET] setup(remotehost=private-24fa-unittests.apiary-mock.com)
* STATE: RESOLVING => CONNECTING handle 0x7f8201879e08; line 2029 (connection #1)
* family0 == v4, family1 == v6
*   Trying 23.212.110.201:443...
* [CONN-1-0] connect(block=0)-> 0, done=0
* [CONN-1-0] connect(block=0)-> 0, done=0
* Connected to private-24fa-unittests.apiary-mock.com (23.212.110.201) port 443 (#1)
* ALPN: offers http/1.1
* [CONN-1] Didn't find Session ID in cache for host HTTPS://private-24fa-unittests.apiary-mock.com:443
* [CONN-1] Added Session ID to cache for HTTPS://private-24fa-unittests.apiary-mock.com:443 [server]
* [CONN-1-0] connect(block=0)-> 0, done=0
* Internal SSL engine error encountered during the SSL handshake
* [CONN-1-0] connect(block=0)-> 35, done=0
* multi_done: status: 35 prem: 1 done: 0
* multi_done, not re-using connection=1, forbid=0, close=1, premature=1, stream=0
* The cache now contains 1 members
* Curl_disconnect(conn #1, dead=1)
* Closing connection 1
* Expire cleared (transfer 0x7f8201879e08)
* 
```

The same code works ok with the previous version of vcpk (hash `d8d61c941c333a147edffdcbdc9964dc0c0962f5`) and also the same code works ok on Ubuntu and Windows.

Unfortunately, I'm not able to find any other information about the error `Internal SSL engine error encountered during the SSL handshake`

**Environment**
- OS: Mac OS Catalina 10.15
- Compiler: Applce clang 12.0.0

**To Reproduce**

./vcpkg install openssl
./vcpkg install curl[openssl]

**To simulate**

The following snippet (with disabled CA verification and host verification) works ok on Ubuntu/Windows with the latest version of vcpk but doesn't work on OS X.

```
	AX_TEST_CASE(verify)
	{
	CURL* curl;
	CURLcode res;
	curl_global_init(CURL_GLOBAL_DEFAULT);

	curl = curl_easy_init();
	if (curl) {
		curl_easy_setopt(curl, CURLOPT_URL, "https://private-24fa-unittests.apiary-mock.com/body-and-header");
		curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L);
		curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 0L);

		res = curl_easy_perform(curl);
		if (res != CURLE_OK)
			fprintf(stderr, "curl_easy_perform() failed: %s\n",
				curl_easy_strerror(res));

		int nResponseCode = 0;
		curl_easy_getinfo(curl, CURLINFO_RESPONSE_CODE, &nResponseCode);
		TEST_CHECK_EQUAL(nResponseCode, 200);

		curl_easy_cleanup(curl);
	}
	curl_global_cleanup();
}
```

### PR DESCRIPTION
**Pull request by FrankXie05**
Fix https://github.com/microsoft/vcpkg/issues/29499

Note: Reference the upstream commit. Solve the problem that when the length is too long, it cannot be accepted and sent
https://github.com/curl/curl/commit/16bb32e104d348e05ec84436ded662ae4f761019

```
Internal SSL engine error encountered during the SSL handshake.
```
cc @ludekvodicka could you please test this PR?
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- ~~[ ] The "supports" clause reflects platforms that may be fixed by this new version~~
- ~~[ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- ~~[ ] Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by FrankXie05** [comment]
@marekr Thank you for reminding, I will finish the update today.

**Comment by marekr** [comment]
> @marekr Thank you for reminding, I will finish the update today.

Actually you may want to hold off until Feb 20, a somewhat problematic bug affecting HTTP2 connections was found so a 7.88.1 release is being made 

https://github.com/curl/curl/issues/10525#issuecomment-1432713383

**Comment by FrankXie05** [comment]
I'll wait. Thanks. :)

**Comment by dg0yt** [comment]
@FrankXie05  curl 7.88.1 is released.

**Review by Adela0814 — APPROVED** [review]

**Pull request merged**
