### PR TITLE
[lapack-reference] add to CMAKE_FIND_LIBRARY_SUFFIXES additional suffixes

### PR DESCRIPTION
**Pull request by xandox**
add to `CMAKE_FIND_LIBRARY_SUFFIXES` additional suffixes with versions for make find_library to able to find libgfortran

Under ubuntu (do not check for other distributives) libgfortran always has some version suffix and cmake find_library not able to find them without additional suffixes in CMAKE_FIND_LIBRARY_SUFFIXES as result FindLAPACK.cmake always fails and as result installing port lapack under ubuntu always fails. 

- What does your PR fix? Fixes #
find_library(gfortran)

- Which triplets are supported/not supported? Have you updated the CI baseline?

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
yes

### CODE REVIEW

**Comment by xandox** [comment]
@Neumann-A How you think is it ok?

**Comment by Neumann-A** [comment]
@xandox Normally there should be a symlink called `libgfortran.so`.

**Comment by JackBoosY** [comment]
@xandox Did you test the usage?

**Review by JackBoosY — APPROVED** [review]

**Comment by Neumann-A** [comment]
It would be better to restore the original CMAKE_FIND_LIBRARY_SUFFIXES after the find_library call for gfortran. Alternatively, adding additional search paths to the find_library call could also work?

**Comment by strega-nil** [comment]
LGTM! Thanks @xandox!

**Pull request merged**
