### PR TITLE
[Azure-IoT-Sdk*] Update to 2020-07-19

### PR DESCRIPTION
**Pull request by ewertons**
Azure-IoT-Sdk for C release 2020-07-19

### CODE REVIEW

**Review by NancyLi1013 — CHANGES_REQUESTED** [review]

**Comment by NancyLi1013** [comment]
Hi @ewertons 
Thanks for this PR.
Have you tested these features?

**Comment by ewertons** [comment]
Hi @NancyLi1013 , thanks for the review and suggested changes.
Yes, our packages have been tested. Please merge the PR as soon as possible, so we can proceed with our release process. 
Thanks.

**Review by NancyLi1013 — COMMENTED** [review]
There are no portfile.cmake files that also need to be updated for `azure-macro-utils-c` and  `umock-c`.
Could you please update them?

**Comment by ewertons** [comment]
Thanks @NancyLi1013 , actually upon verification these two ports do not need to change. I updated the PR not to update azure-macro-utils-c and umock-c.

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
@ewertons 
Thanks for your clarification. 
LGTM now.

**Comment by ewertons** [comment]
@NancyLi1013 , if the changes are good could we please get them merged? Our latest release depends on this update. Thanks.

**Comment by NancyLi1013** [comment]
@ewertons 
Since there is something wrong with CI checks. I will try to rerun this PR.
We will merge this if all CI checks have passed.

**Pull request merged**
