### PR TITLE
[openssl] Update to 3.3.0, limited cmake config fixup

### PR DESCRIPTION
**Pull request by dg0yt**
Based on #38118, credits: @talregev.

OpenSSL now installs a CMake config, but it is not generated by CMake, and it is not multi-config capable. This limitation affects location properties, interface link libraries and package variables.
This PR just patches the config to chainload CMake's Find module. Together with vcpkg's cmake wrapper, this immediately gives the desired imported targets in a multi-config configuration when a user really requests `OpenSSL CONFIG`.

### CODE REVIEW

**Comment by talregev** [comment]
@dg0yt Thank you!

**Comment by jimwang118** [comment]
Usage test pass with following triplets:

```
x86-windows
x64-windows
x64-windows-static
```

**Comment by Neustradamus** [comment]
Thanks @talregev and @dg0yt!

It fixes:
- https://github.com/microsoft/vcpkg/issues/38076

**Comment by WangWeiLin-MV** [comment]
Fixed #38076

**Pull request merged**
