### PR TITLE
[cyclonedds] update to 0.10.4

### PR DESCRIPTION
**Pull request by ex-purple**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by jimwang118** [comment]
When testing locally, the following error occurs.
```
F:\cyclonedds\buildtrees\cyclonedds\src\0.10.4-13ac356444.clean\src\core\ddsi\include\dds/ddsi/ddsi_serdata.h(328): error C2375: 'ddsi_serdata_from_iox': redefinition; different linkage
F:\cyclonedds\buildtrees\cyclonedds\src\0.10.4-13ac356444.clean\src\core\ddsi\include\dds/ddsi/ddsi_serdata.h(326): note: see declaration of 'ddsi_serdata_from_iox'
F:\cyclonedds\buildtrees\cyclonedds\src\0.10.4-13ac356444.clean\src\core\ddsi\include\dds/ddsi/ddsi_serdata.h(335): error C2375: 'ddsi_serdata_from_loaned_sample': redefinition; different linkage
F:\cyclonedds\buildtrees\cyclonedds\src\0.10.4-13ac356444.clean\src\core\ddsi\include\dds/ddsi/ddsi_serdata.h(333): note: see declaration of 'ddsi_serdata_from_loaned_sample'
```
.\vcpkg.exe install cyclonedds[*] --allow-unsupported
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/12733662/install-x64-windows-dbg-out.log)

**Comment by dg0yt** [comment]
> .\vcpkg.exe install cyclonedds[*] --allow-unsupported

Any errors with *supported* features?

**Comment by jimwang118** [comment]
> > .\vcpkg.exe install cyclonedds[*] --allow-unsupported
> 
> Any errors with _supported_ features?

The `shm` feature does not support the Windows platform. In order not to interrupt the installation, I added `--allow-unsupported`.

**Comment by dg0yt** [comment]
If you ask for *unsupported* features, the build is more and less *expected to fail*, i.e. to "interrupt the installation".
This is not how to do PR reviews.
If you don't want to manually remove unsupported features from the command line, I would recommend to build vcpkg with the test-features PR.

**Comment by jimwang118** [comment]
> If you ask for _unsupported_ features, the build is more and less _expected to fail_, i.e. to "interrupt the installation". This is not how to do PR reviews. If you don't want to manually remove unsupported features from the command line, I would recommend to build vcpkg with the test-features PR.

OK, I use the test command:` .\vcpkg.exe install cyclonedds[ddsperf,deadline-missed,idlc,ipv6,lifespan,security,source-specific-multicast,ssl,topic-discovery,type-discovery]:x64-windows` , re-tested, and this time the following error occurred.
```
FAILED: src/tools/ddsperf/ddsperf_types.c src/tools/ddsperf/ddsperf_types.h F:/cyclonedds/buildtrees/cyclonedds/x64-windows-dbg/src/tools/ddsperf/ddsperf_types.c F:/cyclonedds/buildtrees/cyclonedds/x64-windows-dbg/src/tools/ddsperf/ddsperf_types.h 
cmd.exe /C "cd /D F:\cyclonedds\buildtrees\cyclonedds\x64-windows-dbg\src\tools\ddsperf && F:\cyclonedds\buildtrees\cyclonedds\x64-windows-dbg\bin\idlc.exe -Wno-implicit-extensibility -oF:/cyclonedds/buildtrees/cyclonedds/x64-windows-dbg/src/tools/ddsperf F:/cyclonedds/buildtrees/cyclonedds/src/0.10.4-13ac356444.clean/src/tools/ddsperf/ddsperf_types.idl"
ninja: build stopped: subcommand failed.
```
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/12735871/install-x64-windows-dbg-out.log)

**Comment by jimwang118** [comment]
Thanks for your PR, Is work still being done for this PR?

**Pull request closed without merging**
