### PR TITLE
[protobuf] update to 3.21.9

### LINKED ISSUE #27493: [protobuf] update to 3.21.9
Library name: protobuf

New version number: 3.21.9

[Other information that may be useful (release notes, etc...)](https://github.com/protocolbuffers/protobuf/releases/tag/v21.9)

### PR DESCRIPTION
**Pull request by JonLiu1993**
Fix #27493 

Update protobuf to the latest version 3.21.9

Feature `zlib` tested successfully in the following triplet:
- x86-windows
- x64-windows
- x64-windows-static

### CODE REVIEW

**Review by MonicaLiu0311 — APPROVED** [review]

**Comment by olejniczak** [comment]
Would you please merge it into master?

**Comment by olejniczak** [comment]
@JonLiu1993 Thank you. Unfortunately it won't be merged.

**Comment by olejniczak** [comment]
I don't wish to urge, but is there any chance of fixing this pr? Thanks!

**Comment by JonLiu1993** [comment]
Duplicate of #28710

**Pull request closed without merging**
