### PR TITLE
[libpng] Disable build framework on APPLE

### PR DESCRIPTION
**Pull request by xiaozhuai**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [x] The "supports" clause reflects platforms that may be fixed by this new version.
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

This pr disable build framework on APPLE, like we've always done.

### CODE REVIEW

**Comment by xiaozhuai** [comment]
@WangWeiLin-MV @MonicaLiu0311 
Please review this PR, the CI fails on `kf5io` port on `x64-linux` triplet, but this has nothing to do with this PR.

**Comment by xiaozhuai** [comment]
@WangWeiLin-MV Would you please review this pr?

**Comment by dg0yt** [comment]
@xiaozhuai You can merge master. The kf5kio issue is fixed, and you need green CI anyways.

**Comment by xiaozhuai** [comment]
@dg0yt Thanks for informing

**Review by WangWeiLin-MV — APPROVED** [review]
The port usage tests pass with the following triplets:
* x64-osx
* x64-windows

**Review by vicroms — APPROVED** [review]

**Pull request merged**
