### PR TITLE
[boost-atomic] Add message for installing linux-headers on alpine linux

### LINKED ISSUE #23888: [boost-atomic] build failure on alpine linux due to missing headers
**Host Environment**
- OS: Alpine Linux 3.15.3
- Compiler: g++ (Alpine 10.3.1_git20211027) 10.3.1 20211027

**To Reproduce**

1. Install minimum set of system packages needed to run vcpkg on an alpine system.
2. git clone vckpg
3. set env variable VCPKG_FORCE_SYSTEM_BINARIES to 1
4. run bootstrap-vcpkg.sh (it pulls down the pre-build muslc binary of vcpkg)
5. Attempt to install boost-atomic

  > ./vcpkg install boost-atomic

vcpkg reports:
```
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: /usr/bin/cmake --build . --config Debug --target install -- -v -j9
    Working Directory: /src/vcpkg/buildtrees/boost-atomic/x64-linux-dbg
    See logs for more information:
      /src/vcpkg/buildtrees/boost-atomic/install-x64-linux-dbg-out.log
```

**Failure logs**
Output log shows root cause...
```
    "/usr/bin/c++"   -fPIC -g -m64 -pthread -O0 -fno-inline -Wall -g  -DBOOST_ALL_NO_LIB=1 -DBOOST_ATOMIC_SOURCE -DBOOST_ATOMIC_STATIC_LINK=1 -DBOOST_ATOMIC_USE_SSE2 -DBOOST_ATOMIC_USE_SSE41  -I"../include" -I"/src/vcpkg/installed/x64-linux/include" -I"../src"  -c -o "/src/vcpkg/buildtrees/boost-atomic/x64-linux-dbg/boost/build/599c3892010ad001b78ddcb47e1afb19/lock_pool.o" "../src/lock_pool.cpp"

In file included from ../include/boost/atomic/detail/platform.hpp:151,
                 from ../include/boost/atomic/detail/capabilities.hpp:18,
                 from ../include/boost/atomic/capabilities.hpp:18,
                 from ../src/lock_pool.cpp:33:
../include/boost/atomic/detail/futex.hpp:52:10: fatal error: linux/futex.h: No such file or directory
   52 | #include <linux/futex.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
```

**Additional context**
This problem can be resolved by adding a system package.

> apk add linux-headers

**Expectation**
The port should tell the user what system packages are missing, if any, in order to build the port.  For example, if you attempt to install openssl and the perl package is not installed, the user is presented with a cmake message indicating the package could not be found.

### PR DESCRIPTION
**Pull request by PhoebeHui**
Fixes https://github.com/microsoft/vcpkg/issues/23888

Boost-atomic requires linux-headers on alpine linux.
Update scripts/boost/generate-ports.ps1 to match the latest changes. I have confirmed the scrips locally.

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by strega-nil-ms** [comment]
Do we need to add this warning to every port that uses linux specific headers? it seems like it'd be kind of a lot...

**Comment by BillyONeal** [comment]
I don't mind this change but if we are expecting a lot of ports to be in this situation it should be a metaport (for example atlmfc)

**Comment by dg0yt** [comment]
I'm generally concerned about the scalablity of the messages: `n ports * m dependencies * p package managers`, and every "message" improvement forcing a rebuild on everyone else.

**Comment by strega-nil-ms** [comment]
Discussed at the meeting; we are of the opinion that this is not a good change right now; we might want it to be a node in the graph eventually, but this is uncommon enough (alpine is not a big enough distro, and `linux-headers` is such a common dependency) that we don't want a per-port solution here.

We may want to implement "scan the build logs and recognize the failure message" in the tool itself experimentally as a heuristic. If you're interested in implementing this @PhoebeHui, we can talk about it in the next monday meeting?

**Comment by PhoebeHui** [comment]
Sure, thank you for confirming this issue!

**Pull request closed without merging**
