### PR TITLE
[vtk] Change the runtime dir from tools to bin to fix DLL location

### LINKED ISSUE #5109: VTK dlls are placed in tools instead of bin
I found this problem on Windows 10, but it does apply to all OSs supported by vcpkg.

## Problem Description

In VTKs [`portfile.cmake`](../tree/master/ports/vtk/portfile.cmake) the cmake variable `VTK_INSTALL_RUNTIME_DIR` is set to `tools` instead of `bin`.
This results in the VTK DLLs being installed into `vcpkg/installed/x64-windows/tools` instead of `vcpkg/installed/x64-windows/bin`.
In turn, this means that [`applocal.ps1`](../tree/master/scripts/buildsystems/msbuild/applocal.ps1) on Windows will **silently** fail to copy those DLLs into the build folder after the build has finished.

## How to reproduce

1. Run `vcpkg install vtk:x64-windows` or any other target triplet on Windows or on any other OS.
2. Check `vcpkg/installed/x64-windows/bin` folder: No VTK DLLs.
3. Check `vcpkg/installed/x64-windows/tools` folder: There are the VTK DLLs.
4. Build any cmake project that depends on VTK using vcpkg's VTK linking dynamically: No DLLs will be placed in the build folder after building the project.

## Proposed Fix

My proposed fixes would include
1. Changing the `VTK_INSTALL_RUNTIME_DIR` to `bin`
2. Now, the build will fail because `vtkEncodeString-8.1.exe` and `vtkHashSource-8.1.exe` are placed in bin. Those tools are references in the VTK cmake targets file as supposed to be in `vcpkg/installed/x64-windows/tool/vtk/*.exe`, to where they need to get moved.
3. Improving `applocal.ps1` so that it doesn't fail silently if it cannot find dlls required to run the exe/use the dll.

The fix for the VTK package is in MR #5150.

### PR DESCRIPTION
**Pull request by at-2500**
Fix MR aims to fix #5109!

The issue is that currently for dynamic builds of VTK (mainly `x64-windows` and `x86-windows`) the DLLs are not placed in the `vcpkg/installed/<triplet>/bin` folder but into `vcpkg/installed/<triplet>/tools` which is wrong and breaks things.

The solution in this MR is to change the cmake variable `VTK_INSTALL_RUNTIME_DIR` from `tools` to `bin`. In order to place the executable tools `vtkEncodeString` and friends into the `tools/vtk` folder, it now is moved there manually. The file location is patched for the cmake target files afterwards.

In addition, it calls the function `vcpkg_copy_tool_dependencies` (which copies DLLs necessary to run the executables in the `tool/vtk` folder: only `vtksys-8.1.dll` currently).

I tested building vtk for `x64-windows` and `x64-osx`.

### CODE REVIEW

**Comment by at-2500** [comment]
Small update: The tools where not moved over on macOS (because there the executables don't end with .exe). Also, the call to `vcpkg_copy_pdbs` was there, I just didn't see it. Have to retest on Windows and see whether this breaks.

**Comment by njzhangyifei** [comment]
Same problem here. Would like to see this merged!

**Comment by vicroms** [comment]
I got a regression on `vtk-dicom` package after testing this PR.
I haven't had time to look at the issue myself.

**Comment by jasjuang** [comment]
@elmewo can you please take a look at this? We really need this PR to be merged.

**Comment by jasjuang** [comment]
@vicroms Can we merge this? This PR fixes so many popular libraries that depends on VTK, e.g `opencv`, `pcl` just to name a few. `vtk-dicom` is a lot less popular and the author who created the port for `vtk-dicom` on vcpkg doesn't seem to be responding. I think more people will benefit from having a functional `opencv`, `pcl` than a functional `vtk-dicom`.

**Comment by vicroms** [comment]
I'll look into this.

**Comment by vicroms** [comment]
Merged! Thanks for the PR!

**Pull request merged**
