### PR TITLE
Fixed port of quirc - patch did no longer apply / modified to fix build

### PR DESCRIPTION
**Pull request by Markus87**
* Quirc did no longer build for any triplet because the patch was for a previous version of quirc
* Modified the patch to get the windows triplets working again with the new version of quirc

### CODE REVIEW

**Comment by Markus87** [comment]
I dont know how this did not break any tests.
Are not all ports tested by CI? If so how to get a port into the automatic tests?

**Comment by JackBoosY** [comment]
@Markus87 Maybe the original error has been fixed by other means, and the patch is no longer needed.
So does this PR still exist?

**Comment by Markus87** [comment]
@JackBoosY Indeed the original patch would no longer be needed, but a new patch is required to make it build with msvc.
I just checked the latest code in the quirc repository and it seems fixed there, so updating quirc to the latest version should make the patch obsolete.

I will try to update quirc to the latest version. If that works can I use this pull request for updating the port or should I start a new one?

**Comment by JackBoosY** [comment]
@Markus87 Both patch or update are fine.

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
```
CMake Error at ports/quirc/portfile.cmake:24 (file):
  file COPY cannot find
  "/mnt/vcpkg-ci/buildtrees/quirc/src/b114181c40-f1e71e0d5b.clean/license":
  No such file or directory.
Call Stack (most recent call first):
  scripts/ports.cmake:136 (include)
```

Will fix later.

**Comment by JackBoosY** [comment]
LGTM.

**Comment by vicroms** [comment]
Thanks for the PR!

**Pull request merged**
