### PR TITLE
[sciter] Update to 4.4.1.5

### PR DESCRIPTION
**Pull request by pravic**
* Update Sciter to the latest version
* Fix the executable bit for the app bundles on OSX

### CODE REVIEW

**Comment by pravic** [comment]
>          C:\vsts\_work\1\s\buildtrees\osg\src\raph-3.6.4-9780889fab\examples\osgmovie\osgmovie.cpp(694,10): error C1083:  Cannot open include file: 'SDL/SDL.h': No such file or directory 

I guess, it is not related to this PR.

**Comment by pravic** [comment]
cc @ras0219-msft - This PR looks forgotten, could we merge this?

**Comment by PhoebeHui** [comment]
@dan-shaw, could you help merge this PR?

**Comment by pravic** [comment]
Thanks!

**Pull request merged**
