### PR TITLE
Add zlib support for curl

### PR DESCRIPTION
**Pull request by matttyson**
Allow curl to be built with zlib compression

### CODE REVIEW

**Comment by sanxiyn** [comment]
Shouldn't this delete `Build-Depends: zlib` in line 3 of CONTROL?

**Comment by matttyson** [comment]
Yes you are correct.  I did not even notice that it was there.

**Comment by pravic** [comment]
Then this PR should be closed?

**Comment by matttyson** [comment]
Sorry, let me start again. do you mean closed without merging or merged and closed?  I've fixed the issue with line 3 of CONTROL reported by @sanxiyn .

So this should be ready to be merged now, unless there's other issues?

**Comment by pravic** [comment]
Well, in this PR you [removed](https://github.com/Microsoft/vcpkg/pull/3737/files#diff-94021a72c668aa79a59c2d9fc7bb6a90L3) the direct ZLIB dependency and made it [optional](https://github.com/Microsoft/vcpkg/pull/3737/files#diff-94021a72c668aa79a59c2d9fc7bb6a90R25). Also you've set the `CURL_ZLIB`.

Whereas you are claiming that:

> without it there's no way to build curl with zlib

I the the following:

> **$ curl --version**
curl 7.61.0-DEV (Windows) libcurl/7.61.0-DEV OpenSSL/1.0.2o zlib/1.2.11
Release-Date: [unreleased]
Protocols: http https smb smbs
Features: AsynchDNS IPv6 Largefile NTLM SSL **libz** HTTPS-proxy

So, it does always support zlib. 

May be you meant the opposite, building curl without zlib?

**Comment by matttyson** [comment]
Hm.  When I first built curl with vcpkg, it gave me a curl.exe without zlib, which is why I filed this pull request.

I've downloaded a clean vcpkg tree and rebult curl and it gives me a curl with zlib.  Hm.  Hell If I know what happened the first time.

> May be you meant the opposite, building curl without zlib?

Nope

**Pull request closed without merging**
