### PR TITLE
[NCCL] Fix usage, add wrapper and install Find module file

### LINKED ISSUE #21975: NCCL installation in vcpkg
I am getting the following error and i am not able to fix it
```
CMake Error at /home/cr/Desktop/vcpkg/scripts/buildsystems/vcpkg.cmake:788 (_find_package):
Could not find a package configuration file provided by "nccl" with any of
the following names:

ncclConfig.cmake
nccl-config.cmake
Add the installation prefix of "nccl" to CMAKE_PREFIX_PATH or set
"nccl_DIR" to a directory containing one of the above files. If "nccl"
provides a separate development package or SDK, be sure it has been
installed.
```
nccl is installed in /usr/local/cuda-11.5/lib64 libnccl.so libnccl.so.2 libnccl.so.2.11.4 libnccl_static.a libvncclient.so.0 libvncclient.so.0.0.0

vcpkg install of nccl returns
```
Computing installation plan...
The following packages are already installed:
nccl[core]:x64-linux -> 2.4.6#1
Package nccl:x64-linux is already installed
Restored 0 packages from /home/cr/.cache/vcpkg/archives in 726 ns. Use --debug to see more details.

Total elapsed time: 10.37 us

The package nccl provides CMake variables:

find_package(NCCL REQUIRED)
target_link_libraries(main PRIVATE ${NCCL_LIBRARIES})
target_include_directories(main PRIVATE ${NCCL_INCLUDE_DIRS})
```
I have inserted the above three lines in my CMakeLists.txt
```cmake
cmake_minimum_required(VERSION 3.10)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

SET(NCCL /usr/local/cuda-11.5/lib64/)

project(myProject)

add_executable(myProject project.cpp)

find_package(ArrayFire CONFIG REQUIRED)
target_link_libraries(myProject PRIVATE ArrayFire::af ArrayFire::afcpu ArrayFire::afcuda)

find_package(cereal CONFIG REQUIRED)
target_link_libraries(myProject PRIVATE cereal)

find_package(nccl CONFIG REQUIRED)
target_link_libraries(myProject PRIVATE ${NCCL_LIBRARIES})
target_include_directories(myProject PRIVATE ${NCCL_INCLUDE_DIRS})

target_link_libraries(myProject PRIVATE iomp5 pthread m dl)

find_package(flashlight CONFIG REQUIRED)
target_link_libraries(myProject PRIVATE flashlight::flashlight)
```
but no success.

### PR DESCRIPTION
**Pull request by FrankXie05**
**Describe the pull request**

- #### What does your PR fix?  
  Fixes #21975 

Application FindNCCL.cmake and vcpk-cmake-wrapper.cmake to solve the error

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
@avi-champ Can you please test this PR?

Thanks.

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
Ping @FrankXie05

**Comment by PhoebeHui** [comment]
@FrankXie05, could you merge master?

**Comment by FrankXie05** [comment]
@PhoebeHui Now I have merged the master

**Comment by strega-nil-ms** [comment]
Thanks!

**Pull request merged**
