### PR TITLE
[libiconv] fix libiconv targets

### PR DESCRIPTION
**Pull request by seanwarren**
This PR replaces #5464.

- Ensures that libiconv only creates targets when they do not exist. This fixes an error which occurs when a target depending on libiconv is included before libiconv itself in a third package.
- Fixes required includes on windows and linux and resulting regressions

### CODE REVIEW

**Comment by seanwarren** [comment]
Hello, could you let me know what is failing please

**Comment by vicroms** [comment]
Regressions in `vtk:x64-osx` and `collada-dom:x64-linux`.

| triplet            | port        | master | test | notes          |
| ------------------ | ----------- | ------ | ---- | -------------- |
| x64-windows        |             |        |      | No Change      |
| x64-windows-static |             |        |      | No Change      |
| x64-osx            |             |        |      |
|                    | collada-dom | Fail   | Pass |
|                    | vtk         | Pass   | Fail | **Regression** |
|                    | pcl         | Pass   | Skip |
|                    | vtk-dicom   | Pass   | Skip |
| arm64-windows      |             |        |      | No Change      |
| x86-windows        |             |        |      | No Change      |
| x64-linux          |             |        |      |
|                    | collada-dom | Pass   | Fail | **Regression** |
| x64-uwp            |             |        |      |
|                    | freetype-gl | Skip   | Fail |
|                    | pangolin    | Skip   | Fail |
|                    | opencsg     | Skip   | Fail |
|                    | glew        | Fail   | Pass |
|                    | pixel       | Skip   | Fail |
| arm-uwp            |             |        |      | No Change      |

**Comment by seanwarren** [comment]
@vicroms thanks for the update. I've successfully build `vtk:x64-osx`, please could you send me the log for this build? I don't think the  `collada-dom:x64-linux` failure is anything to do with this PR - it seems to fail intermittently

**Comment by Rastaban** [comment]
Here is the osx failure:
[install-x64-osx-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2989433/install-x64-osx-dbg-out.log)

I have also checked in a fix to help with the stability of collada-dom, so hopefully it won't continue to show up.

**Comment by seanwarren** [comment]
@Rastaban - the `vtk:x64-osx` build is failing with the following error (wrapped for display)
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/
Developer/SDKs/MacOSX10.14.sdk/usr/include/hfs/hfs_format.h:794:2: 
error: unknown type name 'uuid_string_t'; did you mean 'io_string_t'?
        uuid_string_t   ext_jnl_uuid;
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/
Developer/SDKs/MacOSX10.14.sdk/usr/include/device/device_types.h:89:16: 
note: 'io_string_t' declared here
typedef char                    io_string_t[512];
```
This isn't happening on my mac (macOS 10.14 with Xcode 10.1) which makes it a bit difficult to diagnose. A bit of googling shows up similar errors in the past, e.g https://github.com/Homebrew/legacy-homebrew/issues/32587. It seems like this might occur when there is a stray `uuid.h` on the include path. Would you be able to check and see if this is the case on the CI server please?

**Comment by seanwarren** [comment]
I think this PR is cursed :) I'm going to try a different approach to fix #5454

**Comment by vicroms** [comment]
I have had the same issue with the stray uuid.h on MacOS in our CI builds in the past. 

Can't remember how I fixed it :(

I'm away from the office this week, so I don't have access to a Mac. But I can take a look when I get back next week.

**Comment by seanwarren** [comment]
OK cool thanks - it would be good to know in the longer term. For the moment I think this PR is not required.

**Comment by vicroms** [comment]
After reviewing the CI build logs, there's a package `libuuid` that is getting installed during the CI test. This package ships its own `uuid.h` file.

```
Starting package 44/160: libuuid:x64-osx
Building package libuuid[core]:x64-osx... 
Using cached binary package: /Users/philc/vcpkg/myagent/_work/2/s/archives/fe/fe02e23c849b8a577e40429ee988482967bbb6a0.zip
```

Making a whitespace change to `vtk` would rebuild it, without installing `libuuid` (unless there's a hidden dependency for `libuuid` somewhere).

I made a quick search, and found that the following packages depend on `libuuid`, but going through `vtk`'s dependency graph is a hard endeavor.

The easiest fix would be to disallow `libuuid` for anything except Linux (#5844)

```
ports\antlr4\CONTROL:4:Build-Depends: libuuid (!uwp&!windows&!osx)
ports\azure-storage-cpp\CONTROL:3:Build-Depends: cpprestsdk[core], atlmfc (windows), boost-log (!windows&!uwp),boost-locale (!windows&!uwp), libxml2 (!windows&!uwp), libuuid (!windows&!uwp)
ports\crossguid\CONTROL:3:Build-Depends: libuuid (!windows&!uwp&!osx&!android)
ports\xeus\CONTROL:4:Build-Depends: cppzmq, cryptopp, libuuid (linux), nlohmann-json, xtl, zeromq
```

**Pull request closed without merging**
