### PR TITLE
[libdisasm] Support uwp

### LINKED ISSUE #21237: [libdisasm] build failure caused by CMake build failure
**Host Environment**
- OS: Windows
- Compiler: revision

**To Reproduce**
`./vcpkg install breakpad:x64-uwp`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
```
PS C:\workspace\xxxx\xxxx\xxxx> vcpkg install breakpad:x64-uwp
Computing installation plan...
warning: vcpkg appears to be in a Visual Studio prompt targeting x86 but is installing packages for x64-uwp. Consider using --triplet x86-windows or --triplet x86-uwp.
The following packages will be built and installed:
    breakpad[core]:x64-uwp -> 2020-09-14#3
  * libdisasm[core]:x64-uwp -> 0.23#8
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-uwp...
Restored 0 packages from C:\Users\xxxx\AppData\Local\vcpkg\archives in 316 us. Use --debug to see more details.
Starting package 1/2: libdisasm:x64-uwp
Building package libdisasm[core]:x64-uwp...
-- Note: libdisasm only supports static library linkage. Building static library.
-- Using cached libdisasm-0.23.tar.gz.
-- Cleaning sources at C:/workspace/vcpkg/vcpkg/buildtrees/libdisasm/src/29eecfbfd8-87a041f03c.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/workspace/vcpkg/vcpkg/downloads/libdisasm-0.23.tar.gz
-- Applying patch sizeofvoid.patch
-- Using source at C:/workspace/vcpkg/vcpkg/buildtrees/libdisasm/src/29eecfbfd8-87a041f03c.clean
-- Found external ninja('1.10.2').
-- Configuring x64-uwp
-- Building x64-uwp-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: C:/workspace/vcpkg/vcpkg/downloads/tools/cmake-3.21.1-windows/cmake-3.21.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /m
    Working Directory: C:/workspace/vcpkg/vcpkg/buildtrees/libdisasm/x64-uwp-dbg
    See logs for more information:
      C:\workspace\vcpkg\vcpkg\buildtrees\libdisasm\install-x64-uwp-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg
```
-Please attach any additional failure logs mentioned in the console output.
As mentioned in above debug log, details here: [install-x64-uwp-dbg-out.log](https://raw.githubusercontent.com/Magicicesea/GithubIssueFolder/master/vcpkg/1106Breakpad/install-x64-uwp-dbg-out.log)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.
Will try use previous version of vcpkg to see whether that work, will update here.

### PR DESCRIPTION
**Pull request by JackBoosY**
Add `/wd4996` to support uwp.

Fixes #21237.

### CODE REVIEW

**Comment by JackBoosY** [comment]
breakpad should not support uwp officially, see the issues in upstream: https://groups.google.com/g/google-breakpad-discuss/c/596WsrC4pLg/m/_ET2aiBJAQAJ.

**Review by LilyWangLL — APPROVED** [review]

**Review by BillyONeal — CHANGES_REQUESTED** [review]
Generally speaking we should not silence 4996; that warning is the only warning libraries have to tell the user something and it's used for both relatively inane things like this but also things like "we know that function doesn't exist on UWP so even if it compiles it will be rejected by the store".

Can we disable `/WX` or set `_CRT_SECURE_NO_WARNINGS` instead?

**Comment by JackBoosY** [comment]
Ah I forgot `_CRT_SECURE_NO_WARNINGS`, thanks for mentioned me.

**Comment by BillyONeal** [comment]
Awesome, thanks for the fix :D

**Pull request merged**
