### PR TITLE
[glog] Disable tests

### PR DESCRIPTION
**Pull request by huangqinjin**

### CODE REVIEW

**Review by NancyLi1013 — COMMENTED** [review]
`include(vcpkg_common_functions)` is no longer needed.
Could you please remove this line?

**Comment by huangqinjin** [comment]
@NancyLi1013 Done.

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
LGTM, thanks for this PR @huangqinjin .

**Comment by strega-nil** [comment]
Cool, thanks @huangqinjin :)

**Pull request merged**
