### PR TITLE
[nlohmann-json] Added cmake targets

### PR DESCRIPTION
**Pull request by SuperWig**
I *believe* I've fixed the errors made in https://github.com/Microsoft/vcpkg/pull/5095

### CODE REVIEW

**Comment by myd7349** [comment]
@ras0219-msft Is it possible to rename package name to `nlohmann_json`. This way, we can use `find_package(nlohmann_json ...)`(the official way) instead of `find_package(nlohmann-json  ...)`.

**Comment by ras0219-msft** [comment]
Ok, `find_package(nlohmann_json)` should now work :) Thanks for letting me know the other users!

**Comment by SuperWig** [comment]
Oh I assumed it had to go in the same package name directory hence the renaming. I guess that's not the case so I removed that line.

**Comment by evpobr** [comment]
Why cloning from GitHub? This repo is VERY huge, tests or something.

**Comment by ras0219-msft** [comment]
Wow, yeah, over 100MB compressed is pretty terrible. If it was only 10 or so I'd still prefer the archive but... :/

**Comment by ras0219-msft** [comment]
Thanks for the PR!

**Comment by ras0219-msft** [comment]
Thanks for the PR!

**Pull request merged**
