### PR TITLE
Add package Fast-RTPS and enable modules for python

### PR DESCRIPTION
**Pull request by cmpute**
I'm trying to port ros2 to vcpkg, but the building tool `ament` used by ros2 is not that configurable to combine with vcpkg. However, I would like to add related functions to vcpkg.

Modifications:
1. Add package Fast-RTPS
2. Add function `vcpkg_acquire_python`, which helps acquiring python modules. Some big projects use many python scripts in their building procedure, and this function could help if the python scripts need additional python packages.
3. Fix typo in `vlpp`

### CODE REVIEW

**Comment by traversaro** [comment]
This PR solves https://github.com/Microsoft/vcpkg/issues/434 .

**Comment by traversaro** [comment]
Thanks @cmpute for working on this! 

I did not went through all the PR, but I have one suggestion: this port is currently using the fastrtps build system to download and install [fastcdr](https://github.com/eProsima/Fast-CDR) . As there are some projects that depend only on fastcdr, it would be convenient to have a fastcdr vcpkg, that is a dependency for the fastrtps port.

**Comment by traversaro** [comment]
>  building tool ament used by ros2 is not that configurable to combine with vcpkg. However, I would like to add related functions to vcpkg.

Probably it is not directly related to this PR, but if you need to expose vcpkg-installed libraries in a superbuild-like tool (i.e. a tool that configures, builds and installs several different project automatically, such as [catkin](http://wiki.ros.org/catkin), [ament](http://design.ros2.org/articles/ament.html) or [YCM](http://robotology.github.io/ycm/gh-pages/master/index.html#superbuild) ) you indeed cannot use directly the vcpkg toolchain, as these tools typically do not have the configuration support for specifying a CMake toolchain for all their CMake-based subprojects. For YCM (the CMake-based superbuild tool that we used  in our organization) I just opened an issue on this: https://github.com/robotology/ycm/issues/129 .

My current workaround/alternative solution is to manually set the environment variables that are needed to make sure that the libraries installed by vcpkg are found. For the packages I am working with, it is sufficient to add `${VCPKG_ROOT}/installed/x64-windows` and `${VCPKG_ROOT}/installed/x64-windows/debug` to `CMAKE_PREFIX_PATH` and `${VCPKG_ROOT}/installed/x64-windows/tools` to `CMAKE_PROGRAM_PATH`. Clearly, if you are not using the vcpkg toolchain, you are loosing the nice ["copy all dll when install executables"](https://github.com/Microsoft/vcpkg/blob/master/scripts/buildsystems/vcpkg.cmake#L147) feature, and so to run you programs you either need to copy the dll in the executables directories with other means or add `${VCPKG_ROOT}/installed/x64-windows/bin` and `${VCPKG_ROOT}/installed/x64-windows/debug/bin` to `PATH`. **Note: modifying the `PATH` can create problem of having multiple incompatible DLL in the path, so the [usual disclaimers[(https://en.wikipedia.org/wiki/DLL_Hell) apply**.  See https://github.com/robotology/robotology-superbuild#vcpkg for more details.

**Comment by cmpute** [comment]
>  it would be convenient to have a fastcdr vcpkg, that is a dependency for the fastrtps port.

Actually, in my build history, fast-cdr is not downloaded nor even used. Fast-RTPS is successfully built without fast-cdr. Is fast-cdr an essential dependency for fast-rtps? I haven't actually used both libraries.

> I just discovered that ament actually has support for specifying a CMAKE_TOOLCHAIN_FILE for each subproject, see https://github.com/ros2-for-arm/ros2/wiki/ROS2-on-arm-architecture#trigger-a-build ,

Thanks for pointing out that. Indeed ament has some configuration entries for cmake, but I did not notice that toolchain is supported. I'll have a try.

**Comment by traversaro** [comment]
> Actually, in my build history, fast-cdr is not downloaded nor even used. Fast-RTPS is successfully built without fast-cdr. Is fast-cdr an essential dependency for fast-rtps? I haven't actually used both libraries.

You are actually right, fastcdr is used by tests and examples, but in the default configuration is not used at all, so it is not necessary. I was confused by the `EPROSIMA_BUILD` variable behavior.

**Comment by cmpute** [comment]
I tried to set the toolchain file, and it turns out that I was stuck because ament only support VS2015 x64 and VS2017 x64 build now. `-G` to specify generator is not supported by ament. Besides, I met another problem when build `ros2:x64-windows`:
```
CMake Error at D:/vcpkg/scripts/buildsystems/vcpkg.cmake:262 (_find_package):
  Syntax error in cmake code at

    D:/vcpkg/scripts/buildsystems/vcpkg.cmake:262

  when parsing string

    opensplice;NO_MODULE;COMPONENTS;CXX;PATHS;D:\vcpkg\packages\ros2_x64-windows;/usr;/usr/local

  Invalid character escape '\v'.
```
I don't know if it's proper to add escaping in the toolchain file, but I cannot change the arguments fed into `find_package`.

**Comment by traversaro** [comment]
Cool @cmpute . 
I think we are going a bit off topic here (I am actually the one that started the OT to be honest : ) ).
Perhaps we could open a separate issue on vcpkg to discuss using vcpkg dependencies for building ros2 , what do you think? You also may find this discussion interesting: https://github.com/robotology-playground/vcpkg-binary-installer-generator/issues/2 .

**Comment by cmpute** [comment]
@traversaro Yep, I'll create another PR when ready.

**Comment by traversaro** [comment]
Given that preparing a port of ros2 for vcpkg is indeed a complex task, perhaps opening an issue to start discussions even before preparing any PR may be useful. : ) 

For example, I saw from the commits in this PR that you are trying to prepare a monolithic port for all ros2, but given that ros2 is actually a combination of several different packages (of which several are already in vcpkg, such as poco, urdfdom, console-bridge), perhaps generating a port for each repository or for each cmake/ament package could be more convenient. See how boost ports are generated in https://github.com/Microsoft/vcpkg/blob/master/ports/boost-vcpkg-helpers/generate-ports.ps1 for an interesting example of this.

**Comment by cmpute** [comment]
@traversaro I actually have considered this, however I thought it would be easier to build all of them first since ros2 use another tool called `vcstool` to manage multiple repositories, which is not much configurable as well. I would try to build them all, since nearly all of those packages are core packages, and then try to figure out whether to modularize them or make some of the components become `features`

**Comment by traversaro** [comment]
Exactly this is the kind of the discussions it will be convenient to have on a "Add ros2" issue. : )

**Comment by cmpute** [comment]
I don't have much time working on this now. After trying again for several times, I found there's a lot's of dependencies of packages in ros2 is fixed to be built inside, the packages built by vcpkg can be utilized by no way! (for example `rviz_ogre_vendor`.) The ament tool is quite sealed now and I might put aside the porting for a while.

**Comment by traversaro** [comment]
As a reference, an alternative solution would be to modify the bloom release tool to generate automatically vcpkg ports for ros2 packages, as discussed (but not implemented) in https://github.com/ros-infrastructure/bloom/issues/254 for homebrew.

**Comment by cmpute** [comment]
No problem~

**Pull request merged**
