### PR TITLE
Small version bump to redshell port

### PR DESCRIPTION
**Pull request by yintothayang**
Bump version of `redshell` port.

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for making this PR! Could you also update the "built-using" field in the CONTROL file so we can keep track?

**Comment by yintothayang** [comment]
Just took a look, this new version was built using the exact same libs, as well as the same versions of those libs. No changes. 

Let me know if you would like me to change anything else. 
Thanks for the quick response!

**Comment by ras0219-msft** [comment]
I know that in the case of `cpprestsdk` there were several memory leaks and crashes fixed in the latest (`2.10`). In `openssl`, two releases have gone by (we're on `1.0.2m` now) which has several security fixes associated with it.

I don't think this blocks the update if you do not want those fixes, but I think your users would appreciate it :).

**Comment by yintothayang** [comment]
Rebuilt and updated deps.

Thanks for letting me know about that!

**Comment by alexkaratarakis** [comment]
Thanks!

**Pull request merged**
