### PR TITLE
[qt-advanced-docking-system] update and use qt6

### PR DESCRIPTION
**Pull request by Neumann-A**
people wanting the qt5 version should use an overlay :P

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]
LGTM.

**Comment by BillyONeal** [comment]
Given that qt5 no longer has OSS support I believe we should start accepting changes like this but given that it is a change in a team-wide decision I'm not merging this just yet; will be discussing later today though with @strega-nil @ras0219 @vicroms and @dan-shaw

**Review by BillyONeal — APPROVED** [review]

**Review by vicroms — APPROVED** [review]

**Comment by BillyONeal** [comment]
In discussion yesterday @ras0219 / @ras0219-msft wants to see a more coordinated mechanism to change the qt major version for and took point to record that here, I poked him.

**Comment by Neumann-A** [comment]
Ah finally. Are XOR features coming?

**Comment by BillyONeal** [comment]
> Ah finally. Are XOR features coming?

I think Robert wanted some coordinated way for users to overlay to select which version all at once but I'm not positive. I'm notifying him every day to look but I think he's OOF until the new year. Ditto on the other PR https://github.com/microsoft/vcpkg/pull/22012

**Comment by strega-nil-ms** [comment]
Thanks!

**Comment by strega-nil-ms** [comment]
gosh dangit, I accidentally merged this since I forgot about the discussion about updating qt5 to qt6; marking as depends:vcpkg-team to avoid this being `info:reviewed` without any depends tags

**Comment by m-kuhn** [comment]
> In discussion yesterday @ras0219 / @ras0219-msft wants to see a more coordinated mechanism to change the qt major version for and took point to record that here, I poked him.

Has there any progress been made regarding this migration path?

**Pull request merged**
