### PR TITLE
[gklib,metis,parmetis] Update sources for metis et al. to GitHub

### LINKED ISSUE #25764: [metis] upstream is gone
See also https://github.com/microsoft/vcpkg/issues/25609

image

I looked at what's in that repo suggested as an alternative ( https://github.com/KarypisLab/METIS ) vs. what's in our cached copy of that release file `metis-5.1.0.tar.gz` and there seem to be meaningful differences. @karypis @BarclayII @zheng-da @pvc1989 can you either:

(1) let us know where we should look for `metis-5.1.0.tar.gz` now, or
(2) let us know what we should be doing instead (e.g. updating our `metis` port to something more recent than 2013?)

### PR DESCRIPTION
**Pull request by BillyONeal**
Updates sources for metis and parmetis to GitHub. Also merges all patches together and makes things consistent in how CMake targets are exported.

Resolves https://github.com/microsoft/vcpkg/issues/25764

Competes with https://github.com/microsoft/vcpkg/pull/25953

Tested that parmetis works like this:

image

### CODE REVIEW

**Comment by surumed** [comment]
I solved.#25970

I changed the URL from "http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/metis-${METIS_VERSION}.tar.gz" to "https://www.nektar.info/thirdparty/metis-${METIS_VERSION}.tar.gz"
image

Thank you!

**Comment by kysucix** [comment]
Great thanks @BillyONeal !

**Comment by brosaplanella** [comment]
Any updates on this or on #25953? Our latest release depends on this.

**Comment by BillyONeal** [comment]
> Any updates on this or on #25953? Our latest release depends on this.

Sorry, I've been out on vacation since Thursday of last week; I'll see if I can fix the failures today but can't promise it will land today.

**Comment by BillyONeal** [comment]
@ras0219 reviewed this over my shoulder

**Comment by ahojnnes** [comment]
Thanks @BillyONeal !

**Pull request merged**
