### PR TITLE
Add AOM

### PR DESCRIPTION
**Pull request by HappySeaFox**
**Describe the pull request**

Add AV1 codec library

- #### What does your PR fix?  
\-

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  

Triplets: Everything except UWP and ARM.

CI baseline is not updated.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  

Yes.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  

Yes.

### CODE REVIEW

**Comment by Hoikas** [comment]
It looks like this PR contains some commits on the sail port in addition to the aom port?

**Comment by smoked-herring** [comment]
@Hoikas Previously I added `sail`, and it's in `vcpkg` master already. It looks like a `github` peculiarity. It shows all my commits in my `vcpkg` fork even those already in upstream. The list of changed files looks correct though.

**Comment by smoked-herring** [comment]
I'll make a new PR just not to confuse people with sail-related commits.

**Comment by smoked-herring** [comment]
See https://github.com/microsoft/vcpkg/pull/17332

**Pull request closed without merging**
