### PR TITLE
[pkgconf] enable search for system libs on linux

### PR DESCRIPTION
**Pull request by Neumann-A**
This is required to make cmake 3.22 work since it will pickup `pkgconf` from vcpkg. As such `pkgconf` from vcpkg needs to be able to pickup system dependencies which it only can if the default paths are correctly set. Unfortunately I don't know of a way to get the correct paths from the system's `pkg-config` (maybe the paths can be dumped somehow? String literals in the binary?)

This also belongs in the category that the host build requires information for the target to correctly set pkgconf up. 

@ras0219: Maybe you have a better solution? 

(maybe build it from the contents of  `/etc/ld.so.conf` `/etc/ld.so.conf.d/*.conf` ?)

### CODE REVIEW

**Comment by Neumann-A** [comment]
@JackBoosY Feel free to propose a license here. I would probably go with `none` or `custom`. It is like MIT but not really MIT

**Comment by ras0219-msft** [comment]
Since these paths are target specific (e.g. a sysroot when cross compiling), it seems like we must not bake them in at compile time and instead they must be dynamically added to `PKG_CONFIG_PATH` within the context of the consuming triplet.

What do you mean specifically by

>This is required to make cmake 3.22 work since it will pickup pkgconf from vcpkg.

Do you mean "If we want CMake to be able to use pkgconf from vcpkg, it needs system paths"?


Another potential approach would be to generate script wrappers in the target triplets that prepend/append the appropriate values to `PKG_CONFIG_PATH` before forwarding to the true executable.

**Comment by Neumann-A** [comment]
> Do you mean "If we want CMake to be able to use pkgconf from vcpkg, it needs system paths"?

If we want to use cmake 3.22 we need to have pkgconf behave like the system pkg-config because otherwise ports will fail sporadically since `vcpkg.cmake` is setup in such a way that `find_program(PKGCONFIG_EXECUTABLE NAMES pkg-config pkgconf NAMES_PER_DIR)` will **preferably** find `pkgconf` within vcpkg due to search order. 

> Or are you saying that today CMake 3.22 is broken because it is erroneously finding pkgconf
 you're proposing we fix it by making pkgconf work?

I am proposing to make it work like the system one. For the cross-compiling case the users need to define the correct non-system behavior anyway.
Also it is not erroneously finding pkgconf it is finding pkgconf since I added that to cmake ;) The problem is just that our pkgconf currently does not behave like the system version. (due to missing proper default search paths.)

**Comment by Neumann-A** [comment]
So possible way to determine system defaults is to run
```
neumann@Iluinrandir:~$ strings -d /usr/bin/pkg-config | grep /include
/usr/include
neumann@Iluinrandir:~$ strings -d /usr/bin/pkg-config | grep /lib
/lib64/ld-linux-x86-64.so.2
/lib:/lib/i386-linux-gnu:/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnux32:/lib32:/libx32:/usr/lib:/usr/lib/i386-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnux32:/usr/lib32:/usr/libx32
/usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig
```

That would be 
```
SYSTEM_INCLUDEDIR
(ignore)
SYSTEM_LIBDIRS
DEFAULT_PKGCONFIG_SEARCH_PATHS
```

**Comment by dg0yt** [comment]
~~~
$pkg-config --debug 2>&1 | grep 'directory #'
Cannot open directory #1 '/usr/local/lib/x86_64-linux-gnu/pkgconfig' in package search path: No such file or directory
Scanning directory #2 '/usr/local/lib/pkgconfig'
Cannot open directory #3 '/usr/local/share/pkgconfig' in package search path: No such file or directory
Scanning directory #4 '/usr/lib/x86_64-linux-gnu/pkgconfig'
Scanning directory #5 '/usr/lib/pkgconfig'
Scanning directory #6 '/usr/share/pkgconfig'
~~~

**Comment by Neumann-A** [comment]
After thinking about it I would like to have a solution which does not require the system pkg-config.

**Comment by dg0yt** [comment]
It is probably enough to use reasonable system paths plus user environment variable.

**Comment by JackBoosY** [comment]
> It is probably enough to use reasonable system paths plus user environment variable.

The user may not installed pkgconfig yet.

**Comment by dg0yt** [comment]
> > It is probably enough to use reasonable system paths plus user environment variable.
> 
> The user may not installed pkgconfig yet.

No problem if it is not called.

**Comment by ras0219-msft** [comment]
>https://github.com/microsoft/vcpkg/pull/23010#issuecomment-1034974243

Finally! This particular issue has been very elusive to repro. Thanks :)

--

I 100% agree that we need a solution that doesn't rely on a system pkg-config (since that kinda defeats the point in a lot of ways :)). However, I think it's important that we offer users the option to control the results. Looking at the man page[1], I see that

>PKG_CONFIG_LIBDIR
>Replaces the default pkg-config search directory.

So we should ensure that our solution respects that. For example, if we went with a script-wrapper solution like I mentioned above, the script wrapper should _not_ append the system paths if this env was defined.

I'm additionally not familiar enough with current Linux to know how we should handle `/lib`, `/lib64`, `/usr/lib`, and `/usr/lib64`. There are also other systems like NixOS or Haiku that might have more challenging configurations. I note that the documentation says "By default, pkg-config looks in the directory _prefix_/lib/pkgconfig", so perhaps we should do something like:

1. Search for a pkg-config executable
2. If found, use `$pkgconfig_exe/../lib/pkgconfig`. If not found, assume `/usr/lib/pkgconfig` if host is linux and ??? if host is osx.

Perhaps there's something more clever that would be reasonable, like transforming all elements of `$PATH` as `../lib/pkgconfig`

[1]: https://linux.die.net/man/1/pkg-config

**Comment by Neumann-A** [comment]
> Finally! This particular issue has been very elusive to repro. Thanks :)

I think there is an error in the CMakeLists.txt using an absolute path in the installation. Cmake tries to `rm -r -f  /lib/Graclus/libgraclus.a`

> So we should ensure that our solution respects that.

environment variable `PKG_CONFIG_LIBDIR` will be respect no matter what we set as the defaults. pkgconf has additional a personality.d file which can also be use to define some defaults. 

> Search for a pkg-config executable

this again requires system pkg-config

OpenSuse defaults:
libpkgconf:
```
/usr/include
/usr/lib64
/usr/lib64/pkgconfig:/usr/share/pkgconfig
/usr/share/pkgconfig/personality.d:/etc/pkgconfig/personality.d
```
pkg-config
```
/usr/include
/usr/lib64:/lib64:/usr/lib:/lib
/usr/local/lib64/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib64/pkgconfig:/usr/share/pkgconfig:/opt/kde3/lib64/pkgconfig
```
debian is like ubuntu
alpine (pkgconf):
```
/usr/include
/usr/lib
/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig
/usr/share/pkgconfig/personality.d:/etc/pkgconfig/personality.d
```

(That are the 3 linux distros I could find in WSL)

**Comment by JackBoosY** [comment]
> ```
> duplicate symbol '_METIS_NodeND' in:
>     lib/Graclus/libgraclus.a(ometis.c.o)
>     /Users/vagrant/Data/installed/x64-osx/debug/lib/libmetis.a(ometis.c.o)
> ld: 1 duplicate symbol for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ninja: build stopped: subcommand failed.
> ```

Will be fixed in another PR.

**Comment by Neumann-A** [comment]
@ras0219-msft: hmm is the type of linux system part of the binary hash? If not this will definitely break binary caching since the output result will depend on system introspection not considered in the binary hash.

**Comment by Neumann-A** [comment]
@ras0219-msft why did you close this? This is not about colmap.

**Comment by JackBoosY** [comment]
```
ninja: error: 'D:/installed/x64-windows-static/debug/lib/openblas.lib', needed by 'src/exe/colmap.exe', missing and no known rule to make it
```

**Comment by Neumann-A** [comment]
@JackBoosY That is a bug in the dependency chain of colmap somewhere. Something is pulling in openblas if it is installed. Basically the repro is to first install openblas than everything colmap needs than deinstall openblas and retry to install colmap.

**Review by strega-nil-ms — APPROVED** [review]

**Comment by strega-nil-ms** [comment]
Thanks for your patience everyone!

**Pull request merged**
