### PR TITLE
[SDL2] update to 2.28.1

### LINKED ISSUE #32186: [SDL2] update to 2.28.0
### Library name

SDL2

### New version number

2.28.0

### Other information that may be useful (release notes, etc...)

Released on June 20th 2023
Release notes: https://github.com/libsdl-org/SDL/releases/tag/release-2.28.0

### PR DESCRIPTION
**Pull request by JonLiu1993**
Fixes #32186 

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

Feature `samplerate`,`vulkan` tested successfully in the following triplrt:

- x86-windows
- x64-windows
- x64-windows-static

All featrue tested successfully in the x64-linux triplet.

### CODE REVIEW

**Comment by tomconder** [comment]
Any progress? A quick look at the logs showed a build error in the wxwidgets dep for linux.

**Comment by tsunamistate** [comment]
Any chance, that the port will be updated?

**Comment by tomconder** [comment]
A new update, [SDL2 2.28.2](https://github.com/libsdl-org/SDL/releases/tag/release-2.28.2) has been released. Has there been any progress?

**Comment by lsl330** [comment]
hope update sdl2 2.28.2

**Comment by lsl330** [comment]
please update 2.28.2!

**Comment by tsunamistate** [comment]
This PR is abandoned

This is more likely to be merged soon™ https://github.com/microsoft/vcpkg/pull/33283

**Pull request closed without merging**
