### PR TITLE
[glog] update v0.4.0

### PR DESCRIPTION
**Pull request by MVoz**
possible fix error dynamic

if(VCPKG_LIBRARY_LINKAGE STREQUAL "dynamic")
    set(BUILD_SHARED_LIBS ON)
else()
    set(BUILD_SHARED_LIBS OFF)
endif()

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
	OPTIONS
		-DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS}
)

### CODE REVIEW

**Comment by Rastaban** [comment]
Could you also update the version number in the CONTROL file?

**Comment by Voskrese** [comment]
Ок ;)

**Comment by Rastaban** [comment]
I am seeing the following results in the PR test:

|x64-windows |master| test |notes
|------------|------|------|-----
|sophus      |Pass  |Fail  |**Regression**
|openmvg     |Pass  |Fail  |**Regression**
|cartographer|Pass  |Fail  |**Regression**

|x64-windows-static|master| test |notes
|------------------|------|------|-----
|fizz              |Pass  |Fail  |**Regression**

|arm64-windows|master| test |notes
|-------------|------|------|-----
|sophus       |Pass  |Fail  |**Regression**

|x86-windows |master| test |notes
|------------|------|------|-----
|sophus      |Pass  |Fail  |**Regression**
|openmvg     |Pass  |Fail  |**Regression**
|cartographer|Pass  |Fail  |**Regression**

**Comment by Voskrese** [comment]
and how to be with outdated code and vice versa, with those who are old does not support?
Too many ports, architectures to be perfect for everyone

It is so, thoughts aloud

close?

**Comment by Rastaban** [comment]
@Voskrese, If you want to close this PR then I am okay with that.  It looks like we ran into the same build failures when we tried to update this port recently in #5698, so if you close this PR we will probably take it over to investigate the failures and try to fix them.

**Pull request closed without merging**
