### PR TITLE
[expat] Fix a warning EXPAT_MSVC_STATIC_CRT not used

### PR DESCRIPTION
**Pull request by xiaozhuai**
```
CMake Warning at installed/x64-osx/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:311 (message):
  The following variables are not used in CMakeLists.txt:

      EXPAT_MSVC_STATIC_CRT

  Please recheck them and remove the unnecessary options from the
  `vcpkg_cmake_configure` call.

  If these options should still be passed for whatever reason, please use the
  `MAYBE_UNUSED_VARIABLES` argument.
Call Stack (most recent call first):
  ports/expat/portfile.cmake:12 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)
```

### CODE REVIEW

**Comment by dg0yt** [comment]
It doesn't need more complexity. Just add `MAYBE_UNUSED_VARIABLES EXPAT_MSVC_STATIC_CRT` at the end of `vcpkg_cmake_configure`.

**Comment by xiaozhuai** [comment]
> It doesn't need more complexity. Just add `MAYBE_UNUSED_VARIABLES EXPAT_MSVC_STATIC_CRT` at the end of `vcpkg_cmake_configure`.

Done~

**Comment by MonicaLiu0311** [comment]
Please resolve the conflict.

**Comment by xiaozhuai** [comment]
> Please resolve the conflict.

Sorry for the late reply due to Omicron infection these days.
Done~

**Review by MonicaLiu0311 — APPROVED** [review]

**Pull request merged**
