### PR TITLE
[pthreads] Make port empty on mingw

### PR DESCRIPTION
**Pull request by dg0yt**
- #### What does your PR fix?  
  This PR fixes build failures for mingw for packages which depend on pthread[s].
  The pthreads port fails to build for mingw. But Mingw-w64 (community-supported in vcpkg) usually comes with libwinpthread ([mingw-w64-x86_64-libwinpthread-git](https://packages.msys2.org/package/mingw-w64-x86_64-libwinpthread-git) in MSYS2, `mingw-w64-x86-64-dev` in Debian) and doesn't need the software from this port, similar to linux and osx targets.
  Related discussion: https://github.com/microsoft/vcpkg/issues/14692#issuecomment-819822506

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  mingw, yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  yes

### CODE REVIEW

**Comment by dg0yt** [comment]
linux CI: unrelated, "curl failed to execute"

**Comment by BillyONeal** [comment]
This doesn't seem correct: VCPKG_TARGET_IS_MINGW already implies VCPKG_TARGET_IS_WINDOWS:

https://github.com/microsoft/vcpkg/blob/3ec41f57e64f691a723fd6e89830d01cc9be93e1/scripts/cmake/vcpkg_common_definitions.cmake#L52-L55

**Comment by dg0yt** [comment]
@JackBoosY et al.: Can you please re-run the failed check (or all of them)? This PR has no assignees or reviewers.

**Comment by JackBoosY** [comment]
Sorry, we forgot this PR.

**Review by JackBoosY — APPROVED** [review]

**Comment by ras0219-msft** [comment]
This LGTM, though I suspect we'll want to build `libwinpthread` ourselves at some point in the future.

**Comment by dg0yt** [comment]
> I suspect we'll want to build `libwinpthread` ourselves at some point in the future

I agree. It is mandatory if you must provide the complete source code of your application (GPL). (For now, I know how to get the relevant files from MSYS2.)

**Pull request merged**
