### PR TITLE
[charls] upgrade to 2.1.0

### PR DESCRIPTION
**Pull request by vbaderks**
Upgrade to the latest released version of CharLS.

Note: The patch file has become obsolete.

The following triplets are supported:
charls:x86-windows
charls:x86-windows-static
charls:x64-windows
charls:x64-windows-static
charls:x64-uwp
charls:x64-linux
charls:x64-osx

### CODE REVIEW

**Comment by vbaderks** [comment]
Note: the CI checks are currently failing/pending. This seems to be caused by other changes and the problem with the macOS pipeline.

**Review by JackBoosY — CHANGES_REQUESTED** [review]
Could you remove these following code in _VCPKG_PATH/scripts/ci.baseline.txt_ ?
```
charls:arm-uwp=fail
charls:x64-uwp=fail
```

**Review by JackBoosY — APPROVED** [review]

**Comment by dan-shaw** [comment]
Thanks for the PR!

**Pull request merged**
