### PR TITLE
[ace] new optional feature: xml-utils

### PR DESCRIPTION
**Pull request by mitza-oci**
Added a feature to the ace port.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
No change

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
Yes

### CODE REVIEW

**Review by JonLiu1993 — APPROVED** [review]

**Comment by JonLiu1993** [comment]
@mitza-oci, thanks for your pr, I tested all the features in the x86-windows triplt locally, but failed. This is the error log. Please take a look:
[build-x86-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/7525328/build-x86-windows-rel-out.log)

**Comment by jwillemsen** [comment]
@mitza-oci See https://github.com/microsoft/vcpkg/pull/21322 for the upgrade to ACE 7.0.4

**Comment by mitza-oci** [comment]
> 
> 
> @mitza-oci See #21322 for the upgrade to ACE 7.0.4

Right, I'll rebase this again and check the error that @JonLiu1993 posted

**Comment by mitza-oci** [comment]
Xerces-C++ has `#define XERCES_XMLCH_T char16_t` which is not what ACE expects with `uses_wchar=1`.  I'm not sure if that's unique to the vcpkg port of Xerces or if it's an upstream problem

**Comment by mitza-oci** [comment]
@jwillemsen in #5602 you added the optional `xmlch-wchar` feature to the `xerces-c` port, I guess we need to use it here

**Comment by jwillemsen** [comment]
I think the existing ace xml feature was intended for xml_utils but looks it is now used for acexml. Looks we used this in the past for the azure pipelines

**Comment by mitza-oci** [comment]
OK, @JonLiu1993 this should fix the error you saw.  I didn't update version numbers since https://github.com/microsoft/vcpkg/pull/21322 will get merged first.  Once that's done I'll rebase this and update the versions.

**Comment by JonLiu1993** [comment]
@mitza-oci ,Thanks for your pr, please run command "./vcpkg x-add-version ace --overwrite-version " then commit again

**Review by JonLiu1993 — APPROVED** [review]

**Review by jwillemsen — APPROVED** [review]

**Comment by mitza-oci** [comment]
Do I need to do anything for `requires:all-feature-testing`?

**Comment by JonLiu1993** [comment]
All features are tested successfully in the 

> Do I need to do anything for `requires:all-feature-testing`?

No, I am testing all features on mu local machine

**Comment by JonLiu1993** [comment]
@mitza-oci ,I tested  all features on my local machine, x86-windows and x64-windows-static triplet are successfully, but x64-windows triplet have a little problem:
````
Mismatching number of debug and release binaries. Found 140 for debug but 134 for release.
Debug binaries

E:/test5/vcpkg/packages/ace_x64-windows/debug/lib/ACEsd.lib
E:/test5/vcpkg/packages/ace_x64-windows/debug/lib/ACEXMLsd.lib
......
Release binaries

E:/test5/vcpkg/packages/ace_x64-windows/lib/ACE.lib
E:/test5/vcpkg/packages/ace_x64-windows/lib/ACEXML.lib
......

Debug binaries were not found
Found 2 post-build check problem(s). To submit these ports to curated catalogs, please first correct the portfile:
E:\test5\vcpkg\ports\ace\portfile.cmake
-- Performing post-build validation done
Stored binary cache: C:\Users\AppData\Local\vcpkg\archives\8c\8c6174664096c9668cbb96136932eb6bf2d06b34fa4009c2c8be0fc3b7b05951.zip
Installing package ace[core,ssl,tao,wchar,xml,xml-utils,zlib]:x64-windows...
Elapsed time for package ace:x64-windows: 3.413 h
````

**Comment by mitza-oci** [comment]
If I'm reading that correctly, it generated `ACEsd.lib` even though it was not configured for static libs?
Nothing in this PR should have impacted that.  I can try reproducing locally.

**Comment by mitza-oci** [comment]
I didn't get an error running `vcpkg install --recurse ace[core,ssl,tao,wchar,xml,xml-utils,zlib]:x64-windows` on this branch.

**Comment by JonLiu1993** [comment]
> If I'm reading that correctly, it generated `ACEsd.lib` even though it was not configured for static libs? Nothing in this PR should have impacted that. I can try reproducing locally.

It’s a bit strange, I just clone your branch and test it locally

**Comment by JonLiu1993** [comment]
All features are tested successfully in the following triplet:
- x86-windows
- x64-windows-static

@mitza-oci have tested x64-windows triplet successfully locally

**Comment by BillyONeal** [comment]
Thanks for the new feature!

**Pull request merged**
