### PR TITLE
[Curl] Update to version 7.64.1

### PR DESCRIPTION
**Pull request by LilyWangL**
1. Since the source changed, modified the name of the target files.

2. Add the uwp compilation macro `_WINSOCK_DEPRECATED_NO_WARNINGS` to disable warnings.

### CODE REVIEW

**Comment by wangli28** [comment]
Related issue #4691.

**Comment by LarryIII** [comment]
Also related https://github.com/Microsoft/vcpkg/issues/5845

**Comment by Rastaban** [comment]
Azure Devops did not automatically trigger a test build, so I started one by hand (#2622463)

**Comment by Rastaban** [comment]
With this change I see a build failure with curl on x64-linux and with cpr on all triplets.

**Comment by wangli28** [comment]
cpr needs update to support curl 7.64.1([#311](https://github.com/whoshuu/cpr/issues/311)).

**Comment by fcharlie** [comment]
Unfortunately, the OpenSSL version of vcpkg does not support TLS 1.3.

**Comment by wangli28** [comment]
Duplicate with #6429, so I am closing this PR for now.

**Pull request closed without merging**
