### PR TITLE
[entt] Update to version 3.3.2

### PR DESCRIPTION
**Pull request by meyerzinn**
Fixes issue #10671

### CODE REVIEW

**Comment by LilyWangL** [comment]
Thanks for your PR! Can you please correct the Version field in the CONTROL file? You can get more information from [maintainer-guide.md](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md).

**Review by LilyWangL — APPROVED** [review]

**Comment by lholden** [comment]
Would love if this got merged :)

**Comment by 20zinnm** [comment]
@Iholden Not sure what we're waiting on. @LilyWangL is this ready to merge?

**Comment by LilyWangL** [comment]
> @iHolden Not sure what we're waiting on. @LilyWangL is this ready to merge?

We will merge this PR soon.

**Pull request merged**
