### PR TITLE
[pugixml] Update to 1.11.1

### PR DESCRIPTION
**Pull request by RT2Code**
I removed the patch because it was fixed upsteam : https://github.com/zeux/pugixml/pull/363

Changelog : https://github.com/zeux/pugixml/releases/tag/v1.11

### CODE REVIEW

**Comment by BillyONeal** [comment]
The CI failures look legitimate. For example, ismrmrd

```
[1/10] "C:\PROGRA~2\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.27.29110\bin\Hostx64\x86\cl.exe"   -DH5_BUILT_AS_DYNAMIC_LIB -DUNICODE -DWIN32 -D_CRT_SECURE_NO_WARNINGS -D_UNICODE -D_WIN32 -D_WINDOWS -D__func__=__FUNCTION__ -Dismrmrd_EXPORTS -ID:\buildtrees\ismrmrd\src\v1.4.2.1-d2fe19029e.clean\include -Iinclude -ID:\installed\x86-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\ismrmrd.dir\libsrc\ismrmrd.c.obj /FdCMakeFiles\ismrmrd.dir\ /FS -c D:\buildtrees\ismrmrd\src\v1.4.2.1-d2fe19029e.clean\libsrc\ismrmrd.c
D:\buildtrees\ismrmrd\src\v1.4.2.1-d2fe19029e.clean\libsrc\ismrmrd.c(551): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
[2/10] "C:\PROGRA~2\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.27.29110\bin\Hostx64\x86\cl.exe"   -DH5_BUILT_AS_DYNAMIC_LIB -DUNICODE -DWIN32 -D_CRT_SECURE_NO_WARNINGS -D_UNICODE -D_WIN32 -D_WINDOWS -D__func__=__FUNCTION__ -Dismrmrd_EXPORTS -ID:\buildtrees\ismrmrd\src\v1.4.2.1-d2fe19029e.clean\include -Iinclude -ID:\installed\x86-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\ismrmrd.dir\libsrc\waveform.c.obj /FdCMakeFiles\ismrmrd.dir\ /FS -c D:\buildtrees\ismrmrd\src\v1.4.2.1-d2fe19029e.clean\libsrc\waveform.c
[3/10] "C:\PROGRA~2\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.27.29110\bin\Hostx64\x86\cl.exe"   -DH5_BUILT_AS_DYNAMIC_LIB -DUNICODE -DWIN32 -D_CRT_SECURE_NO_WARNINGS -D_UNICODE -D_WIN32 -D_WINDOWS -D__func__=__FUNCTION__ -Dismrmrd_EXPORTS -ID:\buildtrees\ismrmrd\src\v1.4.2.1-d2fe19029e.clean\include -Iinclude -ID:\installed\x86-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\ismrmrd.dir\libsrc\dataset.c.obj /FdCMakeFiles\ismrmrd.dir\ /FS -c D:\buildtrees\ismrmrd\src\v1.4.2.1-d2fe19029e.clean\libsrc\dataset.c
D:\buildtrees\ismrmrd\src\v1.4.2.1-d2fe19029e.clean\libsrc\dataset.c(598): warning C4244: 'function': conversion from 'hsize_t' to 'size_t', possible loss of data
D:\buildtrees\ismrmrd\src\v1.4.2.1-d2fe19029e.clean\libsrc\dataset.c(599): warning C4244: 'function': conversion from 'hsize_t' to 'size_t', possible loss of data
D:\buildtrees\ismrmrd\src\v1.4.2.1-d2fe19029e.clean\libsrc\dataset.c(601): warning C4244: '=': conversion from 'hsize_t' to 'uint32_t', possible loss of data
D:\buildtrees\ismrmrd\src\v1.4.2.1-d2fe19029e.clean\libsrc\dataset.c(805): warning C4244: '=': conversion from 'hsize_t' to 'size_t', possible loss of data
[4/10] "C:\PROGRA~2\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.27.29110\bin\Hostx64\x86\cl.exe"   /TP -DH5_BUILT_AS_DYNAMIC_LIB -DUNICODE -DWIN32 -D_CRT_SECURE_NO_WARNINGS -D_UNICODE -D_WIN32 -D_WINDOWS -D__func__=__FUNCTION__ -Dismrmrd_EXPORTS -ID:\buildtrees\ismrmrd\src\v1.4.2.1-d2fe19029e.clean\include -Iinclude -ID:\installed\x86-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /EHsc /W3 /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\ismrmrd.dir\libsrc\waveform.cpp.obj /FdCMakeFiles\ismrmrd.dir\ /FS -c D:\buildtrees\ismrmrd\src\v1.4.2.1-d2fe19029e.clean\libsrc\waveform.cpp
[5/10] "C:\PROGRA~2\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.27.29110\bin\Hostx64\x86\cl.exe"   /TP -DH5_BUILT_AS_DYNAMIC_LIB -DUNICODE -DWIN32 -D_CRT_SECURE_NO_WARNINGS -D_UNICODE -D_WIN32 -D_WINDOWS -D__func__=__FUNCTION__ -Dismrmrd_EXPORTS -ID:\buildtrees\ismrmrd\src\v1.4.2.1-d2fe19029e.clean\include -Iinclude -ID:\installed\x86-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /EHsc /W3 /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\ismrmrd.dir\libsrc\dataset.cpp.obj /FdCMakeFiles\ismrmrd.dir\ /FS -c D:\buildtrees\ismrmrd\src\v1.4.2.1-d2fe19029e.clean\libsrc\dataset.cpp
[6/10] "C:\PROGRA~2\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.27.29110\bin\Hostx64\x86\cl.exe"   /TP -DH5_BUILT_AS_DYNAMIC_LIB -DUNICODE -DWIN32 -D_CRT_SECURE_NO_WARNINGS -D_UNICODE -D_WIN32 -D_WINDOWS -D__func__=__FUNCTION__ -Dismrmrd_EXPORTS -ID:\buildtrees\ismrmrd\src\v1.4.2.1-d2fe19029e.clean\include -Iinclude -ID:\installed\x86-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /EHsc /W3 /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\ismrmrd.dir\libsrc\meta.cpp.obj /FdCMakeFiles\ismrmrd.dir\ /FS -c D:\buildtrees\ismrmrd\src\v1.4.2.1-d2fe19029e.clean\libsrc\meta.cpp
[7/10] "C:\PROGRA~2\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.27.29110\bin\Hostx64\x86\cl.exe"   /TP -DH5_BUILT_AS_DYNAMIC_LIB -DUNICODE -DWIN32 -D_CRT_SECURE_NO_WARNINGS -D_UNICODE -D_WIN32 -D_WINDOWS -D__func__=__FUNCTION__ -Dismrmrd_EXPORTS -ID:\buildtrees\ismrmrd\src\v1.4.2.1-d2fe19029e.clean\include -Iinclude -ID:\installed\x86-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /EHsc /W3 /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\ismrmrd.dir\libsrc\ismrmrd.cpp.obj /FdCMakeFiles\ismrmrd.dir\ /FS -c D:\buildtrees\ismrmrd\src\v1.4.2.1-d2fe19029e.clean\libsrc\ismrmrd.cpp
[8/10] "C:\PROGRA~2\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.27.29110\bin\Hostx64\x86\cl.exe"   /TP -DH5_BUILT_AS_DYNAMIC_LIB -DUNICODE -DWIN32 -D_CRT_SECURE_NO_WARNINGS -D_UNICODE -D_WIN32 -D_WINDOWS -D__func__=__FUNCTION__ -Dismrmrd_EXPORTS -ID:\buildtrees\ismrmrd\src\v1.4.2.1-d2fe19029e.clean\include -Iinclude -ID:\installed\x86-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /EHsc /W3 /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\ismrmrd.dir\libsrc\xml.cpp.obj /FdCMakeFiles\ismrmrd.dir\ /FS -c D:\buildtrees\ismrmrd\src\v1.4.2.1-d2fe19029e.clean\libsrc\xml.cpp
D:\buildtrees\ismrmrd\src\v1.4.2.1-d2fe19029e.clean\libsrc\xml.cpp(27): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
D:\buildtrees\ismrmrd\src\v1.4.2.1-d2fe19029e.clean\libsrc\xml.cpp(28): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
D:\buildtrees\ismrmrd\src\v1.4.2.1-d2fe19029e.clean\libsrc\xml.cpp(29): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
D:\buildtrees\ismrmrd\src\v1.4.2.1-d2fe19029e.clean\libsrc\xml.cpp(71): warning C4244: 'argument': conversion from 'double' to 'const T', possible loss of data
        with
        [
            T=float
        ]
D:\buildtrees\ismrmrd\src\v1.4.2.1-d2fe19029e.clean\libsrc\xml.cpp(101): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
D:\buildtrees\ismrmrd\src\v1.4.2.1-d2fe19029e.clean\libsrc\xml.cpp(316): warning C4101: 'e': unreferenced local variable
[9/10] cmd.exe /C "cd . && D:\downloads\tools\cmake-3.18.4-windows\cmake-3.18.4-win32-x86\bin\cmake.exe -E vs_link_dll --intdir=CMakeFiles\ismrmrd.dir --rc="C:\PROGRA~2\Windows Kits\10\bin\10.0.19041.0\x64\rc.exe" --mt="C:\PROGRA~2\Windows Kits\10\bin\10.0.19041.0\x64\mt.exe" --manifests  -- "C:\PROGRA~2\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.27.29110\bin\Hostx64\x86\link.exe"  CMakeFiles\ismrmrd.dir\libsrc\ismrmrd.c.obj CMakeFiles\ismrmrd.dir\libsrc\ismrmrd.cpp.obj CMakeFiles\ismrmrd.dir\libsrc\xml.cpp.obj CMakeFiles\ismrmrd.dir\libsrc\meta.cpp.obj CMakeFiles\ismrmrd.dir\libsrc\waveform.cpp.obj CMakeFiles\ismrmrd.dir\libsrc\waveform.c.obj CMakeFiles\ismrmrd.dir\libsrc\dataset.c.obj CMakeFiles\ismrmrd.dir\libsrc\dataset.cpp.obj  /out:ismrmrd.dll /implib:ismrmrd.lib /pdb:ismrmrd.pdb /dll /version:1.4 /machine:X86 /debug /INCREMENTAL:NO  D:\installed\x86-windows\debug\lib\hdf5_D.lib  pugixml.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib  && cd ."
FAILED: ismrmrd.dll ismrmrd.lib 
cmd.exe /C "cd . && D:\downloads\tools\cmake-3.18.4-windows\cmake-3.18.4-win32-x86\bin\cmake.exe -E vs_link_dll --intdir=CMakeFiles\ismrmrd.dir --rc="C:\PROGRA~2\Windows Kits\10\bin\10.0.19041.0\x64\rc.exe" --mt="C:\PROGRA~2\Windows Kits\10\bin\10.0.19041.0\x64\mt.exe" --manifests  -- "C:\PROGRA~2\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.27.29110\bin\Hostx64\x86\link.exe"  CMakeFiles\ismrmrd.dir\libsrc\ismrmrd.c.obj CMakeFiles\ismrmrd.dir\libsrc\ismrmrd.cpp.obj CMakeFiles\ismrmrd.dir\libsrc\xml.cpp.obj CMakeFiles\ismrmrd.dir\libsrc\meta.cpp.obj CMakeFiles\ismrmrd.dir\libsrc\waveform.cpp.obj CMakeFiles\ismrmrd.dir\libsrc\waveform.c.obj CMakeFiles\ismrmrd.dir\libsrc\dataset.c.obj CMakeFiles\ismrmrd.dir\libsrc\dataset.cpp.obj  /out:ismrmrd.dll /implib:ismrmrd.lib /pdb:ismrmrd.pdb /dll /version:1.4 /machine:X86 /debug /INCREMENTAL:NO  D:\installed\x86-windows\debug\lib\hdf5_D.lib  pugixml.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib  && cd ."
LINK: command "C:\PROGRA~2\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.27.29110\bin\Hostx64\x86\link.exe CMakeFiles\ismrmrd.dir\libsrc\ismrmrd.c.obj CMakeFiles\ismrmrd.dir\libsrc\ismrmrd.cpp.obj CMakeFiles\ismrmrd.dir\libsrc\xml.cpp.obj CMakeFiles\ismrmrd.dir\libsrc\meta.cpp.obj CMakeFiles\ismrmrd.dir\libsrc\waveform.cpp.obj CMakeFiles\ismrmrd.dir\libsrc\waveform.c.obj CMakeFiles\ismrmrd.dir\libsrc\dataset.c.obj CMakeFiles\ismrmrd.dir\libsrc\dataset.cpp.obj /out:ismrmrd.dll /implib:ismrmrd.lib /pdb:ismrmrd.pdb /dll /version:1.4 /machine:X86 /debug /INCREMENTAL:NO D:\installed\x86-windows\debug\lib\hdf5_D.lib pugixml.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:ismrmrd.dll.manifest" failed (exit code 1181) with the following output:
Microsoft (R) Incremental Linker Version 14.27.29111.0
Copyright (C) Microsoft Corporation.  All rights reserved.

LINK : fatal error LNK1181: cannot open input file 'pugixml.lib'
ninja: build stopped: subcommand failed.
```

**Comment by BillyONeal** [comment]
I also note that this looks like what that patch might have been fixing?

**Comment by c72578** [comment]
Please have a look at the discussion here:
https://github.com/zeux/pugixml/pull/384
Pugixml 1.11 is currently broken concerning find_package(pugixml)

**Comment by c72578** [comment]
@RT222 Could you please add the following patch from the upstream PR:
https://patch-diff.githubusercontent.com/raw/zeux/pugixml/pull/384.patch

**Comment by RT222** [comment]
Thanks for your help c72578, it's very much appreciated. Digging into linking problems is a dreadful task for me. ^^

**Comment by c72578** [comment]
@RT222 In the meantime, **`pugixml 1.11.1`** has been released.
https://github.com/zeux/pugixml/releases/tag/v1.11.1
It includes the fix of https://github.com/zeux/pugixml/pull/384

**Comment by c72578** [comment]
@RT222 Could you please update the title of the PR to 1.11.1

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Comment by zeux** [comment]
Thanks for catching this and sorry about the CMake issues!

**Pull request merged**
