### PR TITLE
[libffi] Update to v3.4.2

### LINKED ISSUE #18076: libffi build failure
**Host Environment**
- OS: Windows
- Compiler: MingW

**To Reproduce**
`./vcpkg install boost:x86-mingw-dynamic`

**Failure logs** 
```
Starting package 1/22: libffi:x64-mingw-dynamic
Building package libffi[core]:x64-mingw-dynamic...
-- Using community triplet x64-mingw-dynamic. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: C:\Users\thebl\GitHub\vcpkg\triplets\community\x64-mingw-dynamic.cmake
-- Using cached C:/Users/thebl/GitHub/vcpkg/downloads/libffi-libffi-v3.3.tar.gz
-- Cleaning sources at C:/Users/thebl/GitHub/vcpkg/buildtrees/libffi/src/v3.3-e8d06c1444.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/thebl/GitHub/vcpkg/downloads/libffi-libffi-v3.3.tar.gz
-- Applying patch win64-disable-stackframe-check.patch
-- Applying patch win32-disable-stackframe-check.patch
-- Using source at C:/Users/thebl/GitHub/vcpkg/buildtrees/libffi/src/v3.3-e8d06c1444.clean
-- Configuring x64-mingw-dynamic
-- Building x64-mingw-dynamic-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: C:/Users/thebl/GitHub/vcpkg/downloads/tools/cmake-3.20.2-windows/cmake-3.20.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: C:/Users/thebl/GitHub/vcpkg/buildtrees/libffi/x64-mingw-dynamic-dbg
    See logs for more information:
      C:\Users\thebl\GitHub\vcpkg\buildtrees\libffi\install-x64-mingw-dynamic-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:104 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/libffi/portfile.cmake:26 (vcpkg_install_cmake)
  scripts/ports.cmake:141 (include)


Error: Building package libffi:x64-mingw-dynamic failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libffi:x64-mingw-dynamic
  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9

Additionally, attach any relevant sections from the log files above.
```
**Additional context**
Most other packages are installing fine. This is the only one that is causing problems.

### PR DESCRIPTION
**Pull request by longnguyen2004**
**Describe the pull request**

- #### What does your PR fix?  
  Fixes #18076
  Update libffi to v3.4.2 and remove upstreamed patches
- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all, not needed

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

### CODE REVIEW

**Comment by talregev** [comment]
I am run it on the ci. I will let you know the result.

**Comment by talregev** [comment]
I also check on my wsl:
I can confirm it working for:
--triplet=x64-mingw-static
it not working for: 
--triplet=x86-mingw-static

Not sure if we need to support x86?

**Comment by talregev** [comment]
For x86-mingw-static
```
CMake Error at CMakeLists.txt:19 (message):
  Unknown processor: i686
```

logs:
[libffi.zip](https://github.com/microsoft/vcpkg/files/6835931/libffi.zip)

**Comment by talregev** [comment]
Now I can confirm it working on my wsl also with --triplet=x86-mingw-static

Thank you.

**Review by JonLiu1993 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Comment by talregev** [comment]
Thank you!

**Pull request merged**
