### PR TITLE
ICU: Add WindowsStore support

### PR DESCRIPTION
**Pull request by Ghabry**
ICU handles the UWP build like a cross compilation.
This means ICU needs a native build tree to run the ICU apps in it. I'm not sure if my strategy to find a buildtree is optimal.

Don't merge yet, one problem remaining:
The post-check fails with "The following DLLs do not have the App Container bit set: icudt59.dll"
icudt contains only data, no code and this file is generated through a ICU application, not through the compiler, so my LDFLAGS are ignored.
Is there a tool available that can set the App Container bit? Assuming this is enough, I don't know if UWP-DLLs have additional requirements.

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for the PR!

Yeah, you can use `link.exe /edit /APPCONTAINER:YES foo.dll` (if I recall correctly).

It does seem like we should have a better solution than referencing the other build trees since those can be from newer/older/broken versions of `icu`. However, I think that would be a lot more complicated and I'd be happy to get `icu` working for UWP this way in the meantime!

**Comment by Ghabry** [comment]
Hey. I can't get the "link.exe /edit /APPCONTAINER:YES foo.dll" to work. Only get an error message.
I also tried the build-option for ICU that emits the data file as C code that is compiled (instead of generating the lib through a tool) but seems to be unsupported for Windows builds :/.

**Comment by Rastaban** [comment]
Closing PR.  No progress has been made for awhile and It looks like there are enough changes in the latest icu port file that this may need to be reworked.  If you get a chance to look into this again then please submit another PR.

**Comment by jefgen** [comment]
I wonder if it would be more interesting to see if the Win32 binaries could be modifies to work inside the UWP environment instead? (The separate "UWP" Visual Studio project files is something that we'd like to eventually remove in the upstream ICU project).

**Pull request closed without merging**
