### PR TITLE
[tensorflow-cc] fix build issues on Windows

### LINKED ISSUE #12506: [tensorflow-cc:x64-windows] build failure
**Host Environment**
- OS: Windows 10 64 bit
- Using Visual Studio 2019

**To Reproduce**
`./vcpkg install tensorflow-cc:x64-windows`

**Failure logs** 
Error: Building package tensorflow-cc:x64-windows failed with: BUILD_FAILED
[build-x64-windows-rel-err.log](https://github.com/microsoft/vcpkg/files/4948508/build-x64-windows-rel-err.log)
[build-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/4948509/build-x64-windows-rel-out.log)

I'm a beginner so if you need more information just tell me. And also I saw pretty similar issues but I was not able to solve the problem so thanks for your help.

### PR DESCRIPTION
**Pull request by jgehw**
occurring from default bazel config being used because customized bazel config is stored in wrong directory:

Omitting the --workspace parameter of configure.py defaults not the the current working directory but to the directory where configure.py is extracted to. This results in the customized bazel config being stored in the wrong directory and thus the default bazel config being used. This, in turn leads to tons of build errors, mainly of two types:

1)
` .\tensorflow/stream_executor/rng.h(66): error C2589: 'constant': illegal token on right side of '::'`
`.\tensorflow/stream_executor/rng.h(66): error C2059: syntax error: '::'`
`.\tensorflow/stream_executor/rng.h(72): error C2589: 'constant': illegal token on right side of '::'`
`.\tensorflow/stream_executor/rng.h(72): error C2059: syntax error: '::'`

2) tons of winsock2 related errors such as macro redefinitions and invalid constants, like those already reported in https://github.com/microsoft/vcpkg/issues/12506
Closes #12506

### CODE REVIEW

**Review by dan-shaw — APPROVED** [review]

**Comment by JackBoosY** [comment]
@jgehw Please sign CLA first.

Thanks.

**Comment by jgehw** [comment]
The CI runs on windows fail due to some access denied issue while setting up MSYS2. No idea what's going on there.
PS: I recall that the very first time I tried to install it in my environment also failed (it didn't crash but was hanging after setting up MSYS2). All subsequent runs however worked because MSYS2 was present then.

**Comment by JackBoosY** [comment]
Will fix in #12603

**Comment by JackBoosY** [comment]
When building x64-windows:
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.26.28801\include\yvals_core.h(466): fatal error C1189: #error:  STL1001: Unexpected compiler version, expected MSVC 19.25 or newer.
```

**Comment by jgehw** [comment]
Can you please re-run the failed x64_windows port? (I checked the build error logs and found a bazel package download error - bad timings because a server was down over the weekend. I had this error on my machine, too, and it disappeared after the server was back on.)

**Comment by JackBoosY** [comment]
Reruning...

**Comment by LilyWangL** [comment]
@jgehw The new error:
```
Loading: 0 packages loaded
    currently loading: tensorflow
Analyzing: 2 targets (1 packages loaded, 0 targets configured)
INFO: An error occurred during the fetch of repository 'local_config_cc'
INFO: Call stack for the definition of repository 'local_config_cc':
 - D:/buildtrees/.bzl/_bazel_azdevops/zcqffzsa/external/bazel_tools/tools/cpp/cc_configure.bzl:97:5
 - /DEFAULT.WORKSPACE.SUFFIX:246:1
ERROR: no such package '@local_config_cc//': Traceback (most recent call last):
	File "D:/buildtrees/.bzl/_bazel_azdevops/zcqffzsa/external/bazel_tools/tools/cpp/cc_configure.bzl", line 52
		configure_windows_toolchain(repository_ctx)
	File "D:/buildtrees/.bzl/_bazel_azdevops/zcqffzsa/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 349, in configure_windows_toolchain
		_find_missing_vc_tools(repository_ctx, vc_path)
	File "D:/buildtrees/.bzl/_bazel_azdevops/zcqffzsa/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 248, in _find_missing_vc_tools
		_find_vcvarsall_bat_script(repository_ctx, vc_path)
	File "D:/buildtrees/.bzl/_bazel_azdevops/zcqffzsa/external/bazel_tools/tools/cpp/windows_cc_configure.bzl", line 191, in _find_vcvarsall_bat_script
		repository_ctx.path(vcvarsall).exists
```

**Comment by jgehw** [comment]
can you please re-run again? (the errors of the automated run seem to me to come from azure devops pipepline early stage, hopefully transient)

**Comment by LilyWangL** [comment]
> can you please re-run again? (the errors of the automated run seem to me to come from azure devops pipepline early stage, hopefully transient)

Done.

**Comment by JackBoosY** [comment]
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.26.28801\include\yvals_core.h(466): fatal error C1189: #error:  STL1001: Unexpected compiler version, expected MSVC 19.25 or newer.
```

**Comment by jgehw** [comment]
It turned out that tensorflow v1.14 requires really outdated bazel v0.25, so I reverted the bazel upgrade to 3.4.1 and set x64-windows CI to fail again. It only works if no more than one VC toolkit is installed. So the PR still has its value, but the CI won't succeed. As ultimate solution I'm going to upgrade tensorflow to v2.3 and then using up-to-date bazel, but will do this in a separate PR, as it requires more work.

**Review by JackBoosY — APPROVED** [review]

**Review by LilyWangL — APPROVED** [review]

**Pull request merged**
