### PR TITLE
[polyhook2]  Update to latest

### PR DESCRIPTION
**Pull request by stevemk14ebr**
**Describe the pull request**

- What does your PR fix? Fixes #
Fixes some core bugs in polyhook2

- Which triplets are supported/not supported? Have you updated the CI baseline?
x86-windows-static
x86-windows
x64-windows
x64-windows-static

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

### CODE REVIEW

**Comment by NancyLi1013** [comment]
Hi @stevemk14ebr 
Thanks for this PR.
Have you tested all features?

**Review by NancyLi1013 — APPROVED** [review]

**Comment by stevemk14ebr** [comment]
I run this version locally, everything is tested.

**Comment by ras0219-msft** [comment]
Thanks for the PR!

**Pull request merged**
