### PR TITLE
[libev] init required by #1122

### PR DESCRIPTION
**Pull request by atkawa7**

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for the PR!

I think it may be better to not include the libevent wrapper, and instead package libevent proper as a separate library (if desired).

This is what ArchLinux does:
- https://www.archlinux.org/packages/core/x86_64/libevent/
- https://www.archlinux.org/packages/community/x86_64/libev/

It looks like Debian does have the wrapper available as a separate package:
- https://packages.debian.org/sid/libev-libevent-dev

**Comment by atkawa7** [comment]
@ras0219-msft Could you elaborate further?  I am not sure I understand what you mean by `libevent wrapper`.

**Comment by Voskrese** [comment]
сейчас пытаюсь собрать OpenSSL на максимуме, у нее в зависимости **nghttp2** https://github.com/nghttp2/nghttp2 в свою очерез зависимость пораждает зависимость libev >= 4.11 , spdylay >= 1.3.2 , libevent-openssl >= 2.0.8
я думаю стоит одобрить этот порт) 

> now try to build OpenSSL on high, she based on * nghttp2 * https://github.com/nghttp2/nghttp2 in your ocherez addiction porazhdaet dependency libev > = 4.11, spdylay > = 1.3.2, libevent-openssl > = 2.0.8
> I think it is worth to endorse this port)

**Comment by ras0219-msft** [comment]
`libev` optionally provides an "event.h" header which is intended to impersonate `libevent`. In the current portfile configuration, this header is being generated and installed, which will conflict with the main `libevent` library.

Since we have `libevent` proper packaged, it seems better to avoid installing that wrapper header since it will cause conflicts. I think there should be a cmake option to disable the compatibility layer? Simply deleting the header won't be sufficient because there will still be problematic exported symbols.

**Comment by atkawa7** [comment]
@ras0219-msft Thanks. I guess closing this would be the best thing right

**Pull request closed without merging**
