### PR TITLE
[libsodium] Fix CPU feature not properly detected on Linux

### LINKED ISSUE #8956: libsodium build script not properly detect CPU feature
**Describe the bug**
When I  (static) link my program with the libsodium.a library,  running my program lead to core dump.

**Environment**
- OS: Ubuntu 18.04.3 LTS
- Compiler: gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

**To Reproduce**
1. ./vcpkg install libsodium

**Expected behavior**

**Failure logs** 
Illegal instruction (core dumped)

core dump stack:
  >│0x562887b92931  vmovdqa 0x464ad7(%rip),%xmm0        # 0x562887ff7410                │

**Additional context**
```bash
cat /proc/cpuinfo

processor	: 19
vendor_id	: GenuineIntel
cpu family	: 15
model		: 6
model name	: Common KVM processor
stepping	: 1
microcode	: 0x1
cpu MHz		: 2297.338
cache size	: 16384 KB
physical id	: 1
siblings	: 10
core id		: 9
cpu cores	: 10
apicid		: 25
initial apicid	: 25
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl xtopology cpuid tsc_known_freq pni cx16 x2apic hypervisor lahf_lm cpuid_fault pti
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs
bogomips	: 4594.67
clflush size	: 64
cache_alignment	: 128
address sizes	: 40 bits physical, 48 bits virtual
power management:
```

### PR DESCRIPTION
**Pull request by valbendan**
fix #8956

### CODE REVIEW

**Comment by JackBoosY** [comment]
Hi @valbendan, thanks for making this PR! I also have PR #8977 to solve this problem. Is your PR effective?

**Comment by valbendan** [comment]
I have test the modification with my demo repo: https://github.com/valbendan/LibsodiumVcpkg and it WORKS.


I found the main problem is the following code can be successfully COMPILED even on CPU without avx2 feature, it lead to the all `check_c_source_compiles` with success value.
```c
#include <immintrin.h>
#pragma GCC target("avx2")
int main(void) {
	__m256 x = _mm256_set1_ps(3.14);
	__m256 y = _mm256_permutevar8x32_ps(x, _mm256_set1_epi32(42));
	return _mm256_movemask_ps(_mm256_cmp_ps(x, y, _CMP_NEQ_OQ));
}
```

**Comment by myd7349** [comment]
Hi! @Formulator Sorry for the delay. Would you like to give this patch a try?

**Comment by valbendan** [comment]
Any update ?

**Comment by JackBoosY** [comment]
@valbendan We are waiting for fix the CI system.

**Comment by JackBoosY** [comment]
We just fixed the CI system

**Comment by JackBoosY** [comment]
Please update the version in `CONTROL` file:
`Version: 1.0.18-1`
->
`Version: 1.0.18-2`

**Review by JackBoosY — CHANGES_REQUESTED** [review]
Please update the version in CONTROL file:
`Version: 1.0.18-1`
->
`Version: 1.0.18-2`

**Review by JackBoosY — APPROVED** [review]

**Comment by valbendan** [comment]
Can be merged ?

**Comment by JackBoosY** [comment]
@grdowns This PR is ready to merge now.

**Comment by ras0219-msft** [comment]
LGTM, thanks for the PR!

**Pull request merged**
