### PR TITLE
[antlr4] Support build on Linux and MacOS.

### PR DESCRIPTION
**Pull request by icedream2linxi**
I tested build antlr4 with following triplet:

- x86-windows
- x86-windows-static
- x64-windows
- x64-windows-static
- x64-linux
- x64-osx

### CODE REVIEW

**Comment by icedream2linxi** [comment]
After using this PR, #3965 is no longer needed.

**Comment by alexkaratarakis** [comment]
Looks solid!
I am getting a hash mismatch for the LICENSE file. Mine is: `1e8414de5fdc211e3188a8ec3276c6b3c55235f5edaf48522045ae18fa79fd9049719cb8924d25145016f223ac9a178defada1eeb983ccff598a08b0c0f67a3b`.

Does it correctly work for you if you delete: `$vcpkg/downloads/temp/antlr4-copyright` ?

**Comment by icedream2linxi** [comment]
Sorry, I made a low-level mistake. Now add the version number to copyright to avoid making mistakes again.

**Comment by icedream2linxi** [comment]
@alexkaratarakis

**Comment by icedream2linxi** [comment]
@alexkaratarakis 
My current design, need to install uuid-dev on Linux, is it acceptable?

**Comment by alexkaratarakis** [comment]
@icedream2linxi 
It is not ideal, but in this case it is not necessary!
I have modified the portfile to use `libuuid` from `vcpkg` instead.

One things that I found strange though: I had to add `#include "antlr4-common.h"` in `guid.cpp`, as can be seen in the patchfile. That file uses a bunch of macros like `GUID_LIBUUID` that are #defined in antlr4-common.h, so without including said header those macros are never defined. 

This looks like a bug in the library. Do you know if the macros are supposed to be defined some other way?

**Comment by vicroms** [comment]
Closed in favor of #5606.

**Pull request closed without merging**
