### PR TITLE
[drogon, trantor] Bump drogon to 1.9.8 and trantor to 1.5.22

### PR DESCRIPTION
**Pull request by an-tao**

### CODE REVIEW

**Review by MonicaLiu0311 — APPROVED** [review]

**Review by MonicaLiu0311 — APPROVED** [review]

**Comment by MonicaLiu0311** [comment]
Note: There is one unsuccessful check shown here, but in fact all checks passed：

image

**Comment by vicroms** [comment]
Attempt #2 of whacking CI awake

**Review by vicroms — APPROVED** [review]
Waiting for green CI checks before merging

**Comment by vicroms** [comment]
I don't know how to make the red check go away and cannot merge without it being green. 

@an-tao would you mind closing this PR and opening a new one with the same changes, I think that should give a clean CI build.

**Pull request merged**
