### PR TITLE
[sdl2pp] Fix find dependencies

### PR DESCRIPTION
**Pull request by JackBoosY**
Fix find dependencies port sdl2, sdl2-image, sdl2-ttf, sdl2-mixer.

Related: #9393.

Note: no feature needs to be tested.

### CODE REVIEW

**Comment by JackBoosY** [comment]
@longnguyen2004 Could you test it? Thanks.

**Comment by longnguyen2004** [comment]
Thanks, I'll test it tonight

**Comment by longnguyen2004** [comment]
hmm I got an error when applying the patch, can you double check it?

**Comment by JackBoosY** [comment]
@longnguyen2004 Could you re-clone `https://github.com/JackBoosY/vcpkg.git`, switch branch to `dev/jack/9393` and try again?

**Comment by JackBoosY** [comment]
Hi @longnguyen2004, you cannot copy-paste the contents of the patch to use, this will lose some data. You should clone _https://github.com/JackBoosY/vcpkg.git_ and switch to branch `dev/jack/9393` to get the **patch** and **portfile.cmake** and use these changes.

**Comment by longnguyen2004** [comment]
Oh ok, my bad. I'm still a starter at Git, will try tomorrow

**Comment by longnguyen2004** [comment]
image
Seems all good, still wondering why CI is mad about this

**Review by PhoebeHui — APPROVED** [review]

**Pull request merged**
