### PR TITLE
[cctag] Add new port

### PR DESCRIPTION
**Pull request by simogasp**
**Describe the pull request**

The PR introduces a new port for the CCTag library, a computer vision library for detecting markers made of concentric circles. The port comes with two optional features, `cuda` for enabling cuda support and `apps` to build some sample applications that showcase the library

- Which triplets are supported/not supported? Have you updated the CI baseline?
At the moment it does not support uwp, arm, arm64, android and x86.
For x64-windows, the `cuda` option is currently broken because of Boost 1.75 and this fix that is required https://github.com/boostorg/preprocessor/commit/aa8f347df2b189b14c4079c6fb7fa2819ac4a6f1 and that is likely to appear in 1.76 soon

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

### CODE REVIEW

**Comment by simogasp** [comment]
Hi @PhoebeHui 
I cannot understand the error, if it comes from my scripts or if it is something unrelated the pipeline needs to be launched again.
Thanks!

**Comment by PhoebeHui** [comment]
@simogasp, it failed due to the vcpkg.json format, you can apply the following patch, and submit the changes.

[format.diff (2).zip](https://github.com/microsoft/vcpkg/files/6152980/format.diff.2.zip)

**Comment by simogasp** [comment]
@PhoebeHui Thanks for the patch, it fixed it.
Just to know, the problem was the formatting/tab spacing or the entries must be in alphabetical order as well or that's just a convention.
Is there a JSON schema to validate the file or a "hidden" functionality of vcpkg that allows to validate it locally? Because it was working fine on my pc.

**Comment by simogasp** [comment]
I will keep it WIP because we are in the process of making the v1.0.0 release, once we are done I will clean the code from all the debug and test comments, i will add the ref to the v1.0.0 tag and open it for review.

**Comment by PhoebeHui** [comment]
@simogasp,  you can format vcpkg.json with following command:

./vcpkg format-manifest ./ports/cctag/vcpkg.json

**Comment by PhoebeHui** [comment]
@simogasp, ping me if the PR ready for review!

**Review by Matausi29 — APPROVED** [review]

**Comment by simogasp** [comment]
@PhoebeHui @Matausi29 we finally release the v1.0.0 and I move the PR from draft to ready for review.
If you have any other comments or remarks I will gladly deal with them. Thanks!

**Comment by PhoebeHui** [comment]
Features test:
- [x] cctag[app]:x64-windows: Pass, see above comments for feature 'cuda' failures.
- [x] cctag[cuda,apps]:x64-linux: Pass

Noted that cctag:x64-windows doesn't test in CI pipeline, it cascaded due to dependent port opencv3 skipped in CI testing. We test it locally, it built successfully.

The simage:x64-osx failure is baseline issue, it doesn't relate to this PR, please ignore it, It would be fixed by PR https://github.com/microsoft/vcpkg/pull/18645

**Review by PhoebeHui — APPROVED** [review]

**Pull request merged**
