### PR TITLE
[vcpkg] Disable timeout (default 10s) in vcpkg_acquire_msys

### PR DESCRIPTION
**Pull request by jgehw**
Default timeout is 10s, and MSYS2 servers are rather slow. When additional being on a slow internet connection, installation of MSYS2 fails. Fix by disabling timeout.

### CODE REVIEW

**Comment by jgehw** [comment]
As pacman only allows to disable the timeout (or use a custom command), I set a timeout via `_execute_process` as @BillyONeal suggested, and extended `vcpkg_execute_required_process` accordingly to pass a timeout forward to `_execute_process`.

**Comment by jgehw** [comment]
Made the timeout in the last case (install the packages) in `vcpkg_acquire_msys()` configurable as someone may want to install many packages and thus needs a longer timeout.

**Review by BillyONeal — APPROVED** [review]

**Review by PhoebeHui — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
