### PR TITLE
[flecs] update to 3.2.2

### PR DESCRIPTION
**Pull request by podsvirov**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by MonicaLiu0311** [comment]
The usage test passed (header files found):
```
flecs provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(flecs CONFIG REQUIRED)
    target_link_libraries(main PRIVATE flecs::flecs flecs::flecs_static)
```

**Review by MonicaLiu0311 — APPROVED** [review]

**Comment by dg0yt** [comment]
> target_link_libraries(main PRIVATE flecs::flecs flecs::flecs_static)

Can't there be something better than the heuristics?
(Won't my project fail in dynamic linkage when I link to `flecs::flecs_static`?)

**Comment by MonicaLiu0311** [comment]
> > target_link_libraries(main PRIVATE flecs::flecs flecs::flecs_static)
> 
> Can't there be something better than the heuristics? (Won't my project fail in dynamic linkage when I link to `flecs::flecs_static`?)


* x64-windows
* VS 2022

When I test Usage in the following way, it succeeds. Please let me know if my tests are flawed.

usage:
```
flecs provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(flecs CONFIG REQUIRED)
    target_link_libraries(main PRIVATE flecs::flecs flecs::flecs_static)
```

<details>
<summary><b>CMakeFindUsage.cpp</b></summary>
<pre>
#include &#60;iostream&#62;
#include "flecs.hpp"

using namespace std;

int main()
{
        cout << "Hello CMake." << endl;
        return 0;
}
</pre></details>


<details>
<summary><b>CMakeLists.txt</b></summary>
<pre>
cmake_minimum_required (VERSION 3.8)

set(BUILD_SHARED_LIBS "build dynamic lib" ON)
set(CMAKE_TOOLCHAIN_FILE "E:/flecs/scripts/buildsystems/vcpkg.cmake")

project ("CMakeFindUsage")

add_library(main "CMakeFindUsage.cpp")

find_package(flecs CONFIG REQUIRED)
target_link_libraries(main PRIVATE flecs::flecs flecs::flecs_static)
</pre></details>

**Comment by FrankXie05** [comment]
We should use method instead of output `Hello World`. :)
Upstream examples: https://github.com/SanderMertens/flecs#show-me-the-code

**Comment by dg0yt** [comment]
The test is flawed because it doesn' t answer why it succeeds for you and why success is bad here.

Why does `flecs::flecs_static` work in dynamic linkage?
It works because the wrapper creates the missing target.
It may be nice to do this, so users/maintainers don't need to care if they come with a project which wasn't tested with the other linkage.

Why is the successful test bad here?
Suggesting `target_link_libraries(main PRIVATE flecs::flecs flecs::flecs_static)` only works in vcpkg. Outside vcpkg either one target will be missing, or the user will link two libs providing the same symbols but with different linkage.

What needs to be done?
Add a usage file which can work without the wrapper, i.e. using
~~~cmake
    target_link_libraries(main PRIVATE $<IF:$<TARGET_EXISTS:flecs::flecs>,flecs::flecs,flecs::flecs_static>)
~~~

**Comment by MonicaLiu0311** [comment]
Thanks very much for @dg0yt's patient answer.



@podsvirov 
Note: I will convert this PR to draft status. Please revert to "ready for review" when you reply. Since you can't edit tags, this will let me know you've replied.

**Comment by podsvirov** [comment]
I think this discussion goes beyond the question of updating this package.
At least these questions didn't arise in #30090, #30495 and #30929.
I suggest just merge this update.

**Review by MonicaLiu0311 — APPROVED** [review]

**Pull request merged**
