### PR TITLE
[kfr] update to 5.2.0

### PR DESCRIPTION
**Pull request by miyanyan**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [ ] The "supports" clause reflects platforms that may be fixed by this new version
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [ ] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

kfr supports linux and arm, see https://github.com/kfrlib/kfr/blob/5.2.0/docs/docs/installation.md

### CODE REVIEW

**Comment by miyanyan** [comment]
the dft/dft-np feature needs clang, https://github.com/kfrlib/kfr/blob/5.2.0/CMakeLists.txt#L66
it seems that the feature is auto set, should we remove dft/dft-np in vcpkg.json?

**Comment by jimwang118** [comment]
> the dft/dft-np feature needs clang, https://github.com/kfrlib/kfr/blob/5.2.0/CMakeLists.txt#L66 it seems that the feature is auto set, should we remove dft/dft-np in vcpkg.json?

If you don't want to enable dft/dft-np, you can add -DKFR_ENABLE_DFT=OFF -DKFR_ENABLE_DFT_NP=OFF in vcpkg_cmake_configure.

**Comment by miyanyan** [comment]
> > the dft/dft-np feature needs clang, https://github.com/kfrlib/kfr/blob/5.2.0/CMakeLists.txt#L66 it seems that the feature is auto set, should we remove dft/dft-np in vcpkg.json?
> 
> If you don't want to enable dft/dft-np, you can add -DKFR_ENABLE_DFT=OFF -DKFR_ENABLE_DFT_NP=OFF in vcpkg_cmake_configure.

if enable dft，it will use clang to compile, maybe need set compiler in portfile.cmake https://github.com/kfrlib/kfr/blob/5.2.0/CMakeLists.txt#L225C6-L225C6

**Comment by jimwang118** [comment]
> if enable dft，it will use clang to compile, maybe need set compiler in portfile.cmake https://github.com/kfrlib/kfr/blob/5.2.0/CMakeLists.txt#L225C6-L225C6

Yes, if enabled, the compiler can be specified in portfile.cmake.

**Comment by miyanyan** [comment]
> Yes, if enabled, the compiler can be specified in portfile.cmake.

but it set clang, dft will auto enable, this's why I said `should we remove dft/dft-np in vcpkg.json`, https://github.com/kfrlib/kfr/blob/5.2.0/CMakeLists.txt#L66

**Comment by dg0yt** [comment]
The compiler must not be specified in `portfile.cmake`.

AFAIU 
`KFR_ENABLE_DFT` needs clang, but doesn't enable it.
Using clang changes the default value for `KFR_ENABLE_DFT`.
And dft-np depends on dft.

I would say that it makes sense to remove the feature control, and let the build system decide. It doesn't add dependencies, and it is default behaviour. However it is not so easy with the capi feature. 
So maybe leave the features as is, but add better error reporting, based on `vcpkg-cmake-get-vars`.

**Comment by jimwang118** [comment]
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

**Pull request closed without merging**
