### PR TITLE
[simdjson] Update to 0.3.1

### LINKED ISSUE #10145: Invalid link library for port simdjson found by find_library.
**Describe the bug**
With cmake function find_library, it returns an invalid path for libsimdjson.a.

**Environment**
- OS: Mac OS

**To Reproduce**
1. ./vcpkg install simdjson
2. in my project CMakeLists.txt, add 
```cmake
find_path(SIMDJSON_INCLUDE_DIR simdjson)
message("SIMDJSON_INCLUDE_DIR: ${SIMDJSON_INCLUDE_DIR}")
find_library(SIMDJSON_LIBRARY NAMES simdjson)
message("SIMDJSON_LIBRARY: ${SIMDJSON_LIBRARY}")

target_include_directories(main PUBLIC ${SIMDJSON_INCLUDE_DIR})
target_link_libraries(main ${SIMDJSON_LIBRARY})
```
got output
```
SIMDJSON_INCLUDE_DIR: .../vcpkg/installed/x64-osx/include
SIMDJSON_LIBRARY: .../vcpkg/installed/x64-osx/debug/lib/libsimdjson.a
```
3. compile project and got linker failures
4. change the last line of CMakeLists.txt to 
```cmake
target_link_libraries(main .../vcpkg/installed/x64-osx/lib/libsimdjson.a)
```
5. compile project and it succeeded

**Questions**
With find_library(SIMDJSON_LIBRARY NAMES simdjson), it returned SIMDJSON_LIBRARY with value .../vcpkg/installed/x64-osx/debug/lib/libsimdjson.a which failed. And the path ".../vcpkg/installed/x64-osx/lib/libsimdjson.a" succeeded.
1. What's the difference between the two libs and why the first one fails?
2. Why the function find_library doesn't find .../vcpkg/installed/x64-osx/lib/libsimdjson.a?

### PR DESCRIPTION
**Pull request by myd7349**
**Describe the pull request**

- What does your PR fix? Fixes issue https://github.com/simdjson/simdjson/issues/658, fixes #10145.

- Which triplets are supported/not supported? Have you updated the CI baseline?

It seems that simdjson supports `arm64` now.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

### CODE REVIEW

**Review by PhoebeHui — CHANGES_REQUESTED** [review]

**Comment by PhoebeHui** [comment]
simdjson:x64-uwp failed on CI testing, could you please have a look?

**Comment by myd7349** [comment]
> 
> 
> simdjson:x64-uwp failed on CI testing, could you please have a look?

Hi! I think I have finished this PR.

**Comment by myd7349** [comment]
> 
> 
> simdjson:x64-uwp failed on CI testing, could you please have a look?

Hi! @PhoebeHui Sorry for the long delay. I think I have finished PR.

**Review by PhoebeHui — APPROVED** [review]
Thanks for your updates!

**Review by dan-shaw — APPROVED** [review]

**Comment by dan-shaw** [comment]
LGTM, thanks @myd7349. Just merged another `simdjson` PR, could you resolve the conflicts?

**Comment by myd7349** [comment]
Hi! @dan-shaw I have resolved the conflicts. By specifing `-DSIMDJSON_SANITIZE=OFF`, the `Fix-error-LNK2001.patch` patch is unnecessary any more.

**Pull request merged**
