### PR TITLE
[azure-storage-cpp] Upgrade to 7.4.0

### PR DESCRIPTION
**Pull request by Jinming-Hu**
**Describe the pull request**

- What does your PR fix? Version upgrade

- Which triplets are supported/not supported? Have you updated the CI baseline? All triplets are supported. didn't update the CI baseline.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)? Yes

### CODE REVIEW

**Review by BillyONeal — APPROVED** [review]

**Review by NancyLi1013 — COMMENTED** [review]
Could you please update the way to handle copyright as 
```
file(INSTALL
    ${SOURCE_PATH}/LICENSE.txt
    DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
```
?

**Comment by JinmingHu-MSFT** [comment]
> Could you please update the way to handle copyright as
> 
> ```
> file(INSTALL
>     ${SOURCE_PATH}/LICENSE.txt
>     DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
> ```
> 
> ?

Done

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
LGTM now. @JinmingHu-MSFT  Thanks for this PR.

**Comment by strega-nil** [comment]
@Thanks @JinmingHu-MSFT :)

**Pull request merged**
