### PR TITLE
[kaldi] Add new port

### LINKED ISSUE #27544: [New Port Request] kaldi
Library name: kaldi

Library description: Kaldi is a toolkit for speech recognition, intended for use by speech recognition researchers and professionals.

Source repository URL: https://github.com/kaldi-asr/kaldi

Project homepage (if different from the source repository): http://kaldi-asr.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

deps on:

#27541

### PR DESCRIPTION
**Pull request by day253**
**Describe the pull request**

- #### What does your PR fix?
  Fixes #27544
  Related Works
  #27542
  #21479

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  all, Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by JonLiu1993** [comment]
Pinging @day253 for response. Is work still being done for this PR?

**Comment by day253** [comment]
> Pinging @day253 for response. Is work still being done for this PR?

sorry... The depends is #27542. I am learning to make port by autotool. Currently I works on #27922 and it will finish soon.

**Comment by JonLiu1993** [comment]
@day253, could you please fix the conflict files?

**Comment by JonLiu1993** [comment]
Pinging @day253 for response. Is work still being done for this PR?

**Comment by JonLiu1993** [comment]
Closing this PR since it seems that no progress is being made. Please ping us to reopen if work is still being done.

**Pull request closed without merging**
