### PR TITLE
[openssl-unix] Shared library support

### PR DESCRIPTION
**Pull request by lebdron**
Add shared library support for Linux and OSX

### CODE REVIEW

**Comment by Rastaban** [comment]
This change causes a failure in `thrift:x64-linux`.  Could you take a look at that?

**Comment by lebdron** [comment]
@Rastaban I compiled both current master and my current branch in a Ubuntu 19.10 container, and did not see any difference. The only "issue" with thrift is that it requires bison and flex to be installed in the system. Could you give more details?

**Comment by grdowns** [comment]
Hi @lebdron! Thanks for the PR. We've sorted out some CI problems we've been having and this change can go through now

**Pull request merged**
