### PR TITLE
[catch2] no absolute paths

### PR DESCRIPTION
**Pull request by autoantwort**
For https://github.com/microsoft/vcpkg/issues/20469

### CODE REVIEW

**Review by MonicaLiu0311 — DISMISSED** [review]

**Comment by BillyONeal** [comment]
Can you explain what this is doing? It looks like the intent here is much the opposite, to remove the prefix from any results?

https://github.com/catchorg/Catch2/blob/728de353be6a6d3658932bfc8e1ea5c7742a61c6/CMake/CatchMiscFunctions.cmake#L113-L120

**Comment by autoantwort** [comment]
I have created https://github.com/catchorg/Catch2/pull/2553

**Comment by BillyONeal** [comment]
Thanks!

**Pull request merged**
