### PR TITLE
[portaudio] Enable debug output

### PR DESCRIPTION
**Pull request by dechamps**
This is enabled by default in the original MSVC project in the PortAudio distribution, but not in their CMake build. This commit fixes the regression.

I don't think there are any performance concerns with this, as PortAudio (AFAICT) does not log from performance-critical code.

Note that this change might still be somewhat controversial, because PortAudio will by default dump its debug output directly to stderr, which is not particularly nice. However, the alternative is not having any way for end users to troubleshoot PortAudio issues at all, which IMHO is worse. Applications can always call `PaUtil_SetDebugPrintFunction()` to redirect the output away from stderr, and I encourage them to do so.

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for the PR!

I notice that this enables the debug output in release and debug -- was it enabled in release mode in the MSVC project?

**Comment by dechamps** [comment]
Yes, it was enabled in both modes in the original MSVC project. I think it makes sense to have it in Release mode, because the performance implications are negligible and in my experience it provides very useful output for troubleshooting on end user machines.

**Comment by ras0219-msft** [comment]
Thanks!

**Comment by stekyne** [comment]
Not sure I agree with this. That function PaUtil_SetDebugPrintFunction() can't be called via the headers installed by VCPKG so you're stuck with debug logging even in release builds. At least reduce it to only debug builds. This is not the kind of thing that should be enabled by default imo.

**Pull request merged**
