### PR TITLE
[sdformat6] Add new port 🤖

### PR DESCRIPTION
**Pull request by traversaro**
Add new port for the sdformat library (http://sdformat.org/).

The sdformat library is commonly used with the Ignition Robotics libraries (https://github.com/microsoft/vcpkg/pull/7781) and is a fundamental dependency of the Gazebo robotics simulator (https://github.com/microsoft/vcpkg/issues/8014).

### CODE REVIEW

**Comment by traversaro** [comment]
The Linux build is failing, but the "port build failure logs" are empty.

**Comment by traversaro** [comment]
The problem in Linux is apparently: 
~~~
CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:282 (message):
  Could not find ruby.  Please install it via your package manager.
Call Stack (most recent call first):
  ports/sdformat6/portfile.cmake:12 (vcpkg_find_acquire_program)
  scripts/ports.cmake:85 (include)
~~~
Any idea on how to solve it?

**Comment by traversaro** [comment]
@Rastaban thanks for installing ruby, i fixed the problem you reported in the latest commit.

**Review by Rastaban — APPROVED** [review]

**Comment by Rastaban** [comment]
The uwp failures look like they are by design to me (they call desktop only functions like CreateFileA) so I consider the tests passing at this point.

**Comment by traversaro** [comment]
The `uwp` failures are indeed due to missing upstream support, but the `arm64-windows` build could be easily fixed by using this patch in vcpkg port: https://bitbucket.org/osrf/sdformat/pull-requests/565/avoid-hardcoding-machine-x64-flag-on-64/diff .

**Pull request merged**
