### PR TITLE
Add VCPKG_(PRE|POST)_PORTFILE_INCLUDES for code injection before/after the portfile

### PR DESCRIPTION
**Pull request by Neumann-A**
This is basically needed for reproduceable builds. This allows injection of code which changes the created binaries to not have timestamps etc or implement further user controlled checks and policies.

The pre part is needed if the triplet ever gets changed to something easier to parse which is not cmake ;) 

probably needs changes to vcpkg-tool to hash these additional files. 

docs pr: https://github.com/microsoft/vcpkg-docs/pull/336
tool pr: https://github.com/microsoft/vcpkg-tool/pull/1417

- [ ] change variable name to `Z_VCPKG_POST_PORTFILE_INCLUDES` in ports.cmake after tool has been updated.

### CODE REVIEW

**Comment by Osyotr** [comment]
Now that we have `VCPKG_HASH_ADDITIONAL_FILES`, can it be properly reviewed?

**Review by Cheney-W — APPROVED** [review]

**Review by vicroms — CHANGES_REQUESTED** [review]
@BillyONeal
@data-queue
@JavierMatosD
@ras0219-msft
@vicroms

We discussed this PR during our meeting and have the following comments to make:

* Post-portfile injection is interesting for the example use case you mentioned (reproducible builds).

* Pre-portfile injection we don't see a motivation right now. Do you have a definitive use case in mind? Otherwise, we would like to wait until we have a use case for it.

* We noticed that pre-injection runs after port configs are included. So it might be used to override helper functions (but that can be done already with port overlays).

* All files included in `VCPKG_POST_PORTFILE_INCLUDES` should be "laundered" and hashed through the tool. The vcpkg tool should read the variable to validate the files, hash them, and then reinject them into the process (maybe using a `Z_VCPKG_UGLY_NAME` variable) so that the specified files are not changed during the build (for example, by `portfile.cmake`).

* This needs the usual documentation and tests.

**Comment by Neumann-A** [comment]
> Pre-portfile injection we don't see a motivation right now. Do you have a definitive use case in mind? Otherwise, we would like to wait until we have a use case for it.

Installing https://cmake.org/cmake/help/latest/command/variable_watch.html
or overriding any of
https://github.com/microsoft/vcpkg/blob/14b91796a68c87bc8d5cb35911b39287ccb7bd95/scripts/ports.cmake#L24-L125
without needing to use --x-scripts-root and copying all of the scripts to a different directory. 

> We noticed that pre-injection runs after port configs are included. So it might be used to override helper functions (but that can be done already with port overlays).

Wasn't the idea. The idea was to inject directly before/after the portfile as the name of the variable suggest. Some stuff does not work in the triplet (e.g. using `VCPKG_TARGET_IS_WINDOWS`, vcpkg function calls etc.). Best example to override for the pre injection is probably `vcpkg_find_acquire_program(<TOOL_NAME>)`

**Comment by BillyONeal** [comment]
> Wasn't the idea. The idea was to inject directly before/after the portfile as the name of the variable suggest. Some stuff does not work in the triplet (e.g. using `VCPKG_TARGET_IS_WINDOWS`, vcpkg function calls etc.). Best example to override for the pre injection is probably `vcpkg_find_acquire_program(<TOOL_NAME>)`

Can you show an example where someone would want to do that?

**Comment by Neumann-A** [comment]
> Can you show an example where someone would want to do that?

I cannot show an example I also noticed that overriding `vcpkg_find_acquire_program` is a bit more complex. I thought you could simply add `vcpkg_find_acquire_program(<NEW_TOOL_NAME>)` but no that doesn't work. (Due to `set(program_information "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/vcpkg_find_acquire_program(${program}).cmake")`, so it would require overwriting vcpkg_find_acquire_program itself .)
However, you could use it if `vcpkg_configure_make` (or any other) is broken for you (and vcpkg won't fix it due to backwards compat concerns) and you want to use old versions.  
Another interesting function to override could be `vcpkg_install_copyright` where it does some extra steps cleaning up the copyright or even extracting additional info which is then stored somewhere else in the tree.

**Comment by Osyotr** [comment]
> Can you show an example where someone would want to do that?

Overriding `vcpkg_from_*` is something people ask for from time to time.

**Comment by Neumann-A** [comment]
> Overriding vcpkg_from_* is something people ask for from time to time.

Can be done in the triplet.

**Comment by BillyONeal** [comment]
Thanks!

**Pull request merged**
