### PR TITLE
[oatpp] update to 1.2.5

### LINKED ISSUE #17599: [oatpp] update to 1.2.5
Library name: oatpp

New version number: 1.2.5

Release notes can be found at https://github.com/oatpp/oatpp/releases/tag/1.2.5

### PR DESCRIPTION
**Pull request by autoantwort**
**Describe the pull request**

- #### What does your PR fix?  
  Fixes  #17599

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

### CODE REVIEW

**Comment by JonLiu1993** [comment]
@autoantwort ,Thanks for your pr,according to the error display of CI, the components port of oatpp also needs to be upgraded along with oatpp. could you upgrade all components together in one pr?

**Comment by autoantwort** [comment]
I have the feeling that this release breaks more than it fixes :D

**Comment by autoantwort** [comment]
Finally the build is successful

**Comment by xanderdunn** [comment]
@autoantwort Are you finding any breakages other than Windows build? I opened the original issue #17504 because I am trying to troubleshoot oatpp/oatpp-openssl#7, which should be fixed in 1.2.5.

**Comment by autoantwort** [comment]
> @autoantwort Are you finding any breakages other than Windows build? I opened the original issue #17504 because I am trying to troubleshoot [oatpp/oatpp-openssl#7](https://github.com/oatpp/oatpp-openssl/issues/7), which should be fixed in 1.2.5.

Yeah I was only referring to the windows builds that needed some patches.

**Comment by xanderdunn** [comment]
Thanks a lot for getting it to build @autoantwort

**Review by JonLiu1993 — APPROVED** [review]

**Pull request merged**
