### PR TITLE
[quickcpplib] Update port to 2022-06-17

### LINKED ISSUE #26: Missing <cstring> include when building with vcpkg
I wasn't sure if I should report this here or on the outcome repo.
Anyway, building outcome 2.2.2-20211208 (the latest version available in vcpkg) produces the following compiler error:
```
include/quickcpplib/boost/test/unit_test.hpp:188:12: error: ‘strstr’ was not declared in this scope
  188 |         if(strstr(argv[n] + 2, "help"))
      |            ^~~~~~

include/quickcpplib/boost/test/unit_test.hpp:94:1: note: ‘strstr’ is defined in header ‘<cstring>’; did you forget to ‘#include <cstring>’?
   93 | #include "../../console_colours.hpp"
  +++ |+#include <cstring>
   94 | //#ifdef _WIN32
```
which is here: https://github.com/ned14/quickcpplib/blob/d2aa76116bff915ff1980c071b3e154295d0c0c7/include/quickcpplib/boost/test/unit_test.hpp#L189

(The list of include errors goes on.)

In b4b23064d1e8468b718efc2c8287b94a55035d10 this is fixed.
However, the errors still occur when building the latest version of outcome with vcpkg.
Is there any easy fix to this?

### PR DESCRIPTION
**Pull request by BurningEnlightenment**
**Describe the pull request**

- #### What does your PR fix?
  Fixes a build failure on GCC12 due to quickcpplib
  Fixes ned14/quickcpplib#26

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  unchanged, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

### CODE REVIEW

**Comment by ras0219-msft** [comment]
+@ned14 for review

Also, I think we should move the versioning of `ned14-internal-quickcpplib` over to `version-date` since git commit ids won't sort correctly. Our policy for that is "date of access", not "date listed in the commit", so it would be `"version-date": "2022-06-10"`.

**Comment by BurningEnlightenment** [comment]
> Also, I think we should move the versioning of `ned14-internal-quickcpplib` over to `version-date` since git commit ids won't sort correctly. 

Is that a blocker? The diff https://github.com/ned14/quickcpplib/compare/cad832c8083c8eb984c26ee995609817f27f9847...d2aa76116bff915ff1980c071b3e154295d0c0c7 is rather small and I would like to get that bugfix in sooner than later, because it blocks building `outcome` and `llfio` with GCC12.

I'd open a seperate issue/PR for the versioning change (discussion) if desired.

**Comment by ras0219-msft** [comment]
The version change is not blocking, but I want to wait at least 7 days for @ned14 to have a chance to review. If you would consider making that change in the meantime it would be great, but it won't prevent merging after the sooner of {7 days, @ned14 review}.

**Comment by BurningEnlightenment** [comment]
I added the new two commits from yesterday which contain two more bugfixes (including ned14/quickcpplib#27)

**Comment by BurningEnlightenment** [comment]
@ras0219-msft can we get this merged now?

**Pull request merged**
