### PR TITLE
Update vcpkg tool, add windows-arm64, and download rather than build on some POSIX

### PR DESCRIPTION
**Pull request by BillyONeal**
See the new vcpkg-tool version: https://github.com/microsoft/vcpkg-tool/releases/tag/2021-10-25

Resolves:

* https://github.com/microsoft/vcpkg/issues/16850 (I think)
* https://github.com/microsoft/vcpkg/issues/20993
* https://github.com/microsoft/vcpkg/issues/18615
* https://github.com/microsoft/vcpkg/issues/20982

### CODE REVIEW

**Comment by BillyONeal** [comment]
> I think you should change a central file to trigger a world rebuild.

I'm going to trigger a CI run for that :)

**Comment by BillyONeal** [comment]
Something is messed up because it isn't honoring `--exclude`, for instance libressl is being built even though it is set to skip in ci.baseline.txt. Debugging....

**Comment by BillyONeal** [comment]
> Something is messed up because it isn't honoring `--exclude`, for instance libressl is being built even though it is set to skip in ci.baseline.txt. Debugging....

It was https://github.com/microsoft/vcpkg-tool/pull/224

**Comment by BillyONeal** [comment]
Full CI run is https://dev.azure.com/vcpkg/public/_build/results?buildId=61657&view=results

**Comment by BillyONeal** [comment]
Ahem, I mean https://dev.azure.com/vcpkg/public/_build/results?buildId=61678&view=results

**Comment by autoantwort** [comment]
I currently getting:
```
parallels@debian-gnu-linux-10:~/git_projects/vcpkg$ ./bootstrap-vcpkg.sh 
Downloading vcpkg-glibc...
Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md
parallels@debian-gnu-linux-10:~/git_projects/vcpkg$ ./vcpkg 
bash: ./vcpkg: cannot execute binary file: Exec format error
```
I assume it downloads a x64 binary for arm64?

**Review by vicroms — APPROVED** [review]

**Comment by BillyONeal** [comment]
PASSING, REMOVE FROM FAIL LIST: hpx:x64-linux (.\scripts\ci.baseline.txt)

Yay!

REGRESSION: log4cxx:x64-osx. If expected, add log4cxx:x64-osx=fail to .\scripts\ci.baseline.txt.

```
Building package log4cxx[core]:x64-osx...
-- Downloading https://archive.apache.org/dist/logging/log4cxx/0.12.0/apache-log4cxx-0.12.0.tar.gz -> apache-log4cxx-0.12.0.tar.gz...
-- Extracting source /Users/vagrant/Data/downloads/apache-log4cxx-0.12.0.tar.gz
-- Applying patch expat.patch
-- Applying patch linux.patch
-- Applying patch pkgconfig.patch
-- Using source at /Users/vagrant/Data/buildtrees/log4cxx/src/0.12.0-99c0951785.clean
-- Found external ninja('1.10.2').
-- Configuring x64-osx-dbg
-- Configuring x64-osx-rel
-- Building x64-osx-dbg
-- Building x64-osx-rel
-- Fixing pkgconfig file: /Users/vagrant/Data/packages/log4cxx_x64-osx/lib/pkgconfig/liblog4cxx.pc
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:78 (message):
  /usr/local/bin/pkg-config --exists liblog4cxx failed with error code: 1

      ENV{PKG_CONFIG_PATH}: "/Users/vagrant/Data/packages/log4cxx_x64-osx/lib/pkgconfig:/Users/vagrant/Data/packages/log4cxx_x64-osx/share/pkgconfig:/Users/vagrant/Data/installed/x64-osx/lib/pkgconfig:/Users/vagrant/Data/installed/x64-osx/share/pkgconfig"
      output: Package 'liblog4cxx' has no Name: field
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:201 (z_vcpkg_fixup_pkgconfig_check_files)
  ports/log4cxx/portfile.cmake:31 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:142 (include)
```

Looks like this port is making bad pkgconfig files, but that's not a regression from this change.

PASSING, REMOVE FROM FAIL LIST: ompl:x64-linux (.\scripts\ci.baseline.txt)
PASSING, REMOVE FROM FAIL LIST: ompl:x64-osx (.\scripts\ci.baseline.txt)
REGRESSION: omplapp:x64-linux. If expected, add omplapp:x64-linux=fail to .\scripts\ci.baseline.txt.
REGRESSION: omplapp:x64-osx. If expected, add omplapp:x64-osx=fail to .\scripts\ci.baseline.txt.

ompl is fixed and now things that depend on it are broken, so not a regression from this change.

REGRESSION: qca:x64-linux. If expected, add qca:x64-linux=fail to .\scripts\ci.baseline.txt.
REGRESSION: qca:x64-osx. If expected, add qca:x64-osx=fail to .\scripts\ci.baseline.txt.
REGRESSION: qca:x64-windows
REGRESSION: qca:x64-windows-static
REGRESSION: qca:x86-windows

```
  Imported target "PkgConfig::BOTAN" includes non-existent path

    "D:/installed/x86-windows/lib/pkgconfig/../../include/botan-2"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

This looks like an incorrectly working optional dependency in qca that causes it to fail if botan is also installed, not a regression from this change.

REGRESSION: rtaudio:x64-linux. If expected, add rtaudio:x64-linux=fail to .\scripts\ci.baseline.txt.

```
[12/20] : && /usr/bin/c++ -fPIC -Wall -Werror -g  tests/CMakeFiles/playsaw.dir/playsaw.cpp.o -o tests/playsaw  librtaudio.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libasound.a  -lpthread && :
FAILED: tests/playsaw 
: && /usr/bin/c++ -fPIC -Wall -Werror -g  tests/CMakeFiles/playsaw.dir/playsaw.cpp.o -o tests/playsaw  librtaudio.a  /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libasound.a  -lpthread && :
/usr/bin/ld: /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libasound.a(dlmisc.o): in function `snd_dlinfo_origin':
/mnt/vcpkg-ci/buildtrees/alsa/x64-linux-dbg/src/.././../src/v1.2.5.1-98fc6d1525.clean/src/dlmisc.c:72: undefined reference to `dladdr1'
/usr/bin/ld: /mnt/vcpkg-ci/buildtrees/alsa/x64-linux-dbg/src/.././../src/v1.2.5.1-98fc6d1525.clean/src/dlmisc.c:74: undefined reference to `dlinfo'
/usr/bin/ld: /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libasound.a(dlmisc.o): in function `__snd_dlopen':
/mnt/vcpkg-ci/buildtrees/alsa/x64-linux-dbg/src/.././../src/v1.2.5.1-98fc6d1525.clean/src/dlmisc.c:155: undefined reference to `dlopen'
/usr/bin/ld: /mnt/vcpkg-ci/buildtrees/alsa/x64-linux-dbg/src/.././../src/v1.2.5.1-98fc6d1525.clean/src/dlmisc.c:161: undefined reference to `dlerror'
/usr/bin/ld: /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libasound.a(dlmisc.o): in function `snd_dlclose':
/mnt/vcpkg-ci/buildtrees/alsa/x64-linux-dbg/src/.././../src/v1.2.5.1-98fc6d1525.clean/src/dlmisc.c:191: undefined reference to `dlclose'
/usr/bin/ld: /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libasound.a(dlmisc.o): in function `snd_dlsym_verify':
/mnt/vcpkg-ci/buildtrees/alsa/x64-linux-dbg/src/.././../src/v1.2.5.1-98fc6d1525.clean/src/dlmisc.c:221: undefined reference to `dlsym'
/usr/bin/ld: /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libasound.a(dlmisc.o): in function `snd_dlsym':
/mnt/vcpkg-ci/buildtrees/alsa/x64-linux-dbg/src/.././../src/v1.2.5.1-98fc6d1525.clean/src/dlmisc.c:269: undefined reference to `dlsym'
/usr/bin/ld: /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libasound.a(pcm_ladspa.o): in function `snd_pcm_ladspa_free_plugins':
/mnt/vcpkg-ci/buildtrees/alsa/x64-linux-dbg/src/pcm/../.././../src/v1.2.5.1-98fc6d1525.clean/src/pcm/pcm_ladspa.c:188: undefined reference to `dlclose'
/usr/bin/ld: /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libasound.a(pcm_ladspa.o): in function `snd_pcm_ladspa_check_file':
/mnt/vcpkg-ci/buildtrees/alsa/x64-linux-dbg/src/pcm/../.././../src/v1.2.5.1-98fc6d1525.clean/src/pcm/pcm_ladspa.c:1094: undefined reference to `dlopen'
/usr/bin/ld: /mnt/vcpkg-ci/buildtrees/alsa/x64-linux-dbg/src/pcm/../.././../src/v1.2.5.1-98fc6d1525.clean/src/pcm/pcm_ladspa.c:1096: undefined reference to `dlsym'
/usr/bin/ld: /mnt/vcpkg-ci/buildtrees/alsa/x64-linux-dbg/src/pcm/../.././../src/v1.2.5.1-98fc6d1525.clean/src/pcm/pcm_ladspa.c:1114: undefined reference to `dlclose'
/usr/bin/ld: /mnt/vcpkg-ci/buildtrees/alsa/x64-linux-dbg/src/pcm/../.././../src/v1.2.5.1-98fc6d1525.clean/src/pcm/pcm_ladspa.c:1131: undefined reference to `dlclose'
/usr/bin/ld: /mnt/vcpkg-ci/buildtrees/alsa/x64-linux-dbg/src/pcm/../.././../src/v1.2.5.1-98fc6d1525.clean/src/pcm/pcm_ladspa.c:1139: undefined reference to `dlclose'
/usr/bin/ld: /mnt/vcpkg-ci/installed/x64-linux/debug/lib/libasound.a(pcm_meter.o): in function `snd_pcm_meter_add_scope_conf':
/mnt/vcpkg-ci/buildtrees/alsa/x64-linux-dbg/src/pcm/../.././../src/v1.2.5.1-98fc6d1525.clean/src/pcm/pcm_meter.c:676: undefined reference to `dlsym'
collect2: error: ld returned 1 exit status
```

Don't know exactly what this is but doesn't look related.

**Comment by Neumann-A** [comment]
The last one is a) missing explicit dependency on alsa and b) missing linkage to dl.

**Pull request merged**
