### PR TITLE
[osg] Add feature examples and plugins, fix configure options

### PR DESCRIPTION
**Pull request by JackBoosY**
This PR will:
- [x] Fix conflicts between dependencies sdl1 and sdl2.
- [x] Add feature examples.
- [x] Add feature plugins.
- [x] Add feature tools.
- [x] Add feature packages.
- [x] Add feature docs.

Related: #10051.

Note: All features passed in the following triplets test:
- x86-windows
- x64-windows-static

### CODE REVIEW

**Comment by PhoebeHui** [comment]
osg:x64-windows-static failed om CI testing.

**Comment by vicroms** [comment]
Fails during post-build validations

```
There should be no empty directories in C:\vsts\_work\4\s\packages\osg_x64-windows-static
The following empty directories were found:

    C:/vsts/_work/4/s/packages/osg_x64-windows-static/tools/osg

If a directory should be populated but is not, this might indicate an error in the portfile.
If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:

    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/a/dir" "${CURRENT_PACKAGES_DIR}/some/other/dir")


Found 1 error(s). Please correct the portfile:
    C:\vsts\_work\4\s\ports\osg\portfile.cmake
-- Performing post-build validation done
```

**Comment by JackBoosY** [comment]
@vicroms I will fix it tomorrow.

**Review by PhoebeHui — APPROVED** [review]

**Comment by Voskrese** [comment]
```
CMake Error at ports/osg/portfile.cmake:106 (if):
  if given arguments:

    "NO" "EXISTS" "E:/tools/vcpkg/packages/osg_x64-windows/tools/osg"

  Unknown arguments specified
Call Stack (most recent call first):
  scripts/ports.cmake:90 (include)
```

ports/osg/portfile.cmake:106 and 121 str

**if (NO** EXISTS ${OSG_TO -->> **if(NOT** EXISTS ${OSG_TO ?

**Comment by dan-shaw** [comment]
@JackBoosY It appears that osg-qt is failing

**Comment by NancyLi1013** [comment]
Related issue #10320

**Comment by JackBoosY** [comment]
@dan-shaw The reasons for the osg-qt build failure is:
```
CMake Error at /ci/myagent/_work/1/s/installed/x64-linux/share/cmake/Qt5Gui/Qt5GuiConfig.cmake:15 (message):
  The imported target "Qt5::Gui" references the file

     "/ci/myagent/_work/3/s/installed/x64-linux/lib/libEGL.so"

  but this file does not exist.  Possible reasons include:
  * The file was deleted, renamed, or moved to another location.
  * An install or uninstall procedure did not complete successfully.
  * The installation package was faulty and contained
```

Please note that the path of this library is _/ci/myagent/_work/3/s_ but the current ci test path is _/ci/myagent/_work/1/s_.
So I guess this is because the library is permanently archived on the pipeline machine, and using the library is provided by cmake file _Qt5GuiConfig.cmake_, which causes the issue to occur.

Please check on the pipeline machine, we may need to delete the related files on all pipeline machines.

**Comment by JackBoosY** [comment]
@dan-shaw Seems okay now.

**Pull request merged**
