### PR TITLE
[lua] Fix compiler error of lua[tools]

### LINKED ISSUE #29896: Compiler error of lua[tools]
**Describe the bug**
When install lua[tools] on linux the compilation does not work any more since portfix https://github.com/microsoft/vcpkg/pull/28027

**Environment**
- OS: Linux Ubuntu WSL
- Compiler: cmake version 3.24.0

**To Reproduce**
1. ./vcpkg install lua[tools]

**Expected behavior**
The lua[tools] should compile without errors

**Failure logs**
[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/10839366/install-x64-linux-dbg-out.log)

### PR DESCRIPTION
**Pull request by TobiasFunk**
What does your PR fix?
Fixes #29896

Which triplets are supported? Have you updated the CI baseline?
Linux, No

Does your PR follow the maintainer guide?
Yes

If you have added/updated a port: Have you run ./vcpkg x-add-version --all and committed the result?
Yes

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
~~- [] SHA512s are updated for each updated download~~
~~- [ ] The "supports" clause reflects platforms that may be fixed by this new version~~
~~- [] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
~~- [] Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by TobiasFunk** [comment]
> @TobiasFunk please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by TobiasFunk** [comment]
> @TobiasFunk please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by Adela0814** [comment]
@TobiasFunk  I encountered the following issue when testing the features of `lua`:
Repro steps: `vcpkg install lua[tools]:x64-linux`
Failure log: [install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/10846066/install-x64-linux-dbg-out.log)

**Comment by dg0yt** [comment]
This `CMakeLists.txt`... :roll_eyes: 

Can you please fix the redundancy:
- We need only one `FIND_LIBRARY (LIB_MATH NAMES m)`.
- We need only one `TARGET_LINK_LIBRARIES (lua m)`.

**Comment by TobiasFunk** [comment]
> @TobiasFunk I encountered the following issue when testing the features of `lua`: Repro steps: `vcpkg install lua[tools]:x64-linux` Failure log: [install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/10846066/install-x64-linux-dbg-out.log)

oh sorry i had a typo in the cmakefile (the duplicated TARGET_LINK_LIBRARIES (lua m) instead of TARGET_LINK_LIBRARIES (luac m))

thats actually the exact error i want to fix

**Review by Adela0814 — APPROVED** [review]

**Pull request merged**
