### PR TITLE
[Qt] Update to 6.5.0

### LINKED ISSUE #30778: [qt6] update to 6.5.0
### Library name

Qt

### New version number

6.5.0

### Other information that may be useful (release notes, etc...)

https://www.qt.io/blog/qt-6.5-lts-released

This applies to the whole stack I assume, most important would be qtbase for me.

### PR DESCRIPTION
**Pull request by Neumann-A**
It's late.... just let CI do the work and come back the next day ;)

- [x] depends https://bugreports.qt.io/browse/QTBUG-109639 (`qtwebengine` regression)

### CODE REVIEW

**Comment by Neumann-A** [comment]
@FrankXie05: Please also add the tag: "depends CI update" or however it is called

**Comment by Neumann-A** [comment]
spix -> Needs a source fix
rtabmap -> needs a dependency deploy fix (maybe just translation stuff missing?)

**Comment by janhenke** [comment]
Hi, thanks for your work. What is missing in order to get this merged?

**Comment by Neumann-A** [comment]
> What is missing in order to get this merged?

Fixing rtabmap and spix.

**Comment by jhenkehd** [comment]
Looks like one test of qtopcua is failing on some platforms.

**Comment by jhenkehd** [comment]
Now there is at least one rtabmap failure

**Comment by jhenkehd** [comment]
Unfortunately rtabmap still does not build

> CMake Error at ports/rtabmap/portfile.cmake:126 (file):
  file COPY cannot find
  "D:/packages/rtabmap_x86-windows/tools/Qt6/bin/qt.conf": File exists.
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)
>
>
> error: building rtabmap:x86-windows failed with: BUILD_FAILED
Elapsed time to handle rtabmap:x86-windows: 20 min
Total install time: 22 min

**Comment by janhenke** [comment]
@Neumann-A Thanks for your work, now everything passed. Only this PR is still marked as a draft.

**Comment by FrankXie05** [comment]
Please resolve the file conflicts. @Neumann-A

**Review by FrankXie05 — DISMISSED** [review]

**Review by FrankXie05 — DISMISSED** [review]

**Comment by janhenke** [comment]
Unfortunately this branch now has merge conflicts again, due to what got merged in the mean time. Is there any way to draw attention to this PR so it gets merged quickly, once these conflicts get resolved?

**Comment by janhenke** [comment]
qttools seems to be broken now, I really hope someone can merge this, before more rebasining is required due to changes in master

**Comment by jhenkehd** [comment]
How can we draw attention to this merge request to get it merged? I fear it gets forgotten in the long list of open merge request.

**Review by BillyONeal — APPROVED** [review]
Thanks so much!

**Review by FrankXie05 — APPROVED** [review]

**Pull request merged**
