### PR TITLE
[gtest] Fix clang-tidy error in gtest

### PR DESCRIPTION
**Pull request by kysucix**
**Describe the pull request**

- #### What does your PR fix?
  Fixes clang-tidy in gtest, marked as "won't fix" by the maintainers: https://github.com/google/googletest/issues/3553

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
all, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
I didn't add or update any port.

### CODE REVIEW

**Comment by LilyWangLL** [comment]
Thanks for your PR. Please update the port's version fields and then run:
```
    vcpkg x-add-version gtest
    git add versions
    git commit -m "Update version database"
```

**Comment by dg0yt** [comment]
Does clang-tidy run as part of a port build? Can't it be turned off? It is helpful during development, not during packaging.

**Comment by kysucix** [comment]
> Thanks for your PR. Please update the port's version fields and then run:
> 
> ```
>     vcpkg x-add-version gtest
>     git add versions
>     git commit -m "Update version database"
> ```

Ops I missed that, it's not updated the port version.

**Comment by kysucix** [comment]
> Does clang-tidy run as part of a port build? Can't it be turned off? It is helpful during development, not during packaging.

Clang-tidy is not strictly part of the port build but it's failing only for that one single missing line, otherwise the gtest codebase is already containing tons of NOLINT lines.

**Comment by dg0yt** [comment]
So it affects you when you use the port, not when you build the port?

**Comment by strega-nil-ms** [comment]
@kysucix can you try upstreaming the patch? I imagine they'd be okay with receiving this patch since it's so simple.

I'm also totes okay with merging as is, thanks!

**Comment by kysucix** [comment]
@strega-nil-ms Sure I'll try to upstream the patch.

**Pull request merged**
