### PR TITLE
[directx-dxc, directxtk12] update port for July 2022 release and native ARM64 support

### PR DESCRIPTION
**Pull request by walbourn**
This updates the **directx-dxc** port for the July 2022 release of the DirectX DXC Compiler on GitHub. This release adds arm64 native support in addition to x64.

This includes an upstream hot-fix to **directxtk12**

### CODE REVIEW

**Comment by walbourn** [comment]
I don't understand why the arm64-windows failed. The vcpkg.json for directxtk12 lists host: true for directx-dxc, so it should have used the x64-windows version of directx-dxc.

```
    vcpkg-cmake:x64-windows: SUCCEEDED: 4.693 ms
    vcpkg-cmake-config:x64-windows: SUCCEEDED: 2.794 ms
    directx-headers:arm64-windows: SUCCEEDED: 14.88 ms
    directx-dxc:arm64-windows: SUCCEEDED: 4.415 s
    directx-dxc:x64-windows: SUCCEEDED: 50.44 ms
    directxmath:arm64-windows: SUCCEEDED: 7.456 ms
    directxtk12:arm64-windows: BUILD_FAILED: 2.642 s
```

Can someone look at the logs more to see why it failed?  Locally it builds fine using:

```
The following packages will be built and installed:
  * directx-dxc[core]:x64-windows -> 2022-07-13
  * directx-headers[core]:arm64-windows -> 1.602.0
  * directxmath[core]:arm64-windows -> 2022-05-18
    directxtk12[core,xaudio2-9]:arm64-windows -> 2022-06-15
  * vcpkg-cmake[core]:x64-windows -> 2022-07-02
  * vcpkg-cmake-config[core]:x64-windows -> 2022-02-06#1
```

**Comment by Cheney-W** [comment]
Because `directx-dxc` has been modified, all its supported triplets will be tested in CI, which is expected. And `directx-dxc:x64-windows` being installed is proof that host:true is working.
You can understand it this way, there are two ports that need to be tested:
1. directx-dxc (All supported trilpets are installed)
2. directxtk12 (Because it depends on directx-dxc, it will be tested. While installing it, host true worked, so `directx-dxc:x64-windows` was installed)

Please use following command to reproduce the failure in arm64-windows:
`.\vcpkg.exe install directx-dxc:arm64-windows directxtk12:arm64-windows`

Failure log:
[install-arm64-windows-dbg-err.log](https://dev.azure.com/vcpkg/_apis/resources/Containers/17568396/failure%20logs%20for%20arm64-windows?itemPath=failure%20logs%20for%20arm64-windows%2Fdirectxtk12%2Finstall-arm64-windows-dbg-err.log)
`This version of D:\installed\arm64-windows\tools\directx-dxc\dxc.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.`

**Comment by walbourn** [comment]
Working a fix for upstream.

**Comment by Cheney-W** [comment]
I saw you have update the upstream, are we currently waiting for the new `DirectXTK12` to be released or giving a patch to the `DirectXTK12` on vcpkg?

**Comment by walbourn** [comment]
I am trying to resolve some MinGW issues in directxk12 related to updating the DirectX headers port as well.

**Comment by walbourn** [comment]
@Cheney-W Have an upstream fix in place, and it builds now.

**Comment by BillyONeal** [comment]
Thanks :)

**Pull request merged**
