### PR TITLE
[ninja] new port ninja

### PR DESCRIPTION
**Pull request by Neumann-A**
If possible: Could vcpkg internal ninja be replaced with this one or detect that this one was installed and use it instead? ~~(hmm on windows it got pickuped automatically but not on linux. strange)~~ screw that must have done something so that it automatically used it.

### CODE REVIEW

**Comment by Neumann-A** [comment]
UWP Error:
`LINK : fatal error LNK1104: cannot open file 'libcpmt.lib'`

Does somebody know how to solve that one on UWP platforms?

**Comment by Neumann-A** [comment]
@ras0219-msft according to PR 1098 you are probably interested in this one

**Comment by cbezault** [comment]
So the only thing that failed was UWP. I'm sort of okay with that as people aren't really compiling things on UWP, just compiling things for UWP.

**Comment by cbezault** [comment]
For now I think we shouldn't have vcpkg auto-detect this is installed and just use it. I'd rather not deal with the flood of issues that will probably result, we want deterministic and consistent builds. However, if a port absolutely needs a newer/different version of ninja than what we ship we should make sure it's easy to switch to ninja built by this port.

**Comment by Neumann-A** [comment]
Then there is nothing more to do for this PR and it could be merged.

**Comment by cbezault** [comment]
We're considering taking #1098 over this port and using the precompiled ninja binaries from kitware that work with Fortran instead of the ones we currently download.

**Comment by Neumann-A** [comment]
@cbezault Please do as you like as long as it does not take another two years to get it into VCPKG master ;)
I just wanted to offer an alternative for faster Fortran integration.

**Comment by cbezault** [comment]
Yeah if it looks like it's going to take a significant amount of time to move forward on the fortran PR we might take this one. We just feel that it's not appropriate to have tools as ports and have been discussing maybe adding a new port category for them.

**Comment by Neumann-A** [comment]
closing in favor of #6860

**Pull request closed without merging**
