### PR TITLE
[VMSS] Delete recursive windows initialize-environment

### PR DESCRIPTION
**Pull request by MVoz**
> windows\initialize-environment.ps1 : Exception calling "Delete" with "1" 
> [error]argument(s): "The directory is not empty.

test PORT mpir

### CODE REVIEW

**Comment by JackBoosY** [comment]
Is this PR only for testing?

**Comment by Voskrese** [comment]
@JackBoosY 
can merge

**Review by JackBoosY — APPROVED** [review]

**Review by BillyONeal — CHANGES_REQUESTED** [review]
This seems broken -- deleting a directory symlink should not delete contents of the target.

**Comment by Voskrese** [comment]
deleting directories will cause deletion symlink

**Comment by BillyONeal** [comment]
I believe https://github.com/microsoft/vcpkg/pull/11432 is the correct fix.

**Pull request closed without merging**
