### PR TITLE
[vcpkg] Add tab completion for Fish

### PR DESCRIPTION
**Pull request by Link1J**
Adds tab completion for Fish.
Fish is shell, like bash, but is not fully POSIX compliant.

### CODE REVIEW

**Comment by BillyONeal** [comment]
1. I'm not sure if we should offer autocomplete for `x-` options and commands since those aren't intended to be contractual
2. Since this would be a community supported thing, should we name the whole thing `vcpkg integrate install x-fish` or something like that?

**Comment by Link1J** [comment]
Here is my opinion on the points laid out.
1. Removing the `x-` options makes sense, and will likely be something I will do.
2. a) I don't think using `x-` for community supported items makes sense, but something like `c-` would. 
2. b) The `install` part should be used for all of the tab-completes, if it is added. I don't think it should.

**Comment by BillyONeal** [comment]
> Here is my opinion on the points laid out.
> 
> 1. Removing the `x-` options makes sense, and will likely be something I will do.

Thanks!

> 2. a) I don't think using `x-` for community supported items makes sense, but something like `c-` would.

Sorry, I should clarify: `x-` is a marker that the command's behavior might change in the future without warning, and we want the community to have the power to so change features they contribute. I don't think we would want a different prefix there.

> 3. b) The `install` part should be used for all of the tab-completes, if it is added. I don't think it should.

Ah, you're right, I messed that up. Pretend I said `vcpkg integrate x-fish` :)

**Comment by Link1J** [comment]
Oh, I misunderstood what `x-` meant.
I have made the changes.

**Comment by BillyONeal** [comment]
@strega-nil @ras0219 and I met today and confirmed that we like doing this feature; dropping requires:discussion

**Review by strega-nil — APPROVED** [review]
Approving as a simple, experimental fish support :)

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
