### PR TITLE
[seasocks] New port

### PR DESCRIPTION
**Pull request by chausner**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [x] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by VEERASEKHAR-GIT** [comment]
curl -I https://repology.org/metapackage/your_package_name
npm install
pip install -r requirements.txt
so noe  Rerun the command to fix the version database.
./vcpkg x-add-version --all

**Comment by chausner** [comment]
@VEERASEKHAR-GIT I am not quite sure I understand.

**Comment by FrankXie05** [comment]
```
PS F:\usage\build> cmake --build .
MSBuild version 17.6.3+07e294721 for .NET Framework

1>Checking Build System
Building Custom Rule F:/usage/CMakeLists.txt
main.cpp

F:\test\vcpkg\installed\x64-windows\include\seasocks/WebSocket.h(33,10): 
fatal  error C1083: Cannot open include fil e: '../../../win32/win_unistd.h': No such file or directory [F:\usage\build\main.vcxproj] 
```
We need to install `win_unistd.h`, otherwise we cannot support `WIN32`.

https://github.com/mattgodbolt/seasocks/blob/7155ad2946ea454245051f3a915ea1bc1ff4cf6c/src/main/c/seasocks/WebSocket.h#L33
https://github.com/mattgodbolt/seasocks/blob/7155ad2946ea454245051f3a915ea1bc1ff4cf6c/src/main/c/CMakeLists.txt#L8

**Comment by FrankXie05** [comment]
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". 
          That way, I can be aware that you've responded since you can't modify the tags.

**Comment by chausner** [comment]
@FrankXie05 Good point. Since this issue requires larger changes, I opened a [PR](https://github.com/mattgodbolt/seasocks/pull/193) in the upstream repo with a fix, and disabled Windows support for now until the fix is merged and a new version released.

**Comment by FrankXie05** [comment]
I think the upstream wants to install all the header files, but some may be missing due to certain conditions or path problems.
https://github.com/mattgodbolt/seasocks/blob/7155ad2946ea454245051f3a915ea1bc1ff4cf6c/src/main/c/CMakeLists.txt#L115

**Review by dan-shaw — APPROVED** [review]

**Pull request merged**
