### PR TITLE
[zstd] Add "tools" feature

### LINKED ISSUE #30163: [zstd] add option to build zstd binary
Hi,

I would like to use the zstd binary in tests when building with zstd support. Unfortunately vcpkg port of zstd does not build the zstd binary.

Hence I'd like to add the option to build programs to the zstd port. Would a pull request implementing that have a chance to be accepted?

Regards,

Andres

### PR DESCRIPTION
**Pull request by anarazel**
Fixes: #30163

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Review by JonLiu1993 — DISMISSED** [review]

**Comment by JonLiu1993** [comment]
@anarazel, Thanks for your PR, when I tested the feature by command `./vcpkg install zstd[tools]:x86-windows` I get this error:
````
-- CMAKE_INSTALL_PREFIX: F:/Feature-test/zstd/vcpkg/packages/zstd_x86-windows
-- CMAKE_INSTALL_LIBDIR: lib
-- ZSTD_LEGACY_SUPPORT defined!
-- ZSTD_MULTITHREAD_SUPPORT is enabled
CMake Error at CMakeLists.txt:149 (message):
  You need to build static library to build zstd CLI
````

then I tested feature by command `./vcpkg install zstd[tools]:x64-windows-static` I get this error:
````
-- Performing post-build validation
warning: The following EXEs were found in /bin or /debug/bin. EXEs are not valid distribution targets.

    F:\Feature-test\zstd\vcpkg\packages\zstd_x64-windows-static\bin\zstd.exe

warning: The following EXEs were found in /bin or /debug/bin. EXEs are not valid distribution targets.

    F:\Feature-test\zstd\vcpkg\packages\zstd_x64-windows-static\debug\bin\zstd.exe

warning: There should be no bin\ directory in a static build, but F:\Feature-test\zstd\vcpkg\packages\zstd_x64-windows-static\bin is present.
warning: There should be no debug\bin\ directory in a static build, but F:\Feature-test\zstd\vcpkg\packages\zstd_x64-windows-static\debug\bin is present.
warning: If the creation of bin\ and/or debug\bin\ cannot be disabled, use this in the portfile to remove them
    if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")
        file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/bin" "${CURRENT_PACKAGES_DIR}/debug/bin")
    endif()

error: Found 3 post-build check problem(s). To submit these ports to curated catalogs, please first correct the portfile: F:\Feature-test\zstd\vcpkg\ports\zstd\portfile.cmake
Stored binary cache: "C:\Users\vzhli17\AppData\Local\vcpkg\archives\94\94c0f48c35d0c5e3678189c7d0c6fe2b41d157176a39d737b0edc887e4b65ce7.zip"
Elapsed time to handle zstd:x64-windows-static: 20.15 s
Total install time: 22.43 s
The package zstd provides CMake targets:

    find_package(zstd CONFIG REQUIRED)
    target_link_libraries(main PRIVATE $<IF:$<TARGET_EXISTS:zstd::libzstd_shared>,zstd::libzstd_shared,zstd::libzstd_static>)
````

**Comment by anarazel** [comment]
```
warning: There should be no bin\ directory in a static build, but F:\Feature-test\zstd\vcpkg\packages\zstd_x64-windows-static\bin is present.
warning: There should be no debug\bin\ directory in a static build, but F:\Feature-test\zstd\vcpkg\packages\zstd_x64-windows-static\debug\bin is present.
warning: If the creation of bin\ and/or debug\bin\ cannot be disabled, use this in the portfile to remove them
```
Hm. Looking around a bit more, I guess zstd.exe should  be in tools/?

> CMake Error at CMakeLists.txt:149 (message):
> You need to build static library to build zstd CLI

Looks like the easiest thing will be to just build the library parts as part of zstd in that case.

**Comment by anarazel** [comment]
> Looks like the easiest thing will be to just build the library parts as part of zstd in that case.

Actually, seems like this should turn on ZSTD_PROGRAMS_LINK_SHARED?

**Comment by anarazel** [comment]
> Actually, seems like this should turn on ZSTD_PROGRAMS_LINK_SHARED?

Except that doesn't work - it's been broken in zstd for a while: https://github.com/facebook/zstd/issues/3554


Aside from that getting fixed I can see two potential ways out: 
1) Build the static lib, but avoid installing it. 
2) patch cmake build to add ${LIBRARY_DIR}/common/pool.c ${LIBRARY_DIR}/common/threading.c to the add_executable() when building with shared libraries

**Comment by JonLiu1993** [comment]
@anarazel, For the first error:
````
-- CMAKE_INSTALL_PREFIX: F:/Feature-test/zstd/vcpkg/packages/zstd_x86-windows
-- CMAKE_INSTALL_LIBDIR: lib
-- ZSTD_LEGACY_SUPPORT defined!
-- ZSTD_MULTITHREAD_SUPPORT is enabled
CMake Error at CMakeLists.txt:149 (message):
  You need to build static library to build zstd CLI
````
maybe we can add a static compilation condition to mask it.
````
if(NOT BUILD_SHARED_LIB)
````

For the second error:
````
warning: The following EXEs were found in /bin or /debug/bin. EXEs are not valid distribution targets.

    F:\Feature-test\zstd\vcpkg\packages\zstd_x64-windows-static\bin\zstd.exe

warning: The following EXEs were found in /bin or /debug/bin. EXEs are not valid distribution targets.

    F:\Feature-test\zstd\vcpkg\packages\zstd_x64-windows-static\debug\bin\zstd.exe
````
we can use vcpkg function `vcpkg_copy_tools()`

**Comment by JonLiu1993** [comment]
Pinging @anarazel for response. can you address the review suggestions? Thanks!

**Comment by JonLiu1993** [comment]
Convert this PR to draft since there is no progress. Please ping us if this PR is ready for review again.

**Comment by JonLiu1993** [comment]
Closing this PR since it seems that no progress is being made. Please ping us to reopen if work is still being done.

**Comment by JonLiu1993** [comment]
Feature `tools` tested successfully in the following triplet:
- x86-windows
- x64-windows
- x64-windows-static

**Comment by BillyONeal** [comment]
Thanks!

**Pull request merged**
