### PR TITLE
Update rttr library to 0.9.6. (fixes #5710)

### LINKED ISSUE #5710: [rttr] Update to 0.9.6
ITNOA

Please update [rttr library](https://github.com/rttrorg/rttr) to 0.9.6 version. this version release after two years and have many new features and resolve many bugs.

thanks

### PR DESCRIPTION
**Pull request by soroshsabz**
ITNOA

This PR update RTTR to 0.9.6 and resolved #5710

### CODE REVIEW

**Comment by soroshsabz** [comment]
I cannot access vcpkg-PR-Eager to see error, how can I resolve this?

**Comment by Rastaban** [comment]
These are the failures, let us know if you need to see any of the logs.
```
Processing arm-uwp                        414 vs 415
    rttr                          **regression**                Fail vs Pass
Processing arm64-windows                  473 vs 474
    rttr                          **regression**                Fail vs Pass
Processing x64-linux                      637 vs 638
    rttr                          **regression**                Fail vs Pass
Processing x64-uwp                        443 vs 444
    rttr                          **regression**                Fail vs Pass
```

**Comment by soroshsabz** [comment]
@Rastaban I did not change anything, Are you sure this library pass UWP and ARM triplet before this version?

Can you get me some more log or information to investigation the problem?
Did you have any suggestion to resolve these problems?

thanks

**Comment by soroshsabz** [comment]
@Rastaban I resolved Linux problem, please let me know other triplet error with detailed log.

How to can I test UWP in my computer?

**Comment by soroshsabz** [comment]
@Rastaban because this library using [LoadLibraryW](https://docs.microsoft.com/en-us/windows/desktop/api/libloaderapi/nf-libloaderapi-loadlibraryw
) in src\rttr\detail\library\library_win.cpp so this library does not support UWP platform.

**Comment by Rastaban** [comment]
Thank you for looking into that @soroshsabz.  If the UWP triplets are the only failures when the current set of tests complete then I can merge the change.

**Comment by soroshsabz** [comment]
@Rastaban Ok, What is triplets now failed? please let me know with detailed.

thanks

**Pull request merged**
