### PR TITLE
[protobuf] update to v3.6.0

### PR DESCRIPTION
**Pull request by jozefizso**
Update **protobuf** port to v3.6.0

I've cleaned up patches as most of the are included in this release.

Tested with `x64-windows`, `x64-windows-static`, `x86-windows` and `x86-windows-static` triplets.

### CODE REVIEW

**Comment by thierryba** [comment]
I'm not in power to review this but I'd appreciate if it was reviewed and merged.

**Comment by alexkaratarakis** [comment]
@jozefizso 
First off, sorry for not handling this sooner. I have resolved the current conflicts. The patch remaining here is `jsembed.patch`. It appears the first part:

```
@@ -62,7 +62,7 @@ set(libprotoc_files
   ${protobuf_source_dir}/src/google/protobuf/compiler/java/java_string_field.cc
   ${protobuf_source_dir}/src/google/protobuf/compiler/java/java_string_field_lite.cc
   ${protobuf_source_dir}/src/google/protobuf/compiler/js/js_generator.cc
-  ${protobuf_source_dir}/src/google/protobuf/compiler/js/well_known_types_embed.cc
+  ${CMAKE_CURRENT_BINARY_DIR}/well_known_types_embed.cc
   ${protobuf_source_dir}/src/google/protobuf/compiler/objectivec/objectivec_enum.cc
   ${protobuf_source_dir}/src/google/protobuf/compiler/objectivec/objectivec_enum_field.cc
   ${protobuf_source_dir}/src/google/protobuf/compiler/objectivec/objectivec_extension.cc
```

still applies but the second part:
```
@@ -168,9 +168,9 @@ set(js_well_known_types_sources
 )
 add_executable(js_embed ${protobuf_source_dir}/src/google/protobuf/compiler/js/embed.cc)
 add_custom_command(
-  OUTPUT ${protobuf_source_dir}/src/google/protobuf/compiler/js/well_known_types_embed.cc
+  OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/well_known_types_embed.cc
   DEPENDS js_embed ${js_well_known_types_sources}
-  COMMAND js_embed ${js_well_known_types_sources} > ${protobuf_source_dir}/src/google/protobuf/compiler/js/well_known_types_embed.cc
+  COMMAND "$<TARGET_FILE:js_embed>" ${js_well_known_types_sources} > ${CMAKE_CURRENT_BINARY_DIR}/well_known_types_embed.cc
 )

 add_library(libprotoc ${protobuf_SHARED_OR_STATIC}
```
does not. The corresponding directives don't exist in the most updated file.

Do you know whether this patch is still required?

**Comment by jozefizso** [comment]
They removed the js_embed binary: https://github.com/google/protobuf/commit/b3e4e3abe0d2f79ec9f1e4e24e12dc642d662546#diff-cfb00c0281078b8a94d5f2d6569d64dc

```diff
diff --git a/cmake/libprotoc.cmake b/cmake/libprotoc.cmake
index ec6958bce2..58568bb2fc 100644
--- a/cmake/libprotoc.cmake
+++ b/cmake/libprotoc.cmake
@@ -161,17 +161,11 @@ set(libprotoc_headers
   ${protobuf_source_dir}/src/google/protobuf/compiler/zip_writer.h
 )
 
-set(js_well_known_types_sources
-  ${protobuf_source_dir}/src/google/protobuf/compiler/js/well_known_types/any.js
-  ${protobuf_source_dir}/src/google/protobuf/compiler/js/well_known_types/struct.js
-  ${protobuf_source_dir}/src/google/protobuf/compiler/js/well_known_types/timestamp.js
-)
-add_executable(js_embed ${protobuf_source_dir}/src/google/protobuf/compiler/js/embed.cc)
-add_custom_command(
-  OUTPUT ${protobuf_source_dir}/src/google/protobuf/compiler/js/well_known_types_embed.cc
-  DEPENDS js_embed ${js_well_known_types_sources}
-  COMMAND js_embed ${js_well_known_types_sources} > ${protobuf_source_dir}/src/google/protobuf/compiler/js/well_known_types_embed.cc
+if (MSVC)
+set(libprotoc_rc_files
+  ${CMAKE_CURRENT_BINARY_DIR}/version.rc
 )
+endif()
 
 add_library(libprotoc ${protobuf_SHARED_OR_STATIC}
   ${libprotoc_files} ${libprotoc_headers})
```

**Comment by jozefizso** [comment]
Closing as newer port exists already.

**Pull request closed without merging**
