### PR TITLE
proj4 uwp improvments

### PR DESCRIPTION
**Pull request by gorlak**
Remove prior arm/uwp patch since host dependencies now allow for proj database generation
Add a new patch that repairs Win32 API calls to use UWP counterparts in UWP builds

- #### What does your PR fix?  
  Fixes build of proj4 for uwp triplets and for when host architecture doesn't match target architecture

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  The following triplets work with these changes based upon the May release: arm64-android, arm-android, x64-android, x86-android, arm64-ios, arm64-uwp, x64-linux, x64-osx, x64-uwp, x64-windows

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes, I think so

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes, but I had to use --overwrite-version to get it make modifications

### CODE REVIEW

**Comment by JackBoosY** [comment]
Thanks! But we should wait for the upstream approval, can you please open a PR to the upstream?

**Comment by gorlak** [comment]
Hi! No problem.

I'm waiting on final clearance from my employer to accept the CLA. Shouldn't be a problem but will take a little bit. I was going to do a PR to OSGeo/PROJ _after_ this one. Should I have done the upstream PR first? Then Linked it to this one? Is a source patch undesired vs. being patient on getting a patch upstreamed and released? Note that OSGeo/PROJ is at 8.0.1 now, unclear if upgrading will open issues. They seem to have a good release cadence over there, though.

Cheers.

**Comment by JackBoosY** [comment]
@gorlak  Yes, according to our policy, we should wait for the upstream to accept the source changes first.

**Comment by gorlak** [comment]
Finally getting back to this. https://github.com/OSGeo/PROJ/pull/2831

**Comment by JackBoosY** [comment]
Thanks! Let's wait for the upstream reply.

**Comment by gorlak** [comment]
PROJ PR is in PROJ/master. Do I need to re-kick those checks?

**Comment by JackBoosY** [comment]
> PROJ PR is in PROJ/master. Do I need to re-kick those checks? Oh dear it looks like the build logs are gone

Don't worry.

**Comment by JackBoosY** [comment]
Can you please resolve the file conflicts first?

**Comment by gorlak** [comment]
Ok, I've rebased my changes onto your master. Hopefully that's the right thing. And hopefully I did the right thing with the port versions.

**Review by JackBoosY — CHANGES_REQUESTED** [review]
Please re-update port-version on vcpkg.json

**Comment by JackBoosY** [comment]
And please disable `libgeotiff:x64-uwp` and `libgeotiff:arm-uwp` in the baseline.
Those regressions appear because proj4 enabled the uwp build and libgeotiff depends on proj4.

**Comment by gorlak** [comment]
Thanks for your patience! This is my first PR, port version bump in vcpkg.

**Comment by gorlak** [comment]
Regarding the bot's comments:

I performed the version update and a bunch of other ports version json files were modified, so I think it's crying over other's changes? It also deleted my proj4 port-version #5. I'm a bit unclear on how this version updater is designed to work.

I think I've only added port-version 5, so I'm not quite clear if the bot has detected an issue with the port-versions, or just reminding me.

**Comment by gorlak** [comment]
`vcpkg x-add-version proj4` doesn't have any effect on my repository.

**Comment by JackBoosY** [comment]
Please:
1. merge to master.
2. Use command `./vcpkg x-add-version --overwrite-version proj4`

I don't have permission to push my changes to this branch.

**Comment by gorlak** [comment]
I've rebased to your master again. The command you specified isn't leaving any changes in my workspace:

```C:\Users\geoff.evans\Projects\gorlak-forks-vcpkg>git fetch microsoft
remote: Enumerating objects: 257, done.
remote: Counting objects: 100% (137/137), done.
remote: Total 257 (delta 137), reused 137 (delta 137), pack-reused 120R
Receiving objects: 100% (257/257), 239.23 KiB | 716.00 KiB/s, done.
Resolving deltas: 100% (180/180), completed with 81 local objects.
From https://github.com/microsoft/vcpkg
   8c092e5cb..71422c627  master     -> microsoft/master

C:\Users\geoff.evans\Projects\gorlak-forks-vcpkg>git rebase microsoft/master
Successfully rebased and updated refs/heads/proj4-uwp.

C:\Users\geoff.evans\Projects\gorlak-forks-vcpkg>vcpkg x-add-version --overwrite-version proj4
A suitable version of git was not found (required v2.32.0). Downloading portable git v2.32.0...
Extracting git...
A suitable version of 7zip was not found (required v19.0.0). Downloading portable 7zip v19.0.0...
Extracting 7zip...

C:\Users\geoff.evans\Projects\gorlak-forks-vcpkg>git status
On branch proj4-uwp
Your branch and 'origin/proj4-uwp' have diverged,
and have 28 and 5 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working tree clean
```

**Comment by gorlak** [comment]
I upgraded my local git and it seems to have worked. A proper error message might be nicer here.

**Review by JackBoosY — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for your help!

**Pull request merged**
