### PR TITLE
[ecm] add license

### PR DESCRIPTION
**Pull request by Lex-2008**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] SHA512s are updated for each updated download
- [ ] The "supports" clause reflects platforms that may be fixed by this new version
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [ ] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by data-queue** [comment]
I think this port has many licenses

**Comment by Lex-2008** [comment]
hm. Thanks for checking!

I navigated to "homepage" (github repo), from there - "Licenses" in right-hand-side column opens [this file][t], which looked like BSD for me.

But indeed, now I see that it has "LICENSES" dir with several other licenses. [Relevant commit][c] introducing this.

[t]: https://github.com/KDE/extra-cmake-modules/blob/master/COPYING-CMAKE-SCRIPTS
[c]: https://github.com/KDE/extra-cmake-modules/commit/110f62d69b9529a901889c3998817eb406a22c8f

Checking for existing SPDX-License-Identifier[^1] in that repo finds the following licenses:

```
BSD-2-Clause
BSD-3-Clause
CC0-1.0
GPL-2.0-only
GPL-2.0-or-later
GPL-3.0-only
LGPL-2.1-or-later
LGPL-3.0-only
MIT
```

[^1]: `git grep SPDX-License-Identifier | sed 's/.*://' | sort -u`

Do you know how/if this can be expressed in an SPDX expression? Should I join these licenses with `AND`, `OR`, or is it not-SPDX-possible?

**Comment by BillyONeal** [comment]
>Checking for existing SPDX-License-Identifier[1](https://github.com/microsoft/vcpkg/pull/35085#user-content-fn-1-0c49aaec715a5150373a477135bb7603) in that repo finds the following licenses:

Sounds like the only correct answer is `null` with a copyright file explaining in what context what parts apply.

**Comment by jimwang118** [comment]
The upstream license developed [here](https://github.com/KDE/extra-cmake-modules/blob/master/README.rst#license:~:text=Extra%20CMake%20Modules.-,License,-All%20code%20is) is the BSD 3-Clause license.

**Comment by jimwang118** [comment]
@data-queue Why does the license here need to be revised?

**Comment by data-queue** [comment]
The correct answer is to use `null`, see Billy's comment.

I'm going to close this PR for now, feel free to open a new PR if you are still interested in this change.

**Pull request closed without merging**
