### PR TITLE
[taocpp-tuple] Add port

### PR DESCRIPTION
**Pull request by Jimmy-Hu**
[taocpp-tuple] Add port

### CODE REVIEW

**Comment by JackBoosY** [comment]
```
[1/7] /usr/bin/c++  -I/mnt/vcpkg-ci/buildtrees/taocpp-tuple/src/1.0.0-af40096f4c.clean/include -fPIC -O3 -DNDEBUG -pedantic -Wall -Wextra -Wshadow -Werror -std=c++11 -MD -MT src/test/tuple/CMakeFiles/tuple_main.dir/tuple_main.cpp.o -MF src/test/tuple/CMakeFiles/tuple_main.dir/tuple_main.cpp.o.d -o src/test/tuple/CMakeFiles/tuple_main.dir/tuple_main.cpp.o -c /mnt/vcpkg-ci/buildtrees/taocpp-tuple/src/1.0.0-af40096f4c.clean/src/test/tuple/tuple_main.cpp
FAILED: src/test/tuple/CMakeFiles/tuple_main.dir/tuple_main.cpp.o 
/usr/bin/c++  -I/mnt/vcpkg-ci/buildtrees/taocpp-tuple/src/1.0.0-af40096f4c.clean/include -fPIC -O3 -DNDEBUG -pedantic -Wall -Wextra -Wshadow -Werror -std=c++11 -MD -MT src/test/tuple/CMakeFiles/tuple_main.dir/tuple_main.cpp.o -MF src/test/tuple/CMakeFiles/tuple_main.dir/tuple_main.cpp.o.d -o src/test/tuple/CMakeFiles/tuple_main.dir/tuple_main.cpp.o -c /mnt/vcpkg-ci/buildtrees/taocpp-tuple/src/1.0.0-af40096f4c.clean/src/test/tuple/tuple_main.cpp
/mnt/vcpkg-ci/buildtrees/taocpp-tuple/src/1.0.0-af40096f4c.clean/src/test/tuple/tuple_main.cpp: In function ‘int main()’:
/mnt/vcpkg-ci/buildtrees/taocpp-tuple/src/1.0.0-af40096f4c.clean/src/test/tuple/tuple_main.cpp:17:9: error: variable ‘t4’ set but not used [-Werror=unused-but-set-variable]
    auto t4 = tuple< int, double, int >( 1, 2, 2 );
         ^~
/mnt/vcpkg-ci/buildtrees/taocpp-tuple/src/1.0.0-af40096f4c.clean/src/test/tuple/tuple_main.cpp:18:9: error: variable ‘t5’ set but not used [-Werror=unused-but-set-variable]
    auto t5 = tuple< int, double, int >( 1, 2, 4 );
         ^~
cc1plus: all warnings being treated as errors
```

**Comment by JackBoosY** [comment]
Pinging @Jimmy-Hu for response. Is work still being done for this PR?

**Comment by Jimmy-Hu** [comment]
It seems that the option `-Werror` in build command should be replaced into `-Wno-unused-variable` to disable the unused variable warnings.

**Comment by PhoebeHui** [comment]
Closing this PR since it seems that no progress is being made, Please reopen if work is still being done.

**Pull request closed without merging**
