### PR TITLE
[on-hold] Updated OpenImageIO to 2.0.4 and find_package compatibility.

### PR DESCRIPTION
**Pull request by alanj-ms**
OpenImageIO 2.0.4 update and added support for CMake config (so that find_package works)

Note, the library name is case sensitive, which is covered in all the files here, though the directory remains a lower case version of the proper name - Vcpkg team, you may wish to change this, though I left it be incase you had a lowercase naming policy for ports.

### CODE REVIEW

**Comment by alanj-ms** [comment]
Putting this on hold while I look at getting the config-file CMake package support upstream instead.

**Comment by ras0219-msft** [comment]
Thanks for letting us know! Please rename the title back from [on-hold] once you're ready for us to take a look :)

**Comment by fredrikaverpil** [comment]
I believe 2.0.5 is [soon out](https://github.com/OpenImageIO/oiio/pull/2158#issuecomment-457383469) (1st of Feb).

**Comment by Rastaban** [comment]
2.0.6 is out.  Did the upstream change make it in? https://github.com/OpenImageIO/oiio/releases/tag/Release-2.0.6

**Comment by huargovfx** [comment]
Good day everyone,
I updated my pull from this branch to version 2.0.8 and works perfect, I hope it can be soon merged to master.

**Comment by fredrikaverpil** [comment]
Hey @huargovfx perhaps if you submit your changes as a PR, this Will get merged a bit faster...?

**Comment by grdowns** [comment]
Hey everyone, the OIIO has been superceded by this PR as it is now at 2.0.8. OIIO also contains a valid cmake module which isn't currently exposed which we can use for find_package compat. I've created PR #7588 to amend this. Thanks for raising the issue @alanj-ms!

**Pull request closed without merging**
