### PR TITLE
[utf8cpp] Initial addition

### PR DESCRIPTION
**Pull request by KindDragon**
I don't know how better name package

### CODE REVIEW

**Comment by KindDragon** [comment]
utfcpp, utf8cpp or UTF8-CPP

**Comment by ras0219-msft** [comment]
I think utfcpp is the best name, since:
- That's the name used for the repo
- That's the name used for the sourceforge page: http://utfcpp.sourceforge.net/
- Searching utf8cpp on GitHub pulls up a couple different libraries of that name.

**Comment by KindDragon** [comment]
I rename it

**Comment by ras0219-msft** [comment]
Awesome, thanks!

**Pull request merged**
