### PR TITLE
[ffmpeg] add -fPIC

### LINKED ISSUE #17292: [ffmpeg] add -fPIC to build
**Describe the bug**
When trying to use ffmpeg in a downstream project which produces a shared library, I cannot link to ffmpeg due to this problem: 

```
/usr/bin/ld: vcpkg_installed/x64-linux/lib/libavcodec.a(vc1dsp_mmx.o): relocation R_X86_64_PC32 against symbol `ff_pw_9' can not be used when making a shared object; recompile with -fPIC
```

**Environment**
- OS: Ubuntu 20.04
- Compiler: gcc-8 

**To Reproduce**
1. ./vcpkg install ffmpeg
2. use ffmpeg in a downstream project which builds a .so library and links to ffmpeg

**Additional context**
@mcmtroffaes @Sibras any idea where it might be optimal to add the -fPIC option? It might be useful even if vcpkg is compiling a static library, and it is necessary in case anyone wants to use a personal non-static triplet

### PR DESCRIPTION
**Pull request by cenit**
**Describe the pull request**

- #### What does your PR fix?  
  Fixes #17292 

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
all

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by PhoebeHui** [comment]
The pipeline run actually finished, see https://dev.azure.com/vcpkg/public/_build/results?buildId=52157&view=results

However, it doesn't show correct status here, it looks stuck at step 'microsoft.vcpkg.pr (Formatting and Documentation Checks Job)', It looks does't return the results back.

@strega-nil, could you help have a look? currently all new PRs affected by this issue.

**Comment by cenit** [comment]
yeah I am already fixing regression (which is not due to this PR, but is already in master...)
anyway a commit is coming :)

**Comment by cenit** [comment]
@PhoebeHui regression is fixed :)

**Comment by cenit** [comment]
somehow in production is still not fixed?
I still have ` vcpkg_installed/x64-linux/lib/libavcodec.a(vc1dsp_mmx.o): relocation R_X86_64_PC32 against symbol `ff_pw_9' can not be used when making a shared object; recompile with -fPIC` ....
I will investigate it more, it looks like `--enable-pic` didn't do its job

**Pull request merged**
