### PR TITLE
[fltk] Update to 1.3.6 rc1 and fix osx build

### LINKED ISSUE #17561: [fltk] build failure
**Host Environment**
- OS: MacOS Big Sur 11.2.3
- Compiler: clang

**To Reproduce**
`./vcpkg install fltk`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.

-- Building x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: /Applications/vcpkg/downloads/tools/cmake-3.20.1-osx/cmake-3.20.1-macos-universal/CMake.app/Contents/bin/cmake --build . --config Debug --target install -- -v -j5
    Working Directory: /Applications/vcpkg/buildtrees/fltk/x64-osx-dbg
    See logs for more information:
      /Applications/vcpkg/buildtrees/fltk/install-x64-osx-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:105 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:45 (vcpkg_build_cmake)
  ports/fltk/portfile.cmake:42 (vcpkg_install_cmake)
  scripts/ports.cmake:142 (include)

Error: Building package fltk:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: fltk:x64-osx
  Vcpkg version: 2021-01-13-unknownhash

-Please attach any additional failure logs mentioned in the console output.

[config-x64-osx-dbg-err.log](https://github.com/microsoft/vcpkg/files/6394455/config-x64-osx-dbg-err.log)
[config-x64-osx-dbg-out.log](https://github.com/microsoft/vcpkg/files/6394456/config-x64-osx-dbg-out.log)

**Additional context**
- vcpkg is up to date (was recently installed)
- Reinstalled cmake. 
   Previous: version 3.7.1
   Current: version 3.20.1
- New to coding, so not quite sure on what I'm doing.

### PR DESCRIPTION
**Pull request by JackBoosY**
This PR will:
- update fltk to 1.3.6 rc1
- use github repo
- fix osx build using the official changes: https://github.com/fltk/fltk/issues/191
- drop support with uwp since the upstream use some desktop only functions:
```
     4>f:\vcpkg\buildtrees\fltk\src\629d1bd445-dc683240ba\fl\win32.H(52): error C3861: 'DeleteObject': identifier not found (compiling source file F:\vcpkg\buildtrees\fltk\src\629d1bd445-dc683240ba\src\Fl_Bitmap.cxx) [F:\vcpkg\buildtrees\fltk\arm64-uwp-dbg\src\fltk.vcxproj]
     4>f:\vcpkg\buildtrees\fltk\src\629d1bd445-dc683240ba\fl\win32.H(54): error C3861: 'GetRgnBox': identifier not found (compiling source file F:\vcpkg\buildtrees\fltk\src\629d1bd445-dc683240ba\src\Fl_Bitmap.cxx) [F:\vcpkg\buildtrees\fltk\arm64-uwp-dbg\src\fltk.vcxproj]
     4>f:\vcpkg\buildtrees\fltk\src\629d1bd445-dc683240ba\fl\win32.H(87): error C2061: syntax error: identifier 'MINMAXINFO' (compiling source file F:\vcpkg\buildtrees\fltk\src\629d1bd445-dc683240ba\src\Fl_Bitmap.cxx) [F:\vcpkg\buildtrees\fltk\arm64-uwp-dbg\src\fltk.vcxproj]
```
See https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-deleteobject

### CODE REVIEW

**Comment by JackBoosY** [comment]
@efrainceh Can you please test this PR?

Thanks.

**Comment by efrainceh** [comment]
@JackBoosY tested the PR, fltk successfully downloaded and installed (it works, too). Do you need any of the logs?

**Comment by JackBoosY** [comment]
@efrainceh Nope, I just want to test whether it works.

**Review by NancyLi1013 — APPROVED** [review]

**Comment by MoAlyousef** [comment]
It appears version 1.36 was officially released yesterday.

**Pull request merged**
