### PR TITLE
[imgui] Update to 1.76

### PR DESCRIPTION
**Pull request by michaelquigley**
Update dear imgui library to version 1.76.

- What does your PR fix? Fixes #

N/A

- Which triplets are supported/not supported? Have you updated the CI baseline?

Should be no changes.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

I believe so.

### CODE REVIEW

**Comment by michaelquigley** [comment]
Could be mistaken, but the failing PR checks all look like they might be transient infrastructure failures.

**Review by LilyWangL — APPROVED** [review]

**Comment by michaelquigley** [comment]
Thank you! How do I get this merged?

**Comment by strega-nil** [comment]
You wait for working hours pacific time ;)

Thanks @michaelquigley :)

**Comment by michaelquigley** [comment]
No problem! Just wanted to make sure there wasn't something else I needed to do! I appreciate it...

**Pull request merged**
