### PR TITLE
[pango] Used unused variable (fix for MacOS / Clang 13)

### PR DESCRIPTION
**Pull request by bold84**
**Describe the pull request**

- #### What does your PR fix?
  see title

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  unchanged

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by Neumann-A** [comment]
You can close this. Either keep this patch in your private overlay or submit it upstream. This is not something which should be merged into vcpkg in my view.

**Comment by bold84** [comment]
You see, I couldn’t care less… 

There’s a lot of stuff in here that shouldn’t be in here, from what I’ve seen and according to how I can interpret “your view”. 
I don’t think that’s what really matters. What matters is that this port builds for the next user on OSX or with Clang 13, to be more specific. 

Anyways, the PR is here. If whoever is in charge doesn’t want it, fine with me.

**Comment by Neumann-A** [comment]
> What matters is that this port builds for the next user on OSX or with Clang 13, to be more specific.

What is the actual error because this looks suspicious like a `-Werror` problem.

**Comment by bold84** [comment]
> > What matters is that this port builds for the next user on OSX or with Clang 13, to be more specific.
> 
> What is the actual error because this looks suspicious like a `-Werror` problem.

Correct, but if I add that flag, the next guy will just update the version and commit hash and won't remove the flag. True, this might not matter much here. 
Anyways, I chose to be that next guy to update the version:

https://github.com/microsoft/vcpkg/pull/24345

So, as you suggested, I will close this PR.

**Pull request closed without merging**
