### PR TITLE
[vcpkg] More versioning docs

### PR DESCRIPTION
**Pull request by vicroms**
This PR adds more documentation for versioning

- [X] Getting started ([Rendered](https://github.com/vicroms/vcpkg/blob/versioning/docs/docs/users/versioning.getting-started.md))
- [X] Reference: Version schemes
- [X] Reference: Version files
- [X] Reference: Constraints

### CODE REVIEW

**Comment by soumyamahunt** [comment]
Is there any plan to support `msbuild` too? Also is there plan on `dependabot` integration?

**Comment by vicroms** [comment]
@soumyamahunt 
Yes, this will work with MSBuild projects. 
I added a link to an example of how to use manifests in MSBuild.

**Comment by soumyamahunt** [comment]
> @soumyamahunt
> Yes, this will work with MSBuild projects.
> I added a link to an example of how to use manifests in MSBuild.

What about enabling versions feature flag? Is this feature flag temporary, when versioning available for general release it won't be needed anymore?

**Comment by vicroms** [comment]
We plan to enable the flag by default once we have evidence from users of this feature that the feature is stable enough.

**Pull request merged**
