### PR TITLE
[blend2d|osgearth] Allow blend2d and osgearth[blend2d] on ARM

### LINKED ISSUE #28909: [blend2d] Allow building on ARM platforms
****

**Is your feature request related to a problem? Please describe.**
Blend2d is currently excluded from ARM platforms. However, it appears to support ARM since at least this commit: https://github.com/blend2d/blend2d/commit/da2b485c49536b594d9e2c029735c116d6ef45e6

I haven't done any extensive tests, but I can verify that this port compiles in Ubuntu 20.04 with an `arm64-linux-dynamic` triplet.

**Proposed solution**
Remove the restriction on ARM platforms from the blend2d port, and any dependent ports (e.g. [osgearth](https://github.com/microsoft/vcpkg/blob/4c5be28bfac45e53fa8c4100a1d759a8e5ee97fb/ports/osgearth/vcpkg.json#L57)).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by cbrl**
Fixes #28909 

This change allows blend2d on ARM platforms. As mentioned in the issue above, the blend2d project now supports this architecture, and I have confirmed that both blend2d and osgearth can be compiled on Ubuntu 20.04 with an `arm64-linux-dynamic` triplet.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by BillyONeal** [comment]
Looks like a legitimate regression from this PR.

**Comment by cbrl** [comment]
Yes, it seems the ARM build fails on Windows. Interestingly it's not in the blend2d code that the failure occurs, but rather in asmjit.

```
FAILED: CMakeFiles/blend2d.dir/3rdparty/asmjit/src/asmjit/arm/a64builder.cpp.obj 
C:\PROGRA~1\MICROS~1\2022\ENTERP~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\arm64\cl.exe   /TP  -ID:\buildtrees\blend2d\src\28ab5c6690-f673a4e089.clean\3rdparty\asmjit\src /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -MP -GR- -GF -Zc:__cplusplus -Zc:inline -Zc:strictStrings -Zc:threadSafeInit- -W4 -DASMJIT_STATIC -DASMJIT_NO_STDCXX -GS /showIncludes /FoCMakeFiles\blend2d.dir\3rdparty\asmjit\src\asmjit\arm\a64builder.cpp.obj /FdCMakeFiles\blend2d.dir\ /FS -c D:\buildtrees\blend2d\src\28ab5c6690-f673a4e089.clean\3rdparty\asmjit\src\asmjit\arm\a64builder.cpp
cl : Command line warning D9025 : overriding '/GR' with '/GR-'
cl : Command line warning D9025 : overriding '/W3' with '/W4'
D:\buildtrees\blend2d\src\28ab5c6690-f673a4e089.clean\3rdparty\asmjit\src\asmjit\arm\../arm/a64emitter.h(218): warning C4002: too many arguments for function-like macro invocation 'mvn'
D:\buildtrees\blend2d\src\28ab5c6690-f673a4e089.clean\3rdparty\asmjit\src\asmjit\arm\../arm/a64emitter.h(219): warning C4002: too many arguments for function-like macro invocation 'mvn'
D:\buildtrees\blend2d\src\28ab5c6690-f673a4e089.clean\3rdparty\asmjit\src\asmjit\arm\../arm/a64emitter.h(866): warning C4002: too many arguments for function-like macro invocation 'mvn'
D:\buildtrees\blend2d\src\28ab5c6690-f673a4e089.clean\3rdparty\asmjit\src\asmjit\arm\../arm/a64emitter.h(219): error C2535: 'asmjit::_abi_1_9::Error asmjit::_abi_1_9::a64::EmitterExplicitT<This>::neon_not(const asmjit::_abi_1_9::arm::Gp &)': member function already defined or declared
D:\buildtrees\blend2d\src\28ab5c6690-f673a4e089.clean\3rdparty\asmjit\src\asmjit\arm\../arm/a64emitter.h(218): note: see declaration of 'asmjit::_abi_1_9::a64::EmitterExplicitT<This>::neon_not'
D:\buildtrees\blend2d\src\28ab5c6690-f673a4e089.clean\3rdparty\asmjit\src\asmjit\arm\../arm/a64emitter.h(1204): note: see reference to class template instantiation 'asmjit::_abi_1_9::a64::EmitterExplicitT<This>' being compiled
D:\buildtrees\blend2d\src\28ab5c6690-f673a4e089.clean\3rdparty\asmjit\src\asmjit\arm\../arm/a64emitter.h(219): error C2535: 'asmjit::_abi_1_9::Error asmjit::_abi_1_9::a64::EmitterExplicitT<asmjit::_abi_1_9::a64::Emitter>::neon_not(const asmjit::_abi_1_9::arm::Gp &)': member function already defined or declared
D:\buildtrees\blend2d\src\28ab5c6690-f673a4e089.clean\3rdparty\asmjit\src\asmjit\arm\../arm/a64emitter.h(218): note: see declaration of 'asmjit::_abi_1_9::a64::EmitterExplicitT<asmjit::_abi_1_9::a64::Emitter>::neon_not'
D:\buildtrees\blend2d\src\28ab5c6690-f673a4e089.clean\3rdparty\asmjit\src\asmjit\arm\../arm/a64emitter.h(1211): note: see reference to class template instantiation 'asmjit::_abi_1_9::a64::EmitterExplicitT<asmjit::_abi_1_9::a64::Emitter>' being compiled
D:\buildtrees\blend2d\src\28ab5c6690-f673a4e089.clean\3rdparty\asmjit\src\asmjit\arm\../arm/a64emitter.h(219): error C2535: 'asmjit::_abi_1_9::Error asmjit::_abi_1_9::a64::EmitterExplicitT<asmjit::_abi_1_9::a64::Assembler>::neon_not(const asmjit::_abi_1_9::arm::Gp &)': member function already defined or declared
D:\buildtrees\blend2d\src\28ab5c6690-f673a4e089.clean\3rdparty\asmjit\src\asmjit\arm\../arm/a64emitter.h(218): note: see declaration of 'asmjit::_abi_1_9::a64::EmitterExplicitT<asmjit::_abi_1_9::a64::Assembler>::neon_not'
D:\buildtrees\blend2d\src\28ab5c6690-f673a4e089.clean\3rdparty\asmjit\src\asmjit\arm\../arm/a64assembler.h(21): note: see reference to class template instantiation 'asmjit::_abi_1_9::a64::EmitterExplicitT<asmjit::_abi_1_9::a64::Assembler>' being compiled
D:\buildtrees\blend2d\src\28ab5c6690-f673a4e089.clean\3rdparty\asmjit\src\asmjit\arm\../arm/a64emitter.h(219): error C2535: 'asmjit::_abi_1_9::Error asmjit::_abi_1_9::a64::EmitterExplicitT<asmjit::_abi_1_9::a64::Builder>::neon_not(const asmjit::_abi_1_9::arm::Gp &)': member function already defined or declared
D:\buildtrees\blend2d\src\28ab5c6690-f673a4e089.clean\3rdparty\asmjit\src\asmjit\arm\../arm/a64emitter.h(218): note: see declaration of 'asmjit::_abi_1_9::a64::EmitterExplicitT<asmjit::_abi_1_9::a64::Builder>::neon_not'
D:\buildtrees\blend2d\src\28ab5c6690-f673a4e089.clean\3rdparty\asmjit\src\asmjit\arm\../arm/a64builder.h(23): note: see reference to class template instantiation 'asmjit::_abi_1_9::a64::EmitterExplicitT<asmjit::_abi_1_9::a64::Builder>' being compiled
```

I briefly inspected the relevant asmjit source code, and the function-like macro "mvn" it's complaining about doesn't look like it's actually a macro. It appears to be just an identifier provided as an argument to a macro, which then gets used as a function name. I wonder if this is an MSVC bug.

[install-arm64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/10515399/install-arm64-windows-dbg-out.log)

**Comment by LilyWangLL** [comment]
> Yes, it seems the ARM build fails on Windows. Interestingly it's not in the blend2d code that the failure occurs, but rather in asmjit.
> 
> ```
> FAILED: CMakeFiles/blend2d.dir/3rdparty/asmjit/src/asmjit/arm/a64builder.cpp.obj 
> C:\PROGRA~1\MICROS~1\2022\ENTERP~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\arm64\cl.exe   /TP  -ID:\buildtrees\blend2d\src\28ab5c6690-f673a4e089.clean\3rdparty\asmjit\src /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -MP -GR- -GF -Zc:__cplusplus -Zc:inline -Zc:strictStrings -Zc:threadSafeInit- -W4 -DASMJIT_STATIC -DASMJIT_NO_STDCXX -GS /showIncludes /FoCMakeFiles\blend2d.dir\3rdparty\asmjit\src\asmjit\arm\a64builder.cpp.obj /FdCMakeFiles\blend2d.dir\ /FS -c D:\buildtrees\blend2d\src\28ab5c6690-f673a4e089.clean\3rdparty\asmjit\src\asmjit\arm\a64builder.cpp
> cl : Command line warning D9025 : overriding '/GR' with '/GR-'
> cl : Command line warning D9025 : overriding '/W3' with '/W4'
> D:\buildtrees\blend2d\src\28ab5c6690-f673a4e089.clean\3rdparty\asmjit\src\asmjit\arm\../arm/a64emitter.h(218): warning C4002: too many arguments for function-like macro invocation 'mvn'
> D:\buildtrees\blend2d\src\28ab5c6690-f673a4e089.clean\3rdparty\asmjit\src\asmjit\arm\../arm/a64emitter.h(219): warning C4002: too many arguments for function-like macro invocation 'mvn'
> D:\buildtrees\blend2d\src\28ab5c6690-f673a4e089.clean\3rdparty\asmjit\src\asmjit\arm\../arm/a64emitter.h(866): warning C4002: too many arguments for function-like macro invocation 'mvn'
> D:\buildtrees\blend2d\src\28ab5c6690-f673a4e089.clean\3rdparty\asmjit\src\asmjit\arm\../arm/a64emitter.h(219): error C2535: 'asmjit::_abi_1_9::Error asmjit::_abi_1_9::a64::EmitterExplicitT<This>::neon_not(const asmjit::_abi_1_9::arm::Gp &)': member function already defined or declared
> D:\buildtrees\blend2d\src\28ab5c6690-f673a4e089.clean\3rdparty\asmjit\src\asmjit\arm\../arm/a64emitter.h(218): note: see declaration of 'asmjit::_abi_1_9::a64::EmitterExplicitT<This>::neon_not'
> D:\buildtrees\blend2d\src\28ab5c6690-f673a4e089.clean\3rdparty\asmjit\src\asmjit\arm\../arm/a64emitter.h(1204): note: see reference to class template instantiation 'asmjit::_abi_1_9::a64::EmitterExplicitT<This>' being compiled
> D:\buildtrees\blend2d\src\28ab5c6690-f673a4e089.clean\3rdparty\asmjit\src\asmjit\arm\../arm/a64emitter.h(219): error C2535: 'asmjit::_abi_1_9::Error asmjit::_abi_1_9::a64::EmitterExplicitT<asmjit::_abi_1_9::a64::Emitter>::neon_not(const asmjit::_abi_1_9::arm::Gp &)': member function already defined or declared
> D:\buildtrees\blend2d\src\28ab5c6690-f673a4e089.clean\3rdparty\asmjit\src\asmjit\arm\../arm/a64emitter.h(218): note: see declaration of 'asmjit::_abi_1_9::a64::EmitterExplicitT<asmjit::_abi_1_9::a64::Emitter>::neon_not'
> D:\buildtrees\blend2d\src\28ab5c6690-f673a4e089.clean\3rdparty\asmjit\src\asmjit\arm\../arm/a64emitter.h(1211): note: see reference to class template instantiation 'asmjit::_abi_1_9::a64::EmitterExplicitT<asmjit::_abi_1_9::a64::Emitter>' being compiled
> D:\buildtrees\blend2d\src\28ab5c6690-f673a4e089.clean\3rdparty\asmjit\src\asmjit\arm\../arm/a64emitter.h(219): error C2535: 'asmjit::_abi_1_9::Error asmjit::_abi_1_9::a64::EmitterExplicitT<asmjit::_abi_1_9::a64::Assembler>::neon_not(const asmjit::_abi_1_9::arm::Gp &)': member function already defined or declared
> D:\buildtrees\blend2d\src\28ab5c6690-f673a4e089.clean\3rdparty\asmjit\src\asmjit\arm\../arm/a64emitter.h(218): note: see declaration of 'asmjit::_abi_1_9::a64::EmitterExplicitT<asmjit::_abi_1_9::a64::Assembler>::neon_not'
> D:\buildtrees\blend2d\src\28ab5c6690-f673a4e089.clean\3rdparty\asmjit\src\asmjit\arm\../arm/a64assembler.h(21): note: see reference to class template instantiation 'asmjit::_abi_1_9::a64::EmitterExplicitT<asmjit::_abi_1_9::a64::Assembler>' being compiled
> D:\buildtrees\blend2d\src\28ab5c6690-f673a4e089.clean\3rdparty\asmjit\src\asmjit\arm\../arm/a64emitter.h(219): error C2535: 'asmjit::_abi_1_9::Error asmjit::_abi_1_9::a64::EmitterExplicitT<asmjit::_abi_1_9::a64::Builder>::neon_not(const asmjit::_abi_1_9::arm::Gp &)': member function already defined or declared
> D:\buildtrees\blend2d\src\28ab5c6690-f673a4e089.clean\3rdparty\asmjit\src\asmjit\arm\../arm/a64emitter.h(218): note: see declaration of 'asmjit::_abi_1_9::a64::EmitterExplicitT<asmjit::_abi_1_9::a64::Builder>::neon_not'
> D:\buildtrees\blend2d\src\28ab5c6690-f673a4e089.clean\3rdparty\asmjit\src\asmjit\arm\../arm/a64builder.h(23): note: see reference to class template instantiation 'asmjit::_abi_1_9::a64::EmitterExplicitT<asmjit::_abi_1_9::a64::Builder>' being compiled
> ```
> 
> I briefly inspected the relevant asmjit source code, and the function-like macro "mvn" it's complaining about doesn't look like it's actually a macro. It appears to be just an identifier provided as an argument to a macro, which then gets used as a function name. I wonder if this is an MSVC bug.
> 
> [install-arm64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/10515399/install-arm64-windows-dbg-out.log)

If use `asmjit` which provided by vcpkg instead of `3rdparty/asmjit`, will this error still occur?

**Comment by cbrl** [comment]
> If use `asmjit` which provided by vcpkg instead of `3rdparty/asmjit`, will this error still occur?

It seems the version of asmjit provided by vcpkg doesn't support ARM. vcpkg provides a version from 2021-10-26 and ARM support was added later (see https://github.com/asmjit/asmjit/commit/23ddf56b00f47d8aa0c82ad225e4b3a92661da7e). I imagine the asmjit port would still fail the `arm64-windows` check if it was updated and allowed on ARM, but it's probably a good idea to work that problem out and use the vcpkg-provided dependencies in blend2d. If the error is still present, the discussion for this asmjit issue can be moved to a WIP PR for that port.

**Comment by cbrl** [comment]
So it looks like this problem was encountered just a little while ago in #28962. Some questionably named macros in the Windows SDK collide with identifiers in asmjit. Until the [mentioned issue](https://developercommunity.visualstudio.com/t/Windows-SDK---arm64_neonh-defines-macro/10253729) is resolved, asmjit would have exclude Windows as a supported platform when compiling for ARM.

As for using the version of asmjit provided by vcpkg, there is an open PR #27683 that updates asmjit pending the resolution of some link errors.

For now, the simplest change could be for blend2d to support `!(arm & windows)`. Once the mentioned PR is merged, this port can be modified so that it uses the vcpkg-provided dependencies.

**Comment by cbrl** [comment]
I've changed this so that it allows blend2d on ARM with the exception of Windows. If it's acceptable to temporarily keep the defective behavior of vendoring asmjit, then I think this PR should be good now.

**Review by LilyWangLL — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks!

**Pull request merged**
