### PR TITLE
[ixwebsocket] update to 9.6.2

### PR DESCRIPTION
**Pull request by bsergean**
Update the library to 9.5.0.

Notable changes:

* Windows default to OpenSSL, this simplify the Portfile.
* On Windows, with TLS on, load the os/system certificates by default for verifying peers.
* On OpenSSL and mbedtls TLS backend, add ability to specify a ca-cert from memory, instead of using a file.

### CODE REVIEW

**Review by NancyLi1013 — COMMENTED** [review]
`vcpkg_test_cmake()` is deprecated. 
Could you please remove it?

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
Needs to test the features.

**Review by NancyLi1013 — COMMENTED** [review]
I noticed there is only one options `-DUSE_TLS=1` that is related with these features.
Besides this, I didn't see any operations to handle these features. 
Could you please help make a simple clarification about how these features work?

**Comment by bsergean** [comment]
Hi @NancyLi1013,

I might not use the proper vcpkg terminology.

I used curl as an example, as it's a bit similar to my app.

* I want TLS to always be activated when building this library, which is why the CMake has USE_TLS=1.
* On macOS, the core tls library is part of the OS and called secure-transport. I don't need any dependent package to build it.
* on Windows and Linux, I want the tls library to be OpenSSL, which is why I'm setting up this feature, as non optional.

```
# SSL backends
Feature: openssl
Build-Depends: openssl
Description: SSL support (OpenSSL)
```

**Comment by NancyLi1013** [comment]
HI @bsergean 
Thanks for your above info.
Besides this, we still need to judge in which condition that we can use these features in portfile.cmake.

For example,  if we want to build with `openssl `or `sectransp `feature, how these features work?
Do these options `USE_OPEN_SSL` `USE_SECURE_TRANSPORT` `USE_MBED_TLS` not need to be set in portfile.cmake?

For  feature `mbedtls`, I noticed you removed it from feature list. Could you help make a simple description?

**Comment by bsergean** [comment]
```
$ ./vcpkg install ixwebsocket        
Computing installation plan...
The following packages will be built and installed:
    ixwebsocket[core]:x64-osx
Warning: abi keys are missing values:
    zlib

Starting package 1/1: ixwebsocket:x64-osx
Building package ixwebsocket[core]:x64-osx...
-- Downloading https://github.com/machinezone/IXWebSocket/archive/v9.5.2.tar.gz...
-- Extracting source /Users/bsergeant/src/foss/github/vcpkg/downloads/machinezone-IXWebSocket-v9.5.2.tar.gz
-- Using source at /Users/bsergeant/src/foss/github/vcpkg/buildtrees/ixwebsocket/src/v9.5.2-efe54999d7
-- Configuring x64-osx-dbg
-- Configuring x64-osx-rel
-- Building x64-osx-dbg
-- Building x64-osx-rel
-- Installing: /Users/bsergeant/src/foss/github/vcpkg/packages/ixwebsocket_x64-osx/share/ixwebsocket/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package ixwebsocket[core]:x64-osx... done
Installing package ixwebsocket[core]:x64-osx...
Installing package ixwebsocket[core]:x64-osx... done
Elapsed time for package ixwebsocket:x64-osx: 19.44 s

Total elapsed time: 19.44 s
```

Tried to build locally (on macOS) and it worked fine.

**Comment by NancyLi1013** [comment]
Why do you remove all features?

**Comment by bsergean** [comment]
I would like to simplify the port.

The features were only there to allocate different compatible SSL backed to each platform.

I would like to have SSL always enabled.

**Comment by strega-nil** [comment]
@bsergean this seems to remove support for UWP; that's, imo, a non-starter. Can you add back in the dependency on `mbedtls` for UWP, and depend on `opensll` for `!uwp & !osx`?

**Comment by bsergean** [comment]
I'd prefer making uwp works with OpenSSL, as it's easier for me to test and support. I'll see what I can do. Switching windows to openssl addresses a very common bug.

I have tried enabling CI for uwp in here.
https://github.com/machinezone/IXWebSocket/tree/feature/windows_uwp

The build fails with:

```
2020-04-28T00:14:35.5677795Z D:\a\IXWebSocket\IXWebSocket\ixwebsocket\IXDNSLookup.cpp(44,54): error C2679: binary '=': no operator found which takes a right-hand operand of type 'WCHAR *' (or there is no acceptable conversion) [D:\a\IXWebSocket\IXWebSocket\build\ixwebsocket.vcxproj]
```

in this code, which works will all platform (and used to work ?). Not sure what's going on.

```
        struct addrinfo* res;
        int getaddrinfo_result = getaddrinfo(hostname.c_str(), sport.c_str(), &hints, &res);
        if (getaddrinfo_result)
        {
            errMsg = gai_strerror(getaddrinfo_result);
            res = nullptr;
        }
        return res;
```

**Comment by bsergean** [comment]
gai_strerror seems to return a wchar_t

I configure with:

```
-DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION="10.0"
```

If you have any clue on what's going on @strega-nil I'm all ears :)

**Comment by bsergean** [comment]
I tried to find a MACRO that tells me if I'm building on uwp but I couldn't find it. I could convert the wstring to a string for uwp.

**Comment by strega-nil** [comment]
@bsergean it looks like `_UNICODE` is getting defined on uwp, but not regular windows; might mean you need to explicitly undefine `_UNICODE` with `/U_UNICODE`

**Comment by bsergean** [comment]
It is still failing ... :(

And there is no easy way that I know of to look at the error logs. This is all I could find.

```
2020-05-01T19:05:52.0357413Z Installing package zlib[core]:x64-uwp... done
2020-05-01T19:05:52.0358074Z Elapsed time for package zlib:x64-uwp: 335.3 ms
2020-05-01T19:05:52.0359407Z Starting package 4/4: ixwebsocket:x64-uwp
2020-05-01T19:05:52.0360177Z Building package ixwebsocket[core]:x64-uwp...
2020-05-01T19:05:52.0361023Z Could not locate cached archive: C:\agent\_work\1\s\archives\0f\0fd2c183a63c4874fdf870b40233ad17797bd30b.zip
2020-05-01T19:09:39.1570126Z -- Downloading https://github.com/machinezone/IXWebSocket/archive/v9.5.4.tar.gz...
2020-05-01T19:09:39.1571280Z -- Extracting source C:/agent/_work/1/s/downloads/machinezone-IXWebSocket-v9.5.4.tar.gz
2020-05-01T19:09:39.1571646Z -- Using source at C:/agent/_work/1/s/buildtrees/ixwebsocket/src/v9.5.4-304104947e
2020-05-01T19:09:39.1571935Z -- Configuring x64-uwp
2020-05-01T19:09:39.1572143Z -- Building x64-uwp-dbg
2020-05-01T19:09:39.1573008Z CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
2020-05-01T19:09:39.1573671Z     Command failed: D:/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Debug --target install -- /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /m
2020-05-01T19:09:39.1574720Z     Working Directory: C:/agent/_work/1/s/buildtrees/ixwebsocket/x64-uwp-dbg
2020-05-01T19:09:39.1575276Z     See logs for more information:
2020-05-01T19:09:39.1575795Z       C:\agent\_work\1\s\buildtrees\ixwebsocket\install-x64-uwp-dbg-out.log
2020-05-01T19:09:39.1577164Z 
2020-05-01T19:09:39.1577957Z Call Stack (most recent call first):
2020-05-01T19:09:39.1578675Z   scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
2020-05-01T19:09:39.1579212Z   scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
2020-05-01T19:09:39.1580005Z   ports/ixwebsocket/portfile.cmake:14 (vcpkg_install_cmake)
2020-05-01T19:09:39.1580791Z   scripts/ports.cmake:90 (include)
2020-05-01T19:09:39.1581399Z 
2020-05-01T19:09:39.1582062Z 
2020-05-01T19:09:39.2827842Z Error: Building package ixwebsocket:x64-uwp failed with: BUILD_FAILED
2020-05-01T19:09:39.2828785Z Elapsed time for package ixwebsocket:x64-uwp: 3.787 min
```

**Comment by strega-nil** [comment]
@bsergean this is the build log: https://gist.github.com/strega-nil/ab568c2b79d4145afe187e7547e2acad

**Comment by bsergean** [comment]
Thanks. Looks like the errors are about Windows headers not found in the OpenSSL file ...

         C:\agent\_work\1\s\buildtrees\ixwebsocket\src\v9.5.4-304104947e\ixwebsocket\IXSocketOpenSSL.cpp(30,15): error C2146: syntax error: missing ';' before identifier 'flags' [C:\agent\_work\1\s\buildtrees\ixwebsocket\x64-uwp-dbg\ixwebsocket.vcxproj]
         C:\agent\_work\1\s\buildtrees\ixwebsocket\src\v9.5.4-304104947e\ixwebsocket\IXSocketOpenSSL.cpp(30,15): error C2065: 'flags': undeclared identifier [C:\agent\_work\1\s\buildtrees\ixwebsocket\x64-uwp-dbg\ixwebsocket.vcxproj]
         C:\agent\_work\1\s\buildtrees\ixwebsocket\src\v9.5.4-304104947e\ixwebsocket\IXSocketOpenSSL.cpp(30,23): error C2065: 'CERT_STORE_READONLY_FLAG': undeclared identifier [C:\agent\_work\1\s\buildtrees\ixwebsocket\x64-uwp-dbg\ixwebsocket.vcxproj]
         C:\agent\_work\1\s\buildtrees\ixwebsocket\src\v9.5.4-304104947e\ixwebsocket\IXSocketOpenSSL.cpp(30,50): error C2065: 'CERT_STORE_OPEN_EXISTING_FLAG': undeclared identifier [C:\agent\_work\1\s\buildtrees\ixwebsocket\x64-uwp-dbg\ixwebsocket.vcxproj]
         C:\agent\_work\1\s\buildtrees\ixwebsocket\src\v9.5.4-304104947e\ixwebsocket\IXSocketOpenSSL.cpp(31,23): error C2065: 'CERT_SYSTEM_STORE_CURRENT_USER': undeclared identifier [C:\agent\_work\1\s\buildtrees\ixwebsocket\x64-uwp-dbg\ixwebsocket.vcxproj]
         C:\agent\_work\1\s\buildtrees\ixwebsocket\src\v9.5.4-304104947e\ixwebsocket\IXSocketOpenSSL.cpp(32,9): error C2065: 'HCERTSTORE': undeclared identifier [C:\agent\_work\1\s\buildtrees\ixwebsocket\x64-uwp-dbg\ixwebsocket.vcxproj]
         C:\agent\_work\1\s\buildtrees\ixwebsocket\src\v9.5.4-304104947e\ixwebsocket\IXSocketOpenSSL.cpp(32,20): error C2146: syntax error: missing ';' before identifier 'systemStore' [C:\agent\_work\1\s\buildtrees\ixwebsocket\x64-uwp-dbg\ixwebsocket.vcxproj]
         C:\agent\_work\1\s\buildtrees\ixwebsocket\src\v9.5.4-304104947e\ixwebsocket\IXSocketOpenSSL.cpp(32,20): error C2065: 'systemStore': undeclared identifier [C:\agent\_work\1\s\buildtrees\ixwebsocket\x64-uwp-dbg\ixwebsocket.vcxproj]
         C:\agent\_work\1\s\buildtrees\ixwebsocket\src\v9.5.4-304104947e\ixwebsocket\IXSocketOpenSSL.cpp(32,48): error C2065: 'CERT_STORE_PROV_SYSTEM': undeclared identifier [C:\agent\_work\1\s\buildtrees\ixwebsocket\x64-uwp-dbg\ixwebsocket.vcxproj]
         C:\agent\_work\1\s\buildtrees\ixwebsocket\src\v9.5.4-304104947e\ixwebsocket\IXSocketOpenSSL.cpp(32,78): error C2065: 'flags': undeclared identifier [C:\agent\_work\1\s\buildtrees\ixwebsocket\x64-uwp-dbg\ixwebsocket.vcxproj]
         C:\agent\_work\1\s\buildtrees\ixwebsocket\src\v9.5.4-304104947e\ixwebsocket\IXSocketOpenSSL.cpp(32,34): error C3861: 'CertOpenStore': identifier not found [C:\agent\_work\1\s\buildtrees\ixwebsocket\x64-uwp-dbg\ixwebsocket.vcxproj]
         C:\agent\_work\1\s\buildtrees\ixwebsocket\src\v9.5.4-304104947e\ixwebsocket\IXSocketOpenSSL.cpp(34,14): error C2065: 'systemStore': undeclared identifier [C:\agent\_work\1\s\buildtrees\ixwebsocket\x64-uwp-dbg\ixwebsocket.vcxproj]
         C:\agent\_work\1\s\buildtrees\ixwebsocket\src\v9.5.4-304104947e\ixwebsocket\IXSocketOpenSSL.cpp(37,40): error C3861: 'GetLastError': identifier not found [C:\agent\_work\1\s\buildtrees\ixwebsocket\x64-uwp-dbg\ixwebsocket.vcxproj]
         C:\agent\_work\1\s\buildtrees\ixwebsocket\src\v9.5.4-304104947e\ixwebsocket\IXSocketOpenSSL.cpp(41,9): error C2065: 'PCCERT_CONTEXT': undeclared identifier [C:\agent\_work\1\s\buildtrees\ixwebsocket\x64-uwp-dbg\ixwebsocket.vcxproj]
         C:\agent\_work\1\s\buildtrees\ixwebsocket\src\v9.5.4-304104947e\ixwebsocket\IXSocketOpenSSL.cpp(41,24): error C2146: syntax error: missing ';' before identifier 'certificateIterator' [C:\agent\_work\1\s\buildtrees\ixwebsocket\x64-uwp-dbg\ixwebsocket.vcxproj]
         C:\agent\_work\1\s\buildtrees\ixwebsocket\src\v9.5.4-304104947e\ixwebsocket\IXSocketOpenSSL.cpp(41,24): error C2065: 'certificateIterator': undeclared identifier [C:\agent\_work\1\s\buildtrees\ixwebsocket\x64-uwp-dbg\ixwebsocket.vcxproj]
         C:\agent\_work\1\s\buildtrees\ixwebsocket\src\v9.5.4-304104947e\ixwebsocket\IXSocketOpenSSL.cpp(45,16): error C2065: 'certificateIterator': undeclared identifier [C:\agent\_work\1\s\buildtrees\ixwebsocket\x64-uwp-dbg\ixwebsocket.vcxproj]
         C:\agent\_work\1\s\buildtrees\ixwebsocket\src\v9.5.4-304104947e\ixwebsocket\IXSocketOpenSSL.cpp(45,66): error C2065: 'systemStore': undeclared identifier [C:\agent\_work\1\s\buildtrees\ixwebsocket\x64-uwp-dbg\ixwebsocket.vcxproj]
         C:\agent\_work\1\s\buildtrees\ixwebsocket\src\v9.5.4-304104947e\ixwebsocket\IXSocketOpenSSL.cpp(45,79): error C2065: 'certificateIterator': undeclared identifier [C:\agent\_work\1\s\buildtrees\ixwebsocket\x64-uwp-dbg\ixwebsocket.vcxproj]
         C:\agent\_work\1\s\buildtrees\ixwebsocket\src\v9.5.4-304104947e\ixwebsocket\IXSocketOpenSSL.cpp(45,38): error C3861: 'CertEnumCertificatesInStore': identifier not found [C:\agent\_work\1\s\buildtrees\ixwebsocket\x64-uwp-dbg\ixwebsocket.vcxproj]
         C:\agent\_work\1\s\buildtrees\ixwebsocket\src\v9.5.4-304104947e\ixwebsocket\IXSocketOpenSSL.cpp(48,60): error C2065: 'certificateIterator': undeclared identifier [C:\agent\_work\1\s\buildtrees\ixwebsocket\x64-uwp-dbg\ixwebsocket.vcxproj]
         C:\agent\_work\1\s\buildtrees\ixwebsocket\src\v9.5.4-304104947e\ixwebsocket\IXSocketOpenSSL.cpp(49,35): error C2065: 'certificateIterator': undeclared identifier [C:\agent\_work\1\s\buildtrees\ixwebsocket\x64-uwp-dbg\ixwebsocket.vcxproj]
         C:\agent\_work\1\s\buildtrees\ixwebsocket\src\v9.5.4-304104947e\ixwebsocket\IXSocketOpenSSL.cpp(47,26): error C2660: 'd2i_X509': function does not take 1 arguments [C:\agent\_work\1\s\buildtrees\ixwebsocket\x64-uwp-dbg\ixwebsocket.vcxproj]
         C:\agent\_work\1\s\buildtrees\ixwebsocket\src\v9.5.4-304104947e\ixwebsocket\IXSocketOpenSSL.cpp(62,36): error C2065: 'certificateIterator': undeclared identifier [C:\agent\_work\1\s\buildtrees\ixwebsocket\x64-uwp-dbg\ixwebsocket.vcxproj]
         C:\agent\_work\1\s\buildtrees\ixwebsocket\src\v9.5.4-304104947e\ixwebsocket\IXSocketOpenSSL.cpp(62,9): error C3861: 'CertFreeCertificateContext': identifier not found [C:\agent\_work\1\s\buildtrees\ixwebsocket\x64-uwp-dbg\ixwebsocket.vcxproj]
         C:\agent\_work\1\s\buildtrees\ixwebsocket\src\v9.5.4-304104947e\ixwebsocket\IXSocketOpenSSL.cpp(63,24): error C2065: 'systemStore': undeclared identifier [C:\agent\_work\1\s\buildtrees\ixwebsocket\x64-uwp-dbg\ixwebsocket.vcxproj]
         C:\agent\_work\1\s\buildtrees\ixwebsocket\src\v9.5.4-304104947e\ixwebsocket\IXSocketOpenSSL.cpp(63,9): error C3861: 'CertCloseStore': identifier not found [C:\agent\_work\1\s\buildtrees\ixwebsocket\x64-uwp-dbg\ixwebsocket.vcxproj]
         C:\agent\_work\1\s\buildtrees\ixwebsocket\src\v9.5.4-304104947e\ixwebsocket\IXSocketOpenSSL.cpp(264,16): error C3861: 'PathMatchSpecA': identifier not found [C:\agent\_work\1\s\buildtrees\ixwebsocket\x64-uwp-dbg\ixwebsocket.vcxproj]
         C:\agent\_work\1\s\buildtrees\ixwebsocket\src\v9.5.4-304104947e\ixwebsocket\IXSocketOpenSSL.cpp(777,21): error C2065: 'WSAEWOULDBLOCK': undeclared identifier [C:\agent\_work\1\s\buildtrees\ixwebsocket\x64-uwp-dbg\ixwebsocket.vcxproj]
         C:\agent\_work\1\s\buildtrees\ixwebsocket\src\v9.5.4-304104947e\ixwebsocket\IXSocketOpenSSL.cpp(809,25): error C2065: 'WSAEWOULDBLOCK': undeclared identifier [C:\agent\_work\1\s\buildtrees\ixwebsocket\x64-uwp-dbg\ixwebsocket.vcxproj]

**Comment by bsergean** [comment]
@NancyLi1013 or @strega-nil I'd appreciate some help here, I've tried to revert back to using mbedtls on windows and uwp, but the CI is angry at me and I don't know what to do.

Maybe I'll revert to the previous CONTROL file which was expressing dependencies as features, while all I wanted was just to control dependencies by platform.

**Comment by NancyLi1013** [comment]
@bsergean 
Thanks for your continues efforts on this PR.
It seems that there are some regressions like this:
```
-- Performing post-build validation
The /lib/cmake folder should be merged with /debug/lib/cmake and moved to /share/ixwebsocket/cmake.
Please use the helper function `vcpkg_fixup_cmake_targets()`
The following cmake files were found outside /share/ixwebsocket. Please place cmake files in /share/ixwebsocket.

    C:/agent/_work/1/s/packages/ixwebsocket_x86-windows/lib/cmake/ixwebsocket/ixwebsocket-release.cmake
    C:/agent/_work/1/s/packages/ixwebsocket_x86-windows/lib/cmake/ixwebsocket/ixwebsocket.cmake
    C:/agent/_work/1/s/packages/ixwebsocket_x86-windows/debug/lib/cmake/ixwebsocket/ixwebsocket-debug.cmake
    C:/agent/_work/1/s/packages/ixwebsocket_x86-windows/debug/lib/cmake/ixwebsocket/ixwebsocket.cmake

The /debug/lib/cmake folder should be merged with /lib/cmake into /share/ixwebsocket
Found 3 error(s). Please correct the portfile:
    C:\agent\_work\1\s\ports\ixwebsocket\portfile.cmake
-- Performing post-build validation done
Error: Building package ixwebsocket:x86-windows failed with: POST_BUILD_CHECKS_FAILED
```
You need to handle these files.

**Comment by bsergean** [comment]
Cool those logs helped.

I made one last change and everything seems to pass but the osx test, which looks like a flaky intermittent azure pipeline problem (failure to git clone). Next run should be good.

```
remote: Compressing objects: 100% (15/15), done.        
remote: Total 65 (delta 33), reused 37 (delta 29), pack-reused 21        
From https://github.com/microsoft/vcpkg
 * [new ref]             refs/pull/11030/merge -> pull/11030/merge
git checkout --progress --force refs/remotes/pull/11030/merge
Previous HEAD position was 35a71e008 Merge 6248f7cc6dd2a25fe8b8f31d8f8ef1c76eec5ed9 into 8a583e80da3b72141105da9003175679af2fcb92
fatal: update_ref failed for ref 'HEAD': cannot lock ref 'HEAD': Unable to create '/Volumes/data/work/1/s/.git/HEAD.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```

**Comment by NancyLi1013** [comment]
It seems good now except for osx pipeline that is not related with this PR.
We will solve it later.

**Comment by bsergean** [comment]
It looks like CI is happy again indeed, 'All checks have passed' says the robot.

**Comment by NancyLi1013** [comment]
Yes, all checks have passed now.
I am going to test these features and will update the results once completed.

**Comment by bsergean** [comment]
I have never tried to use different 'features' or tls implementations.

I think it would take a small change to the portfile.cmake to handle that.

For example on macOS, I could try to use mbedtls or openssl. I'll give that a try.

curl does something like that which I should probably do:

vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    FEATURES
    # Support HTTP2 TLS Download https://curl.haxx.se/ca/cacert.pem rename to curl-ca-bundle.crt, copy it to libcurl.dll location.
    http2   USE_NGHTTP2
    openssl CMAKE_USE_OPENSSL
    mbedtls CMAKE_USE_MBEDTLS
    ssh     CMAKE_USE_LIBSSH2
    tool    BUILD_CURL_EXE
    c-ares  ENABLE_ARES
    sspi    CURL_WINDOWS_SSPI
    brotli  CURL_BROTLI
    winssl  CMAKE_USE_WINSSL
    sectransp   CMAKE_USE_SECTRANSP

    INVERTED_FEATURES
    non-http HTTP_ONLY
)


vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    FEATURES
    # Support HTTP2 TLS Download https://curl.haxx.se/ca/cacert.pem rename to curl-ca-bundle.crt, copy it to libcurl.dll location.
    http2   USE_NGHTTP2
    openssl CMAKE_USE_OPENSSL
    mbedtls CMAKE_USE_MBEDTLS
    ssh     CMAKE_USE_LIBSSH2
    tool    BUILD_CURL_EXE
    c-ares  ENABLE_ARES
    sspi    CURL_WINDOWS_SSPI
    brotli  CURL_BROTLI
    winssl  CMAKE_USE_WINSSL
    sectransp   CMAKE_USE_SECTRANSP

    INVERTED_FEATURES
    non-http HTTP_ONLY
)

For me it would be something like that

vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    FEATURES
    openssl USE_OPENSSL
    mbedtls USE_MBEDTLS
    sectransp   USE_SECTRANSP
)

**Comment by bsergean** [comment]
The check that fails looks like a ci problem, unrelated to the change, but I could be wrong -> https://dev.azure.com/vcpkg/public/_build/results?buildId=37180&view=results

It failed right away after 4s trying to cleanup a scratch folder.

**Comment by NancyLi1013** [comment]
All feature (except for `sectransp`) have passed with the following triplets:

- x86-windows
- x64-windows
- x64-windows-static

Note: Feature `sectransp` only supports osx platform.

**Comment by strega-nil** [comment]
Alright, cool, thanks @bsergean :) This looks great

**Comment by bsergean** [comment]
Thanks !

Took me a while but I think I understand ports better now.

**Comment by ludekvodicka** [comment]
Hello, Benjamin (@bsergean bsergean),
I tried to update IXWebsocket port to 11.0.4 version but I'm not sure how to solve this vcpkg error:

```
The /lib/cmake folder should be merged with /debug/lib/cmake and moved to /share/ixwebsocket/cmake.
Please use the helper function `vcpkg_fixup_cmake_targets()`
The following cmake files were found outside /share/ixwebsocket. Please place cmake files in /share/ixwebsocket.

    Q:/ExternalLibraries/vcpkg32/packages/ixwebsocket_x86-windows/lib/cmake/ixwebsocket/ixwebsocket-config-release.cmake
    Q:/ExternalLibraries/vcpkg32/packages/ixwebsocket_x86-windows/lib/cmake/ixwebsocket/ixwebsocket-config.cmake
    Q:/ExternalLibraries/vcpkg32/packages/ixwebsocket_x86-windows/debug/lib/cmake/ixwebsocket/ixwebsocket-config-debug.cmake
    Q:/ExternalLibraries/vcpkg32/packages/ixwebsocket_x86-windows/debug/lib/cmake/ixwebsocket/ixwebsocket-config.cmake

The /debug/lib/cmake folder should be merged with /lib/cmake into /share/ixwebsocket
Found 3 error(s). Please correct the portfile:
    Q:\ExternalLibraries\vcpkg32\ports\ixwebsocket\portfile.cmake
-- Performing post-build validation done
Error: Building package ixwebsocket:x86-windows failed with: POST_BUILD_CHECKS_FAILED
```

I only changed REF and SHA hash in portfile.cmake to following:

```
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO machinezone/IXWebSocket
    REF v11.0.4
    SHA512 
	fb24a628600cf28acdcaed5d2268f6a6e36baa1cc31f54287d91fb979fe375b20931fa9346153eaaf5a5d17fc6d87f06ca03ce12e401b83095c16919d35454ce
)
```

but there are probably larger differences between 9.x and 11.x versions

**Comment by bsergean** [comment]
There's an extra bit of cmake which needs to be added to deal with that but
I never figured it out myself.

Other ports probably have the cmake code snippet to copy paste. This is to
delete a file (or 2) that gets copied over, which vcpkg does not want. Or
maybe copy them in a different folder. vcpkg maintainers might know better.

**Comment by bsergean** [comment]
Also I should make a new tag more recent than 11.0.4

**Comment by bsergean** [comment]
-- Installing: /usr/local/include/ixwebsocket/IXWebSocketVersion.h

-- Installing: /usr/local/include/ixwebsocket/IXSocketAppleSSL.h

-- Installing: /usr/local/lib/cmake/ixwebsocket/ixwebsocket-config.cmake

-- Installing:
/usr/local/lib/cmake/ixwebsocket/ixwebsocket-config-debug.cmake

You need something to uninstall the .cmake files

lots of port files have lines like that

file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/include)
Try to add this after that include line. And maybe remove the 2  files
explicitly. (ixwebsocket-config.cmake and ixwebsocket-config-debug.cmake).

file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/lib/cmake)

**Comment by ludekvodicka** [comment]
Is there any official way on how to ask maintainers to check it? 

Your library is great and I'm currently building it myself. But I'm trying to migrate all our compilation scripts to vcpkg but I have only limited knowledge of cmake and this is unfortunately also beyond my knowledge.

**Comment by ludekvodicka** [comment]
You were right, adding these two lines fixed the issue

```
file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/lib/cmake)
file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/lib/cmake)
```

Now the build proceeds correctly. I'm going to test it and if everything will be ok, I will create PR.

**Comment by NancyLi1013** [comment]
@ludekvodicka

You can use` vcpkg_fixup_cmake_targets(CONFIG_PATH "lib/cmake/ixwebsocket") `to solve this issue.

**Comment by ludekvodicka** [comment]
@NancyLi1013  Thanks! Victor Romero already helped me in another thread.

**Pull request merged**
