### PR TITLE
Added googletest and googlemock 1.8

### PR DESCRIPTION
**Pull request by KindDragon**

### CODE REVIEW

**Comment by KindDragon** [comment]
Should gtest, gmock be dll's or static libraries are fine?

**Comment by ras0219-msft** [comment]
Could you help me understand what the patch is needed for?

**Comment by KindDragon** [comment]
> Could you help me understand what the patch is needed for?

This patch fix compilation because of new warnings in VC2015, also it adds support std::unique_ptr and other C++11 types.

**Comment by ras0219-msft** [comment]
When building this locally, I get:
```
-- Performing post-build validation

The following dlls were found in /lib and /debug/lib. Please move them to /bin or /debug/bin, respectively.

    D:/src/vcpkg/packages/gtest_x86-windows/lib/gmock.dll
    D:/src/vcpkg/packages/gtest_x86-windows/lib/gmock_main.dll
    D:/src/vcpkg/packages/gtest_x86-windows/lib/gtest.dll
    D:/src/vcpkg/packages/gtest_x86-windows/lib/gtest_main.dll
    D:/src/vcpkg/packages/gtest_x86-windows/debug/lib/gmock.dll
    D:/src/vcpkg/packages/gtest_x86-windows/debug/lib/gmock_main.dll
    D:/src/vcpkg/packages/gtest_x86-windows/debug/lib/gtest.dll
    D:/src/vcpkg/packages/gtest_x86-windows/debug/lib/gtest_main.dll

Found 1 error(s). Please correct the portfile:
    D:\src\vcpkg\ports\gtest\portfile.cmake
```

**Comment by KindDragon** [comment]
Fixed

**Comment by Orvid** [comment]
These should probably be separate packages. Although using gmock requires gtest, gtest doesn't require gmock.

**Comment by ras0219-msft** [comment]
Are they independently versioned? If not, it's fine to leave them as one package.

**Comment by KindDragon** [comment]
Now they merge them to one repository https://github.com/google/googletest with one version for both of them

**Comment by ras0219-msft** [comment]
Alright, one package looks like the way to go then. Thanks!

**Pull request merged**
