### PR TITLE
[mimalloc] Update to 2.0.5

### LINKED ISSUE #23355: [mimalloc] update to 2.0.5
Library name: mimalloc

New version number: 2.0.5

Other information that may be useful: https://github.com/microsoft/mimalloc/releases/tag/v2.0.5

### PR DESCRIPTION
**Pull request by RT2Code**
Fix #23355

Update the mimalloc port from 2.0.3 to 2.0.5.

Changelog:
https://github.com/microsoft/mimalloc/releases/tag/v2.0.5

### CODE REVIEW

**Review by JonLiu1993 — APPROVED** [review]

**Comment by JonLiu1993** [comment]
@RT222 ,Thanks for your pr, looks CI tested failed in x86-windows triplet and x64-windows triplet,
This is error log:

````
-- Performing post-build validation

The following dlls were found in /lib or /debug/lib. Please move them to /bin or /debug/bin, respectively.

    D:/packages/mimalloc_x86-windows/lib/mimalloc-redirect32.dll


The following dlls were found in /lib or /debug/lib. Please move them to /bin or /debug/bin, respectively.

    D:/packages/mimalloc_x86-windows/debug/lib/mimalloc-redirect32.dll

Found 2 post-build check problem(s). To submit these ports to curated catalogs, please first correct the portfile:
    C:\a\1\s\ports\mimalloc\portfile.cmake
-- Performing post-build validation done
Error: Building package mimalloc:x86-windows failed with: POST_BUILD_CHECKS_FAILED
Elapsed time for package mimalloc:x86-windows: 4.24 s

Triplet: x86-windows
Total elapsed time: 20.56 s

````

**Comment by JonLiu1993** [comment]
@RT222 ,Ping for response!

**Comment by RT222** [comment]
My apologies for the late answer, it was a very busy week. I fixed the previous issue, but the CI still fails. Everything works fine on my end, so I suppose the problem is coming from the CI?

**Review by JonLiu1993 — APPROVED** [review]

**Comment by JonLiu1993** [comment]
> My apologies for the late answer, it was a very busy week. I fixed the previous issue, but the CI still fails. Everything works fine on my end, so I suppose the problem is coming from the CI?

Yeah, I have rerun the CI and all triplet tested successfully

**Comment by JonLiu1993** [comment]
All features are tested successfully in the following triplet:
- x86-windows
- x64-windows
- x64-windows-static

**Pull request merged**
