### PR TITLE
[blitz] Update to the latest commit and fix no dll and lib generated

### PR DESCRIPTION
**Pull request by NancyLi1013**
There are no dlls or libs generated by `blitz `current version on Windows platform in vcpkg.

So I update this port to the latest commit to fix this issue.

Related issue #10531 

Note: No features need to test.

### CODE REVIEW

**Comment by HerveAncher** [comment]
Dear @NancyLi1013  how can try to install Blitz via vcpkg with this PR?
It is possible to tell at vcpkg to use your repo instead its one?

**Comment by HerveAncher** [comment]
Done, I directly changed the value in my `portfile.cmake`.

And....... it works!! The DLL and library (static and dynamic) are properly copied at good places.

**Comment by HerveAncher** [comment]
Tested for x64-windows, installed is OK.
For x86-windows, compilation seems to failed.

**Comment by HerveAncher** [comment]
Finally it passed for x86-windows, the first there was an error about the write operation around `genvecbfn.exe` tools.

So it is OK under Windows 10, with standard tools provided by vcpkg (CMake 3.14.0 + Python 2.7.16)

**Review by PhoebeHui — APPROVED** [review]
LGTM

**Pull request merged**
