### PR TITLE
[libdatachannel] Update to 0.19.4

### PR DESCRIPTION
**Pull request by SergiusTheBest**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by dg0yt** [comment]
To further minimize the patch, you could move the `(set_target_properties(... PROPERTIES EXCLUDE_FROM_ALL 1)` into the `if(...)` clauses guarding the install commands. (Install one, exclude the other.)

**Comment by SergiusTheBest** [comment]
@dg0yt Indeed, thank you! Do you know do I need to run `./vcpkg x-add-version --all` again (after additional changes)?

**Comment by dg0yt** [comment]
Short answer: yes. But read the details.

Everytime you make changes to `ports/name`, the git-ref changes for this port. And that's why you have to run `x-add-version` again. But you also need the `--overwrite-version` option now, because it is the same PR and same new port-version.  You may also pass the actual port name instead of `--all`.

**Review by Adela0814 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the update and for making the patch much smaller!

**Pull request merged**
