### PR TITLE
[zbar] Add new port

### LINKED ISSUE #15968: [New Port Request] <ZBAR>
Library name: zbar

Library description: qrcode/ barcode ocr same with z-xing

Source repository URL: https://github.com/ZBar/ZBar

Project homepage (if different from the source repository):
https://github.com/ZBar/ZBar
Anything else that is useful to know when adding (such as optional features the library may have that should be included):

### PR DESCRIPTION
**Pull request by JaosonMa**
** add the zbar ports  **

-  Fixes #15968 #15970 

the zbar is same as zxing-cpp ，but it is good for some pices。

@JackBoosY

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
Hi @JaosonMa, does the change meet your requirements?

**Comment by JaosonMa** [comment]
> Hi @JaosonMa, does the change meet your requirements?

let me go to shoot，so much thanks!

**Comment by JaosonMa** [comment]
> > Hi @JaosonMa, does the change meet your requirements?
> 
> let me go to shoot，so much thanks!

我是不是可以关掉这个 pr了， 等待你们合并到master就行了是吗？

**Comment by JackBoosY** [comment]
@JaosonMa  Don't close this PR, waiting for merge it.

**Comment by JaosonMa** [comment]
> @JaosonMa Don't close this PR, waiting for merge it.

got you!

**Comment by Ulysses1337** [comment]
Well this is awkward.

This port uses the outdated ZBar/ZBar repo, but earlier issues #12510 and #13494 asked for mchehab's fork which is very much alive. Painfully I managed to get it to run on Windows x64 *and* produce a PDB (curse Autotools).

Now it's time to dot my i's and submit my effort, I thought, but I see a vastly different fork is about to get merged. Would the vcpkg team rather have One True ZBar or different flavors?

**Comment by JaosonMa** [comment]
> Well this is awkward.
> 
> This port uses the outdated ZBar/ZBar repo, but earlier issues #12510 and #13494 asked for mchehab's fork which is very much alive. Painfully I managed to get it to run on Windows x64 _and_ produce a PDB (curse Autotools).
> 
> Now it's time to dot my i's and submit my effort, I thought, but I see a vastly different fork is about to get merged. Would the vcpkg team rather have One True ZBar or different flavors?

这个zbar跟 pr的zbar 有什么区别和关联（派生）？
你为什么不提交一个这个ZBar的PR，我没有发现你这个zbar，我一直在用的也是我提交的这个zbar，我提交这个目前不能在win上编译使用，你这个可以吗？

**Comment by JaosonMa** [comment]
> > Well this is awkward.
> > This port uses the outdated ZBar/ZBar repo, but earlier issues #12510 and #13494 asked for mchehab's fork which is very much alive. Painfully I managed to get it to run on Windows x64 _and_ produce a PDB (curse Autotools).
> > Now it's time to dot my i's and submit my effort, I thought, but I see a vastly different fork is about to get merged. Would the vcpkg team rather have One True ZBar or different flavors?
> 
> 这个zbar跟 pr的zbar 有什么区别和关联（派生）？
> 你为什么不提交一个这个ZBar的PR，我没有发现你这个zbar，我一直在用的也是我提交的这个zbar，我提交这个目前不能在win上编译使用，你这个可以吗？

do i need use eng to reply you ?

**Comment by JaosonMa** [comment]
> Well this is awkward.
> 
> This port uses the outdated ZBar/ZBar repo, but earlier issues #12510 and #13494 asked for mchehab's fork which is very much alive. Painfully I managed to get it to run on Windows x64 _and_ produce a PDB (curse Autotools).
> 
> Now it's time to dot my i's and submit my effort, I thought, but I see a vastly different fork is about to get merged. Would the vcpkg team rather have One True ZBar or different flavors?

@Ulysses1337 Is mchehab / ZBar branched from ZBar? I hope you can give me a reply. If this is the latest and better version, we can try our best to add the best one instead of an outdated one. This is a good thing for all future users. This PR has not been merged, and we can change it, but we must ensure that it is a better one

**Comment by JaosonMa** [comment]
> @JaosonMa Don't close this PR, waiting for merge it.

don‘t  merge this pr，please . i want to check the Ulysses1337's reply.

**Comment by JackBoosY** [comment]
@JaosonMa We wan to use the official repo, or do you know any other repos such as sourceforge or directly link?

**Comment by JackBoosY** [comment]
@JaosonMa And do you know how to build zbar on Windows (not use mingw or other cross compile method)?

**Comment by JaosonMa** [comment]
> @JaosonMa We wan to use the official repo, or do you know any other repos such as sourceforge or directly link?

i got this：
https://sourceforge.net/projects/zbar/
https://sourceforge.net/projects/zbarw/
http://zbar.sourceforge.net/index.html

**Comment by JaosonMa** [comment]
> @JaosonMa @Ulysses1337 And do you know how to build zbar on Windows (not use mingw or other cross compile method)?

what i used now,  is the pre-build binaries

**Comment by JackBoosY** [comment]
Using mingw on Windows, configure error:
```
configure: WARNING: unrecognized options: --with-zlib-prefix, --with-libpng-prefix, --disable-silent-rules
./../src/76cb8a469e-d3eb821080.clean/config/config.guess: unable to guess system type

This script, last modified 2009-02-03, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from

  http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD
and
  http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD

If the version you run (./../src/76cb8a469e-d3eb821080.clean/config/config.guess) is already up to date, please
send the following data and any information you think might be
pertinent to <config-patches@gnu.org> in order to provide the needed
information to handle your system.

config.guess timestamp = 2009-02-03

uname -m = x86_64
uname -r = 3.1.6-340.x86_64
uname -s = MSYS_NT-10.0-18363
uname -v = 2020-08-14 15:42 UTC

/usr/bin/uname -p = unknown
/bin/uname -X     = 

hostinfo               = 
/bin/universe          = 
/usr/bin/arch -k       = 
/bin/arch              = x86_64
/usr/bin/oslevel       = 
/usr/convex/getsysinfo = 

UNAME_MACHINE = x86_64
UNAME_RELEASE = 3.1.6-340.x86_64
UNAME_SYSTEM  = MSYS_NT-10.0-18363
UNAME_VERSION = 2020-08-14 15:42 UTC
config.sub: too many arguments
Try `config.sub --help' for more information.
configure: error: /bin/sh ./../src/76cb8a469e-d3eb821080.clean/config/config.sub dummy.c
Microsoft (R) Incremental Linker Version 14.16.27045.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:dummy.exe 
/out:G:/15976/vcpkg/downloads/tools/msys2/9c897ff883069dc3/tmp/cginBVCZ/dummy.exe 
dummy.obj  failed
```

**Comment by JaosonMa** [comment]
> Using mingw on Windows, configure error:
> 
> ```
> configure: WARNING: unrecognized options: --with-zlib-prefix, --with-libpng-prefix, --disable-silent-rules
> ./../src/76cb8a469e-d3eb821080.clean/config/config.guess: unable to guess system type
> 
> This script, last modified 2009-02-03, has failed to recognize
> the operating system you are using. It is advised that you
> download the most up to date version of the config scripts from
> 
>   http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD
> and
>   http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD
> 
> If the version you run (./../src/76cb8a469e-d3eb821080.clean/config/config.guess) is already up to date, please
> send the following data and any information you think might be
> pertinent to <config-patches@gnu.org> in order to provide the needed
> information to handle your system.
> 
> config.guess timestamp = 2009-02-03
> 
> uname -m = x86_64
> uname -r = 3.1.6-340.x86_64
> uname -s = MSYS_NT-10.0-18363
> uname -v = 2020-08-14 15:42 UTC
> 
> /usr/bin/uname -p = unknown
> /bin/uname -X     = 
> 
> hostinfo               = 
> /bin/universe          = 
> /usr/bin/arch -k       = 
> /bin/arch              = x86_64
> /usr/bin/oslevel       = 
> /usr/convex/getsysinfo = 
> 
> UNAME_MACHINE = x86_64
> UNAME_RELEASE = 3.1.6-340.x86_64
> UNAME_SYSTEM  = MSYS_NT-10.0-18363
> UNAME_VERSION = 2020-08-14 15:42 UTC
> config.sub: too many arguments
> Try `config.sub --help' for more information.
> configure: error: /bin/sh ./../src/76cb8a469e-d3eb821080.clean/config/config.sub dummy.c
> Microsoft (R) Incremental Linker Version 14.16.27045.0
> Copyright (C) Microsoft Corporation.  All rights reserved.
> 
> /out:dummy.exe 
> /out:G:/15976/vcpkg/downloads/tools/msys2/9c897ff883069dc3/tmp/cginBVCZ/dummy.exe 
> dummy.obj  failed
> ```

[http://zbar.sourceforge.net/download.html](url)

> Windows Installer
Note that the Windows port is in an unstable, testing phase. If you do try it out, please let us know how well it's working for you and open a support request if you encounter any problems.

The Windows Installation Guide has detailed instructions for installing and getting started with ZBar on Windows.

ZBar 0.10 Windows installer
The Windows installer now includes pre-built binaries of the dependencies (ImageMagick et al). Copyright, license, and source code details for these libraries may be found in the README included with the distribution.

Windows binaries for the Python module are available from PyPI

-----------------------------------------



Can we directly put the compiled package of Windows environment provided by them into vcpkg?
https://nchc.dl.sourceforge.net/project/zbar/zbar/0.10/zbar-0.10-setup.exe
it include the bin,lib，include of win


I will keep study this . If i got somewhere, I will come back to update it.

**Comment by JackBoosY** [comment]
@JaosonMa We only accept building binary files if the port can be built.

**Comment by JaosonMa** [comment]
> @JaosonMa We only accept building binary files if the port can be built.

[https://github.com/JaosonMa/Jobs/tree/master/ZBar](url)
this is  the install resoult, it have the libs

**Comment by JackBoosY** [comment]
Trying to use the cross build method http://tuliopo.blogspot.com/2017/10/how-to-compile-zbar-with-mingw.html.

**Comment by Ulysses1337** [comment]
Whew! This thread has certainly grown.

> @JaosonMa @Ulysses1337 And do you know how to build zbar on Windows (not use mingw or other cross compile method)?

Yes, of course I took the idiomatic vcpkg_*_make() route and that's what I successfully got to work.

**Comment by JaosonMa** [comment]
> Whew! This thread has certainly grown.
> 
> > @JaosonMa @Ulysses1337 And do you know how to build zbar on Windows (not use mingw or other cross compile method)?
> 
> Yes, of course I took the idiomatic vcpkg_*_make() route and that's what I successfully got to work.

will you create a PR for zbar?

**Comment by Ulysses1337** [comment]
I was getting ready to, and then I found yours. :wink: I'm mainly waiting for input from @JackBoosY on where to go from here. Also it sounds like you need Linux and I need Windows support. I tried to make my port compile on Linux and failed. I lack the time and expertise.

**Comment by JackBoosY** [comment]
@Ulysses1337 I've change the repo to sourceforge, please let me know if you have any concern.

**Comment by Ulysses1337** [comment]
The ZBar/ZBar repos on both GH and SF are the same ancient codebase.

**Comment by JackBoosY** [comment]
@Ulysses1337 The problem is that other forks are unofficial.

**Comment by Ulysses1337** [comment]
The official one is (officially?) dead and mchehab's is the defacto replacement. Are we really going to shun one of the benefits of OSS?

**Comment by JackBoosY** [comment]
@Ulysses1337  Maybe we should an extra port named `mzbar`.

**Comment by Ulysses1337** [comment]
If different flavors are the team's preference, that's fine. A name that starts with zbar would make it easier to notice the alternative though. Lack of multiplatform notwithstanding, I imagine the installed binary names would conflict too. What's the policy on that?

**Comment by JackBoosY** [comment]
@Ulysses1337 We can add a message to `portfile.cmake` to notify users that there is a conflict between these two ports. And from the perspective of dependencies, these two ports will not be used at the same time.

Note that zbar is not officially compatible with Windows:
When I tried to support windows, the compiler reported many compile errors in the code.

**Comment by Ulysses1337** [comment]
OK, so no detection, just a message (`WARNING` level I assume). Would a name like `zbar-mchehab` be acceptable?

I got the core library to work fine on Windows with little patchwork, so don't worry about that.

**Comment by JackBoosY** [comment]
@Ulysses1337 That's acceptable.
You should add these codes to the head of portfile.cmake:
```cmake
if (EXISTS ${CURRENT_INSTALLED_DIR}/share/zbar/copyright)
    message(FATAL_ERROR "${PORT} conflicts with zbar, please remove zbar before installing ${PORT}.")
endif()
```

**Comment by Ulysses1337** [comment]
Right, that makes sense. I'll do my PR when I get a chance, thanks.

**Comment by ras0219-msft** [comment]
I think that we should _only_ package the new version, under the name "zbar-mchehab" or "mchehab-zbar" (to be hashed out in #16113). The original appears to be completely untouched for over 11 years.

**Comment by JackBoosY** [comment]
So I think this PR is not needed.

**Pull request closed without merging**
