### PR TITLE
[vcpkg] Move include ports.cmake after defining multiple macros

### PR DESCRIPTION
**Pull request by JackBoosY**
Due to cascading dependencies (such as _port1/vcpkg-port-config.cmake_ includes _host_port2/vcpkg-port-config.cmake_), macros such as `HOST_TRIPLET`, `CURRENT_HOST_INSTALLED_DIR` and `TRIPLET_SYSTEM_ARCH` may be used in _vcpkg-port-config.cmake_.

To solve the undefined problem of these macros in _vcpkg-port-config_, move the include _vcpkg-port-config_ code below the definitions.

Related: https://github.com/microsoft/vcpkg/pull/29882

### CODE REVIEW

**Comment by Neumann-A** [comment]
This is also in the meson 1.0 pr

**Comment by JackBoosY** [comment]
> This is also in the meson 1.0 pr

Looks like your PR is not done yet?

**Comment by Neumann-A** [comment]
Why? It only has baseline regressions.

**Comment by dg0yt** [comment]
> Why? It only has baseline regressions.

... and such regressions are very likely, given that this change triggers a world rebuild.

**Comment by JackBoosY** [comment]
In favor of https://github.com/microsoft/vcpkg/pull/28084

**Comment by JackBoosY** [comment]
Can anyone rerun  /azp run here?

**Comment by dg0yt** [comment]
AFAICT we still have at least [one blocker](https://dev.azure.com/vcpkg/public/_build/results?buildId=87796&view=results) for world rebuilds: qca needs another pkgconfig fix. (Triggered by other ports, but nevertheless...) So don't expect a green check mark.

**Comment by JackBoosY** [comment]
@MonicaLiu0311 Can rerun tests.

**Comment by dg0yt** [comment]
> Seems like olio issue is not fixed?

No, #30754 perhaps.

**Comment by JackBoosY** [comment]
Depends on https://github.com/microsoft/vcpkg/pull/30883

**Review by BillyONeal — APPROVED** [review]
I think this is great. I tagged vcpkg-team-review because I want to talk with the rest of the team about force merging around known baseline regressions like this when they produce failures that exactly match a CI run.

**Comment by BillyONeal** [comment]
I don't know why the macos machine got angry with you

**Review by BillyONeal — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thank you!

**Pull request merged**
