### PR TITLE
xalan-c: Remove use of obsolete unary_ and binary_function for C++17 compatibility

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
See [JIRA ticket](https://issues.apache.org/jira/projects/XALANC/issues/XALANC-775?filter=allopenissues) and [original C++17 patch branch](https://github.com/rleigh-codelibre/xalan-c/commits/c%2B%2B17-compat) which dates back to February with these patches split out for independent re-use.

With these patches applied, it's possible to use xalan-c in C++17 codebases compiled with `-std:c++17`.  Without the patches, `std::unary_function` and `std::binary_function` cause compilation to fail, since they were removed with C++17.

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for the PR!

I'd prefer to avoid committing these large patchfiles to the vcpkg tree if possible -- is there a stable URL that we could download them from instead? I see that the jira ticket has links, but I don't know how durable those will be (Do they get cleared when the bug closes? After a year? Never?).

**Comment by rleigh-codelibre** [comment]
I'm not sure about the JIRA links.

Have you considered an equivalent to [Homebrew formula-patches](https://github.com/Homebrew/formula-patches) for vcpkg?  For example [here](https://github.com/Homebrew/formula-patches/tree/master/xalan-c) are the xalan patches.  I'll also be putting them here, so could potentially be pulled by vcpkg.  But I'm unsure of the lifetime--it may well depend upon how long homebrew requires them before dropping them, which might not align with the vcpkg requirement.  And homebrew is often quite aggressive in their cleanups and changes.

If a `vcpkg-patches` or equivalent existed, I would be happy to put them there.

**Comment by rleigh-codelibre** [comment]
@ras0219-msft  I have split out the patches [here](https://github.com/rleigh-codelibre/vcpkg-patches/tree/ca09d69280469ce8f787c67b48f86e46a463ef5d/xalan-c) and then updated this PR to use them.  I hope this meets your requirements.  It downloads using the commit hash, so will be deterministic if the patches are updated by a future commit.  If you wanted to adopt this approach more generally by adopting a `vcpkg-patches` repository yourself, I'll be happy to transfer the repository to you, or to open a PR to add the patches to your repository.

Regards,
Roger

**Comment by rleigh-codelibre** [comment]
@ras0219-msft I've tested this locally with C++17 builds over the last few weeks using the latest VS2017 and it's all working fine for me.  Are the patches in the separate repository for download an acceptable strategy?

**Comment by ras0219-msft** [comment]
Yes, this LGTM; thanks for doing that!

We'll definitely consider opening a `vcpkg-patches` repo in the future, but for now this is a good solution.

Ready to merge pending CI!

**Comment by rleigh-codelibre** [comment]
Awesome, thanks!  I'll be happy to migrate these patches over to your patches repo as and when it becomes available.

**Comment by ras0219-msft** [comment]
Thanks again for the PR!

**Pull request merged**
