### PR TITLE
[mbedtls] Initial port.

### PR DESCRIPTION
**Pull request by icpz**
Initial port for mbedtls (from: https://github.com/ARMmbed/mbedtls)

## Notes
+ mbedtls is an open source, portable, easy to use, readable and flexible SSL library.
+ Uses cmake to build.
+ No patches applied.

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for the PR!

I think you simply need to use `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` instead of `WINDOWS_EXPORT_ALL_SYMBOLS`.

If that doesn't work, then simply add
```
set(VCPKG_LIBRARY_LINKAGE static)
```
to the top of the portfile to declare that you'll always produce static builds.

**Comment by lcdtyph** [comment]
@ras0219-msft 
Thanks for the guiding!

There're still some errors while building dynamic libs, which I think may need some patches to be fixed. But I'm a little busy this month... So I temporarily set ```VCPKG_LIBRARY_LINKAGE``` to static. I'll keep working on it next month. 

Could you please merge this PR if everything is OK~^_^

**Comment by ras0219-msft** [comment]
Looks great, thanks for the PR!

**Comment by lcdtyph** [comment]
Glad to be of help!~

**Pull request merged**
