### PR TITLE
[ryu]Fix linux problem with ccache

### PR DESCRIPTION
**Pull request by kreuzerkrieg**
- What does your PR fix? Fixes issue #
Error on Linux machines with ccache - "ccache: error: Failed to create temporary file for..."
- Which triplets are supported/not supported? 
As in initial PR
- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

### CODE REVIEW

**Comment by NancyLi1013** [comment]
Hi @kreuzerkrieg 
Thanks for this PR.
Could you please also bump the version as `2.0-1` in `CONTROL `file?
It seems that this port doesn't support `arm`, `uwp`, `x86`. If so, please update `vcpkg_fail_port_instll(ON_ARCH "x86" "arm" ON_TARGET "uwp")`.
Also add `Supports: !(uwp|arm|x86)` field to `CONTROL `file.

**Comment by kreuzerkrieg** [comment]
> Hi @kreuzerkrieg
> Thanks for this PR.
> Could you please also bump the version as `2.0-1` in `CONTROL `file?
> It seems that this port doesn't support `arm`, `uwp`, `x86`. If so, please update `vcpkg_fail_port_instll(ON_ARCH "x86" "arm" ON_TARGET "uwp")`.
> Also add `Supports: !(uwp|arm|x86)` field to `CONTROL `file.

Done

**Comment by kreuzerkrieg** [comment]
bump

**Review by NancyLi1013 — COMMENTED** [review]
It seems that we also need to update `vcpkg_fail_port_install(ON_TARGET "UWP")` as
`vcpkg_fail_port_install(ON_ARCH "x86" "arm" ON_TARGET "UWP")`.

**Comment by kreuzerkrieg** [comment]
oops! didnt push the change

**Review by NancyLi1013 — APPROVED** [review]

**Pull request merged**
