### PR TITLE
[boost] Fixup DLL names and fix v142 build issues

### PR DESCRIPTION
**Pull request by ras0219-msft**

### CODE REVIEW

**Comment by Rastaban** [comment]
Don't forget to check boost-iostreams #5042

**Comment by Neumann-A** [comment]
does this change the suffix of the boost libraries? If yes, vcpkg.cmake also contains a hardcoded boost-suffix in the find_package macro

**Comment by ras0219-msft** [comment]
This should not change the suffix of the _lib_ files. It only changes the dll suffixes.

**Pull request merged**
