### PR TITLE
Disable fluidlite in CI.

### PR DESCRIPTION
**Pull request by BillyONeal**
Fluidlite, added 3 days ago in https://github.com/microsoft/vcpkg/pull/13006 , tries to install the same files as fluidsynth; it's similar to the 'boringssl' situation. Given that fluidlite doens't have any dependencies, this change disables that one rather than fluidsynth,

```
Starting package 543/1349: fluidsynth:x86-windows
Building package fluidsynth[core]:x86-windows...
-- Downloading https://github.com/FluidSynth/fluidsynth/archive/2393aef3bd0b4e78084cfe16735d402bc1497edd.tar.gz...
-- Extracting source D:/downloads/FluidSynth-fluidsynth-2393aef3bd0b4e78084cfe16735d402bc1497edd.tar.gz
-- Applying patch force-x86-gentables.patch
-- Using source at D:/buildtrees/fluidsynth/src/2bc1497edd-d19340b672.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: D:/packages/fluidsynth_x86-windows/share/fluidsynth/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: W:\67\67c77d45b2c7b460f24349792075d19b9a2b218f.zip
Building package fluidsynth[core]:x86-windows... done
Installing package fluidsynth[core]:x86-windows...
The following files are already installed in D:/installed/x86-windows and are in conflict with fluidsynth:x86-windows

Installed by fluidlite:x86-windows
    include/fluidsynth/gen.h
    include/fluidsynth/log.h
    include/fluidsynth/misc.h
    include/fluidsynth/mod.h
    include/fluidsynth/settings.h
    include/fluidsynth/sfont.h
    include/fluidsynth/synth.h
    include/fluidsynth/types.h
    include/fluidsynth/version.h
    include/fluidsynth/voice.h

Elapsed time for package fluidsynth:x86-windows: 46.12 s
```

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
Should we add warning or error messages in portfile.cmake to warn users about conflicts?

**Comment by BillyONeal** [comment]
> Should we add warning or error messages in portfile.cmake to warn users about conflicts?

In this case I think we're OK without it because these 2 libraries appear somewhat specialized and it's unlikely that a user is going to want them both at once. We do have a warning like that for boringssl but that's because so many libraries list openssl as an explicit dependency, but nothing declares fluidsynth as an explicit dependency.

On the other hand I can see an argument that we should be consistent about it....

**Comment by BillyONeal** [comment]
Added warning message
image

**Review by JackBoosY — APPROVED** [review]

**Comment by Ghabry** [comment]
Oh. Yeah, sorry. I didn't consider this conflict. Disable it.

There is no use case for both libs at once (you only pick lite when you don't want this huge glib dependency)

**Pull request merged**
