### PR TITLE
[libpq ffmpeg] Fix the nls and iconv features

### PR DESCRIPTION
**Pull request by strega-nil**
cc @StarGate-One and issue #14681

### CODE REVIEW

**Comment by StarGate-One** [comment]
@strega-nil 
I already have all these patches from when I did a git pull done 11/19/2020 at 15:49 eastern.

Did I miss something?

**Comment by strega-nil** [comment]
@StarGate-One what do you mean?

**Comment by StarGate-One** [comment]
> @StarGate-One what do you mean?

@strega-nil 
See commit https://github.com/microsoft/vcpkg/commit/678e3057d60fe426dcc589f9fdcbb666b61e8604 [libpq/ffmpeg] PR Fix iconv/intl linkage not covered by CI (#14626)

**Comment by strega-nil** [comment]
@StarGate-One oops, I'm a dummy.

**Comment by StarGate-One** [comment]
@strega-nil we all have bad days - not a problem. Have a wonderful weekend.

**Pull request closed without merging**
