### PR TITLE
[libgeotiff] fix problems with config/targets

### LINKED ISSUE #6591: [libgeotiff] Missing debug config in share/geotiff
Reason:
Missing vcpkg_fixup_cmake_targets in portfile.

### LINKED ISSUE #6592: [libgeotiff] Missing find_dependency(PROJ4) in config file
If I read the configure logs correctly it tries to link target proj and not library proj supplied by proj config file. For this to work correctly libgeotiff must make a call to find_dependency(PROJ4) before including its target/depens cmake files.

### PR DESCRIPTION
**Pull request by Neumann-A**
closes #6591 
and
closes #6592

### CODE REVIEW

**Comment by Rastaban** [comment]
Only failing on Linux/OSX, probably because of the case sensitive filesystem:

```
CMake Error at scripts/cmake/vcpkg_fixup_cmake_targets.cmake:45 (message):
  
  '/home/vcpkg/myagent/_work/5/s/packages/libgeotiff_x64-linux/debug/share/GeoTIFF'
  does not exist.
Call Stack (most recent call first):
  ports/libgeotiff/portfile.cmake:41 (vcpkg_fixup_cmake_targets)
  scripts/ports.cmake:71 (include)
```

**Comment by Neumann-A** [comment]
nope linux install into share/cmake/GeoTIFF ....  how I like those errors..

**Comment by vicroms** [comment]
This seems to be working now. 

The reason for ❌ is that `vxl` and `openjpeg` were also built in the last CI run, and this two ports are mutually exclusive (`vxl` fails in the presence of `openjpeg`).
 
I'll delete the tombstone for `vxl` and rerun the tests, they should all pass without issues.

**Comment by vicroms** [comment]
✔️ at last.

Thanks @Neumann-A

**Pull request merged**
