### PR TITLE
[vcpkg-cmake] Fix parallel cmake

### LINKED ISSUE #21198: `vcpkg_cmake_configure` does not change the cwd on windows
While working on #21168 the following was detected:
It seems that `vcpkg_cmake_configure` does not change the cwd in contrast to `vcpkg_configure_cmake` on windows. 
The line `file(MAKE_DIRECTORY generated)` generates the following error on windows but not on other platforms:
```
CMake Error at CMakeLists.txt:13 (file):
  file attempted to create a directory:
  C:/Users/LeanderSchulten/git_projects/vcpkg/buildtrees/offscale-libetcd-cpp/src/fdb87cf638-60a9ea69fd.clean/generated
  into a source directory.
```

### PR DESCRIPTION
**Pull request by dg0yt**
- #### What does your PR fix?  
  Invoke parallel cmake from build directory (fixes vcpkg_cmake_configure does not change the cwd on windows #21198).

  This is the non-controversial part of #21507.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all, no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  yes

### CODE REVIEW

**Comment by autoantwort** [comment]
Nice! Can you then also remove the `DISABLE_PARALLEL_CONFIGURE` from the `offscale-libetcd-cpp` port? :)

**Comment by dg0yt** [comment]
> Nice! Can you then also remove the `DISABLE_PARALLEL_CONFIGURE` from the `offscale-libetcd-cpp` port? :)

It didn't work:
~~~
CMake Error at CMakeLists.txt:13 (file):
  file attempted to create a directory:
  D:/buildtrees/offscale-libetcd-cpp/src/fdb87cf638-60a9ea69fd.clean/generated
  into a source directory.
~~~
After another local test, I can confirm that `file(MAKE_DIRECTORY generated)` will always write to the source directory, not to cmake's current working directory. `offscale-libetcd-cpp` can't use parallel configure just with this change.

Commands run via `execute_process` inherit cmake's working directory, so this PR still makes sense for consistent behaviour.

**Comment by cenit** [comment]
> After another local test, I can confirm that `file(MAKE_DIRECTORY generated)` will always write to the source directory, not to cmake's current working directory. 

it should make the "generated" folder in the same folder in which the script containing the file command was, to be precise. So the main source directory, or a subfolder if it was an included script calling it.

**Comment by JackBoosY** [comment]
When building `plplot:x64-osx`:
```
/Users/vagrant/Data/installed/x64-osx/tools/llvm/flang: line 130: local: -n: invalid option
local: usage: local name[=value] ...
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_Fortran_PREPROCESS_SOURCE
CMake Error at /Users/vagrant/Data/downloads/tools/cmake-3.21.1-osx/cmake-3.21.1-macos-universal/CMake.app/Contents/share/cmake-3.21/Modules/CMakeDetermineCompilerABI.cmake:49 (try_compile):
  Failed to generate test project build system.
Call Stack (most recent call first):
  /Users/vagrant/Data/downloads/tools/cmake-3.21.1-osx/cmake-3.21.1-macos-universal/CMake.app/Contents/share/cmake-3.21/Modules/CMakeTestFortranCompiler.cmake:20 (CMAKE_DETERMINE_COMPILER_ABI)
  cmake/modules/fortran.cmake:44 (enable_language)
  cmake/modules/plplot.cmake:488 (include)
  CMakeLists.txt:125 (include)
```

**Comment by dg0yt** [comment]
Fortran issue on osx? Probably unrelated, just triggered via vcpkg-cmake.

**Comment by dg0yt** [comment]
`tinyfiledialog:arm64-windows`: Download error (Sourceforge temporarily down). Shouldn't this be hidden behind an asset cache?

**Review by JackBoosY — APPROVED** [review]

**Comment by BillyONeal** [comment]
> `tinyfiledialog:arm64-windows`: Download error (Sourceforge temporarily down). Shouldn't this be hidden behind an asset cache?

Unfortunately `vcpkg_from_git` isn't connected to asset caching and here we're forced to download sources because the port in question does not have a release archive available.

**Comment by BillyONeal** [comment]
Thanks for your help!

**Pull request merged**
