### PR TITLE
[mpg123] Upgrade to 1.28.2

### PR DESCRIPTION
**Pull request by evpobr**
* Upgrade to 1.28.2
* Remove patches accepted by upstream

### CODE REVIEW

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
`libopenmpt` might be fixed via #18933.

**Comment by BillyONeal** [comment]
> `libopenmpt` might be fixed via #18933.

Possible, but given that the error is:

```
/wd4996 /wd4100 /wd4018 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_WARNINGS /showIncludes /FoCMakeFiles\libopenmpt.dir\soundlib\SampleFormatMP3.cpp.obj /FdCMakeFiles\libopenmpt.dir\ /FS -c D:\buildtrees\libopenmpt\src\2d346efba4-15feadd66e.clean\soundlib\SampleFormatMP3.cpp
D:\buildtrees\libopenmpt\src\2d346efba4-15feadd66e.clean\soundlib\SampleFormatMP3.cpp(60): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\buildtrees\libopenmpt\src\2d346efba4-15feadd66e.clean\soundlib\SampleFormatMP3.cpp(60): error C2146: syntax error: missing ';' before identifier 'mpg123_ssize_t'
D:\buildtrees\libopenmpt\src\2d346efba4-15feadd66e.clean\soundlib\SampleFormatMP3.cpp(60): warning C4091: '': ignored on left of 'ptrdiff_t' when no variable is declared
```

the likely cause is that this change of mpg123 changed in which header, if at all, mpg123_ssize_t exists, and @evpobr could do that without needing that change which is a more extensive overhaul (and which is draft)

**Comment by NancyLi1013** [comment]
Hi @evpobr 

Could you please look into the above problem?

**Comment by evpobr** [comment]
@BillyONeal , @NancyLi1013 

Sorry for long delay. This PR is outdated, i've created #21565 to upgrade mpg123 to 1.29.2.

**Pull request closed without merging**
