### PR TITLE
[vcpkg] Fix broken link

### LINKED ISSUE #19121: [ffmpeg] build failure due to yasm cannot be accessed
Hi,

I noticed that vcpkg fetches `yasm` from this link: https://www.tortall.net/projects/yasm/snapshots/v1.3.0.6.g1962/yasm-1.3.0.6.g1962.exe which doesn't work at the moment because the website has a broken SSL certificate.

Is it possible to change it to this one instead?
https://github.com/yasm/yasm/releases/download/v1.3.0/yasm-1.3.0-win32.exe

At least we would avoid relying on a website which seem that have failed already once in the past ( see #7379 ).

Thank you in advance,
Julian

---

**Host Environment**
- OS: Windows 10 x64 - Azure DevOps
- Compiler: 19.29.30038.1

**To Reproduce**
`./vcpkg install ffmpeg[avcodec,avdevice,avfilter,avformat,avresample,core,gpl,nvcodec,opus,postproc,speex,swresample,swscale,theora,vorbis,vpx,x264,x265]:x86-windows-static`

**Failure logs** 
```
2021-07-25T21:14:48.7673368Z Building package ffmpeg[avcodec,avdevice,avfilter,avformat,avresample,core,gpl,nvcodec,opus,postproc,speex,swresample,swscale,theora,vorbis,vpx,x264,x265]:x86-windows-static...
2021-07-25T21:14:48.7674046Z -- Using community triplet x86-windows-static. This triplet configuration is not guaranteed to succeed.
2021-07-25T21:14:48.7674791Z -- [COMMUNITY] Loading triplet configuration from: C:\vcpkg\triplets\community\x86-windows-static.cmake
2021-07-25T21:14:48.7675661Z -- Installing port from location: C:\vcpkg\buildtrees\versioning\versions\ffmpeg\b118bc2a5cf855546dc3016de53c4d7c75d267b4
2021-07-25T21:15:22.3138511Z -- Downloading https://github.com/aria2/aria2/releases/download/release-1.35.0/aria2-1.35.0-win-32bit-build1.zip -> aria2-1.35.0-win-32bit-build1.zip...
2021-07-25T21:15:22.3148469Z -- Downloading ffmpeg-ffmpeg-n4.4.tar.gz...
2021-07-25T21:15:22.3153053Z -- Extracting source C:/vcpkg/downloads/ffmpeg-ffmpeg-n4.4.tar.gz
2021-07-25T21:15:22.3162773Z -- Applying patch 0001-create-lib-libraries.patch
2021-07-25T21:15:22.3166730Z -- Applying patch 0003-fix-windowsinclude.patch
2021-07-25T21:15:22.3173341Z -- Applying patch 0004-fix-debug-build.patch
2021-07-25T21:15:22.3181899Z -- Applying patch 0006-fix-StaticFeatures.patch
2021-07-25T21:15:22.3191492Z -- Applying patch 0007-fix-lib-naming.patch
2021-07-25T21:15:22.3195548Z -- Applying patch 0009-Fix-fdk-detection.patch
2021-07-25T21:15:22.3204534Z -- Applying patch 0010-Fix-x264-detection.patch
2021-07-25T21:15:22.3207143Z -- Applying patch 0011-Fix-x265-detection.patch
2021-07-25T21:15:22.3213878Z -- Applying patch 0012-Fix-ssl-110-detection.patch
2021-07-25T21:15:22.3220977Z -- Applying patch 0013-define-WINVER.patch
2021-07-25T21:15:22.3229428Z -- Applying patch 0014-avfilter-dependency-fix.patch
2021-07-25T21:15:22.3236978Z -- Applying patch 0015-Fix-xml2-detection.patch
2021-07-25T21:15:22.3244547Z -- Applying patch 0016-configure-dnn-needs-avformat.patch
2021-07-25T21:15:22.3253467Z -- Applying patch 0017-Patch-for-ticket-9019-CUDA-Compile-Broken-Using-MSVC.patch
2021-07-25T21:15:22.3261198Z -- Using source at C:/vcpkg/buildtrees/ffmpeg/src/n4.4-5002d86a54.clean
2021-07-25T21:15:22.3267788Z -- Downloading yasm-1.3.0.6.g1962.exe...
2021-07-25T21:15:22.3276890Z -- Downloading yasm-1.3.0.6.g1962.exe... Failed.
2021-07-25T21:15:22.3283696Z     Exit Code: 1
2021-07-25T21:15:22.3290829Z     See logs for more information:
2021-07-25T21:15:22.3298187Z         C:/vcpkg/downloads/download-yasm-1.3.0.6.g1962.exe-out.log
2021-07-25T21:15:22.3304385Z         C:/vcpkg/downloads/download-yasm-1.3.0.6.g1962.exe-err.log
2021-07-25T21:15:22.3310631Z         C:/vcpkg/downloads/download-yasm-1.3.0.6.g1962.exe-detailed.log
2021-07-25T21:15:22.3313839Z 
2021-07-25T21:15:22.3322043Z CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:251 (message):
2021-07-25T21:15:22.3325355Z 
2021-07-25T21:15:22.3331856Z       
2021-07-25T21:15:22.3335173Z 
2021-07-25T21:15:22.3343573Z       Failed to download file.
2021-07-25T21:15:22.3347587Z 
2021-07-25T21:15:22.3355852Z       If you use a proxy, please check your proxy setting. Possible causes are:
2021-07-25T21:15:22.3360466Z 
2021-07-25T21:15:22.3368727Z       
2021-07-25T21:15:22.3372279Z 
2021-07-25T21:15:22.3379934Z       1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
2021-07-25T21:15:22.3384893Z 
2021-07-25T21:15:22.3392845Z          to `https://address:port`. This is not correct, because `https://` prefix
2021-07-25T21:15:22.3396791Z 
2021-07-25T21:15:22.3406879Z          claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
2021-07-25T21:15:22.3411077Z 
2021-07-25T21:15:22.3417352Z          , etc..) is an HTTP proxy. Try setting `http://address:port` to both
2021-07-25T21:15:22.3420372Z 
2021-07-25T21:15:22.3431001Z          HTTP_PROXY and HTTPS_PROXY instead.
2021-07-25T21:15:22.3434950Z 
2021-07-25T21:15:22.3442692Z       
2021-07-25T21:15:22.3448082Z 
2021-07-25T21:15:22.3458547Z       2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
2021-07-25T21:15:22.3463599Z 
2021-07-25T21:15:22.3479845Z          will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
2021-07-25T21:15:22.3480655Z 
2021-07-25T21:15:22.3490521Z          Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
2021-07-25T21:15:22.3494315Z 
2021-07-25T21:15:22.3502648Z          Change `http=address:port;https=address:port` to `address`, and fill the port number.
2021-07-25T21:15:22.3506246Z 
2021-07-25T21:15:22.3513471Z       
2021-07-25T21:15:22.3516915Z 
2021-07-25T21:15:22.3524240Z       3. You proxy's remote server is out of service.
2021-07-25T21:15:22.3528289Z 
2021-07-25T21:15:22.3537308Z       
2021-07-25T21:15:22.3540922Z 
2021-07-25T21:15:22.3547434Z       In future vcpkg releases, if you are using Windows, you no longer need to set
2021-07-25T21:15:22.3551773Z 
2021-07-25T21:15:22.3559001Z       HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
2021-07-25T21:15:22.3562463Z 
2021-07-25T21:15:22.3569126Z       Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
2021-07-25T21:15:22.3572969Z 
2021-07-25T21:15:22.3579664Z       and (https://github.com/microsoft/vcpkg-tool/pull/77)
2021-07-25T21:15:22.3583062Z 
2021-07-25T21:15:22.3589491Z       
2021-07-25T21:15:22.3593232Z 
2021-07-25T21:15:22.3600364Z       Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues
2021-07-25T21:15:22.3603596Z 
2021-07-25T21:15:22.3607174Z 
2021-07-25T21:15:22.3610794Z 
2021-07-25T21:15:22.3619076Z Call Stack (most recent call first):
2021-07-25T21:15:22.3622385Z 
2021-07-25T21:15:22.3628813Z   scripts/cmake/vcpkg_find_acquire_program.cmake:551 (vcpkg_download_distfile)
2021-07-25T21:15:22.3632093Z 
2021-07-25T21:15:22.3640351Z   buildtrees/versioning/versions/ffmpeg/b118bc2a5cf855546dc3016de53c4d7c75d267b4/portfile.cmake:157 (vcpkg_find_acquire_program)
2021-07-25T21:15:22.3643360Z 
2021-07-25T21:15:22.3649737Z   scripts/ports.cmake:141 (include)
2021-07-25T21:15:22.3657553Z 
2021-07-25T21:15:22.3661473Z 
2021-07-25T21:15:22.3666761Z 
2021-07-25T21:15:22.3668908Z 
2021-07-25T21:15:22.3676024Z Error: Building package ffmpeg:x86-windows-static failed with: BUILD_FAILED
2021-07-25T21:15:22.3684456Z Please ensure you're using the latest portfiles with `.\vcpkg update`, then
2021-07-25T21:15:22.3692101Z submit an issue at https://github.com/Microsoft/vcpkg/issues including:
2021-07-25T21:15:22.3699598Z   Package: ffmpeg:x86-windows-static
2021-07-25T21:15:22.3706984Z   Vcpkg version: 2021-07-16-3be6b75f6972aa72ca34afce39168094432ea300
2021-07-25T21:15:22.3711151Z 
2021-07-25T21:15:22.3717654Z Additionally, attach any relevant sections from the log files above.
2021-07-25T21:15:22.9131278Z -- Running vcpkg install - failed
2021-07-25T21:15:36.9937094Z ##[error]CMake Error at C:/vcpkg/scripts/buildsystems/vcpkg.cmake:840 (message):
  vcpkg install failed.  See logs for more information:
  D:\a\1\s\.build\vcpkg-manifest-install.log
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.21/Modules/CMakeDetermineSystem.cmake:124 (include)
  CMakeLists.txt:61 (project)
2021-07-25T21:15:36.9955315Z -- Configuring incomplete, errors occurred!
2021-07-25T21:15:37.1147490Z Microsoft (R) Build Engine version 16.10.2+857e5a733 for .NET Framework
2021-07-25T21:15:37.1157540Z Copyright (C) Microsoft Corporation. All rights reserved.
2021-07-25T21:15:37.1158120Z 
2021-07-25T21:15:37.1196226Z MSBUILD : error MSB1009: Project file does not exist.
2021-07-25T21:15:37.1199617Z Switch: ALL_BUILD.vcxproj
2021-07-25T21:15:37.1370792Z 
2021-07-25T21:15:37.1376812Z 07/25 21:15:07 [[1;32mNOTICE[0m] Downloading 1 item(s)
2021-07-25T21:15:37.1379914Z 
2021-07-25T21:15:37.1398938Z 07/25 21:15:20 [[1;31mERROR[0m] CUID#7 - Download aborted. URI=https://www.tortall.net/projects/yasm/snapshots/v1.3.0.6.g1962/yasm-1.3.0.6.g1962.exe
2021-07-25T21:15:37.1409405Z Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://www.tortall.net/projects/yasm/snapshots/v1.3.0.6.g1962/yasm-1.3.0.6.g1962.exe
2021-07-25T21:15:37.1414466Z   -> [SocketCore.cc:1021] errorCode=1 SSL/TLS handshake failure: Error: The received certificate has expired.
2021-07-25T21:15:37.1422300Z (80090328)
2021-07-25T21:15:37.1426629Z 
2021-07-25T21:15:37.1434415Z 07/25 21:15:20 [[1;32mNOTICE[0m] Download GID#64cfd560f3ca394d not complete: C:/vcpkg/downloads/temp/yasm-1.3.0.6.g1962.exe
2021-07-25T21:15:37.1436992Z 
2021-07-25T21:15:37.1443510Z Download Results:
2021-07-25T21:15:37.1449944Z gid   |stat|avg speed  |path/URI
2021-07-25T21:15:37.1456110Z ======+====+===========+=======================================================
2021-07-25T21:15:37.1461847Z 64cfd5|ERR |       0B/s|C:/vcpkg/downloads/temp/yasm-1.3.0.6.g1962.exe
2021-07-25T21:15:37.1465095Z 
2021-07-25T21:15:37.1471249Z Status Legend:
2021-07-25T21:15:37.1478025Z (ERR):error occurred.
2021-07-25T21:15:37.1480885Z 
2021-07-25T21:15:37.1490976Z aria2 will resume download if the transfer is restarted.
2021-07-25T21:15:37.1498271Z If there are any errors, then see the log file. See '-l' option in help/man page for details.
2021-07-25T21:15:37.1506944Z 2021-07-25 21:15:07.655763 [INFO] [Context.cc:179] <<--- --- --- ---
2021-07-25T21:15:37.1511331Z 2021-07-25 21:15:07.656762 [INFO] [Context.cc:180]   --- --- --- ---
2021-07-25T21:15:37.1533735Z 2021-07-25 21:15:07.656762 [INFO] [Context.cc:181]   --- --- --- --->>
2021-07-25T21:15:37.1535392Z 2021-07-25 21:15:07.656762 [INFO] [Context.cc:182] aria2 1.35.0
2021-07-25T21:15:37.1598098Z 2021-07-25 21:15:07.656762 [INFO] [Context.cc:183] mingw-w64 6.0.0 (alpha) / gcc 8.3-win32 20190709
2021-07-25T21:15:37.1600299Z   built by  x86_64-pc-linux-gnu
2021-07-25T21:15:37.1601798Z   targeting i686-w64-mingw32
2021-07-25T21:15:37.1602853Z   on        Oct  6 2019 10:20:00
2021-07-25T21:15:37.1603825Z 2021-07-25 21:15:07.656762 [INFO] [Context.cc:184] Windows 6.2 Server (6.2)
2021-07-25T21:15:37.1605215Z 2021-07-25 21:15:07.656762 [INFO] [Context.cc:185] zlib/1.2.11 expat/2.2.7 sqlite3/3.29.0 GMP/6.1.2 c-ares/1.15.0 libssh2/1.9.0
2021-07-25T21:15:37.1606731Z 2021-07-25 21:15:07.656762 [INFO] [Context.cc:186] Logging started.
2021-07-25T21:15:37.1607447Z 2021-07-25 21:15:07.656762 [INFO] [SocketCore.cc:1585] Checking configured addresses
2021-07-25T21:15:37.1608040Z 2021-07-25 21:15:07.662799 [INFO] [SocketCore.cc:1649] Not considered: fe80::7d45:20e3:7961:5c5a%13
2021-07-25T21:15:37.1608817Z 2021-07-25 21:15:07.662799 [INFO] [SocketCore.cc:1646] Found configured address: 10.1.0.17
2021-07-25T21:15:37.1609382Z 2021-07-25 21:15:07.662799 [INFO] [SocketCore.cc:1649] Not considered: ::1
2021-07-25T21:15:37.1609933Z 2021-07-25 21:15:07.662799 [INFO] [SocketCore.cc:1649] Not considered: 127.0.0.1
2021-07-25T21:15:37.1610705Z 2021-07-25 21:15:07.662799 [INFO] [SocketCore.cc:1649] Not considered: fe80::7c05:2435:7eb3:e53b%9
2021-07-25T21:15:37.1611524Z 2021-07-25 21:15:07.662799 [INFO] [SocketCore.cc:1646] Found configured address: 172.18.176.1
2021-07-25T21:15:37.1612141Z 2021-07-25 21:15:07.662799 [INFO] [SocketCore.cc:1657] IPv4 configured=1, IPv6 configured=0
2021-07-25T21:15:37.1612862Z 2021-07-25 21:15:07.662799 [NOTICE] [Context.cc:311] Downloading 1 item(s)
2021-07-25T21:15:37.1613514Z 2021-07-25 21:15:07.663764 [DEBUG] [RequestGroupMan.cc:591] 1 RequestGroup(s) added.
2021-07-25T21:15:37.1620295Z 2021-07-25 21:15:07.664773 [DEBUG] [AbstractCommand.cc:184] CUID#7 - socket: read:0, write:0, hup:0, err:0
2021-07-25T21:15:37.1627077Z 2021-07-25 21:15:07.664773 [DEBUG] [FeedbackURISelector.cc:162] Selected from normCands
2021-07-25T21:15:37.1634729Z 2021-07-25 21:15:07.664773 [DEBUG] [FeedbackURISelector.cc:84] FeedbackURISelector selected https://www.tortall.net/projects/yasm/snapshots/v1.3.0.6.g1962/yasm-1.3.0.6.g1962.exe
2021-07-25T21:15:37.1641242Z 2021-07-25 21:15:07.664773 [DEBUG] [AbstractCommand.cc:184] CUID#7 - socket: read:0, write:0, hup:0, err:0
2021-07-25T21:15:37.1648943Z 2021-07-25 21:15:07.667792 [INFO] [AsyncNameResolverMan.cc:83] CUID#7 - Resolving hostname www.tortall.net
2021-07-25T21:15:37.1656941Z 2021-07-25 21:15:07.994832 [DEBUG] [AbstractCommand.cc:184] CUID#7 - socket: read:0, write:0, hup:0, err:0
2021-07-25T21:15:37.1665879Z 2021-07-25 21:15:07.994832 [INFO] [AbstractCommand.cc:817] CUID#7 - Name resolution complete: www.tortall.net -> 69.55.226.36
2021-07-25T21:15:37.1673972Z 2021-07-25 21:15:07.994832 [INFO] [HttpInitiateConnectionCommand.cc:123] CUID#7 - Connecting to 69.55.226.36:443
2021-07-25T21:15:37.1681357Z 2021-07-25 21:15:07.994832 [DEBUG] [AbstractCommand.cc:184] CUID#7 - socket: read:0, write:0, hup:0, err:0
2021-07-25T21:15:37.1690338Z 2021-07-25 21:15:08.148094 [DEBUG] [AbstractCommand.cc:184] CUID#7 - socket: read:0, write:1, hup:0, err:0
2021-07-25T21:15:37.1699215Z 2021-07-25 21:15:08.148094 [DEBUG] [AbstractCommand.cc:184] CUID#7 - socket: read:0, write:1, hup:0, err:0
2021-07-25T21:15:37.1706397Z 2021-07-25 21:15:08.148094 [DEBUG] [SocketCore.cc:926] Creating TLS session
2021-07-25T21:15:37.1714889Z 2021-07-25 21:15:08.149815 [DEBUG] [SocketCore.cc:946] TLS Handshaking
2021-07-25T21:15:37.1722837Z 2021-07-25 21:15:08.149815 [DEBUG] [WinTLSSession.cc:585] WinTLS: Starting/Resuming TLS Connect
2021-07-25T21:15:37.1729483Z 2021-07-25 21:15:08.149815 [DEBUG] [WinTLSSession.cc:604] WinTLS: Initializing handshake
2021-07-25T21:15:37.1737623Z 2021-07-25 21:15:08.150844 [DEBUG] [WinTLSSession.cc:630] WinTLS: Writing handshake
2021-07-25T21:15:37.1744321Z 2021-07-25 21:15:08.150844 [DEBUG] [WinTLSSession.cc:662] WinTLS: Reading handshake...
2021-07-25T21:15:37.1751330Z 2021-07-25 21:15:08.311323 [DEBUG] [AbstractCommand.cc:184] CUID#7 - socket: read:1, write:0, hup:0, err:0
2021-07-25T21:15:37.1758564Z 2021-07-25 21:15:08.311323 [DEBUG] [WinTLSSession.cc:585] WinTLS: Starting/Resuming TLS Connect
2021-07-25T21:15:37.1765686Z 2021-07-25 21:15:08.311323 [DEBUG] [WinTLSSession.cc:662] WinTLS: Reading handshake...
2021-07-25T21:15:37.1773616Z 2021-07-25 21:15:20.349778 [ERROR] [AbstractCommand.cc:351] CUID#7 - Download aborted. URI=https://www.tortall.net/projects/yasm/snapshots/v1.3.0.6.g1962/yasm-1.3.0.6.g1962.exe
2021-07-25T21:15:37.1780453Z Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://www.tortall.net/projects/yasm/snapshots/v1.3.0.6.g1962/yasm-1.3.0.6.g1962.exe
2021-07-25T21:15:37.1788973Z   -> [SocketCore.cc:1021] errorCode=1 SSL/TLS handshake failure: Error: The received certificate has expired.
2021-07-25T21:15:37.1797043Z (80090328)
2021-07-25T21:15:37.1804783Z 2021-07-25 21:15:20.349778 [DEBUG] [AbstractCommand.cc:479] CUID#7 - Aborting download
2021-07-25T21:15:37.1812430Z 2021-07-25 21:15:20.349778 [DEBUG] [AbstractCommand.cc:426] CUID#7 - Not trying next request. No reserved/pooled request is remaining and total length is still unknown.
2021-07-25T21:15:37.1819630Z 2021-07-25 21:15:20.349778 [DEBUG] [RequestGroup.cc:982] GID#64cfd560f3ca394d - Request queue check
2021-07-25T21:15:37.1827230Z 2021-07-25 21:15:20.349778 [DEBUG] [WinTLSSession.cc:176] WinTLS: Cannot close connection
2021-07-25T21:15:37.1835075Z 2021-07-25 21:15:20.350816 [NOTICE] [RequestGroupMan.cc:427] Download GID#64cfd560f3ca394d not complete: C:/vcpkg/downloads/temp/yasm-1.3.0.6.g1962.exe
2021-07-25T21:15:37.1841894Z 2021-07-25 21:15:20.350816 [DEBUG] [RequestGroup.cc:1172] GID#64cfd560f3ca394d - Creating DownloadResult.
2021-07-25T21:15:37.1848596Z 2021-07-25 21:15:20.350816 [DEBUG] [RequestGroupMan.cc:482] 1 RequestGroup(s) deleted.
```

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by nxtn**
**Describe the pull request**

- #### What does your PR fix?  
  Fixes #19121

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  windows, Yes

Their certificate is only valid for three months.

### CODE REVIEW

**Comment by NancyLi1013** [comment]
`tensorflow-cc:x64-windows-static` has been fixed by PR #19165

`kf5sonnet:x64-windows-static` will be fixed by PR #19323

**Comment by NancyLi1013** [comment]
@dan-shaw 
Could you please help take a look? 

https://www.tortall.net/projects/yasm/snapshots cannot be accessed now,

http://www.tortall.net/projects/yasm/snapshots seems not recommend to be used.

**Comment by BillyONeal** [comment]
I believe the URL is no longer broken.

**Comment by NancyLi1013** [comment]
Thanks for your information @BillyONeal. I can also access the URL now. 
Closing this PR since it should not be needed now.

**Pull request closed without merging**
