### PR TITLE
[gwenhywfar] update to 5.10.1, add support for windows

### PR DESCRIPTION
**Pull request by wrobelda**
**Describe the pull request**
Updates to 5.10.1, adds support for Windows.

- #### What does your PR fix?
  WIP
  - [ ] Depends on #18029 
  - [x] Depends on #26364 
  - [ ] Depends on #26340
  - [ ] Depends on #26619 for `[qt5]` feature on Windows

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  Should support all triplets, although some are skipped due to dependencies not supporting all platforms 

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by JonLiu1993** [comment]
Ping @wrobelda for response, Is work still being done for this PR?

**Comment by wrobelda** [comment]
> Ping @wrobelda for response, Is work still being done for this PR?

It's a Draft, eventually, yes.

**Comment by JonLiu1993** [comment]
@wrobelda , Can you please resolve the conflicts against master?

**Comment by JonLiu1993** [comment]
Pinging @wrobelda  for response. Is work still being done for this PR?

**Comment by JonLiu1993** [comment]
Closing this PR since it seems that no progress is being made. Please ping us to reopen if work is still being done.

**Pull request closed without merging**
