### PR TITLE
Upgrade Bond to 6.0.0

### PR DESCRIPTION
**Pull request by chwarr**
* Updated to the 6.0.0 release of Bond.
* Regenerated patches.

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for making the PR!

**Comment by ras0219-msft** [comment]
I got some boost MPL errors during the CI build. Could you confirm that `vcpkg install bond:x86-windows` works for you with the latest packages?

This is most easily reproduced by:
```
>git pull
>vcpkg remove --outdated
>vcpkg install bond
```

```
2017-07-14T23:25:10.7051011Z      4>D:\vcpkg-live-ci\_work\1\s\installed\x86-windows\include\boost/mpl/push_front.hpp(31): error C2903: 'apply': symbol is neither a class template nor a function template (compiling source file D:\vcpkg-live-ci\_work\1\s\buildtrees\bond\src\bond-6.0.0\cpp\generated\bond\core\bond_types.cpp) [D:\vcpkg-live-ci\_work\1\s\buildtrees\bond\x86-windows-rel\cpp\bond.vcxproj]
2017-07-14T23:25:10.7051011Z          d:\vcpkg-live-ci\_work\1\s\buildtrees\bond\src\bond-6.0.0\cpp\generated\bond\core\bond_reflection.h(46): note: see reference to class template instantiation 'boost::mpl::push_front<bond::SerializableExceptionBase::Schema::fields0,bond::SerializableExceptionBase::Schema::var::message>' being compiled (compiling source file D:\vcpkg-live-ci\_work\1\s\buildtrees\bond\src\bond-6.0.0\cpp\generated\bond\core\bond_types.cpp)
2017-07-14T23:25:10.7051011Z      4>D:\vcpkg-live-ci\_work\1\s\installed\x86-windows\include\boost/mpl/push_front.hpp(31): error C3770: 'unknown-type': is not a valid base class (compiling source file D:\vcpkg-live-ci\_work\1\s\buildtrees\bond\src\bond-6.0.0\cpp\generated\bond\core\bond_types.cpp) [D:\vcpkg-live-ci\_work\1\s\buildtrees\bond\x86-windows-rel\cpp\bond.vcxproj]
2017-07-14T23:25:10.7051011Z      4>d:\vcpkg-live-ci\_work\1\s\buildtrees\bond\src\bond-6.0.0\cpp\generated\bond\core\bond_reflection.h(46): error C2039: 'type': is not a member of 'boost::mpl::push_front<bond::SerializableExceptionBase::Schema::fields0,bond::SerializableExceptionBase::Schema::var::message>' (compiling source file D:\vcpkg-live-ci\_work\1\s\buildtrees\bond\src\bond-6.0.0\cpp\generated\bond\core\bond_types.cpp) [D:\vcpkg-live-ci\_work\1\s\buildtrees\bond\x86-windows-rel\cpp\bond.vcxproj]
2017-07-14T23:25:10.7051011Z          d:\vcpkg-live-ci\_work\1\s\buildtrees\bond\src\bond-6.0.0\cpp\generated\bond\core\bond_reflection.h(46): note: see declaration of 'boost::mpl::push_front<bond::SerializableExceptionBase::Schema::fields0,bond::SerializableExceptionBase::Schema::var::message>' (compiling source file D:\vcpkg-live-ci\_work\1\s\buildtrees\bond\src\bond-6.0.0\cpp\generated\bond\core\bond_types.cpp)
2017-07-14T23:25:10.7051011Z      4>d:\vcpkg-live-ci\_work\1\s\buildtrees\bond\src\bond-6.0.0\cpp\generated\bond\core\bond_reflection.h(46): error C3646: 'fields1': unknown override specifier (compiling source file D:\vcpkg-live-ci\_work\1\s\buildtrees\bond\src\bond-6.0.0\cpp\generated\bond\core\bond_types.cpp) [D:\vcpkg-live-ci\_work\1\s\buildtrees\bond\x86-windows-rel\cpp\bond.vcxproj]
2017-07-14T23:25:10.7051011Z      4>d:\vcpkg-live-ci\_work\1\s\buildtrees\bond\src\bond-6.0.0\cpp\generated\bond\core\bond_reflection.h(46): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file D:\vcpkg-live-ci\_work\1\s\buildtrees\bond\src\bond-6.0.0\cpp\generated\bond\core\bond_types.cpp) [D:\vcpkg-live-ci\_work\1\s\buildtrees\bond\x86-windows-rel\cpp\bond.vcxproj]
2017-07-14T23:25:10.7051011Z      4>d:\vcpkg-live-ci\_work\1\s\buildtrees\bond\src\bond-6.0.0\cpp\generated\bond\core\bond_reflection.h(48): error C2653: 'fields1': is not a class or namespace name (compiling source file D:\vcpkg-live-ci\_work\1\s\buildtrees\bond\src\bond-6.0.0\cpp\generated\bond\core\bond_types.cpp) [D:\vcpkg-live-ci\_work\1\s\buildtrees\bond\x86-windows-rel\cpp\bond.vcxproj]
2017-07-14T23:25:10.7051011Z      4>d:\vcpkg-live-ci\_work\1\s\buildtrees\bond\src\bond-6.0.0\cpp\generated\bond\core\bond_reflection.h(146): error C2039: 'type': is not a member of 'boost::mpl::push_front<bond::GUID::Schema::fields0,bond::GUID::Schema::var::Data4>' (compiling source file D:\vcpkg-live-ci\_work\1\s\buildtrees\bond\src\bond-6.0.0\cpp\generated\bond\core\bond_types.cpp) [D:\vcpkg-live-ci\_work\1\s\buildtrees\bond\x86-windows-rel\cpp\bond.vcxproj]
2017-07-14T23:25:10.7051011Z          d:\vcpkg-live-ci\_work\1\s\buildtrees\bond\src\bond-6.0.0\cpp\generated\bond\core\bond_reflection.h(146): note: see declaration of 'boost::mpl::push_front<bond::GUID::Schema::fields0,bond::GUID::Schema::var::Data4>' (compiling source file D:\vcpkg-live-ci\_work\1\s\buildtrees\bond\src\bond-6.0.0\cpp\generated\bond\core\bond_types.cpp)
2017-07-14T23:25:10.7051011Z      4>d:\vcpkg-live-ci\_work\1\s\buildtrees\bond\src\bond-6.0.0\cpp\generated\bond\core\bond_reflection.h(146): error C3646: 'fields1': unknown override specifier (compiling source file D:\vcpkg-live-ci\_work\1\s\buildtrees\bond\src\bond-6.0.0\cpp\generated\bond\core\bond_types.cpp) [D:\vcpkg-live-ci\_work\1\s\buildtrees\bond\x86-windows-rel\cpp\bond.vcxproj]
2017-07-14T23:25:10.7051011Z      4>d:\vcpkg-live-ci\_work\1\s\buildtrees\bond\src\bond-6.0.0\cpp\generated\bond\core\bond_reflection.h(146): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file D:\vcpkg-live-ci\_work\1\s\buildtrees\bond\src\bond-6.0.0\cpp\generated\bond\core\bond_types.cpp) [D:\vcpkg-live-ci\_work\1\s\buildtrees\bond\x86-windows-rel\cpp\bond.vcxproj]
2017-07-14T23:25:10.7051011Z      4>d:\vcpkg-live-ci\_work\1\s\buildtrees\bond\src\bond-6.0.0\cpp\generated\bond\core\bond_reflection.h(147): error C2065: 'fields1': undeclared identifier (compiling source file D:\vcpkg-live-ci\_work\1\s\buildtrees\bond\src\bond-6.0.0\cpp\generated\bond\core\bond_types.cpp) [D:\vcpkg-live-ci\_work\1\s\buildtrees\bond\x86-windows-rel\cpp\bond.vcxproj]
2017-07-14T23:25:10.7051011Z      4>d:\vcpkg-live-ci\_work\1\s\buildtrees\bond\src\bond-6.0.0\cpp\generated\bond\core\bond_reflection.h(147): error C2923: 'boost::mpl::push_front': 'fields1' is not a valid template type argument for parameter 'Sequence' (compiling source file D:\vcpkg-live-ci\_work\1\s\buildtrees\bond\src\bond-6.0.0\cpp\generated\bond\core\bond_types.cpp) [D:\vcpkg-live-ci\_work\1\s\buildtrees\bond\x86-windows-rel\cpp\bond.vcxproj]
2017-07-14T23:25:10.7051011Z      4>d:\vcpkg-live-ci\_work\1\s\buildtrees\bond\src\bond-6.0.0\cpp\generated\bond\core\bond_reflection.h(147): error C2955: 'boost::mpl::push_front': use of class template requires template argument list (compiling source file D:\vcpkg-live-ci\_work\1\s\buildtrees\bond\src\bond-6.0.0\cpp\generated\bond\core\bond_types.cpp) [D:\vcpkg-live-ci\_work\1\s\buildtrees\bond\x86-windows-rel\cpp\bond.vcxproj]
2017-07-14T23:25:10.7051011Z          D:\vcpkg-live-ci\_work\1\s\installed\x86-windows\include\boost/mpl/push_front.hpp(30): note: see declaration of 'boost::mpl::push_front' (compiling source file D:\vcpkg-live-ci\_work\1\s\buildtrees\bond\src\bond-6.0.0\cpp\generated\bond\core\bond_types.cpp)
2017-07-14T23:25:10.7051011Z      4>d:\vcpkg-live-ci\_work\1\s\buildtrees\bond\src\bond-6.0.0\cpp\generated\bond\core\bond_reflection.h(147): error C2039: 'type': is not a member of 'boost::mpl::push_front<Sequence,T>' (compiling source file D:\vcpkg-live-ci\_work\1\s\buildtrees\bond\src\bond-6.0.0\cpp\generated\bond\core\bond_types.cpp) [D:\vcpkg-live-ci\_work\1\s\buildtrees\bond\x86-windows-rel\cpp\bond.vcxproj]
2017-07-14T23:25:10.7207254Z      4>d:\vcpkg-live-ci\_work\1\s\buildtrees\bond\src\bond-6.0.0\cpp\generated\bond\core\bond_reflection.h(148): error C2039: 'type': is not a member of 'boost::mpl::push_front<bond::GUID::Schema::fields2,bond::GUID::Schema::var::Data2>' (compiling source file D:\vcpkg-live-ci\_work\1\s\buildtrees\bond\src\bond-6.0.0\cpp\generated\bond\core\bond_types.cpp) [D:\vcpkg-live-ci\_work\1\s\buildtrees\bond\x86-windows-rel\cpp\bond.vcxproj]

```

**Comment by chwarr** [comment]
Checking...

**Comment by chwarr** [comment]
I'm not able to reproduce these compiler errors. I have two hypothesises.

1. Are you using a pre-release version of the Visual C++ compiler? vcpkg just built with MSVC 19.10.25019.0 and my [simple test project](https://github.com/chwarr/bond-via-vcpkg) is able to consume this lib fine. (Build details below.)
1. What does the generated header in the file `.\buildtrees\bond\src\bond-6.0.0\cpp\generated\bond\core\bond_reflection.h` say? It should have "Tool : Bond Compiler 0.10.0.0" near the top. If it has a different version, then the wrong `gbc` codegen tool is getting found--likely due to a bug in the Bond CMake files.

Build details from a clean vcpkg repository:

```
7/14/2017 5:16:30 PM :: chwarr@CHWARR-DESK :: S:\src\vcpkg
  [master] [9] > git show
commit 5a74d30aab81e2e0d1f210117fa05e76b39b5fab
Merge: f8e13e7b e235ab75
Author: Robert Schumacher <roschuma@microsoft.com>
Date:   Fri Jul 14 16:23:43 2017 -0700

    Merge pull request #1462 from chwarr/bond-6.0.0

    Upgrade Bond to 6.0.0

7/14/2017 5:16:53 PM :: chwarr@CHWARR-DESK :: S:\src\vcpkg
  [master] [10] > .\bootstrap-vcpkg.bat > booststrap.log
7/14/2017 5:17:40 PM :: chwarr@CHWARR-DESK :: S:\src\vcpkg
  [master] [11] > .\vcpkg.exe install --triplet x86-windows bond
The following packages will be built and installed:
    bond:x86-windows
  * boost:x86-windows
  * bzip2:x86-windows
  * rapidjson:x86-windows
  * zlib:x86-windows
Additional packages (*) will be installed to complete this operation.
Building package zlib:x86-windows...
...
Building package bond:x86-windows...
-- CURRENT_INSTALLED_DIR=S:/src/vcpkg/installed/x86-windows
-- DOWNLOADS=S:/src/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=S:/src/vcpkg/packages/bond_x86-windows
-- CURRENT_BUILDTREES_DIR=S:/src/vcpkg/buildtrees/bond
-- CURRENT_PORT_DIR=S:/src/vcpkg/ports/bond/.
-- Warning: Dynamic building not supported yet. Building static.
-- Downloading https://github.com/Microsoft/bond/archive/6.0.0.zip...
-- Downloading https://github.com/Microsoft/bond/archive/6.0.0.zip... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Downloading https://github.com/Microsoft/bond/releases/download/6.0.0/gbc-6.0.0-amd64.exe.zip...
-- Downloading https://github.com/Microsoft/bond/releases/download/6.0.0/gbc-6.0.0-amd64.exe.zip... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Extracting source S:/src/vcpkg/downloads/bond-6.0.0.zip
-- Extracting done
-- Extracting source S:/src/vcpkg/downloads/gbc-6.0.0-amd64.zip
-- Extracting done
-- Applying patch S:/src/vcpkg/ports/bond/0001_boost_static_libs.patch
-- Applying patch S:/src/vcpkg/ports/bond/0001_boost_static_libs.patch done
-- Applying patch S:/src/vcpkg/ports/bond/0002_omit_rapidjson.patch
-- Applying patch S:/src/vcpkg/ports/bond/0002_omit_rapidjson.patch done
-- Configuring x86-windows-rel
-- Configuring x86-windows-rel done
-- Configuring x86-windows-dbg
-- Configuring x86-windows-dbg done
-- Package x86-windows-rel
-- Package x86-windows-rel done
-- Package x86-windows-dbg
-- Package x86-windows-dbg done
-- Performing post-build validation
-- Performing post-build validation done
Building package bond:x86-windows... done
Installing package bond:x86-windows...
Installing package bond:x86-windows... done
```

**Comment by ras0219-msft** [comment]
You're exactly right, this was caused by a prerelease compiler version. Sorry for the trouble, everything is working now!

**Pull request merged**
