### PR TITLE
[openssl] Restore Blowfish cipher in OpenSSL

### LINKED ISSUE #17183: How do I configure OpenSSL package?
In the latest OpenSSL package for Linux, one can find in opensslconf.h among other things:

    #ifndef OPENSSL_NO_BF
    # define OPENSSL_NO_BF
    #endif

This effectively removes Blowfish encoding functions from the library. Can some option be added for us to reenable them somehow in the package?
Why Blowfish was removed only from Linux build and not from Windows?

### PR DESCRIPTION
**Pull request by EricHripko**
OpenSSL port today excludes Blowfish cipher on *nix platforms. I couldn't find a particular reason for why that is in `git blame` and this is still a useful cipher to have for some older systems. This PR removes `no-bf` flag to restore Blowfish cipher on *nix and bring consistency across supported platforms.

- #### What does your PR fix?  
  Fixes #17183

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
- Only changes *nix port. As far as I can tell, Windows already has this cipher enabled

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
- I believe so

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
- Yes

### CODE REVIEW

**Review by NancyLi1013 — COMMENTED** [review]
Could you please also update `port-version` in vcpkg.json file?

**Comment by EricHripko** [comment]
Thank you for your prompt feedback @NancyLi1013 - I've bumped the version 🙂

**Comment by autoantwort** [comment]
>  If you have added/updated a port: Have you run ./vcpkg x-add-version --all and committed the result?

You have updated a port, so you have to :)

**Comment by NancyLi1013** [comment]
Please also run .\vcpkg x-add-version openssl to update version files and then submit the changes.

**Comment by EricHripko** [comment]
Should be done now 🙂 Please let me know if you have any other feedback

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
> Should be done now 🙂 Please let me know if you have any other feedback

Let's wait for CI test result. Currently, there is nothing needs to be done on your sides.

**Comment by NancyLi1013** [comment]
> CI appears to be passing - could this be landed now? 🙂

Yes, this is ready for merge now.

**Comment by strega-nil-ms** [comment]
lgtm, thanks!

**Pull request merged**
