### PR TITLE
[pixman] fix build on M1 macs

### PR DESCRIPTION
**Pull request by autoantwort**
pixman checks the host and not the target cpu for cpu features

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]
Can you please also make a PR to the upstream?

Thanks.

**Comment by autoantwort** [comment]
I have created https://gitlab.freedesktop.org/pixman/pixman/-/issues/54

**Comment by JackBoosY** [comment]
Waiting for upstream reply.

**Comment by ras0219-msft** [comment]
I think this is the right fix for vcpkg, because the user can instead directly add any desired cpu set flags to their global cflags. Therefore, there isn't a need for ad-hoc per-library detection.

**Comment by ras0219-msft** [comment]
LGTM, thanks!

**Pull request merged**
