### PR TITLE
[add platform_toolset ClangCL] msbuild ClangCL (?)

### PR DESCRIPTION
**Pull request by MVoz**
test only triplet x64-windows, only **msbuild project** 
     and cmake -T"" **msbuild** // CMAKE_GENERATOR "Visual Studio"

### CODE REVIEW

**Comment by Voskrese** [comment]
test ok msbuild clangcl
https://github.com/microsoft/vcpkg/runs/768381200

**Comment by Voskrese** [comment]
test ok cmake -T"ClangCL"

**Comment by NancyLi1013** [comment]
@Voskrese 
Does this PR need some reviews from us?

**Comment by Voskrese** [comment]
@NancyLi1013 
Yes, need feedback and comments in particular ))

**Comment by Voskrese** [comment]
закрою, вдруг виртуальную машину \ образ сломаю ;)

**Pull request closed without merging**
