### PR TITLE
libmupdf initial port

### PR DESCRIPTION
**Pull request by glachancecmaisonneuve**
-For some reason the linting process kept nagging at me until I set both VCPKG_LIBRARY_LINKAGE **and** VCPKG_CRT_LINKAGE to static.  
-While creating the port, I saw that _sumatrapdf_ actually builds a non-static version of this library.  The source provided by libmupdf.org are all geared towards a static build.  The non-static sumatrapdf build of libmupdf seems pretty intricate and involves a custom module-definition file for the linker and something I don't quite grasp yet having to do with a resource file.  I guess what I'm asking is "how hard should I try to provide a non-static build" for this port?

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for the PR!

If the upstream sources seem totally incompatible with a non-static build, then it's fine to simply use[1]
```cmake
if (VCPKG_LIBRARY_LINKAGE STREQUAL dynamic)
    message(STATUS "Warning: Dynamic building not supported yet. Building static.")
    set(VCPKG_LIBRARY_LINKAGE static)
endif()
```

However, I am somewhat concerned about the linting issue. What was the message, specifically?

[1] Example from: https://github.com/Microsoft/vcpkg/blob/83464ec5b70ac881972600dfcea1a02644c80b03/ports/fcl/portfile.cmake#L3-L6

**Comment by glachancecmaisonneuve** [comment]
> Since you're providing a replacement buildsystem anyway (the vcxproj)
I get that vcxproj at very little cost, by running vcupgrade (or devenv /upgrade) on the provided, made-for-older-msbuild vcproj.  I would script it rather than provide the upgraded project manually I could find a reliable way to do so.  Even better would be the ability to force msbuild to build vcproj (not the newer vcprojs, the old ones) project files but no combination of switches have ever allowed me to do so without first upgrading to vcXproj project file first.

>generally portfiles shouldn't be switching the CRT linkage because it will likely result in unusable binaries
Let me double check on that one.

**Comment by glachancecmaisonneuve** [comment]
About having to set VCPKG_CRT_LINKAGE:
- What I wrote needs some clarification: I only get linting problems when vcpkg expects a **dynamic** library but I provide a **static** one instead of failing.  For example the command ```vcpkg install libmupdf:x64-windows``` should fail, however it does not by virtue of the port file adjusting the build to static (set VCPKG_LIBRARY_LINKAGE static). 
- Asking for (and getting) a static build works without linting issues every time.  ```vcpkg install libmupdf:x64-windows-static```
- The resulting packages vcpkg/packages/libmupdf-x64-static and vcpkg/packages/libmupdf-x64 folders and byte-to-byte compare identical.

If I only ```set VCPKG_LIBRARY_LINKAGE static```, the linting process complains that it 
> Expected Debug,**Dynamic** crt linkage but [...] got [...] Debug,Static

To me the linking process is as close as you can get to real magic.  Any advice on how to proceed further?

**Comment by slyshykO** [comment]
Maybe this article https://www.codeproject.com/Articles/1190061/Compiling-MuPDF-DLL-to-Render-and-Edit-PDF-Documen can help make a DLL build.

**Comment by glachancecmaisonneuve** [comment]
I won't make any further modifications on this pull request because I don't have the expertise to maintain a cmake build system for this (or any) library.  I also didn't want to close the branch because that would likely mean losing what Robert commited.

**Comment by ras0219-msft** [comment]
Thanks!

**Pull request merged**
