### PR TITLE
[python3] fix compatibility with macOS 11 big sur

### PR DESCRIPTION
**Pull request by cenit**
**Describe the pull request**
fix compatibility with macOS Big Sur

### CODE REVIEW

**Comment by cenit** [comment]
Almost sure that qt5-location is broken not because of this PR

**Comment by Hoikas** [comment]
Big Sur is fixed in 3.9.0 according to the Python release notes. See #14510.

**Comment by JackBoosY** [comment]
@cenit what do you think? should we wait for #14510 merge?

**Comment by cenit** [comment]
This PR should be much lighter and unblock macOS 11, while waiting for the very nice update to python 3.9. The problem was especially in the new number. Nothing very serious beside that is applied in this patch, which is already in use in the homebrew port.

**Review by JackBoosY — APPROVED** [review]

**Comment by Hoikas** [comment]
I disagree. The patch included here was introduced into python 3.8.4 and does not in fact completely support big sur, as mentioned in the python release notes. It merely fixes the error in the configure script. At bare minimum, the port should be bumped to 3.8.4. The correct fix is to adopt #14510, which is ready (except for false negatives in the baseline).

**Comment by Hoikas** [comment]
See also: [Python 3.8 Changelog](https://docs.python.org/3.8/whatsnew/changelog.html#id31)

**Comment by strega-nil** [comment]
Closed in favor of #14510

**Pull request closed without merging**
