### PR TITLE
[glm] Bump to 2023-06-08 & fix usage

### PR DESCRIPTION
**Pull request by xiaozhuai**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

1. Bump to 0.9.9.8+20230608. Since latest release (0.9.9.8) of glm is about 3 years ago, there have been many important fixes and improvements during this time. 
2. Fix usage

### CODE REVIEW

**Review by BillyONeal — DISMISSED** [review]

**Comment by LilyWangLL** [comment]
Usage passed on `x64-windows`.

**Review by LilyWangLL — DISMISSED** [review]

**Comment by BillyONeal** [comment]
Unfortunately for version precedence rules `0.9.9.8+20230608` == `0.9.9.8`, as things after the + are the 'build metadata' and not relevant for purposes of ordering.

@christophe-lunarg Any chance of glm doing a real release soon?

**Comment by xiaozhuai** [comment]
> If upstream won't do a release I think we have no choice but to switch to version-date.

@BillyONeal 
How about keep the version `0.9.9.8` and just increase port-version?

**Comment by BillyONeal** [comment]
> @BillyONeal How about keep the version `0.9.9.8` and just increase port-version?

That would sort the right way. Do you think users would be 'surprised' at the changes they get since then? Has upstream indicated they are going for 'live at head'? If the changes since then aren't 'small bugfixes' then I think we should go `version-date`.

**Comment by dg0yt** [comment]
> Do you think users would be 'surprised' at the changes they get since then?

Repology will say that vcpkg is lying about the version.

> for version precedence rules 0.9.9.8+20230608 == 0.9.9.8

Then how about using `0.9.9.8+20230608` **and** increasing the port number?
(I guess the key difficulty is explaining this to the reviewers...)

**Comment by xiaozhuai** [comment]
> Then how about using 0.9.9.8+20230608 and increasing the port number?

I vote this.

@BillyONeal @dg0yt 

What's your opinion？

**Comment by xiaozhuai** [comment]
@BillyONeal @dg0yt 
It looks like there is no interest upstream in releasing a new version, I've update this pr and switch to version-date

**Review by dan-shaw — APPROVED** [review]

**Comment by dsa-t** [comment]
This update breaks our application (KiCad), because values in quaternions are stored differently compared to 0.9.9.8.

Order in 0.9.9.8:
https://github.com/g-truc/glm/blob/0.9.9.8/glm/detail/type_quat.hpp#L48C31-L48C31

Order in 2023-06-08:
https://github.com/g-truc/glm/blob/5c46b9c07008ae65cb81ab79cd677ecc1934b903/glm/detail/type_quat.hpp#L48C31-L48C31

Looks like glm should be updated again, with `GLM_FORCE_QUAT_DATA_XYZW` set to restore the order.

**Comment by xiaozhuai** [comment]
@dsa-t 
Thanks for reporting this, I look into it, but there is nothing we should do with this port.
You can define `GLM_FORCE_QUAT_DATA_WXYZ` in your user project.

**Comment by xiaozhuai** [comment]
> Another thing is, `GLM_FORCE_QUAT_DATA_XYZW` likely won't work properly before https://github.com/g-truc/glm/commit/c6606998a529e4e90afc5d06d435a30f5d59445b

Yes, this port currently use https://github.com/g-truc/glm/commit/5c46b9c07008ae65cb81ab79cd677ecc1934b903, which is more later than https://github.com/g-truc/glm/commit/c6606998a529e4e90afc5d06d435a30f5d59445b

**Comment by dsa-t** [comment]
Changes from https://github.com/g-truc/glm/commit/c6606998a529e4e90afc5d06d435a30f5d59445b aren't in https://github.com/g-truc/glm/commit/5c46b9c07008ae65cb81ab79cd677ecc1934b903.

See quat_cast, for example:
https://github.com/g-truc/glm/blob/5c46b9c07008ae65cb81ab79cd677ecc1934b903/glm/gtc/quaternion.inl#L81C31-L81C40

**Comment by xiaozhuai** [comment]
@dsa-t 
Confirmed, I've submit a pr #34523 to fix it. Thanks for reporting.

**Pull request merged**
