### PR TITLE
Deprovision libdbus-1-dev

### PR DESCRIPTION
**Pull request by dg0yt**

### CODE REVIEW

**Comment by talregev** [comment]
@dg0yt Can you explain what you doing / What happen?

**Comment by dg0yt** [comment]
Housekeeping.

**Comment by dg0yt** [comment]
Seems to have worked:
https://dev.azure.com/vcpkg/public/_build/results?buildId=101407&view=logs&j=f79cfdd7-47a8-597f-8f57-dc3e21a8f2ad&t=190fa159-d1a9-5464-6e7a-6824cb60a804

**Review by LilyWangLL — APPROVED** [review]

**Review by BillyONeal — APPROVED** [review]

**Comment by BillyONeal** [comment]
Done, thank you!

**Pull request closed without merging**
