### PR TITLE
[ngspice] build codemodel extension libraries

### PR DESCRIPTION
**Pull request by marekr**
Something I left out previously in this port.

ngspice has "codemodels" which are DLLs with a custom extension of *.cm adding more simulation capability. This update adds them to the port output.

Note, I'm not sure if this is correct but ngspice on all platforms including the official windows binaries wants the code models to reside in /lib/ngspice. I am not sure if this is correct for vcpkg.

### CODE REVIEW

**Review by JackBoosY — CHANGES_REQUESTED** [review]
Are these extensions required? So we can change it to a feature.

**Comment by marekr** [comment]
> Are these extensions required? So we can change it to a feature.

The library itself can run without them. But the use case of ngspice may encounter the need for these codemodel extensions by default since these extensions have been around for SPICE since 1991.

**Comment by JackBoosY** [comment]
@marekr So I suggest to add it as a feature, and set to the default feature.

**Comment by marekr** [comment]
@JackBoosY done

**Review by JackBoosY — APPROVED** [review]

**Comment by ras0219-msft** [comment]
LGTM, thanks for the fix!

**Pull request merged**
