### PR TITLE
[sqlcipher] update to 4.4.3 (#17500)

### LINKED ISSUE #17500: [sqlcipher] update to 4.4.3
Library name: sqlcipher

New version number: 4.4.3

Other information that may be useful (release notes, etc...)
https://www.zetetic.net/blog/2021/03/02/sqlcipher-443-release/
https://github.com/sqlcipher/sqlcipher/releases/tag/v4.4.3

### PR DESCRIPTION
**Pull request by shiena**
Fix #17500 

Update sqlcipher to the latest version 4.4.3

Note: no feature need to test

### CODE REVIEW

**Comment by JonLiu1993** [comment]
@shiena ,Thanks for your PR,I noticed that the port sqlcipher has three featyres of geopoly, json1, and tool. Have you tested them?

**Comment by JonLiu1993** [comment]
@shiena ,Thanks your pr,I noticed that the port sqlcipher has three features of geopoly, json1, and tool. Have you tested them?

**Review by JonLiu1993 — APPROVED** [review]

**Comment by shiena** [comment]
@JonLiu1993 Okay. I also tested geopoly, json1, and tool.

**Comment by JonLiu1993** [comment]
> @JonLiu1993 Okay. I also tested geopoly, json1, and tool.

Thanks for your contribution 👍

**Comment by BillyONeal** [comment]
Thanks again for your contribution!

**Pull request merged**
