### PR TITLE
[freeglut] Update to 3.2.2, fix X11 dependencies

### PR DESCRIPTION
**Pull request by dg0yt**
- #### What does your PR fix?
  Updates freeglut to 3.2.2.
  Drops the gcc-10 patch: Upstream marked those declaration now as `extern`.
  Fixes glut lib `FREEGLUT_LIBRARIES` on Linux where CMake 3.22 would lack the library path for glut. In turn, this fixes a link error when building `opencolorio[tools]` on Ubuntu 18.04.
  Fixes the lookup and export of dependencies related to X11. In turn, this fixes a build error for `libwebp[core,vwebp]` on Ubuntu 18.04:
  ~~~
  FAILED: vwebp 
  : && /usr/bin/cc -fPIC -pthread -mno-sse4.1 -mno-sse2 -g -L/home/dg0yt/Projekte/vcpkg/vcpkg/installed/x64-linux/debug/lib/pkgconfig/../../lib -lglut -lX11 -lXxf86vm -lXrandr -lGL -lm CMakeFiles/vwebp.dir/examples/vwebp.c.o -o vwebp  /usr/lib/x86_64-linux-gnu/libOpenGL.so  /usr/lib/x86_64-linux-gnu/libGLX.so  /usr/lib/x86_64-linux-gnu/libGLU.so  libexampleutild.a  libimageioutild.a  libwebpd.a  libwebpdemuxd.a  /usr/lib/x86_64-linux-gnu/libSM.so  /usr/lib/x86_64-linux-gnu/libICE.so  /usr/lib/x86_64-linux-gnu/libX11.so  /usr/lib/x86_64-linux-gnu/libXext.so  /usr/lib/x86_64-linux-gnu/libXxf86vm.so  /usr/lib/x86_64-linux-gnu/libXrandr.so  -lglut  -lX11  -lXxf86vm  -lXrandr  -lGL  /usr/lib/x86_64-linux-gnu/libXrandr.so  libwebpd.a  -lpthread  -lm && :
  /home/dg0yt/Projekte/vcpkg/vcpkg/installed/x64-linux/debug/lib/pkgconfig/../../lib/libglut.a(fg_xinput_x11.c.o): In function `fgRegisterDevices':
  /home/dg0yt/Projekte/vcpkg/vcpkg/buildtrees/freeglut/src/aced4bbcd3-cc93bf4714.clean/src/x11/fg_xinput_x11.c:58: undefined reference to `XISelectEvents'
  collect2: error: ld returned 1 exit status
  ~~~

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  unchanged, no (fail on arm64-windows, uwp, osx)

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  yes

### CODE REVIEW

**Comment by dg0yt** [comment]
qtinterfaceframework:x64-windows: Baseline regression

**Comment by dg0yt** [comment]
CI bug: #23837

**Comment by dg0yt** [comment]
All checks green, no longer depending on other PR to fix baseline regression.

**Review by LilyWangLL — APPROVED** [review]

**Comment by dg0yt** [comment]
One more change. Hard to believe how much breakage exists when you try to link apps, not libraries.

**Comment by strega-nil-ms** [comment]
Thanks!

**Pull request merged**
