### PR TITLE
[infoware] update to latest commit

### PR DESCRIPTION
**Pull request by Ryan-rsm-McKenzie**
**Describe the pull request**

- #### What does your PR fix?  
  Updates [infoware ](https://github.com/ThePhD/infoware) to the latest commit.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  N/A

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

### CODE REVIEW

**Review by JonLiu1993 — APPROVED** [review]

**Comment by JonLiu1993** [comment]
@Ryan-rsm-McKenzie, have you tested these features?

**Comment by Ryan-rsm-McKenzie** [comment]
Yes

**Comment by Ryan-rsm-McKenzie** [comment]
Actually I can only confirm that `d3d` works as intended. It would appear that `opencl` (on anything other than osx) and `opengl` (on linux) don't work because:
* They don't install the frameworks they depend on (a problem with vcpkg.json).
* The upstream CMakeLists.txt doesn't `find_package` the required libraries.

I don't have anything to test `x11` with.

However, this is a problem that's existed since the port was created.

**Comment by Ryan-rsm-McKenzie** [comment]
I have a [pr open](https://github.com/ThePhD/infoware/pull/51) to fix this.

**Comment by JonLiu1993** [comment]
> Actually I can only confirm that `d3d` works as intended. It would appear that `opencl` (on anything other than osx) and `opengl` (on linux) don't work because:
> 
> * They don't install the frameworks they depend on (a problem with vcpkg.json).
> * The upstream CMakeLists.txt doesn't `find_package` the required libraries.
> 
> I don't have anything to test `x11` with.
> 
> However, this is a problem that's existed since the port was created.

Thanks for your clarification

**Comment by ras0219-msft** [comment]
Thanks for the PR!

I think pulling the latest commit for now makes sense since this is still a relatively small library, however in general if upstream provides released versions we prefer to stay on those. If possible, please encourage upstream to release a new version ASAP so we can get back to numbered versions :)

**Pull request merged**
