### PR TITLE
[sentry-native] Update to 0.4.3

### PR DESCRIPTION
**Pull request by AenBleidd**
Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

### CODE REVIEW

**Comment by AenBleidd** [comment]
Is there any way to get cmake logs from osx ci machine?

**Comment by PhoebeHui** [comment]
@AenBleidd, see full log here:
[failure logs for x64-osx (4).zip](https://github.com/microsoft/vcpkg/files/5364404/failure.logs.for.x64-osx.4.zip)

**Comment by AenBleidd** [comment]
@PhoebeHui, thank you!

**Review by PhoebeHui — APPROVED** [review]

**Pull request merged**
