### PR TITLE
[minizip] support iOS/Android triplets

### PR DESCRIPTION
**Pull request by luncliff**
### What does your PR fix?

Support iOS triplet builds for port `minizip`.

Simply bypass `add_executable` which requires `BUNDLE DESTINATION`.
Moved the configure option `DISABLE_INSTALL_TOOLS` from `OPTIONS_DEBUG` to `OPTIONS`, and provide `VCPKG_TARGET_IS_IOS` for it.

### Which triplets are supported/not supported?

Support 4 `ios` triplets, and 4 `android` triplets

* `arm64-ios`
* `arm-ios`
* `x64-ios`
* `x86-ios`
* `arm64-android`
* `arm-android`
* `x64-android`
* `x86-android`

### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

### CODE REVIEW

**Comment by luncliff** [comment]
The port fails on `android` triplets.  
I'd like to fix those cases together and rename this PR.

**Comment by luncliff** [comment]
@PhoebeHui, would you run the build again? 2 failures are not from this port. I think re-run will resolve that

**Comment by PhoebeHui** [comment]
@luncliff, I have rerun the PR, let's wait for the test results.

**Comment by PhoebeHui** [comment]
I tired to run qt5-3d locally, however, it blocked by issue https://github.com/microsoft/vcpkg/issues/12591, the dependency port failed.

**Comment by JackBoosY** [comment]
```
In file included from /mnt/vcpkg-ci/installed/x64-linux/include/QtGui/QVulkanInstance:1:0,
                 from /mnt/vcpkg-ci/buildtrees/qt5-3d/src/5.15.2-e9ea6a2c75.clean/src/render/surfaces/vulkaninstance.cpp:41:
/mnt/vcpkg-ci/installed/x64-linux/include/QtGui/qvulkaninstance.h:55:10: fatal error: vulkan/vulkan.h: No such file or directory
 #include <vulkan/vulkan.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
```
`qt5-base:QtGui/QVulkanInstance`
vulkan wasn't added in qt5-base's dependency list, but I think it should be added.
@Neumann-A What do you think about this?

**Comment by PhoebeHui** [comment]
Could not repro x64-linux failures in baseline test via PR https://github.com/microsoft/vcpkg/pull/16353, I have rerun the CI testing.

**Review by PhoebeHui — APPROVED** [review]

**Comment by Neumann-A** [comment]
@JackBoosY make it a feature. Seems like there is an option `-vulkan` and `-no-vulkan`

**Comment by strega-nil** [comment]
Thanks @luncliff!

**Pull request merged**
