### PR TITLE
Add port: PLplot

### PR DESCRIPTION
**Pull request by MathiasMagnus**
[PLplot](http://plplot.sourceforge.net/) is a professional plotting library meant to create production/publication ready data plots. It is not a young project (stood the test of time), undoubtedly more modern libraries exist. Nonetheless, it has a wide user base and many language bindings.

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for the PR! I found some interesting interactions between the port and our master `vcpkg_configure_cmake()`, which resulted in some changes while working it out.

**Comment by Voskrese** [comment]
@MathiasMagnus 
E:\tools\vcpkg>vcpkg install --triplet x64-windows-static --recurse plplot
The following packages will be built and installed:
    plplot[core]:x64-windows-static
Starting package 1/1: plplot:x64-windows-static
Building package plplot[core]:x64-windows-static...
-- CURRENT_INSTALLED_DIR=E:/tools/vcpkg/installed/x64-windows-static
-- DOWNLOADS=E:/tools/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=E:/tools/vcpkg/packages/plplot_x64-windows-static
-- CURRENT_BUILDTREES_DIR=E:/tools/vcpkg/buildtrees/plplot
-- CURRENT_PORT_DIR=E:/tools/vcpkg/ports/plplot/.
-- Downloading https://sourceforge.net/projects/plplot/files/plplot/5.13.0%20Source/plplot-5.13.0.tar.gz/download...
-- Downloading https://sourceforge.net/projects/plplot/files/plplot/5.13.0%20Source/plplot-5.13.0.tar.gz/download... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Extracting source E:/tools/vcpkg/downloads/plplot-5.13.0.tar.gz
-- Extracting done
-- Applying patch E:/tools/vcpkg/ports/plplot/install-interface-include-directories.patch
-- Applying patch E:/tools/vcpkg/ports/plplot/install-interface-include-directories.patch done
-- Configuring x64-windows-static-rel
-- Configuring x64-windows-static-rel done
-- Configuring x64-windows-static-dbg
-- Configuring x64-windows-static-dbg done
-- Build x64-windows-static-rel
-- Build x64-windows-static-rel done
-- Build x64-windows-static-dbg
-- Build x64-windows-static-dbg done
-- Installing: E:/tools/vcpkg/packages/plplot_x64-windows-static/share/plplot/copyright
-- Performing post-build validation
```
There should be no bin\ directory in a static build, but E:\tools\vcpkg\packages\plplot_x64-windows-static\bin is present.
There should be no debug\bin\ directory in a static build, but E:\tools\vcpkg\packages\plplot_x64-windows-static\debug\bin is present.
If the creation of bin\ and/or debug\bin\ cannot be disabled, use this in the portfile to remove them

    if(VCPKG_LIBRARY_LINKAGE STREQUAL static)
        file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/bin ${CURRENT_PACKAGES_DIR}/debug/bin)
    endif()

There should be no empty directories in E:/tools/vcpkg/packages/plplot_x64-windows-static
The following empty directories were found:

    E:/tools/vcpkg/packages/plplot_x64-windows-static/bin
    E:/tools/vcpkg/packages/plplot_x64-windows-static/debug/bin

If a directory should be populated but is not, this might indicate an error in the portfile.
If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:

    file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/a/dir ${CURRENT_PACKAGES_DIR}/some/other/dir)


Found 2 error(s). Please correct the portfile:
```
    E:\tools\vcpkg\ports\plplot\portfile.cmake
-- Performing post-build validation done
Error: Building package plplot:x64-windows-static failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:

**Comment by MathiasMagnus** [comment]
I think this might be because the tool `pltek.exe` is built thus creating the `bin` dir (and didn't look yet what builds it) and we only removed the exe and not the dir. In dynamic builds the dlls populate the `bin` anyway. Will fix on monday.

Because we have a group at our institute that wanted to rely on this package ASAP, I wanted to make it work and reduce building unwanted side-effects later to improve installation times. There are few other packages and improvements in the pipeline as well.

_(clFFT can use FFTW3 on CPU devices but stock scripts do not expose this as an option; if it finds it, it silently links to. The current behavior of clFFT depends on installation order when FFTW3 is also installed/queued for install. clRNG is also in the pipes...)_

**Comment by Voskrese** [comment]
@MathiasMagnus 
как я понял намного все проще, исполняемый файл удаляется, а пустая папка остается

> as I understood much more easily, the executable is deleted, and the empty folder remains

```
+# Remove unnecessary tool
+file(REMOVE
+    ${CURRENT_PACKAGES_DIR}/debug/bin/pltek.exe
+    ${CURRENT_PACKAGES_DIR}/bin/pltek.exe
+)
```

**Pull request merged**
