### PR TITLE
windows.cmake: Remove compiler/linker flags that conflict with /clr.

### PR DESCRIPTION
**Pull request by mikehallmusco**
Remove compiler/linker flags that conflict with /clr.

#40075

### CODE REVIEW

**Comment by Neumann-A** [comment]
invalid. clr is a complete different toolchain

**Comment by mikehallmusco** [comment]
> invalid. clr is a complete different toolchain

Are you referring to the UWP toolchain? It uses the same conflicting compiler/linker options. Or is there another toolchain? 
Why would the UWP or Windows toolchain explicitly disallow CLR? These frameworks can happily build within the same solution.

**Comment by Neumann-A** [comment]
> These frameworks can happily build within the same solution.

If that would be the general case you wouldn't need to remove the flags here. 
You can disable the flags by providing the deactivation flags after vcpkgs own flags. There is no need to generally disable them in the toolchain.

**Comment by mikehallmusco** [comment]
> > These frameworks can happily build within the same solution.
> 
> If that would be the general case you wouldn't need to remove the flags here. You can disable the flags by providing the deactivation flags after vcpkgs own flags. There is no need to generally disable them in the toolchain.

I understand. The intent is that the toolchain provides the defaults, which are overridden by the project/solution files.

I don't see a way to disable the flag by providing "deactivation flags" but I'm assuming you mean my projects could provide the /EHa flag which will override the /EHsa flag. This would rely on the fact that CL.exe will take the [right most option](https://learn.microsoft.com/en-us/cpp/build/reference/order-of-cl-options?view=msvc-170) in the case of conflicting options. 

However, since the vcpkg_msbuild_install function uses a target file to pass these options to msbuild, we don't have direct control over the order of the parameters. It doesn't matter if I move the importing of the target file to the beginning of the OPTIONS, or if I change it to ForceImportBeforeCppTargets (as opposed to ForceImportAfterCppTargets), the options from the windows.cmake are always on the end of the CL.exe command. As follows:

`C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.39.33519\bin\HostX64\x86\CL.exe /c /I.. /I.. /I"<vcpkg_installed_path>/vcpkg/pkgs/<portname>/include" /I"<vcpkg_installed_path>/x86-windows/include" /Zi /nologo /W3 /WX- /diagnostics:column /sdl /MP /O2 /Oi /Oy- /D _BASE_EXPORT /D _AFXDLL /D _WINDLL /D _UNICODE /D UNICODE /D _AFXDLL /Gm- /EHa /MD /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++17 /Yc"stdafx.h" /Fp"obj\base\x86\Release\base.pch" /Fo"obj\base\x86\Release\\" /Fd"obj\base\x86\Release\base_vc143.pdb" /external:W3 /Gd /TP /wd4251 /analyze- /FC /errorReport:queue /Zm400    -nologo -DWIN32 -D_WINDOWS -utf-8 -GR -EHsc -MP  -MD -O2 -Oi -Gy -DNDEBUG -Z7    /WX- stdafx.cpp`

I don't see a way to ensure the options from the project files are after the options declared in the windows.cmake.

**Comment by mikehallmusco** [comment]
The simplest solution is to just remove the flags, none of them need to be in there and some of them are the defaults anyway. Unless I'm missing something I would advocate for removal of the following from the `windows.cmake` toolchain script:
`/utf-8 /EHsc /Z7 /Ob0 /Od /RTC1 /O2 /Oi /Gy /OPT:REF /OPT:ICF`

**Comment by Neumann-A** [comment]
> will take the [right most option](https://learn.microsoft.com/en-us/cpp/build/reference/order-of-cl-options?view=msvc-170) in the case of conflicting options.

So you have the solution you just don't know how to apply it. What about `VCPKG_C(XX)?_FLAGS` ?
Also vcpkg_msbuild_install has an option to remove all toolchain flags. 

> Unless I'm missing something

.... at least /Z7 is required.

**Review by BillyONeal — CHANGES_REQUESTED** [review]
It does not make sense to try to build things not expecting CLR bits with `/clr`. The switches herein are the way they are because they're what Visual Studio does when you make a vcxproj.

**Comment by BillyONeal** [comment]
@ras0219-msft @vicroms @JavierMatosD @data-queue and I discussed this today.

I note that this would turn off exception handling by default which seems very broken. The flags were chosen this way because that's what `.vcxproj` does and I would want to see strong evidence that nobody would break.

@ras0219-msft notes that he explicitly agrees with @Neumann-A that this kind of override should not override the normal Windows native/desktop behavior. He doesn't see any PR like this working. Mixing native/desktop and /clr seems an explicit non-goal and should be treated as its own platform.

If you want to do this, you can:

1. Copy/paste `windows.cmake` from here
2. Make the edits you want
3. Write a triplet that sets `VCPKG_CHAINLOAD_TOOLCHAIN_FILE` to the path of that copied and edited `windows.cmake`

If you want some ports that are built for `/clr` and some not, you can do:

```cmake
if ("${PORT}" STREQUAL "example")
    # I want the port named example to be built with /clr
    set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "${CMAKE_CURRENT_LIST_DIR}/my-clr-toolchain-file-made-with-the-instructions-above.cmake")
endif()
```

Thanks for your contribution to vcpkg!

**Pull request closed without merging**
