### PR TITLE
[libvorbis] patch find_library instead of manually supplying the libr…

### LINKED ISSUE #6558: [libvorbis] Patch find_library call in libvorbis
https://github.com/microsoft/vcpkg/blob/ef2d3ff6d0c3cfc5754a640d0929d25aa13b4e14/ports/libvorbis/portfile.cmake#L13-L20

Instead of fixing the behavior externally to find ogg it is better to patch the behavior within libvorbis. E.g. add all the ogg names to the find_library call within libvorbis

same is probably true for `ports/libtheora/FindOGG.cmake`

### PR DESCRIPTION
**Pull request by Neumann-A**
…ary to cmake

closes #6558

### CODE REVIEW

**Comment by NancyLi1013** [comment]
Hi @Neumann-A, thanks for your PR. Here are some regressions from the current CI system:

|x64-windows|test|notes
|-----------|----|-----
|sndfile    |Fail|**Regression**

|arm64-windows|test|notes
|-------------|----|-----
|sndfile      |Fail|**Regression**

|x86-windows|test|notes
|-----------|----|-----
|sndfile    |Fail|**Regression**

|x64-uwp|test|notes
|-------|----|-----
|sndfile|Fail|**Regression**

|arm-uwp|test|notes
|-------|----|-----
|sndfile|Fail|**Regression**

[failureLogs.zip](https://github.com/microsoft/vcpkg/files/3209909/failureLogs.zip)

**Comment by Neumann-A** [comment]
@crazy2013 Why the thumbs down?

**Comment by Neumann-A** [comment]
@NancyLi1013 Again something strange with CI. These are log files from #5543 or #6555. I couldn't reproduce the windows regression locally in a clean clone of this PR.

**Comment by vicroms** [comment]
LGTM.

As a side effect of this PR `sfml` and `tgui` now build on Linux 🎉

**Pull request merged**
