### PR TITLE
[expat] Ensure dllimport

### PR DESCRIPTION
**Pull request by dg0yt**
For https://github.com/microsoft/vcpkg/issues/35878#issuecomment-2034823675.
Alternative to #37956.

### CODE REVIEW

**Comment by dg0yt** [comment]
CC @AlessandroScrem @frabera

**Review by MonicaLiu0311 — APPROVED** [review]

**Comment by dg0yt** [comment]
> I actually encounter the same error as before [#37976 (comment)](https://github.com/microsoft/vcpkg/issues/37976#issue-2226089160), the patch proposed by @AlessandroScrem #37956 worked.

Double check that you test the expat from this PR, and that your project doesn't set definitions inappropriately. With this PR, the installed `include/expat_external.h` for dynamic linkage has (check it!):

~~~C
#if ! defined(XML_STATIC) && ! defined(XMLIMPORT)
#  ifndef XML_BUILDING_EXPAT
/* using Expat from an application */

#    if defined(_WIN32) && ! defined(__BEOS__) && ! defined(__CYGWIN__)
#      define XMLIMPORT __declspec(dllimport)
#    endif

#  endif
#endif /* not defined XML_STATIC */
~~~

which translates to
~~~C
#if ! 0 && ! 0
#  if 1
/* using Expat from an application */

#    if 1 && ! 0 && ! 0
#      define XMLIMPORT __declspec(dllimport)
#    endif

#  endif
#endif /* not defined XML_STATIC */
~~~

which translates to
~~~C
#      define XMLIMPORT __declspec(dllimport)
~~~

which has the effect of
~~~diff
-#define XMLPARSEAPI(type) XMLIMPORT type XMLCALL
+#define XMLPARSEAPI(type) __declspec(dllimport) type XMLCALL
~~~

**Comment by BillyONeal** [comment]
Thanks for the fix; `/Za` is just pain and it hurts every time people ask for the extra bugs mode but at least they can get something that works.

**Comment by hartwork** [comment]
@dg0yt is there interest in turning this into a bug report with explanation and a pull request upstream? I'm having trouble understanding if/how/when `_MSC_EXTENSIONS` stopped being defined, which compilers are affected etc.

**Comment by dg0yt** [comment]
> I'm having trouble understanding if/how/when `_MSC_EXTENSIONS` stopped being defined, which compilers are affected etc.

I can't speak about `_MSC_EXTENSIONS`. I do not have a significant MSVC background, apart from fixing vcpkg ports using Microsoft's CI.

**Comment by hartwork** [comment]
@dg0yt do you remember the origin of the idea to auto-replace `defined(_MSC_EXTENSIONS)` by `defined(_WIN32)`? Any idea who to talk to in here about troubles with `_MSC_EXTENSIONS`? Sorry if I missed the answer somewhere..

**Comment by dg0yt** [comment]
> @dg0yt do you remember the origin of the idea to auto-replace `defined(_MSC_EXTENSIONS)` by `defined(_WIN32)`? Any idea who to talk to in here about troubles with `_MSC_EXTENSIONS`? Sorry if I missed the answer somewhere..

- FTR the auto-replacement is a post-install step.
- The total effect is to ensure `#define XMLIMPORT __declspec(dllimport)` for all *use* of expat in dynamic windows triplets.
  This is a common pattern for Windows, and also supported by MinGW.
  And the lack of dllimport is a common issue with direct use of headers from vcpkg ports.
- I can see why one might want to avoid `__declspec` when `_MSC_EXTENSIONS` is off. But mabye this non-default configuration would be too troublesome as soon you need some C++ lib?
- The people reported problems/`dllimport` hacks in https://github.com/microsoft/vcpkg/issues/35878#issuecomment-2034823675 didn't provide much detals. IIRC this PR was made to ensure the existing definition of `XMLIMPORT` is simply used instead of replacing its use in `XMLPARSEAPI`.

**Comment by hartwork** [comment]
@dg0yt thank you for elaborating!

**Comment by hartwork** [comment]
@dg0yt I have a draft pull request upstream at https://github.com/libexpat/libexpat/pull/1068 now that uses `_MSC_VER` rather than `_WIN32`. I'm happy about insights, feedback, testing from anyone :pray:

**Pull request merged**
