### PR TITLE
[libiconv] Deploy on BSDs

### LINKED ISSUE #39748: Enhancement: Invoke meson with additional include and library paths for BSD systems
Locations for putting user libraries and include files used by BSD systems:
  - FreeBSD: `/usr/local`
  - OpenBSD: `/usr/local`
  - NetBSD: `/usr/pkg`
  - DragonFlyBSD: `/usr/local`

Meson doesn't find libraries and includes inside these directories (e.g. for OpenBSD, user libraries and includes are inside `/usr/local/lib` and `/usr/local/include`), and this causes you cannot get an out-of-box installation for many package that uses meson to build, for example, glib.
These are logs of `vcpkg install glib`, on OpenBSD:
*Console output:*
```
-- Configuring x64-openbsd-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: /usr/local/bin/python3 -I /home/niko/vcpkg/downloads/tools/meson-1.3.2-d646d3/meson.py -Dselinux=disabled -Dlibmount=disabled -Dgtk_doc=false -Dinstalled_tests=false -Dlibelf=disabled -Dman=false -Dtests=false -Dxattr=false --backend ninja --wrap-mode nodownload -Dbuildtype=plain -Doptimization=plain --libdir lib --native /home/niko/vcpkg/buildtrees/glib/meson-x64-openbsd-dbg.log -Ddebug=true --prefix /home/niko/vcpkg/packages/glib_x64-openbsd/debug --includedir ../include -Dcmake_prefix_path=['/home/niko/vcpkg/installed/x64-openbsd/debug','/home/niko/vcpkg/installed/x64-openbsd'] /home/niko/vcpkg/buildtrees/glib/src/glib-2-322e03f702.clean
    Working Directory: /home/niko/vcpkg/buildtrees/glib/x64-openbsd-dbg
    Error code: 1
    See logs for more information:
      /home/niko/vcpkg/buildtrees/glib/config-x64-openbsd-dbg-meson-log.txt.log
      /home/niko/vcpkg/buildtrees/glib/config-x64-openbsd-dbg-out.log

Call Stack (most recent call first):
  installed/x64-openbsd/share/vcpkg-tool-meson/vcpkg_configure_meson.cmake:436 (vcpkg_execute_required_process)
  ports/glib/portfile.cmake:42 (vcpkg_configure_meson)
  scripts/ports.cmake:192 (include)


error: building glib:x64-openbsd failed with: BUILD_FAILED
Elapsed time to handle glib:x64-openbsd: 1.1 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+glib
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[glib]+Build+error+on+x64-openbsd&body=Copy+issue+body+from+%2Fhome%2Fniko%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md
```
*Part of `config-x64-openbsd-dbg-out.log`*:
```
Checking if "stack grows check" runs: NO (1)
Running compile:
Working directory:  /home/niko/vcpkg/buildtrees/glib/x64-openbsd-dbg/meson-private/tmp8pv3xc97
Code:
 #include <iconv.h>

int main() {
    iconv_open("","");
}
-----------
Command line: `/usr/bin/clang++ -fPIC -g -L/home/niko/vcpkg/installed/x64-openbsd/debug/lib -I/home/niko/vcpkg/installed/x64-openbsd/include /home/niko/vcpkg/buildtrees/glib/x64-openbsd-dbg/meson-private/tmp8pv3xc97/testfile.cpp -o /home/niko/vcpkg/buildtrees/glib/x64-openbsd-dbg/meson-private/tmp8pv3xc97/output.exe -fPIC -g -D_FILE_OFFSET_BITS=64 -O0 -fpermissive -Werror=implicit-function-declaration -fuse-ld=/usr/bin/ld.lld` -> 1
stderr:
/home/niko/vcpkg/buildtrees/glib/x64-openbsd-dbg/meson-private/tmp8pv3xc97/testfile.cpp:1:10: fatal error: 'iconv.h' file not found
#include <iconv.h>
         ^~~~~~~~~
1 error generated.
-----------
Running compile:
Working directory:  /home/niko/vcpkg/buildtrees/glib/x64-openbsd-dbg/meson-private/tmpxju7wrxo
Code:
 
        #ifdef __has_include
         #if !__has_include("iconv.h")
          #error "Header 'iconv.h' could not be found"
         #endif
        #else
         #include <iconv.h>
        #endif
-----------
Command line: `/usr/bin/clang++ -fPIC -g -I/home/niko/vcpkg/installed/x64-openbsd/include /home/niko/vcpkg/buildtrees/glib/x64-openbsd-dbg/meson-private/tmpxju7wrxo/testfile.cpp -E -P -fPIC -g -D_FILE_OFFSET_BITS=64 -P -O0 -fpermissive -Werror=implicit-function-declaration` -> 1
stderr:
/home/niko/vcpkg/buildtrees/glib/x64-openbsd-dbg/meson-private/tmpxju7wrxo/testfile.cpp:4:12: error: "Header 'iconv.h' could not be found"
          #error "Header 'iconv.h' could not be found"
           ^
1 error generated.
-----------
Running compile:
Working directory:  /home/niko/vcpkg/buildtrees/glib/x64-openbsd-dbg/meson-private/tmpm8y7hhad
Code:
 int main(void) { return 0; }

-----------
Command line: `/usr/bin/clang++ -fPIC -g -L/home/niko/vcpkg/installed/x64-openbsd/debug/lib -I/home/niko/vcpkg/installed/x64-openbsd/include /home/niko/vcpkg/buildtrees/glib/x64-openbsd-dbg/meson-private/tmpm8y7hhad/testfile.cpp -o /home/niko/vcpkg/buildtrees/glib/x64-openbsd-dbg/meson-private/tmpm8y7hhad/output.exe -fPIC -g -D_FILE_OFFSET_BITS=64 -O0 -fpermissive -Werror=implicit-function-declaration -Wl,--start-group -liconv -Wl,--end-group -fuse-ld=/usr/bin/ld.lld -Wl,--allow-shlib-undefined -fuse-ld=/usr/bin/ld.lld` -> 1
stderr:
ld.lld: error: unable to find library -liconv
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

...

Run-time dependency iconv found: NO (tried builtin and system)

../src/glib-2-322e03f702.clean/meson.build:2082:13: ERROR: Dependency "iconv" not found, tried builtin and system
```
There's an issues mention mentioned this problem: https://github.com/mesonbuild/meson/issues/4468, but it seems that they are still debating. I believe it might be better if we pass these BSD locations to meson (set additional include path and library path), in order to provide an out-of-box installation of the packages use meson, as a temporary solution?

### PR DESCRIPTION
**Pull request by SchaichAlonso**
Fixes #39748 

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [ ] ~SHA512s are updated for each updated download.~
- [ ] ~The "supports" clause reflects platforms that may be fixed by this new version.~
- [ ] ~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~
- [ ] ~Any patches that are no longer applied are deleted from the port's directory.~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by SchaichAlonso** [comment]
Reproducting Github Action using [ChristopherHX/github-act-runner](https://github.com/ChristopherHX/github-act-runner) on a vultr hosted OpenBSD-7.5: [link](https://github.com/SchaichAlonso/vcpkg-39748-iconv-fails-to-deploy-on-openbsd/actions/runs/9873044673)
Notoriously, the [artifact for ${VCPKG_ROOT}/installed/vcpkg/info](https://github.com/SchaichAlonso/vcpkg-39748-iconv-fails-to-deploy-on-openbsd/actions/runs/9873044673/artifacts/1686130865) indicates that the `libiconv` package did _not_ provision the `iconv.h` file consumed by the glib build process, causing the later to fail.

**Comment by SchaichAlonso** [comment]
Build run on the PR branch: [link](https://github.com/SchaichAlonso/vcpkg-39748-iconv-fails-to-deploy-on-openbsd/actions/runs/9873457000)

`iconv.h` and the other content of the libiconv package is deployed, enabling glib and other consumers to be built.

**Comment by WangWeiLin-MV** [comment]
> Build run on the PR branch: [link](https://github.com/SchaichAlonso/vcpkg-39748-iconv-fails-to-deploy-on-openbsd/actions/runs/9873457000)
> 
> `iconv.h` and the other content of the libiconv package is deployed, enabling glib and other consumers to be built.

Thanks for testing.

**Review by WangWeiLin-MV — APPROVED** [review]

**Comment by dg0yt** [comment]
> OpenBSD has BSD's implementation of iconv, but glib and friends - via gnu gettext - rely on GNU's implementation of iconv.

Where can this be verified w.r.t. BSD?
- [ ] glib relying on the *GNU* implementation of gettext/libintl
- [ ] GNU gettext relying on the *GNU* implementation of iconv

FTR we also to deal musl libc *Linux* systems which don't have gettext/libintl in the C lib.

I do know that gettext comes with detection logic built into m4 files for autotools, and I assume that's why we don't have pkg-config files.
CMake has Find modules, but they need wrappers in vcpkg.
Meson ... still not encouraging.

**Comment by SchaichAlonso** [comment]
> > OpenBSD has BSD's implementation of iconv, but glib and friends - via gnu gettext - rely on GNU's implementation of iconv.
> 
> Where can this be verified w.r.t. BSD?
> 
>     * [ ]  glib relying on the _GNU_ implementation of gettext/libintl
> 
>     * [ ]  GNU gettext relying on the _GNU_ implementation of iconv
> 
> 
> FTR vcpkg should also correctly handle musl libc _Linux_ systems which don't have gettext/libintl in the C lib.
> 
> I do know that gettext comes with detection logic built into m4 files for autotools, and I assume that's why we don't have pkg-config files. CMake has Find modules, but they need wrappers in vcpkg. Meson ... still not encouraging.

I was wrongly assuming the glib port tracks its dependency on iconv by depending on gettext which implies iconv, because I didn't double-check it yesterday. The glib port directly tracks it's dependency on iconv, hence it's glib → GNU iconv (rather then glib → gettext → GNU iconv).

There's a lengthy discussion in a FreeBSD mailing list about glibmm consumers throwing exceptions when linked against FreeBSD's libiconv reducing the problem to [glib being reliant on the availablity of the nonstandard WCHAR_T extention](https://lists.freebsd.org/pipermail/freebsd-ports/2014-February/089779.html) available in GNU iconv but not BSD iconv.

FreeBSD's ports have resolved this by hard-depending the glib20 port on gnu's libiconv by adding a corresponding dependency line into the glib20 port Makefile ([iconv:wchar_t](https://github.com/freebsd/freebsd-ports/blob/ec5034b75d87bdfd37131066d86ad4c22d9e8c55/devel/glib20/Makefile#L27) triggers [this branch](https://github.com/freebsd/freebsd-ports/blob/ec5034b75d87bdfd37131066d86ad4c22d9e8c55/Mk/Uses/iconv.mk#L14) to [depend on converters/libiconv](https://github.com/freebsd/freebsd-ports/blob/ec5034b75d87bdfd37131066d86ad4c22d9e8c55/Mk/Uses/iconv.mk#L29) which is [GNU's one](https://github.com/freebsd/freebsd-ports/blob/ec5034b75d87bdfd37131066d86ad4c22d9e8c55/converters/libiconv/Makefile#L9)), just as vcpkg's glib port has an entry [in glib's vcpkg.json](https://github.com/microsoft/vcpkg/blob/5312e9f976e89b256954f571433e34f783dd2d12/ports/glib/vcpkg.json#L13) leading to vcpkg's libiconv port [which also is GNU's one](https://github.com/microsoft/vcpkg/blob/5312e9f976e89b256954f571433e34f783dd2d12/ports/libiconv/portfile.cmake#L9). However, the vcpkg libiconv port, at this time, omits the deployment of libiconv on FreeBSD systems, therefore the dependency declaration has no effect.

---

The vcpkg port currently fiters on the operating system rather then `find_library` / `try_compile` / `try_run`-ing something to detect the `iconv` function's availability on the build system. On setups where libiconv is an explicit package and not installed, or has the library but not the header files installed, this could lead to failures further down the dependency chain.

As I wrote in the issue, we _should_ be able to deploy and use our iconv even in environments where iconv is part of the libc, so _always_ deploying it "should" work there, too.

---

More important then implementational details of the various iconv implementations, though, I'd like vcpkg to provision a dependency when I add it to my `vcpkg.json` dependency list, or to emit a diagnostic indicating the deployment was skipped, rather then silently providing me with an Operating System provided dependency.

**Pull request merged**
