### PR TITLE
[pango] Update to 1.52.1

### PR DESCRIPTION
**Pull request by waywardmonkeys**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [x] The "supports" clause reflects platforms that may be fixed by this new version.
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by WangWeiLin-MV** [comment]
Please check the failure in `microsoft.vcpkg.pr`.

**Comment by waywardmonkeys** [comment]
@WangWeiLin-MV I must be missing something because I don't see how to get the error logs to view the actual error. :( I'm currently on macOS and won't have access to Windows hardware for another couple of days to run it myself and see.

**Comment by WangWeiLin-MV** [comment]
@waywardmonkeys  The PR action log could see in the [Details](https://github.com/microsoft/vcpkg/pull/37262/checks?check_run_id=22431382814), This result is [1 errors / 0 warnings](https://dev.azure.com/vcpkg/public/_build/results?buildId=100322&view=results), and the [error log](https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/100322/artifacts?artifactName=failure%20logs%20for%20x64-windows-static&api-version=7.1&%24format=zip) could be downloaded from its [Artifacts Page](https://dev.azure.com/vcpkg/public/_build/results?buildId=100322&view=artifacts&pathAsName=false&type=publishedArtifacts).

**Comment by WangWeiLin-MV** [comment]
@waywardmonkeys The PR action log is in the [Details](https://github.com/microsoft/vcpkg/pull/37262/checks?check_run_id=22431382814). This result is [1 errors / 0 warnings](https://dev.azure.com/vcpkg/public/_build/results?buildId=100322&view=results), and the [error log](https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/100322/artifacts?artifactName=failure%20logs%20for%20x64-windows-static&api-version=7.1&%24format=zip) could be downloaded from its [Artifacts Page](https://dev.azure.com/vcpkg/public/_build/results?buildId=100322&view=artifacts&pathAsName=false&type=publishedArtifacts).

**Pull request closed without merging**
