### PR TITLE
[Stormlib] UNICODE needs to be PUBLIC

### PR DESCRIPTION
**Pull request by Lectem**
Usually UNICODE can be set or not without issues. However in the case of stormlib, TCHAR is part of the API, which can lead to issues.

By default CMake uses MBCS instead of unicode:
- https://gitlab.kitware.com/cmake/cmake/-/blob/v3.27.7/Source/cmLocalVisualStudio7Generator.cxx#L805
- https://gitlab.kitware.com/cmake/cmake/-/blob/v3.27.7/Source/cmVisualStudio10TargetGenerator.cxx#L1516
- https://gitlab.kitware.com/cmake/cmake/-/blob/v3.27.7/Source/cmVisualStudioGeneratorOptions.cxx#L137

This means that a project using CMake defaults would see sizeof(TCHAR)==1 while stormlib would see sizeof(TCHAR)==2.

Make the define PUBLIC so that targets linking stormlib::stormlib will automatically define it too.

Ideally, we would remove the use of this define entirely (this is something that must be controlled by the user, for example using a toolchain file), but this would break current users. We also can not use a feature to togggle this behaviour due to https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md#features

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [x] The "supports" clause reflects platforms that may be fixed by this new version.
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by Lectem** [comment]
@microsoft-github-policy-service agree

**Comment by JonLiu1993** [comment]
https://github.com/microsoft/vcpkg/blob/a1212c93cabaa9c5c36c1ffdb4bddd59fdf31e43/ports/stormlib/vcpkg.json#L4

Please change `port-version` to 6 and run command `./vcpkg x-add-version stormlib` and commitr again

**Comment by JonLiu1993** [comment]
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

**Comment by Lectem** [comment]
#38834 removed the `CMakeLists.txt` entirely to replace it with the upstream version.
The upstream version does not seem to set the `UNICODE` macros anymore (which is thus a breaking change), so I will close this pull request.

However I still find it a bit concerning that such changes to ABI (as opposed to API) can happen so easily. But I think that we now have the correct behaviour (keep CMake/toolchain defaults). Perhaps ports with libraries that use `TCHAR` in their interface should have `UNICODE` be part of the ABI checks somehow ?

**Pull request closed without merging**
