### PR TITLE
[vcpkg] Move CI cleaning back out of the 'ci' command into a separate command to restore cross-compilation preinstalls.

### PR DESCRIPTION
**Pull request by BillyONeal**

### CODE REVIEW

**Comment by LilyWangL** [comment]
Please remove the following command in _scripts/ci.baseline.txt_. Thanks.
```
protobuf:x64-uwp=ignore
protobuf:arm64-windows=ignore
protobuf:arm-uwp=ignore
```

**Comment by NancyLi1013** [comment]
@BillyONeal 

Could you help also add this for `ignition-msgs5`? 
https://github.com/microsoft/vcpkg/pull/11538#issue-422255906

**Comment by BillyONeal** [comment]
@NancyLi1013 This PR appears unrelated to that one other than that this one should merge first because it restores a workaround in CI upon which the other one depends.

**Comment by NancyLi1013** [comment]
@BillyONeal  Thanks for your clarification. Seems the CI in that PR has passed now.

**Comment by JackBoosY** [comment]
Related: #11502.

**Comment by PhoebeHui** [comment]
@BillyONeal, does this changes test by CI system actually?

**Comment by BillyONeal** [comment]
@PhoebeHui This change just puts a workaround back in place that I accidentally removed in https://github.com/microsoft/vcpkg/commit/f2c46e717d61945fbd51dfd382f46416aa199566

I have been testing the change as part of the effort to refresh the workers, which does a complete rebuild. ( https://github.com/microsoft/vcpkg/pull/11365 ) (There are a few failures there, but none related to this)

**Review by strega-nil — APPROVED** [review]

**Pull request merged**
