### PR TITLE
[zlib/glib]Add debug postfix("d") on unix and fix build error with glib.

### PR DESCRIPTION
**Pull request by JackBoosY**
Since the name of the **debug** library of zlib in linux is changed to **libzd**, modify the glib **configure** file to match the **debug** version of zlib.

Related: #6644 #3601.

### CODE REVIEW

**Comment by Voskrese** [comment]
> so many problems and patches with suffix _d ...
> 
> if libraries have suffix _d why then a separate debug folder? there are problems with the debugging folder include

> and to connect a third-party project, it will be even more difficult, without all these patches and variations in finding libraries

hmm .. thinking out loud

**Comment by JackBoosY** [comment]
@Voskrese Since the cmake team has changed the zlib debug suffix([#3384](https://gitlab.kitware.com/cmake/cmake/merge_requests/3384)), I think we also need to fix it.

**Comment by JackBoosY** [comment]
**qt5-base** and **isrmrmd** require c++17 support (at least gcc-7.1).
And **shogun** needs to wait for cmake to update([#3384](https://gitlab.kitware.com/cmake/cmake/merge_requests/3384)).

**Comment by BillyONeal** [comment]
The original repository is gone and there are merge conflicts; @JackBoosY please open a new PR with these changes if you still want them.

**Pull request closed without merging**
