### PR TITLE
Issue13033

### LINKED ISSUE #13033: [boost] Update to 1.74.0
Library name: boost

New version number: 1.74.0

Other information that may be useful (release notes, etc...)
There are some mingw related fixes in boost-build that I'd like to have

### PR DESCRIPTION
**Pull request by victorburckel**
This is a duplicate of #14089 to test the suggested fixes

- What does your PR fix? Fixes #13033

- Which triplets are supported/not supported? Have you updated the CI baseline?

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

### CODE REVIEW

**Comment by SeanFarrow** [comment]
@PhoebeHui 
What is preventing this from being merged and meaning it is invalid?

**Comment by BillyONeal** [comment]
@SeanFarrow Duplicating another user's review is very strange; I'm not sure how the feedback would be any different here than in the copy/

**Comment by SeanFarrow** [comment]
I wasn’t duplicating a review, I hadn’t seen the original.
I’m trying to understand what the issue(s) that is preventing this from being merged.
Thanks,
Sean.

**Comment by victorburckel** [comment]
Hi, sorry my bad, the purpose of this pr was to test that the fixes suggested for the original PR would eventually fix the issues. I guess that's why the issue is tagged as invalid. I'll close the PR as the commits were ported to the original PR. Thanks and sorry for the misunderstanding.

**Pull request closed without merging**
