### PR TITLE
[vcpkg] Attempt to make the upgrade command 'reasonably transactional'

### PR DESCRIPTION
**Pull request by NulAsh**
Fix for #6317, #4360, #4367, #3864 (it's duplicates)

### CODE REVIEW

**Comment by NulAsh** [comment]
Ask your questions.

**Comment by cbezault** [comment]
I'm just going to leave my two cents here that I like this approach.
Even better, as pointed out #6317, would be to make the upgrade only create non-revertible changes once everything is clearly in order.
However, this is a quick fix that I think will remove most of the pain from failures during an upgrade without breaking backwards compatibility.
The only comment I might have is naming/location details of the update file (I don't really like it just hanging around the root of vcpkg), but likely @ras0219-msft has an opinion on that.

**Comment by NulAsh** [comment]
image
What's wrong with the tests?

**Comment by dan-shaw** [comment]
@NulAsh Going to close this PR as this PR has been open too long. If you are interested in working on this, feel free to reopen, but it might make more sense to make a new PR (otherwise we might lose track of it).

That said, I do think the upgrade command needs fixing.

**Comment by dan-shaw** [comment]
Also I realize we haven't given any feedback on this PR for a long time. If you are still interested in some feedback, let me know and we can reopen this and prioritize this PR.

**Comment by NulAsh** [comment]
Of course I'm interested, this is a working solution to a problem that many people face.

**Comment by dan-shaw** [comment]
@NulAsh We will review it and get some feedback.

**Comment by elibroftw** [comment]
3.5 years later...

**Comment by vicroms** [comment]
Closing this PR since it no longer applies to this repository. If still interested, please open a PR in [Microsoft/vcpkg-tool](https://github.com/Microsoft/vcpkg-tool).

**Pull request closed without merging**
