### PR TITLE
[geographiclib] Update to version 1.51

### PR DESCRIPTION
**Pull request by cffk**
This is just a routine upgrade.

- What does your PR fix? Routine upgrade to 1.51

- Which triplets are supported/not supported? Have you updated the CI baseline? No changes

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)? Yes

### CODE REVIEW

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
Have you tested the feature tool? @cffk

**Comment by cffk** [comment]
> Have you tested the feature tool? @cffk

Yes, I have.  However I've moved this to draft so I can verify whether that it still works with shared libraries.  (This may be an issue for Linux, since the rpath is set to ../lib, which won't work once the tools are copied to tools/geographiclib.)

Also, should man pages be installed for the tools?  They aren't currently but they could easily be.

**Comment by cffk** [comment]
OK, I'm done with my changes.  The main one was to fix the RPATH for the tools so that the shared libraries could be found from tools/geographiclib.  (I realize that this is moot because the linux builds are for a static library.  But I hope that at some point vcpkg supports dynamic libraries on linux.)

I've tested the tools feature on linux + windows + macos.

Should I worry about the failed checks?  They look like timeouts on downloading the source and other things (like geotrans) that I have no control over.

**Comment by NancyLi1013** [comment]
Thanks for your update.

For downloading `geotrans`, it might be something with the network. I checked this on my machine and it can be downloaded successfully. I will try to rerun this PR.

For dynamic support on Linux, vcpkg might implement this point in future.

**Comment by NancyLi1013** [comment]
LGTM now, thanks for your PR @cffk.

**Comment by cffk** [comment]
Thanks @NancyLi1013   This PR is ready for merging!

**Comment by strega-nil** [comment]
Thanks @cffk :)

**Pull request merged**
