### PR TITLE
[docs] Add comment about VCPKG_TARGET_TRIPLET to README and installing package

### PR DESCRIPTION
**Pull request by SallySoul**
**Describe the pull request**

- #### What does your PR fix?  
 I recently had an [issue](https://github.com/microsoft/vcpkg/issues/19528) where I needed to specify `VCPKG_TARGET_TRIPLET`. I now see that I missed the critical piece of information at the bottom of [integration.md](https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md). However, I'm of the opinion. VCPKG_TARGET_TRIPLET deserved some mention in a couple other areas.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline]
Its a documentation update.

- #### Does your PR follow the [maintainer guide]
To the best of my knowledge

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
N/A

### CODE REVIEW

**Comment by PhoebeHui** [comment]
@SallySoul, thanks for the PR! Could you sign the CLA?

**Comment by SallySoul** [comment]
Signed. I can't re-run the checks though.

**Comment by PhoebeHui** [comment]
The baseline issue would be fixed by PR https://github.com/microsoft/vcpkg/pull/19633. I will rerun the CI after the PR merged.

**Review by PhoebeHui — APPROVED** [review]

**Review by PhoebeHui — APPROVED** [review]

**Comment by Neumann-A** [comment]
also needs info about `VCPKG_HOST_TRIPLET` to be complete

**Comment by SallySoul** [comment]
@Neumann-A sure, I'll update the PR shortly.

**Comment by SallySoul** [comment]
@PhoebeHui Is there anything needed from me to push this along?

**Comment by PhoebeHui** [comment]
@SallySoul,  It looks good for me now, thanks!

**Comment by BillyONeal** [comment]
I'm not entirely convinced that this warrants such a big block in the front "readme" -- since the longer readmes get the less likely people are to actually read them, and we don't expect most customers to need to customize triplets that often. If it is something that should be in the readme, I made some changes I would prefer to see against this: https://github.com/BillyONeal/vcpkg/commit/d17fdc0b704357c197ab2753a0aca763107be401

I want @strega-nil / @strega-nil-ms to take a look before landing this since she has Strong opinions about our docs.

**Comment by strega-nil-ms** [comment]
I'm of the opinion that triplets are important enough that they belong in the README, or at least in the first thing people read; however, it doesn't make sense to me to put it under the CMake integration section. Maybe it's own section?

**Comment by BillyONeal** [comment]
The maintainers talked about this in person today and we are OK with adding a block about triplets into the readme but would like @SallySoul to address Nicole's (@strega-nil / @strega-nil-ms ) concerns before merging this.

**Comment by SallySoul** [comment]
@strega-nil Happy to make changes. However, I need some clarification.

First, my experience with vcpkg is limited to use with cmake projects. What are some other use cases of vcpkg targets that I should be mindful of?

Also, where would you like this new section in the README? Given that cmake has a relatively large block in the the current structure, it's not clear to me where a triplet section would belong. Maybe right after the cmake section under "Getting Started"?

**Comment by strega-nil-ms** [comment]
@SallySoul I honestly think that yeah, it could just be its own section. Adding a blurb about how to use this from msbuild would be good too, but I can write that blurb.

**Comment by PhoebeHui** [comment]
Ping @SallySoul for response.

**Comment by PhoebeHui** [comment]
We don't have permission to push changes to this PR, closing this PR since it seems that no progress is being made. Please reopen if work is still being done.

**Pull request closed without merging**
