### PR TITLE
[boost-modular-build-helper] Fix boost build gcc macos

### LINKED ISSUE #22380: [boost-system] build failure in nix environment (gcc on macos)
**Host Environment**
- OS: Darwin
- Compiler: gcc-11
```
$ g++ --version
g++ (GCC) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**To Reproduce**
1. `curl -L https://nixos.org/nix/install | sh`
2. Create those three nix files in an empty directory:
`default.nix`:
```nix
{
    pkgs   ? import <nixpkgs> {},
    stdenv ? pkgs.gcc11Stdenv
}:
rec {
  test_pkg = stdenv.mkDerivation rec {
    name = "test_pkg";
    version = "dev-0.1";
    vcpkg_tool = pkgs.callPackage ./vcpkg-tool.nix {};
    vcpkg = pkgs.callPackage ./vcpkg.nix {};
    buildInputs = with pkgs; [
      gcc11
      ninja
      cmake
      vcpkg_tool
      vcpkg
      git
      perl
      
      # vcpkg dependencies
      curl
      zip
      unzip
    ];

    VCPKG_ROOT = "${builtins.getEnv "PWD"}/.vcpkg";
    VCPKG_DOWNLOADS = "${builtins.getEnv "PWD"}/.vcpkg/downloads";

    shellHook =
    ''
      rm -Rf ./.vcpkg/{docs,ports,scripts,triplets,vcpkg}
      mkdir -p ${VCPKG_ROOT}
      mkdir -p ${VCPKG_ROOT}/downloads
      ln -s ${vcpkg_tool}/bin/vcpkg ${VCPKG_ROOT}/
      ln -s ${vcpkg}/share/vcpkg/{docs,ports,scripts,triplets} ${VCPKG_ROOT}/
    '';
  };
}
```
`vcpkg-tool.nix`:
```nix
{ gcc11Stdenv, gcc11, fetchFromGitHub, ninja, cmake, git, cacert }:

gcc11Stdenv.mkDerivation {
  name = "vcpkg-tool-2021-12-09";

  src = fetchFromGitHub {
    owner = "microsoft";
    repo = "vcpkg-tool";
    rev = "2021-12-09";
    sha256 = "0027fbm6vd82qiddg92wslabsi2dvpfxgyin67fna97xz2hnzr9l";
  };

  buildInputs = [cmake ninja git cacert gcc11];
}
```
`vcpkg.nix`:
```nix
{ gcc11Stdenv, fetchFromGitHub }:

gcc11Stdenv.mkDerivation {
  name = "vcpkg-tool-11c070bc3faca4b3173fd7aa363d830c220a61c7";

  src = fetchFromGitHub {
    # this is only to get openssl-1.1.1m (https://github.com/microsoft/vcpkg/pull/22376)
    owner = "gracicot";
    repo = "vcpkg";
    rev = "11c070bc3faca4b3173fd7aa363d830c220a61c7";
    sha256 = "1q21nz83f0gl3bcvvwsvyki562w26bvndx9z8c9gs5cm6sm3hm5b";
  };

  dontConfigure = true;
  buildPhase = "";

  installPhase = ''
    mkdir -p $out/share/vcpkg
    cp --preserve=mode -r ./{docs,ports,scripts,triplets,.vcpkg-root} $out/share/vcpkg
  '';
  buildInputs = [];
}
```
3. In the directory with the three file, run `nix-shell --pure`
4. run `vcpkg install boost-system`

**Failure logs** 
```
$ vcpkg install boost-system
Computing installation plan...
The following packages will be built and installed:
    boost-system[core]:x64-osx -> 1.77.0
Detecting compiler hash for triplet x64-osx...
Restored 0 packages from /Users/grc/.cache/vcpkg/archives in 29 us. Use --debug to see more details.
Starting package 1/1: boost-system:x64-osx
Building package boost-system[core]:x64-osx...
-- Using cached boostorg-system-boost-1.77.0.tar.gz.
-- Cleaning sources at /Users/myuser/Workspace/project/.vcpkg/buildtrees/boost-system/src/ost-1.77.0-99f78bb632.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /Users/myuser/Workspace/project/.vcpkg/downloads/boostorg-system-boost-1.77.0.tar.gz
-- Using source at /Users/myuser/Workspace/project/.vcpkg/buildtrees/boost-system/src/ost-1.77.0-99f78bb632.clean
-- Found external ninja('1.10.2').
-- Configuring x64-osx-dbg
-- Configuring x64-osx-rel
-- Building x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: /nix/store/gcinad2bdm3fkyxjs73vwqy0pq3wr25m-cmake-3.21.2/bin/cmake --build . --config Debug --target install -- -v -j9
    Working Directory: /Users/myuser/Workspace/project/.vcpkg/buildtrees/boost-system/x64-osx-dbg
    See logs for more information:
      /Users/myuser/Workspace/project/.vcpkg/buildtrees/boost-system/install-x64-osx-dbg-out.log

Call Stack (most recent call first):
  installed/x64-osx/share/vcpkg-cmake/vcpkg_cmake_build.cmake:102 (vcpkg_execute_build_process)
  installed/x64-osx/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  installed/x64-osx/share/boost-build/boost-modular-build.cmake:105 (vcpkg_cmake_install)
  ports/boost-system/portfile.cmake:17 (boost_modular_build)
  scripts/ports.cmake:142 (include)


Error: Building package boost-system:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `./vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-system
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[boost-system]+Build+error
including:
  package: boost-system[core]:x64-osx -> 1.77.0
    vcpkg-tool version: 2999-12-31-unknownhash
    vcpkg-scripts version: unknown

Additionally, attach any relevant sections from the log files above.
```
The file `install-x64-osx-dbg-out.log` contains:
```
[1/2] cd /Users/myuser/Workspace/project/.vcpkg/buildtrees/boost-system/src/ost-1.77.0-99f78bb632.clean/build && /Users/myuser/Workspace/project/.vcpkg/installed/x64-osx/tools/boost-build/b2 toolset=clang --user-config=/Users/myuser/Workspace/project/.vcpkg/buildtrees/boost-system/x64-osx-dbg/user-config.jam --stagedir=/Users/myuser/Workspace/project/.vcpkg/buildtrees/boost-system/x64-osx-dbg/stage --build-dir=/Users/myuser/Workspace/project/.vcpkg/buildtrees/boost-system/x64-osx-dbg -sICU_PATH="ICU_PATH-NOTFOUND" runtime-link=shared link=static address-model=64 architecture=x86 target-os=darwin threadapi=pthread variant=debug --layout=system --with-atomic --with-random --with-date_time --with-filesystem --with-system --with-thread --with-chrono -j8 -sBOOST_ROOT=/Users/myuser/Workspace/project/.vcpkg/installed/x64-osx/tools/boost-build -sBOOST_BUILD_PATH=/Users/myuser/Workspace/project/.vcpkg/installed/x64-osx/tools/boost-build --debug-configuration --debug-building --debug-generators --ignore-site-config --hash -q debug-symbols=on -d +2 threading=multi stage
FAILED: CMakeFiles/boost /Users/myuser/Workspace/project/.vcpkg/buildtrees/boost-system/x64-osx-dbg/CMakeFiles/boost 
cd /Users/myuser/Workspace/project/.vcpkg/buildtrees/boost-system/src/ost-1.77.0-99f78bb632.clean/build && /Users/myuser/Workspace/project/.vcpkg/installed/x64-osx/tools/boost-build/b2 toolset=clang --user-config=/Users/myuser/Workspace/project/.vcpkg/buildtrees/boost-system/x64-osx-dbg/user-config.jam --stagedir=/Users/myuser/Workspace/project/.vcpkg/buildtrees/boost-system/x64-osx-dbg/stage --build-dir=/Users/myuser/Workspace/project/.vcpkg/buildtrees/boost-system/x64-osx-dbg -sICU_PATH="ICU_PATH-NOTFOUND" runtime-link=shared link=static address-model=64 architecture=x86 target-os=darwin threadapi=pthread variant=debug --layout=system --with-atomic --with-random --with-date_time --with-filesystem --with-system --with-thread --with-chrono -j8 -sBOOST_ROOT=/Users/myuser/Workspace/project/.vcpkg/installed/x64-osx/tools/boost-build -sBOOST_BUILD_PATH=/Users/myuser/Workspace/project/.vcpkg/installed/x64-osx/tools/boost-build --debug-configuration --debug-building --debug-generators --ignore-site-config --hash -q debug-symbols=on -d +2 threading=multi stage
notice: found boost-build.jam at /Users/myuser/Workspace/project/.vcpkg/installed/x64-osx/tools/boost-build/boost-build.jam
notice: loading B2 from /Users/myuser/Workspace/project/.vcpkg/installed/x64-osx/tools/boost-build/src/kernel/bootstrap.jam
notice: Site configuration files will be ignored due to the
notice: --ignore-site-config command-line option.
notice: Loading explicitly specified user configuration file:
    /Users/myuser/Workspace/project/.vcpkg/buildtrees/boost-system/x64-osx-dbg/user-config.jam
notice: Searching '/Users/myuser/Workspace/project/.vcpkg/buildtrees/boost-system/x64-osx-dbg' for user-config configuration file 'user-config.jam'.
notice: Loading user-config configuration file 'user-config.jam' from '/Users/myuser/Workspace/project/.vcpkg/buildtrees/boost-system/x64-osx-dbg'.
/Users/myuser/Workspace/project/.vcpkg/installed/x64-osx/tools/boost-build/src/tools/common.jam:1171: in common.match-command-output from module common
error: '"/nix/store/ci8zayp097bfrhzxbwq62wk8ksp1i2g8-gcc-wrapper-11.2.0/bin/g++" --version' returned an invalid $kind string 'g++ (GCC) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

'
/Users/myuser/Workspace/project/.vcpkg/installed/x64-osx/tools/boost-build/src/tools/clang-linux.jam:112: in get-full-version from module clang-linux
/Users/myuser/Workspace/project/.vcpkg/installed/x64-osx/tools/boost-build/src/tools/clang-linux.jam:117: in clang-linux.get-short-version from module clang-linux
/Users/myuser/Workspace/project/.vcpkg/installed/x64-osx/tools/boost-build/src/tools/clang-darwin.jam:88: in get-short-version from module clang-darwin
/Users/myuser/Workspace/project/.vcpkg/installed/x64-osx/tools/boost-build/src/tools/clang-darwin.jam:61: in clang-darwin.init from module clang-darwin
/Users/myuser/Workspace/project/.vcpkg/installed/x64-osx/tools/boost-build/src/build/toolset.jam:44: in toolset.using from module toolset
/Users/myuser/Workspace/project/.vcpkg/installed/x64-osx/tools/boost-build/src/tools/clang.jam:28: in clang.init from module clang
/Users/myuser/Workspace/project/.vcpkg/installed/x64-osx/tools/boost-build/src/build/toolset.jam:44: in toolset.using from module toolset
/Users/myuser/Workspace/project/.vcpkg/installed/x64-osx/tools/boost-build/src/build/project.jam:1104: in using from module project-rules
/Users/myuser/Workspace/project/.vcpkg/buildtrees/boost-system/x64-osx-dbg/user-config.jam:11: in modules.load from module user-config
/Users/myuser/Workspace/project/.vcpkg/installed/x64-osx/tools/boost-build/src/build-system.jam:255: in load-config from module build-system
/Users/myuser/Workspace/project/.vcpkg/installed/x64-osx/tools/boost-build/src/build-system.jam:449: in load-configuration-files from module build-system
/Users/myuser/Workspace/project/.vcpkg/installed/x64-osx/tools/boost-build/src/build-system.jam:607: in load from module build-system
/Users/myuser/Workspace/project/.vcpkg/installed/x64-osx/tools/boost-build/src/kernel/modules.jam:295: in import from module modules
/Users/myuser/Workspace/project/.vcpkg/installed/x64-osx/tools/boost-build/src/kernel/bootstrap.jam:139: in boost-build from module
/Users/myuser/Workspace/project/.vcpkg/installed/x64-osx/tools/boost-build/boost-build.jam:8: in module scope from module

ninja: build stopped: subcommand failed.
```

**Additional context**

I know it's kind of an unusual setup, but vcpkg is capable of installing many other packages, including OpenSSL (given the new 1.1.1m version) and many other boost packages. **Only `boost-system` seems to be a problem.**

I noticed that the errors are related to me selecting GCC as compiler instead of clang. I also notice that build commands try to select clang and `libc++`, which are not available in the selected environment. Maybe selecting a proper triplet would help?

I was also wondering if this was a vcpkg bug to not pass to `boost-build` that GCC is selected as compiler, as it seem to assume that clang with libc++ is used. I simply wanted to be sure and maybe be directed on the right path.

Thanks *a lot* for your help and your support ;)

### PR DESCRIPTION
**Pull request by gracicot**
**Describe the pull request**

Allows boost to be built by GCC on MacOS. I changes to behaviour of boost-modular-build-helper to send `gcc` as being the compiler when using GCC as compilier instead of hardcoding clang.

- #### What does your PR fix?  
  Fixes #22380

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  x64-osx, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
 Yes

### CODE REVIEW

**Comment by gracicot** [comment]
@yurybura I'm tagging you here since we were already in contact while discussing the issue

**Comment by gracicot** [comment]
I marked it as ready, since I'm able to install `boost-system` and link to it to create an executable on MacOS using only GCC.

**Comment by gracicot** [comment]
Seems like there are error with `rtabmap:x64-windows`, but this is completely unrelated to my pull request.

**Comment by PhoebeHui** [comment]
The baseline issue would be fixed by https://github.com/microsoft/vcpkg/pull/22534, please ignore it.

**Review by PhoebeHui — APPROVED** [review]
Thanks for the PR!

**Comment by strega-nil-ms** [comment]
Thanks!

**Pull request merged**
