### PR TITLE
[wt] Fix port for Android and iOS

### PR DESCRIPTION
**Pull request by bold84**
Upstream PR: https://github.com/emweb/wt/pull/206

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] SHA512s are updated for each updated download
- [ ] The "supports" clause reflects platforms that may be fixed by this new version
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [ ] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by MonicaLiu0311** [comment]
All features are tested successfully in the following triplet:
```
x86-windows
x64-windows
x64-windows-static
```

The usage test passed on `x64-windows` (header files found):
```
wt provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(wt CONFIG REQUIRED)
    # note: 4 additional targets are not displayed.
    target_link_libraries(main PRIVATE Wt::Wt Wt::Dbo Wt::HTTP Wt::Test)
```

**Review by MonicaLiu0311 — APPROVED** [review]

**Comment by MonicaLiu0311** [comment]
There has been no response from upstream for three months, so this PR is continued.

**Comment by BillyONeal** [comment]
I think we could merge this under our cooldown period rules but I don't think the patch is correct. I left comments in the upstream PR.

**Comment by BillyONeal** [comment]
(I don't think we need to give upstream an entire month for subsequent changes)

**Comment by MonicaLiu0311** [comment]
The upstream merged https://github.com/emweb/wt/pull/206 last week, please continue your PR.

**Comment by MonicaLiu0311** [comment]
Ping @bold84

**Comment by MonicaLiu0311** [comment]
Closing this PR since it seems that no progress is being made. Please ping us to reopen if work is still being done. Replaced by https://github.com/microsoft/vcpkg/pull/38063.

**Pull request closed without merging**
