### PR TITLE
[vcpkg-cmake-get-vars] Collect PIC flags

### PR DESCRIPTION
**Pull request by russelltg**
- [vcpkg-cmake-get-vars] add PIC flags if CMAKE_POSITION_INDEPENDENT_CODE is set
- ./vcpkg x-add-version --all

The issue I was running into is I was building static boost libs with a chainloaded toolchain that set `CMAKE_POSITIION_INDEPENDENT_CODE` to true, and I realized it wasn't being respected because it wasn't collected properly in `vcpkg-cmake-get-vars`

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by russelltg** [comment]
Gotcha--I felt like I was just following the example of the `CMAKE_SYSROOT` handling

**Comment by russelltg** [comment]
I think this makes sense because I'd expect a triplet that set `VCPKG_CMAKE_CONFIGURE_OPTIONS` to `-DCMAKE_POSITION_INDEPENDENT_CODE=ON` to work on all ports, including ones like boost that use this vcpkg-cmake-get vars. 

It feels like having to specify the flags explicitly is poor CMake style?

I think it's probably okay to continue not propagating CMAKE_<LANG>_STANDARD considering that feels like more of a project specific thing than PIC. 

The other way I could see addressing this is the boost port extracting CMAKE_POSITION_INDEPENDENT_CODE=ON using vcpkg-cmake-get-vars and it using that to decide if it should add -fPIC. Would that be preferable?

**Comment by LilyWangLL** [comment]
Pinging @russelltg for response. Is work still being done for this PR?

**Comment by russelltg** [comment]
Well it seems like it's a bit contraversial, I'm happy to work on it if there's interest in this approach. Otherwise I can open a PR in the boost build stuff to add PIC flags when requested

**Comment by LilyWangLL** [comment]
I will be converting your PR to draft status, waiting for other users suggestion.

**Comment by LilyWangLL** [comment]
Closing this PR since it seems that no progress is being made. Please ping us to reopen if this PR has new progress.

**Pull request closed without merging**
