### PR TITLE
[gdal] Update to 3.8.0

### PR DESCRIPTION
**Pull request by dg0yt**

### CODE REVIEW

**Comment by BillyONeal** [comment]
Restarting run because SAS tokens got reset

**Comment by LilyWangLL** [comment]
Please fix this:
```
warning: The following EXEs were found in /bin or /debug/bin. EXEs are not valid distribution targets.

  F:\gdal\packages\gdal_x64-windows\bin\gdal_footprint.exe

error: Found 1 post-build check problem(s). To submit these ports to curated catalogs, please first correct the portfile: F:\gdal\ports\gdal\portfile.cmake
```

**Comment by dg0yt** [comment]
Done. And removed two duplicates, after sorting the tool names.

**Comment by LilyWangLL** [comment]
All features passed with following triplets:
```
x86-windows
x64-windows
x64-windows-static
```

**Review by LilyWangLL — APPROVED** [review]

**Pull request merged**
