### PR TITLE
add x264 package for vcpkg

### PR DESCRIPTION
**Pull request by melchi45**
add x264 package for vcpkg

### CODE REVIEW

**Comment by jasjuang** [comment]
thanks for creating this

**Comment by ras0219-msft** [comment]
Thanks for the PR!

I simplified the parts of the portfile that I could. Additionally, I switched it to use the GitHub mirror instead (mirror/x264) which enables sharing our existing reliable `vcpkg_from_github()`.

**Comment by MarekMaslanka** [comment]
I have an issue while building this package on Windows 10.
Logs from: buildtrees\x264\config-x86-windows-dbg-out.log
```
Unknown option --build=i686-pc-mingw32, ignored
Unknown option --target=x86_64-pc-mingw32, ignored
Unknown option --disable-silent-rules, ignored
Unknown option --verbose, ignored
Unknown option --disable-shared, ignored
Unknown option --sbindir=${prefix}/../tools/x264/debug/sbin, ignored
Unknown option --datarootdir=${prefix}/share/x264, ignored
No working C compiler found.
```

**Comment by VFoV** [comment]
> I have an issue while building this package on Windows 10.
> Logs from: buildtrees\x264\config-x86-windows-dbg-out.log
> 
> ```
> Unknown option --build=i686-pc-mingw32, ignored
> Unknown option --target=x86_64-pc-mingw32, ignored
> Unknown option --disable-silent-rules, ignored
> Unknown option --verbose, ignored
> Unknown option --disable-shared, ignored
> Unknown option --sbindir=${prefix}/../tools/x264/debug/sbin, ignored
> Unknown option --datarootdir=${prefix}/share/x264, ignored
> No working C compiler found.
> ```

I also get this exact config log output

**Pull request merged**
