### PR TITLE
[openal-soft] add 'pipewire' feature and PulseAudio backend

### PR DESCRIPTION
**Pull request by quyykk**
- #### What does your PR fix?

This PR builds [openal-soft] with the PulseAudio backend enabled on Linux and adds the 'pipewire' feature that enables Pipewire support. 

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
linux

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
yeah

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
yeah

### CODE REVIEW

**Review by JonLiu1993 — APPROVED** [review]

**Comment by JonLiu1993** [comment]
@quyykkx, Thanks for your pr, when I test the feature with command "./vcpkg install openal-soft[*]" I meet a error log:
````
Traceback (most recent call last):
  File "/home/Jon/test/vcpkg/installed/x64-linux/tools/meson/meson.py", line 26, in <module>
    from mesonbuild import mesonmain
  File "/home/Jon/test/vcpkg/installed/x64-linux/tools/meson/mesonbuild/mesonmain.py", line 28, in <module>
    from . import mesonlib
  File "/home/Jon/test/vcpkg/installed/x64-linux/tools/meson/mesonbuild/mesonlib/__init__.py", line 21, in <module>
    from .universal import *
  File "/home/Jon/test/vcpkg/installed/x64-linux/tools/meson/mesonbuild/mesonlib/universal.py", line 17
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined

````

**Comment by quyykk** [comment]
What can I say except "It works on my machine:tm:". I think your Python version may be too old.

**Comment by JonLiu1993** [comment]
> What can I say except "It works on my machine™️". I think your Python version may be too old.

I update my python version to 3.7.7 and test feature successfully in x64-linux triplet

**Comment by BillyONeal** [comment]
Thanks!

**Pull request merged**
