### PR TITLE
[google-cloud-cpp] Upgrade to v0.17.0

### PR DESCRIPTION
**Pull request by coryan**
Upgrade google-cloud-cpp to the (just released) v0.17.0

### CODE REVIEW

**Review by PhoebeHui — APPROVED** [review]
Thanks for the PR!

**Comment by coryan** [comment]
@PhoebeHui the OSX breakage seems unrelated.  Would it help if I rebased to the latest `master`?

**Comment by PhoebeHui** [comment]
@coryan, PR https://github.com/microsoft/vcpkg/pull/9600 will fix the failures on OSX, it's not related to your changes. Please ignore it.

**Pull request merged**
