### PR TITLE
[vcpkg-get-python-packages] Fix exported variable

### PR DESCRIPTION
**Pull request by dg0yt**
Noticed while trying to use another variable name then `PYTHON3` with `lensfun`.
In addition:
- fix typos
- make precompiled archive optional.

### CODE REVIEW

**Review by MonicaLiu0311 — DISMISSED** [review]

**Comment by dg0yt** [comment]
https://github.com/microsoft/vcpkg/blob/11e79b1072c7f12d84258b77948cda3b166aac59/ports/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake#L78-L80
This file isn't installed by `python3:x64-windows`. So the function still breaks when used with the executable from that port.  
https://dev.azure.com/vcpkg/public/_build/results?buildId=98885&view=logs&j=7922e5c4-0103-5f8f-ad17-45ce9bb98e80&t=66eef212-08d6-5e6c-a560-7d01149d0188 
CC @Neumann-A

**Comment by Neumann-A** [comment]
`file(COPY "${python_dir}/python3${PYTHON_VERSION_MINOR}.zip" DESTINATION "${venv_path}/Scripts")`

probably needs to be generated by the python port itself. Ran already into several issues with embedded python not finding the default scripts but need a good way to compose other modules into that.

**Comment by dg0yt** [comment]
Hm. I wonder if the actual problem with this port/function is that `pip install` bypasses asset caching.

**Comment by Neumann-A** [comment]
It should only install into the venv not into the installed tree.

**Comment by dg0yt** [comment]
> It should only install into the venv not into the installed tree.

Yes. And still it is a problem for disconnected builds after `--only-downloads`. Unlike most tools which also aren't installed into the installed tree.

Pip has its own caching. And it is also possible to pre-download to a local downloads dir and to install later from that dir:  
https://pip.pypa.io/en/stable/user_guide/#installing-from-local-packages  
Maybe this will eventually need an injection point and instruction on how to prepare and pass in the local dir. Which may require to build `python3` first to get matching downloads.

(I'm also looking at jinja2: Repeatedly popping up now as a `libsystemd` requirement since this port was allowed to enter this registry, https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+libsystemd+jinja2)

**Review by MonicaLiu0311 — APPROVED** [review]

**Pull request merged**
