### PR TITLE
[libatomic-ops] New port

### PR DESCRIPTION
**Pull request by ivmai**
- #### What does your PR fix?  
Adds libatomic-ops port (it will be needed for bdwgc port with multi-threading support).

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
all

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
Yes

### CODE REVIEW

**Comment by ivmai** [comment]
The PR contains 2 commits, but I'm going to polish and test 1st one, and then add the 2nd one.

**Comment by ivmai** [comment]
> The PR contains 2 commits, but I'm going to polish and test 1st one, and then add the 2nd one.

I've decided to leave libatomic-ops port addition here, and create another PR enabling multi-threading in bdwgc.

@JonLiu1993, please remove category:port-feature label.

**Review by ras0219-msft — APPROVED** [review]
Thanks for the PR and awesome library!

I noticed that the CMake package name is "Atomic_ops", so I adjusted the helper calls to correctly account for that name. I now get:
```
$ vcpkg install libatomic-ops
...
Elapsed time for package libatomic-ops:x64-linux: 703 ms

Total elapsed time: 966.5 ms

The package libatomic-ops provides CMake targets:

    find_package(Atomic_ops CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Atomic_ops::atomic_ops Atomic_ops::atomic_ops_gpl)

```

**Comment by ivmai** [comment]
> I noticed that the CMake package name is "Atomic_ops", so I adjusted the helper calls to correctly account for that name

Okay, thank you.

**Pull request merged**
