### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Prathu121**
**Describe the pull request**
Some typo errors and linguistical mistakes

### CODE REVIEW

**Comment by Hoikas** [comment]
Spam due to hacktoberfest.

**Comment by BillyONeal** [comment]
Due to overwhelming community dislike and this not being a meaningful improvement, closing this as "invalid".

**Comment by Hoikas** [comment]
@BillyONeal please tag this as "invalid" or "spam" so this user will not receive hacktoberfest credit. :)

**Comment by BillyONeal** [comment]
@Hoikas How do I do that? (Do we need to create a label for this?)

**Comment by Hoikas** [comment]
Yes, per the [Hacktoberfest FAQ](https://hacktoberfest.digitalocean.com/faq), any "[p]ull requests that contain a label with the word invalid or spam won’t be counted toward Hacktoberfest." I'm not sure how robust the "word detection" is though. IME most projects use a label named exactly "spam" or "invalid".

**Pull request closed without merging**
