### PR TITLE
[vcpkg] Improve Target Architecture Detection on ARM64 Windows

### LINKED ISSUE #27477: Unable to determine target architecture on ARM64 Windows with MinGW-w64 Toolchain via MSYS2
**Describe the bug**
On ARM64 Windows machines, %PROCESSOR_ARCHITECTURE% is set to **ARM64** as shown in the following screenshot.
image

vcpkg.cmake should be updated to support ARM64 Windows machines at line 324.
image

**Environment**
- OS: ARM64 Windows
- a CMake Project in VS using MinGW64 environment.

**To Reproduce**
1. ./vcpkg install proxy
2. Install MinGW64.
3. Open attached VcpkgMingw64 project in VS.
4. Select "Mingw64-Debug" and generate CMake cache.
5. Observe that vcpkg couldn't determine the target architecture.

[VcpkgMingw64.zip](https://github.com/microsoft/vcpkg/files/9874038/VcpkgMingw64.zip)

image

**Expected behavior**
vcpkg should be able to determine the target architecture and continue.

**Failure logs**
- see above screenshot.

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by kuchungmsft**
**Describe the pull request**

- #### What does your PR fix?
  Fixes #27477

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  N/A

### CODE REVIEW

**Comment by Cheney-W** [comment]
CMake Error at scripts/test_ports/cmake-user/portfile.cmake:213 (message):
##[error]CMake 3.24.0: build with
  `find_package(wxWidgets)` failed.
    See logs for more information:
      /mnt/vcpkg-ci/buildtrees/cmake-user/x64-linux-3.24.0-find-package-wxWidgets-release-build-out.log
      [/mnt/vcpkg-ci/buildtrees/cmake-user/x64-linux-3.24.0-find-package-wxWidgets-release-build-err.log](https://dev.azure.com/vcpkg/_apis/resources/Containers/19224998/failure%20logs%20for%20x64-linux?itemPath=failure%20logs%20for%20x64-linux%2Fcmake-user%2Fx64-linux-3.24.0-find-package-wxWidgets-release-build-err.log)

ninja: error: '/mnt/vcpkg-ci/installed/x64-linux/lib/libEGL.a', needed by 'exe', missing and no known rule to make it

**Comment by dg0yt** [comment]
> x64-linux-3.24.0-find-package-wxWidgets

This is a baseline regression, unrelated to this PR.
(#27244 coulnd't reproduce it. AFAIU it is an installation order problem with port angle, and a related change as in the open Qt PRs.)

**Comment by kuchungmsft** [comment]
> CMake Error at scripts/test_ports/cmake-user/portfile.cmake:213 (message): ##[error]CMake 3.24.0: build with `find_package(wxWidgets)` failed. See logs for more information: /mnt/vcpkg-ci/buildtrees/cmake-user/x64-linux-3.24.0-find-package-wxWidgets-release-build-out.log [/mnt/vcpkg-ci/buildtrees/cmake-user/x64-linux-3.24.0-find-package-wxWidgets-release-build-err.log](https://dev.azure.com/vcpkg/_apis/resources/Containers/19224998/failure%20logs%20for%20x64-linux?itemPath=failure%20logs%20for%20x64-linux%2Fcmake-user%2Fx64-linux-3.24.0-find-package-wxWidgets-release-build-err.log)
> 
> ninja: error: '/mnt/vcpkg-ci/installed/x64-linux/lib/libEGL.a', needed by 'exe', missing and no known rule to make it

The failures don't seem to be related to my pull request, is there a way I can re-queue the failed checks?

**Comment by dg0yt** [comment]
> The failures don't seem to be related to my pull request, is there a way I can re-queue the failed checks?

`git commit --allow-empty -m CI; git push` -  but don't be surprised if you get the same result.

**Comment by BillyONeal** [comment]
Thanks :)

**Pull request merged**
