### PR TITLE
[libvpx] Added support for build on MacOS and Linux

### PR DESCRIPTION
**Pull request by kafeg**
**Describe the pull request**

- Added support for build libvpx on Mac and Linux

- x64-linux, x64-osx

### CODE REVIEW

**Comment by kafeg** [comment]
Hello! I got error "There are no build logs for libvpx build. bla bla bla" for the "vcpkg-osx-PR-test"

**But everything was built fine.**

Can you please help me with understanding and fixing the problem?

**Comment by LilyWangL** [comment]
Thanks for your PR. Could you please remove the following codes in _scripts/ci.baseline.txt_, it makes Linux and MACOS build failed.
```
libvpx:x64-linux=fail
libvpx:x64-osx=fail
```

**Comment by kafeg** [comment]
Done! Thank you for your prompt!

**Review by LilyWangL — APPROVED** [review]

**Comment by strega-nil** [comment]
@kafeg would you mind resolving the merge conflict? otherwise, this looks great, and I'd love to merge it :)

**Comment by kafeg** [comment]
Hey @strega-nil ! Thank you for remind ;)
Conflicts fixed, locally everything builds fine, but there is again something wrong with CI...

**Comment by kafeg** [comment]
Hello @strega-nil? Is everything ok? Could you merge this, please? :pray:

**Comment by strega-nil** [comment]
Yep, I just somehow missed it in my notifications, sorry!

**Pull request merged**
