### PR TITLE
[many ports] Update HTTP to HTTPS links where it can be done safely.

### PR DESCRIPTION
**Pull request by scovetta**
**Describe the pull request**
This PR updates HTTP link (e.g. http://foo) to HTTPS where it can be done safely. 
"Safely" means that the HTTP-based link gave a 200 response with identical
content to the HTTPS version of the link. For links containing
variables, we checked the interpolated (real) link.

This PR covers the first 15 changes.

- #### What does your PR fix?  
#20219 (partial fix, additional PRs to come)

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
<all / no>

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
Yes, though this covers multiple ports as per guidance from #20219.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
N/A

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Review by BillyONeal — APPROVED** [review]

**Comment by BillyONeal** [comment]
@scovetta Do you want to merge this now? Next time you need to do version updates to the vcpkg.jsons next to the relevant portfile.cmakes.

**Comment by BillyONeal** [comment]
@scovetta *ping*

**Comment by JonLiu1993** [comment]
Ping @scovetta for response, Is work still being done for this PR?

**Comment by JonLiu1993** [comment]
@scovetta ping for response

**Comment by JonLiu1993** [comment]
@scovetta ,It looks like this pr is ok, ready for review?

**Comment by JonLiu1993** [comment]
@scovetta ,Can you please resolve the conflicts against master?

**Comment by BillyONeal** [comment]
I also asked Michael over Teams.

**Comment by JonLiu1993** [comment]
@scovetta ,Can you please resolve the conflicts against master?

**Comment by BillyONeal** [comment]
> @scovetta ,Can you please resolve the conflicts against master?

I took care of it :)

**Review by BillyONeal — APPROVED** [review]

**Comment by scovetta** [comment]
Thanks @BillyONeal!

Since I'm super short on cycles for this, (and have been for some time), I've uploaded the script that I used to find, validate, and rewrite certain files. Feel free to use it as you wish.

https://gist.github.com/scovetta/51e15537309d25f3617f908fcd2a1327

**Comment by strega-nil-ms** [comment]
@BillyONeal do you want to merge this?

**Comment by BillyONeal** [comment]
@strega-nil-ms Yes XD

**Pull request merged**
