### PR TITLE
Added basic appveyor CI support

### PR DESCRIPTION
**Pull request by Telokis**
Will simply build vcpkg and, then, install each of the libraries available in ports.
Output can be seen [here](https://ci.appveyor.com/project/Ninetainedo/vcpkg)
Fails because cocos2d doesn't have a CONTROL file.

### CODE REVIEW

**Comment by ras0219-msft** [comment]
I think we should parse the output of ".\vcpkg search" to get the list instead of hardcoding it. Additionally, we should remove cocos-2d entirely (for now) since it does not work.

**Comment by Ninetainedo** [comment]
We could parse the output but wouldn't it be better to try installing everything located in ports?
This way we can easily spot ill-registered libraries. (As cocos2d, for instance)

**Comment by Ninetainedo** [comment]
Earlier I tried to ignore failing libraries and I got about one full hour to install every library.
This obviously won't scale well with hundreds of libraries.
The ideal would be to only try installing libraries that have changed. If the portfile.cmake is different, the library is installed. Otherwise, we skip it.

However, I have no idea how to do so efficiently for now. This could probably be done by a PowerShell script based on portfile's MD5 but the script would need a way to update said MD5.

**Comment by ras0219-msft** [comment]
Hmm, yeah. We could run regex against each portfile to select the version number and compare it against either the output of `vcpkg list` or `packages\<xyz>\CONTROL`.

I definitely agree that as the libraries number increases, we need to have a better strategy here. I'm quite impressed it finished in an hour, honestly.

**Comment by Ninetainedo** [comment]
I'm closing this PR and I'll open an issue about testing.

**Pull request closed without merging**
