### PR TITLE
[vcpkg-ci-curl] Add openssl to curl tests

### PR DESCRIPTION
**Pull request by talregev**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [ ] ~SHA512s are updated for each updated download.~
- [ ] ~The "supports" clause reflects platforms that may be fixed by this new version.~
- [ ] ~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~
- [ ] ~Any patches that are no longer applied are deleted from the port's directory.~
- [ ] ~The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.~
- [ ] ~Only one version is added to each modified port's versions file.~

### CODE REVIEW

**Comment by dg0yt** [comment]
NB:

- Until recently, the vcpkg-ci-curl port was ensuring the primary use case: **Single-SSL** curl with the default SSL backend. 
- vcpkg CI always includes the default SSL backend. Since a few weeks, the test is now activating **Multi-SSL** mode, with mbedtls, gnutls, and now openssl, added explicitly.
- The default backend is OpenSSL for "(uwp | !windows) & !(osx | ios) & !mingw".
- Some capabilities are not available with Multi-SSL. In particular: *HTTP3*, which is known to be a desired future port feature.
  https://github.com/curl/curl/blob/88727f7ed048f828e6cf0b2a0981e51e61143c81/CMakeLists.txt#L878-L880
  See also #40219, #37146.

**Comment by talregev** [comment]
openssl port can be with all platform.
we cannot test http3 even if ci test will be single ssl with default ssl, because non of the os have gnutls nor wolfssl as the default ssl. That why when adding http3 feature with default ssl it will be multissl and it will break the build.

The tests is working with multissl feature, when we add them we discovered problems in curl and other ports and we fix them.

As I see how fast the ci was finished, I think openssl already added to all os in the tests.

**Comment by dg0yt** [comment]
> As I see how fast the ci was finished, I think openssl already added to all os in the tests.

Based on what I wrote: It is a default feature for the linux and android triplets. And for windows, it is explicitly pulled in by some ports (`git grep -A5 curl ports/*/vcpkg.json | grep -B5 openssl` for candidates, e.g. `pulsar-client-cpp`.)

**Comment by Cheney-W** [comment]
@vicroms Could you please help review this PR?

**Comment by dg0yt** [comment]
I would like to see the original intent of this port being restored: testing with the default backend and not pulling in additional backends.

The additional backends here are not even guarded by features, so we can no longer use the test port manually for single-backend tests.

**Pull request merged**
