### PR TITLE
[dlib] Fix pc file, cleanup, drop lib suffixes for MSVC

### PR DESCRIPTION
**Pull request by dg0yt**
- #### What does your PR fix?
  Fixes the invalid pc file, cf. https://github.com/microsoft/vcpkg/pull/23898#issuecomment-1085792419.
  Portfile and patch cleanup.
  Drop lib suffixes for MSVC (breaking pc files)

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  unchanged, no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  yes

### CODE REVIEW

**Review by FrankXie05 — APPROVED** [review]

**Comment by dg0yt** [comment]
> Drop lib suffixes for MSVC (breaking pc files)

Please double-check that this change is okay with regard to [Do not rename binaries outside the names given by upstream](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-rename-binaries-outside-the-names-given-by-upstream).
(Upstream seems to be unhappy about the suffixes, too.)
https://github.com/microsoft/vcpkg/pull/25997/files#diff-238da7623555112f8c58a3cf091530432455f49df6f43138bd4f55ee0eb8d4d2R48-R52

**Comment by FrankXie05** [comment]
I will delve into the code and test it locally. :)

**Comment by FrankXie05** [comment]
Add label `info:reviewed` for FTE review. 
About the change of  lib name: 
https://github.com/microsoft/vcpkg/pull/25997#issuecomment-1198870658
````
dlib19.24.0_debug_32bit_msvc1929.lib
dlib19.24.0_release_32bit_msvc1929.lib
````
After change：
````
 debug: dlib.lib
 release: dlib.lib
````

**Comment by BillyONeal** [comment]
> * Drop lib suffixes for MSVC (breaking pc files)

I think this is OK; my understanding is that the rationale for this guideline is to

1. discourage extreme / extensive patching that tends to be necessary when people mess with binary names
2. ensure that linkers, debuggers, etc. don't get confused by things not matching up.

**Comment by BillyONeal** [comment]
Thanks!

**Pull request merged**
