### PR TITLE
[tinyexpr] Add new port

### PR DESCRIPTION
**Pull request by myd7349**
**Describe the pull request**

- What does your PR fix?
Add new port: https://github.com/codeplea/tinyexpr

- Which triplets are supported/not supported? Have you updated the CI baseline?
N/A. No.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes.

### CODE REVIEW

**Review by LilyWangL — APPROVED** [review]

**Comment by LilyWangL** [comment]
Blocked by #13722.

**Review by ras0219 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
