### PR TITLE
[antlr4] Convert CRLF line endings to LF in portfile.cmake

### PR DESCRIPTION
**Pull request by wangtz0607**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [ ] ~SHA512s are updated for each updated download.~
- [ ] ~The "supports" clause reflects platforms that may be fixed by this new version.~
- [ ] ~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~
- [ ] ~Any patches that are no longer applied are deleted from the port's directory.~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by Osyotr** [comment]
Does it change anything?

**Comment by wangtz0607** [comment]
Nothing except for the line endings.

**Comment by MonicaLiu0311** [comment]
Is this end-of-line character bad for you? If not, I recommend modifying it the next time you update the version. Because this will produce a `port-version` but no actual changes...

**Comment by wangtz0607** [comment]
Actually not...I can close the PR if you are not comfortable with it.

**Comment by MonicaLiu0311** [comment]
Anyway, thanks for your contribution.

**Pull request closed without merging**
