### PR TITLE
Add triplets for static libraries with dynamic CRT on Windows

### PR DESCRIPTION
**Pull request by vicroms**
Add new community triplets for static libraries with dynamic CRT linkage on Windows.

### CODE REVIEW

**Comment by strega-nil** [comment]
testing out new CI changes:

/azp run

**Comment by strega-nil** [comment]
/azp run

testing out new CI changes

**Comment by strega-nil** [comment]
Testing out new CI changes

**Review by JackBoosY — APPROVED** [review]

**Review by ras0219-msft — APPROVED** [review]

**Pull request merged**
