### PR TITLE
[pistache] Delete the port.

### PR DESCRIPTION
**Pull request by BillyONeal**
The port "pistache" was only installing its verdored copy of rapidjson, it wasn't actually installing anything related to itself. As a result, if rapidjson was already installed by vcpkg, and the port tried to use the one provided by vcpkg, nothing at all would be installed. There is no evidence that anyone actually used this port. The upstream project does not have proper cmake bindings set up, and it will require substantial modification of their build system to repair.

As a result, this change just deletes the port. It is likely that someone could add it back later in terms of meson, which seems to be the buildsystem preferred upstream.

### CODE REVIEW

**Comment by PhoebeHui** [comment]
Could you please also remove it from https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt#L1217?

**Comment by strega-nil-ms** [comment]
This is probably not the correct solution. We should instead roll back pistache, since pistache itself is not broken, the new version added was broken.

**Comment by strega-nil-ms** [comment]
Closing in favor of #19206

**Comment by BillyONeal** [comment]
> This is probably not the correct solution. We should instead roll back pistache, since pistache itself is not broken, the new version added was broken.

It looks like it was always broken. But if you know how to fix it I agree that's better.

> Closing in favor of #19206

Sounds great!

**Pull request closed without merging**
