### PR TITLE
[imgui]Set imgui as a header-only library.

### PR DESCRIPTION
**Pull request by JackBoosY**
According to imgui official [description](https://github.com/ocornut/imgui#usage):
> The core of Dear ImGui is self-contained within a few platform-agnostic files which you can easily copy and compile into your application/engine. They are all the files in the root folder of the repository (imgui.cpp, imgui.h, imgui_demo.cpp, imgui_draw.cpp etc.).
\
No specific build process is required. You can add the .cpp files to your existing project.

Since most ports that rely on it use it directly from the source code and include `-internal.h`, try changing this port to a header-only port.

Waiting for [#1713](https://github.com/ocornut/imgui/pull/1713) discussion result.

### CODE REVIEW

**Comment by lerppana** [comment]
Hey,

can you show me an example how to link properly (against examples, like vulkan+sdl) with your version of package and how is it better way. In my mind it is better to explicitly fetch version with features (or support) for different pipelines, in which case it also uses depends functionality. Then only thing when compiling is link against imgui::imgui and all symbols are found. 

Now when I use your branch, I´m getting a lot of lnk2019, because cpp files for examples are not found. What is the intended way of using this header-only library when linking against example pipelines?

**Comment by JackBoosY** [comment]
@lerppana Please see my comments below.
Since the port is explicitly declared as a header-only library, I think it is better to use the include method.
And This PR is still wip, I need more work to fix its compatibility.

**Comment by lerppana** [comment]
I closed my PR in favour of this one, can you also update imgui version with this PR

**Comment by PhoebeHui** [comment]
@JackBoosY, could you resolve the conflicts?

**Pull request closed without merging**
