### PR TITLE
[urho3d, xcb-util-wm] Hash fixes

### PR DESCRIPTION
**Pull request by BillyONeal**
All these problems were detected in https://dev.azure.com/vcpkg/public/_build/results?buildId=84431 because the SAS token to our asset cache expired 😳

[Urho3D] Fix download hash.

The change appears to be changing some of the cases of filenames from uppercase to lowercase; possibly in response to one of the CVEs in Git when applied to case-insensitive filesystems.

[xcb-util-wm] Correct the download hash.

That SHA512 is for 24eb17df2e1245885e72c9d4bbb0a0f69f0700f2, which was 0.4.1, not 0c6681e465c9cc7b1fbb60778ba1eaa61ab01a14 which is 0.4.2.

This was probably just done wrong originally in https://github.com/microsoft/vcpkg/pull/27240

### CODE REVIEW

**Comment by lamarrr** [comment]
I see the patch failed. I suppose it’s quite different.
Please give me some time to submit a patch for v0.0.2 instead.

**Comment by JonLiu1993** [comment]
It looks like the patch application for the stx port failed:
````
CMake Error at scripts/cmake/z_vcpkg_apply_patches.cmake:34 (message):
  Applying patch failed: Checking patch CMakeLists.txt...

  error: while searching for:

  # ===============================================?

  ?

  if(STX_ENABLE_BACKTRACE)?

    if(NOT EXISTS third_party/abseil)?
      execute_process(?
        COMMAND git submodule update --init --recursive third_party/abseil?
        WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR})?
    endif()?
    add_subdirectory(third_party/abseil)?

  endif()?

  ?

  # the atomics library doesn't automatically link on my Android phone?

  

  error: patch failed: CMakeLists.txt:204

  error: CMakeLists.txt: patch does not apply

Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive.cmake:153 (z_vcpkg_apply_patches)
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:8 (vcpkg_extract_source_archive)
  scripts/cmake/vcpkg_from_github.cmake:113 (vcpkg_extract_source_archive_ex)
  ports/stx/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:147 (include)
````

**Comment by lamarrr** [comment]
I've updated the port https://github.com/microsoft/vcpkg/pull/29392

**Comment by JonLiu1993** [comment]
Depends on PR #29392

**Comment by JonLiu1993** [comment]
> I've updated the port #29392

@lamarrr, Thanks for your contribution. This PR https://github.com/microsoft/vcpkg/pull/29383 has already updated stx, we don’t need to submit an additional PR to update this port, I will merge your PR changes into Billy’s PR, thanks again for your contribution.

**Comment by BillyONeal** [comment]
> @lamarrr, Thanks for your contribution. This PR #29383 has already updated stx, we don’t need to submit an additional PR to update this port, I will merge your PR changes into Billy’s PR, thanks again.

I reverted my changes since they did not work in this PR.

**Pull request merged**
