### PR TITLE
[rtmidi] Add support for ALSA

### PR DESCRIPTION
**Pull request by joe-noel-dev**
The port description references ALSA, but it was turned off in the port CMake file. Since it is reasonable to expect it to be installed on a Linux distribution, all that is required is the feature to turn on the flag.

### CODE REVIEW

**Comment by Hoikas** [comment]
This already defaults to `ON` upstream: https://github.com/thestk/rtmidi/blob/cc887191c3b4cb6697aeba5536d9f4eb423090aa/CMakeLists.txt#L39

**Comment by joefocusrite** [comment]
@Hoikas 

Ah yes! is it better to remove the ` OPTIONS -DRTMIDI_API_ALSA=OFF` altogether then? This would mean that the port is not backwards compatible and the flag will be turned on for some users.

**Comment by Hoikas** [comment]
Ugh, when I first read the diff, I didn't see that the portfile was turning it off. I assumed "but it was turned off in the port CMake file" meant the upstream CMakeLists.txt :neutral_face:.

It looks like ASLA was disabled in [this commit](https://github.com/microsoft/vcpkg/pull/9221/commits/02d33429253938d14b67a2e23bd66711ac3b6c3a), but I have no idea why. IMO, it would make sense to turn ALSA OFF only if `VCPKG_TARGET_IS_LINUX` is false, since upstream is just testing for non-Apple UNIXy OSes. That's similar to what the openal-soft port is [doing](https://github.com/microsoft/vcpkg/blob/master/ports/openal-soft/portfile.cmake#L44).

**Review by ytbigvinny27 — APPROVED** [review]

**Review by ytbigvinny27 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
@joefocusrite 

The feature `alsa ` build failed on x64-linux on my machine with the following errors:

config-x64-linux-dbg-err.log
```
CMake Error at CMakeLists.txt:118 (message):
  ALSA API requested but no ALSA dev libraries found
```
config-x64-linux-dbg-out.log
```
-- The CXX compiler identification is GNU 10.1.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Checking for module 'jack'
--   No package 'jack' found
-- Could NOT find ALSA (missing: ALSA_LIBRARY ALSA_INCLUDE_DIR)
-- Configuring incomplete, errors occurred!

```
Does it work on your machine?

**Comment by PhoebeHui** [comment]
@joefocusrite, the feature also test failed with x64-windows, could you please take a look?

```
-- Could NOT find ALSA (missing: ALSA_LIBRARY ALSA_INCLUDE_DIR) 
CMake Error at CMakeLists.txt:118 (message):
  ALSA API requested but no ALSA dev libraries found
```

**Comment by joefocusrite** [comment]
@PhoebeHui @NancyLi1013 It was missing the OPTIONS keyword 🤦🏼 

Regarding @Hoikas [comment](https://github.com/microsoft/vcpkg/pull/17159#issuecomment-816357173). I'm happy to make it default ALSA on for Linux, or keep it as it is right now for backwards compatibility. Either way 🙂 .

**Comment by NancyLi1013** [comment]
The same error as before on x64-linux. Seems `alsa `still cannot be found. 
After install `libasound2-dev` via `apt-get install libasound2-dev`, it can be built successfully.

See the reference https://askubuntu.com/questions/1281211/no-package-alsa-found-in-ubuntu-18-04

I agree with the suggestion from @Hoikas, since upstream also set `RTMIDI_API_ALSA `as on in Linux.

https://github.com/thestk/rtmidi/blob/master/CMakeLists.txt#L38-L40
```
    if(UNIX AND NOT APPLE)
      option(RTMIDI_API_ALSA "Compile with ALSA support." ON)
    endif()
```

**Comment by joefocusrite** [comment]
@NancyLi1013 That makes sense. Would that be instead of the vcpkg feature or as well as the feature?

**Comment by NancyLi1013** [comment]
> @NancyLi1013 That makes sense. Would that be instead of the vcpkg feature or as well as the feature?

Sorry, I'm not clear what you mean. But I think you need to do these changes in this PR.

Seems `alsa `only supports Linux. So we should add `platform: linux` to feature `alsa`. Also it would be better to add a message to remind users to install `libasound2`. Otherwise, it cannot be built.

**Comment by PhoebeHui** [comment]
The 'platform' filed doesn't work with 'feature'. So the following message should be added:
1. The feature only works on linux.
2. It requires additional system package 'libasound2-dev' on linux.

@joefocusrite, could you address above suggestions?

**Comment by PhoebeHui** [comment]
Pinging @joefocusrite for response. Is work still being done for this PR?

**Comment by JonLiu1993** [comment]
@joefocusrite ,I’m going to close this PR because it’s been a long time since any update has been made. If this is something you’d like to see merged and work is being done, please reopen.

**Pull request closed without merging**
