### PR TITLE
[python3] Update to 3.11.8

### LINKED ISSUE #36736: python3 add version 3.11.8
### Library name

python3

### New version number

3.11.8

### Other information that may be useful (release notes, etc...)

For those of us using Python 3.11, it would be nice to use the latest version.
https://www.python.org/downloads/release/python-3118/

### PR DESCRIPTION
**Pull request by Osyotr**
Fixes #36736

Changes: https://github.com/python/cpython/compare/v3.11.5...v3.11.8

### CODE REVIEW

**Comment by Osyotr** [comment]
Both `gmp` and `xcb-util-errors` are CI baseline regressions (#36706).

**Comment by yurybura** [comment]
Why not [Python 3.12.2](https://www.python.org/downloads/release/python-3122/)?

**Comment by Neumann-A** [comment]
probably because 3.12 drops distutils which might break downstream users.

**Comment by Osyotr** [comment]
It also requires autoconf 2.71 and some distros have only 2.69. We probably need `vcpkg-tool-autoconf`.

**Comment by MonicaLiu0311** [comment]
All features are tested successfully in the following triplet:
```
x86-windows
x64-windows
x64-windows-static
```

**Review by MonicaLiu0311 — APPROVED** [review]

**Pull request merged**
