### PR TITLE
FIX: pthreads: also install "pthreads.lib"

### PR DESCRIPTION
**Pull request by ghost**
The current pthreads port installed a library file with a name that other projects don't automatically pick up. This adds a new library file with the standard pthreads name, but preserves backward compatibility for other ports that already have a dependency on this project.

### CODE REVIEW

**Comment by xoviat** [comment]
Okay, confirmed working on appveyor.

**Comment by atkawa7** [comment]
@xoviat @ras0219  This is a regression. Pthreads on windows should be `pthreadVC2`. You might have to patch `ardlib`

See ftp://sourceware.org/pub/pthreads-win32/dll-latest/lib/x64/
and https://www.sourceware.org/pthreads-win32/

**Comment by xoviat** [comment]
A regression removes existing functionally. This doesn't.

**Comment by atkawa7** [comment]
@xoviat I am not sure  you understand what I mean. There is currently a pthreads  port in the repo which depends on the library being name `pthreadvc2.lib`. But you are changing it to `pthreads.lib` which means any project that depends on the library being `pthreadvc2.lib` will fail.

**Comment by xoviat** [comment]
I am copying the file not moving it.

**Comment by atkawa7** [comment]
@xoviat I do not  know if this is copying 

https://github.com/xoviat/vcpkg/blob/dd56066e291545e6885cecb06ef29d6474824fc3/ports/pthreads/portfile.cmake#L35-L39

**Comment by xoviat** [comment]
That's from dd56066. The latest changeset is 4259fc1. Github clearly shows that I made 4259fc1 before you commented initially.

**Comment by xoviat** [comment]
Is this some kind of game? Are you seeing this?

image

**Comment by xoviat** [comment]
I even explained all of this in the first post

> **but preserves backward compatibility for other ports that already have a dependency on this project.**

**Comment by atkawa7** [comment]
@xoviat  I see. Thanks for clarifying.

**Comment by xoviat** [comment]
I'm sorry about the harsh tone if it disturbed you.

**Comment by atkawa7** [comment]
@xoviat No worries

**Comment by ras0219-msft** [comment]
Thanks for sorting that out!

> Pthreads on windows should be pthreadVC2. You might have to patch ardlib
See ftp://sourceware.org/pub/pthreads-win32/dll-latest/lib/x64/
and https://www.sourceware.org/pthreads-win32/

`pthreadVC2` does appear to be the official name for the library on windows; I'd honestly feel better about patching `ardlib` to search for both names than providing it under a nonstandard name (even if it's just an alias). We want to support standards, not replace them!

However, if this would be a common occurrence, I agree that providing an "alias" is the best option. In this case, the alias should be placed under `lib\manual-link\` in order to avoid interfering with our MSBuild integration. That folder will still be added to link search paths, so it will still be findable via `find_library()`.

**Comment by xoviat** [comment]
So I looked at why the names are different and I think I found the answer. The existing `pthreads` is coming from https://www.sourceware.org/pthreads-win32/ but my pthreads is coming from https://github.com/BrianGladman/pthreads. It also seems like my version may be newer.

Given that, and given that `pthreadsVC2` is not a standard name that scripts can pick up (most build systems simply remove "lib" from the linux library name to get the windows library name), I don't personally agree with the default name. But I can provide the alias if it allows the PR to be merged.

**Comment by xoviat** [comment]
@ras0219-msft Done.

**Comment by ras0219-msft** [comment]
Thanks for fixing that!

As an aside, from the README at https://github.com/BrianGladman/pthreads:
> Because the library is being built using various exception
handling schemes and compilers - and because the library
may not work reliably if these are mixed in an application,
each different version of the library has it's own name.
...
Examples:
	pthreadVSE.dll	(MSVC/SEH)
	pthreadGCE.dll	(GNUC/C++ EH)
	pthreadGC.dll	(GNUC/not dependent on exceptions)
	pthreadVC1.dll	(MSVC/not dependent on exceptions - not binary compatible with pthreadVC.dll)
	pthreadVC2.dll	(MSVC/not dependent on exceptions - not binary compatible with pthreadVC1.dll or pthreadVC.dll)

**Comment by xoviat** [comment]
Yes, but if you look [here](https://github.com/BrianGladman/pthreads/blob/master/build.vc14/pthreads_lib/pthreads_lib.vcxproj), the target is "pthreads." So there was a mistake somewhere.

**Pull request merged**
