### PR TITLE
[vcpkg_check_features] Add ${FEATURE_OPTION} to the parent scope to use it in portfile.cmake

### PR DESCRIPTION
**Pull request by JackBoosY**
When using `vcpkg_check_features`, the parameters of the features are added to `${OUT_FEATURE_OPTIONS}`, so we can only use ` "feature_name" IN_LIST FEATURES` to determine whether the feature is enabled.
In order to simplify the judgment conditions, add `${FEATURE_OPTION}` to the parent scope for developers to use.

### CODE REVIEW

**Comment by Neumann-A** [comment]
Wasn't this an explicit design feature to not do that? https://github.com/microsoft/vcpkg/pull/9196#issuecomment-561405505

Maybe instead of generally exporting those variables maybe make it an OPTIONAL feature of the function?

**Comment by JackBoosY** [comment]
@Neumann-A Yes, but I prefer to open a PR to discuss its feasibility.

**Comment by PhoebeHui** [comment]
For me, I am mostly concerned about the thing that Cent said in https://github.com/microsoft/vcpkg/pull/9196#issuecomment-561329095, since 'Not exporting the macros was a design decision', I tend to close this PR now, @JackBoosY, feel free to reopen it if you stick to it.

**Pull request closed without merging**
