### PR TITLE
Upgrade crc32c to 1.0.6.

### PR DESCRIPTION
**Pull request by coryan**
This version supports both static and shared libraries, yay!

### CODE REVIEW

**Comment by Rastaban** [comment]
I am seeing failures on windows when building dynamic triplets

```
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: E:/vcpkg/vcpkg/packages/crc32c_x64-windows/share/crc32c/copyright
-- Performing post-build validation
Import libs were not present in E:\vcpkg\vcpkg\packages\crc32c_x64-windows\debug\lib
If this is intended, add the following line in the portfile:
    SET(VCPKG_POLICY_DLLS_WITHOUT_LIBS enabled)
Import libs were not present in E:\vcpkg\vcpkg\packages\crc32c_x64-windows\lib
If this is intended, add the following line in the portfile:
    SET(VCPKG_POLICY_DLLS_WITHOUT_LIBS enabled)
The following DLLs have no exports:

    E:/vcpkg/vcpkg/packages/crc32c_x64-windows/debug/bin/crc32c.dll
    E:/vcpkg/vcpkg/packages/crc32c_x64-windows/bin/crc32c.dll

DLLs without any exports are likely a bug in the build script.
There should be no empty directories in E:/vcpkg/vcpkg/packages/crc32c_x64-windows
The following empty directories were found:

    E:/vcpkg/vcpkg/packages/crc32c_x64-windows/debug/lib
    E:/vcpkg/vcpkg/packages/crc32c_x64-windows/lib

If a directory should be populated but is not, this might indicate an error in the portfile.
If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:

    file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/a/dir ${CURRENT_PACKAGES_DIR}/some/other/dir)
```

@coryan are you able to look at these?

**Comment by coryan** [comment]
Sadness.  Would it be Okay to define `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` [[1]](https://cmake.org/cmake/help/v3.13/variable/CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS.html#variable:CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS)] There are only a handful of functions in this library.

If not, then I should revert the change to enable shared objects and submit patches to the library.

**Comment by KindDragon** [comment]
You can patch CMakeLists.txt with `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` like here https://github.com/Microsoft/vcpkg/blob/7d72108b9a09e92342ff695c074766fb068049df/ports/nlopt/0001_export_symbols.patch

**Comment by coryan** [comment]
@KindDragon Thanks!  That works for me on both Windows and Linux (did not test macOS, but looks safe).

**Pull request merged**
