### PR TITLE
[reproc] update to 14.2.1

### LINKED ISSUE #15747: [reproc] update to 14.2.1
Library name: reproc

New version number: 14.2.1

Other information that may be useful (release notes, etc...)
Adds pid support:
https://github.com/DaanDeMeyer/reproc/releases/tag/v14.2.1

### PR DESCRIPTION
**Pull request by JonLiu1993**
Fix #15747

Update reproc to the latest version 14.2.1

Note: No feature need to tested

### CODE REVIEW

**Comment by cmaughan** [comment]
Why 14.2.0 and not 14.2.1 ? Is that a policy decision for vcpkg?  I don't need the .1, but it looks like it has useful fixes.

**Comment by cmaughan** [comment]
Ah, it looks like you are calling it 14.2.0 when it is the SHA for 14.2.1?

**Comment by JonLiu1993** [comment]
> Ah, it looks like you are calling it 14.2.0 when it is the SHA for 14.2.1?

Sorry, this hash value is 14.2.1, I wrote the wrong version number, it should be 14.2.1

**Comment by ras0219-msft** [comment]
Thanks!

**Pull request merged**
