### PR TITLE
[baseline][colmap] Fix find dependency freeimage

### PR DESCRIPTION
**Pull request by JackBoosY**
The default find method only find the release version of freeimage.

Related: #15860.

### CODE REVIEW

**Review by NancyLi1013 — APPROVED** [review]

**Comment by Neumann-A** [comment]
you might also want to pass `GMP_LIBRARY=<somepath>/gmpd.lib` via `OPTIONS_DEBUG` so that GMP in debug gets linked (Could be a windows only detail).
Small tip to analyse build logs: search|grep for `installed/<triplet>/debug/lib` in release builds and `installed/<triplet>/lib` in debug builds to discover wrong lib linkage.

**Comment by JackBoosY** [comment]
@Neumann-A  I think the dependency cgal cannot be built successfully. 
Because cgal depends on mpfr and mpir, while mpfr depends on gmp, and there is a conflict between gmp and mpir. 
So we can ignore this point for now.

**Comment by Neumann-A** [comment]
@JackBoosY If you look into CGAL you actually see a `FindGMP`. mpir is just mentioned there in a find_library call as a gmp replacement. That is why #15860 switches the dependency mpir to gmp. The problem is that that find_library call is not configuration aware there and always links the release lib of gmp since the debug version has a debug suffix (gmpd).

**Comment by JackBoosY** [comment]
@Neumann-A  Yep, but I can't test it in the master branch, so I suggest fix this after your PR merge.

**Comment by JackBoosY** [comment]
Ping @dan-shaw for merge this PR quickly. Some PRs require this PR.

**Pull request merged**
