### PR TITLE
[log4cxx] Update to 0.12.0

### LINKED ISSUE #19730: [log4cxx] failure to compile application with clang on Windows/VC2019
We have an application that uses log4cxx.
When I compile with clang on Windows VC2019 I observe the following error:
_[...]
  In file included from C:\vcpkg\installed\x64-windows\include\log4cxx/logger.h:30:
  In file included from C:\vcpkg\installed\x64-windows\include\log4cxx/helpers/appenderattachableimpl.h:27:
  In file included from C:\vcpkg\installed\x64-windows\include\log4cxx/spi/appenderattachable.h:30:
C:\vcpkg\installed\x64-windows\include\log4cxx\appender.h(140,1): error : explicit instantiation of 'allocator' not in a namespace enclosing 'std'
  LOG4CXX_LIST_DEF(AppenderList, AppenderPtr);
  ^
  C:\vcpkg\installed\x64-windows\include\log4cxx\log4cxx.h(91,45): note: expanded from macro 'LOG4CXX_LIST_DEF'
                  extern template class LOG4CXX_EXPORT std::allocator<T>; \
                                                            ^
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.27.29110\include\iosfwd(167,7): note: explicit instantiation refers here
  class allocator;
        ^_

I found this error appears because clang compiler included with Visual Studio has _MSC_VER macro defined.
(Intel icx compiler also has _MSC_VER macro defined on Windows)

The simple fix worked for me for both compilers:
(log4cxx.h, line 81)
`#elif` defined(_MSC_VER) __&& !defined(\_\_clang\_\_)__ && !defined(LOG4CXX_STATIC)

I didn't try to compile with LOG4CXX_STATIC defined, though.

Please apply this fix to github log4cxx sources.

### LINKED ISSUE #19914: [log4cxx] update to 0.12.0
Library name: log4cxx

New version number: 0.12.0

Other information that may be useful (release notes, etc...)
Release notes: https://logging.apache.org/log4cxx/latest_stable/changelog.html
Download information: https://logging.apache.org/log4cxx/latest_stable/download.html

### PR DESCRIPTION
**Pull request by JackBoosY**
Update to 0.12.0 and re-generate patches.

Fixes #19914 maybe fix #19730.

### CODE REVIEW

**Comment by JackBoosY** [comment]
Hi @SergeiDelov, does this update fix your issue?

**Comment by JackBoosY** [comment]
@strega-nil-ms Do you know why the gz file extract failed?
```
  1 CMake Error: Problem with archive_read_next_header(): Pathname can't be converted from UTF-8 to current locale.
  2 CMake Error: Problem extracting tar: /Users/vcpkg/Documents/vcpkg/downloads/apache-log4cxx-0.12.0.tar.gz
```

**Comment by strega-nil-ms** [comment]
@JackBoosY I have no idea... I guess it's because the tarball has a non-ASCII pathname, but that should be supported...

**Comment by rm5248** [comment]
If the problem is with files under src/test/resources/output, those can be ignored - that folder was incorrectly added to the distribution.  Those files are output data from the unit tests.

**Comment by JackBoosY** [comment]
Use command `tar xzvf` result: pass.

**Comment by JackBoosY** [comment]
Maybe related to these file:
_src\test\resources\output\dom³_
_src\test\resources\output\dom㆕_
_src\test\resources\output\PaxHeader\dom³_
_src\test\resources\output\PaxHeader\dom㆕_

**Comment by strega-nil-ms** [comment]
@JackBoosY yeah, the issue is that the locale is set to `"C"`, which is apparently not treated as utf-8; the fix here is to fix the CI, since we can't in general set the locale to a utf-8 locale.

**Review by NancyLi1013 — APPROVED** [review]

**Pull request merged**
