### PR TITLE
[vcpkg docs] Fix broken url of SPDX license

### PR DESCRIPTION
**Pull request by LilyWangLL**
**Describe the pull request**

- #### What does your PR fix?
  Fix broken URL of SPDX license.

### CODE REVIEW

**Review by Cheney-W — APPROVED** [review]

**Comment by LilyWangLL** [comment]
@BillyONeal 
Since I just modified the document file, it does not affect port install. So I canceled the CI pipeline run for not occupied the ci resources.
I am not sure if this will block this PR be merged, could you please help confirm? If yes, I will rerun the CI pipeline run of this PR.

**Comment by BillyONeal** [comment]
Thank you for trying to save CR resources! The fleet caught up so I pushed a master merge and will merge if that comes back OK. (Because there are no edited ports it should be fast)

**Comment by dg0yt** [comment]
Well, the doc update doesn't really consume CI resources, except for a slot in a long queue at the entrance door :laughing:

**Pull request merged**
