### PR TITLE
Fix osx baseline build failures

### PR DESCRIPTION
**Pull request by JackBoosY**
- [x] xerces-c: update ref and sha512
- [x] sfml: fake error
- [x] boost-signals: fake error
- [x] tmxparser: fake error
- [x] soil2: switch repo to github
- [x] pcl: fake error
- [x] gtest: fake error

### CODE REVIEW

**Review by PhoebeHui — APPROVED** [review]
LGTM

**Comment by PhoebeHui** [comment]
@vicroms, please priory to review and merge this PR, it blocks many PRs on OSX, thanks!

**Comment by PhoebeHui** [comment]
Please ignore my above comments, it looks these issue solved on OSX CI testing, I will rerun related PRs.

**Comment by jwillemsen** [comment]
Any plans to merge this PR? All checks are ok, the changes are required for other PRs that now have all kinds of OSX failures

**Comment by ubsan** [comment]
thanks @JackBoosY 😄

**Pull request merged**
