### PR TITLE
[protobuf] Update to version 3.19.3

### LINKED ISSUE #21365: [protobuf] update to 3.19.1
Library name: protobuf

New version number: 3.19.1

Other information that may be useful (release notes, etc...)
https://github.com/protocolbuffers/protobuf/releases/tag/v3.19.1

### PR DESCRIPTION
**Pull request by LilyWangLL**
**Describe the pull request**

- #### What does your PR fix?  
  Fixes #21365, update **protobuf** to version 3.19.1.

1. Due to issue#https://github.com/microsoft/vcpkg/issues/19818, using `vcpkg_cmake_configure` will produce build error on triplet UWP, so I still use `vcpkg_configure_cmake`.

    ```
    -- Building x64-uwp-rel
    CMake Warning at scripts/cmake/vcpkg_copy_pdbs.cmake:70 (message):
      Could not find a matching pdb file for:
    
          E:/vcpkg/packages/protobuf_x64-uwp/bin/libprotobuf-lite.dll
          E:/vcpkg/packages/protobuf_x64-uwp/bin/libprotobuf.dll
    ```

2. There are message in _Source/cmake/CMakeLists.txt_ L187 as below, this port doesn't support triplet `x64-windows-static-md`
    ```
    # In case we are building static libraries, link also the runtime library statically
    # so that MSVCR*.DLL is not required at runtime.
    # https://msdn.microsoft.com/en-us/library/2kzt1wy3.aspx
    # This is achieved by replacing msvc option /MD with /MT and /MDd with /MTd
    # http://www.cmake.org/Wiki/CMake_FAQ#How_can_I_build_my_MSVC_application_with_a_static_runtime.3F
    ```
3. Due to patch `fix-uwp-build.patch` has been merged into source, so remove this patch.
- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  <Yes>

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by LilyWangLL** [comment]
Now `brpc` build failed with the latest version of `protobuf`, the upstream PR https://github.com/apache/incubator-brpc/pull/1657 will fix it. Waiting upstream PR merged, I will sync the new change of `brpc` to VCPKG.

**Comment by LilyWangLL** [comment]
`brpc` build error fix in PR #22685.

**Comment by LilyWangLL** [comment]
Closing this PR since my fork is broken, I will fix this issue in another PR.

**Pull request closed without merging**
