### PR TITLE
Add port anyrpc

### PR DESCRIPTION
**Pull request by faaxm**
This PR adds a port for AnyRPC (https://github.com/sgieseking/anyrpc). This library provides clients and servers for multiple remote procedure call protocols.

### CODE REVIEW

**Comment by dan-shaw** [comment]
Thanks for the PR! On the arm CI builds, it has an error:

`Unknown machine endianess detected. User needs to define ANYRPC_ENDIAN.`

**Comment by faaxm** [comment]
@dan-shaw Sorry for the late reply, I didn't find time to look into this earlier... Is there a way to retrigger the build and get some more information? It seems like the logs are no longer available...

**Comment by faaxm** [comment]
@dan-shaw Found a way to patch anyrpc to know the endianness for ARM when built via VS.
I am not supper happy with this as I had to assume that compiling for ARM with visual studio is always for a little-endian ARM-platform, but to my knowledge that should be valid...

Do you know more about this?

Will eventually submit this patch to the anyrpc-repo....

**Comment by dan-shaw** [comment]
@faaxm Sorry for the delay. I believe compiling for ARM is always in little-endian on Windows. Other than that, the PR looks good. I will squash the commits then merge it - thanks for the PR!

**Pull request merged**
