### PR TITLE
[eve] update to 2023.2.15

### PR DESCRIPTION
**Pull request by jfalcou**
- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [X] SHA512s are updated for each updated download
- [X] The "supports" clause reflects platforms that may be fixed by this new version
- [X] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [X] Any patches that are no longer applied are deleted from the port's directory.
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by jimwang118** [comment]
The installation is successful, but the following error occurs when referencing the header file.
```
/data/test/test.cpp:2:10: fatal error: eve-2023.2.15/eve/as.hpp: No such file or directory
 #include <eve-2023.2.15/eve/as.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/testeve.dir/build.make:76: CMakeFiles/testeve.dir/test.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/testeve.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

```
May I ask if the path of the header file I quoted is wrong? What should be the correct citation?

**Comment by jfalcou** [comment]
Ok so this may comes from the fact the gît ref is actually 2023.02.15.

Can you try  `#include <eve-2023.02.15/eve/as.hpp>` ?

This is something I may need to fix properly.

**Comment by jfalcou** [comment]
Well, actually no.
My local install gives me that:

```
falcou (update/eve) vcpkg $ ls packages/eve_x64-linux/
BUILD_INFO  CONTROL     include/    share/      

falcou (update/eve) vcpkg $ ls packages/eve_x64-linux/include/eve-2023.2.15/eve/
arch      as.hpp      concept          detail   forward.hpp  memory      module       std.hpp  traits.hpp   wide.hpp
arch.hpp  assert.hpp  conditional.hpp  eve.hpp  logical.hpp  memory.hpp  pattern.hpp  traits   version.hpp
```

So maybe you just need to do `#include <eve/as.hpp>`  as I would expect the version folder to be picked up by CMake ?

**Comment by jimwang118** [comment]
> Well, actually no. My local install gives me that:
> 
> ```
> falcou (update/eve) vcpkg $ ls packages/eve_x64-linux/
> BUILD_INFO  CONTROL     include/    share/      
> 
> falcou (update/eve) vcpkg $ ls packages/eve_x64-linux/include/eve-2023.2.15/eve/
> arch      as.hpp      concept          detail   forward.hpp  memory      module       std.hpp  traits.hpp   wide.hpp
> arch.hpp  assert.hpp  conditional.hpp  eve.hpp  logical.hpp  memory.hpp  pattern.hpp  traits   version.hpp
> ```
> 
> So maybe you just need to do `#include <eve/as.hpp>` as I would expect the version folder to be picked up by CMake ?

Ok, this usage is correct and my local test is fine, thank you very much.

**Comment by jimwang118** [comment]
The usage has been tested successfully locally. 
```
find_package(eve CONFIG REQUIRED)
target_link_libraries(main PRIVATE eve::eve)
```

**Pull request merged**
