### PR TITLE
[gdk-pixbuf] Fix Linux compilation.

### PR DESCRIPTION
**Pull request by Kwizatz**
Unlike #6625 this version contains the minimal changes required
to keep other dependencies as untouched as possible.

### CODE REVIEW

**Comment by NancyLi1013** [comment]
Hi @Kwizatz, thanks for your PR. Could you also bump the version in CONTROL file?

**Comment by Kwizatz** [comment]
@NancyLi1013 Done, I also bumped glib and libcroco's version since they also got small changes.

**Comment by Kwizatz** [comment]
So, I don't see any issues when building gdk-pixbuf on Linux or Windows, so I think the problem may be some other library being affected as a side effect, but I don't know what that could be.

**Comment by Rastaban** [comment]
It looks like qt5-imageformats:x64-windows is failing, although it is not obvious to me what the dependency is between that port and the ones you changed in this PR.

**Comment by Kwizatz** [comment]
Thanks! I'll take a look.

**Comment by Rastaban** [comment]
I am unable to reproduce the failure locally so I am rerunning the tests.  It is possible this is an unrelated failure due to other ports not behaving in the CI tests.  If that is the case it should be investigated separately so it does not hold up this PR.  We will see what the test results are when it finishes.

**Comment by Kwizatz** [comment]
Got the same results, qt5-imageformats:x64-windows built successfully locally. I'll await your results.

**Comment by Rastaban** [comment]
The tests are now passing with the rerun.

**Pull request merged**
