### PR TITLE
[vcpkg-scripts] Pass native install dir to nmake

### PR DESCRIPTION
**Pull request by dg0yt**
- #### What does your PR fix?  
  Makes `vcpkg_build_nmake` pass `INSTALLDIR` as native windows path. CMake paths use `/` separators which don't work for `mkdir`, `copy` etc.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  windows, no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  yes

### CODE REVIEW

**Comment by dg0yt** [comment]
TBH I don't even know which port uses the `INSTALLDIR` macro. Is this a `nmake` convention? Only few ports use `vcpkg_build_nmake` at the moment. Those that I touched (related to GIS) need `INSTDIR`. The next step is to add an option to name the variable...

**Comment by Neumann-A** [comment]
qmake also generates Makefiles for nmake on windows. `vcpkg_build_qmake` uses jom instead of nmake.

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
LGTM.

**Comment by BillyONeal** [comment]
Thanks for the fix!

**Pull request merged**
