### PR TITLE
[vcpkg] vcpkg_pkgconfig helper function

### PR DESCRIPTION
**Pull request by Matioupi**
This PR adds a new helper function : vcpkg_pkgconfig in order to easily retrieve the pkgconfig link information from installed packages.
I found that it helps fixing some ports when building tool feature in static configurations.
I also added wldap32 and crypt32 to VCPKG_SYSTEM_LIBRARIES for windows target. I don't know if there is a rationale for not having them there by default.

Some issues e.g. https://github.com/microsoft/vcpkg/issues/2662 seems to request such function and I had the same feeling.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

It should, also I have not seen much regarding PR that are not about ports.

### CODE REVIEW

**Comment by JackBoosY** [comment]
cc @Neumann-A for review this PR.

**Comment by Neumann-A** [comment]
Should probably use the functions defined in the FindPkgConfig module https://cmake.org/cmake/help/v3.19/module/FindPkgConfig.html

But I am missing an application for this within VCPKG. In general the build scripts of a port need to correctly discover dependencies not the portfiles.

**Comment by Matioupi** [comment]
I'll try to modify and use the FindPkgConfig function instead of what I've tried.
As for the use case, I agree that  the build scripts should be responsible in first place, but I found cases where building tools with static configuration triplets would fail.
On example I have it the build of proj 7.1.1 (which is also a PR I authored : https://github.com/microsoft/vcpkg/pull/14143)
When building this package with x64-windows-static, and utilities enabled, then build fail in some cases (e.g. when curl is built with additional features) and the failure is a link stage because the additional link libraries associated to curl features are not added to linker.
I understand it may be considered (and probably is) a dirty fix, but adding those libs thought the VCPKG_LINKER_FLAGS_RELEASE/DEBUG variable at port file level provides an easy way to get around this.
the helper function I proposed was developed in that exact use case frame.

**Comment by Matioupi** [comment]
I see now that the FindPkgConfig in addition to finding the executable path also has a pkg_get_variable that probably deprecates the need for this PR...

**Pull request closed without merging**
