### PR TITLE
[podofo] Change to github and update version to 0.10.0

### LINKED ISSUE #31578: [podofo] update to 0.10.0
### Library name

podofo

### New version number

0.10.0

### Other information that may be useful (release notes, etc...)

current version 0.9.8
0.10.0 is not compatible with 0.9.8

### PR DESCRIPTION
**Pull request by FrankXie05**
Fix https://github.com/microsoft/vcpkg/issues/31578

Note: Changed to [`GitHub`](https://github.com/podofo/podofo/tree/0.10.0) because upstream indicates that it has been transferred to `github` for development.
https://sourceforge.net/projects/podofo/
```
Development of PoDoFo has been moved to GitHub: https://github.com/podofo/podofo
```

However, the `api` has undergone major changes in version `0.10.0`. 
We need to perform compatibility tests for downstream.
https://github.com/podofo/podofo/wiki/PoDoFo-API-migration-guide/#098---0100
https://github.com/podofo/podofo#api-migration

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by FrankXie05** [comment]
@playgithub Has been passed the CI checking, could you please test the latest version api ?

**Comment by dg0yt** [comment]
> We need to perform compatibility tests for downstream.

No. There is not a single port using it.

**Comment by FrankXie05** [comment]
It has been verified that the change of the `api` will carry over to the next version. But this port will not affect `vcpkg`.

**Comment by FrankXie05** [comment]
The usage(Including `static` and `dynamic`) has been tested successfully locally.
```
find_package(PoDoFo CONFIG REQUIRED)
```
```
target_link_libraries(main PRIVATE podofo_shared)
Or
target_link_libraries(main PRIVATE podofo_static podofo_private)
```
Waiting for feature `fontconfig` testing.

**Comment by dg0yt** [comment]
> target_link_libraries(main PRIVATE podofo_static podofo_private)

Private is public, really?
Well, it is unofficial, anyways.

**Comment by FrankXie05** [comment]
@dg0yt 
```
if(PODOFO_BUILD_SHARED)
    export(TARGETS podofo_shared FILE "${PROJECT_BINARY_DIR}/podofoConfig.cmake")
else()
    export(TARGETS podofo_static podofo_private FILE "${PROJECT_BINARY_DIR}/podofoConfig.cmake")
endif()
```
No, it's official. I just changed the location of the export.

**Comment by FrankXie05** [comment]
The feature `fontconfig` is tested successfully in the following triplet:

- x86-windows
- x64-windows
- x64-windows-stataic

**Comment by dg0yt** [comment]
> No, it's official. I just changed the location of the export.

No, it is not official. The patch adds the export and the installation of the exported config. The keyword `EXPORT` isn't used upstream: https://github.com/podofo/podofo/blob/0.10.0/src/podofo/CMakeLists.txt.

**Comment by FrankXie05** [comment]
> No, it is not official. The patch adds the export and the installation of the exported config. The keyword `EXPORT` isn't used upstream: https://github.com/podofo/podofo/blob/0.10.0/src/podofo/CMakeLists.txt.

No, upstream the keyword `EXPORT`.
https://github.com/podofo/podofo/blob/0.10.0/CMakeLists.txt#:~:text=if(PODOFO_BUILD_SHARED),endif()

**Review by LilyWangLL — DISMISSED** [review]

**Review by dg0yt — CHANGES_REQUESTED** [review]
Oh, confusion, also on my side. But I thinked it was worth looking closer:
- Upstream `CMakeLists` does 
  ~~~cmake
  export(TARGETS ... FILE "${PROJECT_BINARY_DIR}/podofoConfig.cmake")
  ~~~
  This is specific to the build tree and not useful for vcpkg.
  But it does qualify as setting the standard for the official config name and namespace.
  (NB: `podofoConfig.cmake` is for case-sensitive package name matching on `find_package(podofo)`.)

- The patch adds to `src/CMakeLists.txt`:
  ~~~cmake
  install(TARGETS podofo_static podofo_private EXPORT PoDoFoConfig ...)
  install(EXPORT PoDoFoConfig DESTINATION share/podofo)
  ~~~
  These commands are for installed trees, i.e. needed for vcpkg.
  But it uses a different case-sensitive package name, matching `find_package(PoDoFo)`. This is *unofficial*.

Now I see the following tasks:
- [ ] Rectify the config file name: the official package name is spelled `podofo`. Options:
  - Use `podofo-config.cmake`. This file name is for case-insensitive package name matching.
  - Use upstream's `podofoConfig.cmake`. However, to not break existing vcpkg users, you will need to provide a forwarding config under the old package name spelling.
- [ ] Add a usage file to get rid of vcpkg tools's limited heuristics.

~~~
podofo provides CMake targets:

    find_package(podofo CONFIG REQUIRED)
    target_link_libraries(main PRIVATE $<IF:$<TARGET_EXISTS:podofo_shared>,podofo_shared,podofo_static>)
~~~

**Comment by FrankXie05** [comment]
@dg0yt I don't think we should provide a `usage` where the upstream has an exported cmake config. I'll fix the case names.
`podofo-config.cmake`

**Review by dg0yt — DISMISSED** [review]
My major concerns are resolved. Thank you for the improvements.

**Comment by FrankXie05** [comment]
Upstream doesn't depend on `libxml2` features, so disabling it can reduce build time.
https://github.com/podofo/podofo/blob/33e9719ad7e2dd11631f3af6035986c781c18748/CMakeLists.txt#L196

**Review by LilyWangLL — APPROVED** [review]

**Comment by ceztko** [comment]
> Upstream doesn't depend on `libxml2` features, so disabling it can reduce build time.
> https://github.com/podofo/podofo/blob/33e9719ad7e2dd11631f3af6035986c781c18748/CMakeLists.txt#L196

PoDoFo maintainer here: no, libxml2 is now a requirement. Also OpenSSL is added as a strict requirement. The bar has been raised on this principle: anything needed to access the structure/metadata of the document is now a requirement. Anything else needed to decode content can be optional. Based on this principle:
- libxml2: needed to access metadata that are unique to XMP (eg. PDF/A level), or all metadata entries if `/Info` is missing;
- OpenSSL: needed to decrypt structure of the document.

Instead libpng, libjpeg, libtiff are needed just to decode content, so they are left as optional.

PoDoFo wants to be as much package manager friendly as possible, so feel free to suggest (non invasive) changes in the build system. I appear to have inspected already the usage of PoDoFo in vcpkg and Conan, and I added few more CMake [switches]( https://github.com/podofo/podofo#cmake-switches) and clarified handling of static vs shared library compilation.

**Comment by dg0yt** [comment]
@ceztko Thanks for having an eye on this port.

> > Upstream doesn't depend on `libxml2` features, so disabling it can reduce build time.
> 
> PoDoFo maintainer here: no, libxml2 is now a requirement. Also OpenSSL is added as a strict requirement. ...

Don't worry. The comment needs context to not be misunderstood.
`libxml2[core]` is a requirement.
What was requested and implemented for libxml2 is removing the hard dependency on the *default features* of port libxml2, i.e. features `iconv`, `lzma`, `zlib`. Users cannot opt out of building libxml2 feature `lzma` as long as some port depends on the default features of libxml2.

**Comment by ceztko** [comment]
> The comment needs context to not be misunderstood.

Thank you for the clarification.

**Comment by ceztko** [comment]
> if(PODOFO_BUILD_SHARED)
>     export(TARGETS podofo_shared FILE "${PROJECT_BINARY_DIR}/podofoConfig.cmake")
> else()
>     export(TARGETS podofo_static podofo_private FILE "${PROJECT_BINARY_DIR}/podofoConfig.cmake")
> endif()

This was present in PoDoFo [0.9.x](https://github.com/podofo/podofo/blob/5723d09bbab68340a3a32923d90910c3d6912cdd/CMakeLists.txt#L552) as well, and I admit to have no idea what it does. Please advice if this can be migrated to more modern CMake usage.

**Comment by dg0yt** [comment]
> This was present in PoDoFo [0.9.x](https://github.com/podofo/podofo/blob/5723d09bbab68340a3a32923d90910c3d6912cdd/CMakeLists.txt#L552) as well

Cf. the first part of https://github.com/microsoft/vcpkg/pull/31584#pullrequestreview-1441064375.
For the modern CMake usage, you need to export CMake config. Given the dependencies being linked as targets, this also means to provide the corresponding `find_dependency` calls which are added in the portfile here - normally only for static linkage, but `LibXml2::LibXml2` also appears for dynamic linkage ATM.

Now that podofo no longer builds static and shared at the same time, you wouldn't need `PODOFO_BUILD_STATIC` but could follow the standard `BUILD_SHARED_LIBS`.
And in the end you could migrate to uniform target/libary name. But this would probably need to be complemented by some polyfill to facilitate migrations.

BTW this port update triggered vcpkg baseline regressions because the presence of other packages causes non-obvious behavioural changes - for the x64-windows triplet (the only one with dynamic linkage in vcpkg CI), the port unexpectedly installed pkg-config files... Follow-up: https://github.com/microsoft/vcpkg/pull/31658

**Comment by ceztko** [comment]
> For the modern CMake usage, you need to export CMake config.

Ok, I think I understood the matter and I am now considering merging your [patch](https://github.com/microsoft/vcpkg/blob/master/ports/podofo/install-cmake-config.patch) as is. I don't see much use of saving the config files in the binary dir, and PoDoFo CMakeLists.txt is well optimized to be included in other CMake projects.

> the port unexpectedly installed pkg-config files... Follow-up: https://github.com/microsoft/vcpkg/pull/31658

I'm not sure what you mean here but if I merge the patch above I think you are fine with that.

> Now that podofo no longer builds static and shared at the same time

Previously I studied the matter and noticed that this was not working 100% as one would expect, so I consider this feature only "accidentally working". Now having both targets enabled would even more difficult because of private static targets so I just disabled it for the time being, or until a correct and maintainable solution to have both enabled is found.

> you wouldn't need `PODOFO_BUILD_STATIC` but could follow the standard `BUILD_SHARED_LIBS`.

I thought about it, and I actually tried it and committed it during development. I ended not liking it, and semantically I just prefer `PODOFO_BUILD_STATIC` which is default false, and will make a side effect when set to true. There's no advantage for me in using `BUILD_SHARED_LIBS` other than being more known variable name.  Also it does change the default of `add_library` which I don't use so it would be an unwanted side effect. Granted: `BUILD_SHARED_LIBS` may be nice for direct/indirect users of PoDoFo, but I think it's not a big deal because there's currently nothing in CMake that is trying to enforce that convention, and anything that can't be enforced is not a strict rule.

> And in the end you could migrate to uniform target/libary name.

Please elaborate more what you need with this.

**Comment by dg0yt** [comment]
> > For the modern CMake usage, you need to export CMake config.
> 
> Ok, I think I understood the matter and I am now considering merging your [patch](https://github.com/microsoft/vcpkg/blob/master/ports/podofo/install-cmake-config.patch) as is. I don't see much use of saving the config files in the binary dir, and PoDoFo CMakeLists.txt is well optimized to be included in other CMake projects.

For the general case, it may take a little bit more effort than just the patch: the portfile injects `find_dependency` calls. This needs to be adjusted for upstreaming. You may want to limit it to static linkage.

> > the port unexpectedly installed pkg-config files... Follow-up: #31658
> 
> I'm not sure what you mean here but if I merge the patch above I think you are fine with that.

They should always be installed. External usage is independent of pkg-config availability at build time.
Changes are needed to support static linkage.

> > Now that podofo no longer builds static and shared at the same time
> 
> Previously I studied the matter and noticed that this was not working 100% as one would expect, so I consider this feature only "accidentally working". Now having both targets enabled would even more difficult because of private static targets so I just disabled it for the time being, or until a correct and maintainable solution to have both enabled is found.

vcpkg doesn't need/want both simultaneously.

> > you wouldn't need `PODOFO_BUILD_STATIC` but could follow the standard `BUILD_SHARED_LIBS`.
> 
> I thought about it, and I actually tried it and committed it during development. I ended not liking it, and semantically I just prefer `PODOFO_BUILD_STATIC` which is default false, and will make a side effect when set to true. There's no advantage for me in using `BUILD_SHARED_LIBS` other than being more known variable name. Also it does change the default of `add_library` which I don't use so it would be an unwanted side effect. Granted: `BUILD_SHARED_LIBS` may be nice for direct/indirect users of PoDoFo, but I think it's not a big deal because there's currently nothing in CMake that is trying to enforce that convention, and anything that can't be enforced is not a strict rule.

Well, it would be one variable less invented differently in each project, for a single problem.
If it is about the default, use
~~~cmake
option(BUILD_SHARED_LIBS "Build a shared podofo library" ON)
~~~
(Alternatively, it would be possible to just derive the default of `PODOFO_BUILD_STATIC` from `BUILD_SHARED_LIBS`.)

> > And in the end you could migrate to uniform target/libary name.
> 
> Please elaborate more what you need with this.

I would prefer if I could use uniformly use:
~~~cmake
find_package(podofo REQUIRED)
target_link_libraries(main PRIVATE podofo::podofo)
~~~
This doesn't require to rename the targets - it can be implemented in the config using an interface target.

**Comment by ceztko** [comment]
> For the general case, it may take a little bit more effort than just the patch [...] You may want to limit it to static linkage.

The problem here is I have no experience with usage of config files, I either include subprojects or find dependencies with `find_package`. Maybe you mean that the config files should better supply compile/linking flags, or specify variables that points to include directory locations? If you show me a (simple) project that does it right it would be easier for me to understand what to do here.

> Well, it would be one variable less invented differently in each project, for a single problem.

You make it easy, but deriving `PODOFO_BUILD_STATIC` from `BUILD_SHARED_LIBS` may be unwanted, because it's easily inherited from external projects, and I want a predictable behavior without the need to set variables that has opposite meaning (which otherwise is a mess). Sorry, but as said: it it's not enforced by CMake I feel free to put my grain of salt here.

> I would prefer if I could use uniformly use:
> ```target_link_libraries(main PRIVATE podofo::podofo)```

Recently we added support to refer to (most) dependencies with that target notation. Please show me a simple project that export targets this way from within the build project (not a `Find<module>.cmake`) and I will implement it.

**Comment by ceztko** [comment]
Hello, I merged your patch about installing config files during install in https://github.com/podofo/podofo/commit/9a073769e6dbe651a014b041f1f8e825f354ecce . I'm not exporting them in the binary folder anymore, we'll see if someone complains about it (I personally don't use them), but the recommended approach is to just include the project file anyway for CMake users, and installing for everyone else. I also added the `podofo::podofo` alias as you recommended https://github.com/podofo/podofo/commit/97447ad10e8f87a41b93f20755e2a55cddfdff73, and I released [0.10.1](https://github.com/podofo/podofo/releases/tag/0.10.1) . If you have further recommendations for future releases please tell me, I'm listening, as I want to have a policy of zero patches for package managers. If you have, please prefer scratching modifications in form of patches/small snippets, as I don't know all possible CMake usage patterns as you do, and it may be difficult for me to understand what do by your descriptions.

**Comment by ceztko** [comment]
Sorry for resuming this old PR, but I just wanted to inform that with PoDoFo 1.0 coming in few days, or with current master, the integration with CMake of PoDoFo as a package improved and now it's possible to do something like:

```
cmake_minimum_required(VERSION 3.23)

project(PoDoFoSample)

set(CMAKE_CXX_STANDARD 17)

# In Windows, or if you installed the package to non
# standard paths
list(APPEND CMAKE_PREFIX_PATH "D:\\Test\\PoDoFoInstallDir")

# Alternative to altering CMAKE_PREFIX_PATH
#set(PoDoFo_DIR "D:\\Test\\PoDoFoInstallDir\\share\\cmake\\podofo")

find_package(PoDoFo 1.0.0 REQUIRED)
message(STATUS "Found PoDoFo: ${PoDoFo_VERSION}")

add_executable(helloworld main.cpp)
target_link_libraries(helloworld podofo::podofo)
```

I think this covers what you suggested here but at the time I could not really grasp all the steps involved into getting this level of integration with CMake. I just merged a patch of yours which exported the targets, which I discovered recently it had some limitations. Some suggestions on improving the CMake integration came from [this](https://github.com/xournalpp/xournalpp/pull/6364#issuecomment-2858805083) message. I will drop a last message here when 1.0 is released.

**Comment by dg0yt** [comment]
@ceztko Would it make sense to test an 1.0 candiate in vcpkg CI before it gets officially released?

**Comment by ceztko** [comment]
I'm sorry, but I am not a vcpkg maintainer, nor I use vcpkg myself. I just lurked this issue and similar ones in the past trying to improve the PoDoFo experience in various package managers (my idea is that there should be zero 3rd party patches in the build configuration). PoDoFo 1.0 is due very soon, but I am available to assist you with patch releases if you encounter problems during vcpkg integration.

**Comment by dg0yt** [comment]
You weren't asked to do that yourself...
Okay, found the rc1 tag for 1.0.0.
But oh, `3rd-party`... vcpkg might want to devendor what has aport.

**Comment by ceztko** [comment]
> But oh, `3rd-party`... vcpkg might want to devendor what has a port.

I know: this is not the right place to discuss, but let me review those for you. These seems to have a vcpkg port and I use them unmodified:
- [date](https://github.com/HowardHinnant/date): header only, used in place of c++20 date/time functions https://vcpkg.link/ports/date
- [fmt](https://github.com/fmtlib/fmt): header only, used in place of c++20 `std::format` https://vcpkg.io/en/package/fmt.html
- [utf8cpp](https://github.com/nemtrif/utfcpp): header only https://vcpkg.link/ports/utfcpp
- [utf8proc](https://juliastrings.github.io/utf8proc/): C library with a single compilation unit, https://vcpkg.link/ports/utf8proc
- [fast_float.h](https://github.com/fastfloat/fast_float): header only https://vcpkg.io/en/package/fast-float.html

The following I don't recommend devendor, even if you find a port:
- [afdko](https://github.com/adobe-type-tools/afdko): partial strip
- [numerics](https://chromium.googlesource.com/chromium/src/base/+/master/numerics/): full header only library stripped from pdfium/chromium with few quirks
- [pdfium](https://pdfium.googlesource.com/pdfium/): very minimal strip of just few classes
- [tclap](https://tclap.sourceforge.net/): ignore, not used in PoDoFo library
- [span.hpp](https://github.com/tcbrindle/span): header only, used as part of the PoDoFo API

**Comment by ceztko** [comment]
PoDoFo 1.0.0 released ([announcement](https://www.mail-archive.com/podofo-users@lists.sourceforge.net/msg05005.html)).

**Pull request merged**
