### PR TITLE
[liblzma] Fix downstream linker warnings

### LINKED ISSUE #30997: [liblzma] Many linker warnings about missing PDB
**Describe the bug**
Linking LibLZMA causes many linker warnings for all dependent targets. This also affects ports that rely on LibLZMA indirectly, such as TIFF. The linker warning is LNK4099 - missing PDB (liblzma.pdb)

**Environment**
- OS: Windows 11
- Compiler: Visual Studio 2022
- Triplet: `x64-windows-static`
- Debug build configuration

**To Reproduce**
Minimal CMake project that uses vcpkg in manifest mode:

CMakeLists.txt
```cmake

cmake_minimum_required(VERSION 3.16)

# Make sure vcpkg toolchain file is used
if(NOT DEFINED CMAKE_TOOLCHAIN_FILE)
    if(DEFINED ENV{VCPKG_ROOT})
        set(CMAKE_TOOLCHAIN_FILE "$ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake")
    else()
        message(FATAL_ERROR "You have to pass pass -DCMAKE_TOOLCHAIN_FILE=VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake to cmake")
    endif()
endif()

# Make sure that static triplet is selected
if(WIN32 AND CMAKE_GENERATOR_PLATFORM MATCHES "64$" AND NOT CMAKE_GENERATOR_PLATFORM STREQUAL "ARM64")
    set(VCPKG_TARGET_TRIPLET "x64-windows-static")
elseif(WIN32 AND CMAKE_GENERATOR_PLATFORM MATCHES "32$" OR CMAKE_GENERATOR_PLATFORM STREQUAL "x86")
    set(VCPKG_TARGET_TRIPLET "x86-windows-static")
else()
    message(WARNING "You need to select a static VCPKG_TARGET_TRIPLET to reproduce this")
endif()

project(min-vcpkg-liblzma-test)
find_package(liblzma REQUIRED)
add_executable(min-vcpkg-liblzma-test ${CMAKE_CURRENT_SOURCE_DIR}/main.cpp)
set_property(TARGET min-vcpkg-liblzma-test PROPERTY MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
target_link_libraries(min-vcpkg-liblzma-test PRIVATE LibLZMA::LibLZMA)
```

vcpkg.json

```json
{
    "name": "min-vcpkg-liblzma-test",
    "version": "1.0.0",
    "builtin-baseline": "809266d51a238e504acc134e5878c7860d5c179c",
    "dependencies": [ "liblzma" ]
}
```

main.cpp

```c++

#include <lzma.h>

int main() {
    lzma_stream strm = LZMA_STREAM_INIT;
    lzma_easy_encoder(&strm, 0, LZMA_CHECK_CRC64);
	return 0;
}
```

Download link: [min-liblzma-test.zip](https://github.com/microsoft/vcpkg/files/11294057/min-liblzma-test.zip)

**Expected behavior**
No warnings.

**Failure logs**
```
Build started...
1>------ Build started: Project: ZERO_CHECK, Configuration: Debug x64 ------
1>Checking Build System
2>------ Build started: Project: min-vcpkg-liblzma-test, Configuration: Debug x64 ------
2>Building Custom Rule C:/Temp/min-liblzma-test/CMakeLists.txt
2>main.cpp
2>lzma.lib(easy_encoder.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(easy_encoder.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(stream_encoder.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(stream_encoder.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(easy_preset.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(easy_preset.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(common.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(common.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(filter_common.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(filter_common.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(stream_flags_encoder.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(stream_flags_encoder.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(block_header_encoder.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(block_header_encoder.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(block_util.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(block_util.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(index.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(index.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(block_encoder.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(block_encoder.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(index_encoder.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(index_encoder.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(lzma_encoder_presets.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(lzma_encoder_presets.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(crc32_fast.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(crc32_fast.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(stream_flags_common.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(stream_flags_common.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(vli_encoder.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(vli_encoder.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(vli_size.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(vli_size.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(filter_flags_encoder.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(filter_flags_encoder.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(check.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(check.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(filter_encoder.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(filter_encoder.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(crc32_table.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(crc32_table.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(crc64_fast.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(crc64_fast.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(sha256.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(sha256.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(lzma_encoder.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(lzma_encoder.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(lzma2_encoder.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(lzma2_encoder.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(x86.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(x86.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(powerpc.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(powerpc.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(ia64.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(ia64.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(arm.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(arm.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(armthumb.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(armthumb.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(arm64.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(arm64.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(sparc.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(sparc.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(simple_encoder.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(simple_encoder.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(delta_common.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(delta_common.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(delta_encoder.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(delta_encoder.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(crc64_table.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(crc64_table.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(lz_encoder.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(lz_encoder.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(lzma_encoder_optimum_fast.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(lzma_encoder_optimum_fast.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(lzma_encoder_optimum_normal.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(lzma_encoder_optimum_normal.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(price_table.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(price_table.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(fastpos_table.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(fastpos_table.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(simple_coder.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(simple_coder.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>lzma.lib(lz_encoder_mf.c.obj) : warning LNK4099: PDB 'liblzma.pdb' was not found with 'lzma.lib(lz_encoder_mf.c.obj)' or at 'C:\Temp\min-liblzma-test\build\win64\Debug\liblzma.pdb'; linking object as if no debug info
2>min-vcpkg-liblzma-test.vcxproj -> C:\Temp\min-liblzma-test\build\win64\Debug\min-vcpkg-liblzma-test.exe
2>Done building project "min-vcpkg-liblzma-test.vcxproj".
3>------ Skipped Build: Project: ALL_BUILD, Configuration: Debug x64 ------
3>Project not selected to build for this solution configuration 
========== Build: 2 succeeded, 0 failed, 0 up-to-date, 1 skipped ==========
```

### PR DESCRIPTION
**Pull request by dg0yt**
Fixes #30997.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by dg0yt** [comment]
Related: #32338.

**Review by MonicaLiu0311 — APPROVED** [review]

**Comment by dg0yt** [comment]
@MonicaLiu0311 added the https://github.com/microsoft/vcpkg/labels/depends%3Adifferent-pr label yesterday

No. This PR doesn't depend on another PR.

**Review by MonicaLiu0311 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks!

**Pull request merged**
