### PR TITLE
Force rebuild all packages in CI

### PR DESCRIPTION
**Pull request by vicroms**

### CODE REVIEW

**Comment by Neumann-A** [comment]
qt5-tools regression on linux due to automatically picked up external dependency to some XML library in one of the qt5-ports. qt is really annoying with this automatically picked up dependencies.

**Comment by vicroms** [comment]
It will take some time to fix all of these regressions 😞

**Comment by JackBoosY** [comment]
@vicroms Don't worry, some of them are expected.

**Comment by PhoebeHui** [comment]
Check port failures on Linux:

Port | Failures
-- | --
google-cloud-cpp | conflict with google-cloud-cpp-common
libmesh | conflict with boost-algorithm
mmx | conflict with jsonnet
nanovg | conflict with stb
otl | File does not have expected hash:   File path: [   /ci/myagent/_work/2/s/downloads/temp/otlv4_h2-4.0.447.zip ]   Expected hash: [ 07663442272a327a7d9154f6e817c0166ed254cfe3b9d043762179e96180a70d3ba4b3762e5ef1ebdb18492e3425467c9ddad3a2c68aa93bb7d51d54e9712008   ]   Actual hash: [   03616606ffb903e43af2e8fec0cd6ecd22380b711966145ca7fe5f1ccde151dcaff044ce7c81389e4055cdab72d019cc301d023a6e179492d1df8b5f2787f4d9   ]
xmsh | Failed to download file. The source https://github.com/libxmsh/xmsh/archive/v0.4.1.tar.gz   doesn’t exist. Need update.   -- Downloading https://github.com/libxmsh/xmsh/archive/v0.4.1.tar.gz...   Failed. Status: 22;"HTTP response code said error"
rapidstring | Failed to download file. Cannot access the https://github.com/boyerjohn/rapidstring   -- Downloading   https://github.com/boyerjohn/rapidstring/archive/ee433955c1e9cacfaecbf53c0a13318ab5825bd4.tar.gz...   Failed. Status: 22;"HTTP response code said error"
tinyfiledialogs | Failed to download file. The source URL https://git.code.sf.net/p/tinyfiledialogs/code   could not access.
cppkafka | Build failures
qt5-tools | Build failures
quickfix | Build failures
Xalan-c | Build failures

**Comment by PhoebeHui** [comment]
Ports failures on windows:


Port | Triplets | Failures
-- | -- | --
google-cloud-cpp | x64-windows   x86-windows   x64-windows-static | conflict with google-cloud-cpp-common
ogre | x64-windows    x86-windows   x64-windows-static | Conflict with ogre-next
mmx | x64-windows   x86-windows   x64-windows-static   x64-uwp   arm64-windows   arm-uwp | conflict with jsonnet
nanovg | x64-windows   x86-windows   x64-windows-static   arm64-windows | conflict with stb
otl | x64-windows   x64-windows-static   x64-uwp   arm64-windows   arm-uwp | File does not have expected hash:   File path: [   /ci/myagent/_work/2/s/downloads/temp/otlv4_h2-4.0.447.zip ]   Expected hash:    [ 07663442272a327a7d9154f6e817c0166ed254cfe3b9d043762179e96180a70d3ba4b3762e5ef1ebdb   18492e3425467c9ddad3a2c68aa93bb7d51d54e9712008 ]   Actual hash:    [   03616606ffb903e43af2e8fec0cd6ecd22380b711966145ca7fe5f1ccde151dcaff044ce7c81389e4055cd   ab72d019cc301d023a6e179492d1df8b5f2787f4d9 ]
parmetis | x64-windows   x86-windows   x64-windows-static | Failed to download file  Downloading http://glaros.dtc.umn.edu/gkhome/fetch/sw/parmetis/parmetis-4.0.3.tar.gz...    Failed. Status:   6;"Couldn't resolve host name"
rapidstring | x64-windows   x86-windows   x64-windows-static | Failed to download file. Cannot access the https://github.com/boyerjohn/rapidstring   -- Downloading https://github.com/boyerjohn/rapidstring/archive/ee433955c1e9cacfaecbf53c0a13318ab5825bd4.tar.gz...      Failed. Status: 22;"HTTP response code said   error"
cnl | x64-windows-static | Failed to download file.    Downloading   https://github.com/johnmcfarlane/cnl/archive/48428242e72b8239cb14c963e40f724929d54df7.tar.gz...      Failed. Status: 22;"HTTP response code said   error"
tiff | X64-uwp | -- Downloading   http://download.osgeo.org/libtiff/tiff-4.0.10.tar.gz... Failed. Status:   7;"Couldn't connect to server"
tinyfiledialogs | x64-windows   x86-windows | Failed to download file. The source URL https://git.code.sf.net/p/tinyfiledialogs/code   could not access.
libfabric | x64-windows | Build failures
pangomm | x64-windows | Build failures
quickfix | x64-windows   x86-windows   x64-windows-static   x64-uwp   arm64-windows   arm-uwp | Build failures
tesseract | x64-windows   x86-windows   x64-windows-static | Build failures
gsoap | x86-windows   arm-uwp | Build failures
libxslt | arm64-windows | Build failures
qhull | arm-uwp | Build failures

**Comment by PhoebeHui** [comment]
Exist PRs to address above issue: 
otl: https://github.com/microsoft/vcpkg/issues/8794
xmsh: https://github.com/microsoft/vcpkg/pull/7155

**Comment by vicroms** [comment]
I have removed the failing tombstones and will rerun the tests, hopefully this will reduce the number of regressions

**Comment by PhoebeHui** [comment]
4 ports failed totally on windows In latest CI results:

3 ports failed to download the source file:
rapidstring: the source has gone, I can not find the new address instead.
parmetis: http://glaros.dtc.umn.edu/ seems down, I can't access it.
tinyfiledialogs: failed get source from https://git.code.sf.net/p/tinyfiledialogs/code, also failed to download from https://sourceforge.net/projects/tinyfiledialogs/

1 ports libxslt failed with arm64-windows, I can't repro this issue with vs2017 and vs2019 on windows locally, failures:
libxml2.lib(libxml2.dll) : fatal error LNK1112: module machine type 'ARM64' conflicts with target machine type 'ARM'

**Comment by vicroms** [comment]
`rapidstring` seems to have disappeared from the face of the earth (the author deleted their GitHub repo and with it all existing forks); so we should probably delete the port as well.

I've updated the current commit ID for `tinyfiledialogs`, the failure is unexepected as I'm still able to browse their repo at the previous commit but vcpkg is not able to get the sources.

I'm not sure what to do about `parmetis`, as the top-level domain is still alive and kicking (belongs to the Unniversity of Minessota), it might come back it might not... for the time being I'll just disable that port in our CI.

I'll take a look at `libxslt`, it has failed consistently on our CI machines so it is not a false negative.

**Comment by vicroms** [comment]
`quickfix` fails when `double-conversion` is installed, this is due to it using an embedded dependency of `double-conversion`.

**Comment by JackBoosY** [comment]
Current regression port:
Linux:
- qt5-tools

OSX:
- llvm
- xmsh

Windows(arm64-windows):
- libxslt

**Comment by cenit** [comment]
@vicroms
OTL maintainers has the very bad habit of updating zip overwriting previous one. Hash was failing because it was updated to .448 in the meantime, so you can refer to that version now since you updated hash in 2a32220852e5eada6e17eb33d2cd1b740a87744f

**Comment by vicroms** [comment]
@cenit thanks for the heads-up, I changed the CONTROL version.

**Comment by JackBoosY** [comment]
I can't reproduce the arm64-windows error on my machine, it seems that everything is fine.

**Comment by JackBoosY** [comment]
And I can't repro x64-linux error on the machine. `libEGL.so`/`libicui18n.a`/`libicuuc.a`/`libicudata.a` does not exist on my machine, but qt5-tools has been successfully built.

@Neumann-A I think qt5 automatically activates some options, what do you think?

**Comment by Neumann-A** [comment]
@JackBoosY: Yeah I fear we must be explicit about all the qt options and make them a feature (#8213) or the default. qt-imageformats for example has 4 options and at least 3 can make problems in vcpkg from which two are explicitly set (tiff, webp) and jasper is missing. Those options can be discovered by looking for a config_help.txt or by searching for a number of configure.json in the source tree. But without #8269 solved I fear that static builds might be difficult to link correctly due to all the possible options in building dependent libraries. 
The other question is how can we make features which are only available on certain platforms. Qt has a lot of options which only apply to Unix or Windows. So having target dependent features would be nice to have (like target dependent Build-Depends)

I already have a small number of qt fixes in different PRs to silent CI:
libpq fix
https://github.com/microsoft/vcpkg/pull/8551/commits/e4a55093dd01f79afa70355e259f5cb99f051f5a
qt-imageformat (jasper fix)
https://github.com/microsoft/vcpkg/pull/8566/commits/db518863bdf000b04b54b1d909232028e47a2999
https://github.com/microsoft/vcpkg/pull/8566/commits/f1e3e10f3b141d74547798146ca149eac42b3c67
https://github.com/microsoft/vcpkg/pull/8566/commits/d0f191708e02eb3f10049b9b0335cfadf5f3803e
https://github.com/microsoft/vcpkg/pull/8566/commits/c1be2ac36bcbe69604fc2d9b3c421e59e0e6ba5c

The current errors seen in qt5-tools are probably due to the following options in qt5-base:
```
  -icu ................. Enable ICU support [auto]
  -opengles3 ........... Enable OpenGL ES 3.x support instead of ES 2.x [auto]
  -egl ................. Enable EGL support [auto]
```
To make static builds work you need to probably pass ICU_LIBS and EGL_LIBS with the correct libraries.
 
but there are a few more options which should be checked like:
```
  -doubleconversion .... Select used double conversion library [system/qt/no]
                         No implies use of sscanf_l and snprintf_l (imprecise).
  -glib ................ Enable Glib support [no; auto on Unix]
```
(basically everything which is auto in the config_help.txt should be checked.)
You can always check the config-<triplet>-err.log to see which options have been enabled.

**Comment by vicroms** [comment]
Thanks @Neumann-A  for the very informative comment about Qt's regressions, I agree that the ports need a lot more work in order to get rid of as much auto-configured options as possible.

There are PRs open to introduce qualifiers for default features, (e.g.: `Default-Features: feat-a(windows&!uwp) feat-b(!windows) feat-c`). But they're blocked by the current state of CI 😞 

With the purpose of unblocking CI ASAP, I decided to only add the missing dependencies to Qt and handle further changes in a PR later.

**Comment by vicroms** [comment]
Some good news, looks like the download servers for metis and parmetis are back, so I've reenabled them in CI.

**Comment by vicroms** [comment]
I see failures on Mac OS during the build step but there aren't any corresponding log files

**Comment by c72578** [comment]
> 
> 
> @vicroms
> OTL maintainers has the very bad habit of updating zip overwriting previous one. Hash was failing because it was updated to .448 in the meantime, so you can refer to that version now since you updated hash in [2a32220](https://github.com/microsoft/vcpkg/commit/2a32220852e5eada6e17eb33d2cd1b740a87744f)

In the meantime **OTL** has been updated again.
Since 2019-11-15 it is at version 4.0.449
New sha512:
055bc52233553738fbdc52a1c5885fad72f3f7bfa9df7bd5880ab47dd656439d00ff8870b1c9a807dc32e205921abbf0ca34bd2bc29aed257fd822685fee8c9e

**Comment by cenit** [comment]
> > @vicroms
> > OTL maintainers has the very bad habit of updating zip overwriting previous one. Hash was failing because it was updated to .448 in the meantime, so you can refer to that version now since you updated hash in [2a32220](https://github.com/microsoft/vcpkg/commit/2a32220852e5eada6e17eb33d2cd1b740a87744f)
> 
> In the meantime **OTL** has been updated again.
> Since 2019-11-15 it is at version 4.0.449
> New sha512:
> 055bc52233553738fbdc52a1c5885fad72f3f7bfa9df7bd5880ab47dd656439d00ff8870b1c9a807dc32e205921abbf0ca34bd2bc29aed257fd822685fee8c9e

https://sourceforge.net/p/otl/discussion/208859/thread/fdb9d3bacc/

**Comment by vicroms** [comment]
> In the meantime **OTL** has been updated again.

@c72578  Thanks for the heads-up!

> https://sourceforge.net/p/otl/discussion/208859/thread/fdb9d3bacc/

@cenit Thank you very mcuh for taking the time to report this upstream! I read the thread and I'm glad that the maintainers were so quick to address this.

**Comment by Neumann-A** [comment]
qt-base requires fontconfig on linux due to automatic detection. Add `FONTCONFIG_LIBS` and also pass expat and libiconv libraries in that variable. Missing symbols seem to be due to expat. Alternativly disable fontconfig for now via `-no-fontconfig`

**Comment by Neumann-A** [comment]
>qt5-tools: library libxml2 is not linked.

@JackBoosY It is expat not libxml2. libxml2 uses different symbols. (see https://github.com/microsoft/vcpkg/pull/8912#issuecomment-554796750) https://www.xml.com/pub/a/1999/09/expat/reference.html

**Comment by cenit** [comment]
(otl is "broken" on master, you might already know that...)

**Comment by cenit** [comment]
@JackBoosY you just broke @vicroms PR in the same way the master is broken.... @vicroms original otl's portfile was ok

**Comment by JackBoosY** [comment]
@cenit Ops...I thought this port has been updated.

**Comment by coryan** [comment]
@JackBoosY I think the `google-cloud-cpp` issues should be resolved now (see #8986 ) please let me know if I can help in any way.

**Comment by cenit** [comment]
> `rapidstring` seems to have disappeared from the face of the earth (the author deleted their GitHub repo and with it all existing forks); so we should probably delete the port as well.

I have a clone of that repository, if you want (only latest commit). But not being the original library author, I think it might not be the best idea to point to my repository...

https://github.com/cenit/rapidstring

**Comment by vicroms** [comment]
As CI has been restored, this full rebuild is no longer necessary, I'll separate fixes made in here into their own PRs.

Thanks to everyone that helped with solving the flakiness in our ports!

**Pull request closed without merging**
