### PR TITLE
[openimageio] update to 2.2.16

### LINKED ISSUE #19156: [openimageio] update to 2.2.16
Library name: OpenImageIO

New version number: 2.2.16

Other information that may be useful (release notes, etc...)

https://github.com/OpenImageIO/oiio/releases/tag/v2.2.16.0

### PR DESCRIPTION
**Pull request by JonLiu1993**
Fix #19156 

Update openimageio to the latest version 2.2.16

All features are tested successfully in the following triplet:
- x86-windows
- x64-windows
- x64-windows-static

### CODE REVIEW

**Comment by JonLiu1993** [comment]
Duplicate of #19272

**Comment by EvanAW** [comment]
I take it you meant #19156 and not #19272?

**Comment by NancyLi1013** [comment]
Thanks for your notice. #19272 contained the update to 2.2.16. So the comment is right.

**Comment by JonLiu1993** [comment]
> I take it you meant #19156 and not #19272?

Pr #19272 update three port yaml-cpp,openimageio,opencolorio

**Pull request closed without merging**
