### PR TITLE
[pdal] Update to 2.4.0

### PR DESCRIPTION
**Pull request by dg0yt**
- #### What does your PR fix?
  Update PDAL to 2.4.0. Major upstream changes:
  - laszip replaced by vendored copy of LAZperf (aka laz-perf).
  - boost::filesystem replaced by C++17 std::filesystem (~requires patching to build with Ubuntu 18.04; untested~ older compilers unsupported).

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  unchanged, no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  yes

### CODE REVIEW

**Comment by dg0yt** [comment]
> * boost::filesystem replaced by C++17 std::filesystem (requires patching to build with Ubuntu 18.04; untested).

Upstream says that "you shouldn't use PDAL 2.4 if you don't have C++17".
How to express that: Fail? Print a warning? Depend on port "cxx17[filesystem]"? Require an opt-in "experimental-filesystem" feature?
x64-linux in vcpkg CI has Ubuntu 18.04 which doesn't qualify for a pristine C++17 build.

**Comment by JackBoosY** [comment]
> > * boost::filesystem replaced by C++17 std::filesystem (requires patching to build with Ubuntu 18.04; untested).
> 
> Upstream says that "you shouldn't use PDAL 2.4 if you don't have C++17". How to express that: Fail? Print a warning? Depend on port "cxx17[filesystem]"? Require an opt-in "experimental-filesystem" feature? x64-linux in vcpkg CI has Ubuntu 18.04 which doesn't qualify for a pristine C++17 build.

According to our policy, we shouldn't add a cxx17 feature, but the upstream requires that first, we need to choose a way to ensure the user's compiler support cxx17 first.
@BillyONeal What's your opinion?

**Comment by dg0yt** [comment]
> we shouldn't add a cxx17 feature, 

Nobody suggested that.

>but the upstream requires that first, we need to choose a way to ensure the user's compiler support cxx17 first.

That's my point. 
There could be a port `cxx17`, as much as there is a port `atlmfc`. It would be the single place to generate the user-facing error message. And this port could have a feature interface.

However, it wouldn't solve the lack of C++17 support in x64-linux CI.

**Comment by BillyONeal** [comment]
> There could be a port `cxx17`, as much as there is a port `atlmfc`. It would be the single place to generate the user-facing error message. And this port could have a feature interface.

Sure.

> However, it wouldn't solve the lack of C++17 support in x64-linux CI.

CI uses Ubuntu 20.04 which comes with GCC 9.3.0 which has '17 support.

**Comment by dg0yt** [comment]
> CI uses Ubuntu 20.04 which comes with GCC 9.3.0 which has '17 support.

Sorry. I checked that it is "focal" but I attached the wrong number...

**Review by raghavthind2005 — APPROVED** [review]

**Comment by dg0yt** [comment]
@JackBoosY This PR is complete and doesn't need an inspection port. I don't think it needs "discussion" at this point.

**Review by JackBoosY — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the version update!

**Pull request merged**
