### PR TITLE
[angle] update list of required apt packages

### PR DESCRIPTION
**Pull request by wrobelda**
**Describe the pull request**
`libmesa-dev` is not the package that needs to be installed, `mesa-common-dev` is. 

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  No change.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes. This is a cosmetic change to the pre-compilation message, so I did not bump the `port-version` as there's no need to trigger a recompilation of this and all dependant ports.

### CODE REVIEW

**Comment by Adela0814** [comment]
@wrobelda  Please upgrade the port version in `angle\vcpkg.json`.

**Comment by wrobelda** [comment]
> @wrobelda Please upgrade the port version in `angle\vcpkg.json`.

I added a comment on that in the PR description. Is that really necessary in this case?

**Comment by Adela0814** [comment]
> I explicitly addressed that in the PR description. Is bumping port version really necessary in this case?

Yes, you need upgrade the port version once the `portfile.cmake` is changed.

**Comment by wrobelda** [comment]
> So strictly speaking this should actually depend on the mesa and the x* ports

I had a strong deja vu we talked about this already, and after checking it turns out I have a local branch that prepared for this in may 2021, which I forgot about 😂

Let's push this change first and I'll try get the other PR done independently.

**Comment by wrobelda** [comment]
> Yes, you need upgrade the port version once the `portfile.cmake` is changed.

It definitely is an overkill, but did as you suggest and updated the PR. Should be ready now.

**Comment by wrobelda** [comment]
@Adela0814 as noted, this is ready.

**Pull request merged**
