### PR TITLE
[yalantinglibs]add port

### PR DESCRIPTION
**Pull request by helintongh**
**Describe the pull request**

- #### What does your PR fix?
this PR adds a new port https://github.com/alibaba/yalantinglibs . A collection of C++20 libraries, include async_simple, coro_rpc and struct_pack 

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
single header library. All supported AFAIK. No CI changes.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**
Yes

### CODE REVIEW

**Comment by helintongh** [comment]
@microsoft-github-policy-service agree

**Comment by helintongh** [comment]
when I use vcpkg install yalantinglibs in my computer.No error.
but in ci command 
image
It give feedback is `CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112`.
I found I can excute `cmake .`  which can configure cmake file first and then excute ci command it will be ok. How can i fix this error,can help me?thanks.

**Comment by lichray** [comment]
> It give feedback is `CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112`. I found I can excute `cmake .` which can configure cmake file first and then excute ci command it will be ok. How can i fix this error,can help me?thanks.

https://dev.azure.com/vcpkg/public/_build/results?buildId=83744&view=logs&j=f79cfdd7-47a8-597f-8f57-dc3e21a8f2ad&t=ecc7153e-cc3c-5847-a756-7e8899ae9637

The failure logs should have been uploaded somewhere:

```
Upload '/agent/_work/1/a/failure-logs' to file container: '#/20476101/failure logs for x64-linux'
Associated artifact 422345 with build 83744
```

The Pipelines aren't only about installation, it contains lots of scripts to check. You may try some of these by reading  https://github.com/microsoft/vcpkg/tree/master/scripts/azure-pipelines.

**Comment by helintongh** [comment]
because of modify portfile.cmake must create new pull request,close this pull request.
new request is https://github.com/microsoft/vcpkg/pull/29011

**Pull request closed without merging**
