### PR TITLE
[freetype] Update to 2.10.4

### PR DESCRIPTION
**Pull request by kevinlul**
pkgconfig patch was upstreamed

- What does your PR fix? Regular port update https://sourceforge.net/projects/freetype/files/freetype2/2.10.4/ with major security vulnerability fix

- Which triplets are supported/not supported? Have you updated the CI baseline? Should be no changes

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)? Yes

### CODE REVIEW

**Comment by JackBoosY** [comment]
```
D:\buildtrees\vtk\src\ad8774e85e-a44294b9ee.clean\Rendering\FreeType\vtkFreeTypeTools.cxx(382): error C3646: 'vtkFreeTypeToolsFaceRequester': unknown override specifier
D:\buildtrees\vtk\src\ad8774e85e-a44294b9ee.clean\Rendering\FreeType\vtkFreeTypeTools.cxx(382): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\buildtrees\vtk\src\ad8774e85e-a44294b9ee.clean\Rendering\FreeType\vtkFreeTypeTools.cxx(382): error C2059: syntax error: '('
D:\buildtrees\vtk\src\ad8774e85e-a44294b9ee.clean\Rendering\FreeType\vtkFreeTypeTools.cxx(383): error C2146: syntax error: missing ')' before identifier 'face_id'
D:\buildtrees\vtk\src\ad8774e85e-a44294b9ee.clean\Rendering\FreeType\vtkFreeTypeTools.cxx(383): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\buildtrees\vtk\src\ad8774e85e-a44294b9ee.clean\Rendering\FreeType\vtkFreeTypeTools.cxx(383): error C2377: 'FTC_FaceID': redefinition; typedef cannot be overloaded with any other symbol
D:\installed\x64-windows\include\freetype/ftcache.h(171): note: see declaration of 'FTC_FaceID'
```
Does this related to your changes?

**Comment by kevinlul** [comment]
I think it is related to [how that library uses freetype](https://github.com/Kitware/VTK/blob/master/Rendering/FreeType/vtkFreeTypeTools.cxx#L382) and something with redefining that typedef
```c
typedef FT_Pointer  FTC_FaceID;
```
but the code immediately surrounding it hasn't changed.

**Comment by JackBoosY** [comment]
> I think it is related to [how that library uses freetype](https://github.com/Kitware/VTK/blob/master/Rendering/FreeType/vtkFreeTypeTools.cxx#L382) and something with redefining that typedef
> 
> ```c
> typedef FT_Pointer  FTC_FaceID;
> ```
> 
> but the code immediately surrounding it hasn't changed.

So I think the port should be upgraded synchronously with vtk.

**Review by JackBoosY — APPROVED** [review]

**Comment by kevinlul** [comment]
Scope of PR changed to 2.10.4, which includes a security fix for a vulnerability since 2.6

**Comment by kevinlul** [comment]
It seems like this is actually a bug in VTK, using a freetype-internal macro. https://discourse.vtk.org/t/building-opencascade-7-5-0-with-vtk-9-0-1/4673/19 

These are apparently patched in VTK mainline but I don't know what its release cycle is. We could apply the patches to VTK temporarily? For posterity, what's the vcpkg policy here if an update (freetype) breaks other ports but is considered urgent due to security issues?

**Comment by JackBoosY** [comment]
@kevinlul Yep, we accpet the official patch.

**Comment by kevinlul** [comment]
I was asking for the case if no such patch existed for vtk.

**Comment by JackBoosY** [comment]
@kevinlul That's fine.

**Pull request closed without merging**
