### PR TITLE
[harfbuzz] fix iOS build

### PR DESCRIPTION
**Pull request by comrade-tomsk**
- #### What does your PR fix?
  Fix harfbuzz building on iOS where ApplicationServices framework is unavailable

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  All, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
 Yes

### CODE REVIEW

**Comment by comrade-tomsk** [comment]
@microsoft-github-policy-service agree

**Review by BillyONeal — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks!

**Comment by BillyONeal** [comment]
The failures looked like baseline issues, I pushed a merge with https://github.com/microsoft/vcpkg/pull/27619 to see if that fixes it.

**Comment by BillyONeal** [comment]
The build break is a baseline issue, investigating.

**Comment by JavierMatosD** [comment]
Thank you!

**Pull request merged**
