### PR TITLE
Allow uname calls in download mode + Fix handling of files without RPATH 

### LINKED ISSUE #37183: [vcpkg-tool] After 2ac6ba17 RUNPATH on built dynamic libraries is not set
**Describe the bug**
We use `VCPKG_FIXUP_ELF_RPATH` in our triplets to have vcpkg set `RUNPATH` to `$ORIGIN` when we build dynamic libraries on Linux. Before `2ac6ba173be85207a7bac4f0f02f5486f9fd4c0f` this works properly, with `2ac6ba173be85207a7bac4f0f02f5486f9fd4c0f` it does not.

**Environment**
- OS: Ubuntu 22.04 LTS
- Compiler: N/A

**To Reproduce**
1. Set up custom linux triplet with `set(VCPKG_FIXUP_ELF_RPATH ON)` and `set(VCPKG_LIBRARY_LINKAGE dynamic)`

This is ours, but any should work
```
# Notably we want ffmpeg to be built as dynamic library to comply with
# its licence, but build everything else as a static library.

set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_CMAKE_SYSTEM_NAME Linux)
set(VCPKG_FIXUP_ELF_RPATH ON)

set(VCPKG_C_FLAGS "-std=gnu17")
set(VCPKG_CXX_FLAGS "-std=c++17")

if (${PORT} MATCHES "ffmpeg")
  set(VCPKG_LIBRARY_LINKAGE dynamic)
else ()
  set(VCPKG_LIBRARY_LINKAGE static)
endif ()

if (NOT ${PORT} MATCHES "ffmpeg")
  set(VCPKG_C_FLAGS "${VCPKG_C_FLAGS} -fvisibility=hidden -fvisibility-inlines-hidden")
  set(VCPKG_CXX_FLAGS "${VCPKG_CXX_FLAGS} -fvisibility=hidden -fvisibility-inlines-hidden")
endif()
```

2. `./vcpkg install ffmpeg` (ffmpeg is issue for us, I did not check whether this reproduces on other libraries)
3. `readelf -d path-to-ffmpeg/libavcodec.so | grep "PATH"`

There will be no output.

**Expected behavior**
The `RUNPATH` of `libavcodec.so` should be set to `$ORIGIN`, so the last step above should provide some output.

**Additional context**
Technically we use manifest build, but I expect that this will be reproducible with plain tool invocation as well, and it is less annoying to set up.

### PR DESCRIPTION
**Pull request by BillyONeal**
... and don't fetch patchelf unless we actually need it. For example cmake helper ports have no need to fetch patchelf.

In https://github.com/microsoft/vcpkg/pull/36056 , things were changed to unconditionally patchelf when targeting Linux. Unfortunately that broke --only-downloads a lot of the time. This fixes that.

Also contains @Osyotr 's fixes from https://github.com/microsoft/vcpkg/pull/37190 to coalesce world rebuilds a bit, so repeating comments from there:

Fixes https://github.com/microsoft/vcpkg/issues/37183
Towards https://github.com/microsoft/vcpkg/issues/25668

### CODE REVIEW

**Comment by dg0yt** [comment]
Note that you must ensure that `vcpkg_find_acquire_program(PATCHELF)` is called in download mode in order to have it available in disconnected operation.

I wonder if the result of `uname -m` shouldn't be cached, early, for the current run. If not already known by the tool.

**Comment by Osyotr** [comment]
> Looking at the logs it seems like the `REMOVE_DUPLICATES` call needs to be later in the fixup script.

It's harmless but would be cool to fix.
`Adjusted RPATH of '/mnt/vcpkg-ci/p/hdf5_x64-linux/tools/hdf5/gif2h5-shared' (From '' -> To '$ORIGIN:$ORIGIN/../../lib:$ORIGIN/../../lib:$ORIGIN/../lib:$ORIGIN')`

**Comment by BillyONeal** [comment]
> It's harmless but would be nice to fix. `Adjusted RPATH of '/mnt/vcpkg-ci/p/hdf5_x64-linux/tools/hdf5/gif2h5-shared' (From '' -> To '$ORIGIN:$ORIGIN/../../lib:$ORIGIN/../../lib:$ORIGIN/../lib:$ORIGIN')`

I get `$ORIGIN:$ORIGIN/../../lib` but why `$ORIGIN/../lib` ?

**Comment by Neumann-A** [comment]
> I get $ORIGIN:$ORIGIN/../../lib but why $ORIGIN/../lib ?

Unix structure. If you are in `/bin` you need `../lib`. The real question here is how does it go from `""` to 4 entries since only two should be added.

**Comment by BillyONeal** [comment]
> Unix structure. If you are in `/bin` you need `../lib`. The real question here is how does it go from `""` to 4 entries since only two should be added.

Can you double check the test I added then since there's clearly something I'm misunderstanding here

**Comment by Neumann-A** [comment]
```
-- Adjusted RPATH of '/mnt/vcpkg-ci/p/llvm_x64-linux/debug/lib/LLVMPolly.so' (From '' -> To '$ORIGIN')
-- Adjusted RPATH of '/mnt/vcpkg-ci/p/llvm_x64-linux/debug/lib/libLTO.so.17' (From '' -> To '$ORIGIN:$ORIGIN/../lib')
```
I feel like there is some variable being reused between runs.

**Comment by Neumann-A** [comment]
Ah the message is wrong:
`message(STATUS "Adjusted RPATH of '${elf_file}' (From '${org_rpath}' -> To '${new_rpath}')")`
needs to be changed to:
`message(STATUS "Adjusted RPATH of '${elf_file}' (From '${readelf_output}' -> To '${new_rpath}')")`

the refactor broke it.

**Comment by BillyONeal** [comment]
> Ah the message is wrong: `message(STATUS "Adjusted RPATH of '${elf_file}' (From '${org_rpath}' -> To '${new_rpath}')")` needs to be changed to: `message(STATUS "Adjusted RPATH of '${elf_file}' (From '${readelf_output}' -> To '${new_rpath}')")`
> 
> the refactor broke it.

Fixed!

**Comment by Neumann-A** [comment]
```
Adjusted RPATH of '/mnt/vcpkg-ci/p/hdf5_x64-linux/tools/hdf5/gif2h5' (From '/mnt/vcpkg-ci/installed/x64-linux/lib:$ORIGIN/../lib:$ORIGIN/' -> To '$ORIGIN:$ORIGIN/../../lib:$ORIGIN/../lib')
```
looks ok now. It is just keeping already existing rpath settings.

**Pull request merged**
