### PR TITLE
[libsrtp] Add Exported CMake Targets for LibSRTP

### PR DESCRIPTION
**Pull request by SE2Dev**
**Describe the pull request**

This pull request adds `libsrtp-config.cmake` to the `libsrtp` port, which allows users to do the following in CMake:
```cmake
find_package(libsrtp REQUIRED)
# ...
target_link_libraries(main PRIVATE LibSRTP::srtp2)
```

Additionally, I've updated the deprecated helper function usage for the `libsrtp` port.

- #### What does your PR fix?  
  Fixes the lack of CMake exports for `libsrtp`, and serves as a prerequisite for #20722.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  unchanged, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  I believe so.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Review by NancyLi1013 — CHANGES_REQUESTED** [review]

**Comment by SE2Dev** [comment]
I should point out that at least part of this pull request will no longer be necessary if the changes to upstream are accepted. If that happens, I'll update this request and #20722 accordingly.

**Comment by LilyWangLL** [comment]
@SE2Dev The upstream PR has been merged. Could you please merge fix on upstream to this PR.

**Comment by SE2Dev** [comment]
@LilyWangLL Yes, although there's still no actual LibSRTP _release_ that includes the merged changes. Should I selectively pull CMake files from a more current snapshot during the configuration process, or wait until there's a release that includes them?

**Comment by LilyWangLL** [comment]
> @LilyWangLL Yes, although there's still no actual LibSRTP _release_ that includes the merged changes. Should I selectively pull CMake files from a more current snapshot during the configuration process, or wait until there's a release that includes them?

You can download patch file from https://patch-diff.githubusercontent.com/raw/cisco/libsrtp/pull/573.diff at runtime by `vcpkg_download_distfile`. Then add it to `PATCHES` in `vcpkg_from_github`.

**Comment by SE2Dev** [comment]
I just pushed the requested changes. Since the path was never corrected in the original pull request before it was merged, I had to explicitly define the `CONFIG_PATH` for `vcpkg_cmake_config_fixup`.

**Review by BillyONeal — APPROVED** [review]
I note upstream has already merged this.

**Comment by BillyONeal** [comment]
I'm not sure why CLA bot is unhappy; have you signed a Microsoft CLA before?

**Comment by BillyONeal** [comment]
It looks like CLA bot is wedged in many places :(

**Comment by SE2Dev** [comment]
It seems to be complaining about the fact that there's no license field in `vcpkg.json`. LibSRTP has its own [license file](https://github.com/cisco/libsrtp/blob/main/LICENSE) in its repo; assuming I'm reading [this](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/manifest-files.md#license] correctly, the license field should be set to `null`, correct?

**Comment by BillyONeal** [comment]
That's a different bot; a suggestion but not a requirement. CLA is a requirement though. I have seen that wedged in other repos too; will keep you posted

**Comment by BillyONeal** [comment]
Tried merging to see if that kicks the bot

**Comment by BillyONeal** [comment]
@SE2Dev Can you try manually visiting https://cla.opensource.microsoft.com/microsoft/vcpkg?pullRequest=20720 ?

**Comment by BillyONeal** [comment]
Closing and reopening the PR kicked the bot to be green :)

**Comment by SE2Dev** [comment]
> Closing and reopening the PR kicked the bot to be green :)

Haha, nice! Apparently, I already signed the CLA at some point, so that shouldn't have been the problem.

**Comment by BillyONeal** [comment]
Thanks for the fix!

**Pull request merged**
