### PR TITLE
[gts] Support for build with cmake in unix

### PR DESCRIPTION
**Pull request by JackBoosY**
The current `CMakeLists.txt` does not support building in UNIX, so add support.

Realted: #9784.

Note: this port doesn't contain any features.

### CODE REVIEW

**Review by PhoebeHui — APPROVED** [review]

**Review by dan-shaw — APPROVED** [review]

**Comment by dan-shaw** [comment]
@JackBoosY CI fails on Linux

**Comment by JackBoosY** [comment]
@dan-shaw Re-run and the test was successful.

**Comment by dan-shaw** [comment]
Should the CI baseline be updated and remove `linux=fail`?

**Comment by JackBoosY** [comment]
@dan-shaw Ready to merge now.

**Pull request merged**
