### PR TITLE
[materialx] Add new port

### PR DESCRIPTION
**Pull request by NancyLi1013**
This port currently doesn't support `arm, arm64  and uwp`.
On Linux platform, need to install these libraries: `libx11    libxt    freeglut3`

Related issue #8780 
No feature need to test.

### CODE REVIEW

**Comment by ras0219-msft** [comment]
@zhonglingxiao, does this portfile work for you?

**Review by JackBoosY — APPROVED** [review]

**Comment by NancyLi1013** [comment]
Please feel free to ask us to reopen this PR if you need it.

**Pull request closed without merging**
