### PR TITLE
[pystring] rename `libpystring` to `pystring`

### PR DESCRIPTION
**Pull request by jixingcn**
**Describe the pull request**

I installed the `pystring`, but the CMake project can't find the `pystringConfig.cmake`.
Rename the `libpystring` to `pystring` like its port name and avoid linking incorrectly.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  windows, Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Review by JackBoosY — APPROVED** [review]

**Review by ras0219-msft — APPROVED** [review]
While reviewing, I went ahead and fixed up a few things:
1. Simplified the CMake (avoid excessive variables)
2. Apply our policy of prefixing unofficial packages with `unofficial::`
3. Update to use `vcpkg-cmake` and `vcpkg-cmake-config`

This LGTM now -- thanks for the PR!

**Review by jixingcn — COMMENTED** [review]
Thanks a lot.

**Comment by jixingcn** [comment]
> While reviewing, I went ahead and fixed up a few things:
> 
> 1. Simplified the CMake (avoid excessive variables)
> 2. Apply our policy of prefixing unofficial packages with `unofficial::`
> 3. Update to use `vcpkg-cmake` and `vcpkg-cmake-config`
> 
> This LGTM now -- thanks for the PR!

I just test this. But it has a problem.

`OpenColorIO` depends `pystring::pystring` in `target_link_libraries`. My project depends `OpenColorIO`.
When configure my project by cmake, it reports some error message:
```
CMake Error at D:/develop/vcpkg/scripts/buildsystems/vcpkg.cmake:574 (_add_library):
  Target "myproject" links to target "pystring::pystring" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```

Then I try to change the `pystring::pystring` to `unofficial::pystring::pystring` in `OpenColorIO`.
I failed to install the `OpenColorIO` like this: 😢 
```
CMake Error at D:/develop/vcpkg/scripts/buildsystems/vcpkg.cmake:574 (_add_library):
  Target "OpenColorIO" links to target "unofficial::pystring::pystring" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
```

Am I wrong? @ras0219-msft

**Review by ras0219-msft — APPROVED** [review]
Good point, it seems that this project is related enough to opencolorio to claim that `pystring::pystring` is "official". This LGTM, thanks for the PR!

(see https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/3c2c8ba3353a8c90068b0bab82ed1e26eaea0db3/share/cmake/modules/Findpystring.cmake)

**Comment by jixingcn** [comment]
> Good point, it seems that this project is related enough to opencolorio to claim that `pystring::pystring` is "official". This LGTM, thanks for the PR!
> 
> (see https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/3c2c8ba3353a8c90068b0bab82ed1e26eaea0db3/share/cmake/modules/Findpystring.cmake)

Thanks a lot.

**Comment by dg0yt** [comment]
> Good point, it seems that this project is related enough to opencolorio to claim that `pystring::pystring` is "official". This LGTM, thanks for the PR!

FAIL.
- Not upstreamed.
- pystring port exports the top-level include dir (bad enough!), making incompatible with opencolorio (noticed in #46779).
- Fixing it properly will break users.

**Pull request merged**
