### PR TITLE
[gamenetworkingsockets] update version to 1.4.0 

### PR DESCRIPTION
**Pull request by zpostfacto**
**Describe the pull request**

- #### What does your PR fix?  
Add version 1.4.0 of gamenetworkingsockets

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
No.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
As best as I can tell!

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by JonLiu1993** [comment]
@fletcherdvalve ,Thanks for your pr, could you please sign CLA first?

**Comment by fletcherdvalve** [comment]
CLA signed

**Comment by JonLiu1993** [comment]
@fletcherdvalve ,If this pr is ready for review, please let me know, thanks !

**Comment by JonLiu1993** [comment]
@fletcherdvalve ,Is this pr ready for review?

**Comment by JonLiu1993** [comment]
Ping @fletcherdvalve for response, Is this pr still work on?

**Review by JonLiu1993 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the update!

**Pull request merged**
