### PR TITLE
[CPR] Update to version 1.9.0

### LINKED ISSUE #25237: [CPR]  Update to 1.8.3 (again, see details)
Library name: CPR

New version number: 1.8.3

Other information that may be useful:
1.8.3 is currently included but there where features added to 1.8.3 after the inclusion into vcpkg. (Like ReserveSize and others)

### LINKED ISSUE #25833: [CPR] update to 1.9.0
Library name: CPR

New version number: 1.9.0

Bugfixes and usability. Last version for cpp11.

### PR DESCRIPTION
**Pull request by JonLiu1993**
Fix #25237
Update cpr to version 1.9.0

All features are tested successfully in the following triplet:
- x86-windows
- x64-windows
- x64-windows-stataic

### CODE REVIEW

**Comment by JonLiu1993** [comment]
Drafting this PR and waiting for the next release I will update this PR

**Comment by FrankXie05** [comment]
There is a new version update https://github.com/libcpr/cpr/commit/e53437b79965e5de9e9bef5a3e7ec609587268d6

**Comment by UmarAhmed129** [comment]
When will the pull request be merged? [vcpkg ](https://vcpkg.io/en/packages.html) still shows the old version 1.7.2.

@JonLiu1993 I do not see x86-windows-static triplet. I need to work on a 32 bit project.

**Comment by JonLiu1993** [comment]
> When will the pull request be merged? [vcpkg ](https://vcpkg.io/en/packages.html) still shows the old version 1.7.2.
> 
> When searching from the command line vcpkg search cpr it returns version 1.8.3
> 
> ` E:\vcpkg>vcpkg search cpr cpr 1.8.3 C++ Requests is a simple wrapper around libcurl inspired by the excellent ... cpr[ssl] Enable SSL support sleepy-discord[cpr] Use CPR library for handling HTTPS The result may be outdated. Run `git pull ` to get the latest results.
> 
> If your port is not listed, please open an issue at and/or consider making a pull request: https://github.com/Microsoft/vcpkg/issues `
> 
> @JonLiu1993 I do not see x86-windows-static triplet. I need to work on a 32 bit project.

@UmarAhmed129, Thanks for your reminder, I am fixing the ci error, expect it to be fixed today or tomorrow

**Review by FrankXie05 — APPROVED** [review]

**Comment by JonLiu1993** [comment]
Version 1.8.4 have a error in x64-osx
````
/Users/vagrant/Data/buildtrees/cpr/src/09587268d6-6a5973052f.clean/cpr/util.cpp:185:13: error: unknown pragma ignored [-Werror,-Wunknown-pragmas]
#pragma GCC push_options   // g++
            ^
/Users/vagrant/Data/buildtrees/cpr/src/09587268d6-6a5973052f.clean/cpr/util.cpp:186:13: error: unknown pragma ignored [-Werror,-Wunknown-pragmas]
#pragma GCC optimize("O0") // g++
            ^
/Users/vagrant/Data/buildtrees/cpr/src/09587268d6-6a5973052f.clean/cpr/util.cpp:188:9: error: unknown pragma ignored [-Werror,-Wunknown-pragmas]
#pragma optimize("", off)  // MSVC
        ^
/Users/vagrant/Data/buildtrees/cpr/src/09587268d6-6a5973052f.clean/cpr/util.cpp:189:17: error: cannot initialize a parameter of type 'void *' with an rvalue of type 'const std::basic_string<char>::value_type *' (aka 'const char *')
    std::memset(s.data(), 0, s.length());
                ^~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/string.h:74:20: note: passing argument to parameter '__b' here
void    *memset(void *__b, int __c, size_t __len);
                      ^
/Users/vagrant/Data/buildtrees/cpr/src/09587268d6-6a5973052f.clean/cpr/util.cpp:190:9: error: unknown pragma ignored [-Werror,-Wunknown-pragmas]
#pragma optimize("", on)   // MSVC
        ^
/Users/vagrant/Data/buildtrees/cpr/src/09587268d6-6a5973052f.clean/cpr/util.cpp:192:13: error: unknown pragma ignored [-Werror,-Wunknown-pragmas]
#pragma GCC pop_options    // g++
````

Upstream have fixed this error in the latest version 1.9.0, So i update the cpr to the latest version 1.9.0 fix this ci error #https://github.com/libcpr/cpr/pull/776

**Comment by UmarAhmed129** [comment]
@JonLiu1993 

In the 12 successful checks passed I do not see 

1. x86_windows_static
2. x86_windows_static_md

I am concerned since I have to work on a 32 bit project linking statically.

I hope I will see those static libraries from cpr 1.9.0 from vcpkg whenever you are done.

**Comment by JonLiu1993** [comment]
> @JonLiu1993
> 
> In the 12 successful checks passed I do not see
> 
> 1. x86_windows_static
> 2. x86_windows_static_md
> 
> I am concerned since I have to work on a 32 bit project linking statically.
> 
> I hope I will see those static libraries from cpr 1.9.0 from vcpkg whenever you are done.

@UmarAhmed129 ,
- x86_windows_static
- x86_windows_static_md
 is community-triplet, not our official triplet. You can try to use it locally after the 1.9.0 merge. If you have any problems, you can submit an issue to us.

**Pull request merged**
