### PR TITLE
[vcpkg] remove warning level flag from Windows toolchain

### PR DESCRIPTION
**Pull request by data-queue**
Avoids globally setting warnings for Windows. Warnings should be controlled by a port or project basis. Additionally globally set warnings can interfere with port or project level warnings.

### CODE REVIEW

**Comment by Neumann-A** [comment]
The prime counter example here is werror. I disagree with this approach, warnings are a toolchain setting.

Could you please explain why you are changing it in more detail and why you are forcing everyone to rebuild.

**Comment by BillyONeal** [comment]
@ras0219-msft
@data-queue
@AugP
@JavierMatosD
@vicroms
and I

discussed this today.

> I disagree with this approach, warnings are a toolchain setting.

We agree that warnings are a toolchain setting. This change is intended to reflect vcpkg's normal policy of not trying to show warnings for ports because downstream port customers generally can't do anything about the resulting warnings.

**Comment by BillyONeal** [comment]
> why you are forcing everyone to rebuild.

We agree that we should merge this with some other change that invalidates most things.

**Review by BillyONeal — APPROVED** [review]

**Comment by BillyONeal** [comment]
I cancelled this run because the fleet is behind. I'm going to cherry pick testing for this into https://github.com/microsoft/vcpkg/pull/39325

**Comment by BillyONeal** [comment]
I'm going to close this as it's effectively merged into https://github.com/microsoft/vcpkg/pull/39325 ; I'll make sure you're listed as a co-author in the merge commit there. Thanks!

**Pull request closed without merging**
