### PR TITLE
[vcpkg] Fix default x86 platform of msbuild in vcpkg_install_msbuild

### LINKED ISSUE #28076: vcpkg_install_msbuild PLATFORM incorrect default parameter
Default parameter of vcpkg_install_msbuild PLATFORM is not ${TRIPLET_SYSTEM_ARCH}.

https://github.com/microsoft/vcpkg/blob/266e4910c6c6a2fe1b20a1bdb5cec4e16f190f01/scripts/cmake/vcpkg_install_msbuild.cmake#L23

### PR DESCRIPTION
**Pull request by Cheney-W**
**Describe the pull request**

- #### What does your PR fix?
  Fixes https://github.com/microsoft/vcpkg/issues/28076

  The c++ project automatically created by Visual Studio includes the following default Configuration and Platform:
```
  	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|x64 = Debug|x64
		Debug|x86 = Debug|x86
		Release|x64 = Release|x64
		Release|x86 = Release|x86
	EndGlobalSection
```
   This means that during msbuild, the `/p: Platform` parameter only accepts `x86` or `x64`. 
   However, according to our current settings in `vcpkg_install_msbuild.cmake`, `/p:Platform` will be set to `Win32` when install port with x86 triplet, which will cause the following errors:
```
   error MSB4126: The specified solution configuration "Release|Win32" is invalid.
   error MSB4126: The specified solution configuration "Debug|Win32" is invalid.
```
   For fixing this issue, I modify the value from Win32 to x86.

   VS project supports setting the platform to Win32, but this is not the default and needs to be set manually. 
   Although Debug|Win32 and Debug|x86 actually point to the same setting, however, the value of `/p: Platform` corresponding to them in the msbuild command is different.
```
GlobalSection(SolutionConfigurationPlatforms) = preSolution
    Debug|Win32 = Debug|Win32
    Debug|x86 = Debug|x86
EndGlobalSection
GlobalSection(ProjectConfigurationPlatforms) = postSolution
    {B760FBDE-F771-4EFA-8FE4-ABB9C80F9A24}.Debug|Win32.ActiveCfg = Debug|Win32
    {B760FBDE-F771-4EFA-8FE4-ABB9C80F9A24}.Debug|Win32.Build.0 = Debug|Win32
    {B760FBDE-F771-4EFA-8FE4-ABB9C80F9A24}.Debug|x86.ActiveCfg = Debug|Win32
    {B760FBDE-F771-4EFA-8FE4-ABB9C80F9A24}.Debug|x86.Build.0 = Debug|Win32
EndGlobalSection
```

### CODE REVIEW

**Comment by BillyONeal** [comment]
> This means that during msbuild, the `/p: Platform` parameter only accepts `x86` or `x64`.

This doesn't repro for me. I just did "new console app" and I get:

image

**Comment by Cheney-W** [comment]
You need open the .sln file instead of the .vcxproj file.

**Comment by BillyONeal** [comment]
> You need to open the .sln file instead of the .vcxproj file.

`vcpkg_install_msbuild` is usually expected to be given `.vcxproj` rather than `.sln` -- that's why the value is "Win32" rather than "x86": that's the default for C++ projects.

This is why there is an argument for `PLATFORM` at all.

Let's look at current callers of `vcpkg_install_msbuild`.

Callers that affirmatively set Win32:

* `3fd`: https://github.com/microsoft/vcpkg/blob/163fe7bd3d67c41200617caaa245b5ba2ba854e6/ports/3fd/portfile.cmake#L3
* `ace`: https://github.com/microsoft/vcpkg/blob/163fe7bd3d67c41200617caaa245b5ba2ba854e6/ports/ace/portfile.cmake#L69
* `activemq-cpp`: https://github.com/microsoft/vcpkg/blob/163fe7bd3d67c41200617caaa245b5ba2ba854e6/ports/activemq-cpp/portfile.cmake#L69
* `easyhook`: https://github.com/microsoft/vcpkg/blob/163fe7bd3d67c41200617caaa245b5ba2ba854e6/ports/easyhook/portfile.cmake#L13
* `hunspell`: https://github.com/microsoft/vcpkg/blob/163fe7bd3d67c41200617caaa245b5ba2ba854e6/ports/hunspell/portfile.cmake#L22
* `mp3lame`: https://github.com/microsoft/vcpkg/blob/163fe7bd3d67c41200617caaa245b5ba2ba854e6/ports/mp3lame/portfile.cmake#L27

Callers that affirmatively set x86:

* `ecsutil`: https://github.com/microsoft/vcpkg/blob/163fe7bd3d67c41200617caaa245b5ba2ba854e6/ports/ecsutil/portfile.cmake#L2
* `ngspice`: https://github.com/microsoft/vcpkg/blob/163fe7bd3d67c41200617caaa245b5ba2ba854e6/ports/ngspice/portfile.cmake#L38-L39
* `ocilib`: https://github.com/microsoft/vcpkg/blob/163fe7bd3d67c41200617caaa245b5ba2ba854e6/ports/ocilib/portfile.cmake#L12
* `rsasynccpp`: https://github.com/microsoft/vcpkg/blob/163fe7bd3d67c41200617caaa245b5ba2ba854e6/ports/rsasynccpp/portfile.cmake#L30
* `shiftmedia-libgcrypt`: https://github.com/microsoft/vcpkg/blob/163fe7bd3d67c41200617caaa245b5ba2ba854e6/ports/shiftmedia-libgcrypt/portfile.cmake#L72
* `shiftmedia-libgnutls`: https://github.com/microsoft/vcpkg/blob/163fe7bd3d67c41200617caaa245b5ba2ba854e6/ports/shiftmedia-libgnutls/portfile.cmake#L142
* `shiftmedia-libgpg-error`: https://github.com/microsoft/vcpkg/blob/163fe7bd3d67c41200617caaa245b5ba2ba854e6/ports/shiftmedia-libgpg-error/portfile.cmake#L44

Callers where the correct value is Win32 because that is currently the default. These are likely to be broken by this PR:

* `ideviceinstaller`: https://github.com/microsoft/vcpkg/blob/master/ports/ideviceinstaller/portfile.cmake
* `idevicerestore`: https://github.com/microsoft/vcpkg/blob/master/ports/idevicerestore/portfile.cmake
* `libirecovery`: https://github.com/microsoft/vcpkg/blob/master/ports/libirecovery/portfile.cmake
* `libmicrohttpd`: https://github.com/microsoft/vcpkg/blob/master/ports/libmicrohttpd/portfile.cmake
* `libosip2`: https://github.com/microsoft/vcpkg/blob/master/ports/libosip2/portfile.cmake
* `libusb`: https://github.com/microsoft/vcpkg/blob/master/ports/libusb/portfile.cmake
* `monkeys-audio`: https://github.com/microsoft/vcpkg/blob/master/ports/monkeys-audio/portfile.cmake
* `pbc`: https://github.com/microsoft/vcpkg/blob/master/ports/pbc/portfile.cmake
* `python3`: https://github.com/microsoft/vcpkg/blob/master/ports/python3/portfile.cmake
* `scintilla`: https://github.com/microsoft/vcpkg/blob/master/ports/scintilla/portfile.cmake
* `sdl1`: https://github.com/microsoft/vcpkg/blob/master/ports/sdl1/portfile.cmake
* `tracy`: https://github.com/microsoft/vcpkg/blob/master/ports/tracy/portfile.cmake
* `libusbmuxd`: https://github.com/microsoft/vcpkg/blob/master/ports/libusbmuxd/portfile.cmake
* `zeroc-ice`: https://github.com/microsoft/vcpkg/blob/master/ports/zeroc-ice/portfile.cmake

Callers that don't care:

* `libfabric` is x64 only: https://github.com/microsoft/vcpkg/blob/163fe7bd3d67c41200617caaa245b5ba2ba854e6/ports/libfabric/portfile.cmake#L21

So 20 ports want Win32, and only 7 want x86, so I think leaving this default as Win32 is correct.

**Comment by BillyONeal** [comment]
It's also notable that undoing the Win32 selection with 1 line is possible but the reverse is not.

**Comment by Cheney-W** [comment]
@BillyONeal Thank you for your detailed reply.

> vcpkg_install_msbuild is usually expected to be given .vcxproj rather than .sln

This is just what we expect. But in fact, many ports pass `.sln` instead of `.vcxproj` to the `PROJECT_SUBPATH` parameter. In addition, our [document](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_install_msbuild.md#project_subpath) also said that both are OK, and there is no tendency. 

> So 20 ports want Win32, and only 7 want x86, so I think leaving this default as Win32 is correct.

Your reason is very good. I agree with your decision. 
Also, we do not need to consider the port which uses the `PLATFORM ${xxx}` parameter in `vcpkg_install_msbuild()`, because the part we modify is for the port that does not use this parameter.

The last question is about this part of the document: `[PLATFORM <${TRIPLET_SYSTEM_ARCH}>]`. 
The description here is not accurate and cannot explain why win32 is used as a parameter on x86 triplet. This is also the concern of the user who report the https://github.com/microsoft/vcpkg/issues/28076. If we maintain the status quo of `vcpkg_install_msbuild`, the document part will have to be modified.
What do you suggest about documentation?

**Comment by BillyONeal** [comment]
>What do you suggest about documentation?

I made a PR fixing the documentation https://github.com/microsoft/vcpkg/pull/28189

Thanks!

**Comment by Cheney-W** [comment]
Close this PR because https://github.com/microsoft/vcpkg/pull/28189 is more reasonable and effective.

**Pull request closed without merging**
