### PR TITLE
[many ports] Add supports

### LINKED ISSUE #12390: vcpkg install atkmm error
Computing installation plan...
The following packages will be built and installed:
    atkmm[core]:x64-linux
Starting package 1/1: atkmm:x64-linux
Building package atkmm[core]:x64-linux...
-- Note: atkmm only supports dynamic library linkage. Building dynamic library.
-- Using cached /home/ggx/Documents/vcpkg/downloads/atkmm-2.24.2.tar.xz
-- Cleaning sources at /home/ggx/Documents/vcpkg/buildtrees/atkmm/src/atkmm-2-de808b48b0.clean. Pass --editable to vcpkg to reuse sources.
-- Extracting source /home/ggx/Documents/vcpkg/downloads/atkmm-2.24.2.tar.xz
-- Applying patch fix_properties.patch
-- Applying patch fix_charset.patch
-- Using source at /home/ggx/Documents/vcpkg/buildtrees/atkmm/src/atkmm-2-de808b48b0.clean
-- Building /home/ggx/Documents/vcpkg/buildtrees/atkmm/src/atkmm-2-de808b48b0.clean/MSVC_Net2013/atkmm.sln for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: msbuild /home/ggx/Documents/vcpkg/buildtrees/atkmm/src/atkmm-2-de808b48b0.clean/MSVC_Net2013/atkmm.sln /p:Configuration=Release /t:atkmm /p:Platform=x64 /p:PlatformToolset=external /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion= /p:VcpkgManifestInstall=false /m /p:ForceImportBeforeCppTargets=/home/ggx/Documents/vcpkg/scripts/buildsystems/msbuild/vcpkg.targets /p:VcpkgTriplet=x64-linux /p:VcpkgCurrentInstalledDir=/home/ggx/Documents/vcpkg/installed/x64-linux
    Working Directory: /home/ggx/Documents/vcpkg/buildtrees/atkmm/x64-linux-rel
    Error code: No such file or directory
    See logs for more information:

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_msbuild.cmake:121 (vcpkg_execute_required_process)
  ports/atkmm/portfile.cmake:25 (vcpkg_build_msbuild)
  scripts/ports.cmake:76 (include)

Error: Building package atkmm:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: atkmm:x64-linux
  Vcpkg version: 2020.06.15-unknownhash

Additionally, attach any relevant sections from the log files above.

### PR DESCRIPTION
**Pull request by PhoebeHui**
Closes https://github.com/microsoft/vcpkg/issues/12390  https://github.com/microsoft/vcpkg/issues/12830 https://github.com/microsoft/vcpkg/pull/11277#issuecomment-669146773

Add unsupport arch/target to 'Support".

### CODE REVIEW

**Comment by Neumann-A** [comment]
>Add unsupport arch/target to 'Support".

@ras0219 @ras0219-msft @strega-nil : I think the `Supports` field should only be used if a port is not designed to be used on a specific platform and not mean vcpkg is just not currently able to build the port on that platform. Maybe a clear guideline when /how to use the `Supports` field is required.

**Comment by PhoebeHui** [comment]
The I have added the !static to Supports for the 2 ports, however, it doesn't skip in CI, still failed here.

REGRESSION: alembic:x64-windows-static. If expected, add alembic:x64-windows-static=fail to .\scripts\ci.baseline.txt.
REGRESSION: avisynthplus:x64-windows-static. If expected, add avisynthplus:x64-windows-static=fail to .\scripts\ci.baseline.txt.

**Comment by BillyONeal** [comment]
> The I have added the !static to Supports for the 2 ports, however, it doesn't skip in CI, still failed here.

`vcpkg ci x64-windows-static` for some reason isn't turning on the "static" flag when evaluating "supports" expressions. :(

**Review by BillyONeal — APPROVED** [review]

**Review by LilyWangL — APPROVED** [review]

**Review by strega-nil — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
