### PR TITLE
[vcpkg baseline][many ports] Fix build error

### LINKED ISSUE #17980: [wxwidgets] build failure
**Host Environment**
- OS: Windows 10
- Compiler: Visual Studio 2019 16.9.5

**To Reproduce**
`./vcpkg install wxwidgets:x64-windows`

**Failure logs** 

> Building package wxwidgets[core]:x64-windows...
-- Downloading https://github.com/wxWidgets/wxWidgets/archive/9c0a8be1dc32063d91ed1901fd5fcd54f4f955a1.tar.gz -> wxWidgets-wxWidgets-9c0a8be1dc32063d91ed1901fd5fcd54f4f955a1.tar.gz...
-- Extracting source D:/vcpkg2/downloads/wxWidgets-wxWidgets-9c0a8be1dc32063d91ed1901fd5fcd54f4f955a1.tar.gz
-- Applying patch disable-platform-lib-dir.patch
-- Using source at D:/vcpkg2/buildtrees/wxwidgets/src/54f4f955a1-1de49a51d0.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j9
    Working Directory: D:/vcpkg2/buildtrees/wxwidgets/x64-windows-dbg
    See logs for more information:
      D:\vcpkg2\buildtrees\wxwidgets\install-x64-windows-dbg-out.log

> Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:104 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/wxwidgets/portfile.cmake:40 (vcpkg_install_cmake)
  scripts/ports.cmake:141 (include)

> Error: Building package wxwidgets:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: wxwidgets:x64-windows
  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9

> Additionally, attach any relevant sections from the log files above.

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/6498508/install-x64-windows-dbg-out.log)

**Additional context**
None

### PR DESCRIPTION
**Pull request by JackBoosY**
Fix baseline issues, these changes need to fix togather, since they affected each other in CI testing.
 - [X] wxwidgets 
 - [x] mlpack
 - [X] embree2
 - [X] embree3
 - [x] opencv4
 - [x] zxing-cpp
 - [x] dbow2
 - [x] clamav

1. Fix wxwidgets bug:
```
F:\vcpkg\buildtrees\wxwidgets\x86-windows-dbg\libs\stc\cotire\wxscintilla_CXX_prefix.hxx(4): fatal error C1083: Cannot open include file: 'F:\vcpkg\buildtrees\wxwidgets\src\54f4f955a1-1de49a51d0\build\cmake\lib\stc\CONFIG': No such file or directory
```
It's becuase the parameter `wxSCINTILLA_PREC_HEADER` is empty:
```cmake
if(wxBUILD_PRECOMP)
    # The auto-generated header causes undefined members and identifiers in the
    # standard c++ headers when using clang.
    # Do not disable precompiled headers entirely but use the main Scintilla
    # header as prefix header so there is at least a small speedup.
    if ("${CMAKE_CXX_COMPILER_ID}" MATCHES "Clang")
        set(wxSCINTILLA_PREC_HEADER "${wxSOURCE_DIR}/src/stc/scintilla/include/Scintilla.h")
    endif()
    wx_target_enable_precomp(wxscintilla ${wxSCINTILLA_PREC_HEADER})
endif()
```
causes the leaked field `CONFIG` to be set in `set_target_properties` in function `wx_target_enable_precomp`.
Then, `get_property` obtained the property and read its file path, resulting in the generation of the wrong _wxscintilla_CXX_prefix.hxx_:
```cpp
/* cotire.cmake 1.8.0 generated file */
/* F:/vcpkg/buildtrees/wxwidgets/x86-windows-dbg/libs/stc/cotire/wxscintilla_CXX_prefix.hxx */
/* cotire.cmake 1.8.0 generated file */
/* F:/vcpkg/buildtrees/wxwidgets/x86-windows-dbg/libs/stc/cotire/wxscintilla_CXX_prefix.hxx */
#ifdef __cplusplus
#include "F:\vcpkg\buildtrees\wxwidgets\src\54f4f955a1-1de49a51d0\build\cmake\lib\stc\CONFIG"
#endif
```
which is not exist.

2. Fix mlpack configure bug, already fixed in upstream https://github.com/mlpack/mlpack/commit/52e123e56792638c957d0229b001ae14a9e94a75.

### CODE REVIEW

**Comment by JackBoosY** [comment]
@cenit When building opencv4:x86-windows or opencv4:x64-windows, we met a error message:
```
CMake Error at cmake/OpenCVGenConfig.cmake:49 (export):
  export Export set "OpenCVModules" not found.
Call Stack (most recent call first):
  CMakeLists.txt:923 (include)
```
And for opencv4:x64-linux:
```
The following empty directories were found:

    /home/usr/work/vcpkg/packages/opencv4_x64-linux/debug

If a directory should be populated but is not, this might indicate an error in the portfile.
If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:

    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/a/dir" "${CURRENT_PACKAGES_DIR}/some/other/dir")


Found 1 error(s). Please correct the portfile:
    /home/usr/work/vcpkg/ports/opencv4/portfile.cmake
```

Can you please take a look?

Thanks.

**Comment by PhoebeHui** [comment]
Fix embree2/embree3 CI test failures:

```
CMake Error in CMakeLists.txt:
  You have set CMAKE_BACKWARDS_COMPATIBILITY to a CMake version less than
  2.4.  This version of CMake only supports backwards compatibility with
  CMake 2.4 or later.  For compatibility with older versions please use any
  CMake 2.8.x release or lower.
```

Reference https://cmake.org/cmake/help/latest/policy/CMP0001.html#policy:CMP0001

**Comment by JackBoosY** [comment]
The opencv4 issue is `OPENCV_MODULES_BUILD` always be cleaned after insert items.
The `dbow2` and `zxing-cpp` regressions are related to `opencv4` regression.

**Comment by PhoebeHui** [comment]
The opencv4 failures start from https://github.com/microsoft/vcpkg/commit/b369b110b16b149066271a09ee56f1b9dcaec7d6.
Related PR https://github.com/microsoft/vcpkg/pull/17955

**Comment by cenit** [comment]
i saw few days ago that opencv is not even tested in many CI configs... i will take a look and send fixes asap (might take a couple of days, sorry)

**Comment by cenit** [comment]
yeah I can confirm anyway that in the last 24h OpenCV was broken for everybody here on vcpkg.
Again a PR was merged and that broke all my "bleeding edge" pipelines. They are really bleeding....

**Comment by cenit** [comment]
this is making the fix much more urgent also for me

**Comment by cenit** [comment]
#17991 will revert #17955 @JackBoosY

**Review by PhoebeHui — APPROVED** [review]

**Comment by PhoebeHui** [comment]
@dan-shaw, could you help merge this PR?

**Review by PhoebeHui — APPROVED** [review]

**Pull request merged**
