### PR TITLE
[distorm] Update to 3.5.2b

### PR DESCRIPTION
**Pull request by chausner**
**Describe the pull request**

- #### What does your PR fix?  
  Updates distorm to 3.5.2b

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  As before, Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run ./vcpkg x-add-version --all and committed the result?  
  Yes

### CODE REVIEW

**Comment by BillyONeal** [comment]
>D:\buildtrees\distorm\src\3.5.2b-f74091219e.clean\src\textdefs.c(45): error C2106: '=': left operand must be l-value

The failure in CI appears to be a legitimate failure.

**Comment by chausner** [comment]
> > D:\buildtrees\distorm\src\3.5.2b-f74091219e.clean\src\textdefs.c(45): error C2106: '=': left operand must be l-value
> 
> The failure in CI appears to be a legitimate failure.

Should be fixed in 2fa59c6.

**Comment by BillyONeal** [comment]
I was just going to ask you to submit upstream but I see you already did :D. Thanks!

**Comment by BillyONeal** [comment]
Thanks for the version update!

**Pull request merged**
