### PR TITLE
[catch2] Update to 3.1.0

### PR DESCRIPTION
**Pull request by RT2Code**
Update catch2 from 3.0.1 to 3.1.0.
Changelog : https://github.com/catchorg/Catch2/releases/tag/v3.1.0

### CODE REVIEW

**Comment by RT222** [comment]
Since [this commit](https://github.com/catchorg/Catch2/commit/7e4ec432d00ccb082846bf9a74c6d8b48e039ba9), if not built with Bazel support, catch2 call std::getenv. Unfortunately, [UWP doesn't support this function](https://docs.microsoft.com/en-us/cpp/cppcx/crt-functions-not-supported-in-universal-windows-platform-apps?view=msvc-170) and according to the documentation, there's no workaround for it. Should we deprecate the support of UWP for this port, or should we try to patch it?

**Comment by JonLiu1993** [comment]
> 

@RT222 ,Thanks for your pr, we should try to fix it first, and if we can't fix it in the end we can explain why and drop UWP support

**Comment by JonLiu1993** [comment]
@RT222, ping for response.

**Comment by RT222** [comment]
The problem is that I have no experience with UWP whatsoever, and in any case, according to the Microsoft documentation, there's no workaround for this specific issue. Therefore, the only fix I can imagine is to revert the problematic changes with a patch, but this would be ugly and hard to maintain.

**Comment by quyykk** [comment]
Here's a simple patch (that you could also upstream I guess). I didn't test it so no guarantees.

```patch
diff --git a/src/catch2/catch_config.cpp b/src/catch2/catch_config.cpp
index 4465831d..b738edcd 100644
--- a/src/catch2/catch_config.cpp
+++ b/src/catch2/catch_config.cpp
@@ -17,6 +17,9 @@ namespace {
     bool provideBazelReporterOutput() {
 #ifdef CATCH_CONFIG_BAZEL_SUPPORT
         return true;
+#elif defined( WINAPI_FAMILY )
+		// UWP doesn't support environment variables.
+		return false;
 #else
 
 #    if defined( _MSC_VER )
```

**Comment by RT222** [comment]
Thanks @quyykk, I added a patch based on your suggestion to disable the Bazel reporter on UWP. The port builds with success everywhere now.

**Review by JonLiu1993 — APPROVED** [review]

**Comment by JavierMatosD** [comment]
Thanks!

**Pull request merged**
