### PR TITLE
[pcre2] fetch from github

### PR DESCRIPTION
**Pull request by m-kuhn**
**Describe the pull request**

- #### What does your PR fix?  
Fixes current build errors of pcre2 because https://ftp.pcre.org is not reachable. This only changes the download source of the code.
According to https://www.pcre.org/ the home is now github, so there we go get it now.

This does not change the version even though a new one is available but that fails to build at the moment. Step by step.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
Yes

### CODE REVIEW

**Review by JonLiu1993 — APPROVED** [review]

**Comment by Canvis-Me** [comment]
Hello, I got pcre2 hash check error.

Building package pcre2[core]:x64-windows...
-- Downloading https://github.com/PhilipHazel/pcre2/archive/pcre2-10.37.tar.gz -> PhilipHazel-pcre2-pcre2-10.37.t
ar.gz...
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Downloading https://github.com/PhilipHazel/pcre2/archive/pcre2-10.37.tar.gz
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(656)
Error: Failed to download from mirror set:
File does not have the expected hash:
             url : [ https://github.com/PhilipHazel/pcre2/archive/pcre2-10.37.tar.gz ]
       File path : [ D:\vcpkg\downloads\PhilipHazel-pcre2-pcre2-10.37.tar.gz.17232.part ]
   Expected hash : [ f91760a8e0747f52211612fb0e134d685e224d16bd884eb574718d077a586b1fd7b6435d4e3b75c879b12e02b252
467ecc28cdc4bc2903c783dacab089f99c99 ]
     Actual hash : [ f15357d8f5400739f26a32fe03a0759607fd7a282a1a8a2bb169b971a8a00330eff3ba465842c4668ad968e3fd1f
ff4dc7f0631d0af8416947070ff7cd056e6f ]


[DEBUG] Exiting after %s (%d us)

**Comment by c72578** [comment]
- Released zip file of pcre2-10.37:
https://github.com/PhilipHazel/pcre2/releases/download/pcre2-10.37/pcre2-10.37.zip
`SHA512: f91760a8e0747f52211612fb0e134d685e224d16bd884eb574718d077a586b1fd7b6435d4e3b75c879b12e02b252467ecc28cdc4bc2903c783dacab089f99c99`
This is the `Expected hash` above.
- Released tarball of pcre2-10.37:
https://github.com/PhilipHazel/pcre2/releases/download/pcre2-10.37/pcre2-10.37.tar.gz
`SHA512: fa5f7e40fced780142c9780a5839578408a3662433fcea53a01eb5acdc2f319885a248fa0d9c6db62047fccd0fee0ea62d49ea22d4b716f7fe6ed8e13cad11fb`
- File downloaded by this PR using vcpkg_from_github() and REF pcre2-10.37:
https://github.com/PhilipHazel/pcre2/archive/pcre2-10.37.tar.gz
`SHA512: f15357d8f5400739f26a32fe03a0759607fd7a282a1a8a2bb169b971a8a00330eff3ba465842c4668ad968e3fd1fff4dc7f0631d0af8416947070ff7cd056e6f`
This is the `Actual hash` above.

Remark: This should not have passed CI. The difference of the SHA512 between the zip file and the tar.gz must be detected.

**Comment by dg0yt** [comment]
> This should not have passed CI.

I guess this went unnoticed due to "asset caching". If the cache key is just the file name, changes in content don't invalidate the cache. This affects local usage (`downloads` directory) as well CI.

**Comment by m-kuhn** [comment]
> > This should not have passed CI.
> 
> I guess this went unnoticed due to "asset caching".

Before it was a .zip, now a .tar.gz, that shouldn't be affected by caching.
I'm not currently at a keyboard and web interface only won't help with x-add-version.
If someone else could provide a fix that'd be great.

**Comment by JonLiu1993** [comment]
I will submit pr to fix this bug

**Comment by cenit** [comment]
> Remark: This should not have passed CI. The difference of the SHA512 between the zip file and the tar.gz must be detected.

couldn't agree more

**Comment by BillyONeal** [comment]
> > Remark: This should not have passed CI. The difference of the SHA512 between the zip file and the tar.gz must be detected.
> 
> couldn't agree more

The problem is that part of the reason for asset caching is to prevent a failure of an external server from preventing all PR progress, and to prevent very very slow external servers from bringing the big build machines to a halt waiting to download those pieces.

I would love to have the best of both worlds somehow but I don't see obvious solutions.

**Comment by m-kuhn** [comment]
> > > Remark: This should not have passed CI. The difference of the SHA512 between the zip file and the tar.gz must be detected.
> > 
> > 
> > couldn't agree more
> 
> The problem is that part of the reason for asset caching is to prevent a failure of an external server from preventing all PR progress, and to prevent very very slow external servers from bringing the big build machines to a halt waiting to download those pieces.
> 
> I would love to have the best of both worlds somehow but I don't see obvious solutions.

Maybe I'm missing something, but wouldn't it help to make the filename or download url the cache key? Currently it's the file basename or version only?

**Comment by BillyONeal** [comment]
> Maybe I'm missing something, but wouldn't it help to make the filename or download url the cache key? Currently it's the file basename or port version?

Currently it is just the SHA. It was intentionally not tied to a given URI because there are often multiple sources for a given thing. There is probably a middle ground that can be struck here but it's not super obvious...

**Pull request merged**
