### PR TITLE
[plplot] Fix static build issue

### PR DESCRIPTION
**Pull request by PhoebeHui**
Related issue: https://github.com/microsoft/vcpkg/issues/8751
1. Merge content in 001*.patch and 005*patch, and update the patch to set(wxWidgets_DEFINITIONS WXUSINGDLL) when build BUILD_SHARED_LIBS, the original patch set wxWidgets_DEFINITIONS for all triplets, so the plplot[wxwidgets]:x64-windows-static and plplot[wxwidgets]:x86-windows-static build failed. 

2. After above issue fixed, it start to fail with LNK2019 when build plplot[wxwidgets]:x64-windows-static and plplot[wxwidgets]:x86-windows-static, fix this issue by fix_utils.patch.

All features test pass with below triplets:
- [X]  x86-windows
- [X]  x64-windows-static

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by ras0219-msft** [comment]
Which triplet does this fix?

**Comment by PhoebeHui** [comment]
@ras0219-msft, it fix plplot[wxwidgets]:x64-windows-static build issue.

**Pull request merged**
