### PR TITLE
[mongo-cxx-driver] Update

### PR DESCRIPTION
**Pull request by dg0yt**
Complements #27517.

- #### What does your PR fix?
  Updates mongo-cxx-driver.
  Major cleanup.
  Revises dependencies, factors out mnmlstc-core.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  unchanged

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  yes
  However, this port carries a legacy decision which implements ABI alternatives via features.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  yes

### CODE REVIEW

**Comment by dg0yt** [comment]
The vendored mnmlstc is fetched with git via ExternalProject and should be de-vendored into a separate port.

**Comment by LilyWangLL** [comment]
Feature `mongo-cxx-driver[boost]` test pass on x64-windows and x64-linux.
Feature `mongo-cxx-driver[mnmlstc]` test pass on x64-linux.
Feature `mongo-cxx-driver[std-experimental]` test failed on x64-linux with the following error:
```
/home/lily/mongo/buildtrees/mongo-cxx-driver/src/r3.7.0-4cb52076a6.clean/src/mongocxx/../mongocxx/private/client_session.hh:59:68: error: call of overloaded ‘scoped_bson_t(<brace-enclosed initializer list>)’ is ambiguous
   59 |             libbson::scoped_bson_t raw{e.raw_server_error()->view()};
      |                                                                    ^
In file included from /home/lily/mongo/buildtrees/mongo-cxx-driver/src/r3.7.0-4cb52076a6.clean/src/mongocxx/../mongocxx/private/client_session.hh:28,
                 from /home/lily/mongo/buildtrees/mongo-cxx-driver/src/r3.7.0-4cb52076a6.clean/src/mongocxx/bulk_write.cpp:24:
/home/lily/mongo/buildtrees/mongo-cxx-driver/src/r3.7.0-4cb52076a6.clean/src/mongocxx/../mongocxx/private/libbson.hh:79:14: note: candidate: ‘mongocxx::v_noabi::libbson::scoped_bson_t::scoped_bson_t(std::experimental::fundamentals_v1::optional<bsoncxx::v_noabi::view_or_value<bsoncxx::v_noabi::document::view, bsoncxx::v_noabi::document::value> >)’
   79 |     explicit scoped_bson_t(bsoncxx::stdx::optional<bsoncxx::document::view_or_value> doc);
      |              ^~~~~~~~~~~~~
/home/lily/mongo/buildtrees/mongo-cxx-driver/src/r3.7.0-4cb52076a6.clean/src/mongocxx/../mongocxx/private/libbson.hh:64:14: note: candidate: ‘mongocxx::v_noabi::libbson::scoped_bson_t::scoped_bson_t(bsoncxx::v_noabi::document::view_or_value)’
   64 |     explicit scoped_bson_t(bsoncxx::document::view_or_value doc);
      |              ^~~~~~~~~~~~~
/home/lily/mongo/buildtrees/mongo-cxx-driver/src/r3.7.0-4cb52076a6.clean/src/mongocxx/bulk_write.cpp: In member function ‘mongocxx::v_noabi::bulk_write& mongocxx::v_noabi::bulk_write::append(const mongocxx::v_noabi::model::write&)’:
/home/lily/mongo/buildtrees/mongo-cxx-driver/src/r3.7.0-4cb52076a6.clean/src/mongocxx/bulk_write.cpp:72:60: error: call of overloaded ‘scoped_bson_t(bsoncxx::v_noabi::document::value)’ is ambiguous
   72 |             scoped_bson_t options(options_builder.extract());
      |                                                            ^
In file included from /home/lily/mongo/buildtrees/mongo-cxx-driver/src/r3.7.0-4cb52076a6.clean/src/mongocxx/../mongocxx/private/client_session.hh:28,
```

**Comment by dg0yt** [comment]
> Feature `mongo-cxx-driver[std-experimental]` test failed on x64-linux with the following error

This features is left for historical reasons and doesn't need fixing. It uses deprecated pre-C++17 gcc features which won't work with newer (C++17 capable) compilers.

**Review by LilyWangLL — DISMISSED** [review]

**Review by FrankXie05 — DISMISSED** [review]

**Comment by BillyONeal** [comment]
@ maintainers:

I would like a vote on this. `mongo-cxx-driver` is a leaf that has ABI-incompatible-polyfill features. I think we should either (1) take what @dg0yt has done here that preserves backcompat, or (2) always force a particular polyfill. I'm weakly in favor of the latter because that's what we've required other ports to do, but I can see an argument that this is just a version update and it would be good to leave well enough alone. Clearly @dg0yt is at least weakly in favor of this leaving us at 'neutral' total.

Thanks for your contribution!

**Review by BillyONeal — DISMISSED** [review]
Thanks!

**Comment by dg0yt** [comment]
FTR I wouldn't mind to get rid of `std-experimental` (legacy) and `mnmlstc-core` (legacy/unmaintained). This leaves the choice between boost and C++17.

**Comment by BillyONeal** [comment]
@valeriaconde @vicroms @dan-shaw @markle11m @ras0219-msft and I discussed this today.

SF is Strongly favor  
WF Weakly favor  
N Neutral  
WA Weakly Against  
SA Strongly against  

```
We want to preserve the status quo, with multiple features that the portfile accepts in some priority order.
SF WF N WA SA
 0  0 1  1  2

We want to preserve most of the status quo, retaining 'boost' and 'cxx17' capabilities but removing 'mnmlstc-core'.
@dg0yt counted as SF.
SF WF N WA SA
 2  3 2  0  0

We want to fix the port to comply with the current guidelines, removing all features and locking a choice in
portfile.camke, even though this may break existing customers.
SF WF N WA SA
 1  2 0  1  0
```

@ras0219-msft notes that we should engage the boost polyfill in CI because boost is more likely to have breaking changes.

@dg0yt, please change this to a single non-default feature named boost which engages the boost polyfill, and add a `vcpkg-ci` test port which will cause that to be turned on.

**Comment by dg0yt** [comment]
- [x] change this to a single non-default feature named boost which engages the boost polyfill
 - [x] add a vcpkg-ci test port which will cause that to be turned on.

**Review by FrankXie05 — APPROVED** [review]

**Comment by JavierMatosD** [comment]
Thanks!

**Pull request merged**
