### PR TITLE
[c-ares] Fix usage

### LINKED ISSUE #24367: How to deal with this error(target with the same name already exists) ?
```

cmake_minimum_required(VERSION 3.9)
set(CMAKE_CXX_STANDARD 20)

set(CMAKE_TOOLCHAIN_FILE /home/xxxx/vcpkg/scripts/buildsystems/vcpkg.cmake
  CACHE STRING "Vcpkg toolchain file")

project(FormatOutput)

add_executable(main src/main.cpp)
    # src/helloworld.pb.cc
    # src/helloworld.grpc.pb.cc)
  
find_package(gRPC CONFIG REQUIRED)
find_package(Drogon)
target_link_libraries(main PUBLIC gRPC::gpr gRPC::upb gRPC::grpc gRPC::grpc++ re2::re2 c-ares::cares)

-------------------------------------------------------------------------------------------------------------------

-- jsoncpp verson:1.9.5
CMake Error at /home/xxxx/vcpkg/scripts/buildsystems/vcpkg.cmake:606 (_add_library):
  _add_library cannot create imported target "c-ares::cares_static" because
  another target with the same name already exists.
Call Stack (most recent call first):
  /home/xxxx/vcpkg/installed/x64-linux/share/c-ares/c-ares-config.cmake:29 (add_library)
  /home/xxxx/vcpkg/scripts/buildsystems/vcpkg.cmake:816 (_find_package)
  /home/xxxx/vcpkg/installed/x64-linux/share/grpc/modules/Findc-ares.cmake:18 (find_package)
  /home/xxxx/vcpkg/scripts/buildsystems/vcpkg.cmake:816 (_find_package)
  /home/xxxx/share/cmake/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /home/xxxx/vcpkg/installed/x64-linux/share/trantor/TrantorConfig.cmake:41 (find_dependency)
  /home/xxxx/vcpkg/scripts/buildsystems/vcpkg.cmake:816 (_find_package)
  /home/xxxx/share/cmake/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /home/xxxx/vcpkg/installed/x64-linux/share/drogon/DrogonConfig.cmake:40 (find_dependency)
  /home/xxxx/vcpkg/scripts/buildsystems/vcpkg.cmake:816 (_find_package)
  CMakeLists.txt:16 (find_package)
```
drogon and grpc depends on the same library

### PR DESCRIPTION
**Pull request by dg0yt**
- #### What does your PR fix?
  Fixes error on repeated `find_package(c-ares)` (resolves #24367).
  Adds usage file to fix broken output (cf. https://github.com/microsoft/vcpkg/issues/20190).
  Changes license field to MIT-CMU which is a closer but still not exact match.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  unchanged, no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  yes

### CODE REVIEW

**Comment by cenit** [comment]
>   Changes license field to MIT-CMU which is a closer but still not exact match.

what does it mean? just put null and let users read the copyright file, in case we are not sure and/or the field might just trigger a very bad error (from the legal point of view)

**Comment by dg0yt** [comment]
> > Changes license field to MIT-CMU which is a closer but still not exact match.
> 
> what does it mean? just put null and let users read the copyright file, in case we are not sure and/or the field might just trigger a very bad error (from the legal point of view)

I very much agree. However, I don't see that this quality is consistently applied.

**Comment by dg0yt** [comment]
> just put null and let users read the copyright file,

My last attempt to use `null` was overruled without discussion by @strega-nil-ms: https://github.com/microsoft/vcpkg/pull/24206/commits/0f718abd2f9039d6d5c9d6dc08fa675c450ea576
There, the point was not the *core* license, but diverging licenses for some parts (including parts contributed by Microsoft) as mentioned in the copyright file.

**Review by raghavthind2005 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thank you! <3

**Pull request merged**
