### PR TITLE
[vcpkg.cmake] fix find_package not restoring variables correctly.

### LINKED ISSUE #19030: [vcpkg.cmake] find_package override not correctly reseting vars.
The code:
https://github.com/microsoft/vcpkg/blob/1c20782ea44a8c07be931a8b8286044ec175cddc/scripts/buildsystems/vcpkg.cmake#L800-L806
is not correctly unsetting undefined variables. Line 804 should be `unset` instead of `set`

### LINKED ISSUE #27498: [vcpkg.cmake] Variable scoping bug in vcpkg.cmake find_package override
https://github.com/microsoft/vcpkg/blob/c72cefb255ecc04f17d956ff12f9bd4b94111ca0/scripts/buildsystems/vcpkg.cmake#L780-L787

does not correctly restore `ARGS` for chained/recursive `find_package` calls. It assumes `function` scope which doesn't work for `find_package` since it has to be a macro. 

 issue observed in #27279:
 xcb-wrapper:
```
 _find_package(X11 COMPONENTS Xau Xdmcp)
_find_package(${ARGS})
```
The bug above magically transformed `ARGS = EXPAT` instead `XCB` for some (not further traced) reason ;)

### PR DESCRIPTION
**Pull request by Neumann-A**
closes #27498
closes #19030

### CODE REVIEW

**Comment by Neumann-A** [comment]
@BillyONeal: another angle related failure in `x64-linux` here. `ninja: error: '/mnt/vcpkg-ci/installed/x64-linux/lib/libEGL.a', needed by 'exe', missing and no known rule to make it`.

@dg0yt: I assume you already encountered that one.

**Comment by Neumann-A** [comment]
@BillyONeal: I also request a full rebuild here. (which will automatically resolve the x64-linux error)

**Review by LilyWangLL — APPROVED** [review]

**Review by BillyONeal — APPROVED** [review]
@ras0219-msft This LGTM, can you double check?

**Comment by BillyONeal** [comment]
Note to self: If Robert doesn't merge by EOD Wednesday, merge.

**Review by ras0219-msft — APPROVED** [review]
LGTM, I think we could use slightly shorter variable names but all the logic looks correct.

Thank you very much for fixing this issue!

**Pull request merged**
