### PR TITLE
[protobuf] fix dynamic build

### PR DESCRIPTION
**Pull request by Jamlys**
**Describe the pull request**

- #### What does your PR fix?
  Fix dynamic build.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  all, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Basically

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by dg0yt** [comment]
#25744. Please don't close and open new PR's without reason. If you need help, ask.

**Comment by Jamlys** [comment]
> #25744. Please don't close and open new PR's without reason. If you need help, ask.

:( My fault. I am sorry for that.

**Review by Adela0814 — APPROVED** [review]

**Comment by dg0yt** [comment]
This change may be convenient, but patching individual ports for that is not the right way IMO.
If you need binaries working out of the box for x64-linux-dynamic, fix the general rpath/LD_LIBRARY_PATH gap. (That's you other PR.)
In the meantime, use a static host triplet.

**Comment by vicroms** [comment]
depends on #23035

**Pull request closed without merging**
