### PR TITLE
Fix tidy-html5 for non-Windows users

### PR DESCRIPTION
**Pull request by cyyynthia**
Tidy is currently impossible to install on Linux-based OSes due to its portfile attempting to move a .exe file which is specific to Windows.

Should fix the installation of this library for both Linux and MacOS, however I only tested on Linux.

### CODE REVIEW

**Comment by c72578** [comment]
The file **`scripts/ci.baseline.txt`** needs to be updated, now that the builds pass.
Remove:
`tidy-html5:x64-linux=fail`
`tidy-html5:x64-osx=fail`

**Comment by LilyWangL** [comment]
`include(vcpkg_common_functions)` in portfile.cmake is deprecated. Please remove it.

**Comment by Bowser65** [comment]
I've updated the ci.baseline.txt file and removed the deprecated include in portfile.cmake, as suggested. Should be all good!

**Review by LilyWangL — APPROVED** [review]

**Comment by strega-nil** [comment]
Alright, thanks so much @Bowser65 :)

**Pull request merged**
