### PR TITLE
[pthreads] support ARM arch and UWP platform

### PR DESCRIPTION
**Pull request by luncliff**
### What does your PR fix? 

* Check `TRIPLET_SYSTEM_ARCH` contains `arm`.  
  If so, replace macro function `PTW32_PROGCTR` to `__PTW32_PROGCTR` so the build step can advance from preprocessing.

* If `VCPKG_TARGET_IS_UWP`, place `#pragma` to link with `kernel32.lib` and `windowsapp.lib`.  
  Also, inject linker option `/APPCONTAINER` with `LINK` environment variable.

* Migrate `CONTROL` to `vcpkg.json`

### Which triplets are supported/not supported? Have you updated the CI baseline?

All `arm` triplets for Windows (including `uwp`) should become available.

* `arm64-windows`
* `arm-windows`
* `arm64-uwp`
* `x64-uwp`

### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

Wish the change followed the guide well.

~~I used `vcpkg_replace_string` instead of adding a new `.patch` since the source code change is trivial (3 lines in total).~~
Any suggestions will be welcomed :)

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
cc @strega-nil for review this PR again.

poppler regression is not related to this PR.

**Comment by JackBoosY** [comment]
Poppler regression is fixing in https://github.com/microsoft/vcpkg/pull/16356.

**Comment by strega-nil** [comment]
@luncliff please use patches instead of this; it'll be much clearer to future maintainers. if you need any help setting that up, please ask :) (and the way you'd do that is via `set(extra_patches blah.patch bloop.patch)`, and then passing `${extra_patches}` to `PATCHES`)

**Comment by luncliff** [comment]
So I just extracted code changes to a single patch (`fix-arm-uwp.patch`), but seems like the macro [`__cplusplus_winrt`](https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-140) is not provided while NMAKE is running.

I think explicitly specifying `kernel32` won't matter. But `WindowsApp` is for UWP only. 
In this case, should I use `vcpkg_apply_patches`?

```cmake
# portfile.cmake
if(VCPKG_TARGET_IS_UWP)
  vcpkg_apply_patches(SOURCE_PATH ${SOURCE_PATH} PATCHES fix-uwp-pragma.patch)
  # https://docs.microsoft.com/en-us/cpp/build/reference/linker-options
  # https://docs.microsoft.com/en-us/cpp/build/reference/linking#link-environment-variables
  set(ENV{LINK} "/APPCONTAINER")
endif()
# ...
```

**Comment by luncliff** [comment]
For future visitors who are using NMAKE, `nmake-build-arm-uwp-release-out.log` from 7390ef3 was like the following.

You can find well known Win32 API functions are there.

```
	cl /errorReport:none /nologo /MD /I. /DHAVE_CONFIG_H /W3 /O2 /Ob2  /D__PTW32_BUILD_INLINED /D__PTW32_CLEANUP_C -c pthread.c
pthread.c
	rc /d__PTW32_ARCHAMD64 /d__PTW32_RC_MSC /d__PTW32_CLEANUP_C version.rc
Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384

Copyright (C) Microsoft Corporation.  All rights reserved.


	cl /errorReport:none /nologo /LDd /Zi pthread.obj version.res /link /implib:pthreadVC3.lib  /out:pthreadVC3.dll
   Creating library pthreadVC3.lib and object pthreadVC3.exp
pthread.obj : error LNK2019: unresolved external symbol __imp_CloseHandle referenced in function __ptw32_callUserDestroyRoutines
pthread.obj : error LNK2019: unresolved external symbol __imp_DuplicateHandle referenced in function pthread_self
pthread.obj : error LNK2019: unresolved external symbol __imp_RaiseException referenced in function SetThreadName
MSVCRT.lib(helpexcept.obj) : error LNK2001: unresolved external symbol __imp_RaiseException
pthread.obj : error LNK2019: unresolved external symbol __imp_GetLastError referenced in function __ptw32_pop_cleanup
pthread.obj : error LNK2019: unresolved external symbol __imp_SetLastError referenced in function __ptw32_pop_cleanup
pthread.obj : error LNK2019: unresolved external symbol __imp_SetEvent referenced in function __ptw32_callUserDestroyRoutines
pthread.obj : error LNK2019: unresolved external symbol __imp_ResetEvent referenced in function __ptw32_cancelable_wait
pthread.obj : error LNK2019: unresolved external symbol __imp_ReleaseSemaphore referenced in function sem_post
pthread.obj : error LNK2019: unresolved external symbol __imp_WaitForSingleObject referenced in function __ptw32_callUserDestroyRoutines
pthread.obj : error LNK2019: unresolved external symbol __imp_CreateEventA referenced in function __ptw32_callUserDestroyRoutines
pthread.obj : error LNK2019: unresolved external symbol __imp_Sleep referenced in function __ptw32_callUserDestroyRoutines
pthread.obj : error LNK2019: unresolved external symbol __imp_WaitForMultipleObjects referenced in function __ptw32_cancelable_wait
pthread.obj : error LNK2019: unresolved external symbol __imp_GetCurrentProcess referenced in function __ptw32_getprocessors
pthread.obj : error LNK2019: unresolved external symbol __imp_GetCurrentProcessId referenced in function pthread_setaffinity_np
MSVCRT.lib(gs_support.obj) : error LNK2001: unresolved external symbol __imp_GetCurrentProcessId
pthread.obj : error LNK2019: unresolved external symbol __imp_GetCurrentThread referenced in function pthread_self
pthread.obj : error LNK2019: unresolved external symbol __imp_GetCurrentThreadId referenced in function pthread_self
```

**Comment by strega-nil** [comment]
fwiw, in the future you can do:

```cmake
if(VCPKG_TARGET_IS_UWP)
    set(platform_patches fix-arm-uwp.patch)
endif()

vcpkg_from_sourceforge(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO pthreads4w
    FILENAME "pthreads4w-code-v${PTHREADS4W_VERSION}.zip"
    SHA512 49e541b66c26ddaf812edb07b61d0553e2a5816ab002edc53a38a897db8ada6d0a096c98a9af73a8f40c94283df53094f76b429b09ac49862465d8697ed20013
    PATCHES
        ${platform_patches}
)
```

**Comment by JackBoosY** [comment]
Please add the following codes to `ci.baseline.txt`:
```
darknet:arm64-windows
darknet:arm-uwp
fontconfig:x64-uwp
fontconfig:arm-uwp
fontconfig:arm64-windows
```

**Review by JackBoosY — APPROVED** [review]

**Comment by luncliff** [comment]
Fixed some collisions with #17011.

**Comment by JackBoosY** [comment]
Please add `clamav:arm64-windows=fail` to _scripts/ci.baseline.txt_.

**Review by JackBoosY — APPROVED** [review]

**Comment by luncliff** [comment]
> Please add `clamav:arm64-windows=fail` to _scripts/ci.baseline.txt_.

Thanks for the check, @JackBoosY. Applied in 34d4f9e :)

**Pull request merged**
