### PR TITLE
[ms-stl] Add MS-STL port

### PR DESCRIPTION
**Pull request by Neumann-A**
- targets probably need some further adjustment to be actually usable (e.g. removing default VS library on windows etc.; Maybe adding /NODEFAULTLIB?; feel free to change)
- port only builds with VS16.3 (Current Preview)
- to avoid naming conflicts due to VS integration the port installs its headers into include/ms-stl.

for people who want to try this stuff out.

### CODE REVIEW

**Comment by Neumann-A** [comment]
I think I have to completly remove the default CMakeLists.txt because it is just wrong to try build all versions. It should only be one version depending on the build type, static/dynamic and the iterator debug level. They probably are building all flavors due to using VS open folder and switching configurations are a pain with that.

**Comment by Neumann-A** [comment]
Only missing an alias target microsoft::stl which switches between microsoft::libcpmt and microsoft::msvcp_implib depending on the setting of MSVC_RUNTIME_LIBRARY

**Comment by Neumann-A** [comment]
> Error: CMake 3.15 or higher is required.  You are running version 3.14.0

I will probably patch the CMake version down to 3.14 because there is nothing fancy in the script so it should work with 3.14

**Comment by JackBoosY** [comment]
>>>>>>> master

**Pull request closed without merging**
