### PR TITLE
[kinectsdk1] Skip HASH check

### PR DESCRIPTION
**Pull request by JackBoosY**
It seems that the binary of the sdk downloaded by each machine is not consistent. (maybe caused by the microsoft download center?)
```
Installing 1/2 kinectsdk1:x86-windows...
Building kinectsdk1[core]:x86-windows...
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:14 (message):


  File does not have expected hash:

          File path: [ F:/vcpkg/downloads/KinectSDK-v1.8-Setup.exe ]
      Expected hash: [ d7e886d639b4310addc7c1350311f81289ffbcd653237882da7bf3d4074281ed35d217cb8be101579cac880c574dd89c62cd6a87772d60905c446d0be5fd1932 ]
        Actual hash: [ ee8a0f70c86aad80fe214108e315e4550a90ed39f278ce00a7137532174ee5bf3bdeb1d0b499fc5ffdb5e176adecfd68963ee3731e1d2f00d69d32d1b8a3c555 ]
```
image
These timestamp data are not written into the installation package downloaded by my another machine using VS2019.

@BillyONeal Do you know who can double confirm this?

### CODE REVIEW

**Comment by LilyWangLL** [comment]
If `kinectsdk1` changed, does this change need synced up to `kinectsdk2`?

**Comment by JackBoosY** [comment]
> If `kinectsdk1` changed, does this change need synced up to `kinectsdk2`?

We need to double confirm whether we should skip the hash check first.

**Comment by JackBoosY** [comment]
packages which are downloaded from `download.microsoft.com` also has port `msmpi` and `directxsdk`.

**Comment by dg0yt** [comment]
> We need to double confirm whether we should skip the hash check first.

I don't think this is an option at all, unless you check digital signatures.

> It seems that the binary of the sdk downloaded by each machine is not consistent. (maybe caused by the microsoft download center?)

Did you carefully exclude any asset caching effects?

**Comment by JackBoosY** [comment]
> Did you carefully exclude any asset caching effects?

No, 2 exes are directly downloaded.

**Comment by JackBoosY** [comment]
Full size sig:
image

Short size sig:
image

**Comment by JackBoosY** [comment]
I checked it again just now, it disappered. No idea why it happened.
At least this PR is no longer needed.

**Pull request closed without merging**
