### PR TITLE
[sobjectizer] Update to 5.8.2.

### PR DESCRIPTION
**Pull request by eao197**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- ~~[ ] The "supports" clause reflects platforms that may be fixed by this new version.~~
- ~~[ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- ~~[ ] Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Review by BillyONeal — APPROVED** [review]
@eao197 This looks good to me, is there a particular reason it's still Draft?

**Comment by eao197** [comment]
> is there a particular reason it's still Draft?

No. There was a recommendation to make PR as "draft" for vcpkg, and I still follow that recommendation.

**Comment by jimwang118** [comment]
@eao197 If you confirm that the update is completed and there is no need to modify any update content, you can click "Ready for review". We'll review updates and merge them.

**Comment by BillyONeal** [comment]
Okie dokie, sorry for the confusion. We mark things as 'draft' when we are waiting for folks to make changes because it's a thing people can change themselves and helps filter out what people are still working on vs. who needs an active response.

Thanks for the update!

**Pull request merged**
