### PR TITLE
[cppgraphqlgen] Add a port for Microsoft/cppgraphqlgen

### PR DESCRIPTION
**Pull request by wravery**

### CODE REVIEW

**Comment by wravery** [comment]
I had to do a quick rev of the v0.5 tag to fix a CMake break on UNIX. The pull request should work now with the updated hash, but you may need to delete the cached download for `Microsoft-cppgraphqlgen-v0.5.tar.gz` from your local `vcpkg/downloads` directory.

**Comment by ras0219-msft** [comment]
Could you change the ref in `vcpkg_from_github()` to be the commit id then? That will rename the file and also avoid silent hash breaks in the future.

**Comment by wravery** [comment]
All set, verified that it pulls the right archive and builds on WSL.

**Comment by ras0219-msft** [comment]
👍 Thanks for the PR!

**Pull request merged**
