### PR TITLE
[physx] Add support for checked and profile builds.

### PR DESCRIPTION
**Pull request by Hoikas**
This adds the ability to build the physx port in ["checked" and "profile" mode](https://gameworksdocs.nvidia.com/PhysX/4.1/documentation/physxguide/Manual/BuildingWithPhysX.html#build-configurations) using a custom triplet, enabling reports on API misuse and allowing scene visualization with the NVIDIA PhysX Visual Debugger in Release builds.

- What does your PR fix?
See above
- Which triplets are supported/not supported? Have you updated the CI baseline?
No change
- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

### CODE REVIEW

**Review by LilyWangL — APPROVED** [review]

**Comment by strega-nil** [comment]
Hey @Hoikas! Thanks for the pull request; however, for cases like this, we recommend using custom triplets. You can, for example, write your own `x64-windows-checked.cmake` file which contains something like this:

```cmake
# copy from x64-windows
if(PORT STREQUAL "physx")
    set(RELEASE_CONFIGURATION "checked")
endif()
```

We're looking at improving this experience in the future, but for now this is the "correct" way to do something like this.

Again, thanks so much :heart: :heart:

If you'd like you can modify the port file to not always set `RELEASE_CONFIGURATION` by doing something like:

```cmake
if(NOT DEFINED RELEASE_CONFIGURATION)
  set(RELEASE_CONFIGURATION "release")
endif()
if(NOT DEFINED DEBUG_CONFIGURATION)
  set(DEBUG_CONFIGURATION "debug")
endif()
```

**Comment by Hoikas** [comment]
Thanks for the feedback! I look forward to the improved handling for this kind of situation that you mention. Features are not the best way to expose mutually exclusive options like build type changes, I suppose. I'll change this pull request to match your suggestion soon.

**Comment by strega-nil** [comment]
Thanks so much @Hoikas :heart:

**Comment by Hoikas** [comment]
Updated. I only added the `if(NOT DEFINED ...)` check for the release configuration--debug builds of PhysX already have the instrumentation included in both the checked and profile builds.

**Comment by strega-nil** [comment]
Alright, this looks good to me! Thanks so much @Hoikas :)

**Comment by Hoikas** [comment]
It was no trouble, @strega-nil, but I *know* I am going to have a question soon about an upcoming PR I am planning :smile:

**Pull request merged**
