### PR TITLE
[chakracore] Update to 2022-11-09

### PR DESCRIPTION
**Pull request by Pospelove**
sync with https://github.com/skyrim-multiplayer/skymp/pull/1227

### CODE REVIEW

**Comment by JonLiu1993** [comment]
@Pospelove, Thanks for your pr, this is ci error, please take a look:
````
MSBuild version 17.4.1+9a89d02ff for .NET Framework
Build started 12/20/2022 10:48:56 PM.
     1>Project "D:\buildtrees\chakracore\x86-windows-rel\x86-windows\Build\Chakra.Core.sln" on node 1 (Rebuild target(s)).
     1>D:\buildtrees\chakracore\x86-windows-rel\x86-windows\Build\Chakra.Core.sln.metaproj : error MSB4126: The specified solution configuration "Release|Win32" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration. [D:\buildtrees\chakracore\x86-windows-rel\x86-windows\Build\Chakra.Core.sln]
     1>Done Building Project "D:\buildtrees\chakracore\x86-windows-rel\x86-windows\Build\Chakra.Core.sln" (Rebuild target(s)) -- FAILED.

Build FAILED.

       "D:\buildtrees\chakracore\x86-windows-rel\x86-windows\Build\Chakra.Core.sln" (Rebuild target) (1) ->
       (ValidateSolutionConfiguration target) -> 
         D:\buildtrees\chakracore\x86-windows-rel\x86-windows\Build\Chakra.Core.sln.metaproj : error MSB4126: The specified solution configuration "Release|Win32" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration. [D:\buildtrees\chakracore\x86-windows-rel\x86-windows\Build\Chakra.Core.sln]

    0 Warning(s)
    1 Error(s)

````

**Comment by Pospelove** [comment]
@JonLiu1993 thanks, how do I access full msbuild log?

**Comment by JonLiu1993** [comment]
This is the full error log:
````
MSBuild version 17.4.1+9a89d02ff for .NET Framework
Build started 12/21/2022 7:57:16 PM.
     1>Project "D:\buildtrees\chakracore\x86-windows-rel\x86-windows\Build\Chakra.Core.sln" on node 1 (Rebuild target(s)).
     1>D:\buildtrees\chakracore\x86-windows-rel\x86-windows\Build\Chakra.Core.sln.metaproj : error MSB4126: The specified solution configuration "Release|Win32" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration. [D:\buildtrees\chakracore\x86-windows-rel\x86-windows\Build\Chakra.Core.sln]
     1>Done Building Project "D:\buildtrees\chakracore\x86-windows-rel\x86-windows\Build\Chakra.Core.sln" (Rebuild target(s)) -- FAILED.

Build FAILED.

       "D:\buildtrees\chakracore\x86-windows-rel\x86-windows\Build\Chakra.Core.sln" (Rebuild target) (1) ->
       (ValidateSolutionConfiguration target) -> 
         D:\buildtrees\chakracore\x86-windows-rel\x86-windows\Build\Chakra.Core.sln.metaproj : error MSB4126: The specified solution configuration "Release|Win32" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration. [D:\buildtrees\chakracore\x86-windows-rel\x86-windows\Build\Chakra.Core.sln]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.84
````

**Review by JonLiu1993 — APPROVED** [review]

**Comment by Pospelove** [comment]
@JonLiu1993 yo let's go merge

**Pull request merged**
