### PR TITLE
[python3] Fix python3:x64-linux builds

### LINKED ISSUE #18211: [WSL2][python3:x64-linux] build failure
**Host Environment**
- OS: Ubuntu 20.04 LTS through WSL2
- Compiler: -- The C compiler identification is GNU 9.3.0 -- The CXX compiler identification is Clang 10.0.0

**To Reproduce**
`./vcpkg install boost`

**Failure logs** 
```
Computing installation plan...
The following packages will be built and installed:
    boost[core]:x64-linux -> 1.75.0
  * boost-parameter-python[core]:x64-linux -> 1.75.0
  * boost-pfr[core]:x64-linux -> 1.75.0
  * boost-poly-collection[core]:x64-linux -> 1.75.0
  * boost-process[core]:x64-linux -> 1.75.0
  * boost-program-options[core]:x64-linux -> 1.75.0#1
  * boost-python[core]:x64-linux -> 1.75.0#3
  * boost-safe-numerics[core]:x64-linux -> 1.75.0
  * boost-signals2[core]:x64-linux -> 1.75.0
  * boost-sort[core]:x64-linux -> 1.75.0
  * boost-stacktrace[core]:x64-linux -> 1.75.0#1
  * boost-statechart[core]:x64-linux -> 1.75.0
  * boost-static-string[core]:x64-linux -> 1.75.0
  * boost-stl-interfaces[core]:x64-linux -> 1.75.0
  * boost-timer[core]:x64-linux -> 1.75.0#1
  * boost-type-erasure[core]:x64-linux -> 1.75.0#1
  * boost-vmd[core]:x64-linux -> 1.75.0
  * boost-wave[core]:x64-linux -> 1.75.0#1
  * boost-yap[core]:x64-linux -> 1.75.0
  * python3[core]:x64-linux -> 3.9.5
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-linux...
Could not locate cached archive: /home/dominic/.cache/vcpkg/archives/bc/bc21f1338507ebd3194af6964c8899c88f8f4bf9.zip
Could not locate cached archive: /home/dominic/.cache/vcpkg/archives/db/dba01e8a4b4c044c1ce463e7028792ec5ae0c81e.zip
Could not locate cached archive: /home/dominic/.cache/vcpkg/archives/3b/3bf32846d66ed369d4e764e5f953939a1bacb504.zip
Could not locate cached archive: /home/dominic/.cache/vcpkg/archives/b3/b338c73261790838e3727309ccbf2dc3acf1cc96.zip
Could not locate cached archive: /home/dominic/.cache/vcpkg/archives/3b/3bd70fb2405ebda377f27ac555aef19ddd104944.zip
Could not locate cached archive: /home/dominic/.cache/vcpkg/archives/16/16a1645f094924cd40077044f74de79dad12647d.zip
Could not locate cached archive: /home/dominic/.cache/vcpkg/archives/23/2339e2f0e6352ae19b30c14321a4324dbdc3a273.zip
Could not locate cached archive: /home/dominic/.cache/vcpkg/archives/af/afeab0de983e74cb8b56ff6fee6c80b6dca536e7.zip
Could not locate cached archive: /home/dominic/.cache/vcpkg/archives/7e/7e0b0438008033d5f791e2c40ee4a934917f37f4.zip
Could not locate cached archive: /home/dominic/.cache/vcpkg/archives/0a/0a8e48e7097158740230ae082ac06f07f5cd1952.zip
Could not locate cached archive: /home/dominic/.cache/vcpkg/archives/15/152eab1ba7c89d989fed30106294f4f12147d5e2.zip
Could not locate cached archive: /home/dominic/.cache/vcpkg/archives/ba/ba23af3f7defae016817b409c2d4a148f899d140.zip
Could not locate cached archive: /home/dominic/.cache/vcpkg/archives/23/237c540b11c3d207e8b301d88be5906c838ac029.zip
Could not locate cached archive: /home/dominic/.cache/vcpkg/archives/19/19d62c617df5af69b9ea07f573b7abbfc605ab29.zip
Could not locate cached archive: /home/dominic/.cache/vcpkg/archives/87/87c38ff8f4536e8370914f617643a9c3696eb212.zip
Could not locate cached archive: /home/dominic/.cache/vcpkg/archives/f2/f23f0d8baafafeb2fa8ce2d12ce051cb797a8831.zip
Could not locate cached archive: /home/dominic/.cache/vcpkg/archives/93/93a0d58b3eb3ca0267f36282d985eb30645c87ba.zip
Could not locate cached archive: /home/dominic/.cache/vcpkg/archives/e1/e1cc04b2d84402dd1b5a062d7e4866e022fa52a1.zip
Could not locate cached archive: /home/dominic/.cache/vcpkg/archives/7d/7dd1557353820f2ec486758c1d901aefb28f2481.zip
Could not locate cached archive: /home/dominic/.cache/vcpkg/archives/f9/f99fea0843892dfa58016c8ad0489033c5a03af1.zip
Starting package 1/20: python3:x64-linux
Building package python3[core]:x64-linux...
-- Using cached /home/dominic/dev/vcpkg/downloads/python-cpython-v3.9.5.tar.gz
-- Cleaning sources at /home/dominic/dev/vcpkg/buildtrees/python3/src/v3.9.5-214b854b69.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/dominic/dev/vcpkg/downloads/python-cpython-v3.9.5.tar.gz
-- Applying patch 0001-static-library.patch
-- Applying patch 0002-use-vcpkg-zlib.patch
-- Applying patch 0003-devendor-external-dependencies.patch
-- Applying patch 0004-dont-copy-vcruntime.patch
-- Applying patch 0005-only-build-required-projects.patch
-- Applying patch 0006-fix-duplicate-symbols.patch
-- Using source at /home/dominic/dev/vcpkg/buildtrees/python3/src/v3.9.5-214b854b69.clean
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Installing x64-linux-dbg
-- Building x64-linux-rel
-- Installing x64-linux-rel
CMake Error at ports/python3/portfile.cmake:175 (file):
  file COPY cannot find
  "/home/dominic/dev/vcpkg/packages/python3_x64-linux/bin": No such file or
  directory.
Call Stack (most recent call first):
  scripts/ports.cmake:139 (include)


Error: Building package python3:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: python3:x64-linux
  Vcpkg version: 2021-05-05-unknownhash

Additionally, attach any relevant sections from the log files above.
```
**Additional context**
None

### PR DESCRIPTION
**Pull request by ankurvdev**
**Describe the pull request**
Fix python3:x64-linux build failures 

- #### What does your PR fix?  
  Fixes #18211

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  <all / linux, windows, ...>, <Yes/No>

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  `Your answer`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  <Yes / I am still working on this PR>

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Review by PhoebeHui — APPROVED** [review]

**Comment by ankurverma85** [comment]
@PhoebeHui , @JackBoosY , Can we get this merged ?

**Comment by PhoebeHui** [comment]
@ras0219 @ras0219-msft, could you help merge this PR?

**Comment by ankurverma85** [comment]
@strega-nil-ms , can you help with merging this

**Comment by ras0219-msft** [comment]
This LGTM -- I inspected the file lists from the latest master builds and this PR and found no changes.

Thanks for the PR!

**Pull request merged**
