### PR TITLE
Corrects file hash for jom_1_1_2.zip

### PR DESCRIPTION
**Pull request by destenson**
I'm not sure why the hash would be wrong, but changing it enabled me to build websocketpp (which depends upon it indirectly).

### CODE REVIEW

**Comment by bagong** [comment]
This is really weird, because for me the 512 bit shasum of that jom download is the one you want to replace. No idea why you get a different one, but your change would break the download for others (at least for me ;) ). Ever tried re-donwloading?

**Comment by destenson** [comment]
I did try re-downloading it 4-5 times, then I decided to try just using the
hash it told me (the one I changed it to), and that worked for me. Maybe it
was a temporary server issue that's now been fixed? This is my first time
using vcpkg, so there's definitely a chance of user error on my part. For
example, I didn't verify that the hashes were using the same algorithm. I
don't know why that would be different either, but it's possible.

**Comment by destenson** [comment]
I understand now. My jom_1_1_2.zip file is zero lengh. There must've been a problem downloading it from the server, created a zero-length file and told me its hash. I'll withdraw my PR, since this isn't the right fix for that at all.

**Comment by zabulus** [comment]
The problem is that jom is downloaded from http file, that I think they've shoot down, not https.

**Pull request closed without merging**
