### PR TITLE
[soil] Delete the port

### PR DESCRIPTION
**Pull request by strega-nil**
Unfortunately, the website no longer exists. Hopefully lonesock is okay...

cc @BillyONeal merge this one

### CODE REVIEW

**Comment by BillyONeal** [comment]
I think last time we had a case like this we put it in ci.baseline.txt for ~6 months rather than outright removal?

**Comment by BillyONeal** [comment]
https://github.com/microsoft/vcpkg/blob/7ad163e476f6ad9db9b6508d52f8f403b85c80d0/scripts/ci.baseline.txt#L1857

**Comment by strega-nil** [comment]
Hmm, okay.

**Comment by strega-nil** [comment]
Then maybe https://github.com/microsoft/vcpkg/pull/13000 should be merged first.

**Comment by BillyONeal** [comment]
Applied https://github.com/microsoft/vcpkg/pull/13000 instead, thanks for the suggestion Nicole!

**Pull request closed without merging**
