### PR TITLE
[darknet] remove ninja preference to enable cuda build on windows

### PR DESCRIPTION
**Pull request by cenit**
after #6069 will be merged, this is necessary for `enable_language(CUDA)` to properly work on Windows and so be able to have a CUDA-enabled darknet on Windows

### CODE REVIEW

**Comment by vicroms** [comment]
Friendly reminder to also bump the CONTROL version

**Comment by cenit** [comment]
Yes! I will do it asap

**Comment by cenit** [comment]
I also opened an issue on the CMake tracker to discuss the problem related to Ninja + CUDA using the new `enable_language(CUDA)`.

https://gitlab.kitware.com/cmake/cmake/issues/19173

**Comment by grdowns** [comment]
Thanks @cenit!

**Pull request merged**
