### PR TITLE
Add Kinect driver to OpenNI2 port

### PR DESCRIPTION
**Pull request by UnaNancyOwen**
Add Kinect driver to OpenNI2 port.
OpenNI2 port generate Kinect driver when Kinect SDK has been installed in your system.

### CODE REVIEW

**Comment by UnaNancyOwen** [comment]
It might be better to create the Kinect SDK port and use it, than using the Kinect SDK installed on the system.
What do you think about it?

**Comment by UnaNancyOwen** [comment]
I tried to make the Kinect SDK v1 port (#1349).
If Kinect SDK v1 port to be merged, the replace_environment_variable.patch are not needed.

**Comment by ras0219-msft** [comment]
Thanks for making #1349, it looks great and I've merged it.

If the Kinect SDK is the primary way to use OpenNI2, would you like to simply make it an unconditional dependency?

**Comment by UnaNancyOwen** [comment]
@ras0219-msft I think that it is necessary to settings the include path and library path of vcpkg to Kinect.vcxproj.

**Comment by UnaNancyOwen** [comment]
@ras0219-msft @alexkaratarakis I think ready to merge this pull request. Please review and merge. Thanks,

**Comment by alexkaratarakis** [comment]
Merging this. Thanks (and sorry for the delay)!

**Pull request merged**
