### PR TITLE
[vcpkg] enable incremental build of vcpkg.exe (bootstrap-vcpkg should not rebuild vcpkg if nothing has changed)

### LINKED ISSUE #13738: Run bootstrap-vcpkg.bat and bootstrap-vcpkg.sh always rebuild vcpkg executable
****

ootstrap-vcpkg.bat and bootstrap-vcpkg.sh always does rebuild (compilation and link) of vcpkg, even if the it was just built and there is no change in the vcpkg repo.

**Proposed solution**
The vcpkg bootstrap script should track dependency of vcpkg.exe and don't trigger rebuild if it is up-to-date.

### PR DESCRIPTION
**Pull request by robertobernabe**
**Describe the pull request**
This pull request enables incremental build of vcpkg.exe using msbuild.
This will avoid to always rebuild vcpkg.exe in a CI build calling boostrap-vcpkg.bat

- What does your PR fix? Fixes #
Before: Every call of `bootstrap-vcpkg.bat` results in a full rebuild of `vcpkg.exe`.
After: Only when changes in the source files of `vcpkg.lib` or `vcpkg.exe` or `vcpkgmetricsuploader.exe` the corresponding project get's rebuilded.
```PS C:\Users\florian.schaeffeler\git\robertobernabe\vcpkg> .\bootstrap-vcpkg.bat


Building vcpkg.exe ...

  vcpkglib.vcxproj -> C:\Users\florian.schaeffeler\git\robertobernabe\vcpkg\toolsrc\msbuild.x86.release\vcpkglib.lib
  vcpkg.vcxproj -> C:\Users\florian.schaeffeler\git\robertobernabe\vcpkg\toolsrc\msbuild.x86.release\vcpkg.exe
  vcpkgmetricsuploader.vcxproj -> C:\Users\florian.schaeffeler\git\robertobernabe\vcpkg\toolsrc\msbuild.x86.release\vcpkgmetricsuploader.exe

Building vcpkg.exe... done.

Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md
```

- Which triplets are supported/not supported? Have you updated the CI baseline?

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

### CODE REVIEW

**Comment by BillyONeal** [comment]
Interestingly, this "auto happens" if we just don't delete the vcpkg we produced in bootstrap

**Comment by StarGate-One** [comment]
I do not see how this would take into account when the C/C++ compiler/linker are upgraded?
Many would consider it a requirement to run the vcpkg bootstrap and build using the new compiler/linker...
Maybe the file should contain the sha256 of the compiler and linker also and if there is a difference in any of the three sha sums then vcpkg powershell script will compile/link vcpkg binary again and update the sha sums?

**Comment by JackBoosY** [comment]
Pinging @robertobernabe  for response. Is work still being done for this PR?

**Comment by BillyONeal** [comment]
@JackBoosY I don't think we are waiting for @robertobernabe on this one, I think we are still concerned about this solution and likelihood of causing breakage when the version of Visual Studio etc. changes.

**Comment by BillyONeal** [comment]
@robertobernabe  We discussed this and overall are too concerned about the build system being incorrect causing "impossible" behavior to take this approach (e.g. if the compiler is upgraded between calls to bootstrap resulting in an intermixing of .objs that don't work together). We do have machinery to produce signed vcpkg.exe binaries and are going to alter the bootstrap script to download one of those rather than building it which avoids that concern, expected sometime around beginning of December. We are working through the project management stuff ("how do we coordinate edits to toolsrc and updating that signed copy?" and similar) and will keep you posted.

/cc @ras0219  @ras0219-msft

**Comment by StarGate-One** [comment]
@BillyONeal 
- Will we still be able to download the vcpkg source and build an unsigned local vcpkg.exe or linux executable from scratch?
- Reason I ask is I have some local customizations to vcpkg source that would cause the product to be unusable without these customizations.

**Comment by StarGate-One** [comment]
@BillyONeal (Sorry for duplicate but I forgot to cc ras...

- Will we still be able to download the vcpkg source and build an unsigned local vcpkg.exe or linux executable from scratch?
- Reason I ask is I have some local customizations to vcpkg source that would cause the product to be unusable without these customizations.
/cc @ras0219 @ras0219-msft

**Comment by BillyONeal** [comment]
>Will we still be able to download the vcpkg source and build an unsigned local vcpkg.exe or linux executable from scratch?

Yes. There are still lots of platforms that we can't build in advance, but we should be able to prebuild the most common ones.

>Reason I ask is I have some local customizations to vcpkg source that would cause the product to be unusable without these customizations.

You might need to alter what you're doing to invoke cmake and ninja to build us rather than running `bootstrap.bat`/`bootstrap.sh` but the sources will still be present.

**Comment by StarGate-One** [comment]
> > Will we still be able to download the vcpkg source and build an unsigned local vcpkg.exe or linux executable from scratch?
> 
> Yes. There are still lots of platforms that we can't build in advance, but we should be able to prebuild the most common ones.
> 
> > Reason I ask is I have some local customizations to vcpkg source that would cause the product to be unusable without these customizations.
> 
> You might need to alter what you're doing to invoke cmake and ninja to build us rather than running `bootstrap.bat`/`bootstrap.sh` but the sources will still be present.

@BillyONeal 
Super. I appreciate all the hard work you all put in on this project. It sure has made my life a lot easier - I can spend more time learning how to use the software ports instead of trying out how to get them to compile/link properly. 👍👍👍❤❤❤

/cc: @ras0219 @ras0219-msft @strega-nil @JackBoosY @Voskrese @Neumann-A @NancyLi1013 @PhoebeHui @vicroms @JonLiu1993

**Comment by strega-nil** [comment]
Closing since we're not interested in pursuing this option; thank you so much @robertobernabe for your contribution, and for being willing to open a PR. We really appreciate you and your work :heart:

**Comment by robertobernabe** [comment]
> @robertobernabe We discussed this and overall are too concerned about the build system being incorrect causing "impossible" behavior to take this approach (e.g. if the compiler is upgraded between calls to bootstrap resulting in an intermixing of .objs that don't work together). We do have machinery to produce signed vcpkg.exe binaries and are going to alter the bootstrap script to download one of those rather than building it which avoids that concern, expected sometime around beginning of December. We are working through the project management stuff ("how do we coordinate edits to toolsrc and updating that signed copy?" and similar) and will keep you posted.
> 
> /cc @ras0219 @ras0219-msft

I also agree shipping prebuild signed binaries for vcpkg exec is really the best way to go. Looking forward to this approach! 😄

**Pull request closed without merging**
