### PR TITLE
[kf5newstuff] new port

### PR DESCRIPTION
**Pull request by wrobelda**
**Describe the pull request**

   New port. Depends on:
   - [x] #19779 
   - [x] #20210 

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  All plus `arm64-osx`

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

### CODE REVIEW

**Comment by wrobelda** [comment]
Why is this even a problem on Windows when the dlls are in `/lib`? This is a default location for that lib on Linux and macOS, and that's how it is packaged on Linux as well. Don't understand what's wrong with it?

```
The following dlls were found in /lib or /debug/lib. Please move them to /bin or /debug/bin, respectively.
D:/packages/kf5newstuff_x64-windows/lib/qml/org/kde/newstuff/newstuffqmlplugin.dll
```

**Comment by dg0yt** [comment]
> Why is this even a problem on Windows when the dlls are in `/lib`? This is a default location for that lib on Linux and macOS, and that's how it is packaged on Linux as well. Don't understand what's wrong with it?
> 
> ```
> The following dlls were found in /lib or /debug/lib. Please move them to /bin or /debug/bin, respectively.
> D:/packages/kf5newstuff_x64-windows/lib/qml/org/kde/newstuff/newstuffqmlplugin.dll
> ```

For Windows dynamic linkage, the run-time DLLs are expected to be side-by-side with the EXEs, in `bin`. In `lib`, there are the build-time import libraries (.lib or .dll.a).
In CMake, this `RUNTIME DESTINATION` vs. `LIBRARY DESTINATION`.

**Comment by wrobelda** [comment]
> For Windows dynamic linkage, the run-time DLLs are expected to be side-by-side with the EXEs, in `bin`. In `lib`, there are the build-time import libraries (.lib or .dll.a).
> In CMake, this `RUNTIME DESTINATION` vs. `LIBRARY DESTINATION`.

Thanks. Did some reading and it makes sense.

**Comment by NancyLi1013** [comment]
Could you please try to format the manifests by running `./vcpkg format-manifest ./ports/portName/vcpkg.json`?

**Comment by wrobelda** [comment]
> Could you please try to format the manifests by running `./vcpkg format-manifest ./ports/portName/vcpkg.json`?

None of the ports' manifest files required any formatting. This is likely caused by an issue with your scripts.

**Comment by NancyLi1013** [comment]
After the dependent PRs merged, please resolve the conflcits.

**Review by NancyLi1013 — CHANGES_REQUESTED** [review]

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
LGTM now, thanks for the new port. @wrobelda

**Pull request merged**
