### PR TITLE
[qt5] bumped to qt5.8

### PR DESCRIPTION
**Pull request by tobiaskohlbau**
This merge request updates the qt5 port to version 5.8. In addition it makes some vital changes. Qt gets different builds for debug and release to overcome the problem of badly linked dependencies like for example double_conversion. Before this update the usage of the debug version resulted in errors of not finding `double_conversion.dll`. In addition this commit makes use of the new introduced configuration system of 5.8 which allows to fine tune the modules of Qt.

Related to #787.

Signed-off-by: Tobias Kohlbau <tobias@kohlbau.de>

### CODE REVIEW

**Comment by bagong** [comment]
I tried this (x64-windows, VS2017) and got quite far. This is where it breaks off:

build x64-windows-dbg-out.log:

````
-I..\..\include\QtQuick -IC:\Users\Rainer\Projects\sc\vcpkg\buildtrees\qt5\src\qt-5.8.0\qtbase\include -IC:\Users\Rainer\Projects\sc\vcpkg\buildtrees\qt5\src\qt-5.8.0\qtbase\include\QtGui -IC:\Users\Rainer\Projects\sc\vcpkg\buildtrees\qt5\x64-windows-dbg\qtbase\include -IC:\Users\Rainer\Projects\sc\vcpkg\buildtrees\qt5\x64-windows-dbg\qtbase\include\QtGui -IC:\Users\Rainer\Projects\sc\vcpkg\buildtrees\qt5\src\qt-5.8.0\qtdeclarative\include\QtQml -I..\..\include\QtQml -IC:\Users\Rainer\Projects\sc\vcpkg\buildtrees\qt5\src\qt-5.8.0\qtbase\include\QtNetwork -IC:\Users\Rainer\Projects\sc\vcpkg\buildtrees\qt5\x64-windows-dbg\qtbase\include\QtNetwork -IC:\Users\Rainer\Projects\sc\vcpkg\buildtrees\qt5\src\qt-5.8.0\qtbase\include\QtCore -IC:\Users\Rainer\Projects\sc\vcpkg\buildtrees\qt5\x64-windows-dbg\qtbase\include\QtCore -I.moc\debug -IC:\Users\Rainer\Projects\sc\vcpkg\installed\x64-windows\include -IC:\Users\Rainer\Projects\sc\vcpkg\buildtrees\qt5\src\qt-5.8.0\qtbase\mkspecs\win32-msvc2017 -Fo.obj\debug\ @C:\Users\Rainer\AppData\Local\Temp\qquickparticlesmodule.obj.8156.9172.jom
qquickparticlesmodule.cpp
qquickparticlesystem.cpp
qquickpointattractor.cpp
qquickpointdirection.cpp
qquickspritegoal.cpp
qquickdirection.cpp
qquicktargetdirection.cpp
qquickturbulence.cpp
````
build x64-windows-dbg-err.log:

````
jom 1.1.2 - empower your cores

C:\Users\Rainer\Projects\sc\vcpkg\buildtrees\qt5\src\qt-5.8.0\qtbase\src\corelib\kernel\qobjectdefs.h(0): Note: No relevant classes found. No output generated.
C:\Users\Rainer\Projects\sc\vcpkg\buildtrees\qt5\src\qt-5.8.0\qtbase\src\network\access\qnetworkaccessdebugpipebackend_p.h(0): Note: No relevant classes found. No output generated.
Checking for ntddmodm... no
Checking for jasper... no
Checking for libmng... no
Checking for libtiff... no
Checking for libwebp... no
Microsoft (R) 32b/64b MIDL Compiler Version 8.01.0620 
Copyright (c) Microsoft Corporation. All rights reserved.
testcon.idl
ocidl.idl
oleidl.idl
objidl.idl
unknwn.idl
wtypes.idl
wtypesbase.idl
basetsd.h
guiddef.h
oaidl.idl
servprov.idl
urlmon.idl
msxml.idl
oaidl.acf
ocidl.acf
jom: C:\Users\Rainer\Projects\sc\vcpkg\buildtrees\qt5\x64-windows-dbg\qtdeclarative\src\particles\Makefile.Debug [.obj\debug\qquickwander.obj] Error 2
jom: C:\Users\Rainer\Projects\sc\vcpkg\buildtrees\qt5\x64-windows-dbg\qtdeclarative\src\particles\Makefile [debug] Error 2
jom: C:\Users\Rainer\Projects\sc\vcpkg\buildtrees\qt5\x64-windows-dbg\qtdeclarative\src\Makefile [sub-particles-make_first-ordered] Error 2
jom: C:\Users\Rainer\Projects\sc\vcpkg\buildtrees\qt5\x64-windows-dbg\qtdeclarative\Makefile [sub-src-make_first] Error 2
jom: C:\Users\Rainer\Projects\sc\vcpkg\buildtrees\qt5\x64-windows-dbg\Makefile [module-qtdeclarative-make_first] Error 2
````
Sorry, I can't interpret this, but I'd love to see the build work ;)

**Comment by tobiaskohlbau** [comment]
I've had some strange issues, too sometimes. Try to shorten the path length `C:\vcpkg\....` this solves some issues when some generated files would result in long files names which can't be handled. Please report back the results :-)

**Comment by bagong** [comment]
I'll try, but it'll take a while, it's a slow, and unfortunately not a dedicated build machine ;)

Before building I did merge current master into your PR. Should I avoid that, or do you maybe want to rebase?

**Comment by tobiaskohlbau** [comment]
Should be fine with merging master back into this branch. That's the annoying part about qt port that it takes ages to build.

You could try to comment out this line: https://github.com/Microsoft/vcpkg/pull/992/files#diff-ffc24f11226c62e48563afc957dfee77R15, this should speed up consecutive builds.

**Comment by bagong** [comment]
Hmmm, this time it already broke in the preparatory steps:

````
Building package qt5:x64-windows...
-- CURRENT_INSTALLED_DIR=C:/vcpkg/installed/x64-windows
-- DOWNLOADS=C:/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/vcpkg/packages/qt5_x64-windows
-- CURRENT_BUILDTREES_DIR=C:/vcpkg/buildtrees/qt5
-- CURRENT_PORT_DIR=c:/vcpkg/ports/qt5/.
-- Downloading http://download.qt.io/official_releases/qt/5.8/5.8.0/single/qt-everywhere-opensource-src-5.8.0.7z...
-- Downloading http://download.qt.io/official_releases/qt/5.8/5.8.0/single/qt-everywhere-opensource-src-5.8.0.7z... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Extracting source C:/vcpkg/downloads/qt-5.8.0.7z
-- Extracting done
-- Applying patch C:/vcpkg/ports/qt5/fix-qalgorithms-vs2017.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/vcpkg/ports/qt5/fix-qalgorithms-vs2017.patch done
-- Applying patch C:/vcpkg/ports/qt5/fix-commandline-overrides.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/vcpkg/ports/qt5/fix-commandline-overrides.patch done
-- Configuring x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
    Command failed: C:/vcpkg/buildtrees/qt5/src/qt-5.8.0/configure.bat;-confirm-license;-opensource;-system-zlib;-system-libjpeg;-system-libpng;-system-freetype;-system-pcre;-system-harfbuzz;-system-doubleconversion;-system-sqlite;-sql-sqlite;-sql-psql;-nomake;examples;-nomake;tests;-skip;webengine;-opengl;desktop;-mp;LIBJPEG_LIBS="-ljpeg";ZLIB_LIBS="-lzlib";LIBPNG_LIBS="-llibpng16";-release;-prefix;C:/vcpkg/packages/qt5_x64-windows;-hostbindir;C:/vcpkg/packages/qt5_x64-windows/tools/qt5;-archdatadir;C:/vcpkg/packages/qt5_x64-windows/share/qt5;-datadir;C:/vcpkg/packages/qt5_x64-windows/share/qt5;-plugindir;C:/vcpkg/packages/qt5_x64-windows/plugins;-qmldir;C:/vcpkg/packages/qt5_x64-windows/qml;-I;C:/vcpkg/installed/x64-windows/include;-L;C:/vcpkg/installed/x64-windows/lib;-platform;win32-msvc2017
    Working Directory: C:/vcpkg/buildtrees/qt5/x64-windows-rel
    See logs for more information:
      C:\vcpkg\buildtrees\qt5\config-x64-windows-rel-out.log
      C:\vcpkg\buildtrees\qt5\config-x64-windows-rel-err.log

Call Stack (most recent call first):
  ports/qt5/configure_qt.cmake:27 (vcpkg_execute_required_process)
  ports/qt5/portfile.cmake:24 (configure_qt)
  scripts/ports.cmake:73 (include)


Error: Building package qt5:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: qt5:x64-windows
  Vcpkg version: 0.0.80-2559c9773615ac1d657bc350a3ce0ad9d724e55c
````

patch-x64-windows-0-err.log:

`````
error: corrupt patch at line 83
`````

patch-x64-windows-1-err.log:

`````
error: corrupt patch at line 21
`````

Both out-logs are empty...

This is from a totally fresh install of vcpkg in c:\vcpkg.  I installed, checkout your branch, merged master and then ran `vcpkg install qt5:x64-windows`. All dependencies installed cleanly (I didn't supervise it, but no breaking errors).

**Comment by tobiaskohlbau** [comment]
I'm not able to reproduce this issues. I've setup a new build following you're steps and it builds just fine. Cause the patches are failing instantly fail after checkout I would guess it could be related to git config. I've hat similar errors with patches if line endings are wrong.

**Comment by bagong** [comment]
Okay, I'll inspect! Thanks for following up. I'll be back ;) Would love to get this working!

**Comment by tobiaskohlbau** [comment]
I've not testet to activate webkit within qt builds but should be possible in a similar way as stated in this MR.

I'm still thinking about if activating QML by default is a good option cause the long build times. Maybe we should disable it by default until optional features are supported by vcpkg. What are your thoughts?

**Comment by bagong** [comment]
Ah, it's because of line breaks. You patches are CR/LF, the source is LF... I should have thought of that this first thing, my git is set to leave things as they are... Building now... The WebKit link is a fork of QtWebkit. @annulen, the author is trying to re-enliven the project independently of Qt. I think a very good idea as many smaller projects have a hard time following Qt and switch to Webengine. In general I am not so concerned about build times. More about a robust build. Ideally we could switch on and off options without having to edit portfiles...

**Comment by ras0219-msft** [comment]
I've pushed a change that adds some missing spaces back into the patches to tobias' qt5.8 branch. I still get an issue when building inside our CI, so I'll let you know when I investigate further.

**Comment by bagong** [comment]
Okay, the build completed succesfully for me. Maybe the first time I just ran out of disk-space. The build eats f***g 20GB! :) On to Webkit...

**Comment by bagong** [comment]
I'll drop remarks and questions while I come across them, okay (say no ;) )
- my understanding that in a single vcplg tree there would always only be on qt5 version. I would like to access the qt5 sources from build that depends on qt5 to use the GnuWin32 utils contained there. It would be easier to address them, if the source was just named qt5 rather than qt-5.8.0. Or should those utils (bison, flex, gperf) be downloaded separately?
- is there a chance that the static build works? I am tempted, but it would more or less block my workstation for 8 hours ;)

**Comment by traversaro** [comment]
+1 for enabling QML by default, it is a quite useful and widespread technology (see https://github.com/search?l=CMake&q=qml&type=Code&utf8=%E2%9C%93).

**Comment by tobiaskohlbau** [comment]
For your first question it's not intended to use tools or anything related from the source directory. Vcpkg is designed around library dependencies and the tools directory is only for convenience. Anywhere within the Documentation or the Issues list there is a comment from some maintainer who talked about this topic (I'm not able to find it right now).

I never tested the static build cause I didn't have any project to test it in. Maybe I will find some time to test this by my own, but I would be glad if someone else with the need of static qt5 could test this.

**Comment by traversaro** [comment]
By the way, I think this PR is also going to solve https://github.com/Microsoft/vcpkg/issues/455 .

**Comment by bagong** [comment]
Am I right that this configuration does not include icu and openssl? Would it be a big deal to add that?

**Comment by annulen** [comment]
@bagong FYI, you don't need ICU-enabled Qt to build QtWebKit

**Comment by bagong** [comment]
Maybe, but unicode support is important for our application, so it might be required for other reasons. However the generic webkit build-description (qt 5.7) warns to build qt with icu and openssl for webkit. But maybe that's not relevant anymore?

**Comment by annulen** [comment]
Qt requires ICU on Windows only for QCollator and maybe for advanced encodings like SCSU or BOCU-1

Since 5.6.1 QtWebkit does not require ICU-enabled Qt to build, this makes it compatible with official configuration of QtBase on Windows that disables ICU. OpenSSL was never a build requirement for QtWebKit, though it may be used at some point in future for WebCrypto as optional dependency

**Comment by bagong** [comment]
Okay, you certainly know better. (and I accidentally mistyped when mentioning Qt 5.7, it was the build description of Webkit QT 5.6)

**Comment by annulen** [comment]
That said, you won't be able to load https URLs if Qt is built w/o openssl support

**Comment by ras0219-msft** [comment]
Ok, I've confirmed that qt5:x86-windows builds, however x64-windows-static fails. Additionally, it looks like the current port _also_ fails at x64-windows-static, so I'm going to call this no regression and merge.

Whenever it seems appropriate, we should probably move the conversation about icu/openssl to a separate issue.

**Comment by bagong** [comment]
Found a problem ;)
https://github.com/Microsoft/vcpkg/issues/1021
I hope the report makes sense. Thanks @annulen for analyzing this.

**Pull request merged**
