### PR TITLE
[libxlsxwriter] Fix link zlib

### PR DESCRIPTION
**Pull request by damuellen**
Fix ZLib usage in pkg config file.

### CODE REVIEW

**Comment by damuellen** [comment]
> @damuellen Please add `port-version`.

Done.

**Comment by damuellen** [comment]
Build #20230504.36 failed
I don't know what to change to fix the error.

**Comment by dg0yt** [comment]
> t. The best solution is to do a patch which uses `Requires.private: zlib` instead. And once we are patching, we can also devendor minizip.

Implemented in #31262.
However the minizip port is currently marked as unsupported on uwp. I try to remove the restriction, #31261.

**Comment by Adela0814** [comment]
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

**Comment by damuellen** [comment]
@dg0yt PR https://github.com/microsoft/vcpkg/pull/31262 is probably the better solution. I close mine.

**Pull request closed without merging**
