### PR TITLE
[vcpkg scripts] toolchain/osx: Fix CMAKE_HOST_SYSTEM_PROCESSOR condition with lower case arm64

### LINKED ISSUE #40474: [qt] Cross-compiled build results in "moc" tool targeting the host architecture
**Describe the bug**

For one of the projects I maintain we have an M1 Mac Mini that is solely used for macOS-related tasks, mostly development and testing.

Our current workflow when drafting a new release consists in:

1. Updating our vcpkg fork.
2. Building and exporting a vcpkg environment for the platforms we provide official binaries for.
3. Downloading the environment on a CI agent and using it to build the release.

Unfortunately Azure Pipelines doesn't provide ARM64 macOS agents yet, resulting in a build failure in case for whatever reason one of the tools in the environment is not compiled for x64.

This appears to be the case for Qt's `moc` tool.

**Environment**

- OS: macOS
- Compiler: 15.0.0 (clang-1500.3.9.4)

**To Reproduce**

1. `./vcpkg install qtbase:x64-osx-release` from an ARM64 machine.
2. Export the installed package.
3. Copy the exported environment onto an x64 machine.
5. Observe the resulting error when building a Qt project using CMake and said environment.

**Expected behavior**

Tools that are used to build Qt itself are compiled for the host architecture, which is perfectly fine.

However, `moc` is also used for dependent projects. I believe the correct binary should be chosen based on the current host architecture and not the one that was used to build the vcpkg environment.

**Failure logs**

<details>
<summary>CMake build log</summary>

```
-- The C compiler identification is AppleClang 14.0.0.14000029
-- The CXX compiler identification is AppleClang 14.0.0.14000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode_14.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode_14.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Python interpreter version 3.11.8
-- Performing Test COMPILER_HAS_MBIG_OBJ
-- Performing Test COMPILER_HAS_MBIG_OBJ - Failed
-- Using (among others) the following compiler flags: -Werror;-Wall;-Wpedantic;-Wextra;-Wconversion;-Wsign-conversion;-fsigned-char;-O3
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- ##################################################
-- Mumble version:              1.6.0
-- Architecture:                x64
-- Build type:                  Release
-- Using LTO in release builds: ON
-- ##################################################
-- 
-- These are the paths the different components will be installed to:
-- Executables:         "/usr/local"
-- Libraries:           "/usr/local/lib/mumble"
-- Plugins:             "/usr/local/lib/mumble/plugins"
-- Scripts:             "/usr/local/bin"
-- Man-files:           "/usr/local/share/man/man1"
-- Documentation:       "/usr/local/share/doc/mumble"
-- Licenses:            "/usr/local/share/doc/mumble"
-- Config files:        "/usr/local/etc/mumble"
-- Metadata files:      "/usr/local/share/metainfo"
-- Application files:   "/usr/local/share/applications"
-- Service files:       "/usr/local/services"
-- Sysusers files:      "/usr/local/sysusers"
-- Tmpfiles files:      "/usr/local/tmpfiles"
-- Shared client files: "/usr/local/share/mumble"
-- Shared server files: "/usr/local/share/mumble-server"
-- 
-- Found ZLIB: /Users/runner/hostedtoolcache/MumbleBuild/mumble_env.x64-osx-release.2024-07-23.9ad0398d8/installed/x64-osx-release/lib/libz.a (found version "1.3.1")
-- Found WrapSystemZLIB: TRUE (found version "1.3.1")
-- Using system ZLIB.
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Checking for module 'libb2'
--   Found libb2, version 0.98.1
-- Found WrapSystemPCRE2: TRUE (found version "10.43.0")
-- Using system PCRE2.
-- Performing Test HAVE_GETTIME
-- Performing Test HAVE_GETTIME - Success
-- Performing Test HAVE_SHM_OPEN_SHM_UNLINK
-- Performing Test HAVE_SHM_OPEN_SHM_UNLINK - Success
-- Qt6 component found: Core | Version: 6.7.2
-- Found OpenSSL: /Users/runner/hostedtoolcache/MumbleBuild/mumble_env.x64-osx-release.2024-07-23.9ad0398d8/installed/x64-osx-release/lib/libcrypto.a (found version "3.3.1")
-- Found WrapOpenSSLHeaders: /Users/runner/hostedtoolcache/MumbleBuild/mumble_env.x64-osx-release.2024-07-23.9ad0398d8/installed/x64-osx-release/include (found version "3.3.1")
-- Qt6 component found: Network | Version: 6.7.2
-- Qt6 component found: Xml | Version: 6.7.2
-- OpenSSL component found: Crypto | Version: 3.3.1
-- OpenSSL component found: SSL | Version: 3.3.1
-- Protobuf found | Version: 25.1.0
-- TRACY_ENABLE: OFF
-- TRACY_ON_DEMAND: ON
-- TRACY_CALLSTACK: OFF
-- TRACY_NO_CALLSTACK: OFF
-- TRACY_NO_CALLSTACK_INLINES: OFF
-- TRACY_ONLY_LOCALHOST: OFF
-- TRACY_NO_BROADCAST: OFF
-- TRACY_ONLY_IPV4: OFF
-- TRACY_NO_CODE_TRANSFER: OFF
-- TRACY_NO_CONTEXT_SWITCH: OFF
-- TRACY_NO_EXIT: OFF
-- TRACY_NO_SAMPLING: OFF
-- TRACY_NO_VERIFY: OFF
-- TRACY_NO_VSYNC_CAPTURE: OFF
-- TRACY_NO_FRAME_IMAGE: OFF
-- TRACY_NO_SYSTEM_TRACING: OFF
-- TRACY_DELAYED_INIT: OFF
-- TRACY_MANUAL_LIFETIME: OFF
-- TRACY_FIBERS: OFF
-- TRACY_NO_CRASH_HANDLER: OFF
-- TRACY_TIMER_FALLBACK: OFF
-- Disabling warnings for targets: TracyClient
-- Tracy: OFF
-- Found Git: /usr/local/bin/git (found version "2.46.0")
-- Qt6 component found: Concurrent | Version: 6.7.2
-- Found OpenSSL: /Users/runner/hostedtoolcache/MumbleBuild/mumble_env.x64-osx-release.2024-07-23.9ad0398d8/installed/x64-osx-release/lib/libcrypto.a (found version "3.3.1")
-- Qt6 component found: Sql | Version: 6.7.2
-- Found OpenGL: /Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/System/Library/Frameworks/OpenGL.framework
-- Found WrapSystemPNG: /Users/runner/hostedtoolcache/MumbleBuild/mumble_env.x64-osx-release.2024-07-23.9ad0398d8/installed/x64-osx-release/lib/libpng16.a;/Users/runner/hostedtoolcache/MumbleBuild/mumble_env.x64-osx-release.2024-07-23.9ad0398d8/installed/x64-osx-release/lib/libz.a (found version "1.6.43")
-- Using system PNG.
-- Found BZip2: /Users/runner/hostedtoolcache/MumbleBuild/mumble_env.x64-osx-release.2024-07-23.9ad0398d8/installed/x64-osx-release/lib/libbz2.a (found version "1.0.8")
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Found PNG: /Users/runner/hostedtoolcache/MumbleBuild/mumble_env.x64-osx-release.2024-07-23.9ad0398d8/installed/x64-osx-release/lib/libpng16.a (found version "1.6.43")
-- Found WrapSystemHarfbuzz: TRUE
-- Using system Harfbuzz.
-- Found WrapSystemFreetype: /Users/runner/hostedtoolcache/MumbleBuild/mumble_env.x64-osx-release.2024-07-23.9ad0398d8/installed/x64-osx-release/lib/libfreetype.a;/Users/runner/hostedtoolcache/MumbleBuild/mumble_env.x64-osx-release.2024-07-23.9ad0398d8/installed/x64-osx-release/lib/libz.a;/Users/runner/hostedtoolcache/MumbleBuild/mumble_env.x64-osx-release.2024-07-23.9ad0398d8/installed/x64-osx-release/lib/libbz2.a;/Users/runner/hostedtoolcache/MumbleBuild/mumble_env.x64-osx-release.2024-07-23.9ad0398d8/installed/x64-osx-release/lib/libpng16.a;/Users/runner/hostedtoolcache/MumbleBuild/mumble_env.x64-osx-release.2024-07-23.9ad0398d8/installed/x64-osx-release/lib/libz.a;/Users/runner/hostedtoolcache/MumbleBuild/mumble_env.x64-osx-release.2024-07-23.9ad0398d8/installed/x64-osx-release/lib/libbrotlidec.a;/Users/runner/hostedtoolcache/MumbleBuild/mumble_env.x64-osx-release.2024-07-23.9ad0398d8/installed/x64-osx-release/lib/libbrotlicommon.a (found version "2.13.2")
-- Using system Freetype.
-- Found WrapSystemJpeg: /Users/runner/hostedtoolcache/MumbleBuild/mumble_env.x64-osx-release.2024-07-23.9ad0398d8/installed/x64-osx-release/lib/libjpeg.a (found version "62")
-- Using system Jpeg.
-- Qt6 component found: Svg | Version: 6.7.2
-- Qt6 component found: Widgets | Version: 6.7.2
-- Poco component found: XML | Version: 1.13.3
-- Poco component found: Zip | Version: 1.13.3
-- Using the multi-header code from /Users/runner/work/1/s/3rdparty/nlohmann_json/include/
-- SndFile found | Version: 1.2.2
-- opus found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- speexdsp: Variable sized arrays supported: TRUE
-- speexdsp: alloca available: TRUE
-- speexdsp: SSE available: TRUE
-- speexdsp: SSE2 available: TRUE
-- Disabling warnings for targets: speexdsp
-- ===
--     Building ReNameNoise Release
--     RENAMENOISE_DEMO_EXECUTABLE is OFF
--     RENAMENOISE_BENCHMARK_EXECUTABLE is OFF
--     CLFAGS = '-fvisibility=hidden;-gfull;-gdwarf-2;-Werror;-Wall;-Wpedantic;-Wextra;-Wconversion;-Wsign-conversion;-fsigned-char;-O3;-Wall;-Wextra;-Wpedantic;-O3'
-- ===
-- Disabling warnings for targets: renamenoise
-- Qt6 component found: LinguistTools | Version: 6.7.2
-- Bundling Qt translations from ""
-- Found Python interpreter version 3.11.8
   > Bundling Qt translation "/Users/runner/work/1/b/src/mumble/qttranslations/qt_it.qm"
   > Bundling Qt translation "/Users/runner/work/1/b/src/mumble/qttranslations/qt_nl.qm"
   > Bundling Qt translation "/Users/runner/work/1/b/src/mumble/qttranslations/qt_tr.qm"
   > Bundling Qt overwrite translation "/Users/runner/work/1/b/src/mumble/qttranslations/qt_zh_CN.qm"
-- Qt6 component found: Sql | Version: 6.7.2
-- File: /Users/runner/work/1/b/src/murmur/murmur_autogen
-- Ice component found: Ice | Version: 3.7.3
-- Ice component found: IceSSL | Version: 3.7.3
-- Ice optional component found: IceDiscovery | Version: 3.7.3
-- Ice optional component found: IceLocatorDiscovery | Version: 3.7.3
-- Ice optional component found: IceUtil | Version: 3.7.3
-- Qt6 component found: Test | Version: 6.7.2
-- Using system PNG.
-- Using system Harfbuzz.
-- Using system Freetype.
-- Using system Jpeg.
-- Qt6 component found: Widgets | Version: 6.7.2
-- Found Python interpreter version 3.11.8
-- Omitting online tests - Testing can be performed without an active internet connection
-- Configuring done (29.2s)
CMake Error: AUTOMOC for target shared: Test run of "moc" executable "/Users/runner/hostedtoolcache/MumbleBuild/mumble_env.x64-osx-release.2024-07-23.9ad0398d8/installed/arm64-osx/tools/Qt6/bin/moc" failed.
/Users/runner/hostedtoolcache/MumbleBuild/mumble_env.x64-osx-release.2024-07-23.9ad0398d8/installed/arm64-osx/tools/Qt6/bin/moc -h

Unknown system error -86
CMake Generate step failed.  Build files cannot be regenerated correctly.
```
</details>

**Additional context**

While exporting the x64 vcpkg packages I noticed ARM64 ones being included as well. This may be an indication that the environment assuming an ARM64 host is on purpose and not a bug.

Is there perhaps a way to tell vcpkg to treat the host machine as an x64 one?

### PR DESCRIPTION
**Pull request by WangWeiLin-MV**
Fix https://github.com/microsoft/vcpkg/issues/40474

CMake `STREQUAL` is case-sensitive, change `ARM64` to `arm64` https://cmake.org/cmake/help/latest/variable/CMAKE_APPLE_SILICON_PROCESSOR.html

### CODE REVIEW

**Comment by WangWeiLin-MV** [comment]
There is an issue that it seems that this optimization has not taken effect:

* The host dependency will still build
* In port file, `VCPKG_CROSSCOMPILING` is still `1` (`TRUE`). So the port still requires being passed tools path for running.
* In toolchain file, `CMAKE_CROSSCOMPILING` is set to empty. The package will build tools, and the passed tool path will be ignored.

Currently, the additional host dependencies could be avoided by specifying `--host-triplet` to same with target triplet. However, this method will fail if the host dependency does not support the target architecture, for example arm64.

### Reference

* #16111
* #24100
* https://devblogs.microsoft.com/cppblog/vcpkg-host-dependencies/

**Review by davidebeatrici — APPROVED** [review]

**Comment by dg0yt** [comment]
I see that the old line didn't make sense, but the new behaviour might not be desired either. Basically, I would suggest to let a cross build be a cross build.

At least for ports, there are no CPU-based short-cuts. When the target triplet is different from the host triplet, it is `"host": true`, `!native`, in manifest, and `VCPKG_CROSSCOMPILING`, in portfile. So when this line is reached for the target triplet, the host tools are already built.

**Comment by WangWeiLin-MV** [comment]
> I see that the old line didn't make sense, but the new behaviour might not be desired either. Basically, I would suggest to let a cross build be a cross build.

In that case, it will make "CMAKE_CROSSCOMPILING" true even if "--host-triplet" is specified.

**Comment by dg0yt** [comment]
> In that case, it will make "CMAKE_CROSSCOMPILING" true even if "--host-triplet" is specified.

This particular toolchain file sets `CMAKE_CROSSCOMPILING` to `OFF` for a case which might looks like meant for target_triplet == host_triplet:

https://github.com/microsoft/vcpkg/blob/2f210a9c13fcf2b0c36b1f2187366feec37e3390/scripts/toolchains/osx.cmake#L44-L46

But vcpkg doesn't control `CMAKE_HOST_SYSTEM_PROCESSOR`... but CMake does, for macOS:  https://cmake.org/cmake/help/latest/variable/CMAKE_HOST_SYSTEM_PROCESSOR.html#macos-platforms

I can't tell how far one would get with running x64 build tools on arm64 osx but this would clearly remove the crosscompiling from targeting x64 osx.

And everything else could be subeject to a specific toolchain instead of vcpkg's generic one.

**Review by Cheney-W — DISMISSED** [review]

**Review by dg0yt — COMMENTED** [review]
Given that it didn't work in the past, I would prefer to not introduce it now.

**Comment by WangWeiLin-MV** [comment]
After not setting `CMAKE_CROSSCOMPILING` empty, `x86-windows` fails with 24 error ports and 76 cascaded ports.

SUMMARY FOR x86-windows
  SUCCEEDED: 2138
  BUILD_FAILED: 24
  POST_BUILD_CHECKS_FAILED: 1
  CASCADED_DUE_TO_MISSING_DEPENDENCIES: 76

It is basically be caused that these packages have different behavior depending on the variable `CMAKE_CROSSCOMPILING`.

Temporarily suspended modifications.

**Comment by dg0yt** [comment]
This is expected. The x86 windows hack hides the poor cross-build capabilities of several ports. The android triplets where the first real cross builds in CI.

**Review by Cheney-W — DISMISSED** [review]

**Comment by BillyONeal** [comment]
This was intentionally changed in https://github.com/microsoft/vcpkg/pull/26240 with the expectation that arm64 macs can run x64 tools, and setting it to off can allow some ports to work that would not otherwise. It isn't clear to me that rolling this change back as this PR does will lead to a better user experience; in particular, it isn't clear that it fixes the original reported issue in https://github.com/microsoft/vcpkg/issues/40474 .

Is the real problem that we need to supply a native arm64 cmake?

>When cross compiling, setting CMAKE_CROSSCOMPILING to empty leads confusion.

```cmake
set(CMAKE_CROSSCOMPILING OFF CACHE STRING "")
```

sets `CMAKE_CROSSCOMPILING` to `OFF`, not "empty". The `""` is the "doc string"

**Comment by BillyONeal** [comment]
@AugP @vicroms @JavierMatosD @data-queue @ras0219-msft We aren't sure how this change fixes the problems described in #40474 and agree with the original design intent clearing `CMAKE_CROSSCOMPILING` at this time. That said, if it's better explained why this fixes the original problem, we would consider changing the existing `CMAKE_CROSSCOMPILING` design.

**Comment by BillyONeal** [comment]
Speaking personally, I think if we were to make this change on macOS we should make similar changes for Windows, and that is going to break a lot of users. So we need a big carrot to go with that stick.

**Comment by WangWeiLin-MV** [comment]
> This is expected. The x86 windows hack hides the poor cross-build capabilities of several ports. The android triplets where the first real cross builds in CI.

> Speaking personally, I think if we were to make this change on macOS we should make similar changes for Windows, and that is going to break a lot of users. So we need a big carrot to go with that stick.

As @dg0yt said, there are many ports depends on this hack for x86 windows. I'll try to fix these portability issues.

---

> We aren't sure how this change fixes the problems described in #40474

I'll change this PR to fix the original issue.

**Comment by WangWeiLin-MV** [comment]
# Failed ports on x86-windows cross compiling

* ampl-asl:x86-windows
* aws-sdk-cpp:x86-windows
* blas-test:x86-windows
* clamav:x86-windows
* cmake-user:x86-windows
* cppmicroservices:x86-windows
* dcmtk:x86-windows
* discount:x86-windows
* fastrtps:x86-windows
* forge:x86-windows
* gamedev-framework:x86-windows
* halide:x86-windows
* itk:x86-windows
* kf5plotting:x86-windows
* kf5sonnet:x86-windows
* kf5syntaxhighlighting:x86-windows
* kfr:x86-windows
* lapack-test:x86-windows
* libfreenect2:x86-windows
* ois:x86-windows
* openblas:x86-windows
* opencc:x86-windows
* plplot:x86-windows
* qtactiveqt:x86-windows
* salome-medcoupling:x86-windows
* torch-th:x86-windows
* vulkan-loader:x86-windows

**Comment by BillyONeal** [comment]
Thanks to @JavierMatosD for testing this on an arm64 macOS device for me. It fixes things to have the intended behavior for him.

**Comment by dg0yt** [comment]
And it makes vcpkg build host tools for the arm64-osx host triplet but not reliably use them when targeting x64-osx, leaving more port bugs hidden. 
(Yes, I still think these lines should be removed!)

**Comment by WangWeiLin-MV** [comment]
@dg0yt Except the ports that can be disabled cross-compiling check, for the other ports that require tools to be compiled and run in-place , we will try make these depend on their own host ports. Subsequent fixes will be updated in the list above for the time being.

**Comment by dg0yt** [comment]
I don't believe this will happen.
This PR added a shortcut which wasn't needed in the past, and it shouldn't be needed in the future. Except for hiding poor port quality.

**Pull request merged**
