### PR TITLE
[dbus] no absolute paths

### PR DESCRIPTION
**Pull request by autoantwort**
For https://github.com/microsoft/vcpkg/issues/20469

cc @Neumann-A

### CODE REVIEW

**Comment by Neumann-A** [comment]
Hmm I think this effectively breaks the tools since those probably require a `session.conf` from somewhere

**Comment by autoantwort** [comment]
Hm because this file is full of absolute paths and I don't see a way to make them relative

**Comment by Neumann-A** [comment]
I only see:
```

  <!-- Include legacy configuration location -->
  <include ignore_missing="yes">E:/xserver-vcpkg/vcpkg/packages/dbus_x64-windows/etc/dbus/dbus-1/session.conf</include>

  <!-- Config files are placed here that among other things, 
       further restrict the above policy for specific services. -->
  <includedir>session.d</includedir>

  <includedir>E:/xserver-vcpkg/vcpkg/packages/dbus_x64-windows/etc/dbus/dbus-1/session.d</includedir>

  <!-- This is included last so local configuration can override what's 
       in this standard file -->
  <include ignore_missing="yes">E:/xserver-vcpkg/vcpkg/packages/dbus_x64-windows/etc/dbus/dbus-1/session-local.conf</include>

  <include if_selinux_enabled="yes" selinux_root_relative="yes">contexts/dbus_contexts</include>
```

which probably can be replaced by relative dirs considering `<includedir>session.d</includedir>` or completly removed considering `<include ignore_missing="yes">`

The other .conf just has the absolute paths in a comment.

**Comment by Neumann-A** [comment]
But considering: https://dbus.freedesktop.org/doc/dbus-daemon.1.html

I think the conf files need to be moved any way since moving the tools changed the prefix.

**Comment by autoantwort** [comment]
Yeah ok the include things can properly removed. But in `system.conf` I have
```xml
  <!-- This is a setuid helper that is used to launch system services -->
  <servicehelper>/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/packages/dbus_arm64-osx/libexec/dbus-daemon-launch-helper</servicehelper>

  <!-- Write a pid file -->
  <pidfile>/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/packages/dbus_arm64-osx/var/run/dbus/pid</pidfile>

  <!-- Only listen on a local socket. (abstract=/path/to/socket 
       means use abstract namespace, don't really create filesystem 
       file; only Linux supports this. Use path=/whatever on other 
       systems.) -->
  <listen>unix:path=/Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/packages/dbus_arm64-osx/var/run/dbus/system_bus_socket</listen>
```

**Comment by Neumann-A** [comment]
I think you can delete that file due to: `This configuration file controls the systemwide message bus`. vcpkg probably doesn't want to mess with that.

**Comment by autoantwort** [comment]
> with that.

But the `session.conf` file is used for the message bus inside a user session. vcpkg probably doesn't want to mess with that either. Maybe vcpkg should not install (build) the daemon at all.

**Comment by Neumann-A** [comment]
> But the session.conf file is used for the message bus inside a user session. vcpkg probably doesn't want to mess with that either. Maybe vcpkg should not install (build) the daemon at all.

windows needs it. Otherwise you don't have a way to test stuff on windows (i think.)

**Comment by autoantwort** [comment]
Ok there is now a `session.conf` without absolute paths.

**Comment by LilyWangLL** [comment]
> Ok there is now a `session.conf` without absolute paths.

cc @Neumann-A, could you please review the latest change again? Thanks in advance.

**Review by LilyWangLL — APPROVED** [review]

**Pull request merged**
