### PR TITLE
[WIP] [vcpkg-export-ifw] Layout

### PR DESCRIPTION
**Pull request by podsvirov**
Add `--ifw-layout` option for `export` command to manage output layout.

Suggestion layouts:
- DEVELOPMENT (by default, standart export) [implemented]
- MAINTENANCE (export cached compiled packages) [this PR]
- PRODUCTION (export only one triplet to use late in custom final installer) [not implemented now]

### CODE REVIEW

**Comment by podsvirov** [comment]
Your can try install cached precompiled packages via [vcpkg-export-ifw-maintenance-installer.exe](http://ifw.podsvirov.pro/vcpkg/beta/vcpkg-export-ifw-maintenance-installer.exe) installer.
Then initialize empty git repository in installation folder, add `vcpkg` remove repository, checkout `master` branch, run bootstrap-vcpkg.bat and check cache via `vcpkg cache`.

There I have new question: `vcpkg install pkg` will build cached `pkg` again... Looks like bug.

@ras0219-msft what you think about this?

**Comment by ras0219-msft** [comment]
We did previously install from the cache, however as part of the implementation of feature packages that behavior was removed. There was no "official" way to really interact with the cache previously except for listing it with `vcpkg cache`.

I wouldn't mind restoring the behavior, but we need to track more information before doing so; specifically we would need to start tracking a kind of "ABI" to know when a cached package is stale and no longer suitable for reinstall.

For your case, I would recommend having the installer immediately install each of the chosen packages. We could add some sort of explicit override (`--no-build`, perhaps) to the install command that _only_ looks at the cache.

**Comment by podsvirov** [comment]
Now when changing the package version, we delete this package and all the packages that depend on it. Then we build all the packages again, but this does not appear in the version of the re-built packages.

I have an idea to track the build number of the package, which can be saved in the `CONTROL` file (or in some similar place). This build number should increase with subsequent builds of the package and be present in the version of the built package.

Source `CONTROL`:
```
Version: 1.10.8
VersionTemplate: 1.10.8-${CURRENT_PACKAGE_VERSION_BUILD}
```

Binary `CONTROL`:
```
Version: 1.10.8-2
VersionBuild: 2
```

We need to save the Binary `CONTROL` file when deleting the package and use its contents directly before the next rewrite.

**Comment by JackBoosY** [comment]
Can you resolve these file conflicts?

Thanks.

**Comment by podsvirov** [comment]
> Can you resolve these file conflicts?

Well, I will try to do this in my free time.

**Comment by dan-shaw** [comment]
@podsvirov Going to close this PR as this PR has been open too long. If you are interested in working on this, feel free to reopen, but it might make more sense to make a new PR (otherwise we might lose track of it).

**Pull request closed without merging**
