### PR TITLE
[protopuf] Update to 2.1.0

### PR DESCRIPTION
**Pull request by PragmaTwice**
**Describe the pull request**

- #### What does your PR fix?  
  Update [protopuf](https://github.com/PragmaTwice/protopuf) to 2.1.0

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  All, and it is a header-only library.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

### CODE REVIEW

**Comment by JackBoosY** [comment]
The cnl regressions will be resolved by another PR.

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
Waiting for #18767 merge.

**Comment by PragmaTwice** [comment]
@JackBoosY Hello, can this PR be merged now?

**Comment by JackBoosY** [comment]
@PragmaTwice Yes.

**Comment by ras0219-msft** [comment]
Thanks for the update!

**Pull request merged**
