### PR TITLE
vcpkg_build_cmake

### PR DESCRIPTION
**Pull request by kreuzerkrieg**
Add `-j` with core count to make the build parallel

### CODE REVIEW

**Comment by MikeGitb** [comment]
Isn't ninja compiling in parallel by default?

**Comment by kreuzerkrieg** [comment]
> Isn't ninja compiling in parallel by default?

good question
I didnt get any clear answer regarding it, so...

**Comment by MikeGitb** [comment]
I definitely know it does so by default, but I've never verified that it is actually happening during a vcpkg library installation.

**Comment by kreuzerkrieg** [comment]
> I definitely know it does so by default, but I've never verified that it is actually happening during a vcpkg library installation.

If you are sure I guess this PR should be rejected.

**Comment by vicroms** [comment]
[From the Ninja manual](https://ninja-build.org/manual.html):

> Builds are always run in parallel, based by default on the number of CPUs your system has.

**Pull request closed without merging**
