### PR TITLE
[libxml2] Disable http and ftp on UWP

### LINKED ISSUE #16529: uwp app using libxml2 can't launch.
**Describe the bug**
uwp app using libxml2 can't launch.
I have libxml2:x64-uwp 2.9.10#2 installed using vcpkg.
repo to reproduce the bug: https://github.com/HppZ/libxml2-uwp
 
**Environment**
- OS: [Windows 19042.844]
- Compiler: vs2019 16.8.6

**To Reproduce**
1.  vcpkg install libxml2 --triplet=x64-uwp
2. run the libxml2-uwp app and it **can't** launch.
https://github.com/HppZ/libxml2-uwp
3. comment out the call `xmlNewTextWriterFilename("test", 1);` , **rebuild** the app and run again, it **can** launch.

**Expected behavior**
the app should launch.

**Failure logs** 
Unable to activate Windows Store app '1a2ed2c1-b8c3-4a00-ab03-f5d6312dc55e_kmdshx21vdgze!App'. The App5.exe process started, but the activation request failed with error 'The target process aborted before activation completed. More information may be available in the Debug pane of the Output window (Debug->Windows->Output)'.

### PR DESCRIPTION
**Pull request by JackBoosY**
Since libxml2 calls some Windows APIs that cannot be used in uwp, disable HTTP and FTP on UWP.

Compiler errors:
```
Unable to activate Windows Store app '1a2ed2c1-b8c3-4a00-ab03-f5d6312dc55e_kmdshx21vdgze!App'. 
The App5.exe process started, but the activation request failed with error 'The target process aborted before activation completed. 
More information may be available in the Debug pane of the Output window (Debug->Windows->Output)'.
```

Fixes #16529.

### CODE REVIEW

**Comment by JackBoosY** [comment]
Hi @ras0219-msft, does my changes met you requires?

**Comment by JackBoosY** [comment]
Already report this issue to the upstream: https://gitlab.gnome.org/GNOME/libxml2/-/issues/225.

**Review by NancyLi1013 — APPROVED** [review]

**Review by ras0219-msft — APPROVED** [review]
This LGTM -- @HppZ does this fix your issue?

**Comment by JackBoosY** [comment]
The upstream approved this changes, and the author response me: solved.

**Pull request merged**
