### PR TITLE
[brotli] Update to v1.1.0

### PR DESCRIPTION
**Pull request by DownerCase**
- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [X] SHA512s are updated for each updated download
- [X] The "supports" clause reflects platforms that may be fixed by this new version
- [X] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [X] Any patches that are no longer applied are deleted from the port's directory.
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

Updates brotli to recently release version. Most notable change from upstream for vcpkg is the build_shared_libs support and the unification of library names.

### CODE REVIEW

**Comment by DownerCase** [comment]
Hmm. This one eludes me. So everything seems to be fine until Brotli goes through qtbase at which point everything downstream breaks...
I don't see anything obviously wrong with [FindWrapBrotli](https://github.com/qt/qtbase/blob/v6.5.2/cmake/FindWrapBrotli.cmake) in qtbase.
The only use of brotli within qtbase is to extend the [network component](https://github.com/qt/qtbase/blob/v6.5.2/src/network/CMakeLists.txt#L136)

I'm able to reproduce qglviewer's build error but as the CI logs suggest both `libbrotlidec` and `libbrotlicommon` are present in the build command. However, they appear to be backwards with `common` appearing _before_ `dec`. Swapping the two seems to make the build work.

Linking `Qt::Network` places a copy of the brotli libs together and in the correct order but `Qt::Gui` places them separated and reversed. If you link both you get two copies of brotli in the link libraries! One reversed from Qt::Gui and one correct from Qt::Network. All this is  done whilst `Qt6::Gui` has a link interface containing `\$<LINK_ONLY:Qt6::Network>;`

No clue what is going on though looks like an opportunity to clean up [freetype](https://github.com/microsoft/vcpkg/blob/master/ports/freetype/brotli-static.patch) slightly

**Comment by DownerCase** [comment]
> No clue what is going on though looks like an opportunity to clean up [freetype](https://github.com/microsoft/vcpkg/blob/master/ports/freetype/brotli-static.patch) slightly

So turns out I had already found the problematic code but not realised it was the cause. I remove the "only add `brotlicommon`
 if brotli was built statically check in favor of always adding it. Its what the pkgconfig and CMake usage methods do and is what this port used to do.

I considered removing the searching for the `-static` postfixed names but left it for backwards compatibility? In case someone pins an older version of Brotli but uses a new freetype? Idk if that's desirable.

**Comment by FrankXie05** [comment]
>I considered removing the searching for the -static postfixed names but left it for backwards compatibility? In case someone pins an older version of Brotli but uses a new freetype? Idk if that's desirable.

A bit worrying, but we encourage using the latest port.

**Review by FrankXie05 — APPROVED** [review]

**Comment by WerWolv** [comment]
It looks like this update broke building the library for wasm again. I'm trying to install freetype (which depends on brotli) and get this error here:
```
#15 19.57 CMake Error at scripts/cmake/vcpkg_copy_tools.cmake:36 (message):
#15 19.57   Couldn't find tool "brotli":
#15 19.57
#15 19.57       "/vcpkg/packages/brotli_wasm32-emscripten/tools/brotli/brotli" does not exist
#15 19.57 Call Stack (most recent call first):
#15 19.57   ports/brotli/portfile.cmake:26 (vcpkg_copy_tools)
#15 19.57   scripts/ports.cmake:147 (include)
#15 19.57
#15 19.57
#15 19.57 error: building brotli:wasm32-emscripten failed with: BUILD_FAILED
```

There's a line in the portfile that tries to prevent this issue but it doesn't seem to work anymore
image

**Comment by DownerCase** [comment]
That's clever, considering the issue the comment is referring to was fixed... https://github.com/google/brotli/pull/906 https://github.com/google/brotli/pull/988
 
The only thing stopping it now would be BROTLI_BUNDLED_MODE. I'll have a look later, and dig into it

**Comment by DownerCase** [comment]
I found the problem. Under emscripten the executable produced is suffixed with `.js`. vcpkg_copy_tools is looking for a file named `brotli` with no extension because on all platforms except Windows the file suffix is set to [empty string](https://github.com/microsoft/vcpkg/blob/db0473513e5dc73ec6b6f431ff05d2f398eea042/scripts/cmake/vcpkg_common_definitions.cmake#L62)

Adding `.js` to the copy tools works as a bodge because the emscripten triplet is not flagged as Windows  (even on Windows) and so looks for no extension.

**Pull request merged**
