### PR TITLE
[grpc] Fix x86-windows build issue

### LINKED ISSUE #17247: Grpc installed libraries difference between x64-windows and x86-windows
After installing grpc with the command below, I cannot find some libraries like grpc++_refletion.lib for x86-windows. Is this supposed to be so or am I missing something?

- The machine setup
Windows10

- package and version you're building
grpc 1.33.1#3

- Installation process
```
$ git clone https://github.com/Microsoft/vcpkg.git
$ ./bootstrap-vcpkg.sh
$ ./vcpkg integrate install
$ vcpkg install grpc
```

- Libraries for x64-windows
```
vcpkg\packages\grpc_x64-windows\lib> Get-ChildItem -Name
pkgconfig
address_sorting.lib
gpr.lib
grpc++.lib
grpc++_alts.lib
grpc++_error_details.lib
grpc++_reflection.lib
grpc++_unsecure.lib
grpc.lib
grpcpp_channelz.lib
grpc_csharp_ext.lib
grpc_plugin_support.lib
grpc_unsecure.lib
```
- Libraries for x86-windows
```
vcpkg\packages\grpc_x86-windows\lib> Get-ChildItem -name
pkgconfig
address_sorting.lib
gpr.lib
grpc++.lib
grpc++_alts.lib
grpc++_unsecure.lib
grpc.lib
grpc_csharp_ext.lib
grpc_plugin_support.lib
grpc_unsecure.lib
```

### PR DESCRIPTION
**Pull request by ykadowak**
- #### What does your PR fix?  
  Fixes #17247

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  `Yes`

I think this is a regression of https://github.com/microsoft/vcpkg/commit/b5bb1511f0a07be530e0bde3ae098eb3d8e83e68.
The original PR contains a lot of changes but I only understand a small part of it. So I am not sure if this is a right way to fix this.

### CODE REVIEW

**Comment by JonLiu1993** [comment]
@yusuke-kadowaki ,Thanks for your contribution,please run the _vcpkg x-add-version grpc --overwrite-version_ command,then commit again

**Review by JonLiu1993 — CHANGES_REQUESTED** [review]
@yusuke-kadowaki ,please add "port-version" : 1 in the vcpkg.json

**Comment by JonLiu1993** [comment]
The failures caused by popsift will be fixed by #17277.

**Comment by JonLiu1993** [comment]
The failures caused by popsift will be fixed by #17277.

**Comment by yusuke-kadowaki** [comment]
> @yusuke-kadowaki ,please add "port-version" : 1 in the vcpkg.json

Wait, which vcpkg.json? I edited the grpc one from "port-version" : 3 to 1, which does not seem right.

**Comment by yusuke-kadowaki** [comment]
@JonLiu1993 Now I'm confused haha. Can you tell me what specifically you wanted me to do?

**Comment by dg0yt** [comment]
You changed the portfile, so you shall *increment* the port version. Than commit this change.
After this commit, let vcpkg register the new port version by `vcpkg x-add-version grpc`, and make another commit.
This is documented in the [Versioning part of the mainainer's guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#versioning).

**Comment by yusuke-kadowaki** [comment]
@dg0yt I was misunderstanding the versioning. Thank you for the comment.

**Comment by yusuke-kadowaki** [comment]
@ras0219
I think desired behavior when running ``` vcpkg install grpc ``` on Windows is building with CODEGEN feature ON for both x64-windows and x86-windows. That is because building for x86-windows on x64-windows is not a usual cross compiling. It used to work like that before https://github.com/microsoft/vcpkg/commit/b5bb1511f0a07be530e0bde3ae098eb3d8e83e68.

Anyway, ``` vcpkg install grpc[codegen] ``` worked on my end too.

**Comment by ras0219** [comment]
The problem with that assumption is that arm64 is becoming much more prominent as a major platform for all three OS's (Windows, OSX, and Linux). I think it's much better to have a consistent story that works for everyone, rather than trying to build a bunch of case-by-case stuff that is likely to need changes or be fully scrapped in the future.

**Comment by yusuke-kadowaki** [comment]
I understand that the hard-coding part is bad and needs fixed anyway. 

The only concern is, as I mentioned, it would be a bit confusing for x86-windows developer I think. What if you add something like this to you PR #17424.
```
else if((TARGET_TRIPLET STREQUAL "x86-windows") AND (HOST_TRIPLET STREQUAL "x64-windows"))
set(gRPC_BUILD_CODEGEN ON)
```

Just my opinion. I'm closing this and leave it to your PR.

**Pull request closed without merging**
