### PR TITLE
[spirv-tools] Update to version 2020.1

### PR DESCRIPTION
**Pull request by BurningEnlightenment**
I'm currently preparing a cmake integrated bgfx port (requested here #1303) which requires a newer `spirv-tools` version. Additionally I updated the portfile to rely on the new upstream cmake install support.
I included the `spirv-headers` update, because it is only directly used by `spirv-tools` and the new `spirv-tools` version is not compatible with the old `spirv-headers` version.

### CODE REVIEW

**Review by NancyLi1013 — CHANGES_REQUESTED** [review]

**Comment by NancyLi1013** [comment]
It seems that there is something wrong with Linux platform.
I will re run it.

**Comment by BurningEnlightenment** [comment]
> It seems that there is something wrong with Linux platform.

@NancyLi1013 I found the underlying issue: `vcpkg_fixup_cmake_targets()` uses `share/${PORT}` => `share/spirv-tools` by default. The cmake, configs, however are written to `share/SPIRV-Tools` by the upstream project install script.

**Comment by NancyLi1013** [comment]
Thanks for your deepest investigation about this issue.
It looks good now.

**Review by NancyLi1013 — APPROVED** [review]

**Review by PhoebeHui — APPROVED** [review]
LGTM

**Review by dan-shaw — APPROVED** [review]

**Pull request merged**
