### PR TITLE
[grpc] Fix missing dll's for grpc_cpp_plugin

### PR DESCRIPTION
**Pull request by KindDragon**

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for the PR!

I used `vcpkg_copy_tool_dependencies()` instead, which will correctly handle cases such as having mixed static/dynamic dependencies.

This exposed a bug in our post-build checks, which I also fixed.

**Comment by KindDragon** [comment]
Cool. Thanks

**Comment by KindDragon** [comment]
BTW it produces some warnings:
```
Installing package grpc:x64-windows...
File d:\Work\vcpkg\installed\x64-windows\tools\grpc\libprotobuf.dll was already present and will be overwritten
File d:\Work\vcpkg\installed\x64-windows\tools\grpc\libprotoc.dll was already present and will be overwritten
File d:\Work\vcpkg\installed\x64-windows\tools\grpc\zlib1.dll was already present and will be overwritten
Installing package grpc:x64-windows... done
```

**Comment by ras0219-msft** [comment]
Hmm, I don't see those warnings. Does this repro every time you rebuild+install?

**Comment by KindDragon** [comment]
Nope, only first time somehow

**Comment by KindDragon** [comment]
Ahh, it is because I copied them manually before your changes. Sorry

**Pull request merged**
