### PR TITLE
[WIP] Scan build output for correct library linkage. 

### PR DESCRIPTION
**Pull request by Neumann-A**
Just a test to find internal vcpkg linking issues.

### CODE REVIEW

**Comment by Fleischner** [comment]
Perfect!

Related for post build checking:

- [ ] Header reachability: (From #1284) Run over all installed header files and check that all #includes work by checking that the included files can be either found from the base include directory or from the directory of the current include file.
- [ ] Header conflict: (From #1284 ,  #3019) Check that headers from all ports are disjunct.
- [ ] Hidden dependency: (From #1284) Check that there are not 2 header files with the same name and very similar contents in two different folders. That is alarm for hidden dependency in a port.
- [ ] Forbidden dependency: (From #1152) Check that libraries only depend on dependencies listed in the port file. Might be impossible for static builds.

**Comment by Neumann-A** [comment]
This PR needs a port which is deliberatly wrongly linked to check wether the code actual does what it promises.

**Comment by Neumann-A** [comment]
List of ports wrongly linked internally (x64-windows-static):
(if ports depend on one of those they are not checked because the build fails with an fatal_error on the listed ports already)
- [ ] libwebp
- [ ] poco
- [ ] yara
- [ ] kf5plotting
- [ ] libfreenect2
- [ ] cutelyst2
- [ ] libmysql
- [ ] kd-soap
- [ ] freeopcena (could be called differently; cannot read my notes clearly here)
- [ ] kealib
- [ ] zxing
- [ ] telnetpp
- [ ] vtk-dicom

**Comment by Neumann-A** [comment]
hmm which ports must i update to get a reasonable coverage in CI?

**Comment by JackBoosY** [comment]
Do we need this PR now?

**Comment by Neumann-A** [comment]
@JackBoosY  Who are you asking?

**Comment by JackBoosY** [comment]
@Neumann-A Since this PR is a test and lasts a long time, has its mission been completed?

**Comment by Neumann-A** [comment]
@JackBoosY Correct debug/release linkage is sometimes still a problem in vcpkg. As such this PR is still required

**Comment by BillyONeal** [comment]
@Neumann-A Are you willing to investigate implementing this as a post-build validation step in vcpkg.exe itself rather than this way? That way it would be caught generally.

**Comment by Neumann-A** [comment]
@BillyONeal: Currently don't have the free time to do so.

**Comment by JackBoosY** [comment]
Please reopen this PR if you continue it.

**Pull request closed without merging**
