### PR TITLE
[assimp]Update assimp to v5.0.0.rc1 and fix build error in arm and uwp.

### PR DESCRIPTION
**Pull request by JackBoosY**
- update to v5.0.0.rc1
- delete useless patch.
- fix build error in arm.
- fix build error in uwp.

Related: #6338

### CODE REVIEW

**Comment by jepessen** [comment]
Just a question from a newbie.. is it correct to include release candidate library version in vcpkg instead of using only stable releases?

**Comment by JackBoosY** [comment]
@jepessen We need to consider the risks between the two versions.

**Comment by jepessen** [comment]
Ok thanks for the reply.

**Comment by ras0219-msft** [comment]
I agree with @jepessen; we should not use the RC1 version here unless there are specific bugfixes we need.

**Pull request closed without merging**
