### PR TITLE
[libpng] Fix CMake targets

### PR DESCRIPTION
**Pull request by PhoebeHui**
Fix related issue #8704 #8241 #1627.

PR https://github.com/microsoft/vcpkg/pull/3092 rename the static lib name, but doesn't update it in cmake target file.

libpng has no feature that need to test locally.

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by PhoebeHui** [comment]
on osx, vxl failed due to conflict with qt5-location:x64-osx, it should not relate to libpng changes here

Failures:
Building package vxl[core]:x64-osx... done
Installing package vxl[core]:x64-osx...
The following files are already installed in /Users/vagrant/azure_agent/_work/2/s/installed/x64-osx and are in conflict with vxl:x64-osx

Installed by qt5-location:x64-osx
    lib/libclipper.a

Elapsed time for package vxl:x64-osx: 20.14 min

**Comment by ras0219-msft** [comment]
The vxl conflict should be solved by https://github.com/microsoft/vcpkg/pull/8777

**Comment by PhoebeHui** [comment]
@ras0219-msft, thanks for fix vxl conflict  issue, currently this PR ready to merge.

**Comment by freddy77** [comment]
Any pending issue on this merge request? It would be really helpful for me

**Comment by PhoebeHui** [comment]
@freddy77, currently CI offline for maintenance, we will give priority to merge this PR after the CI back online.

**Comment by PhoebeHui** [comment]
@grdowns, please priority to review and merge this PR, thanks!

**Comment by cenit** [comment]
this PR broke libpng when deploying in a "release-only" mode.

**Comment by cenit** [comment]
#9198 should fix the problem

**Pull request merged**
