### PR TITLE
Fix aquire flex and bison when not on Windows

### LINKED ISSUE #4042: [thrift] build fails on linux due to FLEX & BISON not found
Currently, thrift tries to find flex and bison using:
```
vcpkg_find_acquire_program(FLEX)
vcpkg_find_acquire_program(BISON)
```
https://github.com/Microsoft/vcpkg/blob/master/ports/thrift/portfile.cmake

However, this only works on windows..

Solution:
Use find_program on other platforms:

```cmake 
if (WIN32)
    vcpkg_find_acquire_program(FLEX)
    vcpkg_find_acquire_program(BISON)
else()
    find_program(FLEX flex)
    if(NOT FLEX)
        message(FATAL_ERROR "Could not find flex. Please install it through your package manager.")
    endif()
    find_program(BISON bison)
    if(NOT BISON)
        message(FATAL_ERROR "Could not find bison. Please install it through your package manager.")
    endif()
endif()
```
I can make a PR with the fix included if this sounds ok?

### PR DESCRIPTION
**Pull request by markaren**
Fix #4042 and #4119

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for the PR!

I think we should do exactly what you suggested _inside_ `vcpkg_find_acquire_program()` -- could you change your PR to modify `scripts\cmake\vcpkg_find_acquire_program()` so everyone gets this behavior (not just thrift)?

**Comment by markaren** [comment]
@ras0219-msft would the below change yield the correct behavior (and the same applied to bison)? If so I can open a new PR with the change applied.

```cmake
elseif(VAR MATCHES "FLEX")
    if (WIN32)
        set(PROGNAME win_flex)
        set(PATHS ${DOWNLOADS}/tools/win_flex)
        set(URL "https://sourceforge.net/projects/winflexbison/files/win_flex_bison-2.5.9.zip/download")
        set(ARCHIVE "win_flex_bison-2.5.9.zip")
        set(HASH 9580f0e46893670a011645947c1becda69909a41a38bb4197fe33bd1ab7719da6b80e1be316f269e1a4759286870d49a9b07ef83afc4bac33232bd348e0bc814)
    else()
        find_program(FLEX flex)
        if(NOT FLEX)
            message(FATAL_ERROR "Could not find flex. Please install it through your package manager.")
        endif()
    endif()
```

**Comment by ras0219-msft** [comment]
Actually, I think it might be as simple as
```
elseif(VAR MATCHES "FLEX")
    if(WIN32)
        set(PROGNAME win_flex)
    else()
        set(PROGNAME flex)
    endif()
    # leave all the rest of the set() commands here
```
because we do call `find_program()` lower down and print out exactly that message :) (lines 195-203)

**Comment by markaren** [comment]
I've updated the pull request. It's untested though. But please have a look.

>  # leave the rest of the set() commands here

I left the other set command inside the ```WIN32``` block as it seems these are for windows only

**Comment by ras0219-msft** [comment]
Awesome, thanks for the PR!

**Pull request merged**
