### PR TITLE
[msdfgen] Update to 1.9.2

### PR DESCRIPTION
**Pull request by chausner**
**Describe the pull request**

- #### What does your PR fix?  
  Updates msdfgen to 1.9.2

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  As before, Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run ./vcpkg x-add-version --all and committed the result?  
  Yes

### CODE REVIEW

**Comment by JonLiu1993** [comment]
@chausner, thanks for posting this PR, MSDFGEN_BUILD_MSDFGEN STANDALONE is not found in upstream sources, I only found MSDFGEN_BUILD STANDALONE, maybe we can remove this feature?

**Comment by chausner** [comment]
> @chausner, thanks for posting this PR, MSDFGEN_BUILD_MSDFGEN STANDALONE is not found in upstream sources, I only found MSDFGEN_BUILD STANDALONE, maybe we can remove this feature?

Thanks for the notice. Yes, that option has been renamed. I fixed it.

**Comment by JonLiu1993** [comment]
All feature are tested successfully in the following triplet:
- x86-windows
- x64-windows
- x64-windows-static

**Review by JonLiu1993 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the update!

**Pull request merged**
