### PR TITLE
[libass] fix fontconfig dependency in .pc file

### PR DESCRIPTION
**Pull request by mcmtroffaes**
**Describe the pull request**

- #### What does your PR fix?  
  This PR fixes link errors with fontconfig when linking against libass using pkgconfig on x64-linux. Ran into this problem when linking against ffmpeg[libass] (for instance, see link errors here: https://github.com/mcmtroffaes/ffmpeg-msvc-build/runs/2851854810?check_suite_focus=true#step:15:42).

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  No changes.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes.

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by ras0219-msft** [comment]
Thanks for the fix, this looks great to me!

**Comment by mcmtroffaes** [comment]
Lovely, many thanks for merging so quickly! For the record, upstream has plans for supporting meson (there's a long standing PR on their repo which appears to be in good shape), so hopefully we can then get rid of the custom CMakeLists.txt in due time.

**Comment by Neumann-A** [comment]
> so hopefully we can then get rid of the custom CMakeLists.txt in due time.

you probably already can by switching to `vcpkg_configure_make`

**Comment by mcmtroffaes** [comment]
> you probably already can by switching to `vcpkg_configure_make`

I wish you were right. Unfortunately upstream doesn't support windows builds with configure/make. It looks like this is the reason the port was created with a custom CMakeLists.txt here on vcpkg, and also the reason why upstream is moving to support meson.

**Pull request merged**
