### PR TITLE
[vcpkg-cmake-config] Merge INTERFACE_LINK_LIBRARIES configurations

### PR DESCRIPTION
**Pull request by dg0yt**
- #### What does your PR fix? 
  Fixes direct references in exported cmake config from `INTERFACE_LINK_LIBRARIES` to binary objects in the release tree, affecting debug usage.
  Example: `INTERFACE_LINK_LIBRARIES` of libwebsockets:x64-linux.
  Before this change:
  ~~~
  ${VCPKG_IMPORT_PREFIX}/lib/libssl.a
  ${VCPKG_IMPORT_PREFIX}/lib/libcrypto.a
  -lpthread
  dl
  dl
  -lpthread
  ssl
  crypto
  /usr/lib/x86_64-linux-gnu/libcap.so
  \$<\$<NOT:\$<CONFIG:DEBUG>>:${VCPKG_IMPORT_PREFIX}/lib/libz.a>
  \$<\$<CONFIG:DEBUG>:${VCPKG_IMPORT_PREFIX}/debug/lib/libz.a>
  ${VCPKG_IMPORT_PREFIX}/lib/liblibuv.a
  ~~~
  After this change:
  ~~~
  \$<\$<NOT:\$<CONFIG:DEBUG>>:${VCPKG_IMPORT_PREFIX}/lib/libssl.a>
  \$<\$<CONFIG:DEBUG>:${VCPKG_IMPORT_PREFIX}/debug/lib/libssl.a>
  \$<\$<NOT:\$<CONFIG:DEBUG>>:${VCPKG_IMPORT_PREFIX}/lib/libcrypto.a>
  \$<\$<CONFIG:DEBUG>:${VCPKG_IMPORT_PREFIX}/debug/lib/libcrypto.a>
  -lpthread
  dl
  dl
  -lpthread
  ssl
  crypto
  /usr/lib/x86_64-linux-gnu/libcap.so
  \$<\$<NOT:\$<CONFIG:DEBUG>>:${VCPKG_IMPORT_PREFIX}/lib/libz.a>
  \$<\$<CONFIG:DEBUG>:${VCPKG_IMPORT_PREFIX}/debug/lib/libz.a>
  \$<\$<NOT:\$<CONFIG:DEBUG>>:${VCPKG_IMPORT_PREFIX}/lib/liblibuv.a>
  \$<\$<CONFIG:DEBUG>:${VCPKG_IMPORT_PREFIX}/debug/lib/liblibuv.a>
  ~~~

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all, no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  no: probably to be combined with other PRs.

### CODE REVIEW

**Comment by JackBoosY** [comment]
Can you please merge changes in https://github.com/microsoft/vcpkg/pull/21763 to this PR?
@horenmar Can we do that?

**Comment by dg0yt** [comment]
> Can you please merge changes in #21763 to this PR?

As soon as these changes are approved.

**Comment by dg0yt** [comment]
The aws-c-common error is an issue with repeated calls of this function: The second call processes all cmake files again, but doesn't have the debug files from the first call.

**Comment by horenmar** [comment]
> @horenmar Can we do that?

Sure

**Comment by dg0yt** [comment]
> Can you please merge changes in #21763 to this PR? @horenmar Can we do that?

#21763 changes a different port. So merging that PR here isn't appropriate if it doesn't qualify for https://github.com/microsoft/vcpkg/pull/21415#issuecomment-1015207004.

**Comment by dg0yt** [comment]
The xzing-cpp error on linux seems to be a missing `-lgomp` in linking the zxing-cv executable with opencv4 with feature openmp enabled. At the moment it is not clear to me if this related to this PR, or just another bug uncovered by this particular build. I hope I can build xzing-cpp with opencv4[core,openmp] locally.

Apart from this, CI looks good. The ultimate test would be seing most of the 300 warnings added by #21415 being resolved by this PR (after solving the merge conflict). After all, these are serious issues for the debug builds.

**Comment by dg0yt** [comment]
> The xzing-cpp error on linux seems to be a missing `-lgomp` in linking the zxing-cv executable with opencv4 with feature openmp enabled. At the moment it is not clear to me if this related to this PR, or just another bug uncovered by this particular build. I hope I can build xzing-cpp with opencv4[core,openmp] locally.

I had to learn that this was indeed caused by this PR. This is the downside of strict text matching, and there might have been additional hidden cases. But now it should be fixed in a robust way.

**Review by JackBoosY — APPROVED** [review]

**Review by strega-nil-ms — APPROVED** [review]
This looks good to me; but I'd like to talk about it at the meeting on thursday

**Review by strega-nil — CHANGES_REQUESTED** [review]
Apparently I didn't click "submit review".

**Comment by strega-nil** [comment]
Something @ras0219-msft pointed out: It would probably be good to stop parsing CMake with regex, which we could do by instead taking the `INTERFACE_LINK_LIBRARIES` and wrapping the entire thing in a `$<CONFIG:DEBUG>` block.

**Comment by strega-nil** [comment]
We talked about this at the meeting, and we like the general PR; however, we were wondering if it would be possible to instead wrap the entire lists in `$<CONFIG:Debug>` or w/e, i.e.:

```
    INTERFACE_LINK_LIBRARIES "$<$<CONFIG:Debug>:${debug-libraries}>;$<$<NOT<CONFIG:Debug>>:${release-libraries}>"
```

**Comment by dg0yt** [comment]
> Something @ras0219-msft pointed out: It would probably be good to stop parsing CMake with regex, which we could do by instead taking the `INTERFACE_LINK_LIBRARIES` and wrapping the entire thing in a `$<CONFIG:DEBUG>` block.

How do you suggest to find "the entire thing", inside a cmake command which may also set other properties? 
And how to deal with the fact that `INTERFACE_LINK_LIBRARIES` is a list, not something which can be wrapped as a whole?

I suggest you improve incrementally if desired. You only need to edit the installed script, and build aws-c-common (the port which needs the already-fixed handling) and libwebsockets (known bad config).

**Comment by JackBoosY** [comment]
Ping @strega-nil-ms for reply.

**Comment by dg0yt** [comment]
Three more weeks with no feedback? 
See https://github.com/microsoft/vcpkg/pull/21415 for a reminder how many ports are currently broken.

**Comment by JackBoosY** [comment]
> Three more weeks with no feedback? See #21415 for a reminder how many ports are currently broken. _EDIT:_ Broken by vcpkg cmake config fixup, not upstream.

Sorry for late, I will ping Nicole again.

**Review by strega-nil-ms — APPROVED** [review]
alright; I'm okay with this, but I want @ras0219-msft to say okay.

@dg0yt it is very, very difficult to deal with notifications from this repo; I recommend poking me on Discord or emailing me or something if you want me to take a look immediately

**Comment by dg0yt** [comment]
> @dg0yt it is very, very difficult to deal with notifications from this repo; I recommend poking me on Discord or emailing me or something if you want me to take a look immediately

Contributing is very difficult, too, sometimes. And I don't get notifications when you edit the comment, even with the explicit mention.

**Review by ras0219-msft — APPROVED** [review]
I have small nits like "maybe we could combine the regex searches into 2 instead of 4" and "I'm not 100% confident that this is the right regex" but I agree that the right thing to do at this point is to merge this and iterate on the results.

Thanks for the PR!

**Pull request merged**
