### PR TITLE
[freeglut] Update to 3.2.1

### PR DESCRIPTION
**Pull request by podsvirov**

### CODE REVIEW

**Comment by podsvirov** [comment]
Anybody can help with failed `vcpkg-osx-PR` failed checks?

**Comment by cenit** [comment]
ideally we should get rid of all dependencies from external package managers, building them inside vcpkg or disabling features that require them non-optionally.
As of now, it is possible that the "new" CI infrastructure was rebuilt without Xquartz

**Comment by LilyWangL** [comment]
Hi @podsvirov, our OSX testing is down, but please do make sure that the PR is passing for both Linux and Windows so we can merge as soon as possible once OSX is available again.
Currently, this PR fails on Windows due to port jasper build x64-windows-static failed:
```
CMake Error at D:/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find GLUT (missing: GLUT_glut_LIBRARY)
Call Stack (most recent call first):
  D:/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  D:/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/share/cmake-3.14/Modules/FindGLUT.cmake:130 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  C:/vsts/_work/3/s/scripts/buildsystems/vcpkg.cmake:263 (_find_package)
  CMakeLists.txt:277 (find_package)
```
This PR fails on Linux due to port freeglut build failed:
```
CMake Error at CMakeLists.txt:487 (TARGET_LINK_LIBRARIES):
  The keyword signature for target_link_libraries has already been used with
  the target "freeglut_static".  All uses of target_link_libraries with a
  target must be either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * CMakeLists.txt:410 (TARGET_LINK_LIBRARIES)
```

**Comment by JackBoosY** [comment]
Pinging @podsvirov  for response. Is work still being done for this PR?

**Comment by podsvirov** [comment]
Hello @JackBoosY! I'm here :-)

Changes rebased to `master` and conflicts resolved. But I see that you have advanced further in resolving this issue - that’s good.

I created a request: [#92 CMake BUILD_SHARED_LIBS variable support](https://sourceforge.net/p/freeglut/feature-requests/92/). Can you review and support the discussion?

**Comment by JackBoosY** [comment]
Seems still have regressions in windows and linux, can you resolve them?

**Comment by LilyWangL** [comment]
Duplicate with #9233

**Comment by LilyWangL** [comment]
@podsvirov Is work still being done for this PR?

**Comment by JackBoosY** [comment]
Closing this PR since it seems that no progress is being made. Please reopen if work is still being done.

**Pull request closed without merging**
