### PR TITLE
[protobuf] protobuf v3.12.0

### PR DESCRIPTION
**Pull request by jozefizso**
Update **protobuf** package to release [v3.12.0](https://github.com/protocolbuffers/protobuf/releases/tag/v3.12.0)

### CODE REVIEW

**Comment by LilyWangL** [comment]
@jozefizso Thanks for your PR. Now `ignition-msgs5` build failed with the following error, it build depends on `protobuf`.
`buildtrees\ignition-msgs5\src\sgs5_5.1.0-e593042925\src\Utility.cc : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj`

**Comment by jozefizso** [comment]
The `/bigobj` switch is set in **CMakeLists.txt** already.

```cmake
  # Allow big object
  add_definitions(/bigobj)
```
Source: https://github.com/protocolbuffers/protobuf/blob/3.12.x/cmake/CMakeLists.txt

**Comment by jozefizso** [comment]
I added patch for **ignition-msg5** to use `/bigobj` switch. This should make it compatible with protobuf 3.12.

**Comment by jozefizso** [comment]
The **microsoft.vcpkg.pr (x64_osx)** failed because of git issue:

```
From https://github.com/microsoft/vcpkg
 * [new ref]             refs/pull/11397/merge -> pull/11397/merge
git checkout --progress --force refs/remotes/pull/11397/merge
Previous HEAD position was 35a71e008 Merge 6248f7cc6dd2a25fe8b8f31d8f8ef1c76eec5ed9 into 8a583e80da3b72141105da9003175679af2fcb92
fatal: update_ref failed for ref 'HEAD': cannot lock ref 'HEAD': Unable to create '/Volumes/data/work/1/s/.git/HEAD.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
##[error]Git checkout failed with exit code: 128
```

Source: https://dev.azure.com/vcpkg/public/_build/results?buildId=37113&view=logs&jobId=7b75bd19-17d3-53d4-00fd-23f1a49a8ba4&j=7b75bd19-17d3-53d4-00fd-23f1a49a8ba4&t=6c1a7a3b-b385-5a17-556f-78ddf167924d

**Review by LilyWangL — APPROVED** [review]

**Comment by strega-nil** [comment]
Cool, thanks @jozefizso :)

**Comment by BillyONeal** [comment]
Looks like this might have caused regressions when merged with other changes: https://dev.azure.com/vcpkg/public/_build/results?buildId=37252&view=artifacts&type=publishedArtifacts

```
-- Downloading https://github.com/protocolbuffers/protobuf/archive/v3.12.0.tar.gz...
-- Extracting source C:/agent/_work/1/s/downloads/protocolbuffers-protobuf-v3.12.0.tar.gz
-- Applying patch fix-uwp.patch
-- Applying patch fix-android-log.patch
-- Using source at C:/agent/_work/1/s/buildtrees/protobuf/src/v3.12.0-8ba83cbbdb
CMake Error at ports/protobuf/portfile.cmake:21 (message):
  Cross-targetting protobuf requires the x86-windows protoc to be available.
  Please install protobuf:x86-windows first.
Call Stack (most recent call first):
  scripts/ports.cmake:90 (include)
```

**Comment by LilyWangL** [comment]
Due to the following code, protobuf `arm64-windows arm-uwp x64-uwp` build failed on CI pipelines.
```
if(CMAKE_HOST_WIN32 AND NOT VCPKG_TARGET_ARCHITECTURE MATCHES "x64" AND NOT VCPKG_TARGET_ARCHITECTURE MATCHES "x86")
    set(protobuf_BUILD_PROTOC_BINARIES OFF)
elseif(CMAKE_HOST_WIN32 AND VCPKG_CMAKE_SYSTEM_NAME)
    set(protobuf_BUILD_PROTOC_BINARIES OFF)
else()
    set(protobuf_BUILD_PROTOC_BINARIES ON)
endif()

if(NOT protobuf_BUILD_PROTOC_BINARIES AND NOT EXISTS ${CURRENT_INSTALLED_DIR}/../x86-windows/tools/protobuf)
    message(FATAL_ERROR "Cross-targetting protobuf requires the x86-windows protoc to be available. Please install protobuf:x86-windows first.")
endif()
```
I will submit a PR to fix this issue.

**Pull request merged**
