### PR TITLE
Allow additional environment variables to be set in a clean environment

### PR DESCRIPTION
**Pull request by donny-dont**
Currently the user has no control of what environment variables are passed into the clean environment created by vcpkg. This is not ideal for third party triplets which may have platforms that expect certain environment variables to be set.

I'm proposing that there be an environment variable, `VCPKG_KEEP_ENV_VARS`, which contains a `;` separated list of environment variables to pass along to the clean environment.

### CODE REVIEW

**Comment by donny-dont** [comment]
@ras0219-msft @vicroms this PR is to just get the conversation started. If this is an acceptable approach I'm happy to write up any corresponding documentation and add any additional error checking you all feel is appropriate.

**Comment by vicroms** [comment]
Hi @donny-dont 

These changes look good to me. 
Don't forget to update the relevant documentation.

**Comment by donny-dont** [comment]
@vicroms any particular docs to hit here? Happy to write something out.

**Comment by donny-dont** [comment]
@vicroms added some documentation.

**Comment by donny-dont** [comment]
@vicroms @Rastaban anything else needed?

**Comment by donny-dont** [comment]
Thank you!

**Pull request merged**
