### PR TITLE
[Thorvg] Update Thorvg port to v0.10.7

### PR DESCRIPTION
**Pull request by rinechran**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by MonicaLiu0311** [comment]
The following error occurs when testing feature `tools`:
```
monica@monica003:~/thorvg$ ./vcpkg install thorvg[*] --recurse
Computing installation plan...
The following packages will be built and installed:
    thorvg[core,tools]:x64-linux -> 0.10.7#1

...

-- Configuring x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /usr/bin/python3 /home/monica/thorvg/installed/x64-linux/tools/meson/meson.py -Dstatic=true -Dtools=all -Dengines=sw -Dloaders=all -Dsavers=tvg -Dvector=true -Dbindings=capi -Dtests=false -Dexamples=false --buildtype plain --backend ninja --wrap-mode nodownload --libdir lib -Dlog=true -Dbindir=/home/monica/thorvg/packages/thorvg_x64-linux/debug/bin --native /home/monica/thorvg/buildtrees/thorvg/meson-x64-linux-dbg.log -Ddebug=true --prefix /home/monica/thorvg/packages/thorvg_x64-linux/debug --includedir ../include -Dcmake_prefix_path=['/home/monica/thorvg/installed/x64-linux/debug','/home/monica/thorvg/installed/x64-linux'] /home/monica/thorvg/buildtrees/thorvg/src/v0.10.7-b3d0f65c7e.clean
    Working Directory: /home/monica/thorvg/buildtrees/thorvg/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /home/monica/thorvg/buildtrees/thorvg/config-x64-linux-dbg-meson-log.txt.log
      /home/monica/thorvg/buildtrees/thorvg/config-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:431 (vcpkg_execute_required_process)
  ports/thorvg/portfile.cmake:22 (vcpkg_configure_meson)
  scripts/ports.cmake:147 (include)
```


<details>
<summary><b>config-x64-linux-dbg-meson-log.txt.log</b></summary>
<pre>
Build started at 2023-09-25T03:32:59.436470
Main binary: /usr/bin/python3
Build Options: -Dstatic=true -Dengines=sw -Dloaders=all -Dsavers=tvg -Dvector=true -Dbindings=capi -Dtests=false -Dexamples=false -Dlog=true -Dbindir=/home/monica/thorvg/packages/thorvg_x64-linux/debug/bin -Ddebug=true '-Dcmake_prefix_path=['"'"'/home/monica/thorvg/installed/x64-linux/debug'"'"','"'"'/home/monica/thorvg/installed/x64-linux'"'"']' -Dprefix=/home/monica/thorvg/packages/thorvg_x64-linux/debug -Dincludedir=../include -Dlibdir=lib -Dbackend=ninja -Dbuildtype=plain -Dwrap_mode=nodownload '--native-file /home/monica/thorvg/buildtrees/thorvg/meson-x64-linux-dbg.log'
Python system: Linux
The Meson build system
Version: 0.62.1
Source dir: /home/monica/thorvg/buildtrees/thorvg/src/v0.10.7-b3d0f65c7e.clean
Build dir: /home/monica/thorvg/buildtrees/thorvg/x64-linux-dbg
Build type: native build
Project name: thorvg
Project version: 0.10.7
Sanity testing C++ compiler: /usr/bin/c++
Is cross compiler: False.
Sanity check compiler command line: /usr/bin/c++ sanitycheckcpp.cc -o sanitycheckcpp.exe -fPIC -g -I/home/monica/thorvg/installed/x64-linux/include -D_FILE_OFFSET_BITS=64 -L/home/monica/thorvg/installed/x64-linux/debug/lib
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /home/monica/thorvg/buildtrees/thorvg/x64-linux-dbg/meson-private/sanitycheckcpp.exe
C++ compiler for the host machine: /usr/bin/c++ (gcc 11.4.0 "c++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
C++ linker for the host machine: /usr/bin/c++ ld.bfd 2.38
Sanity testing C++ compiler: /usr/bin/c++
Is cross compiler: False.
Sanity check compiler command line: /usr/bin/c++ sanitycheckcpp.cc -o sanitycheckcpp.exe -D_FILE_OFFSET_BITS=64
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /home/monica/thorvg/buildtrees/thorvg/x64-linux-dbg/meson-private/sanitycheckcpp.exe
C++ compiler for the build machine: /usr/bin/c++ (gcc 11.4.0 "c++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
C++ linker for the build machine: /usr/bin/c++ ld.bfd 2.38
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Configuring config.h using configuration
Running compile:
Working directory:  /home/monica/thorvg/buildtrees/thorvg/x64-linux-dbg/meson-private/tmpi9bv9q0m
Command line:  /usr/bin/c++ -L/home/monica/thorvg/installed/x64-linux/debug/lib -I/home/monica/thorvg/installed/x64-linux/include /home/monica/thorvg/buildtrees/thorvg/x64-linux-dbg/meson-private/tmpi9bv9q0m/testfile.cpp -o /home/monica/thorvg/buildtrees/thorvg/x64-linux-dbg/meson-private/tmpi9bv9q0m/output.exe -fPIC -g -D_FILE_OFFSET_BITS=64 -O0 -fpermissive -Wl,--start-group -lpthread -Wl,--end-group -Wl,--allow-shlib-undefined

Code:
 int main(void) { return 0; }

Compiler stdout:

Compiler stderr:

Library pthread found: YES
Message:

Summary:
    ThorVG version:        0.10.7
    Build Type:            plain
    Prefix:                /home/monica/thorvg/packages/thorvg_x64-linux/debug
    SIMD Instruction:      avx
    Raster Engine (SW):    true
    Raster Engine (GL):    false
    Loader (TVG):          true
    Loader (SVG):          true
    Loader (PNG):          true
    Loader (JPG):          true
    Loader (WEBP_BETA):    false
    Loader (LOTTIE_BETA):  false
    Saver (TVG):           true
    Binding (CAPI):        true
    Binding (WASM_BETA):   false
    Log Message:           true
    Tests:                 false
    Examples:              false
    Tool (Svg2Tvg):        false
    Tool (Svg2Png):        false


Build targets in project: 1

thorvg 0.10.7

  User defined options
    Native files     : /home/monica/thorvg/buildtrees/thorvg/meson-x64-linux-dbg.log
    backend          : ninja
    bindir           : /home/monica/thorvg/packages/thorvg_x64-linux/debug/bin
    buildtype        : plain
    cmake_prefix_path: ['/home/monica/thorvg/installed/x64-linux/debug','/home/monica/thorvg/installed/x64-linux']
    debug            : true
    includedir       : ../include
    libdir           : lib
    prefix           : /home/monica/thorvg/packages/thorvg_x64-linux/debug
    wrap_mode        : nodownload
    bindings         : capi
    engines          : sw
    examples         : false
    loaders          : all
    log              : true
    savers           : tvg
    static           : true
    tests            : false
    vector           : true

Found ninja-1.10.2 at /home/monica/thorvg/downloads/tools/ninja/1.10.2-linux/ninja
Running compile:
Working directory:  /tmp/tmpvs6obcln
Command line:  /usr/bin/c++ /tmp/tmpvs6obcln/testfile.cpp -o /tmp/tmpvs6obcln/output.obj -D_FILE_OFFSET_BITS=64 -c -std=c++14

Code:
 int i = static_cast<int>(0);
Compiler stdout:

Compiler stderr:

Compiler accepts -std=c++14: YES
</pre></details>



<details>
<summary><b>/config-x64-linux-dbg-out.log</b></summary>
<pre>
WARNING: Recommend using either -Dbuildtype or -Doptimization + -Ddebug. Using both is redundant since they override each other. See: https://mesonbuild.com/Builtin-options.html#build-type-options
The Meson build system
Version: 0.62.1
Source dir: /home/monica/thorvg/buildtrees/thorvg/src/v0.10.7-b3d0f65c7e.clean
Build dir: /home/monica/thorvg/buildtrees/thorvg/x64-linux-dbg
Build type: native build
Project name: thorvg
Project version: 0.10.7
C++ compiler for the host machine: /usr/bin/c++ (gcc 11.4.0 "c++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
C++ linker for the host machine: /usr/bin/c++ ld.bfd 2.38
Host machine cpu family: x86_64
Host machine cpu: x86_64
Configuring config.h using configuration
Library pthread found: YES
Message:

Summary:
    ThorVG version:        0.10.7
    Build Type:            plain
    Prefix:                /home/monica/thorvg/packages/thorvg_x64-linux/debug
    SIMD Instruction:      avx
    Raster Engine (SW):    true
    Raster Engine (GL):    false
    Loader (TVG):          true
    Loader (SVG):          true
    Loader (PNG):          true
    Loader (JPG):          true
    Loader (WEBP_BETA):    false
    Loader (LOTTIE_BETA):  false
    Saver (TVG):           true
    Binding (CAPI):        true
    Binding (WASM_BETA):   false
    Log Message:           true
    Tests:                 false
    Examples:              false
    Tool (Svg2Tvg):        false
    Tool (Svg2Png):        false


Build targets in project: 1

thorvg 0.10.7

  User defined options
    Native files     : /home/monica/thorvg/buildtrees/thorvg/meson-x64-linux-dbg.log
    backend          : ninja
    bindir           : /home/monica/thorvg/packages/thorvg_x64-linux/debug/bin
    buildtype        : plain
    cmake_prefix_path: ['/home/monica/thorvg/installed/x64-linux/debug','/home/monica/thorvg/installed/x64-linux']
    debug            : true
    includedir       : ../include
    libdir           : lib
    prefix           : /home/monica/thorvg/packages/thorvg_x64-linux/debug
    wrap_mode        : nodownload
    bindings         : capi
    engines          : sw
    examples         : false
    loaders          : all
    log              : true
    savers           : tvg
    static           : true
    tests            : false
    vector           : true

Found ninja-1.10.2 at /home/monica/thorvg/downloads/tools/ninja/1.10.2-linux/ninja
</pre></details>

**Comment by MonicaLiu0311** [comment]
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review".

**Comment by rinechran** [comment]
> Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review".

I'll check

**Comment by rinechran** [comment]
a new version was released , so i closed that PR and created a pr for the new versionhttps://github.com/microsoft/vcpkg/pull/34202

**Pull request closed without merging**
