### PR TITLE
[gdal] add feature to support KEA

### PR DESCRIPTION
**Pull request by rcoup**
[kealib](http://www.kealib.org/) has an existing [vcpkg port](https://github.com/microsoft/vcpkg/tree/master/ports/kealib), and GDAL has a [KEA driver](https://gdal.org/drivers/raster/kea.html#raster-kea). Enable [build support](https://gdal.org/development/building_from_source.html#kea) for the KEA format in the GDAL port by adding a new `kea` feature.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] ~~SHA512s are updated for each updated download~~
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by jimwang118** [comment]
> @jimwang118 what OS/triplet was that on? Tested/worked ok for me, but I can try other configs

I am testing on `x64-Windows`. The compiler is compiled using vs2022.
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/11607789/config-x64-windows-out.log)

**Comment by jimwang118** [comment]
@rcoup Thanks for your PR, Is work still being done for this PR?

**Comment by rcoup** [comment]
@jimwang118 picking this up again...

works on Linux. I agree it's not working correctly on Windows, GDAL's cmake doesn't find the library.

Kealib doesn't seem to be exporting it's CMake config, I think maybe it needs a patch like this, since the [targets are `libkea::kea` & `libkea::Kealib`](https://github.com/ubarsc/kealib/blob/master/src/CMakeLists.txt#L102-L105)

```patch
diff --git a/ports/kealib/portfile.cmake b/ports/kealib/portfile.cmake
index c6cebcae9..e58223f51 100644
--- a/ports/kealib/portfile.cmake
+++ b/ports/kealib/portfile.cmake
@@ -21,7 +21,7 @@ if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")
     file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/bin" "${CURRENT_PACKAGES_DIR}/bin")
 endif()

-vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/libkea)
+vcpkg_cmake_config_fixup(PACKAGE_NAME libkea CONFIG_PATH lib/cmake/libkea)

 file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
```

 But then you end up with an installed dir that looks like:
```
installed/arm64-osx/share/kealib
installed/arm64-osx/share/kealib/vcpkg.spdx.json
installed/arm64-osx/share/kealib/vcpkg_abi_info.txt
installed/arm64-osx/share/kealib/copyright
installed/arm64-osx/share/libkea
installed/arm64-osx/share/libkea/libkeaTargets-release.cmake
installed/arm64-osx/share/libkea/libkeaConfigVersion.cmake
installed/arm64-osx/share/libkea/libkeaConfig.cmake
installed/arm64-osx/share/libkea/libkeaTargets-debug.cmake
installed/arm64-osx/share/libkea/libkeaTargets.cmake
```

which doesn't seem quite right either?

**Comment by dg0yt** [comment]
> ```diff
> -vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/libkea)
> +vcpkg_cmake_config_fixup(PACKAGE_NAME libkea CONFIG_PATH lib/cmake/libkea)
> ```

Please add this to your PR.
(I don't know if this fixes the issue - find_package in gdal is tricky.)

**Comment by dg0yt** [comment]
You may temporarily make kea a default feature to test in vcpkg CI.

**Pull request closed without merging**
