### PR TITLE
[grpc] Upgrade gRPC to 1.17.1.

### PR DESCRIPTION
**Pull request by coryan**

### CODE REVIEW

**Comment by KindDragon** [comment]
I think better use latest version 1.17.0 https://github.com/grpc/grpc/releases/tag/v1.17.0

**Comment by coryan** [comment]
Happy to go for 1.17.0 if that is preferred, @Rastaban ?

**Comment by Rastaban** [comment]
@coryan The latest version sounds good to me!  It looks like they posted 1.17.1 earlier today.

**Comment by coryan** [comment]
PTAL.

**Comment by Rastaban** [comment]
I am seeing failures on arm-uwp and x64-uwp.  Maybe the patch needs updated too?

**Comment by Rastaban** [comment]
I may have a fix for uwp failures, testing now.

**Pull request merged**
