### PR TITLE
[vcpkg] Add static triplet for arm-windows

### PR DESCRIPTION
**Pull request by ysc3839**

### CODE REVIEW

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
LGTM, thanks for your PR @ysc3839.

**Comment by strega-nil-ms** [comment]
Is there a reason you need this? As far as I know, there is exactly one machine that runs Windows on ARM32, which makes it seem to me like there isn't a real use to this...

**Comment by ysc3839** [comment]
@strega-nil-ms
I want to add arm/arm64 support for my project [FontMod](https://github.com/ysc3839/FontMod), which is a GDI font replacing library.
Although it's nearly no ARM-only device, there still some ARM apps. So my project need to support these apps.

**Pull request merged**
