### PR TITLE
Default to arm64 target on arm64 hosts with VS2019 or above

### PR DESCRIPTION
**Pull request by playmer**
- #### What does your PR fix?
  Fixes an issue where `cmake ..` selected ARM64 on an ARM64 host machine, but vcpkg selects the x64 triplet because it isn't aware that cmake could make that decision based on host env in the 2019 generators and above.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  This should only affect Windows hosts, and even then only ARM64 ones. That said I'm unsure if 32 bit Windows might need a similar change? I don't have an install locally to test.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  I believe so yes.

### CODE REVIEW

**Comment by JackBoosY** [comment]
I'm not familiar with this part, request @BillyONeal review.

**Comment by BillyONeal** [comment]
Why not instead change:

```
elseif(CMAKE_GENERATOR_PLATFORM MATCHES "^[Ww][Ii][Nn]32$")
    set(Z_VCPKG_TARGET_TRIPLET_ARCH x86)
elseif(CMAKE_GENERATOR_PLATFORM MATCHES "^[Xx]64$")
    set(Z_VCPKG_TARGET_TRIPLET_ARCH x64)
elseif(CMAKE_GENERATOR_PLATFORM MATCHES "^[Aa][Rr][Mm]$")
    set(Z_VCPKG_TARGET_TRIPLET_ARCH arm)
elseif(CMAKE_GENERATOR_PLATFORM MATCHES "^[Aa][Rr][Mm]64$")
    set(Z_VCPKG_TARGET_TRIPLET_ARCH arm64)
```

to

```
elseif(CMAKE_GENERATOR_PLATFORM MATCHES "^[Ww][Ii][Nn]32$" OR CMAKE_VS_PLATFORM_NAME_DEFAULT MATCHES "^[Ww][Ii][Nn]32$")
    set(Z_VCPKG_TARGET_TRIPLET_ARCH x86)
elseif(CMAKE_GENERATOR_PLATFORM MATCHES "^[Xx]64$" OR CMAKE_VS_PLATFORM_NAME_DEFAULT MATCHES "^[Xx]64$")
    set(Z_VCPKG_TARGET_TRIPLET_ARCH x64)
elseif(CMAKE_GENERATOR_PLATFORM MATCHES "^[Aa][Rr][Mm]$" OR CMAKE_VS_PLATFORM_NAME_DEFAULT MATCHES "^[Aa][Rr][Mm]$")
    set(Z_VCPKG_TARGET_TRIPLET_ARCH arm)
elseif(CMAKE_GENERATOR_PLATFORM MATCHES "^[Aa][Rr][Mm]64$" OR CMAKE_VS_PLATFORM_NAME_DEFAULT MATCHES "^[Aa][Rr][Mm]64$")
    set(Z_VCPKG_TARGET_TRIPLET_ARCH arm64)
```

above this which would also make it work for other architectures?

Note that we can't in general assume VS2022 means that is set because that variable is new in CMake 3.14.3.

**Comment by Neumann-A** [comment]
@BillyONeal That logic is wrong.

**Comment by BillyONeal** [comment]
> @BillyONeal That logic is wrong.

OK, I'm not sure on the exact interactions between these variables. Only that doing this for arm64 and nothing else seems incorrect.

**Comment by playmer** [comment]
I haven't had a chance to test the above yet, but the main issue (I think) is that this is just the default if no platform is selected and we're specifically using either the VS 2019 or VS 2022 generators (and presumably whatever comes next, but we'll see). So we can't always check it like this. I think if the user were to invoke `cmake -G "Visual Studio 17 2022" -A ARM64`  on an Windows x64 machine, the above would select the x64 triplet because the default on x64 would be x64 and so we'd for through that path instead of the ARM64 one.

That said using the regex matching does make sense, I can adjust that no problem. I can also add the other cases as well, but I don't have machines/VMs to test the Windows x86 or Windows arm cases.

**Comment by Neumann-A** [comment]
@BillyONeal How many **native** architectures are there for VS?

`CMAKE_VS_PLATFORM_NAME_DEFAULT` also don't need a regex match. It will be defined by CMake with a well defined casing.

**Comment by BillyONeal** [comment]
> @BillyONeal How many **native** architectures are there for VS?

Hmmm... fair enough. This is setting target though. Maybe that makes sense. I'm not sure though.

**Review by BillyONeal — APPROVED** [review]

**Pull request merged**
