### PR TITLE
Fix outdated comment in vcpkg_from_github.cmake

### PR DESCRIPTION
**Pull request by Pospelove**

### CODE REVIEW

**Comment by dg0yt** [comment]
This will rebuild many ports.

**Comment by Pospelove** [comment]
> This will rebuild many ports.
Closing.
will probably come with that in case of major rework of this script.

**Comment by cnSchwarzer** [comment]
Can anyone stop this CI, it seems this queued many PR checks

**Comment by Pospelove** [comment]
oops I'm sorry
didn't expect that

**Pull request closed without merging**
