### PR TITLE
[libwebp] Fixed build error ARM64 Windows 10

### PR DESCRIPTION
**Pull request by shibayan**
`libwebp[core]` does not require `opengl` dependency. Only the extra `vwebp` app requires `opengl`.

### CODE REVIEW

**Comment by shibayan** [comment]
A regression warning has occurred in `leptonica:arm-uwp`, and it was found that the library could not be built for UWP, so the build error seems to be correct.

**Comment by NancyLi1013** [comment]
Hi @shibayan thanks for this PR.
what issue does this PR fix? Please open an issue so others may replicate this problem.

**Comment by shibayan** [comment]
Thank you. I opened new issue #9309

**Review by NancyLi1013 — APPROVED** [review]

**Review by dan-shaw — APPROVED** [review]

**Pull request merged**
