### PR TITLE
[libfuse] add new port

### PR DESCRIPTION
**Pull request by FredyVia**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html).
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [x] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by MonicaLiu0311** [comment]
Successfully found `fuse3.pc` using `pkg_check_modules`.

IMPORTANT: you should define `FUSE_USE_VERSION` before including this header:
https://github.com/libfuse/libfuse/blob/fuse-3.16.2/include/fuse.h#L12-L17
https://github.com/libfuse/libfuse/blob/fuse-3.16.2/include/fuse_common.h#L918-L924

**Review by MonicaLiu0311 — DISMISSED** [review]

**Review by BillyONeal — DISMISSED** [review]
Waiting for a new build because we just updated meson

**Comment by BillyONeal** [comment]
Looks like updated meson hates you :( . /cc @Neumann-A

**Comment by FredyVia** [comment]
```
ERROR: Value "plain" (of type "string") for combo option "Optimization level" is not one of the choices.
Possible choices are (as string): "0", "g", "1", "2", "3", "s".
```
but option "Optimization level" is defined here
[scripts/cmake/vcpkg_configure_meson.cmake](https://github.com/microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_configure_meson.cmake):
```
vcpkg_list(APPEND arg_OPTIONS --backend ninja --wrap-mode nodownload -Dbuildtype=plain -Doptimization=plain)
```
how to fix this problem? I'm not very familiar with meson.

**Comment by Neumann-A** [comment]
Missing dep on vcpkg-tool-meson.

**Review by MonicaLiu0311 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the fix and sorry about the meson mess!

**Pull request merged**
