### PR TITLE
[cmocka] Update to 2020-08-01

### PR DESCRIPTION
**Pull request by myd7349**
**Describe the pull request**

- What does your PR fix? 
N/A.

- Which triplets are supported/not supported? Have you updated the CI baseline?
N/A. No.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
No.

### CODE REVIEW

**Review by NancyLi1013 — COMMENTED** [review]
Why do you remove usage and vcpkg-cmake-wrapper? Could you please make it clarify for this?

**Comment by NancyLi1013** [comment]
Hi @myd7349 

Is this PR ready for review?

**Comment by myd7349** [comment]
> 
> 
> Why do you remove usage and vcpkg-cmake-wrapper? Could you please make it clarify for this?

Hi! @NancyLi1013 Sorry for the long delay. `cmocka`'s CMakeLists.txt has evolved a lot since the first commit of this port. And now it provides a modern CMake target:
```cmake
find_package(cmocka CONFIG REQUIRED)
target_link_libraries(main PRIVATE cmocka::cmocka)
```
So the usage we had here is out of fashion. 
For the same reason, the `vcpkg-cmake-wrapper.cmake` is unnecessary any more.



> 
> 
> Hi @myd7349
> 
> Is this PR ready for review?

Yes. Please.

**Review by NancyLi1013 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
