### PR TITLE
[gdal] Update to 3.3.2

### PR DESCRIPTION
**Pull request by dg0yt**
- #### What does your PR fix?  
  - Updates gdal to 3.3.2 (#19861).
  - Switches to github download method which allows HEAD builds.
    Note that this increases download size, due to test data.
  - Prevent abseil dependency/build failure (#17609).

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  unchanged

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  yes

### CODE REVIEW

**Comment by BillyONeal** [comment]
Thanks for your help, sorry for the traffic on your PR; I need to shut down the insecure before-patch-tuesday VMs :)

**Comment by dg0yt** [comment]
I will put the feature/dependency improvements into another PR so that this update is not delayed.

**Comment by BillyONeal** [comment]
Thanks for the version update!

**Comment by BillyONeal** [comment]
It looks like gdal is now causing our CI to break :(

**Pull request merged**
