### PR TITLE
[distorm, scylla_wrapper, devicenameresolver] init

### PR DESCRIPTION
**Pull request by atkawa7**

### CODE REVIEW

**Comment by atkawa7** [comment]
@ras0219-msft @alexkaratarakis ping

**Comment by LarryIII** [comment]
I am seeing new build failures on the following ports with this PR. Let me know if you need build log.
```
Processing arm-uwp                        404 vs 403
    devicenameresolver                                          Fail 
    scylla-wrapper                                              Fail 
Processing arm64-windows                  454 vs 452
    scylla-wrapper                                              Fail 
Processing x64-linux                      586 vs 585
    devicenameresolver                                          Fail 
    scylla-wrapper                                              Fail 
Processing x64-osx                        578 vs 577
    devicenameresolver                                          Fail 
    scylla-wrapper                                              Fail 
Processing x64-uwp                        432 vs 431
    devicenameresolver                                          Fail 
    scylla-wrapper                                              Fail 
Processing x64-windows-static             761 vs 759
    scylla-wrapper                                              Fail 
```

**Comment by atkawa7** [comment]
@LarryIII Currently windows is supported only

**Comment by LarryIII** [comment]
> @LarryIII Currently windows is supported only

How about x64-windows-static  and arm64-windows? Please consider. if some archs or platform not support, we should add judgement to reminder. See https://github.com/Microsoft/vcpkg/pull/3272 as an example.

**Comment by ras0219-msft** [comment]
LGTM, thanks for the PR and sorry for the long delay in merging!

**Pull request merged**
