### PR TITLE
[libwebsockets] Fix usage, export include path

### LINKED ISSUE #16466: find_path not working on Windows
**Describe the bug**
I am using libwebsockts package. 

On Mac, following code can find the libwebsockts.h include folder. But on Windows, I got "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND" error.
```
find_package(libwebsockets CONFIG REQUIRED)
find_path(LIBWEBSOCKETS_INCLUDE_DIR libwebsockets.h)
```

**Environment**
- OS: Windows Server 2019
- Compiler: Visual Studio 16 2019

**To Reproduce**
1. ./vcpkg install libwebsockets
2. 
```
git clone https://github.com/SlickTech/slicksocket.git
cd slicksocket
mkdir build
cd build
cmake .. -DCMAKE_TOOLCHAN_FILE=<vcpkg_patah>\vcpkg\scripts\buildsystems\vcpkg.cmake
```

**Expected behavior**
Expect that the find_path works on Windows as well.

**Failure logs** 
````
C:\repo\slicksocket\build\Debug>cmake ../.. -DCMAKE_TOOLCHAIN_FILE=C:\repo\vcpkg\scripts\buildsystems\vcpkg.cmake
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.17763.
-- The CXX compiler identification is MSVC 19.28.29336.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Failed
-- Performing Test COMPILER_HAS_DEPRECATED
-- Performing Test COMPILER_HAS_DEPRECATED - Success
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBWEBSOCKETS_INCLUDE_DIR
   used as include directory in directory C:/repo/slicksocket
   used as include directory in directory C:/repo/slicksocket
   used as include directory in directory C:/repo/slicksocket/tests

CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of "ZERO_CHECK":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND


CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of "ZERO_CHECK":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of "ZERO_CHECK":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of "ZERO_CHECK":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of "slicksocket":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of "slicksocket":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in CMakeLists.txt:

  Found relative path while evaluating include directories of "slicksocket":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in CMakeLists.txt:

  Found relative path while evaluating include directories of "slicksocket":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in CMakeLists.txt:

  Found relative path while evaluating include directories of "slicksocket":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of "slicksocket":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of "slicksocket":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of "slicksocket":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of "slicksocket":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of "slicksocket":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of "slicksocket":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of "slicksocket":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of  "slicksocket_shared":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of "slicksocket_shared":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of  "slicksocket_shared":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of  "slicksocket_shared":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of  "slicksocket_shared":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of  "slicksocket_shared":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of  "slicksocket_shared":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of  "slicksocket_shared":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of  "slicksocket_shared":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of  "slicksocket_shared":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of "slicksocket_shared":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of "slicksocket_shared":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of "ALL_BUILD":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of "ALL_BUILD":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of "ALL_BUILD":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of "ALL_BUILD":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of "slicksocket_tests":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of  "slicksocket_tests":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of  "slicksocket_tests":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of  "slicksocket_tests":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in tests/CMakeLists.txt:
 Found relative path while evaluating include directories of  "slicksocket_tests":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of  "slicksocket_tests":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of  "slicksocket_tests":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of  "slicksocket_tests":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of  "slicksocket_tests":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of  "slicksocket_tests":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of  "slicksocket_tests":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of  "slicksocket_tests":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of "ALL_BUILD":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of "ALL_BUILD":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of "ALL_BUILD":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of "ALL_BUILD":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND"


-- Generating done
````
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Additional context**

### PR DESCRIPTION
**Pull request by JackBoosY**
Both the marco `LIBWEBSOCKETS_INCLUDE_DIR` and the `INTERFACE_INLUCDE_DIR` is empty:
```
CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of "ZERO_CHECK":

    "LIBWEBSOCKETS_INCLUDE_DIR-NOTFOUND
```
```
set_target_properties(websockets_shared PROPERTIES
  INTERFACE_LINK_LIBRARIES "${_IMPORT_PREFIX}/lib/libssl.lib;${_IMPORT_PREFIX}/lib/libcrypto.lib;\$<\$<NOT:\$<CONFIG:DEBUG>>:${_IMPORT_PREFIX}/lib/pthreadVC3.lib>;\$<\$<CONFIG:DEBUG>:${_IMPORT_PREFIX}/debug/lib/pthreadVC3d.lib>;\$<\$<NOT:\$<CONFIG:DEBUG>>:${_IMPORT_PREFIX}/lib/pthreadVC3.lib>;\$<\$<CONFIG:DEBUG>:${_IMPORT_PREFIX}/debug/lib/pthreadVC3d.lib>;ws2_32.lib;userenv.lib;psapi.lib;iphlpapi.lib;crypt32.lib;\$<\$<NOT:\$<CONFIG:DEBUG>>:${_IMPORT_PREFIX}/lib/zlib.lib>;\$<\$<CONFIG:DEBUG>:${_IMPORT_PREFIX}/debug/lib/zlibd.lib>;${_IMPORT_PREFIX}/lib/libuv.lib"
)
```
Fix this.

Fixes #16466.

### CODE REVIEW

**Comment by JackBoosY** [comment]
@kzhdev  Can you please test this PR?

Thanks.

**Comment by JackBoosY** [comment]
Depend on #17011.

**Comment by kzhdev** [comment]
@JackBoosY Verified the issue is fixed. Thanks.

**Review by NancyLi1013 — APPROVED** [review]

**Pull request merged**
