### PR TITLE
[vcglib] update to 2021.10

### LINKED ISSUE #17212: [vcglib] update to 2020.09
Library name: vcglib

New version number: 2020.09

URL: https://github.com/cnr-isti-vclab/vcglib/releases/tag/2020.09

### PR DESCRIPTION
**Pull request by JonLiu1993**
Fix #17212 

Update vcglib to the latest version 2021.10

Note: no feature need to test

### CODE REVIEW

**Comment by NancyLi1013** [comment]
Please update to the latest version[ 2020.12](https://github.com/cnr-isti-vclab/vcglib/releases/tag/2020.12).

**Comment by Cheney-W** [comment]
The latest version of vcglib is https://github.com/cnr-isti-vclab/vcglib/releases/tag/2021.10, could you please update this port to it?

**Comment by JonLiu1993** [comment]
Temporarily turn off this pr, I will reopen it when I have time to deal with this pr

**Comment by JonLiu1993** [comment]
Duplicate of #25135

**Pull request closed without merging**
