### PR TITLE
[kissfft] Add new port

### PR DESCRIPTION
**Pull request by myd7349**
https://github.com/mborgerding/kissfft

### CODE REVIEW

**Comment by NancyLi1013** [comment]
Hi @myd7349 thanks for this PR.
What issue does this PR fix? Please open an issue so others may replicate this problem.

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
@myd7349 sorry, there is not necessary an issue for new port.

**Comment by JackBoosY** [comment]
LGTM, needs to wait to resolve the osg-qt regression in #10637.

**Comment by strega-nil** [comment]
Cool, thanks @myd7349 :) This looks great :D

**Pull request merged**
