### PR TITLE
[luajit] Bump version and fix #28004

### LINKED ISSUE #28004: [luajit] VCPKG_OSX_DEPLOYMENT_TARGET not working
**Describe the bug**

I add this triplets, set `VCPKG_OSX_DEPLOYMENT_TARGET` to `10.15` 

```cmake
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Darwin)
set(VCPKG_OSX_ARCHITECTURES x86_64)
set(VCPKG_OSX_DEPLOYMENT_TARGET 10.15)
```

And got these link warnings.

```
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_vm.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_assert.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_gc.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_err.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_char.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_bc.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_obj.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_buf.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_str.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_tab.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_func.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_udata.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_meta.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_debug.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_prng.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_state.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_dispatch.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_vmevent.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_vmmath.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_strscan.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_strfmt.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_strfmt_num.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_serialize.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_api.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_profile.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_lex.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_parse.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_bcread.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_bcwrite.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_load.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_ir.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_opt_mem.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_opt_fold.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_opt_narrow.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_opt_dce.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_opt_loop.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_opt_split.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_opt_sink.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_mcode.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_snap.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_record.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_crecord.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_ffrecord.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_asm.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_trace.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_gdbjit.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_ctype.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_cdata.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_cconv.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_ccall.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_ccallback.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_carith.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_clib.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_cparse.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_lib.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lj_alloc.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lib_aux.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lib_base.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lib_math.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lib_bit.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lib_string.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lib_table.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lib_io.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lib_os.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lib_package.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lib_debug.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lib_jit.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lib_ffi.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lib_buffer.o)) was built for newer macOS version (12.0) than being linked (10.15)
ld: warning: object file (/Users/xiaozhuai/vcpkg/vcpkg/installed/x64-osx-catalina-static-release/lib/libluajit-5.1.a(lib_init.o)) was built for newer macOS version (12.0) than being linked (10.15)
```

**Environment**
macOS Monterey 12.6.1

### PR DESCRIPTION
**Pull request by xiaozhuai**
**Describe the pull request**

- #### What does your PR fix?
1. Bump version
2. Fix #28004

- #### Which triplets are supported/not supported? 
1. x64-osx
2. x64-osx-dynamic
3. x64-osx-release
4. arm64-osx
5. arm64-osx-dynamic

### CODE REVIEW

**Comment by xiaozhuai** [comment]
Hello @Neumann-A , would you please review this pr? Thanks!

**Comment by xiaozhuai** [comment]
Hello @dg0yt, please review this pr. Thanks!

**Review by JonLiu1993 — APPROVED** [review]

**Comment by JonLiu1993** [comment]
@dg0yt  @Neumann-A , would you please review this pr?

**Comment by JavierMatosD** [comment]
Thank you!

**Pull request merged**
