### PR TITLE
[uwebsockets] Update to 19.9.0

### PR DESCRIPTION
**Pull request by chausner**
**Describe the pull request**

- #### What does your PR fix?  
  Updates uwebsockets to 19.9.0

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  As before, Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run ./vcpkg x-add-version --all and committed the result?  
  Yes

### CODE REVIEW

**Review by JonLiu1993 — APPROVED** [review]

**Review by JonLiu1993 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the update!

**Comment by SecretsNetwork** [comment]
@chausner can you also update it to 20.5.0

**Comment by chausner** [comment]
> @chausner can you also update it to 20.5.0

Done: https://github.com/microsoft/vcpkg/pull/20513

**Comment by SecretsNetwork** [comment]
> > @chausner can you also update it to 20.5.0
> 
> Done: #20513
Many thanks <3

**Pull request merged**
