### PR TITLE
Update tool to 2021-11-19.

### PR DESCRIPTION
**Pull request by BillyONeal**

### CODE REVIEW

**Review by ras0219-msft — APPROVED** [review]

**Review by vicroms — APPROVED** [review]

**Comment by Maclain27** [comment]
**maclain27** 

> asking for this repository to run Arduino in vs code readme anytime I need change!

**Comment by Maclain27** [comment]
> **maclain27**
> 
> > asking for this repository to run Arduino in vs code readme anytime I need change!

**Comment by BillyONeal** [comment]
I don't understand what you mean @Maclain27

**Comment by Maclain27** [comment]
Hi it me  i said  i need access to vcpkg to run Arduino in vs code us it was recommeder and feel  free to tell if i need something wrong!!!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Maclain27** [comment]
- I mean I was runing Arduino in vs code and than I got error it was recommder to install vcpkg to found the library!

**Pull request merged**
