### PR TITLE
[restinio] update to 0.6.18

### PR DESCRIPTION
**Pull request by eao197**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- ~~[ ] The "supports" clause reflects platforms that may be fixed by this new version~~
- ~~[ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- ~~[ ] Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by jimwang118** [comment]
After the installation is complete, the following error is prompted when using it.
```
Error		CMake Error at F:/restinio/installed/x64-windows/share/restinio/restinio-targets.cmake:60 (set_target_properties):
  The link interface of target "restinio::restinio" contains:

    fmt::fmt-header-only

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.		F:/restinio/installed/x64-windows/share/restinio/restinio-targets.cmake	60	

```

**Comment by eao197** [comment]
Hi, @jimwang118 

Could you please explain what does it mean "when using it"? Do you use a test project that uses RESTinio as a dependency?

I've just checked with [that demo project](https://github.com/Stiffstream/restinio-crud-example) and have no any errors (cmake 3.26.2 and VS2019 were used for checking).

**Comment by jimwang118** [comment]
> Hi, @jimwang118
> 
> Could you please explain what does it mean "when using it"? Do you use a test project that uses RESTinio as a dependency?
> 
> I've just checked with [that demo project](https://github.com/Stiffstream/restinio-crud-example) and have no any errors (cmake 3.26.2 and VS2019 were used for checking).

I added less `find_package(fmt CONFIG REQUIRED)` and `find_package(unofficial-http-parser CONFIG REQUIRED)` in cmakelists.txt
, after adding this sentence, the compilation is normal.

**Comment by jimwang118** [comment]
The usage has been tested successfully locally. 
```
find_package(restinio CONFIG REQUIRED)
target_link_libraries(main PRIVATE restinio::restinio)
```

**Comment by dg0yt** [comment]
Does the CMake config lack `find_dependency` calls? 
The demo projectt might hide the fact if it has additional `find_package` calls.

**Comment by eao197** [comment]
> Does the CMake config lack find_dependency calls?

RESTinio has several usage scenarios (with or without using CMake, with or without using external dependencies and so on). Because of that it's [officially required](https://stiffstream.com/en/docs/restinio/0.6/obtaining.html#id1) to call `find_package` in CMakeLists.txt file of the projects that uses RESTinio.

**Comment by dg0yt** [comment]
We are only talking about usage with CMake when we talk about CMake config.

IMO the linked official usage "with vcpkg" ... is just documenting the current imperfect usage with vcpkg. 
- It promotes vcpkg lock-in by referring to unofficial `http-parser` cmake config, while vcpkg discourages any lock-in.
- It breaks good CMake package resolution in config mode: With `find_dependency`, CMake might tolerate one config not being acceptable due to lacking dependencies, and continue search in other prefixes. 

The user shouldn't need to know the dependencies. In particular, the user shouldn't need to change e.g. anything when  `http-parser` starts to provide official CMake config.

**Comment by dg0yt** [comment]
FTR the linked page also has this:

> ### Include RESTinio in your project
> #### Canonical way
> ...
> ~~~
> find_package(restinio REQUIRED)
> 
>  # Make your project dependent on restinio,
>  # and let cmake deal with all the headers paths and linked libs.
>  target_link_libraries(MyProject PRIVATE restinio::restinio)

Please make this just work.

**Comment by eao197** [comment]
@dg0yt 

I understand all this, but we have what we have and fixing the behavior takes time and resources that need to be found. Version 0.6.18 fixes a bug found by a RESTinio user, and it seems to me that it is better to update vcpkg's version of RESTinio now than to postpone it for some time (RESTinio has been in vcpkg in its current form for several years, and those who use RESTinio from vcpkg already have the appropriate find_package in their CMakeLists.txt).

**Comment by eao197** [comment]
> FTR the linked page also has this:

There is important fragment you don't mention:

"Canonical way

First, build and install RESTinio dependencies. Then build and install RESTinio itself with -DRESTINIO_FIND_DEPS=ON and passing CMAKE_PREFIX_PATH to locate dependencies."

A user have to do several steps manually. vcpkg takes care of some of those steps, but it also hides some details and it makes things a bit harder. That is why we described usage of vcpkg a bit differently.

> Please make this just work.

I hope we make it one day.

**Comment by dg0yt** [comment]
Extended PR in #30655.

**Comment by jimwang118** [comment]
The fixes in PR https://github.com/microsoft/vcpkg/pull/30655 are better, can we close this PR?

**Comment by eao197** [comment]
Yes.

**Pull request closed without merging**
