### PR TITLE
[qt5-base] no absolute paths

### PR DESCRIPTION
**Pull request by autoantwort**
For #20469

### CODE REVIEW

**Review by LilyWangLL — APPROVED** [review]

**Comment by BillyONeal** [comment]
@Neumann-A Are you OK with this?

**Comment by Neumann-A** [comment]
> @Neumann-A Are you OK with this?

yeah but I don't guarantee that the pc files will be useable with that. Especially for static builds the pc files might be wrong or missing stuff.

**Comment by Neumann-A** [comment]
also there are probably still absolute paths to the winsdk in the qt files.

**Comment by BillyONeal** [comment]
> yeah but I don't guarantee that the pc files will be useable with that. Especially for static builds the pc files might be wrong or missing stuff.

Do you think it's worth a shot anyway?

> also there are probably still absolute paths to the winsdk in the qt files.

Probably :(

**Comment by Neumann-A** [comment]
> Do you think it's worth a shot anyway?

You can try but I there is currently nothing testing qt pc files. qmake uses the prl stuff and cmake uses the cmake configs. Only meson/autotools would possibly use pc files for qt.

**Comment by wrobelda** [comment]
> You can try but I there is currently nothing testing qt pc files. qmake uses the prl stuff and cmake uses the cmake configs. Only meson/autotools would possibly use pc files for qt.

I assume the https://github.com/microsoft/vcpkg/issues/14225 issue still stands, so they will most likely be unusable anyway.

**Comment by Neumann-A** [comment]
> I assume the #14225 issue still stands, so they will remain unusable anyway.

unless you use a single configuration triplet on osx?

**Comment by wrobelda** [comment]
> unless you use a single configuration triplet on osx?

Well, the only Qt .pc files being installed are those with `_debug` suffix; there aren't any `release` copies of them.

**Comment by Neumann-A** [comment]
> Well, the only Qt .pc files being installed are those with _debug suffix; there aren't any release copies of them.

filelist for osx disagrees lib/pkgconfig has qt stuff. 

> EDIT: also, is this specific to macOS only?

windows: no pkgconfig files
linux: normal pkgconfig installation no _debug suffixes. 

qt6 doesn't seem to install pkgconfig files at all

**Comment by wrobelda** [comment]
> > Well, the only Qt .pc files being installed are those with _debug suffix; there aren't any release copies of them.
> 
> filelist for osx disagrees lib/pkgconfig has qt stuff.

That's what I have here:

```
Qt5Concurrent_debug.pc
Qt5Core_debug.pc
Qt5DBus_debug.pc
Qt5Designer_debug.pc
Qt5Gui_debug.pc
Qt5Help_debug.pc
Qt5MacExtras_debug.pc
Qt5Network_debug.pc
Qt5OpenGLExtensions_debug.pc
Qt5OpenGL_debug.pc
Qt5PrintSupport_debug.pc
Qt5QmlModels_debug.pc
Qt5QmlWorkerScript_debug.pc
Qt5Qml_debug.pc
Qt5QuickTest_debug.pc
Qt5QuickWidgets_debug.pc
Qt5Quick_debug.pc
Qt5Sql_debug.pc
Qt5Svg_debug.pc
Qt5Test_debug.pc
Qt5UiPlugin_debug.pc
Qt5UiTools_debug.pc
Qt5Widgets_debug.pc
Qt5XmlPatterns_debug.pc
Qt5Xml_debug.pc
```

**Comment by Neumann-A** [comment]
@wrobelda: CI filelist here: https://dev.azure.com/vcpkg/public/_build/results?buildId=63427&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by wrobelda** [comment]
> @wrobelda: CI filelist here: https://dev.azure.com/vcpkg/public/_build/results?buildId=63427&view=artifacts&pathAsName=false&type=publishedArtifacts

Ah, my bad, was looking into `/debug` 🤦🏻‍♂️
Yeah, so in this case, single configuration triplet would work, but that's still suboptimal. Not to mention the fact that Windows build doesn't install any .pc at all,  so enabling Qt in non-CMake ports would be platform-dependent.

**Comment by autoantwort** [comment]
I did this mainly so that https://github.com/microsoft/vcpkg-tool/pull/172 can be merged. Imho this PR is a small improvement over the status quo. My intention was not to fix all pkgconfig issues of Qt

**Comment by wrobelda** [comment]
> I did this mainly so that [microsoft/vcpkg-tool#172](https://github.com/microsoft/vcpkg-tool/pull/172) can be merged. Imho this PR is a small improvement over the status quo. My intention was not to fix all pkgconfig issues of Qt

Yes, that's fair. We stole your thunder here a bit, our discussion belongs to #14225, sorry for that!

**Comment by BillyONeal** [comment]
@Neumann-A @wrobelda I was mainly making sure that this wouldn't cause things to break horribly, not necessarily to make sure all pkgconfig ills of qt are fixed. :P From the feedback above this seems safe to merge.

**Comment by BillyONeal** [comment]
@autoantwort Thanks for the fix!
@Neumann-A @wrobelda Thanks for the review feedback!

**Pull request merged**
