### PR TITLE
[open62541pp] Add port

### LINKED ISSUE #32995: [New Port Request] open62541++
### Library name

open62541++

### Library description

C++ wrapper of the amazing open62541 OPC UA library.

### Source repository URL

https://github.com/open62541pp/open62541pp

### Project homepage (if different from the source repository)

_No response_

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

_No response_

### PR DESCRIPTION
**Pull request by traversaro**
Fix https://github.com/microsoft/vcpkg/issues/32995 .

Opening as draft as this is blocked until https://github.com/microsoft/vcpkg/issues/36232 is fixed. However, I tried it locally with a workaround for  https://github.com/microsoft/vcpkg/issues/36232, and it seems to be working fine (at least on `x64-windows`).

Commits messages given following https://learn.microsoft.com/en-us/vcpkg/get_started/get-started-adding-to-registry?pivots=shell-cmd .

Repology page: https://repology.org/project/open62541pp/versions .

fyi @lukasberbuer

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [x] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by traversaro** [comment]
> Opening as draft as this is blocked until #36232 is fixed.

 #36232 is fixed, and CI is happy. PR ready for review, thanks!

**Comment by FrankXie05** [comment]
Error when installing `open62541pp:x64-windows` locally:
```
F:\feature\vcpkg\buildtrees\open62541pp\src\v0.11.0-71ba82ebb2.clean\src\DataType.cpp(117): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'opcua::NodeId'
F:\feature\vcpkg\buildtrees\open62541pp\src\v0.11.0-71ba82ebb2.clean\src\DataType.cpp(117): note: 'opcua::NodeId::NodeId': no overloaded function could convert all the argument types
F:\feature\vcpkg\buildtrees\open62541pp\src\v0.11.0-71ba82ebb2.clean\include\open62541pp/types/NodeId.h(52): note: could be 'opcua::NodeId::NodeId(uint16_t,const opcua::ByteString &)'
F:\feature\vcpkg\buildtrees\open62541pp\src\v0.11.0-71ba82ebb2.clean\src\DataType.cpp(117): note: 'opcua::NodeId::NodeId(uint16_t,const opcua::ByteString &)': cannot convert argument 2 from 'const UA_NodeId' to 'const opcua::ByteString &'
F:\feature\vcpkg\buildtrees\open62541pp\src\v0.11.0-71ba82ebb2.clean\src\DataType.cpp(117): note: Reason: cannot convert from 'const UA_NodeId' to 'const opcua::ByteString'
F:\feature\vcpkg\buildtrees\open62541pp\src\v0.11.0-71ba82ebb2.clean\src\DataType.cpp(117): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
F:\feature\vcpkg\buildtrees\open62541pp\src\v0.11.0-71ba82ebb2.clean\include\open62541pp/types/NodeId.h(49): note: or       'opcua::NodeId::NodeId(uint16_t,const opcua::Guid &)'
```

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/14017826/install-x64-windows-dbg-out.log)

**Comment by traversaro** [comment]
This should be fixed by https://github.com/microsoft/vcpkg/pull/36235 . Which version of open62541 are you installing? Note that I did not rebased the PR, so you need to merge it with main to actually run what the CI is running.

**Comment by FrankXie05** [comment]
Original output: 
```
PS F:\feature\vcpkg> git branch
* addopen62541pp
  master
PS F:\feature\vcpkg> ./vcpkg install open62541pp:x64-windows
Computing installation plan...
The following packages will be built and installed:
    open62541pp:x64-windows -> 0.11.0
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\vcpkg\AppData\Local\vcpkg\archives in 131 us. Use --debug to see more details.
Installing 1/1 open62541pp:x64-windows...
Building open62541pp:x64-windows...
-- Using cached open62541pp-open62541pp-v0.11.0.tar.gz.
-- Cleaning sources at F:/feature/vcpkg/buildtrees/open62541pp/src/v0.11.0-71ba82ebb2.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/feature/vcpkg/downloads/open62541pp-open62541pp-v0.11.0.tar.gz
-- Using source at F:/feature/vcpkg/buildtrees/open62541pp/src/v0.11.0-71ba82ebb2.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j33
    Working Directory: F:/feature/vcpkg/buildtrees/open62541pp/x64-windows-dbg
    See logs for more information:
      F:\feature\vcpkg\buildtrees\open62541pp\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/open62541pp/portfile.cmake:19 (vcpkg_cmake_install)
  scripts/ports.cmake:170 (include)


error: building open62541pp:x64-windows failed with: BUILD_FAILED
Elapsed time to handle open62541pp:x64-windows: 7 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+open62541pp
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[open62541pp]+Build+error&body=Copy+issue+body+from+F%3A%2Ffeature%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

PS F:\feature\vcpkg>
```

**Comment by FrankXie05** [comment]
If https://github.com/microsoft/vcpkg/pull/36235 solves the problem, we need merge master.

**Review by FrankXie05 — APPROVED** [review]

**Comment by FrankXie05** [comment]
The usage has been tested successfully locally.

**Comment by lukasberbuer** [comment]
Thank you @traversaro and @FrankXie05! I am very happy, that open62541pp is soon available via vcpkg! 🎉

What's the reason for using Python3 in the port file? Only open62541 requires Python, but this should be handled by open62541's port file?
```cmake
vcpkg_find_acquire_program(PYTHON3)
get_filename_component(PYTHON3_DIR "${PYTHON3}" DIRECTORY)
vcpkg_add_to_path("${PYTHON3_DIR}")
```

**Comment by traversaro** [comment]
> What's the reason for using Python3 in the port file? Only open62541 requires Python, but this should be handled by open62541's port file?
> 
> ```cmake
> vcpkg_find_acquire_program(PYTHON3)
> get_filename_component(PYTHON3_DIR "${PYTHON3}" DIRECTORY)
> vcpkg_add_to_path("${PYTHON3_DIR}")
> ```

The problem is that snippet of code adds Python to the PATH only for the port itself, there is no way (that I know of) in vcpkg to capture the requirement "to call find_package(open62541pp) Python needs to be in the path", and unfortunately there is actually this transitive requirement due to how open62541 cmake config files are written. This is indeed a problem also for any downstream user of open62541 and open62541pp ports, as the downstream project may fail in a vanilla environment due to missing Python. I think it may be possible to kind of mitigate this by changing logic open65541's CMake logic to only require Python if one uses the code generation macros, but probably it make sense to open a dedicate issue in vcpkg for this: https://github.com/microsoft/vcpkg/issues/36320  .

**Comment by FrankXie05** [comment]
I think for a port: you must not provide a port to anything unexpected. Including python.

**Pull request merged**
