### PR TITLE
[ci.baseline.txt] add some entries for arm64-osx

### PR DESCRIPTION
**Pull request by autoantwort**
These are only obviously entries because x64-osx is already failing (and they fail on arm64-osx).

### CODE REVIEW

**Comment by Adela0814** [comment]
`ci.baseline` is for triplets on `CI`. `arm64-osx` is not an official triplet, so it won't run at all, I don't think this change is necessary.

**Comment by autoantwort** [comment]
But when I run the ci locally to test arm64 I need these entries. And when arm64 becomes an official triplet, these entries are already there.

**Comment by Adela0814** [comment]
> But when I run the ci locally to test arm64 I need these entries. And when arm64 becomes an official triplet, these entries are already there.

@BillyONeal Please help to confirm if it is possible to add `arm64-osx` in `ci.baseline`.

**Comment by BillyONeal** [comment]
I think it's fine, thanks :)

**Pull request merged**
