### PR TITLE
[glog] Glog nominmax

### LINKED ISSUE #1511: [Windows] Build error
I'm trying to build colmap through vcpkg. But, this error countinuously occur.

C:\src\vcpkg>.\vcpkg install colmap[cuda,tests]:x64-windows
Computing installation plan...
The following packages will be built and installed:
    colmap[core,cuda,tests]:x64-windows -> 2022-03-14
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\Hyunkil\AppData\Local\vcpkg\archives in 256.1 us. Use --debug to see more details.
Starting package 1/1: colmap:x64-windows
Building package colmap[core,cuda,tests]:x64-windows...
-- Using cached colmap-colmap-29a1e3642a3b00734a52b21e597ea4d576485fe6.tar.gz.
-- Cleaning sources at C:/src/vcpkg/buildtrees/colmap/src/d576485fe6-7dd36362d1.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/src/vcpkg/downloads/colmap-colmap-29a1e3642a3b00734a52b21e597ea4d576485fe6.tar.gz
-- Applying patch fix-dependencies.patch
-- Using source at C:/src/vcpkg/buildtrees/colmap/src/d576485fe6-7dd36362d1.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j17
    Working Directory: C:/src/vcpkg/buildtrees/colmap/x64-windows-dbg
    See logs for more information:
      C:\src\vcpkg\buildtrees\colmap\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:111 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/colmap/portfile.cmake:53 (vcpkg_cmake_install)
  scripts/ports.cmake:145 (include)

error: building colmap:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+colmap
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[colmap]+Build+error
including:
  package: colmap[core,cuda,tests]:x64-windows -> 2022-03-14
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: b98afc9f1 2022-05-02 (10 hours ago)

Additionally, attach any relevant sections from the log files above.

**Expected behavior**
I don't know why this problem occur... Can someone help me?

**Desktop (please complete the following information):**
 - OS: Windows
 - Version Window 10, MSVC19

**Additional context**
[install-x64-windows-dbg-out.log](https://github.com/colmap/colmap/files/8610993/install-x64-windows-dbg-out.log)

### LINKED ISSUE #24420: [colmap] Build error
**Host Environment**
- OS: Windows 10 Home
- Compiler:  Vcpkg package management program version 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb

**To Reproduce**
'.\vcpkg.exe install colmap --triplet=x64-windows --head`

**Failure logs**
```
The following packages will be built and installed:
    colmap[core]:x64-windows -> 2022-03-14 (+HEAD)
Restored 0 packages from C:\Users\user\AppData\Local\vcpkg\archives in 118 us. Use --debug to see more details.
Starting package 1/1: colmap:x64-windows
Building package colmap[core]:x64-windows from HEAD...
-- Skipping hash check for C:/dev/vcpkg/downloads/colmap-colmap-dev.version.
-- Using cached colmap-colmap-dev.version.
-- Skipping hash check for C:/dev/vcpkg/downloads/colmap-colmap-c419bba98a8a987f61a363d6f542c3d050fb7743.tar.gz.
-- Using cached colmap-colmap-c419bba98a8a987f61a363d6f542c3d050fb7743.tar.gz.
-- Cleaning sources at C:/dev/vcpkg/buildtrees/colmap/src/head/d050fb7743-36abf1b6b1.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/dev/vcpkg/downloads/colmap-colmap-c419bba98a8a987f61a363d6f542c3d050fb7743.tar.gz
-- Applying patch fix-dependencies.patch
-- Using source at C:/dev/vcpkg/buildtrees/colmap/src/head/d050fb7743-36abf1b6b1.clean
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: C:/dev/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j17
    Working Directory: C:/dev/vcpkg/buildtrees/colmap/x64-windows-dbg
    See logs for more information:
      C:\dev\vcpkg\buildtrees\colmap\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:111 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/colmap/portfile.cmake:53 (vcpkg_cmake_install)
  scripts/ports.cmake:145 (include)
```
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8560199/install-x64-windows-dbg-out.log)
[patch-x64-windows-0-err.log](https://github.com/microsoft/vcpkg/files/8560201/patch-x64-windows-0-err.log)

### PR DESCRIPTION
**Pull request by whuaegeanse**
**Describe the pull request**
Fixs conflicts with freeimage when building colmap.

- #### What does your PR fix?
  Fixes https://github.com/colmap/colmap/issues/1511

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  All, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

### CODE REVIEW

**Comment by ZZWang21** [comment]
I ran " ./vcpkg x-add-version --all", and got this:
"Error: Local changes detected for glog but no changes to version or port version.
-- Version: 0.5.0#3
-- Old SHA: 6f706ab6117cd08849746b6a4300453727dad905
-- New SHA: ecb04a5ba4d046af782f62ae7c167bd05b0101a8
-- Did you remember to update the version or port version?
-- Pass `--overwrite-version` to bypass this check.
***No files were updated.***"

**Comment by Hyunkil76** [comment]
I also changed file like [cad3645], [3b48bd2] and after run .\vcpkg x-add-version --all
But I also get warning.....
C:\colmap\vcpkg>.\vcpkg x-add-version --all
Warning: Local port files SHA is the same as version `0.5.0#3` in `C:\colmap\vcpkg\versions\g-\glog.json`.
-- SHA: ecb04a5ba4d046af782f62ae7c167bd05b0101a8
-- Did you remember to commit your changes?
***No files were updated.***

**Comment by ZZWang21** [comment]
My build failed again. And, the vcpkg document has been over 60Gb large. Is it possible? Or anything went wrong?

**Comment by ZZWang21** [comment]
I rebooted the computer. re-build again. Now it seems to be finished. 1.13 hours was used.

**Comment by ZZWang21** [comment]
I have installed COLMAP with vcpkg. Do I need to cmake for COLMAP? I planned to install Pycolmap, but I cannot. Got many errors.

**Review by Adela0814 — APPROVED** [review]

**Comment by Adela0814** [comment]
> I changed files like [[cad3645](https://github.com/microsoft/vcpkg/commit/cad36457a4fb108a60a984495f4e6dfe16b7aee1)], [[3b48bd2](https://github.com/microsoft/vcpkg/commit/3b48bd2fd172d2743713187f7299e3cccf12cef8)] and after run .\vcpkg x-add-version --all But I also got warning..... C:\colmap\vcpkg>.\vcpkg x-add-version --all Warning: Local port files SHA is the same as version `0.5.0#3` in `C:\colmap\vcpkg\versions\g-\glog.json`. -- SHA: ecb04a5ba4d046af782f62ae7c167bd05b0101a8 -- Did you remember to commit your changes? _**No files were updated.**_

you need to overwrite the version via `.\vcpkg x-add-version glog --overwrite-version`

**Comment by Adela0814** [comment]
@whuaegeanse  are you trying to fix the CI build issue? you can get the failure logs from https://dev.azure.com/vcpkg/public/_build/results?buildId=71684&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by Hyunkil76** [comment]
I run '.\vcpkg x-add-version glog --overwrite-version'. But same waring occured. I attach files what I changed. Is there a problem with that?? Or I have to do more things after change them and before run x-add-version?

Thank so much for your help

(base) C:\colmap\vcpkg>.\vcpkg x-add-version glog --overwrite-version
Warning: Local port files SHA is the same as version `0.5.0#3` in `C:\colmap\vcpkg\versions\g-\glog.json`.
-- SHA: ecb04a5ba4d046af782f62ae7c167bd05b0101a8
-- Did you remember to commit your changes?
***No files were updated.**
[changed.zip](https://github.com/microsoft/vcpkg/files/8631560/changed.zip)
*

**Comment by whuaegeanse** [comment]
> @whuaegeanse are you trying to fix the CI build issue? you can get the failure logs from https://dev.azure.com/vcpkg/public/_build/results?buildId=71684&view=artifacts&pathAsName=false&type=publishedArtifacts

I am working on this

**Comment by Adela0814** [comment]
> > @whuaegeanse are you trying to fix the CI build issue? you can get the failure logs from https://dev.azure.com/vcpkg/public/_build/results?buildId=71684&view=artifacts&pathAsName=false&type=publishedArtifacts
> 
> I am working on this

What's the status now?

**Comment by whuaegeanse** [comment]
@Adela0814 Done.

**Review by Adela0814 — APPROVED** [review]

**Review by ras0219-msft — APPROVED** [review]

**Comment by ras0219-msft** [comment]
Thanks for the fix!

**Pull request merged**
