### PR TITLE
[libheif] Fixes static linking when building on MSVC

### PR DESCRIPTION
**Pull request by curtisgray**
**Describe the pull request**

- What does your PR fix? Fixes #
#13354 

- Which triplets are supported/not supported? Have you updated the CI baseline?
x86-windows
x86-windows-static
x64-windows
x64-windows-static

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

### CODE REVIEW

**Review by NancyLi1013 — COMMENTED** [review]
Could you please also bump `Port-Version` in CONTROL file?

**Comment by curtisgray** [comment]
> Could you please also bump `Port-Version` in CONTROL file?

Port-Version bumped to 2

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
LGTM now and thanks for your fix @curtisgray.

**Comment by strega-nil** [comment]
@curtisgray could you merge with master?

**Comment by NancyLi1013** [comment]
@curtisgray Could you please resolve the conflicts?

**Comment by NancyLi1013** [comment]
Ping @curtisgray for response. is work still being done for this Pr?

**Comment by curtisgray** [comment]
> Ping @curtisgray for response. is work still being done for this Pr?

@NancyLi1013, the libheif package was updated to a new version while I worked on this PR. The new version has fixed the problem I was having.

This PR can be cancelled.

**Pull request closed without merging**
