### PR TITLE
[libressl] add new port

### PR DESCRIPTION
**Pull request by eternalphane**
Alternative to openssl port.

### CODE REVIEW

**Comment by NancyLi1013** [comment]
Hi @EternalPhane, thanks for the new port. Here are the test results from the current CI system:

|arm64-windows|master| test |notes
|-------------|------|------|-----
|libressl     |      |Fail  |New Port

|x64-uwp |master| test |notes
|--------|------|------|-----
|libressl|      |Fail  |New Port

|arm-uwp |master| test |notes
|--------|------|------|-----
|libressl|      |Fail  |New Port

x64-windows-static results are inconclusive because it is missing logs from test

[failureLogs.zip](https://github.com/Microsoft/vcpkg/files/3146322/failureLogs.zip)

As for x64-windows-static, I see some info like this:
-- Performing post-build validation
Could not open file C:/vsts/_work/2/s/packages/libressl_x64-windows-static/debug/lib/crypto.lib for reading

**Comment by EternalPhane** [comment]
It seems that libressl is not supported on uwp and arm-windows (since Advapi32.dll is only supported on desktop). Can I take a look at the full build results?

**Comment by NancyLi1013** [comment]
Hi @EternalPhane, all other triplets build successfully now from the current CI system except on uwp and arm-windows. x64-windows-static can build successfully now. If the port is not supported on uwp and arm-windows, please add these codes at the beginning of **portfile.cmake** :
```
if(VCPKG_CMAKE_SYSTEM_NAME STREQUAL "WindowsStore")
    message(FATAL_ERROR "${PORT} does not currently support UWP")
endif()
if (VCPKG_TARGET_ARCHITECTURE STREQUAL "arm")
  message(FATAL_ERROR "${PORT} does not support ARM")
endif()
```

**Comment by EternalPhane** [comment]
done.

**Comment by grdowns** [comment]
Thanks for the new port, @EternalPhane!

**Pull request merged**
