### PR TITLE
[rpath-test,rpath-test-binaries] Validate rpath fixup

### PR DESCRIPTION
**Pull request by dg0yt**
CI test for https://github.com/microsoft/vcpkg/pull/39313
- using dynamic linkage in static CI triplets
- testing both release and debug

### CODE REVIEW

**Comment by BillyONeal** [comment]
I believe your test should be supports:linux because we don't do the rpath fixup thing on osx ?

**Comment by dg0yt** [comment]
> I believe your test should be supports:linux because we don't do the rpath fixup thing on osx ?

No, it is a test-first approach and expected to fail. The fix is https://github.com/microsoft/vcpkg/pull/39313.

Maybe I need to add another dynamic lib, to cover one lib loading another one.

**Comment by dg0yt** [comment]
LGTM:

### Location `<packages>/debug/lib`:
~~~
-- Set install name id of '<packages>/debug/lib/librpath-backend-lib.dylib' to '@rpath/librpath-backend-lib.dylib'
-- Adjusted RPATH of '<packages>/debug/lib/librpath-backend-lib.dylib' to '@loader_path'
-- Set install name id of '<packages>/debug/lib/librpath-test-lib.dylib' to '@rpath/librpath-test-lib.dylib'
-- Adjusted RPATH of '<packages>/debug/lib/librpath-test-lib.dylib' to '@loader_path'
~~~
RPATH: `<packages>/debug/lib` :heavy_check_mark: 

### Location `<packages>/debug/tools/<PORT>`:
~~~
-- Adjusted RPATH of '<packages>/debug/tools/rpath-test-binaries/rpath-test-tool' to '@loader_path/../../lib'
~~~
RPATH: `<packages>/debug/tools/<PORT>/../../lib` = `<packages>/debug/lib` :heavy_check_mark: 


### Location `<packages>/lib`:
~~~
-- Set install name id of '<packages>/lib/librpath-backend-lib.dylib' to '@rpath/librpath-backend-lib.dylib'
-- Adjusted RPATH of '<packages>/lib/librpath-backend-lib.dylib' to '@loader_path'
-- Set install name id of '<packages>/lib/librpath-test-lib.dylib' to '@rpath/librpath-test-lib.dylib'
-- Adjusted RPATH of '<packages>/lib/librpath-test-lib.dylib' to '@loader_path'
~~~
RPATH: `<packages>/lib` :heavy_check_mark: 

### Location `<packages>/manual-tools/<PORT>/debug`:
~~~
-- Adjusted RPATH of '<packages>/manual-tools/rpath-test-binaries/debug/rpath-test-tool' to '@loader_path/../../../debug/lib'
~~~
RPATH: `<packages>/manual-tools/<PORT>/debug/../../../debug/lib` = `<packages>/debug/lib` :heavy_check_mark: 

### Location `<packages>/manual-tools/<PORT>`:
~~~
-- Adjusted RPATH of '<packages>/manual-tools/rpath-test-binaries/rpath-test-tool' to '@loader_path/../../lib'
~~~
RPATH: `<packages>/manual-tools/<PORT>/../../lib` = `<packages>/lib` :heavy_check_mark: 

### Location `<packages>/tools/<PORT>/debug`:
~~~
-- Adjusted RPATH of '<packages>/tools/rpath-test-binaries/debug/rpath-test-tool' to '@loader_path/../../../debug/lib'
~~~
RPATH: `<packages>/tools/<PORT>/debug/../../../debug/lib` = `<packages>/debug/lib` :heavy_check_mark: 

### Location `<packages>/tools/<PORT>`:
~~~
-- Adjusted RPATH of '<packages>/tools/rpath-test-binaries/rpath-test-tool' to '@loader_path/../../lib'
~~~
RPATH: `<packages>/tools/<PORT>/../../lib` = `<packages>/lib` :heavy_check_mark:

**Comment by BillyONeal** [comment]
Thanks for the test!

**Pull request merged**
