### PR TITLE
Update eigen3's portfile to use new gitlab repo

### PR DESCRIPTION
**Pull request by traversaro**
As part of the migration from BitBucket to GitLab (see http://eigen.tuxfamily.org/index.php?title=News:Migration_to_GitLab.com_scheduled_on_the_December_4th) the official GitHub mirror at https://github.com/eigenteam/eigen-git-mirror is deprecated and soon will be removed, so to avoid problems it is better to already migrate the eigen3's port to the new repo.

### CODE REVIEW

**Comment by cenit** [comment]
somehow the git repository has been rebuilt?!?
In any case the SHA has been modified for the same reference, so you have to update it:

`4cc3717b9cbe78335e05f724919497214edd482d4812aeb1a9fd6da5b3f6d1b194bb93ed0dab9e734b4334a5b88e8f8c339c43c1b2044332286ef5e758f9ecf4 `

**Comment by traversaro** [comment]
> 
> 
> somehow the git repository has been rebuilt?!?
> In any case the SHA has been modified for the same reference, so you have to update it:
> 
> `4cc3717b9cbe78335e05f724919497214edd482d4812aeb1a9fd6da5b3f6d1b194bb93ed0dab9e734b4334a5b88e8f8c339c43c1b2044332286ef5e758f9ecf4 `

Thanks, I prepared the PR in an environment with reduced network, so I could not check that, thank for the hash.

**Comment by vicroms** [comment]
Thanks for the PR!

**Pull request merged**
