### PR TITLE
[xlnt] Prevent macro redefinition

### LINKED ISSUE #15643: [xlnt] XLNT_STATIC macro redefinition
**Describe the bug**
On windows planform there is clang-tidy \ build warning

**Environment**
- Windows 10
- Compiler: MSVC 19

**To Reproduce**
Just use lib in the project. set warnings level to max

**Expected behavior**
Clean build with no warnings

**Failure logs** 
[build] vcpkg_installed\x64-windows-static\include\xlnt/xlnt.hpp(25): warning C4005: 'XLNT_STATIC': macro redefinition

**Additional context**
Bug introduced by patching lib by vcpkg. Valid only to windows platform. Patch introduced to lib version 1.4. Current version if 1.5 and this patch is not needed anymore.

### PR DESCRIPTION
**Pull request by malirod**
Resolves #15643

### CODE REVIEW

**Comment by Neumann-A** [comment]
This patch is needed for the VS integration to work correctly. You are probably using cmake and there is a target adding the flag to your build?

**Comment by malirod** [comment]
Hi @Neumann-A ,

I'm using cmake and MSVS toolchain. But I'm not setting this macro in my project. As far as I remember it's set by lib itself.
Locally I've managed to build lib statically.

**Comment by Neumann-A** [comment]
You are probably are using the CMake targets to link against xlnt which defines the macro for you.
```
set_target_properties(xlnt::xlnt PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "XLNT_STATIC=1"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)
```
The problem is there are users which don't use CMake and thus the macro must be defined in the main header for them.

**Comment by Neumann-A** [comment]
vcpkg should probably do:
```
#ifndef XLNT_STATIC
#define XLNT_STATIC
```

**Comment by malirod** [comment]
@Neumann-A I need to check why this macro is not defined from CI point of view. Below you can find exact place where xlnt defines this macro for static version

https://github.com/tfussell/xlnt/blob/master/cmake/XlntConfig.cmake.in
```
if(NOT TARGET xlnt::xlnt)
  include("${XLNT_CMAKE_DIR}/XlntTargets.cmake")
endif()
```

https://github.com/tfussell/xlnt/blob/master/source/CMakeLists.txt
```
install(EXPORT XlntTargets
  FILE XlntTargets.cmake
  NAMESPACE xlnt::
  DESTINATION ${XLNT_CMAKE_CFG_DEST_DIR})
```

and generated XlntTargets.cmake in turn contains 
```
set_target_properties(xlnt::xlnt PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "XLNT_STATIC=1"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)
```
Here is where xlnt actually defines this macro for static version
https://github.com/tfussell/xlnt/blob/e66e417b0c8806121202adb2dc45de91809710cc/source/CMakeLists.txt#L175

**Comment by Neumann-A** [comment]
It is not about CI it is about users using e.g. only the VS integration. They don't automatically get the macro definition from the CMake target since they are not using CMake. It is as simple as that.

**Comment by malirod** [comment]
@Neumann-A , sound reasonable. I'll update PR.

**Review by JackBoosY — CHANGES_REQUESTED** [review]
Please bump the port version. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).

**Comment by malirod** [comment]
@JackBoosY , done

**Comment by malirod** [comment]
@JackBoosY CI got following error. I've missed something?
```
Error: While reading versions for port xlnt from file: C:\a\1\s\port_versions\x-\xlnt.json
       Version `1.5.0#1` was not found in versions file.
       Run:

           vcpkg x-add-version xlnt

```

**Comment by JackBoosY** [comment]
Please run command `vcpkg x-add-version xlnt` in this branch and commit the changes.

**Comment by malirod** [comment]
@JackBoosY , didn't help.
```
vcpkg>vcpkg x-add-version xlnt
Error: Couldn't find required file `...apps\vcpkg\port_versions\baseline.json`
.
```

I've checked some commits in the history and I don't see that added port-version lead to updates in some other files.

**Comment by malirod** [comment]
Hmmm. Very interesting. Just made a fresh clone of the vcpkg and now I see port_versions dir in the vcpkg root. I've used just to pull updates for a long time for the vcpkg.

**Comment by malirod** [comment]
@JackBoosY , done

**Review by ras0219 — APPROVED** [review]

**Review by JackBoosY — APPROVED** [review]

**Pull request merged**
