### PR TITLE
[pixman] build on M1 macs

### PR DESCRIPTION
**Pull request by autoantwort**
@Neumann-A   
Otherwise I get the following error when I try to build for x64-osx:
```
DEPRECATION: c_args in the [properties] section of the machine file is deprecated, use the [built-in options] section.
DEPRECATION: cpp_args in the [properties] section of the machine file is deprecated, use the [built-in options] section.
DEPRECATION: c_link_args in the [properties] section of the machine file is deprecated, use the [built-in options] section.
DEPRECATION: cpp_link_args in the [properties] section of the machine file is deprecated, use the [built-in options] section.
WARNING: Recommend using either -Dbuildtype or -Doptimization + -Ddebug. Using both is redundant since they override each other. See: https://mesonbuild.com/Builtin-options.html#build-type-options
The Meson build system
Version: 0.60.2
Source dir: /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/pixman/src/0.40.0-9a8e17d6df.clean
Build dir: /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/pixman/x64-osx-dbg
Build type: native build
Project name: pixman
Project version: 0.40.0
C compiler for the host machine: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc (clang 13.0.0 "Apple clang version 13.0.0 (clang-1300.0.29.30)")
C linker for the host machine: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc ld64 711
Host machine cpu family: aarch64
Host machine cpu: arm64
Compiler for C supports arguments -Wdeclaration-after-statement: YES 
Compiler for C supports arguments -fno-strict-aliasing: YES 
Compiler for C supports arguments -fvisibility=hidden: YES 
Compiler for C supports arguments -Wundef: YES 
Compiler for C supports arguments -Wunused-local-typedefs: YES 

../src/0.40.0-9a8e17d6df.clean/meson.build:145:2: ERROR: Problem encountered: MMX Support unavailable, but required

A full log can be found at /Users/leanderSchulten/git_projekte/Lichtsteuerung/vcpkg/buildtrees/pixman/x64-osx-dbg/meson-logs/meson-log.txt
```

### CODE REVIEW

**Comment by Neumann-A** [comment]
Sry to say this but M1 is an arm chip and not an x64 chip. It has x86 emulation and not x64 so using an x64 triplet is strictly speaking wrong.

**Comment by autoantwort** [comment]
Yeah but crosscompiling should be possible

**Comment by autoantwort** [comment]
> It has x86 emulation and not x64

Huh. It only has x64 emulation, there is no 32 bit on mac

**Comment by Neumann-A** [comment]
> Yeah but crosscompiling should be possible

Then make it a special case `if(VCPKG_TARGET_ARCHITECTURE STREQUAL "x64" AND VCPKG_TARGET_IS_OSX AND VCPKG_CROSSCOMPILING)` where you deactivate all the stuff. I don't think we should brick pixman performance by a faktor of probably 2 (more likely min 4) to 10 for everybody with a real x64 processor. I digged down a bit in history and all amd/intel x64 processor have at least sse2 with sse3 being available in 2nd gen amd64 (> 10 years away; Intel being at SSE4 already.).

**Comment by autoantwort** [comment]
Hm I also can build `embree3[avx,avx2,core,sse2,sse42]:x64-osx.` without problems. Maybe meson tries to detect MMX support on the host cpu and not on the target CPU architecture.

**Comment by Neumann-A** [comment]
embree does a CPUID detection to dispatch to the correct implementation. So that is quite a different behavior.

**Comment by autoantwort** [comment]
> embree does a CPUID detection to dispatch to the correct implementation. So that is quite a different behavior.

But this means that it is possible to cross compile code with sse enables in general. So pixman should also be able to do it.

**Comment by autoantwort** [comment]
I have also set up a small test project on my M1 mac with the following code:
```c++
#include <immintrin.h>
int main(){
    __m256i a{};
    _mm256_abs_epi16(a);
}
```
It compiles with `-mavx2`. 

If I set up a project that only uses sse2 I can even run the project. So it should be possible to compile pixman with SSE enabled.

**Comment by autoantwort** [comment]
I have created #22854 as an alternative

**Pull request closed without merging**
