### PR TITLE
[python3] Update to Python 3.10.2.

### PR DESCRIPTION
**Pull request by Hoikas**
Updates to Python 3.10.2

- #### What does your PR fix?  
  See above

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  No change

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  WIP

### CODE REVIEW

**Comment by Hoikas** [comment]
> [Error: vcpkg has crashed; no additional details are available.](https://dev.azure.com/vcpkg/public/_build/results?buildId=67609&view=logs&j=705ccf51-b0e6-52fa-daea-1be2c9a8756e&t=a531e4fc-78eb-5385-5957-00fd434e2ae1&l=62)

**Comment by Hoikas** [comment]
Depends on:
- [ ] #23167
- [ ] #23166

**Comment by Hoikas** [comment]
libao failures seem unrelated to this PR:

```
.././../src/1.2.2-d87489a217.clean/src/audio_out.c(291): error C2065: 'DIR': undeclared identifier
.././../src/1.2.2-d87489a217.clean/src/audio_out.c(291): error C2065: 'plugindir': undeclared identifier
.././../src/1.2.2-d87489a217.clean/src/audio_out.c(291): warning C4552: '*': result of expression not used
.././../src/1.2.2-d87489a217.clean/src/audio_out.c(297): error C2065: 'plugindir': undeclared identifier
.././../src/1.2.2-d87489a217.clean/src/audio_out.c(297): warning C4013: 'opendir' undefined; assuming extern returning int
.././../src/1.2.2-d87489a217.clean/src/audio_out.c(299): error C2065: 'plugindir': undeclared identifier
.././../src/1.2.2-d87489a217.clean/src/audio_out.c(299): warning C4047: '!=': 'int' differs in levels of indirection from 'void *'
.././../src/1.2.2-d87489a217.clean/src/audio_out.c(300): warning C4013: 'readdir' undefined; assuming extern returning int
.././../src/1.2.2-d87489a217.clean/src/audio_out.c(300): error C2065: 'plugindir': undeclared identifier
.././../src/1.2.2-d87489a217.clean/src/audio_out.c(300): warning C4047: '=': 'dirent *' differs in levels of indirection from 'int'
.././../src/1.2.2-d87489a217.clean/src/audio_out.c(301): error C2037: left of 'd_name' specifies undefined struct/union 'dirent'
.././../src/1.2.2-d87489a217.clean/src/audio_out.c(301): error C2198: 'strlen': too few arguments for call
.././../src/1.2.2-d87489a217.clean/src/audio_out.c(301): error C2057: expected constant expression
.././../src/1.2.2-d87489a217.clean/src/audio_out.c(301): error C2466: cannot allocate an array of constant size 0
.././../src/1.2.2-d87489a217.clean/src/audio_out.c(301): error C2133: 'fullpath': unknown size
.././../src/1.2.2-d87489a217.clean/src/audio_out.c(302): warning C4034: sizeof returns 0
.././../src/1.2.2-d87489a217.clean/src/audio_out.c(303): error C2037: left of 'd_name' specifies undefined struct/union 'dirent'
.././../src/1.2.2-d87489a217.clean/src/audio_out.c(302): warning C4473: 'snprintf' : not enough arguments passed for format string
.././../src/1.2.2-d87489a217.clean/src/audio_out.c(302): note: placeholders and their parameters expect 2 variadic arguments, but 1 were provided
.././../src/1.2.2-d87489a217.clean/src/audio_out.c(302): note: the missing variadic argument 2 is required by format string '%s'
.././../src/1.2.2-d87489a217.clean/src/audio_out.c(305): warning C4013: 'S_ISREG' undefined; assuming extern returning int
.././../src/1.2.2-d87489a217.clean/src/audio_out.c(306): error C2037: left of 'd_name' specifies undefined struct/union 'dirent'
.././../src/1.2.2-d87489a217.clean/src/audio_out.c(306): warning C4047: 'function': 'const char *' differs in levels of indirection from 'int'
.././../src/1.2.2-d87489a217.clean/src/audio_out.c(306): warning C4024: 'strrchr': different types for formal and actual parameter 1
.././../src/1.2.2-d87489a217.clean/src/audio_out.c(306): error C2198: 'strrchr': too few arguments for call
.././../src/1.2.2-d87489a217.clean/src/audio_out.c(318): warning C4013: 'closedir' undefined; assuming extern returning int
.././../src/1.2.2-d87489a217.clean/src/audio_out.c(318): error C2065: 'plugindir': undeclared identifier
```

**Comment by Hoikas** [comment]
Cannot locally repro openxr-loader failure.

**Comment by Hoikas** [comment]
@github-actions go away

**Comment by Hoikas** [comment]
Depends on:
- [ ] #23191

**Comment by Hoikas** [comment]
We're finally ready for review

**Review by JonLiu1993 — APPROVED** [review]

**Review by vicroms — APPROVED** [review]

**Review by JonLiu1993 — APPROVED** [review]

**Pull request merged**
