### PR TITLE
[lerc] Export Package

### LINKED ISSUE #13723: [lerc] Does not create a package
The lerc library does not create a package in its CMakeLists.txt so there is no lercConfig.cmake created which makes it difficult to use in other CMake projects.

Until this is resolved in the lerc source, a patch can be created which will modify the CMakeLists.txt to force it to create a package.

### PR DESCRIPTION
**Pull request by n4z4m3**
Fixes #13723

The lerc library does not export a package which makes it difficult to use in other CMake projects.

This PR creates a patch to the CMakeLists.txt file to export a package.

### CODE REVIEW

**Review by LilyWangL — APPROVED** [review]

**Comment by LilyWangL** [comment]
Blocked by #13722.

**Review by n4z4m3 — COMMENTED** [review]
Agree with these changes

**Review by ras0219 — APPROVED** [review]

**Comment by nazame** [comment]
I am seeing that the CI x86_windows is failing, however, when I run it locally, it works fine.

**Comment by nazame** [comment]
Any ideas why the checks are not getting through?

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
