### PR TITLE
[cppgraphqlgen] bump version to 3.6.0

### PR DESCRIPTION
**Pull request by wravery**
- #### What does your PR fix?  
  Bumps the version of cppgraphqlgen to the latest 3.6.0 release.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes.

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by JonLiu1993** [comment]
@wravery ,Ready for review now?

**Comment by wravery** [comment]
> @wravery ,Ready for review now?

Sure, was just waiting for the CI checks.

**Comment by JonLiu1993** [comment]
It seems that all CI tests have passed, please click ready for review

**Review by JonLiu1993 — APPROVED** [review]

**Comment by ras0219-msft** [comment]
As always, thanks for the clean and simple updates :)

**Pull request merged**
