### PR TITLE
Set CMAKE_MSVC_DEBUG_INFORMATION_FORMAT value so RelWithDebInfo build…

### LINKED ISSUE #37552: Debug information missing for MSVC builds on RelWithDebInfo configuration
**Describe the bug**

When building a vcpkg port using MSVC and with `CMAKE_BUILD_TYPE` set to RelWithDebInfo, the generated compiler commands do not include 'Zi'. This is a change from CMake's default behavior, and it causes projects to build with different settings under vcpkg.

**Environment**
- OS: Windows
- Compiler: MSVC

**To Reproduce**

Issue is with a private dependency within Microsoft that is being built using vcpkg. Can share repo & more info internally if needed.

The portfile for this dependency changes the build type to `RelWithDebInfo` in the `vcpkg_cmake_configure` call:

```
vcpkg_cmake_configure(
    SOURCE_PATH ${SOURCE_PATH}
    DISABLE_PARALLEL_CONFIGURE
    NO_CHARSET_FLAG
    GENERATOR Ninja
    OPTIONS
    OPTIONS_RELEASE
        -DCMAKE_BUILD_TYPE=RelWithDebInfo
)
```
Here is the problem as I understand it after some digging.

Before CMake 3.25, `Zi` was included in the default value for `CMAKE_CXX_FLAGS_RELWITHDEBINFO`. 

Post-CMake 3.25, `Zi` was removed from `CMAKE_CXX_FLAGS_RELWITHDEBINFO` in favor of the abstraction `CMAKE_MSVC_DEBUG_INFORMATION_FORMAT`. The default value of this new variable is `$<$<CONFIG:Debug,RelWithDebInfo>:ProgramDatabase>`, which causes `Zi` to be included on the MSVC command line for Debug and RelWithDebInfo configs.

This apparently caused problems for ports which expected Debug builds to use `Z7` instead of `Zi`. Specifically, the [windows toolchain file](https://github.com/microsoft/vcpkg/blob/3850888eb8480abc8f73f84bf618de3b68900572/scripts/toolchains/windows.cmake#L71) sets `CMAKE_CXX_FLAGS_DEBUG ` to include `Z7`. This resulted in warnings of flags being overwritten, so #32338 overwrites the default value of `CMAKE_MSVC_DEBUG_INFORMATION_FORMAT` to an empty string. 

With this variable unset, Debug and Release builds still have `Z7` included because of the flags set in the toolchain file. However, builds set to RelWithDebInfo do not have any debug information flags on the command line unless projects manually re-set `CMAKE_MSVC_DEBUG_INFORMATION_FORMAT` in their own CMake files.

**Expected behavior**
VCPKG builds configured to build `RelWithDebInfo` should build with the default CMake C/C++ flags for that config and so should include `Zi`. 

**Potential solutions**

Open to other ideas, but thought of these. Proposing a PR to do (1)

1. Set `CMAKE_MSVC_DEBUG_INFORMATION_FORMAT` to `$<$<CONFIG:RelWithDebInfo>:ProgramDatabase>` to maintain default behavior for `RelWithDebInfo` builds without causing the warnings on `Debug` builds.

2. In addition to the existing `CMAKE_CXX_FLAGS_DEBUG` and `CMAKE_CXX_FLAGS_RELEASE`, add a `CMAKE_CXX_FLAGS_RELWITHDEBINFO` to the windows toolchain files and include 'Zi' on it.

### PR DESCRIPTION
**Pull request by dylanclark**
…s include ProgramDatabase debug information

Fixes #37552

### CODE REVIEW

**Comment by Neumann-A** [comment]
There is no reason for vcpkg to set this. If you do something like `-DCMAKE_BUILD_TYPE=RelWithDebInfo` you can also directly pass `CMAKE_MSVC_DEBUG_INFORMATION_FORMAT` without a generator expression

**Comment by dylanclark** [comment]
@Neumann-A Thank you for taking a look. I appreciate your point and your recommendation is how I've fixed the issue in my repo.

However, I disagree that there is no reason for vcpkg to set this. By setting it to an empty string in #32338, Vcpkg has overridden CMake's default values for RelWithDebInfo. If a portfile specifies the RelWithDebInfo configuration, it's reasonable to expect that the port would be built with debug information. The fact that it's not means RelWithDebInfo is broken by default in vcpkg.

I couldn't find any documentation or release notes indicating that this was done, so I spent an inordinate amount of time combing through Cmake and Vcpkg changes to understand why a DLL we ship to users was missing debug information all of the sudden. I'm proposing this change to prevent others from having to do the same in the future.

**Comment by Neumann-A** [comment]
> The fact that it's not means RelWithDebInfo is broken by default in vcpkg.

Because vcpkg is passing `CMAKE_BUILD_TYPE` itself. You are not supposed to change that. Secondly you can and should not assume that `CMAKE_MSVC_DEBUG_INFORMATION_FORMAT` is even honored since only CMake knows about it. Furthermore vcpkg only correctly controls flags for Debug and Release everything else is more or less undefined.

**Comment by dylanclark** [comment]
Fair enough. I wasn't aware that RelWithDebInfo was not supported since it's been working for years as far as I can tell.

**Pull request closed without merging**
