### PR TITLE
[Arrow] Explicitly enable CSV and JSON

### PR DESCRIPTION
**Pull request by isaacbrodsky**
**Describe the pull request**

- What does your PR fix?

Seems inconsistent between different distributions of `arrow` whether CSV and JSON support are enabled - in vcpkg it seems to be disabled, in other package managers it seems to generally be enabled. This changes the configuration to explicitly enable these features and build them. (edited)

- Which triplets are supported/not supported? Have you updated the CI baseline?

No change expected.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

Yes

### CODE REVIEW

**Comment by isaacbrodsky** [comment]
Build failure has a couple messages like:
```
-- Note: argumentum only supports static library linkage. Building static library.
-- Downloading https://github.com/mmahnic/argumentum/archive/v0.3.1.tar.gz...
-- Downloading https://github.com/mmahnic/argumentum/archive/v0.3.1.tar.gz... Failed. Status: 22;"HTTP response code said error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):
      
      Failed to download file.
...
```

Which doesn't look related to this change to me.

**Comment by Cheney-W** [comment]
@isaacbrodsky  Thanks for your PR!
Are these two functions necessary to build arrow? If not, could you add them as a Default-Features of arrow?

**Comment by isaacbrodsky** [comment]
> @isaacbrodsky Thanks for your PR!
> Are these two functions necessary to build arrow? If not, could you add them as a Default-Features of arrow?

Ok, I have converted CSV and JSON to Default Features. I also changed Parquet file support, which I assume works the same way, to also be a default feature.

**Review by JackBoosY — APPROVED** [review]

**Comment by Cheney-W** [comment]
@isaacbrodsky 
1. `include(vcpkg_common_functions)` is deprecated. Could you please remove it?
2.  In front of the following 3 sentences, 5 spaces should be used instead of one Tab.
 `"csv"      ARROW_CSV`
 `"json"     ARROW_JSON`
 `"parquet"  ARROW_PARQUET`
3. Please use `file(INSTALL ${SOURCE_PATH}/LICENSE.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)` 
instead of 
`file(INSTALL ${SOURCE_PATH}/LICENSE.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/arrow RENAME copyright)`

**Comment by isaacbrodsky** [comment]
> @isaacbrodsky
> 
>     1. `include(vcpkg_common_functions)` is deprecated. Could you please remove it?
> 
>     2. In front of the following 3 sentences, 5 spaces should be used instead of one Tab.
>        `"csv"      ARROW_CSV`
>        `"json"     ARROW_JSON`
>        `"parquet"  ARROW_PARQUET`
> 

Interestingly I copied this statement example from opencv4, since the docs mentioned this as something that needed features.

>     3. Please use `file(INSTALL ${SOURCE_PATH}/LICENSE.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)`
>        instead of
>        `file(INSTALL ${SOURCE_PATH}/LICENSE.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/arrow RENAME copyright)`

Okay, I rebased my branch and made the modifications you requested.

**Comment by isaacbrodsky** [comment]
Hi, just a bump on this PR. Anything needed for it to be merged?

**Comment by ras0219-msft** [comment]
LGTM, thanks for the PR!

**Pull request merged**
