### PR TITLE
Fix LLVM cmake modules

### PR DESCRIPTION
**Pull request by koprok**
- Fix wrong paths in LLVM/Clang cmake modules
- Reduce build-time memory usage (at the expense of some build-time slow down)

### CODE REVIEW

**Comment by Rastaban** [comment]
The llvm port test in the CI system is currently disabled because it takes such a long to to build.  Because of this I am testing this on my machine.

**Comment by koprok** [comment]
@Rastaban, that's one of the reasons for my memory usage commit. The debug build takes very long time because the linker needs huge amounts of memory. Running many parallel linker processes (which is the default) on multi-core system causes memory swapping. Running only one linker process reduces memory swapping and may actually increase build time.
Release build does not have such an issue, so another option is to build LLVM only in release. But unfortunately I did not find any way to disable debug build only for the LLVM package and not for the rest of the packages.

**Comment by koprok** [comment]
@Rastaban, I have pushed one more commit to the branch. I found more files that need fixing. Sorry, that I have missed these initially.

**Comment by Rastaban** [comment]
I get the following failure on x64-windows

```
Building package llvm[core]:x64-windows...
-- Using cached D:/vcpkg/vcpkg/downloads/llvm-7.0.0.src.tar.xz
-- Extracting source D:/vcpkg/vcpkg/downloads/llvm-7.0.0.src.tar.xz
-- Using cached D:/vcpkg/vcpkg/downloads/cfe-7.0.0.src.tar.xz
-- Extracting source D:/vcpkg/vcpkg/downloads/cfe-7.0.0.src.tar.xz
-- Applying patch D:/vcpkg/vcpkg/ports/llvm/install-cmake-modules-to-share.patch
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at ports/llvm/portfile.cmake:81 (file):
  file failed to open for reading (No such file or directory):

    D:/vcpkg/vcpkg/packages/llvm_x64-windows/debug/share/clang/ClangTargets-debug.cmake
Call Stack (most recent call first):
  scripts/ports.cmake:71 (include)
```

**Comment by koprok** [comment]
@Rastaban, I will check that error and then get back to you.

**Comment by koprok** [comment]
@Rastaban, I have force-pushed the branch. It should now work both in debug and release.

**Comment by Rastaban** [comment]
My testing of this change looks good.  Thanks!

**Pull request merged**
