### PR TITLE
[curl] Fix android builds. Greatly simplify pkgconfig handling.

### PR DESCRIPTION
**Pull request by ras0219**
Includes changes from #17400. Tested using docker.io/menny/android_ndk:1.15.1.

https://github.com/menny/docker_android/tree/master/android_ndk
https://hub.docker.com/r/menny/android_ndk

```
$ docker pull menny/android_ndk:1.15.1
```

After launching the container, do: 
```
export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/22.0.7026061
git clone https://github.com/ras0219/vcpkg -b dev/roschuma/curl-android
cd vcpkg
./bootstrap-vcpkg.sh
echo "
set(VCPKG_TARGET_ARCHITECTURE arm)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME Android)
" > triplets/community/arm-android.cmake
echo "
set(VCPKG_TARGET_ARCHITECTURE arm)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_CMAKE_SYSTEM_NAME Android)
" > triplets/community/arm-android-dynamic.cmake
./vcpkg install aws-sdk-cpp[core]:arm-android aws-sdk-cpp[core]:arm-android-dynamic --no-binarycaching
```

- #### What does your PR fix?  
  Fixes #17400

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  <all / linux, windows, ...>, <Yes/No>

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  `Your answer`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  <Yes / I am still working on this PR>

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by ahmedyarub** [comment]
Tested on Windows and worked like a charm!

**Comment by talregev** [comment]
Hi Robert, your fix is working with pkg-config when we compile for android with libcurl. 
curl-config is showing permission denied and may have the wrong flags. 
We now switch to pkg-config compilation with vcpkg. 
Thank you for this fix

**Comment by dg0yt** [comment]
> curl-config is showing permission denied and may have the wrong flags.

The port file could set permissions with `file(INSTALL ...)`.
IMO it should go the the tools folder. It will be used by by build scripts on the host, not the target. (Example: gdal).

**Comment by talregev** [comment]
@dg0yt  
Before the fix (current state of vcpkg) curl-config don't show permission denied. After the fix it showing permission denied.
It also may give the wrong flags for libcurl compilation for android.
Also it will be no relevant for us because we switching to compile libcurl vcpkg with android with pkg-config.

**Comment by dg0yt** [comment]
> Also `curl-config` will not relevant for us because we switching to compile libcurl vcpkg with android with `pkg-config`

I think it is relevant for fixing #9068 (GDAL on Linux), at least if using gdal configuration parameters.

**Comment by talregev** [comment]
> I think it is relevant for fixing #9068 (GDAL on Linux), at least if using gdal configuration parameters.

I knew that it might be relevant for other projects, so that why I also report about  `curl-config`

**Comment by ras0219-msft** [comment]
I found the issue -- I was trying to replace `prefix=/absolute/path` with `prefix=$(get current script path)`, but messed up the replacement and just wrote back out `$(get current script path)`.

With this, the PR is good to go on my side assuming it passes CI. @talregev I'd appreciate it if you wouldn't mind trying your previous code (using curl-config) on this new version, as some validation that the new curl-config works.

**Comment by talregev** [comment]
@ras0219 Good morning Robert. It is not my code, it is opensource code.
And sure. I am testing both `curl-config` and `pkg-config` with this PR. 
Thank you.

**Comment by talregev** [comment]
@ras0219 Hi Robert, I open a two test branches as you can see. (I mention this PR on these branches). 
All our tests are successful on both branches. For us the `curl-config` and `pkg-config` are good in this PR.
Thank you again on your time and this fix.

**Review by JackBoosY — CHANGES_REQUESTED** [review]
Please bump the port version. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).
Also please run command `vcpkg x-add-version --all` then commit the changes.

**Comment by dg0yt** [comment]
@ras0219 Once again regarding `curl-config`: It is meant to be executed as a shell script. I would prefer to find this installed with executable bits set, and probably it belongs to `/tools/` in this case. (I'm trying to use it for the gdal port on Unix. It gets harder when it is not executable. Gdal also wants `geos-config` which would be executable but is deleted...)

**Comment by talregev** [comment]
@ras0219 @JackBoosY any news?

**Comment by ras0219-msft** [comment]
I hadn't incremented the version number, so it failed CI. If this passes, it's good to merge.

**Comment by dg0yt** [comment]
Can you have another look at the curl pc files? On x64-linux, with the curl from `master` I see a duplication of 'Libs'.
~~~
...
Libs: -L"${libdir}" -lcurl-d  -lgcc -lgcc_s -lc -lgcc -lgcc_s -ldl -lpthread -lssl -lcrypto -lz  -lgcc -lgcc_s -lc -lgcc -lgcc_s -ldl -lpthread -lssl -lcrypto -lz
~~~

In the buildtree, it looks a little bit different:
~~~
Libs: -L${libdir} -lcurl-d  -lgcc -lgcc_s -lc -lgcc -lgcc_s -ldl -lpthread -lssl -lcrypto -lz
Libs.private:  -lgcc -lgcc_s -lc -lgcc -lgcc_s -ldl -lpthread -lssl -lcrypto -lz
~~~

**Comment by Neumann-A** [comment]
@dg0yt `vcpkg_fixup_pkgconfig` merges `Libs.private` into `Libs` if `VCPKG_LIBRARY_LINKAGE` is static

**Comment by dg0yt** [comment]
> @dg0yt `vcpkg_fixup_pkgconfig` merges `Libs.private` into `Libs` if `VCPKG_LIBRARY_LINKAGE` is static

@Neumann-A Yes, garbage-in-garbage-out here. I want to ask if there could be an improvement on the input side (port curl).

**Comment by ras0219-msft** [comment]
I'm going to merge this PR as-is for now and look at improving the .pc in a followup. Thanks everyone!

**Comment by dg0yt** [comment]
:+1: 
@ras0219-msft  I'm ~fighting with~ looking at various pc files (towards fixing gdal for Unix). Cf. #17748 for a general approach to the duplication issue.

**Pull request merged**
