### PR TITLE
[pthreads] Fixed build on Windows ARM64

### PR DESCRIPTION
**Pull request by ice0**
Build stops with an error:
```
version.rc(132) : error RC2104 : undefined keyword or key name: __PTW32_VERSIONINFO_DESCRIPTION  
```

Fixed by adding definitions for ARM64 arch.

Fixing https://github.com/microsoft/vcpkg/issues/27258

### CODE REVIEW

**Comment by ice0** [comment]
@Cheney-W 
https://github.com/microsoft/vcpkg/pull/27312 needs to be merged before we can continue here.

**Review by BillyONeal — APPROVED** [review]
I submitted upstream as https://sourceforge.net/p/pthreads4w/code/merge-requests/6/

As you noted, upstream seems completely inactive, and this is identical to surrounding code but for the architecture, so I'm happy to merge without waiting for confirmation.

**Comment by BillyONeal** [comment]
This run seemed wedged so I cancelled and restarted it.

**Comment by BillyONeal** [comment]
Thanks!

**Pull request merged**
