### PR TITLE
Python3 no absolute paths

### PR DESCRIPTION
**Pull request by autoantwort**
For #20469

The changed file is used by the [`sysconfig`](https://docs.python.org/3/library/sysconfig.html) module.

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
There are many issues with python3 in vcpkg, I hope we can solve them step by step.

**Comment by Hoikas** [comment]
@JackBoosY what issues does python3 have aside from this one?

**Comment by JackBoosY** [comment]
@Hoikas https://github.com/microsoft/vcpkg/issues/16956 https://github.com/microsoft/vcpkg/issues/16311

**Comment by Hoikas** [comment]
#16956 is a port bug with pybind11 that happens even without vcpkg, IME. I've never been able to repro #16311 😢

**Pull request merged**
