### PR TITLE
[openssl] Revert. support for android and wasm32-emscripten

### LINKED ISSUE #29947: [openssl] build failure on Android
Before 9ccc64ca98b320404d059df4349220bd2c1b4a46 I was able to build OpenSSL for Android with no issues: https://github.com/BOINC/boinc-apps/actions/runs/4288278917/jobs/7470102534
Now it's failing with the next error:
```
Configuring OpenSSL version 3.0.8 for target android-arm
Using os-specific seed configuration
+ /usr/bin/perl /home/runner/work/boinc-apps/boinc-apps/vcpkg/buildtrees/openssl/src/nssl-3.0.8-d9622695f9.clean/Configure android-arm enable-static-engine enable-capieng no-ssl3 no-weak-ssl-ciphers no-tests no-shared no-module --openssldir=/etc/ssl --libdir=lib --prefix=/home/runner/work/boinc-apps/boinc-apps/build/boinc-autodock-vina/arm-android-static/vcpkg_installed/arm-android-static

Failure!  build file wasn't produced.
Please read INSTALL.md and associated NOTES-* files.  You may also have to
look over your available compiler tool chain or change your configuration.

no NDK arm-linux-androideabi-gcc on $PATH at (eval 10) line 142.
```
Ref: https://github.com/BOINC/boinc-apps/actions/runs/4302690901/jobs/7501498224

### LINKED ISSUE #30037: [openssl] build failure on wasm32-emscripten
**Host Environment**

- OS: wsl2 ubuntu 22.04
- Compiler: gcc 11.3

**To Reproduce**

```
git clone https://github.com/emscripten-core/emsdk
emsdk/emsdk install latest
emsdk/emsdk activate latest
source emsdk/emsdk_env.sh
./vcpkg install openssl --triplet=wasm32-emscripten
```

**Failure logs**

We also compile the openssl with `wasm32-emscripten` triplet. and there is a regression:

```
Building openssl[core]:wasm32-emscripten...
-- [OVERLAY] Loading triplet configuration from: /home/tal/boinc/3rdParty/vcpkg_ports/triplets/ci/wasm32-emscripten.cmake
-- Downloading https://github.com/openssl/openssl/archive/openssl-3.0.8.tar.gz -> openssl-openssl-openssl-3.0.8.tar.gz...
-- Extracting source /home/tal/boinc/3rdParty/wasm/vcpkg/downloads/openssl-openssl-openssl-3.0.8.tar.gz
-- Applying patch disable-install-docs.patch
-- Applying patch script-prefix.patch
-- Applying patch windows/install-layout.patch
-- Applying patch windows/install-pdbs.patch
-- Applying patch windows/umul128-arm64.patch
-- Applying patch unix/move-openssldir.patch
-- Applying patch unix/no-empty-dirs.patch
-- Applying patch unix/no-static-libs-for-shared.patch
-- Using source at /home/tal/boinc/3rdParty/wasm/vcpkg/buildtrees/openssl/src/nssl-3.0.8-d9622695f9.clean
-- Found external ninja('1.11.1.git.kitware.jobserver-1').
-- Getting CMake variables for wasm32-emscripten-rel
-- Configuring wasm32-emscripten-rel
-- Building wasm32-emscripten-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: /usr/bin/make V=1 -j 13 -f Makefile build_sw
    Working Directory: /home/tal/boinc/3rdParty/wasm/vcpkg/buildtrees/openssl/wasm32-emscripten-rel/
    See logs for more information:
      /home/tal/boinc/3rdParty/wasm/vcpkg/buildtrees/openssl/build-wasm32-emscripten-rel-out.log
      /home/tal/boinc/3rdParty/wasm/vcpkg/buildtrees/openssl/build-wasm32-emscripten-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:149 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:2 (vcpkg_build_make)
  ports/openssl/unix/portfile.cmake:112 (vcpkg_install_make)
  ports/openssl/portfile.cmake:60 (include)
  scripts/ports.cmake:147 (include)
```

```
make: depend
emmake: error: 'depend' failed: [Errno 2] No such file or directory: 'depend'
make: *** [Makefile:1392: build_sw] Error 1
```

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

[buildtrees.zip](https://github.com/microsoft/vcpkg/files/10893199/buildtrees.zip)

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

This is a regression from https://github.com/microsoft/vcpkg/pull/27261

### PR DESCRIPTION
**Pull request by talregev**
Fix #30037 
Fix #29947

This is a revert from #27261 merge. 
@dg0yt made a fix for android in #29966, but he not sure he can do it for wasm32-emscripten.
I write to him, and I am waiting for his respond. 
Also we compile android and wasm32-emscripten openssl for over 2 year now, and now it break. We are seeking for solution. 
This state of port openssl is not ideal, but it working. Until we find better solution that will not break these triplets, I am suggesting a revert. At least when I open this PR, there will be a discussion. 

If you also compile android and wasm32-emscripten openssl, please write a comment that we know there is more people are using these triplets. Thank you. 

I tested this revert on wsl2 ubuntu 22.04 with all android triplets and wasm32-emscripten

### CODE REVIEW

**Comment by dg0yt** [comment]
There is a 3.0.8  port revision which works for the desired community triplets. No one has to use master `HEAD`.
https://github.com/microsoft/vcpkg/pull/29966 is completed now even for emscripten. Time for testing is better spent on that PR than on restoring the mistakes and shortcoming of the past.

**Comment by talregev** [comment]
> There is a 3.0.8 port revision which works for the desired community triplets. No one has to use master `HEAD`. #29966 is completed now even for emscripten. Time for testing is better spent on that PR than on restoring the mistakes and shortcoming of the past.

I didn't looked for shortcoming of the past, I tested your PR for android. Also seek solution for wasm32-emscripten.
Now you present such a solution also for wasm32-emscripten, There is no need for this revert.
As I say in your fix PR. I think you doing great progress for vcpkg and openssl.
I also thank you for the fixes and moving forward with openssl.

Me and most of the users are choosing to use master `HEAD` and try to fix it as much as possible.
- not be able to be on the master, it mean there will not update from frequently updated ports that we are using. 
Also there is other workaround we can do. Port overly for openssl. It mean that in the future the other port will support the new openssl port, and it will may break the old openssl in the overlay. That why the most useable case is to be on the master `HEAD`.

**Comment by dg0yt** [comment]
> Please remove the unlike reaction from this PR.

No. It is already a *mild* expression for how negative I feel about this PR and also about some comments in the other PR.

**Comment by hushanjushi** [comment]
Just find it... Yeah, it breaks

**Comment by talregev** [comment]
@hushanjushi Please test #29966 it a fix for android and wasm32-emscripten.

**Comment by talregev** [comment]
> > Please remove the unlike reaction from this PR.
> 
> No. It is already a _mild_ expression for how negative I feel about this PR and also about some comments in the other PR.

I am sorry that I force you to have also the wasm32-emscripten fix on your PR. As you can see, other people including the opensource community I come from use it. 
I see you been looking for search for testing your PRs, for example here: #29575
You can always can approach me directly for detailed with logs testing as I usually do, that can help you fix issues quickly. 
I hope it will change your mind about me.

**Pull request closed without merging**
