### PR TITLE
[libpq] update to 16.1

### LINKED ISSUE #35398: [libpq] update to 16.1
### Library name

libpq

### New version number

16.1

### Other information that may be useful (release notes, etc...)

[Release notes](https://www.postgresql.org/docs/release/16.1/)
[Download page](https://ftp.postgresql.org/pub/source/v16.1/)

### PR DESCRIPTION
**Pull request by jimwang118**
Fixes https://github.com/microsoft/vcpkg/issues/35398

- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [X] SHA512s are updated for each updated download
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

Usage test pass with following triplets:

```
x64-windows
x64-windows-static
```

### CODE REVIEW

**Review by JonLiu1993 — DISMISSED** [review]

**Review by dg0yt — COMMENTED** [review]
Some patches should be kept unchanged:
~~~
ports/libpq/unix/no-server-tools.patch
ports/libpq/unix/python.patch
~~~
In another port, I could pass `cross_compiling=yes` as an option. If that would work here, we could drop `ports/libpq/unix/fix-configure.patch` which otherwise needs to be changed with every new version.

**Comment by jimwang118** [comment]
> Some patches should be kept unchanged:
> 
> ```
> ports/libpq/unix/no-server-tools.patch
> ports/libpq/unix/python.patch
> ```
> 
> In another port, I could pass `cross_compiling=yes` as an option. If that would work here, we could drop `ports/libpq/unix/fix-configure.patch` which otherwise needs to be changed with every new version.

Ok, I will try locally if it works, if so I will delete unnecessary patches.

**Comment by dg0yt** [comment]
`cross_compiling=yes` must be tested with a dynamic triplet on a native cpu, e.g. x64-osx-dynamic on x64-osx.

**Comment by dg0yt** [comment]
Obsolete.

**Comment by jimwang118** [comment]
Duplicate of https://github.com/microsoft/vcpkg/pull/40110.

**Pull request closed without merging**
