### PR TITLE
[libarchive ] Fix fix build on iOS

### PR DESCRIPTION
**Pull request by nirvn**
This pull request fixes libarchive building on iOS by setting `ENABLE_UNZIP=OFF`.

The PR is a companion to https://github.com/microsoft/vcpkg/pull/41896 . With both of the PRs in, we can build gdal on iOS with rar and 7z archived datasets support.

### CODE REVIEW

**Comment by dg0yt** [comment]
Wait. The tools are intentionally turned off, and they shall remain in the default features.

**Comment by nirvn** [comment]
@dg0yt , sorry, I wasn't clear. The tools were building unconditionally until this PR, which led to a broken build on iOS. To avoid a behavior change by default, the tools are added as a default-features for all platforms _except_ for iOS.

**Comment by dg0yt** [comment]
AFAICT you were clear, but mostly wrong. Look:

https://github.com/microsoft/vcpkg/blob/4f746bc66438fce2b900c3ba6094a483b871b045/ports/libarchive/portfile.cmake#L59-L61

UNZIP is missing, and the fix is to disable it, too.

**Comment by nirvn** [comment]
@dg0yt , oh, well spotted. Then the question becomes: do we want to allow for these tools to be built at all, and if so add a non-default feature for it. Or should we just disable all of it all the time?

**Comment by dg0yt** [comment]
I gave my opinion: "(...)UNZIP(=OFF) is missing, and the fix is to disable it, too." 

Keep it simple. Vcpkg focuses on libraries. These particulary executable names are generally expected to be provided by the system or by other packages.

**Comment by nirvn** [comment]
@dg0yt , OK, PR adapted to follow your suggestion.

**Review by dg0yt — APPROVED** [review]
LGTM but someone else must approve.

**Review by FrankXie05 — APPROVED** [review]

**Comment by nirvn** [comment]
This is ready for merging.

**Pull request merged**
