### PR TITLE
[abseil] Fix CMake warning

### PR DESCRIPTION
**Pull request by Dico200**
**Describe the pull request**

- What does your PR fix? 
It applies the same fix as [this abseil commit](https://github.com/abseil/abseil-cpp/commit/68494aae959dfbbf781cdf03a988d2f5fc7e4802)
This warning:
```
CMake Warning (dev) at C:/Users/Dico/AppData/Local/JetBrains/Toolbox/apps/CLion/ch-0/202.6397.106/bin/cmake/win/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args` (Threads)
  does not match the name of the calling package (absl).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  C:/Users/Dico/AppData/Local/JetBrains/Toolbox/apps/CLion/ch-0/202.6397.106/bin/cmake/win/share/cmake-3.17/Modules/FindThreads.cmake:234 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  C:/repos/vcpkg/installed/x64-windows-static-md/share/absl/abslConfig.cmake:3 (include)
  C:/repos/vcpkg/scripts/buildsystems/vcpkg.cmake:439 (_find_package)
  C:/repos/vcpkg/installed/x64-windows-static-md/share/gRPC/gRPCConfig.cmake:18 (find_package)
  C:/repos/vcpkg/scripts/buildsystems/vcpkg.cmake:437 (_find_package)
  CMakeLists.txt:27 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

- Which triplets are supported/not supported? Have you updated the CI baseline? 
N/A

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
I read through the guide, I think so, except that there is no CONTROL file in this port (I bumped the version in vcpkg.json)

### CODE REVIEW

**Comment by Dico200** [comment]
I ran the command to format the manifest file - `vcpkg x-format-manifest --all`, it did not make any changes. I also did not change any formatting in the vcpkg.json file.

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
Hi @Dico200 
Thanks for this PR.

have you tested the feature `cxx17`?

**Comment by NancyLi1013** [comment]
Feature `cxx17 `has passed with the following triplets:

- x86-windows
- x64-windows
- x64-windows-static

**Comment by Dico200** [comment]
Hi @NancyLi1013 , it's a small effort :) thanks for the review!
I just tested the [cxx17] feature with success as well for x86-windows, x64-windows-static and even x64-windows-static-md.

**Pull request merged**
