### PR TITLE
Fix sdl2 dependents

### LINKED ISSUE #6152: The release build of SDL2-image depends on the debug build of SDL2
The issue seems related to the search for the SDL library 

ports/sdl2-image/CMakeLists.txt:
find_library(SDL_LIBRARY NAMES SDL2d SDL2)

Note that this pattern seems to be present in other SDL2-xxx libraries, and maybe other ports as well.

### PR DESCRIPTION
**Pull request by cbezault**
Resolves #6152.

### CODE REVIEW

**Comment by grdowns** [comment]
Perhaps it might be best to write this into the `vcpkg_cmake_wrapper.cmake` to populate `SDL_LIBRARY_RELEASE` and `SDL_LIBRARY_DEBUG` so that less ports have to be touched by this? It might also aid authoring ports in the future.

**Comment by Neumann-A** [comment]
The patch should use `find_package` instead of `find_library`. 
SDL2 exports targets and linking against those is probably desirable.

**Comment by cbezault** [comment]
@Neumann-A, I agree, thanks for taking a look.

**Comment by cbezault** [comment]
Same as #5948

**Pull request closed without merging**
