### PR TITLE
[tesseract] update to 5.2.0

### LINKED ISSUE #16019: [tesseract] update to 5.x.x
Library name: tesseract

New version number: 5.0.0-alpha-20201231

https://github.com/tesseract-ocr/tesseract/releases/tag/5.0.0-alpha-20201231

https://abi-laboratory.pro/?view=timeline&l=tesseract
5.0.0-alpha is only 36% backward compatible.
So vcpkg should have options to build the old 4.1.1 as well as new 5.0.0-alpha (with HEAD_REF master).

Opening a new issue as suggested by @NancyLi1013 in https://github.com/microsoft/vcpkg/issues/10624#event-4283543880

### PR DESCRIPTION
**Pull request by LilyWangLL**
**Describe the pull request**

- #### What does your PR fix?
  Fixes #16019, update `tesseract` to version 5.2.0.

### CODE REVIEW

**Comment by jasonodomtaqtile** [comment]
I am trying to build a version of Tesseract to work with HoloLens 2 arm-uwp(hoping this will work)  @LilyWangLL any chance of fixing these check errors?

**Comment by LilyWangLL** [comment]
> I am trying to build a version of Tesseract to work with HoloLens 2 arm-uwp(hoping this will work) @LilyWangLL any chance of fixing these check errors?

I will try.

**Comment by LilyWangLL** [comment]
@jasonodomtaqtile `tesseract` depends on `libarchive` and `leptonica`, and they all don't support `uwp`, so `tesseract` can't install on `uwp`.

**Review by JackBoosY — APPROVED** [review]

**Comment by JavierMatosD** [comment]
Thank You!

**Comment by cenit** [comment]
This PR broke opencv3 and highlights the importance of restoring the port in the CI tests...

**Comment by cenit** [comment]
It should be a mantra: every patch to opencv4 almost surely has an equivalent for opencv3 and maybe even for opencv2...

**Comment by cenit** [comment]
this update also broke normal tesseract downstream usage, or at least highlighted a non-tracked CURL dependency which breaks cache sharing between projects

**Comment by cenit** [comment]
I will open a PR asap trying to fix both errors

**Pull request merged**
