### PR TITLE
[stb] Bump version and remove downloading stb_perlin separately since that patent is expired

### PR DESCRIPTION
**Pull request by xiaozhuai**
- #### What does your PR fix?
1. Bump to latest version
2. Remove downloading stb_perlin separately since that patent is expired
3. Add usage

### CODE REVIEW

**Comment by xiaozhuai** [comment]
Hello @Neumann-A , Why all the CI process is in Quened state?

**Comment by xiaozhuai** [comment]
> Why are you pinging me? There are simply too many prs building a lot of stuff so ci us a bit overloaded

I thought CI was broken, sorry for bothering.

**Comment by Neumann-A** [comment]
Even if CI would be broken I could do nothing about it. I am not a maintainer.

**Comment by BillyONeal** [comment]
Thanks for the update!

**Pull request merged**
