### PR TITLE
[tiff] add vcpkg_fixup_pkgconfig for tiff

### PR DESCRIPTION
**Pull request by Neumann-A**

### CODE REVIEW

**Comment by JackBoosY** [comment]
Can this PR fix #15730?

**Comment by Neumann-A** [comment]
@JackBoosY No. I did not touch vcpkg_fixup_pkgconfig here I just added it to the port here so that the tiff *.pc files are working. vcpkg_fixup_pkgconfig still needs a check for correctness/useability.

**Comment by Neumann-A** [comment]
- [ ] probably need to rerun the version command.

**Comment by JackBoosY** [comment]
@Neumann-A  Yes, please update the baseline record.

**Review by JackBoosY — APPROVED** [review]

**Review by ras0219 — APPROVED** [review]

**Comment by JackBoosY** [comment]
LGTM now, already merged from master.

**Pull request merged**
