### PR TITLE
[range-v3] updates REF to range-v3:HEAD

### LINKED ISSUE #21391: [range-v3] update to head
**Library name:** range-v3

**New version number:** head

**Other information that may be useful (release notes, etc...)**

Several new adaptors have been added.

### PR DESCRIPTION
**Pull request by cjdb**
Closes #21391.

**Describe the pull request**

- #### What does your PR fix?  
  Fixes #21391

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  Unchanged

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Unchanged

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes.

### CODE REVIEW

**Comment by cenit** [comment]
if you need head version and not a release one, why not installing it using --head tag?

**Comment by cjdb** [comment]
> if you need head version and not a release one, why not installing it using --head tag?

Two reasons:

1. vcpkg manifests don't seem to support a `--head` option.
2. The latest release of range-v3 is 0.11.0, which is pretty stale now. range-v3 doesn't issue releases all that often.

**Comment by cenit** [comment]
agree for manifest but that's not a valid point for this PR.
Also, this HEAD is valid only for today, because it's fixed by the commit you put into the vcpkg_from_github command.

A valid solution would be to move to `version-date` in vcpkg.json and put commit's date, then remove any "head" reference you put in the port file, and hope that vcpkg maintainer move range-v3 from a release-based port to a date-commit based port

**Comment by cjdb** [comment]
> agree for manifest but that's not a valid point for this PR. Also, this HEAD is valid only for today, because it's fixed by the commit you put into the vcpkg_from_github command.
> 
> A valid solution would be to move to `version-date` in vcpkg.json and put commit's date, then remove any "head" reference you put in the port file, and hope that vcpkg maintainer move range-v3 from a release-based port to a date-commit based port

Ah, gotcha. To paraphrase: you're in favour of the PR, but want to see "head" changed to the commit-date?

**Comment by cjdb** [comment]
When following the advice by GitHub Actions, I get this:
```
$ ./vcpkg x-add-version --all
Error: Local changes detected for range-v3 but no changes to version or port version.
-- Version: 2021-11-02#2
-- Old SHA: e7735ee7049d2de2753aa92649599bba68681f5c
-- New SHA: c61fd3747fcd7908eec6f482af77edb6b3064c3b
-- Did you remember to update the version or port version?
-- Pass `--overwrite-version` to bypass this check.
***No files were updated.***
```

**Comment by cenit** [comment]
now it's ok, apart from that `port-version` should have not been bumped, on the contrary it should have been removed, because `version(-date)` now is different from before - it's an update! 

(it should be bumped only when keeping commit identical in the `vcpkg_from_github` call and you are fixing other things in the port - in that case `version(-date)` stays the same, you bump `port-version`, i hope it's clear...)

**Review by JonLiu1993 — CHANGES_REQUESTED** [review]

**Review by JonLiu1993 — APPROVED** [review]

**Review by PhoebeHui — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the update!

**Pull request merged**
