### PR TITLE
Added port for OpenMAMA 6.2.1.SNAPSHOT

### PR DESCRIPTION
**Pull request by fquinner**
This is a snapshot version since it contains some changes
necessary to get vcpkg to play nicely with it.

When 6.2.2 is released, this port will be updated with it.

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thank you for the PR!

I believe this is actually linking the _Release_ versions of OpenMAMA's dependencies in Debug mode, which could cause a runtime failure in anyone who tries to use the debug version of OpenMAMA. The debug versions of libraries are located under the `\debug\lib` subdirectory.

I tried separating the calls to SCONS and passing `\debug` to the various home settings, but then it's unable to locate the include headers. I then tried to inject that directory via an environment variable[1], but this is blocked by scons [2].

I think the right way to proceed is to patch the scons files to enable injection from the environment (I also fear that scons is _not_ currently picking up the correct compiler due to this!), however I've reached the limits of my understanding of the system.

[1] https://msdn.microsoft.com/en-us/library/kezkeayy.aspx
[2] https://bitbucket.org/scons/scons/wiki/FrequentlyAskedQuestions#markdown-header-why-doesnt-scons-find-my-compilerlinkeretc-i-can-execute-it-just-fine-from-the-command-line

**Comment by fquinner** [comment]
Thanks Robert - yeah I'll have a look at this I know we had issues in the past with debug builds because dependencies generated library files with the same name in the same location... something which I expect vcpkg will help with. I am keen to get OpenMAMA off scons and on to cmake because of its inflexibility around things like this. They have also ditched python 2.7 in latest releases which effectively puts our build scripts out of maintenance (which is I think why its not playing nicely with the latest versions of VS 2017 - something I literally found out yesterday).

Anyway, many thanks for the detailed response - plenty to chew on. I'll action and respond.

**Comment by fquinner** [comment]
Given the proposed short term nature of the scons build system in our project, I have opted to simply add a vcpkg_build boolean option to the OpenMAMA build system to let the build system know that its dependencies are being provided using vcpkg standards (i.e. look in a debug subdirectory for libs, but don't expect headers to be included in there).

Let me know if this is good to go now?

**Comment by ras0219-msft** [comment]
Sorry for the delay!

When trying to test `openmama:x64-windows`, I currently get build failures while running `scons.py`. I haven't yet investigated more deeply, but I'll keep you posted!

**Comment by fquinner** [comment]
Thanks, what version of visual studio you running?

**Comment by fquinner** [comment]
@ras0219-msft I just tried with both the branch on my fork and the branch on the Microsoft org and they worked fine on a fresh box with a vanilla build of Visual Studio Community 2017. If you can send me over some details about the issues i'd be happy to help! If you are looking for more immediate responses you can usually find me on https://gitter.im/OpenMAMA/OpenMAMA. I'm keen to get this resolved!

**Comment by ras0219-msft** [comment]
Huh, everything is working now. Sorry for the trouble and thank you very much for staying on top of this!

**Comment by fquinner** [comment]
Fantastic news thank you for all of your help!

**Pull request merged**
