### PR TITLE
[vcokg] provision-image.sh: add kf5globalaccel new requires

### PR DESCRIPTION
**Pull request by wrobelda**
**Describe the pull request**

- #### What does your PR fix?
  Adds new packages as required by kf5globalaccel in #26831

### CODE REVIEW

**Comment by Neumann-A** [comment]
related: #27279

**Review by JonLiu1993 — DISMISSED** [review]

**Comment by BillyONeal** [comment]
This failed with

> Unable to locate package llibxcb-keysyms1-dev

**Comment by wrobelda** [comment]
> > Unable to locate package llibxcb-keysyms1-dev

Nasty typo. Fixed.

**Comment by wrobelda** [comment]
> > Unable to locate package llibxcb-keysyms1-dev

Nasty typo. Fixed.

**Comment by JonLiu1993** [comment]
Duplicate of #27718

**Pull request closed without merging**
