### PR TITLE
[akali] Update to v1.41

### PR DESCRIPTION
**Pull request by winsoft666**

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
LGTM, thanks!

**Comment by vicroms** [comment]
HI @winsoft666 

Please remove the line `akali:x64-osx=fail` from `/scripts/ci.baseline.txt`.

**Comment by winsoft666** [comment]
OK, I have removed the line akali:x64-osx=fail from /scripts/ci.baseline.txt.
Please recheck it.

**Comment by vicroms** [comment]
Thanks for the PR!

**Pull request merged**
