### PR TITLE
[mesa] Update to 21.1.6

### PR DESCRIPTION
**Pull request by PhoebeHui**
Extract the mesa changes from https://github.com/microsoft/vcpkg/pull/17302/

dual-osmesa-part2b.patch doesn't apply to the port, so remove it.

### CODE REVIEW

**Comment by xavier2k6** [comment]
Latest [mesa] 21.1.5 - Released 14th July 2021

ref.:
https://docs.mesa3d.org/relnotes.html

**Review by JackBoosY — APPROVED** [review]

**Comment by pal1000** [comment]
The build failure is in `-Dshared-swr=false` configuration which is apparently uncommon enough that it didn't get enough testing and broke. I personally never planned to add support for it in mesa-dist-win.

**Comment by PhoebeHui** [comment]
@pal1000, thanks for your reply! 

Then keep skip mesa:x64-windows-static-md in CI testing. cc @Neumann-A.

**Comment by BillyONeal** [comment]
Thanks for the version update!

**Pull request merged**
