### PR TITLE
[activemq-cpp] Inclusion of SSL and static building.

### PR DESCRIPTION
**Pull request by rotrida**
Fixes issue #9138 and also add SSL option to use with original library

### CODE REVIEW

**Comment by Neumann-A** [comment]
Build will fail with openssl 1.1.1d due to missing library dependencies

**Comment by rotrida** [comment]
> Build will fail with openssl 1.1.1d due to missing library dependencies

Hi Neumman-A,

Would you know which dependency is missing?

Thanks.

**Comment by Neumann-A** [comment]
`crypt32` and the openssl libraries are differently named with the update to 1.1.1d

**Comment by PhoebeHui** [comment]
@rotrida, thanks for the PR! Have you test the feature 'ssl' ? Also does the dependencies issue which Neumann-A mentioned solve?

**Comment by rotrida** [comment]
Hi @Phoebe,

I couldn't test the feature properly yet. Also I didn't have time to
implement the changes suggested by Neumann-A. My intention is to come back
to it soon.

Thanks,

Rodrigo.

**Comment by PhoebeHui** [comment]
@rotrida,  do you have a chance to address the review suggestions? Thanks!

**Comment by PhoebeHui** [comment]
Thanks for the PR; we're closing this for now since there's been no response. If you'd like to continue working on it, please reopen and ping us!

**Pull request closed without merging**
