### PR TITLE
[kf5] Update to 5.98

### PR DESCRIPTION
**Pull request by wrobelda**
**Describe the pull request**

Updates KF5 framework libraries to 5.98 (note the branch name bears a wrong version number by a typo).

Depends on:
- [x] https://bugs.kde.org/show_bug.cgi?id=460656  (an interim workaround was applied here)
- [ ] #27454 

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  No change

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by Cheney-W** [comment]
```
CMake Error at /agent/_work/1/s/scripts/buildsystems/vcpkg.cmake:829 (_find_package):
  Found package configuration file:
    /mnt/vcpkg-ci/installed/x64-linux/share/KF5CoreAddons/KF5CoreAddonsConfig.cmake
  but it set KF5CoreAddons_FOUND to FALSE so package "KF5CoreAddons" is
  considered to be NOT FOUND.  Reason given by package:
  KF5CoreAddons could not be found because dependency Inotify could not be
  found.

```
[/mnt/vcpkg-ci/buildtrees/kf5configwidgets/config-x64-linux-out.log](https://dev.azure.com/vcpkg/_apis/resources/Containers/18561501/failure%20logs%20for%20x64-linux?itemPath=failure%20logs%20for%20x64-linux%2Fkf5configwidgets%2Fconfig-x64-linux-out.log)

[/mnt/vcpkg-ci/buildtrees/kf5globalaccel/config-x64-linux-out.log](https://dev.azure.com/vcpkg/_apis/resources/Containers/18561501/failure%20logs%20for%20x64-linux?itemPath=failure%20logs%20for%20x64-linux%2Fkf5globalaccel%2Fconfig-x64-linux-out.log)

**Comment by wrobelda** [comment]
@Cheney-W I am aware, this is still a Draft, no need to review it yet.

**Comment by Cheney-W** [comment]
Is work still being done for this PR?

**Comment by wrobelda** [comment]
> Is work still being done for this PR?

Yes, still a WIP

**Comment by wrobelda** [comment]
@Cheney-W this is ready for review now. `kf5globalaccel` fails right now because it requires additional OS dependencies: https://github.com/microsoft/vcpkg/commit/6e767509afa9c3ad38c0774b159b6f6946682091

**Comment by wrobelda** [comment]
ping @Cheney-W

**Comment by Cheney-W** [comment]
If the additional OS dependencies: 6e76750 are necessary for new kf5globalaccel version, I think we can add `kf5globalaccel:x64-linux=fail` to `ci.baseline.txt` for now to solve this problem for PR merge, and then we can raise an issue to request the required libraries for CI linux machines.

**Comment by wrobelda** [comment]
> If the additional OS dependencies: 6e76750 are necessary for new kf5globalaccel version, I think we can add `kf5globalaccel:x64-linux=fail` to `ci.baseline.txt` for now to solve this problem for PR merge, and then we can raise an issue to request the required libraries for CI linux machines.

The problem is that if you ignore `kf5globalaccel`, then you also ignore other ports that depend on it, and it's more than a few in total in this PR. I cannot 100% vouch that these dependents compile fine in your CI and we don't want to break the mainline CI. 

I pushed similar PRs before with similar changes to the CI images. I believe the way it usually worked was that you either tested them locally on your end, or had the image(s) updated first. I can break out that commit into a separate PR and we can wait with this one until the images are rebuilt.

**Comment by Neumann-A** [comment]
Did you add the `xcb` dependency in the manifest ?

**Comment by wrobelda** [comment]
> Did you add the `xcb` dependency in the manifest ?

I did not, wasn't aware it exists at all. Testing with it now.

**Comment by Neumann-A** [comment]
> I had not, wasn't aware it existed at all. Testing with it now.

It will tell you that it needs to be installed by your system ;) I just want to have the dep be explicit.

**Comment by wrobelda** [comment]
> It will tell you that it needs to be installed by your system ;) I just want to have the dep be explicit.

OK, so the idea is that `xcb` right now only informs about a need to install a system package, but you're working in https://github.com/microsoft/vcpkg/pull/27279 on getting it to actually be self-sufficient on Linux?

My beef with it is that even if it still asks to install system packages, it pulls in many dependencies which end up not needed? Or am I missing something?

**Comment by Neumann-A** [comment]
> My beef with it is that even if it still asks to install system packages, it pulls in many dependencies which end up not needed? Or am I missing something?

```
$ ./vcpkg.exe depend-info xcb
vcpkg-cmake:
vcpkg-cmake-config:
libiconv:
liblzma: vcpkg-cmake, vcpkg-cmake-config
zlib: vcpkg-cmake
libxml2[tools]: libiconv, liblzma, vcpkg-cmake, vcpkg-cmake-config, zlib
libxslt[default-features]: libxml2, vcpkg-cmake, vcpkg-cmake-config
pthreads:
vcpkg-tool-meson:
xorg-macros:
bzip2[tool]: vcpkg-cmake, vcpkg-cmake-config
pthread: pthreads
xproto: libxslt, vcpkg-tool-meson, xorg-macros
libxau: bzip2, xorg-macros, xproto
libxdmcp: bzip2, xorg-macros, xproto
pthread-stubs: pthread
xcb-proto: bzip2, libxml2, xorg-macros
xcb-util-m4:
xcb: bzip2, libxau, libxdmcp, libxslt, pthread, pthread-stubs, xcb-proto, xcb-util-m4, xorg-macros, xproto
```


Should only really build:
```
vcpkg-cmake:
vcpkg-cmake-config:
libiconv:
liblzma: vcpkg-cmake, vcpkg-cmake-config
zlib: vcpkg-cmake
libxml2[tools]: libiconv, liblzma, vcpkg-cmake, vcpkg-cmake-config, zlib
libxslt[default-features]: libxml2, vcpkg-cmake, vcpkg-cmake-config
bzip2[tool]: vcpkg-cmake, vcpkg-cmake-config
pthread: pthreads
```
which are probably already pulled in partial by something different.

**Comment by wrobelda** [comment]
> xcb-proto, xcb-util-m4, xorg-macros, xproto

OK, but what's the point of building _these_ on Linux at all? They should be marked appropriately in xcv's vcpkg.json to not be pulled in on !Windows, since there's no use for them anyway at this point.

**Comment by Neumann-A** [comment]
> OK, but what's the point of building these on Linux at all? They should be marked appropriately in xcv's vcpkg.json to not be pulled in on !Windows, since there's no use for them anyway at this point.

To make the dependency explicit and not implicit! (Those are all empty ports unless you set a triplet variable)

**Comment by wrobelda** [comment]
> To make the dependency explicit and not implicit! (Those are all empty ports unless you set a triplet variable)

Fair enough. Thanks.

**Comment by Cheney-W** [comment]
@wrobelda Could you please solve the conflicts?

**Comment by wrobelda** [comment]
> @wrobelda Could you please solve the conflicts?

Done.

**Pull request merged**
