### PR TITLE
Adding Breakpad port

### PR DESCRIPTION
**Pull request by DanOlivier**
Can someone please check this out?
I'm new to vcpkg and this involves some (subjectively) intricate cmake code (i.e. Breakpad version, dependencies, use of patched gyp, etc).
Thanks

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Hi @DanOlivier, thanks for the PR!

To ensure repeatable builds, we have a policy that every portfile should have checked-in hashes for all downloaded components of builds -- in this case, that would include GYP. This means we need to pull a stable hash for GYP, instead of the constantly-in-flux "testing" branch.

In the past, we did try to build `libuv` using gyp[1], however it turns out that this was _far_ more complicated, less stable, and less featureful than providing a simple CMake replacement[2][3]. I'd highly encourage you to look into replacing gyp with CMake (using the `libuv` example below as a guide) before trying to "stabilize" gyp.

[1] https://github.com/Microsoft/vcpkg/blob/69f92e73cedf97a38c39ce610cf5036ec21c46b9/ports/libuv/portfile.cmake
[2] https://github.com/Microsoft/vcpkg/blob/eea8a63179648a21313328d2d38966cc4bc297e8/ports/libuv/portfile.cmake
[3] https://github.com/Microsoft/vcpkg/blob/eea8a63179648a21313328d2d38966cc4bc297e8/ports/libuv/CMakeLists.txt

**Comment by DanOlivier** [comment]
I'll hopefully get back to this soon. Apologies.

**Comment by janisozaur** [comment]
FWIW: crashpad has a fork that has some cmake integrated: https://github.com/qedsoftware/crashpad

**Comment by DanOlivier** [comment]
Hi. Uh, sorry for the long delay.

1. whatever the similarities or shared history between breakpad and crashpad, from what I can tell right now, they are nothing alike in terms of file names and directory structure, so I don't know how portable the crashpad-cmake solution might be.
2. you're suggesting that we adapt the build system chosen by the 3rd-party to use cmake, but that is not always possible, given the diversity of solutions, and the wide diversity in complexity in their implementations. Basically, this could be a 2-day job or a 2-week job. It depends. Even if a cmake-base solution is written, it may not be cross platform and may lack in flexibility or completeness. 
3. I'm only performing a "port", and that I have no in-depth knowledge of either breakpad, or gyp. Indeed, I apply patches to breakpad's gyp files that might not suit all potential users (override /MT to /MD, and disable warnings, due to use of VC++17)
3. Nevertheless, the main concern here seems to be NOT that we are using gyp to perform the build, but that we're not selecting a stable, repeatable baseline (of the build tools) to use to build breakpad. Indeed, what would happen if we were talking about a SCons-based solution instead? or any one of a half-dozen other prominent solutions (autotools + gcc toolchain, waf, bazel, etc)? It shouldn't matter if the solution is to use batch files with direct invocations to the toolchain (though I understand the urge and need to standardize).
4. the "testing" branch applies to gtest, which (in addition to gyp) is also fetched as part of the build, and is required in a specific location (ultimately) for the build to complete smoothly (and not because I really care about the outcome), and it was easier to just put it there, rather than try to a) bypass the building (and running?) of tests, or b) have vcpkg find the dependency from the target "image" triple (i.e. vcpkg/installed/triple-dir/).

Would it be sufficient if we just added the commit ID to the clone command line, so that we aren't retrieving moving targets?

**Comment by ras0219-msft** [comment]
You're correct that the number 1 concern is stability! As long as that goal is achieved, I'd be happy to accept the PR.

My comments regarding GYP were to share my previous experience with making gyp stable -- while it appeared to work initially, I continued to experience more and more obstacles and unexpected issues until I simply rewrote the buildsystem in CMake which completely fixed the issue (and has the benefit of standardization as you mentioned). This also automatically fixes `/MD` and `/MT` and was _shorter and more maintainable_ than the sum of the portfile and patches.

**Comment by ras0219-msft** [comment]
I've pushed a CMake-based replacement to master in 0f607865 -- could you try it out and let me know if it works for you?

**Comment by DanOlivier** [comment]
Can't seem to get it (libdisasm) to build (after changing the SHA512)...
```
dan_o@Athena MINGW64 ~/tools/vcpkg (master)
$ vcpkg install breakpad
The following packages will be built and installed:
    breakpad[core]:x64-windows
  * libdisasm[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: libdisasm:x64-windows
Building package libdisasm[core]:x64-windows...
-- CURRENT_INSTALLED_DIR=C:/Users/dan_o/tools/vcpkg/installed/x64-windows
-- DOWNLOADS=C:/Users/dan_o/tools/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/Users/dan_o/tools/vcpkg/packages/libdisasm_x64-windows
-- CURRENT_BUILDTREES_DIR=C:/Users/dan_o/tools/vcpkg/buildtrees/libdisasm
-- CURRENT_PORT_DIR=C:/Users/dan_o/tools/vcpkg/ports/libdisasm/.
CMake Warning at C:/Users/dan_o/tools/vcpkg/ports/libdisasm/portfile.cmake:4 (message):
  Warning: Dynamic building not supported.  Building static.
Call Stack (most recent call first):
  C:/Users/dan_o/tools/vcpkg/scripts/ports.cmake:72 (include)


-- Using cached C:/Users/dan_o/tools/vcpkg/downloads/libdisasm-0.23.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting source C:/Users/dan_o/tools/vcpkg/downloads/libdisasm-0.23.tar.gz
CMake Error at C:/Users/dan_o/tools/vcpkg/scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: C:/Users/dan_o/tools/vcpkg/downloads/cmake-3.10.2-win32-x86/bin/cmake.exe;-E;tar;xjf;C:/Users/dan_o/tools/vcpkg/downloads/libdisasm-0.23.tar.gz
    Working Directory: C:/Users/dan_o/tools/vcpkg/buildtrees/libdisasm/src
    See logs for more information:
      C:\Users\dan_o\tools\vcpkg\buildtrees\libdisasm\extract-err.log

Call Stack (most recent call first):
  C:/Users/dan_o/tools/vcpkg/scripts/cmake/vcpkg_extract_source_archive.cmake:49 (vcpkg_execute_required_process)
  C:/Users/dan_o/tools/vcpkg/scripts/cmake/vcpkg_extract_source_archive.cmake:61 (vcpkg_extract_source_archive_ex)
  C:/Users/dan_o/tools/vcpkg/ports/libdisasm/portfile.cmake:17 (vcpkg_extract_source_archive)
  C:/Users/dan_o/tools/vcpkg/scripts/ports.cmake:72 (include)


Error: Building package libdisasm:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libdisasm:x64-windows
  Vcpkg version: 0.0.105-2018-02-25-8c8fc1a28afd8fa8ea149528d68c264cc1182dd7

Additionally, attach any relevant sections from the log files above.
```

**Comment by ras0219-msft** [comment]
>      vcpkg\buildtrees\libdisasm\extract-err.log

That looks like the archive you downloaded is corrupted somehow. Try this:
- Reset the SHA512 back to what's on master
- Run the build
- When it fails, download the file manually using your web browser and put it in `downloads\` with the appropriate name
- Retry the build

If the build succeeds, then we've got a problem somewhere in the download process. The most common instance of this that I've seen is due to proxies, in which case you'll need to set the `HTTPS_PROXY` and `HTTP_PROXY` environment variables for curl to use your proxy.

**Comment by ras0219-msft** [comment]
Since breakpad is in vcpkg master, I'll close this PR. If we missed something, please open a new PR!

**Comment by janisozaur** [comment]
Sounds good, I tried using breakfast before https://github.com/Microsoft/vcpkg/pull/4008 and it didn't work, I'll retry with updated vcpkg.

**Pull request closed without merging**
