### PR TITLE
[ffmpeg] srt support

### PR DESCRIPTION
**Pull request by fran6co**
Fixes https://github.com/microsoft/vcpkg/pull/23575

### CODE REVIEW

**Comment by fran6co** [comment]
libsrt was generating srt_static.lib instead of srt.lib on Windows and that was breaking the static build. Added a patch to force the correct name so pkgconfig finds it

**Comment by fran6co** [comment]
Actually it still doesn't work.
It's linking against this libs `srt.lib libssl.lib libcrypto.lib crypt32.lib ws2_32.lib` but I'm getting this errors:

```
libcrypto.lib(libcrypto-lib-cryptlib.obj) : error LNK2019: unresolved external symbol __imp_DeregisterEventSource referenced in function OPENSSL_showfatal
libcrypto.lib(libcrypto-lib-cryptlib.obj) : error LNK2019: unresolved external symbol __imp_RegisterEventSourceW referenced in function OPENSSL_showfatal
libcrypto.lib(libcrypto-lib-cryptlib.obj) : error LNK2019: unresolved external symbol __imp_ReportEventW referenced in function OPENSSL_showfatal
libcrypto.lib(libcrypto-lib-cryptlib.obj) : error LNK2019: unresolved external symbol __imp_GetProcessWindowStation referenced in function OPENSSL_isservice
libcrypto.lib(libcrypto-lib-cryptlib.obj) : error LNK2019: unresolved external symbol __imp_GetUserObjectInformationW referenced in function OPENSSL_isservice
libcrypto.lib(libcrypto-lib-cryptlib.obj) : error LNK2019: unresolved external symbol __imp_MessageBoxW referenced in function OPENSSL_showfatal
libcrypto.lib(libcrypto-lib-e_capi.obj) : error LNK2019: unresolved external symbol __imp_CryptAcquireContextW referenced in function capi_ctx_set_provname
libcrypto.lib(libcrypto-lib-e_capi.obj) : error LNK2019: unresolved external symbol __imp_CryptReleaseContext referenced in function capi_ctx_set_provname
libcrypto.lib(libcrypto-lib-e_capi.obj) : error LNK2019: unresolved external symbol __imp_CryptDestroyKey referenced in function capi_dsa_free
libcrypto.lib(libcrypto-lib-e_capi.obj) : error LNK2019: unresolved external symbol __imp_CryptSetHashParam referenced in function capi_dsa_do_sign
libcrypto.lib(libcrypto-lib-e_capi.obj) : error LNK2019: unresolved external symbol __imp_CryptGetProvParam referenced in function capi_list_containers
libcrypto.lib(libcrypto-lib-e_capi.obj) : error LNK2019: unresolved external symbol __imp_CryptGetUserKey referenced in function capi_get_key
libcrypto.lib(libcrypto-lib-e_capi.obj) : error LNK2019: unresolved external symbol __imp_CryptExportKey referenced in function capi_get_pkey
libcrypto.lib(libcrypto-lib-e_capi.obj) : error LNK2019: unresolved external symbol __imp_CryptDecrypt referenced in function capi_rsa_priv_dec
libcrypto.lib(libcrypto-lib-e_capi.obj) : error LNK2019: unresolved external symbol __imp_CryptCreateHash referenced in function capi_dsa_do_sign
libcrypto.lib(libcrypto-lib-e_capi.obj) : error LNK2019: unresolved external symbol __imp_CryptDestroyHash referenced in function capi_dsa_do_sign
libcrypto.lib(libcrypto-lib-e_capi.obj) : error LNK2019: unresolved external symbol __imp_CryptSignHashW referenced in function capi_dsa_do_sign
libcrypto.lib(libcrypto-lib-e_capi.obj) : error LNK2019: unresolved external symbol __imp_CryptEnumProvidersW referenced in function capi_get_provname
```

**Comment by fran6co** [comment]
Something is missing in openssl pkgconfig

**Comment by fran6co** [comment]
Fixed by adding `-ladvapi32 -luser32` to libcrypto deps

**Comment by fran6co** [comment]
Arm windows is failing at the package osg with something that looks unrelated:
```
CMake Error: try_run() invoked in cross-compiling mode, please set the following cache variables appropriately:
   _OPENTHREADS_ATOMIC_USE_WIN32_INTERLOCKED_EXITCODE (advanced)
   _OPENTHREADS_ATOMIC_USE_WIN32_INTERLOCKED_EXITCODE__TRYRUN_OUTPUT (advanced)
``

**Comment by fran6co** [comment]
Not sure what is going with uwp

**Comment by dg0yt** [comment]
> Arm windows is failing at the package osg with something that looks unrelated:

osg:arm64-windows also fails for https://github.com/microsoft/vcpkg/pull/26676#issuecomment-1236331383.

**Comment by JonLiu1993** [comment]
@fran6co,  From the ci error log it looks like it should be caused by not finding OpenEXR after a long list of warnings,
````
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The following OPTIONAL packages have been found:

 * OpenGL
 * Jasper
 * LibXml2
 * GDAL
 * GTA
 * CURL
 * SDL2, low level access to audio, keyboard, mouse, joystick, and graphics hardware, <https://www.libsdl.org/>
 * GIFLIB
 * JPEG
 * ZLIB
 * PNG
 * TIFF
 * Threads
 * Fontconfig
 * Freetype
 * EXPAT

-- The following OPTIONAL packages have not been found:

 * EGL
 * ilmbase
 * OpenCascade
 * COLLADA
 * FBX
 * LibVNCServer
 * DirectShow
 * Poppler-glib
 * RSVG
 * GtkGl
 * DirectInput
 * NVTT
 * ZeroConf
 * LIBLAS
 * QuickTime

-- The following REQUIRED packages have not been found:

 * OpenEXR

-- Configuring incomplete, errors occurred!
````

**Comment by fran6co** [comment]
Is the OpenEXR problem related to the changes to this PR?

**Comment by JonLiu1993** [comment]
> Is the OpenEXR problem related to the changes to this PR?

OpenEXR is related to osg, osg is not related to ffmpeg

**Comment by JonLiu1993** [comment]
Depend on #26646

**Comment by dg0yt** [comment]
> Depend on #26646

No, the baseline issue is fixed by #26698.

**Comment by JonLiu1993** [comment]
@fran6co, please fix the conflicting file, thanks.

**Comment by fran6co** [comment]
@JonLiu1993 done, but I don't know why it fails on uwp builds. The logs are a bit confusing to me, it says that it cascaded or something

**Comment by fran6co** [comment]
https://dev.azure.com/vcpkg/public/_build/results?buildId=78286&view=logs&j=afe306fb-88a0-5d5e-2934-71aa01507316&t=5029ab74-fefd-5c62-0657-5855530a064d&l=7171

**Comment by fran6co** [comment]
Sorted, srt doesn't support uwp

**Comment by JonLiu1993** [comment]
@fran6co, If the ci test failed error is not related to this pr, I will rerun ci, this is my error log, you can take a look

```
fatal: unable to access 'https://code.qt.io/qt/qtinterfaceframework.git/': transfer closed with outstanding read data remaining`
```

**Comment by fran6co** [comment]
It seems that everything is working now

**Review by JonLiu1993 — APPROVED** [review]

**Comment by JonLiu1993** [comment]
Feature `srt` tested successfully in the following triplet:
- x64-windows
- x64-windows-static

**Pull request merged**
