### PR TITLE
[gdal] Update to v3.5.2

### LINKED ISSUE #25941: Undefined reference to pcre2 with qtbase and gdal in combination
**Describe the bug**
When creating an application that links against qtbase and gdal, the resulting library failed to link with undefined reference to pcre symbols.

My understanding of the problem:

Both, qt and gdal cache the library in `PCRE2_LIBRARY`, but link against different versions of it:

- gdal `libpcre2-8.a`
- qt `libpcre2-16.a`

This leads to a race condition where the package that is found first will define which flavor of the pcre2 library is used, symbols from the second one are missing.

**Environment**
- OS: Linux (Fedora 35), MinGW, others untested
- Compiler: gcc12.1.1

**To Reproduce**
Create an application that links against `gdal` and `qtbase`.
Build and link.

**Expected behavior**
No linker errors

**Failure logs**
```
ogrsqlitevirtualogr.cpp:(.text+0xabd): undefined reference to `pcre2_compile_8'
/usr/bin/ld: ogrsqlitevirtualogr.cpp:(.text+0xad8): undefined reference to `pcre2_config_8'
/usr/bin/ld: ogrsqlitevirtualogr.cpp:(.text+0xb03): undefined reference to `pcre2_code_free_8'
/usr/bin/ld: ogrsqlitevirtualogr.cpp:(.text+0xb86): undefined reference to `pcre2_jit_compile_8'
/usr/bin/ld: ogrsqlitevirtualogr.cpp:(.text+0xba6): undefined reference to `pcre2_get_error_message_8'
/usr/bin/ld: ogrsqlitevirtualogr.cpp:(.text+0xbdf): undefined reference to `pcre2_code_free_8'
/usr/bin/ld: ogrsqlitevirtualogr.cpp:(.text+0xbfa): undefined reference to `pcre2_get_error_message_8'
/usr/bin/ld: vcpkg_installed/x64-linux/lib/libgdal.a(ogrsqlitevirtualogr.cpp.o): in function `OGRSQLiteREGEXPFunction(sqlite3_context*, int, sqlite3_value**)':
ogrsqlitevirtualogr.cpp:(.text+0xcac): undefined reference to `pcre2_match_data_create_from_pattern_8'
/usr/bin/ld: ogrsqlitevirtualogr.cpp:(.text+0xcdd): undefined reference to `pcre2_match_8'
/usr/bin/ld: vcpkg_installed/x64-linux/lib/libgdal.a(ogrsqlitevirtualogr.cpp.o): in function `OGRSQLiteExtensionData::~OGRSQLiteExtensionData()':
ogrsqlitevirtualogr.cpp:(.text+0x32ee): undefined reference to `pcre2_code_free_8'
```

**Possible solutions**

- Link gdal against pcre2-16
- Rename the variable names to `PCRE2-8_LIBRARY` and `PCRE2-16_LIBRARY` or similar

CC @Neumann-A @dg0yt

### PR DESCRIPTION
**Pull request by dg0yt**
- #### What does your PR fix?
  Updates GDAL. Removes upstreamed patch.
  Resolves #25941 (upstream change).

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  unchanged, no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  yes

### CODE REVIEW

**Comment by dg0yt** [comment]
The osg:arm64-windows error is unrelated. osg fails to find cmake package OpenEXR. Given a number of warnings, some of openexr's dependencies may need pkg-config/pkgconf. This problem could have been hidden by installation order in the recent openexr update.

**Review by JackBoosY — DISMISSED** [review]

**Comment by JonLiu1993** [comment]
@dg0yt , when I tested the features by command` ./vcpkg install gdal[*]:x86-windows` but failed,
I got this error, please take a look:
````
-- Could NOT find MSSQL_ODBC (missing: MSSQL_ODBC_LIBRARY MSSQL_ODBC_INCLUDE_DIR MSSQL_ODBC_VERSION) 
-- Could NOT find MySQL (missing: MYSQL_LIBRARY) 
CMake Error at cmake/helpers/CheckDependentLibraries.cmake:178 (message):
  Configured to use MYSQL, but not found
Call Stack (most recent call first):
  cmake/helpers/CheckDependentLibraries.cmake:260 (gdal_check_package)
  gdal.cmake:254 (include)
  CMakeLists.txt:218 (include)
````

**Comment by dg0yt** [comment]
@JonLiu1993 Please test again.

**Comment by JonLiu1993** [comment]
@dg0yt , when I tested the features by command ./vcpkg install gdal[*]:x86-windows but failed,
I got this error, please take a look:
````
-- Could NOT find MRSID (missing: MRSID_LIBRARY MRSID_INCLUDE_DIR) 
-- Could NOT find Armadillo (missing: ARMADILLO_INCLUDE_DIR) 
CMake Error at cmake/helpers/CheckDependentLibraries.cmake:178 (message):
  Configured to use CFITSIO, but not found
Call Stack (most recent call first):
  cmake/helpers/CheckDependentLibraries.cmake:601 (gdal_check_package)
  gdal.cmake:254 (include)
  CMakeLists.txt:218 (include)
````

**Comment by dg0yt** [comment]
@JonLiu1993 Please test again.

**Comment by JonLiu1993** [comment]
@dg0yt , when I tested the features by command ./vcpkg install gdal[*]:x86-windows but failed,
I got this error, please take a look:
```
F:\Feature-test\gdal\vcpkg\buildtrees\gdal\src\v3.5.2-f81c44ec59.clean\ogr\ogrsf_frmts\xls\ogrxlsdatasource.cpp(29): fatal error C1083: Cannot open include file: 'freexl.h': No such file or directory`
```

**Comment by dg0yt** [comment]
@JonLiu1993 Please test again.

**Comment by JonLiu1993** [comment]
@dg0yt , I tested the gdal:x86-windows and gdal:x64-windows features successfully,but the gdal:x64-windows-static triplet tested failed. this is error log< please take a look:
````
gdal.lib(LERC_band.cpp.obj) : error LNK2019: unresolved external symbol __imp_lerc_encodeForVersion referenced in function "enum CPLErr __cdecl GDAL_MRF::CompressLERC2(struct GDAL_MRF::buf_mgr &,struct GDAL_MRF::buf_mgr &,struct GDAL_MRF::ILImage const &,double,int)" (?CompressLERC2@GDAL_MRF@@YA?AW4CPLErr@@AEAUbuf_mgr@1@0AEBUILImage@1@NH@Z)
gdal.lib(LERC_band.cpp.obj) : error LNK2019: unresolved external symbol __imp_lerc_getBlobInfo referenced in function "protected: static struct CPLXMLNode * __cdecl GDAL_MRF::LERC_Band::GetMRFConfig(class GDALOpenInfo *)" (?GetMRFConfig@LERC_Band@GDAL_MRF@@KAPEAUCPLXMLNode@@PEAVGDALOpenInfo@@@Z)
gdal.lib(LERC_band.cpp.obj) : error LNK2019: unresolved external symbol __imp_lerc_decode referenced in function "protected: virtual enum CPLErr __cdecl GDAL_MRF::LERC_Band::Decompress(struct GDAL_MRF::buf_mgr &,struct GDAL_MRF::buf_mgr &)" (?Decompress@LERC_Band@GDAL_MRF@@MEAA?AW4CPLErr@@AEAUbuf_mgr@2@0@Z)
apps\gdalenhance.exe : fatal error LNK1120: 3 unresolved externals
[1125/1151] cmd.exe /C "cd . && F:\Feature-test\gdal\vcpkg\downloads\tools\cmake-3.24.0-windows\cmake-3.24.0-windows-i386\bin\cmake.exe -E vs_link_exe --intdir=apps\CMakeFiles\gdalinfo.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\mt.exe --manifests F:\Feature-test\gdal\vcpkg\buildtrees\gdal\src\v3.5.2-e616cd5f5b.clean\apps\longpathaware.manifest -- C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x64\link.exe  @CMakeFiles\gdalinfo.rsp  /out:apps\gdalinfo.exe /implib:apps\gdalinfo.lib /pdb:apps\gdalinfo.pdb /version:0.0 /machine:x64 /nologo /DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF   /subsystem:console wsetargv.obj  && cd ."
FAILED: apps/gdalinfo.exe 
````

**Comment by dg0yt** [comment]
@JonLiu1993 Fixed bug in port lerc.

**Comment by JonLiu1993** [comment]
> @JonLiu1993 Fixed bug in port lerc.

@dg0yt , I tested again and the error persists

**Comment by dg0yt** [comment]
> I tested again and the error persists

I will try to make a separate lerc update to 4.0. It will fix static builds, cf. https://github.com/Esri/lerc/commit/384465e65a8040b400cc9602b0a113886be3f173

**Comment by dg0yt** [comment]
Stop pushing non-sense to my branch. CI for x64-linux is broken.

**Pull request merged**
