### PR TITLE
Update cmake to 3.25.1

### PR DESCRIPTION
**Pull request by autoantwort**
Changes from #28126 but triggers a new pipeline run

### CODE REVIEW

**Comment by Neumann-A** [comment]
Probably won't be green on first run so you need to trigger a second one shortly after the first finished.  
But I assume you know how vcpkg CI works and why it will be green in the second run ;)

**Comment by Osyotr** [comment]
> But I assume you know how vcpkg CI works and why it will be green in the second run ;)

Please tell me :)

**Comment by Neumann-A** [comment]
> Please tell me :)

triggering a rebuild will most likely only rebuild the failing ports and as such stuff like file conflicts or non declared optional dependencies will no longer fail CI due to the partial rebuild.

**Comment by autoantwort** [comment]
Depends on #28485

**Comment by autoantwort** [comment]
I don't get why libphonenumber does not find protobuf-lite. It works locally. In the ci the protobuf-lite file is there and it already finds the header. I don't see a difference between the ci and my local setup.

**Comment by FrankXie05** [comment]
Re-run ci to get the latest error messages. :)

**Comment by dg0yt** [comment]
> I don't get why libphonenumber does not find protobuf-lite. It works locally. In the ci the protobuf-lite file is there and it already finds the header. I don't see a difference between the ci and my local setup.

Check the names:
libphonenumber searches for `protobuf` which means `protobuf.lib` for MSVC.
protobuf installs  `libprotobuf.lib` and `libprotobufd.lib`.

**Comment by autoantwort** [comment]
Depends on https://github.com/microsoft/vcpkg/pull/28748

**Comment by autoantwort** [comment]
@FrankXie05 The last failure is a baseline regression. So maybe already add the review label?

**Comment by FrankXie05** [comment]
Merge master for ci baseline regression.

**Comment by Neumann-A** [comment]
@vicroms it would have been good if this pr would have been merged together with vcpkg_find_acquire_program pr since it would have halved the number of world rebuilds.
The only regression here was/is a know baseline regression which is also a leaf in the dependency tree.
How about adding a tag: Has/Shows/Discovers: baseline regression to not stop PRs from being looked at and being tagged as reviewed?

**Review by vicroms — DISMISSED** [review]

**Comment by autoantwort** [comment]
@FrankXie05 The baseline regression is still there...

**Comment by FrankXie05** [comment]
@autoantwort we will solve this regression today.  :)

**Comment by vicroms** [comment]
I'm ok with merging even with the existing regression on `zeroc-ice`, it will be addressed in another PR.

**Review by FrankXie05 — DISMISSED** [review]

**Comment by FrankXie05** [comment]
> I'm ok with merging even with the existing regression on `zeroc-ice`, it will be addressed in another PR.

LGTM, waiting for the ci osx check to pass.

**Pull request merged**
