### PR TITLE
[bullet3] Add extras feature

### PR DESCRIPTION
**Pull request by NancyLi1013**
Add new feature `extras ` in order to build `BulletRobotics `.

Related issue #10808 

Note: All features have passed in the following triplets:
- x86-windows
- x64-windows
- x64-windows-static

### CODE REVIEW

**Comment by PhoebeHui** [comment]
@NancyLi1013, could you test the feature with linux triplets?

**Comment by NancyLi1013** [comment]
Have tested the features on x64-linux triplet and all features have passed.
Since some functions in `extras` feature depend on `example`. 
Need to do further investigation about this.

**Comment by BillyONeal** [comment]
@NancyLi1013 What upstream changes are we waiting on? Are you still interested in pursuing these changes?

**Comment by NancyLi1013** [comment]
@BillyONeal  Thanks for paying attention to this PR.

Since upstream doesn't support dynamic build on Windows, which causes the linker error like this:

```
>bullet3Project.obj : error LNK2019: unresolved external symbol "public: __cdecl b3RobotSimulatorClientAPI_NoGUI::b3RobotSimulatorClientAPI_NoGUI(void)" (??0b3RobotSimulatorClientAPI_NoGUI@@QEAA@XZ) referenced in function main
1>bullet3Project.obj : error LNK2019: unresolved external symbol "public: virtual __cdecl b3RobotSimulatorClientAPI_NoGUI::~b3RobotSimulatorClientAPI_NoGUI(void)" (??1b3RobotSimulatorClientAPI_NoGUI@@UEAA@XZ) referenced in function main
1>C:\Users\v-ruil\source\repos\bullet3Project\x64\Debug\bullet3Project.exe : fatal error LNK1120: 2 unresolved externals
```

Please see upstream issue https://github.com/bulletphysics/bullet3/issues/1794 and PR https://github.com/bulletphysics/bullet3/pull/2389.

For the details, please https://github.com/microsoft/vcpkg/issues/10808#issuecomment-613960830 and https://github.com/microsoft/vcpkg/issues/10808#issuecomment-669722796.

**Comment by BillyONeal** [comment]
@NancyLi1013 Thanks!

**Comment by NancyLi1013** [comment]
Closing this PR for now since it depends on upstream changes.

**Pull request closed without merging**
