### PR TITLE
[libpng] Fix apng.patch failed to get after using --clean-after-build option

### PR DESCRIPTION
**Pull request by NancyLi1013**
When using --clean -after-build option to build the port, the source codes in buildtree will be removed. So when we build with apng feature , it will post the error info:
```
CMake Error at scripts/cmake/vcpkg_extract_source_archive_ex.cmake:97 (file):
  file SHA512 failed to read file
  "F:/vcpkg/buildtrees/libpng/src/libpng-1.6.37-apng.patch": No such file or
  directory
Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:139 (vcpkg_extract_source_archive_ex)
  ports/libpng/portfile.cmake:30 (vcpkg_from_github)
  scripts/ports.cmake:90 (include)
```
So I download this patch and put it in _ports/libpng_ directory to fix this issue.

Related issue #9849 

Note: Feature has been passed in the following triplets:
- x86-windows
- x64-windows
- arm-uwp

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Review by ras0219-msft — CHANGES_REQUESTED** [review]
This patch is too large and potentially license encumbered for us to check in.

Instead, we should use
```
vcpkg_download_distfile()
vcpkg_extract_archive_ex()
```
before the `vcpkg_from_github()` call.

**Comment by NancyLi1013** [comment]
Hi @ras0219-msft 

thanks for your review and suggestion.

I try to use `vcpkg_extract_source_archive_ex()` to extract this patch archive. But it seems that it cannot be extracted successfully.
It shows the following errors:
```
CMake Error: Problem with archive_read_open_file(): Unrecognized archive format
CMake Error: Problem extracting tar: F:/vcpkg/downloads/libpng-1.6.37-apng.patch.gz
```

**Comment by strega-nil** [comment]
This should be solved by adding `vcpkg_extract_source_file` function which doesn't extract an archive, but a single file (since this is a gzipped text file), I believe.

**Comment by NancyLi1013** [comment]
@strega-nil 
Thanks for your suggestion. I will try to update in this way.

**Comment by strega-nil** [comment]
@NancyLi1013 are you still interested in fixing this issue?

**Comment by NancyLi1013** [comment]
@strega-nil 
Thanks for your kindly reminder.
Since this function `vcpkg_extract_source_file() ` is not implemented yet. And I 'm not familiar with this. So I cannot make progress on this PR. I have asked for help from Jack. After this function is added, I will continue on this PR.

**Comment by NancyLi1013** [comment]
Hi @strega-nil 

This issue seems to be resolved now. I try to rebuild this on my local and I cannot reproduce it now.
So this PR is not needed any more. I 'm closing it.

**Pull request closed without merging**
