### PR TITLE
[osg] Change OPENGL_PROFILE to GL2

### LINKED ISSUE #25705: [osg] OSG examples no longer work
**Describe the bug**
The examples that come with OSG no longer work.  The issue appears related to textures.

The examples worked in vcpkg 2022.02.02. 
The examples do NOT work in vcpkg 2022.05.10.
The examples do NOT work in vcpkg 2022.06.16.1.

**Environment**
- OS: Windows 11
- Compiler: Visual Studio revision 17.2.5

**To Reproduce**
1.  `md ~/desktop/repro`
2.  `cd ~/desktop/repro`
4. `git clone https://github.com/openscenegraph/OpenSceneGraph-Data.git`
5. `$env:OSG_FILE_PATH="$home/desktop/repro/OpenSceneGraph-Data"`
6. `git clone https://github.com/microsoft/vcpkg.git`
7. `.\vcpkg\bootstrap-vcpkg.bat`
8. `.\vcpkg\vcpkg.exe --triplet=x64-windows --recurse install osg[plugins,examples]`
9.  `$env:OSGNOTIFYLEVEL="DEBUG_FP"`
10. `cd .\vcpkg\installed\x64-windows\bin\`
11. `..\tools\osg\osgtexture1D.exe`

You will see a black truck...
image
In the console, you will see lots of warnings/errors...
```
...
Warning: TexGen::apply(State&) - not supported.
Warning: detected OpenGL error 'invalid enumerant' after applying GLMode 0xc60
Warning: detected OpenGL error 'invalid enumerant' after applying GLMode 0xde0
Warning: detected OpenGL error 'invalid enumerant' after applying GLMode 0xb50
Warning: Material::apply(State&) - not supported.
Warning: detected OpenGL error 'invalid enumerant' after applying GLMode 0xb50
Warning: detected OpenGL error 'invalid enumerant' after applying GLMode 0xc60
Warning: detected OpenGL error 'invalid enumerant' after applying GLMode 0xc60
cull()g: detected OpenGL error 'invalid enumerant' after applying GLMode 0xde0
cull()
Warning: Material::apply(State&) - not supported.
Warning: Material::apply(State&) - not supported.
...
```

**Expected behavior**
If you build the latest version of OSG, you see the proper behavior.

You will see a colored truck
image

The console does not have any warnings/errors...
```
...
end draw() 0000021A36FE49C0
cull() got SceneView 0000021A37024D20
end cull() 0000021A36FE49C0
draw() 0000021A36FE49C0
draw() got SceneView 0000021A37024D20
end draw() 0000021A36FE49C0
...
```

**Failure logs**
N/A

**Additional context**
The version of OSG that vcpkg gets: 
tag OpenSceneGraph-3.6.5
**January 31, 2020**
https://github.com/openscenegraph/OpenSceneGraph/tree/OpenSceneGraph-3.6.5

The latest version of OSG
master branch (no tags that I could find)
**April 7, 2022**
https://github.com/openscenegraph/OpenSceneGraph/tree/master

I believe the fix for this issue is to update [osg/port.cmake](https://github.com/microsoft/vcpkg/blob/master/ports/osg/portfile.cmake)  to use the latest OSG update to master.

### PR DESCRIPTION
**Pull request by LilyWangLL**
**Describe the pull request**

- #### What does your PR fix?
  Fixes #25705, change `OPENGL_PROFILE` to `GL2` to keep this option is same with source. The upstream default value is `GL2`.
  The related source codes in _[SOURCE_PATH]/CMakeLists.txt_
```
# Map the OPENGL_PROFILE to OSG_GL*_AVAILABLE settings
SET(OPENGL_PROFILE "GL2" CACHE STRING "OpenGL Profile to use, choose from GL1, GL2, GL3, GLES1, GLES2, GLES3")

IF ((OPENGL_PROFILE STREQUAL "GL1") OR (OPENGL_PROFILE STREQUAL "GL2"))
    OPTION(OSG_GL1_AVAILABLE "Set to OFF to disable use of OpenGL 1.x functions library." ON )
ELSE()
    OPTION(OSG_GL1_AVAILABLE "Set to OFF to disable use of OpenGL 1.x functions library." OFF )
ENDIF()

IF ((OPENGL_PROFILE STREQUAL "GL2"))
    OPTION(OSG_GL2_AVAILABLE "Set to OFF to disable use of OpenGL 2.x functions library." ON )
ELSE()
    OPTION(OSG_GL2_AVAILABLE "Set to OFF to disable use of OpenGL 2.x functions library." OFF )
ENDIF()

IF ((OPENGL_PROFILE STREQUAL "GL3") OR (OPENGL_PROFILE STREQUAL "GLCORE"))
    OPTION(OSG_GL3_AVAILABLE "Set to OFF to disable use of OpenGL 3.x functions library." ON )
    if(APPLE)
        add_definitions(-DGL_DO_NOT_WARN_IF_MULTI_GL_VERSION_HEADERS_INCLUDED)
    endif()
ELSE()
    OPTION(OSG_GL3_AVAILABLE "Set to OFF to disable use of OpenGL 3.x functions library." OFF )
ENDIF()

IF ((OPENGL_PROFILE STREQUAL "GLES1"))
    OPTION(OSG_GLES1_AVAILABLE "Set to OFF to disable use of OpenGL ES 1.x functions library." ON )
ELSE()
    OPTION(OSG_GLES1_AVAILABLE "Set to OFF to disable use of OpenGL ES 1.x functions library." OFF )
ENDIF()

IF ((OPENGL_PROFILE STREQUAL "GLES2"))
    OPTION(OSG_GLES2_AVAILABLE "Set to OFF to disable use of OpenGL ES 2.x functions library." ON )
ELSEIF ((OPENGL_PROFILE STREQUAL "GLES3"))
    OPTION(OSG_GLES3_AVAILABLE "Set to OFF to disable use of OpenGL ES 3.x functions library." ON )
ELSEIF ((OPENGL_PROFILE STREQUAL "GLES2+GLES3"))
    OPTION(OSG_GLES2_AVAILABLE "Set to OFF to disable use of OpenGL ES 2.x functions library." ON )
    OPTION(OSG_GLES3_AVAILABLE "Set to OFF to disable use of OpenGL ES 3.x functions library." ON )
ELSE()
    OPTION(OSG_GLES2_AVAILABLE "Set to OFF to disable use of OpenGL ES 2.x functions library." OFF )
    OPTION(OSG_GLES3_AVAILABLE "Set to OFF to disable use of OpenGL ES 3.x functions library." OFF )
ENDIF()
```

### CODE REVIEW

**Comment by Osyotr** [comment]
Pinging @jasonbeverage so that he makes relevant changes in osgEarth build system.

**Comment by dg0yt** [comment]
You must also update the `usage` file.

**Comment by jasonbeverage** [comment]
If you want to merge this as is for now I think it would be fine.  osgEarth would require a special triplet to be made if you wanted to use osgEarth specifying the OPENGL_PROFILE=GL3 setting.  OpenSceneGraph doesn't do a good job of working out of the box in OpenGL 3 mode and really requires you to bring your own shaders so the examples don't work.

**Comment by Osyotr** [comment]
@LilyWangLL please undraft this PR.

**Review by Cheney-W — APPROVED** [review]

**Pull request merged**
