### PR TITLE
vcpkg: fix toolchain to correctly set the CMAKE_SYSTEM_PROCESSOR vari…

### PR DESCRIPTION
**Pull request by studiofuga**
…able

Some build fails because cmake expects the CMAKE_SYSTEM_PROCESSOR to
be correctly set with the system processor flavour.
scripts/toolchains/linux.cmake fails to set it, while other
toolchains correctly set it (see osx.cmake) for example.
This patch fix this bug.

### CODE REVIEW

**Comment by LarryIII** [comment]
I am seeing new build failures on the following ports with this PR. Let me know if you need build log.
``` 
Processing x64-linux                      579 vs 585
     caffe2                        **regression**                Fail vs Pass
     forest                        **regression**                Fail vs Pass
     libuuid                       **regression**                Fail vs Pass
     sobjectizer                   **regression**                Fail vs Pass
```

**Comment by Rastaban** [comment]
This would probably fix issues currently seen on #4635

**Comment by vicroms** [comment]
I had an open PR to address this same issue, but it got closed when we deleted all the branches on this repo.

I'll resubmit it once I have more time to keep working on the issue.

https://github.com/Microsoft/vcpkg/pull/5697

**Comment by vicroms** [comment]
Fixed in #6872

**Pull request closed without merging**
