### PR TITLE
[avro-cpp] New port

### PR DESCRIPTION
**Pull request by alexander-smyslov**

### CODE REVIEW

**Comment by alexander-smyslov** [comment]
I have no idea how to separate static build from normal -  build produce avrocpp_s.lib and avrocpp.lib at once

**Comment by cenit** [comment]
At least remove the unnecessary one depending from the vcpkg_library_linkage...

**Comment by vicroms** [comment]
@alexander-smyslov 

Thanks for the PR!

> I have no idea how to separate static build from normal -  build produce avrocpp_s.lib and avrocpp.lib at once

Here are the changes you would need to make to `lang/c++/CMakeLists.txt` to produce a single library:

#### 1) Make the build script respect the `BUILD_SHARED_LIBS` variable to create a single library for the correct configuration.

Remove these lines:
```
add_library(avrocpp SHARED ${AVRO_SOURCE_FILES}
add_library(avrocpp_s STATIC ${AVRO_SOURCE_FILES}
```

And replace with:

```
add_library(avrocpp ${AVRO_SOURCE_FILES})
```

#### 2) Fix references to `avrocpp_s`. This means branching the properties added to the `avrocpp` target based on the configuration being built, e.g.:

```
set_property(TARGET avrocpp APPEND PROPERTY COMPILE_DEFINITIONS AVRO_DYN_LINK)
set_property(TARGET avrocpp_s APPEND PROPERTY COMPILE_DEFINITIONS AVRO_SOURCE)
```

Should become

```
if (BUILD_SHARED_LIBS)
  set_property(TARGET avrocpp 
    APPEND PROPERTY COMPILE_DEFINITIONS AVRO_DYN_LINK)
else()
  set_property(TARGET avrocpp 
    APPEND PROPERTY COMPILE_DEFINITIONS AVRO_SOURCE)
endif()
```

#### 3) Export only a single target (remove `avrocpp_s` which no longer exists).

```
install (TARGETS avrocpp avrocpp_s
    LIBRARY DESTINATION lib
    ARCHIVE DESTINATION lib
    RUNTIME DESTINATION lib)
```

#### 4) Finally, create a `vcpkg-cmake-wrapper.cmake` file in the port directory. 

The wrapper should be installed by the portfile in `share/avro-cpp` and it should look similar to https://github.com/microsoft/vcpkg/blob/master/ports/czmq/vcpkg-cmake-wrapper.cmake. The purpose is to provide the missing target name `avrocpp_s`, that might be expected by some users of the library.

---

There might be some things I'm missing, as I just took a brief look at the build system for `avro`, feel free to get back with questions if you have any.

**Comment by LilyWangL** [comment]
Pinging @alexander-smyslov for response. Is work still being done for this PR?

**Comment by LilyWangL** [comment]
Closing this PR since it seems that no progress is being made. Please reopen if work is still being done.

**Pull request closed without merging**
