### PR TITLE
[pdcurses] Revise portfile

### PR DESCRIPTION
**Pull request by dg0yt**
- #### What does your PR fix?  
  Use `vcpkg_build_nmake` instead of custom nmake scripting. The maintainer function takes care of triplet and build type flags, allowing to enable static linkage.
  Add install commands to `makefile.vc`.
  Create `pdcurses.pdb` instead of `none.pdb`.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  `windows & !uwp & !mingw`, yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  yes

### CODE REVIEW

**Comment by dg0yt** [comment]
This PR would benefit from #22095.

**Review by LilyWangLL — APPROVED** [review]

**Review by JackBoosY — APPROVED** [review]
Thanks for fixing this!

**Comment by BillyONeal** [comment]
> This PR would benefit from #22095.

Since that one is now merged do you want to respond to that or merge this as-is?

**Review by BillyONeal — APPROVED** [review]

**Comment by dg0yt** [comment]
Let me update it. I can edit the patch directly (later tonight).

**Comment by dg0yt** [comment]
Ready.

**Comment by BillyONeal** [comment]
Awesome, thank you!

**Pull request merged**
