### PR TITLE
[pdal] Prepare for nlohmann-json 3.11.x

### PR DESCRIPTION
**Pull request by falbrechtskirchinger**
In nlohmann-json 3.11.0, json_fwd.hpp changed.
Replace PDAL's internal copy of the file as part of the de-vendoring process.

This PR is a requirement for #26124 to move forward.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  No change, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

### CODE REVIEW

**Comment by Osyotr** [comment]
There's no mention of nlohmann-json in pdal's `vcpkg.json`

**Comment by falbrechtskirchinger** [comment]
I'm confused about that as well, but it clearly references `nlohmann/json.hpp`. :man_shrugging:

And `nlohmann-json` (3.11.x) fails CI as a consequence.

**Comment by falbrechtskirchinger** [comment]
I've no experience with `vcpkg` and don't use it myself, but I do get the impression there's more wrong with this port.

* Using `"${CURRENT_INSTALLED_DIR}/include/nlohmann/json.hpp"` without `nlohmann-json` being listed as a dependency.
* Using `"${CURRENT_INSTALLED_DIR}/include/nanoflann.hpp"` without `nanoflann` being listed as a dependency.
* Replacing the bundled single-header `json.hpp` with the multi-header version.

I could go on but let's start here.

**Comment by Osyotr** [comment]
> Using "${CURRENT_INSTALLED_DIR}/include/nlohmann/json.hpp" without nlohmann-json being listed as a dependency.
Using "${CURRENT_INSTALLED_DIR}/include/nanoflann.hpp" without nanoflann being listed as a dependency.

nlohman-json dependency is implicitly satisfied: (pdal -> libgeotiff -> nlohman-json). But it should be explicit.
nanoflann is listed as a dependency of pdal https://github.com/microsoft/vcpkg/blob/39dbc6c45ba9493f1c1b59496d619e0d08f20436/ports/pdal/vcpkg.json#L20

**Comment by falbrechtskirchinger** [comment]
> nanoflann is listed as a dependency of pdal

Right. I must have been looking at the wrong file. Thanks for clarifying, I'll add `nlohmann-json` explicitly.

I'm not a fan of conflating the bundled single-header `json.hpp` with the installed multi-header `json.hpp`, but it seems to work.
I believe I understand now why it works as well and that makes my other concerns moot.

**Review by Adela0814 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks!

**Pull request merged**
