### PR TITLE
[bext-sml] Adding new port of boost::sml

### PR DESCRIPTION
**Pull request by misirlou-tg**
Adding new port of boost::sml

- #### What does your PR fix?  
  #20799 

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Review by yurybura — CHANGES_REQUESTED** [review]
I think `boost-ext-sml` is more clear name for this port.

**Review by PhoebeHui — APPROVED** [review]

**Comment by yurybura** [comment]
> I think the name is fine, See [#16302 (review)](https://github.com/microsoft/vcpkg/pull/16302#pullrequestreview-594586277)

I don't understand from the comment why `boost-ext` library shouldn't contain boost in the name.

**Comment by BillyONeal** [comment]
> > I think the name is fine, See [#16302 (review)](https://github.com/microsoft/vcpkg/pull/16302#pullrequestreview-594586277)
> 
> I don't understand from the comment why `boost-ext` library shouldn't contain boost in the name.

This library is not in boost, so it should not use boost- as a prefix. Just because the library wants to claim that it's part of boost, it isn't part of boost until the boost maintainers have accepted it.

**Comment by yurybura** [comment]
> > > I think the name is fine, See [#16302 (review)](https://github.com/microsoft/vcpkg/pull/16302#pullrequestreview-594586277)
> > 
> > 
> > I don't understand from the comment why `boost-ext` library shouldn't contain boost in the name.
> 
> This library is not in boost, so it should not use boost- as a prefix. Just because the library wants to claim that it's part of boost, it isn't part of boost until the boost maintainers have accepted it.

In source code everybody must use `boost`:
```cpp
#include <boost/di.hpp>
#include <boost/sml.hpp>
#include <boost/ut.hpp>
```
Why in the package name `boost` is forbidden? IMHO `bext` is awful prefix.

**Pull request merged**
