### PR TITLE
[vcpkg-cmake-config] Fix fixup of `)` paths

### PR DESCRIPTION
**Pull request by dg0yt**
Cherry-picked from https://github.com/microsoft/vcpkg/pull/38847:

Fix processing of `INTERFACE_LINK_LIBS` when it contain `)` inside `"`, e.g. for  
`C:/Program Files (x86)/Windows Kits/10/Lib/10.0.22621.0/um/x64/User32.Lib`  
created by `pkg_check_modules` from `-luser32` as found in icu pc files.

Without the fix, the property is not processed at all, pulling release libs into debug builds.

### CODE REVIEW

**Comment by Neumann-A** [comment]
`C:/Program Files (x86)/Windows Kits/10/Lib/10.0.22621.0/um/x64/` needs to be removed

**Comment by dg0yt** [comment]
> `C:/Program Files (x86)/Windows Kits/10/Lib/10.0.22621.0/um/x64/` needs to be removed

Actually this PR deals only with completely broken results due to `)`, not with removing SDL paths. It fixes immediate regressions in vcpkg CI as observed in #33847.

https://github.com/microsoft/vcpkg/labels/category%3Aport-bug

**Comment by dg0yt** [comment]
This PR changes CMake config, typically fixing the `debug` variant. Why does the `angle` build always get stuck in the windows release build phase?

**Comment by talregev** [comment]
@dg0yt Please try to merge the latest dev.
@BillyONeal I also see the ci get stuck on that changes. Can you take a look?

**Comment by dg0yt** [comment]
> Please try to merge the latest dev. 

Pointless. Vcpkg CI build merges with `master`.

> AT BillyONeal I also see the ci get stuck on that changes. Can you take a look?

I don't need a proxy in my vcpkg contacts.

FTR it is not the build step which is stuck but the cmake config fixup which follows. Which is the code changed by my PR.

**Comment by talregev** [comment]
In my opinion the ci stuck not from your code change.
I already see the ci stuck, usually trying to build heavy things, or it needs to compile many ports. It also happened on osx many times.

And we already have a ci problem so I am asking to check that.

**Comment by dg0yt** [comment]
Regular expression woes. Escaped double quotes inside quotes in `INTERFACE_COMPILE_DEFINITIONS` here, make CMake hang in the `while` expression. Reproducer:
~~~cmake
set(contents [[
# Generated CMake target import file.
add_library(unofficial::angle::libANGLE STATIC IMPORTED)
set_target_properties(unofficial::angle::libANGLE PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "ANGLE_ENABLE_ESSL;ANGLE_ENABLE_GLSL;ANGLE_CAPTURE_ENABLED=0;GL_APICALL=;GL_API=;NOMINMAX;ANGLE_ENABLE_D3D11;ANGLE_ENABLE_HLSL;ANGLE_PRELOADED_D3DCOMPILER_MODULE_NAMES={ \"d3dcompiler_47.dll\", \"d3dcompiler_46.dll\", \"d3dcompiler_43.dll\" };ANGLE_ENABLE_D3D9;ANGLE_ENABLE_D3D11_COMPOSITOR_NATIVE_WINDOW;ANGLE_ENABLE_GLSL;ANGLE_ENABLE_OPENGL;ANGLE_ENABLE_GL_DESKTOP_BACKEND;KHRONOS_STATIC"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:ZLIB::ZLIB>"
)
]])
while(contents MATCHES "set_target_properties[(]([^ \$]*) PROPERTIES([^\")]+| \"[^\"]*\")+[)]")
    message(STATUS "FOUND set_target_properties")
endwhile()
message(STATUS "${contents}")
~~~

The function is already only touching files which can be assumed to be generated by CMake. Maybe we should simply use this to more closely match on an `INTERFACE_LINK_LIBRARIES "..."\n` line.

**Comment by talregev** [comment]
@FrankXie05 can you take a look?

**Review by FrankXie05 — APPROVED** [review]

**Pull request merged**
