### PR TITLE
[vcpkg] Upgrade GN dependency

### PR DESCRIPTION
**Pull request by omartijn**
Some packages cannot be upgraded without upgrading GN since they use
syntax introduced in later versions of GN. One such example is crashpad.

**Describe the pull request**

- #### What does your PR fix?  
Upgrades GN so packages using it can be upgraded

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
No changes.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
Not applicable

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by omartijn** [comment]
Note: simage fails due to using deprecated type names exported from libtiff.
See http://www.simplesystems.org/libtiff/v4.3.0.html

These build failures have nothing to do with this PR, but are introduced when the libtiff port was updated to 4.3.0.

**Comment by dg0yt** [comment]
> Note: simage fails due to using deprecated type names exported from libtiff.
> See http://www.simplesystems.org/libtiff/v4.3.0.html
> 
> These build failures have nothing to do with this PR, but are introduced when the libtiff port was updated to 4.3.0.

These build failures have nothing to do with this PR, but also aren't an issue of port tiff: 
**simage for windows triplets does not depend on tiff** (and some other ports) so it is no must not use them. That's why it was not covered in CI for port tiff.

**Comment by omartijn** [comment]
> These build failures have nothing to do with this PR, but also aren't an issue of port tiff:
> **simage for windows triplets does not depend on tiff** (and some other ports) so it is no must not use them. That's why it was not covered in CI for port tiff.

And yet the error messages clearly indicate they're happening due to using deprecated symbols from libtiff:

`     4>D:\buildtrees\simage\src\mage-1.8.0-17f988a113.clean\src\simage_tiff.c(88,18): error C4996: 'uint16': libtiff type deprecated; please use corresponding C99 stdint.h type [D:\buildtrees\simage\arm-uwp-dbg\simage.vcxproj]`

So it seems there is a combination of issues:

- for whatever reason vcpkg pulls in an incorrect dependency
- the `simage` library is misconfigured to use it
- `simage` is outdated and should probably be fixed
- deprecations are treated as errors

**Comment by JackBoosY** [comment]
Any progress here?
We wish to replace `vcpkg_*_gn` with `vcpkg_*_ninja` in the future.

**Comment by omartijn** [comment]
No progress, unfortunately. As you might see from the CI, any change here seems to fail some unrelated packages. I haven't had the time to figure this out. If you want to get rid of all the `vcpkg_*_gn` functions, I'd say go for it, though how you plan to do this, I don't know. AFAIK many google projects don't come with Ninja files, but you have to first use gn to generate the ninja files.

**Comment by JackBoosY** [comment]
Most of the regressions are unrelated, we just need to focus to the `v8` one.

**Comment by JackBoosY** [comment]
When building `chromium-base`:x64-windows-static:
```
ERROR at //build/config/BUILDCONFIG.gn:401:1: Unknown function.
set_sources_assignment_filter(sources_assignment_filter)
^----------------------------
```

**Comment by JackBoosY** [comment]
Please get failure logs [here](https://dev.azure.com/vcpkg/public/_build/results?buildId=61204&view=artifacts&pathAsName=false&type=publishedArtifacts).

**Comment by JackBoosY** [comment]
Ping for response.

**Comment by JackBoosY** [comment]
Closing this PR since it seems that no progress is being made. Please reopen if work is still being done.

**Pull request closed without merging**
