### PR TITLE
[openxr-loader] Initial port

### PR DESCRIPTION
**Pull request by jherico**
A Khronos released SDK, the OpenXR loader is similar in function to the Vulkan loader, but currently is designed to be client built rather than installed like the Vulkan SDK.  This PR adds support in vcpkg.

### CODE REVIEW

**Comment by NancyLi1013** [comment]
Hi @jherico, thanks for your new port. I see the test results from the current CI system that the port failed on all triplets. Please refer to the following attachment.
[failureLogs.zip](https://github.com/microsoft/vcpkg/files/3155723/failureLogs.zip)

**Comment by jherico** [comment]
Whoops... looks like there's a build-time python3 dependency I didn't notice since I already have Python3 installed locally.

**Comment by NancyLi1013** [comment]
@jherico, I checked the test results again from the current CI system after you added the python3 dependency commit. The port failed on all triplets. Please take a look at the failure log.
[failureLogs_latest.zip](https://github.com/microsoft/vcpkg/files/3160067/failureLogs_latest.zip)

**Comment by jherico** [comment]
Thanks.  Some of the errors seem to be originating from this error inside `generator.py`..

> TypeError: argument should be string, bytes or integer, not WindowsPath

Investigation suggests that this is an error that only occurs on Python versions less than 3.6.  I'll investigate to see what vcpkg fetches when a python build-time dependency is declared.

The linux build on the other hand is failing because of this:

> Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)

I encountered this when I was doing my docker build, which is why I had to add it in the config, but on examining some of the other ports I'm guessing pkg-config isn't a part of the CI build environment for linux based triplets.  

I'll investigate further for solutions.  thanks for the feedback.

**Comment by Rastaban** [comment]
It looks like it uses Python 3.5.4 on windows see [vcpkg_find_acquire_program](https://github.com/Microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_find_acquire_program.cmake).  Maybe it is time to update to the latest version.

**Comment by Rastaban** [comment]
Updating Python3 in #6383

**Comment by jherico** [comment]
I tried applying this change locallly and the build still failed.  The build system includes it's own python modules which need to be found by the python scripts and it's using the `PYTHONPATH` variable to ensure they're included.

However, the embedded python version used by vcpkg explicitly ignores `PYTHONPATH` in order to ensure total isolation from the host system.  I'm looking into the python docs to figure out what I need to change in the OpenXR build process to make it work with embedded python.

**Comment by jherico** [comment]
OK, I've added two patch files.  

The first modifies the executed python scripts to explicitly add the required library paths to `sys.paths` rather than relying on the PYTHONPATH environment variable.  That resolves the issue with using embedded.

The second modifies the `presentation.cmake` file used on Linux to hard-code the libraries needed rather than relying on pkg-config.  This isn't actually the best approach.  It appears the linkage information here is only used building the tests, which I've explicitly disabled for the vcpkg build.  However, I think the proper fix here is to submit a PR upstream that makes the `pkg-config`  usage conditional on the value of BUILD_TESTS.  I've created that PR [here](https://github.com/KhronosGroup/OpenXR-SDK/pull/44/files) and will retain this patch in the meantime.

**Comment by NancyLi1013** [comment]
New test results from current CI system:

|x64-windows|master| test |notes
|-----------|------|------|-----
|openxr     |      |Fail  |New Port

|x64-windows-static|master| test |notes
|------------------|------|------|-----
|openxr            |      |Fail  |New Port

|x64-osx|master| test |notes
|-------|------|------|-----
|openxr |      |Fail  |New Port

|arm64-windows|master| test |notes
|-------------|------|------|-----
|openxr       |      |Fail  |New Port

|x86-windows|master| test |notes
|-----------|------|------|-----
|openxr     |      |Fail  |New Port

|x64-linux|master| test |notes
|---------|------|------|-----
|openxr   |      |Pass  |New Port

|x64-uwp|master| test |notes
|-------|------|------|-----
|openxr |      |Fail  |New Port

|arm-uwp|master| test |notes
|-------|------|------|-----
|openxr |      |Fail  |New Port

[failureLogs.zip](https://github.com/microsoft/vcpkg/files/3186509/failureLogs.zip)

**Comment by jherico** [comment]
The failures are still all caused by the embedded python being less than 3.6.  However, I've added a patch file that should hopefully resolve this pending #6383

**Comment by brycehutchings** [comment]
The name "openxr" seems a bit too broad. Would "openxr-loader" be more appropriate?

**Comment by jherico** [comment]
@brycehutchings agreed, renamed.

**Comment by vicroms** [comment]
@jherico 

The port fails to build on ARM and UWP, I suppose these failures were expected (am I right?) and I've added some explicit failure messages. If not, I'm OK with merging this PR as an initial version and patching support for the remaining platforms in a different pull request.

**Comment by jherico** [comment]
Sounds good

**Comment by vicroms** [comment]
Thanks for the PR!

**Pull request merged**
