### PR TITLE
[OpenCV2] add library for projects that require the C API

### PR DESCRIPTION
**Pull request by cenit**
as per title, I propose the inclusion of the older OpenCV 2, guarded with an error like MySQL/MariaDB, since it is necessary to build projects that still use the C API (abandoned/broken in OpenCV3). For example, it is necessary to build YOLO on Windows ;)

### CODE REVIEW

**Comment by cenit** [comment]
I did another commit, to fix building on macOS (I hope it fixes also Ubuntu, still not tested). Since `vcpkg` is now cross-platform, I hope it is better now 🤓

**Comment by cenit** [comment]
I tested building also on Ubuntu and it worked. Added a small notice (comment) at the beginning of the port file to explain pre-requisites.

**Comment by cenit** [comment]
As a side note, I tried building also on x86-windows but I got a failure when linking with OpenGL32.lib, with the linker complaining that it couldn't solve `_imp_wglGetProcAddress` symbol...

**Comment by cenit** [comment]
I think that this port is in a good shape to be at least tried by someone, if interested @ras0219-msft @UnaNancyOwen @patrikhuber @jasjuang

**Comment by patrikhuber** [comment]
@cenit Thanks, it might become useful some day (as you mentioned... YOLO & stuff...), but for now I long moved to OpenCV3 (and probably 4 soon) for my own projects :-)

**Comment by cenit** [comment]
closed because there's not enough interest and it would be difficult to keep tested (vcpkg discourages not using the latest version by design)

**Pull request closed without merging**
