### PR TITLE
adding meson-build to the linux VM provisioning script

### PR DESCRIPTION
**Pull request by marzer**
**This PR is an exact replay of https://github.com/microsoft/vcpkg/pull/12224, but from a branch other than master. See the discussion on that PR for context etc.**

A number of minor things relating to the use of the meson build system:
- Adds a step to the x64-linux provisioning script to install meson 0.54.3
- Fixes `vcpkg_find_acquire_program` suggesting that linux users use `apt` to install meson, instead of `pip3`
- Updates `vcpkg_find_acquire_program` meson version to 0.54.3
- Updates `ports/tool-meson/CONTROL` version to 0.54.3

**What does your PR fix?**
Doesn't fix, but contributes to, the resolution of #10786. A quick search of the issues for `meson` suggests that it would be useful for a number of others, too.

**Which triplets are supported/not supported? Have you updated the CI baseline?**
I don't think this question is relevant to my change, since I'm not submitting a port.

**Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?**
I believe so.

### CODE REVIEW

**Comment by Neumann-A** [comment]
as said previously we cannot rely on the system package manager for meson due to it being to low in version. As soon as meson hits 0.55.1 i will continue #12393 which will simply download the version specified by vcpkg and use that instead of system provided meson.

**Comment by marzer** [comment]
@Neumann-A Are you saying that this PR isn't necessary then? If so, I'm happy to close it. I don't really want to maintain this.

**Comment by Neumann-A** [comment]
> Where? am I supposed to know what you're talking about?

see discussion in #12224. 

>Are you saying that this PR isn't necessary then? If so, I'm happy to close it. I don't really want to maintain this.

according to the discussion in https://github.com/microsoft/vcpkg/pull/12224#issuecomment-653216139 I would say yes since we will use a different approach to fix the meson version in the future.

**Comment by marzer** [comment]
None of your points in that PR suggest that, except maybe the one about `vcpkg_find_acquire_program`, but that's actually addressed by this PR. You need to provide more information.

**Comment by marzer** [comment]
Actually, never mind. If your PR brings meson up to a newer version, then I don't really care much for the details ^_^

**Pull request closed without merging**
