### PR TITLE
[libusb] Update to 1.0.22

### PR DESCRIPTION
**Pull request by ryanfitzsimon**
* Update version to v1.0.22 tag instead of non-release commit hash.

* Remove libusb-usbdk output library.

The two Windows backends have been unified. The UsbDk backend is
selectable at runtime using the function libusb_set_option().

* Remove libfreenect2 patch (changes integrated upstream).

* Tidy up portfile.

### CODE REVIEW

**Comment by ryanfitzsimon** [comment]
@jasjuang can you confirm the libfreenect2 patch is no longer necessary? 

As far as I can tell upstream now provides the same functionality.

**Comment by huangqinjin** [comment]
+1. My project uses libusb. I encountered a problem with current version 1.0.21-fc99620 
```
libusb: error [init_device] device '\\.\USB#VID_04D9&PID_8008&MI_03#6&165EC319&0&0001' is no longer connected!
```
It doesn't matters and only occurs on some machines. I have no idea about that. If I substitute with the prebuilt 1.0.22 binary from https://libusb.info/ , or, with this commit, the error disappears.

**Comment by ryanfitzsimon** [comment]
Using vcpkg_install_msbuild() makes things much cleaner, thanks @ras0219-msft!

**Comment by ras0219-msft** [comment]
@ryanfitzsimon Np!

Also, in the future to make it easier on you, I'd recommend making branches for PRs because that way when we push tweaks they won't disturb your master branch :)

**Pull request merged**
