### PR TITLE
[asmjit] Update to latest (2022-04-10)

### PR DESCRIPTION
**Pull request by acidicoala**
This PR updates **asmjit** port to the latest version. It is important because I am working on a new port for [asmtk](https://github.com/acidicoala/asmtk), which depends on the latest asmjit.

### CODE REVIEW

**Comment by acidicoala** [comment]
It would appear that `fbgemm` and `polyhook2` ports are failing to build now. I'm working on `polyhook2` right now, so the next version will require latest asmjit as well. I'm not sure what the appropriate course of actions should be for the `fbgemm` port.

**Comment by Adela0814** [comment]
Due to `fbgemm `and `polyhook2 `ports are failing to build now，I convert this PR to draft temporarily. if this PR is ready to review, please connect us.

**Comment by acidicoala** [comment]
@Adela0814, how is this situation supposed to be resolved? Polyhook2 port cannot be updated until asmjit is updated. fbgemm depends on the older version. What is the vcpkg's policy for resolving cycling dependency breakages? Perhaps fbgemm ports should pin the asmjit version in its manifest?

**Comment by JackBoosY** [comment]
fbgemm:
```
C:\PROGRA~1\MICROS~1\2022\ENTERP~1\VC\Tools\MSVC\1431~1.311\bin\Hostx64\x64\cl.exe   /TP -DCPUINFO_SUPPORTED_PLATFORM=1 -ID:\buildtrees\fbgemm\src\86cd37ac2a-f4be5156b3.clean\include -ID:\buildtrees\fbgemm\src\86cd37ac2a-f4be5156b3.clean -external:ID:\installed\x64-windows\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  -openmp /wd4244 /wd4267 /wd4305 /wd4309 /wd4703 /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++14 /showIncludes /FoCMakeFiles\fbgemm_generic.dir\src\GroupwiseConvAcc32Avx2.cc.obj /FdCMakeFiles\fbgemm_generic.dir\ /FS -c D:\buildtrees\fbgemm\src\86cd37ac2a-f4be5156b3.clean\src\GroupwiseConvAcc32Avx2.cc
D:\buildtrees\fbgemm\src\86cd37ac2a-f4be5156b3.clean\include\fbgemm/Utils.h(91): error C2872: 'x86': ambiguous symbol
D:\buildtrees\fbgemm\src\86cd37ac2a-f4be5156b3.clean\include\fbgemm/Utils.h(18): note: could be 'asmjit::x86'
D:\installed\x64-windows\include\asmjit\x86/x86instdb.h(11): note: or       'asmjit::_abi_1_9::x86'
```

polyhook2:
```
C:\PROGRA~1\MICROS~1\2022\ENTERP~1\VC\Tools\MSVC\1431~1.311\bin\Hostx64\x64\cl.exe   /TP -DPolyHook_2_EXPORTS -ID:\buildtrees\polyhook2\src\c3a4b86737-1f78841e35.clean -ID:\installed\x64-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -MDd /MP /W4 /Z7 -std:c++17 /showIncludes /FoCMakeFiles\PolyHook_2.dir\sources\ILCallback.cpp.obj /FdCMakeFiles\PolyHook_2.dir\ /FS -c D:\buildtrees\polyhook2\src\c3a4b86737-1f78841e35.clean\sources\ILCallback.cpp
cl : Command line warning D9025 : overriding '/W3' with '/W4'
D:\buildtrees\polyhook2\src\c3a4b86737-1f78841e35.clean\polyhook2/Detour/ILCallback.hpp(53): error C2039: 'Arch': is not a member of 'asmjit::_abi_1_9::Environment'
D:\installed\x64-windows\include\asmjit\core\../core/environment.h(183): note: see declaration of 'asmjit::_abi_1_9::Environment'
D:\buildtrees\polyhook2\src\c3a4b86737-1f78841e35.clean\polyhook2/Detour/ILCallback.hpp(53): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\buildtrees\polyhook2\src\c3a4b86737-1f78841e35.clean\polyhook2/Detour/ILCallback.hpp(53): error C2146: syntax error: missing ')' before identifier 'arch'
```

This is obviously caused by the fact that these two ports do not support the latest asmjit, we should wait for them to support the new version of asmjit and update them synchronously with asmjit.

**Comment by acidicoala** [comment]
@JackBoosY, Polyhook is relying on the latest asmjit version in its Github repo. How can Polyhook's vcpkg port support the latest asmjit version if the new version is not being approved here? Do you not see the contradiction here? Polyhook cannot update unless the latest asmjit version is available in vcpkg.

fbgemm's source uses older asmjit version. It doesn't seem to be the case that they are going to be switching to latest asmjit anytime soon. Does that mean that asmjit is now stuck forever with the current version until all of the dependent project require latest asmjit?

**Comment by acidicoala** [comment]
The reasonable thing to do here, given vcpkg's capabilities, is to pin fbgemm to that asmjit version which it supports. That's how it would be done in npm, or any other dependency manager worth the name.

**Comment by Neumann-A** [comment]
> How can Polyhook's vcpkg port support the latest asmjit version if the new version is not being approved here?

also update polyhook in this PR. This is how vcpkg works. 

 > The reasonable thing to do here, given vcpkg's capabilities, is to pin fbgemm to that asmjit version which it supports.
 
 That is not how vcpkg works. 

> Does that mean that asmjit is now stuck forever with the current version until all of the dependent project require latest asmjit?

Yes unless you patch/update downstream usage or the team decides to take the downstream ports out of the vcpkg repository.

**Comment by acidicoala** [comment]
I can sort out the issue on Polyhook side, but

> > Does that mean that asmjit is now stuck forever with the current version until all of the dependent project require latest asmjit?
>
> Yes unless you patch/update downstream usage or the team decides to take the downstream ports out of the vcpkg repository

What if the fbgemm maintainers have no intentions of switching to the latest asmjit? Why would they, if the version they're depending on works for them?

**Comment by stevemk14ebr** [comment]
I can update the polyhook port, as @acidicoala mentioned the current master branch of polyhook already supports this. This update is not easy due to the limitations of vcpkg, we have a cyclic dependency and due to vcpkg not supporting version pinning - or any reasonable versioning system at all - this is hard to do. Here is the current status of this.

Dependencies:
asmtk
- asmjit

polyhook2
- asmtk
- asmjit

fbgemm
- asmjit

To add the asmtk port, we have to update asmjit. To update polyhook2 we have to add the asmtk port, and update asmjit. To keep the fbgemm building, we have to use the old asmjit. I cannot update polyhook2 unless asmjit gets updated, and the asmtk port added. So, what's required is like 6 different PRs to be in flight all at once - this is painful. I will try to do this, but please consider the way vcpkg works to be unreasonably difficult for authors to work with dependencies like this.

**Review by raghavthind2005 — APPROVED** [review]

**Comment by Adela0814** [comment]
Closing this PR since it seems that no progress is being made. Please reopen if work is still being done.

**Comment by stevemk14ebr** [comment]
Please re-open FBGEMM is still waiting to update which is the blocker right now.

**Comment by JackBoosY** [comment]
@acidicoala Do you want to continue this PR?

**Comment by stevemk14ebr** [comment]
Please re-open @acidicoala FBGEMM has landed their asmjit update as of 3hrs ago here https://github.com/pytorch/FBGEMM/commit/64a5c4a9f7f18cbf0e2afcaa561d96c949afd950. It's now possible for asmjit, and fbgemm ports to be updated. Once that's done, this unblocks asmtk to be added, and that will unblock the polyhook2 port update.

**Pull request closed without merging**
