### PR TITLE
[darknet] update to latest release

### LINKED ISSUE #6120: [darknet, openmama, gherkin-c, libevent] Conflicts when installing headers
The following header conflics occur when trying to install these libraries in the presence of each other.

Header file | Conflicting Ports
-- | -- 
`include/list.h` | `darknet` & `openmama`
`include/parser.h` | `darknet` & `gherkin-c`
`include/event.h` | `gherkin-c` & `libevent`

Due to user expectation, we want to preserve upstream include paths as much as possible.
However, when these file conflicts happen, a decision must be made by the `vcpkg` team on which library will be "blessed" by our CI tests.

For example, in the case of `libevent`, due to it's long history, it takes precedence in claiming ownership of `include/event.h`. 

The logical solution would be to move the installation path to these packages to their own subfolders, e.g.: `include/darknet/list.h`, `include/openmama/list.h`. And the easiest way to do this, would be doing this within the portfile. However, the right way would be to submit a request for these changes to be made upstream.

### PR DESCRIPTION
**Pull request by cenit**
Partially solves some problems explained in #6120 (I edited to avoid the verb "fixes" which would have triggered a closed-issue after merging this pr...) for what concern darknet. It took a little bit longer than expected but it is fixed upstream so it should be the best option here

### CODE REVIEW

**Comment by cenit** [comment]
also in the newer release I did a lot of rework for people using darknet as a library. Waiting for feedback on it, i hope it's well accepted

**Comment by cenit** [comment]
please wait a little bit before merge. All these changes will be implemented very soon also upstream, reducing patch size even more

**Comment by ras0219-msft** [comment]
Thanks for the notice!

Could you close this PR and re-open it as a draft PR [1]? Draft PRs are great because _you_ can decide when to promote it to be ready for merging.

[1] https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by cenit** [comment]
> Thanks for the notice!
> 
> Could you close this PR and re-open it as a draft PR [1]? Draft PRs are great because _you_ can decide when to promote it to be ready for merging.
> 
> [1] https://github.blog/2019-02-14-introducing-draft-pull-requests/

@ras0219-msft sorry I didn't read last message.
Anyway, just updated with latest revision. It does not require any patch anymore. If CI is ok, IMHO we can remove the wip tag @cbezault

**Comment by cenit** [comment]
@cbezault any particular request on this PR?

**Pull request merged**
