### PR TITLE
[ppxbase] Add new port

### PR DESCRIPTION
**Pull request by winsoft666**
add new port ppxbase

### CODE REVIEW

**Comment by winsoft666** [comment]
duilib2 only support windows.
ppxbase support windows and linux.

**Review by NancyLi1013 — CHANGES_REQUESTED** [review]

**Comment by NancyLi1013** [comment]
@winsoft666  thanks for this PR.
I noticed that this port failed on the Windows CI. The errors like these:
```
C:\VS2017\Stable\VC\Tools\MSVC\14.22.27905\include\xstring(434): error C2027: use of undefined type 'std::basic_ostream<char,std::char_traits<char>>'
C:\VS2017\Stable\VC\Tools\MSVC\14.22.27905\include\iosfwd(216): note: see declaration of 'std::basic_ostream<char,std::char_traits<char>>'
C:\VS2017\Stable\VC\Tools\MSVC\14.22.27905\include\xstring(4417): note: see reference to function template instantiation 'std::basic_ostream<char,std::char_traits<char>> &std::_Insert_string<char,std::char_traits<char>,unsigned __int64>(std::basic_ostream<char,std::char_traits<char>> &,const _Elem *const ,const _SizeT)' being compiled
        with
        [
            _Elem=char,
            _SizeT=unsigned __int64
        ]
C:\vsts\_work\2\s\buildtrees\ppxbase\src\v1.37-db207a42e5\src\ipaddress.cpp(128): note: see reference to function template instantiation 'std::basic_ostream<char,std::char_traits<char>> &std::operator <<<char,std::char_traits<char>,std::allocator<char>>(std::basic_ostream<char,std::char_traits<char>> &,const std::basic_string<char,std::char_traits<char>,std::allocator<char>> &)' being compiled
C:\VS2017\Stable\VC\Tools\MSVC\14.22.27905\include\xstring(434): error C2065: 'iostate': undeclared identifier
C:\VS2017\Stable\VC\Tools\MSVC\14.22.27905\include\xstring(434): error C2146: syntax error: missing ';' before identifier '_State'
C:\VS2017\Stable\VC\Tools\MSVC\14.22.27905\include\xstring(434): error C2065: '_State': undeclared identifier
C:\VS2017\Stable\VC\Tools\MSVC\14.22.27905\include\xstring(434): error C2027: use of undefined type 'std::basic_ostream<char,std::char_traits<char>>'
C:\VS2017\Stable\VC\Tools\MSVC\14.22.27905\include\iosfwd(216): note: see declaration of 'std::basic_ostream<char,std::char_traits<char>>'
C:\VS2017\Stable\VC\Tools\MSVC\14.22.27905\include\xstring(434): error C2065: 'goodbit': undeclared identifier
C:\VS2017\Stable\VC\Tools\MSVC\14.22.27905\include\xstring(435): error C2027: use of undefined type 'std::basic_ostream<char,std::char_traits<char>>'
C:\VS2017\Stable\VC\Tools\MSVC\14.22.27905\include\iosfwd(216): note: see declaration of 'std::basic_ostream<char,std::char_traits<char>>'
C:\VS2017\Stable\VC\Tools\MSVC\14.22.27905\include\xstring(437): error C2027: use of undefined type 'std::basic_ostream<char,std::char_traits<char>>'
C:\VS2017\Stable\VC\Tools\MSVC\14.22.27905\include\iosfwd(216): note: see declaration of 'std::basic_ostream<char,std::char_traits<char>>'
C:\VS2017\Stable\VC\Tools\MSVC\14.22.27905\include\xstring(438): error C2027: use of undefined type 'std::basic_ostream<char,std::char_traits<char>>'
C:\VS2017\Stable\VC\Tools\MSVC\14.22.27905\include\iosfwd(216): note: see declaration of 'std::basic_ostream<char,std::char_traits<char>>'
C:\VS2017\Stable\VC\Tools\MSVC\14.22.27905\include\xstring(438): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:\VS2017\Stable\VC\Tools\MSVC\14.22.27905\include\xstring(438): error C2146: syntax error: missing ';' before identifier '_Ok'
C:\VS2017\Stable\VC\Tools\MSVC\14.22.27905\include\xstring(438): error C3861: '_Ok': identifier not found
C:\VS2017\Stable\VC\Tools\MSVC\14.22.27905\include\xstring(440): error C2065: '_Ok': undeclared identifier
C:\VS2017\Stable\VC\Tools\MSVC\14.22.27905\include\xstring(441): error C2065: '_State': undeclared identifier
```
Could you take a look and try to fix this issue?

What's more, what issue does this PR fix? Please open an issue so others may replicate this problem.

**Comment by winsoft666** [comment]
thanks, I'll solve above problems in a new push request.

**Comment by NancyLi1013** [comment]
Thanks for your updates. 
BTW, It is not necessary to open an issue for new port. Sorry for my mistake.

**Pull request closed without merging**
