### PR TITLE
[vcpkg] Use last commit hash as VCPKG_VERSION

### PR DESCRIPTION
**Pull request by myd7349**
**Describe the pull request**

This PR added the last commit hash of `vcpkg` repository into the vcpkg version information.

Before this PR:
```
$ ./vcpkg version
Vcpkg package management program version 2020.02.04-unknownhash

See LICENSE.txt for license information.
```

With this PR:
```
$ ./vcpkg version
Vcpkg package management program version 2020.02.04-9b73fa681

See LICENSE.txt for license information.
```

- What does your PR fix?
N/A

- Which triplets are supported/not supported? Have you updated the CI baseline?
N/A

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes.

### CODE REVIEW

**Comment by c72578** [comment]
Could you please edit and update the first comment of this PR:
2020.02.04-unknownhash->2020.02.04-nohash

**Comment by myd7349** [comment]
> 
> 
> Could you please edit and update the first comment of this PR:
> 2020.02.04-unknownhash->2020.02.04-nohash

If `VCPKG_VERSION` is not defined, then:
https://github.com/microsoft/vcpkg/blob/9b4535e7ee7673fb8515d1f4f256990423a0d952/toolsrc/src/vcpkg/commands.version.cpp#L14

Shall we always use `unknownhash`/`nohash` for consistency?

**Comment by c72578** [comment]
> 
> Shall we always use `unknownhash`/`nohash` for consistency?

Makes sense, to use `unknownhash` under all supported OS for consistency.

**Comment by dan-shaw** [comment]
Our decision to use `-nohash` or `-unknownhash` instead of the commit id was for GDPR reasons.

**Comment by myd7349** [comment]
> 
> 
> Our decision to use `-nohash` or `-unknownhash` instead of the commit id was for GDPR reasons.

Hi! @dan-shaw Thanks for telling me that.
I will close this PR now.

**Pull request closed without merging**
