### PR TITLE
[vcpkg baseline][libpcap] Fix flex command --header-file

### PR DESCRIPTION
**Pull request by MonicaLiu0311**
Because the upstream uses the `flex` command [`--header-file=NUL:`](https://github.com/the-tcpdump-group/libpcap/blob/libpcap-1.10.4/CMakeLists.txt#L2529-L2545) , CI Pipelines reports an error: 
```
error delete file C:\Users\AzDevOps\AppData\Local\Temp\~1_flex_5win_flex.exe: error deleting file C:\Users\AzDevOps\AppData\Local\Temp\~flex_out_main_2
CMake Error at CMakeLists.txt:2539 (message):
  D:/downloads/tools/win_flex/2.5.25/win_flex.exe is insufficient to compile
  libpcap.

  libpcap requires Flex 2.5.31 or later, or a compatible version of lex.

  If a suitable version of Lex/Flex is available as a non-standard command

  and/or not in the PATH, you can specify it using the LEX environment

  variable.  That said, on some systems the error can mean that Flex/Lex is

  actually acceptable, but m4 is not.  Likewise, if a suitable version of

  m4 (such as GNU M4) is available but has not been detected, you can

  specify it using the M4 environment variable.
```

Now change it to `--header-file=NULL`: [`fix-flex.patch`](https://github.com/microsoft/vcpkg/pull/34670/files#diff-72f862187384aac48376dc7e75fa89d51ecf621df3f7d75ace9a6e4fc51c29d2).

Reported upstream: https://github.com/the-tcpdump-group/libpcap/issues/1227.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Review by Cheney-W — DISMISSED** [review]

**Comment by guyharris** [comment]
OK, how about ~~`set(NULL_DEVICE "/dev/NUL:")`~~ `set(NULL_DEVICE "\\.\NUL:")` (with backslashes escaped as necessary)?

So why is this causing a CI problem?  Neither `set(NULL_DEVICE "NUL:")` nor `set(NULL_DEVICE "/dev/null:")` are causing a problem with any of the CI done by libpcap.  Is some part of your CI assuming that `--header-file=` is given a regular file argument, rather than the name of the null device?  The goal here is to cause `flex`, when run here *solely* to see whether it's capable of processing libpcap's scanner source, not to produce any additional output (its C-code output to the standard output is discarded).

**Review by dg0yt — CHANGES_REQUESTED** [review]
I think the analysis and solution might be wrong.

This port runs `flex` during the CMake configure step (and probably writes to the source dir).
vcpkg runs debug and release configure in parallel.
Winflex does not use unique names for temporary files.
Together, this leads to a race condition which has hit other vcpkg ports before.

My proposed solution is to disable parallel configure.

**Comment by dg0yt** [comment]
See also https://github.com/microsoft/vcpkg/issues/29139.

**Comment by guyharris** [comment]
> Winflex does not use unique names for temporary files.

If that's the Flex in WinFlexBison, then that appears to be lexxmark/winflexbison#86, fixed in lexxmark/winflexbison#91, although [commit f496d70a0baa36a05f021d2bc66351dd4905778c](https://github.com/lexxmark/winflexbison/commit/f496d70a0baa36a05f021d2bc66351dd4905778c) also appears to have been intended to fix this.

Unfortunately, the last release appears, from [the releases page](https://github.com/lexxmark/winflexbison/releases), to have been in January 2022, and the first of those fixes was in March 2023.

**Pull request merged**
