### PR TITLE
[abseil] Install headers to sub-directories of ${LIB}/internal recursively.

### PR DESCRIPTION
**Pull request by kjpus**
Up to now, `absl::str_format` doesn't work on vcpkg, becuase some header files are not installed into `strings/internal/str_format`. This fix will recursively copy all header files in ${LIB}/internal to the correct locations. Tested on Windows (x64-windows triplet). Here'e the entire include tree:

```
├───algorithm
├───base
│   └───internal
├───container
│   └───internal
├───debugging
│   └───internal
├───memory
├───meta
├───numeric
├───strings
│   └───internal
│       └───str_format
├───synchronization
│   └───internal
├───time
│   └───internal
│       └───cctz
│           ├───include
│           │   └───cctz
│           └───src
├───types
│   └───internal
└───utility
```

### CODE REVIEW

**Comment by OlafvdSpek** [comment]
Indentation of either foreach or endforeach doesn't seem correct.

**Comment by kjpus** [comment]
@OlafvdSpek You are right about the indentation.

HEADERS includes .inc files, while INTERNAL_HEADERS doesn't. It seems it it was done this way so that `${LIB}/*.inc` are installed, but `${LIB}/internal/*.inc` are not.

**Comment by OlafvdSpek** [comment]
What if an internal .inc is included by an internal or non-internal header?

**Comment by kjpus** [comment]
That only happens in one header, probably for a platform not supported by vcpkg. Can't remember which one at the moment.

**Comment by OlafvdSpek** [comment]
For now.. ;)

**Comment by kjpus** [comment]
That one is in `mutex.h`. Go check out the source code, and you'll see why I think it is unlikely this becomes a problem, ever.

Of course, Google can always change upstream...

**Comment by ras0219-msft** [comment]
The internal vs non-internal was simply to avoid the slightly more complex code you've helpfully submitted in this PR -- there isn't any particular issue with `internal\*.inc`.

Therefore, I think the right way forward would be to get rid of the whole `INTERNAL_HEADERS` and just use your algorithm for `HEADERS`.

**Pull request closed without merging**
