### PR TITLE
[libxslt] added linux support

### PR DESCRIPTION
**Pull request by ArneGockeln**
This PR adds support to build Libxslt on linux machines.

### CODE REVIEW

**Comment by dmn-star** [comment]
I think this can be simple closed now, because of #8589

**Comment by JackBoosY** [comment]
Hi @ArneGockeln, libxslt now support UNIX(linux/OSX) using configure/make.

**Comment by JackBoosY** [comment]
Close this PR via #8589.

**Comment by JackBoosY** [comment]
@ArneGockeln Thanks for your effort!

**Pull request closed without merging**
