### PR TITLE
[google-cloud-cpp*] Update to 0.16.0

### PR DESCRIPTION
**Pull request by coryan**

### CODE REVIEW

**Comment by coryan** [comment]
Ping.  Can one of the expert help me understand what the error messages mean?  AFAICT the new ports build. Did I do something wrong?

**Comment by JackBoosY** [comment]
@coryan We just fixed the CI system.

**Comment by vicroms** [comment]
@coryan 

Our CI was showing issues unrelated to these libraries, it has now been fixed.
Thanks for your PR!

**Comment by coryan** [comment]
Thanks for the update, sorry to hear about the CI troubles.

**Pull request merged**
