### PR TITLE
[vcpkg.cmake] remove timestamp file

### PR DESCRIPTION
**Pull request by Neumann-A**
Otherwise CMake errors on reconfigure if _VCPKG_INSTALLED_DIR is a subdir of CMAKE_SOURCE_DIR and not within CMAKE_BINARY_DIR if in source changes are forbidden

### CODE REVIEW

**Comment by strega-nil-ms** [comment]
This doesn't actually help us. The best way, likely, is to remove this entirely, and then make `vcpkg` write out a .stamp file whenever it does a modifying operation, and check for that.

**Comment by Neumann-A** [comment]
stupid question but who/what is actually using/checking this file (only CONFIGURE_DEPENDS?)? Can you not use some file from the `/vcpkg` subfolder in `VCPKG_INSTALLED_DIR`? (e.g. like the status file there?)

**Comment by strega-nil-ms** [comment]
@Neumann-A that'd be great if vcpkg actually wrote to the status file always.

**Comment by JackBoosY** [comment]
Any result here? @BillyONeal @strega-nil-ms should we accept this?

**Comment by BillyONeal** [comment]
> Any result here? @BillyONeal @strega-nil-ms should we accept this?

I am not super familiar about how this works. I know this proposed fix is not quite correct but I think I need Nicole back from vacation to even consider describing what a correct fix might be.

**Comment by Neumann-A** [comment]
https://discord.com/channels/400588936151433218/687365466422902841/895283628538478592

https://discord.com/channels/400588936151433218/687365466422902841/895298811772170260

**Comment by strega-nil-ms** [comment]
@Neumann-A the issue with this is it doesn't "help" at all with the actual problem; it'd be better to just remove this code completely

**Comment by Neumann-A** [comment]
> @Neumann-A the issue with this is it doesn't "help" at all with the actual problem; it'd be better to just remove this code completely


done

**Comment by BillyONeal** [comment]
`buildsystems/vcpkg.cmake` isn't in the ABI hash so this is not a world rebuild.

**Comment by JackBoosY** [comment]
Ping @strega-nil-ms for review this.

**Comment by strega-nil-ms** [comment]
Thanks!

**Pull request merged**
