### PR TITLE
[exiv2] Update to 0.28

### PR DESCRIPTION
**Pull request by DownerCase**
A continuation of #31722. With the recent update to `inih` all the .pc files expected by this project are now present 😄 
The windows unicode feature was merged into the baseline feature set upstream.

- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [X] SHA512s are updated for each updated download
- [X] The "supports" clause reflects platforms that may be fixed by this new version
- [X] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [X] Any patches that are no longer applied are deleted from the port's directory.
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by Cheney-W** [comment]
All features and usage passed with following triplets:
```
x86-windows 
x64-windows 
```

But usage failed with below error in x64-windows-static triplet:
```
CMake Error at F:/33126/installed/x64-windows-static/share/exiv2/vcpkg-cmake-wrapper.cmake:25 (set_property):
  Property INTERFACE_LINK_LIBRARIES may not contain link-type keyword
  "optimized".  The INTERFACE_LINK_LIBRARIES property may contain
  configuration-sensitive generator-expressions which may be used to specify
  per-configuration rules.
```

**Comment by Cheney-W** [comment]
@DownerCase Could you please solve the usage issue?

**Comment by DownerCase** [comment]
So my first version there did a simple `target_link_libraries(...` but then I found why it wasn't already like that with #19120. I don't fully understand but I was able to find #23664 and apply the pattern from there to fix the issue.

I _think_ this is fine but will probably do some more testing...

**Comment by Cheney-W** [comment]
Feature and usage passed with `x64-windows-static` triplet.

**Pull request merged**
