### PR TITLE
[botan] pass -fPIC for static libraries

### LINKED ISSUE #21461: botan2 build static botan-2.a with enable -fPIC
****

**Is your feature request related to a problem? Please describe.**

```
/usr/bin/ld: /usr/local/share/vcpkg/installed/x64-linux/debug/lib/libbotan-2.a(src_lib_ffi.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
```

Full log: https://github.com/rnpgp/rnp/runs/4222343272?check_suite_focus=true#step:7:724

**Proposed solution**

Always compile with `--extra-cxxflags=-fPIC`

**Describe alternatives you've considered**

IDK about possible alternatives

**Additional context**

More logs https://github.com/rnpgp/rnp/runs/4222343068

### PR DESCRIPTION
**Pull request by CAMOBAP**
**Describe the pull request**

- #### What does your PR fix?  
  Fixes #21461

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  This is my first PR, but looks like it follow the rules

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Done

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by LilyWangLL** [comment]
@CAMOBAP Thanks for your PR. Please bump the port version. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).
Also please run command `vcpkg x-add-version --all` then commit the changes.

**Review by LilyWangLL — CHANGES_REQUESTED** [review]
Please bump the port version. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).
Also please run command `vcpkg x-add-version --all` then commit the changes.

**Comment by CAMOBAP** [comment]
@LilyWangLL I think I already did this, here is result in this PR https://github.com/microsoft/vcpkg/pull/21522/files#diff-d3ae18b4fe81bb994249a364fa35b1d04110254662de8793da49ffb8f33a44a5L4-R4

**Comment by CAMOBAP** [comment]
@LilyWangLL can I update `port-version` manually?

**Comment by CAMOBAP** [comment]
Updated manually @LilyWangLL could you please have a look

**Comment by dg0yt** [comment]
I do understand that linking `libbotan-2.a` into a a shared object may need `-fpic` (#21461). But I doubt that adding the parameter in vcpkg is the right solution, because this forces the disadvantages of PIC on all users.
Alternatives:
- Use a dynamic triplet when you want shared objects.
- Use a custom triplet which modifies the flags only for building port `botan`.
- Use an overlay port for `botan` which sets the flag.

**Comment by CAMOBAP** [comment]
@dg0yt thanks for the feedback

> Use a dynamic triplet when you want shared objects.

Not an option unfortunatelly

> Use a custom triplet which modifies the flags only for building port botan.

AFAIK custom triplets means creation for dedicated triplet cmake file, which cannot affect boatn port. Initally I searched for some way to 'override' `BOTAN_FLAG_STATIC` but there is no such option

> Use an overlay port for botan which sets the flag.

Never heard about it, let me check

**Comment by dg0yt** [comment]
> > Use a custom triplet which modifies the flags only for building port botan.
>
> AFAIK custom triplets means creation for dedicated triplet cmake file, which cannot affect boatn port. Initally I searched for some way to 'override' BOTAN_FLAG_STATIC but there is no such option

The triplet file is loaded before `portfile.cmake`. So in your custom triplet file, you could do something like:

~~~cmake
if(PORT STREQUAL "botan")
    # modify vcpkg flags as you like
endif()
~~~

**Comment by CAMOBAP** [comment]
@dg0yt thanks for the comment overlay ports solve my issues

> The triplet file is loaded before portfile.cmake. So in your custom triplet file, you could do something like...

I understand but because botan build system is configure-based, I don't see an option how custom triplet can help here (probably because I has lack of experience with vcpkg). I will be glad if you can share some examples of custom tripets just for me to understand their limits.

I'm totally ok to close this PR

Thanks again

**Comment by dg0yt** [comment]
> I understand but because botan build system is configure-based, I don't see an option how custom triplet can help here.

`vcpkg_configure_make` tries to use the same flags that would be used for cmake. So you can use `VCPKG_C_FLAGS` etc., 
https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md

> I will be glad if you can share some examples of custom tripets just for me to understand their limits.

There is nothing magical. The main downside is that changing the triplet changes the hashes which control binary artifact caching.

**Pull request closed without merging**
