### PR TITLE
[boringssl] Fix pkg-config & cmake find module compat

### PR DESCRIPTION
**Pull request by BurningEnlightenment**
This is a backport of the uncontroversial changes from #30986 @BillyONeal @FrankXie05 

I specified a filename postfix ("d") in order to enable full compatibility with `FindOpenSSL.cmake`.

BoringSSL gained a proper install target with an exported config last year. The exported config is highly compatible with the CMake built-in `FindOpenSSL.cmake` module which is why I added usage information without specifying `MODULE/CONFIG`.

I fixed the pkg-config platform-specific library name sanitization: Previously it removed the `lib` prefix for non-MSVC targets, but left them inplace for MSVC targets. Furthermore it removed the Windows dependencies for MinGW which doesn't match the upstream expectations.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by Neumann-A** [comment]
Needs manual testing: `boringssl:x64-windows:     skip:`

**Comment by BurningEnlightenment** [comment]
I've successfully installed the `grpc` port with `boringssl` on:
- [x] `x64-windows`
- [x] `x64-windows-static`
- [x] `x64-linux` (`Ubuntu-22.04`)

**Comment by BurningEnlightenment** [comment]
@JonLiu1993 @FrankXie05 @BillyONeal can we get this reviewed / merged?

**Comment by JonLiu1993** [comment]
Tested usage successfully by `boring:x64-windows`；
````
boringssl can be found via the built-in CMake find-module:

    find_package(OpenSSL REQUIRED)
    target_link_libraries(main PRIVATE OpenSSL::SSL OpenSSL::Crypto)
````

**Review by JonLiu1993 — APPROVED** [review]

**Comment by autoantwort** [comment]
Since this PR https://github.com/microsoft/vcpkg/issues/31546 happens

**Pull request merged**
