### PR TITLE
[DO NOT MERGE] trigger full rebuild

### PR DESCRIPTION
**Pull request by cenit**
**Describe the pull request**
Due to infinite number of regressions in #11130 I fear that something slipped in, breaking many ports. CMake 3.17?
Here I just want to test in CI what happens triggering a full rebuild...

### CODE REVIEW

**Comment by cenit** [comment]
All the failures on osx and Linux are not due to msys2 problems...
These failures explain many of those experienced in #11130

**Comment by cenit** [comment]
All the failures on osx and Linux are not due to msys2 problems...
These failures explain many of those experienced in #11130

**Comment by BillyONeal** [comment]
> All the failures on osx and Linux are not due to msys2 problems...

Yes, but the previous thing that kept causing this PR to hang the builders forever was

**Comment by BillyONeal** [comment]
The boost ARM ones should be fixed by https://github.com/microsoft/vcpkg/pull/11545/

**Comment by JackBoosY** [comment]
- []`seal:arm64-windows`
- []`quickfix:arm64-windows`
- []`libaiff:arm64-windows`
- []`boost-exception:arm64-windows`
- []`boost-regex:arm64-windows`
- []`boost-stacktrace:arm64-windows`
- []`boost-system:arm64-windows`
- []`boost-container:arm64-windows`
- []`boost-atomic:arm64-windows`
- []`boost-signals:arm64-windows`
- []`boost-atomic:arm-uwp`
- []`geographiclib:arm-uwp`
- []`boost-exception:arm-uwp`
- []`boost-regex:arm-uwp`
- []`boost-nowide:arm-uwp`
- []`boost-system:arm-uwp`
- []`boost-container:arm-uwp`
- []`boost-signals:arm-uwp`
- []`bond:x64-linux`
- []`seal:x64-linux`
- []`opencc:x64-linux`
- []`wtl:x64-linux`
- []`seal:x64-osx`
- []`sigslot:x64-osx`
- []`xmsh:x64-osx`
- []`nettle:x64-osx`
- []`geographiclib:x64-windows`
- []`gmp:x64-windows`
- []`pdal:x64-windows`
- []`icu:x64-windows`
- []`seal:x64-windows`
- []`seal:x64-windows-static`
- []`libfabric:x64-windows-static`
- []`pdal:x64-windows-static`
- []`ois:x64-windows-static`
- []`zxing-cpp:x64-windows-static`
- []`icu:x64-windows-static`
- []`seal:x86-windows`
- []`ccfits:x86-windows`
- []`gsoap:x86-windows`
- []`pdal:x86-windows`
- []`gmp:x86-windows`
- []icu:x86-windows`

**Comment by PhoebeHui** [comment]
sigslot:x64-osx failure doesn't repro locally, and didn't see this issue in latest CI testing status.

**Comment by JackBoosY** [comment]
All green!

**Comment by cenit** [comment]
> All green!

I still see a regression on msix on x86-windows.
Also, I will trigger another final full rebuild whenever I will see a green checkmark, just to be sure...

**Comment by JackBoosY** [comment]
@cenit That pipeline test case has been deprecated.

**Comment by cenit** [comment]
@JackBoosY as you can see, we are still far from a green checkmark on the baseline... unfortunately

> @cenit That pipeline test case has been deprecated.

?? this PR is perfectly in sync with master, only triggering a full port-tree rebuild

**Comment by JackBoosY** [comment]
@cenit Looks like more and more regressions appear, and I'm fixing them.

**Comment by BillyONeal** [comment]
@cenit What are you actually trying to accomplish with this? All this is doing is showing that when you run 1300 separate build systems, the probability of any one of them having flaky behavior approaches 1. And in so doing is burning a ton of compute time and wasted cache storage space. We have the binary caching system precisely because that is necessary to ever make any progress with a system like this.

**Comment by BillyONeal** [comment]
In particular almost all the recent ones are failures to download the sources to build from a third party server which is absolutely not a bug in vcpkg.

**Comment by cenit** [comment]
I was triggering this at the beginning because I had tons of regressions in my opencv PR, all of them not due to my modifications (which on the other hand were extensive and required careful checks).
I was just trying to have a clean baseline, then of course the mission of this PR was over. It seems that having a clean baseline is not so mandatory here, so I will stop with it, understood. 
(caching original source artifacts when they do not change should not be a problem, while I disagree that having probability 1 of having a port broken in the official port-tree using an official triplet can be ok, but this is just IMHO...)

**Comment by BillyONeal** [comment]
>I was just trying to have a clean baseline, then of course the mission of this PR was over. It seems that having a clean baseline is not so mandatory here, so I will stop with it, understood.

I'm not saying that necessarily. This PR highlights that we need some process in place where we monitor for regressions caused by overall tool changes; we should probably be running full rebuilds at least once per week and more likely once per day, and publishing that information for others to consume here. It's just that that being a PR elevates a normal process into a 'fire drill' because someone's blocked because it's a PR :)

> (caching original source artifacts when they do not change should not be a problem, while I disagree that having probability 1 of having a port broken in the official port-tree using an official triplet can be ok, but this is just IMHO...)

It doesn't matter how official the triplet is, the sources are hosted by each third party associated with a given package. For example if SourceForge chooses a bad mirror for a given run you get a whole bunch of failures, none of which are really port bugs.

**Comment by cenit** [comment]
> It doesn't matter how official the triplet is, the sources are hosted by each third party associated with a given package. For example if SourceForge chooses a bad mirror for a given run you get a whole bunch of failures, none of which are really port bugs.

That's what I meant with "caching mechanism for original sources".

Ok thanks for clarifying your points. Of course an official mechanism to keep the tree in shape would be terrific and of course much better than a PR destined to be closed in the end.

**Comment by BillyONeal** [comment]
I'm going to discuss changing our CI builds to never run with binary caching enabled, only PR builds, at our next discussion meeting. (I want to make sure the team is OK with the resulting lower quality of service of PR validation since it's more work for the build fleet given that we have to stay under a core count quota, and the resulting increased expense of keeping the VMs alive longer, rather than making a change like that unilaterally)

**Comment by cenit** [comment]
I'd say that a reasonable compromise would be to expand hash coverage, as to say what declares a binary cache compatible or not. I mean, we should not use just one "outsider" cmake script (target fix is all but important during port build), but all "fundamental" cmake scripts that would change port file behaviour. 
Also, we should include compiler full version, cmake version, ninja version.
This might be useful to not let slip breaking changes, while at the same time preserve a minimum cache mechanism to avoid really unnecessary rebuilds

**Comment by BillyONeal** [comment]
>I'd say that a reasonable compromise would be to expand hash coverage, as to say what declares a binary cache compatible or not. I mean, we should not use just one "outsider" cmake script (target fix is all but important during port build), but all "fundamental" cmake scripts that would change port file behaviour.

We already do things like that.

>Also, we should include compiler full version, cmake version, ninja version.

Compiler is being worked on for that to enable the binary caching stuff. CMake and ninja versions are already included.

The issues this PR have found have been:
* Servers with sources being down
* Servers being up but making changes/redirects to their links that cause our SHA512 check to fail
* Ports that themselves have unstable / racy build scripts (e.g. nettle)
* Ports that are incompatible with each other or improperly inspecting the output directory (e.g. osg depends on boost-asio but will find a dependency in the asio package but needs boost headers, so if asio is installed the port fails to build)
* Merge conflicts that also put normal CI on the floor anyway
and I don't believe there's anything we can do to the caching system to truly address such problems. We can mitigate the first 2 in CI by caching the downloaded sources. The third we can't do much other than skipping such flaky ports; we can't really be in the business of fixing everyone's build race in ~1300 projects :). We could theoretically mitigate the next by doing increasingly exhaustive rebuild schemes (e.g. build each port with everything installed except its dependencies, build each port with only its dependencies and remove unrelated ports after each build, etc.) but that gets expensive in terms of compute time fast.

**Comment by BillyONeal** [comment]
@cenit Does #12082 resolve the concern you were trying to raise with this PR (and thus this one should be closed?

**Comment by cenit** [comment]
@BillyONeal it’s definitely a bold step in the right direction! We can close this one, sure. The main goal here was to highlight the problem, and it has been addressed both with port fixes and infrastructure fixes. 
Work might not be over, but PR goal is reached

**Pull request closed without merging**
