### PR TITLE
WIP: [vtk] [libharu] Add VTK-m and all-modules features to VTK, re-enable libharu

### PR DESCRIPTION
**Pull request by albertziegenhagel**
The following changes are applied to VTK:

  * re-enable system libharu by default and remove the feature introduced for it.
  * add a feature for VTK-m filters.
  * add a feature to build all modules (which includes all other features).

libharu has been fixed according to https://gitlab.kitware.com/vtk/vtk/blob/master/ThirdParty/libharu/vtklibharu/README.kitware.md.

This includes applying the PRs libharu/libharu#114 and libharu/libharu#157 to libharu.

### CODE REVIEW

**Comment by albertziegenhagel** [comment]
@ras0219-msft The `all-modules` feature that I introduced here depends on the `boost` meta package instead of specific boost libraries. Finding all `#include <boost/X>` in the code and adding those libraries as dependencies was not enough, and after adding three more boost libraries I gave up. Do you have any better way to figure out which libraries are really required?

**Comment by ras0219-msft** [comment]
Thanks for the PR!

Not to ignore the other questions, but could you quickly clarify the reasoning behind
>re-enable system libharu by default and remove the feature introduced for it.

If it can be optional, it seems reasonable to leave it as a feature. Or was the feature previously just toggling between the internal libharu and the system libharu?

**Comment by albertziegenhagel** [comment]
> Or was the feature previously just toggling between the internal libharu and the system libharu?

That's exactly what it did. And in my opinion in that case it is more clean to always use the library from vcpkg when we already provide it :)

Besides that I marked the PR work-in-progress, since the way `all-modules` is implement does not seem to work as I expected. vcpkg seems to get confused when I have an other port that depends on `vtk[all-modules]`. Even though `vtk[all-modules]` is installed it always wants to reinstall it but fails with `CASCADED_DUE_TO_MISSING_DEPENDENCIES`. I think this is because `all-modules` depends on all the other features of `vtk`. E.g. `vcpkg install vtk[all-modules] --featurepackages` correctly determines that it has to install `vtk[all-modules, openvr, mpi, python, core, vtkm]` but after the successful installation `vcpkg list` shows only `vcpkg[all-modules]`, `vcpkg[core]` and `vcpkg[openvr]` to be installed.

Anyway I think figuring out which additional modules exactly are enabled by `all-modules` and adding them separately would be the cleaner way to go.

Besides that I think that the fix for HDF5 is not working correctly as well. Currently the dependencies to `hdf5.lib` and `hdf5_hl.lib` are eliminated from the installed `vtkhdf5.cmake` file. This leads to undefined symbols when a library that uses VTK links to the `vtkhdf5` module. I am currently investigating ways to fix this.

**Comment by albertziegenhagel** [comment]
I'm closing this, since I do not currently have time to finish it and I think some of the changes will become unnecessary after the next VTK version gets released.

**Pull request closed without merging**
