### PR TITLE
[vcpkg] Update tls12-download.exe to 2021-05-05 version

### LINKED ISSUE #17688: tls2-downlload.exe get error 0x00000057 behind http proxy
**Describe the bug**
scripts/bootstrap.ps1 failed, because tls2-downlload.exe get error 0x00000057 behind http proxy

**Environment**
- OS: windows 10 v10.0.19042.0
- shell: powershell 5.1.19041.906

**To Reproduce**
1. $Env:HTTP_PROXY=http://192.168.32.1:8080; $Env:HTTPS_PROXY=http://192.168.32.1:8080 # Setup http proxy
2. .\bootstrap-vcpkg.bat
2. See error

**Expected behavior**
Download vcpkg.exe successifully.

**Failure logs** 
image

**Additional context**
There is nothing wrong with my proxy. At my local branch, I modified the 'scripts/bootstrap.ps1' to replace tls2-download.exe with aria2c, which installed by scoop. Then, downloading successed.
image

### PR DESCRIPTION
**Pull request by reitowo**
**Describe the pull request**
Update tls12-download.exe to 2021-05-05 version.

- #### What does your PR fix?  
  Fixes #17688 

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

### CODE REVIEW

**Review by PhoebeHui — APPROVED** [review]
Thanks for the PR!

**Comment by cnSchwarzer** [comment]
Hi guys, what's the status? :)

**Comment by PhoebeHui** [comment]
@dan-shaw, could you help merge this PR?

**Comment by ChanthMiao** [comment]
Can anyone merge this PR?

**Comment by PhoebeHui** [comment]
@ChanthMiao, @cnSchwarzer, the PR #17978 has been merged to master, I will colse this PR, for the issue, please get latest source and try again.

**Pull request closed without merging**
