### PR TITLE
[binutils, texinfo] Add new port

### PR DESCRIPTION
**Pull request by kafeg**
Binutils package for Linux

- Allow using custom Binutils

- Triplets: x64-linux

### CODE REVIEW

**Comment by BillyONeal** [comment]
We currently do not want to include ports which are 'entirely tools' of this form from the default catalog; this really puts us competing with binary distribution tools like apt which is an area we'd like to avoid right now. (We think it has too much potential to cause user confusion.) We have been kicking around ideas for what a 'tools port' would look like as an independent feature but that's not on our near-term roadmap.

You can use overlay-ports and the upcoming registry feature to use something like this in your own projects.

Thanks for your contribution nonetheless!

**Comment by kafeg** [comment]
Ok, i understand your position, but:
1. For e.g. you already have **llvm** port, which contains a lot of utilities. So if somebody will add a similar port for **gcc**, do you will reject it?
2. I planed to create next PR with **glibc** (GNU C Library) which depended on **binutils** port and now I'm in a situation when i can't push the library because its dependency is not present in vcpkg. How I could solve this with your current policy?

I'm confused and just don't know what I could do now, I had some plans on **glibc** in vcpkg.

**Comment by BillyONeal** [comment]
>For e.g. you already have llvm port, which contains a lot of utilities. 

That's because LLVM is usable as a library. That port is not intended to produce a working toolset.

> if somebody will add a similar port for gcc, do you will reject it?

Does it make sense to use GCC as a library? I know once upon a time it did not (and that's part of why LLVM was created in the first place) but I haven't followed that closely.

>I planed to create next PR with glibc (GNU C Library) which depended on binutils port

That port should probably get binutils from the same mechanism providing the rest of the toolset (e.g. gcc). I don't know how much sense it makes to statically link to glibc though...

**Comment by ras0219** [comment]
It sounds like your use case is to package an entire toolchain (compiler, standard library, linker, etc), which is outside the scope of the public, curated vcpkg catalog for now. We recommend using private packages, either via overlay-ports or via the upcoming registries feature, if you would still like to do so.

Once you have an alternate toolchain from apt or otherwise, you can consume it in vcpkg using `VCPKG_CHAINLOAD_TOOLCHAIN_FILE`[1].

[1] https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md#vcpkg_chainload_toolchain_file

**Comment by kafeg** [comment]
Ok, I understand the current policy. Thank you for explanation guys!

**Pull request closed without merging**
