### PR TITLE
[vcpkg] Correct UInt128 code 😇

### LINKED ISSUE #10582: Uint128 <<= not zero filling the LSW
By inspection at https://github.com/microsoft/vcpkg/blob/9b44e4768bf25e1ae07e6eaba072c1a1a160f978/toolsrc/src/vcpkg/base/hash.cpp#L79 it appears that UInt128 <<= is not zero filling the least significant word when the shift is >= 64.  The code giant strides (top=bottom;) but fails to zero fill bottom. There appears to a similar issue for >>=

The author (per git blame) confirms the problems.

**Environment**
Mark-1 eyeball

### PR DESCRIPTION
**Pull request by strega-nil**
`UInt128::operator<<(x, y)` should clear the bottom 64 bits of `x` if
`y >= 64`; however, we don't do this, and so we duplicate `x`'s bottom
bits into `x.top` instead of moving them. Similarly, we have the
opposite problem for `UInt128::operator>>`. This commit fixes these
latent bugs, which we weren't hitting because the thing we use them for
never actually shifts more than 64 bits.

Fixes #10582 :)

### CODE REVIEW

**Review by RobertHenry6bev — CHANGES_REQUESTED** [review]
I would write some unit tests too.

**Comment by strega-nil** [comment]
Oof, getting 504s from github when trying to download the code...

**Review by BillyONeal — APPROVED** [review]

**Pull request merged**
