### PR TITLE
[sdl1-mixer] new port

### PR DESCRIPTION
**Pull request by arbruijn**
Current github version, with custom msbuild files as with the sdl1 port and dependencies from vcpkg.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [x] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Review by LilyWangLL — APPROVED** [review]

**Comment by BillyONeal** [comment]
It looks like this is a complete build system replacement. Is there a specific reason the replacement is done with msbuild rather than with something like cmake? I'm nervous about this replacement not being stable across updates.

**Comment by arbruijn** [comment]
I assumed the sdl1 port would be a good example. but if cmake is preferred I can look into that.

**Comment by BillyONeal** [comment]
> I assumed the sdl1 port would be a good example. but if cmake is preferred I can look into that.

"copied from this other port" is a reasonable justification. This works, so I'm going to merge it as is, but would really appreciate CMake instead where possible.

Thanks!

**Comment by dg0yt** [comment]
IMO there are many old ports which are not good examples...
This msbuild stuff makes it hard for non-MSVC users to contribute.

**Pull request merged**
