### PR TITLE
[boinc] Add custom patch (copied from mainstream unreleased code) to support OpenSSL3

### PR DESCRIPTION
**Pull request by AenBleidd**
Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

### CODE REVIEW

**Comment by AenBleidd** [comment]
Any chance to get it reviewed and maybe even merged? ^^

**Review by JackBoosY — APPROVED** [review]
I think it's acceptable.

**Comment by BillyONeal** [comment]
I confirmed that this was merged upstream as https://github.com/BOINC/boinc/commit/689dc20ede9768377d4032ff8c70b58269c8dc9c

Thanks for the patch!

**Comment by BillyONeal** [comment]
(In the future if you include a link to upstream where it is landed to make it easy to check it will make review easier and as a result probably faster, thanks!)

**Pull request merged**
