### PR TITLE
[protobuf] upgrade to 3.5.0

### PR DESCRIPTION
**Pull request by thierryba**

### CODE REVIEW

**Comment by alexkaratarakis** [comment]
Thanks!

**Comment by jasjuang** [comment]
should bump up the version

**Comment by KindDragon** [comment]
and this break grpc port

**Comment by ras0219-msft** [comment]
Thanks! Fixed in master.

It looks like this mega commit[1] removed an export required for grpc. I've restored the export, which fixes the issue.

[1] https://github.com/google/protobuf/commit/13fd045dbb2b4dacea32be162a41d5a4b0d1802f#diff-a562eb561762203334271ae286ab875eL168

**Comment by thierryba** [comment]
Thanks for the fix

Le 25 nov. 2017 9:39 PM, "Robert Schumacher" <notifications@github.com> a
écrit :

**Pull request merged**
