### PR TITLE
[graphviz] Update to 7.0.0 

### PR DESCRIPTION
**Pull request by dg0yt**
- #### What does your PR fix?
  Updates graphviz.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  - Fixes arm64-windows. Probably this was a general cross-build problem: the `dot` must be run once to create plugin configuration. This used to fail, but now it is guarded (upstream), and a message is printed instead (portfile).
  - staticcrt unsupported due to use of plugin.
  - uwp unknown (cascade).
  - ci.baseline.txt unchanged.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  yes

### CODE REVIEW

**Comment by dg0yt** [comment]
osx suffered from https://gitlab.kitware.com/cmake/cmake/-/issues/16154#note_1220397 again.

**Comment by dg0yt** [comment]
Depends on  #27551

**Review by FrankXie05 — APPROVED** [review]

**Comment by dg0yt** [comment]
> @[FrankXie05](https://github.com/FrankXie05) added the requires:all-feature-testing

There are no features modeled in graphviz.

**Comment by JavierMatosD** [comment]
Thank you!

**Pull request merged**
