### PR TITLE
[nanovg] Add dependency port stb

### PR DESCRIPTION
**Pull request by JackBoosY**
Related issue https://github.com/microsoft/vcpkg/issues/8809

Changes:
1. Add dependency port stb to nanovg
2. It doesn't need to install stb headers when build nanovg, so remove the steps.
3. nanovg does not support uwp. 

Note: this port does not contain any feature.

### CODE REVIEW

**Comment by JackBoosY** [comment]
@xarthurx Could you help me to test it?

Thanks.

**Comment by xarthurx** [comment]
@JackBoosY 
If testing means to uninstall `nanovg` and `stb`, and then install `nanovg`, stb is installed as a dependency.

Everything works fine.

Thank you for the quick response.

**Comment by xarthurx** [comment]
Seems have issue?

**Comment by JackBoosY** [comment]
@xarthurx Nop, This port does not support Windows, and we need to install autoconf / automake on the OS X CI machine.

**Comment by xarthurx** [comment]
@PhoebeHui  Hi, sorry to bother you, but would you please review this?
I'm waiting for this PR so that @JackBoosY  can start fixing the `libigl` PR...

**Comment by JackBoosY** [comment]
@xarthurx We need to wait to fix the CI issue.

**Review by PhoebeHui — APPROVED** [review]

**Comment by PhoebeHui** [comment]
@xarthurx, thanks for reminding me, the changes looks good, I approved it, however, we are waiting for CI back online, after CI test pass, this PR should ready to merge.

**Comment by JackBoosY** [comment]
@dan-shaw This PR is ready to merge.

**Comment by dan-shaw** [comment]
LGTM although the CI is down again, and we trying to fix it as soon as we can. See #9203 #9216

**Review by dan-shaw — APPROVED** [review]

**Comment by xarthurx** [comment]
How is this merge going?

**Pull request merged**
