### PR TITLE
[cppgraphqlgen] Update to v4.5.2

### PR DESCRIPTION
**Pull request by wravery**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by jimwang118** [comment]
I get the following error when testing usage:
```
Error		CMake Error at F:/spdlog/installed/x64-windows/share/cppgraphqlgen/cppgraphqlgen-targets.cmake:70 (set_target_properties):
  The link interface of target "cppgraphqlgen::graphqlpeg" contains:

    taocpp::pegtl

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.		F:/spdlog/installed/x64-windows/share/cppgraphqlgen/cppgraphqlgen-targets.cmake	70	
```
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

**Comment by wravery** [comment]
> I get the following error when testing usage:
> ```
> Error		CMake Error at F:/spdlog/installed/x64-windows/share/cppgraphqlgen/cppgraphqlgen-targets.cmake:70 (set_target_properties):
>   The link interface of target "cppgraphqlgen::graphqlpeg" contains:
> 
>     taocpp::pegtl
> 
>   but the target was not found.  Possible reasons include:
> 
>     * There is a typo in the target name.
>     * A find_package call is missing for an IMPORTED target.
>     * An ALIAS target is missing.		F:/spdlog/installed/x64-windows/share/cppgraphqlgen/cppgraphqlgen-targets.cmake	70	
> ```

That sounds like it did not install or find the pegtl dependency.

On my local branch of `vcpkg`, I was able to install and use `cppgraphqlgen` 4.5.2 just fine in another project, with no additional dependencies on the command line. How are you testing it when you get this error?

**Comment by jimwang118** [comment]
I add the following content to `cmakelists`, and then the error I mentioned above will be reported when compiling.
I use the `CMAKE_TOOLCHAIN_FILE` and compiler configured by `vs2022`.
```
add_executable (testcppgraphqlgen "testcppgraphqlgen.cpp" "testcppgraphqlgen.h")

find_package(cppgraphqlgen CONFIG REQUIRED)
target_link_libraries(testcppgraphqlgen PRIVATE cppgraphqlgen::graphqlpeg cppgraphqlgen::graphqlcoro cppgraphqlgen::graphqljson cppgraphqlgen::graphqlclient)
```

**Comment by wravery** [comment]
Ah, OK. In all of my test projects I've already got a `find_package(PEGTL...)` command as well. This bug is in `cppgraphqlgen` itself, but it pre-dates this version bump. I entered https://github.com/microsoft/cppgraphqlgen/issues/288 to track that, I'll probably publish a 4.5.3 release soon with that change, so I'll close this PR and skip to that version in a new PR.

**Pull request closed without merging**
