### PR TITLE
[directx-shader-compiler] Add new port

### PR DESCRIPTION
**Pull request by JPMMaia**
Related issue Microsoft/DirectXShaderCompiler#715.

This uses `vcpkg_from_github()` to initialize the submodules. If the `--head` switch is passed when installing, it will clone the latest master of each submodule, instead of getting the versions specified by the latest DirectXShaderCompiler master submodules. Is there a way to solve this issue?

### CODE REVIEW

**Comment by cenit** [comment]
Using the spirv tools and headers already provided by vcpkg. I am not sure that installing them again under this port uncontrolled might be acceptable

**Comment by JPMMaia** [comment]
> Using the spirv tools and headers already provided by vcpkg. I am not sure that installing them again under this port uncontrolled might be acceptable

Looking at [DirectXShaderCompiler/external/CMakeLists.txt](https://github.com/microsoft/DirectXShaderCompiler/blob/master/external/CMakeLists.txt), it seems that we could set `DXC_SPIRV_HEADERS_DIR` and `DXC_SPIRV_TOOLS_DIR` to the corresponding source folders of spirv-headers and spirv-tools. 

So, I added `Build-Depends: spirv-headers, spirv-tools` to the CONTROL file. But now, how can we find the source folders of spirv-headers and spirv-tools? Is there a way to reference the source directories of the build dependencies from the port file? I looked at `buildtrees/spirv-headers/src/bbcf2ac77b-0815c889b0/`, but there's this hash. 

One possibility would be to use `file(GLOB)` to get a list of directories inside _buildtrees/spirv-headers/src/_, and choose the first directory of the list and set `DXC_SPIRV_HEADERS_DIR` to that path. However, that does sound a bit hacky. In addition, would it be possible that the _buildtrees_ directory is removed, but the package still be installed? If so, then this approach would not be reliable since it depends on the contents of _buildtrees_.

I looked at the documentation about handling submodules, and found [vcpkg_extract_source_archive](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_extract_source_archive.md), which says: 

> TARGET_DIRECTORY: This can be used to mimic git submodules, by extracting into a subdirectory of another archive.

On the other hand, [vcpkg_download_distfile](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_download_distfile.md) also says:

> The helper vcpkg_from_github should be used for downloading from GitHub projects.

So, in the end I ended up using [vcpkg_from_github](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_from_github.md). However, I also think that it should use the sources of the spirv-headers package already provided by vcpkg.

What would be the prefered approach? Should we just set `DXC_SPIRV_HEADERS_DIR` to a random directory inside `buildtrees/spirv-headers/src/`

**Comment by cenit** [comment]
Absolutely not, do not use buildtrees folder. that would be a road to disaster. You should point to installed packages :)
In fact, if you declare a dependency, you can assume it is installed before the dependent. 
No time now to check, but I think you should work on the DXSC toolchain to see if it’s possible to point to “system” package instead of using internal submodule. If not possible, it will require a patch to do so (and afterwards, please open a PR upstream trying to have it accepted)

**Comment by JPMMaia** [comment]
Thanks for the help @cenit.

I have been trying to create a patch, so that DirectXShaderCompiler's CMake can find vcpkg's installed packages (spirv-tools and spirv-headers). I also added these packages to `Build-Depends` on the CONTROL file. However, the vcpkg-Linux-PR build fails with the following message:

```
CMake Error at /ci/myagent/_work/2/s/installed/x64-linux/share/spirv-tools/spirv-tools-config.cmake:88 (message):
  The imported target "spirv-tools::SPIRV-Tools-opt" references the file

     "/ci/myagent/_work/1/s/packages/spirv-tools_x64-linux/lib/libSPIRV-Tools-opt.a"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/ci/myagent/_work/2/s/installed/x64-linux/share/spirv-tools/spirv-tools-config.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /ci/myagent/_work/2/s/scripts/buildsystems/vcpkg.cmake:256 (_find_package)
  external/CMakeLists.txt:24 (find_package)

```

What am I missing here? Any clues? Thanks in advance.

**Comment by JackBoosY** [comment]
Pinging @JPMMaia for response. Is work still being done for this PR?

**Comment by JPMMaia** [comment]
> 
> 
> Pinging @JPMMaia for response. Is work still being done for this PR?

Currently no. Unfortunately, I haven't had much time to solve some issues.

On Linux, we need to investigate why the cmake in the automated build fails to find spirv-tools::SPIRV-Tools-opt, although it is specified in the CONTROL file. Building locally worked for me.

On Windows, I'm having problems building locally using vcpkg, since it seems to fail to find the TAEG files from Windows 10 SDK. Either my system is not configured properly, or there might be a problem with [FindTAEF](https://github.com/microsoft/DirectXShaderCompiler/blob/master/cmake/modules/FindTAEF.cmake#L17).

**Comment by JackBoosY** [comment]
@JPMMaia Okay, if this pr is ready to review, please ping me.

Thanks.

**Comment by JackBoosY** [comment]
Closing this PR since it seems that no progress is being made. Please reopen if work is still being done.

**Pull request closed without merging**
