### PR TITLE
[hdf5] update to 1.12.1

### LINKED ISSUE #16203: [hdf5] Error: Building package hdf5:x86-windows failed with: BUILD_FAILED
```
Package: hdf5:x86-windows
Vcpkg version: 2021-01-13-768d8f95c9e752603d2c5901c7a7c7fbdb08af35
```
console log:
```
PS C:\src\vcpkg> .\vcpkg.exe install hdf5
Computing installation plan...
The following packages will be built and installed:
    hdf5[core,szip,zlib]:x86-windows -> 1.12.0
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\xc130\AppData\Local\vcpkg\archives\e8\e8f524cd6f0679420e8f0c8844caac1e61717b28.zip
Starting package 1/1: hdf5:x86-windows
Building package hdf5[core,szip,zlib]:x86-windows...
-- Using cached C:/src/vcpkg/downloads/HDFGroup-hdf5-hdf5-1_12_0.tar.gz
-- Cleaning sources at C:/src/vcpkg/buildtrees/hdf5/src/df5-1_12_0-060e97d1ee.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/src/vcpkg/downloads/HDFGroup-hdf5-hdf5-1_12_0.tar.gz
-- Applying patch hdf5_config.patch
-- Applying patch szip.patch
-- Using source at C:/src/vcpkg/buildtrees/hdf5/src/df5-1_12_0-060e97d1ee.clean
-- Configuring x86-windows-dbg
-- Configuring x86-windows-rel
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:144 (message):
    Command failed: C:/src/vcpkg/downloads/tools/cmake-3.19.2-windows/cmake-3.19.2-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v -j13
    Working Directory: C:/src/vcpkg/buildtrees/hdf5/x86-windows-dbg
    See logs for more information:
      C:\src\vcpkg\buildtrees\hdf5\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:27 (vcpkg_build_cmake)
  ports/hdf5/portfile.cmake:63 (vcpkg_install_cmake)
  scripts/ports.cmake:131 (include)


Error: Building package hdf5:x86-windows failed with: BUILD_FAILED
```

log file(C:\src\vcpkg\buildtrees\hdf5\install-x86-windows-dbg-out.log) content:
```
[1/347] C:\PROGRA~2\MICROS~1.0\VC\bin\AMD64_~2\cl.exe   -D_BIND_TO_CURRENT_VCLIBS_VERSION=1 -D_CONSOLE -D_CRT_SECURE_NO_WARNINGS -IC:\src\vcpkg\installed\x86-windows\include -IC:\src\vcpkg\buildtrees\hdf5\src\df5-1_12_0-060e97d1ee.clean\src -I. /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /Fosrc\CMakeFiles\H5make_libsettings.dir\H5make_libsettings.c.obj /Fdsrc\CMakeFiles\H5make_libsettings.dir\ /FS -c C:\src\vcpkg\buildtrees\hdf5\src\df5-1_12_0-060e97d1ee.clean\src\H5make_libsettings.c
[2/347] C:\PROGRA~2\MICROS~1.0\VC\bin\AMD64_~2\cl.exe   -D_BIND_TO_CURRENT_VCLIBS_VERSION=1 -D_CONSOLE -D_CRT_SECURE_NO_WARNINGS -IC:\src\vcpkg\installed\x86-windows\include -IC:\src\vcpkg\buildtrees\hdf5\src\df5-1_12_0-060e97d1ee.clean\src -I. /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /Fosrc\CMakeFiles\H5detect.dir\H5detect.c.obj /Fdsrc\CMakeFiles\H5detect.dir\ /FS -c C:\src\vcpkg\buildtrees\hdf5\src\df5-1_12_0-060e97d1ee.clean\src\H5detect.c
[3/347] cmd.exe /C "cd . && C:\src\vcpkg\downloads\tools\cmake-3.19.2-windows\cmake-3.19.2-win32-x86\bin\cmake.exe -E vs_link_exe --intdir=src\CMakeFiles\H5make_libsettings.dir --rc=C:\PROGRA~2\WI3CF2~1\8.1\bin\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\8.1\bin\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~1.0\VC\bin\AMD64_~2\link.exe  src\CMakeFiles\H5make_libsettings.dir\H5make_libsettings.c.obj  /out:bin\H5make_libsettings.exe /implib:bin\H5make_libsettings.lib /pdb:bin\H5make_libsettings.pdb /version:0.0 /machine:X86 /nologo    /debug /INCREMENTAL /subsystem:console  ws2_32.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
[4/347] cmd.exe /C "cd . && C:\src\vcpkg\downloads\tools\cmake-3.19.2-windows\cmake-3.19.2-win32-x86\bin\cmake.exe -E vs_link_exe --intdir=src\CMakeFiles\H5detect.dir --rc=C:\PROGRA~2\WI3CF2~1\8.1\bin\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\8.1\bin\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~1.0\VC\bin\AMD64_~2\link.exe  src\CMakeFiles\H5detect.dir\H5detect.c.obj  /out:bin\H5detect.exe /implib:bin\H5detect.lib /pdb:bin\H5detect.pdb /version:0.0 /machine:X86 /nologo    /debug /INCREMENTAL /subsystem:console  ws2_32.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
[5/347] cmd.exe /C "cd /D C:\src\vcpkg\buildtrees\hdf5\x86-windows-dbg && C:\src\vcpkg\buildtrees\hdf5\x86-windows-dbg\bin\H5detect.exe C:/src/vcpkg/buildtrees/hdf5/x86-windows-dbg/H5Tinit.c && C:\src\vcpkg\downloads\tools\cmake-3.19.2-windows\cmake-3.19.2-win32-x86\bin\cmake.exe -E touch C:/src/vcpkg/buildtrees/hdf5/x86-windows-dbg/gen_SRCS.stamp1"
FAILED: H5Tinit.c gen_SRCS.stamp1 
cmd.exe /C "cd /D C:\src\vcpkg\buildtrees\hdf5\x86-windows-dbg && C:\src\vcpkg\buildtrees\hdf5\x86-windows-dbg\bin\H5detect.exe C:/src/vcpkg/buildtrees/hdf5/x86-windows-dbg/H5Tinit.c && C:\src\vcpkg\downloads\tools\cmake-3.19.2-windows\cmake-3.19.2-win32-x86\bin\cmake.exe -E touch C:/src/vcpkg/buildtrees/hdf5/x86-windows-dbg/gen_SRCS.stamp1"
[6/347] cmd.exe /C "cd /D C:\src\vcpkg\buildtrees\hdf5\x86-windows-dbg && C:\src\vcpkg\buildtrees\hdf5\x86-windows-dbg\bin\H5make_libsettings.exe C:/src/vcpkg/buildtrees/hdf5/x86-windows-dbg/H5lib_settings.c && C:\src\vcpkg\downloads\tools\cmake-3.19.2-windows\cmake-3.19.2-win32-x86\bin\cmake.exe -E touch C:/src/vcpkg/buildtrees/hdf5/x86-windows-dbg/gen_SRCS.stamp2"
FAILED: H5lib_settings.c gen_SRCS.stamp2 
cmd.exe /C "cd /D C:\src\vcpkg\buildtrees\hdf5\x86-windows-dbg && C:\src\vcpkg\buildtrees\hdf5\x86-windows-dbg\bin\H5make_libsettings.exe C:/src/vcpkg/buildtrees/hdf5/x86-windows-dbg/H5lib_settings.c && C:\src\vcpkg\downloads\tools\cmake-3.19.2-windows\cmake-3.19.2-win32-x86\bin\cmake.exe -E touch C:/src/vcpkg/buildtrees/hdf5/x86-windows-dbg/gen_SRCS.stamp2"
ninja: build stopped: subcommand failed.
```

### PR DESCRIPTION
**Pull request by JackBoosY**
The upstream re-factoried its cmake build system, so:
1. Update to 1.12.1
2. Add feature utils
3. Set option `ALLOW_UNSUPPORTED` to `ON` when the features are mutually exclusive to avoid conflict.
4. update patches.
5. Re-factory code about pkgconfig.
6. Re-fcatory code about tool installation.

Fixes #16203.

### CODE REVIEW

**Comment by JackBoosY** [comment]
@KKKIIO Can you please test this PR?

Thanks.

**Review by dg0yt — CHANGES_REQUESTED** [review]
I will test on mingw as soon as time permits.

**Review by dg0yt — COMMENTED** [review]
With the mingw naming convention adjusted, I could complete a first mingw build and verified the pc file. I will let builds run down to port gdal.

**Review by NancyLi1013 — APPROVED** [review]

**Pull request merged**
