### PR TITLE
[pe-parse] update version to 2.1.0

### PR DESCRIPTION
**Pull request by yardenshafir**
**Describe the pull request**

- #### What does your PR fix?
  Updates pe-parse version to include new capabilities.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
   Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

### CODE REVIEW

**Comment by yardenshafir** [comment]
@microsoft-github-policy-service agree [company="Trail of Bits"]

**Comment by yardenshafir** [comment]
@microsoft-github-policy-service agree company="Trail of Bits"

**Comment by yardenshafir** [comment]
@microsoft-github-policy-service agree

**Review by MonicaLiu0311 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the update!

**Pull request merged**
