### PR TITLE
[vcpkg] Add dummy version.txt for vcpkg older than vcpkg_minimum_required.

### PR DESCRIPTION
**Pull request by BillyONeal**

### CODE REVIEW

**Comment by BillyONeal** [comment]
image

**Comment by BillyONeal** [comment]
We will leave this version.txt even after deleting everything else in toolsrc; and delete it and toolsrc maybe a year later or something like that.

**Comment by gvanem** [comment]
This must be one of the few Microsoft tool without any resource-section. And what would the version be if it had one?
`c:\> filever vcpkg.exe`

```...
 ProductVersion  9999.99.99.0
 FileVersion     9999.99.99.0
```

Or some string with the build-date and a silly git hash string?

**Comment by JackBoosY** [comment]
> This must be one of the few Microsoft tool without any resource-section. And what would the version be if it had one?
> `c:\> filever vcpkg.exe`
> 
> ```
>  ProductVersion  9999.99.99.0
>  FileVersion     9999.99.99.0
> ```
> 
> Or some string with the build-date and a silly git hash string?

cc @ras0219 @ras0219-msft

**Pull request merged**
