### PR TITLE
[swenson-sort] Add new port for sort.h

### PR DESCRIPTION
**Pull request by swenson**
[sort.h](https://github.com/swenson/sort) is a fast C header library with many different sorting algorithms.

There's not a build process, so the port is just copying the header file.

Most people usually just copied the header into their project, but I thought having a vcpkg might make it easier to use sort.h

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [x] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by swenson** [comment]
@microsoft-github-policy-service agree

**Comment by dg0yt** [comment]
Given that `sort` is a very generic word, you will probably be asked to rename the port to something like `swenson-sort`.  
(Disclaimer: I'm only a community member.)

Use `vcpkg x-add-version [--overwrite-version] <port-name>` to deal with the version registry, after committing all changes to `ports/<port-name>`.

**Comment by Cheney-W** [comment]
swenson-sort is a good name for this port.

**Comment by Cheney-W** [comment]
Moving the PR to draft. Please set it to "ready for review" once changes have been applied.

**Comment by swenson** [comment]
Thanks. I moved the package name to `swenson-sort`.

**Review by Cheney-W — APPROVED** [review]

**Pull request merged**
