### PR TITLE
[onnxruntime-gpu] Update to version 1.12.1

### PR DESCRIPTION
**Pull request by rinechran**
**Describe the pull request**

- #### What does your PR fix?
  Update version

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Review by FrankXie05 — DISMISSED** [review]

**Review by dg0yt — COMMENTED** [review]
This port lacks quotes around path expressions.

IMO future maintenance of  this port could benefit from using `${VERSION}` and a compact list of basenames to be handled. Looping over the list may make it easy to trim the install for release-only triplets.

**Comment by rinechran** [comment]
That's a good idea. I'll fix it

**Comment by FrankXie05** [comment]
Before `vcpkg` updates the scripts https://github.com/microsoft/vcpkg/pull/28522, we still need the function `vcpkg_minimum_required(VERSION 2022-10-12) # for ${VERSION}`

**Review by FrankXie05 — APPROVED** [review]

**Comment by FrankXie05** [comment]
Re-open this PR for re-run CI check.

**Review by FrankXie05 — APPROVED** [review]

**Pull request merged**
