### PR TITLE
[gn] Update to current version

### PR DESCRIPTION
**Pull request by bold84**
**Describe the pull request**

While trying to update the Skia port, I found that it doesn't build with vcpkg's version of GN. It seems to be too old.

This change may require updates to ports that use gn. 

- #### What does your PR fix?
  Fixes #...

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  all

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Doesn't look like it does anything

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by bold84** [comment]
So, how am I supposed to do this? 
Updating the Skia port to a newer version requires updating gn. But it seems that the old gn isn't compatible with the new Skia gn files.
Just one PR for all of it?

**Comment by JonLiu1993** [comment]
> So, how am I supposed to do this? Updating the Skia port to a newer version requires updating gn. But it seems that the old gn isn't compatible with the new Skia gn files. Just one PR for all of it?

@bold84 ,Thanks for your pr, you need commit a pr update them all together

**Comment by bold84** [comment]
@JonLiu1993 Than you for your response.
I’ll have a look at the PR you mentioned. Next time I’ll search for unfinished PRs.

**Comment by bold84** [comment]
Closing this PR, will continue updating in this PR: https://github.com/microsoft/vcpkg/pull/24066

**Pull request closed without merging**
