### PR TITLE
[many ports] Add more KF5 frameworks

### PR DESCRIPTION
**Pull request by wrobelda**
This adds ports for a whole bunch more KDE Frameworks 

- Which triplets are supported/not supported? Have you updated the CI baseline?
All default triplets should be supported

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes, except the requirement to publish the ports separately. However, these ports are for the most part a copy-and-paste, with some exceptions.

### CODE REVIEW

**Comment by NancyLi1013** [comment]
It seems that you also included some changes in this PR #13467. Such as update those ports to 5.73.

**Comment by wrobelda** [comment]
> It seems that you also included some changes in this PR #13467. Such as update those ports to 5.73.
> 
> Personally, you might forget to split new ports and updates.  Please let me know if you are intended to do like this.

Indeed this was intended. I will rebase against the master once the PR #13467 gets merged. This PR, which is still WIP, depends on those updated ports, which is why it also includes them.

**Comment by wrobelda** [comment]
@NancyLi1013 I see that all checks have passed, even though pretty much all of the ports I added or modified were skipped with CASCADE status due to some missing/failing dependency (which I haven't look into yet). Is this normal? Because to me that's a clear case of FALSE POSITIVE result. I'd expect the tests to end with "inconclusive" status or just fail in such case.

**Comment by NancyLi1013** [comment]
@wrobelda 
Just as you said, it is related with those dependencies. I noticed that `ecm ` was set as skip in ci.baseline.txt. 
Seems that all ports are required for `ecm`. So the current behavior is normal.

**Comment by NancyLi1013** [comment]
Please let me know if this PR is ready for review now.

**Comment by wrobelda** [comment]
> Please let me know if this PR is ready for review now.

Still a WIP. Few ports are missing and some need extra fixes.

**Comment by wrobelda** [comment]
@NancyLi1013 For the record, this is currently blocked by the #13518  and depends on #11776,  which in term depends on #12936

**Comment by NancyLi1013** [comment]
Hi @wrobelda 

Could you please spilt these changes in this PR into several PRs? Since there are a large amount of files here, which is more difficult to review.

You can add 2 new ports in one PR.

**Comment by wrobelda** [comment]
> Could you please spilt these changes in this PR into several PRs? Since there are a large amount of files here, which is more difficult to review.

Can do. However, all these depend on the other PR (https://github.com/microsoft/vcpkg/pull/13467) so I would appreciate if you could review and hopefully merge that one first.

**Comment by NancyLi1013** [comment]
Thanks for your kindly reminder.
I will try to review PR #13467 today.

**Comment by wrobelda** [comment]
As requested by @NancyLi1013, I will create separate PRs for these ports.

**Pull request closed without merging**
