### PR TITLE
Create VCPKG_NO_INSTALL variable

### PR DESCRIPTION
**Pull request by LRFLEW**
This one might take a little explanation.

This PR adds a new variable, `VCPKG_NO_INSTALL`, that can be used in a custom triplet file. When the variable is defined to `ON` (or another true value), the portfile for the library being installed will be skipped. (To prevent the Vcpkg tool from complaining, it add `PolicyEmptyPackage: enabled` to the BUILD_INFO file when this happens). The idea is that you can use the `PORT` macro in the triplet to disable building specific libraries. I can think of two use cases for this feature:

A number of libraries in Vcpkg have "soft" dependencies, where the dependency isn't required for installing the library, and at least some of the library's functionality can work without it. For example, Boost.ASIO has a dependency on OpenSSL. However, OpenSSL doesn't need to be present when installing Boost.ASIO, and it's only required if you use any of the classes in `boost::asio::ssl`. OpenSSL is a large library that takes a considerable about of time to compile. By adding this to a custom triplet, the user can avoid compiling OpenSSL if they aren't using the SSL features in Boost.ASIO:
```
if(PORT MATCHES "^openssl-")
    set(VCPKG_NO_INSTALL ON)
endif()
```
(Also, the ports for Boost are full of these sorts of soft dependencies to each other. In fact, if you compare the libraries included using Boost's BCP compared to Vcpkg, you can see that Vcpkg ends up including more libraries. This feature could also be used to create a whitelist of Boost libraries to avoid installing more than the user really needs)

The second use is more for the non-Windows platforms. macOS, Linux, etc. usually have a number of libraries included in the OS that developers can make use of. For example, macOS includes both zlib and bzip2 as libraries that the user can use. If the user doesn't build zlib and bzip2 through Vcpkg, then libraries that depend on it, like libpng and freetype, will use the system-installed version instead. For this example, the user would add this to their custom triplet:
```
if(PORT STREQUALS zlib OR PORT STREQUALS bzip2)
    set(VCPKG_NO_INSTALL ON)
endif()
```

### CODE REVIEW

**Comment by LRFLEW** [comment]
I went ahead and added this new variable to the documentation as well. Let me know if you want me to change anything or elaborate more in the documentation.

**Comment by LRFLEW** [comment]
I rebased on top of the current master branch, as my other PR ended up creating a merge conflict. It would be nice to get some feedback on this soon.

**Comment by LRFLEW** [comment]
Can I get some sort of feedback on this? It's been almost 2 months now without any sort of response from Microsoft. Even a simple "this won't be considered" would be better than silence. I'm assuming this slipped through the cracks, and wasn't seen (or at least not seen by the right person). I'm going to ping @ras0219-msft who handled my previous PR's in case this is the case.

I made this PR because it was important for my use case (which is the 2nd use case I mentioned). Getting this PR (or another one that handles the same use case) merged is important for me to be able to use vcpkg in my project.

**Comment by PhoebeHui** [comment]
@LRFLEW, thanks for contributing to vcpkg! All triplets build successfully.

**Comment by PhoebeHui** [comment]
Some thoughts:
 First case: we can add a feature 'ssl' for Boost.ASIO which depend on OpenSSL, then the users can decide whether use ssl or not. And OpenSSL will not be built if user doesn't use ssl.
Second case: Some ports doesn't have cmake config or targets file, VCPKG help export them, and find these libraries correctly when use them, If we use the system-installed version instead, there is no guarantee to find these libraries. More over, some link issue or conflict issue may happen to use dependency libraries.

**Comment by Neumann-A** [comment]
Personally I thing this PR can be closed because the same can be achieved by rerouting `CURRENT_PORT_DIR` to a dummy directory from the triplet file. 
`include(${CMAKE_TRIPLET_FILE})`
is called before 
`include(${CURRENT_PORT_DIR}/portfile.cmake)`
but after any check on `CURRENT_PORT_DIR`. So `CURRENT_PORT_DIR` can just be rerouted to a dummy/empty protfile which just sets the policy

**Comment by PhoebeHui** [comment]
@strega-nil, what do you think about this PR?

**Comment by strega-nil** [comment]
I think given that this is not a usecase we want to support in lieu of features, and that it can be done via @Neumann-A's hack for unsupported usecases, it should be closed. However, I really appreciate the thought that went into this! Thanks @LRFLEW :)

**Comment by BillyONeal** [comment]
As per aforementioned discussion, closing.

**Comment by LRFLEW** [comment]
Just wanted to leave a comment in case anybody ends up here somehow. While @Neumann-A's suggestion *does* work (I tested it), it seems like the more "supported" option would be to use [port overlays](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md) to get vcpkg to use the dummy portfile.

For example, if you wanted to use a system-installed zlib, you could create the file `dummy-ports/zlib/portfile.cmake` containing just the line `set(VCPKG_POLICY_EMPTY_PACKAGE enabled)` and pass `--overlay-ports=dummy-ports` to vcpkg. If you do this, make sure that pkg-config has a config file for the project(s) being replaced with dummy builds (something that's an issue for macOS in some cases) and to append the system libraries being used to `VCPKG_SYSTEM_LIBRARIES`.

**Pull request closed without merging**
