### PR TITLE
Azure-IoT-Sdk for C release 2020-01-22

### PR DESCRIPTION
**Pull request by ewertons**
Azure-IoT-Sdk for C release 2020-01-22

### CODE REVIEW

**Comment by ewertons** [comment]
Hi folks, good morning. Please let us know if the failure above requires our attention.

**Comment by JackBoosY** [comment]
Hi @ewertons, it seems that there are some regressions, please download and check failure logs [here](https://dev.azure.com/vcpkg/public/_build/results?buildId=27093&view=artifacts&type=publishedArtifacts).

**Review by JackBoosY — APPROVED** [review]

**Comment by vicroms** [comment]
@ewertons 
I created a PR to fix this issue once and for all, can you take a look at it?

https://github.com/Azure/azure-c-shared-utility/pull/424

**Comment by JackBoosY** [comment]
@vicroms No...we have not tested features.

**Pull request merged**
