### PR TITLE
[pango] update to 1.40.5, enable static build

### PR DESCRIPTION
**Pull request by Mixaill**

### CODE REVIEW

**Comment by codicodi** [comment]
Note that supplied config.h for windows unconditionally exports symbols: https://github.com/GNOME/pango/blob/6c5d1d35061a91c3c0792f7720da3f8308ebff65/config.h.win32.in#L150.
Could you find a way to disable this behaviour when building static library?

**Comment by madebr** [comment]
@Mixaill @codicodi 
Does this fix the export symbol problem?
Add the following code in `orts/pango/portfile.cmake`:
```
if (VCPKG_LIBRARY_LINKAGE STREQUAL static)
    file(APPEND "${SOURCE_PATH}/config.h.win32.in" "#undef _PANGO_EXTERN\n")
    file(APPEND "${SOURCE_PATH}/config.h.win32.in" "#define _PANGO_EXTERN __attribute__((visibility("default"))) __declspec(dllimport) extern\n")
endif()
```

**Comment by codicodi** [comment]
I don't think MSVC understands attribute syntax. Also this would get appended every build, affecting later dynamic ones. Something like this should work though:
```
if (NOT EXISTS "${SOURCE_PATH}/config.h.win32.fixed")
    file(APPEND "${SOURCE_PATH}/config.h.win32" 
       "#ifndef _WINDLL
        #undef _PANGO_EXTERN
        #define _PANGO_EXTERN
        #endif\n")
    file(WRITE "${SOURCE_PATH}/config.h.win32.fixed" "")
endif()
```

**Comment by ras0219-msft** [comment]
The patch definitely looks like the right way to fix this, good work! 🥇

**Pull request merged**
