### PR TITLE
Openssl version bump 1.0.2s

### PR DESCRIPTION
**Pull request by the-j0k3r**
re: #6049 

@NancyLi1013 @heydojo @Bo98 

https://github.com/Microsoft/openssl has not published any packages for 1.0.2s so openssl-uwp is not part of this update

I closed #6049 due to some glitch in the rebase, I tried solving the conflicts but it was never ending.

So lets try this again.

### CODE REVIEW

**Comment by Bo98** [comment]
:+1:

Good to see we can see the build logs. I assume the failures in the macOS and Linux builds are just teething issues from changing the CI system.

**Comment by Rastaban** [comment]
Yup, we had some issues with the CI system.  We are cleaning it out and will rerun the job.

**Comment by the-j0k3r** [comment]
Green light, finally =)

**Comment by grdowns** [comment]
Fantastic. Thanks for your patience, @the-j0k3r!

**Pull request merged**
