### PR TITLE
[jxrlib] Update port

### PR DESCRIPTION
**Pull request by PhoebeHui**
Related to https://github.com/microsoft/vcpkg/issues/8511
1. Update the version
2. Remove License since the latest commit already contains License.

### CODE REVIEW

**Comment by cenit** [comment]
just a quick question: is the port pointing towards the official source? It doesn't look so, it seems a clone by a user, and so not perfectly under control. Why aren't we using the official link? https://codeplexarchive.blob.core.windows.net/archive/projects/jxrlib/jxrlib.zip

**Comment by PhoebeHui** [comment]
It switched to GitHub from [0e254766f](https://github.com/microsoft/vcpkg/commit/0e254766fd6f58208215ac50b87e8c845fc58033#diff-64fdf0dd08c6391477519ff87457c508), I'm not sure why.

**Comment by cenit** [comment]
I also don't know why. I'd prefer to have code from official source. Homebrew (just checked) uses the link I provided above, not from this 4creators' repository

**Comment by PhoebeHui** [comment]
I tried to download https://codeplexarchive.blob.core.windows.net/archive/projects/jxrlib/jxrlib.zip manually, however, it reported as 'unsafe website'.

**Comment by cenit** [comment]
wow, windows.net is an official microsoft website, which used to host codeplex........

**Comment by PhoebeHui** [comment]
Thanks cenit, I downloaded it through VPN.

I think it might due to codeplex announced that the site and servers wouldn't run on December 15th, 2017([Shutting down CodePlex](https://devblogs.microsoft.com/bharry/shutting-down-codeplex/)), 
Then Alex switched it to GitHub.

There isn’t currently any plan to have an end date for the archive. however I considered if it's safe to download it from codeplex archive now. @dan-shaw, any thoughts?

**Comment by cenit** [comment]
@dan-shaw let's not loose track that this port is downloaded from an unofficial source!

**Pull request merged**
