### PR TITLE
[ci.baseline.txt] colmap:x64-windows-static and symengine:arm64-windows now pass

### PR DESCRIPTION
**Pull request by ras0219-msft**

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]
I'm curious why our pipeline tests didn't report this issue the last time we modified it.

**Comment by cenit** [comment]
ci.baseline.txt is considered truth by test pipelines ;)

**Comment by ras0219-msft** [comment]
These marked-fail-but-passes issues are reported by the daily CI (https://dev.azure.com/vcpkg/public/_build/results?buildId=66382&view=results), not by PR testing

**Comment by BillyONeal** [comment]
Thanks <3

**Pull request merged**
