### PR TITLE
[qt5-base,qt5-tools,qt5-doc] Fix dependencies, enable qdoc

### PR DESCRIPTION
**Pull request by dg0yt**
- at-spi2-core used to be satisfied by a system package in the linux CI image, noticed in the host build in android CI.
- dbus used to be provided by a system dev package in the linux CI. The automatic configuration chooses "linked" mode in this case. With the system package remove from CI, this auto configuration created an installation order dependency due to the lack of a dbus dependency.  Noticed in some CI runs, e.g. https://github.com/microsoft/vcpkg/pull/38618.
- libclang probably became a dependency for qdoc with 5.15, but nobody noticed.
- pcre2 has a default feature jit which is causing problems, #38604. This PR unblocks opt-put from pcre2[jit] in qt5-base.

### CODE REVIEW

**Comment by dg0yt** [comment]
CC @tsondergaard for dbus.

**Comment by dg0yt** [comment]
I reverted the `-dbus-linked` change. 
I still wonder if we should explicitly pass `-dbus=runtime` to avoid an accidental switch to linked mode with uncontrolled installation order.

**Comment by MonicaLiu0311** [comment]
qt5-tools
-
Feature `qdoc` is tested successfully in the following triplet:
```
x86-windows
x64-windows
x64-windows-static
```

**Review by MonicaLiu0311 — DISMISSED** [review]

**Comment by tsondergaard** [comment]
> I reverted the `-dbus-linked` change. I still wonder if we should explicitly pass `-dbus=runtime` to avoid an accidental switch to linked mode with uncontrolled installation order.

I agree with being explicit. A linux developer may have dbus-devel installed via the system package manager and we don't want that to be auto-detected and used.

**Comment by dg0yt** [comment]
> I agree with being explicit. A linux developer may have dbus-devel installed via the system package manager and we don't want that to be auto-detected and used.

I will add explicit control then. 
It is not just "linux developers": We see x64-linux CI regression at the moment, downstream from qt5-base and qtbase. The auto-linking used to be hidden by the fact that the CI image had dbus devel packages installed, but we removed them in favor of the dbus port.

**Comment by dg0yt** [comment]
OTOH "linked" might be the right choice for linux as long as it is linked anyways via at-spi2-core (accessibility).

**Comment by tsondergaard** [comment]
I opened #37945 a while back because the implicit use of "-dbus=runtime" meant that the dbus-1-3.dll was not installed with VCPKG_APPLOCAL_DEPS=ON.

I think it should probably be like this: "dbus-linked" is a feature and when it is enabled qtbase should build with "-dbus=linked" and "dbus" should be listed as a dependency. If this feature is not set qt configure should be built explicitly with "-dbus=runtime" to avoid detecting system-installed dbus-devel.

**Comment by dg0yt** [comment]
I'm not convinced that dbus linkage should be controlled by a feature when generally linkage is controlled by the triplet. The change I added now chooses `linked` for linux (to enforce consistency with at-spi2-core), and `runtime` otherwise. The manifest has the corresponding explicit dependency for linux.

**Comment by tsondergaard** [comment]
Will you make the same changes for the Qt 6 version, qtbase?

**Comment by dg0yt** [comment]
> Will you make the same changes for the Qt 6 version, qtbase?

No, because I still have more qt5 stuff to finish. But it must be ported quickly, indeed.

**Review by MonicaLiu0311 — APPROVED** [review]

**Pull request merged**
