### PR TITLE
[bullet3] Remove vcpkg_fail_port_install.

### PR DESCRIPTION
**Pull request by BillyONeal**
The supports expression and the portfile.cmake disagreed.

Supports: `!((windows | linux) & (arm | uwp))`
Portfile: `osx | !(arm | arm64 | uwp)`

If we demorgan the supports expression we get something closer to the portfile:
`!(windows | linux) | !(arm | uwp)`

If we take "`!(windows | linux)`" to mean that the author meant "osx", and assume arm64 implies arm, we end up with:

osx | !(arm | uwp)

In support of: https://github.com/microsoft/vcpkg/pull/21502

### CODE REVIEW

**Review by FrankXie05 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the review @FrankXie05 :D

**Comment by FrankXie05** [comment]
@BillyONeal After you delete the content of the baseline, whether to overwrite the content of the git tree of `versions/b-/bullet3.json` again?  :)

**Comment by BillyONeal** [comment]
> @BillyONeal After you delete the content of the baseline, whether to overwrite the content of the git tree of `versions/b-/bullet3.json` again? :)

ci.baseline.txt isn't part of the version database.

**Comment by FrankXie05** [comment]
@BillyONeal oh, my bad. I don't see you modifying the baseline halfway through。

**Comment by BillyONeal** [comment]
> @BillyONeal oh, my bad. I don't see you modifying the baseline halfway through。

Yeah, I didn't think about it until @JackBoosY's comment on another PR so I double checked before clicking the merge button here :)

**Comment by bwrsandman** [comment]
Sorry to comment on a closed PR but why is arm disabled? There shouldn't be any issues with building for Android as it is listed as supported on their github.

**Comment by BillyONeal** [comment]
> Sorry to comment on a closed PR but why is arm disabled? There shouldn't be any issues with building for Android as it is listed as supported on their github.

I don't think most of what we've done in terms of determining what ports support what has considered Android; I observe that MacOS also allows ARM which may have been done for iOS?

With this change I was trying to keep the behavior of the port the same; if someone shows that it works elsewhere a PR changing the supports expression to be consistent with what upstream does would be welcome.

**Pull request merged**
