### PR TITLE
 [gdal] Add libspatialite build-dependency

### PR DESCRIPTION
**Pull request by MelodyD**
reference https://github.com/Microsoft/vcpkg/pull/3389

### CODE REVIEW

**Comment by NancyLi1013** [comment]
@MelodyD, could you also bump the version in CONTROL file?

**Comment by grdowns** [comment]
Hey @MelodyD, thanks for the PR (and @freol35241 for the original work). It seems like `libspatialite` should be added as a feature, as according to `gdal`'s documentation it is an optional dependency that is turned on by explicitly linking the `libspacialite` libraries. It sounds like something that users might not necessarily want to opt into. Is using `libspacialite` a standard configuration for users and is it worth opt-ing users into it by default?

**Comment by MelodyD** [comment]
@grdowns Thanks for your great work. I‘m not sure whether it is worth configuring  by default for all users, but `libspatialite` is a very useful extension of 'gdal', and `spatialite` is widely used. At first, i want to option it by setting compilation parameters while installing package , but it seems like no method to do it.In my opinion, i suggest option `libspatialite` by default.

**Comment by Rastaban** [comment]
If you think the feature is usefull enough that most users of gdal would want it enabled by default then it can make it a default feature in the CONTROL file.  See https://github.com/Microsoft/vcpkg/blob/master/ports/cpprestsdk/CONTROL as an example.  This way it can still be opt-out.

**Comment by grdowns** [comment]
Hey @MelodyD, I added `libspatialiate` as a feature to `gdal`. You can install it via `vcpkg install gdal[libspatialite]`. Thanks for the contribution!

**Comment by MelodyD** [comment]
@grdowns Thank you very much!

**Pull request merged**
