### PR TITLE
Remove a ')' character in the documentation

### PR DESCRIPTION
**Pull request by duanqn**
**Describe the pull request**

- What does your PR fix?
This PR removes a ')' character that should not be there. It also decreases the repo size by 1 byte.
- Which triplets are supported/not supported? Have you updated the CI baseline?
N/A - documentation change
- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

### CODE REVIEW

**Comment by JackBoosY** [comment]
Please download [this diff file](https://dev.azure.com/vcpkg/public/_build/results?buildId=50119&view=artifacts&pathAsName=false&type=publishedArtifacts) and apply it, then commit the changes.

**Comment by duanqn** [comment]
> Please download [this diff file](https://dev.azure.com/vcpkg/public/_build/results?buildId=50119&view=artifacts&pathAsName=false&type=publishedArtifacts) and apply it, then commit the changes.

@JackBoosY That patch would completely revert my change. Why would vcpkg enforce the extra ')' ?

**Comment by duanqn** [comment]
Also I don't understand why this triggers format-manifest. I only touched a Markdown file.

**Comment by JackBoosY** [comment]
@duanqn Our documents are generated automaticlly.

**Comment by JackBoosY** [comment]
@duanqn Can you please re-sign CLA?

Thanks.

**Comment by duanqn** [comment]
I've signed the CLA, thanks!

**Review by JackBoosY — APPROVED** [review]

**Comment by JonLiu1993** [comment]
@vicroms ，This pr is ready to merge

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
