### PR TITLE
[llvm] add in clang and enable tools

### PR DESCRIPTION
**Pull request by jasjuang**
This is a continuation of #1946. Not sure why it's closed automatically after the force push to accommodate 4228e1e.

### CODE REVIEW

**Comment by xoviat** [comment]
Should clang be optional?

**Comment by jasjuang** [comment]
@xoviat See https://llvm.org/docs/GettingStarted.html. There is no [optional] tag for clang.

**Comment by fcharlie** [comment]
Please update llvm to 5.0.1.

**Comment by ras0219-msft** [comment]
Thanks for the PR! I did some further fixes to better enable the clang cmake config files.

@fcharlie Let's get this updated in a separate PR! I'd be happy to review it if you submitted one :)

**Comment by fcharlie** [comment]
@ras0219-msft  see https://github.com/Microsoft/vcpkg/pull/2519

**Pull request merged**
