### PR TITLE
Allow pkgconfig acquisition and fix some packages for its use (1/3)

### PR DESCRIPTION
**Pull request by bagong**
This acquires pkg-config lite (the version without additional requirements) and fixes libsndfile, flac, fftw3 and ffmpeg for its use.

This is the first PR in a group of interdependent PRs: pkgconfig, waf -> aubio

While pkg-config may be questioned as not vcpkg conform I think it is useful for backwards compatibility. I think packages with broken pkg-config support (like the ones touched here) could be gradually updated as required.

### CODE REVIEW

**Comment by ras0219-msft** [comment]
One big issue with pkg-config (as far as I'm aware) is that it isn't relocatable. The .pc files have hardcoded paths which will break as soon as you try to use Vcpkg over a network share or move it to a new directory or use `subst` to remount it.

Another is that this will probably not handle debug mode includes correctly. In every port that generates CMake package config files, we have to fix this. I believe pkg-config will have the same issue, but with far less motivation to fix it.

What about simply generating the .pc files on demand inside the aubio build? You could just stamp out `.pc` files that match exactly what's required (and individually for debug and release!), which would completely fix the problem.

**Comment by bagong** [comment]
> One big issue with pkg-config (as far as I'm aware) is that it isn't relocatable. The .pc files have hardcoded paths which will break as soon as you try to use Vcpkg over a network share or move it to a new directory or use subst to remount it.

Both are good points. I didn't think of relocation. I was a aware of the includes issue, but thought it might not relevant because vcpkg provides the corrects paths anywas. Aubio finds its header in the debug build too...
So construct fake pc-files on the fly? That's a creative and amusing idea, I'll give it some thought! ;)

**Comment by ras0219-msft** [comment]
I'm also going to take a stab at a buildsystem replacement for aubio -- it looks like it's honestly just "*.c"[1], which makes for an _extremely_ short CMakeLists.txt :).

[1] https://github.com/aubio/aubio/blob/3c230fae309e9ea3298783368dd71bae6172359a/src/wscript_build#L15

**Comment by bagong** [comment]
As to portability: at second though I am not sure there is a problem: at build-time the pc-files are generated from templates which use the proper paths for the build, of course, the prefix is generated as required for the build (except for include in debug, and in practice it doesn't seem to be an issue). At runtime (which is where relocation is relevant, right?) they are not used anymore?

To create fake ones nevertheless seems attractive, it makes the build independent of future changes...

As to the include problem: feels like the fact that you don't have includes in the debug branch might be a problem in other cases too? I guess you're trying to avoid code duplication? But I've been wondering what happens if somebody just want's to add the debug branch installed/triplet/debug to a build via cmake_prefix_path - there is a potential problem, isn't there? At least for simplicity... Maybe it would make sense to create junctions to the release include-folder in the debug branch as well?

**Comment by bagong** [comment]
@ras0219-msft , sounds great! ;)

**Comment by ras0219-msft** [comment]
I think we can currently continue on our strategy of buildsystem-replacement for libraries that currently rely on pkgconfig (I believe there's diminishingly few of these).

Thanks for the PR anyway!

**Pull request closed without merging**
