### PR TITLE
[liburing] Update to 2.7

### LINKED ISSUE #40621: liburing update to 2.7
### Library name

liburing

### New version number

2.7

### Other information that may be useful (release notes, etc...)

Bug fixes since April 2024 + sync to kernel 6.10 (aligned with Ubuntu Noble kernel):

https://github.com/axboe/liburing/releases/tag/liburing-2.7

### PR DESCRIPTION
**Pull request by dg0yt**
Fixes https://github.com/microsoft/vcpkg/issues/40621

### CODE REVIEW

**Comment by Cheney-W** [comment]
image

**Comment by Cheney-W** [comment]
@dg0yt Could you please help modify the deprecated license? Thank you!

**Comment by dg0yt** [comment]
> @dg0yt Could you please help modify the deprecated license? Thank you!

The project's information maps exactly to the deprecated idenitifier: It is unclear if it is `-only` or `-or-later`. Therefore this PR will not change that field.

**Review by Cheney-W — APPROVED** [review]

**Pull request merged**
