### PR TITLE
Fix aws-checksums not building on Windows

### LINKED ISSUE #21081: Broken usage of aws-cpp-sdk v2
Continuation of https://github.com/microsoft/vcpkg/issues/20252

On windows try:
.\vcpkg.exe install aws-sdk-cpp[cloudformation,ssm,s3,ec2]:x64-windows

The result:
```
Error: aws-checksums[core] is only supported on '!arm & !windows'
```

https://github.com/microsoft/vcpkg/blob/master/ports/aws-checksums/vcpkg.json#L6

Why is windows not supported?

### PR DESCRIPTION
**Pull request by xanather**
**Describe the pull request**
Potential typo fix. Fix aws-checksums compiling on Windows

- #### What does your PR fix?  
https://github.com/microsoft/vcpkg/issues/21081

### CODE REVIEW

**Comment by JonLiu1993** [comment]
@xanather ,Could you please sign CLA?

**Comment by xanather** [comment]
Signed it. As dg0yt was saying though should this be !(arm & windows) rather than !(arm)?

https://github.com/microsoft/vcpkg/issues/21081#issuecomment-955425696

**Comment by JonLiu1993** [comment]
> Signed it. As dg0yt was saying though should this be !(arm & windows) rather than !(arm)?
> 
> [#21081 (comment)](https://github.com/microsoft/vcpkg/issues/21081#issuecomment-955425696)

@xanather ,I think! (arm) might be more appropriate

**Review by JonLiu1993 — APPROVED** [review]

**Comment by xanather** [comment]
This OK to merge? If not willing to amend.

**Pull request merged**
