### PR TITLE
[entt] Update to 3.5.1

### PR DESCRIPTION
**Pull request by Vennor**
Bumping version to the newest release.

### CODE REVIEW

**Review by NancyLi1013 — APPROVED** [review]

**Comment by Vennor** [comment]
Looks like there's [3.5.1](https://github.com/skypjack/entt/releases/tag/v3.5.1) already. Should we just skip 3.5.0 and update to 3.5.1 in this PR?

**Comment by BillyONeal** [comment]
@Vennor Up to you

**Comment by Vennor** [comment]
@BillyONeal, ok, thanks! Updated to 3.5.1 then.

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
