### PR TITLE
[hdf5] Use cmake wrapper to ensure consuming libraries link to szip

### PR DESCRIPTION
**Pull request by seanwarren**
For static build, libraries consuming hdf5 do not include szip. 
This PR uses a wrapper to ensure szip is linked correctly

### CODE REVIEW

**Comment by Rastaban** [comment]
I am seeing new build failures in a few of the ports that depend on hdf5.  Are you able to take a look at these?  Let me know if you need me to attach the logs:

```
 Processing x64-linux                      588 vs 589
     kealib                        **regression**                Fail vs Pass
 Processing x64-osx                        579 vs 580
     kealib                        **regression**                Fail vs Pass
 Processing x64-windows-static             758 vs 762
     highfive                      **regression**                Fail vs Pass
     kealib                        **regression**                Fail vs Pass
     matio                         **regression**                Fail vs Pass
     netcdf-cxx4                   **regression**                Fail vs Pass
```

**Comment by seanwarren** [comment]
@Rastaban, thanks. This regression was caused by the wrapper overriding the hdf5 handling code in vcpkg.cmake (which remapped static-shared as required). I've now moved this code into the wrapper file which has resolved this regression (on my computers at least!)

**Comment by Rastaban** [comment]
It looks like that fixed it for all the ports that were failing earlier, now I see vtk on x64-windows and x86-windows failing.  Let me know if you need to to attach logs files.

**Comment by seanwarren** [comment]
I think that is caused by forcing hdf5 to search in config mode, I've modified this now and vtk:x64-windows is building correctly

**Comment by Rastaban** [comment]
The state as of the last checkin:
```
Processing x64-linux                      593 vs 595
     netcdf-c                      **regression**                Fail vs Pass
     netcdf-cxx4                                                 Skip vs Pass
 Processing x64-osx                        580 vs 584
     highfive                      **regression**                Fail vs Pass
     kealib                        **regression**                Fail vs Pass
     netcdf-c                      **regression**                Fail vs Pass
     netcdf-cxx4                                                 Skip vs Pass
 Processing x64-windows-static             762 vs 765
     highfive                      **regression**                Fail vs Pass
     kealib                        **regression**                Fail vs Pass
     netcdf-cxx4                   **regression**                Fail vs Pass

```

**Comment by seanwarren** [comment]
@Rastaban - I've successfully installed the following packages:

x64-osx: highfive, kealib, netcdf-c netcdf-cxx4
x64-windows-static: highfive, kealib, netcdf-cxx4

At the moment I can't easily test on linux
Are you able to provide any more information about why these packages are failing on the CI server?

Thanks

**Comment by Rastaban** [comment]
Sure!  These are some of the logs:
[config-x64-linux-dbg-err.log](https://github.com/Microsoft/vcpkg/files/2928666/config-x64-linux-dbg-err.log)
[config-x64-linux-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2928667/config-x64-linux-dbg-out.log)

**Comment by seanwarren** [comment]
Third time lucky! Thanks for your help merging this

**Pull request merged**
