### PR TITLE
[port] Added yaml-cpp

### PR DESCRIPTION
**Pull request by Wakusei**
Added yaml-cpp.
#308

### CODE REVIEW

**Comment by alexkaratarakis** [comment]
Looks good!
If you can take a few minutes to sign the cla, we'll merge this right in!

**Comment by Wakusei** [comment]
I thought I finished signing, but I was on the way. I've just signed just a few seconds ago.

**Comment by alexkaratarakis** [comment]
Hmm, this is weird, the bot did not pick up the signing. Normally, it picks it up instantly when you sign and replaces the red cla-required tag with a green cla-signed tag. 
Could you try one more time? Sorry about this.

**Comment by barcharcraz** [comment]
I'm going to go ahead and add support for installing the cmake config files, the library is not very useful if you can't find it!

**Comment by barcharcraz** [comment]
VCPKG calls export(PACKAGE) which means we have trouble detecting both the debug and the release packages. Maybe adding CMAKE_EXPORT_NO_PACKAGE_REGISTRY to the build options would be a good idea.

glfags does this too

**Comment by Wakusei** [comment]
I signed again, but the bot didn't react.

@barcharcraz I'll try to fix.

**Comment by Wakusei** [comment]
I got an e-mail with a following subject.
"Completed: Contribution License Agreement from Microsoft"
I think I finished correctly.

**Comment by Wakusei** [comment]
I sent an email to CLA address. I'm trying to solve the CLA problem.

**Comment by ras0219-msft** [comment]
Thanks, I'll also follow up internally and see what the issue is. We may be delayed until after the Thanksgiving holiday, however, so apologies in advance!

**Comment by ras0219-msft** [comment]
@Wakusei It looks like the CLA bot is back in action, could you please resubmit this as a new PR (no code changes needed)?

**Comment by Wakusei** [comment]
@ras0219-msft I see. I'll reopen the pull request.

@barcharcraz 
Would you tell me why cmake config files are needed in the result package directory?
They are important for using the library?
The file you meant is yaml-cpp-config.cmake?

**Comment by alexkaratarakis** [comment]
@barcharcraz @ras0219-msft @Wakusei 
This is now merged as #375

**Pull request closed without merging**
