### PR TITLE
[wtl] Add two "post-release updates".

### PR DESCRIPTION
**Pull request by chrullrich**
See https://sourceforge.net/projects/wtl/files/WTL%2010/WTL10%20Post-Release%20Updates.txt/download

### CODE REVIEW

**Comment by chrullrich** [comment]
> This is a new experimental fast check for PR issues. Please let us know if this bot is helpful!

As long as this feature is entirely undocumented, I do not think it is particularly helpful, no.

I could not immediately find anything that describes what it does, what it is good for, or even who it is addressed to (i.e. whether I am actually supposed to do what it says), and `x-add-version` is not in vcpkg's usage message.

**Review by JackBoosY — CHANGES_REQUESTED** [review]
Please run command `vcpkg x-add-version --all` then commit the changes.

**Comment by BillyONeal** [comment]
>As long as this feature is entirely undocumented, I do not think it is particularly helpful, no.

FWIW, it did ask you to run the 'magic undocumented command line' in the text but our diagnostics can almost always get better.

**Comment by BillyONeal** [comment]
Thanks for the patches!

**Pull request merged**
