### PR TITLE
[azure-iot-sdk-c] C SDK release 2019-12-11

### PR DESCRIPTION
**Pull request by ewertons**
[azure-iot-sdk-c] C SDK release 2019-12-11

### CODE REVIEW

**Review by dan-shaw — APPROVED** [review]

**Comment by dan-shaw** [comment]
@ewertons LGTM waiting for the MacOS and Windows pipeline to get fixed

**Comment by ewertons** [comment]
Thanks @dan-shaw .
This is for an official release of our SDK, so sending you good wishes to help with the fixes.

**Comment by ewertons** [comment]
This PR will need to be resubmitted.

**Comment by ewertons** [comment]
Replaced by https://github.com/microsoft/vcpkg/pull/9302

**Pull request closed without merging**
