### PR TITLE
[nvidia-cutlass] New port with v3.3.0

### LINKED ISSUE #32648: [New Port Request] cutlass
### Library name

cutlass

### Library description

CUDA Templates for Linear Algebra Subroutines

### Source repository URL

https://github.com/NVIDIA/cutlass

### Project homepage (if different from the source repository)

_No response_

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

_No response_

### PR DESCRIPTION
**Pull request by luncliff**
New port with https://github.com/NVIDIA/cutlass/releases/tag/v3.5.0  

* Resolve #32648

Maybe we can name it with `cutlass`, like the repository name.  
Here, I brought changes of the following PR

* https://github.com/luncliff/vcpkg-registry/pull/191

The port can help CUDA GPU support of other ports

* #36850

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html).
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [x] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by Neumann-A** [comment]
Libtorch is depending on this so adding this means decendoring it from libtorch.

**Comment by luncliff** [comment]
I will check the port

**Comment by luncliff** [comment]
Port `libtorch` now uses `nvidia-cutlass`.

Seems like there is a problem finding CUDA compiler with the default option. Manually set `CUTLASS_NATIVE_CUDA=OFF`

**Comment by jimwang118** [comment]
Usage test pass with following triplets:

```
x64-windows
x64-windows-static
```

**Review by data-queue — APPROVED** [review]

**Pull request merged**
