### PR TITLE
[ixwebsocket] Fix target ZLIB::ZLIB not found

### LINKED ISSUE #24071: [ixwebsocket] Unable to link due to target ZLIB::ZLIB not found
The `ixwebsocket` port is unusable. Linking a target against `ixwebsocket::ixwebsocket` fails with `Target "VcpkgIxWebsocket" links to target "ZLIB::ZLIB" but the target was not found`.

**Host Environment**
- OS: Windows
- Compiler: Visual Studio 2022 (MSVC 19.31.31105)
- vcpkg version: latest master (bd1ef2df46303989eeb048eb7aa9b816aa46365e)

**To Reproduce**

`vcpkg.json`:
```json
{
  "name": "vcpkg-ixwebsocket",
  "version": "0",
  "dependencies": ["ixwebsocket"]
}
```

`CMakeLists.txt`:
```cmake
cmake_minimum_required(VERSION 3.21)
project(VcpkgIxWebsocket)
find_package(ixwebsocket CONFIG REQUIRED)
add_executable(VcpkgIxWebsocket)
target_link_libraries(VcpkgIxWebsocket
	PRIVATE ixwebsocket::ixwebsocket
)
```

**Failure logs**

```
1> CMake generation started for default configuration: 'x64-Debug'.
1> Found and using vcpkg toolchain file (C:/Users/edechamps/Documents/vcpkg/scripts/buildsystems/vcpkg.cmake).
1> Command line: "C:\WINDOWS\system32\cmd.exe" /c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\edechamps\Documents\vcpkg-ixwebsocket\out\install\x64-Debug" -DCMAKE_C_COMPILER:FILEPATH="C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.31.31103/bin/Hostx64/x64/cl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.31.31103/bin/Hostx64/x64/cl.exe"  -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" -DCMAKE_TOOLCHAIN_FILE="C:/Users/edechamps/Documents/vcpkg/scripts/buildsystems/vcpkg.cmake" "C:\Users\edechamps\Documents\vcpkg-ixwebsocket" 2>&1"
1> Working directory: C:\Users\edechamps\Documents\vcpkg-ixwebsocket\out\build\x64-Debug
1> [CMake] -- Running vcpkg install
1> [CMake] Detecting compiler hash for triplet x64-windows...
1> [CMake] All requested packages are currently installed.
1> [CMake] Restored 0 packages from C:\Users\edechamps\AppData\Local\vcpkg\archives in 89.2 us. Use --debug to see more details.
1> [CMake] 
1> [CMake] Total elapsed time: 2.521 s
1> [CMake] 
1> [CMake] The package ixwebsocket provides CMake targets:
1> [CMake] 
1> [CMake]     find_package(ixwebsocket CONFIG REQUIRED)
1> [CMake]     target_link_libraries(main PRIVATE ixwebsocket::ixwebsocket)
1> [CMake] 
1> [CMake] -- Running vcpkg install - done
1> [CMake] -- Configuring done
1> [CMake] CMake Error at C:/Users/edechamps/Documents/vcpkg/scripts/buildsystems/vcpkg.cmake:568 (_add_executable):
1> [CMake]   Target "VcpkgIxWebsocket" links to target "ZLIB::ZLIB" but the target was
1> [CMake]   not found.  Perhaps a find_package() call is missing for an IMPORTED
1> [CMake]   target, or an ALIAS target is missing?
1> [CMake] Call Stack (most recent call first):
1> [CMake]   CMakeLists.txt:4 (add_executable)
1> [CMake] CMake Error at C:/Users/edechamps/Documents/vcpkg/scripts/buildsystems/vcpkg.cmake:568 (_add_executable):
1> [CMake]   No SOURCES given to target: VcpkgIxWebsocket
1> [CMake] Call Stack (most recent call first):
1> [CMake]   CMakeLists.txt:4 (add_executable)
1> [CMake] CMake Generate step failed.  Build files cannot be regenerated correctly.
1> 'C:\WINDOWS\system32\cmd.exe' '/c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\edechamps\Documents\vcpkg-ixwebsocket\out\install\x64-Debug" -DCMAKE_C_COMPILER:FILEPATH="C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.31.31103/bin/Hostx64/x64/cl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.31.31103/bin/Hostx64/x64/cl.exe"  -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" -DCMAKE_TOOLCHAIN_FILE="C:/Users/edechamps/Documents/vcpkg/scripts/buildsystems/vcpkg.cmake" "C:\Users\edechamps\Documents\vcpkg-ixwebsocket" 2>&1"' execution failed with error: ''C:\WINDOWS\system32\cmd.exe' '/c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\edechamps\Documents\vcpkg-ixwebsocket\out\install\x64-Debug" -DCMAKE_C_COMPILER:FILEPATH="C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.31.31103/bin/Hostx64/x64/cl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.31.31103/bin/Hostx64/x64/cl.exe"  -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" -DCMAKE_TOOLCHAIN_FILE="C:/Users/edechamps/Documents/vcpkg/scripts/buildsystems/vcpkg.cmake" "C:\Users\edechamps\Documents\vcpkg-ixwebsocket" 2>&1"' returned with exit code: 1'.
```

### PR DESCRIPTION
**Pull request by Cheney-W**
- #### What does your PR fix?
  Fixes https://github.com/microsoft/vcpkg/issues/24071

  The latest release of upstream has included the fix of this issue, so I updated this port.

### CODE REVIEW

**Comment by Neumann-A** [comment]
Personally I think this should be fixed by upstream and not by vcpkg. I know the fix is trivial but vcpkg cannot fix everything itself. Maybe open up a PR upstream and then integrate the patch here instead?

**Comment by JackBoosY** [comment]
According to the [official readme](https://github.com/machinezone/IXWebSocket#continuous-integration)：
```
TLS and ZLIB are disabled on Windows/UWP because enabling make the CI run takes a lot of time, for setting up vcpkg.
```
May be we should add zlib as a new feature and set `platform: !windows`?

**Comment by dg0yt** [comment]
> ```
> TLS and ZLIB are disabled on Windows/UWP because enabling make the CI run takes a lot of time, for setting up vcpkg.
> ```

This seems to be related to upstream's CI, not related to building in vcpkg CI where input artifacts are cached.
In addition, you don't want to go online without TLS.

**Comment by dg0yt** [comment]
> https://github.com/machinezone/IXWebSocket/blob/master/CMakeLists.txt#L242

AFAICT
- You don't need `if (NOT ZLIB_FOUND)`.
  A user-defined configuration should not set this variable. The user only needs to define the "input variables" `ZLIB_INCLUDE_DIR` and either `ZLIB_LIBRARY` or both `ZLIB_LIBRARY_RELEASE` and `ZLIB_LIBRARY_DEBUG`. Then `find_package(ZLIB REQUIRED)` can do its work.
- `target_link_libraries(ixwebsocket PRIVATE ZLIB::ZLIB)` is great.
  - It carries all "usage requirements".
    So, it is not necessary to use `target_include_directories(ixwebsocket PUBLIC $<BUILD_INTERFACE:${ZLIB_INCLUDE_DIRS}>)` at the same time.
  - However, it will also be written literally to the exported CMake config. 
    That's why the the exported config needs to make sure that the imported target is created there, too:
    ~~~cmake
    include(CMakeFindDependencyMacro)
    find_dependency(ZLIB)
    ~~~
    This would fix this vcpkg issue.
    It is common practice to implement this by letting CMake write `<pkg>-targets.cmake` instead of `<pkg>-config.cmake`, i.e.
    ~~~
    install(EXPORT ixwebsocket
          FILE ixwebsocket-targets.cmake
          ...)
    ~~~
    and `file(WRITE ...` or `configure_file(... @ONLY)` the actual `<pkg>-config.cmake` from something like:
    ~~~cmake
    cmake_policy(PUSH)
    cmake_policy(SET CMP0012 NEW)
    include(CMakeFindDependencyMacro)
    if("@USE_ZLIB@")
        find_dependency(ZLIB)
    endif()
    include("${CMAKE_CURRENT_LIST_DIR}/ixwebsocket-targets.cmake)
    cmake_policy(POP)
    ~~~

**Comment by Neumann-A** [comment]
what @dg0yt said plus:

Your problem is:
https://github.com/machinezone/IXWebSocket/blob/20921f341a1ae61789f64db5171ad7b2af30f811/CMakeLists.txt#L298-L301

you export the targets as a `-config.cmake`. This works if you don't take on dependencies but breaks downstream users if you have dependencies. Instead export that as whatever (commonly `-targets.cmake`) and include it in the real `-config.cmake`. You might want to take a look at https://cmake.org/cmake/help/latest/module/CMakePackageConfigHelpers.html to create the real  `-config.cmake` with the find_dependency lookup @dg0yt gave you.

**Comment by bsergean** [comment]
Ok I don't really know what I'm doing as those cmake incantations are really black magic. Thanks for the help anyway.

I made this PR to solve the vcpkg problem, is that sufficient ?

https://github.com/machinezone/IXWebSocket/pull/384/files

**Review by JackBoosY — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the update and working with upstream to get this fixed!

**Pull request merged**
