### PR TITLE
[libcbor] New port

### PR DESCRIPTION
**Pull request by xgcssch**
This is a new port for libcbor - https://github.com/PJK/libcbor

- What does your PR fix?
-/-

- Which triplets are supported/not supported? 
x64-windows
x86-windows
x64-windows-static

- Have you updated the CI baseline?
No, as i haven't seen the results

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

This port is an dependency for fido2 which i will add as an new port when this port is merged

Best regards
Sönke

### CODE REVIEW

**Comment by Cheney-W** [comment]
Thanks for your PR! 
Please run .`\vcpkg.exe format-manifest --all` to update your vcpkg.json file.

**Comment by Cheney-W** [comment]
Please run `.\vcpkg.exe x-add-version {port name} --overwrite-version` to update the {port}.json file.

**Comment by xgcssch** [comment]
Hi!
Must x-add-version be run every time a change was made as part of a commit?

**Comment by Cheney-W** [comment]
About port's json file, each of your commit changes will modify its git tree value, which means you need to update json file after you have done all the changes and executed the git commit -m "XXX" command. The specific sequence is as follows:
```
Git checkout -b "xxx"
Modify the local files
Git diff
Git add .
Git commit -m "comments description"
.\vcpkg x-add-version {Port name}
Git add .
Git commit -m "comments description"
git push
```
If you haven't executed the '`. \vcpkg x-add-version {port name}`' on the current branch, you need to use it after your modification is completed and submitted.
If you have executed this command on the current branch, you need to execute the following command when you need to update the json file:
`.\vcpkg.exe x-add-version {port name} --overwrite-version`

**Comment by xgcssch** [comment]
Thanks for the clarification!

**Comment by Cheney-W** [comment]
osgearth:x64-linux failure is a CI issue, it will be fixed by PR: https://github.com/microsoft/vcpkg/pull/16088

**Pull request merged**
