### PR TITLE
fix find_package for fftw3 and add arch features

### LINKED ISSUE #3552: CMake cannot find FFTW package
FFTW was successfully installed with vcpkg but including the package in CMakeLists.txt with 
``
find_package(fftw3 REQUIRED)
``
returns this error message:
```
C:\server\build>cmake .. -DCMAKE_TOOLCHAIN_FILE=d:\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x86-windows-static
-- Selecting Windows SDK version 10.0.16299.0 to target Windows 6.1.7601.
-- Boost version: 1.67.0
CMake Error at D:/vcpkg/scripts/buildsystems/vcpkg.cmake:247 (_find_package):
  By not providing "Findfftw3.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "fftw3", but
  CMake did not find one.

  Could not find a package configuration file provided by "fftw3" with any of
  the following names:

    fftw3Config.cmake
    fftw3-config.cmake

  Add the installation prefix of "fftw3" to CMAKE_PREFIX_PATH or set
  "fftw3_DIR" to a directory containing one of the above files.  If "fftw3"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:25 (find_package)


-- Configuring incomplete, errors occurred!
See also "C:/server/build/CMakeFiles/CMakeOutput.log".
```
Note that CMake can find other packages. This is the list of installed packages:
```
d:\vcpkg\vcpkg.exe list
...
boost:x86-windows                                  1.67.0           Peer-reviewed portable C++ source libraries
bzip2:x86-windows                                  1.0.6-2          High-quality data compressor.
bzip2:x86-windows-static                           1.0.6-2          High-quality data compressor.
fftw3:x86-windows                                  3.3.7-2          FFTW is a C subroutine library for computing the...
fftw3:x86-windows-static                           3.3.7-2          FFTW is a C subroutine library for computing the...
liblzma:x86-windows                                5.2.3-2          Compression library with an API similar to that ...
liblzma:x86-windows-static                         5.2.3-2          Compression library with an API similar to that ...
libpng:x86-windows                                 1.6.34-3         libpng is a library implementing an interface fo...
libpng:x86-windows-static                          1.6.34-3         libpng is a library implementing an interface fo...
openssl:x86-windows                                1.0.2o-2         OpenSSL is an open source project that provides ...
python3:x86-windows                                3.6.4-1          The Python programming language as an embeddable...
zlib:x86-windows                                   1.2.11-3         A compression library
zlib:x86-windows-static                            1.2.11-3         A compression library
```

### PR DESCRIPTION
**Pull request by Neumann-A**
requires: #4782 
closes: #3552

### CODE REVIEW

**Comment by Neumann-A** [comment]
TODO: Fix target for RelWithDebInfo linking debug fftw3 libraries

**Comment by seanwarren** [comment]
Hello, I'm wondering what is the status of this PR? 

I have updated this PR to resolve conflicts with master at https://github.com/seanwarren/vcpkg/commit/f0c79e726e90848ca6c9df458c6a138034acc039 . 

@Neumann-A Should I create a new PR or would you like to incorporate these changes?

**Comment by Neumann-A** [comment]
waiting for #5459 until I rebase and force push this branch. The conflicts should be gone then. 
I will also remove the last commit because there is a different way to map those in the consuming project, e.g.:
```
set(CMAKE_MAP_IMPORTED_CONFIG_MINSIZEREL Release)
set(CMAKE_MAP_IMPORTED_CONFIG_RELWITHDEBINFO Release)
```

**Comment by Neumann-A** [comment]
[AVX/AVX2 ICE related  VS Community Feedback](https://developercommunity.visualstudio.com/content/problem/479107/internal-compiler-error-compiling-fftw3-using-avxa.html)  

would be nice if someone can tell me what exactly is failing

**Comment by Cheney-W** [comment]
Here is the test result. 
```
Processing arm64-windows                  465 vs 466
     fftw3                         **regression**                Fail vs Pass
```
Here are all of the failures logs:
[fftw3.zip](https://github.com/Microsoft/vcpkg/files/2935038/fftw3.zip)

**Comment by Neumann-A** [comment]
Having sse2 as a default for x86 and x64 seems desirable. Is there a syntax to conditionally deactivate features by arch? I thought i saw something in a portfile once for uwp targets but it is not mentioned in the feature docs

**Comment by Rastaban** [comment]
Currently there is no standard way to conditionally deactivate a feature by arch.  Do you feel like having sse2 as default for x86/x64 is a precondition for having this PR merged?  If not then am interested in getting this merged and adding an issue for "conditionally deactivate port features for arch that don't support them" and point to this port as a place that would benefit.

**Comment by Neumann-A** [comment]
>  Do you feel like having sse2 as default for x86/x64 is a precondition for having this PR merged? 

@Rastaban: No just a nice to have feature :)

**Pull request merged**
