### PR TITLE
[vcpkg_configure_make] Fix almost-native builds

### LINKED ISSUE #28728: [gmp] Build error on macOS with specified host triplet
**Host Environment**

- OS: macOS 12.3
- Compiler: Xcode 14.0.1 using Apple clang

I initially ran into this issue on my fully updated (x86, macOS 13.1, Xcode 14.2) but figured it might be worth reproducing on GitHub Actions runner, to make sure it wasn't something weird with my environment (and also GitHub Actions is where I will want it to run).

**To Reproduce**

`./vcpkg install --host-triplet=x64-osx-release gmp`

**Failure logs**

See here for full output and reproducing steps in this test repo https://github.com/ekilmer/vcpkg-gmp-test/actions/runs/3841836968/jobs/6542507117#step:4:75

```
Installing 4/4 gmp:x64-osx...
Building gmp[core]:x64-osx...
-- Using cached gmp-6.2.1.tar.xz.
-- Using cached gmp-arm64-asm-fix-5f32dbc41afc.patch.
-- Cleaning sources at /Users/runner/work/vcpkg-gmp-test/vcpkg-gmp-test/vcpkg/buildtrees/gmp/src/v6.2.1-0c723d4b6f.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /Users/runner/work/vcpkg-gmp-test/vcpkg-gmp-test/vcpkg/downloads/gmp-6.2.1.tar.xz
-- Applying patch asmflags.patch
-- Applying patch cross-tools.patch
-- Applying patch subdirs.patch
-- Applying patch msvc_symbol.patch
-- Applying patch arm64-coff.patch
-- Applying patch /Users/runner/work/vcpkg-gmp-test/vcpkg-gmp-test/vcpkg/downloads/gmp-arm64-asm-fix-5f32dbc41afc.patch
-- Using source at /Users/runner/work/vcpkg-gmp-test/vcpkg-gmp-test/vcpkg/buildtrees/gmp/src/v6.2.1-0c723d4b6f.clean
-- Getting CMake variables for x64-osx
-- Getting CMake variables for x64-osx-dbg
-- Getting CMake variables for x64-osx-rel
-- Generating configure for x64-osx
-- Finished generating configure for x64-osx
-- Configuring x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: /bin/bash -c "V=1 ./../src/v6.2.1-0c723d4b6f.clean/configure  \"CCAS=cc\" \"ASMFLAGS=-c\" \"--enable-cxx\" \"--with-pic\" \"--with-readline=no\" \"gmp_cv_prog_exeext_for_build=\" \"--disable-silent-rules\" \"--verbose\" \"--disable-shared\" \"--enable-static\" \"--prefix=/Users/runner/work/vcpkg-gmp-test/vcpkg-gmp-test/vcpkg/installed/x64-osx/debug\" \"--bindir=\\${prefix}/../tools/gmp/debug/bin\" \"--sbindir=\\${prefix}/../tools/gmp/debug/sbin\" \"--libdir=\\${prefix}/lib\" \"--includedir=\\${prefix}/../include\" \"--datarootdir=\\${prefix}/share/gmp\""
    Working Directory: /Users/runner/work/vcpkg-gmp-test/vcpkg-gmp-test/vcpkg/buildtrees/gmp/x64-osx-dbg
    Error code: 1
    See logs for more information:
      /Users/runner/work/vcpkg-gmp-test/vcpkg-gmp-test/vcpkg/buildtrees/gmp/config-x64-osx-dbg-config.log
      /Users/runner/work/vcpkg-gmp-test/vcpkg-gmp-test/vcpkg/buildtrees/gmp/config-x64-osx-dbg-out.log
      /Users/runner/work/vcpkg-gmp-test/vcpkg-gmp-test/vcpkg/buildtrees/gmp/config-x64-osx-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:808 (vcpkg_execute_required_process)
  ports/gmp/portfile.cmake:82 (vcpkg_configure_make)
  scripts/ports.cmake:147 (include)


error: building gmp:x64-osx failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+gmp
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[gmp]+Build+error
Include '[gmp] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
    vcpkg-scripts version: fa32c6acb 2023-01-04 (48 minutes ago)
```

[config-x64-osx-dbg-config.log](https://github.com/microsoft/vcpkg/files/10347722/config-x64-osx-dbg-config.log)
[config-x64-osx-dbg-err.log](https://github.com/microsoft/vcpkg/files/10347723/config-x64-osx-dbg-err.log)
[config-x64-osx-dbg-out.log](https://github.com/microsoft/vcpkg/files/10347724/config-x64-osx-dbg-out.log)

The relevant lines in the log file (`*-config.log`) seems to be this
```
configure: testlist sizeof-long-4
configure:7781: checking compiler /Applications/Xcode_14.0.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -isysroot /Applications/Xcode_14.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -fPIC -g -fPIC -g has sizeof(long)==4
configure:7794: /Applications/Xcode_14.0.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -isysroot /Applications/Xcode_14.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -fPIC -g -fPIC -g -c conftest.c >&5
conftest.c:4:26: error: 'test_array' declared as an array with a negative size
  static int test_array [1 - 2 * (long) (sizeof (long) != 4)];
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
configure:7797: $? = 1
configure:7802: result: no
configure:7844: error: could not find a working compiler, see config.log for details
```

which is odd 

**Additional context**

This seems to be an issue with how cross-compiling is handled because when I remove `--host-triplet=x64-osx-release` (`vcpkg install gmp`) it compiles fine.

I can compile fine on Linux with
```
./vcpkg install --host-triplet=x64-linux-release gmp
```

### PR DESCRIPTION
**Pull request by dg0yt**
VCPKG_CROSSCOMPILING can apply even to builds which are native by traditional understanding. The host tool setup must follow the traditional pattern.
Fixes #28728.
Fixes mingw builds on windows.

### CODE REVIEW

**Comment by ekilmer** [comment]
Confirmed working with gmp for me on x64 osx. Thank you for the fix @dg0yt!

**Comment by Neumann-A** [comment]
> The host tool setup must follow the traditional pattern.

Why? (Currently I think it is a hack to allow running native stuff in a cross build which shouldn't be done. )

**Comment by dg0yt** [comment]
>> The host tool setup must follow the traditional pattern.

More accurately, the host tool setup must follow how triplets are passed to `configure`.
`VCPKG_CROSSCOMPILING` is enabled also for configuration aspects which do not map to autotools triplets.

> Why? (Currently I think it is a hack to allow running native stuff in a cross build which shouldn't be done. )

If triplets are absent, `configure` must use `config.guess` (for `--build`) and `config.sub` (for `--host`) for system detection. 
For some cases of `VCPKG_CROSSCOMPILING`, triplets are not passed to `configure`, but `XXX_FOR_BUILD` isn't set either. This breaks precise system type detection at least for osx, cf. https://github.com/microsoft/vcpkg/issues/28728#issuecomment-1372766170.

This PR implement one possible solution: couple the no-op modification of `XXX_FOR_BUILD` to (the absence of) `--host`. 
You could say that it should actually look for `--build` because the lack of this parameter maps to `config.guess`. But this PR is focused to fix the specific case when the detected `--build` triplet must be used for the `--host` - i.e. a native build due to absence of `--host`.

The alternative is to always pass both triplets: This would avoid the need to enter `config.guess`/`config.sub`. Even `config.guess` recommends against "the use of a compiler to aid in system detection". In the end, `configure` detects cross builds by comparing `--host` and `--build`. But I'm not sure if we want so much change in these non-versioned scripts.

**Comment by Neumann-A** [comment]
> The alternative is to always pass both triplets

The question is rather: Do we have information to do that. I at least would prefer that solution because it seems to be more correct. `--build` should really be controlled by `_HOST_TRIPLET` but we don't have a path to the triplet file to read that in.

**Comment by dg0yt** [comment]
@JonLiu1993 I don't see a good reason to change this PR. It is focused on the specific case which needs a correction. We even got external validation w.r.t. the original problem.

The alternative can be implemented in another PR, maybe in a script port. (A script port could depend on a host port for host toolchain information.)

**Comment by dg0yt** [comment]
Ping @JonLiu1993

**Review by JonLiu1993 — APPROVED** [review]

**Comment by JonLiu1993** [comment]
@dg0yt, Could you please modernize the functions inside portfile.cmake?

**Comment by dg0yt** [comment]
> @dg0yt, Could you please modernize the functions inside portfile.cmake?

No. As before, the PR check issues a false positive warning. gmp needs `vcpkg_copy_tool_dependencies`. It cannot be replaced.

**Comment by dg0yt** [comment]
Ping.

**Review by JonLiu1993 — APPROVED** [review]

**Pull request merged**
