### PR TITLE
[WIP] Add OpenNI2 port

### PR DESCRIPTION
**Pull request by UnaNancyOwen**
Add OpenNI2 port

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for the PR! Overall, looks great!

- I had some issue with the patch, so I tweaked it a bit to remove the problematic line.
- Debian appears to put all the headers under a subdirectory, so I did that as well [1]
- Vcpkg always executes builds in a clean subenvironment (use `vcpkg env` to open a shell inside) which whitelists your environment variables. This means the Kinect optional component can never be triggered, so I've removed it for now.
  - In the future, I think we should look at using Feature Packages (#1205) to support this more "properly". We can probably locate the install directory via the registry.

[1] https://packages.debian.org/sid/amd64/libopenni2-dev/filelist

**Comment by UnaNancyOwen** [comment]
@ras0219-msft Thank you for fix! :)
Currently, the main sensor officially supported by OpenNI2 is Kinect v1.
I think that OpenNI2 port should support Kinect v1 in the future.
Do you have any ideas for it?

**Comment by ras0219-msft** [comment]
If we'd like to always require the Kinect SDK, then that seems very reasonable to me.

We'd ideally make a "stub" port that represents the Kinect sdk (maybe `kinectsdk`?) that checks to ensure the SDK is installed and tells the user how to install it if they don't have it. Take a look at cuda[1], atlmfc[2], and msmpi[3] for some examples.

Now, to find the SDK I believe the best way would be to query the registry. CMake can do this natively[4], so as long as we can find the right key. For example, the CMake installation directory is found at `HKEY_LOCAL_MACHINE\SOFTWARE\Kitware\CMake;InstallDir`.

If they don't set a registry key, then we would need to whitelist[5] the environment variable. This is really a last resort though; it's much better if we don't have to modify the tool for each new package :).

[1] https://github.com/Microsoft/vcpkg/blob/master/ports/cuda/portfile.cmake
[2] https://github.com/Microsoft/vcpkg/blob/master/ports/atlmfc/portfile.cmake
[3] https://github.com/Microsoft/vcpkg/blob/master/ports/msmpi/portfile.cmake

[4] https://cmake.org/Wiki/CMake_FAQ#How_can_I_get_a_windows_registry_key_.3F
[5] https://github.com/Microsoft/vcpkg/blob/b188fefecaf03c1f30ee4752c2235975058553e2/toolsrc/src/vcpkg_System.cpp#L93

**Comment by UnaNancyOwen** [comment]
@ras0219-msft Thank you for your advice!
I found the install path of Kinect SDK v1.x in <code>HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Kinect;SDKInstallPath</code>.
2017-06-22_22h40_21

**Pull request merged**
