### PR TITLE
[portaudio] initial support for portaudio

### PR DESCRIPTION
**Pull request by nagua**
Hello,

I have added a port for portaudio.
The patch for the CMakeLists.txt is needed at the moment, as there is no install target.
However, there is a merge request in upstream, but it was not merged yet.
For this specific version we need the patch.

It should be working with all native windows builds.
I have not yet tested them in a real application.

Greetings,
Nagua

### CODE REVIEW

**Comment by nagua** [comment]
When I tested it in the runtime it is not working, because it tries to load the wrong dll. I renamed the dll's from portaudio_x86.dll to portaudio.dll because it makes detection of dll's easier with existing FindPORTAUDIO.cmake routines.

Has anyone an idea how to get this correct?

**Comment by ras0219-msft** [comment]
Thanks for the port!

Generally, you should *never* rename DLL files. You probably meant to only rename the LIB, which is searched for from `FindXYZ.cmake` scripts and internally contains the filename of the DLL it corresponds to. When you rename the DLL, that internal reference breaks and causes DLL load errors like you experienced.

**Comment by ras0219-msft** [comment]
I fixed the above DLL rename in `06272de6b4844`, which works for my simple test:
```
find_path(PA_INC portaudio.h)
find_library(PA_LIB portaudio)
target_link_libraries(main ${PA_LIB})
target_include_directories(main PUBLIC ${PA_INC})
```

**Comment by stekyne** [comment]
Is there anyway to get ASIO support with this?

**Comment by nagua** [comment]
It should be possible to compile it with ASIO support. But at the moment the package is not doing that.

**Comment by stekyne** [comment]
Any ideas how to achieve that? There is CMake support in portaudio to find the sdk if it's along side it but I'm not sure how to automate all of that.

**Comment by nagua** [comment]
You are able to set the directory of ASIO via the `ASIOSDK_PATH_HINT` CMake variable. See [FINDASIOSDK.cmake](https://github.com/EddieRingle/portaudio/blob/master/cmake_support/FindASIOSDK.cmake) for reference. You have to pass the asio directory via the variable in the CMake configure step. Pull Request are wellcome for this I think.

**Pull request merged**
