### PR TITLE
[networkdirect] Add new port

### PR DESCRIPTION
**Pull request by MVoz**
**deps**
WDK + PlatformToolset=WindowsUserModeDriver10.0 (Vsix-WDK)

### CODE REVIEW

**Comment by cenit** [comment]
Fully agree with it. It might help moving msmpi port from binary to built from source

**Comment by BillyONeal** [comment]
I'm a bit concerned with this because previously installing the WDK changed a whole bunch of machine-wide settings that broke folks (e.g. it tried to force everything to build with /Qspectre). But we'll see.

**Comment by Voskrese** [comment]
https://developercommunity.visualstudio.com/content/problem/348985/installing-wdk-1809-enabled-spectre-mitigation-fla.html

`msbuild /p:SpectreMitigation=false`

or patch

**Removing the following:**

```
<PropertyGroup>
<SpectreMitigation Condition="'$(SpectreMitigation)' == ''">Spectre</SpectreMitigation>
</PropertyGroup>
```

`Microsoft.Cpp.WDK.props` locates at `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160 and subdirectories Platforms\(Platform name)\ImportBefore\Default`

**Comment by BillyONeal** [comment]
@Voskrese That would require making such modifications to all ~1200 ports in inventory to inject that switch, which I don't think we want to sign up to do.

**Comment by Voskrese** [comment]
https://stackoverflow.com/questions/55900512/how-to-update-the-data-source-connection-string-using-powershell-in-the-xml-file
...
`$XmlDocument = [xml](Get-Content "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Platforms\x64\ImportBefore\Default\Microsoft.Cpp.WDK.props");`
...
`Spectre` to `false` ?

**Comment by Voskrese** [comment]
version wdk 10.0.19582.0 no problem

[WDK.zip](https://github.com/microsoft/vcpkg/files/4637981/WDK.zip)

can use a newer version? as well as sdk

**Comment by Voskrese** [comment]
`/p:SpectreMitigation=Disabled` not work )) 

> 
v160\Microsoft.CppBuild.targets(436,5): error MSB8040: Spectre-mitigated libraries are required for this project. Install them from the Visual Studio installer (Individual components tab) for any toolsets and architectures being used. Learn more: https://aka.ms/Ofhn4c

**Comment by Voskrese** [comment]
version wdk 10.0.19041.1 no problem
work

**Comment by BillyONeal** [comment]
Sounds good, will give that a shot

**Comment by Voskrese** [comment]
@BillyONeal 
https://github.com/microsoft/vcpkg/pull/11373#issuecomment-629452303
+ other port

**Comment by BillyONeal** [comment]
This change initially failed to deploy because the vsix install fails. However, it looks like that fails because it's 'already installed to all applicable products'. Either that's because we don't install IDE components on the builders, or because the installer you run first already achieved that registration.

**Comment by Voskrese** [comment]
most likely already installed

**Comment by Voskrese** [comment]
________________

**Comment by BillyONeal** [comment]
After doing the full rebuild with this change it looks like there may be some port failures resulting from msbuild injections mentioned previously.

Do we have a specific port this is intended to enable? Generally speaking we want as few dependencies preinstalled onto the machines as possible as that prevents ports from accidentally depending on system stuff...

**Comment by Voskrese** [comment]
I always installed the SDK and WDK distributions separately from MSVC, there were no problems

**Comment by Voskrese** [comment]
log error 
NuGet Version: 4.8.1.5435

update 5.7+ ???

**Comment by Voskrese** [comment]
ауфф... **local** okey

`vcpkg install networkdirect --triplet x64-windows`

```
Computing installation plan...
The following packages will be built and installed:
    networkdirect[core]:x64-windows
Starting package 1/1: networkdirect:x64-windows
Building package networkdirect[core]:x64-windows...
-- The Fortran compiler identification is unknown
-- Note: networkdirect only supports static library linkage. Building static library.
-- Building dirs.proj for Release
-- Building dirs.proj for Debug
-- Installing: E:/tools/vcpkg/packages/networkdirect_x64-windows/share/networkdirect/copyright
-- Performing post-build validation
```

**Comment by Voskrese** [comment]
`Microsoft.CppBuild.targets(390,5): error MSB8020: The build tools for WindowsUserModeDriver10.0 (Platform Toolset = 'WindowsUserModeDriver10.0') cannot be found. To build using the WindowsUserModeDriver10.0 build tools, please install WindowsUserModeDriver10.0 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".`

**Comment by Voskrese** [comment]
@BillyONeal 
need help, I have the feeling that the SDK and the WDK are not installed

**Comment by BillyONeal** [comment]
> @BillyONeal
> need help, I have the feeling that the SDK and the WDK are not installed

That's correct, we have not updated the image for the VMs with any changes herein. `provision-image.ps1` isn't deployed live to the machines, it's only applied when the fleet is redeployed. That's what I'm trying to do in that update vmss PR but to be able to switch the image means we need a clean build of the tree, so there's been a lot of patching necessary to get us clean vis a vis 16.6.

**Comment by Voskrese** [comment]
I'm stupid)) I sit and don't understand why it doesn't work out
it's bad that there are no log files, everything is blind

the port I added, everything works locally, WDK support is needed

**Comment by Voskrese** [comment]
there is no point wdk in request, delete, leave only port?

**Comment by cenit** [comment]
@voskrese

> don't understand why it doesn't work out

If you modify ps1 scripts, you don’t see the result in CI. When you push, the system is still using the **old** version!
That’s why it works on your pc but not here

**Comment by Voskrese** [comment]
@cenit 
I thought the reference image is used and you can install additional software on it
this is probably a matter of access rights

in General, okay, the test failed once again )))

**Comment by cenit** [comment]
No, that’s not how this azure set works. You have to redeploy the set, and this can **not** be done by a run by itself

**Comment by cenit** [comment]
You can suggest modifications (like how I did for cuda and msmpi) but unfortunately you can **not** see results here in the pull request. It requires a vmss redeploy

**Comment by Voskrese** [comment]
@cenit 
I saw that the SDK and WDK were already added there, except for VSIX-WDK

need to close, after adding WDK, add port in PR

**Comment by Voskrese** [comment]
only test WDK, not merge

**Pull request closed without merging**
