### PR TITLE
[igraph] update to 0.9.4

### PR DESCRIPTION
**Pull request by szhorvat**
**Describe the pull request**

- #### What does your PR fix?  
  Update to 0.9.4

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Review by JonLiu1993 — APPROVED** [review]

**Review by JonLiu1993 — CHANGES_REQUESTED** [review]
@szhorvat ,Please leave two spaces after FEATURES in the vcpkg_check_features function

**Comment by JonLiu1993** [comment]
All features are tested successfully in the following triplets
- x86-windows
- x64-windows
- x64-windows-static

**Comment by szhorvat** [comment]
@JonLiu1993 Can you please answer my question from here? https://github.com/microsoft/vcpkg/pull/17683#issuecomment-834119358

> When using `${FEATURE_OPTIONS}`, vcpkg adds `-DSOMEFLAG=ON` when an option is enabled. Does it also add `-DSOMEFLAG=OFF` when the option is not enabled?  Is there an easy way to see the CMake invocation, so I can determine this for myself?

**Comment by szhorvat** [comment]
> @szhorvat ,Please leave two spaces after FEATURES in the vcpkg_check_features function

I don't understand what you mean. Can you write down the exact modification you need? The current code:

```
vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
  FEATURES
    graphml   IGRAPH_GRAPHML_SUPPORT
    openmp    IGRAPH_OPENMP_SUPPORT
)
```

`FEATURES` is followed by a newline. Do you want two trailing spaces?

**Comment by JonLiu1993** [comment]
> > @szhorvat ,Please leave two spaces after FEATURES in the vcpkg_check_features function
> 
> I don't understand what you mean. Can you write down the exact modification you need? The current code:
> 
> ```
> vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
>   FEATURES
>     graphml   IGRAPH_GRAPHML_SUPPORT
>     openmp    IGRAPH_OPENMP_SUPPORT
> )
> ```
> 
> `FEATURES` is followed by a newline. Do you want two trailing spaces?

vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    FEATURES
    graphml   IGRAPH_GRAPHML_SUPPORT
    openmp    IGRAPH_OPENMP_SUPPORT
)

**Comment by szhorvat** [comment]
Thanks for the clarification. This is done now.

**Review by JonLiu1993 — APPROVED** [review]

**Comment by ras0219-msft** [comment]
LGTM, thanks for the update!

**Pull request merged**
