### PR TITLE
 [tensorflow] update to 2.6

### LINKED ISSUE #18536: [tensorflow] update to 2.5.0
Library name: tensorflow

New version number: 2.5.0
Released on 13 May 2021.

Release notes: https://github.com/tensorflow/tensorflow/releases/tag/v2.5.0

### PR DESCRIPTION
**Pull request by jgehw**
update TensorFlow to v2.6.0

fixes #18536

### CODE REVIEW

**Comment by JonLiu1993** [comment]
@jgehw ,Please take a look:
https://dev.azure.com/vcpkg/public/_build/results?buildId=59103&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by JonLiu1993** [comment]
Thanks for your pr,after finish your suggesstion changes,please run command "./vcpkg x-add-version --all --overwrite-version" then commit the changes again

**Comment by JonLiu1993** [comment]
@jgehw ,This is error log,please take a look:
https://dev.azure.com/vcpkg/public/_build/results?buildId=59297&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by JonLiu1993** [comment]
````
ERROR: D:/buildtrees/tensorflow/x64-windows-dbg/tensorflow/BUILD:984:20: Linking tensorflow/tensorflow.dll failed: (Exit 1120): link.exe failed: error executing command 
  cd D:/buildtrees/tensorflow/.bzl/rge6fwhh/execroot/org_tensorflow
  SET LIB=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\ATLMFC\lib\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\lib\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\\x64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\;C:\Program Files (x86)\HTML Help Workshop;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\devinit;C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\;;C:\Windows\system32;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\Llvm\x64\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\VC\Linux\bin\ConnectionManagerExe
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=D:/downloads/tools/msys2/b3b3d399e80e310e/mingw64/bin/python3.exe
    SET PYTHON_LIB_PATH=D:/downloads/tools/msys2/b3b3d399e80e310e/mingw64/lib/python3.8/site-packages
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=C:\Users\AzDevOps\AppData\Local\Temp
    SET TF2_BEHAVIOR=1
    SET TMP=C:\Users\AzDevOps\AppData\Local\Temp
  C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/HostX64/x64/link.exe @bazel-out/x64_windows-dbg/bin/tensorflow/tensorflow.dll-2.params
Execution platform: @local_execution_config_platform//:platform
INFO: Elapsed time: 1059.069s, Critical Path: 254.00s
INFO: 8902 processes: 1830 internal, 7072 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

````

**Comment by JonLiu1993** [comment]
@jgehw ,Looks the CI error log same as before:
https://dev.azure.com/vcpkg/public/_build/results?buildId=59558&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by jgehw** [comment]
@JonLiu1993 there are some strange CI errors, please re-run CI pipelines

**Comment by jgehw** [comment]
@BillyONeal can you please check what's going wrong on the macOS CI? From what I can see in the logs, it seems while building tensorflow either the build machine stopped responding or the watcher process dropped the connection because something took longer than expected. Strange is that no error logs are provided as artifacts, only a file list (which clearly shows that only tensorflow-common succeeded, but neither tensorflow nor tensorflow-cc). Maybe a disk space issue? (I don't know the exact requirements, but it seems that the buildtrees folder grows clearly above 100GB...)

**Comment by BillyONeal** [comment]
>Maybe a disk space issue? (I don't know the exact requirements, but it seems that the buildtrees folder grows clearly above 100GB...)

That seems unlikely given the post-build results:

```
/bin/bash --noprofile --norc /Users/vagrant/Data/work/_temp/ba3e930e-46b3-4d51-ab68-891937e1ffb6.sh
Filesystem                                                   Size   Used  Avail Capacity iused      ifree %iused  Mounted on
/dev/disk1s5s1                                              256Gi   14Gi  206Gi     7%  553781 2680441659    0%   /
devfs                                                       186Ki  186Ki    0Bi   100%     642          0  100%   /dev
/dev/disk1s4                                                256Gi  3.0Gi  206Gi     2%       4 2680995436    0%   /System/Volumes/VM
/dev/disk1s2                                                256Gi  271Mi  206Gi     1%     723 2680994717    0%   /System/Volumes/Preboot
/dev/disk1s6                                                256Gi  612Ki  206Gi     1%      17 2680995423    0%   /System/Volumes/Update
/dev/disk1s1                                                256Gi   32Gi  206Gi    14%  728764 2680266676    0%   /System/Volumes/Data
//guest:@Shared%20Folders._smb._tcp.local/Shared%20Folders  4.0Ti    0Bi  4.0Ti     0% 18446744073709551614 1073741824 1717986921600%   /Volumes/SharedFolders
map auto_home                                                 0Bi    0Bi    0Bi   100%       0          0  100%   /System/Volumes/Data/home
/dev/disk1s5                                                256Gi   14Gi  206Gi     7%  553781 2680441659    0%   /System/Volumes/Update/mnt1
```

I do know that Tensorflow likes to break workers but we haven't had great ideas to figure out why.

**Comment by jgehw** [comment]
> I do know that Tensorflow likes to break workers but we haven't had great ideas to figure out why.

Diskspace wasn't the issue this time as you suspected. I could reproduce the build error on my machine. It's some strange error most likely introduced by bazel in conjunction with Xcode build tools. [Other users already ran into this in early 2021](https://github.com/tensorflow/tensorflow/issues/46566) with tensorflow 2.4. I could work around it by limiting the debug symbols from full to fastbuild.

With this fixed, a file-not-found error occurs on CI which I can't reproduce (the file exists in my local build). I'm approaching this now with debug output added to portfile.

**Comment by jgehw** [comment]
@BillyONeal It seems that the build didn't even start on CI. It seems to have stalled and be terminated after almost two hours. From raw log:
```
2021-09-19T11:25:02.7978030Z Starting package 2/3: tensorflow:x64-osx
2021-09-19T11:25:02.7978860Z Building package tensorflow[core]:x64-osx...
2021-09-19T13:21:03.9178080Z ##[error]The operation was canceled.
```
If the build process fails, the output should at least contain something like:
```
Starting package 1/1: tensorflow:x64-osx
Building package tensorflow[core]:x64-osx...
-- Downloading https://github.com/tensorflow/tensorflow/archive/v2.6.0.tar.gz -> tensorflow-tensorflow-v2.6.0.tar.gz...
-- Extracting source /Users/joachim/Documents/vcpkg/downloads/tensorflow-tensorflow-v2.6.0.tar.gz
-- Applying patch /Users/joachim/Documents/vcpkg/installed/x64-osx/share/tensorflow-common/fix-build-error.patch
-- Applying patch /Users/joachim/Documents/vcpkg/installed/x64-osx/share/tensorflow-common/Update-bazel-max-version.patch
-- Applying patch /Users/joachim/Documents/vcpkg/installed/x64-osx/share/tensorflow-common/change-macros-for-static-lib.patch
-- Using source at /Users/joachim/Documents/vcpkg/buildtrees/tensorflow/src/v2.6.0-e3dcb031ee.clean
-- Configuring TensorFlow (dbg)
-- Warning: Building TensorFlow can take an hour or more.
```

**Comment by jgehw** [comment]
Found out that on macOS we have instable behaviour of bazel: sometimes `-2.params` file is used for linker arguments, sometimes arguments are inlined. Thus re-activate old argument parsing code and add switch to detect which situation applies.

**Comment by BillyONeal** [comment]
CI is supposed to delete the buildtrees directory after each build.

**Comment by BillyONeal** [comment]
>what we would need here, would be cleanup of each port's buildtrees subdirectory immediately after each port, within the vcpkg run

`ci` (and `install --clean-buildtrees-after-build`) is supposed to do that: https://github.com/microsoft/vcpkg-tool/blob/733e90d1bc3f4f8188d57d73e2d20765c232cc26/src/vcpkg/build.cpp#L983

I'm not ruling out disk space as a potential trigger here but if it were I would expect agents to completely die, which isn't what we're seeing...

**Comment by BillyONeal** [comment]
> > what we would need here, would be cleanup of each port's buildtrees subdirectory immediately after each port, within the vcpkg run
> 
> `ci` (and `install --clean-buildtrees-after-build`) is supposed to do that: https://github.com/microsoft/vcpkg-tool/blob/733e90d1bc3f4f8188d57d73e2d20765c232cc26/src/vcpkg/build.cpp#L983
> 
> I'm not ruling out disk space as a potential trigger here but if it were I would expect agents to completely die, which isn't what we're seeing...

Here's an example where it died partway into building just one: https://github.com/microsoft/vcpkg/pull/20273

I'll see if I can investigate further today...

**Comment by BillyONeal** [comment]
I'm watching a run in top and nothing looks unusual, but I did file https://github.com/microsoft/azure-pipelines-agent/issues/3541

**Comment by BillyONeal** [comment]
Maybe we are running out of physical RAM, hitting swap, and that brings the system to a crawl? 
image

**Comment by jgehw** [comment]
> Maybe we are running out of physical RAM, hitting swap, and that brings the system to a crawl and starves out the agent?

@BillyONeal That sounds likely, especially when also taking into consideration that cleaning up the buildtrees folder after the C-port succeeded causes heavy disk I/O (it's not only >70GB to cleanup but also around 250,000 files).

Is it possible to record and share the `top` output? (Something like `top -b > somefile.log` should do the job.)

**Comment by BillyONeal** [comment]
I intend to investigate what's happening on macos tomorrow

**Comment by BillyONeal** [comment]
Our mac wizard @strega-nil / @strega-nil-ms fixed the VMs powering the macos stuff to have more RAM; it seemed fixed in last night's CI. I merged with my change that disabled leaving long running servers too.

**Comment by BillyONeal** [comment]
Thanks for the update and sorry for for the infrastructure issues! I will go back to meditating on https://youtu.be/NSemlYagjIU

**Comment by jgehw** [comment]
> Thanks for the update and sorry for for the infrastructure issues! I will go back to meditating on https://youtu.be/NSemlYagjIU

@BillyONeal thanks for pointing me to this hilarious talk -- good summary of what we're going through... ;-)

**Pull request merged**
