### PR TITLE
[gdal] Make available on arm

### PR DESCRIPTION
**Pull request by m-kuhn**
**Describe the pull request**

- #### What does your PR fix?  
Removes exclusion of gdal on arm.
This has been around forever, and it's hard to tell why it has been put there originally.
Builds fine here for android-arm, so I assume the cpu is not an issue.
If there are good reasons not to support arm, this PR shall be closed and a descriptive comment added instead, so once the issue has been fixed the port can be adapted accordingly.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
all

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
yes

### CODE REVIEW

**Comment by dg0yt** [comment]
Unfortunately, the change is not tested in vcpkg CI: Some dependency is marked as failing or not supported on arm, and this cascades to gdal.

**Comment by m-kuhn** [comment]
> Some dependency is marked as failing or not supported on arm, and this cascades to gdal.

Sorry, I'm failing to follow the implications of this.

Where I'm coming from: it builds fine for arm-android
What I'd expect is: if a dependency is failing, gdal should be excluded implicitly, not explicitly

**Comment by dg0yt** [comment]
@m-kuhn I just wanted to point out that we cannot feel safe with all CI checks green because gdal:arm still *is excluded implicitly*.

**Comment by m-kuhn** [comment]
> @m-kuhn I just wanted to point out that we cannot feel safe with all CI checks green because gdal:arm still _is excluded implicitly_.

_is_ or _may be_?
Whatever, even if there still is a problem somewhere else, this PR should help shifting the attention to the right spot.

**Comment by autoantwort** [comment]
Works at least on arm64-osx

**Review by NancyLi1013 — APPROVED** [review]

**Comment by dg0yt** [comment]
We know that gdal works on arm from using gdal without vcpkg.
FTR it is hdf5 which is marked as failing on arm. Hdf5 may be hard to fix unless you can test it. But that problem should go away soon, when we turn hdf5 into a non-default feature.

**Comment by dg0yt** [comment]
Building for arm doesn't work yet for windows targets (building with nmake). I adopted a modified version for the gdal 3.4.0 update in #21261. This should make this PR obsolete.

**Comment by m-kuhn** [comment]
Very good news, I'm more than happy to let go

**Pull request closed without merging**
