### PR TITLE
[xlsxio] new port

### PR DESCRIPTION
**Pull request by playgithub**
**Describe the pull request**

- #### What does your PR fix?  
port xlsxio

- #### Which triplets are supported/not supported? Have you updated the [CI baseline]
All
No

- #### Does your PR follow the [maintainer guide]
Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
Yes

### CODE REVIEW

**Comment by cenit** [comment]
the patch is unnecessary

better to pass (in configure cmake

```
-DBUILD_SHARED=$BUILD_SHARED
-DBUILD_STATIC=$BUILD_STATIC
```

after having defined those symbols beforehand with something like

```
set(BUILD_STATIC OFF)
set(BUILD_SHARED OFF)

if (VCPKG_LIBRARY_LINKAGE STREQUAL static)
   set(BUILD_STATIC ON)
else()
   set(BUILD_SHARED ON)
endif()
```

In this way we save some space in vcpkg and guarantee future proof to patch

**Comment by playgithub** [comment]
> some



> the patch is unnecessary
> 
> better to pass (in configure cmake
> 
> ```
> -DBUILD_SHARED=$BUILD_SHARED
> -DBUILD_STATIC=$BUILD_STATIC
> ```
> 
> after having defined those symbols beforehand with something like
> 
> ```
> set(BUILD_STATIC OFF)
> set(BUILD_SHARED OFF)
> 
> if (VCPKG_LIBRARY_LINKAGE STREQUAL static)
>    set(BUILD_STATIC ON)
> else()
>    set(BUILD_SHARED ON)
> endif()
> ```
> 
> In this way we save some space in vcpkg and guarantee future proof to patch

In fact, I've tried this, but with `if(BUILD_SHARED_LIBS)` instead of `if (VCPKG_LIBRARY_LINKAGE STREQUAL static)`, and failed.
I'll try it, thanks.

**Comment by cenit** [comment]
BUILD_SHARED_LIBS is not defined when processing a port file, that's why it didn't work

**Comment by playgithub** [comment]
I've re-forked vcpkg

**Pull request closed without merging**
