### PR TITLE
[librdakafka] add new port librdkafka

### PR DESCRIPTION
**Pull request by alexander-smyslov**

### CODE REVIEW

**Comment by Rastaban** [comment]
Looks like this and #5921 for the same library were submitted on the same day.

**Comment by Rastaban** [comment]
I see build failures on `x64-windows-static`, `x64-uwp`, and `arm-uwp`.  Are these failures expected?

**Comment by alexander-smyslov** [comment]
Same library exists https://github.com/Microsoft/vcpkg/pull/5921

**Comment by myd7349** [comment]
Hi! @alexander-smyslov This seems your first PR on GitHub. If you'd like to finish it, I will close mine.

BTW, the reason I used `rdkafka` as the package name is that the exported CMake target has this name. If we use `librdkafka` as the package name, we may need some more code to make the CMake config file appear in the right place.

**Comment by alexander-smyslov** [comment]
Hi
I close my pull request because your request is first.
librdkafka   is official library name. i suggest use it. Port can produce
dll with different name or several dll.   may be need ask point of
view   librdkafka
owner.

**Comment by myd7349** [comment]
Hi! @alexander-smyslov I think you are right. I will change the package name to `librdkafka`.

**Pull request closed without merging**
