### PR TITLE
CI testrun for CMake 3.28-rc5

### PR DESCRIPTION
**Pull request by Neumann-A**
lets hope everything builds....

### CODE REVIEW

**Comment by xavier2k6** [comment]
CMake 3.28.1 officially out.

**Comment by MonicaLiu0311** [comment]
If you are done testing and are not continuing this PR, I will close it.

**Comment by xavier2k6** [comment]
CMake 3.28.2 officially out.

**Comment by dg0yt** [comment]
> CMake 3.28.2 officially out.

... and it reverts the incomplete FindFreetype changes,

**Pull request closed without merging**
