### PR TITLE
[gdk-pixbuf,gettext,glib,libcroco,libiconv] Fix for gdk-pixbuf Linux …

### PR DESCRIPTION
**Pull request by Kwizatz**
…build

This commit includes changes and updates to properly build
dependencies for gdk-pixbuf on Linux.

Of particular note is the generation of actual archive files
for both gettext and libiconv.

This is preliminary work to introduce a librsvg port.

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for the PR!

We don't currently build libiconv on Linux because glibc provides all of its functionality. Could you go into a bit more detail about why using glibc's exports isn't appropriate in this case?

**Comment by Kwizatz** [comment]
@ras0219-msft Hi. There really isn't any particular reason. gdk-pixbuf is broken on Linux, and in order to fix it, I had to make these changes. I take it it may be possible to fix gdk-pixbuf without these changes, but I couldn't work around it any other way.

**Comment by Kwizatz** [comment]
I may have found a less intrusive fix, I'll upload a new PR if it works. The original problem was that gdk-pixbuf was requesting libintl and gettext has no archives on Linux.

**Comment by Kwizatz** [comment]
PR #6663 does away with building gettext and iconv on Linux.

**Comment by NancyLi1013** [comment]
Hi @Kwizatz , here are the test results from current CI system:

|x64-linux                |test|notes
|-------------------------|----|-----
|qt5-speech               |Fail|**Regression**
|boost-locale             |Fail|**Regression**
|glibmm                   |Fail|**Regression**

[failureLogs.zip](https://github.com/microsoft/vcpkg/files/3260806/failureLogs.zip)

**Comment by Rastaban** [comment]
Closing this PR because I think it is no longer needed now that #6663 is merged.  If I am misunderstanding then please let me know and reopen the PR.

**Pull request closed without merging**
