### PR TITLE
[osg] Add Collada model support to OpenSceneGraph

### PR DESCRIPTION
**Pull request by calumr**
Collada models are .dae files, and are the only open format you can download from [3dwarehouse.sketchup.com](https://3dwarehouse.sketchup.com).

### CODE REVIEW

**Comment by Codiferous** [comment]
@calumr Sorry for the tremendous delay in processing this PR -- we're focusing very heavily on processing PRs now!

Is the `fix-virtual-method.patch` patchfile necessary here? I tried building this port without it and everything seemed fine. In general, we try to avoid intrusive patches to libraries in vcpkg in order to void deviating from the library's functionality. If the library needs to be significantly patched, we prefer that the project takes the changes as a PR. 

Would this PR be something we could accept without the virtual method patch?

**Comment by calumr** [comment]
The patch was a hack to work around a crash in daeIOPluginCommon::beginReadElement. When you try to load a .dae file in OSG, it crashes in here and I didn't get the time to debug the issue. I can't recall why I tried making the methods virtual, but it worked.

I don't have time to investigate a fix right now. If possible I'd prefer to merge without the `fix-virtual-method.patch` and I will come up with a proper fix when my team is finished our current release.

I could try attaching a minimal test case that reproduces the bug?

**Comment by calumr** [comment]
Actually I think this is just a case of missing `-DCOLLADA_DOM_SUPPORT150` out of the osg build. I'll submit a patch soon.

**Comment by Codiferous** [comment]
Okay, this PR is looking pretty good to me! Let's get it merged 😄 Thanks for this, and sorry again for the significant delay in processing this!

**Pull request merged**
