### PR TITLE
[vcpkg] Always use an autotools build triplet

### PR DESCRIPTION
**Pull request by dg0yt**
- #### What does your PR fix?  
  This PR ensures that `vcpkg_configure_make` always determines autotools triplet ~when building for mingw~. This fixes the case when both vcppkg target triplet and vcpkg host triplet are set to the same mingw triplet, i.e. building on a Windows PC without MSVC.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all (but targeting mingw), no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  -/-

PS: I didn't want to add yet another expression to the if clause following that change.

### CODE REVIEW

**Comment by Neumann-A** [comment]
Hmm why? shouldn't _csc_AUTOCONFIG not decide here? Which port is affected by this change?

**Comment by dg0yt** [comment]
> Which port is affected by this change?

It happened a few days ago on a different computer. Let's try here anyway:
~~~sh
$ grep -l vcpkg_configure_make ports/*/portfile.cmake | while read I; do grep "AUTOCONFIG" || echo $I; done
ports/apr/portfile.cmake
~~~

Now I remember: Port apr normally doesn't use `vcpkg_configure_make` on Windows, but it was one of the ports I exerimented with when I investigated @Neumann-A's [question about the linkage flags for uuid](https://github.com/microsoft/vcpkg/pull/17137#issuecomment-845441947).

> shouldn't _csc_AUTOCONFIG not decide here? 

If it is present, yes. But the documenation doesn't give me the impression that this option is *mandatory* when building a project based on autotools, or that it is related to triplets:

> ### AUTOCONFIG
> Need to use autoconfig to generate configure file.

Perhaps `DETERMINE_BUILD_TRIPLET` documentation might be interpreted as making that option mandatory:

> ### DETERMINE_BUILD_TRIPLET
> For ports having a configure script following the autotools rules for selecting the triplet

But it isn't use very often:
~~~sh
$ grep -l vcpkg_configure_make ports/*/portfile.cmake | while read I; do grep -q "DETERMINE_BUILD_TRIPLET" $I && echo $I ; done
ports/gettext/portfile.cmake
ports/libiconv/portfile.cmake
ports/libpq/portfile.cmake
ports/mp3lame/portfile.cmake
~~~

Last not least the `if` statement following the change deals not only with the `AUTOCONFIG` and `DETERMINE_BUILD_TRIPLET` options but also with `VCPKG_CROSSCOMPILING`. However, mingw-target with mingw-host does not activate  `VCPKG_CROSSCOMPILING`.

**Comment by longnguyen2004** [comment]
IIRC, `AUTOCONFIG` is used for libraries that don't come with a pre-generated `configure` script, so it's not related to triplets.

**Comment by Neumann-A** [comment]
> IIRC, AUTOCONFIG is used for libraries that don't come with a pre-generated configure script, so it's not related to triplets.

it is also required if the configure script was generated with an old version of autotools/libtool

**Comment by ras0219-msft** [comment]
This does smell very weird; I don't see why MinGW should be special here.

**Comment by dg0yt** [comment]
> I don't see why MinGW should be special here.

So its up to community support to add `AUTOCONFIG` (for its side effect) or `DETERMINE_BUILD_TRIPLET` (for its regular effect) for all ports that don't build with mingw on Windows (i.e. are not cross-compiling)?

**Comment by dg0yt** [comment]
> This does smell very weird; I don't see why MinGW should be special here.

For `configure` in `WIN32` MinGW must be handled as a crossbuild even if host triplet == target triplet.

**Comment by ras0219-msft** [comment]
> ... MinGW must be handled as a crossbuild even if host triplet == target triplet.

Mechanically, why is this? And then, why should we not _always_ cross build?

**Comment by dg0yt** [comment]
> > ... MinGW must be handled as a crossbuild even if host triplet == target triplet.
> 
> Mechanically, why is this? And then, why should we not _always_ cross build?

You left out the context before my statement:

> For configure in WIN32

When `vcpkg_configure_make` is run on Windows, with a mingw target triplet and mingw host triplet, it must pass triplets to `configure` as it does in cross compiling, or the build will fail due to assumptions about non-mingw tools being available.

This PR is the result of building with mingw on Windows.

**Comment by dg0yt** [comment]
(Wrong button.)

The alternative is to always set the proper mingw `--host=<arch>-w64-minw32` when `VCPKG_TARGET_IS_MINGW`.

**Comment by dg0yt** [comment]
Any other comments how to generally ensure proper triplet when building mingw on windows?

**Comment by NancyLi1013** [comment]
@vicroms

Could you please help take a look?

**Comment by dg0yt** [comment]
Ping.

**Comment by NancyLi1013** [comment]
> Any other comments how to generally ensure proper triplet when building mingw on windows?

@ras0219-msft Could you please help leave some comments for this?

**Comment by strega-nil-ms** [comment]
Given that we don't have any experts on mingw on our team, and the expert on mingw says this is important, could we merge as "strictly better and also on a community triplet"? cc @ras0219, opinions?

**Comment by BillyONeal** [comment]
It seems like the correct fix for this is to yank out a `vcpkg_autoconf_configure()` and friends in a `vcpkg-autoconf` port which always does the `DETERMINE_BUILD_TRIPLET` behavior, and transition autoconf based ports to use that rather than patching `vcpkg_configure_make`.

(Unfortunately, `vcpkg_configure_make` doesn't really make up its mind as to whether it is or is not targeting autoconf; assuming things that are not autoconf but still name themselves `configure` will be happy to get extra `--build`, `--host`, and `--target` switches is probably not safe)

**Comment by ras0219-msft** [comment]
I observe that in the conditional
```cmake
if (_csc_AUTOCONFIG AND NOT _csc_BUILD_TRIPLET OR _csc_DETERMINE_BUILD_TRIPLET OR VCPKG_CROSSCOMPILING AND NOT _csc_BUILD_TRIPLET)
```
the variable `VCPKG_CROSSCOMPILING` is already being set for all our `x86-windows` and `x64-windows-static` customers (that leave the default `x64-windows` host triplet). This gives a strong indication that it should be safe to always engage this block.

Perhaps we should try that approach as a more minimal change that doesn't introduce further diversification?

**Comment by Neumann-A** [comment]
> When vcpkg_configure_make is run on Windows, with a mingw target triplet and mingw host triplet, it must pass triplets to configure as it does in cross compiling, or the build will fail due to assumptions about non-mingw tools being available.

Why is that? is the environment not correctly setup? Or is it choosing the MSYS compilers?

Also there is the undocumented triplet variable `VCPKG_MAKE_BUILD_TRIPLET` to force a certain triplet if needed.

**Comment by dg0yt** [comment]
This is a fairly simple change from May. It makes ports pass a crucial setting to `configure` on native mingw builds, instead of delegating to configure's detection mechanisms.

> Why is that? is the environment not correctly setup?

Who knows? Perhaps some ports didn't properly read the environment?

If you don't want to make this a general behaviour, we will have to make individual changes to all ports which fail due to missing `AUTOCONFIG`.

For more fundamental long-term changes, coordinate with #19753 or #20165 audits by @JackBoosY. Possibly including the flip from opt-in `AUTOCONFIG` to opt-out `SKIP_AUTOCONFIG`. (I would have more ideas but don't want to go OT.)

**Review by ras0219-msft — APPROVED** [review]
I've pushed the simplification I suggested above -- LGTM if it passes :)

Thanks!

**Comment by BillyONeal** [comment]
Thanks and sorry it took a while to review!

**Pull request merged**
