### PR TITLE
[boost-asio] Enable arm64-windows

### PR DESCRIPTION
**Pull request by tony979**
Enable boost:arm64-windows

### CODE REVIEW

**Comment by cenit** [comment]
since the files you modified are generated automatically by `boost-vcpkg-helpers/generate-ports.ps1`, I suggest you to modify that file to not loose your fixes on the next update

**Comment by PhoebeHui** [comment]
@tony979, could you resolve the conflicts?

Actually It support to build Boost with arm64-windows(with msvc toolset) in boost 1.72.0. see https://github.com/boostorg/build/releases

**Comment by dan-shaw** [comment]
I’m going to close this PR because it’s been a long time since any update has been made. If this is something you’d like to see merged and work is being done, please reopen.

**Pull request closed without merging**
