### PR TITLE
[llvm] add more backend options, fix issues

### LINKED ISSUE #11158: [llvm] build failure
**Host Environment**
- OS: Windows
- Compiler: MSVC 19.25.28614

**To Reproduce**
`./vcpkg install llvm[core,tools,utils,target-x86]:x64-windows`

**Failure logs** 
```
CMake Error at scripts/cmake/vcpkg_fixup_cmake_targets.cmake:116 (message):
  'E:/Tools/vcpkg/packages/llvm_x64-windows/debug/share/clang' does not
  exist.
```
[stdout-x64-windows.log](https://github.com/microsoft/vcpkg/files/4575216/stdout-x64-windows.log)

**Additional context**
Fails when building without `clang` feature. Likely cause:
https://github.com/microsoft/vcpkg/blob/cfc05991f5a73ee4b2df7d9132fc8a5a6a42224e/ports/llvm/portfile.cmake#L169

### LINKED ISSUE #11309: llvm build failure
**Host Environment**
- OS: Windows 10 Pro Version 1909 build 18363.778
- Compiler: MSVC 19.25.28614 for x64

**To Reproduce**
`./vcpkg install llvm llvm[clang-tools-extra] llvm[utils] --triplet x64-windows`

**Failure logs** 

```
[3299/3385] cmd.exe /C "cd . && D:\vcpkg\downloads\tools\cmake-3.14.0-windows\cmake-3.14.0-win32-x86\bin\cmake.exe -E vs_link_dll --intdir=tools\clang\tools\libclang\CMakeFiles\libclang.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1425~1.286\bin\Hostx64\x64\link.exe  @CMakeFiles\libclang.rsp  /out:bin\libclangd.dll /implib:lib\libclangd.lib /pdb:bin\libclangd.pdb /dll /version:10.0 /machine:x64 /debug /INCREMENTAL   && cd ."
FAILED: bin/libclangd.dll lib/libclangd.lib 
cmd.exe /C "cd . && D:\vcpkg\downloads\tools\cmake-3.14.0-windows\cmake-3.14.0-win32-x86\bin\cmake.exe -E vs_link_dll --intdir=tools\clang\tools\libclang\CMakeFiles\libclang.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1425~1.286\bin\Hostx64\x64\link.exe  @CMakeFiles\libclang.rsp  /out:bin\libclangd.dll /implib:lib\libclangd.lib /pdb:bin\libclangd.pdb /dll /version:10.0 /machine:x64 /debug /INCREMENTAL   && cd ."
LINK Pass 1: command "C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1425~1.286\bin\Hostx64\x64\link.exe @CMakeFiles\libclang.rsp /out:bin\libclangd.dll /implib:lib\libclangd.lib /pdb:bin\libclangd.pdb /dll /version:10.0 /machine:x64 /debug /INCREMENTAL /MANIFEST /MANIFESTFILE:tools\clang\tools\libclang\CMakeFiles\libclang.dir/intermediate.manifest tools\clang\tools\libclang\CMakeFiles\libclang.dir/manifest.res" failed (exit code 1104) with the following output:
Microsoft (R) Incremental Linker Version 14.25.28614.0
Copyright (C) Microsoft Corporation.  All rights reserved.

...

LINK : fatal error LNK1104: cannot open file 'dl.lib'
ninja: build stopped: subcommand failed.

```
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4610756/install-x64-windows-dbg-out.log)

### PR DESCRIPTION
**Pull request by yurybura**
This PR adds more LLVM backend options.
Fixes #11158
Fixes #11309

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
llvm is huge, we will test all features locally in a long time.

**Comment by JackBoosY** [comment]
Already successfully tested in `x86-windows`, `x64-windows`, `x64-windows-static`.

**Comment by strega-nil** [comment]
I'm good merging this if you are @JackBoosY @yurybura :)

**Comment by yurybura** [comment]
> I'm good merging this if you are @JackBoosY @yurybura ?

I think I've done. Please merge)

**Comment by strega-nil** [comment]
Alright awesome! Thanks so much for seeing this through @yurybura :)

**Pull request merged**
