### PR TITLE
[scintilla] Update include files path

### LINKED ISSUE #15097: [tesseract] build failure if port scintilla is previously installed
**Host Environment**
- OS: [Microsoft Windows [Version 10.0.19042.685]]
- Compiler: 
  - Visual Studio 2017 Version: 15.9.30  VS Tools Version: 14.16.27023 
     Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27045 for x64
  - Visual Studio 2019 Version: 16.8.3  VS Tools Version: 14.28.29333 
    Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29335 for x64

**To Reproduce**

_**Fresh vanilla vcpkg instance cloned on 12.13.2020 around 18:00 GMT**_

1. Failed Build/Install of port `tesseract`
`.\vcpkg.exe install  scintilla:x64-windows`
Successful Build/Install
`.\vcpkg.exe install tesseract:x64-windows`
Build fails because port `scintilla` installs file `[vcpkg-root]\installed\<triplet>\include\Platform.h` dated 09.11.2020 05:21 size 17,604 which is inadvertently used in `tesseract` port build.
2. Successful Build/Install of port `tesseract`
`.\vcpkg.exe remove scintilla:x64-windows`
Successful Removal
file `[vcpkg-root]\installed\<triplet>\include\Platform.h` dated 09.11.2020 05:21 size 17,604 no longer exists
`.\vcpkg.exe install tesseract:x64-windows`
Successful Build/Install
`.\vcpkg.exe install scintilla:x64-windows`
Successful Build/Install
file `[vcpkg-root]\installed\<triplet>\include\Platform.h` dated 09.11.2020 05:21 size 17,604 now exists again

**Failure logs** 
- Cut and past the appropriate build messages from the console output.
 I captured all output to logs, attached below, but the most import part is as follows:

>Starting package 19/19: tesseract:x64-windows
>Building package tesseract[core]:x64-windows...
>-- Downloading https://github.com/tesseract-ocr/tesseract/archive/4.1.1.tar.gz...
>-- Extracting source D:/Git/vcpkg/test/downloads/tesseract-ocr-tesseract-4.1.1.tar.gz
>-- Applying patch fix-tiff-linkage.patch
>-- Applying patch fix-text2image.patch
>-- Applying patch fix-training-tools.patch
>-- Using source at D:/Git/vcpkg/test/buildtrees/tesseract/src/4.1.1-3a7d5a1d2b.clean
>-- Configuring x64-windows
>-- Building x64-windows-dbg
>CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:145 (message):
>    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j17
>    Working Directory: D:/Git/vcpkg/test/buildtrees/tesseract/x64-windows-dbg
>    See logs for more information:
>      **D:\Git\vcpkg\test\buildtrees\tesseract\install-x64-windows-dbg-out.log** 
**_Attached as file 03a-install-x64-windows-dbg-out.log_**
> 
>Call Stack (most recent call first):
>  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
>  scripts/cmake/vcpkg_install_cmake.cmake:27 (vcpkg_build_cmake)
>  ports/tesseract/portfile.cmake:39 (vcpkg_install_cmake)
>  scripts/ports.cmake:136 (include)
>
>Error: Building package tesseract:x64-windows failed with: BUILD_FAILED
>Please ensure you're using the latest portfiles with `.\vcpkg update`, then
>submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>  Package: tesseract:x64-windows
>  Vcpkg version: 2020.11.12-nohash

- Please attach any additional failure logs mentioned in the console output.
[01-scintilla-install-before-tesseract.log](https://github.com/microsoft/vcpkg/files/5685249/01-scintilla-install-before-tesseract.log)
[02-include-after-first-scintilla-install.log](https://github.com/microsoft/vcpkg/files/5685250/02-include-after-first-scintilla-install.log)
[03-tesseract-install-fail.log](https://github.com/microsoft/vcpkg/files/5685252/03-tesseract-install-fail.log)
[03a-install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5685253/03a-install-x64-windows-dbg-out.log) **starting at line 624 errors with including the `D:\Git\vcpkg\test\installed\x64-windows\include\platform.h(339)` file from port scintilla**
[04-include-after-tessearct-fail-install.log](https://github.com/microsoft/vcpkg/files/5685258/04-include-after-tessearct-fail-install.log)
[05-scintilla-remove.log](https://github.com/microsoft/vcpkg/files/5685259/05-scintilla-remove.log)
[06-include-after-scintilla-remove.log](https://github.com/microsoft/vcpkg/files/5685260/06-include-after-scintilla-remove.log)
[07-tesseract-install-success.log](https://github.com/microsoft/vcpkg/files/5685261/07-tesseract-install-success.log)
[08-include-after-tessearct-success-install.log](https://github.com/microsoft/vcpkg/files/5685263/08-include-after-tessearct-success-install.log)
[09-scintilla-install-after-tesseract.log](https://github.com/microsoft/vcpkg/files/5685265/09-scintilla-install-after-tesseract.log)
[10-include-after-second-scintilla-install.log](https://github.com/microsoft/vcpkg/files/5685266/10-include-after-second-scintilla-install.log)
[11-vcpkg-list.log](https://github.com/microsoft/vcpkg/files/5685267/11-vcpkg-list.log)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.
- Port scintilla has no ports it depends on or depending on it (I guess that would be no upstream/downstream dependencies)?
- _**We may want to move its include files into its own directory `include/scintilla` like has been done with other ports in conflict?**_

### PR DESCRIPTION
**Pull request by NancyLi1013**
**Describe the pull request**

- What does your PR fix? Fixes #15097

 Both `tesseract `and `scintilla `included platform.h, which causes the conflict.

So I move the headers for `scintilla `to _include/scintilla_ .

Add `Supports: !arm` to tesseract

Also remove these codes from ci.baseline.txt, since these triplets can build fine.

```
tesseract:x64-windows=fail
tesseract:x64-windows-static=fail
tesseract:x86-windows=fail
```

Note: No feature needs to test.

### CODE REVIEW

**Comment by NancyLi1013** [comment]
`Tesseract `failed on arm64-windows due to this:

`C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.27.29110\include\immintrin.h(17): fatal error C1189: #error:  This header is specific to X86 and X64 targets`

So will add` Supports: !arm` to `tesseract `.

**Comment by StarGate-One** [comment]
@NancyLi1013 I have tested these changes for port scintilla and they have been working well so far for the past few weeks . 
I am not sure what the opencv and openmp ports changes are for as they have nothing to do with the scintilla/tesseract port files conflicts, so I did not test them, as I use neither port.
Thank you for the work so far!!!
Do you have an estimate when the port scintilla changes will be merged to master?

**Comment by NancyLi1013** [comment]
@StarGate-One 

Thanks for your testing and feedback about this.
 
I will resolve the conflicts. I think we can merge this if all CI checks pass.

**Comment by NancyLi1013** [comment]
zxing-cpp failed on x64-windows-static

`ninja: error: 'D:/installed/x64-windows-static/debug/lib/openblas.lib', needed by 'zxing-cv.exe', missing and no known rule to make it`

But I cannot reproduce this on my local. Need further investigation about this problem.

**Comment by NancyLi1013** [comment]
Closing this PR since these changes has been contained in #15859 and #16508.

**Pull request closed without merging**
