### PR TITLE
[many ports] Updates 2019.05.24

### PR DESCRIPTION
**Pull request by ras0219-msft**

### CODE REVIEW

**Comment by vicroms** [comment]
I see a long list of regressions due to mismatched SHA512s.

**Comment by cenit** [comment]
sorry for interfering, but I almost have a small tear of joy: I can see the CI status 😮 # 596 finally!

**Comment by vicroms** [comment]
@cenit 

Public CI is still in experimental phase, so expect it to be unavailable or break down at times.

**Comment by Rastaban** [comment]
@cenit Feel free to peek on your PR results in the public CI systems.  The [Linux](https://dev.azure.com/vcpkg/public/_build?definitionId=8&_a=summary) pipeline has been stable for a few days and running tests on all PRs.  The [Windows](https://dev.azure.com/vcpkg/public/_build?definitionId=8&_a=summary) pipeline has known issues that I am still ironing out so expect a few false negatives if you use it to look at test results.  I haven't started working on moving the OSX pipeline out yet.  My plan is to bring up a bunch of additional VMs next week (they are currently underpowered) and start enabling the feedback to github once I am comfortable with the stability (It was an accident that it showed up for this PR).  I am also working on documentation I plan on checking in around the time they are enabled to explain how they work - especially how the system caches results from previous runs as that can have unexpected side effects if you are not used to it.

**Comment by Rastaban** [comment]
also @Neumann-A @seanwarren @myd7349 who may be interested in the update to the CI system.

**Comment by cenit** [comment]
@Rastaban thanks, even if in "preview", it's already wonderful and very useful to see regressions on otherwise untested platforms. Looking forward to macOS :)

**Comment by JackBoosY** [comment]
Due to compilation errors in fcl v0.3.4, wait for the author to fix it and update it.
I've uploaded my code to the branch _dev/jack/fcl_0.3.4_.

**Comment by Rastaban** [comment]
resolved merge conflict for hpx

**Comment by JackBoosY** [comment]
Due to **compilation problems** with the port **nvtt** source code, and we can **NOT** solve it now, so I don't upgrade the port  **nvtt** temporarily.
See: [issue](https://developercommunity.visualstudio.com/content/problem/32196/msvc-cant-compile-a-templated-using-without-instan.html).

**Comment by PhoebeHui** [comment]
Finally, there is no failed port blocked this PR! ☺

Summary the failed ports that need to summit a separate PRs.

Port | Status
-- | --
vlpp | Done
Aws-sdk-cpp | Done
asio and tinyobjloader | Done
Flann | done
Libffi | done
itk | done
libtins | done
xxhash | done
paho-mqtt | done
arb | done
harfbuzz | done
libopusenc | done
aws-c-common | done
nvtt | done
Mongo-c-driver  and libbson | In progress
xmsh | In progress
taglib | In progress
openvdb | In progress
Forge draco flatbuffers | In progress
qhull | In progress
lcm | In progress
kd-soap | In progress
qca | In progress
libmupdf | In progress

**Comment by ras0219-msft** [comment]
8ac9039 is good to merge once passing.

**Comment by PhoebeHui** [comment]
@ras0219-msft, the latest results failed to find patch 'ports/mosquitto/archive-dest.patch' I noticed you reference in portfile.cmake, but didn't add the patch file to the port in https://github.com/microsoft/vcpkg/pull/6618/commits/f93e5329e52f91f8e22b7e0a273bec39b7d5adb5, could you summit the patch file as well?

**Pull request merged**
