### PR TITLE
[unrar] Fix library linkage

### PR DESCRIPTION
**Pull request by dbarkar**
Currently, linking library doesn't add unrar.lib to the target, so you get unresolved externals.
This patch fixes the problem.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by dg0yt** [comment]
Good catch, but AFAICS the config remains unable to properly carry the debug lib.
(This port really needs more care with regard to version, platform support, and config.)

**Comment by dbarkar** [comment]
> the config remains unable to properly carry the debug lib.

Fixed now, thanks. 

> This port really needs more care with regard to version, platform support, and config.

It surely does! Official source archive contains vcxproj for Windows and pure (!) makefile for *NIX, so it's possbile to add other platforms, though it's hard to imagine. Unless we add vendored CMakeLists.txt...

I didn't touch anything else, only fixed one issue. I don't have much experience with vcpkg to see the full picture, but if there is something I can help with, let me know.

**Comment by MonicaLiu0311** [comment]
usage:
```
unrar provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(unofficial-unrar CONFIG REQUIRED)
    target_link_libraries(main PRIVATE unofficial::unrar::unrar)
```

When testing usage, the following error occurs:
```
>------ Build All started: Project: CMakeFindUsage, Configuration: x64-Debug ------
  MSBuild version 17.5.0+6f08c67f3 for .NET Framework
  
    Checking Build System
    Building Custom Rule C:/Users/monica/source/repos/CMakeFindUsage/CMakeFindUsage/CMakeLists.txt
    CMakeFindUsage.cpp
E:\unrar\installed\x64-windows\include\unrar.h(126,23): error C2143: syntax error: missing ')' before '*' 
E:\unrar\installed\x64-windows\include\unrar.h(126,23): error C2143: syntax error: missing ';' before '*' 
E:\unrar\installed\x64-windows\include\unrar.h(126,37): error C2059: syntax error: ')' 
E:\unrar\installed\x64-windows\include\unrar.h(126,39): error C2065: 'UINT': undeclared identifier 
E:\unrar\installed\x64-windows\include\unrar.h(126,44): error C2146: syntax error: missing ')' before identifier 'msg' 
E:\unrar\installed\x64-windows\include\unrar.h(151,17): error C3646: 'Callback': unknown override specifier 
E:\unrar\installed\x64-windows\include\unrar.h(152,17): error C3646: 'UserData': unknown override specifier 
E:\unrar\installed\x64-windows\include\unrar.h(163,21): error C2143: syntax error: missing ')' before '*' 
E:\unrar\installed\x64-windows\include\unrar.h(163,21): error C2143: syntax error: missing ';' before '*' 
E:\unrar\installed\x64-windows\include\unrar.h(163,35): error C2059: syntax error: ')' 
E:\unrar\installed\x64-windows\include\unrar.h(164,21): error C2143: syntax error: missing ')' before '*' 
E:\unrar\installed\x64-windows\include\unrar.h(164,21): error C2143: syntax error: missing ';' before '*' 
E:\unrar\installed\x64-windows\include\unrar.h(164,37): error C2059: syntax error: ')' 
E:\unrar\installed\x64-windows\include\unrar.h(170,8): error C2146: syntax error: missing ';' before identifier 'PASCAL' 
E:\unrar\installed\x64-windows\include\unrar.h(171,1): error C2086: 'int HANDLE': redefinition 
  E:\unrar\installed\x64-windows\include\unrar.h(170,1): message : see declaration of 'HANDLE' [C:\Users\monica\source\repos\CMakeFindUsage\out\build\x64-Debug\CMakeFindUsage\main.vcxproj]
E:\unrar\installed\x64-windows\include\unrar.h(171,8): error C2146: syntax error: missing ';' before identifier 'PASCAL' 
E:\unrar\installed\x64-windows\include\unrar.h(172,30): error C2377: 'PASCAL': redefinition; typedef cannot be overloaded with any other symbol 
  E:\unrar\installed\x64-windows\include\unrar.h(163,14): message : see declaration of 'PASCAL' [C:\Users\monica\source\repos\CMakeFindUsage\out\build\x64-Debug\CMakeFindUsage\main.vcxproj]
E:\unrar\installed\x64-windows\include\unrar.h(172,15): error C2146: syntax error: missing ';' before identifier 'RARCloseArchive' 
E:\unrar\installed\x64-windows\include\unrar.h(172,38): error C2146: syntax error: missing ')' before identifier 'hArcData' 
E:\unrar\installed\x64-windows\include\unrar.h(173,8): error C2086: 'int PASCAL': redefinition 
  E:\unrar\installed\x64-windows\include\unrar.h(172,8): message : see declaration of 'PASCAL' [C:\Users\monica\source\repos\CMakeFindUsage\out\build\x64-Debug\CMakeFindUsage\main.vcxproj]
...
Build All failed.
```

<details>
<summary><b>CMakeFindUsage.cpp</b></summary>
<pre>
#include &#60;iostream&#62;
#include "unrar.h"

using namespace std;

int main()
{
        cout << "Hello CMake." << endl;
        return 0;
}
</pre></details>


<details>
<summary><b>CMakeLists.txt</b></summary>
<pre>
cmake_minimum_required (VERSION 3.8)

set(CMAKE_TOOLCHAIN_FILE "E:/unrar/scripts/buildsystems/vcpkg.cmake")

project ("CMakeFindUsage")

find_package(unofficial-unrar CONFIG REQUIRED)

add_executable (main "CMakeFindUsage.cpp")

target_link_libraries(main PRIVATE unofficial::unrar::unrar)
</pre></details>

**Comment by dbarkar** [comment]
@MonicaLiu0311 you can see from logs that it's missing Windows-specific defines.
You should put `#include <windows.h>` or `#define _UNIX` before the inclusion of `unrar.h`.
This is the official behavior.

**Comment by MonicaLiu0311** [comment]
> @MonicaLiu0311 you can see from logs that it's missing Windows-specific defines. You should put `#include <windows.h>` or `#define _UNIX` before the inclusion of `unrar.h`. This is the official behavior.

The usage test passed(header files found): 
```
unrar provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(unofficial-unrar CONFIG REQUIRED)
    target_link_libraries(main PRIVATE unofficial::unrar::unrar)
```

**Review by MonicaLiu0311 — APPROVED** [review]

**Pull request merged**
