### PR TITLE
[sundials] Update to 6.7.0; add features

### PR DESCRIPTION
**Pull request by jbuonagurio**
This PR updates SUNDIALS to 6.7.0 and adds new features to control which solvers and backends are included in the build:

- `arkode`, `cvode`, `cvodes`, `ida`, `idas`, `kinsol`: These are the solvers included in SUNDIALS. Consistent with previous versions, all solvers are enabled by default.
- `ginkgo`, `hypre`, `klu`, `magma`: These are various linear algebra libraries which can be used as SUNDIALS backends (primarily for LU factorization). All available backends with a vcpkg port are supported with this PR.
- `cuda`, `lapack`, `mpi`, `openmp`: These are lower-level computational backends used by both SUNDIALS and external libraries.

Checklist:

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [x] The "supports" clause reflects platforms that may be fixed by this new version.
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by jbuonagurio** [comment]
Sorry, I unchecked draft too soon after I realized that not all external libraries were getting fully linked. I added a `test` feature for further validation. Here's the build output on Windows with every feature enabled: `vcpkg install sundials[cuda,ginkgo,hypre,klu,lapack,magma,mpi,openmp,test]:x64-windows-static-md`

[config-x64-windows-static-md-out.log](https://github.com/microsoft/vcpkg/files/14357971/config-x64-windows-static-md-out.log)
[install-x64-windows-static-md-rel-out.log](https://github.com/microsoft/vcpkg/files/14357972/install-x64-windows-static-md-rel-out.log)

I've only tested with one triplet so far (mainly because `magma` takes well over an hour to build), but so far so good. All tests passing.

**Comment by JonLiu1993** [comment]
@jbuonagurio, Thanks for your PR, when I tested the feature by command `./vcpkg install sundials[*]:x86-windows` I get this error, please take a look:
````
src\nvector\manyvector\CMakeFiles\sundials_nvecmpimanyvector_shared.dir/manifest.res" failed (exit code 1120) with the following output:
   Creating library bin\sundials_nvecmpimanyvector.lib and object bin\sundials_nvecmpimanyvector.exp
nvector_manyvector.c.obj : error LNK2019: unresolved external symbol MPI_Allreduce referenced in function N_VMake_MPIManyVector
nvector_manyvector.c.obj : error LNK2019: unresolved external symbol MPI_Comm_rank referenced in function SubvectorMPIRank
nvector_manyvector.c.obj : error LNK2019: unresolved external symbol MPI_Comm_compare referenced in function N_VNew_MPIManyVector
nvector_manyvector.c.obj : error LNK2019: unresolved external symbol MPI_Comm_dup referenced in function N_VMake_MPIManyVector

nvector_manyvector.c.obj : error LNK2019: unresolved external symbol MPI_Comm_free referenced in function N_VNew_MPIManyVector

bin\sundials_nvecmpimanyvector.dll : fatal error LNK1120: 5 unresolved externals
````

**Comment by jbuonagurio** [comment]
Thanks for helping test it! This should be fixed with https://github.com/microsoft/vcpkg/pull/36885/commits/78aff889fd01ef0906340ebb945a2684ef075ec0. SUNDIALS doesn't link with MPI by default unless `SUNDIALS_LOGGING_ENABLE_MPI` is turned on. It was recently changed to default off in the v6.3.0 release.

**Comment by JonLiu1993** [comment]
Now there is no problem when testing x86-windows and x64-windows locally, but I encountered an error when testing x64-windows.
image
[install-x64-windows-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/14383841/install-x64-windows-static-dbg-out.log)

**Comment by jbuonagurio** [comment]
Looks like one of the libraries is forcing dynamic CRT linkage and it's probably LAPACK. I might need to disable some `test` feature targets for triplets with `VCPKG_CRT_LINKAGE=static`. If you build the `lapack-reference` port using that triplet it warns about that:

```
-- VCPKG_CRT_LINKAGE linkage for lapack-reference using vcpkg's internal gfortran cannot be static due to linking against MinGW libraries. Forcing dynamic CRT linkage
-- VCPKG_LIBRARY_LINKAGE linkage for lapack-reference using vcpkg's internal gfortran cannot be static due to linking against MinGW libraries. Forcing dynamic library linkage
```

I'll see what I can do.

**Comment by BillyONeal** [comment]
> I'll see what I can do.

I interpreted this as 'I'm still working on it', so I made this PR a draft. Please mark 'ready for review' when you're happy :)

**Comment by JonLiu1993** [comment]
Duplicate of PR https://github.com/microsoft/vcpkg/pull/41414

**Pull request closed without merging**
