### PR TITLE
[lua] update to 5.4.0

### PR DESCRIPTION
**Pull request by id6tm-mteterel**

### CODE REVIEW

**Comment by JackBoosY** [comment]
shiva:
```
CMake Error in modules/lua/CMakeLists.txt:
  Target "lua" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "D:/buildtrees/shiva/src/1.0-2860004d47.clean/modules/lua/LUA_INCLUDE_DIR-NOTFOUND"

  which is prefixed in the source directory.
```

**Comment by mteterel** [comment]
These packages depend exclusively on Lua 5.3, any chance we push 5.4 under another port name ?

**Comment by JackBoosY** [comment]
@mteterel 
Since this PR is a minor version update of lua, we should not separate this version into a new port. 
So we can choose one of the following ways:
-Update lua dependent ports to adapt to this version
-Wait for lua dependent port updates and open an issues to upstream

**Comment by NancyLi1013** [comment]
Duplicated to #12352.

**Comment by BillyONeal** [comment]
Closed due to being an exact duplicate of the other PR.

Thanks for your contribution!

**Pull request closed without merging**
