### PR TITLE
 Update HDF5 to 1.10.5 and build both static and shared hdf5 libs

### PR DESCRIPTION
**Pull request by Neumann-A**
reenabled static build if linkage is dynamic.
This is default HDF5 behavior and HDF5 also exports the targets for it.
(I also have a actual use case for this default behavior)

Changed szip accordingly to also build static in dynamic linkage. (default behavior)

Fixed the config paths.
find_package was not working due to files being a subfolder too deep. (share/hdf5/hdf5/)

Private linkage was changed upstream. -> Removed unnecessary patches.

### CODE REVIEW

**Comment by Neumann-A** [comment]
TODO: Fix Hdf5 target file to actually find libszip

**Comment by Neumann-A** [comment]
problem was: trying to link szip-static instead of libszip. Solved now with latest commit

**Comment by ras0219-msft** [comment]
One issue you may run in to is how the szip port has been modified. It appears to be using the `vcpkg_extract_source_archive()` command, which has issues when dealing with patches (specifically, you can't _remove_ patches -- they'll still be applied to our local cached copy).

The way to fix this inconsistency is to switch to using `vcpkg_extract_source_archive_ex()`[1] which will use hashes to ensure each patchset gets a different directory.

[1] https://github.com/Microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_extract_source_archive_ex.md

**Comment by Neumann-A** [comment]
TODO: Fix target for RelWithDebugInfo linking debug hdf5 libraries.

**Comment by luzpaz** [comment]
Thanks for this PR!
Btw, is it worth addressing #4028 in this PR as well ?

**Comment by Neumann-A** [comment]
@luzpaz 
#4028 is in my eyes not an issue. See my response there.

**Comment by Voskrese** [comment]
not ENABLE_PARALLEL, use HDF5_ENABLE_PARALLEL

```
if ("parallel" IN_LIST FEATURES)
    set(HDF5_ENABLE_PARALLEL ON)
else()
    set(HDF5_ENABLE_PARALLEL OFF)
endif()
```

**Comment by luzpaz** [comment]
1.10.5 has been released https://www.hdfgroup.org/2019/02/hdf5-1-10-5-release-newsletter-168/

**Comment by Neumann-A** [comment]
@poiuytreec how are your comments related to hdf5. Seems more like other issues?

**Comment by Cheney-W** [comment]
Here are the test results. The left results column is the latest commit to this PR, the right results column is test results from master: Skip typically means somthing it has a dependancy on failed so it was not built.
```
Processing x64-linux                      601 vs 605
    alembic                                                     Skip vs Fail
    hdf5                          **regression**                Fail vs Pass
    highfive                                                    Skip vs Fail
    itk                                                         Skip vs Fail
    kealib                                                      Skip vs Pass
    matio                                                       Skip vs Fail
    netcdf-c                                                    Skip vs Pass
    netcdf-cxx4                                                 Skip vs Pass
    vtk                                                         Skip vs Fail
Processing x64-osx                        589 vs 596
    alembic                                                     Skip vs Fail
    hdf5                          **regression**                Fail vs Pass
    highfive                                                    Skip vs Pass
    itk                                                         Skip vs Fail
    kealib                                                      Skip vs Pass
    matio                                                       Skip vs Fail
    netcdf-c                                                    Skip vs Pass
    netcdf-cxx4                                                 Skip vs Pass
    vtk                                                         Skip vs Pass
    vtk-dicom                                                   Skip vs Pass
Processing x64-windows-static             769 vs 773
    highfive                      **regression**                Fail vs Pass
    kealib                        **regression**                Fail vs Pass
    matio                         **regression**                Fail vs Pass
    netcdf-cxx4                   **regression**                Fail vs Pass
```
Here are all of the failures logs:
[failureLogs.zip](https://github.com/Microsoft/vcpkg/files/2935073/failureLogs.zip)

**Comment by Neumann-A** [comment]
> Processing x64-windows-static             769 vs 773
    highfive                      **regression**                Fail vs Pass
    kealib                        **regression**                Fail vs Pass
    matio                         **regression**                Fail vs Pass
    netcdf-cxx4                   **regression**                Fail vs Pass

highfive, kealib and netcdf-cxx4 probably need and updated CMake version to not regress.
Error is:
> CMake Error at D:/downloads/tools/cmake-3.12.4-windows/cmake-3.12.4-win32-x86/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
>   Could NOT find HDF5 (missing: HDF5_LIBRARIES) (found version "1.10.5")  

so it finds HDF5 but it find_package is not setting the HDF5_LIBRARIES correctly for 1.10.5.
Will look at it if I got the time

Regression in matio is actually a port bug in matio.  Error reads:
> Target "libmatio" links to target "hdf5::hdf5-shared" but the target was
  not found.

so libmatio is actually linking the wrong HDF5 target in x64-windows-static. 
But be careful with matio and hdf5 >1.8.  It states in the readme:
>        2.1.2 HDF5
>             Support for MAT file version 7.3 requires the HDF5 library. This library can be downloaded from The HDF Group website (http://www.hdfgroup.org/). MATIO requires HDF5 version 1.8.x, and must be built with default API version 1.8 (i.e. '--with-default-api-version=v18').

vcpkg is probably not supporting matio correctly currently. 


Concerning the failures in OSX and LINUX build: Please comment the requirements for some patches in the future. I didn't know that the szip patch is required for these targets.

**Comment by Neumann-A** [comment]
Just checked highfive and it is just doing:
`find_package(HDF5 QUIET REQUIRED)`

probably need to also set `HDF5_USE_STATIC_LIBRARIES` in static builds.

**Comment by Neumann-A** [comment]
did not test netcdf-cxx4 due to the perl download taking way too long without any visible progress

**Comment by Neumann-A** [comment]
@Cheney-W: Can I get a new list of regressions + logs? On Windows everything which before failed seems to work now and on Linux (in docker using nvidia/opengl:1.0-glvnd-devel-ubuntu18.04 + devtools) I tested to build VTK 8.1 and it worked. So i would like to know where the errors are.

**Comment by Neumann-A** [comment]
closing in favor of #5574

**Pull request closed without merging**
