### PR TITLE
[opentelemetry-cpp] update contrib repo while keeping the versioning

### PR DESCRIPTION
**Pull request by ThomsonTan**

### CODE REVIEW

**Review by MonicaLiu0311 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Can you explain why the version number exposed to users doesn't change? In general if we are giving them different sources then the version should change...

**Comment by dg0yt** [comment]
@BillyONeal It doesn't change the main source but extra downloads ("contrib").

**Comment by ThomsonTan** [comment]
Yes, the "contrib" repo is not versioned independently than the main repo.

**Comment by BillyONeal** [comment]
I think we need to talk to opentelemetry-cpp maintainers and choose one of the following options:

1. opentelemetry-cpp-contrib moves to a separate port which owns versioning of that source code. For example, one port may only publish which version of the sources are intended.
2. contrib can only be updated in vcpkg when opentelemetry-cpp itself updates. This may turn into an ask for that to be released more frequently.

**Comment by ThomsonTan** [comment]
Will update the port after a new release from opentelemetry-cpp.

**Pull request closed without merging**
