### PR TITLE
[corrade] Add the /permissive- option

### PR DESCRIPTION
**Pull request by Cheney-W**
Corrade install failed with an error C2666 in an internal version, this issue has been fixed. 
This fix need the /permissive- option, so I add a patch for this option.

Furthermore, this option will not affect the installation of corrade on stable VS after tested,

### CODE REVIEW

**Comment by janisozaur** [comment]
Can I request you amend the commit message to feature the name of port?

`[corrade] Add the /permissive- option`

**Comment by janisozaur** [comment]
@Cheney-W i see you modified the PR title, I assume in response to my comment. I mentioned the commit message's subject line, though.

**Comment by Cheney-W** [comment]
@janisozaur , Sorry for delay this reply. I have changed the commit name, thanks for your reminder.

**Comment by mosra** [comment]
@Cheney-W can you elaborate on what was the error? Is there something I can do upstream, besides adding `/permissive-` as well? OTOH, I know about a few cases where using `/permissive-` would cause ICEs on older compiler versions, that's why I hesitated to use it.

**Pull request merged**
