### PR TITLE
Update proxy failure hint

### LINKED ISSUE #17752: [vcpkg-tool] pr 49 cause proxy no use
**Describe the bug**

I had notice vcpkg.exe of may version has the ability to set proxy auto. But it no use acctually. And it will override the envs I set.

**To Reproduce**
1. install vcpkg.exe version may
2. use fiddler.exe set a proxy
3. run vcpkg
4. fiddler can't get any internet flow of vcpkg.exe

> Note:
>
> the flow in Chinese is called 流量， it means a internet swap between pc and other computers. But I don't know English is called flow or not.

**Expected behavior**

fiddler can catch flow of vcpkg.exe

**Failure logs** 

for vcpkg5.exe:
(no HTTP_PROXY set)
```
>vcpkg5.exe install laszip
Computing installation plan...
The following packages will be built and installed:
    laszip[core]:x64-windows -> 3.4.3
Detecting compiler hash for triplet x64-windows...
-- Setting HTTP_PROXY environment variables to http://127.0.0.1:8889
-- Setting HTTPS_PROXY environment variables to https://127.0.0.1:8889
Could not locate cached archive: C:\Users\Drago\AppData\Local\vcpkg\archives\58\589d2f070bea4b545f19a105f44b9c5b5dfeaf40.zip
Starting package 1/1: laszip:x64-windows
Building package laszip[core]:x64-windows...
-- Downloading https://github.com/LASzip/LASzip/archive/1ab671e42ff1f086e29d5b7e300a5026e7b8d69b.tar.gz -> LASzip-LASzip-1ab671e42ff1f086e29d5b7e300a5026e7b8d69b.tar.gz...
-- Downloading https://github.com/LASzip/LASzip/archive/1ab671e42ff1f086e29d5b7e300a5026e7b8d69b.tar.gz... Failed. Status: 4;"A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision."
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:184 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".

      If error with status 4 (Issue #15434),
      try setting "http://user:password@your-proxy-ip-address:port/".

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:147 (vcpkg_download_distfile)
  ports/laszip/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:142 (include)


Error: Building package laszip:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: laszip:x64-windows
  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9

Additionally, attach any relevant sections from the log files above.
```

for vcpkg4.exe:

```
>set HTTPS_PROXY=localhost:8889

>set HTTP_PROXY=localhost:8889

>vcpkg.exe install laszip
Computing installation plan...
The following packages will be built and installed:
    laszip[core]:x64-windows -> 3.4.3
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\Drago\AppData\Local\vcpkg\archives\58\589d2f070bea4b545f19a105f44b9c5b5dfeaf40.zip
Starting package 1/1: laszip:x64-windows
Building package laszip[core]:x64-windows...
-- Downloading https://github.com/LASzip/LASzip/archive/1ab671e42ff1f086e29d5b7e300a5026e7b8d69b.tar.gz -> LASzip-LASzip-1ab671e42ff1f086e29d5b7e300a5026e7b8d69b.tar.gz...
-- Extracting source D:/Documents/Tools/dev/vcpkg/downloads/LASzip-LASzip-1ab671e42ff1f086e29d5b7e300a5026e7b8d69b.tar.gz
-- Using source at D:/Documents/Tools/dev/vcpkg/buildtrees/laszip/src/26e7b8d69b-860c05dba9.clean
```

### PR DESCRIPTION
**Pull request by reitowo**
**Describe the pull request**

- #### What does your PR fix?  
  Fixes #17752 #17688

- #### Related PR
  https://github.com/microsoft/vcpkg-tool/pull/77 https://github.com/microsoft/vcpkg-tool/pull/49

As the hint is misleading, we should point out some possible causes in the hint. 
Also, a bug cause is presented in the hint, and when the (https://github.com/microsoft/vcpkg-tool/pull/77) is merged, another PR will be opened to delete that hint.

### CODE REVIEW

**Comment by JackBoosY** [comment]
Waiting for https://github.com/microsoft/vcpkg/pull/17797 merge.

**Review by JackBoosY — APPROVED** [review]

**Comment by cnSchwarzer** [comment]
Kindly reminder: https://github.com/microsoft/vcpkg/pull/17797 merged :)

**Comment by cnSchwarzer** [comment]
Although https://github.com/microsoft/vcpkg-tool/pull/77 get merged, the next PR to remove the bug hint will wait for the next vcpkg's version release.

**Review by ras0219 — APPROVED** [review]

**Pull request merged**
