### PR TITLE
[proj] Disable docs

### LINKED ISSUE #25497: [proj] build failure
**Host Environment**
- OS: Windows 10 20H2 19042.1706
- Compiler: Visual Studio 2019 (Build engine 16.11.2.50704)

**To Reproduce**
`./vcpkg install proj:x64-windows`

**Failure logs**
```
Computing installation plan...
The following packages will be built and installed:
    proj[core,net,tiff]:x64-windows -> 9.0.1
Detecting compiler hash for triplet "x64-windows"...
-- Using HTTP(S)_PROXY in environment variables.
Restored 0 packages from D:\cschulte\AppData\Local\vcpkg\archives in 241 us. Use --debug to see more details.
Installing 1/1 proj:x64-windows...
Building proj[core,net,tiff]:x64-windows...
-- Using cached OSGeo-PROJ-9.0.1.tar.gz.
-- Cleaning sources at D:/cschulte/DevEnv64/vcpkg/buildtrees/proj/src/9.0.1-b314c5518d.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/cschulte/DevEnv64/vcpkg/downloads/OSGeo-PROJ-9.0.1.tar.gz
-- Applying patch fix-win-output-name.patch
-- Applying patch fix-proj4-targets-cmake.patch
-- Applying patch tools-cmake.patch
-- Using source at D:/cschulte/DevEnv64/vcpkg/buildtrees/proj/src/9.0.1-b314c5518d.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
    Command failed: D:/cschulte/DevEnv64/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: D:/cschulte/DevEnv64/vcpkg/buildtrees/proj/x64-windows-dbg
    See logs for more information:
      D:\cschulte\DevEnv64\vcpkg\buildtrees\proj\install-x64-windows-dbg-out.log
      D:\cschulte\DevEnv64\vcpkg\buildtrees\proj\install-x64-windows-dbg-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/proj/portfile.cmake:41 (vcpkg_cmake_install)
  scripts/ports.cmake:146 (include)


error: building proj:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+proj
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[proj]+Build+error
Include '[proj] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-06-17-9268e366206712e38102b28dbd1617697a99ff2e
    vcpkg-scripts version: 019027ada 2022-06-21 (8 days ago)

You can also use the prefilled template from D:\cschulte\DevEnv64\vcpkg\installed\vcpkg\issue_body.md.
```
**Additional context**
This issue does not appear with the previous version of proj. Indeed from version 9.0.0 to 9.0.1 man install path has been modified from share/man/man1 to $CMAKE_INSTALL_MANDIR/man1 (https://github.com/OSGeo/PROJ/commit/1461c9b30d93941e858cf68c01117b83f095c3d6). I clearly have the needed privileges on the vcpkg folder as every other install works correctly. As he tries to create path /man1 I don't know where he is trying to create this folder.
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/9017349/install-x64-windows-dbg-out.log)
[install-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/9017350/install-x64-windows-dbg-err.log)

### PR DESCRIPTION
**Pull request by Thomas1664**
**Describe the pull request**

- #### What does your PR fix?
  Fixes #25497
  Man files shouldn't be installed by default.

### CODE REVIEW

**Comment by Adela0814** [comment]
Please convert this PR to draft, we need to wait for the discussion result of issue https://github.com/microsoft/vcpkg/issues/25497 to decide how to fix it. thanks.

**Comment by dg0yt** [comment]
> Please convert this PR to draft, we need to wait for the discussion result of issue #25497 to decide how to fix it. thanks.

No discussion needed. I would have submitted the same PR.

**Comment by Thomas1664** [comment]
> Please convert this PR to draft, we need to wait for the discussion result of issue https://github.com/microsoft/vcpkg/issues/25497 to decide how to fix it. thanks.

Nicole confirmed the issue on Discord

**Review by Adela0814 — APPROVED** [review]

**Comment by JackBoosY** [comment]
Can you please use the [official patch](https://github.com/OSGeo/PROJ/pull/3245) to fix this instead?

Thanks.

**Comment by dg0yt** [comment]
> Can you please use the [official patch](https://github.com/OSGeo/PROJ/pull/3245) to fix this instead?

The official patch will restore installation of man pages. Do we really want that?

**Comment by Thomas1664** [comment]
> Can you please use the [official patch](https://github.com/OSGeo/PROJ/pull/3245) to fix this instead?
> 
> Thanks.

This would violate "[Do not install docs by default](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#do-not-build-testsdocsexamples-by-default)".

**Comment by JackBoosY** [comment]
Okay. LGTM.

**Pull request merged**
