### PR TITLE
[winpcap] Fix error hash

### LINKED ISSUE #21242: [winpcap] build failure
**Host Environment**
- OS: Windows
- Compiler: MSVC 2019

**To Reproduce**
`vcpkg install winpcap:x86-windows`

**Failure logs** 
Error: Failed to download from mirror set:
File does not have the expected hash:
             url : [ https://www.winpcap.org/misc/copyright.htm ]
       File path : [ C:\workspace\vcpkg\downloads\Wpcap_license.htm.14496.part ]
   Expected hash : [ 661e848f229612a4354e8243cdb0cb7ef387abc8933412b8c09ccfcaa3335143a958ea9ec9da558f89afe71afea29f0548872e3544ea51144c297a1aa1276718 ]
     Actual hash : [ bb2519e8f3d02c408fa3f2ef339adda1cc31338d05d2fa4ce25d5369427243fd3e2abc4b21aa654b2be5791f53c2281847a4a15778ffcb90576fd166140c7d2e ]
...

**Additional context**
It looks like the copyright page has been updated. (Even though the page says 'Last modified: Friday, July 2, 2010 10:02' at the bottom, that is not true. Comparing the license with one from an older vcpkg installation on another machine shows there are some small differences in the mark-up.

### PR DESCRIPTION
**Pull request by JonLiu1993**
**Describe the pull request**

- #### What does your PR fix?  
  Fixes #21242 
  Update the hash of the downloaded mirror, upadte hash can successfully download the mirror

### CODE REVIEW

**Review by NancyLi1013 — APPROVED** [review]

**Comment by herrwusel** [comment]
After applying the patch I get this error:
```
.\vcpkg.exe install winpcap
Computing installation plan...
The following packages will be built and installed:
    winpcap[core]:x86-windows -> 4.1.3#6
Detecting compiler hash for triplet x86-windows...
Restored 0 packages from C:\Users\jakobhabedank\AppData\Local\vcpkg\archives in 138 us. Use --debug to see more details.
Starting package 1/1: winpcap:x86-windows
Building package winpcap[core]:x86-windows...
-- Using cached WpcapSrc_4_1_3.zip.
-- Downloading https://www.winpcap.org/misc/copyright.htm -> Wpcap_license.htm...
-- Extracting source C:/src/vcpkg/downloads/WpcapSrc_4_1_3.zip
-- Applying patch C:/src/vcpkg/buildtrees/winpcap/src/packetNtx.patch
-- Applying patch C:/src/vcpkg/buildtrees/winpcap/src/wpcap.patch
-- Applying patch C:/src/vcpkg/ports/winpcap/create_lib.patch
-- Applying patch C:/src/vcpkg/ports/winpcap/fix-create-lib-batch.patch
-- Using source at C:/src/vcpkg/buildtrees/winpcap/src/4_1_3-2020b05bdd.clean
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: devenv.exe Packet.sln /Upgrade
    Working Directory: C:/src/vcpkg/buildtrees/winpcap/src/4_1_3-2020b05bdd.clean/packetNtx/Dll/Project
    Error code: The system cannot find the file specified
    See logs for more information:

Call Stack (most recent call first):
  ports/winpcap/portfile.cmake:56 (vcpkg_execute_required_process)
  scripts/ports.cmake:142 (include)


Error: Building package winpcap:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  package: winpcap[core]:x86-windows -> 4.1.3#6
  vcpkg version: 2021-11-02-af04ebf6274fd6f7a941bff4662b3955c64f6f42
  vcpkg-tool version: 70033dbb3 2021-11-09 (14 hours ago)

Additionally, attach any relevant sections from the log files above.
```

**Comment by JonLiu1993** [comment]
@herrwusel, thanks for your testing, I git checkout my branch and successfully installed it again, maybe you can git clone my repo and try again:
````
PS F:\test7\vcpkg> ./vcpkg install winpcap --editable
Computing installation plan...
The following packages will be built and installed:
    winpcap[core]:x86-windows -> 4.1.3#6
Restored 0 packages from C:\Users\vzhli17\AppData\Local\vcpkg\archives in 148.6 us. Use --debug to see more details.
Starting package 1/1: winpcap:x86-windows
Building package winpcap[core]:x86-windows...
-- Using cached WpcapSrc_4_1_3.zip.
-- Using cached Wpcap_license.htm.
-- Extracting source F:/test7/vcpkg/downloads/WpcapSrc_4_1_3.zip
-- Applying patch F:/test7/vcpkg/buildtrees/winpcap/src/packetNtx.patch
-- Applying patch F:/test7/vcpkg/buildtrees/winpcap/src/wpcap.patch
-- Applying patch F:/test7/vcpkg/ports/winpcap/create_lib.patch
-- Applying patch F:/test7/vcpkg/ports/winpcap/fix-create-lib-batch.patch
-- Using source at F:/test7/vcpkg/buildtrees/winpcap/src/4_1_3-2020b05bdd
-- Building F:/test7/vcpkg/buildtrees/winpcap/src/4_1_3-2020b05bdd/packetNtx/Dll/Project/Packet.sln for Release
-- Building F:/test7/vcpkg/buildtrees/winpcap/src/4_1_3-2020b05bdd/packetNtx/Dll/Project/Packet.sln for Debug
-- Downloading https://sourceforge.net/projects/winflexbison//files/winflexbison-2.5.16.zip/download;https://sourceforge.net/projects/winflexbison//files/winflexbison-2.5.16.zip/download?use_mirror=cfhcable;https://sourceforge.net/projects/winflexbison//files/winflexbison-2.5.16.zip/download?use_mirror=pilotfiber;https://sourceforge.net/projects/winflexbison//files/winflexbison-2.5.16.zip/download?use_mirror=gigenet;https://sourceforge.net/projects/winflexbison//files/winflexbison-2.5.16.zip/download?use_mirror=versaweb;https://sourceforge.net/projects/winflexbison//files/winflexbison-2.5.16.zip/download?use_mirror=ayera;https://sourceforge.net/projects/winflexbison//files/winflexbison-2.5.16.zip/download?use_mirror=netactuate;https://sourceforge.net/projects/winflexbison//files/winflexbison-2.5.16.zip/download?use_mirror=phoenixnap;https://sourceforge.net/projects/winflexbison//files/winflexbison-2.5.16.zip/download?use_mirror=astuteinternet;https://sourceforge.net/projects/winflexbison//files/winflexbison-2.5.16.zip/download?use_mirror=freefr;https://sourceforge.net/projects/winflexbison//files/winflexbison-2.5.16.zip/download?use_mirror=netcologne;https://sourceforge.net/projects/winflexbison//files/winflexbison-2.5.16.zip/download?use_mirror=deac-riga;https://sourceforge.net/projects/winflexbison//files/winflexbison-2.5.16.zip/download?use_mirror=excellmedia;https://sourceforge.net/projects/winflexbison//files/winflexbison-2.5.16.zip/download?use_mirror=iweb;https://sourceforge.net/projects/winflexbison//files/winflexbison-2.5.16.zip/download?use_mirror=jaist;https://sourceforge.net/projects/winflexbison//files/winflexbison-2.5.16.zip/download?use_mirror=jztkft;https://sourceforge.net/projects/winflexbison//files/winflexbison-2.5.16.zip/download?use_mirror=managedway;https://sourceforge.net/projects/winflexbison//files/winflexbison-2.5.16.zip/download?use_mirror=nchc;https://sourceforge.net/projects/winflexbison//files/winflexbison-2.5.16.zip/download?use_mirror=netix;https://sourceforge.net/projects/winflexbison//files/winflexbison-2.5.16.zip/download?use_mirror=ufpr;https://sourceforge.net/projects/winflexbison//files/winflexbison-2.5.16.zip/download?use_mirror=tenet -> winflexbison-2.5.16.zip...
-- Extracting source F:/test7/vcpkg/downloads/winflexbison-2.5.16.zip
-- Using source at F:/test7/vcpkg/downloads/tools/winflexbison/0a14154bff-a8cf65db07
-- Building F:/test7/vcpkg/buildtrees/winpcap/src/4_1_3-2020b05bdd/wpcap/PRJ/wpcap.sln for Release
-- Building F:/test7/vcpkg/buildtrees/winpcap/src/4_1_3-2020b05bdd/wpcap/PRJ/wpcap.sln for Debug
-- Installing: F:/test7/vcpkg/packages/winpcap_x86-windows/include/bittypes.h
-- Installing: F:/test7/vcpkg/packages/winpcap_x86-windows/include/ip6_misc.h
-- Installing: F:/test7/vcpkg/packages/winpcap_x86-windows/include/Packet32.h
-- Installing: F:/test7/vcpkg/packages/winpcap_x86-windows/include/pcap.h
-- Installing: F:/test7/vcpkg/packages/winpcap_x86-windows/include/pcap-bpf.h
-- Installing: F:/test7/vcpkg/packages/winpcap_x86-windows/include/pcap-namedb.h
-- Installing: F:/test7/vcpkg/packages/winpcap_x86-windows/include/pcap-stdinc.h
-- Installing: F:/test7/vcpkg/packages/winpcap_x86-windows/include/remote-ext.h
-- Installing: F:/test7/vcpkg/packages/winpcap_x86-windows/include/Win32-Extensions.h
-- Installing: F:/test7/vcpkg/packages/winpcap_x86-windows/include/pcap/bluetooth.h
-- Installing: F:/test7/vcpkg/packages/winpcap_x86-windows/include/pcap/bpf.h
-- Installing: F:/test7/vcpkg/packages/winpcap_x86-windows/include/pcap/namedb.h
-- Installing: F:/test7/vcpkg/packages/winpcap_x86-windows/include/pcap/pcap.h
-- Installing: F:/test7/vcpkg/packages/winpcap_x86-windows/include/pcap/sll.h
-- Installing: F:/test7/vcpkg/packages/winpcap_x86-windows/include/pcap/usb.h
-- Installing: F:/test7/vcpkg/packages/winpcap_x86-windows/include/pcap/vlan.h
-- Installing: F:/test7/vcpkg/packages/winpcap_x86-windows/lib/Packet.lib
-- Installing: F:/test7/vcpkg/packages/winpcap_x86-windows/lib/wpcap.lib
-- Installing: F:/test7/vcpkg/packages/winpcap_x86-windows/debug/lib/Packet.lib
-- Installing: F:/test7/vcpkg/packages/winpcap_x86-windows/debug/lib/wpcap.lib
-- Installing: F:/test7/vcpkg/packages/winpcap_x86-windows/bin/Packet.dll
-- Installing: F:/test7/vcpkg/packages/winpcap_x86-windows/bin/wpcap.dll
-- Installing: F:/test7/vcpkg/packages/winpcap_x86-windows/debug/bin/Packet.dll
-- Installing: F:/test7/vcpkg/packages/winpcap_x86-windows/debug/bin/wpcap.dll
-- Performing post-build validation
-- Performing post-build validation done
Installing package winpcap[core]:x86-windows...
Elapsed time for package winpcap:x86-windows: 1.619 min

Total elapsed time: 1.622 min
````

**Comment by NancyLi1013** [comment]
`Error code: The system cannot find the file specified`

@herrwusel 

The problem you encountered is not related with this update. It should be something with your local environment.

**Comment by herrwusel** [comment]
Sorry for the late reply. It is indeed working now and was my environment!

**Pull request merged**
