### PR TITLE
[eve] Fix export usage

### LINKED ISSUE #27989: [eve]  port can't use after installed.
**Describe the bug**
after ./vcpkg install eve
add this line  find_package(eve CONFIG REQUIRED) to CMakeLists.txt
and when configure , report can't find eve-config.cmake.

**Environment**
- OS: Linux
- Compiler: gcc 11.2

**To Reproduce**
1. ./vcpkg install eve
2. add  find_package(eve CONFIG REQUIRED) 
3. configure add see configure error
Repro code when

**Expected behavior**
Should can use find_package to find eve port.

**Failure logs**
-(please attached failure logs)
1> [CMake] CMake Error at /home/rob/vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package):
1> [CMake]   Could not find a package configuration file provided by "eve" with any of
1> [CMake]   the following names:
1> [CMake] 
1> [CMake]     eveConfig.cmake
1> [CMake]     eve-config.cmake
1> [CMake] 
1> [CMake]   Add the installation prefix of "eve" to CMAKE_PREFIX_PATH or set "eve_DIR"
1> [CMake]   to a directory containing one of the above files.  If "eve" provides a
1> [CMake]   separate development package or SDK, be sure it has been installed.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   clang_rename/CMakeLists.txt:8 (find_package)
**Additional context**

### PR DESCRIPTION
**Pull request by FrankXie05**
**Describe the pull request**

- #### What does your PR fix?
  Fixes https://github.com/microsoft/vcpkg/issues/27989
  Note: Export `eve` cmake configuration to the correct file location.
  The usage has been tested successfully.
  ```
  eve provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(eve CONFIG REQUIRED)
    target_link_libraries(main PRIVATE eve::eve)
  ```

### CODE REVIEW

**Review by MonicaLiu0311 — APPROVED** [review]

**Review by dg0yt — CHANGES_REQUESTED** [review]
This ain't right. Even if this port doesn't support MSVC, each build type must get the proper config. Normally this is handled by `vcpkg_cmake_config_fixup`.

Current list in CI, no `vcpkg_cmake_config_fixup`:
~~~
eve:x64-linux:/lib/eve-2022.3.0/eve-config.cmake
eve:x64-linux:/lib/eve-2022.3.0/eve-multiarch.cmake
eve:x64-linux:/lib/eve-2022.3.0/eve-targets.cmake
...
~~~

**Comment by FrankXie05** [comment]
`{MAIN_DEST}` should be placed in the `share/{PORT}` folder instead of the `{CMAKE_INSTALL_LIBDIR}` folder.
https://github.com/jfalcou/eve/blob/bf84c63a61279726c58d764414d8e17fa915f6ee/cmake/config/eve-install.cmake#L7

**Comment by dg0yt** [comment]
> `{MAIN_DEST}` should be placed in the `share/{PORT}` folder instead of the `{CMAKE_INSTALL_LIBDIR}` folder. https://github.com/jfalcou/eve/blob/bf84c63a61279726c58d764414d8e17fa915f6ee/cmake/config/eve-install.cmake#L7

Don't point me to the spot you are patching. 
Please look up why and how `vcpkg_cmake_config_fixup` is used.

**Comment by MonicaLiu0311** [comment]
Duplicate: https://github.com/microsoft/vcpkg/pull/28212

**Pull request closed without merging**
