### PR TITLE
[BlingFire] Adding BlingFire Package

### PR DESCRIPTION
**Pull request by TomasMorris**
- #### What does your PR fix?
Adds a [BlingFire](https://github.com/microsoft/BlingFire) port

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
Windows x64, Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
Yes

### CODE REVIEW

**Review by JonLiu1993 — CHANGES_REQUESTED** [review]

**Review by JonLiu1993 — DISMISSED** [review]

**Comment by JonLiu1993** [comment]
@TomasMorris, when I install this port on my local machine, I find no xxxconfig.cmake in package file but Upstream code have this code, could you please take a look?
image

````
INSTALL(
  TARGETS blingfiretokdll
  EXPORT blingfire-targets
  RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
  ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
  LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
  INCLUDES DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
````

**Comment by TomasMorris** [comment]
> @TomasMorris, when I install this port on my local machine, I find no xxxconfig.cmake in package file but Upstream code have this code, could you please take a look? image
> 
> ```
> INSTALL(
>   TARGETS blingfiretokdll
>   EXPORT blingfire-targets
>   RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
>   ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
>   LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
>   INCLUDES DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
> ```

codebase didn't include a cmake config, I have updated BlingFire to include that and updated the commit in this port to match.

**Comment by JonLiu1993** [comment]
@TomasMorris, when I tested the usage by a simple cmake project, I got this erro.
Please take a look:
CMakeLists:
````
cmake_minimum_required (VERSION 3.8)

project(test)

find_package(blingfire CONFIG REQUIRED)
add_executable (main "CMakeProject42.cpp" "CMakeProject42.h")

target_link_libraries(main PRIVATE blingfiretokdll)

````
CMakeProject42.cpp:
````
// CMakeProject42.cpp : Defines the entry point for the application.
//

#include "CMakeProject42.h"
#include "blingfiretokdll.h"

using namespace std;

int main()
{
	cout << "Hello CMake." << endl;
	return 0;
}

````
CMakeProject42.h:
````
// CMakeProject42.h : Include file for standard system include files,
// or project specific include files.

#pragma once

#include <iostream>

// TODO: Reference additional headers your program requires here.

````

````
CMake Error at F:/Feature-test/bling/vcpkg/installed/x64-windows/share/blingfire/blingfire-config.cmake:1:
1> [CMake]   Parse error.  Expected a command name, got unquoted argument with text
1> [CMake]   "@PACKAGE_INIT@".
1> [CMake] Call Stack (most recent call first):
1> [CMake]   F:/Feature-test/bling/vcpkg/scripts/buildsystems/vcpkg.cmake:843 (_find_package)
1> [CMake]   CMakeProject42/CMakeLists.txt:10 (find_package)
````

**Comment by JonLiu1993** [comment]
Pinging @TomasMorris for response.

**Comment by JonLiu1993** [comment]
Convert this PR to draft since there is no progress. Please ping us if this PR is ready for review again.

**Comment by JonLiu1993** [comment]
Closing this PR since it seems that no progress is being made. Please ping us to reopen if work is still being done.

**Comment by TomasMorris** [comment]
Sorry for the break, took some time off. @JonLiu1993, would you mind reopening this as it should be ready for review and all the issues above were fixed.

**Comment by JonLiu1993** [comment]
@TomasMorris, this PR cannot be reopened, thinking that the branch `TomasMorris:master` has been forced to push or no longer exists, could you please resubmit a PR?

**Pull request closed without merging**
