### PR TITLE
Fix double flags when building Qt modules

### LINKED ISSUE #28835: [qt5-declarative] Build error with arm64 on macOS crosscompiled on x64 since #26354
**Host Environment**

- OS: macOS

**To Reproduce**

`./vcpkg install qt5-declarative:arm64-osx`

Running on a x64 hardware

**Failure logs**

```
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:131 (message):
    Command failed: /usr/bin/make -j 4
    Working Directory: /Users/runner/mixxx-vcpkg/buildtrees/qt5-declarative/arm64-osx-min1100-dbg
    See logs for more information:
      /Users/runner/mixxx-vcpkg/buildtrees/qt5-declarative/package-build-arm64-osx-min1100-dbg-out.log
      /Users/runner/mixxx-vcpkg/buildtrees/qt5-declarative/package-build-arm64-osx-min1100-dbg-err.log
```

**Additional context**

This is the failing Run on GitHub: 
* https://github.com/daschuer/vcpkg/actions/runs/3868940153

Her it works again after reverting #26354: 
* https://github.com/daschuer/vcpkg/actions/runs/3873496046

The issue is that the build flags are applied twice. During the build of qt5-base the flags are collected in qtconf: 
` -qtconf /Users/runner/mixxx-vcpkg/buildtrees/qt5-declarative/arm64-osx-min1100-dbg/qt.conf`

But due to the change in [configure_qt.cmake](https://github.com/daschuer/vcpkg/commit/4faa481527835cfd4a9d58a60e01c087485c0a5d#diff-dd79c460f9353c301fcea2179a3bb152e45afddff029576ce0216aff5463ce7d) they are applied again in collision with the original Qt flags. Wen calling https://github.com/daschuer/vcpkg/blob/arm64-osx-min1100-qt5.15.7/ports/qt5-base/cmake/qt_build_submodule.cmake#L12

### PR DESCRIPTION
**Pull request by daschuer**
The CMake flags have been already collected during configuring Qt5 base and are stored in qmodule.pri (<installed>\tools\qt5\mkspecs). The additional flag retrieving is disabled in qt_build_submodule.cmake

This fixes a regression since #26354

- #### What does your PR fix?
  Fixes #28835

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  `No change`

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  `Yes`

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by daschuer** [comment]
Before https://github.com/microsoft/vcpkg/pull/26354:
```
	cl 
	-c -nologo -Zc:wchar_t -FS -Zc:rvalueCast -Zc:inline -Zc:strictStrings -Zc:throwingNew -Zc:referenceBinding -Zc:__cplusplus -O2 -MD 
	-std:c++17 -utf-8 /wd4530 /wd4577 -W3 -w34100 -w34189 -w44996 -w44456 -w44457 -w44458 -wd4577 -wd4467 -DUNICODE -D_UNICODE -DWIN32 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -DWIN64 -DQT_NO_LINKED_LIST -DQT_NO_LINKED_LIST -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_USE_QSTRINGBUILDER -DNDEBUG -DQT_NO_EXCEPTIONS -DQT_NO_DEBUG -DQT_QMLDEVTOOLS_LIB -DQT_CORE_LIB -IC:\mixxx-vcpkg\buildtrees\qt5-declarative\src\5.15.7-7f3698f29e.clean\tools\qmllint -I. -IC:\mixxx-vcpkg\buildtrees\qt5-declarative\src\5.15.7-7f3698f29e.clean\include -IC:\mixxx-vcpkg\buildtrees\qt5-declarative\src\5.15.7-7f3698f29e.clean\include\QtQml -IC:\mixxx-vcpkg\buildtrees\qt5-declarative\src\5.15.7-7f3698f29e.clean\include\QtQml\5.15.7 -IC:\mixxx-vcpkg\buildtrees\qt5-declarative\src\5.15.7-7f3698f29e.clean\include\QtQml\5.15.7\QtQml -I..\..\include -I..\..\include\QtQml -I..\..\include\QtQml\5.15.7 -I..\..\include\QtQml\5.15.7\QtQml -IC:\mixxx-vcpkg\installed\x64-windows\include\qt5\QtCore\5.15.7 -IC:\mixxx-vcpkg\installed\x64-windows\include\qt5\QtCore\5.15.7\QtCore -IC:\mixxx-vcpkg\installed\x64-windows\include\qt5 -IC:\mixxx-vcpkg\installed\x64-windows\include\qt5\QtCore -I.moc\release -IC:\mixxx-vcpkg\installed\x64-windows\include -IC:\mixxx-vcpkg\installed\x64-windows\include\qt5 -IC:\mixxx-vcpkg\installed\x64-windows\tools\qt5\mkspecs\win32-msvc -Fo.obj\release\ @C:\Users\RUNNER~1\AppData\Local\Temp\main.obj.6780.15.jom
main.cpp
```

After https://github.com/microsoft/vcpkg/pull/26354:
```
	cl.exe 
	-c -nologo -Zc:wchar_t -FS -Zc:rvalueCast -Zc:inline -Zc:strictStrings -Zc:throwingNew -Zc:referenceBinding -Zc:__cplusplus -O2 -MD 
	-nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -GR -EHsc -MP -MD -O2 -Oi -Gy -DNDEBUG -Z7 
	-nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -GR -EHsc -MP -MD -O2 -Oi -Gy -DNDEBUG -Z7 
	-std:c++17 -utf-8 /wd4530 /wd4577 -W3 -w34100 -w34189 -w44996 -w44456 -w44457 -w44458 -wd4577 -wd4467 -DUNICODE -D_UNICODE -DWIN32 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -DWIN64 -DQT_NO_LINKED_LIST -DQT_NO_LINKED_LIST -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_USE_QSTRINGBUILDER -DNDEBUG -DQT_NO_EXCEPTIONS -DQT_NO_DEBUG -DQT_QMLDEVTOOLS_LIB -DQT_CORE_LIB -IC:\mixxx-vcpkg\buildtrees\qt5-declarative\src\5.15.7-7f3698f29e.clean\tools\qmllint -I. -IC:\mixxx-vcpkg\buildtrees\qt5-declarative\src\5.15.7-7f3698f29e.clean\include -IC:\mixxx-vcpkg\buildtrees\qt5-declarative\src\5.15.7-7f3698f29e.clean\include\QtQml -IC:\mixxx-vcpkg\buildtrees\qt5-declarative\src\5.15.7-7f3698f29e.clean\include\QtQml\5.15.7 -IC:\mixxx-vcpkg\buildtrees\qt5-declarative\src\5.15.7-7f3698f29e.clean\include\QtQml\5.15.7\QtQml -I..\..\include -I..\..\include\QtQml -I..\..\include\QtQml\5.15.7 -I..\..\include\QtQml\5.15.7\QtQml -IC:\mixxx-vcpkg\installed\x64-windows\include\qt5\QtCore\5.15.7 -IC:\mixxx-vcpkg\installed\x64-windows\include\qt5\QtCore\5.15.7\QtCore -IC:\mixxx-vcpkg\installed\x64-windows\include\qt5 -IC:\mixxx-vcpkg\installed\x64-windows\include\qt5\QtCore -I.moc\release -IC:\mixxx-vcpkg\installed\x64-windows\include -IC:\mixxx-vcpkg\installed\x64-windows\include\qt5 -IC:\mixxx-vcpkg\installed\x64-windows\tools\qt5\mkspecs\win32-msvc -Fo.obj\release\ @C:\Users\RUNNER~1\AppData\Local\Temp\main.obj.2604.16.jom
main.cpp
```

With the proposed patch applied:
```
	cl.exe 
	-c -nologo -Zc:wchar_t -FS -Zc:rvalueCast -Zc:inline -Zc:strictStrings -Zc:throwingNew -Zc:referenceBinding -Zc:__cplusplus -O2 -MD 
	-nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -GR -EHsc -MP -MD -O2 -Oi -Gy -DNDEBUG -Z7 
	-std:c++17 -utf-8 /wd4530 /wd4577 -W3 -w34100 -w34189 -w44996 -w44456 -w44457 -w44458 -wd4577 -wd4467 -DUNICODE -D_UNICODE -DWIN32 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -DWIN64 -DQT_NO_LINKED_LIST -DQT_NO_LINKED_LIST -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_USE_QSTRINGBUILDER -DNDEBUG -DQT_NO_EXCEPTIONS -DQT_NO_DEBUG -DQT_QMLDEVTOOLS_LIB -DQT_CORE_LIB -IC:\mixxx-vcpkg\buildtrees\qt5-declarative\src\5.15.7-7f3698f29e.clean\tools\qmllint -I. -IC:\mixxx-vcpkg\buildtrees\qt5-declarative\src\5.15.7-7f3698f29e.clean\include -IC:\mixxx-vcpkg\buildtrees\qt5-declarative\src\5.15.7-7f3698f29e.clean\include\QtQml -IC:\mixxx-vcpkg\buildtrees\qt5-declarative\src\5.15.7-7f3698f29e.clean\include\QtQml\5.15.7 -IC:\mixxx-vcpkg\buildtrees\qt5-declarative\src\5.15.7-7f3698f29e.clean\include\QtQml\5.15.7\QtQml -I..\..\include -I..\..\include\QtQml -I..\..\include\QtQml\5.15.7 -I..\..\include\QtQml\5.15.7\QtQml -IC:\mixxx-vcpkg\installed\x64-windows\include\qt5\QtCore\5.15.7 -IC:\mixxx-vcpkg\installed\x64-windows\include\qt5\QtCore\5.15.7\QtCore -IC:\mixxx-vcpkg\installed\x64-windows\include\qt5 -IC:\mixxx-vcpkg\installed\x64-windows\include\qt5\QtCore -I.moc\release -IC:\mixxx-vcpkg\installed\x64-windows\include -IC:\mixxx-vcpkg\installed\x64-windows\include\qt5 -IC:\mixxx-vcpkg\installed\x64-windows\tools\qt5\mkspecs\win32-msvc -Fo.obj\release\ @C:\Users\RUNNER~1\AppData\Local\Temp\main.obj.6856.16.jom
main.cpp
```

**Comment by Neumann-A** [comment]
> The CMake flags have been already collected during configuring Qt5 base and are stored in qmodule.pri (\tools\qt5\mkspecs).

The correct approach is to remove the flags from `qmodule.pri`

**Comment by daschuer** [comment]
> The correct approach is to remove the flags from qmodule.pri

qmodule.pri contains not only flags passed from CMake. I don't have a good overview about all the implications with this file. It is likely that some corner cases are broken with such a solution. 
At least it will not solve issue https://github.com/microsoft/vcpkg/issues/28835 Such a solution will work even more against the original Qt build system. At least will be a fundamental change, require some good testing. 

Instead this PR only reverts the changes from https://github.com/microsoft/vcpkg/pull/26354 for qt submodules back to an established state. 
A low impact solution that might be considered as a band aid, until a correct solution is mature.

**Comment by Neumann-A** [comment]
> At least it will not solve issue https://github.com/microsoft/vcpkg/issues/28835

The whole qt5 tree is not properly setup to support cross compilation. I played around with it a bit and can tell you that the setup to do this is to correctly tell qmake what is going on by providing appropriate cross flags and mkspecs. However one major problem I discovered was that the qt build scripts `ALWAYS` try to build host tools in this configuration and consume their internal dependencies. As such vcpkg needs to setup qt5 in a way that it will pretend to do a native build while however using in reality tools from the host triplet. As such removing the flags from `qmodule.pri` is a hard requirement to properly setup cross builds of qt5 in vcpkg any way. (in addition of adding the required host dependencies).

Providing a band aid is not a solution for the main registry of vcpkg. If you need it keep it in your private registry/port overlay.

**Comment by daschuer** [comment]
> Providing a band aid is not a solution for the main registry of vcpkg

I think it is a good practice in software development to revert a commit that breaks something and than develop a better solution while not suffering the broken bits in the meantime. This PR does that, for the qt submodules only. 

What could be the downside of this PR for the main registry?

**Comment by BillyONeal** [comment]
@Neumann-A Notwithstanding what the correct change is, is this change better than the status quo?

**Comment by Neumann-A** [comment]
>  is this change better than the status quo?

From my point of view no. It doesn't follow vcpkg's model of host/target triplet and allows host binaries to be mixed with target libraries within the same triplet. Furthermore instead of port `qt5-*` being build with the flags of port `qt5-*` it will use the flags of `qt5-base`. As such I don't see this as a good step forward but rather a step backwards. So the current state is:
- disallow mixing of host/target libraries by a collision of -arch compiler flags.
- applying `qt5-*` flags after flags from `qt5-base` overruling flags from `qt5-base` if possible and not conflicting. 

@BillyONeal: But decide for yourself considering the above.

**Comment by daschuer** [comment]
> It doesn't follow vcpkg's model of host/target triplet and allows host binaries to be mixed with target libraries within the same triplet.

This was a topic in the issue report, but is not relevant here. A pending issue in any case. 

> Furthermore instead of port qt5-* being build with the flags of port qt5-* it will use the flags of qt5-base

* Before https://github.com/microsoft/vcpkg/pull/26354: Qt Submodules are build with the common flags calculated in the `qt5-base` derived from CMake 
* Situation in Main: Submodule are build with the calculated flags form `qt5-base` and potential concurrent original flags taken again form CMake.
* This PR reverts to the known good situation from before.

**Comment by Neumann-A** [comment]
> This PR reverts to the known good situation from before.

Since you are deliberately not considering the cross build case here. The current situation is also known to be good -> see CI. So there is no need to "revert" the situation.

**Review by FrankXie05 — APPROVED** [review]

**Comment by JavierMatosD** [comment]
Hi @daschuer, instead of reverting @Neumann-A's pull request, I'd like to address the issue they mentioned and remove the flags from `qmodule.pri`. I agree that double flags shouldn't be present, and I believe `qt5-* `ports should build with `qt5-*` flags.

However, if fixing the issue requires more work than simply removing the flags from `qmodule.pri`, we can consider reverting https://github.com/microsoft/vcpkg/pull/26354 for now. This will give us time to find a more robust solution.

For now, I'll set this pull request as a draft. If you'd like to attempt the suggested fix, please feel free to update the pull request and mark it as "ready for review." If not, I'll try it out on my end and update the pull request accordingly.

Thank you, and I look forward to your input. :)

**Comment by daschuer** [comment]
The alternative solution from @JavierMatosD is here: https://github.com/microsoft/vcpkg/pull/31634

**Comment by vicroms** [comment]
Fixed by #31634 

Please feel free to re-open if the issue is not fixed

**Pull request closed without merging**
