### PR TITLE
[saucer] build against Qt6

### PR DESCRIPTION
**Pull request by MehdiChinoune**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] SHA512s are updated for each updated download
- [ ] The "supports" clause reflects platforms that may be fixed by this new version
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [ ] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [ ] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Review by MonicaLiu0311 — APPROVED** [review]

**Comment by Curve** [comment]
As the library maintainer I strongly discourage forcing the backend to Qt6.

Please consider making this optional / user selectable instead.

**Comment by dg0yt** [comment]
ATM vcpkg has no interface for choosing alternatives, unfortunately.

**Comment by Curve** [comment]
> ATM vcpkg has no interface for choosing alternatives, unfortunately.

Wasn't there an option to install different feature sets?

I vaguely remember being able to install packages like this:

```
vcpkg install saucer[qt5]
```

**Comment by dg0yt** [comment]
Features must be additive. Alternatives aren't.

**Pull request merged**
