### PR TITLE
[ned14-internal-quickcpplib,status-code,llfio] Update 2023.01

### PR DESCRIPTION
**Pull request by BurningEnlightenment**
These three ports are tightly coupled and therefore it makes sense to update them with a single PR.

**Port Update Checklist**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file. (currently installed GCC version still doesn't provide `<span>` as tested with [this commit pipeline](https://github.com/microsoft/vcpkg/runs/10927143440))
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by BurningEnlightenment** [comment]
Note that `vcpkg clean` caused the CI failure, 239bd626b015e86cd835f6bd19dd4621c4481a87 passed CI before I unsucessfully tried to remove the ci.baseline fail entry but had to revert back to 239bd626b015e86cd835f6bd19dd4621c4481a87.

**Review by JonLiu1993 — APPROVED** [review]

**Comment by JonLiu1993** [comment]
Tested all features successfully in the following triplet:
- x86-windows
- x64-windows
- x64-windows-static

**Comment by BillyONeal** [comment]
Thanks for the update!

**Pull request merged**
