### PR TITLE
Switch CI image to Android NDK r27c

### PR DESCRIPTION
**Pull request by dg0yt**
r27c seems mature enough to be used in vcpkg CI.
Similar to the r26 transition:
1. Add r27c to the image. This PR, plus @BillyONeal doing the actual rollout.
2. Switch https://github.com/microsoft/vcpkg/pull/40339 to use the new NDK from the image, fix and merge.
3. Remove r26c from the image. Future PR.

### CODE REVIEW

**Comment by BillyONeal** [comment]
Do they need to be installed concurrently or can I just give you one with only r27c you can merge in https://github.com/microsoft/vcpkg/pull/40339 ?

**Comment by dg0yt** [comment]
They are not needed concurrently.

**Review by FrankXie05 — DISMISSED** [review]

**Review by BillyONeal — COMMENTED** [review]
Also needs edit to

scripts/azure-pipelines/android/azure-pipelines.yml

**Comment by BillyONeal** [comment]
https://github.com/dg0yt/vcpkg/pull/25

**Comment by dg0yt** [comment]
Rolled back to stop redundant CI. Actual integration now in #40339.

**Comment by dg0yt** [comment]
All checks green in #40339.

**Pull request closed without merging**
