### PR TITLE
linux toolchain: add missing CMAKE_ASM_FLAGS_INIT.

### LINKED ISSUE #39144: [boost-context] build failure on x86-linux after PR #32309
### Operating system

Linux

### Compiler

gcc 11.4.0 / clang 11.0.0

### Steps to reproduce the behavior

```Shell
`./vcpkg install boost-context:x86-linux`
```

### Failure logs

gcc build log:

```
Run Build Command(s): /home/lawliet/Development/vcpkg/downloads/tools/ninja/1.10.2-linux/ninja -v -v -j21 install
[1/6] /usr/bin/c++ -DBOOST_CONTEXT_EXPORT="" -DBOOST_CONTEXT_NO_LIB="" -DBOOST_CONTEXT_SOURCE="" -DBOOST_CONTEXT_STATIC_LINK="" -I/home/lawliet/Development/vcpkg/buildtrees/boost-context/src/ost-1.84.0-090380ddb3.clean/libs/context/include -isystem /home/lawliet/Development/vcpkg/installed/x86-linux/include -g -x assembler-with-cpp -MD -MT libs/context/CMakeFiles/boost_context.dir/src/asm/make_i386_sysv_elf_gas.S.o -MF libs/context/CMakeFiles/boost_context.dir/src/asm/make_i386_sysv_elf_gas.S.o.d -o libs/context/CMakeFiles/boost_context.dir/src/asm/make_i386_sysv_elf_gas.S.o -c /home/lawliet/Development/vcpkg/buildtrees/boost-context/src/ost-1.84.0-090380ddb3.clean/libs/context/src/asm/make_i386_sysv_elf_gas.S
FAILED: libs/context/CMakeFiles/boost_context.dir/src/asm/make_i386_sysv_elf_gas.S.o
/usr/bin/c++ -DBOOST_CONTEXT_EXPORT="" -DBOOST_CONTEXT_NO_LIB="" -DBOOST_CONTEXT_SOURCE="" -DBOOST_CONTEXT_STATIC_LINK="" -I/home/lawliet/Development/vcpkg/buildtrees/boost-context/src/ost-1.84.0-090380ddb3.clean/libs/context/include -isystem /home/lawliet/Development/vcpkg/installed/x86-linux/include -g -x assembler-with-cpp -MD -MT libs/context/CMakeFiles/boost_context.dir/src/asm/make_i386_sysv_elf_gas.S.o -MF libs/context/CMakeFiles/boost_context.dir/src/asm/make_i386_sysv_elf_gas.S.o.d -o libs/context/CMakeFiles/boost_context.dir/src/asm/make_i386_sysv_elf_gas.S.o -c /home/lawliet/Development/vcpkg/buildtrees/boost-context/src/ost-1.84.0-090380ddb3.clean/libs/context/src/asm/make_i386_sysv_elf_gas.S
/home/lawliet/Development/vcpkg/buildtrees/boost-context/src/ost-1.84.0-090380ddb3.clean/libs/context/src/asm/make_i386_sysv_elf_gas.S: Assembler messages:
/home/lawliet/Development/vcpkg/buildtrees/boost-context/src/ost-1.84.0-090380ddb3.clean/libs/context/src/asm/make_i386_sysv_elf_gas.S:70: Error: invalid instruction suffix for `pop'
/home/lawliet/Development/vcpkg/buildtrees/boost-context/src/ost-1.84.0-090380ddb3.clean/libs/context/src/asm/make_i386_sysv_elf_gas.S:80: Error: invalid instruction suffix for `pop'
/home/lawliet/Development/vcpkg/buildtrees/boost-context/src/ost-1.84.0-090380ddb3.clean/libs/context/src/asm/make_i386_sysv_elf_gas.S:93: Error: invalid instruction suffix for `push'
/home/lawliet/Development/vcpkg/buildtrees/boost-context/src/ost-1.84.0-090380ddb3.clean/libs/context/src/asm/make_i386_sysv_elf_gas.S:95: Error: unsupported syntax for `jmp'
/home/lawliet/Development/vcpkg/buildtrees/boost-context/src/ost-1.84.0-090380ddb3.clean/libs/context/src/asm/make_i386_sysv_elf_gas.S:100: Error: invalid instruction suffix for `pop'
[2/6] /usr/bin/c++ -DBOOST_CONTEXT_EXPORT="" -DBOOST_CONTEXT_NO_LIB="" -DBOOST_CONTEXT_SOURCE="" -DBOOST_CONTEXT_STATIC_LINK="" -I/home/lawliet/Development/vcpkg/buildtrees/boost-context/src/ost-1.84.0-090380ddb3.clean/libs/context/include -isystem /home/lawliet/Development/vcpkg/installed/x86-linux/include -g -x assembler-with-cpp -MD -MT libs/context/CMakeFiles/boost_context.dir/src/asm/jump_i386_sysv_elf_gas.S.o -MF libs/context/CMakeFiles/boost_context.dir/src/asm/jump_i386_sysv_elf_gas.S.o.d -o libs/context/CMakeFiles/boost_context.dir/src/asm/jump_i386_sysv_elf_gas.S.o -c /home/lawliet/Development/vcpkg/buildtrees/boost-context/src/ost-1.84.0-090380ddb3.clean/libs/context/src/asm/jump_i386_sysv_elf_gas.S
FAILED: libs/context/CMakeFiles/boost_context.dir/src/asm/jump_i386_sysv_elf_gas.S.o
/usr/bin/c++ -DBOOST_CONTEXT_EXPORT="" -DBOOST_CONTEXT_NO_LIB="" -DBOOST_CONTEXT_SOURCE="" -DBOOST_CONTEXT_STATIC_LINK="" -I/home/lawliet/Development/vcpkg/buildtrees/boost-context/src/ost-1.84.0-090380ddb3.clean/libs/context/include -isystem /home/lawliet/Development/vcpkg/installed/x86-linux/include -g -x assembler-with-cpp -MD -MT libs/context/CMakeFiles/boost_context.dir/src/asm/jump_i386_sysv_elf_gas.S.o -MF libs/context/CMakeFiles/boost_context.dir/src/asm/jump_i386_sysv_elf_gas.S.o.d -o libs/context/CMakeFiles/boost_context.dir/src/asm/jump_i386_sysv_elf_gas.S.o -c /home/lawliet/Development/vcpkg/buildtrees/boost-context/src/ost-1.84.0-090380ddb3.clean/libs/context/src/asm/jump_i386_sysv_elf_gas.S
jump_i386_sysv_elf_gas.S: Assembler messages:
jump_i386_sysv_elf_gas.S:89: Error: unsupported syntax for `jmp'
[3/6] /usr/bin/c++ -DBOOST_CONTEXT_EXPORT="" -DBOOST_CONTEXT_NO_LIB="" -DBOOST_CONTEXT_SOURCE="" -DBOOST_CONTEXT_STATIC_LINK="" -I/home/lawliet/Development/vcpkg/buildtrees/boost-context/src/ost-1.84.0-090380ddb3.clean/libs/context/include -isystem /home/lawliet/Development/vcpkg/installed/x86-linux/include -g -x assembler-with-cpp -MD -MT libs/context/CMakeFiles/boost_context.dir/src/asm/ontop_i386_sysv_elf_gas.S.o -MF libs/context/CMakeFiles/boost_context.dir/src/asm/ontop_i386_sysv_elf_gas.S.o.d -o libs/context/CMakeFiles/boost_context.dir/src/asm/ontop_i386_sysv_elf_gas.S.o -c /home/lawliet/Development/vcpkg/buildtrees/boost-context/src/ost-1.84.0-090380ddb3.clean/libs/context/src/asm/ontop_i386_sysv_elf_gas.S
FAILED: libs/context/CMakeFiles/boost_context.dir/src/asm/ontop_i386_sysv_elf_gas.S.o
/usr/bin/c++ -DBOOST_CONTEXT_EXPORT="" -DBOOST_CONTEXT_NO_LIB="" -DBOOST_CONTEXT_SOURCE="" -DBOOST_CONTEXT_STATIC_LINK="" -I/home/lawliet/Development/vcpkg/buildtrees/boost-context/src/ost-1.84.0-090380ddb3.clean/libs/context/include -isystem /home/lawliet/Development/vcpkg/installed/x86-linux/include -g -x assembler-with-cpp -MD -MT libs/context/CMakeFiles/boost_context.dir/src/asm/ontop_i386_sysv_elf_gas.S.o -MF libs/context/CMakeFiles/boost_context.dir/src/asm/ontop_i386_sysv_elf_gas.S.o.d -o libs/context/CMakeFiles/boost_context.dir/src/asm/ontop_i386_sysv_elf_gas.S.o -c /home/lawliet/Development/vcpkg/buildtrees/boost-context/src/ost-1.84.0-090380ddb3.clean/libs/context/src/asm/ontop_i386_sysv_elf_gas.S
ontop_i386_sysv_elf_gas.S: Assembler messages:
ontop_i386_sysv_elf_gas.S:96: Error: unsupported syntax for `jmp'
[4/6] /usr/bin/c++ -DBOOST_CONTEXT_EXPORT="" -DBOOST_CONTEXT_NO_LIB="" -DBOOST_CONTEXT_SOURCE="" -DBOOST_CONTEXT_STATIC_LINK="" -I/home/lawliet/Development/vcpkg/buildtrees/boost-context/src/ost-1.84.0-090380ddb3.clean/libs/context/include -isystem /home/lawliet/Development/vcpkg/installed/x86-linux/include -fPIC  -m32 -g -fvisibility=hidden -fvisibility-inlines-hidden -MD -MT libs/context/CMakeFiles/boost_context.dir/src/posix/stack_traits.cpp.o -MF libs/context/CMakeFiles/boost_context.dir/src/posix/stack_traits.cpp.o.d -o libs/context/CMakeFiles/boost_context.dir/src/posix/stack_traits.cpp.o -c /home/lawliet/Development/vcpkg/buildtrees/boost-context/src/ost-1.84.0-090380ddb3.clean/libs/context/src/posix/stack_traits.cpp
ninja: build stopped: subcommand failed.
```

Build from the different location with clang-11 (more descriptive error message):

```
[1/6] /usr/bin/clang++-11 -DBOOST_CONTEXT_EXPORT="" -DBOOST_CONTEXT_NO_LIB="" -DBOOST_CONTEXT_SOURCE="" -DBOOST_CONTEXT_STATIC_LINK="" -I/home/lawliet/Development/boinc-autodock-vina/vcpkg/buildtrees/boost-context/src/ost-1.85.0-aafc13249c.clean/libs/context/include -isystem /home/lawliet/Development/boinc-autodock-vina/build/boinc-autodock-vina/x86-linux-static/vcpkg_installed/x86-linux-static/include -g -MD -MT libs/context/CMakeFiles/boost_context.dir/src/asm/jump_i386_sysv_elf_gas.S.o -MF libs/context/CMakeFiles/boost_context.dir/src/asm/jump_i386_sysv_elf_gas.S.o.d -o libs/context/CMakeFiles/boost_context.dir/src/asm/jump_i386_sysv_elf_gas.S.o -c /home/lawliet/Development/boinc-autodock-vina/vcpkg/buildtrees/boost-context/src/ost-1.85.0-aafc13249c.clean/libs/context/src/asm/jump_i386_sysv_elf_gas.S
[2/6] /usr/bin/clang++-11 -DBOOST_CONTEXT_EXPORT="" -DBOOST_CONTEXT_NO_LIB="" -DBOOST_CONTEXT_SOURCE="" -DBOOST_CONTEXT_STATIC_LINK="" -I/home/lawliet/Development/boinc-autodock-vina/vcpkg/buildtrees/boost-context/src/ost-1.85.0-aafc13249c.clean/libs/context/include -isystem /home/lawliet/Development/boinc-autodock-vina/build/boinc-autodock-vina/x86-linux-static/vcpkg_installed/x86-linux-static/include -g -MD -MT libs/context/CMakeFiles/boost_context.dir/src/asm/ontop_i386_sysv_elf_gas.S.o -MF libs/context/CMakeFiles/boost_context.dir/src/asm/ontop_i386_sysv_elf_gas.S.o.d -o libs/context/CMakeFiles/boost_context.dir/src/asm/ontop_i386_sysv_elf_gas.S.o -c /home/lawliet/Development/boinc-autodock-vina/vcpkg/buildtrees/boost-context/src/ost-1.85.0-aafc13249c.clean/libs/context/src/asm/ontop_i386_sysv_elf_gas.S
FAILED: libs/context/CMakeFiles/boost_context.dir/src/asm/ontop_i386_sysv_elf_gas.S.o 
/usr/bin/clang++-11 -DBOOST_CONTEXT_EXPORT="" -DBOOST_CONTEXT_NO_LIB="" -DBOOST_CONTEXT_SOURCE="" -DBOOST_CONTEXT_STATIC_LINK="" -I/home/lawliet/Development/boinc-autodock-vina/vcpkg/buildtrees/boost-context/src/ost-1.85.0-aafc13249c.clean/libs/context/include -isystem /home/lawliet/Development/boinc-autodock-vina/build/boinc-autodock-vina/x86-linux-static/vcpkg_installed/x86-linux-static/include -g -MD -MT libs/context/CMakeFiles/boost_context.dir/src/asm/ontop_i386_sysv_elf_gas.S.o -MF libs/context/CMakeFiles/boost_context.dir/src/asm/ontop_i386_sysv_elf_gas.S.o.d -o libs/context/CMakeFiles/boost_context.dir/src/asm/ontop_i386_sysv_elf_gas.S.o -c /home/lawliet/Development/boinc-autodock-vina/vcpkg/buildtrees/boost-context/src/ost-1.85.0-aafc13249c.clean/libs/context/src/asm/ontop_i386_sysv_elf_gas.S
/home/lawliet/Development/boinc-autodock-vina/vcpkg/buildtrees/boost-context/src/ost-1.85.0-aafc13249c.clean/libs/context/src/asm/ontop_i386_sysv_elf_gas.S:96:5: error: instruction requires: Not 64-bit mode
    jmp *%ecx
    ^
[3/6] /usr/bin/clang++-11 -DBOOST_CONTEXT_EXPORT="" -DBOOST_CONTEXT_NO_LIB="" -DBOOST_CONTEXT_SOURCE="" -DBOOST_CONTEXT_STATIC_LINK="" -I/home/lawliet/Development/boinc-autodock-vina/vcpkg/buildtrees/boost-context/src/ost-1.85.0-aafc13249c.clean/libs/context/include -isystem /home/lawliet/Development/boinc-autodock-vina/build/boinc-autodock-vina/x86-linux-static/vcpkg_installed/x86-linux-static/include -g -MD -MT libs/context/CMakeFiles/boost_context.dir/src/asm/make_i386_sysv_elf_gas.S.o -MF libs/context/CMakeFiles/boost_context.dir/src/asm/make_i386_sysv_elf_gas.S.o.d -o libs/context/CMakeFiles/boost_context.dir/src/asm/make_i386_sysv_elf_gas.S.o -c /home/lawliet/Development/boinc-autodock-vina/vcpkg/buildtrees/boost-context/src/ost-1.85.0-aafc13249c.clean/libs/context/src/asm/make_i386_sysv_elf_gas.S
[4/6] /usr/bin/clang++-11  -m32 -DBOOST_CONTEXT_EXPORT="" -DBOOST_CONTEXT_NO_LIB="" -DBOOST_CONTEXT_SOURCE="" -DBOOST_CONTEXT_STATIC_LINK="" -I/home/lawliet/Development/boinc-autodock-vina/vcpkg/buildtrees/boost-context/src/ost-1.85.0-aafc13249c.clean/libs/context/include -isystem /home/lawliet/Development/boinc-autodock-vina/build/boinc-autodock-vina/x86-linux-static/vcpkg_installed/x86-linux-static/include -m32  -fPIC  -m32 -g -fvisibility=hidden -fvisibility-inlines-hidden -MD -MT libs/context/CMakeFiles/boost_context.dir/src/posix/stack_traits.cpp.o -MF libs/context/CMakeFiles/boost_context.dir/src/posix/stack_traits.cpp.o.d -o libs/context/CMakeFiles/boost_context.dir/src/posix/stack_traits.cpp.o -c /home/lawliet/Development/boinc-autodock-vina/vcpkg/buildtrees/boost-context/src/ost-1.85.0-aafc13249c.clean/libs/context/src/posix/stack_traits.cpp
ninja: build stopped: subcommand failed.
```

### Additional context

This was building fine before PR #32309

@Neumann-A, @Cheney-W

### PR DESCRIPTION
**Pull request by AenBleidd**
This fixes: #39144.

### CODE REVIEW

**Comment by Osyotr** [comment]
Might as well add `-g` for release builds (see #39127)

**Comment by dg0yt** [comment]
> Might as well add `-g` for release builds (see #39127)

I'm not convinced that there is agreement on this proposal.
Apart from the developers' local effect, I would be afraid of a negative impact on CI. Large artifacts are not cached, the release config builds a significant number of executables, and the non-windows CI triplets use static library linkage.

(Bonus question: Does vcpkg reliably control `strip` in release triplets?)

**Comment by dg0yt** [comment]
IIUC CMake deals with different "dialects" of ASM, 
https://cmake.org/cmake/help/latest/envvar/ASM_DIALECTFLAGS.html

And I still think that `-fPIC` doesn't belong to ASM.

**Comment by AenBleidd** [comment]
@Osyotr,
> Might as well add `-g` for release builds (see https://github.com/microsoft/vcpkg/issues/39127)

Definitely not: the purpose of this PR is to fix the build issue on `boost-context` on x86-linux.
Any other changes should be reviewed and discussed separately.

@dg0yt,

> And I still think that `-fPIC` doesn't belong to ASM.

I don't know for sure since I don't have enough experience with assembler, but if you think so - I can make this change. Locally I have tested that `boost-context` can be built successfully without `-fPIC` flag. If it really doesn't belong to ASM - then it will be just ignored by the compiler/linker, so from the4 other hand it's safe to keep it as-is as well.

I make this PR ready for review, and wait for further comments and/or suggestions.

**Comment by BillyONeal** [comment]
Can you respond to what dg0yt said here? https://github.com/microsoft/vcpkg/issues/39144#issuecomment-2149794205

His statement matches my understanding.

**Comment by AenBleidd** [comment]
@BillyONeal, I though I have replied to this already one comment before but anyway: I have made a little bit deeper research, and looks like you both are right, this option makes no sense with the ASM compiler itself, thus removed.

**Review by BillyONeal — COMMENTED** [review]
@vicroms 
@ras0219-msft 
@JavierMatosD 
and I discussed today.

We think this seems correct. @BillyONeal to double check that CMake's defaults do something like this.

**Review by LilyWangLL — APPROVED** [review]

**Comment by BillyONeal** [comment]
> @BillyONeal to double check that CMake's defaults do something like this.

Yeah that checks out:

CMake test

**Comment by BillyONeal** [comment]
Thanks!

**Pull request merged**
