### PR TITLE
[libusb] Bump to 1.0.26.11791

### PR DESCRIPTION
**Pull request by xiaozhuai**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

1. Bump to 1.0.26.11791
2. Modernization

### CODE REVIEW

**Comment by JoergAtGithub** [comment]
The version with hash `4239bc3a50014b8e6a5a2a59df1fff3b7469543b` is still the latest release of libusb, see: https://github.com/libusb/libusb/releases
The version with the hash `fcf0c710ef5911ae37fbbf1b39d48a89f6f14e8a` is the last commit to the master branch of the libusb project.

**Comment by xiaozhuai** [comment]
@JonLiu1993 @FrankXie05 Hi there, the CI fails on `dbow2:x64_linux` and `openimageio:x64_linux`. It doesn't seem to have anything to do with this PR. Can these be safely ignored?

**Comment by FrankXie05** [comment]
It's a CI baseline, don't worry, we're fixing it.  But we cannot ignore it to merge this PR. Sorry :)

**Comment by xiaozhuai** [comment]
> The version with hash `4239bc3a50014b8e6a5a2a59df1fff3b7469543b` is still the latest release of libusb, see: https://github.com/libusb/libusb/releases The version with the hash `fcf0c710ef5911ae37fbbf1b39d48a89f6f14e8a` is the last commit to the master branch of the libusb project.

@JoergAtGithub You are right. That is why I add a nanoversion `11791` (Full compliance with upstream regulations). 
It has been year after last release, and there are many fix and improvements, and the build config for windows has changed too. 
Since it is not clear when the new version will be released upstream, it makes sense to use the latest code of the master branch.

**Comment by xiaozhuai** [comment]
@JonLiu1993 @FrankXie05 Please review...

**Review by FrankXie05 — APPROVED** [review]

**Review by MonicaLiu0311 — APPROVED** [review]

**Pull request merged**
