### PR TITLE
set triplet by windows architecture

### LINKED ISSUE #1254: Install x64 packages as default instead of x86
I believe nowadays most computers are 64 bit. Is it possible to install x64 libraries by default?

For example:
``````
vcpkg.exe install gflags 
``````

This now install gflags_x86-windows, can we change it so it install gflags_x64-windows?

### PR DESCRIPTION
**Pull request by psionic12**
automatically set environment variable "VCPKG_DEFAULT_TRIPLET" by architecture.

The bootstrap does not set this environment variable by default, make a user either add it manually or use a wrong version of libraries by mistake.

fixed #1254

### CODE REVIEW

**Comment by psionic12** [comment]
I'm not very familiar with Windows programming, any way I can know if my device is x64_uwp/arm64_windows?

**Comment by Voskrese** [comment]
https://github.com/microsoft/vcpkg/issues/11395

**Comment by timautry** [comment]
- What does the change do if VCPKG_DEFAULT_TRIPLET is already set?
- How does it determine which triplet - i.e. x64-windows, x64-windows-static or x64-uwp to set?

**Comment by psionic12** [comment]
@timautry the second question is actually what I don't know how to deal with, any suggestions?

**Comment by timautry** [comment]
What about the first question?
Both are equally important...
I not expert, but the  code changes does not seem to check if it is already set, it seems to just get the system architecture and set it accordingly. 
What about those that set the variables to something else to cross compile for other platforms?

**Comment by timautry** [comment]
Unless there is something I am missing, I would suggest making it the x64-windows triplet - it is dynamic crt and link. 
Others may want to weight in with an option with better reasoning. 
Also, I think the x86-windows is dynamic crt and link.

**Comment by psionic12** [comment]
@timautry, sorry for late, done.

**Comment by psionic12** [comment]
Sorry I merged some patches by mistake, I'll close this and upload another one

**Comment by psionic12** [comment]
New pull request at https://github.com/microsoft/vcpkg/pull/11610.

**Pull request closed without merging**
