### PR TITLE
[vcpkg-find-acquire-program] Add mirror to nasm.

### PR DESCRIPTION
**Pull request by teo-tsirpanis**
See https://github.com/microsoft/vcpkg/issues/2777#issuecomment-1639755074.

### CODE REVIEW

**Comment by dg0yt** [comment]
fossies.org's Terms of Use forbid "regular automated accesses" so AFAIU it cannot be used as part of build recipes or CI. 
Cf. https://fossies.org/about.html

**Comment by xavier2k6** [comment]
@dg0yt The `ilammy/setup-nasm` action added a `mirror` in github (nasm 2.15.05) so I believe it may be possible for vcpkg to add it's own self-hosted mirror.

**Comment by xavier2k6** [comment]
Another option could be to use file from https://gstreamer.freedesktop.org/src/mirror/

https://gstreamer.freedesktop.org/src/mirror/nasm-2.16.01-win64.zip

**Comment by teo-tsirpanis** [comment]
@xavier2k6 thanks for the suggestion.

**Comment by cnmade** [comment]
nasm.us down again. this PR looks will help us.

**Review by BillyONeal — DISMISSED** [review]
> fossies.org's Terms of Use forbid "regular automated accesses" so AFAIU it cannot be used as part of build recipes or CI. Cf. https://fossies.org/about.html

+1

**Comment by teo-tsirpanis** [comment]
@BillyONeal I have used a different mirror suggested by @xavier2k6.

**Review by JonLiu1993 — APPROVED** [review]

**Pull request merged**
