### PR TITLE
[rocksdb] Remove default-feature liburing

### LINKED ISSUE #32458: [RocksDB] port cmake error
**Describe the bug**
(In Manifest mode) Port is not self-contained and will produce a CMake error, i.e

[cmake] CMake Error at build/vcpkg_installed/x64-linux/share/rocksdb/RocksDBTargets.cmake:60 (set_target_properties):
[cmake]   The link interface of target "RocksDB::rocksdb" contains:
[cmake] 
[cmake]     uring::uring
[cmake] 
[cmake]   but the target was not found.  Possible reasons include:
[cmake] 
[cmake]     * There is a typo in the target name.
[cmake]     * A find_package call is missing for an IMPORTED target.
[cmake]     * An ALIAS target is missing.
[cmake] 

Also, I do have liburing installed on my system.

**Environment**
Linux Fedora 38
Clang16 gcc13

**Expected behavior**
CMake should succeed, and I can link to RocksDB::rocksdb :)

### PR DESCRIPTION
**Pull request by MonicaLiu0311**
Fixes #32458, Remove default-feature `liburing`.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] ~~SHA512s are updated for each updated download~~
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by autoantwort** [comment]
It would be better to fix the problem instead of removing the feature completely.

**Comment by yurybura** [comment]
@MonicaLiu0311 I can fix RocksDB CMake if you can wait.

**Comment by MonicaLiu0311** [comment]
> @MonicaLiu0311 I can fix RocksDB CMake if you can wait.

Ok, thanks for your contribution🌻

**Comment by yurybura** [comment]
@MonicaLiu0311 The issue has been fixed in #33535.

**Comment by MonicaLiu0311** [comment]
Duplicate of #33535.

**Pull request closed without merging**
