### PR TITLE
[ffmpeg] Install tools

### PR DESCRIPTION
**Pull request by JackBoosY**
Install tools when selecting feature `ffmpeg`.

Related: #9619.

### CODE REVIEW

**Review by PhoebeHui — APPROVED** [review]
LGTM

**Comment by JackBoosY** [comment]
I can't repro `aubio:x64-windows-static` regression on my machine.

**Review by PhoebeHui — APPROVED** [review]

**Comment by cenit** [comment]
also related to https://github.com/microsoft/vcpkg/pull/10368 which deleted them from bin folder

**Pull request merged**
