### PR TITLE
[itk] Add feature opencv supporting ITKBridgeOpenCV

### PR DESCRIPTION
**Pull request by andremueller-cosateq**
see https://github.com/InsightSoftwareConsortium/ITK/tree/master/Modules/Video/BridgeOpenCV

The current Video/BridgeOpenCV module in ITK was not supported before. Added as feature to the ITK port.

- #### What does your PR fix?  

Add the new vcpkg feature `itk[opencv]`

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
unchanged to the base ITK

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  `yes`

### CODE REVIEW

**Review by JonLiu1993 — APPROVED** [review]

**Comment by JonLiu1993** [comment]
All features are tested successfully in the following triplet:
- x86-windows
- x64-windows
- x64-windows-static

**Comment by andremueller-cosateq** [comment]
@JonLiu1993 It seems to be an incompatibility between the dependent opencv[dnn] module and the itk. Possible I should reduce the dependency to only the required opencv modules. I try to fix this.

**Comment by andremueller-cosateq** [comment]
@JonLiu1993 Its working now on my machine (nearly catched fire on that library :-)

`
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Installing: C:/software/tools/vcpkg/packages/itk_x64-windows-static/share/itk/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\amueller\AppData\Local\vcpkg\archives\5a\5ace5c4818f4fd93df2a18c08401cc448eb9463b68298b893012371068221e46.zip
Installing package itk[core,opencl,opencv,tbb,vtk]:x64-windows-static...
Elapsed time for package itk:x64-windows-static: 7.607 min

Total elapsed time: 1.642 h

The package itk provides CMake targets:

    find_package(ITK CONFIG REQUIRED)
    # Note: 92 target(s) were omitted.
    target_link_libraries(main PRIVATE ITKFFT ITKVTK ITKznz itksys)
`

**Comment by JonLiu1993** [comment]
Feature "opencl,opencv,tbb,vtk" tested successfully in the following triplet:
- x86-windows
- x64-windows
- x64-windows-static

**Review by JonLiu1993 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
