### PR TITLE
[ghostscript] Add port

### LINKED ISSUE #10687: [New Port Request] Ghostscript
Library name: Ghostscript

Library description: An interpreter for the PostScript language and for PDF.

Source repository URL: http://git.ghostscript.com/?p=ghostpdl.git;a=summary

Project homepage (if different from the source repository): https://www.ghostscript.com/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

### PR DESCRIPTION
**Pull request by driver1998**
**Describe the pull request**

- What does your PR fix? Fixes #10687

- Which triplets are supported/not supported? Have you updated the CI baseline?
x86-windows
x64-windows
arm-windows
arm64-windows
x64-linux

Note: Windows ports are hardcoded by upstream to use MT/MTd.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

### CODE REVIEW

**Review by LilyWangL — APPROVED** [review]

**Comment by strega-nil** [comment]
@driver1998 have the changes made in the patches been upstreamed?

**Comment by driver1998** [comment]
Well upstreaming doesn't seem possible because they don't take contributions it seems. (AGPL and Commerical dual-license).

**Comment by driver1998** [comment]
I'm still confused about if it actually take contributions... And if it do, how.
Is it fine to merge without upstreaming?

**Comment by dan-shaw** [comment]
@driver1998 Have the changes been upstreamed? 

The reason I hesitate to merge this is that there are a lot of changes in the patch files, and we want to minimize changes to the source. The overall PR and changes look fine.

**Comment by LilyWangL** [comment]
Pinging @driver1998

**Comment by LilyWangL** [comment]
Closing this PR since it seems that no progress is being made. Please reopen if work is still being done.

**Pull request closed without merging**
