### PR TITLE
[clapack] Add uwp support

### PR DESCRIPTION
**Pull request by JackBoosY**
Since we need to use the built-in tools to generate header files, we must first install `clapack:x86-windows` when building `clapack: uwp`.

Related: #9908 

This port does not contain any features.

### CODE REVIEW

**Comment by ras0219-msft** [comment]
This is a reasonably large buildsystem change that would be best to upstream first if possible

**Comment by PhoebeHui** [comment]
@JackBoosY, could you open an issue or PR to clapack?

**Comment by JackBoosY** [comment]
Found github repo https://github.com/Reference-LAPACK/lapack-release/tree/lapack-3.8.0, but the code does not match the official website download.

**Review by PhoebeHui — APPROVED** [review]

**Comment by PhoebeHui** [comment]
@strega-nil, could you help further review?

**Review by strega-nil — CHANGES_REQUESTED** [review]
Could you try defining `_CRT_NONSTDC_NO_DEPRECATE=1` instead of patching?

**Comment by JackBoosY** [comment]
@strega-nil Done.

**Comment by strega-nil** [comment]
LGTM! Thanks @JackBoosY

**Pull request merged**
