### PR TITLE
[fontconfig] no absolute paths

### PR DESCRIPTION
**Pull request by autoantwort**
For #20469

### CODE REVIEW

**Review by JonLiu1993 — APPROVED** [review]

**Comment by JonLiu1993** [comment]
@autoantwort ,Thanks for your pr, could you please take the error log:
````

CMake Error at /agent/_work/1/s/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
  Target "kioexec" links to target "LibMount::LibMount" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  src/kioexec/CMakeLists.txt:28 (add_executable)


CMake Error at /agent/_work/1/s/scripts/buildsystems/vcpkg.cmake:578 (_add_library):
  Target "kio_trash" links to target "LibMount::LibMount" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  src/ioslaves/trash/CMakeLists.txt:30 (add_library)


CMake Error at /agent/_work/1/s/scripts/buildsystems/vcpkg.cmake:578 (_add_library):
  Target "kcm_trash" links to target "LibMount::LibMount" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  src/ioslaves/trash/CMakeLists.txt:95 (add_library)
````

**Comment by JonLiu1993** [comment]
@autoantwort ,Could you please fix the conflict file?

**Review by JonLiu1993 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the fix!

**Pull request merged**
