### PR TITLE
[comms] Add new ports

### PR DESCRIPTION
**Pull request by mathisloge**
This PR added two tightly coupled libraries. 
The comms library is the main header only library. 
Commsdsl is both a tool and a library to generate the necessary code used later in your project.

- Which triplets are supported/not supported? Have you updated the CI baseline? think all

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)? yes

### CODE REVIEW

**Comment by mathisloge** [comment]
can anyone get the error logs of the ci?

**Comment by LilyWangL** [comment]
> can anyone get the error logs of the ci?

You can download the error log from https://dev.azure.com/vcpkg/public/_build/results?buildId=44487&view=artifacts&type=publishedArtifacts

**Comment by mathisloge** [comment]
@LilyWangL so osx and x64-static will install correctly but the CI fails. In the logs are no errors. Do you know why it fails?

**Comment by LilyWangL** [comment]
> @LilyWangL so osx and x64-static will install correctly but the CI fails. In the logs are no errors. Do you know why it fails?

It needs to remove directory `bin` when `VCPKG_LIBRARY_LINKAGE STREQUAL "static"`, could you continue to fix `commsdsl` build error on Linux?

**Comment by mathisloge** [comment]
thanks for fixing that! 

I will lcontinue with the linux port

**Comment by mathisloge** [comment]
So with the `-DCOMMSDSL_NO_WARN_AS_ERR=ON` Flag it is working. 
The error on linux was a known boost error. Either in the next version of commsdsl or maybe in the next version of boost this could be removed. 


See https://github.com/commschamp/commsdsl/issues/6#issuecomment-718249648 for reference.

**Review by LilyWangL — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for your help!

**Pull request merged**
