### PR TITLE
[ecsutil] port is no longer maintained and needs to be removed from VCPKG.

### PR DESCRIPTION
**Pull request by bobk2824**
Please remove this port (ecsutil) from VCPKG.

### CODE REVIEW

**Comment by FrankXie05** [comment]
@bobk2824 We can use `set(VCPKG_POLICY_EMPTY_PACKAGE enabled)` on `portfile.cmake` to indicate that this port is empty. No need to delete all files. :)

**Comment by BillyONeal** [comment]
Just because something has not had changes in a while is not grounds for being deindexed. Is the presence of this library in vcpkg creating specific problems?

**Comment by BillyONeal** [comment]
Sorry, I missed that you were the upstream before.

**Comment by bobk2824** [comment]
Thanks

On Jun 12, 2024, at 7:44 PM, BillyONeal ***@***.***> wrote:

﻿

Sorry, I missed that you were the upstream before.

**Pull request merged**
