### PR TITLE
[ freetype2/harfbuzz/sdl2] Update to the latest version

### PR DESCRIPTION
**Pull request by Sibras**
[freetype2] Update to 2.11.1
[harfbuzz] Update to 3.2.0
[sdl2] Update to 2.0.20

### CODE REVIEW

**Comment by JonLiu1993** [comment]
@Sibras ,Thanks for your pr, looks the ci test failed on many triplet

This is error log:
https://dev.azure.com/vcpkg/public/_build/results?buildId=65939&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by Sibras** [comment]
Hmm, seems the ffmpeg 5.0 update is not supported by several other packages. Those packages would need to be updated before we can move to ffmpeg 5.0. Ill remove the ffmpeg changes from the PR and test the other changes and hold off on 5.0 until other downstream packages update accordingly.

**Comment by tsunamistate** [comment]
@JonLiu1993 is there anything holding up the PR merge? CI is green, and all comments were addressed

**Review by JonLiu1993 — APPROVED** [review]

**Comment by JonLiu1993** [comment]
> @JonLiu1993 is there anything holding up the PR merge? CI is green, and all comments were addressed

I need to test the features locally, if all tests are successful we will merge this pr soon

**Comment by JonLiu1993** [comment]
freetype2:
All features are tested successfully in the following triplet:
- x86-windows
- x64-windows
- x64-windows-static

harbuzz:
Expect feature 'coretext'
All features are tested successfully in the following triplet:
- x86-windows
- x64-windows

sdl2:
Feature 'vulkan' tested successfully in the following triplet:
- x86-windows
- x64-windows
- x64-windows-static

**Comment by BillyONeal** [comment]
Thanks for the updates <3

**Comment by dogstar25** [comment]
This looks to be merged and closed but vcpkg still reports SDL2 version 2.0.16. ?

**Comment by BillyONeal** [comment]
Did you do a `git pull`?

**Comment by dogstar25** [comment]
Thanks. I misunderstood how vcpkg search worked. Thanks

**Pull request merged**
