### PR TITLE
Compute VCPKG_ROOT and VCPKG_COMMAND if needed

### PR DESCRIPTION
**Pull request by zlaski**
This simple fix applies to all platforms.

If VCPKG_ROOT and/or VCPKG_COMMAND are not defined, their values are computed based on the location of the ports.cmake file.

### CODE REVIEW

**Comment by autoantwort** [comment]
Why do you need `VCPKG_ROOT` in a portfile?

**Comment by zlaski** [comment]
I do not understand the nature of these timeouts.  Is there something I can do?

**Review by BillyONeal — CHANGES_REQUESTED** [review]
If these are not being set something is seriously wrong and attempting to paper over it in the scripts tree is not the correct fix. The vcpkg.exe needs to be updated.

**Comment by JackBoosY** [comment]
IMO these 3 variables should be set as environment variables outside.

**Comment by vicroms** [comment]
@zlaski what problem are you trying to solve with this PR? Is there a related issue that we can look at?

**Pull request closed without merging**
