### PR TITLE
[cgal] update to 5.5.2

### PR DESCRIPTION
**Pull request by lrineau**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [x] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by lrineau** [comment]
It turns out my local computer runs x64_linux, and I can reproduce the CI build failure.

The issue in the build of `colmap`, and the culprit seems to be `glog` on Linux, being compiled in static, and not pulling `installed/x64-linux/lib/libgflags.a` as a dependency.

See the build logs at https://gist.github.com/lrineau/40ce6eecbca3ca52cfe8cb2bf16b72d9

Do you have an idea what I should do? Do I have to fix the `colmap/glog/gflags` issue in this PR, if I can?

**Comment by lrineau** [comment]
Now the new issue is still with `x64-linux`, and still with colmap. In `install-x64-linux-dbg-err.log`:
> ninja: error: '/mnt/vcpkg-ci/installed/x64-linux/debug/lib/intel64/libmkl_intel_lp64.a', needed by 'src/exe/colmap', missing and no known rule to make it

The file `installed/x64-linux/debug/lib/intel64/libmkl_intel_lp64.a` does not exists. but `installed/x64-linux/debug/lib/intel64/libmkl_intel_lp64.a` does. The version in `debug/lib/`  is missing. Anyway, that does not seem to be an issue with `colmap`, because colmap does not depend on MKL, or BLAS, or LAPACK. But `suitesparse` does.

I wonder how `intel-mkl` got pull in the dependencies.

**Comment by lrineau** [comment]
> Now the new issue is still with `x64-linux`, and still with colmap. In `install-x64-linux-dbg-err.log`:
> 
> > ninja: error: '/mnt/vcpkg-ci/installed/x64-linux/debug/lib/intel64/libmkl_intel_lp64.a', needed by 'src/exe/colmap', missing and no known rule to make it
> 
> The file `installed/x64-linux/debug/lib/intel64/libmkl_intel_lp64.a` does not exists. but `installed/x64-linux/debug/lib/intel64/libmkl_intel_lp64.a` does. The version in `debug/lib/` is missing. Anyway, that does not seem to be an issue with `colmap`, because colmap does not depend on MKL, or BLAS, or LAPACK. But `suitesparse` does.
> 
> I wonder how `intel-mkl` got pull in the dependencies.

Now I know. See the issue https://github.com/microsoft/vcpkg/issues/30580. I do not have a fix though.

**Comment by dg0yt** [comment]
`installed/x64-linux/debug/lib/intel64/libmkl_intel_lp64.a` is strange indeed.

**Comment by lrineau** [comment]
@MonicaLiu0311 After the merge of `master`, the fix from PR #30421 got pulled and now `colmap` compiles. This PR checks are now eventually all green.

Should I rebase, or can this PR be merged as it is?

**Comment by dg0yt** [comment]
The easiest thing is to merge the latest master into your branch.

**Comment by lrineau** [comment]
> The easiest thing is to merge the latest master into your branch.

That is what I did with commit 8253c31f97a9f69b5ecc867719946e6b5171faf2 (after you pointed to #30421), and that fixed the CI issue for this PR.

**Comment by MonicaLiu0311** [comment]
All features are tested successfully in the following triplet:
```
x86-windows
x64-windows
x64-windows-static
```

The usage test passed (header files found):
```
The package cgal provides CMake targets:

    find_package(CGAL CONFIG REQUIRED)
    target_link_libraries(main PRIVATE CGAL::CGAL)
```

**Review by MonicaLiu0311 — APPROVED** [review]

**Pull request merged**
