### PR TITLE
[vcpkg] EOL LF for ci.baseline.txt

### PR DESCRIPTION
**Pull request by Neumann-A**
@JackBoosY 
see https://github.com/microsoft/vcpkg/pull/12229#discussion_r457801086

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
@ras0219-msft @strega-nil I think we should add a step to check whether the format of `ci.baseline.txt` is correct.

**Comment by Neumann-A** [comment]
@JackBoosY: Let git handle it for you automatically ;) https://docs.github.com/en/github/using-git/configuring-git-to-handle-line-endings . No checks needed. Resolving merge conflicts in the ci.baseline.txt via github should also work again since github will no longer autconvert to crlf.

**Comment by JackBoosY** [comment]
It is difficult to mark label in this PR, but I prefer to use `vcpkg bug` here.

**Review by strega-nil — APPROVED** [review]
Yeah, LGTM!

**Comment by JackBoosY** [comment]
We need to handle the qt5-imageformats regression as soon as possible.

**Pull request merged**
