### PR TITLE
[poppler, poppler-data, lcms] Add new ports; Export lcms targets

### PR DESCRIPTION
**Pull request by ChaoJia**
new ports poppler and poppler-data: Poppler is a PDF rendering library based on the xpdf-3.0 code base.
upstream: https://poppler.freedesktop.org/
repo: https://gitlab.freedesktop.org/poppler
Had to fix lcms so that I don't have to provide another `FindLCMS2.cmake` in the new ports. 
Related issues: #4702, #8238

### CODE REVIEW

**Comment by ChaoJia** [comment]
The portfile for lcms was modified based on an older version; seems the current version in master branch has already exported lcmsConfig.cmake. But poppler and a few other packages need LCMS2. I assume FindLCMS2 is de facto.

**Comment by JackBoosY** [comment]
Error in arm64-windows:
```
CMake Error at C:/vsts/_work/2/s/scripts/buildsystems/vcpkg.cmake:195 (_add_library):
  Target "poppler" links to target "OpenSSL::SSL" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:500 (add_library)
```

**Comment by ChaoJia** [comment]
> Error in arm64-windows:
> 
> ```
> CMake Error at C:/vsts/_work/2/s/scripts/buildsystems/vcpkg.cmake:195 (_add_library):
>   Target "poppler" links to target "OpenSSL::SSL" but the target was not
>   found.  Perhaps a find_package() call is missing for an IMPORTED target, or
>   an ALIAS target is missing?
> Call Stack (most recent call first):
>   CMakeLists.txt:500 (add_library)
> ```

There is definitely something wrong with `windows PR test arm64`. Windows version of curl does not depends on openssl. The rest of poppler has nothing to do with openssl. After I made curl optional as a feature, the issue went away. 

As for os x, I tried to suppress "ranlib blah blah has no symbols", yet no success, and I've got no more tricks up my sleeve. The spell "By the light of Agamotto, disperse ranlib's evil." does not work either...

**Review by JackBoosY — CHANGES_REQUESTED** [review]

**Comment by JackBoosY** [comment]
As this PR contains many modifications, we may need to review it multiple times, please understand us.

Thanks.

**Comment by ChaoJia** [comment]
Sorry I don't have time for this for at least the next couple of months. Feel free to make necessary modifications if that's an option to you, or you can close this PR as you please.

**Comment by dan-shaw** [comment]
@ChaoJia Going to close this PR as this PR has been open too long. If you are interested in working on this, feel free to reopen, but it might make more sense to make a new PR (otherwise we might lose track of it).

**Comment by JackBoosY** [comment]
If you are interested in continuing this PR, please reopen a new one.

Thanks.

**Pull request closed without merging**
