### PR TITLE
[mp-units] add feature flag, use development version 2

### PR DESCRIPTION
**Pull request by jbbjarnason**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [ ] The "supports" clause reflects platforms that may be fixed by this new version
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [ ] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Review by Cheney-W — APPROVED** [review]

**Comment by Cheney-W** [comment]
Feature passed with following triplets:
x86-windows 
x64-windows 
x64-windows-static

**Comment by Cheney-W** [comment]
There is no mention in the [maintainer-guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md) that using sources from other branch as a feature is not allowed, and this port is not being depended on by any other port. Therefore, I have added the `reviewed` flag and kindly request the vcpkg team to conduct further review.

**Comment by dg0yt** [comment]
Well, there is ["Do not use features to implement alternatives"](https://learn.microsoft.com/en-us/vcpkg/contributing/maintainer-guide#do-not-use-features-to-implement-alternatives), and ["A feature may engage preview or beta functionality"](https://learn.microsoft.com/en-us/vcpkg/contributing/maintainer-guide#a-feature-may-engage-preview-or-beta-functionality).

So the question is: Does the feature have a high probability of not disrupting the non-preview functionality (for example, no API removals)?

**Comment by jbbjarnason** [comment]
> @jbbjarnason Moving the PR to draft. When you responded to the question about `Does the feature have a high probability of not disrupting the non-preview functionality (for example, no API removals)?` please revert to "ready for review".
@Cheney-W 
I cannot answer that question, as I am not a maintainer of the mp-units library. I do not want to use API of version 0.7 which is becoming obsolete therefore added this feature flag. I think the maintainer of the library would benefit from bigger audience of his newer version.

**Comment by Cheney-W** [comment]
If this is just your personal requirement, I believe you can use the [overlay-ports](https://learn.microsoft.com/en-us/vcpkg/commands/common-options#overlay-ports) feature.

**Comment by Neumann-A** [comment]
> Does the feature have a high probability of not disrupting the non-preview functionality (for example, no API removals)?

The answer to that question is no since according to the presentation the whole API changed.

**Pull request closed without merging**
