### PR TITLE
update asmjit, fbgemm, polyhook2, start asmtk

### PR DESCRIPTION
**Pull request by stevemk14ebr**
As per https://github.com/microsoft/vcpkg/pull/27476#issuecomment-1302647574

This:
* Removes fbgemm (for now)
* Updates asmjit
* Updates polyhook2
* Attempts to add asmtk

AsmTk currently doesn't correctly link asmjit and I'm not sure exactly why. So that needs to be fixed by someone, then polyhook2 should build after that (or at least be close, asmtk probably needs adjusted first).

### CODE REVIEW

**Comment by FrankXie05** [comment]
Pinging @stevemk14ebr for response. Is work still being done for this PR?

**Comment by stevemk14ebr** [comment]
Yes, but I need help. Asmtk currently doesn't link to asmjit correctly and I'm unsure how to fix.

**Comment by FrankXie05** [comment]
@stevemk14ebr I will pay attention to and deal with this PR. :)

**Comment by stevemk14ebr** [comment]
You're the best, thanks for the help! If the linking issues with asmtk and asmjit can be fixed this will be very close to ready to merge.

**Comment by Chlumsky** [comment]
@FrankXie05 Any news?

**Comment by Chlumsky** [comment]
Can something be done about it?

**Comment by cbrl** [comment]
The latest version of fbgemm seems to work if I copy the changes made to CMakeLists.txt in the old patch file. See https://github.com/cbrl/vcpkg/commit/b9a47076188f93118c44d2cdde060d98e20836d5 for reference, but note that that branch doesn't include the required update to asmjit. I think the reference change can be included in this PR rather than removing fbgemm.

**Comment by FrankXie05** [comment]
Sorry, it took so long to follow this PR. 
I have resolved the issue with `error LNK2019` and have been keeping an eye on completing this PR. :)
@stevemk14ebr @Chlumsky

**Comment by FrankXie05** [comment]
We need to find a compatible method instead of removing port `fbgemm`. 🤔

**Comment by FrankXie05** [comment]
Revert `fbgemm`.

**Comment by FrankXie05** [comment]
```
E:\NEW-PORT\vcpkg\buildtrees\fbgemm\src\86cd37ac2a-f4be5156b3\include\fbgemm\./Utils.h(91): error C2872: 'x86': ambiguous symbol
E:\NEW-PORT\vcpkg\buildtrees\fbgemm\src\86cd37ac2a-f4be5156b3\include\fbgemm\./Utils.h(18): note: could be 'asmjit::x86'
E:\NEW-PORT\vcpkg\installed\x64-windows\include\asmjit\x86/x86instdb.h(11): note: or       'asmjit::_abi_1_9::x86'
```

**Comment by FrankXie05** [comment]
> ```
> E:\NEW-PORT\vcpkg\buildtrees\fbgemm\src\86cd37ac2a-f4be5156b3\include\fbgemm\./Utils.h(91): error C2872: 'x86': ambiguous symbol
> E:\NEW-PORT\vcpkg\buildtrees\fbgemm\src\86cd37ac2a-f4be5156b3\include\fbgemm\./Utils.h(18): note: could be 'asmjit::x86'
> E:\NEW-PORT\vcpkg\installed\x64-windows\include\asmjit\x86/x86instdb.h(11): note: or       'asmjit::_abi_1_9::x86'
> ```

Have been fixed by updating the `fbgemm` version to 0.4.1.

**Review by FrankXie05 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the update!

**Comment by BullyWiiPlaza** [comment]
@stevemk14ebr
Can you please also take care of providing the latest PolyHook2 bug fixed build to vcpkg once again (especially regarding https://github.com/stevemk14ebr/PolyHook_2_0/pull/183)? Thanks

**Pull request merged**
