### PR TITLE
[freerdp] Fix include path

### PR DESCRIPTION
**Pull request by KangLin**
The pull request is fix INCLUDE directory of freerdp.
The fix-include-path.patch is changed INCLUDE directory of freerdp. So that, The INCLUDE directory obtained by find_package is incorrect in my application project.
I don't unstander why is change it.

### CODE REVIEW

**Review by NancyLi1013 — COMMENTED** [review]
Could you please also bump version in CONTROL file?
Add `Port-Version: 1 `below `Version: 2.2.0`.

**Comment by NancyLi1013** [comment]
Hi @KangLin 

Thanks for your PR.

Have you tested the usage of `freerdp`? Can it work fine for you?

**Comment by KangLin** [comment]
> Hi @KangLin
> 
> Thanks for your PR.
> 
> Have you tested the usage of `freerdp`? Can it work fine for you?

Yes. I has test the PR in my project.
https://github.com/KangLin/RabbitRemoteControl


> Could you please also bump version in CONTROL file?
> Add Port-Version: 1 below Version: 2.2.0.

Why add it?

**Comment by NancyLi1013** [comment]
Every port needs to update its version once there are some changes in this port. Currently, we use `Port-Version` field to express that this port has been changed, which makes it easy to track port versions.

Please see this doc.
https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/control-files.md#port-version

**Comment by KangLin** [comment]
> Could you please also bump version in CONTROL file?
> Add `Port-Version: 1 `below `Version: 2.2.0`.

OK!

**Comment by KangLin** [comment]
> > Could you please also bump version in CONTROL file?
> > Add `Port-Version: 1 `below `Version: 2.2.0`.
> 
> OK!

@NancyLi1013 
After modifying the Port-Version , the error still occurs

**Comment by NancyLi1013** [comment]
Hi @KangLin 

You need to run `vcpkg x-add-version freerdp
` and then submit the changes for add_versions.
```
Found the following errors:
Error: While reading versions for port freerdp from file: C:\a\1\s\port_versions\f-\freerdp.json
       Version `2.2.0#1` was not found in versions file.
       Run:

           vcpkg x-add-version freerdp

       to add the new port version.

To attempt to resolve all errors at once, run:

    vcpkg x-add-version --all
```

**Comment by NancyLi1013** [comment]
Could you please merge master to this PR? @KangLin

**Comment by KangLin** [comment]
> Could you please merge master to this PR? @KangLin

This is ok!

**Comment by NancyLi1013** [comment]
It seems that you forgot to update CONTROL file. Please add `Port-Version: 1` field below `Version`.

Note: Please run vcpkg x-add-version freerdp again after this change.

**Comment by KangLin** [comment]
@NancyLi1013
Add Port-version is ok!

**Review by NancyLi1013 — APPROVED** [review]

**Comment by ras0219-msft** [comment]
Thanks for the PR!

We adjust the include paths because vcpkg's install layout is designed to enable code to compile with just one `-I`: `/include`. By renaming `/include/freerdp2/freerdp` to just `/include/freerdp`, we're able to do that.

However, there was a bug in our patch, which your code caught (Sorry)! I've pushed a commit which should fix your code and also keep our rename :)

**Review by ras0219-msft — APPROVED** [review]
LGTM

**Pull request merged**
