### PR TITLE
[libzippp] Update to libzippp-4.0-1.7.3

### PR DESCRIPTION
**Pull request by ctabin**

### CODE REVIEW

**Comment by ctabin** [comment]
I think I'll need some help here. The pipeline is failing with:
```
Building package libzippp[core]:x64-osx...
Could not locate cached archive: /Users/vagrant/Data/archives/96/96614d5a0a088fda659cd16e7f17276e6fd98671.zip
-- Using cached /Users/vagrant/Data/downloads/ctabin-libzippp-e15a60e8ff1f2ce955886acd6a6d89823787255f.tar.gz
-- Extracting source /Users/vagrant/Data/downloads/ctabin-libzippp-e15a60e8ff1f2ce955886acd6a6d89823787255f.tar.gz
-- Using source at /Users/vagrant/Data/buildtrees/libzippp/src/823787255f-facc9098d7.clean
-- Configuring x64-osx-dbg
-- Configuring x64-osx-rel
-- Building x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:141 (message):
    Command failed: /Volumes/data/downloads/tools/cmake-3.17.2-osx/cmake-3.17.2-Darwin-x86_64/CMake.app/Contents/bin/cmake --build . --config Debug --target install -- -v
    Working Directory: /Users/vagrant/Data/buildtrees/libzippp/x64-osx-dbg
    See logs for more information:
      /Users/vagrant/Data/buildtrees/libzippp/install-x64-osx-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/libzippp/portfile.cmake:19 (vcpkg_install_cmake)
  scripts/ports.cmake:79 (include)
```
How can I access to this log, since I don't have any apple/mac/osx to test on ? Any idea why it fails ?
Thanks !

**Comment by PhoebeHui** [comment]
Could you update the Version in CONTROL file for libzip and libzippp?

libzip: please remove the 'Port-Version: 1' as well.
Form 
```
Version: 1.7.1
Port-Version: 1
```
To 
```
Version: 1.7.3
```

libzippp:
From Version: 3.1-1.6.1 to Version: 4.0-1.7.3.

**Comment by ctabin** [comment]
Hi @PhoebeHui and thanks for your reply. I added the update of libzip to see it that could solve the pipeline failure on osx, but unfortunately it isn't related, so I made a #13625 for this. Do you have any idea how I could see the content of the file `/Users/vagrant/Data/buildtrees/libzippp/install-x64-osx-dbg-out.log` specified in the logs ?

I'll rebase the branch and update the control file once #13625 is merged :thumbsup:

**Comment by PhoebeHui** [comment]
See the failures on osx from install-x64-osx-dbg-out.log.

```
[1/3] /Library/Developer/CommandLineTools/usr/bin/c++   -I/Users/vagrant/Data/buildtrees/libzippp/src/823787255f-facc9098d7.clean/src -isystem /Users/vagrant/Data/installed/x64-osx/include -fPIC -g -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -MD -MT CMakeFiles/libzippp.dir/src/libzippp.cpp.o -MF CMakeFiles/libzippp.dir/src/libzippp.cpp.o.d -o CMakeFiles/libzippp.dir/src/libzippp.cpp.o -c /Users/vagrant/Data/buildtrees/libzippp/src/823787255f-facc9098d7.clean/src/libzippp.cpp
FAILED: CMakeFiles/libzippp.dir/src/libzippp.cpp.o 
/Library/Developer/CommandLineTools/usr/bin/c++   -I/Users/vagrant/Data/buildtrees/libzippp/src/823787255f-facc9098d7.clean/src -isystem /Users/vagrant/Data/installed/x64-osx/include -fPIC -g -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -MD -MT CMakeFiles/libzippp.dir/src/libzippp.cpp.o -MF CMakeFiles/libzippp.dir/src/libzippp.cpp.o.d -o CMakeFiles/libzippp.dir/src/libzippp.cpp.o -c /Users/vagrant/Data/buildtrees/libzippp/src/823787255f-facc9098d7.clean/src/libzippp.cpp
In file included from /Users/vagrant/Data/buildtrees/libzippp/src/823787255f-facc9098d7.clean/src/libzippp.cpp:40:
/Users/vagrant/Data/buildtrees/libzippp/src/823787255f-facc9098d7.clean/src/libzippp.h:165:117: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
        explicit ZipArchive(const std::string& zipPath, const std::string& password="", Encryption encryptionMethod=Encryption::None);
                                                                                                                    ^
/Users/vagrant/Data/buildtrees/libzippp/src/823787255f-facc9098d7.clean/src/libzippp.cpp:97:14: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
        case Encryption::None:
             ^
/Users/vagrant/Data/buildtrees/libzippp/src/823787255f-facc9098d7.clean/src/libzippp.cpp:638:66: error: expected expression
    std::function<bool(const void*,libzippp_uint64)> writeFunc = [&ofOutput](const void* data,libzippp_uint64 size){ ofOutput.write((char*)data, size); return bool(ofOutput); };
                                                                 ^
2 warnings and 1 error generated.
ninja: build stopped: subcommand failed.
```

**Comment by ctabin** [comment]
The syntax used is a [lambda](https://en.cppreference.com/w/cpp/language/lambda) supported from C++11. Is the OSX compiler still in a previous-old-incompatible version then ?

**Comment by PhoebeHui** [comment]
The OSX compiler in CI testing machine:
-- The C compiler identification is AppleClang 11.0.3.11030032
-- The CXX compiler identification is AppleClang 11.0.3.11030032

**Comment by ctabin** [comment]
@PhoebeHui Do you have any idea why the x64_osx job is stuck ? It doesn't look like related to my changes... Thanks :pray:

**Comment by PhoebeHui** [comment]
@ctabin, it's not related to your changes, please ignore it.

However, the osx still need to be test, since it failed in prvious run https://github.com/microsoft/vcpkg/pull/13620#issuecomment-696002042.

Does anyone who help to test it?

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
