### PR TITLE
[vcpkg.cmake] add a way to get `--debug` output

### PR DESCRIPTION
**Pull request by strega-nil-ms**
@mathisloge on discord pointed out this missing feature in vcpkg.cmake.

### CODE REVIEW

**Comment by Neumann-A** [comment]
as pointed out in discord `VCPKG_INSTALL_OPTIONS` can be used for this.

**Comment by autoantwort** [comment]
Please also add documentation for this new variable

**Review by Be-ing — APPROVED** [review]

**Comment by Be-ing** [comment]
Thanks for implementing this useful feature.

**Comment by Be-ing** [comment]
Ready for merge?

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
Any progrees in this PR?

**Comment by JackBoosY** [comment]
Ping @strega-nil-ms

**Comment by strega-nil-ms** [comment]
Opinion from the meeting:

- Instead of adding a variable, just use `VCPKG_INSTALL_OPTIONS` (add docs for this)
- It would be great to pass to the binary what integration we're doing

**Comment by strega-nil-ms** [comment]
Closing as "not desired"

**Pull request closed without merging**
