### PR TITLE
[CGAL] Upgrade to 5.2

### PR DESCRIPTION
**Pull request by maxGimeno**
Upgrade CGAL to version 5.2.

### CODE REVIEW

**Comment by JonLiu1993** [comment]
@maxGimeno ，Thank you for your contribution, we currently recommend to update the latest stable version instead of the pre-release version, so I can't approve your pr, we will update it in time after the stable version is released!

**Comment by maxGimeno** [comment]
@JonLiu1993 No problem, it was just to check that the CI tests pass, that is why I made a draft PR. I'll update the version as soon as the release is out, and "un-draft" then.

**Comment by JonLiu1993** [comment]
@maxGimeno ，Have you tested the feature？

**Comment by maxGimeno** [comment]
Only the installation part.

**Comment by maxGimeno** [comment]
I tested an example compilation, it works

**Review by JonLiu1993 — APPROVED** [review]

**Pull request merged**
