### PR TITLE
[ls-qpack] Update, revise

### PR DESCRIPTION
**Pull request by dg0yt**
Enable uwp.
Fix mingw, emscripten.
Fix pkgconfig.
Make CMake config independent of pkgconfig.

Patch upstreaming at https://github.com/litespeedtech/ls-qpack/pulls.

### CODE REVIEW

**Comment by dg0yt** [comment]
This doesn't "DEPEND" on upstream changes. Of course we could wait for upstream acceptance of the changes, but in the meantime the port is partially broken.

**Comment by Mengna-Li** [comment]
Let's wait for upstream approve or response.

**Comment by dg0yt** [comment]
This blocks improvements to downstream ports.

**Comment by dg0yt** [comment]
In particular, this PR enables the removal of pkg-config from the transitive usage requirements for the cmake config. Which is one step towards fixing the sad state of msh3's exported usage.

**Comment by talregev** [comment]
> Let's wait for upstream approve or response.

I agree with @dg0yt. we should have to wait for upstream. @dg0yt already notice them with the PR.
If you still don't agree, we can review this port and let do a vcpkg team review that they will decide.

**Comment by talregev** [comment]
@Mengna-Li I agree with @dg0yt. He already notified upstream.
I already have similar condition when I export namespace cmake in ls-qpack. It was first merge in vcpkg, the upstream merge my PR without any response.
https://github.com/litespeedtech/ls-qpack/pull/59
https://github.com/microsoft/vcpkg/pull/40652

If you still don't agree, please review this port and we can have vcpkg team review, and let all team decide.

Thank you for your help and time to review this port 🙏🏻

**Review by Mengna-Li — APPROVED** [review]

**Pull request merged**
