### PR TITLE
[fontconfig] Fix FC_TEMPLATEDIR

### PR DESCRIPTION
**Pull request by Osyotr**
Follow-up to #28236

See https://github.com/chromium/chromium/blob/main/third_party/fontconfig/BUILD.gn#L56-L58

### CODE REVIEW

**Review by Cheney-W — APPROVED** [review]

**Comment by BillyONeal** [comment]
> Follow-up to #28236

I'm not sure I understand. That PR is intentionally damaging FC_TEMPLATEDIR to ensure one from the system isn't accidentally used. This PR appears to be intentionally trying to use one from the system?

**Review by BillyONeal — CHANGES_REQUESTED** [review]
(Just looking for an explanation, the change is likely OK!)

**Comment by Osyotr** [comment]
> That PR is intentionally damaging FC_TEMPLATEDIR to ensure one from the system isn't accidentally used.

Yes but only on windows. On unix #28236 replaces `${CURRENT_PACKAGES_DIR}` with nothing, so `${CURRENT_PACKAGES_DIR}/etc` becomes `/etc` and so on. This is what chromium does.
This PR replaces `/share` with `/usr/share` because the former path is incorrect and doesn't exist.

**Review by BillyONeal — APPROVED** [review]
I strongly suspect this is wrong but it isn't more wrong than what was already here.

**Comment by BillyONeal** [comment]
Thanks :)

**Pull request merged**
