### PR TITLE
[openexr] Update to 3.1.5

### PR DESCRIPTION
**Pull request by Thomas1664**
**Describe the pull request**

- #### What does your PR fix?
  Fixes #...
  Note: Duplicate of #20957

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  <all / linux, windows, ...>, <Yes/No>

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  `Your answer`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  <Yes / I am still working on this PR>

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by dg0yt** [comment]
I don't see an official `FindOpenEXR.cmake` in CMake. So what is the wrapper targeting at? Each downstream may have it is own variant of the find module. Differences must be handled in downstream ports. Port openexr must not accumulate dependencies on downstream find module implementations.

**Comment by dg0yt** [comment]
To limit downstream patching, would be a transitional option to:
- add forwarding headers from openexr to imath (in particular for `half.h`)
- add a dependency to imath config to openexr config?

**Comment by dg0yt** [comment]
> To limit downstream patching, would be a transitional option to:
> 
>  * add forwarding headers from openexr to imath (in particular for `half.h`)
> 
>  * add a dependency on imath config to openexr config?

... perhaps implemented behind an opt-in `openexr[imath-transition]` feature.

**Comment by Thomas1664** [comment]
@dg0yt Seems like you're more familiar with this than me. Feel free to open your own PR to update openexr. Honestly, I don't want to work on another OpenSSL-like patch thing.

**Comment by Adela0814** [comment]
@Thomas1664 Is work still being done for this PR?

**Comment by Thomas1664** [comment]
> @Thomas1664 Is work still being done for this PR?

No. I don't have time for this.

**Comment by Adela0814** [comment]
Closing this PR, please reopen if you continue this work.

**Pull request closed without merging**
