### PR TITLE
[yara] Usage instructions

### PR DESCRIPTION
**Pull request by VelocityRa**
Related: #17427

### CODE REVIEW

**Comment by VelocityRa** [comment]
```cmake
CMake Error at ports/yara/portfile.cmake:27 (file):
  file COPY cannot find "C:/a/1/s/ports/yara/usage": File exists.
Call Stack (most recent call first):
  scripts/ports.cmake:142 (include)
```
Huh?

**Comment by Hoikas** [comment]
Rename `usage.txt` to `usage`.

**Comment by VelocityRa** [comment]
Oh yea my editor added that.

**Comment by JackBoosY** [comment]
No, I think the correct way is export the unofficial target instead of this.
The way which you provided is only find the release library.

**Comment by VelocityRa** [comment]
@JackBoosY Closed it because I don't know how to do that. I can work on it if you point me to the right cmake commands to use.

**Comment by VelocityRa** [comment]
If it's so hard to actually use, I don't really understand why the port was merged in the first place in such a state.

**Comment by VelocityRa** [comment]
Current PR is also wrong because it depends on openssl too not just openssl. But I assume doing it the 'correct' way you said would fix this.

**Comment by JackBoosY** [comment]
@VelocityRa I provide you 2 ways:
1. export the unofficial target, example: https://github.com/microsoft/vcpkg/blob/030cfaa24de9ea1bbf0a4d9c615ce7312ba77af1/ports/libmariadb/export-cmake-targets.patch
2. Configure the `unofficial-yara-config.cmake.in`, example: https://github.com/microsoft/vcpkg/blob/master/ports/pcre/unofficial-pcre-config.cmake

I perfer the first one.

**Pull request closed without merging**
