### PR TITLE
[openssl] Enable builds with clang-cl

### PR DESCRIPTION
**Pull request by Neumann-A**
clang always uses /Z7 so i deactivated the PDB install rules. Allowing /Z7 on normal windows requires removing /Zi /Fd from the internal build rules.

### CODE REVIEW

**Review by FrankXie05 — DISMISSED** [review]

**Comment by FrankXie05** [comment]
@Neumann-A Is this PR ready for review?

**Comment by Neumann-A** [comment]
> @Neumann-A Is this PR ready for review?

Yes.

**Comment by BillyONeal** [comment]
@Neumann-A Can you confirm that you are OK with the nitpick fix I pushed in https://github.com/microsoft/vcpkg/pull/25869/commits/7fbbf7fe64c88025c2dd9f1e3a2d7f4996e36733 ?

**Review by BillyONeal — APPROVED** [review]

**Comment by Neumann-A** [comment]
> @Neumann-A Can you confirm that you are OK with the nitpick fix I pushed in https://github.com/microsoft/vcpkg/commit/7fbbf7fe64c88025c2dd9f1e3a2d7f4996e36733 ?

LGTM.

**Pull request merged**
