### PR TITLE
[uwebsockets] update to 0.14.0a4

### PR DESCRIPTION
**Pull request by ghost**
This transitions from CMake to msbuild. It is tested with all 4 configurations (x64, Win32, Release, Debug) and can be a base for the upcoming 0.14.0 version. I had some issues with the builtin vcpkg_build_msbuild so I just called the msbuild tool directly and this works nicely. I think this should be portable?

You can squash this into one commit

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Hey alex, thanks for making this PR.

Sorry I wasn't able to get to your issue[1] quickly! I'll answer that issue here as well as address this PR.

The most common way that MSBuild projects use Vcpkg is via the User-wide integration (as you know). However, Vcpkg is designed to support multiple instances (of Vcpkg) on a single machine and does not require user-wide integration. This is why the `vcpkg_build_msbuild()` command was not working in your issue -- it explicitly ignores the user-wide integration (since we can never assume it is available).

However, the fix is not as simple as "forcing on" the user-wide integration, because that could cause the project to be built in the context of a _different_ Vcpkg instance on the same machine. We need to force the project to specifically import `scripts\buildsystems\msbuild\vcpkg.targets` from the particular instance we're building inside.

Given that you're the author of the library, I think there are three reasonable options to proceed:
1. The portfile patches an import line into the project [2] right below the "Globals" `PropertyGroup`. We then use `vcpkg_build_msbuild()` in the portfile and set the path accordingly.
2. You could add [2] to the upstream MSBuild project (it has no effect if `VcpkgTargetsFilePath` is not defined). Then we do the same as in 1 with `vcpkg_build_msbuild()`.
3. We keep a very simple `CMakeLists.txt` file inside Vcpkg which handles the build. We can use `file(GLOB_RECURSE)` to grab all the sources out of the tree easily. This is the option I believe is the easiest moving forward given your response that you'd like the buildsystem for users to simply be `cl *.cpp`. CMake is more easily customized externally, so this would correctly support things such as static linking the CRT (which I believe the MSBuild will not -- we'd need to patch the MSBuild file for that).

[1] #828 
[2]
```msbuild
<Import Condition="'$(VcpkgTargetsFilePath)'!=''" Project="$(VcpkgTargetsFilePath)"/>
```

**Comment by alexhultman** [comment]
Right, I added that line: https://github.com/uWebSockets/uWebSockets/commit/6888c92691c0e8aaf65661a40c4a1f309a5d7eee

**Comment by alexhultman** [comment]
I still cannot get it to work. The only thing that I can get working is this PR.

**Comment by ras0219-msft** [comment]
Hrm, that's troublesome.

I went ahead and took a stab at the we-keep-a-copy-of-cmake approach:
https://github.com/Microsoft/vcpkg/blob/299776b5396d4f2dbdb490dca612d6bae84163de/ports/uwebsockets/CMakeLists.txt

It's the same length as the portfile itself (i.e. really short), plus it works for static linking against the CRT and potentially UWP in the future. I also did a dry run of upgrading to 0.14.0alpha5 and it compiled completely clean the first time through.

**Comment by alexhultman** [comment]
Okay that's fine, thanks

**Pull request closed without merging**
