### PR TITLE
[numcpp] Add new port

### PR DESCRIPTION
**Pull request by myd7349**
**Describe the pull request**

- What does your PR fix?
Add new port: https://github.com/dpilger26/NumCpp

- Which triplets are supported/not supported? Have you updated the CI baseline?
N/A. No.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes.

### CODE REVIEW

**Comment by NancyLi1013** [comment]
Hi @myd7349 
Thanks for this PR.

The failure on x64-linux is like his:

```
-- Installing: /mnt/vcpkg-ci/packages/numcpp_x64-linux/share/numcpp/copyright
-- Performing post-build validation
There should be no empty directories in /mnt/vcpkg-ci/packages/numcpp_x64-linux
The following empty directories were found:

    /mnt/vcpkg-ci/packages/numcpp_x64-linux/share/NumCpp

If a directory should be populated but is not, this might indicate an error in the portfile.
If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:

    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/a/dir" "${CURRENT_PACKAGES_DIR}/some/other/dir")


Found 1 error(s). Please correct the portfile:
    /agent/_work/1/s/ports/numcpp/portfile.cmake
-- Performing post-build validation done
Error: Building package numcpp:x64-linux failed with: POST_BUILD_CHECKS_FAILED
```
Could you please fix it?

**Comment by myd7349** [comment]
> 
> 
> Hi @myd7349
> Thanks for this PR.
> 
> The failure on x64-linux is like his:
> 
> ```
> -- Installing: /mnt/vcpkg-ci/packages/numcpp_x64-linux/share/numcpp/copyright
> -- Performing post-build validation
> There should be no empty directories in /mnt/vcpkg-ci/packages/numcpp_x64-linux
> The following empty directories were found:
> 
>     /mnt/vcpkg-ci/packages/numcpp_x64-linux/share/NumCpp
> 
> If a directory should be populated but is not, this might indicate an error in the portfile.
> If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:
> 
>     file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/a/dir" "${CURRENT_PACKAGES_DIR}/some/other/dir")
> 
> 
> Found 1 error(s). Please correct the portfile:
>     /agent/_work/1/s/ports/numcpp/portfile.cmake
> -- Performing post-build validation done
> Error: Building package numcpp:x64-linux failed with: POST_BUILD_CHECKS_FAILED
> ```
> 
> Could you please fix it?

Thanks. I will look into it this weekend.

**Review by NancyLi1013 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
