### PR TITLE
[vcpkg baseline][salome-configuration] passing remove from fail 

### PR DESCRIPTION
**Pull request by MonicaLiu0311**
Passing on this run https://dev.azure.com/vcpkg/public/_build/results?buildId=93404&view=results

Related PR https://github.com/microsoft/vcpkg/pull/33336.

### CODE REVIEW

**Comment by JackBoosY** [comment]
Why it failed before?

**Comment by Neumann-A** [comment]
Server was simply down.

**Comment by MonicaLiu0311** [comment]
Related PR https://github.com/microsoft/vcpkg/pull/33336.

**Comment by MonicaLiu0311** [comment]
> Why it failed before?

https://github.com/microsoft/vcpkg/pull/33336#issue-1863102573

**Pull request merged**
