### PR TITLE
Initial proposal for interface packages

### PR DESCRIPTION
**Pull request by albertziegenhagel**
As discussed in #164

### CODE REVIEW

**Comment by albertziegenhagel** [comment]
This proposal uses the proposed feature packages to implement the interface port. While this approach would have the benefit that it would be very easy to implement on top of feature packages, one could argue that this is abusing feature packages for something it is not necessarily intended for. What do you think?

**Comment by ras0219-msft** [comment]
Thanks for making this proposal!

I like `Provides:`, however I don't think we should (ab)use feature packages to list out the possible alternatives. Interfaces are certainly important enough to get whatever syntax is needed to make them easy and simple to use. I believe we can build a solid UX to make the magic sufficiently transparent 😃.

A potential design goal: enabling packages to "Provide" on top of existing packages would enable users to locally extend/enhance/replace the curated set much more easily -- for example, I could make a `boost1-64` package that `Provides: boost` to locally downgrade my package without the main, curated boost being modified at all.

Debian (of course) has an equivalent of these: Virtual Packages
https://www.debian.org/doc/debian-policy/ch-relationships.html#s-virtual
https://www.debian.org/doc/debian-policy/ch-binary.html#s-virtual-pkg

**Comment by EternalPhane** [comment]
Hi. It's been a year and half since this proposal. Any progress with it?

**Comment by dan-shaw** [comment]
I’m going to close this PR because it’s been a long time since any update has been made. If this is something you’d like to see merged and work is being done, please reopen.

**Pull request closed without merging**
