### PR TITLE
Fix [boost] MSVC 2013 v120 Build

### PR DESCRIPTION
**Pull request by ManuelKugelmann**
**Describe the pull request**

   In `boost-modular-build.cmake` only "v140" / "vc140" was expected,.
   Added handling of "v120" / "vc120"

- What does your PR fix? 
   Fixes issue `[boost] build failure with MSVC 2013 / v120` #10643

- Which triplets are supported/not supported? Have you updated the CI baseline?
   Should not affect other triplets

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

### CODE REVIEW

**Comment by ManuelKugelmann** [comment]
What is going on with the PR Test? My changes obviously only affect MSVC 2013 / v120 (and that in a positive way). Is there any way to see the result of the merge that is tested? Something must be wrong there or in the PR test ?

**Comment by ManuelKugelmann** [comment]
[Had to remove boost-python from boost CONTROLS file for a successful boost build](https://github.com/microsoft/vcpkg/issues/10643#issuecomment-607765809)

**Comment by PhoebeHui** [comment]
@ManuelKugelmann, thanks for the PR!

PR https://github.com/microsoft/vcpkg/pull/10660 should adress the CI testing issue.

**Comment by ManuelKugelmann** [comment]
Follow up: Issue #10669 and PR #10670

**Comment by JackBoosY** [comment]
Hi @ManuelKugelmann , thanks for this PR!
Could you resolve these file conflicts?

Thanks.

**Comment by ManuelKugelmann** [comment]
@JackBoosY unfortunately I do not know how to conditionally exclude python from the dependencies list in the CONTROL file - any hints? 
Or would this require deep changes in the handling of the dependencies list?

**Comment by JackBoosY** [comment]
@ManuelKugelmann See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/control-files.md#build-depends).

**Comment by ManuelKugelmann** [comment]
@JackBoosY ah, many thanks. Somehow my google-foo failed to get me there on multiple tries ...
I will look into it, but it might take me a little while.

**Comment by ras0219-msft** [comment]
Friendly ping to @ManuelKugelmann on whether you're still looking into this

**Comment by ManuelKugelmann** [comment]
@ras0219-msft Will look into it right now

**Comment by ManuelKugelmann** [comment]
The original issue does not link here: https://github.com/microsoft/vcpkg/issues/10643

**Comment by ManuelKugelmann** [comment]
@PhoebeHui @ras0219 Done?

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
