### PR TITLE
[tools]Add python64 bit.

### PR DESCRIPTION
**Pull request by JackBoosY**
1. Add 64 bit python2/python3.
2. Choose the different python version depending on the architecture.

Related: #7411.

### CODE REVIEW

**Comment by Rastaban** [comment]
Did a full rebuild https://dev.azure.com/vcpkg/public/_build/results?buildId=7197

**Comment by JackBoosY** [comment]
```
  File does not have expected hash:

          File path: [ /home/vcpkg/myagent/_work/4/s/downloads/tools/python/bin/get-pip.py ]
      Expected hash: [ 1436215d2bc45a8019503aaf6c0e5f7da142108dee0fa2db282e22670eca84beff487ec45f1e6b8968c481f7009afb211a76ac93b637b48ba83f099831db33ff ]
        Actual hash: [ 99520d223819708b8f6e4b839d1fa215e4e8adc7fcd0db6c25a0399cf2fa10034b35673cf450609303646d12497f301ef53b7e7cc65c78e7bce4af0c673555ad ]

  Please delete the file and retry if this file should be downloaded again.
```
I can't reproduce this issue on my linux VM.

**Comment by Rastaban** [comment]
Before vcpkg downloads a file it will check to see if a file with the same name already exists.  If the file name already exists then it will assume it was cached and compare the hash and will fail.  The way to fix this is to change the name of the downloaded file to have a version number in it.

**Comment by Rastaban** [comment]
Started a new full rebuild test: https://dev.azure.com/vcpkg/public/_build/results?buildId=8835

**Comment by JackBoosY** [comment]
I can't reproduce these port build failures:
- libjpeg-turbo:x86-windows
- string-theory:x86-windows


duckx build failed due to files conflict with port libzip and port pugixml.

**Comment by JackBoosY** [comment]
Since this branch was lost, create a new PR #7964 to add this feature.

**Pull request closed without merging**
