### PR TITLE
[qt5-activeqt, qt5-declarative] Skip activeqt in CI.

### PR DESCRIPTION
**Pull request by BillyONeal**
See https://github.com/microsoft/vcpkg/issues/19922

### CODE REVIEW

**Comment by cenit** [comment]
you simplified CI too much. See ports not tested anymore now due to this skip --> cascade failures!

**Comment by dg0yt** [comment]
`vcpkg-ci-opencv`, `vcpkg-ci-paraview` were building in AZP microsoft.vcpkg.ci on Aug 31, but cascade on Sep 3.
Perhaps any cascades reaching `vcpkg-ci-*` test port should be turned into hard errors?

**Comment by BillyONeal** [comment]
To be clear, those were already cascaded failures before this change. The options were skip this and be able to make any progress or block all port updates until qt5 gets fixed, and the latter is unreasonable.

**Comment by BillyONeal** [comment]
> Perhaps any cascades reaching `vcpkg-ci-*` test port should be turned into hard errors?

That wouldn't have changed anything as we would have been forced to skip them too.

**Comment by dg0yt** [comment]
> > Perhaps any cascades reaching `vcpkg-ci-*` test port should be turned into hard errors?
> 
> That wouldn't have changed anything as we would have been forced to skip them too.

A) It might help notice the underlying issue earlier.
B) It might create a different awareness of side effects and follow-up task when accepting a "hotfix".

**Comment by cenit** [comment]
> To be clear, those were already cascaded failures before this change. The options were skip this and be able to make any progress or block all port updates until qt5 gets fixed, and the latter is unreasonable.

i don’t think so.
qt5-tools got skipped by this PR and that triggered the problem. 

in my PR about protobuf merged not a long before this one, everything was still checked and verified

**Comment by BillyONeal** [comment]
> qt5-tools got skipped by this PR and that triggered the problem.
> 
> in my PR about protobuf merged not a long before this one, everything was still checked and verified

Before, qt5-tools was skipped because qt5-activeqt was broken. After, qt5-tools is skipped because qt5-active is skipped.

**Comment by cenit** [comment]
no

https://dev.azure.com/vcpkg/public/_build/results?buildId=58821&view=logs&j=c7e67a25-2047-5d01-7913-57de0573f534&t=0e07d234-e12f-5893-a7f1-2767a24f64ae

this is last ci run before this PR and vcpkg-ci-opencv was tested

**Comment by dg0yt** [comment]
> this is last ci run before this PR and vcpkg-ci-opencv was tested

That's the one from Sep 1 I'm referring to in https://github.com/microsoft/vcpkg/pull/19945#issuecomment-916241522.

**Comment by BillyONeal** [comment]
>this is last ci run before this PR and vcpkg-ci-opencv was tested

That's because ci doesn't use the binary cache, and and so did not discover the way in which qt is broken. All PR builds, in contrast, were broken. We're discussing what we can do over on the other PR where you tagged us all.

**Comment by cenit** [comment]
i don't see anything in the PR mentioned.
But again, sorry for insisting, but in https://github.com/microsoft/vcpkg/commit/09019cbc9abcb728217c4c99625932defe1b781c tested in PR #19770 and merged one day after yours but stale for 7 days everything was fine...

**Comment by Neumann-A** [comment]
hm qt5-activeqt is dependent on qt5-declarative. As such the script should have scanned the installed tree dir for already available dlls and not tried to reinstall the same files again. I smell path shenanigans which broke the script.

**Comment by Neumann-A** [comment]
related #11045

**Comment by BillyONeal** [comment]
> i don't see anything in the PR mentioned.
> But again, sorry for insisting, but in [09019cb](https://github.com/microsoft/vcpkg/commit/09019cbc9abcb728217c4c99625932defe1b781c) tested in PR #19770 and merged one day after yours but stale for 7 days everything was fine...

That PR ran PR validation on 2021-08-27. PR builds broke ~the night before this PR, so 2021-09-02 or so. If we had rerun PR build on that PR it would not have been fine.

**Comment by Neumann-A** [comment]
@BillyONeal #20083 seems to run through without any problems in qt5-declarative and qt5-activeqt. I don't know what broke CI considering that it worked without issues since #11045. So the reason why there were conflicting files is still a mystery.

**Comment by BillyONeal** [comment]
@Neumann-A If there is any reading and deciding not to duplicately deploy to the install directory, as enumerated before, that's broken because it makes installation path dependent, breaking both uninstall and binary caching.

**Comment by wrobelda** [comment]
FYI, this effectively disabled CI on Windows for all `kf5` ports, which depend on `qt5-tools`

**Comment by Neumann-A** [comment]
> @Neumann-A If there is any reading and deciding not to duplicately deploy to the install directory, as enumerated before, that's broken because it makes installation path dependent, breaking both uninstall and binary caching.

The problem is that qt5-declarative should have been the owner of these files and not qt5-activeqt. The scripts should have deleted the additional files. Basically the duplication should habe never happened because qt5-declarative is always build/installed before qt5-activeqt because it declares a dep on qt5-declarative. The question thus remains: what broke the scripts for the detection of the already installed files?

**Comment by cenit** [comment]
> FYI, this effectively disabled CI on Windows for all kf5 ports, due to their dependency on qt5-tools

yeah, that's the problem. A quick hotfix just disabled a lot of ports in CI and this went totally unnoticed to the authors due to how the system works. If not triggered by me tagging everyone in #20074 i have the impression the issue was not even tracked anywhere...

**Comment by wrobelda** [comment]
> > FYI, this effectively disabled CI on Windows for all kf5 ports, due to their dependency on qt5-tools
> 
> yeah, that's the problem. A quick hotfix just disabled a lot of ports in CI and this went totally unnoticed to the authors due to how the system works. 

I have previously complained about it, but the issue was closed without being properly addressed: https://github.com/microsoft/vcpkg/issues/13533

In short, any PR of which the CI build is being skipped due to "cascade" status should be marked as failed or inconclusive. Right now we're unknowingly getting the false positives in such situations.

**Pull request merged**
