### PR TITLE
[zfp] Fix feature utility

### PR DESCRIPTION
**Pull request by autoantwort**

### CODE REVIEW

**Comment by jimwang118** [comment]
Look at the name of the runnable generated by the upstream code has not changed. This PR is unnecessary.
```
\utils\CMakeLists.txt
add_executable(zfpcmd zfp.c)
```

**Comment by autoantwort** [comment]
image

**Comment by autoantwort** [comment]
> Look at the name of the runnable generated by the upstream code has not changed. This PR is unnecessary.
> 
> ```
> \utils\CMakeLists.txt
> add_executable(zfpcmd zfp.c)
> ```

And if we further look at the code we see
```cmake
set_property(TARGET zfpcmd PROPERTY OUTPUT_NAME zfp)
```

**Comment by jimwang118** [comment]
I tested the following error.
```
target_link_libraries(testzfd PRIVATE zfp::cfp zfp::zfp)
Error		CMake Error at testzfd/CMakeLists.txt:8 (target_link_libraries):
  Target "testzfd" links to:
    zfp::cfp
  but the target was not found.  Possible reasons include:
    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.		E:\test\testzfd\testzfd/CMakeLists.txt	8	
```

**Comment by autoantwort** [comment]
Why `zfp::cfp`?

**Comment by jimwang118** [comment]
> Why `zfp::cfp`?

When calling `zfp::cfp` with `find_package()`, `cfp.lib` was not found. This calling method is in your usage.

**Comment by autoantwort** [comment]
The usage is autogenerated and not touched by this PR. This was probably a problem beforehand and is not related to this PR and should be fixed by another PR.

**Comment by dg0yt** [comment]
cfp or zfp?

**Review by jimwang118 — APPROVED** [review]

**Pull request merged**
