### PR TITLE
[speedb] new port

### LINKED ISSUE #33738: [New Port Request] Speedb
### Library name

Speedb

### Library description

A first-of-its-kind, community-led key-value storage engine, designed to support modern data sets. Speedb is a 100% RocksDB compatible, drop-in library, focused on high performance, optimized for modern storage hardware and scale, on-premise and in the cloud.

### Source repository URL

https://github.com/speedb-io/speedb

### Project homepage (if different from the source repository)

https://www.speedb.io

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

_No response_

### PR DESCRIPTION
**Pull request by justend29**
Fixes #33738

Upstream GitHub repo for source code, license info, releases, etc: [speedb repo](https://github.com/speedb-io/speedb).
Since Speedb is based of RocksDB, there was enough overlap to stem from the RocksDB port with minimal changes.
The port's patches are equivalent to those from RocksDB but reapplied to the Speedb release offered in this port such that they could apply nicely.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
   - [speedb.io](https://www.speedb.io/)
- [X] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [X] The versioning scheme in `vcpkg.json` matches what upstream says.
    - `speedb/v2.7.0` [release](https://github.com/speedb-io/speedb/releases/tag/speedb%2Fv2.7.0). 
- [X] The license declaration in `vcpkg.json` matches what upstream says.
- [X] The installed as the "copyright" file matches what upstream says.
- [X] The source code of the component installed comes from an authoritative source.
- [X] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
   - tested with a minimal example and the package name & targets are correctly named.  
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is in the new port's versions file.
- [ ] ~Only one version is added to each modified port's versions file.~

### CODE REVIEW

**Comment by FrankXie05** [comment]
```
speedb provides CMake targets:

  # this is heuristically generated, and may not be correct
  find_package(Speedb CONFIG REQUIRED)
  target_link_libraries(main PRIVATE Speedb::speedb Speedb::speedb-shared)

speedb provides pkg-config modules:

    # An embeddable persistent key-value store for fast storage
    speedb
```
@justend29 Now that the pc file is provided, we can consider adding `pkg-config`, or delete it directly.

**Comment by dg0yt** [comment]
> speedb is based of RocksDB, there was enough overlap to stem from the RocksDB port with minimal changes.

Actually there is too much overlap: It installs file which are already owned by port rocksdb, e.g.
~~~
speedb:x64-linux:/include/rocksdb/cache.h
~~~
vs.
~~~
rocksdb:x64-linux:/include/rocksdb/cache.h
~~~
This doesn't work for users which happen to have both ports installed, and this would immediately break vcpkg daily CI.
I didn't check for duplicate symbols which in the libs which would at least break msbuild autolinking.

**Comment by justend29** [comment]
@dg0yt Oh, that's a great point. I didn't catch that speedb provides *literally* the same headers when reviewing that point in the maintainer's guide.

I'm not dependent on this port, so I'm fine with closing, but in an effort to provide this for other users, what options are there? I wouldn't want to nest or rename the headers in the vcpkg port, as that would break compatibility with external installations, but that seems like the only option.

**Comment by dg0yt** [comment]
I don't know if there is a satisfying answer.

> Speedb is a 100% RocksDB compatible, drop-in library,

So its an alternative, and vcpkg is weak at handling alternatives. 
Ask maintainers for advice. (I'm a community member.)

**Comment by justend29** [comment]
@dg0yt Thanks for all the contributions to the community.

@FrankXie05, do you have any suggestions on handling the alternative? We could consider speedb a "backend" to the rocksdb port, maybe.

**Comment by JavierMatosD** [comment]
Hi @justend29, unfortunately, we can't accept this port on account that it's an alternative to `RocksDB`. We are interested in figuring out a solution to "alternatives" but we currently don't have one. 

> I'm not dependent on this port, so I'm fine with closing, but in an effort to provide this for other users, what options are there? 

While we can't add it to our registry, you can always provide a custom registry for your users. https://learn.microsoft.com/en-us/vcpkg/maintainers/registries

**Comment by justend29** [comment]
@JavierMatosD sounds great. Overlay ports and custom registries rock. Maybe once alternatives are possible upstream, this port can be revisited.
Should the original issue be closed as well?

**Pull request closed without merging**
