### PR TITLE
[zlib]Add debug postfix("d") on unix.

### PR DESCRIPTION
**Pull request by JackBoosY**
Related: #6644.

### CODE REVIEW

**Review by Neumann-A — CHANGES_REQUESTED** [review]
Is it not just possible to add CMAKE_DEBUG_POSTFIX to the configure step within the portfile?

**Comment by JackBoosY** [comment]
@Neumann-A  no, it's not working.

**Comment by Neumann-A** [comment]
Hmm ok. Then i would just ask you to leave a comment behind the patch saying that cmake_debug_postfix did not work. Thats stops people from wondering why it was not used and they wont even try to refactor the code

**Comment by JackBoosY** [comment]
``` 
Processing x64-linux                      725 vs 750
     glib                          **regression**                Fail vs Pass
     itk                           **regression**                Fail vs Pass
     vxl                           **regression**                Fail vs Pass
 Processing x64-osx                        692 vs 695
     highfive                      **regression**                Fail vs Pass
     itk                           **regression**                Fail vs Pass
     ptex                          **regression**                Fail vs Pass
     vxl                           **regression**                Fail vs Pass
 Processing x86-windows                    935 vs 932
     libnice                       **regression**                Fail vs Pass
```

Both x64-linux and x86-windows have been tested successfully, but I can't test on x64-osx.

**Comment by Neumann-A** [comment]
I wonder why there is no regression in qt.... 

`"QMAKE_LIBS_PRIVATE+=${CURRENT_INSTALLED_DIR}/debug/lib/libz.a"
"ZLIB_LIBS=${CURRENT_INSTALLED_DIR}/debug/lib/libz.a"`

**Comment by Neumann-A** [comment]
@JackBoosY 
> Is it not just possible to add CMAKE_DEBUG_POSTFIX to the configure step within the portfile?
>@Neumann-A no, it's not working.

So I test this myself because I found it strange. So I did that:
```
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS
        -DSKIP_INSTALL_FILES=ON
        -DSKIP_BUILD_EXAMPLES=ON
        -DCMAKE_DEBUG_POSTFIX=d
    OPTIONS_DEBUG
        -DSKIP_INSTALL_HEADERS=ON
)
```
and it did what I expected -> installing lib/libz.a and debug/lib/libzd.a. (Ubuntu/WSL) . So how was that not working?

**Comment by JackBoosY** [comment]
@Neumann-A sorry, I forgot that setting the cmake option directly in portfile.cmake doesn't work. we have to import this option using vcpkg_configure_cmake.

**Comment by JackBoosY** [comment]
@Neumann-A glib can't be built successfully, here is the error message:
```
configure: error: *** Working zlib library and headers not found ***
CMake Error at CMakeLists.txt:107 (message):
  Configure failed.
```

In glib **CMakeLists.txt:107**(_ports/glib/CMakeLists.txt_):
```
        execute_process(
            COMMAND "${CMAKE_SOURCE_DIR}/configure"
                --disable-libelf
                --disable-libmount
                "CPPFLAGS=${CXXFLAGS}"
                "CFLAGS=${CFLAGS}"
                "LDFLAGS=${LDFLAGS}"
            WORKING_DIRECTORY ${CMAKE_BINARY_DIR}/config
            RESULT_VARIABLE res
        )
```

In _source/configure_(line 7775):
```
if test $pkg_failed = yes; then
   	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
$as_echo "no" >&6; }

if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
        _pkg_short_errors_supported=yes
else
        _pkg_short_errors_supported=no
fi
        if test $_pkg_short_errors_supported = yes; then
	        ZLIB_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors --cflags --libs "zlib" 2>&1`
        else
	        ZLIB_PKG_ERRORS=`$PKG_CONFIG --print-errors --cflags --libs "zlib" 2>&1`
        fi
	# Put the nasty error message in config.log where it belongs
	echo "$ZLIB_PKG_ERRORS" >&5

	found_zlib=no
elif test $pkg_failed = untried; then
     	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
$as_echo "no" >&6; }
	found_zlib=no
else
	ZLIB_CFLAGS=$pkg_cv_ZLIB_CFLAGS
	ZLIB_LIBS=$pkg_cv_ZLIB_LIBS
        { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
$as_echo "yes" >&6; }
	found_zlib=yes
fi
```

Any good ideas?

**Comment by Neumann-A** [comment]
Make the ZLIB library name a configure variable via a patch to the source tree and add it to the configure command?

**Comment by JackBoosY** [comment]
@Neumann-A 
```
        if (CMAKE_BUILD_TYPE STREQUAL "Debug")
            set(ZLIB_LIB_NAME "libzd")
        else()
            set(ZLIB_LIB_NAME "libz")
        endif()
        execute_process(
            COMMAND "${CMAKE_SOURCE_DIR}/configure"
                --disable-libelf
                --disable-libmount
                "CPPFLAGS=${CXXFLAGS}"
                "CFLAGS=${CFLAGS}"
                "LDFLAGS=${LDFLAGS}"
                "ZLIB_LIBS=${ZLIB_LIB_NAME}"
            WORKING_DIRECTORY ${CMAKE_BINARY_DIR}/config
            RESULT_VARIABLE res
        )
```

Not working.

**Comment by Neumann-A** [comment]
yeah because the current variable is not meant for that:
`ZLIB_LIBS   linker flags for ZLIB, overriding pkg-config`
you have to define a new one and patch all ussages of `"zlib"` and `\"zlib\"` to use the new defined variable

**Comment by JackBoosY** [comment]
Due to my branch has been deleted, create new PR #6883 to fix this issue.

**Pull request closed without merging**
