### PR TITLE
[atk] Allow building on ARM

### PR DESCRIPTION
**Pull request by ice0**
Tested on Windows 11 ARM / macOS ARM

**Describe the pull request**
Allow building on ARM arch

- #### What does your PR fix?
  Fixes build on Windows/macOS arm

### CODE REVIEW

**Comment by Cheney-W** [comment]
https://github.com/microsoft/contributorlicenseagreement#accepting

**Comment by ice0** [comment]
> https://github.com/microsoft/contributorlicenseagreement#accepting

It shows 404.

image

**Comment by Cheney-W** [comment]
To accept the agreement, the user can issue one of the following two commands as a comment on the pull request.

If you are contributing on behalf of yourself:
@bot agree

If you are contributing on behalf of a company:
@bot agree company="your company"

**Comment by ice0** [comment]
@bot agree

**Comment by ice0** [comment]
@Cheney-W Done!

**Comment by Cheney-W** [comment]
Could you please modify the `portfile.cmake` file to to trigger CI test for this port? You can simply add a blank line at the end of the file.
After above, don't forget run `./vcpkg x-add-version atk --overwrite-version`.

**Comment by ice0** [comment]
@Cheney-W Done.

**Comment by BillyONeal** [comment]
Thanks!

**Pull request merged**
