### PR TITLE
[openblas] Update OpenBLAS port for Windows

### PR DESCRIPTION
**Pull request by AlessioZanga**
**Describe the pull request**

- #### What does your PR fix?
  Fixes the `OpenBLAS` port by adding the necessary `gfortran` compiler to build `LAPACK` correctly on Windows.
  
  This is still a draft since it also required to update `OpenBLAS`. In fact, while the associated pull request has been accepted (see xianyi/OpenBLAS#3561), it is still on the development branch. I will update the reference commit and convert the draft into a pull request once a new release of `OpenBLAS` will be delivered.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  Supported triplets: `x64-windows`, `x64-windows-static` and `x86-windows`. No, it is not needed.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes, I've read it and checked against the specific section about updating the portfile.

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  I am still working on this PR.

### CODE REVIEW

**Comment by JonLiu1993** [comment]
@AlessioZanga , Are you still continuing this PR?

**Comment by AlessioZanga** [comment]
@JonLiu1993 , actually, I'm currently waiting for the next OpenBLAS release that will make the changes production-ready. Then, the only thing remaining is to update the SHA512 contained in the `portfile.cmake`.

**Comment by JonLiu1993** [comment]
> @JonLiu1993 I've updated this patch with respect to the master branch. Now that OpenBLAS 0.3.21 has been added to `vcpkg`, I can continue with the work on this pull request.

@AlessioZanga, Thanks for your contribution, if this pr is ready for review, please let me know.

**Comment by JonLiu1993** [comment]
Pinging @AlessioZanga for response. Is work still being done for this PR?

**Comment by AlessioZanga** [comment]
I'm trying to understand why some build fails in the pipeline, but I'm new to the `vcpkg` environment.

**Comment by JonLiu1993** [comment]
> I'm trying to understand why some build fails in the pipeline, but I'm new to the `vcpkg` environment.

Please ping me if you need any help.

**Comment by JonLiu1993** [comment]
Pinging @AlessioZanga for response. Is work still being done for this PR?

**Comment by JonLiu1993** [comment]
Closing this PR since it seems that no progress is being made. Please ping us to reopen if work is still being done.

**Pull request closed without merging**
