### PR TITLE
[minizip] Enable uwp

### PR DESCRIPTION
**Pull request by dg0yt**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by dg0yt** [comment]
gz-math7:x64-windows: baseline regression, needs #31277.

**Comment by Adela0814** [comment]
Note: I will be converting your PR to draft status. Please activate it once the CI issue is resolved.

**Comment by dg0yt** [comment]
> Note: I will be converting your PR to draft status. Please activate it once the CI issue is resolved.

The PR is in a state where everything should be handled by maintainers.

**Comment by dg0yt** [comment]
Please re-run osx.

**Review by Adela0814 — APPROVED** [review]

**Pull request merged**
