### PR TITLE
[nettle] Update to 3.8.1

### PR DESCRIPTION
**Pull request by dg0yt**
Updates nettle to 3.8.1.
Adds cmake to code to help with regenerating the list of exported symbols. CC @Neumann-A 
(This code was verified to generate the same symbols for 3.7.3. Only the order differs.)

No switch clang for ASM in this PR. Reason: This needs more work, cf. https://dev.azure.com/vcpkg/public/_build/results?buildId=86589.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by dg0yt** [comment]
This needs an update to the def files.
x64-windows (blocking all windows triplets in CI, due to nettle host dependency):
~~~
nettle.def : error LNK2001: unresolved external symbol _nettle_aes_decrypt_aesni
nettle.def : error LNK2001: unresolved external symbol _nettle_aes_decrypt_x86_64
nettle.def : error LNK2001: unresolved external symbol _nettle_aes_encrypt_aesni
nettle.def : error LNK2001: unresolved external symbol _nettle_aes_encrypt_x86_64
nettle.def : error LNK2001: unresolved external symbol _nettle_gcm_hash8
nettle.lib : fatal error LNK1120: 5 unresolved externals
~~~

**Comment by dg0yt** [comment]
@MonicaLiu0311 https://github.com/microsoft/vcpkg/labels/depends%3Adifferent-pr is wrong.

**Review by MonicaLiu0311 — DISMISSED** [review]

**Comment by Neumann-A** [comment]
> Why maintain MSVC DLL patches if nobody notices the absence of DLLs in bin?

cc @BillyONeal: isn't this something the tool could easily detect ?

**Comment by dg0yt** [comment]
> > Why maintain MSVC DLL patches if nobody notices the absence of DLLs in bin?
> 
> cc @BillyONeal: isn't this something the tool could easily detect ?

Minus `*-tool*` ports and case sensitivity issues, this is a quick scan result on `VCPKG_Database` from CI:
~~~
cutelyst2:x64-windows:/tools/cutelyst2/Cutelyst2Qt5.dll
cutelyst2:x64-windows:/tools/cutelyst2/Cutelyst2Qt5Wsgi.dll
gettext:x64-windows:/tools/gettext/bin/gettextlib-0-21-1.dll
gettext:x64-windows:/tools/gettext/bin/gettextsrc-0-21-1.dll
gettext:x64-windows:/tools/gettext/bin/textstyle-0.dll
llvm:x64-windows:/tools/llvm/lib/clang/14.0.6/lib/windows/clang_rt.asan_dynamic-x86_64.dll
marble:x64-windows:/tools/marble/plugins/AnnotatePlugin.dll
marble:x64-windows:/tools/marble/plugins/AtmospherePlugin.dll
marble:x64-windows:/tools/marble/plugins/CachePlugin.dll
marble:x64-windows:/tools/marble/plugins/CompassFloatItem.dll
marble:x64-windows:/tools/marble/plugins/CrosshairsPlugin.dll
marble:x64-windows:/tools/marble/plugins/CycleStreetsPlugin.dll
marble:x64-windows:/tools/marble/plugins/EarthquakePlugin.dll
marble:x64-windows:/tools/marble/plugins/EclipsesPlugin.dll
marble:x64-windows:/tools/marble/plugins/ElevationProfileFloatItem.dll
marble:x64-windows:/tools/marble/plugins/ElevationProfileMarker.dll
marble:x64-windows:/tools/marble/plugins/FlightGearPositionProviderPlugin.dll
marble:x64-windows:/tools/marble/plugins/FoursquarePlugin.dll
marble:x64-windows:/tools/marble/plugins/GeoUriPlugin.dll
marble:x64-windows:/tools/marble/plugins/GosmoreReverseGeocodingPlugin.dll
marble:x64-windows:/tools/marble/plugins/GosmoreRoutingPlugin.dll
marble:x64-windows:/tools/marble/plugins/GpsInfo.dll
marble:x64-windows:/tools/marble/plugins/GpsbabelPlugin.dll
marble:x64-windows:/tools/marble/plugins/GpxPlugin.dll
marble:x64-windows:/tools/marble/plugins/GraticulePlugin.dll
marble:x64-windows:/tools/marble/plugins/HostipPlugin.dll
marble:x64-windows:/tools/marble/plugins/JsonPlugin.dll
marble:x64-windows:/tools/marble/plugins/KmlPlugin.dll
marble:x64-windows:/tools/marble/plugins/LatLonEditPlugin.dll
marble:x64-windows:/tools/marble/plugins/LatLonPlugin.dll
marble:x64-windows:/tools/marble/plugins/License.dll
marble:x64-windows:/tools/marble/plugins/LocalDatabasePlugin.dll
marble:x64-windows:/tools/marble/plugins/LocalOsmSearchPlugin.dll
marble:x64-windows:/tools/marble/plugins/LogPlugin.dll
marble:x64-windows:/tools/marble/plugins/MapQuestPlugin.dll
marble:x64-windows:/tools/marble/plugins/MapScaleFloatItem.dll
marble:x64-windows:/tools/marble/plugins/MarbleNavigatorPlugin.dll
marble:x64-windows:/tools/marble/plugins/MarbleWidgetPlugin.dll
marble:x64-windows:/tools/marble/plugins/MeasureTool.dll
marble:x64-windows:/tools/marble/plugins/MonavPlugin.dll
marble:x64-windows:/tools/marble/plugins/NavigationFloatItem.dll
marble:x64-windows:/tools/marble/plugins/NominatimReverseGeocodingPlugin.dll
marble:x64-windows:/tools/marble/plugins/NominatimSearchPlugin.dll
marble:x64-windows:/tools/marble/plugins/NotesPlugin.dll
marble:x64-windows:/tools/marble/plugins/OSRMPlugin.dll
marble:x64-windows:/tools/marble/plugins/OpenLocationCodeSearchPlugin.dll
marble:x64-windows:/tools/marble/plugins/OpenRouteServicePlugin.dll
marble:x64-windows:/tools/marble/plugins/OsmPlugin.dll
marble:x64-windows:/tools/marble/plugins/OverviewMap.dll
marble:x64-windows:/tools/marble/plugins/Pn2Plugin.dll
marble:x64-windows:/tools/marble/plugins/PntPlugin.dll
marble:x64-windows:/tools/marble/plugins/PositionMarker.dll
marble:x64-windows:/tools/marble/plugins/PostalCode.dll
marble:x64-windows:/tools/marble/plugins/ProgressFloatItem.dll
marble:x64-windows:/tools/marble/plugins/RoutingPlugin.dll
marble:x64-windows:/tools/marble/plugins/RoutinoPlugin.dll
marble:x64-windows:/tools/marble/plugins/SatellitesPlugin.dll
marble:x64-windows:/tools/marble/plugins/Speedometer.dll
marble:x64-windows:/tools/marble/plugins/StarsPlugin.dll
marble:x64-windows:/tools/marble/plugins/SunPlugin.dll
marble:x64-windows:/tools/marble/plugins/YoursPlugin.dll
nettle:x64-windows:/tools/nettle/bin/hogweed-6.dll
nettle:x64-windows:/tools/nettle/bin/nettle-8.dll
nettle:x64-windows:/tools/nettle/debug/bin/hogweed-6.dll
nettle:x64-windows:/tools/nettle/debug/bin/nettle-8.dll
openni2:x64-windows:/tools/openni2/glut64.dll
~~~

Generator:
~~~cmake
set(DATABASE "../VCPKGDatabase-x64-windows.txt" CACHE FILEPATH "CI file list")
file(STRINGS "${DATABASE}" all_dlls REGEX "[.]dll$")
file(STRINGS "${DATABASE}" tool_dlls REGEX ":/tools/.*[.]dll$")
list(REMOVE_ITEM all_dlls ${tool_dlls})
list(FILTER tool_dlls EXCLUDE REGEX "^[^:]*-tool")
list(TRANSFORM all_dlls REPLACE "^.*/(.*)\$" "/\\1\$")
list(TRANSFORM all_dlls REPLACE "([+.])" "[\\1]")
list(REMOVE_DUPLICATES all_dlls)
foreach(pattern IN LISTS all_dlls)
    string(TOUPPER "${pattern}" all_upper)
    string(REPLACE "[.]DLL" "[.]dll" stem_upper "${all_upper}")
    list(FILTER tool_dlls EXCLUDE REGEX "${pattern}|${all_upper}|${stem_upper}")
endforeach()
list(JOIN tool_dlls "\n" only_in_tools)
message("The following DLLs exist only `/tools:\n${only_in_tools}\n")
~~~

**Comment by dg0yt** [comment]
Please repair the broken outdated "change requested" review from (now-gone?) GH actions.

**Comment by BillyONeal** [comment]
> Please repair the broken outdated "change requested" review from (now-gone?) GH actions.

Sorry about that, if you see any more please tag me directly with a message like "broken GH actions bot" and I'll dismiss them. Unfortunately the security change that made it so our bot could no longer approve PRs broke this (which is why we no longer have the bot try to approve or deny PRs, and only make review comments)

**Comment by dg0yt** [comment]
@BillyONeal I'm afraid this PR is still blocked by the broken GH actions bot.

**Comment by BillyONeal** [comment]
> @BillyONeal I'm afraid this PR is still blocked by the broken GH actions bot.

Does not look blocked to me? The bot is a "pending" reviewer but that doesn't mean anything. Only a "Request Changes" would block merge.

**Pull request merged**
