### PR TITLE
[antlr4] update to 4.9.1

### PR DESCRIPTION
**Pull request by NickStrupat**
**Describe the pull request**

- What does your PR fix?

> Updates the port to version 4.9.1.

- Which triplets are supported/not supported? Have you updated the CI baseline?

> This change contains nothing related to triplets or CI.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

> Yes.

### CODE REVIEW

**Comment by JonLiu1993** [comment]
Hi @NickStrupat ，Thank you for your pr, I helped you modify the problem in your portifile.cmake, and updated the version, but CI showed that could not find git for clone of utfcpp, I attached the log, please take a look:
[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/6033805/config-x86-windows-out.log)

**Comment by NickStrupat** [comment]
@JonLiu1993, thanks for your help. I noticed those CI errors as well. I figured it was an issue with CI, but mostly because I have no clues as to what about this port could be causing those issues.

Have you seen this kind of error before?

**Comment by NickStrupat** [comment]
@JonLiu1993 I'm not sure what's going on here...

```
CMake Error at D:/downloads/tools/cmake-3.19.2-windows/cmake-3.19.2-win32-x86/share/cmake-3.19/Modules/ExternalProject.cmake:2542 (message):
  error: could not find git for clone of utfcpp```

It seems that something is broken on Azure? Do I need to introduce some change to reflect some change in git's availability on the build agents?

**Comment by NickStrupat** [comment]
@capra314cabra I saw your previous ANTLR upgrade PR. If you have any insight here it would be greatly appreciated.

**Comment by capra314cabra** [comment]
> @capra314cabra I saw your previous ANTLR upgrade PR. If you have any insight here it would be greatly appreciated.

It seems to occur here. All I can say is that investigating this command may solve this problem.
https://github.com/antlr/antlr4/blob/5c2b686f95e1a42f302fefd99271863bf25b2e06/runtime/Cpp/runtime/CMakeLists.txt#L6-L14

**Comment by NickStrupat** [comment]
@JonLiu1993 I had some free time and finally figured it out.

**Comment by JonLiu1993** [comment]
@NickStrupat ，Thanks for your contribution

**Review by JonLiu1993 — APPROVED** [review]

**Review by ras0219-msft — APPROVED** [review]
Thanks for the PR!

**Comment by NickStrupat** [comment]
@JonLiu1993, Any idea why the Windows tests are now failing due to `osgearth`?

**Comment by JonLiu1993** [comment]
> @JonLiu1993, Any idea why the Windows tests are now failing due to `osgearth`?

This is caused by other ports on ci and has been fixed.

**Comment by JonLiu1993** [comment]
@vicroms ,Please merge this pr.

**Pull request merged**
