### PR TITLE
[llvm] improve cross compilation

### PR DESCRIPTION
**Pull request by abique**
This pull request address missing options required when cross compiling.

### CODE REVIEW

**Comment by yurybura** [comment]
Have you ever tried `arm64-windows`? It doesn't build with error:

```
[250/3764] C:\PROGRA~2\MIB055~1\2019\COMMUN~1\VC\Tools\MSVC\1429~1.300\bin\Hostx64\arm64\cl.exe   /TP -DGTEST_HAS_RTTI=0 -DUNICODE -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -D_UNICODE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Ilib\MC -ID:\libs\vcpkg\buildtrees\llvm\src\org-12.0.0-511e760473.clean\llvm\lib\MC -Iinclude -ID:\libs\vcpkg\buildtrees\llvm\src\org-12.0.0-511e760473.clean\llvm\include -ID:\libs\vcpkg\installed\arm64-windows\include /nologo /DWIN32 /D_WINDOWS /utf-8   /MP  /Zc:inline /Zc:__cplusplus /Zc:strictStrings /Oi /Zc:rvalueCast /bigobj /W4 -wd4141 -wd4146 -wd4244 -wd4267 -wd4291 -wd4351 -wd4456 -wd4457 -wd4458 -wd4459 -wd4503 -wd4624 -wd4722 -wd4100 -wd4127 -wd4512 -wd4505 -wd4610 -wd4510 -wd4702 -wd4245 -wd4706 -wd4310 -wd4701 -wd4703 -wd4389 -wd4611 -wd4805 -wd4204 -wd4577 -wd4091 -wd4592 -wd4319 -wd4709 -wd4324 -w14062 -we4238 /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /EHs-c- /GR- -std:c++14 /showIncludes /Folib\MC\CMakeFiles\LLVMMC.dir\MCAsmInfo.cpp.obj /Fdlib\MC\CMakeFiles\LLVMMC.dir\LLVMMC.pdb /FS -c D:\libs\vcpkg\buildtrees\llvm\src\org-12.0.0-511e760473.clean\llvm\lib\MC\MCAsmInfo.cpp
[251/3764] cmd.exe /C "cd /D D:\libs\vcpkg\buildtrees\llvm\arm64-windows-dbg && D:\libs\vcpkg\buildtrees\llvm\arm64-windows-dbg\bin\llvm-tblgen.exe -gen-intrinsic-enums -I D:/libs/vcpkg/buildtrees/llvm/src/org-12.0.0-511e760473.clean/llvm/include/llvm/IR -ID:/libs/vcpkg/buildtrees/llvm/arm64-windows-dbg/include -ID:/libs/vcpkg/buildtrees/llvm/src/org-12.0.0-511e760473.clean/llvm/include --long-string-literals=0 D:/libs/vcpkg/buildtrees/llvm/src/org-12.0.0-511e760473.clean/llvm/include/llvm/IR/Intrinsics.td --write-if-changed -o include/llvm/IR/IntrinsicEnums.inc -d include/llvm/IR/IntrinsicEnums.inc.d"
FAILED: include/llvm/IR/IntrinsicEnums.inc 
cmd.exe /C "cd /D D:\libs\vcpkg\buildtrees\llvm\arm64-windows-dbg && D:\libs\vcpkg\buildtrees\llvm\arm64-windows-dbg\bin\llvm-tblgen.exe -gen-intrinsic-enums -I D:/libs/vcpkg/buildtrees/llvm/src/org-12.0.0-511e760473.clean/llvm/include/llvm/IR -ID:/libs/vcpkg/buildtrees/llvm/arm64-windows-dbg/include -ID:/libs/vcpkg/buildtrees/llvm/src/org-12.0.0-511e760473.clean/llvm/include --long-string-literals=0 D:/libs/vcpkg/buildtrees/llvm/src/org-12.0.0-511e760473.clean/llvm/include/llvm/IR/Intrinsics.td --write-if-changed -o include/llvm/IR/IntrinsicEnums.inc -d include/llvm/IR/IntrinsicEnums.inc.d"
This version of D:\libs\vcpkg\buildtrees\llvm\arm64-windows-dbg\bin\llvm-tblgen.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
```

Steps to reproduce:
`vcpkg install llvm:arm64-windows`

**Comment by Neumann-A** [comment]
Be aware that the current toolchains for arm don't correctly set `CMAKE_CROSSCOMPILING` which is why 
https://github.com/microsoft/vcpkg/blob/b361c2eefa3966cb7cec45275aff32e90430aaa6/ports/qtbase/cmake/qt_install_submodule.cmake#L72-L74 is required for e.g. qt
Maybe the LLVM build will also work better with those options passed?

**Comment by abique** [comment]
@yurybura I've added extra settings for your issue
@Neumann-A I've added a similar check to what you suggested

Thank you very much for your feedback.

**Review by JackBoosY — APPROVED** [review]

**Comment by Neumann-A** [comment]
@JackBoosY: Note that `llvm:arm64-windows` is still skipped in CI

**Comment by abique** [comment]
> @abique Could you tell what combination of platforms have you tested yet?
> Your changes don't help me to build arm64-windows on Windows x86_64.

Hi @yurybura I did a blind change from the suggestions.
Would you like commit access to my branch?
I may not be able to checkout windows arm64 build now, but likely this week.
@JackBoosY it would help if I could get CI to do the cross build @yurybura mentioned.

**Comment by yurybura** [comment]
@abique I can test on my PC. I will suggest you a solution if I find one.
For enable CI for llvm:x64-windows just remove the line:
https://github.com/microsoft/vcpkg/blob/b1b4808228377515acd849b8706ee2ad25ba455d/scripts/ci.baseline.txt#L829

**Review by vicroms — APPROVED** [review]

**Comment by vicroms** [comment]
The changes look good to me, but I'll wait for actual confirmation that they work before merging.

**Pull request merged**
