### PR TITLE
[DO NOT MERGE]test osg-qt

### PR DESCRIPTION
**Pull request by JackBoosY**

### CODE REVIEW

**Comment by JackBoosY** [comment]
@dan-shaw So, I think everything is clear:
We archived cmake files and library files generated by `qt5-base` on the pipeline machine, and these cmake files contain the path of the libraries related to the build path(_/ci/myagent/_work/**1**/s/installed/x64-linux/lib_), which caused osg-qt to find no matching library path when using these libraries(eg: _/ci/myagent/_work/**3**/s/installed/x64-linux/lib_) .

**Comment by Neumann-A** [comment]
@JackBoosY: which file contains an absolute path?

**Comment by JackBoosY** [comment]
@Neumann-A 
```
CMake Error at /ci/myagent/_work/3/s/installed/x64-linux/share/cmake/Qt5Gui/Qt5GuiConfig.cmake:15 (message):
  The imported target "Qt5::Gui" references the file

     "/ci/myagent/_work/1/s/installed/x64-linux/lib/libEGL.so"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/ci/myagent/_work/3/s/installed/x64-linux/share/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /ci/myagent/_work/3/s/installed/x64-linux/share/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:63 (_qt5_Gui_check_file_exists)
  /ci/myagent/_work/3/s/installed/x64-linux/share/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:85 (_qt5gui_find_extra_libs)
  /ci/myagent/_work/3/s/installed/x64-linux/share/cmake/Qt5Gui/Qt5GuiConfig.cmake:184 (include)
  /ci/myagent/_work/3/s/scripts/buildsystems/vcpkg.cmake:286 (_find_package)
  /ci/myagent/_work/3/s/installed/x64-linux/share/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake:93 (find_package)
  /ci/myagent/_work/3/s/scripts/buildsystems/vcpkg.cmake:286 (_find_package)
  /ci/myagent/_work/3/s/installed/x64-linux/share/cmake/Qt5/Qt5Config.cmake:28 (find_package)
  /ci/myagent/_work/3/s/scripts/buildsystems/vcpkg.cmake:286 (_find_package)
  CMakeLists.txt:468 (FIND_PACKAGE)
```

**Comment by Neumann-A** [comment]
Please try out #10641

**Comment by JackBoosY** [comment]
I think this issue should be completely solved in #10641.

**Pull request closed without merging**
