### PR TITLE
[pixel] added support for dascandy/pixel

### PR DESCRIPTION
**Pull request by jayeshbadwaik**
added support for dascandy/pixel library

### CODE REVIEW

**Review by Farwaykorse — CHANGES_REQUESTED** [review]
Let `vcpkg_from_github()` manage all the particulars when getting a project from Github. Easier to update (just the REF and SHA512 values) and harder to make errors.

**Comment by jayeshbadwaik** [comment]
I knew there was a `vcpkg_from_github()` function. I did not know it would be there so soon. So, how do you want me to proceed on it? I am okay with all the changes shown here. Should I just apply them using github interface? Or try to incorporate it into my PR commit?

**Review by jayeshbadwaik — COMMENTED** [review]
* take advantage of `vcpkg_from_github()` function

**Comment by Farwaykorse** [comment]
However you want. The end result would be the same. I believe if you accept anything it flows back to your account and you can pull it. This website is quite good at working with git. ;-)

**Comment by jayeshbadwaik** [comment]
Okay, so I have incorporated all your changes in my commit. You should be able to startup the CI again. Thanks. :-)

**Comment by jayeshbadwaik** [comment]
I have removed the copyright copy from the portfile because I already do that in my installation procedure and having it done twice was causing permissions issues.

**Comment by Farwaykorse** [comment]
About the interaction with your changes to the pixel CmakeLests.txt:  
You want to keep pixels CmakeLists.txt as general as possible.
Following the most used or most obvious implementation.
You don't want to tailor it to vcpkg's current behaviour.
Vcpkg might change and there are more packages-systems. And don't forget stand-alone builds by human users.

But whatever you do, make sure the license ends up as `copyright` in:
 `vcpkg\installed\[triplet]\share\pixel`.

----
*P.s.* When you push a commit to the jayeshbadwaik/vcpkg/pixel branch on GitHub, it will be automatically added to this PR. Then we can follow what changed.
There is no need for a PR to be a single commit, it will end up in a single merge commit anyway.

**Comment by jayeshbadwaik** [comment]
Okay, I think I am ready for this to be merged.

**Comment by jayeshbadwaik** [comment]
The update should now pass the CI.

**Comment by ras0219-msft** [comment]
@jayeshbadwaik It looks like this is still linking with `-lSDL2` instead of using `SDL2::SDL2` (and therefore failing); I remember you mentioned something about either redirecting the source or publishing a new version?

**Comment by jayeshbadwaik** [comment]
Yes. The new version is not yet published. I will let you know when it happens. 
Thanks.

**Comment by jayeshbadwaik** [comment]
@ras0219-msft  Hey, I have fixed the library to link to `SDL2::SDL2` now. Please check it. Thank you. :)

**Comment by ras0219-msft** [comment]
Thanks again!

**Comment by jayeshbadwaik** [comment]
Thank you. :-)

**Pull request merged**
