### PR TITLE
[vcpkg_acquire_msys] add 'which' package to default set on Windows

### PR DESCRIPTION
**Pull request by wrobelda**
**Describe the pull request**
This adds a `which` package to `vcpkg_acquire_msys` and adds it to the list of default packages acquired on Windows in `vcpkg_configure_make`. `which` is commonly used by autotools macros, see e.g. https://cs.github.com/?scopeName=All+repos&scope=&q=path%3A*.m4+%60which

By not providing it, many macros will fail their checks with `which: command not found`, which actually implies the `which` command itself is missing, not the command which `which` is supposed to locate.

### CODE REVIEW

**Comment by Osyotr** [comment]
Maybe also add autoconf-archive?

**Comment by wrobelda** [comment]
> Maybe also add autoconf-archive?

It's already in `vcpkg_acquire_msys`. Adding it to `vcpkg_configure_make` was discussed recently and found unnecessary for vast majority of ports, which I concur with.

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
Waiting for merge https://github.com/microsoft/vcpkg/pull/26646 first.

**Pull request merged**
