### PR TITLE
Update vcpkg-tool to 2022-10-12.

### PR DESCRIPTION
**Pull request by BillyONeal**
https://github.com/microsoft/vcpkg-tool/releases/tag/2022-10-12

### CODE REVIEW

**Review by vicroms — APPROVED** [review]

**Comment by AenBleidd** [comment]
Not sure what went wrong, but immediately after this update I have a build failure on Windows:
```
 LINK : fatal error LNK1181: cannot open input file 'wxmsw32u_webview.lib'
```
https://github.com/BOINC/boinc/actions/runs/3246375246/jobs/5325041431

**Comment by BillyONeal** [comment]
Nothing by that name is published by any port, at least not in the official catalog.

**Comment by AenBleidd** [comment]
This is wxWidgets, but the version is the same. The only that was changed is a vcpkg binary itself

**Comment by BillyONeal** [comment]
> This is wxWidgets, but the version is the same. The only that was changed is a vcpkg binary itself

image

**Comment by BillyONeal** [comment]
Looks like this machine was overriding VCPKG_ROOT so you weren't using the versions of things actually declared in your repo before.

**Comment by AenBleidd** [comment]
ok, thanks will check that

**Comment by BillyONeal** [comment]
> ok, thanks will check that

FYI that was https://github.com/microsoft/vcpkg-tool/pull/725

**Pull request merged**
