### PR TITLE
[opentelemetry-cpp] Add missing features #21124

### LINKED ISSUE #21124: [opentelemetry-cpp] Missing features
There are missing OpenTelemetry features: 
 * [otlp](https://github.com/open-telemetry/opentelemetry-cpp/blob/368f172fe00581dc09405a2c1f1e5ccfcb273040/CMakeLists.txt#L158) 
 * [zpages](https://github.com/open-telemetry/opentelemetry-cpp/blob/368f172fe00581dc09405a2c1f1e5ccfcb273040/CMakeLists.txt#L167)

[OTLP exporter](https://github.com/open-telemetry/opentelemetry-cpp/blob/bfab71a53fda0ac2533c81de61e84adaa47c4149/exporters/otlp/README.md) depends on opentelemetry-proto which is utilized as a submodule at [opentelemetry-cpp/third_party/opentelemetry-proto@795cc81](https://github.com/open-telemetry/opentelemetry-proto/tree/795cc815ce9bb438b46a4a7f6ecb465b52d50935) if I do manually add otlp to the feature list in the vcpkg portfile.cmake then the vcpkg build fails because the third_party folder was empty. It is needed to clone the submodules after downloading open-telemetry-opentelemetry-cpp-v1.0.1.tar.gz

```
vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    FEATURES
        etw WITH_ETW
        zipkin WITH_ZIPKIN
        prometheus WITH_PROMETHEUS
        elasticsearch WITH_ELASTICSEARCH
        jaeger WITH_JAEGER

        otlp WITH_OTLP
)
```

### PR DESCRIPTION
**Pull request by juandemanjon**
Add missing opentelemetry-cpp features otlp and zpages. 
Fixes #21124

For the next release update, the vcpkg maintainer should update the OTEL_PROTO_VERSION variable and the SHA512 signature for the opentelemetry-proto submodule dependency

### CODE REVIEW

**Review by JonLiu1993 — APPROVED** [review]

**Comment by JonLiu1993** [comment]
@juandemanjon ,Thanks for your pr, I tested the features in the x64-linux triplet but failed, this is the error log:
````
CMake Warning at /home/test1/vcpkg/scripts/buildsystems/vcpkg.cmake:788 (_find_package):
  By not providing "FindgRPC.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "gRPC", but
  CMake did not find one.

  Could not find a package configuration file provided by "gRPC" with any of
  the following names:

    gRPCConfig.cmake
    grpc-config.cmake

  Add the installation prefix of "gRPC" to CMAKE_PREFIX_PATH or set
  "gRPC_DIR" to a directory containing one of the above files.  If "gRPC"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:305 (find_package)


CMake Error at /home/test1/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Protobuf (missing: Protobuf_LIBRARIES Protobuf_INCLUDE_DIR)
Call Stack (most recent call first):
  /home/test1/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /home/test1/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/share/cmake-3.21/Modules/FindProtobuf.cmake:650 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /home/test1/vcpkg/scripts/buildsystems/vcpkg.cmake:788 (_find_package)
  CMakeLists.txt:319 (find_package)

````

**Comment by juandemanjon** [comment]
@JonLiu1993 I have added grpc and protobuf dependencies to OTLP feature in the vcpkg.json

**Comment by juandemanjon** [comment]
@JonLiu1993  Now both x64_linux and x64_osx succeeded but windows is failing. I think it is not related to the port. Please would you have a look?

**Comment by JonLiu1993** [comment]
Except for ‘etw’, all features have been successfully tested under the 64-linux triplet

**Review by JonLiu1993 — APPROVED** [review]

**Comment by juandemanjon** [comment]
@JonLiu1993 Thank you for pushing a new ```port-version```

**Pull request merged**
