### PR TITLE
[cspice] Add new port

### PR DESCRIPTION
**Pull request by 375gnu**
SPICE (Spacecraft Planet Instrument C-matrix Events) is a NASA ancillary information system used to compute geometric and event information in analyzing and planning science observations obtained from spacecraft. It is also used in planning missions and conducting numerous engineering functions needed to carry out those missions.

### CODE REVIEW

**Comment by LilyWangL** [comment]
There are no features of this port need to test.

**Review by LilyWangL — APPROVED** [review]

**Comment by LilyWangL** [comment]
There are no features of this port need to test.
@grdowns, this PR is ready to merge now.

**Comment by grdowns** [comment]
Thanks for the new port, @375gnu! Always cool to see NASA libraries

**Pull request merged**
