### PR TITLE
Fix wrong single line endings in CRLF port files

### PR DESCRIPTION
**Pull request by c72578**
**Describe the pull request**
Several CONTROL and portfile.cmake files with Windows (CRLF) line
endings contain single lines with wrong line endings. At the end of the
affected lines, the CR is incorrectly missing.

Command used to detect and correct these files:
```console
git grep -Il $'\r' -- '*/CONTROL' '*/portfile.cmake' | xargs unix2dos
```
- What does your PR fix? Fixes issue #
Single, incorrect line endings in CONTROL and portfile.cmake files with CRLF line endings

- Which triplets are supported/not supported? Have you updated the CI baseline?
N/A

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

### CODE REVIEW

**Comment by cenit** [comment]
the script that MS team internally uses to update most of github ports updates those lines using CRLF line ending. That is the source of what you found.
I already opened a PR time ago modifying not just those lines but all the files that were not conforming to a LF line ending and forcing it globally using gitattributes, but it was closed as "troublesome".
For sure, before merging this PR, it would be nice if also the script that made this mix is fixed in order to use LF line ending.

**Comment by LilyWangL** [comment]
@c72578, thanks for your PR! Can you please correct the Version field in the CONTROL file? You can see more detail from the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).

**Comment by c72578** [comment]
Concerning the Version: field
> Vcpkg uses this field to determine whether a given port is out-of-date and should be changed whenever the port's behavior changes.

The behavior of the ports does not change, so there is no need to update the version field.

This PR fixes detected incorrect line endings in text files. The malformed files have got Windows (CRLF) line endings in general, but single lines with LF only line ending (Unix) have been "injected" into them.

**Comment by c72578** [comment]
@cenit, I looked up the PR you mentioned above, which is "[many ports] normalize line endings" https://github.com/microsoft/vcpkg/pull/6290

**Comment by c72578** [comment]
Just for the records.
As of 2020-01-13, the following **`CONTROL`** and **`portfile.cmake`** files were affected:
```console
ports/abseil/portfile.cmake
ports/aws-c-common/CONTROL
ports/aws-c-common/portfile.cmake
ports/aws-sdk-cpp/portfile.cmake
ports/boost/portfile.cmake
ports/breakpad/CONTROL
ports/breakpad/portfile.cmake
ports/caf/CONTROL
ports/cmark/CONTROL
ports/ensmallen/portfile.cmake
ports/fizz/CONTROL
ports/fizz/portfile.cmake
ports/forge/CONTROL
ports/forge/portfile.cmake
ports/ftgl/CONTROL
ports/ftgl/portfile.cmake
ports/gherkin-c/CONTROL
ports/gherkin-c/portfile.cmake
ports/glad/CONTROL
ports/glad/portfile.cmake
ports/kf5archive/CONTROL
ports/kf5archive/portfile.cmake
ports/kf5holidays/CONTROL
ports/kf5holidays/portfile.cmake
ports/laszip/CONTROL
ports/laszip/portfile.cmake
ports/lest/CONTROL
ports/lest/portfile.cmake
ports/libimobiledevice/CONTROL
ports/libimobiledevice/portfile.cmake
ports/liblinear/CONTROL
ports/liblinear/portfile.cmake
ports/libmariadb/portfile.cmake
ports/libplist/CONTROL
ports/libplist/portfile.cmake
ports/libyaml/CONTROL
ports/luabridge/CONTROL
ports/msix/CONTROL
ports/nana/portfile.cmake
ports/osg-qt/CONTROL
ports/osg-qt/portfile.cmake
ports/osgearth/CONTROL
ports/piex/CONTROL
ports/qtkeychain/CONTROL
ports/rabit/CONTROL
ports/rabit/portfile.cmake
ports/sqlpp11/portfile.cmake
ports/taocpp-json/CONTROL
ports/taocpp-json/portfile.cmake
ports/tinyutf8/CONTROL
ports/usbmuxd/CONTROL
ports/usbmuxd/portfile.cmake
ports/vtk-dicom/CONTROL
ports/vtk-dicom/portfile.cmake
ports/vulkan-memory-allocator/CONTROL
ports/vulkan-memory-allocator/portfile.cmake
ports/wangle/CONTROL
ports/wangle/portfile.cmake
ports/xeus/CONTROL
ports/xeus/portfile.cmake
```

**Pull request closed without merging**
