### PR TITLE
[boost-locale] Enable arm64-windows

### PR DESCRIPTION
**Pull request by tony979**
boost-locale:arm64-windows needs boost-thread:arm64-windows

### CODE REVIEW

**Comment by NancyLi1013** [comment]
Hi @tony979, could you also bump the CONTROL version?

**Comment by tony979** [comment]
The Version is bumped from 1.69.0 to 1.69.0-1

**Comment by NancyLi1013** [comment]
@tony979, I'm so sorry about this. It's my mistake.

**Comment by grdowns** [comment]
This PR passes the CI build. Thanks @tony979!

**Pull request merged**
