### PR TITLE
Add headers to vcpkg_download_distfile

### PR DESCRIPTION
**Pull request by donny-dont**
Allows headers to be appended when downloading a distribution. This allows for setting
authentication headers to download from a private repository.

This can be extended to private GitHub repos, GitHub Enterprise repos, and probably GitLab as well.

### CODE REVIEW

**Comment by donny-dont** [comment]
@vicroms hows this look to you? Anything else that would need to happen to get this merged?

**Comment by vicroms** [comment]
Sorry for the delay,

I intended to piggyback this PR to include some much needed documentation updates and forgot to follow through.

**Comment by donny-dont** [comment]
No worries. Wasn't sure if any code changes were required.

**Comment by vicroms** [comment]
Do you have an example of how to use this new feature that can be added to the docs?

**Comment by donny-dont** [comment]
So its useful for private repositories in GitHub and GitHub Enterprise. Though I would probably add on top of the GitHub download script to accept an OAuth token. But something like

```
vcpkg_download_distfile(
  ARCHIVE
  FILENAME "hello-world-1.0.0.tar.gz"
  URLS https://github.my-company.com/api/v3/repos/octocat/hello-world/zipball/v1.0.0
  HEADERS "Authorization: token $ENV{GITHUB_TOKEN}
)
```

I would probably add support for downloading from a github enterprise instance in `vcpkg_from_github` and add the ability to add an OAUTH_TOKEN. Then that would call accordingly to `vcpkg_download_distfile`.

**Pull request merged**
