### PR TITLE
[qhttpengine] New port

### PR DESCRIPTION
**Pull request by kafeg**
https://github.com/nitroshare/qhttpengine

### CODE REVIEW

**Review by LilyWangLL — APPROVED** [review]

**Review by BillyONeal — APPROVED** [review]
I removed the duplicate build_shared_libs setting and looks good to me now :)

**Comment by kafeg** [comment]
Thank you, would be good to know it's handled automaticaly =)

**Comment by BillyONeal** [comment]
Thanks :)

**Review by Patrikguarda71 — COMMENTED** [review]
Coar documenti

**Pull request merged**
