### PR TITLE
[WIP] add emscripten toolchain

### PR DESCRIPTION
**Pull request by Milerius**

### CODE REVIEW

**Comment by MoAlyousef** [comment]
Hi
I've tried implementing this on osx and linux and it works (haven't tried it on windows yet).
It only needs adding the EMSCRIPTEN environment variable to the shell.
Why not add it to the main repo?

**Comment by Milerius** [comment]
I dont remember but we had a discussion about this subject with @ras0219-msft . I dont remember but he give me a non intruisive way for Emscripten. Will wait for his answer

**Comment by MoAlyousef** [comment]
> I dont remember but we had a discussion about this subject with @ras0219-msft . I dont remember but he give me a non intruisive way for Emscripten. Will wait for his answer

So I've been poking around the scripts a bit, and it turns out all you need to do is modify the x86-emscripten triplet by setting the VCPKG_CHAINLOAD_TOOLCHAIN_FILE to point to the location of the Emscripten toolchain. And that's it!

**Comment by ras0219-msft** [comment]
The primary issue with adding a new triplet is that we use the triplets in the box to represent the set of platforms that we actively test and support -- therefore, before accepting this PR to add a new triplet we need to internally have systems to active test and support it :). If we remove the triplet file (which is really easy for users to create!) then it'd be a lot easier to merge.

Additionally, I think we can do better than directly checking in the entire emscripten toolchain file -- isn't this copied out of the emscripten distribution? If so, we should give the user a way to point us at their distribution and we should just `include()` it from there.

Finally, I think we need to mess with the emscripten platform detection logic; I really doubt we need three separate cases to detect it :)

**Comment by TrevorSundberg** [comment]
I was attempting to run this pull request, however I ran into a few snags. Whenever I try and download a package (trying with assimp) I get a build error saying that the `EMSCRIPTEN` environment variable isn't defined. I checked with my system environment variables and it definitely is (I can even write `echo %EMSCRIPTEN%` and it prints out the path). After some debugging, I realized that vcpkg is stripping out environment variables to build a sort of "clean machine", and `EMSCRIPTEN` wasn't added to the white-list.

That leads me to the question of how are you currently getting it to run?

As a stopgap I manually defined my `EMSCRIPTEN` path inside the `Emscripten.cmake`, and got yet another error. This time it was when calling `em++` it failed to run. After a bit more digging, the reason it was failing was because it couldn't find `python`. Python was definitely in my path, but this goes back to the same problem of the `PATH` variable not getting through into `Emscripten.cmake` due to vcpkg sanitization.

I feel like I'm missing something if everyone else is able to run this pull request. Any help would be greatly appreciated! :)

**Comment by Milerius** [comment]
I think that we can ask Robert Schumacher, if he had any news about an emscripten support with vcpkg

**Comment by akaltar** [comment]
It's been half a year, are there any updates on this?

**Comment by cbezault** [comment]
It's currently still in the same state of affairs. We only accept pull requests for libraries on platforms we're actively engaged in testing. We currently don't have any plans to add emscripten to our testing and until we do, we can't accept this PR.

**Comment by dan-shaw** [comment]
We are now okay with adding a new toolchain; we've recently merged the MinGW one. @Milerius Let us know if you're still interested in getting this merged.

**Comment by Milerius** [comment]
I'm still interested @dan-shaw But i'm really busy those days and incoming week, is it possible for someone to continue this pull request maybe ?.

**Comment by dan-shaw** [comment]
@Milerius Going to close/archive this PR for now. If anyone wants to continue this, feel free to reopen. It might make more sense to open a new PR instead, since this PR is fairly old and we might lose track of it.

**Pull request closed without merging**
