### PR TITLE
[qt5-location] Modify clipper library name to avoid conflicts with vxl

### PR DESCRIPTION
**Pull request by ras0219-msft**

### CODE REVIEW

**Comment by PhoebeHui** [comment]
@ras0219-msft, the patch updated, and vxl:x64-osx pass in CI testing, this fix worked, it's ready to merge.

**Comment by ras0219-msft** [comment]
Thanks for handling this!

**Comment by cenit** [comment]
this renaming is just a way to redistribute "again" the polyclipping library, hiding a port conflict, since we already have a portfile for clipper/polyclipping.
Is it the right way to handle the problem? Asking because something similar is happening in #12199, for the poly2cli library...

**Comment by cenit** [comment]
@ras0219 this looks like a way to just double the files owning the same symbols, isn't it? With all those problems that might appear downstream in case of different linking paths...
Anyway, I applied the same strategy also in PR #12199

**Pull request merged**
