### PR TITLE
[libpng] Fix android build

### PR DESCRIPTION
**Pull request by huangqinjin**

### CODE REVIEW

**Comment by pthom** [comment]
Hello, I tested this PR on my side, it fixes the issue I was complaining about [here](https://github.com/microsoft/vcpkg/pull/11130) (when trying to build opencv4 for android, which require png). 
Thanks!

**Comment by cenit** [comment]
when merged, I will cherry pick this commit into my PR so that @pthom can continue tests with opencv4 and png

**Comment by atkawa7** [comment]
@huangqinjin @pthom @cenit  Current patch on mine which doesn't affect the cmakelist

```
diff --git a/ports/libpng/portfile.cmake b/ports/libpng/portfile.cmake
index e9a200455..e89ff15cf 100644
--- a/ports/libpng/portfile.cmake
+++ b/ports/libpng/portfile.cmake
@@ -47,11 +47,16 @@ else()
     set(PNG_SHARED_LIBS OFF)
 endif()

+if(VCPKG_CMAKE_SYSTEM_NAME STREQUAL Android)
+    set(HAVE_LD_VERSION_OPTION "-DHAVE_LD_VERSION_SCRIPT=OFF")
+endif()
+
 vcpkg_configure_cmake(
     SOURCE_PATH ${SOURCE_PATH}
     PREFER_NINJA
     OPTIONS
         ${LIBPNG_APNG_OPTION}
+        ${HAVE_LD_VERSION_OPTION}
         -DPNG_STATIC=${PNG_STATIC_LIBS}
         -DPNG_SHARED=${PNG_SHARED_LIBS}
         -DPNG_TESTS=OFF
```

**Comment by huangqinjin** [comment]
https://github.com/glennrp/libpng/blob/6dd99ca9c85a59cc8848553177b84abea228f82f/CMakeLists.txt#L425 generates `libpng.vers` if not `(NOT AWK OR ANDROID)`, so I think it's a bug @atkawa7 .

**Comment by atkawa7** [comment]
> https://github.com/glennrp/libpng/blob/6dd99ca9c85a59cc8848553177b84abea228f82f/CMakeLists.txt#L425 generates `libpng.vers` if not `(NOT AWK OR ANDROID)`, so I think it's a bug @atkawa7 .

There wasn't any need to include a patch as this option `HAVE_LD_VERSION_SCRIPT` option can be used to turn it off

**Comment by huangqinjin** [comment]
It's better if we can fix it without patch from vcpkg's point of view.  But I think it's a bug which shoule be fixed in upstream. Actually there is a cmake option `ld-version-script` can be used. I reworked this PR to use it.

**Review by PhoebeHui — APPROVED** [review]
LGTM, thanks for the PR!

**Comment by strega-nil** [comment]
This conflicts with #11162; can you update the version to `-9`, and fix the merge conflict?

**Comment by huangqinjin** [comment]
@strega-nil Done.

**Comment by strega-nil** [comment]
Awesome, thanks @huangqinjin. This looks great :)

**Pull request merged**
