### PR TITLE
[vcpkg ci] Check for deprecated license identifiers

### PR DESCRIPTION
**Pull request by autoantwort**
Fixes https://github.com/microsoft/vcpkg/pull/22946#issuecomment-1030592217

### CODE REVIEW

**Comment by autoantwort** [comment]
@JackBoosY can you add the reviewed flag so it is seen by the other maintainers?

**Comment by JackBoosY** [comment]
Ping @BillyONeal for review this PR.

**Comment by BillyONeal** [comment]
1. This seems reasonable to me.
2. Could the message be combined with the one about "missing" licenses into an overall "you should check the license field in these files"?
3. Is there a good way to test this? I'm concerned about the last time I merged a change like this and put the bot on the floor for a while.

**Comment by autoantwort** [comment]
> Is there a good way to test this? I'm concerned about the last time I merged a change like this and put the bot on the floor for a while.

Yes, we can change code to trigger the code paths. I one changes `vcpkg/.github/workflows/trustedPR.yml` one have the problem that you can not test the change

**Comment by JackBoosY** [comment]
Ping @BillyONeal for reply.

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
