### PR TITLE
[Python3] update to 3.9.7

### LINKED ISSUE #19849: [Python3] update to 3.9.7
Library name: **Python3**

New version number: **3.9.7**
Other information that may be useful (release notes, etc...)
https://docs.python.org/release/3.9.7/whatsnew/changelog.html

tool-update, already noted in https://github.com/microsoft/vcpkg/issues/19568

### PR DESCRIPTION
**Pull request by JonLiu1993**
Fix #19849 

Update Python3 to the latest version 3.9.7

All features are tested successfully in the following triplet:
- x86-windows
- x64-windows
- x64-windows-static

### CODE REVIEW

**Comment by Hoikas** [comment]
Please also update the the PYTHON3 binaries in vcpkg_find_acquire_program and vcpkgTools.xml. These items must always update in lock-step with the python3 port or risk breaking ports that depend on both the tools and the python3 port.

**Comment by JonLiu1993** [comment]
> Please also update the the PYTHON3 binaries in vcpkg_find_acquire_program and vcpkgTools.xml. These items must always update in lock-step with the python3 port or risk breaking ports that depend on both the tools and the python3 port.

Ok, thanks for your reminder

**Comment by Hoikas** [comment]
Thanks for doing this update, @JonLiu1993 😄

**Comment by JonLiu1993** [comment]
This pr depend on pr #20006

**Review by NancyLi1013 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the version update!

**Pull request merged**
