### PR TITLE
[liblo] Fix filenames for linux in liblo portfile

### PR DESCRIPTION
**Pull request by stekyne**
**Describe the pull request** 
Liblo currently doesn't build on Linux (and I assume Mac) due to some filenames in the portfile specifying "exe" filetype.

- #### What does your PR fix?  
Allows building on non-windows platforms

- #### Which triplets are supported/not supported? Have you updated the [CI baseline]?
x64-linux, x64-windows, x64-osx

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
I think so

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
Yes

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
Depends on https://github.com/microsoft/vcpkg/pull/19633.

**Comment by stekyne** [comment]
What's left to get this merged? It looks like the checks have passed. Thanks

**Comment by ras0219-msft** [comment]
Awesome, LGTM! Thanks for the PR!

**Pull request merged**
