### PR TITLE
[quantlib] update to v1.30

### PR DESCRIPTION
**Pull request by sweemer**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by sweemer** [comment]
Hi @Adela0814 can you share the CMake error logs with me? I can't see the underlying build failure from the pipeline logs so it's a bit hard to know why the builds failed.

**Comment by dg0yt** [comment]
CI failure logs are in the public artifacts:
https://dev.azure.com/vcpkg/public/_build/results?buildId=88447&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by sweemer** [comment]
Hmm, the links on that page are not working for me. @dg0yt if the links work for you, then would you mind pasting the underlying build error here for me?

**Comment by dg0yt** [comment]
The downloads are hidden behind a thee dots icon appearing on the right side when you hover an item.

**Comment by sweemer** [comment]
Aha, thanks!

I found out the reason for the build failures now and I will fix it soon.

**Comment by sweemer** [comment]
I added a patch and now all checks have passed so I think this can be merged.

I'll try to fix the upstream issue and remove the patch for the next version update.

**Comment by BillyONeal** [comment]
I see commits upstream from @sweemer so I'm happy saying they are a representative of upstream and thus no cooldown period is necessary.

Thanks for the update/patch!

**Pull request merged**
