### PR TITLE
[cairo] Fix static cairo builds

### PR DESCRIPTION
**Pull request by Neumann-A**
Makes cairo buildable in x64-windows-static.
For some reason cario is skipped in CI. Probably due to some port depending on gobject feature?

### CODE REVIEW

**Comment by JackBoosY** [comment]
Should also fix https://github.com/microsoft/vcpkg/issues/18082 ?

**Comment by JackBoosY** [comment]
Can you also fix https://github.com/microsoft/vcpkg/issues/18102 in this PR?

Thanks.

**Comment by Neumann-A** [comment]
@JackBoosY I am not going to add unofficial CMake targets. The way to consume Cairo is via the supplied pc files and FindPkgConf. 
The real problem is that Io2d is still referencing that target in the portfile while generating a config for Io2d.

**Comment by Neumann-A** [comment]
Ah yeah I wanted to CI to build this first in `x64-windows-static` before marking it as ready to review

**Comment by JackBoosY** [comment]
The regression should be fixed by https://github.com/microsoft/vcpkg/pull/18116, can you please merge to master?

**Comment by Neumann-A** [comment]
@JackBoosY I am not concerned about the regression in libtasn1 because i know it has been fixed. I want  `cairo:x64-windows-static:    cascade: 95900d64bc91f32160b6dfd64fa2affa92fb3fde` to be solved or a way to remove the cascade failure. It happens because glib does not build statically and something (GTK) is requesting the glib feature from cairo

**Comment by JackBoosY** [comment]
@Neumann-A Because:
```
.\vcpkg depend-info cairo:x64-windows-static
cairo[fontconfig, freetype, gobject, x11]: dirent, expat, fontconfig, freetype, glib, libpng, lzo, pixman, pthread, zlib
```
```
glib:x64-windows-static:       skip: c903b3210ebbf1f98d344a620ddc948f9d384853
```

**Comment by Neumann-A** [comment]
@JackBoosY: For me it returns:
```
./vcpkg.exe depend-info cairo:x64-windows-static
...
cairo[fontconfig, freetype]: dirent, expat, fontconfig, freetype, libpng, lzo, pixman, pthread, zlib
```

**Comment by JackBoosY** [comment]
@Neumann-A use `./vcpkg depend-info cairo[*]:x64-windows-static`.

**Comment by Neumann-A** [comment]
@JackBoosY I know that * depends on glib. CI should not test this configuration since the dependencies requiring the `gobject` feature are marked as skipped. This is really a CI pitfall since it can greatly reduce the number of tested ports in CI by simply addding a feature to another port with an unsupported configuration for certain triplets. This is really annoying and should be reworked. I mean cairo with default features work fine in x64-windows-static but it is simply not tested because another port like gtk depends on the gobject feature which is marked as skiped but CI still tries to build the feature rich version of cairo.

**Comment by JackBoosY** [comment]
I perfer to let @BillyONeal tell why we do that.

**Review by JackBoosY — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
