### PR TITLE
[tbb]: added support for hybrid processors via hwloc

### PR DESCRIPTION
**Pull request by ilya-lavrenov**
With this patch we are adding support of hybrid processors (new tbbbind library is being built), so TBB can distinguish performance and efficient cores on both ARM and x64 processors.

Note: this applicable only for shared libraries built, because tbbbind library is built as plugin for TBB.

### CODE REVIEW

**Comment by Osyotr** [comment]
Maybe make it a feature? Also add `"supports": "!static"`

**Comment by ilya-lavrenov** [comment]
> Maybe make it a feature? Also add `"supports": "!static"`

done

**Comment by Osyotr** [comment]
Hmm if there are no changes in `protfile.cmake` I assume tbb will link to `hwloc` even if installed separately. This is a bug, in the port. Probably `-DTBB_DISABLE_HWLOC_AUTOMATIC_SEARCH=ON/OFF` needs to be passed depending on whether the feature is requested or not.

**Comment by ilya-lavrenov** [comment]
> Hmm if there are no changes in `protfile.cmake` I assume tbb will link to `hwloc` even if installed separately. This is a bug in the port. Probably `-DTBB_DISABLE_HWLOC_AUTOMATIC_SEARCH=ON/OFF` needs to be passed depending on whether the feature is requested or not.

great catch! Fixed according to your note.

**Comment by LilyWangLL** [comment]
Feature passed on the following triplets:
```
x64-windows
x86-windows
```

**Review by LilyWangLL — APPROVED** [review]

**Comment by ilya-lavrenov** [comment]
Can we merge the PR?

**Pull request merged**
