### PR TITLE
[fftw] Use builtin cmake configuration

### PR DESCRIPTION
**Pull request by ghost**
This uses the builtin cmake file and incidentally fixes a missing symbols problem that I had.

### CODE REVIEW

**Comment by alexkaratarakis** [comment]
Thanks!

**Comment by jasjuang** [comment]
@xoviat I just tried this and I got the error

```
CMake Error at C:/dev/vcpkg/ports/fftw3/portfile.cmake:27 (file):
  file RENAME failed to rename

    C:/dev/vcpkg/packages/fftw3_x64-windows/lib/cmake

  to

    C:/dev/vcpkg/packages/fftw3_x64-windows/share/fftw3

  because: File exists

Call Stack (most recent call first):
  C:/dev/vcpkg/scripts/ports.cmake:72 (include)

```

Is there a reason not using `vcpkg_fixup_cmake_targets`?

**Comment by xoviat** [comment]
Was not aware of that function. That file did not exist on my computer though.

**Comment by xoviat** [comment]
Hi there. After several attempts, I could not reproduce this problem on multiple computers.

**Comment by jasjuang** [comment]
That's weird. I tried it on 3 computers and it all have the same problem. Not sure if it's a problem of my setup or yours.

@ras0219-msft Can you give it a try?

**Comment by xoviat** [comment]
Successful build from HEAD:

https://ci.appveyor.com/project/xoviat/test-vcpkg/build/1.0.124

**Comment by ras0219-msft** [comment]
Right, I know the issue.

The problem is that the sources are automatically cached between builds. This is to improve the build speed when rebuilding (because we avoid re-unpacking), but it does cause problems when making these kinds of changes.

The right fix is to test if the installed file is from the previous version, then purge the source folder if it is.

**Comment by jasjuang** [comment]
Confirmed that once I removed the fftw3 from the buildtree and the downloads folder and reinstall it works. Thanks @xoviat and @ras0219-msft

**Pull request merged**
