### PR TITLE
[openexr] Update from 2 to 3.1.5, patch all consuming ports

### PR DESCRIPTION
**Pull request by dg0yt**
- #### What does your PR fix?
  Updates openexr  major version.
  Patches all consuming ports which don't natively support major version 3.
  Drops the cmake wrapper.

  Previous work: #26788 (side-by-side 2 and 3), #25238 (only adding openexr3), #24249, #20957 (direct updates of openexr).

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  unchanged, no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  yes

### CODE REVIEW

**Comment by dg0yt** [comment]
What to do with `/guard:ehcont` as used by `directxtex`, but absent in `openexr`?
a) Disabled it where used (`directxtex` (done), `uvatlas` (current error))
b) Add it upstream where necessary (at least `openexr`, `imath`)

Note that this problem is not a regression, but was already hidden behind optional `directxtex[openexr]`. It is just uncovered by specific test commits.

**Comment by meshula** [comment]
Thank you for this patch! Looking forward to being able to use it :)

**Review by JonLiu1993 — APPROVED** [review]

**Comment by JonLiu1993** [comment]
All features are tested successfully in the following triplet:
- x86-windows
- x64-windows
- x64-windows-static

**Comment by simogasp** [comment]
Great work! thanks for this.
If it can be merged I will close my draft #25238

**Pull request merged**
