### PR TITLE
[directxmesh, directxtex, directxtk, uvatlas, dxut, effects11] June 2023 update

### PR DESCRIPTION
**Pull request by walbourn**
This PR updates the following ports for June 2023 releases on GitHub:

**directxmesh**, **directxtex**, **directxtk**, **directxtk12**, **uvatlas**, **dxut**, **effects11**

* **directxtex:**  A few minor new features for the library and tools

* **direcxtxtex**, **directxmesh** only require *directx-headers* for MinGW or Linux scenarios -or- if using the ``dx12`` feature.

* command-line tools are now Long Path Aware on Windows 10, Version 1607 or later

* command-line tools updated for a minor output quirk when printing system error messages

* All ports now have explicit ``usage`` files

* **dxut**, **effects11** now use ``vcpkg_install_copyright``

* All ports updated with CMake fixes for specific issues:
  * The generated cmake targets for the xbox triplet forced the use of directx-headers as a dependency which isn't supported
  * Fixed a build break when mixing VS 2022 Update 5 with Windows SDKs prior to 22000
  * Improved support for clang v16

### CODE REVIEW

**Comment by walbourn** [comment]
Locally validated all supported triplets and features:

# DirectXMesh
```
vcpkg install directxmesh:x86-windows
vcpkg install directxmesh[tools]:x86-windows --recurse
vcpkg install directxmesh[dx12]:x86-windows --recurse
vcpkg install directxmesh[spectre]:x86-windows --recurse
vcpkg install directxmesh:x86-windows-static
vcpkg install directxmesh:x86-windows-static-md

vcpkg install directxmesh:x64-windows
vcpkg install directxmesh[tools]:x64-windows --recurse
vcpkg install directxmesh[dx12]:x64-windows --recurse
vcpkg install directxmesh[spectre]:x64-windows --recurse
vcpkg install directxmesh:x64-windows-static
vcpkg install directxmesh:x64-windows-static-md

vcpkg install directxmesh:arm-windows
vcpkg install directxmesh[tools]:arm-windows --recurse
vcpkg install directxmesh[spectre]:arm-windows --recurse

vcpkg install directxmesh:arm64-windows
vcpkg install directxmesh[tools]:arm64-windows --recurse
vcpkg install directxmesh[spectre]:arm64-windows --recurse
vcpkg install directxmesh:arm64-windows-static
vcpkg install directxmesh:arm64-windows-static-md

vcpkg install directxmesh:x86-uwp
vcpkg install directxmesh:x64-uwp
vcpkg install directxmesh:arm-uwp
vcpkg install directxmesh:arm64-uwp

vcpkg install directxmesh:x64-xbox-scarlett
vcpkg install directxmesh:x64-xbox-scarlett-static
vcpkg install directxmesh:x64-xbox-xboxone
vcpkg install directxmesh:x64-xbox-xboxone-static

./vcpkg install directxmesh:x64-linux
./vcpkg install directxmesh[dx12]:x64-linux --recurse

./vcpkg install directxmesh:arm64-linux
./vcpkg install directxmesh[dx12]:arm64-linux --recurse

vcpkg install directxmesh:x64-mingw-static
vcpkg install directxmesh[dx12]:x64-mingw-static --recurse
vcpkg install directxmesh[tools]:x64-mingw-static --recurse

vcpkg install directxmesh:x86-mingw-static
vcpkg install directxmesh[dx12]:x86-mingw-static --recurse
vcpkg install directxmesh[tools]:x86-mingw-static --recurse

vcpkg install directxmesh:x64-clangcl-dynamic
vcpkg install directxmesh[tools]:x64-clangcl-dynamic --recurse
vcpkg install directxmesh[dx12]:x64-clangcl-dynamic --recurse
vcpkg install directxmesh:x64-clangcl-static

vcpkg install directxmesh:arm64-clangcl-dynamic
vcpkg install directxmesh[tools]:arm64-clangcl-dynamic --recurse
vcpkg install directxmesh:arm64-clangcl-static

vcpkg install directxmesh:x64-clangcl-uwp
vcpkg install directxmesh:arm64-clangcl-uwp

vcpkg install directxmesh:x64-clangcl-scarlett
vcpkg install directxmesh:x64-clangcl-scarlett-static
vcpkg install directxmesh:x64-clangcl-xboxone
vcpkg install directxmesh:x64-clangcl-xboxone-static
```

**Comment by walbourn** [comment]
# DirectXTex
```
vcpkg install directxtex[core]:x86-windows
vcpkg install directxtex:x86-windows --recurse
vcpkg install directxtex[tools]:x86-windows --recurse
vcpkg install directxtex[dx12]:x86-windows --recurse
vcpkg install directxtex[openexr,tools]:x86-windows --recurse
vcpkg install directxtex[spectre]:x86-windows --recurse
vcpkg install directxtex:x86-windows-static
vcpkg install directxtex:x86-windows-static-md

vcpkg install directxtex[core]:x64-windows
vcpkg install directxtex:x64-windows --recurse
vcpkg install directxtex[tools]:x64-windows --recurse
vcpkg install directxtex[dx12]:x64-windows --recurse
vcpkg install directxtex[openexr,tools]:x64-windows --recurse
vcpkg install directxtex[spectre]:x64-windows --recurse
vcpkg install directxtex:x64-windows-static
vcpkg install directxtex:x64-windows-static-md

vcpkg install directxtex:arm-windows
vcpkg install directxtex[tools]:arm-windows --recurse
vcpkg install directxtex[spectre]:arm-windows --recurse

vcpkg install directxtex:arm64-windows
vcpkg install directxtex[tools]:arm64-windows --recurse 
vcpkg install directxtex[spectre]:arm64-windows --recurse
vcpkg install directxtex:arm64-windows-static
vcpkg install directxtex:arm64-windows-static-md

vcpkg install directxtex:x86-uwp
vcpkg install directxtex:x64-uwp
vcpkg install directxtex:arm-uwp
vcpkg install directxtex:arm64-uwp

vcpkg install directxtex:x64-xbox-scarlett
vcpkg install directxtex:x64-xbox-scarlett-static
vcpkg install directxtex:x64-xbox-xboxone
vcpkg install directxtex:x64-xbox-xboxone-static

./vcpkg install directxtex:x64-linux
./vcpkg install directxtex[dx12]:x64-linux --recurse
./vcpkg install directxtex[openexr]:x64-linux --recurse

./vcpkg install directxtex:arm64-linux
./vcpkg install directxtex[dx12]:arm64-linux --recurse
./vcpkg install directxtex[openexr]:arm64-linux --recurse

vcpkg install directxtex:x64-mingw-static
vcpkg install directxtex[dx12]:x64-mingw-static --recurse
vcpkg install directxtex[tools]:x64-mingw-static --recurse

vcpkg install directxtex:x86-mingw-static
vcpkg install directxtex[dx12]:x86-mingw-static --recurse
vcpkg install directxtex[tools]:x86-mingw-static --recurse

vcpkg install directxtex[core]:x64-clangcl-dynamic
vcpkg install directxtex:x64-clangcl-dynamic --recurse
vcpkg install directxtex[tools]:x64-clangcl-dynamic --recurse
vcpkg install directxtex[dx12]:x64-clangcl-dynamic --recurse
vcpkg install directxtex:x64-clangcl-static

vcpkg install directxtex:arm64-clangcl-dynamic
vcpkg install directxtex[tools]:arm64-clangcl-dynamic --recurse 
vcpkg install directxtex:arm64-clangcl-static

vcpkg install directxtex:x64-clangcl-uwp
vcpkg install directxtex:arm64-clangcl-uwp

vcpkg install directxtex:x64-clangcl-scarlett
vcpkg install directxtex:x64-clangcl-scarlett-static
vcpkg install directxtex:x64-clangcl-xboxone
vcpkg install directxtex:x64-clangcl-xboxone-static
```

**Comment by jimwang118** [comment]
Note: I will be converting your PR to draft status. When you respond, please revert to "ready for review". That way, I can be aware that you've responded since you can't modify the tags.

**Comment by walbourn** [comment]
# UVAtlas
```
vcpkg install uvatlas:x86-windows
vcpkg install uvatlas[tools]:x86-windows --recurse
vcpkg install uvatlas[eigen]:x86-windows --recurse
vcpkg install uvatlas[spectre]:x86-windows --recurse
vcpkg install uvatlas:x86-windows-static
vcpkg install uvatlas:x86-windows-static-md

vcpkg install uvatlas:x64-windows
vcpkg install uvatlas[tools]:x64-windows --recurse
vcpkg install uvatlas[eigen]:x64-windows --recurse
vcpkg install uvatlas[spectre]:x64-windows --recurse
vcpkg install uvatlas:x64-windows-static
vcpkg install uvatlas:x64-windows-static-md

vcpkg install uvatlas:arm-windows
vcpkg install uvatlas[tools]:arm-windows --recurse
vcpkg install uvatlas[spectre]:arm-windows --recurse

vcpkg install uvatlas:arm64-windows
vcpkg install uvatlas[tools]:arm64-windows --recurse
vcpkg install uvatlas[spectre]:arm64-windows --recurse
vcpkg install uvatlas:arm64-windows-static
vcpkg install uvatlas:arm64-windows-static-md

vcpkg install uvatlas:x86-uwp
vcpkg install uvatlas:x64-uwp
vcpkg install uvatlas:arm-uwp
vcpkg install uvatlas:arm64-uwp

vcpkg install uvatlas:x64-xbox-scarlett
vcpkg install uvatlas:x64-xbox-scarlett-static
vcpkg install uvatlas:x64-xbox-xboxone
vcpkg install uvatlas:x64-xbox-xboxone-static

./vcpkg install uvatlas:x64-linux
./vcpkg install uvatlas[eigen]:x64-linux --recurse

./vcpkg install uvatlas:arm64-linux
./vcpkg install uvatlas[eigen]:arm64-linux --recurse

vcpkg install uvatlas:x64-mingw-static
vcpkg install uvatlas[tools]:x64-mingw-static --recurse

vcpkg install uvatlas:x86-mingw-static
vcpkg install uvatlas[tools]:x86-mingw-static --recurse

vcpkg install uvatlas:x64-clangcl-dynamic
vcpkg install uvatlas[tools]:x64-clangcl-dynamic --recurse
vcpkg install uvatlas[eigen]:x64-clangcl-dynamic --recurse
vcpkg install uvatlas:x64-clangcl-static

vcpkg install uvatlas:arm64-clangcl-dynamic
vcpkg install uvatlas[tools]:arm64-clangcl-dynamic --recurse
vcpkg install uvatlas:arm64-clangcl-static

vcpkg install uvatlas:x64-clangcl-uwp
vcpkg install uvatlas:arm64-clangcl-uwp

vcpkg install uvatlas:x64-clangcl-scarlett
vcpkg install uvatlas:x64-clangcl-scarlett-static
vcpkg install uvatlas:x64-xbox-xboxone
vcpkg install uvatlas:x64-xbox-xboxone-static
```

**Comment by walbourn** [comment]
# DirectX Tool Kit for DX11
```
vcpkg install directxtk:x86-windows
vcpkg install directxtk[tools]:x86-windows --recurse
vcpkg install directxtk[xaudio2-8]:x86-windows --recurse
vcpkg install directxtk[xaudio2-9]:x86-windows --recurse
vcpkg install directxtk[xaudio2redist]:x86-windows --recurse
vcpkg install directxtk[xaudio2redist]:x86-windows-static-md --recurse
vcpkg install directxtk[spectre]:x86-windows --recurse
vcpkg install directxtk:x86-windows-static
vcpkg install directxtk:x86-windows-static-md

vcpkg install directxtk:x64-windows
vcpkg install directxtk[tools]:x64-windows --recurse
vcpkg install directxtk[xaudio2-8]:x64-windows --recurse
vcpkg install directxtk[xaudio2-9]:x64-windows --recurse
vcpkg install directxtk[xaudio2redist]:x64-windows --recurse
vcpkg install directxtk[xaudio2redist]:x64-windows-static-md --recurse
vcpkg install directxtk[spectre]:x64-windows --recurse
vcpkg install directxtk:x64-windows-static
vcpkg install directxtk:x64-windows-static-md

vcpkg install directxtk:arm-windows
vcpkg install directxtk[tools]:arm-windows --recurse
vcpkg install directxtk[spectre]:arm-windows --recurse

vcpkg install directxtk:arm64-windows
vcpkg install directxtk[tools]:arm64-windows --recurse
vcpkg install directxtk[spectre]:arm64-windows --recurse
vcpkg install directxtk:arm64-windows-static
vcpkg install directxtk:arm64-windows-static-md

vcpkg install directxtk:x86-uwp
vcpkg install directxtk:x64-uwp
vcpkg install directxtk:arm-uwp
vcpkg install directxtk:arm64-uwp

vcpkg install directxtk:x64-mingw-static
vcpkg install directxtk[xaudio2redist]:x64-mingw-static --recurse
vcpkg install directxtk[tools]:x64-mingw-static --recurse

vcpkg install directxtk:x86-mingw-static
vcpkg install directxtk[xaudio2redist]:x86-mingw-static --recurse
vcpkg install directxtk[tools]:x86-mingw-static --recurse

vcpkg install directxtk:x64-clangcl-dynamic
vcpkg install directxtk[tools]:x64-clangcl-dynamic --recurse
vcpkg install directxtk[xaudio2-8]:x64-clangcl-dynamic --recurse
vcpkg install directxtk[xaudio2-9]:x64-clangcl-dynamic --recurse
vcpkg install directxtk[xaudio2redist]:x64-clangcl-dynamic --recurse
vcpkg install directxtk:x64-clangcl-static

vcpkg install directxtk:arm64-clangcl-dynamic
vcpkg install directxtk[tools]:arm64-clangcl-dynamic --recurse
vcpkg install directxtk:arm64-clangcl-static
vcpkg install directxtk:x64-clangcl-uwp
vcpkg install directxtk:arm64-clangcl-uwp
```

# DirectX Tool Kit for DX12
```
vcpkg install directxtk12[core]:x86-windows
vcpkg install directxtk12[xaudio2-9]:x86-windows --recurse
vcpkg install directxtk12[xaudio2redist]:x86-windows --recurse
vcpkg install directxtk12[xaudio2redist]:x86-windows-static-md --recurse
vcpkg install directxtk12[spectre]:x86-windows-static-md --recurse
vcpkg install directxtk12:x86-windows-static
vcpkg install directxtk12:x86-windows-static-md

vcpkg install directxtk12[core]:x64-windows
vcpkg install directxtk12[tools]:x64-windows --recurse
vcpkg install directxtk12[xaudio2-9]:x64-windows --recurse
vcpkg install directxtk12[xaudio2redist]:x64-windows --recurse
vcpkg install directxtk12[xaudio2redist]:x64-windows-static-md --recurse
vcpkg install directxtk12[spectre]:x64-windows-static-md --recurse
vcpkg install directxtk12:x64-windows-static
vcpkg install directxtk12:x64-windows-static-md

vcpkg install directxtk12:arm-windows
vcpkg install directxtk12[spectre]:arm-windows --recurse

vcpkg install directxtk12[core]:arm64-windows
vcpkg install directxtk12[tools]:arm64-windows --recurse
vcpkg install directxtk12[spectre]:arm64-windows --recurse
vcpkg install directxtk12:arm64-windows-static
vcpkg install directxtk12:arm64-windows-static-md

vcpkg install directxtk12:x86-uwp
vcpkg install directxtk12:x64-uwp
vcpkg install directxtk12:arm-uwp
vcpkg install directxtk12:arm64-uwp

vcpkg install directxtk12:x64-xbox-scarlett
vcpkg install directxtk12:x64-xbox-scarlett-static
vcpkg install directxtk12:x64-xbox-xboxone
vcpkg install directxtk12:x64-xbox-xboxone-static

vcpkg install directxtk12:x64-mingw-static
vcpkg install directxtk12[xaudio2redist]:x64-mingw-static --recurse
vcpkg install directxtk12[tools]:x64-mingw-static --recurse

vcpkg install directxtk12:x86-mingw-static
vcpkg install directxtk12[xaudio2redist]:x86-mingw-static --recurse

vcpkg install directxtk12[core]:x64-clangcl-dynamic
vcpkg install directxtk12[tools]:x64-clangcl-dynamic --recurse
vcpkg install directxtk12[xaudio2-9]:x64-clangcl-dynamic --recurse
vcpkg install directxtk12[xaudio2redist]:x64-clangcl-dynamic --recurse
vcpkg install directxtk12:x64-clangcl-static

vcpkg install directxtk12[core]:arm64-clangcl-dynamic
vcpkg install directxtk12[tools]:arm64-clangcl-dynamic --recurse
vcpkg install directxtk12:arm64-clangcl-static

vcpkg install directxtk12:x64-clangcl-uwp
vcpkg install directxtk12:arm64-clangcl-uwp

vcpkg install directxtk12:x64-clangcl-scarlett
vcpkg install directxtk12:x64-clangcl-scarlett-static
vcpkg install directxtk12:x64-clangcl-xboxone
vcpkg install directxtk12:x64-clangcl-xboxone-static
```

**Comment by walbourn** [comment]
# DXUT
```
vcpkg install dxut:x86-windows
vcpkg install dxut:x86-windows-static
vcpkg install dxut:x86-windows-static-md

vcpkg install dxut:x64-windows
vcpkg install dxut:x64-windows-static
vcpkg install dxut:x64-windows-static-md

vcpkg install dxut:arm-windows

vcpkg install dxut:arm64-windows
vcpkg install dxut:arm64-windows-static
vcpkg install dxut:arm64-windows-static-md

vcpkg install dxut:x64-mingw-static
vcpkg install dxut:x86-mingw-static

vcpkg install dxut:x64-clangcl-dynamic
vcpkg install dxut:x64-clangcl-static

vcpkg install dxut:arm64-clangcl-dynamic
vcpkg install dxut:arm64-clangcl-static
```

# Effects11
```
vcpkg install effects11:x86-windows
vcpkg install effects11:x86-windows-static
vcpkg install effects11:x86-windows-static-md

vcpkg install effects11:x64-windows
vcpkg install effects11:x64-windows-static
vcpkg install effects11:x64-windows-static-md

vcpkg install effects11:arm-windows

vcpkg install effects11:arm64-windows
vcpkg install effects11:arm64-windows-static
vcpkg install effects11:arm64-windows-static-md

vcpkg install effects11:x86-uwp
vcpkg install effects11:x64-uwp
vcpkg install effects11:arm-uwp
vcpkg install effects11:arm64-uwp

vcpkg install effects11:x64-clangcl-dynamic
vcpkg install effects11:x64-clangcl-static

vcpkg install effects11:arm64-clangcl-dynamic
vcpkg install effects11:arm64-clangcl-static

vcpkg install effects11:x64-clangcl-uwp
vcpkg install effects11:arm64-clangcl-uwp
```

**Comment by walbourn** [comment]
> I'm taking a look at **rsm-bsa** now...

The problem with *rsm-bsa* was that my CMake targets files were not properly reflecting the optional vs. required package dependencies. This have all been fixed upstream, the tag regenerated, and the portfile SHA512 values updated.

**Pull request merged**
