### PR TITLE
[7zip] Update to 24.06

### LINKED ISSUE #38764: [7zip] update to <24.05>
### Library name

7zip

### New version number

24.05

### Other information that may be useful (release notes, etc...)

https://7-zip.org/
https://www.7-zip.org/download.html
https://www.7-zip.org/history.txt
https://sourceforge.net/p/sevenzip/discussion/45797/thread/b92679e642/
https://github.com/ip7z/7zip/releases/tag/24.05

`scripts/vcpkgTools.xml` - needs to be updated too.

### PR DESCRIPTION
**Pull request by MonicaLiu0311**
Fixes #38764, update `7zip` to 24.06.

No feature needs to be tested, the usage test passed on `x64-windows`(header files found):
```
7zip provides CMake targets:

  # this is heuristically generated, and may not be correct
  find_package(7zip CONFIG REQUIRED)
  target_link_libraries(main PRIVATE 7zip::7zip)
```

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [ ] ~SHA512s are updated for each updated download.~
- [ ] ~The "supports" clause reflects platforms that may be fixed by this new version.~
- [ ] ~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~
- [ ] ~Any patches that are no longer applied are deleted from the port's directory.~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by SportsDataPlayground** [comment]
Hi there. any progress on 24.05? if doesn't like 24.05, what about 24.06? ;-)

**Comment by SportsDataPlayground** [comment]
I see already few records in scripts/ci.baseline.txt:
_7zip:arm-neon-android=fail
7zip:arm64-android=fail_
what about adding one more _7zip:x64-android=fail_, if it is so hard to build it for x64-android?

**Comment by SportsDataPlayground** [comment]
Just curious, why is this PR still in progress? btw, several hours or even day(s) on every [azure_pipelined] check is also quite annoying, isn't it? ;-)

**Comment by BillyONeal** [comment]
> Just curious, why is this PR still in progress? btw, several hours or even day(s) on every [azure_pipelined] check is also quite annoying, isn't it? ;-)

I don't know exactly but I do know @MonicaLiu0311 is out of office for a bit so I fixed the version DB.

I also checked that `vcpkg fetch 7zip` and `vcpkg fetch 7zip_msi` do the right thing.

**Review by BillyONeal — APPROVED** [review]

**Review by LilyWangLL — APPROVED** [review]

**Pull request merged**
