### PR TITLE
[drogon] Update to 1.7.4

### PR DESCRIPTION
**Pull request by an-tao**

### CODE REVIEW

**Comment by JonLiu1993** [comment]
@an-tao ,Thanks for your pr, this is the detail error log:
https://dev.azure.com/vcpkg/public/_build/results?buildId=64547&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by an-tao** [comment]
@dan-shaw Hi, do you know how to solve the failure? thanks.

**Comment by chausner** [comment]
> @chausner Hi, do you know how to solve the failure? thanks.

Not sure. I see you removed the patch about std::filesystem which should be fine because it is now part of 1.7.4. It seems another change in 1.7.4 broke it, maybe https://github.com/drogonframework/drogon/pull/1102.

**Comment by an-tao** [comment]
@JonLiu1993 would you please review this pr again? thanks.

**Comment by JonLiu1993** [comment]
@an-tao ,Have you tested the features locally?

**Review by JonLiu1993 — APPROVED** [review]

**Comment by an-tao** [comment]
> @an-tao ,Have you tested the features locally?
I've tested them on windows(x86,x64)

**Comment by BillyONeal** [comment]
Thanks!

**Pull request merged**
