### PR TITLE
[vcpkg docs] Update vcpkg_extract_source_archive.md

### PR DESCRIPTION
**Pull request by dg0yt**
- #### What does your PR fix?
  Update/extension for relevance.

### CODE REVIEW

**Comment by Cheney-W** [comment]
@BillyONeal @ras0219-msft @vicroms 
Is the `REF` parameter sure it's no longer used in `vcpkg_extract_source_archive.cmake`?

According to the following codes:
```
    if(DEFINED arg_REF)
        if(NOT arg_Z_ALLOW_OLD_PARAMETER_NAMES)
            message(FATAL_ERROR "Unexpected argument REF")
        elseif(DEFINED arg_SOURCE_BASE)
            message(FATAL_ERROR "Cannot specify both REF and SOURCE_BASE")
        else()
            string(REPLACE "/" "-" arg_SOURCE_BASE "${arg_REF}")
        endif()
    endif()
```
`REF` only works when `vcpkg_extract_source_archive_ex()` is called or `SOURCE_BASE` is not being used.
This causes an error to be reported when using `REF` in `vcpkg_extract_source_archive()`, which does not match our current documentation.

If this parameter is no longer used, then the [example](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_extract_source_archive.md#examples) in the documentation needs to be modified as well; if this parameter is still to be used, then `vcpkg_extract_source_archive.cmake`  needs to be updated.

**Review by BillyONeal — DISMISSED** [review]
/cc @ras0219-msft

**Comment by dg0yt** [comment]
@MonicaLiu0311 Done.

**Review by BillyONeal — APPROVED** [review]

**Review by ras0219-msft — APPROVED** [review]
Thanks, this looks great!

**Comment by BillyONeal** [comment]
Thanks again!

**Pull request merged**
