### PR TITLE
[angelscript] Update to 2.35.0

### LINKED ISSUE #15840: [angelscript] update to 2.35.0
Library name: angelscript

New version number: 2.35.0

### PR DESCRIPTION
**Pull request by crackedmind**
- Fixes #15840

### CODE REVIEW

**Review by JonLiu1993 — APPROVED** [review]

**Comment by JonLiu1993** [comment]
@crackedmind ,Have you tested feature "addons"?

**Comment by crackedmind** [comment]
> Hi @crackedmind ,Have you tested feature "addons"?

Sure, files are copied as expected

**Comment by JonLiu1993** [comment]
> > Hi @crackedmind ,Have you tested feature "addons"?
> 
> Sure, files are copied as expected

Ok ，thanks for your contribution

**Comment by dan-shaw** [comment]
@crackedmind Is the patch checked in to upstream?

**Comment by crackedmind** [comment]
@dan-shaw patch got from upstream :)
2.35.0 released at 5 december, patch commited at 10 december
https://sourceforge.net/p/angelscript/code/2686/tree//trunk/sdk/angelscript/source/as_module.cpp?diff=517fcf595fcbc90e9958797a:2685

**Pull request merged**
