### PR TITLE
[vcpkg baseline][poppler] Fix issue with using libcurl.

### PR DESCRIPTION
**Pull request by Hoikas**
This fixes an issue where poppler will attempt to build with libcurl. Libcurl's cmake config file does not properly set its CMake policies so certain `if()` calls fail, causing a cascade failure in the poppler. Should fix issue seen in #15200.

- What does your PR fix?
See above

- Which triplets are supported/not supported? Have you updated the CI baseline?
No change

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

### CODE REVIEW

**Comment by JackBoosY** [comment]
Can we completely solve this issue instead of simply disabling curl?

**Comment by Hoikas** [comment]
Sure. This just seemed like the quickest fix because poppler does not list curl as a dependency.

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
Ping @vicroms for merge this PR.

**Comment by ras0219-msft** [comment]
Thanks for the fix!

**Pull request merged**
