### PR TITLE
szip

### LINKED ISSUE #428: Add SZip
Hi!

It would be great if you add SZip.

Link:
http://www.hdfgroup.org/HDF5/release/cmakebuild.html

Thanks in advance!

### PR DESCRIPTION
**Pull request by albertziegenhagel**
Adds a port for Szip (https://support.hdfgroup.org/doc_resource/SZIP/)

fixes #428

### CODE REVIEW

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by alexkaratarakis** [comment]
The dynamic build ends up with two lib files (libszip.lib and szip.lib) but only one dll. I think the libszip.lib is the static flavor of the library, and thus should be removed. The static build looks good.

Is there an option to make the CMake script not build the static flavor at all in the dynamic build?
If not, then you could simply do:
```
if(VCPKG_LIBRARY_LINKAGE STREQUAL dynamic)
    file(REMOVE ${CURRENT_PACKAGES_DIR}/lib/libszip.lib ${CURRENT_PACKAGES_DIR}/debug/lib/libszip_D.lib)
endif()
```

**Comment by albertziegenhagel** [comment]
I added a patch to disable the static library in shared builds.

Just deleting the file keeps a reference to it in the szip-targets-*.cmake files and therefore makes them invalid.

**Comment by alexkaratarakis** [comment]
Good catch!
Merging, thanks for the PR!

**Pull request merged**
