### PR TITLE
[vincentlaucsb-csv-parser] New port

### LINKED ISSUE #32759: [New Port Request] <library name here>
### Library name

csv-parser

### Library description

_No response_

### Source repository URL

https://github.com/vincentlaucsb/csv-parser

### Project homepage (if different from the source repository)

_No response_

### Anything else that is useful to know when adding (such as optional features the library may have that should be included)

_No response_

### PR DESCRIPTION
**Pull request by xiaozhuai**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [x] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

Close #32759

---

The following usage test passed on x64-osx-release

```cpp
#include <iostream>
#include "csv.hpp"

int main() {
    csv::CSVFormat format;
    csv::CSVReader reader("addresses.csv", format);
    for (auto &row: reader) {
        for (auto &col: row) {
            std::cout << col.get<std::string>() << " ";
        }
        std::cout << std::endl;
    }
    return 0;
}
```

```csv
John,Doe,120 jefferson st.,Riverside, NJ, 08075
Jack,McGinnis,220 hobo Av.,Phila, PA,09119
"John ""Da Man""",Repici,120 Jefferson St.,Riverside, NJ,08075
Stephen,Tyler,"7452 Terrace ""At the Plaza"" road",SomeTown,SD, 91234
,Blankman,,SomeTown, SD, 00298
"Joan ""the bone"", Anne",Jet,"9th, at Terrace plc",Desert City,CO,00123

```

```cmake
cmake_minimum_required(VERSION 3.15)
project(test_csv_parser)

set(CMAKE_CXX_STANDARD 17)

find_package(unofficial-vincentlaucsb-csv-parser CONFIG REQUIRED)

add_executable(test_csv_parser main.cpp)
target_link_libraries(test_csv_parser PRIVATE unofficial::vincentlaucsb-csv-parser::csv)
```

### CODE REVIEW

**Comment by Cheney-W** [comment]
Port name should be `vincentlaucsb-csv-parser` instead of `csv-parser`.

Moving the PR to draft. Please set it to "ready for review" once changes have been applied.

**Comment by xiaozhuai** [comment]
> Port name should be `vincentlaucsb-csv-parser` instead of `csv-parser`.

@Cheney-W 
Done~

**Review by Cheney-W — DISMISSED** [review]

**Comment by BillyONeal** [comment]
Unfortunately several names this port wants:

```
x86-windows/debug/lib/csv.lib
x86-windows/debug/lib/csv.lib
x86-windows/include/csv/csv.hpp
x86-windows/include/csv/internal/basic_csv_parser.hpp
x86-windows/include/csv/internal/col_names.hpp
x86-windows/include/csv/internal/common.hpp
x86-windows/include/csv/internal/csv_format.hpp
x86-windows/include/csv/internal/csv_reader.hpp
x86-windows/include/csv/internal/csv_row.hpp
x86-windows/include/csv/internal/csv_stat.hpp
x86-windows/include/csv/internal/csv_utility.hpp
x86-windows/include/csv/internal/csv_writer.hpp
x86-windows/include/csv/internal/data_type.h
x86-windows/lib/csv.lib
x86-windows/share/unofficial-vincentlaucsb-csv-parser/unofficial-vincentlaucsb-csv-parser-config-debug.cmake
x86-windows/share/unofficial-vincentlaucsb-csv-parser/unofficial-vincentlaucsb-csv-parser-config-release.cmake
x86-windows/share/unofficial-vincentlaucsb-csv-parser/unofficial-vincentlaucsb-csv-parser-config.cmake
x86-windows/share/vincentlaucsb-csv-parser/copyright
x86-windows/share/vincentlaucsb-csv-parser/usage
x86-windows/share/vincentlaucsb-csv-parser/vcpkg.spdx.json
x86-windows/share/vincentlaucsb-csv-parser/vcpkg_abi_info.txt
```

are already taken by `libcsv`:

```
libcsv:x64-windows:/debug/lib/csv.lib
libcsv:x64-windows:/include/csv.h
libcsv:x64-windows:/lib/csv.lib
libcsv:x64-windows:/share/libcsv/copyright
libcsv:x64-windows:/share/libcsv/man3/csv.3
libcsv:x64-windows:/share/libcsv/vcpkg.spdx.json
libcsv:x64-windows:/share/libcsv/vcpkg_abi_info.txt
```

Borderline since they want the same directory:

```
p-ranav-csv:x64-windows:/include/csv/concurrent_queue.hpp
p-ranav-csv:x64-windows:/include/csv/dialect.hpp
p-ranav-csv:x64-windows:/include/csv/reader.hpp
p-ranav-csv:x64-windows:/include/csv/robin_hood.hpp
p-ranav-csv:x64-windows:/include/csv/writer.hpp
```

I think we need to patch the include paths and lib name?

**Comment by xiaozhuai** [comment]
@BillyONeal 

> I think we need to patch the include paths and lib name?

Sure. Here is what looks like after patched.

```
x64-osx-release/
x64-osx-release/include/
x64-osx-release/include/vincentlaucsb-csv-parser/
x64-osx-release/include/vincentlaucsb-csv-parser/csv.hpp
x64-osx-release/include/vincentlaucsb-csv-parser/internal/
x64-osx-release/include/vincentlaucsb-csv-parser/internal/basic_csv_parser.hpp
x64-osx-release/include/vincentlaucsb-csv-parser/internal/col_names.hpp
x64-osx-release/include/vincentlaucsb-csv-parser/internal/common.hpp
x64-osx-release/include/vincentlaucsb-csv-parser/internal/csv_format.hpp
x64-osx-release/include/vincentlaucsb-csv-parser/internal/csv_reader.hpp
x64-osx-release/include/vincentlaucsb-csv-parser/internal/csv_row.hpp
x64-osx-release/include/vincentlaucsb-csv-parser/internal/csv_stat.hpp
x64-osx-release/include/vincentlaucsb-csv-parser/internal/csv_utility.hpp
x64-osx-release/include/vincentlaucsb-csv-parser/internal/csv_writer.hpp
x64-osx-release/include/vincentlaucsb-csv-parser/internal/data_type.h
x64-osx-release/lib/
x64-osx-release/lib/libvincentlaucsb-csv-parser-csv.a
x64-osx-release/share/
x64-osx-release/share/unofficial-vincentlaucsb-csv-parser/
x64-osx-release/share/unofficial-vincentlaucsb-csv-parser/unofficial-vincentlaucsb-csv-parser-config-release.cmake
x64-osx-release/share/unofficial-vincentlaucsb-csv-parser/unofficial-vincentlaucsb-csv-parser-config.cmake
x64-osx-release/share/vincentlaucsb-csv-parser/
x64-osx-release/share/vincentlaucsb-csv-parser/copyright
x64-osx-release/share/vincentlaucsb-csv-parser/usage
x64-osx-release/share/vincentlaucsb-csv-parser/vcpkg.spdx.json
x64-osx-release/share/vincentlaucsb-csv-parser/vcpkg_abi_info.txt
```

**Comment by xiaozhuai** [comment]
@Cheney-W The CI seems broken, please rerun CI.

**Comment by BillyONeal** [comment]
Thanks for the new port and sorry about needing to deal with the crowded field

**Pull request merged**
