### PR TITLE
[opentelemetry-cpp] Update to 1.13.0

### LINKED ISSUE #35992: [opentelemetry-cpp] update to 1.13.0
### Library name

opentelemetry-cpp

### New version number

1.13.0

### Other information that may be useful (release notes, etc...)

https://github.com/open-telemetry/opentelemetry-cpp/releases/tag/v1.13.0

### PR DESCRIPTION
**Pull request by waywardmonkeys**
The patch to add a dependency of opentelemetry-proto on gRPC should not be needed after the upstream changes in:

https://github.com/open-telemetry/opentelemetry-cpp/pull/2268

Additionally, the "zpages" feature is removed as it is no longer present upstream after having been deprecated in a previous release.

Fixes #35992.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

Might be best to have this reviewed by someone that uses this more or who knows more about the upstream.

### CODE REVIEW

**Comment by jimwang118** [comment]
I used the following command locally: .\vcpkg.exe install opentelemetry-cpp[*] when testing the feature installation, the following error occurred.
```
F:\opentelemetry-cpp\buildtrees\opentelemetry-cpp\src\v1.13.0-18976a2470.clean\exporters\otlp\include\opentelemetry/exporters/otlp/otlp_grpc_exporter.h(61): error C2589: '(': illegal token on right side of '::'
F:\opentelemetry-cpp\buildtrees\opentelemetry-cpp\src\v1.13.0-18976a2470.clean\exporters\otlp\include\opentelemetry/exporters/otlp/otlp_grpc_exporter.h(61): error C2059: syntax error: ')'
F:\opentelemetry-cpp\buildtrees\opentelemetry-cpp\src\v1.13.0-18976a2470.clean\exporters\otlp\include\opentelemetry/exporters/otlp/otlp_grpc_exporter.h(70): warning C4003: not enough arguments for function-like macro invocation 'max'
F:\opentelemetry-cpp\buildtrees\opentelemetry-cpp\src\v1.13.0-18976a2470.clean\exporters\otlp\include\opentelemetry/exporters/otlp/otlp_grpc_exporter.h(70): error C2589: '(': illegal token on right side of '::'
F:\opentelemetry-cpp\buildtrees\opentelemetry-cpp\src\v1.13.0-18976a2470.clean\exporters\otlp\include\opentelemetry/exporters/otlp/otlp_grpc_exporter.h(70): error C2059: syntax error: ')'
F:\opentelemetry-cpp\buildtrees\opentelemetry-cpp\src\v1.13.0-18976a2470.clean\exporters\otlp\include\opentelemetry/exporters/otlp/otlp_grpc_exporter.h(61): error C2062: type 'unknown-type' unexpected
F:\opentelemetry-cpp\buildtrees\opentelemetry-cpp\src\v1.13.0-18976a2470.clean\exporters\otlp\include\opentelemetry/exporters/otlp/otlp_grpc_exporter.h(61): error C2059: syntax error: ')'
F:\opentelemetry-cpp\buildtrees\opentelemetry-cpp\src\v1.13.0-18976a2470.clean\exporters\otlp\include\opentelemetry/exporters/otlp/otlp_grpc_exporter.h(70): error C2059: syntax error: 'default argument'
F:\opentelemetry-cpp\buildtrees\opentelemetry-cpp\src\v1.13.0-18976a2470.clean\exporters\otlp\include\opentelemetry/exporters/otlp/otlp_grpc_exporter.h(70): error C2059: syntax error: ')'
F:\opentelemetry-cpp\buildtrees\opentelemetry-cpp\src\v1.13.0-18976a2470.clean\exporters\otlp\include\opentelemetry/exporters/otlp/otlp_grpc_exporter.h(89): error C2059: syntax error: 'member initializer'
F:\opentelemetry-cpp\buildtrees\opentelemetry-cpp\src\v1.13.0-18976a2470.clean\exporters\otlp\include\opentelemetry/exporters/otlp/otlp_grpc_exporter.h(92): error C2059: syntax error: 
```
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/13815355/install-x64-windows-dbg-out.log)

**Comment by jimwang118** [comment]
Note: I will be converting your PR to draft status. The above suggested changes are only recommendations. If you are willing to adopt them, please click "ready for review" after making the modifications. If you do not wish to make any changes, please click "ready for review" directly. That way, I can be aware that you've responded since you can't modify the tags.

**Comment by waywardmonkeys** [comment]
Updated again to include https://github.com/open-telemetry/opentelemetry-cpp/pull/2449 to fix one more `NOMINMAX` problem.

**Comment by jimwang118** [comment]
All features passed with following triplets:

```
x86-windows
x64-windows
```

**Review by BillyONeal — APPROVED** [review]

**Comment by BillyONeal** [comment]
The android build lab appears to be broken and I only made whitespace changes so I'll merge this if all other platforms come back OK

**Pull request merged**
