### PR TITLE
[mimalloc] update to 2.1.7

### PR DESCRIPTION
**Pull request by nickdademo**
- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [X] SHA512s are updated for each updated download.
- [ ] ~The "supports" clause reflects platforms that may be fixed by this new version.~
- [ ] ~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~
- [X] Any patches that are no longer applied are deleted from the port's directory.
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by nickdademo** [comment]
Not sure on the exact cause of the CI failures yet... If anyone has hints, please let me know :)

**Comment by dg0yt** [comment]
There is a test port, and you can install it locally with 
~~~
vcpkg install --overlay-ports=scripts/test-ports vcpkg-ci-mimalloc
~~~

For x64-linux, the CI logs show:
~~~
undefined reference to `_mi_page_malloc_zero(mi_heap_s*, mi_page_s*, unsigned long, bool)'
~~~

The test port pulls source code from the mimalloc repo, so you must also update it now.

**Comment by dg0yt** [comment]
Still failing with 
~~~
page.c:(.text+0x25fb): undefined reference to `_mi_page_malloc_zero(mi_heap_s*, mi_page_s*, unsigned long, bool)'
~~~

**Comment by nickdademo** [comment]
> Still failing with
> 
> ```
> page.c:(.text+0x25fb): undefined reference to `_mi_page_malloc_zero(mi_heap_s*, mi_page_s*, unsigned long, bool)'
> ```

Are you able to post a link to this log? I didn't manage to find it :) Thanks!

**Comment by dg0yt** [comment]
You get to Azure pipeline by following the details links, then go to the assets, then find the download in the three dots on the right side when you hover the failure logs line.
https://github.com/microsoft/vcpkg/discussions/31357

It is a new mimalloc function, and I wonder if it is related to its `extern inline` state. The command line doesn't set a C standard.

**Comment by Cheney-W** [comment]
Moving the PR to draft. Please set it to "ready for review" once the CI test passed.

**Comment by VladimirShaleev** [comment]
Hello! From the log, it appears that the issue is related to the fact that the source code is being compiled by the `C++` compiler with optimization **enabled**. When compiling with optimization, `inline` functions are inlined, and symbols are removed (translation unit `alloc.c`) for C++ clang and gcc. As a result, in another translation unit (in this case, `page.c`), the symbol was not found. 

https://godbolt.org/z/xPEc6a5qs
https://godbolt.org/z/a4Gzo9jrY

Most likely this is a `mimalloc` error. Which went unnoticed, due to the fact that release assemblies are not created for C++, but only debug ones:

CI

I think it’s worth open an issue in the `mimalloc` repository.

To solve the current problem, the obvious solution would be to apply patch. Removing the `inline` keyword from a file `alloc.c`

https://github.com/microsoft/mimalloc/blob/v2.1.7/src/alloc.c#L31

At least it seems to me that everything points to this.

**Comment by VladimirShaleev** [comment]
I see that in version `2.1.7` they forgot to get the address of `_mi_page_malloc_zero` function:

https://github.com/microsoft/mimalloc/blob/v2.1.7/src/alloc.c#L584-L598

This means that the optimizing C++ compiler will easily remove this symbol from the translation unit (if the address for the inline function was not get, then there is no need to define for it during optimization, so that it can be call).

This has already been fixed in the dev version:

https://github.com/microsoft/mimalloc/blob/dev/src/alloc.c#L587

https://github.com/microsoft/mimalloc/commit/0c322c556664563eea9a13b54dc7942b492d87c3

Therefore, a new simple solution: apply the patch in this port exactly in this place

**Comment by VladimirShaleev** [comment]
Actually, I came with a small request. When using the port, I noticed in the `usage` of the port there is a typo:

https://github.com/microsoft/vcpkg/blob/master/ports/mimalloc/usage#L4

missing closing angle bracket.

It would be great if the typo in this PR was fixed.

If you have time and desire, need to correct this line with:

```cmake
target_link_libraries(main PRIVATE $<IF:$<TARGET_EXISTS:mimalloc-static>,mimalloc-static,mimalloc)
```

on the:

```cmake
target_link_libraries(main PRIVATE $<IF:$<TARGET_EXISTS:mimalloc-static>,mimalloc-static,mimalloc>)
```

**Review by Cheney-W — APPROVED** [review]

**Pull request merged**
