### PR TITLE
[libmad] Fix libmad header for non-x86 MSVC targets

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by janisozaur** [comment]
The differences between `mad.h` and `msvc++/mad.h` are virtually non-existent.

```diff
--- mad.h	2019-11-11 23:42:12.918310412 +0100
+++ msvc++/mad.h	2004-01-23 10:36:03.000000000 +0100
@@ -33,7 +33,7 @@
 # define SIZEOF_LONG_LONG 8
 
 
-/* Id: version.h,v 1.26 2004/01/23 09:41:33 rob Exp */
+/* Id: version.h,v 1.24 2003/05/27 22:40:37 rob Exp */
 
 # ifndef LIBMAD_VERSION_H
 # define LIBMAD_VERSION_H
@@ -51,7 +51,7 @@
 				MAD_VERSION_STRING(MAD_VERSION_PATCH)  \
 				MAD_VERSION_EXTRA
 
-# define MAD_PUBLISHYEAR	"2000-2004"
+# define MAD_PUBLISHYEAR	"2000-2003"
 # define MAD_AUTHOR		"Underbit Technologies, Inc."
 # define MAD_EMAIL		"info@underbit.com"
 
@@ -62,7 +62,7 @@
 
 # endif
 
-/* Id: fixed.h,v 1.38 2004/02/17 02:02:03 rob Exp */
+/* Id: fixed.h,v 1.36 2003/05/28 04:36:00 rob Exp */
 
 # ifndef LIBMAD_FIXED_H
 # define LIBMAD_FIXED_H
@@ -253,22 +253,7 @@
 	    : "cc");  \
        __result;  \
     })
-#   elif defined(OPT_INTEL)
-/*
- * Alternate Intel scaling that may or may not perform better.
- */
-#    define mad_f_scale64(hi, lo)  \
-    ({ mad_fixed_t __result;  \
-       asm ("shrl %3,%1\n\t"  \
-	    "shll %4,%2\n\t"  \
-	    "orl %2,%1"  \
-	    : "=rm" (__result)  \
-	    : "0" (lo), "r" (hi),  \
-	      "I" (MAD_F_SCALEBITS), "I" (32 - MAD_F_SCALEBITS)  \
-	    : "cc");  \
-       __result;  \
-    })
-#   else
+#    else
 #    define mad_f_scale64(hi, lo)  \
     ({ mad_fixed_t __result;  \
        asm ("shrdl %3,%2,%1"  \
@@ -543,7 +528,7 @@
 
 # endif
 
-/* Id: bit.h,v 1.12 2004/01/23 09:41:32 rob Exp */
+/* Id: bit.h,v 1.11 2003/05/27 22:40:36 rob Exp */
 
 # ifndef LIBMAD_BIT_H
 # define LIBMAD_BIT_H
@@ -572,7 +557,7 @@
 
 # endif
 
-/* Id: timer.h,v 1.16 2004/01/23 09:41:33 rob Exp */
+/* Id: timer.h,v 1.15 2003/05/27 22:40:37 rob Exp */
 
 # ifndef LIBMAD_TIMER_H
 # define LIBMAD_TIMER_H
@@ -654,7 +639,7 @@
 
 # endif
 
-/* Id: stream.h,v 1.20 2004/02/05 09:02:39 rob Exp */
+/* Id: stream.h,v 1.18 2003/05/27 22:40:37 rob Exp */
 
 # ifndef LIBMAD_STREAM_H
 # define LIBMAD_STREAM_H
@@ -680,7 +665,6 @@
   MAD_ERROR_BADCRC	   = 0x0201,	/* CRC check failed */
   MAD_ERROR_BADBITALLOC	   = 0x0211,	/* forbidden bit allocation value */
   MAD_ERROR_BADSCALEFACTOR = 0x0221,	/* bad scalefactor index */
-  MAD_ERROR_BADMODE        = 0x0222,	/* bad bitrate/mode combination */
   MAD_ERROR_BADFRAMELEN	   = 0x0231,	/* bad frame length */
   MAD_ERROR_BADBIGVALUES   = 0x0232,	/* bad big_values count */
   MAD_ERROR_BADBLOCKTYPE   = 0x0233,	/* reserved block_type */
@@ -743,7 +727,7 @@
 
 # endif
 
-/* Id: frame.h,v 1.20 2004/01/23 09:41:32 rob Exp */
+/* Id: frame.h,v 1.19 2003/05/27 22:40:36 rob Exp */
 
 # ifndef LIBMAD_FRAME_H
 # define LIBMAD_FRAME_H
@@ -840,7 +824,7 @@
 
 # endif
 
-/* Id: synth.h,v 1.15 2004/01/23 09:41:33 rob Exp */
+/* Id: synth.h,v 1.14 2003/05/27 22:40:37 rob Exp */
 
 # ifndef LIBMAD_SYNTH_H
 # define LIBMAD_SYNTH_H
@@ -889,7 +873,7 @@
 
 # endif
 
-/* Id: decoder.h,v 1.17 2004/01/23 09:41:32 rob Exp */
+/* Id: decoder.h,v 1.16 2003/05/27 22:40:36 rob Exp */
 
 # ifndef LIBMAD_DECODER_H
 # define LIBMAD_DECODER_H
```

**Comment by janisozaur** [comment]
The CI reports errors such as:
```
Starting package 1/396: libodb:x86-windows
Building package libodb[core]:x86-windows...
Using cached binary package: C:\vsts\_work\2\s\archives\4c\4cbe30cf8502cd1abcc762ab9638cd2a1e65868e.zip
Error: while parsing the Binary Paragraph for libodb:x86-windows
Error: There are invalid fields in the control file of libodb:x86-windows
The following fields were not expected:

    Type

This is the list of valid fields (case-sensitive): 

    Source
    Version
    Description
    Maintainer
    Build-Depends
    Homepage
    Type
```
which is quite bogus and doesn't seem related to this PR.

**Comment by JackBoosY** [comment]
Yes, see #8949.

**Review by cbezault — APPROVED** [review]

**Review by JackBoosY — APPROVED** [review]

**Pull request merged**
