### PR TITLE
[sdl2] Update to 2.0.18

### LINKED ISSUE #22290: [SDL2] update to <2.0.18>
Library name: SDL2

New version number: 2.0.18

Other information that may be useful (release notes, etc...)
https://www.libsdl.org/download-2.0.php

### LINKED ISSUE #22536: imgui[core,sdl2-renderer-binding] build failure
**Host Environment**
- OS: Windows 10 2004
- Compiler: MSVC

**To Reproduce**
`./vcpkg install imgui[core,sdl2-renderer-binding]`

**Failure logs** 

```
C:\w\vcpkg\buildtrees\imgui\src\v1.86-7944920afc.clean\backends\imgui_impl_sdlrenderer.cpp(37): fatal error C1189: #error:  This backend requires SDL 2.0.17+ because of SDL_RenderGeometry() function
```

**Additional context**

The current version of SDL2 in vcpkg is 2.0.16, but imgui requires SDL 2.0.17+. Perhaps this will be fixed by #22290.

### PR DESCRIPTION
**Pull request by crackedmind**
Update sdl2 to 2.0.18
Patches 3 and 4 removed, because this now in upstream.

- #### What does your PR fix?  
Just update

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
All, no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  yes

### CODE REVIEW

**Comment by LilyWangLL** [comment]
@crackedmind Thanks for your PR. Now sdl2 build failed with the following error on UWP. could you continue to fix it?
```
D:\buildtrees\sdl2\src\ase-2.0.18-6afe4b495e.clean\src\stdlib\SDL_string.c(734,12): error C4996: '_strupr': This function or variable may be unsafe. Consider using _strupr_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\buildtrees\sdl2\x64-uwp-dbg\SDL2.vcxproj]
     4>D:\buildtrees\sdl2\src\ase-2.0.18-6afe4b495e.clean\include\SDL_stdinc.h(88,1): warning C4005: '_USE_MATH_DEFINES': macro redefinition (compiling source file D:\buildtrees\sdl2\src\ase-2.0.18-6afe4b495e.clean\src\video\SDL_RLEaccel.c) [D:\buildtrees\sdl2\x64-uwp-dbg\SDL2.vcxproj]
       D:\buildtrees\sdl2\src\ase-2.0.18-6afe4b495e.clean\src\video\SDL_RLEaccel.c : message : see previous definition of '_USE_MATH_DEFINES' [D:\buildtrees\sdl2\x64-uwp-dbg\SDL2.vcxproj]
     4>D:\buildtrees\sdl2\src\ase-2.0.18-6afe4b495e.clean\src\stdlib\SDL_string.c(749,12): error C4996: '_strlwr': This function or variable may be unsafe. Consider using _strlwr_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [D:\buildtrees\sdl2\x64-uwp-dbg\SDL2.vcxproj]
     4>D:\buildtrees\sdl2\src\ase-2.0.18-6afe4b495e.clean\src\stdlib\SDL_string.c(828,12): error C4996: 'itoa': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _itoa. See online help for details. [D:\buildtrees\sdl2\x64-uwp-dbg\SDL2.vcxproj]
         SDL_fillrect.c
```

**Comment by crackedmind** [comment]
Sure, just trying to figure out what happens between 2.0.16 and 2.0.18
I found one problem with xinput and fixed it locally, i want to send pr in upstream before.

**Comment by flibitijibibo** [comment]
@crackedmind Just as a heads up, we expect SDL 2.0.20 to be out in less than 2 weeks, so we'll need that PR ASAP. It doesn't have to be pretty at this point, just needs to be working.

**Comment by LilyWangLL** [comment]
@crackedmind Does this PR has any update?

**Comment by flibitijibibo** [comment]
This PR has been obsoleted by #22586

**Comment by LilyWangLL** [comment]
Closing this PR since it seems that no progress is being made. PR#22586 has same change with this PR.

**Pull request closed without merging**
