### PR TITLE
[Many ports] Add licenses to manifests of various ports

### PR DESCRIPTION
**Pull request by chausner**
**Describe the pull request**

- #### What does your PR fix?
  This adds the `license` attribute to various manifests where it is currently missing. Only those ports are updated that could be linked to a GitHub repository where license information is recognized by GitHub.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  No changes, Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

### CODE REVIEW

**Comment by chausner** [comment]
Let me know if there is a better way to add this information. If it helps, I can also split this PR up into multiple smaller ones.

**Comment by Thomas1664** [comment]
Although I like the idea I think that's a waste of CI time because it triggers at least a quarter world rebuild. Furthermore, this invalidates every binary cache that customers have. And all of this just to add license information?! If you would replace `vcpkg_configure_cmake`, this would at least make configure slightly faster and therefore actually a more useful reason to rebuild so many ports.
The current approach of adding license every time a port is modified is more CI/ cost effective, although it might be annoying.

**Comment by Neumann-A** [comment]
Yeah I also think it is better to add the licenses on port update. Having a complete list of which port has which license would be great though. Makes it much easier to add the license on update.

**Comment by dg0yt** [comment]
@chausner Did you get the information programmatically? Maybe it would be a useful addition to the PR suggestions GH action.

In the end, it really needs to be reviewed carefully, per port.
- Are there exceptions for some parts of the code?
- Are there are alternative licenses?
- Does LGPL-3.0 mean LGPL-3.0-only or LGPL-3.0-or-later?

**Comment by chausner** [comment]
> Although I like the idea I think that's a waste of CI time because it triggers at least a quarter world rebuild. Furthermore, this invalidates every binary cache that customers have. 

That's a fair point that I didn't consider. 

> @chausner Did you get the information programmatically? Maybe it would be a useful addition to the PR suggestions GH action.
> 
> In the end, it really needs to be reviewed carefully, per port.

Yes, I wrote a script that finds ports based on GitHub repos and uses the GitHub API to retrieve the SPDX identifier of the license. I am not sure how GitHub detects licenses but I assume it looks for common license files (`LICENSE`, `COPYING`, etc.) and checks if they match a template.

So the process is certainly not always 100% correct (as you say, there can be multiple licenses sometimes or exceptions) but the same is probably true when users search for and add this information. There can always be mistakes. I thought retrieving this information in an automatic way might be good enough and it saves people from having to gather this information manually.

**Comment by chausner** [comment]
> If you would replace vcpkg_configure_cmake, this would at least make configure slightly faster and therefore actually a more useful reason to rebuild so many ports.

I have seen with some ports that switching from `vcpkg_configure_cmake` to `vcpkg_cmake_configure` is not always safe and they broke after updating. So blindly updating ports might be a bit risky.

However, another addition that we could safely make is setting the `homepage` attribute in the manifest to the GitHub URL, if not already present.

**Comment by strega-nil-ms** [comment]
Discussed in the Thursday meeting:

I do not want to take a PR that changes 300 ports at once; we'd love it if we could integrate the license checker into CI, on the other hand. @chausner can you PR that, or at least updload your script so that we can do so?

**Comment by chausner** [comment]
> I do not want to take a PR that changes 300 ports at once; we'd love it if we could integrate the license checker into CI, on the other hand. @chausner can you PR that, or at least upload your script so that we can do so?

Okay fine, I'll attach the script I used and will close this PR then. The parsing of the GitHub URL from CMakeLists.txt is a bit crude and works for the standard cases but fails if the CMake script does something special, so it probably would need to be made more robust before being added to CI.

[LookupLicenses.zip](https://github.com/microsoft/vcpkg/files/8515742/LookupLicenses.zip)

**Comment by autoantwort** [comment]
I tried to execute it locally, but there is no command `Get-GitHubRepository`. Do you know what I have to do to make it available?

**Comment by autoantwort** [comment]
[vcpkg_licenses.json.txt](https://github.com/microsoft/vcpkg/files/9667115/vcpkg_licenses.json.txt)

Is a summary of what vcpkg has and what github and the spdx online tool found.

**Pull request closed without merging**
