### PR TITLE
Fix Android Build for AWS

### PR DESCRIPTION
**Pull request by ahmedyarub**
**Describe the pull request**
Adds toolchain chaining to external builds

- What does your PR fix? Fixes #
Fixes Android builds. Same solution can be used in the future for any cross-platform builds.

- Which triplets are supported/not supported? Have you updated the CI baseline?
x64-Android

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

### CODE REVIEW

**Comment by NancyLi1013** [comment]
Hi @ahmedyarub 

Could you please execute the command  `vcpkg x-add-version aws-sdk-cpp` first?

```
Found the following errors:
Error: While reading versions for port aws-sdk-cpp from file: C:\a\1\s\port_versions\a-\aws-sdk-cpp.json
       File declares version `1.8.83#5` with SHA: 471e4ba73dcb43a31ebd0c460b298fb38b1f5625
       But local port with the same verion has a different SHA: bfc729671845a82f9c592a234f0daeacdde8daea
       Please update the port's version fields and then run:

           vcpkg x-add-version aws-sdk-cpp
```

**Review by NancyLi1013 — COMMENTED** [review]
It seems like you updated many formats, which are not related with your changes. Could you please revert these?

**Comment by ahmedyarub** [comment]
I think that I'll be creating a new PR. For some reason Windows + CLion cannot detect the formatting changes!

**Comment by ahmedyarub** [comment]
Superseded by https://github.com/microsoft/vcpkg/pull/15725

**Pull request closed without merging**
