### PR TITLE
Update harfbuzz to 1.3.4

### PR DESCRIPTION
**Pull request by ebraminio**
The needed local patches are now upstreamed thus no longer needed.

Also Uniscribe backend is no longer default enabled so almost no lib is needed to be linked.

### CODE REVIEW

**Comment by ebraminio** [comment]
@vlj please take a look as I didn't test it on a Windows machine yet.

**Comment by ebraminio** [comment]
This seems need another patch [on upstream](https://github.com/behdad/harfbuzz/pull/356), closing this for now till next release of harfbuzz.

**Comment by ebraminio** [comment]
Now this is ready to merge.

**Comment by ras0219-msft** [comment]
Thanks!

**Pull request merged**
