### PR TITLE
[curl] fix curl find_package

### PR DESCRIPTION
**Pull request by msclock**
**Describe the pull request**

- #### What does your PR fix?
  Fix `find_package(CURL CONFIG REQUIRED)`can't find `CURLConfig.cmake` because of case sensitive on linux

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  No, unchanged.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
   Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
   Yes

- #### If you have added/updated a port: Have you run ./vcpkg x-add-version --all and committed the result?
   Yes

### CODE REVIEW

**Comment by msclock** [comment]
@microsoft-github-policy-service agree

**Comment by dg0yt** [comment]
Thanks for your contribution. But this change is invalid. `CURL` is the only valid package name, and it works as is in module mode and in config mode.

(If project CURL would want to support arbitrary case, they could have chosen to install `curl-config.cmake`.)

**Comment by msclock** [comment]
> Thanks for your contribution. But this change is invalid. `CURL` is the only valid package name, and it works as is in module mode and in config mode.
> 
> (If project CURL would want to support arbitrary case, they could have chosen to install `curl-config.cmake`.)

@dg0yt 
Thank you for answering, I found the relevant information as follows:
https://github.com/microsoft/vcpkg/blob/0d382380b9dbfd2e13afa37fc92092c5e1456f31/scripts/buildsystems/vcpkg.cmake#L783
https://github.com/microsoft/vcpkg/blob/0d382380b9dbfd2e13afa37fc92092c5e1456f31/ports/curl/vcpkg-cmake-wrapper.cmake#L11

Because file names are case-sensitive on linux, find_package(CURL CONFIG REQUIRED) is required to find curlConfig.cmake or curl-config.cmake in the configuration above. I will give feedback to curl community later.
```
[cmake] Not searching for unused variables given on the command line.
[cmake] -- VCPKG-Info: CMAKE_MAP_IMPORTED_CONFIG_MINSIZEREL set to MinSizeRel;Release;
[cmake] -- VCPKG-Info: CMAKE_MAP_IMPORTED_CONFIG_RELWITHDEBINFO set to RelWithDebInfo;Release;
[cmake] CMake Error at external/vcpkg/installed/x64-linux/share/curl/vcpkg-cmake-wrapper.cmake:12 (_find_package):
[cmake]   Could not find a package configuration file provided by "curl" with any of
[cmake]   the following names:
[cmake] 
[cmake]     curlConfig.cmake
[cmake]     curl-config.cmake
[cmake] 
[cmake]   Add the installation prefix of "curl" to CMAKE_PREFIX_PATH or set
[cmake]   "curl_DIR" to a directory containing one of the above files.  If "curl"
[cmake]   provides a separate development package or SDK, be sure it has been
[cmake]   installed.
[cmake] Call Stack (most recent call first):
[cmake]   external/vcpkg/scripts/buildsystems/vcpkg.cmake:797 (include)
[cmake]   cmake/monitor.cmake:14 (find_package)
[cmake]   CMakeLists.txt:29 (include)
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
```

**Comment by msclock** [comment]
@dg0yt The name here in CURL does not conform to the case-insensitive lookup rules of find_package. Please refer to https://github.com/curl/curl/issues/10229. 
But the best way to adapt here is in the file vcpkg-cmake-wrapper.cmake.

https://github.com/microsoft/vcpkg/blob/0d382380b9dbfd2e13afa37fc92092c5e1456f31/ports/curl/vcpkg-cmake-wrapper.cmake#L10-L11

**Comment by Neumann-A** [comment]
@msclock: Your find_package call is wrong. End of story. It has to be `find_package(CURL)` due to `CURLConfig.cmake` upstream made it case sensitive by not using `curl-config.cmake` instead. 

> The name here in CURL does not conform to the case-insensitive lookup rules of find_package

To be clear. This is not a vcpkg issue that is a CURL issue. 
Also why should it even conform to case-insensitive lookup? (its not a rule it is just an implementation detail of cmake.)

**Comment by msclock** [comment]
Oh!! 
It's my fault. Thanks for answering the questions. 
I will close the relevant questions later. 
Thank you again for your tolerance and solution.

**Pull request closed without merging**
