### PR TITLE
[dimcli] Add supports field instead of written in ci.baseline, disable testing, support osx

### PR DESCRIPTION
**Pull request by JackBoosY**
This port doesn't support osx officially:
```
  6 FAILED: CMakeFiles/ostrm.dir/tests/ostrm/ostrmtest.cpp.o
  7 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DDIMCLI_LIB_KEEP_MACROS -I/Users/vcpkg/Documents/vcpkg/vcpkg/buildtrees/dimcli/src/be1840feae-eb4a4de173/libs -fPIC -g -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/    SDKs/MacOSX11.3.sdk -std=gnu++11 -MD -MT CMakeFiles/ostrm.dir/tests/ostrm/ostrmtest.cpp.o -MF CMakeFiles/ostrm.dir/tests/ostrm/ostrmtest.cpp.o.d -o CMakeFiles/ostrm.dir/tests/ostrm/ostrmtest.cpp.o -c /Users/vcpkg/Documents/vcpkg/vcpkg/buildtrees/dimcli/src/be1840feae-eb4a4de173/tests/ostrm/ostrmtest.cpp
  8 /Users/vcpkg/Documents/vcpkg/vcpkg/buildtrees/dimcli/src/be1840feae-eb4a4de173/tests/ostrm/ostrmtest.cpp:43:28: error: expected ';' in 'for' statement specifier
  9     for (auto i = 0; i < 10'000'000; ++i) {
 10                            ^
 11 /Users/vcpkg/Documents/vcpkg/vcpkg/buildtrees/dimcli/src/be1840feae-eb4a4de173/tests/ostrm/ostrmtest.cpp:43:28: warning: multi-character character constant [-Wmultichar]
 12 /Users/vcpkg/Documents/vcpkg/vcpkg/buildtrees/dimcli/src/be1840feae-eb4a4de173/tests/ostrm/ostrmtest.cpp:43:28: warning: expression result unused [-Wunused-value]
 13     for (auto i = 0; i < 10'000'000; ++i) {
 14                            ^~~~~
 15 /Users/vcpkg/Documents/vcpkg/vcpkg/buildtrees/dimcli/src/be1840feae-eb4a4de173/tests/ostrm/ostrmtest.cpp:43:33: error: expected ')'
 16     for (auto i = 0; i < 10'000'000; ++i) {
 17                                 ^
 18 /Users/vcpkg/Documents/vcpkg/vcpkg/buildtrees/dimcli/src/be1840feae-eb4a4de173/tests/ostrm/ostrmtest.cpp:43:9: note: to match this '('
 19     for (auto i = 0; i < 10'000'000; ++i) {
 20         ^
 21 /Users/vcpkg/Documents/vcpkg/vcpkg/buildtrees/dimcli/src/be1840feae-eb4a4de173/tests/ostrm/ostrmtest.cpp:43:41: error: expected ';' after expression
 22     for (auto i = 0; i < 10'000'000; ++i) {
 23                                         ^
 24                                         ;
 25 /Users/vcpkg/Documents/vcpkg/vcpkg/buildtrees/dimcli/src/be1840feae-eb4a4de173/tests/ostrm/ostrmtest.cpp:43:40: error: use of undeclared identifier 'i'
 26     for (auto i = 0; i < 10'000'000; ++i) {
 27                                        ^
 28 /Users/vcpkg/Documents/vcpkg/vcpkg/buildtrees/dimcli/src/be1840feae-eb4a4de173/tests/ostrm/ostrmtest.cpp:43:41: error: expected expression
 29     for (auto i = 0; i < 10'000'000; ++i) {
 30                                         ^
```

Related: #22570.

### CODE REVIEW

**Comment by autoantwort** [comment]
It does support osx, but it required c++11

**Comment by JackBoosY** [comment]
> It does support osx, but it required c++11

Add 11 or 14 doesn't resolve this issue.

**Review by JonLiu1993 — APPROVED** [review]

**Comment by autoantwort** [comment]
With the following patch is also compiles on osx:
```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 509e634..07ba36f 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -261,6 +261,7 @@ function(add_lib_project tgt srcdir)
         set_target_properties(${tgt} PROPERTIES EXCLUDE_FROM_ALL false)
     endif()
     set_target_properties(${tgt} PROPERTIES FOLDER libs)
+    target_compile_features(${tgt} PUBLIC cxx_std_17)
     set_pch(${tgt} ${srcdir})
     if(INSTALL_LIBS)
         file(GLOB incls LIST_DIRECTORIES false

```

**Comment by JackBoosY** [comment]
@autoantwort As you can see, dimcli upstream already added cxx17 in the configure file, but it requires the gcc version which the users may not have.

**Comment by autoantwort** [comment]
Huh, I am compiling the port with c++17 and clang without problems

**Comment by JackBoosY** [comment]
> Huh, I am compiling the port with c++17 and clang without problems

It's required the gcc version, which gcc version do you use?

**Comment by autoantwort** [comment]
Apple Clang 13

**Comment by autoantwort** [comment]
> It's required the gcc version, which gcc version do you use?

Why do you think that?

**Comment by JackBoosY** [comment]
> Apple Clang 13

```cmake
elseif(CMAKE_CXX_COMPILER_ID STREQUAL Clang)
    if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS "5")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++1z")
    else()
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++2a")
    endif()
```
Can you please check this compiler flag whether exists in the install log?

**Comment by autoantwort** [comment]
They don't exist in the install log

**Comment by JackBoosY** [comment]
> They don't exist in the install log

Yeah, that's what I think about. The user's compiler may not match the requirement which the upstream made, so I disabled on OSX.

**Comment by autoantwort** [comment]
> The user's compiler may not match the requirement which the upstream made, so I disabled on OSX.

But that has nothing to do with osx. If I use "normal" clang or gcc on osx it works without problems.

**Comment by strega-nil-ms** [comment]
@JackBoosY this should just change

```cmake
elseif(CMAKE_CXX_COMPILER_ID STREQUAL Clang)
    if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS "5")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++1z")
    else()
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++2a")
    endif()
```

to

```cmake
elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS "5")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++1z")
    else()
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++2a")
    endif()
```

it's pretty trivial to fix, so I'd rather just do that.

**Comment by strega-nil-ms** [comment]
Cool, thanks!

**Pull request merged**
