### PR TITLE
[argparse] bump version to 2.9

### PR DESCRIPTION
**Pull request by marcovc**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by marcovc** [comment]
Sorry what do you mean by EOL?

**Comment by MonicaLiu0311** [comment]
> Sorry what do you mean by EOL?

End of line.
image

**Comment by marcovc** [comment]
I guess the initial file was submitted in a windows OS and now I am on a mac. Is this a problem?

**Comment by MonicaLiu0311** [comment]
This file originally ended with `CRLF`, but now it ends with `LF`, which will generate unnecessary modification records, just like the current performance of `portfile.cmake`.

image

Many editors can modify EOF, just submit it after modification.

**Review by MonicaLiu0311 — APPROVED** [review]

**Pull request merged**
