### PR TITLE
Update vcpkg-tool to 2023-03-22.

### PR DESCRIPTION
**Pull request by BillyONeal**
https://github.com/microsoft/vcpkg-tool/releases/tag/2023-03-22

### CODE REVIEW

**Comment by autoantwort** [comment]
I am really interested if https://github.com/microsoft/vcpkg-tool/pull/957 will change to quality of the reported issues

**Review by vicroms — APPROVED** [review]

**Review by ras0219-msft — APPROVED** [review]

**Comment by BillyONeal** [comment]
```
REGRESSION: vowpal-wabbit:x64-windows-static-md failed with FILE_CONFLICTS. If expected, add vowpal-wabbit:x64-windows-static-md=fail to C:\a\2\s\scripts\azure-pipelines/../ci.baseline.txt.
REGRESSION: vowpal-wabbit:x64-windows-static failed with FILE_CONFLICTS. If expected, add vowpal-wabbit:x64-windows-static=fail to C:\a\2\s\scripts\azure-pipelines/../ci.baseline.txt.
REGRESSION: vowpal-wabbit:x64-windows failed with FILE_CONFLICTS. If expected, add vowpal-wabbit:x64-windows=fail to C:\a\2\s\scripts\azure-pipelines/../ci.baseline.txt.
REGRESSION: vowpal-wabbit:x64-osx failed with FILE_CONFLICTS. If expected, add vowpal-wabbit:x64-osx=fail to /Users/vagrant/Data/work/2/s/scripts/azure-pipelines/../ci.baseline.txt.
REGRESSION: vowpal-wabbit:x64-linux failed with FILE_CONFLICTS. If expected, add vowpal-wabbit:x64-linux=fail to /agent/_work/2/s/scripts/azure-pipelines/../ci.baseline.txt.
```

Should be fixed by https://github.com/microsoft/vcpkg/commit/bc671eb900ae54711fc6ebd3203e3fc4d585a140

These are also broken in recent CI run: https://dev.azure.com/vcpkg/public/_build/results?buildId=87214

```
REGRESSION: vcpkg-ci-openimageio:x64-linux cascaded, but it is required to pass. (/agent/_work/1/s/scripts/azure-pipelines/../ci.baseline.txt).
REGRESSION: vcpkg-ci-llvm:x64-windows-static-md cascaded, but it is required to pass. (C:\a\1\s\scripts\azure-pipelines/../ci.baseline.txt).
REGRESSION: vcpkg-ci-llvm:x64-windows cascaded, but it is required to pass. (C:\a\1\s\scripts\azure-pipelines/../ci.baseline.txt).
REGRESSION: shogun:x64-linux failed with BUILD_FAILED. If expected, add shogun:x64-linux=fail to /agent/_work/1/s/scripts/azure-pipelines/../ci.baseline.txt.
REGRESSION: qca:arm64-windows failed with BUILD_FAILED. If expected, add qca:arm64-windows=fail to C:\a\1\s\scripts\azure-pipelines/../ci.baseline.txt.
REGRESSION: openimageio:x64-linux failed with BUILD_FAILED. If expected, add openimageio:x64-linux=fail to /agent/_work/1/s/scripts/azure-pipelines/../ci.baseline.txt.
REGRESSION: llvm:x64-windows-static-md failed with FILE_CONFLICTS. If expected, add llvm:x64-windows-static-md=fail to C:\a\1\s\scripts\azure-pipelines/../ci.baseline.txt.
REGRESSION: llvm:x64-windows failed with FILE_CONFLICTS. If expected, add llvm:x64-windows=fail to C:\a\1\s\scripts\azure-pipelines/../ci.baseline.txt.
REGRESSION: forge:x64-windows-static-md failed with FILE_CONFLICTS. If expected, add forge:x64-windows-static-md=fail to C:\a\1\s\scripts\azure-pipelines/../ci.baseline.txt.
REGRESSION: forge:x64-windows-static failed with FILE_CONFLICTS. If expected, add forge:x64-windows-static=fail to C:\a\1\s\scripts\azure-pipelines/../ci.baseline.txt.
REGRESSION: forge:x64-windows failed with FILE_CONFLICTS. If expected, add forge:x64-windows=fail to C:\a\1\s\scripts\azure-pipelines/../ci.baseline.txt.
REGRESSION: dbow2:x64-linux failed with BUILD_FAILED. If expected, add dbow2:x64-linux=fail to /agent/_work/1/s/scripts/azure-pipelines/../ci.baseline.txt.
REGRESSION: colmap:x64-linux failed with BUILD_FAILED. If expected, add colmap:x64-linux=fail to /agent/_work/1/s/scripts/azure-pipelines/../ci.baseline.txt.
REGRESSION: cminpack:x64-windows-static-md failed with BUILD_FAILED. If expected, add cminpack:x64-windows-static-md=fail to C:\a\1\s\scripts\azure-pipelines/../ci.baseline.txt.
REGRESSION: cminpack:x64-windows-static failed with BUILD_FAILED. If expected, add cminpack:x64-windows-static=fail to C:\a\1\s\scripts\azure-pipelines/../ci.baseline.txt.
REGRESSION: cminpack:x64-windows failed with BUILD_FAILED. If expected, add cminpack:x64-windows=fail to C:\a\1\s\scripts\azure-pipelines/../ci.baseline.txt.
REGRESSION: cminpack:x64-linux failed with BUILD_FAILED. If expected, add cminpack:x64-linux=fail to /agent/_work/1/s/scripts/azure-pipelines/../ci.baseline.txt.
REGRESSION: cmake-user:x64-linux failed with BUILD_FAILED. If expected, add cmake-user:x64-linux=fail to /agent/_work/1/s/scripts/azure-pipelines/../ci.baseline.txt.
```

**Comment by dg0yt** [comment]
Some of the x64-linux issues are resolved by #30421.

**Comment by BillyONeal** [comment]
Discovered a problem with this release during VS insertion, closing.

**Comment by autoantwort** [comment]
> I am really interested if [microsoft/vcpkg-tool#957](https://github.com/microsoft/vcpkg-tool/pull/957) will change to quality of the reported issues

They are still not able to click on a link and follow the one steps :(

**Comment by dg0yt** [comment]
This is expected, unfortunately. It is still easier to submit a poor issue.
To some extent, it might perhaps help to link a more sophisticated landing page with step by step instructions instead (or with Tiktok videos :smile:).
This page could also display "hot issues" such as "msys2-runtime fails".

**Comment by autoantwort** [comment]
My current idea is to provide a video how to report a build failure. Maybe automatically post it on poor issues.

**Comment by autoantwort** [comment]
We could auto convert the issue templates to https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository, then it is harder to report poor issues.

**Comment by autoantwort** [comment]
Currently something like the following is printed
```
...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /opt/homebrew/bin/ninja -v
    Working Directory: /Users/leanderSchulten/git_projekte/vcpkg/buildtrees/qtopcua/arm64-osx-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      /Users/leanderSchulten/git_projekte/vcpkg/buildtrees/qtopcua/config-arm64-osx-dbg-CMakeCache.txt.log
      /Users/leanderSchulten/git_projekte/vcpkg/buildtrees/qtopcua/config-arm64-osx-rel-CMakeCache.txt.log
      /Users/leanderSchulten/git_projekte/vcpkg/buildtrees/qtopcua/config-arm64-osx-out.log

Call Stack (most recent call first):
  vcpkg_installed/arm64-osx/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:248 (vcpkg_execute_required_process)
  vcpkg_installed/arm64-osx/share/qtbase/qt_install_submodule.cmake:147 (vcpkg_cmake_configure)
  vcpkg_installed/arm64-osx/share/qtbase/qt_install_submodule.cmake:330 (qt_cmake_configure)
  ports/qtopcua/portfile.cmake:27 (qt_install_submodule)
  scripts/ports.cmake:147 (include)


error: building qtopcua:arm64-osx failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+qtopcua
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[qtopcua]+Build+error&body=Copy+issue+body+from+%2FUsers%2FleanderSchulten%2Fgit_projekte%2Fvcpkg%2Fvcpkg_installed%2Fvcpkg%2Fissue_body.md
You can also sumbit an issue by running (GitHub cli must be installed):
    gh issue create -R microsoft/vcpkg --title "[qtopcua] Build failue" --body-file /Users/leanderSchulten/git_projekte/vcpkg/vcpkg_installed/vcpkg/issue_body.md
``` 
@dg0yt What would the ideal output look like in your opinion?

**Comment by dg0yt** [comment]
- The first two blocks of output are distracting if a download failed (e.g. msys2 runtime, gitlab, github).
- All of this is distracting if a system feature check failed (e.g. linux headers or perl modules for openssl, VS language pack, Windows SDK).

And as an vcpkg author, in most these cases I know which type of error I want to report. I just need a maintainer function offering a proper interface to vcpkg tool instead of a generic `message(FATAL_ERROR ...)`. 
(We tried to move in that direction with mingw compiler detection some time ago, but I didn't succed in telling that this is generally needed.)

**Comment by autoantwort** [comment]
> (We tried to move in that direction with mingw compiler detection some time ago, but I didn't succed in telling that this is generally needed.)

Do you have a link to this discussion?

**Comment by dg0yt** [comment]
It is not exactly the general case, and not really reaching the tool, but it is about UX with early detection of a working toolchain... https://github.com/microsoft/vcpkg/pull/17505#issuecomment-917144906

**Pull request closed without merging**
