### PR TITLE
[azure-c-shared-utility] Fix patch when selected feature public-preview

### PR DESCRIPTION
**Pull request by JackBoosY**
The code in the public-preview version is different from the official version, causing the patch applying to fail. Fix this issue.

Related: #9870 #9805.

### CODE REVIEW

**Comment by JackBoosY** [comment]
> CMake Error at CMakeLists.txt:172 (configure_file):
  configure_file Problem configuring file

code:
```
configure_file(StubGenerator.xml.in ${CMAKE_CURRENT_SOURCE_DIR}/src/csharp/StubGenerator.x64.xml)
```

I cannot repro it on my machine.

**Comment by vicroms** [comment]
Azure Kinect has been flaky for a while, I don't know the root cause of the problem but usually removing the tombstone and rebuilding is enough.

**Comment by vicroms** [comment]
CI is passing now

**Review by vicroms — APPROVED** [review]
LGTM

**Review by PhoebeHui — APPROVED** [review]

**Pull request merged**
