### PR TITLE
[opencv4] Fix INTERFACE_LINK_LIBRARIES error

### LINKED ISSUE #14171: [opencv] build failure
**Host Environment**
- OS: Windows 10
- Compiler: revision

**To Reproduce**
`.\vcpkg install opencv[core,dnn,ffmpeg,jpeg,opengl,png,tiff,webp] --triplet x64-windows`
`.\vcpkg install darknet[full]:x64-windows`
`.\vcpkg install darknet[opencv-base,cuda,cudnn] --triplet x64-windows`

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    darknet[core,cuda,cudnn,opencv-base]:x64-windows
  * opencv[core,dnn,ffmpeg,jpeg,opengl,png,tiff,webp]:x64-windows
  * opencv4[core,dnn,ffmpeg,jpeg,opengl,png,tiff,webp]:x64-windows
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Starting package 1/3: opencv4:x64-windows
Building package opencv4[core,dnn,ffmpeg,jpeg,opengl,png,tiff,webp]:x64-windows...
Could not locate cached archive: C:\Users\runji\AppData\Local\vcpkg\archives\95\953199745b91131c12e335bfdb55eefe7d7b784c.zip
-- Using cached C:/vcpkg/downloads/opencv-opencv-4.3.0.tar.gz
-- Cleaning sources at C:/vcpkg/buildtrees/opencv4/src/4.3.0-1e84697c4a.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/opencv-opencv-4.3.0.tar.gz
-- Applying patch 0001-disable-downloading.patch
-- Applying patch 0002-install-options.patch
-- Applying patch 0003-force-package-requirements.patch
-- Applying patch 0004-fix-policy-CMP0057.patch
-- Applying patch 0006-jpeg2000_getref.patch
-- Applying patch 0009-fix-uwp.patch
-- Using source at C:/vcpkg/buildtrees/opencv4/src/4.3.0-1e84697c4a.clean
-- Using cached C:/vcpkg/downloads/opencv-cache/tiny_dnn/adb1c512e09ca2c7a6faef36f9c53e59-v1.0.0a3.tar.gz
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:85 (message):
    Command failed: ninja -v
    Working Directory: C:/vcpkg/buildtrees/opencv4/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\opencv4\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:312 (vcpkg_execute_required_process)
  ports/opencv4/portfile.cmake:280 (vcpkg_configure_cmake)
  scripts/ports.cmake:79 (include)

Error: Building package opencv4:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opencv4:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/5426364/config-x64-windows-out.log)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

I tried updating vcpkg and cmake, reinstalling everything.

### PR DESCRIPTION
**Pull request by JackBoosY**
Fix configure error:
```
INTERFACE_LINK_LIBRARIES: optimized;F:/vcpkg/installed/x64-windows/lib/avcodec.lib;debug;F:/vcpkg/installed/x64-windows/debug/lib/avcodec.lib;optimized;F:/vcpkg/installed/x64-windows/lib/avdevice.lib;debug;F:/vcpkg/installed/x64-windows/debug/lib/avdevice.lib;optimized;F:/vcpkg/installed/x64-windows/lib/avfilter.lib;debug;F:/vcpkg/installed/x64-windows/debug/lib/avfilter.lib;optimized;F:/vcpkg/installed/x64-windows/lib/avformat.lib;debug;F:/vcpkg/installed/x64-windows/debug/lib/avformat.lib;optimized;F:/vcpkg/installed/x64-windows/lib/avresample.lib;debug;F:/vcpkg/installed/x64-windows/debug/lib/avresample.lib;optimized;F:/vcpkg/installed/x64-windows/lib/avutil.lib;debug;F:/vcpkg/installed/x64-windows/debug/lib/avutil.lib;optimized;F:/vcpkg/installed/x64-windows/lib/postproc.lib;debug;F:/vcpkg/installed/x64-windows/debug/lib/postproc.lib;optimized;F:/vcpkg/installed/x64-windows/lib/swresample.lib;debug;F:/vcpkg/installed/x64-windows/debug/lib/swresample.lib;optimized;F:/vcpkg/installed/x64-windows/lib/swscale.lib;debug;F:/vcpkg/installed/x64-windows/debug/lib/swscale.lib;optimized;wsock32;debug;wsock32;optimized;ws2_32;debug;ws2_32;optimized;secur32;debug;secur32;optimized;bcrypt;debug;bcrypt;optimized;strmiids;debug;strmiids;optimized;Vfw32;debug;Vfw32;optimized;Shlwapi;debug;Shlwapi;optimized;mfplat;debug;mfplat;optimized;mfuuid;debug;mfuuid
CMake Error at modules/videoio/cmake/init.cmake:13 (set_target_properties):
  Property INTERFACE_LINK_LIBRARIES may not contain link-type keyword
  "optimized".  The INTERFACE_LINK_LIBRARIES property may contain
  configuration-sensitive generator-expressions which may be used to specify
  per-configuration rules.
Call Stack (most recent call first):
  modules/videoio/cmake/detect_ffmpeg.cmake:60 (ocv_add_external_target)
  modules/videoio/cmake/init.cmake:3 (include)
  modules/videoio/cmake/init.cmake:23 (add_backend)
  cmake/OpenCVModule.cmake:312 (include)
  cmake/OpenCVModule.cmake:375 (_add_modules_1)
  modules/CMakeLists.txt:7 (ocv_glob_modules)
```

Fixes #14171.

### CODE REVIEW

**Comment by JackBoosY** [comment]
cc @cenit for review this PR.
PS: should I report this issue to the upstream & should I also fix other versions of opencv?

**Review by cenit — APPROVED** [review]
Thanks @JackBoosY for the patch.
Yes it is very appropriate to back port the patch also to opencv2/3 and to suggest it also upstream

**Comment by JackBoosY** [comment]
These contents did not appear in opencv2/opencv3.

**Review by PhoebeHui — APPROVED** [review]

**Comment by BillyONeal** [comment]
I think this change is correct but want to give upstream a few days to respond; as long as they don't take explicit issue with this change I'll merge it in ~4 days (Friday)

**Comment by cenit** [comment]
> These contents did not appear in opencv2/opencv3.

might be in different positions of the code maybe? Did you try if `./vcpkg install opencv3[ffmpeg]` and `./vcpkg install opencv2[ffmpeg]` work with the new FindFFMPEG.cmake recently rewritten?

**Comment by JackBoosY** [comment]
@cenit opencv2 and opencv3 can be built successfully without this changes.

**Comment by JackBoosY** [comment]
@BillyONeal Okay, the upstream accepted my PR.

**Comment by guybashan** [comment]
Just tested and PR seems to be working fine and compile without errors..

**Comment by BillyONeal** [comment]
Awesome, thanks @JackBoosY !

**Comment by fishduke** [comment]
try 'vcpkg install opencv[core,dnn,ffmpeg,jpeg,opengl,png,tiff,webp,freetype]:x64-windows --recurse'

**Pull request merged**
