### PR TITLE
[spdlog] Update to 1.2.0

### PR DESCRIPTION
**Pull request by crackedmind**

### CODE REVIEW

**Comment by alexkaratarakis** [comment]
Note: regresses arm-uwp and x64-uwp.

**Comment by gabime** [comment]
@alexkaratarakis What's the problem with x64-uwp ? Can you share more details please?

**Comment by crackedmind** [comment]
@alexkaratarakis 
Can you review PR again?
I rebased commit to latest spdlog 1.2.0 version. Also, I disabled builds for bench and exmaples, that breaks uwp builds.

**Comment by crackedmind** [comment]
@alexkaratarakis @ras0219-msft ping

**Comment by ras0219-msft** [comment]
Looks like we took so long processing that this was automatically picked up as part of our rolling upgrade system[1].

Thanks again for the PR!

[1] https://github.com/Microsoft/vcpkg/commit/9c62c6a37ac940abbb4f19237d9a891881421a1a

**Pull request closed without merging**
