### PR TITLE
[soil2] Add new package soil2

### PR DESCRIPTION
**Pull request by Jacob-Tate**

### CODE REVIEW

**Comment by nightslashs** [comment]
My comment didnt go through this is just a simple port for soil2!

**Comment by vicroms** [comment]
Hi @nightslashs 

Thanks for contributing to vcpkg! 

Here's the current status of the build:

Platform | Status
-- | --
arm-uwp | Fail
arm64-windows | **Pass**
x64-linux | **Pass**
x64-uwp | Fail
x64-windows | **Pass**
x64-windows-static | **Pass**
x86-windows | **Pass**

It is only failing on UWP, I can accept the PR as it is. But let me know if you want to tackle fixing the UWP build.

**Comment by nightslashs** [comment]
Ill look into the uwp failures it appears to be something with the opengl linkage so ill let you know!

**Comment by nightslashs** [comment]
It appears that the issue is due to the version of opengl which is linked to the UWP app. I cant quite figure out why the included gl.h doesn't seem to define the types we expect it to (ie GLint, GLenum). Looking up some stuff it may be related to this but the fixes don't seem to make any difference https://stackoverflow.com/a/3939495. 

Additionally, I have attempted to include the opengl port which seems to exist for this reason in specific but to no avail! 

Lastly, I have attempted to check how some of the other gl reliant ports have dealt with this issue but it appears most of them provide raw binaries rather than building from source.

If you have any ideas on where to go forward the help would be much appreciated!

**Comment by vicroms** [comment]
It looks like fixing builds for UWP might require some investigation. 
Thanks for your effort, @nightslashs! 

I'm OK with merging this PR as it is, it makes for a good initial version and we can add support for the missing platforms incrementally.

Can you please file an issue with your comments regarding UWP support so we can keep track on it?

**Pull request merged**
