### PR TITLE
[qcustomplot] Add new port

### PR DESCRIPTION
**Pull request by myd7349**
* [x] x86-windows
* [ ] x86-windows-static
* [x] x64-windows
* [ ] x64-windows-static
* [ ] x64-linux

### CODE REVIEW

**Comment by myd7349** [comment]
Test project: https://github.com/myd7349/Ongoing-Study/tree/master/cpp/Qt/QCustomPlot

**Comment by PhoebeHui** [comment]
@myd7349, thanks for contributing to vcpkg!

Here is failed triplet( x64-linux, x64-windows-static, x64-windows, x86-windows) and failed ports with your PR.
```
Processing arm-uwp                        405 vs 405
    qcustomplot                                                 Skip vs 
Processing arm64-windows                  456 vs 456
    qcustomplot                                                 Skip vs 
Processing x64-linux                      589 vs 589
    qcustomplot                                                 Fail vs 
Processing x64-osx                        579 vs 579
    qcustomplot                                                 Skip vs 
Processing x64-uwp                        433 vs 433
    qcustomplot                                                 Skip vs 
Processing x64-windows                    866 vs 866
    qcustomplot                                                 Fail vs 
Processing x64-windows-static             761 vs 761
    qcustomplot                                                 Fail vs 
Processing x86-windows                    846 vs 846
    qcustomplot                                                 Fail vs 
```
Failures:
CMake Error at scripts/cmake/vcpkg_configure_qmake.cmake:23 (message):
  vcpkg_configure_qmake: unable to find qmake.
Call Stack (most recent call first):
  ports/qcustomplot/portfile.cmake:23 (vcpkg_configure_qmake)
  scripts/ports.cmake:71 (include)

[x86-windows.txt](https://github.com/Microsoft/vcpkg/files/2935708/x86-windows.txt)

**Comment by myd7349** [comment]
@PhoebeHui Hi! Thanks for the reply. It seems that this port faces a similer problem as https://github.com/Microsoft/vcpkg/pull/5024.

I have tested it with `x86-windows` and `x64-windows`, and it works well with these two triplets.

I was also able to install it on `x86-windows-static` and `x64-windows-static`, but these were some link errors when I tried to use it in a test project. Maybe I can check it again.

I am not able to install it on `x64-linux` since `vcpkg install qt5-base` failed on my Ubuntu 17.04. Now that, the Qt port has updated to `5.12`, maybe I can give it a try.

**Comment by vicroms** [comment]
The issue is quite strange, it failed to find qmake in all our CI machines:

```
CMake Error at scripts/cmake/vcpkg_configure_qmake.cmake:23 (message):
  vcpkg_configure_qmake: unable to find qmake.
Call Stack (most recent call first):
  ports/qcustomplot/portfile.cmake:23 (vcpkg_configure_qmake)
  scripts/ports.cmake:71 (include)
```

**Comment by bouffa** [comment]
@vicroms I also experienced the same problem with qt-base5 (cmake unable to find qmake.exe), and I think the problem was introduced by a recent pull request, see #5566

**Comment by myd7349** [comment]
@vicroms I will try to trigger a rebuild of `qt5-base`. I noticed we have encountered a similar problem before in another PR: https://github.com/Microsoft/vcpkg/pull/5024#issuecomment-470302164 .

**Comment by PhoebeHui** [comment]
@myd7349, thanks for the updates! Here is latest test results:
```
Processing arm-uwp                        412 vs 412
    qcustomplot                                                 Skip vs 
Processing arm64-windows                  472 vs 472
    qcustomplot                                                 Skip vs 
Processing x64-linux                      617 vs 617
    qcustomplot                                                 Fail vs 
Processing x64-osx                        610 vs 610
    qcustomplot                                                 Skip vs 
Processing x64-uwp                        440 vs 440
    qcustomplot                                                 Skip vs 
Processing x64-windows                    887 vs 886
    qcustomplot                                                 Pass vs 
Processing x64-windows-static             781 vs 780
    qcustomplot                                                 Pass vs 
Processing x86-windows                    867 vs 866
    qcustomplot                                                 Pass vs 
```

**Comment by vicroms** [comment]
Thanks for yet another port @myd7349! 
I'm going to merget it as it is. 
Support for Linux and MacOS can be added in future PRs.

**Pull request merged**
