### PR TITLE
[winpcap] Remove port

### PR DESCRIPTION
**Pull request by Neumann-A**
+ remove broken version due to vcpkg_msbuild_install

```
WinPcap Has Ceased Development. We recommend Npcap.
The WinPcap project has ceased development and WinPcap and WinDump are no longer maintained. WE RECOMMEND USING [Npcap INSTEAD](https://nmap.org/npcap/).
```
According to https://www.winpcap.org/default.htm development basically already ended 2018. The alternative is to use npcap from nmap.

### CODE REVIEW

**Review by BillyONeal — APPROVED** [review]

**Review by BillyONeal — CHANGES_REQUESTED** [review]
The PR build crash is because winpcap is not a leaf. nmap, pcapplusplus, pcl, and soem need to get fixed

**Comment by giles45** [comment]
I'm against removing this. npcap isn't a good replacement given that it is not open source software and has very restrictive license terms (see https://github.com/nmap/npcap/blob/master/LICENSE).

WinPcap may have stopped development but AFAIK there are no black marks against it in terms of security vulnerabilities or other things. Until such time, I think it is reasonable to continue to make it available. The decision to remove seems to have been made because the port got broken by a vcpkg change (copying PDBs) with the justification being that it is end-of-life.

**Comment by seladb** [comment]
Currently there is no Npcap port in vcpkg, probably because of the license issue @giles45 mentioned, so there is no alternative to WinPcap on Windows...

**Comment by BillyONeal** [comment]
Given the report by @giles45, this not being a leaf,  and there being no concrete reported problems with the current port, we (@vicroms @data-queue @JavierMatosD @ras0219-msft and I) want to keep it as is.

Thanks for your contribution to vcpkg :)

**Pull request closed without merging**
