### PR TITLE
[vcpkg baseline][fastrtps/foonathan-memory/chipmunk] Modify ci.baseline.txt

### PR DESCRIPTION
**Pull request by Cheney-W**
Fixed [CI pipeline](https://dev.azure.com/vcpkg/public/_build/results?buildId=90705&view=results) issue:
```
PASSING, REMOVE FROM FAIL LIST: foonathan-memory:arm-neon-android
PASSING, REMOVE FROM FAIL LIST: foonathan-memory:x64-android
PASSING, REMOVE FROM FAIL LIST: foonathan-memory:arm64-android
```
Above records were added into the ci.baseline.txt by PR https://github.com/microsoft/vcpkg/pull/29406, them were fixed in PR https://github.com/microsoft/vcpkg/pull/31905, so remove the records from ci.baseline.txt.

```
fastrtps:arm-neon-android
fastrtps:x64-android
fastrtps:arm64-android  
```
install failed with below error, adding them into the ci.baseline.txt.
```
Cannot find package android-ifaddrs
```
Fixes [CI pipeline](https://dev.azure.com/vcpkg/public/_build/results?buildId=90840&view=results) issue:
```
PASSING, REMOVE FROM FAIL LIST: chipmunk:arm64-android
PASSING, REMOVE FROM FAIL LIST: chipmunk:x64-android
```

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] ~~SHA512s are updated for each updated download~~
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [ ] ~~The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.~~
- [ ] ~~Only one version is added to each modified port's versions file.~~

END OF PORT UPDATE CHECKLIST (delete this line) -->

### CODE REVIEW

**Comment by vicroms** [comment]
There's a newer version of `fastrtps` (2.10.1). 

Maybe we could try updating and see if that fixes the problem.

**Comment by Cheney-W** [comment]
> There's a newer version of `fastrtps` (2.10.1).
> Maybe we could try updating and see if that fixes the problem.

Okay, I will take care of this matter today.

**Comment by Cheney-W** [comment]
After updated `fastrtps` to 2.10.1, it still failed with error:
```
Cannot find package android-ifaddrs
```

**Comment by Cheney-W** [comment]
Waiting for https://github.com/microsoft/vcpkg/pull/32049.

**Comment by FrankXie05** [comment]
Related `chipmunk` PR https://github.com/microsoft/vcpkg/pull/32441

**Comment by Cheney-W** [comment]
Duplicate of https://github.com/microsoft/vcpkg/pull/32484

**Pull request closed without merging**
