### PR TITLE
[vcpkg] Avoid naming Policheck sensitive term 'Virgin Islands'

### PR DESCRIPTION
**Pull request by BillyONeal**

### CODE REVIEW

**Comment by strega-nil** [comment]
Is this an issue, given that this is an actual US territory?

**Comment by BillyONeal** [comment]
Policheck wants "US Virgin Islands" or "British Virgin Islands". The address doesn't appear to exist so I couldn't replace with the correct one and we don't care about the specific value, so I just replaced it.

**Comment by strega-nil** [comment]
Ah, fair enough, makes sense.

**Pull request merged**
