### PR TITLE
Fix for issue #28120.

### LINKED ISSUE #28120: [arrow] CMake config files for Dataset are not copied to the install directory
****

**Is your feature request related to a problem? Please describe.**

I built Arrow 10.0.1 using:
```
vcpkg.exe install "arrow[core,csv,dataset,filesystem,json,parquet]" --triplet=x64-windows-static --x-install-root=%installDir% --recurse
```
I cannot link arrow_dataset.lib using documented CMake functions (find_package(ArrowDataset REQUIRED), target: ArrowDataset::arrow_dataset_static), because ArrowDatasetConfig.cmake and other configuration files for Dataset are not copied to the install directory.

**Proposed solution**

The solution was proposed here: https://github.com/apache/arrow/issues/14801

**Describe alternatives you've considered**
Currently you can use find_library instead of find_package to configure ArrowDataset in CMake.

### PR DESCRIPTION
**Pull request by piotrwendykier**
**Describe the pull request**

- #### What does your PR fix?
  Fixes #28120 

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  all, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by piotrwendykier** [comment]
> 

@microsoft-github-policy-service agree [company="Wolfram Research"]

**Comment by piotrwendykier** [comment]
> @microsoft-github-policy-service agree [company="Wolfram Research"]

@microsoft-github-policy-service agree company="Wolfram Research"

**Comment by piotrwendykier** [comment]
> _This is a new experimental fast check for PR issues. Please let us know if this bot is helpful!_
> 
> PRs must add only one version and must not modify any published versions

I don't understand this comment. I have manually bumped port-version in ports/arrow/vcpkg.json and versions/baseline.json and then run `./vcpkg x-add-version --all`.

**Comment by FrankXie05** [comment]
@piotrwendykier After all the changes are made, you need to submit a commit separately. Don't worry that I will update it. :)

**Review by FrankXie05 — APPROVED** [review]

**Comment by piotrwendykier** [comment]
I assume there is nothing else I can do here. Somebody with the write access should merge this PR.

**Pull request merged**
