### PR TITLE
[ignition-cmake0, ignition-math4] Add support for writing ports of Ignition Robotics libraries 🤖

### PR DESCRIPTION
**Pull request by traversaro**
The Ignition Robotics Libraries ( https://ignitionrobotics.org ) are a set of libraries that are used to develop robotics applications. In particular, they are dependencies for the widely used Gazebo simulator ( http://gazebosim.org ).

In this PR, three ports are added: 
* `ignition-modularscript` ( https://github.com/microsoft/vcpkg/commit/8fb25c18fc34249fd7c496607a01b862a6e9d9d1 )
* `ignition-cmake0` : A port for the version 0 of the ignition-cmake (https://ignitionrobotics.org/libs/cmake) library 
* `ignition-math4` : A port for the version 4 of the ignition-math (https://ignitionrobotics.org/libs/math)  library 

As most ignition libraries follow the same structure and convention, the use of `ignition-modularscript` reduces the process of writing a port of an ignition library to a few lines, unless the library has some particular features, for which custom lines can be added to the portfile.

One interesting feature of the ignition libraries  is that they different major version of the same library can be installed side-by-side in the same system. For this reason, it is quite natural to create a port for each major supported version, to enable user and downstream project to autonomously select which major version of the library they need. This is the reason why, as a first example of ports, Ignition CMake 0 and  Ignition Math 4 are added even if more recent version have been released as well, as they are the version used as dependencies for the latest stable version of the Gazebo robotic simulator.

### CODE REVIEW

**Comment by traversaro** [comment]
Related downstream issue: https://github.com/j-rivero/vcpkg_ignition/issues/2 . 
cc @seanyen @j-rivero

**Comment by traversaro** [comment]
The ports now compile fine in all the triplets tested by the CI system. Two patches were necessary to permit compilation on `arm-windows` and `arm64-windows`, they have been already submitted upstream and included as patches in the `ignition-cmake0` port:
*  https://bitbucket.org/ignitionrobotics/ign-cmake/pull-requests/163
* https://bitbucket.org/ignitionrobotics/ign-cmake/pull-requests/168

**Comment by vicroms** [comment]
Thanks for the PR!

**Comment by traversaro** [comment]
Thanks @vicroms ! Just to understand, I now need to add 🤖 to any robotics-related PR? :smile:

**Comment by vicroms** [comment]
The suggested format for titles is **"[ports] description"** but I thought that the 🤖 would be a nice touch 🤣

**Comment by j-rivero** [comment]
> Related downstream issue: [j-rivero/vcpkg_ignition#2](https://github.com/j-rivero/vcpkg_ignition/issues/2) .
> cc @seanyen @j-rivero

wow! thanks Silvio!

**Pull request merged**
