### PR TITLE
[ignition-msgs1, ignition-transport4] Add new ports 🤖

### PR DESCRIPTION
**Pull request by traversaro**
Write new ports using the ignition-modularscript port added in https://github.com/microsoft/vcpkg/pull/7781 .
The ports are for the ignition-msgs ( https://ignitionrobotics.org/libs/msgs ) and ignition-transport ( https://ignitionrobotics.org/libs/transport ) libraries for robotics applications. 

Related issue: https://github.com/microsoft/vcpkg/issues/8014 .

### CODE REVIEW

**Comment by traversaro** [comment]
The failures on triplets `x64-uwp`, `arm64-windows`, `arm-uwp` are expected, as `ignition-msgs1` requires some modifications to support cross compilation, and instead of working directly on a patch I opened an issue upstream to make sure that the modification will be eventually merged upstream (see https://bitbucket.org/ignitionrobotics/ign-msgs/issues/34/add-support-for-cross-compilation). 

Instead, the failure in `x64-linux` is quite strange, and can be investigated further, as there are some strange linking failures w.r.t. to protobuf.

**Comment by traversaro** [comment]
The `x64-linux` failure is apparently due to the fact that the linking order depends when linking static libraries using `ld`, and the order used in the build system of `ignition-msgs` for linking protobuf libraries was wrong, see the PR at https://bitbucket.org/ignitionrobotics/ign-msgs/pull-requests/151/fix-linking-order-of-protocol-buffers/diff for more details.

**Comment by traversaro** [comment]
In the latest commit the failure in `x64-linux` have been solved, and the only failures are the expected one on cross-compilation targets.

**Comment by traversaro** [comment]
There is another Linux failure because the logic to find `UUID` in ignition-transport4 requires `pkg-config` to be installed, and `pkg-config` is not installed in the test machines.

**Comment by traversaro** [comment]
Fix for uuid problem described  in https://github.com/microsoft/vcpkg/pull/8044#issuecomment-529515227 added in the latest version of the PR.

**Comment by traversaro** [comment]
Robot emoji added to the title (see https://github.com/microsoft/vcpkg/pull/7781#issuecomment-528017994), I think the PR is now ready for review.

**Review by cbezault — APPROVED** [review]

**Pull request merged**
