### PR TITLE
[ixwebsocket] update to 11.2.3

### PR DESCRIPTION
**Pull request by bsergean**
**Describe the pull request**

- What does your PR fix? 

Update ixwebsocket to latest as of March 23nd 2021

- Which triplets are supported/not supported? Have you updated the CI baseline?

mingw (windows + gcc) is supported now.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

I think so

### CODE REVIEW

**Comment by bsergean** [comment]
I'm not too sure why some test failed / I have CI now on github actions and things works fine on windows.
I'm often lost with Azure pipelines ...

**Comment by JonLiu1993** [comment]
> I'm not too sure why some test failed / I have CI now on github actions and things works fine on windows.
> I'm often lost with Azure pipelines ...

Thanks for your contribution. I modified some things and waited for the CI test to be completed

**Comment by JonLiu1993** [comment]
@bsergean ,I helped you fix the version problem, but it seems that there are still some problems that need to be modified. Can you take a look?
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/6194988/install-x64-windows-dbg-out.log)
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/6194989/install-x86-windows-dbg-out.log)

**Comment by bsergean** [comment]
That’s great, thanks for the help @JonLiu1993

Let me look at those logs.

The library used to be a static only library, and now it can also be built as a dynamic library (DLL or .so / .dylib on unix), but I have not tested that too much on windows. (I think I need an export file, and cmake has a statement to export all symbols).

**Comment by bsergean** [comment]
Yeah everything is green now :)

Thanks for the help @JonLiu1993

**Review by JonLiu1993 — APPROVED** [review]

**Comment by ras0219-msft** [comment]
LGTM, thanks for the PR!

**Comment by bsergean** [comment]
Thanks for merging !

Vcpkg is such a useful piece of software and on a noble battle to make packaging easier with C++.

**Pull request merged**
