### PR TITLE
[vcpkg baseline][tmx] Fix libxml dependency

### PR DESCRIPTION
**Pull request by dg0yt**
- #### What does your PR fix?
  Fixes https://github.com/microsoft/vcpkg/pull/24935#issuecomment-1177115255. CC @JackBoosY 

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  unchanged, no

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  yes

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
Is _versions/baseline.txt_ file format changed?

**Comment by dg0yt** [comment]
> Is _versions/baseline.txt_ file format changed? I noticed there is `100755 → 100644`.

Isn't this the UNIX file permissions, with the executable bit correctly removed from this plain file? 
I didn't do any other step than usual (`git`, `vcpkg x-add-version`). But there was a manual edit recently, with an extra line break added.

**Comment by JackBoosY** [comment]
> Isn't this the UNIX file permissions, with the executable bit correctly removed from this plain file? I didn't do any other step than usual (`git`, `vcpkg x-add-version`). But there was a manual edit recently, with an extra line break added.

Can you please rerun `./vcpkg x-add-version --overwrite-version --all`?

**Comment by dg0yt** [comment]
> > Isn't this the UNIX file permissions, with the executable bit correctly removed from this plain file? I didn't do any other step than usual (`git`, `vcpkg x-add-version`). But there was a manual edit recently, with an extra line break added.
> 
> Can you please rerun `./vcpkg x-add-version --overwrite-version --all`?

No changes.

**Comment by dg0yt** [comment]
Look here: https://github.com/microsoft/vcpkg/commit/35fb7a05a7d7e387dd9a913118c535911b0cbc7d#diff-dba19656e5032ab9d4d3f06eea74404e06a570a1552e628ab1410b721b2481ef

**Comment by JackBoosY** [comment]
Well, okay.

**Pull request merged**
