### PR TITLE
[ace] Add versioned-namespace feature

### PR DESCRIPTION
**Pull request by jwillemsen**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Review by LilyWangLL — APPROVED** [review]

**Comment by LilyWangLL** [comment]
Feature `ace[versioned-namespace]` test pass on `x64-windows`.

**Review by dg0yt — CHANGES_REQUESTED** [review]
This feature causes source incompatible changes: It breaks forward declaration, or more correctly, makes it mandatory to put forward declarations of ACE symbols within the versioned namespace using specific macros:
https://www.dre.vanderbilt.edu/~schmidt/DOC_ROOT/ACE/docs/Symbol_Versioning.html
This is similar to building Qt with namespaces.
For this reason, I think this feature is not acceptable.
https://learn.microsoft.com/en-us/vcpkg/contributing/maintainer-guide#do-not-use-features-to-implement-alternatives

**Comment by jwillemsen** [comment]
From the vcpkg documentation it is not clear for me how this kind of features should be handled with vcpkg, we have a lot of this kind of features in ACE/TAO, compile time flags which enable/disable features which impact the API exported.

**Comment by dg0yt** [comment]
Enabling additive features is no problem - it won't break any downstream usage. 
Problems only exist with alternatives. As long as the alternatives don't need dependencies, they can be handled from customized triplet files, by setting specific variables which are applied by the portfile or maintainer functions.

**Comment by jwillemsen** [comment]
Do you have a link to some docu and examples how to do that?

**Comment by dg0yt** [comment]
Triplet files are described here:
https://learn.microsoft.com/en-us/vcpkg/users/triplets 

Variables for maintainer functions can't be used here because the ace port doesn't use the common configuration functions.
But you can add your own variables such as `VCPKG_ACE_WITH_VERSIONED_NAMESPACE`. This will be visible for code in the portfile. This is how qtbase deals with the Qt namespace option:
https://github.com/microsoft/vcpkg/blob/2f56fdad4bcf43c21ec6f952cf7b91c8c43c5c0d/ports/qtbase/portfile.cmake#L96-L98

Note: Customization via triplet is not convenient. It cannot be applied to the official triplet files. They need to be supplied via custom files. The content of the files is hashed for ABI tracking, so changes do affect caching and rebuilds.
https://learn.microsoft.com/en-us/vcpkg/users/triplets#adding-or-replacing-triplets

**Comment by jwillemsen** [comment]
Closing, don't have free time to look at this in more detail

**Pull request closed without merging**
