### PR TITLE
[msbuild] Init Import user props

### PR DESCRIPTION
**Pull request by MVoz**

### CODE REVIEW

**Comment by BillyONeal** [comment]
I don't really think checking in an entire third party project is a reasonable example (and I'm almost positive there are bits in here that are not MIT licensed, for example there are msbuild scripts clearly copied out of a Visual Studio installation)

**Comment by Voskrese** [comment]
@BillyONeal 
which ones? for example NASM and YASM scripts are already present in VCPKG
LLVM scripts are missing, but the package itself is added

the only question is WDK (PlatformToolsets LLVM WindowsUserModeDriver10)

**Comment by BillyONeal** [comment]
[vs-yasm is GPL](https://github.com/ShiftMediaProject/VSYASM/blob/master/COPYING), so we absolutely cannot include those sources in this MIT repository. Our repo contains a script that will download that package, not that package itself.

The WDK would be under the WDK's EULA which is not going to be compatible with MIT either.

**Comment by Voskrese** [comment]
@BillyONeal 
ok, can redo it as a package \ port

```
vs-yasm
vs-nasm
vs-llvm
```

delete `WindowsUserModeDriver10`

**Comment by Voskrese** [comment]
@BillyONeal 
actually it's just a test

and by the way why don't add PlatformToolsets WindowsUserModeDriver10 to the image?

**Comment by BillyONeal** [comment]
(To be honest I'm not positive what the PR is trying to do since there's no description so I can't comment on whether your proposed course of action makes sense; I just saw stuff with the wrong license in the PR and wanted to save you a bunch of time if possible)

**Comment by BillyONeal** [comment]
>and by the way why don't add PlatformToolsets WindowsUserModeDriver10 to the image?

We want as little in the image as possible: the more dependencies we install there the less likely it is that we will detect necessary dependencies vcpkg needs to provide. So we want to do that if and only if there is some port that needs it and vcpkg can't provide it for some reason. (In addition to the concerns about global edits from the WDK mentioned last time that came up but I think you said are fixed in the latest version... :) )

**Comment by Voskrese** [comment]
@BillyONeal 
Ah I have locally all works and intends to, is done not for me exactly, and for all

port deps `networkdirect` --> `ms-mpi`

**Comment by Voskrese** [comment]
@BillyONeal 
how do I check that WDK is installed at all?

**Comment by BillyONeal** [comment]
Sadly I don't know anything about the WDK :/.

**Comment by Voskrese** [comment]
@BillyONeal 
I mean that the installation was successful or rolled back, when there is an error, there is a rollback

**Comment by Voskrese** [comment]
I think it's possible to isolate PlatformToolsets WindowsUserModeDriver10

https://gitlab.kitware.com/cmake/cmake/commit/548e9051a4f20657d04341107924171ea9d1bcb5
https://gitlab.kitware.com/cmake/cmake/-/blob/master/Help/variable/CMAKE_GENERATOR_TOOLSET.rst

https://github.com/microsoft/vcpkg/pull/11908

set(WindowsWindowsModeDriver $ENV{...PATH...})
set(VS_PLATFORM_TOOLSET VCTargetsPath="$WindowsWindowsModeDriver")

**Comment by Voskrese** [comment]
reopen, i can't delete branch

**Comment by BillyONeal** [comment]
It won't let me reopen either, I'm confused. Perhaps the branch is already deleted?

**Comment by BillyONeal** [comment]
image

**Comment by BillyONeal** [comment]
Yes, I reclosed it because I opened it by accident (that's why you see open and then immediate close). If I hover over the reopen button it won't let me because the branch has been deleted:
Screen Shot 2020-06-18 at 9 27 03 PM

**Comment by Voskrese** [comment]
https://github.com/Voskrese/vcpkg/tree/msbuild_user_props

**Comment by BillyONeal** [comment]
That is very strange :(. Maybe it was deleted and then recreated with the same name? Let me see if GitHub will let someone else reopen....

**Comment by Voskrese** [comment]
but no, everything is correct, deleted, there are still commits, because github remembers everything

**Comment by Voskrese** [comment]
it shouldn't be like this, it's some github bug


___

**Comment by cbezault** [comment]
Does seem like a GitHub bug. I'm getting a different message.
image

**Comment by Voskrese** [comment]
> Does seem like a GitHub bug. I'm getting a different message.

I have already deleted the branch from the repo-fork

**Pull request closed without merging**
