### PR TITLE
Libgd cmake targets

### PR DESCRIPTION
**Pull request by jumpinjackie**
This PR patches the CMakeLists.txt in libgd to export a `.cmake` targets file so one can use `find_package(libgd)` to consume the vcpkg port.

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Hi @jumpinjackie, a very relevant discussion for this PR is #616: Consider generating CMake config scripts for packages that don't natively provide them.

From that thread:
> The problem is that there are several choices that can be made when adding find_package() support, such as the casing of the package name and the exact spelling and arrangement of the libraries. Many libraries opt for a flat name, so you can do `target_link_libraries(hello sqlite3)`, but others choose (in line with the official CMake guidance) to use namespaces: `target_link_libraries(hello Sqlite3::sqlite)`.
>
>If the upstream package decides to add official, native CMake support, it's very possible they will choose a naming scheme that conflicts with our generated scheme. We want to support cross-platform projects, so we should switch to the upstream scheme -- but that will cause a break for current Vcpkg users. Providing both may be possible, but we'd really prefer to not to do that in the longer term.

So, the first and easiest way to resolve this would be if you could submit these changes to https://github.com/libgd/libgd. As soon as they merge the PR and indicate they're happy with the naming choices, then I'd be thrilled to merge this.

Otherwise, (if they're not currently interested but may be in the future), we need to figure out a way to avoid conflicting with any future choices `libgd` might make.

**Comment by jumpinjackie** [comment]
Ok fair enough.

In the meantime how would this vcpkg port be consumed from cmake on Windows without `find_package`? It would seem `find_path(GD_INCLUDE NAMES "gd.h")` would sort out the include path, but linker settings? 

Still learning CMake here.

**Comment by ras0219-msft** [comment]
I'd recommend something like
```cmake
find_path(GD_INCLUDE NAMES gd.h)
find_library(GD_LIBRARY NAMES libgd)

target_link_libraries(my_exe PRIVATE ${GD_LIBRARY})
target_include_directories(my_exe PRIVATE ${GD_INCLUDE})
```

https://cmake.org/cmake/help/v3.7/command/find_library.html
https://cmake.org/cmake/help/v3.7/command/target_link_libraries.html

**Comment by jumpinjackie** [comment]
Closing in favor of getting desired CMake changes upstream instead

**Pull request closed without merging**
