### PR TITLE
[x265] works on arm linux

### PR DESCRIPTION
**Pull request by fran6co**
x265 runs on linux arm, this PR enables it for it

### CODE REVIEW

**Review by JonLiu1993 — DISMISSED** [review]

**Comment by JonLiu1993** [comment]
@fran6co, please fix the conflict file ffmpeg.json.

**Comment by fran6co** [comment]
Fixed

**Comment by JonLiu1993** [comment]
@fran6co, when I tested the feature by command "./vcpkg install ffmpeg[all-gpl]" I got this error.
please take a look:
````
AILED: CMakeFiles/aom_av1_common_ssse3_intrinsics.dir/av1/common/x86/cdef_block_ssse3.c.obj 
C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x86\cl.exe    -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean -IF:\Feature-test\x256\vcpkg\buildtrees\aom\x86-windows-rel -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\apps -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\common -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\examples -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\stats -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\third_party\libyuv\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /MD /O2 /Oi /Gy /DNDEBUG /Z7  -D_WIN32_WINNT=0x0601 -DNOMINMAX /W3 /wd4996 /wd4703 /showIncludes /FoCMakeFiles\aom_av1_common_ssse3_intrinsics.dir\av1\common\x86\cdef_block_ssse3.c.obj /FdCMakeFiles\aom_av1_common_ssse3_intrinsics.dir\ /FS -c F:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\av1\common\x86\cdef_block_ssse3.c
F:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\av1\common\cdef_block_simd.h(461) : fatal error C1002: compiler is out of heap space in pass 2
F:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\aom_dsp\simd\v64_intrinsics_c.h(782) : fatal error C1002: compiler is out of heap space in pass 2
[347/402] C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x86\cl.exe    -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean -IF:\Feature-test\x256\vcpkg\buildtrees\aom\x86-windows-rel -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\apps -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\common -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\examples -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\stats -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\third_party\libyuv\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /MD /O2 /Oi /Gy /DNDEBUG /Z7  -D_WIN32_WINNT=0x0601 -DNOMINMAX /W3 /wd4996 /wd4703 /showIncludes /FoCMakeFiles\aom_av1_common_sse2_intrinsics.dir\av1\common\x86\cdef_block_sse2.c.obj /FdCMakeFiles\aom_av1_common_sse2_intrinsics.dir\ /FS -c F:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\av1\common\x86\cdef_block_sse2.c
FAILED: CMakeFiles/aom_av1_common_sse2_intrinsics.dir/av1/common/x86/cdef_block_sse2.c.obj 
C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x86\cl.exe    -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean -IF:\Feature-test\x256\vcpkg\buildtrees\aom\x86-windows-rel -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\apps -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\common -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\examples -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\stats -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\third_party\libyuv\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /MD /O2 /Oi /Gy /DNDEBUG /Z7  -D_WIN32_WINNT=0x0601 -DNOMINMAX /W3 /wd4996 /wd4703 /showIncludes /FoCMakeFiles\aom_av1_common_sse2_intrinsics.dir\av1\common\x86\cdef_block_sse2.c.obj /FdCMakeFiles\aom_av1_common_sse2_intrinsics.dir\ /FS -c F:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\av1\common\x86\cdef_block_sse2.c
F:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\aom_dsp\simd\v128_intrinsics_c.h(50) : fatal error C1002: compiler is out of heap space in pass 2
[348/402] C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x86\cl.exe    -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean -IF:\Feature-test\x256\vcpkg\buildtrees\aom\x86-windows-rel -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\apps -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\common -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\examples -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\stats -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\third_party\libyuv\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /MD /O2 /Oi /Gy /DNDEBUG /Z7  -D_WIN32_WINNT=0x0601 -DNOMINMAX /W3 /wd4996 /wd4703 /arch:AVX2 /showIncludes /FoCMakeFiles\aom_av1_common_avx2_intrinsics.dir\av1\common\x86\cdef_block_avx2.c.obj /FdCMakeFiles\aom_av1_common_avx2_intrinsics.dir\ /FS -c F:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\av1\common\x86\cdef_block_avx2.c
FAILED: CMakeFiles/aom_av1_common_avx2_intrinsics.dir/av1/common/x86/cdef_block_avx2.c.obj 
C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x86\cl.exe    -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean -IF:\Feature-test\x256\vcpkg\buildtrees\aom\x86-windows-rel -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\apps -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\common -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\examples -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\stats -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\third_party\libyuv\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /MD /O2 /Oi /Gy /DNDEBUG /Z7  -D_WIN32_WINNT=0x0601 -DNOMINMAX /W3 /wd4996 /wd4703 /arch:AVX2 /showIncludes /FoCMakeFiles\aom_av1_common_avx2_intrinsics.dir\av1\common\x86\cdef_block_avx2.c.obj /FdCMakeFiles\aom_av1_common_avx2_intrinsics.dir\ /FS -c F:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\av1\common\x86\cdef_block_avx2.c
F:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\aom_dsp\simd\v128_intrinsics_c.h(50) : fatal error C1002: compiler is out of heap space in pass 2
F:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\aom_dsp\simd\v64_intrinsics_c.h(754) : fatal error C1002: compiler is out of heap space in pass 2
[349/402] C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x86\cl.exe    -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean -IF:\Feature-test\x256\vcpkg\buildtrees\aom\x86-windows-rel -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\apps -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\common -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\examples -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\stats -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\third_party\libyuv\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /MD /O2 /Oi /Gy /DNDEBUG /Z7  -D_WIN32_WINNT=0x0601 -DNOMINMAX /W3 /wd4996 /wd4703 /showIncludes /FoCMakeFiles\aom_av1_common_sse4_intrinsics.dir\av1\common\x86\cdef_block_sse4.c.obj /FdCMakeFiles\aom_av1_common_sse4_intrinsics.dir\ /FS -c F:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\av1\common\x86\cdef_block_sse4.c
FAILED: CMakeFiles/aom_av1_common_sse4_intrinsics.dir/av1/common/x86/cdef_block_sse4.c.obj 
C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x86\cl.exe    -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean -IF:\Feature-test\x256\vcpkg\buildtrees\aom\x86-windows-rel -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\apps -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\common -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\examples -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\stats -IF:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\third_party\libyuv\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /MD /O2 /Oi /Gy /DNDEBUG /Z7  -D_WIN32_WINNT=0x0601 -DNOMINMAX /W3 /wd4996 /wd4703 /showIncludes /FoCMakeFiles\aom_av1_common_sse4_intrinsics.dir\av1\common\x86\cdef_block_sse4.c.obj /FdCMakeFiles\aom_av1_common_sse4_intrinsics.dir\ /FS -c F:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\av1\common\x86\cdef_block_sse4.c
F:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\aom_dsp\simd\v128_intrinsics_c.h(50) : fatal error C1002: compiler is out of heap space in pass 2
F:\Feature-test\x256\vcpkg\buildtrees\aom\src\2edfc9ae71-486f3907c9.clean\aom_dsp\simd\v64_intrinsics_c.h(775) : fatal error C1002: compiler is out of heap space in pass 2
ninja: build stopped: subcommand failed.

````

**Comment by fran6co** [comment]
I don't understand why it's affecting x86-windows. I just changed it so it can be built in arm-linux

**Comment by fran6co** [comment]
Reading the error message it seems that you are running out of memory while compiling

**Comment by JonLiu1993** [comment]
> I don't understand why it's affecting x86-windows. I just changed it so it can be built in arm-linux. I think that issue is unrelated with this change

when I tested the feature by command "./vcpkg install ffmpeg[x264]:arm-linux" I got this error.
please take a look: 
````
test@vzhli17001:~/vcpkg$ ./vcpkg install ffmpeg[x264]:arm-linux
Computing installation plan...
The following packages will be built and installed:
    ffmpeg[avcodec,avdevice,avfilter,avformat,core,gpl,swresample,swscale,x264]:arm-linux -> 4.4.3#2
  * pkgconf[core]:x64-linux -> 1.8.0#3
  * vcpkg-cmake[core]:x64-linux -> 2022-10-30
  * vcpkg-cmake-get-vars[core]:x64-linux -> 2022-09-04
  * vcpkg-pkgconfig-get-modules[core]:x64-linux -> 2022-02-10#1
  * vcpkg-tool-meson[core]:x64-linux -> 0.63
  * x264[asm,core,default-features]:arm-linux -> 0.164.3095#2
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-linux...
Detecting compiler hash for triplet arm-linux...
error: while detecting compiler information:
The log file content at "/home/test/vcpkg/buildtrees/detect_compiler/stdout-arm-linux.log" is:
-- Configuring arm-linux-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: /home/test/vcpkg/downloads/tools/cmake-3.25.0-linux/cmake-3.25.0-linux-x86_64/bin/cmake /home/test/vcpkg/scripts/detect_compiler -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/test/vcpkg/packages/detect_compiler_arm-linux -DCMAKE_MAKE_PROGRAM=/home/test/vcpkg/downloads/tools/ninja/1.10.2-linux/ninja -DCMAKE_SYSTEM_NAME=Linux -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/test/vcpkg/scripts/toolchains/linux.cmake -DVCPKG_TARGET_TRIPLET=arm-linux -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/home/test/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=arm -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=/home/test/vcpkg -DZ_VCPKG_ROOT_DIR=/home/test/vcpkg -D_VCPKG_INSTALLED_DIR=/home/test/vcpkg/installed -DVCPKG_MANIFEST_INSTALL=OFF -DFETCHCONTENT_FULLY_DISCONNECTED=ON
    Working Directory: /home/test/vcpkg/buildtrees/detect_compiler/arm-linux-rel
    Error code: 1
    See logs for more information:
      /home/test/vcpkg/buildtrees/detect_compiler/config-arm-linux-rel-CMakeCache.txt.log
      /home/test/vcpkg/buildtrees/detect_compiler/config-arm-linux-rel-out.log
      /home/test/vcpkg/buildtrees/detect_compiler/config-arm-linux-rel-err.log

````


/home/vzhli17/vcpkg/buildtrees/detect_compiler/config-arm-linux-rel-out.log
````
-- Cross compiling arm on host x86_64, use cross compiler: arm-linux-gnueabihf-g++/arm-linux-gnueabihf-gcc
-- The C compiler identification is unknown
-- Configuring incomplete, errors occurred!
````



/home/vzhli17/vcpkg/buildtrees/detect_compiler/config-arm-linux-rel-err.log
````
CMake Error at CMakeLists.txt:11 (enable_language):
  The CMAKE_C_COMPILER:

    arm-linux-gnueabihf-gcc

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.
````

**Comment by fran6co** [comment]
I don't think the issue is with this PR. The erros you are getting is when detecting the compiler by vcpkg.

**Comment by fran6co** [comment]
It looks like the path to the compiler is not set correctly

**Comment by fran6co** [comment]
Maybe it's because it's trying to cross compile? I'm not sure what is going on in that setup as it's installing some packages for x64-linux

**Comment by JonLiu1993** [comment]
> I don't think the issue is with this PR. The erros you are getting is when detecting the compiler by vcpkg.

Do you have a test feature locally?

**Comment by fran6co** [comment]
I did compile it locally and I got it running in an app in my jetson. Not sure how to show that here. It would be nice to add to CI arm-linux as well

**Review by JonLiu1993 — APPROVED** [review]

**Comment by fran6co** [comment]
I also cross compiled it using qemu and docker with:

```
sudo apt-get install qemu binfmt-support qemu-user-static
docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
docker run --rm -e VCPKG_FORCE_SYSTEM_BINARIES=ON --platform linux/arm64 -v <vcpkg_src>:/opt/vcpkg -w /opt/vcpkg -it <some_ubuntu_arm_image_with_build_tools> bash -c "./bootstrap-vcpkg.sh && ./vcpkg install fmpeg[x265]"
```

**Pull request merged**
