### PR TITLE
[cyclonedds] Add new port

### PR DESCRIPTION
**Pull request by ex-purple**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html)
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [x] The generated "usage text" is accurate. See docs/examples/adding-an-explicit-usage.md for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Review by BillyONeal — CHANGES_REQUESTED** [review]
Thanks for the new port!

I fixed up absolute paths in the output and added usage text.

Can you take a look at why it doesn't seem to work when with these feature combos?

cyclonedds[core] passed  
cyclonedds[ddsperf,deadline-missed,idlc,ipv6,lifespan,security,shm,source-specific-multicast,ssl,topic-discovery,type-discovery] failed due to Windows  
cyclonedds[ddsperf,deadline-missed,idlc,ipv6,lifespan,security,shm,source-specific-multicast,ssl,topic-discovery,type-discovery] failed on Linux:  

```
FAILED: bin/idlc
: && /usr/bin/cc -fPIC -g  src/tools/idlc/CMakeFiles/idlc.dir/src/idlc.c.o src/tools/idlc/CMakeFiles/idlc.dir/src/plugin.c.o src/tools/idlc/CMakeFiles/idlc.dir/src/options.c.o src/tools/idlc/CMakeFiles/idlc.dir/src/generator.c.o src/tools/idlc/CMakeFiles/idlc.dir/src/descriptor.c.o src/tools/idlc/CMakeFiles/idlc.dir/src/types.c.o src/tools/idlc/CMakeFiles/idlc.dir/src/descriptor_type_meta.c.o -o bin/idlc  -Wl,-rpath,/home/bion/vcpkg/buildtrees/cyclonedds/x64-linux-dbg/lib:  lib/libcycloneddsidl.so.0.10.2  lib/libidlpp.a  lib/libddsc.a  -ldl  /home/bion/vcpkg/installed/x64-linux/debug/lib/libssl.a  /home/bion/vcpkg/installed/x64-linux/debug/lib/libcrypto.a  /home/bion/vcpkg/installed/x64-linux/debug/lib/libiceoryx_binding_c.a  -lstdc++  /home/bion/vcpkg/installed/x64-linux/debug/lib/libiceoryx_posh.a  /home/bion/vcpkg/installed/x64-linux/debug/lib/libiceoryx_hoofs.a  /home/bion/vcpkg/installed/x64-linux/debug/lib/libiceoryx_platform.a  -lpthread  -lrt  -lacl  -latomic  -ldl  -lpthread && :
/usr/bin/ld: cannot find -lacl
collect2: error: ld returned 1 exit status
```

cyclonedds[ddsperf,deadline-missed,idlc,ipv6,lifespan,security,source-specific-multicast,ssl,topic-discovery,type-discovery] failed

```
[255/262] cmd.exe /C "cd /D C:\Dev\vcpkg\buildtrees\cyclonedds\x64-windows-dbg\src\tools\ddsperf && C:\Dev\vcpkg\buildtrees\cyclonedds\x64-windows-dbg\bin\idlc.exe -Wno-implicit-extensibility -oC:/Dev/vcpkg/buildtrees/cyclonedds/x64-windows-dbg/src/tools/ddsperf C:/Dev/vcpkg/buildtrees/cyclonedds/src/0.10.2-7b64d80da3.clean/src/tools/ddsperf/ddsperf_types.idl"
FAILED: src/tools/ddsperf/ddsperf_types.c src/tools/ddsperf/ddsperf_types.h C:/Dev/vcpkg/buildtrees/cyclonedds/x64-windows-dbg/src/tools/ddsperf/ddsperf_types.c C:/Dev/vcpkg/buildtrees/cyclonedds/x64-windows-dbg/src/tools/ddsperf/ddsperf_types.h 
cmd.exe /C "cd /D C:\Dev\vcpkg\buildtrees\cyclonedds\x64-windows-dbg\src\tools\ddsperf && C:\Dev\vcpkg\buildtrees\cyclonedds\x64-windows-dbg\bin\idlc.exe -Wno-implicit-extensibility -oC:/Dev/vcpkg/buildtrees/cyclonedds/x64-windows-dbg/src/tools/ddsperf C:/Dev/vcpkg/buildtrees/cyclonedds/src/0.10.2-7b64d80da3.clean/src/tools/ddsperf/ddsperf_types.idl"
ninja: build stopped: subcommand failed.
```

Do you know what happened here? This looks like it will be mishandled in cross-compilation scenarios. Perhaps whatever makes C:\Dev\vcpkg\buildtrees\cyclonedds\x64-windows-dbg\bin\idlc.exe should be hooked up and plumbed in as a host dependency?

cyclonedds[deadline-missed,idlc,ipv6,lifespan,security,source-specific-multicast,ssl,topic-discovery,type-discovery] pass  
cyclonedds[idlc,ipv6,lifespan,security,source-specific-multicast,ssl,topic-discovery,type-discovery] pass  
cyclonedds[deadline-missed,ipv6,lifespan,security,source-specific-multicast,ssl,topic-discovery,type-discovery] pass  
cyclonedds[deadline-missed,idlc,lifespan,security,source-specific-multicast,ssl,topic-discovery,type-discovery] pass  
cyclonedds[deadline-missed,idlc,ipv6,security,source-specific-multicast,ssl,topic-discovery,type-discovery] pass  
cyclonedds[deadline-missed,idlc,ipv6,lifespan,source-specific-multicast,ssl,topic-discovery,type-discovery] pass  
cyclonedds[deadline-missed,idlc,ipv6,lifespan,security,ssl,topic-discovery,type-discovery] pass  
cyclonedds[deadline-missed,idlc,ipv6,lifespan,security,source-specific-multicast,topic-discovery,type-discovery] pass  
cyclonedds[deadline-missed,idlc,ipv6,lifespan,security,source-specific-multicast,ssl] pass

**Comment by ex-purple** [comment]
Hello @BillyONeal,

> cyclonedds[ddsperf,deadline-missed,idlc,ipv6,lifespan,security,shm,source-specific-multicast,ssl,topic-discovery,type-discovery] failed due to Windows

First, shm feature is not supported on Windows. 
`message(STATUS "Warning: iceoryx binding for Windows currently not supported")`
What about the rest. Unfortunately, I don't have a Windows build environment to reproduce this. Do you have more information on this issue?

> cyclonedds[ddsperf,deadline-missed,idlc,ipv6,lifespan,security,shm,source-specific-multicast,ssl,topic-discovery,type-discovery] failed on Linux:
/usr/bin/ld: cannot find -lacl

acl is a linux-only dependency of the iceoryx package. What is the correct way to link it? For example, I can make patch for linking acl library and idlc tool.


> Perhaps whatever makes C:\Dev\vcpkg\buildtrees\cyclonedds\x64-windows-dbg\bin\idlc.exe should be hooked up and plumbed in as a host dependency?

Yes, it is make sense. I updated a ddsperf dependency of the idlc. Now it is a host dependency.

**Comment by BillyONeal** [comment]
>First, shm feature is not supported on Windows.
message(STATUS "Warning: iceoryx binding for Windows currently not supported")

Sorry, I should have clarified. I was only noting that I tested that, not saying that it had to work. It's correctly annotated in `vcpkg.json` so the user doesn't spend forever building something that will explode which is great!

>acl is a linux-only dependency of the iceoryx package. What is the correct way to link it? For example, I can make patch for linking acl library and idlc tool.

Do we have a port for it you can list as a dependency that will just make it work? I observe that we do have https://github.com/microsoft/vcpkg/tree/master/ports/acl but I'm not sure if that's what the port is looking for.

>What about the rest. Unfortunately, I don't have a Windows build environment to reproduce this. Do you have more information on this issue?

It looks like it's building a thing that crashes. Try fixing the acl thing first and we'll see about this one then.

Thanks again!

**Comment by ex-purple** [comment]
> Do we have a port for it you can list as a dependency that will just make it work? I observe that we do have https://github.com/microsoft/vcpkg/tree/master/ports/acl but I'm not sure if that's what the port is looking for.

Yes, it is right port. I added it, because cyclonedds[shm] depends on iceoryx and iceoryx depends on acl. All dependencies are listed. On the Linux, acl is installed for the cyclone[shm]. But it seems that this is not enough for proper linking. I don't know how to solve this yet, but I'll try to do it.

**Comment by ex-purple** [comment]
Depends on https://github.com/microsoft/vcpkg/pull/29257

**Review by BillyONeal — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the new port!

**Pull request merged**
