### PR TITLE
[idyntree] Update to 10.0.0 

### PR DESCRIPTION
**Pull request by traversaro**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [x] The "supports" clause reflects platforms that may be fixed by this new version
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by MonicaLiu0311** [comment]
Please get [failure logs here](https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/95509/artifacts?artifactName=failure%20logs%20for%20x64-windows&api-version=7.1&%24format=zip): 
```
CMake Error at scripts/cmake/vcpkg_install_copyright.cmake:27 (message):
  

  vcpkg_install_copyright was passed a non-existing path:
  D:/buildtrees/idyntree/src/v10.0.0-287170927b.clean/LICENSE.LGPL2

Call Stack (most recent call first):
  ports/idyntree/portfile.cmake:54 (vcpkg_install_copyright)
  scripts/ports.cmake:168 (include)
```

**Comment by MonicaLiu0311** [comment]
Note: I will be converting your PR to draft status. When you're ready, please revert to "ready for review".

**Comment by traversaro** [comment]
> Note: I will be converting your PR to draft status. When you're ready, please revert to "ready for review".

Thanks, the problem should have been fixed now.

**Comment by MonicaLiu0311** [comment]
All features are tested successfully in the following triplet:
```
x64-linux
```

Feature `assimp` is tested successfully in the following triplet:
```
x86-windows
x64-windows
x64-windows-static
```

The usage test passed on `x64-windows` (header files found): 
```
The package idyntree provides CMake targets:

    find_package(iDynTree CONFIG REQUIRED)
    target_link_libraries(main PRIVATE iDynTree::idyntree-core iDynTree::idyntree-model iDynTree::idyntree-modelio iDynTree::idyntree-modelio iDynTree::idyntree-high-level iDynTree::idyntree-estimation)
```

**Review by MonicaLiu0311 — APPROVED** [review]

**Pull request merged**
