### PR TITLE
[vcpkg baseline][vtk-m] fix the sha512

### PR DESCRIPTION
**Pull request by strega-nil**
**Describe the pull request**

- What does your PR fix? Fixes #

- Which triplets are supported/not supported? Have you updated the CI baseline?

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

### CODE REVIEW

**Comment by Neumann-A** [comment]
osx already disagrees with that change.

**Comment by strega-nil** [comment]
@Neumann-A this is because osx has a cached binary that is wrong

**Comment by Neumann-A** [comment]
any knowledge why the SHA changed?

**Review by NancyLi1013 — APPROVED** [review]
Do we need to update version in CONTROL file?

**Comment by JackBoosY** [comment]
@Neumann-A  Do you know what has changed in the current version?

**Comment by strega-nil** [comment]
I believe this is the same issue as #14343.

**Comment by NancyLi1013** [comment]
@strega-nil 

Please help merge this PR first if all CI checks pass.

**Comment by strega-nil** [comment]
Merging as "the only issue was strawberry perl not downloading"

**Pull request merged**
