### PR TITLE
[ctp] bugfix for linux-x64 and file name case sensitivity

### PR DESCRIPTION
**Pull request by xgao1023**
[ctp] Bugfix for Linux build

- fix the issue of Linux installation due to wrong archive file name; fix the debug folder name (Debug -> debug)

### CODE REVIEW

**Review by NancyLi1013 — COMMENTED** [review]
Could you please also bump the version in CONTROL file? Add `Port-Version: 1`

**Comment by xgao1023** [comment]
> Could you please also bump the version in CONTROL file? Add `Port-Version: 1`

Done in commit 68d364b0f3bf8827fe4dc0343d8d5de151c8bb74

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
@xgao1023 

Have you tested feature `datacollect`?

**Comment by NancyLi1013** [comment]
Feature has passed with the following triplets:

- x86-windows
- x64-windows
- x64-linux

Note: ctp only supports dynamic build.

**Comment by BillyONeal** [comment]
Thanks for the fix!

**Pull request merged**
