### PR TITLE
[scotch] update to v7.0.5

### PR DESCRIPTION
**Pull request by Mengna-Li**
Update to v7.0.5.
No feature need to test.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [ ] ~The "supports" clause reflects platforms that may be fixed by this new version.~
- [ ] ~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~
- [ ] ~Any patches that are no longer applied are deleted from the port's directory.~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Review by FrankXie05 — DISMISSED** [review]

**Comment by data-queue** [comment]
Can you explain why we run `add_library(scotcherr ...)` twice in the patch?

**Comment by Mengna-Li** [comment]
> Can you explain why we run `add_library(scotcherr ...)` twice in the patch?

These two are different.
```
add_library(scotcherr library_error.c)
add_library(scotcherrexit library_error_exit.c)
```
In fact, I didn't change the content of the patch, I just applied the previous patch to the latest release.

**Comment by data-queue** [comment]
In the final patch, we run `add_library(scotcherr library_error.c)` twice

**Comment by dg0yt** [comment]
The patch seems to need a thorough review.

**Review by data-queue — APPROVED** [review]

**Pull request merged**
