### PR TITLE
[skia] Update version to 0.38.2

### LINKED ISSUE #34769: [skia] update to 0.39.1 (or 0.38.2 at least)
### Library name

skia

### New version number

0.39.1

### Other information that may be useful (release notes, etc...)

0.39.1 doesn't seem to be tagged, but it exists on the changelog (talking about `canvaskit_0.39.1` which seems to be what vcpkg tracks, as Skia itself uses Milestones from Chromium, last one is Milestone 119 https://github.com/google/skia/blob/main/RELEASE_NOTES.md )

### PR DESCRIPTION
**Pull request by FrankXie05**
Fix https://github.com/microsoft/vcpkg/issues/34769

Upstream has merged the patch `disable-msvc-env-setup.patch`.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by dg0yt** [comment]
NB: The key challenge is to update the dependencies which are downloaded and built as part of the port.

**Comment by FrankXie05** [comment]
> NB: The key challenge is to update the dependencies which are downloaded and built as part of the port.

Do you mean this:
```
declare_external_from_git(
```

**Review by JonLiu1993 — APPROVED** [review]

**Comment by dg0yt** [comment]
Did the new patch achieve anything which old patch didn't.

IMO this is an incomplete update, not nearly the same as native skia 0.38.2 build. There is a long lost of dependencies which are normally downloaded as part of the gn build. I even added warning output as a help, but it seems to be ignored.

**Comment by autoantwort** [comment]
This caused https://github.com/microsoft/vcpkg/issues/34896

**Comment by JonLiu1993** [comment]
@FrankXie05

**Pull request merged**
