### PR TITLE
[highway] Bump to 1.2.0

### PR DESCRIPTION
**Pull request by xiaozhuai**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [x] The "supports" clause reflects platforms that may be fixed by this new version.
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by xiaozhuai** [comment]
The CI failed on `libjxl` port.
I took a look at the `libjxl` port and found that things were a mess and the `libjxl` port needed to be refactored.

**Comment by xiaozhuai** [comment]
Hello @LilyWangLL 
The `libjxl` port has been fixed. This pr is ready for review now.

**Comment by LilyWangLL** [comment]
The new version of `highway[contrib]` build failed with the following error, could you please fix this error?
```
C:\PROGRA~1\MICROS~3\2022\ENTERP~1\VC\Tools\MSVC\1440~1.338\bin\Hostx64\x64\cl.exe   /TP -DHWY_SHARED_DEFINE -DTOOLCHAIN_MISS_ASM_HWCAP_H -DTOOLCHAIN_MISS_SYS_AUXV_H -Dhwy_contrib_EXPORTS -IF:\PRreview\vcpkg\buildtrees\highway\src\1.2.0-6e50e13274.clean /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++17 /bigobj /W4 /wd4100 /wd4127 /wd4324 /wd4456 /wd4701 /wd4702 /wd4723 /GR- /EHs-c- -D_HAS_EXCEPTIONS=0 /showIncludes /FoCMakeFiles\hwy_contrib.dir\hwy\contrib\thread_pool\topology.cc.obj /FdCMakeFiles\hwy_contrib.dir\ /FS -c F:\PRreview\vcpkg\buildtrees\highway\src\1.2.0-6e50e13274.clean\hwy\contrib\thread_pool\topology.cc
cl : Command line warning D9025 : overriding '/W3' with '/W4'
cl : Command line warning D9025 : overriding '/GR' with '/GR-'
cl : Command line warning D9025 : overriding '/EHs' with '/EHs-'
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
F:\PRreview\vcpkg\buildtrees\highway\src\1.2.0-6e50e13274.clean\hwy\contrib\thread_pool\topology.cc(67): error C2491: 'hwy::HaveThreadingSupport': definition of dllimport function not allowed
F:\PRreview\vcpkg\buildtrees\highway\src\1.2.0-6e50e13274.clean\hwy\contrib\thread_pool\topology.cc(75): error C2491: 'hwy::TotalLogicalProcessors': definition of dllimport function not allowed
F:\PRreview\vcpkg\buildtrees\highway\src\1.2.0-6e50e13274.clean\hwy\contrib\thread_pool\topology.cc(114): error C2491: 'hwy::GetThreadAffinity': definition of dllimport function not allowed
F:\PRreview\vcpkg\buildtrees\highway\src\1.2.0-6e50e13274.clean\hwy\contrib\thread_pool\topology.cc(176): error C2491: 'hwy::SetThreadAffinity': definition of dllimport function not allowed
F:\PRreview\vcpkg\buildtrees\highway\src\1.2.0-6e50e13274.clean\hwy\contrib\thread_pool\topology.cc(388): error C2491: 'hwy::Topology::Topology': definition of dllimport function not allowed
```

**Comment by xiaozhuai** [comment]
> The new version of highway[contrib] build failed with the following error, could you please fix this error?

@LilyWangLL OK, I'll look into it.

**Comment by xiaozhuai** [comment]
@LilyWangLL 
Please review this again. The compile error has been solved by https://github.com/google/highway/pull/2229, but not it's not included in version 1.2.0. We need a patch here.

**Comment by LilyWangLL** [comment]
All features passed with following triplets:
```
x86-windows
x64-windows
x64-windows-static
```
Usage test passed on `x64-windows`.

**Review by LilyWangLL — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the update!

**Pull request merged**
