### PR TITLE
[skia] update to 126

### PR DESCRIPTION
**Pull request by abique**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [x] The "supports" clause reflects platforms that may be fixed by this new version.
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by abique** [comment]
x64_uwp failure:
```
FAILED: obj/src/pdf/pdf.SkPDFSubsetFont.obj 
"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC/Tools/MSVC/14.38.33130/bin/HostX64/x64/cl.exe" /nologo /showIncludes /FC -D_CRT_SECURE_NO_WARNINGS -D_HAS_EXCEPTIONS=0 -DWIN32_LEAN_AND_MEAN -DNOMINMAX -DSK_CODEC_DECODES_BMP -DSK_CODEC_DECODES_WBMP -DSKIA_DLL -DSK_ENABLE_PRECOMPILE -DSK_GANESH -DSK_GAMMA_APPLY_TO_A8 -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=1 -DGR_TEST_UTILS=0 -DSK_WINUWP -DSK_ENABLE_AVX512_OPTS -DSKIA_IMPLEMENTATION=1 -DSK_SUPPORT_PDF -DSK_CODEC_DECODES_JPEG "-IC:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.38.33130/include" "-IC:/Program Files (x86)/Windows Kits/10/Include/10.0.22621.0/shared" "-IC:/Program Files (x86)/Windows Kits/10/Include/10.0.22621.0/ucrt" "-IC:/Program Files (x86)/Windows Kits/10/Include/10.0.22621.0/um" "-IC:/Program Files (x86)/Windows Kits/10/Include/10.0.22621.0/winrt" -I../src/f4d1f7e488-c77bada2e9.clean -ID:/installed/x64-uwp/include /wd5030 /wd5051 /bigobj /utf-8 /Z7 /W3 /wd4244 /wd4267 /wd4800 /wd4291 /wd4251 /wd4275 /wd4723 /wd5041  /std:c++17 /GR- -DWIN32 -D_WINDOWS -D_UNICODE -DUNICODE -DWINAPI_FAMILY=WINAPI_FAMILY_APP -D__WRL_NO_DEFAULT_LIB__ -nologo -Z7 -MP -GS -Gd -Gm- -W3 -WX- -Zc:wchar_t -Zc:inline -Zc:forScope -fp:precise -Oy- -EHsc -utf-8 -D_DEBUG -MDd -Od -RTC1 -ZW:nostdlib /c ../src/f4d1f7e488-c77bada2e9.clean/src/pdf/SkPDFSubsetFont.cpp /Foobj/src/pdf/pdf.SkPDFSubsetFont.obj /Fd"obj/pdf_c.pdb"
D:\b\skia\src\f4d1f7e488-c77bada2e9.clean\include\core\SkRefCnt.h(151): error C2027: use of undefined type 'SkData'
D:\b\skia\src\f4d1f7e488-c77bada2e9.clean\src\pdf\SkPDFSubsetFont.h(9): note: see declaration of 'SkData'
D:\b\skia\src\f4d1f7e488-c77bada2e9.clean\include\core\SkRefCnt.h(151): note: the template instantiation context (the oldest one first) is
D:\b\skia\src\f4d1f7e488-c77bada2e9.clean\src\pdf\SkPDFSubsetFont.cpp(109): note: see reference to class template instantiation 'sk_sp<SkData>' being compiled
D:\b\skia\src\f4d1f7e488-c77bada2e9.clean\include\core\SkRefCnt.h(255): note: while compiling class template member function 'sk_sp<SkData>::~sk_sp(void)'
D:\b\skia\src\f4d1f7e488-c77bada2e9.clean\src\pdf\SkPDFSubsetFont.cpp(110): note: see the first reference to 'sk_sp<SkData>::~sk_sp' in 'SkPDFSubsetFont'
D:\b\skia\src\f4d1f7e488-c77bada2e9.clean\include\core\SkRefCnt.h(256): note: see reference to function template instantiation 'void SkSafeUnref<T>(T *)' being compiled
        with
        [
            T=SkData
        ]
```

**Comment by abique** [comment]
x64_windows failure:
```
[2278/2281] link skunicode_icu.dll skunicode_icu.dll.lib skunicode_icu.dll.pdb
FAILED: skunicode_icu.dll skunicode_icu.dll.lib skunicode_icu.dll.pdb 
"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC/Tools/MSVC/14.38.33130/bin/HostX64/x64/link.exe" /nologo /IMPLIB:./skunicode_icu.dll.lib /DLL /OUT:./skunicode_icu.dll /PDB:./skunicode_icu.dll.pdb @./skunicode_icu.dll.rsp
   Creating library ./skunicode_icu.dll.lib and object ./skunicode_icu.dll.exp
skunicode_icu.SkUnicode_icu_builtin.obj : error LNK2019: unresolved external symbol u_errorName referenced in function "class std::unique_ptr<struct SkICULib,struct std::default_delete<struct SkICULib> > __cdecl SkLoadICULib(void)" (?SkLoadICULib@@YA?AV?$unique_ptr@USkICULib@@U?$default_delete@USkICULib@@@std@@@std@@XZ)
skunicode_icu.SkUnicode_icu_builtin.obj : error LNK2019: unresolved external symbol u_hasBinaryProperty referenced in function "class std::unique_ptr<struct SkICULib,struct std::default_delete<struct SkICULib> > __cdecl SkLoadICULib(void)" (?SkLoadICULib@@YA?AV?$unique_ptr@USkICULib@@U?$default_delete@USkICULib@@@std@@@std@@XZ)
skunicode_icu.SkUnicode_icu_builtin.obj : error LNK2019: unresolved external symbol u_getIntPropertyValue referenced in function "class std::unique_ptr<struct SkICULib,struct std::default_delete<struct SkICULib> > __cdecl SkLoadICULib(void)" (?SkLoadICULib@@YA?AV?$unique_ptr@USkICULib@@U?$default_delete@USkICULib@@@std@@@std@@XZ)
skunicode_icu.SkUnicode_icu_builtin.obj : error LNK2019: unresolved external symbol u_isspace referenced in function "class std::unique_ptr<struct SkICULib,struct std::default_delete<struct SkICULib> > __cdecl SkLoadICULib(void)" (?SkLoadICULib@@YA?AV?$unique_ptr@USkICULib@@U?$default_delete@USkICULib@@@std@@@std@@XZ)
skunicode_icu.SkUnicode_icu_builtin.obj : error LNK2019: unresolved external symbol u_isWhitespace referenced in function "class std::unique_ptr<struct SkICULib,struct std::default_delete<struct SkICULib> > __cdecl SkLoadICULib(void)" (?SkLoadICULib@@YA?AV?$unique_ptr@USkICULib@@U?$default_delete@USkICULib@@@std@@@std@@XZ)
skunicode_icu.SkUnicode_icu_builtin.obj : error LNK2019: unresolved external symbol u_iscntrl referenced in function "class std::unique_ptr<struct SkICULib,struct std::default_delete<struct SkICULib> > __cdecl SkLoadICULib(void)" (?SkLoadICULib@@YA?AV?$unique_ptr@USkICULib@@U?$default_delete@USkICULib@@@std@@@std@@XZ)
skunicode_icu.SkUnicode_icu_builtin.obj : error LNK2019: unresolved external symbol ubidi_openSized referenced in function "class std::unique_ptr<struct SkICULib,struct std::default_delete<struct SkICULib> > __cdecl SkLoadICULib(void)" (?SkLoadICULib@@YA?AV?$unique_ptr@USkICULib@@U?$default_delete@USkICULib@@@std@@@std@@XZ)
skunicode_icu.SkUnicode_icu_builtin.obj : error LNK2019: unresolved external symbol ubidi_close referenced in function "class std::unique_ptr<struct SkICULib,struct std::default_delete<struct SkICULib> > __cdecl SkLoadICULib(void)" (?SkLoadICULib@@YA?AV?$unique_ptr@USkICULib@@U?$default_delete@USkICULib@@@std@@@std@@XZ)
skunicode_icu.SkUnicode_icu_builtin.obj : error LNK2019: unresolved external symbol ubidi_setPara referenced in function "class std::unique_ptr<struct SkICULib,struct std::default_delete<struct SkICULib> > __cdecl SkLoadICULib(void)" (?SkLoadICULib@@YA?AV?$unique_ptr@USkICULib@@U?$default_delete@USkICULib@@@std@@@std@@XZ)
skunicode_icu.SkUnicode_icu_builtin.obj : error LNK2019: unresolved external symbol ubidi_getDirection referenced in function "class std::unique_ptr<struct SkICULib,struct std::default_delete<struct SkICULib> > __cdecl SkLoadICULib(void)" (?SkLoadICULib@@YA?AV?$unique_ptr@USkICULib@@U?$default_delete@USkICULib@@@std@@@std@@XZ)
skunicode_icu.SkUnicode_icu_builtin.obj : error LNK2019: unresolved external symbol ubidi_getLength referenced in function "class std::unique_ptr<struct SkICULib,struct std::default_delete<struct SkICULib> > __cdecl SkLoadICULib(void)" (?SkLoadICULib@@YA?AV?$unique_ptr@USkICULib@@U?$default_delete@USkICULib@@@std@@@std@@XZ)
skunicode_icu.SkUnicode_icu_builtin.obj : error LNK2019: unresolved external symbol ubidi_getLevelAt referenced in function "class std::unique_ptr<struct SkICULib,struct std::default_delete<struct SkICULib> > __cdecl SkLoadICULib(void)" (?SkLoadICULib@@YA?AV?$unique_ptr@USkICULib@@U?$default_delete@USkICULib@@@std@@@std@@XZ)
skunicode_icu.SkUnicode_icu_builtin.obj : error LNK2019: unresolved external symbol ubidi_reorderVisual referenced in function "class std::unique_ptr<struct SkICULib,struct std::default_delete<struct SkICULib> > __cdecl SkLoadICULib(void)" (?SkLoadICULib@@YA?AV?$unique_ptr@USkICULib@@U?$default_delete@USkICULib@@@std@@@std@@XZ)
skunicode_icu.SkUnicode_icu_builtin.obj : error LNK2019: unresolved external symbol uloc_getDefault referenced in function "class std::unique_ptr<struct SkICULib,struct std::default_delete<struct SkICULib> > __cdecl SkLoadICULib(void)" (?SkLoadICULib@@YA?AV?$unique_ptr@USkICULib@@U?$default_delete@USkICULib@@@std@@@std@@XZ)
skunicode_icu.SkUnicode_icu_builtin.obj : error LNK2019: unresolved external symbol uloc_forLanguageTag referenced in function "class std::unique_ptr<struct SkICULib,struct std::default_delete<struct SkICULib> > __cdecl SkLoadICULib(void)" (?SkLoadICULib@@YA?AV?$unique_ptr@USkICULib@@U?$default_delete@USkICULib@@@std@@@std@@XZ)
skunicode_icu.SkUnicode_icu_builtin.obj : error LNK2019: unresolved external symbol utext_close referenced in function "class std::unique_ptr<struct SkICULib,struct std::default_delete<struct SkICULib> > __cdecl SkLoadICULib(void)" (?SkLoadICULib@@YA?AV?$unique_ptr@USkICULib@@U?$default_delete@USkICULib@@@std@@@std@@XZ)
skunicode_icu.SkUnicode_icu_builtin.obj : error LNK2019: unresolved external symbol utext_openUTF8 referenced in function "class std::unique_ptr<struct SkICULib,struct std::default_delete<struct SkICULib> > __cdecl SkLoadICULib(void)" (?SkLoadICULib@@YA?AV?$unique_ptr@USkICULib@@U?$default_delete@USkICULib@@@std@@@std@@XZ)
skunicode_icu.SkUnicode_icu_builtin.obj : error LNK2019: unresolved external symbol utext_openUChars referenced in function "class std::unique_ptr<struct SkICULib,struct std::default_delete<struct SkICULib> > __cdecl SkLoadICULib(void)" (?SkLoadICULib@@YA?AV?$unique_ptr@USkICULib@@U?$default_delete@USkICULib@@@std@@@std@@XZ)
skunicode_icu.SkUnicode_icu_builtin.obj : error LNK2019: unresolved external symbol ubrk_open referenced in function "class std::unique_ptr<struct SkICULib,struct std::default_delete<struct SkICULib> > __cdecl SkLoadICULib(void)" (?SkLoadICULib@@YA?AV?$unique_ptr@USkICULib@@U?$default_delete@USkICULib@@@std@@@std@@XZ)
skunicode_icu.SkUnicode_icu_builtin.obj : error LNK2019: unresolved external symbol ubrk_clone referenced in function "public: static struct UBreakIterator * __cdecl `anonymous namespace'::SkUbrkClone<struct UBreakIterator const *,void>::clone(struct UBreakIterator const *,enum UErrorCode *)" (?clone@?$SkUbrkClone@PEBUUBreakIterator@@X@?A0x2141876c@@SAPEAUUBreakIterator@@PEBU3@PEAW4UErrorCode@@@Z)
skunicode_icu.SkUnicode_icu_builtin.obj : error LNK2019: unresolved external symbol ubrk_close referenced in function "class std::unique_ptr<struct SkICULib,struct std::default_delete<struct SkICULib> > __cdecl SkLoadICULib(void)" (?SkLoadICULib@@YA?AV?$unique_ptr@USkICULib@@U?$default_delete@USkICULib@@@std@@@std@@XZ)
skunicode_icu.SkUnicode_icu_builtin.obj : error LNK2019: unresolved external symbol ubrk_setText referenced in function "class std::unique_ptr<struct SkICULib,struct std::default_delete<struct SkICULib> > __cdecl SkLoadICULib(void)" (?SkLoadICULib@@YA?AV?$unique_ptr@USkICULib@@U?$default_delete@USkICULib@@@std@@@std@@XZ)
skunicode_icu.SkUnicode_icu_builtin.obj : error LNK2019: unresolved external symbol ubrk_setUText referenced in function "class std::unique_ptr<struct SkICULib,struct std::default_delete<struct SkICULib> > __cdecl SkLoadICULib(void)" (?SkLoadICULib@@YA?AV?$unique_ptr@USkICULib@@U?$default_delete@USkICULib@@@std@@@std@@XZ)
skunicode_icu.SkUnicode_icu_builtin.obj : error LNK2019: unresolved external symbol ubrk_current referenced in function "class std::unique_ptr<struct SkICULib,struct std::default_delete<struct SkICULib> > __cdecl SkLoadICULib(void)" (?SkLoadICULib@@YA?AV?$unique_ptr@USkICULib@@U?$default_delete@USkICULib@@@std@@@std@@XZ)
skunicode_icu.SkUnicode_icu_builtin.obj : error LNK2019: unresolved external symbol ubrk_next referenced in function "class std::unique_ptr<struct SkICULib,struct std::default_delete<struct SkICULib> > __cdecl SkLoadICULib(void)" (?SkLoadICULib@@YA?AV?$unique_ptr@USkICULib@@U?$default_delete@USkICULib@@@std@@@std@@XZ)
skunicode_icu.SkUnicode_icu_builtin.obj : error LNK2019: unresolved external symbol ubrk_first referenced in function "class std::unique_ptr<struct SkICULib,struct std::default_delete<struct SkICULib> > __cdecl SkLoadICULib(void)" (?SkLoadICULib@@YA?AV?$unique_ptr@USkICULib@@U?$default_delete@USkICULib@@@std@@@std@@XZ)
skunicode_icu.SkUnicode_icu_builtin.obj : error LNK2019: unresolved external symbol ubrk_preceding referenced in function "class std::unique_ptr<struct SkICULib,struct std::default_delete<struct SkICULib> > __cdecl SkLoadICULib(void)" (?SkLoadICULib@@YA?AV?$unique_ptr@USkICULib@@U?$default_delete@USkICULib@@@std@@@std@@XZ)
skunicode_icu.SkUnicode_icu_builtin.obj : error LNK2019: unresolved external symbol ubrk_following referenced in function "class std::unique_ptr<struct SkICULib,struct std::default_delete<struct SkICULib> > __cdecl SkLoadICULib(void)" (?SkLoadICULib@@YA?AV?$unique_ptr@USkICULib@@U?$default_delete@USkICULib@@@std@@@std@@XZ)
skunicode_icu.SkUnicode_icu_builtin.obj : error LNK2019: unresolved external symbol ubrk_getRuleStatus referenced in function "class std::unique_ptr<struct SkICULib,struct std::default_delete<struct SkICULib> > __cdecl SkLoadICULib(void)" (?SkLoadICULib@@YA?AV?$unique_ptr@USkICULib@@U?$default_delete@USkICULib@@@std@@@std@@XZ)
skunicode_icu.SkUnicode_icu_builtin.obj : error LNK2019: unresolved external symbol ubrk_getLocaleByType referenced in function "public: static char const * __cdecl `anonymous namespace'::SkUbrkGetLocaleByType<struct UBreakIterator const *,void>::getLocaleByType(struct UBreakIterator const *,enum ULocDataLocaleType,enum UErrorCode *)" (?getLocaleByType@?$SkUbrkGetLocaleByType@PEBUUBreakIterator@@X@?A0x2141876c@@SAPEBDPEBUUBreakIterator@@W4ULocDataLocaleType@@PEAW4UErrorCode@@@Z)
skunicode_icu.SkUnicode_icu_builtin.obj : error LNK2019: unresolved external symbol uscript_getScript referenced in function "class std::unique_ptr<struct SkICULib,struct std::default_delete<struct SkICULib> > __cdecl SkLoadICULib(void)" (?SkLoadICULib@@YA?AV?$unique_ptr@USkICULib@@U?$default_delete@USkICULib@@@std@@@std@@XZ)
skunicode_icu.SkUnicode_icu_builtin.obj : error LNK2019: unresolved external symbol u_strToUpper referenced in function "class std::unique_ptr<struct SkICULib,struct std::default_delete<struct SkICULib> > __cdecl SkLoadICULib(void)" (?SkLoadICULib@@YA?AV?$unique_ptr@USkICULib@@U?$default_delete@USkICULib@@@std@@@std@@XZ)

.\skunicode_icu.dll : fatal error LNK1120: 32 unresolved externals
```

**Comment by abique** [comment]
Maybe we need a more recent version of ICU for skia.

**Comment by abique** [comment]
it seems that ICU 75.1 is out.
https://icu.unicode.org/download/75

**Comment by abique** [comment]
I pushed an update to ICU as well to 75.1.

**Comment by dg0yt** [comment]
It is not a problem with *our* icu. It is the problem of picking icu link libs from the windows SDK. This is what took so long to fix in the previous revision of skia.

And for the icu update: you don't want to touch it now: https://github.com/microsoft/vcpkg/pull/38826

**Comment by abique** [comment]
I reverted the ICU change.

**Comment by dg0yt** [comment]
I don't know where the icu problems come from. The build is using full filepaths for the icu libs, according to `desc-x64-windows-dbg-out.log`:
~~~
"D:/installed/x64-windows/debug/lib/icuucd.lib", "D:/installed/x64-windows/debug/lib/icudtd.lib"
~~~
I would probably manually "bisect" the changes since m124 in https://github.com/google/skia/commits/chrome/m126/modules/skunicode, limiting CI to x64-windows, and then study the changes at the failing commit.

**Comment by dg0yt** [comment]
In addition, I spotted a bug in `skia-functions.cmake` line 149:
~~~diff
-    set(libdirs_DEBUG "${CURRENT_INSTALLED_DIR}/lib/debug")
+    set(libdirs_DEBUG "${CURRENT_INSTALLED_DIR}/debug/lib")
~~~

**Comment by abique** [comment]
> In addition, I spotted a bug in `skia-functions.cmake` line 149:
> 
> ```diff
> -    set(libdirs_DEBUG "${CURRENT_INSTALLED_DIR}/lib/debug")
> +    set(libdirs_DEBUG "${CURRENT_INSTALLED_DIR}/debug/lib")
> ```

I can add that one.

**Comment by abique** [comment]
> I don't know where the icu problems come from. The build is using full filepaths for the icu libs, according to `desc-x64-windows-dbg-out.log`:
> 
> ```
> "D:/installed/x64-windows/debug/lib/icuucd.lib", "D:/installed/x64-windows/debug/lib/icudtd.lib"
> ```
> 
> I would probably manually "bisect" the changes since m124 in https://github.com/google/skia/commits/chrome/m126/modules/skunicode, limiting CI to x64-windows, and then study the changes at the failing commit.

I may look into it in the future but we're currently in a rush with the 5.2 Beta of Bitwig Studio.

**Pull request closed without merging**
