### PR TITLE
[libarchive] Update to 3.7.2

### LINKED ISSUE #32965: [libarchive] update to 3.7.1
### Library name

libarchive

### New version number

3.7.1

### Other information that may be useful (release notes, etc...)

[3.7.1 release notes](https://github.com/libarchive/libarchive/releases/tag/v3.7.1)
[3.7.0 release notes](https://github.com/libarchive/libarchive/releases/tag/v3.7.0)

### PR DESCRIPTION
**Pull request by LilyWangLL**
Fixes #32965, update `libarchive` to 3.7.2

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

All features passed with following triplets:
```
x86-windows
x64-windows
x64-windows-static
```
Usage test passed on `x64-windows`.

### CODE REVIEW

**Comment by SHIINASAMA** [comment]
Is it possible that these updates will be resolved in the future?

**Comment by dg0yt** [comment]
The downstream osx errors are due to mbedtls:
~~~
Undefined symbols for architecture x86_64:
  "_mbedtls_ripemd160_finish_ret", referenced from:
      ___archive_ripemd160final in libarchive.a(archive_digest.c.o)
  "_mbedtls_ripemd160_free", referenced from:
      ___archive_ripemd160final in libarchive.a(archive_digest.c.o)
  "_mbedtls_ripemd160_init", referenced from:
      ___archive_ripemd160init in libarchive.a(archive_digest.c.o)
  "_mbedtls_ripemd160_starts_ret", referenced from:
      ___archive_ripemd160init in libarchive.a(archive_digest.c.o)
  "_mbedtls_ripemd160_update_ret", referenced from:
      ___archive_ripemd160update in libarchive.a(archive_digest.c.o)
~~~
The port uses mbedtls for crypto only on osx. I don't see that this would be covered by the find module wrapper at the moment. However I wonder why it didn't fail to build in the past...

**Comment by dg0yt** [comment]
The problem (now) is not the build of libarchive. 
The problem is making downstream consumers aware of the need to link mbedtls, on osx.

**Comment by data-queue** [comment]
Closing this PR, see #36677

**Pull request closed without merging**
