### PR TITLE
Update portfiles to use VCPKG_BUILD_TYPE

### PR DESCRIPTION
**Pull request by SeekingMeaning**
**Describe the pull request**

- What does your PR fix?

Related to PR #9592; some portfiles incorrectly use `CMAKE_BUILD_TYPE` instead of `VCPKG_BUILD_TYPE`

- Which triplets are supported/not supported? Have you updated the CI baseline?

Same triplets as before; no update required

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

Yes

---

Question: is this a good alternative for `vcpkg_fail_port_install` for a port that only supports UWP?

```cmake
if (NOT VCPKG_TARGET_IS_UWP)
    message(FATAL_ERROR "${PORT} only supports UWP")
endif()
```

`vcpkg_fail_port_install(ON_TARGET "Windows" "Linux" "OSX")` would fail on UWP since, well, it's also Windows.

### CODE REVIEW

**Comment by cbezault** [comment]
This is ready to merge. The only failure is a file conflict between libpcap and pfring.

**Review by cbezault — APPROVED** [review]

**Comment by SeekingMeaning** [comment]
Okay, hmm... At first glance, it seems libpcap is building its own version of pfring. I'll look into this.

**Comment by PhoebeHui** [comment]
@SeekingMeaning, thanks for the PR!

Could you also update CONTROL file for related ports? see [Update the Version: field in the CONTROL file of any modified ports](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports)

**Comment by SeekingMeaning** [comment]
I'm not really sure how to go about fixing the pfring issue. I can't build it, even on virtual machine. Hmm...

**Comment by SeekingMeaning** [comment]
Yay

**Review by PhoebeHui — APPROVED** [review]
LGTM, thanks for the PR!

**Pull request merged**
