### PR TITLE
[libiconv] Before creating targets, check they do not exist already

### PR DESCRIPTION
**Pull request by seanwarren**
This PR ensures that libiconv only creates targets when they do not exist. 
This fixes an error which occurs when a target depending on libiconv is included before libiconv itself in a third package.

Required for #5454

### CODE REVIEW

**Comment by Rastaban** [comment]
I am seeing a new build failure in dependent ports collada-dom:x64-linux and vtk:x64-osx.  Attached is the collada-dom failure log.

[install-x64-linux-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2911881/install-x64-linux-dbg-out.log)

**Comment by seanwarren** [comment]
@Rastaban, thanks for the feedback. I believe this error is due to libxml2 only linking to iconv on windows. I've updated the cmake wrapper for libxml2 which should resolve this error. I can now install vtk and collada successfully on mac (I don't have easy access to a linux system at the moment)

**Comment by Rastaban** [comment]
In the CI tests I am seeing a build failure on qt5-declarative, which has no dependencys related to the ports being changed in this PR.  I don't know why this PR is triggering it but it is probably an issue in the CI system, I will be looking into it today.

**Comment by ras0219-msft** [comment]
Note: this change appears to remove ws2_32 from the `LIBXML2_LIBRARIES` list on windows.

**Comment by seanwarren** [comment]
Apologies, I missed the `ws2_32` library first time. I've re-added this. 

If I remove `${LIBLZMA_LIBRARIES}` from `LIBXML2_LIBRARIES` consuming packages (e.g. `collada-dom:x64-osx` don't link to LZMA and so fail to build. FindLIBXML2.cmake does not include the link to LZMA so I think this is required - let me know if I'm missing something!

**Comment by seanwarren** [comment]
Hello, please could you let me know what ports are still failing here

**Comment by grdowns** [comment]
Sure! Here's a snippet from the results:

Processing x64-osx                        583 vs 584
     collada-dom                                                 Pass vs Fail
     vtk                           **regression**                Fail vs Pass
     vtk-dicom                                                   Skip vs Pass

Processing x64-windows                    836 vs 846
     qt5-3d                                                      Skip vs Pass
     qt5-declarative               **regression**                Fail vs Pass
     qt5-graphicaleffects                                        Skip vs Pass
     qt5-location                                                Skip vs Pass
     qt5-multimedia                                              Skip vs Pass
     qt5-quickcontrols                                           Skip vs Pass
     qt5-quickcontrols2                                          Skip vs Pass
     qt5-scxml                                                   Skip vs Pass
     qt5-tools                                                   Skip vs Pass
     qt5-webview                                                 Skip vs Pass

 Processing x64-windows-static             762 vs 765
     pcl                                                         Skip vs Pass
     vtk                           **regression**                Fail vs Pass
     vtk-dicom                                                   Skip vs Pass

 Processing x86-windows                    815 vs 826
     qt5-3d                                                      Skip vs Pass
     qt5-declarative               **regression**                Fail vs Pass
     qt5-graphicaleffects                                        Skip vs Pass
     qt5-location                                                Skip vs Pass
     qt5-multimedia                                              Skip vs Pass
     qt5-quickcontrols                                           Skip vs Pass
     qt5-quickcontrols2                                          Skip vs Pass
     qt5-scxml                                                   Skip vs Pass
     qt5-tools                                                   Skip vs Pass
     qt5-webview                                                 Skip vs Pass
     qt5-winextras                 **regression**                Fail vs Pass

**Comment by grdowns** [comment]
To be more concise, the ports that are still failing are:

- `vtk`: `x64-osx` and `x64-windows-static`
- `qt5-declarative`: `x64-windows` and `x86-windows`
- `qt5-winextras`: `x86-windows`

Hope that helps Sean

**Comment by seanwarren** [comment]
#5558 should fix the regressions in `qt5-declarative` and `qt5-winextras` (which, as far as I can tell, aren't actually related to this PR).

**Comment by Rastaban** [comment]
Our CI system will cache the installed results of a port so it can avoid building things that have not changed.  Unfortunatly the qt5-base port is doing something that causes it to not cache correctly and as a result ports that have a dependency on it can incorrectly fail.  I am working on addressing that issue so for now you should be able to ignore the qt5 failures if they are not reproducible on your local machine.  One workaround is to make a whitespace change to qt5-base\portfile.cmake which will force the CI system to rebuild it and not use the cache.

**Comment by seanwarren** [comment]
OK I'll try that when I've figured out the vtk issue!

**Comment by seanwarren** [comment]
Hello, could you let me know what is still failing here please

**Comment by grdowns** [comment]
The build fails for:
 `x64-linux`: `collada-dom`
`x64-osx`: `vtk`
`x64-windows-static`: `vtk`

**Comment by grdowns** [comment]
`vtk` is failing for `x64-windows-static` with the error message:

```
CMake Error at C:/vsts/_work/2/s/scripts/buildsystems/vcpkg.cmake:165 (_add_library):
  Target "vtkIOInfovis" links to target "unofficial::iconv::libiconv" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMake/vtkModuleMacros.cmake:607 (add_library)
  CMake/vtkModuleMacros.cmake:712 (vtk_add_library)
  IO/Infovis/CMakeLists.txt:20 (vtk_module_library)
```

**Comment by seanwarren** [comment]
I am able to build all of these with a clean checkout of this branch, could you let let me know the errors you're getting on the CI please?

> The build fails for:
> `x64-linux`: `collada-dom`
> `x64-osx`: `vtk`
> `x64-windows-static`: `vtk`

**Comment by Rastaban** [comment]
Here are the logs for collada-dom:x64-linux and vtk:x64-windows-static
[failureLogs_2486860.zip](https://github.com/Microsoft/vcpkg/files/2964031/failureLogs_2486860.zip)

**Comment by seanwarren** [comment]
Hi, I think I have resolved the `vtk` issue, please can you confirm this?
I can't reproduce the `collada-dom` issue on linux (ubuntu 18.10), do you have any suggestions?

**Comment by Rastaban** [comment]
I have noticed collada-dom failures showing up in other PRs recently so it may just be a flakey port.  I may have time tomorrow to look into that a little more.  It looks like some of the jobs in the last test got canceled so I have requeued the tests I will check on the vtk results when it completes (note to self: check build #2499578 and post the results)

**Comment by Rastaban** [comment]
This is what I am seeing now:

```
 Processing x64-linux                      609 vs 638
     exiv2                         **regression**                Fail vs Pass
     fontconfig                    **regression**                Fail vs Pass
     glib                          **regression**                Fail vs Pass
     libxml2                       **regression**                Fail vs Pass
 Processing x64-osx                        623 vs 633
     exiv2                         **regression**                Fail vs Pass
     fontconfig                    **regression**                Fail vs Pass
     gettext                       **regression**                Fail vs Pass
     libxml2                       **regression**                Fail vs Pass

```

**Comment by seanwarren** [comment]
I think I've fixed everything but `glib:x64-linux`. Here it get a bit hairy - as far as I can tell `glib` was previously compiling an internal `libiconv` but now that we are linking to the built libiconv it's throwing an error. I'm afraid it's not obvious to me how to fix this.

**Comment by Rastaban** [comment]
I see build failures in` boost-locale:x64-linux` and `vtk:x64-osx`.

**Comment by seanwarren** [comment]
OK thanks @Rastaban. This PR has become a bit of a mess - I'm going to close and start a new clean request if thats ok?

**Pull request closed without merging**
