### PR TITLE
add shogun 6.1.3

### PR DESCRIPTION
**Pull request by vigsterkr**

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for the PR!

**Comment by vigsterkr** [comment]
@ras0219-msft thnx heaps for merging and for the addition fixes! 💃

**Comment by vigsterkr** [comment]
@ras0219-msft btw is there a way to actually have different variants of the same package? since i've realised that vcpkg contains intel's mkl, and with that some of the shogun models are way much faster :) so i'm wondering if that's somehow possible to have a shogun with openblas and a shogun with mkl variant?

**Comment by ras0219-msft** [comment]
Unfortunately, we don't currently have a good way to express packages with _conflicting_ options (A XOR B) that change the set of dependencies.

The approaches we can take right now are:

- Have shogun depend on _both_ openblas and mkl, and you can use a setting in your triplet file (`triplets\x64-windows.cmake`) to select which one should be used.
- Have a completely separate package (`shogun-mkl`) which is a complete clone except the different BLAS provider. This somewhat works as long as shogun is a "leaf" package and nobody else depends on it -- otherwise they have to choose one to depend on, which causes problems.
- Have shogun depend on the _triplet name itself_ using conditional dependencies. This is a capability we intend to change significantly in the near future, but it would technically work right now. This would mean if you created a new triplet file containing a magic substring (e.g. `triplets\x86-windows-mkl.cmake`) then shogun under that triplet would depend on MKL instead of openblas.

All three have additional shortcomings that I've omitted for brevity :)

(Also I don't 100% understand the exact relationship between shogun+openblas+mkl, so feel free to correct me if I got something wrong!)

**Comment by vigsterkr** [comment]
mmmm lemme check about this triplet... the idea is that shogun is invariant of having mkl or openblas as a BLAS/LAPACK backend, but MKL is way faster than openblas. currently unfortunately shogun needs this dependency to be fixed using compile time - there's a plan to be able to switch runtime.
the only reason i haven't used MKL is because some users would have problems with MKL's licensing...

**Pull request merged**
