### PR TITLE
[selene] Update to v0.2.

### PR DESCRIPTION
**Pull request by kmhofmann**
I have updated the Selene image representation library port files to v0.2.
(Port maintained by library's project lead.)

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks a bunch for pushing this PR and making a great library!

I made two tweaks while reviewing:
1. `SOURCE_PATH` is actually an _out_ parameter of `vcpkg_from_github()`, so I removed the unneeded `set()` above
2. `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` only has an effect in shared library builds, so we can always turn it "on"

Additionally, we have generally found that `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` is actually a poor experience for users (it tends to export a lot of things it shouldn't, like STL symbols). If you'd prefer users to just always consume the library as static, we can add
```
vcpkg_check_linkage(ONLY_STATIC_LIBRARY)
```
to the top of the file (right below including the common functions).

**Comment by kmhofmann** [comment]
Thanks for the thorough review and simplifications to the portfile!

I agree that `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` may result in a poor user experience. I have for now made the changes you suggested, and added the `vcpkg_check_linkage` line.

In the longer run I might choose to explicitly export the relevant symbols, but I'm still not that hot on adding a macro everywhere. :)

**Comment by kmhofmann** [comment]
It seems the CI failed, but I don't have access to what might have gone wrong. Is there anything I can change, or help with?

**Comment by ras0219-msft** [comment]
Sorry, there was a temporary regression on master which resulted in failed builds. I've kicked off a fresh CI :)

**Comment by ras0219-msft** [comment]
Ok, in the fresh CI I'm seeing a regression only on OSX:
```
/Users/ras0219/vcpkg/buildtrees/selene/src/v0.2-46c013a9a9/selene/base/_impl/ExplicitType.hpp:68:22: error: no template named 'is_arithmetic_v' in namespace 'std'; did you mean 'is_arithmetic'?
  static_assert(std::is_arithmetic_v<value_type>);
                ~~~~~^~~~~~~~~~~~~~~
                     is_arithmetic
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:522:51: note: 'is_arithmetic' declared here
template <class _Tp> struct _LIBCPP_TYPE_VIS_ONLY is_arithmetic
                                                  ^
/Users/ras0219/vcpkg/buildtrees/selene/src/v0.2-46c013a9a9/selene/img/dynamic/DynImageView.hpp:549:6: error: expected '(' after 'if'
  if constexpr (is_modifiable)
     ^
```

Our version of XCode may be slightly outdated -- is upstream selene working fine on OSX?

**Comment by kmhofmann** [comment]
That looks like the AppleClang/lib++ installation is not supporting C++17.

No build problems on my laptop using AppleClang 10.0.0.10001145/macOS 10.13.6.
All OK on Azure Pipelines using AppleClang 9.1.0.9020039, too (see e.g. https://dev.azure.com/kmhofmann/selene/_build/results?buildId=107)

**Comment by ras0219-msft** [comment]
LGTM then, thanks again!

**Pull request merged**
