### PR TITLE
Add the flint2 library

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by xoviat** [comment]
@ras0219-msft When running the build, I got the following error:

> fatal error C1083: Cannot open include file: 'gmp.h': No such file or directory

The file is in the vcpkg include directory:

```


    Directory: C:\Tools\vcpkg\installed\x86-windows\include


Mode                LastWriteTime         Length Name                                                                                                                                                                                
----                -------------         ------ ----                                                                                                                                                                                
-a----       10/16/2017   7:37 PM          97422 gmp.h                                                                                                                                                                               
-a----        2/22/2017   4:18 PM         123668 gmpxx.h                                                                                                                                                                             
-a----         9/7/2017  11:36 AM          51307 mpfr.h                                                                                                                                                                              
-a----       10/16/2017   7:37 PM          97422 mpir.h                                                                                                                                                                              
-a----        2/22/2017   4:18 PM         123668 mpirxx.h                                                                                                                                                                            
-a----       10/16/2017   7:41 PM          43822 pthread.h                                                                                                                                                                           
-a----       10/16/2017   7:41 PM           5178 sched.h                                                                                                                                                                             
-a----       10/16/2017   7:41 PM           4732 semaphore.h                                                                                                                                                                         
```

Why is this happening?

**Comment by xoviat** [comment]
Great, so the vcpkg include and library directories are not added to the msbuild command by default. 

@ras0219-msft is there a way to add them?

**Comment by ras0219-msft** [comment]
Thanks for the PR!

We don't currently have a way to pull in the Vcpkg integration for MSBuild projects reliably (for example, when the user doesn't have user-wide integration installed), so they don't automatically get the includes/libraries.

Unfortunately, the MSBuild files will need to be patched to make that work -- though to handle VS2017 it will also may require patches anyway. `openni2`[1] is an example of where this is done. The approach is to patch in a `;@NATIVE_INSTALLED_DIR@` entry into the `AdditionalIncludeDirectories` list, then run cmake's `configure_file()` in place to replace those variables with the exact current location. It's important when doing this to use fresh sources each time, so you'll notice a section like:
```cmake
file(REMOVE_RECURSE ${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET})
file(MAKE_DIRECTORY ${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET})
file(COPY ${SOURCE_PATH} DESTINATION ${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET})
```
which copies the "fresh" source files into a build-specific directory for the actual build.

[1] https://github.com/Microsoft/vcpkg/blob/01f47f5823b0c0db4a7e3e5b690dbc809429da56/ports/openni2/portfile.cmake

**Comment by xoviat** [comment]
Thanks. I'll look at doing that.

**Comment by xoviat** [comment]
Okay, this should be ready to go (testing for x86 on Appveyor). Unfortunately, I couldn't get it to work with x64, which had the following failure:

```         get_mpfr.obj : error LNK2019: unresolved external symbol __gmpfr_set_sj referenced in function fmpz_get_mpfr```

This should be in `mpfr.lib`, but isn't. I may come back to this later once I have `arb` finished.

**Comment by xoviat** [comment]
@ras0219-msft After pulling the latest changes, I can no longer build the library; it fails with:

```
Expected Debug,Dynamic crt linkage, but the following libs had invalid crt linkage:
    C:/Tools/vcpkg/packages/flint_x86-windows/debug/lib/flint.lib: Debug,Static
To inspect the lib files, use:
    dumpbin.exe /directives mylibfile.lib
Expected Release,Dynamic crt linkage, but the following libs had invalid crt linkage:
    C:/Tools/vcpkg/packages/flint_x86-windows/lib/flint.lib: Release,Static
```

The suggestion of running dumpbin produced no helpful output, but the results are here: 

https://ci.appveyor.com/project/xoviat/test-vcpkg-mue34/build/1.0.10

**Comment by xoviat** [comment]
Seems I can no longer override the default linkage. I'm not the only one who did this though.

**Comment by xoviat** [comment]
Still happening.

**Comment by xoviat** [comment]
Looks like the build type is checked here: https://github.com/Microsoft/vcpkg/blob/0d7381ba408e4d5bcde06ab7a6353ff14e7afc0b/toolsrc/src/vcpkg/postbuildlint.buildtype.cpp#L54

Reasons why this might not have happened before.
1. Something changed with CMake
2. Appveyor update their images

**Comment by xoviat** [comment]
Problem resolved;.

**Comment by xoviat** [comment]
@ras0219-msft Ping.

**Comment by alexkaratarakis** [comment]
Thanks for the PR!

**Pull request merged**
