### PR TITLE
[behaviortree-cpp] update port

### PR DESCRIPTION
**Pull request by mathisloge**
# DO NOT REVIEW YET
I'm waiting for the next release, since v3.6.0 hasn't got the necessary feature flags to support the added features. 
Might take a while. 

## todo

- [ ] Add patch for zmq -> cppzmq

- #### What does your PR fix?  
Updates behaviortree-cpp to the latest version

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
yes

### CODE REVIEW

**Comment by JonLiu1993** [comment]
@mathisloge , behaviortree-cpp 3.7.0 Release has been published
 https://github.com/BehaviorTree/BehaviorTree.CPP/commit/a5411c978ec976f66d83b1df5aa4dd7c632a142c
Could we update this pr?

**Comment by mathisloge** [comment]
@JonLiu1993 thanks for the reminder :)

I'll update the port in the next few days.

**Comment by JonLiu1993** [comment]
@mathisloge , Ping for response.

**Comment by JonLiu1993** [comment]
Closing this PR since it seems that no progress is being made. Please ping us to reopen if work is still being done.

**Pull request closed without merging**
