### PR TITLE
[lapack] Skip build on osx

### PR DESCRIPTION
**Pull request by sarlinpe**
Building the `lapack-reference` port on `osx-arm64` fails (see https://github.com/microsoft/vcpkg/issues/34857) unless tests are disabled (https://github.com/microsoft/vcpkg/pull/35920). macOS ships its own version of LAPACK in [vecLib](https://developer.apple.com/documentation/accelerate/veclib). I think that we should thus skip building LAPACK altogether on osx.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [ ] ~~SHA512s are updated for each updated download~~
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by Neumann-A** [comment]
This requires forcing the lapack vendor. More strictly speaking this is a subset of #24327

**Comment by jimwang118** [comment]
This requires you to confirm with the upstream that arm64-osx is not supported.

**Comment by jimwang118** [comment]
Note: I will be converting your PR to draft status. The above suggested changes are only recommendations. If you are willing to adopt them, please click "ready for review" after making the modifications. If you do not wish to make any changes, please click "ready for review" directly. That way, I can be aware that you've responded since you can't modify the tags.

**Comment by jimwang118** [comment]
@sarlinpe Thanks for your PR, Is work still being done for this PR?

**Comment by jimwang118** [comment]
Closing this PR since it seems that no progress is being made. Please ping us to reopen if work is still being done.

**Pull request closed without merging**
