### PR TITLE
[jsonnet]Upgrade version to 0.13.0

### PR DESCRIPTION
**Pull request by JackBoosY**
1. Upgrade to v0.13.0.
2. Since powershell version 5.1 was upgraded to version 6.0, the `Get-Content` command removed the parameter `-Encoding Byte` and changed it to `-AsByteStream`. See documentation([5.1](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-content?view=powershell-5.1)/[6.0](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-content?view=powershell-6)).
Related: #7217.

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Related: #7382

**Comment by Rastaban** [comment]
The powershell version checking logic may be unneeded with @ras0219-msft PR, as everything will use the version of powershell that vcpkg downloads.

**Comment by JackBoosY** [comment]
@Rastaban I will revert the second commit if Robert's PR merge.

**Comment by JackBoosY** [comment]
@Rastaban The powershell issue has been fixed now.

**Pull request merged**
