### PR TITLE
[sdl2] update to 2.0.8

### PR DESCRIPTION
**Pull request by jasjuang**
tested and everything compiles as usual

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Awesome, thanks for the update!

**Comment by janisozaur** [comment]
@jasjuang any chance you could take a look at #2970 ?

**Comment by jasjuang** [comment]
@janisozaur Sorry I didn't test it on arm-uwp. I only tested on x64 and x86. I am not sure how to do a arm-uwp build. If you build from source, do you see the same error? It might be a problem from the upstream instead of vcpkg.

@ras0219-msft Please revert this PR for now.

**Comment by janisozaur** [comment]
Looking at it, it certainly seems like the regression is upstream, but then again there is a non-trivial patch for getting UWP builds working in vcpkg.

I've already submitted https://bugzilla.libsdl.org/show_bug.cgi?id=4104 to fix one of the issues with native windows on ARM.

> If you build from source, do you see the same error?

Weird as it may sound, I'm not a Windows user and don't generally observe these issues, only through services like AppVeyor.

**Pull request merged**
