### PR TITLE
[sqlcipher] Update to version 4.6.0

### PR DESCRIPTION
**Pull request by kadirlua**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [x] The "supports" clause reflects platforms that may be fixed by this new version.
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

This PR updates sqlcipher to version 4.6.0.

### CODE REVIEW

**Comment by nlogozzo** [comment]
Hi, could you look into adding Linux support for this package?

**Review by musaBoya — APPROVED** [review]

**Comment by kadirlua** [comment]
> Hi, could you look into adding Linux support for this package?

This package already has Linux support as I know.

**Comment by dg0yt** [comment]
> > Hi, could you look into adding Linux support for this package?
> 
> This package already has Linux support as I know.

The port does not.

https://github.com/microsoft/vcpkg/blob/68f016e70164b093fd9777c2840447ee0b528d90/ports/sqlcipher/vcpkg.json#L7

**Comment by kadirlua** [comment]
> > > Hi, could you look into adding Linux support for this package?
> 
> > 
> 
> > This package already has Linux support as I know.
> 
> 
> 
> The port does not.
> 
> 
> 
> https://github.com/microsoft/vcpkg/blob/68f016e70164b093fd9777c2840447ee0b528d90/ports/sqlcipher/vcpkg.json#L7

Hmm. Ok, I got it but after this PR, I can look into it.

**Comment by nlogozzo** [comment]
> > > > Hi, could you look into adding Linux support for this package?
> > 
> > > 
> > 
> > > This package already has Linux support as I know.
> > 
> > 
> > 
> > The port does not.
> > 
> > 
> > 
> > https://github.com/microsoft/vcpkg/blob/68f016e70164b093fd9777c2840447ee0b528d90/ports/sqlcipher/vcpkg.json#L7
> 
> Hmm. Ok, I got it but after this PR, I can look into it.

Really appreciate it, thanks!

**Comment by kadirlua** [comment]
By the way, the PR is ready for merging @MonicaLiu0311

**Comment by BillyONeal** [comment]
Thanks for the update!

**Comment by MonicaLiu0311** [comment]
All features are tested successfully in the following triplet:
```
x86-windows
x64-windows
```

**Pull request merged**
