### PR TITLE
[akali] Update to v1.43

### PR DESCRIPTION
**Pull request by winsoft666**
**Describe the pull request**

- #### What does your PR fix?
  Update to v1.43

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  <linux, windows, macOS / arm, uwp>, <No>

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  <Yes>

### CODE REVIEW

**Comment by FrankXie05** [comment]
@winsoft666 Thanks for your PR! Can you please correct the `git-tree` field in the `akali.json` file? 
Please run the command `./vpckg x-add-version akali --overwrite-version` after each change, and you can get more information from [maintainer-guide.md](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md).

**Comment by winsoft666** [comment]
> @winsoft666 Thanks for your PR! Can you please correct the `git-tree` field in the `akali.json` file? Please run the command `./vpckg x-add-version akali --overwrite-version` after each change, and you can get more information from [maintainer-guide.md](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md).

Sorry, I don't know how to correct the `git-tree` field, I have never manually modified this file

**Comment by FrankXie05** [comment]
@winsoft666  Do you mind if I make changes on your PR?

**Comment by winsoft666** [comment]
> @winsoft666 Do you mind if I make changes on your PR?

Please do it

**Review by FrankXie05 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the update and modernization!

**Pull request merged**
