### PR TITLE
[Qt] Update to 5.12.4

### LINKED ISSUE #2050: Qt5 fails with custom triplet
I use a a custom triplet to build static libraries with dynamic crt linkage. I had to add a couple of exceptions - libraries which can only be built dynamically. My triplet file looks like this:

```cmake
set(VCPKG_TARGET_ARCHITECTURE x64)

# Always use thy dynamic CRT.
set(VCPKG_CRT_LINKAGE dynamic)

# Prefer to link statically.
set(VCPKG_LIBRARY_LINKAGE static)

# Except for the following exceptions:
if(PORT STREQUAL "openssl")
    set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()

if(PORT STREQUAL "qt5")
    set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()

...
```
Building qt5 fails, because it cannot find libpng and psql.

## config-rmak-rel-err.log:
```
ERROR: Feature 'sql-psql' was enabled, but the pre-condition 'libs.psql' failed.

ERROR: Feature 'system-png' was enabled, but the pre-condition 'features.png && libs.libpng' failed.

Check config.log for details.
```

## config.log:
```
looking for library libpng
Trying source 0 (type pkgConfig) of library libpng ...
  => source produced no result.
Trying source 1 (type inline) of library libpng ...
+ cd /d C:\vcpkg\buildtrees\qt5\rmak-rel\qtbase\config.tests\unix\libpng && C:\vcpkg\buildtrees\qt5\rmak-rel\qtbase\bin\qmake.exe "CONFIG -= qt debug_and_release app_bundle lib_bundle" "CONFIG += shared console" "QMAKE_LIBDIR += C:/vcpkg/installed/rmak/lib" "INCLUDEPATH += C:/vcpkg/installed/rmak/include" "LIBS += \"-llibpng16\"" C:/vcpkg/buildtrees/qt5/src/qt-5.8.0/qtbase/config.tests/unix/libpng
+ cd /d C:\vcpkg\buildtrees\qt5\rmak-rel\qtbase\config.tests\unix\libpng && set MAKEFLAGS=& nmake
> Microsoft (R) Program Maintenance Utility Version 14.11.25547.0
> Copyright (C) Microsoft Corporation.  All rights reserved.
> 	cl -c -nologo -Zc:wchar_t -FS -Zc:strictStrings -Zc:throwingNew -O2 -MD -GR -W3 -w34100 -w34189 -w44996 -w44456 -w44457 -w44458 -wd4577 -wd4467 -EHsc -DUNICODE -DWIN32 -DWIN64 -DNDEBUG -IC:\vcpkg\buildtrees\qt5\src\qt-5.8.0\qtbase\config.tests\unix\libpng -I. -IC:\vcpkg\installed\rmak\include -IC:\vcpkg\buildtrees\qt5\src\qt-5.8.0\qtbase\mkspecs\win32-msvc2017 -Fo @C:\Users\BJORNP~1\AppData\Local\Temp\nmF995.tmp
> libpng.cpp
> 	link /NOLOGO /DYNAMICBASE /NXCOMPAT /INCREMENTAL:NO /SUBSYSTEM:CONSOLE "/MANIFESTDEPENDENCY:type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' publicKeyToken='6595b64144ccf1df' language='*' processorArchitecture='*'" /MANIFEST:embed /OUT:libpng.exe @C:\Users\BJORNP~1\AppData\Local\Temp\nmFA23.tmp
> libpng16.lib(pngread.c.obj) : error LNK2019: unresolved external symbol inflateEnd referenced in function png_destroy_read_struct
> libpng16.lib(png.c.obj) : error LNK2019: unresolved external symbol inflateReset referenced in function png_reset_zstream
> libpng16.lib(pngrutil.c.obj) : error LNK2001: unresolved external symbol inflateReset
> libpng16.lib(png.c.obj) : error LNK2019: unresolved external symbol adler32 referenced in function png_compare_ICC_profile_with_sRGB
> libpng16.lib(png.c.obj) : error LNK2019: unresolved external symbol crc32 referenced in function png_calculate_crc
> libpng16.lib(pngrutil.c.obj) : error LNK2019: unresolved external symbol inflate referenced in function png_inflate
> libpng16.lib(pngrutil.c.obj) : error LNK2019: unresolved external symbol inflateReset2 referenced in function png_inflate_claim
> libpng16.lib(pngrutil.c.obj) : error LNK2019: unresolved external symbol inflateInit2_ referenced in function png_inflate_claim
> libpng16.lib(pngrutil.c.obj) : error LNK2019: unresolved external symbol inflateValidate referenced in function png_inflate_claim
> libpng16.lib(pngwrite.c.obj) : error LNK2019: unresolved external symbol deflateEnd referenced in function png_destroy_write_struct
> libpng16.lib(pngwutil.c.obj) : error LNK2001: unresolved external symbol deflateEnd
> libpng16.lib(pngwutil.c.obj) : error LNK2019: unresolved external symbol deflate referenced in function png_compress_IDAT
> libpng16.lib(pngwutil.c.obj) : error LNK2019: unresolved external symbol deflateReset referenced in function png_deflate_claim
> libpng16.lib(pngwutil.c.obj) : error LNK2019: unresolved external symbol deflateInit2_ referenced in function png_deflate_claim
> libpng.exe : fatal error LNK1120: 12 unresolved externals
> NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\HostX64\x64\link.EXE"' : return code '0x460'
> Stop.
 => source failed verification.
Trying source 2 (type inline) of library libpng ...
  => source failed condition.
test config.gui.libraries.libpng FAILED
```

## config.log(cont'd):
```
looking for library psql
Trying source 0 (type pkgConfig) of library psql ...
  => source produced no result.
Trying source 1 (type psqlConfig) of library psql ...
  => source produced no result.
Trying source 2 (type inline) of library psql ...
+ cd /d C:\vcpkg\buildtrees\qt5\rmak-rel\qtbase\config.tests\unix\psql && C:\vcpkg\buildtrees\qt5\rmak-rel\qtbase\bin\qmake.exe "CONFIG -= qt debug_and_release app_bundle lib_bundle" "CONFIG += shared console" "QMAKE_LIBDIR += C:/vcpkg/installed/rmak/lib" "INCLUDEPATH += C:/vcpkg/installed/rmak/include" "LIBS += -llibpq -lws2_32 -ladvapi32" C:/vcpkg/buildtrees/qt5/src/qt-5.8.0/qtbase/config.tests/unix/psql
+ cd /d C:\vcpkg\buildtrees\qt5\rmak-rel\qtbase\config.tests\unix\psql && set MAKEFLAGS=& nmake
> Microsoft (R) Program Maintenance Utility Version 14.11.25547.0
> Copyright (C) Microsoft Corporation.  All rights reserved.
> 	cl -c -nologo -Zc:wchar_t -FS -Zc:strictStrings -Zc:throwingNew -O2 -MD -GR -W3 -w34100 -w34189 -w44996 -w44456 -w44457 -w44458 -wd4577 -wd4467 -EHsc -DUNICODE -DWIN32 -DWIN64 -DNDEBUG -IC:\vcpkg\buildtrees\qt5\src\qt-5.8.0\qtbase\config.tests\unix\psql -I. -IC:\vcpkg\installed\rmak\include -IC:\vcpkg\buildtrees\qt5\src\qt-5.8.0\qtbase\mkspecs\win32-msvc2017 -Fo @C:\Users\BJORNP~1\AppData\Local\Temp\nmE041.tmp
> psql.cpp
> 	link /NOLOGO /DYNAMICBASE /NXCOMPAT /INCREMENTAL:NO /SUBSYSTEM:CONSOLE "/MANIFESTDEPENDENCY:type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' publicKeyToken='6595b64144ccf1df' language='*' processorArchitecture='*'" /MANIFEST:embed /OUT:psql.exe @C:\Users\BJORNP~1\AppData\Local\Temp\nmE0CE.tmp
> libpq.lib(fe-connect.obj) : error LNK2019: unresolved external symbol __imp_FreeCredentialsHandle referenced in function closePGconn
> libpq.lib(fe-connect.obj) : error LNK2019: unresolved external symbol __imp_DeleteSecurityContext referenced in function closePGconn
> libpq.lib(fe-connect.obj) : error LNK2019: unresolved external symbol __imp_SHGetFolderPathA referenced in function getPgPassFilename
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol sk_num referenced in function verify_peer_name_matches_certificate
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol sk_value referenced in function verify_peer_name_matches_certificate
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol sk_free referenced in function verify_peer_name_matches_certificate
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol BIO_set_flags referenced in function my_sock_read
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol BIO_clear_flags referenced in function my_sock_read
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol BIO_new referenced in function initialize_SSL
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol BIO_int_ctrl referenced in function initialize_SSL
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol BIO_s_socket referenced in function initialize_SSL
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol ASN1_STRING_length referenced in function verify_peer_name_matches_certificate_name
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol ASN1_STRING_data referenced in function verify_peer_name_matches_certificate_name
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol X509_STORE_set_flags referenced in function initialize_SSL
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol X509_STORE_load_locations referenced in function initialize_SSL
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol X509_free referenced in function pgtls_close
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol X509_get_subject_name referenced in function verify_peer_name_matches_certificate
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol X509_NAME_get_index_by_NID referenced in function verify_peer_name_matches_certificate
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol X509_NAME_get_entry referenced in function verify_peer_name_matches_certificate
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol X509_NAME_ENTRY_get_data referenced in function verify_peer_name_matches_certificate
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol X509_get_ext_d2i referenced in function verify_peer_name_matches_certificate
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol SSL_CTX_new referenced in function initialize_SSL
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol SSL_CTX_free referenced in function initialize_SSL
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol SSL_CTX_get_cert_store referenced in function initialize_SSL
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol SSL_get_current_cipher referenced in function PQsslAttribute
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol SSL_CIPHER_get_bits referenced in function PQsslAttribute
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol SSL_CIPHER_get_name referenced in function PQsslAttribute
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol SSL_pending referenced in function pgtls_read_pending
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol SSL_set_bio referenced in function initialize_SSL
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol SSL_set_verify referenced in function initialize_SSL
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol SSL_use_PrivateKey referenced in function initialize_SSL
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol SSL_use_PrivateKey_file referenced in function initialize_SSL
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol SSL_CTX_use_certificate_chain_file referenced in function initialize_SSL
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol SSL_load_error_strings referenced in function pgtls_init
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol SSL_get_peer_certificate referenced in function pgtls_open_client
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol SSL_check_private_key referenced in function initialize_SSL
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol SSL_new referenced in function initialize_SSL
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol SSL_free referenced in function pgtls_close
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol SSL_connect referenced in function pgtls_open_client
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol SSL_read referenced in function pgtls_read
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol SSL_write referenced in function pgtls_write
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol SSL_ctrl referenced in function initialize_SSL
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol SSL_CTX_ctrl referenced in function initialize_SSL
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol SSL_get_error referenced in function pgtls_open_client
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol SSL_get_version referenced in function PQsslAttribute
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol SSLv23_method referenced in function initialize_SSL
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol SSL_shutdown referenced in function pgtls_close
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol SSL_library_init referenced in function pgtls_init
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol SSL_CTX_load_verify_locations referenced in function initialize_SSL
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol SSL_set_ex_data referenced in function initialize_SSL
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol SSL_get_current_compression referenced in function PQsslAttribute
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol ERR_put_error referenced in function initialize_SSL
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol ERR_get_error referenced in function initialize_SSL
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol ERR_clear_error referenced in function initialize_SSL
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol ERR_reason_error_string referenced in function SSLerrmessage
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol OPENSSL_config referenced in function pgtls_init
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol ENGINE_by_id referenced in function initialize_SSL
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol ENGINE_free referenced in function initialize_SSL
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol ENGINE_init referenced in function initialize_SSL
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol ENGINE_finish referenced in function initialize_SSL
> libpq.lib(fe-secure-openssl.obj) : error LNK2019: unresolved external symbol ENGINE_load_private_key referenced in function initialize_SSL
> libpq.lib(fe-auth.obj) : error LNK2019: unresolved external symbol AcquireCredentialsHandleA referenced in function pg_SSPI_startup
> libpq.lib(fe-auth.obj) : error LNK2019: unresolved external symbol InitializeSecurityContextA referenced in function pg_SSPI_continue
> libpq.lib(fe-auth.obj) : error LNK2019: unresolved external symbol FreeContextBuffer referenced in function pg_SSPI_continue
> psql.exe : fatal error LNK1120: 64 unresolved externals
> NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\HostX64\x64\link.EXE"' : return code '0x460'
> Stop.
 => source failed verification.
```

## Summary
So, it seems like 
1. Qt finds the static libpng, but not the transitive dependency zlib. 
2. Qt finds the static libpq, but not the transitive dependency openssl.

### PR DESCRIPTION
**Pull request by Neumann-A**
(still have to figure out where to put host tools!)

Related: #4560 #6240 #5881 #731 #513.
closes: #2050

### CODE REVIEW

**Comment by Neumann-A** [comment]
@Rastaban Is there a reason why CI is not testing qt5 on osx and arm?

**Comment by Neumann-A** [comment]
Note to myself: triplet x86-windows built locally succesful with https://github.com/microsoft/vcpkg/pull/7667/commits/9416a64120b2196233f21caa970ac06ea17e603c (might break again since i am refactoring qt_modularscripts)

**Comment by Neumann-A** [comment]
TODO: Test if #2643 is closed by this (probably only works correct for one configuration and there must be a trick to make it work with two different qt.conf e.g. debug/release)

**Comment by Neumann-A** [comment]
#2643 seems to work if i copy all additional libraries into the host folder. Funny though that qt decides to install the libs into the bin folder and not the host/bin folder like the executables. Seems like there is a host_build still setting the wrong target.path for libraries.

**Comment by Neumann-A** [comment]
Also note qt5-tools should be built for _the host_ **not the target** system

**Comment by Neumann-A** [comment]
TODO: 
- [ ] deactivate dependencies of qtdeclarative and qt-tools on non host builds somehow?

**Comment by Neumann-A** [comment]
Linux at Starting package 32/53: qt5-svg:x64-linux and was succesfull i'll assume that it works on linux and will push new commits after a quick local check. 
The windows failures are just ci cache failures. CI did not recognize that it had to rebuild those packages and thus just returned the old failure.

**Comment by Neumann-A** [comment]
x86-windows CI is testing QT 5.13
x64-windows should work (local build is still running)

furthermore crosscompilation targets should work now meaning:
arm64-windows should be working -> will test if x64-windows finishes locally (required due to host tools being required)

**Comment by Neumann-A** [comment]
hmpf suddenly:
CMake Error at ports/qt5-base/portfile.cmake:190 (file):
```
  file RENAME failed to rename

    E:/qt_5.12.4/packages/qt5-base_x64-windows/lib/cmake

  to

    E:/qt_5.12.4/packages/qt5-base_x64-windows/share/cmake

  because: No such file or directory
```
also in CI. wondering what is going on here since `E:/qt_5.12.4/packages/qt5-base_x64-windows/lib/cmake` exists.

**Comment by Neumann-A** [comment]
hmm the libqglviewer:x64-windows-static regression is not a regression... it is just pointing out that something is horrible wrong with that port udner that triplet. The *.pro file states CONFIG+=shared and another variable QGLVIEW_STATIC or similar which is not set by the port. 

@JackBoosY can you comment on that? I cannot see how you fixed that in #7313.

**Comment by JackBoosY** [comment]
@Neumann-A This problem seems to be caused by some libraries/tools not found on the libqglviewer dependency path. I can't completely determine this.

**Comment by Neumann-A** [comment]
Ah Qt.... stupid static build! qt-declarative builds debug but fails release due to not linking bzip..  
So please tell me qt build system why does your `qt_lib_gui_private.pri` mksepc differ for release and debug that you always only want to link `QMAKE_LIBS_FREETYPE = -lfreetype` for release but `QMAKE_LIBS_FREETYPE = $$[QT_INSTALL_LIBS]/freetyped.lib $$[QT_INSTALL_LIBS]/bz2d.lib` for debug although I already told you while building that you need bzip..... `FREETYPE_LIBS=${CURRENT_INSTALLED_DIR}/lib/freetype.lib ${CURRENT_INSTALLED_DIR}/lib/bz2.lib`
And dont let me fool you by simply changing `qt_lib_gui_private.pri` you still give me linker errors. So lets try to go the linux way and define `QMAKE_LIBS_PRIVATE+=${CURRENT_INSTALLED_DIR}/lib/bz2.lib` and another hour to see the results........

and concerning the linux regressions. I have to setup a linux build env to see the directory layout. Maybe the mkspecs get installed into a different folder there. On windows they get always installed into -hostprefix indepent of what i told configure -archdatadir. Maybe the issue is that -datadir is pointing to a different folder.

**Comment by JackBoosY** [comment]
Yeah, qt5 spend me several weeks. I will help you to solve these problems.

**Comment by Neumann-A** [comment]
> Hmm could it be that your configure.json in the qt5-base source is overruling my external say?

hmm qt you little brick you were really messing with my flags..... so let me patch your mess away and watch the static build progress.

@JackBoosY qt5-declarative and activeqt are fixed for static windows builds. Would be good if you could solve the libqglviewer regression in the static build. Could be related to my change to switch opengl to es2 in the static build for qt (since dynamic will generate angle dll's and this port has been explicitly deactivated for static builds so I do the same in qt5-base). Maybe we have to explicitly disable libqglviewer in windows-static?
I will in the meantime try to solve the linux regression.

**Comment by JackBoosY** [comment]
@Neumann-A I will try to fix it next week.

**Comment by Neumann-A** [comment]
@JackBoosY Too late already fixed that regression now.... Qt5 buildsystem is seriously broken with all those little bugs...

hmm and linux should also build. In my VM it takes forever but qt5-declarative[core]:x64-linux is already way past the configuration step and building (CI told that it was failing in the config step). So there seems to be some error in the CI. Lets see what this CI run tells us.

**Comment by Neumann-A** [comment]
yeah 6 seconds for Linux CI. I'll doubt it re-run correctly. Can somebody please fix that?

**Comment by JackBoosY** [comment]
@Rastaban Can you rerun Linux PR-Eager? Thanks.

**Comment by Neumann-A** [comment]
clean CI running in #7730.

**Comment by cenit** [comment]
> Qt5 buildsystem is seriously broken with all those little bugs...

There is a reason if for QT6 they are moving to CMake...

**Comment by Neumann-A** [comment]
Really a bit too clever.... so in my local test x64-windows-static builds qt completly and x64-linux builds qt completly (fresh ubuntu 19.04). 
I smell something fishy with CI since the error logs for x64-linux indicate that all qt ports should fail.

**Comment by JackBoosY** [comment]
@cenit Setting the hash and ref of all ports in a configuration file is only suitable for large ports (such as qt5 and boost) because their components are bound to their cores.
For other small ports, updating their versions may cause build errors, we need to fix it in portfile.cmake, so I think it might be better to set their hash and ref in portfile.cmake.

**Comment by JackBoosY** [comment]
@Neumann-A You forgot these patches.

**Comment by Rastaban** [comment]
@Neumann-A the CI system tries to be clever and cache as much as it can.  The cleverness is mostly in the way it calculates a hash of each port and its dependencies and uses that hash as a key to cache the results.  If you want to force a full rebuild of Qt then you just need to make a change to any of the files in `qt5-base`.  This will cause a change in the hash of everything that depends on it.  Sometimes people keep ticking up the dash version but you could just make a unique white space change.  We are capable of deleting the cached results in the CI, but for libraries that are complex like Qt there is currently not an easy way to so that.  The other option is that CI runs can be started without sharing a cache, but it means all ports will be rebuilt.

**Comment by Rastaban** [comment]
Fixed this bug after looking into your build failures: #7754.  Restarted your tests after it was merged (Running CI tests automatically merge latest master for tests so it will pick up the change).

**Comment by JackBoosY** [comment]
I tested it in x86-windows and x64-linux, they were built successfully, but failed in x64-windows-static:
>qwindowsd.lib(qwindowseglcontext.obj) : error LNK2019: unresolved external symbol __imp_glActiveTexture referenced in function "public: virtual void (__cdecl*__cdecl QWindowsEGLContext::getProcAddress(char const *))(void)" (?getProcAddress@QWindowsEGLContext@@UEAAP6AXXZPEBD@Z)
qwindowsd.lib(qwindowseglcontext.obj) : error LNK2019: unresolved external symbol __imp_glAttachShader referenced in function "public: virtual void (__cdecl*__cdecl QWindowsEGLContext::getProcAddress(char const *))(void)" (?getProcAddress@QWindowsEGLContext@@UEAAP6AXXZPEBD@Z)
...
..\..\bin\qml.exe : fatal error LNK1120: 161 unresolved externals
..\..\bin\qmltestrunner.exe : fatal error LNK1120: 161 unresolved externals
..\..\bin\qmleasing.exe : fatal error LNK1120: 161 unresolved externals

**Comment by Neumann-A** [comment]
@JackBoosY Hmm after testing that error comes from the libqglviewer opengl fix. After investigating further it seems like the with Qt is setting some incompatible preprocessor defines with the windows gl header. If you remove the patch qt will build successfully again but libqglviewer will fail. 

Our Options for the static build are:
- define `_GDI32_` ( which removes declspec(dllimport) from the windows gl headers and statically links against angle). Has probably side effects on the windows headers/functions? (anybody?)
- build with -opengl desktop (uses graphics driver)
- build with -opengl dynamic and delete the angle dll's (same as above but with the possibility to manually supply angle dll's)
- build completly without opengl

**Comment by Neumann-A** [comment]
I could use some help with the osx regression because i have no clue how to solve:

```
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: /Users/vagrant/azure_agent/_work/2/s/packages/qt5-base_x64-osx/debug/lib/libQt5Core_debug.a(qversiontagging.o) has no symbols
....(ann a few more no symbols warnings)...
ld: file too small (length=5) file 'makefile.o' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by Neumann-A** [comment]
@Rastaban: Could you please tell me what is going on with the Linux CI. I could compile 15283b7 on Linux without a problem and JackBoosY was also able to build an early commit on Linux without a problem. From the error it looks like the folder `<vcpkginstalleddir>/tools/qt5(/debug)/mkspec` is somehow missing

**Comment by Neumann-A** [comment]
hmm osx again: this time debug build succeeded but release build failed with:
```
ld: file too small (length=5) file 'makefile.o' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [../qmake/qmake] Error 1
make[1]: *** [/Volumes/Data/buildtrees/qt5-base/x64-osx-rel/qmake/qmake] Error 2
make: *** [sub-qmake-qmake-aux-pro-install_subtargets] Error 2
```

**Comment by Neumann-A** [comment]
```
Building package qt5-base[core]:x64-osx... done
Installing package qt5-base[core]:x64-osx...
Installing package qt5-base[core]:x64-osx... done
Elapsed time for package qt5-base:x64-osx: 4.503 h
```
Finally with 8fa9dcf....lets make it faster

**Comment by Neumann-A** [comment]
only linux failures remaining. If anybody can reproduce those please tell me how so I can fix them ;)

**Comment by Rastaban** [comment]
I am going to add larger drives to the Linux CI machines so we can get rid of the links.

**Comment by Rastaban** [comment]
Finished updating the Linux CI machines and merge this PR to latest master (along with a bump to the qt5-base control version) to to a clean rebuild.

**Comment by cenit** [comment]
wow green mark!

**Comment by Neumann-A** [comment]
still the osx build needs roughly 3 h (3 cores)
`Elapsed time for package qt5-base:x64-osx: 2.901 h`
while the linux build only took 22min (8 cores)
`Elapsed time for package qt5-base:x64-linux: 22.21 min`
on windows a bit more than 30 min (8 cores)
`Elapsed time for package qt5-base:x64-windows-static: 32.21 min`

It would be good if somebody could figure out why the additional clean steps are necessary on osx

**Comment by cenit** [comment]
It’s roughly a factor of two of difference per core, without knowing real running core frequencies. Also, not sure what valgrind role is in all of that. Since build times here on vcpkg are generally slower on osx ‘s CI, I wouldn’t worry so much. If it fixes problems, for me it’s not a regression, at all. There is always room for refinements later, while real fixes are never soon enough. I am sure many can wait a little bit longer for a working library, but cannot use a broken lib build quickly

**Comment by Neumann-A** [comment]
>slower on osx ‘s CI. 

My OsX VirtualBox is even slower ;).
Ok I'll take this PR out of Draft mode. It still has some open optional TODOs (like ltcg feature). But I probably will not have the time to test and implement those optional features. 
So @Rastaban: change the PR as you like. 

Main changes:
- removed port qt5-modularscripts and split it functionality into more functions into qt5-base
- added qt_port_hashes.cmake for simpler upgrade. 
- added optional `VCPKG_QT_HOST_MKSPEC` and `VCPKG_QT_TARGET_MKSPEC` to select QTs build mkspecs from a triplet
- qt_\<config\>.conf are now copied from the build dir instead from the port dir
- fixed freetype dependencies.  
- cleanup of vcpkg_qmake scripts. No strange/unclear replacements anymore. 
- introduced `vcpkg_buildpath_length_warning`
- changed directory layout of the qt5 installation executables and mkspecs a bit.

**Comment by JackBoosY** [comment]
Test results:

|x64-osx             |test|notes
|--------------------|----|-----
|qt5-tools           |Pass|
|qtkeychain          |Pass|
|qt5-location        |Pass|
|qt5-webview         |Pass|
|qt5-graphicaleffects|Pass|
|qt5-declarative     |Pass|
|qt5-scxml           |Pass|
|qt5-purchasing      |Pass|
|qwt                 |Fail|Previously skipped, not a regression
|qt5-modularscripts  |    |Missing port dependency
|qt5-quickcontrols   |Pass|
|qt5-3d              |Pass|
|qt5-multimedia      |Pass|
|qt5-quickcontrols2  |Pass|
|qt5                 |Pass|

**Comment by longhuan2018** [comment]
the qt5-base/fixcmake.py only considers the file suffix of windows. Add the suffix of linux and osx to the regular expression to support unix. #8029
```
dllpattern = re.compile("_install_prefix}/bin/Qt5.*d+(.dll|.so)")
libpattern = re.compile("_install_prefix}/lib/Qt5.*d+(.lib|.a)")
exepattern = re.compile("_install_prefix}/bin/[a-z]+(.exe|)")
toolexepattern = re.compile("_install_prefix}/tools/qt5/bin/[a-z]+(.exe|)")
tooldllpattern = re.compile("_install_prefix}/tools/qt5/bin/Qt5.*d+(.dll|.so)")
```

**Comment by Rastaban** [comment]
removing `qt5-modularscripts` port make `vcpkg update` not delete it correctly.  I am bringing back the port as an empty shell for now.

**Comment by JackBoosY** [comment]
Can this issue fix #6085?

**Comment by Neumann-A** [comment]
@JackBoosY 
> Can this issue fix #6085?

Since all paths are set to `${CURRENT_INSTALLED_DIR}` in the the configure_qt script it should fix it. I doubt that all qt5 executables work though because the `${CURRENT_INSTALLED_DIR}/bin` dir must be on the path for it to work correctly (I couldn't find a proper way to copy all the dlls to the ${CURRENT_INSTALLED_DIR}/tools/qt5/bin directory due to overlaps in the dependencies of the different qt ports which would make a clean removal of single qt ports impossible. That is why every port has his own tools/${PORT} folder with the correct dependencies copied)

**Review by Rastaban — APPROVED** [review]

**Comment by Neumann-A** [comment]
@JackBoosY : here is the next #8159 ;)

**Pull request merged**
