### PR TITLE
[duktape] Update library to 2.4.0

### PR DESCRIPTION
**Pull request by ehsan-mohammadi**
Update `duktape` library to 2.4.0 version.

### CODE REVIEW

**Comment by ehsan-mohammadi** [comment]
Refer to https://github.com/microsoft/vcpkg/pull/7548#issuecomment-518117080:

> "`duktape` build failed on Linux because it requires tools from the system package manager: python-yaml. This tool needs to install manually. There are comments in duktape's portfile.cmake."

**Comment by ehsan-mohammadi** [comment]
@Rastaban Many thanks for reviewing. I updated the pip hash.

**Comment by ehsan-mohammadi** [comment]
@Rastaban Many thanks for reviewing. I updated the pip hash.

**Comment by cenit** [comment]
> Looks like the pip hash needs to be updated. 

does it means that the move to use a fixed release (3.3 in the address) is still not working as expected? :(

**Pull request merged**
