### PR TITLE
[vcpkg_copy_pdbs] Fix PDB path matching for link.exe on Wine

### LINKED ISSUE #42264: vcpkg_copy_pdbs() no longer works on non-Windows after #41609
We have a toolchain that wrap MSVC with wine on Linux https://github.com/mstorsjo/msvc-wine.

`dumpbin` in the toolchain outputs PDB paths in Unix style.

Image

Before #41609, `"PDB file found at.*'(.*)'"` matches the Unix style paths, but now it requires paths starting with a drive letter.

### PR DESCRIPTION
**Pull request by huangqinjin**
Fixes #42264.

Also fixes the dot escaping.

### CODE REVIEW

**Review by BillyONeal — APPROVED** [review]
This seems reasonable to me if build passes

**Review by FrankXie05 — APPROVED** [review]

**Comment by BillyONeal** [comment]
The build failures so far look like baseline issues, will keep you posted.

**Comment by BillyONeal** [comment]
The build failures are all openimageio which exactly matches the previous CI build, so I will merge through them: https://dev.azure.com/vcpkg/public/_build/results?buildId=109536

**Comment by BillyONeal** [comment]
Thanks for the fix!

**Comment by BillyONeal** [comment]
Hopefully the openimageio ones will be fixed by https://github.com/microsoft/vcpkg/pull/42305/

**Pull request merged**
