### PR TITLE
[proj4] Bump to proj 7.2.1

### PR DESCRIPTION
**Pull request by rhuijben**
**Describe the pull request**

Upgrade PROJ from 7.2.0 to 7.2.1 (minimal change)

### CODE REVIEW

**Review by JonLiu1993 — APPROVED** [review]

**Comment by JonLiu1993** [comment]
@rhuijben ,Have you tested all these features?

**Comment by rhuijben** [comment]
@JonLiu1993 Yes, I'm working on a project that now depends on this buid, so I tested the proj features. This proj release is just a minor patch release fixing some local issues in proj.

I would love to have a static build that still supports the tiff feature, but that will be a future patch. Without tiff support there is a reduced accuracy on some of the projections supported by proj.

**Comment by JonLiu1993** [comment]
> @JonLiu1993 Yes, I'm working on a project that now depends on this buid, so I tested the proj features. This proj release is just a minor patch release fixing some local issues in proj.
> 
> I would love to have a static build that still supports the tiff feature, but that will be a future patch. Without tiff support there is a reduced accuracy on some of the projections supported by proj.

Thank you for your contribution, great

**Comment by ras0219-msft** [comment]
LGTM, thanks for the update!

**Pull request merged**
