### PR TITLE
[yoga] Update to 3.0.2

### PR DESCRIPTION
**Pull request by waywardmonkeys**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [x] The "supports" clause reflects platforms that may be fixed by this new version.
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
I think the Android failures here are NDK 25 vs 26. Not positive though.

**Comment by waywardmonkeys** [comment]
Yes and those are features in C++20, which is enabled in the build flags. Also, upstream Yoga has CI jobs for Android (but on NDK 26).

**Comment by FrankXie05** [comment]
@waywardmonkeys Sorry, currently we have not updated to 26.  We can add this port of arm triplets to `ci.baseline.txt`,

**Comment by waywardmonkeys** [comment]
@FrankXie05 I made that update, so I think this is okay to go?

**Review by FrankXie05 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks!

**Pull request merged**
