### PR TITLE
[vcpkg baseline][armadillo] Update to 10.2.0 and also update the repository

### PR DESCRIPTION
**Pull request by NancyLi1013**
**Describe the pull request**

- What does your PR fix? Fixes #
```

-- Downloading https://gitlab.com/conradsnicta/armadillo-code/-/archive/24b4762cbfbd3ad14c99a4854acd3560559a3195/armadillo-code-24b4762cbfbd3ad14c99a4854acd3560559a3195.tar.gz... Failed. Status: 22;"HTTP response code said error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:184 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".

      If error with status 4 (Issue #15434),
      try setting "http://user:password@your-proxy-ip-address:port/".

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues
```
Update the repository from sourceforge since there is something wrong with the server on GitLab.

Note: No feature needs to test.

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by ras0219-msft** [comment]
Hi @NancyLi1013, I checked in a workaround for v10.1.0 as part of #15677 -- could you simply update this PR to be based off master? I'd like to move to using `vcpkg_from_sourceforge()` over `vcpkg_from_git()` (as you have it here).

**Comment by NancyLi1013** [comment]
Thanks for your information @ras0219-msft. I will update it later.

**Comment by JackBoosY** [comment]
Ping @ras0219  @ras0219-msft for review and merge this PR quickly.

**Comment by ras0219-msft** [comment]
Thanks!

**Pull request merged**
