### PR TITLE
Update vcpkg-tool to 2022-06-15

### LINKED ISSUE #15836: Impossible to install successfully new ports after a custom port has been installed strikes back
**Describe the bug**
With the current `master` branch since the PR has been merged https://github.com/microsoft/vcpkg/pull/15709 the use of custom ports at some point prevents to install any further non-custom port from vcpkg.

**Environment**
- OS: Windows
- Compiler: VS2019

**To Reproduce**
~~~
git clone https://github.com/microsoft/vcpkg  C:/vcpkg
git clone https://github.com/robotology/robotology-vcpkg-binary-ports C:/robotology-vcpkg-binary-ports
C:/vcpkg/bootstrap-vcpkg.sh
C:/vcpkg/vcpkg.exe --overlay-ports=C:/robotology-vcpkg-binary-ports install --triplet x64-windows ipopt-binary
C:/vcpkg/vcpkg.exe  install --triplet x64-windows asio
~~~
The last command will fail with the following error:
~~~
Computing installation plan...
Error: while loading  ipopt-binary:
The port directory (C:\vcpkg\ports\ipopt-binary) does not exist
Error: failed to load port from C:\vcpkg\ports\ipopt-binary
Note: Updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
~~~

**Expected behavior**
The `asio` port should be installed correctly, even if the custom port `ipopt-binary` had been installed before. 

**Failure logs** 
See https://github.com/robotology/robotology-vcpkg-ports/issues/18 for more details and the bisection that lead to identify the PR https://github.com/microsoft/vcpkg/pull/15709 . This is a regression that re-created the already existing issue https://github.com/microsoft/vcpkg/issues/10119 .

### LINKED ISSUE #16216: VCPKG_FORCE_SYSTEM_BINARIES cause vcpkg_apply_patches error on Windows
**Environment**
- OS: Windows

**To Reproduce**
1. set VCPKG_FORCE_SYSTEM_BINARIES=1
2. vcpkg install sqlite3

**Failure logs** 
```
-- Applying patch fix-arm-uwp.patch
CMake Error at scripts/cmake/vcpkg_apply_patches.cmake:68 (message):
  Applying patch failed.
Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:145 (vcpkg_apply_patches)
  ports/sqlite3/portfile.cmake:10 (vcpkg_extract_source_archive_ex)
  scripts/ports.cmake:131 (include)
```

**Additional context**
Add some logs to vcpkg_apply_patches
```
    message(STATUS "PATH = $ENV{PATH}")
    message(STATUS "GIT = ${GIT}")
```

got
```
-- PATH = C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\\Extensions\Microsoft\IntelliCode\CLI;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\bin\HostX64\x86;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\;C:\Program Files (x86)\HTML Help Workshop;C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\;;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32\Wbem;C:\WINDOWS\system32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\VC\Linux\bin\ConnectionManagerExe
-- GIT = GIT-NOTFOUND
```

PATH doesn't contain git installation path which should be
```
C:\vcpkg>where git
C:\Program Files\Git\cmd\git.exe
```

### LINKED ISSUE #21800: Diagnostics about vcpkg calling into other binaries don't differentiate between WinAPI Errors and application exit codes
**Describe the bug**
While running vcpkg we got the following error message:
```
error : curl failed to put file to file:///G:/Entwicklung/vcpkg/assetcache/abc123 with exit code '2' and http code '0'
```
But the problem was not, that curl exited with code 2, but the `CreateProcessA` function failed and `GetLastError` returned `2` aka `ERROR_FILE_NOT_FOUND`. So the problem was that there was no curl on the path. 

**Environment**
- OS: Windows

**To Reproduce**
1. Use a system without curl on the path or remove it from the path. 
2. Use vcpkg with some assetcache 

**Expected behavior**
The function should differentiate between failed WinAPI calls and the return code of the application. If you currently get a code `x` you don't know if the API call failed with code `x` or if the application existed with code `x`.   

**Additional context**
Happened on a windows server 2008 (Yeah I know that it is not supported anymore, there are plans to replace it)

### LINKED ISSUE #22686: Directory named 'control' is mistaken as a 'CONTROL' file failing manifest mode of vcpkg
**Describe the bug**
We wanted to add vcpkg to manage libraries in an existing project using the manifest mode with vcpkg.json.
We have added vcpkg.json to the root directory and use the -DCMAKE_TOOLCHAIN_FILE=vcpkginstall/.../vcpkg.cmake.
Running CMake results in following error message:

-- Running vcpkg install
Found both manifest and CONTROL file in port /Users/markus/Programming/vcpkgbug; please rename one or the other
-- Running vcpkg install - failed

Part of our code is in a directory named "control". Renaming it makes the bug disappear. 
Also adding a folder "control" to another project that works well with vcpkg will trigger this bug.

**Environment**
- OS: MacOs 11.6.2
- Compiler: Xcode_12_4 Clang

**To Reproduce**
1. take any project using a manifest: vcpkg.json
2. add a folder named 'control' at the same level as the manifest
3. Run configure

**Expected behavior**
I would have expected that a folder 'control' will not be interpreted as a CONTROL file.

### PR DESCRIPTION
**Pull request by BillyONeal**
* Update vcpkg-tool to 2022-06-15. See https://github.com/microsoft/vcpkg-tool/releases/tag/2022-06-15
* Add `=pass` entries from https://github.com/microsoft/vcpkg-tool/pull/579
* Cherry pick XUnit output from https://github.com/microsoft/vcpkg/pull/23477 which hooks up https://github.com/microsoft/vcpkg-tool/pull/585 (Thanks again @dg0yt !)
* Update release process document now that we can do the full tree rebuild to test the tool release before signing.

Thank you:

@autoantwort 
@christophe-calmejane 
@JackBoosY 
@benmcmorran
@hmoffatt 
@klalumiere 
@Thomas1664 
@Neumann-A 
@AenBleidd

for your contributions!

Fixes https://github.com/microsoft/vcpkg/issues/22686 .
Fixes https://github.com/microsoft/vcpkg/issues/21800 .
Fixes https://github.com/microsoft/vcpkg/issues/16216 .
Fixes https://github.com/microsoft/vcpkg/issues/15836 .

Full tree rebuild testing this update is: https://dev.azure.com/vcpkg/public/_build/results?buildId=73664&view=results

### CODE REVIEW

**Comment by BillyONeal** [comment]
Resolves https://github.com/microsoft/vcpkg/issues/22686 .
Resolves https://github.com/microsoft/vcpkg/issues/21800 .
Resolves https://github.com/microsoft/vcpkg/issues/16216 .
Resolves https://github.com/microsoft/vcpkg/issues/15836 .

**Comment by dg0yt** [comment]
This includes the simulated build error for `librttopo`. Before reverting this change I would like to see a test for another new feature, by temporarily adding `spatialite-tools:x64-windows = pass` to the CI baseline, to be triggered by simulated error.

**Comment by BillyONeal** [comment]
> This includes the simulated build error for `librttopo`.

Yep, already sucked it out into its own commit so that it can be force-pushed off. It works! Thank you! 
image

>Before reverting this change I would like to see a test for another new feature, by temporarily adding `spatialite-tools:x64-windows = pass` to the CI baseline, to be triggered by simulated error.

Stand by...

**Comment by BillyONeal** [comment]
> > Before reverting this change I would like to see a test for another new feature, by temporarily adding `spatialite-tools:x64-windows = pass` to the CI baseline, to be triggered by simulated error.
> 
> Stand by...

Does not show in the xunit output but does show on the terminal:

image

**Comment by dg0yt** [comment]
> Does not show in the xunit output but does show on the terminal

Yes. IMO it is good enough for now. But it should be turned into an error in vcpkg tool xunit output, aligning console output with xunit. (It is possibly that this is the only error, so it should be a formal error in xunit output even if not "run".)

**Comment by BillyONeal** [comment]
@cenit I know you were looking for this `=pass` feature @ras0219-msft implemented.

**Review by ras0219-msft — APPROVED** [review]

**Comment by cenit** [comment]
> @cenit I know you were looking for this `=pass` feature @ras0219-msft implemented.

wonderful, thanks.
I have been busy recently in many other projects, glad to see very nice improvements here in the meantime

**Pull request merged**
