### PR TITLE
[folly/fizz]Upgrade version.

### PR DESCRIPTION
**Pull request by JackBoosY**
Needed by port proxygen(#8766).

Note: all features test pass with following triples:
- x64-windows (only support x64)
- x64-windows-static (only support x64)

### CODE REVIEW

**Comment by JackBoosY** [comment]
`json.cpp(142): error C2061: syntax error: identifier 'ref'`
I cannot repro it, why?

**Comment by PhoebeHui** [comment]
Double checked, it's a compiler bug that already fixed in vs2019 16.4 preview 2.

The failures:
E:\VCPKG\jack\vcpkg\buildtrees\folly\src\46d6707604-d64234cbb5\folly\json.cpp(142): error C2061: syntax error: identifier 'ref'
E:\VCPKG\jack\vcpkg\buildtrees\folly\src\46d6707604-d64234cbb5\folly\json.cpp(145): note: see reference to function template instantiation 'auto folly::json::`anonymous-namespace'::Printer::printObject::<lambda_1>::operator ()<std::_Vector_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>,std::_Vector_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>,folly::Function<bool (const folly::dynamic &,const folly::dynamic &) const>>(_T1,_T2,const _T3 &) const' being compiled
        with
        [
            _Ty=ref,
            _T1=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<ref>>>,
            _T2=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<ref>>>,
            _T3=folly::Function<bool (const folly::dynamic &,const folly::dynamic &) const>
        ]
E:\VCPKG\jack\vcpkg\buildtrees\folly\src\46d6707604-d64234cbb5\folly/Range.h(1356): note: see reference to class template instantiation 'folly::Range<const char *>' being compiled
E:\VCPKG\jack\vcpkg\buildtrees\folly\src\46d6707604-d64234cbb5\folly\json.cpp(140): error C2065: 'a': undeclared identifier
E:\VCPKG\jack\vcpkg\buildtrees\folly\src\46d6707604-d64234cbb5\folly\json.cpp(140): error C2065: 'b': undeclared identifier
E:\VCPKG\jack\vcpkg\buildtrees\folly\src\46d6707604-d64234cbb5\folly\json.cpp(140): error C2064: term does not evaluate to a function taking 1 arguments
E:\VCPKG\jack\vcpkg\buildtrees\folly\src\46d6707604-d64234cbb5\folly\json.cpp(142): note: class does not define an 'operator()' or a user defined conversion operator to a pointer-to-function or reference-to-function that takes appropriate number of arguments
E:\VCPKG\jack\vcpkg\buildtrees\folly\src\46d6707604-d64234cbb5\folly\json.cpp(140): error C2672: 'operator __surrogate_func': no matching overloaded function found
E:\VCPKG\jack\vcpkg\buildtrees\folly\src\46d6707604-d64234cbb5\folly\json.cpp(142): error C2780: 'unknown-type std::less<void>::operator ()(_Ty1 &&,_Ty2 &&) noexcept(<expr>) const': expects 2 arguments - 1 provided
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\include\xstddef(242): note: see declaration of 'std::less<void>::operator ()'

**Comment by JackBoosY** [comment]
@vicroms I think this pr is ready to merge now.

**Review by PhoebeHui — APPROVED** [review]

**Comment by JackBoosY** [comment]
@dan-shaw Ready to merge now.

**Pull request merged**
