### PR TITLE
[ableton-link] Fix typo missing dash in name.

### PR DESCRIPTION
**Pull request by BillyONeal**
Typo from https://github.com/microsoft/vcpkg/pull/28892

### CODE REVIEW

**Comment by Neumann-A** [comment]
you probably don't want to bump port versions of abelton

**Comment by BillyONeal** [comment]
> you probably don't want to bump port versions of abelton

It must be to conform with version DB rules.

**Comment by Neumann-A** [comment]
> It must be to conform with version DB rules.

Which means you have a dangling reference to a non existent port in the db.

**Comment by Neumann-A** [comment]
hmm wait you didn't delete the wrongly typed v db.

**Comment by BillyONeal** [comment]
> hmm wait you didn't delete the wrongly typed v db.

In the unlikely event someone is referring to the old name with versioning I see no reason to break them.

**Review by JavierMatosD — APPROVED** [review]

**Pull request merged**
