### PR TITLE
[many ports] Warning to VCPKG long build path

### PR DESCRIPTION
**Pull request by PhoebeHui**
Changes:
1. Add warning for  long build path to port boost-system, related issue https://github.com/microsoft/vcpkg/issues/8272
2. Refactor others port to use function [vcpkg_buildpath_length_warning.cmake](https://github.com/microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_buildpath_length_warning.cmake)

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Review by Rastaban — APPROVED** [review]

**Comment by Neumann-A** [comment]
Instead of adding the warning manual to every port. would it not make sense to integrate the function into each function which extracts into the buildtree (e.g. vcpkg_from_github, vcpkg_extract_source_archive_ex et.c) and just inspect the longest filename observed within the source tree (+ some buffer) and only warn if it we expect to actually hit the limit?

**Comment by JackBoosY** [comment]
@Neumann-A Good idea.

**Comment by PhoebeHui** [comment]
Not all ports use vcpkg_from_github, some use vcpkg_from_gitlab.cmake or vcpkg_download_distfile.

Adding it to vcpkg_extract_source_archive_ex seems to be a solution(I haven't test yet), however, I just consider it's a bit weird to check long build path in that function, it does more thing than it looks.

**Comment by Neumann-A** [comment]
>Not all ports use vcpkg_from_github, some use vcpkg_from_gitlab.cmake or vcpkg_download_distfile.

then also change those?

Alternatively you could add the warning to the `vcpkg_<configure>` or `<install>` scripts?  `vcpkg_buildpath_length_warning` is not something which belongs in a portfile since every port must check its buildpath length on windows. I mean the user could be "crazy" and setup and vcpkg_root path with 250 characters which would probably automatically fail most ports. Alternatively vcpkg could decide to `subst` away the vcpkg_root path on windows automatically for the user.

**Comment by cbezault** [comment]
@neumann-a there's two conflicting design philosophies at play here. One is to make the port file as explicit as possible so someone reading it can understand what is going on without hunting for magic in the rest of the vcpkg code base. (Granted there is magic but we try to keep it to a minimum) and then there are vcpkg power users who write a lot of portfiles and want a minimum of boilerplate. We'll discuss on what side we fall on in this case.

**Comment by Neumann-A** [comment]
>there's two conflicting design philosophies at play here.

@cbezault: Not really since the problem here is dealing with a build limitation of the host machine and thus has nothing to do with the port itself. As such the buildsystem is responsible to throw the warning or solve the problem somehow and not the portfile. I mean the problem could also be solved in port.cmake where a warning is thrown if `CMAKE_CURRENT_BUILDTREES` is already longer than 25 chars or so.

**Comment by cenit** [comment]
@PhoebeHui for boost you modified the portfile but not the script that generates it. Next time it will be used, your mods will be lost ;)

**Comment by PhoebeHui** [comment]
@cenit, thanks for pointing out this!, I updated it with PR https://github.com/microsoft/vcpkg/pull/8372.

**Pull request merged**
