### PR TITLE
Add a port for the Microsoft/cppgraphqlgen project

### PR DESCRIPTION
**Pull request by wravery**
Tested on Windows and Ubuntu through WSL. The cpprestsdk dependency is tricky, I found that building it via `vcpkg` on Unix created static libraries instead of shared libraries, and it wasn't able to link this project properly against those without missing references.

### CODE REVIEW

**Comment by MathiasMagnus** [comment]
Having recently ported the OpenCL SDK to Linux, I also found that building static libraries results in missing references. It is because linking to a `libSomtehing.a` will not instruct the linker to pick up system dependencies, or generally anything it used to build. Because building cpprestsdk and cppgraphqlgen are two totally different CMake invocation, anything that is not persisted in the package config file or the find module file will be lost info.

In the case of OpenCL, I made use of the wrapper function feature, where you can wrap and `find_package` invocation with code that sets up a few variables that will guide the detection. You can also use this to inject extra dependencies downstreams require when linking to cppgraphqlgen. After detection. Perhaps after detection, you should inject the dependencies that cpprestsdk was built with.

**Comment by MathiasMagnus** [comment]
I'm saying this because building dynamic libraries on Linux will definitely not work, because the linker won't be able to load them. Without forcing the user to create `LD_LIBRARY_PATH` or entries under `/etc/ld.so.conf.d`, apps won't launch. Linux does not look for shared libraries beside the executables, so copying them around like on Windows will not solve anything. Linux pretty much **has to** use static libraries.

**Comment by wravery** [comment]
Dynamic libraries work OK if you use a redistributable package installed on the system. For example, Debian's/Ubuntu's apt package installs cpprestsdk in `/usr/local/…` (lib, include, etc.) as dynamic libraries, and by default that's on the `LD_LIBRARY_PATH` so it works.

Similarly, CMake can rewrite the rpath so the executables can find the target libraries when you run `make install`, or they can reference the ones that you built in the same directory. I found that worked OK when I built outside of vcpkg with the vcpkg `-DCMAKE_TOOLCHAIN_FILE=...` which pointed to the shared library dependencies built and installed by vcpkg.

It was just when I tried to use the static libraries for cpprestsdk that vcpkg built and installed as dependencies that I ran into this problem. I'm also the maintainer of cppgraphqlgen, and I'm reconsidering using cpprestsdk for this anyway. I may make that a non-default build option for consumers which already have that dependency and pick a header-only JSON library instead for consumers which don't. I might even be able to make it toggle that option depending on whether or not it detected cpprestsdk.

**Comment by ras0219-msft** [comment]
@wravery Thanks for the PR!

It's pretty easy to solve the static linking issue in CMake by using the `find_dependency()`[1] helper in your `cppgraphqlgen-config.cmake` file for _most_ libraries. The one exception is Boost, which doesn't have a good solution for CMake versions before 3.11.

I'll take a shot at fixing this issue via a patch, then we can look at upstreaming it if you're satisfied :)

[1] https://cmake.org/cmake/help/latest/module/CMakeFindDependencyMacro.html

**Comment by wravery** [comment]
@ras0219-msft Sure, sounds good, thanks!

**Comment by wravery** [comment]
I've mostly got the static linking working for vcpkg on UNIX, but I need to sort out my branches before it's really ready to pull into master.

**Pull request closed without merging**
