### PR TITLE
[vcpkg-gn] New port vcpkg-gn

### PR DESCRIPTION
**Pull request by dave-juicelabs**
Adds gn as a versioned port. See #21114

- #### What does your PR fix?  
  Fixes versioning issues of gn.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by dave-juicelabs** [comment]
v8 is failing for me on master as well. Not sure what to do here.

**Comment by dave-juicelabs** [comment]
Nothing I can do about the failed v8 port. It should not have been affected by this PR.

**Comment by dg0yt** [comment]
> Nothing I can do about the failed v8 port. It should not have been affected by this PR.

The port is triggered by the changes to `scripts/cmake/*gn`, but the failure is unrelated:
~~~
Command failed: D:/downloads/tools/git-2.32.0.2-windows/mingw32/bin/git.exe clone --depth 1 https://chromium.googlesource.com/external/github.com/google/googletest.git third_party/googletest/src
~~~

**Comment by dave-juicelabs** [comment]
Is there a way to rebuild the v8 port from master to check? Installing the v8 port from master on my machine results in the same error being presented to me.

**Comment by JackBoosY** [comment]
Sorry for late, I will handle this tomorrow.

**Comment by JackBoosY** [comment]
Ahh, this issue is caused by the google guys wrongly move those 3rd repos. And they were already fixed them.
I will rerun the pipeline tests and wish thoese regression will gone away.

**Comment by dave-juicelabs** [comment]
Any update on this PR?

**Review by JackBoosY — CHANGES_REQUESTED** [review]
Please follow document [scripts-extraction](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/scripts-extraction.md).

**Comment by dave-juicelabs** [comment]
I do not see anything against the document you provided. Do you see changes that are necessary?

**Comment by BillyONeal** [comment]
Thanks for extracting this out as a port :)

**Pull request merged**
