### PR TITLE
Install CGAL as header-only

### PR DESCRIPTION
**Pull request by lrineau**
I think the issue #2471 would be completely solved, if vcpkg installed CGAL as header-only. That way, the installed `CGALConfig.cmake` would search for its dependencies, instead of hard-coding their path in the file.

### CODE REVIEW

**Comment by LarryIII** [comment]
I am seeing new build failures on the following ports with this PR. Let me know if you need build log.
```
 Processing x64-windows                    844 vs 845
     cgal                          **regression**                Fail vs Pass
 Processing x64-windows-static             763 vs 764
     cgal                          **regression**                Fail vs Pass
 Processing x86-windows                    824 vs 825
     cgal                          **regression**                Fail vs Pass
```

**Comment by lrineau** [comment]
Hi @LarryIII. Thanks for pointing that out. We will try to reproduce the bug locally, first.

I just added @maxGimeno, a collegue of mines, as a collaborator for my fork. He has an easier access to Windows machines, to check the issue and fix it.

**Comment by lrineau** [comment]
I: 
  - have tried on Linux,
  - was able to reproduce the issue (a postbuild check failing) and,
  - pushed a fix: d6b3e0962674c7c114fc91209b857dda5dcf48d9.

At least the patch fixed the issue on Linux. Let's see what your CI think about it, on Windows...

**Comment by vicroms** [comment]
Hi @lrineau 

CGAL builds successfully for Windows 32- and 64-bit. 

However, the build is being skipped on Linux and Mac due to `mpir` failing to build on those platforms. Are you able to install `mpir` in Linux using `vcpkg`?
If so: 
* Which version of the port are you using? 
* Did you make any changes to `mpir`'s port?

**Comment by lrineau** [comment]
[**@vicroms**](https://github.com/vicroms) commented on [Mar 8, 2019, 11:30 PM GMT+1](https://github.com/Microsoft/vcpkg/pull/4975#issuecomment-471098429 "2019-03-08T22:30:04Z - Replied by Github Reply Comments"):
> However, the build is being skipped on Linux and Mac due to `mpir` failing to build on those platforms. Are you able to install `mpir` in Linux using `vcpkg`?  
> 
> If so:
> 
> *   Which version of the port are you using?

I am using the version in this PR: d6b3e0962674c7c114fc91209b857dda5dcf48d9.

> *   Did you make any changes to `mpir`'s port?

Not that I know. I just used the HEAD of this PR, and then:
```
lrineau@bonnard:~/Git/vcpkg/ports/cgal% ../../toolsrc/build.rel/vcpkg install cgal:x64-linux
The following packages will be built and installed:
    cgal[core]:x64-linux
  * mpfr[core]:x64-linux
  * mpir[core]:x64-linux
Additional packages (*) will be modified to complete this operation.
Starting package 1/3: mpir:x64-linux
Building package mpir[core]:x64-linux... 
-- Using cached /home/lrineau/Git/vcpkg/downloads/mpir-3.0.0.tar.bz2
-- Using source at /home/lrineau/Git/vcpkg/buildtrees/mpir/src/3.0.0-a3f571144a
-- Configuring x64-linux-dbg
-- Building x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package mpir[core]:x64-linux... done
Installing package mpir[core]:x64-linux... 
Installing package mpir[core]:x64-linux... done
Elapsed time for package mpir:x64-linux: 55.7 s
Starting package 2/3: mpfr:x64-linux
Building package mpfr[core]:x64-linux... 
-- Using cached /home/lrineau/Git/vcpkg/downloads/mpfr-4.0.1.tar.xz
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package mpfr[core]:x64-linux... done
Installing package mpfr[core]:x64-linux... 
Installing package mpfr[core]:x64-linux... done
Elapsed time for package mpfr:x64-linux: 5.432 s
Starting package 3/3: cgal:x64-linux
Building package cgal[core]:x64-linux... 
-- Using cached /home/lrineau/Git/vcpkg/downloads/CGAL-cgal-releases-CGAL-4.13.tar.gz
-- Using source at /home/lrineau/Git/vcpkg/buildtrees/cgal/src/-CGAL-4.13-1d6325e1db
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package cgal[core]:x64-linux... done
Installing package cgal[core]:x64-linux... 
Installing package cgal[core]:x64-linux... done
Elapsed time for package cgal:x64-linux: 7.75 s

Total elapsed time: 1.148 min

The package cgal:x64-linux provides CMake targets:

    find_package(CGAL CONFIG REQUIRED)
    # Note: 1 target(s) were omitted.
    target_link_libraries(main PRIVATE ${cgal_lib} CGAL::${cgal_lib} CGAL_Qt5_moc_and_resources CGAL::Qt5_moc_and_resources)

104.14s user 49.94s system 223% cpu 1:08.95s total
```

**Pull request merged**
