### PR TITLE
[qtwebengine] fix version

### PR DESCRIPTION
**Pull request by Neumann-A**

### CODE REVIEW

**Comment by Neumann-A** [comment]
@BillyONeal: Did you kill the run here? The message here is: `The agent has received a shutdown signal. This can happen when the agent service is stopped, or a manually started agent is canceled.`

**Comment by BillyONeal** [comment]
Nope. Maybe Azure Spot killed it :(

**Comment by Neumann-A** [comment]
@BillyONeal: This doesn't really need a CI run since it just fixes the version number to be correct.

**Comment by BillyONeal** [comment]
That's fair, thanks!

**Pull request merged**
