### PR TITLE
[imgui]: Update to 1.91.5

### PR DESCRIPTION
**Pull request by tomconder**
- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [X] SHA512s are updated for each updated download.
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version.~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by BillyONeal** [comment]
I cancelled the build because all triplets except x64-windows report failures and we're destroying the westus3 test VMs.

**Comment by tomconder** [comment]
The patch for hello-imgui is based on this upstream commit:
https://github.com/pthom/hello_imgui/commit/3ba369ad5b9bc281f01a2b2ee78d64ecef7d632a

The patch for imgui-node-editor is based on the comment from the imgui maintainer that GetKeyIndex() is, in fact, a no-op since 1.87. See:
https://github.com/ocornut/imgui/issues/5979#issuecomment-1345349492

**Comment by tomconder** [comment]
The **milerius-sfml-imgui** port is problematic. Its source repository consists of [3 files](https://github.com/Milerius/imgui-sfml-shared/tree/master/sfml-imgui) copied from the [imgui-sfml repo](https://github.com/SFML/imgui-sfml) 6 years ago.

Elias Daler, the author of imgui-sfml, has asked the repo owner to [add his name to the license](https://github.com/Milerius/imgui-sfml-shared/issues/1). In my opinion it would not feel right to copy updates from imgui-sfml into a patch for milerius-sfml-imgui without honoring this request.

I recommend deprecating and removing the milerius-cfml-imgui port. Users should use the sfml-imgui port instead.

Please advise.

**Comment by dg0yt** [comment]
> I recommend removing the milerius-sfml-imgui port. Users should use the imgui-sfml port instead.

Upstream code is unmaintained since 2018. Zero forks, one star, one author.

Please also remove its entry from `scripts/ci.baseline.txt`.

**Comment by tomconder** [comment]
Done. Removed entry from ci.baseline.txt

**Comment by tomconder** [comment]
Patch for imgui-sfml based on PRs from that repo: 

* 0002-clean-deprecated-api.patch - submitted patch: https://github.com/SFML/imgui-sfml/pull/305
* 0003-use-explicit-id.patch - upstream patch: https://github.com/SFML/imgui-sfml/pull/266

**Comment by BillyONeal** [comment]
Thanks for the update!

**Pull request merged**
