### PR TITLE
[taglib] Update to 1.13

### PR DESCRIPTION
**Pull request by complexlogic**
Upgrade TagLib to the latest stable version, 1.13. The removed patch was [merged upstream](https://github.com/taglib/taglib/commit/02c7e34681a680c619bed28c7d7248cbe3803a8f).

- #### What does your PR fix?
  See above.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  All. No.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

### CODE REVIEW

**Comment by complexlogic** [comment]
@microsoft-github-policy-service agree default

**Comment by FrankXie05** [comment]
Please bump the port version. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).
Also please run command `vcpkg x-add-version --taglib` then commit the changes.

**Comment by complexlogic** [comment]
@FrankXie05 The bumped port version should be 4, or 0?. The [documentation](https://vcpkg.readthedocs.io/en/latest/specifications/versioning/) says to reset to 0 when the package version increases, but when I set `port-version` to 0 I get the below error when running `vcpkg x-add-version`:
```
error: taglib is not properly formatted
Run `vcpkg format-manifest ports/taglib/vcpkg.json` to format the file
Don't forget to commit the result!
```
If I run that formatting command, it removes the `"port-version": 0` from the manifest file. So I am a bit confused here.

**Comment by FrankXie05** [comment]
@complexlogic 
The following steps are recommended:
1. Delete the `"port-version": 3,`line in the `vcpkg.json` file (for updates).
2. .Run `./vcpkg format-manifest ports/taglib/vcpkg.json`
3. `git commit -m "update"`
4. Run `./vcpkg x-add-version taglib` (Automatically add the line of `"port-version": 0,` to `ci.baseline`)
5. `git commit` and `git push`.

**Comment by complexlogic** [comment]
@FrankXie05 Done.

**Review by FrankXie05 — APPROVED** [review]

**Pull request merged**
