### PR TITLE
[certify] new port

### LINKED ISSUE #20630: [New Port Request] djarek / certify
Library name: djarek / certify

Library description: Platform-specific TLS keystore abstraction for use with Boost.ASIO and OpenSSL

Source repository URL: https://github.com/djarek/certify

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

Installing boost beast with vcpkg reports missing includes

#include <boost/certify/extensions.hpp>
#include <boost/certify/https_verification.hpp>

### PR DESCRIPTION
**Pull request by autoantwort**
Same as #16185 with suggestions. The PR author did not respond anymore, so I have integrated the suggestions and created this PR.

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Before we depend on this fork, let's first ensure the author intends to maintain it long-term.

@jens-diewald, could you speak for your future intentions regarding `certify`? Do you intend to take up long-term maintainership / submit it to boost / etc?

Given how young of a library it is, without a committed author I do not think this library is suitable for inclusion in the catalog.

**Comment by jens-diewald** [comment]
> 
> 
> Before we depend on this fork, let's first ensure the author intends to maintain it long-term.
> 
> @jens-diewald, could you speak for your future intentions regarding `certify`? Do you intend to take up long-term maintainership / submit it to boost / etc?
> 
> Given how young of a library it is, without a committed author I do not think this library is suitable for inclusion in the public curated catalog.

Hi, i mainly created my fork to make the pull request to the original repository.
The author of that repository stated, that he is no longer working on the project, but i hoped he would take the time to review the request. Sadly he did not respond at all.
That being said, i strongly believe this library should exist and i plan to fix some more shortcomings in the future.
But i can not make any promises. Particularly for submission to boost, there should probably be more people actively working on the library.

**Comment by JackBoosY** [comment]
I think we should rename the port to distinguish the original repo and use the same license as the original repo.

**Comment by JackBoosY** [comment]
Ping for response.

**Comment by jens-diewald** [comment]
I have looked at https://github.com/laudrup/boost-wintls and agree with djarek that this is a better approach to follow than the one of certify.
Only downside may be, that it is not as cross-platform, but it would be good enough for me.
So, i will not do any more work on certify for now.
Also, djarek has accepted my pull request and merged my changes into his repository, so there is no reason to use my fork any more.

**Pull request closed without merging**
