### PR TITLE
[libass] switch the build system to meson and enable asm optimization

### PR DESCRIPTION
**Pull request by Masaiki**
**Describe the pull request**

- #### What does your PR fix?  
  switch the build system to meson and enable asm optimization, meson files from https://github.com/libass/libass/pull/330, with few changes.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all, Yes

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by Masaiki** [comment]
x64-windows and x86-windows failed because ass.lib was not generated.
I can't find out why...

**Comment by JackBoosY** [comment]
```
Traceback (most recent call last):
  File "D:\downloads\tools\meson\meson-aeda7f249c4a5dbbecc52e44f382246a2377b5b0\mesonbuild\mesonmain.py", line 134, in run
    return options.run_func(options)
  File "D:\downloads\tools\meson\meson-aeda7f249c4a5dbbecc52e44f382246a2377b5b0\mesonbuild\minstall.py", line 719, in run
    installer.do_install(datafilename)
  File "D:\downloads\tools\meson\meson-aeda7f249c4a5dbbecc52e44f382246a2377b5b0\mesonbuild\minstall.py", line 511, in do_install
    self.install_targets(d, dm, destdir, fullprefix)
  File "D:\downloads\tools\meson\meson-aeda7f249c4a5dbbecc52e44f382246a2377b5b0\mesonbuild\minstall.py", line 614, in install_targets
    raise RuntimeError(f'File {t.fname!r} could not be found')
RuntimeError: File 'libass\\ass.lib' could not be found
```

**Comment by JackBoosY** [comment]
```
[20/21] "D:\downloads\tools\python\python-3.9.6-x64\python.exe" "D:\downloads\tools\meson\meson-aeda7f249c4a5dbbecc52e44f382246a2377b5b0\meson.py" "install" "--no-rebuild"
Installing libass\ass.dll to D:/packages/libass_x64-windows/debug\bin
Traceback (most recent call last):
  File "D:\downloads\tools\meson\meson-aeda7f249c4a5dbbecc52e44f382246a2377b5b0\mesonbuild\mesonmain.py", line 134, in run
    return options.run_func(options)
  File "D:\downloads\tools\meson\meson-aeda7f249c4a5dbbecc52e44f382246a2377b5b0\mesonbuild\minstall.py", line 719, in run
    installer.do_install(datafilename)
  File "D:\downloads\tools\meson\meson-aeda7f249c4a5dbbecc52e44f382246a2377b5b0\mesonbuild\minstall.py", line 511, in do_install
    self.install_targets(d, dm, destdir, fullprefix)
  File "D:\downloads\tools\meson\meson-aeda7f249c4a5dbbecc52e44f382246a2377b5b0\mesonbuild\minstall.py", line 614, in install_targets
    raise RuntimeError(f'File {t.fname!r} could not be found')
RuntimeError: File 'libass\\ass.lib' could not be found
FAILED: meson-install 
"D:\downloads\tools\python\python-3.9.6-x64\python.exe" "D:\downloads\tools\meson\meson-aeda7f249c4a5dbbecc52e44f382246a2377b5b0\meson.py" "install" "--no-rebuild"
ninja: build stopped: subcommand failed.
```

**Comment by Masaiki** [comment]
add patch from https://github.com/ShiftMediaProject/libass/commit/9a92b600710e37beeb5aff55b5e5c8162c270d38
add .def back to export functions.

**Comment by JackBoosY** [comment]
Depends on https://github.com/microsoft/vcpkg/pull/19629.

**Comment by Masaiki** [comment]
Remove codes about subproject for vcpkg doesn't need it.

**Review by JackBoosY — CHANGES_REQUESTED** [review]
Does the upstream not support meson now? I noticed you manually copied the meson scripts.

**Comment by Masaiki** [comment]
> Does the upstream not support meson now? I noticed you manually copied the meson scripts.

meson scripts are from this pr https://github.com/libass/libass/pull/330, and I do some fixes for it. upstream only support autoconf.

**Comment by JackBoosY** [comment]
@Masaiki  Okay, let's wait for libass/libass#330 merge.

**Comment by JackBoosY** [comment]
Why close this?

**Pull request closed without merging**
