### PR TITLE
[azure-iot-sdk-c] Add `use-prov-client` feature to enable device provisioning client

### PR DESCRIPTION
**Pull request by denis2glez**
The `use-prov-client` feature in the `vcpkg.json` manifest file was removed in PR #29046, ~probably by mistake when removing the `public-preview` feature,~ and therefore it is not possible to enable the device provisioning client.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [x] The "supports" clause reflects platforms that may be fixed by this new version.
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by denis2glez** [comment]
> @denis2glez please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by denis2glez** [comment]
I just found that it was intentionally removed in 2f40239.  @JoseSanchez7 could you please give any feedback on this?
Thanks

**Comment by denis2glez** [comment]
For future reference, these changes are working without any issues.

**Comment by BillyONeal** [comment]
The feature was explicitly removed in https://github.com/microsoft/vcpkg/pull/29046 ; I'm guessing @JoseSanchez7 intended to remove only the `public-preview` feature and accidentally removed this one.

**Pull request merged**
