### PR TITLE
[vcpkg] Set CMAKE_SYSTEM_PROCESSOR if target architecture is arm-linux or arm64-linux.

### PR DESCRIPTION
**Pull request by ghost**
**Describe the pull request**

> This change tries to fix issue #13395.
> 
> Root cause:
> In script mode, cmake won't populate CMAKE_SYSTEM_PROCESSOR parameter automatically. That parameter is
> required by libpng to configure build parameters. To fix this issue, we need explicitly set CMAKE_SYSTEM_PROCESSOR
> value.
> 
> Verify:
> On arm64-linux host, run `./vcpkg install tesseract:arm64-linux`.

- What does your PR fix? Fixes #
     #13395: [tesseract:arm64-linux] build failure 

- Which triplets are supported/not supported? Have you updated the CI baseline?
    * arm64-linux
    * arm-linux

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
    yes

### CODE REVIEW

**Comment by Neumann-A** [comment]
This belongs in the CMake toolchain not the triplet....

**Comment by JackBoosY** [comment]
Agreed with @Neumann-A.

**Comment by xieyubo** [comment]
To me, `CMAKE_SYSTEM_PROCESSOR` is an alias of `VCPKG_TARGET_ARCHITECTURE`. If `VCPKG_TARGET_ARCHITECTURE` belongs to the triplet, why does ` CMAKE_SYSTEM_PROCESSOR` not?

**Comment by Neumann-A** [comment]
>To me, CMAKE_SYSTEM_PROCESSOR is an alias of VCPKG_TARGET_ARCHITECTURE.

bad design to double down on the same thing especially since `VCPKG_TARGET_ARCHITECTURE` is basically a global variable while CMAKE_SYSTEM_PROCESSOR only applies to CMake. 

Furthermore if you compile your outside project for that system you probably have a toolchain setting all the values and compiler flags correctly. As such you can just use that toolchain within vcpkg and be done with it instead of repeating yourself in the triplet.

**Comment by xieyubo** [comment]
Updated. Change is moved to `scripts/toolchains/linux.cmake`. I found that we had set `CMAKE_SYSTEM_PROCESSOR` for x86 and x86_64 in that file. So I think it is also a right place to set for arm and arm64. But `CMAKE_SYSTEM_PROCESSOR` is needed for all system, not just linux, so might be the best place is `vcpkg_configure_cmake.cmake`? Maybe it's worth to discuss further. Currently, I think just following the old pattern is not bad.

**Comment by ras0219-msft** [comment]
This PR LGTM once we get the CI to pass :)

**Comment by Neumann-A** [comment]
Something similar needs to be applied to windows based arm triplets

**Comment by BillyONeal** [comment]
This broke openxr-loader:

```
CMake Error: install(EXPORT "openxr_loader_export" ...) includes target "openxr_loader" which requires target "jsoncpp_interface" that is not in any export set.
CMake Error in src/loader/CMakeLists.txt:
  export called with target "openxr_loader" which requires target
  "jsoncpp_interface" that is not in any export set.
```

**Comment by xieyubo** [comment]
@BillyONeal, seems this build failed on vcpkg/master already.

xyb@ubuntu:~/src/vcpkg2$ ./vcpkg install openxr-loader
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
Computing installation plan...
The following packages will be built and installed:
    openxr-loader[core]:x64-linux
Detecting compiler hash for triplet x64-linux...
Starting package 1/1: openxr-loader:x64-linux
Building package openxr-loader[core]:x64-linux...
Could not locate cached archive: /home/xyb/.cache/vcpkg/archives/13/13e0de973fe88aad24e157acf79e4ef5d171ca09.zip
-- Using cached /home/xyb/src/vcpkg2/downloads/KhronosGroup-OpenXR-SDK-e3a4e41d61544d8e2eba73f00da99b6818ec472b.tar.gz
-- Cleaning sources at /home/xyb/src/vcpkg2/buildtrees/openxr-loader/src/6818ec472b-d1dc3815be.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/xyb/src/vcpkg2/downloads/KhronosGroup-OpenXR-SDK-e3a4e41d61544d8e2eba73f00da99b6818ec472b.tar.gz
-- Using source at /home/xyb/src/vcpkg2/buildtrees/openxr-loader/src/6818ec472b-d1dc3815be.clean
-- Using cached /home/xyb/src/vcpkg2/downloads/KhronosGroup-OpenXR-SDK-Source-6dee6e228f47857adf5d7673eb90c64f04d33c60.tar.gz
-- Cleaning sources at /home/xyb/src/vcpkg2/buildtrees/openxr-loader/src/4f04d33c60-d722ef33b7.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/xyb/src/vcpkg2/downloads/KhronosGroup-OpenXR-SDK-Source-6dee6e228f47857adf5d7673eb90c64f04d33c60.tar.gz
-- Using source at /home/xyb/src/vcpkg2/buildtrees/openxr-loader/src/4f04d33c60-d722ef33b7.clean
-- Using cached /home/xyb/src/vcpkg2/downloads/KhronosGroup-OpenXR-hpp-097a7535563fc84bb7648ea9c5a4531a1e909458.tar.gz
-- Cleaning sources at /home/xyb/src/vcpkg2/buildtrees/openxr-loader/src/1a1e909458-6946dc9d31.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/xyb/src/vcpkg2/downloads/KhronosGroup-OpenXR-hpp-097a7535563fc84bb7648ea9c5a4531a1e909458.tar.gz
-- Using source at /home/xyb/src/vcpkg2/buildtrees/openxr-loader/src/1a1e909458-6946dc9d31.clean
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:141 (message):
    Command failed: /home/xyb/src/vcpkg2/downloads/tools/cmake-3.17.2-linux/cmake-3.17.2-Linux-x86_64/bin/cmake --build . --config Debug --target install -- -v -j65
    Working Directory: /home/xyb/src/vcpkg2/buildtrees/openxr-loader/x64-linux-dbg
    See logs for more information:
      /home/xyb/src/vcpkg2/buildtrees/openxr-loader/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:92 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/openxr-loader/portfile.cmake:52 (vcpkg_install_cmake)
  scripts/ports.cmake:79 (include)


**Error: Building package openxr-loader:x64-linux failed with: BUILD_FAILED**
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openxr-loader:x64-linux
  Vcpkg version: 2020.06.15-unknownhash

Additionally, attach any relevant sections from the log files above.
xyb@ubuntu:~/src/vcpkg2$ git log --oneline
**37c412ae0 (HEAD -> vcpkg-master, vcpkg/master) [osg] Fix feature plugin (#13942)**
3714469e0 [gcem] Update to version 1.13.1 (#13895)
54e7948c7 [mikktspace] Initial port (#13900)
dea7dbb19 [drogon] Update to 1.0.0 (#13907)
032f3e29c [freeimage] Fix macOS build error (#13916)

**Comment by xieyubo** [comment]
@BillyONeal , figured out the issue. That lib depends on another library (libxcb-glx0-dev), after run `sudo apt-get install libxcb-glx0-dev`, build success. It's not related to my PR.

**Comment by JackBoosY** [comment]
@xieyubo We already installed that before the pipeline check.
See https://github.com/microsoft/vcpkg/blob/bf7985127550bc93da55c721eb629b25e04d5349/scripts/azure-pipelines/linux/provision-image.sh#L18

**Comment by xieyubo** [comment]
@JackBoosY , still didn't repro on a clean environment:

xyb@xybpc:~/src/vcpkg$ ./vcpkg install openxr-loader
Computing installation plan...
The following packages will be built and installed:
    openxr-loader[core]:x64-linux
Detecting compiler hash for triplet x64-linux...
Starting package 1/1: openxr-loader:x64-linux
Building package openxr-loader[core]:x64-linux...
Could not locate cached archive: /home/xyb/.cache/vcpkg/archives/4d/4d7effa59a6a926bfcbc43c8890d66b32f9361fa.zip
-- Downloading https://github.com/KhronosGroup/OpenXR-SDK/archive/e3a4e41d61544d8e2eba73f00da99b6818ec472b.tar.gz...
-- Extracting source /home/xyb/src/vcpkg/downloads/KhronosGroup-OpenXR-SDK-e3a4e41d61544d8e2eba73f00da99b6818ec472b.tar.gz
-- Using source at /home/xyb/src/vcpkg/buildtrees/openxr-loader/src/6818ec472b-d1dc3815be.clean
-- Downloading https://github.com/KhronosGroup/OpenXR-SDK-Source/archive/6dee6e228f47857adf5d7673eb90c64f04d33c60.tar.gz...
-- Extracting source /home/xyb/src/vcpkg/downloads/KhronosGroup-OpenXR-SDK-Source-6dee6e228f47857adf5d7673eb90c64f04d33c60.tar.gz
-- Using source at /home/xyb/src/vcpkg/buildtrees/openxr-loader/src/4f04d33c60-d722ef33b7.clean
-- Downloading https://github.com/KhronosGroup/OpenXR-hpp/archive/097a7535563fc84bb7648ea9c5a4531a1e909458.tar.gz...
-- Extracting source /home/xyb/src/vcpkg/downloads/KhronosGroup-OpenXR-hpp-097a7535563fc84bb7648ea9c5a4531a1e909458.tar.gz
-- Using source at /home/xyb/src/vcpkg/buildtrees/openxr-loader/src/1a1e909458-6946dc9d31.clean
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Applying patch 001-fix-array-decl.patch
-- Installing: /home/xyb/src/vcpkg/packages/openxr-loader_x64-linux/share/openxr-loader/copyright
-- Performing post-build validation
-- Performing post-build validation done
sh: 1: zip: not found
Failed to store binary cache /home/xyb/.cache/vcpkg/archives/4d/4d7effa59a6a926bfcbc43c8890d66b32f9361fa.zip: No such file or directory
Building package openxr-loader[core]:x64-linux... done
Installing package openxr-loader[core]:x64-linux...
Installing package openxr-loader[core]:x64-linux... done
Elapsed time for package openxr-loader:x64-linux: 24.44 s

Total elapsed time: 25.48 s

The package openxr-loader:x64-linux provides CMake targets:

    find_package(OpenXR CONFIG REQUIRED)
    target_link_libraries(main PRIVATE OpenXR::headers OpenXR::openxr_loader OpenXR::openxr-all-supported)

**Comment by xieyubo** [comment]
OK, repro it. The repro step:
```
./vcpkg install jsoncpp
./vcpkg install openxr-loader
```

**Comment by xieyubo** [comment]
I think it is a separate issue not related to my PR. Even in vcpkg master build, if you install `jsoncpp` package first, then install `openxr-loader`, you will hit the same issue. But if you install `openxr-loader` before `jsoncpp`, you won't hit this issue. @JackBoosY @BillyONeal

**Comment by xieyubo** [comment]
I noticed @PhoebeHui just fixed the openxr-loader build dependency issue: https://github.com/microsoft/vcpkg/commit/790910f79f653978f90aadd958abf3c407215552. I've rebased with his change. I believe my PR should be pass now. @BillyONeal

**Review by JackBoosY — APPROVED** [review]

**Pull request merged**
