### PR TITLE
[boost-pfr] fields_count.hpp: fix compilation OOM issue

### PR DESCRIPTION
**Pull request by ghost**
# Description

With complex data structures, the current implementation inside `fields_count.hpp` can require a lot of memory
for the compiler to achieve its task. We had use cases where compiling a single C++ file required several gibabytes of RAM.

This isssue has been noticed with the following use case (but it is definitively not restricted to it):
- `boost-pfr` version `1.85.0#2`
- tripletx: `x64-windows`, `x64-windows-static`
- compiler: `clang-cl`, versions 16.0.6, 18.1.6

## References

This is the reference issue from the upstream repository:
 - https://github.com/boostorg/pfr/pull/120

### CODE REVIEW

**Comment by MonicaLiu0311** [comment]
> I have enriched the description mentioning a couple of PR for the mainstream repository about this fix.

Thank you for your contribution. The upstream is already trying to solve the problem. We will wait and see whether the upstream will release a new version after solving it.

**Comment by MonicaLiu0311** [comment]
The fix is ​​still being [worked](https://github.com/boostorg/pfr/pull/120) on upstream, so this PR will be approved. The patch will be removed after the next release.

**Review by MonicaLiu0311 — APPROVED** [review]

**Comment by JavierMatosD** [comment]
@MonicaLiu0311, @rressi-at-globus, please note that all boost portfiles are generated by `scripts/boost/generate-ports.ps1`. Any manual changes to their portfiles will be overwritten the next time the script is executed. Therefore, all modifications to the `Boost` ports must be made within the `generate-ports.ps1` script itself.

To correctly add a patch to a boost port:

	1.	Place the patch file in the port’s directory.
	2.	Bump the port’s version in the `$portVersions` section of the `generate-ports.ps1` script.
	3.	Execute the script to regenerate the portfiles.

I attempted to make these changes for you, but I do not have access to the branch.

**Comment by MonicaLiu0311** [comment]
@rressi-at-globus

**Pull request closed without merging**
