### PR TITLE
[protobuf] Correct protobuf under android (Fix issue #8218)

### LINKED ISSUE #8218: [protobuf]ubuntu-android build failure
**Host Environment**
- OS: [Ubuntu 18.04]
- Compiler: NDK

**To Reproduce**
`./vcpkg install protobuf`

**Failure logs** 
error: undefined reference to '__android_log_write'

with this command:
/opt/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=armv7-none-linux-androideabi21 --gcc-toolchain=/opt/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/opt/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/sysroot  -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -march=armv7-a -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -frtti -fexceptions  -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--exclude-libs,libunwind.a -Wl,--no-undefined -Qunused-arguments -Wl,-z,noexecstack -Wl,--gc-sections CMakeFiles/protoc.dir/home/mohsen/vcpkg/buildtrees/protobuf/src/v3.9.1-c12428cdd0/src/google/protobuf/compiler/main.cc.o  -o protoc-3.9.1.0  libprotocd.a libprotobufd.a -latomic -lm

### PR DESCRIPTION
**Pull request by pthom**
**Describe the pull request**
This PR fixes and issue for protobuf when building for Android. 
When linking, an error "undefined reference to '__android_log_write' was happening.

The original error is likely inside protobuf CMakeLists, which should link the log library under Android: see [this issue in protobuf repo](https://github.com/protocolbuffers/protobuf/issues/2719)

**This fixes https://github.com/microsoft/vcpkg/issues/8218**

- Which triplets are supported/not supported? 
There is no official Android triplet at the moment. I will add an example triplet below. 

- Have you updated the CI baseline?
No

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

---- 

There is no official android triplet file. So, I provide an example one below. May be it could be an inspiration for a triplet in the community folder (however I am *not* an android expert).

**Steps to reproduce the build**

1. Use this triplet file:

`triplets/android-armeabi-v7a.cmake`
````cmake
set(VCPKG_TARGET_ARCHITECTURE arm)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_CMAKE_SYSTEM_NAME Android)

set(ANDROID_NDK_HOME $ENV{ANDROID_NDK_HOME})
if ("${ANDROID_NDK_HOME}" MATCHES "^$")
  message(FATAL_ERROR 
    "Please set an env variable ANDROID_NDK_HOME pointing to your ndk-bundle folder. 
    For example: export ANDROID_NDK_HOME=/home/your-account/Android/Sdk/ndk-bundle")
endif()
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE ${ANDROID_NDK_HOME}/build/cmake/android.toolchain.cmake)

set(ANDROID_ABI armeabi-v7a)
# ANDROID_ABI can be : "armeabi-v7a" , "armeabi-v7a with NEON", "arm64-v8a", "x86" or "x86_64"
````

2. Download and install the [android ndk-bundle](https://developer.android.com/ndk/downloads/)

3. Set an env var to the ndk-bundle folder
````
    export ANDROID_NDK_HOME=/home/your-account/Android/Sdk/ndk-bundle
````

4. Build the protobuf package
````
    ./vcpkg install "protobuf:android-armeabi-v7a"
````

### CODE REVIEW

**Review by JackBoosY — CHANGES_REQUESTED** [review]
Please update the version info. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).

**Comment by JackBoosY** [comment]
@smzahraee Could you test this PR?

Thanks.

**Comment by pthom** [comment]
> Please update the version info. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#update-the-version-field-in-the-control-file-of-any-modified-ports).

Done, I switched from 3.11.4 to 3.11.4-1

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
LGTM.

**Comment by strega-nil** [comment]
LGTM, thanks @pthom :)

**Pull request merged**
