### PR TITLE
[Many tests ports] Run format-manifest on test_ports

### PR DESCRIPTION
**Pull request by talregev**
I run the command:
`find scripts/test_ports/ -name "vcpkg.json"  -exec ./vcpkg format-manifest "{}" \;`
you can take a look we chat here: #39285

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [x] The "supports" clause reflects platforms that may be fixed by this new version.
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Review by BillyONeal — APPROVED** [review]

**Comment by dg0yt** [comment]
FTR I think there is a reason why these manifest are not formatted:

Order of elements is sensitive to the content of `supports`, `dependencies` and `features`.
It is easy to remove a no-longer-unsupported platform or to add a now-supported dependency or feature, and it is *very easy* to review such modifcations.

But it is very hard to review what is the intented change and what is a formatting artifact when reviewing changes in a single commit.

So I tend to continue to not run format-manifest on these ports for trivial changes.
(But I strongly expect `vcpkg ci` to report a fail loudly if a manifest has invalid syntax!)

**Comment by talregev** [comment]
> But it is very hard to review what is the intented change and what is a formatting artifact when reviewing changes in a single commit.

We already review such a changes to regular ports.
Once it formated, the changes will be small.
Most of the difficulty review coming from cmake behavior, not json review.
After awhile tests don't to change.
As I say I also in favor in ci check,
But local check will be fast iteration for developers.
Also **_save CI precious time_** as we experience today.

**Comment by talregev** [comment]
I didn't not format the vcpkg-ci-openimageio because there was already PR open fixing the problem, and not wanted to create conflict.
So this PR #39285 is still valid.

**Comment by dg0yt** [comment]
> Once it formated, the changes will be small.

No, for the reasons already given... 

> Most of the difficulty review coming from cmake behavior, not json review.

Many of the test ports don't have "cmake behavior". The effect is achieved via the manifest alone.

> After awhile tests don't tend to change.

It can take a long while until a dependency or feature can be tested for android. Similar for C++20, C++23, or osx deployment targets.

---

To be clear, I don't object to this PR.
I just want to help understand why such formatting differences exist, and why it might be worthwile to accept them during normal test port updates.
(We don't have a problem with test port manifest formatting. We have a problem with CI not properly reporting malformed test port manifests.)

**Review by JonLiu1993 — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the fix!

**Pull request merged**
