### PR TITLE
[cudnn] Try to find CUDNN locally before downloading

### PR DESCRIPTION
**Pull request by jacobkahn**
Don't download cuDNN unless it's not found on the local system.

This allows using newer versions of cuDNN (esp those compiled with newer versions of CUDA) as dependencies in packages.

- Which triplets are supported/not supported? Have you updated the CI baseline?
Same as before. Tested `x64-linux`.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

Yes

### CODE REVIEW

**Review by PhoebeHui — CHANGES_REQUESTED** [review]
Thanks for the PR!

Could you update the Port-Version to 3 in CONTROL file?

**Comment by jacobkahn** [comment]
@PhoebeHui done!

**Review by PhoebeHui — APPROVED** [review]
LGTM, @strega-nil, could you help further review?

**Comment by strega-nil** [comment]
Awesome, thanks @jacobkahn :)

**Pull request merged**
