### PR TITLE
[libusb] Fixing the error of not being able to locate Libusb header files.

### PR DESCRIPTION
**Pull request by Zheng-Bicheng**

### CODE REVIEW

**Comment by Zheng-Bicheng** [comment]
* https://github.com/microsoft/vcpkg/issues/35558

**Review by dg0yt — CHANGES_REQUESTED** [review]
No. The wrapper isn't a wrapper, and it is about to be removed: #35498
Use `pkg_check_modules`.
Or add an `unofficial-libusb-config.cmake`.

**Comment by Zheng-Bicheng** [comment]
> No. The wrapper isn't a wrapper, and it is about to be removed: #35498 Use `pkg_check_modules`. Or add an `unofficial-libusb-config.cmake`.

I'm sorry, I didn't understand what 'The wrapper isn't a wrapper' means; it runs fine after I made local modifications.If someone else has already submitted a PR to fix this issue, I can wait for the PR to be completed.

**Comment by dg0yt** [comment]
`find_package(libusb)` somewhat works because vcpkg loads `vcpkg-make-wrapper.cmake`.
But there is no official find modules or config for libusb which would define an official cmake interface. Wrapper are meant to complement the official interface, e.g. add transitive usage requirements. They shall not completely take over the role of find modules or config.

libusb provides usage information via pkg-config. This is the official, portable interface, and it can be used in CMake, although with some limitations.

If there is still a desire to provide (and maintain) a CMake package, the wrapper must be ported to an unofficial cmake config, with a distinct name and target namespace, to signal the lock-in effect.
https://learn.microsoft.com/en-us/vcpkg/contributing/maintainer-guide#add-cmake-exports-in-an-unofficial--namespace

**Comment by JonLiu1993** [comment]
Duplicate of https://github.com/microsoft/vcpkg/pull/35498.

**Pull request closed without merging**
