### PR TITLE
[glm] Updated to 0.9.9.7

### PR DESCRIPTION
**Pull request by tagsemb**
Updated glm to latest release 0.9.9.7

### CODE REVIEW

**Review by c72578 — COMMENTED** [review]
*portfile.cmake:*
`include(vcpkg_common_functions)`
We no longer need to include this, please remove this line.

Could you change lines 24 and 25 to:
`file(INSTALL ${SOURCE_PATH}/copying.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)`

Remark: both files, manual.md and copying.txt contain the license. However, copying.txt is the smaller file and it is not necessary to install the whole manual.

**Comment by tagsemb** [comment]
@c72578: Thank you for the feedback, changes should be in the latest commit.

**Review by NancyLi1013 — APPROVED** [review]

**Comment by NancyLi1013** [comment]
Hi @tagsemb thanks for this PR.
@c72578 thanks for your review.
It looks good to me now.

**Review by vicroms — APPROVED** [review]

**Comment by vicroms** [comment]
Thanks for the PR @tagsemb  and thanks for the reviews @c72578 !

**Pull request merged**
