### PR TITLE
[minizip-ng] update to v4.0.1

### PR DESCRIPTION
**Pull request by miyanyan**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [ ] The "supports" clause reflects platforms that may be fixed by this new version
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [ ] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by miyanyan** [comment]
@microsoft-github-policy-service agree

**Comment by miyanyan** [comment]
the feature ```MZ_SIGNING``` seems not used in v4.0.1, so I remove it, see https://github.com/zlib-ng/minizip-ng.
btw, what features should be checked using ```vcpkg_check_features```, I find minizip-ng has a lot of options

**Comment by miyanyan** [comment]
changed ```CONFIG_PATH```, https://github.com/zlib-ng/minizip-ng/pull/704

**Review by Cheney-W — APPROVED** [review]

**Comment by Cheney-W** [comment]
> what features should be checked using `vcpkg_check_features`, I find minizip-ng has a lot of options

All of the features should be checked in vcpkg_check_features().

**Comment by miyanyan** [comment]
> > what features should be checked using `vcpkg_check_features`, I find minizip-ng has a lot of options
> 
> All of the features should be checked in vcpkg_check_features().

image
exclude the red options, right? 
what about ```MZ_COMPRESS_ONLY``` ```MZ_DECOMPRESS_ONLY``` ```MZ_FILE32_API```

**Comment by dg0yt** [comment]
> All of the features should be checked in vcpkg_check_features().

NO. PLEASE MAKE AN INFORMED SELECTION.

**Comment by dg0yt** [comment]
Is signing really gone, is it enabled in general, or does it need different options now?
(I wonder if it is linked to "OpennSSL encryption".)

**Comment by miyanyan** [comment]
> Is signing really gone, is it enabled in general, or does it need different options now? (I wonder if it is linked to "OpennSSL encryption".)

image
seems really gone

**Comment by miyanyan** [comment]
I think there are 8 default features, and 3 features base on platforms.
```
{
  "name": "minizip-ng",
  "version": "4.0.1",
  "description": "minizip-ng is a zip manipulation library written in C that is supported on Windows, macOS, and Linux.",
  "homepage": "https://github.com/zlib-ng/minizip-ng",
  "license": "Zlib",
  "supports": "!uwp",
  "dependencies": [
    {
      "name": "vcpkg-cmake",
      "host": true
    },
    {
      "name": "vcpkg-cmake-config",
      "host": true
    }
  ],
  "default-features": [
    "bzip2",
    "compat",
    "iconv",
    "lzma",
    "pkcrypt",
    "wzaes",
    "zlib",
    "zstd"
  ],
  "features": {
    "bzip2": {
      "description": "Enables BZIP2 compression",
      "dependencies": [
        "bzip2"
      ]
    },
    "compat": {
      "description": "Enables compatibility layer"
    },
    "iconv": {
      "description": "Enables iconv encoding conversion"
    },
    "libbsd": {
      "description": "Builds with libbsd crypto random",
      "supports": "linux"
    },
    "libcomp": {
      "description": "Enables Apple compression",
      "supports": "osx"
    },
    "lzma": {
      "description": "Enables LZMA compression",
      "dependencies": [
        "liblzma"
      ]
    },
    "openssl": {
      "description": "Enables OpenSSL for encryption",
      "supports": "linux",
      "dependencies": [
        "openssl"
      ]
    },
    "pkcrypt": {
      "description": "Enables PKWARE traditional encryption"
    },
    "wzaes": {
      "description": "Enables WinZIP AES encryption"
    },
    "zlib": {
      "description": "Enables ZLIB compression",
      "dependencies": [
        "zlib"
      ]
    },
    "zstd": {
      "description": "Enables ZSTD compression",
      "dependencies": [
        "zstd"
      ]
    }
  }
}
```

**Pull request merged**
