### PR TITLE
re-enable qt5-activeqt

### PR DESCRIPTION
**Pull request by Neumann-A**

### CODE REVIEW

**Comment by Neumann-A** [comment]
https://github.com/microsoft/vcpkg/issues/19922#issue-986445169

for my reference

```
Installed by qt5-declarative:x64-windows
    tools/qt5/bin/Qt5QuickControls2.dll ** owned by qt5-quickcontrols2
    tools/qt5/bin/Qt5QuickTemplates2.dll ** owned by qt5-quickcontrols2
    tools/qt5/bin/Qt5VirtualKeyboard.dll ** owned by qt5-virtualkeyboard
    tools/qt5/bin/plugins/platforminputcontexts/qtvirtualkeyboardplugin.dll
    tools/qt5/bin/qml/Qt/labs/calendar/qtlabscalendarplugin.dll
    tools/qt5/bin/qml/Qt/labs/location/locationlabsplugin.dll
    tools/qt5/bin/qml/Qt/labs/platform/qtlabsplatformplugin.dll
    tools/qt5/bin/qml/QtAudioEngine/declarative_audioengine.dll
    tools/qt5/bin/qml/QtBluetooth/declarative_bluetooth.dll
    tools/qt5/bin/qml/QtCharts/qtchartsqml2.dll
    tools/qt5/bin/qml/QtDataVisualization/datavisualizationqml2.dll
    tools/qt5/bin/qml/QtGraphicalEffects/private/qtgraphicaleffectsprivate.dll
    tools/qt5/bin/qml/QtGraphicalEffects/qtgraphicaleffectsplugin.dll
    tools/qt5/bin/qml/QtLocation/declarative_location.dll
    tools/qt5/bin/qml/QtMultimedia/declarative_multimedia.dll
    tools/qt5/bin/qml/QtNfc/declarative_nfc.dll
    tools/qt5/bin/qml/QtPositioning/declarative_positioning.dll
    tools/qt5/bin/qml/QtPurchasing/declarative_purchasing.dll
    tools/qt5/bin/qml/QtQml/RemoteObjects/qtqmlremoteobjects.dll
    tools/qt5/bin/qml/QtQuick/Controls.2/Fusion/qtquickcontrols2fusionstyleplugin.dll
    tools/qt5/bin/qml/QtQuick/Controls.2/Imagine/qtquickcontrols2imaginestyleplugin.dll
    tools/qt5/bin/qml/QtQuick/Controls.2/Material/qtquickcontrols2materialstyleplugin.dll
    tools/qt5/bin/qml/QtQuick/Controls.2/Universal/qtquickcontrols2universalstyleplugin.dll
    tools/qt5/bin/qml/QtQuick/Controls.2/qtquickcontrols2plugin.dll
    tools/qt5/bin/qml/QtQuick/Controls/Styles/Flat/qtquickextrasflatplugin.dll
    tools/qt5/bin/qml/QtQuick/Controls/qtquickcontrolsplugin.dll
    tools/qt5/bin/qml/QtQuick/Dialogs/Private/dialogsprivateplugin.dll
    tools/qt5/bin/qml/QtQuick/Dialogs/dialogplugin.dll
    tools/qt5/bin/qml/QtQuick/Extras/qtquickextrasplugin.dll
    tools/qt5/bin/qml/QtQuick/PrivateWidgets/widgetsplugin.dll
    tools/qt5/bin/qml/QtQuick/Templates.2/qtquicktemplates2plugin.dll
    tools/qt5/bin/qml/QtQuick/VirtualKeyboard/Settings/qtquickvirtualkeyboardsettingsplugin.dll
    tools/qt5/bin/qml/QtQuick/VirtualKeyboard/Styles/qtquickvirtualkeyboardstylesplugin.dll
    tools/qt5/bin/qml/QtQuick/VirtualKeyboard/qtquickvirtualkeyboardplugin.dll
    tools/qt5/bin/qml/QtQuick/XmlListModel/qmlxmllistmodelplugin.dll
    tools/qt5/bin/qml/QtRemoteObjects/qtremoteobjects.dll
    tools/qt5/bin/qml/QtScxml/declarative_scxml.dll
    tools/qt5/bin/qml/QtSensors/declarative_sensors.dll
    tools/qt5/bin/qml/QtWebChannel/declarative_webchannel.dll
    tools/qt5/bin/qml/QtWebSockets/declarative_qmlwebsockets.dll
    tools/qt5/bin/qml/QtWebView/declarative_webview.dll
    tools/qt5/bin/qml/QtWinExtras/qml_winextras.dll
    tools/qt5/bin/qml/org/kde/kholidays/kholidaysdeclarativeplugin.dll
    tools/qt5/bin/qml/org/kde/kitemmodels/itemmodelsplugin.dll
    tools/qt5/bin/qml/org/kde/solid/solidextensionplugin.dll
```
`qt5-quickcontrols2` depends on `qt5-declarative` so how can `qt5-declarative` install a dll build by `qt5-quickcontrols2` : cc @BillyONeal 
`qt5-virtualkeyboard` depends on `qt5-quickcontrols` which depends on `qt5-declarative`.... this does not make any sense.... 
This only makes sense if the installed tree was not correctly cleaned/removed.

**Comment by BillyONeal** [comment]
The colmap failure is https://github.com/microsoft/vcpkg/pull/19608

**Comment by Neumann-A** [comment]
No version bumps needed the recent merges to vcpkg required a rebuild of qt5-base any way so just reenabling qt5-activeqt is enough.

**Comment by JackBoosY** [comment]
Depends on https://github.com/microsoft/vcpkg/pull/19608.

**Comment by Neumann-A** [comment]
@JackBoosY Let me remove the dependency

**Comment by BillyONeal** [comment]
I believe just adding a downstream thing to ci.baseline.txt while removing something in the "cone of dependencies" shouldn't be a blocker.

Thanks @Neumann-A for your help in Qt bizarroworld once again :D

**Pull request merged**
