### PR TITLE
[freetype] Add mirror

### LINKED ISSUE #5072: [freetype] download fails - main download site is down
> Building package freetype[core]:x86-windows... 
> -- Downloading https://download-mirror.savannah.gnu.org/releases/freetype/freetype-2.8.1.tar.bz2...
> -- Downloading https://download-mirror.savannah.gnu.org/releases/freetype/freetype-2.8.1.tar.bz2... Failed. Status: 7;"Couldn't connect to server"

With no download mirror for the port, installation fails. Will open a new PR.

### PR DESCRIPTION
**Pull request by past-due**
This resolves #5072.

### CODE REVIEW

**Comment by sam3d** [comment]
That was amazingly fast, would love for this to get merged ASAP!

**Comment by past-due** [comment]
Looks like this may have gotten lost in the holiday shuffle. @ras0219-msft?

**Comment by past-due** [comment]
To clarify, this adds the official mirror listed at: https://www.freetype.org/download.html

**Comment by Codiferous** [comment]
I've verified that this mirror looks good on my local machine. We're waiting on a full CI run to complete, just for extra caution. When that's finished, I'll report back and merge if it looks good. 😄

**Comment by Codiferous** [comment]
Okay, everything looks good! I'm going to go ahead and merge this PR -- thanks!

**Pull request merged**
