### PR TITLE
[simdutf] Update to 5.2.5

### LINKED ISSUE #38028: [simdutf] Build error on x64-linux
Package: simdutf:x64-linux@5.2.2

**Host Environment**

- Host: x64-linux
- Compiler: GNU 13.2.1
-    vcpkg-tool version: 2024-03-14-7d353e869753e5609a1f1a057df3db8fd356e49d
    vcpkg-scripts version: 5fa0f075e 2024-04-05 (2 days ago)

**To Reproduce**

`vcpkg install --clean-after-build simdutf`
**Failure logs**

```
-- Downloading https://github.com/simdutf/simdutf/archive/v5.2.2.tar.gz -> simdutf-simdutf-v5.2.2.tar.gz...
-- Extracting source /vcpkg/downloads/simdutf-simdutf-v5.2.2.tar.gz
-- Using source at /vcpkg/buildtrees/simdutf/src/v5.2.2-4a2e23facb.clean
-- Found external ninja('1.11.1').
-- Configuring x64-linux
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Fixing pkgconfig file: /vcpkg/packages/simdutf_x64-linux/lib/pkgconfig/simdutf.pc
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:134 (message):
  /bin/pkg-config --exists simdutf failed with error code: 1

      ENV{PKG_CONFIG_PATH}: "/vcpkg/packages/simdutf_x64-linux/lib/pkgconfig:/vcpkg/packages/simdutf_x64-linux/share/pkgconfig:/vcpkg/installed/x64-linux/lib/pkgconfig:/vcpkg/installed/x64-linux/share/pkgconfig:/gcc/lib64/pkgconfig:"
      output: Package simdutf was not found in the pkg-config search path.

  Perhaps you should add the directory containing `simdutf.pc'

  to the PKG_CONFIG_PATH environment variable

  Package 'simdutf', required by 'virtual:world', not found
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:196 (z_vcpkg_fixup_pkgconfig_check_files)
  ports/simdutf/portfile.cmake:24 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:175 (include)

### PR DESCRIPTION
**Pull request by jimwang118**
Fixes https://github.com/microsoft/vcpkg/issues/38028
Update the upstream version to fix compilation issues.
- [X] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [X] SHA512s are updated for each updated download.
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version.~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [X] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [X] Only one version is added to each modified port's versions file.

Usage test pass with following triplets:

```
x86-windows
x64-windows
x64-windows-static
```

### CODE REVIEW

**Review by WangWeiLin-MV — APPROVED** [review]

**Comment by spinicist** [comment]
Thanks @jimwang118 for getting this done.

@dg0yt this looks good to merge?

**Comment by spinicist** [comment]
I have discovered that scnlib is still broken after this is fixed, due to fixed versions in the config file in scnlib. There is already `remove-simdutf-dependency-version.patch` in the scnlib port, the attached patch is also required to fix the `scn-config.cmake.in` file.

[config.patch](https://github.com/microsoft/vcpkg/files/15075963/config.patch)

**Comment by JavierMatosD** [comment]
@spinicist, since this is a simple port update, please apply the fix in a separate PR. Thanks for pointing out the bug!

**Comment by spinicist** [comment]
Looks like @petersteneteg beat me to it, big thanks to him

**Pull request merged**
