### PR TITLE
[oniguruma] Add new port

### PR DESCRIPTION
**Pull request by myd7349**
https://github.com/kkos/oniguruma

### CODE REVIEW

**Comment by myd7349** [comment]
Test project: https://github.com/myd7349/Ongoing-Study/tree/master/cpp/CMake/vcpkg/oniguruma_example

**Comment by Rastaban** [comment]
I see failures with uwp triplets.  Are those expected?

**Comment by myd7349** [comment]
@Rastaban Thanks for your attention.

I didn't test it with `x86-uwp` or `x64-uwp` before (since I am not familiar with `UWP` platform). But I did give `vcpkg install oniguruma:x86-uwp` a try few minutes ago and found the issue:

>4>e:\vcpkg\buildtrees\oniguruma\src\v6.9.1-752b57c683\src\regparse.c(7366): error C4703: potentially uninitialized local pointer variable 'Then' used [E:\vcpkg\buildtrees\oniguruma\x86-uwp-dbg\onig.vcxproj]
     4>e:\vcpkg\buildtrees\oniguruma\src\v6.9.1-752b57c683\src\regparse.c(6603): error C4703: potentially uninitialized local pointer variable 'tag_end' used [E:\vcpkg\buildtrees\oniguruma\x86-uwp-dbg\onig.vcxproj]
     4>e:\vcpkg\buildtrees\oniguruma\src\v6.9.1-752b57c683\src\regparse.c(6893): error C4703: potentially uninitialized local pointer variable 'tag_end' used [E:\vcpkg\buildtrees\oniguruma\x86-uwp-dbg\onig.vcxproj]

I think it may be caused by the `/W4` compiler option used by `oniguruma`:

https://github.com/kkos/oniguruma/blob/master/CMakeLists.txt#L13-L24

Maybe, we can fix this like this: https://github.com/Microsoft/vcpkg/issues/4577

**Comment by Rastaban** [comment]
@myd7349 that fix sounds good to me.  Another option is if the build uses /WX then you could just remove it so the warning continues to show up in the logs without causing a build failure.

**Comment by myd7349** [comment]
The author has fixed this issue in the upstream repository. I updated the port and found it worked for me.

**Comment by Rastaban** [comment]
Looks great, thanks for the port!

**Pull request merged**
