### PR TITLE
[vcpkg-tool-meson] Update to 1.5.1

### PR DESCRIPTION
**Pull request by dg0yt**

### CODE REVIEW

**Comment by Neumann-A** [comment]
Please check if CMAKE_BUILD_TYPE is actually forwarded.

**Comment by dg0yt** [comment]
> Please check if CMAKE_BUILD_TYPE is actually forwarded.

~~~
[binaries]
c = ['/android-ndk-r26/toolchains/llvm/prebuilt/linux-x86_64/bin/clang', '--target=aarch64-none-linux-android21', '-g', '-DANDROID', '-fdata-sections', '-ffunction-sections', '-funwind-tables', '-fstack-protector-strong', '-no-canonical-prefixes', '-D_FORTIFY_SOURCE=2', '-Wformat', '-Werror=format-security', '-fPIC', '-fno-limit-debug-info', '--sysroot=/android-ndk-r26/toolchains/llvm/prebuilt/linux-x86_64/sysroot']

[cmake]
CMAKE_BUILD_TYPE = 'Debug'

[built-in options]
c_args = ['--target=aarch64-none-linux-android21', '-g', '-DANDROID', '-fdata-sections', '-ffunction-sections', '-funwind-tables', '-fstack-protector-strong', '-no-canonical-prefixes', '-D_FORTIFY_SOURCE=2', '-Wformat', '-Werror=format-security', '-fPIC', '-fno-limit-debug-info', '--sysroot=/android-ndk-r26/toolchains/llvm/prebuilt/linux-x86_64/sysroot', '-I/home/kpa/Projekte/vcpkg/vcpkg/installed/arm64-android/include']
~~~
What else?

**Comment by dg0yt** [comment]
> Please check if CMAKE_BUILD_TYPE is actually forwarded.

~~~
[binaries]
c = ['/android-ndk-r26/toolchains/llvm/prebuilt/linux-x86_64/bin/clang', '--target=aarch64-none-linux-android21', '-g', '-DANDROID', '-fdata-sections', '-ffunction-sections', '-funwind-tables', '-fstack-protector-strong', '-no-canonical-prefixes', '-D_FORTIFY_SOURCE=2', '-Wformat', '-Werror=format-security', '-fPIC', '-fno-limit-debug-info', '--sysroot=/android-ndk-r26/toolchains/llvm/prebuilt/linux-x86_64/sysroot']

[cmake]
CMAKE_BUILD_TYPE = 'Debug'

[built-in options]
c_args = ['--target=aarch64-none-linux-android21', '-g', '-DANDROID', '-fdata-sections', '-ffunction-sections', '-funwind-tables', '-fstack-protector-strong', '-no-canonical-prefixes', '-D_FORTIFY_SOURCE=2', '-Wformat', '-Werror=format-security', '-fPIC', '-fno-limit-debug-info', '--sysroot=/android-ndk-r26/toolchains/llvm/prebuilt/linux-x86_64/sysroot', '-I/vcpkg/installed/arm64-android/include']
~~~
What else?

**Comment by Neumann-A** [comment]
> What else?

Nothing. Just gives me peace of mind that it actually works as intended. Last time I looked at one of the looks it was empty for some reason.

**Review by LilyWangLL — APPROVED** [review]

**Comment by BillyONeal** [comment]
Thanks for the update!

**Pull request merged**
