### PR TITLE
[libqglviewer] update to 2.9.1 + Qt6 + CMake

### PR DESCRIPTION
**Pull request by MehdiChinoune**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md)
- [x] SHA512s are updated for each updated download
- [ ] The "supports" clause reflects platforms that may be fixed by this new version
- [ ] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [x] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by dg0yt** [comment]
Does this package sufficiently forward link libaries for static usage via pkg-config and cmake config?

**Comment by MehdiChinoune** [comment]
> Does this package sufficiently forward link libaries for static usage via pkg-config and cmake config?

I haven't understand the question.

**Comment by dg0yt** [comment]
Upstream builds a shared QGLViewer library. On Linux etc. users only need to link to this shared library. Dependencies are resolved at runtime.
This PR enables building a static library. When linking to a static library, users must also also link to the libraries which are required by that static library. I.e. transitive dependencies must be known at user project build time. Even the order of libraries matters. Here, we are talking about qtbase libs and their transitive usage requirements. 
This information is expected to be carried in .pc files and .cmake config files. Given that upstream doesn't expect to build a static lib, I expect that the information is incomplete.

**Comment by MehdiChinoune** [comment]
> Upstream builds a shared QGLViewer library. On Linux etc. users only need to link to this shared library. Dependencies are resolved at runtime. This PR enables building a static library. When linking to a static library, users must also also link to the libraries which are required by that static library. I.e. transitive dependencies must be known at user project build time. Even the order of libraries matters. Here, we are talking about qtbase libs and their transitive usage requirements. This information is expected to be carried in .pc files and .cmake config files. Given that upstream doesn't expect to build a static lib, I expect that the information is incomplete.

I have disabled shared library on Windows, because It fails to build with MSVC.
Apparently they don't test/support Windows or MSVC!

**Comment by dg0yt** [comment]
I'm concerned about static linkage on non-windows, not about shared linkage on windows.

**Comment by MehdiChinoune** [comment]
> I'm concerned about static linkage on non-windows, not about shared linkage on windows.

Two options:
- Use qmake
- Default to static on Windows and shared elsewhere.

**Comment by dg0yt** [comment]
Use qmake downstream? This is a dead end with Qt6.

The first thing is to look into the installed config files.
- If they are complete, no problem.
- If they can be fixed easily, fix them. (CMake should be easy to get right. But IIRC Qt6 lacks .pc files for static builds.)
- If they cannot be fixed easily, do not offer static linkage. 
  I'm not sure if the situation for static linkage is really better with Windows.
  What is the problem with dynamic linkage on Windows? It is officially supported, and I spotted at least one export macro.

**Comment by MehdiChinoune** [comment]
>   What is the problem with dynamic linkage on Windows? It is officially supported, and I spotted at least one export macro.

Maybe they build only with MINGW, but with MSVC I got this:
```
...
D:\dev\vcpkg-qt5\buildtrees\libqglviewer\x64-windows-dbg\QGLViewer_autogen\SLZDDFIPUJ/moc_camera.cpp(404): error C2491: 'qglviewer::Camera::staticMetaObject': definition of dllimport static data member not allowed
...
D:\dev\vcpkg-qt5\buildtrees\libqglviewer\x64-windows-dbg\QGLViewer_autogen\SLZDDFIPUJ/moc_frame.cpp(91): error C2491: 'qglviewer::Frame::staticMetaObject': definition of dllimport static data member not allowed
...
D:\dev\vcpkg-qt5\buildtrees\libqglviewer\x64-windows-dbg\QGLViewer_autogen\SLZDDFIPUJ/moc_keyFrameInterpolator.cpp(194): error C2491: 'qglviewer::KeyFrameInterpolator::staticMetaObject': definition of dllimport static data member not allowed
...
```
MINGW+GCC accepts that, but MSVC (I think also MINGW+Clang) throws an error.

**Comment by dg0yt** [comment]
The CMake build system is new. AFAICS it misses the definition of `CREATE_QGLVIEWER_DLL` when building the DLL. .vcproj and .pro handle it. 
https://github.com/search?q=user%3AGillesDebunne+CREATE_QGLVIEWER_DLL&type=code

**Review by LilyWangLL — APPROVED** [review]

**Pull request merged**
