### PR TITLE
[docs] document that vcpkg_from_github works with Gitea

### PR DESCRIPTION
**Pull request by Be-ing**
https://github.com/microsoft/vcpkg/pull/20747#pullrequestreview-779956592

**Describe the pull request**

- #### What does your PR fix?  
  How to download sources from Gitea servers was not previously documented.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  N/A

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  N/A

### CODE REVIEW

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
Please apply `[this patch](https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/62793/artifacts?artifactName=format.diff&api-version=6.0&%24format=zip)` and commit.

**Comment by Be-ing** [comment]
That patch just undoes the change?

**Comment by JackBoosY** [comment]
@Be-ing I think you should also modify _scripts/cmake/vcpkg_from_github.cmake_.

**Comment by dg0yt** [comment]
> That patch just undoes the change?

If you changed the derived file, the patch is reversed...

**Comment by JackBoosY** [comment]
Please note our docs will be automaticly generated by the scripts in _scripts/cmake_.

**Review by ras0219-msft — APPROVED** [review]

**Comment by JackBoosY** [comment]
Depends on https://github.com/microsoft/vcpkg/pull/21344.

**Comment by BillyONeal** [comment]
Thanks for the note!

**Pull request merged**
