### PR TITLE
[open62541] new port

### PR DESCRIPTION
**Pull request by cenit**

### CODE REVIEW

**Comment by cenit** [comment]
What is failing, so that I can fix it?

**Comment by vicroms** [comment]
|x64-windows|master| test |notes
|-----------|------|------|-----
|open62541  |      |Pass  |New Port

|x64-windows-static|master| test |notes
|------------------|------|------|-----
|open62541         |      |Pass  |New Port

|x64-osx  |master| test |notes
|---------|------|------|-----
|open62541|      |Pass  |New Port

|arm64-windows|master| test |notes
|-------------|------|------|-----
|open62541    |      |Pass  |New Port

|x86-windows|master| test |notes
|-----------|------|------|-----
|open62541  |      |Pass  |New Port

|x64-linux|master| test |notes
|---------|------|------|-----
|open62541|      |Fail  |New Port

|x64-uwp  |master| test |notes
|---------|------|------|-----
|open62541|      |Fail  |New Port

|arm-uwp  |master| test |notes
|---------|------|------|-----
|open62541|      |Fail  |New Port

**Comment by cenit** [comment]
I will escape uwp explicitly, but on x64-Linux it is working perfectly here. I will need logs

**Comment by vicroms** [comment]
Here's the relevant section of the log:

```
[2/54] cd /mnt/buildtrees/open62541/x64-linux-dbg && /usr/bin/python /home/vcpkg/myagent/_work/2/s/buildtrees/open62541/src/v0.3.0-a3fe33fd2f/tools/nodeset_compiler/nodeset_compiler.py --generate-ns0 --internal-headers --max-string-length=0 --ignore /home/vcpkg/myagent/_work/2/s/buildtrees/open62541/src/v0.3.0-a3fe33fd2f/tools/nodeset_compiler/NodeID_NS0_Base.txt --xml /home/vcpkg/myagent/_work/2/s/buildtrees/open62541/src/v0.3.0-a3fe33fd2f/tools/schema/Opc.Ua.NodeSet2.Minimal.xml /mnt/buildtrees/open62541/x64-linux-dbg/src_generated/ua_namespace0
FAILED: src_generated/ua_namespace0.c src_generated/ua_namespace0.h 
cd /mnt/buildtrees/open62541/x64-linux-dbg && /usr/bin/python /home/vcpkg/myagent/_work/2/s/buildtrees/open62541/src/v0.3.0-a3fe33fd2f/tools/nodeset_compiler/nodeset_compiler.py --generate-ns0 --internal-headers --max-string-length=0 --ignore /home/vcpkg/myagent/_work/2/s/buildtrees/open62541/src/v0.3.0-a3fe33fd2f/tools/nodeset_compiler/NodeID_NS0_Base.txt --xml /home/vcpkg/myagent/_work/2/s/buildtrees/open62541/src/v0.3.0-a3fe33fd2f/tools/schema/Opc.Ua.NodeSet2.Minimal.xml /mnt/buildtrees/open62541/x64-linux-dbg/src_generated/ua_namespace0
Traceback (most recent call last):
  File "/home/vcpkg/myagent/_work/2/s/buildtrees/open62541/src/v0.3.0-a3fe33fd2f/tools/nodeset_compiler/nodeset_compiler.py", line 27, in <module>
    from nodeset import *
  File "/mnt/buildtrees/open62541/src/v0.3.0-a3fe33fd2f/tools/nodeset_compiler/nodeset.py", line 30, in <module>
    from nodes import *
  File "/mnt/buildtrees/open62541/src/v0.3.0-a3fe33fd2f/tools/nodeset_compiler/nodes.py", line 21, in <module>
    from datatypes import *
  File "/mnt/buildtrees/open62541/src/v0.3.0-a3fe33fd2f/tools/nodeset_compiler/datatypes.py", line 29, in <module>
    import six
ImportError: No module named six
```

[install-x64-linux-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2999108/install-x64-linux-dbg-out.log)

**Comment by cenit** [comment]
I deal in portfile.cmake with installing six package, both with easy_install if available or through pip (installing also it if necessary). It could be even a mechanism interesting to put inside vcpkg itself maybe?
I need log files from config stage to see what failed, thanks for now

**Comment by traversaro** [comment]
In the development version of open62541, the six dependency has been removed: https://github.com/open62541/open62541/pull/2493 . If installing the six package proves to be a problem, perhaps it can make sense to try to backport the six-removal patch to 0.3 for vcpkg.

**Comment by cenit** [comment]
It should not be a problem. I was able to fix it locally, can you please try it?
Also, the PR is perfectly compatible with the `-- head` command option, in case you want to try the latest commit revision (I am interested in it too)

**Comment by Rastaban** [comment]
@cenit, are these the files you wanted to see?
[config-x64-linux-dbg-err.log](https://github.com/Microsoft/vcpkg/files/3005425/config-x64-linux-dbg-err.log)
[config-x64-linux-dbg-out.log](https://github.com/Microsoft/vcpkg/files/3005426/config-x64-linux-dbg-out.log)

**Comment by cenit** [comment]
Nope... is there any way to have logs from the screen?

**Comment by Rastaban** [comment]
Here is the console output:
```
Starting package 1/1: open62541:x64-linux
Building package open62541[core]:x64-linux... 
Could not locate cached archive: /home/vcpkg/myagent/_work/2/s/archives/cc/cc8472d1e71c2814f144a43f618e157584f4a102.zip
-- Downloading https://github.com/open62541/open62541/archive/v0.3.0.tar.gz...
-- Extracting source /home/vcpkg/myagent/_work/2/s/downloads/open62541-open62541-v0.3.0.tar.gz
-- Using source at /home/vcpkg/myagent/_work/2/s/buildtrees/open62541/src/v0.3.0-a3fe33fd2f
-- Using cached /home/vcpkg/myagent/_work/2/s/downloads/tools/python/python3/get-pip.py
/usr/bin/python: can't open file '/usr/bin/get-pip.py': [Errno 2] No such file or directory
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: /home/vcpkg/myagent/_work/2/s/downloads/tools/cmake-3.12.4-linux/cmake-3.12.4-Linux-x86_64/bin/cmake;--build;.;--config;Debug;--target;install;--;-v;-j1
    Working Directory: /home/vcpkg/myagent/_work/2/s/buildtrees/open62541/x64-linux-dbg
    See logs for more information:
      /home/vcpkg/myagent/_work/2/s/buildtrees/open62541/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/open62541/portfile.cmake:48 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)


Error: Building package open62541:x64-linux failed with: BUILD_FAILED
Elapsed time for package open62541:x64-linux: 2.856 s
```

**Comment by traversaro** [comment]
> Also, the PR is perfectly compatible with the `--head` command option, in case you want to try the latest commit revision (I am interested in it too)

Cool. I  am currently using a locally forked copy of open62541, but as soon we switch back to the upstream one, I will happy to check it out.

**Comment by Voskrese** [comment]
A great example of how to use PYTHON + PIP
Thx!

**Comment by cenit** [comment]
I used the same idea to other ports, also, after testing it into this one. I think it could also be integrated somehow into `vcpkg` to enable `pip`/`easy_install` with an even more clean approach

**Pull request merged**
