### PR TITLE
[rubberband] new port with version 2.0.2

### PR DESCRIPTION
**Pull request by Be-ing**
- #### What does your PR fix?  
  Add new port for Rubberband

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  yes

### CODE REVIEW

**Comment by Be-ing** [comment]
I don't know why the Windows builds are failing. I reported this [upstream](https://github.com/breakfastquay/rubberband/issues/53).

**Comment by dg0yt** [comment]
Looks like this happened before: https://github.com/microsoft/vcpkg/issues/22196#issuecomment-1001037749

**Comment by Be-ing** [comment]
The issue seems to be a bug in Meson: https://github.com/mesonbuild/meson/issues/9730

**Review by faysal247 — APPROVED** [review]

**Comment by Be-ing** [comment]
I rebased hoping that #22032 would fix the Windows builds. Unfortunately it is still failing with the same error.

**Comment by JonLiu1993** [comment]
Ping @Be-ing  for response, Is work still being done for this PR?

**Comment by JonLiu1993** [comment]
Because of blocking, temporarily convert this pr to draft

**Comment by JonLiu1993** [comment]
Closing this PR since it seems that no progress is being made. Please reopen if work is still being done.

**Pull request closed without merging**
