### PR TITLE
set cmake_prefix_path correctly within vcpkg_configure_meson

### PR DESCRIPTION
**Pull request by NNemec**
Using of a new feature of meson 0.51.0, this allows dependencies of a meson-based port to be resolved by .cmake files provided by other ports.

### CODE REVIEW

**Comment by Voskrese** [comment]
works! Thanks!, there is another flag -DARCHS =

`vcpkg install glib[*] --triplet x64-windows` glib meson

`-Dcmake_prefix_path=E:/tools/vcpkg/installed/x64-windows`

`E:/tools/vcpkg/downloads/tools/python/python3/python.exe E:/tools/vcpkg/downloads/tools/meson/meson-0.51.0/meson.py --backend=ninja -Dinternal_pcre=true -Dnls=disabled -Dc_args=/I:E:/tools/vcpkg/installed/x64-windows/include -Dcpp_args=/I:E:/tools/vcpkg/installed/x64-windows/include -Dcmake_prefix_path=E:/tools/vcpkg/installed/x64-windows --buildtype=plain -Ddefault_library=shared -Db_staticpic=false --buildtype=debug -Derrorlogs=true -Ddebug=true --prefix=E:/tools/vcpkg/packages/glib_x64-windows/debug --datadir=../share --includedir=../include --bindir=bin E:/tools/vcpkg/buildtrees/glib/src/glib-2-5b564ae5a5`

```
"C:/Program Files/cmake/bin\cmake.EXE" -G "Visual Studio 10 2010" --trace-expand -DNAME=libelf -DARCHS= -DCMAKE_PREFIX_PATH=E:/tools/vcpkg/installed/x64-windows .
"C:/Program Files/cmake/bin\cmake.EXE" --trace-expand -DNAME=libelf -DARCHS= -DCMAKE_PREFIX_PATH=E:/tools/vcpkg/installed/x64-windows .
"C:/Program Files/cmake/bin\cmake.EXE" -G "Unix Makefiles" --trace-expand -DNAME=libelf -DARCHS= -DCMAKE_PREFIX_PATH=E:/tools/vcpkg/installed/x64-windows .
```

**Comment by Voskrese** [comment]
I understand flag -DARCHS = affects folder names, for windows it is not significant

lib64 lib32 ...

**Comment by NNemec** [comment]
-DARCHS does not appear to affect my work. Do you see any reason to block this PR?

**Comment by Voskrese** [comment]
why block? )) everything is working

> just wait, very slow to accept fixes

**Comment by ras0219-msft** [comment]
@barcharcraz for a review :) 🦇

**Comment by barcharcraz** [comment]
looks good to me.

**Comment by grdowns** [comment]
Thanks for the fix, @NNemec!

**Pull request merged**
