### PR TITLE
Update nlopt

### PR DESCRIPTION
**Pull request by MVoz**
fix Matlab_MX_LIBRARY:FILEPATH

### CODE REVIEW

**Comment by alexkaratarakis** [comment]
@Voskrese 
Sorry for messing up the PR. I merged the change in master here: https://github.com/Microsoft/vcpkg/commit/ccfd34f1a60caa1d826581b2dd4ffd65898c02f9

**Comment by Voskrese** [comment]
@alexkaratarakis No problem, the main thing is to compile the port ;)

**Comment by alexkaratarakis** [comment]
@Voskrese 
If possible, please delete the patch-2 branch to cleanup this mess. 
https://github.com/Voskrese/vcpkg/tree/patch-2

**Comment by Voskrese** [comment]
@alexkaratarakis It's a go? ;) Did you ruin anything?

**Comment by alexkaratarakis** [comment]
@Voskrese 
Thanks! :)
Fortunately no issues, just a mixup from processing a bunch of PRs at once.

**Pull request closed without merging**
