### PR TITLE
fix issue #7543, remove PREFER_NINJA

### PR DESCRIPTION
**Pull request by the-loki**
fix issue #7543, remove PREFER_NINJA

### CODE REVIEW

**Comment by cbezault** [comment]
LLVM is still failing to build on anything but `x86-windows` and `x64-osx`.

**Comment by 404Polaris** [comment]
> LLVM is still failing to build on anything but `x86-windows` and `x64-osx`.

it's work well on my pc(i test it on ubuntu64 and,windows-x64,windows-x86),can i get these err log files in CI?

install-x64-windows-rel-out.log
install-x64-windows-rel-out-1.log
install-x64-windows-static-rel-out.log
install-x64-windows-static-rel-out-1.log
install-x64-linux-dbg-out.log
install-x64-linux-dbg-err.log

**Comment by cbezault** [comment]
That's a little difficult unfortunately. If there isn't a difference from the baseline logs are not saved. I need to talk to @Rastaban about fixing that. He's out of the office for a while and I'm a little too busy to look into it right now so this PR might sit for a little while.

I'm sorry about that, if I end up with some time on my hands I'll look into improving saving the logs.

**Comment by 404Polaris** [comment]
Okay, if there is any result, please reply to me in this PR. Thank you very much.

> That's a little difficult unfortunately. If there isn't a difference from the baseline logs are not saved. I need to talk to @Rastaban about fixing that. He's out of the office for a while and I'm a little too busy to look into it right now so this PR might sit for a little while.
> 
> I'm sorry about that, if I end up with some time on my hands I'll look into improving saving the logs.

Okay, if there is any result, please reply to me in this PR. Thank you very much.

**Comment by cenit** [comment]
LLVM was manually excluded from CI build, unfortunately. Is it still the case?

**Comment by 404Polaris** [comment]
> LLVM was manually excluded from CI build, unfortunately. Is it still the case?

This problem still exists on my PC. I will test it after I reinstall the operating system and environment to see if it is related to system version, system language, or VS version.



I'm going to close this PR, and if the problem still exists or has been solved, I'll go to issue to reply.

**Pull request closed without merging**
