### PR TITLE
[tcl]Upgrade to 8.6.9 and use vcpkg_install_make/vcpkg_install_nmake.

### PR DESCRIPTION
**Pull request by JackBoosY**
1. Switch to `vcpkg_install_make`/`vcpkg_install_nmake`
2. Upgrade to v8.6.9

Need to wait #8489 merge and merge.

### CODE REVIEW

**Review by cbezault — CHANGES_REQUESTED** [review]
Unfortunately this is actually going to be a downgrade (but I'm okay with that). I'm pretty sure the PR I merged had a dev version of Tcl.

**Comment by Voskrese** [comment]
opt static,msvcrt

**Comment by cbezault** [comment]
@voskrese sorry it's not clear what you mean and I'd like to see this PR merged.

**Comment by Voskrese** [comment]
@cbezault 
build static + add

`OPTS=static,msvcrt`

https://github.com/tcltk/tcl/blob/db5724895859981b0652052eb14fe9290539355c/win/buildall.vc.bat#L71

**Comment by JackBoosY** [comment]
@Voskrese Using msvcrt will change crt linkage to dynamic, while crt linkage when building static libraries should be static.
And when static build, no matter whether I build debug or release will generate debug library, I don't know how to deal with this problem.

**Pull request merged**
