### PR TITLE
[azure-kinect-sensor-sdk] Add new port

### PR DESCRIPTION
**Pull request by JackBoosY**
Too many files needs to be fixed...

Related: #8747.

### CODE REVIEW

**Review by PhoebeHui — APPROVED** [review]

**Comment by jasjuang** [comment]
Is this PR ready to merge? I really want to see this in vcpkg.

**Review by dan-shaw — APPROVED** [review]

**Comment by dan-shaw** [comment]
LGTM @jasjuang We are waiting for the MacOS CI pipeline to be back up.

**Pull request merged**
