### PR TITLE
[raylib] Cleanup, fix platform support

### LINKED ISSUE #39996: [glfw] Undifined Reference to asan / ubsan
**Describe the bug**
Hello, I am trying to install and use raylib port, which depends on glfw. I have a simple CMake project. It seems like the GLFW port requires the adress sanitizer runtime. When adding `asan` and `ubsan` to my `target_link_library`,  my program compiles and runs but reports false (?) memory leaks from glfw3. My intention is to completely disable the address sanitizer runtime.

I tried manually building glfw3 from source and it doesn't happen.

**Environment**
- OS: EndevourOS KDE Plasma 
- Compiler: GCC 14.1.1

**To Reproduce**
1. Download the example project
2. Run vcpkg install
3. Build with CMake

**Expected behavior**

**Failure logs**
[cmake_error.txt](https://github.com/user-attachments/files/16321753/cmake_error.txt)

**Additional context**
[Sample.zip](https://github.com/user-attachments/files/16321754/Sample.zip)

### PR DESCRIPTION
**Pull request by dg0yt**
Enable android and emscripten.
Don't suggest X packages for osx.
Resolves #39996.

### CODE REVIEW

**Comment by AregevDev** [comment]
I tested the build on Windows. Devendoring the header files causes MSVC to complain about redefinitions between raylib and the Windows headers. I have no idea why

**Comment by dg0yt** [comment]
> I complains about the Windows headers themselves? What?

That's what I thought. I guess that one of the devendored headers pulls in the regular Windows headers (which is fine) where raylib has local definitions to avoid including the headers (which is bad, in particular when there is a mismatch.)

**Comment by AregevDev** [comment]
I'll try diffing the vendored headers against the vcpkg headers, I'll see what I can find. We can probably apply a patch that disables the `Windows.h` include.

**Comment by AregevDev** [comment]
We can also try isolating one vcpkg header at a time to isolate the problematic headers. I didn't have enough time to debug the portfile thoroughly.

Thanks for letting me merge my sanitizers PR btw.

**Comment by dg0yt** [comment]
Checks are green now. Can you test this with a real app @AregevDev?

**Comment by AregevDev** [comment]
I'll be able to in around 6 hrs, is that OK?

**Comment by dg0yt** [comment]
Oh, I'm not in a hurry at all. It was broken for a long time...

**Comment by AregevDev** [comment]
Works for me on my Windows VM. My sample project builds

**Comment by jimwang118** [comment]
Usage test pass with following triplet:

```
x64-linux
```

**Review by data-queue — APPROVED** [review]

**Pull request merged**
