### PR TITLE
[openmvg] Update version to v2.0

### LINKED ISSUE #21364: [openmvg] update to 2.0
Library name: openMVG

New version number: 2.0

See: https://github.com/openMVG/openMVG/releases/tag/v2.0

Also fixes the issue with Eigen3.4.0: https://github.com/microsoft/vcpkg/pull/20056

### PR DESCRIPTION
**Pull request by FrankXie05**
Fix #21364 

Update [openmvg] to the latest version 2.0

Note: No feature needs to test.

### CODE REVIEW

**Comment by cenit** [comment]
build_fixes.patch is still in the port folder even if not used anymore? why the patch rename, that was hiding the problem?

**Comment by FrankXie05** [comment]
@cenit  Thanks for your reminder, I will corrcet it right away. :)

**Comment by cenit** [comment]
now the situation is opposite. There is the new fix-build.patch that you introduced totally unused but still pushed in this PR. Please delete that file

**Review by JonLiu1993 — APPROVED** [review]

**Comment by cenit** [comment]
now that graphviz has been merge, openmvg[tool] feature can depend on that, and you can remove the message info in the portfile (patch also the python scripts to use neato from vcpkg folder!)

https://github.com/microsoft/vcpkg/pull/20564

**Comment by FrankXie05** [comment]
This PR has been resolved by another PR #22020

**Pull request closed without merging**
