### PR TITLE
[akali] Update string replace method to embed AKALI_STATIC

### PR DESCRIPTION
**Pull request by winsoft666**
**Describe the pull request**

- #### What does your PR fix?
  Fix string replace bug in vcpkg.json

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  <linux, windows, macos / arm>, <No>

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  `Yes`

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  <Yes>

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by BillyONeal** [comment]
Thanks for the cleanup!

**Comment by JonLiu1993** [comment]
@winsoft666, The akali port cannot be downloaded now because the package link is invalid. I can't visit the homepage of akali https://github.com/winsoft666/akali now. I wonder if this library no longer exists? Or changed to another name?

**Comment by winsoft666** [comment]
Please forgive me for replying to you so late. winsoft666/akali project had to be removed dut to sensitive data.
could you help me remove this project from the library?
| |
smart7178
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 4/4/2023 15:02 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [microsoft/vcpkg] [akali] Update string replace method to embed AKALI_STATIC (PR #24741) |

@winsoft666, The akali port cannot be downloaded now because the package link is invalid. I can't visit the homepage of akali https://github.com/winsoft666/akali now. I wonder if this library no longer exists? Or changed to another name?

**Comment by JonLiu1993** [comment]
@winsoft666, Thank you for your confirmation, I have submitted a [PR ](https://github.com/microsoft/vcpkg/pull/30748)in vcpkg to set the akali port to empty.

**Pull request merged**
