### PR TITLE
[vtk|opencv4|openimageio] Switch to Qt6

### PR DESCRIPTION
**Pull request by Neumann-A**
ignores new checklist since this is just a CI test run for now. 

~~https://gitlab.kitware.com/vtk/vtk/-/issues/18792~~ fixed by not using gles in qt

### CODE REVIEW

**Comment by Neumann-A** [comment]
@dg0yt Another gles header/symbol collision here in x64-linux. I thought you fixed it ;)

**Comment by dg0yt** [comment]
> @dg0yt Another gles header/symbol collision here in x64-linux. I thought you fixed it ;)

I resolved some file-level conflicts, but you are facing a problem at symbol level...

**Comment by Neumann-A** [comment]
So Windows is green. Linux/OSX probably also if I can somehow solve the OpenGL issues.

**Comment by Neumann-A** [comment]
Seems to work on windows with qt6:
image

**Comment by Neumann-A** [comment]
@cenit  any objections for moving opencv4 to qt6 ?

**Comment by Neumann-A** [comment]
running paraview client in wsl via an x server on windows also works. Only issue is:
```
neumann@Iluinrandir:~/vcpkg/packages/paraview_x64-linux/tools/paraview$ ./paraview
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-neumann'
qt.core.qobject.connect: QObject::connect: No such slot QTableView::sortByColumn(int)
```
according to qt docs it should by [sortByColumn](https://doc.qt.io/qt-6/qtableview.html#sortByColumn)(int column, Qt::SortOrder order)

**Comment by cenit** [comment]
> @cenit  any objections against moving opencv4 to qt6 ?

absolutely none.
I made the port almost ready because it was good for me since a long time ago!

**Comment by BillyONeal** [comment]
Thanks for the switch! As usual, please submit the upstreamable patches upstream.

**Pull request merged**
