### PR TITLE
Update VMs for June Patch Tuesday

### PR DESCRIPTION
**Pull request by BillyONeal**

### CODE REVIEW

**Comment by BillyONeal** [comment]
Full rebuild running: https://dev.azure.com/vcpkg/public/_build/results?buildId=73749&view=results

**Comment by BillyONeal** [comment]
Reran another full rebuild due to the opengl crash on arm64: https://dev.azure.com/vcpkg/public/_build/results?buildId=73949&view=results

**Comment by JackBoosY** [comment]
Seems like our pipeline stucked?

**Comment by BillyONeal** [comment]
> Seems like our pipeline stucked?

Looks like it did the correct thing to me?

**Pull request merged**
