### PR TITLE
[proj] Update to 9.5.0

### LINKED ISSUE #41583: [PROJ] PROJ should find unofficial-sqlite3 instead of SQlite3 for better multiconfig support
### Is your feature request related to a problem? Please describe.

I am working on a super build for a project that depends on PROJ. I've been struggling to debug a LNK4098 warning reporting that my application, which I am building in release mode, is linking with something that was built in debug mode. I have eventually tracked this issue down to PROJ. When running CMake with CMAKE_FIND_DEBUG_MODE, I realized that when PROJ is installed with VCPKG the resulting `proj-config.cmake` script calls `find_dependency(SQLite3)`, this then gets picked up by `cmake-3.29/Modules/FindSQLite3.cmake`. That's a problem because the default FindSQLite3 module searches with a `find_library` command and the debug and release versions of the library share the same name.

### Proposed solution

A patch should be added to change the find_package call of SQLite3 to unofficial-sqlite3 and update the corresponding imported targets.

### Describe alternatives you've considered

Another option would be to set CMAKE_FIND_PACKAGE_PREFER_CONFIG, but this can't be done on a package by package basis.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dg0yt**
Restore use of unofficial-sqlite3 for multi-config usage. Fixes https://github.com/microsoft/vcpkg/issues/41583.

### CODE REVIEW

**Comment by BillyONeal** [comment]
Rerunning due to network mistake

**Review by LilyWangLL — APPROVED** [review]

**Comment by dg0yt** [comment]
Waiting for info:reviewed.

**Comment by BillyONeal** [comment]
Thanks for the update!

**Pull request merged**
