### PR TITLE
[rttr] Disable -Werror in order to support android

### LINKED ISSUE #37123: [rttr] Build error on x64-android
### Operating system

 x64-windows

### Compiler

Clang 14.0.06

### Steps to reproduce the behavior

```Shell
vcpkg install rttr:arm64-android
```

### Failure logs

Computing installation plan...
The following packages will be built and installed:
    rttr[core]:arm64-android -> 0.9.6+20210811
Detecting compiler hash for triplet arm64-android...
-- Automatically setting HTTP(S)_PROXY environment variables to "127.0.0.1:7890".
Restored 0 package(s) from C:\Users\Lenovo\AppData\Local\vcpkg\archives in 315 us. Use --debug to see more details.
Installing 1/1 rttr:arm64-android...
Building rttr[core]:arm64-android...
-- Using cached rttrorg-rttr-7edbd580cfad509a3253c733e70144e36f02ecd4.tar.gz.
-- Cleaning sources at D:/vcpkg/buildtrees/rttr/src/e36f02ecd4-afbbb37f66.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/rttrorg-rttr-7edbd580cfad509a3253c733e70144e36f02ecd4.tar.gz
-- Applying patch fix-directory-output.patch
-- Applying patch Fix-depends.patch
-- Applying patch remove-owner-read-perms.patch
-- Applying patch disable-unsupport-header.patch
-- Using source at D:/vcpkg/buildtrees/rttr/src/e36f02ecd4-afbbb37f66.clean
-- Configuring arm64-android
-- Building arm64-android-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j17
    Working Directory: D:/vcpkg/buildtrees/rttr/arm64-android-dbg
    See logs for more information:
      D:\vcpkg\buildtrees\rttr\install-arm64-android-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/rttr/portfile.cmake:42 (vcpkg_cmake_install)
  scripts/ports.cmake:170 (include)

[install-arm64-android-dbg-out.log](https://github.com/microsoft/vcpkg/files/14481434/install-arm64-android-dbg-out.log)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by FrankXie05**
Fix https://github.com/microsoft/vcpkg/issues/37123

Note:
    In C++, if two values of different types are operated on or compared, the compiler attempts an implicit type conversion to convert one value to the type of the other. This implicit type conversion may result in loss of precision, overflow, or incorrect results。
    Now change to the result of explicit conversion for android.
    
Upstream PR: https://github.com/rttrorg/rttr/pull/371

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [ ] ~~SHA512s are updated for each updated download.~~
- [x] The "supports" clause reflects platforms that may be fixed by this new version.
- [x] Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.
- [ ] Any patches that are no longer applied are deleted from the port's directory.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by dg0yt** [comment]
https://github.com/rttrorg/rttr/pull/371#issuecomment-1993739239

**Comment by FrankXie05** [comment]
Regarding the precision of the values, they are well below the precision range of float(-2^128 ~ +2^128).
```
(aka 'int') to 'float' changes value from -2147483647 to -2147483648
(aka 'long') to 'float' changes value from 9223372036854775807 to 9223372036854775808
```

**Comment by dg0yt** [comment]
> Regarding the precision of the values, they are well below the precision range of float(-2^128 ~ +2^128).
> 
> ```
> (aka 'int') to 'float' changes value from -2147483647 to -2147483648
> (aka 'long') to 'float' changes value from 9223372036854775807 to 9223372036854775808
> ```

Precision is not min/max value. Precision is number of signifcant bits. It is relevant for floating point type which use part of the bits for the exponent. 
https://en.wikipedia.org/wiki/Floating-point_arithmetic
So there can be integer numbers which are within the min/max range of a given floating point type but cannot be represented exactly.

In addition, the ranges of int, float, and log are not defined exactly. Only the minimum range can be assumed for each type.

Now the patched function is only to indicate if a value is too small or too large to fit into the floating point type. Maybe the patch is acceptable because precision is not an issue here. But correct transition between fp and integer can be tricky, and so it should be reviewed carefully.

**Comment by Cheney-W** [comment]
Add `reviewed` tag to request further review from Billy.

**Comment by BillyONeal** [comment]
I'm not convinced that this patch is correct in the face of all types F and T. In particular, it's not necessarily true that `numeric_limits<T>::max` is representable in `F`. The correctness of this depends on the intended interface of the function in question and how it is used.

I do not think it is appropriate to apply a change like this without upstream having made the change first. It is not clearly only build system related or similarly related to our core competencies, so I don't think even a waiting period is appropriate.

If the actual build failure is due to some sort of warning that fires on Android, turning off the warning would be OK.

**Review by Cheney-W — APPROVED** [review]

**Comment by BillyONeal** [comment]
Awesome, thanks!

**Pull request merged**
