### PR TITLE
[vcpkg] rename hash to digest

### PR DESCRIPTION
**Pull request by strega-nil**
in preparation for adding ["types don't know #"] style hashing code.

Note that `digest` is used in other places to refer to this style of hashing, when it's cryptographic hashing and not hashing objects for hash tables, specifically in [Rust's Ring library] and [Java's Apache Common Codec library]; the "message digest" is the end result of a cryptographic hashing algorithm. Alternatively, we could call it "cryptographic hashing", like C#, but "digest" is much shorter.

["types don't know #"]: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n3980.html
[Rust's Ring library]: https://briansmith.org/rustdoc/ring/digest/struct.Digest.html
[Java's Apache Common Codec library]: http://commons.apache.org/proper/commons-codec/apidocs/index.html

### CODE REVIEW

**Review by vicroms — APPROVED** [review]

**Comment by ras0219** [comment]
What about MD5?

**Comment by strega-nil** [comment]
@ras0219 hashing objects, for things like unordered_map

**Comment by ras0219** [comment]
I'd like to more clearly know the overall plan before merging this instead of seeing it in tiny steps; for example, what precisely do we need to fix w.r.t. `std::hash<>` and why shouldn't these share the same name -- the tasks are exactly the same (turn arbitrary object into fixed length integer) with different algorithms and different "guarantees".

**Comment by strega-nil** [comment]
@ras0219 yeah, fair enough; I'll write up a mini write-up that explains where I am about this, and then start doing these PRs.

**Comment by BillyONeal** [comment]
I believe using "digest" in this fashion is a relic of when MD5 "message digest 5" was the state of the art and "hash" is the modern description of this thing. (e.g. in the replacement SHA "secure hash algorithm")

But certainly not an over my dead body thing.

**Comment by vicroms** [comment]
Replay in vcpkg-tool repo.

**Pull request closed without merging**
