### PR TITLE
[Lua 5.1] Added old version of lua

### LINKED ISSUE #7713: [lua] 5.1 version
****

**Is your feature request related to a problem? Please describe.**
Need Lua 5.1 to build Mudlet (https://github.com/mudlet/mudlet), which has an enormous ecosystem of user-made scripts already made with that specific version.

**Proposed solution**
Add Lua 5.1 as an alternative version for vcpkg.

**Additional context**
I think there would be a fair bit of other Lua projects that use Lua 5.1.

### PR DESCRIPTION
**Pull request by mathisloge**
**Describe the pull request**

So I don't really know if this is the correct way of adding a older version of a already newer library. But i thought i will give it a try.

- What does your PR fix? Fixes #7713

- Which triplets are supported/not supported? Have you updated the CI baseline? yes

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?yes

### CODE REVIEW

**Comment by mathisloge** [comment]
pinging @vadi2 as he requested this and might have time to test this as soon as it is ready to use.

**Comment by mathisloge** [comment]
waiting for the ci run and then pushing the commits to go back to version 5.4.3

**Comment by vadi2** [comment]
Nice, how would I try this in the project?

**Comment by mathisloge** [comment]
> Nice, how would I try this in the project?

currently you could clone the https://github.com/mathisloge/vcpkg with the branch lua 5.1. 
But after i push the commits to go back to 5.4.3 you need to follow https://github.com/microsoft/vcpkg/blob/master/docs/users/versioning.md to freeze the version to 5.1

**Comment by vicroms** [comment]
Per policy we don't allow downgrading of libraries. The correct way to accomplish this would be to create your own custom Git registry and push the needed versions to that registry.

You can read our [registries blog post that includes an in-depth tutorial](https://devblogs.microsoft.com/cppblog/registries-bring-your-own-libraries-to-vcpkg/). If you need more help setting this up for your project/team please feel free to open a new discussion or contact us by email or Slack/Discord.

**Comment by mathisloge** [comment]
So I thought if I'm pushing it back to 5.4.3 the version feature should allow projects to consume the 5.1 version. But since lua started (in vcpkg) with version 5.4.3 only version beginning with this version are supported in the future?

All older versions have to live in a slcu) custom registry?

Thanks for clarifying.

**Comment by vicroms** [comment]
@mathisloge 

That's correct. Our current stance is to have missing versions be provided by custom registries; we hope that a federated environment of high-quality custom registries is born at some point in time that can address the shortcomings of the main registry. We also may change our stance on this in the future.

**Comment by mathisloge** [comment]
@vadi2 Have created a custom registry as @vicroms said with lua versions 5.1, 5.2 and 5.3 since 5.4 and onward will be supported from vcpkg main repo 
https://github.com/mathisloge/vcpkg-registry

**Comment by mathisloge** [comment]
@vicroms  should maybe also close #7713

**Pull request closed without merging**
