### PR TITLE
Added support for VS2013 build chain tools.

### PR DESCRIPTION
**Pull request by martin-s**
This patch will enable to use the build tools from Visual Studio 2013. Msvc120 libraries have to be skipped during post-build verification.
Source code could be more harmonized to prevent code duplication which is now more obvious.

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks for the PR! This is ready for merge once you've signed the CLA!

I reverted the changes to the powershell script -- that's only used to build the `vcpkg.exe` tool itself, which certainly won't build with VS2013. Then, I've made some changes in the toolset selection to avoid using VS2013 as a VS2015/17 fallback -- the reason for our current behavior is that VS2015 and VS2017 are binary compatible, so it's fine to mix them and everything will keep working if you install a newer version later.

However, in the case of VS2013, if we automatically fell back and built v120 binaries, everything would break if you install a newer VS version. These changes make it so the default triplets will _not_ pick up v120, but you can create another triplet that explicitly says `set(VCPKG_PLATFORM_TOOLSET v120)`, which will always get VS2013.

**Comment by martin-s** [comment]
I will look int the license issue end of the week. Beforehand, I have no objections if you use any code in this PR.
Regarding the other issues, I mostly agree on the comments:
- I use v120 triplets myself, so this is ok.
- My changes to the powershell script are probably out of scope. I built vcpkg with VS2015 or newer, too. Hence, no support for VS2013 on powershell level is surely needed.
- I leave the fallback mechanism to you. As VS2013 support is not official, my patch wasn't intended to change any default behaviour of vcpkg. :-)

**Comment by martin-s** [comment]
From my point of view, this RR is ready for merging. Any objections?

**Comment by ras0219-msft** [comment]
Thanks!

**Pull request merged**
