### PR TITLE
[libkeyfinder] Remove feature test

### PR DESCRIPTION
**Pull request by autoantwort**
Was not compatible with catch3

### CODE REVIEW

**Comment by MonicaLiu0311** [comment]
An error occurred while testing the feature:
```
PS E:\libkeyfinder> ./vcpkg install libkeyfinder[*]:x64-windows
...
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: E:/libkeyfinder/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: E:/libkeyfinder/buildtrees/libkeyfinder/x64-windows-dbg
    See logs for more information:
      E:\libkeyfinder\buildtrees\libkeyfinder\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/libkeyfinder/portfile.cmake:21 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)
```

**E:\libkeyfinder\buildtrees\libkeyfinder\install-x64-windows-dbg-out.log:**
```
[36/37] cmd.exe /C "cd . && E:\libkeyfinder\downloads\tools\cmake-3.25.1-windows\cmake-3.25.1-windows-i386\bin\cmake.exe -E vs_link_exe --intdir=tests\CMakeFiles\keyfinder-tests.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MIB055~1\2022\ENTERP~1\VC\Tools\MSVC\1435~1.322\bin\Hostx64\x64\link.exe  tests\CMakeFiles\keyfinder-tests.dir\main.cpp.obj tests\CMakeFiles\keyfinder-tests.dir\_testhelpers.cpp.obj tests\CMakeFiles\keyfinder-tests.dir\audiodatatest.cpp.obj tests\CMakeFiles\keyfinder-tests.dir\binodetest.cpp.obj tests\CMakeFiles\keyfinder-tests.dir\chromagramtest.cpp.obj tests\CMakeFiles\keyfinder-tests.dir\chromatransformtest.cpp.obj tests\CMakeFiles\keyfinder-tests.dir\chromatransformfactorytest.cpp.obj tests\CMakeFiles\keyfinder-tests.dir\constantstest.cpp.obj tests\CMakeFiles\keyfinder-tests.dir\downsamplershortcuttest.cpp.obj tests\CMakeFiles\keyfinder-tests.dir\fftadaptertest.cpp.obj tests\CMakeFiles\keyfinder-tests.dir\keyclassifiertest.cpp.obj tests\CMakeFiles\keyfinder-tests.dir\keyfindertest.cpp.obj tests\CMakeFiles\keyfinder-tests.dir\lowpassfiltertest.cpp.obj tests\CMakeFiles\keyfinder-tests.dir\lowpassfilterfactorytest.cpp.obj tests\CMakeFiles\keyfinder-tests.dir\spectrumanalysertest.cpp.obj tests\CMakeFiles\keyfinder-tests.dir\temporalwindowfactorytest.cpp.obj tests\CMakeFiles\keyfinder-tests.dir\toneprofilestest.cpp.obj tests\CMakeFiles\keyfinder-tests.dir\windowfunctiontest.cpp.obj tests\CMakeFiles\keyfinder-tests.dir\workspacetest.cpp.obj  /out:tests\keyfinder-tests.exe /implib:tests\keyfinder-tests.lib /pdb:tests\keyfinder-tests.pdb /version:0.0 /machine:x64 /nologo    /debug /INCREMENTAL /subsystem:console  keyfinder.lib  E:\libkeyfinder\installed\x64-windows\debug\lib\manual-link\Catch2Maind.lib  E:\libkeyfinder\installed\x64-windows\debug\lib\fftw3.lib  E:\libkeyfinder\installed\x64-windows\debug\lib\Catch2d.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cmd.exe /C "cd /D E:\libkeyfinder\buildtrees\libkeyfinder\x64-windows-dbg\tests && E:\libkeyfinder\downloads\tools\cmake-3.25.1-windows\cmake-3.25.1-windows-i386\bin\cmake.exe -D TEST_TARGET=keyfinder-tests -D TEST_EXECUTABLE=E:/libkeyfinder/buildtrees/libkeyfinder/x64-windows-dbg/tests/keyfinder-tests.exe -D TEST_EXECUTOR= -D TEST_WORKING_DIR=E:/libkeyfinder/buildtrees/libkeyfinder/x64-windows-dbg/tests -D TEST_SPEC= -D TEST_EXTRA_ARGS= -D TEST_PROPERTIES= -D TEST_PREFIX= -D TEST_SUFFIX= -D TEST_LIST=keyfinder-tests_TESTS -D TEST_REPORTER= -D TEST_OUTPUT_DIR= -D TEST_OUTPUT_PREFIX= -D TEST_OUTPUT_SUFFIX= -D TEST_DL_PATHS= -D CTEST_FILE=E:/libkeyfinder/buildtrees/libkeyfinder/x64-windows-dbg/tests/keyfinder-tests_tests-b12d07c.cmake -P E:/libkeyfinder/installed/x64-windows/share/Catch2/CatchAddTests.cmake""
FAILED: tests/keyfinder-tests.exe tests/keyfinder-tests_tests-b12d07c.cmake E:/libkeyfinder/buildtrees/libkeyfinder/x64-windows-dbg/tests/keyfinder-tests_tests-b12d07c.cmake 
cmd.exe /C "cd . && E:\libkeyfinder\downloads\tools\cmake-3.25.1-windows\cmake-3.25.1-windows-i386\bin\cmake.exe -E vs_link_exe --intdir=tests\CMakeFiles\keyfinder-tests.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MIB055~1\2022\ENTERP~1\VC\Tools\MSVC\1435~1.322\bin\Hostx64\x64\link.exe  tests\CMakeFiles\keyfinder-tests.dir\main.cpp.obj tests\CMakeFiles\keyfinder-tests.dir\_testhelpers.cpp.obj tests\CMakeFiles\keyfinder-tests.dir\audiodatatest.cpp.obj tests\CMakeFiles\keyfinder-tests.dir\binodetest.cpp.obj tests\CMakeFiles\keyfinder-tests.dir\chromagramtest.cpp.obj tests\CMakeFiles\keyfinder-tests.dir\chromatransformtest.cpp.obj tests\CMakeFiles\keyfinder-tests.dir\chromatransformfactorytest.cpp.obj tests\CMakeFiles\keyfinder-tests.dir\constantstest.cpp.obj tests\CMakeFiles\keyfinder-tests.dir\downsamplershortcuttest.cpp.obj tests\CMakeFiles\keyfinder-tests.dir\fftadaptertest.cpp.obj tests\CMakeFiles\keyfinder-tests.dir\keyclassifiertest.cpp.obj tests\CMakeFiles\keyfinder-tests.dir\keyfindertest.cpp.obj tests\CMakeFiles\keyfinder-tests.dir\lowpassfiltertest.cpp.obj tests\CMakeFiles\keyfinder-tests.dir\lowpassfilterfactorytest.cpp.obj tests\CMakeFiles\keyfinder-tests.dir\spectrumanalysertest.cpp.obj tests\CMakeFiles\keyfinder-tests.dir\temporalwindowfactorytest.cpp.obj tests\CMakeFiles\keyfinder-tests.dir\toneprofilestest.cpp.obj tests\CMakeFiles\keyfinder-tests.dir\windowfunctiontest.cpp.obj tests\CMakeFiles\keyfinder-tests.dir\workspacetest.cpp.obj  /out:tests\keyfinder-tests.exe /implib:tests\keyfinder-tests.lib /pdb:tests\keyfinder-tests.pdb /version:0.0 /machine:x64 /nologo    /debug /INCREMENTAL /subsystem:console  keyfinder.lib  E:\libkeyfinder\installed\x64-windows\debug\lib\manual-link\Catch2Maind.lib  E:\libkeyfinder\installed\x64-windows\debug\lib\fftw3.lib  E:\libkeyfinder\installed\x64-windows\debug\lib\Catch2d.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cmd.exe /C "cd /D E:\libkeyfinder\buildtrees\libkeyfinder\x64-windows-dbg\tests && E:\libkeyfinder\downloads\tools\cmake-3.25.1-windows\cmake-3.25.1-windows-i386\bin\cmake.exe -D TEST_TARGET=keyfinder-tests -D TEST_EXECUTABLE=E:/libkeyfinder/buildtrees/libkeyfinder/x64-windows-dbg/tests/keyfinder-tests.exe -D TEST_EXECUTOR= -D TEST_WORKING_DIR=E:/libkeyfinder/buildtrees/libkeyfinder/x64-windows-dbg/tests -D TEST_SPEC= -D TEST_EXTRA_ARGS= -D TEST_PROPERTIES= -D TEST_PREFIX= -D TEST_SUFFIX= -D TEST_LIST=keyfinder-tests_TESTS -D TEST_REPORTER= -D TEST_OUTPUT_DIR= -D TEST_OUTPUT_PREFIX= -D TEST_OUTPUT_SUFFIX= -D TEST_DL_PATHS= -D CTEST_FILE=E:/libkeyfinder/buildtrees/libkeyfinder/x64-windows-dbg/tests/keyfinder-tests_tests-b12d07c.cmake -P E:/libkeyfinder/installed/x64-windows/share/Catch2/CatchAddTests.cmake""
CMake Error at E:/libkeyfinder/installed/x64-windows/share/Catch2/CatchAddTests.cmake:60 (message):
  Error running test executable
  'E:/libkeyfinder/buildtrees/libkeyfinder/x64-windows-dbg/tests/keyfinder-tests.exe':
    Result: Exit code 0xc0000135
    Output: 
ninja: build stopped: subcommand failed.
```

**Comment by autoantwort** [comment]
Maybe we should simply remove that feature completely

**Comment by MonicaLiu0311** [comment]
> Maybe we should simply remove that feature completely

Is there any progress?

**Comment by MonicaLiu0311** [comment]
CI test failed, the log is as follows:
```
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: D:/buildtrees/libkeyfinder/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\buildtrees\libkeyfinder\config-x64-windows-dbg-CMakeCache.txt.log
      D:\buildtrees\libkeyfinder\config-x64-windows-rel-CMakeCache.txt.log
      D:\buildtrees\libkeyfinder\config-x64-windows-out.log
```

**D:\buildtrees\libkeyfinder\config-x64-windows-out.log**
```
-- Found FFTW3: D:/installed/x64-windows/debug/lib/fftw3.lib  
-- Could NOT find Catch2 (missing: Catch2_DIR)
-- Fetching Catch2 from GitHub
CMake Error at tests/CMakeLists.txt:35 (include):
  include could not find requested file:

    Catch

CMake Error at tests/CMakeLists.txt:36 (catch_discover_tests):
  Unknown CMake command "catch_discover_tests".
```

Please get detailed [failure logs here](https://dev.azure.com/vcpkg/c1ee48cb-0df2-4ab3-8384-b1df5a79fe53/_apis/build/builds/87979/artifacts?artifactName=failure%20logs%20for%20x64-windows&api-version=7.0&%24format=zip).

**Review by MonicaLiu0311 — APPROVED** [review]

**Pull request merged**
