### PR TITLE
[fluidsynth/redis-plus-plus] Update to the latest released version

### LINKED ISSUE #12968: fluidsynth build failure
Error: Building package fluidsynth:x64-linux failed with: BUILD_FAILED

  Package: fluidsynth:x64-linux
  Vcpkg version: 2020.06.15-unknownhash

(My suggestion:  .exe  extension is not used on the unix ...)

**To Reproduce**
`./vcpkg install fluidsynth`

kamil@unuk:~/vcpkg$ ./vcpkg install fluidsynth
Computing installation plan...
The following packages will be built and installed:
    fluidsynth[core]:x64-linux
Detecting compiler hash for triplet x64-linux...
Starting package 1/1: fluidsynth:x64-linux
Building package fluidsynth[core]:x64-linux...
Could not locate cached archive: /home/kamil/.cache/vcpkg/archives/1b/1bf1ce828f73bf656dd45a780447cf00b2c62142.zip
-- Using cached /home/kamil/vcpkg/downloads/FluidSynth-fluidsynth-37c9ae2bf431a764032f023b3b2c0c0b86b7c272.tar.gz
-- Cleaning sources at /home/kamil/vcpkg/buildtrees/fluidsynth/src/0b86b7c272-b21350e92b.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/kamil/vcpkg/downloads/FluidSynth-fluidsynth-37c9ae2bf431a764032f023b3b2c0c0b86b7c272.tar.gz
-- Applying patch force-x86-gentables.patch
-- Using source at /home/kamil/vcpkg/buildtrees/fluidsynth/src/0b86b7c272-b21350e92b.clean
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
CMake Error at ports/fluidsynth/portfile.cmake:19 (file):
  file COPY cannot find
  "/home/kamil/vcpkg/packages/fluidsynth_x64-linux/bin/fluidsynth.exe": No
  such file or directory.
Call Stack (most recent call first):
  scripts/ports.cmake:79 (include)

Error: Building package fluidsynth:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: fluidsynth:x64-linux
  Vcpkg version: 2020.06.15-unknownhash

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

### PR DESCRIPTION
**Pull request by NancyLi1013**
**Describe the pull request**

- What does your PR fix? Fixes #12968

- Update `fluidsynth` to latest version 2.1.4.
- Use `vcpkg_copy_tools` to fix the tools cannot be found on unix.

Also update `redis-plus-plus` to latest version 1.1.2 and fix typo error.

Note: No features need to test.

### CODE REVIEW

**Comment by BillyONeal** [comment]
This looks good to me, any reason it's still draft?

**Comment by NancyLi1013** [comment]
Just to wait for CI test results. It seems work fine now.
So I convert it to open. Thanks for your reminder @BillyONeal

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
