### PR TITLE
curl support http2, use nghttp2

### PR DESCRIPTION
**Pull request by fcharlie**
Nghttp has been port to vcpkg, we can enable cURL HTTP2 support.

### CODE REVIEW

**Comment by fcharlie** [comment]
TO Enable HTTP2: `curl_easy_setopt(curl, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_2_0);`

image

**Comment by atkawa7** [comment]
@fcharlie Adding nghttp2 causes curl to fail in static mode

**Comment by fcharlie** [comment]
@alexkaratarakis

**Comment by fcharlie** [comment]
When need support HTTP2

Linux: 
```
-DCURL_CA_BUNDLE="/etc/ssl/certs/ca-certificates.crt"
```

**Comment by alexkaratarakis** [comment]
Looks good to me. Thanks!

**Comment by fcharlie** [comment]
Good News @alexkaratarakis  Thanks.

**Pull request merged**
