### PR TITLE
[quill] Update to 4.1.0

### PR DESCRIPTION
**Pull request by RT2Code**
Update quill port from 3.9.0 to 4.1.0 : 
https://github.com/odygrd/quill/releases/tag/v4.0.1
https://github.com/odygrd/quill/releases/tag/v4.0.0

This version brings major changes to the library. It is now header only. The ability to easily devendor fmt was removed, but the one bundled with quill is now encapsulated behind a distinct namespace, so it should not conflict with libraries using the vcpkg fmt port.

- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] SHA512s are updated for each updated download.
- [ ] ~~The "supports" clause reflects platforms that may be fixed by this new version.~~
- [ ] ~~Any fixed [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt) entries are removed from that file.~~
- [ ] ~~Any patches that are no longer applied are deleted from the port's directory.~~
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Comment by MonicaLiu0311** [comment]
Records: Became a `Header-only` library in the new version [4.0.0](https://github.com/odygrd/quill/releases/tag/v4.0.0).

* Header-Only library
The library is now header-only. This change simplifies exporting the library as a C++ module in the future. See
[here](https://github.com/odygrd/quill/blob/master/examples/recommended_usage/recommended_usage.cpp) on how to build a wrapper static library which includes the backend and will minimise the compile times.

**Comment by MonicaLiu0311** [comment]
There is a problem with the currently generated `usage`, there is an extra ")"：
image

**Comment by dg0yt** [comment]
> There is a problem with the currently generated `usage`, there is an extra ")"：

Fixed by next vcpkg tool update: https://github.com/microsoft/vcpkg-tool/pull/1403

**Comment by dg0yt** [comment]
It is strange that it is "header-only" now but states that it is "advisable to encapsulate the header-only library into a static library, which you build once and link to your main  application." If so, what is advisable for the vcpkg port?

**Comment by RT2Code** [comment]
I also find it strange that the author tried to improve compilation time and, at the same time, switched to header-only mode; it seems counterproductive. However, he said he did that because he wants to export the library as a C++ module in the future, so maybe it makes sense after all.

Anyway, I think his advice about encapsulating the library is irrelevant for vcpkg because he's not providing the code for that. We would need to write a custom wrapper, and it's out of scope for vcpkg ports to do that. The library builds and works fine without it anyway; it will just compile a little slower, but Quill has never been the bottleneck in that regard in my experience.

**Review by MonicaLiu0311 — APPROVED** [review]

**Pull request merged**
