### PR TITLE
[scnlib] Add new port

### PR DESCRIPTION
**Pull request by SuperWig**
The support for range-v3 doesn't work with the fork vcpkg has so I disabled it.

Edit: Now realising that vcpkg doesn't use the Microsoft fork as indicated by the control file.

### CODE REVIEW

**Comment by SuperWig** [comment]
I'm unfamiliar with UWP but I assume the library doesn't support it?
Should the description include (pre-release) in it?

**Comment by eliaskosunen** [comment]
Thanks for doing this; I don't know vcpkg, so it's good that someone knowledgeable would do this for me.

Couple of points:
 * Version should be `0.1.2`, and the head reference should be updated
 * Homepage should be https://scnlib.dev
 * To disable the ranges target, set `-DSCN_RANGES=OFF` instead of `-DCMAKE_DISABLE_FIND_PACKAGE`

I don't know about the UWP error; that's just a warning on Appveyor on Windows. Maybe do what abseil does:

https://github.com/microsoft/vcpkg/blob/1004b2ea11f67c59f2b3388ac4fb7947d0fa5e87/ports/abseil/portfile.cmake#L3-L5

`WindowsStore` is UWP, right?

**Comment by SuperWig** [comment]
I didn't realise that the logs were accessible. Apparently the UWP build fails because of this
```
visitor.cpp(517): error C4146: unary minus operator applied to unsigned type, result still unsigned
```

And thank you for the library :)

**Pull request merged**
