### PR TITLE
[gmp] correct supports field to run CI for other platforms

### PR DESCRIPTION
**Pull request by Neumann-A**

### CODE REVIEW

**Comment by NancyLi1013** [comment]
This PR is just to test, right? @Neumann-A

**Comment by Neumann-A** [comment]
@NancyLi1013. Not really. The supports field is wrong in gmp and needs fixing. The CI errors is just fallout of the fact that gmp is now actually considered by CI. The errors in mpfr in linux/osx seems to need a VM update but I cannot test what is needed locally.

**Comment by PhoebeHui** [comment]
I will take a look at the CI test failures, @Neumann-A, thanks for fixing this issue!

**Comment by PhoebeHui** [comment]
mpfr:x64-linux: after I installed texinfo package, it passed.
build-x64-linux-dbg-err.log:
```
/mnt/vcpkg-ci/buildtrees/mpfr/src/mpfr-4-8955d4bc66.clean/missing: 81: /mnt/vcpkg-ci/buildtrees/mpfr/src/mpfr-4-8955d4bc66.clean/missing: makeinfo: not found
WARNING: 'makeinfo' is missing on your system.
         You should only need it if you modified a '.texi' file, or
         any other file indirectly affecting the aspect of the manual.
         You might want to install the Texinfo package:
         <http://www.gnu.org/software/texinfo/>
         The spurious makeinfo call might also be the consequence of
         using a buggy 'make' (AIX, DU, IRIX), in which case you might
         want to install GNU make:
         <http://www.gnu.org/software/make/>
make[1]: *** [.././../src/mpfr-4-8955d4bc66.clean/doc/mpfr.info] Error 127
make: *** [all-recursive] Error 1

```

**Review by PhoebeHui — APPROVED** [review]

**Comment by PhoebeHui** [comment]
@ras0219-msft, could you help review and merge this PR?

**Comment by ras0219-msft** [comment]
LGTM, thanks!

**Pull request merged**
