### PR TITLE
Make vcpkg-qmake qt5 compatible

### PR DESCRIPTION
**Pull request by m-kuhn**
Completes support for qt5 of vcpkg-qmake. It was half there (lines 67-73) but not in a working state.

### CODE REVIEW

**Comment by Neumann-A** [comment]
I think the agreement was to disallow Qt5 usage in `vcpkg-qmake` and if you want to use Qt5 instead of Qt6 you would use an overlay for everything which needs to depend on qt

**Comment by Neumann-A** [comment]
See discussion starting at https://github.com/microsoft/vcpkg/pull/22012#issuecomment-1377690282

**Comment by m-kuhn** [comment]
Fine for me too, in this case I'd say the half baked qt5 support should be dropped instead.

**Comment by MonicaLiu0311** [comment]
vcpkg-qmake
-
All features are tested successfully in the following triplet:
```
x86-windows
x64-windows
x64-windows-static
```

**Review by MonicaLiu0311 — APPROVED** [review]

**Comment by BillyONeal** [comment]
> Fine for me too, in this case I'd say the half baked qt5 support should be dropped instead.

@vicroms @ras0219-msft @JavierMatosD @data-queue and I like this direction :)

**Comment by MonicaLiu0311** [comment]
> > Fine for me too, in this case I'd say the half baked qt5 support should be dropped instead.
> 
> @vicroms @ras0219-msft @JavierMatosD @data-queue and I like this direction :)

If there are no other comments, then I will continue to move forward with this PR.

**Comment by m-kuhn** [comment]
For the record, I don't plan to work on this, but I agree it would be good to move forward.

**Comment by MonicaLiu0311** [comment]
@m-kuhn 
Please resolve the conflict, and I will open this PR later.

**Comment by m-kuhn** [comment]
@MonicaLiu0311 I don't think there is much valuable code in here, so rebasing doesn't make sense. The consensus was as far as I understand to get rid of qt5 related code whereas this tried to fix qt5 related code.

**Pull request closed without merging**
