### PR TITLE
[libsoundio] fix macos 12 build

### PR DESCRIPTION
**Pull request by autoantwort**
Workaround for https://github.com/andrewrk/libsoundio/issues/256

### CODE REVIEW

**Comment by Cheney-W** [comment]
Waiting for upstream agreement on this workaround.

**Comment by autoantwort** [comment]
I don't think you need a upstream agreement for ignoring deprecation warnings, this kind of warnings are only hints that you should change your implementation in the future.

**Comment by JackBoosY** [comment]
This is definitely an upstream bug, so we'd better listen to what the upstream has to say first 😄

**Comment by autoantwort** [comment]
Already done in #22314

**Pull request closed without merging**
