### PR TITLE
[python3] Fix pkgconfig for debug Linux builds

### PR DESCRIPTION
**Pull request by mkhon**
**Describe the pull request**

pkgconfig files have incorrect includedir for Linux debug

Also, this change unifies the patching of pkgconfig files with Windows build

- #### What does your PR fix?  

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
all

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
Yes

**If you are still working on the PR, open it as a Draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/**

### CODE REVIEW

**Comment by JackBoosY** [comment]
Needs check the pc files.

**Comment by JackBoosY** [comment]
In _python-3.10.pc_:
```pc
prefix=${pcfiledir}/../..
# See: man pkg-config
exec_prefix=${prefix}/tools/python3
libdir=${prefix}/lib
includedir=${prefix}/include

Name: Python
Description: Build a C extension for Python
Requires:
Version: 3.10
Libs.private: 
Libs:
Cflags: -I"${includedir}/python3.10"
```
`Libs` and `Libs.private` are empty, it seems incorrect.

**Comment by mkhon** [comment]
@JackBoosY why do you think it is incorrect? python3.pc in Linux packages has similar content:

```
# See: man pkg-config
prefix=/usr
exec_prefix=${prefix}
includedir=${prefix}/include

Name: Python
Description: Build a C extension for Python
Requires:
Version: 3.9
Libs.private: -lcrypt -lpthread -ldl  -lutil -lm
Libs:
Cflags: -I${includedir}/python3.9 -I${includedir}/x86_64-linux-gnu/python3.9
```

**Comment by JackBoosY** [comment]
There are 2 pc files installed on Windows:
- python-3.10-embed.pc
```
prefix=${pcfiledir}/../..
# See: man pkg-config
exec_prefix=${prefix}/tools/python3
libdir=${prefix}/lib
includedir=${prefix}/include

Name: Python
Description: Embed Python into an application
Requires:
Version: 3.10
Libs.private: 
Libs: -L"${libdir}" -lpython310
Cflags: -I"${includedir}/python3.10"
```
This is correct.
- python-3.10.pc
```
prefix=${pcfiledir}/../..
# See: man pkg-config
exec_prefix=${prefix}/tools/python3
libdir=${prefix}/lib
includedir=${prefix}/include

Name: Python
Description: Build a C extension for Python
Requires:
Version: 3.10
Libs.private: 
Libs:
Cflags: -I"${includedir}/python3.10"
```
Missing libs here.

**Comment by mkhon** [comment]
> There are 2 pc files installed on Windows:
> 
> * python-3.10-embed.pc
> 
> ```
> prefix=${pcfiledir}/../..
> # See: man pkg-config
> exec_prefix=${prefix}/tools/python3
> libdir=${prefix}/lib
> includedir=${prefix}/include
> 
> Name: Python
> Description: Embed Python into an application
> Requires:
> Version: 3.10
> Libs.private: 
> Libs: -L"${libdir}" -lpython310
> Cflags: -I"${includedir}/python3.10"
> ```
> 
> This is correct.
> 
> * python-3.10.pc
> 
> ```
> prefix=${pcfiledir}/../..
> # See: man pkg-config
> exec_prefix=${prefix}/tools/python3
> libdir=${prefix}/lib
> includedir=${prefix}/include
> 
> Name: Python
> Description: Build a C extension for Python
> Requires:
> Version: 3.10
> Libs.private: 
> Libs:
> Cflags: -I"${includedir}/python3.10"
> ```
> 
> Missing libs here.

@JackBoosY if you look at .pc files installed by stock Python (e.g. in stock Linux packages for any Linux distro) you will notice that libs is empty in python.pc and is there in python-embed.pc

So this is by design. Please also take time to check the links in my previous comment

**Comment by JackBoosY** [comment]
cc @Hoikas for review this PR.

**Comment by Hoikas** [comment]
I'm not familiar with the PC files for Python 😞 , but missing lib files sounds suspicious to me.

**Comment by mkhon** [comment]
@Hoikas please compare with .pc files installed by any Python >= 3.9 on any Linux distro

**Review by JackBoosY — APPROVED** [review]

**Comment by JackBoosY** [comment]
This changes does not related to `LIBS` or `LIBS.private`, so I think it's okay.
Also cc @Neumann-A for review pkgconfig part.

**Review by JackBoosY — APPROVED** [review]

**Comment by ras0219-msft** [comment]
Yep, this looks like the right solution to me. Thanks for the PR!

**Pull request merged**
