### PR TITLE
[many ports] Updates 2019.04.19

### PR DESCRIPTION
**Pull request by ras0219-msft**

### CODE REVIEW

**Comment by PhoebeHui** [comment]
It only has itk and vxl failed here, @Rastaban, I can't reproduce itk and vxl failure locally, could you help have a look?

vxl:  I didn't find the vxl failures logs, I verified it on x86-windows, x64-windows and linux, all build successfully.
itk: it has failures logs that says compile failed on linux, however, i didn't reproduce it locally with gcc 5.4.0 and 7.3.0. they are build successfully.
They has same dependency port libpng changed here, but there is no proof it related to the failures.

The latest failure:
NEW baseline job: 2610544
NEW baseline commitid: e9f1c3831f43c87c484f78a9458f8b0758dc23d5

|x64-windows|master| test |notes
|-----------|------|------|-----
|vxl        |Pass  |Fail  |**Regression**

|x64-windows-static|master| test |notes
|------------------|------|------|-----
|vxl               |Pass  |Fail  |**Regression**

|x64-osx |master| test |notes
|--------|------|------|-----
|gdcm2   |Skip  |Pass  |
|itk     |Pass  |Fail  |**Regression**
|vxl     |Pass  |Fail  |**Regression**
|openjpeg|Fail  |Pass  |

arm64-windows had no regressionsvcpkg 

|x86-windows|master| test |notes
|-----------|------|------|-----
|vxl        |Pass  |Fail  |**Regression** 

|x64-linux|master| test |notes
|---------|------|------|-----
|gdcm2    |Skip  |Pass  |
|itk      |Pass  |Fail  |**Regression**
|vxl      |Pass  |Fail  |**Regression**
|openjpeg |Fail  |Pass  |

**Comment by ras0219-msft** [comment]
The `vxl` failure had this message in build 2606930 x64-linux:
```
Starting package 256/310: vxl:x64-linux
Building package vxl[core]:x64-linux...
Could not locate cached archive: /home/vcpkg/myagent/_work/1/s/archives/79/79efb4f56c93a39c5ad97e05b8e58f1921caddc9.zip
CMake Error at ports/vxl/portfile.cmake:4 (message):
  Can't build VXL with non built-in OpenJpeg in current version.  Please
  remove OpenJpeg, and try install VXL again.
Call Stack (most recent call first):
  scripts/ports.cmake:71 (include)


Error: Building package vxl:x64-linux failed with: BUILD_FAILED
```
and the same for x64-windows:
```
Starting package 323/358: vxl:x64-windows
Building package vxl[core]:x64-windows...
Could not locate cached archive: C:\vsts\_work\2\s\archives\80\8029945bd5a1d7e44721c95100692c3582813739.zip
CMake Error at ports/vxl/portfile.cmake:4 (message):
  Can't build VXL with non built-in OpenJpeg in current version.  Please
  remove OpenJpeg, and try install VXL again.
Call Stack (most recent call first):
  scripts/ports.cmake:71 (include)


Error: Building package vxl:x64-windows failed with: BUILD_FAILED
Elapsed time for package vxl:x64-windows: 1.241 s
```

The `itk:x64-linux` failure should have produced log files.

**Comment by PhoebeHui** [comment]
@ras0219-msft, we still can’t repro ITK failures locally, same OS, gcc and cmake revision: 18.04 + gcc 7.3.0  + cmake with CI test machine, everything build successfully locally, we have no idea about the this.

Checked 'opj_stream_create’ in lib/libitkgdcmopenjp2-5.0.a, not sure if lib/libitkgdcmopenjp2-5.0.a generated correctly in CI test machine.

Failures:
/home/vcpkg/myagent/_work/1/s/buildtrees/itk/ITK/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmJPEG2000Codec.cxx:368: error: undefined reference to 'opj_stream_create'
/home/vcpkg/myagent/_work/1/s/buildtrees/itk/ITK/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmJPEG2000Codec.cxx:374: error: undefined reference to 'opj_stream_set_user_data'
…

**Comment by Rastaban** [comment]
resolved merge conflict with cctz

**Comment by Rastaban** [comment]
itk went from pass->fail and openjpeg went from fail->pass on both Linux and OSX.  I suspect there is a conflict between those ports.  Are you able to reproduce the itk failure if you install openjpeg first?  And conversly, are you able to install openjpeg if itk is installed first?

**Comment by PhoebeHui** [comment]
@Rastaban, thanks for your guideline! 
Install itk first:  itk pass, and openjpeg failed 
Install openjpeg first: openjpeg pass, itk failed. 

They failed due to libopenjp2.pc conflict, Both 2 ports installed libopenjp2.pc, however the failures are different from the failure logs that CI provided.

Failure:
- Performing post-build validation done
Building package itk[core]:x64-linux... done
Installing package itk[core]:x64-linux...
The following files are already installed in /home/vwangli/Phoebe/Robert/vcpkg/installed/x64-linux and are in conflict with itk:x64-linux
Installed by openjpeg:x64-linux
    debug/lib/pkgconfig/libopenjp2.pc
    lib/pkgconfig/libopenjp2.pc

 I will undo openjpeg changes here, and summit a separate PR for it.

**Comment by PhoebeHui** [comment]
@Rastaban, itk still failed on osx, could you help have a look?

**Comment by PhoebeHui** [comment]
All failures resolved here, see related separate PRs [cctz, rocksdb, oepnjpeg/itk].

**Pull request merged**
