### PR TITLE
[bw-tempdir] add new port

### PR DESCRIPTION
**Pull request by bw-hro**
- [x] Changes comply with the [maintainer guide](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/contributing/maintainer-guide.md).
- [x] The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.
- [x] Optional dependencies are resolved in exactly one way. For example, if the component is built with CMake, all `find_package` calls are REQUIRED, are satisfied by `vcpkg.json`'s declared dependencies, or disabled with [CMAKE_DISABLE_FIND_PACKAGE_Xxx](https://cmake.org/cmake/help/latest/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html).
- [x] The versioning scheme in `vcpkg.json` matches what upstream says.
- [x] The license declaration in `vcpkg.json` matches what upstream says.
- [x] The installed as the "copyright" file matches what upstream says.
- [x] The source code of the component installed comes from an authoritative source.
- [x] The generated "usage text" is accurate. See [adding-usage](https://github.com/microsoft/vcpkg-docs/blob/main/vcpkg/examples/adding-usage.md) for context.
- [x] The version database is fixed by rerunning `./vcpkg x-add-version --all` and committing the result.
- [x] Only one version is in the new port's versions file.
- [x] Only one version is added to each modified port's versions file.

### CODE REVIEW

**Review by Mengna-Li — DISMISSED** [review]

**Comment by Mengna-Li** [comment]
Usage tested pass on x64-windows.

**Comment by BillyONeal** [comment]
> The name of the port matches an existing name for this component on https://repology.org/ if possible, and/or is strongly associated with that component on search engines.

As far as I can see, this is not true. Would you be happy if the name of the port was `bw-hro-tempdir`?

**Comment by BillyONeal** [comment]
There is no objection to your library being named `tempdir`. In general, we want names to be of the form `<GithubOrganization>-<Library>` unless the name has conclusively demonstrated that that is what people expect when they say `vcpkg install <Library>`. If, in the future, this becomes the defacto implementation of 'tempdir' for C++ programmers, which we would observe in repology and/or web search results and/or direct customer feedback, we can always create `tempdir` which just points to `bw-hro-tempdir` in the future.

Our concern is that once we have 'given away' a name, we can never change it to something else. That is, `vcpkg install tempdir` would have to remain pointing at your library, even if after a few years you decide to stop working on it and something else becomes the defacto provider of that name.

**Comment by bw-hro** [comment]
Ok, understand. Would you accept "bw-tempdir" as I like it more because it is shorter and resembles the namespace/include path `#include <bw/tempdir/tempdir.hpp>` while still having a creator related prefix?

**Comment by bw-hro** [comment]
Renamed the port from "tempdir" to "bw-tempdir"  hope this is fine.

**Comment by BillyONeal** [comment]
@ras0219-msft @vicroms and I think `bw-tempdir` is reasonable, thank you!

**Pull request merged**
