### PR TITLE
[portmidi] update to 2.0.1; add Linux support

### PR DESCRIPTION
**Pull request by Be-ing**
The original PortMidi author moved it to GitHub and made the first
release in many years. The build system now works without hacks.

### CODE REVIEW

**Comment by Be-ing** [comment]
```
find_package(Threads)
```
is failing on macOS??

https://github.com/PortMidi/portmidi/blob/master/pm_common/CMakeLists.txt#L75

**Comment by Be-ing** [comment]
macOS build is working [on GitHub Actions](https://github.com/PortMidi/portmidi/pull/11) so I think there's a problem with vcpkg's CI?

**Review by JackBoosY — CHANGES_REQUESTED** [review]
Change this line https://github.com/PortMidi/portmidi/blob/master/pm_common/CMakeLists.txt#L56
```cmake
if(APPLE)
```
to
```cmake
if(0)
```
and make a patch.

**Comment by Be-ing** [comment]
Well, that worked... that code makes no sense... https://github.com/PortMidi/portmidi/pull/14

**Comment by Be-ing** [comment]
Libraries should not set `-mmacosx-version-min` on their own. It is up to the downstream user/packager to set [`CMAKE_OSX_DEPLOYMENT_TARGET`](https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html#variable:CMAKE_OSX_DEPLOYMENT_TARGET). The library can check teh value of `CMAKE_OSX_DEPLOYMENT_TARGET` and fail the build with `message(FATAL_ERROR` if it is below a minimum version supported by the library.

Likewise there is no reason for a library to set `-isysroot`. It is up to the user/packager to set [`CMAKE_OSX_SYSROOT`](https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_SYSROOT.html) or the `SDKROOT` environment variable if they're building with a macOS SDK in a nonstandard location.

**Review by JackBoosY — APPROVED** [review]

**Comment by BillyONeal** [comment]
Awesome, thanks for the update!

**Pull request merged**
