### PR TITLE
[loguru] bumped to 2.1.0

### PR DESCRIPTION
**Pull request by BullyWiiPlaza**
- What does your PR fix?
I had trouble successfully using the library before the update since the `loguru.cpp` file was missing which needs to be included once somewhere in the code base (counterintuitively). After that, the `loguru.hpp` can be included as often as one wants.

- Which triplets are supported/not supported? Have you updated the CI baseline?
I only bumped up the version.

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes.

### CODE REVIEW

**Comment by BullyWiiPlaza** [comment]
It's signed.

**Comment by PhoebeHui** [comment]
@BullyWiiPlaza, thanks for the PR!

There is a exist PR https://github.com/microsoft/vcpkg/pull/8682 to upgrade loguru to 2.1.0.

**Comment by BullyWiiPlaza** [comment]
@PhoebeHui Oh, excuse me. I searched for loguru but your `PR` didn't show up before. It's been a while since you submitted your PR so I'm wondering why it takes so long to accept PRs like these? It would be crucial for the package manager to somewhat stay up-to-date.

**Comment by PhoebeHui** [comment]
@BullyWiiPlaza, the CI testing system offline for maintenance previously that blocked that PR for a long time, we will priority to merge that PR!

**Comment by PhoebeHui** [comment]
@BullyWiiPlaza, the PR https://github.com/microsoft/vcpkg/pull/8682 has been merged. Is that ok to close this PR?

**Comment by BullyWiiPlaza** [comment]
@PhoebeHui Yes, thank you.

**Pull request closed without merging**
