### PR TITLE
[sol2] rename port sol to sol2 and fix the full port

### PR DESCRIPTION
**Pull request by Milerius**

### CODE REVIEW

**Comment by Milerius** [comment]
the name of the library is sol2 and not sol, sol is the old library that belongs to someone else.

**Comment by ras0219-msft** [comment]
Thanks for the PR!

I restored upstream's `include/sol/` include directory (in addition to the `include/` directory) to avoid breaking compatibility with projects that might previously have used upstream directly. That said, I completely agree that upstream should _strongly_ consider not doing that :). However, we should follow whatever upstream decides here.

**Comment by Milerius** [comment]
@ras0219-msft 
capture d ecran 2018-06-26 a 20 01 23

You break the port ! :3

**Comment by ThePhD** [comment]
I wanted to transition to `include/sol` for sol3, since it is technically a breaking change.

I'm on board with changing from `sol` to `sol2`, albeit sol2 is supposed to be the direct successor and replacement of the original sol...

**Pull request merged**
