### PR TITLE
[SDL2] Enable hidapi

### LINKED ISSUE #19252: [SDL] enable hidapi
****

**Is your feature request related to a problem? Please describe.**
Since a few versions, SDL uses HIDAPI for some game controller features, most notably access to the gyroscope and accelerometer data. This isn't included currently in vcpkg, so only the buttons and joysticks work.

**Proposed solution**
From [what I can see](https://github.com/libsdl-org/SDL/blob/main/cmake/sdlchecks.cmake#L1146-L1180), SDL uses its own bundled hidapi version, so we should just need to enable the  HIDAPI=ON cmake flag?

I can do the change, but I'm not familiar with vcpkg so some guidance would be welcomed, including testing it works on all platforms.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by Yamakaky**
Status: waiting for fix to https://github.com/libsdl-org/SDL/issues/4602 (probably in SDL 2.0.18).

**Describe the pull request**

Enables building the bundled modified `hidapi` dependency to add support for motion controls (gyro, accelerometer) in compatible game controllers (playstation, Switch, Steam Controller...). It should work on every OS supported by SDL. Only known issue is https://github.com/libsdl-org/SDL/issues/4602 when doing a static link of upstream `hidapi` at the same time.

- #### What does your PR fix?  
  Fixes #19252.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
  all, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
  I am still working on this PR

### CODE REVIEW

**Comment by NancyLi1013** [comment]
Since a known issue is libsdl-org/SDL#4602 when doing a static link of upstream hidapi at the same time. If we enable `hidapi ` in `SDL2`, this problem should also exist.

Also, is it possible to add `hidapi `as a feature and depends on `hidapi` provided by vcpkg?

**Comment by Yamakaky** [comment]
Then maybe enable hidapi as a feature while the bug is being worked on?

We can't use hidapi from vcpkg, SDL uses a modified version. It would require a modification of SDL.

**Comment by NancyLi1013** [comment]
We can wait for the changes from upstream. So I think we can enable `hidapi ` once the problem is fixed by upstream.

**Comment by Yamakaky** [comment]
OK. For info, the merge window for 2.0.16 is closed so this will wait for the next version.

**Comment by NancyLi1013** [comment]
> OK. For info, the merge window for 2.0.16 is closed so this will wait for the next version.

Thanks for your information. You can close this PR temporarily or convert this PR to draft until the next version is released.

**Comment by past-due** [comment]
To double-down on an earlier comment: I think hidapi should be added as a feature to the port - as the existing port does not enable it and some consumers may not require it / want it built.

**Comment by NancyLi1013** [comment]
> To double-down on an earlier comment: I think hidapi should be added as a feature to the port - as the existing port does not enable it and some consumers may not require it / want it built.

Thanks for your suggestion. We will add it as feature in the future. Since currently, there're some problems with this feature on upstream. Please see https://github.com/microsoft/vcpkg/pull/19422#issue-963033209.

**Comment by JackBoosY** [comment]
Since libsdl-org/SDL#4602 was merged, can we continue this PR?

**Comment by JackBoosY** [comment]
Ping for response.

**Comment by Yamakaky** [comment]
Oops, didn't answer. I guess so! I'll check it when I get some time.

**Comment by Yamakaky** [comment]
Should be good, it builds locally on linux. I did the 2.0.18 upgrade which includes the hidapi static link patch, should it be in another PR?

BTW, all the vcpkg patches are in 2.0.18 so I removed them.

**Comment by JackBoosY** [comment]
```
CMake Error at scripts/cmake/vcpkg_replace_string.cmake:12 (file):
  file failed to open for reading (No such file or directory):

    D:/packages/sdl2_x86-windows/debug/lib/pkgconfig/sdl2.pc
Call Stack (most recent call first):
  ports/sdl2/portfile.cmake:91 (vcpkg_replace_string)
  scripts/ports.cmake:142 (include)
```
Does the upstream rename the pc file's intallation path?

**Comment by Yamakaky** [comment]
Hum, I don't know that and I don't have a windows at hand. I'll see if I can reproduce in wine

**Comment by JackBoosY** [comment]
Any progress here?

**Comment by JackBoosY** [comment]
Closing this PR since it seems that no progress is being made. Please reopen if work is still being done.

**Pull request closed without merging**
