### PR TITLE
[python3] Upgrade to Python 3.10.1

### PR DESCRIPTION
**Pull request by dfederm**
Upgrades the python3 port to 3.10.1

- #### What does your PR fix?  
See above.

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?  
No change.

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?  
Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?  
Yes

### CODE REVIEW

**Review by ras0219-msft — APPROVED** [review]

**Review by LilyWangLL — APPROVED** [review]

**Comment by ras0219-msft** [comment]
Thanks!

**Comment by aizuon** [comment]
Isn't the hash updated?

```
[DEBUG] Downloading https://github.com/python/cpython/archive/v3.10.1.tar.gz
Error: Failed to download from mirror set:
File does not have the expected hash:
             url : [ https://github.com/python/cpython/archive/v3.10.1.tar.gz ]
       File path : [ D:\vcpkg\downloads\python-cpython-v3.10.1.tar.gz.16400.part ]
   Expected hash : [ d83e0685c274be09da7833a3c24b7379ae0e43b43c131f11bfaccd5902f6a1c510a3ae67c42471a4281922ead3bd34856608ec47be7dd76ddd734e59906ba03b ]
     Actual hash : [ 23f99b77c7978282d43a6e442811de1d6e8cc9597c6d1143ec65ae986f64805c36a0a033632a4d1a89053a55854904bcf11415d91e2a3b4a5308c4a21de80098 ]```

**Comment by aizuon** [comment]
@ras0219-msft @dfederm @LilyWangLL

**Comment by dfederm** [comment]
Hmm, seems like I missed this but weird why it didn't show up in the PR gate.

I'll fix it when. I'm back at a computer in a few hours unless someone or you beat me to it.

**Pull request merged**
