### PR TITLE
[curl] Update to 7.22.0

### PR DESCRIPTION
**Pull request by kevinlul**
Regular port update https://github.com/curl/curl/releases/tag/curl-7_72_0

No changes to triplet support, basic functionality tested

Add feature schannel as an alias to winssl for compatibility (upstream dropped the "WinSSL" naming altogether)

Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)? Yes

### CODE REVIEW

**Comment by LilyWangL** [comment]
Thanks for your PR. Now curl build failed on target UWP with the following error:
```
     4>LINK : warning LNK4075: ignoring '/INCREMENTAL' due to '/OPT:ICF' specification [D:\buildtrees\curl\x64-uwp-dbg\lib\libcurl.vcxproj]
            Creating library D:/buildtrees/curl/x64-uwp-dbg/lib/Debug/libcurl-d.lib and object D:/buildtrees/curl/x64-uwp-dbg/lib/Debug/libcurl-d.exp
     4>openssl.obj : error LNK2019: unresolved external symbol CertOpenSystemStore referenced in function ossl_connect_step1 [D:\buildtrees\curl\x64-uwp-dbg\lib\libcurl.vcxproj]
     4>D:\buildtrees\curl\x64-uwp-dbg\lib\Debug\libcurl-d.dll : fatal error LNK1120: 1 unresolved externals [D:\buildtrees\curl\x64-uwp-dbg\lib\libcurl.vcxproj]
```

**Comment by JackBoosY** [comment]
```
Minimum supported client | Windows XP [desktop apps only]
Minimum supported server | Windows Server 2003 [desktop apps only]
Target Platform | Windows
Header | wincrypt.h
Library | Crypt32.lib
DLL | Crypt32.dll
```

**Comment by kevinlul** [comment]
On my end, that page says both desktop and UWP are supported 🤔 

image

**Comment by JackBoosY** [comment]
https://docs.microsoft.com/en-us/windows/win32/api/wincrypt/nf-wincrypt-certopensystemstorea

**Comment by kevinlul** [comment]
I think this is patchable because the [segment in question](https://github.com/curl/curl/blame/fbe07c6829ba8c5793c84c2856526e19e9029ab9/lib/vtls/openssl.c#L2837) is already wrapped in a `USE_WIN32_CRYPTO` define. However, even before it was calling `CertOpenSystemStoreA`...

**Comment by JackBoosY** [comment]
@kevinlul Do you know which feature or its core caused this problem?

**Comment by kevinlul** [comment]
openssl in this case, though I just discovered that core also fails with these missing symbols from `md4.c`, `md5.c`, `sha256.c`
```
CryptAcquireContext
CryptCreateHash
CryptHashData
CryptGetHashParam
CryptDestroyHash
```

**Comment by JackBoosY** [comment]
I think we need to ensure that we can successfully build on all triplets. So, please remove the broken default features on uwp.

**Comment by kevinlul** [comment]
I think I found the problem, though this CMake logic hasn't changed between 7.71.1 and 7.72.0.

**Comment by kevinlul** [comment]
Sorry, left a typo in.

**Review by JackBoosY — APPROVED** [review]

**Comment by BillyONeal** [comment]
Manually checked on x86-windows:
* `curl[core]`
* `curl[core,tool]`
* `curl[core,non-http]`
* `curl[core,http2]`
* `curl[core,ssh]`
* `curl[core,openssl]`
* `curl[core,schannel]`
* `curl[core,mbedtls]`
* `curl[core,sectransp]` (failed because not supported on non-apple platforms)
* `curl[core,c-ares]`
* `curl[core,sspi]`
* `curl[core,brotli]`
* `curl[core,brotli,tool,non-http,http2,ssh,schannel,c-ares,sspi]`

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
