### PR TITLE
Shiva sfml port

### PR DESCRIPTION
**Pull request by Milerius**

### CODE REVIEW

**Comment by ras0219-msft** [comment]
Thanks!

**Comment by Milerius** [comment]
@ras0219-msft Also Robert i want to know your opinion on this pull request, this is a good way to import modules automatically you think ? i mean the `shiva-sfml` portfile.cmake

**Comment by ras0219-msft** [comment]
I think this line is highly suspicious: https://github.com/Microsoft/vcpkg/pull/4011/files#diff-84a3d373c40c330f16e3d9de770d2b8bR21. Did you really mean to search inside the *source code*?

Otherwise, I don't exactly see what you mean by import modules automatically :(

**Comment by Milerius** [comment]
@ras0219-msft It's because on Linux/OSX plugins are ".so" ".dylib", i manually import it into the lib directory since VCPKG didn't do that for me. After the build of shiva-sfml i got in "bin/systems" directory, 3 dynamic library which doesn't have to be linked since they are DLL, but imported into a binary directory for latter loading

**Comment by ras0219-msft** [comment]
Thanks for the link :)

The `import_plugin` macro seems serviceable, however for more complicated projects with nested `add_subdirectory()`s or even nested `project()`s I think this will break down. The lowest-cost fix for that (afaict) would be to provide the user a macro like `shiva_deploy_plugins(<directory>)` that they can call in their cmake file which will deploy the plugins to the target directory.

**Comment by Milerius** [comment]
@ras0219-msft Oh i see, thank's for the advice, also there is a VCPKG_VARIABLE to access $VCPKG_ROOT/installed/triplet/lib directory ?

**Comment by ras0219-msft** [comment]
From inside of your `shiva-config.cmake` file, no. I recommend using a relative path lookup:
```
file(GLOB RELEASE_PLUGINS ${CMAKE_CURRENT_LIST_DIR}/../../lib/*) #release
file(GLOB DEBUG_PLUGINS ${CMAKE_CURRENT_LIST_DIR}/../../debug/lib/*) #debug
```

Unfortunately, I still don't quite understand the reason for looking in the `${SOURCE_PATH}` for binaries -- as far as I can tell from your repo and cmake files, you should not have any files in that directory.

Are you sure you did not mean something like `file(GLOB PLUGINS "${CURRENT_PACKAGES_DIR}/bin/systems/*")`?

**Comment by Milerius** [comment]
@ras0219-msft It's appear that when i build shiva-sfml, plugins are generated in ${SOURCE_PATH}/bin/systems -> probably because of https://github.com/Milerius/shiva/blob/master/cmake/module.cmake#L48 , let me know ;)

**Pull request merged**
