### PR TITLE
[mysql-connector-cpp] update to 8.0.30

### PR DESCRIPTION
**Pull request by Xiaobin0860**
**Describe the pull request**

- #### What does your PR fix?
  No, upgrade `mysql-connector-cpp` to 8.0.30

- #### Which triplets are supported/not supported? Have you updated the [CI baseline](https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt)?
  `!uwp & !(windows & (arm | arm64))`, No

- #### Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
  Yes

- #### If you have added/updated a port: Have you run `./vcpkg x-add-version --all` and committed the result?
  Yes

### CODE REVIEW

**Comment by FrankXie05** [comment]
@Xiaobin0860 Is this PR ready for review? I am going to review this PR tomorrow.

**Comment by Xiaobin0860** [comment]
Yes

**Review by FrankXie05 — APPROVED** [review]

**Comment by FrankXie05** [comment]
The new usage has been successfully tested locally.
````
mysql-connector-cpp provides CMake targets: 
    # this is heuristically generated, and may not be correct
    find_package(unofficial-mysql-connector-cpp CONFIG REQUIRED)
    target_link_libraries(main PRIVATE connector) 
````

**Comment by JavierMatosD** [comment]
Thanks!

**Comment by dg0yt** [comment]
> The new usage has been successfully tested locally.
> 
> ```
> mysql-connector-cpp provides CMake targets: 
>     # this is heuristically generated, and may not be correct
>     find_package(unofficial-mysql-connector-cpp CONFIG REQUIRED)
>     target_link_libraries(main PRIVATE connector) 
> ```

The imported target `connector` lacks a proper namespace (`unofficial::mysql-connector-cpp::`).

**Comment by FrankXie05** [comment]
@dg0yt I will fix it today. :)

**Pull request merged**
